MLIR: lib/Dialect/LLVMIR/Transforms/AddComdats.cpp File Reference
AddComdats.cpp File Reference
#include "mlir/Dialect/LLVMIR/Transforms/AddComdats.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Dialect/LLVMIR/Transforms/Passes.h.inc"
Classes
class mlir::LLVM::impl::LLVMAddComdatsBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::LLVM
namespace mlir::LLVM::impl
Macros
#define GEN_PASS_DEF_LLVMADDCOMDATS
Functions
std::unique_ptr<::mlir::Pass > mlir::LLVM::impl::createLLVMAddComdats ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMAddComdats ()
static void addComdat (LLVM::LLVMFuncOp &op, OpBuilder &builder, SymbolTable &symbolTable, ModuleOp &module)
Macro Definition Documentation
GEN_PASS_DEF_LLVMADDCOMDATS
#define GEN_PASS_DEF_LLVMADDCOMDATS
Definition at line 15 of file AddComdats.cpp.
Function Documentation
addComdat()
void addComdat (LLVM::LLVMFuncOp & op, OpBuilder & builder, SymbolTable & symbolTable, ModuleOp & module) static
Definition at line 22 of file AddComdats.cpp.
References mlir::FlatSymbolRefAttr::get(), mlir::Builder::getContext(), mlir::SymbolTable::insert(), mlir::SymbolTable::lookup(), and mlir::OpBuilder::setInsertionPointToStart().