MLIR: lib/Dialect/Affine/Transforms/AffineScalarReplacement.cpp File Reference
AffineScalarReplacement.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/SmallPtrSet.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "memref-dataflow-opt"
Functions
template<typename EffectType , typename T >
bool hasNoInterveningEffect (Operation *start, T memOp)
Ensure that all operations that could be executed after start (noninclusive) and prior to memOp (e.g.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memref-dataflow-opt"
Definition at line 29 of file AffineScalarReplacement.cpp.
Function Documentation
hasNoInterveningEffect()
template<typename EffectType , typename T > bool hasNoInterveningEffect (Operation * start, T memOp)
Ensure that all operations that could be executed after start (noninclusive) and prior to memOp (e.g.
on a control flow/op path between the operations) do not have the potential memory effect EffectType on memOp. memOp is an operation that reads or writes to a memref. For example, if EffectType is MemoryEffects::Write, this method will check if there is no write to the memory between start and memOp that would change the read within memOp.
Definition at line 95 of file AffineScalarReplacement.cpp.
References mlir::checkMemrefAccessDependence(), mlir::DominanceInfo::dominates(), mlir::Block::end(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::AffineReadOpInterface::getMemRef(), mlir::AffineWriteOpInterface::getMemRef(), mlir::getNumCommonSurroundingLoops(), mlir::OpState::getOperation(), mlir::Operation::getParentOp(), mlir::Operation::getParentRegion(), mlir::Region::getParentRegion(), mlir::Operation::getRegions(), mlir::Block::getSuccessors(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::AffineReadOpInterface::getValue(), mlir::hasDependence(), mlir::Operation::hasTrait(), mlir::Operation::isAncestor(), mlir::Region::isAncestor(), mlir::MemRefAccess::memref, op, mlir::PostDominanceInfo::postDominates(), mlir::Value::replaceAllUsesWith(), and mlir::success().