MLIR: lib/Dialect/SCF/Utils/AffineCanonicalizationUtils.cpp File Reference
AffineCanonicalizationUtils.cpp File Reference
#include <utility>
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Utils/AffineCanonicalizationUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/PatternMatch.h"
Macros
#define DEBUG_TYPE "mlir-scf-affine-utils"
Functions
static FailureOr< AffineApplyOp > canonicalizeMinMaxOp (RewriterBase &rewriter, Operation *op, FlatAffineValueConstraints constraints)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-scf-affine-utils"
Definition at line 25 of file AffineCanonicalizationUtils.cpp.
Function Documentation
canonicalizeMinMaxOp()
static FailureOr<AffineApplyOp> canonicalizeMinMaxOp (RewriterBase & rewriter, Operation * op, FlatAffineValueConstraints constraints) static
Definition at line 65 of file AffineCanonicalizationUtils.cpp.
References mlir::Operation::getOperands(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), and mlir::affine::simplifyConstrainedMinMaxOp().
Referenced by mlir::scf::canonicalizeMinMaxOpInLoop(), and mlir::scf::rewritePeeledMinMaxOp().