MLIR: lib/Dialect/Affine/Analysis/AffineAnalysis.cpp File Reference
AffineAnalysis.cpp File Reference
#include "mlir/Dialect/Affine/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/Presburger/IntegerRelation.h"
#include "mlir/Analysis/Presburger/PresburgerSpace.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Macros
#define DEBUG_TYPE "affine-analysis"
Functions
static Value getSupportedReduction (AffineForOp forOp, unsigned pos, arith::AtomicRMWKind &kind)
Get the value that is being reduced by pos-th reduction in the loop if such a reduction can be performed by affine parallel loops.
for (Operation *op :ops)
return success ()
static LogicalResult getOpIndexSet (Operation *op, FlatAffineValueConstraints *indexSet)
Computes the iteration domain for 'op' and populates 'indexSet', which encapsulates the constraints involving loops surrounding 'op' and potentially involving any Function symbols. The dimensional variables in 'indexSet' correspond to the loops surrounding 'op' from outermost to innermost.
static unsigned getNumCommonLoops (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, SmallVectorImpl< AffineForOp > *commonLoops=nullptr)
static Block * getCommonBlockInAffineScope (Operation *opA, Operation *opB)
Returns the closest surrounding block common to opA and opB. opA and opB should be in the same affine scope. Returns nullptr if such a block does not exist (when the two ops are in different blocks of an op starting an AffineScope).
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess)
Returns true if the ancestor operation of 'srcAccess' appears before the ancestor operation of 'dstAccess' in their common ancestral block. The operations for srcAccess and dstAccess are expected to be in the same affine scope and have a common surrounding block within it.
static void addOrderingConstraints (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, unsigned loopDepth, IntegerRelation *dependenceDomain)
static void computeDirectionVector (const FlatAffineValueConstraints &srcDomain, const FlatAffineValueConstraints &dstDomain, unsigned loopDepth, IntegerPolyhedron *dependenceDomain, SmallVector< DependenceComponent, 2 > *dependenceComponents)
Variables
indices
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-analysis"
Definition at line 29 of file AffineAnalysis.cpp.
Function Documentation
addOrderingConstraints()
void addOrderingConstraints (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, unsigned loopDepth, IntegerRelation * dependenceDomain) static
Definition at line 382 of file AffineAnalysis.cpp.
References mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::addInequality(), mlir::presburger::IntegerRelation::getNumCols(), getNumCommonLoops(), and mlir::presburger::IntegerRelation::getNumDimVars().
Referenced by mlir::affine::checkMemrefAccessDependence().
computeDirectionVector()
void computeDirectionVector (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, unsigned loopDepth, IntegerPolyhedron * dependenceDomain, SmallVector< DependenceComponent, 2 > * dependenceComponents) static
Definition at line 408 of file AffineAnalysis.cpp.
References mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::getConstantBound64(), mlir::presburger::IntegerRelation::getNumCols(), getNumCommonLoops(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumVars(), mlir::presburger::IntegerPolyhedron::insertVar(), and mlir::presburger::IntegerRelation::projectOut().
Referenced by mlir::affine::checkMemrefAccessDependence().
for()
for (Operation *op :ops)
Definition at line 264 of file AffineAnalysis.cpp.
References mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::affine::FlatAffineValueConstraints::addAffineIfOpDomain(), and mlir::affine::FlatAffineValueConstraints::addAffineParallelOpDomain().
Referenced by mlir::tblgen::FmtStrVecObject::FmtStrVecObject(), mlir::tblgen::FmtStrVecObject::FmtStrVecObject(), mlir::presburger::FracMatrix::FracMatrix(), mlir::tblgen::Pass::Pass(), PrivateVarsInfo::PrivateVarsInfo(), mlir::presburger::SetCoalescer::SetCoalescer(), mlir::spirv::TargetEnv::TargetEnv(), and mlir::tosa::ValueKnowledge::ValueKnowledge().
getCommonBlockInAffineScope()
Block * getCommonBlockInAffineScope (Operation * opA, Operation * opB) static
Returns the closest surrounding block common to opA and opB. opA and opB should be in the same affine scope. Returns nullptr if such a block does not exist (when the two ops are in different blocks of an op starting an AffineScope).
Definition at line 320 of file AffineAnalysis.cpp.
References mlir::Operation::getBlock(), mlir::Block::getParentOp(), and mlir::Operation::hasTrait().
Referenced by mlir::affine::checkMemrefAccessDependence(), and srcAppearsBeforeDstInAncestralBlock().
getNumCommonLoops()
unsigned getNumCommonLoops (const FlatAffineValueConstraints & srcDomain, const FlatAffineValueConstraints & dstDomain, SmallVectorImpl< AffineForOp > * commonLoops = nullptr) static
Definition at line 293 of file AffineAnalysis.cpp.
References mlir::affine::getForInductionVarOwner(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::FlatLinearValueConstraints::getValue(), mlir::affine::isAffineForInductionVar(), and mlir::affine::isAffineParallelInductionVar().
Referenced by addOrderingConstraints(), mlir::affine::checkMemrefAccessDependence(), and computeDirectionVector().
getOpIndexSet()
LogicalResult getOpIndexSet (Operation * op, FlatAffineValueConstraints * indexSet) static
Computes the iteration domain for 'op' and populates 'indexSet', which encapsulates the constraints involving loops surrounding 'op' and potentially involving any Function symbols. The dimensional variables in 'indexSet' correspond to the loops surrounding 'op' from outermost to innermost.
Definition at line 283 of file AffineAnalysis.cpp.
References mlir::affine::getEnclosingAffineOps(), and mlir::affine::getIndexSet().
Referenced by mlir::affine::MemRefAccess::getAccessRelation().
getSupportedReduction()
Value getSupportedReduction (AffineForOp forOp, unsigned pos, arith::AtomicRMWKind & kind) static
Get the value that is being reduced by pos-th reduction in the loop if such a reduction can be performed by affine parallel loops.
This assumes floating-point operations are commutative. On success, kind will be the reduction kind suitable for use in affine parallel loop builder. If the reduction is not supported, returns null.
Definition at line 40 of file AffineAnalysis.cpp.
References mlir::matchReduction().
Referenced by mlir::affine::getSupportedReductions().
srcAppearsBeforeDstInAncestralBlock()
bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess) static
Returns true if the ancestor operation of 'srcAccess' appears before the ancestor operation of 'dstAccess' in their common ancestral block. The operations for srcAccess and dstAccess are expected to be in the same affine scope and have a common surrounding block within it.
Definition at line 356 of file AffineAnalysis.cpp.
References mlir::Block::findAncestorOpInBlock(), getCommonBlockInAffineScope(), mlir::Operation::isBeforeInBlock(), and mlir::affine::MemRefAccess::opInst.
Referenced by mlir::affine::checkMemrefAccessDependence().
success()
return success ()
Referenced by mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::affine::FlatAffineValueConstraints::addAffineParallelOpDomain(), mlir::FlatLinearConstraints::addBound(), mlir::affine::FlatAffineValueConstraints::addDomainFromSliceMaps(), mlir::affine::FlatAffineValueConstraints::addInductionVarOrTerminalSymbol(), addInitOperandsToLoopNest(), mlir::SimpleAffineExprFlattener::addLocalIdSemiAffine(), addMissingLoopIVBounds(), addShardOp(), addShardOp(), mlir::affine::FlatAffineValueConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), mlir::AsmParser::addTypesToList(), mlir::AsmParser::addTypeToList(), mlir::xegpu::addVectorTypeConversion(), mlir::affine::affineForOpBodySkew(), mlir::affine::affineParallelize(), alignedConversionPrecondition(), allocAndInitializeReductionVars(), mlir::arm_sme::allocateSMETiles(), allocReductionVars(), mlir::LLVMTranslationInterface::amendOperation(), amendOperationImpl(), mlir::bufferization::analyzeModuleOp(), mlir::bufferization::analyzeOp(), mlir::bufferization::OneShotAnalysisState::analyzeOp(), analyzeProfitability(), mlir::bufferization::OneShotAnalysisState::analyzeSingleOp(), appendMangledType(), mlir::NVVM::SerializeGPUModuleBase::appendStandardLibs(), mlir::ROCDL::SerializeGPUModuleBase::appendStandardLibs(), mlir::transform::detail::appendValueMappings(), mlir::PassReproducerOptions::apply(), applyConversion(), mlir::OperationConverter::applyConversion(), applyFuse(), mlir::applyOpPatternsGreedily(), mlir::applyPassManagerCLOptions(), applyTile(), applyTilingToAll(), mlir::transform::applyTransforms(), applyUnrollHeuristic(), areAllLLVMTypes(), mlir::transform::detail::assembleTransformLibraryFromPaths(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::attachOpTrait(), bufferizableInPlaceAnalysisImpl(), mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::bufferization::func_ext::ReturnOpInterface::bufferize(), mlir::bufferization::bufferizeBlockSignature(), mlir::bufferization::bufferizeModuleOp(), mlir::bufferization::bufferizeOp(), mlir::affine::AffineValueMap::canonicalize(), canonicalizeAssociativeCommutativeBinaryOp(), canonicalizeLoopBounds(), checkAffineLoopNestMappable(), checkAffineLoopNestMappableImpl(), checkAndUpdateCapabilityRequirements(), checkAndUpdateExtensionRequirements(), mlir::transform::detail::checkApplyToOne(), checkAssumptionForFusingConsumer(), ValueEquivalenceCache::checkCommutativeEquivalent(), checkCorrectAnyOf(), checkDataOperands(), checkDeclareOperands(), checkDoubleConsume(), ValueEquivalenceCache::checkEquivalent(), TosaProfileCompliance::checkExtension(), mlir::shard::checkFullyAnnotated(), mlir::shard::checkFullyAnnotated(), checkFunctionTypeCompatibility(), checkGlobalXtorData(), checkIfHyperRectangular(), checkImplementationStatus(), TosaProfileCompliance::checkInvalid(), mlir::transform::detail::checkNestedConsumption(), checkNoModifier(), checkOperandAffineExprRecursively(), checkPreBufferizationAssumptions(), mlir::checkPreconditions(), checkPrivateOperands(), TosaProfileCompliance::checkProfile(), TosaProfileCompliance::checkProfileOrExtension(), checkRecipe(), checkSourceOpTypes(), checkSymbolIsTypeOrAttribute(), checkTensorElementType(), checkTileSizes(), checkTransformationPreconditions(), checkValidModifier(), checkVarAndAccVar(), checkVarAndVarType(), checkWaitAndAsyncConflict(), mlir::impl::ArithToLLVMConversionPassBase< DerivedT >::classof(), cleanupPrivateVars(), mlir::impl::ConvertLinalgToParallelLoopsPassBase< DerivedT >::clonePass(), mlir::coalesceLoops(), mlir::coalescePerfectlyNestedSCFForLoops(), collapseBranch(), collectAndValidateTaskloopRedDecls(), collectStage0PipeliningOps(), collectValidReferencesFor(), combineOneSpec(), commonConversionPrecondition(), mlir::linalg::commonVerifierPackAndUnPackOp(), mlir::FlatLinearConstraints::composeMatchingMap(), mlir::affine::MemRefRegion::compute(), mlir::ValueBoundsConstraintSet::computeBound(), computeExpandedSliceInfoForReassocGroup(), mlir::FlatLinearConstraints::computeLocalVars(), computeReachableValuesFromSuccessorInput(), mlir::detail::ExpectedDiag::computeRegex(), mlir::AffineMap::constantFold(), mlir::presburger::IntegerRelation::constantFoldVar(), mlir::OperationConverter::convert(), convertAcoshOp(), convertAffineLoopNestToGPULaunch(), mlir::LLVM::ModuleImport::convertAliases(), convertAllocateDirOp(), convertAllocateFreeOp(), convertAllocSharedMemOp(), mlir::LLVM::ModuleTranslation::convertArgAndResultAttrs(), convertAsinhOp(), convertAtanhOp(), convertBroadcastOp(), convertCallBaseAttributes(), mlir::LLVMTypeConverter::convertCallingConventionType(), convertCallLLVMIntrinsicOp(), convertCastingOp(), convertCeilOp(), convertClampfOp(), mlir::LLVM::ModuleImport::convertComdats(), mlir::LLVM::ModuleImport::convertCommandlineMetadata(), convertConstantOp(), convertConstantOpMmaSync(), convertContractOp(), convertContractOpToMmaSync(), convertCoshOp(), convertCtlzOp(), mlir::LLVM::ModuleImport::convertDataLayout(), convertDataOp(), convertDeclareTargetAttr(), convertDenseArrayFromAttr(), convertDenseArrayFromAttr(), mlir::LLVM::ModuleImport::convertDependentLibrariesMetadata(), convertElementwiseOp(), convertExp2fOp(), convertExtractStridedSlice(), convertFlagsAttr(), mlir::detail::convertFloatTypeFromAttribute(), convertFmaFOp(), convertForOp(), convertFPowIOp(), convertFreeSharedMemOp(), mlir::convertFromAttribute(), mlir::convertFromAttribute(), mlir::convertFromAttribute(), mlir::convertFromAttribute(), mlir::convertFromAttribute(), mlir::convertFromAttribute(), convertFuncOpTypes(), mlir::LLVM::ModuleImport::convertFunctions(), mlir::LLVM::ModuleImport::convertGlobals(), mlir::LLVM::ModuleImport::convertIdentMetadata(), mlir::LLVM::ModuleImport::convertIFuncs(), mlir::LLVM::ModuleImport::convertIntrinsicArguments(), convertIteratorType(), convertIterSpaceType(), mlir::LLVM::ModuleImport::convertLinkerOptionsMetadata(), mlir::LLVM::ModuleImport::convertMetadata(), mlir::LLVM::ModuleImport::convertModuleFlagsMetadata(), convertOmpAtomicCapture(), convertOmpAtomicCompare(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), convertOmpAtomicWrite(), convertOmpCancel(), convertOmpCancellationPoint(), convertOmpCanonicalLoopOp(), convertOmpCritical(), convertOmpDistribute(), convertOmpGroupprivate(), convertOmpLoopNest(), convertOmpMasked(), convertOmpMaster(), convertOmpOrdered(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSections(), convertOmpSingle(), convertOmpTarget(), convertOmpTargetData(), convertOmpTaskgroupOp(), convertOmpTaskloopContextOp(), convertOmpTaskloopWrapperOp(), convertOmpTaskOp(), convertOmpTaskwaitOp(), convertOmpTeams(), convertOmpThreadprivate(), convertOperationImpl(), convertParameterAttr(), mlir::LLVMTranslationInterface::convertParameterAttr(), convertPowfOp(), convertProfileSummaryModuleFlagValue(), convertRoundEvenOp(), convertRoundOp(), convertRsqrtOp(), convertSinhOp(), convertSparseTensorType(), convertStandaloneDataOp(), convertTanhOp(), convertTanOp(), convertTargetAllocMemOp(), convertTargetFreeMemOp(), convertTransferReadOp(), convertTransferWriteOp(), convertTransferWriteToStores(), mlir::convertVectorToNVVMCompatibleMMASync(), convertYieldOp(), copyFirstPrivateVars(), mlir::linalg::copyToGPUPrivateMemory(), mlir::linalg::copyToWorkgroupMemory(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), cpAsyncBulkTensorCommonVerifier(), mlir::createConvertAsyncToLLVMPass(), createDirectoryOrPrintErr(), mlir::memref::createFoldMemRefAliasOpsPass(), createFullTiles(), mlir::createGpuAsyncRegionPass(), mlir::createGpuKernelOutliningPass(), mlir::spirv::Deserializer::createGraphBlock(), mlir::createMem2Reg(), createNonLdMatrixLoads(), mlir::LLVM::createPrintStrCall(), createReductionsAndCleanup(), mlir::ControlFlowToSCFTransformation::createStructuredBranchRegionTerminatorOp(), mlir::xegpu::createXeGPUWgToSgDistribute(), creatLdMatrixCompatibleLoads(), mlir::linalg::deallocateGPUPrivateMemory(), mlir::linalg::deallocateWorkgroupMemory(), mlir::LLVM::decomposeValue(), mlir::shard::detail::defaultAddShardingAnnotations(), defaultDeallocBufferCallBack(), ContractOpToElementwise::defaultFilter(), mlir::detail::defaultMatcherFn(), deleteDeadness(), deserializeCacheControlDecoration(), mlir::spirv::Deserializer::processOp< spirv::CopyMemoryOp >(), mlir::spirv::Deserializer::processOp< spirv::EntryPointOp >(), mlir::spirv::Deserializer::processOp< spirv::ExecutionModeIdOp >(), mlir::spirv::Deserializer::processOp< spirv::ExecutionModeOp >(), mlir::spirv::Deserializer::processOp< spirv::FunctionCallOp >(), mlir::spirv::Deserializer::processOp< spirv::GenericCastToPtrExplicitOp >(), VulkanRuntime::destroy(), dispatchParse(), mlir::Inliner::doInlining(), doVerifyRoundTrip(), doVerifyRoundTrip(), dropRedundantArguments(), dropRedundantArguments(), dropRefIfNoUses(), dropSwitchCasesThatMatchDefault(), effectMightAffectAddressSpaces(), mlir::bufferization::eliminateEmptyTensors(), llvm::embedBinaryImpl(), emit(), emitAddressOfWithConstCast(), emitElementwiseComputation(), emitSwitchCase(), encodeKernelName(), mlir::tosa::EqualizeRanks(), eraseRedundantGpuBarrierOps(), eraseRedundantLDSBarrierOps(), mlir::eraseUnreachableBlocks(), errorIfShapeNotSizeOne(), errorIfTypeOrShapeMismatch(), errorIfTypeOrShapeMismatch(), mlir::OperationEquivalence::exactValueMatch(), mlir::transform::detail::expandPathsToMLIRFiles(), extractStrides(), mlir::spirv::extractValueFromConstOp(), mlir::failableParallelForEach(), mlir::BytecodeReader::Impl::finalize(), mlir::detail::OpPassManagerImpl::finalizePassList(), mlir::FlatLinearConstraints::flattenAlignedMapAndMergeLocals(), mlir::Operation::fold(), foldBroadcastOfShapeCast(), mlir::impl::foldCastInterfaceOp(), mlir::OpTrait::impl::foldCommutative(), foldCopyOfCast(), mlir::foldDynamicIndexList(), foldExtractOpFromExtractChain(), foldExtractStridedOpFromInsertChain(), foldGlobalLoadAsyncToLDSConstantMask(), foldIdentityOffsetSizeAndStrideOpInterface(), foldInsertAfterInsertSlice(), mlir::memref::foldMemRefCast(), foldSize1TransferPermutationMap(), mlir::tensor::foldTensorCast(), mlir::bufferization::foldToBufferToTensorPair(), foldToElementsFromElements(), foldToElementsOfBroadcast(), mlir::op_definition_impl::foldTrait(), mlir::op_definition_impl::foldTraits(), foldTransferFullMask(), foldTransferInBoundsAttribute(), mlir::presburger::IntegerRelation::gaussianEliminateVar(), generalizeNamedOpPrecondition(), generateCleanupLoopForUnroll(), generateCopy(), generateLocationsFromIR(), generateLoopNestUsingForOp(), generateTypeInclude(), mlir::OpState::genericParseProperties(), genForeachOnSparseConstant(), mlir::affine::MemRefAccess::getAccessRelation(), mlir::detail::getAffineMapStridesAndOffset(), getAllocEffectFor(), mlir::affine::ComputationSliceState::getAsConstraints(), getBackwardSliceImpl(), mlir::tensor::getCollapsedExtractSliceInfo(), mlir::AsmParser::getCurrentLocation(), getDefaultABIAttrs(), mlir::arm_sme::impl::VectorLegalizationBase< DerivedT >::getDependentDialects(), mlir::impl::GpuAsyncRegionPassBase< DerivedT >::getDependentDialects(), mlir::impl::ReductionTreePassBase< DerivedT >::getDependentDialects(), mlir::impl::SCFForLoopCanonicalizationBase< DerivedT >::getDependentDialects(), getDivRepr(), getDivRepr(), mlir::tensor::getExpandedExtractSliceInfo(), getFlattenedAffineExprs(), mlir::getFlattenedAffineExprs(), mlir::getFlattenedAffineExprs(), getFuncOpsOrderedByCalls(), mlir::transform::TransformState::getHandlesForPayloadOp(), mlir::transform::TransformState::getHandlesForPayloadValue(), getInterfaceVariables(), getKernelGlobalVariables(), getMemRefAlignment(), mlir::bufferization::DeallocationState::getMemrefsAndConditionsToDeallocate(), mlir::getMultiAffineFunctionFromMap(), mlir::tensor::getOrCreateDestinations(), mlir::affine::getRelationFromMap(), mlir::affine::getRelationFromMap(), getSegmentSizes(), getSegmentSizesFromAttr(), mlir::shape::getShapeVec(), getShmReadAndWriteOps(), mlir::affine::ComputationSliceState::getSourceAsConstraints(), ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::getSpatialParameters(), ConvInferShapeAdaptor< Conv2DOp::Adaptor >::getSpatialParameters(), ConvInferShapeAdaptor< Conv3DOp::Adaptor >::getSpatialParameters(), getStridesAndOffset(), getTileSizePos(), getVectorAlignment(), getVectorToLLVMAlignment(), mlir::LLVM::ModuleToObject::handleBitcodeFile(), mlir::ROCDL::SerializeGPUModuleBase::handleBitcodeFile(), handleError(), handleError(), mlir::LLVM::detail::handleMultidimensionalVectors(), hasBufferAddressSpace(), hoistOpsBetween(), mlir::OperationEquivalence::ignoreValueEquivalence(), incSlicePosition(), inferConvReturnTypeComponents(), inferMBarrierArriveResultTypes(), inferOperationTypes(), mlir::detail::inferReturnTensorTypes(), inferSideEffectAnnotations(), inferSparseBufferType(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::initialize(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::initialize(), mlir::ExternalPass::initialize(), mlir::Pass::initialize(), mlir::ReductionNode::initialize(), mlir::remark::detail::RemarkEngine::initialize(), mlir::DataFlowSolver::initializeAndRun(), mlir::LLVMImportInterface::initializeImport(), mlir::Pass::initializeOptions(), VulkanRuntime::initRuntime(), VectorizationState::initState(), mlir::sparse_tensor::CodegenEnv::initTensorExp(), mlir::inlineCall(), inlineConvertOmpRegions(), inlineOmpRegionCleanup(), inlinePayload(), mlir::Inliner::Impl::inlineSCC(), insertCasts(), mlir::bufferization::insertTensorCopies(), mlir::NVVM::PtxBuilder::insertValue(), interchangeGenericOpPrecondition(), interleaveWithError(), mlir::LLVM::detail::intrinsicRewrite(), irdlAttrOrTypeVerifier(), irdlOpVerifier(), irdlRegionVerifier(), isAllowedSizeM(), isAllowedSizeN(), isAllowedSizeN(), isAllowedWGMMADataType(), isAllowedWGMMADataType(), isArrayOf(), isAsyncWithOneDependency(), isCmpIConvertable(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isIntegerArrayAttrSmallerThanShape(), isMatchingWidth(), isMemRefTypeSupported(), isScaleInExpressedTypeRange(), isSumOfIntegerArrayAttrConfinedToShape(), isValidContiguity(), isValidGatherScatterBufferParams(), mlir::vector::isValidMaskedInputVector(), IsValidMatrixOpParams(), isValidName(), legalizeBlockArguments(), mlir::OperationConverter::legalizeOperations(), legalizeUnresolvedMaterialization(), mlir::linalg::linalgOpAnchoredEmptyTensorEliminationStep(), mlir::LLVM::ModuleToObject::linkFiles(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::LLVM::ModuleToObject::loadBitcodeFilesFromList(), mlir::irdl::loadDialects(), lookupSymbolInImpl(), mlir::affine::loopUnrollByFactor(), mlir::affine::loopUnrollFull(), mlir::loopUnrollFull(), mlir::affine::loopUnrollJamByFactor(), mlir::loopUnrollJamByFactor(), mlir::affine::lowerAffineDelinearizeIndexOp(), mlir::affine::lowerAffineLinearizeIndexOp(), lvlIsInBounds(), mlir::transform::TransformState::mapBlockArguments(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), matchAndReplaceDepthwiseConv(), AllocaScopeHoister::matchAndRewrite(), AllocaScopeInliner::matchAndRewrite(), ArithmeticExtendedBinaryFold< spirv::IAddCarryOp >::matchAndRewrite(), AssertOpLowering::matchAndRewrite(), AvgPool2dAdaptiveToAvgPool2d::matchAndRewrite(), AvgPool2dIsNoOp::matchAndRewrite(), BreakDownVectorReduction::matchAndRewrite(), CancellingBlockScaledCastsOptimization::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), CanonicalizeContractMatmulToMMT::matchAndRewrite(), ChainedReduction::matchAndRewrite(), ClampClampOptimization::matchAndRewrite(), ClampFOpConversion::matchAndRewrite(), ClampIsNoOp::matchAndRewrite(), CmpFIntToFPConst::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), ConcatOptimization::matchAndRewrite(), ConcatSliceOptimization::matchAndRewrite(), ConsecutiveConcatOptimization::matchAndRewrite(), ConsolidateTransposeOptimization::matchAndRewrite(), Convert1DExtractStridedSliceIntoExtractInsertChain::matchAndRewrite(), Convert1DExtractStridedSliceIntoShuffle::matchAndRewrite(), ConvertAccessChain::matchAndRewrite(), ConvertAddressOf::matchAndRewrite(), ConvertFsubToFnegFadd::matchAndRewrite(), ConvertNativeFuncPattern< Op >::matchAndRewrite(), ConvertSameRankInsertStridedSliceIntoShuffle::matchAndRewrite(), ConvertStore::matchAndRewrite(), ConvertVariable::matchAndRewrite(), DecomposeDifferentRankInsertStridedSlice::matchAndRewrite(), DecomposeNDExtractStridedSlice::matchAndRewrite(), DropUnitDimFromElementwiseOps::matchAndRewrite(), DropUnitDimsFromScfForOp::matchAndRewrite(), DropUnitDimsFromTransposeOp::matchAndRewrite(), ExpandShapeOpMemRefCastFolder::matchAndRewrite(), FmaOpToAPFloatConversion::matchAndRewrite(), FoldAddIntoDest::matchAndRewrite(), FoldArithExtIntoContractionOp< ExtOp >::matchAndRewrite(), FoldBroadcasts::matchAndRewrite(), FoldBroadcastSplatConstant::matchAndRewrite(), FoldLaunchArguments::matchAndRewrite(), FoldTensorCastProducerOp::matchAndRewrite(), FoldTransposeSplatConstant::matchAndRewrite(), FoldTransposeWithTranspose::matchAndRewrite(), GPUAllReduceConversion::matchAndRewrite(), GPUSubgroupReduceConversion::matchAndRewrite(), IndexSwitchOpLowering::matchAndRewrite(), InsertSliceOfInsertSliceFolder< OpTy >::matchAndRewrite(), MaxPool2dAdaptiveToMaxPool2d::matchAndRewrite(), MaxPool2dIsNoOp::matchAndRewrite(), MergeArithBitcast::matchAndRewrite(), MergeComplexBitcast::matchAndRewrite(), MergeConsecutiveExtractSlice::matchAndRewrite(), mlir::acc::ACCDeclareEnterOpConversion::matchAndRewrite(), mlir::acc::ACCOpEraseConversion< OpTy >::matchAndRewrite(), mlir::acc::ACCOpReplaceWithVarConversion< OpTy >::matchAndRewrite(), mlir::acc::ACCRegionUnwrapConversion< OpTy >::matchAndRewrite(), mlir::ComposeCollapseOfExpandOp< CollapseOpTy, ExpandOpTy, CastOpTy, DimOpTy, TensorTy >::matchAndRewrite(), mlir::ComposeExpandOfCollapseOp< ExpandOpTy, CollapseOpTy, CastOpTy >::matchAndRewrite(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::GPUDynamicSharedMemoryOpLowering::matchAndRewrite(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), mlir::GPUPrintfOpToVPrintfLowering::matchAndRewrite(), mlir::GPUReturnOpLowering::matchAndRewrite(), mlir::linalg::DecomposeOuterUnitDimsPackOpPattern::matchAndRewrite(), mlir::linalg::DecomposeOuterUnitDimsUnPackOpPattern::matchAndRewrite(), mlir::linalg::DecomposePadOpPattern::matchAndRewrite(), mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite(), mlir::linalg::FoldTensorCastPackOp::matchAndRewrite(), mlir::linalg::FoldTensorCastUnPackOp::matchAndRewrite(), mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite(), mlir::math::ErfcPolynomialApproximation::matchAndRewrite(), mlir::math::ErfPolynomialApproximation::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::OpWithOffsetSizesAndStridesConstantArgumentFolder< OpType, ResultTypeFn, CastOpFunc >::matchAndRewrite(), mlir::spirv::ElementwiseOpPattern< Op, SPIRVOp >::matchAndRewrite(), MulExtendedFold< spirv::SMulExtendedOp, true >::matchAndRewrite(), MultiBlockExecuteInliner::matchAndRewrite(), NonNarrowingCastsOptimization::matchAndRewrite(), OuterProductOpLowering::matchAndRewrite(), PadSliceOptimization::matchAndRewrite(), ReduceRedundantZero::matchAndRewrite(), RemoveUnusedLvlCrds::matchAndRewrite(), RowGatherToGather::matchAndRewrite(), SelectToExtUI::matchAndRewrite(), SincosOpLowering::matchAndRewrite(), SinkVectorProducerOps< producerOp >::matchAndRewrite(), SliceDynamicSizeCanonicalization::matchAndRewrite(), SortCommutativeOperands::matchAndRewrite(), SpecifierGetterSetterOpConverter< Base, SourceOp >::matchAndRewrite(), StorageSpecifierInitOpConverter::matchAndRewrite(), SwapExtractSliceOfFill::matchAndRewrite(), SwapTransposeWithBroadcast::matchAndRewrite(), ToElementsOfBroadcast::matchAndRewrite(), TransposeIsReshape::matchAndRewrite(), TransposeOpLowering::matchAndRewrite(), UModSimplification::matchAndRewrite(), UMulExtendedOpXOne::matchAndRewrite(), VectorContractBF16ToFMA::matchAndRewrite(), WhileLowering::matchAndRewrite(), YieldOpLowering::matchAndRewrite(), matchAndRewriteSortOp(), mlir::LLVM::ModuleImport::matchFloatAttr(), mlir::scf::matchForLikeLoop(), mlir::LLVM::ModuleImport::matchIntegerAttr(), mlir::BytecodeReader::Impl::materializeAll(), mlir::dataflow::maybeReplaceWithConstant(), memcpyEnsureOnlySafeAccesses(), mergeIdenticalBlocks(), mergeIdenticalBlocks(), mergeInto(), mlir::affine::mergeOffsetsSizesAndStrides(), mlir::transform::detail::mergeSymbolsInto(), mlirExecutionEngineInvokePacked(), mlir::MlirOptMain(), mlir::mlirReduceMain(), mlir::moveOperationDependencies(), mlir::presburger::LexSimplexBase::moveRowUnknownToColumn(), mlir::moveValueDefinitions(), mlir::LLVM::detail::LLVMStructTypeStorage::mutate(), mlir::spirv::detail::StructTypeStorage::mutate(), NAryInferReturnTypes(), nextIndex(), mlir::LLVM::detail::oneToOneRewrite(), mlir::LLVM::ModuleToObject::optimizeModule(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), mlir::outlineIfOp(), mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl(), mlir::parallelForEach(), mlir::DynamicAttr::parse(), mlir::DynamicType::parse(), mlir::FieldParser< ContainerT, std::enable_if_t< llvm::is_detected< detail::has_push_back_t, ContainerT >::value, ContainerT > >::parse(), parseAccVar(), mlir::detail::Parser::parseAffineMapReference(), parseAlignedClause(), parseAllReduceOperation(), parseAlternativesOpSelectedRegion(), parseApplyRegisteredPassOptions(), parseArithmeticExtendedBinaryOp(), mlir::detail::AsmParserImpl< BaseT >::parseArrowTypeList(), mlir::AsmParser::parseAttribute(), mlir::detail::AsmParserImpl< BaseT >::parseAttribute(), mlir::detail::Parser::parseAttribute(), mlir::detail::Parser::parseAttributeDict(), parseAttributesOp(), parseAttributions(), parseAttributions(), parseAwaitResultType(), mlir::detail::AsmParserImpl< BaseT >::parseBase64Bytes(), parseBlockSizeInfoUntilRBrace(), parseCachePolicy(), parseCachePolicyEnum(), mlir::detail::Parser::parseCallSiteLocation(), parseCallTypeAndResolveOperands(), parseClauseWithRegionArgs(), parseCmpOp(), mlir::AsmParser::parseColonType(), parseCombinedConstructsLoop(), mlir::detail::Parser::parseCommaSeparatedList(), mlir::detail::pass_options::parseCommaSeparatedList(), mlir::detail::pass_options::parseCommaSeparatedList(), mlir::detail::Parser::parseCommaSeparatedListUntil(), parseCommonGlobalAndAlias(), parseCommonStructuredOpParts(), parseContinuousTileSizeTypes(), mlir::spirv::parseControlAttribute(), parseCreateOperationOpAttributes(), parseCreateOperationOpResults(), mlir::AsmParser::parseCustomAttributeWithFallback(), mlir::detail::AsmParserImpl< BaseT >::parseCustomAttributeWithFallback(), mlir::AsmParser::parseCustomTypeWithFallback(), mlir::detail::AsmParserImpl< BaseT >::parseCustomTypeWithFallback(), parseDenseElementsAttrTyped(), parseDenseI64ArrayAttr(), parseDependVarList(), parseDeviceTypeArrayAttr(), parseDeviceTypeOperands(), parseDeviceTypeOperandsWithKeywordOnly(), parseDeviceTypeOperandsWithSegment(), parseDialectGrouping(), mlir::detail::Parser::parseDialectSymbolBody(), mlir::parseDimensionList(), mlir::detail::Parser::parseDimensionListRanked(), parseDstStyleOp(), mlir::parseDynamicIndexList(), parseElementAttrHexValues(), parseEmitCFieldOpTypeAndInitialValue(), parseEmitCGlobalOpTypeAndInitialValue(), mlir::spirv::parseEnumKeywordAttr(), mlir::spirv::parseEnumKeywordAttr(), mlir::spirv::parseEnumStrAttr(), mlir::spirv::parseEnumStrAttr(), parseExpressionArg(), parseExtTypeParams(), mlir::detail::AsmParserImpl< BaseT >::parseFloat(), mlir::detail::AsmParserImpl< BaseT >::parseFloat(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), mlir::detail::Parser::parseFloatFromLiteral(), parseForeachMatchSymbols(), parseFunctionArgumentList(), mlir::function_interface_impl::parseFunctionOp(), mlir::call_interface_impl::parseFunctionResultList(), mlir::detail::Parser::parseFunctionResultTypes(), mlir::call_interface_impl::parseFunctionSignature(), mlir::function_interface_impl::parseFunctionSignatureWithArguments(), parseFunctionTypes(), mlir::detail::Parser::parseFusedLocation(), parseGangClause(), parseGangValue(), parseGEPIndices(), parseGlobalMemrefOpTypeAndInitialValue(), mlir::spirv::parseImageOperands(), parseIndirectBrOpSucessors(), parseInsertExtractValueElementType(), mlir::detail::Parser::parseIntegerInDimensionList(), mlir::detail::Parser::parseIntegerSetReference(), parseIteratorHeader(), mlir::AsmParser::parseKeyword(), mlir::detail::AsmParserImpl< BaseT >::parseKeyword(), parseKeywordList(), mlir::detail::AsmParserImpl< BaseT >::parseKeywordOrCompletion(), mlir::AsmParser::parseKeywordOrString(), parseLaunchDimType(), parseLaunchFuncOperands(), parseLevelRange(), parseLevelRange(), parseLLVMLinkage(), mlir::detail::Parser::parseLocationInstance(), mlir::spirv::parseMemoryAccessAttributes(), mlir::detail::Parser::parseMemRefType(), parseMmaOperand(), parseMmaTypeSignature(), mlir::amdgpu::parseMNKDimensionList(), parseMultitileSizesTypes(), parseNamedStructuredOp(), parseNamedStructuredOpRegion(), parseNamedStructuredOpResults(), parseNamedValueListImpl(), mlir::detail::Parser::parseNameOrFileLineColRange(), parseNumGangs(), parseOffloadingHandler(), parseOneOpBundle(), parseOneResultSameOperandTypeOp(), parseOpBundles(), parseOperandsWithKeywordOnly(), parseOperandWithKeywordOnly(), parseOperationOpAttributes(), parseOptionalArrayStride(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalArrow(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalArrowTypeList(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDict(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDictWithKeyword(), mlir::detail::Parser::parseOptionalAttribute(), parseOptionalCallFuncPtr(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalColon(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalColonTypeList(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalComma(), mlir::AsmParser::parseOptionalDecimalInteger(), mlir::detail::Parser::parseOptionalDecimalInteger(), parseOptionalDefinedList(), mlir::ExtensibleDialect::parseOptionalDynamicAttr(), mlir::ExtensibleDialect::parseOptionalDynamicType(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalEllipsis(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalEqual(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalGreater(), mlir::detail::Parser::parseOptionalInteger(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword(), mlir::detail::Parser::parseOptionalKeyword(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeywordOrString(), mlir::detail::Parser::parseOptionalKeywordOrString(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLBrace(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLess(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLParen(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLSquare(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalMinus(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalPlus(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalQuestion(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalRBrace(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalRParen(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalRSquare(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalSlash(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalStar(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalString(), mlir::detail::Parser::parseOptionalString(), mlir::AsmParser::parseOptionalSymbolName(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalSymbolName(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalVerticalBar(), mlir::impl::parseOptionalVisibilityKeyword(), mlir::transform::parsePackedOrDynamicIndexList(), mlir::parsePassPipeline(), parseQuantParamListUntilRBrace(), parseQuantParams(), parseRangeType(), parseRangeType(), parseRecipeSym(), parseRegions(), parseResultsValueType(), parseRoutineGangClause(), parseSameOperandTypeVariadicToBoolOp(), mlir::parseSemiFunctionType(), mlir::parseSemiFunctionType(), parseSequenceOpOperands(), parseShuffleType(), parseSingleBlockRegion(), mlir::spirv::parseSourceMemoryAccessAttributes(), parseSparseCoIterateLoop(), parseSparseIterateLoop(), mlir::spirv::parseSPIRV_I32_1DArmTensor(), parseStorageRange(), mlir::AsmParser::parseString(), parseStructMemberDecorations(), parseStructType(), parseSwitchCases(), parseSwitchCases(), mlir::spirv::parseSwitchOpCases(), parseSwitchOpCases(), parseSwitchOpCases(), mlir::AsmParser::parseSymbolName(), mlir::AsmParser::parseSymbolName(), parseSymbolVisibility(), mlir::detail::Parser::parseToken(), parseTokenOrdering(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::transform::parseTransformMatchDims(), mlir::transform::detail::parseTransformModuleFromFile(), mlir::AsmParser::parseType(), parseTypeAndAttrList(), parseTypedInitialValue(), mlir::detail::Parser::parseTypeListNoParens(), mlir::detail::Parser::parseTypeListParens(), parseUsedCoordList(), parseValueWithVariadicity(), parseVar(), mlir::spirv::parseVariableDecorations(), parseVarPtrType(), mlir::detail::Parser::parseVectorDimensionList(), parseVerCapExtAttr(), parseWaitClause(), mlir::detail::Parser::parseXInDimensionList(), mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::partition(), mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >::partition(), mlir::shard::partitionBlock(), mlir::shard::partitionFuncOp(), mlir::shard::partitionOperation(), mlir::shard::partitionOperation(), mlir::shard::partitionOperation(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration(), performActions(), performPreTilingChecks(), poolingInferReturnTypes(), mlir::populateAMDGPUTypeAndAttributeConversions(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), ProfileInfoDepot::populateProfileInfo(), mlir::xegpu::populateXeGPUWgToSgDistributeTypeConversions(), preallocateAttrDefs(), preallocateTypeDefs(), mlir::DialectRegistry::preloadSelectDialects(), printBinaryOperation(), printCallOperation(), printConstantOp(), printFunctionBody(), mlir::ExtensibleDialect::printIfDynamicAttr(), mlir::ExtensibleDialect::printIfDynamicType(), printOpaqueCallCommon(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printRegisteredDialects(), printRegisteredPassesAndReturn(), printUnaryOperation(), mlir::spirv::Deserializer::processArrayType(), mlir::spirv::Deserializer::processBranch(), mlir::spirv::Deserializer::processBranchConditional(), processBuffer(), mlir::spirv::Deserializer::processConstant(), mlir::spirv::Deserializer::processConstantBool(), mlir::spirv::Deserializer::processConstantComposite(), mlir::spirv::Deserializer::processConstantCompositeReplicateEXT(), mlir::spirv::Deserializer::processConstantNull(), mlir::spirv::Deserializer::processCooperativeMatrixTypeKHR(), processDataOperands(), processDataOperands(), processDataOperands(), mlir::spirv::Deserializer::processDebugInfoExtInst(), mlir::spirv::Deserializer::processDebugLine(), mlir::spirv::Deserializer::processDebugString(), mlir::spirv::processDecorationList(), mlir::LLVM::ModuleImport::processFunction(), mlir::spirv::Deserializer::processFunctionEnd(), mlir::spirv::Deserializer::processFunctionType(), mlir::spirv::Deserializer::processGlobalVariable(), mlir::spirv::Deserializer::processGraphARM(), mlir::spirv::Deserializer::processGraphConstantARM(), mlir::spirv::Deserializer::processGraphEndARM(), mlir::spirv::Deserializer::processGraphEntryPointARM(), mlir::spirv::Deserializer::processGraphTypeARM(), mlir::spirv::Deserializer::processImageType(), mlir::spirv::Deserializer::processInstruction(), mlir::spirv::Deserializer::processLabel(), mlir::spirv::Deserializer::processLoopMerge(), mlir::spirv::Deserializer::processMatrixType(), mlir::spirv::Deserializer::processNamedBarrierType(), processOperands(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::processOperation(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::processOperation(), mlir::spirv::Deserializer::processOpGraphSetOutputARM(), mlir::spirv::Deserializer::processOpTypePointer(), mlir::spirv::Deserializer::processOpWithoutGrammarAttr(), processParallelLoop(), mlir::spirv::Deserializer::processPhi(), mlir::spirv::Deserializer::processRuntimeArrayType(), mlir::spirv::Deserializer::processSampledImageType(), mlir::spirv::Deserializer::processSamplerType(), mlir::spirv::Deserializer::processSelectionMerge(), mlir::spirv::Deserializer::processSpecConstantComposite(), mlir::spirv::Deserializer::processSpecConstantCompositeReplicateEXT(), mlir::spirv::Deserializer::processSpecConstantOperation(), mlir::spirv::Deserializer::processStructType(), mlir::spirv::Deserializer::processSwitch(), mlir::spirv::Deserializer::processTensorARMType(), mlir::spirv::Deserializer::processType(), mlir::spirv::Deserializer::processTypeForwardPointer(), mlir::spirv::Deserializer::processUndef(), produceSliceErrorMsg(), produceSubViewErrorMsg(), mlir::affine::promoteIfSingleIteration(), promoteSingleIterReductionLoop(), mlir::linalg::promoteSubviewsPrecondition(), mlir::xegpu::propagateLayouts(), mlir::detail::AsmParserImpl< BaseT >::pushCyclicParsing(), mlir::detail::AsmStateImpl::pushCyclicPrinting(), mlir::pdll::Lexer::pushInclude(), mlir::DialectBytecodeReader::readAttribute(), mlir::DialectBytecodeReader::readList(), mlir::DialectBytecodeReader::readOptionalAttribute(), mlir::readResourceHandle(), mlir::DialectBytecodeReader::readSparseArray(), mlir::DialectBytecodeReader::readType(), mlir::DialectBytecodeReader::readVarIntWithFlag(), ReduceInferReturnTypes(), reduceMatchAndRewriteHelper(), mlir::DiagnosticEngine::registerHandler(), mlir::registerIRDLToCppTranslation(), mlir::registerToLLVMIRTranslation(), registerTranslateToMLIRFunction(), reifyOpResultShapes(), ReifyCollapseShapeOp::reifyResultShapes(), mlir::linalg::reifyResultShapesImpl(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::SymbolTable::rename(), replaceAllSymbolUsesImpl(), replaceUsesAndPropagateType(), replaceWithConstant(), replaceWithLoadOrStore(), resolveBroadcastShape(), resolveEntry(), resolveOpBundleOperands(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::resolveOperands(), mlir::memref::resolveSourceIndicesRankReducingSubview(), mlir::linalg::rewriteAsPaddedOp(), rewriteFromElementsAsBroadcast(), VulkanRuntime::run(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runDenseBufferization(), mlir::bufferization::runOneShotBufferize(), mlir::bufferization::runOneShotModuleBufferize(), runTransformOnCGSCCs(), mlir::impl::scalarizeVectorOp(), mlir::spirv::Serializer::serialize(), mlir::spirv::Serializer::processOp<::mlir::spirv::AtomicISubOp >(), mlir::spirv::Serializer::processTypeDecoration< spirv::ArrayType >(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), setAccessGroupsAttr(), setAliasScopesAttr(), setDebugIntrinsicBuilderInsertionPoint(), setDereferenceableAttr(), mlir::spirv::Deserializer::setFunctionArgAttrs(), setIntelReqdSubGroupSizeAttr(), setLoopAttr(), mlir::transform::TransformResults::setMappedValues(), mlir::LLVMImportInterface::setMetadataAttrs(), setMmraAttr(), setNoaliasScopesAttr(), mlir::MlirOptMainConfig::setPassPipelineParser(), setProfilingAttr(), mlir::OperationState::setProperties(), mlir::OperationName::UnregisteredOpModel::setPropertiesFromAttr(), mlir::Operation::setPropertiesFromAttribute(), setReqdWorkGroupSizeAttr(), setTBAAAttr(), mlir::MlirOptMainConfig::setupPassPipeline(), setVecTypeHintAttr(), setWorkGroupSizeHintAttr(), mlir::x86::shuffleAfterReadLikeOp(), mlir::x86::shuffleBeforeWriteLikeOp(), mlir::affine::simplifyAffineMinMaxOps(), simplifyBrToBlockWithSinglePred(), simplifyConstSwitchValue(), simplifyPassThroughBr(), simplifyPassThroughSwitch(), mlir::simplifyRegions(), simplifySwitchFromDefaultSwitchOnSameCondition(), simplifySwitchFromSwitchOnSameCondition(), simplifySwitchWithOnlyDefault(), simplifyUniformBlockArgs(), mlir::sinkOperationsIntoLaunchOp(), mlir::spirv::Deserializer::sliceInstruction(), mlir::detail::SourceMgrDiagnosticVerifierHandlerImpl::SourceMgrDiagnosticVerifierHandlerImpl(), mlir::spirv::Deserializer::splitSelectionHeader(), mlir::dataflow::staticallyNonNegative(), mlir::dataflow::staticallyNonNegative(), mlir::structFuncArgTypeConverter(), mlir::spirv::Deserializer::structurizeControlFlow(), tensorExtractVectorizationPrecondition(), tileAndFuseConsumerOfSlicesImpl(), mlir::affine::tilePerfectlyNested(), mlir::affine::tilePerfectlyNestedParametric(), tileTransferVerifier(), mlir::gpu::transformGpuModulesToBinaries(), mlir::LLVM::detail::LoopAnnotationImporter::translateAccessGroup(), translateDataLayout(), tryIsolateBands(), mlir::detail::OpToOpPassAdaptor::tryMergeInto(), mlir::tryToDestructureMemorySlots(), mlir::OperationFolder::tryToFold(), tryUpdateDimOrFailure(), typeOrAttrParser(), mlir::presburger::IntegerRelation::unionBoundingBox(), mlir::vector::unrollVectorOp(), mlir::spirv::unrollVectorsInFuncBodies(), updateControlFlowOps(), updateDeallocIfChanged(), updateFuncOp(), updateFunctionOpInterface(), VulkanRuntime::updateHostMemoryBuffers(), updateOp(), updateSymbolAndAllUses(), valsAreEquivalent(), vectorizeAsLinalgGeneric(), vectorizeLoopNest(), mlir::irdl::AllOfConstraint::verify(), mlir::irdl::AnyAttributeConstraint::verify(), mlir::irdl::AnyOfConstraint::verify(), mlir::irdl::BaseAttrConstraint::verify(), mlir::irdl::BaseTypeConstraint::verify(), mlir::irdl::ConstraintVerifier::verify(), mlir::irdl::DynParametricAttrConstraint::verify(), mlir::irdl::DynParametricTypeConstraint::verify(), mlir::irdl::IsConstraint::verify(), mlir::irdl::RegionConstraint::verify(), mlir::OpState::verify(), verify1DBlockArg(), mlir::spirv::verifyAccessChain(), mlir::LLVM::detail::verifyAccessGroupOpInterface(), verifyAddSubFOp(), mlir::detail::verifyAffineMapAsLayout(), mlir::LLVM::detail::verifyAliasAnalysisOpInterface(), verifyAlignment(), verifyAllocLikeOp(), verifyAllToAllOperandAndResultShape(), verifyArithmeticExtendedBinaryOp(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::OpTrait::impl::verifyAtLeastNResults(), verifyAtomicMemOp(), verifyAtomicMemOp(), mlir::spirv::verifyAtomicUpdateOp(), verifyAttributions(), verifyAvgPoolCommonTypeAndZpChecks(), verifyBase(), verifyBlockReadWritePtrAndValTypes(), mlir::detail::verifyBranchSuccessorOperands(), verifyCallOpDebugInfo(), verifyCallOpVarCalleeType(), mlir::impl::verifyCastInterfaceOp(), mlir::spirv::verifyCastOp(), verifyCollapsedShape(), verifyComdat(), mlir::verifyCompatibleDims(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::verifyCompatibleShape(), mlir::verifyCompatibleShape(), mlir::verifyCompatibleShapes(), mlir::verifyCompatibleShapes(), mlir::wasmssa::detail::verifyConstantExpressionInterface(), verifyConstantRangeAttr(), verifyConstantType(), mlir::linalg::detail::verifyContractionInterface(), verifyConvertF32x2ToFP16x2Op(), mlir::linalg::detail::verifyConvolutionInterface(), verifyConvOp(), verifyConvOpErrorIf(), verifyConvOpModes(), verifyConvOutputSize(), mlir::spirv::verifyCoopMatrixAccess(), mlir::detail::verifyDataLayoutOp(), mlir::detail::verifyDataLayoutSpec(), mlir::LLVM::detail::verifyDereferenceableOpInterface(), verifyDescriptorOp(), mlir::detail::verifyDestinationStyleOpInterface(), verifyDeviceTypeAndSegmentCountMatch(), verifyDeviceTypeCountMatch(), verifyDimensionCompatibility(), verifyDimIsPowerOfTwo(), verifyDistributedType(), verifyDpasAccumulator(), verifyDpasDimensions(), verifyDsBarrierOpCommon(), mlir::verifyDynamicDimensionCount(), mlir::verifyElementTypesMatch(), mlir::OpTrait::impl::verifyElementwise(), verifyEntries(), verifyExtendedBatchVariantMatmulSemantic(), verifyExtendedMatmulSemantic(), verifyExtOp(), verifyExtOp(), mlir::linalg::detail::verifyFillInterface(), verifyFloatIntegerBuiltin(), verifyGatherOperandAndResultShape(), verifyGatherOrScatterDims(), verifyGridAxes(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), mlir::spirv::verifyGroupNonUniformShuffleOp(), verifyHasBindingUse(), mlir::impl::verifyHasDefaultDLTIDataLayoutTrait(), verifyImageOperands(), verifyIndexCount(), mlir::memref::detail::verifyIndexedAccessOpInterface(), mlir::memref::detail::verifyIndexedMemCopyOpInterface(), verifyIndexingMapOperandType(), verifyInGroupDevice(), mlir::DynamicOpDefinition::verifyInherentAttrs(), mlir::OperationName::UnregisteredOpModel::verifyInherentAttrs(), mlir::RegisteredOperationName::Model< ConcreteOp >::verifyInherentAttrs(), verifyInitializationAttribute(), verifyInitLikeSingleArgRegion(), mlir::detail::verifyInParallelOpInterface(), verifyInputMaps(), mlir::spirv::verifyIntegerDotProduct(), mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >::verifyInvariants(), mlir::gpu::MMAMatrixType::verifyInvariants(), mlir::OperationName::UnregisteredOpModel::verifyInvariants(), mlir::quant::AnyQuantizedType::verifyInvariants(), mlir::quant::CalibratedQuantizedType::verifyInvariants(), mlir::quant::QuantileType::verifyInvariants(), mlir::quant::QuantizedType::verifyInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyInvariants(), mlir::quant::UniformQuantizedSubChannelType::verifyInvariants(), mlir::quant::UniformQuantizedType::verifyInvariants(), mlir::spirv::MatrixType::verifyInvariants(), mlir::spirv::SampledImageType::verifyInvariants(), mlir::spirv::TensorArmType::verifyInvariants(), mlir::spirv::VerCapExtAttr::verifyInvariants(), mlir::OpTrait::impl::verifyIsIdempotent(), mlir::OpTrait::impl::verifyIsInvolution(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), mlir::OpTrait::impl::verifyIsTerminator(), verifyKnownLaunchSizeAttr(), mlir::wasmssa::detail::verifyLabelLevelInterface(), mlir::wasmssa::detail::verifyLabelLevelInterfaceIsTerminator(), verifyLayoutDistributable(), mlir::verifyListOfOperandsOrIntegers(), mlir::spirv::verifyLoadStorePtrAndValTypes(), mlir::detail::verifyLoopLikeOpInterface(), verifyLoopNesting(), verifyMatMulQuantizedOperandsType(), verifyMatMulZeroPointType(), verifyMBarrierArriveLikeOp(), mlir::spirv::verifyMemoryAccessAttribute(), mlir::spirv::verifyMemorySemantics(), mlir::detail::verifyMemorySpaceCastOpInterface(), verifyMmaSyncOp(), mlir::LLVM::detail::verifyModuleFlagValue(), verifyMultShape(), verifyNames(), mlir::OpTrait::impl::verifyNOperands(), mlir::transform::detail::verifyNoRecursionInCallGraph(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyNResults(), verifyNumBlockArgs(), mlir::detail::verifyOffsetSizeAndStrideOp(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneRegion(), mlir::OpTrait::impl::verifyOneResult(), verifyOpaqueCallCommon(), verifyOperandBundles(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::Dialect::verifyOperationAttribute(), mlir::arm_sme::verifyOperationHasValidTileId(), verifyOptions(), verifyOutputMap(), verifyOutputShape(), verifyOutputShapeCompatibleWithExpected(), verifyPackUnPack(), mlir::transform::detail::verifyParamProducerTransformOpTrait(), verifyPermutationMap(), mlir::spirv::verifyPhysicalStorageBufferDecorations(), verifyPoolingOpImpl(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), verifyQuantifierRegions(), mlir::verifyRanksMatch(), verifyReduceOp(), verifyReduceOpAndType(), verifyRegion(), mlir::Dialect::verifyRegionArgAttribute(), verifyRegionAttribute(), mlir::detail::verifyRegionBranchOpInterface(), mlir::OperationName::UnregisteredOpModel::verifyRegionInvariants(), mlir::Dialect::verifyRegionResultAttribute(), mlir::OpState::verifyRegions(), mlir::DynamicOpTrait::verifyRegionTrait(), mlir::op_definition_impl::verifyRegionTrait(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::DynamicOpTraitList::verifyRegionTraits(), mlir::op_definition_impl::verifyRegionTraits(), verifyRescaleValueAndZpTypes(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), verifyResultTypesAreInferrable(), verifySameElementTypes(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultRank(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyScatterOrSliceOperandAndResultShape(), mlir::detail::verifyShapedDimOpInterface(), verifyShapeOrExtentTensorOp(), verifyShiftOp(), verifySizeOrIndexOp(), mlir::spirv::verifySourceMemoryAccessAttribute(), verifySparseLoopOp(), verifySparsifierGetterSetter(), verifyStructArrayConstant(), verifyStructIndices(), verifyStructuredOperandOp(), mlir::linalg::detail::verifyStructuredOpInterface(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), mlir::detail::verifySubsetExtractionOpInterface(), mlir::detail::verifySubsetOpInterface(), verifySwitchOp(), mlir::detail::verifySymbol(), verifySymbolAttrUse(), mlir::detail::verifySymbolTable(), mlir::tosa::TargetEnv::verifyTargetInformation(), mlir::detail::verifyTargetSystemSpec(), verifyTcgen05MMABlockScaleOp(), verifyTcgen05MMAOp(), verifyTensorReshapeOp(), verifyTerminatorSuccessors(), verifyTileSize(), verifyTMALoadParams(), mlir::OpTrait::tosa::verifyTosaResolvableShapeOperands(), mlir::OpTrait::tosa::verifyTosaShapeOperatorWithSameRanks(), mlir::DynamicOpTrait::verifyTrait(), mlir::op_definition_impl::verifyTrait(), mlir::OpTrait::AffineScope< ConcreteType >::verifyTrait(), mlir::OpTrait::AtMostOneChildOf< ChildOps >::Impl< ConcreteType >::verifyTrait(), mlir::OpTrait::AutomaticAllocationScope< ConcreteType >::verifyTrait(), mlir::OpTrait::ConstantLike< ConcreteType >::verifyTrait(), mlir::OpTrait::HasAncestor< AncestorOpTypes >::Impl< ConcreteType >::verifyTrait(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait(), mlir::OpTrait::ReturnLike< ConcreteType >::verifyTrait(), mlir::OpTrait::Scalarizable< ConcreteType >::verifyTrait(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), mlir::OpTrait::Tensorizable< ConcreteType >::verifyTrait(), mlir::OpTrait::Vectorizable< ConcreteType >::verifyTrait(), mlir::transform::AtMostOneOpMatcherOpTrait< OpTy >::verifyTrait(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::NavigationTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::SingleValueMatcherOpTrait< OpTy >::verifyTrait(), mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait(), mlir::DynamicOpTraitList::verifyTraits(), mlir::op_definition_impl::verifyTraits(), verifyTransferOp(), mlir::transform::verifyTransformMatchDimsOp(), mlir::transform::detail::verifyTransformOpInterface(), verifyTruncateOp(), verifyTypeRangesMatch(), mlir::OpTrait::impl::verifyValueSizeAttr(), verifyVariableOpErrorIf(), verifyWeights(), verifyYield(), mlir::OpTrait::impl::verifyZeroOperands(), verifyZeroPoint(), verifyZeroPoint(), mlir::OpTrait::impl::verifyZeroRegions(), mlir::OpTrait::impl::verifyZeroResults(), mlir::OpTrait::impl::verifyZeroSuccessors(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::visit(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visit(), mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visit(), mlir::dataflow::AbstractSparseForwardDataFlowAnalysis::visit(), mlir::dataflow::DeadCodeAnalysis::visit(), mlir::SimpleAffineExprFlattener::visitAddExpr(), mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitCallableOperation(), mlir::dataflow::AbstractSparseForwardDataFlowAnalysis::visitCallOperation(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), mlir::SimpleAffineExprFlattener::visitDimExpr(), mlir::SimpleAffineExprFlattener::visitModExpr(), mlir::SimpleAffineExprFlattener::visitMulExpr(), visitOp(), mlir::dataflow::IntegerDivisibilityAnalysis::visitOperation(), mlir::dataflow::IntegerRangeAnalysis::visitOperation(), mlir::dataflow::LivenessAnalysis::visitOperation(), mlir::dataflow::SparseConstantPropagation::visitOperation(), mlir::dataflow::StridedMetadataRangeAnalysis::visitOperation(), mlir::xegpu::detail::axis_dataflow::AxisInfoAnalysis::visitOperation(), mlir::SimpleAffineExprFlattener::visitSymbolExpr(), walkReferenceCountedValues(), and mlir::spirv::Deserializer::wireUpBlockArgument().
Variable Documentation
indices
indices
Definition at line 263 of file AffineAnalysis.cpp.
Referenced by adjustAccessChainForBitwidth(), mlir::tensor::bubbleUpPadSlice(), buildVectorWrite(), mlir::memref::impl::FlattenMemrefsPassBase< DerivedT >::classof(), mlir::nvgpu::impl::OptimizeSharedMemoryBase< DerivedT >::classof(), mlir::nvgpu::impl::OptimizeSharedMemoryBase< DerivedT >::clonePass(), mlir::composeReassociationIndices(), computeCandidateInterchangePermutations(), mlir::computeLinearIndex(), mlir::computeLinearIndex(), mlir::LLVM::convertArrayToIndices(), mlir::convertReassociationIndicesToExprs(), mlir::convertReassociationMapsToIndices(), createInserts(), mlir::LLVM::createPrintStrCall(), mlir::vector::createReadOrMaskedRead(), creatLdMatrixCompatibleLoads(), destructureIndices(), expandToUnderlyingIndices(), extractCompositeElement(), extractLoadCoordsForComposite(), extractPosition(), mlir::filterTypesOut(), foldScalarExtractFromFromElements(), foreachIndividualVectorElement(), genExpand(), gepToByteOffset(), mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >::getArgument(), mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >::getArgumentName(), getAttributeIndexFromIndexOperands(), mlir::spirv::getBuiltinVariableValue(), mlir::tensor::getCollapsedExtractSliceInfo(), getCollapsedIndices(), getCollapseShapeTrivialSegments(), mlir::memref::impl::FlattenMemrefsPassBase< DerivedT >::getDescription(), mlir::spirv::getElementPtr(), mlir::spirv::getElementPtrType(), getElementType(), getElementType(), getElementType(), getElementType(), getFirstOrLastMappedMemberPtr(), getFlattenMemrefAndOffset(), getIndicesForAccess(), mlir::affine::getInvariantAccesses(), getLinearIndexI32(), mlir::memref::getLinearizedMemRefOffsetAndSize(), getLinearizedSrcIndices(), mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >::getName(), mlir::spirv::getOpenCLElementPtr(), mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >::getPassName(), getPositionFromIndices(), getReassociationForExpansion(), mlir::getReassociationIndicesAttribute(), getSemiAffineExprFromFlatForm(), mlir::ConvertToLLVMPattern::getStridedElementPtr(), mlir::LLVM::getStridedElementPtr(), getTensorExtractMemoryAccessPattern(), getUniqueNonUnitDim(), mlir::getValuesSortedByKeyImpl(), mlir::spirv::getVulkanElementPtr(), getXferIndices(), hasTrivialReassociationSuffix(), mlir::tosa::hasUniqueConstantScatterIndices(), inlinePayload(), mlir::insertTypesInto(), interchangeLoops(), isIVMappedToMultipleIndices(), isMaskTriviallyFoldable(), mlir::spirv::linearizeIndex(), mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >::LowerVectorMultiReductionBase(), makePermutationMap(), ConvertAccessChain::matchAndRewrite(), mlir::ComposeCollapseOfExpandOp< CollapseOpTy, ExpandOpTy, CastOpTy, DimOpTy, TensorTy >::matchAndRewrite(), mlir::gpu::WarpDistributionPattern::matchAndRewrite(), mlir::gpu::WarpDistributionPattern::moveRegionToNewWarpOpAndAppendReturns(), GpuAsyncRegionPass::SingleTokenUseCallback::operator()(), DynamicMemRefType< T >::operator[](), mlir::OwningMemRef< T, Rank >::operator[](), StridedMemRefType< T, 0 >::operator[](), StridedMemRefType< T, 1 >::operator[](), StridedMemRefType< T, Rank >::operator[](), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), parseGEPIndices(), parseSizeAssignment(), mlir::detail::Parser::parseSparseElementsAttr(), mlir::spirv::printAccessChain(), mlir::AsmPrinter::Impl::printAttributeImpl(), printGEPIndices(), mlir::affine::resolveIndicesIntoOpWithOffsetsAndStrides(), mlir::memref::resolveSourceIndicesCollapseShape(), mlir::memref::resolveSourceIndicesExpandShape(), mlir::memref::resolveSourceIndicesRankReducingSubview(), mlir::linalg::rewriteInDestinationPassingStyle(), mlir::linalg::rewriteInIm2Col(), mlir::nvgpu::setIndices(), mlir::IRObjectWithUseList< OperandType >::shuffleUseList(), mlir::Value::shuffleUseList(), sliceLoadStoreIndices(), sortMapIndices(), mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >::SPIRVUnifyAliasedResourcePassBase(), transformIndices(), vectorizeAffineLoad(), vectorizeAffineStore(), vectorizeAsLinalgGeneric(), mlir::spirv::verifyAccessChain(), verifyGatherOrScatterDims(), verifyStructIndices(), verifyStructIndices(), mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >::~LowerVectorMultiReductionBase(), and mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >::~SPIRVUnifyAliasedResourcePassBase().