MLIR: lib/Dialect/Affine/Transforms/ReifyValueBounds.cpp File Reference
ReifyValueBounds.cpp File Reference
#include "mlir/Dialect/Affine/Transforms/Transforms.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Interfaces/ValueBoundsOpInterface.h"
Functions
static FailureOr< OpFoldResult > reifyValueBound (OpBuilder &b, Location loc, presburger::BoundType type, Value value, std::optional< int64_t > dim, ValueBoundsConstraintSet::StopConditionFn stopCondition, bool closedUB)
Function Documentation
reifyValueBound()
static FailureOr<OpFoldResult> reifyValueBound (OpBuilder & b, Location loc, presburger::BoundType type, Value value, std::optional< int64_t > dim, ValueBoundsConstraintSet::StopConditionFn stopCondition, bool closedUB) static
Definition at line 20 of file ReifyValueBounds.cpp.
References mlir::ValueBoundsConstraintSet::computeBound(), mlir::failed(), mlir::failure(), and mlir::affine::materializeComputedBound().
Referenced by mlir::affine::reifyIndexValueBound(), and mlir::affine::reifyShapedValueDimBound().