MLIR: lib/Dialect/Affine/Transforms/FoldMemRefAliasOps.cpp File Reference
FoldMemRefAliasOps.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/Transforms/Passes.h"
#include "mlir/Dialect/Affine/ViewLikeInterfaceUtils.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Dialect/Affine/Transforms/Passes.h.inc"
Classes
class mlir::affine::impl::AffineFoldMemRefAliasOpsBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::affine
namespace mlir::affine::impl
Macros
#define GEN_PASS_DEF_AFFINEFOLDMEMREFALIASOPS
Functions
std::unique_ptr<::mlir::Pass > mlir::affine::impl::createAffineFoldMemRefAliasOps ()
std::unique_ptr<::mlir::Pass > mlir::affine::createAffineFoldMemRefAliasOps ()
static void expandToUnderlyingIndices (AffineMap affineMap, ValueRange indices, Location loc, PatternRewriter &rewriter, SmallVectorImpl< Value > &result)
Given an AffineMap and a list of indices, apply the map to get the underlying indices (expanding the affine map).
Macro Definition Documentation
GEN_PASS_DEF_AFFINEFOLDMEMREFALIASOPS
#define GEN_PASS_DEF_AFFINEFOLDMEMREFALIASOPS
Definition at line 26 of file FoldMemRefAliasOps.cpp.
Function Documentation
expandToUnderlyingIndices()
void expandToUnderlyingIndices (AffineMap affineMap, ValueRange indices, Location loc, PatternRewriter & rewriter, SmallVectorImpl< Value > & result) static
Given an AffineMap and a list of indices, apply the map to get the underlying indices (expanding the affine map).
Definition at line 40 of file FoldMemRefAliasOps.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getSubMap(), mlir::getValueOrCreateConstantIndexOp(), indices, mlir::affine::makeComposedFoldedAffineApply(), and result.