MLIR: lib/Conversion/MemRefToLLVM/AllocLikeConversion.cpp File Reference
AllocLikeConversion.cpp File Reference
#include "mlir/Conversion/MemRefToLLVM/AllocLikeConversion.h"
#include "mlir/Analysis/DataLayoutAnalysis.h"
#include "mlir/Dialect/LLVMIR/FunctionCallUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/SymbolTable.h"
Functions
static Value castAllocFuncResult (ConversionPatternRewriter &rewriter, Location loc, Value allocatedPtr, MemRefType memRefType, Type elementPtrType, const LLVMTypeConverter &typeConverter)
Function Documentation
castAllocFuncResult()
static Value castAllocFuncResult (ConversionPatternRewriter & rewriter, Location loc, Value allocatedPtr, MemRefType memRefType, Type elementPtrType, const LLVMTypeConverter & typeConverter) static
Definition at line 49 of file AllocLikeConversion.cpp.
References mlir::OpBuilder::create(), mlir::get(), mlir::Builder::getContext(), mlir::LLVMTypeConverter::getMemRefAddressSpace(), and mlir::Value::getType().
Referenced by mlir::AllocationOpLLVMLowering::allocateBufferAutoAlign(), and mlir::AllocationOpLLVMLowering::allocateBufferManuallyAlign().