MLIR: include/mlir-c/Dialect/AMDGPU.h File Reference
AMDGPU.h File Reference
#include "mlir-c/IR.h"
#include "mlir/Dialect/AMDGPU/Transforms/Passes.capi.h.inc"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (AMDGPU, amdgpu)
MLIR_CAPI_EXPORTED bool mlirTypeIsAAMDGPUTDMBaseType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirAMDGPUTDMBaseTypeGetTypeID ()
MLIR_CAPI_EXPORTED MlirType mlirAMDGPUTDMBaseTypeGet (MlirContext ctx, MlirType elementType)
MLIR_CAPI_EXPORTED MlirStringRef mlirAMDGPUTDMBaseTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsAAMDGPUTDMDescriptorType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirAMDGPUTDMDescriptorTypeGetTypeID ()
MLIR_CAPI_EXPORTED MlirType mlirAMDGPUTDMDescriptorTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirStringRef mlirAMDGPUTDMDescriptorTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsAAMDGPUTDMGatherBaseType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirAMDGPUTDMGatherBaseTypeGetTypeID ()
MLIR_CAPI_EXPORTED MlirType mlirAMDGPUTDMGatherBaseTypeGet (MlirContext ctx, MlirType elementType, MlirType indexType)
MLIR_CAPI_EXPORTED MlirStringRef mlirAMDGPUTDMGatherBaseTypeGetName (void)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (AMDGPU , amdgpu)
References MLIR_CAPI_EXPORTED.
mlirAMDGPUTDMBaseTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirAMDGPUTDMBaseTypeGet (MlirContext ctx, MlirType elementType)
Definition at line 31 of file AMDGPU.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMBaseType::bindDerived().
mlirAMDGPUTDMBaseTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirAMDGPUTDMBaseTypeGetName (void)
Definition at line 35 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMBaseTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirAMDGPUTDMBaseTypeGetTypeID ()
Definition at line 27 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMDescriptorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirAMDGPUTDMDescriptorTypeGet (MlirContext ctx)
Definition at line 51 of file AMDGPU.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMDescriptorType::bindDerived().
mlirAMDGPUTDMDescriptorTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirAMDGPUTDMDescriptorTypeGetName (void)
Definition at line 55 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMDescriptorTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirAMDGPUTDMDescriptorTypeGetTypeID ()
Definition at line 47 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMGatherBaseTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirAMDGPUTDMGatherBaseTypeGet (MlirContext ctx, MlirType elementType, MlirType indexType)
Definition at line 71 of file AMDGPU.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMGatherBaseType::bindDerived().
mlirAMDGPUTDMGatherBaseTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirAMDGPUTDMGatherBaseTypeGetName (void)
Definition at line 77 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMGatherBaseTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirAMDGPUTDMGatherBaseTypeGetTypeID ()
Definition at line 67 of file AMDGPU.cpp.
References wrap().
mlirTypeIsAAMDGPUTDMBaseType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAAMDGPUTDMBaseType (MlirType type)
Definition at line 23 of file AMDGPU.cpp.
References unwrap().
mlirTypeIsAAMDGPUTDMDescriptorType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAAMDGPUTDMDescriptorType (MlirType type)
Definition at line 43 of file AMDGPU.cpp.
References unwrap().
mlirTypeIsAAMDGPUTDMGatherBaseType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAAMDGPUTDMGatherBaseType (MlirType type)
Definition at line 63 of file AMDGPU.cpp.
References unwrap().