MLIR: lib/Dialect/AMDGPU/Transforms/OptimizeSharedMemory.cpp File Reference
OptimizeSharedMemory.cpp File Reference
#include "mlir/Dialect/AMDGPU/Transforms/Passes.h"
#include "mlir/Dialect/AMDGPU/IR/AMDGPUDialect.h"
#include "mlir/Dialect/AMDGPU/Transforms/Transforms.h"
#include "mlir/Dialect/AMDGPU/Transforms/Utils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Dialect/AMDGPU/Transforms/Passes.h.inc"
Classes
struct OptimizeSharedMemoryPass
Namespaces
mlir
Include the generated interface declarations.
mlir::amdgpu
Macros
#define GEN_PASS_DEF_OPTIMIZESHAREDMEMORY
Functions
static Value permuteVectorOffset (OpBuilder &b, Location loc, ArrayRef< Value > indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim, int64_t sharedMemoryLineSizeBytes, int64_t defaultVectorSizeBits)
Uses srcIndexValue to permute tgtIndexValue via `result = xor(floordiv(srcIdxVal,permuteEveryN), floordiv(tgtIdxVal,vectorSize)))
static void transformIndices (OpBuilder &builder, Location loc, SmallVector< Value, 4 > &indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim, int64_t sharedMemoryLineSizeBytes, int64_t defaultVectorSizeBits)
static LogicalResult getShmReadAndWriteOps (Operation *parentOp, Value shmMemRef, SmallVector< Operation *, 16 > &readOps, SmallVector< Operation *, 16 > &writeOps)
Macro Definition Documentation
GEN_PASS_DEF_OPTIMIZESHAREDMEMORY
#define GEN_PASS_DEF_OPTIMIZESHAREDMEMORY
Definition at line 30 of file OptimizeSharedMemory.cpp.
Function Documentation
getShmReadAndWriteOps()
static LogicalResult getShmReadAndWriteOps (Operation * parentOp, Value shmMemRef, SmallVector< Operation *, 16 > & readOps, SmallVector< Operation *, 16 > & writeOps) static
Definition at line 113 of file OptimizeSharedMemory.cpp.
References mlir::Operation::walk().
Referenced by mlir::amdgpu::optimizeSharedMemoryReadsAndWrites().
permuteVectorOffset()
static Value permuteVectorOffset (OpBuilder & b, Location loc, ArrayRef< Value > indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim, int64_t sharedMemoryLineSizeBytes, int64_t defaultVectorSizeBits) static
Uses srcIndexValue to permute tgtIndexValue via `result = xor(floordiv(srcIdxVal,permuteEveryN), floordiv(tgtIdxVal,vectorSize)))
tgtIdxVal % vectorSize This is done using an optimized sequence ofarith` operations.
Use the src bits to permute the target bits b[N:M] containing the vector offset.
Definition at line 43 of file OptimizeSharedMemory.cpp.
References mlir::OpBuilder::create(), and mlir::OpBuilder::createOrFold().
Referenced by transformIndices().
transformIndices()
static void transformIndices (OpBuilder & builder, Location loc, SmallVector< Value, 4 > & indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim, int64_t sharedMemoryLineSizeBytes, int64_t defaultVectorSizeBits) static
Definition at line 100 of file OptimizeSharedMemory.cpp.
References permuteVectorOffset().
Referenced by mlir::amdgpu::optimizeSharedMemoryReadsAndWrites().