MLIR: lib/CAPI/Dialect/AMDGPU.cpp File Reference
AMDGPU.cpp File Reference
#include "mlir-c/Dialect/AMDGPU.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/AMDGPU/IR/AMDGPUDialect.h"
Functions
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION (AMDGPU, amdgpu, mlir::amdgpu::AMDGPUDialect) using namespace mlir
bool mlirTypeIsAAMDGPUTDMBaseType (MlirType type)
MlirTypeID mlirAMDGPUTDMBaseTypeGetTypeID ()
MlirType mlirAMDGPUTDMBaseTypeGet (MlirContext ctx, MlirType elementType)
MlirStringRef mlirAMDGPUTDMBaseTypeGetName (void)
bool mlirTypeIsAAMDGPUTDMDescriptorType (MlirType type)
MlirTypeID mlirAMDGPUTDMDescriptorTypeGetTypeID ()
MlirType mlirAMDGPUTDMDescriptorTypeGet (MlirContext ctx)
MlirStringRef mlirAMDGPUTDMDescriptorTypeGetName (void)
bool mlirTypeIsAAMDGPUTDMGatherBaseType (MlirType type)
MlirTypeID mlirAMDGPUTDMGatherBaseTypeGetTypeID ()
MlirType mlirAMDGPUTDMGatherBaseTypeGet (MlirContext ctx, MlirType elementType, MlirType indexType)
MlirStringRef mlirAMDGPUTDMGatherBaseTypeGetName (void)
Function Documentation
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION()
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION (AMDGPU , amdgpu , mlir::amdgpu::AMDGPUDialect)
mlirAMDGPUTDMBaseTypeGet()
MlirType mlirAMDGPUTDMBaseTypeGet (MlirContext ctx, MlirType elementType)
Definition at line 31 of file AMDGPU.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMBaseType::bindDerived().
mlirAMDGPUTDMBaseTypeGetName()
MlirStringRef mlirAMDGPUTDMBaseTypeGetName (void)
Definition at line 35 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMBaseTypeGetTypeID()
MlirTypeID mlirAMDGPUTDMBaseTypeGetTypeID ()
Definition at line 27 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMDescriptorTypeGet()
MlirType mlirAMDGPUTDMDescriptorTypeGet (MlirContext ctx)
Definition at line 51 of file AMDGPU.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMDescriptorType::bindDerived().
mlirAMDGPUTDMDescriptorTypeGetName()
MlirStringRef mlirAMDGPUTDMDescriptorTypeGetName (void)
Definition at line 55 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMDescriptorTypeGetTypeID()
MlirTypeID mlirAMDGPUTDMDescriptorTypeGetTypeID ()
Definition at line 47 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMGatherBaseTypeGet()
MlirType mlirAMDGPUTDMGatherBaseTypeGet (MlirContext ctx, MlirType elementType, MlirType indexType)
Definition at line 71 of file AMDGPU.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMGatherBaseType::bindDerived().
mlirAMDGPUTDMGatherBaseTypeGetName()
MlirStringRef mlirAMDGPUTDMGatherBaseTypeGetName (void)
Definition at line 77 of file AMDGPU.cpp.
References wrap().
mlirAMDGPUTDMGatherBaseTypeGetTypeID()
MlirTypeID mlirAMDGPUTDMGatherBaseTypeGetTypeID ()
Definition at line 67 of file AMDGPU.cpp.
References wrap().
mlirTypeIsAAMDGPUTDMBaseType()
bool mlirTypeIsAAMDGPUTDMBaseType (MlirType type)
Definition at line 23 of file AMDGPU.cpp.
References unwrap().
mlirTypeIsAAMDGPUTDMDescriptorType()
bool mlirTypeIsAAMDGPUTDMDescriptorType (MlirType type)
Definition at line 43 of file AMDGPU.cpp.
References unwrap().
mlirTypeIsAAMDGPUTDMGatherBaseType()
bool mlirTypeIsAAMDGPUTDMGatherBaseType (MlirType type)
Definition at line 63 of file AMDGPU.cpp.
References unwrap().