MLIR: lib/Dialect/Arith/Transforms/ExpandOps.cpp File Reference
ExpandOps.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinTypeInterfaces.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h.inc"
Classes
class mlir::arith::impl::ArithExpandOpsPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::arith
namespace mlir::arith::impl
Macros
#define GEN_PASS_DEF_ARITHEXPANDOPSPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::arith::impl::createArithExpandOpsPass ()
std::unique_ptr<::mlir::Pass > mlir::arith::impl::createArithExpandOpsPass (ArithExpandOpsPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::arith::createArithExpandOpsPass ()
std::unique_ptr<::mlir::Pass > mlir::arith::createArithExpandOpsPass (ArithExpandOpsPassOptions options)
static Value createConst (Location loc, Type type, int value, PatternRewriter &rewriter)
Create an integer or index constant.
static Value createFloatConst (Location loc, Type type, const APFloat &value, PatternRewriter &rewriter)
Create a float constant.
static Type cloneToShapedType (Type cloneFrom, Type cloneTo)
Creates shapedType using shape from cloneFrom and base type from cloneTo.
Macro Definition Documentation
GEN_PASS_DEF_ARITHEXPANDOPSPASS
#define GEN_PASS_DEF_ARITHEXPANDOPSPASS
Definition at line 19 of file ExpandOps.cpp.
Function Documentation
cloneToShapedType()
Type cloneToShapedType (Type cloneFrom, Type cloneTo) static
Creates shapedType using shape from cloneFrom and base type from cloneTo.
Definition at line 50 of file ExpandOps.cpp.
createConst()
Value createConst (Location loc, Type type, int value, PatternRewriter & rewriter) static
Create an integer or index constant.
Definition at line 27 of file ExpandOps.cpp.
References mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), and mlir::Builder::getIntegerAttr().
Referenced by mlir::transform::gpu::createGpuLaunch().
createFloatConst()
Value createFloatConst (Location loc, Type type, const APFloat & value, PatternRewriter & rewriter) static
Create a float constant.
Definition at line 38 of file ExpandOps.cpp.
References mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), and mlir::Builder::getFloatAttr().