MLIR: lib/Conversion/ArithToAPFloat/ArithToAPFloat.cpp File Reference
ArithToAPFloat.cpp File Reference
#include "mlir/Conversion/ArithToAPFloat/ArithToAPFloat.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Utils/Utils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Transforms/WalkPatternRewriteDriver.h"
#include "mlir/Conversion/Passes.h.inc"
Classes
struct mlir::ArithToAMDGPUConversionPassOptions
class mlir::impl::ArithToAPFloatConversionPassBase< DerivedT >
struct mlir::ArithToLLVMConversionPassOptions
struct mlir::ConvertAMDGPUToROCDLPassOptions
struct mlir::ConvertAffineForToGPUPassOptions
struct mlir::ConvertArithToSPIRVPassOptions
struct mlir::ConvertArmSMEToLLVMOptions
struct mlir::ConvertComplexToLLVMPassOptions
struct mlir::ConvertComplexToStandardPassOptions
struct mlir::ConvertControlFlowToLLVMPassOptions
struct mlir::ConvertControlFlowToSPIRVPassOptions
struct mlir::ConvertFuncToLLVMPassOptions
struct mlir::ConvertFuncToSPIRVPassOptions
struct mlir::ConvertGPUToSPIRVOptions
struct mlir::ConvertGpuOpsToLLVMSPVOpsOptions
struct mlir::ConvertGpuOpsToNVVMOpsOptions
struct mlir::ConvertGpuOpsToROCDLOpsOptions
struct mlir::ConvertIndexToLLVMPassOptions
struct mlir::ConvertIndexToSPIRVPassOptions
struct mlir::ConvertMathToEmitCOptions
struct mlir::ConvertMathToFuncsOptions
struct mlir::ConvertMathToLLVMPassOptions
struct mlir::ConvertMathToROCDLOptions
struct mlir::ConvertMathToXeVMOptions
struct mlir::ConvertMemRefToEmitCOptions
struct mlir::ConvertMemRefToSPIRVPassOptions
struct mlir::ConvertSCFToOpenMPPassOptions
struct mlir::ConvertSPIRVToLLVMPassOptions
struct mlir::ConvertTensorToSPIRVPassOptions
struct mlir::ConvertToEmitCOptions
struct mlir::ConvertToLLVMPassOptions
struct mlir::ConvertVectorToGPUOptions
struct mlir::ConvertVectorToLLVMPassOptions
struct mlir::ConvertVectorToSCFOptions
struct mlir::FinalizeMemRefToLLVMConversionPassOptions
struct mlir::GpuToLLVMConversionPassOptions
struct mlir::MapMemRefStorageClassOptions
struct mlir::SCFToControlFlowPassOptions
struct mlir::SetLLVMModuleDataLayoutPassOptions
struct mlir::TosaToArithPassOptions
struct mlir::TosaToLinalgOptions
struct mlir::TosaToLinalgNamedOptions
struct mlir::UBToLLVMConversionPassOptions
struct BinaryArithOpToAPFloatConversion< OpTy >
Rewrite a binary arithmetic operation to an APFloat function call.
struct FpToFpConversion< OpTy >
struct FpToIntConversion< OpTy >
struct IntToFpConversion< OpTy >
struct CmpFOpToAPFloatConversion
struct NegFOpToAPFloatConversion
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_ARITHTOAPFLOATCONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOAMDGPUCONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOAPFLOATCONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOARMSMECONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_CONVERTAMDGPUTOROCDLPASS
#define GEN_PASS_DECL_CONVERTAFFINEFORTOGPUPASS
#define GEN_PASS_DECL_CONVERTARITHTOEMITC
#define GEN_PASS_DECL_CONVERTARITHTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTARMNEON2DTOINTRPASS
#define GEN_PASS_DECL_CONVERTARMSMETOLLVM
#define GEN_PASS_DECL_CONVERTARMSMETOSCFPASS
#define GEN_PASS_DECL_CONVERTASYNCTOLLVMPASS
#define GEN_PASS_DECL_CONVERTBUFFERIZATIONTOMEMREFPASS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOLLVMPASS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOLIBM
#define GEN_PASS_DECL_CONVERTCOMPLEXTOROCDLLIBRARYCALLS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOSTANDARDPASS
#define GEN_PASS_DECL_CONVERTCONTROLFLOWTOLLVMPASS
#define GEN_PASS_DECL_CONVERTCONTROLFLOWTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTFUNCTOEMITC
#define GEN_PASS_DECL_CONVERTFUNCTOLLVMPASS
#define GEN_PASS_DECL_CONVERTFUNCTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTGPUTOSPIRV
#define GEN_PASS_DECL_CONVERTGPUOPSTOLLVMSPVOPS
#define GEN_PASS_DECL_CONVERTGPUOPSTONVVMOPS
#define GEN_PASS_DECL_CONVERTGPUOPSTOROCDLOPS
#define GEN_PASS_DECL_CONVERTINDEXTOLLVMPASS
#define GEN_PASS_DECL_CONVERTINDEXTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTLINALGTOSTANDARDPASS
#define GEN_PASS_DECL_CONVERTMATHTOEMITC
#define GEN_PASS_DECL_CONVERTMATHTOFUNCS
#define GEN_PASS_DECL_CONVERTMATHTOLLVMPASS
#define GEN_PASS_DECL_CONVERTMATHTOLIBMPASS
#define GEN_PASS_DECL_CONVERTMATHTOROCDL
#define GEN_PASS_DECL_CONVERTMATHTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTMATHTOXEVM
#define GEN_PASS_DECL_CONVERTMEMREFTOEMITC
#define GEN_PASS_DECL_CONVERTMEMREFTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTNVGPUTONVVMPASS
#define GEN_PASS_DECL_CONVERTNVVMTOLLVMPASS
#define GEN_PASS_DECL_CONVERTOPENACCTOSCFPASS
#define GEN_PASS_DECL_CONVERTOPENMPTOLLVMPASS
#define GEN_PASS_DECL_CONVERTPDLTOPDLINTERPPASS
#define GEN_PASS_DECL_CONVERTPARALLELLOOPTOGPUPASS
#define GEN_PASS_DECL_CONVERTSCFTOOPENMPPASS
#define GEN_PASS_DECL_CONVERTSPIRVTOLLVMPASS
#define GEN_PASS_DECL_CONVERTSHAPECONSTRAINTSPASS
#define GEN_PASS_DECL_CONVERTSHAPETOSTANDARDPASS
#define GEN_PASS_DECL_CONVERTSHARDTOMPIPASS
#define GEN_PASS_DECL_CONVERTTENSORTOLINALGPASS
#define GEN_PASS_DECL_CONVERTTENSORTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTTOEMITC
#define GEN_PASS_DECL_CONVERTTOLLVMPASS
#define GEN_PASS_DECL_CONVERTVECTORTOAMX
#define GEN_PASS_DECL_CONVERTVECTORTOARMSMEPASS
#define GEN_PASS_DECL_CONVERTVECTORTOGPU
#define GEN_PASS_DECL_CONVERTVECTORTOLLVMPASS
#define GEN_PASS_DECL_CONVERTVECTORTOSCF
#define GEN_PASS_DECL_CONVERTVECTORTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTVECTORTOXEGPU
#define GEN_PASS_DECL_CONVERTXEGPUTOXEVMPASS
#define GEN_PASS_DECL_CONVERTXEVMTOLLVMPASS
#define GEN_PASS_DECL_FINALIZEMEMREFTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_LIFTCONTROLFLOWTOSCFPASS
#define GEN_PASS_DECL_LOWERAFFINEPASS
#define GEN_PASS_DECL_LOWERHOSTCODETOLLVMPASS
#define GEN_PASS_DECL_MAPMEMREFSTORAGECLASS
#define GEN_PASS_DECL_RECONCILEUNREALIZEDCASTSPASS
#define GEN_PASS_DECL_SCFTOCONTROLFLOWPASS
#define GEN_PASS_DECL_SCFTOEMITC
#define GEN_PASS_DECL_SCFTOSPIRV
#define GEN_PASS_DECL_SETLLVMMODULEDATALAYOUTPASS
#define GEN_PASS_DECL_TOSATOARITHPASS
#define GEN_PASS_DECL_TOSATOLINALG
#define GEN_PASS_DECL_TOSATOLINALGNAMED
#define GEN_PASS_DECL_TOSATOMLPROGRAM
#define GEN_PASS_DECL_TOSATOSCFPASS
#define GEN_PASS_DECL_TOSATOTENSORPASS
#define GEN_PASS_DECL_UBTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_UBTOSPIRVCONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOAMDGPUCONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOAPFLOATCONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOARMSMECONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_CONVERTAMDGPUTOROCDLPASS
#define GEN_PASS_REGISTRATION_CONVERTAFFINEFORTOGPUPASS
#define GEN_PASS_REGISTRATION_CONVERTARITHTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTARITHTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTARMNEON2DTOINTRPASS
#define GEN_PASS_REGISTRATION_CONVERTARMSMETOLLVM
#define GEN_PASS_REGISTRATION_CONVERTARMSMETOSCFPASS
#define GEN_PASS_REGISTRATION_CONVERTASYNCTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTBUFFERIZATIONTOMEMREFPASS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOLIBM
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOROCDLLIBRARYCALLS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOSTANDARDPASS
#define GEN_PASS_REGISTRATION_CONVERTCONTROLFLOWTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTCONTROLFLOWTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTFUNCTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTFUNCTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTFUNCTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTGPUTOSPIRV
#define GEN_PASS_REGISTRATION_CONVERTGPUOPSTOLLVMSPVOPS
#define GEN_PASS_REGISTRATION_CONVERTGPUOPSTONVVMOPS
#define GEN_PASS_REGISTRATION_CONVERTGPUOPSTOROCDLOPS
#define GEN_PASS_REGISTRATION_CONVERTINDEXTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTINDEXTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTLINALGTOSTANDARDPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTMATHTOFUNCS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOLIBMPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOROCDL
#define GEN_PASS_REGISTRATION_CONVERTMATHTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOXEVM
#define GEN_PASS_REGISTRATION_CONVERTMEMREFTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTMEMREFTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTNVGPUTONVVMPASS
#define GEN_PASS_REGISTRATION_CONVERTNVVMTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTOPENACCTOSCFPASS
#define GEN_PASS_REGISTRATION_CONVERTOPENMPTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTPDLTOPDLINTERPPASS
#define GEN_PASS_REGISTRATION_CONVERTPARALLELLOOPTOGPUPASS
#define GEN_PASS_REGISTRATION_CONVERTSCFTOOPENMPPASS
#define GEN_PASS_REGISTRATION_CONVERTSPIRVTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTSHAPECONSTRAINTSPASS
#define GEN_PASS_REGISTRATION_CONVERTSHAPETOSTANDARDPASS
#define GEN_PASS_REGISTRATION_CONVERTSHARDTOMPIPASS
#define GEN_PASS_REGISTRATION_CONVERTTENSORTOLINALGPASS
#define GEN_PASS_REGISTRATION_CONVERTTENSORTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOAMX
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOARMSMEPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOGPU
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOSCF
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOXEGPU
#define GEN_PASS_REGISTRATION_CONVERTXEGPUTOXEVMPASS
#define GEN_PASS_REGISTRATION_CONVERTXEVMTOLLVMPASS
#define GEN_PASS_REGISTRATION_FINALIZEMEMREFTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_LIFTCONTROLFLOWTOSCFPASS
#define GEN_PASS_REGISTRATION_LOWERAFFINEPASS
#define GEN_PASS_REGISTRATION_LOWERHOSTCODETOLLVMPASS
#define GEN_PASS_REGISTRATION_MAPMEMREFSTORAGECLASS
#define GEN_PASS_REGISTRATION_RECONCILEUNREALIZEDCASTSPASS
#define GEN_PASS_REGISTRATION_SCFTOCONTROLFLOWPASS
#define GEN_PASS_REGISTRATION_SCFTOEMITC
#define GEN_PASS_REGISTRATION_SCFTOSPIRV
#define GEN_PASS_REGISTRATION_SETLLVMMODULEDATALAYOUTPASS
#define GEN_PASS_REGISTRATION_TOSATOARITHPASS
#define GEN_PASS_REGISTRATION_TOSATOLINALG
#define GEN_PASS_REGISTRATION_TOSATOLINALGNAMED
#define GEN_PASS_REGISTRATION_TOSATOMLPROGRAM
#define GEN_PASS_REGISTRATION_TOSATOSCFPASS
#define GEN_PASS_REGISTRATION_TOSATOTENSORPASS
#define GEN_PASS_REGISTRATION_UBTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_UBTOSPIRVCONVERSIONPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::createArithToAMDGPUConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createArithToAMDGPUConversionPass (ArithToAMDGPUConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createArithToAPFloatConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToAPFloatConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createArithToArmSMEConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createArithToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createArithToLLVMConversionPass (ArithToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertAMDGPUToROCDLPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertAMDGPUToROCDLPass (ConvertAMDGPUToROCDLPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertAffineForToGPUPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertAffineForToGPUPass (ConvertAffineForToGPUPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertArithToEmitC ()
std::unique_ptr<::mlir::Pass > mlir::createConvertArithToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertArithToSPIRVPass (ConvertArithToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertArmNeon2dToIntrPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertArmSMEToSCFPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertAsyncToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertBufferizationToMemRefPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToLLVMPass (ConvertComplexToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToLibm ()
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToROCDLLibraryCalls ()
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToStandardPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertComplexToStandardPass (ConvertComplexToStandardPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertControlFlowToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertControlFlowToLLVMPass (ConvertControlFlowToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertControlFlowToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertControlFlowToSPIRVPass (ConvertControlFlowToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertFuncToEmitC ()
std::unique_ptr<::mlir::Pass > mlir::createConvertFuncToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertFuncToLLVMPass (ConvertFuncToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertFuncToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertFuncToSPIRVPass (ConvertFuncToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToLLVMSPVOps ()
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToLLVMSPVOps (ConvertGpuOpsToLLVMSPVOpsOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToNVVMOps ()
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToNVVMOps (ConvertGpuOpsToNVVMOpsOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToROCDLOps ()
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToROCDLOps (ConvertGpuOpsToROCDLOpsOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertIndexToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertIndexToLLVMPass (ConvertIndexToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertIndexToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertIndexToSPIRVPass (ConvertIndexToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertLinalgToStandardPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToEmitC ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToEmitC (ConvertMathToEmitCOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToFuncs ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToFuncs (ConvertMathToFuncsOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToLLVMPass (ConvertMathToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToLibmPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToROCDL ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToROCDL (ConvertMathToROCDLOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToXeVM ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToXeVM (ConvertMathToXeVMOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertMemRefToEmitC ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMemRefToEmitC (ConvertMemRefToEmitCOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertMemRefToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMemRefToSPIRVPass (ConvertMemRefToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertNVGPUToNVVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertNVVMToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertOpenACCToSCFPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertOpenMPToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertPDLToPDLInterpPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertParallelLoopToGpuPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertSCFToOpenMPPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertSCFToOpenMPPass (ConvertSCFToOpenMPPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertSPIRVToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertSPIRVToLLVMPass (ConvertSPIRVToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertShapeConstraintsPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertShapeToStandardPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertShardToMPIPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertTensorToLinalgPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertTensorToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertTensorToSPIRVPass (ConvertTensorToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertToEmitC ()
std::unique_ptr<::mlir::Pass > mlir::createConvertToEmitC (ConvertToEmitCOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertToLLVMPass (ConvertToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertVectorToAMX ()
std::unique_ptr<::mlir::Pass > mlir::createConvertVectorToArmSMEPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertVectorToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertVectorToLLVMPass (ConvertVectorToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertVectorToSPIRVPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertVectorToXeGPU ()
std::unique_ptr<::mlir::Pass > mlir::createConvertXeGPUToXeVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertXeVMToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createFinalizeMemRefToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createFinalizeMemRefToLLVMConversionPass (FinalizeMemRefToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createGpuToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createGpuToLLVMConversionPass (GpuToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createLiftControlFlowToSCFPass ()
std::unique_ptr<::mlir::Pass > mlir::createLowerAffinePass ()
std::unique_ptr<::mlir::Pass > mlir::createLowerHostCodeToLLVMPass ()
std::unique_ptr<::mlir::Pass > mlir::createReconcileUnrealizedCastsPass ()
std::unique_ptr<::mlir::Pass > mlir::createSCFToControlFlowPass ()
std::unique_ptr<::mlir::Pass > mlir::createSCFToControlFlowPass (SCFToControlFlowPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createSCFToEmitC ()
std::unique_ptr<::mlir::Pass > mlir::createSCFToSPIRV ()
std::unique_ptr<::mlir::Pass > mlir::createSetLLVMModuleDataLayoutPass ()
std::unique_ptr<::mlir::Pass > mlir::createSetLLVMModuleDataLayoutPass (SetLLVMModuleDataLayoutPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createTosaToArithPass ()
std::unique_ptr<::mlir::Pass > mlir::createTosaToArithPass (TosaToArithPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createTosaToMLProgram ()
std::unique_ptr<::mlir::Pass > mlir::createTosaToSCFPass ()
std::unique_ptr<::mlir::Pass > mlir::createTosaToTensorPass ()
std::unique_ptr<::mlir::Pass > mlir::createUBToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createUBToLLVMConversionPass (UBToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createUBToSPIRVConversionPass ()
void mlir::registerArithToAMDGPUConversionPass ()
void mlir::registerArithToAMDGPUConversionPassPass ()
void mlir::registerArithToAPFloatConversionPass ()
void mlir::registerArithToAPFloatConversionPassPass ()
void mlir::registerArithToArmSMEConversionPass ()
void mlir::registerArithToArmSMEConversionPassPass ()
void mlir::registerArithToLLVMConversionPass ()
void mlir::registerArithToLLVMConversionPassPass ()
void mlir::registerConvertAMDGPUToROCDLPass ()
void mlir::registerConvertAMDGPUToROCDLPassPass ()
void mlir::registerConvertAffineForToGPUPass ()
void mlir::registerConvertAffineForToGPUPassPass ()
void mlir::registerConvertArithToEmitC ()
void mlir::registerConvertArithToEmitCPass ()
void mlir::registerConvertArithToSPIRVPass ()
void mlir::registerConvertArithToSPIRVPassPass ()
void mlir::registerConvertArmNeon2dToIntrPass ()
void mlir::registerConvertArmNeon2dToIntrPassPass ()
void mlir::registerConvertArmSMEToLLVM ()
void mlir::registerConvertArmSMEToLLVMPass ()
void mlir::registerConvertArmSMEToSCFPass ()
void mlir::registerConvertArmSMEToSCFPassPass ()
void mlir::registerConvertAsyncToLLVMPass ()
void mlir::registerConvertAsyncToLLVMPassPass ()
void mlir::registerConvertBufferizationToMemRefPass ()
void mlir::registerConvertBufferizationToMemRefPassPass ()
void mlir::registerConvertComplexToLLVMPass ()
void mlir::registerConvertComplexToLLVMPassPass ()
void mlir::registerConvertComplexToLibm ()
void mlir::registerConvertComplexToLibmPass ()
void mlir::registerConvertComplexToROCDLLibraryCalls ()
void mlir::registerConvertComplexToROCDLLibraryCallsPass ()
void mlir::registerConvertComplexToSPIRVPass ()
void mlir::registerConvertComplexToSPIRVPassPass ()
void mlir::registerConvertComplexToStandardPass ()
void mlir::registerConvertComplexToStandardPassPass ()
void mlir::registerConvertControlFlowToLLVMPass ()
void mlir::registerConvertControlFlowToLLVMPassPass ()
void mlir::registerConvertControlFlowToSPIRVPass ()
void mlir::registerConvertControlFlowToSPIRVPassPass ()
void mlir::registerConvertFuncToEmitC ()
void mlir::registerConvertFuncToEmitCPass ()
void mlir::registerConvertFuncToLLVMPass ()
void mlir::registerConvertFuncToLLVMPassPass ()
void mlir::registerConvertFuncToSPIRVPass ()
void mlir::registerConvertFuncToSPIRVPassPass ()
void mlir::registerConvertGPUToSPIRV ()
void mlir::registerConvertGPUToSPIRVPass ()
void mlir::registerConvertGpuOpsToLLVMSPVOps ()
void mlir::registerConvertGpuOpsToLLVMSPVOpsPass ()
void mlir::registerConvertGpuOpsToNVVMOps ()
void mlir::registerConvertGpuOpsToNVVMOpsPass ()
void mlir::registerConvertGpuOpsToROCDLOps ()
void mlir::registerConvertGpuOpsToROCDLOpsPass ()
void mlir::registerConvertIndexToLLVMPass ()
void mlir::registerConvertIndexToLLVMPassPass ()
void mlir::registerConvertIndexToSPIRVPass ()
void mlir::registerConvertIndexToSPIRVPassPass ()
void mlir::registerConvertLinalgToStandardPass ()
void mlir::registerConvertLinalgToStandardPassPass ()
void mlir::registerConvertMathToEmitC ()
void mlir::registerConvertMathToEmitCPass ()
void mlir::registerConvertMathToFuncs ()
void mlir::registerConvertMathToFuncsPass ()
void mlir::registerConvertMathToLLVMPass ()
void mlir::registerConvertMathToLLVMPassPass ()
void mlir::registerConvertMathToLibmPass ()
void mlir::registerConvertMathToLibmPassPass ()
void mlir::registerConvertMathToROCDL ()
void mlir::registerConvertMathToROCDLPass ()
void mlir::registerConvertMathToSPIRVPass ()
void mlir::registerConvertMathToSPIRVPassPass ()
void mlir::registerConvertMathToXeVM ()
void mlir::registerConvertMathToXeVMPass ()
void mlir::registerConvertMemRefToEmitC ()
void mlir::registerConvertMemRefToEmitCPass ()
void mlir::registerConvertMemRefToSPIRVPass ()
void mlir::registerConvertMemRefToSPIRVPassPass ()
void mlir::registerConvertNVGPUToNVVMPass ()
void mlir::registerConvertNVGPUToNVVMPassPass ()
void mlir::registerConvertNVVMToLLVMPass ()
void mlir::registerConvertNVVMToLLVMPassPass ()
void mlir::registerConvertOpenACCToSCFPass ()
void mlir::registerConvertOpenACCToSCFPassPass ()
void mlir::registerConvertOpenMPToLLVMPass ()
void mlir::registerConvertOpenMPToLLVMPassPass ()
void mlir::registerConvertPDLToPDLInterpPass ()
void mlir::registerConvertPDLToPDLInterpPassPass ()
void mlir::registerConvertParallelLoopToGpuPass ()
void mlir::registerConvertParallelLoopToGpuPassPass ()
void mlir::registerConvertSCFToOpenMPPass ()
void mlir::registerConvertSCFToOpenMPPassPass ()
void mlir::registerConvertSPIRVToLLVMPass ()
void mlir::registerConvertSPIRVToLLVMPassPass ()
void mlir::registerConvertShapeConstraintsPass ()
void mlir::registerConvertShapeConstraintsPassPass ()
void mlir::registerConvertShapeToStandardPass ()
void mlir::registerConvertShapeToStandardPassPass ()
void mlir::registerConvertShardToMPIPass ()
void mlir::registerConvertShardToMPIPassPass ()
void mlir::registerConvertTensorToLinalgPass ()
void mlir::registerConvertTensorToLinalgPassPass ()
void mlir::registerConvertTensorToSPIRVPass ()
void mlir::registerConvertTensorToSPIRVPassPass ()
void mlir::registerConvertToEmitC ()
void mlir::registerConvertToEmitCPass ()
void mlir::registerConvertToLLVMPass ()
void mlir::registerConvertToLLVMPassPass ()
void mlir::registerConvertVectorToAMX ()
void mlir::registerConvertVectorToAMXPass ()
void mlir::registerConvertVectorToArmSMEPass ()
void mlir::registerConvertVectorToArmSMEPassPass ()
void mlir::registerConvertVectorToGPU ()
void mlir::registerConvertVectorToGPUPass ()
void mlir::registerConvertVectorToLLVMPass ()
void mlir::registerConvertVectorToLLVMPassPass ()
void mlir::registerConvertVectorToSCF ()
void mlir::registerConvertVectorToSCFPass ()
void mlir::registerConvertVectorToSPIRVPass ()
void mlir::registerConvertVectorToSPIRVPassPass ()
void mlir::registerConvertVectorToXeGPU ()
void mlir::registerConvertVectorToXeGPUPass ()
void mlir::registerConvertXeGPUToXeVMPass ()
void mlir::registerConvertXeGPUToXeVMPassPass ()
void mlir::registerConvertXeVMToLLVMPass ()
void mlir::registerConvertXeVMToLLVMPassPass ()
void mlir::registerFinalizeMemRefToLLVMConversionPass ()
void mlir::registerFinalizeMemRefToLLVMConversionPassPass ()
void mlir::registerGpuToLLVMConversionPass ()
void mlir::registerGpuToLLVMConversionPassPass ()
void mlir::registerLiftControlFlowToSCFPass ()
void mlir::registerLiftControlFlowToSCFPassPass ()
void mlir::registerLowerAffinePass ()
void mlir::registerLowerAffinePassPass ()
void mlir::registerLowerHostCodeToLLVMPass ()
void mlir::registerLowerHostCodeToLLVMPassPass ()
void mlir::registerMapMemRefStorageClass ()
void mlir::registerMapMemRefStorageClassPass ()
void mlir::registerReconcileUnrealizedCastsPass ()
void mlir::registerReconcileUnrealizedCastsPassPass ()
void mlir::registerSCFToControlFlowPass ()
void mlir::registerSCFToControlFlowPassPass ()
void mlir::registerSCFToEmitC ()
void mlir::registerSCFToEmitCPass ()
void mlir::registerSCFToSPIRV ()
void mlir::registerSCFToSPIRVPass ()
void mlir::registerSetLLVMModuleDataLayoutPass ()
void mlir::registerSetLLVMModuleDataLayoutPassPass ()
void mlir::registerTosaToArithPass ()
void mlir::registerTosaToArithPassPass ()
void mlir::registerTosaToLinalg ()
void mlir::registerTosaToLinalgPass ()
void mlir::registerTosaToLinalgNamed ()
void mlir::registerTosaToLinalgNamedPass ()
void mlir::registerTosaToMLProgram ()
void mlir::registerTosaToMLProgramPass ()
void mlir::registerTosaToSCFPass ()
void mlir::registerTosaToSCFPassPass ()
void mlir::registerTosaToTensorPass ()
void mlir::registerTosaToTensorPassPass ()
void mlir::registerUBToLLVMConversionPass ()
void mlir::registerUBToLLVMConversionPassPass ()
void mlir::registerUBToSPIRVConversionPass ()
void mlir::registerUBToSPIRVConversionPassPass ()
void mlir::registerConversionPasses ()
static FuncOp createFnDecl (OpBuilder &b, SymbolOpInterface symTable, StringRef name, FunctionType funcT, bool setPrivate, SymbolTableCollection *symbolTables=nullptr)
static FailureOr< FuncOp > lookupOrCreateApFloatFn (OpBuilder &b, SymbolOpInterface symTable, StringRef name, TypeRange paramTypes, SymbolTableCollection *symbolTables=nullptr, Type resultType={})
Helper function to look up or create the symbol for a runtime library function with the given parameter types.
static FailureOr< FuncOp > lookupOrCreateBinaryFn (OpBuilder &b, SymbolOpInterface symTable, StringRef name, SymbolTableCollection *symbolTables=nullptr)
Helper function to look up or create the symbol for a runtime library function for a binary arithmetic operation.
static Value getSemanticsValue (OpBuilder &b, Location loc, FloatType floatTy)
template<typename Fn, typename... Values>
static Value forEachScalarValue (RewriterBase &rewriter, Location loc, Value operand1, Value operand2, Type resultType, Fn fn)
Given two operands of vector type and vector result type (with the same shape), call the given function for each pair of scalar operands and package the result into a vector.
static LogicalResult checkPreconditions (RewriterBase &rewriter, Operation *op)
Check preconditions for the conversion:
Macro Definition Documentation
GEN_PASS_DECL_ARITHTOAMDGPUCONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOAMDGPUCONVERSIONPASS
GEN_PASS_DECL_ARITHTOAPFLOATCONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOAPFLOATCONVERSIONPASS
GEN_PASS_DECL_ARITHTOARMSMECONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOARMSMECONVERSIONPASS
GEN_PASS_DECL_ARITHTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_ARITHTOLLVMCONVERSIONPASS
GEN_PASS_DECL_CONVERTAFFINEFORTOGPUPASS
#define GEN_PASS_DECL_CONVERTAFFINEFORTOGPUPASS
GEN_PASS_DECL_CONVERTAMDGPUTOROCDLPASS
#define GEN_PASS_DECL_CONVERTAMDGPUTOROCDLPASS
GEN_PASS_DECL_CONVERTARITHTOEMITC
#define GEN_PASS_DECL_CONVERTARITHTOEMITC
GEN_PASS_DECL_CONVERTARITHTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTARITHTOSPIRVPASS
GEN_PASS_DECL_CONVERTARMNEON2DTOINTRPASS
#define GEN_PASS_DECL_CONVERTARMNEON2DTOINTRPASS
GEN_PASS_DECL_CONVERTARMSMETOLLVM
#define GEN_PASS_DECL_CONVERTARMSMETOLLVM
GEN_PASS_DECL_CONVERTARMSMETOSCFPASS
#define GEN_PASS_DECL_CONVERTARMSMETOSCFPASS
GEN_PASS_DECL_CONVERTASYNCTOLLVMPASS
#define GEN_PASS_DECL_CONVERTASYNCTOLLVMPASS
GEN_PASS_DECL_CONVERTBUFFERIZATIONTOMEMREFPASS
#define GEN_PASS_DECL_CONVERTBUFFERIZATIONTOMEMREFPASS
GEN_PASS_DECL_CONVERTCOMPLEXTOLIBM
#define GEN_PASS_DECL_CONVERTCOMPLEXTOLIBM
GEN_PASS_DECL_CONVERTCOMPLEXTOLLVMPASS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOLLVMPASS
GEN_PASS_DECL_CONVERTCOMPLEXTOROCDLLIBRARYCALLS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOROCDLLIBRARYCALLS
GEN_PASS_DECL_CONVERTCOMPLEXTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOSPIRVPASS
GEN_PASS_DECL_CONVERTCOMPLEXTOSTANDARDPASS
#define GEN_PASS_DECL_CONVERTCOMPLEXTOSTANDARDPASS
GEN_PASS_DECL_CONVERTCONTROLFLOWTOLLVMPASS
#define GEN_PASS_DECL_CONVERTCONTROLFLOWTOLLVMPASS
GEN_PASS_DECL_CONVERTCONTROLFLOWTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTCONTROLFLOWTOSPIRVPASS
GEN_PASS_DECL_CONVERTFUNCTOEMITC
#define GEN_PASS_DECL_CONVERTFUNCTOEMITC
GEN_PASS_DECL_CONVERTFUNCTOLLVMPASS
#define GEN_PASS_DECL_CONVERTFUNCTOLLVMPASS
GEN_PASS_DECL_CONVERTFUNCTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTFUNCTOSPIRVPASS
GEN_PASS_DECL_CONVERTGPUOPSTOLLVMSPVOPS
#define GEN_PASS_DECL_CONVERTGPUOPSTOLLVMSPVOPS
GEN_PASS_DECL_CONVERTGPUOPSTONVVMOPS
#define GEN_PASS_DECL_CONVERTGPUOPSTONVVMOPS
GEN_PASS_DECL_CONVERTGPUOPSTOROCDLOPS
#define GEN_PASS_DECL_CONVERTGPUOPSTOROCDLOPS
GEN_PASS_DECL_CONVERTGPUTOSPIRV
#define GEN_PASS_DECL_CONVERTGPUTOSPIRV
GEN_PASS_DECL_CONVERTINDEXTOLLVMPASS
#define GEN_PASS_DECL_CONVERTINDEXTOLLVMPASS
GEN_PASS_DECL_CONVERTINDEXTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTINDEXTOSPIRVPASS
GEN_PASS_DECL_CONVERTLINALGTOSTANDARDPASS
#define GEN_PASS_DECL_CONVERTLINALGTOSTANDARDPASS
GEN_PASS_DECL_CONVERTMATHTOEMITC
#define GEN_PASS_DECL_CONVERTMATHTOEMITC
GEN_PASS_DECL_CONVERTMATHTOFUNCS
#define GEN_PASS_DECL_CONVERTMATHTOFUNCS
GEN_PASS_DECL_CONVERTMATHTOLIBMPASS
#define GEN_PASS_DECL_CONVERTMATHTOLIBMPASS
GEN_PASS_DECL_CONVERTMATHTOLLVMPASS
#define GEN_PASS_DECL_CONVERTMATHTOLLVMPASS
GEN_PASS_DECL_CONVERTMATHTOROCDL
#define GEN_PASS_DECL_CONVERTMATHTOROCDL
GEN_PASS_DECL_CONVERTMATHTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTMATHTOSPIRVPASS
GEN_PASS_DECL_CONVERTMATHTOXEVM
#define GEN_PASS_DECL_CONVERTMATHTOXEVM
GEN_PASS_DECL_CONVERTMEMREFTOEMITC
#define GEN_PASS_DECL_CONVERTMEMREFTOEMITC
GEN_PASS_DECL_CONVERTMEMREFTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTMEMREFTOSPIRVPASS
GEN_PASS_DECL_CONVERTNVGPUTONVVMPASS
#define GEN_PASS_DECL_CONVERTNVGPUTONVVMPASS
GEN_PASS_DECL_CONVERTNVVMTOLLVMPASS
#define GEN_PASS_DECL_CONVERTNVVMTOLLVMPASS
GEN_PASS_DECL_CONVERTOPENACCTOSCFPASS
#define GEN_PASS_DECL_CONVERTOPENACCTOSCFPASS
GEN_PASS_DECL_CONVERTOPENMPTOLLVMPASS
#define GEN_PASS_DECL_CONVERTOPENMPTOLLVMPASS
GEN_PASS_DECL_CONVERTPARALLELLOOPTOGPUPASS
#define GEN_PASS_DECL_CONVERTPARALLELLOOPTOGPUPASS
GEN_PASS_DECL_CONVERTPDLTOPDLINTERPPASS
#define GEN_PASS_DECL_CONVERTPDLTOPDLINTERPPASS
GEN_PASS_DECL_CONVERTSCFTOOPENMPPASS
#define GEN_PASS_DECL_CONVERTSCFTOOPENMPPASS
GEN_PASS_DECL_CONVERTSHAPECONSTRAINTSPASS
#define GEN_PASS_DECL_CONVERTSHAPECONSTRAINTSPASS
GEN_PASS_DECL_CONVERTSHAPETOSTANDARDPASS
#define GEN_PASS_DECL_CONVERTSHAPETOSTANDARDPASS
GEN_PASS_DECL_CONVERTSHARDTOMPIPASS
#define GEN_PASS_DECL_CONVERTSHARDTOMPIPASS
GEN_PASS_DECL_CONVERTSPIRVTOLLVMPASS
#define GEN_PASS_DECL_CONVERTSPIRVTOLLVMPASS
GEN_PASS_DECL_CONVERTTENSORTOLINALGPASS
#define GEN_PASS_DECL_CONVERTTENSORTOLINALGPASS
GEN_PASS_DECL_CONVERTTENSORTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTTENSORTOSPIRVPASS
GEN_PASS_DECL_CONVERTTOEMITC
#define GEN_PASS_DECL_CONVERTTOEMITC
GEN_PASS_DECL_CONVERTTOLLVMPASS
#define GEN_PASS_DECL_CONVERTTOLLVMPASS
GEN_PASS_DECL_CONVERTVECTORTOAMX
#define GEN_PASS_DECL_CONVERTVECTORTOAMX
GEN_PASS_DECL_CONVERTVECTORTOARMSMEPASS
#define GEN_PASS_DECL_CONVERTVECTORTOARMSMEPASS
GEN_PASS_DECL_CONVERTVECTORTOGPU
#define GEN_PASS_DECL_CONVERTVECTORTOGPU
GEN_PASS_DECL_CONVERTVECTORTOLLVMPASS
#define GEN_PASS_DECL_CONVERTVECTORTOLLVMPASS
GEN_PASS_DECL_CONVERTVECTORTOSCF
#define GEN_PASS_DECL_CONVERTVECTORTOSCF
GEN_PASS_DECL_CONVERTVECTORTOSPIRVPASS
#define GEN_PASS_DECL_CONVERTVECTORTOSPIRVPASS
GEN_PASS_DECL_CONVERTVECTORTOXEGPU
#define GEN_PASS_DECL_CONVERTVECTORTOXEGPU
GEN_PASS_DECL_CONVERTXEGPUTOXEVMPASS
#define GEN_PASS_DECL_CONVERTXEGPUTOXEVMPASS
GEN_PASS_DECL_CONVERTXEVMTOLLVMPASS
#define GEN_PASS_DECL_CONVERTXEVMTOLLVMPASS
GEN_PASS_DECL_FINALIZEMEMREFTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_FINALIZEMEMREFTOLLVMCONVERSIONPASS
GEN_PASS_DECL_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_GPUTOLLVMCONVERSIONPASS
GEN_PASS_DECL_LIFTCONTROLFLOWTOSCFPASS
#define GEN_PASS_DECL_LIFTCONTROLFLOWTOSCFPASS
GEN_PASS_DECL_LOWERAFFINEPASS
#define GEN_PASS_DECL_LOWERAFFINEPASS
GEN_PASS_DECL_LOWERHOSTCODETOLLVMPASS
#define GEN_PASS_DECL_LOWERHOSTCODETOLLVMPASS
GEN_PASS_DECL_MAPMEMREFSTORAGECLASS
#define GEN_PASS_DECL_MAPMEMREFSTORAGECLASS
GEN_PASS_DECL_RECONCILEUNREALIZEDCASTSPASS
#define GEN_PASS_DECL_RECONCILEUNREALIZEDCASTSPASS
GEN_PASS_DECL_SCFTOCONTROLFLOWPASS
#define GEN_PASS_DECL_SCFTOCONTROLFLOWPASS
GEN_PASS_DECL_SCFTOEMITC
#define GEN_PASS_DECL_SCFTOEMITC
GEN_PASS_DECL_SCFTOSPIRV
#define GEN_PASS_DECL_SCFTOSPIRV
GEN_PASS_DECL_SETLLVMMODULEDATALAYOUTPASS
#define GEN_PASS_DECL_SETLLVMMODULEDATALAYOUTPASS
GEN_PASS_DECL_TOSATOARITHPASS
#define GEN_PASS_DECL_TOSATOARITHPASS
GEN_PASS_DECL_TOSATOLINALG
#define GEN_PASS_DECL_TOSATOLINALG
GEN_PASS_DECL_TOSATOLINALGNAMED
#define GEN_PASS_DECL_TOSATOLINALGNAMED
GEN_PASS_DECL_TOSATOMLPROGRAM
#define GEN_PASS_DECL_TOSATOMLPROGRAM
GEN_PASS_DECL_TOSATOSCFPASS
#define GEN_PASS_DECL_TOSATOSCFPASS
GEN_PASS_DECL_TOSATOTENSORPASS
#define GEN_PASS_DECL_TOSATOTENSORPASS
GEN_PASS_DECL_UBTOLLVMCONVERSIONPASS
#define GEN_PASS_DECL_UBTOLLVMCONVERSIONPASS
GEN_PASS_DECL_UBTOSPIRVCONVERSIONPASS
#define GEN_PASS_DECL_UBTOSPIRVCONVERSIONPASS
GEN_PASS_DEF_ARITHTOAPFLOATCONVERSIONPASS
#define GEN_PASS_DEF_ARITHTOAPFLOATCONVERSIONPASS
Definition at line 21 of file ArithToAPFloat.cpp.
GEN_PASS_REGISTRATION_ARITHTOAMDGPUCONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOAMDGPUCONVERSIONPASS
GEN_PASS_REGISTRATION_ARITHTOAPFLOATCONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOAPFLOATCONVERSIONPASS
GEN_PASS_REGISTRATION_ARITHTOARMSMECONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOARMSMECONVERSIONPASS
GEN_PASS_REGISTRATION_ARITHTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_ARITHTOLLVMCONVERSIONPASS
GEN_PASS_REGISTRATION_CONVERTAFFINEFORTOGPUPASS
#define GEN_PASS_REGISTRATION_CONVERTAFFINEFORTOGPUPASS
GEN_PASS_REGISTRATION_CONVERTAMDGPUTOROCDLPASS
#define GEN_PASS_REGISTRATION_CONVERTAMDGPUTOROCDLPASS
GEN_PASS_REGISTRATION_CONVERTARITHTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTARITHTOEMITC
GEN_PASS_REGISTRATION_CONVERTARITHTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTARITHTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTARMNEON2DTOINTRPASS
#define GEN_PASS_REGISTRATION_CONVERTARMNEON2DTOINTRPASS
GEN_PASS_REGISTRATION_CONVERTARMSMETOLLVM
#define GEN_PASS_REGISTRATION_CONVERTARMSMETOLLVM
GEN_PASS_REGISTRATION_CONVERTARMSMETOSCFPASS
#define GEN_PASS_REGISTRATION_CONVERTARMSMETOSCFPASS
GEN_PASS_REGISTRATION_CONVERTASYNCTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTASYNCTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTBUFFERIZATIONTOMEMREFPASS
#define GEN_PASS_REGISTRATION_CONVERTBUFFERIZATIONTOMEMREFPASS
GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOLIBM
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOLIBM
GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOROCDLLIBRARYCALLS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOROCDLLIBRARYCALLS
GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOSTANDARDPASS
#define GEN_PASS_REGISTRATION_CONVERTCOMPLEXTOSTANDARDPASS
GEN_PASS_REGISTRATION_CONVERTCONTROLFLOWTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTCONTROLFLOWTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTCONTROLFLOWTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTCONTROLFLOWTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTFUNCTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTFUNCTOEMITC
GEN_PASS_REGISTRATION_CONVERTFUNCTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTFUNCTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTFUNCTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTFUNCTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTGPUOPSTOLLVMSPVOPS
#define GEN_PASS_REGISTRATION_CONVERTGPUOPSTOLLVMSPVOPS
GEN_PASS_REGISTRATION_CONVERTGPUOPSTONVVMOPS
#define GEN_PASS_REGISTRATION_CONVERTGPUOPSTONVVMOPS
GEN_PASS_REGISTRATION_CONVERTGPUOPSTOROCDLOPS
#define GEN_PASS_REGISTRATION_CONVERTGPUOPSTOROCDLOPS
GEN_PASS_REGISTRATION_CONVERTGPUTOSPIRV
#define GEN_PASS_REGISTRATION_CONVERTGPUTOSPIRV
GEN_PASS_REGISTRATION_CONVERTINDEXTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTINDEXTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTINDEXTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTINDEXTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTLINALGTOSTANDARDPASS
#define GEN_PASS_REGISTRATION_CONVERTLINALGTOSTANDARDPASS
GEN_PASS_REGISTRATION_CONVERTMATHTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTMATHTOEMITC
GEN_PASS_REGISTRATION_CONVERTMATHTOFUNCS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOFUNCS
GEN_PASS_REGISTRATION_CONVERTMATHTOLIBMPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOLIBMPASS
GEN_PASS_REGISTRATION_CONVERTMATHTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTMATHTOROCDL
#define GEN_PASS_REGISTRATION_CONVERTMATHTOROCDL
GEN_PASS_REGISTRATION_CONVERTMATHTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTMATHTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTMATHTOXEVM
#define GEN_PASS_REGISTRATION_CONVERTMATHTOXEVM
GEN_PASS_REGISTRATION_CONVERTMEMREFTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTMEMREFTOEMITC
GEN_PASS_REGISTRATION_CONVERTMEMREFTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTMEMREFTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTNVGPUTONVVMPASS
#define GEN_PASS_REGISTRATION_CONVERTNVGPUTONVVMPASS
GEN_PASS_REGISTRATION_CONVERTNVVMTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTNVVMTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTOPENACCTOSCFPASS
#define GEN_PASS_REGISTRATION_CONVERTOPENACCTOSCFPASS
GEN_PASS_REGISTRATION_CONVERTOPENMPTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTOPENMPTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTPARALLELLOOPTOGPUPASS
#define GEN_PASS_REGISTRATION_CONVERTPARALLELLOOPTOGPUPASS
GEN_PASS_REGISTRATION_CONVERTPDLTOPDLINTERPPASS
#define GEN_PASS_REGISTRATION_CONVERTPDLTOPDLINTERPPASS
GEN_PASS_REGISTRATION_CONVERTSCFTOOPENMPPASS
#define GEN_PASS_REGISTRATION_CONVERTSCFTOOPENMPPASS
GEN_PASS_REGISTRATION_CONVERTSHAPECONSTRAINTSPASS
#define GEN_PASS_REGISTRATION_CONVERTSHAPECONSTRAINTSPASS
GEN_PASS_REGISTRATION_CONVERTSHAPETOSTANDARDPASS
#define GEN_PASS_REGISTRATION_CONVERTSHAPETOSTANDARDPASS
GEN_PASS_REGISTRATION_CONVERTSHARDTOMPIPASS
#define GEN_PASS_REGISTRATION_CONVERTSHARDTOMPIPASS
GEN_PASS_REGISTRATION_CONVERTSPIRVTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTSPIRVTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTTENSORTOLINALGPASS
#define GEN_PASS_REGISTRATION_CONVERTTENSORTOLINALGPASS
GEN_PASS_REGISTRATION_CONVERTTENSORTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTTENSORTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTTOEMITC
#define GEN_PASS_REGISTRATION_CONVERTTOEMITC
GEN_PASS_REGISTRATION_CONVERTTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTVECTORTOAMX
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOAMX
GEN_PASS_REGISTRATION_CONVERTVECTORTOARMSMEPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOARMSMEPASS
GEN_PASS_REGISTRATION_CONVERTVECTORTOGPU
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOGPU
GEN_PASS_REGISTRATION_CONVERTVECTORTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOLLVMPASS
GEN_PASS_REGISTRATION_CONVERTVECTORTOSCF
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOSCF
GEN_PASS_REGISTRATION_CONVERTVECTORTOSPIRVPASS
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOSPIRVPASS
GEN_PASS_REGISTRATION_CONVERTVECTORTOXEGPU
#define GEN_PASS_REGISTRATION_CONVERTVECTORTOXEGPU
GEN_PASS_REGISTRATION_CONVERTXEGPUTOXEVMPASS
#define GEN_PASS_REGISTRATION_CONVERTXEGPUTOXEVMPASS
GEN_PASS_REGISTRATION_CONVERTXEVMTOLLVMPASS
#define GEN_PASS_REGISTRATION_CONVERTXEVMTOLLVMPASS
GEN_PASS_REGISTRATION_FINALIZEMEMREFTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_FINALIZEMEMREFTOLLVMCONVERSIONPASS
GEN_PASS_REGISTRATION_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_GPUTOLLVMCONVERSIONPASS
GEN_PASS_REGISTRATION_LIFTCONTROLFLOWTOSCFPASS
#define GEN_PASS_REGISTRATION_LIFTCONTROLFLOWTOSCFPASS
GEN_PASS_REGISTRATION_LOWERAFFINEPASS
#define GEN_PASS_REGISTRATION_LOWERAFFINEPASS
GEN_PASS_REGISTRATION_LOWERHOSTCODETOLLVMPASS
#define GEN_PASS_REGISTRATION_LOWERHOSTCODETOLLVMPASS
GEN_PASS_REGISTRATION_MAPMEMREFSTORAGECLASS
#define GEN_PASS_REGISTRATION_MAPMEMREFSTORAGECLASS
GEN_PASS_REGISTRATION_RECONCILEUNREALIZEDCASTSPASS
#define GEN_PASS_REGISTRATION_RECONCILEUNREALIZEDCASTSPASS
GEN_PASS_REGISTRATION_SCFTOCONTROLFLOWPASS
#define GEN_PASS_REGISTRATION_SCFTOCONTROLFLOWPASS
GEN_PASS_REGISTRATION_SCFTOEMITC
#define GEN_PASS_REGISTRATION_SCFTOEMITC
GEN_PASS_REGISTRATION_SCFTOSPIRV
#define GEN_PASS_REGISTRATION_SCFTOSPIRV
GEN_PASS_REGISTRATION_SETLLVMMODULEDATALAYOUTPASS
#define GEN_PASS_REGISTRATION_SETLLVMMODULEDATALAYOUTPASS
GEN_PASS_REGISTRATION_TOSATOARITHPASS
#define GEN_PASS_REGISTRATION_TOSATOARITHPASS
GEN_PASS_REGISTRATION_TOSATOLINALG
#define GEN_PASS_REGISTRATION_TOSATOLINALG
GEN_PASS_REGISTRATION_TOSATOLINALGNAMED
#define GEN_PASS_REGISTRATION_TOSATOLINALGNAMED
GEN_PASS_REGISTRATION_TOSATOMLPROGRAM
#define GEN_PASS_REGISTRATION_TOSATOMLPROGRAM
GEN_PASS_REGISTRATION_TOSATOSCFPASS
#define GEN_PASS_REGISTRATION_TOSATOSCFPASS
GEN_PASS_REGISTRATION_TOSATOTENSORPASS
#define GEN_PASS_REGISTRATION_TOSATOTENSORPASS
GEN_PASS_REGISTRATION_UBTOLLVMCONVERSIONPASS
#define GEN_PASS_REGISTRATION_UBTOLLVMCONVERSIONPASS
GEN_PASS_REGISTRATION_UBTOSPIRVCONVERSIONPASS
#define GEN_PASS_REGISTRATION_UBTOSPIRVCONVERSIONPASS
Function Documentation
checkPreconditions()
LogicalResult checkPreconditions (RewriterBase & rewriter, Operation * op) static
Check preconditions for the conversion:
All operands / results must be integers or floats (or vectors thereof).
The bitwidth of the operands / results must be <= 64.
Definition at line 144 of file ArithToAPFloat.cpp.
References mlir::Type::getIntOrFloatBitWidth(), mlir::Operation::getOperands(), mlir::Operation::getResults(), mlir::Type::isIntOrFloat(), mlir::RewriterBase::notifyMatchFailure(), and success().
Referenced by BinaryArithOpToAPFloatConversion< OpTy >::matchAndRewrite(), CmpFOpToAPFloatConversion::matchAndRewrite(), FpToIntConversion< OpTy >::matchAndRewrite(), IntToFpConversion< OpTy >::matchAndRewrite(), and NegFOpToAPFloatConversion::matchAndRewrite().
createFnDecl()
FuncOp createFnDecl (OpBuilder & b, SymbolOpInterface symTable, StringRef name, FunctionType funcT, bool setPrivate, SymbolTableCollection * symbolTables = nullptr) static
Definition at line 28 of file ArithToAPFloat.cpp.
References b, and mlir::SymbolTable::insert().
forEachScalarValue()
template<typename Fn, typename... Values> Value forEachScalarValue (RewriterBase & rewriter, Location loc, Value operand1, Value operand2, Type resultType, Fn fn) static
Given two operands of vector type and vector result type (with the same shape), call the given function for each pair of scalar operands and package the result into a vector.
If the given operands and result type are not vectors, call the function directly. The second operand is optional.
Definition at line 99 of file ArithToAPFloat.cpp.
References mlir::Value::getType(), and result.
Referenced by BinaryArithOpToAPFloatConversion< OpTy >::matchAndRewrite(), CmpFOpToAPFloatConversion::matchAndRewrite(), FpToIntConversion< OpTy >::matchAndRewrite(), IntToFpConversion< OpTy >::matchAndRewrite(), and NegFOpToAPFloatConversion::matchAndRewrite().
getSemanticsValue()
Value getSemanticsValue (OpBuilder & b, Location loc, FloatType floatTy) static
Definition at line 88 of file ArithToAPFloat.cpp.
References b.
Referenced by IntToFpConversion< OpTy >::matchAndRewrite().
lookupOrCreateApFloatFn()
FailureOr< FuncOp > lookupOrCreateApFloatFn (OpBuilder & b, SymbolOpInterface symTable, StringRef name, TypeRange paramTypes, SymbolTableCollection * symbolTables = nullptr, Type resultType = {}) static
Helper function to look up or create the symbol for a runtime library function with the given parameter types.
Returns an int64_t, unless a different result type is specified.
Definition at line 48 of file ArithToAPFloat.cpp.
References b.
Referenced by lookupOrCreateBinaryFn(), CmpFOpToAPFloatConversion::matchAndRewrite(), FpToIntConversion< OpTy >::matchAndRewrite(), IntToFpConversion< OpTy >::matchAndRewrite(), and NegFOpToAPFloatConversion::matchAndRewrite().
lookupOrCreateBinaryFn()
FailureOr< FuncOp > lookupOrCreateBinaryFn (OpBuilder & b, SymbolOpInterface symTable, StringRef name, SymbolTableCollection * symbolTables = nullptr) static
Helper function to look up or create the symbol for a runtime library function for a binary arithmetic operation.
Parameter 1: APFloat semantics Parameter 2: Left-hand side operand Parameter 3: Right-hand side operand
This function will return a failure if the function is found but has an unexpected signature.
Definition at line 80 of file ArithToAPFloat.cpp.
References b, and lookupOrCreateApFloatFn().
Referenced by BinaryArithOpToAPFloatConversion< OpTy >::matchAndRewrite().