MLIR: lib/Dialect/Arith/IR/InferIntDivisibilityOpInterfaceImpl.cpp File Reference
InferIntDivisibilityOpInterfaceImpl.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Interfaces/InferIntDivisibilityOpInterface.h"
#include <cstdlib>
Functions
static ConstantIntDivisibility getDivisibilityOfOperand (Value v, IntegerDivisibility divisibility)
template<typename OpTy>
static void inferBinaryGCDResultDivisibility (OpTy op, ArrayRef< IntegerDivisibility > argDivs, SetIntDivisibilityFn setResultDivs)
Function Documentation
getDivisibilityOfOperand()
ConstantIntDivisibility getDivisibilityOfOperand (Value v, IntegerDivisibility divisibility) static
Definition at line 23 of file InferIntDivisibilityOpInterfaceImpl.cpp.
References mlir::IntegerDivisibility::getValue(), mlir::IntegerDivisibility::isUninitialized(), mlir::m_ConstantInt(), and mlir::matchPattern().
Referenced by inferBinaryGCDResultDivisibility().
inferBinaryGCDResultDivisibility()
template<typename OpTy> void inferBinaryGCDResultDivisibility (OpTy op, ArrayRef< IntegerDivisibility > argDivs, SetIntDivisibilityFn setResultDivs) static
Definition at line 38 of file InferIntDivisibilityOpInterfaceImpl.cpp.
References getDivisibilityOfOperand().