MLIR: lib/Conversion/ArithToAMDGPU/ArithToAMDGPU.cpp File Reference
ArithToAMDGPU.cpp File Reference
#include "mlir/Conversion/ArithToAMDGPU/ArithToAMDGPU.h"
#include "mlir/Dialect/AMDGPU/IR/AMDGPUDialect.h"
#include "mlir/Dialect/AMDGPU/Utils/Chipset.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorRewritePatterns.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Conversion/Passes.h.inc"
Classes
class mlir::impl::ArithToAMDGPUConversionPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_ARITHTOAMDGPUCONVERSIONPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToAMDGPUConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToAMDGPUConversionPass (ArithToAMDGPUConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createArithToAMDGPUConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createArithToAMDGPUConversionPass (ArithToAMDGPUConversionPassOptions options)
static bool isSupportedF8 (Type elementType, Chipset chipset)
static Value castF32To (Type desType, Value f32, Location loc, PatternRewriter &rewriter)
static Value castToF32 (Value value, Location loc, PatternRewriter &rewriter)
static Value clampInput (PatternRewriter &rewriter, Location loc, Type outElemType, Value source)
static Value getOriginalVectorValue (Value value)
Get the broadcasted / splatted value for a chain of ops.
Macro Definition Documentation
GEN_PASS_DEF_ARITHTOAMDGPUCONVERSIONPASS
#define GEN_PASS_DEF_ARITHTOAMDGPUCONVERSIONPASS
Definition at line 28 of file ArithToAMDGPU.cpp.
Function Documentation
castF32To()
Value castF32To (Type desType, Value f32, Location loc, PatternRewriter & rewriter) static
Definition at line 107 of file ArithToAMDGPU.cpp.
References mlir::getElementTypeOrSelf(), mlir::Type::getIntOrFloatBitWidth(), and mlir::Type::isF32().
Referenced by mlir::impl::ArithToAMDGPUConversionPassBase< DerivedT >::createArithToAMDGPUConversionPass.
castToF32()
Value castToF32 (Value value, Location loc, PatternRewriter & rewriter) static
Definition at line 201 of file ArithToAMDGPU.cpp.
References mlir::Builder::getF32Type(), mlir::Type::getIntOrFloatBitWidth(), mlir::Value::getType(), and mlir::Type::isF32().
clampInput()
Value clampInput (PatternRewriter & rewriter, Location loc, Type outElemType, Value source) static
Definition at line 217 of file ArithToAMDGPU.cpp.
References mlir::OpBuilder::createOrFold(), mlir::createScalarOrSplatConstant(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), max(), and min().
getOriginalVectorValue()
Value getOriginalVectorValue (Value value) static
Get the broadcasted / splatted value for a chain of ops.
Definition at line 423 of file ArithToAMDGPU.cpp.
References mlir::Value::getDefiningOp().
isSupportedF8()
bool isSupportedF8 (Type elementType, Chipset chipset) static
Definition at line 99 of file ArithToAMDGPU.cpp.
References mlir::amdgpu::hasOcpFp8(), and kGfx942.