MLIR: lib/Dialect/Arith/Transforms/ReifyValueBounds.cpp File Reference
ReifyValueBounds.cpp File Reference
#include <utility>
#include "mlir/Dialect/Arith/Transforms/Transforms.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Interfaces/ValueBoundsOpInterface.h"
Functions
static Value buildArithValue (OpBuilder &b, Location loc, AffineMap map, ValueRange operands)
Build Arith IR for the given affine map and its operands.
Function Documentation
buildArithValue()
Value buildArithValue (OpBuilder & b, Location loc, AffineMap map, ValueRange operands) static
Build Arith IR for the given affine map and its operands.
Definition at line 22 of file ReifyValueBounds.cpp.
References mlir::Add, b, mlir::CeilDiv, mlir::Constant, mlir::arith::ConstantIndexOp::create(), mlir::DimId, mlir::FloorDiv, mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by mlir::arith::reifyValueBound().