MLIR: lib/Dialect/ArmSVE/IR/ArmSVEDialect.cpp File Reference
ArmSVEDialect.cpp File Reference
#include "mlir/Dialect/ArmSVE/ArmSVEDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/ArmSVE/ArmSVEDialect.cpp.inc"
#include "mlir/Dialect/ArmSVE/ArmSVE.cpp.inc"
#include "mlir/Dialect/ArmSVE/ArmSVETypes.cpp.inc"
Macros
#define GET_OP_CLASSES
#define GET_TYPEDEF_CLASSES
#define GET_OP_LIST
#define GET_TYPEDEF_LIST
Functions
static Type getI1SameShape (Type type)
static void buildScalableCmpIOp (OpBuilder &build, OperationState &result, CmpIPredicate predicate, Value lhs, Value rhs)
static void buildScalableCmpFOp (OpBuilder &build, OperationState &result, CmpFPredicate predicate, Value lhs, Value rhs)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 33 of file ArmSVEDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 36 of file ArmSVEDialect.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
buildScalableCmpFOp()
static void buildScalableCmpFOp (OpBuilder & build, OperationState & result, CmpFPredicate predicate, Value lhs, Value rhs) static
Definition at line 89 of file ArmSVEDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
buildScalableCmpIOp()
static void buildScalableCmpIOp (OpBuilder & build, OperationState & result, CmpIPredicate predicate, Value lhs, Value rhs) static
Definition at line 97 of file ArmSVEDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
getI1SameShape()
static Type getI1SameShape (Type type) static
Definition at line 77 of file ArmSVEDialect.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::getContext().
Referenced by buildScalableCmpFOp(), and buildScalableCmpIOp().