MLIR: lib/Dialect/ArmSVE/Transforms/LegalizeForLLVMExport.cpp File Reference
LegalizeForLLVMExport.cpp File Reference
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Dialect/ArmSVE/ArmSVEDialect.h"
#include "mlir/Dialect/ArmSVE/Transforms.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
Classes
class ForwardOperands< OpTy >
class ReturnOpTypeConversion
struct ScalableLoadOpLowering
struct ScalableStoreOpLowering
Typedefs
using SdotOpLowering = OneToOneConvertToLLVMPattern< SdotOp, SdotIntrOp >
using SmmlaOpLowering = OneToOneConvertToLLVMPattern< SmmlaOp, SmmlaIntrOp >
using UdotOpLowering = OneToOneConvertToLLVMPattern< UdotOp, UdotIntrOp >
using UmmlaOpLowering = OneToOneConvertToLLVMPattern< UmmlaOp, UmmlaIntrOp >
using VectorScaleOpLowering = OneToOneConvertToLLVMPattern< VectorScaleOp, VectorScaleIntrOp >
using ScalableMaskedAddIOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedAddIOp, ScalableMaskedAddIIntrOp >
using ScalableMaskedAddFOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedAddFOp, ScalableMaskedAddFIntrOp >
using ScalableMaskedSubIOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedSubIOp, ScalableMaskedSubIIntrOp >
using ScalableMaskedSubFOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedSubFOp, ScalableMaskedSubFIntrOp >
using ScalableMaskedMulIOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedMulIOp, ScalableMaskedMulIIntrOp >
using ScalableMaskedMulFOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedMulFOp, ScalableMaskedMulFIntrOp >
using ScalableMaskedSDivIOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedSDivIOp, ScalableMaskedSDivIIntrOp >
using ScalableMaskedUDivIOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedUDivIOp, ScalableMaskedUDivIIntrOp >
using ScalableMaskedDivFOpLowering = OneToOneConvertToLLVMPattern< ScalableMaskedDivFOp, ScalableMaskedDivFIntrOp >
Functions
static Type unwrap (Type type)
static Optional< Type > convertScalableVectorTypeToLLVM (ScalableVectorType svType, LLVMTypeConverter &converter)
static Optional< Value > addUnrealizedCast (OpBuilder &builder, ScalableVectorType svType, ValueRange inputs, Location loc)
static void populateBasicSVEArithmeticExportPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
static void configureBasicSVEArithmeticLegalizations (LLVMConversionTarget &target)
static void populateSVEMaskGenerationExportPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
static void configureSVEMaskGenerationLegalizations (LLVMConversionTarget &target)
Typedef Documentation
ScalableMaskedAddFOpLowering
using ScalableMaskedAddFOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedAddFOp, ScalableMaskedAddFIntrOp>
Definition at line 92 of file LegalizeForLLVMExport.cpp.
ScalableMaskedAddIOpLowering
using ScalableMaskedAddIOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedAddIOp, ScalableMaskedAddIIntrOp>
Definition at line 89 of file LegalizeForLLVMExport.cpp.
ScalableMaskedDivFOpLowering
using ScalableMaskedDivFOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedDivFOp, ScalableMaskedDivFIntrOp>
Definition at line 113 of file LegalizeForLLVMExport.cpp.
ScalableMaskedMulFOpLowering
using ScalableMaskedMulFOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedMulFOp, ScalableMaskedMulFIntrOp>
Definition at line 104 of file LegalizeForLLVMExport.cpp.
ScalableMaskedMulIOpLowering
using ScalableMaskedMulIOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedMulIOp, ScalableMaskedMulIIntrOp>
Definition at line 101 of file LegalizeForLLVMExport.cpp.
ScalableMaskedSDivIOpLowering
using ScalableMaskedSDivIOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedSDivIOp, ScalableMaskedSDivIIntrOp>
Definition at line 107 of file LegalizeForLLVMExport.cpp.
ScalableMaskedSubFOpLowering
using ScalableMaskedSubFOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedSubFOp, ScalableMaskedSubFIntrOp>
Definition at line 98 of file LegalizeForLLVMExport.cpp.
ScalableMaskedSubIOpLowering
using ScalableMaskedSubIOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedSubIOp, ScalableMaskedSubIIntrOp>
Definition at line 95 of file LegalizeForLLVMExport.cpp.
ScalableMaskedUDivIOpLowering
using ScalableMaskedUDivIOpLowering = OneToOneConvertToLLVMPattern<ScalableMaskedUDivIOp, ScalableMaskedUDivIIntrOp>
Definition at line 110 of file LegalizeForLLVMExport.cpp.
SdotOpLowering
using SdotOpLowering = OneToOneConvertToLLVMPattern<SdotOp, SdotIntrOp>
Definition at line 81 of file LegalizeForLLVMExport.cpp.
SmmlaOpLowering
using SmmlaOpLowering = OneToOneConvertToLLVMPattern<SmmlaOp, SmmlaIntrOp>
Definition at line 82 of file LegalizeForLLVMExport.cpp.
UdotOpLowering
using UdotOpLowering = OneToOneConvertToLLVMPattern<UdotOp, UdotIntrOp>
Definition at line 83 of file LegalizeForLLVMExport.cpp.
UmmlaOpLowering
using UmmlaOpLowering = OneToOneConvertToLLVMPattern<UmmlaOp, UmmlaIntrOp>
Definition at line 84 of file LegalizeForLLVMExport.cpp.
VectorScaleOpLowering
using VectorScaleOpLowering = OneToOneConvertToLLVMPattern<VectorScaleOp, VectorScaleIntrOp>
Definition at line 86 of file LegalizeForLLVMExport.cpp.
Function Documentation
addUnrealizedCast()
static Optional<Value> addUnrealizedCast (OpBuilder & builder, ScalableVectorType svType, ValueRange inputs, Location loc) static
Definition at line 71 of file LegalizeForLLVMExport.cpp.
References mlir::OpBuilder::create(), mlir::ValueRange::getType(), and loc.
Referenced by mlir::populateArmSVELegalizeForLLVMExportPatterns().
configureBasicSVEArithmeticLegalizations()
static void configureBasicSVEArithmeticLegalizations (LLVMConversionTarget & target) static
Definition at line 207 of file LegalizeForLLVMExport.cpp.
References mlir::ConversionTarget::addIllegalOp().
Referenced by mlir::configureArmSVELegalizeForExportTarget().
configureSVEMaskGenerationLegalizations()
static void configureSVEMaskGenerationLegalizations (LLVMConversionTarget & target) static
Definition at line 232 of file LegalizeForLLVMExport.cpp.
References mlir::ConversionTarget::addIllegalOp().
Referenced by mlir::configureArmSVELegalizeForExportTarget().
convertScalableVectorTypeToLLVM()
static Optional<Type> convertScalableVectorTypeToLLVM (ScalableVectorType svType, LLVMTypeConverter & converter) static
Definition at line 33 of file LegalizeForLLVMExport.cpp.
References mlir::TypeConverter::convertType(), elementType(), mlir::LLVM::LLVMScalableVectorType::get(), and unwrap().
Referenced by ScalableLoadOpLowering::matchAndRewrite(), ScalableStoreOpLowering::matchAndRewrite(), and mlir::populateArmSVELegalizeForLLVMExportPatterns().
populateBasicSVEArithmeticExportPatterns()
static void populateBasicSVEArithmeticExportPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns) static
Definition at line 190 of file LegalizeForLLVMExport.cpp.
References mlir::RewritePatternSet::add().
Referenced by mlir::populateArmSVELegalizeForLLVMExportPatterns().
populateSVEMaskGenerationExportPatterns()
static void populateSVEMaskGenerationExportPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns) static
Definition at line 222 of file LegalizeForLLVMExport.cpp.
References mlir::RewritePatternSet::add().
Referenced by mlir::populateArmSVELegalizeForLLVMExportPatterns().
unwrap()
static Type unwrap (Type type) static
Definition at line 22 of file LegalizeForLLVMExport.cpp.
References mlir::emitError(), mlir::Type::getContext(), and mlir::LLVM::isCompatibleType().
Referenced by convertScalableVectorTypeToLLVM().