MLIR: lib/IR/AsmPrinter.cpp File Reference
AsmPrinter.cpp File Reference
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/SubElementInterfaces.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SaveAndRestore.h"
#include <tuple>
#include "mlir/IR/OpAsmInterface.cpp.inc"
Classes
class mlir::detail::AsmStateImpl
Namespaces
mlir
Include the generated interface declarations.
mlir::detail
Functions
static bool shouldPrintElementsAttrWithHex (int64_t numElements)
Returns true if an ElementsAttr with the given number of elements should be printed with hex.
static raw_ostream & operator<< (raw_ostream &os, NewLineCounter &newLine)
static StringRef sanitizeIdentifier (StringRef name, SmallString< 16 > &buffer, StringRef allowedPunctChars="$._-", bool allowTrailingDigit=true)
Sanitize the given name such that it can be used as a valid identifier.
template<typename T >
static void initializeAliases (llvm::MapVector< StringRef, std::vector< T >> &aliasToSymbol, llvm::MapVector< T, SymbolAlias > &symbolToAlias, DenseSet< T > *deferrableAliases=nullptr)
Given a collection of aliases and symbols, initialize a mapping from a symbol to a given alias.
static void printFloatValue (const APFloat &apValue, raw_ostream &os)
Print a floating point value in a way that the parser will be able to round-trip losslessly.
static bool isDialectSymbolSimpleEnoughForPrettyForm (StringRef symName)
Returns true if the given dialect symbol data is simple enough to print in the pretty form, i.e.
static void printDialectSymbol (raw_ostream &os, StringRef symPrefix, StringRef dialectName, StringRef symString)
Print the given dialect symbol to the stream.
static bool isBareIdentifier (StringRef name)
Returns true if the given string can be represented as a bare identifier.
static void printSymbolReference (StringRef symbolRef, raw_ostream &os)
Print the given string as a symbol reference.
static void printElidedElementsAttr (raw_ostream &os)
static void printDenseIntElement (const APInt &value, raw_ostream &os, bool isSigned)
Print the integer element of a DenseElementsAttr.
static void printDenseElementsAttrImpl (bool isSplat, ShapedType type, raw_ostream &os, function_ref< void(unsigned)> printEltFn)
Variables
static llvm::ManagedStatic< AsmPrinterOptions > clOptions
Function Documentation
initializeAliases()
template<typename T > static void initializeAliases (llvm::MapVector< StringRef, std::vector< T >> & aliasToSymbol, llvm::MapVector< T, SymbolAlias > & symbolToAlias, DenseSet< T > * deferrableAliases = nullptr) static
Given a collection of aliases and symbols, initialize a mapping from a symbol to a given alias.
Definition at line 572 of file AsmPrinter.cpp.
References mlir::Value::cast(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Value::dyn_cast(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::Region::getArgument(), mlir::Block::getArguments(), mlir::Value::getDefiningOp(), mlir::Operation::getDialect(), mlir::DialectInterfaceCollection< InterfaceType >::getInterfaceFor(), mlir::Region::getNumArguments(), mlir::Operation::getNumResults(), mlir::Region::getOps(), mlir::BlockArgument::getOwner(), mlir::OpResult::getOwner(), mlir::Block::getParentOp(), mlir::Region::getParentOp(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::OpResult::getResultNumber(), mlir::Operation::hasTrait(), mlir::Block::isEntryBlock(), op, sanitizeIdentifier(), mlir::OpPrintingFlags::shouldPrintGenericOpForm(), mlir::succeeded(), mlir::success(), and value.
isBareIdentifier()
static bool isBareIdentifier (StringRef name) static
Returns true if the given string can be represented as a bare identifier.
Definition at line 1527 of file AsmPrinter.cpp.
Referenced by printDenseElementsAttrImpl(), and printSymbolReference().
isDialectSymbolSimpleEnoughForPrettyForm()
static bool isDialectSymbolSimpleEnoughForPrettyForm (StringRef symName) static
Returns true if the given dialect symbol data is simple enough to print in the pretty form, i.e.
without the enclosing "".
Definition at line 1437 of file AsmPrinter.cpp.
Referenced by printDialectSymbol().
operator<<()
static raw_ostream& operator<< (raw_ostream & os, NewLineCounter & newLine) static
Definition at line 254 of file AsmPrinter.cpp.
References mlir::Block::back(), mlir::Block::begin(), mlir::Region::empty(), mlir::Block::empty(), mlir::Block::end(), mlir::Region::front(), mlir::Operation::getAbstractOperation(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Operation::getLoc(), mlir::BlockArgument::getLoc(), mlir::Operation::getNumRegions(), mlir::Operation::getOperandTypes(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::Operation::hasTrait(), op, print(), printNewline(), mlir::LLVM::detail::printType(), mlir::OpPrintingFlags::shouldPrintDebugInfo(), and mlir::OpPrintingFlags::shouldPrintGenericOpForm().
printDenseElementsAttrImpl()
static void printDenseElementsAttrImpl (bool isSplat, ShapedType type, raw_ostream & os, function_ref< void(unsigned)> printEltFn) static
Definition at line 1726 of file AsmPrinter.cpp.
References mlir::Add, mlir::Block::args_empty(), mlir::Block::back(), mlir::Block::begin(), mlir::Attribute::cast(), mlir::AffineExpr::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::Attribute::dyn_cast(), mlir::AffineExpr::dyn_cast(), mlir::Type::dyn_cast(), elementType(), mlir::Region::empty(), mlir::Block::empty(), mlir::Block::end(), mlir::FloorDiv, mlir::Region::front(), mlir::Operation::getAbstractOperation(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Region::getBlocks(), mlir::Attribute::getDialect(), mlir::Operation::getDialect(), mlir::Type::getDialect(), mlir::ShapedType::getElementType(), mlir::AffineExpr::getKind(), mlir::Operation::getLoc(), mlir::BlockArgument::getLoc(), mlir::Operation::getName(), mlir::AffineMap::getNumDims(), mlir::ShapedType::getNumElements(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getNumSuccessors(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getOperands(), mlir::Block::getParent(), mlir::Block::getPredecessors(), mlir::ShapedType::getRank(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::AffineMap::getResults(), mlir::ShapedType::getShape(), mlir::Block::getSinglePredecessor(), mlir::detail::AsmStateImpl::getSSANameState(), mlir::OperationName::getStringRef(), mlir::Operation::getSuccessors(), mlir::Value::getType(), mlir::Block::hasNoPredecessors(), mlir::Operation::hasTrait(), mlir::Type::isa(), isBareIdentifier(), mlir::ShapedType::isDynamic(), mlir::Type::isIntOrIndex(), mlir::Type::isUnsignedInteger(), map(), mlir::Mod, mlir::Mul, print(), printDenseIntElement(), printDialectSymbol(), printFloatValue(), printNewline(), printSymbolReference(), mlir::LLVM::detail::printType(), shouldPrintElementsAttrWithHex(), mlir::OpPrintingFlags::shouldPrintGenericOpForm(), mlir::succeeded(), mlir::SymbolId, and value.
printDenseIntElement()
static void printDenseIntElement (const APInt & value, raw_ostream & os, bool isSigned) static
Print the integer element of a DenseElementsAttr.
Definition at line 1717 of file AsmPrinter.cpp.
Referenced by printDenseElementsAttrImpl().
printDialectSymbol()
static void printDialectSymbol (raw_ostream & os, StringRef symPrefix, StringRef dialectName, StringRef symString) static
Print the given dialect symbol to the stream.
Definition at line 1510 of file AsmPrinter.cpp.
References isDialectSymbolSimpleEnoughForPrettyForm().
Referenced by printDenseElementsAttrImpl(), and printElidedElementsAttr().
printElidedElementsAttr()
static void printElidedElementsAttr (raw_ostream & os) static
Definition at line 1569 of file AsmPrinter.cpp.
References mlir::Attribute::dyn_cast(), mlir::Attribute::getType(), mlir::Attribute::isa(), print(), printDialectSymbol(), printFloatValue(), mlir::LLVM::detail::printType(), and mlir::succeeded().
printFloatValue()
static void printFloatValue (const APFloat & apValue, raw_ostream & os) static
Print a floating point value in a way that the parser will be able to round-trip losslessly.
Definition at line 1377 of file AsmPrinter.cpp.
References mlir::failed(), and mlir::OpPrintingFlags::shouldPrintDebugInfoPrettyForm().
Referenced by printDenseElementsAttrImpl(), and printElidedElementsAttr().
printSymbolReference()
static void printSymbolReference (StringRef symbolRef, raw_ostream & os) static
Print the given string as a symbol reference.
A symbol reference is represented as a string prefixed with '@'. The reference is surrounded with ""'s and escaped if it has any special or non-printable characters in it.
Definition at line 1545 of file AsmPrinter.cpp.
References isBareIdentifier().
Referenced by printDenseElementsAttrImpl().
sanitizeIdentifier()
static StringRef sanitizeIdentifier (StringRef name, SmallString< 16 > & buffer, StringRef allowedPunctChars = "$._-", bool allowTrailingDigit = true) static
Sanitize the given name such that it can be used as a valid identifier.
If the string needs to be modified in any way, the provided buffer is used to store the new copy,
Definition at line 523 of file AsmPrinter.cpp.
Referenced by initializeAliases().
shouldPrintElementsAttrWithHex()
static bool shouldPrintElementsAttrWithHex (int64_t numElements) static
Returns true if an ElementsAttr with the given number of elements should be printed with hex.
Definition at line 226 of file AsmPrinter.cpp.
References clOptions.
Referenced by printDenseElementsAttrImpl().
Variable Documentation
clOptions
llvm::ManagedStatic<AsmPrinterOptions> clOptions static
Definition at line 138 of file AsmPrinter.cpp.
Referenced by mlir::OpPrintingFlags::OpPrintingFlags(), mlir::registerAsmPrinterCLOptions(), and shouldPrintElementsAttrWithHex().