MLIR: lib/Dialect/Async/Transforms/AsyncParallelFor.cpp File Reference
AsyncParallelFor.cpp File Reference
#include "mlir/Dialect/Async/Passes.h"
#include "PassDetail.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/Async/Transforms.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/RegionUtils.h"
#include <utility>
#include "mlir/Dialect/Async/Passes.h.inc"
Classes
class mlir::impl::AsyncParallelForPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_ASYNCPARALLELFORPASS
#define DEBUG_TYPE "async-parallel-for"
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncParallelForPass ()
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncParallelForPass (AsyncParallelForPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createAsyncParallelForPass ()
std::unique_ptr<::mlir::Pass > mlir::createAsyncParallelForPass (AsyncParallelForPassOptions options)
template<typename ValueRange>
static SmallVector< IntegerAttr > integerConstants (ValueRange values)
static SmallVector< Value > delinearize (ImplicitLocOpBuilder &b, Value index, ArrayRef< Value > tripCounts)
static ParallelComputeFunctionType getParallelComputeFunctionType (scf::ParallelOp op, PatternRewriter &rewriter)
static ParallelComputeFunction createParallelComputeFunction (scf::ParallelOp op, const ParallelComputeFunctionBounds &bounds, unsigned numBlockAlignedInnerLoops, PatternRewriter &rewriter)
static func::FuncOp createAsyncDispatchFunction (ParallelComputeFunction &computeFunc, PatternRewriter &rewriter)
static void doAsyncDispatch (ImplicitLocOpBuilder &b, PatternRewriter &rewriter, ParallelComputeFunction &parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > &tripCounts)
static void doSequentialDispatch (ImplicitLocOpBuilder &b, PatternRewriter &rewriter, ParallelComputeFunction &parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > &tripCounts)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "async-parallel-for"
Definition at line 37 of file AsyncParallelFor.cpp.
GEN_PASS_DEF_ASYNCPARALLELFORPASS
#define GEN_PASS_DEF_ASYNCPARALLELFORPASS
Definition at line 30 of file AsyncParallelFor.cpp.
Function Documentation
createAsyncDispatchFunction()
func::FuncOp createAsyncDispatchFunction (ParallelComputeFunction & computeFunc, PatternRewriter & rewriter) static
Definition at line 453 of file AsyncParallelFor.cpp.
References b, mlir::arith::ConstantIndexOp::create(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Builder::getContext(), mlir::Builder::getFunctionType(), mlir::Builder::getIndexType(), mlir::OpBuilder::getListener(), mlir::SymbolTable::insert(), mlir::OpBuilder::Listener::notifyOperationInserted(), TypeRange, and ValueRange.
Referenced by doAsyncDispatch().
createParallelComputeFunction()
ParallelComputeFunction createParallelComputeFunction (scf::ParallelOp op, const ParallelComputeFunctionBounds & bounds, unsigned numBlockAlignedInnerLoops, PatternRewriter & rewriter) static
Definition at line 241 of file AsyncParallelFor.cpp.
References b, mlir::arith::ConstantIndexOp::create(), mlir::delinearize(), mlir::OpBuilder::getListener(), getParallelComputeFunctionType(), mlir::SymbolTable::insert(), mlir::IRMapping::map(), mlir::OpBuilder::Listener::notifyOperationInserted(), and ValueRange.
delinearize()
SmallVector< Value > delinearize (ImplicitLocOpBuilder & b, Value index, ArrayRef< Value > tripCounts) static
Definition at line 187 of file AsyncParallelFor.cpp.
References b.
doAsyncDispatch()
void doAsyncDispatch (ImplicitLocOpBuilder & b, PatternRewriter & rewriter, ParallelComputeFunction & parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > & tripCounts) static
Definition at line 568 of file AsyncParallelFor.cpp.
References b, mlir::arith::ConstantIndexOp::create(), and createAsyncDispatchFunction().
doSequentialDispatch()
void doSequentialDispatch (ImplicitLocOpBuilder & b, PatternRewriter & rewriter, ParallelComputeFunction & parallelComputeFunction, scf::ParallelOp op, Value blockSize, Value blockCount, const SmallVector< Value > & tripCounts) static
Definition at line 641 of file AsyncParallelFor.cpp.
References b, mlir::arith::ConstantIndexOp::create(), mlir::Builder::getIndexType(), TypeRange, and ValueRange.
getParallelComputeFunctionType()
ParallelComputeFunctionType getParallelComputeFunctionType (scf::ParallelOp op, PatternRewriter & rewriter) static
Definition at line 204 of file AsyncParallelFor.cpp.
References mlir::Builder::getFunctionType(), mlir::Builder::getIndexType(), mlir::getUsedValuesDefinedAbove(), and TypeRange.
Referenced by createParallelComputeFunction().
integerConstants()
template<typename ValueRange> SmallVector< IntegerAttr > integerConstants (ValueRange values) static
Definition at line 178 of file AsyncParallelFor.cpp.