MLIR: lib/TableGen/Attribute.cpp File Reference
Attribute.cpp File Reference
#include "mlir/TableGen/Format.h"
#include "mlir/TableGen/Operator.h"
#include "llvm/TableGen/Record.h"
Functions
static StringRef getValueAsString (const Init *init)
Function Documentation
getValueAsString()
static StringRef getValueAsString (const Init * init) static
Definition at line 28 of file Attribute.cpp.
Referenced by mlir::tblgen::Attribute::getConstBuilderTemplate(), mlir::tblgen::Attribute::getConvertFromStorageCall(), mlir::tblgen::Attribute::getDefaultValue(), mlir::tblgen::Attribute::getReturnType(), mlir::tblgen::Attribute::getStorageType(), mlir::tblgen::Attribute::hasDefaultValue(), and mlir::tblgen::Attribute::isConstBuildable().