MLIR: lib/IR/AttrTypeSubElements.cpp File Reference
AttrTypeSubElements.cpp File Reference
#include "mlir/IR/Operation.h"
#include <optional>
Functions
template<typename T, typename Replacer>
static void updateSubElementImpl (T element, Replacer &replacer, SmallVectorImpl< T > &newElements, FailureOr< bool > &changed)
template<typename T, typename Replacer>
static T replaceSubElements (T interface, Replacer &replacer)
template<typename T, typename ReplaceFns, typename Replacer>
static T replaceElementImpl (T element, ReplaceFns &replaceFns, Replacer &replacer)
Shared implementation of replacing a given attribute or type element.
Function Documentation
replaceElementImpl()
template<typename T, typename ReplaceFns, typename Replacer> T replaceElementImpl (T element, ReplaceFns & replaceFns, Replacer & replacer) static
Shared implementation of replacing a given attribute or type element.
Definition at line 193 of file AttrTypeSubElements.cpp.
References mlir::WalkResult::advance(), replaceSubElements(), result, mlir::WalkResult::wasInterrupted(), and mlir::WalkResult::wasSkipped().
Referenced by mlir::detail::AttrTypeReplacerBase< Concrete >::replaceBase(), and mlir::detail::AttrTypeReplacerBase< Concrete >::replaceBase().
replaceSubElements()
template<typename T, typename Replacer> T replaceSubElements (T interface, Replacer & replacer) static
Definition at line 169 of file AttrTypeSubElements.cpp.
References mlir::changed, result, and updateSubElementImpl().
Referenced by replaceElementImpl().
updateSubElementImpl()
template<typename T, typename Replacer> void updateSubElementImpl (T element, Replacer & replacer, SmallVectorImpl< T > & newElements, FailureOr< bool > & changed) static
Definition at line 145 of file AttrTypeSubElements.cpp.
Referenced by replaceSubElements().