MLIR: lib/Bindings/Python/TransformInterpreter.cpp File Reference
TransformInterpreter.cpp File Reference
#include "mlir-c/Dialect/Transform/Interpreter.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Bindings/Python/Diagnostics.h"
#include "mlir/Bindings/Python/IRCore.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Classes
struct mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::python
namespace mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN
namespace mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter
Functions
static void populateTransformInterpreterSubmodule (nb::module_ &m)
NB_MODULE (_mlirTransformInterpreter, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlirTransformInterpreter , m)
Definition at line 116 of file TransformInterpreter.cpp.
References populateTransformInterpreterSubmodule().
populateTransformInterpreterSubmodule()
void populateTransformInterpreterSubmodule (nb::module_ & m) static
Definition at line 44 of file TransformInterpreter.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), mlirLogicalResultIsFailure(), mlirLogicalResultIsSuccess(), mlirMergeSymbolsIntoFromClone(), mlirOperationGetContext(), mlirTransformApplyNamedSequence(), mlirTransformOptionsEnableExpensiveChecks(), mlirTransformOptionsEnforceSingleTopLevelTransformOp(), mlirTransformOptionsGetEnforceSingleTopLevelTransformOp(), mlirTransformOptionsGetExpensiveChecksEnabled(), options, result, mlir::python::CollectDiagnosticsToStringScope::takeMessage(), and target.
Referenced by NB_MODULE().