MLIR: lib/Dialect/Bufferization/IR/BufferDeallocationOpInterface.cpp File Reference
BufferDeallocationOpInterface.cpp File Reference
#include "mlir/Dialect/Bufferization/IR/BufferDeallocationOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "llvm/ADT/SetOperations.h"
#include "mlir/Dialect/Bufferization/IR/BufferDeallocationOpInterface.cpp.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Functions
static Value buildBoolValue (OpBuilder &builder, Location loc, bool value)
static bool isMemref (Value v)
Function Documentation
buildBoolValue()
static Value buildBoolValue (OpBuilder & builder, Location loc, bool value) static
Definition at line 37 of file BufferDeallocationOpInterface.cpp.
References mlir::Builder::getBoolAttr().
Referenced by mlir::bufferization::DeallocationState::getMemrefWithUniqueOwnership().
isMemref()
static bool isMemref (Value v) static
Definition at line 41 of file BufferDeallocationOpInterface.cpp.
References mlir::Value::getType().
Referenced by mlir::bufferization::DeallocationState::getLiveMemrefsIn(), and mlir::bufferization::DeallocationState::getMemrefsToRetain().