MLIR: lib/Dialect/Bufferization/Transforms/BufferViewFlowAnalysis.cpp File Reference
BufferViewFlowAnalysis.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/BufferViewFlowAnalysis.h"
#include "mlir/Dialect/Bufferization/IR/BufferViewFlowOpInterface.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "llvm/ADT/SetOperations.h"
Functions
static BufferViewFlowAnalysis::ValueSetT resolveValues (const BufferViewFlowAnalysis::ValueMapT &map, Value value)
static bool hasAllocateSideEffect (Value v)
Return "true" if the given value is the result of a memory allocation.
static bool isFunctionArgument (Value v)
Return "true" if the given value is a function block argument.
static Value getViewBase (Value value)
Given a memref value, return the "base" value by skipping over all ViewLikeOpInterface ops (if any) in the reverse use-def chain.
Function Documentation
getViewBase()
static Value getViewBase (Value value) static
Given a memref value, return the "base" value by skipping over all ViewLikeOpInterface ops (if any) in the reverse use-def chain.
Definition at line 233 of file BufferViewFlowAnalysis.cpp.
References mlir::Value::getDefiningOp().
Referenced by mlir::BufferOriginAnalysis::isSameAllocation().
hasAllocateSideEffect()
static bool hasAllocateSideEffect (Value v) static
Return "true" if the given value is the result of a memory allocation.
Definition at line 212 of file BufferViewFlowAnalysis.cpp.
References mlir::Value::getDefiningOp().
Referenced by mlir::BufferOriginAnalysis::isSameAllocation().
isFunctionArgument()
static bool isFunctionArgument (Value v) static
Return "true" if the given value is a function block argument.
Definition at line 220 of file BufferViewFlowAnalysis.cpp.
References mlir::Block::getParentOp().
Referenced by mlir::BufferOriginAnalysis::isSameAllocation().
resolveValues()
static BufferViewFlowAnalysis::ValueSetT resolveValues (const BufferViewFlowAnalysis::ValueMapT & map, Value value) static
Definition at line 29 of file BufferViewFlowAnalysis.cpp.
Referenced by mlir::BufferViewFlowAnalysis::resolve(), and mlir::BufferViewFlowAnalysis::resolveReverse().