MLIR: lib/Transforms/BufferDeallocation.cpp File Reference
BufferDeallocation.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/LoopLikeInterface.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/BufferUtils.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SetOperations.h"
Functions
template<typename FuncT >
static void walkReturnOperations (Region *region, const FuncT &func)
Walks over all immediate return-like terminators in the given region.
static bool validateSupportedControlFlow (Region &region)
Checks if all operations in a given region have at least one attached region that implements the RegionBranchOpInterface.
Function Documentation
validateSupportedControlFlow()
static bool validateSupportedControlFlow (Region & region) static
Checks if all operations in a given region have at least one attached region that implements the RegionBranchOpInterface.
This is not required in edge cases, where we have a single attached region and the parent operation has no results.
Definition at line 81 of file BufferDeallocation.cpp.
References mlir::OpBuilder::create(), mlir::Operation::emitError(), mlir::Region::front(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::LivenessBlockInfo::getEndOperation(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::BlockArgument::getOwner(), mlir::Block::getParent(), mlir::Value::getParentBlock(), mlir::Region::getParentOp(), mlir::Region::getRegionNumber(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::RegionSuccessor::getSuccessor(), mlir::Operation::getSuccessor(), mlir::RegionSuccessor::getSuccessorInputs(), mlir::Block::getSuccessors(), mlir::Value::isa(), mlir::Operation::isBeforeInBlock(), mlir::Operation::moveAfter(), op, mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::Operation::setOperand(), mlir::success(), value, mlir::Region::walk(), and walkReturnOperations().
walkReturnOperations()
template<typename FuncT > static void walkReturnOperations (Region * region, const FuncT & func) static
Walks over all immediate return-like terminators in the given region.
Definition at line 68 of file BufferDeallocation.cpp.
Referenced by validateSupportedControlFlow().