MLIR: lib/IR/Builders.cpp File Reference
Builders.cpp File Reference
#include "mlir/IR/Builders.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Matchers.h"
#include "llvm/ADT/SmallVectorExtras.h"
#include "llvm/Support/DebugLog.h"
Functions
static void notifyBlockInsertions (Operation *op, OpBuilder::Listener *listener)
Helper function that sends block insertion notifications for every block that is directly nested in the given op.
Function Documentation
notifyBlockInsertions()
void notifyBlockInsertions (Operation * op, OpBuilder::Listener * listener) static
Helper function that sends block insertion notifications for every block that is directly nested in the given op.
Definition at line 554 of file Builders.cpp.
References b, mlir::Operation::getRegions(), and mlir::OpBuilder::Listener::notifyBlockInserted().
Referenced by mlir::OpBuilder::clone(), and mlir::OpBuilder::cloneRegionBefore().