MLIR: lib/IR/BuiltinDialect.cpp File Reference
BuiltinDialect.cpp File Reference
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/MapVector.h"
#include "mlir/IR/BuiltinDialect.cpp.inc"
#include "mlir/IR/BuiltinOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static ParseResult parseFuncOp (OpAsmParser &parser, OperationState &result)
static void print (FuncOp op, OpAsmPrinter &p)
static LogicalResult verify (FuncOp op)
static LogicalResult verify (ModuleOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 321 of file BuiltinDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseFuncOp()
static ParseResult parseFuncOp (OpAsmParser & parser, OperationState & result) static
Definition at line 115 of file BuiltinDialect.cpp.
References mlir::Builder::getFunctionType(), and mlir::function_like_impl::parseFunctionLikeOp().
print()
static void print (FuncOp op, OpAsmPrinter & p) static
Definition at line 126 of file BuiltinDialect.cpp.
References mlir::function_like_impl::printFunctionLikeOp().
verify() [1/2]
static LogicalResult verify (FuncOp op) static
Definition at line 132 of file BuiltinDialect.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::BlockAndValueMapping::contains(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::Operation::emitOpError(), mlir::Region::emplaceBlock(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Attribute::getContext(), mlir::impl::getDataLayoutSpec(), mlir::Builder::getNamedAttr(), mlir::Block::getNumArguments(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::Value::getType(), loc, mlir::NamedAttrList::push_back(), and mlir::success().
verify() [2/2]
static LogicalResult verify (ModuleOp op) static
Definition at line 245 of file BuiltinDialect.cpp.
References mlir::InFlightDiagnostic::attachNote(), diag(), mlir::failure(), mlir::Value::getDefiningOp(), mlir::SymbolTable::getSymbolAttrName(), mlir::OperandRange::getType(), mlir::ResultRange::getType(), mlir::ResultRange::getTypes(), mlir::SymbolTable::getVisibilityAttrName(), and mlir::success().