MLIR: include/mlir-c/BuiltinTypes.h File Reference
BuiltinTypes.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include <stdint.h>
Functions
MLIR_CAPI_EXPORTED bool mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
MLIR_CAPI_EXPORTED unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
MLIR_CAPI_EXPORTED bool mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
MLIR_CAPI_EXPORTED MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
MLIR_CAPI_EXPORTED MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
MLIR_CAPI_EXPORTED MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
MLIR_CAPI_EXPORTED MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
MLIR_CAPI_EXPORTED MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
MLIR_CAPI_EXPORTED MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
MLIR_CAPI_EXPORTED MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks wither the dim-th dimension of the given shaped type is dynamic.
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
MLIR_CAPI_EXPORTED bool mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGet (intptr_t rank, const int64_t *shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, MlirType elementType)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED bool mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
MLIR_CAPI_EXPORTED bool mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGet (intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute encoding)
Creates a tensor type of a fixed rank with the given shape, element type, and optional encoding in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute encoding)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirAttribute mlirRankedTensorTypeGetEncoding (MlirType type)
Gets the 'encoding' attribute from the ranked tensor type, returning a null attribute if none.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGetChecked (MlirLocation loc, MlirType elementType)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED bool mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, const int64_t *shape, intptr_t numMaps, MlirAffineMap const *affineMaps, MlirAttribute memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t *shape, intptr_t numMaps, MlirAffineMap const *affineMaps, MlirAttribute memorySpace)
Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute memorySpace)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, MlirAttribute memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, MlirAttribute memorySpace)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED intptr_t mlirMemRefTypeGetNumAffineMaps (MlirType type)
Returns the number of affine layout maps in the given MemRef type.
MLIR_CAPI_EXPORTED MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type, intptr_t pos)
Returns the pos-th affine map of the given MemRef type.
MLIR_CAPI_EXPORTED MlirAttribute mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
MLIR_CAPI_EXPORTED MlirAttribute mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
MLIR_CAPI_EXPORTED bool mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType const *elements)
Creates a tuple type that consists of the given list of elemental types.
MLIR_CAPI_EXPORTED intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType const *inputs, intptr_t numResults, MlirType const *results)
Creates a function type, mapping a list of input types to result types.
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
Function Documentation
mlirBF16TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
The type is owned by the context.
Definition at line 72 of file BuiltinTypes.cpp.
References mlir::FloatType::getBF16(), unwrap(), and wrap().
mlirComplexTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 112 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirComplexTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
Definition at line 116 of file BuiltinTypes.cpp.
References getElementType(), unwrap(), and wrap().
mlirF16TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
The type is owned by the context.
Definition at line 78 of file BuiltinTypes.cpp.
References mlir::FloatType::getF16(), unwrap(), and wrap().
mlirF32TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
The type is owned by the context.
Definition at line 84 of file BuiltinTypes.cpp.
References mlir::FloatType::getF32(), unwrap(), and wrap().
mlirF64TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
The type is owned by the context.
Definition at line 90 of file BuiltinTypes.cpp.
References mlir::FloatType::getF64(), unwrap(), and wrap().
mlirFunctionTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType const * inputs, intptr_t numResults, MlirType const * results)
Creates a function type, mapping a list of input types to result types.
Definition at line 331 of file BuiltinTypes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirFunctionTypeGetInput()
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
Definition at line 349 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFunctionTypeGetNumInputs()
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
Definition at line 341 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGetNumResults()
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
Definition at line 345 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGetResult()
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
Definition at line 355 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIndexTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
The type is owned by the context.
Definition at line 62 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIntegerTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 28 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOpView::buildGeneric().
mlirIntegerTypeGetWidth()
MLIR_CAPI_EXPORTED unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
Definition at line 40 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsSigned()
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
Definition at line 48 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsSignless()
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
Definition at line 44 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsUnsigned()
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
Definition at line 52 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeSignedGet()
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 32 of file BuiltinTypes.cpp.
References mlir::quant::QuantizationFlags::Signed, unwrap(), and wrap().
mlirIntegerTypeUnsignedGet()
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 36 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeContiguousGet()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
The type has no affine maps, i.e. represents a default row-major contiguous memref. The type is owned by the context.
Definition at line 251 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeContiguousGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute memorySpace)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 259 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, const int64_t * shape, intptr_t numMaps, MlirAffineMap const * affineMaps, MlirAttribute memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
The type is owned by the context.
Definition at line 228 of file BuiltinTypes.cpp.
References maps, unwrap(), unwrapList(), and wrap().
mlirMemRefTypeGetAffineMap()
MLIR_CAPI_EXPORTED MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type, intptr_t pos)
Returns the pos-th affine map of the given MemRef type.
Definition at line 273 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t * shape, intptr_t numMaps, MlirAffineMap const * affineMaps, MlirAttribute memorySpace)
Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o illegal arguments, emitting appropriate diagnostics.
Definition at line 239 of file BuiltinTypes.cpp.
References maps, unwrap(), unwrapList(), and wrap().
mlirMemRefTypeGetMemorySpace()
MLIR_CAPI_EXPORTED MlirAttribute mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
Definition at line 277 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetNumAffineMaps()
MLIR_CAPI_EXPORTED intptr_t mlirMemRefTypeGetNumAffineMaps (MlirType type)
Returns the number of affine layout maps in the given MemRef type.
Definition at line 268 of file BuiltinTypes.cpp.
References unwrap().
mlirNoneTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
The type is owned by the context.
Definition at line 100 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGet (intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute encoding)
Creates a tensor type of a fixed rank with the given shape, element type, and optional encoding in the same context as the element type.
The type is owned by the context. Tensor types without any specific encoding field should assign mlirAttributeGetNull() to this parameter.
Definition at line 193 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute encoding)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 200 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetEncoding()
MLIR_CAPI_EXPORTED MlirAttribute mlirRankedTensorTypeGetEncoding (MlirType type)
Gets the 'encoding' attribute from the ranked tensor type, returning a null attribute if none.
Definition at line 209 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirShapedTypeGetDimSize()
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
Definition at line 147 of file BuiltinTypes.cpp.
References unwrap().
mlirShapedTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
Definition at line 126 of file BuiltinTypes.cpp.
References getElementType(), unwrap(), and wrap().
mlirShapedTypeGetRank()
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
Definition at line 134 of file BuiltinTypes.cpp.
References unwrap().
mlirShapedTypeHasRank()
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
Definition at line 130 of file BuiltinTypes.cpp.
References unwrap().
mlirShapedTypeHasStaticShape()
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
Definition at line 138 of file BuiltinTypes.cpp.
References unwrap().
mlirShapedTypeIsDynamicDim()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks wither the dim-th dimension of the given shaped type is dynamic.
Definition at line 142 of file BuiltinTypes.cpp.
References unwrap().
mlirShapedTypeIsDynamicSize()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
Definition at line 151 of file BuiltinTypes.cpp.
References mlir::ShapedType::isDynamic().
mlirShapedTypeIsDynamicStrideOrOffset()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
Definition at line 155 of file BuiltinTypes.cpp.
References mlir::ShapedType::isDynamicStrideOrOffset().
mlirTupleTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType const * elements)
Creates a tuple type that consists of the given list of elemental types.
The type is owned by the context.
Definition at line 308 of file BuiltinTypes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirTupleTypeGetNumTypes()
MLIR_CAPI_EXPORTED intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
Definition at line 315 of file BuiltinTypes.cpp.
References unwrap().
mlirTupleTypeGetType()
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
Definition at line 319 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirTypeIsABF16()
MLIR_CAPI_EXPORTED bool mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
Definition at line 70 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAComplex()
MLIR_CAPI_EXPORTED bool mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
Definition at line 108 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF16()
MLIR_CAPI_EXPORTED bool mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
Definition at line 76 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF32()
MLIR_CAPI_EXPORTED bool mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
Definition at line 82 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF64()
MLIR_CAPI_EXPORTED bool mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
Definition at line 88 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFunction()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
Definition at line 327 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAIndex()
MLIR_CAPI_EXPORTED bool mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
Definition at line 60 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAInteger()
MLIR_CAPI_EXPORTED bool mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
Definition at line 24 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAMemRef()
MLIR_CAPI_EXPORTED bool mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
Definition at line 226 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsANone()
MLIR_CAPI_EXPORTED bool mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
Definition at line 98 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsARankedTensor()
MLIR_CAPI_EXPORTED bool mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
Definition at line 185 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAShaped()
MLIR_CAPI_EXPORTED bool mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
Definition at line 124 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATensor()
MLIR_CAPI_EXPORTED bool mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
Definition at line 183 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATuple()
MLIR_CAPI_EXPORTED bool mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
Definition at line 306 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAUnrankedMemRef()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
Definition at line 281 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAUnrankedTensor()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
Definition at line 189 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAVector()
MLIR_CAPI_EXPORTED bool mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
Definition at line 163 of file BuiltinTypes.cpp.
References unwrap().
mlirUnrankedMemrefGetMemorySpace()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
Definition at line 298 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, MlirAttribute memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
The type is owned by the context of element type.
Definition at line 285 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, MlirAttribute memorySpace)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 291 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedTensorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 213 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedTensorTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGetChecked (MlirLocation loc, MlirType elementType)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 217 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGet (intptr_t rank, const int64_t * shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 165 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyOpView::buildGeneric().
mlirVectorTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, MlirType elementType)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 172 of file BuiltinTypes.cpp.
References unwrap(), and wrap().