MLIR: include/mlir-c/Dialect/LLVM.h File Reference
LLVM.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Registration.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (LLVM, llvm)
MLIR_CAPI_EXPORTED MlirType mlirLLVMPointerTypeGet (MlirType pointee, unsigned addressSpace)
Creates an llvm.ptr type.
MLIR_CAPI_EXPORTED MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
MLIR_CAPI_EXPORTED MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const *argumentTypes, bool isVarArg)
Creates an llvm.func type.
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (LLVM , llvm)
mlirLLVMArrayTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
Definition at line 27 of file LLVM.cpp.
References mlir::LLVM::LLVMArrayType::get(), unwrap(), and wrap().
mlirLLVMFunctionTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const * argumentTypes, bool isVarArg)
Creates an llvm.func type.
Definition at line 31 of file LLVM.cpp.
References mlir::LLVM::LLVMFunctionType::get(), unwrap(), unwrapList(), and wrap().
mlirLLVMPointerTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMPointerTypeGet (MlirType pointee, unsigned addressSpace)
Creates an llvm.ptr type.
Definition at line 19 of file LLVM.cpp.
References mlir::LLVM::LLVMPointerType::get(), unwrap(), and wrap().
mlirLLVMStructTypeLiteralGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
Definition at line 39 of file LLVM.cpp.
References mlir::LLVM::LLVMStructType::getLiteral(), unwrap(), unwrapList(), and wrap().
mlirLLVMVoidTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
Definition at line 23 of file LLVM.cpp.
References unwrap(), and wrap().