MLIR: include/mlir-c/Dialect/SparseTensor.h File Reference
SparseTensor.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/Registration.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.capi.h.inc"
Enumerations
enum MlirSparseTensorDimLevelType { MLIR_SPARSE_TENSOR_DIM_LEVEL_DENSE, MLIR_SPARSE_TENSOR_DIM_LEVEL_COMPRESSED, MLIR_SPARSE_TENSOR_DIM_LEVEL_SINGLETON }
Dimension level types that define sparse tensors:
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (SparseTensor, sparse_tensor)
MLIR_CAPI_EXPORTED bool mlirAttributeIsASparseTensorEncodingAttr (MlirAttribute attr)
Checks whether the given attribute is a sparse_tensor.encoding attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseTensorEncodingAttrGet (MlirContext ctx, intptr_t numDimLevelTypes, enum MlirSparseTensorDimLevelType const *dimLevelTypes, MlirAffineMap dimOrdering, int pointerBitWidth, int indexBitWidth)
Creates a sparse_tensor.encoding attribute with the given parameters.
MLIR_CAPI_EXPORTED intptr_t mlirSparseTensorEncodingGetNumDimLevelTypes (MlirAttribute attr)
Returns the number of dim level types in a sparse_tensor.encoding attribute.
MLIR_CAPI_EXPORTED enum MlirSparseTensorDimLevelType mlirSparseTensorEncodingAttrGetDimLevelType (MlirAttribute attr, intptr_t pos)
Returns a specified dim level type in a sparse_tensor.encoding attribute.
MLIR_CAPI_EXPORTED MlirAffineMap mlirSparseTensorEncodingAttrGetDimOrdering (MlirAttribute attr)
Returns the dimension ordering in a sparse_tensor.encoding attribute.
MLIR_CAPI_EXPORTED int mlirSparseTensorEncodingAttrGetPointerBitWidth (MlirAttribute attr)
Returns the pointer bit width in a sparse_tensor.encoding attribute.
MLIR_CAPI_EXPORTED int mlirSparseTensorEncodingAttrGetIndexBitWidth (MlirAttribute attr)
Returns the index bit width in a sparse_tensor.encoding attribute.
Enumeration Type Documentation
MlirSparseTensorDimLevelType
enum MlirSparseTensorDimLevelType
Dimension level types that define sparse tensors:
MLIR_SPARSE_TENSOR_DIM_LEVEL_DENSE - dimension is dense, every entry is stored
MLIR_SPARSE_TENSOR_DIM_LEVEL_COMPRESSED - dimension is sparse, only nonzeros are stored.
MLIR_SPARSE_TENSOR_DIM_LEVEL_SINGLETON - dimension contains single coordinate, no siblings.
These correspond to SparseTensorEncodingAttr::DimLevelType in the C++ API. If updating, keep them in sync and update the static_assert in the impl file.
Enumerator
MLIR_SPARSE_TENSOR_DIM_LEVEL_DENSE
MLIR_SPARSE_TENSOR_DIM_LEVEL_COMPRESSED
MLIR_SPARSE_TENSOR_DIM_LEVEL_SINGLETON
Definition at line 33 of file SparseTensor.h.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (SparseTensor , sparse_tensor)
mlirAttributeIsASparseTensorEncodingAttr()
MLIR_CAPI_EXPORTED bool mlirAttributeIsASparseTensorEncodingAttr (MlirAttribute attr)
Checks whether the given attribute is a sparse_tensor.encoding attribute.
Definition at line 33 of file SparseTensor.cpp.
References unwrap().
mlirSparseTensorEncodingAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseTensorEncodingAttrGet (MlirContext ctx, intptr_t numDimLevelTypes, enum MlirSparseTensorDimLevelType const * dimLevelTypes, MlirAffineMap dimOrdering, int pointerBitWidth, int indexBitWidth)
Creates a sparse_tensor.encoding attribute with the given parameters.
mlirSparseTensorEncodingAttrGetDimLevelType()
MLIR_CAPI_EXPORTED enum MlirSparseTensorDimLevelType mlirSparseTensorEncodingAttrGetDimLevelType (MlirAttribute attr, intptr_t pos)
Returns a specified dim level type in a sparse_tensor.encoding attribute.
Definition at line 60 of file SparseTensor.cpp.
References unwrap().
mlirSparseTensorEncodingAttrGetDimOrdering()
MLIR_CAPI_EXPORTED MlirAffineMap mlirSparseTensorEncodingAttrGetDimOrdering (MlirAttribute attr)
Returns the dimension ordering in a sparse_tensor.encoding attribute.
Definition at line 51 of file SparseTensor.cpp.
References unwrap(), and wrap().
mlirSparseTensorEncodingAttrGetIndexBitWidth()
MLIR_CAPI_EXPORTED int mlirSparseTensorEncodingAttrGetIndexBitWidth (MlirAttribute attr)
Returns the index bit width in a sparse_tensor.encoding attribute.
Definition at line 69 of file SparseTensor.cpp.
References unwrap().
mlirSparseTensorEncodingAttrGetPointerBitWidth()
MLIR_CAPI_EXPORTED int mlirSparseTensorEncodingAttrGetPointerBitWidth (MlirAttribute attr)
Returns the pointer bit width in a sparse_tensor.encoding attribute.
Definition at line 65 of file SparseTensor.cpp.
References unwrap().
mlirSparseTensorEncodingGetNumDimLevelTypes()
MLIR_CAPI_EXPORTED intptr_t mlirSparseTensorEncodingGetNumDimLevelTypes (MlirAttribute attr)
Returns the number of dim level types in a sparse_tensor.encoding attribute.
Definition at line 55 of file SparseTensor.cpp.
References unwrap().