MLIR: lib/Analysis/CallGraph.cpp File Reference
CallGraph.cpp File Reference
#include "mlir/Analysis/CallGraph.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <memory>
Functions
static void computeCallGraph (Operation *op, CallGraph &cg, SymbolTableCollection &symbolTable, CallGraphNode *parentNode, bool resolveCalls)
Recursively compute the callgraph edges for the given operation.
Function Documentation
computeCallGraph()
void computeCallGraph (Operation * op, CallGraph & cg, SymbolTableCollection & symbolTable, CallGraphNode * parentNode, bool resolveCalls) static
Recursively compute the callgraph edges for the given operation.
Computed edges are placed into the given callgraph object.
Definition at line 74 of file CallGraph.cpp.
References mlir::CallGraphNode::addCallEdge(), computeCallGraph(), mlir::CallGraph::getOrAddNode(), mlir::Operation::getRegions(), and mlir::CallGraph::resolveCallable().
Referenced by mlir::CallGraph::CallGraph(), and computeCallGraph().