MLIR: lib/Interfaces/CallInterfaces.cpp File Reference
CallInterfaces.cpp File Reference
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/IR/Builders.h"
#include "mlir/Interfaces/CallInterfaces.cpp.inc"
Functions
static ParseResult parseTypeAndAttrList (OpAsmParser &parser, SmallVectorImpl< Type > &types, SmallVectorImpl< DictionaryAttr > &attrs)
static void printFunctionResultList (OpAsmPrinter &p, TypeRange types, ArrayAttr attrs)
Print a function result list.
Function Documentation
parseTypeAndAttrList()
ParseResult parseTypeAndAttrList (OpAsmParser & parser, SmallVectorImpl< Type > & types, SmallVectorImpl< DictionaryAttr > & attrs) static
Definition at line 19 of file CallInterfaces.cpp.
References mlir::AsmParser::getContext(), mlir::NamedAttrList::getDictionary(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), and success().
Referenced by mlir::call_interface_impl::parseFunctionResultList(), and mlir::call_interface_impl::parseFunctionSignature().
printFunctionResultList()
void printFunctionResultList (OpAsmPrinter & p, TypeRange types, ArrayAttr attrs) static
Print a function result list.
The provided attrs must either be null, or contain a set of DictionaryAttrs of the same arity as types.
Definition at line 81 of file CallInterfaces.cpp.
References ArrayAttr(), and mlir::AsmPrinter::getStream().
Referenced by mlir::call_interface_impl::printFunctionSignature().