MLIR: lib/CAPI/Target/ExportSMTLIB.cpp File Reference
ExportSMTLIB.cpp File Reference
#include "mlir-c/Target/ExportSMTLIB.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "mlir/Target/SMTLIB/ExportSMTLIB.h"
Functions
MlirLogicalResult mlirTranslateOperationToSMTLIB (MlirOperation module, MlirStringCallback callback, void *userData, bool inlineSingleUseValues, bool indentLetBody)
MlirLogicalResult mlirTranslateModuleToSMTLIB (MlirModule module, MlirStringCallback callback, void *userData, bool inlineSingleUseValues, bool indentLetBody)
Emits SMTLIB for the specified module using the provided callback and user data.
Function Documentation
mlirTranslateModuleToSMTLIB()
MlirLogicalResult mlirTranslateModuleToSMTLIB (MlirModule module, MlirStringCallback callback, void * userData, bool inlineSingleUseValues, bool indentLetBody)
Emits SMTLIB for the specified module using the provided callback and user data.
Definition at line 34 of file ExportSMTLIB.cpp.
References mlirModuleGetOperation(), and mlirTranslateOperationToSMTLIB().
mlirTranslateOperationToSMTLIB()
MlirLogicalResult mlirTranslateOperationToSMTLIB (MlirOperation module, MlirStringCallback callback, void * userData, bool inlineSingleUseValues, bool indentLetBody)
Definition at line 22 of file ExportSMTLIB.cpp.
References mlir::smt::exportSMTLIB(), options, unwrap(), and wrap().
Referenced by mlirTranslateModuleToSMTLIB(), and populateDialectSMTSubmodule().