MLIR: lib/CAPI/Dialect/EmitC.cpp File Reference
EmitC.cpp File Reference
#include "mlir-c/Dialect/EmitC.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/EmitC/IR/EmitC.h"
Functions
bool mlirTypeIsAEmitCArrayType (MlirType type)
MlirTypeID mlirEmitCArrayTypeGetTypeID (void)
MlirType mlirEmitCArrayTypeGet (intptr_t nDims, int64_t *shape, MlirType elementType)
bool mlirTypeIsAEmitCLValueType (MlirType type)
MlirTypeID mlirEmitCLValueTypeGetTypeID (void)
MlirType mlirEmitCLValueTypeGet (MlirType valueType)
bool mlirTypeIsAEmitCOpaqueType (MlirType type)
MlirTypeID mlirEmitCOpaqueTypeGetTypeID (void)
MlirType mlirEmitCOpaqueTypeGet (MlirContext ctx, MlirStringRef value)
bool mlirTypeIsAEmitCPointerType (MlirType type)
MlirTypeID mlirEmitCPointerTypeGetTypeID (void)
MlirType mlirEmitCPointerTypeGet (MlirType pointee)
bool mlirTypeIsAEmitCPtrDiffTType (MlirType type)
MlirTypeID mlirEmitCPtrDiffTTypeGetTypeID (void)
MlirType mlirEmitCPtrDiffTTypeGet (MlirContext ctx)
bool mlirTypeIsAEmitCSignedSizeTType (MlirType type)
MlirTypeID mlirEmitCSignedSizeTTypeGetTypeID (void)
MlirType mlirEmitCSignedSizeTTypeGet (MlirContext ctx)
bool mlirTypeIsAEmitCSizeTType (MlirType type)
MlirTypeID mlirEmitCSizeTTypeGetTypeID (void)
MlirType mlirEmitCSizeTTypeGet (MlirContext ctx)
bool mlirAttributeIsAEmitCCmpPredicate (MlirAttribute attr)
MlirAttribute mlirEmitCCmpPredicateAttrGet (MlirContext ctx, MlirEmitCCmpPredicate val)
MlirEmitCCmpPredicate mlirEmitCCmpPredicateAttrGetValue (MlirAttribute attr)
MlirTypeID mlirEmitCCmpPredicateAttrGetTypeID (void)
bool mlirAttributeIsAEmitCOpaque (MlirAttribute attr)
MlirAttribute mlirEmitCOpaqueAttrGet (MlirContext ctx, MlirStringRef value)
MlirStringRef mlirEmitCOpaqueAttrGetValue (MlirAttribute attr)
MlirTypeID mlirEmitCOpaqueAttrGetTypeID (void)
Function Documentation
mlirAttributeIsAEmitCCmpPredicate()
bool mlirAttributeIsAEmitCCmpPredicate (MlirAttribute attr)
Definition at line 152 of file EmitC.cpp.
References unwrap().
mlirAttributeIsAEmitCOpaque()
bool mlirAttributeIsAEmitCOpaque (MlirAttribute attr)
Definition at line 175 of file EmitC.cpp.
References unwrap().
mlirEmitCArrayTypeGet()
MlirType mlirEmitCArrayTypeGet (intptr_t nDims, int64_t * shape, MlirType elementType)
Definition at line 46 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCArrayTypeGetTypeID()
MlirTypeID mlirEmitCArrayTypeGetTypeID (void)
Definition at line 42 of file EmitC.cpp.
References wrap().
mlirEmitCCmpPredicateAttrGet()
MlirAttribute mlirEmitCCmpPredicateAttrGet (MlirContext ctx, MlirEmitCCmpPredicate val)
Definition at line 156 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCCmpPredicateAttrGetTypeID()
MlirTypeID mlirEmitCCmpPredicateAttrGetTypeID (void)
Definition at line 167 of file EmitC.cpp.
References wrap().
mlirEmitCCmpPredicateAttrGetValue()
MlirEmitCCmpPredicate mlirEmitCCmpPredicateAttrGetValue (MlirAttribute attr)
Definition at line 162 of file EmitC.cpp.
References unwrap().
mlirEmitCLValueTypeGet()
MlirType mlirEmitCLValueTypeGet (MlirType valueType)
Definition at line 64 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCLValueTypeGetTypeID()
MlirTypeID mlirEmitCLValueTypeGetTypeID (void)
Definition at line 60 of file EmitC.cpp.
References wrap().
mlirEmitCOpaqueAttrGet()
MlirAttribute mlirEmitCOpaqueAttrGet (MlirContext ctx, MlirStringRef value)
Definition at line 179 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCOpaqueAttrGetTypeID()
MlirTypeID mlirEmitCOpaqueAttrGetTypeID (void)
Definition at line 187 of file EmitC.cpp.
References wrap().
mlirEmitCOpaqueAttrGetValue()
MlirStringRef mlirEmitCOpaqueAttrGetValue (MlirAttribute attr)
Definition at line 183 of file EmitC.cpp.
References unwrap(), and wrap().
mlirEmitCOpaqueTypeGet()
MlirType mlirEmitCOpaqueTypeGet (MlirContext ctx, MlirStringRef value)
Definition at line 80 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCOpaqueTypeGetTypeID()
MlirTypeID mlirEmitCOpaqueTypeGetTypeID (void)
Definition at line 76 of file EmitC.cpp.
References wrap().
mlirEmitCPointerTypeGet()
MlirType mlirEmitCPointerTypeGet (MlirType pointee)
Definition at line 96 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCPointerTypeGetTypeID()
MlirTypeID mlirEmitCPointerTypeGetTypeID (void)
Definition at line 92 of file EmitC.cpp.
References wrap().
mlirEmitCPtrDiffTTypeGet()
MlirType mlirEmitCPtrDiffTTypeGet (MlirContext ctx)
Definition at line 112 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCPtrDiffTTypeGetTypeID()
MlirTypeID mlirEmitCPtrDiffTTypeGetTypeID (void)
Definition at line 108 of file EmitC.cpp.
References wrap().
mlirEmitCSignedSizeTTypeGet()
MlirType mlirEmitCSignedSizeTTypeGet (MlirContext ctx)
Definition at line 128 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCSignedSizeTTypeGetTypeID()
MlirTypeID mlirEmitCSignedSizeTTypeGetTypeID (void)
Definition at line 124 of file EmitC.cpp.
References wrap().
mlirEmitCSizeTTypeGet()
MlirType mlirEmitCSizeTTypeGet (MlirContext ctx)
Definition at line 144 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCSizeTTypeGetTypeID()
MlirTypeID mlirEmitCSizeTTypeGetTypeID (void)
Definition at line 140 of file EmitC.cpp.
References wrap().
mlirTypeIsAEmitCArrayType()
bool mlirTypeIsAEmitCArrayType (MlirType type)
Definition at line 38 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCLValueType()
bool mlirTypeIsAEmitCLValueType (MlirType type)
Definition at line 56 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCOpaqueType()
bool mlirTypeIsAEmitCOpaqueType (MlirType type)
Definition at line 72 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCPointerType()
bool mlirTypeIsAEmitCPointerType (MlirType type)
Definition at line 88 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCPtrDiffTType()
bool mlirTypeIsAEmitCPtrDiffTType (MlirType type)
Definition at line 104 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCSignedSizeTType()
bool mlirTypeIsAEmitCSignedSizeTType (MlirType type)
Definition at line 120 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCSizeTType()
bool mlirTypeIsAEmitCSizeTType (MlirType type)
Definition at line 136 of file EmitC.cpp.
References unwrap().