MLIR: lib/CAPI/IR/BuiltinTypes.cpp File Reference
BuiltinTypes.cpp File Reference
#include "mlir-c/BuiltinTypes.h"
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/AffineMap.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Types.h"
#include <algorithm>
Functions
MlirTypeID mlirIntegerTypeGetTypeID ()
Returns the typeID of an Integer type.
bool mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
bool mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
bool mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
bool mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
MlirTypeID mlirIndexTypeGetTypeID ()
Returns the typeID of an Index type.
bool mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
bool mlirTypeIsAFloat (MlirType type)
Checks whether the given type is a floating-point type.
unsigned mlirFloatTypeGetWidth (MlirType type)
Returns the bitwidth of a floating-point type.
MlirTypeID mlirFloat4E2M1FNTypeGetTypeID ()
Returns the typeID of an Float4E2M1FN type.
bool mlirTypeIsAFloat4E2M1FN (MlirType type)
Checks whether the given type is an f4E2M1FN type.
MlirType mlirFloat4E2M1FNTypeGet (MlirContext ctx)
Creates an f4E2M1FN type in the given context.
MlirTypeID mlirFloat6E2M3FNTypeGetTypeID ()
Returns the typeID of an Float6E2M3FN type.
bool mlirTypeIsAFloat6E2M3FN (MlirType type)
Checks whether the given type is an f6E2M3FN type.
MlirType mlirFloat6E2M3FNTypeGet (MlirContext ctx)
Creates an f6E2M3FN type in the given context.
MlirTypeID mlirFloat6E3M2FNTypeGetTypeID ()
Returns the typeID of an Float6E3M2FN type.
bool mlirTypeIsAFloat6E3M2FN (MlirType type)
Checks whether the given type is an f6E3M2FN type.
MlirType mlirFloat6E3M2FNTypeGet (MlirContext ctx)
Creates an f6E3M2FN type in the given context.
MlirTypeID mlirFloat8E5M2TypeGetTypeID ()
Returns the typeID of an Float8E5M2 type.
bool mlirTypeIsAFloat8E5M2 (MlirType type)
Checks whether the given type is an f8E5M2 type.
MlirType mlirFloat8E5M2TypeGet (MlirContext ctx)
Creates an f8E5M2 type in the given context.
MlirTypeID mlirFloat8E4M3TypeGetTypeID ()
Returns the typeID of an Float8E4M3 type.
bool mlirTypeIsAFloat8E4M3 (MlirType type)
Checks whether the given type is an f8E4M3 type.
MlirType mlirFloat8E4M3TypeGet (MlirContext ctx)
Creates an f8E4M3 type in the given context.
MlirTypeID mlirFloat8E4M3FNTypeGetTypeID ()
Returns the typeID of an Float8E4M3FN type.
bool mlirTypeIsAFloat8E4M3FN (MlirType type)
Checks whether the given type is an f8E4M3FN type.
MlirType mlirFloat8E4M3FNTypeGet (MlirContext ctx)
Creates an f8E4M3FN type in the given context.
MlirTypeID mlirFloat8E5M2FNUZTypeGetTypeID ()
Returns the typeID of an Float8E5M2FNUZ type.
bool mlirTypeIsAFloat8E5M2FNUZ (MlirType type)
Checks whether the given type is an f8E5M2FNUZ type.
MlirType mlirFloat8E5M2FNUZTypeGet (MlirContext ctx)
Creates an f8E5M2FNUZ type in the given context.
MlirTypeID mlirFloat8E4M3FNUZTypeGetTypeID ()
Returns the typeID of an Float8E4M3FNUZ type.
bool mlirTypeIsAFloat8E4M3FNUZ (MlirType type)
Checks whether the given type is an f8E4M3FNUZ type.
MlirType mlirFloat8E4M3FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3FNUZ type in the given context.
MlirTypeID mlirFloat8E4M3B11FNUZTypeGetTypeID ()
Returns the typeID of an Float8E4M3B11FNUZ type.
bool mlirTypeIsAFloat8E4M3B11FNUZ (MlirType type)
Checks whether the given type is an f8E4M3B11FNUZ type.
MlirType mlirFloat8E4M3B11FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3B11FNUZ type in the given context.
MlirTypeID mlirFloat8E3M4TypeGetTypeID ()
Returns the typeID of an Float8E3M4 type.
bool mlirTypeIsAFloat8E3M4 (MlirType type)
Checks whether the given type is an f8E3M4 type.
MlirType mlirFloat8E3M4TypeGet (MlirContext ctx)
Creates an f8E3M4 type in the given context.
MlirTypeID mlirFloat8E8M0FNUTypeGetTypeID ()
Returns the typeID of an Float8E8M0FNU type.
bool mlirTypeIsAFloat8E8M0FNU (MlirType type)
Checks whether the given type is an f8E8M0FNU type.
MlirType mlirFloat8E8M0FNUTypeGet (MlirContext ctx)
Creates an f8E8M0FNU type in the given context.
MlirTypeID mlirBFloat16TypeGetTypeID ()
Returns the typeID of an BFloat16 type.
bool mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
MlirTypeID mlirFloat16TypeGetTypeID ()
Returns the typeID of an Float16 type.
bool mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
MlirTypeID mlirFloatTF32TypeGetTypeID ()
Returns the typeID of a TF32 type.
bool mlirTypeIsATF32 (MlirType type)
Checks whether the given type is an TF32 type.
MlirType mlirTF32TypeGet (MlirContext ctx)
Creates a TF32 type in the given context.
MlirTypeID mlirFloat32TypeGetTypeID ()
Returns the typeID of an Float32 type.
bool mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
MlirTypeID mlirFloat64TypeGetTypeID ()
Returns the typeID of an Float64 type.
bool mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
MlirTypeID mlirNoneTypeGetTypeID ()
Returns the typeID of an None type.
bool mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
MlirTypeID mlirComplexTypeGetTypeID ()
Returns the typeID of an Complex type.
bool mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
bool mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
bool mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
bool mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
bool mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is dynamic.
bool mlirShapedTypeIsStaticDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is static.
int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
int64_t mlirShapedTypeGetDynamicSize ()
Returns the value indicating a dynamic size in a shaped type.
bool mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
bool mlirShapedTypeIsStaticSize (int64_t size)
Checks whether the given shaped type dimension value is statically-sized.
bool mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
bool mlirShapedTypeIsStaticStrideOrOffset (int64_t val)
Checks whether the given dimension value of a stride or an offset is statically-sized.
int64_t mlirShapedTypeGetDynamicStrideOrOffset ()
Returns the value indicating a dynamic stride or offset in a shaped type.
MlirTypeID mlirVectorTypeGetTypeID ()
Returns the typeID of an Vector type.
bool mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
MlirType mlirVectorTypeGet (intptr_t rank, const int64_t *shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
MlirType mlirVectorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, MlirType elementType)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirType mlirVectorTypeGetScalable (intptr_t rank, const int64_t *shape, const bool *scalable, MlirType elementType)
Creates a scalable vector type with the shape identified by its rank and dimensions.
MlirType mlirVectorTypeGetScalableChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, const bool *scalable, MlirType elementType)
Same as "mlirVectorTypeGetScalable" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
bool mlirVectorTypeIsScalable (MlirType type)
Checks whether the given vector type is scalable, i.e., has at least one scalable dimension.
bool mlirVectorTypeIsDimScalable (MlirType type, intptr_t dim)
Checks whether the "dim"-th dimension of the given vector is scalable.
bool mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
MlirTypeID mlirRankedTensorTypeGetTypeID ()
Returns the typeID of an RankedTensor type.
bool mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
MlirTypeID mlirUnrankedTensorTypeGetTypeID ()
Returns the typeID of an UnrankedTensor type.
bool mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
MlirType mlirRankedTensorTypeGet (intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute encoding)
Creates a tensor type of a fixed rank with the given shape, element type, and optional encoding in the same context as the element type.
MlirType mlirRankedTensorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute encoding)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirAttribute mlirRankedTensorTypeGetEncoding (MlirType type)
Gets the 'encoding' attribute from the ranked tensor type, returning a null attribute if none.
MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
MlirType mlirUnrankedTensorTypeGetChecked (MlirLocation loc, MlirType elementType)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirTypeID mlirMemRefTypeGetTypeID ()
Returns the typeID of an MemRef type.
bool mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute layout, MlirAttribute memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
MlirType mlirMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute layout, MlirAttribute memorySpace)
Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o illegal arguments, emitting appropriate diagnostics.
MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
MlirType mlirMemRefTypeContiguousGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute memorySpace)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirAttribute mlirMemRefTypeGetLayout (MlirType type)
Returns the layout of the given MemRef type.
MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type)
Returns the affine map of the given MemRef type.
MlirAttribute mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
MlirLogicalResult mlirMemRefTypeGetStridesAndOffset (MlirType type, int64_t *strides, int64_t *offset)
Returns the strides of the MemRef if the layout map is in strided form.
MlirTypeID mlirUnrankedMemRefTypeGetTypeID ()
Returns the typeID of an UnrankedMemRef type.
bool mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, MlirAttribute memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
MlirType mlirUnrankedMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, MlirAttribute memorySpace)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirAttribute mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
MlirTypeID mlirTupleTypeGetTypeID ()
Returns the typeID of an Tuple type.
bool mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType const *elements)
Creates a tuple type that consists of the given list of elemental types.
intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
MlirTypeID mlirFunctionTypeGetTypeID ()
Returns the typeID of an Function type.
bool mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType const *inputs, intptr_t numResults, MlirType const *results)
Creates a function type, mapping a list of input types to result types.
intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
MlirTypeID mlirOpaqueTypeGetTypeID ()
Returns the typeID of an Opaque type.
bool mlirTypeIsAOpaque (MlirType type)
Checks whether the given type is an opaque type.
MlirType mlirOpaqueTypeGet (MlirContext ctx, MlirStringRef dialectNamespace, MlirStringRef typeData)
Creates an opaque type in the given context associated with the dialect identified by its namespace.
MlirStringRef mlirOpaqueTypeGetDialectNamespace (MlirType type)
Returns the namespace of the dialect with which the given opaque type is associated.
MlirStringRef mlirOpaqueTypeGetData (MlirType type)
Returns the raw data as a string reference.
Function Documentation
mlirBF16TypeGet()
MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
The type is owned by the context.
Definition at line 228 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirBFloat16TypeGetTypeID()
MlirTypeID mlirBFloat16TypeGetTypeID (void)
Returns the typeID of an BFloat16 type.
Definition at line 220 of file BuiltinTypes.cpp.
References wrap().
mlirComplexTypeGet()
MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 298 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirComplexTypeGetElementType()
MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
Definition at line 302 of file BuiltinTypes.cpp.
References getElementType(), unwrap(), and wrap().
mlirComplexTypeGetTypeID()
MlirTypeID mlirComplexTypeGetTypeID (void)
Returns the typeID of an Complex type.
Definition at line 292 of file BuiltinTypes.cpp.
References wrap().
mlirF16TypeGet()
MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
The type is owned by the context.
Definition at line 238 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirF32TypeGet()
MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
The type is owned by the context.
Definition at line 260 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirF64TypeGet()
MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
The type is owned by the context.
Definition at line 270 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat16TypeGetTypeID()
MlirTypeID mlirFloat16TypeGetTypeID (void)
Returns the typeID of an Float16 type.
Definition at line 232 of file BuiltinTypes.cpp.
References wrap().
mlirFloat32TypeGetTypeID()
MlirTypeID mlirFloat32TypeGetTypeID (void)
Returns the typeID of an Float32 type.
Definition at line 254 of file BuiltinTypes.cpp.
References wrap().
mlirFloat4E2M1FNTypeGet()
MlirType mlirFloat4E2M1FNTypeGet (MlirContext ctx)
Creates an f4E2M1FN type in the given context.
The type is owned by the context.
Definition at line 96 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat4E2M1FNTypeGetTypeID()
MlirTypeID mlirFloat4E2M1FNTypeGetTypeID (void)
Returns the typeID of an Float4E2M1FN type.
Definition at line 88 of file BuiltinTypes.cpp.
References wrap().
mlirFloat64TypeGetTypeID()
MlirTypeID mlirFloat64TypeGetTypeID (void)
Returns the typeID of an Float64 type.
Definition at line 264 of file BuiltinTypes.cpp.
References wrap().
mlirFloat6E2M3FNTypeGet()
MlirType mlirFloat6E2M3FNTypeGet (MlirContext ctx)
Creates an f6E2M3FN type in the given context.
The type is owned by the context.
Definition at line 108 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat6E2M3FNTypeGetTypeID()
MlirTypeID mlirFloat6E2M3FNTypeGetTypeID (void)
Returns the typeID of an Float6E2M3FN type.
Definition at line 100 of file BuiltinTypes.cpp.
References wrap().
mlirFloat6E3M2FNTypeGet()
MlirType mlirFloat6E3M2FNTypeGet (MlirContext ctx)
Creates an f6E3M2FN type in the given context.
The type is owned by the context.
Definition at line 120 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat6E3M2FNTypeGetTypeID()
MlirTypeID mlirFloat6E3M2FNTypeGetTypeID (void)
Returns the typeID of an Float6E3M2FN type.
Definition at line 112 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E3M4TypeGet()
MlirType mlirFloat8E3M4TypeGet (MlirContext ctx)
Creates an f8E3M4 type in the given context.
The type is owned by the context.
Definition at line 204 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E3M4TypeGetTypeID()
MlirTypeID mlirFloat8E3M4TypeGetTypeID (void)
Returns the typeID of an Float8E3M4 type.
Definition at line 196 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3B11FNUZTypeGet()
MlirType mlirFloat8E4M3B11FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3B11FNUZ type in the given context.
The type is owned by the context.
Definition at line 192 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3B11FNUZTypeGetTypeID()
MlirTypeID mlirFloat8E4M3B11FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E4M3B11FNUZ type.
Definition at line 184 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3FNTypeGet()
MlirType mlirFloat8E4M3FNTypeGet (MlirContext ctx)
Creates an f8E4M3FN type in the given context.
The type is owned by the context.
Definition at line 156 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3FNTypeGetTypeID()
MlirTypeID mlirFloat8E4M3FNTypeGetTypeID (void)
Returns the typeID of an Float8E4M3FN type.
Definition at line 148 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3FNUZTypeGet()
MlirType mlirFloat8E4M3FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3FNUZ type in the given context.
The type is owned by the context.
Definition at line 180 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3FNUZTypeGetTypeID()
MlirTypeID mlirFloat8E4M3FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E4M3FNUZ type.
Definition at line 172 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3TypeGet()
MlirType mlirFloat8E4M3TypeGet (MlirContext ctx)
Creates an f8E4M3 type in the given context.
The type is owned by the context.
Definition at line 144 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3TypeGetTypeID()
MlirTypeID mlirFloat8E4M3TypeGetTypeID (void)
Returns the typeID of an Float8E4M3 type.
Definition at line 136 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E5M2FNUZTypeGet()
MlirType mlirFloat8E5M2FNUZTypeGet (MlirContext ctx)
Creates an f8E5M2FNUZ type in the given context.
The type is owned by the context.
Definition at line 168 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E5M2FNUZTypeGetTypeID()
MlirTypeID mlirFloat8E5M2FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E5M2FNUZ type.
Definition at line 160 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E5M2TypeGet()
MlirType mlirFloat8E5M2TypeGet (MlirContext ctx)
Creates an f8E5M2 type in the given context.
The type is owned by the context.
Definition at line 132 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E5M2TypeGetTypeID()
MlirTypeID mlirFloat8E5M2TypeGetTypeID (void)
Returns the typeID of an Float8E5M2 type.
Definition at line 124 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E8M0FNUTypeGet()
MlirType mlirFloat8E8M0FNUTypeGet (MlirContext ctx)
Creates an f8E8M0FNU type in the given context.
The type is owned by the context.
Definition at line 216 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E8M0FNUTypeGetTypeID()
MlirTypeID mlirFloat8E8M0FNUTypeGetTypeID (void)
Returns the typeID of an Float8E8M0FNU type.
Definition at line 208 of file BuiltinTypes.cpp.
References wrap().
mlirFloatTF32TypeGetTypeID()
MlirTypeID mlirFloatTF32TypeGetTypeID (void)
Returns the typeID of a TF32 type.
Definition at line 242 of file BuiltinTypes.cpp.
References wrap().
mlirFloatTypeGetWidth()
unsigned mlirFloatTypeGetWidth (MlirType type)
Returns the bitwidth of a floating-point type.
Definition at line 84 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGet()
MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType const * inputs, intptr_t numResults, MlirType const * results)
Creates a function type, mapping a list of input types to result types.
Definition at line 606 of file BuiltinTypes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirFunctionTypeGetInput()
MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
Definition at line 624 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFunctionTypeGetNumInputs()
intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
Definition at line 616 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGetNumResults()
intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
Definition at line 620 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGetResult()
MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
Definition at line 630 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFunctionTypeGetTypeID()
MlirTypeID mlirFunctionTypeGetTypeID (void)
Returns the typeID of an Function type.
Definition at line 598 of file BuiltinTypes.cpp.
References wrap().
mlirIndexTypeGet()
MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
The type is owned by the context.
Definition at line 72 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIndexTypeGetTypeID()
MlirTypeID mlirIndexTypeGetTypeID (void)
Returns the typeID of an Index type.
Definition at line 66 of file BuiltinTypes.cpp.
References wrap().
mlirIntegerTypeGet()
MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 34 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIntegerTypeGetTypeID()
MlirTypeID mlirIntegerTypeGetTypeID (void)
Returns the typeID of an Integer type.
Definition at line 28 of file BuiltinTypes.cpp.
References wrap().
mlirIntegerTypeGetWidth()
unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
Definition at line 46 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsSigned()
bool mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
Definition at line 54 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsSignless()
bool mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
Definition at line 50 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsUnsigned()
bool mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
Definition at line 58 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeSignedGet()
MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 38 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIntegerTypeUnsignedGet()
MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 42 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeContiguousGet()
MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
The type has no affine maps, i.e. represents a default row-major contiguous memref. The type is owned by the context.
Definition at line 502 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeContiguousGetChecked()
MlirType mlirMemRefTypeContiguousGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute memorySpace)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 510 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGet()
MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute layout, MlirAttribute memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
The type is owned by the context.
Definition at line 478 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetAffineMap()
MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type)
Returns the affine map of the given MemRef type.
Definition at line 523 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetChecked()
MlirType mlirMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute layout, MlirAttribute memorySpace)
Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o illegal arguments, emitting appropriate diagnostics.
Definition at line 489 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetLayout()
MlirAttribute mlirMemRefTypeGetLayout (MlirType type)
Returns the layout of the given MemRef type.
Definition at line 519 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetMemorySpace()
MlirAttribute mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
Definition at line 527 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetStridesAndOffset()
MlirLogicalResult mlirMemRefTypeGetStridesAndOffset (MlirType type, int64_t * strides, int64_t * offset)
Returns the strides of the MemRef if the layout map is in strided form.
Both strides and offset are out params. strides must point to pre-allocated memory of length equal to the rank of the memref.
Definition at line 531 of file BuiltinTypes.cpp.
References mlirLogicalResultFailure(), mlirLogicalResultSuccess(), and unwrap().
mlirMemRefTypeGetTypeID()
MlirTypeID mlirMemRefTypeGetTypeID (void)
Returns the typeID of an MemRef type.
Definition at line 472 of file BuiltinTypes.cpp.
References wrap().
mlirNoneTypeGet()
MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
The type is owned by the context.
Definition at line 284 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirNoneTypeGetTypeID()
MlirTypeID mlirNoneTypeGetTypeID (void)
Returns the typeID of an None type.
Definition at line 278 of file BuiltinTypes.cpp.
References wrap().
mlirOpaqueTypeGet()
MlirType mlirOpaqueTypeGet (MlirContext ctx, MlirStringRef dialectNamespace, MlirStringRef typeData)
Creates an opaque type in the given context associated with the dialect identified by its namespace.
The type contains opaque byte data of the specified length (data need not be null-terminated).
Definition at line 646 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirOpaqueTypeGetData()
MlirStringRef mlirOpaqueTypeGetData (MlirType type)
Returns the raw data as a string reference.
The data remains live as long as the context in which the type lives.
Definition at line 658 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirOpaqueTypeGetDialectNamespace()
MlirStringRef mlirOpaqueTypeGetDialectNamespace (MlirType type)
Returns the namespace of the dialect with which the given opaque type is associated.
The namespace string is owned by the context.
Definition at line 653 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirOpaqueTypeGetTypeID()
MlirTypeID mlirOpaqueTypeGetTypeID (void)
Returns the typeID of an Opaque type.
Definition at line 640 of file BuiltinTypes.cpp.
References wrap().
mlirRankedTensorTypeGet()
MlirType mlirRankedTensorTypeGet (intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute encoding)
Creates a tensor type of a fixed rank with the given shape, element type, and optional encoding in the same context as the element type.
The type is owned by the context. Tensor types without any specific encoding field should assign mlirAttributeGetNull() to this parameter.
Definition at line 439 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetChecked()
MlirType mlirRankedTensorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute encoding)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 446 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetEncoding()
MlirAttribute mlirRankedTensorTypeGetEncoding (MlirType type)
Gets the 'encoding' attribute from the ranked tensor type, returning a null attribute if none.
Definition at line 455 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetTypeID()
MlirTypeID mlirRankedTensorTypeGetTypeID (void)
Returns the typeID of an RankedTensor type.
Definition at line 423 of file BuiltinTypes.cpp.
References wrap().
mlirShapedTypeGetDimSize()
int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
Definition at line 340 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetDynamicSize()
int64_t mlirShapedTypeGetDynamicSize (void)
Returns the value indicating a dynamic size in a shaped type.
Prefer mlirShapedTypeIsDynamicSize and mlirShapedTypeIsStaticSize to direct comparisons with this value.
Definition at line 345 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetDynamicStrideOrOffset()
int64_t mlirShapedTypeGetDynamicStrideOrOffset (void)
Returns the value indicating a dynamic stride or offset in a shaped type.
Prefer mlirShapedTypeIsDynamicStrideOrOffset and mlirShapedTypeIsStaticStrideOrOffset to direct comparisons with this value.
Definition at line 363 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetElementType()
MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
Definition at line 314 of file BuiltinTypes.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetRank()
int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
Definition at line 322 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeHasRank()
bool mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
Definition at line 318 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeHasStaticShape()
bool mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
Definition at line 326 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsDynamicDim()
bool mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is dynamic.
Definition at line 330 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsDynamicSize()
bool mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
Definition at line 347 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsDynamicStrideOrOffset()
bool mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
Definition at line 355 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsStaticDim()
bool mlirShapedTypeIsStaticDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is static.
Definition at line 335 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsStaticSize()
bool mlirShapedTypeIsStaticSize (int64_t size)
Checks whether the given shaped type dimension value is statically-sized.
Definition at line 351 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsStaticStrideOrOffset()
bool mlirShapedTypeIsStaticStrideOrOffset (int64_t val)
Checks whether the given dimension value of a stride or an offset is statically-sized.
Definition at line 359 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirTF32TypeGet()
MlirType mlirTF32TypeGet (MlirContext ctx)
Creates a TF32 type in the given context.
The type is owned by the context.
Definition at line 250 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirTupleTypeGet()
MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType const * elements)
Creates a tuple type that consists of the given list of elemental types.
The type is owned by the context.
Definition at line 578 of file BuiltinTypes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirTupleTypeGetNumTypes()
intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
Definition at line 585 of file BuiltinTypes.cpp.
References unwrap().
mlirTupleTypeGetType()
MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
Definition at line 589 of file BuiltinTypes.cpp.
References mlir::getType(), unwrap(), and wrap().
mlirTupleTypeGetTypeID()
MlirTypeID mlirTupleTypeGetTypeID (void)
Returns the typeID of an Tuple type.
Definition at line 572 of file BuiltinTypes.cpp.
References wrap().
mlirTypeIsABF16()
bool mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
Definition at line 224 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAComplex()
bool mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
Definition at line 294 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF16()
bool mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
Definition at line 234 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF32()
bool mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
Definition at line 256 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF64()
bool mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
Definition at line 266 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat()
bool mlirTypeIsAFloat (MlirType type)
Checks whether the given type is a floating-point type.
Definition at line 80 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat4E2M1FN()
bool mlirTypeIsAFloat4E2M1FN (MlirType type)
Checks whether the given type is an f4E2M1FN type.
Definition at line 92 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat6E2M3FN()
bool mlirTypeIsAFloat6E2M3FN (MlirType type)
Checks whether the given type is an f6E2M3FN type.
Definition at line 104 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat6E3M2FN()
bool mlirTypeIsAFloat6E3M2FN (MlirType type)
Checks whether the given type is an f6E3M2FN type.
Definition at line 116 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E3M4()
bool mlirTypeIsAFloat8E3M4 (MlirType type)
Checks whether the given type is an f8E3M4 type.
Definition at line 200 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3()
bool mlirTypeIsAFloat8E4M3 (MlirType type)
Checks whether the given type is an f8E4M3 type.
Definition at line 140 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3B11FNUZ()
bool mlirTypeIsAFloat8E4M3B11FNUZ (MlirType type)
Checks whether the given type is an f8E4M3B11FNUZ type.
Definition at line 188 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3FN()
bool mlirTypeIsAFloat8E4M3FN (MlirType type)
Checks whether the given type is an f8E4M3FN type.
Definition at line 152 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3FNUZ()
bool mlirTypeIsAFloat8E4M3FNUZ (MlirType type)
Checks whether the given type is an f8E4M3FNUZ type.
Definition at line 176 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E5M2()
bool mlirTypeIsAFloat8E5M2 (MlirType type)
Checks whether the given type is an f8E5M2 type.
Definition at line 128 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E5M2FNUZ()
bool mlirTypeIsAFloat8E5M2FNUZ (MlirType type)
Checks whether the given type is an f8E5M2FNUZ type.
Definition at line 164 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E8M0FNU()
bool mlirTypeIsAFloat8E8M0FNU (MlirType type)
Checks whether the given type is an f8E8M0FNU type.
Definition at line 212 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFunction()
bool mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
Definition at line 602 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAIndex()
bool mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
Definition at line 68 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAInteger()
bool mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
Definition at line 30 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAMemRef()
bool mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
Definition at line 474 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsANone()
bool mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
Definition at line 280 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAOpaque()
bool mlirTypeIsAOpaque (MlirType type)
Checks whether the given type is an opaque type.
Definition at line 642 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsARankedTensor()
bool mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
Definition at line 427 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAShaped()
bool mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
Definition at line 310 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATensor()
bool mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
Definition at line 419 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATF32()
bool mlirTypeIsATF32 (MlirType type)
Checks whether the given type is an TF32 type.
Definition at line 246 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATuple()
bool mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
Definition at line 574 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAUnrankedMemRef()
bool mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
Definition at line 547 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAUnrankedTensor()
bool mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
Definition at line 435 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAVector()
bool mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
Definition at line 373 of file BuiltinTypes.cpp.
References unwrap().
mlirUnrankedMemrefGetMemorySpace()
MlirAttribute mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
Definition at line 564 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGet()
MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, MlirAttribute memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
The type is owned by the context of element type.
Definition at line 551 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGetChecked()
MlirType mlirUnrankedMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, MlirAttribute memorySpace)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 557 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGetTypeID()
MlirTypeID mlirUnrankedMemRefTypeGetTypeID (void)
Returns the typeID of an UnrankedMemRef type.
Definition at line 543 of file BuiltinTypes.cpp.
References wrap().
mlirUnrankedTensorTypeGet()
MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 459 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedTensorTypeGetChecked()
MlirType mlirUnrankedTensorTypeGetChecked (MlirLocation loc, MlirType elementType)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 463 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedTensorTypeGetTypeID()
MlirTypeID mlirUnrankedTensorTypeGetTypeID (void)
Returns the typeID of an UnrankedTensor type.
Definition at line 431 of file BuiltinTypes.cpp.
References wrap().
mlirVectorTypeGet()
MlirType mlirVectorTypeGet (intptr_t rank, const int64_t * shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 377 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetChecked()
MlirType mlirVectorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, MlirType elementType)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 383 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetScalable()
MlirType mlirVectorTypeGetScalable (intptr_t rank, const int64_t * shape, const bool * scalable, MlirType elementType)
Creates a scalable vector type with the shape identified by its rank and dimensions.
A subset of dimensions may be marked as scalable via the corresponding flag list, which is expected to have as many entries as the rank of the vector. The vector is created in the same context as the element type.
Definition at line 390 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetScalableChecked()
MlirType mlirVectorTypeGetScalableChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, const bool * scalable, MlirType elementType)
Same as "mlirVectorTypeGetScalable" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 397 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetTypeID()
MlirTypeID mlirVectorTypeGetTypeID (void)
Returns the typeID of an Vector type.
Definition at line 371 of file BuiltinTypes.cpp.
References wrap().
mlirVectorTypeIsDimScalable()
bool mlirVectorTypeIsDimScalable (MlirType type, intptr_t dim)
Checks whether the "dim"-th dimension of the given vector is scalable.
Definition at line 411 of file BuiltinTypes.cpp.
References unwrap().
mlirVectorTypeIsScalable()
bool mlirVectorTypeIsScalable (MlirType type)
Checks whether the given vector type is scalable, i.e., has at least one scalable dimension.
Definition at line 407 of file BuiltinTypes.cpp.
References unwrap().