MLIR: lib/CAPI/RegisterEverything/RegisterEverything.cpp File Reference
RegisterEverything.cpp File Reference
#include "mlir-c/RegisterEverything.h"
#include "mlir/CAPI/IR.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllExtensions.h"
#include "mlir/InitAllPasses.h"
#include "mlir/Target/LLVMIR/Dialect/All.h"
#include "mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
Functions
void mlirRegisterAllDialects (MlirDialectRegistry registry)
Appends all upstream dialects and extensions to the dialect registry.
void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
void mlirRegisterAllPasses ()
Register all compiler passes of MLIR.
Function Documentation
mlirRegisterAllDialects()
void mlirRegisterAllDialects (MlirDialectRegistry registry)
Appends all upstream dialects and extensions to the dialect registry.
Definition at line 20 of file RegisterEverything.cpp.
References mlir::registerAllDialects(), mlir::registerAllExtensions(), and unwrap().
Referenced by NB_MODULE().
mlirRegisterAllLLVMTranslations()
void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
Definition at line 25 of file RegisterEverything.cpp.
References mlir::registerAllToLLVMIRTranslations(), and unwrap().
Referenced by NB_MODULE().
mlirRegisterAllPasses()
void mlirRegisterAllPasses (void)
Register all compiler passes of MLIR.
Definition at line 32 of file RegisterEverything.cpp.
References mlir::registerAllPasses().
Referenced by NB_MODULE().