MLIR: lib/CAPI/Interfaces/Interfaces.cpp File Reference
Interfaces.cpp File Reference
#include "mlir-c/Interfaces.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Interfaces.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Wrap.h"
#include "mlir/IR/ValueRange.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "llvm/ADT/ScopeExit.h"
#include <optional>
Classes
class ConditionallySpeculatableOpInterfaceFallbackModel
Fallback model for the ConditionallySpeculatable interface that uses C API callbacks.
class MemoryEffectOpInterfaceFallbackModel
Fallback model for the MemoryEffectsOpInterface that uses C API callbacks.
Functions
bool mlirOperationImplementsInterface (MlirOperation operation, MlirTypeID interfaceTypeID)
Returns true if the given operation implements an interface identified by its TypeID.
bool mlirOperationImplementsInterfaceStatic (MlirStringRef operationName, MlirContext context, MlirTypeID interfaceTypeID)
Returns true if the operation identified by its canonical string name implements the interface identified by its TypeID in the given context.
MlirTypeID mlirInferTypeOpInterfaceTypeID ()
Returns the interface TypeID of the InferTypeOpInterface.
MlirLogicalResult mlirInferTypeOpInterfaceInferReturnTypes (MlirStringRef opName, MlirContext context, MlirLocation location, intptr_t nOperands, MlirValue *operands, MlirAttribute attributes, void *properties, intptr_t nRegions, MlirRegion *regions, MlirTypesCallback callback, void *userData)
Infers the return types of the operation identified by its canonical given the arguments that will be supplied to its generic builder.
MlirTypeID mlirInferShapedTypeOpInterfaceTypeID ()
Returns the interface TypeID of the InferShapedTypeOpInterface.
MlirLogicalResult mlirInferShapedTypeOpInterfaceInferReturnTypes (MlirStringRef opName, MlirContext context, MlirLocation location, intptr_t nOperands, MlirValue *operands, MlirAttribute attributes, void *properties, intptr_t nRegions, MlirRegion *regions, MlirShapedTypeComponentsCallback callback, void *userData)
Infers the return shaped type components of the operation.
MlirTypeID mlirConditionallySpeculatableOpInterfaceTypeID ()
Returns the interface TypeID of the ConditionallySpeculatable interface.
void mlirConditionallySpeculatableOpInterfaceAttachFallbackModel (MlirContext ctx, MlirStringRef opName, MlirConditionallySpeculatableOpInterfaceCallbacks callbacks)
Attach a ConditionallySpeculatable FallbackModel to the given named op.
MlirSpeculatability mlirConditionallySpeculatableOpInterfaceGetSpeculatability (MlirOperation operation)
Returns the speculatability of the given operation.
MlirTypeID mlirMemoryEffectsOpInterfaceTypeID ()
Returns the interface TypeID of the MemoryEffectsOpInterface.
void mlirMemoryEffectsOpInterfaceAttachFallbackModel (MlirContext ctx, MlirStringRef opName, MlirMemoryEffectsOpInterfaceCallbacks callbacks)
Attach a MemoryEffectsOpInterface FallbackModel to the given named op.
Function Documentation
mlirConditionallySpeculatableOpInterfaceAttachFallbackModel()
void mlirConditionallySpeculatableOpInterfaceAttachFallbackModel (MlirContext ctx, MlirStringRef opName, MlirConditionallySpeculatableOpInterfaceCallbacks callbacks)
Attach a ConditionallySpeculatable FallbackModel to the given named op.
Attach a new FallbackModel for the ConditionallySpeculatable interface to the named operation.
The FallbackModel uses the provided callbacks to implement the interface.
Definition at line 242 of file Interfaces.cpp.
References mlir::RegisteredOperationName::lookup(), ConditionallySpeculatableOpInterfaceFallbackModel::setCallbacks(), and unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::attach().
mlirConditionallySpeculatableOpInterfaceGetSpeculatability()
MlirSpeculatability mlirConditionallySpeculatableOpInterfaceGetSpeculatability (MlirOperation operation)
Returns the speculatability of the given operation.
The operation must implement the ConditionallySpeculatable interface.
Definition at line 263 of file Interfaces.cpp.
References MlirSpeculatabilityNotSpeculatable, MlirSpeculatabilityRecursivelySpeculatable, MlirSpeculatabilitySpeculatable, mlir::Speculation::NotSpeculatable, mlir::Speculation::RecursivelySpeculatable, mlir::Speculation::Speculatable, and unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::bindDerived().
mlirConditionallySpeculatableOpInterfaceTypeID()
MlirTypeID mlirConditionallySpeculatableOpInterfaceTypeID (void)
Returns the interface TypeID of the ConditionallySpeculatable interface.
Definition at line 186 of file Interfaces.cpp.
References wrap().
mlirInferShapedTypeOpInterfaceInferReturnTypes()
MlirLogicalResult mlirInferShapedTypeOpInterfaceInferReturnTypes (MlirStringRef opName, MlirContext context, MlirLocation location, intptr_t nOperands, MlirValue * operands, MlirAttribute attributes, void * properties, intptr_t nRegions, MlirRegion * regions, MlirShapedTypeComponentsCallback callback, void * userData)
Infers the return shaped type components of the operation.
Calls callback with the types of inferred arguments on success. Returns failure otherwise.
Definition at line 133 of file Interfaces.cpp.
References mlirLogicalResultFailure(), mlirLogicalResultSuccess(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::inferReturnTypeComponents().
mlirInferShapedTypeOpInterfaceTypeID()
MlirTypeID mlirInferShapedTypeOpInterfaceTypeID (void)
Returns the interface TypeID of the InferShapedTypeOpInterface.
Definition at line 129 of file Interfaces.cpp.
References wrap().
mlirInferTypeOpInterfaceInferReturnTypes()
MlirLogicalResult mlirInferTypeOpInterfaceInferReturnTypes (MlirStringRef opName, MlirContext context, MlirLocation location, intptr_t nOperands, MlirValue * operands, MlirAttribute attributes, void * properties, intptr_t nRegions, MlirRegion * regions, MlirTypesCallback callback, void * userData)
Infers the return types of the operation identified by its canonical given the arguments that will be supplied to its generic builder.
Calls callback with the types of inferred arguments, potentially several times, on success. Returns failure otherwise.
Definition at line 92 of file Interfaces.cpp.
References MlirStringRef::data, MlirStringRef::length, mlirLogicalResultFailure(), mlirLogicalResultSuccess(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferTypeOpInterface::inferReturnTypes().
mlirInferTypeOpInterfaceTypeID()
MlirTypeID mlirInferTypeOpInterfaceTypeID (void)
Returns the interface TypeID of the InferTypeOpInterface.
Definition at line 88 of file Interfaces.cpp.
References wrap().
mlirMemoryEffectsOpInterfaceAttachFallbackModel()
void mlirMemoryEffectsOpInterfaceAttachFallbackModel (MlirContext ctx, MlirStringRef opName, MlirMemoryEffectsOpInterfaceCallbacks callbacks)
Attach a MemoryEffectsOpInterface FallbackModel to the given named op.
Attach a new FallbackModel for the MemoryEffectsOpInterface to the named operation.
The FallbackModel uses the provided callbacks to implement the interface.
Definition at line 330 of file Interfaces.cpp.
References mlir::RegisteredOperationName::lookup(), MemoryEffectOpInterfaceFallbackModel::setCallbacks(), and unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::attach().
mlirMemoryEffectsOpInterfaceTypeID()
MlirTypeID mlirMemoryEffectsOpInterfaceTypeID (void)
Returns the interface TypeID of the MemoryEffectsOpInterface.
Definition at line 283 of file Interfaces.cpp.
References wrap().
mlirOperationImplementsInterface()
bool mlirOperationImplementsInterface (MlirOperation operation, MlirTypeID interfaceTypeID)
Returns true if the given operation implements an interface identified by its TypeID.
Definition at line 73 of file Interfaces.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< ConcreteIface >::PyConcreteOpInterface().
mlirOperationImplementsInterfaceStatic()
bool mlirOperationImplementsInterfaceStatic (MlirStringRef operationName, MlirContext context, MlirTypeID interfaceTypeID)
Returns true if the operation identified by its canonical string name implements the interface identified by its TypeID in the given context.
Note that interfaces may be attached to operations in some contexts and not others.
Definition at line 80 of file Interfaces.cpp.
References MlirStringRef::data, MlirStringRef::length, mlir::RegisteredOperationName::lookup(), and unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< ConcreteIface >::PyConcreteOpInterface().