MLIR: lib/CAPI/Dialect/IRDL.cpp File Reference
IRDL.cpp File Reference
#include "mlir-c/Dialect/IRDL.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/IRDL/IR/IRDL.h"
#include "mlir/Dialect/IRDL/IRDLLoading.h"
Functions
MlirLogicalResult mlirLoadIRDLDialects (MlirModule module)
Loads all IRDL dialects in the provided module, registering the dialects in the module's associated context.
MlirAttribute mlirIRDLVariadicityAttrGet (MlirContext ctx, MlirStringRef value)
MlirAttribute mlirIRDLVariadicityArrayAttrGet (MlirContext ctx, intptr_t nValues, MlirAttribute const *values)
Function Documentation
mlirIRDLVariadicityArrayAttrGet()
MlirAttribute mlirIRDLVariadicityArrayAttrGet (MlirContext ctx, intptr_t nValues, MlirAttribute const * values)
Definition at line 33 of file IRDL.cpp.
References unwrap(), unwrapList(), and wrap().
mlirIRDLVariadicityAttrGet()
MlirAttribute mlirIRDLVariadicityAttrGet (MlirContext ctx, MlirStringRef value)
Definition at line 24 of file IRDL.cpp.
References unwrap(), and wrap().
mlirLoadIRDLDialects()
MlirLogicalResult mlirLoadIRDLDialects (MlirModule module)
Loads all IRDL dialects in the provided module, registering the dialects in the module's associated context.
Definition at line 16 of file IRDL.cpp.
References mlir::irdl::loadDialects(), mlirLoadIRDLDialects(), unwrap(), and wrap().
Referenced by mlirLoadIRDLDialects(), and populateDialectIRDLSubmodule().