MLIR: lib/CAPI/Dialect/PDL.cpp File Reference
PDL.cpp File Reference
#include "mlir-c/Dialect/PDL.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
Functions
bool mlirTypeIsAPDLType (MlirType type)
bool mlirTypeIsAPDLAttributeType (MlirType type)
MlirType mlirPDLAttributeTypeGet (MlirContext ctx)
bool mlirTypeIsAPDLOperationType (MlirType type)
MlirType mlirPDLOperationTypeGet (MlirContext ctx)
bool mlirTypeIsAPDLRangeType (MlirType type)
MlirType mlirPDLRangeTypeGet (MlirType elementType)
MlirType mlirPDLRangeTypeGetElementType (MlirType type)
bool mlirTypeIsAPDLTypeType (MlirType type)
MlirType mlirPDLTypeTypeGet (MlirContext ctx)
bool mlirTypeIsAPDLValueType (MlirType type)
MlirType mlirPDLValueTypeGet (MlirContext ctx)
Function Documentation
mlirPDLAttributeTypeGet()
MlirType mlirPDLAttributeTypeGet (MlirContext ctx)
Definition at line 35 of file PDL.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectPDLSubmodule().
mlirPDLOperationTypeGet()
MlirType mlirPDLOperationTypeGet (MlirContext ctx)
Definition at line 47 of file PDL.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectPDLSubmodule().
mlirPDLRangeTypeGet()
MlirType mlirPDLRangeTypeGet (MlirType elementType)
Definition at line 59 of file PDL.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectPDLSubmodule().
mlirPDLRangeTypeGetElementType()
MlirType mlirPDLRangeTypeGetElementType (MlirType type)
Definition at line 63 of file PDL.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by populateDialectPDLSubmodule().
mlirPDLTypeTypeGet()
MlirType mlirPDLTypeTypeGet (MlirContext ctx)
Definition at line 75 of file PDL.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectPDLSubmodule().
mlirPDLValueTypeGet()
MlirType mlirPDLValueTypeGet (MlirContext ctx)
Definition at line 87 of file PDL.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectPDLSubmodule().
mlirTypeIsAPDLAttributeType()
bool mlirTypeIsAPDLAttributeType (MlirType type)
Definition at line 31 of file PDL.cpp.
References unwrap().
Referenced by populateDialectPDLSubmodule().
mlirTypeIsAPDLOperationType()
bool mlirTypeIsAPDLOperationType (MlirType type)
Definition at line 43 of file PDL.cpp.
References unwrap().
Referenced by populateDialectPDLSubmodule().
mlirTypeIsAPDLRangeType()
bool mlirTypeIsAPDLRangeType (MlirType type)
Definition at line 55 of file PDL.cpp.
References unwrap().
Referenced by populateDialectPDLSubmodule().
mlirTypeIsAPDLType()
bool mlirTypeIsAPDLType (MlirType type)
Definition at line 23 of file PDL.cpp.
References unwrap().
Referenced by populateDialectPDLSubmodule().
mlirTypeIsAPDLTypeType()
bool mlirTypeIsAPDLTypeType (MlirType type)
Definition at line 71 of file PDL.cpp.
References unwrap().
Referenced by populateDialectPDLSubmodule().
mlirTypeIsAPDLValueType()
bool mlirTypeIsAPDLValueType (MlirType type)
Definition at line 83 of file PDL.cpp.
References unwrap().
Referenced by populateDialectPDLSubmodule().