MLIR: mlir::affine::AffineBound Class Reference
mlir::affine::AffineBound Class Reference
AffineBound represents a lower or upper bound in the for operation.
#include "mlir/Dialect/Affine/IR/AffineOps.h"
Public Types
using operand_iterator = AffineForOp::operand_iterator
using operand_range = AffineForOp::operand_range
Public Member Functions
AffineForOp getAffineForOp ()
AffineMap getMap ()
unsigned getNumOperands ()
Value getOperand (unsigned idx)
operand_iterator operandBegin ()
operand_iterator operandEnd ()
operand_range getOperands ()
Friends
class AffineForOp
Detailed Description
AffineBound represents a lower or upper bound in the for operation.
This class does not own the underlying operands. Instead, it refers to the operands stored in the AffineForOp. Its life span should not exceed that of the for operation it refers to.
Definition at line 550 of file AffineOps.h.
Member Typedef Documentation
operand_iterator
using mlir::affine::AffineBound::operand_iterator = AffineForOp::operand_iterator
Definition at line 560 of file AffineOps.h.
operand_range
using mlir::affine::AffineBound::operand_range = AffineForOp::operand_range
Definition at line 561 of file AffineOps.h.
Member Function Documentation
getAffineForOp()
AffineForOp mlir::affine::AffineBound::getAffineForOp () inline
Definition at line 552 of file AffineOps.h.
getMap()
AffineMap mlir::affine::AffineBound::getMap () inline
Definition at line 553 of file AffineOps.h.
Referenced by mlir::affine::coalesceLoops(), constructTiledIndexSetHyperRect(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getNumOperands()
unsigned mlir::affine::AffineBound::getNumOperands () inline
Definition at line 555 of file AffineOps.h.
Referenced by constructTiledIndexSetHyperRect(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getOperand()
Value mlir::affine::AffineBound::getOperand (unsigned idx) inline
Definition at line 556 of file AffineOps.h.
References mlir::OperandRange::getBeginOperandIndex().
Referenced by constructTiledIndexSetHyperRect(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getOperands()
operand_range mlir::affine::AffineBound::getOperands () inline
Definition at line 565 of file AffineOps.h.
References operandBegin(), and operandEnd().
Referenced by mlir::affine::coalesceLoops().
operandBegin()
operand_iterator mlir::affine::AffineBound::operandBegin () inline
Definition at line 563 of file AffineOps.h.
Referenced by getOperands().
operandEnd()
operand_iterator mlir::affine::AffineBound::operandEnd () inline
Definition at line 564 of file AffineOps.h.
Referenced by getOperands().
Friends And Related Function Documentation
AffineForOp
friend class AffineForOp friend
Definition at line 578 of file AffineOps.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Affine/IR/AffineOps.h