MLIR: mlir::arith::AttrConvertFastMathToLLVM< SourceOp, TargetOp > Class Template Reference
mlir::arith::AttrConvertFastMathToLLVM< SourceOp, TargetOp > Class Template Reference
#include "mlir/Conversion/ArithCommon/AttrToLLVMConverter.h"
Public Member Functions
AttrConvertFastMathToLLVM (SourceOp srcOp)
ArrayRef< NamedAttribute > getAttrs () const
LLVM::IntegerOverflowFlags getOverflowFlags () const
Detailed Description
template<typename SourceOp, typename TargetOp>
class mlir::arith::AttrConvertFastMathToLLVM< SourceOp, TargetOp >
Definition at line 52 of file AttrToLLVMConverter.h.
Constructor & Destructor Documentation
AttrConvertFastMathToLLVM()
template<typename SourceOp , typename TargetOp > mlir::arith::AttrConvertFastMathToLLVM< SourceOp, TargetOp >::AttrConvertFastMathToLLVM (SourceOp srcOp) inline
Definition at line 54 of file AttrToLLVMConverter.h.
References mlir::arith::convertArithFastMathAttrToLLVM(), mlir::NamedAttrList::erase(), mlir::NamedAttrList::getAttrs(), and mlir::NamedAttrList::set().
Member Function Documentation
getAttrs()
template<typename SourceOp , typename TargetOp > ArrayRef<NamedAttribute> mlir::arith::AttrConvertFastMathToLLVM< SourceOp, TargetOp >::getAttrs () const inline
Definition at line 69 of file AttrToLLVMConverter.h.
References mlir::NamedAttrList::getAttrs().
getOverflowFlags()
template<typename SourceOp , typename TargetOp > LLVM::IntegerOverflowFlags mlir::arith::AttrConvertFastMathToLLVM< SourceOp, TargetOp >::getOverflowFlags () const inline
Definition at line 70 of file AttrToLLVMConverter.h.
The documentation for this class was generated from the following file:
include/mlir/Conversion/ArithCommon/AttrToLLVMConverter.h