MLIR: mlir::PassPipelineInfo Class Reference
mlir::PassPipelineInfo Class Reference
A structure to represent the information of a registered pass pipeline.
#include "mlir/Pass/PassRegistry.h"
Public Member Functions
PassPipelineInfo (StringRef arg, StringRef description, const PassRegistryFunction &builder, std::function< void(function_ref< void(const detail::PassOptions &)>)> optHandler)
Public Member Functions inherited from mlir::PassRegistryEntry
LogicalResult addToPipeline (OpPassManager &pm, StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler) const
Adds this pass registry entry to the given pass manager.
StringRef getPassArgument () const
Returns the command line option that may be passed to 'mlir-opt' that will cause this pass to run or null if there is no such argument.
StringRef getPassDescription () const
Returns a description for the pass, this never returns null.
void printHelpStr (size_t indent, size_t descIndent) const
Print the help information for this pass.
size_t getOptionWidth () const
Return the maximum width required when printing the options of this entry.
Static Public Member Functions
static const PassPipelineInfo * lookup (StringRef pipelineArg)
Returns the pass pipeline info for the specified pass pipeline or null if unknown.
Additional Inherited Members
Protected Member Functions inherited from mlir::PassRegistryEntry
PassRegistryEntry (StringRef arg, StringRef description, const PassRegistryFunction &builder, std::function< void(function_ref< void(const detail::PassOptions &)>)> optHandler)
Detailed Description
A structure to represent the information of a registered pass pipeline.
Definition at line 104 of file PassRegistry.h.
Constructor & Destructor Documentation
PassPipelineInfo()
mlir::PassPipelineInfo::PassPipelineInfo (StringRef arg, StringRef description, const PassRegistryFunction & builder, std::function< void(function_ref< void(const detail::PassOptions &)>)> optHandler) inline
Definition at line 106 of file PassRegistry.h.
References mlir::PassRegistryEntry::PassRegistryEntry().
Referenced by lookup().
Member Function Documentation
lookup()
const PassPipelineInfo * mlir::PassPipelineInfo::lookup (StringRef pipelineArg) static
Returns the pass pipeline info for the specified pass pipeline or null if unknown.
Returns the pass pipeline info for the specified pass pipeline argument or null if unknown.
Definition at line 179 of file PassRegistry.cpp.
References nullptr, PassPipelineInfo(), and passPipelineRegistry.
The documentation for this class was generated from the following files:
include/mlir/Pass/PassRegistry.h
lib/Pass/PassRegistry.cpp