MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator Class Reference
#include "mlir/Bindings/Python/Globals.h"
Public Member Functions
TypeIDAllocator ()
~TypeIDAllocator ()
TypeIDAllocator (const TypeIDAllocator &)=delete
TypeIDAllocator (TypeIDAllocator &&other)
MlirTypeIDAllocator get ()
MlirTypeID allocate ()
Detailed Description
Definition at line 187 of file Globals.h.
Constructor & Destructor Documentation
TypeIDAllocator() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator::TypeIDAllocator () inline
Definition at line 189 of file Globals.h.
References mlirTypeIDAllocatorCreate().
Referenced by TypeIDAllocator(), and TypeIDAllocator().
~TypeIDAllocator()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator::~TypeIDAllocator () inline
Definition at line 190 of file Globals.h.
References mlirTypeIDAllocatorDestroy().
TypeIDAllocator() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator::TypeIDAllocator (const TypeIDAllocator &) delete
References TypeIDAllocator().
TypeIDAllocator() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator::TypeIDAllocator (TypeIDAllocator && other) inline
Definition at line 195 of file Globals.h.
References TypeIDAllocator().
Member Function Documentation
allocate()
MlirTypeID mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator::allocate () inline
Definition at line 200 of file Globals.h.
References mlirTypeIDAllocatorAllocateTypeID().
get()
MlirTypeIDAllocator mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TypeIDAllocator::get () inline
Definition at line 199 of file Globals.h.
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/Globals.h