MLIR: mlir::OperationFolder Class Reference
mlir::OperationFolder Class Reference
A utility class for folding operations, and unifying duplicated constants generated along the way.
#include "mlir/Transforms/FoldUtils.h"
Public Member Functions
OperationFolder (MLIRContext *ctx)
LogicalResult tryToFold (Operation *op, function_ref< void(Operation *)> processGeneratedConstants=nullptr, function_ref< void(Operation *)> preReplaceAction=nullptr, bool *inPlaceUpdate=nullptr)
Tries to perform folding on the given op, including unifying deduplicated constants.
void notifyRemoval (Operation *op)
Notifies that the given constant op should be remove from this OperationFolder's internal bookkeeping.
template<typename OpTy , typename... Args>
void create (OpBuilder &builder, SmallVectorImpl< Value > &results, Location location, Args &&... args)
Create an operation of specific op type with the given builder, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::OneResult >), Value >::type create (OpBuilder &builder, Location location, Args &&... args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::ZeroResult >), OpTy >::type create (OpBuilder &builder, Location location, Args &&... args)
Overload to create or fold a zero result operation.
void clear ()
Clear out any constants cached inside of the folder.
Value getOrCreateConstant (OpBuilder &builder, Dialect *dialect, Attribute value, Type type, Location loc)
Get or create a constant using the given builder.
Detailed Description
A utility class for folding operations, and unifying duplicated constants generated along the way.
Definition at line 32 of file FoldUtils.h.
Constructor & Destructor Documentation
OperationFolder()
mlir::OperationFolder::OperationFolder (MLIRContext * ctx) inline
Definition at line 34 of file FoldUtils.h.
References notifyRemoval(), op, and tryToFold().
Member Function Documentation
clear()
void OperationFolder::clear ()
Clear out any constants cached inside of the folder.
Definition at line 150 of file FoldUtils.cpp.
Referenced by create().
create() [1/3]
template<typename OpTy , typename... Args> void mlir::OperationFolder::create (OpBuilder & builder, SmallVectorImpl< Value > & results, Location location, Args &&... args) inline
Create an operation of specific op type with the given builder, and immediately try to fold it.
This function populates 'results' with the results after folding the operation.
Definition at line 59 of file FoldUtils.h.
References mlir::Operation::create(), mlir::Operation::destroy(), mlir::failed(), mlir::OpBuilder::insert(), mlir::Operation::result_begin(), mlir::Operation::result_end(), and tryToFold().
create() [2/3]
template<typename OpTy , typename... Args> std::enable_if<OpTy::template hasTrait<OpTrait::OneResult>), Value>::type mlir::OperationFolder::create (OpBuilder & builder, Location location, Args &&... args) inline
Overload to create or fold a single result operation.
Definition at line 81 of file FoldUtils.h.
create() [3/3]
template<typename OpTy , typename... Args> std::enable_if<OpTy::template hasTrait<OpTrait::ZeroResult>), OpTy>::type mlir::OperationFolder::create (OpBuilder & builder, Location location, Args &&... args) inline
Overload to create or fold a zero result operation.
Definition at line 91 of file FoldUtils.h.
References clear(), mlir::OpBuilder::create(), getOrCreateConstant(), loc, op, tryToFold(), and value.
getOrCreateConstant()
Value OperationFolder::getOrCreateConstant (OpBuilder & builder, Dialect * dialect, Attribute value, Type type, Location loc)
Get or create a constant using the given builder.
On success this returns the constant operation, nullptr otherwise.
Definition at line 157 of file FoldUtils.cpp.
References mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::fold(), mlir::Region::front(), mlir::Operation::getDialect(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), getInsertionRegion(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getOpOperands(), mlir::Operation::getResult(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::Operation::hasTrait(), loc, mlir::m_Constant(), mlir::matchPattern(), materializeConstant(), notifyRemoval(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), tryToFold(), and value.
Referenced by create(), and replaceWithConstant().
notifyRemoval()
void OperationFolder::notifyRemoval (Operation * op)
Notifies that the given constant op should be remove from this OperationFolder's internal bookkeeping.
Note: this method must be called if a constant op is to be deleted externally to this OperationFolder. op must be a constant op.
Definition at line 126 of file FoldUtils.cpp.
References mlir::Operation::getBlock(), getInsertionRegion(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::m_Constant(), and mlir::matchPattern().
Referenced by getOrCreateConstant(), and OperationFolder().
tryToFold()
LogicalResult OperationFolder::tryToFold (Operation * op, function_ref< void(Operation *)> processGeneratedConstants = nullptr, function_ref< void(Operation *)> preReplaceAction = nullptr, bool * inPlaceUpdate = nullptr)
Tries to perform folding on the given op, including unifying deduplicated constants.
If successful, replaces op's uses with folded results, and returns success. preReplaceAction is invoked on op before it is replaced. 'processGeneratedConstants' is invoked for any new operations generated when folding. If the op was completely folded it is erased. If it is just updated in place, inPlaceUpdate is set to true.
Definition at line 87 of file FoldUtils.cpp.
References mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::getResult(), mlir::Value::replaceAllUsesWith(), and mlir::success().
Referenced by create(), getOrCreateConstant(), and OperationFolder().
The documentation for this class was generated from the following files:
include/mlir/Transforms/FoldUtils.h
lib/Transforms/Utils/FoldUtils.cpp