MLIR: llvm::cl::detail::VectorParserBase< VectorT, ElementT > Class Template Reference
llvm::cl::detail::VectorParserBase< VectorT, ElementT > Class Template Reference
#include "mlir/Pass/PassOptions.h"
Public Types
using parser_data_type = VectorT
Public Member Functions
VectorParserBase (Option &opt)
bool parse (Option &opt, StringRef argName, StringRef arg, parser_data_type &vector)
void printOptionInfo (const Option &opt, size_t globalWidth) const
size_t getOptionWidth (const Option &opt) const
Static Public Member Functions
static void print (raw_ostream &os, const VectorT &vector)
Detailed Description
template<typename VectorT, typename ElementT>
class llvm::cl::detail::VectorParserBase< VectorT, ElementT >
Definition at line 410 of file PassOptions.h.
Member Typedef Documentation
parser_data_type
template<typename VectorT , typename ElementT > using llvm::cl::detail::VectorParserBase< VectorT, ElementT >::parser_data_type = VectorT
Definition at line 414 of file PassOptions.h.
Constructor & Destructor Documentation
VectorParserBase()
template<typename VectorT , typename ElementT > llvm::cl::detail::VectorParserBase< VectorT, ElementT >::VectorParserBase (Option & opt) inline
Definition at line 412 of file PassOptions.h.
Member Function Documentation
getOptionWidth()
template<typename VectorT , typename ElementT > size_t llvm::cl::detail::VectorParserBase< VectorT, ElementT >::getOptionWidth (const Option & opt) const inline
Definition at line 445 of file PassOptions.h.
Referenced by llvm::cl::detail::VectorParserBase< VectorT, ElementT >::printOptionInfo().
parse()
template<typename VectorT , typename ElementT > bool llvm::cl::detail::VectorParserBase< VectorT, ElementT >::parse (Option & opt, StringRef argName, StringRef arg, parser_data_type & vector) inline
Definition at line 416 of file PassOptions.h.
References mlir::detail::pass_options::parseCommaSeparatedList().
print()
template<typename VectorT , typename ElementT > static void llvm::cl::detail::VectorParserBase< VectorT, ElementT >::print (raw_ostream & os, const VectorT & vector) inline static
Definition at line 428 of file PassOptions.h.
References mlir::detail::pass_options::printOptionValue().
printOptionInfo()
template<typename VectorT , typename ElementT > void llvm::cl::detail::VectorParserBase< VectorT, ElementT >::printOptionInfo (const Option & opt, size_t globalWidth) const inline
Definition at line 438 of file PassOptions.h.
References llvm::cl::detail::VectorParserBase< VectorT, ElementT >::getOptionWidth().
The documentation for this class was generated from the following file:
include/mlir/Pass/PassOptions.h