MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine Class Reference
Owning Wrapper around an ExecutionEngine.
Public Member Functions
PyExecutionEngine (MlirExecutionEngine executionEngine)
PyExecutionEngine (PyExecutionEngine &&other) noexcept
~PyExecutionEngine ()
MlirExecutionEngine get ()
void release ()
nb::object getCapsule ()
void addReferencedObject (const nb::object &obj)
Static Public Member Functions
static nb::object createFromCapsule (const nb::object &capsule)
Detailed Description
Owning Wrapper around an ExecutionEngine.
Definition at line 24 of file ExecutionEngineModule.cpp.
Constructor & Destructor Documentation
PyExecutionEngine() [1/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::PyExecutionEngine (MlirExecutionEngine executionEngine) inline
Definition at line 26 of file ExecutionEngineModule.cpp.
Referenced by createFromCapsule(), and PyExecutionEngine().
PyExecutionEngine() [2/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::PyExecutionEngine (PyExecutionEngine && other) inline noexcept
Definition at line 28 of file ExecutionEngineModule.cpp.
References PyExecutionEngine().
~PyExecutionEngine()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::~PyExecutionEngine () inline
Definition at line 32 of file ExecutionEngineModule.cpp.
References mlirExecutionEngineDestroy(), and mlirExecutionEngineIsNull().
Member Function Documentation
addReferencedObject()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::addReferencedObject (const nb::object & obj) inline
Definition at line 48 of file ExecutionEngineModule.cpp.
createFromCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::createFromCapsule (const nb::object & capsule) inline static
Definition at line 52 of file ExecutionEngineModule.cpp.
References mlirExecutionEngineIsNull(), mlirPythonCapsuleToExecutionEngine(), and PyExecutionEngine().
get()
MlirExecutionEngine mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::get () inline
Definition at line 36 of file ExecutionEngineModule.cpp.
Referenced by getCapsule().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::getCapsule () inline
Definition at line 42 of file ExecutionEngineModule.cpp.
References get(), and mlirPythonExecutionEngineToCapsule().
release()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::execution_engine::PyExecutionEngine::release () inline
Definition at line 38 of file ExecutionEngineModule.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/ExecutionEngineModule.cpp