MLIR: mlir::RegionBranchPoint Class Reference
mlir::RegionBranchPoint Class Reference
This class represents a point being branched from in the methods of the RegionBranchOpInterface.
#include "mlir/Interfaces/ControlFlowInterfaces.h"
Public Member Functions
RegionBranchPoint (Region *region)
Creates a RegionBranchPoint that branches from the given region.
RegionBranchPoint (Region &region)
RegionBranchPoint (std::nullptr_t)=delete
Explicitly stops users from constructing with nullptr.
RegionBranchPoint (RegionSuccessor successor)
Constructs a RegionBranchPoint from the the target of a RegionSuccessor instance.
RegionBranchPoint & operator= (Region &region)
Assigns a region being branched from.
bool isParent () const
Returns true if branching from the parent op.
Region * getRegionOrNull () const
Returns the region if branching from a region.
Static Public Member Functions
static constexpr RegionBranchPoint parent ()
Returns an instance of RegionBranchPoint representing the parent operation.
Friends
bool operator== (RegionBranchPoint lhs, RegionBranchPoint rhs)
Returns true if the two branch points are equal.
Detailed Description
This class represents a point being branched from in the methods of the RegionBranchOpInterface.
One can branch from one of two kinds of places:
The parent operation (aka the RegionBranchOpInterface implementation)
A region within the parent operation.
Definition at line 218 of file ControlFlowInterfaces.h.
Constructor & Destructor Documentation
RegionBranchPoint() [1/4]
mlir::RegionBranchPoint::RegionBranchPoint (Region * region) inline
Creates a RegionBranchPoint that branches from the given region.
The pointer must not be null.
Definition at line 226 of file ControlFlowInterfaces.h.
RegionBranchPoint() [2/4]
mlir::RegionBranchPoint::RegionBranchPoint (Region & region) inline
Definition at line 230 of file ControlFlowInterfaces.h.
RegionBranchPoint() [3/4]
mlir::RegionBranchPoint::RegionBranchPoint (std::nullptr_t) delete
Explicitly stops users from constructing with nullptr.
RegionBranchPoint() [4/4]
mlir::RegionBranchPoint::RegionBranchPoint (RegionSuccessor successor) inline
Constructs a RegionBranchPoint from the the target of a RegionSuccessor instance.
Definition at line 237 of file ControlFlowInterfaces.h.
References mlir::RegionSuccessor::getSuccessor(), and mlir::RegionSuccessor::isParent().
Member Function Documentation
getRegionOrNull()
Region* mlir::RegionBranchPoint::getRegionOrNull () const inline
Returns the region if branching from a region.
A null pointer otherwise.
Definition at line 255 of file ControlFlowInterfaces.h.
Referenced by printRegionEdgeName().
isParent()
bool mlir::RegionBranchPoint::isParent () const inline
Returns true if branching from the parent op.
Definition at line 251 of file ControlFlowInterfaces.h.
operator=()
RegionBranchPoint& mlir::RegionBranchPoint::operator= (Region & region) inline
Assigns a region being branched from.
Definition at line 245 of file ControlFlowInterfaces.h.
parent()
static constexpr RegionBranchPoint mlir::RegionBranchPoint::parent () inline static constexpr
Returns an instance of RegionBranchPoint representing the parent operation.
Definition at line 222 of file ControlFlowInterfaces.h.
Referenced by collectUnderlyingAddressValues(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::processOperation(), and mlir::detail::verifyTypesAlongControlFlowEdges().
Friends And Related Function Documentation
operator==
bool operator== (RegionBranchPoint lhs, RegionBranchPoint rhs) friend
Returns true if the two branch points are equal.
Definition at line 258 of file ControlFlowInterfaces.h.
The documentation for this class was generated from the following file:
include/mlir/Interfaces/ControlFlowInterfaces.h