MLIR: mlir::detail::ForwardDataFlowAnalysisBase Class Reference
mlir::detail::ForwardDataFlowAnalysisBase Class Reference abstract
This class is the non-templated virtual base class for the ForwardDataFlowAnalysis.
#include "mlir/Analysis/DataFlowAnalysis.h"
Public Member Functions
virtual ~ForwardDataFlowAnalysisBase ()
void run (Operation *topLevelOp)
Initialize and compute the analysis on operations rooted under the given top-level operation.
AbstractLatticeElement & getLatticeElement (Value value)
Return the lattice element attached to the given value.
AbstractLatticeElement * lookupLatticeElement (Value value)
Return the lattice element attached to the given value, or nullptr if no lattice for the value has yet been created.
virtual ChangeResult visitOperation (Operation *op, ArrayRef< AbstractLatticeElement *> operands)=0
Visit the given operation, and join any necessary analysis state into the lattices for the results and block arguments owned by this operation using the provided set of operand lattice elements (all pointer values are guaranteed to be non-null).
virtual LogicalResult getSuccessorsForOperands (BranchOpInterface branch, ArrayRef< AbstractLatticeElement *> operands, SmallVectorImpl< Block *> &successors)=0
Given a BranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), try to compute a specific set of successors that would be selected for the branch.
virtual void getSuccessorsForOperands (RegionBranchOpInterface branch, Optional< unsigned > sourceIndex, ArrayRef< AbstractLatticeElement *> operands, SmallVectorImpl< RegionSuccessor > &successors)=0
Given a RegionBranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), compute a specific set of region successors that would be selected.
virtual AbstractLatticeElement * createLatticeElement (Value value={})=0
Create a new uninitialized lattice element.
Detailed Description
This class is the non-templated virtual base class for the ForwardDataFlowAnalysis.
This class provides opaque hooks to the main alogrithm.
Definition at line 204 of file DataFlowAnalysis.h.
Constructor & Destructor Documentation
~ForwardDataFlowAnalysisBase()
ForwardDataFlowAnalysisBase::~ForwardDataFlowAnalysisBase () virtual
Definition at line 763 of file DataFlowAnalysis.cpp.
Member Function Documentation
createLatticeElement()
virtual AbstractLatticeElement* mlir::detail::ForwardDataFlowAnalysisBase::createLatticeElement (Value value = {}) pure virtual
Create a new uninitialized lattice element.
An optional value is provided which, if valid, should be used to initialize the known conservative state of the lattice.
getLatticeElement()
AbstractLatticeElement & ForwardDataFlowAnalysisBase::getLatticeElement (Value value)
Return the lattice element attached to the given value.
If a lattice has not been added for the given value, a new 'uninitialized' value is inserted and returned.
Definition at line 766 of file DataFlowAnalysis.cpp.
References value.
Referenced by mlir::ForwardDataFlowAnalysis< ValueT >::getLatticeElement().
getSuccessorsForOperands() [1/2]
virtual LogicalResult mlir::detail::ForwardDataFlowAnalysisBase::getSuccessorsForOperands (BranchOpInterface branch, ArrayRef< AbstractLatticeElement *> operands, SmallVectorImpl< Block *> & successors) pure virtual
Given a BranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), try to compute a specific set of successors that would be selected for the branch.
Returns failure if not computable, or if all of the successors would be chosen. If a subset of successors can be selected, successors is populated.
getSuccessorsForOperands() [2/2]
virtual void mlir::detail::ForwardDataFlowAnalysisBase::getSuccessorsForOperands (RegionBranchOpInterface branch, Optional< unsigned > sourceIndex, ArrayRef< AbstractLatticeElement *> operands, SmallVectorImpl< RegionSuccessor > & successors) pure virtual
Given a RegionBranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), compute a specific set of region successors that would be selected.
lookupLatticeElement()
AbstractLatticeElement * ForwardDataFlowAnalysisBase::lookupLatticeElement (Value value)
Return the lattice element attached to the given value, or nullptr if no lattice for the value has yet been created.
Definition at line 774 of file DataFlowAnalysis.cpp.
Referenced by mlir::ForwardDataFlowAnalysis< ValueT >::lookupLatticeElement().
run()
void ForwardDataFlowAnalysisBase::run (Operation * topLevelOp)
Initialize and compute the analysis on operations rooted under the given top-level operation.
Note that the top-level operation is not visited.
Definition at line 778 of file DataFlowAnalysis.cpp.
Referenced by mlir::ForwardDataFlowAnalysis< ValueT >::run().
visitOperation()
virtual ChangeResult mlir::detail::ForwardDataFlowAnalysisBase::visitOperation (Operation * op, ArrayRef< AbstractLatticeElement *> operands) pure virtual
Visit the given operation, and join any necessary analysis state into the lattices for the results and block arguments owned by this operation using the provided set of operand lattice elements (all pointer values are guaranteed to be non-null).
Returns if any result or block argument value lattices changed during the visit. The lattice for a result or block argument value can be obtained and join'ed into by using getLatticeElement.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlowAnalysis.h
lib/Analysis/DataFlowAnalysis.cpp