MLIR: mlir::transform::AtMostOneOpMatcherOpTrait< OpTy > Class Template Reference
mlir::transform::AtMostOneOpMatcherOpTrait< OpTy > Class Template Reference
#include "mlir/Dialect/Transform/Interfaces/MatchInterfaces.h"
Public Member Functions
DiagnosedSilenceableFailure apply (TransformRewriter &rewriter, TransformResults &results, TransformState &state)
void getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< OpTy, AtMostOneOpMatcherOpTrait >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename OpTy>
class mlir::transform::AtMostOneOpMatcherOpTrait< OpTy >
Definition at line 42 of file MatchInterfaces.h.
Member Function Documentation
apply()
template<typename OpTy> DiagnosedSilenceableFailure mlir::transform::AtMostOneOpMatcherOpTrait< OpTy >::apply (TransformRewriter & rewriter, TransformResults & results, TransformState & state) inline
Definition at line 86 of file MatchInterfaces.h.
References mlir::emitDefiniteFailure(), mlir::OpTrait::TraitBase< OpTy, AtMostOneOpMatcherOpTrait >::getOperation(), mlir::transform::TransformState::getPayloadOps(), and mlir::transform::detail::matchOptionalOperation().
getEffects()
template<typename OpTy> void mlir::transform::AtMostOneOpMatcherOpTrait< OpTy >::getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > & effects) inline
Definition at line 104 of file MatchInterfaces.h.
References mlir::OpTrait::TraitBase< OpTy, AtMostOneOpMatcherOpTrait >::getOperation(), mlir::transform::onlyReadsHandle(), mlir::transform::onlyReadsPayload(), and mlir::transform::producesHandle().
verifyTrait()
template<typename OpTy> LogicalResult mlir::transform::AtMostOneOpMatcherOpTrait< OpTy >::verifyTrait (Operation * op) inline static
Definition at line 59 of file MatchInterfaces.h.
References mlir::Operation::emitError(), mlir::Value::getType(), and success().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/Interfaces/MatchInterfaces.h