MLIR: mlir::NumberOfExecutions Class Reference
mlir::NumberOfExecutions Class Reference
Represents an analysis for computing how many times a block or an operation within a region is executed each time that region is entered.
#include "mlir/Analysis/NumberOfExecutions.h"
Public Member Functions
NumberOfExecutions (Operation *op)
Creates a new NumberOfExecutions analysis that computes how many times a block within a region is executed for all associated regions.
Optional< int64_t > getNumberOfExecutions (Operation *op, Region *perEntryOfThisRegion) const
Returns the number of times operations op is executed each time the control flow enters the region perEntryOfThisRegion.
Optional< int64_t > getNumberOfExecutions (Block *block, Region *perEntryOfThisRegion) const
Returns the number of times block block is executed each time the control flow enters the region perEntryOfThisRegion.
void printBlockExecutions (raw_ostream &os, Region *perEntryOfThisRegion) const
Dumps the number of block executions each time the control flow enters the region perEntryOfThisRegion to the given stream.
void printOperationExecutions (raw_ostream &os, Region *perEntryOfThisRegion) const
Dumps the number of operation executions each time the control flow enters the region perEntryOfThisRegion to the given stream.
Detailed Description
Represents an analysis for computing how many times a block or an operation within a region is executed each time that region is entered.
The analysis iterates over all associated regions that are attached to the given top-level operation.
This analysis assumes that all operations complete in a finite amount of time (do not abort and do not go into the infinite loop).
Definition at line 39 of file NumberOfExecutions.h.
Constructor & Destructor Documentation
NumberOfExecutions()
NumberOfExecutions::NumberOfExecutions (Operation * op) explicit
Creates a new NumberOfExecutions analysis that computes how many times a block within a region is executed for all associated regions.
Definition at line 117 of file NumberOfExecutions.cpp.
References computeRegionBlockNumberOfExecutions(), mlir::PreOrder, and mlir::Operation::walk().
Member Function Documentation
getNumberOfExecutions() [1/2]
Optional< int64_t > NumberOfExecutions::getNumberOfExecutions (Operation * op, Region * perEntryOfThisRegion) const
Returns the number of times operations op is executed each time the control flow enters the region perEntryOfThisRegion.
Returns empty optional if this is not known statically.
Definition at line 124 of file NumberOfExecutions.cpp.
References mlir::Operation::getBlock().
Referenced by getNumberOfExecutions(), printBlockExecutions(), and printOperationExecutions().
getNumberOfExecutions() [2/2]
Optional< int64_t > NumberOfExecutions::getNumberOfExecutions (Block * block, Region * perEntryOfThisRegion) const
Returns the number of times block block is executed each time the control flow enters the region perEntryOfThisRegion.
Returns empty optional if this is not known statically.
Definition at line 134 of file NumberOfExecutions.cpp.
References mlir::Region::findAncestorBlockInRegion(), mlir::Operation::getBlock(), getNumberOfExecutions(), mlir::Block::getParentOp(), mlir::Operation::getParentOp(), and mlir::Region::getParentOp().
printBlockExecutions()
void NumberOfExecutions::printBlockExecutions (raw_ostream & os, Region * perEntryOfThisRegion) const
Dumps the number of block executions each time the control flow enters the region perEntryOfThisRegion to the given stream.
Definition at line 190 of file NumberOfExecutions.cpp.
References getNumberOfExecutions(), mlir::PreOrder, and mlir::Operation::walk().
printOperationExecutions()
void NumberOfExecutions::printOperationExecutions (raw_ostream & os, Region * perEntryOfThisRegion) const
Dumps the number of operation executions each time the control flow enters the region perEntryOfThisRegion to the given stream.
Definition at line 204 of file NumberOfExecutions.cpp.
References mlir::Operation::getName(), getNumberOfExecutions(), mlir::PreOrder, and mlir::Operation::walk().
The documentation for this class was generated from the following files:
include/mlir/Analysis/NumberOfExecutions.h
lib/Analysis/NumberOfExecutions.cpp