MLIR: mlir::DataLayout Class Reference
mlir::DataLayout Class Reference
The main mechanism for performing data layout queries.
#include "mlir/Interfaces/DataLayoutInterfaces.h"
Public Member Functions
DataLayout ()
DataLayout (DataLayoutOpInterface op)
DataLayout (ModuleOp op)
llvm::TypeSize getTypeSize (Type t) const
Returns the size of the given type in the current scope.
llvm::TypeSize getTypeSizeInBits (Type t) const
Returns the size in bits of the given type in the current scope.
uint64_t getTypeABIAlignment (Type t) const
Returns the required alignment of the given type in the current scope.
uint64_t getTypePreferredAlignment (Type t) const
Returns the preferred of the given type in the current scope.
std::optional< uint64_t > getTypeIndexBitwidth (Type t) const
Returns the bitwidth that should be used when performing index computations for the given pointer-like type in the current scope.
Attribute getEndianness () const
Returns the specified endianness.
Attribute getDefaultMemorySpace () const
Returns the default memory space used for memory operations.
Attribute getAllocaMemorySpace () const
Returns the memory space used for AllocaOps.
Attribute getManglingMode () const
Returns the mangling mode.
Attribute getProgramMemorySpace () const
Returns the memory space used for program memory operations.
Attribute getGlobalMemorySpace () const
Returns the memory space used for global operations.
uint64_t getStackAlignment () const
Returns the natural alignment of the stack in bits.
Attribute getFunctionPointerAlignment () const
Returns function pointer alignment.
Attribute getLegalIntWidths () const
Returns the legal int widths.
std::optional< Attribute > getDevicePropertyValue (TargetSystemSpecInterface::DeviceID, StringAttr propertyName) const
Returns the value of the specified property if the property is defined for the given device ID, otherwise returns std::nullopt.
Static Public Member Functions
static DataLayout closest (Operation *op)
Returns the layout of the closest parent operation carrying layout info.
Detailed Description
The main mechanism for performing data layout queries.
Instances of this class can be created for an operation implementing DataLayoutOpInterface. Upon construction, a layout spec combining that of the given operation with all its ancestors will be computed and used to handle further requests. For efficiency, results to all requests will be cached in this object. Therefore, if the data layout spec for the scoping operation, or any of the enclosing operations, changes, the cache is no longer valid. The user is responsible creating a new DataLayout object after any spec change. In debug mode, the cache validity is being checked in every request.
Definition at line 220 of file DataLayoutInterfaces.h.
Constructor & Destructor Documentation
DataLayout() [1/3]
mlir::DataLayout::DataLayout () explicit
Definition at line 485 of file DataLayoutInterfaces.cpp.
References DataLayout().
Referenced by closest(), and DataLayout().
DataLayout() [2/3]
mlir::DataLayout::DataLayout (DataLayoutOpInterface op) explicit
Definition at line 487 of file DataLayoutInterfaces.cpp.
References checkMissingLayout(), collectParentLayouts(), getCombinedDataLayout(), and getTargetSystemSpec().
DataLayout() [3/3]
mlir::DataLayout::DataLayout (ModuleOp op) explicit
Definition at line 498 of file DataLayoutInterfaces.cpp.
References checkMissingLayout(), collectParentLayouts(), getCombinedDataLayout(), and getTargetSystemSpec().
Member Function Documentation
closest()
mlir::DataLayout mlir::DataLayout::closest (Operation * op) static
Returns the layout of the closest parent operation carrying layout info.
Definition at line 509 of file DataLayoutInterfaces.cpp.
References DataLayout(), and mlir::Operation::getParentOp().
Referenced by defaultIsSmallAlloc(), handleByValArgument(), memcpyEnsureOnlySafeAccesses(), mlir::linalg::promoteSubViews(), verifyAtomicMemOp(), and verifyTransferOp().
getAllocaMemorySpace()
mlir::Attribute mlir::DataLayout::getAllocaMemorySpace () const
Returns the memory space used for AllocaOps.
Definition at line 649 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultAllocaMemorySpace().
getDefaultMemorySpace()
mlir::Attribute mlir::DataLayout::getDefaultMemorySpace () const
Returns the default memory space used for memory operations.
Definition at line 633 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultMemorySpace().
getDevicePropertyValue()
std::optional< Attribute > mlir::DataLayout::getDevicePropertyValue (TargetSystemSpecInterface::DeviceID deviceID, StringAttr propertyName) const
Returns the value of the specified property if the property is defined for the given device ID, otherwise returns std::nullopt.
Definition at line 762 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDevicePropertyValue().
getEndianness()
mlir::Attribute mlir::DataLayout::getEndianness () const
Returns the specified endianness.
Definition at line 617 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultEndianness().
Referenced by isBigEndian().
getFunctionPointerAlignment()
Attribute mlir::DataLayout::getFunctionPointerAlignment () const
Returns function pointer alignment.
Definition at line 729 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultFunctionPointerAlignment().
getGlobalMemorySpace()
mlir::Attribute mlir::DataLayout::getGlobalMemorySpace () const
Returns the memory space used for global operations.
Definition at line 697 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultGlobalMemorySpace().
getLegalIntWidths()
Attribute mlir::DataLayout::getLegalIntWidths () const
Returns the legal int widths.
Definition at line 746 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultLegalIntWidths().
getManglingMode()
mlir::Attribute mlir::DataLayout::getManglingMode () const
Returns the mangling mode.
Definition at line 665 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultManglingMode().
getProgramMemorySpace()
mlir::Attribute mlir::DataLayout::getProgramMemorySpace () const
Returns the memory space used for program memory operations.
Definition at line 681 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultProgramMemorySpace().
getStackAlignment()
uint64_t mlir::DataLayout::getStackAlignment () const
Returns the natural alignment of the stack in bits.
Alignment promotion of stack variables should be limited to the natural stack alignment to prevent dynamic stack alignment. Returns zero if the stack alignment is unspecified.
Definition at line 713 of file DataLayoutInterfaces.cpp.
References mlir::detail::getDefaultStackAlignment().
Referenced by tryToEnforceAllocaAlignment().
getTypeABIAlignment()
uint64_t mlir::DataLayout::getTypeABIAlignment (Type t) const
Returns the required alignment of the given type in the current scope.
Definition at line 581 of file DataLayoutInterfaces.cpp.
References cachedLookup(), mlir::detail::getDefaultABIAlignment(), and mlir::Type::getTypeID().
Referenced by calculateStructAlignment(), gepToByteOffset(), mlir::detail::getDefaultABIAlignment(), mlir::detail::getDefaultPreferredAlignment(), getFloatTypePreferredAlignment(), getSubslotAccessInfo(), handleByValArgument(), memsetRewire(), and translateDataLayout().
getTypeIndexBitwidth()
std::optional< uint64_t > mlir::DataLayout::getTypeIndexBitwidth (Type t) const
Returns the bitwidth that should be used when performing index computations for the given pointer-like type in the current scope.
If the type is not a pointer-like type, it returns std::nullopt.
Definition at line 605 of file DataLayoutInterfaces.cpp.
References cachedLookup(), and mlir::detail::getDefaultIndexBitwidth().
Referenced by translateDataLayout().
getTypePreferredAlignment()
uint64_t mlir::DataLayout::getTypePreferredAlignment (Type t) const
Returns the preferred of the given type in the current scope.
Definition at line 593 of file DataLayoutInterfaces.cpp.
References cachedLookup(), mlir::detail::getDefaultPreferredAlignment(), and mlir::Type::getTypeID().
Referenced by mlir::detail::getDefaultPreferredAlignment(), and translateDataLayout().
getTypeSize()
llvm::TypeSize mlir::DataLayout::getTypeSize (Type t) const
Returns the size of the given type in the current scope.
Definition at line 557 of file DataLayoutInterfaces.cpp.
References cachedLookup(), mlir::detail::getDefaultTypeSize(), and mlir::Type::getTypeID().
Referenced by allocBuffer(), areConversionCompatible(), definitelyWritesOnlyWithinSlot(), gepToByteOffset(), mlir::detail::getDefaultABIAlignment(), mlir::detail::getDefaultTypeSizeInBits(), getFloatTypeABIAlignment(), getIntegerTypePreferredAlignment(), mlir::LLVMTypeConverter::getMemRefDescriptorSize(), getSubslotAccessInfo(), mlir::LLVMTypeConverter::getUnrankedMemRefDescriptorSize(), handleByValArgument(), isValidAccessType(), memcpyCanRewire(), memcpyCanUsesBeRemoved(), memsetCanUsesBeRemoved(), and memsetRewire().
getTypeSizeInBits()
llvm::TypeSize mlir::DataLayout::getTypeSizeInBits (Type t) const
Returns the size in bits of the given type in the current scope.
Definition at line 569 of file DataLayoutInterfaces.cpp.
References cachedLookup(), mlir::detail::getDefaultTypeSizeInBits(), and mlir::Type::getTypeID().
Referenced by castToSameSizedInt(), createExtractAndCast(), createInsertAndCast(), defaultIsSmallAlloc(), getArrayElementSizeInBits(), mlir::detail::getDefaultTypeSizeInBits(), getSizeInBytes(), getTypeByteSize(), mlir::LLVM::isTypeCompatibleWithAtomicOp(), mlir::LowerToLLVMOptions::LowerToLLVMOptions(), translateDataLayout(), and verifyTransferOp().
The documentation for this class was generated from the following files:
include/mlir/Interfaces/DataLayoutInterfaces.h
lib/Interfaces/DataLayoutInterfaces.cpp