MLIR: mlir::Block Class Reference
mlir::Block Class Reference
Block represents an ordered list of Operations.
#include "mlir/IR/Block.h"
Public Types
using BlockArgListType = MutableArrayRef<BlockArgument>
using args_iterator = BlockArgListType::iterator
using reverse_args_iterator = BlockArgListType::reverse_iterator
using OpListType = llvm::iplist<Operation>
This is the list of operations in the block.
using iterator = OpListType::iterator
using reverse_iterator = OpListType::reverse_iterator
template<typename OpT>
using op_iterator = detail::op_iterator<OpT, iterator>
This class provides iteration over the held operations of a block for a specific operation type.
using pred_iterator = PredecessorIterator
using succ_iterator = SuccessorRange::iterator
Public Types inherited from mlir::IRObjectWithUseList< BlockOperand >
using use_iterator
using use_range
using user_iterator
using user_range
Public Member Functions
Block ()=default
~Block ()
void clear ()
Region * getParent () const
Provide a 'getParent' method for ilist_node_with_parent methods.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this block.
bool isEntryBlock ()
Return if this block is the entry block in the parent region.
void insertBefore (Block *block)
Insert this block (which must not already be in a region) right before the specified block.
void insertAfter (Block *block)
Insert this block (which must not already be in a region) right after the specified block.
void moveBefore (Block *block)
Unlink this block from its current region and insert it right before the specific block.
void moveBefore (Region *region, llvm::iplist< Block >::iterator iterator)
Unlink this block from its current region and insert it right before the block that the given iterator points to in the region region.
void erase ()
Unlink this Block from its parent region and delete it.
BlockArgListType getArguments ()
ValueTypeRange< BlockArgListType > getArgumentTypes ()
Return a range containing the types of the arguments for this block.
args_iterator args_begin ()
args_iterator args_end ()
reverse_args_iterator args_rbegin ()
reverse_args_iterator args_rend ()
bool args_empty ()
BlockArgument addArgument (Type type, Location loc)
Add one value to the argument list.
BlockArgument insertArgument (args_iterator it, Type type, Location loc)
Insert one value to the position in the argument list indicated by the given iterator.
iterator_range< args_iterator > addArguments (TypeRange types, ArrayRef< Location > locs)
Add one argument to the argument list for each type specified in the list.
BlockArgument insertArgument (unsigned index, Type type, Location loc)
Add one value to the argument list at the specified position.
void eraseArgument (unsigned index)
Erase the argument at 'index' and remove it from the argument list.
void eraseArguments (unsigned start, unsigned num)
Erases 'num' arguments from the index 'start'.
void eraseArguments (const BitVector &eraseIndices)
Erases the arguments that have their corresponding bit set in eraseIndices and removes them from the argument list.
void eraseArguments (function_ref< bool(BlockArgument)> shouldEraseFn)
Erases arguments using the given predicate.
unsigned getNumArguments ()
BlockArgument getArgument (unsigned i)
OpListType & getOperations ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
bool empty ()
void push_back (Operation *op)
void push_front (Operation *op)
Operation & back ()
Operation & front ()
Operation * findAncestorOpInBlock (Operation &op)
Returns 'op' if 'op' lies in this block, or otherwise finds the ancestor operation of 'op' that lies in this block.
void dropAllReferences ()
This drops all operand uses from operations within this block, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
void dropAllDefinedValueUses ()
This drops all uses of values defined in this block or in the blocks of nested regions wherever the uses are located.
bool isOpOrderValid ()
Returns true if the ordering of the child operations is valid, false otherwise.
void invalidateOpOrder ()
Invalidates the current ordering of operations.
bool verifyOpOrder ()
Verifies the current ordering of child operations matches the validOpOrder flag.
void recomputeOpOrder ()
Recomputes the ordering of child operations within the block.
template<typename OpT>
iterator_range< op_iterator< OpT > > getOps ()
Return an iterator range over the operations within this block that are of 'OpT'.
template<typename OpT>
op_iterator< OpT > op_begin ()
template<typename OpT>
op_iterator< OpT > op_end ()
iterator_range< iterator > without_terminator ()
Return an iterator range over the operation within this block excluding the terminator operation at the end.
Operation * getTerminator ()
Get the terminator operation of this block.
bool mightHaveTerminator ()
Return "true" if this block might have a terminator.
pred_iterator pred_begin ()
pred_iterator pred_end ()
iterator_range< pred_iterator > getPredecessors ()
bool hasNoPredecessors ()
Return true if this block has no predecessors.
bool hasNoSuccessors ()
Returns true if this blocks has no successors.
Block * getSinglePredecessor ()
If this block has exactly one predecessor, return it.
Block * getUniquePredecessor ()
If this block has a unique predecessor, i.e., all incoming edges originate from one block, return it.
unsigned getNumSuccessors ()
Block * getSuccessor (unsigned i)
succ_iterator succ_begin ()
succ_iterator succ_end ()
SuccessorRange getSuccessors ()
bool isReachable (Block *other, SmallPtrSet< Block *, 16 > &&except={})
Return "true" if there is a path from this block to the given block (according to the successors relationship).
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename ArgT = detail::first_argument<FnT>, typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk all nested operations, blocks (including this block) or regions, depending on the type of callback.
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename RetT = detail::walkResultType<FnT>>
RetT walk (Block::iterator begin, Block::iterator end, FnT &&callback)
Walk all nested operations, blocks (excluding this block) or regions, depending on the type of callback, in the specified [begin, end) range of this block.
Block * splitBlock (iterator splitBefore)
Split the block into two blocks before the specified operation or iterator.
Block * splitBlock (Operation *splitBeforeOp)
void print (raw_ostream &os)
void print (raw_ostream &os, AsmState &state)
void dump ()
void printAsOperand (raw_ostream &os, bool printType=true)
Print out the name of the block without printing its body.
void printAsOperand (raw_ostream &os, AsmState &state)
Public Member Functions inherited from mlir::IRObjectWithUseList< BlockOperand >
~IRObjectWithUseList ()
void dropAllUses ()
Drop all uses of this object from their respective owners.
void replaceAllUsesWith (ValueT &&newValue)
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
void shuffleUseList (ArrayRef< unsigned > indices)
Shuffle the use-list chain according to the provided indices vector, which need to represent a valid shuffle.
use_iterator use_begin () const
use_iterator use_end () const
use_range getUses () const
Returns a range of all uses, which is useful for iterating over all uses.
bool hasOneUse () const
Returns true if this value has exactly one use.
bool use_empty () const
Returns true if this value has no uses.
user_iterator user_begin () const
user_iterator user_end () const
user_range getUsers () const
Returns a range of all users.
Static Public Member Functions
static OpListType Block::* getSublistAccess (Operation *)
Returns pointer to member of operation list.
Friends
struct llvm::ilist_traits< Block >
Additional Inherited Members
Protected Member Functions inherited from mlir::IRObjectWithUseList< BlockOperand >
IRObjectWithUseList ()=default
BlockOperand * getFirstUse () const
Return the first operand that is using this value, for use by custom use/def iterators.
Detailed Description
Block represents an ordered list of Operations.
Definition at line 32 of file Block.h.
Member Typedef Documentation
args_iterator
using mlir::Block::args_iterator = BlockArgListType::iterator
Definition at line 92 of file Block.h.
BlockArgListType
using mlir::Block::BlockArgListType = MutableArrayRef<BlockArgument>
Definition at line 85 of file Block.h.
iterator
using mlir::Block::iterator = OpListType::iterator
Definition at line 140 of file Block.h.
op_iterator
template<typename OpT> using mlir::Block::op_iterator = detail::op_iterator<OpT, iterator>
This class provides iteration over the held operations of a block for a specific operation type.
Definition at line 188 of file Block.h.
OpListType
using mlir::Block::OpListType = llvm::iplist<Operation>
This is the list of operations in the block.
Definition at line 136 of file Block.h.
pred_iterator
using mlir::Block::pred_iterator = PredecessorIterator
Definition at line 235 of file Block.h.
reverse_args_iterator
using mlir::Block::reverse_args_iterator = BlockArgListType::reverse_iterator
Definition at line 93 of file Block.h.
reverse_iterator
using mlir::Block::reverse_iterator = OpListType::reverse_iterator
Definition at line 141 of file Block.h.
succ_iterator
using mlir::Block::succ_iterator = SuccessorRange::iterator
Definition at line 267 of file Block.h.
Constructor & Destructor Documentation
Block()
mlir::Block::Block () explicit default
Referenced by getSinglePredecessor(), getSublistAccess(), getSuccessor(), getUniquePredecessor(), insertAfter(), insertBefore(), isReachable(), llvm::ilist_traits< Block >, moveBefore(), splitBlock(), and splitBlock().
~Block()
Block::~Block ()
Definition at line 20 of file Block.cpp.
References clear(), and verifyOpOrder().
Member Function Documentation
addArgument()
BlockArgument Block::addArgument (Type type, Location loc)
Add one value to the argument list.
Definition at line 153 of file Block.cpp.
Referenced by mlir::Region::addArgument(), addArguments(), addBlockArgumentsFromOther(), addBodyWithPayloadOp(), mlir::Region::cloneInto(), ensureDistinctSuccessors(), generateFusedElementwiseOpRegion(), MultiBlockExecuteInliner::matchAndRewrite(), and transformToReduceLoop().
addArguments()
auto Block::addArguments (TypeRange types, ArrayRef< Location > locs)
Add one argument to the argument list for each type specified in the list.
locs is required to have the same number of elements as types.
Definition at line 160 of file Block.cpp.
References addArgument().
Referenced by mlir::Region::addArguments(), buildQuantifier(), mlir::ControlFlowToSCFTransformation::createStructuredDoWhileLoopOp(), and mlir::sparse_tensor::LoopEmitter::enterCurrentCoIterationCase().
args_begin()
args_iterator mlir::Block::args_begin () inline
Definition at line 94 of file Block.h.
References getArguments().
args_empty()
bool mlir::Block::args_empty () inline
Definition at line 99 of file Block.h.
Referenced by collapseBranch(), and mlir::spirv::Deserializer::structurizeControlFlow().
args_end()
args_iterator mlir::Block::args_end () inline
Definition at line 95 of file Block.h.
References getArguments().
args_rbegin()
reverse_args_iterator mlir::Block::args_rbegin () inline
Definition at line 96 of file Block.h.
References getArguments().
args_rend()
reverse_args_iterator mlir::Block::args_rend () inline
Definition at line 97 of file Block.h.
References getArguments().
back()
Operation & mlir::Block::back () inline
Definition at line 152 of file Block.h.
Referenced by addAtomicRMW(), mlir::Region::back(), mlir::impl::GpuEliminateBarriersBase< DerivedT >::clonePass(), ensureDistinctSuccessors(), mlir::impl::ensureRegionTerminator(), mlir::sparse_tensor::LoopEmitter::exitCurrentLoop(), mlir::findReachableBlocks(), getNumSuccessors(), getTerminator(), mlir::spirv::hasOneBranchOpTo(), inlineConvertOmpRegions(), insertCopies(), mlir::linalg::isaCopyOpInterface(), isaElemwiseSingleUnaryOrBinaryOpInterface(), isaInlinedFillOp(), mlir::linalg::detail::isContractionBody(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), matchSelectReduction(), matchSimpleReduction(), mightHaveTerminator(), mlirBlockGetTerminator(), printOperation(), mlir::SuccessorRange::SuccessorRange(), verifyAndGetTerminator(), mlir::OpTrait::impl::verifyIsTerminator(), verifyRegion(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), and mlir::JamBlockGatherer< OpTy >::walk().
begin()
iterator mlir::Block::begin () inline
Definition at line 143 of file Block.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), mlir::OpTrait::SingleBlock< ConcreteType >::begin(), collapseBranch(), computeInsertPoint(), mlir::detail::constructContainerOpForParserIfNecessary(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), findHighestBlockForPlacement(), findInstPosition(), mlir::detail::DominanceInfoBase< IsPostDom >::findNearestCommonDominator(), fuseIfLegal(), generateCopy(), generateUnrolledLoop(), mlir::generateUnrolledLoop(), getMemoryFootprintBytes(), getOps(), mlir::affine::getPerfectlyNestedLoops(), getPerfectlyNestedLoopsImpl(), mlir::DataFlowSolver::getProgramPointBefore(), handleInlinedAllocas(), mlir::LLVM::lookupOrCreateFn(), matchSelectReduction(), matchSimpleReduction(), mlirBlockInsertOwnedOperationAfter(), op_begin(), mlir::affine::permuteLoops(), promoteIfBlock(), mlir::DominanceInfo::properlyDominates(), rewriteOneForallCommonImpl(), mlir::RewriterBase::splitBlock(), mlir::spirv::Deserializer::structurizeControlFlow(), walk(), walk(), mlir::JamBlockGatherer< OpTy >::walk(), and without_terminator().
clear()
void mlir::Block::clear () inline
Definition at line 38 of file Block.h.
References dropAllReferences(), and empty().
Referenced by ~Block().
dropAllDefinedValueUses()
void Block::dropAllDefinedValueUses ()
This drops all uses of values defined in this block or in the blocks of nested regions wherever the uses are located.
Definition at line 94 of file Block.cpp.
References mlir::IRObjectWithUseList< BlockOperand >::dropAllUses(), and getArguments().
dropAllReferences()
void Block::dropAllReferences ()
This drops all operand uses from operations within this block, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
Definition at line 89 of file Block.cpp.
References mlir::Operation::dropAllReferences().
Referenced by clear().
dump()
void Block::dump ()
Definition at line 4160 of file AsmPrinter.cpp.
References print().
empty()
bool mlir::Block::empty () inline
Definition at line 148 of file Block.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), clear(), mlir::spirv::Deserializer::createGraphBlock(), ensureDistinctSuccessors(), mlir::impl::ensureRegionTerminator(), mlir::sparse_tensor::LoopEmitter::exitCurrentLoop(), getNumSuccessors(), mlir::RewriterBase::inlineBlockBefore(), insertArgument(), mlir::linalg::detail::isContractionBody(), matchSelectReduction(), matchSimpleReduction(), mightHaveTerminator(), mlirBlockGetFirstOperation(), mlirBlockGetTerminator(), populateOpPayload(), setDebugIntrinsicBuilderInsertionPoint(), mlir::SuccessorRange::SuccessorRange(), verifyAndGetTerminator(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), and mlir::JamBlockGatherer< OpTy >::walk().
end()
iterator mlir::Block::end () inline
Definition at line 144 of file Block.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), collapseBranch(), mlir::OpTrait::SingleBlock< ConcreteType >::end(), generateUnrolledLoop(), mlir::generateUnrolledLoop(), getOps(), mlir::affine::getPerfectlyNestedLoops(), getPerfectlyNestedLoopsImpl(), mlir::DataFlowSolver::getProgramPointAfter(), mlir::affine::hasNoInterveningEffect(), mlir::RewriterBase::inlineBlockBefore(), matchSelectReduction(), matchSimpleReduction(), mlir::RewriterBase::mergeBlocks(), mlirRewriterBaseGetOperationAfterInsertion(), op_begin(), op_end(), mlir::affine::permuteLoops(), promoteIfBlock(), mlir::PostDominanceInfo::properlyPostDominates(), splitBlock(), transformToStructuredCFBranches(), walk(), walk(), mlir::JamBlockGatherer< OpTy >::walk(), and without_terminator().
erase()
void Block::erase ()
Unlink this Block from its parent region and delete it.
Unlink this Block from its parent Region and delete it.
Definition at line 66 of file Block.cpp.
References mlir::Region::getBlocks(), and getParent().
Referenced by outlineKernelFuncImpl(), mlir::spirv::Deserializer::structurizeControlFlow(), transformCyclesToSCFLoops(), and transformToStructuredCFBranches().
eraseArgument()
void Block::eraseArgument (unsigned index)
Erase the argument at 'index' and remove it from the argument list.
Definition at line 193 of file Block.cpp.
Referenced by dropRedundantArguments(), mlir::Region::eraseArgument(), legalizeBlockArguments(), and pruneRedundantArguments().
eraseArguments() [1/3]
void Block::eraseArguments (const BitVector & eraseIndices)
Erases the arguments that have their corresponding bit set in eraseIndices and removes them from the argument list.
Definition at line 210 of file Block.cpp.
References eraseArguments(), and mlir::BlockArgument::getArgNumber().
eraseArguments() [2/3]
void Block::eraseArguments (function_ref< bool(BlockArgument)> shouldEraseFn)
Erases arguments using the given predicate.
If the predicate returns true, that argument is erased.
Definition at line 215 of file Block.cpp.
eraseArguments() [3/3]
void Block::eraseArguments (unsigned start, unsigned num)
Erases 'num' arguments from the index 'start'.
Definition at line 201 of file Block.cpp.
Referenced by eraseArguments(), mlir::function_interface_impl::eraseFunctionArguments(), inlineIfCase(), and transformToStructuredCFBranches().
findAncestorOpInBlock()
Operation * Block::findAncestorOpInBlock (Operation & op)
Returns 'op' if 'op' lies in this block, or otherwise finds the ancestor operation of 'op' that lies in this block.
Returns nullptr if the latter fails. TODO: This is very specific functionality that should live somewhere else, probably in Dominance.cpp.
Returns nullptr if the latter fails.
Definition at line 74 of file Block.cpp.
Referenced by mlir::impl::AsyncRuntimePolicyBasedRefCountingPassBase< DerivedT >::createAsyncRuntimePolicyBasedRefCountingPass, generateCopy(), mlir::bufferization::BufferPlacementAllocs::getStartOperation(), happensBefore(), hasReadAfterWriteInterference(), neededValuesDominateInsertionPoint(), and srcAppearsBeforeDstInAncestralBlock().
front()
Operation & mlir::Block::front () inline
Definition at line 153 of file Block.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), areBinOpsSwapped(), checkTransformationPreconditions(), mlir::detail::constructContainerOpForParserIfNecessary(), mlir::lsp::MLIRServer::convertFromBytecode(), mlir::createGpuEliminateBarriers(), mlir::sparse_tensor::LoopEmitter::enterCoIterationOverTensorsAtLvls(), mlir::function_interface_impl::eraseFunctionArguments(), mlir::Region::front(), fuseIfLegal(), generateFusedElementwiseOpRegion(), getEffectsBeforeInBlock(), mlir::affine::getPerfectlyNestedLoops(), getPerfectlyNestedLoopsImpl(), mlir::RewriterBase::inlineBlockBefore(), inlineOmpRegionCleanup(), mlir::function_interface_impl::insertFunctionArguments(), mlir::OperationFolder::insertKnownConstant(), isaElemwiseSingleUnaryOrBinaryOpInterface(), mlir::spirv::isMergeBlock(), mlir::bufferization::func_ext::FuncOpInterface::isWritable(), AllocaScopeInliner::matchAndRewrite(), mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), matchSelectReduction(), matchSimpleReduction(), mlir::spirv::Deserializer::materializeSpecConstantOperation(), mlirBlockGetFirstOperation(), printOperation(), mlir::scf::replaceAndCastForOpIterArg(), rewriteOneForallCommonImpl(), setDebugIntrinsicBuilderInsertionPoint(), transformToStructuredCFBranches(), mlir::OperationFolder::tryToFold(), and mlir::dataflow::AbstractSparseForwardDataFlowAnalysis::visitCallableOperation().
getArgument()
BlockArgument mlir::Block::getArgument (unsigned i) inline
Definition at line 129 of file Block.h.
Referenced by addAtomicRMW(), mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), areBinOpsSwapped(), buildSequenceBody(), canUseShortForm(), convertForOp(), createAsyncDispatchFunction(), createBinarySearchFunc(), createElementFPowIFunc(), createElementIPowIFunc(), createPartitionFunc(), createQuickSortFunc(), createScanLoop(), createShiftDownFunc(), eraseTerminatorSuccessorOperands(), generateFusedElementwiseOpRegion(), mlir::bufferization::BranchOpBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp >::getAliasingValues(), mlir::detail::getBranchSuccessorArgument(), injectGpuIndexOperations(), inlineOmpRegionCleanup(), mlir::linalg::isaCopyOpInterface(), mlir::linalg::detail::isContractionBody(), legalizeBlockArguments(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), outlineKernelFuncImpl(), populateOpPayload(), propagateTerminatorLiveness(), pruneRedundantArguments(), mlir::detail::verifyBranchSuccessorOperands(), verifyInitLikeSingleArgRegion(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::linalg::detail::verifyStructuredOpInterface(), and mlir::transform::detail::verifyStructuredOpPredicateOpTrait().
getArguments()
BlockArgListType mlir::Block::getArguments () inline
Definition at line 87 of file Block.h.
Referenced by addBlockArgumentsFromOther(), addBodyWithPayloadOp(), mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), args_begin(), args_end(), args_rbegin(), args_rend(), mlir::bufferization::bufferizeBlockSignature(), buildGenericRegion(), buildQuantifier(), buildSequenceBody(), canUseShortForm(), mlir::Region::cloneInto(), mlir::impl::AsyncRuntimeRefCountingPassBase< DerivedT >::clonePass(), collapseBranch(), createAsyncDispatchFunction(), createBinarySearchFunc(), mlir::emitc::createExpression(), createHeapSortFunc(), createPartitionFunc(), createQuickSortFunc(), createShiftDownFunc(), createSingleExitBranchRegion(), createSingleExitingLatch(), createSortStableFunc(), mlir::ControlFlowToSCFTransformation::createStructuredDoWhileLoopOp(), dropAllDefinedValueUses(), dropRedundantArguments(), ensureDistinctSuccessors(), fuseIfLegal(), mlir::sparse_tensor::FuncCallOrInlineGenerator< SubClass >::genCallOrInline(), genCoIterateBranchNest(), mlir::sparse_tensor::genCoIteration(), generateFusedElementwiseOpRegion(), genLoopWithIterator(), mlir::Region::getArguments(), getArgumentTypes(), mlir::RewriterBase::inlineBlockBefore(), inlineIfCase(), inlinePayload(), inlineWhileCase(), mlir::OperationEquivalence::isRegionEquivalentTo(), mlir::makeRegionIsolatedFromAbove(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), matchBlock(), matchSelectReduction(), matchSimpleReduction(), mergeIdenticalBlocks(), mlir::outlineSingleBlockRegion(), mlir::shard::partitionBlock(), printLoopControl(), printOperation(), printOperation(), pruneRedundantArguments(), remapArgumentEffects(), mlir::scf::replaceAndCastForOpIterArg(), rewrite(), mlir::shard::shardedBlockArgumentTypes(), transformCyclesToSCFLoops(), transformToReduceLoop(), transformToStructuredCFBranches(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), and walkReferenceCountedValues().
getArgumentTypes()
auto Block::getArgumentTypes ()
Return a range containing the types of the arguments for this block.
Definition at line 149 of file Block.cpp.
References getArguments().
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), mlir::makeRegionIsolatedFromAbove(), and transformToStructuredCFBranches().
getNumArguments()
unsigned mlir::Block::getNumArguments () inline
Definition at line 128 of file Block.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), canUseShortForm(), createSingleExitingLatch(), ensureDistinctSuccessors(), generateFusedElementwiseOpRegion(), mlir::RewriterBase::inlineBlockBefore(), inlineIfCase(), mlir::linalg::detail::isContractionBody(), mlir::OperationEquivalence::isRegionEquivalentTo(), legalizeBlockArguments(), mlir::makeRegionIsolatedFromAbove(), mapInitializationArgs(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), matchSimpleReduction(), mlir::outlineSingleBlockRegion(), populateOpPayload(), transformToReduceLoop(), transformToStructuredCFBranches(), mlir::detail::verifyBranchSuccessorOperands(), verifyInitLikeSingleArgRegion(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::linalg::detail::verifyStructuredOpInterface(), and mlir::transform::detail::verifyStructuredOpPredicateOpTrait().
getNumSuccessors()
unsigned Block::getNumSuccessors ()
Definition at line 265 of file Block.cpp.
References back(), empty(), and mlir::Operation::getNumSuccessors().
Referenced by createSingleExitBlocksForReturnLike(), getSuccessor(), mlir::isLegalForBranchOpInterfaceTypeConversionPattern(), isRegionExitBlock(), successorEdges(), and transformToStructuredCFBranches().
getOperations()
OpListType & mlir::Block::getOperations () inline
Definition at line 137 of file Block.h.
Referenced by mlir::affine::affineParallelize(), mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), canUseShortForm(), mlir::detail::constructContainerOpForParserIfNecessary(), constructTiledLoopNest(), getPhiIncomingBlock(), hoistAffineIfOp(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::initialize(), mlir::RewriterBase::inlineBlockBefore(), mlir::OpTrait::SingleBlock< ConcreteType >::insert(), mlir::linalg::isaCopyOpInterface(), isaElemwiseSingleUnaryOrBinaryOpInterface(), isaInlinedFillOp(), mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), mlirBlockInsertOwnedOperationAfter(), outlineKernelFuncImpl(), mlir::shard::partitionBlock(), mlir::affine::permuteLoops(), processParallelLoop(), promoteIfBlock(), rewriteOneForallCommonImpl(), ShardingPropagation::runOnOperation(), setupCoroMachinery(), splitBlock(), transformCyclesToSCFLoops(), transformToStructuredCFBranches(), and vectorizeAsLinalgGeneric().
getOps()
template<typename OpT> iterator_range< op_iterator< OpT > > mlir::Block::getOps () inline
Return an iterator range over the operations within this block that are of 'OpT'.
Definition at line 193 of file Block.h.
References begin(), and end().
Referenced by generateFusedElementwiseOpRegion(), handleInlinedAllocas(), and updateExpandedGenericOpRegion().
getParent()
Region * Block::getParent () const
Provide a 'getParent' method for ilist_node_with_parent methods.
We mark it as a const function because ilist_node_with_parent specifically requires a 'getParent() const' method. Once ilist_node removes this constraint, we should drop the const to fit the rest of the MLIR const model.
Definition at line 27 of file Block.cpp.
Referenced by llvm::ilist_traits<::mlir::Block >::addNodeToList(), mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), mlir::OpBuilder::cloneRegionBefore(), collectUnderlyingAddressValues(), mlir::OpBuilder::createBlock(), createElementFPowIFunc(), createElementIPowIFunc(), mlir::createGpuEliminateBarriers(), diagnoseInvalidOperandDominance(), ensureDistinctSuccessors(), erase(), mlir::detail::ConversionPatternRewriterImpl::eraseBlock(), mlir::Region::findAncestorBlockInRegion(), mlir::detail::DominanceInfoBase< IsPostDom >::findNearestCommonDominator(), genCoIterateBranchNest(), generateCopy(), getBlockNumber(), getEffectsBefore(), getInsertionRegion(), mlir::dataflow::CFGEdge::getLoc(), mlir::LatticeAnchor::getLoc(), mlir::detail::DominanceInfoBase< IsPostDom >::getNode(), getParentOp(), mlir::detail::DominanceInfoBase< IsPostDom >::hasSSADominance(), mlir::ReductionNode::initialize(), mlir::RewriterBase::inlineRegionBefore(), insertAfter(), insertBefore(), isEntryBlock(), isReachable(), matchBlock(), mayBeValidWithoutTerminator(), moveBefore(), moveBefore(), mlir::RewriterBase::moveBlockBefore(), mlir::shard::partitionBlock(), printBlock(), llvm::ilist_traits<::mlir::Block >::removeNodeFromList(), splitBlock(), mlir::SuccessorRange::SuccessorRange(), mlir::transformCFGToSCF(), transformCyclesToSCFLoops(), transformToReduceLoop(), transformToStructuredCFBranches(), tryGetBlocksInSameRegion(), and mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visitRegionBranchOperation().
getParentOp()
Operation * Block::getParentOp ()
Returns the closest surrounding operation that contains this block.
Returns the closest surrounding operation that contains this block or nullptr if this block is unlinked.
Definition at line 31 of file Block.cpp.
References getParent(), and mlir::Region::getParentOp().
Referenced by mlir::bufferization::bufferizeBlockSignature(), buildPackingLoopNestImpl(), checkAndNestUnderRewriteOp(), diagnoseInvalidOperandDominance(), emitRemarkForBlock(), mlir::detail::ConversionPatternRewriterImpl::eraseBlock(), finalizeWhileOp(), mlir::Region::findAncestorBlockInRegion(), findInstPosition(), forwardEmptyOperands(), mlir::transform::detail::forwardTerminatorOperands(), mlir::bufferization::OpWithUnstructuredControlFlowBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp >::getAliasingBranchOpOperands(), getAncestorBlock(), getBackwardSliceImpl(), getCommonBlockInAffineScope(), mlir::getControlFlowPredecessors(), getParentsOfType(), getPhiIncomingBlock(), hoistSubsetAtIterArg(), isFnEntryBlock(), mayBeValidWithoutTerminator(), mlir::detail::ConversionPatternRewriterImpl::notifyBlockInserted(), print(), printAsOperand(), mlir::spirv::Serializer::printValueIDMap(), removeBufferizationAttributes(), sameOrEquivalentIterArg(), transformToReduceLoop(), tryToEnforceAlignment(), vectorizeAffineYieldOp(), and mlir::spirv::Deserializer::wireUpBlockArgument().
getPredecessors()
iterator_range< pred_iterator > mlir::Block::getPredecessors () inline
Definition at line 240 of file Block.h.
References pred_begin(), and pred_end().
Referenced by insertArgument(), simplifyBrToBlockWithSinglePred(), and transformToReduceLoop().
getSinglePredecessor()
Block * Block::getSinglePredecessor ()
If this block has exactly one predecessor, return it.
Otherwise, return null.
Note that if a block has duplicate predecessors from a single block (e.g. if you have a conditional branch with the same block as the true/false destinations) is not considered to be a single predecessor.
Otherwise, return null.
Note that multiple edges from a single block (e.g. if you have a cond branch with the same block as the true/false destinations) is not considered to be a single predecessor.
Definition at line 280 of file Block.cpp.
References Block(), pred_begin(), and pred_end().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition(), simplifySwitchFromSwitchOnSameCondition(), and transformToReduceLoop().
getSublistAccess()
OpListType Block::* mlir::Block::getSublistAccess (Operation *) inline static
Returns pointer to member of operation list.
Definition at line 393 of file Block.h.
References Block().
getSuccessor()
Block * Block::getSuccessor (unsigned i)
Definition at line 269 of file Block.cpp.
References Block(), getNumSuccessors(), mlir::Operation::getSuccessor(), and getTerminator().
Referenced by ensureDistinctSuccessors(), printOperation(), transformToReduceLoop(), and transformToStructuredCFBranches().
getSuccessors()
SuccessorRange mlir::Block::getSuccessors () inline
Definition at line 270 of file Block.h.
Referenced by calculateCycleEdges(), findCapturedOmpOp(), mlir::affine::hasNoInterveningEffect(), mergeIdenticalBlocks(), mlir::Liveness::resolveLiveness(), succ_begin(), succ_end(), and transformToStructuredCFBranches().
getTerminator()
Operation * Block::getTerminator ()
Get the terminator operation of this block.
This function asserts that the block might have a valid terminator operation.
Definition at line 244 of file Block.cpp.
References back(), and mightHaveTerminator().
Referenced by mlir::sparse_tensor::Merger::buildLattices(), mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), canUseShortForm(), mlir::arm_sme::impl::TestTileAllocationBase< DerivedT >::clonePass(), collapseBranch(), containsReturn(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), createSingleExitBlocksForReturnLike(), ensureDistinctSuccessors(), mlir::transform::detail::forwardTerminatorOperands(), fuseIfLegal(), generateFusedElementwiseOpRegion(), generateUnrolledLoop(), mlir::generateUnrolledLoop(), getBlockPredecessorOperands(), getMutableSuccessorOperands(), getPHISourceValue(), mlir::bufferization::BufferPlacementAllocs::getStartOperation(), getSuccessor(), mlir::affine::hasNoInterveningEffect(), inlineIfCase(), inlinePayload(), inlineWhileCase(), mlir::sparse_tensor::insertYieldOp(), mlir::sparse_tensor::isAdmissibleBranch(), mlir::linalg::detail::isContractionBody(), isRegionOrCallableReturn(), lastNonTerminatorInRegion(), AllocaScopeInliner::matchAndRewrite(), ExecuteRegionForwardingEliminator::matchAndRewrite(), FoldConstantCase::matchAndRewrite(), matchBlock(), mlir::linalg::ConvMatcherBuilder::matchBody(), outlineExecuteOp(), outlineKernelFuncImpl(), mlir::outlineSingleBlockRegion(), populateOpPayload(), processParallelLoop(), mlir::scf::replaceAndCastForOpIterArg(), replaceOpWithRegion(), setDebugIntrinsicBuilderInsertionPoint(), simplifySwitchFromDefaultSwitchOnSameCondition(), simplifySwitchFromSwitchOnSameCondition(), tileAndFuseConsumerOfSlicesImpl(), transformCyclesToSCFLoops(), transformToStructuredCFBranches(), verifyNumBlockArgs(), verifyQuantifierRegions(), and mlir::spirv::Deserializer::wireUpBlockArgument().
getUniquePredecessor()
Block * Block::getUniquePredecessor ()
If this block has a unique predecessor, i.e., all incoming edges originate from one block, return it.
Otherwise, return null.
Definition at line 291 of file Block.cpp.
References Block(), pred_begin(), and pred_end().
hasNoPredecessors()
bool mlir::Block::hasNoPredecessors () inline
Return true if this block has no predecessors.
Definition at line 245 of file Block.h.
References pred_begin(), and pred_end().
Referenced by checkTransformationPreconditions(), and mlir::RewriterBase::inlineBlockBefore().
hasNoSuccessors()
bool mlir::Block::hasNoSuccessors () inline
Returns true if this blocks has no successors.
Definition at line 248 of file Block.h.
References succ_begin(), and succ_end().
Referenced by mlir::RewriterBase::inlineBlockBefore().
insertAfter()
void Block::insertAfter (Block * block)
Insert this block (which must not already be in a region) right after the specified block.
Definition at line 46 of file Block.cpp.
References Block(), mlir::Region::getBlocks(), and getParent().
Referenced by createSingleExitingLatch().
insertArgument() [1/2]
BlockArgument Block::insertArgument (args_iterator it, Type type, Location loc)
Insert one value to the position in the argument list indicated by the given iterator.
Insert one value to the given position of the argument list.
The existing arguments are shifted. The block is expected not to have predecessors.
Definition at line 187 of file Block.cpp.
References empty(), getPredecessors(), and insertArgument().
Referenced by insertArgument(), mlir::Region::insertArgument(), mlir::Region::insertArgument(), mlir::function_interface_impl::insertFunctionArguments(), and legalizeBlockArguments().
insertArgument() [2/2]
BlockArgument Block::insertArgument (unsigned index, Type type, Location loc)
Add one value to the argument list at the specified position.
Definition at line 172 of file Block.cpp.
insertBefore()
void Block::insertBefore (Block * block)
Insert this block (which must not already be in a region) right before the specified block.
Definition at line 40 of file Block.cpp.
References Block(), mlir::Region::getBlocks(), and getParent().
Referenced by transformCyclesToSCFLoops().
invalidateOpOrder()
void Block::invalidateOpOrder ()
Invalidates the current ordering of operations.
Definition at line 107 of file Block.cpp.
References verifyOpOrder().
Referenced by llvm::ilist_traits<::mlir::Operation >::transferNodesFromList().
isEntryBlock()
bool Block::isEntryBlock ()
Return if this block is the entry block in the parent region.
Definition at line 36 of file Block.cpp.
References mlir::Region::front(), and getParent().
Referenced by checkTransformationPreconditions(), collectUnderlyingAddressValues(), mlir::bufferization::createBufferLoopHoistingPass(), mlir::getControlFlowPredecessors(), getPhiIncomingBlock(), and isFnEntryBlock().
isOpOrderValid()
bool Block::isOpOrderValid ()
Returns true if the ordering of the child operations is valid, false otherwise.
Definition at line 104 of file Block.cpp.
Referenced by verifyOpOrder().
isReachable()
bool Block::isReachable (Block * other, SmallPtrSet< Block *, 16 > && except = {})
Return "true" if there is a path from this block to the given block (according to the successors relationship).
Both blocks must be in the same region. Paths that contain a block from except do not count. This function returns "false" if other is in except.
Note: This function performs a block graph traversal and its complexity linear in the number of blocks in the parent region.
Note: Reachability is a necessary but insufficient condition for dominance. Do not use this function in places where you need to check for dominance.
Definition at line 363 of file Block.cpp.
References Block(), getParent(), succ_begin(), and succ_end().
Referenced by canUseOpDominanceDueToBlocks().
mightHaveTerminator()
bool Block::mightHaveTerminator ()
Return "true" if this block might have a terminator.
Check whether this block might have a terminator.
Return "true" if the last operation is unregistered.
Definition at line 250 of file Block.cpp.
References back(), empty(), and mlir::Operation::mightHaveTrait().
Referenced by getTerminator(), and lastNonTerminatorInRegion().
moveBefore() [1/2]
void Block::moveBefore (Block * block)
Unlink this block from its current region and insert it right before the specific block.
Definition at line 54 of file Block.cpp.
References Block(), getParent(), and moveBefore().
Referenced by moveBefore().
moveBefore() [2/2]
void Block::moveBefore (Region * region, llvm::iplist< Block >::iterator iterator)
Unlink this block from its current region and insert it right before the block that the given iterator points to in the region region.
Definition at line 61 of file Block.cpp.
References mlir::Region::getBlocks(), and getParent().
op_begin()
template<typename OpT> op_iterator< OpT > mlir::Block::op_begin () inline
Definition at line 199 of file Block.h.
References begin(), and end().
op_end()
template<typename OpT> op_iterator< OpT > mlir::Block::op_end () inline
Definition at line 203 of file Block.h.
References end().
pred_begin()
pred_iterator mlir::Block::pred_begin () inline
Definition at line 236 of file Block.h.
References mlir::IRObjectWithUseList< BlockOperand >::getFirstUse().
Referenced by ableToUpdatePredOperands(), buildBlockMapping(), calculateCycleEdges(), llvm::GraphTraits< Inverse< mlir::Block * > >::child_begin(), collectUnderlyingAddressValues(), dropRedundantArguments(), getBlockPredecessorOperands(), getPredecessors(), getSinglePredecessor(), getUniquePredecessor(), hasNoPredecessors(), transformToReduceLoop(), and transformToStructuredCFBranches().
pred_end()
pred_iterator mlir::Block::pred_end () inline
Definition at line 239 of file Block.h.
Referenced by ableToUpdatePredOperands(), buildBlockMapping(), calculateCycleEdges(), llvm::GraphTraits< Inverse< mlir::Block * > >::child_end(), collectUnderlyingAddressValues(), dropRedundantArguments(), getBlockPredecessorOperands(), getPredecessors(), getSinglePredecessor(), getUniquePredecessor(), hasNoPredecessors(), transformToReduceLoop(), and transformToStructuredCFBranches().
print() [1/2]
void Block::print (raw_ostream & os)
Definition at line 4143 of file AsmPrinter.cpp.
References getParentOp(), mlir::Operation::getParentOp(), and print().
Referenced by mlir::operator<<(), mlir::dataflow::CFGEdge::print(), printBlock(), and mlir::spirv::Deserializer::structurizeControlFlow().
print() [2/2]
void Block::print (raw_ostream & os, AsmState & state)
Definition at line 4156 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl().
printAsOperand() [1/2]
void Block::printAsOperand (raw_ostream & os, AsmState & state)
Definition at line 4172 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl().
printAsOperand() [2/2]
void Block::printAsOperand (raw_ostream & os, bool printType = true)
Print out the name of the block without printing its body.
NOTE: The printType argument is ignored. We keep it for compatibility with LLVM dominator machinery that expects it to exist.
Definition at line 4163 of file AsmPrinter.cpp.
References getParentOp(), and printAsOperand().
Referenced by printAsOperand().
push_back()
void mlir::Block::push_back (Operation * op) inline
Definition at line 149 of file Block.h.
Referenced by mlir::Region::cloneInto().
push_front()
void mlir::Block::push_front (Operation * op) inline
Definition at line 150 of file Block.h.
rbegin()
reverse_iterator mlir::Block::rbegin () inline
Definition at line 145 of file Block.h.
recomputeOpOrder()
void Block::recomputeOpOrder ()
Recomputes the ordering of child operations within the block.
Definition at line 136 of file Block.cpp.
rend()
reverse_iterator mlir::Block::rend () inline
Definition at line 146 of file Block.h.
splitBlock() [1/2]
Block * Block::splitBlock (iterator splitBefore)
Split the block into two blocks before the specified operation or iterator.
Note that all operations BEFORE the specified iterator stay as part of the original basic block, and the rest of the operations in the original block are moved to the new block, including the old terminator. The original block is left without a terminator.
The newly formed Block is returned, and the specified iterator is invalidated.
Definition at line 318 of file Block.cpp.
References Block(), end(), mlir::Region::getBlocks(), getOperations(), and getParent().
Referenced by mlir::spirv::Deserializer::materializeSpecConstantOperation(), setupCoroMachinery(), splitBlock(), mlir::RewriterBase::splitBlock(), and mlir::spirv::Deserializer::splitSelectionHeader().
splitBlock() [2/2]
Block * mlir::Block::splitBlock (Operation * splitBeforeOp) inline
Definition at line 388 of file Block.h.
References Block(), and splitBlock().
succ_begin()
succ_iterator mlir::Block::succ_begin () inline
Definition at line 268 of file Block.h.
References getSuccessors().
Referenced by llvm::GraphTraits< mlir::Block * >::child_begin(), hasNoSuccessors(), and isReachable().
succ_end()
succ_iterator mlir::Block::succ_end () inline
Definition at line 269 of file Block.h.
References getSuccessors().
Referenced by llvm::GraphTraits< mlir::Block * >::child_end(), hasNoSuccessors(), and isReachable().
verifyOpOrder()
bool Block::verifyOpOrder ()
Verifies the current ordering of child operations matches the validOpOrder flag.
Verifies the current ordering of child operations.
Returns false if the order is valid, true otherwise.
Definition at line 115 of file Block.cpp.
References isOpOrderValid().
Referenced by invalidateOpOrder(), and ~Block().
walk() [1/2]
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename RetT = detail::walkResultType<FnT>> RetT mlir::Block::walk (Block::iterator begin, Block::iterator end, FnT && callback) inline
Walk all nested operations, blocks (excluding this block) or regions, depending on the type of callback, in the specified [begin, end) range of this block.
The order in which operations, blocks or regions at the same nesting level are visited (e.g., lexicographical or reverse lexicographical order) is determined by Iterator. The walk order for enclosing operations, blocks or regions with respect to their nested ones is specified by Order (post-order by default).
A callback on a operation or block is allowed to erase that operation or block if either:
the walk is in post-order, or
the walk is in pre-order and the walk is skipped after the erasure.
See Operation::walk for more details.
Definition at line 360 of file Block.h.
References mlir::WalkResult::advance(), begin(), end(), mlir::WalkResult::interrupt(), and mlir::detail::walk().
walk() [2/2]
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename ArgT = detail::first_argument<FnT>, typename RetT = detail::walkResultType<FnT>> RetT mlir::Block::walk (FnT && callback) inline
Walk all nested operations, blocks (including this block) or regions, depending on the type of callback.
The order in which operations, blocks or regions at the same nesting level are visited (e.g., lexicographical or reverse lexicographical order) is determined by Iterator. The walk order for enclosing operations, blocks or regions with respect to their nested ones is specified by Order (post-order by default).
A callback on a operation or block is allowed to erase that operation or block if either:
the walk is in post-order, or
the walk is in pre-order and the walk is skipped after the erasure.
See Operation::walk for more details.
Definition at line 308 of file Block.h.
References mlir::WalkResult::advance(), begin(), end(), mlir::WalkResult::interrupt(), mlir::PostOrder, mlir::PreOrder, result, and walk().
Referenced by emit(), mlir::detail::ConversionPatternRewriterImpl::eraseBlock(), getMemoryFootprintBytes(), getSingleOpOfType(), and walk().
without_terminator()
iterator_range< iterator > mlir::Block::without_terminator () inline
Return an iterator range over the operation within this block excluding the terminator operation at the end.
If the block has no terminator, return an iterator range over the entire block. If it is unknown if the block has a terminator (i.e., last block operation is unregistered), also return an iterator range over the entire block.
Definition at line 212 of file Block.h.
References begin(), and end().
Referenced by applySequenceBlock(), generateFusedElementwiseOpRegion(), inlinePayload(), mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), matchBlock(), processParallelLoop(), and mlir::sortTopologically().
Friends And Related Symbol Documentation
llvm::ilist_traits< Block >
friend struct llvm::ilist_traits< Block > friend
Definition at line 422 of file Block.h.
References Block().
The documentation for this class was generated from the following files:
include/mlir/IR/Block.h
lib/IR/AsmPrinter.cpp
lib/IR/Block.cpp