MLIR: mlir::LocationAttr Class Reference
mlir::LocationAttr Class Reference
Location objects represent source locations information in MLIR.
#include "mlir/IR/Location.h"
Public Member Functions
WalkResult walk (function_ref< WalkResult(Location)> walkFn)
Walk all of the locations nested directly under, and including, the current.
template<typename T>
T findInstanceOf ()
Return an instance of the given location type if one is nested under the current location.
template<typename T, typename UnknownT = UnknownLoc>
LocationAttr findInstanceOfOrUnknown ()
Return an instance of the given location type if one is nested under the current location else return unknown location.
constexpr Attribute ()=default
Attribute (const ImplType *impl)
Attribute (const Attribute &other)=default
Public Member Functions inherited from mlir::Attribute
constexpr Attribute ()=default
Attribute (const ImplType *impl)
Attribute (const Attribute &other)=default
Attribute & operator= (const Attribute &other)=default
bool operator== (Attribute other) const
bool operator!= (Attribute other) const
operator bool () const
bool operator! () const
TypeID getTypeID ()
Return a unique identifier for the concrete attribute type.
MLIRContext * getContext () const
Return the context this attribute belongs to.
Dialect & getDialect () const
Get the dialect this attribute is registered to.
void print (raw_ostream &os, bool elideType=false) const
Print the attribute.
void print (raw_ostream &os, AsmState &state, bool elideType=false) const
void dump () const
void printStripped (raw_ostream &os) const
Print the attribute without dialect wrapping.
void printStripped (raw_ostream &os, AsmState &state) const
const void * getAsOpaquePointer () const
Get an opaque pointer to the attribute.
friend::llvm::hash_code hash_value (Attribute arg)
template<typename InterfaceT>
bool hasPromiseOrImplementsInterface ()
Returns true if InterfaceT has been promised by the dialect or implemented.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the type was registered with a particular trait.
const AbstractTy & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
void walkImmediateSubElements (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn) const
Walk all of the immediately nested sub-attributes and sub-types.
auto replaceImmediateSubElements (ArrayRef< Attribute > replAttrs, ArrayRef< Type > replTypes) const
Replace the immediately nested sub-attributes and sub-types with those provided.
template<WalkOrder Order = WalkOrder::PostOrder, typename... WalkFns>
auto walk (WalkFns &&...walkFns)
Walk this attribute and all attibutes/types nested within using the provided walk functions.
template<typename... ReplacementFns>
auto replace (ReplacementFns &&...replacementFns)
Recursively replace all of the nested sub-attributes and sub-types using the provided map functions.
ImplType * getImpl () const
Return the internal Attribute implementation.
Static Public Member Functions
static bool classof (Attribute attr)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::Attribute
static Attribute getFromOpaquePointer (const void *ptr)
Construct an attribute from the opaque pointer representation.
Additional Inherited Members
Public Types inherited from mlir::Attribute
template<typename ConcreteType, typename BaseType, typename StorageType, template< typename T > class... Traits>
using AttrBase
Utility class for implementing attributes.
using ImplType = AttributeStorage
using ValueType = void
using AbstractTy = AbstractAttribute
Protected Attributes inherited from mlir::Attribute
ImplType * impl {nullptr}
Detailed Description
Location objects represent source locations information in MLIR.
LocationAttr acts as the anchor for all Location based attributes.
Definition at line 32 of file Location.h.
Member Function Documentation
Attribute() [1/3]
mlir::Attribute::Attribute () constexpr default
Referenced by classof(), and walk().
Attribute() [2/3]
mlir::Attribute::Attribute (const Attribute & other) default
Attribute() [3/3]
mlir::Attribute::Attribute (const ImplType * impl) inline
Definition at line 38 of file Attributes.h.
classof()
bool LocationAttr::classof (Attribute attr) static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 137 of file Location.cpp.
References Attribute(), and mlir::Attribute::hasTrait().
findInstanceOf()
template<typename T> T mlir::LocationAttr::findInstanceOf () inline
Return an instance of the given location type if one is nested under the current location.
Returns nullptr if one could not be found.
Definition at line 45 of file Location.h.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), result, and walk().
Referenced by convertDeclareTargetAttr(), mlir::SourceMgrDiagnosticHandler::emitDiagnostic(), findInstanceOfOrUnknown(), and getLocalScopeFromLoc().
findInstanceOfOrUnknown()
template<typename T, typename UnknownT = UnknownLoc> LocationAttr mlir::LocationAttr::findInstanceOfOrUnknown () inline
Return an instance of the given location type if one is nested under the current location else return unknown location.
Definition at line 60 of file Location.h.
References findInstanceOf(), mlir::Attribute::getContext(), and result.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::appendOrGetFuncOp(), and mlir::GPUPrintfOpToVPrintfLowering::matchAndRewrite().
walk()
WalkResult LocationAttr::walk (function_ref< WalkResult(Location)> walkFn)
Walk all of the locations nested directly under, and including, the current.
This means that if a location is nested under a non-location attribute, it will not be walked by this method. This walk is performed in pre-order to get this behavior.
Definition at line 124 of file Location.cpp.
References mlir::AttrTypeWalker::addWalk(), Attribute(), mlir::PreOrder, mlir::WalkResult::skip(), and mlir::AttrTypeWalker::walk().
Referenced by collectLocationsFromLoc(), findInstanceOf(), and getLocationFromLoc().
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/Location.cpp