MLIR: mlir::DialectResourceBlobManager::BlobEntry Class Reference
mlir::DialectResourceBlobManager::BlobEntry Class Reference
The class represents an individual entry of a blob.
#include "mlir/IR/DialectResourceBlobManager.h"
Public Member Functions
StringRef getKey () const
Return the key used to reference this blob.
const AsmResourceBlob * getBlob () const
Return the blob owned by this entry if one has been initialized.
AsmResourceBlob * getBlob ()
void setBlob (AsmResourceBlob &&newBlob)
Set the blob owned by this entry.
Friends
class llvm::StringMapEntryStorage< BlobEntry >
Detailed Description
The class represents an individual entry of a blob.
Definition at line 36 of file DialectResourceBlobManager.h.
Member Function Documentation
getBlob() [1/2]
AsmResourceBlob* mlir::DialectResourceBlobManager::BlobEntry::getBlob () inline
Definition at line 44 of file DialectResourceBlobManager.h.
getBlob() [2/2]
const AsmResourceBlob* mlir::DialectResourceBlobManager::BlobEntry::getBlob () const inline
Return the blob owned by this entry if one has been initialized.
Returns nullptr otherwise.
Definition at line 43 of file DialectResourceBlobManager.h.
Referenced by mlir::DialectResourceBlobHandle< DialectT >::getBlob().
getKey()
StringRef mlir::DialectResourceBlobManager::BlobEntry::getKey () const inline
Return the key used to reference this blob.
Definition at line 39 of file DialectResourceBlobManager.h.
Referenced by mlir::DialectResourceBlobHandle< DialectT >::getKey().
setBlob()
void mlir::DialectResourceBlobManager::BlobEntry::setBlob (AsmResourceBlob && newBlob) inline
Set the blob owned by this entry.
Definition at line 47 of file DialectResourceBlobManager.h.
Referenced by mlir::DialectResourceBlobManager::update().
Friends And Related Function Documentation
llvm::StringMapEntryStorage< BlobEntry >
friend class llvm::StringMapEntryStorage< BlobEntry > friend
Definition at line 68 of file DialectResourceBlobManager.h.
The documentation for this class was generated from the following file:
include/mlir/IR/DialectResourceBlobManager.h