MLIR: mlir::python::PyLocation Class Reference
mlir::python::PyLocation Class Reference
Wrapper around an MlirLocation.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyLocation (PyMlirContextRef contextRef, MlirLocation loc)
operator MlirLocation () const
MlirLocation get () const
pybind11::object contextEnter ()
Enter and exit the context manager.
void contextExit (pybind11::object excType, pybind11::object excVal, pybind11::object excTb)
pybind11::object getCapsule ()
Gets a capsule wrapping the void* within the MlirLocation.
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyLocation createFromCapsule (pybind11::object capsule)
Creates a PyLocation from the MlirLocation wrapped by a capsule.
Detailed Description
Wrapper around an MlirLocation.
Definition at line 308 of file IRModule.h.
Constructor & Destructor Documentation
PyLocation()
mlir::python::PyLocation::PyLocation (PyMlirContextRef contextRef, MlirLocation loc) inline
Definition at line 310 of file IRModule.h.
Member Function Documentation
contextEnter()
py::object PyLocation::contextEnter ()
Enter and exit the context manager.
Definition at line 674 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::pushLocation().
Referenced by mlir::python::PyValue::createFromCapsule().
contextExit()
void PyLocation::contextExit (pybind11::object excType, pybind11::object excVal, pybind11::object excTb)
Definition at line 678 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::popLocation().
Referenced by mlir::python::PyValue::createFromCapsule().
createFromCapsule()
PyLocation PyLocation::createFromCapsule (pybind11::object capsule) static
Creates a PyLocation from the MlirLocation wrapped by a capsule.
Note that PyLocation instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirLocation is taken by calling this function.
Definition at line 666 of file IRCore.cpp.
References mlir::python::PyMlirContext::forContext(), mlirLocationGetContext(), mlirLocationIsNull(), and mlirPythonCapsuleToLocation().
Referenced by mlir::python::PyValue::createFromCapsule().
get()
MlirLocation mlir::python::PyLocation::get () const inline
Definition at line 314 of file IRModule.h.
References loc.
getCapsule()
py::object PyLocation::getCapsule ()
Gets a capsule wrapping the void* within the MlirLocation.
Definition at line 662 of file IRCore.cpp.
References mlirPythonLocationToCapsule().
Referenced by mlir::python::PyValue::createFromCapsule().
operator MlirLocation()
mlir::python::PyLocation::operator MlirLocation () const inline
Definition at line 313 of file IRModule.h.
References loc.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp