MLIR: mlir::tblgen::OpMethodParameters Class Reference
mlir::tblgen::OpMethodParameters Class Reference abstract
#include "mlir/TableGen/OpClass.h"
Public Types
enum ParamsKind { PK_Unresolved, PK_Resolved }
Public Member Functions
OpMethodParameters (ParamsKind kind)
virtual ~OpMethodParameters ()
ParamsKind getKind () const
virtual void writeDeclTo (raw_ostream &os) const =0
virtual void writeDefTo (raw_ostream &os) const =0
Static Public Member Functions
static std::unique_ptr< OpMethodParameters > create ()
static std::unique_ptr< OpMethodParameters > create (StringRef params)
static std::unique_ptr< OpMethodParameters > create (llvm::SmallVectorImpl< OpMethodParameter > &&params)
static std::unique_ptr< OpMethodParameters > create (StringRef type, StringRef name, StringRef defaultValue="")
Detailed Description
Definition at line 76 of file OpClass.h.
Member Enumeration Documentation
ParamsKind
enum mlir::tblgen::OpMethodParameters::ParamsKind
Enumerator
PK_Unresolved
PK_Resolved
Definition at line 79 of file OpClass.h.
Constructor & Destructor Documentation
OpMethodParameters()
mlir::tblgen::OpMethodParameters::OpMethodParameters (ParamsKind kind) inline
Definition at line 86 of file OpClass.h.
~OpMethodParameters()
virtual mlir::tblgen::OpMethodParameters::~OpMethodParameters () inline virtual
Definition at line 87 of file OpClass.h.
Member Function Documentation
create() [1/4]
std::unique_ptr< OpMethodParameters > OpMethodParameters::create () static
Definition at line 51 of file OpClass.cpp.
create() [2/4]
std::unique_ptr< OpMethodParameters > OpMethodParameters::create (StringRef params) static
Definition at line 56 of file OpClass.cpp.
create() [3/4]
std::unique_ptr< OpMethodParameters > OpMethodParameters::create (llvm::SmallVectorImpl< OpMethodParameter > && params) static
Definition at line 61 of file OpClass.cpp.
create() [4/4]
std::unique_ptr< OpMethodParameters > OpMethodParameters::create (StringRef type, StringRef name, StringRef defaultValue = "") static
Definition at line 66 of file OpClass.cpp.
getKind()
ParamsKind mlir::tblgen::OpMethodParameters::getKind () const inline
Definition at line 90 of file OpClass.h.
References kind, mlir::tblgen::OpMethodParameter::writeDeclTo(), and mlir::tblgen::OpMethodParameter::writeDefTo().
Referenced by mlir::tblgen::OpMethodUnresolvedParameters::classof(), and mlir::tblgen::OpMethodResolvedParameters::classof().
writeDeclTo()
virtual void mlir::tblgen::OpMethodParameters::writeDeclTo (raw_ostream & os) const pure virtual
Implemented in mlir::tblgen::OpMethodResolvedParameters, and mlir::tblgen::OpMethodUnresolvedParameters.
writeDefTo()
virtual void mlir::tblgen::OpMethodParameters::writeDefTo (raw_ostream & os) const pure virtual
Implemented in mlir::tblgen::OpMethodResolvedParameters, and mlir::tblgen::OpMethodUnresolvedParameters.
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp