MLIR: mlir::MemRefType::Builder Class Reference
mlir::MemRefType::Builder Class Reference
This is a builder type that keeps local references to arguments.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
Builder (MemRefType other)
Builder (ArrayRef< int64_t > shape, Type elementType)
Builder & setShape (ArrayRef< int64_t > newShape)
Builder & setElementType (Type newElementType)
Builder & setAffineMaps (ArrayRef< AffineMap > newAffineMaps)
Builder & setMemorySpace (Attribute newMemorySpace)
Builder & setMemorySpace (unsigned newMemorySpace)
operator MemRefType ()
Detailed Description
This is a builder type that keeps local references to arguments.
Arguments that are passed into the builder must out-live the builder.
Definition at line 207 of file BuiltinTypes.h.
Constructor & Destructor Documentation
Builder() [1/2]
mlir::MemRefType::Builder::Builder (MemRefType other) inline explicit
Definition at line 210 of file BuiltinTypes.h.
Builder() [2/2]
mlir::MemRefType::Builder::Builder (ArrayRef< int64_t > shape, Type elementType) inline
Definition at line 216 of file BuiltinTypes.h.
Member Function Documentation
operator MemRefType()
mlir::MemRefType::Builder::operator MemRefType () inline
Definition at line 242 of file BuiltinTypes.h.
References mlir::computeRankReductionMask(), and elementType().
setAffineMaps()
Builder& mlir::MemRefType::Builder::setAffineMaps (ArrayRef< AffineMap > newAffineMaps) inline
Definition at line 229 of file BuiltinTypes.h.
Referenced by mlir::canonicalizeStridedLayout(), computeReshapeCollapsedType(), doubleBuffer(), mlir::eraseStridedLayout(), and inferTransposeResultType().
setElementType()
Builder& mlir::MemRefType::Builder::setElementType (Type newElementType) inline
Definition at line 224 of file BuiltinTypes.h.
References elementType().
Referenced by mlir::ShapedType::clone().
setMemorySpace() [1/2]
Builder& mlir::MemRefType::Builder::setMemorySpace (Attribute newMemorySpace) inline
Definition at line 234 of file BuiltinTypes.h.
Referenced by mlir::ShapedType::clone().
setMemorySpace() [2/2]
MemRefType::Builder & MemRefType::Builder::setMemorySpace (unsigned newMemorySpace)
Definition at line 633 of file BuiltinTypes.cpp.
References mlir::emitError(), mlir::detail::enumerate(), mlir::Type::getContext(), getElementType(), mlir::detail::getMemorySpaceAsInt(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::detail::isSupportedMemorySpace(), mlir::BaseMemRefType::isValidElementType(), map(), mlir::success(), mlir::verify(), and mlir::detail::wrapIntegerMemorySpace().
setShape()
Builder& mlir::MemRefType::Builder::setShape (ArrayRef< int64_t > newShape) inline
Definition at line 219 of file BuiltinTypes.h.
Referenced by mlir::ShapedType::clone(), computeReshapeCollapsedType(), doubleBuffer(), inferTransposeResultType(), mlir::normalizeMemRefType(), and verify().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp