MLIR: mlir::lsp::LSPServer Class Reference
mlir::lsp::LSPServer Class Reference
This class represents the main LSP server, and handles communication with the LSP client.
#include "Tools/mlir-lsp-server/LSPServer.h"
Classes
struct Impl
Public Member Functions
LSPServer (MLIRServer &server, JSONTransport &transport)
Construct a new language server with the given MLIR server.
~LSPServer ()
LogicalResult run ()
Run the main loop of the server.
Detailed Description
This class represents the main LSP server, and handles communication with the LSP client.
Definition at line 23 of file LSPServer.h.
Constructor & Destructor Documentation
LSPServer()
LSPServer::LSPServer (MLIRServer & server, JSONTransport & transport)
Construct a new language server with the given MLIR server.
Definition at line 199 of file LSPServer.cpp.
~LSPServer()
LSPServer::~LSPServer ()
Definition at line 201 of file LSPServer.cpp.
Member Function Documentation
run()
LogicalResult LSPServer::run ()
Run the main loop of the server.
Definition at line 203 of file LSPServer.cpp.
References mlir::lsp::Logger::error(), mlir::lsp::Error, mlir::failure(), mlir::lsp::MessageHandler::method(), mlir::lsp::MessageHandler::notification(), mlir::lsp::LSPServer::Impl::onDocumentDidChange(), mlir::lsp::LSPServer::Impl::onDocumentDidClose(), mlir::lsp::LSPServer::Impl::onDocumentDidOpen(), mlir::lsp::LSPServer::Impl::onDocumentSymbol(), mlir::lsp::LSPServer::Impl::onGoToDefinition(), mlir::lsp::LSPServer::Impl::onHover(), mlir::lsp::LSPServer::Impl::onInitialize(), mlir::lsp::LSPServer::Impl::onInitialized(), mlir::lsp::LSPServer::Impl::onReference(), mlir::lsp::LSPServer::Impl::onShutdown(), mlir::lsp::MessageHandler::outgoingNotification(), and mlir::success().
Referenced by mlir::MlirLspServerMain().
The documentation for this class was generated from the following files:
lib/Tools/mlir-lsp-server/LSPServer.h
lib/Tools/mlir-lsp-server/LSPServer.cpp