MLIR: mlir::tblgen::OpMethodUnresolvedParameters Class Reference
mlir::tblgen::OpMethodUnresolvedParameters Class Reference
#include "mlir/TableGen/OpClass.h"
Public Member Functions
OpMethodUnresolvedParameters (StringRef params)
void writeDeclTo (raw_ostream &os) const override
void writeDefTo (raw_ostream &os) const override
Public Member Functions inherited from mlir::tblgen::OpMethodParameters
OpMethodParameters (ParamsKind kind)
virtual ~OpMethodParameters ()
ParamsKind getKind () const
Static Public Member Functions
static bool classof (const OpMethodParameters *params)
Static Public Member Functions inherited from mlir::tblgen::OpMethodParameters
static std::unique_ptr< OpMethodParameters > create ()
static std::unique_ptr< OpMethodParameters > create (StringRef params)
static std::unique_ptr< OpMethodParameters > create (llvm::SmallVectorImpl< OpMethodParameter > &&params)
static std::unique_ptr< OpMethodParameters > create (StringRef type, StringRef name, StringRef defaultValue="")
Additional Inherited Members
Public Types inherited from mlir::tblgen::OpMethodParameters
enum ParamsKind { PK_Unresolved, PK_Resolved }
Detailed Description
Definition at line 115 of file OpClass.h.
Constructor & Destructor Documentation
OpMethodUnresolvedParameters()
mlir::tblgen::OpMethodUnresolvedParameters::OpMethodUnresolvedParameters (StringRef params) inline
Definition at line 117 of file OpClass.h.
References mlir::tblgen::OpMethodParameter::writeDeclTo(), and mlir::tblgen::OpMethodParameter::writeDefTo().
Member Function Documentation
classof()
static bool mlir::tblgen::OpMethodUnresolvedParameters::classof (const OpMethodParameters * params) inline static
Definition at line 127 of file OpClass.h.
References mlir::tblgen::OpMethodParameters::getKind().
writeDeclTo()
void OpMethodUnresolvedParameters::writeDeclTo (raw_ostream & os) const override virtual
Implements mlir::tblgen::OpMethodParameters.
Definition at line 74 of file OpClass.cpp.
writeDefTo()
void OpMethodUnresolvedParameters::writeDefTo (raw_ostream & os) const override virtual
Implements mlir::tblgen::OpMethodParameters.
Definition at line 78 of file OpClass.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp