MLIR: mlir::ConvertOpInterfaceToLLVMPattern< SourceOp > Class Template Reference
mlir::ConvertOpInterfaceToLLVMPattern< SourceOp > Class Template Reference
Utility class for operation conversions targeting the LLVM dialect that allows for matching and rewriting against an instance of an OpInterface class.
#include "mlir/Conversion/LLVMCommon/Pattern.h"
Public Member Functions
ConvertOpInterfaceToLLVMPattern (const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const final
virtual LogicalResult matchAndRewrite (SourceOp op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Methods that operate on the SourceOp type.
virtual LogicalResult matchAndRewrite (SourceOp op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const
Public Member Functions inherited from mlir::ConvertToLLVMPattern
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
Additional Inherited Members
Protected Member Functions inherited from mlir::ConvertToLLVMPattern
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
const LLVMTypeConverter * getTypeConverter () const
Type getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Type getIntPtrType (unsigned addressSpace=0) const
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
Type getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
Type getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Type getPtrType (unsigned addressSpace=0) const
Get the MLIR type wrapping the LLVM ptr type.
Value getStridedElementPtr (ConversionPatternRewriter &rewriter, Location loc, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags=LLVM::GEPNoWrapFlags::none) const
Convenience wrapper for the corresponding helper utility.
bool isConvertibleAndHasIdentityMaps (MemRefType type) const
Returns if the given memref type is convertible to LLVM and has an identity layout map.
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &strides, Value &size, bool sizeInBytes=true) const
Computes sizes, strides and buffer size of memRefType with identity layout.
Value getSizeInBytes (Location loc, Type type, ConversionPatternRewriter &rewriter) const
Computes the size of type in bytes.
Value getNumElements (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter) const
Computes total number of elements for the given MemRef and dynamicSizes.
MemRefDescriptor createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter &rewriter) const
Creates and populates a canonical memref descriptor struct.
Value copyUnrankedDescriptor (OpBuilder &builder, Location loc, UnrankedMemRefType memRefType, Value operand, bool toDynamic) const
Copies the given unranked memory descriptor to heap-allocated memory (if toDynamic is true) or to stack-allocated memory (otherwise) and returns the new descriptor.
LogicalResult copyUnrankedDescriptors (OpBuilder &builder, Location loc, TypeRange origTypes, SmallVectorImpl< Value > &operands, bool toDynamic) const
Copies the memory descriptor for any operands that were unranked descriptors originally to heap-allocated memory (if toDynamic is true) or to stack-allocated memory (otherwise).
Static Protected Member Functions inherited from mlir::ConvertToLLVMPattern
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
Create a constant Op producing a value of resultType from an index-typed integer attribute.
Detailed Description
template<typename SourceOp>
class mlir::ConvertOpInterfaceToLLVMPattern< SourceOp >
Utility class for operation conversions targeting the LLVM dialect that allows for matching and rewriting against an instance of an OpInterface class.
Definition at line 276 of file Pattern.h.
Constructor & Destructor Documentation
ConvertOpInterfaceToLLVMPattern()
template<typename SourceOp> mlir::ConvertOpInterfaceToLLVMPattern< SourceOp >::ConvertOpInterfaceToLLVMPattern (const LLVMTypeConverter & typeConverter, PatternBenefit benefit = 1) inline explicit
Definition at line 278 of file Pattern.h.
References mlir::ConvertToLLVMPattern::ConvertToLLVMPattern(), and getContext().
Member Function Documentation
matchAndRewrite() [1/4]
template<typename SourceOp> LogicalResult mlir::ConvertOpInterfaceToLLVMPattern< SourceOp >::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline final
Wrappers around the RewritePattern methods that pass the derived op type.
Definition at line 286 of file Pattern.h.
References matchAndRewrite().
Referenced by matchAndRewrite(), and matchAndRewrite().
matchAndRewrite() [2/4]
template<typename SourceOp> LogicalResult mlir::ConvertOpInterfaceToLLVMPattern< SourceOp >::matchAndRewrite (Operation * op, ArrayRef< ValueRange > operands, ConversionPatternRewriter & rewriter) const inline final
Definition at line 291 of file Pattern.h.
References matchAndRewrite().
matchAndRewrite() [3/4]
template<typename SourceOp> virtual LogicalResult mlir::ConvertOpInterfaceToLLVMPattern< SourceOp >::matchAndRewrite (SourceOp op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Methods that operate on the SourceOp type.
One of these must be overridden by the derived pattern class.
Definition at line 299 of file Pattern.h.
matchAndRewrite() [4/4]
template<typename SourceOp> virtual LogicalResult mlir::ConvertOpInterfaceToLLVMPattern< SourceOp >::matchAndRewrite (SourceOp op, ArrayRef< ValueRange > operands, ConversionPatternRewriter & rewriter) const inline virtual
Definition at line 304 of file Pattern.h.
The documentation for this class was generated from the following file:
include/mlir/Conversion/LLVMCommon/Pattern.h