MLIR: mlir::affine::AffineDmaStartOp Class Reference
mlir::affine::AffineDmaStartOp Class Reference
AffineDmaStartOp starts a non-blocking DMA operation that transfers data from a source memref to a destination memref.
#include "mlir/Dialect/Affine/IR/AffineOps.h"
Public Member Functions
unsigned getSrcMemRefOperandIndex ()
Returns the operand index of the source memref.
Value getSrcMemRef ()
Returns the source MemRefType for this DMA operation.
OpOperand & getSrcMemRefMutable ()
MemRefType getSrcMemRefType ()
unsigned getSrcMemRefRank ()
Returns the rank (number of indices) of the source MemRefType.
AffineMap getSrcMap ()
Returns the affine map used to access the source memref.
AffineMapAttr getSrcMapAttr ()
operand_range getSrcIndices ()
Returns the source memref affine map indices for this DMA operation.
unsigned getSrcMemorySpace ()
Returns the memory space of the source memref.
unsigned getDstMemRefOperandIndex ()
Returns the operand index of the destination memref.
Value getDstMemRef ()
Returns the destination MemRefType for this DMA operation.
OpOperand & getDstMemRefMutable ()
MemRefType getDstMemRefType ()
unsigned getDstMemRefRank ()
Returns the rank (number of indices) of the destination MemRefType.
unsigned getDstMemorySpace ()
Returns the memory space of the source memref.
AffineMap getDstMap ()
Returns the affine map used to access the destination memref.
AffineMapAttr getDstMapAttr ()
operand_range getDstIndices ()
Returns the destination memref indices for this DMA operation.
unsigned getTagMemRefOperandIndex ()
Returns the operand index of the tag memref.
Value getTagMemRef ()
Returns the Tag MemRef for this DMA operation.
OpOperand & getTagMemRefMutable ()
MemRefType getTagMemRefType ()
unsigned getTagMemRefRank ()
Returns the rank (number of indices) of the tag MemRefType.
AffineMap getTagMap ()
Returns the affine map used to access the tag memref.
AffineMapAttr getTagMapAttr ()
operand_range getTagIndices ()
Returns the tag memref indices for this DMA operation.
Value getNumElements ()
Returns the number of elements being transferred by this DMA operation.
NamedAttribute getAffineMapAttrForMemRef (Value memref)
Impelements the AffineMapAccessInterface.
bool isDestMemorySpaceFaster ()
Returns true if this is a DMA from a faster memory space to a slower one.
bool isSrcMemorySpaceFaster ()
Returns true if this is a DMA from a slower memory space to a faster one.
unsigned getFasterMemPos ()
Given a DMA start operation, returns the operand position of either the source or destination memref depending on the one that is at the higher level of the memory hierarchy.
void getEffects (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect > > &effects)
void print (OpAsmPrinter &p)
LogicalResult verifyInvariantsImpl ()
LogicalResult verifyInvariants ()
LogicalResult fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > &results)
bool isStrided ()
Returns true if this DMA operation is strided, returns false otherwise.
Value getStride ()
Returns the stride value for this DMA operation.
Value getNumElementsPerStride ()
Returns the number of elements to transfer per stride for this DMA op.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
Public Member Functions inherited from mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait, MemoryEffectOpInterface::Trait >
Operation * getOperation ()
Inherit getOperation from OpState.
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
LogicalResult verifyRegions ()
AffineDmaStartOp clone ()
Create a deep copy of this operation.
AffineDmaStartOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Op ()
This is a public constructor. Any op can be initialized to null.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
InferredProperties< T > & getProperties ()
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * operator-> () const
Shortcut of -> to access a member of Operation.
Operation * getOperation ()
Return the operation that this refers to.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags={})
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==1, RetT > walk (FnT &&callback)
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
template<typename FnT, typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==2, RetT > walk (FnT &&callback)
Generic walker with a stage aware callback.
Static Public Member Functions
static ArrayRef< StringRef > getAttributeNames ()
static void build (OpBuilder &builder, OperationState &result, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride=nullptr, Value elementsPerStride=nullptr)
static AffineDmaStartOp create (OpBuilder &builder, Location location, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride=nullptr, Value elementsPerStride=nullptr)
static AffineDmaStartOp create (ImplicitLocOpBuilder &builder, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride=nullptr, Value elementsPerStride=nullptr)
static StringRef getSrcMapAttrStrName ()
static StringRef getDstMapAttrStrName ()
static StringRef getTagMapAttrStrName ()
static StringRef getOperationName ()
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Static Public Member Functions inherited from mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait, MemoryEffectOpInterface::Trait >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static ConcreteOpType getFromOpaquePointer (const void *pointer)
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
static LogicalResult setPropertiesFromAttr (PropertiesTy &prop, Attribute attr, function_ref< InFlightDiagnostic()> emitError)
Convert the provided attribute to a property and assigned it to the provided properties.
static Attribute getPropertiesAsAttr (MLIRContext *ctx, const PropertiesTy &prop)
Convert the provided properties to an attribute.
static llvm::hash_code computePropertiesHash (const PropertiesTy &prop)
Hash the provided properties.
static constexpr bool hasProperties ()
Returns true if this operation defines a Properties inner type.
static void populateDefaultProperties (OperationName opName, InferredProperties< T > &properties)
This hook populates any unset default attrs when mapped to properties.
static void printProperties (MLIRContext *ctx, OpAsmPrinter &p, const T &properties, ArrayRef< StringRef > elidedProps={})
Print the operation properties with names not included within 'elidedProps'.
static ParseResult parseProperties (OpAsmParser &parser, OperationState &result)
Parses 'prop-dict' for the operation.
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
static void populateDefaultAttrs (const OperationName &, NamedAttrList &)
This hook populates any unset default attrs.
Additional Inherited Members
Public Types inherited from mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait, MemoryEffectOpInterface::Trait >
using ConcreteOpType
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
using InferredProperties
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
LogicalResult verifyRegions ()
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< AffineDmaStartOp, MemRefsNormalizable >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Parse the custom form of an operation.
static void print (Operation *op, OpAsmPrinter &p, StringRef defaultDialect)
Print the operation.
static ParseResult genericParseProperties (OpAsmParser &parser, Attribute &result)
Parse properties as a Attribute.
static void genericPrintProperties (OpAsmPrinter &p, Attribute properties, ArrayRef< StringRef > elidedProps={})
Print the properties as a Attribute with names not included within 'elidedProps'.
static void printOpName (Operation *op, OpAsmPrinter &p, StringRef defaultDialect)
Print an operation name, eliding the dialect prefix if necessary.
static EmptyProperties & getEmptyProperties ()
For all op which don't have properties, we keep a single instance of EmptyProperties to be used where a reference to a properties is needed: this allow to bind a pointer to the reference without triggering UB.
Detailed Description
AffineDmaStartOp starts a non-blocking DMA operation that transfers data from a source memref to a destination memref.
The source and destination memref need not be of the same dimensionality, but need to have the same elemental type. The operands include the source and destination memref's each followed by its indices, size of the data transfer in terms of the number of elements (of the elemental type of the memref), a tag memref with its indices, and optionally at the end, a stride and a number_of_elements_per_stride arguments. The tag location is used by an AffineDmaWaitOp to check for completion. The indices of the source memref, destination memref, and the tag memref have the same restrictions as any affine.load/store. In particular, index for each memref dimension must be an affine expression of loop induction variables and symbols. The optional stride arguments should be of 'index' type, and specify a stride for the slower memory space (memory space with a lower memory space id), transferring chunks of number_of_elements_per_stride every stride until num_elements are transferred. Either both or no stride arguments should be specified. The value of 'num_elements' must be a multiple of 'number_of_elements_per_stride'. If the source and destination locations overlap the behavior of this operation is not defined.
Definition at line 102 of file AffineOps.h.
Member Function Documentation
build()
void AffineDmaStartOp::build (OpBuilder & builder, OperationState & result, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride = nullptr, Value elementsPerStride = nullptr) static
Definition at line 1866 of file AffineOps.cpp.
References getDstMapAttrStrName(), getSrcMapAttrStrName(), getTagMapAttrStrName(), and result.
Referenced by create().
create() [1/2]
AffineDmaStartOp AffineDmaStartOp::create (ImplicitLocOpBuilder & builder, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride = nullptr, Value elementsPerStride = nullptr) static
Definition at line 1903 of file AffineOps.cpp.
References create(), and mlir::ImplicitLocOpBuilder::getLoc().
create() [2/2]
AffineDmaStartOp AffineDmaStartOp::create (OpBuilder & builder, Location location, Value srcMemRef, AffineMap srcMap, ValueRange srcIndices, Value destMemRef, AffineMap dstMap, ValueRange destIndices, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements, Value stride = nullptr, Value elementsPerStride = nullptr) static
Definition at line 1888 of file AffineOps.cpp.
References build(), mlir::OpBuilder::create(), getOperationName(), and result.
Referenced by create(), and generateCopy().
fold()
LogicalResult AffineDmaStartOp::fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > & results)
dma_start(memrefcast) -> dma_start
Definition at line 2053 of file AffineOps.cpp.
References mlir::memref::foldMemRefCast().
getAffineMapAttrForMemRef()
NamedAttribute mlir::affine::AffineDmaStartOp::getAffineMapAttrForMemRef (Value memref) inline
Impelements the AffineMapAccessInterface.
Returns the AffineMapAttr associated with 'memref'.
Definition at line 245 of file AffineOps.h.
References mlir::OpState::getContext(), getDstMapAttr(), getDstMapAttrStrName(), getDstMemRef(), getSrcMapAttr(), getSrcMapAttrStrName(), getSrcMemRef(), getTagMapAttr(), getTagMapAttrStrName(), and getTagMemRef().
getAttributeNames()
ArrayRef< StringRef > mlir::affine::AffineDmaStartOp::getAttributeNames () inline static
Definition at line 109 of file AffineOps.h.
getDstIndices()
operand_range mlir::affine::AffineDmaStartOp::getDstIndices () inline
Returns the destination memref indices for this DMA operation.
Definition at line 198 of file AffineOps.h.
References getDstMap(), getDstMemRefOperandIndex(), and mlir::AffineMap::getNumInputs().
Referenced by print(), and verifyInvariantsImpl().
getDstMap()
AffineMap mlir::affine::AffineDmaStartOp::getDstMap () inline
Returns the affine map used to access the destination memref.
Definition at line 191 of file AffineOps.h.
References getDstMapAttr().
Referenced by getDstIndices(), getTagMemRefOperandIndex(), and verifyInvariantsImpl().
getDstMapAttr()
AffineMapAttr mlir::affine::AffineDmaStartOp::getDstMapAttr () inline
Definition at line 192 of file AffineOps.h.
References getDstMapAttrStrName().
Referenced by getAffineMapAttrForMemRef(), getDstMap(), and print().
getDstMapAttrStrName()
StringRef mlir::affine::AffineDmaStartOp::getDstMapAttrStrName () inline static
Definition at line 282 of file AffineOps.h.
Referenced by build(), getAffineMapAttrForMemRef(), getDstMapAttr(), and parse().
getDstMemorySpace()
unsigned mlir::affine::AffineDmaStartOp::getDstMemorySpace () inline
Returns the memory space of the source memref.
Definition at line 186 of file AffineOps.h.
References getDstMemRef(), and mlir::getType().
Referenced by isDestMemorySpaceFaster(), and isSrcMemorySpaceFaster().
getDstMemRef()
Value mlir::affine::AffineDmaStartOp::getDstMemRef () inline
Returns the destination MemRefType for this DMA operation.
Definition at line 172 of file AffineOps.h.
References getDstMemRefOperandIndex().
Referenced by getAffineMapAttrForMemRef(), getDstMemorySpace(), getDstMemRefRank(), getDstMemRefType(), and print().
getDstMemRefMutable()
OpOperand & mlir::affine::AffineDmaStartOp::getDstMemRefMutable () inline
Definition at line 173 of file AffineOps.h.
References getDstMemRefOperandIndex(), mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait, MemoryEffectOpInterface::Trait >::getOperation(), and mlir::Operation::getOpOperand().
Referenced by getEffects().
getDstMemRefOperandIndex()
unsigned mlir::affine::AffineDmaStartOp::getDstMemRefOperandIndex () inline
Returns the operand index of the destination memref.
Definition at line 167 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getSrcMap(), and getSrcMemRefOperandIndex().
Referenced by getDstIndices(), getDstMemRef(), getDstMemRefMutable(), getFasterMemPos(), getTagMemRefOperandIndex(), and verifyInvariantsImpl().
getDstMemRefRank()
unsigned mlir::affine::AffineDmaStartOp::getDstMemRefRank () inline
Returns the rank (number of indices) of the destination MemRefType.
Definition at line 181 of file AffineOps.h.
References getDstMemRef(), and mlir::getType().
getDstMemRefType()
MemRefType mlir::affine::AffineDmaStartOp::getDstMemRefType () inline
Definition at line 176 of file AffineOps.h.
References getDstMemRef(), and mlir::getType().
Referenced by print().
getEffects()
void AffineDmaStartOp::getEffects (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect > > & effects)
Definition at line 2059 of file AffineOps.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, Effect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), getDstMemRefMutable(), getSrcMemRefMutable(), and getTagMemRefMutable().
getFasterMemPos()
unsigned mlir::affine::AffineDmaStartOp::getFasterMemPos () inline
Given a DMA start operation, returns the operand position of either the source or destination memref depending on the one that is at the higher level of the memory hierarchy.
Asserts failure if neither is true.
Definition at line 272 of file AffineOps.h.
References getDstMemRefOperandIndex(), isDestMemorySpaceFaster(), and isSrcMemorySpaceFaster().
getNumElements()
Value mlir::affine::AffineDmaStartOp::getNumElements () inline
Returns the number of elements being transferred by this DMA operation.
Definition at line 238 of file AffineOps.h.
References getTagMap(), and getTagMemRefOperandIndex().
Referenced by print().
getNumElementsPerStride()
Value mlir::affine::AffineDmaStartOp::getNumElementsPerStride () inline
Returns the number of elements to transfer per stride for this DMA op.
Definition at line 307 of file AffineOps.h.
References isStrided().
Referenced by print().
getOperationName()
StringRef mlir::affine::AffineDmaStartOp::getOperationName () inline static
Definition at line 285 of file AffineOps.h.
Referenced by create().
getSrcIndices()
operand_range mlir::affine::AffineDmaStartOp::getSrcIndices () inline
Returns the source memref affine map indices for this DMA operation.
Definition at line 155 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getSrcMap(), and getSrcMemRefOperandIndex().
Referenced by print(), and verifyInvariantsImpl().
getSrcMap()
AffineMap mlir::affine::AffineDmaStartOp::getSrcMap () inline
Returns the affine map used to access the source memref.
Definition at line 148 of file AffineOps.h.
References getSrcMapAttr().
Referenced by getDstMemRefOperandIndex(), getSrcIndices(), and verifyInvariantsImpl().
getSrcMapAttr()
AffineMapAttr mlir::affine::AffineDmaStartOp::getSrcMapAttr () inline
Definition at line 149 of file AffineOps.h.
References getSrcMapAttrStrName().
Referenced by getAffineMapAttrForMemRef(), getSrcMap(), and print().
getSrcMapAttrStrName()
StringRef mlir::affine::AffineDmaStartOp::getSrcMapAttrStrName () inline static
Definition at line 281 of file AffineOps.h.
Referenced by build(), getAffineMapAttrForMemRef(), getSrcMapAttr(), and parse().
getSrcMemorySpace()
unsigned mlir::affine::AffineDmaStartOp::getSrcMemorySpace () inline
Returns the memory space of the source memref.
Definition at line 162 of file AffineOps.h.
References getSrcMemRef(), and mlir::getType().
Referenced by isDestMemorySpaceFaster(), and isSrcMemorySpaceFaster().
getSrcMemRef()
Value mlir::affine::AffineDmaStartOp::getSrcMemRef () inline
Returns the source MemRefType for this DMA operation.
Definition at line 136 of file AffineOps.h.
References getSrcMemRefOperandIndex().
Referenced by getAffineMapAttrForMemRef(), getSrcMemorySpace(), getSrcMemRefType(), and print().
getSrcMemRefMutable()
OpOperand & mlir::affine::AffineDmaStartOp::getSrcMemRefMutable () inline
Definition at line 137 of file AffineOps.h.
References mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait, MemoryEffectOpInterface::Trait >::getOperation(), mlir::Operation::getOpOperand(), and getSrcMemRefOperandIndex().
Referenced by getEffects().
getSrcMemRefOperandIndex()
unsigned mlir::affine::AffineDmaStartOp::getSrcMemRefOperandIndex () inline
Returns the operand index of the source memref.
Definition at line 133 of file AffineOps.h.
Referenced by getDstMemRefOperandIndex(), getSrcIndices(), getSrcMemRef(), getSrcMemRefMutable(), and verifyInvariantsImpl().
getSrcMemRefRank()
unsigned mlir::affine::AffineDmaStartOp::getSrcMemRefRank () inline
Returns the rank (number of indices) of the source MemRefType.
Definition at line 145 of file AffineOps.h.
References getSrcMemRefType().
getSrcMemRefType()
MemRefType mlir::affine::AffineDmaStartOp::getSrcMemRefType () inline
Definition at line 140 of file AffineOps.h.
References getSrcMemRef(), and mlir::getType().
Referenced by getSrcMemRefRank(), and print().
getStride()
Value mlir::affine::AffineDmaStartOp::getStride () inline
Returns the stride value for this DMA operation.
Definition at line 300 of file AffineOps.h.
References isStrided().
Referenced by print().
getTagIndices()
operand_range mlir::affine::AffineDmaStartOp::getTagIndices () inline
Returns the tag memref indices for this DMA operation.
Definition at line 231 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getTagMap(), and getTagMemRefOperandIndex().
Referenced by checkTagMatch(), print(), and verifyInvariantsImpl().
getTagMap()
AffineMap mlir::affine::AffineDmaStartOp::getTagMap () inline
Returns the affine map used to access the tag memref.
Definition at line 224 of file AffineOps.h.
References getTagMapAttr().
Referenced by getNumElements(), getTagIndices(), isStrided(), and verifyInvariantsImpl().
getTagMapAttr()
AffineMapAttr mlir::affine::AffineDmaStartOp::getTagMapAttr () inline
Definition at line 225 of file AffineOps.h.
References getTagMapAttrStrName().
Referenced by getAffineMapAttrForMemRef(), getTagMap(), and print().
getTagMapAttrStrName()
StringRef mlir::affine::AffineDmaStartOp::getTagMapAttrStrName () inline static
Definition at line 283 of file AffineOps.h.
Referenced by build(), getAffineMapAttrForMemRef(), getTagMapAttr(), and parse().
getTagMemRef()
Value mlir::affine::AffineDmaStartOp::getTagMemRef () inline
Returns the Tag MemRef for this DMA operation.
Definition at line 210 of file AffineOps.h.
References getTagMemRefOperandIndex().
Referenced by checkTagMatch(), getAffineMapAttrForMemRef(), getTagMemRefRank(), getTagMemRefType(), and print().
getTagMemRefMutable()
OpOperand & mlir::affine::AffineDmaStartOp::getTagMemRefMutable () inline
Definition at line 211 of file AffineOps.h.
References mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait, MemoryEffectOpInterface::Trait >::getOperation(), mlir::Operation::getOpOperand(), and getTagMemRefOperandIndex().
Referenced by getEffects().
getTagMemRefOperandIndex()
unsigned mlir::affine::AffineDmaStartOp::getTagMemRefOperandIndex () inline
Returns the operand index of the tag memref.
Definition at line 205 of file AffineOps.h.
References getDstMap(), getDstMemRefOperandIndex(), and mlir::AffineMap::getNumInputs().
Referenced by getNumElements(), getTagIndices(), getTagMemRef(), getTagMemRefMutable(), isStrided(), and verifyInvariantsImpl().
getTagMemRefRank()
unsigned mlir::affine::AffineDmaStartOp::getTagMemRefRank () inline
Returns the rank (number of indices) of the tag MemRefType.
Definition at line 219 of file AffineOps.h.
References getTagMemRef(), and mlir::getType().
getTagMemRefType()
MemRefType mlir::affine::AffineDmaStartOp::getTagMemRefType () inline
Definition at line 214 of file AffineOps.h.
References getTagMemRef(), and mlir::getType().
Referenced by print().
isDestMemorySpaceFaster()
bool mlir::affine::AffineDmaStartOp::isDestMemorySpaceFaster () inline
Returns true if this is a DMA from a faster memory space to a slower one.
Definition at line 259 of file AffineOps.h.
References getDstMemorySpace(), and getSrcMemorySpace().
Referenced by getFasterMemPos().
isSrcMemorySpaceFaster()
bool mlir::affine::AffineDmaStartOp::isSrcMemorySpaceFaster () inline
Returns true if this is a DMA from a slower memory space to a faster one.
Definition at line 264 of file AffineOps.h.
References getDstMemorySpace(), and getSrcMemorySpace().
Referenced by getFasterMemPos().
isStrided()
bool mlir::affine::AffineDmaStartOp::isStrided () inline
Returns true if this DMA operation is strided, returns false otherwise.
Definition at line 294 of file AffineOps.h.
References mlir::AffineMap::getNumInputs(), getTagMap(), and getTagMemRefOperandIndex().
Referenced by getNumElementsPerStride(), getStride(), parse(), and print().
Op() [1/3]
mlir::Op< ConcreteType, Traits >::Op () inline explicit
This is a public constructor. Any op can be initialized to null.
Definition at line 1721 of file OpDefinition.h.
Op() [2/3]
mlir::Op< ConcreteType, Traits >::Op (Operation * state) inline explicit
This is a public constructor to enable access via the llvm::cast family of methods.
This should not be used directly.
Definition at line 1726 of file OpDefinition.h.
Op() [3/3]
mlir::Op< ConcreteType, Traits >::Op (std::nullptr_t) inline
Definition at line 1722 of file OpDefinition.h.
parse()
ParseResult AffineDmaStartOp::parse (OpAsmParser & parser, OperationState & result) static
Definition at line 1936 of file AffineOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), getDstMapAttrStrName(), mlir::Builder::getIndexType(), mlir::AsmParser::getNameLoc(), getSrcMapAttrStrName(), getTagMapAttrStrName(), isStrided(), mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), result, and success().
print()
void AffineDmaStartOp::print (OpAsmPrinter & p)
Definition at line 1914 of file AffineOps.cpp.
References getDstIndices(), getDstMapAttr(), getDstMemRef(), getDstMemRefType(), getNumElements(), getNumElementsPerStride(), getSrcIndices(), getSrcMapAttr(), getSrcMemRef(), getSrcMemRefType(), getStride(), getTagIndices(), getTagMapAttr(), getTagMemRef(), getTagMemRefType(), isStrided(), and mlir::OpAsmPrinter::printAffineMapOfSSAIds().
verifyInvariants()
LogicalResult mlir::affine::AffineDmaStartOp::verifyInvariants () inline
Definition at line 289 of file AffineOps.h.
References verifyInvariantsImpl().
verifyInvariantsImpl()
LogicalResult AffineDmaStartOp::verifyInvariantsImpl ()
Definition at line 2012 of file AffineOps.cpp.
References mlir::OpState::emitOpError(), mlir::affine::getAffineScope(), getDstIndices(), getDstMap(), getDstMemRefOperandIndex(), mlir::AffineMap::getNumInputs(), getSrcIndices(), getSrcMap(), getSrcMemRefOperandIndex(), getTagIndices(), getTagMap(), getTagMemRefOperandIndex(), mlir::getType(), isValidAffineIndexOperand(), and success().
Referenced by verifyInvariants().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/IR/AffineOps.h
lib/Dialect/Affine/IR/AffineOps.cpp