MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr Class Reference
Public Member Functions
PyConcreteAffineExpr ()=default
PyConcreteAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr)
PyConcreteAffineExpr (PyAffineExpr &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineConstantExpr >
PyConcreteAffineExpr ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr
PyAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr)
bool operator== (const PyAffineExpr &other) const
operator MlirAffineExpr () const
MlirAffineExpr get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineExpr.
PyAffineExpr add (const PyAffineExpr &other) const
PyAffineExpr mul (const PyAffineExpr &other) const
PyAffineExpr floorDiv (const PyAffineExpr &other) const
PyAffineExpr ceilDiv (const PyAffineExpr &other) const
PyAffineExpr mod (const PyAffineExpr &other) const
nanobind::typed< nanobind::object, PyAffineExpr > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyAffineConstantExpr get (intptr_t value, DefaultingPyMlirContext context)
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineConstantExpr >
static MlirAffineExpr castFrom (PyAffineExpr &orig)
static void bind (nb::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr
static PyAffineExpr createFromCapsule (const nanobind::object &capsule)
Creates a PyAffineExpr from the MlirAffineExpr wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirAffineExprIsAConstant
static constexpr const char * pyClassName = "AffineConstantExpr"
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineConstantExpr >
using ClassTy
using IsAFunctionTy
Detailed Description
Definition at line 119 of file IRAffine.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr::bindDerived (ClassTy & c) inline static
Definition at line 132 of file IRAffine.cpp.
References get(), and mlirAffineConstantExprGetValue().
get()
PyAffineConstantExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr::get (intptr_t value, DefaultingPyMlirContext context) inline static
Definition at line 125 of file IRAffine.cpp.
References mlir::python::Defaulting< DerivedTy, T >::get(), and mlirAffineConstantExprGet().
Referenced by bindDerived(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
PyConcreteAffineExpr() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr () default
PyConcreteAffineExpr() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr (PyAffineExpr & orig) inline
Definition at line 94 of file IRAffine.cpp.
PyConcreteAffineExpr() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr) inline
Definition at line 92 of file IRAffine.cpp.
Member Data Documentation
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr::isaFunction = mlirAffineExprIsAConstant static constexpr
Definition at line 121 of file IRAffine.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr::pyClassName = "AffineConstantExpr" static constexpr
Definition at line 122 of file IRAffine.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRAffine.cpp