MLIR: mlir::tracing::BreakpointManager Class Reference
mlir::tracing::BreakpointManager Class Reference abstract
A breakpoint manager is responsible for managing a set of breakpoints and matching them to a given action.
#include "mlir/Debug/BreakpointManager.h"
Public Member Functions
virtual ~BreakpointManager ()=default
TypeID getTypeID () const
TypeID for the subclass, used for casting purpose.
virtual Breakpoint * match (const Action &action) const =0
Try to match a Breakpoint to a given Action.
Protected Member Functions
BreakpointManager (TypeID typeID)
Protected Attributes
TypeID typeID
Detailed Description
A breakpoint manager is responsible for managing a set of breakpoints and matching them to a given action.
Definition at line 62 of file BreakpointManager.h.
Constructor & Destructor Documentation
~BreakpointManager()
virtual mlir::tracing::BreakpointManager::~BreakpointManager () virtual default
BreakpointManager()
mlir::tracing::BreakpointManager::BreakpointManager (TypeID typeID) inline protected
Definition at line 75 of file BreakpointManager.h.
References typeID.
Referenced by mlir::tracing::BreakpointManagerBase< Derived >::BreakpointManagerBase(), and mlir::tracing::BreakpointManagerBase< Derived >::classof().
Member Function Documentation
getTypeID()
TypeID mlir::tracing::BreakpointManager::getTypeID () const inline
TypeID for the subclass, used for casting purpose.
Definition at line 67 of file BreakpointManager.h.
References typeID.
Referenced by mlir::tracing::BreakpointManagerBase< Derived >::classof().
match()
virtual Breakpoint * mlir::tracing::BreakpointManager::match (const Action & action) const pure virtual
Try to match a Breakpoint to a given Action.
If there is a match and the breakpoint is enabled, return the breakpoint. Otherwise, return nullptr.
Implemented in mlir::tracing::FileLineColLocBreakpointManager, and mlir::tracing::TagBreakpointManager.
Member Data Documentation
typeID
TypeID mlir::tracing::BreakpointManager::typeID protected
Definition at line 77 of file BreakpointManager.h.
Referenced by BreakpointManager(), and getTypeID().
The documentation for this class was generated from the following file:
include/mlir/Debug/BreakpointManager.h