MLIR: mlir::pdll::ast::MemberAccessExpr Class Reference
mlir::pdll::ast::MemberAccessExpr Class Reference
This expression represents a named member or field access of a given parent expression.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
const Expr * getParentExpr () const
Get the parent expression of this access.
StringRef getMemberName () const
Return the name of the member being accessed.
Static Public Member Functions
static MemberAccessExpr * create (Context &ctx, SMRange loc, const Expr *parentExpr, StringRef memberName, Type type)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< T, BaseT >
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< T, BaseT >
using Base = NodeBase< T, BaseT >
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< T, BaseT >
template<typename... Args>
NodeBase (SMRange loc, Args &&...args)
Detailed Description
This expression represents a named member or field access of a given parent expression.
Definition at line 454 of file Nodes.h.
Member Function Documentation
create()
MemberAccessExpr * MemberAccessExpr::create (Context & ctx, SMRange loc, const Expr * parentExpr, StringRef memberName, Type type) static
Definition at line 295 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator().
Referenced by mlir::pdll::ast::AllResultsMemberAccessExpr::create().
getMemberName()
StringRef mlir::pdll::ast::MemberAccessExpr::getMemberName () const inline
Return the name of the member being accessed.
Definition at line 464 of file Nodes.h.
Referenced by mlir::pdll::ast::AllResultsMemberAccessExpr::classof().
getParentExpr()
const Expr* mlir::pdll::ast::MemberAccessExpr::getParentExpr () const inline
Get the parent expression of this access.
Definition at line 461 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp