MLIR: mlir::OpTrait::AttrSizedOperandSegments< ConcreteType > Class Template Reference
mlir::OpTrait::AttrSizedOperandSegments< ConcreteType > Class Template Reference
A trait for operations that have an attribute specifying operand segments.
#include "mlir/IR/OpDefinition.h"
Static Public Member Functions
static StringRef getOperandSegmentSizeAttr ()
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, AttrSizedOperandSegments >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::AttrSizedOperandSegments< ConcreteType >
A trait for operations that have an attribute specifying operand segments.
Certain operations can have multiple variadic operands and their size relationship is not always known statically. For such cases, we need a per-op-instance specification to divide the operands into logical groups or segments. This can be modeled by attributes. The attribute will be named as operandSegmentSizes.
This trait verifies the attribute for specifying operand segments has the correct type (1D vector) and values (non-negative), etc.
Definition at line 1337 of file OpDefinition.h.
Member Function Documentation
getOperandSegmentSizeAttr()
template<typename ConcreteType> StringRef mlir::OpTrait::AttrSizedOperandSegments< ConcreteType >::getOperandSegmentSizeAttr () inline static
Definition at line 1340 of file OpDefinition.h.
Referenced by mlir::gpu::addAsyncDependency(), and verifyTrait().
verifyTrait()
template<typename ConcreteType> LogicalResult mlir::OpTrait::AttrSizedOperandSegments< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 1342 of file OpDefinition.h.
References getOperandSegmentSizeAttr().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h