MLIR: mlir::python::PyDialectRegistry Class Reference
mlir::python::PyDialectRegistry Class Reference
Wrapper around an MlirDialectRegistry.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyDialectRegistry ()
PyDialectRegistry (MlirDialectRegistry registry)
~PyDialectRegistry ()
PyDialectRegistry (PyDialectRegistry &)=delete
PyDialectRegistry (PyDialectRegistry &&other) noexcept
operator MlirDialectRegistry () const
MlirDialectRegistry get () const
nanobind::object getCapsule ()
Static Public Member Functions
static PyDialectRegistry createFromCapsule (nanobind::object capsule)
Detailed Description
Wrapper around an MlirDialectRegistry.
Upon construction, the Python wrapper takes ownership of the underlying MlirDialectRegistry.
Definition at line 472 of file IRModule.h.
Constructor & Destructor Documentation
PyDialectRegistry() [1/4]
mlir::python::PyDialectRegistry::PyDialectRegistry () inline
Definition at line 474 of file IRModule.h.
References mlirDialectRegistryCreate().
Referenced by createFromCapsule(), PyDialectRegistry(), and PyDialectRegistry().
PyDialectRegistry() [2/4]
mlir::python::PyDialectRegistry::PyDialectRegistry (MlirDialectRegistry registry) inline
Definition at line 475 of file IRModule.h.
~PyDialectRegistry()
mlir::python::PyDialectRegistry::~PyDialectRegistry () inline
Definition at line 476 of file IRModule.h.
References mlirDialectRegistryDestroy(), and mlirDialectRegistryIsNull().
PyDialectRegistry() [3/4]
mlir::python::PyDialectRegistry::PyDialectRegistry (PyDialectRegistry &) delete
References PyDialectRegistry().
PyDialectRegistry() [4/4]
mlir::python::PyDialectRegistry::PyDialectRegistry (PyDialectRegistry && other) inline noexcept
Definition at line 481 of file IRModule.h.
References PyDialectRegistry().
Member Function Documentation
createFromCapsule()
PyDialectRegistry PyDialectRegistry::createFromCapsule (nanobind::object capsule) static
Definition at line 917 of file IRCore.cpp.
References mlirDialectRegistryIsNull(), mlirPythonCapsuleToDialectRegistry(), and PyDialectRegistry().
get()
MlirDialectRegistry mlir::python::PyDialectRegistry::get () const inline
Definition at line 487 of file IRModule.h.
getCapsule()
nb::object PyDialectRegistry::getCapsule ()
Definition at line 913 of file IRCore.cpp.
References mlirPythonDialectRegistryToCapsule().
operator MlirDialectRegistry()
mlir::python::PyDialectRegistry::operator MlirDialectRegistry () const inline
Definition at line 486 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp