MLIR: mlir::ConstraintsSet Class Reference
mlir::ConstraintsSet Class Reference
Linalg-specific constraints set extensions.
#include "mlir/Dialect/Linalg/Analysis/ConstraintsSet.h"
Public Member Functions
ConstraintsSet ()
LogicalResult composeMin (Value val, AffineMap map, ValueRange operands)
Assuming val is defined by val = affine.min map (operands), introduce all the constraints val >= expr_i(operands), where expr_i are all the results of map.
LogicalResult composeMax (Value val, AffineMap map, ValueRange operands)
Assuming val is defined by val = affine.max map (operands), introduce all the constraints val <= expr_i(operands), where expr_i are all the results of map.
LogicalResult composeAffineApply (Value val, AffineMap map, ValueRange operands)
Assuming val is defined by val = affine.apply map (operands), call composeMap.
unsigned lookupPos (Value id) const
Asserts the identifier id is in the constraints set and returns it.
LogicalResult ensureIdOfType (Value v, bool asDim)
If v is not in the constraint set, insert it as a dim or symbol depending on asDim.
Public Member Functions inherited from mlir::FlatAffineConstraints
FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0, ArrayRef< Optional< Value >> idArgs={})
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0, ArrayRef< Optional< Value >> idArgs={})
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineConstraints (const AffineValueMap &avm)
Create a flat affine constraint system from an AffineValueMap or a list of these.
FlatAffineConstraints (ArrayRef< const AffineValueMap *> avmRef)
FlatAffineConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineConstraints (ArrayRef< const AffineValueMap *> avmRef, IntegerSet set)
FlatAffineConstraints (const MutableAffineMap &map)
~FlatAffineConstraints ()
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0, ArrayRef< Value > idArgs={})
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0, ArrayRef< Value > idArgs={})
void append (const FlatAffineConstraints &other)
Appends constraints from 'other' into this.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
std::unique_ptr< FlatAffineConstraints > clone () const
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
LogicalResult addAffineForOpDomain (AffineForOp forOp)
Adds constraints (lower and upper bounds) for the specified 'affine.for' operation's Value using IR information stored in its bound maps.
LogicalResult addDomainFromSliceMaps (ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds constraints (lower and upper bounds) for each loop in the loop nest described by the bound maps 'lbMaps' and 'ubMaps' of a computation slice.
void addAffineIfOpDomain (AffineIfOp ifOp)
Adds constraints imposed by the affine.if operation.
LogicalResult addLowerOrUpperBound (unsigned pos, AffineMap boundMap, ValueRange operands, bool eq, bool lower=true)
Adds a lower or an upper bound for the identifier at the specified position with constraints being drawn from the specified bound map and operands.
void getIneqAsAffineValueMap (unsigned pos, unsigned ineqPos, AffineValueMap &vmap, MLIRContext *context) const
Returns the bound for the identifier at pos from the inequality at ineqPos as a 1-d affine value map (affine map + operands).
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps)
Computes the lower and upper bounds of the first 'num' dimensional identifiers (starting at 'offset') as an affine map of the remaining identifiers (dimensional and symbolic).
LogicalResult addSliceBounds (ArrayRef< Value > values, ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds slice lower bounds represented by lower bounds in 'lbMaps' and upper bounds in 'ubMaps' to each identifier in the constraint system which has a value in 'values'.
void addInequality (ArrayRef< int64_t > inEq)
void addEquality (ArrayRef< int64_t > eq)
void addConstantLowerBound (unsigned pos, int64_t lb)
Adds a constant lower bound constraint for the specified identifier.
void addConstantUpperBound (unsigned pos, int64_t ub)
Adds a constant upper bound constraint for the specified identifier.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in 'dividend' and with respect to a positive constant 'divisor'.
void addConstantLowerBound (ArrayRef< int64_t > expr, int64_t lb)
Adds a constant lower bound constraint for the specified expression.
void addConstantUpperBound (ArrayRef< int64_t > expr, int64_t ub)
Adds a constant upper bound constraint for the specified expression.
void setIdToConstant (unsigned pos, int64_t val)
Sets the identifier at the specified position to a constant.
void setIdToConstant (Value id, int64_t val)
Sets the identifier corresponding to the specified Value id to a constant.
bool findId (Value id, unsigned *pos) const
Looks up the position of the identifier with the specified Value.
bool containsId (Value id) const
Returns true if an identifier with the specified Value exists, false otherwise.
void swapId (unsigned posA, unsigned posB)
Swap the posA^th identifier with the posB^th identifier.
void addDimId (unsigned pos, Value id=nullptr)
void addSymbolId (unsigned pos, Value id=nullptr)
void addLocalId (unsigned pos)
void addId (IdKind kind, unsigned pos, Value id=nullptr)
Adds a dimensional identifier.
void addInductionVarOrTerminalSymbol (Value id)
Add the specified values as a dim or symbol id depending on its nature, if it already doesn't exist in the system.
LogicalResult composeMap (const AffineValueMap *vMap)
Composes the affine value map with this FlatAffineConstrains, adding the results of the map as dimensions at the front [0, vMap->getNumResults()) and with the dimensions set to the equalities specified by the value map.
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions match one to one to the dimensions of this FlatAffineConstraints.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) 'num' identifiers starting at position 'pos'.
void projectOut (unsigned pos)
void projectOut (Value id)
Projects out the identifier that is associate with Value .
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
void convertLoopIVSymbolsToDims ()
Changes all symbol identifiers which are loop IVs to dim identifiers.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, 'num' identifiers starting at position 'pos'.
LogicalResult unionBoundingBox (const FlatAffineConstraints &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of 'this' set and that of 'other', with the symbols being treated specially.
bool areIdsAlignedWithOther (const FlatAffineConstraints &other)
Returns 'true' if this constraint system and 'other' are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
void mergeAndAlignIdsWithOther (unsigned offset, FlatAffineConstraints *other)
Merge and align the identifiers of 'this' and 'other' starting at 'offset', so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with this's original identifiers appearing first followed by any of other's identifiers that didn't appear in 'this'.
unsigned getNumConstraints () const
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumLocalIds () const
ArrayRef< Optional< Value > > getIds () const
MutableArrayRef< Optional< Value > > getIds ()
Optional< Value > getId (unsigned pos) const
Returns the optional Value corresponding to the pos^th identifier.
Optional< Value > & getId (unsigned pos)
Value getIdValue (unsigned pos) const
Returns the Value associated with the pos^th identifier.
void getIdValues (unsigned start, unsigned end, SmallVectorImpl< Value > *values) const
Returns the Values associated with identifiers in range [start, end).
void getAllIdValues (SmallVectorImpl< Value > *values) const
void setIdValue (unsigned pos, Value val)
Sets Value associated with the pos^th identifier.
void setIdValues (unsigned start, unsigned end, ArrayRef< Value > values)
Sets Values associated with identifiers in the range [start, end).
void clearAndCopyFrom (const FlatAffineConstraints &other)
Clears this list of constraints and copies other into it.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantLowerBound (unsigned pos) const
Returns the constant lower bound for the pos^th identifier if there is one; None otherwise.
Optional< int64_t > getConstantUpperBound (unsigned pos) const
Returns the constant upper bound for the pos^th identifier if there is one; None otherwise.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient for) for identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check to detect redundant inequalities thatn removeTrivialRedundancy.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void clearConstraints ()
void print (raw_ostream &os) const
void dump () const
Additional Inherited Members
Public Types inherited from mlir::FlatAffineConstraints
enum IdKind { Dimension, Symbol, Local }
Static Public Member Functions inherited from mlir::FlatAffineConstraints
static FlatAffineConstraints getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
Detailed Description
Linalg-specific constraints set extensions.
Definition at line 23 of file ConstraintsSet.h.
Constructor & Destructor Documentation
ConstraintsSet()
mlir::ConstraintsSet::ConstraintsSet () inline
Definition at line 25 of file ConstraintsSet.h.
Member Function Documentation
composeAffineApply()
LogicalResult ConstraintsSet::composeAffineApply (Value val, AffineMap map, ValueRange operands)
Assuming val is defined by val = affine.apply map (operands), call composeMap.
Definition at line 42 of file ConstraintsSet.cpp.
References mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::composeMap(), mlir::failed(), mlir::failure(), mlir::getFlattenedAffineExprs(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), lookupPos(), map(), min(), and mlir::success().
Referenced by composeMax(), and foldUpperBoundsIntoConstraintsSet().
composeMax()
LogicalResult mlir::ConstraintsSet::composeMax (Value val, AffineMap map, ValueRange operands) inline
Assuming val is defined by val = affine.max map (operands), introduce all the constraints val <= expr_i(operands), where expr_i are all the results of map.
Definition at line 39 of file ConstraintsSet.h.
References composeAffineApply(), ensureIdOfType(), lookupPos(), map(), and min().
composeMin()
LogicalResult mlir::ConstraintsSet::composeMin (Value val, AffineMap map, ValueRange operands) inline
Assuming val is defined by val = affine.min map (operands), introduce all the constraints val >= expr_i(operands), where expr_i are all the results of map.
Definition at line 31 of file ConstraintsSet.h.
Referenced by foldUpperBoundsIntoConstraintsSet().
ensureIdOfType()
LogicalResult ConstraintsSet::ensureIdOfType (Value v, bool asDim)
If v is not in the constraint set, insert it as a dim or symbol depending on asDim.
Return success if v is of dim id type when asDim is true and of symbol id type when asDim is false. Return failure otherwise.
Definition at line 28 of file ConstraintsSet.cpp.
References mlir::FlatAffineConstraints::addDimId(), mlir::FlatAffineConstraints::addSymbolId(), mlir::FlatAffineConstraints::containsId(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), lookupPos(), and mlir::success().
Referenced by composeMax(), and foldUpperBoundsIntoConstraintsSet().
lookupPos()
unsigned ConstraintsSet::lookupPos (Value id) const
Asserts the identifier id is in the constraints set and returns it.
Definition at line 19 of file ConstraintsSet.cpp.
References mlir::FlatAffineConstraints::findId().
Referenced by composeAffineApply(), composeMax(), and ensureIdOfType().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/Analysis/ConstraintsSet.h
lib/Dialect/Linalg/Analysis/ConstraintsSet.cpp