MLIR: mlir::detail::DistinctAttributeAllocator Class Reference
mlir::detail::DistinctAttributeAllocator Class Reference final
An allocator for distinct attribute storage instances.
#include "IR/AttributeDetail.h"
Public Member Functions
DistinctAttributeAllocator ()=default
DistinctAttributeAllocator (DistinctAttributeAllocator &&)=delete
DistinctAttributeAllocator (const DistinctAttributeAllocator &)=delete
DistinctAttributeAllocator & operator= (const DistinctAttributeAllocator &)=delete
DistinctAttrStorage * allocate (Attribute referencedAttr)
Detailed Description
An allocator for distinct attribute storage instances.
Uses a synchronized BumpPtrAllocator to ensure thread-safety. The allocated storage is deleted when the DistinctAttributeAllocator is destroyed.
Definition at line 400 of file AttributeDetail.h.
Constructor & Destructor Documentation
DistinctAttributeAllocator() [1/3]
mlir::detail::DistinctAttributeAllocator::DistinctAttributeAllocator () default
Referenced by DistinctAttributeAllocator(), DistinctAttributeAllocator(), and operator=().
DistinctAttributeAllocator() [2/3]
mlir::detail::DistinctAttributeAllocator::DistinctAttributeAllocator (DistinctAttributeAllocator &&) delete
References DistinctAttributeAllocator().
DistinctAttributeAllocator() [3/3]
mlir::detail::DistinctAttributeAllocator::DistinctAttributeAllocator (const DistinctAttributeAllocator &) delete
References DistinctAttributeAllocator().
Member Function Documentation
allocate()
DistinctAttrStorage * mlir::detail::DistinctAttributeAllocator::allocate (Attribute referencedAttr) inline
Definition at line 408 of file AttributeDetail.h.
operator=()
DistinctAttributeAllocator & mlir::detail::DistinctAttributeAllocator::operator= (const DistinctAttributeAllocator &) delete
References DistinctAttributeAllocator().
The documentation for this class was generated from the following file:
lib/IR/AttributeDetail.h