MLIR: mlir::python::PyGlobals::TypeIDAllocator Class Reference
mlir::python::PyGlobals::TypeIDAllocator Class Reference
#include "Bindings/Python/Globals.h"
Public Member Functions
TypeIDAllocator ()
~TypeIDAllocator ()
TypeIDAllocator (const TypeIDAllocator &)=delete
TypeIDAllocator (TypeIDAllocator &&other)
MlirTypeIDAllocator get ()
MlirTypeID allocate ()
Detailed Description
Definition at line 155 of file Globals.h.
Constructor & Destructor Documentation
TypeIDAllocator() [1/3]
mlir::python::PyGlobals::TypeIDAllocator::TypeIDAllocator () inline
Definition at line 157 of file Globals.h.
References mlirTypeIDAllocatorCreate().
Referenced by TypeIDAllocator(), and TypeIDAllocator().
~TypeIDAllocator()
mlir::python::PyGlobals::TypeIDAllocator::~TypeIDAllocator () inline
Definition at line 158 of file Globals.h.
References mlirTypeIDAllocatorDestroy().
TypeIDAllocator() [2/3]
mlir::python::PyGlobals::TypeIDAllocator::TypeIDAllocator (const TypeIDAllocator &) delete
References TypeIDAllocator().
TypeIDAllocator() [3/3]
mlir::python::PyGlobals::TypeIDAllocator::TypeIDAllocator (TypeIDAllocator && other) inline
Definition at line 163 of file Globals.h.
References TypeIDAllocator().
Member Function Documentation
allocate()
MlirTypeID mlir::python::PyGlobals::TypeIDAllocator::allocate () inline
Definition at line 168 of file Globals.h.
References mlirTypeIDAllocatorAllocateTypeID().
get()
MlirTypeIDAllocator mlir::python::PyGlobals::TypeIDAllocator::get () inline
Definition at line 167 of file Globals.h.
The documentation for this class was generated from the following file:
lib/Bindings/Python/Globals.h