MLIR: SpecifierGetterSetterOpConverter< Base, SourceOp > Class Template Reference
SpecifierGetterSetterOpConverter< Base, SourceOp > Class Template Reference
Public Types
using OpAdaptor = typename SourceOp::Adaptor
Public Member Functions
LogicalResult matchAndRewrite (SourceOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Detailed Description
template<typename Base, typename SourceOp>
class SpecifierGetterSetterOpConverter< Base, SourceOp >
Definition at line 234 of file SparseStorageSpecifierToLLVM.cpp.
Member Typedef Documentation
OpAdaptor
template<typename Base, typename SourceOp> using SpecifierGetterSetterOpConverter< Base, SourceOp >::OpAdaptor = typename SourceOp::Adaptor
Definition at line 236 of file SparseStorageSpecifierToLLVM.cpp.
Member Function Documentation
matchAndRewrite()
template<typename Base, typename SourceOp> LogicalResult SpecifierGetterSetterOpConverter< Base, SourceOp >::matchAndRewrite (SourceOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 240 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::sparse_tensor::StorageLayout::getMemRefFieldIndex(), success(), and mlir::sparse_tensor::toFieldKind().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/Transforms/SparseStorageSpecifierToLLVM.cpp