MLIR: mlir::OpPrintingFlags Class Reference
mlir::OpPrintingFlags Class Reference
Set of flags used to control the behavior of the various IR print methods (e.g.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OpPrintingFlags ()
Initialize the printing flags with default supplied by the cl::opts above.
LLVM_DEPRECATED ("Use OpPrintingFlags() instead", "OpPrintingFlags()") OpPrintingFlags(std
OpPrintingFlags & elideLargeElementsAttrs (int64_t largeElementLimit=16)
Enables the elision of large elements attributes by printing a lexically valid but otherwise meaningless form instead of the element data.
OpPrintingFlags & printLargeElementsAttrWithHex (int64_t largeElementLimit=100)
Enables the printing of large element attributes with a hex string.
OpPrintingFlags & elideLargeResourceString (int64_t largeResourceLimit=64)
Enables the elision of large resources strings by omitting them from the dialect_resources section.
OpPrintingFlags & enableDebugInfo (bool enable=true, bool prettyForm=false)
Enable or disable printing of debug information (based on enable).
OpPrintingFlags & printGenericOpForm (bool enable=true)
Always print operations in the generic form.
OpPrintingFlags & skipRegions (bool skip=true)
Skip printing regions.
OpPrintingFlags & assumeVerified (bool enable=true)
Do not verify the operation when using custom operation printers.
OpPrintingFlags & useLocalScope (bool enable=true)
Use local scope when printing the operation.
OpPrintingFlags & printValueUsers (bool enable=true)
Print users of values as comments.
OpPrintingFlags & printUniqueSSAIDs (bool enable=true)
Print unique SSA ID numbers for values, block arguments and naming conflicts across all regions.
OpPrintingFlags & printNameLocAsPrefix (bool enable=true)
Print SSA IDs using their NameLoc, if provided, as prefix.
bool shouldElideElementsAttr (ElementsAttr attr) const
Return if the given ElementsAttr should be elided.
bool shouldPrintElementsAttrWithHex (ElementsAttr attr) const
Return if the given ElementsAttr should be printed as hex string.
std::optional< int64_t > getLargeElementsAttrLimit () const
Return the size limit for printing large ElementsAttr.
int64_t getLargeElementsAttrHexLimit () const
Return the size limit for printing large ElementsAttr as hex string.
std::optional< uint64_t > getLargeResourceStringLimit () const
Return the size limit in chars for printing large resources.
bool shouldPrintDebugInfo () const
Return if debug information should be printed.
bool shouldPrintDebugInfoPrettyForm () const
Return if debug information should be printed in the pretty form.
bool shouldPrintGenericOpForm () const
Return if operations should be printed in the generic form.
bool shouldSkipRegions () const
Return if regions should be skipped.
bool shouldAssumeVerified () const
Return if operation verification should be skipped.
bool shouldUseLocalScope () const
Return if the printer should use local scope when dumping the IR.
bool shouldPrintValueUsers () const
Return if the printer should print users of values.
bool shouldPrintUniqueSSAIDs () const
Return if printer should use unique SSA IDs.
bool shouldUseNameLocAsPrefix () const
Return if the printer should use NameLocs as prefixes when printing SSA IDs.
Detailed Description
Set of flags used to control the behavior of the various IR print methods (e.g.
Operation::Print).
Definition at line 1176 of file OperationSupport.h.
Constructor & Destructor Documentation
OpPrintingFlags()
OpPrintingFlags::OpPrintingFlags ()
Initialize the printing flags with default supplied by the cl::opts above.
Definition at line 217 of file AsmPrinter.cpp.
References clOptions, false, and if().
Referenced by assumeVerified(), enableDebugInfo(), LLVM_DEPRECATED(), printGenericOpForm(), printNameLocAsPrefix(), printUniqueSSAIDs(), printValueUsers(), skipRegions(), and useLocalScope().
Member Function Documentation
assumeVerified()
OpPrintingFlags & OpPrintingFlags::assumeVerified (bool enable = true)
Do not verify the operation when using custom operation printers.
Definition at line 288 of file AsmPrinter.cpp.
References OpPrintingFlags().
elideLargeElementsAttrs()
OpPrintingFlags & OpPrintingFlags::elideLargeElementsAttrs (int64_t largeElementLimit = 16)
Enables the elision of large elements attributes by printing a lexically valid but otherwise meaningless form instead of the element data.
Enable the elision of large elements attributes, by printing a '...' instead of the element data, when the number of elements is greater than largeElementLimit.
The largeElementLimit is used to configure what is considered to be a "large" ElementsAttr by providing an upper limit to the number of elements.
Note: The IR generated with this option is not parsable.
Definition at line 249 of file AsmPrinter.cpp.
Referenced by adjustPrintingFlags().
elideLargeResourceString()
OpPrintingFlags & OpPrintingFlags::elideLargeResourceString (int64_t largeResourceLimit = 64)
Enables the elision of large resources strings by omitting them from the dialect_resources section.
The largeResourceLimit is used to configure what is considered to be a "large" resource by providing an upper limit to the string size.
Definition at line 261 of file AsmPrinter.cpp.
enableDebugInfo()
OpPrintingFlags & OpPrintingFlags::enableDebugInfo (bool enable = true, bool prettyForm = false)
Enable or disable printing of debug information (based on enable).
Enable printing of debug information.
If 'prettyForm' is set to true, debug information is printed in a more readable 'pretty' form. Note: The IR generated with 'prettyForm' is not parsable.
If 'prettyForm' is set to true, debug information is printed in a more readable 'pretty' form.
Definition at line 268 of file AsmPrinter.cpp.
References OpPrintingFlags().
getLargeElementsAttrHexLimit()
int64_t OpPrintingFlags::getLargeElementsAttrHexLimit () const
Return the size limit for printing large ElementsAttr as hex string.
Definition at line 340 of file AsmPrinter.cpp.
getLargeElementsAttrLimit()
std::optional< int64_t > OpPrintingFlags::getLargeElementsAttrLimit () const
Return the size limit for printing large ElementsAttr.
Definition at line 335 of file AsmPrinter.cpp.
getLargeResourceStringLimit()
std::optional< uint64_t > OpPrintingFlags::getLargeResourceStringLimit () const
Return the size limit in chars for printing large resources.
Return the size limit for printing large ElementsAttr.
Definition at line 345 of file AsmPrinter.cpp.
LLVM_DEPRECATED()
mlir::OpPrintingFlags::LLVM_DEPRECATED ("Use OpPrintingFlags() instead" , "OpPrintingFlags()") inline
Definition at line 1179 of file OperationSupport.h.
References OpPrintingFlags().
printGenericOpForm()
OpPrintingFlags & OpPrintingFlags::printGenericOpForm (bool enable = true)
Always print operations in the generic form.
Definition at line 276 of file AsmPrinter.cpp.
References OpPrintingFlags().
Referenced by adjustPrintingFlags().
printLargeElementsAttrWithHex()
OpPrintingFlags & OpPrintingFlags::printLargeElementsAttrWithHex (int64_t largeElementLimit = 100)
Enables the printing of large element attributes with a hex string.
The largeElementLimit is used to configure what is considered to be a "large" ElementsAttr by providing an upper limit to the number of elements. Use -1 to disable the hex printing.
Definition at line 255 of file AsmPrinter.cpp.
printNameLocAsPrefix()
OpPrintingFlags & OpPrintingFlags::printNameLocAsPrefix (bool enable = true)
Print SSA IDs using their NameLoc, if provided, as prefix.
Definition at line 329 of file AsmPrinter.cpp.
References OpPrintingFlags().
printUniqueSSAIDs()
OpPrintingFlags & OpPrintingFlags::printUniqueSSAIDs (bool enable = true)
Print unique SSA ID numbers for values, block arguments and naming conflicts across all regions.
Definition at line 309 of file AsmPrinter.cpp.
References OpPrintingFlags().
printValueUsers()
OpPrintingFlags & OpPrintingFlags::printValueUsers (bool enable = true)
Print users of values as comments.
Definition at line 302 of file AsmPrinter.cpp.
References OpPrintingFlags().
shouldAssumeVerified()
bool OpPrintingFlags::shouldAssumeVerified () const
Return if operation verification should be skipped.
Definition at line 368 of file AsmPrinter.cpp.
Referenced by verifyOpAndAdjustFlags().
shouldElideElementsAttr()
bool OpPrintingFlags::shouldElideElementsAttr (ElementsAttr attr) const
Return if the given ElementsAttr should be elided.
Definition at line 315 of file AsmPrinter.cpp.
shouldPrintDebugInfo()
bool OpPrintingFlags::shouldPrintDebugInfo () const
Return if debug information should be printed.
Definition at line 350 of file AsmPrinter.cpp.
shouldPrintDebugInfoPrettyForm()
bool OpPrintingFlags::shouldPrintDebugInfoPrettyForm () const
Return if debug information should be printed in the pretty form.
Definition at line 355 of file AsmPrinter.cpp.
shouldPrintElementsAttrWithHex()
bool OpPrintingFlags::shouldPrintElementsAttrWithHex (ElementsAttr attr) const
Return if the given ElementsAttr should be printed as hex string.
Definition at line 322 of file AsmPrinter.cpp.
shouldPrintGenericOpForm()
bool OpPrintingFlags::shouldPrintGenericOpForm () const
Return if operations should be printed in the generic form.
Definition at line 360 of file AsmPrinter.cpp.
Referenced by shouldPrintUniqueSSAIDs(), and verifyOpAndAdjustFlags().
shouldPrintUniqueSSAIDs()
bool OpPrintingFlags::shouldPrintUniqueSSAIDs () const
Return if printer should use unique SSA IDs.
Return if the printer should use unique IDs.
Definition at line 381 of file AsmPrinter.cpp.
References shouldPrintGenericOpForm().
shouldPrintValueUsers()
bool OpPrintingFlags::shouldPrintValueUsers () const
Return if the printer should print users of values.
Definition at line 376 of file AsmPrinter.cpp.
shouldSkipRegions()
bool OpPrintingFlags::shouldSkipRegions () const
Return if regions should be skipped.
Return if Region should be skipped.
Definition at line 365 of file AsmPrinter.cpp.
Referenced by printBlock().
shouldUseLocalScope()
bool OpPrintingFlags::shouldUseLocalScope () const
Return if the printer should use local scope when dumping the IR.
Definition at line 373 of file AsmPrinter.cpp.
Referenced by mlir::Operation::print(), mlir::Operation::print(), and mlir::Value::printAsOperand().
shouldUseNameLocAsPrefix()
bool OpPrintingFlags::shouldUseNameLocAsPrefix () const
Return if the printer should use NameLocs as prefixes when printing SSA IDs.
Definition at line 386 of file AsmPrinter.cpp.
skipRegions()
OpPrintingFlags & OpPrintingFlags::skipRegions (bool skip = true)
Skip printing regions.
Always skip Regions.
Definition at line 282 of file AsmPrinter.cpp.
References OpPrintingFlags().
Referenced by printBlock().
useLocalScope()
OpPrintingFlags & OpPrintingFlags::useLocalScope (bool enable = true)
Use local scope when printing the operation.
This allows for using the printer in a more localized and thread-safe setting, but may not necessarily be identical to what the IR will look like when dumping the full module.
This allows for using the printer in a more localized and thread-safe setting, but may not necessarily be identical of what the IR will look like when dumping the full module.
Definition at line 296 of file AsmPrinter.cpp.
References OpPrintingFlags().
Referenced by adjustPrintingFlags(), mlir::OpWithFlags::operator<<, and printIR().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/AsmPrinter.cpp