MLIR: mlir::MutableOperandRangeRange Class Reference
mlir::MutableOperandRangeRange Class Reference final
This class represents a contiguous range of mutable operand ranges, e.g.
#include "mlir/IR/ValueRange.h"
Public Member Functions
MutableOperandRangeRange (const MutableOperandRange &operands, NamedAttribute operandSegmentAttr)
Construct a range given a parent set of operands, and an I32 tensor elements attribute containing the sizes of the sub ranges.
MutableOperandRange join () const
Flatten all of the sub ranges into a single contiguous mutable operand range.
operator OperandRangeRange () const
Allow implicit conversion to an OperandRangeRange.
Detailed Description
This class represents a contiguous range of mutable operand ranges, e.g.
from a VariadicOfVariadic operand group.
Definition at line 206 of file ValueRange.h.
Constructor & Destructor Documentation
MutableOperandRangeRange()
MutableOperandRangeRange::MutableOperandRangeRange (const MutableOperandRange & operands, NamedAttribute operandSegmentAttr)
Construct a range given a parent set of operands, and an I32 tensor elements attribute containing the sizes of the sub ranges.
Definition at line 547 of file OperationSupport.cpp.
References MutableOperandRangeRange().
Referenced by MutableOperandRangeRange().
Member Function Documentation
join()
MutableOperandRange MutableOperandRangeRange::join () const
Flatten all of the sub ranges into a single contiguous mutable operand range.
Definition at line 554 of file OperationSupport.cpp.
References getBase().
operator OperandRangeRange()
MutableOperandRangeRange::operator OperandRangeRange () const
Allow implicit conversion to an OperandRangeRange.
Definition at line 558 of file OperationSupport.cpp.
References getBase().
The documentation for this class was generated from the following files:
include/mlir/IR/ValueRange.h
lib/IR/OperationSupport.cpp