MLIR: mlir::ContractionOpToOuterProductOpLowering Class Reference
mlir::ContractionOpToOuterProductOpLowering Class Reference
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintType = std::function< LogicalResult(vector::ContractionOp op)>
Public Member Functions
ContractionOpToOuterProductOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext *context, FilterConstraintType constraint=defaultFilter)
LogicalResult matchAndRewrite (vector::ContractionOp op, PatternRewriter &rewriter) const override
Progressively lower a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
Public Member Functions inherited from mlir::OpRewritePattern< vector::ContractionOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (vector::ContractionOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (vector::ContractionOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Static Public Member Functions
static LogicalResult defaultFilter (vector::ContractionOp op)
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&... args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Additional Inherited Members
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
bRowK = vector.extract b[K] atRowK = vector.extract at[K] cK = vector.outerproduct atRowK, bRowK, cK-1 ```
This only kicks in when VectorTransformsOptions is set to OuterProduct and the vector.contract op is a row-major matrix multiply.
Definition at line 250 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintType
using mlir::ContractionOpToOuterProductOpLowering::FilterConstraintType = std::function<LogicalResult(vector::ContractionOp op)>
Definition at line 255 of file VectorTransforms.h.
Constructor & Destructor Documentation
ContractionOpToOuterProductOpLowering()
mlir::ContractionOpToOuterProductOpLowering::ContractionOpToOuterProductOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext * context, FilterConstraintType constraint = defaultFilter) inline
Definition at line 261 of file VectorTransforms.h.
References op, and rewriter.
Member Function Documentation
defaultFilter()
static LogicalResult mlir::ContractionOpToOuterProductOpLowering::defaultFilter (vector::ContractionOp op) inline static
Definition at line 257 of file VectorTransforms.h.
References mlir::success().
matchAndRewrite()
LogicalResult mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite (vector::ContractionOp op, PatternRewriter & rewriter) const override virtual
Progressively lower a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
bRowK = vector.extract b[K] atRowK = vector.extract at[K] cK = vector.outerproduct atRowK, bRowK, cK-1 ```
This only kicks in when VectorTransformsOptions is set to OuterProduct but otherwise supports any layout permutation of the matrix-multiply.
Reimplemented from mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >.
Definition at line 1322 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::failed(), mlir::failure(), mlir::Builder::getContext(), and mlir::vector::OuterProduct.
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Vector/VectorTransforms.h
lib/Dialect/Vector/VectorTransforms.cpp