MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T > Class Template Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T > Class Template Reference
Template for a reference to a concrete type which captures a python reference to its underlying python object.
#include "mlir/Bindings/Python/IRCore.h"
Public Types
using NBTypedT = nanobind::typed<nanobind::object, T>
Public Member Functions
PyObjectRef (T *referrent, nanobind::object object)
PyObjectRef (PyObjectRef &&other) noexcept
PyObjectRef (const PyObjectRef &other)
PyObjectRef & operator= (const PyObjectRef &other)
PyObjectRef & operator= (PyObjectRef &&other) noexcept
~PyObjectRef ()=default
int getRefCount ()
nanobind::object releaseObject ()
Releases the object held by this instance, returning it.
T * get ()
T * operator-> ()
nanobind::object getObject ()
operator bool () const
Detailed Description
template<typename T>
class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >
Template for a reference to a concrete type which captures a python reference to its underlying python object.
Definition at line 66 of file IRCore.h.
Member Typedef Documentation
NBTypedT
template<typename T> using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::NBTypedT = nanobind::typed<nanobind::object, T>
Definition at line 122 of file IRCore.h.
Constructor & Destructor Documentation
PyObjectRef() [1/3]
template<typename T> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::PyObjectRef (T * referrent, nanobind::object object) inline
Definition at line 68 of file IRCore.h.
PyObjectRef() [2/3]
template<typename T> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::PyObjectRef (PyObjectRef< T > && other) inline noexcept
Definition at line 74 of file IRCore.h.
PyObjectRef() [3/3]
template<typename T> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::PyObjectRef (const PyObjectRef< T > & other) inline
Definition at line 79 of file IRCore.h.
~PyObjectRef()
template<typename T> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::~PyObjectRef () default
Member Function Documentation
get()
template<typename T> T * mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::get () inline
Definition at line 111 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getObject()
template<typename T> nanobind::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::getObject () inline
Definition at line 116 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getRefCount()
template<typename T> int mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::getRefCount () inline
Definition at line 95 of file IRCore.h.
operator bool()
template<typename T> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::operator bool () const inline
Definition at line 120 of file IRCore.h.
operator->()
template<typename T> T * mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::operator-> () inline
Definition at line 112 of file IRCore.h.
operator=() [1/2]
template<typename T> PyObjectRef & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::operator= (const PyObjectRef< T > & other) inline
Definition at line 81 of file IRCore.h.
operator=() [2/2]
template<typename T> PyObjectRef & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::operator= (PyObjectRef< T > && other) inline noexcept
Definition at line 86 of file IRCore.h.
releaseObject()
template<typename T> nanobind::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::releaseObject () inline
Releases the object held by this instance, returning it.
This is the proper thing to return from a function that wants to return the reference. Note that this does not work from initializers.
Definition at line 104 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/IRCore.h