MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyConcreteLocation ()=default
PyConcreteLocation (PyMlirContextRef contextRef, MlirLocation loc)
PyConcreteLocation (PyLocation &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyCallSiteLocation >
PyConcreteLocation ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation
PyLocation (PyMlirContextRef contextRef, MlirLocation loc)
operator MlirLocation () const
MlirLocation get () const
void contextExit (const nanobind::object &excType, const nanobind::object &excVal, const nanobind::object &excTb)
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirLocation.
nanobind::typed< nanobind::object, PyLocation > maybeDownCast ()
Returns the most-derived Location subclass registered for this TypeID, or self.
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyCallSiteLocation >
static MlirLocation castFrom (PyLocation &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation
static nanobind::object contextEnter (nanobind::object location)
Enter and exit the context manager.
static PyLocation createFromCapsule (nanobind::object capsule)
Creates a PyLocation from the MlirLocation wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirLocationIsACallSite
static constexpr const char * pyClassName = "CallSiteLoc"
static constexpr GetTypeIDFunctionTy getTypeIdFunction
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyCallSiteLocation >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyCallSiteLocation >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Detailed Description
Definition at line 1272 of file IRCore.h.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::bindDerived (ClassTy & c) static
Definition at line 3173 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirLocationCallSiteGet(), mlirLocationCallSiteGetCallee(), mlirLocationCallSiteGetCaller(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::PyLocation().
PyConcreteLocation() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::PyConcreteLocation () default
PyConcreteLocation() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::PyConcreteLocation (PyLocation & orig) inline
Definition at line 1188 of file IRCore.h.
PyConcreteLocation() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::PyConcreteLocation (PyMlirContextRef contextRef, MlirLocation loc) inline
Definition at line 1186 of file IRCore.h.
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::getTypeIdFunction static constexpr
Initial value:
=
      mlirLocationCallSiteGetTypeID
Definition at line 1278 of file IRCore.h.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::isaFunction = mlirLocationIsACallSite static constexpr
Definition at line 1275 of file IRCore.h.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::pyClassName = "CallSiteLoc" static constexpr
Definition at line 1276 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp