MLIR: mlir::FloatType Class Reference
mlir::FloatType Class Reference
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
unsigned getWidth ()
Return the bitwidth of this float type.
FloatType scaleElementBitwidth (unsigned scale)
Get or create a new FloatType with bitwidth scaled by scale.
const llvm::fltSemantics & getFloatSemantics ()
Return the floating semantics of this float type.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractTy & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static FloatType getBF16 (MLIRContext *ctx)
static FloatType getF16 (MLIRContext *ctx)
static FloatType getF32 (MLIRContext *ctx)
static FloatType getF64 (MLIRContext *ctx)
static FloatType getF80 (MLIRContext *ctx)
static FloatType getF128 (MLIRContext *ctx)
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
Definition at line 31 of file BuiltinTypes.h.
Member Function Documentation
classof()
bool mlir::FloatType::classof (Type type) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 279 of file BuiltinTypes.h.
References mlir::Type::isa().
getBF16()
FloatType mlir::FloatType::getBF16 (MLIRContext * ctx) inline static
Definition at line 284 of file BuiltinTypes.h.
Referenced by mlir::Builder::getBF16Type(), and mlirBF16TypeGet().
getF128()
FloatType mlir::FloatType::getF128 (MLIRContext * ctx) inline static
Definition at line 304 of file BuiltinTypes.h.
Referenced by mlir::Builder::getF128Type().
getF16()
FloatType mlir::FloatType::getF16 (MLIRContext * ctx) inline static
Definition at line 288 of file BuiltinTypes.h.
Referenced by mlir::Builder::getF16Type(), mlirF16TypeGet(), verify(), and verifyWMMALoadOp().
getF32()
FloatType mlir::FloatType::getF32 (MLIRContext * ctx) inline static
Definition at line 292 of file BuiltinTypes.h.
Referenced by diag(), mlir::Builder::getF32Type(), mlirF32TypeGet(), scaleElementBitwidth(), verify(), and verifyWMMALoadOp().
getF64()
FloatType mlir::FloatType::getF64 (MLIRContext * ctx) inline static
Definition at line 296 of file BuiltinTypes.h.
Referenced by diag(), mlir::Builder::getF64Type(), mlirF64TypeGet(), and scaleElementBitwidth().
getF80()
FloatType mlir::FloatType::getF80 (MLIRContext * ctx) inline static
Definition at line 300 of file BuiltinTypes.h.
Referenced by mlir::Builder::getF80Type().
getFloatSemantics()
const llvm::fltSemantics & FloatType::getFloatSemantics ()
Return the floating semantics of this float type.
Returns the floating semantics for the given type.
Definition at line 112 of file BuiltinTypes.cpp.
Referenced by convolutionMatchAndRewriterHelper(), createInitialValueForReduceOp(), findDuplicateElement(), mlir::DenseElementsAttr::AttributeElementIterator::operator*(), and parseElementAttrHexValues().
getWidth()
unsigned FloatType::getWidth ()
Return the bitwidth of this float type.
Definition at line 97 of file BuiltinTypes.cpp.
Referenced by parseElementAttrHexValues().
scaleElementBitwidth()
FloatType FloatType::scaleElementBitwidth (unsigned scale)
Get or create a new FloatType with bitwidth scaled by scale.
Return null if the scaled element type cannot be represented.
Definition at line 128 of file BuiltinTypes.cpp.
References getF32(), getF64(), and isF32().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp