MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyAffineMap (PyMlirContextRef contextRef, MlirAffineMap affineMap)
bool operator== (const PyAffineMap &other) const
operator MlirAffineMap () const
MlirAffineMap get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineMap.
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyAffineMap createFromCapsule (const nanobind::object &capsule)
Creates a PyAffineMap from the MlirAffineMap wrapped by a capsule.
Detailed Description
Definition at line 1365 of file IRCore.h.
Constructor & Destructor Documentation
PyAffineMap()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap::PyAffineMap (PyMlirContextRef contextRef, MlirAffineMap affineMap) inline
Definition at line 1367 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject().
Referenced by createFromCapsule(), and operator==().
Member Function Documentation
createFromCapsule()
PyAffineMap PyAffineMap::createFromCapsule (const nanobind::object & capsule) static
Creates a PyAffineMap from the MlirAffineMap wrapped by a capsule.
Note that PyAffineMap instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirAffineMap is taken by calling this function.
Definition at line 443 of file IRAffine.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlirAffineMapGetContext(), mlirAffineMapIsNull(), mlirPythonCapsuleToAffineMap(), and PyAffineMap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
get()
MlirAffineMap mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap::get () const inline
Definition at line 1371 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMapAttribute::bindDerived().
getCapsule()
nb::object PyAffineMap::getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineMap.
Definition at line 439 of file IRAffine.cpp.
References mlirPythonAffineMapToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
operator MlirAffineMap()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap::operator MlirAffineMap () const inline
Definition at line 1370 of file IRCore.h.
operator==()
bool PyAffineMap::operator== (const PyAffineMap & other) const
Definition at line 435 of file IRAffine.cpp.
References mlirAffineMapEqual(), and PyAffineMap().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRAffine.cpp