MLIR: mlir::python::DefaultingPyMlirContext Class Reference
mlir::python::DefaultingPyMlirContext Class Reference
Used in function arguments when None should resolve to the current context manager set instance.
#include "Bindings/Python/IRModule.h"
Public Member Functions
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting (ReferrentTy &referrent)
Public Member Functions inherited from mlir::python::Defaulting< DefaultingPyMlirContext, PyMlirContext >
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting (ReferrentTy &referrent)
ReferrentTy * get () const
ReferrentTy * operator-> ()
Static Public Member Functions
static PyMlirContext & resolve ()
Static Public Attributes
static constexpr const char kTypeDescription [] = "mlir.ir.Context"
Additional Inherited Members
Public Types inherited from mlir::python::Defaulting< DefaultingPyMlirContext, PyMlirContext >
using ReferrentTy = PyMlirContext
Detailed Description
Used in function arguments when None should resolve to the current context manager set instance.
Definition at line 319 of file IRModule.h.
Member Function Documentation
Defaulting() [1/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting() [2/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting inline
Definition at line 58 of file NanobindUtils.h.
resolve()
PyMlirContext & DefaultingPyMlirContext::resolve () static
Definition at line 860 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::getDefaultContext().
Referenced by mlir::python::PyInferShapedTypeOpInterface::inferReturnTypeComponents(), mlir::python::PyInferTypeOpInterface::inferReturnTypes(), and mlir::python::PyConcreteOpInterface< ConcreteIface >::PyConcreteOpInterface().
Member Data Documentation
kTypeDescription
constexpr const char mlir::python::DefaultingPyMlirContext::kTypeDescription[] = "mlir.ir.Context" static constexpr
Definition at line 323 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp