MLIR: mlir::pdll::ast::CallExpr Class Reference
mlir::pdll::ast::CallExpr Class Reference final
This expression represents a call to a decl, such as a UserConstraintDecl/UserRewriteDecl.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
Expr * getCallableExpr () const
Return the callable of this call.
MutableArrayRef< Expr * > getArguments ()
Return the arguments of this call.
ArrayRef< Expr * > getArguments () const
bool getIsNegated () const
Returns whether the result of this call is to be negated.
Public Member Functions inherited from mlir::pdll::ast::Expr
Type getType () const
Return the type of this expression.
Public Member Functions inherited from mlir::pdll::ast::Stmt
Node (TypeID typeID, SMRange loc)
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT, typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static CallExpr * create (Context &ctx, SMRange loc, Expr *callable, ArrayRef< Expr * > arguments, Type resultType, bool isNegated=false)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< CallExpr, Expr >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Expr
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Stmt
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< CallExpr, Expr >
using Base
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< CallExpr, Expr >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Expr
Expr (TypeID typeID, SMRange loc, Type type)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This expression represents a call to a decl, such as a UserConstraintDecl/UserRewriteDecl.
Definition at line 392 of file Nodes.h.
Member Function Documentation
create()
CallExpr * CallExpr::create (Context & ctx, SMRange loc, Expr * callable, ArrayRef< Expr * > arguments, Type resultType, bool isNegated = false) static
Definition at line 269 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator(), and getArguments().
getArguments() [1/2]
MutableArrayRef< Expr * > mlir::pdll::ast::CallExpr::getArguments () inline
Return the arguments of this call.
Definition at line 403 of file Nodes.h.
Referenced by create().
getArguments() [2/2]
ArrayRef< Expr * > mlir::pdll::ast::CallExpr::getArguments () const inline
Definition at line 404 of file Nodes.h.
getCallableExpr()
Expr * mlir::pdll::ast::CallExpr::getCallableExpr () const inline
Return the callable of this call.
Definition at line 400 of file Nodes.h.
getIsNegated()
bool mlir::pdll::ast::CallExpr::getIsNegated () const inline
Returns whether the result of this call is to be negated.
Definition at line 407 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp