MLIR: mlir::detail::OperandStorage Class Reference
mlir::detail::OperandStorage Class Reference final
This class handles the management of operation operands.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OperandStorage (Operation *owner, ValueRange values)
~OperandStorage ()
void setOperands (Operation *owner, ValueRange values)
Replace the operands contained in the storage with the ones provided in 'values'.
void setOperands (Operation *owner, unsigned start, unsigned length, ValueRange operands)
Replace the operands beginning at 'start' and ending at 'start' + 'length' with the ones provided in 'operands'.
void eraseOperands (unsigned start, unsigned length)
Erase the operands held by the storage within the given range.
void eraseOperands (const llvm::BitVector &eraseIndices)
Erase the operands held by the storage that have their corresponding bit set in eraseIndices.
MutableArrayRef< OpOperand > getOperands ()
Get the operation operands held by the storage.
unsigned size ()
Return the number of operands held in the storage.
Static Public Member Functions
static size_t additionalAllocSize (unsigned numOperands)
Returns the additional size necessary for allocating this object.
Detailed Description
This class handles the management of operation operands.
Operands are stored either in a trailing array, or a dynamically resizable vector.
Definition at line 557 of file OperationSupport.h.
Constructor & Destructor Documentation
OperandStorage()
detail::OperandStorage::OperandStorage (Operation * owner, ValueRange values)
Definition at line 226 of file OperationSupport.cpp.
References mlir::detail::TrailingOperandStorage::capacity, inlineStorage, and mlir::detail::TrailingOperandStorage::numOperands.
~OperandStorage()
detail::OperandStorage::~OperandStorage ()
Definition at line 235 of file OperationSupport.cpp.
References mlir::detail::TrailingOperandStorage::~TrailingOperandStorage().
Member Function Documentation
additionalAllocSize()
static size_t mlir::detail::OperandStorage::additionalAllocSize (unsigned numOperands) inline static
Returns the additional size necessary for allocating this object.
Definition at line 589 of file OperationSupport.h.
Referenced by mlir::Operation::create().
eraseOperands() [1/2]
void detail::OperandStorage::eraseOperands (unsigned start, unsigned length)
Erase the operands held by the storage within the given range.
Erase an operand held by the storage.
Definition at line 290 of file OperationSupport.cpp.
References mlir::detail::TrailingOperandStorage::getOperands(), and mlir::detail::TrailingOperandStorage::numOperands.
Referenced by mlir::Operation::eraseOperands(), and setOperands().
eraseOperands() [2/2]
void detail::OperandStorage::eraseOperands (const llvm::BitVector & eraseIndices)
Erase the operands held by the storage that have their corresponding bit set in eraseIndices.
Definition at line 305 of file OperationSupport.cpp.
References mlir::detail::TrailingOperandStorage::capacity, dynamicStorage, mlir::detail::TrailingOperandStorage::getOperands(), max(), and mlir::detail::TrailingOperandStorage::numOperands.
getOperands()
MutableArrayRef<OpOperand> mlir::detail::OperandStorage::getOperands () inline
Get the operation operands held by the storage.
Definition at line 581 of file OperationSupport.h.
Referenced by mlir::Operation::getOpOperands(), and setOperands().
setOperands() [1/2]
void detail::OperandStorage::setOperands (Operation * owner, ValueRange values)
Replace the operands contained in the storage with the ones provided in 'values'.
Definition at line 250 of file OperationSupport.cpp.
Referenced by setOperands().
setOperands() [2/2]
void detail::OperandStorage::setOperands (Operation * owner, unsigned start, unsigned length, ValueRange operands)
Replace the operands beginning at 'start' and ending at 'start' + 'length' with the ones provided in 'operands'.
'operands' may be smaller or larger than the range pointed to by 'start'+'length'.
Definition at line 259 of file OperationSupport.cpp.
References eraseOperands(), getOperands(), setOperands(), and size().
size()
unsigned mlir::detail::OperandStorage::size () inline
Return the number of operands held in the storage.
Definition at line 586 of file OperationSupport.h.
Referenced by mlir::Operation::getNumOperands(), and setOperands().
Member Data Documentation
dynamicStorage
llvm::PointerIntPair<TrailingOperandStorage *, 1, bool, StoragePointerLikeTypeTraits> mlir::detail::OperandStorage::dynamicStorage
Definition at line 632 of file OperationSupport.h.
Referenced by eraseOperands().
inlineStorage
TrailingOperandStorage mlir::detail::OperandStorage::inlineStorage
Definition at line 629 of file OperationSupport.h.
Referenced by OperandStorage().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp