MLIR: mlir::remark::detail::RemarkEngine Class Reference
mlir::remark::detail::RemarkEngine Class Reference
#include "mlir/IR/Remarks.h"
Public Member Functions
RemarkEngine ()=delete
Default constructor is deleted, use the other constructor.
RemarkEngine (bool printAsEmitRemarks, const RemarkCategories &cats)
Constructs Remark engine with optional category names.
~RemarkEngine ()
Destructor that will close the output file and reset the main remark streamer.
LogicalResult initialize (std::unique_ptr< MLIRRemarkStreamerBase > streamer, std::unique_ptr< RemarkEmittingPolicyBase > remarkEmittingPolicy, std::string *errMsg)
Setup the remark engine with the given output path and format.
RemarkEmittingPolicyBase * getRemarkEmittingPolicy () const
Get the remark emitting policy.
void report (const Remark &&remark)
Report a remark.
InFlightRemark emitOptimizationRemark (Location loc, RemarkOpts opts)
Report a successful remark, this will create an InFlightRemark that can be used to build the remark using the << operator.
InFlightRemark emitOptimizationRemarkMiss (Location loc, RemarkOpts opts)
Report a missed optimization remark that can be used to build the remark using the << operator.
InFlightRemark emitOptimizationRemarkFailure (Location loc, RemarkOpts opts)
Report a failed optimization remark, this will create an InFlightRemark that can be used to build the remark using the << operator.
InFlightRemark emitOptimizationRemarkAnalysis (Location loc, RemarkOpts opts)
Report an analysis remark, this will create an InFlightRemark that can be used to build the remark using the << operator.
Detailed Description
Definition at line 376 of file Remarks.h.
Constructor & Destructor Documentation
RemarkEngine() [1/2]
mlir::remark::detail::RemarkEngine::RemarkEngine () delete
Default constructor is deleted, use the other constructor.
RemarkEngine() [2/2]
RemarkEngine::RemarkEngine (bool printAsEmitRemarks, const RemarkCategories & cats)
Constructs Remark engine with optional category names.
If a category name is not provided, it is not enabled. The category names are used to filter the remarks that are emitted.
Definition at line 312 of file Remarks.cpp.
References mlir::remark::RemarkCategories::analysis, buildFilter(), mlir::remark::RemarkCategories::failed, if(), mlir::remark::RemarkCategories::missed, and mlir::remark::RemarkCategories::passed.
~RemarkEngine()
RemarkEngine::~RemarkEngine ()
Destructor that will close the output file and reset the main remark streamer.
Definition at line 250 of file Remarks.cpp.
Member Function Documentation
emitOptimizationRemark()
InFlightRemark RemarkEngine::emitOptimizationRemark (Location loc, RemarkOpts opts)
Report a successful remark, this will create an InFlightRemark that can be used to build the remark using the << operator.
Definition at line 206 of file Remarks.cpp.
References mlir::remark::detail::Remark::loc.
Referenced by mlir::remark::passed().
emitOptimizationRemarkAnalysis()
InFlightRemark RemarkEngine::emitOptimizationRemarkAnalysis (Location loc, RemarkOpts opts)
Report an analysis remark, this will create an InFlightRemark that can be used to build the remark using the << operator.
Definition at line 224 of file Remarks.cpp.
References mlir::remark::detail::Remark::loc.
Referenced by mlir::remark::analysis().
emitOptimizationRemarkFailure()
InFlightRemark RemarkEngine::emitOptimizationRemarkFailure (Location loc, RemarkOpts opts)
Report a failed optimization remark, this will create an InFlightRemark that can be used to build the remark using the << operator.
Definition at line 218 of file Remarks.cpp.
References mlir::remark::detail::Remark::loc.
Referenced by mlir::remark::failed().
emitOptimizationRemarkMiss()
InFlightRemark RemarkEngine::emitOptimizationRemarkMiss (Location loc, RemarkOpts opts)
Report a missed optimization remark that can be used to build the remark using the << operator.
Definition at line 212 of file Remarks.cpp.
References mlir::remark::detail::Remark::loc.
Referenced by mlir::remark::missed().
getRemarkEmittingPolicy()
RemarkEmittingPolicyBase * mlir::remark::detail::RemarkEngine::getRemarkEmittingPolicy () const inline
Get the remark emitting policy.
Definition at line 451 of file Remarks.h.
initialize()
llvm::LogicalResult RemarkEngine::initialize (std::unique_ptr< MLIRRemarkStreamerBase > streamer, std::unique_ptr< RemarkEmittingPolicyBase > remarkEmittingPolicy, std::string * errMsg)
Setup the remark engine with the given output path and format.
Definition at line 258 of file Remarks.cpp.
References success().
report()
void RemarkEngine::report (const Remark && remark)
Report a remark.
Definition at line 245 of file Remarks.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/Remarks.h
lib/IR/Remarks.cpp