MLIR: mlir::PassInfo Class Reference
mlir::PassInfo Class Reference
A structure to represent the information for a derived pass class.
#include "mlir/Pass/PassRegistry.h"
Public Member Functions
PassInfo (StringRef arg, StringRef description, const PassAllocatorFunction &allocator)
PassInfo constructor should not be invoked directly, instead use PassRegistration or registerPass.
Public Member Functions inherited from mlir::PassRegistryEntry
LogicalResult addToPipeline (OpPassManager &pm, StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler) const
Adds this pass registry entry to the given pass manager.
StringRef getPassArgument () const
Returns the command line option that may be passed to 'mlir-opt' that will cause this pass to run or null if there is no such argument.
StringRef getPassDescription () const
Returns a description for the pass, this never returns null.
void printHelpStr (size_t indent, size_t descIndent) const
Print the help information for this pass.
size_t getOptionWidth () const
Return the maximum width required when printing the options of this entry.
Static Public Member Functions
static const PassInfo * lookup (StringRef passArg)
Returns the pass info for the specified pass class or null if unknown.
Additional Inherited Members
Protected Member Functions inherited from mlir::PassRegistryEntry
PassRegistryEntry (StringRef arg, StringRef description, const PassRegistryFunction &builder, std::function< void(function_ref< void(const detail::PassOptions &)>)> optHandler)
Detailed Description
A structure to represent the information for a derived pass class.
Definition at line 118 of file PassRegistry.h.
Constructor & Destructor Documentation
PassInfo()
PassInfo::PassInfo (StringRef arg, StringRef description, const PassAllocatorFunction & allocator)
PassInfo constructor should not be invoked directly, instead use PassRegistration or registerPass.
Definition at line 140 of file PassRegistry.cpp.
References buildDefaultRegistryFn(), and mlir::PassRegistryEntry::PassRegistryEntry().
Referenced by lookup().
Member Function Documentation
lookup()
const PassInfo * mlir::PassInfo::lookup (StringRef passArg) static
Returns the pass info for the specified pass class or null if unknown.
Returns the pass info for the specified pass argument or null if unknown.
Definition at line 172 of file PassRegistry.cpp.
References nullptr, PassInfo(), and passRegistry.
Referenced by mlir::Pass::lookupPassInfo().
The documentation for this class was generated from the following files:
include/mlir/Pass/PassRegistry.h
lib/Pass/PassRegistry.cpp