MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget Class Reference
Public Member Functions
PyConversionTarget (MlirContext context)
~PyConversionTarget ()
void addLegalOp (const std::string &opName)
void addIllegalOp (const std::string &opName)
void addLegalDialect (const std::string &dialectName)
void addIllegalDialect (const std::string &dialectName)
MlirConversionTarget get ()
Detailed Description
Definition at line 135 of file Rewrite.cpp.
Constructor & Destructor Documentation
PyConversionTarget()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::PyConversionTarget (MlirContext context) inline
Definition at line 137 of file Rewrite.cpp.
References mlirConversionTargetCreate().
~PyConversionTarget()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::~PyConversionTarget () inline
Definition at line 139 of file Rewrite.cpp.
References mlirConversionTargetDestroy().
Member Function Documentation
addIllegalDialect()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::addIllegalDialect (const std::string & dialectName) inline
Definition at line 156 of file Rewrite.cpp.
References mlirConversionTargetAddIllegalDialect(), and mlirStringRefCreate().
addIllegalOp()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::addIllegalOp (const std::string & opName) inline
Definition at line 146 of file Rewrite.cpp.
References mlirConversionTargetAddIllegalOp(), and mlirStringRefCreate().
addLegalDialect()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::addLegalDialect (const std::string & dialectName) inline
Definition at line 151 of file Rewrite.cpp.
References mlirConversionTargetAddLegalDialect(), and mlirStringRefCreate().
addLegalOp()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::addLegalOp (const std::string & opName) inline
Definition at line 141 of file Rewrite.cpp.
References mlirConversionTargetAddLegalOp(), and mlirStringRefCreate().
get()
MlirConversionTarget mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionTarget::get () inline
Definition at line 161 of file Rewrite.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.cpp