MLIR: mlir::OpBuilder::InsertPoint Class Reference
mlir::OpBuilder::InsertPoint Class Reference
This class represents a saved insertion point.
#include "mlir/IR/Builders.h"
Public Member Functions
InsertPoint ()=default
Creates a new insertion point which doesn't point to anything.
InsertPoint (Block *insertBlock, Block::iterator insertPt)
Creates a new insertion point at the given location.
bool isSet () const
Returns true if this insert point is set.
Block * getBlock () const
Block::iterator getPoint () const
Detailed Description
This class represents a saved insertion point.
Definition at line 327 of file Builders.h.
Constructor & Destructor Documentation
InsertPoint() [1/2]
mlir::OpBuilder::InsertPoint::InsertPoint () default
Creates a new insertion point which doesn't point to anything.
InsertPoint() [2/2]
mlir::OpBuilder::InsertPoint::InsertPoint (Block * insertBlock, Block::iterator insertPt) inline
Creates a new insertion point at the given location.
Definition at line 333 of file Builders.h.
Member Function Documentation
getBlock()
Block * mlir::OpBuilder::InsertPoint::getBlock () const inline
Definition at line 339 of file Builders.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::buildUnresolvedMaterialization(), computeInsertPoint(), and mlir::OpBuilder::restoreInsertionPoint().
getPoint()
Block::iterator mlir::OpBuilder::InsertPoint::getPoint () const inline
Definition at line 340 of file Builders.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::buildUnresolvedMaterialization(), computeInsertPoint(), and mlir::OpBuilder::restoreInsertionPoint().
isSet()
bool mlir::OpBuilder::InsertPoint::isSet () const inline
Returns true if this insert point is set.
Definition at line 337 of file Builders.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::notifyOperationInserted(), and mlir::OpBuilder::restoreInsertionPoint().
The documentation for this class was generated from the following file:
include/mlir/IR/Builders.h