MLIR: mlir::python::PyModule Class Reference
mlir::python::PyModule Class Reference
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyModule (PyModule &)=delete
PyModule (PyMlirContext &&)=delete
~PyModule ()
MlirModule get ()
Gets the backing MlirModule.
PyModuleRef getRef ()
Gets a strong reference to this module.
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirModule.
void clearMlirModule ()
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyModuleRef forModule (MlirModule module)
Returns a PyModule reference for the given MlirModule.
static nanobind::object createFromCapsule (nanobind::object capsule)
Creates a PyModule from the MlirModule wrapped by a capsule.
Detailed Description
Definition at line 512 of file IRModule.h.
Constructor & Destructor Documentation
PyModule() [1/2]
mlir::python::PyModule::PyModule (PyModule &) delete
References PyModule().
Referenced by forModule(), and PyModule().
PyModule() [2/2]
mlir::python::PyModule::PyModule (PyMlirContext &&) delete
~PyModule()
PyModule::~PyModule ()
Definition at line 969 of file IRCore.cpp.
References mlir::python::BaseContextObject::getContext(), and mlirModuleDestroy().
Member Function Documentation
clearMlirModule()
void mlir::python::PyModule::clearMlirModule () inline
Definition at line 540 of file IRModule.h.
createFromCapsule()
nb::object PyModule::createFromCapsule (nanobind::object capsule) static
Creates a PyModule from the MlirModule wrapped by a capsule.
Note this returns a new object BUT clearMlirModule() must be called to prevent double-frees (of the underlying mlir::Module).
Definition at line 1003 of file IRCore.cpp.
References forModule(), mlirPythonCapsuleToModule(), and mlir::python::PyObjectRef< T >::releaseObject().
forModule()
PyModuleRef PyModule::forModule (MlirModule module) static
Returns a PyModule reference for the given MlirModule.
This always returns a new object.
Definition at line 978 of file IRCore.cpp.
References mlir::python::PyMlirContext::forContext(), mlirModuleGetContext(), and PyModule().
Referenced by createFromCapsule().
get()
MlirModule mlir::python::PyModule::get () inline
Gets the backing MlirModule.
Definition at line 522 of file IRModule.h.
Referenced by getCapsule().
getCapsule()
nb::object PyModule::getCapsule ()
Gets a capsule wrapping the void* within the MlirModule.
Note that the module does not (yet) provide a corresponding factory for constructing from a capsule as that would require uniquing PyModule instances, which is not currently done.
Definition at line 1010 of file IRCore.cpp.
References get(), and mlirPythonModuleToCapsule().
getRef()
PyModuleRef mlir::python::PyModule::getRef () inline
Gets a strong reference to this module.
Definition at line 525 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp