MLIR: mlir::tblgen::Property Class Reference
mlir::tblgen::Property Class Reference
#include "mlir/TableGen/Property.h"
Public Member Functions
Property (const llvm::Record *def)
Property (const llvm::DefInit *init)
Property (const llvm::Record *maybeDef, StringRef summary, StringRef description, StringRef storageType, StringRef interfaceType, StringRef convertFromStorageCall, StringRef assignToStorageCall, StringRef convertToAttributeCall, StringRef convertFromAttributeCall, StringRef parserCall, StringRef optionalParserCall, StringRef printerCall, StringRef readFromMlirBytecodeCall, StringRef writeToMlirBytecodeCall, StringRef hashPropertyCall, StringRef defaultValue, StringRef storageTypeValueOverride)
StringRef getSummary () const
StringRef getDescription () const
StringRef getStorageType () const
StringRef getInterfaceType () const
StringRef getConvertFromStorageCall () const
StringRef getAssignToStorageCall () const
StringRef getConvertToAttributeCall () const
StringRef getConvertFromAttributeCall () const
Pred getPredicate () const
StringRef getParserCall () const
bool hasOptionalParser () const
StringRef getOptionalParserCall () const
StringRef getPrinterCall () const
StringRef getReadFromMlirBytecodeCall () const
StringRef getWriteToMlirBytecodeCall () const
StringRef getHashPropertyCall () const
bool hasDefaultValue () const
StringRef getDefaultValue () const
bool hasStorageTypeValueOverride () const
StringRef getStorageTypeValueOverride () const
StringRef getPropertyDefName () const
Property getBaseProperty () const
bool isSubClassOf (StringRef className) const
Public Member Functions inherited from mlir::tblgen::PropConstraint
StringRef getInterfaceType () const
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
Constraints are pointer-comparable.
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getSummary () const
StringRef getDescription () const
StringRef getDefName () const
Returns the name of the TablGen def of this constraint.
std::string getUniqueDefName () const
Returns a unique name for the TablGen def of this constraint.
std::optional< StringRef > getCppFunctionName () const
Returns the name of the C++ function that should be generated for this constraint, or std::nullopt if no C++ function should be generated.
Kind getKind () const
const llvm::Record & getDef () const
Return the underlying def.
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind {
CK_Attr , CK_Prop , CK_Region , CK_Successor ,
CK_Type , CK_Uncategorized
}
Static Public Member Functions inherited from mlir::tblgen::PropConstraint
static bool classof (const Constraint *c)
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 46 of file Property.h.
Constructor & Destructor Documentation
Property() [1/3]
mlir::tblgen::Property::Property (const llvm::Record * def) explicit
References mlir::tblgen::Constraint::def.
Referenced by mlir::tblgen::ConstantProp::classof(), mlir::tblgen::ConstantProp::ConstantProp(), and getBaseProperty().
Property() [2/3]
mlir::tblgen::Property::Property (const llvm::DefInit * init) explicit
Property() [3/3]
Property::Property (const llvm::Record * maybeDef, StringRef summary, StringRef description, StringRef storageType, StringRef interfaceType, StringRef convertFromStorageCall, StringRef assignToStorageCall, StringRef convertToAttributeCall, StringRef convertFromAttributeCall, StringRef parserCall, StringRef optionalParserCall, StringRef printerCall, StringRef readFromMlirBytecodeCall, StringRef writeToMlirBytecodeCall, StringRef hashPropertyCall, StringRef defaultValue, StringRef storageTypeValueOverride)
Definition at line 63 of file Property.cpp.
References mlir::tblgen::Constraint::CK_Prop, and mlir::tblgen::PropConstraint::Constraint().
Member Function Documentation
getAssignToStorageCall()
StringRef mlir::tblgen::Property::getAssignToStorageCall () const inline
Definition at line 78 of file Property.h.
getBaseProperty()
Property Property::getBaseProperty () const
Definition at line 107 of file Property.cpp.
References mlir::tblgen::Constraint::def, and Property().
Referenced by getPropertyDefName().
getConvertFromAttributeCall()
StringRef mlir::tblgen::Property::getConvertFromAttributeCall () const inline
Definition at line 86 of file Property.h.
getConvertFromStorageCall()
StringRef mlir::tblgen::Property::getConvertFromStorageCall () const inline
Definition at line 74 of file Property.h.
getConvertToAttributeCall()
StringRef mlir::tblgen::Property::getConvertToAttributeCall () const inline
Definition at line 82 of file Property.h.
getDefaultValue()
StringRef mlir::tblgen::Property::getDefaultValue () const inline
Definition at line 126 of file Property.h.
getDescription()
StringRef mlir::tblgen::Property::getDescription () const inline
Definition at line 64 of file Property.h.
getHashPropertyCall()
StringRef mlir::tblgen::Property::getHashPropertyCall () const inline
Definition at line 120 of file Property.h.
getInterfaceType()
StringRef mlir::tblgen::Property::getInterfaceType () const inline
Definition at line 70 of file Property.h.
Referenced by canUniquePropConstraint().
getOptionalParserCall()
StringRef mlir::tblgen::Property::getOptionalParserCall () const inline
Definition at line 102 of file Property.h.
getParserCall()
StringRef mlir::tblgen::Property::getParserCall () const inline
Definition at line 95 of file Property.h.
getPredicate()
Pred Property::getPredicate () const
Definition at line 98 of file Property.cpp.
References mlir::tblgen::Constraint::def.
getPrinterCall()
StringRef mlir::tblgen::Property::getPrinterCall () const inline
Definition at line 105 of file Property.h.
getPropertyDefName()
StringRef Property::getPropertyDefName () const
Definition at line 91 of file Property.cpp.
References mlir::tblgen::Constraint::def, and getBaseProperty().
getReadFromMlirBytecodeCall()
StringRef mlir::tblgen::Property::getReadFromMlirBytecodeCall () const inline
Definition at line 109 of file Property.h.
getStorageType()
StringRef mlir::tblgen::Property::getStorageType () const inline
Definition at line 67 of file Property.h.
getStorageTypeValueOverride()
StringRef mlir::tblgen::Property::getStorageTypeValueOverride () const inline
Definition at line 134 of file Property.h.
getSummary()
StringRef mlir::tblgen::Property::getSummary () const inline
Definition at line 61 of file Property.h.
getWriteToMlirBytecodeCall()
StringRef mlir::tblgen::Property::getWriteToMlirBytecodeCall () const inline
Definition at line 115 of file Property.h.
hasDefaultValue()
bool mlir::tblgen::Property::hasDefaultValue () const inline
Definition at line 123 of file Property.h.
hasOptionalParser()
bool mlir::tblgen::Property::hasOptionalParser () const inline
Definition at line 98 of file Property.h.
hasStorageTypeValueOverride()
bool mlir::tblgen::Property::hasStorageTypeValueOverride () const inline
Definition at line 130 of file Property.h.
isSubClassOf()
bool Property::isSubClassOf (StringRef className) const
Definition at line 115 of file Property.cpp.
References mlir::tblgen::Constraint::def.
Referenced by mlir::tblgen::ConstantProp::classof(), and mlir::tblgen::ConstantProp::ConstantProp().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Property.h
lib/TableGen/Property.cpp