MLIR: ConvInferShapeAdaptor< Conv3DOp::Adaptor > Class Reference
ConvInferShapeAdaptor< Conv3DOp::Adaptor > Class Reference
Public Member Functions
ConvInferShapeAdaptor (Conv3DOp::Adaptor adaptor)
void inferInputShape (SmallVectorImpl< int64_t > &outputShape, SmallVectorImpl< int64_t > &inputSpatial)
void inferWeightShape (SmallVectorImpl< int64_t > &outputShape, SmallVectorImpl< int64_t > &weightSpatial)
int64_t getNumSpatialDims () const
int64_t getOutputRank () const
LogicalResult getSpatialParameters (SmallVector< int64_t > &padValues, SmallVector< int64_t > &strideValues, SmallVector< int64_t > &dilationValues)
Additional Inherited Members
Static Protected Member Functions inherited from ConvInferShapeAdaptorBase
static void updateIfDynamic (int64_t &current, int64_t candidate)
Detailed Description
Definition at line 4440 of file TosaOps.cpp.
Constructor & Destructor Documentation
ConvInferShapeAdaptor()
ConvInferShapeAdaptor< Conv3DOp::Adaptor >::ConvInferShapeAdaptor (Conv3DOp::Adaptor adaptor) inline explicit
Definition at line 4443 of file TosaOps.cpp.
Member Function Documentation
getNumSpatialDims()
int64_t ConvInferShapeAdaptor< Conv3DOp::Adaptor >::getNumSpatialDims () const inline
Definition at line 4480 of file TosaOps.cpp.
getOutputRank()
int64_t ConvInferShapeAdaptor< Conv3DOp::Adaptor >::getOutputRank () const inline
Definition at line 4481 of file TosaOps.cpp.
getSpatialParameters()
LogicalResult ConvInferShapeAdaptor< Conv3DOp::Adaptor >::getSpatialParameters (SmallVector< int64_t > & padValues, SmallVector< int64_t > & strideValues, SmallVector< int64_t > & dilationValues) inline
Definition at line 4483 of file TosaOps.cpp.
References success().
inferInputShape()
void ConvInferShapeAdaptor< Conv3DOp::Adaptor >::inferInputShape (SmallVectorImpl< int64_t > & outputShape, SmallVectorImpl< int64_t > & inputSpatial) inline
Definition at line 4446 of file TosaOps.cpp.
References mlir::ShapeAdaptor::getDimSize(), and mlir::ShapeAdaptor::hasRank().
inferWeightShape()
void ConvInferShapeAdaptor< Conv3DOp::Adaptor >::inferWeightShape (SmallVectorImpl< int64_t > & outputShape, SmallVectorImpl< int64_t > & weightSpatial) inline
Definition at line 4463 of file TosaOps.cpp.
References mlir::ShapeAdaptor::getDimSize(), and mlir::ShapeAdaptor::hasRank().
The documentation for this class was generated from the following file:
lib/Dialect/Tosa/IR/TosaOps.cpp