MLIR: mlir::DialectExtension< DerivedT, DialectsT > Class Template Reference
mlir::DialectExtension< DerivedT, DialectsT > Class Template Reference abstract
This class represents a dialect extension anchored on the given set of dialects.
#include "mlir/IR/DialectRegistry.h"
Public Member Functions
virtual void apply (MLIRContext *context, DialectsT *...dialects) const =0
Applies this extension to the given context and set of required dialects.
std::unique_ptr< DialectExtensionBase > clone () const final
Return a copy of this extension.
Public Member Functions inherited from mlir::DialectExtensionBase
virtual ~DialectExtensionBase ()
ArrayRef< StringRef > getRequiredDialects () const
Return the dialects that our required by this extension to be loaded before applying.
Protected Member Functions
DialectExtension ()
void apply (MLIRContext *context, MutableArrayRef< Dialect * > dialects) const final
Override the base apply method to allow providing the exact dialect types.
Protected Member Functions inherited from mlir::DialectExtensionBase
DialectExtensionBase (ArrayRef< StringRef > dialectNames)
Initialize the extension with a set of required dialects.
Detailed Description
template<typename DerivedT, typename... DialectsT>
class mlir::DialectExtension< DerivedT, DialectsT >
This class represents a dialect extension anchored on the given set of dialects.
When all of the specified dialects have been loaded, the application function of this extension will be executed.
Definition at line 74 of file DialectRegistry.h.
Constructor & Destructor Documentation
DialectExtension()
template<typename DerivedT, typename... DialectsT> mlir::DialectExtension< DerivedT, DialectsT >::DialectExtension () inline protected
Definition at line 85 of file DialectRegistry.h.
References mlir::DialectExtensionBase::DialectExtensionBase().
Member Function Documentation
apply() [1/2]
template<typename DerivedT, typename... DialectsT> virtual void mlir::DialectExtension< DerivedT, DialectsT >::apply (MLIRContext * context, DialectsT *... dialects) const pure virtual
Applies this extension to the given context and set of required dialects.
Referenced by apply().
apply() [2/2]
template<typename DerivedT, typename... DialectsT> void mlir::DialectExtension< DerivedT, DialectsT >::apply (MLIRContext * context, MutableArrayRef< Dialect * > dialects) const inline final protected virtual
Override the base apply method to allow providing the exact dialect types.
Implements mlir::DialectExtensionBase.
Definition at line 90 of file DialectRegistry.h.
References apply().
clone()
template<typename DerivedT, typename... DialectsT> std::unique_ptr< DialectExtensionBase > mlir::DialectExtension< DerivedT, DialectsT >::clone () const inline final virtual
Return a copy of this extension.
Implements mlir::DialectExtensionBase.
Definition at line 80 of file DialectRegistry.h.
The documentation for this class was generated from the following file:
include/mlir/IR/DialectRegistry.h