MLIR: mlir::affine::NestedPattern Class Reference
mlir::affine::NestedPattern Class Reference
#include "mlir/Dialect/Affine/Analysis/NestedMatcher.h"
Public Member Functions
NestedPattern (ArrayRef< NestedPattern > nested, FilterFunctionType filter=defaultFilterFunction)
NestedPattern (const NestedPattern &other)
NestedPattern & operator= (const NestedPattern &other)
~NestedPattern ()
void match (Operation *op, SmallVectorImpl< NestedMatch > *matches)
Returns all the top-level matches in op.
unsigned getDepth () const
Returns the depth of the pattern.
Friends
class NestedPatternContext
class NestedMatch
struct State
Detailed Description
Definition at line 93 of file NestedMatcher.h.
Constructor & Destructor Documentation
NestedPattern() [1/2]
NestedPattern::NestedPattern (ArrayRef< NestedPattern > nested, FilterFunctionType filter = defaultFilterFunction)
Definition at line 56 of file NestedMatcher.cpp.
References nullptr.
Referenced by NestedPattern(), and operator=().
NestedPattern() [2/2]
NestedPattern::NestedPattern (const NestedPattern & other)
Definition at line 62 of file NestedMatcher.cpp.
References NestedPattern().
~NestedPattern()
mlir::affine::NestedPattern::~NestedPattern () inline
Definition at line 100 of file NestedMatcher.h.
Member Function Documentation
getDepth()
unsigned NestedPattern::getDepth () const
Returns the depth of the pattern.
Definition at line 75 of file NestedMatcher.cpp.
match()
void mlir::affine::NestedPattern::match (Operation * op, SmallVectorImpl< NestedMatch > * matches) inline
Returns all the top-level matches in op.
Definition at line 108 of file NestedMatcher.h.
References mlir::Operation::walk().
Referenced by isVectorizableLoopBodyWithOpCond().
operator=()
NestedPattern & NestedPattern::operator= (const NestedPattern & other)
Definition at line 67 of file NestedMatcher.cpp.
References NestedPattern().
Friends And Related Symbol Documentation
NestedMatch
friend class NestedMatch friend
Definition at line 117 of file NestedMatcher.h.
References NestedMatch.
Referenced by NestedMatch.
NestedPatternContext
friend class NestedPatternContext friend
Definition at line 116 of file NestedMatcher.h.
References NestedPatternContext.
Referenced by NestedPatternContext.
State
friend struct State friend
Definition at line 118 of file NestedMatcher.h.
References State.
Referenced by State.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/Analysis/NestedMatcher.h
lib/Dialect/Affine/Analysis/NestedMatcher.cpp