MLIR: mlir::OperationName::Impl Class Reference
mlir::OperationName::Impl Class Reference
#include "mlir/IR/OperationSupport.h"
Public Member Functions
Impl (StringRef, Dialect *dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
Impl (StringAttr name, Dialect *dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
bool isRegistered () const
Returns true if this is a registered operation.
detail::InterfaceMap & getInterfaceMap ()
Dialect * getDialect () const
StringAttr getName () const
TypeID getTypeID () const
TypeID getPropertiesTypeID () const
ArrayRef< StringAttr > getAttributeNames () const
Public Member Functions inherited from mlir::OperationName::InterfaceConcept
virtual ~InterfaceConcept ()=default
virtual LogicalResult foldHook (Operation *, ArrayRef< Attribute >, SmallVectorImpl< OpFoldResult > &)=0
virtual void getCanonicalizationPatterns (RewritePatternSet &, MLIRContext *)=0
virtual bool hasTrait (TypeID)=0
virtual OperationName::ParseAssemblyFn getParseAssemblyFn ()=0
virtual void populateDefaultAttrs (const OperationName &, NamedAttrList &)=0
virtual void printAssembly (Operation *, OpAsmPrinter &, StringRef)=0
virtual LogicalResult verifyInvariants (Operation *)=0
virtual LogicalResult verifyRegionInvariants (Operation *)=0
virtual std::optional< Attribute > getInherentAttr (Operation *, StringRef name)=0
Implementation for properties.
virtual void setInherentAttr (Operation *op, StringAttr name, Attribute value)=0
virtual void populateInherentAttrs (Operation *op, NamedAttrList &attrs)=0
virtual LogicalResult verifyInherentAttrs (OperationName opName, NamedAttrList &attributes, function_ref< InFlightDiagnostic()> emitError)=0
virtual int getOpPropertyByteSize ()=0
virtual void initProperties (OperationName opName, PropertyRef storage, PropertyRef init)=0
virtual void deleteProperties (PropertyRef)=0
virtual void populateDefaultProperties (OperationName opName, PropertyRef properties)=0
virtual LogicalResult setPropertiesFromAttr (OperationName, PropertyRef, Attribute, function_ref< InFlightDiagnostic()> emitError)=0
virtual Attribute getPropertiesAsAttr (Operation *)=0
virtual void copyProperties (PropertyRef, PropertyRef)=0
virtual bool compareProperties (PropertyRef, PropertyRef)=0
virtual llvm::hash_code hashProperties (PropertyRef)=0
Protected Attributes
StringAttr name
The name of the operation.
TypeID typeID
The unique identifier of the derived Op class.
Dialect * dialect
The following fields are only populated when the operation is registered.
detail::InterfaceMap interfaceMap
A map of interfaces that were registered to this operation.
ArrayRef< StringAttr > attributeNames
A list of attribute names registered to this operation in StringAttr form.
TypeID propertiesTypeID
The TypeID of the Properties struct for this operation.
Friends
class RegisteredOperationName
Detailed Description
Definition at line 159 of file OperationSupport.h.
Constructor & Destructor Documentation
Impl() [1/2]
OperationName::Impl::Impl (StringRef name, Dialect * dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
Definition at line 808 of file MLIRContext.cpp.
References dialect, mlir::get(), mlir::OperationName::getContext(), Impl(), interfaceMap, name, and typeID.
Referenced by Impl(), mlir::RegisteredOperationName::Model< ConcreteOp >::Model(), and mlir::OperationName::UnregisteredOpModel::UnregisteredOpModel().
Impl() [2/2]
mlir::OperationName::Impl::Impl (StringAttr name, Dialect * dialect, TypeID typeID, detail::InterfaceMap interfaceMap) inline
Definition at line 163 of file OperationSupport.h.
References dialect, interfaceMap, name, and typeID.
Member Function Documentation
getAttributeNames()
ArrayRef< StringAttr > mlir::OperationName::Impl::getAttributeNames () const inline
Definition at line 175 of file OperationSupport.h.
References attributeNames.
Referenced by mlir::OperationName::getAttributeNames().
getDialect()
Dialect * mlir::OperationName::Impl::getDialect () const inline
Definition at line 171 of file OperationSupport.h.
References dialect.
Referenced by mlir::OperationName::attachInterface(), mlir::OperationName::getDialect(), and mlir::OperationName::hasPromiseOrImplementsInterface().
getInterfaceMap()
detail::InterfaceMap & mlir::OperationName::Impl::getInterfaceMap () inline
Definition at line 170 of file OperationSupport.h.
References interfaceMap.
Referenced by mlir::OperationName::attachInterface(), mlir::OperationName::getInterface(), mlir::OperationName::hasInterface(), and mlir::RegisteredOperationName::Model< ConcreteOp >::Model().
getName()
StringAttr mlir::OperationName::Impl::getName () const inline
Definition at line 172 of file OperationSupport.h.
References name.
Referenced by mlir::OperationName::getDialect(), and mlir::OperationName::getIdentifier().
getPropertiesTypeID()
TypeID mlir::OperationName::Impl::getPropertiesTypeID () const inline
Definition at line 174 of file OperationSupport.h.
References propertiesTypeID.
Referenced by mlir::OperationName::getOpPropertiesTypeID().
getTypeID()
TypeID mlir::OperationName::Impl::getTypeID () const inline
Definition at line 173 of file OperationSupport.h.
References typeID.
Referenced by mlir::OperationName::attachInterface(), mlir::OperationName::getTypeID(), and mlir::OperationName::hasPromiseOrImplementsInterface().
isRegistered()
bool mlir::OperationName::Impl::isRegistered () const inline
Returns true if this is a registered operation.
Definition at line 169 of file OperationSupport.h.
References mlir::TypeID::get(), and typeID.
Referenced by mlir::OperationName::getDialect(), mlir::OperationName::isRegistered(), mlir::OperationName::mightHaveInterface(), and mlir::OperationName::mightHaveTrait().
Friends And Related Symbol Documentation
RegisteredOperationName
friend class RegisteredOperationName friend
Definition at line 204 of file OperationSupport.h.
References RegisteredOperationName.
Referenced by RegisteredOperationName.
Member Data Documentation
attributeNames
ArrayRef<StringAttr> mlir::OperationName::Impl::attributeNames protected
A list of attribute names registered to this operation in StringAttr form.
This allows for operation classes to use StringAttr for attribute lookup/creation/etc., as opposed to raw strings.
Definition at line 199 of file OperationSupport.h.
Referenced by getAttributeNames().
dialect
Dialect* mlir::OperationName::Impl::dialect protected
The following fields are only populated when the operation is registered.
This is the dialect that this operation belongs to.
Definition at line 191 of file OperationSupport.h.
Referenced by mlir::DynamicOpDefinition::get(), mlir::DynamicOpDefinition::get(), mlir::DynamicOpDefinition::get(), getDialect(), Impl(), Impl(), mlir::RegisteredOperationName::Model< ConcreteOp >::Model(), and mlir::OperationName::UnregisteredOpModel::UnregisteredOpModel().
interfaceMap
detail::InterfaceMap mlir::OperationName::Impl::interfaceMap protected
A map of interfaces that were registered to this operation.
Definition at line 194 of file OperationSupport.h.
Referenced by getInterfaceMap(), Impl(), Impl(), and mlir::OperationName::UnregisteredOpModel::UnregisteredOpModel().
name
StringAttr mlir::OperationName::Impl::name protected
The name of the operation.
Definition at line 182 of file OperationSupport.h.
Referenced by mlir::DynamicOpDefinition::get(), mlir::DynamicOpDefinition::get(), mlir::DynamicOpDefinition::get(), mlir::DynamicOpDefinition::getInherentAttr(), mlir::OperationName::getInherentAttr(), mlir::OperationName::UnregisteredOpModel::getInherentAttr(), mlir::RegisteredOperationName::Model< ConcreteOp >::getInherentAttr(), getName(), Impl(), Impl(), mlir::DynamicOpDefinition::populateDefaultAttrs(), mlir::RegisteredOperationName::Model< ConcreteOp >::populateDefaultAttrs(), mlir::DynamicOpDefinition::printAssembly(), mlir::RegisteredOperationName::Model< ConcreteOp >::printAssembly(), mlir::DynamicOpDefinition::setInherentAttr(), mlir::OperationName::setInherentAttr(), mlir::OperationName::UnregisteredOpModel::setInherentAttr(), mlir::RegisteredOperationName::Model< ConcreteOp >::setInherentAttr(), and mlir::OperationName::UnregisteredOpModel::UnregisteredOpModel().
propertiesTypeID
TypeID mlir::OperationName::Impl::propertiesTypeID protected
The TypeID of the Properties struct for this operation.
Definition at line 202 of file OperationSupport.h.
Referenced by getPropertiesTypeID(), mlir::RegisteredOperationName::Model< ConcreteOp >::Model(), and mlir::OperationName::UnregisteredOpModel::UnregisteredOpModel().
typeID
TypeID mlir::OperationName::Impl::typeID protected
The unique identifier of the derived Op class.
Definition at line 185 of file OperationSupport.h.
Referenced by mlir::DynamicOpDefinition::getTypeID(), getTypeID(), Impl(), Impl(), isRegistered(), and mlir::OperationName::UnregisteredOpModel::UnregisteredOpModel().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/MLIRContext.cpp