MLIR: mlir::BlockAndValueMapping Class Reference
mlir::BlockAndValueMapping Class Reference
#include "mlir/IR/BlockAndValueMapping.h"
Public Member Functions
void map (Block *from, Block *to)
Inserts a new mapping for 'from' to 'to'.
void map (Value from, Value to)
template<typename S , typename T , std::enable_if_t<!std::is_assignable< Value, S >::value &&!std::is_assignable< Block *, S >::value > * = nullptr>
void map (S &&from, T &&to)
void erase (Block *from)
Erases a mapping for 'from'.
void erase (Value from)
bool contains (Block *from) const
Checks to see if a mapping for 'from' exists.
bool contains (Value from) const
Block * lookupOrNull (Block *from) const
Lookup a mapped value within the map.
Value lookupOrNull (Value from) const
Block * lookupOrDefault (Block *from) const
Lookup a mapped value within the map.
Value lookupOrDefault (Value from) const
template<typename T >
T lookup (T from) const
Lookup a mapped value within the map.
void clear ()
Clears all mappings held by the mapper.
BlockAndValueMapping getInverse () const
Returns a new mapper containing the inverse mapping.
Detailed Description
Definition at line 26 of file BlockAndValueMapping.h.
Member Function Documentation
clear()
void mlir::BlockAndValueMapping::clear () inline
Clears all mappings held by the mapper.
Definition at line 77 of file BlockAndValueMapping.h.
Referenced by addExecuteResults(), and hoistAffineIfOp().
contains() [1/2]
bool mlir::BlockAndValueMapping::contains (Block * from) const inline
Checks to see if a mapping for 'from' exists.
Definition at line 49 of file BlockAndValueMapping.h.
Referenced by mlir::Region::cloneInto(), inlineRegionImpl(), and verify().
contains() [2/2]
bool mlir::BlockAndValueMapping::contains (Value from) const inline
Definition at line 50 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer().
erase() [1/2]
void mlir::BlockAndValueMapping::erase (Block * from) inline
Erases a mapping for 'from'.
Definition at line 45 of file BlockAndValueMapping.h.
erase() [2/2]
void mlir::BlockAndValueMapping::erase (Value from) inline
Definition at line 46 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer().
getInverse()
BlockAndValueMapping mlir::BlockAndValueMapping::getInverse () const inline
Returns a new mapper containing the inverse mapping.
Definition at line 80 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer(), mlir::Value::getFromOpaquePointer(), and value.
Referenced by logFailure().
lookup()
template<typename T > T mlir::BlockAndValueMapping::lookup (T from) const inline
Lookup a mapped value within the map.
This asserts the provided value exists within the map.
Definition at line 70 of file BlockAndValueMapping.h.
References lookupOrNull().
Referenced by mlir::Region::cloneInto(), mlir::ConversionPatternRewriter::cloneRegionBefore(), generateUnrolledLoop(), mlir::linalg::hoistPaddingOnTensors(), mlir::ReductionNode::initialize(), matchSimpleAtomicOp(), mlir::outlineIfOp(), outlineKernelFuncImpl(), remainsLegalAfterInline(), vectorizeLinalgYield(), and vectorizeOneOp().
lookupOrDefault() [1/2]
Block* mlir::BlockAndValueMapping::lookupOrDefault (Block * from) const inline
Lookup a mapped value within the map.
If a mapping for the provided value does not exist then return the provided value.
Definition at line 63 of file BlockAndValueMapping.h.
Referenced by allocateBuffersForResults(), mlir::Operation::cloneWithoutRegions(), generateFusedElementwiseOpRegion(), mlir::scf::getParallelForInductionVarOwner(), haveNoReadsAfterWriteExceptSameIndex(), mlir::linalg::hoistPaddingOnTensors(), inlineRegionAndEmitStore(), processParallelLoop(), and verify().
lookupOrDefault() [2/2]
Value mlir::BlockAndValueMapping::lookupOrDefault (Value from) const inline
Definition at line 66 of file BlockAndValueMapping.h.
lookupOrNull() [1/2]
Block* mlir::BlockAndValueMapping::lookupOrNull (Block * from) const inline
Lookup a mapped value within the map.
If a mapping for the provided value does not exist then return nullptr.
Definition at line 56 of file BlockAndValueMapping.h.
Referenced by mlir::Region::cloneInto(), mlir::spirv::Deserializer::collect(), findLiveUserOfReplaced(), lookup(), lookup(), and remapInlinedOperands().
lookupOrNull() [2/2]
Value mlir::BlockAndValueMapping::lookupOrNull (Value from) const inline
Definition at line 59 of file BlockAndValueMapping.h.
map() [1/3]
void mlir::BlockAndValueMapping::map (Block * from, Block * to) inline
Inserts a new mapping for 'from' to 'to'.
If there is an existing mapping, it is overwritten.
Definition at line 30 of file BlockAndValueMapping.h.
Referenced by mlir::Region::cloneInto(), mlir::cloneWithNewYields(), mlir::Operation::cloneWithoutRegions(), mlir::spirv::Deserializer::collect(), createFullPartialVectorTransferWrite(), createFullTiles(), createParallelComputeFunction(), fuseIfLegal(), fuseWithReshapeByExpansion(), generateFusedElementwiseOpRegion(), generateShiftedLoop(), generateUnrolledLoop(), mlir::scf::getParallelForInductionVarOwner(), mlir::linalg::hoistPaddingOnTensors(), injectGpuIndexOperations(), mlir::inlineCall(), inlineRegionAndEmitStore(), inlineRegionImpl(), mlir::loopUnrollJamByFactor(), map(), map(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), matchSimpleAtomicOp(), outlineExecuteOp(), mlir::outlineIfOp(), outlineKernelFuncImpl(), processParallelLoop(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::vector::splitFullAndPartialTransfer(), vectorizeAsLinalgGeneric(), verify(), and verifyDependencies().
map() [2/3]
void mlir::BlockAndValueMapping::map (Value from, Value to) inline
Definition at line 31 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer(), and value.
map() [3/3]
template<typename S , typename T , std::enable_if_t<!std::is_assignable< Value, S >::value &&!std::is_assignable< Block *, S >::value > * = nullptr> void mlir::BlockAndValueMapping::map (S && from, T && to) inline
Definition at line 39 of file BlockAndValueMapping.h.
References map().
The documentation for this class was generated from the following file:
include/mlir/IR/BlockAndValueMapping.h