MLIR: mlir::Identifier Class Reference
mlir::Identifier Class Reference
This class represents a uniqued string owned by an MLIRContext.
#include "mlir/IR/Identifier.h"
Public Member Functions
Identifier (const Identifier &)=default
Identifier & operator= (const Identifier &other)=default
StringRef strref () const
Return a StringRef for the string.
operator StringRef () const
Identifiers implicitly convert to StringRefs.
std::string str () const
Return an std::string.
const char * c_str () const
Return a null terminated C string.
const char * data () const
Return a pointer to the start of the string data.
unsigned size () const
Return the number of bytes in this string.
Dialect * getDialect ()
Return the dialect loaded in the context for this identifier or nullptr if this identifier isn't prefixed with a loaded dialect.
MLIRContext * getContext ()
Return the current MLIRContext associated with this identifier.
const char * begin () const
const char * end () const
bool operator== (Identifier other) const
bool operator!= (Identifier rhs) const
void print (raw_ostream &os) const
void dump () const
const void * getAsOpaquePointer () const
int compare (Identifier rhs) const
Compare the underlying StringRef.
Static Public Member Functions
static Identifier get (const Twine &string, MLIRContext *context)
Return an identifier for the specified string.
static Identifier getFromOpaquePointer (const void *entry)
Detailed Description
This class represents a uniqued string owned by an MLIRContext.
Strings represented by this type cannot contain nul characters, and may not have a zero length.
This is a POD type with pointer size, so it should be passed around by value. The underlying data is owned by MLIRContext and is thus immortal for almost all clients.
An Identifier may be prefixed with a dialect namespace followed by a single dot .. This is particularly useful when used as a key in a NamedAttribute to differentiate a dependent attribute (specific to an operation) from a generic attribute defined by the dialect (in general applicable to multiple operations).
Definition at line 36 of file Identifier.h.
Constructor & Destructor Documentation
Identifier()
mlir::Identifier::Identifier (const Identifier &) default
Referenced by compare(), and getFromOpaquePointer().
Member Function Documentation
begin()
const char* mlir::Identifier::begin () const inline
Definition at line 74 of file Identifier.h.
References data().
c_str()
const char* mlir::Identifier::c_str () const inline
Return a null terminated C string.
Definition at line 57 of file Identifier.h.
compare()
int mlir::Identifier::compare (Identifier rhs) const inline
Compare the underlying StringRef.
Definition at line 91 of file Identifier.h.
References Identifier(), and strref().
Referenced by mlir::detail::OpToOpPassAdaptor::mergeInto().
data()
const char* mlir::Identifier::data () const inline
Return a pointer to the start of the string data.
Definition at line 60 of file Identifier.h.
Referenced by begin().
dump()
void Identifier::dump () const
Definition at line 48 of file AsmPrinter.cpp.
References print().
Referenced by operator!=().
end()
const char* mlir::Identifier::end () const inline
Definition at line 75 of file Identifier.h.
References size().
get()
Identifier Identifier::get (const Twine & string, MLIRContext * context) static
Return an identifier for the specified string.
Definition at line 834 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), mlir::MLIRContext::getLoadedDialect(), and mlir::MLIRContext::isMultithreadingEnabled().
Referenced by mlir::NamedAttrList::append(), collectValidReferencesFor(), combineOneSpec(), mlir::AffineDmaStartOp::getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), mlir::pdl_to_pdl_interp::PredicateBuilder::getAttribute(), getDefaultABIAttrs(), mlir::Builder::getIdentifier(), mlir::detail::OpPassManagerImpl::getOpName(), mlir::AbstractOperation::insert(), mlir::SymbolTable::lookupSymbolIn(), mlirIdentifierGet(), mlirOpaqueAttrGet(), mlir::OperationName::OperationName(), mlir::detail::Parser::parseExtendedAttr(), mlir::detail::Parser::parseExtendedType(), mlir::detail::Parser::parseNameOrFileLineColLocation(), mlir::Dialect::parseType(), mlir::populateGpuToNVVMConversionPatterns(), mlir::populateGpuToROCDLConversionPatterns(), populateVectorizationPatterns(), mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr(), mlir::Operation::removeAttr(), mlir::linalg::LinalgTransformationFilter::replaceLinalgTransformationFilter(), mlir::NamedAttrList::set(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), mlir::Operation::setAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr(), mlir::SymbolTable::setSymbolVisibility(), mlir::SymbolTable::SymbolTable(), tilePadTensorOp(), mlir::linalg::CodegenStrategy::transform(), and mlir::detail::verifyDataLayoutSpec().
getAsOpaquePointer()
const void* mlir::Identifier::getAsOpaquePointer () const inline
Definition at line 83 of file Identifier.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::Identifier >::getAsVoidPointer(), and mlir::hash_value().
getContext()
MLIRContext * Identifier::getContext ()
Return the current MLIRContext associated with this identifier.
Definition at line 880 of file MLIRContext.cpp.
References mlir::Dialect::getContext().
Referenced by mlir::BoolAttr::classof(), mlir::DataLayoutEntryAttr::get(), iterateIndicesExcept(), and size().
getDialect()
Dialect * Identifier::getDialect ()
Return the dialect loaded in the context for this identifier or nullptr if this identifier isn't prefixed with a loaded dialect.
For example the llvm.fastmathflags identifier would return the LLVM dialect here, assuming it is loaded in the context.
Definition at line 876 of file MLIRContext.cpp.
Referenced by mlir::DenseIntElementsAttr::classof(), size(), and mlir::detail::verifyDataLayoutSpec().
getFromOpaquePointer()
static Identifier mlir::Identifier::getFromOpaquePointer (const void * entry) inline static
Definition at line 86 of file Identifier.h.
References Identifier().
Referenced by llvm::DenseMapInfo< mlir::Identifier >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::Identifier >::getFromVoidPointer(), and llvm::DenseMapInfo< mlir::Identifier >::getTombstoneKey().
operator StringRef()
mlir::Identifier::operator StringRef () const inline
Identifiers implicitly convert to StringRefs.
Definition at line 51 of file Identifier.h.
References strref().
operator!=()
bool mlir::Identifier::operator!= (Identifier rhs) const inline
Definition at line 78 of file Identifier.h.
References dump(), and print().
operator=()
Identifier& mlir::Identifier::operator= (const Identifier & other) default
operator==()
bool mlir::Identifier::operator== (Identifier other) const inline
Definition at line 77 of file Identifier.h.
print()
void Identifier::print (raw_ostream & os) const
Definition at line 46 of file AsmPrinter.cpp.
Referenced by operator!=(), and mlir::operator<<().
size()
unsigned mlir::Identifier::size () const inline
Return the number of bytes in this string.
Definition at line 63 of file Identifier.h.
References getContext(), and getDialect().
Referenced by end().
str()
std::string mlir::Identifier::str () const inline
Return an std::string.
Definition at line 54 of file Identifier.h.
References strref().
strref()
StringRef mlir::Identifier::strref () const inline
Return a StringRef for the string.
Definition at line 48 of file Identifier.h.
Referenced by mlir::BoolAttr::classof(), mlir::DenseIntElementsAttr::classof(), compare(), iterateIndicesExcept(), operator StringRef(), mlir::Diagnostic::operator<<(), mlir::operator==(), and str().
The documentation for this class was generated from the following files:
include/mlir/IR/Identifier.h
lib/IR/AsmPrinter.cpp
lib/IR/MLIRContext.cpp