MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType Class Reference
Unranked Tensor Type subclass - UnrankedTensorType.
#include "mlir/Bindings/Python/IRTypes.h"
Public Member Functions
PyConcreteType ()=default
PyConcreteType (PyMlirContextRef contextRef, MlirType t)
PyConcreteType (PyType &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyUnrankedTensorType, PyShapedType >
PyConcreteType ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyShapedType
PyConcreteType ()=default
PyConcreteType (PyMlirContextRef contextRef, MlirType t)
PyConcreteType (PyType &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyShapedType >
PyConcreteType ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::typed< nanobind::object, PyType > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyUnrankedTensorType, PyShapedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyShapedType
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyShapedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirTypeIsAUnrankedTensor
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "UnrankedTensorType"
static const MlirStringRef name = mlirUnrankedTensorTypeGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyUnrankedTensorType, PyShapedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyShapedType
static const IsAFunctionTy isaFunction = mlirTypeIsAShaped
static constexpr const char * pyClassName = "ShapedType"
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyShapedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyUnrankedTensorType, PyShapedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyShapedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Detailed Description
Unranked Tensor Type subclass - UnrankedTensorType.
Definition at line 366 of file IRTypes.h.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::bindDerived (ClassTy & c) static
Definition at line 593 of file IRTypes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirTypeIsNull(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture::take().
PyConcreteType() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType () default
PyConcreteType() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType (PyMlirContextRef contextRef, MlirType t) inline
Definition at line 956 of file IRCore.h.
PyConcreteType() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType (PyType & orig) inline
Definition at line 958 of file IRCore.h.
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::getTypeIdFunction static constexpr
Initial value:
=
      mlirUnrankedTensorTypeGetTypeID
Definition at line 370 of file IRTypes.h.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::isaFunction = mlirTypeIsAUnrankedTensor static constexpr
Definition at line 369 of file IRTypes.h.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::name = mlirUnrankedTensorTypeGetName() inline static
Definition at line 373 of file IRTypes.h.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::pyClassName = "UnrankedTensorType" static constexpr
Definition at line 372 of file IRTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRTypes.h
lib/Bindings/Python/IRTypes.cpp