MLIR: mlir::python::PyDialects Class Reference
mlir::python::PyDialects Class Reference
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyDialects (PyMlirContextRef contextRef)
MlirDialect getDialectForKey (const std::string &key, bool attrError)
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
Definition at line 448 of file IRModule.h.
Constructor & Destructor Documentation
PyDialects()
mlir::python::PyDialects::PyDialects (PyMlirContextRef contextRef) inline
Definition at line 450 of file IRModule.h.
References mlir::python::BaseContextObject::BaseContextObject().
Member Function Documentation
getDialectForKey()
MlirDialect PyDialects::getDialectForKey (const std::string & key, bool attrError)
Definition at line 900 of file IRCore.cpp.
References mlir::get(), mlir::python::BaseContextObject::getContext(), mlirContextGetOrLoadDialect(), and mlirDialectIsNull().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp