MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation Class Reference
Wrapper around an MlirLocation.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyLocation (PyMlirContextRef contextRef, MlirLocation loc)
operator MlirLocation () const
MlirLocation get () const
void contextExit (const nanobind::object &excType, const nanobind::object &excVal, const nanobind::object &excTb)
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirLocation.
nanobind::typed< nanobind::object, PyLocation > maybeDownCast ()
Returns the most-derived Location subclass registered for this TypeID, or self.
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static nanobind::object contextEnter (nanobind::object location)
Enter and exit the context manager.
static PyLocation createFromCapsule (nanobind::object capsule)
Creates a PyLocation from the MlirLocation wrapped by a capsule.
Detailed Description
Wrapper around an MlirLocation.
Definition at line 317 of file IRCore.h.
Constructor & Destructor Documentation
PyLocation()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::PyLocation (PyMlirContextRef contextRef, MlirLocation loc) inline
Definition at line 319 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyNameLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::castFrom(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::PyConcreteLocation().
Member Function Documentation
contextEnter()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::contextEnter (nanobind::object location) static
Enter and exit the context manager.
Definition at line 836 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
contextExit()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::contextExit (const nanobind::object & excType, const nanobind::object & excVal, const nanobind::object & excTb)
Definition at line 840 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadContextEntry::pushLocation().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
createFromCapsule()
PyLocation mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::createFromCapsule (nanobind::object capsule) static
Creates a PyLocation from the MlirLocation wrapped by a capsule.
Note that PyLocation instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirLocation is taken by calling this function.
Definition at line 828 of file IRCore.cpp.
References mlirPythonLocationToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirLocation mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::get () const inline
Definition at line 323 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFileLineColLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFusedLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyNameLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::castFrom(), maybeDownCast(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::getCapsule ()
Gets a capsule wrapping the void* within the MlirLocation.
Definition at line 824 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
maybeDownCast()
nb::typed< nb::object, PyLocation > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::maybeDownCast ()
Returns the most-derived Location subclass registered for this TypeID, or self.
Definition at line 1890 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::lookupTypeCaster(), mlirAttributeGetDialect(), mlirAttributeGetTypeID(), mlirLocationGetAttribute(), and mlirTypeIDIsNull().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFusedLocation::bindDerived(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirLocation()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::operator MlirLocation () const inline
Definition at line 322 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp