MLIR: mlir::DialectAsmPrinter Class Reference
mlir::DialectAsmPrinter Class Reference abstract
This is a pure-virtual base class that exposes the asmprinter hooks necessary to implement a custom printAttribute/printType() method on a dialect.
#include "mlir/IR/DialectImplementation.h"
Public Member Functions
DialectAsmPrinter ()
virtual ~DialectAsmPrinter ()
virtual raw_ostream & getStream () const =0
virtual void printAttribute (Attribute attr)=0
Print the given attribute to the stream.
virtual void printFloat (const APFloat &value)=0
Print the given floating point value in a stabilized form that can be roundtripped through the IR.
virtual void printType (Type type)=0
Print the given type to the stream.
Detailed Description
This is a pure-virtual base class that exposes the asmprinter hooks necessary to implement a custom printAttribute/printType() method on a dialect.
Definition at line 33 of file DialectImplementation.h.
Constructor & Destructor Documentation
DialectAsmPrinter()
mlir::DialectAsmPrinter::DialectAsmPrinter () inline
Definition at line 35 of file DialectImplementation.h.
References getStream(), printAttribute(), printFloat(), printType(), value, and ~DialectAsmPrinter().
~DialectAsmPrinter()
DialectAsmPrinter::~DialectAsmPrinter () virtual
Definition at line 54 of file AsmPrinter.cpp.
Referenced by DialectAsmPrinter().
Member Function Documentation
getStream()
virtual raw_ostream& mlir::DialectAsmPrinter::getStream () const pure virtual
Referenced by DialectAsmPrinter(), mlir::operator<<(), and print().
printAttribute()
virtual void mlir::DialectAsmPrinter::printAttribute (Attribute attr) pure virtual
Print the given attribute to the stream.
Referenced by DialectAsmPrinter(), and mlir::operator<<().
printFloat()
virtual void mlir::DialectAsmPrinter::printFloat (const APFloat & value) pure virtual
Print the given floating point value in a stabilized form that can be roundtripped through the IR.
This is the companion to the 'parseFloat' hook on the DialectAsmParser.
Referenced by DialectAsmPrinter(), and mlir::operator<<().
printType()
virtual void mlir::DialectAsmPrinter::printType (Type type) pure virtual
Print the given type to the stream.
Referenced by DialectAsmPrinter(), dispatchPrint(), and mlir::operator<<().
The documentation for this class was generated from the following files:
include/mlir/IR/DialectImplementation.h
lib/IR/AsmPrinter.cpp