MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::NoTerminator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::NoTerminator Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Static Public Member Functions
static bool attach (const nanobind::object &opName, PyMlirContext &context)
static void bind (nanobind::module_ &m)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTrait
static bool attach (const nanobind::object &opName, const nanobind::object &target, PyMlirContext &context)
static void bind (nanobind::module_ &m)
Additional Inherited Members
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTrait
static const char * typeIDAttr = "_trait_typeid"
Detailed Description
Definition at line 1988 of file IRCore.h.
Member Function Documentation
attach()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::NoTerminator::attach (const nanobind::object & opName, PyMlirContext & context) static
Definition at line 2642 of file IRCore.cpp.
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::NoTerminator::bind (nanobind::module_ & m) static
Definition at line 2648 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::attachOpTrait(), and mlirDynamicOpTraitNoTerminatorCreate().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp