MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyBlockIterator (PyOperationRef operation, MlirBlock next)
PyBlockIterator & dunderIter ()
nanobind::typed< nanobind::object, PyBlock > dunderNext ()
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 1534 of file IRCore.h.
Constructor & Destructor Documentation
PyBlockIterator()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator::PyBlockIterator (PyOperationRef operation, MlirBlock next) inline
Definition at line 1536 of file IRCore.h.
Referenced by dunderIter().
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator::bind (nanobind::module_ & m) static
Definition at line 230 of file IRCore.cpp.
References dunderIter(), and dunderNext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderIter()
PyBlockIterator & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator::dunderIter () inline
Definition at line 1539 of file IRCore.h.
References PyBlockIterator().
Referenced by bind().
dunderNext()
nb::typed< nb::object, PyBlock > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator::dunderNext ()
Definition at line 217 of file IRCore.cpp.
References mlirBlockGetNextInRegion(), and mlirBlockIsNull().
Referenced by bind().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp