MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute Class Reference
Refinement of PyDenseElementsAttribute for attributes containing floating-point values.
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
nanobind::float_ dunderGetItem (intptr_t pos) const
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseFPElementsAttribute, PyDenseElementsAttribute >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute
intptr_t dunderLen () const
std::unique_ptr< nb_buffer_info > accessBuffer ()
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseElementsAttribute >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseFPElementsAttribute, PyDenseElementsAttribute >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute
static PyDenseElementsAttribute getFromList (const nanobind::typed< nanobind::sequence, PyAttribute > &attributes, std::optional< PyType > explicitType, DefaultingPyMlirContext contextWrapper)
static PyDenseElementsAttribute getFromBuffer (const nb_buffer &array, bool signless, const std::optional< PyType > &explicitType, std::optional< std::vector< int64_t > > explicitShape, DefaultingPyMlirContext contextWrapper)
static PyDenseElementsAttribute getSplat (const PyType &shapedType, PyAttribute &elementAttr)
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseElementsAttribute >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirAttributeIsADenseFPElements
static constexpr const char * pyClassName = "DenseFPElementsAttr"
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseFPElementsAttribute, PyDenseElementsAttribute >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute
static constexpr IsAFunctionTy isaFunction = mlirAttributeIsADenseElements
static constexpr const char * pyClassName = "DenseElementsAttr"
static PyType_Slot slots []
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseElementsAttribute >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseFPElementsAttribute, PyDenseElementsAttribute >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseElementsAttribute >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Static Protected Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute
template<typename ClassT>
static void bindFactoryMethods (ClassT &c, const char *pyClassName)
Registers get/get_splat factory methods with the concrete return type in the nb::sig.
Detailed Description
Refinement of PyDenseElementsAttribute for attributes containing floating-point values.
Supports element access.
Definition at line 545 of file IRAttributes.h.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute::bindDerived (ClassTy & c) static
Definition at line 1238 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::bindFactoryMethods(), dunderGetItem(), and pyClassName.
dunderGetItem()
nb::float_ mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute::dunderGetItem (intptr_t pos) const
Definition at line 1217 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::dunderLen(), mlirAttributeGetType(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatValue(), mlirShapedTypeGetElementType(), mlirTypeIsAF32(), and mlirTypeIsAF64().
Referenced by bindDerived().
PyConcreteAttribute() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute () default
PyConcreteAttribute() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyAttribute & orig) inline
Definition at line 1085 of file IRCore.h.
PyConcreteAttribute() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr) inline
Definition at line 1083 of file IRCore.h.
Member Data Documentation
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute::isaFunction = mlirAttributeIsADenseFPElements static constexpr
Definition at line 549 of file IRAttributes.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::denseTypedElementsAttributeCaster().
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute::pyClassName = "DenseFPElementsAttr" static constexpr
Definition at line 550 of file IRAttributes.h.
Referenced by bindDerived().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRAttributes.h
lib/Bindings/Python/IRAttributes.cpp