MLIR: mlir::query::matcher::internal::Diagnostics Class Reference
mlir::query::matcher::internal::Diagnostics Class Reference
#include "Query/Matcher/Diagnostics.h"
Classes
class ArgStream
Public Member Functions
ArgStream addError (SourceRange range, ErrorType error)
void print (llvm::raw_ostream &os) const
Detailed Description
Definition at line 28 of file Diagnostics.h.
Member Function Documentation
addError()
Diagnostics::ArgStream mlir::query::matcher::internal::Diagnostics::addError (SourceRange range, ErrorType error)
Definition at line 20 of file Diagnostics.cpp.
Referenced by mlir::query::matcher::internal::addError(), mlir::query::matcher::RegistryManager::constructMatcher(), mlir::query::matcher::internal::Parser::parseExpression(), and mlir::query::matcher::internal::Parser::parseMatcherExpression().
print()
void mlir::query::matcher::internal::Diagnostics::print (llvm::raw_ostream & os) const
Definition at line 130 of file Diagnostics.cpp.
The documentation for this class was generated from the following files:
lib/Query/Matcher/Diagnostics.h
lib/Query/Matcher/Diagnostics.cpp