MLIR: mlir::sparse_tensor::ir_detail::LvlTypeParser Class Reference
mlir::sparse_tensor::ir_detail::LvlTypeParser Class Reference
#include "Dialect/SparseTensor/IR/Detail/LvlTypeParser.h"
Public Member Functions
LvlTypeParser ()=default
FailureOr< uint64_t > parseLvlType (AsmParser &parser) const
Detailed Description
Definition at line 18 of file LvlTypeParser.h.
Constructor & Destructor Documentation
LvlTypeParser()
mlir::sparse_tensor::ir_detail::LvlTypeParser::LvlTypeParser () default
Member Function Documentation
parseLvlType()
FailureOr< uint64_t > LvlTypeParser::parseLvlType (AsmParser & parser) const
Definition at line 32 of file LvlTypeParser.cpp.
References mlir::sparse_tensor::Batch, mlir::sparse_tensor::Compressed, mlir::sparse_tensor::Dense, mlir::AsmParser::emitError(), ERROR_IF, FAILURE_IF_FAILED, mlir::AsmParser::getCurrentLocation(), mlir::sparse_tensor::isValidLT(), mlir::sparse_tensor::LooseCompressed, mlir::sparse_tensor::mToBits(), mlir::sparse_tensor::NOutOfM, mlir::sparse_tensor::nToBits(), mlir::AsmParser::OptionalParen, mlir::AsmParser::OptionalSquare, mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalKeyword(), and mlir::sparse_tensor::Singleton.
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/LvlTypeParser.h
lib/Dialect/SparseTensor/IR/Detail/LvlTypeParser.cpp