MLIR: mlir::NestedMatch Class Reference
mlir::NestedMatch Class Reference
An NestedPattern captures nested patterns in the IR.
#include "mlir/Analysis/NestedMatcher.h"
Public Member Functions
NestedMatch (const NestedMatch &)=default
NestedMatch & operator= (const NestedMatch &)=default
operator bool ()
Operation * getMatchedOperation () const
ArrayRef< NestedMatch > getMatchedChildren ()
Static Public Member Functions
static NestedMatch build (Operation *operation, ArrayRef< NestedMatch > nestedMatches)
Friends
class NestedPattern
class NestedPatternContext
Detailed Description
An NestedPattern captures nested patterns in the IR.
It is used in conjunction with a scoped NestedPatternContext which is an llvm::BumpPtrAllocator that handles memory allocations efficiently and avoids ownership issues.
In order to use NestedPatterns, first create a scoped context. When the context goes out of scope, everything is freed. This design simplifies the API by avoiding references to the context and makes it clear that references to matchers must not escape.
Example: { NestedPatternContext context; auto gemmLike = Doall(Doall(Red(LoadStores()))); auto matches = gemmLike.match(f); // do work on matches } // everything is freed
Nested abstraction for matching results. Provides access to the nested Operation* captured by a Matcher.
A NestedMatch contains an Operation* and the children NestedMatch and is thus cheap to copy. NestedMatch is stored in a scoped bumper allocator whose lifetime is managed by an RAII NestedPatternContext.
Definition at line 46 of file NestedMatcher.h.
Constructor & Destructor Documentation
NestedMatch()
mlir::NestedMatch::NestedMatch (const NestedMatch &) default
Member Function Documentation
build()
NestedMatch NestedMatch::build (Operation * operation, ArrayRef< NestedMatch > nestedMatches) static
Definition at line 25 of file NestedMatcher.cpp.
Referenced by mlir::NestedPattern::getDepth().
getMatchedChildren()
ArrayRef<NestedMatch> mlir::NestedMatch::getMatchedChildren () inline
Definition at line 56 of file NestedMatcher.h.
Referenced by getMatchedAffineLoopsRec().
getMatchedOperation()
Operation* mlir::NestedMatch::getMatchedOperation () const inline
Definition at line 55 of file NestedMatcher.h.
Referenced by getMatchedAffineLoopsRec().
operator bool()
mlir::NestedMatch::operator bool () inline explicit
Definition at line 53 of file NestedMatcher.h.
operator=()
NestedMatch& mlir::NestedMatch::operator= (const NestedMatch &) default
Friends And Related Function Documentation
NestedPattern
friend class NestedPattern friend
Definition at line 59 of file NestedMatcher.h.
NestedPatternContext
friend class NestedPatternContext friend
Definition at line 60 of file NestedMatcher.h.
The documentation for this class was generated from the following files:
include/mlir/Analysis/NestedMatcher.h
lib/Analysis/NestedMatcher.cpp