MLIR: mlir::OperandRange Class Reference
mlir::OperandRange Class Reference final
This class implements the operand iterators for the Operation class.
#include "mlir/IR/ValueRange.h"
Public Types
using type_iterator = ValueTypeIterator< iterator >
Returns the types of the values within this range.
using type_range = ValueTypeRange< OperandRange >
Public Member Functions
type_range getTypes () const
type_range getType () const
unsigned getBeginOperandIndex () const
Return the operand index of the first element of this range.
OperandRangeRange split (DenseI32ArrayAttr segmentSizes) const
Split this range into a set of contiguous subranges using the given elements attribute, which contains the sizes of the sub ranges.
Detailed Description
This class implements the operand iterators for the Operation class.
Definition at line 42 of file ValueRange.h.
Member Typedef Documentation
type_iterator
using mlir::OperandRange::type_iterator = ValueTypeIterator<iterator>
Returns the types of the values within this range.
Definition at line 48 of file ValueRange.h.
type_range
using mlir::OperandRange::type_range = ValueTypeRange<OperandRange>
Definition at line 49 of file ValueRange.h.
Member Function Documentation
getBeginOperandIndex()
unsigned OperandRange::getBeginOperandIndex () const
Return the operand index of the first element of this range.
The range must not be empty.
Definition at line 387 of file OperationSupport.cpp.
Referenced by fuse(), mlir::detail::getBranchSuccessorArgument(), mlir::bufferization::detail::getCallerOpOperands(), mlir::affine::AffineBound::getOperand(), and mlir::SuccessorOperands::getOperandIndex().
getType()
OperandRange::type_range OperandRange::getType () const
Definition at line 32 of file ValueRange.cpp.
References getTypes().
Referenced by getTreePredicates(), verifyNamedSequenceOp(), and verifyYieldingSingleBlockOp().
getTypes()
OperandRange::type_range OperandRange::getTypes () const
Definition at line 28 of file ValueRange.cpp.
Referenced by mlir::impl::foldCastInterfaceOp(), mlir::Operation::getOperandTypes(), getType(), mlir::sparse_tensor::hasAnySparseOperand(), and legalizeUnresolvedMaterialization().
split()
OperandRangeRange OperandRange::split (DenseI32ArrayAttr segmentSizes) const
Split this range into a set of contiguous subranges using the given elements attribute, which contains the sizes of the sub ranges.
Definition at line 392 of file OperationSupport.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/ValueRange.h
lib/IR/OperationSupport.cpp
lib/IR/ValueRange.cpp