MLIR: mlir::ShapeAdaptor Class Reference
mlir::ShapeAdaptor Class Reference
Adaptor class to abstract the differences between whether value is from a ShapedType or ShapedTypeComponents or DenseIntElementsAttribute.
#include "mlir/Interfaces/InferTypeOpInterface.h"
Public Member Functions
ShapeAdaptor (Type t)
ShapeAdaptor (Attribute t)
ShapeAdaptor (ShapedTypeComponents *components)
ShapeAdaptor (ShapedTypeComponents &components)
bool hasRank () const
Returns whether the shape has a rank.
Type getElementType () const
Returns the element type.
void getDims (SmallVectorImpl< int64_t > &res) const
Populates the dimensions from shape referenced.
void getDims (ShapedTypeComponents &res) const
Populates the dimensions of the ShapeTypeComponents.
int64_t getDimSize (int index) const
Returns the size of the index'th dimension.
bool isDynamicDim (int index) const
Returns whether the index'th dimension is dynamic.
bool hasStaticShape () const
Returns whether the shape is fully static.
int64_t getRank () const
Returns the rank of the shape.
int64_t getNumElements () const
Returns the number of elements in the shape.
operator bool () const
Returns whether valid (non-null) shape.
void dump () const
Dumps textual repesentation to stderr.
Detailed Description
Adaptor class to abstract the differences between whether value is from a ShapedType or ShapedTypeComponents or DenseIntElementsAttribute.
Definition at line 43 of file InferTypeOpInterface.h.
Constructor & Destructor Documentation
ShapeAdaptor() [1/4]
mlir::ShapeAdaptor::ShapeAdaptor (Type t) inline
Definition at line 45 of file InferTypeOpInterface.h.
ShapeAdaptor() [2/4]
mlir::ShapeAdaptor::ShapeAdaptor (Attribute t) inline
Definition at line 49 of file InferTypeOpInterface.h.
ShapeAdaptor() [3/4]
mlir::ShapeAdaptor::ShapeAdaptor (ShapedTypeComponents * components) inline
Definition at line 53 of file InferTypeOpInterface.h.
ShapeAdaptor() [4/4]
mlir::ShapeAdaptor::ShapeAdaptor (ShapedTypeComponents & components) inline
Definition at line 54 of file InferTypeOpInterface.h.
Member Function Documentation
dump()
void ShapeAdaptor::dump () const
Dumps textual repesentation to stderr.
Definition at line 183 of file InferTypeOpInterface.cpp.
References getDims(), getRank(), and hasRank().
getDims() [1/2]
void ShapeAdaptor::getDims (ShapedTypeComponents & res) const
Populates the dimensions of the ShapeTypeComponents.
Requires: shape is ranked.
Definition at line 114 of file InferTypeOpInterface.cpp.
References getDims(), and hasRank().
getDims() [2/2]
void ShapeAdaptor::getDims (SmallVectorImpl< int64_t > & res) const
Populates the dimensions from shape referenced.
Requires: shape is ranked.
Definition at line 97 of file InferTypeOpInterface.cpp.
References hasRank().
Referenced by dump(), getDims(), ReduceInferReturnTypes(), and mlir::ShapedTypeComponents::ShapedTypeComponents().
getDimSize()
int64_t ShapeAdaptor::getDimSize (int index) const
Returns the size of the index'th dimension.
Requires: shape is ranked.
Definition at line 120 of file InferTypeOpInterface.cpp.
References hasRank().
Referenced by isDynamicDim(), and poolingInferReturnTypes().
getElementType()
Type ShapeAdaptor::getElementType () const
Returns the element type.
Definition at line 87 of file InferTypeOpInterface.cpp.
Referenced by mlir::ShapedTypeComponents::ShapedTypeComponents().
getNumElements()
int64_t ShapeAdaptor::getNumElements () const
Returns the number of elements in the shape.
Requires: hasStaticShape
Definition at line 158 of file InferTypeOpInterface.cpp.
References hasStaticShape().
Referenced by errorIfShapeNotSizeOne().
getRank()
int64_t ShapeAdaptor::getRank () const
Returns the rank of the shape.
Requires: shape is ranked.
Definition at line 132 of file InferTypeOpInterface.cpp.
References hasRank().
Referenced by dump(), and ReduceInferReturnTypes().
hasRank()
bool ShapeAdaptor::hasRank () const
Returns whether the shape has a rank.
Definition at line 77 of file InferTypeOpInterface.cpp.
Referenced by dump(), errorIfShapeNotSizeOne(), getDims(), getDims(), getDimSize(), getRank(), hasStaticShape(), ReduceInferReturnTypes(), and mlir::ShapedTypeComponents::ShapedTypeComponents().
hasStaticShape()
bool ShapeAdaptor::hasStaticShape () const
Returns whether the shape is fully static.
Definition at line 141 of file InferTypeOpInterface.cpp.
References hasRank().
Referenced by errorIfShapeNotSizeOne(), and getNumElements().
isDynamicDim()
bool mlir::ShapeAdaptor::isDynamicDim (int index) const inline
Returns whether the index'th dimension is dynamic.
Requires: shape is ranked.
Definition at line 76 of file InferTypeOpInterface.h.
References getDimSize().
operator bool()
mlir::ShapeAdaptor::operator bool () const inline explicit
Returns whether valid (non-null) shape.
Definition at line 92 of file InferTypeOpInterface.h.
The documentation for this class was generated from the following files:
include/mlir/Interfaces/InferTypeOpInterface.h
lib/Interfaces/InferTypeOpInterface.cpp