MLIR: mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT > Class Template Reference
mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT > Class Template Reference
Public Types
using Base = MathExtendToSupportedTypesBase
Public Member Functions
MathExtendToSupportedTypesBase ()
MathExtendToSupportedTypesBase (const MathExtendToSupportedTypesBase &other)
MathExtendToSupportedTypesBase & operator= (const MathExtendToSupportedTypesBase &)=delete
MathExtendToSupportedTypesBase (MathExtendToSupportedTypesBase &&)=delete
MathExtendToSupportedTypesBase & operator= (MathExtendToSupportedTypesBase &&)=delete
~MathExtendToSupportedTypesBase ()=default
::llvm::StringRef getArgument () const override
Return the command line argument used when registering this pass.
::llvm::StringRef getDescription () const override
Return the command line description used when registering this pass.
::llvm::StringRef getName () const override
Returns the derived pass name.
std::unique_ptr<::mlir::Pass > clonePass () const override
A clone method to create a copy of this pass.
void getDependentDialects (::mlir::DialectRegistry &registry) const override
Return the dialect that must be loaded in the context before this pass.
MathExtendToSupportedTypesBase (MathExtendToSupportedTypesOptions options)
Explicitly declare the TypeID for this class.
Public Member Functions inherited from mlir::OperationPass< OpT >
~OperationPass () override=default
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Static Public Member Functions
static constexpr ::llvm::StringLiteral getArgumentName ()
Returns the command-line argument attached to this pass.
static constexpr ::llvm::StringLiteral getPassName ()
Returns the derived pass name.
static bool classof (const ::mlir::Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Attributes
::mlir::Pass::ListOption< std::string > extraTypeStrs {*this, "extra-types", ::llvm::cl::desc(R"PO(MLIR types with arithmetic support on a given target (f64 and f32 are implicitly supported))PO")}
::mlir::Pass::Option< std::string > targetTypeStr {*this, "target-type", ::llvm::cl::desc(R"PO(MLIR type to convert the unsupported source types to)PO"), ::llvm::cl::init("f32")}
Friends
std::unique_ptr<::mlir::Pass > createMathExtendToSupportedTypes ()
std::unique_ptr<::mlir::Pass > createMathExtendToSupportedTypes (MathExtendToSupportedTypesOptions options)
Additional Inherited Members
Protected Member Functions inherited from mlir::OperationPass< OpT >
OperationPass (TypeID passID)
OperationPass (const OperationPass &)=default
OperationPass & operator= (const OperationPass &)=delete
OperationPass (OperationPass &&)=delete
OperationPass & operator= (OperationPass &&)=delete
bool canScheduleOn (RegisteredOperationName opName) const final
Indicate if the current pass can be scheduled on the given operation type.
OpT getOperation ()
Return the current operation being transformed.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current operation of the specific derived operation type.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
virtual bool canScheduleOn (Operation *op) const
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Static Protected Member Functions inherited from mlir::OperationPass< OpT >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Detailed Description
template<typename DerivedT>
class mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >
Definition at line 132 of file ExtendToSupportedTypes.cpp.
Member Typedef Documentation
Base
template<typename DerivedT> using mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::Base = MathExtendToSupportedTypesBase
Definition at line 134 of file ExtendToSupportedTypes.cpp.
Constructor & Destructor Documentation
MathExtendToSupportedTypesBase() [1/4]
template<typename DerivedT> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::MathExtendToSupportedTypesBase () inline
Definition at line 136 of file ExtendToSupportedTypes.cpp.
MathExtendToSupportedTypesBase() [2/4]
template<typename DerivedT> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::MathExtendToSupportedTypesBase (const MathExtendToSupportedTypesBase< DerivedT > & other) inline
Definition at line 137 of file ExtendToSupportedTypes.cpp.
MathExtendToSupportedTypesBase() [3/4]
template<typename DerivedT> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::MathExtendToSupportedTypesBase (MathExtendToSupportedTypesBase< DerivedT > &&) delete
References extraTypeStrs.
~MathExtendToSupportedTypesBase()
template<typename DerivedT> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::~MathExtendToSupportedTypesBase () default
References mlir::arith::parseFloatType().
MathExtendToSupportedTypesBase() [4/4]
template<typename DerivedT> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::MathExtendToSupportedTypesBase (MathExtendToSupportedTypesOptions options) inline
Explicitly declare the TypeID for this class.
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 178 of file ExtendToSupportedTypes.cpp.
Member Function Documentation
classof()
template<typename DerivedT> bool mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::classof (const ::mlir::Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 158 of file ExtendToSupportedTypes.cpp.
References mlir::patterns, and target.
clonePass()
template<typename DerivedT> std::unique_ptr<::mlir::Pass > mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::clonePass () const inline override virtual
A clone method to create a copy of this pass.
Implements mlir::Pass.
Definition at line 163 of file ExtendToSupportedTypes.cpp.
References mlir::Pass::signalPassFailure().
getArgument()
template<typename DerivedT> ::llvm::StringRef mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 147 of file ExtendToSupportedTypes.cpp.
getArgumentName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getArgumentName () inline static
Returns the command-line argument attached to this pass.
Definition at line 144 of file ExtendToSupportedTypes.cpp.
References mlir::Pass::signalPassFailure().
getDependentDialects()
template<typename DerivedT> void mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getDependentDialects (::mlir::DialectRegistry & registry) const inline override
Return the dialect that must be loaded in the context before this pass.
Definition at line 168 of file ExtendToSupportedTypes.cpp.
getDescription()
template<typename DerivedT> ::llvm::StringRef mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 149 of file ExtendToSupportedTypes.cpp.
getName()
template<typename DerivedT> ::llvm::StringRef mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 155 of file ExtendToSupportedTypes.cpp.
getPassName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getPassName () inline static
Returns the derived pass name.
Definition at line 152 of file ExtendToSupportedTypes.cpp.
References b.
operator=() [1/2]
template<typename DerivedT> MathExtendToSupportedTypesBase & mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::operator= (const MathExtendToSupportedTypesBase< DerivedT > &) delete
operator=() [2/2]
template<typename DerivedT> MathExtendToSupportedTypesBase & mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::operator= (MathExtendToSupportedTypesBase< DerivedT > &&) delete
Friends And Related Symbol Documentation
createMathExtendToSupportedTypes [1/2]
template<typename DerivedT> std::unique_ptr<::mlir::Pass > createMathExtendToSupportedTypes () friend
Definition at line 187 of file ExtendToSupportedTypes.cpp.
createMathExtendToSupportedTypes [2/2]
template<typename DerivedT> std::unique_ptr<::mlir::Pass > createMathExtendToSupportedTypes (MathExtendToSupportedTypesOptions options) friend
Definition at line 191 of file ExtendToSupportedTypes.cpp.
Member Data Documentation
extraTypeStrs
template<typename DerivedT> ::mlir::Pass::ListOption<std::string> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::extraTypeStrs {*this, "extra-types", ::llvm::cl::desc(R"PO(MLIR types with arithmetic support on a given target (f64 and f32 are implicitly supported))PO")} protected
Definition at line 183 of file ExtendToSupportedTypes.cpp.
Referenced by MathExtendToSupportedTypesBase().
targetTypeStr
template<typename DerivedT> ::mlir::Pass::Option<std::string> mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::targetTypeStr {*this, "target-type", ::llvm::cl::desc(R"PO(MLIR type to convert the unsupported source types to)PO"), ::llvm::cl::init("f32")} protected
Definition at line 184 of file ExtendToSupportedTypes.cpp.
The documentation for this class was generated from the following file:
lib/Dialect/Math/Transforms/ExtendToSupportedTypes.cpp