MLIR: mlir::NestedPattern Class Reference
mlir::NestedPattern Class Reference
#include "mlir/Analysis/NestedMatcher.h"
Public Member Functions
NestedPattern (ArrayRef< NestedPattern > nested, FilterFunctionType filter=defaultFilterFunction)
NestedPattern (const NestedPattern &other)
NestedPattern & operator= (const NestedPattern &other)
~NestedPattern ()
void match (FuncOp func, SmallVectorImpl< NestedMatch > *matches)
Returns all the top-level matches in func.
void match (Operation *op, SmallVectorImpl< NestedMatch > *matches)
Returns all the top-level matches in op.
unsigned getDepth () const
Returns the depth of the pattern.
Friends
class NestedPatternContext
class NestedMatch
struct State
Detailed Description
Definition at line 92 of file NestedMatcher.h.
Constructor & Destructor Documentation
NestedPattern() [1/2]
NestedPattern::NestedPattern (ArrayRef< NestedPattern > nested, FilterFunctionType filter = defaultFilterFunction)
Definition at line 56 of file NestedMatcher.cpp.
Referenced by mlir::matcher::For(), mlir::matcher::If(), and mlir::matcher::Op().
NestedPattern() [2/2]
NestedPattern::NestedPattern (const NestedPattern & other)
Definition at line 62 of file NestedMatcher.cpp.
~NestedPattern()
mlir::NestedPattern::~NestedPattern () inline
Definition at line 99 of file NestedMatcher.h.
Member Function Documentation
getDepth()
unsigned NestedPattern::getDepth () const
Returns the depth of the pattern.
Definition at line 75 of file NestedMatcher.cpp.
References mlir::NestedMatch::build(), max(), and op.
match() [1/2]
void mlir::NestedPattern::match (FuncOp func, SmallVectorImpl< NestedMatch > * matches) inline
Returns all the top-level matches in func.
Definition at line 107 of file NestedMatcher.h.
References op.
Referenced by isVectorizableLoopBodyWithOpCond().
match() [2/2]
void mlir::NestedPattern::match (Operation * op, SmallVectorImpl< NestedMatch > * matches) inline
Returns all the top-level matches in op.
Definition at line 112 of file NestedMatcher.h.
References mlir::Operation::walk().
operator=()
NestedPattern & NestedPattern::operator= (const NestedPattern & other)
Definition at line 67 of file NestedMatcher.cpp.
Friends And Related Function Documentation
NestedMatch
friend class NestedMatch friend
Definition at line 121 of file NestedMatcher.h.
NestedPatternContext
friend class NestedPatternContext friend
Definition at line 120 of file NestedMatcher.h.
State
friend struct State friend
Definition at line 122 of file NestedMatcher.h.
The documentation for this class was generated from the following files:
include/mlir/Analysis/NestedMatcher.h
lib/Analysis/NestedMatcher.cpp