MLIR: mlir::AsmParser::KeywordSwitch< ResultT > Class Template Reference
mlir::AsmParser::KeywordSwitch< ResultT > Class Template Reference
This class represents a StringSwitch like class that is useful for parsing expected keywords.
#include "mlir/IR/OpImplementation.h"
Public Member Functions
KeywordSwitch (AsmParser &parser, StringRef *keyword=nullptr)
KeywordSwitch & Case (StringLiteral str, ResultT value)
Case that uses the provided value when true.
KeywordSwitch & Default (ResultT value)
template<typename FnT>
std::enable_if_t<!std::is_convertible< FnT, ResultT >::value, KeywordSwitch & > Case (StringLiteral str, FnT &&fn)
Case that invokes the provided functor when true.
template<typename FnT>
std::enable_if_t<!std::is_convertible< FnT, ResultT >::value, KeywordSwitch & > Default (FnT &&fn)
bool hasValue () const
Returns true if this switch has a value yet.
operator ResultT ()
Return the result of the switch.
Detailed Description
template<typename ResultT = ParseResult>
class mlir::AsmParser::KeywordSwitch< ResultT >
This class represents a StringSwitch like class that is useful for parsing expected keywords.
On construction, unless a non-empty keyword is provided, it invokes parseKeyword and processes each of the provided cases statements until a match is hit. The provided ResultT must be assignable from failure().
Definition at line 861 of file OpImplementation.h.
Constructor & Destructor Documentation
KeywordSwitch()
template<typename ResultT = ParseResult> mlir::AsmParser::KeywordSwitch< ResultT >::KeywordSwitch (AsmParser & parser, StringRef * keyword = nullptr) inline
Definition at line 863 of file OpImplementation.h.
References mlir::AsmParser::AsmParser(), mlir::AsmParser::getCurrentLocation(), and if().
Referenced by Case(), and Default().
Member Function Documentation
Case() [1/2]
template<typename ResultT = ParseResult> template<typename FnT> std::enable_if_t<!std::is_convertible< FnT, ResultT >::value, KeywordSwitch & > mlir::AsmParser::KeywordSwitch< ResultT >::Case (StringLiteral str, FnT && fn) inline
Case that invokes the provided functor when true.
The parameters passed to the functor are the keyword, and the location of the keyword (in case any errors need to be emitted).
Definition at line 882 of file OpImplementation.h.
Case() [2/2]
template<typename ResultT = ParseResult> KeywordSwitch & mlir::AsmParser::KeywordSwitch< ResultT >::Case (StringLiteral str, ResultT value) inline
Case that uses the provided value when true.
Definition at line 871 of file OpImplementation.h.
References Case(), and KeywordSwitch().
Referenced by Case().
Default() [1/2]
template<typename ResultT = ParseResult> template<typename FnT> std::enable_if_t<!std::is_convertible< FnT, ResultT >::value, KeywordSwitch & > mlir::AsmParser::KeywordSwitch< ResultT >::Default (FnT && fn) inline
Definition at line 895 of file OpImplementation.h.
Default() [2/2]
template<typename ResultT = ParseResult> KeywordSwitch & mlir::AsmParser::KeywordSwitch< ResultT >::Default (ResultT value) inline
Definition at line 874 of file OpImplementation.h.
References Default(), and KeywordSwitch().
Referenced by Default().
hasValue()
template<typename ResultT = ParseResult> bool mlir::AsmParser::KeywordSwitch< ResultT >::hasValue () const inline
Returns true if this switch has a value yet.
Definition at line 902 of file OpImplementation.h.
operator ResultT()
template<typename ResultT = ParseResult> mlir::AsmParser::KeywordSwitch< ResultT >::operator ResultT () inline nodiscard
Return the result of the switch.
Definition at line 905 of file OpImplementation.h.
The documentation for this class was generated from the following file:
include/mlir/IR/OpImplementation.h