MLIR: lib/TableGen/Class.cpp File Reference
Class.cpp File Reference
#include "mlir/TableGen/Class.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Debug.h"
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::tblgen
Functions
static StringRef getSpaceAfterType (StringRef type)
Returns space to be emitted after the given C++ type.
raw_ostream & mlir::tblgen::operator<< (raw_ostream &os, Visibility visibility)
Method * insertAndPruneMethods (std::vector< std::unique_ptr< Method > > &methods, std::unique_ptr< Method > newMethod)
Function Documentation
getSpaceAfterType()
StringRef getSpaceAfterType (StringRef type) static
Returns space to be emitted after the given C++ type.
return "" if the ends with '&' or '*', or is empty, else returns " ".
Definition at line 18 of file Class.cpp.
Referenced by mlir::tblgen::MethodParameter::writeDeclTo(), mlir::tblgen::MethodSignature::writeDeclTo(), mlir::tblgen::MethodParameter::writeDefTo(), and mlir::tblgen::MethodSignature::writeDefTo().
insertAndPruneMethods()
Method * insertAndPruneMethods (std::vector< std::unique_ptr< Method > > & methods, std::unique_ptr< Method > newMethod)
Definition at line 408 of file Class.cpp.