MLIR: mlir::SideEffects::Resource Class Reference
mlir::SideEffects::Resource Class Reference abstract
This class represents a specific resource that an effect applies to.
#include "mlir/Interfaces/SideEffectInterfaces.h"
Classes
class Base
This base class is used for derived effects that are non-parametric.
Public Member Functions
virtual ~Resource ()=default
TypeID getResourceID () const
Return the unique identifier for the base resource class.
virtual StringRef getName ()=0
Return a string name of the resource.
Protected Member Functions
Resource (TypeID id)
Detailed Description
This class represents a specific resource that an effect applies to.
This class represents an abstract interface for a given resource.
Definition at line 79 of file SideEffectInterfaces.h.
Constructor & Destructor Documentation
~Resource()
virtual mlir::SideEffects::Resource::~Resource () virtual default
Resource()
mlir::SideEffects::Resource::Resource (TypeID id) inline protected
Definition at line 114 of file SideEffectInterfaces.h.
Referenced by mlir::SideEffects::Resource::Base< DerivedResource, BaseResource >::classof().
Member Function Documentation
getName()
virtual StringRef mlir::SideEffects::Resource::getName () pure virtual
Return a string name of the resource.
Implemented in mlir::acc::ConstructResource, mlir::acc::CurrentDeviceIdResource, mlir::acc::RuntimeCounters, mlir::SideEffects::AutomaticAllocationScopeResource, mlir::SideEffects::DefaultResource, mlir::transform::PayloadIRResource, and mlir::transform::TransformMappingResource.
getResourceID()
TypeID mlir::SideEffects::Resource::getResourceID () const inline
Return the unique identifier for the base resource class.
Definition at line 108 of file SideEffectInterfaces.h.
Referenced by mlir::SideEffects::Resource::Base< DerivedResource, BaseResource >::classof(), and mayAlias().
The documentation for this class was generated from the following file:
include/mlir/Interfaces/SideEffectInterfaces.h