MLIR: mlir::query::matcher::internal::Parser::RegistrySema Class Reference
mlir::query::matcher::internal::Parser::RegistrySema Class Reference
#include "Query/Matcher/Parser.h"
Public Member Functions
RegistrySema (const Registry &matcherRegistry)
~RegistrySema () override
std::optional< MatcherCtor > lookupMatcherCtor (llvm::StringRef matcherName) override
VariantMatcher actOnMatcherExpression (MatcherCtor Ctor, SourceRange NameRange, StringRef functionName, ArrayRef< ParserValue > Args, Diagnostics *Error) override
std::vector< ArgKind > getAcceptedCompletionTypes (llvm::ArrayRef< std::pair< MatcherCtor, unsigned >> context) override
std::vector< MatcherCompletion > getMatcherCompletions (llvm::ArrayRef< ArgKind > acceptedTypes) override
Public Member Functions inherited from mlir::query::matcher::internal::Parser::Sema
virtual ~Sema ()
virtual VariantMatcher actOnMatcherExpression (MatcherCtor ctor, SourceRange nameRange, llvm::StringRef functionName, llvm::ArrayRef< ParserValue > args, Diagnostics *error)=0
Detailed Description
Definition at line 89 of file Parser.h.
Constructor & Destructor Documentation
RegistrySema()
mlir::query::matcher::internal::Parser::RegistrySema::RegistrySema (const Registry & matcherRegistry) inline
Definition at line 91 of file Parser.h.
~RegistrySema()
mlir::query::matcher::internal::Parser::RegistrySema::~RegistrySema () override default
Member Function Documentation
actOnMatcherExpression()
VariantMatcher mlir::query::matcher::internal::Parser::RegistrySema::actOnMatcherExpression (MatcherCtor Ctor, SourceRange NameRange, StringRef functionName, ArrayRef< ParserValue > Args, Diagnostics * Error) override
Definition at line 571 of file Parser.cpp.
References mlir::query::matcher::RegistryManager::constructMatcher().
getAcceptedCompletionTypes()
std::vector< ArgKind > mlir::query::matcher::internal::Parser::RegistrySema::getAcceptedCompletionTypes (llvm::ArrayRef< std::pair< MatcherCtor, unsigned >> context) override virtual
Reimplemented from mlir::query::matcher::internal::Parser::Sema.
Definition at line 578 of file Parser.cpp.
References mlir::query::matcher::RegistryManager::getAcceptedCompletionTypes().
getMatcherCompletions()
std::vector< MatcherCompletion > mlir::query::matcher::internal::Parser::RegistrySema::getMatcherCompletions (llvm::ArrayRef< ArgKind > acceptedTypes) override virtual
Reimplemented from mlir::query::matcher::internal::Parser::Sema.
Definition at line 583 of file Parser.cpp.
References mlir::query::matcher::RegistryManager::getMatcherCompletions().
lookupMatcherCtor()
std::optional< MatcherCtor > mlir::query::matcher::internal::Parser::RegistrySema::lookupMatcherCtor (llvm::StringRef matcherName) override virtual
Implements mlir::query::matcher::internal::Parser::Sema.
Definition at line 567 of file Parser.cpp.
References mlir::query::matcher::RegistryManager::lookupMatcherCtor().
The documentation for this class was generated from the following files:
lib/Query/Matcher/Parser.h
lib/Query/Matcher/Parser.cpp