MLIR: mlir::NVVM::SerializeGPUModuleBase Class Reference
mlir::NVVM::SerializeGPUModuleBase Class Reference
Base class for all NVVM serializations from GPU modules into binary strings.
#include "mlir/Target/LLVM/NVVM/Utils.h"
Public Member Functions
SerializeGPUModuleBase (Operation &module, NVVMTargetAttr target, const gpu::TargetOptions &targetOptions={})
Initializes the toolkitPath with the path in targetOptions or if empty with the path in getCUDAToolkitPath.
NVVMTargetAttr getTarget () const
Returns the target attribute.
StringRef getToolkitPath () const
Returns the CUDA toolkit path.
ArrayRef< Attribute > getLibrariesToLink () const
Returns the bitcode libraries to be linked into the gpu module after translation to LLVM IR.
LogicalResult appendStandardLibs ()
Appends nvvm/libdevice.bc into librariesToLink.
std::optional< SmallVector< std::unique_ptr< llvm::Module > > > loadBitcodeFiles (llvm::Module &module) override
Loads the bitcode files in librariesToLink.
Public Member Functions inherited from mlir::LLVM::ModuleToObject
ModuleToObject (Operation &module, StringRef triple, StringRef chip, StringRef features={}, int optLevel=3, function_ref< void(llvm::Module &)> initialLlvmIRCallback={}, function_ref< void(llvm::Module &)> linkedLlvmIRCallback={}, function_ref< void(llvm::Module &)> optimizedLlvmIRCallback={}, function_ref< void(StringRef)> isaCallback={})
virtual ~ModuleToObject ()
Operation & getOperation ()
Returns the operation being serialized.
virtual std::optional< SmallVector< char, 0 > > run ()
Runs the serialization pipeline, returning std::nullopt on error.
Static Public Member Functions
static void init ()
Initializes the LLVM NVPTX target by safely calling LLVMInitializeNVPTX* methods if available.
Protected Attributes
NVVMTargetAttr target
NVVM target attribute.
std::string toolkitPath
CUDA toolkit path.
SmallVector< Attribute > librariesToLink
List of LLVM bitcode to link into after translation to LLVM IR.
Protected Attributes inherited from mlir::LLVM::ModuleToObject
Operation & module
Module to transform to a binary object.
StringRef triple
Target triple.
StringRef chip
Target chip.
StringRef features
Target features.
int optLevel
Optimization level.
function_ref< void(llvm::Module &)> initialLlvmIRCallback
Callback invoked with the initial LLVM IR for the device module.
function_ref< void(llvm::Module &)> linkedLlvmIRCallback
Callback invoked with LLVM IR for the device module after linking the device libraries.
function_ref< void(llvm::Module &)> optimizedLlvmIRCallback
Callback invoked with LLVM IR for the device module after LLVM optimizations but before codegen.
function_ref< void(StringRef)> isaCallback
Callback invoked with the target ISA for the device, for example PTX assembly.
Additional Inherited Members
Protected Member Functions inherited from mlir::LLVM::ModuleToObject
virtual void setDataLayoutAndTriple (llvm::Module &module)
Hook for computing the Datalayout.
virtual LogicalResult handleBitcodeFile (llvm::Module &module)
Hook for performing additional actions on a loaded bitcode file.
virtual void handleModulePreLink (llvm::Module &module)
Hook for performing additional actions on the llvmModule pre linking.
virtual void handleModulePostLink (llvm::Module &module)
Hook for performing additional actions on the llvmModule post linking.
virtual std::optional< SmallVector< char, 0 > > moduleToObject (llvm::Module &llvmModule)
Serializes the LLVM IR bitcode to an object file, by default it serializes to LLVM bitcode.
std::optional< llvm::TargetMachine * > getOrCreateTargetMachine ()
Create the target machine based on the target triple and chip.
std::unique_ptr< llvm::Module > loadBitcodeFile (llvm::LLVMContext &context, StringRef path)
Loads a bitcode file from path.
LogicalResult loadBitcodeFilesFromList (llvm::LLVMContext &context, ArrayRef< Attribute > librariesToLink, SmallVector< std::unique_ptr< llvm::Module > > &llvmModules, bool failureOnError=true)
Loads multiple bitcode files.
std::unique_ptr< llvm::Module > translateToLLVMIR (llvm::LLVMContext &llvmContext)
Translates the operation to LLVM IR.
LogicalResult linkFiles (llvm::Module &module, SmallVector< std::unique_ptr< llvm::Module > > &&libs)
Link the llvmModule to other bitcode file.
virtual LogicalResult optimizeModule (llvm::Module &module, int optL)
Optimize the module.
Static Protected Member Functions inherited from mlir::LLVM::ModuleToObject
static std::optional< std::string > translateToISA (llvm::Module &llvmModule, llvm::TargetMachine &targetMachine)
Utility function for translating to ISA, returns std::nullopt on failure.
Detailed Description
Base class for all NVVM serializations from GPU modules into binary strings.
By default this class serializes into LLVM bitcode.
Definition at line 32 of file Utils.h.
Constructor & Destructor Documentation
SerializeGPUModuleBase()
SerializeGPUModuleBase::SerializeGPUModuleBase (Operation & module, NVVMTargetAttr target, const gpu::TargetOptions & targetOptions = {})
Initializes the toolkitPath with the path in targetOptions or if empty with the path in getCUDAToolkitPath.
Definition at line 98 of file Target.cpp.
References appendStandardLibs(), mlir::NVVM::getCUDAToolkitPath(), getLibrariesToLink(), getToolkitPath(), librariesToLink, mlir::LLVM::ModuleToObject::module, mlir::LLVM::ModuleToObject::ModuleToObject(), target, and toolkitPath.
Member Function Documentation
appendStandardLibs()
LogicalResult SerializeGPUModuleBase::appendStandardLibs ()
Appends nvvm/libdevice.bc into librariesToLink.
Returns failure if the library couldn't be found.
Definition at line 144 of file Target.cpp.
References _mlir_embedded_libdevice, _mlir_embedded_libdevice_size, mlir::UnmanagedAsmResourceBlob::allocateInferAlign(), mlir::Operation::emitError(), mlir::MLIRContext::getLoadedDialect(), mlir::DialectResourceBlobHandle< BuiltinDialect >::getManagerInterface(), mlir::LLVM::ModuleToObject::getOperation(), getToolkitPath(), librariesToLink, success(), and target.
Referenced by SerializeGPUModuleBase().
getLibrariesToLink()
ArrayRef< Attribute > SerializeGPUModuleBase::getLibrariesToLink () const
Returns the bitcode libraries to be linked into the gpu module after translation to LLVM IR.
Definition at line 139 of file Target.cpp.
References librariesToLink.
Referenced by SerializeGPUModuleBase().
getTarget()
NVVMTargetAttr SerializeGPUModuleBase::getTarget () const
Returns the target attribute.
Definition at line 135 of file Target.cpp.
References target.
getToolkitPath()
StringRef SerializeGPUModuleBase::getToolkitPath () const
Returns the CUDA toolkit path.
Definition at line 137 of file Target.cpp.
References toolkitPath.
Referenced by appendStandardLibs(), and SerializeGPUModuleBase().
init()
void SerializeGPUModuleBase::init () static
Initializes the LLVM NVPTX target by safely calling LLVMInitializeNVPTX* methods if available.
Definition at line 122 of file Target.cpp.
loadBitcodeFiles()
std::optional< SmallVector< std::unique_ptr< llvm::Module > > > SerializeGPUModuleBase::loadBitcodeFiles (llvm::Module & module) override virtual
Loads the bitcode files in librariesToLink.
Reimplemented from mlir::LLVM::ModuleToObject.
Definition at line 197 of file Target.cpp.
References librariesToLink, mlir::LLVM::ModuleToObject::loadBitcodeFilesFromList(), and mlir::LLVM::ModuleToObject::module.
Member Data Documentation
librariesToLink
SmallVector<Attribute> mlir::NVVM::SerializeGPUModuleBase::librariesToLink protected
List of LLVM bitcode to link into after translation to LLVM IR.
The attributes can be StringAttr pointing to a file path, or a Resource blob pointing to the LLVM bitcode in-memory.
Definition at line 71 of file Utils.h.
Referenced by appendStandardLibs(), getLibrariesToLink(), loadBitcodeFiles(), and SerializeGPUModuleBase().
target
NVVMTargetAttr mlir::NVVM::SerializeGPUModuleBase::target protected
NVVM target attribute.
Definition at line 63 of file Utils.h.
Referenced by appendStandardLibs(), getTarget(), and SerializeGPUModuleBase().
toolkitPath
std::string mlir::NVVM::SerializeGPUModuleBase::toolkitPath protected
CUDA toolkit path.
Definition at line 66 of file Utils.h.
Referenced by getToolkitPath(), and SerializeGPUModuleBase().
The documentation for this class was generated from the following files:
include/mlir/Target/LLVM/NVVM/Utils.h
lib/Target/LLVM/NVVM/Target.cpp