MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyOpOperand (MlirOpOperand opOperand)
operator MlirOpOperand () const
nanobind::typed< nanobind::object, PyOpView > getOwner () const
size_t getOperandNumber () const
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 1612 of file IRCore.h.
Constructor & Destructor Documentation
PyOpOperand()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::PyOpOperand (MlirOpOperand opOperand) inline
Definition at line 1614 of file IRCore.h.
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::bind (nanobind::module_ & m) static
Definition at line 374 of file IRCore.cpp.
References mlirOpOperandGetOperandNumber().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getOperandNumber()
size_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::getOperandNumber () const
Definition at line 370 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator::dunderNext().
getOwner()
nb::typed< nb::object, PyOpView > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::getOwner () const
Definition at line 363 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationList::dunderLen().
operator MlirOpOperand()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::operator MlirOpOperand () const inline
Definition at line 1615 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp