MLIR: mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT > Class Template Reference
mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT > Class Template Reference
Public Types
using Base = AffineDataCopyGenerationBase
Public Member Functions
AffineDataCopyGenerationBase ()
AffineDataCopyGenerationBase (const AffineDataCopyGenerationBase &other)
AffineDataCopyGenerationBase & operator= (const AffineDataCopyGenerationBase &)=delete
AffineDataCopyGenerationBase (AffineDataCopyGenerationBase &&)=delete
AffineDataCopyGenerationBase & operator= (AffineDataCopyGenerationBase &&)=delete
~AffineDataCopyGenerationBase ()=default
::llvm::StringRef getArgument () const override
Return the command line argument used when registering this pass.
::llvm::StringRef getDescription () const override
Return the command line description used when registering this pass.
::llvm::StringRef getName () const override
Returns the derived pass name.
std::unique_ptr<::mlir::Pass > clonePass () const override
A clone method to create a copy of this pass.
void getDependentDialects (::mlir::DialectRegistry &registry) const override
Return the dialect that must be loaded in the context before this pass.
AffineDataCopyGenerationBase (AffineDataCopyGenerationOptions options)
Explicitly declare the TypeID for this class.
Public Member Functions inherited from mlir::OperationPass< func::FuncOp >
~OperationPass () override=default
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Static Public Member Functions
static constexpr ::llvm::StringLiteral getArgumentName ()
Returns the command-line argument attached to this pass.
static constexpr ::llvm::StringLiteral getPassName ()
Returns the derived pass name.
static bool classof (const ::mlir::Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Attributes
::mlir::Pass::Option< uint64_t > fastMemoryCapacity {*this, "fast-mem-capacity", ::llvm::cl::desc(R"PO(Set fast memory space capacity in KiB (default: unlimited))PO"), ::llvm::cl::init(std::numeric_limits<uint64_t>::max())}
::mlir::Pass::Option< unsigned > fastMemorySpace {*this, "fast-mem-space", ::llvm::cl::desc(R"PO(Fast memory space identifier for copy generation (default: 1))PO"), ::llvm::cl::init(1)}
::mlir::Pass::Option< bool > generateDma {*this, "generate-dma", ::llvm::cl::desc(R"PO(Generate DMA instead of point-wise copy)PO"), ::llvm::cl::init(false)}
::mlir::Pass::Option< int > minDmaTransferSize {*this, "min-dma-transfer", ::llvm::cl::desc(R"PO(Minimum DMA transfer size supported by the target in bytes)PO"), ::llvm::cl::init(1024)}
::mlir::Pass::Option< unsigned > slowMemorySpace {*this, "slow-mem-space", ::llvm::cl::desc(R"PO(Slow memory space identifier for copy generation (default: 0))PO"), ::llvm::cl::init(0)}
::mlir::Pass::Option< bool > skipNonUnitStrideLoops {*this, "skip-non-unit-stride-loops", ::llvm::cl::desc(R"PO(Testing purposes: avoid non-unit stride loop choice depths for copy placement)PO"), ::llvm::cl::init(false)}
::mlir::Pass::Option< unsigned > tagMemorySpace {*this, "tag-mem-space", ::llvm::cl::desc(R"PO(Tag memory space identifier for copy generation (default: 0))PO"), ::llvm::cl::init(0)}
Additional Inherited Members
Protected Member Functions inherited from mlir::OperationPass< func::FuncOp >
OperationPass (TypeID passID)
OperationPass & operator= (const OperationPass &)=delete
bool canScheduleOn (RegisteredOperationName opName) const final
Indicate if the current pass can be scheduled on the given operation type.
func::FuncOp getOperation ()
Return the current operation being transformed.
AnalysisT & getAnalysis ()
Query an analysis for the current operation of the specific derived operation type.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
virtual bool canScheduleOn (Operation *op) const
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Static Protected Member Functions inherited from mlir::OperationPass< func::FuncOp >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Detailed Description
template<typename DerivedT>
class mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >
Definition at line 45 of file AffineDataCopyGeneration.cpp.
Member Typedef Documentation
Base
template<typename DerivedT> using mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::Base = AffineDataCopyGenerationBase
Definition at line 47 of file AffineDataCopyGeneration.cpp.
Constructor & Destructor Documentation
AffineDataCopyGenerationBase() [1/4]
template<typename DerivedT> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::AffineDataCopyGenerationBase () inline
Definition at line 49 of file AffineDataCopyGeneration.cpp.
AffineDataCopyGenerationBase() [2/4]
template<typename DerivedT> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::AffineDataCopyGenerationBase (const AffineDataCopyGenerationBase< DerivedT > & other) inline
Definition at line 50 of file AffineDataCopyGeneration.cpp.
AffineDataCopyGenerationBase() [3/4]
template<typename DerivedT> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::AffineDataCopyGenerationBase (AffineDataCopyGenerationBase< DerivedT > &&) delete
~AffineDataCopyGenerationBase()
template<typename DerivedT> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::~AffineDataCopyGenerationBase () default
AffineDataCopyGenerationBase() [4/4]
template<typename DerivedT> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::AffineDataCopyGenerationBase (AffineDataCopyGenerationOptions options) inline
Explicitly declare the TypeID for this class.
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 90 of file AffineDataCopyGeneration.cpp.
References fastMemorySpace, minDmaTransferSize, slowMemorySpace, and tagMemorySpace.
Member Function Documentation
classof()
template<typename DerivedT> bool mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::classof (const ::mlir::Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 71 of file AffineDataCopyGeneration.cpp.
References fastMemoryCapacity, minDmaTransferSize, and tagMemorySpace.
clonePass()
template<typename DerivedT> std::unique_ptr<::mlir::Pass > mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::clonePass () const inline override virtual
A clone method to create a copy of this pass.
Implements mlir::Pass.
Definition at line 76 of file AffineDataCopyGeneration.cpp.
References mlir::Pass::runOnOperation().
getArgument()
template<typename DerivedT> ::llvm::StringRef mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 60 of file AffineDataCopyGeneration.cpp.
getArgumentName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::getArgumentName () inline static
Returns the command-line argument attached to this pass.
Definition at line 57 of file AffineDataCopyGeneration.cpp.
getDependentDialects()
template<typename DerivedT> void mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::getDependentDialects (::mlir::DialectRegistry & registry) const inline override
Return the dialect that must be loaded in the context before this pass.
Definition at line 81 of file AffineDataCopyGeneration.cpp.
getDescription()
template<typename DerivedT> ::llvm::StringRef mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 62 of file AffineDataCopyGeneration.cpp.
References slowMemorySpace.
getName()
template<typename DerivedT> ::llvm::StringRef mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 68 of file AffineDataCopyGeneration.cpp.
References fastMemorySpace, and slowMemorySpace.
getPassName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::getPassName () inline static
Returns the derived pass name.
Definition at line 65 of file AffineDataCopyGeneration.cpp.
References fastMemorySpace, minDmaTransferSize, and tagMemorySpace.
operator=() [1/2]
template<typename DerivedT> AffineDataCopyGenerationBase & mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::operator= (AffineDataCopyGenerationBase< DerivedT > &&) delete
operator=() [2/2]
template<typename DerivedT> AffineDataCopyGenerationBase & mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::operator= (const AffineDataCopyGenerationBase< DerivedT > &) delete
Member Data Documentation
fastMemoryCapacity
template<typename DerivedT> ::mlir::Pass::Option<uint64_t> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::fastMemoryCapacity {*this, "fast-mem-capacity", ::llvm::cl::desc(R"PO(Set fast memory space capacity in KiB (default: unlimited))PO"), ::llvm::cl::init(std::numeric_limits<uint64_t>::max())} protected
Definition at line 100 of file AffineDataCopyGeneration.cpp.
Referenced by classof().
fastMemorySpace
template<typename DerivedT> ::mlir::Pass::Option<unsigned> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::fastMemorySpace {*this, "fast-mem-space", ::llvm::cl::desc(R"PO(Fast memory space identifier for copy generation (default: 1))PO"), ::llvm::cl::init(1)} protected
Definition at line 101 of file AffineDataCopyGeneration.cpp.
Referenced by AffineDataCopyGenerationBase(), getName(), and getPassName().
generateDma
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::generateDma {*this, "generate-dma", ::llvm::cl::desc(R"PO(Generate DMA instead of point-wise copy)PO"), ::llvm::cl::init(false)} protected
Definition at line 102 of file AffineDataCopyGeneration.cpp.
minDmaTransferSize
template<typename DerivedT> ::mlir::Pass::Option<int> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::minDmaTransferSize {*this, "min-dma-transfer", ::llvm::cl::desc(R"PO(Minimum DMA transfer size supported by the target in bytes)PO"), ::llvm::cl::init(1024)} protected
Definition at line 103 of file AffineDataCopyGeneration.cpp.
Referenced by AffineDataCopyGenerationBase(), classof(), and getPassName().
skipNonUnitStrideLoops
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::skipNonUnitStrideLoops {*this, "skip-non-unit-stride-loops", ::llvm::cl::desc(R"PO(Testing purposes: avoid non-unit stride loop choice depths for copy placement)PO"), ::llvm::cl::init(false)} protected
Definition at line 105 of file AffineDataCopyGeneration.cpp.
slowMemorySpace
template<typename DerivedT> ::mlir::Pass::Option<unsigned> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::slowMemorySpace {*this, "slow-mem-space", ::llvm::cl::desc(R"PO(Slow memory space identifier for copy generation (default: 0))PO"), ::llvm::cl::init(0)} protected
Definition at line 104 of file AffineDataCopyGeneration.cpp.
Referenced by AffineDataCopyGenerationBase(), getDescription(), and getName().
tagMemorySpace
template<typename DerivedT> ::mlir::Pass::Option<unsigned> mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::tagMemorySpace {*this, "tag-mem-space", ::llvm::cl::desc(R"PO(Tag memory space identifier for copy generation (default: 0))PO"), ::llvm::cl::init(0)} protected
Definition at line 106 of file AffineDataCopyGeneration.cpp.
Referenced by AffineDataCopyGenerationBase(), classof(), and getPassName().
The documentation for this class was generated from the following file:
lib/Dialect/Affine/Transforms/AffineDataCopyGeneration.cpp