MLIR: mlir::sparse_tensor::ir_detail::DimLvlMapParser Class Reference
mlir::sparse_tensor::ir_detail::DimLvlMapParser Class Reference final
Parses the Sparse Tensor Encoding Attribute (STEA).
#include "Dialect/SparseTensor/IR/Detail/DimLvlMapParser.h"
Public Member Functions
DimLvlMapParser (AsmParser &parser)
FailureOr< DimLvlMap > parseDimLvlMap ()
Detailed Description
Parses the Sparse Tensor Encoding Attribute (STEA).
General syntax is as follows,
[s0, ...] // optional forward decl sym-vars {l0, ...} // optional forward decl lvl-vars (d0 = ..., // dim-var = dim-exp ...) -> (l0 = ..., // lvl-var = lvl-exp ...)
with simplifications when variables are implicit.
Definition at line 36 of file DimLvlMapParser.h.
Constructor & Destructor Documentation
DimLvlMapParser()
mlir::sparse_tensor::ir_detail::DimLvlMapParser::DimLvlMapParser (AsmParser & parser) inline explicit
Definition at line 38 of file DimLvlMapParser.h.
Member Function Documentation
parseDimLvlMap()
FailureOr< DimLvlMap > DimLvlMapParser::parseDimLvlMap ()
Definition at line 142 of file DimLvlMapParser.cpp.
References mlir::sparse_tensor::ir_detail::VarEnv::emitErrorIfAnyUnbound(), FAILURE_IF_FAILED, mlir::sparse_tensor::ir_detail::VarEnv::getRanks(), mlir::sparse_tensor::ir_detail::Ranks::getSymRank(), and mlir::AsmParser::parseArrow().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMapParser.h
lib/Dialect/SparseTensor/IR/Detail/DimLvlMapParser.cpp