MLIR: mlir::DebugAction< ParameterTs >::Handler Class Reference
mlir::DebugAction< ParameterTs >::Handler Class Reference
#include "mlir/Support/DebugAction.h"
Public Member Functions
Handler ()
virtual FailureOr< bool > shouldExecute (ParameterTs... parameters)
This hook allows for controlling whether an action should execute or not.
Public Member Functions inherited from mlir::DebugActionManager::HandlerBase
virtual ~HandlerBase ()
TypeID getHandlerID () const
Return the unique handler id of this handler, use for casting functionality.
Static Public Member Functions
static bool classof (const DebugActionManager::HandlerBase *handler)
Provide classof to allow casting between handler types.
Additional Inherited Members
Protected Member Functions inherited from mlir::DebugActionManager::HandlerBase
HandlerBase (TypeID handlerID)
Protected Attributes inherited from mlir::DebugActionManager::HandlerBase
TypeID handlerID
The type of the derived handler class.
Detailed Description
template<typename... ParameterTs>
class mlir::DebugAction< ParameterTs >::Handler
Definition at line 194 of file DebugAction.h.
Constructor & Destructor Documentation
Handler()
template<typename... ParameterTs> mlir::DebugAction< ParameterTs >::Handler::Handler () inline
Definition at line 196 of file DebugAction.h.
Member Function Documentation
classof()
template<typename... ParameterTs> static bool mlir::DebugAction< ParameterTs >::Handler::classof (const DebugActionManager::HandlerBase * handler) inline static
Provide classof to allow casting between handler types.
Definition at line 207 of file DebugAction.h.
References mlir::TypeID::get(), mlir::DebugActionManager::HandlerBase::getHandlerID(), and value.
shouldExecute()
template<typename... ParameterTs> virtual FailureOr<bool> mlir::DebugAction< ParameterTs >::Handler::shouldExecute (ParameterTs... parameters) inline virtual
This hook allows for controlling whether an action should execute or not.
parameters correspond to the set of values provided by the action as context. It should return failure if the handler could not process the action, passing it to the next registered handler.
Definition at line 202 of file DebugAction.h.
References mlir::failure().
The documentation for this class was generated from the following file:
include/mlir/Support/DebugAction.h