MLIR: mlir::tblgen::AttrOrTypeDef Class Reference
mlir::tblgen::AttrOrTypeDef Class Reference
Wrapper class that contains a TableGen AttrOrTypeDef's record and provides helper methods for accessing them.
#include "mlir/TableGen/AttrOrTypeDef.h"
Public Member Functions
AttrOrTypeDef (const llvm::Record *def)
Dialect getDialect () const
Get the dialect for which this def belongs.
StringRef getName () const
Returns the name of this AttrOrTypeDef record.
bool hasDescription () const
Query functions for the documentation of the def.
StringRef getDescription () const
bool hasSummary () const
StringRef getSummary () const
StringRef getCppClassName () const
Returns the name of the C++ class to generate.
StringRef getCppBaseClassName () const
Returns the name of the C++ base class to use when generating this def.
StringRef getStorageClassName () const
Returns the name of the storage class for this def.
StringRef getStorageNamespace () const
Returns the C++ namespace for this def's storage class.
bool genStorageClass () const
Returns true if we should generate the storage class.
bool hasStorageCustomConstructor () const
Indicates whether or not to generate the storage class constructor.
ArrayRef< AttrOrTypeParameter > getParameters () const
Get the parameters of this attribute or type.
unsigned getNumParameters () const
Return the number of parameters.
std::optional< StringRef > getMnemonic () const
Return the keyword/mnemonic to use in the printer/parser methods if we are supposed to auto-generate them.
bool hasCustomAssemblyFormat () const
Returns if the attribute or type has a custom assembly format implemented in C++.
std::optional< StringRef > getAssemblyFormat () const
Returns the custom assembly format, if one was specified.
bool genAccessors () const
Returns true if the accessors based on the parameters should be generated.
bool genVerifyDecl () const
Return true if we need to generate the verify declaration and getChecked method.
bool genVerifyInvariantsImpl () const
Return true if we need to generate any type constraint verification and the getChecked method.
std::optional< StringRef > getExtraDecls () const
Returns the def's extra class declaration code.
std::optional< StringRef > getExtraDefs () const
Returns the def's extra class definition code.
bool genMnemonicAlias () const
Returns true if we need to generate a default 'getAlias' implementation using the mnemonic.
ArrayRef< SMLoc > getLoc () const
Get the code location (for error printing).
bool skipDefaultBuilders () const
Returns true if the default get/getChecked methods should be skipped during generation.
ArrayRef< AttrOrTypeBuilder > getBuilders () const
Returns the builders of this def.
ArrayRef< Trait > getTraits () const
Returns the traits of this def.
bool operator== (const AttrOrTypeDef &other) const
Returns whether two AttrOrTypeDefs are equal by checking the equality of the underlying record.
bool operator< (const AttrOrTypeDef &other) const
Compares two AttrOrTypeDefs by comparing the names of the dialects.
operator bool () const
Returns whether the AttrOrTypeDef is defined.
const llvm::Record * getDef () const
Return the underlying def.
Protected Attributes
const llvm::Record * def
SmallVector< AttrOrTypeBuilder > builders
The builders of this definition.
SmallVector< Trait > traits
The traits of this definition.
SmallVector< AttrOrTypeParameter > parameters
The parameters of this attribute or type.
Detailed Description
Wrapper class that contains a TableGen AttrOrTypeDef's record and provides helper methods for accessing them.
Definition at line 151 of file AttrOrTypeDef.h.
Constructor & Destructor Documentation
AttrOrTypeDef()
AttrOrTypeDef::AttrOrTypeDef (const llvm::Record * def) explicit
Definition at line 44 of file AttrOrTypeDef.cpp.
References builders, mlir::tblgen::Trait::create(), def, genAccessors(), getAssemblyFormat(), getDef(), getLoc(), getMnemonic(), mlir::tblgen::Builder::getParameters(), hasCustomAssemblyFormat(), parameters, and traits.
Referenced by operator<(), and operator==().
Member Function Documentation
genAccessors()
bool AttrOrTypeDef::genAccessors () const
Returns true if the accessors based on the parameters should be generated.
Definition at line 184 of file AttrOrTypeDef.cpp.
References def.
Referenced by AttrOrTypeDef().
genMnemonicAlias()
bool AttrOrTypeDef::genMnemonicAlias () const
Returns true if we need to generate a default 'getAlias' implementation using the mnemonic.
Definition at line 208 of file AttrOrTypeDef.cpp.
References def.
genStorageClass()
bool AttrOrTypeDef::genStorageClass () const
Returns true if we should generate the storage class.
Definition at line 159 of file AttrOrTypeDef.cpp.
References def.
genVerifyDecl()
bool AttrOrTypeDef::genVerifyDecl () const
Return true if we need to generate the verify declaration and getChecked method.
Definition at line 188 of file AttrOrTypeDef.cpp.
References def.
genVerifyInvariantsImpl()
bool AttrOrTypeDef::genVerifyInvariantsImpl () const
Return true if we need to generate any type constraint verification and the getChecked method.
Definition at line 192 of file AttrOrTypeDef.cpp.
References mlir::tblgen::AttrOrTypeParameter::getConstraint(), and parameters.
getAssemblyFormat()
std::optional< StringRef > AttrOrTypeDef::getAssemblyFormat () const
Returns the custom assembly format, if one was specified.
Definition at line 180 of file AttrOrTypeDef.cpp.
References def.
Referenced by AttrOrTypeDef().
getBuilders()
ArrayRef< AttrOrTypeBuilder > mlir::tblgen::AttrOrTypeDef::getBuilders () const inline
Returns the builders of this def.
Definition at line 231 of file AttrOrTypeDef.h.
References builders.
getCppBaseClassName()
StringRef AttrOrTypeDef::getCppBaseClassName () const
Returns the name of the C++ base class to use when generating this def.
Definition at line 129 of file AttrOrTypeDef.cpp.
References def.
getCppClassName()
StringRef AttrOrTypeDef::getCppClassName () const
Returns the name of the C++ class to generate.
Definition at line 125 of file AttrOrTypeDef.cpp.
References def.
getDef()
const llvm::Record * mlir::tblgen::AttrOrTypeDef::getDef () const inline
Return the underlying def.
Definition at line 247 of file AttrOrTypeDef.h.
References def.
Referenced by AttrOrTypeDef().
getDescription()
StringRef AttrOrTypeDef::getDescription () const
Definition at line 138 of file AttrOrTypeDef.cpp.
References def.
getDialect()
Dialect AttrOrTypeDef::getDialect () const
Get the dialect for which this def belongs.
Definition at line 118 of file AttrOrTypeDef.cpp.
References def.
getExtraDecls()
std::optional< StringRef > AttrOrTypeDef::getExtraDecls () const
Returns the def's extra class declaration code.
Definition at line 198 of file AttrOrTypeDef.cpp.
References def.
getExtraDefs()
std::optional< StringRef > AttrOrTypeDef::getExtraDefs () const
Returns the def's extra class definition code.
Definition at line 203 of file AttrOrTypeDef.cpp.
References def.
getLoc()
ArrayRef< SMLoc > AttrOrTypeDef::getLoc () const
Get the code location (for error printing).
Definition at line 212 of file AttrOrTypeDef.cpp.
References def.
Referenced by AttrOrTypeDef().
getMnemonic()
std::optional< StringRef > AttrOrTypeDef::getMnemonic () const
Return the keyword/mnemonic to use in the printer/parser methods if we are supposed to auto-generate them.
Definition at line 172 of file AttrOrTypeDef.cpp.
References def.
Referenced by AttrOrTypeDef().
getName()
StringRef AttrOrTypeDef::getName () const
Returns the name of this AttrOrTypeDef record.
Definition at line 123 of file AttrOrTypeDef.cpp.
References def.
Referenced by operator<().
getNumParameters()
unsigned AttrOrTypeDef::getNumParameters () const
Return the number of parameters.
Definition at line 167 of file AttrOrTypeDef.cpp.
References def.
getParameters()
ArrayRef< AttrOrTypeParameter > mlir::tblgen::AttrOrTypeDef::getParameters () const inline
Get the parameters of this attribute or type.
Definition at line 186 of file AttrOrTypeDef.h.
References parameters.
getStorageClassName()
StringRef AttrOrTypeDef::getStorageClassName () const
Returns the name of the storage class for this def.
Definition at line 151 of file AttrOrTypeDef.cpp.
References def.
getStorageNamespace()
StringRef AttrOrTypeDef::getStorageNamespace () const
Returns the C++ namespace for this def's storage class.
Definition at line 155 of file AttrOrTypeDef.cpp.
References def.
getSummary()
StringRef AttrOrTypeDef::getSummary () const
Definition at line 147 of file AttrOrTypeDef.cpp.
References def.
getTraits()
ArrayRef< Trait > mlir::tblgen::AttrOrTypeDef::getTraits () const inline
Returns the traits of this def.
Definition at line 234 of file AttrOrTypeDef.h.
References traits.
hasCustomAssemblyFormat()
bool AttrOrTypeDef::hasCustomAssemblyFormat () const
Returns if the attribute or type has a custom assembly format implemented in C++.
Corresponds to the hasCustomAssemblyFormat field.
Definition at line 176 of file AttrOrTypeDef.cpp.
References def.
Referenced by AttrOrTypeDef().
hasDescription()
bool AttrOrTypeDef::hasDescription () const
Query functions for the documentation of the def.
Definition at line 133 of file AttrOrTypeDef.cpp.
References def.
hasStorageCustomConstructor()
bool AttrOrTypeDef::hasStorageCustomConstructor () const
Indicates whether or not to generate the storage class constructor.
Definition at line 163 of file AttrOrTypeDef.cpp.
References def.
hasSummary()
bool AttrOrTypeDef::hasSummary () const
Definition at line 142 of file AttrOrTypeDef.cpp.
References def.
operator bool()
mlir::tblgen::AttrOrTypeDef::operator bool () const inline
Returns whether the AttrOrTypeDef is defined.
Definition at line 244 of file AttrOrTypeDef.h.
References def.
operator<()
bool AttrOrTypeDef::operator< (const AttrOrTypeDef & other) const
Compares two AttrOrTypeDefs by comparing the names of the dialects.
Definition at line 222 of file AttrOrTypeDef.cpp.
References AttrOrTypeDef(), and getName().
operator==()
bool AttrOrTypeDef::operator== (const AttrOrTypeDef & other) const
Returns whether two AttrOrTypeDefs are equal by checking the equality of the underlying record.
Definition at line 218 of file AttrOrTypeDef.cpp.
References AttrOrTypeDef(), and def.
skipDefaultBuilders()
bool AttrOrTypeDef::skipDefaultBuilders () const
Returns true if the default get/getChecked methods should be skipped during generation.
Definition at line 214 of file AttrOrTypeDef.cpp.
References def.
Member Data Documentation
builders
SmallVector<AttrOrTypeBuilder> mlir::tblgen::AttrOrTypeDef::builders protected
The builders of this definition.
Definition at line 253 of file AttrOrTypeDef.h.
Referenced by AttrOrTypeDef(), and getBuilders().
def
const llvm::Record* mlir::tblgen::AttrOrTypeDef::def protected
Definition at line 250 of file AttrOrTypeDef.h.
Referenced by AttrOrTypeDef(), mlir::tblgen::AttrDef::classof(), mlir::tblgen::TypeDef::classof(), genAccessors(), genMnemonicAlias(), genStorageClass(), genVerifyDecl(), getAssemblyFormat(), mlir::tblgen::AttrDef::getAttrName(), getCppBaseClassName(), getCppClassName(), getDef(), getDescription(), getDialect(), getExtraDecls(), getExtraDefs(), getLoc(), getMnemonic(), getName(), getNumParameters(), getStorageClassName(), getStorageNamespace(), getSummary(), mlir::tblgen::AttrDef::getTypeBuilder(), mlir::tblgen::TypeDef::getTypeName(), hasCustomAssemblyFormat(), hasDescription(), hasStorageCustomConstructor(), hasSummary(), operator bool(), operator==(), and skipDefaultBuilders().
parameters
SmallVector<AttrOrTypeParameter> mlir::tblgen::AttrOrTypeDef::parameters protected
The parameters of this attribute or type.
Definition at line 259 of file AttrOrTypeDef.h.
Referenced by AttrOrTypeDef(), genVerifyInvariantsImpl(), and getParameters().
traits
SmallVector<Trait> mlir::tblgen::AttrOrTypeDef::traits protected
The traits of this definition.
Definition at line 256 of file AttrOrTypeDef.h.
Referenced by AttrOrTypeDef(), and getTraits().
The documentation for this class was generated from the following files:
include/mlir/TableGen/AttrOrTypeDef.h
lib/TableGen/AttrOrTypeDef.cpp