MLIR: mlir::linalg::LinalgDependenceGraph Class Reference
mlir::linalg::LinalgDependenceGraph Class Reference
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
Classes
struct LinalgDependenceGraphElem
Public Types
enum DependenceType {
RAR = 0, RAW, WAR, WAW,
NumTypes
}
using LinalgDependences = SmallVector< LinalgDependenceGraphElem, 8 >
using DependenceGraph = DenseMap< Operation *, LinalgDependences >
using dependence_iterator = LinalgDependences::const_iterator
using dependence_range = iterator_range< dependence_iterator >
Public Member Functions
LinalgDependenceGraph (Aliases &aliases, ArrayRef< LinalgOp > ops)
dependence_range getDependencesFrom (Operation *src, DependenceType dt) const
Returns the X such that op -> X is a dependence of type dt.
dependence_range getDependencesFrom (LinalgOp src, DependenceType dt) const
dependence_range getDependencesInto (Operation *dst, DependenceType dt) const
Returns the X such that X -> op is a dependence of type dt.
dependence_range getDependencesInto (LinalgOp dst, DependenceType dt) const
SmallVector< Operation *, 8 > findCoveringDependences (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp) const
Returns the operations that are interleaved between srcLinalgOp and dstLinalgOp and that are involved in any RAW, WAR or WAW dependence relation with srcLinalgOp, on any view.
SmallVector< Operation *, 8 > findCoveringReads (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp, Value view) const
Returns the operations that are interleaved between srcLinalgOp and dstLinalgOp and that are involved in a RAR or RAW with srcLinalgOp.
SmallVector< Operation *, 8 > findCoveringWrites (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp, Value view) const
Returns the operations that are interleaved between srcLinalgOp and dstLinalgOp and that are involved in a WAR or WAW with srcLinalgOp.
bool hasDependenceFrom (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns true if the two operations have the specified dependence from srcLinalgOp to dstLinalgOp.
bool hasDependentOperationsInto (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns true if the linalgOp has dependences into it.
bool hasDependentOperationsFrom (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns true if the linalgOp has dependences from it.
bool hasDependentOperations (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns true if the linalgOp has dependences into or from it.
SmallVector< LinalgDependenceGraphElem, 2 > getDependentOperationsInto (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns all operations that have a dependence into linalgOp of types listed in depTypes.
SmallVector< LinalgDependenceGraphElem, 2 > getDependentOperationsFrom (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns all operations that have a dependence from linalgOp of types listed in depTypes.
SmallVector< LinalgDependenceGraphElem, 2 > getDependentOperations (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes={ DependenceType::RAW, DependenceType::WAW}) const
Returns all dependent operations (into and from) given operation.
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static StringRef getDependenceTypeStr (DependenceType depType)
static LinalgDependenceGraph buildDependenceGraph (Aliases &aliases, FuncOp f)
Detailed Description
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
Definition at line 45 of file DependenceAnalysis.h.
Member Typedef Documentation
dependence_iterator
using mlir::linalg::LinalgDependenceGraph::dependence_iterator = LinalgDependences::const_iterator
Definition at line 152 of file DependenceAnalysis.h.
dependence_range
using mlir::linalg::LinalgDependenceGraph::dependence_range = iterator_range<dependence_iterator>
Definition at line 153 of file DependenceAnalysis.h.
DependenceGraph
using mlir::linalg::LinalgDependenceGraph::DependenceGraph = DenseMap<Operation *, LinalgDependences>
Definition at line 151 of file DependenceAnalysis.h.
LinalgDependences
using mlir::linalg::LinalgDependenceGraph::LinalgDependences = SmallVector<LinalgDependenceGraphElem, 8>
Definition at line 150 of file DependenceAnalysis.h.
Member Enumeration Documentation
DependenceType
enum mlir::linalg::LinalgDependenceGraph::DependenceType
Enumerator
RAR
RAW
WAR
WAW
NumTypes
Definition at line 47 of file DependenceAnalysis.h.
Constructor & Destructor Documentation
LinalgDependenceGraph()
LinalgDependenceGraph::LinalgDependenceGraph (Aliases & aliases, ArrayRef< LinalgOp > ops)
Definition at line 103 of file DependenceAnalysis.cpp.
References mlir::detail::enumerate(), getDependenceTypeStr(), mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getOwner(), and mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getValue().
Member Function Documentation
buildDependenceGraph()
LinalgDependenceGraph LinalgDependenceGraph::buildDependenceGraph (Aliases & aliases, FuncOp f) static
Definition at line 97 of file DependenceAnalysis.cpp.
References op.
dump()
void LinalgDependenceGraph::dump () const
Definition at line 356 of file DependenceAnalysis.cpp.
References print().
findCoveringDependences()
SmallVector< Operation *, 8 > LinalgDependenceGraph::findCoveringDependences (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp) const
Returns the operations that are interleaved between srcLinalgOp and dstLinalgOp and that are involved in any RAW, WAR or WAW dependence relation with srcLinalgOp, on any view.
Any such operation prevents reordering.
Definition at line 214 of file DependenceAnalysis.cpp.
Referenced by mlir::linalg::isFusableInto().
findCoveringReads()
SmallVector< Operation *, 8 > LinalgDependenceGraph::findCoveringReads (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp, Value view) const
Returns the operations that are interleaved between srcLinalgOp and dstLinalgOp and that are involved in a RAR or RAW with srcLinalgOp.
Dependences are restricted to views aliasing view.
Definition at line 228 of file DependenceAnalysis.cpp.
References mlir::linalg::Aliases::alias(), getDependencesFrom(), getDependenceTypeStr(), and op.
findCoveringWrites()
SmallVector< Operation *, 8 > LinalgDependenceGraph::findCoveringWrites (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp, Value view) const
Returns the operations that are interleaved between srcLinalgOp and dstLinalgOp and that are involved in a WAR or WAW with srcLinalgOp.
Dependences are restricted to views aliasing view.
Definition at line 221 of file DependenceAnalysis.cpp.
Referenced by mlir::linalg::isProducerLastWriteOfView().
getDependencesFrom() [1/2]
LinalgDependenceGraph::dependence_range LinalgDependenceGraph::getDependencesFrom (Operation * src, LinalgDependenceGraph::DependenceType dt) const
Returns the X such that op -> X is a dependence of type dt.
Definition at line 141 of file DependenceAnalysis.cpp.
Referenced by findCoveringReads(), getDependencesFrom(), getDependentOperationsFrom(), and hasDependentOperationsFrom().
getDependencesFrom() [2/2]
LinalgDependenceGraph::dependence_range LinalgDependenceGraph::getDependencesFrom (LinalgOp src, LinalgDependenceGraph::DependenceType dt) const
Definition at line 135 of file DependenceAnalysis.cpp.
References getDependencesFrom().
getDependencesInto() [1/2]
LinalgDependenceGraph::dependence_range LinalgDependenceGraph::getDependencesInto (Operation * dst, LinalgDependenceGraph::DependenceType dt) const
Returns the X such that X -> op is a dependence of type dt.
Definition at line 156 of file DependenceAnalysis.cpp.
References mlir::linalg::Aliases::alias().
Referenced by findFusableProducer(), getDependencesInto(), getDependentOperationsInto(), hasDependenceFrom(), and hasDependentOperationsInto().
getDependencesInto() [2/2]
LinalgDependenceGraph::dependence_range LinalgDependenceGraph::getDependencesInto (LinalgOp dst, LinalgDependenceGraph::DependenceType dt) const
Definition at line 150 of file DependenceAnalysis.cpp.
References getDependencesInto().
getDependenceTypeStr()
StringRef LinalgDependenceGraph::getDependenceTypeStr (DependenceType depType) static
Definition at line 80 of file DependenceAnalysis.cpp.
Referenced by findCoveringReads(), findFusableProducer(), and LinalgDependenceGraph().
getDependentOperations()
SmallVector< LinalgDependenceGraph::LinalgDependenceGraphElem, 2 > LinalgDependenceGraph::getDependentOperations (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns all dependent operations (into and from) given operation.
Definition at line 330 of file DependenceAnalysis.cpp.
References getDependentOperationsFrom(), and getDependentOperationsInto().
getDependentOperationsFrom()
SmallVector< LinalgDependenceGraph::LinalgDependenceGraphElem, 2 > LinalgDependenceGraph::getDependentOperationsFrom (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns all operations that have a dependence from linalgOp of types listed in depTypes.
Definition at line 317 of file DependenceAnalysis.cpp.
References getDependencesFrom().
Referenced by getDependentOperations().
getDependentOperationsInto()
SmallVector< LinalgDependenceGraph::LinalgDependenceGraphElem, 2 > LinalgDependenceGraph::getDependentOperationsInto (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns all operations that have a dependence into linalgOp of types listed in depTypes.
Definition at line 305 of file DependenceAnalysis.cpp.
References getDependencesInto().
Referenced by getDependentOperations(), and mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
hasDependenceFrom()
bool LinalgDependenceGraph::hasDependenceFrom (LinalgOp srcLinalgOp, LinalgOp dstLinalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns true if the two operations have the specified dependence from srcLinalgOp to dstLinalgOp.
Definition at line 268 of file DependenceAnalysis.cpp.
References getDependencesInto().
hasDependentOperations()
bool LinalgDependenceGraph::hasDependentOperations (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns true if the linalgOp has dependences into or from it.
Definition at line 298 of file DependenceAnalysis.cpp.
References hasDependentOperationsFrom(), and hasDependentOperationsInto().
hasDependentOperationsFrom()
bool LinalgDependenceGraph::hasDependentOperationsFrom (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns true if the linalgOp has dependences from it.
Definition at line 278 of file DependenceAnalysis.cpp.
References getDependencesFrom().
Referenced by hasDependentOperations().
hasDependentOperationsInto()
bool LinalgDependenceGraph::hasDependentOperationsInto (LinalgOp linalgOp, ArrayRef< DependenceType > depTypes = { DependenceType::RAW, DependenceType::WAW}) const
Returns true if the linalgOp has dependences into it.
Definition at line 288 of file DependenceAnalysis.cpp.
References getDependencesInto().
Referenced by hasDependentOperations().
print()
void LinalgDependenceGraph::print (raw_ostream & os) const
Definition at line 340 of file DependenceAnalysis.cpp.
Referenced by dump().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h
lib/Dialect/Linalg/Analysis/DependenceAnalysis.cpp