MLIR: mlir::presburger::IntegerPolyhedron Class Reference
mlir::presburger::IntegerPolyhedron Class Reference
An IntegerPolyhedron represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
#include "mlir/Analysis/Presburger/IntegerRelation.h"
Public Member Functions
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a set reserving memory for the specified number of constraints and variables.
IntegerPolyhedron (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
IntegerPolyhedron (const PresburgerSpace &space, const IntMatrix &inequalities)
Constructs a relation with the specified number of dimensions and symbols and adds the given inequalities.
IntegerPolyhedron (const PresburgerSpace &space, const FracMatrix &inequalities)
Constructs a relation with the specified number of dimensions and symbols and adds the given inequalities, after normalizing row-wise to integer values.
IntegerPolyhedron (const IntegerRelation &rel)
Construct a set from an IntegerRelation.
IntegerPolyhedron (IntegerRelation &&rel)
Construct a set from an IntegerRelation, but instead of creating a copy, use move constructor.
Kind getKind () const override
Return the kind of this IntegerRelation.
std::unique_ptr< IntegerPolyhedron > clone () const
unsigned insertVar (VarKind kind, unsigned pos, unsigned num=1) override
Insert num variables of the specified kind at position pos.
IntegerPolyhedron intersect (const IntegerPolyhedron &other) const
Return the intersection of the two relations.
PresburgerSet subtract (const PresburgerSet &other) const
Return the set difference of this set and the given set, i.e., return this \ set.
Public Member Functions inherited from mlir::presburger::IntegerRelation
IntegerRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a relation reserving memory for the specified number of constraints and variables.
IntegerRelation (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
virtual ~IntegerRelation ()=default
std::unique_ptr< IntegerRelation > clone () const
const PresburgerSpace & getSpace () const
Returns a reference to the underlying space.
void setSpace (const PresburgerSpace &oSpace)
Set the space to oSpace, which should have the same number of ids as the current space.
void setSpaceExceptLocals (const PresburgerSpace &oSpace)
Set the space to oSpace, which should not have any local ids.
void setId (VarKind kind, unsigned i, Identifier id)
Set the identifier for the ith variable of the specified kind of the IntegerRelation's PresburgerSpace.
void resetIds ()
ArrayRef< Identifier > getIds (VarKind kind)
Get the identifiers for the variables of specified varKind.
PresburgerSpace getSpaceWithoutLocals () const
Returns a copy of the space without locals.
void append (const IntegerRelation &other)
Appends constraints from other into this.
int findEqualityToConstant (unsigned pos, bool symbolic=false) const
Finds an equality that equates the specified variable to a constant.
IntegerRelation intersect (IntegerRelation other) const
Return the intersection of the two relations.
bool isEqual (const IntegerRelation &other) const
Return whether this and other are equal.
bool isObviouslyEqual (const IntegerRelation &other) const
Perform a quick equality check on this and other.
bool isSubsetOf (const IntegerRelation &other) const
Return whether this is a subset of the given IntegerRelation.
DynamicAPInt atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t atEq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
DynamicAPInt & atEq (unsigned i, unsigned j)
DynamicAPInt atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t atIneq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
DynamicAPInt & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
int64_t atConstraint64 (unsigned i, unsigned j) const
Unified indexing into the constraints.
DynamicAPInt & atConstraint (unsigned i, unsigned j)
unsigned getNumDomainVars () const
unsigned getNumRangeVars () const
unsigned getNumSymbolVars () const
unsigned getNumLocalVars () const
unsigned getNumDimVars () const
unsigned getNumDimAndSymbolVars () const
unsigned getNumVars () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< DynamicAPInt > getEquality (unsigned idx) const
ArrayRef< DynamicAPInt > getInequality (unsigned idx) const
SmallVector< int64_t, 8 > getEquality64 (unsigned idx) const
The same, but casts to int64_t.
SmallVector< int64_t, 8 > getInequality64 (unsigned idx) const
IntMatrix getInequalities () const
unsigned getNumVarKind (VarKind kind) const
Get the number of vars of the specified kind.
unsigned getVarKindOffset (VarKind kind) const
Return the index at which the specified kind of vars starts.
unsigned getVarKindEnd (VarKind kind) const
Return the index at Which the specified kind of vars ends.
auto iterVarKind (VarKind kind)
Return an interator over the variables of the specified kind starting at the relevant offset.
unsigned getVarKindOverlap (VarKind kind, unsigned varStart, unsigned varLimit) const
Get the number of elements of the specified kind in the range [varStart, varLimit).
VarKind getVarKindAt (unsigned pos) const
Return the VarKind of the var at the specified position.
CountsSnapshot getCounts () const
void truncate (const CountsSnapshot &counts)
unsigned appendVar (VarKind kind, unsigned num=1)
Append num variables of the specified kind after the last variable of that kind.
void addInequality (ArrayRef< DynamicAPInt > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addInequality (ArrayRef< int64_t > inEq)
void addEquality (ArrayRef< DynamicAPInt > eq)
Adds an equality from the coefficients specified in eq.
void addEquality (ArrayRef< int64_t > eq)
virtual void eliminateRedundantLocalVar (unsigned posA, unsigned posB)
Eliminate the posB^th local variable, replacing every instance of it with the posA^th local variable.
void removeVar (VarKind kind, unsigned pos)
Removes variables of the specified kind with the specified pos (or within the specified range) from the system.
virtual void removeVarRange (VarKind kind, unsigned varStart, unsigned varLimit)
void removeVar (unsigned pos)
Removes the specified variable from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeConstraint (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
MaybeOptimum< SmallVector< Fraction, 8 > > findRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
MaybeOptimum< SmallVector< DynamicAPInt, 8 > > findIntegerLexMin () const
Same as above, but returns lexicographically minimal integer point.
virtual void swapVar (unsigned posA, unsigned posB)
Swap the posA^th variable with the posB^th variable.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< DynamicAPInt > values)
Sets the values.size() variables starting at pos to the specified values and removes them.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
virtual void clearAndCopyFrom (const IntegerRelation &other)
Replaces the contents of this IntegerRelation with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the variable at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all variables, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isObviouslyEmpty () const
Performs GCD checks and invalid constraint checks.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
IntMatrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
std::optional< SmallVector< DynamicAPInt, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
std::optional< DynamicAPInt > computeVolume () const
Compute an overapproximation of the number of integer points in the relation.
bool containsPoint (ArrayRef< DynamicAPInt > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
bool containsPoint (ArrayRef< int64_t > point) const
std::optional< SmallVector< DynamicAPInt, 8 > > containsPointNoLocal (ArrayRef< DynamicAPInt > point) const
Given the values of non-local vars, return a satisfying assignment to the local if one exists, or an empty optional otherwise.
std::optional< SmallVector< DynamicAPInt, 8 > > containsPointNoLocal (ArrayRef< int64_t > point) const
DivisionRepr getLocalReprs (std::vector< MaybeLocalRepr > *repr=nullptr) const
Returns a DivisonRepr representing the division representation of local variables in the constraint system.
void addBound (BoundType type, unsigned pos, const DynamicAPInt &value)
Adds a constant bound for the specified variable.
void addBound (BoundType type, unsigned pos, int64_t value)
void addBound (BoundType type, ArrayRef< DynamicAPInt > expr, const DynamicAPInt &value)
Adds a constant bound for the specified expression.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
unsigned addLocalFloorDiv (ArrayRef< DynamicAPInt > dividend, const DynamicAPInt &divisor)
Adds a new local variable as the floordiv of an affine function of other variables, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
unsigned addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
unsigned addLocalModulo (ArrayRef< DynamicAPInt > exprs, const DynamicAPInt &modulus)
Adds a new local variable as the modulus of an affine function of other variables, the coefficients of which are provided in exprs.
unsigned addLocalModulo (ArrayRef< int64_t > exprs, int64_t modulus)
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num variables starting at position pos.
void projectOut (unsigned pos)
void pruneOrthogonalConstraints (unsigned pos)
The function removes some constraints that do not impose any bound on the specified variable.
LogicalResult constantFoldVar (unsigned pos)
Tries to fold the specified variable to a constant using a trivial equality detection; if successful, the constant is substituted for the variable everywhere in the constraint system and then removed from the system.
void constantFoldVarRange (unsigned pos, unsigned num)
This method calls constantFoldVar for the specified range of variables, num variables starting at position pos.
LogicalResult unionBoundingBox (const IntegerRelation &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
std::optional< DynamicAPInt > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< DynamicAPInt > *lb=nullptr, DynamicAPInt *boundFloorDivisor=nullptr, SmallVectorImpl< DynamicAPInt > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified variable (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the variable.
std::optional< int64_t > getConstantBoundOnDimSize64 (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
The same, but casts to int64_t.
std::optional< DynamicAPInt > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th variable if there is one; std::nullopt otherwise.
std::optional< int64_t > getConstantBound64 (BoundType type, unsigned pos) const
The same, but casts to int64_t.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) variables in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of variables.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void removeDuplicateDivs ()
void simplify ()
Simplify the constraint system by removing canonicalizing constraints and removing redundant constraints.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind, unsigned pos)
Converts variables of kind srcKind in the range [varStart, varLimit) to variables of kind dstKind.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind)
void convertToLocal (VarKind kind, unsigned varStart, unsigned varLimit)
void mergeAndAlignSymbols (IntegerRelation &other)
Merge and align symbol variables of this and other with respect to identifiers.
unsigned mergeLocalVars (IntegerRelation &other)
Adds additional local vars to the sets such that they both have the union of the local vars in each set, without changing the set of points that lie in this and other.
bool hasOnlyDivLocals () const
Check whether all local ids have a division representation.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
IntegerPolyhedron getDomainSet () const
Return a set corresponding to all points in the domain of the relation.
IntegerPolyhedron getRangeSet () const
Return a set corresponding to all points in the range of the relation.
void intersectDomain (const IntegerPolyhedron &poly)
Intersect the given poly with the domain in-place.
void intersectRange (const IntegerPolyhedron &poly)
Intersect the given poly with the range in-place.
void inverse ()
Invert the relation i.e., swap its domain and range.
void compose (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void applyDomain (const IntegerRelation &rel)
Given a relation rel, apply the relation to the domain of this relation.
void applyRange (const IntegerRelation &rel)
Given a relation rel, apply the relation to the range of this relation.
IntegerRelation rangeProduct (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void mergeAndCompose (const IntegerRelation &other)
Given a relation other: (A -> B), this operation merges the symbol and local variables and then takes the composition of other on this: (B -> / C).
PresburgerRelation computeReprWithOnlyDivLocals () const
Compute an equivalent representation of the same set, such that all local vars in all disjuncts have division representations.
SymbolicLexOpt findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the relation.
SymbolicLexOpt findSymbolicIntegerLexMax () const
Same as findSymbolicIntegerLexMin but produces lexmax instead of lexmin.
std::optional< unsigned > findConstraintWithNonZeroAt (unsigned colIdx, bool isEq) const
Finds a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
PresburgerRelation subtract (const PresburgerRelation &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
void removeTrivialEqualities ()
bool isFullDim ()
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static IntegerPolyhedron getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerRelation *cst)
Static Public Member Functions inherited from mlir::presburger::IntegerRelation
static IntegerRelation getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static IntegerRelation getEmpty (const PresburgerSpace &space)
Return an empty system containing an invalid equation 0 = 1.
static bool classof (const IntegerRelation *cst)
Additional Inherited Members
Public Types inherited from mlir::presburger::IntegerRelation
enum class Kind {
IntegerRelation , IntegerPolyhedron , FlatLinearConstraints , FlatLinearValueConstraints ,
FlatAffineValueConstraints , FlatAffineRelation
}
All derived classes of IntegerRelation.
Protected Member Functions inherited from mlir::presburger::IntegerRelation
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
std::optional< DynamicAPInt > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound if isLower is true, and the upper bound if isLower is false.
template<bool isLower>
std::optional< int64_t > computeConstantLowerOrUpperBound64 (unsigned pos)
The same, but casts to int64_t.
LogicalResult gaussianEliminateVar (unsigned position)
Eliminates a single variable at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateVars (unsigned posStart, unsigned posLimit)
Eliminates variables from equality and inequality constraints in column range [posStart, posLimit).
bool gaussianEliminate ()
Perform a Gaussian elimination operation to reduce all equations to standard form.
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the variable at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that variable.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
bool removeDuplicateConstraints ()
Checks for identical inequalities and eliminates redundant inequalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various variable counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
virtual void printSpace (raw_ostream &os) const
Prints the number of constraints, dimensions, symbols and locals in the IntegerRelation.
void removeVarRange (unsigned varStart, unsigned varLimit)
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
void truncateVarKind (VarKind kind, unsigned num)
Truncate the vars of the specified kind to the specified number by dropping some vars at the end.
void truncateVarKind (VarKind kind, const CountsSnapshot &counts)
Truncate the vars to the number in the space of the specified CountsSnapshot.
Protected Attributes inherited from mlir::presburger::IntegerRelation
PresburgerSpace space
IntMatrix equalities
Coefficients of affine equalities (in == 0 form).
IntMatrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes inherited from mlir::presburger::IntegerRelation
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
An IntegerPolyhedron represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
Affine constraints can be inequalities or equalities in the form:
Inequality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n >= 0 Equality : c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n == 0
where c_0, c_1, ..., c_n are integers and n is the total number of variables in the space.
An IntegerPolyhedron is similar to an IntegerRelation but it does not make a distinction between Domain and Range variables. Internally, IntegerPolyhedron is implemented as a IntegerRelation with zero domain vars.
Since IntegerPolyhedron does not make a distinction between kinds of dimensions, VarKind::SetDim should be used to refer to dimension variables.
Definition at line 991 of file IntegerRelation.h.
Constructor & Destructor Documentation
IntegerPolyhedron() [1/6]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace & space) inline
Constructs a set reserving memory for the specified number of constraints and variables.
Definition at line 995 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::IntegerRelation(), and mlir::presburger::IntegerRelation::space.
Referenced by mlir::affine::FlatAffineRelation::FlatAffineRelation(), mlir::FlatLinearConstraints::FlatLinearConstraints(), mlir::FlatLinearConstraints::FlatLinearConstraints(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), getUniverse(), IntegerPolyhedron(), IntegerPolyhedron(), IntegerPolyhedron(), and intersect().
IntegerPolyhedron() [2/6]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (const PresburgerSpace & space) inline explicit
Constructs a relation with the specified number of dimensions and symbols.
Definition at line 1006 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::getNumVars(), IntegerPolyhedron(), and mlir::presburger::IntegerRelation::space.
IntegerPolyhedron() [3/6]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (const PresburgerSpace & space, const IntMatrix & inequalities) inline explicit
Constructs a relation with the specified number of dimensions and symbols and adds the given inequalities.
Definition at line 1013 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::addInequality(), mlir::presburger::IntegerRelation::inequalities, IntegerPolyhedron(), and mlir::presburger::IntegerRelation::space.
IntegerPolyhedron() [4/6]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (const PresburgerSpace & space, const FracMatrix & inequalities) inline explicit
Constructs a relation with the specified number of dimensions and symbols and adds the given inequalities, after normalizing row-wise to integer values.
Definition at line 1023 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::addInequality(), mlir::presburger::Matrix< T >::getRow(), mlir::presburger::IntegerRelation::inequalities, IntegerPolyhedron(), and mlir::presburger::IntegerRelation::space.
IntegerPolyhedron() [5/6]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (const IntegerRelation & rel) inline explicit
Construct a set from an IntegerRelation.
The relation should have no domain vars.
Definition at line 1033 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::IntegerRelation(), and mlir::presburger::IntegerRelation::space.
IntegerPolyhedron() [6/6]
mlir::presburger::IntegerPolyhedron::IntegerPolyhedron (IntegerRelation && rel) inline explicit
Construct a set from an IntegerRelation, but instead of creating a copy, use move constructor.
The relation should have no domain vars.
Definition at line 1041 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::IntegerRelation(), and mlir::presburger::IntegerRelation::space.
Member Function Documentation
classof()
bool mlir::presburger::IntegerPolyhedron::classof (const IntegerRelation * cst) inline static
Definition at line 1055 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::FlatAffineRelation, mlir::presburger::IntegerRelation::getKind(), mlir::presburger::IntegerRelation::IntegerPolyhedron, and mlir::presburger::IntegerRelation::IntegerRelation().
clone()
std::unique_ptr< IntegerPolyhedron > IntegerPolyhedron::clone () const
Definition at line 50 of file IntegerRelation.cpp.
getKind()
Kind mlir::presburger::IntegerPolyhedron::getKind () const inline override virtual
Return the kind of this IntegerRelation.
Reimplemented from mlir::presburger::IntegerRelation.
Definition at line 1053 of file IntegerRelation.h.
References mlir::presburger::IntegerRelation::IntegerPolyhedron.
getUniverse()
IntegerPolyhedron mlir::presburger::IntegerPolyhedron::getUniverse (const PresburgerSpace & space) inline static
Return a system with no constraints, i.e., one which is satisfied by all points.
Definition at line 1048 of file IntegerRelation.h.
References IntegerPolyhedron(), mlir::presburger::IntegerRelation::IntegerPolyhedron, and mlir::presburger::IntegerRelation::space.
Referenced by mlir::presburger::PresburgerSet::getUniverse().
insertVar()
unsigned IntegerPolyhedron::insertVar (VarKind kind, unsigned pos, unsigned num = 1) override virtual
Insert num variables of the specified kind at position pos.
Positions are relative to the kind of variable. Return the absolute column position (i.e., not relative to the kind of variable) of the first added variable.
Reimplemented from mlir::presburger::IntegerRelation.
Definition at line 2742 of file IntegerRelation.cpp.
References mlir::presburger::Domain, and mlir::presburger::IntegerRelation::insertVar().
Referenced by computeDirectionVector(), mlir::FlatLinearConstraints::insertDimVar(), mlir::FlatLinearConstraints::insertLocalVar(), mlir::FlatLinearConstraints::insertSymbolVar(), mlir::FlatLinearValueConstraints::insertVar(), and mlir::FlatLinearValueConstraints::insertVar().
intersect()
IntegerPolyhedron IntegerPolyhedron::intersect (const IntegerPolyhedron & other) const
Return the intersection of the two relations.
If there are locals, they will be merged.
Definition at line 2749 of file IntegerRelation.cpp.
References IntegerPolyhedron(), mlir::presburger::IntegerRelation::IntegerPolyhedron, and mlir::presburger::IntegerRelation::intersect().
subtract()
PresburgerSet IntegerPolyhedron::subtract (const PresburgerSet & other) const
Return the set difference of this set and the given set, i.e., return this \ set.
Definition at line 2753 of file IntegerRelation.cpp.
References mlir::presburger::IntegerRelation::subtract().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/IntegerRelation.h
lib/Analysis/Presburger/IntegerRelation.cpp