MLIR: mlir::AsmPrinter Class Reference
mlir::AsmPrinter Class Reference
This base class exposes generic asm printer hooks, usable across the various derived printers.
#include "mlir/IR/OpImplementation.h"
Classes
class CyclicPrintReset
Class used to automatically end a cyclic region on destruction.
class Impl
Public Types
template<typename AttrOrType>
using has_print_method
Trait to check if AttrType provides a print method.
template<typename AttrOrType>
using detect_has_print_method
Public Member Functions
AsmPrinter (Impl &impl)
Initialize the printer with the given internal implementation.
virtual ~AsmPrinter ()
virtual raw_ostream & getStream () const
Return the raw output stream used by this printer.
virtual void printFloat (const APFloat &value)
Print the given floating point value in a stabilized form that can be roundtripped through the IR.
template<typename IntT>
std::enable_if_t< std::is_integral_v< IntT >, void > printInteger (IntT value)
Print the given integer value.
virtual void printType (Type type)
virtual void printAttribute (Attribute attr)
template<typename AttrOrType, std::enable_if_t< detect_has_print_method< AttrOrType >::value > * sfinae = nullptr>
void printStrippedAttrOrType (AttrOrType attrOrType)
Print the provided attribute in the context of an operation custom printer/parser: this will invoke directly the print method on the attribute class and skip the #dialect.mnemonic prefix in most cases.
template<typename AttrOrType, std::enable_if_t< detect_has_print_method< AttrOrType >::value > * sfinae = nullptr>
void printStrippedAttrOrType (ArrayRef< AttrOrType > attrOrTypes)
Print the provided array of attributes or types in the context of an operation custom printer/parser: this will invoke directly the print method on the attribute class and skip the #dialect.mnemonic prefix in most cases.
template<typename AttrOrType, std::enable_if_t<!detect_has_print_method< AttrOrType >::value > * sfinae = nullptr>
void printStrippedAttrOrType (AttrOrType attrOrType)
SFINAE for printing the provided attribute in the context of an operation custom printer in the case where the attribute does not define a print method.
virtual void printAttributeWithoutType (Attribute attr)
Print the given attribute without its type.
virtual void printNamedAttribute (NamedAttribute attr)
Print the given named attribute.
virtual LogicalResult printAlias (Attribute attr)
Print the alias for the given attribute, return failure if no alias could be printed.
virtual LogicalResult printAlias (Type type)
Print the alias for the given type, return failure if no alias could be printed.
virtual void printKeywordOrString (StringRef keyword)
Print the given string as a keyword, or a quoted and escaped string if it has any special or non-printable characters in it.
virtual void printString (StringRef string)
Print the given string as a quoted string, escaping any special or non-printable characters in it.
virtual void printSymbolName (StringRef symbolRef)
Print the given string as a symbol reference, i.e.
virtual void printResourceHandle (const AsmDialectResourceHandle &resource)
Print a handle to the given dialect resource.
template<typename TypeRange>
void printOptionalArrowTypeList (TypeRange &&types)
Print an optional arrow followed by a type list.
template<typename TypeRange>
void printArrowTypeList (TypeRange &&types)
template<typename InputRangeT, typename ResultRangeT>
void printFunctionalType (InputRangeT &&inputs, ResultRangeT &&results)
Print the two given type ranges in a functional form.
void printDimensionList (ArrayRef< int64_t > shape)
template<class AttrOrTypeT>
FailureOr< CyclicPrintReset > tryStartCyclicPrint (AttrOrTypeT attrOrType)
Attempts to start a cyclic printing region for attrOrType.
Protected Member Functions
AsmPrinter ()=default
Initialize the printer with no internal implementation.
virtual LogicalResult pushCyclicPrinting (const void *opaquePointer)
Pushes a new attribute or type in the form of a type erased pointer into an internal set.
virtual void popCyclicPrinting ()
Removes the element that was last inserted with a successful call to pushCyclicPrinting.
Detailed Description
This base class exposes generic asm printer hooks, usable across the various derived printers.
Definition at line 120 of file OpImplementation.h.
Member Typedef Documentation
detect_has_print_method
template<typename AttrOrType> using mlir::AsmPrinter::detect_has_print_method
Initial value:
      llvm::is_detected<has_print_method, AttrOrType>
Definition at line 159 of file OpImplementation.h.
has_print_method
template<typename AttrOrType> using mlir::AsmPrinter::has_print_method
Initial value:
      decltype(std::declval<AttrOrType>().print(std::declval<AsmPrinter &>()))
Trait to check if AttrType provides a print method.
Definition at line 156 of file OpImplementation.h.
Constructor & Destructor Documentation
AsmPrinter() [1/2]
mlir::AsmPrinter::AsmPrinter (Impl & impl) inline
Initialize the printer with the given internal implementation.
Definition at line 127 of file OpImplementation.h.
Referenced by AsmPrinter(), and mlir::AsmPrinter::CyclicPrintReset::CyclicPrintReset().
~AsmPrinter()
AsmPrinter::~AsmPrinter () virtual default
AsmPrinter() [2/2]
mlir::AsmPrinter::AsmPrinter () protected default
Initialize the printer with no internal implementation.
In this case, all virtual methods of this class must be overriden.
References AsmPrinter().
Member Function Documentation
getStream()
raw_ostream & AsmPrinter::getStream () const virtual
Return the raw output stream used by this printer.
Definition at line 2956 of file AsmPrinter.cpp.
Referenced by mlir::detail::DenseArrayAttrImpl< T >::print(), mlir::sparse_tensor::ir_detail::Var::print(), printArrowTypeList(), mlir::AsmPrinter::Impl::printDenseArrayAttr(), printDimensionList(), printFunctionalType(), mlir::OpAsmPrinter::printFunctionalType(), printFunctionResultList(), printInteger(), mlir::OpAsmPrinter::printOperands(), mlir::OpState::printOpName(), printString(), printStrippedAttrOrType(), and printStrippedAttrOrType().
popCyclicPrinting()
void AsmPrinter::popCyclicPrinting () protected virtual
Removes the element that was last inserted with a successful call to pushCyclicPrinting.
There must be exactly one popCyclicPrinting call in reverse order of all successful pushCyclicPrinting.
Definition at line 3028 of file AsmPrinter.cpp.
printAlias() [1/2]
LogicalResult AsmPrinter::printAlias (Attribute attr) virtual
Print the alias for the given attribute, return failure if no alias could be printed.
Definition at line 2977 of file AsmPrinter.cpp.
Referenced by mlir::AsmPrinter::Impl::printAttribute(), mlir::AsmPrinter::Impl::printLocation(), printStrippedAttrOrType(), and mlir::AsmPrinter::Impl::printType().
printAlias() [2/2]
LogicalResult AsmPrinter::printAlias (Type type) virtual
Print the alias for the given type, return failure if no alias could be printed.
Definition at line 2982 of file AsmPrinter.cpp.
printArrowTypeList()
template<typename TypeRange> void mlir::AsmPrinter::printArrowTypeList (TypeRange && types) inline
Definition at line 246 of file OpImplementation.h.
References getStream().
Referenced by printFunctionalType(), and printOptionalArrowTypeList().
printAttribute()
void AsmPrinter::printAttribute (Attribute attr) virtual
Definition at line 2972 of file AsmPrinter.cpp.
Referenced by printApplyRegisteredPassOptions(), mlir::AsmPrinter::Impl::printAttributeImpl(), mlir::AsmPrinter::Impl::printLocationInternal(), mlir::AsmPrinter::Impl::printNamedAttribute(), printTypedInitialValue(), mlir::AsmPrinter::Impl::printTypeImpl(), and mlir::tosa::printVariableOpTypeOrInitialValue().
printAttributeWithoutType()
void AsmPrinter::printAttributeWithoutType (Attribute attr) virtual
Print the given attribute without its type.
The corresponding parser must provide a valid type for the attribute.
Definition at line 2987 of file AsmPrinter.cpp.
References mlir::AsmPrinter::Impl::Must.
Referenced by print(), printEmitCFieldOpTypeAndInitialValue(), printEmitCGlobalOpTypeAndInitialValue(), and printGlobalMemrefOpTypeAndInitialValue().
printDimensionList()
void AsmPrinter::printDimensionList (ArrayRef< int64_t > shape)
Definition at line 3020 of file AsmPrinter.cpp.
References getStream(), and mlir::detail::printDimensionList().
Referenced by mlir::printDimensionList(), mlir::amdgpu::printMNKDimensionList(), and mlir::AsmPrinter::Impl::printTypeImpl().
printFloat()
void AsmPrinter::printFloat (const APFloat & value) virtual
Print the given floating point value in a stabilized form that can be roundtripped through the IR.
Print the given floating point value in a stablized form.
This is the companion to the 'parseFloat' hook on the AsmParser.
Definition at line 2962 of file AsmPrinter.cpp.
References printFloatValue().
printFunctionalType()
template<typename InputRangeT, typename ResultRangeT> void mlir::AsmPrinter::printFunctionalType (InputRangeT && inputs, ResultRangeT && results) inline
Print the two given type ranges in a functional form.
Definition at line 260 of file OpImplementation.h.
References getStream(), and printArrowTypeList().
Referenced by mlir::OpAsmPrinter::printAffineExprOfSSAIds().
printInteger()
template<typename IntT> std::enable_if_t< std::is_integral_v< IntT >, void > mlir::AsmPrinter::printInteger (IntT value) inline
Print the given integer value.
This is useful to force a uint8_t/int8_t to be printed as an integer instead of a char.
Definition at line 141 of file OpImplementation.h.
References getStream().
printKeywordOrString()
void AsmPrinter::printKeywordOrString (StringRef keyword) virtual
Print the given string as a keyword, or a quoted and escaped string if it has any special or non-printable characters in it.
Definition at line 2998 of file AsmPrinter.cpp.
References printKeywordOrString().
Referenced by printKeywordOrString(), mlir::AsmPrinter::Impl::printNamedAttribute(), mlir::AsmPrinter::Impl::printResourceHandle(), and printSymbolReference().
printNamedAttribute()
void AsmPrinter::printNamedAttribute (NamedAttribute attr) virtual
Print the given named attribute.
Definition at line 2993 of file AsmPrinter.cpp.
Referenced by mlir::OpState::genericPrintProperties(), and mlir::AsmPrinter::Impl::printOptionalAttrDict().
printOptionalArrowTypeList()
template<typename TypeRange> void mlir::AsmPrinter::printOptionalArrowTypeList (TypeRange && types) inline
Print an optional arrow followed by a type list.
Definition at line 241 of file OpImplementation.h.
References printArrowTypeList().
Referenced by printNamedStructuredOpResults().
printResourceHandle()
void AsmPrinter::printResourceHandle (const AsmDialectResourceHandle & resource) virtual
Print a handle to the given dialect resource.
The handle key is quoted and escaped if it has any special or non-printable characters in it.
Definition at line 3015 of file AsmPrinter.cpp.
Referenced by mlir::AsmPrinter::Impl::printAttributeImpl().
printString()
void AsmPrinter::printString (StringRef string) virtual
Print the given string as a quoted string, escaping any special or non-printable characters in it.
Definition at line 3003 of file AsmPrinter.cpp.
References getStream().
Referenced by printOneOpBundle().
printStrippedAttrOrType() [1/3]
template<typename AttrOrType, std::enable_if_t< detect_has_print_method< AttrOrType >::value > * sfinae = nullptr> void mlir::AsmPrinter::printStrippedAttrOrType (ArrayRef< AttrOrType > attrOrTypes) inline
Print the provided array of attributes or types in the context of an operation custom printer/parser: this will invoke directly the print method on the attribute class and skip the #dialect.mnemonic prefix in most cases.
Definition at line 190 of file OpImplementation.h.
References getStream(), and printStrippedAttrOrType().
printStrippedAttrOrType() [2/3]
template<typename AttrOrType, std::enable_if_t< detect_has_print_method< AttrOrType >::value > * sfinae = nullptr> void mlir::AsmPrinter::printStrippedAttrOrType (AttrOrType attrOrType) inline
Print the provided attribute in the context of an operation custom printer/parser: this will invoke directly the print method on the attribute class and skip the #dialect.mnemonic prefix in most cases.
Definition at line 168 of file OpImplementation.h.
References getStream(), and printAlias().
Referenced by printStrippedAttrOrType().
printStrippedAttrOrType() [3/3]
template<typename AttrOrType, std::enable_if_t<!detect_has_print_method< AttrOrType >::value > * sfinae = nullptr> void mlir::AsmPrinter::printStrippedAttrOrType (AttrOrType attrOrType) inline
SFINAE for printing the provided attribute in the context of an operation custom printer in the case where the attribute does not define a print method.
Definition at line 202 of file OpImplementation.h.
printSymbolName()
void AsmPrinter::printSymbolName (StringRef symbolRef) virtual
Print the given string as a symbol reference, i.e.
a form representable by a SymbolRefAttr. A symbol reference is represented as a string prefixed with '@'. The reference is surrounded with ""'s and escaped if it has any special or non-printable characters in it.
Definition at line 3010 of file AsmPrinter.cpp.
References printSymbolReference().
Referenced by mlir::function_interface_impl::printFunctionOp().
printType()
void AsmPrinter::printType (Type type) virtual
Definition at line 2967 of file AsmPrinter.cpp.
Referenced by dispatchPrint(), printAccVar(), mlir::AsmPrinter::Impl::printAttributeImpl(), mlir::call_interface_impl::printFunctionSignature(), printOperandWithKeywordOnly(), printTokenOrdering(), mlir::AsmPrinter::Impl::printTypeImpl(), and printVarPtrType().
pushCyclicPrinting()
LogicalResult AsmPrinter::pushCyclicPrinting (const void * opaquePointer) protected virtual
Pushes a new attribute or type in the form of a type erased pointer into an internal set.
Returns success if the type or attribute was inserted in the set or failure if it was already contained.
Definition at line 3024 of file AsmPrinter.cpp.
Referenced by tryStartCyclicPrint().
tryStartCyclicPrint()
template<class AttrOrTypeT> FailureOr< CyclicPrintReset > mlir::AsmPrinter::tryStartCyclicPrint (AttrOrTypeT attrOrType) inline
Attempts to start a cyclic printing region for attrOrType.
A cyclic printing region starts with this call and ends with the destruction of the returned CyclicPrintReset. During this time, calling tryStartCyclicPrint with the same attribute in any printer will lead to returning failure.
This makes it possible to break infinite recursions when trying to print cyclic attributes or types by printing only immutable parameters if nested within itself.
Definition at line 306 of file OpImplementation.h.
References pushCyclicPrinting().
Referenced by print().
The documentation for this class was generated from the following files:
include/mlir/IR/OpImplementation.h
lib/IR/AsmPrinter.cpp