MLIR: mlir::python::PyBlock Class Reference
mlir::python::PyBlock Class Reference
Wrapper around an MlirBlock.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyBlock (PyOperationRef parentOperation, MlirBlock block)
MlirBlock get ()
PyOperationRef & getParentOperation ()
void checkValid ()
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirBlock.
Detailed Description
Wrapper around an MlirBlock.
Blocks are managed completely by their containing operation. Unlike the C++ API, the python API does not support detached blocks.
Definition at line 859 of file IRModule.h.
Constructor & Destructor Documentation
PyBlock()
mlir::python::PyBlock::PyBlock (PyOperationRef parentOperation, MlirBlock block) inline
Definition at line 861 of file IRModule.h.
References mlirBlockIsNull().
Member Function Documentation
checkValid()
void mlir::python::PyBlock::checkValid () inline
Definition at line 869 of file IRModule.h.
References mlir::python::PyOperation::checkValid().
get()
MlirBlock mlir::python::PyBlock::get () inline
Definition at line 866 of file IRModule.h.
Referenced by mlir::python::PyInsertionPoint::atBlockBegin(), and mlir::python::PyInsertionPoint::atBlockTerminator().
getCapsule()
nb::object PyBlock::getCapsule ()
Gets a capsule wrapping the void* within the MlirBlock.
Definition at line 329 of file IRCore.cpp.
References mlir::get(), and mlirPythonBlockToCapsule().
getParentOperation()
PyOperationRef& mlir::python::PyBlock::getParentOperation () inline
Definition at line 867 of file IRModule.h.
Referenced by mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), and mlir::python::PyThreadContextEntry::pushInsertionPoint().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp