MLIR: mlir::OwningMemRef< T, Rank > Class Template Reference
mlir::OwningMemRef< T, Rank > Class Template Reference
Owning MemRef type that abstracts over the runtime type for ranked strided memref.
#include "mlir/ExecutionEngine/MemRefUtils.h"
Public Types
using DescriptorType = StridedMemRefType<T, Rank>
using FreeFunType = std::function<void(DescriptorType)>
Public Member Functions
OwningMemRef (ArrayRef< int64_t > shape, ArrayRef< int64_t > shapeAlloc={}, ElementWiseVisitor< T > init={}, std::optional< uint64_t > alignment=std::optional< uint64_t >(), AllocFunType allocFun=&::malloc, std::function< void(StridedMemRefType< T, Rank >)> freeFun=[](StridedMemRefType< T, Rank > descriptor) { ::free(descriptor.basePtr);})
Allocate a new dense StridedMemrefRef with a given shape.
OwningMemRef (DescriptorType descriptor, FreeFunType freeFunc)
Take ownership of an existing descriptor with a custom deleter.
~OwningMemRef ()
OwningMemRef (const OwningMemRef &)=delete
OwningMemRef & operator= (const OwningMemRef &)=delete
OwningMemRef & operator= (const OwningMemRef &&other)
OwningMemRef (OwningMemRef &&other)
DescriptorType & operator* ()
DescriptorType * operator-> ()
T & operator[] (std::initializer_list< int64_t > indices)
Detailed Description
template<typename T, unsigned Rank>
class mlir::OwningMemRef< T, Rank >
Owning MemRef type that abstracts over the runtime type for ranked strided memref.
Definition at line 136 of file MemRefUtils.h.
Member Typedef Documentation
DescriptorType
template<typename T, unsigned Rank> using mlir::OwningMemRef< T, Rank >::DescriptorType = StridedMemRefType<T, Rank>
Definition at line 138 of file MemRefUtils.h.
FreeFunType
template<typename T, unsigned Rank> using mlir::OwningMemRef< T, Rank >::FreeFunType = std::function<void(DescriptorType)>
Definition at line 139 of file MemRefUtils.h.
Constructor & Destructor Documentation
OwningMemRef() [1/4]
template<typename T, unsigned Rank> mlir::OwningMemRef< T, Rank >::OwningMemRef (ArrayRef< int64_t > shape, ArrayRef< int64_t > shapeAlloc = {}, ElementWiseVisitor< T > init = {}, std::optional< uint64_t > alignment = std::optional<uint64_t>(), AllocFunType allocFun = &::malloc, std::function< void(StridedMemRefType< T, Rank >)> freeFun = [](StridedMemRefType<T, Rank> descriptor) { ::free(descriptor.basePtr); }) inline
Allocate a new dense StridedMemrefRef with a given shape.
An optional shapeAlloc array can be supplied to "pad" every dimension individually. If an ElementWiseVisitor is provided, it will be used to initialize the data, else the memory will be zero-initialized. The alloc and free method used to manage the data allocation can be optionally provided, and default to malloc/free.
Definition at line 147 of file MemRefUtils.h.
Referenced by operator=(), operator=(), OwningMemRef(), and OwningMemRef().
OwningMemRef() [2/4]
template<typename T, unsigned Rank> mlir::OwningMemRef< T, Rank >::OwningMemRef (DescriptorType descriptor, FreeFunType freeFunc) inline
Take ownership of an existing descriptor with a custom deleter.
Definition at line 181 of file MemRefUtils.h.
~OwningMemRef()
template<typename T, unsigned Rank> mlir::OwningMemRef< T, Rank >::~OwningMemRef () inline
Definition at line 183 of file MemRefUtils.h.
OwningMemRef() [3/4]
template<typename T, unsigned Rank> mlir::OwningMemRef< T, Rank >::OwningMemRef (const OwningMemRef< T, Rank > &) delete
References OwningMemRef().
OwningMemRef() [4/4]
template<typename T, unsigned Rank> mlir::OwningMemRef< T, Rank >::OwningMemRef (OwningMemRef< T, Rank > && other) inline
Definition at line 195 of file MemRefUtils.h.
References OwningMemRef().
Member Function Documentation
operator*()
template<typename T, unsigned Rank> DescriptorType & mlir::OwningMemRef< T, Rank >::operator* () inline
Definition at line 197 of file MemRefUtils.h.
operator->()
template<typename T, unsigned Rank> DescriptorType * mlir::OwningMemRef< T, Rank >::operator-> () inline
Definition at line 198 of file MemRefUtils.h.
operator=() [1/2]
template<typename T, unsigned Rank> OwningMemRef & mlir::OwningMemRef< T, Rank >::operator= (const OwningMemRef< T, Rank > && other) inline
Definition at line 189 of file MemRefUtils.h.
References OwningMemRef().
operator=() [2/2]
template<typename T, unsigned Rank> OwningMemRef & mlir::OwningMemRef< T, Rank >::operator= (const OwningMemRef< T, Rank > &) delete
References OwningMemRef().
operator[]()
template<typename T, unsigned Rank> T & mlir::OwningMemRef< T, Rank >::operator[] (std::initializer_list< int64_t > indices) inline
Definition at line 199 of file MemRefUtils.h.
References indices.
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/MemRefUtils.h