MLIR: mlir::OpTrait::FunctionLike< ConcreteType > Class Template Reference
mlir::OpTrait::FunctionLike< ConcreteType > Class Template Reference
This trait provides APIs for Ops that behave like functions.
#include "mlir/IR/FunctionSupport.h"
Public Types
using BlockListType = Region::BlockListType
This is the list of blocks in the function.
using iterator = BlockListType::iterator
using reverse_iterator = BlockListType::reverse_iterator
using BlockArgListType = Region::BlockArgListType
using args_iterator = Region::args_iterator
Support argument iteration.
Public Member Functions
bool isExternal ()
Returns true if this function is external, i.e. it has no body.
Region & getBody ()
void eraseBody ()
Delete all blocks from this function.
BlockListType & getBlocks ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
bool empty ()
void push_back (Block *block)
void push_front (Block *block)
Block & back ()
Block & front ()
Block * addEntryBlock ()
Add an entry block to an empty function, and set up the block arguments to match the signature of the function.
Block * addBlock ()
Add a normal block to the end of the function's block list.
LogicalResult verifyBody ()
Hook for concrete ops to verify the contents of the body.
TypeAttr getTypeAttr ()
FunctionType getType ()
Return the type of this function.
FunctionType getTypeWithArgsAndResults (ArrayRef< unsigned > argIndices, TypeRange argTypes, ArrayRef< unsigned > resultIndices, TypeRange resultTypes)
Return the type of this function with the specified arguments and results inserted.
FunctionType getTypeWithoutArgsAndResults (ArrayRef< unsigned > argIndices, ArrayRef< unsigned > resultIndices)
Return the type of this function without the specified arguments and results.
bool isTypeAttrValid ()
void setType (FunctionType newType)
Change the type of this function in place.
unsigned getNumArguments ()
unsigned getNumResults ()
BlockArgument getArgument (unsigned idx)
Gets argument.
args_iterator args_begin ()
args_iterator args_end ()
Block::BlockArgListType getArguments ()
ValueTypeRange< BlockArgListType > getArgumentTypes ()
void insertArgument (unsigned argIndex, Type argType, DictionaryAttr argAttrs, Optional< Location > argLoc={})
Insert a single argument of type argType with attributes argAttrs and location argLoc at argIndex.
void insertArguments (ArrayRef< unsigned > argIndices, TypeRange argTypes, ArrayRef< DictionaryAttr > argAttrs, ArrayRef< Optional< Location >> argLocs)
Inserts arguments with the listed types, attributes, and locations at the listed indices.
void insertResult (unsigned resultIndex, Type resultType, DictionaryAttr resultAttrs)
Insert a single result of type resultType at resultIndex.
void insertResults (ArrayRef< unsigned > resultIndices, TypeRange resultTypes, ArrayRef< DictionaryAttr > resultAttrs)
Inserts results with the listed types at the listed indices.
void eraseArgument (unsigned argIndex)
Erase a single argument at argIndex.
void eraseArguments (ArrayRef< unsigned > argIndices)
Erases the arguments listed in argIndices.
void eraseResult (unsigned resultIndex)
Erase a single result at resultIndex.
void eraseResults (ArrayRef< unsigned > resultIndices)
Erases the results listed in resultIndices.
ArrayRef< NamedAttribute > getArgAttrs (unsigned index)
FunctionLike operations allow for attaching attributes to each of the respective function arguments.
ArrayAttr getAllArgAttrs ()
Return an ArrayAttr containing all argument attribute dictionaries of this function, or nullptr if no arguments have attributes.
void getAllArgAttrs (SmallVectorImpl< DictionaryAttr > &result)
Return all argument attributes of this function.
Attribute getArgAttr (unsigned index, Identifier name)
Return the specified attribute, if present, for the argument at 'index', null otherwise.
Attribute getArgAttr (unsigned index, StringRef name)
template<typename AttrClass >
AttrClass getArgAttrOfType (unsigned index, Identifier name)
template<typename AttrClass >
AttrClass getArgAttrOfType (unsigned index, StringRef name)
void setArgAttrs (unsigned index, ArrayRef< NamedAttribute > attributes)
Set the attributes held by the argument at 'index'.
void setArgAttrs (unsigned index, DictionaryAttr attributes)
Set the attributes held by the argument at 'index'.
void setAllArgAttrs (ArrayRef< DictionaryAttr > attributes)
void setAllArgAttrs (ArrayRef< Attribute > attributes)
void setAllArgAttrs (ArrayAttr attributes)
void setArgAttr (unsigned index, Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setArgAttr (unsigned index, StringRef name, Attribute value)
Attribute removeArgAttr (unsigned index, Identifier name)
Remove the attribute 'name' from the argument at 'index'.
Attribute removeArgAttr (unsigned index, StringRef name)
ArrayRef< NamedAttribute > getResultAttrs (unsigned index)
FunctionLike operations allow for attaching attributes to each of the respective function results.
ArrayAttr getAllResultAttrs ()
Return an ArrayAttr containing all result attribute dictionaries of this function, or nullptr if no result have attributes.
void getAllResultAttrs (SmallVectorImpl< DictionaryAttr > &result)
Return all result attributes of this function.
Attribute getResultAttr (unsigned index, Identifier name)
Return the specified attribute, if present, for the result at 'index', null otherwise.
Attribute getResultAttr (unsigned index, StringRef name)
template<typename AttrClass >
AttrClass getResultAttrOfType (unsigned index, Identifier name)
template<typename AttrClass >
AttrClass getResultAttrOfType (unsigned index, StringRef name)
void setResultAttrs (unsigned index, ArrayRef< NamedAttribute > attributes)
Set the attributes held by the result at 'index'.
void setResultAttrs (unsigned index, DictionaryAttr attributes)
Set the attributes held by the result at 'index'.
void setAllResultAttrs (ArrayRef< DictionaryAttr > attributes)
void setAllResultAttrs (ArrayRef< Attribute > attributes)
void setAllResultAttrs (ArrayAttr attributes)
void setResultAttr (unsigned index, Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setResultAttr (unsigned index, StringRef name, Attribute value)
Attribute removeResultAttr (unsigned index, Identifier name)
Remove the attribute 'name' from the result at 'index'.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Verify that all of the argument attributes are dialect attributes.
static StringRef getTypeAttrName ()
Return the name of the attribute used for function types.
Protected Member Functions
DictionaryAttr getArgAttrDict (unsigned index)
Returns the dictionary attribute corresponding to the argument at 'index'.
DictionaryAttr getResultAttrDict (unsigned index)
Returns the dictionary attribute corresponding to the result at 'index'.
LogicalResult verifyType ()
Hook for concrete classes to verify that the type attribute respects op-specific invariants.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, FunctionLike >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::FunctionLike< ConcreteType >
This trait provides APIs for Ops that behave like functions.
In particular:
Ops must be symbols, i.e. also have the Symbol trait;
Ops have a single region with multiple blocks that corresponds to the body of the function;
An op with a single empty region corresponds to an external function;
leading arguments of the first block of the region are treated as function arguments;
they can have argument attributes that are stored in a dictionary attribute on the Op itself.
This trait provides limited type support for the declared or defined functions. The convenience function getTypeAttrName() returns the name of an attribute that can be used to store the function type. In addition, this trait provides getType and setType helpers to store a FunctionType in the attribute named by getTypeAttrName().
In general, this trait assumes concrete ops use FunctionType under the hood. If this is not the case, in order to use the function type support, concrete ops must define the following methods, using the same name, to hide the ones defined for FunctionType: addBodyBlock, getType, getTypeWithoutArgsAndResults and setType.
Besides the requirements above, concrete ops must interact with this trait using the following functions:
Concrete ops must define a member function getNumFuncArguments() that returns the number of function arguments based exclusively on type (so that it can be called on function declarations).
Concrete ops must define a member function getNumFuncResults() that returns the number of function results based exclusively on type (so that it can be called on function declarations).
To verify that the type respects op-specific invariants, concrete ops may redefine the verifyType() hook that will be called after verifying the presence of the type attribute and before any call to getNumFuncArguments/getNumFuncResults from the verifier.
To verify that the body respects op-specific invariants, concrete ops may redefine the verifyBody() hook that will be called after verifying the function type and the presence of the (potentially empty) body region.
Definition at line 141 of file FunctionSupport.h.
Member Typedef Documentation
args_iterator
template<typename ConcreteType > using mlir::OpTrait::FunctionLike< ConcreteType >::args_iterator = Region::args_iterator
Support argument iteration.
Definition at line 290 of file FunctionSupport.h.
BlockArgListType
template<typename ConcreteType > using mlir::OpTrait::FunctionLike< ConcreteType >::BlockArgListType = Region::BlockArgListType
Definition at line 276 of file FunctionSupport.h.
BlockListType
template<typename ConcreteType > using mlir::OpTrait::FunctionLike< ConcreteType >::BlockListType = Region::BlockListType
This is the list of blocks in the function.
Definition at line 164 of file FunctionSupport.h.
iterator
template<typename ConcreteType > using mlir::OpTrait::FunctionLike< ConcreteType >::iterator = BlockListType::iterator
Definition at line 168 of file FunctionSupport.h.
reverse_iterator
template<typename ConcreteType > using mlir::OpTrait::FunctionLike< ConcreteType >::reverse_iterator = BlockListType::reverse_iterator
Definition at line 169 of file FunctionSupport.h.
Member Function Documentation
addBlock()
template<typename ConcreteType > Block * mlir::OpTrait::FunctionLike< ConcreteType >::addBlock ()
Add a normal block to the end of the function's block list.
The function should at least already have an entry block.
Definition at line 679 of file FunctionSupport.h.
addEntryBlock()
template<typename ConcreteType > Block * mlir::OpTrait::FunctionLike< ConcreteType >::addEntryBlock ()
Add an entry block to an empty function, and set up the block arguments to match the signature of the function.
The newly inserted entry block is returned.
Note that the concrete class must define a method with the same name to hide this one if the concrete class does not use FunctionType for the function type under the hood.
Definition at line 670 of file FunctionSupport.h.
args_begin()
template<typename ConcreteType > args_iterator mlir::OpTrait::FunctionLike< ConcreteType >::args_begin () inline
Definition at line 291 of file FunctionSupport.h.
args_end()
template<typename ConcreteType > args_iterator mlir::OpTrait::FunctionLike< ConcreteType >::args_end () inline
Definition at line 292 of file FunctionSupport.h.
back()
template<typename ConcreteType > Block& mlir::OpTrait::FunctionLike< ConcreteType >::back () inline
Definition at line 180 of file FunctionSupport.h.
References mlir::Block::back().
begin()
template<typename ConcreteType > iterator mlir::OpTrait::FunctionLike< ConcreteType >::begin () inline
Definition at line 171 of file FunctionSupport.h.
empty()
template<typename ConcreteType > bool mlir::OpTrait::FunctionLike< ConcreteType >::empty () inline
Definition at line 176 of file FunctionSupport.h.
end()
template<typename ConcreteType > iterator mlir::OpTrait::FunctionLike< ConcreteType >::end () inline
Definition at line 172 of file FunctionSupport.h.
eraseArgument()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::eraseArgument (unsigned argIndex) inline
Erase a single argument at argIndex.
Definition at line 342 of file FunctionSupport.h.
eraseArguments()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::eraseArguments (ArrayRef< unsigned > argIndices) inline
Erases the arguments listed in argIndices.
argIndices is allowed to have duplicates and can be in any order.
Definition at line 346 of file FunctionSupport.h.
References mlir::function_like_impl::eraseFunctionArguments().
eraseBody()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::eraseBody () inline
Delete all blocks from this function.
Definition at line 158 of file FunctionSupport.h.
eraseResult()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::eraseResult (unsigned resultIndex) inline
Erase a single result at resultIndex.
Definition at line 354 of file FunctionSupport.h.
eraseResults()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::eraseResults (ArrayRef< unsigned > resultIndices) inline
Erases the results listed in resultIndices.
resultIndices is allowed to have duplicates and can be in any order.
Definition at line 358 of file FunctionSupport.h.
References mlir::function_like_impl::eraseFunctionResults().
front()
template<typename ConcreteType > Block& mlir::OpTrait::FunctionLike< ConcreteType >::front () inline
Definition at line 181 of file FunctionSupport.h.
References mlir::Block::front().
getAllArgAttrs() [1/2]
template<typename ConcreteType > ArrayAttr mlir::OpTrait::FunctionLike< ConcreteType >::getAllArgAttrs () inline
Return an ArrayAttr containing all argument attribute dictionaries of this function, or nullptr if no arguments have attributes.
Definition at line 383 of file FunctionSupport.h.
References mlir::function_like_impl::getArgDictAttrName().
getAllArgAttrs() [2/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::getAllArgAttrs (SmallVectorImpl< DictionaryAttr > & result) inline
Return all argument attributes of this function.
Definition at line 388 of file FunctionSupport.h.
getAllResultAttrs() [1/2]
template<typename ConcreteType > ArrayAttr mlir::OpTrait::FunctionLike< ConcreteType >::getAllResultAttrs () inline
Return an ArrayAttr containing all result attribute dictionaries of this function, or nullptr if no result have attributes.
Definition at line 472 of file FunctionSupport.h.
References mlir::function_like_impl::getResultDictAttrName().
getAllResultAttrs() [2/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::getAllResultAttrs (SmallVectorImpl< DictionaryAttr > & result) inline
Return all result attributes of this function.
Definition at line 477 of file FunctionSupport.h.
getArgAttr() [1/2]
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttr (unsigned index, Identifier name) inline
Return the specified attribute, if present, for the argument at 'index', null otherwise.
Definition at line 399 of file FunctionSupport.h.
References mlir::function_like_impl::getArgAttrDict().
getArgAttr() [2/2]
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttr (unsigned index, StringRef name) inline
Definition at line 403 of file FunctionSupport.h.
References mlir::function_like_impl::getArgAttrDict().
getArgAttrDict()
template<typename ConcreteType > DictionaryAttr mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrDict (unsigned index) inline protected
Returns the dictionary attribute corresponding to the argument at 'index'.
If there are no argument attributes at 'index', a null attribute is returned.
Definition at line 544 of file FunctionSupport.h.
References mlir::function_like_impl::getArgAttrDict().
getArgAttrOfType() [1/2]
template<typename ConcreteType > template<typename AttrClass > AttrClass mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrOfType (unsigned index, Identifier name) inline
Definition at line 409 of file FunctionSupport.h.
getArgAttrOfType() [2/2]
template<typename ConcreteType > template<typename AttrClass > AttrClass mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrOfType (unsigned index, StringRef name) inline
Definition at line 413 of file FunctionSupport.h.
getArgAttrs()
template<typename ConcreteType > ArrayRef<NamedAttribute> mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrs (unsigned index) inline
FunctionLike operations allow for attaching attributes to each of the respective function arguments.
These argument attributes are stored as DictionaryAttrs in the main operation attribute dictionary. The name of these entries is arg followed by the index of the argument. These argument attribute dictionaries are optional, and will generally only exist if they are non-empty. Return all of the attributes for the argument at 'index'.
Definition at line 377 of file FunctionSupport.h.
References mlir::function_like_impl::getArgAttrs().
getArgument()
template<typename ConcreteType > BlockArgument mlir::OpTrait::FunctionLike< ConcreteType >::getArgument (unsigned idx) inline
Gets argument.
Definition at line 287 of file FunctionSupport.h.
getArguments()
template<typename ConcreteType > Block::BlockArgListType mlir::OpTrait::FunctionLike< ConcreteType >::getArguments () inline
Definition at line 293 of file FunctionSupport.h.
getArgumentTypes()
template<typename ConcreteType > ValueTypeRange<BlockArgListType> mlir::OpTrait::FunctionLike< ConcreteType >::getArgumentTypes () inline
Definition at line 295 of file FunctionSupport.h.
getBlocks()
template<typename ConcreteType > BlockListType& mlir::OpTrait::FunctionLike< ConcreteType >::getBlocks () inline
Definition at line 165 of file FunctionSupport.h.
getBody()
template<typename ConcreteType > Region& mlir::OpTrait::FunctionLike< ConcreteType >::getBody () inline
Definition at line 153 of file FunctionSupport.h.
References mlir::function_like_impl::getFunctionBody().
getNumArguments()
template<typename ConcreteType > unsigned mlir::OpTrait::FunctionLike< ConcreteType >::getNumArguments () inline
Definition at line 278 of file FunctionSupport.h.
getNumResults()
template<typename ConcreteType > unsigned mlir::OpTrait::FunctionLike< ConcreteType >::getNumResults () inline
Definition at line 282 of file FunctionSupport.h.
getResultAttr() [1/2]
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttr (unsigned index, Identifier name) inline
Return the specified attribute, if present, for the result at 'index', null otherwise.
Definition at line 488 of file FunctionSupport.h.
References mlir::function_like_impl::getResultAttrDict().
getResultAttr() [2/2]
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttr (unsigned index, StringRef name) inline
Definition at line 492 of file FunctionSupport.h.
References mlir::function_like_impl::getResultAttrDict().
getResultAttrDict()
template<typename ConcreteType > DictionaryAttr mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrDict (unsigned index) inline protected
Returns the dictionary attribute corresponding to the result at 'index'.
If there are no result attributes at 'index', a null attribute is returned.
Definition at line 552 of file FunctionSupport.h.
References mlir::function_like_impl::getResultAttrDict().
getResultAttrOfType() [1/2]
template<typename ConcreteType > template<typename AttrClass > AttrClass mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrOfType (unsigned index, Identifier name) inline
Definition at line 498 of file FunctionSupport.h.
getResultAttrOfType() [2/2]
template<typename ConcreteType > template<typename AttrClass > AttrClass mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrOfType (unsigned index, StringRef name) inline
Definition at line 502 of file FunctionSupport.h.
getResultAttrs()
template<typename ConcreteType > ArrayRef<NamedAttribute> mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrs (unsigned index) inline
FunctionLike operations allow for attaching attributes to each of the respective function results.
These result attributes are stored as DictionaryAttrs in the main operation attribute dictionary. The name of these entries is result followed by the index of the result. These result attribute dictionaries are optional, and will generally only exist if they are non-empty. Return all of the attributes for the result at 'index'.
Definition at line 466 of file FunctionSupport.h.
References mlir::function_like_impl::getResultAttrs().
getType()
template<typename ConcreteType > FunctionType mlir::OpTrait::FunctionLike< ConcreteType >::getType () inline
Return the type of this function.
Note that the concrete class must define a method with the same name to hide this one if the concrete class does not use FunctionType for the function type under the hood.
Definition at line 220 of file FunctionSupport.h.
References mlir::function_like_impl::getFunctionType().
getTypeAttr()
template<typename ConcreteType > TypeAttr mlir::OpTrait::FunctionLike< ConcreteType >::getTypeAttr () inline
Definition at line 210 of file FunctionSupport.h.
References mlir::function_like_impl::getTypeAttrName().
getTypeAttrName()
template<typename ConcreteType > static StringRef mlir::OpTrait::FunctionLike< ConcreteType >::getTypeAttrName () inline static
Return the name of the attribute used for function types.
Definition at line 206 of file FunctionSupport.h.
References mlir::function_like_impl::getTypeAttrName().
getTypeWithArgsAndResults()
template<typename ConcreteType > FunctionType mlir::OpTrait::FunctionLike< ConcreteType >::getTypeWithArgsAndResults (ArrayRef< unsigned > argIndices, TypeRange argTypes, ArrayRef< unsigned > resultIndices, TypeRange resultTypes) inline
Return the type of this function with the specified arguments and results inserted.
This is used to update the function's signature in the insertArguments and insertResults methods. The arrays must be sorted by increasing index.
Note that the concrete class must define a method with the same name to hide this one if the concrete class does not use FunctionType for the function type under the hood.
Definition at line 232 of file FunctionSupport.h.
getTypeWithoutArgsAndResults()
template<typename ConcreteType > FunctionType mlir::OpTrait::FunctionLike< ConcreteType >::getTypeWithoutArgsAndResults (ArrayRef< unsigned > argIndices, ArrayRef< unsigned > resultIndices) inline
Return the type of this function without the specified arguments and results.
This is used to update the function's signature in the eraseArguments and eraseResults methods. The arrays of indices are allowed to have duplicates and can be in any order.
Note that the concrete class must define a method with the same name to hide this one if the concrete class does not use FunctionType for the function type under the hood.
Definition at line 248 of file FunctionSupport.h.
insertArgument()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::insertArgument (unsigned argIndex, Type argType, DictionaryAttr argAttrs, Optional< Location > argLoc = {}) inline
Insert a single argument of type argType with attributes argAttrs and location argLoc at argIndex.
Definition at line 301 of file FunctionSupport.h.
insertArguments()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::insertArguments (ArrayRef< unsigned > argIndices, TypeRange argTypes, ArrayRef< DictionaryAttr > argAttrs, ArrayRef< Optional< Location >> argLocs) inline
Inserts arguments with the listed types, attributes, and locations at the listed indices.
argIndices must be sorted. Arguments are inserted in the order they are listed, such that arguments with identical index will appear in the same order that they were listed here.
Definition at line 310 of file FunctionSupport.h.
References mlir::function_like_impl::insertFunctionArguments().
insertResult()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::insertResult (unsigned resultIndex, Type resultType, DictionaryAttr resultAttrs) inline
Insert a single result of type resultType at resultIndex.
Definition at line 322 of file FunctionSupport.h.
insertResults()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::insertResults (ArrayRef< unsigned > resultIndices, TypeRange resultTypes, ArrayRef< DictionaryAttr > resultAttrs) inline
Inserts results with the listed types at the listed indices.
resultIndices must be sorted. Results are inserted in the order they are listed, such that results with identical index will appear in the same order that they were listed here.
Definition at line 331 of file FunctionSupport.h.
References mlir::function_like_impl::insertFunctionResults().
isExternal()
template<typename ConcreteType > bool mlir::OpTrait::FunctionLike< ConcreteType >::isExternal () inline
Returns true if this function is external, i.e. it has no body.
Definition at line 151 of file FunctionSupport.h.
isTypeAttrValid()
template<typename ConcreteType > bool mlir::OpTrait::FunctionLike< ConcreteType >::isTypeAttrValid () inline
Definition at line 253 of file FunctionSupport.h.
push_back()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::push_back (Block * block) inline
Definition at line 177 of file FunctionSupport.h.
push_front()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::push_front (Block * block) inline
Definition at line 178 of file FunctionSupport.h.
rbegin()
template<typename ConcreteType > reverse_iterator mlir::OpTrait::FunctionLike< ConcreteType >::rbegin () inline
Definition at line 173 of file FunctionSupport.h.
removeArgAttr() [1/2]
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr (unsigned index, Identifier name)
Remove the attribute 'name' from the argument at 'index'.
Return the attribute that was erased, or nullptr if there was no attribute with such name.
Definition at line 733 of file FunctionSupport.h.
References mlir::NamedAttrList::erase(), mlir::function_like_impl::getArgAttrDict(), mlir::Attribute::getContext(), and mlir::NamedAttrList::getDictionary().
removeArgAttr() [2/2]
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr (unsigned index, StringRef name) inline
Definition at line 449 of file FunctionSupport.h.
References mlir::Identifier::get().
removeResultAttr()
template<typename ConcreteType > Attribute mlir::OpTrait::FunctionLike< ConcreteType >::removeResultAttr (unsigned index, Identifier name)
Remove the attribute 'name' from the result at 'index'.
Return the attribute that was erased, or nullptr if there was no attribute with such name.
Definition at line 785 of file FunctionSupport.h.
References mlir::NamedAttrList::erase(), mlir::Attribute::getContext(), mlir::NamedAttrList::getDictionary(), and mlir::function_like_impl::getResultAttrDict().
rend()
template<typename ConcreteType > reverse_iterator mlir::OpTrait::FunctionLike< ConcreteType >::rend () inline
Definition at line 174 of file FunctionSupport.h.
setAllArgAttrs() [1/3]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setAllArgAttrs (ArrayRef< DictionaryAttr > attributes) inline
Definition at line 423 of file FunctionSupport.h.
References mlir::function_like_impl::setAllArgAttrDicts().
setAllArgAttrs() [2/3]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setAllArgAttrs (ArrayRef< Attribute > attributes) inline
Definition at line 427 of file FunctionSupport.h.
References mlir::function_like_impl::setAllArgAttrDicts().
setAllArgAttrs() [3/3]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setAllArgAttrs (ArrayAttr attributes) inline
Definition at line 431 of file FunctionSupport.h.
References mlir::function_like_impl::getArgDictAttrName(), and value.
setAllResultAttrs() [1/3]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setAllResultAttrs (ArrayRef< DictionaryAttr > attributes) inline
Definition at line 512 of file FunctionSupport.h.
References mlir::function_like_impl::setAllResultAttrDicts().
setAllResultAttrs() [2/3]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setAllResultAttrs (ArrayRef< Attribute > attributes) inline
Definition at line 516 of file FunctionSupport.h.
References mlir::function_like_impl::setAllResultAttrDicts().
setAllResultAttrs() [3/3]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setAllResultAttrs (ArrayAttr attributes) inline
Definition at line 520 of file FunctionSupport.h.
References mlir::function_like_impl::getResultDictAttrName().
setArgAttr() [1/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr (unsigned index, Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 721 of file FunctionSupport.h.
References mlir::function_like_impl::getArgAttrDict(), mlir::Attribute::getContext(), mlir::NamedAttrList::getDictionary(), and mlir::NamedAttrList::set().
setArgAttr() [2/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr (unsigned index, StringRef name, Attribute value) inline
Definition at line 440 of file FunctionSupport.h.
References mlir::Identifier::get().
setArgAttrs() [1/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs (unsigned index, ArrayRef< NamedAttribute > attributes)
Set the attributes held by the argument at 'index'.
Definition at line 700 of file FunctionSupport.h.
References mlir::function_like_impl::getArgDictAttrName(), mlir::Operation::getContext(), and mlir::function_like_impl::detail::setArgResAttrDict().
setArgAttrs() [2/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs (unsigned index, DictionaryAttr attributes)
Set the attributes held by the argument at 'index'.
attributes may be null, in which case any existing argument attributes are removed.
Definition at line 710 of file FunctionSupport.h.
References mlir::function_like_impl::getArgDictAttrName(), mlir::Operation::getContext(), and mlir::function_like_impl::detail::setArgResAttrDict().
setResultAttr() [1/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr (unsigned index, Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 773 of file FunctionSupport.h.
References mlir::Attribute::getContext(), mlir::NamedAttrList::getDictionary(), mlir::function_like_impl::getResultAttrDict(), and mlir::NamedAttrList::set().
setResultAttr() [2/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr (unsigned index, StringRef name, Attribute value) inline
Definition at line 529 of file FunctionSupport.h.
References mlir::Identifier::get().
setResultAttrs() [1/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs (unsigned index, ArrayRef< NamedAttribute > attributes)
Set the attributes held by the result at 'index'.
Definition at line 751 of file FunctionSupport.h.
References mlir::Operation::getContext(), mlir::function_like_impl::getResultDictAttrName(), and mlir::function_like_impl::detail::setArgResAttrDict().
setResultAttrs() [2/2]
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs (unsigned index, DictionaryAttr attributes)
Set the attributes held by the result at 'index'.
attributes may be null, in which case any existing argument attributes are removed.
Definition at line 761 of file FunctionSupport.h.
References mlir::Operation::getContext(), mlir::function_like_impl::getResultDictAttrName(), and mlir::function_like_impl::detail::setArgResAttrDict().
setType()
template<typename ConcreteType > void mlir::OpTrait::FunctionLike< ConcreteType >::setType (FunctionType newType)
Change the type of this function in place.
This is an extremely dangerous operation and it is up to the caller to ensure that this is legal for this function, and to restore invariants:
the entry block args must be updated to match the function params.
the argument/result attributes may need an update: if the new type has less parameters we drop the extra attributes, if there are more parameters they won't have any attributes.
Note that the concrete class must define a method with the same name to hide this one if the concrete class does not use FunctionType for the function type under the hood.
Definition at line 690 of file FunctionSupport.h.
References mlir::function_like_impl::setFunctionType().
verifyBody()
template<typename ConcreteType > LogicalResult mlir::OpTrait::FunctionLike< ConcreteType >::verifyBody ()
Hook for concrete ops to verify the contents of the body.
Default verifier checks that if the entry block exists, it has the same number of arguments as the function-like operation.
Called as a part of trait verification, after type verification and ensuring that a region exists.
Definition at line 565 of file FunctionSupport.h.
References mlir::success().
verifyTrait()
template<typename ConcreteType > LogicalResult mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait (Operation * op) static
Verify that all of the argument attributes are dialect attributes.
Definition at line 580 of file FunctionSupport.h.
References mlir::failed(), mlir::failure(), mlir::function_like_impl::getArgDictAttrName(), mlir::Operation::getNumRegions(), mlir::function_like_impl::getResultDictAttrName(), mlir::function_like_impl::getTypeAttrName(), and op.
verifyType()
template<typename ConcreteType > LogicalResult mlir::OpTrait::FunctionLike< ConcreteType >::verifyType () inline protected
Hook for concrete classes to verify that the type attribute respects op-specific invariants.
Default implementation always succeeds.
Definition at line 559 of file FunctionSupport.h.
References mlir::success().
The documentation for this class was generated from the following file:
include/mlir/IR/FunctionSupport.h