MLIR: mlir::Operation Class Reference
mlir::Operation Class Reference final
Operation is the basic unit of execution within MLIR.
#include "mlir/IR/Operation.h"
Classes
class CloneOptions
Class encompassing various options related to cloning an operation.
class dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
Public Types
using operand_range = OperandRange
using operand_iterator = operand_range::iterator
using operand_type_iterator = operand_range::type_iterator
using operand_type_range = operand_range::type_range
using result_range = ResultRange
Support result iteration.
using result_iterator = result_range::iterator
using result_type_iterator = result_range::type_iterator
Support result type iteration.
using result_type_range = result_range::type_range
using dialect_attr_range = iterator_range<dialect_attr_iterator>
using succ_iterator = SuccessorRange::iterator
using use_iterator = result_range::use_iterator
using use_range = result_range::use_range
using user_iterator = ValueUserIterator<use_iterator, OpOperand>
using user_range = iterator_range<user_iterator>
Public Member Functions
OperationName getName ()
The name of an operation is the key identifier for it.
std::optional< RegisteredOperationName > getRegisteredInfo ()
If this operation has a registered operation description, return it.
bool isRegistered ()
Returns true if this operation has a registered operation description, otherwise false.
void erase ()
Remove this operation from its parent block and delete it.
void remove ()
Remove the operation from its parent block, but don't delete it.
Operation * clone (IRMapping &mapper, CloneOptions options=CloneOptions::all())
Create a deep copy of this operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (CloneOptions options=CloneOptions::all())
Operation * cloneWithoutRegions (IRMapping &mapper)
Create a partial copy of this operation without traversing into attached regions.
Operation * cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Block * getBlock ()
Returns the operation block that contains this operation.
MLIRContext * getContext ()
Return the context this operation is associated with.
Dialect * getDialect ()
Return the dialect this operation is associated with, or nullptr if the associated dialect is not loaded.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
Set the source location the operation was defined or derived from.
Region * getParentRegion ()
Returns the region to which the instruction belongs.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy>
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
template<template< typename T > class Trait>
Operation * getParentWithTrait ()
Returns the closest surrounding parent operation with trait Trait.
bool isProperAncestor (Operation *other)
Return true if this operation is a proper ancestor of the other operation.
bool isAncestor (Operation *other)
Return true if this operation is an ancestor of the other operation.
void replaceUsesOfWith (Value from, Value to)
Replace any uses of 'from' with 'to' within this operation.
template<typename ValuesT>
void replaceAllUsesWith (ValuesT &&values)
Replace all uses of results of this operation with the provided 'values'.
template<typename ValuesT>
void replaceUsesWithIf (ValuesT &&values, function_ref< bool(OpOperand &)> shouldReplace)
Replace uses of results of this operation with the provided values if the given callback returns true.
void destroy ()
Destroys this operation and its subclass data.
void dropAllReferences ()
This drops all operand uses from this operation, which is an essential step in breaking cyclic dependencies between references when they are to be deleted.
void dropAllDefinedValueUses ()
Drop uses of all values defined by this operation or its nested regions.
void moveBefore (Operation *existingOp)
Unlink this operation from its current block and insert it right before existingOp which may be in the same or another block in the same function.
void moveBefore (Block *block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right before iterator in the specified block.
void moveAfter (Operation *existingOp)
Unlink this operation from its current block and insert it right after existingOp which may be in the same or another block in the same function.
void moveAfter (Block *block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right after iterator in the specified block.
bool isBeforeInBlock (Operation *other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
void print (raw_ostream &os, const OpPrintingFlags &flags={})
void print (raw_ostream &os, AsmState &state)
void dump ()
LLVM_DUMP_METHOD void dumpPretty ()
void setOperands (ValueRange operands)
Replace the current operands of this operation with the ones provided in 'operands'.
void setOperands (unsigned start, unsigned length, ValueRange operands)
Replace the operands beginning at 'start' and ending at 'start' + 'length' with the ones provided in 'operands'.
void insertOperands (unsigned index, ValueRange operands)
Insert the given operands into the operand list at the given 'index'.
unsigned getNumOperands ()
Value getOperand (unsigned idx)
void setOperand (unsigned idx, Value value)
void eraseOperand (unsigned idx)
Erase the operand at position idx.
void eraseOperands (unsigned idx, unsigned length=1)
Erase the operands starting at position idx and ending at position 'idx'+'length'.
void eraseOperands (const BitVector &eraseIndices)
Erases the operands that have their corresponding bit set in eraseIndices and removes them from the operand list.
operand_iterator operand_begin ()
operand_iterator operand_end ()
operand_range getOperands ()
Returns an iterator on the underlying Value's.
MutableArrayRef< OpOperand > getOpOperands ()
OpOperand & getOpOperand (unsigned idx)
operand_type_iterator operand_type_begin ()
operand_type_iterator operand_type_end ()
operand_type_range getOperandTypes ()
unsigned getNumResults ()
Return the number of results held by this operation.
OpResult getResult (unsigned idx)
Get the 'idx'th result of this operation.
result_iterator result_begin ()
result_iterator result_end ()
result_range getResults ()
result_range getOpResults ()
OpResult getOpResult (unsigned idx)
result_type_iterator result_type_begin ()
result_type_iterator result_type_end ()
result_type_range getResultTypes ()
std::optional< Attribute > getInherentAttr (StringRef name)
Access an inherent attribute by name: returns an empty optional if there is no inherent attribute with this name.
void setInherentAttr (StringAttr name, Attribute value)
Set an inherent attribute by name.
Attribute getDiscardableAttr (StringRef name)
Access a discardable attribute by name, returns a null Attribute if the discardable attribute does not exist.
Attribute getDiscardableAttr (StringAttr name)
Access a discardable attribute by name, returns a null Attribute if the discardable attribute does not exist.
void setDiscardableAttr (StringAttr name, Attribute value)
Set a discardable attribute by name.
void setDiscardableAttr (StringRef name, Attribute value)
Attribute removeDiscardableAttr (StringAttr name)
Remove the discardable attribute with the specified name if it exists.
Attribute removeDiscardableAttr (StringRef name)
auto getDiscardableAttrs ()
Return a range of all of discardable attributes on this operation.
DictionaryAttr getDiscardableAttrDictionary ()
Return all of the discardable attributes on this operation as a DictionaryAttr.
DictionaryAttr getRawDictionaryAttrs ()
Return all attributes that are not stored as properties.
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
DictionaryAttr getAttrDictionary ()
Return all of the attributes on this operation as a DictionaryAttr.
void setAttrs (DictionaryAttr newAttrs)
Set the attributes from a dictionary on this operation.
void setAttrs (ArrayRef< NamedAttribute > newAttrs)
void setDiscardableAttrs (DictionaryAttr newAttrs)
Set the discardable attribute dictionary on this operation.
void setDiscardableAttrs (ArrayRef< NamedAttribute > newAttrs)
Attribute getAttr (StringAttr name)
Return the specified attribute if present, null otherwise.
Attribute getAttr (StringRef name)
template<typename AttrClass>
AttrClass getAttrOfType (StringAttr name)
template<typename AttrClass>
AttrClass getAttrOfType (StringRef name)
bool hasAttr (StringAttr name)
Return true if the operation has an attribute with the provided name, false otherwise.
bool hasAttr (StringRef name)
template<typename AttrClass, typename NameT>
bool hasAttrOfType (NameT &&name)
void setAttr (StringAttr name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
Attribute removeAttr (StringAttr name)
Remove the attribute with the specified name if it exists.
Attribute removeAttr (StringRef name)
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
template<typename DialectAttrT>
void setDialectAttrs (DialectAttrT &&dialectAttrs)
Set the dialect attributes for this operation, and preserve all inherent.
void populateDefaultAttrs ()
Sets default attributes on unset attributes.
unsigned getNumRegions ()
Returns the number of regions held by this operation.
MutableArrayRef< Region > getRegions ()
Returns the regions held by this operation.
Region & getRegion (unsigned index)
Returns the region held by this operation at position 'index'.
MutableArrayRef< BlockOperand > getBlockOperands ()
succ_iterator successor_begin ()
succ_iterator successor_end ()
SuccessorRange getSuccessors ()
bool hasSuccessors ()
unsigned getNumSuccessors ()
Block * getSuccessor (unsigned index)
void setSuccessor (Block *block, unsigned index)
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
Attempt to fold this operation with the specified constant operand values.
LogicalResult fold (SmallVectorImpl< OpFoldResult > &results)
Attempt to fold this operation.
template<typename InterfaceT>
bool hasPromiseOrImplementsInterface () const
Returns true if InterfaceT has been promised by the dialect or implemented.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the operation was registered with a particular trait, e.g.
template<template< typename T > class Trait>
bool mightHaveTrait ()
Returns true if the operation might have the provided trait.
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==1, RetT > walk (FnT &&callback)
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
template<typename FnT, typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==2, RetT > walk (FnT &&callback)
Generic walker with a stage aware callback.
void dropAllUses ()
Drop all uses of results of this operation.
use_iterator use_begin ()
use_iterator use_end ()
use_range getUses ()
Returns a range of all uses, which is useful for iterating over all uses.
bool hasOneUse ()
Returns true if this operation has exactly one use.
bool use_empty ()
Returns true if this operation has no uses.
bool isUsedOutsideOfBlock (Block *block)
Returns true if the results of this operation are used outside of the given block.
user_iterator user_begin ()
user_iterator user_end ()
user_range getUsers ()
Returns a range of all users.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
int getPropertiesStorageSize () const
Returns the properties storage size.
OpaqueProperties getPropertiesStorage ()
Returns the properties storage.
OpaqueProperties getPropertiesStorage () const
OpaqueProperties getPropertiesStorageUnsafe ()
Returns the properties storage without checking whether properties are present.
Attribute getPropertiesAsAttribute ()
Return the properties converted to an attribute.
LogicalResult setPropertiesFromAttribute (Attribute attr, function_ref< InFlightDiagnostic()> emitError)
Set the properties from the provided attribute.
void copyProperties (OpaqueProperties rhs)
Copy properties from an existing other properties object.
llvm::hash_code hashProperties ()
Compute a hash for the op properties (if any).
Static Public Member Functions
static Operation * create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList &&attributes, OpaqueProperties properties, BlockRange successors, unsigned numRegions)
Create a new Operation with the specific fields.
static Operation * create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, DictionaryAttr attributes, OpaqueProperties properties, BlockRange successors, unsigned numRegions)
Create a new Operation with the specific fields.
static Operation * create (const OperationState &state)
Create a new Operation from the fields stored in state.
static Operation * create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList &&attributes, OpaqueProperties properties, BlockRange successors={}, RegionRange regions={})
Create a new Operation with the specific fields.
Friends
struct llvm::ilist_traits< Operation >
class Block
class Value
class llvm::ilist_node_with_parent< Operation, Block >
Detailed Description
Operation is the basic unit of execution within MLIR.
The following documentations are recommended to understand this class:
https://mlir.llvm.org/docs/LangRef/#operations
https://mlir.llvm.org/docs/Tutorials/UnderstandingTheIRStructure/
An Operation is defined first by its name, which is a unique string. The name is interpreted so that if it contains a '.' character, the part before is the dialect name this operation belongs to, and everything that follows is this operation name within the dialect.
An Operation defines zero or more SSA Value that we refer to as the Operation results. This array of Value is actually stored in memory before the Operation itself in reverse order. That is for an Operation with 3 results we allocate the following memory layout:
[Result2, Result1, Result0, Operation] ^ this is where Operation* pointer points to.
A consequence of this is that this class must be heap allocated, which is handled by the various create methods. Each result contains:
one pointer to the first use (see OpOperand)
the type of the SSA Value this result defines.
the index for this result in the array. The results are defined as subclass of ValueImpl, and more precisely as the only two subclasses of OpResultImpl: InlineOpResult and OutOfLineOpResult. The former is used for the first 5 results and the latter for the subsequent ones. They differ in how they store their index: the first 5 results only need 3 bits and thus are packed with the Type pointer, while the subsequent one have an extra unsigned value and thus need more space.
An Operation also has zero or more operands: these are uses of SSA Value, which can be the results of other operations or Block arguments. Each of these uses is an instance of OpOperand. This optional array is initially tail allocated with the operation class itself, but can be dynamically moved out-of-line in a dynamic allocation as needed.
An Operation may optionally contain one or multiple Regions, stored in a tail allocated array. Each Region is a list of Blocks. Each Block is itself a list of Operations. This structure is effectively forming a tree.
Some operations like branches also refer to other Block, in which case they would have an array of BlockOperand.
An Operation may optionally contain a "Properties" object: this is a pre-defined C++ object with a fixed size. This object is owned by the operation and deleted with the operation. It can be converted to an Attribute on demand, or loaded from an Attribute.
Finally an Operation also contain an optional DictionaryAttr, a Location, and a pointer to its parent Block (if any).
Definition at line 84 of file Operation.h.
Member Typedef Documentation
dialect_attr_range
using mlir::Operation::dialect_attr_range = iterator_range<dialect_attr_iterator>
Definition at line 634 of file Operation.h.
operand_iterator
using mlir::Operation::operand_iterator = operand_range::iterator
Definition at line 372 of file Operation.h.
operand_range
using mlir::Operation::operand_range = OperandRange
Definition at line 371 of file Operation.h.
operand_type_iterator
using mlir::Operation::operand_type_iterator = operand_range::type_iterator
Definition at line 393 of file Operation.h.
operand_type_range
using mlir::Operation::operand_type_range = operand_range::type_range
Definition at line 394 of file Operation.h.
result_iterator
using mlir::Operation::result_iterator = result_range::iterator
Definition at line 411 of file Operation.h.
result_range
using mlir::Operation::result_range = ResultRange
Support result iteration.
Definition at line 410 of file Operation.h.
result_type_iterator
using mlir::Operation::result_type_iterator = result_range::type_iterator
Support result type iteration.
Definition at line 424 of file Operation.h.
result_type_range
using mlir::Operation::result_type_range = result_range::type_range
Definition at line 425 of file Operation.h.
succ_iterator
using mlir::Operation::succ_iterator = SuccessorRange::iterator
Definition at line 700 of file Operation.h.
use_iterator
using mlir::Operation::use_iterator = result_range::use_iterator
Definition at line 839 of file Operation.h.
use_range
using mlir::Operation::use_range = result_range::use_range
Definition at line 840 of file Operation.h.
user_iterator
using mlir::Operation::user_iterator = ValueUserIterator<use_iterator, OpOperand>
Definition at line 866 of file Operation.h.
user_range
using mlir::Operation::user_range = iterator_range<user_iterator>
Definition at line 867 of file Operation.h.
Member Function Documentation
clone() [1/2]
Operation * Operation::clone (CloneOptions options = CloneOptions::all())
Definition at line 748 of file Operation.cpp.
References clone(), and options.
clone() [2/2]
Operation * Operation::clone (IRMapping & mapper, CloneOptions options = CloneOptions::all())
Create a deep copy of this operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Replaces references to cloned sub-operations to the corresponding operation that is copied, and adds those mappings to the map. Optionally, one may configure what parts of the operation to clone using the options parameter.
Calling this method from multiple threads is generally safe if through the process of cloning no new uses of 'Value's from outside the operation are created. Cloning an isolated-from-above operation with no operands, such as top level function operations, is therefore always safe. Using the mapper, it is possible to avoid adding uses to outside operands by remapping them to 'Value's owned by the caller thread.
Replaces references to cloned sub-operations to the corresponding operation that is copied, and adds those mappings to the map.
Definition at line 714 of file Operation.cpp.
References Block, mlir::Region::cloneInto(), create(), getLoc(), getName(), getNumOperands(), getNumRegions(), getNumResults(), getNumSuccessors(), getOperands(), getPropertiesStorage(), getRegion(), getResult(), getResultTypes(), getSuccessors(), mlir::IRMapping::lookupOrDefault(), mlir::IRMapping::map(), and options.
Referenced by mlir::OpBuilder::clone(), clone(), cloneWithoutRegions(), generateUnrolledLoop(), and mlir::generateUnrolledLoop().
cloneWithoutRegions() [1/2]
Operation * Operation::cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
The new operation will have the same number of regions as the original one, but they will be left empty.
Definition at line 704 of file Operation.cpp.
References cloneWithoutRegions().
Referenced by cloneWithoutRegions().
cloneWithoutRegions() [2/2]
Operation * Operation::cloneWithoutRegions (IRMapping & mapper)
Create a partial copy of this operation without traversing into attached regions.
Create a deep copy of this operation but keep the operation regions empty.
The new operation will have the same number of regions as the original one, but they will be left empty. Operands are remapped using mapper (if present), and mapper is updated to contain the results.
Operands are remapped using mapper (if present), and mapper is updated to contain the results. The mapResults flag specifies whether the results of the cloned operation should be added to the map.
Definition at line 700 of file Operation.cpp.
References mlir::Operation::CloneOptions::all(), and clone().
Referenced by mlir::OpBuilder::cloneWithoutRegions(), and mlir::OpBuilder::cloneWithoutRegions().
copyProperties()
void Operation::copyProperties (OpaqueProperties rhs)
Copy properties from an existing other properties object.
The two objects must be the same type.
Definition at line 366 of file Operation.cpp.
References getPropertiesStorage(), and rhs.
create() [1/4]
Operation * Operation::create (const OperationState & state) static
Create a new Operation from the fields stored in state.
Create a new Operation from operation state.
Definition at line 34 of file Operation.cpp.
References mlir::OperationState::attributes, create(), mlir::OperationState::getContext(), mlir::NamedAttrList::getDictionary(), mlir::OperationState::location, mlir::OperationState::name, mlir::OperationState::operands, mlir::OperationState::propertiesAttr, mlir::OperationState::regions, result, setPropertiesFromAttribute(), mlir::OperationState::successors, and mlir::OperationState::types.
create() [2/4]
Operation * Operation::create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, DictionaryAttr attributes, OpaqueProperties properties, BlockRange successors, unsigned numRegions) static
Create a new Operation with the specific fields.
Overload of create that takes an existing DictionaryAttr to avoid unnecessarily uniquing a list of attributes.
This constructor uses an existing attribute dictionary to avoid uniquing a list of attributes.
Definition at line 82 of file Operation.cpp.
References getBlockOperands(), getRegion(), mightHaveTrait(), and setAttrs().
create() [3/4]
Operation * Operation::create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList && attributes, OpaqueProperties properties, BlockRange successors, unsigned numRegions) static
Create a new Operation with the specific fields.
This constructor populates the provided attribute list with default attributes if necessary.
Definition at line 67 of file Operation.cpp.
References create(), and populateDefaultAttrs().
Referenced by clone(), mlir::OpBuilder::create(), create(), create(), create(), mlir::createGpuAsyncRegionPass(), mlir::OpBuilder::createOrFold(), mlirOperationCreate(), and mlir::spirv::Deserializer::processOpWithoutGrammarAttr().
create() [4/4]
Operation * Operation::create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList && attributes, OpaqueProperties properties, BlockRange successors = {}, RegionRange regions = {}) static
Create a new Operation with the specific fields.
Definition at line 51 of file Operation.cpp.
References create(), getRegion(), and mlir::Region::takeBody().
destroy()
void Operation::destroy ()
Destroys this operation and its subclass data.
Destroy this operation or one of its subclasses.
Definition at line 208 of file Operation.cpp.
Referenced by llvm::ilist_traits<::mlir::Operation >::deleteNode(), and erase().
dialect_attr_begin()
dialect_attr_iterator mlir::Operation::dialect_attr_begin () inline
Definition at line 642 of file Operation.h.
References getAttrs().
dialect_attr_end()
dialect_attr_iterator mlir::Operation::dialect_attr_end () inline
Definition at line 646 of file Operation.h.
References getAttrs().
dropAllDefinedValueUses()
void Operation::dropAllDefinedValueUses ()
Drop uses of all values defined by this operation or its nested regions.
This drops all uses of any values defined by this operation or its nested regions, wherever they are located.
Definition at line 594 of file Operation.cpp.
References dropAllUses(), and getRegions().
dropAllReferences()
void Operation::dropAllReferences ()
This drops all operand uses from this operation, which is an essential step in breaking cyclic dependencies between references when they are to be deleted.
This drops all operand uses from this operation, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
Definition at line 581 of file Operation.cpp.
References getBlockOperands(), getOpOperands(), and getRegions().
Referenced by mlir::Block::dropAllReferences(), and mlir::BytecodeReader::Impl::finalize().
dropAllUses()
void mlir::Operation::dropAllUses () inline
Drop all uses of results of this operation.
Definition at line 834 of file Operation.h.
References getOpResults(), and result.
Referenced by dropAllDefinedValueUses(), and mlir::detail::ConversionPatternRewriterImpl::SingleEraseRewriter::eraseOp().
dump()
void Operation::dump ()
Definition at line 4133 of file AsmPrinter.cpp.
References print().
Referenced by mlir::affine::checkMemrefAccessDependence().
dumpPretty()
void Operation::dumpPretty ()
Definition at line 4138 of file AsmPrinter.cpp.
References print().
emitError()
InFlightDiagnostic Operation::emitError (const Twine & message = {})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 268 of file Operation.cpp.
References diag(), mlir::emitError(), getContext(), and getLoc().
Referenced by mlir::NVVM::SerializeGPUModuleBase::appendStandardLibs(), mlir::ROCDL::SerializeGPUModuleBase::appendStandardLibs(), applyTilingToAll(), mlir::bufferization::bufferizeOp(), checkAffineLoopNestMappableImpl(), checkAndUpdateCapabilityRequirements(), checkAndUpdateExtensionRequirements(), checkGlobalXtorData(), checkImplementationStatus(), mlir::linalg::commonVerifierPackAndUnPackOp(), mlir::ROCDL::SerializeGPUModuleBase::compileToBinary(), mlir::affine::MemRefRegion::compute(), mlir::OperationConverter::convert(), convertHostOrTargetOperation(), convertOmpThreadprivate(), mlir::convertVectorToNVVMCompatibleMMASync(), diagnoseInvalidOperandDominance(), emit(), emitOpError(), findPayloadRoot(), mlir::transform::detail::findTransformEntryPoint(), generateLocationsFromIR(), getGridAndVerify(), getMemoryFootprintBytes(), mlir::LLVM::ModuleToObject::getOrCreateTargetMachine(), mlir::spirv::getPushConstantValue(), getSegmentSizes(), getSegmentSizesFromAttr(), mlir::nvgpu::getWarpMatrixInfo(), handleError(), inferSideEffectAnnotations(), mlir::affine::insertBackwardComputationSlice(), irdlOpVerifier(), isValidName(), mlir::LLVM::ModuleToObject::linkFiles(), mlir::LLVM::ModuleToObject::loadBitcodeFile(), mlir::LLVM::ModuleToObject::loadBitcodeFilesFromList(), mlirTransformApplyNamedSequence(), mlir::ROCDL::SerializeGPUModuleBase::moduleToObjectImpl(), mlir::LLVM::ModuleToObject::optimizeModule(), mlir::shard::partitionOperation(), prepareLLVMModule(), printFunctionBody(), produceSliceErrorMsg(), mlir::dlti::query(), mlir::registerIRDLToCppTranslation(), mlir::LLVM::ModuleToObject::run(), TargetToTargetFeaturesPass::runOnOperation(), setPropertiesFromAttribute(), mlir::linalg::tileReductionUsingForall(), mlir::detail::verifyBranchSuccessorOperands(), verifyComdat(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::wasmssa::detail::verifyConstantExpressionInterface(), mlir::linalg::detail::verifyContractionInterface(), mlir::linalg::detail::verifyConvolutionInterface(), mlir::detail::verifyDataLayoutOp(), mlir::linalg::detail::verifyFillInterface(), verifyImageOperands(), mlir::detail::verifyInParallelOpInterface(), mlir::wasmssa::detail::verifyLabelLevelInterface(), mlir::verifyListOfOperandsOrIntegers(), verifyMBarrierArriveLikeOp(), mlir::spirv::verifyMemorySemantics(), mlir::detail::verifyMemorySpaceCastOpInterface(), verifyMmaSyncOp(), verifyPackUnPack(), verifyReductionVarList(), mlir::detail::verifyShapedDimOpInterface(), verifyShiftOp(), verifySparsifierGetterSetter(), mlir::detail::verifySymbolTable(), verifyTerminatorSuccessors(), verifyTmaDescriptorWithMemref(), mlir::OpTrait::AtMostOneChildOf< ChildOps >::Impl< ConcreteType >::verifyTrait(), mlir::transform::AtMostOneOpMatcherOpTrait< OpTy >::verifyTrait(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::NavigationTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::SingleValueMatcherOpTrait< OpTy >::verifyTrait(), mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait(), mlir::transform::detail::verifyTransformOpInterface(), verifyWeights(), and walkReferenceCountedValues().
emitOpError()
InFlightDiagnostic Operation::emitOpError (const Twine & message = {})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
Definition at line 668 of file Operation.cpp.
References emitError(), and getName().
Referenced by amendOperationImpl(), mlir::bufferization::bufferizeBlockSignature(), mlir::bufferization::bufferizeOp(), checkFoldResultTypes(), TosaProfileCompliance::checkInvalid(), checkPreBufferizationAssumptions(), checkPrivateOperands(), TosaProfileCompliance::checkProfileOrExtension(), checkSymbolIsTypeOrAttribute(), checkTransformationPreconditions(), mlir::arith::impl::ArithEmulateUnsupportedFloatsBase< DerivedT >::classof(), mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >::clonePass(), mlir::convertVectorToNVVMCompatibleMMASync(), mlir::ControlFlowToSCFTransformation::createStructuredBranchRegionOp(), mlir::shard::detail::defaultGetShardingOption(), doVerifyRoundTrip(), errorIfTypeOrShapeMismatch(), errorIfTypeOrShapeMismatch(), mlir::bufferization::OpWithUnstructuredControlFlowBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp >::getBufferType(), irdlOpVerifier(), irdlRegionVerifier(), isArrayOf(), printFunctionBody(), processOperands(), ProfileInfoDepot::ProfileInfoDepot(), verifyAlignedClause(), verifyAndGetTerminator(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::OpTrait::impl::verifyAtLeastNResults(), mlir::OpTrait::impl::verifyAtLeastNSuccessors(), mlir::spirv::verifyAtomicUpdateOp(), verifyAttributions(), mlir::impl::verifyCastInterfaceOp(), mlir::spirv::verifyCastOp(), verifyCollapsedShape(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), verifyConstantRangeAttr(), verifyConvertF32x2ToFP16x2Op(), mlir::spirv::verifyCoopMatrixAccess(), verifyCopyprivateVarList(), verifyDependVarList(), mlir::LLVM::detail::verifyDereferenceableOpInterface(), mlir::detail::verifyDestinationStyleOpInterface(), verifyDimIsPowerOfTwo(), verifyDistributedType(), mlir::OpTrait::impl::verifyElementwise(), mlir::linalg::detail::verifyFillInterface(), verifyGatherOrScatterDims(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), verifyHasBindingUse(), mlir::detail::verifyInferredResultTypes(), verifyInitializationAttribute(), verifyInitLikeSingleArgRegion(), mlir::spirv::verifyIntegerDotProduct(), mlir::OpTrait::impl::verifyIsTerminator(), verifyKnownLaunchSizeAttr(), mlir::detail::verifyLoopLikeOpInterface(), verifyMapInfoDefinedArgs(), verifyMmaSyncOp(), verifyMultShape(), verifyNames(), verifyNontemporalClause(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyNSuccessors(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneRegion(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyOneSuccessor(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), verifyOrderedParent(), mlir::transform::detail::verifyParamProducerTransformOpTrait(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), verifyReductionVarList(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), verifyRescaleValueAndZpTypes(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultRank(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), mlir::linalg::detail::verifyStructuredOpInterface(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), mlir::detail::verifySymbol(), verifySymbolAttrUse(), mlir::detail::verifySymbolTable(), verifySynchronizationHint(), verifyTileSize(), mlir::OpTrait::tosa::verifyTosaResolvableShapeOperands(), mlir::OpTrait::tosa::verifyTosaShapeOperator(), mlir::OpTrait::tosa::verifyTosaShapeOperatorWithSameRanks(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), mlir::OpTrait::tosa::MulOperandsAndResultElementType< ConcreteType >::verifyTrait(), mlir::transform::verifyTransformMatchDimsOp(), mlir::OpTrait::impl::verifyValueSizeAttr(), mlir::OpTrait::impl::verifyZeroOperands(), mlir::OpTrait::impl::verifyZeroRegions(), mlir::OpTrait::impl::verifyZeroResults(), mlir::OpTrait::impl::verifyZeroSuccessors(), mlir::smt::SMTOpVisitor< ExpressionVisitor, LogicalResult, VisitorInfo & >::visitInvalidSMTOp(), and visitOp().
emitRemark()
InFlightDiagnostic Operation::emitRemark (const Twine & message = {})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 289 of file Operation.cpp.
References diag(), mlir::emitRemark(), getContext(), and getLoc().
Referenced by mlir::ROCDL::SerializeGPUModuleBase::appendStandardLibs(), and emitRemarkForBlock().
emitWarning()
InFlightDiagnostic Operation::emitWarning (const Twine & message = {})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 280 of file Operation.cpp.
References diag(), mlir::emitWarning(), getContext(), and getLoc().
Referenced by checkImplementationStatus(), getMemoryFootprintBytes(), setProfilingAttr(), and updateOp().
erase()
void Operation::erase ()
Remove this operation from its parent block and delete it.
Remove this operation (and its descendants) from its Block and delete all of them.
Definition at line 534 of file Operation.cpp.
References destroy(), and getBlock().
Referenced by mlir::emitc::createExpression(), mlir::createGpuAsyncRegionPass(), mlir::OpBuilder::createOrFold(), mlir::SymbolTable::erase(), mlir::RewriterBase::eraseOp(), mlir::BytecodeReader::Impl::finalize(), mlir::query::MatchQuery::run(), teamsReductionContainedInDistribute(), transformCyclesToSCFLoops(), and transformToStructuredCFBranches().
eraseOperand()
void mlir::Operation::eraseOperand (unsigned idx) inline
Erase the operand at position idx.
Definition at line 356 of file Operation.h.
References eraseOperands().
eraseOperands() [1/2]
void mlir::Operation::eraseOperands (const BitVector & eraseIndices) inline
Erases the operands that have their corresponding bit set in eraseIndices and removes them from the operand list.
Definition at line 366 of file Operation.h.
eraseOperands() [2/2]
void mlir::Operation::eraseOperands (unsigned idx, unsigned length = 1) inline
Erase the operands starting at position idx and ending at position 'idx'+'length'.
Definition at line 360 of file Operation.h.
Referenced by eraseOperand().
fold() [1/2]
LogicalResult Operation::fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > & results)
Attempt to fold this operation with the specified constant operand values.
Attempt to fold this operation using the Op's registered foldHook.
the elements in "operands" will correspond directly to the operands of the operation, but may be null if non-constant.
If folding was successful, this function returns "success".
If this operation was modified in-place (but not folded away), results is empty.
Otherwise, results is filled with the folded results. If folding was unsuccessful, this function returns "failure".
Definition at line 629 of file Operation.cpp.
References checkFoldResultTypes(), mlir::DialectFoldInterface::fold(), getDialect(), and success().
Referenced by fold(), mlir::detail::constant_op_binder< AttrT >::match(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
fold() [2/2]
LogicalResult Operation::fold (SmallVectorImpl< OpFoldResult > & results)
Attempt to fold this operation.
If folding was successful, this function returns "success".
If this operation was modified in-place (but not folded away), results is empty.
Otherwise, results is filled with the folded results. If folding was unsuccessful, this function returns "failure".
Definition at line 657 of file Operation.cpp.
References fold(), getNumOperands(), getOperand(), mlir::m_Constant(), and mlir::matchPattern().
getAttr() [1/2]
Attribute mlir::Operation::getAttr (StringAttr name) inline
Return the specified attribute if present, null otherwise.
These methods are expensive: if the dictionary only contains discardable attributes, getDiscardableAttr is more efficient.
Definition at line 534 of file Operation.h.
References getInherentAttr(), and getPropertiesStorageSize().
Referenced by mlir::linalg::BatchMatmulTransposeAOp::classof(), mlir::linalg::BatchMatmulTransposeBOp::classof(), mlir::linalg::MatmulTransposeAOp::classof(), mlir::linalg::MatmulTransposeBOp::classof(), mlir::LLVM::detail::createIntrinsicCall(), createLinalgBodyCalculationForElementwiseOp(), getAttrOfType(), getAttrOfType(), mlir::spirv::getIntegerDotProductCapabilities(), getSegmentSizesFromAttr(), lookupSymbolInImpl(), setInPlaceOpOperand(), mlir::spirv::verifyIntegerDotProduct(), verifyNamedSequenceOp(), and mlir::detail::verifySymbol().
getAttr() [2/2]
Attribute mlir::Operation::getAttr (StringRef name) inline
Definition at line 541 of file Operation.h.
References getInherentAttr(), and getPropertiesStorageSize().
getAttrDictionary()
DictionaryAttr Operation::getAttrDictionary ()
Return all of the attributes on this operation as a DictionaryAttr.
Definition at line 296 of file Operation.cpp.
References getContext(), mlir::NamedAttrList::getDictionary(), getName(), getPropertiesStorageSize(), and mlir::OperationName::populateInherentAttrs().
Referenced by getAttrs(), mlir::LLVM::detail::intrinsicRewrite(), irdlOpVerifier(), populateDefaultAttrs(), mlir::detail::AttrTypeReplacerBase< Concrete >::replaceElementsIn(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and walkSymbolRefs().
getAttrOfType() [1/2]
template<typename AttrClass> AttrClass mlir::Operation::getAttrOfType (StringAttr name) inline
Definition at line 550 of file Operation.h.
References getAttr().
Referenced by convertOperationImpl(), createDimGetterFunctionCall(), executeGetOperandsResults(), findPayloadRoot(), mlir::impl::getDataLayoutSpec(), mlir::xegpu::getDistributeLayoutAttr(), mlir::xegpu::getDistributeLayoutAttr(), getNameIfSymbol(), getNameIfSymbol(), mlir::SymbolTable::getSymbolVisibility(), mlir::impl::getTargetSystemSpec(), hasAttrOfType(), mlir::spirv::lookupEntryPointABI(), mlir::spirv::lookupTargetEnv(), mlir::tosa::lookupTargetEnv(), mlir::detail::AttrOpBinder< AttrT >::match(), nvvmInferResultRanges(), printIR(), mlir::spirv::printVariableDecorations(), TargetToTargetFeaturesPass::runOnOperation(), updateVisibility(), mlir::spirv::verifyAtomicUpdateOp(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), mlir::detail::verifySymbol(), mlir::detail::verifySymbolTable(), and mlir::OpTrait::impl::verifyValueSizeAttr().
getAttrOfType() [2/2]
template<typename AttrClass> AttrClass mlir::Operation::getAttrOfType (StringRef name) inline
Definition at line 554 of file Operation.h.
References getAttr().
getAttrs()
ArrayRef< NamedAttribute > mlir::Operation::getAttrs () inline
Return all of the attributes on this operation.
Definition at line 512 of file Operation.h.
References getAttrDictionary().
Referenced by mlir::clone(), cloneOpWithOperandsAndTypes(), cloneOpWithOperandsAndTypes(), mlir::cloneWithoutRegions(), dialect_attr_begin(), dialect_attr_end(), mlir::linalg::generateLibraryCallName(), getClosestQueryable(), getDialectAttrs(), mlir::getPrunedAttributeList(), insertCasts(), isLegalOp(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), printArithmeticExtendedBinaryOp(), mlir::function_interface_impl::printFunctionAttributes(), printOneResultOp(), printShortForm(), mlir::spirv::printVariableDecorations(), propagateLoopAttrs(), scalarizeVectorOpHelper(), setDialectAttrs(), vectorizeOneOp(), and widenOp().
getBlock()
Block * mlir::Operation::getBlock () inline
Returns the operation block that contains this operation.
Definition at line 213 of file Operation.h.
References Block.
Referenced by llvm::ilist_traits<::mlir::Operation >::addNodeToList(), canMakeGroupOpUniform(), canRemoveSrcNodeAfterFusion(), canUseOpDominanceDueToBlocks(), checkAssumptionForFusingConsumer(), mlir::impl::GpuEliminateBarriersBase< DerivedT >::clonePass(), constructTiledLoopNest(), mlir::createGpuEliminateBarriers(), mlir::bufferization::createOwnershipBasedBufferDeallocationPass(), diagnoseInvalidOperandDominance(), erase(), mlir::Region::findAncestorBlockInRegion(), findAncestorIteratorInRegion(), findCapturedOmpOp(), mlir::affine::findInnermostCommonBlockInScope(), findInstPosition(), generateUnrolledLoop(), getCommonBlockInAffineScope(), getConsumerFromLoopUses(), getEffectsBefore(), getEffectsBeforeInBlock(), getFirstUserOfLoop(), getPhiIncomingBlock(), getPipelineStages(), mlir::DataFlowSolver::getProgramPointAfter(), mlir::DataFlowSolver::getProgramPointBefore(), getSameBlockUsers(), mlir::bufferization::BufferPlacementAllocs::getStartOperation(), happensBefore(), mlir::affine::hasNoInterveningEffect(), hoistAffineIfOp(), mlir::RewriterBase::inlineBlockBefore(), mlir::inlineRegion(), mlir::inlineRegion(), mlir::bufferization::deallocation_impl::insertDeallocOpForReturnLike(), mlir::OperationFolder::insertKnownConstant(), mlir::sparse_tensor::isAdmissibleBranchExp(), mlir::isLegalForBranchOpInterfaceTypeConversionPattern(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), isOpSibling(), isRegionOrCallableReturn(), mlir::Value::isUsedOutsideOfBlock(), lastNonTerminatorInRegion(), moveAfter(), moveBefore(), moveBefore(), mlir::RewriterBase::moveOpAfter(), mlir::RewriterBase::moveOpBefore(), mlir::RewriterBase::moveOpBefore(), mlir::moveOperationDependencies(), mlir::moveValueDefinitions(), mlir::OperationFolder::notifyRemoval(), mlir::dataflow::Executable::onUpdate(), performReplaceValue(), printIR(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::processOperation(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::processOperation(), mlir::DominanceInfo::properlyDominates(), mlir::PostDominanceInfo::properlyPostDominates(), remove(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), transformToReduceLoop(), mlir::OperationFolder::tryToFold(), mlir::OpTrait::impl::verifyIsTerminator(), mlir::wasmssa::detail::verifyLabelBranchingOpInterface(), verifyResultTypesAreInferrable(), and mlir::dataflow::DeadCodeAnalysis::visit().
getBlockOperands()
MutableArrayRef< BlockOperand > mlir::Operation::getBlockOperands () inline
Definition at line 695 of file Operation.h.
Referenced by create(), dropAllReferences(), mlir::BlockOperand::getOperandNumber(), getSuccessor(), setSuccessor(), and mlir::SuccessorRange::SuccessorRange().
getContext()
MLIRContext * mlir::Operation::getContext () inline
Return the context this operation is associated with.
Definition at line 216 of file Operation.h.
Referenced by mlir::gpu::addAsyncDependency(), annotateConflict(), annotateOpsWithAliasSets(), mlir::OpToFuncCallLowering< SourceOp >::appendOrGetFuncOp(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::bufferization::bufferizeModuleOp(), mlir::bufferization::bufferizeOp(), collectValidReferencesFor(), mlir::nvgpu::createAsyncGroups(), mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >::createDIScopeForLLVMFuncOpPass, createNewAliasScopesFromNoAliasParameter(), mlir::detail::defaultOperatesOnDisjointSubset(), mlir::detail::defaultOperatesOnEquivalentSubset(), diagnoseInvalidOperandDominance(), mlir::xegpu::doSCFStructuralTypeConversionWithTensorType(), doVerifyRoundTrip(), emitError(), emitRemark(), emitWarning(), findPayloadRoot(), generateLocationsFromIR(), getAttrDictionary(), mlir::affine::getComputationSliceState(), mlir::OpState::getContext(), mlir::Pass::getContext(), getDiscardableAttrDictionary(), getElementalFuncTypeForOp(), mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getIndexingMaps(), mlir::ROCDL::getKernelMetadata(), getLibraryCallSymbolRef(), mlir::arith::getNeutralElement(), getReductionDataSize(), handleInlinedAllocas(), inferSideEffectAnnotations(), mlir::detail::PassCrashReproducerGenerator::initialize(), mlir::SymbolTable::insert(), mlir::bufferization::insertTensorCopies(), mlir::LLVM::lookupOrCreateAlignedAllocFn(), mlir::LLVM::lookupOrCreateApFloatPrintFn(), mlir::LLVM::lookupOrCreateFreeFn(), mlir::LLVM::lookupOrCreateGenericAlignedAllocFn(), mlir::LLVM::lookupOrCreateGenericAllocFn(), mlir::LLVM::lookupOrCreateGenericFreeFn(), mlir::LLVM::lookupOrCreateMallocFn(), mlir::LLVM::lookupOrCreateMemRefCopyFn(), mlir::LLVM::lookupOrCreatePrintBF16Fn(), mlir::LLVM::lookupOrCreatePrintCloseFn(), mlir::LLVM::lookupOrCreatePrintCommaFn(), mlir::LLVM::lookupOrCreatePrintF16Fn(), mlir::LLVM::lookupOrCreatePrintF32Fn(), mlir::LLVM::lookupOrCreatePrintF64Fn(), mlir::LLVM::lookupOrCreatePrintI64Fn(), mlir::LLVM::lookupOrCreatePrintNewlineFn(), mlir::LLVM::lookupOrCreatePrintOpenFn(), mlir::LLVM::lookupOrCreatePrintStringFn(), mlir::LLVM::lookupOrCreatePrintU64Fn(), mlir::SymbolTable::lookupSymbolIn(), mlir::spirv::lookupTargetEnvOrDefault(), mlir::tosa::lookupTargetEnvOrDefault(), mlir::PatternApplicator::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), populateDefaultAttrs(), prepareLLVMModule(), printBlockArgRegion(), printOffloadingHandler(), mlir::dlti::query(), removeAttr(), removeAttr(), removeDiscardableAttr(), removeDiscardableAttr(), mlir::query::MatchQuery::run(), setAttr(), setAttr(), setAttrs(), setAttrs(), setDialectAttrs(), setDiscardableAttr(), setDiscardableAttr(), setDiscardableAttrs(), mlir::OperationName::UnregisteredOpModel::setInherentAttr(), setLexicalBlockFileAttr(), setMmraAttr(), mlir::SymbolTable::setSymbolName(), mlir::SymbolTable::setSymbolVisibility(), mlir::affine::simplifyConstrainedMinMaxOp(), mlir::LLVM::detail::LoopAnnotationTranslation::translateLoopAnnotation(), tryApply(), mlir::spirv::unrollVectorsInFuncBodies(), mlir::spirv::unrollVectorsInSignatures(), mlir::detail::verifyInferredResultTypes(), verifyOpAndAdjustFlags(), and mlir::walkAndApplyPatterns().
getDialect()
Dialect * mlir::Operation::getDialect () inline
Return the dialect this operation is associated with, or nullptr if the associated dialect is not loaded.
Definition at line 220 of file Operation.h.
References mlir::OperationName::getDialect(), and getName().
Referenced by checkImplementationStatus(), emit(), findCapturedOmpOp(), fold(), mlir::detail::DialectInterfaceCollectionBase::getInterfaceFor(), mlir::Dialect::getOperationPrinter(), getParentInSameDialect(), mlir::OperationFolder::insertKnownConstant(), isLinearizable(), isPotentiallyUnknownSymbolTable(), mlir::dataflow::maybeReplaceWithConstant(), opInGlobalImplicitParallelRegion(), mlir::populateConversionTargetFromOperation(), mlir::math::populateExtendToSupportedTypesConversionTarget(), mlir::OpState::print(), verifyQuantifierRegions(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and mlir::tosa::impl::TosaInferShapesPassBase< DerivedT >::~TosaInferShapesPassBase().
getDialectAttrs()
dialect_attr_range mlir::Operation::getDialectAttrs () inline
Return a range corresponding to the dialect attributes for this operation.
Definition at line 637 of file Operation.h.
References getAttrs().
getDiscardableAttr() [1/2]
Attribute mlir::Operation::getDiscardableAttr (StringAttr name) inline
Access a discardable attribute by name, returns a null Attribute if the discardable attribute does not exist.
Definition at line 457 of file Operation.h.
getDiscardableAttr() [2/2]
Attribute mlir::Operation::getDiscardableAttr (StringRef name) inline
Access a discardable attribute by name, returns a null Attribute if the discardable attribute does not exist.
Definition at line 453 of file Operation.h.
Referenced by prepareLLVMModule().
getDiscardableAttrDictionary()
DictionaryAttr mlir::Operation::getDiscardableAttrDictionary () inline
Return all of the discardable attributes on this operation as a DictionaryAttr.
Definition at line 501 of file Operation.h.
References getContext(), getDiscardableAttrs(), and getPropertiesStorage().
Referenced by mlir::createGpuAsyncRegionPass().
getDiscardableAttrs()
auto mlir::Operation::getDiscardableAttrs () inline
Return a range of all of discardable attributes on this operation.
Note that for unregistered operations that are not storing inherent attributes as properties, all attributes are considered discardable.
Definition at line 486 of file Operation.h.
References getRegisteredInfo().
Referenced by getDiscardableAttrDictionary(), and mlir::detail::verifySymbolTable().
getInherentAttr()
std::optional< Attribute > Operation::getInherentAttr (StringRef name)
Access an inherent attribute by name: returns an empty optional if there is no inherent attribute with this name.
This method is available as a transient facility in the migration process to use Properties instead.
Definition at line 341 of file Operation.cpp.
References mlir::OperationName::getInherentAttr(), and getName().
Referenced by getAttr(), getAttr(), hasAttr(), hasAttr(), removeAttr(), setAttr(), setAttrs(), and setAttrs().
getLoc()
Location mlir::Operation::getLoc () inline
The source location the operation was defined or derived from.
Definition at line 223 of file Operation.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::appendOrGetFuncOp(), mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(), mlir::linalg::bufferizeToAllocation(), buildMultiDimReduce(), mlir::transform::detail::checkApplyToOne(), checkDoubleConsume(), mlir::clone(), clone(), cloneAndFuseFirstUse(), mlir::cloneWithoutRegions(), mlir::OperationEquivalence::computeHash(), computeMemoryOpIndices(), convertDeclareTargetAttr(), convertElementwiseOp(), convertMixedValuesToInt(), mlir::linalg::copyToWorkgroupMemory(), mlir::nvgpu::createAsyncGroups(), mlir::emitc::createExpression(), mlir::createGpuAsyncRegionPass(), mlir::LLVM::detail::createIntrinsicCall(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), createNewAliasScopesFromNoAliasParameter(), createPrivateMemRef(), createSourceLocationInfo(), mlir::ControlFlowToSCFTransformation::createStructuredBranchRegionOp(), mlir::ControlFlowToSCFTransformation::createStructuredDoWhileLoopOp(), diagnoseInvalidOperandDominance(), elementwiseMatchAndRewriteHelper(), emitError(), mlir::acc::emitRemark(), emitRemark(), emitWarning(), ensurePayloadIsSeparateFromTransform(), mlir::detail::PassCrashReproducerGenerator::finalize(), mlir::transform::TrackingListener::findReplacementOp(), fuse(), mlir::arm_sme::impl::TestTileAllocationBase< DerivedT >::getDependentDialects(), getLibraryCallSymbolRef(), mlir::LatticeAnchor::getLoc(), getMemoryFootprintBytes(), mlir::vector::getMixedSizesXfer(), mlir::arith::getNeutralElement(), mlir::spirv::getPushConstantValue(), getTypeConversionFailure(), handleInlinedAllocas(), handleLoopAnnotations(), mlir::LLVM::detail::handleMultidimensionalVectors(), inlinePayload(), insertCasts(), mlir::bufferization::deallocation_impl::insertDeallocOpForReturnLike(), interruptIfValidLocation(), mlir::LLVM::detail::intrinsicRewrite(), isFusionProfitable(), legalizeBlockArguments(), mlir::LLVM::lookupOrCreateFn(), lookupOrCreateSPIRVFn(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), matchAndReplaceDepthwiseConv(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::RewriterBase::notifyMatchFailure(), mlir::transform::ErrorCheckingTrackingListener::notifyPayloadReplacementNotFound(), mlir::LLVM::detail::oneToOneRewrite(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), prepareLLVMModule(), printConstantOp(), printFunctionArgs(), printFunctionArgs(), mlir::query::matcher::MatchFinder::printMatch(), mlir::query::matcher::MatchFinder::printMatch(), printOperation(), printOperation(), printOperation(), mlir::dlti::query(), ReifyCollapseShapeOp::reifyResultShapes(), replaceAndPropagateMemRefType(), mlir::detail::AttrTypeReplacerBase< Concrete >::replaceElementsIn(), replaceForAllWithNewSignature(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::PassManager::run(), scalarizeVectorOpHelper(), setLexicalBlockFileAttr(), setLoopAttr(), tileAndFuseFirstExtractUse(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), transformCyclesToSCFLoops(), transformToStructuredCFBranches(), unpackSingleIndexResultPayloadOperations(), mlir::vector::unrollVectorOp(), vectorizeOneOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), verifyAndGetTerminator(), mlir::detail::verifyDataLayoutOp(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), verifyMapClause(), verifyNamedSequenceOp(), verifyQuantifierRegions(), mlir::detail::verifySymbolTable(), verifyYieldingSingleBlockOp(), widenOp(), and wrapInExecuteRegion().
getName()
OperationName mlir::Operation::getName () inline
The name of an operation is the key identifier for it.
Definition at line 119 of file Operation.h.
Referenced by AncestorKey::AncestorKey(), appendReproducer(), mlir::bufferization::bufferizeOp(), mlir::Pass::canScheduleOn(), checkAndUpdateCapabilityRequirements(), checkAndUpdateExtensionRequirements(), mlir::transform::detail::checkApplyToOne(), checkImplementationStatus(), TosaProfileCompliance::checkInvalid(), checkSymbolIsTypeOrAttribute(), mlir::Op< ConcreteType, Traits >::classof(), mlir::clone(), clone(), cloneOpWithOperandsAndTypes(), cloneOpWithOperandsAndTypes(), mlir::cloneWithoutRegions(), mlir::OperationEquivalence::computeHash(), mlir::OperationConverter::convert(), convertHostOrTargetOperation(), mlir::createGpuAsyncRegionPass(), mlir::ControlFlowToSCFTransformation::createUnreachableTerminator(), mlir::ValueBoundsConstraintSet::dump(), emitOpError(), mlir::transform::TrackingListener::findReplacementOp(), mlir::OpTrait::impl::foldIdempotent(), mlir::OpTrait::impl::foldInvolution(), mlir::linalg::generateLibraryCallName(), getAttrDictionary(), getDialect(), mlir::spirv::getElementPtrType(), mlir::getEnclosingRepetitiveRegion(), mlir::getEnclosingRepetitiveRegion(), getInherentAttr(), mlir::spirv::getIntegerDotProductCapabilities(), mlir::OpInterface< ConcreteType, Traits >::getInterfaceFor(), mlir::ValueBoundsConstraintSet::getPos(), getRegisteredInfo(), getTargetShape(), mlir::AsmParserState::initialize(), mlir::ValueBoundsConstraintSet::insert(), isRegistered(), mlir::detail::NameOpMatcher::match(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlir::PatternApplicator::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::detail::ConversionPatternRewriterImpl::notifyBlockInserted(), mlir::RewriterBase::PatternLoggingListener::notifyOperationErased(), mlir::detail::ConversionPatternRewriterImpl::notifyOperationInserted(), mlir::RewriterBase::PatternLoggingListener::notifyOperationInserted(), mlir::RewriterBase::PatternLoggingListener::notifyOperationModified(), mlir::RewriterBase::PatternLoggingListener::notifyOperationReplaced(), mlir::RewriterBase::PatternLoggingListener::notifyOperationReplaced(), mlir::RewriterBase::PatternLoggingListener::notifyPatternBegin(), mlir::operator<<(), mlir::detail::PassCrashReproducerGenerator::prepareReproducerFor(), printIR(), mlir::OpState::printOpName(), printShortForm(), mlir::spirv::Serializer::printValueIDMap(), mlir::ValueBoundsConstraintSet::processWorklist(), mlir::detail::ConversionPatternRewriterImpl::replaceOp(), reportNewIrLegalizationFatalError(), mlir::PassManager::run(), mlir::dataflow::RunLivenessAnalysis::RunLivenessAnalysis(), scalarizeVectorOpHelper(), setInherentAttr(), setPropertiesFromAttribute(), vectorizeOneOp(), mlir::spirv::verifyAtomicUpdateOp(), mlir::detail::verifyBranchSuccessorOperands(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), mlir::spirv::verifyIntegerDotProduct(), verifyMmaSyncOp(), mlir::transform::detail::verifyParamProducerTransformOpTrait(), verifyRegion(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::NavigationTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait(), and widenOp().
getNumOperands()
unsigned mlir::Operation::getNumOperands () inline
Definition at line 346 of file Operation.h.
Referenced by addExecuteResults(), mlir::sparse_tensor::Merger::buildExp(), canUseShortForm(), clone(), mlir::Region::cloneInto(), mlir::OperationEquivalence::computeHash(), convertOmpOpRegions(), mlir::shard::detail::defaultAddShardingAnnotations(), mlir::shard::detail::defaultGetShardingAnnotations(), mlir::shard::detail::defaultGetShardingOption(), elementwiseMatchAndRewriteHelper(), emitElementwiseComputation(), extractOperandTypes(), findProducerOfType(), fold(), mlir::OpTrait::impl::foldCommutative(), mlir::OpTrait::impl::foldIdempotent(), getElementalFuncTypeForOp(), mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getIndexingMaps(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getNumOperands(), getOperandSegmentSizes(), mlir::shard::getOperandShardings(), getSourceSkipUnary(), mlir::sparse_tensor::isAdmissibleBranchExp(), isaElemwiseSingleUnaryOrBinaryOpInterface(), mlir::linalg::detail::isContractionBody(), isOpLoopInvariant(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match(), mlir::matchReduction(), materializeConversion(), setInPlaceOpOperand(), setOperands(), vectorizeAffineYieldOp(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), mlir::spirv::verifyIntegerDotProduct(), verifyNamedSequenceOp(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOperandSizeAttr(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), verifyQuantifierRegions(), mlir::OpTrait::impl::verifySameTypeOperands(), mlir::linalg::detail::verifyStructuredOpInterface(), verifyYieldingSingleBlockOp(), mlir::OpTrait::impl::verifyZeroOperands(), visitOp(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
getNumRegions()
unsigned mlir::Operation::getNumRegions () inline
Returns the number of regions held by this operation.
Definition at line 674 of file Operation.h.
Referenced by canBeHoisted(), clone(), mlir::cloneWithoutRegions(), mlir::createGpuAsyncRegionPass(), mlir::smt::exportSMTLIB(), findCapturedOmpOp(), getBackwardSliceImpl(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getNumRegions(), irdlRegionVerifier(), isPotentiallyUnknownSymbolTable(), isVectorizableLoopBodyWithOpCond(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlirDebuggerCursorSelectNextIRUnit(), mlirLinalgFillBuiltinNamedOpRegion(), mlirOperationGetFirstRegion(), mlirRegionGetNextInOperation(), mlir::memref::resultIsNotRead(), vectorizeOneOperation(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::detail::verifyInParallelOpInterface(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyOneRegion(), verifyOrderedParent(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::detail::verifyRegionBranchWeights(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), mlir::detail::verifySymbolTable(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), mlir::OpTrait::impl::verifyZeroRegions(), mlir::dataflow::DeadCodeAnalysis::visit(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and wrapInExecuteRegion().
getNumResults()
unsigned mlir::Operation::getNumResults () inline
Return the number of results held by this operation.
Definition at line 404 of file Operation.h.
Referenced by mlir::transform::detail::checkApplyToOne(), clone(), convertMixedValuesToInt(), convertOperationImpl(), mlir::emitc::createExpression(), mlir::createGpuAsyncRegionPass(), elementwiseMatchAndRewriteHelper(), mlir::sparse_tensor::LoopEmitter::exitCurrentLoop(), mlir::transform::TrackingListener::findReplacementOp(), getElementalFuncTypeForOp(), mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getIndexingMaps(), getLibraryCallSymbolRef(), mlir::spirv::getNativeVectorShape(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getNumResults(), getResultSegmentSizes(), mlir::shard::getResultShardings(), getSubgroupMmaNativeVectorSize(), getTypeConversionFailure(), inferFragType(), mlir::LLVM::detail::intrinsicRewrite(), isaElemwiseSingleUnaryOrBinaryOpInterface(), mlir::linalg::detail::isContractionBody(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlir::matchReduction(), materializeConversion(), mlir::LLVM::detail::oneToOneRewrite(), mlir::Liveness::print(), mlir::OpAsmPrinter::printFunctionalType(), printOneResultOp(), reifyMixedParamAndHandleResults(), replaceAndPropagateMemRefType(), mlir::detail::ConversionPatternRewriterImpl::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::memref::resultIsNotRead(), mlir::transform::detail::setApplyToOneResults(), unpackSingleIndexResultPayloadOperations(), mlir::vector::unrollVectorOp(), mlir::OpTrait::impl::verifyAtLeastNResults(), mlir::LLVM::detail::verifyDereferenceableOpInterface(), mlir::OpTrait::impl::verifyElementwise(), verifyInitializationAttribute(), mlir::spirv::verifyIntegerDotProduct(), mlir::detail::verifyMemorySpaceCastOpInterface(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyResultSizeAttr(), mlir::detail::verifyShapedDimOpInterface(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), mlir::OpTrait::impl::verifyZeroResults(), mlir::dataflow::LivenessAnalysis::visitBranchOperand(), visitOp(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and walkReferenceCountedValues().
getNumSuccessors()
unsigned mlir::Operation::getNumSuccessors () inline
Definition at line 706 of file Operation.h.
Referenced by checkTransformationPreconditions(), clone(), eraseTerminatorSuccessorOperands(), mlir::Block::getNumSuccessors(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getNumSuccessors(), getPHISourceValue(), getSuccessor(), isRegionOrCallableReturn(), mlir::OperationFingerPrint::OperationFingerPrint(), propagateTerminatorLiveness(), setProfilingAttr(), setSuccessor(), mlir::SuccessorRange::SuccessorRange(), mlir::OpTrait::impl::verifyAtLeastNSuccessors(), mlir::detail::verifyBranchWeights(), mlir::OpTrait::impl::verifyNSuccessors(), mlir::OpTrait::impl::verifyOneSuccessor(), mlir::OpTrait::impl::verifyZeroSuccessors(), and mlir::dataflow::DeadCodeAnalysis::visit().
getOperand()
Value mlir::Operation::getOperand (unsigned idx) inline
Definition at line 350 of file Operation.h.
References mlir::IROperand< DerivedT, IRValueT >::get(), getOpOperand(), and Value.
Referenced by mlir::affine::affineParallelize(), mlir::linalg::bodyMatcherForConvolutionOps(), mlir::linalg::bodyMatcherForPoolOps(), mlir::linalg::bodyMatcherForZeroPointOffsets(), mlir::sparse_tensor::Merger::buildExp(), mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), mlir::OperationEquivalence::computeHash(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOpRegions(), convertOmpThreadprivate(), createLinalgBodyCalculationForElementwiseOp(), diagnoseInvalidOperandDominance(), findProducerOfType(), fold(), foldExtractFromBroadcast(), mlir::OpTrait::impl::foldIdempotent(), mlir::OpTrait::impl::foldInvolution(), mlir::linalg::getBlockArgumentWithOptionalCastOps(), getBroadcastableOperands(), getDistinctObjectsOperand(), getGlobalOpFromValue(), mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getIndexingMaps(), mlir::spirv::getIntegerDotProductCapabilities(), mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getLoopIteratorTypes(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperand(), mlir::OpTrait::OneOperand< ConcreteType >::getOperand(), getPHISourceValue(), getSourceSkipUnary(), mlir::sparse_tensor::isAdmissibleBranch(), mlir::sparse_tensor::isAdmissibleBranchExp(), mlir::linalg::detail::isContractionBody(), isOpLoopInvariant(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlir::detail::matchOperandOrValueAtIndex(), mlir::matchReduction(), materializeConversion(), printBinaryOperation(), printOperation(), printUnaryOperation(), mlir::spirv::verifyAtomicUpdateOp(), mlir::spirv::verifyCastOp(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), mlir::spirv::verifyIntegerDotProduct(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShiftOp(), and mlir::OpTrait::tosa::MulOperandsAndResultElementType< ConcreteType >::verifyTrait().
getOperands()
operand_range mlir::Operation::getOperands () inline
Returns an iterator on the underlying Value's.
Definition at line 378 of file Operation.h.
References getOpOperands().
Referenced by mlir::linalg::bufferizeToAllocation(), canBeHoisted(), canonicalizeMinMaxOp(), mlir::scf::canonicalizeMinMaxOpInLoop(), canUseShortForm(), checkAssumptionForLoop(), checkPreconditions(), clone(), mlir::Region::cloneInto(), mlir::coalesceLoops(), mlir::affine::LoopNestStateCollector::collect(), mlir::OperationEquivalence::computeHash(), mlir::ValueBoundsConstraintSet::computeIndependentBound(), convertElementwiseOp(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), createDecl(), mlir::emitc::createExpression(), mlir::createGpuAsyncRegionPass(), mlir::LLVM::detail::createIntrinsicCall(), defaultIsSmallAlloc(), mlir::arm_sme::eraseTriviallyDeadTileOps(), extractBeneficiaryOps(), mlir::transform::TrackingListener::findReplacementOp(), mlir::impl::foldCastInterfaceOp(), mlir::transform::detail::forwardTerminatorOperands(), genForeachOnSparseConstant(), getDynamicSize(), getEffectedValues(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperands(), mlir::shard::getOperandShardings(), getOperandTypes(), getOutermostInvariantForOp(), mlir::shard::getResultShardings(), mlir::sparse_tensor::hasAnyNonIdentityOperandsOrResults(), mlir::sparse_tensor::hasAnySparseOperand(), hasBufferSemantics(), inlineConvertOmpRegions(), inlinePayload(), insertCasts(), isOpReady(), mlir::makeRegionIsolatedFromAbove(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::detail::infer_int_range_op_binder::match(), AllocaScopeHoister::matchAndRewrite(), AllocaScopeInliner::matchAndRewrite(), DropUnitDimFromElementwiseOps::matchAndRewrite(), FoldConstantCase::matchAndRewrite(), SortCommutativeOperands::matchAndRewrite(), matchBlock(), matchSimpleReduction(), operand_begin(), operand_end(), operandsAndResultsRanked(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::LLVM::detail::opHasUnsupportedFloatingPointTypes(), mlir::outlineSingleBlockRegion(), mlir::shard::partitionFullyReplicatedOperation(), mlir::shard::partitionOperation(), CommutativeOperand::popFrontAndPushAdjacentUnvisitedAncestors(), printArithmeticExtendedBinaryOp(), mlir::OpAsmPrinter::printFunctionalType(), printOneResultOp(), processParallelLoop(), reconcileUnrealizedCastsImpl(), replaceOpWithRegion(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runDenseBufferization(), mlir::affine::simplifyConstrainedMinMaxOp(), mlir::dataflow::staticallyNonNegative(), vectorizeOneOp(), mlir::detail::verifyInferredResultTypes(), verifyNamedSequenceOp(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::tosa::verifyTosaResolvableShapeOperands(), verifyYieldingSingleBlockOp(), mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and widenOp().
getOperandTypes()
operand_type_range mlir::Operation::getOperandTypes () inline
Definition at line 397 of file Operation.h.
References getOperands(), and mlir::OperandRange::getTypes().
Referenced by checkSourceOpTypes(), mlir::xegpu::doSCFStructuralTypeConversionWithTensorType(), extractOperandTypes(), mlir::linalg::generateLibraryCallName(), mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >::getLoopIteratorTypes(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperandTypes(), getOpToConvert(), hasZeroDimVectors(), insertCasts(), irdlOpVerifier(), isElementwiseMappableOpOnRankedTensors(), isLegalOp(), isVectorizableLoopBodyWithOpCond(), mlir::outlineSingleBlockRegion(), mlir::shard::partitionFuncOp(), printOneResultOp(), mlir::impl::verifyCastInterfaceOp(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::OpTrait::impl::verifyElementwise(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultRank(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), mlir::OpTrait::tosa::verifyTosaShapeOperator(), and mlir::OpTrait::tosa::verifyTosaShapeOperatorWithSameRanks().
getOpOperand()
OpOperand & mlir::Operation::getOpOperand (unsigned idx) inline
Definition at line 388 of file Operation.h.
Referenced by areBinOpsSwapped(), mlir::affine::AffineDmaStartOp::getDstMemRefMutable(), getOperand(), mlir::affine::AffineDmaStartOp::getSrcMemRefMutable(), mlir::affine::AffineDmaStartOp::getTagMemRefMutable(), mlir::affine::AffineDmaWaitOp::getTagMemRefMutable(), and setOperand().
getOpOperands()
MutableArrayRef< OpOperand > mlir::Operation::getOpOperands () inline
Definition at line 383 of file Operation.h.
Referenced by mlir::bufferization::OneShotAnalysisState::analyzeSingleOp(), annotateOpsWithBufferizationMarkers(), mlir::linalg::bufferizeToAllocation(), checkPreBufferizationAssumptions(), mlir::shard::detail::defaultAddShardingAnnotations(), mlir::shard::detail::defaultGetShardingAnnotations(), dropAllReferences(), mlir::OpTrait::impl::foldCommutative(), mlir::memref::foldMemRefCast(), mlir::tensor::foldTensorCast(), getBackwardSliceImpl(), mlir::OpOperand::getOperandNumber(), getOperands(), mlir::transform::detail::getParamProducerTransformOpTraitEffects(), mlir::transform::detail::getPotentialTopLevelEffects(), mlir::tensor::hasFoldableTensorCastOperand(), inlineRegionAndEmitStore(), mlir::xegpu::removeLayoutAttrs(), replaceUsesOfWith(), mlir::xegpu::setDistributeLayoutAttrs(), setInPlaceOpOperand(), mlir::transform::detail::verifyTransformOpInterface(), visitOp(), and mlir::visitUsedValuesDefinedAbove().
getOpResult()
OpResult mlir::Operation::getOpResult (unsigned idx) inline
Definition at line 421 of file Operation.h.
References getResult().
Referenced by applyTilingToAll().
getOpResults()
result_range mlir::Operation::getOpResults () inline
Definition at line 420 of file Operation.h.
References getResults().
Referenced by annotateOpsWithAliasSets(), cloneAndFuseFirstUse(), mlir::xegpu::doSCFStructuralTypeConversionWithTensorType(), dropAllUses(), forwardEmptyOperands(), mlir::transform::detail::forwardTerminatorOperands(), mlir::bufferization::OneShotAnalysisState::gatherUndefinedTensorUses(), mlir::transform::detail::getPotentialTopLevelEffects(), isUsedOutsideOfBlock(), mlir::xegpu::removeLayoutAttrs(), and mlir::xegpu::setDistributeLayoutAttrs().
getParentOfType()
template<typename OpTy> OpTy mlir::Operation::getParentOfType () inline
Return the closest surrounding parent operation that is of type 'OpTy'.
Definition at line 238 of file Operation.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::appendOrGetFuncOp(), canPromoteToNoLoop(), castOrGetParentOfType(), convertDeclareTargetAttr(), convertOmpDistribute(), convertOmpTarget(), convertOmpTargetData(), createPrivateMemRef(), createSourceLocationInfo(), debugPrintLoopInShortForm(), mlir::acc::emitRemark(), mlir::xegpu::getChipStr(), mlir::impl::SCFForLoopSpecializationBase< DerivedT >::getDependentDialects(), mlir::acc::getDominatingDataClauses(), getReductionDataSize(), getTargetSystemSpec(), handleLoopAnnotations(), mlir::linalg::hoistPaddingOnTensors(), mlir::scf::insideMutuallyExclusiveBranches(), isInsideLaunch(), isTargetDeviceOp(), mlir::affine::numEnclosingInvariantLoops(), numEnclosingInvariantLoops(), mlir::populateOpConvertToLLVMConversionPatterns(), mlir::bufferization::runOneShotModuleBufferize(), setLexicalBlockFileAttr(), verifyNamedSequenceOp(), verifyOrderedParent(), and verifyYieldingSingleBlockOp().
getParentOp()
Operation * mlir::Operation::getParentOp () inline
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
Definition at line 234 of file Operation.h.
References getParentOp().
Referenced by canMakeGroupOpUniform(), castOrGetParentOfType(), checkImplementationStatus(), mlir::DataLayout::closest(), collectParentLayouts(), collectSymbolScopes(), collectValidReferencesFor(), convertHostOrTargetOperation(), convertOmpWsloop(), mlir::createGpuEliminateBarriers(), mlir::DataLayoutAnalysis::DataLayoutAnalysis(), declareReduction(), mlir::xegpu::doSCFStructuralTypeConversionWithTensorType(), ensurePayloadIsSeparateFromTransform(), findAncestorOpInRegion(), mlir::Region::findAncestorOpInRegion(), findCommonAncestor(), mlir::affine::findInnermostCommonBlockInScope(), findParent(), findParent(), mlir::DataLayoutAnalysis::getAbove(), mlir::affine::getAffineAnalysisScope(), mlir::affine::getAffineForIVs(), mlir::affine::getAffineIVs(), mlir::affine::getAffineParallelInductionVarOwner(), getAllocEffectFor(), mlir::ml_program::impl::MLProgramPipelineGlobalsPassBase< DerivedT >::getArgumentName(), getAtMostNEnclosingLoops(), mlir::getBackwardSlice(), mlir::AnalysisManager::getCachedChildAnalysis(), mlir::Pass::getCachedParentAnalysis(), getClosestQueryable(), mlir::acc::getDefaultAttr(), mlir::detail::DominanceInfoBase< IsPostDom >::getDominanceInfo(), mlir::acc::getDominatingDataClauses(), getEffectsBefore(), mlir::affine::getEnclosingAffineOps(), mlir::acc::getEnclosingComputeOp(), getEnclosingLoopsUntil(), mlir::SymbolTable::getNearestSymbolTable(), mlir::affine::getNestingDepth(), getOutermostInvariantForOp(), getOwnerOfValue(), getParentInSameDialect(), getParentOp(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::getParentOp(), getParentWithTrait(), mlir::spirv::getPushConstantValue(), mlir::sparse_tensor::getTop(), getUntiledConsumerFromSlice(), handleInlinedAllocas(), happensBefore(), happensBefore(), mlir::affine::hasNoInterveningEffect(), mlir::SymbolTable::insert(), mlir::spirv::isNestedInFunctionOpInterface(), mlir::spirv::isNestedInGraphARMOpInterface(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), isOpReady(), isProperAncestor(), isRegionOrCallableReturn(), mlir::affine::isTopLevelValue(), lookupDialectOp(), mlir::spirv::lookupEntryPointABI(), mlir::spirv::lookupTargetEnv(), mlir::tosa::lookupTargetEnv(), AllocaScopeHoister::matchAndRewrite(), mlir::matchReduction(), mlirAsmStateCreateForValue(), mlirDebuggerCursorSelectNextIRUnit(), mlirDebuggerCursorSelectPreviousIRUnit(), movePaddingToFillOrGenericOp(), mlir::AnalysisManager::nest(), mlir::detail::ConversionPatternRewriterImpl::notifyOperationInserted(), mlir::OperationFingerPrint::OperationFingerPrint(), opInGlobalImplicitParallelRegion(), mlir::LLVM::parentLLVMModule(), mlir::detail::PassCrashReproducerGenerator::prepareReproducerFor(), mlir::Block::print(), mlir::Value::printAsOperand(), printFunctionBody(), mlir::SymbolTable::remove(), mlir::SymbolTable::rename(), mlir::SymbolUserMap::replaceAllUsesWith(), mlir::detail::ConversionPatternRewriterImpl::replaceValueUses(), shouldBeInlined(), verifyHasBindingUse(), verifyOrderedParent(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait(), mlir::dataflow::DeadCodeAnalysis::visit(), visit(), mlir::dataflow::LivenessAnalysis::visitBranchOperand(), and walkReferencedSymbolNodes().
getParentRegion()
Region * mlir::Operation::getParentRegion () inline
Returns the region to which the instruction belongs.
Returns nullptr if the instruction is unlinked.
Definition at line 230 of file Operation.h.
Referenced by canUseOpDominanceDueToBlocks(), findAncestorOpInRegion(), mlir::Region::findAncestorOpInRegion(), findCapturedOmpOp(), findHighestBlockForPlacement(), mlir::affine::findInnermostCommonBlockInScope(), generateLoopNestingName(), mlir::affine::getAffineAnalysisScope(), mlir::getEnclosingRepetitiveRegion(), mlir::getEnclosingRepetitiveRegion(), handleInlinedAllocas(), mlir::affine::hasNoInterveningEffect(), mlir::affine::isTopLevelValue(), isTopLevelValueOrAbove(), lastNonTerminatorInRegion(), mlir::moveLoopInvariantCode(), mlir::operator<<(), mlir::wasmssa::detail::verifyLabelLevelInterface(), and verifyTerminatorSuccessors().
getParentWithTrait()
template<template< typename T > class Trait> Operation * mlir::Operation::getParentWithTrait () inline
Returns the closest surrounding parent operation with trait Trait.
Definition at line 248 of file Operation.h.
References getParentOp(), and hasTrait().
Referenced by mlir::convertFuncOpToLLVMFuncOp(), findCommonAncestor(), getDumpRootOp(), mlir::bufferization::insertSymbol(), mlir::bufferization::insertTensorCopies(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), mlir::GPUPrintfOpToVPrintfLowering::matchAndRewrite(), mlir::bufferization::removeSymbol(), verifyNamedSequenceOp(), and mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait().
getPropertiesAsAttribute()
Attribute Operation::getPropertiesAsAttribute ()
Return the properties converted to an attribute.
This is expensive, and mostly useful when dealing with unregistered operation. Returns an empty attribute if no properties are present.
Definition at line 349 of file Operation.cpp.
References mlir::OpaqueProperties::as(), getPropertiesStorage(), and getRegisteredInfo().
getPropertiesStorage() [1/2]
OpaqueProperties mlir::Operation::getPropertiesStorage () inline
Returns the properties storage.
Definition at line 900 of file Operation.h.
References getPropertiesStorageUnsafe().
Referenced by clone(), copyProperties(), mlir::createGpuAsyncRegionPass(), getDiscardableAttrDictionary(), mlir::OperationName::UnregisteredOpModel::getPropertiesAsAttr(), getPropertiesAsAttribute(), hashProperties(), mlir::OperationName::UnregisteredOpModel::setInherentAttr(), mlir::OperationState::setProperties(), setPropertiesFromAttribute(), and mlir::detail::verifyInferredResultTypes().
getPropertiesStorage() [2/2]
OpaqueProperties mlir::Operation::getPropertiesStorage () const inline
Definition at line 905 of file Operation.h.
getPropertiesStorageSize()
int mlir::Operation::getPropertiesStorageSize () const inline
Returns the properties storage size.
Definition at line 896 of file Operation.h.
Referenced by getAttr(), getAttr(), getAttrDictionary(), hasAttr(), hasAttr(), removeAttr(), setAttr(), setAttrs(), and setAttrs().
getPropertiesStorageUnsafe()
OpaqueProperties mlir::Operation::getPropertiesStorageUnsafe () inline
Returns the properties storage without checking whether properties are present.
Definition at line 913 of file Operation.h.
Referenced by mlir::Op< ConcreteType, Traits >::getProperties(), and getPropertiesStorage().
getRawDictionaryAttrs()
DictionaryAttr mlir::Operation::getRawDictionaryAttrs () inline
Return all attributes that are not stored as properties.
Definition at line 509 of file Operation.h.
Referenced by mlir::OperationEquivalence::computeHash(), mlir::OperationFingerPrint::OperationFingerPrint(), and mlir::detail::verifyInferredResultTypes().
getRegion()
Region & mlir::Operation::getRegion (unsigned index) inline
Returns the region held by this operation at position 'index'.
Definition at line 686 of file Operation.h.
References getRegions().
Referenced by mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), clone(), collectSymbolScopes(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpSections(), mlir::ExecutionEngine::create(), create(), create(), createExpandedGenericOp(), mlir::irdl::createVerifier(), mlir::smt::exportSMTLIB(), getAttrOrTypeVerifier(), getBackwardSliceImpl(), mlir::OpTrait::SingleBlock< ConcreteType >::getBody(), mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::getBodyBlock(), mlir::OpTrait::SingleBlock< ConcreteType >::getBodyRegion(), mlir::bufferization::getGlobalFor(), mlir::getOrCreateStringConstant(), mlir::getOrDefineFunction(), mlir::spirv::getPushConstantValue(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegion(), mlir::OpTrait::OneRegion< ConcreteType >::getRegion(), mlir::LLVM::lookupOrCreateFn(), lookupOrCreateSPIRVFn(), mlir::transform::detail::mergeSymbolsInto(), mlirDebuggerCursorSelectNextIRUnit(), mlirDebuggerCursorSelectPreviousIRUnit(), mlirLinalgFillBuiltinNamedOpRegion(), mlirOperationGetFirstRegion(), mlirRegionGetNextInOperation(), mlir::SymbolTable::SymbolTable(), mlir::SymbolUserMap::SymbolUserMap(), mlir::wasmssa::detail::verifyConstantExpressionInterface(), mlir::detail::verifyInParallelOpInterface(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), mlir::detail::verifySymbolTable(), and mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait().
getRegions()
MutableArrayRef< Region > mlir::Operation::getRegions () inline
Returns the regions held by this operation.
Definition at line 677 of file Operation.h.
Referenced by annotateOpsWithAliasSets(), mlir::applyPatternsGreedily(), mlir::bufferization::bufferizeModuleOp(), mlir::bufferization::bufferizeOp(), checkPreBufferizationAssumptions(), mlir::clone(), mlir::OpBuilder::clone(), mlir::Region::cloneInto(), collectCallOps(), collectEffects(), collectSymbolScopes(), computeCallGraph(), mlir::createGpuAsyncRegionPass(), dropAllDefinedValueUses(), dropAllReferences(), mlir::LLVM::ensureDistinctSuccessors(), findTransformEntryPointNonRecursive(), generateLoopNestingName(), getBackwardSliceImpl(), mlir::getEffectsRecursively(), getForwardSliceImpl(), getFuncOpsOrderedByCalls(), mlir::getInnermostParallelLoops(), getInstAtPosition(), getRegion(), mlir::Region::getRegionNumber(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegions(), hasBufferSemantics(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::initialize(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::initialize(), mlir::dataflow::AbstractSparseForwardDataFlowAnalysis::initialize(), mlir::dataflow::DeadCodeAnalysis::initialize(), irdlRegionVerifier(), mlir::bytecode::detail::IRNumberingState::IRNumberingState(), mlir::isMemoryEffectFree(), mlir::isSpeculatable(), mlir::ForwardIterator::makeIterable(), AllocaScopeHoister::matchAndRewrite(), mergeIdenticalBlocks(), notifyBlockInsertions(), mlir::bufferization::OneShotAnalysisState::OneShotAnalysisState(), mlir::OperationFingerPrint::OperationFingerPrint(), propagateLiveness(), mlir::bufferization::removeBufferizationAttributesInModule(), mlir::detail::AttrTypeReplacerBase< Concrete >::replaceElementsIn(), mlir::dataflow::RunLivenessAnalysis::RunLivenessAnalysis(), mlir::gpu::transformGpuModulesToBinaries(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::detail::verifySymbolTable(), mlir::detail::verifyTypesAlongControlFlowEdges(), mlir::dataflow::LivenessAnalysis::visitBranchOperand(), mlir::JamBlockGatherer< OpTy >::walk(), mlir::walkAndApplyPatterns(), walkSymbolTable(), mlir::SymbolTable::walkSymbolTables(), walkSymbolUses(), wouldOpBeTriviallyDeadImpl(), and wrapInExecuteRegion().
getRegisteredInfo()
std::optional< RegisteredOperationName > mlir::Operation::getRegisteredInfo () inline
If this operation has a registered operation description, return it.
Otherwise return std::nullopt.
Definition at line 123 of file Operation.h.
References getName(), and mlir::OperationName::getRegisteredInfo().
Referenced by mlir::Op< ConcreteType, Traits >::classof(), getDiscardableAttrs(), getPropertiesAsAttribute(), and setPropertiesFromAttribute().
getResult()
OpResult mlir::Operation::getResult (unsigned idx) inline
Get the 'idx'th result of this operation.
Definition at line 407 of file Operation.h.
Referenced by mlir::affine::affineParallelize(), mlir::tensor::bubbleUpPadSlice(), mlir::sparse_tensor::Merger::buildExp(), buildVectorWrite(), clone(), convertElementwiseOp(), convertMixedValuesToInt(), convertOmpThreadprivate(), convertOperationImpl(), mlir::emitc::createExpression(), mlir::LLVM::detail::createIntrinsicCall(), mlir::vector::createReadOrMaskedRead(), mlir::spirv::Deserializer::processOp< spirv::GenericCastToPtrExplicitOp >(), mlir::op_definition_impl::foldTrait(), fuseWithReshapeByExpansion(), mlir::sparse_tensor::SparseIterator::genNotEnd(), getConsumerFromLoopUses(), mlir::arith::getNeutralElement(), getOpResult(), mlir::OperationFolder::getOrCreateConstant(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResult(), mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getResult(), mlir::tosa::getTosaConstShape(), mlir::nvgpu::getWarpMatrixInfo(), mlir::LLVM::detail::handleMultidimensionalVectors(), inferFragType(), mlir::detail::constant_float_value_binder::match(), mlir::detail::constant_int_value_binder::match(), mlir::detail::infer_int_range_op_binder::match(), matchAndReplaceDepthwiseConv(), DropUnitDimFromElementwiseOps::matchAndRewrite(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), materializeConversion(), mlir::spirv::Deserializer::materializeSpecConstantOperation(), mlir::dataflow::maybeReplaceWithConstant(), movePaddingToFillOrGenericOp(), mlir::OperationFolder::notifyRemoval(), mlir::LLVM::detail::oneToOneRewrite(), mlir::outlineSingleBlockRegion(), mlir::shard::partitionOperation(), printConstantOp(), mlir::OpAsmPrinter::printFunctionalType(), printOneResultOp(), printOperation(), mlir::spirv::Deserializer::processOpWithoutGrammarAttr(), reifyMixedParamAndHandleResults(), reifyOpResultShapes(), mlir::OpTrait::OneResult< ConcreteType >::replaceAllUsesWith(), replaceAndPropagateMemRefType(), replaceForAllWithNewSignature(), mlir::linalg::rewriteInDestinationPassingStyle(), scalarizeVectorOpHelper(), mlir::linalg::splitReduction(), mlir::linalg::splitReductionByScaling(), unpackSingleIndexResultPayloadOperations(), mlir::vector::unrollVectorOp(), vectorizeAsLinalgGeneric(), vectorizeOperand(), mlir::LLVM::detail::vectorOneToOneRewrite(), mlir::spirv::verifyCastOp(), mlir::LLVM::detail::verifyDereferenceableOpInterface(), verifyInitializationAttribute(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::detail::verifyShapedDimOpInterface(), verifyShiftOp(), mlir::OpTrait::tosa::MulOperandsAndResultElementType< ConcreteType >::verifyTrait(), and walkReferenceCountedValues().
getResults()
result_range mlir::Operation::getResults () inline
Definition at line 415 of file Operation.h.
Referenced by addBodyWithPayloadOp(), mlir::transform::TransformState::applyTransform(), mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::linalg::bufferizeToAllocation(), buildVectorWrite(), mlir::transform::detail::checkApplyToOne(), checkFoldResultTypes(), checkPreconditions(), mlir::async::cloneConstantsIntoTheRegion(), collectUnderlyingAddressValues(), mlir::OperationEquivalence::computeHash(), mlir::emitc::createExpression(), mlir::OpBuilder::createOrFold(), mlir::shard::detail::defaultAddShardingAnnotations(), mlir::shard::detail::defaultGetShardingAnnotations(), delinearizeInductionVariable(), mlir::sparse_tensor::LoopEmitter::exitCurrentLoop(), extractBeneficiaryOps(), mlir::impl::foldCastInterfaceOp(), mlir::sparse_tensor::SparseIterator::forward(), forwardToUsers(), mlir::sparse_tensor::SparseIterator::genInit(), getForwardSliceImpl(), getLastDependentOpInRange(), getOpResults(), mlir::tensor::getOrCreateDestinations(), mlir::transform::detail::getParamProducerTransformOpTraitEffects(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResults(), mlir::shard::getResultShardings(), getResultTypes(), getSameBlockUsers(), getSingleRegionOpSuccessorRegions(), getUses(), mlir::sparse_tensor::hasAnyNonIdentityOperandsOrResults(), mlir::sparse_tensor::hasAnySparseResult(), hasBufferSemantics(), mlir::affine::MemRefDependenceGraph::init(), mlir::OperationFolder::insertKnownConstant(), isGuaranteedAutomaticAllocation(), isOpItselfPotentialAutomaticAllocation(), mlir::makeRegionIsolatedFromAbove(), VectorizationState::maskOperation(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::bufferization::OneShotAnalysisState::OneShotAnalysisState(), operandsAndResultsRanked(), mlir::LLVM::detail::opHasUnsupportedFloatingPointTypes(), mlir::shard::partitionFullyReplicatedOperation(), mlir::shard::partitionOperation(), mlir::shard::partitionTriviallyShardableOperation(), mlir::linalg::peelLoop(), mlir::Liveness::print(), mlir::OpAsmPrinter::printFunctionalType(), printFunctionBody(), propagateLiveness(), mlir::reifyResultShapes(), mlir::RewriterBase::replaceAllOpUsesWith(), mlir::RewriterBase::replaceAllOpUsesWith(), replaceAllUsesWith(), mlir::ResultRange::replaceAllUsesWith(), replaceAndPropagateMemRefType(), mlir::detail::AttrTypeReplacerBase< Concrete >::replaceElementsIn(), mlir::detail::ConversionPatternRewriterImpl::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpUsesWithIf(), replaceUsesWithIf(), mlir::ResultRange::replaceUsesWithIf(), result_begin(), result_end(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runDenseBufferization(), mlir::dataflow::RunLivenessAnalysis::RunLivenessAnalysis(), mlir::transform::detail::setApplyToOneResults(), mlir::sinkOperationsIntoLaunchOp(), mlir::dataflow::staticallyNonNegative(), tileAndFuseConsumerOfSlicesImpl(), tileLinalgOpImpl(), transformToStructuredCFBranches(), updateOp(), use_begin(), use_empty(), use_end(), vectorizeAsLinalgGeneric(), mlir::transform::detail::verifyParamProducerTransformOpTrait(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::transform::detail::verifyTransformOpInterface(), mlir::dataflow::LivenessAnalysis::visitBranchOperand(), visitOp(), mlir::dataflow::IntegerRangeAnalysis::visitOperation(), mlir::dataflow::StridedMetadataRangeAnalysis::visitOperation(), widenOp(), wrapInExecuteRegion(), and mlir::transform::TransformState::RegionScope::~RegionScope().
getResultTypes()
result_type_range mlir::Operation::getResultTypes () inline
Definition at line 428 of file Operation.h.
References getResults(), and mlir::ResultRange::getTypes().
Referenced by checkSourceOpTypes(), clone(), mlir::OperationEquivalence::computeHash(), convertElementwiseOp(), mlir::createGpuAsyncRegionPass(), mlir::xegpu::doSCFStructuralTypeConversionWithTensorType(), emit(), emitElementwiseComputation(), equivalenceAnalysis(), getCompressedMaskOp(), mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >::getLoopIteratorTypes(), mlir::spirv::getNativeVectorShape(), getOpToConvert(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResultTypes(), getSubgroupMmaNativeVectorSize(), getTypeConversionFailure(), hasZeroDimVectors(), insertCasts(), mlir::LLVM::detail::intrinsicRewrite(), irdlOpVerifier(), isLegalOp(), isVectorizableLoopBodyWithOpCond(), mlir::LLVM::detail::oneToOneRewrite(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::outlineSingleBlockRegion(), printArithmeticExtendedBinaryOp(), result_type_begin(), result_type_end(), mlir::impl::scalarizeVectorOp(), vectorizeOneOp(), mlir::impl::verifyCastInterfaceOp(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::OpTrait::impl::verifyElementwise(), mlir::detail::verifyInferredResultTypes(), mlir::spirv::verifyIntegerDotProduct(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultRank(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), mlir::OpTrait::tosa::verifyTosaShapeOperator(), mlir::OpTrait::tosa::verifyTosaShapeOperatorWithSameRanks(), walkReferenceCountedValues(), and wrapInExecuteRegion().
getSuccessor()
Block * mlir::Operation::getSuccessor (unsigned index) inline
Definition at line 708 of file Operation.h.
References Block, getBlockOperands(), and getNumSuccessors().
Referenced by eraseTerminatorSuccessorOperands(), getPHISourceValue(), mlir::Block::getSuccessor(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessor(), mlir::OpTrait::OneSuccessor< ConcreteType >::getSuccessor(), mlir::OperationFingerPrint::OperationFingerPrint(), propagateTerminatorLiveness(), and mlir::detail::verifyBranchSuccessorOperands().
getSuccessors()
SuccessorRange mlir::Operation::getSuccessors () inline
Definition at line 703 of file Operation.h.
Referenced by mlir::bufferization::bufferizeBlockSignature(), clone(), mlir::createGpuAsyncRegionPass(), mlir::findReachableBlocks(), mlir::bufferization::BranchOpBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp >::getAliasingValues(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessors(), mlir::OperationEquivalence::isRegionEquivalentTo(), propagateTerminatorLiveness(), successor_begin(), successor_end(), verifyTerminatorSuccessors(), and mlir::dataflow::DeadCodeAnalysis::visit().
getUsers()
user_range mlir::Operation::getUsers () inline
Returns a range of all users.
Definition at line 873 of file Operation.h.
References user_begin(), and user_end().
Referenced by collapseBranch(), createNewAliasScopesFromNoAliasParameter(), extractHostEvalClauses(), mlir::bufferization::findCommonDominator(), findUnusedStore(), fuseIfLegal(), getFirstUserOfLoop(), getLastDependentOpInRange(), getSubgroupMmaNativeVectorSize(), mlir::nvgpu::getUserContract(), hasBindingUse(), hasLifetimeMarkers(), inferFragType(), mlir::affine::MemRefDependenceGraph::init(), mlir::matchReduction(), mlir::moveLoopInvariantCode(), mlir::memref::multiBuffer(), mlir::shard::shardedBlockArgumentTypes(), and visit().
getUses()
use_range mlir::Operation::getUses () inline
Returns a range of all uses, which is useful for iterating over all uses.
Definition at line 846 of file Operation.h.
References getResults(), and mlir::ResultRange::getUses().
Referenced by mlir::bufferization::bufferizeOp(), hasOneUse(), replaceUsesAndPropagateType(), and mlir::memref::resultIsNotRead().
hasAttr() [1/2]
bool mlir::Operation::hasAttr (StringAttr name) inline
Return true if the operation has an attribute with the provided name, false otherwise.
Definition at line 560 of file Operation.h.
References getInherentAttr(), and getPropertiesStorageSize().
Referenced by mlir::impl::SCFForLoopSpecializationBase< DerivedT >::getDependentDialects(), mlir::xegpu::getDistributeLayoutAttr(), mlir::xegpu::getDistributeLayoutAttr(), mlir::acc::isAccRoutine(), isParallelRegionBoundary(), isPureTypeConversion(), mlir::acc::isSpecializedAccRoutine(), mlir::acc::isValidSymbolUse(), mlir::detail::AttrOpMatcher::match(), shouldUseBarePtrCallConv(), and mlir::spirv::verifyIntegerDotProduct().
hasAttr() [2/2]
bool mlir::Operation::hasAttr (StringRef name) inline
Definition at line 567 of file Operation.h.
References getInherentAttr(), and getPropertiesStorageSize().
hasAttrOfType()
template<typename AttrClass, typename NameT> bool mlir::Operation::hasAttrOfType (NameT && name) inline
Definition at line 575 of file Operation.h.
References getAttrOfType().
Referenced by mlir::xegpu::removeLayoutAttr(), and mlir::xegpu::setDistributeLayoutAttr().
hashProperties()
llvm::hash_code Operation::hashProperties ()
Compute a hash for the op properties (if any).
Definition at line 370 of file Operation.cpp.
References getPropertiesStorage().
Referenced by mlir::OperationEquivalence::computeHash(), and mlir::OperationFingerPrint::OperationFingerPrint().
hasOneUse()
bool mlir::Operation::hasOneUse () inline
Returns true if this operation has exactly one use.
Definition at line 849 of file Operation.h.
References getUses().
Referenced by inferFragType(), and mlir::matchReduction().
hasPromiseOrImplementsInterface()
template<typename InterfaceT> bool mlir::Operation::hasPromiseOrImplementsInterface () const inline
Returns true if InterfaceT has been promised by the dialect or implemented.
Definition at line 742 of file Operation.h.
hasSuccessors()
bool mlir::Operation::hasSuccessors () inline
Definition at line 705 of file Operation.h.
Referenced by mlir::bufferization::deallocation_impl::insertDeallocOpForReturnLike().
hasTrait()
template<template< typename T > class Trait> bool mlir::Operation::hasTrait () inline
Returns true if the operation was registered with a particular trait, e.g.
hasTrait<OperandsAreSignlessIntegerLike>().
Definition at line 749 of file Operation.h.
Referenced by AncestorKey::AncestorKey(), mlir::applyPatternsGreedily(), mlir::bufferization::bufferizeModuleOp(), canBeHoisted(), mlir::async::cloneConstantsIntoTheRegion(), mlir::affine::LoopNestStateCollector::collect(), collectEffects(), collectSymbolScopes(), collectValidReferencesFor(), mlir::OperationEquivalence::computeHash(), mlir::nvgpu::createAsyncGroups(), mlir::createGpuEliminateBarriers(), mlir::impl::ensureRegionTerminator(), executeGetOperandsResults(), findCommonAncestor(), findParent(), findParent(), mlir::transform::TrackingListener::findReplacementOp(), mlir::op_definition_impl::foldTrait(), generateLoopNestingName(), getBackwardSliceImpl(), getCommonBlockInAffineScope(), getEffectedValues(), getEffectsBefore(), mlir::getEffectsRecursively(), mlir::affine::getEnclosingAffineOps(), mlir::transform::TransformState::getHandlesForPayloadOp(), mlir::transform::TransformState::getHandlesForPayloadValue(), mlir::LocalAliasAnalysis::getModRef(), mlir::SymbolTable::getNearestSymbolTable(), getOutermostInvariantForOp(), getParentWithTrait(), getSingleTerminatorUse(), mlir::OpTrait::hasElementwiseMappableTraits(), mlir::hasUnknownEffects(), inferFragType(), mlir::DataFlowSolver::initializeAndRun(), mlir::bufferization::deallocation_impl::insertDeallocOpForReturnLike(), mlir::bufferization::insertTensorCopies(), mlir::spirv::isDirectInModuleLikeOp(), isDistinctObjectsOp(), mlir::isLegalForReturnOpTypeConversionPattern(), isLinearizable(), mlir::isMemoryEffectFree(), isMemRefNormalizable(), mlir::spirv::isNestedInFunctionOpInterface(), mlir::spirv::isNestedInGraphARMOpInterface(), isOpItselfPotentialAutomaticAllocation(), isSequentialLoop(), mlir::affine::isTopLevelValue(), isTopLevelValueOrAbove(), isUseSpeciallyKnownDead(), mlir::LLVM::lookupOrCreateFn(), lookupSymbolInImpl(), mlir::detail::constant_op_binder< AttrT >::match(), mlir::detail::constant_op_matcher::match(), AllocaScopeHoister::matchAndRewrite(), SortCommutativeOperands::matchAndRewrite(), mlir::shard::maybeInsertSourceShardingAnnotation(), mlirBlockGetTerminator(), mlir::spirv::Deserializer::processOpWithoutGrammarAttr(), propagateLiveness(), mlir::LLVM::satisfiesLLVMModule(), setDebugIntrinsicBuilderInsertionPoint(), mlir::wasmssa::detail::verifyConstantExpressionInterface(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), mlir::OpTrait::tosa::verifyTosaResolvableShapeOperands(), visitOp(), mlir::dataflow::LivenessAnalysis::visitOperation(), mlir::JamBlockGatherer< OpTy >::walk(), walkSymbolTable(), mlir::SymbolTable::walkSymbolTables(), walkSymbolUses(), and wouldOpBeTriviallyDeadImpl().
insertOperands()
void Operation::insertOperands (unsigned index, ValueRange operands)
Insert the given operands into the operand list at the given 'index'.
Definition at line 256 of file Operation.cpp.
References setOperands().
Referenced by mlir::gpu::addAsyncDependency(), and addExecuteResults().
isAncestor()
bool mlir::Operation::isAncestor (Operation * other) inline
Return true if this operation is an ancestor of the other operation.
An operation is considered as its own ancestor, use isProperAncestor to avoid this.
Definition at line 263 of file Operation.h.
References isProperAncestor().
Referenced by canBeHoisted(), canUseOpDominanceDueToRegions(), collectValidReferencesFor(), dependsOnCarriedVals(), findCommonAncestor(), mlir::affine::hasNoInterveningEffect(), and replaceForAllWithNewSignature().
isBeforeInBlock()
bool Operation::isBeforeInBlock (Operation * other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
Note: This function has an average complexity of O(1), but worst case may take O(N) where N is the number of operations within the parent block.
Definition at line 383 of file Operation.cpp.
Referenced by canRemoveSrcNodeAfterFusion(), mlir::LivenessBlockInfo::currentlyLiveValues(), generateCopy(), mlir::LivenessBlockInfo::getEndOperation(), getFirstUserOfLoop(), getFusedLoopNestInsertionPoint(), happensBefore(), mlir::affine::MemRefDependenceGraph::hasDependencePath(), mlir::Liveness::isDeadAfter(), mlir::bufferization::ValueComparator::operator()(), performReplaceValue(), srcAppearsBeforeDstInAncestralBlock(), and verifyResultTypesAreInferrable().
isProperAncestor()
bool Operation::isProperAncestor (Operation * other)
Return true if this operation is a proper ancestor of the other operation.
Definition at line 219 of file Operation.cpp.
References getParentOp().
Referenced by mlir::LocalAliasAnalysis::aliasImpl(), cloneAndFuseFirstUse(), findCommonAncestor(), happensBefore(), happensBefore(), isAncestor(), and mlir::AnalysisManager::nest().
isRegistered()
bool mlir::Operation::isRegistered () inline
Returns true if this operation has a registered operation description, otherwise false.
Definition at line 129 of file Operation.h.
References getName(), and mlir::OperationName::isRegistered().
Referenced by mlir::mayBeGraphRegion().
isUsedOutsideOfBlock()
bool mlir::Operation::isUsedOutsideOfBlock (Block * block) inline
Returns true if the results of this operation are used outside of the given block.
Definition at line 856 of file Operation.h.
References Block, getOpResults(), and result.
mightHaveTrait()
template<template< typename T > class Trait> bool mlir::Operation::mightHaveTrait () inline
Returns true if the operation might have the provided trait.
This means that either the operation is unregistered, or it was registered with the provide trait.
Definition at line 757 of file Operation.h.
Referenced by create(), ensureDistinctSuccessors(), mlir::linalg::detail::isContractionBody(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), mlir::matchReduction(), mayBeValidWithoutTerminator(), mlir::Block::mightHaveTerminator(), mlir::memref::resultIsNotRead(), and mlir::wouldOpBeTriviallyDead().
moveAfter() [1/2]
void Operation::moveAfter (Block * block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right after iterator in the specified block.
Definition at line 572 of file Operation.cpp.
References Block, and moveBefore().
moveAfter() [2/2]
void Operation::moveAfter (Operation * existingOp)
Unlink this operation from its current block and insert it right after existingOp which may be in the same or another block in the same function.
Definition at line 566 of file Operation.cpp.
References getBlock(), and moveAfter().
Referenced by moveAfter().
moveBefore() [1/2]
void Operation::moveBefore (Block * block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right before iterator in the specified block.
Unlink this operation from its current basic block and insert it right before iterator in the specified basic block.
Definition at line 556 of file Operation.cpp.
References Block, and getBlock().
moveBefore() [2/2]
void Operation::moveBefore (Operation * existingOp)
Unlink this operation from its current block and insert it right before existingOp which may be in the same or another block in the same function.
Definition at line 550 of file Operation.cpp.
References getBlock(), and moveBefore().
Referenced by mlir::OperationFolder::insertKnownConstant(), SinkVectorProducerOps< producerOp >::matchAndRewrite(), moveAfter(), moveBefore(), moveFuncDeclarationsToTop(), mlir::RewriterBase::moveOpBefore(), mlir::sortTopologically(), and mlir::OperationFolder::tryToFold().
operand_begin()
operand_iterator mlir::Operation::operand_begin () inline
Definition at line 374 of file Operation.h.
References getOperands().
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_begin(), and operand_type_begin().
operand_end()
operand_iterator mlir::Operation::operand_end () inline
Definition at line 375 of file Operation.h.
References getOperands().
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_end(), and operand_type_end().
operand_type_begin()
operand_type_iterator mlir::Operation::operand_type_begin () inline
Definition at line 395 of file Operation.h.
References operand_begin().
Referenced by getElementalFuncTypeForOp(), and mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_type_begin().
operand_type_end()
operand_type_iterator mlir::Operation::operand_type_end () inline
Definition at line 396 of file Operation.h.
References operand_end().
Referenced by getElementalFuncTypeForOp(), and mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_type_end().
populateDefaultAttrs()
void mlir::Operation::populateDefaultAttrs () inline
Sets default attributes on unset attributes.
Definition at line 663 of file Operation.h.
References getAttrDictionary(), getContext(), and setAttrs().
Referenced by create().
print() [1/2]
void Operation::print (raw_ostream & os, AsmState & state)
Definition at line 4123 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl(), mlir::AsmState::getPrinterFlags(), mlir::detail::AsmStateImpl::initializeAliases(), and mlir::OpPrintingFlags::shouldUseLocalScope().
print() [2/2]
void Operation::print (raw_ostream & os, const OpPrintingFlags & flags = {})
Definition at line 4117 of file AsmPrinter.cpp.
References findParent(), print(), and mlir::OpPrintingFlags::shouldUseLocalScope().
Referenced by mlir::Diagnostic::appendOp(), appendReproducer(), doVerifyRoundTrip(), generateLocationsFromIR(), is2To4Sparsity(), mlir::OpWithFlags::operator<<, mlir::OpWithState::operator<<, mlir::Liveness::print(), mlir::Value::print(), mlir::Value::print(), printIR(), printOp(), and mlir::spirv::Deserializer::wireUpBlockArgument().
remove()
void Operation::remove ()
Remove the operation from its parent block, but don't delete it.
Definition at line 542 of file Operation.cpp.
References Block, and getBlock().
Referenced by mlir::nvgpu::createAsyncGroups(), and transformCyclesToSCFLoops().
removeAttr() [1/2]
Attribute mlir::Operation::removeAttr (StringAttr name) inline
Remove the attribute with the specified name if it exists.
Return the attribute that was erased, or nullptr if there was no attribute with such name.
Definition at line 600 of file Operation.h.
References mlir::NamedAttrList::erase(), getContext(), mlir::NamedAttrList::getDictionary(), getInherentAttr(), getPropertiesStorageSize(), and setInherentAttr().
Referenced by removeAttr(), mlir::xegpu::removeLayoutAttr(), and mlir::SymbolTable::setSymbolVisibility().
removeAttr() [2/2]
Attribute mlir::Operation::removeAttr (StringRef name) inline
Definition at line 613 of file Operation.h.
References getContext(), and removeAttr().
removeDiscardableAttr() [1/2]
Attribute mlir::Operation::removeDiscardableAttr (StringAttr name) inline
Remove the discardable attribute with the specified name if it exists.
Return the attribute that was erased, or nullptr if there was no attribute with such name.
Definition at line 472 of file Operation.h.
References mlir::NamedAttrList::erase(), getContext(), and mlir::NamedAttrList::getDictionary().
Referenced by removeDiscardableAttr().
removeDiscardableAttr() [2/2]
Attribute mlir::Operation::removeDiscardableAttr (StringRef name) inline
Definition at line 479 of file Operation.h.
References getContext(), and removeDiscardableAttr().
replaceAllUsesWith()
template<typename ValuesT> void mlir::Operation::replaceAllUsesWith (ValuesT && values) inline
Replace all uses of results of this operation with the provided 'values'.
Definition at line 272 of file Operation.h.
References getResults(), and mlir::ResultRange::replaceAllUsesWith().
Referenced by mlir::createGpuAsyncRegionPass(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::replaceAllUsesWith(), mlir::OpTrait::OneResult< ConcreteType >::replaceAllUsesWith(), and transformToStructuredCFBranches().
replaceUsesOfWith()
void Operation::replaceUsesOfWith (Value from, Value to)
Replace any uses of 'from' with 'to' within this operation.
Definition at line 227 of file Operation.cpp.
References getOpOperands(), and Value.
Referenced by mlir::inlineCall(), and replaceConstantUsesOf().
replaceUsesWithIf()
template<typename ValuesT> void mlir::Operation::replaceUsesWithIf (ValuesT && values, function_ref< bool(OpOperand &)> shouldReplace) inline
Replace uses of results of this operation with the provided values if the given callback returns true.
Definition at line 279 of file Operation.h.
References getResults(), and mlir::ResultRange::replaceUsesWithIf().
result_begin()
result_iterator mlir::Operation::result_begin () inline
Definition at line 413 of file Operation.h.
References getResults().
Referenced by mlir::query::extractFunction(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_begin().
result_end()
result_iterator mlir::Operation::result_end () inline
Definition at line 414 of file Operation.h.
References getResults().
Referenced by mlir::query::extractFunction(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_end().
result_type_begin()
result_type_iterator mlir::Operation::result_type_begin () inline
Definition at line 426 of file Operation.h.
References getResultTypes().
Referenced by getElementalFuncTypeForOp(), mlir::OperationFolder::insertKnownConstant(), materializeConversion(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_type_begin().
result_type_end()
result_type_iterator mlir::Operation::result_type_end () inline
Definition at line 427 of file Operation.h.
References getResultTypes().
Referenced by getElementalFuncTypeForOp(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_type_end().
setAttr() [1/2]
void mlir::Operation::setAttr (StringAttr name, Attribute value) inline
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 582 of file Operation.h.
References getContext(), mlir::NamedAttrList::getDictionary(), getInherentAttr(), getPropertiesStorageSize(), mlir::NamedAttrList::set(), and setInherentAttr().
Referenced by mlir::gpu::addAsyncDependency(), annotateConflict(), annotateOpsWithAliasSets(), matchAndReplaceDepthwiseConv(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), TargetToTargetFeaturesPass::runOnOperation(), setAttr(), mlir::xegpu::setDistributeLayoutAttr(), setInPlaceOpOperand(), setMmraAttr(), mlir::SymbolTable::setSymbolName(), mlir::SymbolTable::setSymbolVisibility(), and updateVisibility().
setAttr() [2/2]
void mlir::Operation::setAttr (StringRef name, Attribute value) inline
Definition at line 593 of file Operation.h.
References getContext(), and setAttr().
setAttrs() [1/2]
void Operation::setAttrs (ArrayRef< NamedAttribute > newAttrs)
Definition at line 323 of file Operation.cpp.
References getContext(), getInherentAttr(), getPropertiesStorageSize(), and setInherentAttr().
setAttrs() [2/2]
void Operation::setAttrs (DictionaryAttr newAttrs)
Set the attributes from a dictionary on this operation.
These methods are expensive: if the dictionary only contains discardable attributes, setDiscardableAttrs is more efficient.
Definition at line 305 of file Operation.cpp.
References getContext(), getInherentAttr(), getPropertiesStorageSize(), and setInherentAttr().
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), create(), populateDefaultAttrs(), mlir::detail::AttrTypeReplacerBase< Concrete >::replaceElementsIn(), setDialectAttrs(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
setDialectAttrs()
template<typename DialectAttrT> void mlir::Operation::setDialectAttrs (DialectAttrT && dialectAttrs) inline
Set the dialect attributes for this operation, and preserve all inherent.
Definition at line 653 of file Operation.h.
References mlir::NamedAttrList::append(), getAttrs(), getContext(), and setAttrs().
setDiscardableAttr() [1/2]
void mlir::Operation::setDiscardableAttr (StringAttr name, Attribute value) inline
Set a discardable attribute by name.
Definition at line 460 of file Operation.h.
References getContext(), mlir::NamedAttrList::getDictionary(), and mlir::NamedAttrList::set().
Referenced by setDiscardableAttr().
setDiscardableAttr() [2/2]
void mlir::Operation::setDiscardableAttr (StringRef name, Attribute value) inline
Definition at line 465 of file Operation.h.
References getContext(), and setDiscardableAttr().
setDiscardableAttrs() [1/2]
void mlir::Operation::setDiscardableAttrs (ArrayRef< NamedAttribute > newAttrs) inline
Definition at line 527 of file Operation.h.
References getContext(), and setDiscardableAttrs().
setDiscardableAttrs() [2/2]
void mlir::Operation::setDiscardableAttrs (DictionaryAttr newAttrs) inline
Set the discardable attribute dictionary on this operation.
Definition at line 523 of file Operation.h.
Referenced by propagateLoopAttrs(), and setDiscardableAttrs().
setInherentAttr()
void Operation::setInherentAttr (StringAttr name, Attribute value)
Set an inherent attribute by name.
This method is available as a transient facility in the migration process to use Properties instead.
Definition at line 345 of file Operation.cpp.
References getName(), and mlir::OperationName::setInherentAttr().
Referenced by removeAttr(), setAttr(), setAttrs(), and setAttrs().
setLoc()
void mlir::Operation::setLoc (Location loc) inline
Set the source location the operation was defined or derived from.
Definition at line 226 of file Operation.h.
Referenced by generateLocationsFromIR(), mlir::OperationFolder::insertKnownConstant(), mlir::detail::AttrTypeReplacerBase< Concrete >::replaceElementsIn(), setLexicalBlockFileAttr(), and mlir::OperationFolder::tryToFold().
setOperand()
void mlir::Operation::setOperand (unsigned idx, Value value) inline
Definition at line 351 of file Operation.h.
References getOpOperand(), mlir::IROperand< DerivedT, IRValueT >::set(), and Value.
Referenced by mlir::bufferization::eliminateEmptyTensors(), foldInsertUseChain(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::setOperand(), mlir::OpTrait::OneOperand< ConcreteType >::setOperand(), mlir::linalg::splitReduction(), mlir::linalg::splitReductionByScaling(), and tileAndFuseFirstExtractUseThroughContainingOpBlockArgument().
setOperands() [1/2]
void Operation::setOperands (unsigned start, unsigned length, ValueRange operands)
Replace the operands beginning at 'start' and ending at 'start' + 'length' with the ones provided in 'operands'.
'operands' may be smaller or larger than the range pointed to by 'start'+'length'.
Definition at line 246 of file Operation.cpp.
References getNumOperands().
setOperands() [2/2]
void Operation::setOperands (ValueRange operands)
Replace the current operands of this operation with the ones provided in 'operands'.
Definition at line 237 of file Operation.cpp.
Referenced by mlir::affine::affineParallelize(), generateUnrolledLoop(), mlir::generateUnrolledLoop(), insertOperands(), SortCommutativeOperands::matchAndRewrite(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
setPropertiesFromAttribute()
LogicalResult Operation::setPropertiesFromAttribute (Attribute attr, function_ref< InFlightDiagnostic()> emitError)
Set the properties from the provided attribute.
This is an expensive operation that can fail if the attribute is not matching the expectations of the properties for this operation. This is mostly useful for unregistered operations or used when parsing the generic format. An optional diagnostic emitter can be passed in for richer errors, if none is passed then behavior is undefined in error case.
Definition at line 355 of file Operation.cpp.
References mlir::OpaqueProperties::as(), emitError(), getName(), getPropertiesStorage(), getRegisteredInfo(), and success().
Referenced by create(), and mlir::OperationState::setProperties().
setSuccessor()
void Operation::setSuccessor (Block * block, unsigned index)
Definition at line 602 of file Operation.cpp.
References Block, getBlockOperands(), and getNumSuccessors().
Referenced by mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::setSuccessor(), and mlir::OpTrait::OneSuccessor< ConcreteType >::setSuccessor().
successor_begin()
succ_iterator mlir::Operation::successor_begin () inline
Definition at line 701 of file Operation.h.
References getSuccessors().
successor_end()
succ_iterator mlir::Operation::successor_end () inline
Definition at line 702 of file Operation.h.
References getSuccessors().
use_begin()
use_iterator mlir::Operation::use_begin () inline
Definition at line 842 of file Operation.h.
References getResults(), and mlir::ResultRange::use_begin().
Referenced by user_begin().
use_empty()
bool mlir::Operation::use_empty () inline
Returns true if this operation has no uses.
Definition at line 852 of file Operation.h.
References getResults(), and mlir::ResultRange::use_empty().
Referenced by mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), getConsumerFromLoopUses(), mlir::isOpTriviallyDead(), and isResultValueDead().
use_end()
use_iterator mlir::Operation::use_end () inline
Definition at line 843 of file Operation.h.
References getResults(), and mlir::ResultRange::use_end().
Referenced by user_end().
user_begin()
user_iterator mlir::Operation::user_begin () inline
Definition at line 869 of file Operation.h.
References use_begin().
Referenced by getUsers(), and inferFragType().
user_end()
user_iterator mlir::Operation::user_end () inline
Definition at line 870 of file Operation.h.
References use_end().
Referenced by getUsers().
walk() [1/2]
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename RetT = detail::walkResultType<FnT>> std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==1, RetT > mlir::Operation::walk (FnT && callback) inline
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
The order in which regions, blocks and operations at the same nesting level are visited (e.g., lexicographical or reverse lexicographical order) is determined by 'Iterator'. The walk order for enclosing regions, blocks and operations with respect to their nested ones is specified by 'Order' (post-order by default). A callback on a block or operation is allowed to erase that block or operation if either:
the walk is in post-order, or
the walk is in pre-order and the walk is skipped after the erasure.
The callback method can take any of the following forms: void(Operation*) : Walk all operations opaquely.
op->walk([](Operation nestedOp) { ...}); void(OpT) : Walk all operations of the given derived type.
op->walk([](ReturnOp returnOp) { ...}); WalkResult(Operation|OpT) : Walk operations, but allow for interruption/skipping.
op->walk([](... op) { // Skip the walk of this op based on some invariant. if (some_invariant) return WalkResult::skip(); // Interrupt, i.e cancel, the walk based on some invariant. if (another_invariant) return WalkResult::interrupt(); return WalkResult::advance(); });
Definition at line 797 of file Operation.h.
References mlir::detail::walk().
Referenced by mlir::bufferization::analyzeOp(), mlir::bufferization::OneShotAnalysisState::analyzeOp(), annotateOpsWithAliasSets(), annotateOpsWithBufferizationMarkers(), bottomUpFromTerminatorsHeuristic(), mlir::bufferization::bufferizeOp(), mlir::linalg::bufferizeToAllocation(), buildBlockMapping(), canBeHoisted(), checkPreBufferizationAssumptions(), mlir::affine::LoopNestStateCollector::collect(), mlir::query::matcher::MatchFinder::collectMatches(), constructIsCancellable(), mlir::OperationConverter::convertOperations(), convertTargetOpsInNest(), mlir::nvgpu::createAsyncGroups(), mlir::transform::createCheckUsesPass(), mlir::createGpuEliminateBarriers(), mlir::DataLayoutAnalysis::DataLayoutAnalysis(), mlir::LLVM::detail::DebugTranslation::DebugTranslation(), mlir::xegpu::doSCFStructuralTypeConversionWithTensorType(), mlir::bufferization::eliminateEmptyTensors(), mlir::LLVM::ensureDistinctSuccessors(), equivalenceAnalysis(), mlir::memref::eraseDeadAllocAndStores(), mlir::finalizeParallelLoopToGPUConversion(), findCapturedOmpOp(), findPayloadRoot(), findTransformEntryPointRecursive(), mlir::bufferization::OneShotAnalysisState::gatherUndefinedTensorUses(), generateLocationsFromIR(), getFirstDependentOpInRange(), getLastDependentOpInRange(), getLoadAndStoreMemRefAccesses(), getOpToConvert(), getShmReadAndWriteOps(), hoistAffineIfOp(), mlir::linalg::hoistRedundantVectorBroadcasts(), mlir::linalg::hoistRedundantVectorTransfers(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::initializeEquivalentLatticeAnchor(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::initializeEquivalentLatticeAnchor(), mlir::bufferization::insertTensorCopies(), isOpReady(), mlir::linalg::linalgOpAnchoredEmptyTensorEliminationStep(), mlir::affine::NestedPattern::match(), mlir::bufferization::OneShotAnalysisState::OneShotAnalysisState(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), mlir::populateConversionTargetFromOperation(), printFunctionBody(), mlir::detail::AttrTypeReplacerBase< Concrete >::recursivelyReplaceElementsIn(), mlir::xegpu::removeLayoutAttrs(), mlir::detail::ConversionPatternRewriterImpl::replaceOp(), mlir::dataflow::RunLivenessAnalysis::RunLivenessAnalysis(), mlir::xegpu::setDistributeLayoutAttrs(), and walkReferenceCountedValues().
walk() [2/2]
template<typename FnT, typename RetT = detail::walkResultType<FnT>> std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==2, RetT > mlir::Operation::walk (FnT && callback) inline
Generic walker with a stage aware callback.
Walk the operation by calling the callback for each nested operation (including this one) N+1 times, where N is the number of regions attached to that operation.
The callback method can take any of the following forms: void(Operation <em>, const WalkStage &) : Walk all operation opaquely
op->walk([](Operation *nestedOp, const WalkStage &stage) { ...}); void(OpT, const WalkStage &) : Walk all operations of the given derived type.
op->walk([](ReturnOp returnOp, const WalkStage &stage) { ...}); WalkResult(Operation
|OpT, const WalkStage &stage) : Walk operations, but allow for interruption/skipping.
op->walk([](... op, const WalkStage &stage) { // Skip the walk of this op based on some invariant. if (some_invariant) return WalkResult::skip(); // Interrupt, i.e cancel, the walk based on some invariant. if (another_invariant) return WalkResult::interrupt(); return WalkResult::advance(); });
Definition at line 825 of file Operation.h.
References mlir::detail::walk().
Friends And Related Symbol Documentation
Block
friend class Block friend
Definition at line 1076 of file Operation.h.
References Block.
Referenced by Block, clone(), getBlock(), getSuccessor(), isUsedOutsideOfBlock(), llvm::ilist_node_with_parent< Operation, Block >, moveAfter(), moveBefore(), remove(), and setSuccessor().
llvm::ilist_node_with_parent< Operation, Block >
friend class llvm::ilist_node_with_parent< Operation, Block > friend
Definition at line 1079 of file Operation.h.
References Block, and Value.
llvm::ilist_traits< Operation >
friend struct llvm::ilist_traits< Operation > friend
Definition at line 1070 of file Operation.h.
Value
friend class Value friend
Definition at line 1079 of file Operation.h.
Referenced by getOperand(), llvm::ilist_node_with_parent< Operation, Block >, replaceUsesOfWith(), and setOperand().
The documentation for this class was generated from the following files:
include/mlir/IR/Operation.h
lib/IR/AsmPrinter.cpp
lib/IR/Operation.cpp