MLIR: mlir::ElementsAttr Class Reference
mlir::ElementsAttr Class Reference
A base attribute that represents a reference to a static shaped tensor or vector constant.
#include "mlir/IR/BuiltinAttributes.h"
Public Types
template<typename T >
using iterator = detail::ElementsAttrIterator< T >
template<typename T >
using iterator_range = detail::ElementsAttrRange< T >
Public Types inherited from mlir::Attribute
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using AttrBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
Utility class for implementing attributes.
using ImplType = AttributeStorage
using ValueType = void
using AbstractTy = AbstractAttribute
Public Member Functions
ShapedType getType () const
Return the type of this ElementsAttr, guaranteed to be a vector or tensor with static shape.
Attribute getValue (ArrayRef< uint64_t > index) const
Return the value at the given index.
template<typename T >
T getValue (ArrayRef< uint64_t > index) const
Return the value of type 'T' at the given index, where 'T' corresponds to an Attribute type.
template<typename T >
iterator_range< T > getValues () const
Return the elements of this attribute as a value of type 'T'.
bool isValidIndex (ArrayRef< uint64_t > index) const
Return if the given 'index' refers to a valid element in this attribute.
int64_t getNumElements () const
Returns the number of elements held by this attribute.
int64_t size () const
Returns the number of elements held by this attribute.
bool empty () const
Returns if the number of elements held by this attribute is 0.
ElementsAttr mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new ElementsAttr by mapping each int value to a new underlying APInt.
ElementsAttr mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new ElementsAttr by mapping each float value to a new underlying APInt.
template<typename T >
auto getValues () const -> iterator_range< T >
Return the elements of this attribute as a value of type 'T'.
Public Member Functions inherited from mlir::Attribute
constexpr Attribute ()
Attribute (const ImplType *impl)
Attribute (const Attribute &other)=default
Attribute & operator= (const Attribute &other)=default
bool operator== (Attribute other) const
bool operator!= (Attribute other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete attribute type.
Type getType () const
Return the type of this attribute.
MLIRContext * getContext () const
Return the context this attribute belongs to.
Dialect & getDialect () const
Get the dialect this attribute is registered to.
void print (raw_ostream &os) const
Print the attribute.
void dump () const
const void * getAsOpaquePointer () const
Get an opaque pointer to the attribute.
const AbstractTy & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static bool classof (Attribute attr)
Method for support type inquiry through isa, cast and dyn_cast.
Static Public Member Functions inherited from mlir::Attribute
static bool classof (Attribute)
static Attribute getFromOpaquePointer (const void *ptr)
Construct an attribute from the opaque pointer representation.
Protected Member Functions
uint64_t getFlattenedIndex (ArrayRef< uint64_t > index) const
Returns the 1 dimensional flattened row-major index from the given multi-dimensional index.
Additional Inherited Members
Protected Attributes inherited from mlir::Attribute
ImplType * impl
Detailed Description
A base attribute that represents a reference to a static shaped tensor or vector constant.
Definition at line 39 of file BuiltinAttributes.h.
Member Typedef Documentation
iterator
template<typename T > using mlir::ElementsAttr::iterator = detail::ElementsAttrIterator<T>
Definition at line 42 of file BuiltinAttributes.h.
iterator_range
template<typename T > using mlir::ElementsAttr::iterator_range = detail::ElementsAttrRange<T>
Definition at line 43 of file BuiltinAttributes.h.
Member Function Documentation
classof()
bool ElementsAttr::classof (Attribute attr) static
Method for support type inquiry through isa, cast and dyn_cast.
Definition at line 428 of file BuiltinAttributes.cpp.
References mlir::Attribute::isa().
empty()
bool mlir::ElementsAttr::empty () const inline
Returns if the number of elements held by this attribute is 0.
Definition at line 74 of file BuiltinAttributes.h.
getFlattenedIndex()
uint64_t ElementsAttr::getFlattenedIndex (ArrayRef< uint64_t > index) const protected
Returns the 1 dimensional flattened row-major index from the given multi-dimensional index.
Definition at line 435 of file BuiltinAttributes.cpp.
getNumElements()
int64_t ElementsAttr::getNumElements () const
Returns the number of elements held by this attribute.
Definition at line 378 of file BuiltinAttributes.cpp.
Referenced by mlir::OpPrintingFlags::shouldElideElementsAttr().
getType()
ShapedType ElementsAttr::getType () const
Return the type of this ElementsAttr, guaranteed to be a vector or tensor with static shape.
Definition at line 373 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), and mlir::Attribute::getType().
Referenced by fuseWithReshapeByExpansion(), mlir::DenseElementsAttr::BoolElementIterator::operator*(), mlir::DenseElementsAttr::IntElementIterator::operator*(), and mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >().
getValue() [1/2]
Attribute ElementsAttr::getValue (ArrayRef< uint64_t > index) const
Return the value at the given index.
The index is expected to refer to a valid element.
If index does not refer to a valid element, then a null attribute is returned.
Definition at line 384 of file BuiltinAttributes.cpp.
Referenced by verify().
getValue() [2/2]
template<typename T > T mlir::ElementsAttr::getValue (ArrayRef< uint64_t > index) const inline
Return the value of type 'T' at the given index, where 'T' corresponds to an Attribute type.
Definition at line 55 of file BuiltinAttributes.h.
getValues() [1/2]
template<typename T > iterator_range<T> mlir::ElementsAttr::getValues () const
Return the elements of this attribute as a value of type 'T'.
Note: Aborts if the subclass is OpaqueElementsAttrs, these attrs do not support iteration.
Referenced by mlir::constFoldBinaryOp().
getValues() [2/2]
template<typename T > auto mlir::ElementsAttr::getValues () const -> iterator_range<T>
Return the elements of this attribute as a value of type 'T'.
Definition at line 915 of file BuiltinAttributes.h.
isValidIndex()
bool ElementsAttr::isValidIndex (ArrayRef< uint64_t > index) const
Return if the given 'index' refers to a valid element in this attribute.
Definition at line 393 of file BuiltinAttributes.cpp.
mapValues() [1/2]
ElementsAttr ElementsAttr::mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new ElementsAttr by mapping each int value to a new underlying APInt.
The new values can represent either an integer or float. This ElementsAttr should contain integers.
Definition at line 412 of file BuiltinAttributes.cpp.
References mapValues().
Referenced by mapValues().
mapValues() [2/2]
ElementsAttr ElementsAttr::mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new ElementsAttr by mapping each float value to a new underlying APInt.
The new values can represent either an integer or float. This ElementsAttr should contain floats.
Definition at line 420 of file BuiltinAttributes.cpp.
References mapValues().
size()
int64_t mlir::ElementsAttr::size () const inline
Returns the number of elements held by this attribute.
Definition at line 71 of file BuiltinAttributes.h.
Referenced by verify().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinAttributes.h
lib/IR/BuiltinAttributes.cpp