MLIR: mlir::sparse_tensor::ir_detail::DimLvlMap Class Reference
mlir::sparse_tensor::ir_detail::DimLvlMap Class Reference final
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
DimLvlMap (unsigned symRank, ArrayRef< DimSpec > dimSpecs, ArrayRef< LvlSpec > lvlSpecs)
unsigned getSymRank () const
unsigned getDimRank () const
unsigned getLvlRank () const
unsigned getRank (VarKind vk) const
Ranks getRanks () const
ArrayRef< DimSpec > getDims () const
const DimSpec & getDim (Dimension dim) const
SparseTensorDimSliceAttr getDimSlice (Dimension dim) const
ArrayRef< LvlSpec > getLvls () const
const LvlSpec & getLvl (Level lvl) const
LevelType getLvlType (Level lvl) const
AffineMap getDimToLvlMap (MLIRContext *context) const
AffineMap getLvlToDimMap (MLIRContext *context) const
Detailed Description
Definition at line 230 of file DimLvlMap.h.
Constructor & Destructor Documentation
DimLvlMap()
DimLvlMap::DimLvlMap (unsigned symRank, ArrayRef< DimSpec > dimSpecs, ArrayRef< LvlSpec > lvlSpecs)
Definition at line 80 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::VarSet::add(), mlir::sparse_tensor::ir_detail::VarSet::contains(), false, and getRanks().
Member Function Documentation
getDim()
const DimSpec & mlir::sparse_tensor::ir_detail::DimLvlMap::getDim (Dimension dim) const inline
Definition at line 242 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Dimension.
Referenced by getDimSlice().
getDimRank()
unsigned mlir::sparse_tensor::ir_detail::DimLvlMap::getDimRank () const inline
Definition at line 236 of file DimLvlMap.h.
Referenced by getDimToLvlMap(), getLvlToDimMap(), and getRanks().
getDims()
ArrayRef< DimSpec > mlir::sparse_tensor::ir_detail::DimLvlMap::getDims () const inline
Definition at line 241 of file DimLvlMap.h.
getDimSlice()
SparseTensorDimSliceAttr mlir::sparse_tensor::ir_detail::DimLvlMap::getDimSlice (Dimension dim) const inline
Definition at line 243 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Dimension, getDim(), and mlir::sparse_tensor::ir_detail::DimSpec::getSlice().
getDimToLvlMap()
AffineMap DimLvlMap::getDimToLvlMap (MLIRContext * context) const
Definition at line 118 of file DimLvlMap.cpp.
References mlir::AffineMap::get(), getDimRank(), getLvlRank(), and getSymRank().
getLvl()
const LvlSpec & mlir::sparse_tensor::ir_detail::DimLvlMap::getLvl (Level lvl) const inline
Definition at line 248 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Level.
Referenced by getLvlType().
getLvlRank()
unsigned mlir::sparse_tensor::ir_detail::DimLvlMap::getLvlRank () const inline
Definition at line 237 of file DimLvlMap.h.
Referenced by getDimToLvlMap(), getLvlToDimMap(), and getRanks().
getLvls()
ArrayRef< LvlSpec > mlir::sparse_tensor::ir_detail::DimLvlMap::getLvls () const inline
Definition at line 247 of file DimLvlMap.h.
getLvlToDimMap()
AffineMap DimLvlMap::getLvlToDimMap (MLIRContext * context) const
Definition at line 127 of file DimLvlMap.cpp.
References mlir::AffineMap::get(), getDimRank(), getLvlRank(), and getSymRank().
getLvlType()
LevelType mlir::sparse_tensor::ir_detail::DimLvlMap::getLvlType (Level lvl) const inline
Definition at line 249 of file DimLvlMap.h.
References getLvl(), mlir::sparse_tensor::ir_detail::LvlSpec::getType(), and mlir::sparse_tensor::ir_detail::Level.
getRank()
unsigned mlir::sparse_tensor::ir_detail::DimLvlMap::getRank (VarKind vk) const inline
Definition at line 238 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Ranks::getRank(), and getRanks().
getRanks()
Ranks mlir::sparse_tensor::ir_detail::DimLvlMap::getRanks () const inline
Definition at line 239 of file DimLvlMap.h.
References getDimRank(), getLvlRank(), and getSymRank().
Referenced by DimLvlMap(), and getRank().
getSymRank()
unsigned mlir::sparse_tensor::ir_detail::DimLvlMap::getSymRank () const inline
Definition at line 235 of file DimLvlMap.h.
Referenced by getDimToLvlMap(), getLvlToDimMap(), and getRanks().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.cpp