MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults Class Reference
Public Member Functions
PyTransformResults (MlirTransformResults results)
MlirTransformResults get () const
void setOps (PyValue &result, const nb::typed< nb::sequence, PyOperationBase > &ops)
void setValues (PyValue &result, const nb::typed< nb::sequence, PyValue > &values)
void setParams (PyValue &result, const nb::typed< nb::sequence, PyAttribute > &params)
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 43 of file DialectTransform.cpp.
Constructor & Destructor Documentation
PyTransformResults()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::PyTransformResults (MlirTransformResults results) inline
Definition at line 45 of file DialectTransform.cpp.
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::bind (nanobind::module_ & m) inline static
Definition at line 81 of file DialectTransform.cpp.
References setOps(), setParams(), and setValues().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::populateDialectTransformSubmodule().
get()
MlirTransformResults mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::get () const inline
Definition at line 47 of file DialectTransform.cpp.
setOps()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::setOps (PyValue & result, const nb::typed< nb::sequence, PyOperationBase > & ops) inline
Definition at line 49 of file DialectTransform.cpp.
References mlirTransformResultsSetOps(), and result.
Referenced by bind().
setParams()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::setParams (PyValue & result, const nb::typed< nb::sequence, PyAttribute > & params) inline
Definition at line 70 of file DialectTransform.cpp.
References mlirTransformResultsSetParams(), and result.
Referenced by bind().
setValues()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::setValues (PyValue & result, const nb::typed< nb::sequence, PyValue > & values) inline
Definition at line 59 of file DialectTransform.cpp.
References mlirTransformResultsSetValues(), and result.
Referenced by bind().
The documentation for this class was generated from the following file:
lib/Bindings/Python/DialectTransform.cpp