MLIR: mlir::lsp::Logger Class Reference
mlir::lsp::Logger Class Reference
This class represents the main interface for logging, and allows for filtering logging based on different levels of severity or significance.
#include "mlir/Tools/lsp-server-support/Logging.h"
Public Types
enum class Level { Debug , Info , Error }
The level of significance for a log message.
Static Public Member Functions
static void setLogLevel (Level logLevel)
Set the severity level of the logger.
template<typename... Ts>
static void debug (const char *fmt, Ts &&...vals)
Initiate a log message at various severity levels.
template<typename... Ts>
static void info (const char *fmt, Ts &&...vals)
template<typename... Ts>
static void error (const char *fmt, Ts &&...vals)
Detailed Description
This class represents the main interface for logging, and allows for filtering logging based on different levels of severity or significance.
Definition at line 23 of file Logging.h.
Member Enumeration Documentation
Level
enum mlir::lsp::Logger::Level strong
The level of significance for a log message.
Enumerator
Debug
Info
Error
Definition at line 26 of file Logging.h.
Member Function Documentation
debug()
template<typename... Ts> static void mlir::lsp::Logger::debug (const char * fmt, Ts &&... vals) inline static
Initiate a log message at various severity levels.
These should be called after a call to initialize.
Definition at line 34 of file Logging.h.
References Debug.
error()
template<typename... Ts> static void mlir::lsp::Logger::error (const char * fmt, Ts &&... vals) inline static
Definition at line 42 of file Logging.h.
References Error.
Referenced by getLocationFromLoc(), getURIFromLoc(), mlir::lsp::MessageHandler::onReply(), mlir::lsp::JSONTransport::run(), mlir::lsp::runMlirLSPServer(), mlir::lsp::runPdllLSPServer(), and mlir::lsp::runTableGenLSPServer().
info()
template<typename... Ts> static void mlir::lsp::Logger::info (const char * fmt, Ts &&... vals) inline static
Definition at line 38 of file Logging.h.
References Info.
Referenced by mlir::lsp::MessageHandler::onCall(), mlir::lsp::MessageHandler::onNotify(), mlir::lsp::MessageHandler::onReply(), mlir::lsp::MessageHandler::outgoingNotification(), and mlir::lsp::MessageHandler::outgoingRequest().
setLogLevel()
void Logger::setLogLevel (Level logLevel) static
Set the severity level of the logger.
Definition at line 16 of file Logging.cpp.
Referenced by mlir::MlirLspServerMain(), mlir::MlirPdllLspServerMain(), and mlir::TableGenLspServerMain().
The documentation for this class was generated from the following files:
include/mlir/Tools/lsp-server-support/Logging.h
lib/Tools/lsp-server-support/Logging.cpp