MLIR: mlir::tblgen::FmtObject< Tuple > Class Template Reference
mlir::tblgen::FmtObject< Tuple > Class Template Reference
#include "mlir/TableGen/Format.h"
Public Member Functions
FmtObject (StringRef fmt, const FmtContext *ctx, Tuple &&params)
FmtObject (FmtObject const &that)=delete
FmtObject (FmtObject &&that)
Public Member Functions inherited from mlir::tblgen::FmtObjectBase
FmtObjectBase (StringRef fmt, const FmtContext *ctx, size_t numParams)
FmtObjectBase (const FmtObjectBase &that)=delete
FmtObjectBase (FmtObjectBase &&that)
void format (llvm::raw_ostream &s) const
std::string str () const
template<unsigned N>
SmallString< N > sstr () const
template<unsigned N>
operator SmallString< N > () const
operator std::string () const
Additional Inherited Members
Protected Attributes inherited from mlir::tblgen::FmtObjectBase
StringRef fmt
const FmtContext * context
std::vector< llvm::support::detail::format_adapter * > adapters
std::vector< FmtReplacement > replacements
Detailed Description
template<typename Tuple>
class mlir::tblgen::FmtObject< Tuple >
Definition at line 184 of file Format.h.
Constructor & Destructor Documentation
FmtObject() [1/3]
template<typename Tuple> mlir::tblgen::FmtObject< Tuple >::FmtObject (StringRef fmt, const FmtContext * ctx, Tuple && params) inline
Definition at line 191 of file Format.h.
References mlir::tblgen::FmtObjectBase::adapters, mlir::tblgen::FmtObjectBase::fmt, and mlir::tblgen::FmtObjectBase::FmtObjectBase().
Referenced by FmtObject(), and FmtObject().
FmtObject() [2/3]
template<typename Tuple> mlir::tblgen::FmtObject< Tuple >::FmtObject (FmtObject< Tuple > const & that) delete
References FmtObject().
FmtObject() [3/3]
template<typename Tuple> mlir::tblgen::FmtObject< Tuple >::FmtObject (FmtObject< Tuple > && that) inline
Definition at line 200 of file Format.h.
References mlir::tblgen::FmtObjectBase::adapters, FmtObject(), and mlir::tblgen::FmtObjectBase::FmtObjectBase().
The documentation for this class was generated from the following file:
include/mlir/TableGen/Format.h