MLIR: mlir::DenseElementsAttr::AttributeElementIterator Class Reference
mlir::DenseElementsAttr::AttributeElementIterator Class Reference
A utility iterator that allows walking over the internal Attribute values of a DenseElementsAttr.
#include "mlir/IR/BuiltinAttributes.h"
Public Member Functions
Attribute operator* () const
Accesses the Attribute value at this iterator position.
Detailed Description
A utility iterator that allows walking over the internal Attribute values of a DenseElementsAttr.
Definition at line 275 of file BuiltinAttributes.h.
Member Function Documentation
operator*()
Attribute DenseElementsAttr::AttributeElementIterator::operator* () const
Accesses the Attribute value at this iterator position.
Definition at line 619 of file BuiltinAttributes.cpp.
References mlir::Attribute::cast(), mlir::FloatType::getFloatSemantics(), mlir::DenseElementsAttr::getRawData(), and mlir::DenseElementsAttr::isSplat().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinAttributes.h
lib/IR/BuiltinAttributes.cpp