MLIR: mlir::spirv::MemorySpaceToStorageClassConverter Class Reference
mlir::spirv::MemorySpaceToStorageClassConverter Class Reference
Type converter for converting numeric MemRef memory spaces into SPIR-V symbolic ones.
#include "mlir/Conversion/MemRefToSPIRV/MemRefToSPIRV.h"
Public Member Functions
MemorySpaceToStorageClassConverter (const MemorySpaceToStorageClassMap &memorySpaceMap)
Detailed Description
Type converter for converting numeric MemRef memory spaces into SPIR-V symbolic ones.
Definition at line 48 of file MemRefToSPIRV.h.
Constructor & Destructor Documentation
MemorySpaceToStorageClassConverter()
spirv::MemorySpaceToStorageClassConverter::MemorySpaceToStorageClassConverter (const MemorySpaceToStorageClassMap & memorySpaceMap) explicit
Definition at line 168 of file MapMemRefStorageClassPass.cpp.
References mlir::Type::getContext(), mlir::BaseMemRefType::getElementType(), mlir::BaseMemRefType::getMemorySpace(), and mlir::BaseMemRefType::getShape().
The documentation for this class was generated from the following files:
include/mlir/Conversion/MemRefToSPIRV/MemRefToSPIRV.h
lib/Conversion/MemRefToSPIRV/MapMemRefStorageClassPass.cpp