MLIR: mlir::bufferization::AnalysisState Class Reference
mlir::bufferization::AnalysisState Class Reference
AnalysisState provides a variety of helper functions for dealing with tensor values.
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
Public Member Functions
AliasingOpOperandList getAliasingOpOperands (Value value) const
Determine which OpOperand* will alias with value if the op is bufferized in place.
AliasingValueList getAliasingValues (OpOperand &opOperand) const
Determine which Value will alias with opOperand if the op is bufferized in place.
bool bufferizesToMemoryRead (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory read.
bool bufferizesToMemoryWrite (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory write.
bool bufferizesToMemoryWrite (Value value) const
Return true if the given value bufferizes to a memory write.
bool bufferizesToAliasOnly (OpOperand &opOperand) const
Return true if opOperand does neither read nor write but bufferizes to an alias.
bool canOmitTensorCopy (OpOperand &opOperand) const
Return true if a copy can always be avoided when allocating a new tensor for the given OpOperand.
bool isValueRead (Value value) const
Return true if the given value is read by an op that bufferizes to a memory read.
SetVector< Value > findValueInReverseUseDefChain (OpOperand *opOperand, llvm::function_ref< bool(Value)> condition, TraversalConfig config=TraversalConfig(), llvm::DenseSet< OpOperand * > *visitedOpOperands=nullptr) const
Starting from opOperand, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
SetVector< Value > findDefinitions (OpOperand *opOperand) const
Find the values that may define the contents of the given value at runtime.
virtual bool isInPlace (OpOperand &opOperand) const
Return true if the given OpResult has been decided to bufferize inplace.
virtual bool areEquivalentBufferizedValues (Value v1, Value v2) const
Return true if v1 and v2 bufferize to equivalent buffers.
virtual bool areAliasingBufferizedValues (Value v1, Value v2) const
Return true if v1 and v2 may bufferize to aliasing buffers.
virtual bool hasUndefinedContents (OpOperand *opOperand) const
Return true if the given tensor has undefined contents.
const BufferizationOptions & getOptions () const
Return a reference to the BufferizationOptions.
AnalysisState (const BufferizationOptions &options)
AnalysisState (const AnalysisState &)=delete
virtual ~AnalysisState ()=default
TypeID getType () const
Region * getEnclosingRepetitiveRegion (Operation *op, const BufferizationOptions &options)
Return the closest enclosing repetitive region around the given op.
Region * getEnclosingRepetitiveRegion (Value value, const BufferizationOptions &options)
Return the closest enclosing repetitive region around the place where the given value is defined.
Region * getEnclosingRepetitiveRegion (Block *block, const BufferizationOptions &options)
Return the closest enclosing repetitive region around the given block.
virtual void resetCache ()
bool insideMutuallyExclusiveRegions (Operation *op0, Operation *op1)
Checks whether op0 and op1 are inside mutually exclusive regions.
Static Public Member Functions
static bool classof (const AnalysisState *base)
Protected Member Functions
AnalysisState (const BufferizationOptions &options, TypeID type)
Detailed Description
AnalysisState provides a variety of helper functions for dealing with tensor values.
Definition at line 413 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
AnalysisState() [1/3]
AnalysisState::AnalysisState (const BufferizationOptions & options)
Definition at line 604 of file BufferizableOpInterface.cpp.
AnalysisState() [2/3]
mlir::bufferization::AnalysisState::AnalysisState (const AnalysisState &) delete
~AnalysisState()
virtual mlir::bufferization::AnalysisState::~AnalysisState () virtual default
AnalysisState() [3/3]
AnalysisState::AnalysisState (const BufferizationOptions & options, TypeID type) protected
Definition at line 607 of file BufferizableOpInterface.cpp.
References mlir::bufferization::BufferizationOptions::stateInitializers.
Member Function Documentation
areAliasingBufferizedValues()
bool AnalysisState::areAliasingBufferizedValues (Value v1, Value v2) const virtual
Return true if v1 and v2 may bufferize to aliasing buffers.
Reimplemented in mlir::bufferization::OneShotAnalysisState.
Definition at line 651 of file BufferizableOpInterface.cpp.
areEquivalentBufferizedValues()
bool AnalysisState::areEquivalentBufferizedValues (Value v1, Value v2) const virtual
Return true if v1 and v2 bufferize to equivalent buffers.
Reimplemented in mlir::bufferization::OneShotAnalysisState.
Definition at line 645 of file BufferizableOpInterface.cpp.
bufferizesToAliasOnly()
bool AnalysisState::bufferizesToAliasOnly (OpOperand & opOperand) const
Return true if opOperand does neither read nor write but bufferizes to an alias.
Return false if the op is not bufferizable.
Definition at line 461 of file BufferizableOpInterface.cpp.
References getOptions(), and mlir::detail::IROperandBase::getOwner().
Referenced by isValueRead().
bufferizesToMemoryRead()
bool AnalysisState::bufferizesToMemoryRead (OpOperand & opOperand) const
Return true if opOperand bufferizes to a memory read.
Return true if the op is not bufferizable.
Definition at line 437 of file BufferizableOpInterface.cpp.
References getOptions(), and mlir::detail::IROperandBase::getOwner().
Referenced by canOmitTensorCopy(), and isValueRead().
bufferizesToMemoryWrite() [1/2]
bool AnalysisState::bufferizesToMemoryWrite (OpOperand & opOperand) const
Return true if opOperand bufferizes to a memory write.
Return true` if the op is not bufferizable.
Return true if the op is not bufferizable.
Definition at line 449 of file BufferizableOpInterface.cpp.
References getOptions(), and mlir::detail::IROperandBase::getOwner().
Referenced by canOmitTensorCopy(), findDefinitions(), isInPlace(), and mlir::bufferization::OneShotAnalysisState::isValueWritten().
bufferizesToMemoryWrite() [2/2]
bool AnalysisState::bufferizesToMemoryWrite (Value value) const
Return true if the given value bufferizes to a memory write.
Return true if the value is a block argument. Return true if the defining op is not bufferizable. Otherwise, consult the BufferizableOpInterface.
Definition at line 471 of file BufferizableOpInterface.cpp.
References mlir::bufferization::BufferizationOptions::dynCastBufferizableOp(), and getOptions().
canOmitTensorCopy()
bool AnalysisState::canOmitTensorCopy (OpOperand & opOperand) const
Return true if a copy can always be avoided when allocating a new tensor for the given OpOperand.
Definition at line 614 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryRead(), bufferizesToMemoryWrite(), getAliasingValues(), hasUndefinedContents(), isValueRead(), and mlir::bufferization::AliasingValue::value.
classof()
static bool mlir::bufferization::AnalysisState::classof (const AnalysisState * base) inline static
Definition at line 538 of file BufferizableOpInterface.h.
findDefinitions()
llvm::SetVector< Value > AnalysisState::findDefinitions (OpOperand * opOperand) const
Find the values that may define the contents of the given value at runtime.
A block argument is always a definition. An OpResult is a definition if it bufferizes to memory write. If it does not bufferize to a memory write but has aliasing operands, we continue the lookup on these values.
Example: r = tensor.insert f into t[c0] : tensor<?xf32> findDefinitions(r) = {r} because r bufferizes to memory write.
Example: r = tensor.empty() : tensor<10xf32> findDefinitions(r) = {} because tensor.empty does not the define the contents of its result (i.e., it does not bufferize to a memory write) and it has no aliasing OpOperands.
Example: a = arith.constant ... : tensor<10xf32> b1 = tensor.insert f into t : tensor<50xf32> b2 = tensor.extract_slice b1[0][10][1] : tensor<50xf32> tensor<10xf32> r = arith.select cond, a, b : tensor<10xf32> findDefinitions(r) = {a, b1}. r and b2 are skipped (lookup continues in the operands) because their defining ops do not define the contents of the tensor.
Example: a = tensor.empty() : tensor<10xf32> b = arith.constant ... : tensor<10xf32> r = arith.select cond, a, b : tensor<10xf32> findDefinitions(r) = {b}. a is excluded because it does not define the contents of the tensor.
Note: OpResults of unknown ops are handled conservatively and assumed to be definitions.
Definition at line 596 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryWrite(), mlir::config, and findValueInReverseUseDefChain().
Referenced by mlir::bufferization::OneShotAnalysisState::findDefinitionsCached().
findValueInReverseUseDefChain()
llvm::SetVector< Value > AnalysisState::findValueInReverseUseDefChain (OpOperand * opOperand, llvm::function_ref< bool(Value)> condition, TraversalConfig config = TraversalConfig(), llvm::DenseSet< OpOperand * > * visitedOpOperands = nullptr) const
Starting from opOperand, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Find and return Values for which condition evaluates to true. OpOperands of such matching Values are not traversed any further, the visited aliasing opOperands will be preserved through visitedOpOperands.
When reaching the end of a chain, also return the last Value of that chain if config.alwaysIncludeLeaves is set.
Example:
                          8
                          |
6* 7* +--—+-—+ | | | | 2* 3 4* 5 | | | | +-------—+-------—+-------—+ | 1
In the above example, Values with a star satisfy the condition. When starting the traversal from Value 1, the resulting SetVector is: { 2, 7, 8, 5 }
Additional stopping conditions for the traversal can be specified in config.
Definition at line 513 of file BufferizableOpInterface.cpp.
References mlir::config, mlir::bufferization::BufferizationOptions::dynCastBufferizableOp(), mlir::bufferization::Equivalent, mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpOperands(), mlir::Value::getDefiningOp(), mlir::bufferization::AliasList< T >::getNumAliases(), mlir::Value::getType(), and isInPlace().
Referenced by findDefinitions().
getAliasingOpOperands()
AliasingOpOperandList AnalysisState::getAliasingOpOperands (Value value) const
Determine which OpOperand* will alias with value if the op is bufferized in place.
Return all tensor OpOperand* if the op is not bufferizable.
Definition at line 415 of file BufferizableOpInterface.cpp.
References getOptions(), mlir::bufferization::getOwnerOfValue(), and mlir::bufferization::detail::unknownGetAliasingOpOperands().
Referenced by mlir::bufferization::detail::defaultGetBufferType(), and findValueInReverseUseDefChain().
getAliasingValues()
AliasingValueList AnalysisState::getAliasingValues (OpOperand & opOperand) const
Determine which Value will alias with opOperand if the op is bufferized in place.
Determine which Values will alias with opOperand if the op is bufferized in place.
Return all tensor Values if the op is not bufferizable.
Definition at line 426 of file BufferizableOpInterface.cpp.
References getOptions(), mlir::detail::IROperandBase::getOwner(), and mlir::bufferization::detail::unknownGetAliasingValues().
Referenced by mlir::bufferization::OneShotAnalysisState::bufferizeInPlace(), canOmitTensorCopy(), and isValueRead().
getEnclosingRepetitiveRegion() [1/3]
Region * AnalysisState::getEnclosingRepetitiveRegion (Block * block, const BufferizationOptions & options)
Return the closest enclosing repetitive region around the given block.
Definition at line 83 of file BufferizableOpInterface.cpp.
References mlir::Block::getParent(), mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), and isRepetitiveRegion().
getEnclosingRepetitiveRegion() [2/3]
Region * AnalysisState::getEnclosingRepetitiveRegion (Operation * op, const BufferizationOptions & options)
Return the closest enclosing repetitive region around the given op.
Definition at line 50 of file BufferizableOpInterface.cpp.
References mlir::Operation::getBlock().
getEnclosingRepetitiveRegion() [3/3]
Region * AnalysisState::getEnclosingRepetitiveRegion (Value value, const BufferizationOptions & options)
Return the closest enclosing repetitive region around the place where the given value is defined.
Definition at line 61 of file BufferizableOpInterface.cpp.
References mlir::Region::getParentRegion(), mlir::Value::getParentRegion(), and isRepetitiveRegion().
getOptions()
const BufferizationOptions& mlir::bufferization::AnalysisState::getOptions () const inline
Return a reference to the BufferizationOptions.
Definition at line 529 of file BufferizableOpInterface.h.
Referenced by bufferizesToAliasOnly(), bufferizesToMemoryRead(), bufferizesToMemoryWrite(), getAliasingOpOperands(), getAliasingValues(), mlir::bufferization::OneShotAnalysisState::getOptions(), and mlir::bufferization::insertTensorCopies().
getType()
TypeID mlir::bufferization::AnalysisState::getType () const inline
Definition at line 540 of file BufferizableOpInterface.h.
Referenced by mlir::bufferization::OneShotAnalysisState::classof().
hasUndefinedContents()
bool AnalysisState::hasUndefinedContents (OpOperand * opOperand) const virtual
Return true if the given tensor has undefined contents.
Reimplemented in mlir::bufferization::OneShotAnalysisState.
Definition at line 657 of file BufferizableOpInterface.cpp.
Referenced by canOmitTensorCopy().
insideMutuallyExclusiveRegions()
bool AnalysisState::insideMutuallyExclusiveRegions (Operation * op0, Operation * op1)
Checks whether op0 and op1 are inside mutually exclusive regions.
The logic defers to mlir::insideMutuallyExclusiveRegions, but the result is cached.
Definition at line 106 of file BufferizableOpInterface.cpp.
References mlir::insideMutuallyExclusiveRegions().
isInPlace()
bool AnalysisState::isInPlace (OpOperand & opOperand) const virtual
Return true if the given OpResult has been decided to bufferize inplace.
Reimplemented in mlir::bufferization::OneShotAnalysisState.
Definition at line 635 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryWrite(), and mlir::detail::IROperandBase::getOwner().
Referenced by findValueInReverseUseDefChain().
isValueRead()
bool AnalysisState::isValueRead (Value value) const
Return true if the given value is read by an op that bufferizes to a memory read.
Also takes into account ops that create an alias but do not read by themselves (e.g., ExtractSliceOp).
Definition at line 484 of file BufferizableOpInterface.cpp.
References bufferizesToAliasOnly(), bufferizesToMemoryRead(), getAliasingValues(), mlir::Value::getType(), and mlir::Value::getUses().
Referenced by canOmitTensorCopy().
resetCache()
void AnalysisState::resetCache () virtual
Reimplemented in mlir::bufferization::OneShotAnalysisState.
Definition at line 119 of file BufferizableOpInterface.cpp.
Referenced by mlir::bufferization::OneShotAnalysisState::resetCache().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h
lib/Dialect/Bufferization/IR/BufferizableOpInterface.cpp