MLIR: mlir::spirv::ImageType Class Reference
mlir::spirv::ImageType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Member Functions
Type getElementType () const
Dim getDim () const
ImageDepthInfo getDepthInfo () const
ImageArrayedInfo getArrayedInfo () const
ImageSamplingInfo getSamplingInfo () const
ImageSamplerUseInfo getSamplerUseInfo () const
ImageFormat getImageFormat () const
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static ImageType get (Type elementType, Dim dim, ImageDepthInfo depth=ImageDepthInfo::DepthUnknown, ImageArrayedInfo arrayed=ImageArrayedInfo::NonArrayed, ImageSamplingInfo samplingInfo=ImageSamplingInfo::SingleSampled, ImageSamplerUseInfo samplerUse=ImageSamplerUseInfo::SamplerUnknown, ImageFormat format=ImageFormat::Unknown)
static ImageType get (std::tuple< Type, Dim, ImageDepthInfo, ImageArrayedInfo, ImageSamplingInfo, ImageSamplerUseInfo, ImageFormat >)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
static ConcreteType get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteType getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.image"
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
using Base
Utility declarations for the concrete attribute class.
using ImplType
using HasTraitFn
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 139 of file SPIRVTypes.h.
Member Function Documentation
get() [1/2]
ImageType ImageType::get (std::tuple< Type, Dim, ImageDepthInfo, ImageArrayedInfo, ImageSamplingInfo, ImageSamplerUseInfo, ImageFormat > value) static
Definition at line 389 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), and getContext().
get() [2/2]
ImageType mlir::spirv::ImageType::get (Type elementType, Dim dim, ImageDepthInfo depth = ImageDepthInfo::DepthUnknown, ImageArrayedInfo arrayed = ImageArrayedInfo::NonArrayed, ImageSamplingInfo samplingInfo = ImageSamplingInfo::SingleSampled, ImageSamplerUseInfo samplerUse = ImageSamplerUseInfo::SamplerUnknown, ImageFormat format = ImageFormat::Unknown) inline static
Definition at line 147 of file SPIRVTypes.h.
References get().
Referenced by get(), parseImageType(), and mlir::spirv::Deserializer::processImageType().
getArrayedInfo()
ImageArrayedInfo ImageType::getArrayedInfo () const
Definition at line 401 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print().
getDepthInfo()
ImageDepthInfo ImageType::getDepthInfo () const
Definition at line 399 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print().
getDim()
Dim ImageType::getDim () const
Definition at line 397 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print(), and verifyImageOperands().
getElementType()
Type ImageType::getElementType () const
Definition at line 395 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print().
getImageFormat()
ImageFormat ImageType::getImageFormat () const
Definition at line 413 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print().
getSamplerUseInfo()
ImageSamplerUseInfo ImageType::getSamplerUseInfo () const
Definition at line 409 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print().
getSamplingInfo()
ImageSamplingInfo ImageType::getSamplingInfo () const
Definition at line 405 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by print(), and verifyImageOperands().
Member Data Documentation
name
StringLiteral mlir::spirv::ImageType::name = "spirv.image" static constexpr
Definition at line 144 of file SPIRVTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp