MLIR: mlir::sparse_tensor::FuncCallOrInlineGenerator< SubClass > Class Template Reference
mlir::sparse_tensor::FuncCallOrInlineGenerator< SubClass > Class Template Reference
A helper class to simplify lowering operations with/without function calls.
#include "Dialect/SparseTensor/Transforms/Utils/CodegenUtils.h"
Public Member Functions
FuncCallOrInlineGenerator (TypeRange retTypes, ValueRange params, bool genCall)
SmallVector< Value > genCallOrInline (OpBuilder &builder, Location loc)
Detailed Description
template<class SubClass>
class mlir::sparse_tensor::FuncCallOrInlineGenerator< SubClass >
A helper class to simplify lowering operations with/without function calls.
Definition at line 78 of file CodegenUtils.h.
Constructor & Destructor Documentation
FuncCallOrInlineGenerator()
template<class SubClass > mlir::sparse_tensor::FuncCallOrInlineGenerator< SubClass >::FuncCallOrInlineGenerator (TypeRange retTypes, ValueRange params, bool genCall) inline
Definition at line 80 of file CodegenUtils.h.
Member Function Documentation
genCallOrInline()
template<class SubClass > SmallVector<Value> mlir::sparse_tensor::FuncCallOrInlineGenerator< SubClass >::genCallOrInline (OpBuilder & builder, Location loc) inline
Definition at line 85 of file CodegenUtils.h.
References mlir::get(), mlir::Block::getArguments(), mlir::ValueRange::getTypes(), mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointToStart().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/Transforms/Utils/CodegenUtils.h