MLIR: mlir::detail::DominanceInfoBase< IsPostDom > Class Template Reference
mlir::detail::DominanceInfoBase< IsPostDom > Class Template Reference
#include "mlir/IR/Dominance.h"
Public Member Functions
DominanceInfoBase (Operation *op=nullptr)
DominanceInfoBase (DominanceInfoBase &&)=default
DominanceInfoBase & operator= (DominanceInfoBase &&)=default
~DominanceInfoBase ()
DominanceInfoBase (const DominanceInfoBase &)=delete
DominanceInfoBase & operator= (const DominanceInfoBase &)=delete
void invalidate ()
Invalidate dominance info.
void invalidate (Region *region)
Block * findNearestCommonDominator (Block *a, Block *b) const
Finds the nearest common dominator block for the two given blocks a and b.
template<typename BlockRangeT>
Block * findNearestCommonDominator (BlockRangeT &&blocks) const
Finds the nearest common dominator block for the given range of blocks.
DominanceInfoNode * getRootNode (Region *region)
Get the root dominance node of the given region.
DominanceInfoNode * getNode (Block *a)
Return the dominance node from the Region containing block A.
bool isReachableFromEntry (Block *a) const
Return true if the specified block is reachable from the entry block of its region.
bool hasSSADominance (Block *block) const
Return true if operations in the specified block are known to obey SSA dominance requirements.
bool hasSSADominance (Region *region) const
Return true if operations in the specified block are known to obey SSA dominance requirements.
DomTree & getDomTree (Region *region) const
Protected Types
using super = DominanceInfoBase<IsPostDom>
Protected Member Functions
llvm::PointerIntPair< DomTree *, 1, bool > getDominanceInfo (Region *region, bool needsDomTree) const
Return the dom tree and "hasSSADominance" bit for the given region.
bool properlyDominatesImpl (Block *aBlock, Block::iterator aIt, Block *bBlock, Block::iterator bIt, bool enclosingOk=true) const
Return "true" if block iterator A properly (post)dominates block iterator B.
Protected Attributes
DenseMap< Region *, llvm::PointerIntPair< DomTree *, 1, bool > > dominanceInfos
A mapping of regions to their base dominator tree and a cached "hasSSADominance" bit.
Detailed Description
template<bool IsPostDom>
class mlir::detail::DominanceInfoBase< IsPostDom >
Definition at line 35 of file Dominance.h.
Member Typedef Documentation
super
template<bool IsPostDom> using mlir::detail::DominanceInfoBase< IsPostDom >::super = DominanceInfoBase<IsPostDom> protected
Definition at line 108 of file Dominance.h.
Constructor & Destructor Documentation
DominanceInfoBase() [1/3]
template<bool IsPostDom> mlir::detail::DominanceInfoBase< IsPostDom >::DominanceInfoBase (Operation * op = nullptr) inline
Definition at line 39 of file Dominance.h.
Referenced by DominanceInfoBase(), DominanceInfoBase(), operator=(), and operator=().
DominanceInfoBase() [2/3]
template<bool IsPostDom> mlir::detail::DominanceInfoBase< IsPostDom >::DominanceInfoBase (DominanceInfoBase< IsPostDom > &&) default
References DominanceInfoBase().
~DominanceInfoBase()
template<bool IsPostDom> DominanceInfoBase::~DominanceInfoBase ()
Definition at line 31 of file Dominance.cpp.
References dominanceInfos.
DominanceInfoBase() [3/3]
template<bool IsPostDom> mlir::detail::DominanceInfoBase< IsPostDom >::DominanceInfoBase (const DominanceInfoBase< IsPostDom > &) delete
References DominanceInfoBase().
Member Function Documentation
findNearestCommonDominator() [1/2]
template<bool IsPostDom> Block * DominanceInfoBase::findNearestCommonDominator (Block * a, Block * b) const
Finds the nearest common dominator block for the two given blocks a and b.
If no common dominator can be found, this function will return nullptr.
Definition at line 191 of file Dominance.cpp.
References b, getDomTree(), mlir::Block::getParent(), and tryGetBlocksInSameRegion().
Referenced by findNearestCommonDominator(), and operator=().
findNearestCommonDominator() [2/2]
template<bool IsPostDom> template<typename BlockRangeT> Block * mlir::detail::DominanceInfoBase< IsPostDom >::findNearestCommonDominator (BlockRangeT && blocks) const inline
Finds the nearest common dominator block for the given range of blocks.
If no common dominator can be found, this function will return nullptr.
Definition at line 60 of file Dominance.h.
References mlir::Block::begin(), and findNearestCommonDominator().
getDominanceInfo()
template<bool IsPostDom> auto DominanceInfoBase::getDominanceInfo (Region * region, bool needsDomTree) const protected
Return the dom tree and "hasSSADominance" bit for the given region.
The DomTree will be null for single-block regions. This lazily constructs the DomTree on demand when needsDomTree=true.
Definition at line 56 of file Dominance.cpp.
References dominanceInfos, and mlir::Operation::getParentOp().
Referenced by getDomTree(), getRootNode(), and hasSSADominance().
getDomTree()
template<bool IsPostDom> DomTree & mlir::detail::DominanceInfoBase< IsPostDom >::getDomTree (Region * region) const inline
Definition at line 101 of file Dominance.h.
References getDominanceInfo(), and mlir::Region::hasOneBlock().
Referenced by findNearestCommonDominator(), and getNode().
getNode()
template<bool IsPostDom> DominanceInfoNode * mlir::detail::DominanceInfoBase< IsPostDom >::getNode (Block * a) inline
Return the dominance node from the Region containing block A.
This only works for multi-block regions.
Definition at line 82 of file Dominance.h.
References getDomTree(), and mlir::Block::getParent().
Referenced by setDebugIntrinsicBuilderInsertionPoint(), and transformToStructuredCFBranches().
getRootNode()
template<bool IsPostDom> DominanceInfoNode * mlir::detail::DominanceInfoBase< IsPostDom >::getRootNode (Region * region) inline
Get the root dominance node of the given region.
Note that this operation is only defined for multi-block regions!
Definition at line 74 of file Dominance.h.
References getDominanceInfo().
hasSSADominance() [1/2]
template<bool IsPostDom> bool mlir::detail::DominanceInfoBase< IsPostDom >::hasSSADominance (Block * block) const inline
Return true if operations in the specified block are known to obey SSA dominance requirements.
False if the block is a graph region or unknown.
Definition at line 92 of file Dominance.h.
References mlir::Block::getParent(), and hasSSADominance().
Referenced by hasSSADominance().
hasSSADominance() [2/2]
template<bool IsPostDom> bool mlir::detail::DominanceInfoBase< IsPostDom >::hasSSADominance (Region * region) const inline
Return true if operations in the specified block are known to obey SSA dominance requirements.
False if the block is a graph region or unknown.
Definition at line 97 of file Dominance.h.
References getDominanceInfo().
invalidate() [1/2]
template<bool IsPostDom> void DominanceInfoBase::invalidate ()
Invalidate dominance info.
This can be used by clients that make major changes to the CFG and don't have a good way to update it.
Definition at line 37 of file Dominance.cpp.
References dominanceInfos.
Referenced by operator=(), mlir::transformCFGToSCF(), and transformToStructuredCFBranches().
invalidate() [2/2]
template<bool IsPostDom> void DominanceInfoBase::invalidate (Region * region)
Definition at line 44 of file Dominance.cpp.
References dominanceInfos.
isReachableFromEntry()
template<bool IsPostDom> bool mlir::detail::DominanceInfoBase< IsPostDom >::isReachableFromEntry (Block * a) const
Return true if the specified block is reachable from the entry block of its region.
Referenced by findCapturedOmpOp().
operator=() [1/2]
template<bool IsPostDom> DominanceInfoBase & mlir::detail::DominanceInfoBase< IsPostDom >::operator= (const DominanceInfoBase< IsPostDom > &) delete
References b, DominanceInfoBase(), findNearestCommonDominator(), and invalidate().
operator=() [2/2]
template<bool IsPostDom> DominanceInfoBase & mlir::detail::DominanceInfoBase< IsPostDom >::operator= (DominanceInfoBase< IsPostDom > &&) default
References DominanceInfoBase().
properlyDominatesImpl()
template<bool IsPostDom> bool mlir::detail::DominanceInfoBase< IsPostDom >::properlyDominatesImpl (Block * aBlock, Block::iterator aIt, Block * bBlock, Block::iterator bIt, bool enclosingOk = true) const protected
Return "true" if block iterator A properly (post)dominates block iterator B.
If enclosingOk is set, A is considered to (post)dominate B if A encloses B.
Referenced by mlir::DominanceInfo::dominates(), mlir::PostDominanceInfo::postDominates(), mlir::DominanceInfo::properlyDominates(), mlir::DominanceInfo::properlyDominates(), mlir::DominanceInfo::properlyDominates(), mlir::PostDominanceInfo::properlyPostDominates(), mlir::PostDominanceInfo::properlyPostDominates(), and mlir::PostDominanceInfo::properlyPostDominates().
Member Data Documentation
dominanceInfos
template<bool IsPostDom> DenseMap<Region *, llvm::PointerIntPair<DomTree *, 1, bool> > mlir::detail::DominanceInfoBase< IsPostDom >::dominanceInfos mutable protected
A mapping of regions to their base dominator tree and a cached "hasSSADominance" bit.
This map does not contain dominator trees for single block CFG regions, but we do want to cache the "hasSSADominance" bit for them. We may also not have computed the DomTree yet. In either case, the DomTree is just null.
Definition at line 130 of file Dominance.h.
Referenced by getDominanceInfo(), invalidate(), invalidate(), and ~DominanceInfoBase().
The documentation for this class was generated from the following files:
include/mlir/IR/Dominance.h
lib/IR/Dominance.cpp