MLIR: mlir::tracing::InstallDebugHandler::Impl Class Reference
mlir::tracing::InstallDebugHandler::Impl Class Reference
Public Member Functions
Impl (MLIRContext &context, const DebugConfig &config)
Detailed Description
Definition at line 83 of file CLOptionsSetup.cpp.
Constructor & Destructor Documentation
Impl()
mlir::tracing::InstallDebugHandler::Impl::Impl (MLIRContext & context, const DebugConfig & config) inline
Definition at line 85 of file CLOptionsSetup.cpp.
References mlir::config, mlir::emitError(), mlir::get(), mlir::tracing::DebugCounter::isActivated(), mlir::openOutputFile(), mlir::MLIRContext::registerActionHandler(), and mlir::setupDebuggerExecutionContextHook().
The documentation for this class was generated from the following file:
lib/Debug/CLOptionsSetup.cpp