MLIR: mlir::AffineValueMap Class Reference
mlir::AffineValueMap Class Reference
An AffineValueMap is an affine map plus its ML value operands and results for analysis purposes.
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
Public Member Functions
AffineValueMap ()
AffineValueMap (AffineMap map, ValueRange operands, ValueRange results={})
~AffineValueMap ()
void reset (AffineMap map, ValueRange operands, ValueRange results={})
bool isMultipleOf (unsigned idx, int64_t factor) const
Return true if the idx^th result can be proved to be a multiple of 'factor', false otherwise.
bool isFunctionOf (unsigned idx, Value value) const
Return true if the idx^th result depends on 'value', false otherwise.
bool isConstant (unsigned idx) const
Return true if the result at 'idx' is a constant, false otherwise.
bool isIdentity () const
Return true if this is an identity map.
void setResult (unsigned i, AffineExpr e)
AffineExpr getResult (unsigned i)
unsigned getNumOperands () const
unsigned getNumDims () const
unsigned getNumSymbols () const
unsigned getNumResults () const
Value getOperand (unsigned i) const
ArrayRef< Value > getOperands () const
AffineMap getAffineMap () const
LogicalResult canonicalize ()
Attempts to canonicalize the map and operands.
Static Public Member Functions
static void difference (const AffineValueMap &a, const AffineValueMap &b, AffineValueMap *res)
Return the value map that is the difference of value maps 'a' and 'b', represented as an affine map and its operands.
Detailed Description
An AffineValueMap is an affine map plus its ML value operands and results for analysis purposes.
The structure is still a tree form that is same as that of an affine map or an AffineApplyOp. However, its operands, results, and its map can themselves change as a result of substitutions, simplifications, and other analysis.
Definition at line 34 of file AffineValueMap.h.
Constructor & Destructor Documentation
AffineValueMap() [1/2]
mlir::AffineValueMap::AffineValueMap () inline
Definition at line 38 of file AffineValueMap.h.
References difference(), isConstant(), isFunctionOf(), isIdentity(), isMultipleOf(), reset(), value, and ~AffineValueMap().
AffineValueMap() [2/2]
AffineValueMap::AffineValueMap (AffineMap map, ValueRange operands, ValueRange results = {})
Definition at line 14 of file AffineValueMap.cpp.
~AffineValueMap()
AffineValueMap::~AffineValueMap ()
Definition at line 102 of file AffineValueMap.cpp.
Referenced by AffineValueMap().
Member Function Documentation
canonicalize()
LogicalResult AffineValueMap::canonicalize ()
Attempts to canonicalize the map and operands.
Return success if the map and/or operands have been modified.
Definition at line 3014 of file AffineOps.cpp.
References composeAffineMapAndOperands(), mlir::failure(), and mlir::success().
Referenced by canonicalizeLoopBounds(), and getNumResults().
difference()
void AffineValueMap::difference (const AffineValueMap & a, const AffineValueMap & b, AffineValueMap * res) static
Return the value map that is the difference of value maps 'a' and 'b', represented as an affine map and its operands.
The output map + operands are canonicalized and simplified.
Definition at line 26 of file AffineValueMap.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), getAffineMap(), getNumDims(), getNumOperands(), getNumResults(), getNumSymbols(), getOperands(), reset(), mlir::AffineMap::shiftDims(), and mlir::simplifyAffineMap().
Referenced by AffineValueMap(), mlir::buildTripCountMapAndOperands(), mlir::normalizeAffineParallel(), mlir::MemRefAccess::operator==(), and verify().
getAffineMap()
AffineMap AffineValueMap::getAffineMap () const
Definition at line 100 of file AffineValueMap.cpp.
References mlir::MutableAffineMap::getAffineMap().
Referenced by addMemRefAccessConstraints(), canonicalizeLoopBounds(), mlir::FlatAffineConstraints::composeMap(), mlir::MemRefRegion::compute(), createFullTiles(), difference(), getNumResults(), initDependenceConstraints(), isFunctionOf(), and mlir::MemRefAccess::operator==().
getNumDims()
unsigned mlir::AffineValueMap::getNumDims () const inline
Definition at line 69 of file AffineValueMap.h.
References mlir::AffineMap::getNumDims().
Referenced by difference(), and mlir::normalizeAffineParallel().
getNumOperands()
unsigned mlir::AffineValueMap::getNumOperands () const inline
Definition at line 68 of file AffineValueMap.h.
Referenced by mlir::FlatAffineConstraints::composeMap(), mlir::MemRefRegion::compute(), and difference().
getNumResults()
unsigned mlir::AffineValueMap::getNumResults () const inline
Definition at line 71 of file AffineValueMap.h.
References canonicalize(), getAffineMap(), mlir::AffineMap::getNumResults(), getOperand(), and getOperands().
Referenced by mlir::FlatAffineConstraints::composeMap(), difference(), and verify().
getNumSymbols()
unsigned mlir::AffineValueMap::getNumSymbols () const inline
Definition at line 70 of file AffineValueMap.h.
References mlir::AffineMap::getNumSymbols().
Referenced by difference(), and mlir::normalizeAffineParallel().
getOperand()
Value AffineValueMap::getOperand (unsigned i) const
Definition at line 92 of file AffineValueMap.cpp.
Referenced by mlir::FlatAffineConstraints::composeMap(), mlir::MemRefRegion::compute(), and getNumResults().
getOperands()
ArrayRef< Value > AffineValueMap::getOperands () const
Definition at line 96 of file AffineValueMap.cpp.
Referenced by addMemRefAccessConstraints(), buildDimAndSymbolPositionMaps(), canonicalizeLoopBounds(), mlir::FlatAffineConstraints::composeMap(), createFullTiles(), difference(), getNumResults(), initDependenceConstraints(), and mlir::normalizeAffineParallel().
getResult()
AffineExpr mlir::AffineValueMap::getResult (unsigned i) inline
Definition at line 67 of file AffineValueMap.h.
References mlir::AffineMap::getResult().
Referenced by mlir::normalizeAffineParallel(), and verify().
isConstant()
bool mlir::AffineValueMap::isConstant (unsigned idx) const
Return true if the result at 'idx' is a constant, false otherwise.
Referenced by AffineValueMap().
isFunctionOf()
bool AffineValueMap::isFunctionOf (unsigned idx, Value value) const
Return true if the idx^th result depends on 'value', false otherwise.
This method uses the invariant that operands are always positionally aligned with the AffineDimExpr in the underlying AffineMap.
Definition at line 81 of file AffineValueMap.cpp.
References findIndex(), getAffineMap(), mlir::AffineMap::getResult(), and mlir::AffineExpr::isFunctionOfDim().
Referenced by AffineValueMap().
isIdentity()
bool mlir::AffineValueMap::isIdentity () const
Return true if this is an identity map.
Referenced by AffineValueMap().
isMultipleOf()
bool AffineValueMap::isMultipleOf (unsigned idx, int64_t factor) const inline
Return true if the idx^th result can be proved to be a multiple of 'factor', false otherwise.
Definition at line 75 of file AffineValueMap.cpp.
References mlir::MutableAffineMap::isMultipleOf().
Referenced by AffineValueMap().
reset()
void AffineValueMap::reset (AffineMap map, ValueRange operands, ValueRange results = {})
Definition at line 19 of file AffineValueMap.cpp.
Referenced by AffineValueMap(), difference(), mlir::MemRefAccess::getAccessMap(), and mlir::FlatAffineConstraints::getIneqAsAffineValueMap().
setResult()
void mlir::AffineValueMap::setResult (unsigned i, AffineExpr e) inline
Definition at line 66 of file AffineValueMap.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/IR/AffineValueMap.h
lib/Dialect/Affine/IR/AffineOps.cpp
lib/Dialect/Affine/IR/AffineValueMap.cpp