MLIR: mlir::query::matcher::VariantMatcher Class Reference
mlir::query::matcher::VariantMatcher Class Reference
#include "mlir/Query/Matcher/VariantValue.h"
Classes
class SinglePayload
class VariadicOpPayload
Public Member Functions
VariantMatcher ()
void reset ()
bool isNull () const
std::optional< DynMatcher > getDynMatcher () const
std::string getTypeAsString () const
Static Public Member Functions
static VariantMatcher SingleMatcher (DynMatcher matcher)
static VariantMatcher VariadicOperatorMatcher (DynMatcher::VariadicOperator varOp, ArrayRef< VariantMatcher > args)
Detailed Description
Definition at line 28 of file VariantValue.h.
Constructor & Destructor Documentation
VariantMatcher()
mlir::query::matcher::VariantMatcher::VariantMatcher () default
References VariantMatcher().
Referenced by SingleMatcher(), VariadicOperatorMatcher(), and VariantMatcher().
Member Function Documentation
getDynMatcher()
std::optional< DynMatcher > mlir::query::matcher::VariantMatcher::getDynMatcher () const
Definition at line 87 of file VariantValue.cpp.
Referenced by mlir::query::matcher::RegistryManager::constructMatcher(), mlir::query::matcher::internal::ArgTypeTraits< DynMatcher >::get(), and mlir::query::matcher::internal::Parser::parseMatcherExpression().
getTypeAsString()
std::string mlir::query::matcher::VariantMatcher::getTypeAsString () const
Definition at line 93 of file VariantValue.cpp.
isNull()
bool mlir::query::matcher::VariantMatcher::isNull () const inline
Definition at line 59 of file VariantValue.h.
Referenced by mlir::query::matcher::RegistryManager::constructMatcher().
reset()
void mlir::query::matcher::VariantMatcher::reset ()
Definition at line 91 of file VariantValue.cpp.
SingleMatcher()
VariantMatcher mlir::query::matcher::VariantMatcher::SingleMatcher (DynMatcher matcher) static
Definition at line 62 of file VariantValue.cpp.
References VariantMatcher().
Referenced by mlir::query::matcher::RegistryManager::constructMatcher(), and mlir::query::matcher::internal::matcherMarshallFixedImpl().
VariadicOperatorMatcher()
VariantMatcher mlir::query::matcher::VariantMatcher::VariadicOperatorMatcher (DynMatcher::VariadicOperator varOp, ArrayRef< VariantMatcher > args) static
Definition at line 67 of file VariantValue.cpp.
References VariantMatcher().
Referenced by mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::create().
The documentation for this class was generated from the following files:
include/mlir/Query/Matcher/VariantValue.h
lib/Query/Matcher/VariantValue.cpp