MLIR: mlir::python::CollectDiagnosticsToStringScope Class Reference
mlir::python::CollectDiagnosticsToStringScope Class Reference
RAII scope intercepting all diagnostics into a string.
#include "mlir/Bindings/Python/Diagnostics.h"
Public Member Functions
CollectDiagnosticsToStringScope (MlirContext ctx)
~CollectDiagnosticsToStringScope ()
std::string takeMessage ()
Detailed Description
RAII scope intercepting all diagnostics into a string.
The message must be checked before this goes out of scope.
Definition at line 25 of file Diagnostics.h.
Constructor & Destructor Documentation
CollectDiagnosticsToStringScope()
mlir::python::CollectDiagnosticsToStringScope::CollectDiagnosticsToStringScope (MlirContext ctx) inline explicit
Definition at line 27 of file Diagnostics.h.
References mlirContextAttachDiagnosticHandler().
~CollectDiagnosticsToStringScope()
mlir::python::CollectDiagnosticsToStringScope::~CollectDiagnosticsToStringScope () inline
Definition at line 32 of file Diagnostics.h.
References mlirContextDetachDiagnosticHandler().
Member Function Documentation
takeMessage()
std::string mlir::python::CollectDiagnosticsToStringScope::takeMessage () inline
Definition at line 37 of file Diagnostics.h.
Referenced by populateDialectLLVMSubmodule(), populateDialectSMTSubmodule(), and populateTransformInterpreterSubmodule().
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/Diagnostics.h