MLIR: mlir::RegionRange Class Reference
mlir::RegionRange Class Reference
This class provides an abstraction over the different types of ranges over Regions.
#include "mlir/IR/Region.h"
Public Member Functions
RegionRange (MutableArrayRef< Region > regions={})
template<typename Arg, typename = std::enable_if_t<std::is_constructible< ArrayRef<std::unique_ptr<Region>>, Arg>::value>>
RegionRange (Arg &&arg LLVM_LIFETIME_BOUND)
template<typename Arg>
RegionRange (Arg &&arg LLVM_LIFETIME_BOUND, std::enable_if_t< std::is_constructible< ArrayRef< Region * >, Arg >::value > *=nullptr)
RegionRange (ArrayRef< std::unique_ptr< Region > > regions)
RegionRange (ArrayRef< Region * > regions)
Detailed Description
This class provides an abstraction over the different types of ranges over Regions.
In many cases, this prevents the need to explicitly materialize a SmallVector/stdvector. This class should be used in places that are not suitable for a more derived type (e.g. ArrayRef) or a template range parameter.
Definition at line 342 of file Region.h.
Constructor & Destructor Documentation
RegionRange() [1/5]
RegionRange::RegionRange (MutableArrayRef< Region > regions = {})
Definition at line 275 of file Region.cpp.
References RegionRange().
Referenced by RegionRange(), RegionRange(), RegionRange(), RegionRange(), and RegionRange().
RegionRange() [2/5]
template<typename Arg, typename = std::enable_if_t<std::is_constructible< ArrayRef<std::unique_ptr<Region>>, Arg>::value>> mlir::RegionRange::RegionRange (Arg &&arg LLVM_LIFETIME_BOUND) inline
Definition at line 360 of file Region.h.
References RegionRange().
RegionRange() [3/5]
template<typename Arg> mlir::RegionRange::RegionRange (Arg &&arg LLVM_LIFETIME_BOUND, std::enable_if_t< std::is_constructible< ArrayRef< Region * >, Arg >::value > * = nullptr) inline
Definition at line 364 of file Region.h.
References RegionRange().
RegionRange() [4/5]
RegionRange::RegionRange (ArrayRef< std::unique_ptr< Region > > regions)
Definition at line 277 of file Region.cpp.
References RegionRange().
RegionRange() [5/5]
RegionRange::RegionRange (ArrayRef< Region * > regions)
Definition at line 279 of file Region.cpp.
References RegionRange().
The documentation for this class was generated from the following files:
include/mlir/IR/Region.h
lib/IR/Region.cpp