MLIR: mlir::linalg::MatmulTransposeBOp Class Reference
mlir::linalg::MatmulTransposeBOp Class Reference
Specialization of linalg.matmul op that has a transpose map on B.
#include "mlir/Dialect/Linalg/IR/Linalg.h"
Static Public Member Functions
::mlir::TypeID resolveTypeID ()
static void build (OpBuilder &builder, OperationState &result, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
Build a transpose B matmul.
static MatmulTransposeBOp create (OpBuilder &builder, Location location, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
static void build (OpBuilder &builder, OperationState &result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
Build a transpose B matmul with a specific result type.
static MatmulTransposeBOp create (OpBuilder &builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
static void build (OpBuilder &builder, OperationState &result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes={})
Build a transpose B matmul with a specific result type and a cast type.
static MatmulTransposeBOp create (OpBuilder &builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes={})
static bool isDefaultIndexingMaps (Attribute attr)
Checks if the affine map is the expected one for this operation.
static bool classof (Operation *op)
Detailed Description
Specialization of linalg.matmul op that has a transpose map on B.
Definition at line 204 of file Linalg.h.
Member Function Documentation
build() [1/3]
void mlir::linalg::linalg::MatmulTransposeBOp::build (OpBuilder & builder, OperationState & result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose B matmul with a specific result type.
Definition at line 4106 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
build() [2/3]
void mlir::linalg::linalg::MatmulTransposeBOp::build (OpBuilder & builder, OperationState & result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose B matmul with a specific result type and a cast type.
Definition at line 4127 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
build() [3/3]
void mlir::linalg::linalg::MatmulTransposeBOp::build (OpBuilder & builder, OperationState & result, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose B matmul.
Definition at line 4087 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
Referenced by create(), create(), and create().
classof()
bool mlir::linalg::MatmulTransposeBOp::classof (Operation * op) static
Definition at line 4150 of file LinalgOps.cpp.
References mlir::Operation::getAttr(), and isDefaultIndexingMaps().
create() [1/3]
MatmulTransposeBOp mlir::linalg::MatmulTransposeBOp::create (OpBuilder & builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4116 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
create() [2/3]
MatmulTransposeBOp mlir::linalg::MatmulTransposeBOp::create (OpBuilder & builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4139 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
create() [3/3]
MatmulTransposeBOp mlir::linalg::MatmulTransposeBOp::create (OpBuilder & builder, Location location, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4096 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
Referenced by mlir::linalg::transposeMatmul().
isDefaultIndexingMaps()
bool mlir::linalg::MatmulTransposeBOp::isDefaultIndexingMaps (Attribute attr) static
Checks if the affine map is the expected one for this operation.
Definition at line 4073 of file LinalgOps.cpp.
References mlir::linalg::getAffineResultPositions().
Referenced by classof().
resolveTypeID()
::mlir::TypeID mlir::linalg::MatmulTransposeBOp::resolveTypeID () inline static
Definition at line 210 of file Linalg.h.
References mlir::TypeID::get().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/IR/Linalg.h
lib/Dialect/Linalg/IR/LinalgOps.cpp