MLIR: mlir::bytecode::detail::IRNumberingState Class Reference
mlir::bytecode::detail::IRNumberingState Class Reference
This class manages numbering IR entities in preparation of bytecode emission.
#include "Bytecode/Writer/IRNumbering.h"
Classes
struct NumberingDialectWriter
Public Member Functions
IRNumberingState (Operation *op, const BytecodeWriterConfig &config)
auto getDialects ()
Return the numbered dialects.
auto getAttributes ()
auto getOpNames ()
auto getTypes ()
unsigned getNumber (Attribute attr)
Return the number for the given IR unit.
unsigned getNumber (Block *block)
unsigned getNumber (Operation *op)
unsigned getNumber (OperationName opName)
unsigned getNumber (Type type)
unsigned getNumber (Value value)
unsigned getNumber (const AsmDialectResourceHandle &resource)
std::pair< unsigned, unsigned > getBlockValueCount (Region *region)
Return the block and value counts of the given region.
unsigned getOperationCount (Block *block)
Return the number of operations in the given block.
bool isIsolatedFromAbove (Operation *op)
Return if the given operation is isolated from above.
int64_t getDesiredBytecodeVersion () const
Get the set desired bytecode version to emit.
Detailed Description
This class manages numbering IR entities in preparation of bytecode emission.
Definition at line 151 of file IRNumbering.h.
Constructor & Destructor Documentation
IRNumberingState()
IRNumberingState::IRNumberingState (Operation * op, const BytecodeWriterConfig & config)
Definition at line 130 of file IRNumbering.cpp.
References mlir::detail::enumerate(), mlir::Region::getOps(), mlir::Operation::getRegions(), groupByDialectPerByte(), and isIsolatedFromAbove().
Member Function Documentation
getAttributes()
auto mlir::bytecode::detail::IRNumberingState::getAttributes () inline
Definition at line 159 of file IRNumbering.h.
getBlockValueCount()
std::pair<unsigned, unsigned> mlir::bytecode::detail::IRNumberingState::getBlockValueCount (Region * region) inline
Return the block and value counts of the given region.
Definition at line 194 of file IRNumbering.h.
getDesiredBytecodeVersion()
int64_t IRNumberingState::getDesiredBytecodeVersion () const
Get the set desired bytecode version to emit.
Definition at line 555 of file IRNumbering.cpp.
References mlir::config.
Referenced by mlir::bytecode::detail::IRNumberingState::NumberingDialectWriter::getBytecodeVersion().
getDialects()
auto mlir::bytecode::detail::IRNumberingState::getDialects () inline
Return the numbered dialects.
Definition at line 156 of file IRNumbering.h.
getNumber() [1/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (Attribute attr) inline
Return the number for the given IR unit.
Definition at line 164 of file IRNumbering.h.
getNumber() [2/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (Block * block) inline
Definition at line 168 of file IRNumbering.h.
getNumber() [3/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (const AsmDialectResourceHandle & resource) inline
Definition at line 188 of file IRNumbering.h.
getNumber() [4/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (Operation * op) inline
Definition at line 172 of file IRNumbering.h.
getNumber() [5/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (OperationName opName) inline
Definition at line 176 of file IRNumbering.h.
getNumber() [6/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (Type type) inline
Definition at line 180 of file IRNumbering.h.
getNumber() [7/7]
unsigned mlir::bytecode::detail::IRNumberingState::getNumber (Value value) inline
Definition at line 184 of file IRNumbering.h.
getOperationCount()
unsigned mlir::bytecode::detail::IRNumberingState::getOperationCount (Block * block) inline
Return the number of operations in the given block.
Definition at line 200 of file IRNumbering.h.
getOpNames()
auto mlir::bytecode::detail::IRNumberingState::getOpNames () inline
Definition at line 160 of file IRNumbering.h.
getTypes()
auto mlir::bytecode::detail::IRNumberingState::getTypes () inline
Definition at line 161 of file IRNumbering.h.
isIsolatedFromAbove()
bool mlir::bytecode::detail::IRNumberingState::isIsolatedFromAbove (Operation * op) inline
Return if the given operation is isolated from above.
Definition at line 206 of file IRNumbering.h.
Referenced by IRNumberingState().
The documentation for this class was generated from the following files:
lib/Bytecode/Writer/IRNumbering.h
lib/Bytecode/Writer/IRNumbering.cpp