MLIR: mlir::query::matcher::internal::Parser Class Reference
mlir::query::matcher::internal::Parser Class Reference
#include "Query/Matcher/Parser.h"
Classes
class CodeTokenizer
class RegistrySema
struct ScopedContextEntry
class Sema
struct TokenInfo
Public Types
enum class TokenKind {
Eof , NewLine , OpenParen , CloseParen ,
Comma , Period , Literal , Ident ,
InvalidChar , CodeCompletion , Error
}
using NamedValueMap = llvm::StringMap< VariantValue >
Static Public Member Functions
static std::optional< DynMatcher > parseMatcherExpression (llvm::StringRef &matcherCode, const Registry &matcherRegistry, const NamedValueMap *namedValues, Diagnostics *error)
static std::optional< DynMatcher > parseMatcherExpression (llvm::StringRef &matcherCode, const Registry &matcherRegistry, Diagnostics *error)
static bool parseExpression (llvm::StringRef &code, const Registry &matcherRegistry, const NamedValueMap *namedValues, VariantValue *value, Diagnostics *error)
static bool parseExpression (llvm::StringRef &code, const Registry &matcherRegistry, VariantValue *value, Diagnostics *error)
static std::vector< MatcherCompletion > completeExpression (llvm::StringRef &code, unsigned completionOffset, const Registry &matcherRegistry, const NamedValueMap *namedValues)
static std::vector< MatcherCompletion > completeExpression (llvm::StringRef &code, unsigned completionOffset, const Registry &matcherRegistry)
Detailed Description
Definition at line 44 of file Parser.h.
Member Typedef Documentation
NamedValueMap
using mlir::query::matcher::internal::Parser::NamedValueMap = llvm::StringMap<VariantValue>
Definition at line 114 of file Parser.h.
Member Enumeration Documentation
TokenKind
enum mlir::query::matcher::internal::Parser::TokenKind strong
Enumerator
Eof
NewLine
OpenParen
CloseParen
Comma
Period
Literal
Ident
InvalidChar
CodeCompletion
Error
Definition at line 47 of file Parser.h.
Member Function Documentation
completeExpression() [1/2]
static std::vector<MatcherCompletion> mlir::query::matcher::internal::Parser::completeExpression (llvm::StringRef & code, unsigned completionOffset, const Registry & matcherRegistry) inline static
Definition at line 146 of file Parser.h.
References completeExpression().
completeExpression() [2/2]
std::vector< MatcherCompletion > mlir::query::matcher::internal::Parser::completeExpression (llvm::StringRef & code, unsigned completionOffset, const Registry & matcherRegistry, const NamedValueMap * namedValues) static
Definition at line 607 of file Parser.cpp.
Referenced by completeExpression().
parseExpression() [1/2]
bool mlir::query::matcher::internal::Parser::parseExpression (llvm::StringRef & code, const Registry & matcherRegistry, const NamedValueMap * namedValues, VariantValue * value, Diagnostics * error) static
Definition at line 588 of file Parser.cpp.
References mlir::query::matcher::internal::Diagnostics::addError(), Eof, NewLine, mlir::query::matcher::internal::ParserTrailingCode, mlir::query::matcher::internal::Parser::CodeTokenizer::peekNextToken(), and mlir::query::matcher::internal::Parser::TokenInfo::range.
Referenced by parseExpression(), and parseMatcherExpression().
parseExpression() [2/2]
static bool mlir::query::matcher::internal::Parser::parseExpression (llvm::StringRef & code, const Registry & matcherRegistry, VariantValue * value, Diagnostics * error) inline static
Definition at line 134 of file Parser.h.
References parseExpression().
parseMatcherExpression() [1/2]
std::optional< DynMatcher > mlir::query::matcher::internal::Parser::parseMatcherExpression (llvm::StringRef & matcherCode, const Registry & matcherRegistry, const NamedValueMap * namedValues, Diagnostics * error) static
Definition at line 619 of file Parser.cpp.
References mlir::query::matcher::internal::Diagnostics::addError(), mlir::query::matcher::VariantMatcher::getDynMatcher(), mlir::query::matcher::VariantValue::getMatcher(), mlir::query::matcher::VariantValue::getTypeAsString(), mlir::query::matcher::VariantValue::isMatcher(), parseExpression(), mlir::query::matcher::internal::ParserNotAMatcher, and mlir::query::matcher::internal::ParserOverloadedType.
Referenced by parseMatcherExpression().
parseMatcherExpression() [2/2]
static std::optional<DynMatcher> mlir::query::matcher::internal::Parser::parseMatcherExpression (llvm::StringRef & matcherCode, const Registry & matcherRegistry, Diagnostics * error) inline static
Definition at line 123 of file Parser.h.
References parseMatcherExpression().
The documentation for this class was generated from the following files:
lib/Query/Matcher/Parser.h
lib/Query/Matcher/Parser.cpp