MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion Class Reference
Wrapper around an MlirRegion.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyRegion (PyOperationRef parentOperation, MlirRegion region)
operator MlirRegion () const
MlirRegion get ()
PyOperationRef & getParentOperation ()
void checkValid ()
Detailed Description
Wrapper around an MlirRegion.
Regions are managed completely by their containing operation. Unlike the C++ API, the python API does not support detached regions.
Definition at line 787 of file IRCore.h.
Constructor & Destructor Documentation
PyRegion()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::PyRegion (PyOperationRef parentOperation, MlirRegion region) inline
Definition at line 789 of file IRCore.h.
References mlirRegionIsNull().
Member Function Documentation
checkValid()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::checkValid () inline
Definition at line 798 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirRegion mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::get () inline
Definition at line 795 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getParentOperation()
PyOperationRef & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::getParentOperation () inline
Definition at line 796 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirRegion()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::operator MlirRegion () const inline
Definition at line 793 of file IRCore.h.
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/IRCore.h