MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable Class Reference
Bindings for MLIR symbol tables.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PySymbolTable (PyOperationBase &operation)
Constructs a symbol table for the given operation.
~PySymbolTable ()
Destroys the symbol table.
nanobind::object dunderGetItem (const std::string &name)
Returns the symbol (opview) with the given name, throws if there is no such symbol in the table.
void erase (PyOperationBase &symbol)
Removes the given operation from the symbol table and erases it.
void dunderDel (const std::string &name)
Removes the operation with the given name from the symbol table and erases it, throws if there is no such symbol in the table.
PyStringAttribute insert (PyOperationBase &symbol)
Inserts the given operation into the symbol table.
operator MlirSymbolTable ()
Casts the bindings class into the C API structure.
Static Public Member Functions
static PyStringAttribute getSymbolName (PyOperationBase &symbol)
Gets and sets the name of a symbol op.
static void setSymbolName (PyOperationBase &symbol, const std::string &name)
static PyStringAttribute getVisibility (PyOperationBase &symbol)
Gets and sets the visibility of a symbol op.
static void setVisibility (PyOperationBase &symbol, const std::string &visibility)
static void replaceAllSymbolUses (const std::string &oldSymbol, const std::string &newSymbol, PyOperationBase &from)
Replaces all symbol uses within an operation.
static void walkSymbolTables (PyOperationBase &from, bool allSymUsesVisible, nanobind::object callback)
Walks all symbol tables under and including 'from'.
Detailed Description
Bindings for MLIR symbol tables.
Definition at line 1407 of file IRCore.h.
Constructor & Destructor Documentation
PySymbolTable()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::PySymbolTable (PyOperationBase & operation) explicit
Constructs a symbol table for the given operation.
Definition at line 2023 of file IRCore.cpp.
References mlirSymbolTableCreate().
~PySymbolTable()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::~PySymbolTable () inline
Destroys the symbol table.
Definition at line 1413 of file IRCore.h.
References mlirSymbolTableDestroy().
Member Function Documentation
dunderDel()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::dunderDel (const std::string & name)
Removes the operation with the given name from the symbol table and erases it, throws if there is no such symbol in the table.
Definition at line 2054 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderGetItem()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::dunderGetItem (const std::string & name)
Returns the symbol (opview) with the given name, throws if there is no such symbol in the table.
Definition at line 2031 of file IRCore.cpp.
Referenced by insert().
erase()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::erase (PyOperationBase & symbol)
Removes the given operation from the symbol table and erases it.
Definition at line 2044 of file IRCore.cpp.
Referenced by insert(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getSymbolName()
PyStringAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::getSymbolName (PyOperationBase & symbol) static
Gets and sets the name of a symbol op.
Definition at line 2071 of file IRCore.cpp.
References mlirSymbolTableInsert().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getVisibility()
PyStringAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::getVisibility (PyOperationBase & symbol) static
Gets and sets the visibility of a symbol op.
Definition at line 2099 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
insert()
PyStringAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::insert (PyOperationBase & symbol)
Inserts the given operation into the symbol table.
The operation must have the symbol trait.
Definition at line 2059 of file IRCore.cpp.
References dunderGetItem(), and erase().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirSymbolTable()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::operator MlirSymbolTable () inline
Casts the bindings class into the C API structure.
Definition at line 1450 of file IRCore.h.
replaceAllSymbolUses()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::replaceAllSymbolUses (const std::string & oldSymbol, const std::string & newSymbol, PyOperationBase & from) static
Replaces all symbol uses within an operation.
See the API mlirSymbolTableReplaceAllSymbolUses for all caveats.
Definition at line 2128 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
setSymbolName()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::setSymbolName (PyOperationBase & symbol, const std::string & name) static
Definition at line 2084 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
setVisibility()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::setVisibility (PyOperationBase & symbol, const std::string & visibility) static
Definition at line 2110 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
walkSymbolTables()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::walkSymbolTables (PyOperationBase & from, bool allSymUsesVisible, nanobind::object callback) static
Walks all symbol tables under and including 'from'.
Definition at line 2140 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp