MLIR: mlir::bufferization::AliasList< T > Class Template Reference
mlir::bufferization::AliasList< T > Class Template Reference
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
Public Member Functions
AliasList ()=default
Create an empty list of aliases.
AliasList (std::initializer_list< T > elems)
Create a list of aliases.
AliasList (SmallVector< T > &&aliases)
Create a list of aliases.
ArrayRef< T > getAliases () const
size_t getNumAliases () const
void addAlias (T alias)
auto begin () const
auto end () const
Detailed Description
template<typename T>
class mlir::bufferization::AliasList< T >
Definition at line 65 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
AliasList() [1/3]
template<typename T > mlir::bufferization::AliasList< T >::AliasList () default
Create an empty list of aliases.
AliasList() [2/3]
template<typename T > mlir::bufferization::AliasList< T >::AliasList (std::initializer_list< T > elems) inline
Create a list of aliases.
Definition at line 71 of file BufferizableOpInterface.h.
References mlir::bufferization::AliasList< T >::addAlias().
AliasList() [3/3]
template<typename T > mlir::bufferization::AliasList< T >::AliasList (SmallVector< T > && aliases) inline
Create a list of aliases.
Definition at line 77 of file BufferizableOpInterface.h.
Member Function Documentation
addAlias()
template<typename T > void mlir::bufferization::AliasList< T >::addAlias (T alias) inline
Definition at line 83 of file BufferizableOpInterface.h.
Referenced by mlir::bufferization::AliasList< T >::AliasList(), mlir::bufferization::detail::unknownGetAliasingOpOperands(), and mlir::bufferization::detail::unknownGetAliasingValues().
begin()
template<typename T > auto mlir::bufferization::AliasList< T >::begin () const inline
Definition at line 85 of file BufferizableOpInterface.h.
end()
template<typename T > auto mlir::bufferization::AliasList< T >::end () const inline
Definition at line 86 of file BufferizableOpInterface.h.
getAliases()
template<typename T > ArrayRef<T> mlir::bufferization::AliasList< T >::getAliases () const inline
Definition at line 79 of file BufferizableOpInterface.h.
Referenced by mlir::bufferization::detail::defaultGetBufferType().
getNumAliases()
template<typename T > size_t mlir::bufferization::AliasList< T >::getNumAliases () const inline
Definition at line 81 of file BufferizableOpInterface.h.
Referenced by mlir::bufferization::detail::defaultGetBufferType(), and mlir::bufferization::AnalysisState::findValueInReverseUseDefChain().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h