MLIR: mlir::detail::PassOptions::ListOption< DataType, OptionParser > Class Template Reference
mlir::detail::PassOptions::ListOption< DataType, OptionParser > Class Template Reference
This class represents a specific pass option that contains a list of values of the provided data type.
#include "mlir/Pass/PassOptions.h"
Public Member Functions
template<typename... Args>
ListOption (PassOptions &parent, StringRef arg, Args &&...args)
~ListOption () override=default
ListOption< DataType, OptionParser > & operator= (const ListOption< DataType, OptionParser > &other)
bool handleOccurrence (unsigned pos, StringRef argName, StringRef arg) override
ListOption< DataType, OptionParser > & operator= (ArrayRef< DataType > values)
Allow assigning from an ArrayRef.
MutableArrayRef< DataType > operator* ()
Allow accessing the data held by this option.
ArrayRef< DataType > operator* () const
Detailed Description
template<typename DataType, typename OptionParser = OptionParser<DataType>>
class mlir::detail::PassOptions::ListOption< DataType, OptionParser >
This class represents a specific pass option that contains a list of values of the provided data type.
The elements within the textual form of this option are parsed assuming they are comma-separated. Delimited sub-ranges within individual elements of the list may contain commas that are not treated as separators for the top-level list.
Definition at line 239 of file PassOptions.h.
Constructor & Destructor Documentation
ListOption()
template<typename DataType, typename OptionParser = OptionParser<DataType>> template<typename... Args> mlir::detail::PassOptions::ListOption< DataType, OptionParser >::ListOption (PassOptions & parent, StringRef arg, Args &&... args) inline
Definition at line 244 of file PassOptions.h.
References mlir::detail::PassOptions::elementParser.
Referenced by operator=(), operator=(), and ~ListOption().
~ListOption()
template<typename DataType, typename OptionParser = OptionParser<DataType>> mlir::detail::PassOptions::ListOption< DataType, OptionParser >::~ListOption () override default
References ListOption().
Member Function Documentation
handleOccurrence()
template<typename DataType, typename OptionParser = OptionParser<DataType>> bool mlir::detail::PassOptions::ListOption< DataType, OptionParser >::handleOccurrence (unsigned pos, StringRef argName, StringRef arg) inline override
Definition at line 269 of file PassOptions.h.
References clear(), mlir::detail::PassOptions::elementParser, and mlir::detail::pass_options::parseCommaSeparatedList().
operator*() [1/2]
template<typename DataType, typename OptionParser = OptionParser<DataType>> MutableArrayRef< DataType > mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator* () inline
Allow accessing the data held by this option.
Definition at line 289 of file PassOptions.h.
operator*() [2/2]
template<typename DataType, typename OptionParser = OptionParser<DataType>> ArrayRef< DataType > mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator* () const inline
Definition at line 292 of file PassOptions.h.
operator=() [1/2]
template<typename DataType, typename OptionParser = OptionParser<DataType>> ListOption< DataType, OptionParser > & mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator= (ArrayRef< DataType > values) inline
Allow assigning from an ArrayRef.
Definition at line 282 of file PassOptions.h.
References ListOption().
operator=() [2/2]
template<typename DataType, typename OptionParser = OptionParser<DataType>> ListOption< DataType, OptionParser > & mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator= (const ListOption< DataType, OptionParser > & other) inline
Definition at line 263 of file PassOptions.h.
References ListOption().
The documentation for this class was generated from the following file:
include/mlir/Pass/PassOptions.h