MLIR: mlir::transform::ApplyToEachResultList Class Reference
mlir::transform::ApplyToEachResultList Class Reference
A list of results of applying a transform op with ApplyEachOpTrait to a single payload operation, co-indexed with the results of the transform op.
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
Public Member Functions
ApplyToEachResultList ()=default
ApplyToEachResultList (unsigned size)
void assign (unsigned size, std::nullptr_t)
Sets the list of results to size null pointers.
template<typename Range>
void assign (Range &&range)
Sets the list of results to the given range of values.
void push_back (Operation *op)
Appends an element to the list.
void push_back (Attribute attr)
void push_back (ApplyToEachResult r)
void reserve (unsigned size)
Reserves space for size elements in the list.
auto begin ()
Iterators over the list.
auto end ()
auto begin () const
auto end () const
size_t size () const
Returns the number of elements in the list.
ApplyToEachResult & operator[] (size_t index)
Element access. Expects the index to be in bounds.
const ApplyToEachResult & operator[] (size_t index) const
Detailed Description
A list of results of applying a transform op with ApplyEachOpTrait to a single payload operation, co-indexed with the results of the transform op.
Definition at line 1409 of file TransformInterfaces.h.
Constructor & Destructor Documentation
ApplyToEachResultList() [1/2]
mlir::transform::ApplyToEachResultList::ApplyToEachResultList () default
ApplyToEachResultList() [2/2]
mlir::transform::ApplyToEachResultList::ApplyToEachResultList (unsigned size) inline explicit
Definition at line 1412 of file TransformInterfaces.h.
References size().
Member Function Documentation
assign() [1/2]
template<typename Range> void mlir::transform::ApplyToEachResultList::assign (Range && range) inline
Sets the list of results to the given range of values.
Definition at line 1419 of file TransformInterfaces.h.
References mlir::get().
assign() [2/2]
void mlir::transform::ApplyToEachResultList::assign (unsigned size, std::nullptr_t) inline
Sets the list of results to size null pointers.
Definition at line 1415 of file TransformInterfaces.h.
References size().
begin() [1/2]
auto mlir::transform::ApplyToEachResultList::begin () inline
Iterators over the list.
Definition at line 1450 of file TransformInterfaces.h.
begin() [2/2]
auto mlir::transform::ApplyToEachResultList::begin () const inline
Definition at line 1452 of file TransformInterfaces.h.
end() [1/2]
auto mlir::transform::ApplyToEachResultList::end () inline
Definition at line 1451 of file TransformInterfaces.h.
end() [2/2]
auto mlir::transform::ApplyToEachResultList::end () const inline
Definition at line 1453 of file TransformInterfaces.h.
operator[]() [1/2]
ApplyToEachResult & mlir::transform::ApplyToEachResultList::operator[] (size_t index) inline
Element access. Expects the index to be in bounds.
Definition at line 1459 of file TransformInterfaces.h.
operator[]() [2/2]
const ApplyToEachResult & mlir::transform::ApplyToEachResultList::operator[] (size_t index) const inline
Definition at line 1460 of file TransformInterfaces.h.
push_back() [1/3]
void mlir::transform::ApplyToEachResultList::push_back (ApplyToEachResult r) inline
Definition at line 1444 of file TransformInterfaces.h.
push_back() [2/3]
void mlir::transform::ApplyToEachResultList::push_back (Attribute attr) inline
Definition at line 1443 of file TransformInterfaces.h.
push_back() [3/3]
void mlir::transform::ApplyToEachResultList::push_back (Operation * op) inline
Appends an element to the list.
Definition at line 1442 of file TransformInterfaces.h.
Referenced by doit().
reserve()
void mlir::transform::ApplyToEachResultList::reserve (unsigned size) inline
Reserves space for size elements in the list.
Definition at line 1447 of file TransformInterfaces.h.
References size().
Referenced by mlir::transform::detail::applyTransformToEach().
size()
size_t mlir::transform::ApplyToEachResultList::size () const inline
Returns the number of elements in the list.
Definition at line 1456 of file TransformInterfaces.h.
Referenced by ApplyToEachResultList(), assign(), mlir::transform::detail::checkApplyToOne(), and reserve().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h