MLIR: mlir::OperandRangeRange Class Reference
mlir::OperandRangeRange Class Reference final
This class represents a contiguous range of operand ranges, e.g.
#include "mlir/IR/ValueRange.h"
Public Member Functions
TypeRangeRange getTypes () const
Returns the range of types of the values within this range.
TypeRangeRange getType () const
OperandRangeRange (OperandRange operands, Attribute operandSegments)
Construct a range given a parent set of operands, and an I32 elements attribute containing the sizes of the sub ranges.
OperandRange join () const
Flatten all of the sub ranges into a single contiguous operand range.
Detailed Description
This class represents a contiguous range of operand ranges, e.g.
from a VariadicOfVariadic operand group.
Definition at line 81 of file ValueRange.h.
Constructor & Destructor Documentation
OperandRangeRange()
OperandRangeRange::OperandRangeRange (OperandRange operands, Attribute operandSegments)
Construct a range given a parent set of operands, and an I32 elements attribute containing the sizes of the sub ranges.
Definition at line 400 of file OperationSupport.cpp.
Member Function Documentation
getType()
TypeRangeRange OperandRangeRange::getType () const
Definition at line 22 of file ValueRange.cpp.
References getTypes().
getTypes()
TypeRangeRange OperandRangeRange::getTypes () const
Returns the range of types of the values within this range.
Definition at line 18 of file ValueRange.cpp.
Referenced by getType().
join()
OperandRange OperandRangeRange::join () const
Flatten all of the sub ranges into a single contiguous operand range.
Definition at line 406 of file OperationSupport.cpp.
References getBase().
The documentation for this class was generated from the following files:
include/mlir/IR/ValueRange.h
lib/IR/OperationSupport.cpp
lib/IR/ValueRange.cpp