MLIR: StridedMemrefIterator< T, Rank > Class Template Reference
StridedMemrefIterator< T, Rank > Class Template Reference
Iterate over all elements in a strided memref.
#include "mlir/ExecutionEngine/CRunnerUtils.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = T
using difference_type = std::ptrdiff_t
using pointer = T *
using reference = T &
Public Member Functions
StridedMemrefIterator (StridedMemRefType< T, Rank > &descriptor, int64_t offset=0)
StridedMemrefIterator< T, Rank > & operator++ ()
reference operator* ()
pointer operator-> ()
const std::array< int64_t, Rank > & getIndices ()
bool operator== (const StridedMemrefIterator &other) const
bool operator!= (const StridedMemrefIterator &other) const
Detailed Description
template<typename T, int Rank>
class StridedMemrefIterator< T, Rank >
Iterate over all elements in a strided memref.
Definition at line 211 of file CRunnerUtils.h.
Member Typedef Documentation
difference_type
template<typename T, int Rank> using StridedMemrefIterator< T, Rank >::difference_type = std::ptrdiff_t
Definition at line 215 of file CRunnerUtils.h.
iterator_category
template<typename T, int Rank> using StridedMemrefIterator< T, Rank >::iterator_category = std::forward_iterator_tag
Definition at line 213 of file CRunnerUtils.h.
pointer
template<typename T, int Rank> using StridedMemrefIterator< T, Rank >::pointer = T *
Definition at line 216 of file CRunnerUtils.h.
reference
template<typename T, int Rank> using StridedMemrefIterator< T, Rank >::reference = T &
Definition at line 217 of file CRunnerUtils.h.
value_type
template<typename T, int Rank> using StridedMemrefIterator< T, Rank >::value_type = T
Definition at line 214 of file CRunnerUtils.h.
Constructor & Destructor Documentation
StridedMemrefIterator()
template<typename T, int Rank> StridedMemrefIterator< T, Rank >::StridedMemrefIterator (StridedMemRefType< T, Rank > & descriptor, int64_t offset = 0) inline
Definition at line 219 of file CRunnerUtils.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
getIndices()
template<typename T, int Rank> const std::array< int64_t, Rank > & StridedMemrefIterator< T, Rank >::getIndices () inline
Definition at line 241 of file CRunnerUtils.h.
operator!=()
template<typename T, int Rank> bool StridedMemrefIterator< T, Rank >::operator!= (const StridedMemrefIterator< T, Rank > & other) const inline
Definition at line 247 of file CRunnerUtils.h.
References StridedMemrefIterator().
operator*()
template<typename T, int Rank> reference StridedMemrefIterator< T, Rank >::operator* () inline
Definition at line 238 of file CRunnerUtils.h.
operator++()
template<typename T, int Rank> StridedMemrefIterator< T, Rank > & StridedMemrefIterator< T, Rank >::operator++ () inline
Definition at line 222 of file CRunnerUtils.h.
References StridedMemrefIterator().
operator->()
template<typename T, int Rank> pointer StridedMemrefIterator< T, Rank >::operator-> () inline
Definition at line 239 of file CRunnerUtils.h.
operator==()
template<typename T, int Rank> bool StridedMemrefIterator< T, Rank >::operator== (const StridedMemrefIterator< T, Rank > & other) const inline
Definition at line 243 of file CRunnerUtils.h.
References StridedMemrefIterator().
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/CRunnerUtils.h