MLIR: mlir::AsmDialectResourceHandle Class Reference
mlir::AsmDialectResourceHandle Class Reference
This class represents an opaque handle to a dialect resource entry.
#include "mlir/IR/OpImplementation.h"
Public Member Functions
AsmDialectResourceHandle ()=default
AsmDialectResourceHandle (void *resource, TypeID resourceID, Dialect *dialect)
bool operator== (const AsmDialectResourceHandle &other) const
void * getResource () const
Return an opaque pointer to the referenced resource.
TypeID getTypeID () const
Return the type ID of the resource.
Dialect * getDialect () const
Return the dialect that owns the resource.
Detailed Description
This class represents an opaque handle to a dialect resource entry.
Definition at line 47 of file OpImplementation.h.
Constructor & Destructor Documentation
AsmDialectResourceHandle() [1/2]
mlir::AsmDialectResourceHandle::AsmDialectResourceHandle () default
AsmDialectResourceHandle() [2/2]
mlir::AsmDialectResourceHandle::AsmDialectResourceHandle (void * resource, TypeID resourceID, Dialect * dialect) inline
Definition at line 50 of file OpImplementation.h.
Member Function Documentation
getDialect()
Dialect* mlir::AsmDialectResourceHandle::getDialect () const inline
Return the dialect that owns the resource.
Definition at line 63 of file OpImplementation.h.
Referenced by mlir::AsmDialectResourceHandleBase< DerivedT, ResourceT, DialectT >::getDialect(), and mlir::bytecode::detail::IRNumberingState::NumberingDialectWriter::writeResourceHandle().
getResource()
void* mlir::AsmDialectResourceHandle::getResource () const inline
Return an opaque pointer to the referenced resource.
Definition at line 57 of file OpImplementation.h.
Referenced by llvm::DenseMapInfo< mlir::AsmDialectResourceHandle >::getHashValue(), mlir::AsmDialectResourceHandleBase< DerivedT, ResourceT, DialectT >::getResource(), mlir::hash_value(), and llvm::DenseMapInfo< mlir::AsmDialectResourceHandle >::isEqual().
getTypeID()
TypeID mlir::AsmDialectResourceHandle::getTypeID () const inline
Return the type ID of the resource.
Definition at line 60 of file OpImplementation.h.
Referenced by mlir::AsmDialectResourceHandleBase< DerivedT, ResourceT, DialectT >::AsmDialectResourceHandleBase(), and mlir::AsmDialectResourceHandleBase< DerivedT, ResourceT, DialectT >::classof().
operator==()
bool mlir::AsmDialectResourceHandle::operator== (const AsmDialectResourceHandle & other) const inline
Definition at line 52 of file OpImplementation.h.
The documentation for this class was generated from the following file:
include/mlir/IR/OpImplementation.h