MLIR: mlir::lsp::JSONTransport Class Reference
mlir::lsp::JSONTransport Class Reference
A transport class that performs the JSON-RPC communication with the LSP client.
#include "mlir/Tools/lsp-server-support/Transport.h"
Public Member Functions
JSONTransport (std::unique_ptr< JSONTransportInput > in, raw_ostream &out, bool prettyOutput=false)
JSONTransport (std::FILE *in, raw_ostream &out, JSONStreamStyle style=JSONStreamStyle::Standard, bool prettyOutput=false)
void notify (StringRef method, llvm::json::Value params)
The following methods are used to send a message to the LSP client.
void call (StringRef method, llvm::json::Value params, llvm::json::Value id)
void reply (llvm::json::Value id, llvm::Expected< llvm::json::Value > result)
llvm::Error run (MessageHandler &handler)
Start executing the JSON-RPC transport.
Detailed Description
A transport class that performs the JSON-RPC communication with the LSP client.
Definition at line 88 of file Transport.h.
Constructor & Destructor Documentation
JSONTransport() [1/2]
mlir::lsp::JSONTransport::JSONTransport (std::unique_ptr< JSONTransportInput > in, raw_ostream & out, bool prettyOutput = false) inline
Definition at line 90 of file Transport.h.
JSONTransport() [2/2]
mlir::lsp::JSONTransport::JSONTransport (std::FILE * in, raw_ostream & out, JSONStreamStyle style = JSONStreamStyle::Standard, bool prettyOutput = false) inline
Definition at line 94 of file Transport.h.
Member Function Documentation
call()
void JSONTransport::call (StringRef method, llvm::json::Value params, llvm::json::Value id)
Definition at line 183 of file Transport.cpp.
Referenced by mlir::lsp::MessageHandler::outgoingRequest().
notify()
void JSONTransport::notify (StringRef method, llvm::json::Value params)
The following methods are used to send a message to the LSP client.
Definition at line 176 of file Transport.cpp.
Referenced by mlir::lsp::MessageHandler::outgoingNotification().
reply()
void JSONTransport::reply (llvm::json::Value id, llvm::Expected< llvm::json::Value > result)
Definition at line 192 of file Transport.cpp.
References encodeError().
run()
llvm::Error JSONTransport::run (MessageHandler & handler)
Start executing the JSON-RPC transport.
Definition at line 209 of file Transport.cpp.
References mlir::lsp::Logger::error(), mlir::query::parse(), and toString().
Referenced by mlir::lsp::runMlirLSPServer(), mlir::lsp::runPdllLSPServer(), and mlir::lsp::runTableGenLSPServer().
The documentation for this class was generated from the following files:
include/mlir/Tools/lsp-server-support/Transport.h
lib/Tools/lsp-server-support/Transport.cpp