MLIR: mlir::pdll::ast::CompoundStmt Class Reference
mlir::pdll::ast::CompoundStmt Class Reference final
This statement represents a compound statement, which contains a collection of other statements.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
MutableArrayRef< Stmt * > getChildren ()
Return the children of this compound statement.
ArrayRef< Stmt * > getChildren () const
ArrayRef< Stmt * >::iterator begin () const
ArrayRef< Stmt * >::iterator end () const
Public Member Functions inherited from mlir::pdll::ast::Stmt
Node (TypeID typeID, SMRange loc)
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT, typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static CompoundStmt * create (Context &ctx, SMRange location, ArrayRef< Stmt * > children)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< CompoundStmt, Stmt >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Stmt
static bool classof (const Node *node)
Provide type casting support.
Friends
class llvm::TrailingObjects< CompoundStmt, Stmt * >
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< CompoundStmt, Stmt >
using Base
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< CompoundStmt, Stmt >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This statement represents a compound statement, which contains a collection of other statements.
Definition at line 178 of file Nodes.h.
Member Function Documentation
begin()
ArrayRef< Stmt * >::iterator mlir::pdll::ast::CompoundStmt::begin () const inline
Definition at line 191 of file Nodes.h.
References getChildren().
create()
CompoundStmt * CompoundStmt::create (Context & ctx, SMRange location, ArrayRef< Stmt * > children) static
Definition at line 192 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator(), and getChildren().
end()
ArrayRef< Stmt * >::iterator mlir::pdll::ast::CompoundStmt::end () const inline
Definition at line 192 of file Nodes.h.
References getChildren().
getChildren() [1/2]
MutableArrayRef< Stmt * > mlir::pdll::ast::CompoundStmt::getChildren () inline
Return the children of this compound statement.
Definition at line 185 of file Nodes.h.
Referenced by begin(), create(), and end().
getChildren() [2/2]
ArrayRef< Stmt * > mlir::pdll::ast::CompoundStmt::getChildren () const inline
Definition at line 188 of file Nodes.h.
Friends And Related Symbol Documentation
llvm::TrailingObjects< CompoundStmt, Stmt * >
friend class llvm::TrailingObjects< CompoundStmt, Stmt * > friend
Definition at line 199 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp