MLIR: PatternDescriptorOpInterfaceFallbackModel Class Reference
PatternDescriptorOpInterfaceFallbackModel Class Reference
Fallback model for the PatternDescriptorOpInterface that uses C API callbacks.
Public Member Functions
void setCallbacks (MlirPatternDescriptorOpInterfaceCallbacks callbacks)
Sets the callbacks that this FallbackModel will use.
~PatternDescriptorOpInterfaceFallbackModel ()
void populatePatterns (Operation *op, RewritePatternSet &patterns) const
void populatePatternsWithState (Operation *op, RewritePatternSet &patterns, transform::TransformState &state) const
Static Public Member Functions
static TypeID getInterfaceID ()
static bool classof (const mlir::transform::detail::PatternDescriptorOpInterfaceInterfaceTraits::Concept *op)
Detailed Description
Fallback model for the PatternDescriptorOpInterface that uses C API callbacks.
Definition at line 311 of file Transform.cpp.
Constructor & Destructor Documentation
~PatternDescriptorOpInterfaceFallbackModel()
PatternDescriptorOpInterfaceFallbackModel::~PatternDescriptorOpInterfaceFallbackModel () inline
Definition at line 323 of file Transform.cpp.
Member Function Documentation
classof()
bool PatternDescriptorOpInterfaceFallbackModel::classof (const mlir::transform::detail::PatternDescriptorOpInterfaceInterfaceTraits::Concept * op) inline static
Definition at line 333 of file Transform.cpp.
getInterfaceID()
TypeID PatternDescriptorOpInterfaceFallbackModel::getInterfaceID () inline static
Definition at line 328 of file Transform.cpp.
populatePatterns()
void PatternDescriptorOpInterfaceFallbackModel::populatePatterns (Operation * op, RewritePatternSet & patterns) const inline
Definition at line 341 of file Transform.cpp.
References wrap().
Referenced by populatePatternsWithState().
populatePatternsWithState()
void PatternDescriptorOpInterfaceFallbackModel::populatePatternsWithState (Operation * op, RewritePatternSet & patterns, transform::TransformState & state) const inline
Definition at line 346 of file Transform.cpp.
References populatePatterns(), and wrap().
setCallbacks()
void PatternDescriptorOpInterfaceFallbackModel::setCallbacks (MlirPatternDescriptorOpInterfaceCallbacks callbacks) inline
Sets the callbacks that this FallbackModel will use.
NB: the callbacks can only be set through this method as the RegisteredOperationName::attachInterface mechanism default-constructs the FallbackModel without being able to provide arguments.
Definition at line 319 of file Transform.cpp.
Referenced by mlirPatternDescriptorOpInterfaceAttachFallbackModel().
The documentation for this class was generated from the following file:
lib/CAPI/Dialect/Transform.cpp