MLIR: mlir::GlobalCreator Class Reference
mlir::GlobalCreator Class Reference
#include "mlir/Transforms/BufferUtils.h"
Public Member Functions
GlobalCreator (ModuleOp module)
memref::GlobalOp getGlobalFor (ConstantOp constantOp)
Detailed Description
Definition at line 126 of file BufferUtils.h.
Constructor & Destructor Documentation
GlobalCreator()
mlir::GlobalCreator::GlobalCreator (ModuleOp module) inline explicit
Definition at line 128 of file BufferUtils.h.
Member Function Documentation
getGlobalFor()
memref::GlobalOp GlobalCreator::getGlobalFor (ConstantOp constantOp)
Definition at line 24 of file TensorConstantBufferize.cpp.
References mlir::failure(), getGlobalFor(), mlir::Operation::getName(), op, mlir::RewriterBase::replaceOpWithNewOp(), rewriter, and mlir::success().
Referenced by bufferize(), and getGlobalFor().
The documentation for this class was generated from the following files:
include/mlir/Transforms/BufferUtils.h
lib/Dialect/StandardOps/Transforms/TensorConstantBufferize.cpp