MLIR: mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT > Class Template Reference
mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT > Class Template Reference
Public Types
using Base = EnableArmStreamingBase
Public Member Functions
EnableArmStreamingBase ()
EnableArmStreamingBase (const EnableArmStreamingBase &other)
EnableArmStreamingBase & operator= (const EnableArmStreamingBase &)=delete
EnableArmStreamingBase (EnableArmStreamingBase &&)=delete
EnableArmStreamingBase & operator= (EnableArmStreamingBase &&)=delete
~EnableArmStreamingBase ()=default
::llvm::StringRef getArgument () const override
Return the command line argument used when registering this pass.
::llvm::StringRef getDescription () const override
Return the command line description used when registering this pass.
::llvm::StringRef getName () const override
Returns the derived pass name.
std::unique_ptr<::mlir::Pass > clonePass () const override
A clone method to create a copy of this pass.
void getDependentDialects (::mlir::DialectRegistry &registry) const override
Return the dialect that must be loaded in the context before this pass.
EnableArmStreamingBase (EnableArmStreamingOptions options)
Explicitly declare the TypeID for this class.
Public Member Functions inherited from mlir::OperationPass< mlir::func::FuncOp >
~OperationPass () override=default
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Static Public Member Functions
static constexpr ::llvm::StringLiteral getArgumentName ()
Returns the command-line argument attached to this pass.
static constexpr ::llvm::StringLiteral getPassName ()
Returns the derived pass name.
static bool classof (const ::mlir::Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Attributes
::mlir::Pass::Option< mlir::arm_sme::ArmStreamingMode > streamingMode
::mlir::Pass::Option< mlir::arm_sme::ArmZaMode > zaMode
::mlir::Pass::Option< bool > ifRequiredByOps {*this, "if-required-by-ops", ::llvm::cl::desc(R"PO(Only apply the selected streaming/ZA modes if the function contains ops that implement the ArmSMETileOpInterface.)PO"), ::llvm::cl::init(false)}
::mlir::Pass::Option< bool > ifScalableAndSupported {*this, "if-scalable-and-supported", ::llvm::cl::desc(R"PO(Only apply the selected streaming/ZA modes if the function contains supported scalable vector operations.)PO"), ::llvm::cl::init(false)}
Additional Inherited Members
Protected Member Functions inherited from mlir::OperationPass< mlir::func::FuncOp >
OperationPass (TypeID passID)
OperationPass & operator= (const OperationPass &)=delete
bool canScheduleOn (RegisteredOperationName opName) const final
Indicate if the current pass can be scheduled on the given operation type.
mlir::func::FuncOp getOperation ()
Return the current operation being transformed.
AnalysisT & getAnalysis ()
Query an analysis for the current operation of the specific derived operation type.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
virtual bool canScheduleOn (Operation *op) const
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Static Protected Member Functions inherited from mlir::OperationPass< mlir::func::FuncOp >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Detailed Description
template<typename DerivedT>
class mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >
Definition at line 29 of file EnableArmStreaming.cpp.
Member Typedef Documentation
Base
template<typename DerivedT> using mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::Base = EnableArmStreamingBase
Definition at line 31 of file EnableArmStreaming.cpp.
Constructor & Destructor Documentation
EnableArmStreamingBase() [1/4]
template<typename DerivedT> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::EnableArmStreamingBase () inline
Definition at line 33 of file EnableArmStreaming.cpp.
EnableArmStreamingBase() [2/4]
template<typename DerivedT> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::EnableArmStreamingBase (const EnableArmStreamingBase< DerivedT > & other) inline
Definition at line 34 of file EnableArmStreaming.cpp.
EnableArmStreamingBase() [3/4]
template<typename DerivedT> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::EnableArmStreamingBase (EnableArmStreamingBase< DerivedT > &&) delete
~EnableArmStreamingBase()
template<typename DerivedT> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::~EnableArmStreamingBase () default
EnableArmStreamingBase() [4/4]
template<typename DerivedT> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::EnableArmStreamingBase (EnableArmStreamingOptions options) inline
Explicitly declare the TypeID for this class.
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 74 of file EnableArmStreaming.cpp.
References ifRequiredByOps, ifScalableAndSupported, and zaMode.
Member Function Documentation
classof()
template<typename DerivedT> bool mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::classof (const ::mlir::Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 55 of file EnableArmStreaming.cpp.
clonePass()
template<typename DerivedT> std::unique_ptr<::mlir::Pass > mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::clonePass () const inline override virtual
A clone method to create a copy of this pass.
Implements mlir::Pass.
Definition at line 60 of file EnableArmStreaming.cpp.
References mlir::TypeID::get().
getArgument()
template<typename DerivedT> ::llvm::StringRef mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 44 of file EnableArmStreaming.cpp.
getArgumentName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::getArgumentName () inline static
Returns the command-line argument attached to this pass.
Definition at line 41 of file EnableArmStreaming.cpp.
getDependentDialects()
template<typename DerivedT> void mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::getDependentDialects (::mlir::DialectRegistry & registry) const inline override
Return the dialect that must be loaded in the context before this pass.
Definition at line 65 of file EnableArmStreaming.cpp.
getDescription()
template<typename DerivedT> ::llvm::StringRef mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 46 of file EnableArmStreaming.cpp.
getName()
template<typename DerivedT> ::llvm::StringRef mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 52 of file EnableArmStreaming.cpp.
getPassName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::getPassName () inline static
Returns the derived pass name.
Definition at line 49 of file EnableArmStreaming.cpp.
operator=() [1/2]
template<typename DerivedT> EnableArmStreamingBase & mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::operator= (const EnableArmStreamingBase< DerivedT > &) delete
operator=() [2/2]
template<typename DerivedT> EnableArmStreamingBase & mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::operator= (EnableArmStreamingBase< DerivedT > &&) delete
Member Data Documentation
ifRequiredByOps
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::ifRequiredByOps {*this, "if-required-by-ops", ::llvm::cl::desc(R"PO(Only apply the selected streaming/ZA modes if the function contains ops that implement the ArmSMETileOpInterface.)PO"), ::llvm::cl::init(false)} protected
Definition at line 122 of file EnableArmStreaming.cpp.
Referenced by EnableArmStreamingBase().
ifScalableAndSupported
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::ifScalableAndSupported {*this, "if-scalable-and-supported", ::llvm::cl::desc(R"PO(Only apply the selected streaming/ZA modes if the function contains supported scalable vector operations.)PO"), ::llvm::cl::init(false)} protected
Definition at line 123 of file EnableArmStreaming.cpp.
Referenced by EnableArmStreamingBase().
streamingMode
template<typename DerivedT> ::mlir::Pass::Option<mlir::arm_sme::ArmStreamingMode> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::streamingMode protected
Initial value:
{*this, "streaming-mode", ::llvm::cl::desc(R"PO(Select how streaming-mode is managed at the function-level.)PO"), ::llvm::cl::init(mlir::arm_sme::ArmStreamingMode::Streaming), ::llvm::cl::values(
                clEnumValN(mlir::arm_sme::ArmStreamingMode::Disabled,
                           "disabled", "Streaming mode is disabled."),
                clEnumValN(mlir::arm_sme::ArmStreamingMode::Streaming,
                           "streaming",
                           "Streaming mode is part of the function interface "
                           "(ABI), caller manages PSTATE.SM on entry/exit."),
                clEnumValN(mlir::arm_sme::ArmStreamingMode::StreamingLocally,
                           "streaming-locally",
                           "Streaming mode is internal to the function, callee "
                           "manages PSTATE.SM on entry/exit."),
                clEnumValN(mlir::arm_sme::ArmStreamingMode::StreamingCompatible,
                           "streaming-compatible",
                           "Function supports both streaming and non-streaming "
                           "modes.")
          )}
Definition at line 81 of file EnableArmStreaming.cpp.
zaMode
template<typename DerivedT> ::mlir::Pass::Option<mlir::arm_sme::ArmZaMode> mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >::zaMode protected
Initial value:
{*this, "za-mode", ::llvm::cl::desc(R"PO(Select how ZA-storage is managed at the function-level.)PO"), ::llvm::cl::init(mlir::arm_sme::ArmZaMode::Disabled), ::llvm::cl::values(
                 clEnumValN(mlir::arm_sme::ArmZaMode::Disabled,
                            "disabled", "ZA storage is disabled."),
                 clEnumValN(mlir::arm_sme::ArmZaMode::NewZA,
                            "new-za",
                            "The function has ZA state. The ZA state is "
                            "created on entry and destroyed on exit."),
                 clEnumValN(mlir::arm_sme::ArmZaMode::InZA,
                            "in-za",
                            "The function uses ZA state. The ZA state may "
                            "be used for input."),
                 clEnumValN(mlir::arm_sme::ArmZaMode::OutZA,
                            "out-za",
                            "The function uses ZA state. The ZA state may "
                            "be used for output."),
                 clEnumValN(mlir::arm_sme::ArmZaMode::InOutZA,
                            "inout-za",
                            "The function uses ZA state. The ZA state may "
                            "be used for input and/or output."),
                 clEnumValN(mlir::arm_sme::ArmZaMode::PreservesZA,
                            "preserves-za",
                            "The function shares ZA state. The ZA state may "
                            "not be used for input and/or output and the "
                            "function must return with ZA unchanged")
           )}
Definition at line 97 of file EnableArmStreaming.cpp.
Referenced by EnableArmStreamingBase().
The documentation for this class was generated from the following file:
lib/Dialect/ArmSME/Transforms/EnableArmStreaming.cpp