MLIR: mlir::OpTrait::OneRegion< ConcreteType > Class Template Reference
mlir::OpTrait::OneRegion< ConcreteType > Class Template Reference
This class provides APIs for ops that are known to have a single region.
#include "mlir/IR/OpDefinition.h"
Public Member Functions
Region & getRegion ()
auto getOps ()
Returns a range of operations within the region of this operation.
template<typename OpT >
auto getOps ()
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, OneRegion >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::OneRegion< ConcreteType >
This class provides APIs for ops that are known to have a single region.
Definition at line 556 of file OpDefinition.h.
Member Function Documentation
getOps() [1/2]
template<typename ConcreteType > auto mlir::OpTrait::OneRegion< ConcreteType >::getOps () inline
Returns a range of operations within the region of this operation.
Definition at line 561 of file OpDefinition.h.
References mlir::Region::getOps(), and mlir::OpTrait::OneRegion< ConcreteType >::getRegion().
getOps() [2/2]
template<typename ConcreteType > template<typename OpT > auto mlir::OpTrait::OneRegion< ConcreteType >::getOps () inline
Definition at line 563 of file OpDefinition.h.
References mlir::OpTrait::OneRegion< ConcreteType >::getRegion().
getRegion()
template<typename ConcreteType > Region& mlir::OpTrait::OneRegion< ConcreteType >::getRegion () inline
Definition at line 558 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, OneRegion >::getOperation(), and mlir::Operation::getRegion().
Referenced by mlir::OpTrait::OneRegion< ConcreteType >::getOps().
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::OneRegion< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 567 of file OpDefinition.h.
References mlir::OpTrait::impl::verifyOneRegion().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h