MLIR: mlir::python::nanobind_adaptors::mlir_value_subclass Class Reference
mlir::python::nanobind_adaptors::mlir_value_subclass Class Reference
Creates a custom subclass of mlir.ir.Value, implementing a casting constructor and type checking methods.
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Public Types
using IsAFunctionTy = bool (*)(MlirValue)
Public Member Functions
mlir_value_subclass (nanobind::handle scope, const char *valueClassName, IsAFunctionTy isaFunction)
Subclasses by looking up the super-class dynamically.
mlir_value_subclass (nanobind::handle scope, const char *valueClassName, IsAFunctionTy isaFunction, const nanobind::object &superCls)
Subclasses with a provided mlir.ir.Value super-class.
Public Member Functions inherited from mlir::python::nanobind_adaptors::pure_subclass
pure_subclass (nanobind::handle scope, const char *derivedClassName, const nanobind::object &superClass)
template<typename Func, typename... Extra>
pure_subclass & def (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_property_readonly (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_staticmethod (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_classmethod (const char *name, Func &&f, const Extra &...extra)
nanobind::object get_class () const
Additional Inherited Members
Protected Attributes inherited from mlir::python::nanobind_adaptors::pure_subclass
nanobind::object superClass
nanobind::object thisClass
Detailed Description
Creates a custom subclass of mlir.ir.Value, implementing a casting constructor and type checking methods.
Definition at line 687 of file NanobindAdaptors.h.
Member Typedef Documentation
IsAFunctionTy
using mlir::python::nanobind_adaptors::mlir_value_subclass::IsAFunctionTy = bool (*)(MlirValue)
Definition at line 689 of file NanobindAdaptors.h.
Constructor & Destructor Documentation
mlir_value_subclass() [1/2]
mlir::python::nanobind_adaptors::mlir_value_subclass::mlir_value_subclass (nanobind::handle scope, const char * valueClassName, IsAFunctionTy isaFunction) inline
Subclasses by looking up the super-class dynamically.
Definition at line 692 of file NanobindAdaptors.h.
References mlir_value_subclass().
Referenced by mlir_value_subclass().
mlir_value_subclass() [2/2]
mlir::python::nanobind_adaptors::mlir_value_subclass::mlir_value_subclass (nanobind::handle scope, const char * valueClassName, IsAFunctionTy isaFunction, const nanobind::object & superCls) inline
Subclasses with a provided mlir.ir.Value super-class.
This must be used if the subclass is being defined in the same extension module as the mlir.ir class (otherwise, it will trigger a recursive initialization).
Definition at line 701 of file NanobindAdaptors.h.
References mlir::python::nanobind_adaptors::pure_subclass::def_staticmethod(), MAKE_MLIR_PYTHON_QUALNAME, mlir::python::nanobind_adaptors::pure_subclass::pure_subclass(), and mlir::python::nanobind_adaptors::pure_subclass::thisClass.
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/NanobindAdaptors.h