MLIR: mlir::RaggedArray< T >::iterator Class Reference
mlir::RaggedArray< T >::iterator Class Reference
Iterator over the rows.
#include "mlir/Dialect/Transform/Utils/RaggedArray.h"
Public Member Functions
iterator (RaggedArray &ragged)
Creates the start iterator.
iterator (RaggedArray &ragged, size_t pos)
Creates the end iterator.
MutableArrayRef< T > operator* () const
Dereferences the current iterator. Assumes in-bounds.
iterator & operator++ ()
Increments the iterator.
bool operator== (const iterator &other) const
Compares the two iterators.
Detailed Description
template<typename T>
class mlir::RaggedArray< T >::iterator
Iterator over the rows.
Definition at line 43 of file RaggedArray.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename T> mlir::RaggedArray< T >::iterator::iterator (RaggedArray & ragged) inline explicit
Creates the start iterator.
Definition at line 49 of file RaggedArray.h.
Referenced by operator++(), and operator==().
iterator() [2/2]
template<typename T> mlir::RaggedArray< T >::iterator::iterator (RaggedArray & ragged, size_t pos) inline
Creates the end iterator.
Definition at line 52 of file RaggedArray.h.
Member Function Documentation
operator*()
template<typename T> MutableArrayRef< T > mlir::RaggedArray< T >::iterator::operator* () const inline
Dereferences the current iterator. Assumes in-bounds.
Definition at line 55 of file RaggedArray.h.
operator++()
template<typename T> iterator & mlir::RaggedArray< T >::iterator::operator++ () inline
Increments the iterator.
Definition at line 58 of file RaggedArray.h.
References iterator().
operator==()
template<typename T> bool mlir::RaggedArray< T >::iterator::operator== (const iterator & other) const inline
Compares the two iterators.
Iterators into different ragged arrays compare not equal.
Definition at line 66 of file RaggedArray.h.
References iterator().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/Utils/RaggedArray.h