MLIR: mlir::detail::InterfaceMap Class Reference
mlir::detail::InterfaceMap Class Reference
This class provides an efficient mapping between a given Interface type, and a particular implementation of its concept.
#include "mlir/Support/InterfaceSupport.h"
Public Member Functions
InterfaceMap (InterfaceMap &&)=default
~InterfaceMap ()
template<typename T >
T::Concept * lookup () const
Returns an instance of the concept object for the given interface if it was registered to this map, null otherwise.
bool contains (TypeID interfaceID) const
Returns true if the interface map contains an interface for the given id.
InterfaceMap (MutableArrayRef< std::pair< TypeID, void *>> elements)
Create an InterfaceMap given with the implementation of the interfaces.
template<typename... IfaceModels>
void insert ()
Insert the given models as implementations of the corresponding interfaces for the concrete attribute class.
Static Public Member Functions
template<typename... Types>
static std::enable_if_t< num_interface_types< Types... >::value !=0, InterfaceMap > get ()
Construct an InterfaceMap with the given set of template types.
template<typename... Types>
static std::enable_if_t< num_interface_types< Types... >::value==0, InterfaceMap > get ()
Detailed Description
This class provides an efficient mapping between a given Interface type, and a particular implementation of its concept.
Definition at line 166 of file InterfaceSupport.h.
Constructor & Destructor Documentation
InterfaceMap() [1/2]
mlir::detail::InterfaceMap::InterfaceMap (InterfaceMap &&) default
~InterfaceMap()
mlir::detail::InterfaceMap::~InterfaceMap () inline
Definition at line 178 of file InterfaceSupport.h.
References value.
InterfaceMap() [2/2]
mlir::detail::InterfaceMap::InterfaceMap (MutableArrayRef< std::pair< TypeID, void *>> elements) inline
Create an InterfaceMap given with the implementation of the interfaces.
The use of this constructor is in general discouraged in favor of 'InterfaceMap::get<InterfaceA, ...>()'.
Definition at line 216 of file InterfaceSupport.h.
References mlir::compare().
Member Function Documentation
contains()
bool mlir::detail::InterfaceMap::contains (TypeID interfaceID) const inline
Returns true if the interface map contains an interface for the given id.
Definition at line 211 of file InterfaceSupport.h.
References lookup().
Referenced by mlir::AbstractAttribute::hasInterface().
get() [1/2]
template<typename... Types> static std::enable_if_t<num_interface_types<Types...>::value != 0, InterfaceMap> mlir::detail::InterfaceMap::get () inline static
Construct an InterfaceMap with the given set of template types.
For convenience given that object trait lists may contain other non-interface types, not all of the types need to be interfaces. The provided types that do not represent interfaces are not added to the interface map.
Definition at line 190 of file InterfaceSupport.h.
References value.
get() [2/2]
template<typename... Types> static std::enable_if_t<num_interface_types<Types...>::value == 0, InterfaceMap> mlir::detail::InterfaceMap::get () inline static
Definition at line 200 of file InterfaceSupport.h.
insert()
template<typename... IfaceModels> void mlir::detail::InterfaceMap::insert () inline
Insert the given models as implementations of the corresponding interfaces for the concrete attribute class.
Definition at line 226 of file InterfaceSupport.h.
References mlir::compare(), mlir::TypeID::getAsOpaquePointer(), lookup(), and value.
lookup()
template<typename T > T::Concept* mlir::detail::InterfaceMap::lookup () const inline
Returns an instance of the concept object for the given interface if it was registered to this map, null otherwise.
Definition at line 206 of file InterfaceSupport.h.
References lookup().
Referenced by mlir::AbstractAttribute::getInterface().
The documentation for this class was generated from the following files:
include/mlir/Support/InterfaceSupport.h
lib/Support/InterfaceSupport.cpp