MLIR: mlir::python::PyOperationBase Class Reference
mlir::python::PyOperationBase Class Reference abstract
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
#include "Bindings/Python/IRModule.h"
Public Member Functions
virtual ~PyOperationBase ()=default
void print (std::optional< int64_t > largeElementsLimit, std::optional< int64_t > largeResourceLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool useNameLocAsPrefix, bool assumeVerified, nanobind::object fileObject, bool binary, bool skipRegions)
Implements the bound 'print' method and helps with others.
void print (PyAsmState &state, nanobind::object fileObject, bool binary)
nanobind::object getAsm (bool binary, std::optional< int64_t > largeElementsLimit, std::optional< int64_t > largeResourceLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool useNameLocAsPrefix, bool assumeVerified, bool skipRegions)
void writeBytecode (const nanobind::object &fileObject, std::optional< int64_t > bytecodeVersion)
void walk (std::function< MlirWalkResult(MlirOperation)> callback, MlirWalkOrder walkOrder)
void moveAfter (PyOperationBase &other)
Moves the operation before or after the other operation.
void moveBefore (PyOperationBase &other)
bool isBeforeInBlock (PyOperationBase &other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
bool verify ()
Verify the operation.
virtual PyOperation & getOperation ()=0
Each must provide access to the raw Operation.
Detailed Description
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
Definition at line 598 of file IRModule.h.
Constructor & Destructor Documentation
~PyOperationBase()
virtual mlir::python::PyOperationBase::~PyOperationBase () virtual default
Member Function Documentation
getAsm()
nb::object PyOperationBase::getAsm (bool binary, std::optional< int64_t > largeElementsLimit, std::optional< int64_t > largeResourceLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool useNameLocAsPrefix, bool assumeVerified, bool skipRegions)
Definition at line 1411 of file IRCore.cpp.
References print().
getOperation()
virtual PyOperation& mlir::python::PyOperationBase::getOperation () pure virtual
Each must provide access to the raw Operation.
Implemented in mlir::python::PyOpView, and mlir::python::PyOperation.
Referenced by mlir::python::PyMlirContext::clearOperationAndInside(), mlir::python::PyMlirContext::clearOperationsInside(), mlir::python::PySymbolTable::erase(), getOpResultOrValue(), mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::getVisibility(), mlir::python::PyInsertionPoint::insert(), mlir::python::PySymbolTable::insert(), isBeforeInBlock(), moveAfter(), moveBefore(), mlir::python::PyAsmState::PyAsmState(), mlir::python::PySymbolTable::PySymbolTable(), mlir::python::PySymbolTable::replaceAllSymbolUses(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), verify(), walk(), mlir::python::PySymbolTable::walkSymbolTables(), and writeBytecode().
isBeforeInBlock()
bool PyOperationBase::isBeforeInBlock (PyOperationBase & other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
Note: This function has an average complexity of O(1), but worst case may take O(N) where N is the number of operations within the parent block.
Definition at line 1457 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), getOperation(), and mlirOperationIsBeforeInBlock().
moveAfter()
void PyOperationBase::moveAfter (PyOperationBase & other)
Moves the operation before or after the other operation.
Definition at line 1439 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), getOperation(), and mlirOperationMoveAfter().
moveBefore()
void PyOperationBase::moveBefore (PyOperationBase & other)
Definition at line 1448 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), getOperation(), and mlirOperationMoveBefore().
print() [1/2]
void mlir::python::PyOperationBase::print (PyAsmState & state, nanobind::object fileObject, bool binary)
print() [2/2]
void mlir::python::PyOperationBase::print (std::optional< int64_t > largeElementsLimit, std::optional< int64_t > largeResourceLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool useNameLocAsPrefix, bool assumeVerified, nanobind::object fileObject, bool binary, bool skipRegions)
Implements the bound 'print' method and helps with others.
Referenced by getAsm().
verify()
bool PyOperationBase::verify ()
Verify the operation.
Throws MLIRError if verification fails, and returns true otherwise.
Definition at line 1465 of file IRCore.cpp.
References mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), getOperation(), mlirOperationVerify(), and mlir::python::PyMlirContext::ErrorCapture::take().
walk()
void PyOperationBase::walk (std::function< MlirWalkResult(MlirOperation)> callback, MlirWalkOrder walkOrder)
Definition at line 1379 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), getOperation(), mlirOperationWalk(), and MlirWalkResultInterrupt.
writeBytecode()
void PyOperationBase::writeBytecode (const nanobind::object & fileObject, std::optional< int64_t > bytecodeVersion)
Definition at line 1357 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::config, mlir::PyFileAccumulator::getCallback(), getOperation(), mlir::PyFileAccumulator::getUserData(), mlirBytecodeWriterConfigCreate(), mlirBytecodeWriterConfigDesiredEmitVersion(), mlirBytecodeWriterConfigDestroy(), mlirLogicalResultIsFailure(), mlirOperationWriteBytecode(), and mlirOperationWriteBytecodeWithConfig().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp