MLIR: mlir::PatternBenefit Class Reference
mlir::PatternBenefit Class Reference
This class represents the benefit of a pattern match in a unitless scheme that ranges from 0 (very little benefit) to 65K.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
PatternBenefit ()=default
PatternBenefit (unsigned benefit)
PatternBenefit (const PatternBenefit &)=default
PatternBenefit & operator= (const PatternBenefit &)=default
bool isImpossibleToMatch () const
unsigned short getBenefit () const
If the corresponding pattern can match, return its benefit. If the.
bool operator== (const PatternBenefit &rhs) const
bool operator!= (const PatternBenefit &rhs) const
bool operator< (const PatternBenefit &rhs) const
bool operator> (const PatternBenefit &rhs) const
bool operator<= (const PatternBenefit &rhs) const
bool operator>= (const PatternBenefit &rhs) const
Static Public Member Functions
static PatternBenefit impossibleToMatch ()
Detailed Description
This class represents the benefit of a pattern match in a unitless scheme that ranges from 0 (very little benefit) to 65K.
The most common unit to use here is the "number of operations matched" by the pattern.
This also has a sentinel representation that can be used for patterns that fail to match.
Definition at line 34 of file PatternMatch.h.
Constructor & Destructor Documentation
PatternBenefit() [1/3]
mlir::PatternBenefit::PatternBenefit () default
Referenced by impossibleToMatch(), operator!=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and PatternBenefit().
PatternBenefit() [2/3]
PatternBenefit::PatternBenefit (unsigned benefit)
Definition at line 20 of file PatternMatch.cpp.
PatternBenefit() [3/3]
mlir::PatternBenefit::PatternBenefit (const PatternBenefit &) default
References PatternBenefit().
Member Function Documentation
getBenefit()
unsigned short PatternBenefit::getBenefit () const
If the corresponding pattern can match, return its benefit. If the.
Definition at line 25 of file PatternMatch.cpp.
References isImpossibleToMatch().
Referenced by mlir::PatternApplicator::matchAndRewrite().
impossibleToMatch()
PatternBenefit mlir::PatternBenefit::impossibleToMatch () inline static
Definition at line 43 of file PatternMatch.h.
References PatternBenefit().
Referenced by isImpossibleToMatch().
isImpossibleToMatch()
bool mlir::PatternBenefit::isImpossibleToMatch () const inline
Definition at line 44 of file PatternMatch.h.
References impossibleToMatch().
Referenced by mlir::PatternApplicator::applyCostModel(), and getBenefit().
operator!=()
bool mlir::PatternBenefit::operator!= (const PatternBenefit & rhs) const inline
Definition at line 53 of file PatternMatch.h.
References PatternBenefit(), and rhs.
operator<()
bool mlir::PatternBenefit::operator< (const PatternBenefit & rhs) const inline
Definition at line 54 of file PatternMatch.h.
References PatternBenefit(), and rhs.
operator<=()
bool mlir::PatternBenefit::operator<= (const PatternBenefit & rhs) const inline
Definition at line 58 of file PatternMatch.h.
References PatternBenefit(), and rhs.
operator=()
PatternBenefit & mlir::PatternBenefit::operator= (const PatternBenefit &) default
References PatternBenefit().
operator==()
bool mlir::PatternBenefit::operator== (const PatternBenefit & rhs) const inline
Definition at line 50 of file PatternMatch.h.
References PatternBenefit(), and rhs.
operator>()
bool mlir::PatternBenefit::operator> (const PatternBenefit & rhs) const inline
Definition at line 57 of file PatternMatch.h.
References PatternBenefit(), and rhs.
operator>=()
bool mlir::PatternBenefit::operator>= (const PatternBenefit & rhs) const inline
Definition at line 59 of file PatternMatch.h.
References PatternBenefit(), and rhs.
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp