MLIR: mlir::ConstantIntOp Class Reference
mlir::ConstantIntOp Class Reference
This is a refinement of the "constant" op for the case where it is returning an integer value of IntegerType.
#include "mlir/Dialect/StandardOps/IR/Ops.h"
Public Member Functions
int64_t getValue ()
Static Public Member Functions
static void build (OpBuilder &builder, OperationState &result, int64_t value, unsigned width)
Build a constant int op producing an integer of the specified width.
static void build (OpBuilder &builder, OperationState &result, int64_t value, Type type)
Build a constant int op producing an integer with the specified type, which must be an integer type.
static bool classof (Operation *op)
ConstantIntOp only matches values whose result type is an IntegerType.
Detailed Description
This is a refinement of the "constant" op for the case where it is returning an integer value of IntegerType.
%1 = "std.constant"(){value: 42} : i32
Definition at line 69 of file Ops.h.
Member Function Documentation
build() [1/2]
void ConstantIntOp::build (OpBuilder & builder, OperationState & result, int64_t value, unsigned width) static
Build a constant int op producing an integer of the specified width.
Definition at line 1267 of file Ops.cpp.
References mlir::Builder::getIntegerAttr(), and mlir::Builder::getIntegerType().
build() [2/2]
void ConstantIntOp::build (OpBuilder & builder, OperationState & result, int64_t value, Type type) static
Build a constant int op producing an integer with the specified type, which must be an integer type.
Definition at line 1275 of file Ops.cpp.
References mlir::Builder::getIntegerAttr(), and mlir::Type::isSignlessInteger().
classof()
bool ConstantIntOp::classof (Operation * op) static
ConstantIntOp only matches values whose result type is an IntegerType.
Definition at line 1262 of file Ops.cpp.
References mlir::Operation::getResult(), mlir::Value::getType(), and mlir::Type::isSignlessInteger().
getValue()
int64_t mlir::ConstantIntOp::getValue () inline
Definition at line 81 of file Ops.h.
References mlir::ConstantFloatOp::classof(), and op.
The documentation for this class was generated from the following files:
include/mlir/Dialect/StandardOps/IR/Ops.h
lib/Dialect/StandardOps/IR/Ops.cpp