MLIR: mlir::detail::AsmStateImpl Class Reference
mlir::detail::AsmStateImpl Class Reference
Public Member Functions
AsmStateImpl (Operation *op, const OpPrintingFlags &printerFlags, AsmState::LocationMap *locationMap)
AsmStateImpl (MLIRContext *ctx, const OpPrintingFlags &printerFlags, AsmState::LocationMap *locationMap)
void initializeAliases (Operation *op)
Initialize the alias state to enable the printing of aliases.
AliasState & getAliasState ()
Get the state used for aliases.
SSANameState & getSSANameState ()
Get the state used for SSA names.
DistinctState & getDistinctState ()
Get the state used for distinct attribute identifiers.
DialectInterfaceCollection< OpAsmDialectInterface > & getDialectInterfaces ()
Return the dialects within the context that implement OpAsmDialectInterface.
auto getResourcePrinters ()
Return the non-dialect resource printers.
const OpPrintingFlags & getPrinterFlags () const
Get the printer flags.
void registerOperationLocation (Operation *op, unsigned line, unsigned col)
Register the location, line and column, within the buffer that the given operation was printed at.
DenseMap< Dialect *, SetVector< AsmDialectResourceHandle > > & getDialectResources ()
Return the referenced dialect resources within the printer.
LogicalResult pushCyclicPrinting (const void *opaquePointer)
void popCyclicPrinting ()
Detailed Description
Definition at line 1944 of file AsmPrinter.cpp.
Constructor & Destructor Documentation
AsmStateImpl() [1/2]
mlir::detail::AsmStateImpl::AsmStateImpl (Operation * op, const OpPrintingFlags & printerFlags, AsmState::LocationMap * locationMap) inline explicit
Definition at line 1946 of file AsmPrinter.cpp.
References getContext().
AsmStateImpl() [2/2]
mlir::detail::AsmStateImpl::AsmStateImpl (MLIRContext * ctx, const OpPrintingFlags & printerFlags, AsmState::LocationMap * locationMap) inline explicit
Definition at line 1950 of file AsmPrinter.cpp.
Member Function Documentation
getAliasState()
AliasState & mlir::detail::AsmStateImpl::getAliasState () inline
Get the state used for aliases.
Definition at line 1960 of file AsmPrinter.cpp.
getDialectInterfaces()
DialectInterfaceCollection< OpAsmDialectInterface > & mlir::detail::AsmStateImpl::getDialectInterfaces () inline
Return the dialects within the context that implement OpAsmDialectInterface.
Definition at line 1970 of file AsmPrinter.cpp.
getDialectResources()
DenseMap< Dialect *, SetVector< AsmDialectResourceHandle > > & mlir::detail::AsmStateImpl::getDialectResources () inline
Return the referenced dialect resources within the printer.
Definition at line 1991 of file AsmPrinter.cpp.
getDistinctState()
DistinctState & mlir::detail::AsmStateImpl::getDistinctState () inline
Get the state used for distinct attribute identifiers.
Definition at line 1966 of file AsmPrinter.cpp.
getPrinterFlags()
const OpPrintingFlags & mlir::detail::AsmStateImpl::getPrinterFlags () const inline
Get the printer flags.
Definition at line 1980 of file AsmPrinter.cpp.
getResourcePrinters()
auto mlir::detail::AsmStateImpl::getResourcePrinters () inline
Return the non-dialect resource printers.
Definition at line 1975 of file AsmPrinter.cpp.
getSSANameState()
SSANameState & mlir::detail::AsmStateImpl::getSSANameState () inline
Get the state used for SSA names.
Definition at line 1963 of file AsmPrinter.cpp.
Referenced by mlir::Value::printAsOperand().
initializeAliases()
void mlir::detail::AsmStateImpl::initializeAliases (Operation * op) inline
Initialize the alias state to enable the printing of aliases.
Definition at line 1955 of file AsmPrinter.cpp.
Referenced by mlir::Operation::print().
popCyclicPrinting()
void mlir::detail::AsmStateImpl::popCyclicPrinting () inline
Definition at line 1999 of file AsmPrinter.cpp.
pushCyclicPrinting()
LogicalResult mlir::detail::AsmStateImpl::pushCyclicPrinting (const void * opaquePointer) inline
Definition at line 1995 of file AsmPrinter.cpp.
References success().
registerOperationLocation()
void mlir::detail::AsmStateImpl::registerOperationLocation (Operation * op, unsigned line, unsigned col) inline
Register the location, line and column, within the buffer that the given operation was printed at.
Definition at line 1984 of file AsmPrinter.cpp.
The documentation for this class was generated from the following file:
lib/IR/AsmPrinter.cpp