MLIR: mlir::transform::TransformResults Class Reference
mlir::transform::TransformResults Class Reference
Local mapping between values defined by a specific op implementing the TransformOpInterface and the payload IR ops they correspond to.
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
Public Member Functions
template<typename Range>
void set (OpResult value, Range &&ops)
Indicates that the result of the transform IR op at the given position corresponds to the given list of payload IR ops.
void set (OpResult value, std::initializer_list< Operation * > ops)
Indicates that the result of the transform IR op at the given position corresponds to the given list of payload IR ops.
void setParams (OpResult value, ArrayRef< TransformState::Param > params)
Indicates that the result of the transform IR op at the given position corresponds to the given list of parameters.
template<typename Range>
void setValues (OpResult handle, Range &&values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of payload IR values.
void setValues (OpResult handle, std::initializer_list< Value > values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of payload IR values.
void setMappedValues (OpResult handle, ArrayRef< MappedValue > values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of mapped values.
void setRemainingToEmpty (TransformOpInterface transform)
Sets the currently unset results to empty lists of the kind expected by the corresponding results of the given transform op.
Friends
class TransformState
Detailed Description
Local mapping between values defined by a specific op implementing the TransformOpInterface and the payload IR ops they correspond to.
Definition at line 815 of file TransformInterfaces.h.
Member Function Documentation
set() [1/2]
template<typename Range> void mlir::transform::TransformResults::set (OpResult value, Range && ops) inline
Indicates that the result of the transform IR op at the given position corresponds to the given list of payload IR ops.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformHandleTypeInterface.
Definition at line 824 of file TransformInterfaces.h.
References mlir::OpResult::getResultNumber().
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply(), applyTilingToAll(), forwardEmptyOperands(), mlir::transform::detail::forwardTerminatorOperands(), set(), mlir::transform::detail::setApplyToOneResults(), and setMappedValues().
set() [2/2]
void mlir::transform::TransformResults::set (OpResult value, std::initializer_list< Operation * > ops) inline
Indicates that the result of the transform IR op at the given position corresponds to the given list of payload IR ops.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformHandleTypeInterface.
Definition at line 840 of file TransformInterfaces.h.
References set().
setMappedValues()
void transform::TransformResults::setMappedValues (OpResult handle, ArrayRef< MappedValue > values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of mapped values.
All mapped values are expected to be compatible with the type of the result, e.g., if the result is an operation handle, all mapped values are expected to be payload operations.
Definition at line 1092 of file TransformInterfaces.cpp.
References diag(), dispatchMappedValues(), set(), setParams(), setValues(), and success().
Referenced by setRemainingToEmpty().
setParams()
void transform::TransformResults::setParams (OpResult value, ArrayRef< TransformState::Param > params)
Indicates that the result of the transform IR op at the given position corresponds to the given list of parameters.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformParamTypeInterface.
Definition at line 1079 of file TransformInterfaces.cpp.
References mlir::OpResult::getResultNumber().
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply(), mlir::transform::detail::forwardTerminatorOperands(), mlir::transform::detail::setApplyToOneResults(), and setMappedValues().
setRemainingToEmpty()
void transform::TransformResults::setRemainingToEmpty (TransformOpInterface transform)
Sets the currently unset results to empty lists of the kind expected by the corresponding results of the given transform op.
Definition at line 1113 of file TransformInterfaces.cpp.
References setMappedValues().
Referenced by mlir::transform::TransformState::applyTransform().
setValues() [1/2]
template<typename Range> void mlir::transform::TransformResults::setValues (OpResult handle, Range && values) inline
Indicates that the result of the transform IR op at the given position corresponds to the given range of payload IR values.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformValueHandleTypeInterface.
Definition at line 856 of file TransformInterfaces.h.
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply(), mlir::transform::detail::forwardTerminatorOperands(), mlir::transform::detail::setApplyToOneResults(), setMappedValues(), and setValues().
setValues() [2/2]
void mlir::transform::TransformResults::setValues (OpResult handle, std::initializer_list< Value > values) inline
Indicates that the result of the transform IR op at the given position corresponds to the given range of payload IR values.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformValueHandleTypeInterface.
Definition at line 873 of file TransformInterfaces.h.
References setValues().
Friends And Related Symbol Documentation
TransformState
friend class TransformState friend
Definition at line 816 of file TransformInterfaces.h.
References TransformState.
Referenced by TransformState.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h
lib/Dialect/Transform/Interfaces/TransformInterfaces.cpp