MLIR: mlir::tracing::Breakpoint Class Reference
mlir::tracing::Breakpoint Class Reference abstract
This abstract class represents a breakpoint.
#include "mlir/Debug/BreakpointManager.h"
Public Member Functions
virtual ~Breakpoint ()=default
TypeID getTypeID () const
TypeID for the subclass, used for casting purpose.
bool isEnabled () const
void enable ()
void disable ()
virtual void print (raw_ostream &os) const =0
Protected Member Functions
Breakpoint (TypeID typeID)
Detailed Description
This abstract class represents a breakpoint.
Definition at line 19 of file BreakpointManager.h.
Constructor & Destructor Documentation
~Breakpoint()
virtual mlir::tracing::Breakpoint::~Breakpoint () virtual default
Breakpoint()
mlir::tracing::Breakpoint::Breakpoint (TypeID typeID) inline protected
Definition at line 32 of file BreakpointManager.h.
References true.
Referenced by mlir::tracing::BreakpointBase< Derived >::BreakpointBase(), and mlir::tracing::BreakpointBase< Derived >::classof().
Member Function Documentation
disable()
void mlir::tracing::Breakpoint::disable () inline
Definition at line 28 of file BreakpointManager.h.
enable()
void mlir::tracing::Breakpoint::enable () inline
Definition at line 27 of file BreakpointManager.h.
getTypeID()
TypeID mlir::tracing::Breakpoint::getTypeID () const inline
TypeID for the subclass, used for casting purpose.
Definition at line 24 of file BreakpointManager.h.
Referenced by mlir::tracing::BreakpointBase< Derived >::classof().
isEnabled()
bool mlir::tracing::Breakpoint::isEnabled () const inline
Definition at line 26 of file BreakpointManager.h.
print()
virtual void mlir::tracing::Breakpoint::print (raw_ostream & os) const pure virtual
Implemented in mlir::tracing::FileLineColLocBreakpoint, and mlir::tracing::TagBreakpoint.
Referenced by mlir::tracing::operator<<().
The documentation for this class was generated from the following file:
include/mlir/Debug/BreakpointManager.h