MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList Class Reference
Blocks are exposed by the C-API as a forward-only linked list.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyBlockList (PyOperationRef operation, MlirRegion region)
PyBlockIterator dunderIter ()
intptr_t dunderLen ()
PyBlock dunderGetItem (intptr_t index)
PyBlock appendBlock (const nanobind::args &pyArgTypes, const std::optional< nanobind::sequence > &pyArgLocs)
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Blocks are exposed by the C-API as a forward-only linked list.
In Python, we present them as a more full-featured list-like container but optimize it for forward iteration. Blocks are always owned by a region.
Definition at line 1553 of file IRCore.h.
Constructor & Destructor Documentation
PyBlockList()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::PyBlockList (PyOperationRef operation, MlirRegion region) inline
Definition at line 1555 of file IRCore.h.
Member Function Documentation
appendBlock()
PyBlock mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::appendBlock (const nanobind::args & pyArgTypes, const std::optional< nanobind::sequence > & pyArgLocs)
Definition at line 273 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::checkValid(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::createBlock(), and mlirRegionAppendOwnedBlock().
Referenced by bind().
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::bind (nanobind::module_ & m) static
Definition at line 281 of file IRCore.cpp.
References appendBlock(), dunderGetItem(), dunderIter(), and dunderLen().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderGetItem()
PyBlock mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::dunderGetItem (intptr_t index)
Definition at line 254 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::checkValid(), dunderLen(), mlirBlockGetNextInRegion(), mlirBlockIsNull(), and mlirRegionGetFirstBlock().
Referenced by bind().
dunderIter()
PyBlockIterator mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::dunderIter ()
Definition at line 238 of file IRCore.cpp.
References mlirRegionGetFirstBlock().
Referenced by bind().
dunderLen()
intptr_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::dunderLen ()
Definition at line 243 of file IRCore.cpp.
References mlirBlockGetNextInRegion(), mlirBlockIsNull(), and mlirRegionGetFirstBlock().
Referenced by bind(), and dunderGetItem().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp