MLIR: mlir::OperationName Class Reference
mlir::OperationName Class Reference
#include "mlir/IR/OperationSupport.h"
Classes
class Impl
struct InterfaceConcept
This class represents a type erased version of an operation.
struct UnregisteredOpModel
Default implementation for unregistered operations.
Public Types
using FoldHookFn
using HasTraitFn = llvm::unique_function<bool(TypeID) const>
using ParseAssemblyFn
using PopulateDefaultAttrsFn
using PrintAssemblyFn
using VerifyInvariantsFn
using VerifyRegionInvariantsFn
Public Member Functions
OperationName (StringRef name, MLIRContext *context)
bool isRegistered () const
Return if this operation is registered.
TypeID getTypeID () const
Return the unique identifier of the derived Op class, or null if not registered.
std::optional< RegisteredOperationName > getRegisteredInfo () const
If this operation is registered, returns the registered information, std::nullopt otherwise.
LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results) const
This hook implements a generalized folder for this operation.
void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context) const
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
template<template< typename T > class Trait>
bool hasTrait () const
Returns true if the operation was registered with a particular trait, e.g.
bool hasTrait (TypeID traitID) const
template<template< typename T > class Trait>
bool mightHaveTrait () const
Returns true if the operation might have the provided trait.
bool mightHaveTrait (TypeID traitID) const
ParseAssemblyFn getParseAssemblyFn () const
Return the static hook for parsing this operation assembly.
void populateDefaultAttrs (NamedAttrList &attrs) const
This hook implements the method to populate defaults attributes that are unset.
void printAssembly (Operation *op, OpAsmPrinter &p, StringRef defaultDialect) const
This hook implements the AsmPrinter for this operation.
LogicalResult verifyInvariants (Operation *op) const
These hooks implement the verifiers for this operation.
LogicalResult verifyRegionInvariants (Operation *op) const
ArrayRef< StringAttr > getAttributeNames () const
Return the list of cached attribute names registered to this operation.
template<typename T>
T::Concept * getInterface () const
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
template<typename... Models>
void attachInterface ()
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
template<typename InterfaceT>
bool hasPromiseOrImplementsInterface () const
Returns true if InterfaceT has been promised by the dialect or implemented.
template<typename T>
bool hasInterface () const
Returns true if this operation has the given interface registered to it.
bool hasInterface (TypeID interfaceID) const
template<typename T>
bool mightHaveInterface () const
Returns true if the operation might have the provided interface.
bool mightHaveInterface (TypeID interfaceID) const
std::optional< Attribute > getInherentAttr (Operation *op, StringRef name) const
Lookup an inherent attribute by name, this method isn't recommended and may be removed in the future.
void setInherentAttr (Operation *op, StringAttr name, Attribute value) const
void populateInherentAttrs (Operation *op, NamedAttrList &attrs) const
LogicalResult verifyInherentAttrs (NamedAttrList &attributes, function_ref< InFlightDiagnostic()> emitError) const
This method exists for backward compatibility purpose when using properties to store inherent attributes, it enables validating the attributes when parsed from the older generic syntax pre-Properties.
int getOpPropertyByteSize () const
This hooks return the number of bytes to allocate for the op properties.
void destroyOpProperties (OpaqueProperties properties) const
This hooks destroy the op properties.
void initOpProperties (OpaqueProperties storage, OpaqueProperties init) const
Initialize the op properties.
void populateDefaultProperties (OpaqueProperties properties) const
Set the default values on the ODS attribute in the properties.
Attribute getOpPropertiesAsAttribute (Operation *op) const
Return the op properties converted to an Attribute.
LogicalResult setOpPropertiesFromAttribute (OperationName opName, OpaqueProperties properties, Attribute attr, function_ref< InFlightDiagnostic()> emitError) const
Define the op properties from the provided Attribute.
void copyOpProperties (OpaqueProperties lhs, OpaqueProperties rhs) const
bool compareOpProperties (OpaqueProperties lhs, OpaqueProperties rhs) const
llvm::hash_code hashOpProperties (OpaqueProperties properties) const
Dialect * getDialect () const
Return the dialect this operation is registered to if the dialect is loaded in the context, or nullptr if the dialect isn't loaded.
StringRef getDialectNamespace () const
Return the name of the dialect this operation is registered to.
StringRef stripDialect () const
Return the operation name with dialect name stripped, if it has one.
MLIRContext * getContext ()
Return the context this operation is associated with.
StringRef getStringRef () const
Return the name of this operation. This always succeeds.
StringAttr getIdentifier () const
Return the name of this operation as a StringAttr.
void print (raw_ostream &os) const
void dump () const
void * getAsOpaquePointer () const
Represent the operation name as an opaque pointer.
bool operator== (const OperationName &rhs) const
bool operator!= (const OperationName &rhs) const
Static Public Member Functions
static OperationName getFromOpaquePointer (const void *pointer)
Protected Member Functions
OperationName (Impl *impl)
Impl * getImpl () const
void setImpl (Impl *rhs)
Detailed Description
Definition at line 88 of file OperationSupport.h.
Member Typedef Documentation
FoldHookFn
using mlir::OperationName::FoldHookFn
Initial value:
 llvm::unique_function<LogicalResult(
      Operation *, ArrayRef<Attribute>, SmallVectorImpl<OpFoldResult> &) const>
Definition at line 90 of file OperationSupport.h.
HasTraitFn
using mlir::OperationName::HasTraitFn = llvm::unique_function<bool(TypeID) const>
Definition at line 92 of file OperationSupport.h.
ParseAssemblyFn
using mlir::OperationName::ParseAssemblyFn
Initial value:
      llvm::unique_function<ParseResult(OpAsmParser &, OperationState &)>
Definition at line 93 of file OperationSupport.h.
PopulateDefaultAttrsFn
using mlir::OperationName::PopulateDefaultAttrsFn
Initial value:
      llvm::unique_function<void(const OperationName &, NamedAttrList &) const>
Definition at line 97 of file OperationSupport.h.
PrintAssemblyFn
using mlir::OperationName::PrintAssemblyFn
Initial value:
      llvm::unique_function<void(Operation *, OpAsmPrinter &, StringRef) const>
Definition at line 99 of file OperationSupport.h.
VerifyInvariantsFn
using mlir::OperationName::VerifyInvariantsFn
Initial value:
      llvm::unique_function<LogicalResult(Operation *) const>
Definition at line 101 of file OperationSupport.h.
VerifyRegionInvariantsFn
using mlir::OperationName::VerifyRegionInvariantsFn
Initial value:
      llvm::unique_function<LogicalResult(Operation *) const>
Definition at line 103 of file OperationSupport.h.
Constructor & Destructor Documentation
OperationName() [1/2]
OperationName::OperationName (StringRef name, MLIRContext * context)
Definition at line 804 of file MLIRContext.cpp.
References mlir::TypeID::get(), mlir::MLIRContext::getImpl(), mlir::MLIRContext::isMultithreadingEnabled(), mlir::MLIRContextImpl::operationInfoMutex, mlir::MLIRContextImpl::operations, and mlir::MLIRContextImpl::registeredOperationsByName.
Referenced by getFromOpaquePointer(), mlir::OperationName::InterfaceConcept::initProperties(), mlir::OperationName::UnregisteredOpModel::initProperties(), operator!=(), operator==(), mlir::OperationName::InterfaceConcept::populateDefaultAttrs(), mlir::OperationName::UnregisteredOpModel::populateDefaultAttrs(), mlir::OperationName::InterfaceConcept::populateDefaultProperties(), mlir::OperationName::UnregisteredOpModel::populateDefaultProperties(), setOpPropertiesFromAttribute(), mlir::OperationName::InterfaceConcept::setPropertiesFromAttr(), mlir::OperationName::UnregisteredOpModel::setPropertiesFromAttr(), mlir::OperationName::InterfaceConcept::verifyInherentAttrs(), and mlir::OperationName::UnregisteredOpModel::verifyInherentAttrs().
OperationName() [2/2]
mlir::OperationName::OperationName (Impl * impl) inline protected
Definition at line 493 of file OperationSupport.h.
Member Function Documentation
attachInterface()
template<typename... Models> void mlir::OperationName::attachInterface () inline
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
Definition at line 351 of file OperationSupport.h.
References getDialect(), getImpl(), mlir::OperationName::Impl::getInterfaceMap(), getTypeID(), mlir::dialect_extension_detail::handleAdditionOfUndefinedPromisedInterface(), and mlir::detail::InterfaceMap::insertModels().
compareOpProperties()
bool mlir::OperationName::compareOpProperties (OpaqueProperties lhs, OpaqueProperties rhs) const inline
Definition at line 448 of file OperationSupport.h.
References mlir::OperationName::InterfaceConcept::compareProperties(), getImpl(), lhs, and rhs.
copyOpProperties()
void mlir::OperationName::copyOpProperties (OpaqueProperties lhs, OpaqueProperties rhs) const inline
Definition at line 444 of file OperationSupport.h.
References mlir::OperationName::InterfaceConcept::copyProperties(), getImpl(), lhs, and rhs.
destroyOpProperties()
void mlir::OperationName::destroyOpProperties (OpaqueProperties properties) const inline
This hooks destroy the op properties.
Definition at line 417 of file OperationSupport.h.
References mlir::OperationName::InterfaceConcept::deleteProperties(), and getImpl().
dump()
void OperationName::dump () const
Definition at line 62 of file AsmPrinter.cpp.
References print().
foldHook()
LogicalResult mlir::OperationName::foldHook (Operation * op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > & results) const inline
This hook implements a generalized folder for this operation.
Operations can implement this to provide simplifications rules that are applied by the Builder::createOrFold API and the canonicalization pass.
This is an intentionally limited interface - implementations of this hook can only perform the following changes to the operation:
They can leave the operation alone and without changing the IR, and return failure.
They can mutate the operation in place, without changing anything else in the IR. In this case, return success.
They can return a list of existing values that can be used instead of the operation. In this case, fill in the results list and return success. The caller will remove the operation and use those results instead.
This allows expression of some simple in-place canonicalizations (e.g. "x+0 -> x", "min(x,y,x,z) -> min(x,y,z)", "x+y-x -> y", etc), as well as generalized constant folding.
Definition at line 261 of file OperationSupport.h.
References mlir::OperationName::InterfaceConcept::foldHook(), and getImpl().
getAsOpaquePointer()
void * mlir::OperationName::getAsOpaquePointer () const inline
Represent the operation name as an opaque pointer.
(Used to support PointerLikeTypeTraits).
Definition at line 483 of file OperationSupport.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::OperationName >::getAsVoidPointer(), llvm::DenseMapInfo< mlir::OperationName >::getHashValue(), and mlir::hash_value().
getAttributeNames()
ArrayRef< StringAttr > mlir::OperationName::getAttributeNames () const inline
Return the list of cached attribute names registered to this operation.
The order of attributes cached here is unique to each type of operation, and the interpretation of this attribute list should generally be driven by the respective operation. In many cases, this caching removes the need to use the raw string name of a known attribute.
For example the ODS generator, with an op defining the following attributes:
let arguments = (ins I32Attr:$attr1, I32Attr:$attr2);
... may produce an order here of ["attr1", "attr2"]. This allows for the ODS generator to directly access the cached name for a known attribute, greatly simplifying the cost and complexity of attribute usage produced by the generator.
Definition at line 336 of file OperationSupport.h.
References mlir::OperationName::Impl::getAttributeNames(), and getImpl().
getCanonicalizationPatterns()
void mlir::OperationName::getCanonicalizationPatterns (RewritePatternSet & results, MLIRContext * context) const inline
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Definition at line 268 of file OperationSupport.h.
References mlir::OperationName::InterfaceConcept::getCanonicalizationPatterns(), and getImpl().
getContext()
MLIRContext * mlir::OperationName::getContext () inline
Return the context this operation is associated with.
Definition at line 470 of file OperationSupport.h.
References getIdentifier().
Referenced by mlir::OperationName::Impl::Impl().
getDialect()
Dialect * mlir::OperationName::getDialect () const inline
Return the dialect this operation is registered to if the dialect is loaded in the context, or nullptr if the dialect isn't loaded.
Definition at line 458 of file OperationSupport.h.
References mlir::OperationName::Impl::getDialect(), getImpl(), mlir::OperationName::Impl::getName(), and isRegistered().
Referenced by attachInterface(), mlir::Operation::getDialect(), getDialectNamespace(), mlir::OpInterface< ConcreteType, Traits >::getInterfaceFor(), and hasPromiseOrImplementsInterface().
getDialectNamespace()
StringRef OperationName::getDialectNamespace () const
Return the name of the dialect this operation is registered to.
Definition at line 840 of file MLIRContext.cpp.
References getDialect(), and getStringRef().
getFromOpaquePointer()
OperationName mlir::OperationName::getFromOpaquePointer (const void * pointer) inline static
Definition at line 484 of file OperationSupport.h.
References OperationName().
Referenced by llvm::DenseMapInfo< mlir::OperationName >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::OperationName >::getFromVoidPointer(), mlir::Pattern::getRootKind(), and llvm::DenseMapInfo< mlir::OperationName >::getTombstoneKey().
getIdentifier()
StringAttr mlir::OperationName::getIdentifier () const inline
Return the name of this operation as a StringAttr.
Definition at line 476 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::Impl::getName().
Referenced by cloneOpWithOperandsAndTypes(), getContext(), getStringRef(), DropUnitDimFromElementwiseOps::matchAndRewrite(), scalarizeVectorOpHelper(), vectorizeOneOp(), and widenOp().
getImpl()
Impl * mlir::OperationName::getImpl () const inline protected
Definition at line 494 of file OperationSupport.h.
Referenced by attachInterface(), compareOpProperties(), copyOpProperties(), destroyOpProperties(), foldHook(), mlir::AffineMap::get(), mlir::AffineMap::get(), mlir::AffineMap::get(), mlir::AffineMap::get(), mlir::MLIRContext::getAffineUniquer(), getAttributeNames(), mlir::MLIRContext::getAttributeUniquer(), getCanonicalizationPatterns(), getDialect(), mlir::RegisteredOperationName::getDialect(), getIdentifier(), getInherentAttr(), getInterface(), getOpPropertiesAsAttribute(), getOpPropertyByteSize(), getParseAssemblyFn(), getTypeID(), mlir::MLIRContext::getTypeUniquer(), hashOpProperties(), hasInterface(), hasTrait(), initOpProperties(), isRegistered(), mightHaveTrait(), populateDefaultAttrs(), populateDefaultProperties(), populateInherentAttrs(), printAssembly(), setInherentAttr(), setOpPropertiesFromAttribute(), verifyInherentAttrs(), verifyInvariants(), and verifyRegionInvariants().
getInherentAttr()
std::optional< Attribute > mlir::OperationName::getInherentAttr (Operation * op, StringRef name) const inline
Lookup an inherent attribute by name, this method isn't recommended and may be removed in the future.
Definition at line 391 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::getInherentAttr().
Referenced by mlir::Operation::getInherentAttr().
getInterface()
template<typename T> T::Concept * mlir::OperationName::getInterface () const inline
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
This should not be used directly.
Definition at line 344 of file OperationSupport.h.
References getImpl(), mlir::OperationName::Impl::getInterfaceMap(), and mlir::detail::InterfaceMap::lookup().
Referenced by mlir::transform::detail::verifyParamProducerTransformOpTrait(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::NavigationTransformOpTrait< OpTy >::verifyTrait(), and mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait().
getOpPropertiesAsAttribute()
Attribute mlir::OperationName::getOpPropertiesAsAttribute (Operation * op) const inline
Return the op properties converted to an Attribute.
Definition at line 432 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::getPropertiesAsAttr().
getOpPropertyByteSize()
int mlir::OperationName::getOpPropertyByteSize () const inline
This hooks return the number of bytes to allocate for the op properties.
Definition at line 412 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::getOpPropertyByteSize().
getParseAssemblyFn()
ParseAssemblyFn mlir::OperationName::getParseAssemblyFn () const inline
Return the static hook for parsing this operation assembly.
Definition at line 294 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::getParseAssemblyFn().
getRegisteredInfo()
std::optional< RegisteredOperationName > mlir::OperationName::getRegisteredInfo () const inline
If this operation is registered, returns the registered information, std::nullopt otherwise.
Definition at line 711 of file OperationSupport.h.
References isRegistered().
Referenced by mlir::Pass::canScheduleOn(), mlir::OpInterface< ConcreteType, Traits >::getInterfaceFor(), mlir::Operation::getRegisteredInfo(), and inferOperationTypes().
getStringRef()
StringRef mlir::OperationName::getStringRef () const inline
Return the name of this operation. This always succeeds.
Definition at line 473 of file OperationSupport.h.
References getIdentifier().
Referenced by addBodyWithPayloadOp(), AncestorKey::AncestorKey(), mlir::transform::detail::checkApplyToOne(), TosaProfileCompliance::checkInvalid(), mlir::Op< ConcreteType, Traits >::classof(), cloneOpWithOperandsAndTypes(), mlir::linalg::generateLibraryCallName(), getDialectNamespace(), getTargetShape(), inferOperationTypes(), mlir::detail::NameOpMatcher::match(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::Diagnostic::operator<<(), print(), mlir::OpState::printOpName(), printShortForm(), reportNewIrLegalizationFatalError(), stripDialect(), mlir::transform::detail::verifyParamProducerTransformOpTrait(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait().
getTypeID()
TypeID mlir::OperationName::getTypeID () const inline
Return the unique identifier of the derived Op class, or null if not registered.
Definition at line 236 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::Impl::getTypeID().
Referenced by attachInterface(), mlir::OpInterface< ConcreteType, Traits >::getInterfaceFor(), and hasPromiseOrImplementsInterface().
hashOpProperties()
llvm::hash_code mlir::OperationName::hashOpProperties (OpaqueProperties properties) const inline
Definition at line 452 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::hashProperties().
hasInterface() [1/2]
template<typename T> bool mlir::OperationName::hasInterface () const inline
Returns true if this operation has the given interface registered to it.
Definition at line 371 of file OperationSupport.h.
References mlir::TypeID::get(), and hasInterface().
Referenced by mlir::transform::detail::checkImplementsTransformOpInterface(), hasInterface(), hasPromiseOrImplementsInterface(), and mightHaveInterface().
hasInterface() [2/2]
bool mlir::OperationName::hasInterface (TypeID interfaceID) const inline
Definition at line 374 of file OperationSupport.h.
References mlir::detail::InterfaceMap::contains(), getImpl(), and mlir::OperationName::Impl::getInterfaceMap().
hasPromiseOrImplementsInterface()
template<typename InterfaceT> bool mlir::OperationName::hasPromiseOrImplementsInterface () const inline
Returns true if InterfaceT has been promised by the dialect or implemented.
Definition at line 363 of file OperationSupport.h.
References getDialect(), getTypeID(), hasInterface(), and mlir::dialect_extension_detail::hasPromisedInterface().
hasTrait() [1/2]
template<template< typename T > class Trait> bool mlir::OperationName::hasTrait () const inline
Returns true if the operation was registered with a particular trait, e.g.
hasTrait<OperandsAreSignlessIntegerLike>(). Returns false if the operation is unregistered.
Definition at line 277 of file OperationSupport.h.
References mlir::TypeID::get(), and hasTrait().
Referenced by mlir::transform::detail::checkImplementsTransformOpInterface(), hasTrait(), and mlir::AsmParserState::Impl::PartialOpDef::PartialOpDef().
hasTrait() [2/2]
bool mlir::OperationName::hasTrait (TypeID traitID) const inline
Definition at line 280 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::hasTrait().
initOpProperties()
void mlir::OperationName::initOpProperties (OpaqueProperties storage, OpaqueProperties init) const inline
Initialize the op properties.
Definition at line 422 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::initProperties().
isRegistered()
bool mlir::OperationName::isRegistered () const inline
Return if this operation is registered.
Definition at line 232 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::Impl::isRegistered().
Referenced by getDialect(), getRegisteredInfo(), mlir::Operation::isRegistered(), mightHaveInterface(), and mightHaveTrait().
mightHaveInterface() [1/2]
template<typename T> bool mlir::OperationName::mightHaveInterface () const inline
Returns true if the operation might have the provided interface.
This means that either the operation is unregistered, or it was registered with the provide interface.
Definition at line 382 of file OperationSupport.h.
References mlir::TypeID::get(), and mightHaveInterface().
Referenced by mightHaveInterface().
mightHaveInterface() [2/2]
bool mlir::OperationName::mightHaveInterface (TypeID interfaceID) const inline
Definition at line 385 of file OperationSupport.h.
References hasInterface(), and isRegistered().
mightHaveTrait() [1/2]
template<template< typename T > class Trait> bool mlir::OperationName::mightHaveTrait () const inline
Returns true if the operation might have the provided trait.
This means that either the operation is unregistered, or it was registered with the provide trait.
Definition at line 286 of file OperationSupport.h.
References mlir::TypeID::get(), and mightHaveTrait().
Referenced by mightHaveTrait().
mightHaveTrait() [2/2]
bool mlir::OperationName::mightHaveTrait (TypeID traitID) const inline
Definition at line 289 of file OperationSupport.h.
References getImpl(), mlir::OperationName::InterfaceConcept::hasTrait(), and isRegistered().
operator!=()
bool mlir::OperationName::operator!= (const OperationName & rhs) const inline
Definition at line 490 of file OperationSupport.h.
References OperationName(), and rhs.
operator==()
bool mlir::OperationName::operator== (const OperationName & rhs) const inline
Definition at line 489 of file OperationSupport.h.
References OperationName(), and rhs.
populateDefaultAttrs()
void mlir::OperationName::populateDefaultAttrs (NamedAttrList & attrs) const inline
This hook implements the method to populate defaults attributes that are unset.
Definition at line 300 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::populateDefaultAttrs().
populateDefaultProperties()
void mlir::OperationName::populateDefaultProperties (OpaqueProperties properties) const inline
Set the default values on the ODS attribute in the properties.
Definition at line 427 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::populateDefaultProperties().
populateInherentAttrs()
void mlir::OperationName::populateInherentAttrs (Operation * op, NamedAttrList & attrs) const inline
Definition at line 400 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::populateInherentAttrs().
Referenced by mlir::Operation::getAttrDictionary().
print()
void OperationName::print (raw_ostream & os) const
Definition at line 60 of file AsmPrinter.cpp.
References getStringRef().
Referenced by dump(), and mlir::operator<<().
printAssembly()
void mlir::OperationName::printAssembly (Operation * op, OpAsmPrinter & p, StringRef defaultDialect) const inline
This hook implements the AsmPrinter for this operation.
Definition at line 305 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::printAssembly().
setImpl()
void mlir::OperationName::setImpl (Impl * rhs) inline protected
Definition at line 495 of file OperationSupport.h.
References rhs.
setInherentAttr()
void mlir::OperationName::setInherentAttr (Operation * op, StringAttr name, Attribute value) const inline
Definition at line 396 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::setInherentAttr().
Referenced by mlir::Operation::setInherentAttr().
setOpPropertiesFromAttribute()
LogicalResult mlir::OperationName::setOpPropertiesFromAttribute (OperationName opName, OpaqueProperties properties, Attribute attr, function_ref< InFlightDiagnostic()> emitError) const inline
Define the op properties from the provided Attribute.
Definition at line 437 of file OperationSupport.h.
References mlir::emitError(), getImpl(), OperationName(), and mlir::OperationName::InterfaceConcept::setPropertiesFromAttr().
stripDialect()
StringRef mlir::OperationName::stripDialect () const inline
Return the operation name with dialect name stripped, if it has one.
Definition at line 467 of file OperationSupport.h.
References getStringRef().
verifyInherentAttrs()
LogicalResult mlir::OperationName::verifyInherentAttrs (NamedAttrList & attributes, function_ref< InFlightDiagnostic()> emitError) const inline
This method exists for backward compatibility purpose when using properties to store inherent attributes, it enables validating the attributes when parsed from the older generic syntax pre-Properties.
Definition at line 407 of file OperationSupport.h.
References mlir::emitError(), getImpl(), and mlir::OperationName::InterfaceConcept::verifyInherentAttrs().
verifyInvariants()
LogicalResult mlir::OperationName::verifyInvariants (Operation * op) const inline
These hooks implement the verifiers for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 313 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::verifyInvariants().
verifyRegionInvariants()
LogicalResult mlir::OperationName::verifyRegionInvariants (Operation * op) const inline
Definition at line 316 of file OperationSupport.h.
References getImpl(), and mlir::OperationName::InterfaceConcept::verifyRegionInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/AsmPrinter.cpp
lib/IR/MLIRContext.cpp