MLIR: mlir::TypeConverter::AttributeConversionResult Class Reference
mlir::TypeConverter::AttributeConversionResult Class Reference
The general result of a type attribute conversion callback, allowing for early termination.
#include "mlir/Transforms/DialectConversion.h"
Public Member Functions
constexpr AttributeConversionResult ()
AttributeConversionResult (Attribute attr)
bool hasResult () const
bool isNa () const
bool isAbort () const
Attribute getResult () const
Static Public Member Functions
static AttributeConversionResult result (Attribute attr)
static AttributeConversionResult na ()
static AttributeConversionResult abort ()
Detailed Description
The general result of a type attribute conversion callback, allowing for early termination.
The default constructor creates the na case.
Definition at line 115 of file DialectConversion.h.
Constructor & Destructor Documentation
AttributeConversionResult() [1/2]
constexpr mlir::TypeConverter::AttributeConversionResult::AttributeConversionResult () inline constexpr
Definition at line 117 of file DialectConversion.h.
AttributeConversionResult() [2/2]
mlir::TypeConverter::AttributeConversionResult::AttributeConversionResult (Attribute attr) inline
Definition at line 118 of file DialectConversion.h.
Member Function Documentation
abort()
TypeConverter::AttributeConversionResult TypeConverter::AttributeConversionResult::abort () static
Definition at line 3202 of file DialectConversion.cpp.
Referenced by mlir::populateAMDGPUMemorySpaceAttributeConversions().
getResult()
Attribute TypeConverter::AttributeConversionResult::getResult () const
Definition at line 3218 of file DialectConversion.cpp.
Referenced by mlir::TypeConverter::convertTypeAttribute().
hasResult()
bool TypeConverter::AttributeConversionResult::hasResult () const
Definition at line 3206 of file DialectConversion.cpp.
Referenced by mlir::TypeConverter::convertTypeAttribute().
isAbort()
bool TypeConverter::AttributeConversionResult::isAbort () const
Definition at line 3214 of file DialectConversion.cpp.
Referenced by mlir::TypeConverter::convertTypeAttribute().
isNa()
bool TypeConverter::AttributeConversionResult::isNa () const
Definition at line 3210 of file DialectConversion.cpp.
na()
TypeConverter::AttributeConversionResult TypeConverter::AttributeConversionResult::na () static
Definition at line 3197 of file DialectConversion.cpp.
result()
TypeConverter::AttributeConversionResult TypeConverter::AttributeConversionResult::result (Attribute attr) static
Definition at line 3192 of file DialectConversion.cpp.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/Utils/DialectConversion.cpp