MLIR: mlir::tblgen::MethodParameters Class Reference
mlir::tblgen::MethodParameters Class Reference
This class contains a list of method parameters for constructor, class methods, and method signatures.
#include "mlir/TableGen/Class.h"
Public Member Functions
MethodParameters (std::initializer_list< MethodParameter > parameters)
Create a list of method parameters.
MethodParameters (SmallVector< MethodParameter > parameters)
void writeDeclTo (raw_indented_ostream &os) const
Write the parameters as part of a method declaration.
void writeDefTo (raw_indented_ostream &os) const
Write the parameters as part of a method definition.
bool subsumes (const MethodParameters &other) const
Determine whether this list of parameters "subsumes" another, which occurs when this parameter list is identical to the other and has zero or more additional default-valued parameters.
unsigned getNumParameters () const
Return the number of parameters.
Detailed Description
This class contains a list of method parameters for constructor, class methods, and method signatures.
Definition at line 93 of file Class.h.
Constructor & Destructor Documentation
MethodParameters() [1/2]
mlir::tblgen::MethodParameters::MethodParameters (std::initializer_list< MethodParameter > parameters) inline
Create a list of method parameters.
Definition at line 96 of file Class.h.
MethodParameters() [2/2]
mlir::tblgen::MethodParameters::MethodParameters (SmallVector< MethodParameter > parameters) inline
Definition at line 98 of file Class.h.
Member Function Documentation
getNumParameters()
unsigned mlir::tblgen::MethodParameters::getNumParameters () const inline
Return the number of parameters.
Definition at line 112 of file Class.h.
Referenced by mlir::tblgen::MethodSignature::getNumParameters().
subsumes()
bool MethodParameters::subsumes (const MethodParameters & other) const
Determine whether this list of parameters "subsumes" another, which occurs when this parameter list is identical to the other and has zero or more additional default-valued parameters.
Definition at line 54 of file Class.cpp.
Referenced by mlir::tblgen::MethodSignature::makesRedundant().
writeDeclTo()
void MethodParameters::writeDeclTo (raw_indented_ostream & os) const
Write the parameters as part of a method declaration.
Definition at line 45 of file Class.cpp.
Referenced by mlir::tblgen::MethodSignature::writeDeclTo().
writeDefTo()
void MethodParameters::writeDefTo (raw_indented_ostream & os) const
Write the parameters as part of a method definition.
Definition at line 49 of file Class.cpp.
Referenced by mlir::tblgen::MethodSignature::writeDefTo().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp