MLIR: mlir::CopyOnWriteArrayRef< T > Class Template Reference
mlir::CopyOnWriteArrayRef< T > Class Template Reference
#include "mlir/Support/ADTExtras.h"
Public Member Functions
CopyOnWriteArrayRef (ArrayRef< T > array)
CopyOnWriteArrayRef & operator= (ArrayRef< T > array)
void insert (size_t index, T value)
void erase (size_t index)
void set (size_t index, T value)
size_t size () const
bool empty () const
operator ArrayRef< T > () const
Detailed Description
template<typename T>
class mlir::CopyOnWriteArrayRef< T >
Definition at line 25 of file ADTExtras.h.
Constructor & Destructor Documentation
CopyOnWriteArrayRef()
template<typename T > mlir::CopyOnWriteArrayRef< T >::CopyOnWriteArrayRef (ArrayRef< T > array) inline
Definition at line 27 of file ADTExtras.h.
Member Function Documentation
empty()
template<typename T > bool mlir::CopyOnWriteArrayRef< T >::empty () const inline
Definition at line 56 of file ADTExtras.h.
Referenced by mlir::VectorType::Builder::dropDim().
erase()
template<typename T > void mlir::CopyOnWriteArrayRef< T >::erase (size_t index) inline
Definition at line 40 of file ADTExtras.h.
References mlir::CopyOnWriteArrayRef< T >::size().
Referenced by mlir::RankedTensorType::Builder::dropDim(), and mlir::VectorType::Builder::dropDim().
insert()
template<typename T > void mlir::CopyOnWriteArrayRef< T >::insert (size_t index, T value) inline
Definition at line 35 of file ADTExtras.h.
Referenced by mlir::RankedTensorType::Builder::insertDim().
operator ArrayRef< T >()
template<typename T > mlir::CopyOnWriteArrayRef< T >::operator ArrayRef< T > () const inline
Definition at line 58 of file ADTExtras.h.
operator=()
template<typename T > CopyOnWriteArrayRef& mlir::CopyOnWriteArrayRef< T >::operator= (ArrayRef< T > array) inline
Definition at line 29 of file ADTExtras.h.
set()
template<typename T > void mlir::CopyOnWriteArrayRef< T >::set (size_t index, T value) inline
Definition at line 52 of file ADTExtras.h.
size()
template<typename T > size_t mlir::CopyOnWriteArrayRef< T >::size () const inline
Definition at line 54 of file ADTExtras.h.
Referenced by mlir::RankedTensorType::Builder::dropDim(), mlir::CopyOnWriteArrayRef< T >::erase(), and mlir::RankedTensorType::Builder::insertDim().
The documentation for this class was generated from the following file:
include/mlir/Support/ADTExtras.h