MLIR: mlir::detail::PassCrashReproducerGenerator Class Reference
mlir::detail::PassCrashReproducerGenerator Class Reference
#include "Pass/PassDetail.h"
Classes
struct Impl
Public Member Functions
PassCrashReproducerGenerator (PassManager::ReproducerStreamFactory &streamFactory, bool localReproducer)
~PassCrashReproducerGenerator ()
void initialize (iterator_range< PassManager::pass_iterator > passes, Operation *op, bool pmFlagVerifyPasses)
Initialize the generator in preparation for reproducer generation.
void finalize (Operation *rootOp, LogicalResult executionResult)
Finalize the current run of the generator, generating any necessary reproducers if the provided execution result is a failure.
void prepareReproducerFor (Pass *pass, Operation *op)
Prepare a new reproducer for the given pass, operating on op.
void prepareReproducerFor (iterator_range< PassManager::pass_iterator > passes, Operation *op)
Prepare a new reproducer for the given passes, operating on op.
void removeLastReproducerFor (Pass *pass, Operation *op)
Remove the last recorded reproducer anchored at the given pass and operation.
Detailed Description
Definition at line 89 of file PassDetail.h.
Constructor & Destructor Documentation
PassCrashReproducerGenerator()
PassCrashReproducerGenerator::PassCrashReproducerGenerator (PassManager::ReproducerStreamFactory & streamFactory, bool localReproducer)
Definition at line 198 of file PassCrashRecovery.cpp.
~PassCrashReproducerGenerator()
PassCrashReproducerGenerator::~PassCrashReproducerGenerator ()
Definition at line 201 of file PassCrashRecovery.cpp.
Member Function Documentation
finalize()
void PassCrashReproducerGenerator::finalize (Operation * rootOp, LogicalResult executionResult)
Finalize the current run of the generator, generating any necessary reproducers if the provided execution result is a failure.
Definition at line 229 of file PassCrashRecovery.cpp.
References mlir::InFlightDiagnostic::attachNote(), diag(), mlir::Operation::emitError(), formatPassOpReproducerMessage(), mlir::Operation::getContext(), mlir::MLIRContext::printOpOnDiagnostic(), mlir::MLIRContext::shouldPrintOpOnDiagnostic(), mlir::succeeded(), and value.
initialize()
void PassCrashReproducerGenerator::initialize (iterator_range< PassManager::pass_iterator > passes, Operation * op, bool pmFlagVerifyPasses)
Initialize the generator in preparation for reproducer generation.
The generator should be reinitialized before each run of the pass manager.
Definition at line 203 of file PassCrashRecovery.cpp.
References mlir::Operation::getContext(), mlir::MLIRContext::isMultithreadingEnabled(), and prepareReproducerFor().
prepareReproducerFor() [1/2]
void PassCrashReproducerGenerator::prepareReproducerFor (Pass * pass, Operation * op)
Prepare a new reproducer for the given pass, operating on op.
Definition at line 281 of file PassCrashRecovery.cpp.
References mlir::Operation::getName(), mlir::Operation::getParentOp(), op, and mlir::Pass::printAsTextualPipeline().
Referenced by initialize(), and removeLastReproducerFor().
prepareReproducerFor() [2/2]
void PassCrashReproducerGenerator::prepareReproducerFor (iterator_range< PassManager::pass_iterator > passes, Operation * op)
Prepare a new reproducer for the given passes, operating on op.
Definition at line 314 of file PassCrashRecovery.cpp.
References op, and mlir::Pass::printAsTextualPipeline().
removeLastReproducerFor()
void PassCrashReproducerGenerator::removeLastReproducerFor (Pass * pass, Operation * op)
Remove the last recorded reproducer anchored at the given pass and operation.
Definition at line 325 of file PassCrashRecovery.cpp.
References mlir::failure(), op, prepareReproducerFor(), removeLastReproducerFor(), and runPasses().
Referenced by removeLastReproducerFor().
The documentation for this class was generated from the following files:
lib/Pass/PassDetail.h
lib/Pass/PassCrashRecovery.cpp