MLIR: mlir::scf::ForLoopPipeliningPattern Class Reference
mlir::scf::ForLoopPipeliningPattern Class Reference
#include "mlir/Dialect/SCF/Transforms/Patterns.h"
Public Member Functions
ForLoopPipeliningPattern (const PipeliningOption &options, MLIRContext *context)
LogicalResult matchAndRewrite (ForOp forOp, PatternRewriter &rewriter) const override
FailureOr< ForOp > returningMatchAndRewrite (ForOp forOp, PatternRewriter &rewriter) const
Public Member Functions inherited from mlir::OpRewritePattern< ForOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1, ArrayRef< StringRef > generatedNames={})
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching and a list of generated ops.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Wrapper around the RewritePattern method that passes the derived op type.
virtual LogicalResult matchAndRewrite (SourceOp op, PatternRewriter &rewriter) const =0
Method that operates on the SourceOp type.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Protected Attributes
PipeliningOption options
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Definition at line 24 of file Patterns.h.
Constructor & Destructor Documentation
ForLoopPipeliningPattern()
mlir::scf::ForLoopPipeliningPattern::ForLoopPipeliningPattern (const PipeliningOption & options, MLIRContext * context) inline
Definition at line 26 of file Patterns.h.
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::scf::ForLoopPipeliningPattern::matchAndRewrite (ForOp forOp, PatternRewriter & rewriter) const inline override
Definition at line 29 of file Patterns.h.
References returningMatchAndRewrite().
returningMatchAndRewrite()
FailureOr<ForOp> mlir::scf::ForLoopPipeliningPattern::returningMatchAndRewrite (ForOp forOp, PatternRewriter & rewriter) const inline
Definition at line 34 of file Patterns.h.
References options, and mlir::scf::pipelineForLoop().
Referenced by matchAndRewrite().
Member Data Documentation
options
PipeliningOption mlir::scf::ForLoopPipeliningPattern::options protected
Definition at line 40 of file Patterns.h.
Referenced by returningMatchAndRewrite().
The documentation for this class was generated from the following file:
include/mlir/Dialect/SCF/Transforms/Patterns.h