MLIR: mlir::sparse_tensor::SparseTensorSpecifier Class Reference
mlir::sparse_tensor::SparseTensorSpecifier Class Reference
#include "Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.h"
Public Member Functions
SparseTensorSpecifier (Value specifier)
operator Value ()
Value getSpecifierField (OpBuilder &builder, Location loc, StorageSpecifierKind kind, std::optional< Level > lvl)
void setSpecifierField (OpBuilder &builder, Location loc, Value v, StorageSpecifierKind kind, std::optional< Level > lvl)
Static Public Member Functions
static Value getInitValue (OpBuilder &builder, Location loc, SparseTensorType stt)
Detailed Description
Definition at line 24 of file SparseTensorDescriptor.h.
Constructor & Destructor Documentation
SparseTensorSpecifier()
mlir::sparse_tensor::SparseTensorSpecifier::SparseTensorSpecifier (Value specifier) inline explicit
Definition at line 26 of file SparseTensorDescriptor.h.
Member Function Documentation
getInitValue()
Value SparseTensorSpecifier::getInitValue (OpBuilder & builder, Location loc, SparseTensorType stt) static
Definition at line 79 of file SparseTensorDescriptor.cpp.
References mlir::get(), and mlir::sparse_tensor::SparseTensorType::getEncoding().
Referenced by createAllocFields().
getSpecifierField()
Value SparseTensorSpecifier::getSpecifierField (OpBuilder & builder, Location loc, StorageSpecifierKind kind, std::optional< Level > lvl)
Definition at line 85 of file SparseTensorDescriptor.cpp.
References kind, and optionalLevelAttr().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueArrayRef >::getSpecifierField().
operator Value()
mlir::sparse_tensor::SparseTensorSpecifier::operator Value () inline
Definition at line 33 of file SparseTensorDescriptor.h.
setSpecifierField()
void SparseTensorSpecifier::setSpecifierField (OpBuilder & builder, Location loc, Value v, StorageSpecifierKind kind, std::optional< Level > lvl)
Definition at line 93 of file SparseTensorDescriptor.cpp.
References mlir::Value::getType(), mlir::Type::isIndex(), kind, and optionalLevelAttr().
Referenced by mlir::sparse_tensor::MutSparseTensorDescriptor::setSpecifierField().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.h
lib/Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.cpp