MLIR: mlir::tblgen::OpMethodParameter Class Reference
mlir::tblgen::OpMethodParameter Class Reference
#include "mlir/TableGen/OpClass.h"
Public Types
enum Property { PP_None = 0x0, PP_Optional = 0x1 }
Public Member Functions
OpMethodParameter (StringRef type, StringRef name, StringRef defaultValue="", Property properties=PP_None)
OpMethodParameter (StringRef type, StringRef name, Property property)
void writeDeclTo (raw_ostream &os) const
void writeDefTo (raw_ostream &os) const
const std::string & getType () const
bool hasDefaultValue () const
Detailed Description
Definition at line 41 of file OpClass.h.
Member Enumeration Documentation
Property
enum mlir::tblgen::OpMethodParameter::Property
Enumerator
PP_None
PP_Optional
Definition at line 44 of file OpClass.h.
Constructor & Destructor Documentation
OpMethodParameter() [1/2]
mlir::tblgen::OpMethodParameter::OpMethodParameter (StringRef type, StringRef name, StringRef defaultValue = "", Property properties = PP_None) inline
Definition at line 49 of file OpClass.h.
OpMethodParameter() [2/2]
mlir::tblgen::OpMethodParameter::OpMethodParameter (StringRef type, StringRef name, Property property) inline
Definition at line 54 of file OpClass.h.
Member Function Documentation
getType()
const std::string& mlir::tblgen::OpMethodParameter::getType () const inline
Definition at line 63 of file OpClass.h.
Referenced by mlir::tblgen::OpMethodResolvedParameters::makesRedundant().
hasDefaultValue()
bool mlir::tblgen::OpMethodParameter::hasDefaultValue () const inline
Definition at line 64 of file OpClass.h.
writeDeclTo()
void mlir::tblgen::OpMethodParameter::writeDeclTo (raw_ostream & os) const inline
Definition at line 58 of file OpClass.h.
Referenced by mlir::tblgen::Class::addConstructorAndPrune(), mlir::tblgen::OpMethodParameters::getKind(), mlir::tblgen::OpMethodSignature::getName(), mlir::tblgen::OpMethodResolvedParameters::getNumParameters(), mlir::tblgen::OpMethod::makesRedundant(), mlir::tblgen::OpMethodUnresolvedParameters::OpMethodUnresolvedParameters(), and mlir::tblgen::OpMethodResolvedParameters::writeDeclTo().
writeDefTo()
void mlir::tblgen::OpMethodParameter::writeDefTo (raw_ostream & os) const inline
Definition at line 61 of file OpClass.h.
Referenced by mlir::tblgen::Class::addConstructorAndPrune(), mlir::tblgen::OpMethodParameters::getKind(), mlir::tblgen::OpMethodSignature::getName(), mlir::tblgen::OpMethodResolvedParameters::getNumParameters(), mlir::tblgen::OpMethod::makesRedundant(), mlir::tblgen::OpConstructor::OpConstructor(), mlir::tblgen::OpMethodUnresolvedParameters::OpMethodUnresolvedParameters(), and mlir::tblgen::OpMethodResolvedParameters::writeDefTo().
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp