MLIR: mlir::query::matcher::VariantValue Class Reference
mlir::query::matcher::VariantValue Class Reference
#include "mlir/Query/Matcher/VariantValue.h"
Public Member Functions
VariantValue ()
VariantValue (const VariantValue &other)
~VariantValue ()
VariantValue & operator= (const VariantValue &other)
VariantValue (const llvm::StringRef string)
VariantValue (const VariantMatcher &matcher)
VariantValue (int64_t signedValue)
VariantValue (bool setBoolean)
bool isString () const
const llvm::StringRef & getString () const
void setString (const llvm::StringRef &string)
bool isMatcher () const
const VariantMatcher & getMatcher () const
void setMatcher (const VariantMatcher &matcher)
bool isSigned () const
int64_t getSigned () const
void setSigned (int64_t signedValue)
bool isBoolean () const
bool getBoolean () const
void setBoolean (bool booleanValue)
std::string getTypeAsString () const
operator bool () const
bool hasValue () const
Detailed Description
Definition at line 82 of file VariantValue.h.
Constructor & Destructor Documentation
VariantValue() [1/6]
mlir::query::matcher::VariantValue::VariantValue () inline
Definition at line 84 of file VariantValue.h.
VariantValue() [2/6]
mlir::query::matcher::VariantValue::VariantValue (const VariantValue & other)
Definition at line 96 of file VariantValue.cpp.
~VariantValue()
mlir::query::matcher::VariantValue::~VariantValue ()
Definition at line 119 of file VariantValue.cpp.
VariantValue() [3/6]
mlir::query::matcher::VariantValue::VariantValue (const llvm::StringRef string)
Definition at line 101 of file VariantValue.cpp.
References mlir::String.
VariantValue() [4/6]
mlir::query::matcher::VariantValue::VariantValue (const VariantMatcher & matcher)
Definition at line 106 of file VariantValue.cpp.
References mlir::query::matcher::Matcher.
VariantValue() [5/6]
mlir::query::matcher::VariantValue::VariantValue (int64_t signedValue)
Definition at line 111 of file VariantValue.cpp.
VariantValue() [6/6]
mlir::query::matcher::VariantValue::VariantValue (bool setBoolean)
Definition at line 115 of file VariantValue.cpp.
References mlir::query::matcher::Boolean, and setBoolean().
Member Function Documentation
getBoolean()
bool mlir::query::matcher::VariantValue::getBoolean () const
Definition at line 175 of file VariantValue.cpp.
Referenced by mlir::query::matcher::internal::ArgTypeTraits< bool >::get(), and operator=().
getMatcher()
const VariantMatcher & mlir::query::matcher::VariantValue::getMatcher () const
Definition at line 197 of file VariantValue.cpp.
References isMatcher().
Referenced by mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::create(), mlir::query::matcher::internal::ArgTypeTraits< DynMatcher >::get(), operator=(), and mlir::query::matcher::internal::Parser::parseMatcherExpression().
getSigned()
int64_t mlir::query::matcher::VariantValue::getSigned () const
Definition at line 165 of file VariantValue.cpp.
Referenced by mlir::query::matcher::internal::ArgTypeTraits< int64_t >::get(), and operator=().
getString()
const llvm::StringRef & mlir::query::matcher::VariantValue::getString () const
Definition at line 184 of file VariantValue.cpp.
References isString().
Referenced by mlir::query::matcher::internal::ArgTypeTraits< llvm::StringRef >::get(), and operator=().
getTypeAsString()
std::string mlir::query::matcher::VariantValue::getTypeAsString () const
Definition at line 208 of file VariantValue.cpp.
Referenced by mlir::query::matcher::internal::Parser::parseMatcherExpression().
hasValue()
bool mlir::query::matcher::VariantValue::hasValue () const inline
Definition at line 118 of file VariantValue.h.
Referenced by operator bool().
isBoolean()
bool mlir::query::matcher::VariantValue::isBoolean () const
Definition at line 173 of file VariantValue.cpp.
Referenced by mlir::query::matcher::internal::ArgTypeTraits< bool >::hasCorrectType().
isMatcher()
bool mlir::query::matcher::VariantValue::isMatcher () const
Definition at line 195 of file VariantValue.cpp.
Referenced by mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::create(), getMatcher(), mlir::query::matcher::internal::ArgTypeTraits< DynMatcher >::hasCorrectType(), and mlir::query::matcher::internal::Parser::parseMatcherExpression().
isSigned()
bool mlir::query::matcher::VariantValue::isSigned () const
Definition at line 163 of file VariantValue.cpp.
Referenced by mlir::query::matcher::internal::ArgTypeTraits< int64_t >::hasCorrectType().
isString()
bool mlir::query::matcher::VariantValue::isString () const
Definition at line 182 of file VariantValue.cpp.
Referenced by getString(), and mlir::query::matcher::internal::ArgTypeTraits< llvm::StringRef >::hasCorrectType().
operator bool()
mlir::query::matcher::VariantValue::operator bool () const inline explicit
Definition at line 117 of file VariantValue.h.
References hasValue().
operator=()
VariantValue & mlir::query::matcher::VariantValue::operator= (const VariantValue & other)
Definition at line 121 of file VariantValue.cpp.
References getBoolean(), getMatcher(), getSigned(), getString(), setBoolean(), setMatcher(), setSigned(), and setString().
setBoolean()
void mlir::query::matcher::VariantValue::setBoolean (bool booleanValue)
Definition at line 177 of file VariantValue.cpp.
Referenced by operator=(), and VariantValue().
setMatcher()
void mlir::query::matcher::VariantValue::setMatcher (const VariantMatcher & matcher)
Definition at line 202 of file VariantValue.cpp.
Referenced by operator=().
setSigned()
void mlir::query::matcher::VariantValue::setSigned (int64_t signedValue)
Definition at line 167 of file VariantValue.cpp.
Referenced by operator=().
setString()
void mlir::query::matcher::VariantValue::setString (const llvm::StringRef & string)
Definition at line 189 of file VariantValue.cpp.
Referenced by operator=().
The documentation for this class was generated from the following files:
include/mlir/Query/Matcher/VariantValue.h
lib/Query/Matcher/VariantValue.cpp