MLIR: mlir::ConvertToLLVMPattern Class Reference
mlir::ConvertToLLVMPattern Class Reference
Base class for operation conversions targeting the LLVM IR dialect.
#include "mlir/Conversion/LLVMCommon/Pattern.h"
Public Member Functions
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::ConversionPattern
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
const TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, const ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Protected Member Functions
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
const LLVMTypeConverter * getTypeConverter () const
Type getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Type getIntPtrType (unsigned addressSpace=0) const
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
Type getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
Type getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Type getPtrType (unsigned addressSpace=0) const
Get the MLIR type wrapping the LLVM ptr type.
Value getStridedElementPtr (ConversionPatternRewriter &rewriter, Location loc, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags=LLVM::GEPNoWrapFlags::none) const
Convenience wrapper for the corresponding helper utility.
bool isConvertibleAndHasIdentityMaps (MemRefType type) const
Returns if the given memref type is convertible to LLVM and has an identity layout map.
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &strides, Value &size, bool sizeInBytes=true) const
Computes sizes, strides and buffer size of memRefType with identity layout.
Value getSizeInBytes (Location loc, Type type, ConversionPatternRewriter &rewriter) const
Computes the size of type in bytes.
Value getNumElements (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter) const
Computes total number of elements for the given MemRef and dynamicSizes.
MemRefDescriptor createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter &rewriter) const
Creates and populates a canonical memref descriptor struct.
LogicalResult copyUnrankedDescriptors (OpBuilder &builder, Location loc, TypeRange origTypes, SmallVectorImpl< Value > &operands, bool toDynamic) const
Copies the memory descriptor for any operands that were unranked descriptors originally to heap-allocated memory (if toDynamic is true) or to stack-allocated memory (otherwise).
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
See ConversionPattern::ConversionPattern for information on the other available constructors.
Protected Member Functions inherited from mlir::ConversionPattern
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
SmallVector< Value > getOneToOneAdaptorOperands (ArrayRef< ValueRange > operands) const
Given an array of value ranges, which are the inputs to a 1:N adaptor, try to extract the single value of each range to construct a the inputs for a 1:1 adaptor.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Static Protected Member Functions
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
Create a constant Op producing a value of resultType from an index-typed integer attribute.
Additional Inherited Members
Public Types inherited from mlir::ConversionPattern
using OpAdaptor = ArrayRef< Value >
using OneToNOpAdaptor = ArrayRef< ValueRange >
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Attributes inherited from mlir::ConversionPattern
const TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
Base class for operation conversions targeting the LLVM IR dialect.
It provides the conversion patterns with access to the LLVMTypeConverter and the LowerToLLVMOptions. The class captures the LLVMTypeConverter and the LowerToLLVMOptions by reference meaning the references have to remain alive during the entire pattern lifetime.
Definition at line 88 of file Pattern.h.
Constructor & Destructor Documentation
ConvertToLLVMPattern()
ConvertToLLVMPattern::ConvertToLLVMPattern (StringRef rootOpName, MLIRContext * context, const LLVMTypeConverter & typeConverter, PatternBenefit benefit = 1)
Definition at line 22 of file Pattern.cpp.
Member Function Documentation
ConversionPattern()
template<typename... Args> mlir::ConversionPattern::ConversionPattern (typename... Args) inline protected
See ConversionPattern::ConversionPattern for information on the other available constructors.
Definition at line 562 of file DialectConversion.h.
copyUnrankedDescriptors()
LogicalResult ConvertToLLVMPattern::copyUnrankedDescriptors (OpBuilder & builder, Location loc, TypeRange origTypes, SmallVectorImpl< Value > & operands, bool toDynamic) const protected
Copies the memory descriptor for any operands that were unranked descriptors originally to heap-allocated memory (if toDynamic is true) or to stack-allocated memory (otherwise).
Also frees the previously used memory (that is assumed to be heap-allocated) if toDynamic is false.
Definition at line 219 of file Pattern.cpp.
References mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::LLVMTypeConverter::convertType(), mlir::get(), mlir::Pattern::getContext(), mlir::LLVMTypeConverter::getIndexType(), mlir::OpBuilder::getInsertionPoint(), mlir::LLVMTypeConverter::getMemRefAddressSpace(), getPtrType(), getTypeConverter(), mlir::LLVM::lookupOrCreateFreeFn(), mlir::LLVM::lookupOrCreateMallocFn(), mlir::UnrankedMemRefDescriptor::memRefDescPtr(), mlir::UnrankedMemRefDescriptor::poison(), and mlir::UnrankedMemRefDescriptor::rank().
Referenced by mlir::GPUReturnOpLowering::matchAndRewrite().
createIndexAttrConstant()
Value ConvertToLLVMPattern::createIndexAttrConstant (OpBuilder & builder, Location loc, Type resultType, int64_t value) static protected
Create a constant Op producing a value of resultType from an index-typed integer attribute.
Definition at line 56 of file Pattern.cpp.
References mlir::Builder::getIndexAttr().
Referenced by createMemRefDescriptor(), getMemRefDescriptorSizes(), and getNumElements().
createMemRefDescriptor()
MemRefDescriptor ConvertToLLVMPattern::createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter & rewriter) const protected
Creates and populates a canonical memref descriptor struct.
Creates and populates the memref descriptor struct given all its fields.
Definition at line 190 of file Pattern.cpp.
References mlir::TypeConverter::convertType(), createIndexAttrConstant(), mlir::detail::enumerate(), getIndexType(), mlir::MemRefDescriptor::poison(), and mlir::ConversionPattern::typeConverter.
Referenced by mlir::GPUDynamicSharedMemoryOpLowering::matchAndRewrite().
getDialect()
LLVM::LLVMDialect & ConvertToLLVMPattern::getDialect () const protected
Returns the LLVM dialect.
Definition at line 32 of file Pattern.cpp.
References mlir::LLVMTypeConverter::getDialect(), and getTypeConverter().
Referenced by mlir::GPUFuncOpLowering::matchAndRewrite().
getElementPtrType()
Type ConvertToLLVMPattern::getElementPtrType (MemRefType type) const protected
Returns the type of a pointer to an element of the memref.
Definition at line 81 of file Pattern.cpp.
References mlir::get(), mlir::LLVMTypeConverter::getMemRefAddressSpace(), and getTypeConverter().
getIndexType()
Type ConvertToLLVMPattern::getIndexType () const protected
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Definition at line 36 of file Pattern.cpp.
References mlir::LLVMTypeConverter::getIndexType(), and getTypeConverter().
Referenced by createMemRefDescriptor(), getMemRefDescriptorSizes(), getNumElements(), and getSizeInBytes().
getIntPtrType()
Type ConvertToLLVMPattern::getIntPtrType (unsigned addressSpace = 0) const protected
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
Definition at line 40 of file Pattern.cpp.
References mlir::get(), mlir::Pattern::getContext(), and getTypeConverter().
getMemRefDescriptorSizes()
void ConvertToLLVMPattern::getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter & rewriter, SmallVectorImpl< Value > & sizes, SmallVectorImpl< Value > & strides, Value & size, bool sizeInBytes = true) const protected
Computes sizes, strides and buffer size of memRefType with identity layout.
Emits constant ops for the static sizes of memRefType, and uses dynamicSizes for the others. Emits instructions to compute strides and buffer size from these sizes.
For example, memref<4x?xf32> with sizeInBytes = true emits: sizes[0] = llvm.mlir.constant(4 : index) : i64 sizes[1] = dynamicSizes[0] strides[1] = llvm.mlir.constant(1 : index) : i64 strides[0] = sizes[0] size = llvm.mul sizes[0], sizes[1] : i64 nullptr = llvm.mlir.zero : !llvm.ptr gep = llvm.getelementptr nullptr[size] : (!llvm.ptr, i64) -> !llvm.ptr, f32 sizeBytes = llvm.ptrtoint gep : !llvm.ptr to i64
If sizeInBytes = false, memref<4x?xf32> emits: sizes[0] = llvm.mlir.constant(4 : index) : i64 sizes[1] = dynamicSizes[0] strides[1] = llvm.mlir.constant(1 : index) : i64 strides[0] = sizes[0] size = llvm.mul sizes[0], sizes[1] : i64
Definition at line 88 of file Pattern.cpp.
References mlir::TypeConverter::convertType(), createIndexAttrConstant(), mlir::get(), mlir::Builder::getContext(), getIndexType(), isConvertibleAndHasIdentityMaps(), and mlir::ConversionPattern::typeConverter.
Referenced by mlir::GPUDynamicSharedMemoryOpLowering::matchAndRewrite().
getNumElements()
Value ConvertToLLVMPattern::getNumElements (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter & rewriter) const protected
Computes total number of elements for the given MemRef and dynamicSizes.
Definition at line 158 of file Pattern.cpp.
References createIndexAttrConstant(), and getIndexType().
getPtrType()
Type ConvertToLLVMPattern::getPtrType (unsigned addressSpace = 0) const protected
Get the MLIR type wrapping the LLVM ptr type.
Definition at line 49 of file Pattern.cpp.
References mlir::get(), mlir::Pattern::getContext(), and getTypeConverter().
Referenced by copyUnrankedDescriptors(), and getVoidPtrType().
getSizeInBytes()
Value ConvertToLLVMPattern::getSizeInBytes (Location loc, Type type, ConversionPatternRewriter & rewriter) const protected
Computes the size of type in bytes.
Definition at line 143 of file Pattern.cpp.
References mlir::TypeConverter::convertType(), mlir::get(), mlir::Builder::getContext(), getIndexType(), and mlir::ConversionPattern::typeConverter.
getStridedElementPtr()
Value ConvertToLLVMPattern::getStridedElementPtr (ConversionPatternRewriter & rewriter, Location loc, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags = LLVM::GEPNoWrapFlags::none) const protected
Convenience wrapper for the corresponding helper utility.
This is a strided getElementPtr variant with linearized subscripts.
Definition at line 64 of file Pattern.cpp.
References mlir::LLVM::getStridedElementPtr(), and getTypeConverter().
getTypeConverter()
const LLVMTypeConverter * ConvertToLLVMPattern::getTypeConverter () const protected
Definition at line 27 of file Pattern.cpp.
References mlir::ConversionPattern::getTypeConverter().
Referenced by copyUnrankedDescriptors(), getDialect(), getElementPtrType(), getIndexType(), getIntPtrType(), getPtrType(), getStridedElementPtr(), getVoidType(), mlir::GPUDynamicSharedMemoryOpLowering::matchAndRewrite(), mlir::GPUFuncOpLowering::matchAndRewrite(), and mlir::GPUReturnOpLowering::matchAndRewrite().
getVoidPtrType()
Type ConvertToLLVMPattern::getVoidPtrType () const protected
Get the MLIR type wrapping the LLVM i8* type.
Definition at line 54 of file Pattern.cpp.
References getPtrType().
getVoidType()
Type ConvertToLLVMPattern::getVoidType () const protected
Gets the MLIR type wrapping the LLVM void type.
Definition at line 45 of file Pattern.cpp.
References mlir::get(), mlir::Pattern::getContext(), and getTypeConverter().
isConvertibleAndHasIdentityMaps()
bool ConvertToLLVMPattern::isConvertibleAndHasIdentityMaps (MemRefType type) const protected
Returns if the given memref type is convertible to LLVM and has an identity layout map.
Definition at line 74 of file Pattern.cpp.
References mlir::TypeConverter::convertType(), and mlir::ConversionPattern::typeConverter.
Referenced by getMemRefDescriptorSizes().
The documentation for this class was generated from the following files:
include/mlir/Conversion/LLVMCommon/Pattern.h
lib/Conversion/LLVMCommon/Pattern.cpp