MLIR: mlir::ValueTypeRange< ValueRangeT > Class Template Reference
mlir::ValueTypeRange< ValueRangeT > Class Template Reference
This class implements iteration on the types of a given range of values.
#include "mlir/IR/TypeRange.h"
Public Member Functions
template<typename Container >
ValueTypeRange (Container &&c)
Type operator[] (size_t index) const
Return the type at the given index.
size_t size () const
Return the size of this range.
Type front ()
Return first type in the range.
template<typename OtherT >
bool operator== (const OtherT &other) const
Compare this range with another.
template<typename OtherT >
bool operator!= (const OtherT &other) const
Detailed Description
template<typename ValueRangeT>
class mlir::ValueTypeRange< ValueRangeT >
This class implements iteration on the types of a given range of values.
Definition at line 133 of file TypeRange.h.
Constructor & Destructor Documentation
ValueTypeRange()
template<typename ValueRangeT > template<typename Container > mlir::ValueTypeRange< ValueRangeT >::ValueTypeRange (Container && c) inline
Definition at line 140 of file TypeRange.h.
Member Function Documentation
front()
template<typename ValueRangeT > Type mlir::ValueTypeRange< ValueRangeT >::front () inline
Return first type in the range.
Definition at line 152 of file TypeRange.h.
Referenced by emitElementwiseComputation(), getTypeConversionFailure(), insertCasts(), printArithmeticExtendedBinaryOp(), mlir::spirv::verifyIntegerDotProduct(), verifyShapeOrExtentTensorOp(), and verifySizeOrIndexOp().
operator!=()
template<typename ValueRangeT > template<typename OtherT > bool mlir::ValueTypeRange< ValueRangeT >::operator!= (const OtherT & other) const inline
Definition at line 161 of file TypeRange.h.
operator==()
template<typename ValueRangeT > template<typename OtherT > bool mlir::ValueTypeRange< ValueRangeT >::operator== (const OtherT & other) const inline
Compare this range with another.
Definition at line 156 of file TypeRange.h.
operator[]()
template<typename ValueRangeT > Type mlir::ValueTypeRange< ValueRangeT >::operator[] (size_t index) const inline
Return the type at the given index.
Definition at line 143 of file TypeRange.h.
References mlir::ValueTypeRange< ValueRangeT >::size().
size()
template<typename ValueRangeT > size_t mlir::ValueTypeRange< ValueRangeT >::size () const inline
Return the size of this range.
Definition at line 149 of file TypeRange.h.
Referenced by mlir::ValueTypeRange< ValueRangeT >::operator[]().
The documentation for this class was generated from the following files:
include/mlir/IR/Block.h
include/mlir/IR/TypeRange.h