MLIR: mlir::presburger::PresburgerSet Class Reference
mlir::presburger::PresburgerSet Class Reference
#include "mlir/Analysis/Presburger/PresburgerRelation.h"
Public Member Functions
PresburgerSet (const IntegerPolyhedron &disjunct)
Create a set from a relation.
PresburgerSet (const PresburgerRelation &set)
PresburgerSet unionSet (const PresburgerRelation &set) const
These operations are the same as the ones in PresburgeRelation, they just forward the arguement and return the result as a set instead of a relation.
PresburgerSet intersect (const PresburgerRelation &set) const
PresburgerSet complement () const
PresburgerSet subtract (const PresburgerRelation &set) const
PresburgerSet coalesce () const
Public Member Functions inherited from mlir::presburger::PresburgerRelation
PresburgerRelation (const IntegerRelation &disjunct)
unsigned getNumDomainVars () const
unsigned getNumRangeVars () const
unsigned getNumSymbolVars () const
unsigned getNumLocalVars () const
unsigned getNumVars () const
unsigned getNumDisjuncts () const
Return the number of disjuncts in the union.
const PresburgerSpace & getSpace () const
void setSpace (const PresburgerSpace &oSpace)
Set the space to oSpace.
void insertVarInPlace (VarKind kind, unsigned pos, unsigned num=1)
void convertVarKind (VarKind srcKind, unsigned srcPos, unsigned num, VarKind dstKind, unsigned dstPos)
Converts variables of the specified kind in the column range [srcPos, srcPos + num) to variables of the specified kind at position dstPos.
ArrayRef< IntegerRelation > getAllDisjuncts () const
Return a reference to the list of disjuncts.
const IntegerRelation & getDisjunct (unsigned index) const
Return the disjunct at the specified index.
void unionInPlace (const IntegerRelation &disjunct)
Mutate this set, turning it into the union of this set and the given disjunct.
void unionInPlace (const PresburgerRelation &set)
Mutate this set, turning it into the union of this set and the given set.
PresburgerRelation unionSet (const PresburgerRelation &set) const
Return the union of this set and the given set.
PresburgerRelation intersect (const PresburgerRelation &set) const
Return the intersection of this set and the given set.
PresburgerRelation intersectRange (const PresburgerSet &set) const
Return the range intersection of the given set with this relation.
PresburgerRelation intersectDomain (const PresburgerSet &set) const
Return the domain intersection of the given set with this relation.
PresburgerSet getDomainSet () const
Return a set corresponding to the domain of the relation.
PresburgerSet getRangeSet () const
Return a set corresponding to the range of the relation.
void inverse ()
Invert the relation, i.e.
void compose (const PresburgerRelation &rel)
Compose this relation with the given relation rel in-place.
void applyDomain (const PresburgerRelation &rel)
Apply the domain of given relation rel to this relation.
void applyRange (const PresburgerRelation &rel)
Same as compose, provided for uniformity with applyDomain.
SymbolicLexOpt findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the relation, i.e.
SymbolicLexOpt findSymbolicIntegerLexMax () const
Compute the symbolic integer lexmax of the relation, i.e.
bool containsPoint (ArrayRef< DynamicAPInt > point) const
Return true if the set contains the given point, and false otherwise.
bool containsPoint (ArrayRef< int64_t > point) const
PresburgerRelation complement () const
Return the complement of this set.
PresburgerRelation subtract (const PresburgerRelation &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
bool isSubsetOf (const PresburgerRelation &set) const
Return true if this set is a subset of the given set, and false otherwise.
bool isEqual (const PresburgerRelation &set) const
Return true if this set is equal to the given set, and false otherwise.
bool isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
bool isObviouslyEmpty () const
Return true if there is no disjunct, false otherwise.
bool isObviouslyUniverse () const
Return true if the set is known to have one unconstrained disjunct, false otherwise.
bool isObviouslyEqual (const PresburgerRelation &set) const
Perform a quick equality check on this and other.
bool isConvexNoLocals () const
Return true if the set is consist of a single disjunct, without any local variables, false otherwise.
bool findIntegerSample (SmallVectorImpl< DynamicAPInt > &sample)
Find an integer sample from the given set.
std::optional< DynamicAPInt > computeVolume () const
Compute an overapproximation of the number of integer points in the disjunct.
PresburgerRelation coalesce () const
Simplifies the representation of a PresburgerRelation.
bool hasOnlyDivLocals () const
Check whether all local ids in all disjuncts have a div representation.
PresburgerRelation computeReprWithOnlyDivLocals () const
Compute an equivalent representation of the same relation, such that all local ids in all disjuncts have division representations.
PresburgerRelation simplify () const
Simplify each disjunct, canonicalizing each disjunct and removing redundencies.
bool isFullDim () const
Return whether the given PresburgerRelation is full-dimensional.
void print (raw_ostream &os) const
Print the set's internal state.
void dump () const
Static Public Member Functions
static PresburgerSet getUniverse (const PresburgerSpace &space)
Return a universe set of the specified type that contains all points.
static PresburgerSet getEmpty (const PresburgerSpace &space)
Return an empty set of the specified type that contains no points.
Static Public Member Functions inherited from mlir::presburger::PresburgerRelation
static PresburgerRelation getUniverse (const PresburgerSpace &space)
Return a universe set of the specified type that contains all points.
static PresburgerRelation getEmpty (const PresburgerSpace &space)
Return an empty set of the specified type that contains no points.
Protected Member Functions
PresburgerSet (const PresburgerSpace &space)
Construct an empty PresburgerRelation with the specified number of dimension and symbols.
Protected Member Functions inherited from mlir::presburger::PresburgerRelation
PresburgerRelation (const PresburgerSpace &space)
Construct an empty PresburgerRelation with the specified number of dimension and symbols.
Additional Inherited Members
Protected Attributes inherited from mlir::presburger::PresburgerRelation
PresburgerSpace space
SmallVector< IntegerRelation, 2 > disjuncts
The list of disjuncts that this set is the union of.
Detailed Description
Definition at line 244 of file PresburgerRelation.h.
Constructor & Destructor Documentation
PresburgerSet() [1/3]
PresburgerSet::PresburgerSet (const IntegerPolyhedron & disjunct) explicit
Create a set from a relation.
Definition at line 1071 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::PresburgerRelation().
Referenced by coalesce(), complement(), getEmpty(), getUniverse(), intersect(), subtract(), and unionSet().
PresburgerSet() [2/3]
PresburgerSet::PresburgerSet (const PresburgerRelation & set) explicit
Definition at line 1074 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::PresburgerRelation().
PresburgerSet() [3/3]
mlir::presburger::PresburgerSet::PresburgerSet (const PresburgerSpace & space) inline explicit protected
Construct an empty PresburgerRelation with the specified number of dimension and symbols.
Definition at line 268 of file PresburgerRelation.h.
References mlir::presburger::PresburgerRelation::PresburgerRelation(), and mlir::presburger::PresburgerRelation::space.
Member Function Documentation
coalesce()
PresburgerSet PresburgerSet::coalesce () const
Definition at line 1093 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::coalesce(), and PresburgerSet().
complement()
PresburgerSet PresburgerSet::complement () const
Definition at line 1085 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::complement(), and PresburgerSet().
getEmpty()
PresburgerSet PresburgerSet::getEmpty (const PresburgerSpace & space) static
Return an empty set of the specified type that contains no points.
Definition at line 1067 of file PresburgerRelation.cpp.
References PresburgerSet(), and mlir::presburger::PresburgerRelation::space.
Referenced by mlir::presburger::PWMAFunction::getDomain(), mlir::presburger::PresburgerRelation::getDomainSet(), mlir::presburger::MultiAffineFunction::getLexSet(), and mlir::presburger::PresburgerRelation::getRangeSet().
getUniverse()
PresburgerSet PresburgerSet::getUniverse (const PresburgerSpace & space) static
Return a universe set of the specified type that contains all points.
Definition at line 1061 of file PresburgerRelation.cpp.
References mlir::presburger::IntegerPolyhedron::getUniverse(), PresburgerSet(), result, and mlir::presburger::PresburgerRelation::space.
Referenced by mlir::presburger::detail::computeChamberDecomposition().
intersect()
PresburgerSet PresburgerSet::intersect (const PresburgerRelation & set) const
Definition at line 1081 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::intersect(), mlir::presburger::PresburgerRelation::PresburgerRelation(), and PresburgerSet().
Referenced by mlir::presburger::PWMAFunction::addPiece(), mlir::presburger::detail::computeChamberDecomposition(), and findSymbolicIntegerLexOpt().
subtract()
PresburgerSet PresburgerSet::subtract (const PresburgerRelation & set) const
Definition at line 1089 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::PresburgerRelation(), PresburgerSet(), and mlir::presburger::PresburgerRelation::subtract().
Referenced by mlir::affine::ComputationSliceState::isMaximal(), and mlir::affine::ComputationSliceState::isSliceValid().
unionSet()
PresburgerSet PresburgerSet::unionSet (const PresburgerRelation & set) const
These operations are the same as the ones in PresburgeRelation, they just forward the arguement and return the result as a set instead of a relation.
Definition at line 1077 of file PresburgerRelation.cpp.
References mlir::presburger::PresburgerRelation::PresburgerRelation(), PresburgerSet(), and mlir::presburger::PresburgerRelation::unionSet().
Referenced by mlir::presburger::IntegerRelation::computeReprWithOnlyDivLocals().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PresburgerRelation.h
lib/Analysis/Presburger/PresburgerRelation.cpp