MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
virtual ~PyValue ()=default
PyValue (PyOperationRef parentOperation, MlirValue value)
operator MlirValue () const
MlirValue get ()
PyOperationRef & getParentOperation ()
void checkValid ()
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirValue.
nanobind::typed< nanobind::object, std::variant< PyBlockArgument, PyOpResult, PyValue > > maybeDownCast ()
Static Public Member Functions
static PyValue createFromCapsule (nanobind::object capsule)
Creates a PyValue from the MlirValue wrapped by a capsule.
Detailed Description
Definition at line 1304 of file IRCore.h.
Constructor & Destructor Documentation
~PyValue()
virtual mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::~PyValue () virtual default
PyValue()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::PyValue (PyOperationRef parentOperation, MlirValue value) inline
Definition at line 1310 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< DerivedTy >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< DerivedTy >::castFrom(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< DerivedTy >::PyConcreteValue(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< DerivedTy >::PyConcreteValue().
Member Function Documentation
checkValid()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::checkValid () inline
Definition at line 1317 of file IRCore.h.
createFromCapsule()
PyValue mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::createFromCapsule (nanobind::object capsule) static
Creates a PyValue from the MlirValue wrapped by a capsule.
Ownership of the underlying MlirValue is still tied to the owning operation.
Definition at line 2011 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirValue mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::get () inline
Definition at line 1314 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< DerivedTy >::castFrom(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getValueOwnerRef(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::getCapsule ()
Gets a capsule wrapping the void* within the MlirValue.
Definition at line 1971 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getParentOperation()
PyOperationRef & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::getParentOperation () inline
Definition at line 1315 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< DerivedTy >::PyConcreteValue().
maybeDownCast()
nb::typed< nb::object, std::variant< PyBlockArgument, PyOpResult, PyValue > > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::maybeDownCast ()
Definition at line 1990 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirValue()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::operator MlirValue () const inline
Definition at line 1312 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp