MLIR: ConvInferShapeAdaptor< Conv2DOp::Adaptor > Class Reference
ConvInferShapeAdaptor< Conv2DOp::Adaptor > Class Reference
Public Member Functions
ConvInferShapeAdaptor (Conv2DOp::Adaptor adaptor)
void inferInputShape (SmallVectorImpl< int64_t > &outputShape, SmallVectorImpl< int64_t > &inputSpatial)
void inferWeightShape (SmallVectorImpl< int64_t > &outputShape, SmallVectorImpl< int64_t > &weightSpatial)
int64_t getNumSpatialDims () const
int64_t getOutputRank () const
LogicalResult getSpatialParameters (SmallVector< int64_t > &padValues, SmallVector< int64_t > &strideValues, SmallVector< int64_t > &dilationValues)
Additional Inherited Members
Static Protected Member Functions inherited from ConvInferShapeAdaptorBase
static void updateIfDynamic (int64_t &current, int64_t candidate)
Detailed Description
Definition at line 4307 of file TosaOps.cpp.
Constructor & Destructor Documentation
ConvInferShapeAdaptor()
ConvInferShapeAdaptor< Conv2DOp::Adaptor >::ConvInferShapeAdaptor (Conv2DOp::Adaptor adaptor) inline explicit
Definition at line 4310 of file TosaOps.cpp.
Member Function Documentation
getNumSpatialDims()
int64_t ConvInferShapeAdaptor< Conv2DOp::Adaptor >::getNumSpatialDims () const inline
Definition at line 4343 of file TosaOps.cpp.
getOutputRank()
int64_t ConvInferShapeAdaptor< Conv2DOp::Adaptor >::getOutputRank () const inline
Definition at line 4344 of file TosaOps.cpp.
getSpatialParameters()
LogicalResult ConvInferShapeAdaptor< Conv2DOp::Adaptor >::getSpatialParameters (SmallVector< int64_t > & padValues, SmallVector< int64_t > & strideValues, SmallVector< int64_t > & dilationValues) inline
Definition at line 4346 of file TosaOps.cpp.
References success().
inferInputShape()
void ConvInferShapeAdaptor< Conv2DOp::Adaptor >::inferInputShape (SmallVectorImpl< int64_t > & outputShape, SmallVectorImpl< int64_t > & inputSpatial) inline
Definition at line 4313 of file TosaOps.cpp.
References mlir::ShapeAdaptor::getDimSize(), and mlir::ShapeAdaptor::hasRank().
inferWeightShape()
void ConvInferShapeAdaptor< Conv2DOp::Adaptor >::inferWeightShape (SmallVectorImpl< int64_t > & outputShape, SmallVectorImpl< int64_t > & weightSpatial) inline
Definition at line 4328 of file TosaOps.cpp.
References mlir::ShapeAdaptor::getDimSize(), and mlir::ShapeAdaptor::hasRank().
The documentation for this class was generated from the following file:
lib/Dialect/Tosa/IR/TosaOps.cpp