MLIR: mlir::AsmParser::CyclicParseReset Class Reference
mlir::AsmParser::CyclicParseReset Class Reference
Class used to automatically end a cyclic region on destruction.
#include "mlir/IR/OpImplementation.h"
Public Member Functions
CyclicParseReset (AsmParser *parser)
~CyclicParseReset ()
CyclicParseReset (const CyclicParseReset &)=delete
CyclicParseReset & operator= (const CyclicParseReset &)=delete
CyclicParseReset (CyclicParseReset &&rhs)
CyclicParseReset & operator= (CyclicParseReset &&rhs)
Detailed Description
Class used to automatically end a cyclic region on destruction.
Definition at line 1419 of file OpImplementation.h.
Constructor & Destructor Documentation
CyclicParseReset() [1/3]
mlir::AsmParser::CyclicParseReset::CyclicParseReset (AsmParser * parser) inline explicit
Definition at line 1421 of file OpImplementation.h.
References mlir::AsmParser::AsmParser().
Referenced by CyclicParseReset(), CyclicParseReset(), operator=(), and operator=().
~CyclicParseReset()
mlir::AsmParser::CyclicParseReset::~CyclicParseReset () inline
Definition at line 1423 of file OpImplementation.h.
CyclicParseReset() [2/3]
mlir::AsmParser::CyclicParseReset::CyclicParseReset (const CyclicParseReset &) delete
References CyclicParseReset().
CyclicParseReset() [3/3]
mlir::AsmParser::CyclicParseReset::CyclicParseReset (CyclicParseReset && rhs) inline
Definition at line 1430 of file OpImplementation.h.
References CyclicParseReset(), nullptr, and rhs.
Member Function Documentation
operator=() [1/2]
CyclicParseReset & mlir::AsmParser::CyclicParseReset::operator= (const CyclicParseReset &) delete
References CyclicParseReset().
operator=() [2/2]
CyclicParseReset & mlir::AsmParser::CyclicParseReset::operator= (CyclicParseReset && rhs) inline
Definition at line 1432 of file OpImplementation.h.
References CyclicParseReset(), and rhs.
The documentation for this class was generated from the following file:
include/mlir/IR/OpImplementation.h