MLIR: mlir::ValueBoundsConstraintSet::Variable Class Reference
mlir::ValueBoundsConstraintSet::Variable Class Reference
A variable that can be added to the constraint set as a "column".
#include "mlir/Interfaces/ValueBoundsOpInterface.h"
Public Member Functions
Variable (OpFoldResult ofr)
Construct a variable for an index-typed attribute or SSA value.
Variable (Value indexValue)
Construct a variable for an index-typed SSA value.
Variable (Value shapedValue, int64_t dim)
Construct a variable for a dimension of a shaped value.
Variable (OpFoldResult ofr, std::optional< int64_t > dim)
Construct a variable for an index-typed attribute/SSA value or for a dimension of a shaped value.
Variable (AffineMap map, ArrayRef< Variable > mapOperands)
Construct a variable for a map and its operands.
Variable (AffineMap map, ValueRange mapOperands)
MLIRContext * getContext () const
AffineMap getMap () const
Returns the affine map.
ValueDimList & getOperands ()
Returns the map operands.
const ValueDimList & getOperands () const
Friends
class ValueBoundsConstraintSet
Detailed Description
A variable that can be added to the constraint set as a "column".
The value bounds infrastructure can compute bounds for variables and compare two variables.
Internally, a variable is represented as an affine map and operands.
Definition at line 120 of file ValueBoundsOpInterface.h.
Constructor & Destructor Documentation
Variable() [1/6]
ValueBoundsConstraintSet::Variable::Variable (OpFoldResult ofr)
Construct a variable for an index-typed attribute or SSA value.
Definition at line 76 of file ValueBoundsOpInterface.cpp.
Referenced by Variable().
Variable() [2/6]
ValueBoundsConstraintSet::Variable::Variable (Value indexValue)
Construct a variable for an index-typed SSA value.
Definition at line 79 of file ValueBoundsOpInterface.cpp.
Variable() [3/6]
ValueBoundsConstraintSet::Variable::Variable (Value shapedValue, int64_t dim)
Construct a variable for a dimension of a shaped value.
Definition at line 82 of file ValueBoundsOpInterface.cpp.
Variable() [4/6]
ValueBoundsConstraintSet::Variable::Variable (OpFoldResult ofr, std::optional< int64_t > dim)
Construct a variable for an index-typed attribute/SSA value or for a dimension of a shaped value.
A non-null dimension must be provided if and only if ofr is a shaped value.
Definition at line 85 of file ValueBoundsOpInterface.cpp.
References mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineSymbolExpr(), mlir::getConstantIntValue(), mlir::OpFoldResult::getContext(), mlir::Value::getType(), and mlir::Type::isIndex().
Variable() [5/6]
ValueBoundsConstraintSet::Variable::Variable (AffineMap map, ArrayRef< Variable > mapOperands)
Construct a variable for a map and its operands.
Definition at line 107 of file ValueBoundsOpInterface.cpp.
References mlir::detail::enumerate(), mlir::Builder::getAffineSymbolExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::replace(), and mlir::AffineMap::replaceDimsAndSymbols().
Variable() [6/6]
ValueBoundsConstraintSet::Variable::Variable (AffineMap map, ValueRange mapOperands)
Definition at line 148 of file ValueBoundsOpInterface.cpp.
References Variable().
Member Function Documentation
getContext()
MLIRContext* mlir::ValueBoundsConstraintSet::Variable::getContext () const inline
Definition at line 140 of file ValueBoundsOpInterface.h.
References mlir::AffineMap::getContext().
Referenced by mlir::ValueBoundsConstraintSet::compare(), mlir::ValueBoundsConstraintSet::computeBound(), mlir::ValueBoundsConstraintSet::computeConstantBound(), and mlir::ValueBoundsConstraintSet::strongCompare().
getMap()
AffineMap mlir::ValueBoundsConstraintSet::Variable::getMap () const inline
Returns the affine map.
Definition at line 143 of file ValueBoundsOpInterface.h.
getOperands() [1/2]
ValueDimList& mlir::ValueBoundsConstraintSet::Variable::getOperands () inline
Returns the map operands.
Definition at line 146 of file ValueBoundsOpInterface.h.
getOperands() [2/2]
const ValueDimList& mlir::ValueBoundsConstraintSet::Variable::getOperands () const inline
Definition at line 147 of file ValueBoundsOpInterface.h.
Friends And Related Function Documentation
ValueBoundsConstraintSet
friend class ValueBoundsConstraintSet friend
Definition at line 150 of file ValueBoundsOpInterface.h.
The documentation for this class was generated from the following files:
include/mlir/Interfaces/ValueBoundsOpInterface.h
lib/Interfaces/ValueBoundsOpInterface.cpp