MLIR: mlir::tblgen::ClassDeclarationBase< DeclKind > Class Template Reference
mlir::tblgen::ClassDeclarationBase< DeclKind > Class Template Reference
Base class for class declarations.
#include "mlir/TableGen/Class.h"
Public Types
using Base = ClassDeclarationBase<DeclKind>
Public Types inherited from mlir::tblgen::ClassDeclaration
enum Kind {
Method , UsingDeclaration , VisibilityDeclaration , Field ,
ExtraClassDeclaration
}
Kinds for LLVM-style RTTI.
Public Member Functions
ClassDeclarationBase ()
Public Member Functions inherited from mlir::tblgen::ClassDeclaration
virtual ~ClassDeclaration ()=default
ClassDeclaration (Kind kind)
Create a class declaration with a given kind.
Kind getKind () const
Get the class declaration kind.
virtual void writeDeclTo (raw_indented_ostream &os) const =0
Write the declaration.
virtual void writeDefTo (raw_indented_ostream &os, StringRef namePrefix) const
Write the definition, if any.
Static Public Member Functions
static bool classof (const ClassDeclaration *other)
Detailed Description
template<ClassDeclaration::Kind DeclKind>
class mlir::tblgen::ClassDeclarationBase< DeclKind >
Base class for class declarations.
Definition at line 299 of file Class.h.
Member Typedef Documentation
Base
template<ClassDeclaration::Kind DeclKind> using mlir::tblgen::ClassDeclarationBase< DeclKind >::Base = ClassDeclarationBase<DeclKind>
Definition at line 301 of file Class.h.
Constructor & Destructor Documentation
ClassDeclarationBase()
template<ClassDeclaration::Kind DeclKind> mlir::tblgen::ClassDeclarationBase< DeclKind >::ClassDeclarationBase () inline
Definition at line 302 of file Class.h.
References mlir::tblgen::ClassDeclaration::ClassDeclaration().
Member Function Documentation
classof()
template<ClassDeclaration::Kind DeclKind> bool mlir::tblgen::ClassDeclarationBase< DeclKind >::classof (const ClassDeclaration * other) inline static
Definition at line 304 of file Class.h.
References mlir::tblgen::ClassDeclaration::ClassDeclaration(), and mlir::tblgen::ClassDeclaration::getKind().
The documentation for this class was generated from the following file:
include/mlir/TableGen/Class.h