MLIR: mlir::python::PyThreadContextEntry Class Reference
mlir::python::PyThreadContextEntry Class Reference
Tracks an entry in the thread context stack.
#include "Bindings/Python/IRModule.h"
Public Types
enum class FrameKind { Context , InsertionPoint , Location }
Public Member Functions
PyThreadContextEntry (FrameKind frameKind, nanobind::object context, nanobind::object insertionPoint, nanobind::object location)
PyMlirContext * getContext ()
PyInsertionPoint * getInsertionPoint ()
PyLocation * getLocation ()
FrameKind getFrameKind ()
Static Public Member Functions
static PyMlirContext * getDefaultContext ()
Gets the top of stack context and return nullptr if not defined.
static PyInsertionPoint * getDefaultInsertionPoint ()
Gets the top of stack insertion point and return nullptr if not defined.
static PyLocation * getDefaultLocation ()
Gets the top of stack location and returns nullptr if not defined.
static PyThreadContextEntry * getTopOfStack ()
Stack management.
static nanobind::object pushContext (nanobind::object context)
static void popContext (PyMlirContext &context)
static nanobind::object pushInsertionPoint (nanobind::object insertionPoint)
static void popInsertionPoint (PyInsertionPoint &insertionPoint)
static nanobind::object pushLocation (nanobind::object location)
static void popLocation (PyLocation &location)
static std::vector< PyThreadContextEntry > & getStack ()
Gets the thread local stack.
Detailed Description
Tracks an entry in the thread context stack.
New entries are pushed onto here for each with block that activates a new InsertionPoint, Context or Location.
Pushing either a Location or InsertionPoint also pushes its associated Context. Pushing a Context will not modify the Location or InsertionPoint unless if they are from a different context, in which case, they are cleared.
Definition at line 112 of file IRModule.h.
Member Enumeration Documentation
FrameKind
enum class mlir::python::PyThreadContextEntry::FrameKind strong
Enumerator
Context
InsertionPoint
Location
Definition at line 114 of file IRModule.h.
Constructor & Destructor Documentation
PyThreadContextEntry()
mlir::python::PyThreadContextEntry::PyThreadContextEntry (FrameKind frameKind, nanobind::object context, nanobind::object insertionPoint, nanobind::object location) inline
Definition at line 120 of file IRModule.h.
Referenced by getTopOfStack().
Member Function Documentation
getContext()
PyMlirContext * PyThreadContextEntry::getContext ()
Definition at line 721 of file IRCore.cpp.
getDefaultContext()
PyMlirContext * PyThreadContextEntry::getDefaultContext () static
Gets the top of stack context and return nullptr if not defined.
Definition at line 739 of file IRCore.cpp.
References getTopOfStack().
Referenced by mlir::python::DefaultingPyMlirContext::resolve().
getDefaultInsertionPoint()
PyInsertionPoint * PyThreadContextEntry::getDefaultInsertionPoint () static
Gets the top of stack insertion point and return nullptr if not defined.
Definition at line 744 of file IRCore.cpp.
References getTopOfStack().
Referenced by maybeInsertOperation().
getDefaultLocation()
PyLocation * PyThreadContextEntry::getDefaultLocation () static
Gets the top of stack location and returns nullptr if not defined.
Definition at line 749 of file IRCore.cpp.
References getTopOfStack().
Referenced by mlir::python::DefaultingPyLocation::resolve().
getFrameKind()
FrameKind mlir::python::PyThreadContextEntry::getFrameKind () inline
Definition at line 138 of file IRModule.h.
getInsertionPoint()
PyInsertionPoint * PyThreadContextEntry::getInsertionPoint ()
Definition at line 727 of file IRCore.cpp.
getLocation()
PyLocation * PyThreadContextEntry::getLocation ()
Definition at line 733 of file IRCore.cpp.
getStack()
std::vector< PyThreadContextEntry > & PyThreadContextEntry::getStack () static
Gets the thread local stack.
Definition at line 687 of file IRCore.cpp.
Referenced by getTopOfStack(), popContext(), popInsertionPoint(), and popLocation().
getTopOfStack()
PyThreadContextEntry * PyThreadContextEntry::getTopOfStack () static
Stack management.
Definition at line 692 of file IRCore.cpp.
References getStack(), and PyThreadContextEntry().
Referenced by getDefaultContext(), getDefaultInsertionPoint(), and getDefaultLocation().
popContext()
void PyThreadContextEntry::popContext (PyMlirContext & context) static
Definition at line 761 of file IRCore.cpp.
References Context, and getStack().
Referenced by mlir::python::PyMlirContext::contextExit().
popInsertionPoint()
void PyThreadContextEntry::popInsertionPoint (PyInsertionPoint & insertionPoint) static
Definition at line 784 of file IRCore.cpp.
References getStack(), and InsertionPoint.
Referenced by mlir::python::PyInsertionPoint::contextExit().
popLocation()
void PyThreadContextEntry::popLocation (PyLocation & location) static
Definition at line 804 of file IRCore.cpp.
References getStack(), and Location.
Referenced by mlir::python::PyLocation::contextExit().
pushContext()
nb::object PyThreadContextEntry::pushContext (nanobind::object context) static
Definition at line 754 of file IRCore.cpp.
References Context.
Referenced by mlir::python::PyMlirContext::contextEnter().
pushInsertionPoint()
nb::object PyThreadContextEntry::pushInsertionPoint (nanobind::object insertionPoint) static
Definition at line 772 of file IRCore.cpp.
References InsertionPoint.
Referenced by mlir::python::PyInsertionPoint::contextEnter().
pushLocation()
nb::object PyThreadContextEntry::pushLocation (nanobind::object location) static
Definition at line 795 of file IRCore.cpp.
References Location.
Referenced by mlir::python::PyLocation::contextEnter().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp