MLIR: PyOpResultList Class Reference
PyOpResultList Class Reference
A list of operation results.
Public Types
using SliceableT = Sliceable<PyOpResultList, PyOpResult>
Public Member Functions
PyOpResultList (PyOperationRef operation, intptr_t startIndex=0, intptr_t length=-1, intptr_t step=1)
PyOperationRef & getOperation ()
Public Member Functions inherited from mlir::Sliceable< PyOpResultList, PyOpResult >
Sliceable (intptr_t startIndex, intptr_t length, intptr_t step)
PyOpResult getElement (intptr_t index)
Returns the index-th element in the slice, supports negative indices.
intptr_t size ()
Returns the size of slice.
std::vector< PyOpResult > dunderAdd (PyOpResultList &other)
Returns a new vector (mapped to Python list) containing elements from two slices.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::Sliceable< PyOpResultList, PyOpResult >
static void bind (nanobind::module_ &m)
Binds the indexing and length methods in the Python class.
static void bindDerived (ClassTy &)
Hook for derived classes willing to bind more methods.
Static Public Attributes
static constexpr const char * pyClassName = "OpResultList"
Friends
class Sliceable< PyOpResultList, PyOpResult >
Give the parent CRTP class access to hook implementations below.
Additional Inherited Members
Public Attributes inherited from mlir::Sliceable< PyOpResultList, PyOpResult >
intptr_t startIndex
intptr_t length
intptr_t step
Protected Types inherited from mlir::Sliceable< PyOpResultList, PyOpResult >
using ClassTy
using has_maybe_downcast
Trait to check if T provides a maybeDownCast method.
Protected Member Functions inherited from mlir::Sliceable< PyOpResultList, PyOpResult >
intptr_t wrapIndex (intptr_t index)
Transforms index into a legal value to access the underlying sequence.
intptr_t linearizeIndex (intptr_t index)
Computes the linear index given the current slice properties.
nanobind::object getItem (intptr_t index)
Returns the element at the given slice index.
nanobind::object getItemSlice (PyObject *slice)
Returns a new instance of the pseudo-container restricted to the given slice.
Detailed Description
A list of operation results.
Internally, these are stored as consecutive elements, random access is cheap. The (returned) result list is associated with the operation whose results these are, and thus extends the lifetime of this operation.
Definition at line 1557 of file IRCore.cpp.
Member Typedef Documentation
SliceableT
using PyOpResultList::SliceableT = Sliceable<PyOpResultList, PyOpResult>
Definition at line 1560 of file IRCore.cpp.
Constructor & Destructor Documentation
PyOpResultList()
PyOpResultList::PyOpResultList (PyOperationRef operation, intptr_t startIndex = 0, intptr_t length = -1, intptr_t step = 1) inline
Definition at line 1562 of file IRCore.cpp.
References mlir::get(), mlir::Sliceable< PyOpResultList, PyOpResult >::length, mlirOperationGetNumResults(), mlir::Sliceable< PyOpResultList, PyOpResult >::Sliceable(), mlir::Sliceable< PyOpResultList, PyOpResult >::startIndex, and mlir::Sliceable< PyOpResultList, PyOpResult >::step.
Referenced by bindDerived().
Member Function Documentation
bindDerived()
void PyOpResultList::bindDerived (ClassTy & c) inline static
Definition at line 1570 of file IRCore.cpp.
References mlir::python::PyOperation::createOpView(), mlir::python::BaseContextObject::getContext(), getValueTypes(), and PyOpResultList().
getOperation()
PyOperationRef & PyOpResultList::getOperation () inline
Definition at line 1585 of file IRCore.cpp.
Referenced by getOpResultOrValue().
Friends And Related Symbol Documentation
Sliceable< PyOpResultList, PyOpResult >
friend class Sliceable< PyOpResultList, PyOpResult > friend
Give the parent CRTP class access to hook implementations below.
Definition at line 1585 of file IRCore.cpp.
Member Data Documentation
pyClassName
const char* PyOpResultList::pyClassName = "OpResultList" static constexpr
Definition at line 1559 of file IRCore.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRCore.cpp