MLIR: ConvertTypesInSCFWhileOp Class Reference
ConvertTypesInSCFWhileOp Class Reference
Public Member Functions
LogicalResult matchAndRewrite (WhileOp op, OpAdaptor adaptor, OneToNPatternRewriter &rewriter) const override
Overload that derived classes have to override for their op type.
Public Member Functions inherited from mlir::OneToNOpConversionPattern< WhileOp >
OneToNOpConversionPattern (const TypeConverter &typeConverter, MLIRContext *context, PatternBenefit benefit=1, ArrayRef< StringRef > generatedNames={})
LogicalResult matchAndRewrite (Operation *op, OneToNPatternRewriter &rewriter, const OneToNTypeMapping &operandMapping, const OneToNTypeMapping &resultMapping, ValueRange convertedOperands) const final
This function has to be implemented by derived classes and is called from the usual overloads.
virtual LogicalResult matchAndRewrite (Operation *op, OneToNPatternRewriter &rewriter, const OneToNTypeMapping &operandMapping, const OneToNTypeMapping &resultMapping, ValueRange convertedOperands) const =0
This function has to be implemented by derived classes and is called from the usual overloads.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Public Member Functions inherited from mlir::OneToNConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
template<typename... Args>
RewritePatternWithConverter (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
Public Member Functions inherited from mlir::RewritePatternWithConverter
template<typename... Args>
RewritePatternWithConverter (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
const TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, const ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Public Types inherited from mlir::RewritePattern
using OperationT = Operation *
using SplitMatchAndRewrite = detail::SplitMatchAndRewriteImpl< RewritePattern >
SplitMatchAndRewrite is deprecated.
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::RewritePatternWithConverter
const TypeConverter *const typeConverter
A type converter for use by this pattern.
Detailed Description
Definition at line 58 of file OneToNTypeConversion.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult ConvertTypesInSCFWhileOp::matchAndRewrite (WhileOp op, OpAdaptor adaptor, OneToNPatternRewriter & rewriter) const inline override virtual
Overload that derived classes have to override for their op type.
Implements mlir::OneToNOpConversionPattern< WhileOp >.
Definition at line 63 of file OneToNTypeConversion.cpp.
References mlir::OneToNPatternRewriter::applySignatureConversion(), mlir::OpBuilder::create(), mlir::Region::end(), mlir::Region::front(), mlir::OneToNTypeMapping::getConvertedTypes(), mlir::OneToNTypeMapping::hasNonIdentityConversion(), mlir::RewriterBase::inlineRegionBefore(), mlir::OneToNPatternRewriter::replaceOp(), and mlir::Operation::setAttrs().
The documentation for this class was generated from the following file:
lib/Dialect/SCF/Transforms/OneToNTypeConversion.cpp