MLIR: mlir::ShapedType Class Reference
mlir::ShapedType Class Reference
This is a common base class between Vector, UnrankedTensor, RankedTensor, and MemRef types because they share behavior and semantics around shape, rank, and fixed element type.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
ShapedType clone (ArrayRef< int64_t > shape, Type elementType)
Return clone of this type with new shape and element type.
ShapedType clone (ArrayRef< int64_t > shape)
ShapedType clone (Type elementType)
Type getElementType () const
Return the element type.
unsigned getElementTypeBitWidth () const
If an element type is an integer or a float, return its width.
int64_t getNumElements () const
If it has static shape, return the number of elements. Otherwise, abort.
int64_t getRank () const
If this is a ranked type, return the rank. Otherwise, abort.
bool hasRank () const
Whether or not this is a ranked type.
ArrayRef< int64_t > getShape () const
If this is a ranked type, return the shape. Otherwise, abort.
bool hasStaticShape () const
If this is unranked type or any dimension has unknown size (<0), it doesn't have static shape.
bool hasStaticShape (ArrayRef< int64_t > shape) const
If this has a static shape and the shape is equal to shape return true.
int64_t getNumDynamicDims () const
If this is a ranked type, return the number of dimensions with dynamic size.
int64_t getDimSize (unsigned idx) const
If this is ranked type, return the size of the specified dimension.
bool isDynamicDim (unsigned idx) const
Returns true if this dimension has a dynamic size (for ranked types); aborts for unranked types.
unsigned getDynamicDimIndex (unsigned index) const
Returns the position of the dynamic dimension relative to just the dynamic dimensions, given its index within the shape.
int64_t getSizeInBits () const
Get the total amount of bits occupied by a value of this type.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractTy & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
static constexpr bool isDynamic (int64_t dSize)
Whether the given dimension size indicates a dynamic dimension.
static constexpr bool isDynamicStrideOrOffset (int64_t dStrideOrOffset)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Static Public Attributes
static constexpr int64_t kDynamicSize = -1
static constexpr int64_t kDynamicStrideOrOffset
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
This is a common base class between Vector, UnrankedTensor, RankedTensor, and MemRef types because they share behavior and semantics around shape, rank, and fixed element type.
Any type with these semantics should inherit from ShapedType.
Definition at line 65 of file BuiltinTypes.h.
Member Function Documentation
classof()
bool mlir::ShapedType::classof (Type type) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 308 of file BuiltinTypes.h.
References mlir::Type::isa().
clone() [1/3]
ShapedType ShapedType::clone (ArrayRef< int64_t > shape, Type elementType)
Return clone of this type with new shape and element type.
Definition at line 279 of file BuiltinTypes.cpp.
References mlir::MemRefType::Builder::setElementType(), mlir::MemRefType::Builder::setMemorySpace(), and mlir::MemRefType::Builder::setShape().
clone() [2/3]
ShapedType ShapedType::clone (ArrayRef< int64_t > shape)
Definition at line 302 of file BuiltinTypes.cpp.
References getElementType(), mlir::MemRefType::Builder::setMemorySpace(), and mlir::MemRefType::Builder::setShape().
clone() [3/3]
ShapedType ShapedType::clone (Type elementType)
Definition at line 325 of file BuiltinTypes.cpp.
References elementType(), getShape(), and mlir::MemRefType::Builder::setElementType().
getDimSize()
int64_t ShapedType::getDimSize (unsigned idx) const
If this is ranked type, return the size of the specified dimension.
Otherwise, abort.
Definition at line 378 of file BuiltinTypes.cpp.
References getShape().
Referenced by mlir::quant::UniformQuantizedPerAxisValueConverter::convert(), getAtomicOpScope(), getI64Values(), joinShapes(), and mlir::detail::Parser::parseSparseElementsAttr().
getDynamicDimIndex()
unsigned ShapedType::getDynamicDimIndex (unsigned index) const
Returns the position of the dynamic dimension relative to just the dynamic dimensions, given its index within the shape.
Definition at line 388 of file BuiltinTypes.cpp.
References getShape(), and isDynamic().
getElementType()
Type ShapedType::getElementType () const
Return the element type.
Definition at line 348 of file BuiltinTypes.cpp.
Referenced by applyPad(), mlir::ConstantIndexOp::build(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::detail::DenseIntOrFPElementsAttrStorage::construct(), convertTensorType(), convolutionMatchAndRewriterHelper(), defaultAllocBufferCallBack(), defaultIsSmallAlloc(), elementwiseMatchAndRewriteHelper(), mlir::tensor::foldTensorCast(), foldTransferInBoundsAttribute(), fuseWithReshapeByExpansion(), mlir::DenseElementsAttr::get(), getEnclosingforOps(), mlir::detail::DenseIntOrFPElementsAttrStorage::getKey(), mlir::LLVMTypeConverter::getUnrankedMemRefDescriptorSize(), isRankReducedType(), mlir::DenseElementsAttr::isValidRawBuffer(), joinShapes(), mlir::linalg::PadTensorOpTransformationPattern::matchAndRewrite(), mlir::DenseElementsAttr::BoolElementIterator::operator*(), mlir::DenseElementsAttr::IntElementIterator::operator*(), mlir::detail::DenseIntOrFPElementsAttrStorage::operator==(), parseElementAttrHexValues(), mlir::detail::Parser::parseSparseElementsAttr(), printDenseElementsAttrImpl(), mlir::DenseElementsAttr::reshape(), mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >(), sourceMaterializationCallback(), verify(), verifyTransferOp(), and writeAPIntsToBuffer().
getElementTypeBitWidth()
unsigned ShapedType::getElementTypeBitWidth () const
If an element type is an integer or a float, return its width.
Otherwise, abort.
Definition at line 354 of file BuiltinTypes.cpp.
References getElementType(), and mlir::Type::getIntOrFloatBitWidth().
Referenced by getAtomicOpScope().
getNumDynamicDims()
int64_t ShapedType::getNumDynamicDims () const
If this is a ranked type, return the number of dimensions with dynamic size.
Otherwise, abort.
Definition at line 426 of file BuiltinTypes.cpp.
References getShape().
getNumElements()
int64_t ShapedType::getNumElements () const
If it has static shape, return the number of elements. Otherwise, abort.
Definition at line 358 of file BuiltinTypes.cpp.
References getShape().
Referenced by getAtomicOpScope(), getI64Values(), mlir::detail::DenseIntOrFPElementsAttrStorage::getKey(), mlir::detail::DenseStringElementsAttrStorage::getKey(), hasSameElementsOrSplat(), mlir::DenseElementsAttr::isValidRawBuffer(), mappingHelper(), parseElementAttrHexValues(), printDenseElementsAttrImpl(), mlir::DenseElementsAttr::reshape(), verify(), and writeAPIntsToBuffer().
getRank()
int64_t ShapedType::getRank () const
If this is a ranked type, return the rank. Otherwise, abort.
Definition at line 369 of file BuiltinTypes.cpp.
References getShape().
Referenced by mlir::DenseIntElementsAttr::classof(), convolutionMatchAndRewriterHelper(), elementwiseMatchAndRewriteHelper(), foldTransferInBoundsAttribute(), getAtomicOpScope(), getEnclosingforOps(), getI64Values(), mlir::getReassociationIndicesForReshape(), joinShapes(), mlir::CollapseMixedReshapeOps< ReshapeOpTy, InverseReshapeOpTy >::matchAndRewrite(), mlir::linalg::PadTensorOpTransformationPattern::matchAndRewrite(), mlir::detail::Parser::parseSparseElementsAttr(), printDenseElementsAttrImpl(), sourceMaterializationCallback(), verify(), and verifyTransferOp().
getShape()
ArrayRef< int64_t > ShapedType::getShape () const
If this is a ranked type, return the shape. Otherwise, abort.
Definition at line 418 of file BuiltinTypes.cpp.
References getShape(), and vectorType().
Referenced by applyPad(), mlir::ConstantIndexOp::build(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::quant::UniformQuantizedPerAxisValueConverter::convert(), convolutionMatchAndRewriterHelper(), elementwiseMatchAndRewriteHelper(), foldIdentityOffsetSizeAndStrideOpInterface(), getI64Values(), GetNumElements(), mlir::getReassociationIndicesForReshape(), isRankReducedType(), mappingHelper(), mlir::linalg::PadTensorOpTransformationPattern::matchAndRewrite(), parseElementAttrHexValues(), mlir::detail::Parser::parseSparseElementsAttr(), printDenseElementsAttrImpl(), resolveBroadcastShape(), mlir::verifyCompatibleShape(), and mlir::verifyReshapeLikeShapes().
getSizeInBits()
int64_t ShapedType::getSizeInBits () const
Get the total amount of bits occupied by a value of this type.
Get the number of bits require to store a value of the given shaped type.
This does not take into account any memory layout or widening constraints, e.g. a vector<3xi57> is reported to occupy 3x57=171 bit, even though in practice it will likely be stored as in a 4xi64 vector register. Fail an assertion if the size cannot be computed statically, i.e. if the type has a dynamic shape or if its elemental type does not have a known bit width.
Compute the value recursively since tensors are allowed to have vectors as elements.
Definition at line 397 of file BuiltinTypes.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), getElementType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isa(), and mlir::Type::isIntOrFloat().
hasRank()
bool ShapedType::hasRank () const
Whether or not this is a ranked type.
Memrefs, vectors and ranked tensors have a rank, while unranked tensors do not.
Definition at line 374 of file BuiltinTypes.cpp.
Referenced by getI64Values(), joinShapes(), sourceMaterializationCallback(), and mlir::verifyCompatibleShape().
hasStaticShape() [1/2]
bool ShapedType::hasStaticShape () const
If this is unranked type or any dimension has unknown size (<0), it doesn't have static shape.
If all dimensions have known size (>= 0), it has static shape.
Definition at line 430 of file BuiltinTypes.cpp.
References getShape().
Referenced by convertTensorType(), convolutionMatchAndRewriterHelper(), getAtomicOpScope(), getI64Values(), mlir::linalg::PadTensorOpTransformationPattern::matchAndRewrite(), and writeAPIntsToBuffer().
hasStaticShape() [2/2]
bool ShapedType::hasStaticShape (ArrayRef< int64_t > shape) const
If this has a static shape and the shape is equal to shape return true.
Definition at line 434 of file BuiltinTypes.cpp.
References mlir::Type::dyn_cast(), mlir::emitError(), getElementType(), getShape(), mlir::success(), and mlir::verify().
isDynamic()
static constexpr bool mlir::ShapedType::isDynamic (int64_t dSize) inline static
Whether the given dimension size indicates a dynamic dimension.
Definition at line 137 of file BuiltinTypes.h.
Referenced by mlir::tensor::canFoldIntoConsumerOp(), castDataPtr(), foldIdentityOffsetSizeAndStrideOpInterface(), mlir::MemRefRegion::getConstantBoundingSizeAndShape(), getDynamicDimIndex(), getExpandedOutputDimFromInputShape(), getShapeString(), mlir::linalg::hoistPaddingOnTensors(), isGenericOpExpandable(), isReshapableDimBand(), mlir::linalg::makeTiledShape(), mlir::OpWithOffsetSizesAndStridesConstantArgumentFolder< OpType, ResultTypeFunc, CastOpFunc >::matchAndRewrite(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), mlirShapedTypeIsDynamicSize(), padOperandToSmallestStaticBoundingBox(), mlir::detail::Parser::parseStrideList(), printDenseElementsAttrImpl(), mlir::OpTrait::util::staticallyKnownBroadcastable(), updateExpandedGenericOpRegion(), verify(), mlir::verifyCompatibleDims(), mlir::verifyCompatibleShape(), mlir::detail::verifyOffsetSizeAndStrideOp(), mlir::verifyReshapeLikeShapes(), and mlir::linalg::detail::verifyStructuredOpInterface().
isDynamicDim()
bool ShapedType::isDynamicDim (unsigned idx) const
Returns true if this dimension has a dynamic size (for ranked types); aborts for unranked types.
Definition at line 383 of file BuiltinTypes.cpp.
References getShape().
Referenced by getI64Values(), and joinShapes().
isDynamicStrideOrOffset()
static constexpr bool mlir::ShapedType::isDynamicStrideOrOffset (int64_t dStrideOrOffset) inline static
Definition at line 140 of file BuiltinTypes.h.
Referenced by castDataPtr(), foldIdentityOffsetSizeAndStrideOpInterface(), mlir::LLVMTypeConverter::getUnrankedMemRefDescriptorSize(), mlir::OpWithOffsetSizesAndStridesConstantArgumentFolder< OpType, ResultTypeFunc, CastOpFunc >::matchAndRewrite(), mlirShapedTypeIsDynamicStrideOrOffset(), and mlir::detail::verifyOffsetSizeAndStrideOp().
Member Data Documentation
kDynamicSize
constexpr int64_t ShapedType::kDynamicSize = -1 static
Definition at line 72 of file BuiltinTypes.h.
Referenced by computeReshapeCollapsedType(), computeTensorReshapeCollapsedType(), createNewAllocDeallocPairForShapedValue(), defaultAllocBufferCallBack(), doubleBuffer(), foldIdentityOffsetSizeAndStrideOpInterface(), fuse(), genBuffers(), mlir::linalg::getDynOperands(), mlir::ConvertToLLVMPattern::getMemRefDescriptorSizes(), mlir::getReassociationIndicesForReshape(), getTypeNumBytes(), mlir::linalg::hoistPaddingOnTensors(), iterateIndicesExcept(), mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite(), print(), mlir::linalg::skipUnitDimReshape(), and verify().
kDynamicStrideOrOffset
constexpr int64_t ShapedType::kDynamicStrideOrOffset static
Initial value:
=
      std::numeric_limits<int64_t>::min()
Definition at line 73 of file BuiltinTypes.h.
Referenced by computeReshapeCollapsedType(), mlir::eraseStridedLayout(), foldIdentityOffsetSizeAndStrideOpInterface(), fuse(), getDynamicMemRefType(), getMemrefConstantHorizontalStride(), mlir::getStridesAndOffset(), iterateIndicesExcept(), and verify().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp