MLIR: mlir::LocalAliasAnalysis Class Reference
mlir::LocalAliasAnalysis Class Reference
This class implements a local form of alias analysis that tries to identify the underlying values addressed by each value and performs a few basic checks to see if they alias.
#include "mlir/Analysis/AliasAnalysis/LocalAliasAnalysis.h"
Public Member Functions
virtual ~LocalAliasAnalysis ()=default
AliasResult alias (Value lhs, Value rhs)
Given two values, return their aliasing behavior.
ModRefResult getModRef (Operation *op, Value location)
Return the modify-reference behavior of op on location.
Protected Member Functions
virtual AliasResult aliasImpl (Value lhs, Value rhs)
Given the two values, return their aliasing behavior.
Detailed Description
This class implements a local form of alias analysis that tries to identify the underlying values addressed by each value and performs a few basic checks to see if they alias.
Definition at line 24 of file LocalAliasAnalysis.h.
Constructor & Destructor Documentation
~LocalAliasAnalysis()
virtual mlir::LocalAliasAnalysis::~LocalAliasAnalysis () virtual default
Member Function Documentation
alias()
AliasResult LocalAliasAnalysis::alias (Value lhs, Value rhs)
Given two values, return their aliasing behavior.
Given the two values, return their aliasing behavior.
Definition at line 330 of file LocalAliasAnalysis.cpp.
References aliasImpl(), collectUnderlyingAddressValues(), mlir::AliasResult::MayAlias, and mlir::AliasResult::MustAlias.
Referenced by getModRef().
aliasImpl()
AliasResult LocalAliasAnalysis::aliasImpl (Value lhs, Value rhs) protected virtual
Given the two values, return their aliasing behavior.
Definition at line 259 of file LocalAliasAnalysis.cpp.
References getAllocEffectFor(), mlir::Value::getParentBlock(), mlir::Region::getParentOp(), mlir::Value::getParentRegion(), mlir::Block::isEntryBlock(), mlir::Operation::isProperAncestor(), mlir::m_Constant(), mlir::matchPattern(), mlir::AliasResult::MayAlias, mlir::AliasResult::MustAlias, and mlir::AliasResult::NoAlias.
Referenced by alias().
getModRef()
ModRefResult LocalAliasAnalysis::getModRef (Operation * op, Value location)
Return the modify-reference behavior of op on location.
Definition at line 361 of file LocalAliasAnalysis.cpp.
References alias(), mlir::ModRefResult::getMod(), mlir::ModRefResult::getModAndRef(), mlir::ModRefResult::getNoModRef(), mlir::ModRefResult::getRef(), mlir::Operation::hasTrait(), mlir::ModRefResult::isModAndRef(), mlir::AliasResult::isNo(), mlir::AliasResult::MayAlias, and mlir::ModRefResult::merge().
The documentation for this class was generated from the following files:
include/mlir/Analysis/AliasAnalysis/LocalAliasAnalysis.h
lib/Analysis/AliasAnalysis/LocalAliasAnalysis.cpp