MLIR: TransformOpInterfaceFallbackModel Class Reference
TransformOpInterfaceFallbackModel Class Reference
Fallback model for the TransformOpInterface that uses C API callbacks.
Public Member Functions
void setCallbacks (MlirTransformOpInterfaceCallbacks callbacks)
Sets the callbacks that this FallbackModel will use.
~TransformOpInterfaceFallbackModel ()
::mlir::DiagnosedSilenceableFailure apply (Operation *op, ::mlir::transform::TransformRewriter &rewriter, ::mlir::transform::TransformResults &transformResults, ::mlir::transform::TransformState &state) const
bool allowsRepeatedHandleOperands (Operation *op) const
Static Public Member Functions
static TypeID getInterfaceID ()
static bool classof (const mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept *op)
Detailed Description
Fallback model for the TransformOpInterface that uses C API callbacks.
Definition at line 215 of file Transform.cpp.
Constructor & Destructor Documentation
~TransformOpInterfaceFallbackModel()
TransformOpInterfaceFallbackModel::~TransformOpInterfaceFallbackModel () inline
Definition at line 227 of file Transform.cpp.
Member Function Documentation
allowsRepeatedHandleOperands()
bool TransformOpInterfaceFallbackModel::allowsRepeatedHandleOperands (Operation * op) const inline
Definition at line 269 of file Transform.cpp.
References wrap().
apply()
::mlir::DiagnosedSilenceableFailure TransformOpInterfaceFallbackModel::apply (Operation * op, ::mlir::transform::TransformRewriter & rewriter, ::mlir::transform::TransformResults & transformResults, ::mlir::transform::TransformState & state) const inline
Definition at line 245 of file Transform.cpp.
References mlir::DiagnosedSilenceableFailure::definiteFailure(), mlir::Operation::emitError(), MlirDiagnosedSilenceableFailureDefiniteFailure, MlirDiagnosedSilenceableFailureSilenceableFailure, MlirDiagnosedSilenceableFailureSuccess, mlir::DiagnosedSilenceableFailure::silenceableFailure(), mlir::DiagnosedSilenceableFailure::success(), and wrap().
classof()
bool TransformOpInterfaceFallbackModel::classof (const mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept * op) inline static
Definition at line 236 of file Transform.cpp.
getInterfaceID()
TypeID TransformOpInterfaceFallbackModel::getInterfaceID () inline static
Definition at line 232 of file Transform.cpp.
setCallbacks()
void TransformOpInterfaceFallbackModel::setCallbacks (MlirTransformOpInterfaceCallbacks callbacks) inline
Sets the callbacks that this FallbackModel will use.
NB: the callbacks can only be set through this method as the RegisteredOperationName::attachInterface mechanism default-constructs the FallbackModel without being able to provide arguments.
Definition at line 223 of file Transform.cpp.
Referenced by mlirTransformOpInterfaceAttachFallbackModel().
The documentation for this class was generated from the following file:
lib/CAPI/Dialect/Transform.cpp