MLIR: mlir::Op< ConcreteType, Traits > Class Template Reference
mlir::Op< ConcreteType, Traits > Class Template Reference
This provides public APIs that all operations should have.
#include "mlir/IR/OpDefinition.h"
Public Types
using ConcreteOpType = ConcreteType
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
template<typename T >
using InferredProperties = typename PropertiesSelector< T >::type
Public Member Functions
ConcreteType clone ()
Create a deep copy of this operation.
ConcreteType cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
template<typename T = ConcreteType>
InferredProperties< T > & getProperties ()
Operation * getOperation ()
Inherit getOperation from OpState.
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
LogicalResult verifyRegions ()
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * operator-> () const
Shortcut of -> to access a member of Operation.
Operation * getOperation ()
Return the operation that this refers to.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags={})
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==1, RetT > walk (FnT &&callback)
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==2, RetT > walk (FnT &&callback)
Generic walker with a stage aware callback.
Static Public Member Functions
template<template< typename T > class Trait>
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
template<typename T >
static std::enable_if_t< std::is_base_of< OpState, T >::value, bool > classof (const T *op)
Provide classof support for other OpBase derived classes, such as Interfaces.
static ConcreteOpType getFromOpaquePointer (const void *pointer)
template<typename... Models>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
template<typename PropertiesTy >
static LogicalResult setPropertiesFromAttr (PropertiesTy &prop, Attribute attr, function_ref< InFlightDiagnostic()> emitError)
Convert the provided attribute to a property and assigned it to the provided properties.
template<typename PropertiesTy >
static Attribute getPropertiesAsAttr (MLIRContext *ctx, const PropertiesTy &prop)
Convert the provided properties to an attribute.
template<typename PropertiesTy >
static llvm::hash_code computePropertiesHash (const PropertiesTy &prop)
Hash the provided properties.
static constexpr bool hasProperties ()
Returns true if this operation defines a Properties inner type.
template<typename T = ConcreteType>
static void populateDefaultProperties (OperationName opName, InferredProperties< T > &properties)
This hook populates any unset default attrs when mapped to properties.
template<typename T >
static void printProperties (MLIRContext *ctx, OpAsmPrinter &p, const T &properties, ArrayRef< StringRef > elidedProps={})
Print the operation properties with names not included within 'elidedProps'.
template<typename T = ConcreteType>
static ParseResult parseProperties (OpAsmParser &parser, OperationState &result)
Parses 'prop-dict' for the operation.
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
static void populateDefaultAttrs (const OperationName &, NamedAttrList &)
This hook populates any unset default attrs.
Additional Inherited Members
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
LogicalResult verifyRegions ()
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Parse the custom form of an operation.
static void print (Operation *op, OpAsmPrinter &p, StringRef defaultDialect)
Print the operation.
static ParseResult genericParseProperties (OpAsmParser &parser, Attribute &result)
Parse properties as a Attribute.
static void genericPrintProperties (OpAsmPrinter &p, Attribute properties, ArrayRef< StringRef > elidedProps={})
Print the properties as a Attribute with names not included within 'elidedProps'.
static void printOpName (Operation *op, OpAsmPrinter &p, StringRef defaultDialect)
Print an operation name, eliding the dialect prefix if necessary.
static EmptyProperties & getEmptyProperties ()
For all op which don't have properties, we keep a single instance of EmptyProperties to be used where a reference to a properties is needed: this allow to bind a pointer to the reference without triggering UB.
Detailed Description
template<typename ConcreteType, template< typename T > class... Traits>
class mlir::Op< ConcreteType, Traits >
This provides public APIs that all operations should have.
The template argument 'ConcreteType' should be the concrete type by CRTP and the others are base classes by the policy pattern.
Definition at line 1673 of file OpDefinition.h.
Member Typedef Documentation
ConcreteOpType
template<typename ConcreteType , template< typename T > class... Traits> using mlir::Op< ConcreteType, Traits >::ConcreteOpType = ConcreteType
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Definition at line 1718 of file OpDefinition.h.
InferredProperties
template<typename ConcreteType , template< typename T > class... Traits> template<typename T > using mlir::Op< ConcreteType, Traits >::InferredProperties = typename PropertiesSelector<T>::type
Definition at line 1975 of file OpDefinition.h.
Constructor & Destructor Documentation
Op() [1/3]
template<typename ConcreteType , template< typename T > class... Traits> mlir::Op< ConcreteType, Traits >::Op () inline explicit
This is a public constructor. Any op can be initialized to null.
Definition at line 1721 of file OpDefinition.h.
Op() [2/3]
template<typename ConcreteType , template< typename T > class... Traits> mlir::Op< ConcreteType, Traits >::Op (std::nullptr_t) inline
Definition at line 1722 of file OpDefinition.h.
Op() [3/3]
template<typename ConcreteType , template< typename T > class... Traits> mlir::Op< ConcreteType, Traits >::Op (Operation * state) inline explicit
This is a public constructor to enable access via the llvm::cast family of methods.
This should not be used directly.
Definition at line 1726 of file OpDefinition.h.
Member Function Documentation
attachInterface()
template<typename ConcreteType , template< typename T > class... Traits> template<typename... Models> static void mlir::Op< ConcreteType, Traits >::attachInterface (MLIRContext & context) inline static
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
Definition at line 1740 of file OpDefinition.h.
References mlir::RegisteredOperationName::lookup().
classof() [1/2]
template<typename ConcreteType , template< typename T > class... Traits> template<typename T > static std::enable_if_t<std::is_base_of<OpState, T>::value, bool> mlir::Op< ConcreteType, Traits >::classof (const T * op) inline static
Provide classof support for other OpBase derived classes, such as Interfaces.
Definition at line 1712 of file OpDefinition.h.
References mlir::Op< ConcreteType, Traits >::classof(), and mlir::Op< ConcreteType, Traits >::getOperation().
classof() [2/2]
template<typename ConcreteType , template< typename T > class... Traits> static bool mlir::Op< ConcreteType, Traits >::classof (Operation * op) inline static
Return true if this "op class" can match against the specified operation.
Definition at line 1697 of file OpDefinition.h.
References mlir::Operation::getName(), mlir::Operation::getRegisteredInfo(), and mlir::OperationName::getStringRef().
Referenced by mlir::Op< ConcreteType, Traits >::classof().
clone()
template<typename ConcreteType , template< typename T > class... Traits> ConcreteType mlir::Op< ConcreteType, Traits >::clone () inline
Create a deep copy of this operation.
Definition at line 1687 of file OpDefinition.h.
References mlir::Op< ConcreteType, Traits >::clone(), and mlir::Op< ConcreteType, Traits >::getOperation().
Referenced by mlir::Op< ConcreteType, Traits >::clone().
cloneWithoutRegions()
template<typename ConcreteType , template< typename T > class... Traits> ConcreteType mlir::Op< ConcreteType, Traits >::cloneWithoutRegions () inline
Create a partial copy of this operation without traversing into attached regions.
The new operation will have the same number of regions as the original one, but they will be left empty.
Definition at line 1692 of file OpDefinition.h.
References mlir::Op< ConcreteType, Traits >::getOperation().
computePropertiesHash()
template<typename ConcreteType , template< typename T > class... Traits> template<typename PropertiesTy > static llvm::hash_code mlir::Op< ConcreteType, Traits >::computePropertiesHash (const PropertiesTy & prop) inline static
Hash the provided properties.
This default implementation forwards to a free function computeHash that can be looked up with ADL in the namespace where the properties are defined. It can also be overridden in the derived ConcreteOp.
Definition at line 1775 of file OpDefinition.h.
References computeHash().
getAsOpaquePointer()
template<typename ConcreteType , template< typename T > class... Traits> const void* mlir::Op< ConcreteType, Traits >::getAsOpaquePointer () const inline
Methods for supporting PointerLikeTypeTraits.
Definition at line 1729 of file OpDefinition.h.
getFromOpaquePointer()
template<typename ConcreteType , template< typename T > class... Traits> static ConcreteOpType mlir::Op< ConcreteType, Traits >::getFromOpaquePointer (const void * pointer) inline static
Definition at line 1732 of file OpDefinition.h.
getOperation()
template<typename ConcreteType , template< typename T > class... Traits> Operation* mlir::OpState::getOperation inline
Inherit getOperation from OpState.
Definition at line 112 of file OpDefinition.h.
Referenced by mlir::Op< ConcreteType, Traits >::classof(), mlir::Op< ConcreteType, Traits >::clone(), mlir::Op< ConcreteType, Traits >::cloneWithoutRegions(), mlir::shard::getGrid(), getGridAndVerifyAxes(), and mlir::Op< ConcreteType, Traits >::getProperties().
getProperties()
template<typename ConcreteType , template< typename T > class... Traits> template<typename T = ConcreteType> InferredProperties<T>& mlir::Op< ConcreteType, Traits >::getProperties () inline
Definition at line 1977 of file OpDefinition.h.
References mlir::OpState::getEmptyProperties(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Operation::getPropertiesStorageUnsafe(), and mlir::Op< ConcreteType, Traits >::hasProperties().
getPropertiesAsAttr()
template<typename ConcreteType , template< typename T > class... Traits> template<typename PropertiesTy > static Attribute mlir::Op< ConcreteType, Traits >::getPropertiesAsAttr (MLIRContext * ctx, const PropertiesTy & prop) inline static
Convert the provided properties to an attribute.
This default implementation forwards to a free function getPropertiesAsAttribute that can be looked up with ADL in the namespace where the properties are defined. It can also be overridden in the derived ConcreteOp.
Definition at line 1766 of file OpDefinition.h.
hasProperties()
template<typename ConcreteType , template< typename T > class... Traits> static constexpr bool mlir::Op< ConcreteType, Traits >::hasProperties () inline static constexpr
Returns true if this operation defines a Properties inner type.
Definition at line 1843 of file OpDefinition.h.
Referenced by mlir::Op< ConcreteType, Traits >::getProperties().
hasTrait()
template<typename ConcreteType , template< typename T > class... Traits> template<template< typename T > class Trait> static constexpr bool mlir::Op< ConcreteType, Traits >::hasTrait () inline static constexpr
Return if this operation contains the provided trait.
Definition at line 1682 of file OpDefinition.h.
parseProperties()
template<typename ConcreteType , template< typename T > class... Traits> template<typename T = ConcreteType> static ParseResult mlir::Op< ConcreteType, Traits >::parseProperties (OpAsmParser & parser, OperationState & result) inline static
Parses 'prop-dict' for the operation.
Unless overridden, the method will parse the properties using the generic property dictionary using the '<{ ... }>' syntax. The resulting properties are stored within the property structure of 'result', accessible via 'getOrAddProperties'.
Definition at line 2009 of file OpDefinition.h.
References mlir::OpState::emitError(), mlir::emitError(), mlir::OpState::genericParseProperties(), mlir::get(), mlir::OperationState::getContext(), mlir::OperationState::getOrAddProperties(), mlir::OperationName::getStringRef(), mlir::OperationState::location, and mlir::OperationState::name.
populateDefaultProperties()
template<typename ConcreteType , template< typename T > class... Traits> template<typename T = ConcreteType> static void mlir::Op< ConcreteType, Traits >::populateDefaultProperties (OperationName opName, InferredProperties< T > & properties) inline static
This hook populates any unset default attrs when mapped to properties.
Definition at line 1987 of file OpDefinition.h.
printProperties()
template<typename ConcreteType , template< typename T > class... Traits> template<typename T > static void mlir::Op< ConcreteType, Traits >::printProperties (MLIRContext * ctx, OpAsmPrinter & p, const T & properties, ArrayRef< StringRef > elidedProps = {}) inline static
Print the operation properties with names not included within 'elidedProps'.
Unless overridden, this method will try to dispatch to a printProperties free-function if it exists, and otherwise by converting the properties to an Attribute.
Definition at line 1995 of file OpDefinition.h.
setPropertiesFromAttr()
template<typename ConcreteType , template< typename T > class... Traits> template<typename PropertiesTy > static LogicalResult mlir::Op< ConcreteType, Traits >::setPropertiesFromAttr (PropertiesTy & prop, Attribute attr, function_ref< InFlightDiagnostic()> emitError) inline static
Convert the provided attribute to a property and assigned it to the provided properties.
This default implementation forwards to a free function setPropertiesFromAttribute that can be looked up with ADL in the namespace where the properties are defined. It can also be overridden in the derived ConcreteOp.
Definition at line 1757 of file OpDefinition.h.
References mlir::OpState::emitError().
verify()
template<typename ConcreteType , template< typename T > class... Traits> LogicalResult mlir::OpState::verify inline
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
Definition at line 214 of file OpDefinition.h.
verifyRegions()
template<typename ConcreteType , template< typename T > class... Traits> LogicalResult mlir::OpState::verifyRegions inline
Definition at line 215 of file OpDefinition.h.
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h