MLIR: mlir::LatticeElement< ValueT > Class Template Reference
mlir::LatticeElement< ValueT > Class Template Reference final
This class represents a lattice holding a specific value of type ValueT.
#include "mlir/Analysis/DataFlowAnalysis.h"
Public Member Functions
LatticeElement ()=delete
LatticeElement (const ValueT &knownValue)
ValueT & getValue ()
Return the value held by this lattice.
const ValueT & getValue () const
bool isUninitialized () const final
Returns true if the value of this lattice hasn't yet been initialized.
ChangeResult join (const detail::AbstractLatticeElement &rhs) final
Join the information contained in the 'rhs' lattice into this lattice.
ChangeResult join (const ValueT &rhs)
Join the information contained in the 'rhs' value into this lattice.
ChangeResult markPessimisticFixpoint () final
Mark the lattice element as having reached a pessimistic fixpoint.
void markOptimisticFixpoint () final
Mark the lattice element as having reached an optimistic fixpoint.
bool isAtFixpoint () const final
Returns true if the lattice has reached a fixpoint.
Public Member Functions inherited from mlir::detail::AbstractLatticeElement
virtual ~AbstractLatticeElement ()
Detailed Description
template<typename ValueT>
class mlir::LatticeElement< ValueT >
This class represents a lattice holding a specific value of type ValueT.
Lattice values (ValueT) are required to adhere to the following:
static ValueT join(const ValueT &lhs, const ValueT &rhs);
This method conservatively joins the information held by lhs and rhs into a new value. This method is required to be monotonic.
static ValueT getPessimisticValueState(MLIRContext *context);
This method computes a pessimistic/conservative value state assuming no information about the state of the IR.
static ValueT getPessimisticValueState(Value value);
This method computes a pessimistic/conservative value state for value assuming only information present in the current IR.
bool operator==(const ValueT &rhs) const;
Definition at line 106 of file DataFlowAnalysis.h.
Constructor & Destructor Documentation
LatticeElement() [1/2]
template<typename ValueT> mlir::LatticeElement< ValueT >::LatticeElement () delete
LatticeElement() [2/2]
template<typename ValueT> mlir::LatticeElement< ValueT >::LatticeElement (const ValueT & knownValue) inline
Definition at line 109 of file DataFlowAnalysis.h.
Member Function Documentation
getValue() [1/2]
template<typename ValueT> ValueT& mlir::LatticeElement< ValueT >::getValue () inline
Return the value held by this lattice.
This requires that the value is initialized.
Definition at line 113 of file DataFlowAnalysis.h.
Referenced by mlir::LatticeElement< ValueT >::join(), and replaceWithConstant().
getValue() [2/2]
template<typename ValueT> const ValueT& mlir::LatticeElement< ValueT >::getValue () const inline
Definition at line 117 of file DataFlowAnalysis.h.
isAtFixpoint()
template<typename ValueT> bool mlir::LatticeElement< ValueT >::isAtFixpoint () const inline final virtual
Returns true if the lattice has reached a fixpoint.
A fixpoint is when the information optimistically assumed to be true is the same as the information known to be true.
Implements mlir::detail::AbstractLatticeElement.
Definition at line 186 of file DataFlowAnalysis.h.
isUninitialized()
template<typename ValueT> bool mlir::LatticeElement< ValueT >::isUninitialized () const inline final virtual
Returns true if the value of this lattice hasn't yet been initialized.
Implements mlir::detail::AbstractLatticeElement.
Definition at line 123 of file DataFlowAnalysis.h.
Referenced by mlir::LatticeElement< ValueT >::join().
join() [1/2]
template<typename ValueT> ChangeResult mlir::LatticeElement< ValueT >::join (const detail::AbstractLatticeElement< ValueT > & rhs) inline final virtual
Join the information contained in the 'rhs' lattice into this lattice.
Returns if the state of the current lattice changed.
Implements mlir::detail::AbstractLatticeElement.
Definition at line 127 of file DataFlowAnalysis.h.
References mlir::LatticeElement< ValueT >::getValue(), mlir::LatticeElement< ValueT >::isUninitialized(), and mlir::NoChange.
join() [2/2]
template<typename ValueT> ChangeResult mlir::LatticeElement< ValueT >::join (const ValueT & rhs) inline
Join the information contained in the 'rhs' value into this lattice.
Returns if the state of the current lattice changed.
Definition at line 141 of file DataFlowAnalysis.h.
References mlir::Change, and mlir::NoChange.
markOptimisticFixpoint()
template<typename ValueT> void mlir::LatticeElement< ValueT >::markOptimisticFixpoint () inline final virtual
Mark the lattice element as having reached an optimistic fixpoint.
This means that we optimisticly assume the current value is the true state.
Implements mlir::detail::AbstractLatticeElement.
Definition at line 178 of file DataFlowAnalysis.h.
markPessimisticFixpoint()
template<typename ValueT> ChangeResult mlir::LatticeElement< ValueT >::markPessimisticFixpoint () inline final virtual
Mark the lattice element as having reached a pessimistic fixpoint.
This means that the lattice may potentially have conflicting value states, and only the conservatively known value state should be relied on.
Implements mlir::detail::AbstractLatticeElement.
Definition at line 166 of file DataFlowAnalysis.h.
References mlir::Change, and mlir::NoChange.
The documentation for this class was generated from the following file:
include/mlir/Analysis/DataFlowAnalysis.h