MLIR: mlir::tosa::TosaSpecificationVersion Class Reference
mlir::tosa::TosaSpecificationVersion Class Reference
A thin wrapper around the SpecificationVersion enum to represent and provide utilities around the TOSA specification version.
#include "mlir/Dialect/Tosa/IR/TargetEnv.h"
Public Member Functions
TosaSpecificationVersion ()=default
TosaSpecificationVersion (uint32_t major, uint32_t minor)
TosaSpecificationVersion (SpecificationVersion version)
bool isBackwardsCompatibleWith (TosaSpecificationVersion baseVersion) const
uint32_t getMajor () const
uint32_t getMinor () const
Detailed Description
A thin wrapper around the SpecificationVersion enum to represent and provide utilities around the TOSA specification version.
Definition at line 55 of file TargetEnv.h.
Constructor & Destructor Documentation
TosaSpecificationVersion() [1/3]
mlir::tosa::TosaSpecificationVersion::TosaSpecificationVersion () default
Referenced by isBackwardsCompatibleWith(), and TosaSpecificationVersion().
TosaSpecificationVersion() [2/3]
mlir::tosa::TosaSpecificationVersion::TosaSpecificationVersion (uint32_t major, uint32_t minor) inline
Definition at line 59 of file TargetEnv.h.
TosaSpecificationVersion() [3/3]
mlir::tosa::TosaSpecificationVersion::TosaSpecificationVersion (SpecificationVersion version) inline
Definition at line 61 of file TargetEnv.h.
References TosaSpecificationVersion().
Member Function Documentation
getMajor()
uint32_t mlir::tosa::TosaSpecificationVersion::getMajor () const inline
Definition at line 69 of file TargetEnv.h.
Referenced by mlir::tosa::stringifyVersion().
getMinor()
uint32_t mlir::tosa::TosaSpecificationVersion::getMinor () const inline
Definition at line 70 of file TargetEnv.h.
Referenced by mlir::tosa::stringifyVersion().
isBackwardsCompatibleWith()
bool mlir::tosa::TosaSpecificationVersion::isBackwardsCompatibleWith (TosaSpecificationVersion baseVersion) const inline
Definition at line 64 of file TargetEnv.h.
References TosaSpecificationVersion().
Referenced by TosaProfileCompliance::checkProfileOrExtension(), and mlir::tosa::TargetEnv::verifyTargetInformation().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Tosa/IR/TargetEnv.h