MLIR: mlir::PyFileAccumulator Class Reference
mlir::PyFileAccumulator Class Reference
Accumulates into a file, either writing text (default) or binary.
#include "Bindings/Python/NanobindUtils.h"
Public Member Functions
PyFileAccumulator (const nanobind::object &fileOrStringObject, bool binary)
MlirStringCallback getCallback ()
void * getUserData ()
Detailed Description
Accumulates into a file, either writing text (default) or binary.
The file may be a Python file-like object or a path to a file.
Definition at line 139 of file NanobindUtils.h.
Constructor & Destructor Documentation
PyFileAccumulator()
mlir::PyFileAccumulator::PyFileAccumulator (const nanobind::object & fileOrStringObject, bool binary) inline
Definition at line 141 of file NanobindUtils.h.
Member Function Documentation
getCallback()
MlirStringCallback mlir::PyFileAccumulator::getCallback () inline
Definition at line 157 of file NanobindUtils.h.
Referenced by mlir::python::PyDiagnostic::getMessage(), and mlir::python::PyOperationBase::writeBytecode().
getUserData()
void * mlir::PyFileAccumulator::getUserData () inline
Definition at line 162 of file NanobindUtils.h.
Referenced by mlir::python::PyDiagnostic::getMessage(), and mlir::python::PyOperationBase::writeBytecode().
The documentation for this class was generated from the following file:
lib/Bindings/Python/NanobindUtils.h