MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig Class Reference
Owning Wrapper around a GreedyRewriteDriverConfig.
Public Member Functions
PyGreedyRewriteConfig ()
PyGreedyRewriteConfig (PyGreedyRewriteConfig &&other) noexcept
PyGreedyRewriteConfig (const PyGreedyRewriteConfig &other) noexcept
MlirGreedyRewriteDriverConfig get ()
void setMaxIterations (int64_t maxIterations)
void setMaxNumRewrites (int64_t maxNumRewrites)
void setUseTopDownTraversal (bool useTopDownTraversal)
void enableFolding (bool enable)
void setStrictness (PyGreedyRewriteStrictness strictness)
void setRegionSimplificationLevel (PyGreedySimplifyRegionLevel level)
void enableConstantCSE (bool enable)
int64_t getMaxIterations ()
int64_t getMaxNumRewrites ()
bool getUseTopDownTraversal ()
bool isFoldingEnabled ()
PyGreedyRewriteStrictness getStrictness ()
PyGreedySimplifyRegionLevel getRegionSimplificationLevel ()
bool isConstantCSEEnabled ()
Detailed Description
Owning Wrapper around a GreedyRewriteDriverConfig.
Definition at line 416 of file Rewrite.cpp.
Constructor & Destructor Documentation
PyGreedyRewriteConfig() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::PyGreedyRewriteConfig () inline
Definition at line 418 of file Rewrite.cpp.
Referenced by setUseTopDownTraversal().
PyGreedyRewriteConfig() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::PyGreedyRewriteConfig (PyGreedyRewriteConfig && other) inline noexcept
Definition at line 421 of file Rewrite.cpp.
PyGreedyRewriteConfig() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::PyGreedyRewriteConfig (const PyGreedyRewriteConfig & other) inline noexcept
Definition at line 423 of file Rewrite.cpp.
Member Function Documentation
enableConstantCSE()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::enableConstantCSE (bool enable) inline
Definition at line 457 of file Rewrite.cpp.
References mlir::get(), mlirGreedyRewriteDriverConfigSetMaxNumRewrites(), and setMaxNumRewrites().
enableFolding()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::enableFolding (bool enable) inline
Definition at line 443 of file Rewrite.cpp.
Referenced by getMaxNumRewrites().
get()
MlirGreedyRewriteDriverConfig mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::get () inline
Definition at line 426 of file Rewrite.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::ANY_OP, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::EXISTING_AND_NEW_OPS, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::EXISTING_OPS, MLIR_GREEDY_REWRITE_STRICTNESS_ANY_OP, MLIR_GREEDY_REWRITE_STRICTNESS_EXISTING_AND_NEW_OPS, and MLIR_GREEDY_REWRITE_STRICTNESS_EXISTING_OPS.
getMaxIterations()
int64_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::getMaxIterations () inline
Definition at line 461 of file Rewrite.cpp.
References mlir::get(), mlirGreedyRewriteDriverConfigSetUseTopDownTraversal(), and setUseTopDownTraversal().
getMaxNumRewrites()
int64_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::getMaxNumRewrites () inline
Definition at line 465 of file Rewrite.cpp.
References enableFolding(), mlir::get(), and mlirGreedyRewriteDriverConfigEnableFolding().
Referenced by isConstantCSEEnabled().
getRegionSimplificationLevel()
PyGreedySimplifyRegionLevel mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::getRegionSimplificationLevel () inline
Definition at line 482 of file Rewrite.cpp.
getStrictness()
PyGreedyRewriteStrictness mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::getStrictness () inline
Definition at line 477 of file Rewrite.cpp.
getUseTopDownTraversal()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::getUseTopDownTraversal () inline
Definition at line 469 of file Rewrite.cpp.
References mlir::get(), mlirGreedyRewriteDriverConfigSetStrictness(), and setStrictness().
isConstantCSEEnabled()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::isConstantCSEEnabled () inline
Definition at line 487 of file Rewrite.cpp.
References mlir::get(), getMaxNumRewrites(), and mlirGreedyRewriteDriverConfigGetMaxNumRewrites().
isFoldingEnabled()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::isFoldingEnabled () inline
Definition at line 473 of file Rewrite.cpp.
setMaxIterations()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::setMaxIterations (int64_t maxIterations) inline
Definition at line 430 of file Rewrite.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DISABLED, and MLIR_GREEDY_SIMPLIFY_REGION_LEVEL_DISABLED.
Referenced by setRegionSimplificationLevel().
setMaxNumRewrites()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::setMaxNumRewrites (int64_t maxNumRewrites) inline
Definition at line 434 of file Rewrite.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::AGGRESSIVE, MLIR_GREEDY_SIMPLIFY_REGION_LEVEL_AGGRESSIVE, MLIR_GREEDY_SIMPLIFY_REGION_LEVEL_NORMAL, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::NORMAL.
Referenced by enableConstantCSE().
setRegionSimplificationLevel()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::setRegionSimplificationLevel (PyGreedySimplifyRegionLevel level) inline
Definition at line 452 of file Rewrite.cpp.
References mlir::get(), mlirGreedyRewriteDriverConfigSetMaxIterations(), and setMaxIterations().
setStrictness()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::setStrictness (PyGreedyRewriteStrictness strictness) inline
Definition at line 447 of file Rewrite.cpp.
Referenced by getUseTopDownTraversal().
setUseTopDownTraversal()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteConfig::setUseTopDownTraversal (bool useTopDownTraversal) inline
Definition at line 438 of file Rewrite.cpp.
References mlirGreedyRewriteDriverConfigCreate(), and PyGreedyRewriteConfig().
Referenced by getMaxIterations().
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.cpp