MLIR: mlir::transform::TransformOptions Class Reference
mlir::transform::TransformOptions Class Reference
Options controlling the application of transform operations by the TransformState.
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
Public Member Functions
TransformOptions ()=default
TransformOptions (const TransformOptions &)=default
TransformOptions & operator= (const TransformOptions &)=default
TransformOptions & enableExpensiveChecks (bool enable=true)
Requests computationally expensive checks of the transform and payload IR well-formedness to be performed before each transformation.
TransformOptions & enableEnforceSingleToplevelTransformOp (bool enable=true)
bool getExpensiveChecksEnabled () const
Returns true if the expensive checks are requested.
bool getEnforceSingleToplevelTransformOp () const
Detailed Description
Options controlling the application of transform operations by the TransformState.
Definition at line 95 of file TransformInterfaces.h.
Constructor & Destructor Documentation
TransformOptions() [1/2]
mlir::transform::TransformOptions::TransformOptions () default
Referenced by enableEnforceSingleToplevelTransformOp(), enableExpensiveChecks(), operator=(), and TransformOptions().
TransformOptions() [2/2]
mlir::transform::TransformOptions::TransformOptions (const TransformOptions &) default
References TransformOptions().
Member Function Documentation
enableEnforceSingleToplevelTransformOp()
TransformOptions & mlir::transform::TransformOptions::enableEnforceSingleToplevelTransformOp (bool enable = true) inline
Definition at line 110 of file TransformInterfaces.h.
References TransformOptions().
enableExpensiveChecks()
TransformOptions & mlir::transform::TransformOptions::enableExpensiveChecks (bool enable = true) inline
Requests computationally expensive checks of the transform and payload IR well-formedness to be performed before each transformation.
In particular, these ensure that the handles still point to valid operations when used.
Definition at line 104 of file TransformInterfaces.h.
References TransformOptions().
getEnforceSingleToplevelTransformOp()
bool mlir::transform::TransformOptions::getEnforceSingleToplevelTransformOp () const inline
Definition at line 119 of file TransformInterfaces.h.
getExpensiveChecksEnabled()
bool mlir::transform::TransformOptions::getExpensiveChecksEnabled () const inline
Returns true if the expensive checks are requested.
Definition at line 116 of file TransformInterfaces.h.
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply().
operator=()
TransformOptions & mlir::transform::TransformOptions::operator= (const TransformOptions &) default
References TransformOptions().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h