MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute Class Reference
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseResourceElementsAttribute >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyDenseResourceElementsAttribute getFromBuffer (const nb_buffer &buffer, const std::string &name, const PyType &type, std::optional< size_t > alignment, bool isMutable, DefaultingPyMlirContext contextWrapper)
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseResourceElementsAttribute >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction
static constexpr const char * pyClassName = "DenseResourceElementsAttr"
static const MlirStringRef name
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseResourceElementsAttribute >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseResourceElementsAttribute >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Detailed Description
Definition at line 508 of file IRAttributes.h.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute::bindDerived (ClassTy & c) static
Definition at line 1152 of file IRAttributes.cpp.
References getFromBuffer(), and kDenseResourceElementsAttrGetFromBufferDocstring.
getFromBuffer()
PyDenseResourceElementsAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute::getFromBuffer (const nb_buffer & buffer, const std::string & name, const PyType & type, std::optional< size_t > alignment, bool isMutable, DefaultingPyMlirContext contextWrapper) static
Definition at line 1088 of file IRAttributes.cpp.
References mlirTypeIsAShaped(), mlirUnmanagedDenseResourceElementsAttrGet(), name, Py_IsFinalizing, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
Referenced by bindDerived().
PyConcreteAttribute() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute () default
PyConcreteAttribute() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyAttribute & orig) inline
Definition at line 1085 of file IRCore.h.
PyConcreteAttribute() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr) inline
Definition at line 1083 of file IRCore.h.
Member Data Documentation
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute::isaFunction static constexpr
Initial value:
=
      mlirAttributeIsADenseResourceElements
Definition at line 511 of file IRAttributes.h.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute::name inline static
Initial value:
=
      mlirDenseResourceElementsAttrGetName()
Definition at line 515 of file IRAttributes.h.
Referenced by getFromBuffer().
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute::pyClassName = "DenseResourceElementsAttr" static constexpr
Definition at line 513 of file IRAttributes.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRAttributes.h
lib/Bindings/Python/IRAttributes.cpp