MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr Class Reference
Wrapper around MlirAffineExpr. Affine expressions are owned by the context.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr)
bool operator== (const PyAffineExpr &other) const
operator MlirAffineExpr () const
MlirAffineExpr get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineExpr.
PyAffineExpr add (const PyAffineExpr &other) const
PyAffineExpr mul (const PyAffineExpr &other) const
PyAffineExpr floorDiv (const PyAffineExpr &other) const
PyAffineExpr ceilDiv (const PyAffineExpr &other) const
PyAffineExpr mod (const PyAffineExpr &other) const
nanobind::typed< nanobind::object, PyAffineExpr > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyAffineExpr createFromCapsule (const nanobind::object &capsule)
Creates a PyAffineExpr from the MlirAffineExpr wrapped by a capsule.
Detailed Description
Wrapper around MlirAffineExpr. Affine expressions are owned by the context.
Definition at line 1336 of file IRCore.h.
Constructor & Destructor Documentation
PyAffineExpr()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::PyAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr) inline
Definition at line 1338 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject().
Referenced by add(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::castFrom(), ceilDiv(), createFromCapsule(), floorDiv(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::lhs(), mod(), mul(), operator==(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::rhs().
Member Function Documentation
add()
PyAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::add (const PyAffineExpr & other) const
References PyAffineExpr().
ceilDiv()
PyAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::ceilDiv (const PyAffineExpr & other) const
References PyAffineExpr().
createFromCapsule()
PyAffineExpr PyAffineExpr::createFromCapsule (const nanobind::object & capsule) static
Creates a PyAffineExpr from the MlirAffineExpr wrapped by a capsule.
Note that PyAffineExpr instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirAffineExpr is taken by calling this function.
Definition at line 360 of file IRAffine.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlirAffineExprGetContext(), mlirAffineExprIsNull(), mlirPythonCapsuleToAffineExpr(), and PyAffineExpr().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
floorDiv()
PyAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::floorDiv (const PyAffineExpr & other) const
References PyAffineExpr().
get()
MlirAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::get () const inline
Definition at line 1342 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::lhs(), maybeDownCast(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::rhs().
getCapsule()
nb::object PyAffineExpr::getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineExpr.
Definition at line 356 of file IRAffine.cpp.
References mlirPythonAffineExprToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
maybeDownCast()
nb::typed< nb::object, PyAffineExpr > PyAffineExpr::maybeDownCast ()
Definition at line 369 of file IRAffine.cpp.
References get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirAffineExprIsAAdd(), mlirAffineExprIsACeilDiv(), mlirAffineExprIsAConstant(), mlirAffineExprIsADim(), mlirAffineExprIsAFloorDiv(), mlirAffineExprIsAMod(), mlirAffineExprIsAMul(), and mlirAffineExprIsASymbol().
Referenced by mod(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
mod()
PyAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::mod (const PyAffineExpr & other) const
References maybeDownCast(), and PyAffineExpr().
mul()
PyAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::mul (const PyAffineExpr & other) const
References PyAffineExpr().
operator MlirAffineExpr()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::operator MlirAffineExpr () const inline
Definition at line 1341 of file IRCore.h.
operator==()
bool PyAffineExpr::operator== (const PyAffineExpr & other) const
Definition at line 352 of file IRAffine.cpp.
References mlirAffineExprEqual(), and PyAffineExpr().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRAffine.cpp