MLIR: mlir::tracing::Action Class Reference
mlir::tracing::Action Class Reference abstract
An action is a specific action that is to be taken by the compiler, that can be toggled and controlled by an external user.
#include "mlir/IR/Action.h"
Public Member Functions
virtual ~Action ()=default
TypeID getActionID () const
Return the unique action id of this action, use for casting functionality.
virtual StringRef getTag () const =0
Return a string "tag" which intends to uniquely identify this type of action.
virtual void print (raw_ostream &os) const
virtual ArrayRef< IRUnit > getContextIRUnits () const
Return the set of IR units that are associated with this action.
Protected Member Functions
Action (TypeID actionID, ArrayRef< IRUnit > irUnits)
Protected Attributes
TypeID actionID
The type of the derived action class, used for isa/dyn_cast.
ArrayRef< IRUnit > irUnits
Set of IR units (operations, regions, blocks, values) that are associated with this action.
Detailed Description
An action is a specific action that is to be taken by the compiler, that can be toggled and controlled by an external user.
There are no constraints on the granularity of an action, it could be as simple as "perform this fold" and as complex as "run this pass pipeline".
This class represents the base class of the ActionImpl class (see below). This holds the template-invariant elements of the Action class.
Definition at line 38 of file Action.h.
Constructor & Destructor Documentation
~Action()
virtual mlir::tracing::Action::~Action () virtual default
Action()
mlir::tracing::Action::Action (TypeID actionID, ArrayRef< IRUnit > irUnits) inline protected
Definition at line 58 of file Action.h.
References actionID, and irUnits.
Referenced by mlir::tracing::ActionImpl< PassExecutionAction >::classof().
Member Function Documentation
getActionID()
TypeID mlir::tracing::Action::getActionID () const inline
Return the unique action id of this action, use for casting functionality.
Definition at line 44 of file Action.h.
References actionID.
Referenced by mlir::tracing::ActionImpl< PassExecutionAction >::classof().
getContextIRUnits()
virtual ArrayRef< IRUnit > mlir::tracing::Action::getContextIRUnits () const inline virtual
Return the set of IR units that are associated with this action.
Definition at line 55 of file Action.h.
References irUnits.
Referenced by mlir::tracing::ActionLogger::beforeExecute(), mlir::PassExecutionAction::getOp(), mlir::tracing::FileLineColLocBreakpointManager::match(), mlirDebuggerPrintContext(), and mlir::tracing::ActionActiveStack::print().
getTag()
virtual StringRef mlir::tracing::Action::getTag () const pure virtual
Return a string "tag" which intends to uniquely identify this type of action.
For example "pass-application" or "pattern-rewrite".
Implemented in mlir::tracing::ActionImpl< Derived >, mlir::tracing::ActionImpl< ApplyConversionAction >, mlir::tracing::ActionImpl< ApplyPatternAction >, and mlir::tracing::ActionImpl< PassExecutionAction >.
Referenced by mlir::tracing::ActionLogger::afterExecute(), mlir::tracing::ActionLogger::beforeExecute(), mlir::tracing::TagBreakpointManager::match(), mlir::tracing::DebugCounter::operator()(), and print().
print()
virtual void mlir::tracing::Action::print (raw_ostream & os) const inline virtual
Reimplemented in ApplyConversionAction, and mlir::ApplyPatternAction.
Definition at line 50 of file Action.h.
References getTag().
Referenced by mlir::tracing::ActionLogger::beforeExecute(), and mlir::tracing::ActionActiveStack::print().
Member Data Documentation
actionID
TypeID mlir::tracing::Action::actionID protected
The type of the derived action class, used for isa/dyn_cast.
Definition at line 62 of file Action.h.
Referenced by Action(), and getActionID().
irUnits
ArrayRef<IRUnit> mlir::tracing::Action::irUnits protected
Set of IR units (operations, regions, blocks, values) that are associated with this action.
Definition at line 66 of file Action.h.
Referenced by Action(), mlir::tracing::ActionImpl< PassExecutionAction >::ActionImpl(), ApplyConversionAction::ApplyConversionAction(), mlir::ApplyPatternAction::ApplyPatternAction(), getContextIRUnits(), mlir::PassExecutionAction::getOp(), and mlir::PassExecutionAction::PassExecutionAction().
The documentation for this class was generated from the following file:
include/mlir/IR/Action.h