MLIR: mlir::tblgen::SymbolInfoMap Class Reference
mlir::tblgen::SymbolInfoMap Class Reference
#include "mlir/TableGen/Pattern.h"
Classes
class SymbolInfo
Public Types
using BaseT = std::unordered_multimap<std::string, SymbolInfo>
using iterator = BaseT::iterator
using const_iterator = BaseT::const_iterator
Public Member Functions
SymbolInfoMap (ArrayRef< SMLoc > loc)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool bindOpArgument (DagNode node, StringRef symbol, const Operator &op, int argIndex, std::optional< int > variadicSubIndex=std::nullopt)
bool bindOpResult (StringRef symbol, const Operator &op)
bool bindValues (StringRef symbol, int numValues=1)
bool bindValue (StringRef symbol)
bool bindMultipleValues (StringRef symbol, int numValues)
bool bindAttr (StringRef symbol)
bool bindProp (StringRef symbol, const PropConstraint &constraint)
bool contains (StringRef symbol) const
const_iterator find (StringRef key) const
const_iterator findBoundSymbol (StringRef key, DagNode node, const Operator &op, int argIndex, std::optional< int > variadicSubIndex) const
const_iterator findBoundSymbol (StringRef key, const SymbolInfo &symbolInfo) const
std::pair< iterator, iterator > getRangeOfEqualElements (StringRef key)
int count (StringRef key) const
int getStaticValueCount (StringRef symbol) const
std::string getValueAndRangeUse (StringRef symbol, const char *fmt="{0}", const char *separator=", ") const
std::string getAllRangeUse (StringRef symbol, const char *fmt="{0}", const char *separator=", ") const
void assignUniqueAlternativeNames ()
Static Public Member Functions
static StringRef getValuePackName (StringRef symbol, int *index=nullptr)
Detailed Description
Definition at line 272 of file Pattern.h.
Member Typedef Documentation
BaseT
using mlir::tblgen::SymbolInfoMap::BaseT = std::unordered_multimap<std::string, SymbolInfo>
Definition at line 496 of file Pattern.h.
const_iterator
using mlir::tblgen::SymbolInfoMap::const_iterator = BaseT::const_iterator
Definition at line 504 of file Pattern.h.
iterator
using mlir::tblgen::SymbolInfoMap::iterator = BaseT::iterator
Definition at line 499 of file Pattern.h.
Constructor & Destructor Documentation
SymbolInfoMap()
mlir::tblgen::SymbolInfoMap::SymbolInfoMap (ArrayRef< SMLoc > loc) inline explicit
Definition at line 274 of file Pattern.h.
Member Function Documentation
assignUniqueAlternativeNames()
void SymbolInfoMap::assignUniqueAlternativeNames ()
Definition at line 646 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectSourcePatternBoundSymbols().
begin() [1/2]
iterator mlir::tblgen::SymbolInfoMap::begin () inline
Definition at line 500 of file Pattern.h.
begin() [2/2]
const_iterator mlir::tblgen::SymbolInfoMap::begin () const inline
Definition at line 505 of file Pattern.h.
bindAttr()
bool SymbolInfoMap::bindAttr (StringRef symbol)
Definition at line 551 of file Pattern.cpp.
References inserted().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
bindMultipleValues()
bool SymbolInfoMap::bindMultipleValues (StringRef symbol, int numValues)
Definition at line 544 of file Pattern.cpp.
References getValuePackName(), and inserted().
Referenced by bindValues().
bindOpArgument()
bool SymbolInfoMap::bindOpArgument (DagNode node, StringRef symbol, const Operator & op, int argIndex, std::optional< int > variadicSubIndex = std::nullopt)
Definition at line 490 of file Pattern.cpp.
References mlir::tblgen::Operator::getArg(), and getValuePackName().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
bindOpResult()
bool SymbolInfoMap::bindOpResult (StringRef symbol, const Operator & op)
Definition at line 525 of file Pattern.cpp.
References getValuePackName(), and inserted().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
bindProp()
bool SymbolInfoMap::bindProp (StringRef symbol, const PropConstraint & constraint)
Definition at line 556 of file Pattern.cpp.
References inserted().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
bindValue()
bool SymbolInfoMap::bindValue (StringRef symbol)
Definition at line 539 of file Pattern.cpp.
References inserted().
Referenced by bindValues(), and mlir::tblgen::Pattern::collectBoundSymbols().
bindValues()
bool SymbolInfoMap::bindValues (StringRef symbol, int numValues = 1)
Definition at line 532 of file Pattern.cpp.
References bindMultipleValues(), bindValue(), and getValuePackName().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
contains()
bool SymbolInfoMap::contains (StringRef symbol) const
Definition at line 563 of file Pattern.cpp.
References find().
count()
int SymbolInfoMap::count (StringRef key) const
Definition at line 601 of file Pattern.cpp.
References getValuePackName().
end() [1/2]
iterator mlir::tblgen::SymbolInfoMap::end () inline
Definition at line 501 of file Pattern.h.
end() [2/2]
const_iterator mlir::tblgen::SymbolInfoMap::end () const inline
Definition at line 506 of file Pattern.h.
find()
SymbolInfoMap::const_iterator SymbolInfoMap::find (StringRef key) const
Definition at line 567 of file Pattern.cpp.
References getValuePackName().
Referenced by contains(), and getStaticValueCount().
findBoundSymbol() [1/2]
SymbolInfoMap::const_iterator SymbolInfoMap::findBoundSymbol (StringRef key, const SymbolInfo & symbolInfo) const
Definition at line 582 of file Pattern.cpp.
References getValuePackName().
findBoundSymbol() [2/2]
SymbolInfoMap::const_iterator SymbolInfoMap::findBoundSymbol (StringRef key, DagNode node, const Operator & op, int argIndex, std::optional< int > variadicSubIndex) const
Definition at line 574 of file Pattern.cpp.
References findBoundSymbol().
Referenced by findBoundSymbol().
getAllRangeUse()
std::string SymbolInfoMap::getAllRangeUse (StringRef symbol, const char * fmt = "{0}", const char * separator = ", ") const
Definition at line 632 of file Pattern.cpp.
References getValuePackName().
getRangeOfEqualElements()
std::pair< SymbolInfoMap::iterator, SymbolInfoMap::iterator > SymbolInfoMap::getRangeOfEqualElements (StringRef key)
Definition at line 595 of file Pattern.cpp.
References getValuePackName().
getStaticValueCount()
int SymbolInfoMap::getStaticValueCount (StringRef symbol) const
Definition at line 606 of file Pattern.cpp.
References find(), and getValuePackName().
getValueAndRangeUse()
std::string SymbolInfoMap::getValueAndRangeUse (StringRef symbol, const char * fmt = "{0}", const char * separator = ", ") const
Definition at line 617 of file Pattern.cpp.
References getValuePackName().
getValuePackName()
StringRef SymbolInfoMap::getValuePackName (StringRef symbol, int * index = nullptr) static
Definition at line 241 of file Pattern.cpp.
Referenced by bindMultipleValues(), bindOpArgument(), bindOpResult(), bindValues(), count(), find(), findBoundSymbol(), getAllRangeUse(), getRangeOfEqualElements(), getStaticValueCount(), and getValueAndRangeUse().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp