MLIR: mlir::presburger::detail::GeneratingFunction Class Reference
mlir::presburger::detail::GeneratingFunction Class Reference
#include "mlir/Analysis/Presburger/GeneratingFunction.h"
Public Member Functions
GeneratingFunction (unsigned numParam, SmallVector< int > signs, std::vector< ParamPoint > nums, std::vector< std::vector< Point > > dens)
unsigned getNumParams () const
SmallVector< int > getSigns () const
std::vector< ParamPoint > getNumerators () const
std::vector< std::vector< Point > > getDenominators () const
GeneratingFunction operator+ (const GeneratingFunction &gf) const
llvm::raw_ostream & print (llvm::raw_ostream &os) const
Detailed Description
Definition at line 51 of file GeneratingFunction.h.
Constructor & Destructor Documentation
GeneratingFunction()
mlir::presburger::detail::GeneratingFunction::GeneratingFunction (unsigned numParam, SmallVector< int > signs, std::vector< ParamPoint > nums, std::vector< std::vector< Point > > dens) inline
Definition at line 53 of file GeneratingFunction.h.
Referenced by operator+().
Member Function Documentation
getDenominators()
std::vector< std::vector< Point > > mlir::presburger::detail::GeneratingFunction::getDenominators () const inline
Definition at line 71 of file GeneratingFunction.h.
Referenced by mlir::presburger::detail::computeNumTerms().
getNumerators()
std::vector< ParamPoint > mlir::presburger::detail::GeneratingFunction::getNumerators () const inline
Definition at line 69 of file GeneratingFunction.h.
Referenced by mlir::presburger::detail::computeNumTerms().
getNumParams()
unsigned mlir::presburger::detail::GeneratingFunction::getNumParams () const inline
Definition at line 65 of file GeneratingFunction.h.
Referenced by mlir::presburger::detail::computeNumTerms(), and operator+().
getSigns()
SmallVector< int > mlir::presburger::detail::GeneratingFunction::getSigns () const inline
Definition at line 67 of file GeneratingFunction.h.
Referenced by mlir::presburger::detail::computeNumTerms().
operator+()
GeneratingFunction mlir::presburger::detail::GeneratingFunction::operator+ (const GeneratingFunction & gf) const inline
Definition at line 75 of file GeneratingFunction.h.
References GeneratingFunction(), and getNumParams().
print()
llvm::raw_ostream & mlir::presburger::detail::GeneratingFunction::print (llvm::raw_ostream & os) const inline
Definition at line 91 of file GeneratingFunction.h.
The documentation for this class was generated from the following file:
include/mlir/Analysis/Presburger/GeneratingFunction.h