MLIR: mlir::ConstantIntDivisibility Class Reference
mlir::ConstantIntDivisibility Class Reference
Statically known divisibility information for an integer SSA value.
#include "mlir/Interfaces/InferIntDivisibilityOpInterface.h"
Public Member Functions
ConstantIntDivisibility ()=default
ConstantIntDivisibility (uint64_t udiv, uint64_t sdiv)
bool operator== (const ConstantIntDivisibility &other) const
uint64_t udiv () const
uint64_t sdiv () const
ConstantIntDivisibility getUnion (const ConstantIntDivisibility &other) const
Friends
raw_ostream & operator<< (raw_ostream &os, const ConstantIntDivisibility &div)
Detailed Description
Statically known divisibility information for an integer SSA value.
Tracks separate divisors for the unsigned and signed interpretations of the value so that subsequent analyses can use whichever is more precise.
Definition at line 26 of file InferIntDivisibilityOpInterface.h.
Constructor & Destructor Documentation
ConstantIntDivisibility() [1/2]
mlir::ConstantIntDivisibility::ConstantIntDivisibility () default
Referenced by getUnion(), operator<<, and operator==().
ConstantIntDivisibility() [2/2]
mlir::ConstantIntDivisibility::ConstantIntDivisibility (uint64_t udiv, uint64_t sdiv) inline
Definition at line 29 of file InferIntDivisibilityOpInterface.h.
References sdiv(), and udiv().
Member Function Documentation
getUnion()
ConstantIntDivisibility mlir::ConstantIntDivisibility::getUnion (const ConstantIntDivisibility & other) const inline
Definition at line 41 of file InferIntDivisibilityOpInterface.h.
References ConstantIntDivisibility(), sdiv(), and udiv().
Referenced by mlir::dataflow::IntegerDivisibilityAnalysis::visitNonControlFlowArguments().
operator==()
bool mlir::ConstantIntDivisibility::operator== (const ConstantIntDivisibility & other) const inline
Definition at line 32 of file InferIntDivisibilityOpInterface.h.
References ConstantIntDivisibility().
sdiv()
uint64_t mlir::ConstantIntDivisibility::sdiv () const inline
Definition at line 37 of file InferIntDivisibilityOpInterface.h.
Referenced by ConstantIntDivisibility(), getUnion(), and mlir::dataflow::IntegerDivisibilityAnalysis::visitNonControlFlowArguments().
udiv()
uint64_t mlir::ConstantIntDivisibility::udiv () const inline
Definition at line 36 of file InferIntDivisibilityOpInterface.h.
Referenced by ConstantIntDivisibility(), getUnion(), and mlir::dataflow::IntegerDivisibilityAnalysis::visitNonControlFlowArguments().
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & os, const ConstantIntDivisibility & div) friend
Definition at line 55 of file InferIntDivisibilityOpInterface.h.
References ConstantIntDivisibility(), and div.
The documentation for this class was generated from the following file:
include/mlir/Interfaces/InferIntDivisibilityOpInterface.h