MLIR: mlir::detail::DataLayoutEntryAttrStorage Class Reference
mlir::detail::DataLayoutEntryAttrStorage Class Reference
Public Types
using KeyTy = std::pair<DataLayoutEntryKey, Attribute>
Public Member Functions
DataLayoutEntryAttrStorage (DataLayoutEntryKey entryKey, Attribute value)
bool operator== (const KeyTy &other) const
Public Member Functions inherited from mlir::AttributeStorage
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static DataLayoutEntryAttrStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
DataLayoutEntryKey entryKey
Attribute value
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 163 of file DLTI.cpp.
Member Typedef Documentation
KeyTy
using mlir::detail::DataLayoutEntryAttrStorage::KeyTy = std::pair<DataLayoutEntryKey, Attribute>
Definition at line 165 of file DLTI.cpp.
Constructor & Destructor Documentation
DataLayoutEntryAttrStorage()
mlir::detail::DataLayoutEntryAttrStorage::DataLayoutEntryAttrStorage (DataLayoutEntryKey entryKey, Attribute value) inline
Definition at line 167 of file DLTI.cpp.
References entryKey, and value.
Referenced by construct().
Member Function Documentation
construct()
DataLayoutEntryAttrStorage * mlir::detail::DataLayoutEntryAttrStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 171 of file DLTI.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and DataLayoutEntryAttrStorage().
operator==()
bool mlir::detail::DataLayoutEntryAttrStorage::operator== (const KeyTy & other) const inline
Definition at line 176 of file DLTI.cpp.
References entryKey, and value.
Member Data Documentation
entryKey
DataLayoutEntryKey mlir::detail::DataLayoutEntryAttrStorage::entryKey
Definition at line 180 of file DLTI.cpp.
Referenced by DataLayoutEntryAttrStorage(), and operator==().
value
Attribute mlir::detail::DataLayoutEntryAttrStorage::value
Definition at line 181 of file DLTI.cpp.
Referenced by DataLayoutEntryAttrStorage(), and operator==().
The documentation for this class was generated from the following file:
lib/Dialect/DLTI/DLTI.cpp