MLIR: mlir::query::matcher::internal::MatcherDescriptor Class Reference
mlir::query::matcher::internal::MatcherDescriptor Class Reference abstract
#include "mlir/Query/Matcher/Marshallers.h"
Public Member Functions
virtual ~MatcherDescriptor ()=default
virtual VariantMatcher create (SourceRange nameRange, const llvm::ArrayRef< ParserValue > args, Diagnostics *error) const =0
virtual bool isVariadic () const =0
virtual unsigned getNumArgs () const =0
virtual void getArgKinds (unsigned argNo, std::vector< ArgKind > &argKinds) const =0
Detailed Description
Definition at line 104 of file Marshallers.h.
Constructor & Destructor Documentation
~MatcherDescriptor()
virtual mlir::query::matcher::internal::MatcherDescriptor::~MatcherDescriptor () virtual default
Member Function Documentation
create()
virtual VariantMatcher mlir::query::matcher::internal::MatcherDescriptor::create (SourceRange nameRange, const llvm::ArrayRef< ParserValue > args, Diagnostics * error) const pure virtual
Implemented in mlir::query::matcher::internal::FixedArgCountMatcherDescriptor, and mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor.
Referenced by mlir::query::matcher::RegistryManager::constructMatcher().
getArgKinds()
virtual void mlir::query::matcher::internal::MatcherDescriptor::getArgKinds (unsigned argNo, std::vector< ArgKind > & argKinds) const pure virtual
Implemented in mlir::query::matcher::internal::FixedArgCountMatcherDescriptor, and mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor.
Referenced by mlir::query::matcher::RegistryManager::getAcceptedCompletionTypes().
getNumArgs()
virtual unsigned mlir::query::matcher::internal::MatcherDescriptor::getNumArgs () const pure virtual
Implemented in mlir::query::matcher::internal::FixedArgCountMatcherDescriptor, and mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor.
isVariadic()
virtual bool mlir::query::matcher::internal::MatcherDescriptor::isVariadic () const pure virtual
Implemented in mlir::query::matcher::internal::FixedArgCountMatcherDescriptor, and mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor.
Referenced by mlir::query::matcher::RegistryManager::getAcceptedCompletionTypes().
The documentation for this class was generated from the following file:
include/mlir/Query/Matcher/Marshallers.h