MLIR: mlir::tblgen::InferredResultType Class Reference
mlir::tblgen::InferredResultType Class Reference
This class represents an inferred result type.
#include "mlir/TableGen/Operator.h"
Public Member Functions
InferredResultType (int index, std::string transformer)
bool isArg () const
Returns true if result type is inferred from an argument type.
int getIndex () const
Return the mapped argument or result index.
int getResultIndex () const
If the type is inferred from a result, return the result index.
StringRef getTransformer () const
Static Public Member Functions
static int mapResultIndex (int i)
static int unmapResultIndex (int i)
static bool isResultIndex (int i)
static bool isArgIndex (int i)
Detailed Description
This class represents an inferred result type.
The result type can be inferred from an argument or result type. If it is inferred from another result type, that type must be buildable or inferred from yet another type.
Definition at line 44 of file Operator.h.
Constructor & Destructor Documentation
InferredResultType()
mlir::tblgen::InferredResultType::InferredResultType (int index, std::string transformer) inline
Definition at line 46 of file Operator.h.
Member Function Documentation
getIndex()
int mlir::tblgen::InferredResultType::getIndex () const inline
Return the mapped argument or result index.
Definition at line 52 of file Operator.h.
getResultIndex()
int mlir::tblgen::InferredResultType::getResultIndex () const inline
If the type is inferred from a result, return the result index.
Definition at line 54 of file Operator.h.
References unmapResultIndex().
getTransformer()
StringRef mlir::tblgen::InferredResultType::getTransformer () const inline
Definition at line 64 of file Operator.h.
isArg()
bool mlir::tblgen::InferredResultType::isArg () const inline
Returns true if result type is inferred from an argument type.
Definition at line 50 of file Operator.h.
References isArgIndex().
isArgIndex()
static bool mlir::tblgen::InferredResultType::isArgIndex (int i) inline static
Definition at line 62 of file Operator.h.
Referenced by isArg().
isResultIndex()
static bool mlir::tblgen::InferredResultType::isResultIndex (int i) inline static
Definition at line 61 of file Operator.h.
mapResultIndex()
static int mlir::tblgen::InferredResultType::mapResultIndex (int i) inline static
Definition at line 59 of file Operator.h.
unmapResultIndex()
static int mlir::tblgen::InferredResultType::unmapResultIndex (int i) inline static
Definition at line 60 of file Operator.h.
Referenced by getResultIndex().
The documentation for this class was generated from the following file:
include/mlir/TableGen/Operator.h