MLIR: mlir::spirv::ArrayType Class Reference
mlir::spirv::ArrayType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
unsigned getNumElements () const
Type getElementType () const
unsigned getArrayStride () const
Returns the array stride in bytes.
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, std::optional< StorageClass > storage=std::nullopt)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, std::optional< StorageClass > storage=std::nullopt)
std::optional< int64_t > getSizeInBytes ()
Returns the array size in bytes.
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static ArrayType get (Type elementType, unsigned elementCount)
static ArrayType get (Type elementType, unsigned elementCount, unsigned stride)
Returns an array type with the given stride in bytes.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.array"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 130 of file SPIRVTypes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
Member Function Documentation
get() [1/2]
ArrayType ArrayType::get (Type elementType, unsigned elementCount) static
Definition at line 50 of file SPIRVTypes.cpp.
References mlir::get(), and mlir::Type::getContext().
Referenced by parseArrayType().
get() [2/2]
ArrayType ArrayType::get (Type elementType, unsigned elementCount, unsigned stride) static
Returns an array type with the given stride in bytes.
Definition at line 56 of file SPIRVTypes.cpp.
References mlir::get(), and mlir::Type::getContext().
getArrayStride()
unsigned ArrayType::getArrayStride () const
Returns the array stride in bytes.
0 means no stride decorated on this type.
Definition at line 66 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by convertArrayType(), getSizeInBytes(), print(), and mlir::spirv::Serializer::processTypeDecoration< spirv::ArrayType >().
getCapabilities()
void ArrayType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, std::optional< StorageClass > storage = std::nullopt)
Definition at line 73 of file SPIRVTypes.cpp.
References getElementType().
getElementType()
Type ArrayType::getElementType () const
Definition at line 64 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by convertArrayType(), getCapabilities(), getExtensions(), getSizeInBytes(), and print().
getExtensions()
void ArrayType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, std::optional< StorageClass > storage = std::nullopt)
Definition at line 68 of file SPIRVTypes.cpp.
References getElementType().
getNumElements()
unsigned ArrayType::getNumElements () const
Definition at line 62 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by convertArrayType(), getSizeInBytes(), and print().
getSizeInBytes()
std::optional< int64_t > ArrayType::getSizeInBytes ()
Returns the array size in bytes.
Since array type may have an explicit stride declaration (in bytes), we also include it in the calculation.
Definition at line 80 of file SPIRVTypes.cpp.
References getArrayStride(), getElementType(), and getNumElements().
Member Data Documentation
name
constexpr StringLiteral mlir::spirv::ArrayType::name = "spirv.array" static constexpr
Definition at line 135 of file SPIRVTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp