MLIR: mlir::tblgen::Constructor Class Reference
mlir::tblgen::Constructor Class Reference
#include "mlir/TableGen/Class.h"
Classes
class MemberInitializer
Initialization of a class field in a constructor.
Public Member Functions
template<typename NameT, typename... Args>
Constructor (NameT &&className, Properties properties, Args &&...args)
Create a constructor for a given class, with method properties, and parameters specified either as a list of a variadic pack.
template<typename NameT, typename ValueT>
void addMemberInitializer (NameT &&name, ValueT &&value)
Add member initializer to constructor initializing name with value.
void writeDeclTo (raw_indented_ostream &os) const override
Write the declaration of the constructor, and its definition if inline.
void writeDefTo (raw_indented_ostream &os, StringRef namePrefix) const override
Write the definition of the constructor if it is not inline.
Public Member Functions inherited from mlir::tblgen::Method
template<typename RetTypeT, typename NameT, typename... Args>
Method (RetTypeT &&retType, NameT &&name, Properties properties, Args &&...args)
Create a method with a return type, a name, method properties, and a some parameters.
Method (StringRef retType, StringRef name, Properties properties, std::initializer_list< MethodParameter > params)
Create a method with a return type, a name, method properties, and a list of parameters.
Method (Method &&)=default
Method & operator= (Method &&)=default
MethodBody & body ()
Get the method body.
void setDeprecated (std::optional< StringRef > message)
Sets or removes the deprecation message of the method.
bool isStatic () const
Returns true if this is a static method.
bool isPrivate () const
Returns true if this is a private method.
bool isInline () const
Returns true if this is an inline method.
bool isConstructor () const
Returns true if this is a constructor.
bool isConst () const
Returns true if this class method is const.
StringRef getName () const
Returns the name of this method.
StringRef getReturnType () const
Returns the return type of this method.
bool makesRedundant (const Method &other) const
Returns if this method makes the other method redundant.
void writeDeclTo (raw_indented_ostream &os) const override
Write the method declaration, including the definition if inline.
void writeDefTo (raw_indented_ostream &os, StringRef namePrefix) const override
Write the method definition. This is a no-op for inline methods.
template<typename ParamT>
void addTemplateParam (ParamT param)
Add a template parameter.
template<typename ContainerT>
void addTemplateParams (ContainerT &&container)
Add a list of template parameters.
Public Member Functions inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::Method >
ClassDeclarationBase ()
Public Member Functions inherited from mlir::tblgen::ClassDeclaration
virtual ~ClassDeclaration ()=default
ClassDeclaration (Kind kind)
Create a class declaration with a given kind.
Kind getKind () const
Get the class declaration kind.
Static Public Member Functions
static bool classof (const ClassDeclaration *other)
Return true if a method is a constructor.
Static Public Member Functions inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::Method >
static bool classof (const ClassDeclaration *other)
Additional Inherited Members
Public Types inherited from mlir::tblgen::Method
enum Properties {
None = 0x0 , Static = 0x1 , Constructor = 0x2 , Private = 0x4 ,
Declaration = 0x8 , Inline = 0x10 , ConstexprValue = 0x20 , Const = 0x40 ,
Constexpr = ConstexprValue | Inline , StaticDeclaration = Static | Declaration , StaticInline = Static | Inline , ConstInline = Const | Inline ,
ConstDeclaration = Const | Declaration
}
Properties (qualifiers) of class methods.
Public Types inherited from mlir::tblgen::ClassDeclarationBase< ClassDeclaration::Method >
using Base
Public Types inherited from mlir::tblgen::ClassDeclaration
enum Kind {
Method , UsingDeclaration , VisibilityDeclaration , Field ,
ExtraClassDeclaration
}
Kinds for LLVM-style RTTI.
Static Protected Member Functions inherited from mlir::tblgen::Method
static bool methodPropertiesAreCompatible (Properties properties)
Utility method to verify method properties correctness.
Protected Attributes inherited from mlir::tblgen::Method
Properties properties
A collection of method properties.
MethodSignature methodSignature
The signature of the method.
MethodBody methodBody
The body of the method, if it has one.
std::optional< std::string > deprecationMessage
Deprecation message if the method is deprecated.
Detailed Description
Definition at line 433 of file Class.h.
Constructor & Destructor Documentation
Constructor()
template<typename NameT, typename... Args> mlir::tblgen::Constructor::Constructor (NameT && className, Properties properties, Args &&... args) inline
Create a constructor for a given class, with method properties, and parameters specified either as a list of a variadic pack.
Definition at line 438 of file Class.h.
References mlir::tblgen::Method::Method(), and mlir::tblgen::Method::properties.
Member Function Documentation
addMemberInitializer()
template<typename NameT, typename ValueT> void mlir::tblgen::Constructor::addMemberInitializer (NameT && name, ValueT && value) inline
Add member initializer to constructor initializing name with value.
Definition at line 444 of file Class.h.
References mlir::tblgen::stringify().
classof()
bool mlir::tblgen::Constructor::classof (const ClassDeclaration * other) inline static
Return true if a method is a constructor.
Definition at line 457 of file Class.h.
writeDeclTo()
void Constructor::writeDeclTo (raw_indented_ostream & os) const override virtual
Write the declaration of the constructor, and its definition if inline.
Implements mlir::tblgen::ClassDeclaration.
Definition at line 198 of file Class.cpp.
References mlir::tblgen::Method::ConstexprValue, mlir::tblgen::Method::isInline(), mlir::tblgen::Method::methodBody, mlir::tblgen::Method::methodSignature, and mlir::tblgen::Method::properties.
writeDefTo()
void Constructor::writeDefTo (raw_indented_ostream & os, StringRef namePrefix) const override virtual
Write the definition of the constructor if it is not inline.
Reimplemented from mlir::tblgen::ClassDeclaration.
Definition at line 219 of file Class.cpp.
References mlir::tblgen::Method::Declaration, mlir::tblgen::Method::isInline(), mlir::tblgen::Method::methodBody, mlir::tblgen::Method::methodSignature, and mlir::tblgen::Method::properties.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp