MLIR: TuneExtension Class Reference
TuneExtension Class Reference
Public Member Functions
void init ()
Public Member Functions inherited from mlir::transform::TransformDialectExtension< TuneExtension >
void apply (MLIRContext *context, TransformDialect *transformDialect, ExtraDialects *...) const final
Extension application hook.
Public Member Functions inherited from mlir::DialectExtension< TuneExtension, TransformDialect, ExtraDialects... >
virtual void apply (MLIRContext *context, DialectsT *...dialects) const=0
Applies this extension to the given context and set of required dialects.
std::unique_ptr< DialectExtensionBase > clone () const final
Return a copy of this extension.
Public Member Functions inherited from mlir::DialectExtensionBase
virtual ~DialectExtensionBase ()
ArrayRef< StringRef > getRequiredDialects () const
Return the dialects that our required by this extension to be loaded before applying.
virtual void apply (MLIRContext *context, MutableArrayRef< Dialect * > dialects) const =0
Apply this extension to the given context and the required dialects.
Additional Inherited Members
Protected Types inherited from mlir::transform::TransformDialectExtension< TuneExtension >
using Base
Protected Member Functions inherited from mlir::transform::TransformDialectExtension< TuneExtension >
TransformDialectExtension (bool buildOnly=false)
Extension constructor.
void addCustomInitializationStep (Func &&func)
Registers a custom initialization step to be performed when the extension is applied to the dialect while loading.
void addDialectDataInitializer (Func &&func)
Registers the given function as one of the initializers for the dialect-owned data of the kind specified as template argument.
void init ()
Hook for derived classes to inject constructor behavior.
void registerTransformOps ()
Injects the operations into the Transform dialect.
void registerTypes ()
Injects the types into the Transform dialect.
void declareDependentDialect ()
Declares that this Transform dialect extension depends on the dialect provided as template parameter.
void declareGeneratedDialect ()
Declares that the transformations associated with the operations registered by this dialect extension may produce operations from the dialect provided as template parameter while processing payload IR that does not contain the operations from said dialect.
Protected Member Functions inherited from mlir::DialectExtension< TuneExtension, TransformDialect, ExtraDialects... >
DialectExtension ()
Protected Member Functions inherited from mlir::DialectExtensionBase
DialectExtensionBase (ArrayRef< StringRef > dialectNames)
Initialize the extension with a set of required dialects.
Detailed Description
Definition at line 17 of file TuneExtension.cpp.
Member Function Documentation
init()
void TuneExtension::init () inline
Definition at line 22 of file TuneExtension.cpp.
References init(), and mlir::transform::TransformDialectExtension< TuneExtension >::registerTransformOps().
Referenced by init().
The documentation for this class was generated from the following file:
lib/Dialect/Transform/TuneExtension/TuneExtension.cpp