MLIR: mlir::tracing::FileLineColLocBreakpointManager Class Reference
mlir::tracing::FileLineColLocBreakpointManager Class Reference
This breakpoint manager is responsible for matching FileLineColLocBreakpoint.
#include "mlir/Debug/BreakpointManagers/FileLineColLocBreakpointManager.h"
Public Member Functions
Breakpoint * match (const Action &action) const override
Try to match a Breakpoint to a given Action.
FileLineColLocBreakpoint * addBreakpoint (StringRef file, int64_t line, int64_t col=-1)
Public Member Functions inherited from mlir::tracing::BreakpointManagerBase< FileLineColLocBreakpointManager >
BreakpointManagerBase ()
Public Member Functions inherited from mlir::tracing::BreakpointManager
virtual ~BreakpointManager ()=default
TypeID getTypeID () const
TypeID for the subclass, used for casting purpose.
Additional Inherited Members
Static Public Member Functions inherited from mlir::tracing::BreakpointManagerBase< FileLineColLocBreakpointManager >
static bool classof (const BreakpointManager *breakpointManager)
Provide classof to allow casting between breakpoint manager types.
Protected Member Functions inherited from mlir::tracing::BreakpointManager
BreakpointManager (TypeID typeID)
Protected Attributes inherited from mlir::tracing::BreakpointManager
TypeID typeID
Detailed Description
This breakpoint manager is responsible for matching FileLineColLocBreakpoint.
It'll extract the location from the action context looking for a FileLineColLocation, and match it against the registered breakpoints.
Definition at line 60 of file FileLineColLocBreakpointManager.h.
Member Function Documentation
addBreakpoint()
FileLineColLocBreakpoint * mlir::tracing::FileLineColLocBreakpointManager::addBreakpoint (StringRef file, int64_t line, int64_t col = -1) inline
Definition at line 86 of file FileLineColLocBreakpointManager.h.
Referenced by mlirDebuggerAddFileLineColLocBreakpoint().
match()
Breakpoint * mlir::tracing::FileLineColLocBreakpointManager::match (const Action & action) const inline override virtual
Try to match a Breakpoint to a given Action.
If there is a match and the breakpoint is enabled, return the breakpoint. Otherwise, return nullptr.
Implements mlir::tracing::BreakpointManager.
Definition at line 63 of file FileLineColLocBreakpointManager.h.
References mlir::tracing::Action::getContextIRUnits(), and match().
Referenced by match().
The documentation for this class was generated from the following file:
include/mlir/Debug/BreakpointManagers/FileLineColLocBreakpointManager.h