MLIR: mlir::sparse_tensor::SparseTensorDescriptor Class Reference
mlir::sparse_tensor::SparseTensorDescriptor Class Reference
Uses ValueRange for immutable descriptors.
#include "Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.h"
Public Member Functions
SparseTensorDescriptor (SparseTensorType stt, ValueRange buffers)
Value getCrdMemRefOrView (OpBuilder &builder, Location loc, Level lvl) const
Public Member Functions inherited from mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >
FieldIndex getMemRefFieldIndex (SparseTensorFieldKind kind, std::optional< Level > lvl) const
unsigned getNumFields () const
Value getSpecifier () const
Getters: get the value for required field.
Value getSpecifierField (OpBuilder &builder, Location loc, StorageSpecifierKind kind, std::optional< Level > lvl) const
Value getLvlSize (OpBuilder &builder, Location loc, Level lvl) const
Value getPosMemRef (Level lvl) const
Value getValMemRef () const
Value getMemRefField (SparseTensorFieldKind kind, std::optional< Level > lvl) const
Value getPosMemSize (OpBuilder &builder, Location loc, Level lvl) const
Value getCrdMemSize (OpBuilder &builder, Location loc, Level lvl) const
Value getValMemSize (OpBuilder &builder, Location loc) const
Type getMemRefElementType (SparseTensorFieldKind kind, std::optional< Level > lvl) const
Value getField (FieldIndex fidx) const
ValueRange getMemRefFields () const
std::pair< FieldIndex, unsigned > getCrdMemRefIndexAndStride (Level lvl) const
Value getAOSMemRef () const
RankedTensorType getRankedTensorType () const
ValueRange getFields () const
StorageLayout getLayout () const
Additional Inherited Members
Protected Member Functions inherited from mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >
SparseTensorDescriptorImpl (SparseTensorType stt, ValueRange fields)
Protected Attributes inherited from mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >
SparseTensorType rType
ValueRange fields
StorageLayout layout
Detailed Description
Uses ValueRange for immutable descriptors.
Definition at line 156 of file SparseTensorDescriptor.h.
Constructor & Destructor Documentation
SparseTensorDescriptor()
mlir::sparse_tensor::SparseTensorDescriptor::SparseTensorDescriptor (SparseTensorType stt, ValueRange buffers) inline
Definition at line 158 of file SparseTensorDescriptor.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >::SparseTensorDescriptorImpl().
Member Function Documentation
getCrdMemRefOrView()
Value sparse_tensor::SparseTensorDescriptor::getCrdMemRefOrView (OpBuilder & builder, Location loc, Level lvl) const
Definition at line 108 of file SparseTensorDescriptor.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::sparse_tensor::CrdMemRef, mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >::getCrdMemSize(), mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >::getMemRefField(), and mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueRange >::rType.
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.h
lib/Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.cpp