MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface Class Reference
Python wrapper for InferShapedTypeOpInterface.
Classes
struct AppendResultsCallbackData
C-style user-data structure for type appending callback.
Public Member Functions
std::vector< PyShapedTypeComponents > inferReturnTypeComponents (std::optional< nb::sequence > operandList, std::optional< PyAttribute > attributes, void *properties, std::optional< std::vector< PyRegion > > regions, DefaultingPyMlirContext context, DefaultingPyLocation location)
Given the arguments required to build an operation, attempts to infer the shaped type components.
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyInferShapedTypeOpInterface >
PyConcreteOpInterface (nanobind::object object, DefaultingPyMlirContext context)
Constructs an interface instance from an object that is either an operation or a subclass of OpView.
bool isStatic ()
Returns true if this object was constructed from a subclass of OpView rather than from an operation instance.
nanobind::typed< nanobind::object, PyOperation > getOperationObject ()
Returns the operation instance from which this object was constructed.
nanobind::typed< nanobind::object, PyOpView > getOpView ()
Returns the opview of the operation instance from which this object was constructed.
const std::string & getOpName ()
Returns the canonical name of the operation this interface is constructed from.
Static Public Member Functions
static void appendResultsCallback (bool hasRank, intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute attribute, void *userData)
Appends the shaped type components provided as unpacked shape, element type, attribute to the user-data.
static void bindDerived (ClassTy &cls)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyInferShapedTypeOpInterface >
static void bind (nanobind::module_ &m)
Creates the Python bindings for this class in the given module.
static void bindDerived (ClassTy &cls)
Hook for derived classes to add class-specific bindings.
Static Public Attributes
static constexpr const char * pyClassName = "InferShapedTypeOpInterface"
static constexpr GetTypeIDFunctionTy getInterfaceID
Additional Inherited Members
Protected Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyInferShapedTypeOpInterface >
using ClassTy
using GetTypeIDFunctionTy
Detailed Description
Python wrapper for InferShapedTypeOpInterface.
This interface has only static methods.
Definition at line 268 of file IRInterfaces.cpp.
Member Function Documentation
appendResultsCallback()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::appendResultsCallback (bool hasRank, intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute attribute, void * userData) inline static
Appends the shaped type components provided as unpacked shape, element type, attribute to the user-data.
Definition at line 285 of file IRInterfaces.cpp.
Referenced by inferReturnTypeComponents().
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::bindDerived (ClassTy & cls) inline static
Definition at line 331 of file IRInterfaces.cpp.
References inferReturnTypeComponents(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::inferReturnTypeComponentsDoc.
inferReturnTypeComponents()
std::vector< PyShapedTypeComponents > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::inferReturnTypeComponents (std::optional< nb::sequence > operandList, std::optional< PyAttribute > attributes, void * properties, std::optional< std::vector< PyRegion > > regions, DefaultingPyMlirContext context, DefaultingPyLocation location) inline
Given the arguments required to build an operation, attempts to infer the shaped type components.
Throws value_error on failure.
Definition at line 303 of file IRInterfaces.cpp.
References appendResultsCallback(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyInferShapedTypeOpInterface >::getOpName(), mlirAttributeGetNull(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirLogicalResultIsFailure(), mlirStringRefCreate(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation::resolve(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyMlirContext::resolve(), and result.
Referenced by bindDerived().
Member Data Documentation
getInterfaceID
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::getInterfaceID static constexpr
Initial value:
=
      &mlirInferShapedTypeOpInterfaceTypeID
Definition at line 275 of file IRInterfaces.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::pyClassName = "InferShapedTypeOpInterface" static constexpr
Definition at line 274 of file IRInterfaces.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRInterfaces.cpp