MLIR: mlir::python::DefaultingPyLocation Class Reference
mlir::python::DefaultingPyLocation Class Reference
Used in function arguments when None should resolve to the current context manager set instance.
#include "Bindings/Python/IRModule.h"
Public Member Functions
operator MlirLocation () const
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting (ReferrentTy &referrent)
Public Member Functions inherited from mlir::python::Defaulting< DefaultingPyLocation, PyLocation >
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
ReferrentTy * get () const
ReferrentTy * operator-> ()
Static Public Member Functions
static PyLocation & resolve ()
Static Public Attributes
static constexpr const char kTypeDescription [] = "Location"
Additional Inherited Members
Public Types inherited from mlir::python::Defaulting< DefaultingPyLocation, PyLocation >
using ReferrentTy
Detailed Description
Used in function arguments when None should resolve to the current context manager set instance.
Definition at line 498 of file IRModule.h.
Member Function Documentation
Defaulting() [1/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting () default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting() [2/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting (ReferrentTy & referrent) inline
Definition at line 59 of file NanobindUtils.h.
operator MlirLocation()
mlir::python::DefaultingPyLocation::operator MlirLocation () const inline
Definition at line 505 of file IRModule.h.
References mlir::python::Defaulting< DefaultingPyLocation, PyLocation >::get().
resolve()
PyLocation & DefaultingPyLocation::resolve () static
Definition at line 951 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::getDefaultLocation().
Referenced by createBlock(), mlir::python::PyInferShapedTypeOpInterface::inferReturnTypeComponents(), and mlir::python::PyInferTypeOpInterface::inferReturnTypes().
Member Data Documentation
kTypeDescription
const char mlir::python::DefaultingPyLocation::kTypeDescription[] = "Location" static constexpr
Definition at line 502 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp