MLIR: mlir::AttrTypeImmediateSubElementWalker Class Reference
mlir::AttrTypeImmediateSubElementWalker Class Reference
AttrTypeSubElementHandler.
#include "mlir/IR/AttrTypeSubElements.h"
Public Member Functions
AttrTypeImmediateSubElementWalker (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn)
void walk (Attribute element)
Walk an attribute.
void walk (Type element)
Walk a type.
template<typename RangeT >
void walkRange (RangeT &&elements)
Walk a range of attributes or types.
Detailed Description
AttrTypeSubElementHandler.
This class is used by AttrTypeSubElementHandler instances to walking sub attributes and types.
Definition at line 332 of file AttrTypeSubElements.h.
Constructor & Destructor Documentation
AttrTypeImmediateSubElementWalker()
mlir::AttrTypeImmediateSubElementWalker::AttrTypeImmediateSubElementWalker (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn) inline
Definition at line 334 of file AttrTypeSubElements.h.
Member Function Documentation
walk() [1/2]
void AttrTypeImmediateSubElementWalker::walk (Attribute element)
Walk an attribute.
Definition at line 320 of file AttrTypeSubElements.cpp.
Referenced by mlir::AttrTypeSubElementHandler< Location >::walk(), mlir::AttrTypeSubElementHandler< NamedAttribute >::walk(), mlir::AttrTypeSubElementHandler< T, std::enable_if_t< std::is_base_of_v< Attribute, T >||std::is_base_of_v< Type, T > > >::walk(), and walkRange().
walk() [2/2]
void AttrTypeImmediateSubElementWalker::walk (Type element)
Walk a type.
Definition at line 325 of file AttrTypeSubElements.cpp.
walkRange()
template<typename RangeT > void mlir::AttrTypeImmediateSubElementWalker::walkRange (RangeT && elements) inline
Walk a range of attributes or types.
Definition at line 344 of file AttrTypeSubElements.h.
References walk().
Referenced by mlir::AttrTypeSubElementHandler< LLVM::detail::LLVMStructTypeStorage::Key >::walk(), and mlir::AttrTypeSubElementHandler< TypeRange >::walk().
The documentation for this class was generated from the following files:
include/mlir/IR/AttrTypeSubElements.h
lib/IR/AttrTypeSubElements.cpp