MLIR: mlir::transform::ParamProducerTransformOpTrait< OpTy > Class Template Reference
mlir::transform::ParamProducerTransformOpTrait< OpTy > Class Template Reference
Trait implementing the MemoryEffectsOpInterface for operations that produce transform dialect parameters.
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
Public Member Functions
void getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
Populates effects with effect instances described in the trait documentation.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Checks that the op matches the expectation of this trait, i.e., that it implements the MemoryEffectsOpInterface and only produces parameter-typed results.
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< OpTy, ParamProducerTransformOpTrait >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename OpTy>
class mlir::transform::ParamProducerTransformOpTrait< OpTy >
Trait implementing the MemoryEffectsOpInterface for operations that produce transform dialect parameters.
It marks all op results of TransformHandleTypeInterface as produced by the op, all operands as only read by the op and, if at least one of the operand is a handle to payload ops, the entire payload as potentially read. The op must only produce parameter-typed results.
Definition at line 1376 of file TransformInterfaces.h.
Member Function Documentation
getEffects()
template<typename OpTy > void mlir::transform::ParamProducerTransformOpTrait< OpTy >::getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > & effects) inline
Populates effects with effect instances described in the trait documentation.
Definition at line 1381 of file TransformInterfaces.h.
References mlir::OpTrait::TraitBase< OpTy, ParamProducerTransformOpTrait >::getOperation(), and mlir::transform::detail::getParamProducerTransformOpTraitEffects().
verifyTrait()
template<typename OpTy > static LogicalResult mlir::transform::ParamProducerTransformOpTrait< OpTy >::verifyTrait (Operation * op) inline static
Checks that the op matches the expectation of this trait, i.e., that it implements the MemoryEffectsOpInterface and only produces parameter-typed results.
Definition at line 1389 of file TransformInterfaces.h.
References mlir::transform::detail::verifyParamProducerTransformOpTrait().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h