MLIR: mlir::pdll::ods::Attribute Class Reference
mlir::pdll::ods::Attribute Class Reference
This class provides an ODS representation of a specific operation attribute.
#include "mlir/Tools/PDLL/ODS/Operation.h"
Public Member Functions
StringRef getName () const
Return the name of this operand.
bool isOptional () const
Return true if this attribute is optional.
const AttributeConstraint & getConstraint () const
Return the constraint of this attribute.
Friends
class Operation
Allow access to the private constructor.
Detailed Description
This class provides an ODS representation of a specific operation attribute.
This includes the name, optionality, and more.
Definition at line 39 of file Operation.h.
Member Function Documentation
getConstraint()
const AttributeConstraint & mlir::pdll::ods::Attribute::getConstraint () const inline
Return the constraint of this attribute.
Definition at line 48 of file Operation.h.
Referenced by mlir::pdll::ods::Context::print().
getName()
StringRef mlir::pdll::ods::Attribute::getName () const inline
Return the name of this operand.
Definition at line 42 of file Operation.h.
Referenced by mlir::pdll::ods::Context::print().
isOptional()
bool Attribute::isOptional () const inline
Return true if this attribute is optional.
Definition at line 45 of file Operation.h.
Referenced by mlir::pdll::ods::Context::print().
Friends And Related Symbol Documentation
Operation
friend class Operation friend
Allow access to the private constructor.
Definition at line 65 of file Operation.h.
References Operation.
Referenced by Operation.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/ODS/Operation.h
lib/TableGen/Attribute.cpp