MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType Class Reference
Wrapper around the generic MlirType.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::typed< nanobind::object, PyType > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Detailed Description
Wrapper around the generic MlirType.
The lifetime of a type is bound by the PyContext that created it.
Definition at line 891 of file IRCore.h.
Constructor & Destructor Documentation
PyType()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType (PyMlirContextRef contextRef, MlirType type) inline
Definition at line 893 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMBaseType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::TDMGatherBaseType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nvgpu::TensorMapDescriptorType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyComplexType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyShapedType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTupleType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::QuantizedType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::ParamType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::castFrom(), getCapsule(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType().
Member Function Documentation
createFromCapsule()
PyType mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::createFromCapsule (nanobind::object capsule) static
Creates a PyType from the MlirType wrapped by a capsule.
Note that PyType instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirType is taken by calling this function.
Definition at line 1927 of file IRCore.cpp.
References mlirPythonTypeToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirType mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::get () const inline
Definition at line 897 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRankedTensorType::bindDerived(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeAttribute::bindDerived().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
Definition at line 1923 of file IRCore.cpp.
References mlirTypeEqual(), and PyType().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
maybeDownCast()
nb::typed< nb::object, PyType > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::maybeDownCast ()
Definition at line 1935 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::convertType(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirType()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::operator MlirType () const inline
Definition at line 896 of file IRCore.h.
operator==()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::operator== (const PyType & other) const
Definition at line 1919 of file IRCore.cpp.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp