MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList Class Reference
A list of operation operands.
#include "mlir/Bindings/Python/IRCore.h"
Public Types
using SliceableT = Sliceable<PyOpOperandList, PyValue>
Public Member Functions
PyOpOperandList (PyOperationRef operation, intptr_t startIndex=0, intptr_t length=-1, intptr_t step=1)
void dunderSetItem (intptr_t index, PyValue value)
Public Member Functions inherited from mlir::Sliceable< PyOpOperandList, PyValue >
Sliceable (intptr_t startIndex, intptr_t length, intptr_t step)
PyValue getElement (intptr_t index)
Returns the index-th element in the slice, supports negative indices.
intptr_t size ()
Returns the size of slice.
std::vector< PyValue > dunderAdd (PyOpOperandList &other)
Returns a new vector (mapped to Python list) containing elements from two slices.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::Sliceable< PyOpOperandList, PyValue >
static void bind (nanobind::module_ &m)
Binds the indexing and length methods in the Python class.
static void bindDerived (ClassTy &)
Hook for derived classes willing to bind more methods.
Static Public Attributes
static constexpr const char * pyClassName = "OpOperandList"
static constexpr std::array< const char *, 1 > typeParams = {"_T"}
Friends
class Sliceable< PyOpOperandList, PyValue >
Give the parent CRTP class access to hook implementations below.
Additional Inherited Members
Public Attributes inherited from mlir::Sliceable< PyOpOperandList, PyValue >
intptr_t startIndex
intptr_t length
intptr_t step
Protected Types inherited from mlir::Sliceable< PyOpOperandList, PyValue >
using ClassTy
Protected Member Functions inherited from mlir::Sliceable< PyOpOperandList, PyValue >
intptr_t wrapIndex (intptr_t index)
Transforms index into a legal value to access the underlying sequence.
intptr_t linearizeIndex (intptr_t index)
Computes the linear index given the current slice properties.
nanobind::typed< nanobind::object, PyValue > getItem (intptr_t index)
Returns the element at the given slice index.
nanobind::object getItemSlice (PyObject *slice)
Returns a new instance of the pseudo-container restricted to the given slice.
Static Protected Attributes inherited from mlir::Sliceable< PyOpOperandList, PyValue >
static constexpr std::array< const char *, 0 > typeParams
Type parameter names for generic classes.
Detailed Description
A list of operation operands.
Internally, these are stored as consecutive elements, random access is cheap. The (returned) operand list is associated with the operation whose operands these are, and thus extends the lifetime of this operation.
Definition at line 1805 of file IRCore.h.
Member Typedef Documentation
SliceableT
using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::SliceableT = Sliceable<PyOpOperandList, PyValue>
Definition at line 1810 of file IRCore.h.
Constructor & Destructor Documentation
PyOpOperandList()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::PyOpOperandList (PyOperationRef operation, intptr_t startIndex = 0, intptr_t length = -1, intptr_t step = 1)
Definition at line 2238 of file IRCore.cpp.
References mlir::Sliceable< PyOpOperandList, PyValue >::length, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList::PyBlockArgumentList(), mlir::Sliceable< PyOpOperandList, PyValue >::startIndex, and mlir::Sliceable< PyOpOperandList, PyValue >::step.
Referenced by Sliceable< PyOpOperandList, PyValue >.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::bindDerived (ClassTy & c) static
Definition at line 2251 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::get(), mlirOperationSetOperand(), and mlir::Sliceable< PyOpOperandList, PyValue >::wrapIndex().
Referenced by Sliceable< PyOpOperandList, PyValue >.
dunderSetItem()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::dunderSetItem (intptr_t index, PyValue value)
Definition at line 2246 of file IRCore.cpp.
References mlir::get(), mlir::Sliceable< PyOpOperandList, PyValue >::length, mlirOperationGetNumOperands(), and mlir::Sliceable< PyOpOperandList, PyValue >::step.
Friends And Related Symbol Documentation
Sliceable< PyOpOperandList, PyValue >
friend class Sliceable< PyOpOperandList, PyValue > friend
Give the parent CRTP class access to hook implementations below.
Definition at line 1817 of file IRCore.h.
References bindDerived(), mlir::Sliceable< PyOpOperandList, PyValue >::length, PyOpOperandList(), mlir::Sliceable< PyOpOperandList, PyValue >::Sliceable(), mlir::Sliceable< PyOpOperandList, PyValue >::startIndex, and mlir::Sliceable< PyOpOperandList, PyValue >::step.
Member Data Documentation
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::pyClassName = "OpOperandList" static constexpr
Definition at line 1808 of file IRCore.h.
typeParams
std::array<const char *, 1> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::typeParams = {"_T"} static constexpr
Definition at line 1809 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp