MLIR: DynamicMemRefIterator< T > Class Template Reference
DynamicMemRefIterator< T > Class Template Reference
Iterate over all elements in a dynamic memref.
#include "mlir/ExecutionEngine/CRunnerUtils.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = T
using difference_type = std::ptrdiff_t
using pointer = T *
using reference = T &
Public Member Functions
DynamicMemRefIterator (DynamicMemRefType< T > &descriptor, int64_t offset=0)
DynamicMemRefIterator< T > & operator++ ()
reference operator* ()
pointer operator-> ()
const std::vector< int64_t > & getIndices ()
bool operator== (const DynamicMemRefIterator &other) const
bool operator!= (const DynamicMemRefIterator &other) const
Detailed Description
template<typename T>
class DynamicMemRefIterator< T >
Iterate over all elements in a dynamic memref.
Definition at line 392 of file CRunnerUtils.h.
Member Typedef Documentation
difference_type
template<typename T> using DynamicMemRefIterator< T >::difference_type = std::ptrdiff_t
Definition at line 396 of file CRunnerUtils.h.
iterator_category
template<typename T> using DynamicMemRefIterator< T >::iterator_category = std::forward_iterator_tag
Definition at line 394 of file CRunnerUtils.h.
pointer
template<typename T> using DynamicMemRefIterator< T >::pointer = T *
Definition at line 397 of file CRunnerUtils.h.
reference
template<typename T> using DynamicMemRefIterator< T >::reference = T &
Definition at line 398 of file CRunnerUtils.h.
value_type
template<typename T> using DynamicMemRefIterator< T >::value_type = T
Definition at line 395 of file CRunnerUtils.h.
Constructor & Destructor Documentation
DynamicMemRefIterator()
template<typename T> DynamicMemRefIterator< T >::DynamicMemRefIterator (DynamicMemRefType< T > & descriptor, int64_t offset = 0) inline
Definition at line 400 of file CRunnerUtils.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
getIndices()
template<typename T> const std::vector< int64_t > & DynamicMemRefIterator< T >::getIndices () inline
Definition at line 432 of file CRunnerUtils.h.
operator!=()
template<typename T> bool DynamicMemRefIterator< T >::operator!= (const DynamicMemRefIterator< T > & other) const inline
Definition at line 438 of file CRunnerUtils.h.
References DynamicMemRefIterator().
operator*()
template<typename T> reference DynamicMemRefIterator< T >::operator* () inline
Definition at line 429 of file CRunnerUtils.h.
operator++()
template<typename T> DynamicMemRefIterator< T > & DynamicMemRefIterator< T >::operator++ () inline
Definition at line 405 of file CRunnerUtils.h.
References DynamicMemRefIterator().
operator->()
template<typename T> pointer DynamicMemRefIterator< T >::operator-> () inline
Definition at line 430 of file CRunnerUtils.h.
operator==()
template<typename T> bool DynamicMemRefIterator< T >::operator== (const DynamicMemRefIterator< T > & other) const inline
Definition at line 434 of file CRunnerUtils.h.
References DynamicMemRefIterator().
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/CRunnerUtils.h