MLIR: mlir::detail::DenseArrayAttrImpl< T > Class Template Reference
mlir::detail::DenseArrayAttrImpl< T > Class Template Reference
Base class for DenseArrayAttr that is instantiated and specialized for each supported element type below.
#include "mlir/IR/BuiltinAttributes.h"
Public Member Functions
operator ArrayRef< T > () const
Implicit conversion to ArrayRef<T>.
ArrayRef< T > asArrayRef () const
T operator[] (std::size_t index) const
Random access to elements.
void print (AsmPrinter &printer) const
Print the short form [42, 100, -1] without any type prefix.
void print (raw_ostream &os) const
void printWithoutBraces (raw_ostream &os) const
Print the short form 42, 100, -1 without any braces or type prefix.
Static Public Member Functions
static DenseArrayAttrImpl get (MLIRContext *context, ArrayRef< T > content)
Builder from ArrayRef<T>.
static Attribute parse (AsmParser &parser, Type type)
Parse the short form [42, 100, -1] without any type prefix.
static Attribute parseWithoutBraces (AsmParser &parser, Type type)
Parse the short form 42, 100, -1 without any type prefix or braces.
static bool classof (Attribute attr)
Support for isa<>/cast<>.
Detailed Description
template<typename T>
class mlir::detail::DenseArrayAttrImpl< T >
Base class for DenseArrayAttr that is instantiated and specialized for each supported element type below.
Definition at line 725 of file BuiltinAttributes.h.
Member Function Documentation
asArrayRef()
template<typename T > ArrayRef<T> mlir::detail::DenseArrayAttrImpl< T >::asArrayRef () const inline
Definition at line 731 of file BuiltinAttributes.h.
Referenced by mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::begin(), mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::end(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::detail::DenseArrayAttrImpl< T >::operator[](), parseInsertExtractValueElementType(), printSwitchCases(), mlir::transform::printTransformMatchDims(), mlir::LLVM::ModuleTranslation::setBranchWeightsMetadata(), and verifyDeviceTypeAndSegmentCountMatch().
classof()
template<typename T > bool DenseArrayAttrImpl::classof (Attribute attr) static
Support for isa<>/cast<>.
Definition at line 870 of file BuiltinAttributes.cpp.
get()
template<typename T > DenseArrayAttrImpl< T > DenseArrayAttrImpl::get (MLIRContext * context, ArrayRef< T > content) static
Builder from ArrayRef<T>.
Builds a DenseArrayAttr<T> from an ArrayRef<T>.
Definition at line 860 of file BuiltinAttributes.cpp.
References mlir::get(), and getElementType().
Referenced by mlir::convertToAttribute(), fromArrayOfVector(), mlir::mesh::MeshSharding::get(), mlir::Builder::getDenseBoolArrayAttr(), mlir::Builder::getDenseF32ArrayAttr(), mlir::Builder::getDenseF64ArrayAttr(), mlir::Builder::getDenseI16ArrayAttr(), mlir::Builder::getDenseI64ArrayAttr(), mlir::Builder::getDenseI8ArrayAttr(), makeDenseBoolArrayAttr(), mlirDenseBoolArrayGet(), mlirDenseF32ArrayGet(), mlirDenseF64ArrayGet(), mlirDenseI16ArrayGet(), mlirDenseI64ArrayGet(), mlirDenseI8ArrayGet(), mlir::parseDimensionList(), mlir::mesh::targetShardingInMoveLastAxis(), mlir::mesh::targetShardingInSplitLastAxis(), and mlir::mesh::targetShardingInUnsplitLastAxis().
operator ArrayRef< T >()
template<typename T > DenseArrayAttrImpl::operator ArrayRef< T >
Implicit conversion to ArrayRef<T>.
Conversion from DenseArrayAttr<T> to ArrayRef<T>.
Definition at line 851 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::getRawData().
operator[]()
template<typename T > T mlir::detail::DenseArrayAttrImpl< T >::operator[] (std::size_t index) const inline
Random access to elements.
Definition at line 734 of file BuiltinAttributes.h.
References mlir::detail::DenseArrayAttrImpl< T >::asArrayRef().
parse()
template<typename T > Attribute DenseArrayAttrImpl::parse (AsmParser & parser, Type type) static
Parse the short form [42, 100, -1] without any type prefix.
Parse a DenseArrayAttr: [ 1, 2, 3 ]
Definition at line 837 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), mlir::AsmParser::getContext(), mlir::AsmParser::parseLSquare(), mlir::AsmParser::parseOptionalRSquare(), and mlir::AsmParser::parseRSquare().
Referenced by parseDenseI64ArrayAttr().
parseWithoutBraces()
template<typename T > Attribute DenseArrayAttrImpl::parseWithoutBraces (AsmParser & parser, Type type) static
Parse the short form 42, 100, -1 without any type prefix or braces.
Parse a DenseArrayAttr without the braces: 1, 2, 3
Definition at line 821 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), mlir::AsmParser::getContext(), and mlir::AsmParser::parseCommaSeparatedList().
print() [1/2]
template<typename T > void DenseArrayAttrImpl::print (AsmPrinter & printer) const
Print the short form [42, 100, -1] without any type prefix.
Definition at line 801 of file BuiltinAttributes.cpp.
References mlir::AsmPrinter::getStream(), and mlir::Attribute::print().
print() [2/2]
template<typename T > void DenseArrayAttrImpl::print (raw_ostream & os) const
Definition at line 813 of file BuiltinAttributes.cpp.
printWithoutBraces()
template<typename T > void DenseArrayAttrImpl::printWithoutBraces (raw_ostream & os) const
Print the short form 42, 100, -1 without any braces or type prefix.
Definition at line 806 of file BuiltinAttributes.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinAttributes.h
lib/IR/BuiltinAttributes.cpp