MLIR: PyOpResult Class Reference
PyOpResult Class Reference
Python wrapper for MlirOpResult.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirValueIsAOpResult
static constexpr const char * pyClassName = "OpResult"
Detailed Description
Python wrapper for MlirOpResult.
Definition at line 1718 of file IRCore.cpp.
Member Function Documentation
bindDerived()
static void PyOpResult::bindDerived (ClassTy & c) inline static
Definition at line 1724 of file IRCore.cpp.
References mlir::get(), mlirOperationEqual(), mlirOpResultGetOwner(), and mlirOpResultGetResultNumber().
Member Data Documentation
isaFunction
constexpr IsAFunctionTy PyOpResult::isaFunction = mlirValueIsAOpResult static constexpr
Definition at line 1720 of file IRCore.cpp.
pyClassName
constexpr const char* PyOpResult::pyClassName = "OpResult" static constexpr
Definition at line 1721 of file IRCore.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRCore.cpp