MLIR: mlir::DebugActionManager Class Reference
mlir::DebugActionManager Class Reference
This class represents manages debug actions, and orchestrates the communication between action queries and action handlers.
#include "mlir/Support/DebugAction.h"
Classes
class GenericHandler
This class represents a generic action handler.
class HandlerBase
This class represents the base class of a debug action handler.
Public Member Functions
void registerActionHandler (std::unique_ptr< HandlerBase > handler)
Register the given action handler with the manager.
template<typename T >
void registerActionHandler ()
template<typename ActionType , typename... Args>
bool shouldExecute (Args &&... args)
Returns true if the given action type should be executed, false otherwise.
Detailed Description
This class represents manages debug actions, and orchestrates the communication between action queries and action handlers.
An action handler is either an action specific handler, i.e. a derived class of MyActionType::Handler, or a generic handler, i.e. a derived class of DebugActionManager::GenericHandler. For more details on action specific handlers, see the definition of DebugAction::Handler below. For more details on generic handlers, see DebugActionManager::GenericHandler below.
Definition at line 42 of file DebugAction.h.
Member Function Documentation
registerActionHandler() [1/2]
void mlir::DebugActionManager::registerActionHandler (std::unique_ptr< HandlerBase > handler) inline
Register the given action handler with the manager.
Definition at line 91 of file DebugAction.h.
Referenced by processBuffer().
registerActionHandler() [2/2]
template<typename T > void mlir::DebugActionManager::registerActionHandler () inline
Definition at line 98 of file DebugAction.h.
shouldExecute()
template<typename ActionType , typename... Args> bool mlir::DebugActionManager::shouldExecute (Args &&... args) inline
Returns true if the given action type should be executed, false otherwise.
Args are a set of parameters used by handlers of ActionType to determine if the action should be executed.
Definition at line 110 of file DebugAction.h.
References mlir::failure(), and mlir::succeeded().
The documentation for this class was generated from the following file:
include/mlir/Support/DebugAction.h