MLIR: mlir::query::matcher::internal::Parser::CodeTokenizer Class Reference
mlir::query::matcher::internal::Parser::CodeTokenizer Class Reference
Public Member Functions
CodeTokenizer (llvm::StringRef matcherCode, Diagnostics *error)
CodeTokenizer (llvm::StringRef matcherCode, Diagnostics *error, unsigned codeCompletionOffset)
const TokenInfo & peekNextToken () const
TokenInfo consumeNextToken ()
TokenInfo skipNewlines ()
TokenInfo consumeNextTokenIgnoreNewlines ()
TokenKind nextTokenKind () const
Detailed Description
Definition at line 40 of file Parser.cpp.
Constructor & Destructor Documentation
CodeTokenizer() [1/2]
mlir::query::matcher::internal::Parser::CodeTokenizer::CodeTokenizer (llvm::StringRef matcherCode, Diagnostics * error) inline explicit
Definition at line 43 of file Parser.cpp.
CodeTokenizer() [2/2]
mlir::query::matcher::internal::Parser::CodeTokenizer::CodeTokenizer (llvm::StringRef matcherCode, Diagnostics * error, unsigned codeCompletionOffset) inline
Definition at line 49 of file Parser.cpp.
Member Function Documentation
consumeNextToken()
TokenInfo mlir::query::matcher::internal::Parser::CodeTokenizer::consumeNextToken () inline
Definition at line 60 of file Parser.cpp.
Referenced by consumeNextTokenIgnoreNewlines().
consumeNextTokenIgnoreNewlines()
TokenInfo mlir::query::matcher::internal::Parser::CodeTokenizer::consumeNextTokenIgnoreNewlines () inline
Definition at line 74 of file Parser.cpp.
References consumeNextToken(), mlir::query::matcher::internal::Parser::Eof, mlir::query::matcher::internal::Parser::TokenInfo::kind, and skipNewlines().
nextTokenKind()
TokenKind mlir::query::matcher::internal::Parser::CodeTokenizer::nextTokenKind () const inline
Definition at line 80 of file Parser.cpp.
References mlir::query::matcher::internal::Parser::TokenInfo::kind.
peekNextToken()
const TokenInfo& mlir::query::matcher::internal::Parser::CodeTokenizer::peekNextToken () const inline
Definition at line 57 of file Parser.cpp.
Referenced by mlir::query::matcher::internal::Parser::parseExpression().
skipNewlines()
TokenInfo mlir::query::matcher::internal::Parser::CodeTokenizer::skipNewlines () inline
Definition at line 67 of file Parser.cpp.
References mlir::query::matcher::internal::Parser::TokenInfo::kind, and mlir::query::matcher::internal::Parser::NewLine.
Referenced by consumeNextTokenIgnoreNewlines().
The documentation for this class was generated from the following file:
lib/Query/Matcher/Parser.cpp