MLIR: mlir::Region::OpIterator Class Reference
mlir::Region::OpIterator Class Reference final
This class provides iteration over the held operations of blocks directly within a region.
#include "mlir/IR/Region.h"
Public Member Functions
OpIterator (Region *region, bool end=false)
Initialize OpIterator for a region, specify end to return the iterator to last operation.
OpIterator & operator++ ()
Operation * operator-> () const
Operation & operator* () const
bool operator== (const OpIterator &rhs) const
Compare this iterator with another.
bool operator!= (const OpIterator &rhs) const
Detailed Description
This class provides iteration over the held operations of blocks directly within a region.
Definition at line 132 of file Region.h.
Constructor & Destructor Documentation
OpIterator()
Region::OpIterator::OpIterator (Region * region, bool end = false) explicit
Initialize OpIterator for a region, specify end to return the iterator to last operation.
Definition at line 226 of file Region.cpp.
References mlir::Region::begin(), mlir::Region::end(), and mlir::Region::Region().
Referenced by operator!=(), and operator==().
Member Function Documentation
operator!=()
bool mlir::Region::OpIterator::operator!= (const OpIterator & rhs) const inline
Definition at line 150 of file Region.h.
References OpIterator(), and rhs.
operator*()
Operation & mlir::Region::OpIterator::operator* () const inline
Definition at line 144 of file Region.h.
operator++()
Region::OpIterator & Region::OpIterator::operator++ ()
Definition at line 232 of file Region.cpp.
operator->()
Operation * mlir::Region::OpIterator::operator-> () const inline
Definition at line 143 of file Region.h.
operator==()
bool mlir::Region::OpIterator::operator== (const OpIterator & rhs) const inline
Compare this iterator with another.
Definition at line 147 of file Region.h.
References OpIterator(), and rhs.
The documentation for this class was generated from the following files:
include/mlir/IR/Region.h
lib/IR/Region.cpp