MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute Class Reference
Wrapper around the generic MlirAttribute.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Detailed Description
Wrapper around the generic MlirAttribute.
The lifetime of a type is bound by the PyContext that created it.
Definition at line 1018 of file IRCore.h.
Constructor & Destructor Documentation
PyAttribute()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr) inline
Definition at line 1020 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::gpu::ObjectAttr::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDConstantAttr::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::castFrom(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::dunderNext(), getCapsule(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute().
Member Function Documentation
createFromCapsule()
PyAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::createFromCapsule (const nanobind::object & capsule) static
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Note that PyAttribute instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirAttribute is taken by calling this function.
Definition at line 1864 of file IRCore.cpp.
References mlirPythonAttributeToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::get () const inline
Definition at line 1024 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeAttribute::bindDerived(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::dunderNext().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
Definition at line 1860 of file IRCore.cpp.
References mlirAttributeEqual(), and PyAttribute().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
maybeDownCast()
nb::typed< nb::object, PyAttribute > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::maybeDownCast ()
Definition at line 1872 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemRefType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRankedTensorType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedMemRefType::bindDerived(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirAttribute()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::operator MlirAttribute () const inline
Definition at line 1023 of file IRCore.h.
operator==()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::operator== (const PyAttribute & other) const
Definition at line 1856 of file IRCore.cpp.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp