MLIR: mlir::Namespace Class Reference
mlir::Namespace Class Reference
A namespace that is used to store existing names and generate new names in some scope within the IR.
#include "mlir/Target/SMTLIB/Namespace.h"
Public Member Functions
Namespace ()
Namespace (const Namespace &other)=default
Namespace (Namespace &&other)
Namespace & operator= (const Namespace &other)=default
Namespace & operator= (Namespace &&other)
void add (mlir::ModuleOp module)
void add (SymbolCache &symCache)
SymbolCache initializer; initialize from every key that is convertible to a StringAttr in the SymbolCache.
void add (llvm::StringRef name)
bool erase (llvm::StringRef symbol)
Removes a symbol from the namespace.
void clear ()
Empty the namespace.
llvm::StringRef newName (const llvm::Twine &name)
Return a unique name, derived from the input name, and add the new name to the internal namespace.
llvm::StringRef newName (const llvm::Twine &name, const llvm::Twine &suffix)
Return a unique name, derived from the input name and ensure the returned name has the input suffix.
Protected Attributes
llvm::StringMap< size_t > nextIndex
bool locked = false
Detailed Description
A namespace that is used to store existing names and generate new names in some scope within the IR.
This exists to work around limitations of SymbolTables. This acts as a base class providing facilities common to all namespaces implementations.
Definition at line 29 of file Namespace.h.
Constructor & Destructor Documentation
Namespace() [1/3]
mlir::Namespace::Namespace () inline
Definition at line 31 of file Namespace.h.
References nextIndex.
Referenced by Namespace(), Namespace(), operator=(), and operator=().
Namespace() [2/3]
mlir::Namespace::Namespace (const Namespace & other) default
References Namespace().
Namespace() [3/3]
mlir::Namespace::Namespace (Namespace && other) inline
Definition at line 37 of file Namespace.h.
References locked, Namespace(), and nextIndex.
Member Function Documentation
add() [1/3]
void mlir::Namespace::add (llvm::StringRef name) inline
Definition at line 63 of file Namespace.h.
References nextIndex.
add() [2/3]
void mlir::Namespace::add (mlir::ModuleOp module) inline
Definition at line 47 of file Namespace.h.
References mlir::SymbolTable::getSymbolAttrName(), and nextIndex.
add() [3/3]
void mlir::Namespace::add (SymbolCache & symCache) inline
SymbolCache initializer; initialize from every key that is convertible to a StringAttr in the SymbolCache.
Definition at line 57 of file Namespace.h.
References nextIndex.
clear()
void mlir::Namespace::clear () inline
Empty the namespace.
Definition at line 74 of file Namespace.h.
References locked, and nextIndex.
erase()
bool mlir::Namespace::erase (llvm::StringRef symbol) inline
Removes a symbol from the namespace.
Returns true if the symbol was removed, false if the symbol was not found. This is only allowed to be called before any call to newName.
Definition at line 68 of file Namespace.h.
References locked, and nextIndex.
newName() [1/2]
llvm::StringRef mlir::Namespace::newName (const llvm::Twine & name) inline
Return a unique name, derived from the input name, and add the new name to the internal namespace.
There are two possible outcomes for the returned name:
The original name is returned.
The name is given a _<n> suffix where <n> is a number starting from 0 and incrementing by one each time (_0, ...).
Definition at line 86 of file Namespace.h.
References inserted(), locked, and nextIndex.
newName() [2/2]
llvm::StringRef mlir::Namespace::newName (const llvm::Twine & name, const llvm::Twine & suffix) inline
Return a unique name, derived from the input name and ensure the returned name has the input suffix.
Also add the new name to the internal namespace. There are two possible outcomes for the returned name:
The original name + _<suffix> is returned.
The name is given a suffix _<n>_<suffix> where <n> is a number starting from 0 and incrementing by one each time.
Definition at line 120 of file Namespace.h.
References inserted(), locked, and nextIndex.
operator=() [1/2]
Namespace & mlir::Namespace::operator= (const Namespace & other) default
References Namespace().
operator=() [2/2]
Namespace & mlir::Namespace::operator= (Namespace && other) inline
Definition at line 41 of file Namespace.h.
References locked, Namespace(), and nextIndex.
Member Data Documentation
locked
bool mlir::Namespace::locked = false protected
Definition at line 165 of file Namespace.h.
Referenced by clear(), erase(), Namespace(), newName(), newName(), and operator=().
nextIndex
llvm::StringMap<size_t> mlir::Namespace::nextIndex protected
Definition at line 160 of file Namespace.h.
Referenced by add(), add(), add(), clear(), erase(), Namespace(), Namespace(), newName(), newName(), and operator=().
The documentation for this class was generated from the following file:
include/mlir/Target/SMTLIB/Namespace.h