MLIR: mlir::SelfOwningTypeID Class Reference
mlir::SelfOwningTypeID Class Reference
Defines a TypeID for each instance of this class by using a pointer to the instance.
#include "mlir/Support/TypeID.h"
Public Member Functions
SelfOwningTypeID ()=default
SelfOwningTypeID (const SelfOwningTypeID &)=delete
SelfOwningTypeID & operator= (const SelfOwningTypeID &)=delete
SelfOwningTypeID (SelfOwningTypeID &&)=delete
SelfOwningTypeID & operator= (SelfOwningTypeID &&)=delete
operator TypeID () const
Implicitly converts to the owned TypeID.
TypeID getTypeID () const
Return the TypeID owned by this object.
Detailed Description
Defines a TypeID for each instance of this class by using a pointer to the instance.
Thus, the copy and move constructor are deleted. Note: We align by 8 to match the alignment of TypeID::Storage, as we treat an instance of this class similarly to TypeID::Storage.
Definition at line 369 of file TypeID.h.
Constructor & Destructor Documentation
SelfOwningTypeID() [1/3]
mlir::SelfOwningTypeID::SelfOwningTypeID () default
Referenced by mlir::DynamicDialect::DynamicDialect(), operator=(), operator=(), SelfOwningTypeID(), and SelfOwningTypeID().
SelfOwningTypeID() [2/3]
mlir::SelfOwningTypeID::SelfOwningTypeID (const SelfOwningTypeID &) delete
References SelfOwningTypeID().
SelfOwningTypeID() [3/3]
mlir::SelfOwningTypeID::SelfOwningTypeID (SelfOwningTypeID &&) delete
References SelfOwningTypeID().
Member Function Documentation
getTypeID()
TypeID mlir::SelfOwningTypeID::getTypeID () const inline
Return the TypeID owned by this object.
Definition at line 381 of file TypeID.h.
References mlir::TypeID::getFromOpaquePointer().
Referenced by mlir::DynamicAttr::get(), mlir::DynamicType::get(), mlir::DynamicType::getChecked(), mlir::DynamicDialect::getTypeID(), mlir::DynamicAttr::isa(), mlir::DynamicType::isa(), and operator TypeID().
operator TypeID()
mlir::SelfOwningTypeID::operator TypeID () const inline
Implicitly converts to the owned TypeID.
Definition at line 378 of file TypeID.h.
References getTypeID().
operator=() [1/2]
SelfOwningTypeID & mlir::SelfOwningTypeID::operator= (const SelfOwningTypeID &) delete
References SelfOwningTypeID().
operator=() [2/2]
SelfOwningTypeID & mlir::SelfOwningTypeID::operator= (SelfOwningTypeID &&) delete
References SelfOwningTypeID().
The documentation for this class was generated from the following file:
include/mlir/Support/TypeID.h