MLIR: mlir::pdll::ast::Module Class Reference
mlir::pdll::ast::Module Class Reference final
This class represents a top-level AST module.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
MutableArrayRef< Decl * > getChildren ()
Return the children of this module.
ArrayRef< Decl * > getChildren () const
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT, typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static Module * create (Context &ctx, SMLoc loc, ArrayRef< Decl * > children)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< Module, Node >
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< Module, Node >
using Base
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< Module, Node >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This class represents a top-level AST module.
Definition at line 1296 of file Nodes.h.
Member Function Documentation
create()
Module * Module::create (Context & ctx, SMLoc loc, ArrayRef< Decl * > children) static
Definition at line 566 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator(), and getChildren().
getChildren() [1/2]
MutableArrayRef< Decl * > mlir::pdll::ast::Module::getChildren () inline
Return the children of this module.
Definition at line 1302 of file Nodes.h.
Referenced by create().
getChildren() [2/2]
ArrayRef< Decl * > mlir::pdll::ast::Module::getChildren () const inline
Definition at line 1305 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp