MLIR: mlir::quant::UniformQuantizedPerAxisValueConverter Class Reference
mlir::quant::UniformQuantizedPerAxisValueConverter Class Reference
An utility class to quantize an attribute by the per-axis quantization parameters.
#include "mlir/Dialect/Quant/UniformSupport.h"
Public Member Functions
UniformQuantizedPerAxisValueConverter (UniformQuantizedPerAxisType uniformType)
ElementsAttr convert (Attribute realValue)
Quantize an Attribute by the quantization parameters.
Detailed Description
An utility class to quantize an attribute by the per-axis quantization parameters.
The size of the quantization dim in the converted elements attribute should matche the size of of scales/zeroPoints vectors in the quantization parameters.
Definition at line 173 of file UniformSupport.h.
Constructor & Destructor Documentation
UniformQuantizedPerAxisValueConverter()
mlir::quant::UniformQuantizedPerAxisValueConverter::UniformQuantizedPerAxisValueConverter (UniformQuantizedPerAxisType uniformType) inline explicit
Definition at line 175 of file UniformSupport.h.
References mlir::quant::ExpressedToQuantizedConverter::convert().
Member Function Documentation
convert()
ElementsAttr UniformQuantizedPerAxisValueConverter::convert (Attribute realValue)
Quantize an Attribute by the quantization parameters.
Return nullptr if the conversion fails or the input array isn't an ElementsAttr.
Definition at line 52 of file UniformSupport.cpp.
References mlir::quant::ExpressedToQuantizedConverter::convert(), mlir::Attribute::dyn_cast(), mlir::ShapedType::getDimSize(), mlir::ShapedType::getShape(), and mlir::DenseFPElementsAttr::mapValues().
Referenced by mlir::quant::quantizeAttr().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Quant/UniformSupport.h
lib/Dialect/Quant/Utils/UniformSupport.cpp