MLIR: mlir::memref::DmaWaitOp Class Reference
mlir::memref::DmaWaitOp Class Reference
#include "mlir/Dialect/MemRef/IR/MemRef.h"
Public Member Functions
Value getTagMemRef ()
operand_range getTagIndices ()
unsigned getTagMemRefRank ()
Value getNumElements ()
void print (OpAsmPrinter &p)
LogicalResult fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > &results)
LogicalResult verify ()
Public Member Functions inherited from mlir::Op< DmaWaitOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
DmaWaitOp clone ()
Create a deep copy of this operation.
DmaWaitOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * operator-> () const
Shortcut of -> to access a member of Operation.
Operation * getOperation ()
Return the operation that this refers to.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<WalkOrder Order = WalkOrder::PostOrder, typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
Public Member Functions inherited from mlir::OpTrait::detail::MultiOperandTraitBase< DmaWaitOp, VariadicOperands >
unsigned getNumOperands ()
Return the number of operands.
Value getOperand (unsigned i)
Return the operand at index 'i'.
void setOperand (unsigned i, Value value)
Set the operand at index 'i' to 'value'.
operand_iterator operand_begin ()
Operand iterator access.
operand_iterator operand_end ()
operand_range getOperands ()
operand_type_iterator operand_type_begin ()
Operand type access.
operand_type_iterator operand_type_end ()
operand_type_range getOperandTypes ()
Static Public Member Functions
static ArrayRef< StringRef > getAttributeNames ()
static void build (OpBuilder &builder, OperationState &result, Value tagMemRef, ValueRange tagIndices, Value numElements)
static StringRef getOperationName ()
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Static Public Member Functions inherited from mlir::Op< DmaWaitOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static std::enable_if_t< std::is_base_of< OpState, T >::value, bool > classof (const T *op)
Provide classof support for other OpBase derived classes, such as Interfaces.
static ConcreteOpType getFromOpaquePointer (const void *pointer)
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete operation.
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Additional Inherited Members
Public Types inherited from mlir::Op< DmaWaitOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
using ConcreteOpType = DmaWaitOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Public Types inherited from mlir::OpTrait::detail::MultiOperandTraitBase< DmaWaitOp, VariadicOperands >
using operand_iterator = Operation::operand_iterator
using operand_range = Operation::operand_range
using operand_type_iterator = Operation::operand_type_iterator
using operand_type_range = Operation::operand_type_range
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< DmaWaitOp, VariadicOperands >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
static void print (Operation *op, OpAsmPrinter &p)
Detailed Description
Definition at line 214 of file MemRef.h.
Member Function Documentation
build()
void DmaWaitOp::build (OpBuilder & builder, OperationState & result, Value tagMemRef, ValueRange tagIndices, Value numElements) static
Definition at line 914 of file MemRefOps.cpp.
References mlir::OperationState::addOperands().
fold()
LogicalResult DmaWaitOp::fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > & results)
dma_wait(memrefcast) -> dma_wait
Definition at line 953 of file MemRefOps.cpp.
References foldMemRefCast().
getAttributeNames()
static ArrayRef<StringRef> mlir::memref::DmaWaitOp::getAttributeNames () inline static
Definition at line 218 of file MemRef.h.
References mlir::memref::DmaStartOp::build().
getNumElements()
Value mlir::memref::DmaWaitOp::getNumElements () inline
Definition at line 240 of file MemRef.h.
References mlir::memref::DmaStartOp::fold(), mlir::OpTrait::detail::MultiOperandTraitBase< DmaStartOp, VariadicOperands >::getOperand(), mlir::memref::DmaStartOp::getTagMemRefRank(), mlir::memref::DmaStartOp::parse(), mlir::memref::DmaStartOp::print(), and mlir::memref::DmaStartOp::verify().
Referenced by mlir::lowerAffineLowerBound().
getOperationName()
static StringRef mlir::memref::DmaWaitOp::getOperationName () inline static
Definition at line 223 of file MemRef.h.
getTagIndices()
operand_range mlir::memref::DmaWaitOp::getTagIndices () inline
Definition at line 229 of file MemRef.h.
References mlir::memref::DmaStartOp::getTagMemRefRank().
getTagMemRef()
Value mlir::memref::DmaWaitOp::getTagMemRef () inline
Definition at line 226 of file MemRef.h.
References mlir::OpTrait::detail::MultiOperandTraitBase< DmaStartOp, VariadicOperands >::getOperand().
Referenced by mlir::lowerAffineLowerBound().
getTagMemRefRank()
unsigned mlir::memref::DmaWaitOp::getTagMemRefRank () inline
Definition at line 235 of file MemRef.h.
References mlir::Type::cast(), mlir::memref::DmaStartOp::getTagMemRef(), and mlir::Value::getType().
parse()
ParseResult DmaWaitOp::parse (OpAsmParser & parser, OperationState & result) static
Definition at line 933 of file MemRefOps.cpp.
References mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
print()
void DmaWaitOp::print (OpAsmPrinter & p)
Definition at line 922 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
verify()
LogicalResult DmaWaitOp::verify ()
Definition at line 959 of file MemRefOps.cpp.
References mlir::Type::isIndex(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/MemRef/IR/MemRef.h
lib/Dialect/MemRef/IR/MemRefOps.cpp