MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPatternRewriter Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPatternRewriter Class Reference
Public Member Functions
PyPatternRewriter (MlirPatternRewriter rewriter)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< PyPatternRewriter >
PyRewriterBase (MlirRewriterBase rewriter)
PyInsertionPoint getInsertionPoint () const
Static Public Attributes
static constexpr const char * pyClassName = "PatternRewriter"
Additional Inherited Members
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< PyPatternRewriter >
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 60 of file Rewrite.cpp.
Constructor & Destructor Documentation
PyPatternRewriter()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPatternRewriter::PyPatternRewriter (MlirPatternRewriter rewriter) inline
Definition at line 64 of file Rewrite.cpp.
References mlirPatternRewriterAsBase(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< PyPatternRewriter >::PyRewriterBase().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionPatternRewriter::PyConversionPatternRewriter().
Member Data Documentation
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPatternRewriter::pyClassName = "PatternRewriter" static constexpr
Definition at line 62 of file Rewrite.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.cpp