MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyOperationIterator (PyOperationRef parentOperation, MlirOperation next)
PyOperationIterator & dunderIter ()
nanobind::typed< nanobind::object, PyOpView > dunderNext ()
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 1574 of file IRCore.h.
Constructor & Destructor Documentation
PyOperationIterator()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator::PyOperationIterator (PyOperationRef parentOperation, MlirOperation next) inline
Definition at line 1576 of file IRCore.h.
Referenced by dunderIter().
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator::bind (nanobind::module_ & m) static
Definition at line 308 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderIter()
PyOperationIterator & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator::dunderIter () inline
Definition at line 1579 of file IRCore.h.
References PyOperationIterator().
dunderNext()
nb::typed< nb::object, PyOpView > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator::dunderNext ()
Definition at line 294 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationList::dunderIter().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp