MLIR: mlir::PresburgerSet Class Reference
mlir::PresburgerSet Class Reference
This class can represent a union of FlatAffineConstraints, with support for union, intersection, subtraction and complement operations, as well as sampling.
#include "mlir/Analysis/PresburgerSet.h"
Public Member Functions
PresburgerSet (const FlatAffineConstraints &fac)
unsigned getNumFACs () const
Return the number of FACs in the union.
unsigned getNumDims () const
Return the number of real dimensions.
unsigned getNumSyms () const
Return the number of symbolic dimensions.
ArrayRef< FlatAffineConstraints > getAllFlatAffineConstraints () const
Return a reference to the list of FlatAffineConstraints.
const FlatAffineConstraints & getFlatAffineConstraints (unsigned index) const
Return the FlatAffineConstraints at the specified index.
void unionFACInPlace (const FlatAffineConstraints &fac)
Mutate this set, turning it into the union of this set and the given FlatAffineConstraints.
void unionSetInPlace (const PresburgerSet &set)
Mutate this set, turning it into the union of this set and the given set.
PresburgerSet unionSet (const PresburgerSet &set) const
Return the union of this set and the given set.
PresburgerSet intersect (const PresburgerSet &set) const
Return the intersection of this set and the given set.
bool containsPoint (ArrayRef< int64_t > point) const
Return true if the set contains the given point, and false otherwise.
void print (raw_ostream &os) const
Print the set's internal state.
void dump () const
PresburgerSet complement () const
Return the complement of this set.
PresburgerSet subtract (const PresburgerSet &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
bool isEqual (const PresburgerSet &set) const
Return true if this set is equal to the given set, and false otherwise.
bool isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
bool findIntegerSample (SmallVectorImpl< int64_t > &sample)
Find an integer sample from the given set.
Static Public Member Functions
static PresburgerSet getUniverse (unsigned nDim=0, unsigned nSym=0)
Return a universe set of the specified type that contains all points.
static PresburgerSet getEmptySet (unsigned nDim=0, unsigned nSym=0)
Return an empty set of the specified type that contains no points.
Detailed Description
This class can represent a union of FlatAffineConstraints, with support for union, intersection, subtraction and complement operations, as well as sampling.
The FlatAffineConstraints (FACs) are stored in a vector, and the set represents the union of these FACs. An empty list corresponds to the empty set.
Note that there are no invariants guaranteed on the list of FACs other than that they are all in the same space, i.e., they all have the same number of dimensions and symbols. For example, the FACs may overlap each other.
Definition at line 31 of file PresburgerSet.h.
Constructor & Destructor Documentation
PresburgerSet()
PresburgerSet::PresburgerSet (const FlatAffineConstraints & fac) explicit
Definition at line 16 of file PresburgerSet.cpp.
References unionFACInPlace().
Referenced by getEmptySet().
Member Function Documentation
complement()
PresburgerSet PresburgerSet::complement () const
Return the complement of this set.
Computing the complement of a set containing divisions is not yet supported.
Definition at line 272 of file PresburgerSet.cpp.
References getNumDims(), getNumSyms(), and mlir::FlatAffineConstraints::getUniverse().
containsPoint()
bool PresburgerSet::containsPoint (ArrayRef< int64_t > point) const
Return true if the set contains the given point, and false otherwise.
A point is contained in the union iff any of the parts contain the point.
Definition at line 87 of file PresburgerSet.cpp.
dump()
void PresburgerSet::dump () const
Definition at line 331 of file PresburgerSet.cpp.
References print().
findIntegerSample()
bool PresburgerSet::findIntegerSample (SmallVectorImpl< int64_t > & sample)
Find an integer sample from the given set.
This should not be called if any of the FACs in the union are unbounded.
Definition at line 312 of file PresburgerSet.cpp.
References mlir::FlatAffineConstraints::findIntegerSample().
getAllFlatAffineConstraints()
ArrayRef< FlatAffineConstraints > PresburgerSet::getAllFlatAffineConstraints () const
Return a reference to the list of FlatAffineConstraints.
Definition at line 30 of file PresburgerSet.cpp.
getEmptySet()
PresburgerSet PresburgerSet::getEmptySet (unsigned nDim = 0, unsigned nSym = 0) static
Return an empty set of the specified type that contains no points.
Definition at line 101 of file PresburgerSet.cpp.
References PresburgerSet().
Referenced by subtractRecursively().
getFlatAffineConstraints()
const FlatAffineConstraints & PresburgerSet::getFlatAffineConstraints (unsigned index) const
Return the FlatAffineConstraints at the specified index.
Definition at line 35 of file PresburgerSet.cpp.
Referenced by subtractRecursively().
getNumDims()
unsigned PresburgerSet::getNumDims () const
Return the number of real dimensions.
Definition at line 25 of file PresburgerSet.cpp.
Referenced by assertDimensionsCompatible(), and complement().
getNumFACs()
unsigned PresburgerSet::getNumFACs () const
Return the number of FACs in the union.
Definition at line 21 of file PresburgerSet.cpp.
Referenced by print(), and subtractRecursively().
getNumSyms()
unsigned PresburgerSet::getNumSyms () const
Return the number of symbolic dimensions.
Definition at line 27 of file PresburgerSet.cpp.
Referenced by assertDimensionsCompatible(), and complement().
getUniverse()
PresburgerSet PresburgerSet::getUniverse (unsigned nDim = 0, unsigned nSym = 0) static
Return a universe set of the specified type that contains all points.
Definition at line 95 of file PresburgerSet.cpp.
References mlir::FlatAffineConstraints::getUniverse(), and unionFACInPlace().
intersect()
PresburgerSet PresburgerSet::intersect (const PresburgerSet & set) const
Return the intersection of this set and the given set.
Definition at line 109 of file PresburgerSet.cpp.
References mlir::FlatAffineConstraints::append(), assertDimensionsCompatible(), mlir::FlatAffineConstraints::isEmpty(), and unionFACInPlace().
isEqual()
bool PresburgerSet::isEqual (const PresburgerSet & set) const
Return true if this set is equal to the given set, and false otherwise.
Two sets S and T are equal iff S contains T and T contains S.
Checking equality when either set contains divisions is not yet supported.
By "S contains T", we mean that S is a superset of or equal to T.
S contains T iff T \ S is empty, since if T \ S contains a point then this is a point that is contained in T but not S.
Therefore, S is equal to T iff S \ T and T \ S are both empty.
Definition at line 295 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), isIntegerEmpty(), and subtract().
isIntegerEmpty()
bool PresburgerSet::isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
Return true if all the sets in the union are known to be integer empty, false otherwise.
Definition at line 303 of file PresburgerSet.cpp.
References mlir::FlatAffineConstraints::isIntegerEmpty().
Referenced by isEqual(), mlir::ComputationSliceState::isMaximal(), and mlir::ComputationSliceState::isSliceValid().
print()
void PresburgerSet::print (raw_ostream & os) const
Print the set's internal state.
Definition at line 323 of file PresburgerSet.cpp.
References getNumFACs(), and mlir::FlatAffineConstraints::print().
Referenced by dump().
subtract()
PresburgerSet PresburgerSet::subtract (const PresburgerSet & set) const
Return the set difference of this set and the given set, i.e., return this \ set.
Return the result of subtract the given set from this set, i.e., return this \ set.
Subtracting when either set contains divisions is not yet supported.
Definition at line 279 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), and unionSetInPlace().
Referenced by isEqual(), mlir::ComputationSliceState::isMaximal(), and mlir::ComputationSliceState::isSliceValid().
unionFACInPlace()
void PresburgerSet::unionFACInPlace (const FlatAffineConstraints & fac)
Mutate this set, turning it into the union of this set and the given FlatAffineConstraints.
Definition at line 63 of file PresburgerSet.cpp.
References assertDimensionsCompatible().
Referenced by getUniverse(), intersect(), PresburgerSet(), subtractRecursively(), and unionSetInPlace().
unionSet()
PresburgerSet PresburgerSet::unionSet (const PresburgerSet & set) const
Return the union of this set and the given set.
Definition at line 79 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), and unionSetInPlace().
unionSetInPlace()
void PresburgerSet::unionSetInPlace (const PresburgerSet & set)
Mutate this set, turning it into the union of this set and the given set.
This is accomplished by simply adding all the FACs of the given set to this set.
Definition at line 72 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), and unionFACInPlace().
Referenced by subtract(), and unionSet().
The documentation for this class was generated from the following files:
include/mlir/Analysis/PresburgerSet.h
lib/Analysis/PresburgerSet.cpp