MLIR: mlir::pdll::ast::ValueType Class Reference
mlir::pdll::ast::ValueType Class Reference
This class represents a PDLL type that corresponds to an mlir::Value.
#include "mlir/Tools/PDLL/AST/Types.h"
Static Public Member Functions
static ValueType get (Context &context)
Return an instance of the Value type.
Static Public Member Functions inherited from mlir::pdll::ast::Type::TypeBase< detail::ValueTypeStorage >
static bool classof (Type type)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Type::TypeBase< detail::ValueTypeStorage >
using Base = TypeBase< detail::ValueTypeStorage, Type >
using ImplTy = detail::ValueTypeStorage
Public Member Functions inherited from mlir::pdll::ast::Type
Type (Storage *impl=nullptr)
bool operator== (const Type &other) const
bool operator!= (const Type &other) const
operator bool () const
Storage * getImpl () const
Return the internal storage instance of this type.
TypeID getTypeID () const
Return the TypeID instance of this type.
void print (raw_ostream &os) const
Print this type to the given stream.
Type refineWith (Type other) const
Try to refine this type with the one provided.
Protected Member Functions inherited from mlir::pdll::ast::Type
template<typename T >
const T * getImplAs () const
Return the internal storage instance of this type reinterpreted as the given derived storage type.
Detailed Description
This class represents a PDLL type that corresponds to an mlir::Value.
Definition at line 262 of file Types.h.
Member Function Documentation
get()
ValueType ValueType::get (Context & context) static
Return an instance of the Value type.
Definition at line 175 of file Types.cpp.
References mlir::StorageUniquer::get(), and mlir::pdll::ast::Context::getTypeUniquer().
Referenced by mlir::pdll::ast::ValueRangeType::get(), and mlir::parseSourceFile().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Types.h
lib/Tools/PDLL/AST/Types.cpp