MLIR: mlir::AbstractOperation Class Reference
mlir::AbstractOperation Class Reference
This is a "type erased" representation of a registered operation.
#include "mlir/IR/OperationSupport.h"
Public Types
using GetCanonicalizationPatternsFn = llvm::unique_function< void(RewritePatternSet &, MLIRContext *) const >
using FoldHookFn = llvm::unique_function< LogicalResult(Operation *, ArrayRef< Attribute >, SmallVectorImpl< OpFoldResult > &) const >
using HasTraitFn = llvm::unique_function< bool(TypeID) const >
using ParseAssemblyFn = llvm::unique_function< ParseResult(OpAsmParser &, OperationState &) const >
using PrintAssemblyFn = llvm::unique_function< void(Operation *, OpAsmPrinter &) const >
using VerifyInvariantsFn = llvm::unique_function< LogicalResult(Operation *) const >
Public Member Functions
ParseResult parseAssembly (OpAsmParser &parser, OperationState &result) const
Use the specified object to parse this ops custom assembly format.
const ParseAssemblyFn & getParseAssemblyFn () const
Return the static hook for parsing this operation assembly.
void printAssembly (Operation *op, OpAsmPrinter &p) const
This hook implements the AsmPrinter for this operation.
LogicalResult verifyInvariants (Operation *op) const
This hook implements the verifier for this operation.
LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results) const
This hook implements a generalized folder for this operation.
void getCanonicalizationPatterns (RewritePatternSet &results, MLIRContext *context) const
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
template<typename T >
T::Concept * getInterface () const
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
bool hasInterface (TypeID interfaceID) const
Returns true if this operation has the given interface registered to it.
template<template< typename T > class Trait>
bool hasTrait () const
Returns true if the operation has a particular trait.
bool hasTrait (TypeID traitID) const
Returns true if the operation has a particular trait.
ArrayRef< Identifier > getAttributeNames () const
Return the list of cached attribute names registered to this operation.
Static Public Member Functions
static const AbstractOperation * lookup (StringRef opName, MLIRContext *context)
Look up the specified operation in the specified MLIRContext and return a pointer to it if present.
template<typename T >
static void insert (Dialect &dialect)
This constructor is used by Dialect objects when they register the list of operations they contain.
static void insert (StringRef name, Dialect &dialect, TypeID typeID, ParseAssemblyFn &&parseAssembly, PrintAssemblyFn &&printAssembly, VerifyInvariantsFn &&verifyInvariants, FoldHookFn &&foldHook, GetCanonicalizationPatternsFn &&getCanonicalizationPatterns, detail::InterfaceMap &&interfaceMap, HasTraitFn &&hasTrait, ArrayRef< StringRef > attrNames)
Register a new operation in a Dialect object.
Public Attributes
const Identifier name
This is the name of the operation.
Dialect & dialect
This is the dialect that this operation belongs to.
TypeID typeID
The unique identifier of the derived Op class.
Friends
template<typename ConcreteType , template< typename T > class... Traits>
class Op
Give Op access to lookupMutable.
Detailed Description
This is a "type erased" representation of a registered operation.
This should only be used by things like the AsmPrinter and other things that need to be parameterized by generic operation hooks. Most user code should use the concrete operation types.
Definition at line 68 of file OperationSupport.h.
Member Typedef Documentation
FoldHookFn
using mlir::AbstractOperation::FoldHookFn = llvm::unique_function<LogicalResult(Operation *, ArrayRef<Attribute>, SmallVectorImpl<OpFoldResult> &) const>
Definition at line 73 of file OperationSupport.h.
GetCanonicalizationPatternsFn
using mlir::AbstractOperation::GetCanonicalizationPatternsFn = llvm::unique_function<void(RewritePatternSet &, MLIRContext *) const>
Definition at line 71 of file OperationSupport.h.
HasTraitFn
using mlir::AbstractOperation::HasTraitFn = llvm::unique_function<bool(TypeID) const>
Definition at line 74 of file OperationSupport.h.
ParseAssemblyFn
using mlir::AbstractOperation::ParseAssemblyFn = llvm::unique_function<ParseResult(OpAsmParser &, OperationState &) const>
Definition at line 76 of file OperationSupport.h.
PrintAssemblyFn
using mlir::AbstractOperation::PrintAssemblyFn = llvm::unique_function<void(Operation *, OpAsmPrinter &) const>
Definition at line 78 of file OperationSupport.h.
VerifyInvariantsFn
using mlir::AbstractOperation::VerifyInvariantsFn = llvm::unique_function<LogicalResult(Operation *) const>
Definition at line 80 of file OperationSupport.h.
Member Function Documentation
foldHook()
LogicalResult mlir::AbstractOperation::foldHook (Operation * op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > & results) const inline
This hook implements a generalized folder for this operation.
Operations can implement this to provide simplifications rules that are applied by the Builder::createOrFold API and the canonicalization pass.
This is an intentionally limited interface - implementations of this hook can only perform the following changes to the operation:
They can leave the operation alone and without changing the IR, and return failure.
They can mutate the operation in place, without changing anything else in the IR. In this case, return success.
They can return a list of existing values that can be used instead of the operation. In this case, fill in the results list and return success. The caller will remove the operation and use those results instead.
This allows expression of some simple in-place canonicalizations (e.g. "x+0 -> x", "min(x,y,x,z) -> min(x,y,z)", "x+y-x -> y", etc), as well as generalized constant folding.
Definition at line 128 of file OperationSupport.h.
getAttributeNames()
ArrayRef<Identifier> mlir::AbstractOperation::getAttributeNames () const inline
Return the list of cached attribute names registered to this operation.
The order of attributes cached here is unique to each type of operation, and the interpretation of this attribute list should generally be driven by the respective operation. In many cases, this caching removes the need to use the raw string name of a known attribute.
For example the ODS generator, with an op defining the following attributes:
let arguments = (ins I32Attr:$attr1, I32Attr:$attr2);
... may produce an order here of ["attr1", "attr2"]. This allows for the ODS generator to directly access the cached name for a known attribute, greatly simplifying the cost and complexity of attribute usage produced by the generator.
Definition at line 207 of file OperationSupport.h.
References mlir::op_definition_impl::hasTrait().
getCanonicalizationPatterns()
void mlir::AbstractOperation::getCanonicalizationPatterns (RewritePatternSet & results, MLIRContext * context) const inline
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Definition at line 135 of file OperationSupport.h.
getInterface()
template<typename T > T::Concept* mlir::AbstractOperation::getInterface () const inline
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
This should not be used directly.
Definition at line 144 of file OperationSupport.h.
Referenced by inferOperationTypes(), and mlir::detail::PDLByteCode::initializeMutableState().
getParseAssemblyFn()
const ParseAssemblyFn& mlir::AbstractOperation::getParseAssemblyFn () const inline
Return the static hook for parsing this operation assembly.
Definition at line 95 of file OperationSupport.h.
hasInterface()
bool mlir::AbstractOperation::hasInterface (TypeID interfaceID) const inline
Returns true if this operation has the given interface registered to it.
Definition at line 149 of file OperationSupport.h.
Referenced by mlir::FrozenRewritePatternSet::FrozenRewritePatternSet().
hasTrait() [1/2]
template<template< typename T > class Trait> bool mlir::AbstractOperation::hasTrait () const inline
Returns true if the operation has a particular trait.
Definition at line 155 of file OperationSupport.h.
Referenced by mlir::FrozenRewritePatternSet::FrozenRewritePatternSet(), mlir::Operation::hasTrait(), mlir::Operation::mightHaveTrait(), and mlir::detail::Parser::parseFloatFromIntegerLiteral().
hasTrait() [2/2]
bool mlir::AbstractOperation::hasTrait (TypeID traitID) const inline
Returns true if the operation has a particular trait.
Definition at line 160 of file OperationSupport.h.
insert() [1/2]
template<typename T > static void mlir::AbstractOperation::insert (Dialect & dialect) inline static
This constructor is used by Dialect objects when they register the list of operations they contain.
Definition at line 172 of file OperationSupport.h.
References mlir::op_definition_impl::hasTrait().
insert() [2/2]
void AbstractOperation::insert (StringRef name, Dialect & dialect, TypeID typeID, ParseAssemblyFn && parseAssembly, PrintAssemblyFn && printAssembly, VerifyInvariantsFn && verifyInvariants, FoldHookFn && foldHook, GetCanonicalizationPatternsFn && getCanonicalizationPatterns, detail::InterfaceMap && interfaceMap, HasTraitFn && hasTrait, ArrayRef< StringRef > attrNames) static
Register a new operation in a Dialect object.
The use of this method is in general discouraged in favor of 'insert<CustomOp>(dialect)'.
Definition at line 756 of file MLIRContext.cpp.
References mlir::Identifier::get(), mlir::Dialect::getContext(), mlir::MLIRContext::getImpl(), and mlir::op_definition_impl::hasTrait().
lookup()
static const AbstractOperation* mlir::AbstractOperation::lookup (StringRef opName, MLIRContext * context) inline static
Look up the specified operation in the specified MLIRContext and return a pointer to it if present.
Otherwise, return a null pointer.
Definition at line 164 of file OperationSupport.h.
Referenced by inferOperationTypes(), mlir::OperationName::OperationName(), and mlir::detail::Parser::parseFloatFromIntegerLiteral().
parseAssembly()
ParseResult AbstractOperation::parseAssembly (OpAsmParser & parser, OperationState & result) const
Use the specified object to parse this ops custom assembly format.
Definition at line 740 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl().
printAssembly()
void mlir::AbstractOperation::printAssembly (Operation * op, OpAsmPrinter & p) const inline
This hook implements the AsmPrinter for this operation.
Definition at line 98 of file OperationSupport.h.
verifyInvariants()
LogicalResult mlir::AbstractOperation::verifyInvariants (Operation * op) const inline
This hook implements the verifier for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 105 of file OperationSupport.h.
Friends And Related Function Documentation
Op
template<typename ConcreteType , template< typename T > class... Traits> friend class Op friend
Give Op access to lookupMutable.
Definition at line 221 of file OperationSupport.h.
Member Data Documentation
dialect
Dialect& mlir::AbstractOperation::dialect
This is the dialect that this operation belongs to.
Definition at line 86 of file OperationSupport.h.
Referenced by mlir::OpInterface< AffineMapAccessInterface, detail::AffineMapAccessInterfaceInterfaceTraits >::getInterfaceFor().
name
const Identifier mlir::AbstractOperation::name
This is the name of the operation.
Definition at line 83 of file OperationSupport.h.
typeID
TypeID mlir::AbstractOperation::typeID
The unique identifier of the derived Op class.
Definition at line 89 of file OperationSupport.h.
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/MLIRContext.cpp