MLIR: mlir::pdll::ast::OpNameDecl Class Reference
mlir::pdll::ast::OpNameDecl Class Reference
This Decl represents an OperationName.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
std::optional< StringRef > getName () const
Return the name of this operation, or std::nullopt if the name is unknown.
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
void setDocComment (Context &ctx, StringRef comment)
Set the documentation comment for this decl.
std::optional< StringRef > getDocComment () const
Return the documentation comment attached to this decl if it has been set.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT, typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static OpNameDecl * create (Context &ctx, const Name &name)
static OpNameDecl * create (Context &ctx, SMRange loc)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< OpNameDecl, Decl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< OpNameDecl, Decl >
using Base
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< OpNameDecl, Decl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This Decl represents an OperationName.
Definition at line 1022 of file Nodes.h.
Member Function Documentation
create() [1/2]
OpNameDecl * OpNameDecl::create (Context & ctx, const Name & name) static
Definition at line 502 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator().
Referenced by mlir::pdll::ast::OpConstraintDecl::create().
create() [2/2]
OpNameDecl * OpNameDecl::create (Context & ctx, SMRange loc) static
Definition at line 505 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator().
getName()
std::optional< StringRef > mlir::pdll::ast::OpNameDecl::getName () const inline
Return the name of this operation, or std::nullopt if the name is unknown.
Definition at line 1028 of file Nodes.h.
References mlir::pdll::ast::Decl::getName().
Referenced by mlir::pdll::ast::OperationExpr::create(), mlir::pdll::ast::OpConstraintDecl::getName(), and mlir::pdll::ast::OperationExpr::getName().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp