MLIR: mlir::tblgen::OpMethodSignature Class Reference
mlir::tblgen::OpMethodSignature Class Reference
#include "mlir/TableGen/OpClass.h"
Public Member Functions
template<typename... Args>
OpMethodSignature (StringRef retType, StringRef name, Args &&...args)
OpMethodSignature (OpMethodSignature &&)=default
bool makesRedundant (const OpMethodSignature &other) const
size_t getNumParameters () const
StringRef getName () const
void writeDeclTo (raw_ostream &os) const
void writeDefTo (raw_ostream &os, StringRef namePrefix) const
Detailed Description
Definition at line 178 of file OpClass.h.
Constructor & Destructor Documentation
OpMethodSignature() [1/2]
template<typename... Args> mlir::tblgen::OpMethodSignature::OpMethodSignature (StringRef retType, StringRef name, Args &&... args) inline
Definition at line 181 of file OpClass.h.
OpMethodSignature() [2/2]
mlir::tblgen::OpMethodSignature::OpMethodSignature (OpMethodSignature &&) default
Member Function Documentation
getName()
StringRef mlir::tblgen::OpMethodSignature::getName () const inline
Definition at line 197 of file OpClass.h.
References mlir::tblgen::OpMethodParameter::writeDeclTo(), and mlir::tblgen::OpMethodParameter::writeDefTo().
getNumParameters()
size_t mlir::tblgen::OpMethodSignature::getNumParameters () const inline
Definition at line 191 of file OpClass.h.
makesRedundant()
bool OpMethodSignature::makesRedundant (const OpMethodSignature & other) const
Definition at line 140 of file OpClass.cpp.
References mlir::tblgen::OpMethodResolvedParameters::makesRedundant().
writeDeclTo()
void OpMethodSignature::writeDeclTo (raw_ostream & os) const
Definition at line 151 of file OpClass.cpp.
writeDefTo()
void OpMethodSignature::writeDefTo (raw_ostream & os, StringRef namePrefix) const
Definition at line 157 of file OpClass.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp