MLIR: mlir::Region Class Reference
mlir::Region Class Reference
This class contains a list of basic blocks and a link to the parent operation it is attached to.
#include "mlir/IR/Region.h"
Classes
class OpIterator
This class provides iteration over the held operations of blocks directly within a region.
Public Types
using BlockListType = llvm::iplist<Block>
using iterator = BlockListType::iterator
using reverse_iterator = BlockListType::reverse_iterator
using BlockArgListType = MutableArrayRef<BlockArgument>
using args_iterator = BlockArgListType::iterator
using reverse_args_iterator = BlockArgListType::reverse_iterator
template<typename OpT>
using op_iterator = detail::op_iterator<OpT, OpIterator>
This class provides iteration over the held operations of a region for a specific operation type.
Public Member Functions
Region ()=default
Region (Operation *container)
~Region ()
MLIRContext * getContext ()
Return the context this region is inserted in.
Location getLoc ()
Return a location for this region.
BlockListType & getBlocks ()
Block & emplaceBlock ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
bool empty ()
void push_back (Block *block)
void push_front (Block *block)
Block & back ()
Block & front ()
bool hasOneBlock ()
Return true if this region has exactly one block.
BlockArgListType getArguments ()
ValueTypeRange< BlockArgListType > getArgumentTypes ()
Returns the argument types of the first block within the region.
args_iterator args_begin ()
args_iterator args_end ()
reverse_args_iterator args_rbegin ()
reverse_args_iterator args_rend ()
bool args_empty ()
BlockArgument addArgument (Type type, Location loc)
Add one value to the argument list.
BlockArgument insertArgument (args_iterator it, Type type, Location loc)
Insert one value to the position in the argument list indicated by the given iterator.
iterator_range< args_iterator > addArguments (TypeRange types, ArrayRef< Location > locs)
Add one argument to the argument list for each type specified in the list.
BlockArgument insertArgument (unsigned index, Type type, Location loc)
Add one value to the argument list at the specified position.
void eraseArgument (unsigned index)
Erase the argument at 'index' and remove it from the argument list.
unsigned getNumArguments ()
BlockArgument getArgument (unsigned i)
OpIterator op_begin ()
Return iterators that walk the operations nested directly within this region.
OpIterator op_end ()
iterator_range< OpIterator > getOps ()
template<typename OpT>
op_iterator< OpT > op_begin ()
Return iterators that walk operations of type 'T' nested directly within this region.
template<typename OpT>
op_iterator< OpT > op_end ()
template<typename OpT>
iterator_range< op_iterator< OpT > > getOps ()
Region * getParentRegion ()
Return the region containing this region or nullptr if the region is attached to a top-level operation.
Operation * getParentOp ()
Return the parent operation this region is attached to.
template<typename ParentT>
ParentT getParentOfType ()
Find the first parent operation of the given type, or nullptr if there is no ancestor operation.
template<typename... ParentT>
std::enable_if_t<(sizeof...(ParentT) > 1), Operation * > getParentOfType ()
unsigned getRegionNumber ()
Return the number of this region in the parent operation.
bool isProperAncestor (Region *other)
Return true if this region is a proper ancestor of the other region.
bool isAncestor (Region *other)
Return true if this region is ancestor of the other region.
void cloneInto (Region *dest, IRMapping &mapper)
Clone the internal blocks from this region into dest.
void cloneInto (Region *dest, Region::iterator destPos, IRMapping &mapper)
Clone this region into 'dest' before the given position in 'dest'.
void takeBody (Region &other)
Takes body of another region (that region will have no body after this operation completes).
Block * findAncestorBlockInRegion (Block &block)
Returns 'block' if 'block' lies in this region, or otherwise finds the ancestor of 'block' that lies in this region.
Operation * findAncestorOpInRegion (Operation &op)
Returns 'op' if 'op' lies in this region, or otherwise finds the ancestor of 'op' that lies in this region.
void dropAllReferences ()
Drop all operand uses from operations within this region, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename ArgT = detail::first_argument<FnT>, typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk all nested operations, blocks or regions (including this region), depending on the type of callback.
void viewGraph (const Twine &regionName)
Displays the CFG in a window.
void viewGraph ()
Static Public Member Functions
static BlockListType Region::* getSublistAccess (Block *)
getSublistAccess() - Returns pointer to member of region.
Detailed Description
This class contains a list of basic blocks and a link to the parent operation it is attached to.
Definition at line 26 of file Region.h.
Member Typedef Documentation
args_iterator
using mlir::Region::args_iterator = BlockArgListType::iterator
Definition at line 88 of file Region.h.
BlockArgListType
using mlir::Region::BlockArgListType = MutableArrayRef<BlockArgument>
Definition at line 80 of file Region.h.
BlockListType
using mlir::Region::BlockListType = llvm::iplist<Block>
Definition at line 44 of file Region.h.
iterator
using mlir::Region::iterator = BlockListType::iterator
Definition at line 52 of file Region.h.
op_iterator
template<typename OpT> using mlir::Region::op_iterator = detail::op_iterator<OpT, OpIterator>
This class provides iteration over the held operations of a region for a specific operation type.
Definition at line 166 of file Region.h.
reverse_args_iterator
using mlir::Region::reverse_args_iterator = BlockArgListType::reverse_iterator
Definition at line 89 of file Region.h.
reverse_iterator
using mlir::Region::reverse_iterator = BlockListType::reverse_iterator
Definition at line 53 of file Region.h.
Constructor & Destructor Documentation
Region() [1/2]
mlir::Region::Region () default
Referenced by cloneInto(), cloneInto(), findAncestorOpInRegion(), getParentRegion(), getSublistAccess(), isAncestor(), isProperAncestor(), mlir::Region::OpIterator::OpIterator(), and takeBody().
Region() [2/2]
Region::Region (Operation * container) explicit
Definition at line 14 of file Region.cpp.
~Region()
Region::~Region ()
Definition at line 16 of file Region.cpp.
References dropAllReferences().
Member Function Documentation
addArgument()
BlockArgument mlir::Region::addArgument (Type type, Location loc) inline
Add one value to the argument list.
Definition at line 98 of file Region.h.
References mlir::Block::addArgument(), and front().
addArguments()
iterator_range< Region::args_iterator > Region::addArguments (TypeRange types, ArrayRef< Location > locs)
Add one argument to the argument list for each type specified in the list.
locs contains the locations for each of the new arguments, and must be of equal size to types.
Definition at line 41 of file Region.cpp.
References mlir::Block::addArguments(), and front().
args_begin()
args_iterator mlir::Region::args_begin () inline
Definition at line 90 of file Region.h.
References getArguments().
args_empty()
bool mlir::Region::args_empty () inline
Definition at line 95 of file Region.h.
References getArguments().
args_end()
args_iterator mlir::Region::args_end () inline
Definition at line 91 of file Region.h.
References getArguments().
args_rbegin()
reverse_args_iterator mlir::Region::args_rbegin () inline
Definition at line 92 of file Region.h.
References getArguments().
args_rend()
reverse_args_iterator mlir::Region::args_rend () inline
Definition at line 93 of file Region.h.
References getArguments().
back()
Block & mlir::Region::back () inline
Definition at line 64 of file Region.h.
References mlir::Block::back().
Referenced by emplaceBlock(), mlir::impl::ensureRegionTerminator(), inlineIfCase(), inlineWhileCase(), mlir::transform::TransformState::mapBlockArguments(), and mlir::spirv::Deserializer::materializeSpecConstantOperation().
begin()
iterator mlir::Region::begin () inline
Definition at line 55 of file Region.h.
Referenced by buildSequenceBody(), mlir::clone(), convertOmpSections(), createExpandedGenericOp(), mlir::RewriterBase::eraseOpResults(), genCoIterateBranchNest(), hasOneBlock(), mlir::ReductionNode::initialize(), mlir::sparse_tensor::insertYieldOp(), mlir::makeRegionIsolatedFromAbove(), mlirRegionInsertOwnedBlockAfter(), mlir::gpu::WarpDistributionPattern::moveRegionToNewWarpOpAndReplaceReturns(), llvm::GraphTraits< mlir::Region * >::nodes_begin(), mlir::Region::OpIterator::OpIterator(), mlir::outlineSingleBlockRegion(), and mlir::walkAndApplyPatterns().
cloneInto() [1/2]
void Region::cloneInto (Region * dest, IRMapping & mapper)
Clone the internal blocks from this region into dest.
Clone the internal blocks from this region into dest.
Any cloned blocks are appended to the back of dest. If the mapper contains entries for block arguments, these arguments are not included in the respective cloned block.
Calling this method from multiple threads is generally safe if through the process of cloning, no new uses of 'Value's from outside the region are created. Using the mapper, it is possible to avoid adding uses to outside operands by remapping them to 'Value's owned by the caller thread.
Any cloned blocks are appended to the back of dest.
Definition at line 70 of file Region.cpp.
References cloneInto(), end(), and Region().
Referenced by mlir::Operation::clone(), mlir::acc::cloneACCRegionInto(), cloneInto(), mlir::OpBuilder::cloneRegionBefore(), mlir::sparse_tensor::insertYieldOp(), and outlineKernelFuncImpl().
cloneInto() [2/2]
void Region::cloneInto (Region * dest, Region::iterator destPos, IRMapping & mapper)
Clone this region into 'dest' before the given position in 'dest'.
Definition at line 76 of file Region.cpp.
References mlir::Block::addArgument(), mlir::Operation::CloneOptions::all(), mlir::Block, mlir::clone(), mlir::Operation::CloneOptions::cloneOperands(), mlir::Operation::CloneOptions::cloneRegions(), mlir::IRMapping::contains(), empty(), front(), mlir::Block::getArguments(), getBlocks(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), mlir::Operation::getRegions(), mlir::IRMapping::lookup(), mlir::IRMapping::map(), mlir::Block::push_back(), and Region().
dropAllReferences()
void Region::dropAllReferences ()
Drop all operand uses from operations within this region, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
Definition at line 181 of file Region.cpp.
References b.
Referenced by takeBody(), and ~Region().
emplaceBlock()
Block & mlir::Region::emplaceBlock () inline
Definition at line 46 of file Region.h.
References back(), and push_back().
Referenced by addBodyWithPayloadOp(), and mlir::sparse_tensor::LoopEmitter::enterCurrentCoIterationCase().
empty()
bool mlir::Region::empty () inline
Definition at line 60 of file Region.h.
Referenced by allocReductionVars(), mlir::sparse_tensor::buildBinaryOverlap(), mlir::sparse_tensor::Merger::buildLattices(), mlir::sparse_tensor::buildUnaryPresent(), canMakeGroupOpUniform(), checkImplementationStatus(), cloneInto(), mlir::detail::ConversionPatternRewriterImpl::convertRegionTypes(), deleteDeadness(), dominanceSort(), mlir::impl::ensureRegionTerminator(), mlir::eraseUnreachableBlocks(), getArguments(), mlir::OpTrait::SingleBlock< ConcreteType >::getBody(), mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::getPotentialTopLevelEffects(), hasOneBlock(), mlir::spirv::hasOtherMerge(), initPrivateVar(), mlir::inlineCall(), inlineConvertOmpRegions(), mlir::RewriterBase::inlineRegionBefore(), mlir::sparse_tensor::isAdmissibleBranch(), mlir::LLVM::lookupOrCreateFn(), mlir::SymbolTable::lookupSymbolIn(), mlir::ForwardDominanceIterator< SkipGraphRegion >::makeIterable(), mlir::ReverseDominanceIterator< SkipGraphRegion >::makeIterable(), mergeIdenticalBlocks(), mlirRegionGetFirstBlock(), mlir::OpBuilder::OpBuilder(), parseSingleBlockRegion(), mlir::call_interface_impl::printFunctionSignature(), printOperation(), propagateLiveness(), ShardingPropagation::runOnOperation(), mlir::transformCFGToSCF(), verifyAndGetTerminator(), verifyInitLikeSingleArgRegion(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), walkRegionBackward(), and wrapInExecuteRegion().
end()
iterator mlir::Region::end () inline
Definition at line 56 of file Region.h.
Referenced by buildGenericRegion(), cloneInto(), mlir::OpBuilder::createBlock(), createElementFPowIFunc(), createElementIPowIFunc(), hasOneBlock(), mlir::spirv::Deserializer::materializeSpecConstantOperation(), llvm::GraphTraits< mlir::Region * >::nodes_end(), mlir::Region::OpIterator::OpIterator(), mlir::LLVM::ModuleImport::processFunction(), mlir::walkAndApplyPatterns(), wrapInExecuteRegion(), and mlir::acc::wrapMultiBlockRegionWithSCFExecuteRegion().
eraseArgument()
void mlir::Region::eraseArgument (unsigned index) inline
Erase the argument at 'index' and remove it from the argument list.
Definition at line 121 of file Region.h.
References mlir::Block::eraseArgument(), and front().
findAncestorBlockInRegion()
Block * Region::findAncestorBlockInRegion (Block & block)
Returns 'block' if 'block' lies in this region, or otherwise finds the ancestor of 'block' that lies in this region.
Returns nullptr if the latter fails.
Definition at line 154 of file Region.cpp.
References mlir::Operation::getBlock(), mlir::Block::getParent(), and mlir::Block::getParentOp().
Referenced by mlir::impl::AsyncRuntimePolicyBasedRefCountingPassBase< DerivedT >::createAsyncRuntimePolicyBasedRefCountingPass.
findAncestorOpInRegion()
Operation * Region::findAncestorOpInRegion (Operation & op)
Returns 'op' if 'op' lies in this region, or otherwise finds the ancestor of 'op' that lies in this region.
Returns nullptr if the latter fails.
Definition at line 168 of file Region.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::getParentRegion(), and Region().
Referenced by findAncestorIteratorInRegion(), and findCommonAncestor().
front()
Block & mlir::Region::front () inline
Definition at line 65 of file Region.h.
References mlir::Block::front().
Referenced by addArgument(), addArguments(), mlir::acc::buildComputeRegion(), mlir::sparse_tensor::Merger::buildLattices(), mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), canMakeGroupOpUniform(), checkImplementationStatus(), checkTransformationPreconditions(), mlir::async::cloneConstantsIntoTheRegion(), cloneInto(), mlir::OpBuilder::cloneRegionBefore(), convertOmpAtomicCapture(), convertOmpAtomicCompare(), convertOmpAtomicUpdate(), mlir::detail::ConversionPatternRewriterImpl::convertRegionTypes(), deleteDeadness(), dominanceSort(), mlir::sparse_tensor::LoopEmitter::enterCurrentCoIterationCase(), eraseArgument(), mlir::eraseUnreachableBlocks(), fillIteratorLoop(), mlir::findReachableBlocks(), getArguments(), mlir::OpTrait::SingleBlock< ConcreteType >::getBody(), mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::getBodyBlock(), llvm::GraphTraits< mlir::Region * >::getEntryNode(), mlir::getOrCreateStringConstant(), mlir::getOrDefineFunction(), mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::getPotentialTopLevelEffects(), mlir::spirv::getPushConstantValue(), handleByValArgumentInit(), handleInlinedAllocas(), mlir::linalg::hasOnlyScalarElementwiseOp(), injectGpuIndexOperations(), mlir::inlineCall(), inlineConvertOmpRegions(), inlineIfCase(), mlir::RewriterBase::inlineRegionBefore(), inlineWhileCase(), insertArgument(), insertArgument(), insertCopies(), mlir::OperationFolder::insertKnownConstant(), mlir::sparse_tensor::insertYieldOp(), mlir::sparse_tensor::isAdmissibleBranch(), mlir::Block::isEntryBlock(), mlir::LLVM::lookupOrCreateFn(), mlir::SymbolTable::lookupSymbolIn(), mlir::ForwardDominanceIterator< SkipGraphRegion >::makeIterable(), mlir::makeRegionIsolatedFromAbove(), mapInitializationArgs(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::transform::detail::mergeSymbolsInto(), mlirRegionGetFirstBlock(), mlir::gpu::WarpDistributionPattern::moveRegionToNewWarpOpAndReplaceReturns(), mlir::OpBuilder::OpBuilder(), outlineKernelFuncImpl(), mlir::outlineSingleBlockRegion(), printIteratorHeader(), printLoopControl(), propagateLiveness(), replaceOpWithRegion(), ShardingPropagation::runOnOperation(), mlir::SymbolTable::SymbolTable(), mlir::transformCFGToSCF(), updateExpandedGenericOpRegion(), verifyAndGetTerminator(), verifyInitLikeSingleArgRegion(), verifyNumBlockArgs(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), verifyQuantifierRegions(), verifyRegion(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::transform::detail::verifyStructuredOpPredicateOpTrait(), and mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait().
getArgument()
BlockArgument mlir::Region::getArgument (unsigned i) inline
Definition at line 124 of file Region.h.
References getArguments().
Referenced by mlir::call_interface_impl::printFunctionSignature(), and verifyNumBlockArgs().
getArguments()
BlockArgListType mlir::Region::getArguments () inline
Definition at line 81 of file Region.h.
References empty(), front(), and mlir::Block::getArguments().
Referenced by args_begin(), args_empty(), args_end(), args_rbegin(), args_rend(), convertOmpSections(), getArgument(), getArgumentTypes(), getNumArguments(), mlir::outlineSingleBlockRegion(), mlir::irdl::RegionConstraint::verify(), and mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments().
getArgumentTypes()
auto Region::getArgumentTypes ()
Returns the argument types of the first block within the region.
Definition at line 36 of file Region.cpp.
References getArguments().
Referenced by verifyQuantifierRegions().
getBlocks()
BlockListType & mlir::Region::getBlocks () inline
Definition at line 45 of file Region.h.
Referenced by mlir::acc::buildComputeRegion(), checkTransformationPreconditions(), cloneInto(), convertOmpOpRegions(), mlir::OpBuilder::createBlock(), createSingleExitBlocksForReturnLike(), deleteDeadness(), mlir::eliminateTriviallyDeadOps(), mlir::sparse_tensor::LoopEmitter::enterCurrentCoIterationCase(), mlir::Block::erase(), mlir::detail::ConversionPatternRewriterImpl::eraseBlock(), mlir::eraseUnreachableBlocks(), generateLoopNestingName(), mlir::getBlocksSortedByDominance(), mlir::RewriterBase::inlineRegionBefore(), mlir::Block::insertAfter(), mlir::Block::insertBefore(), insertDeviceSharedMemDeallocation(), mlir::spirv::Deserializer::materializeSpecConstantOperation(), mlirLinalgFillBuiltinNamedOpRegion(), mlirRegionInsertOwnedBlockAfter(), mlir::Block::moveBefore(), mlir::gpu::WarpDistributionPattern::moveRegionToNewWarpOpAndReplaceReturns(), mlir::operator<<(), mlir::impl::OptReductionPassBase< DerivedT >::OptReductionPassBase(), printSingleBlockRegion(), mlir::Block::splitBlock(), takeBody(), transformCyclesToSCFLoops(), transformToStructuredCFBranches(), mlir::irdl::RegionConstraint::verify(), and mlir::acc::wrapMultiBlockRegionWithSCFExecuteRegion().
getContext()
MLIRContext * Region::getContext ()
Return the context this region is inserted in.
The region must have a valid parent container.
Definition at line 24 of file Region.cpp.
Referenced by mlir::applyPatternsGreedily().
getLoc()
Location Region::getLoc ()
Return a location for this region.
This is the location attached to the parent container. The region must have a valid parent container.
Definition at line 31 of file Region.cpp.
Referenced by mlir::shard::checkFullyAnnotated(), mlir::dataflow::CFGEdge::getLoc(), mlir::LatticeAnchor::getLoc(), mlir::transformCFGToSCF(), and mlir::irdl::RegionConstraint::verify().
getNumArguments()
unsigned mlir::Region::getNumArguments () inline
Definition at line 123 of file Region.h.
References getArguments().
Referenced by convertOmpSections(), and verifyNumBlockArgs().
getOps() [1/2]
iterator_range< OpIterator > mlir::Region::getOps () inline
Definition at line 172 of file Region.h.
References op_begin(), and op_end().
Referenced by applyPatterns(), mlir::ExecutionEngine::create(), mlir::irdl::createVerifier(), mlir::eliminateTriviallyDeadOps(), getAttrOrTypeVerifier(), mlir::bufferization::getGlobalFor(), mlir::OpTrait::OneRegion< ConcreteType >::getOps(), mlir::getOrCreateStringConstant(), mlir::spirv::hasOtherMerge(), mlir::bytecode::detail::IRNumberingState::IRNumberingState(), printOperation(), mlir::spirv::returnTypesMatch(), mlir::SymbolUserMap::SymbolUserMap(), and verifyInitLikeSingleArgRegion().
getOps() [2/2]
template<typename OpT> iterator_range< op_iterator< OpT > > mlir::Region::getOps () inline
Definition at line 185 of file Region.h.
References op_begin(), and op_end().
getParentOfType() [1/2]
template<typename ParentT> ParentT mlir::Region::getParentOfType () inline
Find the first parent operation of the given type, or nullptr if there is no ancestor operation.
Definition at line 205 of file Region.h.
Referenced by generateCopy(), mlir::acc::getEnclosingComputeOp(), and mlir::outlineSingleBlockRegion().
getParentOfType() [2/2]
template<typename... ParentT> std::enable_if_t<(sizeof...(ParentT) > 1), Operation * > mlir::Region::getParentOfType () inline
Definition at line 214 of file Region.h.
getParentOp()
Operation * mlir::Region::getParentOp () inline
Return the parent operation this region is attached to.
Definition at line 200 of file Region.h.
Referenced by mlir::applyOpPatternsGreedily(), mlir::applyPatternsGreedily(), canUseOpDominanceDueToRegions(), collectSymbolScopes(), collectUnderlyingAddressValues(), convertOmpOpRegions(), mlir::ControlFlowToSCFTransformation::createUnreachableTerminator(), mlir::eliminateTriviallyDeadOps(), mlir::eraseUnreachableBlocks(), generateLoopNestingName(), mlir::detail::DominanceInfoBase< IsPostDom >::getDominanceInfo(), mlir::getEnclosingRepetitiveRegion(), mlir::transform::TransformState::getHandlesForPayloadOp(), mlir::transform::TransformState::getHandlesForPayloadValue(), mlir::CallGraph::getOrAddNode(), mlir::Block::getParentOp(), getRegionNumber(), hasIsolatedRegionBetween(), inlineConvertOmpRegions(), insertCopyLoops(), isDefinedBefore(), mlir::InlinerInterface::isLegalToInline(), isRegionReachable(), isRepetitiveRegion(), isTopLevelValueOrAbove(), mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::mapBlockArguments(), mlir::mayBeGraphRegion(), mlir::dataflow::maybeReplaceWithConstant(), mlir::mayHaveSSADominance(), mlirRegionGetNextInOperation(), mlir::bufferization::ValueComparator::operator()(), mlir::operator<<(), mlir::CallGraph::print(), printRegion(), traverseRegionGraph(), mlir::irdl::RegionConstraint::verify(), mlir::wasmssa::detail::verifyLabelLevelInterface(), and mlir::dataflow::LivenessAnalysis::visitNonControlFlowArguments().
getParentRegion()
Region * Region::getParentRegion ()
Return the region containing this region or nullptr if the region is attached to a top-level operation.
Definition at line 45 of file Region.cpp.
References Region().
Referenced by findCommonAncestor(), mlir::Value::getParentRegion(), mlir::affine::hasNoInterveningEffect(), isProperAncestor(), mlir::bufferization::ValueComparator::operator()(), and mlir::visitUsedValuesDefinedAbove().
getRegionNumber()
unsigned Region::getRegionNumber ()
Return the number of this region in the parent operation.
Definition at line 62 of file Region.cpp.
References getParentOp(), and mlir::Operation::getRegions().
Referenced by genCoIterateBranchNest(), mlir::detail::DominanceInfoBase< IsPostDom >::getDominanceInfo(), mlir::getEnclosingRepetitiveRegion(), isRepetitiveRegion(), mlir::mayBeGraphRegion(), mlir::mayHaveSSADominance(), mlirRegionGetNextInOperation(), mlir::bufferization::ValueComparator::operator()(), mlir::operator<<(), printRegion(), traverseRegionGraph(), mlir::irdl::RegionConstraint::verify(), mlir::dataflow::LivenessAnalysis::visitNonControlFlowArguments(), and mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visitRegionBranchOperation().
getSublistAccess()
BlockListType Region::* mlir::Region::getSublistAccess (Block *) inline static
getSublistAccess() - Returns pointer to member of region.
Definition at line 71 of file Region.h.
References Region().
hasOneBlock()
bool mlir::Region::hasOneBlock () inline
Return true if this region has exactly one block.
Definition at line 68 of file Region.h.
References begin(), empty(), and end().
Referenced by mlir::acc::cloneACCRegionInto(), deleteDeadness(), mlir::eraseUnreachableBlocks(), mlir::smt::exportSMTLIB(), getBackwardSliceImpl(), mlir::detail::DominanceInfoBase< IsPostDom >::getDominanceInfo(), mlir::detail::DominanceInfoBase< IsPostDom >::getDomTree(), getEffectsAfter(), getEffectsBefore(), mlir::linalg::hasOnlyScalarElementwiseOp(), inlineConvertOmpRegions(), insertCopies(), lastNonTerminatorInRegion(), mergeIdenticalBlocks(), mlir::outlineSingleBlockRegion(), replaceOpWithRegion(), ShardingPropagation::runOnOperation(), mlir::transformCFGToSCF(), mlir::detail::verifyInParallelOpInterface(), mlir::detail::verifySymbolTable(), and mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait().
insertArgument() [1/2]
BlockArgument mlir::Region::insertArgument (args_iterator it, Type type, Location loc) inline
Insert one value to the position in the argument list indicated by the given iterator.
The existing arguments are shifted. The block is expected not to have predecessors.
Definition at line 105 of file Region.h.
References front(), and mlir::Block::insertArgument().
insertArgument() [2/2]
BlockArgument mlir::Region::insertArgument (unsigned index, Type type, Location loc) inline
Add one value to the argument list at the specified position.
Definition at line 116 of file Region.h.
References front(), and mlir::Block::insertArgument().
isAncestor()
bool mlir::Region::isAncestor (Region * other) inline
Return true if this region is ancestor of the other region.
A region is considered as its own ancestor, use isProperAncestor to avoid this.
Definition at line 233 of file Region.h.
References isProperAncestor(), and Region().
Referenced by mlir::affine::hasNoInterveningEffect(), isOnlyUsedByOpClauses(), mlir::makeRegionIsolatedFromAbove(), mlir::replaceAllUsesInRegionWith(), and mlir::visitUsedValuesDefinedAbove().
isProperAncestor()
bool Region::isProperAncestor (Region * other)
Return true if this region is a proper ancestor of the other region.
Definition at line 50 of file Region.cpp.
References getParentRegion(), and Region().
Referenced by diagnoseInvalidOperandDominance(), and isAncestor().
op_begin() [1/2]
OpIterator mlir::Region::op_begin () inline
Return iterators that walk the operations nested directly within this region.
Definition at line 170 of file Region.h.
Referenced by emitSwitchCase(), findOptimal(), getOps(), and op_begin().
op_begin() [2/2]
template<typename OpT> op_iterator< OpT > mlir::Region::op_begin () inline
Return iterators that walk operations of type 'T' nested directly within this region.
Definition at line 177 of file Region.h.
References op_begin(), and op_end().
op_end() [1/2]
OpIterator mlir::Region::op_end () inline
Definition at line 171 of file Region.h.
Referenced by emitSwitchCase(), findOptimal(), getOps(), op_begin(), and op_end().
op_end() [2/2]
template<typename OpT> op_iterator< OpT > mlir::Region::op_end () inline
Definition at line 181 of file Region.h.
References op_end().
push_back()
void mlir::Region::push_back (Block * block) inline
Definition at line 61 of file Region.h.
Referenced by createSingleExitBranchRegion(), emplaceBlock(), parseSingleBlockRegion(), and transformCyclesToSCFLoops().
push_front()
void mlir::Region::push_front (Block * block) inline
Definition at line 62 of file Region.h.
rbegin()
reverse_iterator mlir::Region::rbegin () inline
Definition at line 57 of file Region.h.
rend()
reverse_iterator mlir::Region::rend () inline
Definition at line 58 of file Region.h.
takeBody()
void mlir::Region::takeBody (Region & other) inline
Takes body of another region (that region will have no body after this operation completes).
The current body of this region is cleared.
Definition at line 252 of file Region.h.
References dropAllReferences(), getBlocks(), and Region().
Referenced by mlir::Operation::create(), and mlir::memoryslot::replaceWithNewResults().
viewGraph() [1/2]
void mlir::Region::viewGraph ()
Definition at line 490 of file ViewOpGraph.cpp.
References viewGraph().
viewGraph() [2/2]
void mlir::Region::viewGraph (const Twine & regionName)
Displays the CFG in a window.
This is for use from the debugger and depends on Graphviz to generate the graph. This function is defined in ViewOpGraph.cpp and only works with that target linked.
Definition at line 486 of file ViewOpGraph.cpp.
References llvmViewGraph().
Referenced by viewGraph().
walk()
template<WalkOrder Order = WalkOrder::PostOrder, typename Iterator = ForwardIterator, typename FnT, typename ArgT = detail::first_argument<FnT>, typename RetT = detail::walkResultType<FnT>> RetT mlir::Region::walk (FnT && callback) inline
Walk all nested operations, blocks or regions (including this region), depending on the type of callback.
The order in which operations, blocks or regions at the same nesting level are visited (e.g., lexicographical or reverse lexicographical order) is determined by Iterator. The walk order for enclosing operations, blocks or regions with respect to their nested ones is specified by Order (post-order by default).
A callback on a operation or block is allowed to erase that operation or block if either:
the walk is in post-order, or
the walk is in pre-order and the walk is skipped after the erasure.
See Operation::walk for more details.
Definition at line 296 of file Region.h.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), mlir::PostOrder, mlir::PreOrder, and result.
Referenced by checkTransformationPreconditions(), getBackwardSliceImpl(), mlir::wasmssa::detail::verifyConstantExpressionInterface(), verifyQuantifierRegions(), and mlir::visitUsedValuesDefinedAbove().
The documentation for this class was generated from the following files:
include/mlir/IR/Region.h
lib/IR/Region.cpp
lib/Transforms/ViewOpGraph.cpp