MLIR: mlir::presburger::IntegerRelation Class Reference
mlir::presburger::IntegerRelation Class Reference
An IntegerRelation represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
#include "mlir/Analysis/Presburger/IntegerRelation.h"
Classes
struct CountsSnapshot
The struct CountsSnapshot stores the count of each VarKind, and also of each constraint type.
Public Types
enum class Kind {
IntegerRelation , IntegerPolyhedron , FlatLinearConstraints , FlatLinearValueConstraints ,
FlatAffineValueConstraints , FlatAffineRelation
}
All derived classes of IntegerRelation.
Public Member Functions
IntegerRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a relation reserving memory for the specified number of constraints and variables.
IntegerRelation (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
virtual ~IntegerRelation ()=default
virtual Kind getKind () const
Return the kind of this IntegerRelation.
std::unique_ptr< IntegerRelation > clone () const
const PresburgerSpace & getSpace () const
Returns a reference to the underlying space.
void setSpace (const PresburgerSpace &oSpace)
Set the space to oSpace, which should have the same number of ids as the current space.
void setSpaceExceptLocals (const PresburgerSpace &oSpace)
Set the space to oSpace, which should not have any local ids.
void setId (VarKind kind, unsigned i, Identifier id)
Set the identifier for the ith variable of the specified kind of the IntegerRelation's PresburgerSpace.
void resetIds ()
ArrayRef< Identifier > getIds (VarKind kind)
Get the identifiers for the variables of specified varKind.
PresburgerSpace getSpaceWithoutLocals () const
Returns a copy of the space without locals.
void append (const IntegerRelation &other)
Appends constraints from other into this.
int findEqualityToConstant (unsigned pos, bool symbolic=false) const
Finds an equality that equates the specified variable to a constant.
IntegerRelation intersect (IntegerRelation other) const
Return the intersection of the two relations.
bool isEqual (const IntegerRelation &other) const
Return whether this and other are equal.
bool isObviouslyEqual (const IntegerRelation &other) const
Perform a quick equality check on this and other.
bool isSubsetOf (const IntegerRelation &other) const
Return whether this is a subset of the given IntegerRelation.
DynamicAPInt atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t atEq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
DynamicAPInt & atEq (unsigned i, unsigned j)
DynamicAPInt atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t atIneq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
DynamicAPInt & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
int64_t atConstraint64 (unsigned i, unsigned j) const
Unified indexing into the constraints.
DynamicAPInt & atConstraint (unsigned i, unsigned j)
unsigned getNumDomainVars () const
unsigned getNumRangeVars () const
unsigned getNumSymbolVars () const
unsigned getNumLocalVars () const
unsigned getNumDimVars () const
unsigned getNumDimAndSymbolVars () const
unsigned getNumVars () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< DynamicAPInt > getEquality (unsigned idx) const
ArrayRef< DynamicAPInt > getInequality (unsigned idx) const
SmallVector< int64_t, 8 > getEquality64 (unsigned idx) const
The same, but casts to int64_t.
SmallVector< int64_t, 8 > getInequality64 (unsigned idx) const
IntMatrix getInequalities () const
unsigned getNumVarKind (VarKind kind) const
Get the number of vars of the specified kind.
unsigned getVarKindOffset (VarKind kind) const
Return the index at which the specified kind of vars starts.
unsigned getVarKindEnd (VarKind kind) const
Return the index at Which the specified kind of vars ends.
auto iterVarKind (VarKind kind)
Return an interator over the variables of the specified kind starting at the relevant offset.
unsigned getVarKindOverlap (VarKind kind, unsigned varStart, unsigned varLimit) const
Get the number of elements of the specified kind in the range [varStart, varLimit).
VarKind getVarKindAt (unsigned pos) const
Return the VarKind of the var at the specified position.
CountsSnapshot getCounts () const
void truncate (const CountsSnapshot &counts)
virtual unsigned insertVar (VarKind kind, unsigned pos, unsigned num=1)
Insert num variables of the specified kind at position pos.
unsigned appendVar (VarKind kind, unsigned num=1)
Append num variables of the specified kind after the last variable of that kind.
void addInequality (ArrayRef< DynamicAPInt > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addInequality (ArrayRef< int64_t > inEq)
void addEquality (ArrayRef< DynamicAPInt > eq)
Adds an equality from the coefficients specified in eq.
void addEquality (ArrayRef< int64_t > eq)
virtual void eliminateRedundantLocalVar (unsigned posA, unsigned posB)
Eliminate the posB^th local variable, replacing every instance of it with the posA^th local variable.
void removeVar (VarKind kind, unsigned pos)
Removes variables of the specified kind with the specified pos (or within the specified range) from the system.
virtual void removeVarRange (VarKind kind, unsigned varStart, unsigned varLimit)
void removeVar (unsigned pos)
Removes the specified variable from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeConstraint (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
MaybeOptimum< SmallVector< Fraction, 8 > > findRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
MaybeOptimum< SmallVector< DynamicAPInt, 8 > > findIntegerLexMin () const
Same as above, but returns lexicographically minimal integer point.
virtual void swapVar (unsigned posA, unsigned posB)
Swap the posA^th variable with the posB^th variable.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< DynamicAPInt > values)
Sets the values.size() variables starting at pos to the specified values and removes them.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
virtual void clearAndCopyFrom (const IntegerRelation &other)
Replaces the contents of this IntegerRelation with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the variable at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all variables, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isObviouslyEmpty () const
Performs GCD checks and invalid constraint checks.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
IntMatrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
std::optional< SmallVector< DynamicAPInt, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
std::optional< DynamicAPInt > computeVolume () const
Compute an overapproximation of the number of integer points in the relation.
bool containsPoint (ArrayRef< DynamicAPInt > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
bool containsPoint (ArrayRef< int64_t > point) const
std::optional< SmallVector< DynamicAPInt, 8 > > containsPointNoLocal (ArrayRef< DynamicAPInt > point) const
Given the values of non-local vars, return a satisfying assignment to the local if one exists, or an empty optional otherwise.
std::optional< SmallVector< DynamicAPInt, 8 > > containsPointNoLocal (ArrayRef< int64_t > point) const
DivisionRepr getLocalReprs (std::vector< MaybeLocalRepr > *repr=nullptr) const
Returns a DivisonRepr representing the division representation of local variables in the constraint system.
void addBound (BoundType type, unsigned pos, const DynamicAPInt &value)
Adds a constant bound for the specified variable.
void addBound (BoundType type, unsigned pos, int64_t value)
void addBound (BoundType type, ArrayRef< DynamicAPInt > expr, const DynamicAPInt &value)
Adds a constant bound for the specified expression.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
unsigned addLocalFloorDiv (ArrayRef< DynamicAPInt > dividend, const DynamicAPInt &divisor)
Adds a new local variable as the floordiv of an affine function of other variables, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
unsigned addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
unsigned addLocalModulo (ArrayRef< DynamicAPInt > exprs, const DynamicAPInt &modulus)
Adds a new local variable as the modulus of an affine function of other variables, the coefficients of which are provided in exprs.
unsigned addLocalModulo (ArrayRef< int64_t > exprs, int64_t modulus)
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num variables starting at position pos.
void projectOut (unsigned pos)
void pruneOrthogonalConstraints (unsigned pos)
The function removes some constraints that do not impose any bound on the specified variable.
LogicalResult constantFoldVar (unsigned pos)
Tries to fold the specified variable to a constant using a trivial equality detection; if successful, the constant is substituted for the variable everywhere in the constraint system and then removed from the system.
void constantFoldVarRange (unsigned pos, unsigned num)
This method calls constantFoldVar for the specified range of variables, num variables starting at position pos.
LogicalResult unionBoundingBox (const IntegerRelation &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
std::optional< DynamicAPInt > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< DynamicAPInt > *lb=nullptr, DynamicAPInt *boundFloorDivisor=nullptr, SmallVectorImpl< DynamicAPInt > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified variable (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the variable.
std::optional< int64_t > getConstantBoundOnDimSize64 (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
The same, but casts to int64_t.
std::optional< DynamicAPInt > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th variable if there is one; std::nullopt otherwise.
std::optional< int64_t > getConstantBound64 (BoundType type, unsigned pos) const
The same, but casts to int64_t.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) variables in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of variables.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void removeDuplicateDivs ()
void simplify ()
Simplify the constraint system by removing canonicalizing constraints and removing redundant constraints.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind, unsigned pos)
Converts variables of kind srcKind in the range [varStart, varLimit) to variables of kind dstKind.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind)
void convertToLocal (VarKind kind, unsigned varStart, unsigned varLimit)
void mergeAndAlignSymbols (IntegerRelation &other)
Merge and align symbol variables of this and other with respect to identifiers.
unsigned mergeLocalVars (IntegerRelation &other)
Adds additional local vars to the sets such that they both have the union of the local vars in each set, without changing the set of points that lie in this and other.
bool hasOnlyDivLocals () const
Check whether all local ids have a division representation.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
IntegerPolyhedron getDomainSet () const
Return a set corresponding to all points in the domain of the relation.
IntegerPolyhedron getRangeSet () const
Return a set corresponding to all points in the range of the relation.
void intersectDomain (const IntegerPolyhedron &poly)
Intersect the given poly with the domain in-place.
void intersectRange (const IntegerPolyhedron &poly)
Intersect the given poly with the range in-place.
void inverse ()
Invert the relation i.e., swap its domain and range.
void compose (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void applyDomain (const IntegerRelation &rel)
Given a relation rel, apply the relation to the domain of this relation.
void applyRange (const IntegerRelation &rel)
Given a relation rel, apply the relation to the range of this relation.
IntegerRelation rangeProduct (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void mergeAndCompose (const IntegerRelation &other)
Given a relation other: (A -> B), this operation merges the symbol and local variables and then takes the composition of other on this: (B -> / C).
PresburgerRelation computeReprWithOnlyDivLocals () const
Compute an equivalent representation of the same set, such that all local vars in all disjuncts have division representations.
SymbolicLexOpt findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the relation.
SymbolicLexOpt findSymbolicIntegerLexMax () const
Same as findSymbolicIntegerLexMin but produces lexmax instead of lexmin.
std::optional< unsigned > findConstraintWithNonZeroAt (unsigned colIdx, bool isEq) const
Finds a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
PresburgerRelation subtract (const PresburgerRelation &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
void removeTrivialEqualities ()
bool isFullDim ()
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static IntegerRelation getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static IntegerRelation getEmpty (const PresburgerSpace &space)
Return an empty system containing an invalid equation 0 = 1.
static bool classof (const IntegerRelation *cst)
Protected Member Functions
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
std::optional< DynamicAPInt > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound if isLower is true, and the upper bound if isLower is false.
template<bool isLower>
std::optional< int64_t > computeConstantLowerOrUpperBound64 (unsigned pos)
The same, but casts to int64_t.
LogicalResult gaussianEliminateVar (unsigned position)
Eliminates a single variable at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateVars (unsigned posStart, unsigned posLimit)
Eliminates variables from equality and inequality constraints in column range [posStart, posLimit).
bool gaussianEliminate ()
Perform a Gaussian elimination operation to reduce all equations to standard form.
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the variable at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that variable.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
bool removeDuplicateConstraints ()
Checks for identical inequalities and eliminates redundant inequalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various variable counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
virtual void printSpace (raw_ostream &os) const
Prints the number of constraints, dimensions, symbols and locals in the IntegerRelation.
void removeVarRange (unsigned varStart, unsigned varLimit)
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
void truncateVarKind (VarKind kind, unsigned num)
Truncate the vars of the specified kind to the specified number by dropping some vars at the end.
void truncateVarKind (VarKind kind, const CountsSnapshot &counts)
Truncate the vars to the number in the space of the specified CountsSnapshot.
Protected Attributes
PresburgerSpace space
IntMatrix equalities
Coefficients of affine equalities (in == 0 form).
IntMatrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
An IntegerRelation represents the set of points from a PresburgerSpace that satisfy a list of affine constraints.
Affine constraints can be inequalities or equalities in the form:
Inequality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n >= 0 Equality : c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n == 0
where c_0, c_1, ..., c_n are integers and n is the total number of variables in the space.
Such a relation corresponds to the set of integer points lying in a convex polyhedron. For example, consider the relation: (x) -> (y) : (1 <= x <= 7, x = 2y) These can be thought of as points in the polyhedron: (x, y) : (1 <= x <= 7, x = 2y) This relation contains the pairs (2, 1), (4, 2), and (6, 3).
Since IntegerRelation makes a distinction between dimensions, VarKind::Range and VarKind::Domain should be used to refer to dimension variables.
Definition at line 65 of file IntegerRelation.h.
Member Enumeration Documentation
Kind
enum class mlir::presburger::IntegerRelation::Kind strong
All derived classes of IntegerRelation.
Enumerator
IntegerRelation
IntegerPolyhedron
FlatLinearConstraints
FlatLinearValueConstraints
FlatAffineValueConstraints
FlatAffineRelation
Definition at line 68 of file IntegerRelation.h.
Constructor & Destructor Documentation
IntegerRelation() [1/2]
mlir::presburger::IntegerRelation::IntegerRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace & space) inline
Constructs a relation reserving memory for the specified number of constraints and variables.
Definition at line 79 of file IntegerRelation.h.
References equalities, getNumVars(), inequalities, and space.
Referenced by append(), applyDomain(), applyRange(), mlir::affine::FlatAffineRelation::classof(), mlir::affine::FlatAffineValueConstraints::classof(), mlir::FlatLinearValueConstraints::classof(), mlir::presburger::IntegerPolyhedron::classof(), classof(), clearAndCopyFrom(), compose(), computeReprWithOnlyDivLocals(), containsPointNoLocal(), findIntegerSample(), findSymbolicIntegerLexMax(), fourierMotzkinEliminate(), getDomainSet(), getEmpty(), getRangeSet(), getUniverse(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), IntegerRelation(), IntegerRelation, intersect(), intersectDomain(), intersectRange(), isEmpty(), isEqual(), isObviouslyEqual(), isSubsetOf(), mergeAndAlignSymbols(), mergeAndCompose(), mergeLocalVars(), rangeProduct(), removeRedundantInequalities(), and unionBoundingBox().
IntegerRelation() [2/2]
mlir::presburger::IntegerRelation::IntegerRelation (const PresburgerSpace & space) inline explicit
Constructs a relation with the specified number of dimensions and symbols.
Definition at line 90 of file IntegerRelation.h.
References getNumVars(), IntegerRelation(), and space.
~IntegerRelation()
virtual mlir::presburger::IntegerRelation::~IntegerRelation () virtual default
Member Function Documentation
addBound() [1/4]
void IntegerRelation::addBound (BoundType type, ArrayRef< DynamicAPInt > expr, const DynamicAPInt & value)
Adds a constant bound for the specified expression.
Definition at line 1515 of file IntegerRelation.cpp.
References mlir::presburger::EQ, getNumCols(), inequalities, and mlir::presburger::LB.
addBound() [2/4]
void mlir::presburger::IntegerRelation::addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value) inline
Definition at line 488 of file IntegerRelation.h.
References addBound(), and mlir::presburger::getDynamicAPIntVec().
addBound() [3/4]
void IntegerRelation::addBound (BoundType type, unsigned pos, const DynamicAPInt & value)
Adds a constant bound for the specified variable.
Definition at line 1500 of file IntegerRelation.cpp.
References mlir::presburger::EQ, equalities, getNumCols(), inequalities, and mlir::presburger::LB.
Referenced by addBound(), addBound(), and mlir::presburger::MultiAffineFunction::getLexSet().
addBound() [4/4]
void mlir::presburger::IntegerRelation::addBound (BoundType type, unsigned pos, int64_t value) inline
Definition at line 481 of file IntegerRelation.h.
References addBound().
addEquality() [1/2]
void IntegerRelation::addEquality (ArrayRef< DynamicAPInt > eq)
Adds an equality from the coefficients specified in eq.
Definition at line 364 of file IntegerRelation.cpp.
References equalities, and getNumCols().
Referenced by mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::FlatLinearConstraints::addBound(), addEquality(), addLocalModulo(), addOrderingConstraints(), append(), mlir::FlatLinearConstraints::composeMatchingMap(), computeDirectionVector(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), fourierMotzkinEliminate(), getCommonConstraints(), mlir::presburger::MultiAffineFunction::getLexSet(), mlir::affine::getRelationFromMap(), and removeDuplicateConstraints().
addEquality() [2/2]
void mlir::presburger::IntegerRelation::addEquality (ArrayRef< int64_t > eq) inline
Definition at line 347 of file IntegerRelation.h.
References addEquality(), and mlir::presburger::getDynamicAPIntVec().
addInequality() [1/2]
void IntegerRelation::addInequality (ArrayRef< DynamicAPInt > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
Definition at line 371 of file IntegerRelation.cpp.
References getNumCols(), and inequalities.
Referenced by mlir::FlatLinearConstraints::addBound(), addDivisionConstraints(), addInequality(), addLocalFloorDiv(), mlir::scf::addLoopRangeConstraints(), addOrderingConstraints(), append(), mlir::presburger::detail::computePolytopeGeneratingFunction(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), fourierMotzkinEliminate(), getCommonConstraints(), mlir::presburger::detail::getDual(), mlir::presburger::MultiAffineFunction::getLexSet(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::scf::rewritePeeledMinMaxOp(), mlir::affine::simplifyConstrainedMinMaxOp(), and unionBoundingBox().
addInequality() [2/2]
void mlir::presburger::IntegerRelation::addInequality (ArrayRef< int64_t > inEq) inline
Definition at line 342 of file IntegerRelation.h.
References addInequality(), and mlir::presburger::getDynamicAPIntVec().
addLocalFloorDiv() [1/2]
unsigned IntegerRelation::addLocalFloorDiv (ArrayRef< DynamicAPInt > dividend, const DynamicAPInt & divisor)
Adds a new local variable as the floordiv of an affine function of other variables, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
Adds a new local variable as the floordiv of an affine function of other variables, the coefficients of which are provided in 'dividend' and with respect to a positive constant 'divisor'.
Two constraints are added to the system to capture equivalence with the floordiv: q = dividend floordiv c <=> c*q <= dividend <= c*q + c - 1. Returns the column position of the new local variable.
Two constraints are added to the system to capture equivalence with the floordiv. q = expr floordiv c <=> c*q <= expr <= c*q + c - 1. Returns the column position of the new local variable.
Definition at line 1532 of file IntegerRelation.cpp.
References addInequality(), appendVar(), mlir::presburger::getDivLowerBound(), mlir::presburger::getDivUpperBound(), getNumCols(), and mlir::presburger::Local.
Referenced by mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), addLocalFloorDiv(), and addLocalModulo().
addLocalFloorDiv() [2/2]
unsigned mlir::presburger::IntegerRelation::addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor) inline
Definition at line 500 of file IntegerRelation.h.
References addLocalFloorDiv(), and mlir::presburger::getDynamicAPIntVec().
addLocalModulo() [1/2]
unsigned IntegerRelation::addLocalModulo (ArrayRef< DynamicAPInt > exprs, const DynamicAPInt & modulus)
Adds a new local variable as the modulus of an affine function of other variables, the coefficients of which are provided in exprs.
The modulus is with respect to a positive constant modulus. The function returns the absolute index of the new local variable representing the result of the modulus operation. Two new local variables are added to the system, one representing the floor div with respect to the modulus and one representing the mod. Three constraints are added to the system to capture the equivalance. The first two are required to compute the result of the floor division q, and the third computes the equality relation: result = exprs - modulus * q.
Add a local variable for q = expr floordiv modulus
Add a local var to represent the result
Insert the two new locals before the constant Add locals that correspond to q and result to compute 0 = (expr - modulus * q) - result
Definition at line 1548 of file IntegerRelation.cpp.
References addEquality(), addLocalFloorDiv(), appendVar(), getNumCols(), and mlir::presburger::Local.
Referenced by addLocalModulo().
addLocalModulo() [2/2]
unsigned mlir::presburger::IntegerRelation::addLocalModulo (ArrayRef< int64_t > exprs, int64_t modulus) inline
Definition at line 517 of file IntegerRelation.h.
References addLocalModulo(), and mlir::presburger::getDynamicAPIntVec().
append()
void IntegerRelation::append (const IntegerRelation & other)
Appends constraints from other into this.
This is equivalent to an intersection with no simplification of any sort attempted.
Definition at line 81 of file IntegerRelation.cpp.
References addEquality(), addInequality(), equalities, getEquality(), getInequality(), getNumEqualities(), getNumInequalities(), getSpace(), inequalities, IntegerRelation(), and space.
Referenced by mlir::affine::FlatAffineValueConstraints::addAffineIfOpDomain(), mlir::affine::FlatAffineRelation::compose(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearConstraints::flattenAlignedMapAndMergeLocals(), mlir::affine::MemRefAccess::getAccessRelation(), intersectDomain(), intersectRange(), and unionBoundingBox().
appendVar()
unsigned IntegerRelation::appendVar (VarKind kind, unsigned num = 1)
Append num variables of the specified kind after the last variable of that kind.
The coefficient columns corresponding to the added variables are initialized to zero. Return the absolute column position (i.e., not relative to the kind of variable) of the first appended variable.
Definition at line 359 of file IntegerRelation.cpp.
References getNumVarKind(), and insertVar().
Referenced by addLocalFloorDiv(), addLocalModulo(), mlir::FlatLinearConstraints::appendDimVar(), mlir::FlatLinearConstraints::appendLocalVar(), mlir::FlatLinearConstraints::appendSymbolVar(), compose(), mlir::affine::MemRefAccess::getAccessRelation(), intersectDomain(), and intersectRange().
applyDomain()
void IntegerRelation::applyDomain (const IntegerRelation & rel)
Given a relation rel, apply the relation to the domain of this relation.
R1: i -> j : (0 <= i < 2, j = i) R2: i -> k : (k = i floordiv 2) R3: k -> j : (0 <= k < 1, 2k <= j <= 2k + 1)
R1 = {(0, 0), (1, 1)}. R2 maps both 0 and 1 to 0. So R3 = {(0, 0), (0, 1)}.
Formally, R1.applyDomain(R2) = R2.inverse().compose(R1).
Definition at line 2578 of file IntegerRelation.cpp.
References compose(), IntegerRelation(), and inverse().
applyRange()
void IntegerRelation::applyRange (const IntegerRelation & rel)
Given a relation rel, apply the relation to the range of this relation.
Formally, R1.applyRange(R2) is the same as R1.compose(R2) but we provide this for uniformity with applyDomain.
Definition at line 2584 of file IntegerRelation.cpp.
References compose(), and IntegerRelation().
atConstraint()
DynamicAPInt & mlir::presburger::IntegerRelation::atConstraint (unsigned i, unsigned j) inline
Definition at line 220 of file IntegerRelation.h.
References atEq(), atIneq(), getNumConstraints(), and getNumInequalities().
Referenced by pruneOrthogonalConstraints().
atConstraint64()
int64_t mlir::presburger::IntegerRelation::atConstraint64 (unsigned i, unsigned j) const inline
Unified indexing into the constraints.
Index into the inequalities if i < getNumInequalities() and into the equalities otherwise.
Definition at line 215 of file IntegerRelation.h.
References atEq64(), atIneq64(), getNumConstraints(), and getNumInequalities().
atEq() [1/2]
DynamicAPInt & mlir::presburger::IntegerRelation::atEq (unsigned i, unsigned j) inline
Definition at line 193 of file IntegerRelation.h.
References equalities.
atEq() [2/2]
DynamicAPInt mlir::presburger::IntegerRelation::atEq (unsigned i, unsigned j) const inline
Returns the value at the specified equality row and column.
Definition at line 185 of file IntegerRelation.h.
References equalities.
Referenced by atConstraint(), computeConstantLowerOrUpperBound(), constantFoldVar(), eliminateFromConstraint(), findConstraintWithNonZeroAt(), findEqualityToConstant(), findEqualityWithNonZeroAfterRow(), findSymbolicIntegerLexMax(), fourierMotzkinEliminate(), gaussianEliminate(), getBoundedDirections(), getConstantBoundOnDimSize(), getDivRepr(), getIndependentConstraints(), getLowerAndUpperBoundIndices(), hasInvalidConstraint(), isEmptyByGCDTest(), isHyperRectangular(), isObviouslyEqual(), print(), and removeRedundantLocalVars().
atEq64()
int64_t mlir::presburger::IntegerRelation::atEq64 (unsigned i, unsigned j) const inline
The same, but casts to int64_t.
This is unsafe and will assert-fail if the value does not fit in an int64_t.
Definition at line 190 of file IntegerRelation.h.
References equalities.
Referenced by atConstraint64(), detectAsExpr(), detectAsMod(), and mlir::affine::FlatAffineValueConstraints::FlatLinearValueConstraints().
atIneq() [1/2]
DynamicAPInt & mlir::presburger::IntegerRelation::atIneq (unsigned i, unsigned j) inline
Definition at line 205 of file IntegerRelation.h.
References inequalities.
atIneq() [2/2]
DynamicAPInt mlir::presburger::IntegerRelation::atIneq (unsigned i, unsigned j) const inline
Returns the value at the specified inequality row and column.
Definition at line 196 of file IntegerRelation.h.
References inequalities.
Referenced by atConstraint(), computeConstantLowerOrUpperBound(), createSeparationCondition(), eliminateFromConstraint(), findConstraintWithNonZeroAt(), findIntegerSample(), findSymbolicIntegerLexMax(), fourierMotzkinEliminate(), gcdTightenInequalities(), getBestVarToEliminate(), getBoundedDirections(), getConstantBoundOnDimSize(), getDivRepr(), mlir::presburger::detail::getDual(), getIndependentConstraints(), getLowerAndUpperBoundIndices(), hasInvalidConstraint(), isHyperRectangular(), isObviouslyEqual(), print(), removeDuplicateConstraints(), removeRedundantInequalities(), and removeTrivialRedundancy().
atIneq64()
int64_t mlir::presburger::IntegerRelation::atIneq64 (unsigned i, unsigned j) const inline
The same, but casts to int64_t.
This is unsafe and will assert-fail if the value does not fit in an int64_t.
Definition at line 202 of file IntegerRelation.h.
References inequalities.
Referenced by atConstraint64(), and mlir::FlatLinearConstraints::getConstantBoundOnDimSize().
classof()
bool mlir::presburger::IntegerRelation::classof (const IntegerRelation * cst) inline static
Definition at line 115 of file IntegerRelation.h.
References IntegerRelation().
clearAndCopyFrom()
void IntegerRelation::clearAndCopyFrom (const IntegerRelation & other) virtual
Replaces the contents of this IntegerRelation with other.
Definition at line 567 of file IntegerRelation.cpp.
References IntegerRelation().
Referenced by fourierMotzkinEliminate(), and getFlattenedAffineExprs().
clearConstraints()
void IntegerRelation::clearConstraints ()
Removes all equalities and inequalities.
Definition at line 483 of file IntegerRelation.cpp.
References equalities, and inequalities.
Referenced by unionBoundingBox().
clone()
std::unique_ptr< IntegerRelation > IntegerRelation::clone () const
Definition at line 46 of file IntegerRelation.cpp.
compose()
void IntegerRelation::compose (const IntegerRelation & rel)
Let the relation this be R1, and the relation rel be R2.
Modifies R1 to be the composition of R1 and R2: R1;R2.
Formally, if R1: A -> B, and R2: B -> C, then this function returns a relation R3: A -> C such that a point (a, c) belongs to R3 iff there exists b such that (a, b) is in R1 and, (b, c) is in R2.
Definition at line 2552 of file IntegerRelation.cpp.
References appendVar(), convertVarKind(), mlir::presburger::Domain, getDomainSet(), getNumRangeVars(), getRangeSet(), getSpace(), IntegerPolyhedron, IntegerRelation(), intersectRange(), mlir::presburger::Local, and mlir::presburger::Range.
Referenced by applyDomain(), applyRange(), and mlir::presburger::PresburgerRelation::compose().
computeConstantLowerOrUpperBound()
template<bool isLower> std::optional< DynamicAPInt > IntegerRelation::computeConstantLowerOrUpperBound (unsigned pos) protected
Returns the constant lower bound if isLower is true, and the upper bound if isLower is false.
Definition at line 1801 of file IntegerRelation.cpp.
References atEq(), atIneq(), findEqualityToConstant(), getNumCols(), getNumInequalities(), getNumVars(), projectOut(), and pruneOrthogonalConstraints().
Referenced by computeConstantLowerOrUpperBound64().
computeConstantLowerOrUpperBound64()
template<bool isLower> std::optional< int64_t > mlir::presburger::IntegerRelation::computeConstantLowerOrUpperBound64 (unsigned pos) inline protected
The same, but casts to int64_t.
This is unsafe and will assert-fail if the value does not fit in an int64_t.
Definition at line 868 of file IntegerRelation.h.
References computeConstantLowerOrUpperBound().
computeReprWithOnlyDivLocals()
PresburgerRelation IntegerRelation::computeReprWithOnlyDivLocals () const
Compute an equivalent representation of the same set, such that all local vars in all disjuncts have division representations.
This representation may involve local vars that correspond to divisions, and may also be a union of convex disjuncts.
Definition at line 219 of file IntegerRelation.cpp.
References mlir::presburger::SymbolicLexSimplex::computeSymbolicIntegerLexMin(), copy(), mlir::presburger::PWMAFunction::getDomain(), getNumLocalVars(), mlir::presburger::PresburgerSpace::getSetSpace(), getSpace(), IntegerPolyhedron, IntegerRelation(), mlir::presburger::SymbolicLexOpt::lexopt, mlir::presburger::Local, result, space, mlir::presburger::SymbolicLexOpt::unboundedDomain, and mlir::presburger::PresburgerSet::unionSet().
computeVolume()
std::optional< DynamicAPInt > IntegerRelation::computeVolume () const
Compute an overapproximation of the number of integer points in the relation.
Symbol vars currently not supported. If the computed overapproximation is infinite, an empty optional is returned.
Definition at line 1258 of file IntegerRelation.cpp.
References mlir::presburger::Simplex::computeIntegerBounds(), getNumDimAndSymbolVars(), getNumSymbolVars(), getNumVars(), mlir::presburger::SimplexBase::isEmpty(), max(), and min().
constantFoldVar()
LogicalResult IntegerRelation::constantFoldVar (unsigned pos)
Tries to fold the specified variable to a constant using a trivial equality detection; if successful, the constant is substituted for the variable everywhere in the constraint system and then removed from the system.
Definition at line 1593 of file IntegerRelation.cpp.
References atEq(), findEqualityToConstant(), getNumCols(), getNumVars(), setAndEliminate(), and success().
Referenced by constantFoldVarRange().
constantFoldVarRange()
void IntegerRelation::constantFoldVarRange (unsigned pos, unsigned num)
This method calls constantFoldVar for the specified range of variables, num variables starting at position pos.
Definition at line 1606 of file IntegerRelation.cpp.
References constantFoldVar().
containsPoint() [1/2]
bool IntegerRelation::containsPoint (ArrayRef< DynamicAPInt > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
A point satisfies an equality iff the value of the equality at the expression is zero, and it satisfies an inequality iff the value of the inequality at that point is non-negative.
Takes the values of all vars including locals.
Definition at line 991 of file IntegerRelation.cpp.
References getEquality(), getInequality(), getNumEqualities(), getNumInequalities(), and valueAt().
Referenced by containsPoint(), and findIntegerSample().
containsPoint() [2/2]
bool mlir::presburger::IntegerRelation::containsPoint (ArrayRef< int64_t > point) const inline
Definition at line 456 of file IntegerRelation.h.
References containsPoint(), and mlir::presburger::getDynamicAPIntVec().
containsPointNoLocal() [1/2]
std::optional< SmallVector< DynamicAPInt, 8 > > IntegerRelation::containsPointNoLocal (ArrayRef< DynamicAPInt > point) const
Given the values of non-local vars, return a satisfying assignment to the local if one exists, or an empty optional otherwise.
Just substitute the values given and check if an integer sample exists for the local vars.
TODO: this could be made more efficient by handling divisions separately. Instead of finding an integer sample over all the locals, we can first compute the values of the locals that have division representations and only use the integer emptiness check for the locals that don't have this. Handling this correctly requires ordering the divs, though.
Definition at line 1012 of file IntegerRelation.cpp.
References copy(), getNumLocalVars(), getNumVars(), getVarKindOffset(), IntegerRelation(), and mlir::presburger::Local.
Referenced by mlir::presburger::PresburgerRelation::containsPoint(), and containsPointNoLocal().
containsPointNoLocal() [2/2]
std::optional< SmallVector< DynamicAPInt, 8 > > mlir::presburger::IntegerRelation::containsPointNoLocal (ArrayRef< int64_t > point) const inline
Definition at line 464 of file IntegerRelation.h.
References containsPointNoLocal(), and mlir::presburger::getDynamicAPIntVec().
convertToLocal()
void mlir::presburger::IntegerRelation::convertToLocal (VarKind kind, unsigned varStart, unsigned varLimit) inline
Definition at line 685 of file IntegerRelation.h.
References convertVarKind(), and mlir::presburger::Local.
Referenced by mlir::affine::FlatAffineRelation::compose(), mlir::affine::FlatAffineRelation::getDomainSet(), mlir::affine::FlatAffineRelation::getRangeSet(), and mergeAndCompose().
convertVarKind() [1/2]
void mlir::presburger::IntegerRelation::convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind) inline
Definition at line 680 of file IntegerRelation.h.
References convertVarKind(), and getNumVarKind().
convertVarKind() [2/2]
void IntegerRelation::convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind, unsigned pos)
Converts variables of kind srcKind in the range [varStart, varLimit) to variables of kind dstKind.
If pos is given, the variables are placed at position pos of dstKind, otherwise they are placed after all the other variables of kind dstKind. The internal ordering among the moved variables is preserved.
Definition at line 1479 of file IntegerRelation.cpp.
References equalities, getNumVarKind(), getVarKindOffset(), inequalities, and space.
Referenced by mlir::affine::checkMemrefAccessDependence(), compose(), convertToLocal(), convertVarKind(), mlir::affine::MemRefAccess::getAccessRelation(), getDomainSet(), getRangeSet(), and inverse().
dump()
void IntegerRelation::dump () const
Definition at line 2740 of file IntegerRelation.cpp.
References print().
Referenced by mlir::affine::checkMemrefAccessDependence(), fourierMotzkinEliminate(), and mlir::FlatLinearConstraints::getAsIntegerSet().
eliminateRedundantLocalVar()
void IntegerRelation::eliminateRedundantLocalVar (unsigned posA, unsigned posB) virtual
Eliminate the posB^th local variable, replacing every instance of it with the posA^th local variable.
This should be used when the two local variables are known to always take the same values.
Definition at line 1314 of file IntegerRelation.cpp.
References equalities, getNumLocalVars(), getVarKindOffset(), inequalities, mlir::presburger::Local, and removeVar().
Referenced by mergeLocalVars(), and removeDuplicateDivs().
findConstraintWithNonZeroAt()
std::optional< unsigned > IntegerRelation::findConstraintWithNonZeroAt (unsigned colIdx, bool isEq) const
Finds a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
Returns the position of the row if it was found or none otherwise.
Definition at line 572 of file IntegerRelation.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), and getNumInequalities().
Referenced by computeUnknownVars(), gaussianEliminateVars(), and isColZero().
findEqualityToConstant()
int IntegerRelation::findEqualityToConstant (unsigned pos, bool symbolic = false) const
Finds an equality that equates the specified variable to a constant.
Returns the position of the equality row. If 'symbolic' is set to true, symbols are also treated like a constant, i.e., an affine function of the symbols is also treated like a constant. Returns -1 if such an equality could not be found.
Definition at line 1569 of file IntegerRelation.cpp.
References atEq(), getNumDimVars(), getNumEqualities(), and getNumVars().
Referenced by computeConstantLowerOrUpperBound(), constantFoldVar(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), and getConstantBoundOnDimSize().
findIntegerLexMin()
MaybeOptimum< SmallVector< DynamicAPInt, 8 > > IntegerRelation::findIntegerLexMin () const
Same as above, but returns lexicographically minimal integer point.
Note: this should be used only when the lexmin is really required. For a generic integer sampling operation, findIntegerSample is more robust and should be preferred. Note that Domain is minimized first, then range.
Definition at line 158 of file IntegerRelation.cpp.
References mlir::presburger::LexSimplex::findIntegerLexMin(), mlir::presburger::MaybeOptimum< T >::getKind(), getNumDimAndSymbolVars(), getNumSymbolVars(), getNumVars(), and mlir::presburger::MaybeOptimum< T >::isBounded().
findIntegerSample()
std::optional< SmallVector< DynamicAPInt, 8 > > IntegerRelation::findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
Let this set be S.
Returns an integer sample point if one exists, or an empty Optional otherwise. The returned value also includes values of local ids.
If S is bounded then we directly call into the GBR sampling algorithm. Otherwise, there are some unbounded directions, i.e., vectors v such that S extends to infinity along v or -v. In this case we use an algorithm described in the integer set library (isl) manual and used by the isl_set_sample function in that library. The algorithm is:
1) Apply a unimodular transform T to S to obtain S*T, such that all dimensions in which S*T is bounded lie in the linear span of a prefix of the dimensions.
2) Construct a set B by removing all constraints that involve the unbounded dimensions and then deleting the unbounded dimensions. Note that B is a Bounded set.
3) Try to obtain a sample from B using the GBR sampling algorithm. If no sample is found, return that S is empty.
4) Otherwise, substitute the obtained sample into S*T to obtain a set C. C is a full-dimensional Cone and always contains a sample.
5) Obtain an integer sample from C.
6) Return T*v, where v is the concatenation of the samples from B and C.
The following is a sketch of a proof that a) If the algorithm returns empty, then S is empty. b) If the algorithm returns a sample, it is a valid sample in S.
The algorithm returns empty only if B is empty, in which case S*T is certainly empty since B was obtained by removing constraints and then deleting unconstrained dimensions from S*T. Since T is unimodular, a vector v is in S*T iff T*v is in S. So in this case, since S*T is empty, S is empty too.
Otherwise, the algorithm substitutes the sample from B into S*T. All the constraints of S*T that did not involve unbounded dimensions are satisfied by this substitution. All dimensions in the linear span of the dimensions outside the prefix are unbounded in S*T (step 1). Substituting values for the bounded dimensions cannot make these dimensions bounded, and these are the only remaining dimensions in C, so C is unbounded along every vector (in the positive or negative direction, or both). C is hence a full-dimensional cone and therefore always contains an integer point.
Concatenating the samples from B and C gives a sample v in S*T, so the returned sample T*v is a sample in S.
Definition at line 871 of file IntegerRelation.cpp.
References atIneq(), mlir::presburger::ceil(), containsPoint(), mlir::presburger::Simplex::findIntegerSample(), getBoundedDirections(), getNumInequalities(), getNumVars(), mlir::presburger::Simplex::getRationalSample(), IntegerRelation(), mlir::presburger::SimplexBase::isEmpty(), isEmptyByGCDTest(), mlir::presburger::Simplex::isUnbounded(), mlir::presburger::LinearTransform::makeTransformToColumnEchelon(), removeConstraintsInvolvingVarRange(), removeVarRange(), result, and setAndEliminate().
Referenced by isIntegerEmpty().
findRationalLexMin()
MaybeOptimum< SmallVector< Fraction, 8 > > IntegerRelation::findRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
Returns an empty optional if the relation is empty or if the lexmin is unbounded. Symbols are not supported and will result in assert-failure. Note that Domain is minimized first, then range.
Definition at line 138 of file IntegerRelation.cpp.
References mlir::presburger::LexSimplex::findRationalLexMin(), getNumDimAndSymbolVars(), getNumSymbolVars(), getNumVars(), and mlir::presburger::MaybeOptimum< T >::isBounded().
findSymbolicIntegerLexMax()
SymbolicLexOpt IntegerRelation::findSymbolicIntegerLexMax () const
Same as findSymbolicIntegerLexMin but produces lexmax instead of lexmin.
findSymbolicIntegerLexMax is implemented using findSymbolicIntegerLexMin as follows:
A new relation is created which is this relation with the sign of each dimension variable in range flipped;
findSymbolicIntegerLexMin is called on the range negated relation to compute the negated lexmax of this relation;
The sign of the negated lexmax is flipped and returned.
Definition at line 314 of file IntegerRelation.cpp.
References atEq(), atIneq(), b, findSymbolicIntegerLexMin(), mlir::presburger::PWMAFunction::getAllPieces(), getNumDomainVars(), getNumEqualities(), getNumInequalities(), getNumRangeVars(), mlir::presburger::Matrix< T >::getNumRows(), mlir::presburger::PWMAFunction::getSpace(), IntegerRelation(), mlir::presburger::SymbolicLexOpt::lexopt, mlir::presburger::Matrix< T >::negateRow(), and mlir::presburger::SymbolicLexOpt::unboundedDomain.
findSymbolicIntegerLexMin()
SymbolicLexOpt IntegerRelation::findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the relation.
This finds, for every assignment to the symbols and domain, the lexicographically minimum value attained by the range.
For example, the symbolic lexmin of the set
(x, y)[a, b, c] : (a <= x, b <= x, x <= c)
can be written as
x = a if b <= a, a <= c x = b if a < b, b <= c
This function is stored in the lexopt function in the result. Some assignments to the symbols might make the set empty. Such points are not part of the function's domain. In the above example, this happens when max(a, b) > c.
For some values of the symbols, the lexmin may be unbounded. SymbolicLexOpt stores these parts of the symbolic domain in a separate PresburgerSet, unboundedDomain.
Definition at line 280 of file IntegerRelation.cpp.
References mlir::presburger::SymbolicLexSimplex::computeSymbolicIntegerLexMin(), mlir::presburger::Domain, getNumDomainVars(), getNumLocalVars(), getNumSymbolVars(), getNumVars(), mlir::presburger::PresburgerSpace::getSetSpace(), getVarKindEnd(), getVarKindOffset(), IntegerPolyhedron, result, and mlir::presburger::Symbol.
Referenced by findSymbolicIntegerLexMax().
fourierMotzkinEliminate()
void IntegerRelation::fourierMotzkinEliminate (unsigned pos, bool darkShadow = false, bool * isResultIntegerExact = nullptr) protected virtual
Eliminates the variable at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that variable.
If the result of the elimination is integer exact, *isResultIntegerExact is set to true. If darkShadow is set to true, a potential under approximation (subset) of the rational shadow / exact integer shadow is computed.
Create the new system which has one variable less.
Definition at line 2024 of file IntegerRelation.cpp.
References addEquality(), addInequality(), atEq(), atIneq(), clearAndCopyFrom(), dump(), gaussianEliminateVar(), gcdTightenInequalities(), getNumCols(), getNumConstraints(), getNumEqualities(), getNumInequalities(), getNumVars(), getSpace(), mlir::presburger::PresburgerSpace::getVarKindAt(), mlir::presburger::PresburgerSpace::getVarKindOffset(), hasConsistentState(), IntegerRelation(), isColZero(), normalizeConstraintsByGCD(), removeTrivialRedundancy(), removeVar(), and mlir::presburger::PresburgerSpace::removeVarRange().
Referenced by isEmpty(), mlir::FlatLinearValueConstraints::projectOut(), and projectOut().
gaussianEliminate()
bool IntegerRelation::gaussianEliminate () protected
Perform a Gaussian elimination operation to reduce all equations to standard form.
Returns whether the constraint system was modified.
Definition at line 1137 of file IntegerRelation.cpp.
References atEq(), eliminateFromConstraint(), equalities, findEqualityWithNonZeroAfterRow(), gcdTightenInequalities(), getEmpty(), getNumEqualities(), getNumInequalities(), getNumVars(), getSpace(), inequalities, and removeEqualityRange().
Referenced by simplify().
gaussianEliminateVar()
LogicalResult mlir::presburger::IntegerRelation::gaussianEliminateVar (unsigned position) inline protected
Eliminates a single variable at position from equality and inequality constraints.
Returns success if the variable was eliminated, and failure otherwise.
Definition at line 876 of file IntegerRelation.h.
References gaussianEliminateVars(), and success().
Referenced by fourierMotzkinEliminate().
gaussianEliminateVars()
unsigned IntegerRelation::gaussianEliminateVars (unsigned posStart, unsigned posLimit) protected
Eliminates variables from equality and inequality constraints in column range [posStart, posLimit).
Returns the number of variables eliminated.
Definition at line 1077 of file IntegerRelation.cpp.
References eliminateFromConstraint(), equalities, findConstraintWithNonZeroAt(), gcdTightenInequalities(), getNumEqualities(), getNumInequalities(), getNumVars(), hasConsistentState(), inequalities, removeEquality(), and removeVarRange().
Referenced by gaussianEliminateVar(), isEmpty(), and projectOut().
gcdTightenInequalities()
void IntegerRelation::gcdTightenInequalities () protected
Tightens inequalities given that we are dealing with integer spaces.
This is similar to the GCD test but applied to inequalities. The constant term can be reduced to the preceding multiple of the GCD of the coefficients, i.e., 64*i - 100 >= 0 => 64*i - 128 >= 0 (since 'i' is an integer). This is a fast method (linear in the number of coefficients).
This is analogous to the GCD test but applied to inequalities. The constant term can be reduced to the preceding multiple of the GCD of the coefficients, i.e., 64*i - 100 >= 0 => 64*i - 128 >= 0 (since 'i' is an integer). This is a fast method - linear in the number of coefficients.
Definition at line 1065 of file IntegerRelation.cpp.
References atIneq(), getNumCols(), getNumInequalities(), and inequalities.
Referenced by fourierMotzkinEliminate(), gaussianEliminate(), gaussianEliminateVars(), projectOut(), removeRedundantConstraints(), and removeTrivialRedundancy().
getBoundedDirections()
IntMatrix IntegerRelation::getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
The span of the returned vectors is guaranteed to contain all such vectors. The returned vectors are NOT guaranteed to be linearly independent. This function should not be called on empty sets.
Definition at line 782 of file IntegerRelation.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumInequalities(), mlir::presburger::Simplex::isBoundedAlongConstraint(), and mlir::presburger::SimplexBase::isEmpty().
Referenced by findIntegerSample().
getConstantBound()
std::optional< DynamicAPInt > IntegerRelation::getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th variable if there is one; std::nullopt otherwise.
Definition at line 1865 of file IntegerRelation.cpp.
References mlir::presburger::EQ, IntegerRelation, mlir::presburger::LB, and mlir::presburger::UB.
Referenced by getConstantBound64(), and unionBoundingBox().
getConstantBound64()
std::optional< int64_t > mlir::presburger::IntegerRelation::getConstantBound64 (BoundType type, unsigned pos) const inline
The same, but casts to int64_t.
This is unsafe and will assert-fail if the value does not fit in an int64_t.
Definition at line 634 of file IntegerRelation.h.
References getConstantBound().
Referenced by computeDirectionVector(), computeUnknownVars(), mlir::FlatLinearConstraints::getSliceBounds(), and mlir::affine::simplifyConstrainedMinMaxOp().
getConstantBoundOnDimSize()
std::optional< DynamicAPInt > IntegerRelation::getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< DynamicAPInt > * lb = nullptr, DynamicAPInt * boundFloorDivisor = nullptr, SmallVectorImpl< DynamicAPInt > * ub = nullptr, unsigned * minLbPos = nullptr, unsigned * minUbPos = nullptr) const
Returns the smallest known constant bound for the extent of the specified variable (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the variable.
Returns a non-negative constant bound on the extent (upper bound - lower bound) of the specified variable if it is found to be a constant; returns std::nullopt if it's not a constant.
This constant bound is guaranteed to be non-negative. Returns std::nullopt if it's not a constant. This method employs trivial (low complexity / cost) checks and detection. Symbolic variables are treated specially, i.e., it looks for constant differences between affine expressions involving only the symbolic variables. lb and ub (along with the boundFloorDivisor) are set to represent the lower and upper bound associated with the constant difference: lb, ub have the coefficients, and boundFloorDivisor, their divisor. minLbPos and minUbPos if non-null are set to the position of the constant lower bound and upper bound respectively (to the same if they are from an equality). Ex: if the lower bound is [(s0 + s2 - 1) floordiv 32] for a system with three symbolic variables, *lb = [1, 0, 1], lbDivisor = 32. See comments at function definition for examples.
This methods treats symbolic variables specially, i.e., it looks for constant differences between affine expressions involving only the symbolic variables. See comments at function definition for example. 'lb', if provided, is set to the lower bound associated with the constant difference. Note that 'lb' is purely symbolic and thus will contain the coefficients of the symbolic variables and the constant coefficient.
Definition at line 1627 of file IntegerRelation.cpp.
References atEq(), atIneq(), findEqualityToConstant(), getEquality(), getLowerAndUpperBoundIndices(), getNumCols(), getNumDimAndSymbolVars(), getNumDimVars(), getNumInequalities(), and getNumSymbolVars().
Referenced by getConstantBoundOnDimSize64(), and unionBoundingBox().
getConstantBoundOnDimSize64()
std::optional< int64_t > mlir::presburger::IntegerRelation::getConstantBoundOnDimSize64 (unsigned pos, SmallVectorImpl< int64_t > * lb = nullptr, int64_t * boundFloorDivisor = nullptr, SmallVectorImpl< int64_t > * ub = nullptr, unsigned * minLbPos = nullptr, unsigned * minUbPos = nullptr) const inline
The same, but casts to int64_t.
This is unsafe and will assert-fail if the value does not fit in an int64_t.
Definition at line 609 of file IntegerRelation.h.
References getConstantBoundOnDimSize(), mlir::presburger::getInt64Vec(), and result.
getCounts()
IntegerRelation::CountsSnapshot IntegerRelation::getCounts () const
Definition at line 195 of file IntegerRelation.cpp.
References getNumEqualities(), getNumInequalities(), and getSpace().
getDomainSet()
IntegerPolyhedron IntegerRelation::getDomainSet () const
Return a set corresponding to all points in the domain of the relation.
Definition at line 2428 of file IntegerRelation.cpp.
References convertVarKind(), mlir::presburger::Domain, getNumVarKind(), IntegerPolyhedron, IntegerRelation(), mlir::presburger::Local, mlir::presburger::Range, and mlir::presburger::SetDim.
Referenced by mlir::affine::checkMemrefAccessDependence(), compose(), and intersectDomain().
getEmpty()
IntegerRelation mlir::presburger::IntegerRelation::getEmpty (const PresburgerSpace & space) inline static
Return an empty system containing an invalid equation 0 = 1.
Definition at line 104 of file IntegerRelation.h.
References IntegerRelation(), result, and space.
Referenced by gaussianEliminate(), and removeDuplicateConstraints().
getEquality()
ArrayRef< DynamicAPInt > mlir::presburger::IntegerRelation::getEquality (unsigned idx) const inline
Definition at line 254 of file IntegerRelation.h.
References equalities.
Referenced by append(), mlir::presburger::LinearTransform::applyTo(), containsPoint(), getCommonConstraints(), getConstantBoundOnDimSize(), getIneqCoeffsFromIdx(), getLowerAndUpperBoundIndices(), mlir::presburger::SimplexBase::intersectIntegerRelation(), mlir::presburger::Simplex::isRationalSubsetOf(), rangeProduct(), removeConstraintsInvolvingVarRange(), and removeTrivialEqualities().
getEquality64()
SmallVector< int64_t, 8 > mlir::presburger::IntegerRelation::getEquality64 (unsigned idx) const inline
The same, but casts to int64_t.
This is unsafe and will assert-fail if the value does not fit in an int64_t.
Definition at line 262 of file IntegerRelation.h.
References equalities, and mlir::presburger::getInt64Vec().
Referenced by mlir::FlatLinearConstraints::dumpPretty(), getAsExpr(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), and mlir::FlatLinearConstraints::getLowerAndUpperBound().
getIds()
ArrayRef< Identifier > IntegerRelation::getIds (VarKind kind)
Get the identifiers for the variables of specified varKind.
Calls resetIds on the relations space if identifiers are not enabled.
Definition at line 75 of file IntegerRelation.cpp.
References space.
Referenced by mlir::affine::MemRefAccess::getAccessRelation().
getInequalities()
IntMatrix mlir::presburger::IntegerRelation::getInequalities () const inline
Definition at line 269 of file IntegerRelation.h.
References inequalities.
Referenced by mlir::presburger::detail::computePolytopeGeneratingFunction(), and mlir::presburger::detail::computeUnimodularConeGeneratingFunction().
getInequality()
ArrayRef< DynamicAPInt > mlir::presburger::IntegerRelation::getInequality (unsigned idx) const inline
Definition at line 257 of file IntegerRelation.h.
References inequalities.
Referenced by append(), mlir::presburger::LinearTransform::applyTo(), containsPoint(), createSeparationCondition(), getCommonConstraints(), getIneqCoeffsFromIdx(), getLowerAndUpperBoundIndices(), getSetDifference(), mlir::presburger::SimplexBase::intersectIntegerRelation(), isFullDim(), mlir::presburger::Simplex::isRationalSubsetOf(), rangeProduct(), removeConstraintsInvolvingVarRange(), and removeDuplicateConstraints().
getInequality64()
SmallVector< int64_t, 8 > mlir::presburger::IntegerRelation::getInequality64 (unsigned idx) const inline
Definition at line 265 of file IntegerRelation.h.
References mlir::presburger::getInt64Vec(), and inequalities.
Referenced by mlir::FlatLinearConstraints::dumpPretty(), getAsExpr(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), and mlir::FlatLinearConstraints::getLowerAndUpperBound().
getKind()
virtual Kind mlir::presburger::IntegerRelation::getKind () const inline virtual
Return the kind of this IntegerRelation.
Reimplemented in mlir::affine::FlatAffineRelation, mlir::affine::FlatAffineValueConstraints, mlir::FlatLinearConstraints, mlir::FlatLinearValueConstraints, and mlir::presburger::IntegerPolyhedron.
Definition at line 113 of file IntegerRelation.h.
References IntegerRelation.
Referenced by mlir::presburger::IntegerPolyhedron::classof().
getLocalReprs()
DivisionRepr IntegerRelation::getLocalReprs (std::vector< MaybeLocalRepr > * repr = nullptr) const
Returns a DivisonRepr representing the division representation of local variables in the constraint system.
If repr is not nullptr, the equality and pairs of inequality constraints identified by their position indices using which an explicit representation for each local variable can be computed are set in repr in the form of a MaybeLocalRepr struct. If no such inequality pair/equality can be found, the kind attribute in MaybeLocalRepr is set to None.
Definition at line 1023 of file IntegerRelation.cpp.
References mlir::changed, mlir::presburger::DivisionRepr::clearRepr(), mlir::presburger::computeSingleVarRepr(), mlir::presburger::DivisionRepr::getDenom(), mlir::presburger::DivisionRepr::getDividend(), getNumDimAndSymbolVars(), getNumLocalVars(), getNumVars(), getVarKindOffset(), and mlir::presburger::Local.
Referenced by mlir::getMultiAffineFunctionFromMap(), getSetDifference(), hasOnlyDivLocals(), mlir::presburger::mergeLocalVars(), and removeDuplicateDivs().
getLowerAndUpperBoundIndices()
void IntegerRelation::getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > * lbIndices, SmallVectorImpl< unsigned > * ubIndices, SmallVectorImpl< unsigned > * eqIndices = nullptr, unsigned offset = 0, unsigned num = 0) const
Gather positions of all lower and upper bounds of the variable at pos, and optionally any equalities on it.
Gather all lower and upper bounds of the variable at pos, and optionally any equalities on it.
In addition, the bounds are to be independent of variables in position range [offset, offset + num).
Definition at line 491 of file IntegerRelation.cpp.
References atEq(), atIneq(), getEquality(), getInequality(), getNumCols(), getNumEqualities(), getNumInequalities(), and getNumVars().
Referenced by mlir::presburger::computeSingleVarRepr(), createSeparationCondition(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), getConstantBoundOnDimSize(), and mlir::FlatLinearConstraints::getLowerAndUpperBound().
getNumCols()
unsigned mlir::presburger::IntegerRelation::getNumCols () const inline
Returns the number of columns in the constraint system.
Definition at line 238 of file IntegerRelation.h.
References space.
Referenced by mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::FlatLinearConstraints::addBound(), addBound(), addBound(), addEquality(), addInequality(), addLocalFloorDiv(), addLocalModulo(), mlir::scf::addLoopRangeConstraints(), addOrderingConstraints(), mlir::FlatLinearConstraints::composeMatchingMap(), computeConstantLowerOrUpperBound(), computeDirectionVector(), mlir::presburger::computeSingleVarRepr(), mlir::presburger::computeSingleVarRepr(), constantFoldVar(), createSeparationCondition(), detectAsFloorDiv(), detectAsMod(), mlir::FlatLinearConstraints::dumpRow(), eliminateFromConstraint(), findConstraintWithNonZeroAt(), findEqualityWithNonZeroAfterRow(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), fourierMotzkinEliminate(), gcdTightenInequalities(), generateCopy(), getBoundedDirections(), getConstantBoundOnDimSize(), getDivRepr(), getDivRepr(), mlir::presburger::detail::getDual(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLowerAndUpperBoundIndices(), mlir::affine::getRelationFromMap(), hasInvalidConstraint(), isEmptyByGCDTest(), isHyperRectangular(), isObviouslyEqual(), print(), projectOut(), removeDuplicateConstraints(), removeRedundantInequalities(), removeTrivialRedundancy(), setAndEliminate(), mlir::affine::simplifyConstrainedMinMaxOp(), and unionBoundingBox().
getNumConstraints()
unsigned mlir::presburger::IntegerRelation::getNumConstraints () const inline
Definition at line 209 of file IntegerRelation.h.
References getNumEqualities(), and getNumInequalities().
Referenced by atConstraint(), atConstraint64(), mlir::FlatLinearConstraints::dumpPretty(), fourierMotzkinEliminate(), mlir::FlatLinearConstraints::getAsIntegerSet(), isEmpty(), printSpace(), and pruneOrthogonalConstraints().
getNumDimAndSymbolVars()
unsigned mlir::presburger::IntegerRelation::getNumDimAndSymbolVars () const inline
Definition at line 232 of file IntegerRelation.h.
References space.
Referenced by mlir::FlatLinearConstraints::addBound(), areVarsUnique(), areVarsUnique(), areVarsUnique(), mlir::affine::computeSliceUnion(), computeUnknownVars(), computeVolume(), mlir::affine::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), createFullTiles(), createPrivateMemRef(), createSeparationCondition(), findIntegerLexMin(), findRationalLexMin(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::affine::getComputationSliceState(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), getConstantBoundOnDimSize(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLocalReprs(), mlir::FlatLinearConstraints::getLowerAndUpperBound(), mlir::FlatLinearValueConstraints::getMaybeValues(), mlir::affine::getRelationFromMap(), mlir::FlatLinearValueConstraints::getValue(), mlir::FlatLinearValueConstraints::getValues(), mlir::FlatLinearValueConstraints::hasValue(), mlir::FlatLinearValueConstraints::mergeSymbolVars(), mlir::FlatLinearConstraints::printSpace(), mlir::FlatLinearValueConstraints::printSpace(), removeRedundantLocalVars(), mlir::FlatLinearValueConstraints::setValue(), and mlir::affine::simplifyConstrainedMinMaxOp().
getNumDimVars()
unsigned mlir::presburger::IntegerRelation::getNumDimVars () const inline
Definition at line 231 of file IntegerRelation.h.
References space.
Referenced by mlir::FlatLinearConstraints::addBound(), mlir::affine::FlatAffineValueConstraints::addDomainFromSliceMaps(), mlir::scf::addLoopRangeConstraints(), addMissingLoopIVBounds(), addOrderingConstraints(), mlir::FlatLinearValueConstraints::appendDimVar(), mlir::affine::FlatAffineRelation::appendRangeVar(), areVarsUnique(), mlir::FlatLinearConstraints::composeMatchingMap(), mlir::FlatLinearValueConstraints::computeAlignedMap(), computeDirectionVector(), mlir::FlatLinearConstraints::computeLocalVars(), mlir::affine::computeSliceUnion(), computeUnknownVars(), mlir::affine::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), mlir::FlatLinearConstraints::dumpPretty(), findEqualityToConstant(), mlir::affine::MemRefAccess::getAccessRelation(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), getConstantBoundOnDimSize(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatLinearConstraints::getLowerAndUpperBound(), getNumCommonLoops(), mlir::affine::getRelationFromMap(), mlir::affine::getRelationFromMap(), mlir::FlatLinearConstraints::getSliceBounds(), mlir::affine::ComputationSliceState::isMaximal(), mergeAndAlignVars(), mlir::FlatLinearValueConstraints::mergeSymbolVars(), mlir::affine::FlatAffineRelation::removeVarRange(), turnSymbolIntoDim(), mlir::FlatLinearValueConstraints::unionBoundingBox(), and unionBoundingBox().
getNumDomainVars()
unsigned mlir::presburger::IntegerRelation::getNumDomainVars () const inline
Definition at line 226 of file IntegerRelation.h.
References space.
Referenced by areVarsAligned(), mlir::affine::checkMemrefAccessDependence(), findSymbolicIntegerLexMax(), findSymbolicIntegerLexMin(), intersectRange(), mergeAndCompose(), and rangeProduct().
getNumEqualities()
unsigned mlir::presburger::IntegerRelation::getNumEqualities () const inline
Definition at line 240 of file IntegerRelation.h.
References equalities.
Referenced by append(), mlir::presburger::LinearTransform::applyTo(), containsPoint(), detectAsMod(), mlir::FlatLinearConstraints::dumpPretty(), findConstraintWithNonZeroAt(), findEqualityToConstant(), findEqualityWithNonZeroAfterRow(), findSymbolicIntegerLexMax(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), fourierMotzkinEliminate(), gaussianEliminate(), gaussianEliminateVars(), mlir::FlatLinearConstraints::getAsIntegerSet(), getBoundedDirections(), getCommonConstraints(), getCounts(), getDivRepr(), getIndependentConstraints(), getIneqCoeffsFromIdx(), getLowerAndUpperBoundIndices(), getNumConstraints(), getSetDifference(), hasInvalidConstraint(), mlir::presburger::SimplexBase::intersectIntegerRelation(), isEmptyByGCDTest(), isFullDim(), isHyperRectangular(), isObviouslyEqual(), mlir::presburger::Simplex::isRationalSubsetOf(), normalizeConstraintsByGCD(), print(), rangeProduct(), removeConstraintsInvolvingVarRange(), removeRedundantConstraints(), removeRedundantLocalVars(), removeTrivialEqualities(), and truncate().
getNumInequalities()
unsigned mlir::presburger::IntegerRelation::getNumInequalities () const inline
Definition at line 242 of file IntegerRelation.h.
References inequalities.
Referenced by append(), mlir::presburger::LinearTransform::applyTo(), atConstraint(), atConstraint64(), computeConstantLowerOrUpperBound(), mlir::presburger::detail::computePolytopeGeneratingFunction(), mlir::presburger::detail::computeUnimodularConeGeneratingFunction(), containsPoint(), mlir::FlatLinearConstraints::dumpPretty(), findConstraintWithNonZeroAt(), findIntegerSample(), findSymbolicIntegerLexMax(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), fourierMotzkinEliminate(), gaussianEliminate(), gaussianEliminateVars(), gcdTightenInequalities(), mlir::FlatLinearConstraints::getAsIntegerSet(), getBestVarToEliminate(), getBoundedDirections(), getCommonConstraints(), getConstantBoundOnDimSize(), getCounts(), getDivRepr(), mlir::presburger::detail::getDual(), getIndependentConstraints(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getIneqCoeffsFromIdx(), mlir::presburger::MultiAffineFunction::getLexSet(), getLowerAndUpperBoundIndices(), getNumConstraints(), getSetDifference(), hasInvalidConstraint(), mlir::presburger::SimplexBase::intersectIntegerRelation(), isFullDim(), isHyperRectangular(), isObviouslyEqual(), mlir::presburger::Simplex::isRationalSubsetOf(), normalizeConstraintsByGCD(), print(), rangeProduct(), removeConstraint(), removeConstraintsInvolvingVarRange(), removeDuplicateConstraints(), removeRedundantConstraints(), removeRedundantInequalities(), removeRedundantLocalVars(), removeTrivialRedundancy(), and truncate().
getNumLocalVars()
unsigned mlir::presburger::IntegerRelation::getNumLocalVars () const inline
Definition at line 229 of file IntegerRelation.h.
References space.
Referenced by addDivisionConstraints(), mlir::FlatLinearConstraints::computeLocalVars(), computeReprWithOnlyDivLocals(), mlir::affine::computeSliceUnion(), containsPointNoLocal(), mlir::FlatLinearConstraints::dumpPretty(), eliminateRedundantLocalVar(), findSymbolicIntegerLexMin(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearConstraints::flattenAlignedMapAndMergeLocals(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLocalReprs(), mlir::FlatLinearConstraints::getLowerAndUpperBound(), getSetDifference(), mlir::FlatLinearConstraints::getSliceBounds(), mlir::affine::ComputationSliceState::isSliceValid(), mergeLocalVars(), mlir::presburger::mergeLocalVars(), mlir::FlatLinearValueConstraints::unionBoundingBox(), and unionBoundingBox().
getNumRangeVars()
unsigned mlir::presburger::IntegerRelation::getNumRangeVars () const inline
Definition at line 227 of file IntegerRelation.h.
References space.
Referenced by areVarsAligned(), compose(), mlir::presburger::detail::computePolytopeGeneratingFunction(), findSymbolicIntegerLexMax(), intersectDomain(), mergeAndCompose(), and rangeProduct().
getNumReservedEqualities()
unsigned mlir::presburger::IntegerRelation::getNumReservedEqualities () const inline
Definition at line 246 of file IntegerRelation.h.
References equalities.
getNumReservedInequalities()
unsigned mlir::presburger::IntegerRelation::getNumReservedInequalities () const inline
Definition at line 250 of file IntegerRelation.h.
References inequalities.
getNumSymbolVars()
unsigned mlir::presburger::IntegerRelation::getNumSymbolVars () const inline
Definition at line 228 of file IntegerRelation.h.
References space.
Referenced by mlir::FlatLinearConstraints::addBound(), mlir::scf::addLoopRangeConstraints(), mlir::FlatLinearValueConstraints::appendSymbolVar(), areVarsAligned(), mlir::FlatLinearConstraints::composeMatchingMap(), mlir::FlatLinearValueConstraints::computeAlignedMap(), mlir::FlatLinearConstraints::computeLocalVars(), mlir::presburger::detail::computePolytopeGeneratingFunction(), computeVolume(), mlir::FlatLinearConstraints::dumpPretty(), findIntegerLexMin(), findRationalLexMin(), findSymbolicIntegerLexMin(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::affine::MemRefRegion::getConstantBoundingSizeAndShape(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), getConstantBoundOnDimSize(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::affine::getRelationFromMap(), mlir::FlatLinearConstraints::getSliceBounds(), mlir::affine::ComputationSliceState::isSliceValid(), mlir::FlatLinearValueConstraints::mergeSymbolVars(), rangeProduct(), mlir::presburger::SymbolicLexSimplex::SymbolicLexSimplex(), turnSymbolIntoDim(), and unionBoundingBox().
getNumVarKind()
unsigned mlir::presburger::IntegerRelation::getNumVarKind (VarKind kind) const inline
Get the number of vars of the specified kind.
Definition at line 272 of file IntegerRelation.h.
References space.
Referenced by appendVar(), mlir::FlatLinearValueConstraints::computeAlignedMap(), convertVarKind(), convertVarKind(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), getDomainSet(), mlir::FlatLinearValueConstraints::getMaybeValues(), getRangeSet(), insertVar(), inverse(), mergeAndAlignSymbols(), mlir::affine::FlatAffineRelation::removeVarRange(), removeVarRange(), removeVarRange(), and truncateVarKind().
getNumVars()
unsigned mlir::presburger::IntegerRelation::getNumVars () const inline
Definition at line 235 of file IntegerRelation.h.
References space.
Referenced by addDivisionConstraints(), checkExplicitRepresentation(), computeConstantLowerOrUpperBound(), computeDirectionVector(), mlir::presburger::computeSingleVarRepr(), mlir::presburger::detail::computeUnimodularConeGeneratingFunction(), computeUnknownVars(), computeVolume(), constantFoldVar(), containsPointNoLocal(), detectAsExpr(), detectAsFloorDiv(), detectAsMod(), findEqualityToConstant(), findIntegerLexMin(), findIntegerSample(), findRationalLexMin(), findSymbolicIntegerLexMin(), mlir::FlatLinearConstraints::FlatLinearConstraints(), fourierMotzkinEliminate(), gaussianEliminate(), gaussianEliminateVars(), generateCopy(), getAsExpr(), mlir::FlatLinearConstraints::getAsIntegerSet(), getBestVarToEliminate(), mlir::FlatLinearConstraints::getConstantBoundOnDimSize(), getDivRepr(), getDivRepr(), getIndependentConstraints(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLocalReprs(), getLowerAndUpperBoundIndices(), mlir::FlatLinearConstraints::getSliceBounds(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), IntegerRelation(), IntegerRelation(), mlir::presburger::SimplexBase::intersectIntegerRelation(), isEmpty(), isFullDim(), mlir::affine::ComputationSliceState::isSliceValid(), projectOut(), pruneOrthogonalConstraints(), removeIndependentConstraints(), removeRedundantLocalVars(), removeVarRange(), setAndEliminate(), setSpaceExceptLocals(), mlir::FlatLinearValueConstraints::setValues(), swapVar(), and mlir::presburger::SymbolicLexSimplex::SymbolicLexSimplex().
getRangeSet()
IntegerPolyhedron IntegerRelation::getRangeSet () const
Return a set corresponding to all points in the range of the relation.
Definition at line 2503 of file IntegerRelation.cpp.
References convertVarKind(), mlir::presburger::Domain, getNumVarKind(), IntegerPolyhedron, IntegerRelation(), and mlir::presburger::Local.
Referenced by compose(), and intersectRange().
getSpace()
const PresburgerSpace & mlir::presburger::IntegerRelation::getSpace () const inline
Returns a reference to the underlying space.
Definition at line 121 of file IntegerRelation.h.
References space.
Referenced by append(), mlir::presburger::LinearTransform::applyTo(), mlir::affine::checkMemrefAccessDependence(), mlir::affine::FlatAffineRelation::compose(), compose(), computeReprWithOnlyDivLocals(), fourierMotzkinEliminate(), gaussianEliminate(), mlir::affine::MemRefAccess::getAccessRelation(), getCommonConstraints(), getCounts(), intersectDomain(), intersectRange(), isEqual(), isObviouslyEqual(), isSubsetOf(), mlir::presburger::mergeLocalVars(), removeDuplicateConstraints(), unionBoundingBox(), and mlir::presburger::PresburgerRelation::unionInPlace().
getSpaceWithoutLocals()
PresburgerSpace mlir::presburger::IntegerRelation::getSpaceWithoutLocals () const inline
Returns a copy of the space without locals.
Definition at line 146 of file IntegerRelation.h.
References mlir::presburger::PresburgerSpace::getRelationSpace(), and space.
getUniverse()
IntegerRelation mlir::presburger::IntegerRelation::getUniverse (const PresburgerSpace & space) inline static
Return a system with no constraints, i.e., one which is satisfied by all points.
Definition at line 99 of file IntegerRelation.h.
References IntegerRelation(), IntegerRelation, and space.
Referenced by mlir::presburger::PresburgerRelation::complement(), and mlir::presburger::PresburgerRelation::getUniverse().
getVarKindAt()
VarKind mlir::presburger::IntegerRelation::getVarKindAt (unsigned pos) const inline
Return the VarKind of the var at the specified position.
Definition at line 301 of file IntegerRelation.h.
References space.
Referenced by mlir::FlatLinearValueConstraints::getValue(), mlir::FlatLinearValueConstraints::hasValue(), and mlir::FlatLinearValueConstraints::setValue().
getVarKindEnd()
unsigned mlir::presburger::IntegerRelation::getVarKindEnd (VarKind kind) const inline
Return the index at Which the specified kind of vars ends.
Definition at line 282 of file IntegerRelation.h.
References space.
Referenced by findSymbolicIntegerLexMin(), inverse(), iterVarKind(), mlir::FlatLinearConstraints::printSpace(), and mlir::FlatLinearValueConstraints::printSpace().
getVarKindOffset()
unsigned mlir::presburger::IntegerRelation::getVarKindOffset (VarKind kind) const inline
Return the index at which the specified kind of vars starts.
Definition at line 277 of file IntegerRelation.h.
References space.
Referenced by containsPointNoLocal(), convertVarKind(), eliminateRedundantLocalVar(), findSymbolicIntegerLexMin(), getLocalReprs(), getSetDifference(), mlir::FlatLinearValueConstraints::getValue(), mlir::FlatLinearValueConstraints::hasValue(), iterVarKind(), mergeAndAlignSymbols(), mlir::FlatLinearConstraints::printSpace(), mlir::FlatLinearValueConstraints::printSpace(), rangeProduct(), removeVarRange(), removeVarRange(), mlir::FlatLinearValueConstraints::setValue(), and swapVar().
getVarKindOverlap()
unsigned mlir::presburger::IntegerRelation::getVarKindOverlap (VarKind kind, unsigned varStart, unsigned varLimit) const inline
Get the number of elements of the specified kind in the range [varStart, varLimit).
Definition at line 295 of file IntegerRelation.h.
References space.
hasConsistentState()
bool IntegerRelation::hasConsistentState () const protected virtual
Returns false if the fields corresponding to various variable counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
This is meant to be used within an assert internally.
Definition at line 542 of file IntegerRelation.cpp.
References equalities, and inequalities.
Referenced by mlir::FlatLinearConstraints::dumpPretty(), fourierMotzkinEliminate(), gaussianEliminateVars(), hasInvalidConstraint(), isEmptyByGCDTest(), and print().
hasInvalidConstraint()
bool IntegerRelation::hasInvalidConstraint () const protected
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
Returns true if an invalid constraint is found; false otherwise.
Definition at line 592 of file IntegerRelation.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumInequalities(), and hasConsistentState().
Referenced by isEmpty(), and isObviouslyEmpty().
hasOnlyDivLocals()
bool IntegerRelation::hasOnlyDivLocals () const
Check whether all local ids have a division representation.
Definition at line 1404 of file IntegerRelation.cpp.
References getLocalReprs(), and mlir::presburger::DivisionRepr::hasAllReprs().
Referenced by mlir::presburger::PresburgerRelation::hasOnlyDivLocals().
insertVar()
unsigned IntegerRelation::insertVar (VarKind kind, unsigned pos, unsigned num = 1) virtual
Insert num variables of the specified kind at position pos.
Positions are relative to the kind of variable. The coefficient columns corresponding to the added variables are initialized to zero. Return the absolute column position (i.e., not relative to the kind of variable) of the first added variable.
Reimplemented in mlir::FlatLinearValueConstraints, and mlir::presburger::IntegerPolyhedron.
Definition at line 350 of file IntegerRelation.cpp.
References equalities, getNumVarKind(), inequalities, and space.
Referenced by appendVar(), mlir::affine::MemRefAccess::getAccessRelation(), mlir::presburger::IntegerPolyhedron::insertVar(), mergeAndAlignSymbols(), mergeAndCompose(), and mlir::presburger::mergeLocalVars().
intersect()
IntegerRelation IntegerRelation::intersect (IntegerRelation other) const
Return the intersection of the two relations.
If there are locals, they will be merged.
Definition at line 96 of file IntegerRelation.cpp.
References IntegerRelation(), and result.
Referenced by mlir::presburger::IntegerPolyhedron::intersect(), and mlir::presburger::PresburgerRelation::intersect().
intersectDomain()
void IntegerRelation::intersectDomain (const IntegerPolyhedron & poly)
Intersect the given poly with the domain in-place.
Formally, let the relation this be R: A -> B and poly is C, then this operation modifies R to be (A intersection C) -> B.
Definition at line 2516 of file IntegerRelation.cpp.
References append(), appendVar(), getDomainSet(), getNumRangeVars(), getSpace(), IntegerPolyhedron, IntegerRelation(), inverse(), mergeLocalVars(), and mlir::presburger::Range.
Referenced by mlir::presburger::MultiAffineFunction::isEqual().
intersectRange()
void IntegerRelation::intersectRange (const IntegerPolyhedron & poly)
Intersect the given poly with the range in-place.
Formally, let the relation this be R: A -> B and poly is C, then this operation modifies R to be A -> (B intersection C).
Definition at line 2532 of file IntegerRelation.cpp.
References append(), appendVar(), mlir::presburger::Domain, getNumDomainVars(), getRangeSet(), getSpace(), IntegerPolyhedron, IntegerRelation(), and mergeLocalVars().
Referenced by compose().
inverse()
void IntegerRelation::inverse ()
Invert the relation i.e., swap its domain and range.
Formally, let the relation this be R: A -> B, then this operation modifies R to be B -> A.
Definition at line 2545 of file IntegerRelation.cpp.
References convertVarKind(), mlir::presburger::Domain, getNumVarKind(), getVarKindEnd(), and mlir::presburger::Range.
Referenced by applyDomain(), mlir::affine::checkMemrefAccessDependence(), and intersectDomain().
isColZero()
bool IntegerRelation::isColZero (unsigned pos) const protected
Returns true if the pos^th column is all zero for both inequalities and equalities.
Definition at line 2375 of file IntegerRelation.cpp.
References findConstraintWithNonZeroAt().
Referenced by fourierMotzkinEliminate(), and mlir::FlatLinearConstraints::getAsIntegerSet().
isEmpty()
bool IntegerRelation::isEmpty () const
Checks for emptiness by performing variable elimination on all variables, running the GCD test on each equality constraint, and checking for invalid constraints.
Returns true if the GCD test fails for any equality, or if any invalid constraints are discovered on any row. Returns false otherwise.
Definition at line 695 of file IntegerRelation.cpp.
References fourierMotzkinEliminate(), gaussianEliminateVars(), getBestVarToEliminate(), getNumConstraints(), getNumVars(), hasInvalidConstraint(), IntegerRelation(), isEmptyByGCDTest(), kExplosionFactor, and removeRedundantLocalVars().
Referenced by mlir::affine::checkMemrefAccessDependence(), mlir::presburger::PresburgerRelation::compose(), mlir::presburger::PresburgerRelation::intersect(), isFullDim(), removeRedundantInequalities(), mlir::affine::simplifyConstrainedMinMaxOp(), and mlir::affine::simplifyIntegerSet().
isEmptyByGCDTest()
bool IntegerRelation::isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
Returns true if this test fails on any equality. Returns false otherwise. This test can be used to disprove the existence of a solution. If it returns true, no integer solution to the equality constraints can exist.
Definition at line 759 of file IntegerRelation.cpp.
References mlir::presburger::abs(), atEq(), getNumCols(), getNumEqualities(), and hasConsistentState().
Referenced by findIntegerSample(), isEmpty(), and isObviouslyEmpty().
isEqual()
bool IntegerRelation::isEqual (const IntegerRelation & other) const
Return whether this and other are equal.
This is integer-exact and somewhat expensive, since it uses the integer emptiness check (see IntegerRelation::findIntegerSample()).
Definition at line 103 of file IntegerRelation.cpp.
References getSpace(), IntegerRelation(), mlir::presburger::PresburgerRelation::isEqual(), and space.
Referenced by mlir::presburger::MultiAffineFunction::isEqual(), and mlir::presburger::MultiAffineFunction::isEqual().
isFullDim()
bool IntegerRelation::isFullDim ()
Definition at line 2635 of file IntegerRelation.cpp.
References getInequality(), getNumEqualities(), getNumInequalities(), getNumVars(), isEmpty(), mlir::presburger::Simplex::isFlatAlong(), and removeTrivialEqualities().
Referenced by mlir::presburger::PresburgerRelation::isFullDim().
isHyperRectangular()
bool IntegerRelation::isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of variables.
Definition at line 1885 of file IntegerRelation.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), and getNumInequalities().
Referenced by checkIfHyperRectangular().
isIntegerEmpty()
bool IntegerRelation::isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Uses the same algorithm as findIntegerSample.
Definition at line 823 of file IntegerRelation.cpp.
References findIntegerSample().
Referenced by mlir::presburger::PresburgerRelation::isIntegerEmpty().
isObviouslyEmpty()
bool IntegerRelation::isObviouslyEmpty () const
Performs GCD checks and invalid constraint checks.
Definition at line 741 of file IntegerRelation.cpp.
References hasInvalidConstraint(), and isEmptyByGCDTest().
Referenced by simplify(), and mlir::presburger::PresburgerRelation::simplify().
isObviouslyEqual()
bool IntegerRelation::isObviouslyEqual (const IntegerRelation & other) const
Perform a quick equality check on this and other.
The relations are equal if the check return true, but may or may not be equal if the check returns false. The equality check is performed in a plain manner, by comparing if all the equalities and inequalities in this and other are the same.
Definition at line 108 of file IntegerRelation.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumInequalities(), getSpace(), IntegerRelation(), and space.
isSubsetOf()
bool IntegerRelation::isSubsetOf (const IntegerRelation & other) const
Return whether this is a subset of the given IntegerRelation.
This is integer-exact and somewhat expensive, since it uses the integer emptiness check (see IntegerRelation::findIntegerSample()).
Definition at line 132 of file IntegerRelation.cpp.
References getSpace(), IntegerRelation(), mlir::presburger::PresburgerRelation::isSubsetOf(), and space.
iterVarKind()
auto mlir::presburger::IntegerRelation::iterVarKind (VarKind kind) inline
Return an interator over the variables of the specified kind starting at the relevant offset.
The return type is auto in keeping with the convention for iterators.
Definition at line 289 of file IntegerRelation.h.
References getVarKindEnd(), and getVarKindOffset().
mergeAndAlignSymbols()
void IntegerRelation::mergeAndAlignSymbols (IntegerRelation & other)
Merge and align symbol variables of this and other with respect to identifiers.
mergeAndAlignSymbols's implementation can be broken down into two steps:
After this operation the symbol variables of both relations have the same identifiers in the same order.
Merge and align identifiers into other from this. If an identifier / from this exists in other then we align it. Otherwise, we assume it is a / new identifier and insert it into other in the same position as this. / 2. Add identifiers that are in other but not this to this.
Definition at line 1331 of file IntegerRelation.cpp.
References mlir::presburger::PresburgerSpace::getId(), mlir::presburger::PresburgerSpace::getIds(), getNumVarKind(), getVarKindOffset(), insertVar(), IntegerRelation(), mlir::presburger::PresburgerSpace::isUsingIds(), mlir::presburger::PresburgerSpace::setId(), space, swapVar(), and mlir::presburger::Symbol.
Referenced by mlir::affine::MemRefAccess::getAccessRelation(), and mergeAndCompose().
mergeAndCompose()
void IntegerRelation::mergeAndCompose (const IntegerRelation & other)
Given a relation other: (A -> B), this operation merges the symbol and local variables and then takes the composition of other on this: (B -> / C).
The resulting relation represents tuples of the form: A -> C.
Definition at line 2654 of file IntegerRelation.cpp.
References convertToLocal(), mlir::presburger::Domain, getNumDomainVars(), getNumRangeVars(), insertVar(), IntegerRelation(), mergeAndAlignSymbols(), mergeLocalVars(), mlir::presburger::Range, removeVarRange(), result, and space.
Referenced by mlir::affine::checkMemrefAccessDependence().
mergeLocalVars()
unsigned IntegerRelation::mergeLocalVars (IntegerRelation & other)
Adds additional local vars to the sets such that they both have the union of the local vars in each set, without changing the set of points that lie in this and other.
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
While taking union, if a local var in other has a division representation which is a duplicate of division representation, of another local var, it is not added to the final union of local vars and is instead merged. The new ordering of local vars is:
[Local vars of this] [Non-merged local vars of other]
The relative ordering of local vars is same as before.
After merging, if the i^th local variable in one set has a known division representation, then the i^th local variable in the other set either has the same division representation or no known division representation.
The spaces of both relations should be compatible.
Returns the number of non-merged local vars of other, i.e. the number of locals that have been added to this.
To detect local ids that always take the same value, each local id is represented as a floordiv with constant denominator in terms of other ids. After extracting these divisions, local ids in other with the same division representation as some other local id in any set are considered duplicate and are merged.
It is possible that division representation for some local id cannot be obtained, and thus these local ids are not considered for detecting duplicates.
Definition at line 1373 of file IntegerRelation.cpp.
References eliminateRedundantLocalVar(), getNumLocalVars(), IntegerRelation(), and mlir::presburger::mergeLocalVars().
Referenced by mlir::affine::FlatAffineRelation::compose(), mlir::affine::MemRefAccess::getAccessRelation(), intersectDomain(), intersectRange(), mergeAndAlignVars(), and mergeAndCompose().
normalizeConstraintsByGCD()
void IntegerRelation::normalizeConstraintsByGCD () protected
Normalized each constraints by the GCD of its coefficients.
Definition at line 585 of file IntegerRelation.cpp.
References equalities, getNumEqualities(), getNumInequalities(), and inequalities.
Referenced by fourierMotzkinEliminate(), mlir::FlatLinearConstraints::getSliceBounds(), projectOut(), removeTrivialRedundancy(), and simplify().
print()
void IntegerRelation::print (raw_ostream & os) const
Definition at line 2713 of file IntegerRelation.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumInequalities(), hasConsistentState(), printSpace(), mlir::presburger::printWithPrintMetrics(), and mlir::presburger::updatePrintMetrics().
Referenced by dump(), mlir::presburger::operator<<(), and mlir::presburger::PresburgerRelation::print().
printSpace()
void IntegerRelation::printSpace (raw_ostream & os) const protected virtual
Prints the number of constraints, dimensions, symbols and locals in the IntegerRelation.
Reimplemented in mlir::FlatLinearConstraints, and mlir::FlatLinearValueConstraints.
Definition at line 2624 of file IntegerRelation.cpp.
References getNumConstraints(), and space.
Referenced by print().
projectOut() [1/2]
void mlir::presburger::IntegerRelation::projectOut (unsigned pos) inline
Definition at line 527 of file IntegerRelation.h.
References projectOut().
Referenced by projectOut().
projectOut() [2/2]
void IntegerRelation::projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num variables starting at position pos.
The resulting constraint system is the shadow along the dimensions that still exist. This method may not always be integer exact.
Definition at line 2179 of file IntegerRelation.cpp.
References fourierMotzkinEliminate(), gaussianEliminateVars(), gcdTightenInequalities(), getBestVarToEliminate(), getNumCols(), getNumVars(), and normalizeConstraintsByGCD().
Referenced by computeConstantLowerOrUpperBound(), and computeDirectionVector().
pruneOrthogonalConstraints()
void IntegerRelation::pruneOrthogonalConstraints (unsigned pos)
The function removes some constraints that do not impose any bound on the specified variable.
The set of constraints (equations/inequalities) can be modeled as an undirected graph where:
Variables are the nodes.
Constraints are the edges connecting those nodes.
Variables and constraints belonging to different connected components are irrelevant to each other. This property allows for safe pruning of constraints.
For example, given the following constraints:
Inequalities: (1) d0 + d1 > 0, (2) d1 >= 2, (3) d4 > 5
Equalities: (4) d3 + d4 = 1, (5) d0 - d2 = 3
These form two connected components:
Component 1: {d0, d1, d2} (related by constraints 1, 2, 5)
Component 2: {d3, d4} (related by constraint 4)
If we are querying the bound of variable d0, constraints related to Component 2 (e.g., constraints 3 and 4) can be safely pruned as they have no impact on the solution space of Component 1. This function prunes irrelevant constraints by identifying all variables and constraints that belong to the same connected component as the target variable.
Definition at line 1754 of file IntegerRelation.cpp.
References atConstraint(), getNumConstraints(), getNumVars(), and removeConstraint().
Referenced by computeConstantLowerOrUpperBound().
rangeProduct()
IntegerRelation IntegerRelation::rangeProduct (const IntegerRelation & rel)
Let the relation this be R1, and the relation rel be R2.
Requires R1 and R2 to have the same domain.
Let R3 be the rangeProduct of R1 and R2. Then x R3 (y, z) iff (x R1 y and x R2 z).
Example:
R1: (i, j) -> k : f(i, j, k) = 0 R2: (i, j) -> l : g(i, j, l) = 0 R1.rangeProduct(R2): (i, j) -> (k, l) : f(i, j, k) = 0 and g(i, j, l) = 0
R1: (i, j) -> k : f(i, j, k) = 0 R2: (i, j) -> l : g(i, j, l) = 0 R1.rangeProduct(R2): (i, j) -> (k, l) : f(i, j, k) = 0 and g(i, j, l) = 0
Definition at line 2586 of file IntegerRelation.cpp.
References copy(), getEquality(), getInequality(), getNumDomainVars(), getNumEqualities(), getNumInequalities(), getNumRangeVars(), getNumSymbolVars(), getVarKindOffset(), IntegerRelation(), mlir::presburger::Range, and result.
removeConstraint()
void IntegerRelation::removeConstraint (unsigned pos)
Definition at line 446 of file IntegerRelation.cpp.
References getNumInequalities(), removeEquality(), and removeInequality().
Referenced by pruneOrthogonalConstraints().
removeDuplicateConstraints()
bool IntegerRelation::removeDuplicateConstraints () protected
Checks for identical inequalities and eliminates redundant inequalities.
Returns whether the constraint system was modified.
Definition at line 2442 of file IntegerRelation.cpp.
References addEquality(), atIneq(), mlir::changed, getEmpty(), getInequality(), getNumCols(), getNumInequalities(), getSpace(), inequalities, and removeInequality().
Referenced by simplify().
removeDuplicateDivs()
void IntegerRelation::removeDuplicateDivs ()
Definition at line 1408 of file IntegerRelation.cpp.
References eliminateRedundantLocalVar(), getLocalReprs(), and mlir::presburger::DivisionRepr::removeDuplicateDivs().
Referenced by getSetDifference().
removeEquality()
void IntegerRelation::removeEquality (unsigned pos)
Definition at line 438 of file IntegerRelation.cpp.
References equalities.
Referenced by gaussianEliminateVars(), removeConstraint(), removeConstraintsInvolvingVarRange(), removeIndependentConstraints(), removeRedundantLocalVars(), and removeTrivialEqualities().
removeEqualityRange()
void IntegerRelation::removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
Definition at line 454 of file IntegerRelation.cpp.
References equalities.
Referenced by gaussianEliminate(), and truncate().
removeIndependentConstraints()
void IntegerRelation::removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) variables in the range [pos, pos + num).
Definition at line 2412 of file IntegerRelation.cpp.
References getIndependentConstraints(), getNumVars(), removeEquality(), and removeInequality().
Referenced by createSeparationCondition().
removeInequality()
void IntegerRelation::removeInequality (unsigned pos)
Definition at line 442 of file IntegerRelation.cpp.
References inequalities.
Referenced by mlir::presburger::MultiAffineFunction::getLexSet(), removeConstraint(), removeConstraintsInvolvingVarRange(), removeDuplicateConstraints(), and removeIndependentConstraints().
removeInequalityRange()
void IntegerRelation::removeInequalityRange (unsigned start, unsigned end)
Definition at line 460 of file IntegerRelation.cpp.
References inequalities.
Referenced by truncate().
removeRedundantConstraints()
void IntegerRelation::removeRedundantConstraints ()
Removes redundant constraints using Simplex.
Although the algorithm can theoretically take exponential time in the worst case (rare), it is known to perform much better in the average case. If V is the number of vertices in the polytope and C is the number of constraints, the algorithm takes O(VC) time.
Definition at line 1227 of file IntegerRelation.cpp.
References mlir::presburger::Simplex::detectRedundant(), equalities, gcdTightenInequalities(), getNumEqualities(), getNumInequalities(), inequalities, and mlir::presburger::Simplex::isMarkedRedundant().
removeRedundantInequalities()
void IntegerRelation::removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
Definition at line 1195 of file IntegerRelation.cpp.
References atIneq(), mlir::presburger::Matrix< T >::fillRow(), getNumCols(), getNumInequalities(), inequalities, IntegerRelation(), isEmpty(), and mlir::presburger::Matrix< T >::negateRow().
removeRedundantLocalVars()
void IntegerRelation::removeRedundantLocalVars () protected
Removes local variables using equalities.
Each equality is checked if it can be reduced to the form: e = affine-expr, where e is a local variable and affine-expr is an affine expression not containing e. If an equality satisfies this form, the local variable is replaced in each constraint and then removed. The equality used to replace this local variable is also removed.
Definition at line 1437 of file IntegerRelation.cpp.
References mlir::presburger::abs(), atEq(), eliminateFromConstraint(), equalities, getNumDimAndSymbolVars(), getNumEqualities(), getNumInequalities(), getNumVars(), removeEquality(), and removeVar().
Referenced by mlir::affine::FlatAffineRelation::compose(), and isEmpty().
removeTrivialEqualities()
void IntegerRelation::removeTrivialEqualities ()
Definition at line 2629 of file IntegerRelation.cpp.
References getEquality(), getNumEqualities(), rangeIsZero(), and removeEquality().
Referenced by isFullDim().
removeTrivialRedundancy()
void IntegerRelation::removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
A constraint of the form <non-negative constant> >= 0 is considered trivially true. This method is a linear time method on the constraints, does a single scan, and updates in place. It also normalizes constraints by their GCD and performs GCD tightening on inequalities.
A constraint of the form <non-negative constant> >= 0 is considered trivially true.
Definition at line 1915 of file IntegerRelation.cpp.
References atIneq(), gcdTightenInequalities(), getNumCols(), getNumInequalities(), inequalities, and normalizeConstraintsByGCD().
Referenced by createSeparationCondition(), fourierMotzkinEliminate(), mlir::affine::simplifyIntegerSet(), and unionBoundingBox().
removeVar() [1/2]
void IntegerRelation::removeVar (unsigned pos)
Removes the specified variable from the system.
Definition at line 382 of file IntegerRelation.cpp.
References removeVarRange().
removeVar() [2/2]
void IntegerRelation::removeVar (VarKind kind, unsigned pos)
Removes variables of the specified kind with the specified pos (or within the specified range) from the system.
The specified location is relative to the first variable of the specified kind.
Definition at line 378 of file IntegerRelation.cpp.
References removeVarRange().
Referenced by createSeparationCondition(), eliminateRedundantLocalVar(), fourierMotzkinEliminate(), and removeRedundantLocalVars().
removeVarRange() [1/2]
void IntegerRelation::removeVarRange (unsigned varStart, unsigned varLimit) protected
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Definition at line 400 of file IntegerRelation.cpp.
References mlir::presburger::Domain, getNumVarKind(), getNumVars(), getVarKindOffset(), mlir::presburger::Local, mlir::presburger::Range, removeVarRange(), and mlir::presburger::Symbol.
removeVarRange() [2/2]
void IntegerRelation::removeVarRange (VarKind kind, unsigned varStart, unsigned varLimit) virtual
Reimplemented in mlir::affine::FlatAffineRelation, and mlir::FlatLinearValueConstraints.
Definition at line 384 of file IntegerRelation.cpp.
References equalities, getNumVarKind(), getVarKindOffset(), inequalities, and space.
Referenced by findIntegerSample(), gaussianEliminateVars(), mergeAndCompose(), removeVar(), removeVar(), removeVarRange(), setAndEliminate(), and truncateVarKind().
resetIds()
void mlir::presburger::IntegerRelation::resetIds () inline
Definition at line 139 of file IntegerRelation.h.
References space.
Referenced by mlir::affine::checkMemrefAccessDependence(), and mlir::affine::MemRefAccess::getAccessRelation().
setAndEliminate() [1/2]
void IntegerRelation::setAndEliminate (unsigned pos, ArrayRef< DynamicAPInt > values)
Sets the values.size() variables starting at pos to the specified values and removes them.
Definition at line 550 of file IntegerRelation.cpp.
References equalities, getNumCols(), getNumVars(), inequalities, and removeVarRange().
Referenced by constantFoldVar(), findIntegerSample(), and setAndEliminate().
setAndEliminate() [2/2]
void mlir::presburger::IntegerRelation::setAndEliminate (unsigned pos, ArrayRef< int64_t > values) inline
Definition at line 396 of file IntegerRelation.h.
References mlir::presburger::getDynamicAPIntVec(), and setAndEliminate().
setDimSymbolSeparation()
void mlir::presburger::IntegerRelation::setDimSymbolSeparation (unsigned newSymbolCount) inline
Changes the partition between dimensions and symbols.
Depending on the new symbol count, either a chunk of dimensional variables immediately before the split become symbols, or some of the symbols immediately after the split become dimensions.
Definition at line 725 of file IntegerRelation.h.
References space.
Referenced by createFullTiles(), createSeparationCondition(), and turnSymbolIntoDim().
setId()
void IntegerRelation::setId (VarKind kind, unsigned i, Identifier id)
Set the identifier for the ith variable of the specified kind of the IntegerRelation's PresburgerSpace.
The index is relative to the kind of the variable.
Definition at line 67 of file IntegerRelation.cpp.
References mlir::presburger::Local, and space.
Referenced by mlir::affine::MemRefAccess::getAccessRelation(), and mlir::affine::getRelationFromMap().
setSpace()
void IntegerRelation::setSpace (const PresburgerSpace & oSpace)
Set the space to oSpace, which should have the same number of ids as the current space.
Definition at line 54 of file IntegerRelation.cpp.
References mlir::presburger::PresburgerSpace::getNumVars(), and space.
setSpaceExceptLocals()
void IntegerRelation::setSpaceExceptLocals (const PresburgerSpace & oSpace)
Set the space to oSpace, which should not have any local ids.
oSpace can have fewer ids than the current space; in that case, the the extra ids in this that are not accounted for by oSpace will be considered as local ids. oSpace should not have more ids than the current space; this will result in an assert failure.
Definition at line 59 of file IntegerRelation.cpp.
References mlir::presburger::PresburgerSpace::getNumLocalVars(), getNumVars(), mlir::presburger::PresburgerSpace::getNumVars(), mlir::presburger::Local, and space.
simplify()
void IntegerRelation::simplify ()
Simplify the constraint system by removing canonicalizing constraints and removing redundant constraints.
Definition at line 1417 of file IntegerRelation.cpp.
References mlir::changed, gaussianEliminate(), isObviouslyEmpty(), normalizeConstraintsByGCD(), and removeDuplicateConstraints().
Referenced by mlir::presburger::PresburgerRelation::simplify().
subtract()
PresburgerRelation IntegerRelation::subtract (const PresburgerRelation & set) const
Return the set difference of this set and the given set, i.e., return this \ set.
Definition at line 346 of file IntegerRelation.cpp.
References mlir::presburger::PresburgerRelation::subtract().
Referenced by mlir::presburger::IntegerPolyhedron::subtract().
swapVar()
void IntegerRelation::swapVar (unsigned posA, unsigned posB) virtual
Swap the posA^th variable with the posB^th variable.
Definition at line 466 of file IntegerRelation.cpp.
References equalities, getNumVars(), getVarKindOffset(), inequalities, and space.
Referenced by mlir::affine::MemRefAccess::getAccessRelation(), mlir::affine::FlatAffineRelation::inverse(), mergeAndAlignSymbols(), mlir::FlatLinearValueConstraints::mergeSymbolVars(), and turnSymbolIntoDim().
truncate()
void IntegerRelation::truncate (const CountsSnapshot & counts)
Definition at line 210 of file IntegerRelation.cpp.
References mlir::presburger::Domain, mlir::presburger::IntegerRelation::CountsSnapshot::getNumEqs(), getNumEqualities(), mlir::presburger::IntegerRelation::CountsSnapshot::getNumIneqs(), getNumInequalities(), mlir::presburger::Local, mlir::presburger::Range, removeEqualityRange(), removeInequalityRange(), mlir::presburger::Symbol, and truncateVarKind().
truncateVarKind() [1/2]
void IntegerRelation::truncateVarKind (VarKind kind, const CountsSnapshot & counts) protected
Truncate the vars to the number in the space of the specified CountsSnapshot.
Definition at line 205 of file IntegerRelation.cpp.
References mlir::presburger::PresburgerSpace::getNumVarKind(), mlir::presburger::IntegerRelation::CountsSnapshot::getSpace(), and truncateVarKind().
truncateVarKind() [2/2]
void IntegerRelation::truncateVarKind (VarKind kind, unsigned num) protected
Truncate the vars of the specified kind to the specified number by dropping some vars at the end.
num must be less than the current number.
Definition at line 199 of file IntegerRelation.cpp.
References getNumVarKind(), and removeVarRange().
Referenced by truncate(), and truncateVarKind().
unionBoundingBox()
LogicalResult IntegerRelation::unionBoundingBox (const IntegerRelation & other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
For each of the dimensions, the min of the lower bounds (symbolic) and the max of the upper bounds (symbolic) is computed to determine such a bounding box. other is expected to have the same dimensional variables as this constraint system (in the same order).
E.g.: 1) this = {0 <= d0 <= 127}, other = {16 <= d0 <= 192}, output = {0 <= d0 <= 192} 2) this = {s0 + 5 <= d0 <= s0 + 20}, other = {s0 + 1 <= d0 <= s0 + 9}, output = {s0 + 1 <= d0 <= s0 + 20} 3) this = {0 <= d0 <= 5, 1 <= d1 <= 9} other = {2 <= d0 <= 6, 5 <= d1 <= 15}, output = {0 <= d0 <= 6, 1 <= d1 <= 15}
Definition at line 2264 of file IntegerRelation.cpp.
References addInequality(), append(), clearConstraints(), getCommonConstraints(), getConstantBound(), getConstantBoundOnDimSize(), getNumCols(), getNumDimVars(), getNumLocalVars(), getNumSymbolVars(), mlir::presburger::PresburgerSpace::getRelationSpace(), getSpace(), IntegerRelation(), mlir::presburger::LB, removeTrivialRedundancy(), space, success(), and mlir::presburger::UB.
Member Data Documentation
equalities
IntMatrix mlir::presburger::IntegerRelation::equalities protected
Coefficients of affine equalities (in == 0 form).
Definition at line 963 of file IntegerRelation.h.
Referenced by addBound(), addEquality(), append(), atEq(), atEq(), atEq64(), clearConstraints(), convertVarKind(), eliminateRedundantLocalVar(), gaussianEliminate(), gaussianEliminateVars(), getEquality(), getEquality64(), getNumEqualities(), getNumReservedEqualities(), hasConsistentState(), insertVar(), IntegerRelation(), normalizeConstraintsByGCD(), removeEquality(), removeEqualityRange(), removeRedundantConstraints(), removeRedundantLocalVars(), removeVarRange(), setAndEliminate(), and swapVar().
inequalities
IntMatrix mlir::presburger::IntegerRelation::inequalities protected
Coefficients of affine inequalities (in >= 0 form).
Definition at line 966 of file IntegerRelation.h.
Referenced by addBound(), addBound(), addInequality(), append(), atIneq(), atIneq(), atIneq64(), clearConstraints(), convertVarKind(), eliminateRedundantLocalVar(), gaussianEliminate(), gaussianEliminateVars(), gcdTightenInequalities(), getInequalities(), getInequality(), getInequality64(), getNumInequalities(), getNumReservedInequalities(), hasConsistentState(), insertVar(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), IntegerRelation(), normalizeConstraintsByGCD(), removeDuplicateConstraints(), removeInequality(), removeInequalityRange(), removeRedundantConstraints(), removeRedundantInequalities(), removeTrivialRedundancy(), removeVarRange(), setAndEliminate(), and swapVar().
kExplosionFactor
unsigned mlir::presburger::IntegerRelation::kExplosionFactor = 32 static constexpr protected
A parameter that controls detection of an unrealistic number of constraints.
If the number of constraints is this many times the number of variables, we consider such a system out of line with the intended use case of IntegerRelation.
Definition at line 958 of file IntegerRelation.h.
Referenced by isEmpty().
space
PresburgerSpace mlir::presburger::IntegerRelation::space protected
Definition at line 960 of file IntegerRelation.h.
Referenced by append(), mlir::affine::FlatAffineRelation::compose(), mlir::FlatLinearValueConstraints::computeAlignedMap(), computeReprWithOnlyDivLocals(), convertVarKind(), getEmpty(), getIds(), mlir::FlatLinearValueConstraints::getMaybeValues(), getNumCols(), getNumDimAndSymbolVars(), getNumDimVars(), getNumDomainVars(), getNumLocalVars(), getNumRangeVars(), getNumSymbolVars(), getNumVarKind(), getNumVars(), getSpace(), getSpaceWithoutLocals(), mlir::presburger::IntegerPolyhedron::getUniverse(), getUniverse(), mlir::FlatLinearValueConstraints::getValue(), getVarKindAt(), getVarKindEnd(), getVarKindOffset(), getVarKindOverlap(), mlir::FlatLinearValueConstraints::hasValue(), insertVar(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), mlir::presburger::IntegerPolyhedron::IntegerPolyhedron(), IntegerRelation(), IntegerRelation(), isEqual(), isObviouslyEqual(), isSubsetOf(), mergeAndAlignSymbols(), mergeAndCompose(), printSpace(), removeVarRange(), resetIds(), setDimSymbolSeparation(), setId(), setSpace(), setSpaceExceptLocals(), mlir::FlatLinearValueConstraints::setValue(), swapVar(), and unionBoundingBox().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/IntegerRelation.h
lib/Analysis/Presburger/IntegerRelation.cpp