MLIR: mlir::tblgen::Pattern Class Reference
mlir::tblgen::Pattern Class Reference
#include "mlir/TableGen/Pattern.h"
Public Types
using IdentifierLine = std::pair<StringRef, unsigned>
Public Member Functions
Pattern (const llvm::Record *def, RecordOperatorMap *mapper)
DagNode getSourcePattern () const
int getNumResultPatterns () const
DagNode getResultPattern (unsigned index) const
void collectSourcePatternBoundSymbols (SymbolInfoMap &infoMap)
void collectResultPatternBoundSymbols (SymbolInfoMap &infoMap)
const Operator & getSourceRootOp ()
Operator & getDialectOp (DagNode node)
std::vector< AppliedConstraint > getConstraints () const
int getNumSupplementalPatterns () const
DagNode getSupplementalPattern (unsigned index) const
int getBenefit () const
std::vector< IdentifierLine > getLocation (bool forSourceOutput=false) const
void collectBoundSymbols (DagNode tree, SymbolInfoMap &infoMap, bool isSrcPattern)
Detailed Description
Definition at line 602 of file Pattern.h.
Member Typedef Documentation
IdentifierLine
using mlir::tblgen::Pattern::IdentifierLine = std::pair<StringRef, unsigned>
Definition at line 643 of file Pattern.h.
Constructor & Destructor Documentation
Pattern()
mlir::tblgen::Pattern::Pattern (const llvm::Record * def, RecordOperatorMap * mapper) explicit
Member Function Documentation
collectBoundSymbols()
void Pattern::collectBoundSymbols (DagNode tree, SymbolInfoMap & infoMap, bool isSrcPattern)
Definition at line 807 of file Pattern.cpp.
References mlir::tblgen::SymbolInfoMap::bindAttr(), mlir::tblgen::SymbolInfoMap::bindOpArgument(), mlir::tblgen::SymbolInfoMap::bindOpResult(), mlir::tblgen::SymbolInfoMap::bindProp(), mlir::tblgen::SymbolInfoMap::bindValue(), mlir::tblgen::SymbolInfoMap::bindValues(), mlir::tblgen::Constraint::CK_Attr, collectBoundSymbols(), mlir::tblgen::DagNode::getArgAsLeaf(), mlir::tblgen::DagNode::getArgAsNestedDag(), mlir::tblgen::DagNode::getArgName(), mlir::tblgen::DagLeaf::getAsConstraint(), mlir::tblgen::DagLeaf::getAsPropConstraint(), getDialectOp(), mlir::tblgen::DagNode::getNumArgs(), mlir::tblgen::DagNode::getNumReturnsOfNativeCode(), mlir::tblgen::DagNode::getSymbol(), mlir::tblgen::DagLeaf::isAttrMatcher(), mlir::tblgen::DagLeaf::isConstantAttr(), mlir::tblgen::DagLeaf::isEnumCase(), mlir::tblgen::DagNode::isNativeCodeCall(), mlir::tblgen::DagNode::isOperation(), mlir::tblgen::DagLeaf::isPropMatcher(), and mlir::tblgen::DagLeaf::isUnspecified().
Referenced by collectBoundSymbols(), collectResultPatternBoundSymbols(), and collectSourcePatternBoundSymbols().
collectResultPatternBoundSymbols()
void Pattern::collectResultPatternBoundSymbols (SymbolInfoMap & infoMap)
Definition at line 708 of file Pattern.cpp.
References collectBoundSymbols(), getNumResultPatterns(), and getResultPattern().
collectSourcePatternBoundSymbols()
void Pattern::collectSourcePatternBoundSymbols (SymbolInfoMap & infoMap)
Definition at line 698 of file Pattern.cpp.
References mlir::tblgen::SymbolInfoMap::assignUniqueAlternativeNames(), collectBoundSymbols(), and getSourcePattern().
getBenefit()
int mlir::tblgen::Pattern::getBenefit () const
getConstraints()
std::vector< AppliedConstraint > Pattern::getConstraints () const
Definition at line 725 of file Pattern.cpp.
getDialectOp()
Operator & Pattern::getDialectOp (DagNode node)
Definition at line 721 of file Pattern.cpp.
References mlir::tblgen::DagNode::getDialectOp().
Referenced by collectBoundSymbols().
getLocation()
std::vector< Pattern::IdentifierLine > Pattern::getLocation (bool forSourceOutput = false) const
Definition at line 776 of file Pattern.cpp.
References result.
getNumResultPatterns()
int Pattern::getNumResultPatterns () const
Definition at line 688 of file Pattern.cpp.
Referenced by collectResultPatternBoundSymbols().
getNumSupplementalPatterns()
int Pattern::getNumSupplementalPatterns () const
Definition at line 753 of file Pattern.cpp.
getResultPattern()
DagNode Pattern::getResultPattern (unsigned index) const
Definition at line 693 of file Pattern.cpp.
Referenced by collectResultPatternBoundSymbols().
getSourcePattern()
DagNode Pattern::getSourcePattern () const
Definition at line 684 of file Pattern.cpp.
Referenced by collectSourcePatternBoundSymbols(), and getSourceRootOp().
getSourceRootOp()
const Operator & Pattern::getSourceRootOp ()
Definition at line 717 of file Pattern.cpp.
References mlir::tblgen::DagNode::getDialectOp(), and getSourcePattern().
getSupplementalPattern()
DagNode Pattern::getSupplementalPattern (unsigned index) const
Definition at line 758 of file Pattern.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp