MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager Class Reference
Owning Wrapper around a PassManager.
Public Member Functions
PyPassManager (MlirPassManager passManager)
PyPassManager (PyPassManager &&other) noexcept
~PyPassManager ()
MlirPassManager get ()
void release ()
nb::object getCapsule ()
Static Public Member Functions
static nb::object createFromCapsule (const nb::object &capsule)
Detailed Description
Owning Wrapper around a PassManager.
Definition at line 29 of file Pass.cpp.
Constructor & Destructor Documentation
PyPassManager() [1/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::PyPassManager (MlirPassManager passManager) inline
Definition at line 31 of file Pass.cpp.
Referenced by createFromCapsule(), and PyPassManager().
PyPassManager() [2/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::PyPassManager (PyPassManager && other) inline noexcept
Definition at line 32 of file Pass.cpp.
References PyPassManager().
~PyPassManager()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::~PyPassManager () inline
Definition at line 36 of file Pass.cpp.
References mlirPassManagerDestroy(), and mlirPassManagerIsNull().
Member Function Documentation
createFromCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::createFromCapsule (const nb::object & capsule) inline static
Definition at line 47 of file Pass.cpp.
References mlirPassManagerIsNull(), mlirPythonCapsuleToPassManager(), and PyPassManager().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule().
get()
MlirPassManager mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::get () inline
Definition at line 40 of file Pass.cpp.
Referenced by getCapsule(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::getCapsule () inline
Definition at line 43 of file Pass.cpp.
References get(), and mlirPythonPassManagerToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule().
release()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::release () inline
Definition at line 42 of file Pass.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule().
The documentation for this class was generated from the following file:
lib/Bindings/Python/Pass.cpp