MLIR: mlir::tblgen::FmtStrVecObject Class Reference
mlir::tblgen::FmtStrVecObject Class Reference
#include "mlir/TableGen/Format.h"
Public Types
using StrFormatAdapter
Public Member Functions
FmtStrVecObject (StringRef fmt, const FmtContext *ctx, ArrayRef< std::string > params)
FmtStrVecObject (FmtStrVecObject const &that)=delete
FmtStrVecObject (FmtStrVecObject &&that)
Public Member Functions inherited from mlir::tblgen::FmtObjectBase
FmtObjectBase (StringRef fmt, const FmtContext *ctx, size_t numParams)
FmtObjectBase (const FmtObjectBase &that)=delete
FmtObjectBase (FmtObjectBase &&that)
void format (llvm::raw_ostream &s) const
std::string str () const
template<unsigned N>
SmallString< N > sstr () const
template<unsigned N>
operator SmallString< N > () const
operator std::string () const
Additional Inherited Members
Protected Attributes inherited from mlir::tblgen::FmtObjectBase
StringRef fmt
const FmtContext * context
std::vector< llvm::support::detail::format_adapter * > adapters
std::vector< FmtReplacement > replacements
Detailed Description
Definition at line 207 of file Format.h.
Member Typedef Documentation
StrFormatAdapter
using mlir::tblgen::FmtStrVecObject::StrFormatAdapter
Initial value:
 decltype(llvm::support::detail::build_format_adapter(
      std::declval<std::string>()))
Definition at line 209 of file Format.h.
Constructor & Destructor Documentation
FmtStrVecObject() [1/3]
FmtStrVecObject::FmtStrVecObject (StringRef fmt, const FmtContext * ctx, ArrayRef< std::string > params)
Definition at line 201 of file Format.cpp.
References mlir::tblgen::FmtObjectBase::adapters, mlir::tblgen::FmtObjectBase::fmt, mlir::tblgen::FmtObjectBase::FmtObjectBase(), and for().
Referenced by FmtStrVecObject(), and FmtStrVecObject().
FmtStrVecObject() [2/3]
mlir::tblgen::FmtStrVecObject::FmtStrVecObject (FmtStrVecObject const & that) delete
References FmtStrVecObject().
FmtStrVecObject() [3/3]
FmtStrVecObject::FmtStrVecObject (FmtStrVecObject && that)
Definition at line 214 of file Format.cpp.
References mlir::tblgen::FmtObjectBase::adapters, mlir::tblgen::FmtObjectBase::FmtObjectBase(), FmtStrVecObject(), and for().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Format.h
lib/TableGen/Format.cpp