MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock Class Reference
Wrapper around an MlirBlock.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyBlock (PyOperationRef parentOperation, MlirBlock block)
MlirBlock get ()
PyOperationRef & getParentOperation ()
void checkValid ()
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirBlock.
Detailed Description
Wrapper around an MlirBlock.
Blocks are managed completely by their containing operation. Unlike the C++ API, the python API does not support detached blocks.
Definition at line 825 of file IRCore.h.
Constructor & Destructor Documentation
PyBlock()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::PyBlock (PyOperationRef parentOperation, MlirBlock block) inline
Definition at line 827 of file IRCore.h.
References mlirBlockIsNull().
Member Function Documentation
checkValid()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::checkValid () inline
Definition at line 835 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::appendBlock(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::dunderGetItem().
get()
MlirBlock mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::get () inline
Definition at line 832 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors::bindDerived(), and getCapsule().
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::getCapsule ()
Gets a capsule wrapping the void* within the MlirBlock.
Definition at line 186 of file IRCore.cpp.
References get(), and mlirPythonBlockToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getParentOperation()
PyOperationRef & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::getParentOperation () inline
Definition at line 833 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp