MLIR: mlir::linalg::MatmulTransposeAOp Class Reference
mlir::linalg::MatmulTransposeAOp Class Reference
Specialization of linalg.matmul op that has a transpose map on A.
#include "mlir/Dialect/Linalg/IR/Linalg.h"
Static Public Member Functions
::mlir::TypeID resolveTypeID ()
static void build (OpBuilder &builder, OperationState &result, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
Build a transpose A matmul.
static MatmulTransposeAOp create (OpBuilder &builder, Location location, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
static void build (OpBuilder &builder, OperationState &result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
Build a transpose A matmul with a specific result type.
static MatmulTransposeAOp create (OpBuilder &builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
static void build (OpBuilder &builder, OperationState &result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes={})
Build a transpose A matmul with a specific result type and a cast type.
static MatmulTransposeAOp create (OpBuilder &builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes={})
static bool isDefaultIndexingMaps (Attribute attr)
Checks if the affine map is the expected one for this operation.
static bool classof (Operation *op)
Detailed Description
Specialization of linalg.matmul op that has a transpose map on A.
Definition at line 157 of file Linalg.h.
Member Function Documentation
build() [1/3]
void mlir::linalg::linalg::MatmulTransposeAOp::build (OpBuilder & builder, OperationState & result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose A matmul with a specific result type.
Definition at line 4012 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
build() [2/3]
void mlir::linalg::linalg::MatmulTransposeAOp::build (OpBuilder & builder, OperationState & result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose A matmul with a specific result type and a cast type.
Definition at line 4033 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
build() [3/3]
void mlir::linalg::linalg::MatmulTransposeAOp::build (OpBuilder & builder, OperationState & result, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose A matmul.
Definition at line 3993 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
Referenced by create(), create(), and create().
classof()
bool mlir::linalg::MatmulTransposeAOp::classof (Operation * op) static
Definition at line 4056 of file LinalgOps.cpp.
References mlir::Operation::getAttr(), and isDefaultIndexingMaps().
create() [1/3]
MatmulTransposeAOp mlir::linalg::MatmulTransposeAOp::create (OpBuilder & builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4022 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
create() [2/3]
MatmulTransposeAOp mlir::linalg::MatmulTransposeAOp::create (OpBuilder & builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4045 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
create() [3/3]
MatmulTransposeAOp mlir::linalg::MatmulTransposeAOp::create (OpBuilder & builder, Location location, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4002 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
Referenced by mlir::linalg::transposeMatmul().
isDefaultIndexingMaps()
bool mlir::linalg::MatmulTransposeAOp::isDefaultIndexingMaps (Attribute attr) static
Checks if the affine map is the expected one for this operation.
Definition at line 3979 of file LinalgOps.cpp.
References mlir::linalg::getAffineResultPositions().
Referenced by classof().
resolveTypeID()
::mlir::TypeID mlir::linalg::MatmulTransposeAOp::resolveTypeID () inline static
Definition at line 163 of file Linalg.h.
References mlir::TypeID::get().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/IR/Linalg.h
lib/Dialect/Linalg/IR/LinalgOps.cpp