MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet Class Reference
#include "Bindings/Python/Rewrite.h"
Public Member Functions
PyRewritePatternSet (MlirContext ctx)
Create an owned pattern set.
PyRewritePatternSet (MlirRewritePatternSet patterns)
Create a non-owning reference to an existing pattern set.
~PyRewritePatternSet ()
MlirRewritePatternSet get () const
bool isOwned () const
void add (nanobind::handle root, const nanobind::callable &matchAndRewrite, unsigned benefit)
Add a new rewrite pattern to the pattern set.
void addConversion (nanobind::handle root, const nanobind::callable &matchAndRewrite, PyTypeConverter &typeConverter, unsigned benefit)
Add a new conversion pattern to the pattern set.
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 83 of file Rewrite.h.
Constructor & Destructor Documentation
PyRewritePatternSet() [1/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::PyRewritePatternSet (MlirContext ctx)
Create an owned pattern set.
Definition at line 72 of file Rewrite.cpp.
References mlirRewritePatternSetCreate(), and true.
Referenced by bind().
PyRewritePatternSet() [2/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::PyRewritePatternSet (MlirRewritePatternSet patterns)
Create a non-owning reference to an existing pattern set.
Definition at line 75 of file Rewrite.cpp.
References false.
~PyRewritePatternSet()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::~PyRewritePatternSet ()
Definition at line 78 of file Rewrite.cpp.
References mlirRewritePatternSetDestroy().
Member Function Documentation
add()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::add (nanobind::handle root, const nanobind::callable & matchAndRewrite, unsigned benefit)
Add a new rewrite pattern to the pattern set.
Definition at line 87 of file Rewrite.cpp.
References MlirRewritePatternCallbacks::construct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::createOpView(), MlirRewritePatternCallbacks::destruct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::forOperation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::logicalResultFromObject(), MlirRewritePatternCallbacks::matchAndRewrite, mlirOperationGetContext(), mlirOpRewritePatternCreate(), mlirRewritePatternSetAdd(), mlirRewritePatternSetGetContext(), mlirStringRefCreate(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::operationNameFromObject().
Referenced by bind().
addConversion()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::addConversion (nanobind::handle root, const nanobind::callable & matchAndRewrite, PyTypeConverter & typeConverter, unsigned benefit)
Add a new conversion pattern to the pattern set.
Definition at line 222 of file Rewrite.cpp.
References MlirConversionPatternCallbacks::construct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::createOpView(), MlirStringRef::data, MlirConversionPatternCallbacks::destruct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::forOperation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::get(), MlirStringRef::length, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::logicalResultFromObject(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::lookupOpAdaptorClass(), MlirConversionPatternCallbacks::matchAndRewrite, mlirConversionPatternAsRewritePattern(), mlirIdentifierStr(), mlirOpConversionPatternCreate(), mlirOperationGetContext(), mlirOperationGetName(), mlirRewritePatternSetAdd(), mlirRewritePatternSetGetContext(), mlirStringRefCreate(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::operationNameFromObject().
Referenced by bind().
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::bind (nanobind::module_ & m) static
Definition at line 374 of file Rewrite.cpp.
References add(), addConversion(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::get(), and PyRewritePatternSet().
get()
MlirRewritePatternSet mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::get () const
Definition at line 83 of file Rewrite.cpp.
isOwned()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::isOwned () const
Definition at line 85 of file Rewrite.cpp.
The documentation for this class was generated from the following files:
lib/Bindings/Python/Rewrite.h
lib/Bindings/Python/Rewrite.cpp