MLIR: mlir::query::matcher::RegistryManager Class Reference
mlir::query::matcher::RegistryManager Class Reference
#include "Query/Matcher/RegistryManager.h"
Public Member Functions
RegistryManager ()=delete
Static Public Member Functions
static std::optional< MatcherCtor > lookupMatcherCtor (llvm::StringRef matcherName, const Registry &matcherRegistry)
static std::vector< ArgKind > getAcceptedCompletionTypes (llvm::ArrayRef< std::pair< MatcherCtor, unsigned >> context)
static std::vector< MatcherCompletion > getMatcherCompletions (ArrayRef< ArgKind > acceptedTypes, const Registry &matcherRegistry)
static VariantMatcher constructMatcher (MatcherCtor ctor, internal::SourceRange nameRange, llvm::StringRef functionName, ArrayRef< ParserValue > args, internal::Diagnostics *error)
Detailed Description
Definition at line 47 of file RegistryManager.h.
Constructor & Destructor Documentation
RegistryManager()
mlir::query::matcher::RegistryManager::RegistryManager () delete
Member Function Documentation
constructMatcher()
VariantMatcher mlir::query::matcher::RegistryManager::constructMatcher (MatcherCtor ctor, internal::SourceRange nameRange, llvm::StringRef functionName, llvm::ArrayRef< ParserValue > args, internal::Diagnostics * error) static
Definition at line 135 of file RegistryManager.cpp.
References mlir::query::matcher::internal::Diagnostics::addError(), mlir::query::matcher::internal::MatcherDescriptor::create(), mlir::query::matcher::VariantMatcher::getDynMatcher(), mlir::query::matcher::VariantMatcher::isNull(), mlir::query::matcher::internal::RegistryNotBindable, and mlir::query::matcher::VariantMatcher::SingleMatcher().
Referenced by mlir::query::matcher::internal::Parser::RegistrySema::actOnMatcherExpression().
getAcceptedCompletionTypes()
std::vector< ArgKind > mlir::query::matcher::RegistryManager::getAcceptedCompletionTypes (llvm::ArrayRef< std::pair< MatcherCtor, unsigned >> context) static
Definition at line 55 of file RegistryManager.cpp.
References mlir::query::matcher::internal::MatcherDescriptor::getArgKinds(), mlir::query::matcher::internal::MatcherDescriptor::isVariadic(), and mlir::query::matcher::Matcher.
Referenced by mlir::query::matcher::internal::Parser::RegistrySema::getAcceptedCompletionTypes().
getMatcherCompletions()
std::vector< MatcherCompletion > mlir::query::matcher::RegistryManager::getMatcherCompletions (llvm::ArrayRef< ArgKind > acceptedTypes, const Registry & matcherRegistry) static
Definition at line 77 of file RegistryManager.cpp.
References mlir::query::matcher::Registry::constructors(), mlir::query::matcher::internal::MatcherDescriptor::getArgKinds(), mlir::query::matcher::internal::MatcherDescriptor::getNumArgs(), mlir::query::matcher::internal::MatcherDescriptor::isVariadic(), kind, mlir::query::matcher::Matcher, and mlir::query::matcher::String.
Referenced by mlir::query::matcher::internal::Parser::RegistrySema::getMatcherCompletions().
lookupMatcherCtor()
std::optional< MatcherCtor > mlir::query::matcher::RegistryManager::lookupMatcherCtor (llvm::StringRef matcherName, const Registry & matcherRegistry) static
Definition at line 47 of file RegistryManager.cpp.
References mlir::query::matcher::Registry::constructors().
Referenced by mlir::query::matcher::internal::Parser::RegistrySema::lookupMatcherCtor().
The documentation for this class was generated from the following files:
lib/Query/Matcher/RegistryManager.h
lib/Query/Matcher/RegistryManager.cpp