MLIR: mlir::RankedTensorType::Builder Class Reference
mlir::RankedTensorType::Builder Class Reference
This is a builder type that keeps local references to arguments.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
Builder (RankedTensorType other)
Build from another RankedTensorType.
Builder (ArrayRef< int64_t > shape, Type elementType, Attribute encoding)
Build from scratch.
Builder & setShape (ArrayRef< int64_t > newShape)
Builder & setElementType (Type newElementType)
Builder & setEncoding (Attribute newEncoding)
Builder & dropDim (unsigned pos)
Erase a dim from shape @pos.
Builder & insertDim (int64_t val, unsigned pos)
Insert a val into shape @pos.
operator RankedTensorType ()
Detailed Description
This is a builder type that keeps local references to arguments.
Arguments that are passed into the builder must outlive the builder.
Definition at line 230 of file BuiltinTypes.h.
Constructor & Destructor Documentation
Builder() [1/2]
mlir::RankedTensorType::Builder::Builder (RankedTensorType other) inline explicit
Build from another RankedTensorType.
Definition at line 233 of file BuiltinTypes.h.
References getElementType(), and getShape().
Referenced by dropDim(), insertDim(), setElementType(), setEncoding(), and setShape().
Builder() [2/2]
mlir::RankedTensorType::Builder::Builder (ArrayRef< int64_t > shape, Type elementType, Attribute encoding) inline
Build from scratch.
Definition at line 238 of file BuiltinTypes.h.
Member Function Documentation
dropDim()
Builder & mlir::RankedTensorType::Builder::dropDim (unsigned pos) inline
Erase a dim from shape @pos.
Definition at line 257 of file BuiltinTypes.h.
References Builder().
Referenced by mlir::linalg::DownscaleConv2DOp::returningMatchAndRewrite(), mlir::linalg::DownscaleDepthwiseConv2DNhwcHwcOp::returningMatchAndRewrite(), and mlir::linalg::DownscaleSizeOneWindowed2DConvolution< Conv2DOp, Conv1DOp >::returningMatchAndRewrite().
insertDim()
Builder & mlir::RankedTensorType::Builder::insertDim (int64_t val, unsigned pos) inline
Insert a val into shape @pos.
Definition at line 264 of file BuiltinTypes.h.
References Builder().
Referenced by mlir::linalg::splitReductionByScaling().
operator RankedTensorType()
mlir::RankedTensorType::Builder::operator RankedTensorType () inline
Definition at line 270 of file BuiltinTypes.h.
setElementType()
Builder & mlir::RankedTensorType::Builder::setElementType (Type newElementType) inline
Definition at line 246 of file BuiltinTypes.h.
References Builder().
setEncoding()
Builder & mlir::RankedTensorType::Builder::setEncoding (Attribute newEncoding) inline
Definition at line 251 of file BuiltinTypes.h.
References Builder().
setShape()
Builder & mlir::RankedTensorType::Builder::setShape (ArrayRef< int64_t > newShape) inline
Definition at line 241 of file BuiltinTypes.h.
References Builder().
Referenced by mlir::tensor::computeTransposedType(), mlir::linalg::lowerPack(), mlir::linalg::lowerUnPack(), and permuteShape().
The documentation for this class was generated from the following file:
include/mlir/IR/BuiltinTypes.h