MLIR: mlir::tblgen::Attribute Class Reference
mlir::tblgen::Attribute Class Reference
#include "mlir/TableGen/Attribute.h"
Public Member Functions
Attribute (const llvm::Record *record)
Attribute (const llvm::DefInit *init)
StringRef getStorageType () const
StringRef getReturnType () const
std::optional< Type > getValueType () const
StringRef getConvertFromStorageCall () const
bool isConstBuildable () const
StringRef getConstBuilderTemplate () const
Attribute getBaseAttr () const
bool hasDefaultValue () const
StringRef getDefaultValue () const
bool isOptional () const
bool isDerivedAttr () const
bool isTypeAttr () const
bool isSymbolRefAttr () const
bool isEnumAttr () const
StringRef getAttrDefName () const
StringRef getDerivedCodeBody () const
Dialect getDialect () const
const llvm::Record & getDef () const
Public Member Functions inherited from mlir::tblgen::AttrConstraint
bool isSubClassOf (StringRef className) const
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
Constraints are pointer-comparable.
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getSummary () const
StringRef getDescription () const
StringRef getDefName () const
Returns the name of the TablGen def of this constraint.
std::string getUniqueDefName () const
Returns a unique name for the TablGen def of this constraint.
std::optional< StringRef > getCppFunctionName () const
Returns the name of the C++ function that should be generated for this constraint, or std::nullopt if no C++ function should be generated.
Kind getKind () const
const llvm::Record & getDef () const
Return the underlying def.
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind {
CK_Attr , CK_Prop , CK_Region , CK_Successor ,
CK_Type , CK_Uncategorized
}
Static Public Member Functions inherited from mlir::tblgen::AttrConstraint
static bool classof (const Constraint *c)
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 46 of file Attribute.h.
Constructor & Destructor Documentation
Attribute() [1/2]
mlir::tblgen::Attribute::Attribute (const llvm::Record * record) explicit
Referenced by Attribute(), and getBaseAttr().
Attribute() [2/2]
mlir::tblgen::Attribute::Attribute (const llvm::DefInit * init) explicit
References Attribute().
Member Function Documentation
getAttrDefName()
StringRef Attribute::getAttrDefName () const
Definition at line 112 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getBaseAttr().
getBaseAttr()
Attribute Attribute::getBaseAttr () const
Definition at line 93 of file Attribute.cpp.
References Attribute(), and mlir::tblgen::Constraint::def.
Referenced by getAttrDefName().
getConstBuilderTemplate()
StringRef Attribute::getConstBuilderTemplate () const
Definition at line 88 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getConvertFromStorageCall()
StringRef Attribute::getConvertFromStorageCall () const
Definition at line 78 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getDef()
const Record & Attribute::getDef () const
Definition at line 133 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getDefaultValue()
StringRef Attribute::getDefaultValue () const
Definition at line 105 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getDerivedCodeBody()
StringRef Attribute::getDerivedCodeBody () const
Definition at line 119 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and isDerivedAttr().
getDialect()
Dialect mlir::tblgen::Attribute::getDialect () const
getReturnType()
StringRef Attribute::getReturnType () const
Definition at line 65 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getStorageType()
StringRef Attribute::getStorageType () const
Definition at line 57 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getValueType()
std::optional< Type > Attribute::getValueType () const
Definition at line 72 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
hasDefaultValue()
bool Attribute::hasDefaultValue () const
Definition at line 100 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
isConstBuildable()
bool Attribute::isConstBuildable () const
Definition at line 83 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
isDerivedAttr()
bool Attribute::isDerivedAttr () const
Definition at line 44 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
Referenced by getDerivedCodeBody().
isEnumAttr()
bool Attribute::isEnumAttr () const
Definition at line 55 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
isOptional()
bool mlir::tblgen::Attribute::isOptional () const
isSymbolRefAttr()
bool Attribute::isSymbolRefAttr () const
Definition at line 48 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and mlir::tblgen::AttrConstraint::isSubClassOf().
isTypeAttr()
bool Attribute::isTypeAttr () const
Definition at line 46 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Attribute.h
lib/TableGen/Attribute.cpp