MLIR: mlir::OpTrait::OneResult< ConcreteType > Class Template Reference
mlir::OpTrait::OneResult< ConcreteType > Class Template Reference
This class provides return value APIs for ops that are known to have a single result.
#include "mlir/IR/OpDefinition.h"
Public Member Functions
void replaceAllUsesWith (Value newValue)
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
void replaceAllUsesWith (Operation *op)
Replace all uses of 'this' value with the result of 'op'.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, OneResult >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::OneResult< ConcreteType >
This class provides return value APIs for ops that are known to have a single result.
ResultType is the concrete type returned by getType().
Definition at line 673 of file OpDefinition.h.
Member Function Documentation
replaceAllUsesWith() [1/2]
template<typename ConcreteType > void mlir::OpTrait::OneResult< ConcreteType >::replaceAllUsesWith (Operation * op) inline
Replace all uses of 'this' value with the result of 'op'.
Definition at line 683 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, OneResult >::getOperation(), and mlir::Operation::replaceAllUsesWith().
replaceAllUsesWith() [2/2]
template<typename ConcreteType > void mlir::OpTrait::OneResult< ConcreteType >::replaceAllUsesWith (Value newValue) inline
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
When this returns there are zero uses of 'this'.
Definition at line 678 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, OneResult >::getOperation(), mlir::Operation::getResult(), and mlir::Value::replaceAllUsesWith().
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::OneResult< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 687 of file OpDefinition.h.
References mlir::OpTrait::impl::verifyOneResult().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h