MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet Class Reference
Owning Wrapper around a FrozenRewritePatternSet.
Public Member Functions
PyFrozenRewritePatternSet (MlirFrozenRewritePatternSet set)
PyFrozenRewritePatternSet (PyFrozenRewritePatternSet &&other) noexcept
~PyFrozenRewritePatternSet ()
MlirFrozenRewritePatternSet get ()
nb::object getCapsule ()
Static Public Member Functions
static nb::object createFromCapsule (const nb::object &capsule)
Detailed Description
Owning Wrapper around a FrozenRewritePatternSet.
Definition at line 344 of file Rewrite.cpp.
Constructor & Destructor Documentation
PyFrozenRewritePatternSet() [1/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet::PyFrozenRewritePatternSet (MlirFrozenRewritePatternSet set) inline
Definition at line 346 of file Rewrite.cpp.
Referenced by createFromCapsule(), and PyFrozenRewritePatternSet().
PyFrozenRewritePatternSet() [2/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet::PyFrozenRewritePatternSet (PyFrozenRewritePatternSet && other) inline noexcept
Definition at line 347 of file Rewrite.cpp.
References PyFrozenRewritePatternSet().
~PyFrozenRewritePatternSet()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet::~PyFrozenRewritePatternSet () inline
Definition at line 351 of file Rewrite.cpp.
References mlirFrozenRewritePatternSetDestroy().
Member Function Documentation
createFromCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet::createFromCapsule (const nb::object & capsule) inline static
Definition at line 362 of file Rewrite.cpp.
References mlirPythonCapsuleToFrozenRewritePatternSet(), and PyFrozenRewritePatternSet().
get()
MlirFrozenRewritePatternSet mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet::get () inline
Definition at line 355 of file Rewrite.cpp.
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFrozenRewritePatternSet::getCapsule () inline
Definition at line 357 of file Rewrite.cpp.
References mlir::get(), and mlirPythonFrozenRewritePatternSetToCapsule().
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.cpp