MLIR: mlir::CallGraphNode::Edge Class Reference
mlir::CallGraphNode::Edge Class Reference
This class represents a directed edge between two nodes in the callgraph.
#include "mlir/Analysis/CallGraph.h"
Public Member Functions
bool isAbstract () const
Returns true if this edge represents an Abstract edge.
bool isCall () const
Returns true if this edge represents a Call edge.
bool isChild () const
Returns true if this edge represents a Child edge.
CallGraphNode * getTarget () const
Returns the target node for this edge.
bool operator== (const Edge &edge) const
Friends
class CallGraphNode
Detailed Description
This class represents a directed edge between two nodes in the callgraph.
Definition at line 43 of file CallGraph.h.
Member Function Documentation
getTarget()
CallGraphNode * mlir::CallGraphNode::Edge::getTarget () const inline
Returns the target node for this edge.
Definition at line 73 of file CallGraph.h.
References CallGraphNode.
Referenced by mlir::CallGraph::eraseNode(), and llvm::GraphTraits< const mlir::CallGraphNode * >::unwrap().
isAbstract()
bool mlir::CallGraphNode::Edge::isAbstract () const inline
Returns true if this edge represents an Abstract edge.
Definition at line 64 of file CallGraph.h.
isCall()
bool mlir::CallGraphNode::Edge::isCall () const inline
Returns true if this edge represents a Call edge.
Definition at line 67 of file CallGraph.h.
isChild()
bool mlir::CallGraphNode::Edge::isChild () const inline
Returns true if this edge represents a Child edge.
Definition at line 70 of file CallGraph.h.
Referenced by mlir::CallGraphNode::hasChildren().
operator==()
bool mlir::CallGraphNode::Edge::operator== (const Edge & edge) const inline
Definition at line 75 of file CallGraph.h.
Friends And Related Symbol Documentation
CallGraphNode
friend class CallGraphNode friend
Definition at line 88 of file CallGraph.h.
References CallGraphNode.
Referenced by CallGraphNode, and getTarget().
The documentation for this class was generated from the following file:
include/mlir/Analysis/CallGraph.h