MLIR: mlir::remark::RemarkId Class Reference
mlir::remark::RemarkId Class Reference
A unique identifier for a remark, used to link related remarks together.
#include "mlir/IR/Remarks.h"
Public Member Functions
RemarkId ()
RemarkId (uint64_t id)
operator bool () const
Check if this is a valid (non-zero) ID.
uint64_t getValue () const
Get the raw ID value.
bool operator== (const RemarkId &other) const
bool operator!= (const RemarkId &other) const
void print (llvm::raw_ostream &os) const
Print the ID.
Detailed Description
A unique identifier for a remark, used to link related remarks together.
An invalid/empty ID has value 0.
Definition at line 36 of file Remarks.h.
Constructor & Destructor Documentation
RemarkId() [1/2]
mlir::remark::RemarkId::RemarkId () inline
Definition at line 38 of file Remarks.h.
Referenced by operator!=(), and operator==().
RemarkId() [2/2]
mlir::remark::RemarkId::RemarkId (uint64_t id) inline explicit
Definition at line 39 of file Remarks.h.
Member Function Documentation
getValue()
uint64_t mlir::remark::RemarkId::getValue () const inline
Get the raw ID value.
Definition at line 45 of file Remarks.h.
Referenced by mlir::remark::detail::Remark::addRelatedRemark().
operator bool()
mlir::remark::RemarkId::operator bool () const inline explicit
Check if this is a valid (non-zero) ID.
Definition at line 42 of file Remarks.h.
operator!=()
bool mlir::remark::RemarkId::operator!= (const RemarkId & other) const inline
Definition at line 48 of file Remarks.h.
References RemarkId().
operator==()
bool mlir::remark::RemarkId::operator== (const RemarkId & other) const inline
Definition at line 47 of file Remarks.h.
References RemarkId().
print()
void mlir::remark::RemarkId::print (llvm::raw_ostream & os) const inline
Print the ID.
Definition at line 51 of file Remarks.h.
The documentation for this class was generated from the following file:
include/mlir/IR/Remarks.h