MLIR: mlir::tblgen::AttrConstraint Class Reference
mlir::tblgen::AttrConstraint Class Reference
#include "mlir/TableGen/Attribute.h"
Public Member Functions
AttrConstraint (const llvm::Record *record)
bool isSubClassOf (StringRef className) const
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getSummary () const
Kind getKind () const
const void * getAsOpaquePointer () const
Get an opaque pointer to the constraint.
Static Public Member Functions
static bool classof (const Constraint *c)
Static Public Member Functions inherited from mlir::tblgen::Constraint
static Constraint getFromOpaquePointer (const void *ptr)
Construct a constraint from the opaque pointer representation.
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind {
CK_Attr, CK_Region, CK_Successor, CK_Type,
CK_Uncategorized
}
Protected Member Functions inherited from mlir::tblgen::Constraint
Constraint (Kind kind, const llvm::Record *record)
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 33 of file Attribute.h.
Constructor & Destructor Documentation
AttrConstraint()
AttrConstraint::AttrConstraint (const llvm::Record * record) explicit
Definition at line 34 of file Attribute.cpp.
References isSubClassOf().
Referenced by isSubClassOf().
Member Function Documentation
classof()
static bool mlir::tblgen::AttrConstraint::classof (const Constraint * c) inline static
Definition at line 37 of file Attribute.h.
References mlir::tblgen::Constraint::getKind().
isSubClassOf()
bool AttrConstraint::isSubClassOf (StringRef className) const
Definition at line 40 of file Attribute.cpp.
References AttrConstraint(), mlir::tblgen::Attribute::Attribute(), and mlir::tblgen::Constraint::def.
Referenced by AttrConstraint(), mlir::tblgen::EnumAttr::classof(), mlir::tblgen::EnumAttr::EnumAttr(), mlir::tblgen::EnumAttrCase::EnumAttrCase(), mlir::tblgen::EnumAttr::isBitEnum(), mlir::tblgen::Attribute::isDerivedAttr(), mlir::tblgen::Attribute::isEnumAttr(), mlir::tblgen::EnumAttrCase::isStrCase(), mlir::tblgen::Attribute::isSymbolRefAttr(), mlir::tblgen::Attribute::isTypeAttr(), and mlir::tblgen::StructAttr::StructAttr().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Attribute.h
lib/TableGen/Attribute.cpp