MLIR: mlir::OpAsmParser Class Reference
mlir::OpAsmParser Class Reference abstract
The OpAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
#include "mlir/IR/OpImplementation.h"
Classes
struct OperandType
This is the representation of an operand reference.
Public Types
enum Delimiter {
Delimiter::None, Delimiter::Paren, Delimiter::Square, Delimiter::OptionalParen,
Delimiter::OptionalSquare
}
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList and parseRegionArgumentList.
Public Member Functions
virtual ~OpAsmParser ()
virtual InFlightDiagnostic emitError (llvm::SMLoc loc, const Twine &message={})=0
Emit a diagnostic at the specified location and return failure.
virtual Builder & getBuilder () const =0
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
virtual llvm::SMLoc getCurrentLocation ()=0
Get the location of the next token and store it into the argument.
ParseResult getCurrentLocation (llvm::SMLoc *loc)
virtual std::pair< StringRef, unsigned > getResultName (unsigned resultNo) const =0
Return the name of the specified result in the specified syntax, as well as the sub-element in the name.
virtual size_t getNumResults () const =0
Return the number of declared SSA results.
virtual llvm::SMLoc getNameLoc () const =0
Return the location of the original name token.
virtual Location getEncodedSourceLoc (llvm::SMLoc loc)=0
Re-encode the given source location as an MLIR location and return it.
virtual Operation * parseGenericOperation (Block *insertBlock, Block::iterator insertPt)=0
Parse an operation in its generic form.
virtual ParseResult parseArrow ()=0
Parse a '->' token.
virtual ParseResult parseOptionalArrow ()=0
Parse a '->' token if present.
virtual ParseResult parseLBrace ()=0
Parse a { token.
virtual ParseResult parseOptionalLBrace ()=0
Parse a { token if present.
virtual ParseResult parseRBrace ()=0
Parse a } token.
virtual ParseResult parseOptionalRBrace ()=0
Parse a } token if present.
virtual ParseResult parseColon ()=0
Parse a : token.
virtual ParseResult parseOptionalColon ()=0
Parse a : token if present.
virtual ParseResult parseComma ()=0
Parse a , token.
virtual ParseResult parseOptionalComma ()=0
Parse a , token if present.
virtual ParseResult parseEqual ()=0
Parse a = token.
virtual ParseResult parseOptionalEqual ()=0
Parse a = token if present.
virtual ParseResult parseLess ()=0
Parse a '<' token.
virtual ParseResult parseOptionalLess ()=0
Parse a '<' token if present.
virtual ParseResult parseGreater ()=0
Parse a '>' token.
virtual ParseResult parseOptionalGreater ()=0
Parse a '>' token if present.
virtual ParseResult parseQuestion ()=0
Parse a '?' token.
virtual ParseResult parseOptionalQuestion ()=0
Parse a '?' token if present.
virtual ParseResult parsePlus ()=0
Parse a '+' token.
virtual ParseResult parseOptionalPlus ()=0
Parse a '+' token if present.
virtual ParseResult parseStar ()=0
Parse a '*' token.
virtual ParseResult parseOptionalStar ()=0
Parse a '*' token if present.
ParseResult parseKeyword (StringRef keyword, const Twine &msg="")
Parse a given keyword.
ParseResult parseKeyword (StringRef *keyword)
Parse a keyword into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef keyword)=0
Parse the given keyword if present.
virtual ParseResult parseOptionalKeyword (StringRef *keyword)=0
Parse a keyword, if present, into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef *keyword, ArrayRef< StringRef > allowedValues)=0
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
virtual ParseResult parseLParen ()=0
Parse a (token.
virtual ParseResult parseOptionalLParen ()=0
Parse a (token if present.
virtual ParseResult parseRParen ()=0
Parse a) token.
virtual ParseResult parseOptionalRParen ()=0
Parse a) token if present.
virtual ParseResult parseLSquare ()=0
Parse a [ token.
virtual ParseResult parseOptionalLSquare ()=0
Parse a [ token if present.
virtual ParseResult parseRSquare ()=0
Parse a ] token.
virtual ParseResult parseOptionalRSquare ()=0
Parse a ] token if present.
virtual ParseResult parseOptionalEllipsis ()=0
Parse a ... token if present;.
template<typename IntT >
ParseResult parseInteger (IntT &result)
Parse an integer value from the stream.
virtual OptionalParseResult parseOptionalInteger (APInt &result)=0
Parse an optional integer value from the stream.
template<typename IntT >
OptionalParseResult parseOptionalInteger (IntT &result)
virtual ParseResult parseAttribute (Attribute &result, Type type={})=0
Parse an arbitrary attribute of a given type and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type={})
Parse an attribute of a specific kind and type.
ParseResult parseAttribute (Attribute &result, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an attribute of a specific kind and type.
virtual OptionalParseResult parseOptionalAttribute (Attribute &result, Type type, StringRef attrName, NamedAttrList &attrs)=0
Parse an optional attribute.
template<typename AttrT >
OptionalParseResult parseOptionalAttribute (AttrT &result, StringRef attrName, NamedAttrList &attrs)
virtual OptionalParseResult parseOptionalAttribute (ArrayAttr &result, Type type, StringRef attrName, NamedAttrList &attrs)=0
Specialized variants of parseOptionalAttribute that remove potential ambiguities in syntax.
virtual OptionalParseResult parseOptionalAttribute (StringAttr &result, Type type, StringRef attrName, NamedAttrList &attrs)=0
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute of a given type and return it in result.
virtual ParseResult parseOptionalAttrDict (NamedAttrList &result)=0
Parse a named dictionary into 'result' if it is present.
virtual ParseResult parseOptionalAttrDictWithKeyword (NamedAttrList &result)=0
Parse a named dictionary into 'result' if the attributes keyword is present.
virtual ParseResult parseAffineMap (AffineMap &map)=0
Parse an affine map instance into 'map'.
virtual ParseResult printIntegerSet (IntegerSet &set)=0
Parse an integer set instance into 'set'.
ParseResult parseSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)=0
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalLocationSpecifier (Optional< Location > &result)=0
Parse a loc(...) specifier if present, filling in result if so.
virtual ParseResult parseOperand (OperandType &result)=0
Parse a single operand.
virtual OptionalParseResult parseOptionalOperand (OperandType &result)=0
Parse a single operand if present.
virtual ParseResult parseOperandList (SmallVectorImpl< OperandType > &result, int requiredOperandCount=-1, Delimiter delimiter=Delimiter::None)=0
Parse zero or more SSA comma-separated operand references with a specified surrounding delimiter, and an optional required operand count.
ParseResult parseOperandList (SmallVectorImpl< OperandType > &result, Delimiter delimiter)
virtual ParseResult parseTrailingOperandList (SmallVectorImpl< OperandType > &result, int requiredOperandCount=-1, Delimiter delimiter=Delimiter::None)=0
Parse zero or more trailing SSA comma-separated trailing operand references with a specified surrounding delimiter, and an optional required operand count.
ParseResult parseTrailingOperandList (SmallVectorImpl< OperandType > &result, Delimiter delimiter)
virtual ParseResult resolveOperand (const OperandType &operand, Type type, SmallVectorImpl< Value > &result)=0
Resolve an operand to an SSA value, emitting an error on failure.
ParseResult resolveOperands (ArrayRef< OperandType > operands, Type type, SmallVectorImpl< Value > &result)
Resolve a list of operands to SSA values, emitting an error on failure, or appending the results to the list on success.
ParseResult resolveOperands (ArrayRef< OperandType > operands, ArrayRef< Type > types, llvm::SMLoc loc, SmallVectorImpl< Value > &result)
Resolve a list of operands and a list of operand types to SSA values, emitting an error and returning failure, or appending the results to the list on success.
template<typename Operands >
ParseResult resolveOperands (Operands &&operands, Type type, llvm::SMLoc loc, SmallVectorImpl< Value > &result)
template<typename Operands , typename Types >
std::enable_if_t<!std::is_convertible< Types, Type >::value, ParseResult > resolveOperands (Operands &&operands, Types &&types, llvm::SMLoc loc, SmallVectorImpl< Value > &result)
virtual ParseResult parseAffineMapOfSSAIds (SmallVectorImpl< OperandType > &operands, Attribute &map, StringRef attrName, NamedAttrList &attrs, Delimiter delimiter=Delimiter::Square)=0
Parses an affine map attribute where dims and symbols are SSA operands.
virtual ParseResult parseAffineExprOfSSAIds (SmallVectorImpl< OperandType > &dimOperands, SmallVectorImpl< OperandType > &symbOperands, AffineExpr &expr)=0
Parses an affine expression where dims and symbols are SSA operands.
virtual ParseResult parseRegion (Region &region, ArrayRef< OperandType > arguments={}, ArrayRef< Type > argTypes={}, bool enableNameShadowing=false)=0
Parses a region.
virtual OptionalParseResult parseOptionalRegion (Region &region, ArrayRef< OperandType > arguments={}, ArrayRef< Type > argTypes={}, bool enableNameShadowing=false)=0
Parses a region if present.
virtual OptionalParseResult parseOptionalRegion (std::unique_ptr< Region > &region, ArrayRef< OperandType > arguments={}, ArrayRef< Type > argTypes={}, bool enableNameShadowing=false)=0
Parses a region if present.
virtual ParseResult parseRegionArgument (OperandType &argument)=0
Parse a region argument, this argument is resolved when calling 'parseRegion'.
virtual ParseResult parseRegionArgumentList (SmallVectorImpl< OperandType > &result, int requiredOperandCount=-1, Delimiter delimiter=Delimiter::None)=0
Parse zero or more region arguments with a specified surrounding delimiter, and an optional required argument count.
virtual ParseResult parseRegionArgumentList (SmallVectorImpl< OperandType > &result, Delimiter delimiter)
virtual ParseResult parseOptionalRegionArgument (OperandType &argument)=0
Parse a region argument if present.
virtual ParseResult parseSuccessor (Block *&dest)=0
Parse a single operation successor.
virtual OptionalParseResult parseOptionalSuccessor (Block *&dest)=0
Parse an optional operation successor.
virtual ParseResult parseSuccessorAndUseList (Block *&dest, SmallVectorImpl< Value > &operands)=0
Parse a single operation successor and its operand list.
virtual ParseResult parseType (Type &result)=0
Parse a type.
virtual OptionalParseResult parseOptionalType (Type &result)=0
Parse an optional type.
template<typename TypeT >
ParseResult parseType (TypeT &result)
Parse a type of a specific type.
ParseResult parseTypeList (SmallVectorImpl< Type > &result)
Parse a type list.
virtual ParseResult parseArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an arrow followed by a type list.
virtual ParseResult parseOptionalArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional arrow followed by a type list.
virtual ParseResult parseColonType (Type &result)=0
Parse a colon followed by a type.
template<typename TypeType >
ParseResult parseColonType (TypeType &result)
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
virtual ParseResult parseColonTypeList (SmallVectorImpl< Type > &result)=0
Parse a colon followed by a type list, which must have at least one type.
virtual ParseResult parseOptionalColonTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional colon followed by a type list, which if present must have at least one type.
ParseResult parseAssignmentList (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs)
Parse a list of assignments of the form (x1 = y1, x2 = y2, ...)
virtual OptionalParseResult parseOptionalAssignmentList (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs)=0
ParseResult parseAssignmentListWithTypes (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs, SmallVectorImpl< Type > &types)
Parse a list of assignments of the form (x1 = y1 : type1, x2 = y2 : type2, ...)
virtual OptionalParseResult parseOptionalAssignmentListWithTypes (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs, SmallVectorImpl< Type > &types)=0
ParseResult parseKeywordType (const char *keyword, Type &result)
Parse a keyword followed by a type.
ParseResult addTypeToList (Type type, SmallVectorImpl< Type > &result)
Add the specified type to the end of the specified type list and return success.
ParseResult addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > &result)
Add the specified types to the end of the specified type list and return success.
Detailed Description
The OpAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
It has an intentionally high-level API that is designed to reduce/constrain syntax innovation in individual operations.
For example, consider an op like this:
x = load p[%1, %2] : memref<...>
The "%x = load" tokens are already parsed and therefore invisible to the custom op parser. This can be supported by calling parseOperandList to parse the p, then calling parseOperandList with a SquareDelimiter to parse the indices, then calling parseColonTypeList to parse the result type.
Definition at line 258 of file OpImplementation.h.
Member Enumeration Documentation
Delimiter
enum mlir::OpAsmParser::Delimiter strong
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList and parseRegionArgumentList.
Enumerator
None
Zero or more operands with no delimiters.
Paren
Parens surrounding zero or more operands.
Square
Square brackets surrounding zero or more operands.
OptionalParen
Parens supporting zero or more operands, or nothing.
OptionalSquare
Square brackets supporting zero or more ops, or nothing.
Definition at line 613 of file OpImplementation.h.
Constructor & Destructor Documentation
~OpAsmParser()
OpAsmParser::~OpAsmParser () virtual
Definition at line 21 of file Operation.cpp.
Member Function Documentation
addTypesToList()
ParseResult mlir::OpAsmParser::addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > & result) inline
Add the specified types to the end of the specified type list and return success.
This is a helper designed to allow parse methods to be simple and chain through || operators.
Definition at line 905 of file OpImplementation.h.
References mlir::success().
Referenced by parseCompositeInsertOp(), parseExecuteOp(), and parseShuffleOp().
addTypeToList()
ParseResult mlir::OpAsmParser::addTypeToList (Type type, SmallVectorImpl< Type > & result) inline
Add the specified type to the end of the specified type list and return success.
This is a helper designed to allow parse methods to be simple and chain through || operators.
Definition at line 897 of file OpImplementation.h.
References mlir::success().
Referenced by foldTransferInBoundsAttribute(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineVectorLoadOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), mlir::impl::parseCastOp(), parseConstantOp(), parseContractionOp(), parseExecuteOp(), parseExtractOp(), parseGroupNonUniformArithmeticOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseReductionOp(), parseROCDLMubufLoadOp(), parseShuffleOp(), parseTransferReadOp(), parseTransposeOp(), and parseViewOp().
emitError()
virtual InFlightDiagnostic mlir::OpAsmParser::emitError (llvm::SMLoc loc, const Twine & message = {}) pure virtual
Emit a diagnostic at the specified location and return failure.
Referenced by allowedOnce(), buildLLVMFunctionType(), mlir::Operation::emitOpError(), foldTransferInBoundsAttribute(), getElementType(), getInsertExtractValueElementType(), getLoadStoreElementType(), mlir::memref::DmaStartOp::parse(), mlir::OpState::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAsyncDependencies(), parseAtomicBinOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicOrdering(), parseAtomicUpdateOp(), parseBound(), parseCallOp(), parseCmpOp(), parseCompositeConstructOp(), parseContractionOp(), parseEnumStrAttr(), parseExtractElementOp(), parseExtractOp(), parseForOp(), mlir::function_like_impl::parseFunctionArgumentList(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseIncludeOp(), parseInsertElementOp(), parseInvokeOp(), parseNamedStructuredOpRegion(), parseOperandsOrIntegersImpl(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReductionOp(), parseScheduleClause(), parseShuffleOp(), parseShuffleVectorOp(), parseTransferReadOp(), parseVariableOp(), parseViewOp(), and verify().
getBuilder()
virtual Builder& mlir::OpAsmParser::getBuilder () const pure virtual
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
Referenced by buildLLVMFunctionType(), deduplicateAndResolveOperands(), foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMapWithMinMax(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAsyncDependencies(), parseAtomicBinOp(), parseAtomicCmpXchgOp(), parseAtomicOrdering(), parseBound(), parseBranchConditionalOp(), parseCallOp(), parseCmpOp(), parseCommonStructuredOpParts(), parseConstShapeOp(), parseContractionOp(), parseControlAttribute(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyOpRegion(), parseCreateOperationOpAttributes(), mlir::parseDimAndSymbolList(), parseEntryPointOp(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseExecuteOp(), parseExecutionModeOp(), parseFenceOp(), parseFillOpRegion(), parseForOp(), parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGenericAtomicRMWOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseIncludeOp(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseLLVMFuncOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseLoopOp(), parseMemoryAccessAttributes(), parseNamedStructuredOpRegion(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), parseOperandsOrIntegersImpl(), parseOperationOpAttributes(), parseOptionalLLVMKeyword(), mlir::impl::parseOptionalVisibilityKeyword(), parseParallelOp(), parsePrefetchOp(), mlir::parseReshapeLikeOp(), parseResultsValueType(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShuffleOp(), parseSourceMemoryAccessAttributes(), parseSpecConstantCompositeOp(), parseSpecConstantOperationOp(), parseStoreOp(), parseSwitchOpCases(), parseTiledLoopOp(), parseTransferReadOp(), parseVariableDecorations(), parseVariableOp(), parseViewOp(), and parseWsLoopOp().
getCurrentLocation() [1/2]
virtual llvm::SMLoc mlir::OpAsmParser::getCurrentLocation () pure virtual
Get the location of the next token and store it into the argument.
This always succeeds.
Referenced by foldTransferInBoundsAttribute(), parseAccessChainOp(), parseAffineForOp(), parseAffineParallelOp(), parseAllocaOp(), parseAsyncDependencies(), parseAtomicBinOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicOrdering(), parseAtomicUpdateOp(), parseBound(), parseCallOp(), parseCmpOp(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseContractionOp(), parseEnumStrAttr(), parseExecuteOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), mlir::function_like_impl::parseFunctionArgumentList(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLLVMFuncOp(), parseLoadOp(), parseNamedStructuredOpRegion(), parseOperandList(), parseReturnOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStoreOp(), parseSubgroupBlockWriteINTELOp(), parseTiledLoopOp(), parseTransferReadOp(), parseVariableOp(), parseViewOp(), parseWMMAMmaF16F16M16N16K16Op(), parseYieldOp(), and verify().
getCurrentLocation() [2/2]
ParseResult mlir::OpAsmParser::getCurrentLocation (llvm::SMLoc * loc) inline
Definition at line 273 of file OpImplementation.h.
References mlir::success().
getEncodedSourceLoc()
virtual Location mlir::OpAsmParser::getEncodedSourceLoc (llvm::SMLoc loc) pure virtual
Re-encode the given source location as an MLIR location and return it.
Note: This method should only be used when a Location is necessary, as the encoding process is not efficient.
getNameLoc()
virtual llvm::SMLoc mlir::OpAsmParser::getNameLoc () const pure virtual
Return the location of the original name token.
Referenced by allowedOnce(), mlir::memref::DmaStartOp::parse(), mlir::OpState::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), parseBound(), parseCallOp(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseForOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseIncludeOp(), parseInvokeOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), parseOperandsOrIntegersImpl(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseScheduleClause(), parseSelectOp(), parseShuffleOp(), and parseWsLoopOp().
getNumResults()
virtual size_t mlir::OpAsmParser::getNumResults () const pure virtual
Return the number of declared SSA results.
This returns 4 for the foo.op example in the comment for getResultName.
Referenced by mlir::Operation::cloneWithoutRegions(), and parseAsyncDependencies().
getResultName()
virtual std::pair<StringRef, unsigned> mlir::OpAsmParser::getResultName (unsigned resultNo) const pure virtual
Return the name of the specified result in the specified syntax, as well as the sub-element in the name.
It returns an empty string and ~0U for invalid result numbers. For example, in this operation:
x, y:2, z = foo.op
getResultName(0) == {"x", 0 } getResultName(1) == {"y", 0 } getResultName(2) == {"y", 1 } getResultName(3) == {"z", 0 } getResultName(4) == {"", ~0U }
parseAffineExprOfSSAIds()
virtual ParseResult mlir::OpAsmParser::parseAffineExprOfSSAIds (SmallVectorImpl< OperandType > & dimOperands, SmallVectorImpl< OperandType > & symbOperands, AffineExpr & expr) pure virtual
Parses an affine expression where dims and symbols are SSA operands.
Operand values must come from single-result sources, and be valid dimensions/symbol identifiers according to mlir::isValidDim/Symbol.
Referenced by parseAffineMapWithMinMax().
parseAffineMap()
virtual ParseResult mlir::OpAsmParser::parseAffineMap (AffineMap & map) pure virtual
Parse an affine map instance into 'map'.
Referenced by parseTransposeOp().
parseAffineMapOfSSAIds()
virtual ParseResult mlir::OpAsmParser::parseAffineMapOfSSAIds (SmallVectorImpl< OperandType > & operands, Attribute & map, StringRef attrName, NamedAttrList & attrs, Delimiter delimiter = Delimiter::Square) pure virtual
Parses an affine map attribute where dims and symbols are SSA operands.
Operand values must come from single-result sources, and be valid dimensions/symbol identifiers according to mlir::isValidDim/Symbol.
Referenced by mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineLoadOp(), parseAffineMapWithMinMax(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), and parseAffineVectorStoreOp().
parseArrow()
virtual ParseResult mlir::OpAsmParser::parseArrow () pure virtual
Parse a '->' token.
Referenced by parseAllocateAndAllocator(), parseReductionVarList(), parseResultsValueType(), and parseWMMAMmaF16F16M16N16K16Op().
parseArrowTypeList()
virtual ParseResult mlir::OpAsmParser::parseArrowTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an arrow followed by a type list.
Referenced by parseAffineForOp(), and parseForOp().
parseAssignmentList()
ParseResult mlir::OpAsmParser::parseAssignmentList (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs) inline
Parse a list of assignments of the form (x1 = y1, x2 = y2, ...)
Definition at line 861 of file OpImplementation.h.
References mlir::emitError(), mlir::OptionalParseResult::getValue(), and mlir::OptionalParseResult::hasValue().
Referenced by parseAffineForOp(), and parseForOp().
parseAssignmentListWithTypes()
ParseResult mlir::OpAsmParser::parseAssignmentListWithTypes (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs, SmallVectorImpl< Type > & types) inline
Parse a list of assignments of the form (x1 = y1 : type1, x2 = y2 : type2, ...)
Definition at line 875 of file OpImplementation.h.
References mlir::emitError(), mlir::OptionalParseResult::getValue(), and mlir::OptionalParseResult::hasValue().
Referenced by parseTiledLoopOp().
parseAttribute() [1/5]
virtual ParseResult mlir::OpAsmParser::parseAttribute (Attribute & result, Type type = {}) pure virtual
Parse an arbitrary attribute of a given type and return it in result.
Referenced by parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), parseCmpOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseCreateOperationOpAttributes(), parseEntryPointOp(), parseEnumStrAttr(), parseExecutionModeOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), parseFunctionLibraryOp(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseInsertValueOp(), parseInvokeOp(), parseMemoryAccessAttributes(), parseModuleOp(), parseOperandsOrIntegersImpl(), parseOperationOpAttributes(), parsePrefetchOp(), parseReductionOp(), parseReductionVarList(), parseShuffleOp(), parseShuffleVectorOp(), parseSourceMemoryAccessAttributes(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseTiledLoopOp(), parseVariableDecorations(), and parseWsLoopOp().
parseAttribute() [2/5]
template<typename AttrType > ParseResult mlir::OpAsmParser::parseAttribute (AttrType & result, Type type = {}) inline
Parse an attribute of a specific kind and type.
Definition at line 483 of file OpImplementation.h.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseAttribute(), and mlir::success().
parseAttribute() [3/5]
ParseResult mlir::OpAsmParser::parseAttribute (Attribute & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an arbitrary attribute and return it in result.
This also adds the attribute to the specified attribute list with the specified name.
Definition at line 500 of file OpImplementation.h.
References mlir::parseAttribute().
parseAttribute() [4/5]
template<typename AttrType > ParseResult mlir::OpAsmParser::parseAttribute (AttrType & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an attribute of a specific kind and type.
Definition at line 507 of file OpImplementation.h.
References mlir::parseAttribute().
parseAttribute() [5/5]
template<typename AttrType > ParseResult mlir::OpAsmParser::parseAttribute (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
Parse an arbitrary attribute of a given type and return it in result.
This also adds the attribute to the specified attribute list with the specified name.
Definition at line 538 of file OpImplementation.h.
References mlir::NamedAttrList::append(), mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), map(), mlir::parseAttribute(), and mlir::success().
parseColon()
virtual ParseResult mlir::OpAsmParser::parseColon () pure virtual
Parse a : token.
Referenced by parseAllocaOp(), parseCallOp(), parseCmpOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseExtractValueOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), mlir::parseReshapeLikeOp(), parseShiftOp(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), parseSwitchOpCases(), parseVariableOp(), and parseWMMAMmaF16F16M16N16K16Op().
parseColonType() [1/2]
virtual ParseResult mlir::OpAsmParser::parseColonType (Type & result) pure virtual
Parse a colon followed by a type.
Referenced by mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineLoadOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocateAndAllocator(), parseAtomicCmpXchgOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicRMWOp(), parseAtomicUpdateOp(), parseAttributions(), mlir::impl::parseCastOp(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseExecuteOp(), parseExtractElementOp(), parseExtractOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseGenericAtomicRMWOp(), parseGlobalVariableOp(), parseGroupNonUniformArithmeticOp(), parseInsertElementOp(), parseLinearClause(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandAndType(), parseOperandAndTypeList(), parseOperandList(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), parseReductionVarList(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantCompositeOp(), parseTransposeOp(), parseUnaryOp(), parseViewOp(), parseWsLoopOp(), and verify().
parseColonType() [2/2]
template<typename TypeType > ParseResult mlir::OpAsmParser::parseColonType (TypeType & result) inline
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
Definition at line 835 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), and mlir::success().
parseColonTypeList()
virtual ParseResult mlir::OpAsmParser::parseColonTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse a colon followed by a type list, which must have at least one type.
Referenced by foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), parseCommonStructuredOpParts(), parseContractionOp(), parseSwitchOpCases(), parseTransferReadOp(), and parseYieldOp().
parseComma()
virtual ParseResult mlir::OpAsmParser::parseComma () pure virtual
Parse a , token.
Referenced by foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseBranchConditionalOp(), parseCmpOp(), parseContractionOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseInsertElementOp(), parseInsertValueOp(), parseMemoryAccessAttributes(), parseOuterProductOp(), parsePrefetchOp(), parseReductionOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSizeAssignment(), parseSourceMemoryAccessAttributes(), parseStoreOp(), parseTiledLoopOp(), parseTransferReadOp(), and parseVariableDecorations().
parseEqual()
virtual ParseResult mlir::OpAsmParser::parseEqual () pure virtual
Parse a = token.
Referenced by parseAffineForOp(), parseAffineParallelOp(), parseCreateOperationOpAttributes(), parseForOp(), parseGenericOp(), parseLinearClause(), parseOperationOpAttributes(), parseParallelOp(), parserOptionalOperandAndTypeWithPrefix(), parseSizeAssignment(), parseSpecConstantOp(), parseTiledLoopOp(), and parseWsLoopOp().
parseGenericOperation()
virtual Operation* mlir::OpAsmParser::parseGenericOperation (Block * insertBlock, Block::iterator insertPt) pure virtual
Parse an operation in its generic form.
The parsed operation is parsed in the current context and inserted in the provided block and insertion point. The results produced by this operation aren't mapped to any named value in the parser. Returns nullptr on failure.
Referenced by parseSpecConstantOperationOp().
parseGreater()
virtual ParseResult mlir::OpAsmParser::parseGreater () pure virtual
Parse a '>' token.
Referenced by parseAffinePrefetchOp(), and parsePrefetchOp().
parseInteger()
template<typename IntT > ParseResult mlir::OpAsmParser::parseInteger (IntT & result) inline
Parse an integer value from the stream.
Definition at line 443 of file OpImplementation.h.
References mlir::emitError(), and mlir::OptionalParseResult::hasValue().
Referenced by mlir::parseReshapeLikeOp(), and parseSwitchOpCases().
parseKeyword() [1/2]
ParseResult mlir::OpAsmParser::parseKeyword (StringRef keyword, const Twine & msg = "") inline
Parse a given keyword.
Definition at line 387 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
Referenced by parseAffineForOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAtomicBinOp(), parseAtomicOrdering(), parseExecuteOp(), parseForOp(), parseFunctionLibraryOp(), parseInvokeOp(), parseLaunchOp(), parseParallelOp(), parsePrefetchOp(), mlir::parseReshapeLikeOp(), parseScheduleClause(), parseShuffleOp(), parseSizeAssignment(), parseSpecConstantOperationOp(), parseSwitchOpCases(), parseTiledLoopOp(), parseWsLoopOp(), and verify().
parseKeyword() [2/2]
ParseResult mlir::OpAsmParser::parseKeyword (StringRef * keyword) inline
Parse a keyword into 'keyword'.
Definition at line 395 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
parseKeywordType()
ParseResult mlir::OpAsmParser::parseKeywordType (const char * keyword, Type & result) inline
Parse a keyword followed by a type.
Definition at line 890 of file OpImplementation.h.
References mlir::failure(), and mlir::parseType().
Referenced by mlir::impl::parseCastOp(), parseCompositeInsertOp(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseReductionOp(), parseTransposeOp(), and parseViewOp().
parseLBrace()
virtual ParseResult mlir::OpAsmParser::parseLBrace () pure virtual
Parse a { token.
parseLess()
virtual ParseResult mlir::OpAsmParser::parseLess () pure virtual
Parse a '<' token.
Referenced by parseAffinePrefetchOp(), and parsePrefetchOp().
parseLParen()
virtual ParseResult mlir::OpAsmParser::parseLParen () pure virtual
Parse a (token.
Referenced by parseAffineMapWithMinMax(), parseAffineParallelOp(), parseAllocateAndAllocator(), parseAttributions(), parseCommonStructuredOpParts(), parseControlAttribute(), parseFenceOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseGlobalOp(), parseGlobalVariableOp(), parseGroupNonUniformArithmeticOp(), parseLinearClause(), parseOperandAndTypeList(), parseOperandList(), parseOptionalOperand(), parseOptionalOperandAndType(), parseParallelOp(), parseReduceOp(), parseReductionVarList(), parseScheduleClause(), parseSizeAssignment(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseVariableDecorations(), parseVariableOp(), and parseWsLoopOp().
parseLSquare()
virtual ParseResult mlir::OpAsmParser::parseLSquare () pure virtual
Parse a [ token.
Referenced by parseExtractElementOp(), parseInsertElementOp(), parseOperandsOrIntegersImpl(), mlir::parseReshapeLikeOp(), and parseTiledLoopOp().
parseOperand()
virtual ParseResult mlir::OpAsmParser::parseOperand (OperandType & result) pure virtual
Parse a single operand.
Referenced by foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineLoadOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocateAndAllocator(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseBranchConditionalOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCompositeExtractOp(), parseContractionOp(), parseCopyMemoryOp(), parseCreateOperationOpAttributes(), parseExecuteOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseLandingpadOp(), parseLinearClause(), parseLoadOp(), parseLogicalUnaryOp(), parseOperandAndType(), parseOperandAndTypeList(), parseOperationOpAttributes(), parseOptionalOperand(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionVarList(), mlir::parseReshapeLikeOp(), parseScheduleClause(), parseShuffleOp(), parseShuffleVectorOp(), parseSizeAssignment(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseTransferReadOp(), parseTransposeOp(), parseUnaryOp(), parseVariableOp(), and parseViewOp().
parseOperandList() [1/2]
virtual ParseResult mlir::OpAsmParser::parseOperandList (SmallVectorImpl< OperandType > & result, int requiredOperandCount = -1, Delimiter delimiter = Delimiter::None) pure virtual
Parse zero or more SSA comma-separated operand references with a specified surrounding delimiter, and an optional required operand count.
Referenced by foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), parseAccessChainOp(), parseAffineMinMaxOp(), parseAsyncDependencies(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), parseBound(), parseCallOp(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeInsertOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), mlir::parseDimAndSymbolList(), parseExecuteOp(), parseGenericAtomicRMWOp(), parseInvokeOp(), parseLogicalBinaryOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseStoreOp(), parseSubgroupBlockWriteINTELOp(), parseTiledLoopOp(), parseTransferReadOp(), parseViewOp(), parseWMMAMmaF16F16M16N16K16Op(), parseWsLoopOp(), and parseYieldOp().
parseOperandList() [2/2]
ParseResult mlir::OpAsmParser::parseOperandList (SmallVectorImpl< OperandType > & result, Delimiter delimiter) inline
Definition at line 632 of file OpImplementation.h.
References parseOperandList().
parseOptionalArrow()
virtual ParseResult mlir::OpAsmParser::parseOptionalArrow () pure virtual
Parse a '->' token if present.
Referenced by mlir::function_like_impl::parseFunctionSignature().
parseOptionalArrowTypeList()
virtual ParseResult mlir::OpAsmParser::parseOptionalArrowTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an optional arrow followed by a type list.
Referenced by parseAffineIfOp(), parseAffineParallelOp(), parseAllocaScopeOp(), parseAssumingOp(), parseExecuteOp(), parseExecuteRegionOp(), parseIfOp(), parseLoopOp(), parseNamedStructuredOpResults(), parseParallelOp(), and parseReduceOp().
parseOptionalAssignmentList()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAssignmentList (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs) pure virtual
Referenced by verify().
parseOptionalAssignmentListWithTypes()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAssignmentListWithTypes (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs, SmallVectorImpl< Type > & types) pure virtual
parseOptionalAttrDict()
virtual ParseResult mlir::OpAsmParser::parseOptionalAttrDict (NamedAttrList & result) pure virtual
Parse a named dictionary into 'result' if it is present.
Referenced by foldTransferInBoundsAttribute(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCommonStructuredOpParts(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseCopyMemoryOp(), parseExecuteRegionOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), parseForOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLaunchOp(), parseLLVMOpAttrs(), parseLoadOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parseReduceOp(), mlir::parseReshapeLikeOp(), parseReturnOp(), parseSelectOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantOperationOp(), parseStoreOp(), parseTiledLoopOp(), parseTransferReadOp(), parseTransposeOp(), parseVariableDecorations(), parseViewOp(), parseWMMAMmaF16F16M16N16K16Op(), and parseYieldOp().
parseOptionalAttrDictWithKeyword()
virtual ParseResult mlir::OpAsmParser::parseOptionalAttrDictWithKeyword (NamedAttrList & result) pure virtual
Parse a named dictionary into 'result' if the attributes keyword is present.
Referenced by parseExecuteOp(), parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseLLVMFuncOp(), parseLoopOp(), parseModuleOp(), parseParallelOp(), and verify().
parseOptionalAttribute() [1/4]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAttribute (Attribute & result, Type type, StringRef attrName, NamedAttrList & attrs) pure virtual
Parse an optional attribute.
Referenced by parseIncludeOp().
parseOptionalAttribute() [2/4]
template<typename AttrT > OptionalParseResult mlir::OpAsmParser::parseOptionalAttribute (AttrT & result, StringRef attrName, NamedAttrList & attrs) inline
Definition at line 518 of file OpImplementation.h.
parseOptionalAttribute() [3/4]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAttribute (ArrayAttr & result, Type type, StringRef attrName, NamedAttrList & attrs) pure virtual
Specialized variants of parseOptionalAttribute that remove potential ambiguities in syntax.
parseOptionalAttribute() [4/4]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAttribute (StringAttr & result, Type type, StringRef attrName, NamedAttrList & attrs) pure virtual
parseOptionalColon()
virtual ParseResult mlir::OpAsmParser::parseOptionalColon () pure virtual
Parse a : token if present.
parseOptionalColonTypeList()
virtual ParseResult mlir::OpAsmParser::parseOptionalColonTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an optional colon followed by a type list, which if present must have at least one type.
Referenced by parseGlobalOp(), and parseReturnOp().
parseOptionalComma()
virtual ParseResult mlir::OpAsmParser::parseOptionalComma () pure virtual
Parse a , token if present.
Referenced by foldTransferInBoundsAttribute(), parseAffineMapWithMinMax(), parseAffineParallelOp(), parseAllocateAndAllocator(), parseAttributions(), parseCopyMemoryOp(), parseCreateOperationOpAttributes(), parseEntryPointOp(), parseExecuteOp(), parseExecutionModeOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseLinearClause(), parseLoopOp(), parseOperandAndTypeList(), parseOperandList(), parseOperandsOrIntegersImpl(), parseOperationOpAttributes(), parseReductionVarList(), mlir::parseReshapeLikeOp(), parseSelectOp(), parseSpecConstantCompositeOp(), parseSwitchOpCases(), and parseTransferReadOp().
parseOptionalEllipsis()
virtual ParseResult mlir::OpAsmParser::parseOptionalEllipsis () pure virtual
Parse a ... token if present;.
Referenced by mlir::function_like_impl::parseFunctionArgumentList().
parseOptionalEqual()
virtual ParseResult mlir::OpAsmParser::parseOptionalEqual () pure virtual
Parse a = token if present.
Referenced by parseGlobalMemrefOpTypeAndInitialValue(), and parseScheduleClause().
parseOptionalGreater()
virtual ParseResult mlir::OpAsmParser::parseOptionalGreater () pure virtual
Parse a '>' token if present.
Referenced by parseIncludeOp().
parseOptionalInteger() [1/2]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalInteger (APInt & result) pure virtual
Parse an optional integer value from the stream.
Referenced by parseSwitchOpCases().
parseOptionalInteger() [2/2]
template<typename IntT > OptionalParseResult mlir::OpAsmParser::parseOptionalInteger (IntT & result) inline
Definition at line 455 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), mlir::OptionalParseResult::hasValue(), mlir::parseAttribute(), and mlir::success().
parseOptionalKeyword() [1/3]
virtual ParseResult mlir::OpAsmParser::parseOptionalKeyword (StringRef keyword) pure virtual
Parse the given keyword if present.
Referenced by parseAffineForOp(), parseAffineIfOp(), parseAffineMapWithMinMax(), parseAffineParallelOp(), parseAsyncDependencies(), parseAtomicReductionRegion(), parseAttributions(), parseBound(), parseCommonStructuredOpParts(), parseControlAttribute(), parseFenceOp(), parseForOp(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseLandingpadOp(), parseLaunchFuncOperands(), parseLoadOp(), parseLoopOp(), parseModuleOp(), parseOperandList(), parseOptionalKeywordAlternative(), parseOptionalOperand(), parseOptionalOperandAndType(), mlir::impl::parseOptionalVisibilityKeyword(), parseParallelOp(), parserOptionalOperandAndTypeWithPrefix(), parseSpecConstantOp(), parseStoreOp(), parseTiledLoopOp(), parseVariableDecorations(), parseVariableOp(), and parseWsLoopOp().
parseOptionalKeyword() [2/3]
virtual ParseResult mlir::OpAsmParser::parseOptionalKeyword (StringRef * keyword) pure virtual
Parse a keyword, if present, into 'keyword'.
parseOptionalKeyword() [3/3]
virtual ParseResult mlir::OpAsmParser::parseOptionalKeyword (StringRef * keyword, ArrayRef< StringRef > allowedValues) pure virtual
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
parseOptionalLBrace()
virtual ParseResult mlir::OpAsmParser::parseOptionalLBrace () pure virtual
Parse a { token if present.
Referenced by parseCreateOperationOpAttributes(), and parseOperationOpAttributes().
parseOptionalLess()
virtual ParseResult mlir::OpAsmParser::parseOptionalLess () pure virtual
Parse a '<' token if present.
Referenced by parseIncludeOp().
parseOptionalLocationSpecifier()
virtual ParseResult mlir::OpAsmParser::parseOptionalLocationSpecifier (Optional< Location > & result) pure virtual
Parse a loc(...) specifier if present, filling in result if so.
Referenced by mlir::function_like_impl::parseFunctionArgumentList().
parseOptionalLParen()
virtual ParseResult mlir::OpAsmParser::parseOptionalLParen () pure virtual
Parse a (token if present.
Referenced by parseExecuteOp(), parseFunctionResultList(), parseLandingpadOp(), parseLoopOp(), parseOptionalOperandAndType(), parseSwitchOpCases(), and parseWsLoopOp().
parseOptionalLSquare()
virtual ParseResult mlir::OpAsmParser::parseOptionalLSquare () pure virtual
Parse a [ token if present.
Referenced by parseBranchConditionalOp(), parseExecuteOp(), parseMemoryAccessAttributes(), and parseSourceMemoryAccessAttributes().
parseOptionalOperand()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalOperand (OperandType & result) pure virtual
Parse a single operand if present.
Referenced by parseOperandsOrIntegersImpl().
parseOptionalPlus()
virtual ParseResult mlir::OpAsmParser::parseOptionalPlus () pure virtual
Parse a '+' token if present.
parseOptionalQuestion()
virtual ParseResult mlir::OpAsmParser::parseOptionalQuestion () pure virtual
Parse a '?' token if present.
parseOptionalRBrace()
virtual ParseResult mlir::OpAsmParser::parseOptionalRBrace () pure virtual
Parse a } token if present.
parseOptionalRegion() [1/2]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalRegion (Region & region, ArrayRef< OperandType > arguments = {}, ArrayRef< Type > argTypes = {}, bool enableNameShadowing = false) pure virtual
Parses a region if present.
Referenced by parseFuncOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalOp(), and parseLLVMFuncOp().
parseOptionalRegion() [2/2]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalRegion (std::unique_ptr< Region > & region, ArrayRef< OperandType > arguments = {}, ArrayRef< Type > argTypes = {}, bool enableNameShadowing = false) pure virtual
Parses a region if present.
If the region is present, a new region is allocated and placed in region. If no region is present or on failure, region remains untouched.
parseOptionalRegionArgument()
virtual ParseResult mlir::OpAsmParser::parseOptionalRegionArgument (OperandType & argument) pure virtual
Parse a region argument if present.
Referenced by mlir::function_like_impl::parseFunctionArgumentList().
parseOptionalRParen()
virtual ParseResult mlir::OpAsmParser::parseOptionalRParen () pure virtual
Parse a) token if present.
Referenced by parseAffineMapWithMinMax(), parseAttributions(), parseExecuteOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalOp(), and parseOperandList().
parseOptionalRSquare()
virtual ParseResult mlir::OpAsmParser::parseOptionalRSquare () pure virtual
Parse a ] token if present.
Referenced by parseOperandsOrIntegersImpl(), and mlir::parseReshapeLikeOp().
parseOptionalStar()
virtual ParseResult mlir::OpAsmParser::parseOptionalStar () pure virtual
Parse a '*' token if present.
parseOptionalSuccessor()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalSuccessor (Block *& dest) pure virtual
Parse an optional operation successor.
parseOptionalSymbolName()
virtual ParseResult mlir::OpAsmParser::parseOptionalSymbolName (StringAttr & result, StringRef attrName, NamedAttrList & attrs) pure virtual
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Referenced by parseModuleOp().
parseOptionalType()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalType (Type & result) pure virtual
Parse an optional type.
parsePlus()
virtual ParseResult mlir::OpAsmParser::parsePlus () pure virtual
Parse a '+' token.
parseQuestion()
virtual ParseResult mlir::OpAsmParser::parseQuestion () pure virtual
Parse a '?' token.
parseRBrace()
virtual ParseResult mlir::OpAsmParser::parseRBrace () pure virtual
Parse a } token.
Referenced by parseCreateOperationOpAttributes(), and parseOperationOpAttributes().
parseRegion()
virtual ParseResult mlir::OpAsmParser::parseRegion (Region & region, ArrayRef< OperandType > arguments = {}, ArrayRef< Type > argTypes = {}, bool enableNameShadowing = false) pure virtual
Parses a region.
Any parsed blocks are appended to 'region' and must be moved to the op regions after the op is created. The first block of the region takes 'arguments' of types 'argTypes'. If 'enableNameShadowing' is set to true, the argument names are allowed to shadow the names of other existing SSA values defined above the region scope. 'enableNameShadowing' can only be set to true for regions attached to operations that are 'IsolatedFromAbove.
Referenced by parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAtomicReductionRegion(), parseExecuteOp(), parseExecuteRegionOp(), parseForOp(), parseFunctionLibraryOp(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseIfOp(), parseLaunchOp(), parseLoopOp(), parseModuleOp(), parseParallelOp(), parseReduceOp(), parseRegions(), parseSelectionOp(), parseTiledLoopOp(), parseWsLoopOp(), and verify().
parseRegionArgument()
virtual ParseResult mlir::OpAsmParser::parseRegionArgument (OperandType & argument) pure virtual
Parse a region argument, this argument is resolved when calling 'parseRegion'.
Referenced by parseAffineForOp(), parseAttributions(), parseForOp(), parseOperandList(), and parseSizeAssignment().
parseRegionArgumentList() [1/2]
virtual ParseResult mlir::OpAsmParser::parseRegionArgumentList (SmallVectorImpl< OperandType > & result, int requiredOperandCount = -1, Delimiter delimiter = Delimiter::None) pure virtual
Parse zero or more region arguments with a specified surrounding delimiter, and an optional required argument count.
Region arguments define new values; so this also checks if values with the same names have not been defined yet.
Referenced by parseAffineParallelOp(), parseParallelOp(), parseSizeAssignment(), parseSwitchOpCases(), parseTiledLoopOp(), and parseWsLoopOp().
parseRegionArgumentList() [2/2]
virtual ParseResult mlir::OpAsmParser::parseRegionArgumentList (SmallVectorImpl< OperandType > & result, Delimiter delimiter) inline virtual
Definition at line 761 of file OpImplementation.h.
References mlir::parseType().
parseRParen()
virtual ParseResult mlir::OpAsmParser::parseRParen () pure virtual
Parse a) token.
Referenced by parseAffineMapWithMinMax(), parseAffineParallelOp(), parseAllocateAndAllocator(), parseAttributions(), parseCommonStructuredOpParts(), parseControlAttribute(), parseExecuteOp(), parseFenceOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalOp(), parseGlobalVariableOp(), parseGroupNonUniformArithmeticOp(), parseLandingpadOp(), parseLinearClause(), parseLoopOp(), parseOperandAndTypeList(), parseOperandList(), parseOptionalOperand(), parseOptionalOperandAndType(), parseParallelOp(), parseReduceOp(), parseReductionVarList(), parseScheduleClause(), parseSizeAssignment(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseSwitchOpCases(), parseVariableDecorations(), parseVariableOp(), and parseWsLoopOp().
parseRSquare()
virtual ParseResult mlir::OpAsmParser::parseRSquare () pure virtual
Parse a ] token.
Referenced by parseBranchConditionalOp(), parseExecuteOp(), parseExtractElementOp(), parseInsertElementOp(), parseMemoryAccessAttributes(), parseOperandsOrIntegersImpl(), mlir::parseReshapeLikeOp(), parseSourceMemoryAccessAttributes(), and parseTiledLoopOp().
parseStar()
virtual ParseResult mlir::OpAsmParser::parseStar () pure virtual
Parse a '*' token.
parseSuccessor()
virtual ParseResult mlir::OpAsmParser::parseSuccessor (Block *& dest) pure virtual
Parse a single operation successor.
Referenced by parseSwitchOpCases().
parseSuccessorAndUseList()
virtual ParseResult mlir::OpAsmParser::parseSuccessorAndUseList (Block *& dest, SmallVectorImpl< Value > & operands) pure virtual
Parse a single operation successor and its operand list.
Referenced by parseBranchConditionalOp(), and parseInvokeOp().
parseSymbolName()
ParseResult mlir::OpAsmParser::parseSymbolName (StringAttr & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Definition at line 576 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), and mlir::success().
Referenced by parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseLLVMFuncOp(), parseSpecConstantCompositeOp(), and parseSpecConstantOp().
parseTrailingOperandList() [1/2]
virtual ParseResult mlir::OpAsmParser::parseTrailingOperandList (SmallVectorImpl< OperandType > & result, int requiredOperandCount = -1, Delimiter delimiter = Delimiter::None) pure virtual
Parse zero or more trailing SSA comma-separated trailing operand references with a specified surrounding delimiter, and an optional required operand count.
A leading comma is expected before the operands.
Referenced by mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), and parseContractionOp().
parseTrailingOperandList() [2/2]
ParseResult mlir::OpAsmParser::parseTrailingOperandList (SmallVectorImpl< OperandType > & result, Delimiter delimiter) inline
Definition at line 644 of file OpImplementation.h.
parseType() [1/2]
virtual ParseResult mlir::OpAsmParser::parseType (Type & result) pure virtual
Parse a type.
Referenced by parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAwaitResultType(), parseCallOp(), parseCmpOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseExtractValueOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalMemrefOpTypeAndInitialValue(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), parseOuterProductOp(), mlir::parseReshapeLikeOp(), parseResultsValueType(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), parseVariableOp(), and parseWMMAMmaF16F16M16N16K16Op().
parseType() [2/2]
template<typename TypeT > ParseResult mlir::OpAsmParser::parseType (TypeT & result) inline
Parse a type of a specific type.
Definition at line 796 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseType(), and mlir::success().
parseTypeList()
ParseResult mlir::OpAsmParser::parseTypeList (SmallVectorImpl< Type > & result) inline
Parse a type list.
Definition at line 813 of file OpImplementation.h.
References mlir::failure(), mlir::parseType(), mlir::succeeded(), and mlir::success().
Referenced by parseAccessChainOp().
printIntegerSet()
virtual ParseResult mlir::OpAsmParser::printIntegerSet (IntegerSet & set) pure virtual
Parse an integer set instance into 'set'.
resolveOperand()
virtual ParseResult mlir::OpAsmParser::resolveOperand (const OperandType & operand, Type type, SmallVectorImpl< Value > & result) pure virtual
Resolve an operand to an SSA value, emitting an error on failure.
Referenced by foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineForOp(), parseAffineLoadOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCompositeExtractOp(), parseContractionOp(), parseCopyMemoryOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), parseLogicalUnaryOp(), parseOperandAndType(), parseOptionalOperand(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), mlir::parseReshapeLikeOp(), parseReturnOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseTransferReadOp(), parseTransposeOp(), parseVariableOp(), parseViewOp(), and parseWsLoopOp().
resolveOperands() [1/4]
ParseResult mlir::OpAsmParser::resolveOperands (ArrayRef< OperandType > operands, Type type, SmallVectorImpl< Value > & result) inline
Resolve a list of operands to SSA values, emitting an error on failure, or appending the results to the list on success.
This method should be used when all operands have the same type.
Definition at line 657 of file OpImplementation.h.
References mlir::failure(), and mlir::success().
Referenced by deduplicateAndResolveOperands(), foldTransferInBoundsAttribute(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), parseCallOp(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeInsertOp(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), mlir::parseDimAndSymbolList(), parseExecuteOp(), parseGenericAtomicRMWOp(), parseInvokeOp(), parseLaunchOp(), parseLogicalBinaryOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandList(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseStoreOp(), parseSubgroupBlockWriteINTELOp(), parseTiledLoopOp(), parseTransferReadOp(), parseUnaryOp(), parseViewOp(), parseWMMAMmaF16F16M16N16K16Op(), parseWsLoopOp(), parseYieldOp(), and verify().
resolveOperands() [2/4]
ParseResult mlir::OpAsmParser::resolveOperands (ArrayRef< OperandType > operands, ArrayRef< Type > types, llvm::SMLoc loc, SmallVectorImpl< Value > & result) inline
Resolve a list of operands and a list of operand types to SSA values, emitting an error and returning failure, or appending the results to the list on success.
Definition at line 668 of file OpImplementation.h.
References mlir::emitError(), mlir::failure(), and mlir::success().
resolveOperands() [3/4]
template<typename Operands > ParseResult mlir::OpAsmParser::resolveOperands (Operands && operands, Type type, llvm::SMLoc loc, SmallVectorImpl< Value > & result) inline
Definition at line 682 of file OpImplementation.h.
References value.
resolveOperands() [4/4]
template<typename Operands , typename Types > std::enable_if_t<!std::is_convertible<Types, Type>::value, ParseResult> mlir::OpAsmParser::resolveOperands (Operands && operands, Types && types, llvm::SMLoc loc, SmallVectorImpl< Value > & result) inline
Definition at line 689 of file OpImplementation.h.
References mlir::emitError(), mlir::failure(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/OpImplementation.h
lib/IR/Operation.cpp