MLIR: mlir::pdll::ast::TupleType Class Reference
mlir::pdll::ast::TupleType Class Reference
This class represents a PDLL tuple type, i.e.
#include "mlir/Tools/PDLL/AST/Types.h"
Public Member Functions
ArrayRef< Type > getElementTypes () const
Return the element types of this tuple.
ArrayRef< StringRef > getElementNames () const
Return the element names of this tuple.
size_t size () const
Return the number of elements within this tuple.
bool empty () const
Return if the tuple has no elements.
Public Member Functions inherited from mlir::pdll::ast::Type
Type (Storage *impl=nullptr)
bool operator== (const Type &other) const
bool operator!= (const Type &other) const
operator bool () const
Storage * getImpl () const
Return the internal storage instance of this type.
TypeID getTypeID () const
Return the TypeID instance of this type.
void print (raw_ostream &os) const
Print this type to the given stream.
Type refineWith (Type other) const
Try to refine this type with the one provided.
Static Public Member Functions
static TupleType get (Context &context, ArrayRef< Type > elementTypes, ArrayRef< StringRef > elementNames)
Return an instance of the Tuple type.
static TupleType get (Context &context, ArrayRef< Type > elementTypes={})
Static Public Member Functions inherited from mlir::pdll::ast::Type::TypeBase< detail::TupleTypeStorage >
static bool classof (Type type)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Type::TypeBase< detail::TupleTypeStorage >
using Base
using ImplTy
Protected Member Functions inherited from mlir::pdll::ast::Type
template<typename T>
const T * getImplAs () const
Return the internal storage instance of this type reinterpreted as the given derived storage type.
Detailed Description
This class represents a PDLL tuple type, i.e.
an ordered set of element types with optional names.
Definition at line 332 of file Types.h.
Member Function Documentation
empty()
bool mlir::pdll::ast::TupleType::empty () const inline
Return if the tuple has no elements.
Definition at line 351 of file Types.h.
References size().
get() [1/2]
TupleType TupleType::get (Context & context, ArrayRef< Type > elementTypes, ArrayRef< StringRef > elementNames) static
Return an instance of the Tuple type.
Definition at line 143 of file Types.cpp.
References mlir::StorageUniquer::get(), and mlir::pdll::ast::Context::getTypeUniquer().
Referenced by mlir::pdll::ast::TupleExpr::create().
get() [2/2]
TupleType TupleType::get (Context & context, ArrayRef< Type > elementTypes = {}) static
Definition at line 149 of file Types.cpp.
References mlir::get().
getElementNames()
ArrayRef< StringRef > TupleType::getElementNames () const
Return the element names of this tuple.
Definition at line 158 of file Types.cpp.
References mlir::pdll::ast::Type::getImplAs().
getElementTypes()
ArrayRef< Type > TupleType::getElementTypes () const
Return the element types of this tuple.
Definition at line 154 of file Types.cpp.
References mlir::pdll::ast::Type::getImplAs().
Referenced by size().
size()
size_t TupleType::size () const inline
Return the number of elements within this tuple.
Return the number of element types.
Definition at line 348 of file Types.h.
References getElementTypes().
Referenced by empty().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Types.h
lib/IR/BuiltinTypes.cpp
lib/Tools/PDLL/AST/Types.cpp