MLIR: mlir::quant::QuantizedType Class Reference
mlir::quant::QuantizedType Class Reference
Base class for all quantized types known to this dialect.
#include "mlir/Dialect/Quant/IR/QuantTypes.h"
Public Types
using ImplType = detail::QuantizedTypeStorage
Public Types inherited from mlir::Type
template<typename ConcreteType, typename BaseType, typename StorageType, template< typename T > class... Traits>
using TypeBase
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Public Member Functions
Type getExpressedType () const
Gets the original expressed type that this quantized type approximates.
unsigned getFlags () const
Gets the flags associated with this type.
bool isSigned () const
Whether the storage type should be interpreted as a signed quantity (true) or an unsigned value (false).
Type getStorageType () const
Gets the underlying type used for to store values.
int64_t getStorageTypeMin () const
The minimum value that storageType can take.
int64_t getStorageTypeMax () const
The maximum value that storageType can take.
bool hasStorageTypeBounds () const
Return whether the storage type has explicit min or max boundaries different from the minimum and maximum representable values.
unsigned getStorageTypeIntegralWidth () const
Gets the integral bit width that the underlying storage type can exactly represent.
bool isCompatibleExpressedType (Type candidateExpressedType)
Returns whether the candidateExpressedType is a match for this QuantizedType.
Type castFromStorageType (Type candidateType)
Casts from a type based on the storageType to a corresponding type based on this type (returns nullptr if the cast is not valid).
Type castFromExpressedType (Type candidateType)
Casts from a type based on the expressedType to a corresponding type based on this type (returns nullptr if the cast is not valid).
Type castExpressedToStorageType (Type candidateType)
Casts from a type based on the expressedType to the equivalent type based on storageType by way of this QuantizedType.
constexpr Type ()=default
Type (const ImplType *impl)
Type (const Type &other)=default
Public Member Functions inherited from mlir::Type
constexpr Type ()=default
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isTF32 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isFloat () const
Return true if this is an float type (with the specified width).
bool isFloat (unsigned width) const
Return true if this is a float type with the specified width.
bool isInteger () const
Return true if this is an integer type (with the specified width).
bool isInteger (unsigned width) const
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void print (raw_ostream &os, AsmState &state) const
void dump () const
friend::llvm::hash_code hash_value (Type arg)
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
template<typename InterfaceT>
bool hasPromiseOrImplementsInterface ()
Returns true if InterfaceT has been promised by the dialect or implemented.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the type was registered with a particular trait.
const AbstractTy & getAbstractType () const
Return the abstract type descriptor for this type.
ImplType * getImpl () const
Return the Type implementation.
void walkImmediateSubElements (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn) const
Walk all of the immediately nested sub-attributes and sub-types.
auto replaceImmediateSubElements (ArrayRef< Attribute > replAttrs, ArrayRef< Type > replTypes) const
Replace the immediately nested sub-attributes and sub-types with those provided.
template<WalkOrder Order = WalkOrder::PostOrder, typename... WalkFns>
auto walk (WalkFns &&...walkFns)
Walk this type and all attibutes/types nested within using the provided walk functions.
template<typename... ReplacementFns>
auto replace (ReplacementFns &&...replacementFns)
Recursively replace all of the nested sub-attributes and sub-types using the provided map functions.
Static Public Member Functions
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
static bool classof (Type type)
Support method to enable LLVM-style type casting.
static int64_t getDefaultMinimumForInteger (bool isSigned, unsigned integralWidth)
Gets the minimum possible stored by a storageType.
static int64_t getDefaultMaximumForInteger (bool isSigned, unsigned integralWidth)
Gets the maximum possible stored by a storageType.
static QuantizedType getQuantizedElementType (Type primitiveOrContainerType)
Returns the element type as a QuantizedType or nullptr if it is not a quantized type.
static Type castToStorageType (Type quantizedType)
Casts from a type based on a QuantizedType to a corresponding type based on the storageType (returns nullptr if the cast is not valid).
static Type castToExpressedType (Type quantizedType)
Casts from a type based on QuantizedType to a corresponding type based on the expressedType (returns nullptr if the cast is not valid).
Static Public Member Functions inherited from mlir::Type
static Type getFromOpaquePointer (const void *pointer)
Static Public Attributes
static constexpr unsigned MaxStorageBits = 32
The maximum number of bits supported for storage types.
Additional Inherited Members
Protected Attributes inherited from mlir::Type
ImplType * impl {nullptr}
Detailed Description
Base class for all quantized types known to this dialect.
All quantized types have:
storageType: The (narrower) numeric type that is being used to approximate some expressed type.
expressedType: The type that is being approximated.
The base class provides generic support for manipulating the types based on these fields.
Definition at line 50 of file QuantTypes.h.
Member Typedef Documentation
ImplType
using mlir::quant::QuantizedType::ImplType = detail::QuantizedTypeStorage
Definition at line 52 of file QuantTypes.h.
Member Function Documentation
castExpressedToStorageType()
Type QuantizedType::castExpressedToStorageType (Type candidateType)
Casts from a type based on the expressedType to the equivalent type based on storageType by way of this QuantizedType.
Equivalent to: QuantizedType::castToStorageType(castFromExpressedType(candidateType)) (but with validity checks). Example (for this = !quant.uniform<i8:f32, 1.0>): tensor<4xf32> -> tensor<4xi8>
Definition at line 234 of file QuantTypes.cpp.
References castFromExpressedType(), castToStorageType(), and Type().
castFromExpressedType()
Type QuantizedType::castFromExpressedType (Type candidateType)
Casts from a type based on the expressedType to a corresponding type based on this type (returns nullptr if the cast is not valid).
Examples: f32 -> !quant.uniform<i8:f32, 1.0> tensor<4xf32> -> tensor<4x!quant.uniform<i8:f32, 1.0>> vector<4xf32> -> vector<4x!quant.uniform<i8:f32, 1.0>>
Definition at line 179 of file QuantTypes.cpp.
References getExpressedType(), and Type().
Referenced by castExpressedToStorageType().
castFromStorageType()
Type QuantizedType::castFromStorageType (Type candidateType)
Casts from a type based on the storageType to a corresponding type based on this type (returns nullptr if the cast is not valid).
Examples: candidate type -> return type i8 -> !quant.uniform<i8:f32, 1.0> tensor<4xi8> -> tensor<4x!quant.uniform<i8:f32, 1.0}>> vector<4xi8> -> vector<4x!quant.uniform<i8:f32, 1.0>> It is assumed above that this type's quantization is <i8:f32, 1.0>.
Definition at line 128 of file QuantTypes.cpp.
References getShape(), getStorageType(), and Type().
castToExpressedType()
Type QuantizedType::castToExpressedType (Type quantizedType) static
Casts from a type based on QuantizedType to a corresponding type based on the expressedType (returns nullptr if the cast is not valid).
This is the inverse of castFromExpressedType.
Definition at line 207 of file QuantTypes.cpp.
References Type().
Referenced by mlirQuantizedTypeCastToExpressedType().
castToStorageType()
Type QuantizedType::castToStorageType (Type quantizedType) static
Casts from a type based on a QuantizedType to a corresponding type based on the storageType (returns nullptr if the cast is not valid).
This is the inverse of castFromStorageType().
Definition at line 152 of file QuantTypes.cpp.
References Type().
Referenced by castExpressedToStorageType(), and mlirQuantizedTypeCastToStorageType().
classof()
bool QuantizedType::classof (Type type) static
Support method to enable LLVM-style type casting.
Definition at line 40 of file QuantTypes.cpp.
References mlir::Type::getDialect(), and Type().
getDefaultMaximumForInteger()
int64_t mlir::quant::QuantizedType::getDefaultMaximumForInteger (bool isSigned, unsigned integralWidth) inline static
Gets the maximum possible stored by a storageType.
storageTypeMax must be less than or equal to this value.
Definition at line 78 of file QuantTypes.h.
References isSigned().
Referenced by hasStorageTypeBounds(), mlirQuantizedTypeGetDefaultMaximumForInteger(), parseStorageRange(), and verifyInvariants().
getDefaultMinimumForInteger()
int64_t mlir::quant::QuantizedType::getDefaultMinimumForInteger (bool isSigned, unsigned integralWidth) inline static
Gets the minimum possible stored by a storageType.
storageTypeMin must be greater than or equal to this value.
Definition at line 68 of file QuantTypes.h.
References isSigned().
Referenced by hasStorageTypeBounds(), mlirQuantizedTypeGetDefaultMinimumForInteger(), parseStorageRange(), and verifyInvariants().
getExpressedType()
Type QuantizedType::getExpressedType () const
Gets the original expressed type that this quantized type approximates.
Note that this presumes that the quantized type was always derived from a floating point type, which in the broadest definition, is not true (i.e. it could be some form of integral, fixed type or affine type in its own right); however, at the high level, no examples of such usage are presently known and the restriction serves some useful purposes (such as always being able to reverse a transformation or measure error). In most cases, this will be f32.
Definition at line 106 of file QuantTypes.cpp.
References Type().
Referenced by castFromExpressedType(), mlir::quant::ExpressedToQuantizedConverter::convert(), and isCompatibleExpressedType().
getFlags()
unsigned QuantizedType::getFlags () const
Gets the flags associated with this type.
Typically a more specific accessor is appropriate.
Definition at line 36 of file QuantTypes.cpp.
Referenced by isSigned().
getQuantizedElementType()
QuantizedType QuantizedType::getQuantizedElementType (Type primitiveOrContainerType) static
Returns the element type as a QuantizedType or nullptr if it is not a quantized type.
If the type is primitive, returns that. If it is a container (vector/tensor), return the element type. Examples: !quant.uniform<i8:f32, 1.0> -> !quant.uniform<i8:f32, 1.0> tensor<4x!quant.uniform<i8:f32, 1.0> -> quant.uniform<i8:f32, 1.0>
Definition at line 119 of file QuantTypes.cpp.
References Type().
Referenced by mlirQuantizedTypeGetQuantizedElementType().
getStorageType()
Type QuantizedType::getStorageType () const
Gets the underlying type used for to store values.
Note that this may be signed or unsigned. Use the isSigned() accessor to differentiate.
Definition at line 77 of file QuantTypes.cpp.
References Type().
Referenced by castFromStorageType(), and mlir::tosa::getStorageElementTypeFromQuantized().
getStorageTypeIntegralWidth()
unsigned QuantizedType::getStorageTypeIntegralWidth () const
Gets the integral bit width that the underlying storage type can exactly represent.
For integral storage types, this will just be their width.
Definition at line 100 of file QuantTypes.cpp.
Referenced by hasStorageTypeBounds(), and printStorageType().
getStorageTypeMax()
int64_t QuantizedType::getStorageTypeMax () const
The maximum value that storageType can take.
Definition at line 85 of file QuantTypes.cpp.
Referenced by hasStorageTypeBounds(), and printStorageType().
getStorageTypeMin()
int64_t QuantizedType::getStorageTypeMin () const
The minimum value that storageType can take.
Definition at line 81 of file QuantTypes.cpp.
Referenced by hasStorageTypeBounds(), and printStorageType().
hasStorageTypeBounds()
bool QuantizedType::hasStorageTypeBounds () const
Return whether the storage type has explicit min or max boundaries different from the minimum and maximum representable values.
Definition at line 89 of file QuantTypes.cpp.
References getDefaultMaximumForInteger(), getDefaultMinimumForInteger(), getStorageTypeIntegralWidth(), getStorageTypeMax(), getStorageTypeMin(), isSigned(), and mlir::Type::isSignedInteger().
Referenced by printStorageType().
isCompatibleExpressedType()
bool QuantizedType::isCompatibleExpressedType (Type candidateExpressedType)
Returns whether the candidateExpressedType is a match for this QuantizedType.
This will be true if the candidate type is either a primitive type or a container type whose element type equals this QuantizedType's expressed type. Examples of compatible candidateExpressedType: !quant.uniform<i8:f32, 1.0> =~ f32 !quant.uniform<i8:f32, 1.0> =~ tensor<4xf32>
Definition at line 110 of file QuantTypes.cpp.
References getExpressedType(), and Type().
isSigned()
bool mlir::quant::QuantizedType::isSigned () const inline
Whether the storage type should be interpreted as a signed quantity (true) or an unsigned value (false).
Definition at line 103 of file QuantTypes.h.
References getFlags(), and mlir::quant::QuantizationFlags::Signed.
Referenced by getDefaultMaximumForInteger(), getDefaultMinimumForInteger(), mlir::tosa::getStorageElementTypeFromQuantized(), hasStorageTypeBounds(), printStorageType(), and verifyInvariants().
Type() [1/3]
mlir::Type::Type () constexpr default
Referenced by castExpressedToStorageType(), castFromExpressedType(), castFromStorageType(), castToExpressedType(), castToStorageType(), classof(), getExpressedType(), getQuantizedElementType(), getStorageType(), isCompatibleExpressedType(), and verifyInvariants().
Type() [2/3]
mlir::Type::Type (const ImplType * impl) inline
Definition at line 87 of file Types.h.
Type() [3/3]
mlir::Type::Type (const Type & other) default
verifyInvariants()
LogicalResult QuantizedType::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax) static
Definition at line 45 of file QuantTypes.cpp.
References mlir::emitError(), getDefaultMaximumForInteger(), getDefaultMinimumForInteger(), isSigned(), MaxStorageBits, mlir::quant::QuantizationFlags::Signed, success(), and Type().
Referenced by mlir::quant::AnyQuantizedType::verifyInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyInvariants(), mlir::quant::UniformQuantizedSubChannelType::verifyInvariants(), and mlir::quant::UniformQuantizedType::verifyInvariants().
Member Data Documentation
MaxStorageBits
unsigned mlir::quant::QuantizedType::MaxStorageBits = 32 static constexpr
The maximum number of bits supported for storage types.
Definition at line 56 of file QuantTypes.h.
Referenced by parseStorageType(), and verifyInvariants().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Quant/IR/QuantTypes.h
lib/Dialect/Quant/IR/QuantTypes.cpp