MLIR: mlir::ConstantFloatOp Class Reference
mlir::ConstantFloatOp Class Reference
This is a refinement of the "constant" op for the case where it is returning a float value of FloatType.
#include "mlir/Dialect/StandardOps/IR/Ops.h"
Public Member Functions
APFloat getValue ()
Static Public Member Functions
static void build (OpBuilder &builder, OperationState &result, const APFloat &value, FloatType type)
Builds a constant float op producing a float of the specified type.
static bool classof (Operation *op)
Detailed Description
This is a refinement of the "constant" op for the case where it is returning a float value of FloatType.
%1 = "std.constant"(){value: 42.0} : bf16
Definition at line 49 of file Ops.h.
Member Function Documentation
build()
void ConstantFloatOp::build (OpBuilder & builder, OperationState & result, const APFloat & value, FloatType type) static
Builds a constant float op producing a float of the specified type.
Definition at line 1252 of file Ops.cpp.
References mlir::Builder::getFloatAttr().
classof()
bool ConstantFloatOp::classof (Operation * op) static
Definition at line 1257 of file Ops.cpp.
References mlir::Operation::getResult(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by getValue(), mlir::ConstantIntOp::getValue(), and mlir::ConstantIndexOp::getValue().
getValue()
APFloat mlir::ConstantFloatOp::getValue () inline
Definition at line 57 of file Ops.h.
References classof(), and op.
The documentation for this class was generated from the following files:
include/mlir/Dialect/StandardOps/IR/Ops.h
lib/Dialect/StandardOps/IR/Ops.cpp