MLIR: mlir::sparse_tensor::ir_detail::LvlExpr Class Reference
mlir::sparse_tensor::ir_detail::LvlExpr Class Reference final
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
constexpr LvlExpr (AffineExpr expr)
DimVar castDimVar () const
std::optional< DimVar > dyn_castDimVar () const
Public Member Functions inherited from mlir::sparse_tensor::ir_detail::DimLvlExpr
constexpr DimLvlExpr (ExprKind ek, AffineExpr expr)
constexpr bool operator== (DimLvlExpr other) const
constexpr bool operator!= (DimLvlExpr other) const
operator bool () const
template<typename U >
constexpr bool isa () const
template<typename U >
constexpr U cast () const
template<typename U >
constexpr U dyn_cast () const
constexpr ExprKind getExprKind () const
constexpr VarKind getAllowedVarKind () const
constexpr AffineExpr getAffineExpr () const
AffineExprKind getAffineKind () const
MLIRContext * tryGetContext () const
SymVar castSymVar () const
std::optional< SymVar > dyn_castSymVar () const
Var castDimLvlVar () const
std::optional< Var > dyn_castDimLvlVar () const
std::tuple< DimLvlExpr, AffineExprKind, DimLvlExpr > unpackBinop () const
bool isValid (Ranks const &ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
Static Public Member Functions
static constexpr bool classof (DimLvlExpr const *expr)
Static Public Attributes
static constexpr ExprKind Kind = ExprKind::Level
Friends
class DimLvlExpr
Additional Inherited Members
Protected Types inherited from mlir::sparse_tensor::ir_detail::DimLvlExpr
enum class BindingStrength : bool { Weak = false , Strong = true }
Detailed Description
Definition at line 115 of file DimLvlMap.h.
Constructor & Destructor Documentation
LvlExpr()
constexpr mlir::sparse_tensor::ir_detail::LvlExpr::LvlExpr (AffineExpr expr) inline explicit constexpr
Definition at line 124 of file DimLvlMap.h.
Member Function Documentation
castDimVar()
DimVar mlir::sparse_tensor::ir_detail::LvlExpr::castDimVar () const inline
Definition at line 126 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Var::cast(), and mlir::sparse_tensor::ir_detail::DimLvlExpr::castDimLvlVar().
classof()
static constexpr bool mlir::sparse_tensor::ir_detail::LvlExpr::classof (DimLvlExpr const * expr) inline static constexpr
Definition at line 121 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::getExprKind(), and Kind.
dyn_castDimVar()
std::optional<DimVar> mlir::sparse_tensor::ir_detail::LvlExpr::dyn_castDimVar () const inline
Definition at line 127 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::dyn_castDimLvlVar().
Friends And Related Function Documentation
DimLvlExpr
friend class DimLvlExpr friend
Definition at line 116 of file DimLvlMap.h.
Member Data Documentation
Kind
constexpr ExprKind mlir::sparse_tensor::ir_detail::LvlExpr::Kind = ExprKind::Level static constexpr
Definition at line 120 of file DimLvlMap.h.
Referenced by classof().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h