MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap Class Reference
A list of operation attributes.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyOpAttributeMap (PyOperationRef operation)
nanobind::typed< nanobind::object, PyAttribute > dunderGetItemNamed (const std::string &name)
PyNamedAttribute dunderGetItemIndexed (intptr_t index)
nanobind::typed< nanobind::object, std::optional< PyAttribute > > get (const std::string &key, nanobind::object defaultValue)
void dunderSetItem (const std::string &name, const PyAttribute &attr)
void dunderDelItem (const std::string &name)
intptr_t dunderLen ()
bool dunderContains (const std::string &name)
Static Public Member Functions
static void forEachAttr (MlirOperation op, std::function< void(MlirStringRef, MlirAttribute)> fn)
static void bind (nanobind::module_ &m)
Detailed Description
A list of operation attributes.
Can be indexed by name, producing attributes, or by index, producing named attributes.
Definition at line 1924 of file IRCore.h.
Constructor & Destructor Documentation
PyOpAttributeMap()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::PyOpAttributeMap (PyOperationRef operation) inline
Definition at line 1926 of file IRCore.h.
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::bind (nanobind::module_ & m) static
Definition at line 2458 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderContains()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderContains (const std::string & name)
Definition at line 2443 of file IRCore.cpp.
References mlirOperationGetNumAttributes().
dunderDelItem()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderDelItem (const std::string & name)
Definition at line 2432 of file IRCore.cpp.
References mlirOperationSetAttributeByName(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
dunderGetItemIndexed()
PyNamedAttribute mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderGetItemIndexed (intptr_t index)
Definition at line 2411 of file IRCore.cpp.
dunderGetItemNamed()
nb::typed< nb::object, PyAttribute > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderGetItemNamed (const std::string & name)
Definition at line 2393 of file IRCore.cpp.
References mlir::Sliceable< PyBlockPredecessors, PyBlock >::length, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockPredecessors::PyBlockPredecessors(), mlir::Sliceable< PyBlockPredecessors, PyBlock >::startIndex, and mlir::Sliceable< PyBlockPredecessors, PyBlock >::step.
dunderLen()
intptr_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderLen ()
Definition at line 2439 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
dunderSetItem()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderSetItem (const std::string & name, const PyAttribute & attr)
Definition at line 2426 of file IRCore.cpp.
References mlirIdentifierStr().
forEachAttr()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::forEachAttr (MlirOperation op, std::function< void(MlirStringRef, MlirAttribute)> fn) static
Definition at line 2448 of file IRCore.cpp.
References mlirOperationGetAttributeByName(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
get()
nb::typed< nb::object, std::optional< PyAttribute > > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::get (const std::string & key, nanobind::object defaultValue)
Definition at line 2403 of file IRCore.cpp.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp