MLIR: mlir::python::BaseContextObject Class Reference
mlir::python::BaseContextObject Class Reference
Base class for all objects that directly or indirectly depend on an MlirContext.
#include "Bindings/Python/IRModule.h"
Public Member Functions
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Base class for all objects that directly or indirectly depend on an MlirContext.
The lifetime of the context will extend at least to the lifetime of these instances. Immutable objects that depend on a context extend this directly.
Definition at line 284 of file IRModule.h.
Constructor & Destructor Documentation
BaseContextObject()
mlir::python::BaseContextObject::BaseContextObject (PyMlirContextRef ref) inline
Definition at line 286 of file IRModule.h.
Referenced by mlir::python::PyAffineExpr::PyAffineExpr(), mlir::python::PyAffineMap::PyAffineMap(), mlir::python::PyAttribute::PyAttribute(), mlir::python::PyDialectDescriptor::PyDialectDescriptor(), mlir::python::PyDialects::PyDialects(), mlir::python::PyIntegerSet::PyIntegerSet(), mlir::python::PyLocation::PyLocation(), mlir::python::PyOperation::PyOperation(), and mlir::python::PyType::PyType().
Member Function Documentation
getContext()
PyMlirContextRef & mlir::python::BaseContextObject::getContext () inline
Accesses the context reference.
Definition at line 292 of file IRModule.h.
Referenced by mlir::PyShapedType::bindDerived(), mlir::python::PyStringAttribute::bindDerived(), PyOpResultList::bindDerived(), mlir::python::PyOpView::buildGeneric(), mlir::python::PyOperation::clone(), mlir::python::PyOperation::create(), mlir::python::PyDialects::getDialectForKey(), mlir::python::PyOperation::getParentOperation(), mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::getVisibility(), mlir::python::PySymbolTable::insert(), mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType(), mlir::python::PyOperationBase::verify(), mlir::python::PySymbolTable::walkSymbolTables(), and mlir::python::PyModule::~PyModule().
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRModule.h