MLIR: mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator Class Reference
mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator Class Reference
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
Public Member Functions
iterator (const GEPIndicesAdaptor *base, ArrayRef< int32_t >::iterator rawConstantIter, llvm::detail::IterOfRange< const DynamicRange > valuesIter)
value_type operator* () const
iterator & operator++ ()
bool operator== (const iterator &rhs) const
Detailed Description
template<typename DynamicRange>
class mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator
Definition at line 157 of file LLVMDialect.h.
Constructor & Destructor Documentation
iterator()
template<typename DynamicRange> mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator::iterator (const GEPIndicesAdaptor * base, ArrayRef< int32_t >::iterator rawConstantIter, llvm::detail::IterOfRange< const DynamicRange > valuesIter) inline
Definition at line 162 of file LLVMDialect.h.
References mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::GEPIndicesAdaptor().
Referenced by operator++(), and operator==().
Member Function Documentation
operator*()
template<typename DynamicRange> value_type mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator::operator* () const inline
Definition at line 168 of file LLVMDialect.h.
operator++()
template<typename DynamicRange> iterator & mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator::operator++ () inline
Definition at line 176 of file LLVMDialect.h.
References iterator().
operator==()
template<typename DynamicRange> bool mlir::LLVM::GEPIndicesAdaptor< DynamicRange >::iterator::operator== (const iterator & rhs) const inline
Definition at line 183 of file LLVMDialect.h.
References iterator(), and rhs.
The documentation for this class was generated from the following file:
include/mlir/Dialect/LLVMIR/LLVMDialect.h