MLIR: mlir::StorageUniquer::StorageAllocator Class Reference
mlir::StorageUniquer::StorageAllocator Class Reference
This is a utility allocator used to allocate memory for instances of derived types.
#include "mlir/Support/StorageUniquer.h"
Public Member Functions
template<typename T >
ArrayRef< T > copyInto (ArrayRef< T > elements)
Copy the specified array of elements into memory managed by our bump pointer allocator.
StringRef copyInto (StringRef str)
Copy the provided string into memory managed by our bump pointer allocator.
template<typename T >
T * allocate ()
Allocate an instance of the provided type.
void * allocate (size_t size, size_t alignment)
Allocate 'size' bytes of 'alignment' aligned memory.
bool allocated (const void *ptr)
Returns true if this allocator allocated the provided object pointer.
Detailed Description
This is a utility allocator used to allocate memory for instances of derived types.
Definition at line 93 of file StorageUniquer.h.
Member Function Documentation
allocate() [1/2]
template<typename T > T* mlir::StorageUniquer::StorageAllocator::allocate () inline
Allocate an instance of the provided type.
Definition at line 120 of file StorageUniquer.h.
Referenced by mlir::detail::FileLineColRangeAttrStorage::construct(), mlir::detail::DynamicAttrStorage::construct(), mlir::detail::DataLayoutEntryAttrStorage::construct(), mlir::spirv::detail::InterfaceVarABIAttributeStorage::construct(), mlir::spirv::detail::VerCapExtAttributeStorage::construct(), mlir::spirv::detail::TargetEnvAttributeStorage::construct(), mlir::vector::detail::BitmaskEnumStorage::construct(), mlir::detail::StringAttrStorage::construct(), mlir::detail::DenseIntOrFPElementsAttrStorage::construct(), mlir::detail::DenseStringElementsAttrStorage::construct(), mlir::pdll::ast::detail::TypeStorageBase< ConcreteT, KeyT >::construct(), mlir::pdll::ast::detail::OperationTypeStorage::construct(), mlir::pdl_to_pdl_interp::PredicateBase< ConcreteT, BaseT, Key, Kind >::construct(), mlir::ProgramPoint::construct(), mlir::pdll::ast::detail::TupleTypeStorage::construct(), mlir::GenericLatticeAnchorBase< ConcreteT, Value >::construct(), mlir::detail::AffineBinaryOpExprStorage::construct(), mlir::detail::AffineDimExprStorage::construct(), mlir::detail::AffineConstantExprStorage::construct(), mlir::detail::AffineMapStorage::construct(), mlir::detail::IntegerSetStorage::construct(), mlir::detail::DynamicTypeStorage::construct(), mlir::gpu::MMAMatrixStorageType::construct(), mlir::LLVM::detail::LLVMStructTypeStorage::construct(), mlir::LLVM::detail::LLVMTypeAndSizeStorage::construct(), mlir::quant::detail::AnyQuantizedTypeStorage::construct(), mlir::quant::detail::UniformQuantizedTypeStorage::construct(), mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::construct(), mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::construct(), mlir::quant::detail::CalibratedQuantizedTypeStorage::construct(), mlir::spirv::detail::ArrayTypeStorage::construct(), mlir::spirv::detail::CooperativeMatrixTypeStorage::construct(), mlir::spirv::detail::ImageTypeStorage::construct(), mlir::spirv::detail::PointerTypeStorage::construct(), mlir::spirv::detail::RuntimeArrayTypeStorage::construct(), mlir::spirv::detail::SampledImageTypeStorage::construct(), mlir::spirv::detail::StructTypeStorage::construct(), mlir::spirv::detail::MatrixTypeStorage::construct(), mlir::spirv::detail::TensorArmTypeStorage::construct(), mlir::detail::FunctionTypeStorage::construct(), mlir::detail::IntegerTypeStorage::construct(), and mlir::detail::TupleTypeStorage::construct().
allocate() [2/2]
void* mlir::StorageUniquer::StorageAllocator::allocate (size_t size, size_t alignment) inline
Allocate 'size' bytes of 'alignment' aligned memory.
Definition at line 125 of file StorageUniquer.h.
allocated()
bool mlir::StorageUniquer::StorageAllocator::allocated (const void * ptr) inline
Returns true if this allocator allocated the provided object pointer.
Definition at line 130 of file StorageUniquer.h.
copyInto() [1/2]
template<typename T > ArrayRef<T> mlir::StorageUniquer::StorageAllocator::copyInto (ArrayRef< T > elements) inline
Copy the specified array of elements into memory managed by our bump pointer allocator.
This assumes the elements are all PODs.
Definition at line 98 of file StorageUniquer.h.
Referenced by mlir::detail::DynamicAttrStorage::construct(), mlir::detail::StringAttrStorage::construct(), mlir::pdll::ast::detail::OperationTypeStorage::construct(), mlir::pdl_to_pdl_interp::ConstraintQuestion::construct(), mlir::pdll::ast::detail::TupleTypeStorage::construct(), mlir::detail::IntegerSetStorage::construct(), mlir::detail::DynamicTypeStorage::construct(), mlir::gpu::MMAMatrixStorageType::construct(), mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::construct(), mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::construct(), mlir::spirv::detail::StructTypeStorage::construct(), mlir::spirv::detail::TensorArmTypeStorage::construct(), mlir::detail::FunctionTypeStorage::construct(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::copyIntoAllocator(), mlir::LLVM::detail::LLVMStructTypeStorage::mutate(), and mlir::spirv::detail::StructTypeStorage::mutate().
copyInto() [2/2]
StringRef mlir::StorageUniquer::StorageAllocator::copyInto (StringRef str) inline
Copy the provided string into memory managed by our bump pointer allocator.
Definition at line 108 of file StorageUniquer.h.
The documentation for this class was generated from the following file:
include/mlir/Support/StorageUniquer.h