MLIR: mlir::python::PyGlobals Class Reference
mlir::python::PyGlobals Class Reference
Globals that are always accessible once the extension has been initialized.
#include "Bindings/Python/Globals.h"
Classes
class TracebackLoc
class TypeIDAllocator
Public Member Functions
PyGlobals ()
~PyGlobals ()
std::vector< std::string > getDialectSearchPrefixes ()
Get and set the list of parent modules to search for dialect implementation classes.
void setDialectSearchPrefixes (std::vector< std::string > newValues)
void addDialectSearchPrefix (std::string value)
bool loadDialectModule (llvm::StringRef dialectNamespace)
Loads a python module corresponding to the given dialect namespace.
void registerAttributeBuilder (const std::string &attributeKind, nanobind::callable pyFunc, bool replace=false)
Adds a user-friendly Attribute builder.
void registerTypeCaster (MlirTypeID mlirTypeID, nanobind::callable typeCaster, bool replace=false)
Adds a user-friendly type caster.
void registerValueCaster (MlirTypeID mlirTypeID, nanobind::callable valueCaster, bool replace=false)
Adds a user-friendly value caster.
void registerDialectImpl (const std::string &dialectNamespace, nanobind::object pyClass)
Adds a concrete implementation dialect class.
void registerOperationImpl (const std::string &operationName, nanobind::object pyClass, bool replace=false)
Adds a concrete implementation operation class.
std::optional< nanobind::callable > lookupAttributeBuilder (const std::string &attributeKind)
Returns the custom Attribute builder for Attribute kind.
std::optional< nanobind::callable > lookupTypeCaster (MlirTypeID mlirTypeID, MlirDialect dialect)
Returns the custom type caster for MlirTypeID mlirTypeID.
std::optional< nanobind::callable > lookupValueCaster (MlirTypeID mlirTypeID, MlirDialect dialect)
Returns the custom value caster for MlirTypeID mlirTypeID.
std::optional< nanobind::object > lookupDialectClass (const std::string &dialectNamespace)
Looks up a registered dialect class by namespace.
std::optional< nanobind::object > lookupOperationClass (llvm::StringRef operationName)
Looks up a registered operation class (deriving from OpView) by operation name.
TracebackLoc & getTracebackLoc ()
MlirTypeID allocateTypeID ()
Static Public Member Functions
static PyGlobals & get ()
Most code should get the globals via this static accessor.
Detailed Description
Globals that are always accessible once the extension has been initialized.
Methods of this class are thread-safe.
Definition at line 33 of file Globals.h.
Constructor & Destructor Documentation
PyGlobals()
PyGlobals::PyGlobals ()
Definition at line 30 of file IRModule.cpp.
References MAKE_MLIR_PYTHON_QUALNAME.
Referenced by get().
~PyGlobals()
PyGlobals::~PyGlobals ()
Definition at line 38 of file IRModule.cpp.
Member Function Documentation
addDialectSearchPrefix()
void mlir::python::PyGlobals::addDialectSearchPrefix (std::string value) inline
Definition at line 54 of file Globals.h.
Referenced by NB_MODULE().
allocateTypeID()
MlirTypeID mlir::python::PyGlobals::allocateTypeID () inline
Definition at line 176 of file Globals.h.
get()
PyGlobals & mlir::python::PyGlobals::get () inline static
Most code should get the globals via this static accessor.
Definition at line 39 of file Globals.h.
References PyGlobals().
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::bind(), createCustomDialectWrapper(), mlir::python::PyOperation::createOpView(), PyAttrBuilderMap::dunderContains(), PyAttrBuilderMap::dunderGetItemNamed(), PyAttrBuilderMap::dunderSetItemNamed(), mlir::python::PyAttribute::maybeDownCast(), mlir::python::PyType::maybeDownCast(), mlir::python::PyValue::maybeDownCast(), and NB_MODULE().
getDialectSearchPrefixes()
std::vector< std::string > mlir::python::PyGlobals::getDialectSearchPrefixes () inline
Get and set the list of parent modules to search for dialect implementation classes.
Definition at line 46 of file Globals.h.
Referenced by NB_MODULE().
getTracebackLoc()
TracebackLoc & mlir::python::PyGlobals::getTracebackLoc () inline
Definition at line 153 of file Globals.h.
Referenced by NB_MODULE().
loadDialectModule()
bool PyGlobals::loadDialectModule (llvm::StringRef dialectNamespace)
Loads a python module corresponding to the given dialect namespace.
No-ops if the module has already been loaded or is not found. Raises an error on any evaluation issues. Note that this returns void because it is expected that the module contains calls to decorators and helpers that register the salient entities. Returns true if dialect is successfully loaded.
Definition at line 40 of file IRModule.cpp.
Referenced by lookupDialectClass(), lookupOperationClass(), lookupTypeCaster(), lookupValueCaster(), and NB_MODULE().
lookupAttributeBuilder()
std::optional< nb::callable > PyGlobals::lookupAttributeBuilder (const std::string & attributeKind)
Returns the custom Attribute builder for Attribute kind.
Definition at line 132 of file IRModule.cpp.
Referenced by PyAttrBuilderMap::dunderContains(), and PyAttrBuilderMap::dunderGetItemNamed().
lookupDialectClass()
std::optional< nb::object > PyGlobals::lookupDialectClass (const std::string & dialectNamespace)
Looks up a registered dialect class by namespace.
Note that this may trigger loading of the defining module and can arbitrarily re-enter.
Definition at line 169 of file IRModule.cpp.
References loadDialectModule().
Referenced by createCustomDialectWrapper().
lookupOperationClass()
std::optional< nb::object > PyGlobals::lookupOperationClass (llvm::StringRef operationName)
Looks up a registered operation class (deriving from OpView) by operation name.
Note that this may trigger a load of the dialect, which can arbitrarily re-enter.
Definition at line 184 of file IRModule.cpp.
References loadDialectModule().
Referenced by mlir::python::PyOperation::createOpView().
lookupTypeCaster()
std::optional< nb::callable > PyGlobals::lookupTypeCaster (MlirTypeID mlirTypeID, MlirDialect dialect)
Returns the custom type caster for MlirTypeID mlirTypeID.
Definition at line 142 of file IRModule.cpp.
References loadDialectModule(), mlirDialectGetNamespace(), and unwrap().
Referenced by mlir::python::PyAttribute::maybeDownCast(), and mlir::python::PyType::maybeDownCast().
lookupValueCaster()
std::optional< nb::callable > PyGlobals::lookupValueCaster (MlirTypeID mlirTypeID, MlirDialect dialect)
Returns the custom value caster for MlirTypeID mlirTypeID.
Definition at line 155 of file IRModule.cpp.
References loadDialectModule(), mlirDialectGetNamespace(), and unwrap().
Referenced by mlir::python::PyValue::maybeDownCast().
registerAttributeBuilder()
void PyGlobals::registerAttributeBuilder (const std::string & attributeKind, nanobind::callable pyFunc, bool replace = false)
Adds a user-friendly Attribute builder.
Raises an exception if the mapping already exists and replace == false. This is intended to be called by implementation code.
Definition at line 73 of file IRModule.cpp.
Referenced by PyAttrBuilderMap::dunderSetItemNamed().
registerDialectImpl()
void PyGlobals::registerDialectImpl (const std::string & dialectNamespace, nanobind::object pyClass)
Adds a concrete implementation dialect class.
Raises an exception if the mapping already exists. This is intended to be called by implementation code.
Definition at line 107 of file IRModule.cpp.
Referenced by NB_MODULE().
registerOperationImpl()
void PyGlobals::registerOperationImpl (const std::string & operationName, nanobind::object pyClass, bool replace = false)
Adds a concrete implementation operation class.
Raises an exception if the mapping already exists and replace == false. This is intended to be called by implementation code.
Definition at line 119 of file IRModule.cpp.
Referenced by NB_MODULE().
registerTypeCaster()
void PyGlobals::registerTypeCaster (MlirTypeID mlirTypeID, nanobind::callable typeCaster, bool replace = false)
Adds a user-friendly type caster.
Raises an exception if the mapping already exists and replace == false. This is intended to be called by implementation code.
Definition at line 87 of file IRModule.cpp.
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::bind(), and NB_MODULE().
registerValueCaster()
void PyGlobals::registerValueCaster (MlirTypeID mlirTypeID, nanobind::callable valueCaster, bool replace = false)
Adds a user-friendly value caster.
Raises an exception if the mapping already exists and replace == false. This is intended to be called by implementation code.
Definition at line 97 of file IRModule.cpp.
Referenced by NB_MODULE().
setDialectSearchPrefixes()
void mlir::python::PyGlobals::setDialectSearchPrefixes (std::vector< std::string > newValues) inline
Definition at line 50 of file Globals.h.
Referenced by NB_MODULE().
The documentation for this class was generated from the following files:
lib/Bindings/Python/Globals.h
lib/Bindings/Python/IRModule.cpp