MLIR: mlir::python::PyShapedTypeComponents Class Reference
mlir::python::PyShapedTypeComponents Class Reference
Wrapper around an shaped type components.
Public Member Functions
PyShapedTypeComponents (MlirType elementType)
PyShapedTypeComponents (nb::list shape, MlirType elementType)
PyShapedTypeComponents (nb::list shape, MlirType elementType, MlirAttribute attribute)
PyShapedTypeComponents (PyShapedTypeComponents &)=delete
PyShapedTypeComponents (PyShapedTypeComponents &&other) noexcept
nb::object getCapsule ()
Static Public Member Functions
static void bind (nb::module_ &m)
static PyShapedTypeComponents createFromCapsule (nb::object capsule)
Detailed Description
Wrapper around an shaped type components.
Definition at line 311 of file IRInterfaces.cpp.
Constructor & Destructor Documentation
PyShapedTypeComponents() [1/5]
mlir::python::PyShapedTypeComponents::PyShapedTypeComponents (MlirType elementType) inline
Definition at line 313 of file IRInterfaces.cpp.
Referenced by bind(), createFromCapsule(), PyShapedTypeComponents(), and PyShapedTypeComponents().
PyShapedTypeComponents() [2/5]
mlir::python::PyShapedTypeComponents::PyShapedTypeComponents (nb::list shape, MlirType elementType) inline
Definition at line 314 of file IRInterfaces.cpp.
References true.
PyShapedTypeComponents() [3/5]
mlir::python::PyShapedTypeComponents::PyShapedTypeComponents (nb::list shape, MlirType elementType, MlirAttribute attribute) inline
Definition at line 316 of file IRInterfaces.cpp.
References true.
PyShapedTypeComponents() [4/5]
mlir::python::PyShapedTypeComponents::PyShapedTypeComponents (PyShapedTypeComponents &) delete
References PyShapedTypeComponents().
PyShapedTypeComponents() [5/5]
mlir::python::PyShapedTypeComponents::PyShapedTypeComponents (PyShapedTypeComponents && other) inline noexcept
Definition at line 321 of file IRInterfaces.cpp.
References PyShapedTypeComponents().
Member Function Documentation
bind()
void mlir::python::PyShapedTypeComponents::bind (nb::module_ & m) inline static
Definition at line 325 of file IRInterfaces.cpp.
References PyShapedTypeComponents().
Referenced by mlir::python::populateIRInterfaces().
createFromCapsule()
PyShapedTypeComponents mlir::python::PyShapedTypeComponents::createFromCapsule (nb::object capsule) static
References PyShapedTypeComponents().
getCapsule()
nb::object mlir::python::PyShapedTypeComponents::getCapsule ()
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRInterfaces.cpp