MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool Class Reference
Wrapper around MlirLlvmThreadPool Python object owns the C++ thread pool.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyThreadPool ()
~PyThreadPool ()
PyThreadPool (const PyThreadPool &)=delete
PyThreadPool (PyThreadPool &&)=delete
int getMaxConcurrency () const
MlirLlvmThreadPool get ()
std::string _mlir_thread_pool_ptr () const
Detailed Description
Wrapper around MlirLlvmThreadPool Python object owns the C++ thread pool.
Definition at line 193 of file IRCore.h.
Constructor & Destructor Documentation
PyThreadPool() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::PyThreadPool ()
Definition at line 406 of file IRCore.cpp.
Referenced by PyThreadPool(), and PyThreadPool().
~PyThreadPool()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::~PyThreadPool ()
Definition at line 408 of file IRCore.cpp.
References mlirLlvmThreadPoolCreate().
PyThreadPool() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::PyThreadPool (const PyThreadPool &) delete
References PyThreadPool().
PyThreadPool() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::PyThreadPool (PyThreadPool &&) delete
References getMaxConcurrency(), and PyThreadPool().
Member Function Documentation
_mlir_thread_pool_ptr()
std::string mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::_mlir_thread_pool_ptr () const
Definition at line 417 of file IRCore.cpp.
References mlirLlvmThreadPoolGetMaxConcurrency().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirLlvmThreadPool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::get () inline
Definition at line 201 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getMaxConcurrency()
int mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::getMaxConcurrency () const
Definition at line 413 of file IRCore.cpp.
References mlirLlvmThreadPoolDestroy().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore(), and PyThreadPool().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp