MLIR: mlir::python::PyAttribute Class Reference
mlir::python::PyAttribute Class Reference
Wrapper around the generic MlirAttribute.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyAttribute createFromCapsule (nanobind::object capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Detailed Description
Wrapper around the generic MlirAttribute.
The lifetime of a type is bound by the PyContext that created it.
Definition at line 1045 of file IRModule.h.
Constructor & Destructor Documentation
PyAttribute()
mlir::python::PyAttribute::PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr) inline
Definition at line 1047 of file IRModule.h.
Referenced by createFromCapsule().
Member Function Documentation
createFromCapsule()
PyAttribute PyAttribute::createFromCapsule (nanobind::object capsule) static
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Note that PyAttribute instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirAttribute is taken by calling this function.
Definition at line 2212 of file IRCore.cpp.
References mlir::python::PyMlirContext::forContext(), mlirAttributeGetContext(), mlirAttributeIsNull(), mlirPythonCapsuleToAttribute(), and PyAttribute().
get()
MlirAttribute mlir::python::PyAttribute::get () const inline
Definition at line 1051 of file IRModule.h.
getCapsule()
nb::object PyAttribute::getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
Definition at line 2208 of file IRCore.cpp.
References mlirPythonAttributeToCapsule().
operator MlirAttribute()
mlir::python::PyAttribute::operator MlirAttribute () const inline
Definition at line 1050 of file IRModule.h.
operator==()
bool PyAttribute::operator== (const PyAttribute & other) const
Definition at line 2204 of file IRCore.cpp.
References mlirAttributeEqual().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp