MLIR: mlir::PyShapedType Class Reference
mlir::PyShapedType Class Reference
Shaped Type Interface - ShapedType.
#include "mlir/Bindings/Python/IRTypes.h"
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::PyConcreteType< PyShapedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::PyType
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Static Public Attributes
static const IsAFunctionTy isaFunction
static constexpr const char * pyClassName = "ShapedType"
Static Public Attributes inherited from mlir::python::PyConcreteType< PyShapedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
Additional Inherited Members
Public Types inherited from mlir::python::PyConcreteType< PyShapedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
Public Member Functions inherited from mlir::python::PyConcreteType< PyShapedType >
PyConcreteType ()=default
Public Member Functions inherited from mlir::python::PyType
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::object maybeDownCast ()
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Shaped Type Interface - ShapedType.
Definition at line 17 of file IRTypes.h.
Member Function Documentation
bindDerived()
void mlir::PyShapedType::bindDerived (ClassTy & c) static
Definition at line 515 of file IRTypes.cpp.
References mlir::python::BaseContextObject::getContext(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetDynamicSize(), mlirShapedTypeGetDynamicStrideOrOffset(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirShapedTypeIsDynamicSize(), mlirShapedTypeIsDynamicStrideOrOffset(), mlirShapedTypeIsStaticDim(), mlirShapedTypeIsStaticSize(), mlirShapedTypeIsStaticStrideOrOffset(), and mlir::python::PyType::PyType().
Member Data Documentation
isaFunction
const mlir::PyShapedType::IsAFunctionTy mlir::PyShapedType::isaFunction static
Initial value:
=
    mlirTypeIsAShaped
Definition at line 19 of file IRTypes.h.
pyClassName
const char* mlir::PyShapedType::pyClassName = "ShapedType" static constexpr
Definition at line 20 of file IRTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRTypes.h
lib/Bindings/Python/IRTypes.cpp