MLIR: mlir::detail::AsmParserImpl< BaseT > Class Template Reference
mlir::detail::AsmParserImpl< BaseT > Class Template Reference
This class provides the implementation of the generic parser methods within AsmParser.
#include "AsmParser/AsmParserImpl.h"
Public Types
using Delimiter = AsmParser::Delimiter
Public Member Functions
AsmParserImpl (SMLoc nameLoc, Parser &parser)
~AsmParserImpl () override=default
SMLoc getNameLoc () const override
Return the location of the original name token.
bool didEmitError () const
Return if any errors were emitted during parsing.
InFlightDiagnostic emitError (SMLoc loc, const Twine &message) override
Emit a diagnostic at the specified location and return failure.
Builder & getBuilder () const override
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
SMLoc getCurrentLocation () override
Get the location of the next token and store it into the argument.
Location getEncodedSourceLoc (SMLoc loc) override
Re-encode the given source location as an MLIR location and return it.
ParseResult parseArrow () override
Parse a -> token.
ParseResult parseOptionalArrow () override
Parses a -> if present.
ParseResult parseLBrace () override
Parse a '{' token.
ParseResult parseOptionalLBrace () override
Parse a '{' token if present.
ParseResult parseRBrace () override
Parse a } token.
ParseResult parseOptionalRBrace () override
Parse a } token if present.
ParseResult parseColon () override
Parse a : token.
ParseResult parseOptionalColon () override
Parse a : token if present.
ParseResult parseComma () override
Parse a , token.
ParseResult parseOptionalComma () override
Parse a , token if present.
ParseResult parseEllipsis () override
Parses a ....
ParseResult parseOptionalEllipsis () override
Parses a ... if present.
ParseResult parseEqual () override
Parse a = token.
ParseResult parseOptionalEqual () override
Parse a = token if present.
ParseResult parseLess () override
Parse a '<' token.
ParseResult parseOptionalLess () override
Parse a < token if present.
ParseResult parseGreater () override
Parse a '>' token.
ParseResult parseOptionalGreater () override
Parse a > token if present.
ParseResult parseLParen () override
Parse a (token.
ParseResult parseOptionalLParen () override
Parses a '(' if present.
ParseResult parseRParen () override
Parse a) token.
ParseResult parseOptionalRParen () override
Parses a ')' if present.
ParseResult parseLSquare () override
Parse a [ token.
ParseResult parseOptionalLSquare () override
Parses a '[' if present.
ParseResult parseRSquare () override
Parse a ] token.
ParseResult parseOptionalRSquare () override
Parses a ']' if present.
ParseResult parseQuestion () override
Parses a '?' token.
ParseResult parseOptionalQuestion () override
Parses a '?' if present.
ParseResult parseSlash () override
Parses a '/' token.
ParseResult parseOptionalSlash () override
Parses a '/' if present.
ParseResult parseStar () override
Parses a '*' token.
ParseResult parseOptionalStar () override
Parses a '*' if present.
ParseResult parsePlus () override
Parses a '+' token.
ParseResult parseOptionalPlus () override
Parses a '+' token if present.
ParseResult parseMinus () override
Parses a '-' token.
ParseResult parseOptionalMinus () override
Parses a '-' token if present.
ParseResult parseVerticalBar () override
Parse a '|' token.
ParseResult parseOptionalVerticalBar () override
Parse a '|' token if present.
ParseResult parseOptionalString (std::string *string) override
Parses a quoted string token if present.
ParseResult parseBase64Bytes (std::vector< char > *bytes) override
Parses a Base64 encoded string of bytes.
ParseResult parseFloat (const llvm::fltSemantics &semantics, APFloat &result) override
Parse a floating point value with given semantics from the stream.
ParseResult parseFloat (double &result) override
Parse a floating point value from the stream.
OptionalParseResult parseOptionalInteger (APInt &result) override
Parse an optional integer value from the stream.
OptionalParseResult parseOptionalDecimalInteger (APInt &result) override
Parse an optional integer value from the stream.
ParseResult parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElt, StringRef contextMessage) override
Parse a list of comma-separated items with an optional delimiter.
ParseResult parseKeyword (StringRef keyword, const Twine &msg) override
ParseResult parseOptionalKeyword (StringRef keyword) override
Parse the given keyword if present.
ParseResult parseOptionalKeyword (StringRef *keyword) override
Parse a keyword, if present, into 'keyword'.
ParseResult parseOptionalKeyword (StringRef *keyword, ArrayRef< StringRef > allowedKeywords) override
Parse a keyword if it is one of the 'allowedKeywords'.
ParseResult parseOptionalKeywordOrString (std::string *result) override
Parse an optional keyword or string and set instance into 'result'.`.
ParseResult parseAttribute (Attribute &result, Type type) override
Parse an arbitrary attribute and return it in result.
ParseResult parseCustomAttributeWithFallback (Attribute &result, Type type, function_ref< ParseResult(Attribute &result, Type type)> parseAttribute) override
Parse a custom attribute with the provided callback, unless the next token is #, in which case the generic parser is invoked.
ParseResult parseCustomTypeWithFallback (Type &result, function_ref< ParseResult(Type &result)> parseType) override
Parse a custom attribute with the provided callback, unless the next token is #, in which case the generic parser is invoked.
OptionalParseResult parseOptionalAttribute (Attribute &result, Type type) override
OptionalParseResult parseOptionalAttribute (ArrayAttr &result, Type type) override
OptionalParseResult parseOptionalAttribute (StringAttr &result, Type type) override
OptionalParseResult parseOptionalAttribute (SymbolRefAttr &result, Type type) override
ParseResult parseOptionalAttrDict (NamedAttrList &result) override
Parse a named dictionary into 'result' if it is present.
ParseResult parseOptionalAttrDictWithKeyword (NamedAttrList &result) override
Parse a named dictionary into 'result' if the attributes keyword is present.
ParseResult parseAffineMap (AffineMap &map) override
Parse an affine map instance into 'map'.
ParseResult parseAffineExpr (ArrayRef< std::pair< StringRef, AffineExpr >> symbolSet, AffineExpr &expr) override
Parse an affine expr instance into 'expr' using the already computed mapping from symbols to affine expressions in 'symbolSet'.
ParseResult parseIntegerSet (IntegerSet &set) override
Parse an integer set instance into 'set'.
ParseResult parseOptionalSymbolName (StringAttr &result) override
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
FailureOr< AsmDialectResourceHandle > parseResourceHandle (Dialect *dialect) override
Parse a handle to a resource within the assembly format.
ParseResult parseType (Type &result) override
Parse a type.
OptionalParseResult parseOptionalType (Type &result) override
Parse an optional type.
ParseResult parseArrowTypeList (SmallVectorImpl< Type > &result) override
Parse an arrow followed by a type list.
ParseResult parseOptionalArrowTypeList (SmallVectorImpl< Type > &result) override
Parse an optional arrow followed by a type list.
ParseResult parseColonType (Type &result) override
Parse a colon followed by a type.
ParseResult parseColonTypeList (SmallVectorImpl< Type > &result) override
Parse a colon followed by a type list, which must have at least one type.
ParseResult parseOptionalColonTypeList (SmallVectorImpl< Type > &result) override
Parse an optional colon followed by a type list, which if present must have at least one type.
ParseResult parseDimensionList (SmallVectorImpl< int64_t > &dimensions, bool allowDynamic, bool withTrailingX) override
ParseResult parseXInDimensionList () override
LogicalResult pushCyclicParsing (const void *opaquePointer) override
void popCyclicParsing () override
ParseResult parseKeywordOrCompletion (StringRef *keyword) override
Parse a keyword, or an empty string if the current location signals a code completion.
void codeCompleteExpectedTokens (ArrayRef< StringRef > tokens) override
Signal the code completion of a set of expected tokens.
ParseResult parseKeyword (StringRef keyword)
Parse a given keyword.
virtual ParseResult parseKeyword (StringRef keyword, const Twine &msg)=0
ParseResult parseKeyword (StringRef *keyword)
Parse a keyword into 'keyword'.
Protected Attributes
SMLoc nameLoc
The source location of the dialect symbol.
Parser & parser
The main parser.
bool emittedError = false
A flag that indicates if any errors were emitted during parsing.
Detailed Description
template<typename BaseT>
class mlir::detail::AsmParserImpl< BaseT >
This class provides the implementation of the generic parser methods within AsmParser.
Definition at line 28 of file AsmParserImpl.h.
Member Typedef Documentation
Delimiter
template<typename BaseT > using mlir::detail::AsmParserImpl< BaseT >::Delimiter = AsmParser::Delimiter
Definition at line 67 of file AsmParserImpl.h.
Constructor & Destructor Documentation
AsmParserImpl()
template<typename BaseT > mlir::detail::AsmParserImpl< BaseT >::AsmParserImpl (SMLoc nameLoc, Parser & parser) inline
Definition at line 30 of file AsmParserImpl.h.
~AsmParserImpl()
template<typename BaseT > mlir::detail::AsmParserImpl< BaseT >::~AsmParserImpl () override default
Member Function Documentation
codeCompleteExpectedTokens()
template<typename BaseT > void mlir::detail::AsmParserImpl< BaseT >::codeCompleteExpectedTokens (ArrayRef< StringRef > tokens) inline override
Signal the code completion of a set of expected tokens.
Definition at line 599 of file AsmParserImpl.h.
References mlir::detail::Parser::codeCompleteExpectedTokens(), mlir::Token::getSpelling(), mlir::detail::Parser::getToken(), mlir::Token::isCodeCompletion(), and mlir::detail::AsmParserImpl< BaseT >::parser.
didEmitError()
template<typename BaseT > bool mlir::detail::AsmParserImpl< BaseT >::didEmitError () const inline
Return if any errors were emitted during parsing.
Definition at line 42 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::emittedError.
emitError()
template<typename BaseT > InFlightDiagnostic mlir::detail::AsmParserImpl< BaseT >::emitError (SMLoc loc, const Twine & message) inline override
Emit a diagnostic at the specified location and return failure.
Definition at line 45 of file AsmParserImpl.h.
References mlir::detail::Parser::emitError(), mlir::detail::AsmParserImpl< BaseT >::emittedError, and mlir::detail::AsmParserImpl< BaseT >::parser.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseBase64Bytes(), and mlir::detail::AsmParserImpl< BaseT >::parseKeyword().
getBuilder()
template<typename BaseT > Builder& mlir::detail::AsmParserImpl< BaseT >::getBuilder () const inline override
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
Definition at line 52 of file AsmParserImpl.h.
References mlir::detail::Parser::builder, and mlir::detail::AsmParserImpl< BaseT >::parser.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseOptionalSymbolName().
getCurrentLocation()
template<typename BaseT > SMLoc mlir::detail::AsmParserImpl< BaseT >::getCurrentLocation () inline override
Get the location of the next token and store it into the argument.
This always succeeds.
Definition at line 56 of file AsmParserImpl.h.
References mlir::Token::getLoc(), mlir::detail::Parser::getToken(), and mlir::detail::AsmParserImpl< BaseT >::parser.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseBase64Bytes(), and mlir::detail::AsmParserImpl< BaseT >::parseKeyword().
getEncodedSourceLoc()
template<typename BaseT > Location mlir::detail::AsmParserImpl< BaseT >::getEncodedSourceLoc (SMLoc loc) inline override
Re-encode the given source location as an MLIR location and return it.
Definition at line 59 of file AsmParserImpl.h.
References mlir::detail::Parser::getEncodedSourceLocation(), and mlir::detail::AsmParserImpl< BaseT >::parser.
getNameLoc()
template<typename BaseT > SMLoc mlir::detail::AsmParserImpl< BaseT >::getNameLoc () const inline override
Return the location of the original name token.
Definition at line 35 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::nameLoc.
parseAffineExpr()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseAffineExpr (ArrayRef< std::pair< StringRef, AffineExpr >> symbolSet, AffineExpr & expr) inline override
Parse an affine expr instance into 'expr' using the already computed mapping from symbols to affine expressions in 'symbolSet'.
Definition at line 464 of file AsmParserImpl.h.
References mlir::detail::Parser::parseAffineExprReference(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseAffineMap()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseAffineMap (AffineMap & map) inline override
Parse an affine map instance into 'map'.
Definition at line 457 of file AsmParserImpl.h.
References mlir::detail::Parser::parseAffineMapReference(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseArrow()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseArrow () inline override
Parse a -> token.
Definition at line 70 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseArrowTypeList().
parseArrowTypeList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseArrowTypeList (SmallVectorImpl< Type > & result) inline override
Parse an arrow followed by a type list.
Definition at line 528 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parseArrow(), mlir::detail::Parser::parseFunctionResultTypes(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseAttribute()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseAttribute (Attribute & result, Type type) inline override
Parse an arbitrary attribute and return it in result.
Definition at line 396 of file AsmParserImpl.h.
References mlir::detail::Parser::parseAttribute(), and mlir::detail::AsmParserImpl< BaseT >::parser.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseCustomAttributeWithFallback().
parseBase64Bytes()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseBase64Bytes (std::vector< char > * bytes) inline override
Parses a Base64 encoded string of bytes.
Definition at line 265 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeToken(), mlir::detail::AsmParserImpl< BaseT >::emitError(), mlir::detail::AsmParserImpl< BaseT >::getCurrentLocation(), mlir::detail::Parser::getToken(), mlir::detail::Parser::getTokenSpelling(), mlir::Token::is(), mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::toString().
parseColon()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseColon () inline override
Parse a : token.
Definition at line 100 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseColonType()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseColonType (Type & result) inline override
Parse a colon followed by a type.
Definition at line 543 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, mlir::detail::Parser::parseToken(), and mlir::detail::Parser::parseType().
parseColonTypeList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseColonTypeList (SmallVectorImpl< Type > & result) inline override
Parse a colon followed by a type list, which must have at least one type.
Definition at line 549 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, mlir::detail::Parser::parseToken(), and mlir::detail::Parser::parseTypeListNoParens().
parseComma()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseComma () inline override
Parse a , token.
Definition at line 110 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseCommaSeparatedList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElt, StringRef contextMessage) inline override
Parse a list of comma-separated items with an optional delimiter.
If a delimiter is provided, then an empty list is allowed. If not, then at least one element will be parsed.
Definition at line 326 of file AsmParserImpl.h.
References mlir::detail::Parser::parseCommaSeparatedList(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseCustomAttributeWithFallback()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseCustomAttributeWithFallback (Attribute & result, Type type, function_ref< ParseResult(Attribute &result, Type type)> parseAttribute) inline override
Parse a custom attribute with the provided callback, unless the next token is #, in which case the generic parser is invoked.
Definition at line 403 of file AsmParserImpl.h.
References mlir::detail::Parser::getToken(), mlir::Token::isNot(), mlir::detail::AsmParserImpl< BaseT >::parseAttribute(), mlir::detail::Parser::parseAttribute(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseCustomTypeWithFallback()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseCustomTypeWithFallback (Type & result, function_ref< ParseResult(Type &result)> parseType) inline override
Parse a custom attribute with the provided callback, unless the next token is #, in which case the generic parser is invoked.
Definition at line 415 of file AsmParserImpl.h.
References mlir::detail::Parser::getToken(), mlir::Token::isNot(), mlir::detail::AsmParserImpl< BaseT >::parser, mlir::detail::Parser::parseType(), and mlir::detail::AsmParserImpl< BaseT >::parseType().
parseDimensionList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseDimensionList (SmallVectorImpl< int64_t > & dimensions, bool allowDynamic, bool withTrailingX) inline override
Definition at line 564 of file AsmParserImpl.h.
References mlir::detail::Parser::parseDimensionListRanked(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseEllipsis()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseEllipsis () inline override
Parses a ....
Definition at line 120 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseEqual()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseEqual () inline override
Parse a = token.
Definition at line 130 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseFloat() [1/2]
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseFloat (const llvm::fltSemantics & semantics, APFloat & result) inline override
Parse a floating point value with given semantics from the stream.
Since this implementation parses the string as double precision and only afterwards converts the value to the requested semantic, precision may be lost.
Definition at line 290 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), mlir::detail::Parser::consumeToken(), mlir::detail::Parser::getToken(), mlir::detail::Parser::parseFloatFromLiteral(), and mlir::detail::AsmParserImpl< BaseT >::parser.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseFloat().
parseFloat() [2/2]
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseFloat (double & result) inline override
Parse a floating point value from the stream.
Definition at line 304 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parseFloat().
parseGreater()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseGreater () inline override
Parse a '>' token.
Definition at line 150 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseIntegerSet()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseIntegerSet (IntegerSet & set) inline override
Parse an integer set instance into 'set'.
Definition at line 470 of file AsmParserImpl.h.
References mlir::detail::Parser::parseIntegerSetReference(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseKeyword() [1/4]
template<typename BaseT > ParseResult mlir::AsmParser::parseKeyword inline
Parse a keyword into 'keyword'.
Definition at line 932 of file OpImplementation.h.
parseKeyword() [2/4]
template<typename BaseT > ParseResult mlir::AsmParser::parseKeyword inline
Parse a given keyword.
Definition at line 926 of file OpImplementation.h.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseKeywordOrCompletion().
parseKeyword() [3/4]
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseKeyword (StringRef keyword, const Twine & msg) inline override
Definition at line 336 of file AsmParserImpl.h.
References mlir::detail::Parser::codeCompleteExpectedTokens(), mlir::detail::AsmParserImpl< BaseT >::emitError(), mlir::detail::AsmParserImpl< BaseT >::getCurrentLocation(), mlir::detail::Parser::getToken(), mlir::Token::isCodeCompletion(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseKeyword() [4/4]
template<typename BaseT > virtual ParseResult mlir::AsmParser::parseKeyword
parseKeywordOrCompletion()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseKeywordOrCompletion (StringRef * keyword) inline override
Parse a keyword, or an empty string if the current location signals a code completion.
Definition at line 589 of file AsmParserImpl.h.
References mlir::Token::getSpelling(), mlir::detail::Parser::getToken(), mlir::Token::isCodeCompletion(), mlir::detail::AsmParserImpl< BaseT >::parseKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseLBrace()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseLBrace () inline override
Parse a '{' token.
Definition at line 80 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseLess()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseLess () inline override
Parse a '<' token.
Definition at line 140 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseLParen()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseLParen () inline override
Parse a (token.
Definition at line 160 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseLSquare()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseLSquare () inline override
Parse a [ token.
Definition at line 180 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseMinus()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseMinus () inline override
Parses a '-' token.
Definition at line 240 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseOptionalArrow()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalArrow () inline override
Parses a -> if present.
Definition at line 75 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalArrowTypeList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalArrowTypeList (SmallVectorImpl< Type > & result) inline override
Parse an optional arrow followed by a type list.
Definition at line 536 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), mlir::detail::Parser::parseFunctionResultTypes(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalAttrDict()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDict (NamedAttrList & result) inline override
Parse a named dictionary into 'result' if it is present.
Definition at line 442 of file AsmParserImpl.h.
References mlir::detail::Parser::getToken(), mlir::Token::isNot(), mlir::detail::Parser::parseAttributeDict(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalAttrDictWithKeyword()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDictWithKeyword (NamedAttrList & result) inline override
Parse a named dictionary into 'result' if the attributes keyword is present.
Definition at line 450 of file AsmParserImpl.h.
References mlir::detail::Parser::parseAttributeDict(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalAttribute() [1/4]
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttribute (ArrayAttr & result, Type type) inline override
Definition at line 428 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalAttribute(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalAttribute() [2/4]
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttribute (Attribute & result, Type type) inline override
Definition at line 424 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalAttribute(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalAttribute() [3/4]
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttribute (StringAttr & result, Type type) inline override
Definition at line 432 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalAttribute(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalAttribute() [4/4]
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttribute (SymbolRefAttr & result, Type type) inline override
Definition at line 436 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalAttribute(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalColon()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalColon () inline override
Parse a : token if present.
Definition at line 105 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalColonTypeList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalColonTypeList (SmallVectorImpl< Type > & result) inline override
Parse an optional colon followed by a type list, which if present must have at least one type.
Definition at line 558 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseTypeListNoParens().
parseOptionalComma()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalComma () inline override
Parse a , token if present.
Definition at line 115 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalDecimalInteger()
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalDecimalInteger (APInt & result) inline override
Parse an optional integer value from the stream.
Definition at line 319 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalDecimalInteger(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalEllipsis()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalEllipsis () inline override
Parses a ... if present.
Definition at line 125 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalEqual()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalEqual () inline override
Parse a = token if present.
Definition at line 135 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalGreater()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalGreater () inline override
Parse a > token if present.
Definition at line 155 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalInteger()
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalInteger (APInt & result) inline override
Parse an optional integer value from the stream.
Definition at line 314 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalInteger(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalKeyword() [1/3]
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword (StringRef * keyword) inline override
Parse a keyword, if present, into 'keyword'.
Definition at line 361 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalKeyword() [2/3]
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword (StringRef * keyword, ArrayRef< StringRef > allowedKeywords) inline override
Parse a keyword if it is one of the 'allowedKeywords'.
Definition at line 367 of file AsmParserImpl.h.
References mlir::detail::Parser::codeCompleteOptionalTokens(), mlir::detail::Parser::consumeToken(), mlir::detail::Parser::getToken(), mlir::detail::Parser::getTokenSpelling(), mlir::Token::isCodeCompletion(), mlir::detail::Parser::isCurrentTokenAKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalKeyword() [3/3]
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword (StringRef keyword) inline override
Parse the given keyword if present.
Definition at line 348 of file AsmParserImpl.h.
References mlir::detail::Parser::codeCompleteOptionalTokens(), mlir::detail::Parser::consumeToken(), mlir::detail::Parser::getToken(), mlir::detail::Parser::getTokenSpelling(), mlir::Token::isCodeCompletion(), mlir::detail::Parser::isCurrentTokenAKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parser.
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseKeyword(), and mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDictWithKeyword().
parseOptionalKeywordOrString()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeywordOrString (std::string * result) inline override
Parse an optional keyword or string and set instance into 'result'.`.
Definition at line 387 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalKeywordOrString(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalLBrace()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalLBrace () inline override
Parse a '{' token if present.
Definition at line 85 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalLess()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalLess () inline override
Parse a < token if present.
Definition at line 145 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalLParen()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalLParen () inline override
Parses a '(' if present.
Definition at line 165 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalLSquare()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalLSquare () inline override
Parses a '[' if present.
Definition at line 185 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalMinus()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalMinus () inline override
Parses a '-' token if present.
Definition at line 245 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalPlus()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalPlus () inline override
Parses a '+' token if present.
Definition at line 235 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalQuestion()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalQuestion () inline override
Parses a '?' if present.
Definition at line 205 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalRBrace()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalRBrace () inline override
Parse a } token if present.
Definition at line 95 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalRParen()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalRParen () inline override
Parses a ')' if present.
Definition at line 175 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalRSquare()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalRSquare () inline override
Parses a ']' if present.
Definition at line 195 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalSlash()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalSlash () inline override
Parses a '/' if present.
Definition at line 215 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalStar()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalStar () inline override
Parses a '*' if present.
Definition at line 225 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalString()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalString (std::string * string) inline override
Parses a quoted string token if present.
Definition at line 260 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalString(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalSymbolName()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalSymbolName (StringAttr & result) inline override
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Definition at line 480 of file AsmParserImpl.h.
References mlir::AsmParserState::addUses(), mlir::detail::ParserState::asmState, mlir::detail::Parser::consumeToken(), mlir::get(), mlir::detail::AsmParserImpl< BaseT >::getBuilder(), mlir::Token::getLocRange(), mlir::detail::Parser::getState(), mlir::Builder::getStringAttr(), mlir::Token::getSymbolReference(), mlir::detail::Parser::getToken(), mlir::Token::isNot(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalType()
template<typename BaseT > OptionalParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalType (Type & result) inline override
Parse an optional type.
Definition at line 523 of file AsmParserImpl.h.
References mlir::detail::Parser::parseOptionalType(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parseOptionalVerticalBar()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseOptionalVerticalBar () inline override
Parse a '|' token if present.
Definition at line 255 of file AsmParserImpl.h.
References mlir::detail::Parser::consumeIf(), and mlir::detail::AsmParserImpl< BaseT >::parser.
parsePlus()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parsePlus () inline override
Parses a '+' token.
Definition at line 230 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseQuestion()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseQuestion () inline override
Parses a '?' token.
Definition at line 200 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseRBrace()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseRBrace () inline override
Parse a } token.
Definition at line 90 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseResourceHandle()
template<typename BaseT > FailureOr<AsmDialectResourceHandle> mlir::detail::AsmParserImpl< BaseT >::parseResourceHandle (Dialect * dialect) inline override
Parse a handle to a resource within the assembly format.
Definition at line 503 of file AsmParserImpl.h.
References mlir::detail::Parser::emitError(), mlir::Dialect::getNamespace(), mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseResourceHandle().
parseRParen()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseRParen () inline override
Parse a) token.
Definition at line 170 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseRSquare()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseRSquare () inline override
Parse a ] token.
Definition at line 190 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseSlash()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseSlash () inline override
Parses a '/' token.
Definition at line 210 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseStar()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseStar () inline override
Parses a '*' token.
Definition at line 220 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseType()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseType (Type & result) inline override
Parse a type.
Definition at line 518 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseType().
Referenced by mlir::detail::AsmParserImpl< BaseT >::parseCustomTypeWithFallback().
parseVerticalBar()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseVerticalBar () inline override
Parse a '|' token.
Definition at line 250 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseToken().
parseXInDimensionList()
template<typename BaseT > ParseResult mlir::detail::AsmParserImpl< BaseT >::parseXInDimensionList () inline override
Definition at line 571 of file AsmParserImpl.h.
References mlir::detail::AsmParserImpl< BaseT >::parser, and mlir::detail::Parser::parseXInDimensionList().
popCyclicParsing()
template<typename BaseT > void mlir::detail::AsmParserImpl< BaseT >::popCyclicParsing () inline override
Definition at line 579 of file AsmParserImpl.h.
References mlir::detail::ParserState::cyclicParsingStack, mlir::detail::Parser::getState(), and mlir::detail::AsmParserImpl< BaseT >::parser.
pushCyclicParsing()
template<typename BaseT > LogicalResult mlir::detail::AsmParserImpl< BaseT >::pushCyclicParsing (const void * opaquePointer) inline override
Definition at line 575 of file AsmParserImpl.h.
References mlir::detail::ParserState::cyclicParsingStack, mlir::detail::Parser::getState(), and mlir::detail::AsmParserImpl< BaseT >::parser.
Member Data Documentation
emittedError
template<typename BaseT > bool mlir::detail::AsmParserImpl< BaseT >::emittedError = false protected
A flag that indicates if any errors were emitted during parsing.
Definition at line 613 of file AsmParserImpl.h.
Referenced by mlir::detail::AsmParserImpl< BaseT >::didEmitError(), and mlir::detail::AsmParserImpl< BaseT >::emitError().
nameLoc
template<typename BaseT > SMLoc mlir::detail::AsmParserImpl< BaseT >::nameLoc protected
The source location of the dialect symbol.
Definition at line 607 of file AsmParserImpl.h.
Referenced by mlir::detail::AsmParserImpl< BaseT >::getNameLoc().
parser
template<typename BaseT > Parser& mlir::detail::AsmParserImpl< BaseT >::parser protected
The main parser.
Definition at line 610 of file AsmParserImpl.h.
Referenced by mlir::detail::AsmParserImpl< BaseT >::codeCompleteExpectedTokens(), mlir::detail::AsmParserImpl< BaseT >::emitError(), mlir::detail::AsmParserImpl< BaseT >::getBuilder(), mlir::detail::AsmParserImpl< BaseT >::getCurrentLocation(), mlir::detail::AsmParserImpl< BaseT >::getEncodedSourceLoc(), mlir::detail::AsmParserImpl< BaseT >::parseAffineExpr(), mlir::detail::AsmParserImpl< BaseT >::parseAffineMap(), mlir::detail::AsmParserImpl< BaseT >::parseArrow(), mlir::detail::AsmParserImpl< BaseT >::parseArrowTypeList(), mlir::detail::AsmParserImpl< BaseT >::parseAttribute(), mlir::detail::AsmParserImpl< BaseT >::parseBase64Bytes(), mlir::detail::AsmParserImpl< BaseT >::parseColon(), mlir::detail::AsmParserImpl< BaseT >::parseColonType(), mlir::detail::AsmParserImpl< BaseT >::parseColonTypeList(), mlir::detail::AsmParserImpl< BaseT >::parseComma(), mlir::detail::AsmParserImpl< BaseT >::parseCommaSeparatedList(), mlir::detail::AsmParserImpl< BaseT >::parseCustomAttributeWithFallback(), mlir::detail::AsmParserImpl< BaseT >::parseCustomTypeWithFallback(), mlir::detail::AsmParserImpl< BaseT >::parseDimensionList(), mlir::detail::AsmParserImpl< BaseT >::parseEllipsis(), mlir::detail::AsmParserImpl< BaseT >::parseEqual(), mlir::detail::AsmParserImpl< BaseT >::parseFloat(), mlir::detail::AsmParserImpl< BaseT >::parseGreater(), mlir::detail::AsmParserImpl< BaseT >::parseIntegerSet(), mlir::detail::AsmParserImpl< BaseT >::parseKeyword(), mlir::detail::AsmParserImpl< BaseT >::parseKeywordOrCompletion(), mlir::detail::AsmParserImpl< BaseT >::parseLBrace(), mlir::detail::AsmParserImpl< BaseT >::parseLess(), mlir::detail::AsmParserImpl< BaseT >::parseLParen(), mlir::detail::AsmParserImpl< BaseT >::parseLSquare(), mlir::detail::AsmParserImpl< BaseT >::parseMinus(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalArrow(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalArrowTypeList(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDict(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDictWithKeyword(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttribute(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalColon(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalColonTypeList(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalComma(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalDecimalInteger(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalEllipsis(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalEqual(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalGreater(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalInteger(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeyword(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalKeywordOrString(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLBrace(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLess(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLParen(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalLSquare(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalMinus(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalPlus(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalQuestion(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalRBrace(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalRParen(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalRSquare(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalSlash(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalStar(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalString(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalSymbolName(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalType(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalVerticalBar(), mlir::detail::AsmParserImpl< BaseT >::parsePlus(), mlir::detail::AsmParserImpl< BaseT >::parseQuestion(), mlir::detail::AsmParserImpl< BaseT >::parseRBrace(), mlir::detail::AsmParserImpl< BaseT >::parseResourceHandle(), mlir::detail::AsmParserImpl< BaseT >::parseRParen(), mlir::detail::AsmParserImpl< BaseT >::parseRSquare(), mlir::detail::AsmParserImpl< BaseT >::parseSlash(), mlir::detail::AsmParserImpl< BaseT >::parseStar(), mlir::detail::AsmParserImpl< BaseT >::parseType(), mlir::detail::AsmParserImpl< BaseT >::parseVerticalBar(), mlir::detail::AsmParserImpl< BaseT >::parseXInDimensionList(), mlir::detail::AsmParserImpl< BaseT >::popCyclicParsing(), and mlir::detail::AsmParserImpl< BaseT >::pushCyclicParsing().
The documentation for this class was generated from the following file:
lib/AsmParser/AsmParserImpl.h