MLIR: mlir::raw_indented_ostream Class Reference
mlir::raw_indented_ostream Class Reference
raw_ostream subclass that simplifies indention a sequence of code.
#include "mlir/Support/IndentedOstream.h"
Classes
struct DelimitedScope
Simple RAII struct to use to indentation around entering/exiting region.
Public Member Functions
raw_indented_ostream (llvm::raw_ostream &os)
raw_ostream & getOStream () const
Returns the underlying (unindented) raw_ostream.
DelimitedScope scope (StringRef open="", StringRef close="", bool indent=true)
Returns DelimitedScope.
raw_indented_ostream & printReindented (StringRef str, StringRef extraPrefix="")
Prints a string re-indented to the current indent.
raw_indented_ostream & indent ()
Increases the indent and returning this raw_indented_ostream.
raw_indented_ostream & unindent ()
Decreases the indent and returning this raw_indented_ostream.
raw_indented_ostream & indent (int with)
Emits whitespace and sets the indentation for the stream.
Detailed Description
raw_ostream subclass that simplifies indention a sequence of code.
Definition at line 23 of file IndentedOstream.h.
Constructor & Destructor Documentation
raw_indented_ostream()
mlir::raw_indented_ostream::raw_indented_ostream (llvm::raw_ostream & os) inline explicit
Definition at line 25 of file IndentedOstream.h.
Referenced by mlir::raw_indented_ostream::DelimitedScope::DelimitedScope(), indent(), indent(), and unindent().
Member Function Documentation
getOStream()
raw_ostream & mlir::raw_indented_ostream::getOStream () const inline
Returns the underlying (unindented) raw_ostream.
Definition at line 52 of file IndentedOstream.h.
indent() [1/2]
raw_indented_ostream & mlir::raw_indented_ostream::indent () inline
Increases the indent and returning this raw_indented_ostream.
Definition at line 68 of file IndentedOstream.h.
References raw_indented_ostream().
Referenced by indent(), printAsTextualPipeline(), printFunctionBody(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printReindented(), and scope().
indent() [2/2]
raw_indented_ostream & mlir::raw_indented_ostream::indent (int with) inline
Emits whitespace and sets the indentation for the stream.
Definition at line 80 of file IndentedOstream.h.
References indent(), and raw_indented_ostream().
printReindented()
raw_indented_ostream & mlir::raw_indented_ostream::printReindented (StringRef str, StringRef extraPrefix = "") inline
Prints a string re-indented to the current indent.
Re-indents by removing the leading whitespace from the first non-empty line from every line of the string, skipping over empty lines at the start. Prefixes each line with extraPrefix after the indentation.
Definition at line 114 of file IndentedOstream.h.
References indent().
scope()
DelimitedScope mlir::raw_indented_ostream::scope (StringRef open = "", StringRef close = "", bool indent = true) inline
Returns DelimitedScope.
Definition at line 55 of file IndentedOstream.h.
References indent().
Referenced by mlir::tblgen::ParentClass::writeTo().
unindent()
raw_indented_ostream & mlir::raw_indented_ostream::unindent () inline
Decreases the indent and returning this raw_indented_ostream.
Definition at line 74 of file IndentedOstream.h.
References raw_indented_ostream().
Referenced by printAsTextualPipeline(), printFunctionBody(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), and printOperation().
The documentation for this class was generated from the following file:
include/mlir/Support/IndentedOstream.h