MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint Class Reference
Public Member Functions
PyIntegerSetConstraint (PyIntegerSet set, intptr_t pos)
PyAffineExpr getExpr ()
bool isEq ()
Static Public Member Functions
static void bind (nb::module_ &m)
Detailed Description
Definition at line 459 of file IRAffine.cpp.
Constructor & Destructor Documentation
PyIntegerSetConstraint()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint::PyIntegerSetConstraint (PyIntegerSet set, intptr_t pos) inline
Definition at line 461 of file IRAffine.cpp.
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint::bind (nb::module_ & m) inline static
Definition at line 471 of file IRAffine.cpp.
References getExpr(), and isEq().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine().
getExpr()
PyAffineExpr mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint::getExpr () inline
Definition at line 464 of file IRAffine.cpp.
References mlirIntegerSetGetConstraint().
Referenced by bind().
isEq()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint::isEq () inline
Definition at line 469 of file IRAffine.cpp.
References mlirIntegerSetIsConstraintEq().
Referenced by bind().
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRAffine.cpp