MLIR: mlir::tblgen::Pred Class Reference
mlir::tblgen::Pred Class Reference
#include "mlir/TableGen/Predicate.h"
Public Member Functions
Pred ()
Pred (const llvm::Record *record)
Pred (const llvm::Init *init)
bool isNull () const
std::string getCondition () const
bool isCombined () const
ArrayRef< SMLoc > getLoc () const
bool operator== (const Pred &other) const
operator bool () const
const llvm::Record & getDef () const
Return the underlying def.
Protected Attributes
const llvm::Record * def {nullptr}
Friends
llvm::hash_code hash_value (Pred pred)
Detailed Description
Definition at line 34 of file Predicate.h.
Constructor & Destructor Documentation
Pred() [1/3]
mlir::tblgen::Pred::Pred () inline explicit
Definition at line 37 of file Predicate.h.
Referenced by hash_value, and operator==().
Pred() [2/3]
mlir::tblgen::Pred::Pred (const llvm::Record * record) explicit
Pred() [3/3]
mlir::tblgen::Pred::Pred (const llvm::Init * init) explicit
Member Function Documentation
getCondition()
std::string Pred::getCondition () const
Definition at line 38 of file Predicate.cpp.
References def.
Referenced by buildPredicateTree(), and mlir::tblgen::Constraint::getConditionTemplate().
getDef()
const llvm::Record & mlir::tblgen::Pred::getDef () const inline
Return the underlying def.
Definition at line 71 of file Predicate.h.
References def.
getLoc()
ArrayRef< SMLoc > Pred::getLoc () const
Definition at line 51 of file Predicate.cpp.
References def.
Referenced by getCombinedCondition().
isCombined()
bool Pred::isCombined () const
Definition at line 47 of file Predicate.cpp.
References def.
Referenced by buildPredicateTree(), and getPredCombinerKind().
isNull()
bool mlir::tblgen::Pred::isNull () const inline
Definition at line 46 of file Predicate.h.
References def.
Referenced by mlir::tblgen::CPred::getConditionImpl().
operator bool()
mlir::tblgen::Pred::operator bool () const inline
Definition at line 63 of file Predicate.h.
References def.
operator==()
bool mlir::tblgen::Pred::operator== (const Pred & other) const inline
Definition at line 60 of file Predicate.h.
References def, and Pred().
Friends And Related Symbol Documentation
hash_value
llvm::hash_code hash_value (Pred pred) friend
Definition at line 66 of file Predicate.h.
References def, and Pred().
Member Data Documentation
def
const llvm::Record* mlir::tblgen::Pred::def {nullptr} protected
Definition at line 75 of file Predicate.h.
Referenced by mlir::tblgen::CombinedPred::getChildren(), mlir::tblgen::CombinedPred::getCombinerDef(), getCondition(), mlir::tblgen::CPred::getConditionImpl(), getDef(), getLoc(), mlir::tblgen::SubstLeavesPred::getPattern(), mlir::tblgen::ConcatPred::getPrefix(), mlir::tblgen::SubstLeavesPred::getReplacement(), mlir::tblgen::ConcatPred::getSuffix(), hash_value, isCombined(), isNull(), operator bool(), and operator==().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Predicate.h
lib/TableGen/Predicate.cpp