MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator Class Reference
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
PyArrayAttributeIterator (PyAttribute attr)
PyArrayAttributeIterator & dunderIter ()
nanobind::typed< nanobind::object, PyAttribute > dunderNext ()
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 300 of file IRAttributes.h.
Constructor & Destructor Documentation
PyArrayAttributeIterator()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::PyArrayAttributeIterator (PyAttribute attr) inline
Definition at line 302 of file IRAttributes.h.
Referenced by dunderIter().
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::bind (nanobind::module_ & m) static
Definition at line 270 of file IRAttributes.cpp.
References dunderIter(), and dunderNext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAttributes().
dunderIter()
PyArrayAttributeIterator & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::dunderIter () inline
Definition at line 304 of file IRAttributes.h.
References PyArrayAttributeIterator().
Referenced by bind().
dunderNext()
nb::typed< nb::object, PyAttribute > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::dunderNext ()
Definition at line 252 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::PyAttribute().
Referenced by bind().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRAttributes.h
lib/Bindings/Python/IRAttributes.cpp