MLIR: mlir::FlatLinearConstraints Class Reference
mlir::FlatLinearConstraints Class Reference
FlatLinearConstraints is an extension of IntegerPolyhedron.
#include "mlir/Analysis/FlatLinearValueConstraints.h"
Public Types
enum class AddConservativeSemiAffineBounds { No = 0 , Yes }
Flag to control if conservative semi-affine bounds should be added in addBound().
Public Types inherited from mlir::presburger::IntegerRelation
enum class Kind {
IntegerRelation , IntegerPolyhedron , FlatLinearConstraints , FlatLinearValueConstraints ,
FlatAffineValueConstraints , FlatAffineRelation
}
All derived classes of IntegerRelation.
Public Member Functions
FlatLinearConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and variables.
FlatLinearConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
FlatLinearConstraints (const IntegerPolyhedron &fac)
Kind getKind () const override
Return the kind of this object.
LogicalResult addBound (presburger::BoundType type, unsigned pos, AffineMap boundMap, bool isClosedBound, AddConservativeSemiAffineBounds=AddConservativeSemiAffineBounds::No)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map.
LogicalResult addBound (presburger::BoundType type, unsigned pos, AffineMap boundMap, AddConservativeSemiAffineBounds=AddConservativeSemiAffineBounds::No)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map.
std::optional< int64_t > getConstantBoundOnDimSize (MLIRContext *context, unsigned pos, AffineMap *lb=nullptr, AffineMap *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns a non-negative constant bound on the extent (upper bound - lower bound) of the specified variable if it is found to be a constant; returns std::nullopt if it's not a constant.
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps, bool closedUB=false)
Computes the lower and upper bounds of the first num dimensional variables (starting at offset) as an affine map of the remaining variables (dimensional and symbolic).
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatLinearConstraints.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context, bool closedUB=false) const
Gets the lower and upper bound of the offset + posth variable treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolVars) as symbols, and pos lies in [0, num).
unsigned insertDimVar (unsigned pos, unsigned num=1)
Insert variables of the specified kind at position pos.
unsigned insertSymbolVar (unsigned pos, unsigned num=1)
unsigned insertLocalVar (unsigned pos, unsigned num=1)
unsigned appendDimVar (unsigned num=1)
Append variables of the specified kind after the last variable of that kind.
unsigned appendSymbolVar (unsigned num=1)
unsigned appendLocalVar (unsigned num=1)
void dumpPretty () const
A more human-readable version of dump().
void dumpRow (ArrayRef< int64_t > row, bool fixedColWidth=true) const
An easier to read dump of a row of the same width as the number of columns.
Public Member Functions inherited from mlir::presburger::IntegerPolyhedron
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a set reserving memory for the specified number of constraints and variables.
IntegerPolyhedron (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
IntegerPolyhedron (const PresburgerSpace &space, const IntMatrix &inequalities)
Constructs a relation with the specified number of dimensions and symbols and adds the given inequalities.
IntegerPolyhedron (const PresburgerSpace &space, const FracMatrix &inequalities)
Constructs a relation with the specified number of dimensions and symbols and adds the given inequalities, after normalizing row-wise to integer values.
IntegerPolyhedron (const IntegerRelation &rel)
Construct a set from an IntegerRelation.
IntegerPolyhedron (IntegerRelation &&rel)
Construct a set from an IntegerRelation, but instead of creating a copy, use move constructor.
Kind getKind () const override
Return the kind of this IntegerRelation.
std::unique_ptr< IntegerPolyhedron > clone () const
unsigned insertVar (VarKind kind, unsigned pos, unsigned num=1) override
Insert num variables of the specified kind at position pos.
IntegerPolyhedron intersect (const IntegerPolyhedron &other) const
Return the intersection of the two relations.
PresburgerSet subtract (const PresburgerSet &other) const
Return the set difference of this set and the given set, i.e., return this \ set.
Public Member Functions inherited from mlir::presburger::IntegerRelation
IntegerRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a relation reserving memory for the specified number of constraints and variables.
IntegerRelation (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
virtual ~IntegerRelation ()=default
std::unique_ptr< IntegerRelation > clone () const
const PresburgerSpace & getSpace () const
Returns a reference to the underlying space.
void setSpace (const PresburgerSpace &oSpace)
Set the space to oSpace, which should have the same number of ids as the current space.
void setSpaceExceptLocals (const PresburgerSpace &oSpace)
Set the space to oSpace, which should not have any local ids.
void setId (VarKind kind, unsigned i, Identifier id)
Set the identifier for the ith variable of the specified kind of the IntegerRelation's PresburgerSpace.
void resetIds ()
ArrayRef< Identifier > getIds (VarKind kind)
Get the identifiers for the variables of specified varKind.
PresburgerSpace getSpaceWithoutLocals () const
Returns a copy of the space without locals.
void append (const IntegerRelation &other)
Appends constraints from other into this.
int findEqualityToConstant (unsigned pos, bool symbolic=false) const
Finds an equality that equates the specified variable to a constant.
IntegerRelation intersect (IntegerRelation other) const
Return the intersection of the two relations.
bool isEqual (const IntegerRelation &other) const
Return whether this and other are equal.
bool isObviouslyEqual (const IntegerRelation &other) const
Perform a quick equality check on this and other.
bool isSubsetOf (const IntegerRelation &other) const
Return whether this is a subset of the given IntegerRelation.
DynamicAPInt atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t atEq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
DynamicAPInt & atEq (unsigned i, unsigned j)
DynamicAPInt atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t atIneq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
DynamicAPInt & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
int64_t atConstraint64 (unsigned i, unsigned j) const
Unified indexing into the constraints.
DynamicAPInt & atConstraint (unsigned i, unsigned j)
unsigned getNumDomainVars () const
unsigned getNumRangeVars () const
unsigned getNumSymbolVars () const
unsigned getNumLocalVars () const
unsigned getNumDimVars () const
unsigned getNumDimAndSymbolVars () const
unsigned getNumVars () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< DynamicAPInt > getEquality (unsigned idx) const
ArrayRef< DynamicAPInt > getInequality (unsigned idx) const
SmallVector< int64_t, 8 > getEquality64 (unsigned idx) const
The same, but casts to int64_t.
SmallVector< int64_t, 8 > getInequality64 (unsigned idx) const
IntMatrix getInequalities () const
unsigned getNumVarKind (VarKind kind) const
Get the number of vars of the specified kind.
unsigned getVarKindOffset (VarKind kind) const
Return the index at which the specified kind of vars starts.
unsigned getVarKindEnd (VarKind kind) const
Return the index at Which the specified kind of vars ends.
auto iterVarKind (VarKind kind)
Return an interator over the variables of the specified kind starting at the relevant offset.
unsigned getVarKindOverlap (VarKind kind, unsigned varStart, unsigned varLimit) const
Get the number of elements of the specified kind in the range [varStart, varLimit).
VarKind getVarKindAt (unsigned pos) const
Return the VarKind of the var at the specified position.
CountsSnapshot getCounts () const
void truncate (const CountsSnapshot &counts)
unsigned appendVar (VarKind kind, unsigned num=1)
Append num variables of the specified kind after the last variable of that kind.
void addInequality (ArrayRef< DynamicAPInt > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addInequality (ArrayRef< int64_t > inEq)
void addEquality (ArrayRef< DynamicAPInt > eq)
Adds an equality from the coefficients specified in eq.
void addEquality (ArrayRef< int64_t > eq)
virtual void eliminateRedundantLocalVar (unsigned posA, unsigned posB)
Eliminate the posB^th local variable, replacing every instance of it with the posA^th local variable.
void removeVar (VarKind kind, unsigned pos)
Removes variables of the specified kind with the specified pos (or within the specified range) from the system.
virtual void removeVarRange (VarKind kind, unsigned varStart, unsigned varLimit)
void removeVar (unsigned pos)
Removes the specified variable from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeConstraint (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
MaybeOptimum< SmallVector< Fraction, 8 > > findRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
MaybeOptimum< SmallVector< DynamicAPInt, 8 > > findIntegerLexMin () const
Same as above, but returns lexicographically minimal integer point.
virtual void swapVar (unsigned posA, unsigned posB)
Swap the posA^th variable with the posB^th variable.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< DynamicAPInt > values)
Sets the values.size() variables starting at pos to the specified values and removes them.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
virtual void clearAndCopyFrom (const IntegerRelation &other)
Replaces the contents of this IntegerRelation with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the variable at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all variables, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isObviouslyEmpty () const
Performs GCD checks and invalid constraint checks.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
IntMatrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
std::optional< SmallVector< DynamicAPInt, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
std::optional< DynamicAPInt > computeVolume () const
Compute an overapproximation of the number of integer points in the relation.
bool containsPoint (ArrayRef< DynamicAPInt > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
bool containsPoint (ArrayRef< int64_t > point) const
std::optional< SmallVector< DynamicAPInt, 8 > > containsPointNoLocal (ArrayRef< DynamicAPInt > point) const
Given the values of non-local vars, return a satisfying assignment to the local if one exists, or an empty optional otherwise.
std::optional< SmallVector< DynamicAPInt, 8 > > containsPointNoLocal (ArrayRef< int64_t > point) const
DivisionRepr getLocalReprs (std::vector< MaybeLocalRepr > *repr=nullptr) const
Returns a DivisonRepr representing the division representation of local variables in the constraint system.
void addBound (BoundType type, unsigned pos, const DynamicAPInt &value)
Adds a constant bound for the specified variable.
void addBound (BoundType type, unsigned pos, int64_t value)
void addBound (BoundType type, ArrayRef< DynamicAPInt > expr, const DynamicAPInt &value)
Adds a constant bound for the specified expression.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
unsigned addLocalFloorDiv (ArrayRef< DynamicAPInt > dividend, const DynamicAPInt &divisor)
Adds a new local variable as the floordiv of an affine function of other variables, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
unsigned addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
unsigned addLocalModulo (ArrayRef< DynamicAPInt > exprs, const DynamicAPInt &modulus)
Adds a new local variable as the modulus of an affine function of other variables, the coefficients of which are provided in exprs.
unsigned addLocalModulo (ArrayRef< int64_t > exprs, int64_t modulus)
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num variables starting at position pos.
void projectOut (unsigned pos)
void pruneOrthogonalConstraints (unsigned pos)
The function removes some constraints that do not impose any bound on the specified variable.
LogicalResult constantFoldVar (unsigned pos)
Tries to fold the specified variable to a constant using a trivial equality detection; if successful, the constant is substituted for the variable everywhere in the constraint system and then removed from the system.
void constantFoldVarRange (unsigned pos, unsigned num)
This method calls constantFoldVar for the specified range of variables, num variables starting at position pos.
LogicalResult unionBoundingBox (const IntegerRelation &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
std::optional< DynamicAPInt > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< DynamicAPInt > *lb=nullptr, DynamicAPInt *boundFloorDivisor=nullptr, SmallVectorImpl< DynamicAPInt > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified variable (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the variable.
std::optional< int64_t > getConstantBoundOnDimSize64 (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
The same, but casts to int64_t.
std::optional< DynamicAPInt > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th variable if there is one; std::nullopt otherwise.
std::optional< int64_t > getConstantBound64 (BoundType type, unsigned pos) const
The same, but casts to int64_t.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) variables in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of variables.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void removeDuplicateDivs ()
void simplify ()
Simplify the constraint system by removing canonicalizing constraints and removing redundant constraints.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind, unsigned pos)
Converts variables of kind srcKind in the range [varStart, varLimit) to variables of kind dstKind.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind)
void convertToLocal (VarKind kind, unsigned varStart, unsigned varLimit)
void mergeAndAlignSymbols (IntegerRelation &other)
Merge and align symbol variables of this and other with respect to identifiers.
unsigned mergeLocalVars (IntegerRelation &other)
Adds additional local vars to the sets such that they both have the union of the local vars in each set, without changing the set of points that lie in this and other.
bool hasOnlyDivLocals () const
Check whether all local ids have a division representation.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
IntegerPolyhedron getDomainSet () const
Return a set corresponding to all points in the domain of the relation.
IntegerPolyhedron getRangeSet () const
Return a set corresponding to all points in the range of the relation.
void intersectDomain (const IntegerPolyhedron &poly)
Intersect the given poly with the domain in-place.
void intersectRange (const IntegerPolyhedron &poly)
Intersect the given poly with the range in-place.
void inverse ()
Invert the relation i.e., swap its domain and range.
void compose (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void applyDomain (const IntegerRelation &rel)
Given a relation rel, apply the relation to the domain of this relation.
void applyRange (const IntegerRelation &rel)
Given a relation rel, apply the relation to the range of this relation.
IntegerRelation rangeProduct (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void mergeAndCompose (const IntegerRelation &other)
Given a relation other: (A -> B), this operation merges the symbol and local variables and then takes the composition of other on this: (B -> / C).
PresburgerRelation computeReprWithOnlyDivLocals () const
Compute an equivalent representation of the same set, such that all local vars in all disjuncts have division representations.
SymbolicLexOpt findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the relation.
SymbolicLexOpt findSymbolicIntegerLexMax () const
Same as findSymbolicIntegerLexMin but produces lexmax instead of lexmin.
std::optional< unsigned > findConstraintWithNonZeroAt (unsigned colIdx, bool isEq) const
Finds a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
PresburgerRelation subtract (const PresburgerRelation &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
void removeTrivialEqualities ()
bool isFullDim ()
void print (raw_ostream &os) const
void dump () const
Protected Types
using VarKind = presburger::VarKind
Protected Member Functions
LogicalResult computeLocalVars (SmallVectorImpl< AffineExpr > &memo, MLIRContext *context) const
Compute an explicit representation for local vars.
LogicalResult flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 > > *flattenedExprs, bool addConservativeSemiAffineBounds=false)
Given an affine map that is aligned with this constraint system:
void printSpace (raw_ostream &os) const override
Prints the number of constraints, dimensions, symbols and locals in the FlatLinearConstraints.
Protected Member Functions inherited from mlir::presburger::IntegerRelation
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
std::optional< DynamicAPInt > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound if isLower is true, and the upper bound if isLower is false.
template<bool isLower>
std::optional< int64_t > computeConstantLowerOrUpperBound64 (unsigned pos)
The same, but casts to int64_t.
LogicalResult gaussianEliminateVar (unsigned position)
Eliminates a single variable at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateVars (unsigned posStart, unsigned posLimit)
Eliminates variables from equality and inequality constraints in column range [posStart, posLimit).
bool gaussianEliminate ()
Perform a Gaussian elimination operation to reduce all equations to standard form.
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the variable at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that variable.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
bool removeDuplicateConstraints ()
Checks for identical inequalities and eliminates redundant inequalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various variable counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
void removeVarRange (unsigned varStart, unsigned varLimit)
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
void truncateVarKind (VarKind kind, unsigned num)
Truncate the vars of the specified kind to the specified number by dropping some vars at the end.
void truncateVarKind (VarKind kind, const CountsSnapshot &counts)
Truncate the vars to the number in the space of the specified CountsSnapshot.
Additional Inherited Members
Static Public Member Functions inherited from mlir::presburger::IntegerPolyhedron
static IntegerPolyhedron getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerRelation *cst)
Static Public Member Functions inherited from mlir::presburger::IntegerRelation
static IntegerRelation getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static IntegerRelation getEmpty (const PresburgerSpace &space)
Return an empty system containing an invalid equation 0 = 1.
static bool classof (const IntegerRelation *cst)
Protected Attributes inherited from mlir::presburger::IntegerRelation
PresburgerSpace space
IntMatrix equalities
Coefficients of affine equalities (in == 0 form).
IntMatrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes inherited from mlir::presburger::IntegerRelation
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
FlatLinearConstraints is an extension of IntegerPolyhedron.
It provides an AffineExpr-based API.
Definition at line 33 of file FlatLinearValueConstraints.h.
Member Typedef Documentation
VarKind
using mlir::FlatLinearConstraints::VarKind = presburger::VarKind protected
Definition at line 230 of file FlatLinearValueConstraints.h.
Member Enumeration Documentation
AddConservativeSemiAffineBounds
enum class mlir::FlatLinearConstraints::AddConservativeSemiAffineBounds strong
Flag to control if conservative semi-affine bounds should be added in addBound().
Enumerator
No
Yes
Definition at line 70 of file FlatLinearValueConstraints.h.
Constructor & Destructor Documentation
FlatLinearConstraints() [1/3]
mlir::FlatLinearConstraints::FlatLinearConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals) inline
Constructs a constraint system reserving memory for the specified number of constraints and variables.
valArgs are the optional SSA values associated with each dimension/symbol. These must either be empty or match the number of dimensions and symbols.
Definition at line 39 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerRelation::getNumVars(), and mlir::presburger::IntegerPolyhedron::IntegerPolyhedron().
Referenced by mlir::FlatLinearValueConstraints::areVarsAlignedWithOther(), FlatLinearConstraints(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), and flattenAlignedMapAndMergeLocals().
FlatLinearConstraints() [2/3]
mlir::FlatLinearConstraints::FlatLinearConstraints (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Constructs a constraint system with the specified number of dimensions and symbols.
valArgs are the optional SSA values associated with each dimension/symbol. These must either be empty or match the number of dimensions and symbols.
Definition at line 54 of file FlatLinearValueConstraints.h.
References FlatLinearConstraints().
FlatLinearConstraints() [3/3]
mlir::FlatLinearConstraints::FlatLinearConstraints (const IntegerPolyhedron & fac) inline
Definition at line 62 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerPolyhedron::IntegerPolyhedron().
Member Function Documentation
addBound() [1/2]
LogicalResult FlatLinearConstraints::addBound (presburger::BoundType type, unsigned pos, AffineMap boundMap, AddConservativeSemiAffineBounds addSemiAffineBounds = AddConservativeSemiAffineBounds::No)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map.
In case of an EQ bound, the bound map is expected to have exactly one result. In case of a LB/UB, the bound map may have more than one result, for each of which an inequality is added.
Conservative bounds for semi-affine expressions will be added if AddConservativeSemiAffineBounds is set to Yes. This currently only covers semi-affine mod expressions, so addBound() will still fail if it encounters a semi-affine floordiv, ceildiv, or mul. Note: If enabled it is possible for the resulting constraint set to become empty if a precondition of a conservative bound is found not to hold.
Note: The dimensions/symbols of this FlatLinearConstraints must match the dimensions/symbols of the affine map. By default the lower bound is closed and the upper bound is open.
Definition at line 868 of file FlatLinearValueConstraints.cpp.
References addBound().
addBound() [2/2]
LogicalResult FlatLinearConstraints::addBound (presburger::BoundType type, unsigned pos, AffineMap boundMap, bool isClosedBound, AddConservativeSemiAffineBounds addSemiAffineBounds = AddConservativeSemiAffineBounds::No)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map.
In case of an EQ bound, the bound map is expected to have exactly one result. In case of a LB/UB, the bound map may have more than one result, for each of which an inequality is added.
The bound can be added as open or closed by specifying isClosedBound. In case of a LB/UB, isClosedBound = false means the bound is added internally as a closed bound by +1/-1 respectively. In case of an EQ bound, it can only be added as a closed bound.
Conservative bounds for semi-affine expressions will be added if AddConservativeSemiAffineBounds is set to Yes. This currently only covers semi-affine mod expressions, so addBound() will still fail if it encounters a semi-affine floordiv, ceildiv, or mul. Note: If enabled it is possible for the resulting constraint set to become empty if a precondition of a conservative bound is found not to hold.
Note: The dimensions/symbols of this FlatLinearConstraints must match the dimensions/symbols of the affine map.
Definition at line 814 of file FlatLinearValueConstraints.cpp.
References mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::addInequality(), flattenAlignedMapAndMergeLocals(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::IntegerRelation::getNumDimAndSymbolVars(), mlir::AffineMap::getNumDims(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::presburger::IntegerRelation::getNumSymbolVars(), success(), and Yes.
Referenced by addBound().
appendDimVar()
unsigned mlir::FlatLinearConstraints::appendDimVar (unsigned num = 1) inline
Append variables of the specified kind after the last variable of that kind.
The coefficient columns corresponding to the added variables are initialized to zero. vals are the Values corresponding to the variables. Return the absolute column position (i.e., not relative to the kind of variable) of the first appended variable.
Note: Empty Values are allowed in vals.
Definition at line 212 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerRelation::appendVar().
appendLocalVar()
unsigned mlir::FlatLinearConstraints::appendLocalVar (unsigned num = 1) inline
Definition at line 218 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerRelation::appendVar().
Referenced by flattenAlignedMapAndMergeLocals().
appendSymbolVar()
unsigned mlir::FlatLinearConstraints::appendSymbolVar (unsigned num = 1) inline
Definition at line 215 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerRelation::appendVar().
composeMatchingMap()
LogicalResult FlatLinearConstraints::composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatLinearConstraints.
The results of the map other are added as the leading dimensions of this constraint system. Returns failure if other is a semi-affine map.
Definition at line 226 of file FlatLinearValueConstraints.cpp.
References mlir::presburger::IntegerRelation::addEquality(), flattenAlignedMapAndMergeLocals(), mlir::presburger::IntegerRelation::getNumCols(), mlir::AffineMap::getNumDims(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::presburger::IntegerRelation::getNumSymbolVars(), insertDimVar(), and success().
Referenced by mlir::affine::FlatAffineValueConstraints::composeMap().
computeLocalVars()
LogicalResult FlatLinearConstraints::computeLocalVars (SmallVectorImpl< AffineExpr > & memo, MLIRContext * context) const protected
Compute an explicit representation for local vars.
For all systems coming from MLIR integer sets, maps, or expressions where local vars were introduced to model floordivs and mods, this always succeeds.
Definition at line 879 of file FlatLinearValueConstraints.cpp.
References mlir::changed, detectAsFloorDiv(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumLocalVars(), mlir::presburger::IntegerRelation::getNumSymbolVars(), and success().
Referenced by getAsIntegerSet(), getConstantBoundOnDimSize(), and mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap().
dumpPretty()
void FlatLinearConstraints::dumpPretty () const
A more human-readable version of dump().
Definition at line 479 of file FlatLinearValueConstraints.cpp.
References dumpRow(), mlir::presburger::IntegerRelation::getEquality64(), mlir::presburger::IntegerRelation::getInequality64(), mlir::presburger::IntegerRelation::getNumConstraints(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), mlir::presburger::IntegerRelation::getNumLocalVars(), mlir::presburger::IntegerRelation::getNumSymbolVars(), and mlir::presburger::IntegerRelation::hasConsistentState().
Referenced by getSliceBounds().
dumpRow()
void FlatLinearConstraints::dumpRow (ArrayRef< int64_t > row, bool fixedColWidth = true) const
An easier to read dump of a row of the same width as the number of columns.
fixedColWidth ensure that even with a zero coefficient, we print spaces so that variables are aligned.
Definition at line 447 of file FlatLinearValueConstraints.cpp.
References mlir::presburger::IntegerRelation::getNumCols().
Referenced by dumpPretty().
flattenAlignedMapAndMergeLocals()
LogicalResult FlatLinearConstraints::flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 > > * flattenedExprs, bool addConservativeSemiAffineBounds = false) protected
Given an affine map that is aligned with this constraint system:
Flatten the map.
Add newly introduced local columns at the beginning of this constraint system (local column pos 0).
Add equalities that define the new local columns to this constraint system.
Return the flattened expressions via flattenedExprs.
Note: This is a shared helper function of addLowerOrUpperBound and composeMatchingMap.
Definition at line 788 of file FlatLinearValueConstraints.cpp.
References mlir::presburger::IntegerRelation::append(), appendLocalVar(), FlatLinearConstraints(), mlir::getFlattenedAffineExprs(), mlir::presburger::IntegerRelation::getNumLocalVars(), insertLocalVar(), and success().
Referenced by addBound(), and composeMatchingMap().
getAsIntegerSet()
IntegerSet FlatLinearConstraints::getAsIntegerSet (MLIRContext * context) const
Returns the constraint system as an integer set.
Returns a null integer set if the system has no constraints, or if an integer set couldn't be constructed as a result of a local variable's explicit representation not being known and such a local variable appearing in any of the constraints.
Definition at line 1087 of file FlatLinearValueConstraints.cpp.
References computeLocalVars(), mlir::presburger::IntegerRelation::dump(), mlir::IntegerSet::get(), mlir::getAffineConstantExpr(), mlir::getAffineExprFromFlatForm(), mlir::presburger::IntegerRelation::getEquality64(), mlir::presburger::IntegerRelation::getInequality64(), mlir::presburger::IntegerRelation::getNumConstraints(), mlir::presburger::IntegerRelation::getNumDimAndSymbolVars(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), mlir::presburger::IntegerRelation::getNumLocalVars(), mlir::presburger::IntegerRelation::getNumSymbolVars(), mlir::presburger::IntegerRelation::getNumVars(), and mlir::presburger::IntegerRelation::isColZero().
Referenced by createSeparationCondition(), and mlir::affine::simplifyIntegerSet().
getConstantBoundOnDimSize()
std::optional< int64_t > FlatLinearConstraints::getConstantBoundOnDimSize (MLIRContext * context, unsigned pos, AffineMap * lb = nullptr, AffineMap * ub = nullptr, unsigned * minLbPos = nullptr, unsigned * minUbPos = nullptr) const
Returns a non-negative constant bound on the extent (upper bound - lower bound) of the specified variable if it is found to be a constant; returns std::nullopt if it's not a constant.
This method treats symbolic variables specially, i.e., it looks for constant differences between affine expressions involving only the symbolic variables. 'lb', if provided, is set to the lower bound map associated with the constant difference, and similarly, ub to the upper bound. Note that 'lb', 'ub' are purely symbolic and will correspond to the symbolic variables of the constaint set. The difference between this method and IntegerRelation::getConstantBoundOnDimSize is that unlike the latter, this makes use of affine expressions and maps in its inference and provides output with affine maps; it thus handles local variables by detecting them as affine functions of the symbols when possible.
Definition at line 947 of file FlatLinearValueConstraints.cpp.
References mlir::presburger::IntegerRelation::atIneq64(), computeLocalVars(), detectAsExpr(), mlir::presburger::IntegerRelation::findEqualityToConstant(), mlir::AffineExpr::floorDiv(), mlir::AffineMap::get(), getAsExpr(), mlir::presburger::IntegerRelation::getEquality64(), mlir::presburger::IntegerRelation::getLowerAndUpperBoundIndices(), mlir::presburger::IntegerRelation::getNumDimAndSymbolVars(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumSymbolVars(), mlir::presburger::IntegerRelation::getNumVars(), and mlir::simplifyAffineExpr().
Referenced by mlir::affine::MemRefRegion::getConstantBoundingSizeAndShape().
getKind()
Kind mlir::FlatLinearConstraints::getKind () const inline override virtual
Return the kind of this object.
Reimplemented from mlir::presburger::IntegerRelation.
Reimplemented in mlir::FlatLinearValueConstraints.
Definition at line 66 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerRelation::FlatLinearConstraints.
getLowerAndUpperBound()
std::pair< AffineMap, AffineMap > FlatLinearConstraints::getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext * context, bool closedUB = false) const
Gets the lower and upper bound of the offset + posth variable treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolVars) as symbols, and pos lies in [0, num).
The multi-dimensional maps in the returned pair represent the max and min of potentially multiple affine expressions. localExprs holds pre-computed AffineExpr's for all local variables in the system.
By default the returned lower bounds are closed and upper bounds are open. If closedUb is true, the upper bound is closed.
Add to 'b' from 'a' in set [0, offset) U [offset + num, symbStartPos).
Definition at line 499 of file FlatLinearValueConstraints.cpp.
References b, mlir::AffineMap::get(), mlir::getAffineExprFromFlatForm(), mlir::presburger::IntegerRelation::getEquality64(), mlir::presburger::IntegerRelation::getInequality64(), mlir::presburger::IntegerRelation::getLowerAndUpperBoundIndices(), mlir::presburger::IntegerRelation::getNumDimAndSymbolVars(), mlir::presburger::IntegerRelation::getNumDimVars(), and mlir::presburger::IntegerRelation::getNumLocalVars().
getSliceBounds()
void FlatLinearConstraints::getSliceBounds (unsigned offset, unsigned num, MLIRContext * context, SmallVectorImpl< AffineMap > * lbMaps, SmallVectorImpl< AffineMap > * ubMaps, bool closedUB = false)
Computes the lower and upper bounds of the first num dimensional variables (starting at offset) as an affine map of the remaining variables (dimensional and symbolic).
Computes the lower and upper bounds of the first 'num' dimensional variables (starting at 'offset') as affine maps of the remaining variables (dimensional and symbolic variables).
This method is able to detect variables as floordiv's and mod's of affine expressions of other variables with respect to (positive) constants. Sets bound map to a null AffineMap if such a bound can't be found (or yet unimplemented).
By default the returned lower bounds are closed and upper bounds are open. If closedUb is true, the upper bound is closed.
Local variables are themselves explicitly computed as affine functions of other variables in this process if needed.
Definition at line 700 of file FlatLinearValueConstraints.cpp.
References computeUnknownVars(), dumpPretty(), mlir::presburger::IntegerRelation::FlatLinearConstraints, mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::presburger::IntegerRelation::getConstantBound64(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumLocalVars(), mlir::AffineMap::getNumResults(), mlir::presburger::IntegerRelation::getNumSymbolVars(), mlir::presburger::IntegerRelation::getNumVars(), mlir::presburger::IntegerRelation::normalizeConstraintsByGCD(), and mlir::simplifyAffineExpr().
Referenced by mlir::affine::computeSliceUnion(), mlir::affine::getComputationSliceState(), and mlir::affine::simplifyConstrainedMinMaxOp().
insertDimVar()
unsigned mlir::FlatLinearConstraints::insertDimVar (unsigned pos, unsigned num = 1) inline
Insert variables of the specified kind at position pos.
Positions are relative to the kind of variable. The coefficient columns corresponding to the added variables are initialized to zero. vals are the Values corresponding to the variables. Values should not be used with VarKind::Local since values can only be attached to non-local variables. Return the absolute column position (i.e., not relative to the kind of variable) of the first added variable.
Note: Empty Values are allowed in vals.
Definition at line 195 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerPolyhedron::insertVar().
Referenced by composeMatchingMap().
insertLocalVar()
unsigned mlir::FlatLinearConstraints::insertLocalVar (unsigned pos, unsigned num = 1) inline
Definition at line 201 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerPolyhedron::insertVar().
Referenced by flattenAlignedMapAndMergeLocals().
insertSymbolVar()
unsigned mlir::FlatLinearConstraints::insertSymbolVar (unsigned pos, unsigned num = 1) inline
Definition at line 198 of file FlatLinearValueConstraints.h.
References mlir::presburger::IntegerPolyhedron::insertVar().
printSpace()
void FlatLinearConstraints::printSpace (raw_ostream & os) const override protected virtual
Prints the number of constraints, dimensions, symbols and locals in the FlatLinearConstraints.
Also, prints for each variable whether there is an SSA Value attached to it.
Reimplemented from mlir::presburger::IntegerRelation.
Reimplemented in mlir::FlatLinearValueConstraints.
Definition at line 1454 of file FlatLinearValueConstraints.cpp.
References mlir::presburger::IntegerRelation::getNumDimAndSymbolVars(), mlir::presburger::IntegerRelation::getVarKindEnd(), and mlir::presburger::IntegerRelation::getVarKindOffset().
The documentation for this class was generated from the following files:
include/mlir/Analysis/FlatLinearValueConstraints.h
lib/Analysis/FlatLinearValueConstraints.cpp