MLIR: mlir::LinearTransform Class Reference
mlir::LinearTransform Class Reference
#include "mlir/Analysis/LinearTransform.h"
Public Member Functions
LinearTransform (Matrix &&oMatrix)
LinearTransform (const Matrix &oMatrix)
FlatAffineConstraints applyTo (const FlatAffineConstraints &fac) const
SmallVector< int64_t, 8 > postMultiplyRow (ArrayRef< int64_t > rowVec) const
SmallVector< int64_t, 8 > preMultiplyColumn (ArrayRef< int64_t > colVec) const
Static Public Member Functions
static std::pair< unsigned, LinearTransform > makeTransformToColumnEchelon (Matrix m)
Detailed Description
Definition at line 22 of file LinearTransform.h.
Constructor & Destructor Documentation
LinearTransform() [1/2]
mlir::LinearTransform::LinearTransform (Matrix && oMatrix) explicit
Definition at line 14 of file LinearTransform.cpp.
Referenced by makeTransformToColumnEchelon().
LinearTransform() [2/2]
mlir::LinearTransform::LinearTransform (const Matrix & oMatrix) explicit
Definition at line 15 of file LinearTransform.cpp.
Member Function Documentation
applyTo()
FlatAffineConstraints mlir::LinearTransform::applyTo (const FlatAffineConstraints & fac) const
Definition at line 139 of file LinearTransform.cpp.
References mlir::FlatAffineConstraints::getEquality(), mlir::FlatAffineConstraints::getInequality(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumInequalities(), and postMultiplyRow().
Referenced by mlir::FlatAffineConstraints::findIntegerSample().
makeTransformToColumnEchelon()
std::pair< unsigned, LinearTransform > mlir::LinearTransform::makeTransformToColumnEchelon (Matrix m) static
Definition at line 33 of file LinearTransform.cpp.
References mlir::Matrix::getNumColumns(), mlir::Matrix::getNumRows(), mlir::Matrix::identity(), LinearTransform(), mlir::modEntryColumnOperation(), mlir::Matrix::negateColumn(), and mlir::Matrix::swapColumns().
Referenced by mlir::FlatAffineConstraints::findIntegerSample().
postMultiplyRow()
SmallVector< int64_t, 8 > mlir::LinearTransform::postMultiplyRow (ArrayRef< int64_t > rowVec) const
Definition at line 115 of file LinearTransform.cpp.
References mlir::Matrix::getNumColumns(), and mlir::Matrix::getNumRows().
Referenced by applyTo().
preMultiplyColumn()
SmallVector< int64_t, 8 > mlir::LinearTransform::preMultiplyColumn (ArrayRef< int64_t > colVec) const
Definition at line 127 of file LinearTransform.cpp.
References mlir::Matrix::getNumColumns(), and mlir::Matrix::getNumRows().
Referenced by mlir::FlatAffineConstraints::findIntegerSample().
The documentation for this class was generated from the following files:
include/mlir/Analysis/LinearTransform.h
lib/Analysis/LinearTransform.cpp