MLIR: mlir::dataflow::AbstractDenseForwardDataFlowAnalysis Class Reference
mlir::dataflow::AbstractDenseForwardDataFlowAnalysis Class Reference abstract
Base class for dense forward data-flow analyses.
#include "mlir/Analysis/DataFlow/DenseAnalysis.h"
Public Member Functions
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting every program point whose execution may modify the program state; that is, every operation and block.
virtual void initializeEquivalentLatticeAnchor (Operation *top) override
Initialize lattice anchor equivalence class from the provided top-level operation.
LogicalResult visit (ProgramPoint *point) override
Visit a program point that modifies the state of the program.
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
Protected Member Functions
virtual LogicalResult visitOperationImpl (Operation *op, const AbstractDenseLattice &before, AbstractDenseLattice *after)=0
Propagate the dense lattice before the execution of an operation to the lattice after its execution.
virtual AbstractDenseLattice * getLattice (LatticeAnchor anchor)=0
Get the dense lattice on the given lattice anchor.
virtual const AbstractDenseLattice * getLatticeFor (ProgramPoint *dependent, LatticeAnchor anchor)=0
Get the dense lattice on the given lattice anchor and add dependent as its dependency.
virtual void setToEntryState (AbstractDenseLattice *lattice)=0
Set the dense lattice at control flow entry point and propagate an update if it changed.
void join (AbstractDenseLattice *lhs, const AbstractDenseLattice &rhs)
Join a lattice with another and propagate an update if it changed.
virtual LogicalResult processOperation (Operation *op)
Visit an operation.
virtual void buildOperationEquivalentLatticeAnchor (Operation *op)
Visit an operation.
virtual void visitBlockTransfer (Block *block, ProgramPoint *point, Block *predecessor, const AbstractDenseLattice &before, AbstractDenseLattice *after)
Visit a block and propagate the dense lattice forward along the control flow edge from predecessor to block.
virtual void visitRegionBranchControlFlowTransfer (RegionBranchOpInterface branch, std::optional< unsigned > regionFrom, std::optional< unsigned > regionTo, const AbstractDenseLattice &before, AbstractDenseLattice *after)
Propagate the dense lattice forward along the control flow edge from regionFrom to regionTo regions of the branch operation.
virtual void visitCallControlFlowTransfer (CallOpInterface call, CallControlFlowAction action, const AbstractDenseLattice &before, AbstractDenseLattice *after)
Propagate the dense lattice forward along the call control flow edge, which can be either entering or exiting the callee.
void visitRegionBranchOperation (ProgramPoint *point, RegionBranchOpInterface branch, AbstractDenseLattice *after)
Visit a program point within a region branch operation with predecessors in it.
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint *point)
Create a dependency between the given analysis state and lattice anchor on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename AnchorT>
void registerAnchorKind ()
Register a custom lattice anchor class.
template<typename AnchorT, typename... Args>
AnchorT * getLatticeAnchor (Args &&...args)
Get or create a custom lattice anchor.
template<typename StateT, typename AnchorT>
void unionLatticeAnchors (AnchorT anchor, AnchorT other)
Union input anchors under the given state.
template<typename StateT, typename AnchorT>
StateT * getOrCreate (AnchorT anchor)
Get the analysis state associated with the lattice anchor.
template<typename StateT, typename AnchorT>
const StateT * getOrCreateFor (ProgramPoint *dependent, AnchorT anchor)
Get a read-only analysis state for the given point and create a dependency on dependent.
ProgramPoint * getProgramPointBefore (Operation *op)
Get a uniqued program point instance.
ProgramPoint * getProgramPointBefore (Block *block)
ProgramPoint * getProgramPointAfter (Operation *op)
ProgramPoint * getProgramPointAfter (Block *block)
const DataFlowConfig & getSolverConfig () const
Return the configuration of the solver used for this analysis.
Detailed Description
Base class for dense forward data-flow analyses.
Dense data-flow analysis attaches a lattice to program points and implements a transfer function from the lattice before each operation to the lattice after. The lattice contains information about the state of the program at that program point.
Visit a program point in forward dense data-flow analysis will invoke the transfer function of the operation preceding the program point iterator. Visit a program point at the begining of block will visit the block itself.
Definition at line 68 of file DenseAnalysis.h.
Member Function Documentation
buildOperationEquivalentLatticeAnchor()
virtual void mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::buildOperationEquivalentLatticeAnchor (Operation * op) inline protected virtual
Visit an operation.
If this analysis can confirm that lattice content of lattice anchors around operation are necessarily identical, join them into the same equivalent class.
Definition at line 128 of file DenseAnalysis.h.
Referenced by initializeEquivalentLatticeAnchor().
DataFlowAnalysis()
DataFlowAnalysis::DataFlowAnalysis (DataFlowSolver & solver) explicit
Create an analysis with a reference to the parent solver.
Definition at line 596 of file DataFlowFramework.cpp.
getLattice()
virtual AbstractDenseLattice * mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::getLattice (LatticeAnchor anchor) protected pure virtual
Get the dense lattice on the given lattice anchor.
Implemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Referenced by processOperation().
getLatticeFor()
virtual const AbstractDenseLattice * mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::getLatticeFor (ProgramPoint * dependent, LatticeAnchor anchor) protected pure virtual
Get the dense lattice on the given lattice anchor and add dependent as its dependency.
That is, every time the lattice after anchor is updated, the dependent program point must be visited, and the newly triggered visit might update the lattice on dependent.
Implemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Referenced by processOperation(), and visitRegionBranchOperation().
initialize()
LogicalResult AbstractDenseForwardDataFlowAnalysis::initialize (Operation * top) override virtual
Initialize the analysis by visiting every program point whose execution may modify the program state; that is, every operation and block.
Implements mlir::DataFlowAnalysis.
Definition at line 50 of file DenseAnalysis.cpp.
References mlir::Operation::getRegions(), initialize(), processOperation(), and success().
Referenced by initialize().
initializeEquivalentLatticeAnchor()
void AbstractDenseForwardDataFlowAnalysis::initializeEquivalentLatticeAnchor (Operation * top) override virtual
Initialize lattice anchor equivalence class from the provided top-level operation.
This function will union lattice anchor to same equivalent class if the analysis can determine the lattice content of lattice anchor is necessarily identical under the corrensponding lattice type.
Reimplemented from mlir::DataFlowAnalysis.
Definition at line 33 of file DenseAnalysis.cpp.
References buildOperationEquivalentLatticeAnchor(), and mlir::Operation::walk().
join()
void mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::join (AbstractDenseLattice * lhs, const AbstractDenseLattice & rhs) inline protected
Join a lattice with another and propagate an update if it changed.
Definition at line 115 of file DenseAnalysis.h.
References lhs, mlir::DataFlowAnalysis::propagateIfChanged(), and rhs.
Referenced by visitBlockTransfer(), visitCallControlFlowTransfer(), visitRegionBranchControlFlowTransfer(), and visitRegionBranchOperation().
processOperation()
LogicalResult AbstractDenseForwardDataFlowAnalysis::processOperation (Operation * op) protected virtual
Visit an operation.
If this is a call operation or region control-flow operation, then the state after the execution of the operation is set by control-flow or the callgraph. Otherwise, this function invokes the operation transfer function.
Definition at line 151 of file DenseAnalysis.cpp.
References mlir::Operation::getBlock(), getLattice(), getLatticeFor(), mlir::DataFlowAnalysis::getOrCreateFor(), mlir::DataFlowAnalysis::getProgramPointAfter(), mlir::DataFlowAnalysis::getProgramPointBefore(), success(), visitOperationImpl(), and visitRegionBranchOperation().
Referenced by initialize(), and visit().
setToEntryState()
virtual void mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::setToEntryState (AbstractDenseLattice * lattice) protected pure virtual
Set the dense lattice at control flow entry point and propagate an update if it changed.
Implemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Referenced by visitCallControlFlowTransfer().
visit()
LogicalResult AbstractDenseForwardDataFlowAnalysis::visit (ProgramPoint * point) override virtual
Visit a program point that modifies the state of the program.
If the program point is at the beginning of a block, then the state is propagated from control-flow predecessors or callsites. If the operation before program point iterator is a call operation or region control-flow operation, then the state after the execution of the operation is set by control-flow or the callgraph. Otherwise, this function invokes the operation transfer function before the program point iterator.
Implements mlir::DataFlowAnalysis.
Definition at line 80 of file DenseAnalysis.cpp.
References mlir::ProgramPoint::getBlock(), mlir::ProgramPoint::getPrevOp(), mlir::ProgramPoint::isBlockStart(), processOperation(), and success().
visitBlockTransfer()
virtual void mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visitBlockTransfer (Block * block, ProgramPoint * point, Block * predecessor, const AbstractDenseLattice & before, AbstractDenseLattice * after) inline protected virtual
Visit a block and propagate the dense lattice forward along the control flow edge from predecessor to block.
point corresponds to the program point before block. The default implementation merges in the state from the predecessor's terminator.
Reimplemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Definition at line 134 of file DenseAnalysis.h.
References join().
Referenced by mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >::visitBlockTransfer().
visitCallControlFlowTransfer()
virtual void mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visitCallControlFlowTransfer (CallOpInterface call, CallControlFlowAction action, const AbstractDenseLattice & before, AbstractDenseLattice * after) inline protected virtual
Propagate the dense lattice forward along the call control flow edge, which can be either entering or exiting the callee.
Default implementation for enter and exit callee actions just meets the states, meaning that operations implementing CallOpInterface don't have any effect on the lattice that isn't already expressed by the interface itself. Default implementation for the external callee action additionally sets the "after" lattice to the entry state.
Reimplemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Definition at line 163 of file DenseAnalysis.h.
References mlir::dataflow::ExternalCallee, join(), and setToEntryState().
Referenced by mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >::visitCallControlFlowTransfer().
visitOperationImpl()
virtual LogicalResult mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visitOperationImpl (Operation * op, const AbstractDenseLattice & before, AbstractDenseLattice * after) protected pure virtual
Propagate the dense lattice before the execution of an operation to the lattice after its execution.
Implemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Referenced by processOperation().
visitRegionBranchControlFlowTransfer()
virtual void mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::visitRegionBranchControlFlowTransfer (RegionBranchOpInterface branch, std::optional< unsigned > regionFrom, std::optional< unsigned > regionTo, const AbstractDenseLattice & before, AbstractDenseLattice * after) inline protected virtual
Propagate the dense lattice forward along the control flow edge from regionFrom to regionTo regions of the branch operation.
nullopt values correspond to control flow branches originating at or targeting the branch operation itself. Default implementation just joins the states, meaning that operations implementing RegionBranchOpInterface don't have any effect on the lattice that isn't already expressed by the interface itself.
Reimplemented in mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >.
Definition at line 149 of file DenseAnalysis.h.
References join().
Referenced by mlir::dataflow::DenseForwardDataFlowAnalysis< LatticeT >::visitRegionBranchControlFlowTransfer(), and visitRegionBranchOperation().
visitRegionBranchOperation()
void AbstractDenseForwardDataFlowAnalysis::visitRegionBranchOperation (ProgramPoint * point, RegionBranchOpInterface branch, AbstractDenseLattice * after) protected
Visit a program point within a region branch operation with predecessors in it.
This can either be an entry block of one of the regions of the parent operation itself.
Definition at line 276 of file DenseAnalysis.cpp.
References mlir::ProgramPoint::getBlock(), getLatticeFor(), mlir::DataFlowAnalysis::getOrCreateFor(), mlir::Block::getParent(), mlir::ProgramPoint::getPrevOp(), mlir::DataFlowAnalysis::getProgramPointAfter(), mlir::DataFlowAnalysis::getProgramPointBefore(), mlir::Region::getRegionNumber(), mlir::ProgramPoint::isBlockStart(), join(), and visitRegionBranchControlFlowTransfer().
Referenced by processOperation().
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/DenseAnalysis.h
lib/Analysis/DataFlow/DenseAnalysis.cpp