MLIR: mlir::AsmPrinter::CyclicPrintReset Class Reference
mlir::AsmPrinter::CyclicPrintReset Class Reference
Class used to automatically end a cyclic region on destruction.
#include "mlir/IR/OpImplementation.h"
Public Member Functions
CyclicPrintReset (AsmPrinter *printer)
~CyclicPrintReset ()
CyclicPrintReset (const CyclicPrintReset &)=delete
CyclicPrintReset & operator= (const CyclicPrintReset &)=delete
CyclicPrintReset (CyclicPrintReset &&rhs)
CyclicPrintReset & operator= (CyclicPrintReset &&rhs)
Detailed Description
Class used to automatically end a cyclic region on destruction.
Definition at line 271 of file OpImplementation.h.
Constructor & Destructor Documentation
CyclicPrintReset() [1/3]
mlir::AsmPrinter::CyclicPrintReset::CyclicPrintReset (AsmPrinter * printer) inline explicit
Definition at line 273 of file OpImplementation.h.
References mlir::AsmPrinter::AsmPrinter().
Referenced by CyclicPrintReset(), CyclicPrintReset(), operator=(), and operator=().
~CyclicPrintReset()
mlir::AsmPrinter::CyclicPrintReset::~CyclicPrintReset () inline
Definition at line 275 of file OpImplementation.h.
CyclicPrintReset() [2/3]
mlir::AsmPrinter::CyclicPrintReset::CyclicPrintReset (const CyclicPrintReset &) delete
References CyclicPrintReset().
CyclicPrintReset() [3/3]
mlir::AsmPrinter::CyclicPrintReset::CyclicPrintReset (CyclicPrintReset && rhs) inline
Definition at line 284 of file OpImplementation.h.
References CyclicPrintReset(), nullptr, and rhs.
Member Function Documentation
operator=() [1/2]
CyclicPrintReset & mlir::AsmPrinter::CyclicPrintReset::operator= (const CyclicPrintReset &) delete
References CyclicPrintReset().
operator=() [2/2]
CyclicPrintReset & mlir::AsmPrinter::CyclicPrintReset::operator= (CyclicPrintReset && rhs) inline
Definition at line 287 of file OpImplementation.h.
References CyclicPrintReset(), and rhs.
The documentation for this class was generated from the following file:
include/mlir/IR/OpImplementation.h