MLIR: mlir::LLVM::ModuleToObject Class Reference
mlir::LLVM::ModuleToObject Class Reference
Utility base class for transforming operations into binary objects, by default it returns the serialized LLVM bitcode for the module.
#include "mlir/Target/LLVM/ModuleToObject.h"
Public Member Functions
ModuleToObject (Operation &module, StringRef triple, StringRef chip, StringRef features={}, int optLevel=3, function_ref< void(llvm::Module &)> initialLlvmIRCallback={}, function_ref< void(llvm::Module &)> linkedLlvmIRCallback={}, function_ref< void(llvm::Module &)> optimizedLlvmIRCallback={}, function_ref< void(StringRef)> isaCallback={})
virtual ~ModuleToObject ()
Operation & getOperation ()
Returns the operation being serialized.
virtual std::optional< SmallVector< char, 0 > > run ()
Runs the serialization pipeline, returning std::nullopt on error.
Protected Member Functions
virtual void setDataLayoutAndTriple (llvm::Module &module)
Hook for computing the Datalayout.
virtual std::optional< SmallVector< std::unique_ptr< llvm::Module > > > loadBitcodeFiles (llvm::Module &module)
Hook for loading bitcode files, returns std::nullopt on failure.
virtual LogicalResult handleBitcodeFile (llvm::Module &module)
Hook for performing additional actions on a loaded bitcode file.
virtual void handleModulePreLink (llvm::Module &module)
Hook for performing additional actions on the llvmModule pre linking.
virtual void handleModulePostLink (llvm::Module &module)
Hook for performing additional actions on the llvmModule post linking.
virtual std::optional< SmallVector< char, 0 > > moduleToObject (llvm::Module &llvmModule)
Serializes the LLVM IR bitcode to an object file, by default it serializes to LLVM bitcode.
std::optional< llvm::TargetMachine * > getOrCreateTargetMachine ()
Create the target machine based on the target triple and chip.
std::unique_ptr< llvm::Module > loadBitcodeFile (llvm::LLVMContext &context, StringRef path)
Loads a bitcode file from path.
LogicalResult loadBitcodeFilesFromList (llvm::LLVMContext &context, ArrayRef< Attribute > librariesToLink, SmallVector< std::unique_ptr< llvm::Module > > &llvmModules, bool failureOnError=true)
Loads multiple bitcode files.
std::unique_ptr< llvm::Module > translateToLLVMIR (llvm::LLVMContext &llvmContext)
Translates the operation to LLVM IR.
LogicalResult linkFiles (llvm::Module &module, SmallVector< std::unique_ptr< llvm::Module > > &&libs)
Link the llvmModule to other bitcode file.
virtual LogicalResult optimizeModule (llvm::Module &module, int optL)
Optimize the module.
Static Protected Member Functions
static std::optional< std::string > translateToISA (llvm::Module &llvmModule, llvm::TargetMachine &targetMachine)
Utility function for translating to ISA, returns std::nullopt on failure.
Protected Attributes
Operation & module
Module to transform to a binary object.
StringRef triple
Target triple.
StringRef chip
Target chip.
StringRef features
Target features.
int optLevel
Optimization level.
function_ref< void(llvm::Module &)> initialLlvmIRCallback
Callback invoked with the initial LLVM IR for the device module.
function_ref< void(llvm::Module &)> linkedLlvmIRCallback
Callback invoked with LLVM IR for the device module after linking the device libraries.
function_ref< void(llvm::Module &)> optimizedLlvmIRCallback
Callback invoked with LLVM IR for the device module after LLVM optimizations but before codegen.
function_ref< void(StringRef)> isaCallback
Callback invoked with the target ISA for the device, for example PTX assembly.
Detailed Description
Utility base class for transforming operations into binary objects, by default it returns the serialized LLVM bitcode for the module.
The operations being transformed must be translatable into LLVM IR.
Definition at line 30 of file ModuleToObject.h.
Constructor & Destructor Documentation
ModuleToObject()
ModuleToObject::ModuleToObject (Operation & module, StringRef triple, StringRef chip, StringRef features = {}, int optLevel = 3, function_ref< void(llvm::Module &)> initialLlvmIRCallback = {}, function_ref< void(llvm::Module &)> linkedLlvmIRCallback = {}, function_ref< void(llvm::Module &)> optimizedLlvmIRCallback = {}, function_ref< void(StringRef)> isaCallback = {})
Definition at line 37 of file ModuleToObject.cpp.
References chip, features, initialLlvmIRCallback, isaCallback, linkedLlvmIRCallback, module, optimizedLlvmIRCallback, optLevel, and triple.
Referenced by mlir::NVVM::SerializeGPUModuleBase::SerializeGPUModuleBase(), mlir::ROCDL::SerializeGPUModuleBase::SerializeGPUModuleBase(), and mlir::xevm::SerializeGPUModuleBase::SerializeGPUModuleBase().
~ModuleToObject()
ModuleToObject::~ModuleToObject () virtual default
References module.
Member Function Documentation
getOperation()
Operation & ModuleToObject::getOperation ()
Returns the operation being serialized.
Definition at line 51 of file ModuleToObject.cpp.
Referenced by mlir::NVVM::SerializeGPUModuleBase::appendStandardLibs(), mlir::ROCDL::SerializeGPUModuleBase::appendStandardLibs(), mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(), mlir::ROCDL::SerializeGPUModuleBase::compileToBinary(), mlir::xevm::SerializeGPUModuleBase::getGPUModuleOp(), getOrCreateTargetMachine(), linkFiles(), loadBitcodeFile(), loadBitcodeFilesFromList(), mlir::ROCDL::SerializeGPUModuleBase::moduleToObjectImpl(), optimizeModule(), run(), and translateToLLVMIR().
getOrCreateTargetMachine()
std::optional< llvm::TargetMachine * > ModuleToObject::getOrCreateTargetMachine () protected
Create the target machine based on the target triple and chip.
This can fail if the target is not available.
Definition at line 54 of file ModuleToObject.cpp.
References chip, mlir::Operation::emitError(), features, getOperation(), target, and triple.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::moduleToObjectImpl(), optimizeModule(), and setDataLayoutAndTriple().
handleBitcodeFile()
virtual LogicalResult mlir::LLVM::ModuleToObject::handleBitcodeFile (llvm::Module & module) inline protected virtual
Hook for performing additional actions on a loaded bitcode file.
Reimplemented in mlir::ROCDL::SerializeGPUModuleBase.
Definition at line 60 of file ModuleToObject.h.
References module, and success().
Referenced by loadBitcodeFile(), and loadBitcodeFilesFromList().
handleModulePostLink()
virtual void mlir::LLVM::ModuleToObject::handleModulePostLink (llvm::Module & module) inline protected virtual
Hook for performing additional actions on the llvmModule post linking.
Definition at line 68 of file ModuleToObject.h.
References module.
Referenced by run().
handleModulePreLink()
virtual void mlir::LLVM::ModuleToObject::handleModulePreLink (llvm::Module & module) inline protected virtual
Hook for performing additional actions on the llvmModule pre linking.
Reimplemented in mlir::ROCDL::SerializeGPUModuleBase.
Definition at line 65 of file ModuleToObject.h.
References module.
Referenced by run().
linkFiles()
LogicalResult ModuleToObject::linkFiles (llvm::Module & module, SmallVector< std::unique_ptr< llvm::Module > > && libs) protected
Link the llvmModule to other bitcode file.
Definition at line 150 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), getOperation(), module, and success().
Referenced by run().
loadBitcodeFile()
std::unique_ptr< llvm::Module > ModuleToObject::loadBitcodeFile (llvm::LLVMContext & context, StringRef path) protected
Loads a bitcode file from path.
Definition at line 77 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), getOperation(), and handleBitcodeFile().
Referenced by loadBitcodeFilesFromList().
loadBitcodeFiles()
virtual std::optional< SmallVector< std::unique_ptr< llvm::Module > > > mlir::LLVM::ModuleToObject::loadBitcodeFiles (llvm::Module & module) inline protected virtual
Hook for loading bitcode files, returns std::nullopt on failure.
Reimplemented in mlir::NVVM::SerializeGPUModuleBase, mlir::ROCDL::SerializeGPUModuleBase, and mlir::xevm::SerializeGPUModuleBase.
Definition at line 55 of file ModuleToObject.h.
References module.
Referenced by run().
loadBitcodeFilesFromList()
LogicalResult ModuleToObject::loadBitcodeFilesFromList (llvm::LLVMContext & context, ArrayRef< Attribute > librariesToLink, SmallVector< std::unique_ptr< llvm::Module > > & llvmModules, bool failureOnError = true) protected
Loads multiple bitcode files.
Definition at line 92 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), getOperation(), handleBitcodeFile(), loadBitcodeFile(), and success().
Referenced by mlir::NVVM::SerializeGPUModuleBase::loadBitcodeFiles(), mlir::ROCDL::SerializeGPUModuleBase::loadBitcodeFiles(), and mlir::xevm::SerializeGPUModuleBase::loadBitcodeFiles().
moduleToObject()
std::optional< SmallVector< char, 0 > > ModuleToObject::moduleToObject (llvm::Module & llvmModule) protected virtual
Serializes the LLVM IR bitcode to an object file, by default it serializes to LLVM bitcode.
Definition at line 239 of file ModuleToObject.cpp.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::moduleToObjectImpl(), and run().
optimizeModule()
LogicalResult ModuleToObject::optimizeModule (llvm::Module & module, int optL) protected virtual
Optimize the module.
Definition at line 179 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), getOperation(), getOrCreateTargetMachine(), mlir::makeOptimizingTransformer(), module, optLevel, success(), and triple.
Referenced by run().
run()
std::optional< SmallVector< char, 0 > > ModuleToObject::run () virtual
Runs the serialization pipeline, returning std::nullopt on error.
Definition at line 247 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), getOperation(), handleModulePostLink(), handleModulePreLink(), initialLlvmIRCallback, linkedLlvmIRCallback, linkFiles(), loadBitcodeFiles(), moduleToObject(), optimizedLlvmIRCallback, optimizeModule(), optLevel, setDataLayoutAndTriple(), and translateToLLVMIR().
setDataLayoutAndTriple()
void ModuleToObject::setDataLayoutAndTriple (llvm::Module & module) protected virtual
Hook for computing the Datalayout.
Definition at line 227 of file ModuleToObject.cpp.
References getOrCreateTargetMachine(), and module.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::handleBitcodeFile(), and run().
translateToISA()
std::optional< std::string > ModuleToObject::translateToISA (llvm::Module & llvmModule, llvm::TargetMachine & targetMachine) static protected
Utility function for translating to ISA, returns std::nullopt on failure.
Definition at line 209 of file ModuleToObject.cpp.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::moduleToObjectImpl().
translateToLLVMIR()
std::unique_ptr< llvm::Module > ModuleToObject::translateToLLVMIR (llvm::LLVMContext & llvmContext) protected
Translates the operation to LLVM IR.
Definition at line 145 of file ModuleToObject.cpp.
References getOperation(), and mlir::translateModuleToLLVMIR().
Referenced by run().
Member Data Documentation
chip
StringRef mlir::LLVM::ModuleToObject::chip protected
Target chip.
Definition at line 114 of file ModuleToObject.h.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::addControlVariables(), mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(), getOrCreateTargetMachine(), and ModuleToObject().
features
StringRef mlir::LLVM::ModuleToObject::features protected
Target features.
Definition at line 117 of file ModuleToObject.h.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(), getOrCreateTargetMachine(), and ModuleToObject().
initialLlvmIRCallback
function_ref<void(llvm::Module &)> mlir::LLVM::ModuleToObject::initialLlvmIRCallback protected
Callback invoked with the initial LLVM IR for the device module.
Definition at line 123 of file ModuleToObject.h.
Referenced by ModuleToObject(), and run().
isaCallback
function_ref<void(StringRef)> mlir::LLVM::ModuleToObject::isaCallback protected
Callback invoked with the target ISA for the device, for example PTX assembly.
Definition at line 135 of file ModuleToObject.h.
Referenced by ModuleToObject().
linkedLlvmIRCallback
function_ref<void(llvm::Module &)> mlir::LLVM::ModuleToObject::linkedLlvmIRCallback protected
Callback invoked with LLVM IR for the device module after linking the device libraries.
Definition at line 127 of file ModuleToObject.h.
Referenced by ModuleToObject(), and run().
module
Operation& mlir::LLVM::ModuleToObject::module protected
Module to transform to a binary object.
Definition at line 108 of file ModuleToObject.h.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::addControlVariables(), handleBitcodeFile(), mlir::ROCDL::SerializeGPUModuleBase::handleBitcodeFile(), handleModulePostLink(), handleModulePreLink(), mlir::ROCDL::SerializeGPUModuleBase::handleModulePreLink(), linkFiles(), loadBitcodeFiles(), mlir::NVVM::SerializeGPUModuleBase::loadBitcodeFiles(), mlir::ROCDL::SerializeGPUModuleBase::loadBitcodeFiles(), mlir::xevm::SerializeGPUModuleBase::loadBitcodeFiles(), ModuleToObject(), optimizeModule(), mlir::NVVM::SerializeGPUModuleBase::SerializeGPUModuleBase(), mlir::ROCDL::SerializeGPUModuleBase::SerializeGPUModuleBase(), mlir::xevm::SerializeGPUModuleBase::SerializeGPUModuleBase(), setDataLayoutAndTriple(), and ~ModuleToObject().
optimizedLlvmIRCallback
function_ref<void(llvm::Module &)> mlir::LLVM::ModuleToObject::optimizedLlvmIRCallback protected
Callback invoked with LLVM IR for the device module after LLVM optimizations but before codegen.
Definition at line 131 of file ModuleToObject.h.
Referenced by ModuleToObject(), and run().
optLevel
int mlir::LLVM::ModuleToObject::optLevel protected
Optimization level.
Definition at line 120 of file ModuleToObject.h.
Referenced by ModuleToObject(), optimizeModule(), and run().
triple
StringRef mlir::LLVM::ModuleToObject::triple protected
Target triple.
Definition at line 111 of file ModuleToObject.h.
Referenced by mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(), getOrCreateTargetMachine(), ModuleToObject(), mlir::ROCDL::SerializeGPUModuleBase::moduleToObjectImpl(), and optimizeModule().
The documentation for this class was generated from the following files:
include/mlir/Target/LLVM/ModuleToObject.h
lib/Target/LLVM/ModuleToObject.cpp