MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects Class Reference
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyDialects (PyMlirContextRef contextRef)
MlirDialect getDialectForKey (const std::string &key, bool attrError)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
Definition at line 490 of file IRCore.h.
Constructor & Destructor Documentation
PyDialects()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects::PyDialects (PyMlirContextRef contextRef) inline
Definition at line 492 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject().
Member Function Documentation
getDialectForKey()
MlirDialect mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects::getDialectForKey (const std::string & key, bool attrError)
Definition at line 795 of file IRCore.cpp.
References mlir::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), join(), mlirContextGetOrLoadDialect(), and mlirDialectIsNull().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getDynamicAttrDef(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getDynamicTypeDef().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp