MLIR: mlir::spirv::VerCapExtAttr Class Reference
mlir::spirv::VerCapExtAttr Class Reference
An attribute that specifies the SPIR-V (version, capabilities, extensions) triple.
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
Classes
struct cap_iterator
struct ext_iterator
Public Types
using ext_range = llvm::iterator_range< ext_iterator >
using cap_range = llvm::iterator_range< cap_iterator >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
Version getVersion ()
Returns the version.
ext_range getExtensions ()
Returns the extensions.
ArrayAttr getExtensionsAttr ()
Returns the extensions as a string array attribute.
cap_range getCapabilities ()
Returns the capabilities.
ArrayAttr getCapabilitiesAttr ()
Returns the capabilities as an integer array attribute.
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static VerCapExtAttr get (Version version, ArrayRef< Capability > capabilities, ArrayRef< Extension > extensions, MLIRContext *context)
Gets a VerCapExtAttr instance.
static VerCapExtAttr get (IntegerAttr version, ArrayAttr capabilities, ArrayAttr extensions)
static StringRef getKindName ()
Returns the attribute kind's name (without the 'spirv.' prefix).
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, IntegerAttr version, ArrayAttr capabilities, ArrayAttr extensions)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.ver_cap_ext"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that specifies the SPIR-V (version, capabilities, extensions) triple.
Definition at line 89 of file SPIRVAttributes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
cap_range
using mlir::spirv::VerCapExtAttr::cap_range = llvm::iterator_range<cap_iterator>
Definition at line 125 of file SPIRVAttributes.h.
ext_range
using mlir::spirv::VerCapExtAttr::ext_range = llvm::iterator_range<ext_iterator>
Definition at line 113 of file SPIRVAttributes.h.
Member Function Documentation
get() [1/2]
spirv::VerCapExtAttr spirv::VerCapExtAttr::get (IntegerAttr version, ArrayAttr capabilities, ArrayAttr extensions) static
Definition at line 213 of file SPIRVAttributes.cpp.
References mlir::get().
get() [2/2]
static VerCapExtAttr mlir::spirv::VerCapExtAttr::get (Version version, ArrayRef< Capability > capabilities, ArrayRef< Extension > extensions, MLIRContext * context) static
Gets a VerCapExtAttr instance.
Referenced by mlir::spirv::getDefaultTargetEnv(), and parseVerCapExtAttr().
getCapabilities()
spirv::VerCapExtAttr::cap_range spirv::VerCapExtAttr::getCapabilities ()
Returns the capabilities.
Definition at line 252 of file SPIRVAttributes.cpp.
References getCapabilitiesAttr().
Referenced by print().
getCapabilitiesAttr()
ArrayAttr spirv::VerCapExtAttr::getCapabilitiesAttr ()
Returns the capabilities as an integer array attribute.
Definition at line 257 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by getCapabilities().
getExtensions()
spirv::VerCapExtAttr::ext_range spirv::VerCapExtAttr::getExtensions ()
Returns the extensions.
Definition at line 235 of file SPIRVAttributes.cpp.
References getExtensionsAttr().
getExtensionsAttr()
ArrayAttr spirv::VerCapExtAttr::getExtensionsAttr ()
Returns the extensions as a string array attribute.
Definition at line 240 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by getExtensions(), and print().
getKindName()
StringRef spirv::VerCapExtAttr::getKindName () static
Returns the attribute kind's name (without the 'spirv.' prefix).
Definition at line 221 of file SPIRVAttributes.cpp.
Referenced by print().
getVersion()
spirv::Version spirv::VerCapExtAttr::getVersion ()
Returns the version.
Definition at line 223 of file SPIRVAttributes.cpp.
Referenced by print().
verifyInvariants()
LogicalResult spirv::VerCapExtAttr::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, IntegerAttr version, ArrayAttr capabilities, ArrayAttr extensions) static
Definition at line 261 of file SPIRVAttributes.cpp.
References mlir::emitError().
Member Data Documentation
name
constexpr StringLiteral mlir::spirv::VerCapExtAttr::name = "spirv.ver_cap_ext" static constexpr
Definition at line 137 of file SPIRVAttributes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVAttributes.h
lib/Dialect/SPIRV/IR/SPIRVAttributes.cpp