MLIR: mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis Class Reference
mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis Class Reference abstract
Base class for sparse backward data-flow analyses.
#include "mlir/Analysis/DataFlow/SparseAnalysis.h"
Public Member Functions
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting the operation and everything nested under it.
LogicalResult visit (ProgramPoint *point) override
Visit a program point.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
virtual void initializeEquivalentLatticeAnchor (Operation *top)
Initialize lattice anchor equivalence class from the provided top-level operation.
Protected Member Functions
AbstractSparseBackwardDataFlowAnalysis (DataFlowSolver &solver, SymbolTableCollection &symbolTable)
virtual LogicalResult visitOperationImpl (Operation *op, ArrayRef< AbstractSparseLattice * > operandLattices, ArrayRef< const AbstractSparseLattice * > resultLattices)=0
The operation transfer function.
virtual void visitExternalCallImpl (CallOpInterface call, ArrayRef< AbstractSparseLattice * > operandLattices, ArrayRef< const AbstractSparseLattice * > resultLattices)=0
The transfer function for calls to external functions.
virtual void visitBranchOperand (OpOperand &operand)=0
virtual void visitCallOperand (OpOperand &operand)=0
virtual void setToExitState (AbstractSparseLattice *lattice)=0
Set the given lattice element(s) at control flow exit point(s) and propagate the update if it chaned.
void setAllToExitStates (ArrayRef< AbstractSparseLattice * > lattices)
Set the given lattice element(s) at control flow exit point(s) and propagate the update if it chaned.
virtual AbstractSparseLattice * getLatticeElement (Value value)=0
Get the lattice element for a value.
SmallVector< AbstractSparseLattice * > getLatticeElements (ValueRange values)
Get the lattice elements for a range of values.
void meet (AbstractSparseLattice *lhs, const AbstractSparseLattice &rhs)
Join the lattice element and propagate and update if it changed.
virtual LogicalResult visitCallableOperation (Operation *op, CallableOpInterface callable, ArrayRef< AbstractSparseLattice * > operandLattices)
Visits a callable operation.
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint *point)
Create a dependency between the given analysis state and lattice anchor on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename AnchorT>
void registerAnchorKind ()
Register a custom lattice anchor class.
template<typename AnchorT, typename... Args>
AnchorT * getLatticeAnchor (Args &&...args)
Get or create a custom lattice anchor.
template<typename StateT, typename AnchorT>
void unionLatticeAnchors (AnchorT anchor, AnchorT other)
Union input anchors under the given state.
template<typename StateT, typename AnchorT>
StateT * getOrCreate (AnchorT anchor)
Get the analysis state associated with the lattice anchor.
template<typename StateT, typename AnchorT>
const StateT * getOrCreateFor (ProgramPoint *dependent, AnchorT anchor)
Get a read-only analysis state for the given point and create a dependency on dependent.
ProgramPoint * getProgramPointBefore (Operation *op)
Get a uniqued program point instance.
ProgramPoint * getProgramPointBefore (Block *block)
ProgramPoint * getProgramPointAfter (Operation *op)
ProgramPoint * getProgramPointAfter (Block *block)
const DataFlowConfig & getSolverConfig () const
Return the configuration of the solver used for this analysis.
Detailed Description
Base class for sparse backward data-flow analyses.
Similar to AbstractSparseForwardDataFlowAnalysis, but walks bottom to top.
Definition at line 405 of file SparseAnalysis.h.
Constructor & Destructor Documentation
AbstractSparseBackwardDataFlowAnalysis()
AbstractSparseBackwardDataFlowAnalysis::AbstractSparseBackwardDataFlowAnalysis (DataFlowSolver & solver, SymbolTableCollection & symbolTable) explicit protected
Definition at line 359 of file SparseAnalysis.cpp.
References mlir::DataFlowAnalysis::DataFlowAnalysis(), mlir::DataFlowAnalysis::DataFlowSolver, and mlir::DataFlowAnalysis::registerAnchorKind().
Referenced by mlir::dataflow::SparseBackwardDataFlowAnalysis< StateT >::SparseBackwardDataFlowAnalysis().
Member Function Documentation
getLatticeElement()
virtual AbstractSparseLattice * mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::getLatticeElement (Value value) protected pure virtual
Get the lattice element for a value.
Implemented in mlir::dataflow::SparseBackwardDataFlowAnalysis< StateT >, and mlir::dataflow::SparseBackwardDataFlowAnalysis< Liveness >.
References lhs, and rhs.
Referenced by getLatticeElements().
getLatticeElements()
SmallVector< AbstractSparseLattice * > AbstractSparseBackwardDataFlowAnalysis::getLatticeElements (ValueRange values) protected
Get the lattice elements for a range of values.
Definition at line 402 of file SparseAnalysis.cpp.
References getLatticeElement(), and result.
initialize()
LogicalResult AbstractSparseBackwardDataFlowAnalysis::initialize (Operation * top) override virtual
Initialize the analysis by visiting the operation and everything nested under it.
Implements mlir::DataFlowAnalysis.
Definition at line 366 of file SparseAnalysis.cpp.
meet()
void AbstractSparseBackwardDataFlowAnalysis::meet (AbstractSparseLattice * lhs, const AbstractSparseLattice & rhs) protected
Join the lattice element and propagate and update if it changed.
Definition at line 668 of file SparseAnalysis.cpp.
References lhs, mlir::DataFlowAnalysis::propagateIfChanged(), and rhs.
Referenced by visitCallableOperation(), and mlir::dataflow::LivenessAnalysis::visitOperation().
setAllToExitStates()
void AbstractSparseBackwardDataFlowAnalysis::setAllToExitStates (ArrayRef< AbstractSparseLattice * > lattices) protected
Set the given lattice element(s) at control flow exit point(s) and propagate the update if it chaned.
Definition at line 662 of file SparseAnalysis.cpp.
References setToExitState().
Referenced by mlir::dataflow::SparseBackwardDataFlowAnalysis< StateT >::setAllToExitStates(), and visitCallableOperation().
setToExitState()
virtual void mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::setToExitState (AbstractSparseLattice * lattice) protected pure virtual
Set the given lattice element(s) at control flow exit point(s) and propagate the update if it chaned.
Implemented in mlir::dataflow::SparseBackwardDataFlowAnalysis< StateT >.
Referenced by setAllToExitStates().
visit()
LogicalResult AbstractSparseBackwardDataFlowAnalysis::visit (ProgramPoint * point) override virtual
Visit a program point.
If it is after call operation or an operation with block or region control-flow, then operand lattices are set accordingly. Otherwise, invokes the operation transfer function (visitOperationImpl).
Implements mlir::DataFlowAnalysis.
Definition at line 391 of file SparseAnalysis.cpp.
References mlir::ProgramPoint::getPrevOp(), mlir::ProgramPoint::isBlockStart(), and success().
visitBranchOperand()
virtual void mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitBranchOperand (OpOperand & operand) protected pure virtual
Implemented in mlir::dataflow::LivenessAnalysis.
visitCallableOperation()
LogicalResult AbstractSparseBackwardDataFlowAnalysis::visitCallableOperation (Operation * op, CallableOpInterface callable, ArrayRef< AbstractSparseLattice * > operandLattices) protected virtual
Visits a callable operation.
If all the call sites are known computes the operand lattices of op from the result lattices of all the call sites; otherwise, conservatively marks them as having reached their pessimistic fixpoints. This method can be overridden to, for example, be less conservative and propagate the information even if some call sites are unknown.
Definition at line 570 of file SparseAnalysis.cpp.
References mlir::dataflow::PredecessorState::allPredecessorsKnown(), mlir::dataflow::PredecessorState::getKnownPredecessors(), mlir::DataFlowAnalysis::getOrCreateFor(), mlir::DataFlowAnalysis::getProgramPointAfter(), meet(), result, setAllToExitStates(), and success().
visitCallOperand()
virtual void mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitCallOperand (OpOperand & operand) protected pure virtual
Implemented in mlir::dataflow::LivenessAnalysis.
Referenced by mlir::dataflow::SparseBackwardDataFlowAnalysis< StateT >::visitExternalCall().
visitExternalCallImpl()
virtual void mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitExternalCallImpl (CallOpInterface call, ArrayRef< AbstractSparseLattice * > operandLattices, ArrayRef< const AbstractSparseLattice * > resultLattices) protected pure virtual
The transfer function for calls to external functions.
visitOperationImpl()
virtual LogicalResult mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitOperationImpl (Operation * op, ArrayRef< AbstractSparseLattice * > operandLattices, ArrayRef< const AbstractSparseLattice * > resultLattices) protected pure virtual
The operation transfer function.
Given the result lattices, this function is expected to set the operand lattices.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/SparseAnalysis.h
lib/Analysis/DataFlow/SparseAnalysis.cpp