MLIR: mlir::DataFlowSolver Class Reference
mlir::DataFlowSolver Class Reference
The general data-flow analysis solver.
#include "mlir/Analysis/DataFlowFramework.h"
Public Types
using WorkItem = std::pair<ProgramPoint *, DataFlowAnalysis *>
A work item on the solver queue is a program point, child analysis pair.
Public Member Functions
DataFlowSolver (const DataFlowConfig &config=DataFlowConfig())
template<typename AnalysisT, typename... Args>
AnalysisT * load (Args &&...args)
Load an analysis into the solver. Return the analysis instance.
LogicalResult initializeAndRun (Operation *top, llvm::function_ref< bool(DataFlowAnalysis &)> analysisFilter=nullptr)
Initialize analyses starting from the provided top-level operation and run the analysis until fixpoint.
template<typename StateT, typename AnchorT>
const StateT * lookupState (AnchorT anchor) const
Lookup an analysis state for the given lattice anchor.
template<typename AnchorT>
void eraseState (AnchorT anchor)
Erase any analysis state associated with the given lattice anchor.
void eraseAllStates ()
Erase all analysis states.
template<typename AnchorT, typename... Args>
AnchorT * getLatticeAnchor (Args &&...args)
Get a uniqued lattice anchor instance.
ProgramPoint * getProgramPointBefore (Operation *op)
Get a uniqued program point instance.
ProgramPoint * getProgramPointBefore (Block *block)
ProgramPoint * getProgramPointAfter (Operation *op)
ProgramPoint * getProgramPointAfter (Block *block)
void enqueue (WorkItem item)
Push a work item onto the worklist.
template<typename StateT, typename AnchorT>
StateT * getOrCreateState (AnchorT anchor)
Get the state associated with the given lattice anchor.
template<typename StateT>
LatticeAnchor getLeaderAnchorOrSelf (LatticeAnchor latticeAnchor) const
Get leader lattice anchor in equivalence lattice anchor group, return input lattice anchor if input not found in equivalece lattice anchor group.
template<typename StateT, typename AnchorT>
void unionLatticeAnchors (AnchorT anchor, AnchorT other)
Union input anchors under the given state.
template<typename StateT>
bool isEquivalent (LatticeAnchor lhs, LatticeAnchor rhs) const
Return given lattice is equivalent on given state.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to an analysis state if it changed by pushing dependent work items to the back of the queue.
const DataFlowConfig & getConfig () const
Get the configuration of the solver.
Friends
class DataFlowAnalysis
Allow the base child analysis class to access the internals of the solver.
Detailed Description
The general data-flow analysis solver.
This class is responsible for orchestrating child data-flow analyses, running the fixed-point iteration algorithm, managing analysis state and lattice anchor memory, and tracking dependencies between analyses, lattice anchor, and analysis states.
Steps to run a data-flow analysis:
Load and initialize children analyses. Children analyses are instantiated in the solver and initialized, building their dependency relations.
Configure and run the analysis. The solver invokes the children analyses according to their dependency relations until a fixed point is reached.
Query analysis state results from the solver.
Steps to re-run a data-flow analysis when IR changes:
Erase all analysis states as they are no longer valid.
Re-run the analysis using initializeAndRun.
TODO: Optimize the internal implementation of the solver.
Definition at line 324 of file DataFlowFramework.h.
Member Typedef Documentation
WorkItem
using mlir::DataFlowSolver::WorkItem = std::pair<ProgramPoint *, DataFlowAnalysis *>
A work item on the solver queue is a program point, child analysis pair.
Each item is processed by invoking the child analysis at the program point.
Definition at line 410 of file DataFlowFramework.h.
Constructor & Destructor Documentation
DataFlowSolver()
mlir::DataFlowSolver::DataFlowSolver (const DataFlowConfig & config = DataFlowConfig()) inline explicit
Definition at line 326 of file DataFlowFramework.h.
Member Function Documentation
enqueue()
void mlir::DataFlowSolver::enqueue (WorkItem item) inline
Push a work item onto the worklist.
Definition at line 412 of file DataFlowFramework.h.
Referenced by mlir::AnalysisState::onUpdate(), mlir::dataflow::AbstractSparseLattice::onUpdate(), and mlir::dataflow::Executable::onUpdate().
eraseAllStates()
void mlir::DataFlowSolver::eraseAllStates () inline
Erase all analysis states.
Definition at line 366 of file DataFlowFramework.h.
eraseState()
template<typename AnchorT> void mlir::DataFlowSolver::eraseState (AnchorT anchor)
Erase any analysis state associated with the given lattice anchor.
Definition at line 553 of file DataFlowFramework.h.
Referenced by mlir::dataflow::maybeReplaceWithConstant().
getConfig()
const DataFlowConfig & mlir::DataFlowSolver::getConfig () const inline
Get the configuration of the solver.
Definition at line 440 of file DataFlowFramework.h.
getLatticeAnchor()
template<typename AnchorT, typename... Args> AnchorT * mlir::DataFlowSolver::getLatticeAnchor (Args &&... args) inline
Get a uniqued lattice anchor instance.
If one is not present, it is created with the provided arguments.
Definition at line 374 of file DataFlowFramework.h.
getLeaderAnchorOrSelf()
template<typename StateT> LatticeAnchor mlir::DataFlowSolver::getLeaderAnchorOrSelf (LatticeAnchor latticeAnchor) const
Get leader lattice anchor in equivalence lattice anchor group, return input lattice anchor if input not found in equivalece lattice anchor group.
Definition at line 749 of file DataFlowFramework.h.
References mlir::TypeID::get().
Referenced by getOrCreateState(), and lookupState().
getOrCreateState()
template<typename StateT, typename AnchorT> StateT * mlir::DataFlowSolver::getOrCreateState (AnchorT anchor)
Get the state associated with the given lattice anchor.
If it does not exist, create an uninitialized state.
Definition at line 764 of file DataFlowFramework.h.
References mlir::TypeID::get(), and getLeaderAnchorOrSelf().
Referenced by copyIntegerRange().
getProgramPointAfter() [1/2]
ProgramPoint * mlir::DataFlowSolver::getProgramPointAfter (Block * block) inline
Definition at line 402 of file DataFlowFramework.h.
References mlir::Block::end().
getProgramPointAfter() [2/2]
ProgramPoint * mlir::DataFlowSolver::getProgramPointAfter (Operation * op) inline
Definition at line 393 of file DataFlowFramework.h.
References mlir::Operation::getBlock().
Referenced by mlir::dataflow::AbstractSparseLattice::onUpdate(), and mlir::dataflow::Executable::onUpdate().
getProgramPointBefore() [1/2]
ProgramPoint * mlir::DataFlowSolver::getProgramPointBefore (Block * block) inline
Definition at line 388 of file DataFlowFramework.h.
References mlir::Block::begin().
getProgramPointBefore() [2/2]
ProgramPoint * mlir::DataFlowSolver::getProgramPointBefore (Operation * op) inline
Get a uniqued program point instance.
Definition at line 379 of file DataFlowFramework.h.
References mlir::Operation::getBlock().
Referenced by mlir::dataflow::Executable::onUpdate().
initializeAndRun()
LogicalResult DataFlowSolver::initializeAndRun (Operation * top, llvm::function_ref< bool(DataFlowAnalysis &)> analysisFilter = nullptr)
Initialize analyses starting from the provided top-level operation and run the analysis until fixpoint.
An optional analysisFilter predicate restricts which analyses are initialized. When no filter is given every loaded analysis is (re-)initialized. The fixpoint loop always processes all enqueued work items regardless of the filter.
Definition at line 112 of file DataFlowFramework.cpp.
References DATAFLOW_DEBUG, DataFlowAnalysis, mlir::Operation::hasTrait(), and success().
Referenced by mlir::xegpu::runContiguityAnalysis().
isEquivalent()
template<typename StateT> bool mlir::DataFlowSolver::isEquivalent (LatticeAnchor lhs, LatticeAnchor rhs) const
Return given lattice is equivalent on given state.
Definition at line 780 of file DataFlowFramework.h.
References mlir::TypeID::get(), lhs, and rhs.
load()
template<typename AnalysisT, typename... Args> AnalysisT * mlir::DataFlowSolver::load (Args &&... args)
Load an analysis into the solver. Return the analysis instance.
Definition at line 738 of file DataFlowFramework.h.
References mlir::get(), and mlir::TypeID::get().
Referenced by mlir::dataflow::loadBaselineAnalyses(), and mlir::xegpu::runContiguityAnalysis().
lookupState()
template<typename StateT, typename AnchorT> const StateT * mlir::DataFlowSolver::lookupState (AnchorT anchor) const inline
Lookup an analysis state for the given lattice anchor.
Returns null if one does not exist.
Definition at line 349 of file DataFlowFramework.h.
References mlir::TypeID::get(), and getLeaderAnchorOrSelf().
Referenced by copyIntegerRange(), getMaybeConstantValue(), mlir::dataflow::maybeReplaceWithConstant(), replaceWithConstant(), and mlir::dataflow::staticallyNonNegative().
propagateIfChanged()
void DataFlowSolver::propagateIfChanged (AnalysisState * state, ChangeResult changed)
Propagate an update to an analysis state if it changed by pushing dependent work items to the back of the queue.
This should only be used when DataFlowSolver is running. Otherwise, the solver won't process the work items.
Definition at line 161 of file DataFlowFramework.cpp.
References mlir::AnalysisState::anchor, mlir::Change, DATAFLOW_DEBUG, and mlir::AnalysisState::onUpdate().
unionLatticeAnchors()
template<typename StateT, typename AnchorT> void mlir::DataFlowSolver::unionLatticeAnchors (AnchorT anchor, AnchorT other)
Union input anchors under the given state.
Definition at line 792 of file DataFlowFramework.h.
References mlir::TypeID::get().
Friends And Related Symbol Documentation
DataFlowAnalysis
friend class DataFlowAnalysis friend
Allow the base child analysis class to access the internals of the solver.
Definition at line 473 of file DataFlowFramework.h.
References DataFlowAnalysis.
Referenced by DataFlowAnalysis, and initializeAndRun().
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlowFramework.h
lib/Analysis/DataFlowFramework.cpp