MLIR: mlir::Location Class Reference
mlir::Location Class Reference
This class defines the main interface for locations in MLIR and acts as a non-nullable wrapper around a LocationAttr.
#include "mlir/IR/Location.h"
Public Member Functions
Location (LocationAttr loc)
Location (const LocationAttr::ImplType *impl)
MLIRContext * getContext () const
Return the context this location is uniqued in.
operator LocationAttr () const
Access the impl location attribute.
LocationAttr * operator-> () const
template<typename U >
bool isa () const
Type casting utilities on the underlying location.
template<typename U >
U dyn_cast () const
template<typename U >
U cast () const
bool operator== (Location rhs) const
Comparison operators.
bool operator!= (Location rhs) const
void print (raw_ostream &os) const
Print the location.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Static Public Member Functions
static Location getFromOpaquePointer (const void *pointer)
static bool classof (Attribute attr)
Support llvm style casting.
Protected Attributes
LocationAttr impl
The internal backing location attribute.
Friends
::llvm::hash_code hash_value (Location arg)
Detailed Description
This class defines the main interface for locations in MLIR and acts as a non-nullable wrapper around a LocationAttr.
Definition at line 63 of file Location.h.
Constructor & Destructor Documentation
Location() [1/2]
mlir::Location::Location (LocationAttr loc) inline
Definition at line 65 of file Location.h.
Location() [2/2]
mlir::Location::Location (const LocationAttr::ImplType * impl) inline
Definition at line 68 of file Location.h.
Member Function Documentation
cast()
template<typename U > U mlir::Location::cast () const inline
Definition at line 92 of file Location.h.
classof()
static bool mlir::Location::classof (Attribute attr) inline static
Support llvm style casting.
Definition at line 113 of file Location.h.
dump()
void mlir::Location::dump () const inline
Definition at line 102 of file Location.h.
dyn_cast()
template<typename U > U mlir::Location::dyn_cast () const inline
Definition at line 87 of file Location.h.
getAsOpaquePointer()
const void* mlir::Location::getAsOpaquePointer () const inline
Methods for supporting PointerLikeTypeTraits.
Definition at line 107 of file Location.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::Location >::getAsVoidPointer().
getContext()
MLIRContext* mlir::Location::getContext () const inline
Return the context this location is uniqued in.
Definition at line 73 of file Location.h.
Referenced by buildMax(), buildMin(), and mlir::Operation::create().
getFromOpaquePointer()
static Location mlir::Location::getFromOpaquePointer (const void * pointer) inline static
Definition at line 108 of file Location.h.
Referenced by llvm::DenseMapInfo< mlir::Location >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::Location >::getFromVoidPointer(), and llvm::DenseMapInfo< mlir::Location >::getTombstoneKey().
isa()
template<typename U > bool mlir::Location::isa () const inline
Type casting utilities on the underlying location.
Definition at line 82 of file Location.h.
operator LocationAttr()
mlir::Location::operator LocationAttr () const inline
Access the impl location attribute.
Definition at line 76 of file Location.h.
References impl.
operator!=()
bool mlir::Location::operator!= (Location rhs) const inline
Definition at line 98 of file Location.h.
operator->()
LocationAttr* mlir::Location::operator-> () const inline
Definition at line 77 of file Location.h.
References impl.
operator==()
bool mlir::Location::operator== (Location rhs) const inline
Comparison operators.
Definition at line 97 of file Location.h.
References impl.
print()
void mlir::Location::print (raw_ostream & os) const inline
Print the location.
Definition at line 101 of file Location.h.
Referenced by mlir::operator<<().
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (Location arg) friend
Definition at line 126 of file Location.h.
Member Data Documentation
impl
LocationAttr mlir::Location::impl protected
The internal backing location attribute.
Definition at line 117 of file Location.h.
Referenced by operator LocationAttr(), operator->(), and operator==().
The documentation for this class was generated from the following file:
include/mlir/IR/Location.h