MLIR: mlir::PassWrapper< PassT, BaseT > Class Template Reference
mlir::PassWrapper< PassT, BaseT > Class Template Reference
This class provides a CRTP wrapper around a base pass class to define several necessary utility methods.
#include "mlir/Pass/Pass.h"
Public Member Functions
~PassWrapper () override=default
Static Public Member Functions
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Member Functions
PassWrapper ()
PassWrapper (const PassWrapper &)=default
PassWrapper & operator= (const PassWrapper &)=delete
PassWrapper (PassWrapper &&)=delete
PassWrapper & operator= (PassWrapper &&)=delete
StringRef getName () const override
Returns the derived pass name.
std::unique_ptr< Pass > clonePass () const override
A clone method to create a copy of this pass.
Detailed Description
template<typename PassT, typename BaseT>
class mlir::PassWrapper< PassT, BaseT >
This class provides a CRTP wrapper around a base pass class to define several necessary utility methods.
This should only be used for passes that are not suitably represented using the declarative pass specification(i.e. tablegen backend).
Definition at line 470 of file Pass.h.
Constructor & Destructor Documentation
~PassWrapper()
template<typename PassT, typename BaseT> mlir::PassWrapper< PassT, BaseT >::~PassWrapper () override default
PassWrapper() [1/3]
template<typename PassT, typename BaseT> mlir::PassWrapper< PassT, BaseT >::PassWrapper () inline protected
Definition at line 479 of file Pass.h.
References mlir::get().
Referenced by operator=(), operator=(), PassWrapper(), and PassWrapper().
PassWrapper() [2/3]
template<typename PassT, typename BaseT> mlir::PassWrapper< PassT, BaseT >::PassWrapper (const PassWrapper< PassT, BaseT > &) protected default
References PassWrapper().
PassWrapper() [3/3]
template<typename PassT, typename BaseT> mlir::PassWrapper< PassT, BaseT >::PassWrapper (PassWrapper< PassT, BaseT > &&) protected delete
References PassWrapper().
Member Function Documentation
classof()
template<typename PassT, typename BaseT> bool mlir::PassWrapper< PassT, BaseT >::classof (const Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 473 of file Pass.h.
References mlir::TypeID::get(), and mlir::Pass::getTypeID().
clonePass()
template<typename PassT, typename BaseT> std::unique_ptr< Pass > mlir::PassWrapper< PassT, BaseT >::clonePass () const inline override protected
A clone method to create a copy of this pass.
Definition at line 489 of file Pass.h.
getName()
template<typename PassT, typename BaseT> StringRef mlir::PassWrapper< PassT, BaseT >::getName () const inline override protected
Returns the derived pass name.
Definition at line 486 of file Pass.h.
operator=() [1/2]
template<typename PassT, typename BaseT> PassWrapper & mlir::PassWrapper< PassT, BaseT >::operator= (const PassWrapper< PassT, BaseT > &) protected delete
References PassWrapper().
operator=() [2/2]
template<typename PassT, typename BaseT> PassWrapper & mlir::PassWrapper< PassT, BaseT >::operator= (PassWrapper< PassT, BaseT > &&) protected delete
References PassWrapper().
The documentation for this class was generated from the following file:
include/mlir/Pass/Pass.h