MLIR: mlir::ExecutionEngine Class Reference
mlir::ExecutionEngine Class Reference
JIT-backed execution engine for MLIR.
#include "mlir/ExecutionEngine/ExecutionEngine.h"
Classes
struct Argument
Trait that defines how a given type is passed to the JIT code.
struct Argument< Result< T > >
struct Result
Tag to wrap an output parameter when invoking a jitted function.
Public Types
using LibraryInitFn = void (*)(llvm::StringMap<void *> &)
Function type for init functions of shared libraries.
using LibraryDestroyFn = void (*)()
Function type for destroy functions of shared libraries.
Public Member Functions
ExecutionEngine (bool enableObjectDump, bool enableGDBNotificationListener, bool enablePerfNotificationListener)
~ExecutionEngine ()
llvm::Expected< void(*)(void **)> lookupPacked (StringRef name) const
Looks up a packed-argument function wrapping the function with the given name and returns a pointer to it.
llvm::Expected< void * > lookup (StringRef name) const
Looks up the original function with the given name and returns a pointer to it.
llvm::Error invokePacked (StringRef name, MutableArrayRef< void * > args={})
Invokes the function with the given name passing it the list of opaque pointers to the actual arguments.
template<typename... Args>
llvm::Error invoke (StringRef funcName, Args... args)
Invokes the function with the given name passing it the list of arguments by value.
void dumpToObjectFile (StringRef filename)
Dump object code to output file filename.
void registerSymbols (llvm::function_ref< llvm::orc::SymbolMap(llvm::orc::MangleAndInterner)> symbolMap)
Register symbols with this ExecutionEngine.
void initialize ()
Initialize the ExecutionEngine.
Static Public Member Functions
static llvm::Expected< std::unique_ptr< ExecutionEngine > > create (Operation *op, const ExecutionEngineOptions &options={}, std::unique_ptr< llvm::TargetMachine > tm=nullptr)
Creates an execution engine for the given MLIR IR.
template<typename T>
static Result< T > result (T &t)
Helper function to wrap an output operand when using ExecutionEngine::invoke.
static void setupTargetTripleAndDataLayout (llvm::Module *llvmModule, llvm::TargetMachine *tm)
Set the target triple and the data layout for the input module based on the input TargetMachine.
Static Public Attributes
static constexpr const char *const kLibraryInitFnName
Name of init functions of shared libraries.
static constexpr const char *const kLibraryDestroyFnName
Name of destroy functions of shared libraries.
Detailed Description
JIT-backed execution engine for MLIR.
Assumes the IR can be converted to LLVM IR. For each function, creates a wrapper function with the fixed interface
void _mlir_funcName(void **)
where the only argument is interpreted as a list of pointers to the actual arguments of the function, followed by a pointer to the result. This allows the engine to provide the caller with a generic function pointer that can be used to invoke the JIT-compiled function.
Definition at line 114 of file ExecutionEngine.h.
Member Typedef Documentation
LibraryDestroyFn
using mlir::ExecutionEngine::LibraryDestroyFn = void (*)()
Function type for destroy functions of shared libraries.
Definition at line 135 of file ExecutionEngine.h.
LibraryInitFn
using mlir::ExecutionEngine::LibraryInitFn = void (*)(llvm::StringMap<void *> &)
Function type for init functions of shared libraries.
The library may provide a list of symbols that it wants to make available to code run by the ExecutionEngine. If the two functions are not defined, only symbols with public visibility are available to the executed code.
Definition at line 132 of file ExecutionEngine.h.
Constructor & Destructor Documentation
ExecutionEngine()
ExecutionEngine::ExecutionEngine (bool enableObjectDump, bool enableGDBNotificationListener, bool enablePerfNotificationListener)
Definition at line 201 of file ExecutionEngine.cpp.
References nullptr.
~ExecutionEngine()
ExecutionEngine::~ExecutionEngine ()
Definition at line 219 of file ExecutionEngine.cpp.
Member Function Documentation
create()
Expected< std::unique_ptr< ExecutionEngine > > ExecutionEngine::create (Operation * op, const ExecutionEngineOptions & options = {}, std::unique_ptr< llvm::TargetMachine > tm = nullptr) static
Creates an execution engine for the given MLIR IR.
If TargetMachine is not provided, default TM is created (i.e. ignoring any command line flags that could affect the set-up).
Definition at line 231 of file ExecutionEngine.cpp.
References create(), mlir::Region::getOps(), mlir::Operation::getRegion(), kLibraryDestroyFnName, kLibraryInitFnName, makeStringError(), options, packFunctionArguments(), setupTargetTripleAndDataLayout(), and mlir::translateModuleToLLVMIR().
Referenced by compileAndExecute(), create(), and mlirExecutionEngineCreate().
dumpToObjectFile()
void ExecutionEngine::dumpToObjectFile (StringRef filename)
Dump object code to output file filename.
Definition at line 101 of file ExecutionEngine.cpp.
References lookupPacked(), and result().
initialize()
void ExecutionEngine::initialize ()
Initialize the ExecutionEngine.
Global constructors specified by llvm.mlir.global_ctors will be run. One common scenario is that kernel binary compiled from gpu.module gets loaded during initialization. Make sure all symbols are resolvable before initialization by calling registerSymbols or including shared libraries.
Definition at line 449 of file ExecutionEngine.cpp.
Referenced by invokePacked().
invoke()
template<typename... Args> llvm::Error mlir::ExecutionEngine::invoke (StringRef funcName, Args... args) inline
Invokes the function with the given name passing it the list of arguments by value.
Function result can be obtain through output parameter using the Result wrapper defined above. For example:
func @foo(%arg0 : i32) -> i32 attributes { llvm.emit_c_interface }
can be invoked:
int32_t result = 0;
llvm::Error error = jit->invoke("foo", 42,
                                result(result));
Definition at line 206 of file ExecutionEngine.h.
References invokePacked(), and mlir::ExecutionEngine::Argument< T >::pack().
invokePacked()
Error ExecutionEngine::invokePacked (StringRef name, MutableArrayRef< void * > args = {})
Invokes the function with the given name passing it the list of opaque pointers to the actual arguments.
Definition at line 436 of file ExecutionEngine.cpp.
References mlir::Error, initialize(), and lookupPacked().
Referenced by invoke().
lookup()
Expected< void * > ExecutionEngine::lookup (StringRef name) const
Looks up the original function with the given name and returns a pointer to it.
This is not necesarily a packed function. Propagates errors in case of failure.
Definition at line 414 of file ExecutionEngine.cpp.
References makeStringError().
Referenced by lookupPacked().
lookupPacked()
Expected< void(*)(void **)> ExecutionEngine::lookupPacked (StringRef name) const
Looks up a packed-argument function wrapping the function with the given name and returns a pointer to it.
Propagates errors in case of failure.
Definition at line 407 of file ExecutionEngine.cpp.
References lookup(), lookupPacked(), makePackedFunctionName(), and result().
Referenced by dumpToObjectFile(), invokePacked(), and lookupPacked().
registerSymbols()
void ExecutionEngine::registerSymbols (llvm::function_ref< llvm::orc::SymbolMap(llvm::orc::MangleAndInterner)> symbolMap)
Register symbols with this ExecutionEngine.
Definition at line 123 of file ExecutionEngine.cpp.
result()
template<typename T> Result< T > mlir::ExecutionEngine::result (T & t) inline static
Helper function to wrap an output operand when using ExecutionEngine::invoke.
Definition at line 181 of file ExecutionEngine.h.
Referenced by dumpToObjectFile(), lookupPacked(), mlir::ExecutionEngine::Argument< Result< T > >::pack(), and mlir::ExecutionEngine::Result< T >::Result().
setupTargetTripleAndDataLayout()
void ExecutionEngine::setupTargetTripleAndDataLayout (llvm::Module * llvmModule, llvm::TargetMachine * tm) static
Set the target triple and the data layout for the input module based on the input TargetMachine.
This is implicitly done when creating the engine.
Definition at line 131 of file ExecutionEngine.cpp.
Referenced by create().
Member Data Documentation
kLibraryDestroyFnName
const char* const mlir::ExecutionEngine::kLibraryDestroyFnName static constexpr
Initial value:
=
      "__mlir_execution_engine_destroy"
Name of destroy functions of shared libraries.
If a library provides a function with this name and the one of the init function, this function is called upon destructing the ExecutionEngine.
Definition at line 125 of file ExecutionEngine.h.
Referenced by create().
kLibraryInitFnName
const char* const mlir::ExecutionEngine::kLibraryInitFnName static constexpr
Initial value:
=
      "__mlir_execution_engine_init"
Name of init functions of shared libraries.
If a library provides a function with this name and the one of the destroy function, this function is called upon loading the library.
Definition at line 119 of file ExecutionEngine.h.
Referenced by create().
The documentation for this class was generated from the following files:
include/mlir/ExecutionEngine/ExecutionEngine.h
lib/ExecutionEngine/ExecutionEngine.cpp