MLIR: mlir::HasDefaultDLTIDataLayout< ConcreteOp > Class Template Reference
mlir::HasDefaultDLTIDataLayout< ConcreteOp > Class Template Reference
Trait to be used by operations willing to use the implementation of the data layout interfaces provided by the Target dialect.
#include "mlir/Dialect/DLTI/Traits.h"
Public Member Functions
DataLayoutSpecInterface getDataLayoutSpec ()
Returns the data layout specification as provided by the Target dialect specification attribute.
TargetSystemSpecInterface getTargetSystemSpec ()
Returns the target system description specification as provided by DLTI dialect.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Verifies that the operation to which this trait is attached is valid for the trait, i.e., that it implements the data layout operation interface.
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteOp, HasDefaultDLTIDataLayout >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteOp>
class mlir::HasDefaultDLTIDataLayout< ConcreteOp >
Trait to be used by operations willing to use the implementation of the data layout interfaces provided by the Target dialect.
Definition at line 27 of file Traits.h.
Member Function Documentation
getDataLayoutSpec()
template<typename ConcreteOp > DataLayoutSpecInterface mlir::HasDefaultDLTIDataLayout< ConcreteOp >::getDataLayoutSpec () inline
Returns the data layout specification as provided by the Target dialect specification attribute.
Definition at line 38 of file Traits.h.
References mlir::impl::getDataLayoutSpec(), and mlir::OpTrait::TraitBase< ConcreteOp, HasDefaultDLTIDataLayout >::getOperation().
getTargetSystemSpec()
template<typename ConcreteOp > TargetSystemSpecInterface mlir::HasDefaultDLTIDataLayout< ConcreteOp >::getTargetSystemSpec () inline
Returns the target system description specification as provided by DLTI dialect.
Definition at line 44 of file Traits.h.
References mlir::OpTrait::TraitBase< ConcreteOp, HasDefaultDLTIDataLayout >::getOperation(), and mlir::impl::getTargetSystemSpec().
verifyTrait()
template<typename ConcreteOp > static LogicalResult mlir::HasDefaultDLTIDataLayout< ConcreteOp >::verifyTrait (Operation * op) inline static
Verifies that the operation to which this trait is attached is valid for the trait, i.e., that it implements the data layout operation interface.
Definition at line 32 of file Traits.h.
References mlir::impl::verifyHasDefaultDLTIDataLayoutTrait().
The documentation for this class was generated from the following file:
include/mlir/Dialect/DLTI/Traits.h