MLIR: mlir::spirv::CooperativeMatrixType Class Reference
mlir::spirv::CooperativeMatrixType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
Type getElementType () const
Scope getScope () const
Returns the scope of the matrix.
uint32_t getRows () const
Returns the number of rows of the matrix.
uint32_t getColumns () const
Returns the number of columns of the matrix.
CooperativeMatrixUseKHR getUse () const
Returns the use parameter of the cooperative matrix.
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, std::optional< StorageClass > storage=std::nullopt)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, std::optional< StorageClass > storage=std::nullopt)
operator ShapedType () const
ArrayRef< int64_t > getShape () const
bool hasRank () const
CooperativeMatrixType cloneWith (std::optional< ArrayRef< int64_t >> shape, Type elementType) const
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static CooperativeMatrixType get (Type elementType, uint32_t rows, uint32_t columns, Scope scope, CooperativeMatrixUseKHR use)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.coopmatrix"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 436 of file SPIRVTypes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
Member Function Documentation
cloneWith()
CooperativeMatrixType mlir::spirv::CooperativeMatrixType::cloneWith (std::optional< ArrayRef< int64_t >> shape, Type elementType) const inline
Definition at line 470 of file SPIRVTypes.h.
References get(), getColumns(), getRows(), getScope(), and getUse().
get()
CooperativeMatrixType CooperativeMatrixType::get (Type elementType, uint32_t rows, uint32_t columns, Scope scope, CooperativeMatrixUseKHR use) static
Definition at line 255 of file SPIRVTypes.cpp.
References mlir::get(), mlir::Type::getContext(), and rows.
Referenced by cloneWith(), and parseCooperativeMatrixType().
getCapabilities()
void CooperativeMatrixType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, std::optional< StorageClass > storage = std::nullopt)
Definition at line 295 of file SPIRVTypes.cpp.
References getElementType().
getColumns()
uint32_t CooperativeMatrixType::getColumns () const
Returns the number of columns of the matrix.
Definition at line 272 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by cloneWith(), and print().
getElementType()
Type CooperativeMatrixType::getElementType () const
Definition at line 263 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by getCapabilities(), getExtensions(), and print().
getExtensions()
void CooperativeMatrixType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, std::optional< StorageClass > storage = std::nullopt)
Definition at line 287 of file SPIRVTypes.cpp.
References getElementType().
getRows()
uint32_t CooperativeMatrixType::getRows () const
Returns the number of rows of the matrix.
Definition at line 267 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by cloneWith(), and print().
getScope()
Scope CooperativeMatrixType::getScope () const
Returns the scope of the matrix.
Definition at line 281 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by cloneWith(), and print().
getShape()
ArrayRef< int64_t > CooperativeMatrixType::getShape () const
Definition at line 277 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
getUse()
CooperativeMatrixUseKHR CooperativeMatrixType::getUse () const
Returns the use parameter of the cooperative matrix.
Definition at line 283 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by cloneWith(), and print().
hasRank()
bool mlir::spirv::CooperativeMatrixType::hasRank () const inline
Definition at line 468 of file SPIRVTypes.h.
operator ShapedType()
mlir::spirv::CooperativeMatrixType::operator ShapedType () const inline
Definition at line 464 of file SPIRVTypes.h.
Member Data Documentation
name
constexpr StringLiteral mlir::spirv::CooperativeMatrixType::name = "spirv.coopmatrix" static constexpr
Definition at line 443 of file SPIRVTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp