MLIR: mlir::tblgen::DagNode Class Reference
mlir::tblgen::DagNode Class Reference
#include "mlir/TableGen/Pattern.h"
Public Member Functions
DagNode (const llvm::DagInit *node)
operator bool () const
StringRef getSymbol () const
Operator & getDialectOp (RecordOperatorMap *mapper) const
int getNumOps () const
int getNumArgs () const
bool isNestedDagArg (unsigned index) const
DagNode getArgAsNestedDag (unsigned index) const
DagLeaf getArgAsLeaf (unsigned index) const
StringRef getArgName (unsigned index) const
bool isReplaceWithValue () const
bool isLocationDirective () const
bool isReturnTypeDirective () const
bool isNativeCodeCall () const
bool isEither () const
bool isVariadic () const
bool isOperation () const
StringRef getNativeCodeTemplate () const
int getNumReturnsOfNativeCode () const
void print (raw_ostream &os) const
Friends
class SymbolInfoMap
Detailed Description
Definition at line 163 of file Pattern.h.
Constructor & Destructor Documentation
DagNode()
mlir::tblgen::DagNode::DagNode (const llvm::DagInit * node) inline explicit
Definition at line 165 of file Pattern.h.
Referenced by getArgAsNestedDag().
Member Function Documentation
getArgAsLeaf()
DagLeaf DagNode::getArgAsLeaf (unsigned index) const
Definition at line 198 of file Pattern.cpp.
References isNestedDagArg().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
getArgAsNestedDag()
DagNode DagNode::getArgAsNestedDag (unsigned index) const
Definition at line 194 of file Pattern.cpp.
References DagNode().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getNumOps().
getArgName()
StringRef DagNode::getArgName (unsigned index) const
Definition at line 203 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
getDialectOp()
Operator & DagNode::getDialectOp (RecordOperatorMap * mapper) const
Definition at line 169 of file Pattern.cpp.
References mlir::tblgen::Operator::getDef(), and inserted().
Referenced by mlir::tblgen::Pattern::getDialectOp(), and mlir::tblgen::Pattern::getSourceRootOp().
getNativeCodeTemplate()
StringRef DagNode::getNativeCodeTemplate () const
Definition at line 153 of file Pattern.cpp.
References isNativeCodeCall().
getNumArgs()
int DagNode::getNumArgs () const
Definition at line 188 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getNumOps().
getNumOps()
int DagNode::getNumOps () const
Definition at line 177 of file Pattern.cpp.
References getArgAsNestedDag(), getNumArgs(), and isOperation().
getNumReturnsOfNativeCode()
int DagNode::getNumReturnsOfNativeCode () const
Definition at line 160 of file Pattern.cpp.
References isNativeCodeCall().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
getSymbol()
StringRef DagNode::getSymbol () const
Definition at line 167 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
isEither()
bool DagNode::isEither () const
Definition at line 222 of file Pattern.cpp.
Referenced by isOperation().
isLocationDirective()
bool DagNode::isLocationDirective () const
Definition at line 212 of file Pattern.cpp.
Referenced by isOperation().
isNativeCodeCall()
bool DagNode::isNativeCodeCall () const
Definition at line 141 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), getNativeCodeTemplate(), getNumReturnsOfNativeCode(), and isOperation().
isNestedDagArg()
bool DagNode::isNestedDagArg (unsigned index) const
Definition at line 190 of file Pattern.cpp.
Referenced by getArgAsLeaf().
isOperation()
bool DagNode::isOperation () const
Definition at line 147 of file Pattern.cpp.
References isEither(), isLocationDirective(), isNativeCodeCall(), isReplaceWithValue(), isReturnTypeDirective(), and isVariadic().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getNumOps().
isReplaceWithValue()
bool DagNode::isReplaceWithValue () const
Definition at line 207 of file Pattern.cpp.
Referenced by isOperation().
isReturnTypeDirective()
bool DagNode::isReturnTypeDirective () const
Definition at line 217 of file Pattern.cpp.
Referenced by isOperation().
isVariadic()
bool DagNode::isVariadic () const
Definition at line 227 of file Pattern.cpp.
Referenced by isOperation().
operator bool()
mlir::tblgen::DagNode::operator bool () const inline
Definition at line 169 of file Pattern.h.
print()
void DagNode::print (raw_ostream & os) const
Definition at line 232 of file Pattern.cpp.
Friends And Related Symbol Documentation
SymbolInfoMap
friend class SymbolInfoMap friend
Definition at line 233 of file Pattern.h.
References SymbolInfoMap.
Referenced by SymbolInfoMap.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp