MLIR: mlir::python::PyOperation Class Reference
mlir::python::PyOperation Class Reference
#include "Bindings/Python/IRModule.h"
Public Member Functions
~PyOperation () override
PyOperation & getOperation () override
Each must provide access to the raw Operation.
void detachFromParent ()
Detaches the operation from its parent block and updates its state accordingly.
operator MlirOperation () const
Gets the backing operation.
MlirOperation get () const
PyOperationRef getRef ()
bool isAttached ()
void setAttached (const nanobind::object &parent=nanobind::object())
void setDetached ()
void checkValid () const
PyBlock getBlock ()
Gets the owning block or raises an exception if the operation has no owning block.
std::optional< PyOperationRef > getParentOperation ()
Gets the parent operation or raises an exception if the operation has no parent.
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirOperation.
nanobind::object createOpView ()
Creates an OpView suitable for this operation.
void erase ()
Erases the underlying MlirOperation, removes its pointer from the parent context's live operations map, and sets the valid bit false.
void setInvalid ()
Invalidate the operation.
nanobind::object clone (const nanobind::object &ip)
Clones this operation.
PyOperation (PyMlirContextRef contextRef, MlirOperation operation)
Public Member Functions inherited from mlir::python::PyOperationBase
virtual ~PyOperationBase ()=default
void print (std::optional< int64_t > largeElementsLimit, std::optional< int64_t > largeResourceLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool useNameLocAsPrefix, bool assumeVerified, nanobind::object fileObject, bool binary, bool skipRegions)
Implements the bound 'print' method and helps with others.
void print (PyAsmState &state, nanobind::object fileObject, bool binary)
nanobind::object getAsm (bool binary, std::optional< int64_t > largeElementsLimit, std::optional< int64_t > largeResourceLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool useNameLocAsPrefix, bool assumeVerified, bool skipRegions)
void writeBytecode (const nanobind::object &fileObject, std::optional< int64_t > bytecodeVersion)
void walk (std::function< MlirWalkResult(MlirOperation)> callback, MlirWalkOrder walkOrder)
void moveAfter (PyOperationBase &other)
Moves the operation before or after the other operation.
void moveBefore (PyOperationBase &other)
bool isBeforeInBlock (PyOperationBase &other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
bool verify ()
Verify the operation.
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyOperationRef forOperation (PyMlirContextRef contextRef, MlirOperation operation, nanobind::object parentKeepAlive=nanobind::object())
Returns a PyOperation for the given MlirOperation, optionally associating it with a parentKeepAlive.
static PyOperationRef createDetached (PyMlirContextRef contextRef, MlirOperation operation, nanobind::object parentKeepAlive=nanobind::object())
Creates a detached operation.
static PyOperationRef parse (PyMlirContextRef contextRef, const std::string &sourceStr, const std::string &sourceName)
Parses a source string (either text assembly or bytecode), creating a detached operation.
static nanobind::object createFromCapsule (nanobind::object capsule)
Creates a PyOperation from the MlirOperation wrapped by a capsule.
static nanobind::object create (std::string_view name, std::optional< std::vector< PyType * >> results, llvm::ArrayRef< MlirValue > operands, std::optional< nanobind::dict > attributes, std::optional< std::vector< PyBlock * >> successors, int regions, DefaultingPyLocation location, const nanobind::object &ip, bool inferType)
Creates an operation. See corresponding python docstring.
Friends
class PyOperationBase
class PySymbolTable
Detailed Description
Definition at line 650 of file IRModule.h.
Constructor & Destructor Documentation
~PyOperation()
PyOperation::~PyOperation () override
Definition at line 1209 of file IRCore.cpp.
References mlir::python::PyMlirContext::clearOperation(), erase(), mlir::python::BaseContextObject::getContext(), and isAttached().
PyOperation()
PyOperation::PyOperation (PyMlirContextRef contextRef, MlirOperation operation)
Definition at line 1206 of file IRCore.cpp.
Member Function Documentation
checkValid()
void PyOperation::checkValid () const
Definition at line 1303 of file IRCore.cpp.
Referenced by mlir::python::PyRegion::checkValid(), mlir::python::PyBlock::checkValid(), mlir::python::PyValue::checkValid(), createOpView(), mlir::python::PySymbolTable::dunderGetItem(), erase(), mlir::python::PySymbolTable::erase(), get(), getBlock(), getCapsule(), getParentOperation(), mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::getVisibility(), mlir::python::PySymbolTable::insert(), mlir::python::PyOperationBase::isBeforeInBlock(), mlir::python::PyOperationBase::moveAfter(), mlir::python::PyOperationBase::moveBefore(), mlir::python::PySymbolTable::replaceAllSymbolUses(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), mlir::python::PyOperationBase::walk(), mlir::python::PySymbolTable::walkSymbolTables(), and mlir::python::PyOperationBase::writeBytecode().
clone()
nb::object PyOperation::clone (const nanobind::object & ip)
Clones this operation.
Definition at line 1636 of file IRCore.cpp.
References createDetached(), createOpView(), mlir::python::BaseContextObject::getContext(), maybeInsertOperation(), and mlirOperationClone().
create()
nb::object PyOperation::create (std::string_view name, std::optional< std::vector< PyType * >> results, llvm::ArrayRef< MlirValue > operands, std::optional< nanobind::dict > attributes, std::optional< std::vector< PyBlock * >> successors, int regions, DefaultingPyLocation location, const nanobind::object & ip, bool inferType) static
Creates an operation. See corresponding python docstring.
Definition at line 1521 of file IRCore.cpp.
Referenced by mlir::python::PyOpView::buildGeneric().
createDetached()
PyOperationRef PyOperation::createDetached (PyMlirContextRef contextRef, MlirOperation operation, nanobind::object parentKeepAlive = nanobind::object()) static
Creates a detached operation.
The operation must not be associated with any existing live operation.
Definition at line 1275 of file IRCore.cpp.
References mlir::python::PyObjectRef< T >::get(), and mlir::python::PyObjectRef< T >::getObject().
Referenced by clone(), and parse().
createFromCapsule()
nb::object PyOperation::createFromCapsule (nanobind::object capsule) static
Creates a PyOperation from the MlirOperation wrapped by a capsule.
Ownership of the underlying MlirOperation is taken by calling this function.
Definition at line 1497 of file IRCore.cpp.
References mlir::python::PyMlirContext::forContext(), forOperation(), mlirOperationGetContext(), mlirOperationIsNull(), mlirPythonCapsuleToOperation(), and mlir::python::PyObjectRef< T >::releaseObject().
createOpView()
nb::object PyOperation::createOpView ()
Creates an OpView suitable for this operation.
Definition at line 1645 of file IRCore.cpp.
References checkValid(), mlir::python::PyOpView::constructDerived(), MlirStringRef::data, mlir::python::PyGlobals::get(), get(), getRef(), MlirStringRef::length, mlir::python::PyGlobals::lookupOperationClass(), mlirIdentifierStr(), and mlirOperationGetName().
Referenced by clone(), mlir::python::PySymbolTable::dunderGetItem(), and mlir::python::PyConcreteOpInterface< ConcreteIface >::getOpView().
detachFromParent()
void mlir::python::PyOperation::detachFromParent () inline
Detaches the operation from its parent block and updates its state accordingly.
Definition at line 675 of file IRModule.h.
References getOperation(), mlirOperationRemoveFromParent(), and setDetached().
erase()
void PyOperation::erase ()
Erases the underlying MlirOperation, removes its pointer from the parent context's live operations map, and sets the valid bit false.
Definition at line 1656 of file IRCore.cpp.
References checkValid(), mlir::python::PyMlirContext::clearOperationAndInside(), mlir::python::BaseContextObject::getContext(), and mlirOperationDestroy().
Referenced by ~PyOperation().
forOperation()
PyOperationRef PyOperation::forOperation (PyMlirContextRef contextRef, MlirOperation operation, nanobind::object parentKeepAlive = nanobind::object()) static
Returns a PyOperation for the given MlirOperation, optionally associating it with a parentKeepAlive.
Definition at line 1255 of file IRCore.cpp.
References mlir::python::PyObjectRef< T >::get(), and mlir::python::PyObjectRef< T >::getObject().
Referenced by mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), mlir::python::PyMlirContext::clearOperationsInside(), createFromCapsule(), mlir::python::PyValue::createFromCapsule(), mlir::python::PySymbolTable::dunderGetItem(), and getParentOperation().
get()
MlirOperation mlir::python::PyOperation::get () const inline
Definition at line 683 of file IRModule.h.
References checkValid().
Referenced by createOpView(), mlir::python::PySymbolTable::erase(), getBlock(), getCapsule(), getOpResultOrValue(), getParentOperation(), mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::getVisibility(), mlir::python::PySymbolTable::insert(), operator MlirOperation(), mlir::python::PyAsmState::PyAsmState(), mlir::python::PySymbolTable::PySymbolTable(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), mlir::python::PyOperationBase::verify(), and mlir::python::PySymbolTable::walkSymbolTables().
getBlock()
PyBlock PyOperation::getBlock ()
Gets the owning block or raises an exception if the operation has no owning block.
Definition at line 1483 of file IRCore.cpp.
References checkValid(), get(), getParentOperation(), mlirBlockIsNull(), and mlirOperationGetBlock().
getCapsule()
nb::object PyOperation::getCapsule ()
Gets a capsule wrapping the void* within the MlirOperation.
Definition at line 1492 of file IRCore.cpp.
References checkValid(), get(), and mlirPythonOperationToCapsule().
getOperation()
PyOperation& mlir::python::PyOperation::getOperation () inline override virtual
Each must provide access to the raw Operation.
Implements mlir::python::PyOperationBase.
Definition at line 653 of file IRModule.h.
Referenced by mlir::python::PyMlirContext::clearOperationsInside(), detachFromParent(), and mlir::python::PyConcreteOpInterface< ConcreteIface >::PyConcreteOpInterface().
getParentOperation()
std::optional< PyOperationRef > PyOperation::getParentOperation ()
Gets the parent operation or raises an exception if the operation has no parent.
Definition at line 1473 of file IRCore.cpp.
References checkValid(), forOperation(), get(), mlir::python::BaseContextObject::getContext(), isAttached(), mlirOperationGetParentOperation(), and mlirOperationIsNull().
Referenced by getBlock().
getRef()
PyOperationRef mlir::python::PyOperation::getRef () inline
Definition at line 688 of file IRModule.h.
Referenced by createOpView(), and mlir::python::PyConcreteOpInterface< ConcreteIface >::getOperationObject().
isAttached()
bool mlir::python::PyOperation::isAttached () inline
Definition at line 692 of file IRModule.h.
Referenced by getParentOperation(), mlir::python::PyInsertionPoint::insert(), and ~PyOperation().
operator MlirOperation()
mlir::python::PyOperation::operator MlirOperation () const inline
Gets the backing operation.
Definition at line 682 of file IRModule.h.
References get().
parse()
PyOperationRef PyOperation::parse (PyMlirContextRef contextRef, const std::string & sourceStr, const std::string & sourceName) static
Parses a source string (either text assembly or bytecode), creating a detached operation.
Definition at line 1291 of file IRCore.cpp.
References createDetached(), mlir::python::PyMlirContext::get(), mlirOperationCreateParse(), mlirOperationIsNull(), mlir::python::PyMlirContext::ErrorCapture::take(), and toMlirStringRef().
setAttached()
void mlir::python::PyOperation::setAttached (const nanobind::object & parent = nanobind::object()) inline
Definition at line 693 of file IRModule.h.
Referenced by mlir::python::PyInsertionPoint::insert().
setDetached()
void mlir::python::PyOperation::setDetached () inline
Definition at line 697 of file IRModule.h.
Referenced by detachFromParent().
setInvalid()
void mlir::python::PyOperation::setInvalid () inline
Invalidate the operation.
Definition at line 736 of file IRModule.h.
Referenced by mlir::python::PyMlirContext::clearOperation().
Friends And Related Function Documentation
PyOperationBase
friend class PyOperationBase friend
Definition at line 760 of file IRModule.h.
PySymbolTable
friend class PySymbolTable friend
Definition at line 761 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp