MLIR: mlir::ComplexStructBuilder Class Reference
mlir::ComplexStructBuilder Class Reference
#include "mlir/Conversion/ComplexToLLVM/ComplexToLLVM.h"
Public Member Functions
Value real (OpBuilder &builder, Location loc)
void setReal (OpBuilder &builder, Location loc, Value real)
Value imaginary (OpBuilder &builder, Location loc)
void setImaginary (OpBuilder &builder, Location loc, Value imaginary)
StructBuilder (Value v)
Construct a helper for the given complex number value.
Public Member Functions inherited from mlir::StructBuilder
StructBuilder (Value v)
Construct a helper for the given value.
operator Value ()
Static Public Member Functions
static ComplexStructBuilder poison (OpBuilder &builder, Location loc, Type type)
Build IR creating an undef value of the complex number type.
Static Public Member Functions inherited from mlir::StructBuilder
static StructBuilder poison (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating a poison value of the descriptor type.
Additional Inherited Members
Protected Member Functions inherited from mlir::StructBuilder
Value extractPtr (OpBuilder &builder, Location loc, unsigned pos) const
Builds IR to extract a value from the struct at position pos.
void setPtr (OpBuilder &builder, Location loc, unsigned pos, Value ptr)
Builds IR to set a value in the struct at position pos.
Protected Attributes inherited from mlir::StructBuilder
Value value
Type structType
Detailed Description
Definition at line 24 of file ComplexToLLVM.h.
Member Function Documentation
imaginary()
Value ComplexStructBuilder::imaginary (OpBuilder & builder, Location loc)
Definition at line 56 of file ComplexToLLVM.cpp.
References mlir::StructBuilder::extractPtr(), and kImaginaryPosInComplexNumberStruct.
Referenced by setImaginary().
poison()
ComplexStructBuilder ComplexStructBuilder::poison (OpBuilder & builder, Location loc, Type type) static
Build IR creating an undef value of the complex number type.
Definition at line 36 of file ComplexToLLVM.cpp.
real()
Value ComplexStructBuilder::real (OpBuilder & builder, Location loc)
Definition at line 47 of file ComplexToLLVM.cpp.
References mlir::StructBuilder::extractPtr(), and kRealPosInComplexNumberStruct.
Referenced by setReal().
setImaginary()
void ComplexStructBuilder::setImaginary (OpBuilder & builder, Location loc, Value imaginary)
Definition at line 51 of file ComplexToLLVM.cpp.
References imaginary(), kImaginaryPosInComplexNumberStruct, and mlir::StructBuilder::setPtr().
setReal()
void ComplexStructBuilder::setReal (OpBuilder & builder, Location loc, Value real)
Definition at line 42 of file ComplexToLLVM.cpp.
References kRealPosInComplexNumberStruct, real(), and mlir::StructBuilder::setPtr().
StructBuilder()
StructBuilder::StructBuilder (Value v) explicit
Construct a helper for the given complex number value.
Definition at line 29 of file StructBuilder.cpp.
The documentation for this class was generated from the following files:
include/mlir/Conversion/ComplexToLLVM/ComplexToLLVM.h
lib/Conversion/ComplexToLLVM/ComplexToLLVM.cpp