MLIR: mlir::DialectAsmParser Class Reference
mlir::DialectAsmParser Class Reference abstract
The DialectAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
#include "mlir/IR/DialectImplementation.h"
Public Member Functions
virtual ~DialectAsmParser ()
virtual InFlightDiagnostic emitError (llvm::SMLoc loc, const Twine &message={})=0
Emit a diagnostic at the specified location and return failure.
virtual Builder & getBuilder () const =0
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
virtual llvm::SMLoc getCurrentLocation ()=0
Get the location of the next token and store it into the argument.
ParseResult getCurrentLocation (llvm::SMLoc *loc)
virtual llvm::SMLoc getNameLoc () const =0
Return the location of the original name token.
virtual Location getEncodedSourceLoc (llvm::SMLoc loc)=0
Re-encode the given source location as an MLIR location and return it.
virtual StringRef getFullSymbolSpec () const =0
Returns the full specification of the symbol being parsed.
virtual ParseResult parseFloat (double &result)=0
Parse a floating point value from the stream.
template<typename IntT >
ParseResult parseInteger (IntT &result)
Parse an integer value from the stream.
virtual OptionalParseResult parseOptionalInteger (APInt &result)=0
Parse an optional integer value from the stream.
template<typename IntT >
OptionalParseResult parseOptionalInteger (IntT &result)
template<typename T , typename... ParamsT>
T getChecked (llvm::SMLoc loc, ParamsT &&... params)
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
template<typename T , typename... ParamsT>
T getChecked (ParamsT &&... params)
A variant of getChecked that uses the result of getNameLoc to emit errors.
virtual ParseResult parseArrow ()=0
Parse a '->' token.
virtual ParseResult parseOptionalArrow ()=0
Parse a '->' token if present.
virtual ParseResult parseLBrace ()=0
Parse a '{' token.
virtual ParseResult parseOptionalLBrace ()=0
Parse a '{' token if present.
virtual ParseResult parseRBrace ()=0
Parse a } token.
virtual ParseResult parseOptionalRBrace ()=0
Parse a } token if present.
virtual ParseResult parseColon ()=0
Parse a : token.
virtual ParseResult parseOptionalColon ()=0
Parse a : token if present.
virtual ParseResult parseComma ()=0
Parse a , token.
virtual ParseResult parseOptionalComma ()=0
Parse a , token if present.
virtual ParseResult parseEqual ()=0
Parse a = token.
virtual ParseResult parseOptionalEqual ()=0
Parse a = token if present.
ParseResult parseString (StringRef *string)
Parse a quoted string token.
virtual ParseResult parseOptionalString (StringRef *string)=0
Parse a quoted string token if present.
ParseResult parseKeyword (StringRef keyword, const Twine &msg="")
Parse a given keyword.
ParseResult parseKeyword (StringRef *keyword)
Parse a keyword into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef keyword)=0
Parse the given keyword if present.
virtual ParseResult parseOptionalKeyword (StringRef *keyword)=0
Parse a keyword, if present, into 'keyword'.
virtual ParseResult parseLess ()=0
Parse a '<' token.
virtual ParseResult parseOptionalLess ()=0
Parse a < token if present.
virtual ParseResult parseGreater ()=0
Parse a '>' token.
virtual ParseResult parseOptionalGreater ()=0
Parse a > token if present.
virtual ParseResult parseLParen ()=0
Parse a (token.
virtual ParseResult parseOptionalLParen ()=0
Parse a (token if present.
virtual ParseResult parseRParen ()=0
Parse a) token.
virtual ParseResult parseOptionalRParen ()=0
Parse a) token if present.
virtual ParseResult parseLSquare ()=0
Parse a [ token.
virtual ParseResult parseOptionalLSquare ()=0
Parse a [ token if present.
virtual ParseResult parseRSquare ()=0
Parse a ] token.
virtual ParseResult parseOptionalRSquare ()=0
Parse a ] token if present.
virtual ParseResult parseOptionalEllipsis ()=0
Parse a ... token if present;.
virtual ParseResult parseOptionalQuestion ()=0
Parse a ? token.
virtual ParseResult parseOptionalStar ()=0
Parse a * token.
virtual ParseResult parseAttribute (Attribute &result, Type type={})=0
Parse an arbitrary attribute and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type={})
Parse an attribute of a specific kind and type.
virtual ParseResult parseAffineMap (AffineMap &map)=0
Parse an affine map instance into 'map'.
virtual ParseResult printIntegerSet (IntegerSet &set)=0
Parse an integer set instance into 'set'.
virtual ParseResult parseType (Type &result)=0
Parse a type.
template<typename TypeType >
ParseResult parseType (TypeType &result)
Parse a type of a specific kind, e.g. a FunctionType.
virtual OptionalParseResult parseOptionalType (Type &result)=0
Parse a type if present.
virtual ParseResult parseDimensionList (SmallVectorImpl< int64_t > &dimensions, bool allowDynamic=true)=0
Parse a 'x' separated dimension list.
virtual ParseResult parseXInDimensionList ()=0
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
Detailed Description
The DialectAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
It has an intentionally high-level API that is designed to reduce/constrain syntax innovation in individual attributes or types.
Definition at line 100 of file DialectImplementation.h.
Constructor & Destructor Documentation
~DialectAsmParser()
DialectAsmParser::~DialectAsmParser () virtual
Definition at line 27 of file Dialect.cpp.
References mlir::DialectRegistry::addDialectInterface(), and DEBUG_TYPE.
Member Function Documentation
emitError()
virtual InFlightDiagnostic mlir::DialectAsmParser::emitError (llvm::SMLoc loc, const Twine & message = {}) pure virtual
Emit a diagnostic at the specified location and return failure.
Referenced by acceptBitWidth(), addNamedOpBuilders(), mlir::pdl::PDLType::classof(), getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), parseAndVerify(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseArrayType(), mlir::Dialect::parseAttribute(), parseCalibratedType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseInterfaceVarABIAttr(), parseMatrixType(), parseOptionalArrayStride(), parsePDLType(), parsePointerType(), parseStorageRange(), parseStorageType(), parseStructMemberDecorations(), parseStructType(), parseTargetEnvAttr(), mlir::Dialect::parseType(), parseUniformType(), parseVerCapExtAttr(), mlir::DataLayoutSpecAttr::print(), and verifyShapeOrExtentTensorOp().
getBuilder()
virtual Builder& mlir::DialectAsmParser::getBuilder () const pure virtual
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
Referenced by getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), parseInterfaceVarABIAttr(), parsePDLType(), parseStorageType(), and parseVerCapExtAttr().
getChecked() [1/2]
template<typename T , typename... ParamsT> T mlir::DialectAsmParser::getChecked (llvm::SMLoc loc, ParamsT &&... params) inline
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
Note that unlike OpBuilder::getType, this method does not implicitly insert a context parameter.
Definition at line 179 of file DialectImplementation.h.
References mlir::emitError().
Referenced by acceptBitWidth(), parseAnyType(), parseCalibratedType(), and parseUniformType().
getChecked() [2/2]
template<typename T , typename... ParamsT> T mlir::DialectAsmParser::getChecked (ParamsT &&... params) inline
A variant of getChecked that uses the result of getNameLoc to emit errors.
Definition at line 186 of file DialectImplementation.h.
References mlir::emitError().
getCurrentLocation() [1/2]
virtual llvm::SMLoc mlir::DialectAsmParser::getCurrentLocation () pure virtual
Get the location of the next token and store it into the argument.
This always succeeds.
Referenced by mlir::pdl::PDLType::classof(), mlir::DataLayoutEntryAttr::parse(), parseAndVerify(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseArrayType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseInterfaceVarABIAttr(), parseKeywordList(), parseMatrixType(), parseOptionalArrayStride(), parsePointerType(), parseStorageRange(), parseStorageType(), parseStructMemberDecorations(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
getCurrentLocation() [2/2]
ParseResult mlir::DialectAsmParser::getCurrentLocation (llvm::SMLoc * loc) inline
Definition at line 115 of file DialectImplementation.h.
References mlir::success().
getEncodedSourceLoc()
virtual Location mlir::DialectAsmParser::getEncodedSourceLoc (llvm::SMLoc loc) pure virtual
Re-encode the given source location as an MLIR location and return it.
Note: This method should only be used when a Location is necessary, as the encoding process is not efficient. In other cases a more suitable alternative should be used, such as the getChecked methods defined below.
getFullSymbolSpec()
virtual StringRef mlir::DialectAsmParser::getFullSymbolSpec () const pure virtual
Returns the full specification of the symbol being parsed.
This allows for using a separate parser if necessary.
Referenced by mlir::Dialect::parseType().
getNameLoc()
virtual llvm::SMLoc mlir::DialectAsmParser::getNameLoc () const pure virtual
Return the location of the original name token.
Referenced by acceptBitWidth(), addNamedOpBuilders(), getOption(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), mlir::Dialect::parseAttribute(), parseCalibratedType(), parsePDLType(), parseStructType(), parseTargetEnvAttr(), mlir::Dialect::parseType(), mlir::DataLayoutSpecAttr::print(), and verifyShapeOrExtentTensorOp().
parseAffineMap()
virtual ParseResult mlir::DialectAsmParser::parseAffineMap (AffineMap & map) pure virtual
Parse an affine map instance into 'map'.
parseArrow()
virtual ParseResult mlir::DialectAsmParser::parseArrow () pure virtual
Parse a '->' token.
parseAttribute() [1/2]
virtual ParseResult mlir::DialectAsmParser::parseAttribute (Attribute & result, Type type = {}) pure virtual
Parse an arbitrary attribute and return it in result.
Referenced by acceptBitWidth(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), and parseTargetEnvAttr().
parseAttribute() [2/2]
template<typename AttrType > ParseResult mlir::DialectAsmParser::parseAttribute (AttrType & result, Type type = {}) inline
Parse an attribute of a specific kind and type.
Definition at line 318 of file DialectImplementation.h.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), map(), mlir::parseAttribute(), mlir::parseType(), and mlir::success().
parseColon()
virtual ParseResult mlir::DialectAsmParser::parseColon () pure virtual
Parse a : token.
Referenced by parseExpressedTypeAndRange(), parseStorageRange(), and parseUniformType().
parseComma()
virtual ParseResult mlir::DialectAsmParser::parseComma () pure virtual
Parse a , token.
Referenced by mlir::DataLayoutEntryAttr::parse(), parseAndVerify< unsigned >(), parseCooperativeMatrixType(), parseInterfaceVarABIAttr(), parsePointerType(), parseStructMemberDecorations(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseDimensionList()
virtual ParseResult mlir::DialectAsmParser::parseDimensionList (SmallVectorImpl< int64_t > & dimensions, bool allowDynamic = true) pure virtual
Parse a 'x' separated dimension list.
This populates the dimension list, using -1 for the ? dimensions if allowDynamic is set and errors out on ? otherwise.
dimension-list ::= (dimension x)* dimension ::= ? | integer
When allowDynamic is not set, this is used to parse:
static-dimension-list ::= (integer x)*
Referenced by parseArrayType(), parseCooperativeMatrixType(), and parseMatrixType().
parseEqual()
virtual ParseResult mlir::DialectAsmParser::parseEqual () pure virtual
Parse a = token.
Referenced by getOption(), and parseOptionalArrayStride().
parseFloat()
virtual ParseResult mlir::DialectAsmParser::parseFloat (double & result) pure virtual
Parse a floating point value from the stream.
Referenced by parseExpressedTypeAndRange(), and parseQuantParams().
parseGreater()
virtual ParseResult mlir::DialectAsmParser::parseGreater () pure virtual
Parse a '>' token.
Referenced by acceptBitWidth(), mlir::pdl::PDLType::classof(), getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), parseAnyType(), parseArrayType(), parseCalibratedType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseImageType(), parseInterfaceVarABIAttr(), parseMatrixType(), parsePointerType(), parseRuntimeArrayType(), parseSampledImageType(), parseStorageRange(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseInteger()
template<typename IntT > ParseResult mlir::DialectAsmParser::parseInteger (IntT & result) inline
Parse an integer value from the stream.
Definition at line 143 of file DialectImplementation.h.
References mlir::emitError(), and mlir::OptionalParseResult::hasValue().
Referenced by getOption(), parseAndVerifyInteger(), parseQuantParams(), parseStorageRange(), parseTargetEnvAttr(), and parseUniformType().
parseKeyword() [1/2]
ParseResult mlir::DialectAsmParser::parseKeyword (StringRef keyword, const Twine & msg = "") inline
Parse a given keyword.
Definition at line 243 of file DialectImplementation.h.
References mlir::emitError(), and mlir::success().
Referenced by addNamedOpBuilders(), getOption(), mlir::vector::CombiningKindAttr::parse(), parseAndVerify(), parseCalibratedType(), parseInterfaceVarABIAttr(), parseKeywordList(), parseOptionalArrayStride(), parsePDLType(), parsePointerType(), parseStructType(), parseTargetEnvAttr(), parseVerCapExtAttr(), mlir::DataLayoutSpecAttr::print(), and verifyShapeOrExtentTensorOp().
parseKeyword() [2/2]
ParseResult mlir::DialectAsmParser::parseKeyword (StringRef * keyword) inline
Parse a keyword into 'keyword'.
Definition at line 251 of file DialectImplementation.h.
References mlir::emitError(), mlir::parseAttribute(), and mlir::success().
parseLBrace()
virtual ParseResult mlir::DialectAsmParser::parseLBrace () pure virtual
Parse a '{' token.
Referenced by parseUniformType().
parseLess()
virtual ParseResult mlir::DialectAsmParser::parseLess () pure virtual
Parse a '<' token.
Referenced by acceptBitWidth(), mlir::pdl::PDLType::classof(), getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), parseAnyType(), parseArrayType(), parseCalibratedType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseImageType(), parseInterfaceVarABIAttr(), parseMatrixType(), parsePointerType(), parseRuntimeArrayType(), parseSampledImageType(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseLParen()
virtual ParseResult mlir::DialectAsmParser::parseLParen () pure virtual
Parse a (token.
Referenced by parseInterfaceVarABIAttr(), and parseStructType().
parseLSquare()
virtual ParseResult mlir::DialectAsmParser::parseLSquare () pure virtual
Parse a [ token.
Referenced by parseKeywordList().
parseOptionalArrow()
virtual ParseResult mlir::DialectAsmParser::parseOptionalArrow () pure virtual
Parse a '->' token if present.
parseOptionalColon()
virtual ParseResult mlir::DialectAsmParser::parseOptionalColon () pure virtual
Parse a : token if present.
Referenced by parseAnyType(), parseQuantParams(), parseTargetEnvAttr(), and parseUniformType().
parseOptionalComma()
virtual ParseResult mlir::DialectAsmParser::parseOptionalComma () pure virtual
Parse a , token if present.
Referenced by getOption(), mlir::DataLayoutSpecAttr::parse(), parseInterfaceVarABIAttr(), parseKeywordList(), parseOptionalArrayStride(), parseStructMemberDecorations(), parseStructType(), and parseUniformType().
parseOptionalEllipsis()
virtual ParseResult mlir::DialectAsmParser::parseOptionalEllipsis () pure virtual
Parse a ... token if present;.
parseOptionalEqual()
virtual ParseResult mlir::DialectAsmParser::parseOptionalEqual () pure virtual
Parse a = token if present.
Referenced by parseStructMemberDecorations().
parseOptionalGreater()
virtual ParseResult mlir::DialectAsmParser::parseOptionalGreater () pure virtual
Parse a > token if present.
Referenced by mlir::DataLayoutSpecAttr::parse(), and parseStructType().
parseOptionalInteger() [1/2]
virtual OptionalParseResult mlir::DialectAsmParser::parseOptionalInteger (APInt & result) pure virtual
Parse an optional integer value from the stream.
Referenced by parseInterfaceVarABIAttr(), and parseStructMemberDecorations().
parseOptionalInteger() [2/2]
template<typename IntT > OptionalParseResult mlir::DialectAsmParser::parseOptionalInteger (IntT & result) inline
Definition at line 155 of file DialectImplementation.h.
References mlir::emitError(), mlir::failed(), mlir::OptionalParseResult::hasValue(), and mlir::success().
parseOptionalKeyword() [1/2]
virtual ParseResult mlir::DialectAsmParser::parseOptionalKeyword (StringRef keyword) pure virtual
Parse the given keyword if present.
Referenced by getOption(), parseStorageType(), parseStructType(), and parseTargetEnvAttr().
parseOptionalKeyword() [2/2]
virtual ParseResult mlir::DialectAsmParser::parseOptionalKeyword (StringRef * keyword) pure virtual
Parse a keyword, if present, into 'keyword'.
parseOptionalLBrace()
virtual ParseResult mlir::DialectAsmParser::parseOptionalLBrace () pure virtual
Parse a '{' token if present.
parseOptionalLess()
virtual ParseResult mlir::DialectAsmParser::parseOptionalLess () pure virtual
Parse a < token if present.
Referenced by parseStorageRange().
parseOptionalLParen()
virtual ParseResult mlir::DialectAsmParser::parseOptionalLParen () pure virtual
Parse a (token if present.
parseOptionalLSquare()
virtual ParseResult mlir::DialectAsmParser::parseOptionalLSquare () pure virtual
Parse a [ token if present.
Referenced by parseStructType().
parseOptionalQuestion()
virtual ParseResult mlir::DialectAsmParser::parseOptionalQuestion () pure virtual
Parse a ? token.
parseOptionalRBrace()
virtual ParseResult mlir::DialectAsmParser::parseOptionalRBrace () pure virtual
Parse a } token if present.
parseOptionalRParen()
virtual ParseResult mlir::DialectAsmParser::parseOptionalRParen () pure virtual
Parse a) token if present.
Referenced by parseStructType().
parseOptionalRSquare()
virtual ParseResult mlir::DialectAsmParser::parseOptionalRSquare () pure virtual
Parse a ] token if present.
Referenced by parseKeywordList(), and parseStructMemberDecorations().
parseOptionalStar()
virtual ParseResult mlir::DialectAsmParser::parseOptionalStar () pure virtual
Parse a * token.
parseOptionalString()
virtual ParseResult mlir::DialectAsmParser::parseOptionalString (StringRef * string) pure virtual
Parse a quoted string token if present.
Referenced by mlir::DataLayoutEntryAttr::parse().
parseOptionalType()
virtual OptionalParseResult mlir::DialectAsmParser::parseOptionalType (Type & result) pure virtual
Parse a type if present.
Referenced by mlir::DataLayoutEntryAttr::parse().
parseRBrace()
virtual ParseResult mlir::DialectAsmParser::parseRBrace () pure virtual
Parse a } token.
Referenced by parseUniformType().
parseRParen()
virtual ParseResult mlir::DialectAsmParser::parseRParen () pure virtual
Parse a) token.
Referenced by parseInterfaceVarABIAttr(), and parseStructType().
parseRSquare()
virtual ParseResult mlir::DialectAsmParser::parseRSquare () pure virtual
Parse a ] token.
Referenced by parseKeywordList(), and parseStructMemberDecorations().
parseString()
ParseResult mlir::DialectAsmParser::parseString (StringRef * string) inline
Parse a quoted string token.
Definition at line 232 of file DialectImplementation.h.
References mlir::emitError(), and mlir::success().
parseType() [1/2]
virtual ParseResult mlir::DialectAsmParser::parseType (Type & result) pure virtual
Parse a type.
Referenced by parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseAnyType(), parseExpressedTypeAndRange(), parseStorageType(), parseStructType(), and parseUniformType().
parseType() [2/2]
template<typename TypeType > ParseResult mlir::DialectAsmParser::parseType (TypeType & result) inline
Parse a type of a specific kind, e.g. a FunctionType.
Definition at line 348 of file DialectImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseType(), and mlir::success().
parseXInDimensionList()
virtual ParseResult mlir::DialectAsmParser::parseXInDimensionList () pure virtual
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
printIntegerSet()
virtual ParseResult mlir::DialectAsmParser::printIntegerSet (IntegerSet & set) pure virtual
Parse an integer set instance into 'set'.
The documentation for this class was generated from the following files:
include/mlir/IR/DialectImplementation.h
lib/IR/Dialect.cpp