MLIR: mlir::OpTrait::TraitBase< ConcreteType, TraitType > Class Template Reference
mlir::OpTrait::TraitBase< ConcreteType, TraitType > Class Template Reference
Helper class for implementing traits.
#include "mlir/IR/OpDefinition.h"
Inherited by mlir::OpTrait::MemRefsNormalizable< AffineDmaWaitOp >, mlir::OpTrait::MemRefsNormalizable< AffineDmaStartOp >, mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, AtLeastNOperands< N >::Impl >, mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, NOperands< N >::Impl >, mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, VariadicOperands >, mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, NRegions< N >::Impl >, mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, AtLeastNRegions< N >::Impl >, mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, VariadicRegions >, mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, AtLeastNResults< N >::Impl >, mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, VariadicResults >, mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, NResults< N >::Impl >, mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, AtLeastNSuccessors< N >::Impl >, mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, NSuccessors< N >::Impl >, mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, VariadicSuccessors >, mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >, mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >, mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >, and mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >.
Protected Member Functions
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType, template< typename > class TraitType>
class mlir::OpTrait::TraitBase< ConcreteType, TraitType >
Helper class for implementing traits.
Clients are not expected to interact with this directly, so its members are all protected.
Definition at line 378 of file OpDefinition.h.
Member Function Documentation
getOperation()
template<typename ConcreteType , template< typename > class TraitType> Operation* mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation () inline protected
Return the ultimate Operation being worked on.
Definition at line 381 of file OpDefinition.h.
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getNumOperands(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getNumRegions(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getNumResults(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getNumSuccessors(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperand(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperands(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperandTypes(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegion(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegions(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResult(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResults(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResultTypes(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessor(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessors(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_begin(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_end(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_type_begin(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_type_end(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::region_begin(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::region_end(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::replaceAllUsesWith(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_begin(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_end(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_type_begin(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_type_end(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::setOperand(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::setSuccessor(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::succ_begin(), and mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::succ_end().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h