MLIR: mlir::query::matcher::DynMatcher Class Reference
mlir::query::matcher::DynMatcher Class Reference
#include "mlir/Query/Matcher/MatchersInternal.h"
Public Types
enum VariadicOperator { AllOf , AnyOf }
Public Member Functions
DynMatcher (MatcherInterface *implementation)
bool match (Operation *op) const
bool match (Operation *op, SetVector< Operation * > &matchedOps) const
void setFunctionName (StringRef name)
bool hasFunctionName () const
StringRef getFunctionName () const
Static Public Member Functions
static std::unique_ptr< DynMatcher > constructVariadic (VariadicOperator Op, std::vector< DynMatcher > innerMatchers)
template<typename MatcherFn >
static std::unique_ptr< DynMatcher > constructDynMatcherFromMatcherFn (MatcherFn &matcherFn)
Detailed Description
Definition at line 119 of file MatchersInternal.h.
Member Enumeration Documentation
VariadicOperator
enum mlir::query::matcher::DynMatcher::VariadicOperator
Enumerator
AllOf
AnyOf
Definition at line 126 of file MatchersInternal.h.
Constructor & Destructor Documentation
DynMatcher()
mlir::query::matcher::DynMatcher::DynMatcher (MatcherInterface * implementation) inline
Definition at line 122 of file MatchersInternal.h.
Member Function Documentation
constructDynMatcherFromMatcherFn()
template<typename MatcherFn > static std::unique_ptr<DynMatcher> mlir::query::matcher::DynMatcher::constructDynMatcherFromMatcherFn (MatcherFn & matcherFn) inline static
Definition at line 152 of file MatchersInternal.h.
Referenced by mlir::query::matcher::internal::matcherMarshallFixedImpl().
constructVariadic()
static std::unique_ptr<DynMatcher> mlir::query::matcher::DynMatcher::constructVariadic (VariadicOperator Op, std::vector< DynMatcher > innerMatchers) inline static
Definition at line 135 of file MatchersInternal.h.
References AllOf, and AnyOf.
Referenced by mlir::query::matcher::VariantMatcher::VariadicOpPayload::getDynMatcher(), and mlir::query::matcher::VariadicOperatorMatcher< Ps >::operator std::unique_ptr< DynMatcher >().
getFunctionName()
StringRef mlir::query::matcher::DynMatcher::getFunctionName () const inline
Definition at line 164 of file MatchersInternal.h.
Referenced by mlir::query::MatchQuery::run().
hasFunctionName()
bool mlir::query::matcher::DynMatcher::hasFunctionName () const inline
Definition at line 163 of file MatchersInternal.h.
Referenced by mlir::query::MatchQuery::run().
match() [1/2]
bool mlir::query::matcher::DynMatcher::match (Operation * op) const inline
Definition at line 157 of file MatchersInternal.h.
Referenced by mlir::query::matcher::internal::allOfVariadicOperator(), mlir::query::matcher::internal::anyOfVariadicOperator(), and mlir::query::matcher::MatchFinder::collectMatches().
match() [2/2]
bool mlir::query::matcher::DynMatcher::match (Operation * op, SetVector< Operation * > & matchedOps) const inline
Definition at line 158 of file MatchersInternal.h.
setFunctionName()
void mlir::query::matcher::DynMatcher::setFunctionName (StringRef name) inline
Definition at line 162 of file MatchersInternal.h.
The documentation for this class was generated from the following file:
include/mlir/Query/Matcher/MatchersInternal.h