MLIR: ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor > Class Reference
ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor > Class Reference
Public Member Functions
ConvInferShapeAdaptor (Conv2DBlockScaledOp::Adaptor adaptor)
void inferInputShape (SmallVectorImpl< int64_t > &outputShape, SmallVectorImpl< int64_t > &inputSpatial)
void inferWeightShape (SmallVectorImpl< int64_t > &outputShape, SmallVectorImpl< int64_t > &weightSpatial)
int64_t getNumSpatialDims () const
int64_t getOutputRank () const
LogicalResult getSpatialParameters (SmallVector< int64_t > &padValues, SmallVector< int64_t > &strideValues, SmallVector< int64_t > &dilationValues)
Additional Inherited Members
Static Protected Member Functions inherited from ConvInferShapeAdaptorBase
static void updateIfDynamic (int64_t &current, int64_t candidate)
Detailed Description
Definition at line 4361 of file TosaOps.cpp.
Constructor & Destructor Documentation
ConvInferShapeAdaptor()
ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::ConvInferShapeAdaptor (Conv2DBlockScaledOp::Adaptor adaptor) inline explicit
Definition at line 4364 of file TosaOps.cpp.
Member Function Documentation
getNumSpatialDims()
int64_t ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::getNumSpatialDims () const inline
Definition at line 4419 of file TosaOps.cpp.
getOutputRank()
int64_t ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::getOutputRank () const inline
Definition at line 4420 of file TosaOps.cpp.
getSpatialParameters()
LogicalResult ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::getSpatialParameters (SmallVector< int64_t > & padValues, SmallVector< int64_t > & strideValues, SmallVector< int64_t > & dilationValues) inline
Definition at line 4422 of file TosaOps.cpp.
References mlir::tosa::getConstShapeValues(), and success().
inferInputShape()
void ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::inferInputShape (SmallVectorImpl< int64_t > & outputShape, SmallVectorImpl< int64_t > & inputSpatial) inline
Definition at line 4367 of file TosaOps.cpp.
References mlir::ShapeAdaptor::getDimSize(), mlir::ShapeAdaptor::hasRank(), and ConvInferShapeAdaptorBase::updateIfDynamic().
inferWeightShape()
void ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::inferWeightShape (SmallVectorImpl< int64_t > & outputShape, SmallVectorImpl< int64_t > & weightSpatial) inline
Definition at line 4393 of file TosaOps.cpp.
References mlir::ShapeAdaptor::getDimSize(), mlir::ShapeAdaptor::hasRank(), and ConvInferShapeAdaptorBase::updateIfDynamic().
The documentation for this class was generated from the following file:
lib/Dialect/Tosa/IR/TosaOps.cpp