MLIR: mlir::ExternalDynamicOpTrait Class Reference
mlir::ExternalDynamicOpTrait Class Reference
Public Member Functions
ExternalDynamicOpTrait (TypeID typeID, MlirDynamicOpTraitCallbacks callbacks, void *userData)
~ExternalDynamicOpTrait ()
LogicalResult verifyTrait (Operation *op) const override
LogicalResult verifyRegionTrait (Operation *op) const override
TypeID getTypeID () const override
Returns the TypeID of the trait.
Public Member Functions inherited from mlir::DynamicOpTrait
virtual ~DynamicOpTrait ()=default
Detailed Description
Definition at line 63 of file ExtensibleDialect.cpp.
Constructor & Destructor Documentation
ExternalDynamicOpTrait()
mlir::ExternalDynamicOpTrait::ExternalDynamicOpTrait (TypeID typeID, MlirDynamicOpTraitCallbacks callbacks, void * userData) inline
Definition at line 65 of file ExtensibleDialect.cpp.
~ExternalDynamicOpTrait()
mlir::ExternalDynamicOpTrait::~ExternalDynamicOpTrait () inline
Definition at line 71 of file ExtensibleDialect.cpp.
Member Function Documentation
getTypeID()
TypeID mlir::ExternalDynamicOpTrait::getTypeID () const inline override virtual
Returns the TypeID of the trait.
It must be equal to the TypeID of corresponding static trait which will be used in hasTrait(TypeID).
Implements mlir::DynamicOpTrait.
Definition at line 83 of file ExtensibleDialect.cpp.
verifyRegionTrait()
LogicalResult mlir::ExternalDynamicOpTrait::verifyRegionTrait (Operation * op) const inline override virtual
Reimplemented from mlir::DynamicOpTrait.
Definition at line 79 of file ExtensibleDialect.cpp.
References unwrap(), and wrap().
verifyTrait()
LogicalResult mlir::ExternalDynamicOpTrait::verifyTrait (Operation * op) const inline override virtual
Reimplemented from mlir::DynamicOpTrait.
Definition at line 76 of file ExtensibleDialect.cpp.
References unwrap(), and wrap().
The documentation for this class was generated from the following file:
lib/CAPI/IR/ExtensibleDialect.cpp