MLIR: mlir::arith::ConstantIndexOp Class Reference
mlir::arith::ConstantIndexOp Class Reference
Specialization of arith.constant op that returns an integer of index type.
#include "mlir/Dialect/Arith/IR/Arith.h"
Public Member Functions
int64_t value ()
Static Public Member Functions
::mlir::TypeID resolveTypeID ()
static void build (OpBuilder &builder, OperationState &result, int64_t value)
Build a constant int op that produces an index.
static ConstantIndexOp create (OpBuilder &builder, Location location, int64_t value)
static ConstantIndexOp create (ImplicitLocOpBuilder &builder, int64_t value)
static bool classof (Operation *op)
Detailed Description
Specialization of arith.constant op that returns an integer of index type.
Definition at line 114 of file Arith.h.
Member Function Documentation
build()
void arith::ConstantIndexOp::build (OpBuilder & builder, OperationState & result, int64_t value) static
Build a constant int op that produces an index.
Definition at line 378 of file ArithOps.cpp.
References mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), result, and value().
Referenced by create().
classof()
bool arith::ConstantIndexOp::classof (Operation * op) static
Definition at line 399 of file ArithOps.cpp.
create() [1/2]
arith::ConstantIndexOp arith::ConstantIndexOp::create (ImplicitLocOpBuilder & builder, int64_t value) static
Definition at line 395 of file ArithOps.cpp.
References create(), mlir::ImplicitLocOpBuilder::getLoc(), and value().
create() [2/2]
arith::ConstantIndexOp arith::ConstantIndexOp::create (OpBuilder & builder, Location location, int64_t value) static
Definition at line 384 of file ArithOps.cpp.
References build(), mlir::OpBuilder::create(), result, and value().
Referenced by allocBuffer(), mlir::transform::gpu::alterGpuLaunch(), HopperBuilder::buildAndInitBarrierInSharedMemory(), buildArithValue(), HopperBuilder::buildBarrierArriveTx(), buildNumReadElements(), HopperBuilder::buildPredicateLoadsOnThread0(), buildPredicates(), HopperBuilder::buildTmaAsyncLoad(), HopperBuilder::buildTryWaitParity(), buildVectorWrite(), calculateGatherOffset(), mlir::collapseParallelLoops(), mlir::sparse_tensor::constantIndex(), mlir::acc::convertACCLoopToSCFFor(), mlir::acc::convertACCLoopToSCFParallel(), create(), createAsyncDispatchFunction(), mlir::linalg::createDestinationPassingStyleInitOperand(), mlir::transform::gpu::createGpuLaunch(), mlir::arm_sme::createLoopOverTileSlices(), createParallelComputeFunction(), mlir::shard::createProcessLinearIndex(), mlir::vector::createReadOrMaskedRead(), mlir::vector::createWriteOrMaskedWrite(), defaultAllocBufferCallBack(), mlir::gpu::WarpDistributionPattern::delinearizeLaneId(), deriveStaticUpperBound(), doAsyncDispatch(), doSequentialDispatch(), dynamicallyExtractSubVector(), dynamicallyInsertSubVector(), emitIsPositiveIndexAssertion(), mlir::sparse_tensor::foreachInSparseConstant(), mlir::xegpu::genCoordinates(), generateCopy(), mlir::vector::getAsValues(), getCollapsedIndices(), mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >::getDescription(), mlir::getOrCreateRanges(), getOrCreateStep(), getValueFromOpFoldResult(), mlir::getValueOrCreateConstantIndexOp(), getZero(), mlir::inferExpandShapeOutputShape(), insertCopyLoops(), mlir::sparse_tensor::insertYieldOp(), mlir::vector::makeVscaleConstantBuilder(), mlir::transform::gpu::mapForallToBlocksImpl(), mlir::transform::gpu::mapNestedForallToThreadsImpl(), FoldLaunchArguments::matchAndRewrite(), mlir::ComposeCollapseOfExpandOp< CollapseOpTy, ExpandOpTy, CastOpTy, DimOpTy, TensorTy >::matchAndRewrite(), mlir::linalg::DecomposePadOpPattern::matchAndRewrite(), mlir::parallelLoopUnrollByFactors(), processParallelLoop(), mlir::affine::promoteIfSingleIteration(), mlir::linalg::promoteSubviewAsNewBuffer(), reifyConstantDim(), reifyOrComputeDynamicSizes(), replaceConstantUsesOf(), replaceOpWithPredicatedOp(), mlir::linalg::rewriteInDestinationPassingStyle(), mlir::linalg::LinalgTilingOptions::setTileSizes(), sliceLoadStoreIndices(), specializeParallelLoopForUnrolling(), vectorizeAsLinalgGeneric(), and vectorizeTensorExtract().
resolveTypeID()
::mlir::TypeID mlir::arith::ConstantIndexOp::resolveTypeID () inline static
Definition at line 117 of file Arith.h.
References mlir::TypeID::get().
value()
int64_t mlir::arith::ConstantIndexOp::value () inline
Definition at line 124 of file Arith.h.
Referenced by build(), create(), and create().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Arith/IR/Arith.h
lib/Dialect/Arith/IR/ArithOps.cpp