MLIR: mlir::dataflow::SparseConstantPropagation Class Reference
mlir::dataflow::SparseConstantPropagation Class Reference
This analysis implements sparse constant propagation, which attempts to determine constant-valued results for operations using constant-valued operands, by speculatively folding operations.
#include "mlir/Analysis/DataFlow/ConstantPropagationAnalysis.h"
Public Member Functions
LogicalResult visitOperation (Operation *op, ArrayRef< const Lattice< ConstantValue > * > operands, ArrayRef< Lattice< ConstantValue > * > results) override
Visit an operation with the lattices of its operands.
void setToEntryState (Lattice< ConstantValue > *lattice) override
Set the given lattice element(s) at control flow entry point(s).
SparseForwardDataFlowAnalysis (DataFlowSolver &solver)
Public Member Functions inherited from mlir::dataflow::SparseForwardDataFlowAnalysis< Lattice< ConstantValue > >
SparseForwardDataFlowAnalysis (DataFlowSolver &solver)
virtual void visitExternalCall (CallOpInterface call, ArrayRef< const Lattice< ConstantValue > * > argumentLattices, ArrayRef< Lattice< ConstantValue > * > resultLattices)
Visit a call operation to an externally defined function given the lattices of its arguments.
virtual void visitNonControlFlowArguments (Operation *op, const RegionSuccessor &successor, ArrayRef< Lattice< ConstantValue > * > argLattices, unsigned firstIndex)
Given an operation with possible region control-flow, the lattices of the operands, and a region successor, compute the lattice values for block arguments that are not accounted for by the branching control flow (ex.
Public Member Functions inherited from mlir::dataflow::AbstractSparseForwardDataFlowAnalysis
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting every owner of an SSA value: all operations and blocks.
LogicalResult visit (ProgramPoint *point) override
Visit a program point.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
virtual void initializeEquivalentLatticeAnchor (Operation *top)
Initialize lattice anchor equivalence class from the provided top-level operation.
Additional Inherited Members
Protected Member Functions inherited from mlir::dataflow::SparseForwardDataFlowAnalysis< Lattice< ConstantValue > >
Lattice< ConstantValue > * getLatticeElement (Value value) override
Get the lattice element for a value.
const Lattice< ConstantValue > * getLatticeElementFor (ProgramPoint *point, Value value)
Get the lattice element for a value and create a dependency on the provided program point.
void setAllToEntryStates (ArrayRef< Lattice< ConstantValue > * > lattices)
Protected Member Functions inherited from mlir::dataflow::AbstractSparseForwardDataFlowAnalysis
AbstractSparseForwardDataFlowAnalysis (DataFlowSolver &solver)
const AbstractSparseLattice * getLatticeElementFor (ProgramPoint *point, Value value)
Get a read-only lattice element for a value and add it as a dependency to a program point.
virtual void setToEntryState (AbstractSparseLattice *lattice)=0
Set the given lattice element(s) at control flow entry point(s).
void setAllToEntryStates (ArrayRef< AbstractSparseLattice * > lattices)
void join (AbstractSparseLattice *lhs, const AbstractSparseLattice &rhs)
Join the lattice element and propagate and update if it changed.
virtual LogicalResult visitCallOperation (CallOpInterface call, ArrayRef< const AbstractSparseLattice * > operandLattices, ArrayRef< AbstractSparseLattice * > resultLattices)
Visits a call operation.
virtual void visitCallableOperation (CallableOpInterface callable, ArrayRef< AbstractSparseLattice * > argLattices)
Visits a callable operation.
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint *point)
Create a dependency between the given analysis state and lattice anchor on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename AnchorT>
void registerAnchorKind ()
Register a custom lattice anchor class.
template<typename AnchorT, typename... Args>
AnchorT * getLatticeAnchor (Args &&...args)
Get or create a custom lattice anchor.
template<typename StateT, typename AnchorT>
void unionLatticeAnchors (AnchorT anchor, AnchorT other)
Union input anchors under the given state.
template<typename StateT, typename AnchorT>
StateT * getOrCreate (AnchorT anchor)
Get the analysis state associated with the lattice anchor.
template<typename StateT, typename AnchorT>
const StateT * getOrCreateFor (ProgramPoint *dependent, AnchorT anchor)
Get a read-only analysis state for the given point and create a dependency on dependent.
ProgramPoint * getProgramPointBefore (Operation *op)
Get a uniqued program point instance.
ProgramPoint * getProgramPointBefore (Block *block)
ProgramPoint * getProgramPointAfter (Operation *op)
ProgramPoint * getProgramPointAfter (Block *block)
const DataFlowConfig & getSolverConfig () const
Return the configuration of the solver used for this analysis.
Detailed Description
This analysis implements sparse constant propagation, which attempts to determine constant-valued results for operations using constant-valued operands, by speculatively folding operations.
When combined with dead-code analysis, this becomes sparse conditional constant propagation (SCCP).
Definition at line 99 of file ConstantPropagationAnalysis.h.
Member Function Documentation
setToEntryState()
void SparseConstantPropagation::setToEntryState (Lattice< ConstantValue > * lattice) override virtual
Set the given lattice element(s) at control flow entry point(s).
Implements mlir::dataflow::SparseForwardDataFlowAnalysis< Lattice< ConstantValue > >.
Definition at line 114 of file ConstantPropagationAnalysis.cpp.
References mlir::dataflow::ConstantValue::getUnknownConstant(), mlir::dataflow::Lattice< ValueT >::join(), and mlir::DataFlowAnalysis::propagateIfChanged().
SparseForwardDataFlowAnalysis()
mlir::dataflow::SparseForwardDataFlowAnalysis< StateT >::SparseForwardDataFlowAnalysis (DataFlowSolver & solver) inline explicit
Definition at line 306 of file SparseAnalysis.h.
visitOperation()
LogicalResult SparseConstantPropagation::visitOperation (Operation * op, ArrayRef< const Lattice< ConstantValue > * > operands, ArrayRef< Lattice< ConstantValue > * > results) override virtual
Visit an operation with the lattices of its operands.
This function is expected to set the lattices of the operation's results.
Implements mlir::dataflow::SparseForwardDataFlowAnalysis< Lattice< ConstantValue > >.
Definition at line 47 of file ConstantPropagationAnalysis.cpp.
References mlir::Operation::fold(), mlir::Operation::getAttrDictionary(), mlir::Operation::getDialect(), mlir::dataflow::SparseForwardDataFlowAnalysis< Lattice< ConstantValue > >::getLatticeElement(), mlir::Operation::getNumOperands(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::dataflow::AbstractSparseForwardDataFlowAnalysis::join(), mlir::dataflow::Lattice< ValueT >::join(), mlir::DataFlowAnalysis::propagateIfChanged(), mlir::dataflow::SparseForwardDataFlowAnalysis< Lattice< ConstantValue > >::setAllToEntryStates(), mlir::Operation::setAttrs(), mlir::Operation::setOperands(), and success().
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/ConstantPropagationAnalysis.h
lib/Analysis/DataFlow/ConstantPropagationAnalysis.cpp