MLIR: mlir::query::QuerySession Class Reference
mlir::query::QuerySession Class Reference
#include "mlir/Query/QuerySession.h"
Public Member Functions
QuerySession (Operation *rootOp, llvm::SourceMgr &sourceMgr, unsigned bufferId, const matcher::Registry &matcherRegistry)
Operation * getRootOp ()
llvm::SourceMgr & getSourceManager () const
unsigned getBufferId ()
const matcher::Registry & getRegistryData () const
Public Attributes
llvm::StringMap< matcher::VariantValue > namedValues
bool terminate = false
Detailed Description
Definition at line 21 of file QuerySession.h.
Constructor & Destructor Documentation
QuerySession()
mlir::query::QuerySession::QuerySession (Operation * rootOp, llvm::SourceMgr & sourceMgr, unsigned bufferId, const matcher::Registry & matcherRegistry) inline
Definition at line 23 of file QuerySession.h.
Member Function Documentation
getBufferId()
unsigned mlir::query::QuerySession::getBufferId () inline
Definition at line 30 of file QuerySession.h.
Referenced by mlir::query::matcher::MatchFinder::printMatch(), and mlir::query::matcher::MatchFinder::printMatch().
getRegistryData()
const matcher::Registry & mlir::query::QuerySession::getRegistryData () const inline
Definition at line 31 of file QuerySession.h.
getRootOp()
Operation * mlir::query::QuerySession::getRootOp () inline
Definition at line 28 of file QuerySession.h.
Referenced by mlir::query::MatchQuery::run().
getSourceManager()
llvm::SourceMgr & mlir::query::QuerySession::getSourceManager () const inline
Definition at line 29 of file QuerySession.h.
Referenced by mlir::query::matcher::MatchFinder::printMatch(), and mlir::query::matcher::MatchFinder::printMatch().
Member Data Documentation
namedValues
llvm::StringMap<matcher::VariantValue> mlir::query::QuerySession::namedValues
Definition at line 33 of file QuerySession.h.
terminate
bool mlir::query::QuerySession::terminate = false
Definition at line 34 of file QuerySession.h.
Referenced by mlir::mlirQueryMain(), and mlir::query::QuitQuery::run().
The documentation for this class was generated from the following file:
include/mlir/Query/QuerySession.h