MLIR: TosaProfileCompliance Class Reference
TosaProfileCompliance Class Reference
#include "mlir/Dialect/Tosa/IR/TosaProfileCompliance.h"
Public Member Functions
TosaProfileCompliance ()
template<typename T>
std::unordered_map< std::string, SmallVector< OpComplianceInfo< T > > > getProfileComplianceMap ()
LogicalResult checkProfile (Operation *op, const tosa::TargetEnv &targetEnv)
LogicalResult checkExtension (Operation *op, const tosa::TargetEnv &targetEnv)
LogicalResult checkInvalid (Operation *op)
template<typename T>
LogicalResult checkProfileOrExtension (Operation *op, const tosa::TargetEnv &targetEnv, const SmallVector< ArrayRef< T > > &specDefinedProfileSet)
bool isSameTypeInfo (TypeInfo a, TypeInfo b)
template<typename T>
OpComplianceInfo< T > findMatchedEntry (Operation *op, SmallVector< OpComplianceInfo< T > > compInfo)
SmallVector< Profile > getCooperativeProfiles (Extension ext)
template<typename T>
SmallVector< StringRef > stringifyProfile (ArrayRef< T > profiles)
template<typename T>
SmallVector< StringRef > stringifyProfile (const SmallVector< ArrayRef< T > > &profileSet)
template<>
OperationProfileComplianceMap getProfileComplianceMap ()
template<>
OperationExtensionComplianceMap getProfileComplianceMap ()
Static Public Member Functions
static llvm::SmallString< 7 > stringifyTypeInfo (const TypeInfo &typeInfo)
Detailed Description
Definition at line 107 of file TosaProfileCompliance.h.
Constructor & Destructor Documentation
TosaProfileCompliance()
TosaProfileCompliance::TosaProfileCompliance () explicit
Definition at line 15 of file TosaProfileCompliance.cpp.
Member Function Documentation
checkExtension()
LogicalResult TosaProfileCompliance::checkExtension (Operation * op, const tosa::TargetEnv & targetEnv)
Definition at line 465 of file TosaProfileCompliance.cpp.
References checkProfileOrExtension(), and success().
checkInvalid()
LogicalResult TosaProfileCompliance::checkInvalid (Operation * op)
Definition at line 474 of file TosaProfileCompliance.cpp.
References mlir::Operation::emitOpError(), ProfileInfoDepot::getInfo(), mlir::Operation::getName(), getProfileComplianceMap(), mlir::OperationName::getStringRef(), isSameTypeInfo(), stringifyTypeInfo(), and success().
checkProfile()
LogicalResult TosaProfileCompliance::checkProfile (Operation * op, const tosa::TargetEnv & targetEnv)
Definition at line 455 of file TosaProfileCompliance.cpp.
References checkProfileOrExtension(), and success().
checkProfileOrExtension()
template<typename T> LogicalResult TosaProfileCompliance::checkProfileOrExtension (Operation * op, const tosa::TargetEnv & targetEnv, const SmallVector< ArrayRef< T > > & specDefinedProfileSet)
Definition at line 345 of file TosaProfileCompliance.cpp.
References allOf, mlir::tosa::TargetEnv::allowsAllOf(), mlir::tosa::TargetEnv::allowsAnyOf(), anyOf, mlir::Operation::emitOpError(), getCooperativeProfiles(), mlir::tosa::TargetEnv::getSpecVersion(), mlir::tosa::TosaSpecificationVersion::isBackwardsCompatibleWith(), stringifyProfile(), mlir::tosa::stringifyVersion(), and success().
Referenced by checkExtension(), and checkProfile().
findMatchedEntry()
template<typename T> OpComplianceInfo< T > TosaProfileCompliance::findMatchedEntry (Operation * op, SmallVector< OpComplianceInfo< T > > compInfo)
Definition at line 536 of file TosaProfileCompliance.cpp.
References ProfileInfoDepot::getInfo(), and isSameTypeInfo().
getCooperativeProfiles()
SmallVector< Profile > TosaProfileCompliance::getCooperativeProfiles (Extension ext) inline
Definition at line 140 of file TosaProfileCompliance.h.
Referenced by checkProfileOrExtension().
getProfileComplianceMap() [1/3]
template<typename T> std::unordered_map< std::string, SmallVector< OpComplianceInfo< T > > > TosaProfileCompliance::getProfileComplianceMap () inline
Definition at line 114 of file TosaProfileCompliance.h.
Referenced by checkInvalid().
getProfileComplianceMap() [2/3]
template<> OperationProfileComplianceMap TosaProfileCompliance::getProfileComplianceMap ()
Definition at line 43 of file TosaProfileCompliance.cpp.
getProfileComplianceMap() [3/3]
template<> OperationExtensionComplianceMap TosaProfileCompliance::getProfileComplianceMap ()
Definition at line 49 of file TosaProfileCompliance.cpp.
isSameTypeInfo()
bool TosaProfileCompliance::isSameTypeInfo (TypeInfo a, TypeInfo b) inline
Definition at line 130 of file TosaProfileCompliance.h.
References b, TypeInfo::bitWidth, and TypeInfo::typeID.
Referenced by checkInvalid(), and findMatchedEntry().
stringifyProfile() [1/2]
template<typename T> SmallVector< StringRef > TosaProfileCompliance::stringifyProfile (ArrayRef< T > profiles)
Definition at line 582 of file TosaProfileCompliance.cpp.
Referenced by checkProfileOrExtension(), and stringifyProfile().
stringifyProfile() [2/2]
template<typename T> SmallVector< StringRef > TosaProfileCompliance::stringifyProfile (const SmallVector< ArrayRef< T > > & profileSet)
Definition at line 594 of file TosaProfileCompliance.cpp.
References stringifyProfile().
stringifyTypeInfo()
llvm::SmallString< 7 > TosaProfileCompliance::stringifyTypeInfo (const TypeInfo & typeInfo) static
Definition at line 607 of file TosaProfileCompliance.cpp.
References TypeInfo::bitWidth, and TypeInfo::typeID.
Referenced by checkInvalid().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Tosa/IR/TosaProfileCompliance.h
lib/Dialect/Tosa/Transforms/TosaProfileCompliance.cpp