MLIR: mlir::pdll::ast::AllResultsMemberAccessExpr Class Reference
mlir::pdll::ast::AllResultsMemberAccessExpr Class Reference
This class represents an instance of MemberAccessExpr that references all results of an operation.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Static Public Member Functions
static StringRef getMemberName ()
Return the member name used for the "all-results" access.
static AllResultsMemberAccessExpr * create (Context &ctx, SMRange loc, const Expr *parentExpr, Type type)
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::MemberAccessExpr
static MemberAccessExpr * create (Context &ctx, SMRange loc, const Expr *parentExpr, StringRef memberName, Type type)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< T, BaseT >
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< T, BaseT >
using Base = NodeBase< T, BaseT >
Public Member Functions inherited from mlir::pdll::ast::MemberAccessExpr
const Expr * getParentExpr () const
Get the parent expression of this access.
StringRef getMemberName () const
Return the name of the member being accessed.
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< T, BaseT >
template<typename... Args>
NodeBase (SMRange loc, Args &&...args)
Detailed Description
This class represents an instance of MemberAccessExpr that references all results of an operation.
Definition at line 484 of file Nodes.h.
Member Function Documentation
classof()
static bool mlir::pdll::ast::AllResultsMemberAccessExpr::classof (const Node * node) inline static
Provide type casting support.
Definition at line 496 of file Nodes.h.
References getMemberName(), and mlir::pdll::ast::MemberAccessExpr::getMemberName().
create()
static AllResultsMemberAccessExpr* mlir::pdll::ast::AllResultsMemberAccessExpr::create (Context & ctx, SMRange loc, const Expr * parentExpr, Type type) inline static
Definition at line 489 of file Nodes.h.
References mlir::pdll::ast::MemberAccessExpr::create(), and getMemberName().
getMemberName()
static StringRef mlir::pdll::ast::AllResultsMemberAccessExpr::getMemberName () inline static
Return the member name used for the "all-results" access.
Definition at line 487 of file Nodes.h.
Referenced by classof(), and create().
The documentation for this class was generated from the following file:
include/mlir/Tools/PDLL/AST/Nodes.h