MLIR: mlir::ResultRange::UseIterator Class Reference
mlir::ResultRange::UseIterator Class Reference final
This class implements a use iterator for a range of operation results.
#include "mlir/IR/ValueRange.h"
Public Member Functions
UseIterator (ResultRange results, bool end=false)
Initialize the UseIterator.
UseIterator & operator++ ()
OpOperand * operator-> () const
OpOperand & operator* () const
bool operator== (const UseIterator &rhs) const
bool operator!= (const UseIterator &rhs) const
Detailed Description
This class implements a use iterator for a range of operation results.
This iterates over all uses of all results within the given result range.
Definition at line 348 of file ValueRange.h.
Constructor & Destructor Documentation
UseIterator()
ResultRange::UseIterator::UseIterator (ResultRange results, bool end = false) explicit
Initialize the UseIterator.
Specify end to return iterator to last use, otherwise this is an iterator to the first use.
Definition at line 599 of file OperationSupport.cpp.
References mlir::ResultRange::ResultRange().
Referenced by operator!=(), and operator==().
Member Function Documentation
operator!=()
bool mlir::ResultRange::UseIterator::operator!= (const UseIterator & rhs) const inline
Definition at line 363 of file ValueRange.h.
References rhs, and UseIterator().
operator*()
OpOperand & mlir::ResultRange::UseIterator::operator* () const inline
Definition at line 360 of file ValueRange.h.
operator++()
ResultRange::UseIterator & ResultRange::UseIterator::operator++ ()
Definition at line 606 of file OperationSupport.cpp.
operator->()
OpOperand * mlir::ResultRange::UseIterator::operator-> () const inline
Definition at line 359 of file ValueRange.h.
operator==()
bool mlir::ResultRange::UseIterator::operator== (const UseIterator & rhs) const inline
Definition at line 362 of file ValueRange.h.
References rhs, and UseIterator().
The documentation for this class was generated from the following files:
include/mlir/IR/ValueRange.h
lib/IR/OperationSupport.cpp