MLIR: mlir::OpPassManager Class Reference
mlir::OpPassManager Class Reference
This class represents a pass manager that runs passes on either a specific operation type, or any isolated operation.
#include "mlir/Pass/PassManager.h"
Public Types
enum class Nesting { Implicit , Explicit }
This enum represents the nesting behavior of the pass manager.
using pass_iterator
Iterator over the passes in this pass manager.
using const_pass_iterator
Public Member Functions
OpPassManager (Nesting nesting=Nesting::Explicit)
Construct a new op-agnostic ("any") pass manager with the given operation type and nesting behavior.
OpPassManager (StringRef name, Nesting nesting=Nesting::Explicit)
Construct a new pass manager with the given anchor operation type and nesting behavior.
OpPassManager (OperationName name, Nesting nesting=Nesting::Explicit)
OpPassManager (OpPassManager &&rhs)
OpPassManager (const OpPassManager &rhs)
~OpPassManager ()
OpPassManager & operator= (const OpPassManager &rhs)
OpPassManager & operator= (OpPassManager &&rhs)
pass_iterator begin ()
pass_iterator end ()
iterator_range< pass_iterator > getPasses ()
const_pass_iterator begin () const
const_pass_iterator end () const
iterator_range< const_pass_iterator > getPasses () const
bool empty () const
Returns true if the pass manager has no passes.
OpPassManager & nest (OperationName nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
OpPassManager & nest (StringRef nestedName)
template<typename OpT>
OpPassManager & nest ()
OpPassManager & nestAny ()
Nest a new op-agnostic ("any") pass manager under this pass manager.
void addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
void clear ()
Clear the pipeline, but not the other options set on this OpPassManager.
template<typename OpT>
void addNestedPass (std::unique_ptr< Pass > pass)
Add the given pass to a nested pass manager for the given operation kind OpT.
size_t size () const
Returns the number of passes held by this manager.
std::optional< OperationName > getOpName (MLIRContext &context) const
Return the operation name that this pass manager operates on, or std::nullopt if this is an op-agnostic pass manager.
std::optional< StringRef > getOpName () const
Return the operation name that this pass manager operates on, or std::nullopt if this is an op-agnostic pass manager.
StringRef getOpAnchorName () const
Return the name used to anchor this pass manager.
detail::OpPassManagerImpl & getImpl ()
Returns the internal implementation instance.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false) const
Prints out the passes of the pass manager as the textual representation of pipelines.
void dump ()
Raw dump of the pass manager to llvm::errs().
void mergeStatisticsInto (OpPassManager &other)
Merge the pass statistics of this class into 'other'.
void getDependentDialects (DialectRegistry &dialects) const
Register dependent dialects for the current pass manager.
void setNesting (Nesting nesting)
Enable or disable the implicit nesting on this particular PassManager.
Nesting getNesting ()
Return the current nesting mode.
Static Public Member Functions
static StringRef getAnyOpAnchorName ()
Return the string name used to anchor op-agnostic pass managers that operate generically on any viable operation.
Friends
class PassManager
Allow access to the constructor.
class Pass
Detailed Description
This class represents a pass manager that runs passes on either a specific operation type, or any isolated operation.
This pass manager can not be run on an operation directly, but must be run either as part of a top-level PassManager(e.g. when constructed via nest calls), or dynamically within a pass by using the Pass::runPipeline API.
Definition at line 46 of file PassManager.h.
Member Typedef Documentation
const_pass_iterator
using mlir::OpPassManager::const_pass_iterator
Initial value:
      llvm::pointee_iterator<ArrayRef<std::unique_ptr<Pass>>::const_iterator>
Definition at line 81 of file PassManager.h.
pass_iterator
using mlir::OpPassManager::pass_iterator
Initial value:
      llvm::pointee_iterator<MutableArrayRef<std::unique_ptr<Pass>>::iterator>
Iterator over the passes in this pass manager.
Definition at line 75 of file PassManager.h.
Member Enumeration Documentation
Nesting
enum class mlir::OpPassManager::Nesting strong
This enum represents the nesting behavior of the pass manager.
Enumerator
Implicit
Implicit nesting behavior.
This allows for adding passes operating on operations different from this pass manager, in which case a new pass manager is implicitly nested for the operation type of the new pass.
Explicit
Explicit nesting behavior.
This requires that any passes added to this pass manager support its operation type.
Definition at line 49 of file PassManager.h.
Constructor & Destructor Documentation
OpPassManager() [1/5]
OpPassManager::OpPassManager (Nesting nesting = Nesting::Explicit)
Construct a new op-agnostic ("any") pass manager with the given operation type and nesting behavior.
This is the same as invoking: OpPassManager(getAnyOpAnchorName(), nesting).
Definition at line 347 of file Pass.cpp.
Referenced by mergeStatisticsInto(), nest(), nest(), nest(), nestAny(), operator=(), operator=(), OpPassManager(), OpPassManager(), mlir::PassManager::PassManager(), mlir::PassManager::PassManager(), and ~OpPassManager().
OpPassManager() [2/5]
OpPassManager::OpPassManager (StringRef name, Nesting nesting = Nesting::Explicit)
Construct a new pass manager with the given anchor operation type and nesting behavior.
Definition at line 349 of file Pass.cpp.
OpPassManager() [3/5]
OpPassManager::OpPassManager (OperationName name, Nesting nesting = Nesting::Explicit)
Definition at line 351 of file Pass.cpp.
OpPassManager() [4/5]
OpPassManager::OpPassManager (OpPassManager && rhs)
Definition at line 353 of file Pass.cpp.
References OpPassManager(), and rhs.
OpPassManager() [5/5]
OpPassManager::OpPassManager (const OpPassManager & rhs)
Definition at line 354 of file Pass.cpp.
References OpPassManager(), and rhs.
~OpPassManager()
OpPassManager::~OpPassManager () default
References OpPassManager(), and rhs.
Member Function Documentation
addNestedPass()
template<typename OpT> void mlir::OpPassManager::addNestedPass (std::unique_ptr< Pass > pass) inline
Add the given pass to a nested pass manager for the given operation kind OpT.
Definition at line 115 of file PassManager.h.
References addPass(), and nest().
Referenced by mlir::tosa::addTosaToLinalgPasses(), mlir::tosa::addTosaToSCFPasses(), mlir::sparse_tensor::buildSparsifier(), and mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation().
addPass()
void OpPassManager::addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
If this pass has a concrete operation type, it must be the same type as this pass manager.
Definition at line 392 of file Pass.cpp.
Referenced by addNestedPass(), mlir::tosa::addTosaToLinalgPasses(), mlir::bufferization::buildBufferDeallocationPipeline(), buildDefaultRegistryFn(), mlir::sparse_tensor::buildSparsifier(), defaultInlinerOptPipeline(), and mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation().
begin() [1/2]
OpPassManager::pass_iterator OpPassManager::begin ()
Definition at line 366 of file Pass.cpp.
Referenced by empty(), getPasses(), and getPasses().
begin() [2/2]
OpPassManager::const_pass_iterator OpPassManager::begin () const
Definition at line 373 of file Pass.cpp.
clear()
void OpPassManager::clear ()
Clear the pipeline, but not the other options set on this OpPassManager.
Definition at line 396 of file Pass.cpp.
dump()
void OpPassManager::dump ()
Raw dump of the pass manager to llvm::errs().
Definition at line 462 of file Pass.cpp.
References printAsTextualPipeline().
empty()
bool mlir::OpPassManager::empty () const inline
Returns true if the pass manager has no passes.
Definition at line 90 of file PassManager.h.
References begin(), and end().
end() [1/2]
OpPassManager::pass_iterator OpPassManager::end ()
Definition at line 369 of file Pass.cpp.
Referenced by empty(), getPasses(), and getPasses().
end() [2/2]
OpPassManager::const_pass_iterator OpPassManager::end () const
Definition at line 376 of file Pass.cpp.
getAnyOpAnchorName()
StringRef mlir::OpPassManager::getAnyOpAnchorName () inline static
Return the string name used to anchor op-agnostic pass managers that operate generically on any viable operation.
Definition at line 137 of file PassManager.h.
Referenced by mlir::detail::OpPassManagerImpl::getOpAnchorName(), and performActions().
getDependentDialects()
void OpPassManager::getDependentDialects (DialectRegistry & dialects) const
Register dependent dialects for the current pass manager.
This is forwarding to every pass in this PassManager, see the documentation for the same method on the Pass class.
Definition at line 474 of file Pass.cpp.
References registerDialectsForPipeline().
Referenced by mlir::detail::OpToOpPassAdaptor::getDependentDialects(), and mlir::PassManager::run().
getImpl()
OpPassManagerImpl & OpPassManager::getImpl ()
Returns the internal implementation instance.
Definition at line 402 of file Pass.cpp.
Referenced by findPassManagerFor(), mlir::PassManager::run(), and mlir::detail::OpToOpPassAdaptor::tryMergeInto().
getNesting()
OpPassManager::Nesting OpPassManager::getNesting ()
Return the current nesting mode.
Definition at line 480 of file Pass.cpp.
Referenced by buildDefaultRegistryFn().
getOpAnchorName()
StringRef OpPassManager::getOpAnchorName () const
Return the name used to anchor this pass manager.
This is either the name of an operation, or the result of getAnyOpAnchorName() in the case of an op-agnostic pass manager.
Definition at line 415 of file Pass.cpp.
Referenced by buildDefaultRegistryFn(), findPassManagerWithAnchor(), mlir::detail::OpToOpPassAdaptor::getAdaptorName(), printAsTextualPipeline(), mlir::PassManager::run(), and mlir::detail::OpToOpPassAdaptor::tryMergeInto().
getOpName() [1/2]
std::optional< StringRef > OpPassManager::getOpName () const
Return the operation name that this pass manager operates on, or std::nullopt if this is an op-agnostic pass manager.
Return the operation name that this pass manager operates on.
Definition at line 405 of file Pass.cpp.
Referenced by mlir::PassManager::run().
getOpName() [2/2]
std::optional< OperationName > OpPassManager::getOpName (MLIRContext & context) const
Return the operation name that this pass manager operates on, or std::nullopt if this is an op-agnostic pass manager.
Return the operation name that this pass manager operates on.
Definition at line 411 of file Pass.cpp.
Referenced by buildDefaultRegistryFn(), and mlir::detail::OpToOpPassAdaptor::tryMergeInto().
getPasses() [1/2]
iterator_range< pass_iterator > mlir::OpPassManager::getPasses () inline
Definition at line 79 of file PassManager.h.
References begin(), and end().
Referenced by mergeStatisticsInto(), performActions(), prepareStatistics(), printResultsAsList(), printResultsAsPipeline(), and registerDialectsForPipeline().
getPasses() [2/2]
iterator_range< const_pass_iterator > mlir::OpPassManager::getPasses () const inline
Definition at line 85 of file PassManager.h.
References begin(), and end().
mergeStatisticsInto()
void OpPassManager::mergeStatisticsInto (OpPassManager & other)
Merge the pass statistics of this class into 'other'.
Definition at line 194 of file PassStatistics.cpp.
References getPasses(), OpPassManager(), and Pass.
nest() [1/3]
template<typename OpT> OpPassManager & mlir::OpPassManager::nest () inline
Definition at line 97 of file PassManager.h.
References nest(), and OpPassManager().
Referenced by addNestedPass(), and nest().
nest() [2/3]
OpPassManager & OpPassManager::nest (OperationName nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
Definition at line 382 of file Pass.cpp.
References OpPassManager().
nest() [3/3]
OpPassManager & OpPassManager::nest (StringRef nestedName)
Definition at line 385 of file Pass.cpp.
References OpPassManager().
nestAny()
OpPassManager & OpPassManager::nestAny ()
Nest a new op-agnostic ("any") pass manager under this pass manager.
Note: This is the same as invoking nest(getAnyOpAnchorName()).
Definition at line 388 of file Pass.cpp.
References OpPassManager().
operator=() [1/2]
OpPassManager & OpPassManager::operator= (const OpPassManager & rhs)
Definition at line 355 of file Pass.cpp.
References OpPassManager(), and rhs.
operator=() [2/2]
OpPassManager & OpPassManager::operator= (OpPassManager && rhs)
Definition at line 359 of file Pass.cpp.
References OpPassManager(), and rhs.
printAsTextualPipeline()
void OpPassManager::printAsTextualPipeline (raw_ostream & os, bool pretty = false) const
Prints out the passes of the pass manager as the textual representation of pipelines.
When pretty is true, the printed pipeline is formatted for readability.
Note: The quality of the string representation depends entirely on the the correctness of per-pass overrides of Pass::printAsTextualPipeline.
Definition at line 452 of file Pass.cpp.
References getOpAnchorName(), and printAsTextualPipeline().
Referenced by dump(), printAsTextualPipeline(), and mlir::PassManager::run().
setNesting()
void OpPassManager::setNesting (Nesting nesting)
Enable or disable the implicit nesting on this particular PassManager.
This will also apply to any newly nested PassManager built from this instance.
Definition at line 478 of file Pass.cpp.
size()
size_t OpPassManager::size () const
Returns the number of passes held by this manager.
Definition at line 399 of file Pass.cpp.
Referenced by mlir::PassManager::run().
Friends And Related Symbol Documentation
Pass
friend class Pass friend
Definition at line 187 of file PassManager.h.
References Pass.
Referenced by mlir::PassManager::enableIRPrinting(), mlir::PassManager::enableIRPrintingToFileTree(), mergeStatisticsInto(), Pass, mlir::PassManager::IRPrinterConfig::printAfterIfEnabled(), mlir::PassManager::IRPrinterConfig::printBeforeIfEnabled(), and mlir::PassManager::IRPrinterConfig::~IRPrinterConfig().
PassManager
friend class PassManager friend
Allow access to the constructor.
Definition at line 186 of file PassManager.h.
References PassManager.
Referenced by mlir::PassManager::on(), and PassManager.
The documentation for this class was generated from the following files:
include/mlir/Pass/PassManager.h
lib/Pass/Pass.cpp
lib/Pass/PassStatistics.cpp