MLIR: ProfileInfoDepot Class Reference
ProfileInfoDepot Class Reference
#include "mlir/Dialect/Tosa/IR/TosaProfileCompliance.h"
Public Member Functions
ProfileInfoDepot (Operation *op)
void addType (Type t)
void addValue (Value v)
SmallVector< TypeInfo > getInfo ()
template<>
LogicalResult populateProfileInfo (tosa::ConcatOp op)
template<>
LogicalResult populateProfileInfo (tosa::AvgPool2dOp op)
template<>
LogicalResult populateProfileInfo (tosa::AvgPool2dAdaptiveOp op)
template<>
LogicalResult populateProfileInfo (tosa::MaxPool2dAdaptiveOp op)
template<>
LogicalResult populateProfileInfo (tosa::Conv2DOp op)
template<>
LogicalResult populateProfileInfo (tosa::Conv3DOp op)
template<>
LogicalResult populateProfileInfo (tosa::TransposeConv2DOp op)
template<>
LogicalResult populateProfileInfo (tosa::DepthwiseConv2DOp op)
template<>
LogicalResult populateProfileInfo (tosa::Conv2DBlockScaledOp op)
template<>
LogicalResult populateProfileInfo (tosa::PadOp op)
template<>
LogicalResult populateProfileInfo (tosa::ReshapeOp op)
template<>
LogicalResult populateProfileInfo (tosa::SliceOp op)
template<>
LogicalResult populateProfileInfo (tosa::TileOp op)
template<>
LogicalResult populateProfileInfo (tosa::TransposeOp op)
template<>
LogicalResult populateProfileInfo (tosa::GatherOp op)
template<>
LogicalResult populateProfileInfo (tosa::RowGatherOp op)
template<>
LogicalResult populateProfileInfo (tosa::RowGatherBlockScaledOp op)
template<>
LogicalResult populateProfileInfo (tosa::ScatterOp op)
template<>
LogicalResult populateProfileInfo (tosa::MulOp op)
template<>
LogicalResult populateProfileInfo (tosa::ResizeOp op)
template<>
LogicalResult populateProfileInfo (tosa::SelectOp op)
template<>
LogicalResult populateProfileInfo (tosa::RescaleOp op)
template<>
LogicalResult populateProfileInfo (tosa::MatMulOp op)
template<>
LogicalResult populateProfileInfo (tosa::MatMulTOp op)
template<>
LogicalResult populateProfileInfo (tosa::VariableOp op)
template<>
LogicalResult populateProfileInfo (tosa::VariableWriteOp op)
template<>
LogicalResult populateProfileInfo (tosa::DimOp op)
Detailed Description
Definition at line 60 of file TosaProfileCompliance.h.
Constructor & Destructor Documentation
ProfileInfoDepot()
ProfileInfoDepot::ProfileInfoDepot (Operation * op) inline
Definition at line 62 of file TosaProfileCompliance.h.
References mlir::Operation::emitOpError().
Member Function Documentation
addType()
void ProfileInfoDepot::addType (Type t) inline
Definition at line 67 of file TosaProfileCompliance.h.
Referenced by populateProfileInfo(), populateProfileInfo(), and populateProfileInfo().
addValue()
void ProfileInfoDepot::addValue (Value v) inline
Definition at line 68 of file TosaProfileCompliance.h.
Referenced by populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), populateProfileInfo(), and populateProfileInfo().
getInfo()
SmallVector< TypeInfo > ProfileInfoDepot::getInfo () inline
Definition at line 69 of file TosaProfileCompliance.h.
Referenced by TosaProfileCompliance::checkInvalid(), and TosaProfileCompliance::findMatchedEntries().
populateProfileInfo() [1/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::AvgPool2dAdaptiveOp op)
Definition at line 82 of file TosaProfileCompliance.cpp.
References addType(), addValue(), and success().
populateProfileInfo() [2/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::AvgPool2dOp op)
Definition at line 71 of file TosaProfileCompliance.cpp.
References addType(), addValue(), and success().
populateProfileInfo() [3/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::ConcatOp op)
Definition at line 64 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [4/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::Conv2DBlockScaledOp op)
Definition at line 135 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [5/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::Conv2DOp op)
Definition at line 112 of file TosaProfileCompliance.cpp.
populateProfileInfo() [6/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::Conv3DOp op)
Definition at line 117 of file TosaProfileCompliance.cpp.
populateProfileInfo() [7/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::DepthwiseConv2DOp op)
Definition at line 129 of file TosaProfileCompliance.cpp.
populateProfileInfo() [8/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::DimOp op)
Definition at line 280 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [9/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::GatherOp op)
Definition at line 181 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [10/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::MatMulOp op)
Definition at line 250 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [11/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::MatMulTOp op)
Definition at line 260 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [12/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::MaxPool2dAdaptiveOp op)
Definition at line 93 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [13/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::MulOp op)
Definition at line 218 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [14/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::PadOp op)
Definition at line 146 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [15/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::RescaleOp op)
Definition at line 241 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [16/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::ReshapeOp op)
Definition at line 161 of file TosaProfileCompliance.cpp.
populateProfileInfo() [17/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::ResizeOp op)
Definition at line 226 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [18/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::RowGatherBlockScaledOp op)
Definition at line 198 of file TosaProfileCompliance.cpp.
References addValue(), result, and success().
populateProfileInfo() [19/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::RowGatherOp op)
Definition at line 189 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [20/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::ScatterOp op)
Definition at line 209 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [21/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::SelectOp op)
Definition at line 233 of file TosaProfileCompliance.cpp.
References addValue(), and success().
populateProfileInfo() [22/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::SliceOp op)
Definition at line 166 of file TosaProfileCompliance.cpp.
populateProfileInfo() [23/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::TileOp op)
Definition at line 171 of file TosaProfileCompliance.cpp.
populateProfileInfo() [24/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::TransposeConv2DOp op)
Definition at line 123 of file TosaProfileCompliance.cpp.
populateProfileInfo() [25/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::TransposeOp op)
Definition at line 176 of file TosaProfileCompliance.cpp.
populateProfileInfo() [26/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::VariableOp op)
Definition at line 268 of file TosaProfileCompliance.cpp.
References addType(), and success().
populateProfileInfo() [27/27]
template<> LogicalResult ProfileInfoDepot::populateProfileInfo (tosa::VariableWriteOp op)
Definition at line 274 of file TosaProfileCompliance.cpp.
References addValue(), and success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Tosa/IR/TosaProfileCompliance.h
lib/Dialect/Tosa/Transforms/TosaProfileCompliance.cpp