MLIR: mlir::python::adaptors::pure_subclass Class Reference
mlir::python::adaptors::pure_subclass Class Reference
Provides a facility like py::class_ for defining a new class in a scope, but this allows extension of an arbitrary Python class, defining methods on it is a similar way.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
pure_subclass (py::handle scope, const char *derivedClassName, const py::object &superClass)
template<typename Func, typename... Extra>
pure_subclass & def (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_property_readonly (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_staticmethod (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_classmethod (const char *name, Func &&f, const Extra &...extra)
py::object get_class () const
Protected Attributes
py::object superClass
py::object thisClass
Detailed Description
Provides a facility like py::class_ for defining a new class in a scope, but this allows extension of an arbitrary Python class, defining methods on it is a similar way.
Classes defined in this way are very similar to if defined in Python in the usual way but use Pybind11 machinery to do it. These are not "real" Pybind11 classes but pure Python classes with no relation to a concrete C++ class.
Derived from a discussion upstream: https://github.com/pybind/pybind11/issues/1193 (plus a fair amount of extra curricular poking) TODO: If this proves useful, see about including it in pybind11.
Definition at line 336 of file PybindAdaptors.h.
Constructor & Destructor Documentation
pure_subclass()
mlir::python::adaptors::pure_subclass::pure_subclass (py::handle scope, const char * derivedClassName, const py::object & superClass) inline
Definition at line 338 of file PybindAdaptors.h.
References superClass, and thisClass.
Referenced by def(), def_classmethod(), def_property_readonly(), def_staticmethod(), mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass(), and mlir::python::adaptors::mlir_value_subclass::mlir_value_subclass().
Member Function Documentation
def()
template<typename Func, typename... Extra> pure_subclass & mlir::python::adaptors::pure_subclass::def (const char * name, Func && f, const Extra &... extra) inline
Definition at line 351 of file PybindAdaptors.h.
References pure_subclass(), and thisClass.
Referenced by mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), and mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass().
def_classmethod()
template<typename Func, typename... Extra> pure_subclass & mlir::python::adaptors::pure_subclass::def_classmethod (const char * name, Func && f, const Extra &... extra) inline
Definition at line 384 of file PybindAdaptors.h.
References pure_subclass(), and thisClass.
def_property_readonly()
template<typename Func, typename... Extra> pure_subclass & mlir::python::adaptors::pure_subclass::def_property_readonly (const char * name, Func && f, const Extra &... extra) inline
Definition at line 360 of file PybindAdaptors.h.
References pure_subclass(), and thisClass.
def_staticmethod()
template<typename Func, typename... Extra> pure_subclass & mlir::python::adaptors::pure_subclass::def_staticmethod (const char * name, Func && f, const Extra &... extra) inline
Definition at line 372 of file PybindAdaptors.h.
References pure_subclass(), and thisClass.
Referenced by mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass(), and mlir::python::adaptors::mlir_value_subclass::mlir_value_subclass().
get_class()
py::object mlir::python::adaptors::pure_subclass::get_class () const inline
Definition at line 396 of file PybindAdaptors.h.
References thisClass.
Member Data Documentation
superClass
py::object mlir::python::adaptors::pure_subclass::superClass protected
Definition at line 399 of file PybindAdaptors.h.
Referenced by pure_subclass().
thisClass
py::object mlir::python::adaptors::pure_subclass::thisClass protected
Definition at line 400 of file PybindAdaptors.h.
Referenced by def(), def_classmethod(), def_property_readonly(), def_staticmethod(), get_class(), mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass(), mlir::python::adaptors::mlir_value_subclass::mlir_value_subclass(), and pure_subclass().
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h