MLIR: mlir::AsmResourceParser Class Reference
mlir::AsmResourceParser Class Reference abstract
This class represents an instance of a resource parser.
#include "mlir/IR/AsmState.h"
Public Member Functions
AsmResourceParser (StringRef name)
Create a new parser with the given identifying name.
virtual ~AsmResourceParser ()
StringRef getName () const
Return the name of this parser.
virtual LogicalResult parseResource (AsmParsedResourceEntry &entry)=0
Parse the given resource entry.
Static Public Member Functions
template<typename CallableT>
static std::unique_ptr< AsmResourceParser > fromCallable (StringRef name, CallableT &&parseFn)
Return a resource parser implemented via the given callable, whose form should match that of parseResource above.
Detailed Description
This class represents an instance of a resource parser.
This class should be implemented by non-dialect clients that want to inject additional resources into MLIR assembly formats.
Definition at line 339 of file AsmState.h.
Constructor & Destructor Documentation
AsmResourceParser()
mlir::AsmResourceParser::AsmResourceParser (StringRef name) inline
Create a new parser with the given identifying name.
This name uniquely identifies the entries of this parser, and differentiates them from other contexts.
Definition at line 344 of file AsmState.h.
Referenced by fromCallable().
~AsmResourceParser()
AsmResourceParser::~AsmResourceParser () virtual default
Member Function Documentation
fromCallable()
template<typename CallableT> std::unique_ptr< AsmResourceParser > mlir::AsmResourceParser::fromCallable (StringRef name, CallableT && parseFn) inline static
Return a resource parser implemented via the given callable, whose form should match that of parseResource above.
Definition at line 358 of file AsmState.h.
References AsmResourceParser(), and parseResource().
Referenced by mlir::ParserConfig::attachResourceParser().
getName()
StringRef mlir::AsmResourceParser::getName () const inline
Return the name of this parser.
Definition at line 348 of file AsmState.h.
Referenced by mlir::FallbackAsmResourceMap::getPrinters().
parseResource()
virtual LogicalResult mlir::AsmResourceParser::parseResource (AsmParsedResourceEntry & entry) pure virtual
Parse the given resource entry.
Returns failure if the key/data were not valid, or could otherwise not be processed correctly. Any necessary errors should be emitted with the provided entry.
Referenced by fromCallable().
The documentation for this class was generated from the following files:
include/mlir/IR/AsmState.h
lib/IR/AsmPrinter.cpp