MLIR: mlir::NamedAttribute Class Reference
mlir::NamedAttribute Class Reference
NamedAttribute represents a combination of a name and an Attribute value.
#include "mlir/IR/Attributes.h"
Public Member Functions
NamedAttribute (StringAttr name, Attribute value)
NamedAttribute (StringRef name, Attribute value)
StringAttr getName () const
Return the name of the attribute.
Dialect * getNameDialect () const
Return the dialect of the name of this attribute, if the name is prefixed by a dialect namespace.
Attribute getValue () const
Return the value of the attribute.
void setName (StringAttr newName)
Set the name of this attribute.
void setValue (Attribute newValue)
Set the value of this attribute.
bool operator< (const NamedAttribute &rhs) const
Compare this attribute to the provided attribute, ordering by name.
bool operator< (StringRef rhs) const
Compare this attribute to the provided string, ordering by name.
bool operator== (const NamedAttribute &rhs) const
bool operator!= (const NamedAttribute &rhs) const
Detailed Description
NamedAttribute represents a combination of a name and an Attribute value.
Definition at line 164 of file Attributes.h.
Constructor & Destructor Documentation
NamedAttribute() [1/2]
NamedAttribute::NamedAttribute (StringAttr name, Attribute value)
Definition at line 43 of file Attributes.cpp.
Referenced by operator!=(), operator<(), and operator==().
NamedAttribute() [2/2]
NamedAttribute::NamedAttribute (StringRef name, Attribute value)
Definition at line 49 of file Attributes.cpp.
Member Function Documentation
getName()
StringAttr NamedAttribute::getName () const
Return the name of the attribute.
Definition at line 55 of file Attributes.cpp.
Referenced by amendOperationImpl(), mlir::LLVMTranslationInterface::convertParameterAttr(), mlir::OpState::genericPrintProperties(), getNameDialect(), ConvertNativeFuncPattern< Op >::matchAndRewrite(), mlirDictionaryAttrGetElement(), mlirOperationGetAttribute(), mlirOperationGetDiscardableAttribute(), operator<(), operator<(), printApplyRegisteredPassOptions(), mlir::AsmPrinter::Impl::printNamedAttribute(), mlir::AsmPrinter::Impl::printOptionalAttrDict(), processFMFAttr(), verifyKnownLaunchSizeAttr(), and verifyRegionAttribute().
getNameDialect()
Dialect * NamedAttribute::getNameDialect () const
Return the dialect of the name of this attribute, if the name is prefixed by a dialect namespace.
For example, llvm.fast_math would return the LLVM dialect (if it is loaded). Returns nullptr if the dialect isn't loaded, or if the name is not prefixed by a dialect namespace.
Definition at line 59 of file Attributes.cpp.
References getName().
Referenced by mlir::LLVMTranslationInterface::amendOperation(), and mlir::LLVMTranslationInterface::convertParameterAttr().
getValue()
Attribute mlir::NamedAttribute::getValue () const inline
Return the value of the attribute.
Definition at line 179 of file Attributes.h.
Referenced by amendOperationImpl(), convertParameterAttr(), ConvertNativeFuncPattern< Op >::matchAndRewrite(), mlirDictionaryAttrGetElement(), mlirOperationGetAttribute(), mlirOperationGetDiscardableAttribute(), printApplyRegisteredPassOptions(), mlir::AsmPrinter::Impl::printNamedAttribute(), processFMFAttr(), verifyKnownLaunchSizeAttr(), and verifyRegionAttribute().
operator!=()
bool mlir::NamedAttribute::operator!= (const NamedAttribute & rhs) const inline
Definition at line 198 of file Attributes.h.
References NamedAttribute(), and rhs.
operator<() [1/2]
bool NamedAttribute::operator< (const NamedAttribute & rhs) const
Compare this attribute to the provided attribute, ordering by name.
Definition at line 68 of file Attributes.cpp.
References getName(), NamedAttribute(), and rhs.
operator<() [2/2]
bool NamedAttribute::operator< (StringRef rhs) const
Compare this attribute to the provided string, ordering by name.
Definition at line 72 of file Attributes.cpp.
References getName(), and rhs.
operator==()
bool mlir::NamedAttribute::operator== (const NamedAttribute & rhs) const inline
Definition at line 195 of file Attributes.h.
References NamedAttribute(), and rhs.
setName()
void NamedAttribute::setName (StringAttr newName)
Set the name of this attribute.
Definition at line 63 of file Attributes.cpp.
setValue()
void mlir::NamedAttribute::setValue (Attribute newValue) inline
Set the value of this attribute.
Definition at line 185 of file Attributes.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp