MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy > Class Template Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy > Class Template Reference
CRTP base classes for Python types that subclass Type and should be castable from it (i.e.
#include "mlir/Bindings/Python/IRCore.h"
Inherits mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType.
Public Types
using ClassTy = nanobind::class_<DerivedTy, BaseTy>
using IsAFunctionTy = bool (*)(MlirType)
using GetTypeIDFunctionTy = MlirTypeID (*)()
using Base = PyConcreteType
Public Member Functions
PyConcreteType ()=default
PyConcreteType (PyMlirContextRef contextRef, MlirType t)
PyConcreteType (PyType &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::typed< nanobind::object, PyType > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Static Public Attributes
static constexpr GetTypeIDFunctionTy getTypeIdFunction = nullptr
static const MlirStringRef name {}
Detailed Description
template<typename DerivedTy, typename BaseTy = PyType>
class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >
CRTP base classes for Python types that subclass Type and should be castable from it (i.e.
via something like IntegerType(t)). By default, type class hierarchies are one level deep (i.e. a concrete type class extends PyType); however, intermediate python-visible base classes can be modeled by specifying a BaseTy.
Definition at line 943 of file IRCore.h.
Member Typedef Documentation
Base
template<typename DerivedTy, typename BaseTy = PyType> using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::Base = PyConcreteType
Definition at line 951 of file IRCore.h.
ClassTy
template<typename DerivedTy, typename BaseTy = PyType> using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::ClassTy = nanobind::class_<DerivedTy, BaseTy>
Definition at line 948 of file IRCore.h.
GetTypeIDFunctionTy
template<typename DerivedTy, typename BaseTy = PyType> using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::GetTypeIDFunctionTy = MlirTypeID (*)()
Definition at line 950 of file IRCore.h.
IsAFunctionTy
template<typename DerivedTy, typename BaseTy = PyType> using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::IsAFunctionTy = bool (*)(MlirType)
Definition at line 949 of file IRCore.h.
Constructor & Destructor Documentation
PyConcreteType() [1/3]
template<typename DerivedTy, typename BaseTy = PyType> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType () default
Referenced by PyConcreteType().
PyConcreteType() [2/3]
template<typename DerivedTy, typename BaseTy = PyType> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType (PyMlirContextRef contextRef, MlirType t) inline
Definition at line 956 of file IRCore.h.
PyConcreteType() [3/3]
template<typename DerivedTy, typename BaseTy = PyType> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType (PyType & orig) inline
Definition at line 958 of file IRCore.h.
References castFrom(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), PyConcreteType(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType().
Member Function Documentation
bind()
template<typename DerivedTy, typename BaseTy = PyType> void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::bind (nanobind::module_ & m) inline static
Definition at line 973 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), mlir::PyPrintAccumulator::getCallback(), mlir::PyPrintAccumulator::getUserData(), mlir::PyPrintAccumulator::join(), mlirTypePrint(), mlir::PyPrintAccumulator::parts, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType().
bindDerived()
template<typename DerivedTy, typename BaseTy = PyType> void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::bindDerived (ClassTy & m) inline static
Implemented by derived classes to add methods to the Python subclass.
Definition at line 1013 of file IRCore.h.
castFrom()
template<typename DerivedTy, typename BaseTy = PyType> MlirType mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::castFrom (PyType & orig) inline static
Definition at line 961 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType().
Referenced by PyConcreteType().
Member Data Documentation
getTypeIdFunction
template<typename DerivedTy, typename BaseTy = PyType> GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::getTypeIdFunction = nullptr static constexpr
Definition at line 952 of file IRCore.h.
name
template<typename DerivedTy, typename BaseTy = PyType> const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::name {} inline static
Definition at line 953 of file IRCore.h.
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/IRCore.h