MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState Class Reference
Wrapper around an MlirAsmState.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyAsmState (MlirValue value, bool useLocalScope)
PyAsmState (PyOperationBase &operation, bool useLocalScope)
~PyAsmState ()
PyAsmState (PyAsmState &other)=delete
PyAsmState (const PyAsmState &other)=delete
MlirAsmState get ()
Detailed Description
Wrapper around an MlirAsmState.
Definition at line 806 of file IRCore.h.
Constructor & Destructor Documentation
PyAsmState() [1/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::PyAsmState (MlirValue value, bool useLocalScope)
Definition at line 1750 of file IRCore.cpp.
References mlirOpPrintingFlagsCreate().
Referenced by PyAsmState(), and PyAsmState().
PyAsmState() [2/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::PyAsmState (PyOperationBase & operation, bool useLocalScope)
Definition at line 1759 of file IRCore.cpp.
~PyAsmState()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::~PyAsmState () inline
Definition at line 810 of file IRCore.h.
References mlirOpPrintingFlagsDestroy().
PyAsmState() [3/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::PyAsmState (PyAsmState & other) delete
References PyAsmState().
PyAsmState() [4/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::PyAsmState (const PyAsmState & other) delete
References PyAsmState().
Member Function Documentation
get()
MlirAsmState mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::get () inline
Definition at line 815 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp