MLIR: mlir::Matrix Class Reference
mlir::Matrix Class Reference
This is a class to represent a resizable matrix.
#include "mlir/Analysis/Presburger/Matrix.h"
Public Member Functions
Matrix ()=delete
Matrix (unsigned rows, unsigned columns, unsigned reservedRows=0, unsigned reservedColumns=0)
Construct a matrix with the specified number of rows and columns.
int64_t & at (unsigned row, unsigned column)
Access the element at the specified row and column.
int64_t at (unsigned row, unsigned column) const
int64_t & operator() (unsigned row, unsigned column)
int64_t operator() (unsigned row, unsigned column) const
void swapColumns (unsigned column, unsigned otherColumn)
Swap the given columns.
void swapRows (unsigned row, unsigned otherRow)
Swap the given rows.
unsigned getNumRows () const
unsigned getNumColumns () const
unsigned getNumReservedRows () const
Return the maximum number of rows/columns that can be added without incurring a reallocation.
unsigned getNumReservedColumns () const
void reserveRows (unsigned rows)
Reserve enough space to resize to the specified number of rows without reallocations.
ArrayRef< int64_t > getRow (unsigned row) const
Get an ArrayRef corresponding to the specified row.
void insertColumns (unsigned pos, unsigned count)
Insert columns having positions pos, pos + 1, ...
void insertColumn (unsigned pos)
void insertRows (unsigned pos, unsigned count)
Insert rows having positions pos, pos + 1, ...
void insertRow (unsigned pos)
void removeColumns (unsigned pos, unsigned count)
Remove the columns having positions pos, pos + 1, ...
void removeColumn (unsigned pos)
void removeRows (unsigned pos, unsigned count)
Remove the rows having positions pos, pos + 1, ...
void removeRow (unsigned pos)
void copyRow (unsigned sourceRow, unsigned targetRow)
void addToRow (unsigned sourceRow, unsigned targetRow, int64_t scale)
Add scale multiples of the source row to the target row.
void addToColumn (unsigned sourceColumn, unsigned targetColumn, int64_t scale)
Add scale multiples of the source column to the target column.
void negateColumn (unsigned column)
Negate the specified column.
void resizeVertically (unsigned newNRows)
Resize the matrix to the specified dimensions.
unsigned appendExtraRow ()
Add an extra row at the bottom of the matrix and return its position.
void print (raw_ostream &os) const
Print the matrix.
void dump () const
bool hasConsistentState () const
Return whether the Matrix is in a consistent state with all its invariants satisfied.
Static Public Member Functions
static Matrix identity (unsigned dimension)
Return the identity matrix of the specified dimension.
Detailed Description
This is a class to represent a resizable matrix.
More columns and rows can be reserved than are currently used. The data is stored as a single 1D array, viewed as a 2D matrix with nRows rows and nReservedColumns columns, stored in row major form. Thus the element at (i, j) is stored at data[i*nReservedColumns + j]. The reserved but unused columns always have all zero values. The reserved rows are just reserved space in the underlying SmallVector's capacity.
Definition at line 33 of file Matrix.h.
Constructor & Destructor Documentation
Matrix() [1/2]
mlir::Matrix::Matrix () delete
Matrix() [2/2]
mlir::Matrix::Matrix (unsigned rows, unsigned columns, unsigned reservedRows = 0, unsigned reservedColumns = 0)
Construct a matrix with the specified number of rows and columns.
The number of reserved rows and columns will be at least the number specified, and will always be sufficient to accomodate the number of rows and columns specified.
Initially, the entries are initialized to ero.
Definition at line 14 of file Matrix.cpp.
References max().
Member Function Documentation
addToColumn()
void mlir::Matrix::addToColumn (unsigned sourceColumn, unsigned targetColumn, int64_t scale)
Add scale multiples of the source column to the target column.
Definition at line 176 of file Matrix.cpp.
References at(), and getNumRows().
Referenced by mlir::modEntryColumnOperation().
addToRow()
void mlir::Matrix::addToRow (unsigned sourceRow, unsigned targetRow, int64_t scale)
Add scale multiples of the source row to the target row.
Definition at line 169 of file Matrix.cpp.
References at().
Referenced by mlir::GBRSimplex::removeLastEquality().
appendExtraRow()
unsigned mlir::Matrix::appendExtraRow ()
Add an extra row at the bottom of the matrix and return its position.
Definition at line 63 of file Matrix.cpp.
References resizeVertically().
Referenced by mlir::FlatAffineConstraints::addConstantLowerBound(), mlir::FlatAffineConstraints::addConstantUpperBound(), mlir::FlatAffineConstraints::addEquality(), and mlir::FlatAffineConstraints::addInequality().
at() [1/2]
int64_t & mlir::Matrix::at (unsigned row, unsigned column)
Access the element at the specified row and column.
Definition at line 29 of file Matrix.cpp.
Referenced by addToColumn(), addToRow(), copyRow(), insertRows(), negateColumn(), operator()(), print(), removeColumns(), swapColumns(), and swapRows().
at() [2/2]
int64_t mlir::Matrix::at (unsigned row, unsigned column) const
Definition at line 35 of file Matrix.cpp.
copyRow()
void mlir::Matrix::copyRow (unsigned sourceRow, unsigned targetRow)
Definition at line 162 of file Matrix.cpp.
References at().
Referenced by insertRows(), removeRows(), and mlir::FlatAffineConstraints::removeTrivialRedundancy().
dump()
void mlir::Matrix::dump () const
Definition at line 197 of file Matrix.cpp.
References print().
getNumColumns()
unsigned mlir::Matrix::getNumColumns () const
Definition at line 51 of file Matrix.cpp.
Referenced by mlir::LinearTransform::makeTransformToColumnEchelon(), mlir::LinearTransform::postMultiplyRow(), mlir::LinearTransform::preMultiplyColumn(), and swapColumns().
getNumReservedColumns()
unsigned mlir::Matrix::getNumReservedColumns () const
Definition at line 53 of file Matrix.cpp.
getNumReservedRows()
unsigned mlir::Matrix::getNumReservedRows () const
Return the maximum number of rows/columns that can be added without incurring a reallocation.
Definition at line 55 of file Matrix.cpp.
Referenced by mlir::FlatAffineConstraints::getNumReservedEqualities(), and mlir::FlatAffineConstraints::getNumReservedInequalities().
getNumRows()
unsigned mlir::Matrix::getNumRows () const
Definition at line 49 of file Matrix.cpp.
Referenced by mlir::FlatAffineConstraints::addConstantLowerBound(), mlir::FlatAffineConstraints::addConstantUpperBound(), addToColumn(), mlir::FlatAffineConstraints::append(), mlir::Simplex::findIntegerSample(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::LinearTransform::makeTransformToColumnEchelon(), negateColumn(), mlir::LinearTransform::postMultiplyRow(), mlir::LinearTransform::preMultiplyColumn(), mlir::GBRSimplex::removeLastEquality(), mlir::FlatAffineConstraints::setIdToConstant(), mlir::Simplex::Simplex(), and swapRows().
getRow()
ArrayRef< int64_t > mlir::Matrix::getRow (unsigned row) const
Get an ArrayRef corresponding to the specified row.
Definition at line 91 of file Matrix.cpp.
Referenced by mlir::Simplex::findIntegerSample(), mlir::FlatAffineConstraints::getEquality(), mlir::FlatAffineConstraints::getInequality(), and mlir::GBRSimplex::removeLastEquality().
hasConsistentState()
bool mlir::Matrix::hasConsistentState () const
Return whether the Matrix is in a consistent state with all its invariants satisfied.
Definition at line 199 of file Matrix.cpp.
Referenced by normalizeConstraintByGCD().
identity()
Matrix mlir::Matrix::identity (unsigned dimension) static
Return the identity matrix of the specified dimension.
Definition at line 22 of file Matrix.cpp.
Referenced by mlir::Simplex::findIntegerSample(), and mlir::LinearTransform::makeTransformToColumnEchelon().
insertColumn()
void mlir::Matrix::insertColumn (unsigned pos)
Definition at line 95 of file Matrix.cpp.
References insertColumns().
Referenced by mlir::FlatAffineConstraints::addId().
insertColumns()
void mlir::Matrix::insertColumns (unsigned pos, unsigned count)
Insert columns having positions pos, pos + 1, ...
pos + count - 1. Columns that were at positions 0 to pos - 1 will stay where they are; columns that were at positions pos to nColumns - 1 will be pushed to the right. pos should be at most nColumns.
Definition at line 96 of file Matrix.cpp.
Referenced by insertColumn().
insertRow()
void mlir::Matrix::insertRow (unsigned pos)
Definition at line 138 of file Matrix.cpp.
References insertRows().
insertRows()
void mlir::Matrix::insertRows (unsigned pos, unsigned count)
Insert rows having positions pos, pos + 1, ...
pos + count - 1. Rows that were at positions 0 to pos - 1 will stay where they are; rows that were at positions pos to nColumns - 1 will be pushed to the right. pos should be at most nRows.
Definition at line 139 of file Matrix.cpp.
References at(), copyRow(), and resizeVertically().
Referenced by insertRow().
negateColumn()
void mlir::Matrix::negateColumn (unsigned column)
Negate the specified column.
Definition at line 184 of file Matrix.cpp.
References at(), and getNumRows().
Referenced by mlir::LinearTransform::makeTransformToColumnEchelon().
operator()() [1/2]
int64_t & mlir::Matrix::operator() (unsigned row, unsigned column)
Definition at line 41 of file Matrix.cpp.
References at().
operator()() [2/2]
int64_t mlir::Matrix::operator() (unsigned row, unsigned column) const
Definition at line 45 of file Matrix.cpp.
References at().
print()
void mlir::Matrix::print (raw_ostream & os) const
Print the matrix.
Definition at line 189 of file Matrix.cpp.
References at().
Referenced by dump().
removeColumn()
void mlir::Matrix::removeColumn (unsigned pos)
Definition at line 124 of file Matrix.cpp.
References removeColumns().
removeColumns()
void mlir::Matrix::removeColumns (unsigned pos, unsigned count)
Remove the columns having positions pos, pos + 1, ...
pos + count - 1. Rows that were at positions 0 to pos - 1 will stay where they are; columns that were at positions pos + count - 1 or later will be pushed to the right. The columns to be deleted must be valid rows: pos + count - 1 must be at most nColumns - 1.
Definition at line 125 of file Matrix.cpp.
References at().
Referenced by eliminateFromConstraint(), and removeColumn().
removeRow()
void mlir::Matrix::removeRow (unsigned pos)
Definition at line 152 of file Matrix.cpp.
References removeRows().
Referenced by mlir::FlatAffineConstraints::removeEquality(), and mlir::FlatAffineConstraints::removeInequality().
removeRows()
void mlir::Matrix::removeRows (unsigned pos, unsigned count)
Remove the rows having positions pos, pos + 1, ...
pos + count - 1. Rows that were at positions 0 to pos - 1 will stay where they are; rows that were at positions pos + count - 1 or later will be pushed to the right. The rows to be deleted must be valid rows: pos + count - 1 must be at most nRows - 1.
Definition at line 153 of file Matrix.cpp.
References copyRow(), and resizeVertically().
Referenced by removeRow().
reserveRows()
void mlir::Matrix::reserveRows (unsigned rows)
Reserve enough space to resize to the specified number of rows without reallocations.
Definition at line 59 of file Matrix.cpp.
Referenced by mlir::FlatAffineConstraints::append().
resizeVertically()
void mlir::Matrix::resizeVertically (unsigned newNRows)
Resize the matrix to the specified dimensions.
If a dimension is smaller, the values are truncated; if it is bigger, the new values are default initialized.
Definition at line 68 of file Matrix.cpp.
Referenced by appendExtraRow(), mlir::FlatAffineConstraints::clearConstraints(), mlir::Simplex::getSnapshot(), insertRows(), mlir::Simplex::makeProduct(), mlir::FlatAffineConstraints::removeRedundantConstraints(), mlir::FlatAffineConstraints::removeRedundantInequalities(), removeRows(), mlir::FlatAffineConstraints::removeTrivialRedundancy(), mlir::FlatAffineConstraints::setIdToConstant(), and mlir::Simplex::Simplex().
swapColumns()
void mlir::Matrix::swapColumns (unsigned column, unsigned otherColumn)
Swap the given columns.
Definition at line 82 of file Matrix.cpp.
References at(), and getNumColumns().
Referenced by mlir::LinearTransform::makeTransformToColumnEchelon().
swapRows()
void mlir::Matrix::swapRows (unsigned row, unsigned otherRow)
Swap the given rows.
Definition at line 73 of file Matrix.cpp.
References at(), and getNumRows().
Referenced by mlir::Simplex::isEmpty(), and mlir::GBRSimplex::removeLastEquality().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Matrix.h
lib/Analysis/Presburger/Matrix.cpp