MLIR: mlir::pdll::ods::Context Class Reference
mlir::pdll::ods::Context Class Reference
This class contains all of the registered ODS operation classes.
#include "mlir/Tools/PDLL/ODS/Context.h"
Public Member Functions
Context ()
~Context ()
const AttributeConstraint & insertAttributeConstraint (StringRef name, StringRef summary, StringRef cppClass)
Insert a new attribute constraint with the context.
const TypeConstraint & insertTypeConstraint (StringRef name, StringRef summary, StringRef cppClass)
Insert a new type constraint with the context.
Dialect & insertDialect (StringRef name)
Insert a new dialect with the context.
const Dialect * lookupDialect (StringRef name) const
Lookup a dialect registered with the given name, or null if no dialect with that name was inserted.
auto getDialects () const
Return a range of all of the registered dialects.
std::pair< Operation *, bool > insertOperation (StringRef name, StringRef summary, StringRef desc, StringRef nativeClassName, bool supportsResultTypeInferrence, SMLoc loc)
Insert a new operation with the context.
const Operation * lookupOperation (StringRef name) const
Lookup an operation registered with the given name, or null if no operation with that name is registered.
void print (raw_ostream &os) const
Print the contents of this context to the provided stream.
Detailed Description
This class contains all of the registered ODS operation classes.
Definition at line 32 of file Context.h.
Constructor & Destructor Documentation
Context()
Context::Context () default
~Context()
Context::~Context () default
Member Function Documentation
getDialects()
auto mlir::pdll::ods::Context::getDialects () const inline
Return a range of all of the registered dialects.
Definition at line 57 of file Context.h.
insertAttributeConstraint()
const AttributeConstraint & Context::insertAttributeConstraint (StringRef name, StringRef summary, StringRef cppClass)
Insert a new attribute constraint with the context.
Returns the inserted constraint, or a previously inserted constraint with the same name.
Definition at line 27 of file Context.cpp.
insertDialect()
Dialect & Context::insertDialect (StringRef name)
Insert a new dialect with the context.
Returns the inserted dialect, or a previously inserted dialect with the same name.
Definition at line 50 of file Context.cpp.
Referenced by insertOperation().
insertOperation()
std::pair< Operation *, bool > Context::insertOperation (StringRef name, StringRef summary, StringRef desc, StringRef nativeClassName, bool supportsResultTypeInferrence, SMLoc loc)
Insert a new operation with the context.
Returns the inserted operation, and a boolean indicating if the operation newly inserted (false if the operation already existed).
Definition at line 63 of file Context.cpp.
References insertDialect(), and mlir::pdll::ods::Dialect::insertOperation().
insertTypeConstraint()
const TypeConstraint & Context::insertTypeConstraint (StringRef name, StringRef summary, StringRef cppClass)
Insert a new type constraint with the context.
Returns the inserted constraint, or a previously inserted constraint with the same name.
Definition at line 41 of file Context.cpp.
lookupDialect()
const Dialect * Context::lookupDialect (StringRef name) const
Lookup a dialect registered with the given name, or null if no dialect with that name was inserted.
Definition at line 57 of file Context.cpp.
References nullptr.
Referenced by lookupOperation().
lookupOperation()
const Operation * Context::lookupOperation (StringRef name) const
Lookup an operation registered with the given name, or null if no operation with that name is registered.
Definition at line 72 of file Context.cpp.
References lookupDialect().
print()
void Context::print (raw_ostream & os) const
Print the contents of this context to the provided stream.
Definition at line 91 of file Context.cpp.
References mlir::pdll::ods::Attribute::getConstraint(), mlir::pdll::ods::OperandOrResult::getConstraint(), mlir::pdll::ods::Constraint::getDemangledName(), mlir::pdll::ods::Attribute::getName(), mlir::pdll::ods::OperandOrResult::getName(), mlir::pdll::ods::OperandOrResult::getVariableLengthKind(), mlir::pdll::ods::Attribute::isOptional(), mlir::pdll::ods::Optional, result, mlir::pdll::ods::Single, sortMapByName(), and mlir::pdll::ods::Variadic.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/ODS/Context.h
lib/Tools/PDLL/ODS/Context.cpp