MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator Class Reference
Iterator over the integer elements of a dense array.
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
PyDenseArrayIterator (PyAttribute attr)
PyDenseArrayIterator dunderIter ()
Return a copy of the iterator.
EltTy dunderNext ()
Return the next element.
Static Public Member Functions
static void bind (nanobind::module_ &m)
Bind the iterator class.
Detailed Description
template<typename EltTy, typename DerivedT>
class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator
Iterator over the integer elements of a dense array.
Definition at line 126 of file IRAttributes.h.
Constructor & Destructor Documentation
PyDenseArrayIterator()
template<typename EltTy, typename DerivedT> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator::PyDenseArrayIterator (PyAttribute attr) inline
Definition at line 128 of file IRAttributes.h.
Referenced by dunderIter().
Member Function Documentation
bind()
template<typename EltTy, typename DerivedT> void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator::bind (nanobind::module_ & m) inline static
Bind the iterator class.
Definition at line 142 of file IRAttributes.h.
References dunderIter(), and dunderNext().
dunderIter()
template<typename EltTy, typename DerivedT> PyDenseArrayIterator mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator::dunderIter () inline
Return a copy of the iterator.
Definition at line 131 of file IRAttributes.h.
References PyDenseArrayIterator().
Referenced by bind().
dunderNext()
template<typename EltTy, typename DerivedT> EltTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::PyDenseArrayIterator::dunderNext () inline
Return the next element.
Definition at line 134 of file IRAttributes.h.
References mlirDenseArrayGetNumElements().
Referenced by bind().
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/IRAttributes.h