MLIR: StridedMemrefIterator< T, 0 > Class Template Reference
StridedMemrefIterator< T, 0 > Class Template Reference
Iterate over all elements in a 0-ranked strided memref.
#include "mlir/ExecutionEngine/CRunnerUtils.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = T
using difference_type = std::ptrdiff_t
using pointer = T *
using reference = T &
Public Member Functions
StridedMemrefIterator (StridedMemRefType< T, 0 > &descriptor, int64_t offset=0)
StridedMemrefIterator< T, 0 > & operator++ ()
reference operator* ()
pointer operator-> ()
const std::array< int64_t, 0 > & getIndices ()
bool operator== (const StridedMemrefIterator &other) const
bool operator!= (const StridedMemrefIterator &other) const
Detailed Description
template<typename T>
class StridedMemrefIterator< T, 0 >
Iterate over all elements in a 0-ranked strided memref.
Definition at line 265 of file CRunnerUtils.h.
Member Typedef Documentation
difference_type
template<typename T> using StridedMemrefIterator< T, 0 >::difference_type = std::ptrdiff_t
Definition at line 269 of file CRunnerUtils.h.
iterator_category
template<typename T> using StridedMemrefIterator< T, 0 >::iterator_category = std::forward_iterator_tag
Definition at line 267 of file CRunnerUtils.h.
pointer
template<typename T> using StridedMemrefIterator< T, 0 >::pointer = T *
Definition at line 270 of file CRunnerUtils.h.
reference
template<typename T> using StridedMemrefIterator< T, 0 >::reference = T &
Definition at line 271 of file CRunnerUtils.h.
value_type
template<typename T> using StridedMemrefIterator< T, 0 >::value_type = T
Definition at line 268 of file CRunnerUtils.h.
Constructor & Destructor Documentation
StridedMemrefIterator()
template<typename T> StridedMemrefIterator< T, 0 >::StridedMemrefIterator (StridedMemRefType< T, 0 > & descriptor, int64_t offset = 0) inline
Definition at line 273 of file CRunnerUtils.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
getIndices()
template<typename T> const std::array< int64_t, 0 > & StridedMemrefIterator< T, 0 >::getIndices () inline
Definition at line 286 of file CRunnerUtils.h.
operator!=()
template<typename T> bool StridedMemrefIterator< T, 0 >::operator!= (const StridedMemrefIterator< T, 0 > & other) const inline
Definition at line 297 of file CRunnerUtils.h.
References StridedMemrefIterator().
operator*()
template<typename T> reference StridedMemrefIterator< T, 0 >::operator* () inline
Definition at line 281 of file CRunnerUtils.h.
operator++()
template<typename T> StridedMemrefIterator< T, 0 > & StridedMemrefIterator< T, 0 >::operator++ () inline
Definition at line 276 of file CRunnerUtils.h.
References StridedMemrefIterator().
operator->()
template<typename T> pointer StridedMemrefIterator< T, 0 >::operator-> () inline
Definition at line 282 of file CRunnerUtils.h.
operator==()
template<typename T> bool StridedMemrefIterator< T, 0 >::operator== (const StridedMemrefIterator< T, 0 > & other) const inline
Definition at line 293 of file CRunnerUtils.h.
References StridedMemrefIterator().
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/CRunnerUtils.h