MLIR: mlir::FlatSymbolRefAttr Class Reference
mlir::FlatSymbolRefAttr Class Reference
A symbol reference with a reference path containing a single element.
#include "mlir/IR/BuiltinAttributes.h"
Public Types
using ValueType = StringRef
Public Member Functions
StringAttr getAttr () const
Returns the name of the held symbol reference as a StringAttr.
StringRef getValue () const
Returns the name of the held symbol reference.
Static Public Member Functions
static FlatSymbolRefAttr get (StringAttr value)
Construct a symbol reference for the given value name.
static FlatSymbolRefAttr get (MLIRContext *ctx, StringRef value)
static FlatSymbolRefAttr get (Operation *symbol)
Convenience getter for building a SymbolRefAttr based on an operation that implements the SymbolTrait.
static bool classof (Attribute attr)
Methods for support type inquiry through isa, cast, and dyn_cast.
Detailed Description
A symbol reference with a reference path containing a single element.
This is used to refer to an operation within the current symbol table.
Definition at line 871 of file BuiltinAttributes.h.
Member Typedef Documentation
ValueType
using mlir::FlatSymbolRefAttr::ValueType = StringRef
Definition at line 874 of file BuiltinAttributes.h.
Member Function Documentation
classof()
static bool mlir::FlatSymbolRefAttr::classof (Attribute attr) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 897 of file BuiltinAttributes.h.
get() [1/3]
static FlatSymbolRefAttr mlir::FlatSymbolRefAttr::get (MLIRContext * ctx, StringRef value) inline static
Definition at line 880 of file BuiltinAttributes.h.
References mlir::get().
get() [2/3]
static FlatSymbolRefAttr mlir::FlatSymbolRefAttr::get (Operation * symbol) inline static
Convenience getter for building a SymbolRefAttr based on an operation that implements the SymbolTrait.
Definition at line 886 of file BuiltinAttributes.h.
References mlir::get().
get() [3/3]
static FlatSymbolRefAttr mlir::FlatSymbolRefAttr::get (StringAttr value) inline static
Construct a symbol reference for the given value name.
Definition at line 877 of file BuiltinAttributes.h.
References mlir::get().
Referenced by addComdat(), collectValidReferencesFor(), convertCGProfileModuleFlagValue(), convertOperationImpl(), mlirFlatSymbolRefAttrGet(), and replaceAllSymbolUsesImpl().
getAttr()
StringAttr mlir::FlatSymbolRefAttr::getAttr () const inline
Returns the name of the held symbol reference as a StringAttr.
Definition at line 891 of file BuiltinAttributes.h.
Referenced by mlir::SymbolCacheBase::getDefinition(), getLibraryCallSymbolRef(), mlir::LockedSymbolTableCollection::lookupSymbolIn(), and verifySymbolAttrUse().
getValue()
StringRef mlir::FlatSymbolRefAttr::getValue () const inline
Returns the name of the held symbol reference.
Definition at line 894 of file BuiltinAttributes.h.
Referenced by mlir::shard::Sharding::getGrid(), getGridAndVerify(), getLibraryCallSymbolRef(), and verifySymbolAttrUse().
The documentation for this class was generated from the following file:
include/mlir/IR/BuiltinAttributes.h