MLIR: mlir::BytecodeReaderConfig Class Reference
mlir::BytecodeReaderConfig Class Reference
A class containing bytecode-specific configurations of the ParserConfig.
#include "mlir/Bytecode/BytecodeReaderConfig.h"
Public Member Functions
BytecodeReaderConfig ()=default
ArrayRef< std::unique_ptr< AttrTypeBytecodeReader< Attribute > > > getAttributeCallbacks () const
Returns the callbacks available to the parser.
ArrayRef< std::unique_ptr< AttrTypeBytecodeReader< Type > > > getTypeCallbacks () const
void attachAttributeCallback (std::unique_ptr< AttrTypeBytecodeReader< Attribute > > parser)
Attach a custom bytecode parser callback to the configuration for parsing of custom type/attributes encodings.
void attachTypeCallback (std::unique_ptr< AttrTypeBytecodeReader< Type > > parser)
template<typename CallableT>
std::enable_if_t< std::is_convertible_v< CallableT, std::function< LogicalResult(DialectBytecodeReader &, StringRef, Attribute &)> > > attachAttributeCallback (CallableT &&parserFn)
Attach a custom bytecode parser callback to the configuration for parsing of custom type/attributes encodings.
template<typename CallableT>
std::enable_if_t< std::is_convertible_v< CallableT, std::function< LogicalResult(DialectBytecodeReader &, StringRef, Type &)> > > attachTypeCallback (CallableT &&parserFn)
Detailed Description
A class containing bytecode-specific configurations of the ParserConfig.
Definition at line 66 of file BytecodeReaderConfig.h.
Constructor & Destructor Documentation
BytecodeReaderConfig()
mlir::BytecodeReaderConfig::BytecodeReaderConfig () default
Member Function Documentation
attachAttributeCallback() [1/2]
template<typename CallableT> std::enable_if_t< std::is_convertible_v< CallableT, std::function< LogicalResult(DialectBytecodeReader &, StringRef, Attribute &)> > > mlir::BytecodeReaderConfig::attachAttributeCallback (CallableT && parserFn) inline
Attach a custom bytecode parser callback to the configuration for parsing of custom type/attributes encodings.
Definition at line 97 of file BytecodeReaderConfig.h.
References attachAttributeCallback(), and mlir::AttrTypeBytecodeReader< T >::fromCallable().
attachAttributeCallback() [2/2]
void mlir::BytecodeReaderConfig::attachAttributeCallback (std::unique_ptr< AttrTypeBytecodeReader< Attribute > > parser) inline
Attach a custom bytecode parser callback to the configuration for parsing of custom type/attributes encodings.
Definition at line 82 of file BytecodeReaderConfig.h.
Referenced by attachAttributeCallback().
attachTypeCallback() [1/2]
template<typename CallableT> std::enable_if_t< std::is_convertible_v< CallableT, std::function< LogicalResult(DialectBytecodeReader &, StringRef, Type &)> > > mlir::BytecodeReaderConfig::attachTypeCallback (CallableT && parserFn) inline
Definition at line 105 of file BytecodeReaderConfig.h.
References attachTypeCallback(), and mlir::AttrTypeBytecodeReader< T >::fromCallable().
attachTypeCallback() [2/2]
void mlir::BytecodeReaderConfig::attachTypeCallback (std::unique_ptr< AttrTypeBytecodeReader< Type > > parser) inline
Definition at line 87 of file BytecodeReaderConfig.h.
Referenced by attachTypeCallback().
getAttributeCallbacks()
ArrayRef< std::unique_ptr< AttrTypeBytecodeReader< Attribute > > > mlir::BytecodeReaderConfig::getAttributeCallbacks () const inline
Returns the callbacks available to the parser.
Definition at line 72 of file BytecodeReaderConfig.h.
getTypeCallbacks()
ArrayRef< std::unique_ptr< AttrTypeBytecodeReader< Type > > > mlir::BytecodeReaderConfig::getTypeCallbacks () const inline
Definition at line 76 of file BytecodeReaderConfig.h.
The documentation for this class was generated from the following file:
include/mlir/Bytecode/BytecodeReaderConfig.h