MLIR: mlir::quant::CalibratedQuantizedType Class Reference
mlir::quant::CalibratedQuantizedType Class Reference
A quantized type that infers its range from given min/max values.
#include "mlir/Dialect/Quant/IR/QuantTypes.h"
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
double getMin () const
double getMax () const
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static CalibratedQuantizedType get (Type expressedType, double min, double max)
Gets an instance of the type with all parameters specified but not checked.
static CalibratedQuantizedType getChecked (function_ref< InFlightDiagnostic()> emitError, Type expressedType, double min, double max)
Gets an instance of the type with all specified parameters checked.
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, Type expressedType, double min, double max)
Verifies construction invariants and issues errors/warnings.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "quant.calibrated"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
A quantized type that infers its range from given min/max values.
Typical syntax: quant.calibrated<f32<-0.922,0.981>>
Definition at line 520 of file QuantTypes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
Member Function Documentation
get()
CalibratedQuantizedType CalibratedQuantizedType::get (Type expressedType, double min, double max) static
Gets an instance of the type with all parameters specified but not checked.
Definition at line 527 of file QuantTypes.cpp.
References mlir::get(), mlir::Type::getContext(), max(), and min().
Referenced by mlirCalibratedQuantizedTypeGet().
getChecked() [1/3]
template<typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked (typename... Args) inline static
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
If the arguments provided are invalid, errors are emitted using the provided location and a null object is returned.
Definition at line 189 of file StorageUniquerSupport.h.
getChecked() [2/3]
CalibratedQuantizedType CalibratedQuantizedType::getChecked (function_ref< InFlightDiagnostic()> emitError, Type expressedType, double min, double max) static
Gets an instance of the type with all specified parameters checked.
Returns a nullptr convertible type on failure.
Definition at line 532 of file QuantTypes.cpp.
References mlir::emitError(), mlir::Type::getContext(), max(), and min().
getChecked() [3/3]
template<typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked (typename... Args) inline static
Get or create a new ConcreteT instance within the ctx.
If the arguments provided are invalid, errors are emitted using the provided emitError and a null object is returned.
Definition at line 198 of file StorageUniquerSupport.h.
getMax()
double CalibratedQuantizedType::getMax () const
Definition at line 555 of file QuantTypes.cpp.
Referenced by printCalibratedQuantizedType().
getMin()
double CalibratedQuantizedType::getMin () const
Definition at line 553 of file QuantTypes.cpp.
Referenced by printCalibratedQuantizedType().
verifyInvariants()
LogicalResult CalibratedQuantizedType::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, Type expressedType, double min, double max) static
Verifies construction invariants and issues errors/warnings.
Definition at line 539 of file QuantTypes.cpp.
References mlir::emitError(), max(), and min().
Member Data Documentation
name
constexpr StringLiteral mlir::quant::CalibratedQuantizedType::name = "quant.calibrated" static constexpr
Definition at line 527 of file QuantTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Quant/IR/QuantTypes.h
lib/Dialect/Quant/IR/QuantTypes.cpp