MLIR: mlir::tblgen::Trait Class Reference
mlir::tblgen::Trait Class Reference
#include "mlir/TableGen/Trait.h"
Public Types
enum class Kind { Native , Pred , Internal , Interface }
Public Member Functions
Trait (Kind kind, const llvm::Record *def)
Kind getKind () const
const llvm::Record & getDef () const
Static Public Member Functions
static Trait create (const llvm::Init *init)
Protected Attributes
const llvm::Record * def
Kind kind
Detailed Description
Definition at line 32 of file Trait.h.
Member Enumeration Documentation
Kind
enum class mlir::tblgen::Trait::Kind strong
Enumerator
Native
Pred
Internal
Interface
Definition at line 35 of file Trait.h.
Constructor & Destructor Documentation
Trait()
Trait::Trait (Kind kind, const llvm::Record * def) explicit
Definition at line 38 of file Trait.cpp.
References def, and kind.
Referenced by mlir::tblgen::InterfaceTrait::classof(), mlir::tblgen::InternalTrait::classof(), mlir::tblgen::NativeTrait::classof(), mlir::tblgen::PredTrait::classof(), and create().
Member Function Documentation
create()
Trait Trait::create (const llvm::Init * init) static
Definition at line 26 of file Trait.cpp.
References def, Interface, Internal, Native, Pred, and Trait().
Referenced by mlir::tblgen::AttrOrTypeDef::AttrOrTypeDef().
getDef()
const llvm::Record & mlir::tblgen::Trait::getDef () const inline
Definition at line 54 of file Trait.h.
References def.
Referenced by mlir::tblgen::SideEffectTrait::classof().
getKind()
Kind mlir::tblgen::Trait::getKind () const inline
Definition at line 51 of file Trait.h.
References kind.
Referenced by mlir::tblgen::InterfaceTrait::classof(), mlir::tblgen::InternalTrait::classof(), mlir::tblgen::NativeTrait::classof(), and mlir::tblgen::PredTrait::classof().
Member Data Documentation
def
const llvm::Record* mlir::tblgen::Trait::def protected
Definition at line 58 of file Trait.h.
Referenced by create(), mlir::tblgen::InterfaceTrait::getAlwaysDeclaredMethods(), mlir::tblgen::SideEffectTrait::getBaseEffectName(), getDef(), mlir::tblgen::SideEffectTrait::getEffects(), mlir::tblgen::NativeTrait::getExtraConcreteClassDeclaration(), mlir::tblgen::NativeTrait::getExtraConcreteClassDefinition(), mlir::tblgen::InterfaceTrait::getFullyQualifiedTraitName(), mlir::tblgen::InternalTrait::getFullyQualifiedTraitName(), mlir::tblgen::NativeTrait::getFullyQualifiedTraitName(), mlir::tblgen::InterfaceTrait::getInterface(), mlir::tblgen::PredTrait::getPredTemplate(), mlir::tblgen::PredTrait::getSummary(), mlir::tblgen::NativeTrait::isStructuralOpTrait(), mlir::tblgen::InterfaceTrait::shouldDeclareMethods(), and Trait().
kind
Kind mlir::tblgen::Trait::kind protected
Definition at line 59 of file Trait.h.
Referenced by getKind(), and Trait().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Trait.h
lib/TableGen/Trait.cpp