MLIR: mlir::tblgen::DagLeaf Class Reference
mlir::tblgen::DagLeaf Class Reference
#include "mlir/TableGen/Pattern.h"
Public Member Functions
DagLeaf (const llvm::Init *def)
bool isUnspecified () const
bool isOperandMatcher () const
bool isAttrMatcher () const
bool isPropMatcher () const
bool isPropDefinition () const
bool isNativeCodeCall () const
bool isConstantAttr () const
bool isConstantProp () const
bool isEnumCase () const
bool isStringAttr () const
Constraint getAsConstraint () const
PropConstraint getAsPropConstraint () const
Property getAsProperty () const
ConstantAttr getAsConstantAttr () const
ConstantProp getAsConstantProp () const
EnumCase getAsEnumCase () const
std::string getConditionTemplate () const
StringRef getNativeCodeTemplate () const
int getNumReturnsOfNativeCode () const
std::string getStringAttr () const
void print (raw_ostream &os) const
Detailed Description
Definition at line 59 of file Pattern.h.
Constructor & Destructor Documentation
DagLeaf()
mlir::tblgen::DagLeaf::DagLeaf (const llvm::Init * def) inline explicit
Definition at line 61 of file Pattern.h.
Member Function Documentation
getAsConstantAttr()
ConstantAttr DagLeaf::getAsConstantAttr () const
Definition at line 92 of file Pattern.cpp.
References isConstantAttr().
getAsConstantProp()
ConstantProp DagLeaf::getAsConstantProp () const
Definition at line 102 of file Pattern.cpp.
References isConstantProp().
getAsConstraint()
Constraint DagLeaf::getAsConstraint () const
Definition at line 76 of file Pattern.cpp.
References isAttrMatcher(), isOperandMatcher(), and isPropMatcher().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getConditionTemplate().
getAsEnumCase()
EnumCase DagLeaf::getAsEnumCase () const
Definition at line 97 of file Pattern.cpp.
References isEnumCase().
getAsPropConstraint()
PropConstraint DagLeaf::getAsPropConstraint () const
Definition at line 82 of file Pattern.cpp.
References isPropMatcher().
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
getAsProperty()
Property DagLeaf::getAsProperty () const
Definition at line 87 of file Pattern.cpp.
References isPropDefinition().
getConditionTemplate()
std::string DagLeaf::getConditionTemplate () const
Definition at line 107 of file Pattern.cpp.
References getAsConstraint(), and mlir::tblgen::Constraint::getConditionTemplate().
getNativeCodeTemplate()
StringRef DagLeaf::getNativeCodeTemplate () const
Definition at line 111 of file Pattern.cpp.
References isNativeCodeCall().
getNumReturnsOfNativeCode()
int DagLeaf::getNumReturnsOfNativeCode () const
Definition at line 116 of file Pattern.cpp.
References isNativeCodeCall().
getStringAttr()
std::string DagLeaf::getStringAttr () const
Definition at line 121 of file Pattern.cpp.
References isStringAttr().
isAttrMatcher()
bool DagLeaf::isAttrMatcher () const
Definition at line 49 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getAsConstraint().
isConstantAttr()
bool DagLeaf::isConstantAttr () const
Definition at line 68 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getAsConstantAttr().
isConstantProp()
bool DagLeaf::isConstantProp () const
Definition at line 72 of file Pattern.cpp.
Referenced by getAsConstantProp().
isEnumCase()
bool DagLeaf::isEnumCase () const
Definition at line 70 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), and getAsEnumCase().
isNativeCodeCall()
bool DagLeaf::isNativeCodeCall () const
Definition at line 64 of file Pattern.cpp.
Referenced by getNativeCodeTemplate(), and getNumReturnsOfNativeCode().
isOperandMatcher()
bool DagLeaf::isOperandMatcher () const
Definition at line 44 of file Pattern.cpp.
Referenced by getAsConstraint().
isPropDefinition()
bool DagLeaf::isPropDefinition () const
Definition at line 59 of file Pattern.cpp.
Referenced by getAsProperty().
isPropMatcher()
bool DagLeaf::isPropMatcher () const
Definition at line 54 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols(), getAsConstraint(), and getAsPropConstraint().
isStringAttr()
bool DagLeaf::isStringAttr () const
Definition at line 74 of file Pattern.cpp.
Referenced by getStringAttr().
isUnspecified()
bool DagLeaf::isUnspecified () const
Definition at line 40 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::collectBoundSymbols().
print()
void DagLeaf::print (raw_ostream & os) const
Definition at line 131 of file Pattern.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp