MLIR: mlir::pdll::ast::InFlightDiagnostic Class Reference
mlir::pdll::ast::InFlightDiagnostic Class Reference
This class represents a diagnostic that is inflight and set to be reported.
#include "mlir/Tools/PDLL/AST/Diagnostic.h"
Public Member Functions
InFlightDiagnostic ()=default
InFlightDiagnostic (InFlightDiagnostic &&rhs)
~InFlightDiagnostic ()
Diagnostic & operator* ()
Access the internal diagnostic.
Diagnostic * operator-> ()
void report ()
Reports the diagnostic to the engine.
void abandon ()
Abandons this diagnostic so that it will no longer be reported.
operator LogicalResult () const
Allow an inflight diagnostic to be converted to 'failure', otherwise 'success' if this is an empty diagnostic.
Detailed Description
This class represents a diagnostic that is inflight and set to be reported.
This allows for last minute modifications of the diagnostic before it is emitted by a DiagnosticEngine.
Definition at line 83 of file Diagnostic.h.
Constructor & Destructor Documentation
InFlightDiagnostic() [1/2]
mlir::pdll::ast::InFlightDiagnostic::InFlightDiagnostic () default
Referenced by InFlightDiagnostic().
InFlightDiagnostic() [2/2]
mlir::pdll::ast::InFlightDiagnostic::InFlightDiagnostic (InFlightDiagnostic && rhs) inline
Definition at line 86 of file Diagnostic.h.
References InFlightDiagnostic(), and rhs.
~InFlightDiagnostic()
mlir::pdll::ast::InFlightDiagnostic::~InFlightDiagnostic () inline
Definition at line 92 of file Diagnostic.h.
References report().
Member Function Documentation
abandon()
void mlir::pdll::ast::InFlightDiagnostic::abandon () inline
Abandons this diagnostic so that it will no longer be reported.
Definition at line 105 of file Diagnostic.h.
operator LogicalResult()
mlir::pdll::ast::InFlightDiagnostic::operator LogicalResult () const inline
Allow an inflight diagnostic to be converted to 'failure', otherwise 'success' if this is an empty diagnostic.
Definition at line 109 of file Diagnostic.h.
operator*()
Diagnostic & mlir::pdll::ast::InFlightDiagnostic::operator* () inline
Access the internal diagnostic.
Definition at line 98 of file Diagnostic.h.
operator->()
Diagnostic * mlir::pdll::ast::InFlightDiagnostic::operator-> () inline
Definition at line 99 of file Diagnostic.h.
report()
void mlir::pdll::ast::InFlightDiagnostic::report ()
Reports the diagnostic to the engine.
Referenced by ~InFlightDiagnostic().
The documentation for this class was generated from the following file:
include/mlir/Tools/PDLL/AST/Diagnostic.h