MLIR: mlir::sparse_tensor::ir_detail::DimExpr Class Reference
mlir::sparse_tensor::ir_detail::DimExpr Class Reference final
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
constexpr DimExpr (AffineExpr expr)
LvlVar castLvlVar () const
std::optional< LvlVar > dyn_castLvlVar () const
Public Member Functions inherited from mlir::sparse_tensor::ir_detail::DimLvlExpr
constexpr DimLvlExpr (ExprKind ek, AffineExpr expr)
constexpr bool operator== (DimLvlExpr other) const
constexpr bool operator!= (DimLvlExpr other) const
operator bool () const
template<typename U>
constexpr bool isa () const
template<typename U>
constexpr U cast () const
template<typename U>
constexpr U dyn_cast () const
constexpr ExprKind getExprKind () const
constexpr VarKind getAllowedVarKind () const
constexpr AffineExpr getAffineExpr () const
AffineExprKind getAffineKind () const
MLIRContext * tryGetContext () const
SymVar castSymVar () const
std::optional< SymVar > dyn_castSymVar () const
Var castDimLvlVar () const
std::optional< Var > dyn_castDimLvlVar () const
std::tuple< DimLvlExpr, AffineExprKind, DimLvlExpr > unpackBinop () const
bool isValid (Ranks const &ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
Static Public Member Functions
static constexpr bool classof (DimLvlExpr const *expr)
Static Public Attributes
static constexpr ExprKind Kind = ExprKind::Dimension
Friends
class DimLvlExpr
Additional Inherited Members
Protected Types inherited from mlir::sparse_tensor::ir_detail::DimLvlExpr
enum class BindingStrength : bool { Weak = false , Strong = true }
Detailed Description
Definition at line 96 of file DimLvlMap.h.
Constructor & Destructor Documentation
DimExpr()
mlir::sparse_tensor::ir_detail::DimExpr::DimExpr (AffineExpr expr) inline explicit constexpr
Definition at line 105 of file DimLvlMap.h.
References DimLvlExpr, and Kind.
Member Function Documentation
castLvlVar()
LvlVar mlir::sparse_tensor::ir_detail::DimExpr::castLvlVar () const inline
Definition at line 107 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Var::cast(), and mlir::sparse_tensor::ir_detail::DimLvlExpr::castDimLvlVar().
classof()
constexpr bool mlir::sparse_tensor::ir_detail::DimExpr::classof (DimLvlExpr const * expr) inline static constexpr
Definition at line 102 of file DimLvlMap.h.
References DimLvlExpr, and Kind.
dyn_castLvlVar()
std::optional< LvlVar > mlir::sparse_tensor::ir_detail::DimExpr::dyn_castLvlVar () const inline
Definition at line 108 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::dyn_castDimLvlVar().
Friends And Related Symbol Documentation
DimLvlExpr
friend class DimLvlExpr friend
Definition at line 97 of file DimLvlMap.h.
References DimLvlExpr.
Referenced by classof(), DimExpr(), and DimLvlExpr.
Member Data Documentation
Kind
ExprKind mlir::sparse_tensor::ir_detail::DimExpr::Kind = ExprKind::Dimension static constexpr
Definition at line 101 of file DimLvlMap.h.
Referenced by classof(), and DimExpr().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h