MLIR: mlir::python::PyInsertionPoint Class Reference
mlir::python::PyInsertionPoint Class Reference
An insertion point maintains a pointer to a Block and a reference operation.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyInsertionPoint (const PyBlock &block)
Creates an insertion point positioned after the last operation in the block, but still inside the block.
PyInsertionPoint (PyOperationBase &beforeOperationBase)
Creates an insertion point positioned before a reference operation.
PyInsertionPoint (PyOperationRef beforeOperationRef)
Creates an insertion point positioned before a reference operation.
void insert (PyOperationBase &operationBase)
Inserts an operation.
void contextExit (const nanobind::object &excType, const nanobind::object &excVal, const nanobind::object &excTb)
PyBlock & getBlock ()
std::optional< PyOperationRef > & getRefOperation ()
Static Public Member Functions
static PyInsertionPoint atBlockBegin (PyBlock &block)
Shortcut to create an insertion point at the beginning of the block.
static PyInsertionPoint atBlockTerminator (PyBlock &block)
Shortcut to create an insertion point before the block terminator.
static PyInsertionPoint after (PyOperationBase &op)
Shortcut to create an insertion point to the node after the specified operation.
static nanobind::object contextEnter (nanobind::object insertionPoint)
Enter and exit the context manager.
Detailed Description
An insertion point maintains a pointer to a Block and a reference operation.
Calls to insert() will insert a new operation before the reference operation. If the reference operation is null, then appends to the end of the block.
Definition at line 837 of file IRModule.h.
Constructor & Destructor Documentation
PyInsertionPoint() [1/3]
PyInsertionPoint::PyInsertionPoint (const PyBlock & block)
Creates an insertion point positioned after the last operation in the block, but still inside the block.
Definition at line 1945 of file IRCore.cpp.
Referenced by after(), atBlockBegin(), and atBlockTerminator().
PyInsertionPoint() [2/3]
PyInsertionPoint::PyInsertionPoint (PyOperationBase & beforeOperationBase)
Creates an insertion point positioned before a reference operation.
Definition at line 1947 of file IRCore.cpp.
References getBlock().
PyInsertionPoint() [3/3]
PyInsertionPoint::PyInsertionPoint (PyOperationRef beforeOperationRef)
Creates an insertion point positioned before a reference operation.
Definition at line 1951 of file IRCore.cpp.
References getBlock().
Member Function Documentation
after()
PyInsertionPoint PyInsertionPoint::after (PyOperationBase & op) static
Shortcut to create an insertion point to the node after the specified operation.
Definition at line 2002 of file IRCore.cpp.
References mlir::python::PyOperation::forOperation(), mlir::python::PyOperation::getBlock(), mlir::python::PyOperationBase::getOperation(), mlirOperationGetNextInBlock(), and PyInsertionPoint().
atBlockBegin()
PyInsertionPoint PyInsertionPoint::atBlockBegin (PyBlock & block) static
Shortcut to create an insertion point at the beginning of the block.
Definition at line 1980 of file IRCore.cpp.
References mlir::python::PyOperation::forOperation(), mlirBlockGetFirstOperation(), and PyInsertionPoint().
atBlockTerminator()
PyInsertionPoint PyInsertionPoint::atBlockTerminator (PyBlock & block) static
Shortcut to create an insertion point before the block terminator.
Definition at line 1993 of file IRCore.cpp.
References mlir::python::PyOperation::forOperation(), mlirBlockGetTerminator(), and PyInsertionPoint().
contextEnter()
nb::object PyInsertionPoint::contextEnter (nanobind::object insertionPoint) static
Enter and exit the context manager.
Definition at line 2015 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::pushInsertionPoint().
contextExit()
void PyInsertionPoint::contextExit (const nanobind::object & excType, const nanobind::object & excVal, const nanobind::object & excTb)
Definition at line 2019 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::popInsertionPoint().
getBlock()
PyBlock & mlir::python::PyInsertionPoint::getBlock () inline
Definition at line 864 of file IRModule.h.
Referenced by PyInsertionPoint(), and PyInsertionPoint().
getRefOperation()
std::optional< PyOperationRef > & mlir::python::PyInsertionPoint::getRefOperation () inline
Definition at line 865 of file IRModule.h.
insert()
void PyInsertionPoint::insert (PyOperationBase & operationBase)
Inserts an operation.
Definition at line 1954 of file IRCore.cpp.
References mlir::python::PyOperationBase::getOperation(), mlir::python::PyOperation::isAttached(), mlirBlockGetTerminator(), mlirBlockInsertOwnedOperationBefore(), and mlir::python::PyOperation::setAttached().
Referenced by maybeInsertOperation().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp