MLIR: mlir::acc::impl::ACCBindRoutineBase< DerivedT > Class Template Reference
mlir::acc::impl::ACCBindRoutineBase< DerivedT > Class Template Reference
Public Types
using Base = ACCBindRoutineBase
Public Member Functions
ACCBindRoutineBase ()
ACCBindRoutineBase (const ACCBindRoutineBase &other)
ACCBindRoutineBase & operator= (const ACCBindRoutineBase &)=delete
ACCBindRoutineBase (ACCBindRoutineBase &&)=delete
ACCBindRoutineBase & operator= (ACCBindRoutineBase &&)=delete
~ACCBindRoutineBase ()=default
::llvm::StringRef getArgument () const override
Return the command line argument used when registering this pass.
::llvm::StringRef getDescription () const override
Return the command line description used when registering this pass.
::llvm::StringRef getName () const override
Returns the derived pass name.
std::unique_ptr<::mlir::Pass > clonePass () const override
A clone method to create a copy of this pass.
void getDependentDialects (::mlir::DialectRegistry &registry) const override
Return the dialect that must be loaded in the context before this pass.
ACCBindRoutineBase (ACCBindRoutineOptions options)
Explicitly declare the TypeID for this class.
Public Member Functions inherited from mlir::OperationPass< OpT >
~OperationPass () override=default
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Static Public Member Functions
static constexpr ::llvm::StringLiteral getArgumentName ()
Returns the command-line argument attached to this pass.
static constexpr ::llvm::StringLiteral getPassName ()
Returns the derived pass name.
static bool classof (const ::mlir::Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Attributes
::mlir::Pass::Option< mlir::acc::DeviceType > deviceType
Friends
std::unique_ptr<::mlir::Pass > createACCBindRoutine ()
std::unique_ptr<::mlir::Pass > createACCBindRoutine (ACCBindRoutineOptions options)
Additional Inherited Members
Protected Member Functions inherited from mlir::InterfacePass< mlir::FunctionOpInterface >
OperationPass (TypeID passID)
OperationPass (const OperationPass &)=default
OperationPass (OperationPass &&)=delete
bool canScheduleOn (Operation *op) const final
Indicate if the current pass can be scheduled on the given operation type.
mlir::FunctionOpInterface getOperation ()
Return the current operation being transformed.
AnalysisT & getAnalysis ()
Query an analysis for the current operation.
Protected Member Functions inherited from mlir::OperationPass< OpT >
OperationPass (TypeID passID)
OperationPass (const OperationPass &)=default
OperationPass & operator= (const OperationPass &)=delete
OperationPass (OperationPass &&)=delete
OperationPass & operator= (OperationPass &&)=delete
bool canScheduleOn (RegisteredOperationName opName) const final
Indicate if the current pass can be scheduled on the given operation type.
OpT getOperation ()
Return the current operation being transformed.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current operation of the specific derived operation type.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Static Protected Member Functions inherited from mlir::OperationPass< OpT >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Detailed Description
template<typename DerivedT>
class mlir::acc::impl::ACCBindRoutineBase< DerivedT >
Definition at line 51 of file ACCBindRoutine.cpp.
Member Typedef Documentation
Base
template<typename DerivedT> using mlir::acc::impl::ACCBindRoutineBase< DerivedT >::Base = ACCBindRoutineBase
Definition at line 53 of file ACCBindRoutine.cpp.
Constructor & Destructor Documentation
ACCBindRoutineBase() [1/4]
template<typename DerivedT> mlir::acc::impl::ACCBindRoutineBase< DerivedT >::ACCBindRoutineBase () inline
Definition at line 55 of file ACCBindRoutine.cpp.
Referenced by classof().
ACCBindRoutineBase() [2/4]
template<typename DerivedT> mlir::acc::impl::ACCBindRoutineBase< DerivedT >::ACCBindRoutineBase (const ACCBindRoutineBase< DerivedT > & other) inline
Definition at line 56 of file ACCBindRoutine.cpp.
ACCBindRoutineBase() [3/4]
template<typename DerivedT> mlir::acc::impl::ACCBindRoutineBase< DerivedT >::ACCBindRoutineBase (ACCBindRoutineBase< DerivedT > &&) delete
~ACCBindRoutineBase()
template<typename DerivedT> mlir::acc::impl::ACCBindRoutineBase< DerivedT >::~ACCBindRoutineBase () default
ACCBindRoutineBase() [4/4]
template<typename DerivedT> mlir::acc::impl::ACCBindRoutineBase< DerivedT >::ACCBindRoutineBase (ACCBindRoutineOptions options) inline
Explicitly declare the TypeID for this class.
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 96 of file ACCBindRoutine.cpp.
Member Function Documentation
classof()
template<typename DerivedT> bool mlir::acc::impl::ACCBindRoutineBase< DerivedT >::classof (const ::mlir::Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 77 of file ACCBindRoutine.cpp.
References ACCBindRoutineBase().
clonePass()
template<typename DerivedT> std::unique_ptr<::mlir::Pass > mlir::acc::impl::ACCBindRoutineBase< DerivedT >::clonePass () const inline override virtual
A clone method to create a copy of this pass.
Implements mlir::Pass.
Definition at line 82 of file ACCBindRoutine.cpp.
References mlir::InterfacePass< mlir::FunctionOpInterface >::getOperation(), and mlir::Pass::runOnOperation().
getArgument()
template<typename DerivedT> ::llvm::StringRef mlir::acc::impl::ACCBindRoutineBase< DerivedT >::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 66 of file ACCBindRoutine.cpp.
getArgumentName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::acc::impl::ACCBindRoutineBase< DerivedT >::getArgumentName () inline static
Returns the command-line argument attached to this pass.
Definition at line 63 of file ACCBindRoutine.cpp.
getDependentDialects()
template<typename DerivedT> void mlir::acc::impl::ACCBindRoutineBase< DerivedT >::getDependentDialects (::mlir::DialectRegistry & registry) const inline override
Return the dialect that must be loaded in the context before this pass.
Definition at line 87 of file ACCBindRoutine.cpp.
References mlir::InterfacePass< mlir::FunctionOpInterface >::getAnalysis(), and mlir::Pass::getCachedParentAnalysis().
getDescription()
template<typename DerivedT> ::llvm::StringRef mlir::acc::impl::ACCBindRoutineBase< DerivedT >::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 68 of file ACCBindRoutine.cpp.
getName()
template<typename DerivedT> ::llvm::StringRef mlir::acc::impl::ACCBindRoutineBase< DerivedT >::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 74 of file ACCBindRoutine.cpp.
References deviceType.
getPassName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::acc::impl::ACCBindRoutineBase< DerivedT >::getPassName () inline static
Returns the derived pass name.
Definition at line 71 of file ACCBindRoutine.cpp.
References deviceType.
operator=() [1/2]
template<typename DerivedT> ACCBindRoutineBase & mlir::acc::impl::ACCBindRoutineBase< DerivedT >::operator= (ACCBindRoutineBase< DerivedT > &&) delete
operator=() [2/2]
template<typename DerivedT> ACCBindRoutineBase & mlir::acc::impl::ACCBindRoutineBase< DerivedT >::operator= (const ACCBindRoutineBase< DerivedT > &) delete
Friends And Related Symbol Documentation
createACCBindRoutine [1/2]
template<typename DerivedT> std::unique_ptr<::mlir::Pass > createACCBindRoutine () friend
Definition at line 109 of file ACCBindRoutine.cpp.
createACCBindRoutine [2/2]
template<typename DerivedT> std::unique_ptr<::mlir::Pass > createACCBindRoutine (ACCBindRoutineOptions options) friend
Definition at line 113 of file ACCBindRoutine.cpp.
References mlir::acc::OpenACCSupport::emitNYI(), and mlir::acc::getRoutineInfoAttrName().
Member Data Documentation
deviceType
template<typename DerivedT> ::mlir::Pass::Option<mlir::acc::DeviceType> mlir::acc::impl::ACCBindRoutineBase< DerivedT >::deviceType protected
Initial value:
{*this, "device-type", ::llvm::cl::desc(R"PO(Target device type. One use case is ensuring that device_type-specific clauses are considered. Another is device-specific specializations.)PO"), ::llvm::cl::init(mlir::acc::DeviceType::None), ::llvm::cl::values(
       clEnumValN(mlir::acc::DeviceType::None, "none", "none"),
       clEnumValN(mlir::acc::DeviceType::Host, "host", "host"),
       clEnumValN(mlir::acc::DeviceType::Multicore, "multicore", "multicore"),
       clEnumValN(mlir::acc::DeviceType::Nvidia, "nvidia", "nvidia"),
       clEnumValN(mlir::acc::DeviceType::Radeon, "radeon", "radeon"))
    }
Definition at line 100 of file ACCBindRoutine.cpp.
Referenced by getName(), and getPassName().
The documentation for this class was generated from the following file:
lib/Dialect/OpenACC/Transforms/ACCBindRoutine.cpp