MLIR: mlir::spirv::InterfaceVarABIAttr Class Reference
mlir::spirv::InterfaceVarABIAttr Class Reference
An attribute that specifies the information regarding the interface variable: descriptor set, binding, storage class.
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
Public Types
using Base
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
using Base
Utility declarations for the concrete attribute class.
using ImplType
using HasTraitFn
Public Member Functions
uint32_t getDescriptorSet ()
Returns descriptor set.
uint32_t getBinding ()
Returns binding.
std::optional< StorageClass > getStorageClass ()
Returns spirv::StorageClass.
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static InterfaceVarABIAttr get (uint32_t descriptorSet, uint32_t binding, std::optional< StorageClass > storageClass, MLIRContext *context)
Gets a InterfaceVarABIAttr.
static InterfaceVarABIAttr get (IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass)
static StringRef getKindName ()
Returns the attribute kind's name (without the 'spirv.' prefix).
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
static ConcreteType get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteType getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.interface_var_abi"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that specifies the information regarding the interface variable: descriptor set, binding, storage class.
Definition at line 54 of file SPIRVAttributes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits >::Base
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
Member Function Documentation
get() [1/2]
spirv::InterfaceVarABIAttr spirv::InterfaceVarABIAttr::get (IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass) static
Definition at line 137 of file SPIRVAttributes.cpp.
get() [2/2]
InterfaceVarABIAttr mlir::spirv::InterfaceVarABIAttr::get (uint32_t descriptorSet, uint32_t binding, std::optional< StorageClass > storageClass, MLIRContext * context) static
Gets a InterfaceVarABIAttr.
Referenced by parseInterfaceVarABIAttr().
getBinding()
uint32_t spirv::InterfaceVarABIAttr::getBinding ()
Returns binding.
Definition at line 148 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >::getImpl().
Referenced by createGlobalVarForEntryPointArgument(), createGlobalVarForGraphEntryPoint(), and print().
getDescriptorSet()
uint32_t spirv::InterfaceVarABIAttr::getDescriptorSet ()
Returns descriptor set.
Definition at line 152 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >::getImpl().
Referenced by createGlobalVarForEntryPointArgument(), createGlobalVarForGraphEntryPoint(), and print().
getKindName()
StringRef spirv::InterfaceVarABIAttr::getKindName () static
Returns the attribute kind's name (without the 'spirv.' prefix).
Definition at line 144 of file SPIRVAttributes.cpp.
Referenced by print().
getStorageClass()
std::optional< spirv::StorageClass > spirv::InterfaceVarABIAttr::getStorageClass ()
Returns spirv::StorageClass.
Definition at line 157 of file SPIRVAttributes.cpp.
Referenced by createGlobalVarForEntryPointArgument(), createGlobalVarForGraphEntryPoint(), and print().
verifyInvariants()
LogicalResult spirv::InterfaceVarABIAttr::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass) static
Definition at line 166 of file SPIRVAttributes.cpp.
References mlir::emitError(), and success().
Member Data Documentation
name
StringLiteral mlir::spirv::InterfaceVarABIAttr::name = "spirv.interface_var_abi" static constexpr
Definition at line 84 of file SPIRVAttributes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVAttributes.h
lib/Dialect/SPIRV/IR/SPIRVAttributes.cpp