MLIR: mlir::shard::Sharding Class Reference
mlir::shard::Sharding Class Reference
#include "mlir/Dialect/Shard/IR/ShardOps.h"
Public Member Functions
Sharding (::mlir::FlatSymbolRefAttr grid_=nullptr)
Sharding (Value rhs)
::mlir::FlatSymbolRefAttr getGridAttr () const
::llvm::StringRef getGrid () const
ArrayRef< GridAxesAttr > getSplitAxes () const
ArrayRef< int64_t > getStaticHaloSizes () const
ArrayRef< int64_t > getStaticShardedDimsOffsets () const
ArrayRef< Value > getDynamicHaloSizes () const
ArrayRef< Value > getDynamicShardedDimsOffsets () const
operator bool () const
bool operator== (Value rhs) const
bool operator!= (Value rhs) const
bool operator== (const Sharding &rhs) const
bool operator!= (const Sharding &rhs) const
bool equalSplitAxes (const Sharding &rhs) const
bool equalHaloAndShardSizes (const Sharding &rhs) const
bool equalHaloSizes (const Sharding &rhs) const
bool equalShardSizes (const Sharding &rhs) const
Static Public Member Functions
static Sharding get (::mlir::FlatSymbolRefAttr grid_, ArrayRef< GridAxesAttr > split_axes_, ArrayRef< int64_t > static_halo_sizes_={}, ArrayRef< int64_t > static_sharded_dims_offsets_={}, ArrayRef< Value > dynamic_halo_sizes_={}, ArrayRef< Value > dynamic_sharded_dims_offsets_={})
Detailed Description
Definition at line 42 of file ShardOps.h.
Constructor & Destructor Documentation
Sharding() [1/2]
Sharding::Sharding (::mlir::FlatSymbolRefAttr grid_ = nullptr)
Definition at line 751 of file ShardOps.cpp.
Referenced by equalHaloAndShardSizes(), equalHaloSizes(), equalShardSizes(), equalSplitAxes(), get(), operator!=(), operator==(), and Sharding().
Sharding() [2/2]
Sharding::Sharding (Value rhs)
Definition at line 753 of file ShardOps.cpp.
References get(), rhs, and Sharding().
Member Function Documentation
equalHaloAndShardSizes()
bool Sharding::equalHaloAndShardSizes (const Sharding & rhs) const
Definition at line 707 of file ShardOps.cpp.
References equalHaloSizes(), equalShardSizes(), rhs, and Sharding().
Referenced by operator==(), and operator==().
equalHaloSizes()
bool Sharding::equalHaloSizes (const Sharding & rhs) const
Definition at line 727 of file ShardOps.cpp.
References getDynamicHaloSizes(), getStaticHaloSizes(), rhs, and Sharding().
Referenced by equalHaloAndShardSizes(), and mlir::shard::tryUpdateHaloInResharding().
equalShardSizes()
bool Sharding::equalShardSizes (const Sharding & rhs) const
Definition at line 711 of file ShardOps.cpp.
References getDynamicShardedDimsOffsets(), getStaticShardedDimsOffsets(), rhs, and Sharding().
Referenced by equalHaloAndShardSizes().
equalSplitAxes()
bool Sharding::equalSplitAxes (const Sharding & rhs) const
Definition at line 688 of file ShardOps.cpp.
References getGrid(), getSplitAxes(), rhs, and Sharding().
Referenced by operator==(), operator==(), and mlir::shard::tryUpdateHaloInResharding().
get()
Sharding Sharding::get (::mlir::FlatSymbolRefAttr grid_, ArrayRef< GridAxesAttr > split_axes_, ArrayRef< int64_t > static_halo_sizes_ = {}, ArrayRef< int64_t > static_sharded_dims_offsets_ = {}, ArrayRef< Value > dynamic_halo_sizes_ = {}, ArrayRef< Value > dynamic_sharded_dims_offsets_ = {}) static
Definition at line 769 of file ShardOps.cpp.
References mlir::clone(), mlir::detail::DenseArrayAttrImpl< int16_t >::get(), and Sharding().
Referenced by getSharding(), getSharding(), Sharding(), mlir::shard::targetShardingInMoveLastAxis(), and mlir::shard::targetShardingInUnsplitLastAxis().
getDynamicHaloSizes()
ArrayRef< Value > mlir::shard::Sharding::getDynamicHaloSizes () const inline
Definition at line 67 of file ShardOps.h.
Referenced by equalHaloSizes(), and mlir::shard::tryUpdateHaloInResharding().
getDynamicShardedDimsOffsets()
ArrayRef< Value > mlir::shard::Sharding::getDynamicShardedDimsOffsets () const inline
Definition at line 68 of file ShardOps.h.
Referenced by equalShardSizes().
getGrid()
::llvm::StringRef mlir::shard::Sharding::getGrid () const inline
Definition at line 61 of file ShardOps.h.
Referenced by equalSplitAxes().
getGridAttr()
::mlir::FlatSymbolRefAttr mlir::shard::Sharding::getGridAttr () const inline
Definition at line 60 of file ShardOps.h.
Referenced by mlir::shard::detail::defaultGetShardingOption(), mlir::shard::targetShardingInMoveLastAxis(), and mlir::shard::targetShardingInUnsplitLastAxis().
getSplitAxes()
ArrayRef< GridAxesAttr > mlir::shard::Sharding::getSplitAxes () const inline
Definition at line 62 of file ShardOps.h.
Referenced by mlir::shard::detail::defaultGetShardingOption(), mlir::shard::detectMoveLastSplitAxisInResharding(), mlir::shard::detectSplitLastAxisInResharding(), mlir::shard::detectUnsplitLastAxisInResharding(), equalSplitAxes(), mlir::shard::impl::PartitionBase< DerivedT >::getName(), mlir::shard::isFullReplication(), mlir::shard::shardShapedType(), mlir::shard::targetShardingInMoveLastAxis(), mlir::shard::targetShardingInUnsplitLastAxis(), and mlir::shard::tryUpdateHaloInResharding().
getStaticHaloSizes()
ArrayRef< int64_t > mlir::shard::Sharding::getStaticHaloSizes () const inline
Definition at line 63 of file ShardOps.h.
Referenced by equalHaloSizes(), mlir::shard::reshardOn1DGrid(), mlir::shard::shardShapedType(), and mlir::shard::tryUpdateHaloInResharding().
getStaticShardedDimsOffsets()
ArrayRef< int64_t > mlir::shard::Sharding::getStaticShardedDimsOffsets () const inline
Definition at line 64 of file ShardOps.h.
Referenced by equalShardSizes(), mlir::shard::reshardOn1DGrid(), mlir::shard::shardShapedType(), and mlir::shard::tryUpdateHaloInResharding().
operator bool()
mlir::shard::Sharding::operator bool () const inline
Definition at line 71 of file ShardOps.h.
operator!=() [1/2]
bool Sharding::operator!= (const Sharding & rhs) const
Definition at line 749 of file ShardOps.cpp.
References rhs, and Sharding().
operator!=() [2/2]
bool Sharding::operator!= (Value rhs) const
Definition at line 743 of file ShardOps.cpp.
References rhs.
operator==() [1/2]
bool Sharding::operator== (const Sharding & rhs) const
Definition at line 745 of file ShardOps.cpp.
References equalHaloAndShardSizes(), equalSplitAxes(), rhs, and Sharding().
operator==() [2/2]
bool Sharding::operator== (Value rhs) const
Definition at line 739 of file ShardOps.cpp.
References equalHaloAndShardSizes(), equalSplitAxes(), and rhs.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Shard/IR/ShardOps.h
lib/Dialect/Shard/IR/ShardOps.cpp