MLIR: mlir::AffineExprVisitor< SubClass, RetTy > Class Template Reference
mlir::AffineExprVisitor< SubClass, RetTy > Class Template Reference
Base class for AffineExpr visitors/walkers.
#include "mlir/IR/AffineExprVisitor.h"
Public Member Functions
RetTy walkPostOrder (AffineExpr expr)
RetTy visit (AffineExpr expr)
RetTy visitAffineBinaryOpExpr (AffineBinaryOpExpr expr)
RetTy visitAddExpr (AffineBinaryOpExpr expr)
RetTy visitMulExpr (AffineBinaryOpExpr expr)
RetTy visitModExpr (AffineBinaryOpExpr expr)
RetTy visitFloorDivExpr (AffineBinaryOpExpr expr)
RetTy visitCeilDivExpr (AffineBinaryOpExpr expr)
RetTy visitConstantExpr (AffineConstantExpr expr)
RetTy visitDimExpr (AffineDimExpr expr)
RetTy visitSymbolExpr (AffineSymbolExpr expr)
Detailed Description
template<typename SubClass, typename RetTy = void>
class mlir::AffineExprVisitor< SubClass, RetTy >
Base class for AffineExpr visitors/walkers.
AffineExpr visitors are used when you want to perform different actions for different kinds of AffineExprs without having to use lots of casts and a big switch instruction.
To define your own visitor, inherit from this class, specifying your new type for the 'SubClass' template parameter, and "override" visitXXX functions in your class. This class is defined in terms of statically resolved overloading, not virtual functions.
For example, here is a visitor that counts the number of for AffineDimExprs in an AffineExpr.
/// Declare the class. Note that we derive from AffineExprVisitor /// instantiated with our new subclasses_ type.
struct DimExprCounter : public AffineExprVisitor<DimExprCounter> { unsigned numDimExprs; DimExprCounter() : numDimExprs(0) {} void visitDimExpr(AffineDimExpr expr) { ++numDimExprs; } };
And this class would be used like this: DimExprCounter dec; dec.visit(affineExpr); numDimExprs = dec.numDimExprs;
AffineExprVisitor provides visit methods for the following binary affine op expressions: AffineBinaryAddOpExpr, AffineBinaryMulOpExpr, AffineBinaryModOpExpr, AffineBinaryFloorDivOpExpr, AffineBinaryCeilDivOpExpr. Note that default implementations of these methods will call the general AffineBinaryOpExpr method.
In addition, visit methods are provided for the following affine Note that if you don't implement visitXXX for some affine expression type, the visitXXX method for Instruction superclass will be invoked.
Note that this class is specifically designed as a template to avoid virtual function call overhead. Defining and using a AffineExprVisitor is just as efficient as having your own switch instruction over the instruction opcode.
Definition at line 68 of file AffineExprVisitor.h.
Member Function Documentation
visit()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visit (AffineExpr expr) inline
Definition at line 116 of file AffineExprVisitor.h.
visitAddExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitAddExpr (AffineBinaryOpExpr expr) inline
Definition at line 164 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitAffineBinaryOpExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitAffineBinaryOpExpr (AffineBinaryOpExpr expr) inline
Definition at line 163 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visitAddExpr(), mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visitCeilDivExpr(), mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visitFloorDivExpr(), mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visitModExpr(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visitMulExpr().
visitCeilDivExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitCeilDivExpr (AffineBinaryOpExpr expr) inline
Definition at line 176 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitConstantExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitConstantExpr (AffineConstantExpr expr) inline
Definition at line 179 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitDimExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitDimExpr (AffineDimExpr expr) inline
Definition at line 180 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitFloorDivExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitFloorDivExpr (AffineBinaryOpExpr expr) inline
Definition at line 173 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitModExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitModExpr (AffineBinaryOpExpr expr) inline
Definition at line 170 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitMulExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitMulExpr (AffineBinaryOpExpr expr) inline
Definition at line 167 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
visitSymbolExpr()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::visitSymbolExpr (AffineSymbolExpr expr) inline
Definition at line 181 of file AffineExprVisitor.h.
Referenced by mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visit(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::walkPostOrder().
walkPostOrder()
template<typename SubClass, typename RetTy = void> RetTy mlir::AffineExprVisitor< SubClass, RetTy >::walkPostOrder (AffineExpr expr) inline
Definition at line 74 of file AffineExprVisitor.h.
Referenced by mlir::simplifyAffineExpr(), and mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >::visitSymbolExpr().
The documentation for this class was generated from the following file:
include/mlir/IR/AffineExprVisitor.h