MLIR: mlir::pdll::ast::Node::NodeBase< T, BaseT > Class Template Reference
mlir::pdll::ast::Node::NodeBase< T, BaseT > Class Template Reference
This CRTP class provides several utilies when defining new AST nodes.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Types
using Base = NodeBase<T, BaseT>
Static Public Member Functions
static bool classof (const Node *node)
Provide type casting support.
Protected Member Functions
template<typename... Args>
NodeBase (SMRange loc, Args &&...args)
Detailed Description
template<typename T, typename BaseT>
class mlir::pdll::ast::Node::NodeBase< T, BaseT >
This CRTP class provides several utilies when defining new AST nodes.
Definition at line 112 of file Nodes.h.
Member Typedef Documentation
Base
template<typename T, typename BaseT> using mlir::pdll::ast::Node::NodeBase< T, BaseT >::Base = NodeBase<T, BaseT>
Definition at line 114 of file Nodes.h.
Constructor & Destructor Documentation
NodeBase()
template<typename T, typename BaseT> template<typename... Args> mlir::pdll::ast::Node::NodeBase< T, BaseT >::NodeBase (SMRange loc, Args &&... args) inline explicit protected
Definition at line 123 of file Nodes.h.
References mlir::get().
Member Function Documentation
classof()
template<typename T, typename BaseT> bool mlir::pdll::ast::Node::NodeBase< T, BaseT >::classof (const Node * node) inline static
Provide type casting support.
Definition at line 117 of file Nodes.h.
References mlir::TypeID::get(), mlir::pdll::ast::Node::getTypeID(), and mlir::pdll::ast::Node::Node().
The documentation for this class was generated from the following file:
include/mlir/Tools/PDLL/AST/Nodes.h