MLIR: mlir::ImplicitLocOpBuilder Class Reference
mlir::ImplicitLocOpBuilder Class Reference
ImplicitLocOpBuilder maintains a 'current location', allowing use of the create<> method without specifying the location.
#include "mlir/IR/Builders.h"
Public Member Functions
template<typename... T>
ImplicitLocOpBuilder (Location loc, T &&...operands)
OpBuilder has a bunch of convenience constructors - we support them all with the additional Location.
Location getLoc () const
Accessors for the implied location.
void setLoc (Location loc)
template<typename OpTy , typename... Args>
OpTy create (Args &&...args)
Create an operation of specific op type at the current insertion point and location.
template<typename OpTy , typename... Args>
void createOrFold (llvm::SmallVectorImpl< Value > &results, Args &&...args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< mlir::OpTrait::OneResult >), Value > createOrFold (Args &&...args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< mlir::OpTrait::ZeroResults >), OpTy > createOrFold (Args &&...args)
Overload to create or fold a zero result operation.
mlir::InFlightDiagnostic emitError (const llvm::Twine &message=llvm::Twine())
This builder can also be used to emit diagnostics to the current location.
mlir::InFlightDiagnostic emitWarning (const llvm::Twine &message=llvm::Twine())
mlir::InFlightDiagnostic emitRemark (const llvm::Twine &message=llvm::Twine())
Operation * create (const OperationState &state)
Creates an operation given the fields represented as an OperationState.
Operation * create (Location loc, StringAttr opName, ValueRange operands, TypeRange types={}, ArrayRef< NamedAttribute > attributes={}, BlockRange successors={}, MutableArrayRef< std::unique_ptr< Region >> regions={})
Creates an operation with the given fields.
template<typename OpTy , typename... Args>
OpTy create (Location location, Args &&...args)
Create an operation of specific op type at the current insertion point.
template<typename OpTy , typename... Args>
void createOrFold (SmallVectorImpl< Value > &results, Location location, Args &&...args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< OpTrait::OneResult >), Value > createOrFold (Location location, Args &&...args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< OpTrait::ZeroResults >), OpTy > createOrFold (Location location, Args &&...args)
Overload to create or fold a zero result operation.
Public Member Functions inherited from mlir::OpBuilder
OpBuilder (MLIRContext *ctx, Listener *listener=nullptr)
Create a builder with the given context.
OpBuilder (Region *region, Listener *listener=nullptr)
Create a builder and set the insertion point to the start of the region.
OpBuilder (Region &region, Listener *listener=nullptr)
OpBuilder (Operation *op, Listener *listener=nullptr)
Create a builder and set insertion point to the given operation, which will cause subsequent insertions to go right before it.
OpBuilder (Block *block, Block::iterator insertPoint, Listener *listener=nullptr)
void setListener (Listener *newListener)
Sets the listener of this builder to the one provided.
Listener * getListener () const
Returns the current listener of this builder, or nullptr if this builder doesn't have a listener.
void clearInsertionPoint ()
Reset the insertion point to no location.
InsertPoint saveInsertionPoint () const
Return a saved insertion point.
void restoreInsertionPoint (InsertPoint ip)
Restore the insert point to a previously saved point.
void setInsertionPoint (Block *block, Block::iterator insertPoint)
Set the insertion point to the specified location.
void setInsertionPoint (Operation *op)
Sets the insertion point to the specified operation, which will cause subsequent insertions to go right before it.
void setInsertionPointAfter (Operation *op)
Sets the insertion point to the node after the specified operation, which will cause subsequent insertions to go right after it.
void setInsertionPointAfterValue (Value val)
Sets the insertion point to the node after the specified value.
void setInsertionPointToStart (Block *block)
Sets the insertion point to the start of the specified block.
void setInsertionPointToEnd (Block *block)
Sets the insertion point to the end of the specified block.
Block * getInsertionBlock () const
Return the block the current insertion point belongs to.
Block::iterator getInsertionPoint () const
Returns the current insertion point of the builder.
Block * getBlock () const
Returns the current block of the builder.
Block * createBlock (Region *parent, Region::iterator insertPt={}, TypeRange argTypes={}, ArrayRef< Location > locs={})
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Block * createBlock (Block *insertBefore, TypeRange argTypes={}, ArrayRef< Location > locs={})
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Operation * insert (Operation *op)
Insert the given operation at the current insertion point and return it.
Operation * create (const OperationState &state)
Creates an operation given the fields represented as an OperationState.
Operation * create (Location loc, StringAttr opName, ValueRange operands, TypeRange types={}, ArrayRef< NamedAttribute > attributes={}, BlockRange successors={}, MutableArrayRef< std::unique_ptr< Region >> regions={})
Creates an operation with the given fields.
template<typename OpTy , typename... Args>
OpTy create (Location location, Args &&...args)
Create an operation of specific op type at the current insertion point.
template<typename OpTy , typename... Args>
void createOrFold (SmallVectorImpl< Value > &results, Location location, Args &&...args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< OpTrait::OneResult >), Value > createOrFold (Location location, Args &&...args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< OpTrait::ZeroResults >), OpTy > createOrFold (Location location, Args &&...args)
Overload to create or fold a zero result operation.
LogicalResult tryFold (Operation *op, SmallVectorImpl< Value > &results, SmallVectorImpl< Operation * > *materializedConstants=nullptr)
Attempts to fold the given operation and places new results within results.
Operation * clone (Operation &op, IRMapping &mapper)
Creates a deep copy of the specified operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (Operation &op)
Operation * cloneWithoutRegions (Operation &op, IRMapping &mapper)
Creates a deep copy of this operation but keep the operation regions empty.
Operation * cloneWithoutRegions (Operation &op)
template<typename OpT >
OpT cloneWithoutRegions (OpT op)
void cloneRegionBefore (Region &region, Region &parent, Region::iterator before, IRMapping &mapping)
Clone the blocks that belong to "region" before the given position in another region "parent".
void cloneRegionBefore (Region &region, Region &parent, Region::iterator before)
void cloneRegionBefore (Region &region, Block *before)
Public Member Functions inherited from mlir::Builder
Builder (MLIRContext *context)
Builder (Operation *op)
MLIRContext * getContext () const
Location getUnknownLoc ()
Location getFusedLoc (ArrayRef< Location > locs, Attribute metadata=Attribute())
FloatType getF8E8M0Type ()
FloatType getBF16Type ()
FloatType getF16Type ()
FloatType getTF32Type ()
FloatType getF32Type ()
FloatType getF64Type ()
FloatType getF80Type ()
FloatType getF128Type ()
IndexType getIndexType ()
IntegerType getI1Type ()
IntegerType getI2Type ()
IntegerType getI4Type ()
IntegerType getI8Type ()
IntegerType getI16Type ()
IntegerType getI32Type ()
IntegerType getI64Type ()
IntegerType getIntegerType (unsigned width)
IntegerType getIntegerType (unsigned width, bool isSigned)
FunctionType getFunctionType (TypeRange inputs, TypeRange results)
TupleType getTupleType (TypeRange elementTypes)
NoneType getNoneType ()
template<typename Ty , typename... Args>
Ty getType (Args &&...args)
Get or construct an instance of the type Ty with provided arguments.
template<typename Attr , typename... Args>
Attr getAttr (Args &&...args)
Get or construct an instance of the attribute Attr with provided arguments.
NamedAttribute getNamedAttr (StringRef name, Attribute val)
UnitAttr getUnitAttr ()
BoolAttr getBoolAttr (bool value)
DictionaryAttr getDictionaryAttr (ArrayRef< NamedAttribute > value)
IntegerAttr getIntegerAttr (Type type, int64_t value)
IntegerAttr getIntegerAttr (Type type, const APInt &value)
FloatAttr getFloatAttr (Type type, double value)
FloatAttr getFloatAttr (Type type, const APFloat &value)
StringAttr getStringAttr (const Twine &bytes)
ArrayAttr getArrayAttr (ArrayRef< Attribute > value)
TypedAttr getZeroAttr (Type type)
TypedAttr getOneAttr (Type type)
FloatAttr getF16FloatAttr (float value)
FloatAttr getF32FloatAttr (float value)
FloatAttr getF64FloatAttr (double value)
IntegerAttr getI8IntegerAttr (int8_t value)
IntegerAttr getI16IntegerAttr (int16_t value)
IntegerAttr getI32IntegerAttr (int32_t value)
IntegerAttr getI64IntegerAttr (int64_t value)
IntegerAttr getIndexAttr (int64_t value)
IntegerAttr getSI32IntegerAttr (int32_t value)
Signed and unsigned integer attribute getters.
IntegerAttr getUI32IntegerAttr (uint32_t value)
DenseIntElementsAttr getBoolVectorAttr (ArrayRef< bool > values)
Vector-typed DenseIntElementsAttr getters. values must not be empty.
DenseIntElementsAttr getI32VectorAttr (ArrayRef< int32_t > values)
DenseIntElementsAttr getI64VectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexVectorAttr (ArrayRef< int64_t > values)
DenseFPElementsAttr getF32VectorAttr (ArrayRef< float > values)
DenseFPElementsAttr getF64VectorAttr (ArrayRef< double > values)
DenseIntElementsAttr getI32TensorAttr (ArrayRef< int32_t > values)
Tensor-typed DenseIntElementsAttr getters.
DenseIntElementsAttr getI64TensorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexTensorAttr (ArrayRef< int64_t > values)
DenseBoolArrayAttr getDenseBoolArrayAttr (ArrayRef< bool > values)
Tensor-typed DenseArrayAttr getters.
DenseI8ArrayAttr getDenseI8ArrayAttr (ArrayRef< int8_t > values)
DenseI16ArrayAttr getDenseI16ArrayAttr (ArrayRef< int16_t > values)
DenseI32ArrayAttr getDenseI32ArrayAttr (ArrayRef< int32_t > values)
DenseI64ArrayAttr getDenseI64ArrayAttr (ArrayRef< int64_t > values)
DenseF32ArrayAttr getDenseF32ArrayAttr (ArrayRef< float > values)
DenseF64ArrayAttr getDenseF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getAffineMapArrayAttr (ArrayRef< AffineMap > values)
ArrayAttr getBoolArrayAttr (ArrayRef< bool > values)
ArrayAttr getI32ArrayAttr (ArrayRef< int32_t > values)
ArrayAttr getI64ArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getIndexArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getF32ArrayAttr (ArrayRef< float > values)
ArrayAttr getF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getStrArrayAttr (ArrayRef< StringRef > values)
ArrayAttr getTypeArrayAttr (TypeRange values)
AffineExpr getAffineDimExpr (unsigned position)
AffineExpr getAffineSymbolExpr (unsigned position)
AffineExpr getAffineConstantExpr (int64_t constant)
AffineMap getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
AffineMap getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
AffineMap getDimIdentityMap ()
AffineMap getMultiDimIdentityMap (unsigned rank)
AffineMap getSymbolIdentityMap ()
AffineMap getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
AffineMap getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Static Public Member Functions
static ImplicitLocOpBuilder atBlockBegin (Location loc, Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
static ImplicitLocOpBuilder atBlockEnd (Location loc, Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
static ImplicitLocOpBuilder atBlockTerminator (Location loc, Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the block terminator.
Static Public Member Functions inherited from mlir::OpBuilder
static OpBuilder atBlockBegin (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
static OpBuilder atBlockEnd (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
static OpBuilder atBlockTerminator (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the block terminator.
Additional Inherited Members
Protected Attributes inherited from mlir::OpBuilder
Listener * listener
The optional listener for events of this builder.
Protected Attributes inherited from mlir::Builder
MLIRContext * context
Detailed Description
ImplicitLocOpBuilder maintains a 'current location', allowing use of the create<> method without specifying the location.
It is otherwise the same as OpBuilder.
Definition at line 621 of file Builders.h.
Constructor & Destructor Documentation
ImplicitLocOpBuilder()
template<typename... T> mlir::ImplicitLocOpBuilder::ImplicitLocOpBuilder (Location loc, T &&... operands) inline
OpBuilder has a bunch of convenience constructors - we support them all with the additional Location.
Definition at line 626 of file Builders.h.
Referenced by atBlockBegin(), atBlockEnd(), and atBlockTerminator().
Member Function Documentation
atBlockBegin()
static ImplicitLocOpBuilder mlir::ImplicitLocOpBuilder::atBlockBegin (Location loc, Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
Definition at line 631 of file Builders.h.
References mlir::Block::begin(), ImplicitLocOpBuilder(), and mlir::OpBuilder::listener.
Referenced by insertCopies(), outlineExecuteOp(), setupCoroMachinery(), and setupSetErrorBlock().
atBlockEnd()
static ImplicitLocOpBuilder mlir::ImplicitLocOpBuilder::atBlockEnd (Location loc, Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
Definition at line 638 of file Builders.h.
References mlir::Block::end(), ImplicitLocOpBuilder(), and mlir::OpBuilder::listener.
Referenced by addAsyncRuntimeApiDeclarations(), addResumeFunction(), createCtlzFunc(), createElementFPowIFunc(), and createElementIPowIFunc().
atBlockTerminator()
static ImplicitLocOpBuilder mlir::ImplicitLocOpBuilder::atBlockTerminator (Location loc, Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to before the block terminator.
Definition at line 645 of file Builders.h.
References mlir::Block::getTerminator(), ImplicitLocOpBuilder(), and mlir::OpBuilder::listener.
create() [1/4]
template<typename OpTy , typename... Args> OpTy mlir::ImplicitLocOpBuilder::create (Args &&... args) inline
Create an operation of specific op type at the current insertion point and location.
Definition at line 664 of file Builders.h.
create() [2/4]
Operation * OpBuilder::create
Creates an operation given the fields represented as an OperationState.
Create an operation given the fields represented as an OperationState.
Definition at line 474 of file Builders.cpp.
create() [3/4]
Operation * OpBuilder::create
Creates an operation with the given fields.
Definition at line 477 of file Builders.cpp.
create() [4/4]
template<typename OpTy , typename... Args> OpTy mlir::OpBuilder::create (typename OpTy , typename... Args) inline
Create an operation of specific op type at the current insertion point.
Definition at line 503 of file Builders.h.
createOrFold() [1/6]
template<typename OpTy , typename... Args> std::enable_if_t<OpTy::template hasTrait<mlir::OpTrait::OneResult>), Value> mlir::ImplicitLocOpBuilder::createOrFold (Args &&... args) inline
Overload to create or fold a single result operation.
Definition at line 679 of file Builders.h.
createOrFold() [2/6]
template<typename OpTy , typename... Args> std::enable_if_t<OpTy::template hasTrait<mlir::OpTrait::ZeroResults>), OpTy> mlir::ImplicitLocOpBuilder::createOrFold (Args &&... args) inline
Overload to create or fold a zero result operation.
Definition at line 686 of file Builders.h.
createOrFold() [3/6]
template<typename OpTy , typename... Args> void mlir::ImplicitLocOpBuilder::createOrFold (llvm::SmallVectorImpl< Value > & results, Args &&... args) inline
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
This functions populates 'results' with the results after folding the operation.
Definition at line 672 of file Builders.h.
Referenced by allocBuffer(), defaultAllocBufferCallBack(), insertCopyLoops(), and transposeToShuffle16x16().
createOrFold() [4/6]
template<typename OpTy , typename... Args> std::enable_if_t<OpTy::template hasTrait<OpTrait::OneResult>), Value> mlir::OpBuilder::createOrFold (typename OpTy , typename... Args) inline
Overload to create or fold a single result operation.
Definition at line 545 of file Builders.h.
createOrFold() [5/6]
template<typename OpTy , typename... Args> std::enable_if_t<OpTy::template hasTrait<OpTrait::ZeroResults>), OpTy> mlir::OpBuilder::createOrFold (typename OpTy , typename... Args) inline
Overload to create or fold a zero result operation.
Definition at line 554 of file Builders.h.
createOrFold() [6/6]
template<typename OpTy , typename... Args> void mlir::OpBuilder::createOrFold (typename OpTy , typename... Args) inline
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
This functions populates 'results' with the results of the operation.
Definition at line 517 of file Builders.h.
emitError()
mlir::InFlightDiagnostic mlir::ImplicitLocOpBuilder::emitError (const llvm::Twine & message = llvm::Twine()) inline
This builder can also be used to emit diagnostics to the current location.
Definition at line 692 of file Builders.h.
References mlir::emitError().
emitRemark()
mlir::InFlightDiagnostic mlir::ImplicitLocOpBuilder::emitRemark (const llvm::Twine & message = llvm::Twine()) inline
Definition at line 700 of file Builders.h.
References mlir::emitRemark().
emitWarning()
mlir::InFlightDiagnostic mlir::ImplicitLocOpBuilder::emitWarning (const llvm::Twine & message = llvm::Twine()) inline
Definition at line 696 of file Builders.h.
References mlir::emitWarning().
getLoc()
Location mlir::ImplicitLocOpBuilder::getLoc () const inline
Accessors for the implied location.
Definition at line 654 of file Builders.h.
Referenced by mlir::linalg::computeContinuousTileSizes(), mlir::linalg::computeMultiTileSizes(), convertCeilOp(), convertExp2fOp(), convertFPowIOp(), mlir::arith::ConstantFloatOp::create(), mlir::arith::ConstantIndexOp::create(), mlir::arith::ConstantIntOp::create(), mlir::affine::AffineDmaStartOp::create(), mlir::affine::AffineDmaWaitOp::create(), mlir::shard::createCollectiveProcessGroupSize(), mlir::linalg::createDestinationPassingStyleInitOperand(), createElementFPowIFunc(), createElementIPowIFunc(), insertCopyLoops(), mlir::affine::linearizeIndex(), promoteSubViews(), and mlir::shard::tryUpdateHaloInResharding().
setLoc()
void mlir::ImplicitLocOpBuilder::setLoc (Location loc) inline
Definition at line 655 of file Builders.h.
The documentation for this class was generated from the following file:
include/mlir/IR/Builders.h