MLIR: mlir::LLVM::detail::DataLayoutImporter Class Reference
mlir::LLVM::detail::DataLayoutImporter Class Reference
Helper class that translates an LLVM data layout string to an MLIR data layout specification.
#include "mlir/Target/LLVMIR/DataLayoutImporter.h"
Public Member Functions
DataLayoutImporter (MLIRContext *context, StringRef dataLayoutStr)
DataLayoutSpecInterface getDataLayoutSpec () const
Returns the MLIR data layout specification translated from the LLVM data layout.
StringRef getLastToken () const
Returns the last data layout token that has been processed before the data layout translation failed.
ArrayRef< StringRef > getUnhandledTokens () const
Returns the data layout tokens that have not been handled during the data layout translation.
Detailed Description
Helper class that translates an LLVM data layout string to an MLIR data layout specification.
Only integer, float, pointer, alloca memory space, stack alignment, and endianness entries are translated. The class also returns all entries from the default data layout specification found in the language reference (https://llvm.org/docs/LangRef.html#data-layout) if they are not overwritten by the provided data layout.
Definition at line 47 of file DataLayoutImporter.h.
Constructor & Destructor Documentation
DataLayoutImporter()
mlir::LLVM::detail::DataLayoutImporter::DataLayoutImporter (MLIRContext * context, StringRef dataLayoutStr) inline
Definition at line 49 of file DataLayoutImporter.h.
Member Function Documentation
getDataLayoutSpec()
DataLayoutSpecInterface mlir::LLVM::detail::DataLayoutImporter::getDataLayoutSpec () const inline
Returns the MLIR data layout specification translated from the LLVM data layout.
Definition at line 65 of file DataLayoutImporter.h.
Referenced by mlir::LLVM::ModuleImport::convertDataLayout(), and mlir::translateDataLayout().
getLastToken()
StringRef mlir::LLVM::detail::DataLayoutImporter::getLastToken () const inline
Returns the last data layout token that has been processed before the data layout translation failed.
Definition at line 69 of file DataLayoutImporter.h.
Referenced by mlir::LLVM::ModuleImport::convertDataLayout().
getUnhandledTokens()
ArrayRef< StringRef > mlir::LLVM::detail::DataLayoutImporter::getUnhandledTokens () const inline
Returns the data layout tokens that have not been handled during the data layout translation.
Definition at line 73 of file DataLayoutImporter.h.
Referenced by mlir::LLVM::ModuleImport::convertDataLayout().
The documentation for this class was generated from the following files:
include/mlir/Target/LLVMIR/DataLayoutImporter.h
lib/Target/LLVMIR/DataLayoutImporter.cpp