MLIR: mlir::arith::NarrowTypeEmulationConverter Class Reference
mlir::arith::NarrowTypeEmulationConverter Class Reference
Converts narrow integer or float types that are not supported by the target hardware to wider types.
#include "mlir/Dialect/Arith/Transforms/NarrowTypeEmulationConverter.h"
Public Member Functions
NarrowTypeEmulationConverter (unsigned targetBitwidth)
unsigned getLoadStoreBitwidth () const
Public Member Functions inherited from mlir::TypeConverter
virtual ~TypeConverter ()=default
TypeConverter ()=default
TypeConverter (const TypeConverter &other)
TypeConverter & operator= (const TypeConverter &other)
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<0>>
void addConversion (FnT &&callback)
Register a conversion function.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addSourceMaterialization (FnT &&callback)
All of the following materializations require function objects that are convertible to the following form: Value(OpBuilder &, T, ValueRange, Location), where T is any subclass of Type.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addTargetMaterialization (FnT &&callback)
This method registers a materialization that will be called when converting a value to a target type according to a pattern's type converter.
template<typename FnT , typename T = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<0>, typename A = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<1>>
void addTypeAttributeConversion (FnT &&callback)
Register a conversion function for attributes within types.
LogicalResult convertType (Type t, SmallVectorImpl< Type > &results) const
Convert the given type.
Type convertType (Type t) const
This hook simplifies defining 1-1 type conversions.
template<typename TargetType >
TargetType convertType (Type t) const
Attempts a 1-1 type conversion, expecting the result type to be TargetType.
LogicalResult convertTypes (TypeRange types, SmallVectorImpl< Type > &results) const
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type) const
Return true if the given type is legal for this type converter, i.e.
template<typename RangeT >
std::enable_if_t<!std::is_convertible< RangeT, Type >::value &&!std::is_convertible< RangeT, Operation * >::value, bool > isLegal (RangeT &&range) const
Return true if all of the given types are legal for this type converter.
bool isLegal (Operation *op) const
Return true if the given operation has legal operand and result types.
bool isLegal (Region *region) const
Return true if the types of block arguments within the region are legal.
bool isSignatureLegal (FunctionType ty) const
Return true if the inputs and outputs of the given function type are legal.
LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result) const
This method allows for converting a specific argument of a signature.
LogicalResult convertSignatureArgs (TypeRange types, SignatureConversion &result, unsigned origInputOffset=0) const
std::optional< SignatureConversion > convertBlockSignature (Block *block) const
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
Value materializeSourceConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs) const
Materialize a conversion from a set of types into one result type by generating a cast sequence of some kind.
Value materializeTargetConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs, Type originalType={}) const
SmallVector< Value > materializeTargetConversion (OpBuilder &builder, Location loc, TypeRange resultType, ValueRange inputs, Type originalType={}) const
std::optional< Attribute > convertTypeAttribute (Type type, Attribute attr) const
Convert an attribute present attr from within the type type using the registered conversion functions.
Detailed Description
Converts narrow integer or float types that are not supported by the target hardware to wider types.
Currently, we only handle power-of-two integer types and convert them to wider integers that are equal or larger than 8 bits.
Definition at line 20 of file NarrowTypeEmulationConverter.h.
Constructor & Destructor Documentation
NarrowTypeEmulationConverter()
arith::NarrowTypeEmulationConverter::NarrowTypeEmulationConverter (unsigned targetBitwidth) explicit
Definition at line 27 of file EmulateNarrowType.cpp.
References mlir::TypeConverter::addConversion(), mlir::TypeConverter::convertTypes(), mlir::get(), and mlir::Type::getContext().
Member Function Documentation
getLoadStoreBitwidth()
unsigned mlir::arith::NarrowTypeEmulationConverter::getLoadStoreBitwidth () const inline
Definition at line 24 of file NarrowTypeEmulationConverter.h.
Referenced by mlir::memref::populateMemRefNarrowTypeEmulationConversions().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Arith/Transforms/NarrowTypeEmulationConverter.h
lib/Dialect/Arith/Transforms/EmulateNarrowType.cpp