MLIR: mlir::ResourceBlobManagerDialectInterfaceBase< HandleT > Class Template Reference
mlir::ResourceBlobManagerDialectInterfaceBase< HandleT > Class Template Reference
This class provides a base class for dialects implementing the resource blob interface.
#include "mlir/IR/DialectResourceBlobManager.h"
Public Member Functions
void update (StringRef name, AsmResourceBlob &&newBlob)
Update the blob for the entry defined by the provided name.
HandleT insert (StringRef name, std::optional< AsmResourceBlob > blob={})
Insert a new resource blob entry with the provided name and optional blob data.
void buildResources (AsmResourceBuilder &provider, ArrayRef< AsmDialectResourceHandle > referencedResources)
Build resources for each of the referenced blobs within this manager.
Public Member Functions inherited from mlir::ResourceBlobManagerDialectInterface
ResourceBlobManagerDialectInterface (Dialect *dialect)
DialectResourceBlobManager & getBlobManager ()
Return the blob manager held by this interface.
const DialectResourceBlobManager & getBlobManager () const
void setBlobManager (std::shared_ptr< DialectResourceBlobManager > newBlobManager)
Set the blob manager held by this interface.
Additional Inherited Members
Public Types inherited from mlir::detail::DialectInterfaceBase< ConcreteType, BaseT >
using Base = DialectInterfaceBase< ConcreteType, BaseT >
Static Public Member Functions inherited from mlir::detail::DialectInterfaceBase< ConcreteType, BaseT >
static TypeID getInterfaceID ()
Get a unique id for the derived interface type.
Protected Member Functions inherited from mlir::detail::DialectInterfaceBase< ConcreteType, BaseT >
DialectInterfaceBase (Dialect *dialect)
Detailed Description
template<typename HandleT>
class mlir::ResourceBlobManagerDialectInterfaceBase< HandleT >
This class provides a base class for dialects implementing the resource blob interface.
It provides several additional dialect specific utilities on top of the generic interface. HandleT is the type of the handle used to reference a resource blob.
Definition at line 146 of file DialectResourceBlobManager.h.
Member Function Documentation
buildResources()
template<typename HandleT > void mlir::ResourceBlobManagerDialectInterfaceBase< HandleT >::buildResources (AsmResourceBuilder & provider, ArrayRef< AsmDialectResourceHandle > referencedResources) inline
Build resources for each of the referenced blobs within this manager.
Definition at line 168 of file DialectResourceBlobManager.h.
References mlir::AsmResourceBuilder::buildBlob().
insert()
template<typename HandleT > HandleT mlir::ResourceBlobManagerDialectInterfaceBase< HandleT >::insert (StringRef name, std::optional< AsmResourceBlob > blob = {}) inline
Insert a new resource blob entry with the provided name and optional blob data.
The name may be modified during insertion if another entry already exists with that name. Returns a dialect specific handle to the inserted entry.
Definition at line 162 of file DialectResourceBlobManager.h.
update()
template<typename HandleT > void mlir::ResourceBlobManagerDialectInterfaceBase< HandleT >::update (StringRef name, AsmResourceBlob && newBlob) inline
Update the blob for the entry defined by the provided name.
This method asserts that an entry for the given name exists in the manager.
Definition at line 154 of file DialectResourceBlobManager.h.
References mlir::ResourceBlobManagerDialectInterface::getBlobManager(), and mlir::DialectResourceBlobManager::update().
The documentation for this class was generated from the following file:
include/mlir/IR/DialectResourceBlobManager.h