MLIR: mlir::tblgen::EnumAttr Class Reference
mlir::tblgen::EnumAttr Class Reference
#include "mlir/TableGen/Attribute.h"
Public Member Functions
EnumAttr (const llvm::Record *record)
EnumAttr (const llvm::Record &record)
EnumAttr (const llvm::DefInit *init)
bool isBitEnum () const
StringRef getEnumClassName () const
StringRef getCppNamespace () const
StringRef getUnderlyingType () const
StringRef getUnderlyingToSymbolFnName () const
StringRef getStringToSymbolFnName () const
StringRef getSymbolToStringFnName () const
StringRef getSymbolToStringFnRetType () const
StringRef getMaxEnumValFnName () const
std::vector< EnumAttrCase > getAllCases () const
bool genSpecializedAttr () const
llvm::Record * getBaseAttrClass () const
StringRef getSpecializedAttrClassName () const
bool printBitEnumPrimaryGroups () const
Public Member Functions inherited from mlir::tblgen::Attribute
Attribute (const llvm::Record *record)
Attribute (const llvm::DefInit *init)
StringRef getStorageType () const
StringRef getReturnType () const
std::optional< Type > getValueType () const
StringRef getConvertFromStorageCall () const
bool isConstBuildable () const
StringRef getConstBuilderTemplate () const
Attribute getBaseAttr () const
bool hasDefaultValue () const
StringRef getDefaultValue () const
bool isOptional () const
bool isDerivedAttr () const
bool isTypeAttr () const
bool isSymbolRefAttr () const
bool isEnumAttr () const
StringRef getAttrDefName () const
StringRef getDerivedCodeBody () const
Dialect getDialect () const
const llvm::Record & getDef () const
Public Member Functions inherited from mlir::tblgen::AttrConstraint
bool isSubClassOf (StringRef className) const
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
Constraints are pointer-comparable.
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getSummary () const
StringRef getDescription () const
StringRef getDefName () const
Returns the name of the TablGen def of this constraint.
std::string getUniqueDefName () const
Returns a unique name for the TablGen def of this constraint.
Kind getKind () const
const llvm::Record & getDef () const
Return the underlying def.
Static Public Member Functions
static bool classof (const Attribute *attr)
Static Public Member Functions inherited from mlir::tblgen::AttrConstraint
static bool classof (const Constraint *c)
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind {
CK_Attr , CK_Region , CK_Successor , CK_Type ,
CK_Uncategorized
}
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 163 of file Attribute.h.
Constructor & Destructor Documentation
EnumAttr() [1/3]
EnumAttr::EnumAttr (const llvm::Record * record) explicit
Definition at line 168 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
EnumAttr() [2/3]
EnumAttr::EnumAttr (const llvm::Record & record) explicit
Definition at line 173 of file Attribute.cpp.
EnumAttr() [3/3]
EnumAttr::EnumAttr (const llvm::DefInit * init) explicit
Definition at line 175 of file Attribute.cpp.
Member Function Documentation
classof()
bool EnumAttr::classof (const Attribute * attr) static
Definition at line 177 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
genSpecializedAttr()
bool EnumAttr::genSpecializedAttr () const
Definition at line 228 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getAllCases()
std::vector< EnumAttrCase > EnumAttr::getAllCases () const
Definition at line 215 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getBaseAttrClass()
llvm::Record * EnumAttr::getBaseAttrClass () const
Definition at line 232 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getCppNamespace()
StringRef EnumAttr::getCppNamespace () const
Definition at line 187 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getEnumClassName()
StringRef EnumAttr::getEnumClassName () const
Definition at line 183 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getMaxEnumValFnName()
StringRef EnumAttr::getMaxEnumValFnName () const
Definition at line 211 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getSpecializedAttrClassName()
StringRef EnumAttr::getSpecializedAttrClassName () const
Definition at line 236 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getStringToSymbolFnName()
StringRef EnumAttr::getStringToSymbolFnName () const
Definition at line 199 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getSymbolToStringFnName()
StringRef EnumAttr::getSymbolToStringFnName () const
Definition at line 203 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getSymbolToStringFnRetType()
StringRef EnumAttr::getSymbolToStringFnRetType () const
Definition at line 207 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getUnderlyingToSymbolFnName()
StringRef EnumAttr::getUnderlyingToSymbolFnName () const
Definition at line 195 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getUnderlyingType()
StringRef EnumAttr::getUnderlyingType () const
Definition at line 191 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
isBitEnum()
bool EnumAttr::isBitEnum () const
Definition at line 181 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
printBitEnumPrimaryGroups()
bool EnumAttr::printBitEnumPrimaryGroups () const
Definition at line 240 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Attribute.h
lib/TableGen/Attribute.cpp