MLIR: mlir::ExternalPass Class Reference
mlir::ExternalPass Class Reference
This pass class wraps external passes defined in other languages using the MLIR C-interface.
Public Member Functions
ExternalPass (TypeID passID, StringRef name, StringRef argument, StringRef description, std::optional< StringRef > opName, ArrayRef< MlirDialectHandle > dependentDialects, MlirExternalPassCallbacks callbacks, void *userData)
~ExternalPass () override
StringRef getName () const override
Returns the derived pass name.
StringRef getArgument () const override
Return the command line argument used when registering this pass.
StringRef getDescription () const override
Return the command line description used when registering this pass.
void getDependentDialects (DialectRegistry &registry) const override
Register dependent dialects for the current pass.
void signalPassFailure ()
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Protected Member Functions
LogicalResult initialize (MLIRContext *ctx) override
Initialize any complex state necessary for running this pass.
bool canScheduleOn (RegisteredOperationName opName) const override
Indicate if the current pass can be scheduled on the given operation type.
void runOnOperation () override
The polymorphic API that runs the pass over the currently held operation.
std::unique_ptr< Pass > clonePass () const override
Create a copy of this pass, ignoring statistics and options.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT >
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT , typename OpT >
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT >
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT >
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT >
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT >
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT >
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT , typename OpTy >
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Detailed Description
This pass class wraps external passes defined in other languages using the MLIR C-interface.
Definition at line 139 of file Pass.cpp.
Constructor & Destructor Documentation
ExternalPass()
mlir::ExternalPass::ExternalPass (TypeID passID, StringRef name, StringRef argument, StringRef description, std::optional< StringRef > opName, ArrayRef< MlirDialectHandle > dependentDialects, MlirExternalPassCallbacks callbacks, void * userData) inline
Definition at line 141 of file Pass.cpp.
References MlirExternalPassCallbacks::construct.
~ExternalPass()
mlir::ExternalPass::~ExternalPass () inline override
Definition at line 151 of file Pass.cpp.
References MlirExternalPassCallbacks::destruct.
Member Function Documentation
canScheduleOn()
bool mlir::ExternalPass::canScheduleOn (RegisteredOperationName opName) const inline override protected virtual
Indicate if the current pass can be scheduled on the given operation type.
This is useful for generic operation passes to add restrictions on the operations they operate on.
Implements mlir::Pass.
Definition at line 172 of file Pass.cpp.
References mlir::Pass::getOpName(), and mlir::OperationName::getStringRef().
clonePass()
std::unique_ptr<Pass> mlir::ExternalPass::clonePass () const inline override protected virtual
Create a copy of this pass, ignoring statistics and options.
Implements mlir::Pass.
Definition at line 182 of file Pass.cpp.
References MlirExternalPassCallbacks::clone, and mlir::Pass::getOpName().
getArgument()
StringRef mlir::ExternalPass::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 154 of file Pass.cpp.
getDependentDialects()
void mlir::ExternalPass::getDependentDialects (DialectRegistry & registry) const inline override virtual
Register dependent dialects for the current pass.
A pass is expected to register the dialects it will create entities for (Operations, Types, Attributes), other than dialect that exists in the input. For example, a pass that converts from Linalg to Affine would register the Affine dialect but does not need to register Linalg.
Reimplemented from mlir::Pass.
Definition at line 157 of file Pass.cpp.
References mlirDialectHandleInsertDialect(), and wrap().
getDescription()
StringRef mlir::ExternalPass::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 155 of file Pass.cpp.
getName()
StringRef mlir::ExternalPass::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 153 of file Pass.cpp.
initialize()
LogicalResult mlir::ExternalPass::initialize (MLIRContext * context) inline override protected virtual
Initialize any complex state necessary for running this pass.
This hook should not rely on any state accessible during the execution of a pass. For example, getContext/getOperation/getAnalysis/etc. should not be invoked within this hook. This method is invoked after all dependent dialects for the pipeline are loaded, and is not allowed to load any further dialects (override the getDependentDialects() for this purpose instead). Returns a LogicalResult to indicate failure, in which case the pass pipeline won't execute.
Reimplemented from mlir::Pass.
Definition at line 166 of file Pass.cpp.
References MlirExternalPassCallbacks::initialize, unwrap(), and wrap().
runOnOperation()
void mlir::ExternalPass::runOnOperation () inline override protected virtual
The polymorphic API that runs the pass over the currently held operation.
Implements mlir::Pass.
Definition at line 178 of file Pass.cpp.
References mlir::Pass::getOperation(), MlirExternalPassCallbacks::run, and wrap().
signalPassFailure()
void mlir::ExternalPass::signalPassFailure () inline
Definition at line 163 of file Pass.cpp.
References mlir::Pass::signalPassFailure().
The documentation for this class was generated from the following file:
lib/CAPI/IR/Pass.cpp