MLIR: mlir::OperandElementTypeIterator Class Reference
mlir::OperandElementTypeIterator Class Reference final
#include "mlir/IR/TypeUtilities.h"
Public Types
using reference = Type
Public Member Functions
OperandElementTypeIterator (Operation::operand_iterator it)
Initializes the result element type iterator to the specified operand iterator.
Detailed Description
Definition at line 74 of file TypeUtilities.h.
Member Typedef Documentation
reference
using mlir::OperandElementTypeIterator::reference = Type
Definition at line 78 of file TypeUtilities.h.
Constructor & Destructor Documentation
OperandElementTypeIterator()
OperandElementTypeIterator::OperandElementTypeIterator (Operation::operand_iterator it) explicit
Initializes the result element type iterator to the specified operand iterator.
Definition at line 154 of file TypeUtilities.cpp.
References mlir::Type::cast(), getElementType(), mlir::Value::getType(), and value.
The documentation for this class was generated from the following files:
include/mlir/IR/TypeUtilities.h
lib/IR/TypeUtilities.cpp