MLIR: mlir::pdll::ast::AttrConstraintDecl Class Reference
mlir::pdll::ast::AttrConstraintDecl Class Reference
The class represents an Attribute constraint, and constrains a variable to be an Attribute.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
Expr * getTypeExpr ()
Return the optional type the attribute is constrained to.
const Expr * getTypeExpr () const
Public Member Functions inherited from mlir::pdll::ast::Decl
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
void setDocComment (Context &ctx, StringRef comment)
Set the documentation comment for this decl.
std::optional< StringRef > getDocComment () const
Return the documentation comment attached to this decl if it has been set.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT, typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static AttrConstraintDecl * create (Context &ctx, SMRange loc, Expr *typeExpr=nullptr)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< AttrConstraintDecl, CoreConstraintDecl >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::CoreConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::ConstraintDecl
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Decl
static bool classof (const Node *node)
Provide type casting support.
Protected Member Functions
AttrConstraintDecl (SMRange loc, Expr *typeExpr)
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< AttrConstraintDecl, CoreConstraintDecl >
NodeBase (SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::CoreConstraintDecl
CoreConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::ConstraintDecl
ConstraintDecl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Decl
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Protected Attributes
Expr * typeExpr
An optional type that the attribute is constrained to.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< AttrConstraintDecl, CoreConstraintDecl >
using Base
Detailed Description
The class represents an Attribute constraint, and constrains a variable to be an Attribute.
Definition at line 749 of file Nodes.h.
Constructor & Destructor Documentation
AttrConstraintDecl()
mlir::pdll::ast::AttrConstraintDecl::AttrConstraintDecl (SMRange loc, Expr * typeExpr) inline protected
Definition at line 760 of file Nodes.h.
References typeExpr.
Referenced by create().
Member Function Documentation
create()
AttrConstraintDecl * AttrConstraintDecl::create (Context & ctx, SMRange loc, Expr * typeExpr = nullptr) static
Definition at line 385 of file Nodes.cpp.
References AttrConstraintDecl(), mlir::pdll::ast::Context::getAllocator(), and typeExpr.
getTypeExpr() [1/2]
Expr * mlir::pdll::ast::AttrConstraintDecl::getTypeExpr () inline
Return the optional type the attribute is constrained to.
Definition at line 756 of file Nodes.h.
References typeExpr.
getTypeExpr() [2/2]
const Expr * mlir::pdll::ast::AttrConstraintDecl::getTypeExpr () const inline
Definition at line 757 of file Nodes.h.
References typeExpr.
Member Data Documentation
typeExpr
Expr* mlir::pdll::ast::AttrConstraintDecl::typeExpr protected
An optional type that the attribute is constrained to.
Definition at line 764 of file Nodes.h.
Referenced by AttrConstraintDecl(), create(), getTypeExpr(), and getTypeExpr().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp