MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface Class Reference
Wrapper around the MemoryEffectsOpInterface.
Static Public Member Functions
static void attach (nb::object &target, const std::string &opName, DefaultingPyMlirContext ctx)
Attach a new MemoryEffectsOpInterface FallbackModel to the named operation.
static void bindDerived (ClassTy &cls)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyMemoryEffectsOpInterface >
static void bind (nanobind::module_ &m)
Creates the Python bindings for this class in the given module.
static void bindDerived (ClassTy &cls)
Hook for derived classes to add class-specific bindings.
Static Public Attributes
static constexpr const char * pyClassName = "MemoryEffectsOpInterface"
static constexpr GetTypeIDFunctionTy getInterfaceID
Additional Inherited Members
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyMemoryEffectsOpInterface >
PyConcreteOpInterface (nanobind::object object, DefaultingPyMlirContext context)
Constructs an interface instance from an object that is either an operation or a subclass of OpView.
bool isStatic ()
Returns true if this object was constructed from a subclass of OpView rather than from an operation instance.
nanobind::typed< nanobind::object, PyOperation > getOperationObject ()
Returns the operation instance from which this object was constructed.
nanobind::typed< nanobind::object, PyOpView > getOpView ()
Returns the opview of the operation instance from which this object was constructed.
const std::string & getOpName ()
Returns the canonical name of the operation this interface is constructed from.
Protected Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyMemoryEffectsOpInterface >
using ClassTy
using GetTypeIDFunctionTy
Detailed Description
Wrapper around the MemoryEffectsOpInterface.
Definition at line 410 of file IRInterfaces.cpp.
Member Function Documentation
attach()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::attach (nb::object & target, const std::string & opName, DefaultingPyMlirContext ctx) inline static
Attach a new MemoryEffectsOpInterface FallbackModel to the named operation.
The FallbackModel acts as a trampoline for callbacks on the Python class.
Definition at line 423 of file IRInterfaces.cpp.
References MlirMemoryEffectsOpInterfaceCallbacks::construct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::createOpView(), MlirMemoryEffectsOpInterfaceCallbacks::destruct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::forOperation(), mlir::python::Defaulting< DerivedTy, T >::get(), MlirMemoryEffectsOpInterfaceCallbacks::getEffects, mlirMemoryEffectsOpInterfaceAttachFallbackModel(), mlirOperationGetContext(), mlirStringRefCreate(), target, and MlirMemoryEffectsOpInterfaceCallbacks::userData.
Referenced by bindDerived().
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::bindDerived (ClassTy & cls) inline static
Definition at line 456 of file IRInterfaces.cpp.
References attach(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::classmethod(), and target.
Member Data Documentation
getInterfaceID
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::getInterfaceID static constexpr
Initial value:
=
      &mlirMemoryEffectsOpInterfaceTypeID
Definition at line 417 of file IRInterfaces.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::pyClassName = "MemoryEffectsOpInterface" static constexpr
Definition at line 416 of file IRInterfaces.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRInterfaces.cpp