MLIR: mlir::tblgen::Dialect Class Reference
mlir::tblgen::Dialect Class Reference
#include "mlir/TableGen/Dialect.h"
Public Member Functions
Dialect (const llvm::Record *def)
StringRef getName () const
StringRef getCppNamespace () const
std::string getCppClassName () const
StringRef getSummary () const
StringRef getDescription () const
ArrayRef< StringRef > getDependentDialects () const
std::optional< StringRef > getExtraClassDeclaration () const
bool hasCanonicalizer () const
Returns true if this dialect has a canonicalizer.
bool hasConstantMaterializer () const
Returns true if this dialect has a constant materializer.
bool hasNonDefaultDestructor () const
Returns true if the destructor definition is provided explicitly or false if a default should be generated.
bool hasOperationAttrVerify () const
Returns true if this dialect has an operation attribute verifier.
bool hasRegionArgAttrVerify () const
Returns true if this dialect has a region argument attribute verifier.
bool hasRegionResultAttrVerify () const
Returns true if this dialect has a region result attribute verifier.
bool hasOperationInterfaceFallback () const
Returns true if this dialect has fallback interfaces for its operations.
bool useDefaultAttributePrinterParser () const
Returns true if this dialect should generate the default dispatch for attribute printing/parsing.
bool useDefaultTypePrinterParser () const
Returns true if this dialect should generate the default dispatch for type printing/parsing.
bool isExtensible () const
Returns true if this dialect can be extended at runtime with new operations or types.
bool usePropertiesForAttributes () const
Default to use properties for storing Attributes for operations in this dialect.
const llvm::DagInit * getDiscardableAttributes () const
const llvm::Record * getDef () const
bool operator== (const Dialect &other) const
bool operator!= (const Dialect &other) const
bool operator< (const Dialect &other) const
operator bool () const
Detailed Description
Definition at line 30 of file Dialect.h.
Constructor & Destructor Documentation
Dialect()
Dialect::Dialect (const llvm::Record * def) explicit
Definition at line 19 of file Dialect.cpp.
Member Function Documentation
getCppClassName()
std::string Dialect::getCppClassName () const
Definition at line 32 of file Dialect.cpp.
getCppNamespace()
StringRef Dialect::getCppNamespace () const
Definition at line 28 of file Dialect.cpp.
Referenced by mlir::tblgen::NamespaceEmitter::NamespaceEmitter().
getDef()
const llvm::Record* mlir::tblgen::Dialect::getDef () const inline
Definition at line 97 of file Dialect.h.
getDependentDialects()
ArrayRef< StringRef > Dialect::getDependentDialects () const
Definition at line 56 of file Dialect.cpp.
getDescription()
StringRef Dialect::getDescription () const
Definition at line 52 of file Dialect.cpp.
References getAsStringOrEmpty().
getDiscardableAttributes()
const llvm::DagInit * Dialect::getDiscardableAttributes () const
Definition at line 109 of file Dialect.cpp.
getExtraClassDeclaration()
std::optional< StringRef > Dialect::getExtraClassDeclaration () const
Definition at line 60 of file Dialect.cpp.
getName()
StringRef mlir::tblgen::Dialect::getName () const
Referenced by mlir::tblgen::Operator::getDialectName(), mlir::tblgen::Operator::getOperationName(), and operator<().
getSummary()
StringRef Dialect::getSummary () const
Definition at line 48 of file Dialect.cpp.
References getAsStringOrEmpty().
hasCanonicalizer()
bool Dialect::hasCanonicalizer () const
Returns true if this dialect has a canonicalizer.
Definition at line 65 of file Dialect.cpp.
hasConstantMaterializer()
bool Dialect::hasConstantMaterializer () const
Returns true if this dialect has a constant materializer.
Definition at line 69 of file Dialect.cpp.
hasNonDefaultDestructor()
bool Dialect::hasNonDefaultDestructor () const
Returns true if the destructor definition is provided explicitly or false if a default should be generated.
Definition at line 73 of file Dialect.cpp.
hasOperationAttrVerify()
bool Dialect::hasOperationAttrVerify () const
Returns true if this dialect has an operation attribute verifier.
Definition at line 77 of file Dialect.cpp.
hasOperationInterfaceFallback()
bool Dialect::hasOperationInterfaceFallback () const
Returns true if this dialect has fallback interfaces for its operations.
Definition at line 89 of file Dialect.cpp.
hasRegionArgAttrVerify()
bool Dialect::hasRegionArgAttrVerify () const
Returns true if this dialect has a region argument attribute verifier.
Definition at line 81 of file Dialect.cpp.
hasRegionResultAttrVerify()
bool Dialect::hasRegionResultAttrVerify () const
Returns true if this dialect has a region result attribute verifier.
Definition at line 85 of file Dialect.cpp.
isExtensible()
bool Dialect::isExtensible () const
Returns true if this dialect can be extended at runtime with new operations or types.
Definition at line 101 of file Dialect.cpp.
operator bool()
mlir::tblgen::Dialect::operator bool () const inline explicit
Definition at line 109 of file Dialect.h.
operator!=()
bool mlir::tblgen::Dialect::operator!= (const Dialect & other) const inline
Definition at line 103 of file Dialect.h.
operator<()
bool Dialect::operator< (const Dialect & other) const
Definition at line 117 of file Dialect.cpp.
References getName().
operator==()
bool Dialect::operator== (const Dialect & other) const
Definition at line 113 of file Dialect.cpp.
useDefaultAttributePrinterParser()
bool Dialect::useDefaultAttributePrinterParser () const
Returns true if this dialect should generate the default dispatch for attribute printing/parsing.
Definition at line 93 of file Dialect.cpp.
useDefaultTypePrinterParser()
bool Dialect::useDefaultTypePrinterParser () const
Returns true if this dialect should generate the default dispatch for type printing/parsing.
Definition at line 97 of file Dialect.cpp.
usePropertiesForAttributes()
bool Dialect::usePropertiesForAttributes () const
Default to use properties for storing Attributes for operations in this dialect.
Definition at line 105 of file Dialect.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Dialect.h
lib/TableGen/Dialect.cpp