MLIR: mlir::sparse_tensor::ir_detail::LvlSpec Class Reference
mlir::sparse_tensor::ir_detail::LvlSpec Class Reference final
The full lvlVar = lvlExpr : lvlType specification for a given level.
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
LvlSpec (LvlVar var, LvlExpr expr, LevelType type)
MLIRContext * getContext () const
constexpr LvlVar getBoundVar () const
constexpr bool canElideVar () const
void setElideVar (bool b)
constexpr LvlExpr getExpr () const
constexpr LevelType getType () const
bool isValid (Ranks const &ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
Detailed Description
The full lvlVar = lvlExpr : lvlType specification for a given level.
Definition at line 196 of file DimLvlMap.h.
Constructor & Destructor Documentation
LvlSpec()
LvlSpec::LvlSpec (LvlVar var, LvlExpr expr, LevelType type)
Definition at line 65 of file DimLvlMap.cpp.
References mlir::sparse_tensor::isUndefLT(), and mlir::sparse_tensor::isValidLT().
Member Function Documentation
canElideVar()
constexpr bool mlir::sparse_tensor::ir_detail::LvlSpec::canElideVar () const inline constexpr
Definition at line 217 of file DimLvlMap.h.
getBoundVar()
constexpr LvlVar mlir::sparse_tensor::ir_detail::LvlSpec::getBoundVar () const inline constexpr
Definition at line 216 of file DimLvlMap.h.
getContext()
MLIRContext* mlir::sparse_tensor::ir_detail::LvlSpec::getContext () const inline
Definition at line 210 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::tryGetContext().
getExpr()
constexpr LvlExpr mlir::sparse_tensor::ir_detail::LvlSpec::getExpr () const inline constexpr
Definition at line 219 of file DimLvlMap.h.
getType()
constexpr LevelType mlir::sparse_tensor::ir_detail::LvlSpec::getType () const inline constexpr
Definition at line 220 of file DimLvlMap.h.
Referenced by mlir::sparse_tensor::ir_detail::DimLvlMap::getLvlType().
isValid()
bool LvlSpec::isValid (Ranks const & ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
Definition at line 71 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::Ranks::isValid().
setElideVar()
void mlir::sparse_tensor::ir_detail::LvlSpec::setElideVar (bool b) inline
Definition at line 218 of file DimLvlMap.h.
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.cpp