MLIR: mlir::python::PyStringAttribute Class Reference
mlir::python::PyStringAttribute Class Reference
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::PyConcreteAttribute< PyStringAttribute >
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::object maybeDownCast ()
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::PyConcreteAttribute< PyStringAttribute >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirAttributeIsAString
static constexpr const char * pyClassName = "StringAttr"
static constexpr GetTypeIDFunctionTy getTypeIdFunction
Static Public Attributes inherited from mlir::python::PyConcreteAttribute< PyStringAttribute >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
Additional Inherited Members
Public Types inherited from mlir::python::PyConcreteAttribute< PyStringAttribute >
using ClassTy = nanobind::class_< PyStringAttribute, PyAttribute >
using IsAFunctionTy = bool(*)(MlirAttribute)
using GetTypeIDFunctionTy = MlirTypeID(*)()
Detailed Description
Definition at line 1150 of file IRModule.h.
Member Function Documentation
bindDerived()
void PyStringAttribute::bindDerived (ClassTy & c) static
Definition at line 1742 of file IRAttributes.cpp.
References MlirStringRef::data, mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::BaseContextObject::getContext(), MlirStringRef::length, mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), and toMlirStringRef().
PyConcreteAttribute() [1/3]
mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute default
PyConcreteAttribute() [2/3]
mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute inline
Definition at line 1073 of file IRModule.h.
PyConcreteAttribute() [3/3]
mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute inline
Definition at line 1071 of file IRModule.h.
Member Data Documentation
getTypeIdFunction
constexpr GetTypeIDFunctionTy mlir::python::PyStringAttribute::getTypeIdFunction static constexpr
Initial value:
=
      mlirStringAttrGetTypeID
Definition at line 1155 of file IRModule.h.
isaFunction
constexpr IsAFunctionTy mlir::python::PyStringAttribute::isaFunction = mlirAttributeIsAString static constexpr
Definition at line 1152 of file IRModule.h.
pyClassName
constexpr const char* mlir::python::PyStringAttribute::pyClassName = "StringAttr" static constexpr
Definition at line 1153 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRAttributes.cpp