MLIR: mlir::spirv::SampledImageType Class Reference
mlir::spirv::SampledImageType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
Type getImageType () const
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, std::optional< spirv::StorageClass > storage=std::nullopt)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, std::optional< spirv::StorageClass > storage=std::nullopt)
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static SampledImageType get (Type imageType)
static SampledImageType getChecked (function_ref< InFlightDiagnostic()> emitError, Type imageType)
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, Type imageType)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.sampled_image"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 249 of file SPIRVTypes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
Member Function Documentation
get()
SampledImageType SampledImageType::get (Type imageType) static
Definition at line 793 of file SPIRVTypes.cpp.
References mlir::get(), and mlir::Type::getContext().
Referenced by parseSampledImageType().
getCapabilities()
void SampledImageType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, std::optional< spirv::StorageClass > storage = std::nullopt)
Definition at line 820 of file SPIRVTypes.cpp.
References getImageType().
getChecked()
SampledImageType SampledImageType::getChecked (function_ref< InFlightDiagnostic()> emitError, Type imageType) static
Definition at line 798 of file SPIRVTypes.cpp.
References mlir::emitError(), and mlir::Type::getContext().
getExtensions()
void SampledImageType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, std::optional< spirv::StorageClass > storage = std::nullopt)
Definition at line 814 of file SPIRVTypes.cpp.
References getImageType().
getImageType()
Type SampledImageType::getImageType () const
Definition at line 803 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by getCapabilities(), getExtensions(), and print().
verifyInvariants()
LogicalResult SampledImageType::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, Type imageType) static
Definition at line 806 of file SPIRVTypes.cpp.
References mlir::emitError().
Member Data Documentation
name
constexpr StringLiteral mlir::spirv::SampledImageType::name = "spirv.sampled_image" static constexpr
Definition at line 255 of file SPIRVTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp