MLIR: mlir::dataflow::PredecessorState Class Reference
mlir::dataflow::PredecessorState Class Reference
This analysis state represents a set of live control-flow "predecessors" of a program point (either an operation or a block), which are the last operations along all execution paths that pass through this point.
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
Public Member Functions
void print (raw_ostream &os) const override
Print the known predecessors.
bool allPredecessorsKnown () const
Returns true if all predecessors are known.
ChangeResult setHasUnknownPredecessors ()
Indicate that there are potentially unknown predecessors.
ArrayRef< Operation * > getKnownPredecessors () const
Get the known predecessors.
ValueRange getSuccessorInputs (Operation *predecessor) const
Get the successor inputs from a predecessor.
ChangeResult join (Operation *predecessor)
Add a known predecessor.
ChangeResult join (Operation *predecessor, ValueRange inputs)
Add a known predecessor with successor inputs.
AnalysisState (LatticeAnchor anchor)
Create the analysis state on the given lattice anchor.
Public Member Functions inherited from mlir::AnalysisState
virtual ~AnalysisState ()
AnalysisState (LatticeAnchor anchor)
Create the analysis state on the given lattice anchor.
LatticeAnchor getAnchor () const
Returns the lattice anchor this state is located at.
virtual void print (raw_ostream &os) const =0
Print the contents of the analysis state.
LLVM_DUMP_METHOD void dump () const
void addDependency (ProgramPoint *point, DataFlowAnalysis *analysis)
Add a dependency to this analysis state on a lattice anchor and an analysis.
Additional Inherited Members
Protected Member Functions inherited from mlir::AnalysisState
virtual void onUpdate (DataFlowSolver *solver) const
This function is called by the solver when the analysis state is updated to enqueue more work items.
Protected Attributes inherited from mlir::AnalysisState
LatticeAnchor anchor
The lattice anchor to which the state belongs.
Detailed Description
This analysis state represents a set of live control-flow "predecessors" of a program point (either an operation or a block), which are the last operations along all execution paths that pass through this point.
For example, in dead-code analysis, an operation with region control-flow can be the predecessor of a region's entry block or itself, the exiting terminator of a region can be the predecessor of the parent operation or another region's entry block, the callsite of a callable operation can be the predecessor to its entry block, and the exiting terminator or a callable operation can be the predecessor of the call operation.
The state can optionally contain information about which values are propagated from each predecessor to the successor point.
The state can indicate that it is underdefined, meaning that not all live control-flow predecessors can be known.
Definition at line 94 of file DeadCodeAnalysis.h.
Member Function Documentation
allPredecessorsKnown()
bool mlir::dataflow::PredecessorState::allPredecessorsKnown () const inline
Returns true if all predecessors are known.
Definition at line 102 of file DeadCodeAnalysis.h.
Referenced by print(), and mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitCallableOperation().
AnalysisState()
AnalysisState::AnalysisState (LatticeAnchor anchor) inline
Create the analysis state on the given lattice anchor.
Definition at line 493 of file DataFlowFramework.h.
getKnownPredecessors()
ArrayRef< Operation * > mlir::dataflow::PredecessorState::getKnownPredecessors () const inline
Get the known predecessors.
Definition at line 111 of file DeadCodeAnalysis.h.
Referenced by print(), and mlir::dataflow::AbstractSparseBackwardDataFlowAnalysis::visitCallableOperation().
getSuccessorInputs()
ValueRange mlir::dataflow::PredecessorState::getSuccessorInputs (Operation * predecessor) const inline
Get the successor inputs from a predecessor.
Definition at line 116 of file DeadCodeAnalysis.h.
join() [1/2]
ChangeResult PredecessorState::join (Operation * predecessor)
Add a known predecessor.
Definition at line 96 of file DeadCodeAnalysis.cpp.
References mlir::Change, and mlir::NoChange.
Referenced by join().
join() [2/2]
ChangeResult PredecessorState::join (Operation * predecessor, ValueRange inputs)
Add a known predecessor with successor inputs.
Definition at line 101 of file DeadCodeAnalysis.cpp.
References mlir::Change, join(), and result.
print()
void PredecessorState::print (raw_ostream & os) const override
Print the known predecessors.
Definition at line 80 of file DeadCodeAnalysis.cpp.
References allPredecessorsKnown(), and getKnownPredecessors().
setHasUnknownPredecessors()
ChangeResult mlir::dataflow::PredecessorState::setHasUnknownPredecessors () inline
Indicate that there are potentially unknown predecessors.
Definition at line 105 of file DeadCodeAnalysis.h.
References mlir::Change, and mlir::NoChange.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/DeadCodeAnalysis.h
lib/Analysis/DataFlow/DeadCodeAnalysis.cpp