MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors Class Reference
A list of operation successors.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyOpSuccessors (PyOperationRef operation, intptr_t startIndex=0, intptr_t length=-1, intptr_t step=1)
void dunderSetItem (intptr_t index, PyBlock block)
Public Member Functions inherited from mlir::Sliceable< PyOpSuccessors, PyBlock >
Sliceable (intptr_t startIndex, intptr_t length, intptr_t step)
PyBlock getElement (intptr_t index)
Returns the index-th element in the slice, supports negative indices.
intptr_t size ()
Returns the size of slice.
std::vector< PyBlock > dunderAdd (PyOpSuccessors &other)
Returns a new vector (mapped to Python list) containing elements from two slices.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::Sliceable< PyOpSuccessors, PyBlock >
static void bind (nanobind::module_ &m)
Binds the indexing and length methods in the Python class.
static void bindDerived (ClassTy &)
Hook for derived classes willing to bind more methods.
Static Public Attributes
static constexpr const char * pyClassName = "OpSuccessors"
Friends
class Sliceable< PyOpSuccessors, PyBlock >
Give the parent CRTP class access to hook implementations below.
Additional Inherited Members
Public Attributes inherited from mlir::Sliceable< PyOpSuccessors, PyBlock >
intptr_t startIndex
intptr_t length
intptr_t step
Protected Types inherited from mlir::Sliceable< PyOpSuccessors, PyBlock >
using ClassTy
Protected Member Functions inherited from mlir::Sliceable< PyOpSuccessors, PyBlock >
intptr_t wrapIndex (intptr_t index)
Transforms index into a legal value to access the underlying sequence.
intptr_t linearizeIndex (intptr_t index)
Computes the linear index given the current slice properties.
nanobind::typed< nanobind::object, PyBlock > getItem (intptr_t index)
Returns the element at the given slice index.
nanobind::object getItemSlice (PyObject *slice)
Returns a new instance of the pseudo-container restricted to the given slice.
Static Protected Attributes inherited from mlir::Sliceable< PyOpSuccessors, PyBlock >
static constexpr std::array< const char *, 0 > typeParams
Type parameter names for generic classes.
Detailed Description
A list of operation successors.
Internally, these are stored as consecutive elements, random access is cheap. The (returned) successor list is associated with the operation whose successors these are, and thus extends the lifetime of this operation.
Definition at line 1837 of file IRCore.h.
Constructor & Destructor Documentation
PyOpSuccessors()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors::PyOpSuccessors (PyOperationRef operation, intptr_t startIndex = 0, intptr_t length = -1, intptr_t step = 1)
Definition at line 2310 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockSuccessors::PyBlockSuccessors(), and Sliceable< PyOpSuccessors, PyBlock >.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors::bindDerived (ClassTy & c) static
Definition at line 2323 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::get(), mlirOperationSetSuccessor(), and mlir::Sliceable< PyOpSuccessors, PyBlock >::wrapIndex().
Referenced by Sliceable< PyOpSuccessors, PyBlock >.
dunderSetItem()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors::dunderSetItem (intptr_t index, PyBlock block)
Definition at line 2318 of file IRCore.cpp.
References mlir::get(), mlir::Sliceable< PyOpSuccessors, PyBlock >::length, mlirOperationGetNumSuccessors(), and mlir::Sliceable< PyOpSuccessors, PyBlock >::step.
Friends And Related Symbol Documentation
Sliceable< PyOpSuccessors, PyBlock >
friend class Sliceable< PyOpSuccessors, PyBlock > friend
Give the parent CRTP class access to hook implementations below.
Definition at line 1847 of file IRCore.h.
References bindDerived(), mlir::Sliceable< PyOpSuccessors, PyBlock >::length, PyOpSuccessors(), mlir::Sliceable< PyOpSuccessors, PyBlock >::Sliceable(), mlir::Sliceable< PyOpSuccessors, PyBlock >::startIndex, and mlir::Sliceable< PyOpSuccessors, PyBlock >::step.
Member Data Documentation
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpSuccessors::pyClassName = "OpSuccessors" static constexpr
Definition at line 1840 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp