MLIR: mlir::OperationFingerPrint Class Reference
mlir::OperationFingerPrint Class Reference
A unique fingerprint for a specific operation, and all of it's internal operations (if includeNested is set).
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OperationFingerPrint (Operation *topOp, bool includeNested=true)
OperationFingerPrint (const OperationFingerPrint &)=default
OperationFingerPrint & operator= (const OperationFingerPrint &)=default
bool operator== (const OperationFingerPrint &other) const
bool operator!= (const OperationFingerPrint &other) const
Detailed Description
A unique fingerprint for a specific operation, and all of it's internal operations (if includeNested is set).
Definition at line 1419 of file OperationSupport.h.
Constructor & Destructor Documentation
OperationFingerPrint() [1/2]
OperationFingerPrint::OperationFingerPrint (Operation * topOp, bool includeNested = true)
Definition at line 925 of file OperationSupport.cpp.
References addDataToHash(), mlir::Location::getAsOpaquePointer(), mlir::Operation::getLoc(), mlir::Operation::getNumSuccessors(), mlir::Operation::getOperands(), mlir::Operation::getParentOp(), mlir::Operation::getRawDictionaryAttrs(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), mlir::Operation::getSuccessor(), mlir::Operation::hashProperties(), and mlir::Operation::walk().
Referenced by OperationFingerPrint(), operator!=(), operator=(), and operator==().
OperationFingerPrint() [2/2]
mlir::OperationFingerPrint::OperationFingerPrint (const OperationFingerPrint &) default
References OperationFingerPrint().
Member Function Documentation
operator!=()
bool mlir::OperationFingerPrint::operator!= (const OperationFingerPrint & other) const inline
Definition at line 1428 of file OperationSupport.h.
References OperationFingerPrint().
operator=()
OperationFingerPrint & mlir::OperationFingerPrint::operator= (const OperationFingerPrint &) default
References OperationFingerPrint().
operator==()
bool mlir::OperationFingerPrint::operator== (const OperationFingerPrint & other) const inline
Definition at line 1425 of file OperationSupport.h.
References OperationFingerPrint().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp