MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry Class Reference
Wrapper around an MlirDialectRegistry.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyDialectRegistry ()
PyDialectRegistry (MlirDialectRegistry registry)
~PyDialectRegistry ()
PyDialectRegistry (PyDialectRegistry &)=delete
PyDialectRegistry (PyDialectRegistry &&other) noexcept
operator MlirDialectRegistry () const
MlirDialectRegistry get () const
nanobind::object getCapsule ()
Static Public Member Functions
static PyDialectRegistry createFromCapsule (nanobind::object capsule)
Detailed Description
Wrapper around an MlirDialectRegistry.
Upon construction, the Python wrapper takes ownership of the underlying MlirDialectRegistry.
Definition at line 514 of file IRCore.h.
Constructor & Destructor Documentation
PyDialectRegistry() [1/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::PyDialectRegistry () inline
Definition at line 516 of file IRCore.h.
References mlirDialectRegistryCreate().
Referenced by PyDialectRegistry(), and PyDialectRegistry().
PyDialectRegistry() [2/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::PyDialectRegistry (MlirDialectRegistry registry) inline
Definition at line 517 of file IRCore.h.
~PyDialectRegistry()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::~PyDialectRegistry () inline
Definition at line 518 of file IRCore.h.
References mlirDialectRegistryDestroy(), and mlirDialectRegistryIsNull().
PyDialectRegistry() [3/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::PyDialectRegistry (PyDialectRegistry &) delete
References PyDialectRegistry().
PyDialectRegistry() [4/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::PyDialectRegistry (PyDialectRegistry && other) inline noexcept
Definition at line 523 of file IRCore.h.
References PyDialectRegistry().
Member Function Documentation
createFromCapsule()
PyDialectRegistry mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::createFromCapsule (nanobind::object capsule) static
Definition at line 812 of file IRCore.cpp.
References mlirPythonDialectRegistryToCapsule().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
MlirDialectRegistry mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::get () const inline
Definition at line 529 of file IRCore.h.
getCapsule()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::getCapsule ()
Definition at line 808 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
operator MlirDialectRegistry()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::operator MlirDialectRegistry () const inline
Definition at line 528 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp