MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject Class Reference
Base class for all objects that directly or indirectly depend on an MlirContext.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Base class for all objects that directly or indirectly depend on an MlirContext.
The lifetime of the context will extend at least to the lifetime of these instances. Immutable objects that depend on a context extend this directly.
Definition at line 302 of file IRCore.h.
Constructor & Destructor Documentation
BaseContextObject()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::BaseContextObject (PyMlirContextRef ref) inline
Definition at line 304 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::PyAffineExpr(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap::PyAffineMap(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::PyAttribute(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectDescriptor::PyDialectDescriptor(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects::PyDialects(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSet::PyIntegerSet(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::PyLocation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyModule::~PyModule(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::~PyOperation().
Member Function Documentation
getContext()
PyMlirContextRef & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext () inline
Accesses the context reference.
Definition at line 310 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::gpu::ObjectAttr::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMapAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyCallSiteLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyComplexType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFloatAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFusedLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemRefType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyNameLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRankedTensorType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyShapedType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyStringAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTupleType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedMemRefType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::dunderNext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects::getDialectForKey(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::lhs(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::maybeDownCast(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::linalg::populateDialectLinalgSubmodule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< DerivedTy, BaseTy >::PyConcreteLocation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< DerivedTy, BaseTy >::PyConcreteType(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::rhs().
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/IRCore.h