MLIR: mlir::polynomial::PolynomialBase< Derived, Monomial > Class Template Reference
mlir::polynomial::PolynomialBase< Derived, Monomial > Class Template Reference
#include "mlir/Dialect/Polynomial/IR/Polynomial.h"
Public Member Functions
PolynomialBase ()=delete
PolynomialBase (ArrayRef< Monomial > terms)
operator bool () const
bool operator== (const PolynomialBase &other) const
bool operator!= (const PolynomialBase &other) const
void print (raw_ostream &os, ::llvm::StringRef separator, ::llvm::StringRef exponentiation) const
Derived add (const Derived &other)
void print (raw_ostream &os) const
void dump () const
std::string toIdentifier () const
unsigned getDegree () const
ArrayRef< Monomial > getTerms () const
Friends
template<class D , typename T >
::llvm::hash_code hash_value (const PolynomialBase< D, T > &arg)
Detailed Description
template<class Derived, typename Monomial>
class mlir::polynomial::PolynomialBase< Derived, Monomial >
Definition at line 116 of file Polynomial.h.
Constructor & Destructor Documentation
PolynomialBase() [1/2]
template<class Derived , typename Monomial > mlir::polynomial::PolynomialBase< Derived, Monomial >::PolynomialBase () delete
PolynomialBase() [2/2]
template<class Derived , typename Monomial > mlir::polynomial::PolynomialBase< Derived, Monomial >::PolynomialBase (ArrayRef< Monomial > terms) inline explicit
Definition at line 120 of file Polynomial.h.
Member Function Documentation
add()
template<class Derived , typename Monomial > Derived mlir::polynomial::PolynomialBase< Derived, Monomial >::add (const Derived & other) inline
Definition at line 160 of file Polynomial.h.
dump()
template<class Derived , typename Monomial > void mlir::polynomial::PolynomialBase< Derived, Monomial >::dump () const
getDegree()
template<class Derived , typename Monomial > unsigned mlir::polynomial::PolynomialBase< Derived, Monomial >::getDegree () const inline
Definition at line 211 of file Polynomial.h.
getTerms()
template<class Derived , typename Monomial > ArrayRef<Monomial> mlir::polynomial::PolynomialBase< Derived, Monomial >::getTerms () const inline
Definition at line 215 of file Polynomial.h.
Referenced by mlir::polynomial::PolynomialBase< Derived, Monomial >::print().
operator bool()
template<class Derived , typename Monomial > mlir::polynomial::PolynomialBase< Derived, Monomial >::operator bool () const inline explicit
Definition at line 122 of file Polynomial.h.
operator!=()
template<class Derived , typename Monomial > bool mlir::polynomial::PolynomialBase< Derived, Monomial >::operator!= (const PolynomialBase< Derived, Monomial > & other) const inline
Definition at line 126 of file Polynomial.h.
operator==()
template<class Derived , typename Monomial > bool mlir::polynomial::PolynomialBase< Derived, Monomial >::operator== (const PolynomialBase< Derived, Monomial > & other) const inline
Definition at line 123 of file Polynomial.h.
print() [1/2]
template<class Derived , typename Monomial > void mlir::polynomial::PolynomialBase< Derived, Monomial >::print (raw_ostream & os) const inline
Definition at line 199 of file Polynomial.h.
References mlir::polynomial::PolynomialBase< Derived, Monomial >::print().
Referenced by mlir::polynomial::PolynomialBase< Derived, Monomial >::print().
print() [2/2]
template<class Derived , typename Monomial > void mlir::polynomial::PolynomialBase< Derived, Monomial >::print (raw_ostream & os, ::llvm::StringRef separator, ::llvm::StringRef exponentiation) const inline
Definition at line 130 of file Polynomial.h.
References mlir::polynomial::PolynomialBase< Derived, Monomial >::getTerms().
Referenced by mlir::polynomial::operator<<(), and mlir::polynomial::PolynomialBase< Derived, Monomial >::toIdentifier().
toIdentifier()
template<class Derived , typename Monomial > std::string mlir::polynomial::PolynomialBase< Derived, Monomial >::toIdentifier () const inline
Definition at line 204 of file Polynomial.h.
References mlir::polynomial::PolynomialBase< Derived, Monomial >::print().
Friends And Related Function Documentation
hash_value
template<class Derived , typename Monomial > template<class D , typename T > ::llvm::hash_code hash_value (const PolynomialBase< D, T > & arg) friend
Definition at line 262 of file Polynomial.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Polynomial/IR/Polynomial.h