MLIR: mlir::ModuleAnalysisManager Class Reference
mlir::ModuleAnalysisManager Class Reference
An analysis manager class specifically for the top-level operation.
#include "mlir/Pass/AnalysisManager.h"
Public Member Functions
ModuleAnalysisManager (Operation *op, PassInstrumentor *passInstrumentor)
ModuleAnalysisManager (const ModuleAnalysisManager &)=delete
ModuleAnalysisManager & operator= (const ModuleAnalysisManager &)=delete
operator AnalysisManager ()
Returns an analysis manager for the current top-level module.
Detailed Description
An analysis manager class specifically for the top-level operation.
This class contains the memory allocations for all nested analysis managers, and provides an anchor point. This is necessary because AnalysisManager is designed to be a thin wrapper around an existing analysis map instance.
Definition at line 393 of file AnalysisManager.h.
Constructor & Destructor Documentation
ModuleAnalysisManager() [1/2]
mlir::ModuleAnalysisManager::ModuleAnalysisManager (Operation * op, PassInstrumentor * passInstrumentor) inline
Definition at line 395 of file AnalysisManager.h.
Referenced by ModuleAnalysisManager(), and operator=().
ModuleAnalysisManager() [2/2]
mlir::ModuleAnalysisManager::ModuleAnalysisManager (const ModuleAnalysisManager &) delete
References ModuleAnalysisManager().
Member Function Documentation
operator AnalysisManager()
mlir::ModuleAnalysisManager::operator AnalysisManager () inline
Returns an analysis manager for the current top-level module.
Definition at line 401 of file AnalysisManager.h.
operator=()
ModuleAnalysisManager & mlir::ModuleAnalysisManager::operator= (const ModuleAnalysisManager &) delete
References ModuleAnalysisManager().
The documentation for this class was generated from the following file:
include/mlir/Pass/AnalysisManager.h