MLIR: mlir::ResultElementTypeIterator Class Reference
mlir::ResultElementTypeIterator Class Reference final
#include "mlir/IR/TypeUtilities.h"
Public Types
using reference = Type
Public Member Functions
ResultElementTypeIterator (Operation::result_iterator it)
Initializes the result element type iterator to the specified result iterator.
Detailed Description
Definition at line 91 of file TypeUtilities.h.
Member Typedef Documentation
reference
using mlir::ResultElementTypeIterator::reference = Type
Definition at line 95 of file TypeUtilities.h.
Constructor & Destructor Documentation
ResultElementTypeIterator()
ResultElementTypeIterator::ResultElementTypeIterator (Operation::result_iterator it) explicit
Initializes the result element type iterator to the specified result iterator.
Definition at line 163 of file TypeUtilities.cpp.
References mlir::Type::cast(), getElementType(), and mlir::Value::getType().
The documentation for this class was generated from the following files:
include/mlir/IR/TypeUtilities.h
lib/IR/TypeUtilities.cpp