MLIR: mlir::IRUnit Class Reference
mlir::IRUnit Class Reference
IRUnit is a union of the different types of IR objects that constitute the IR structure (other than Type and Attribute), that is Operation, Region, and Block.
#include "mlir/IR/Unit.h"
Public Member Functions
void print (raw_ostream &os, OpPrintingFlags flags=OpPrintingFlags().skipRegions().useLocalScope()) const
Print the IRUnit to the given stream.
Detailed Description
IRUnit is a union of the different types of IR objects that constitute the IR structure (other than Type and Attribute), that is Operation, Region, and Block.
Definition at line 28 of file Unit.h.
Member Function Documentation
print()
void mlir::IRUnit::print (raw_ostream & os, OpPrintingFlags flags = OpPrintingFlags().skipRegions().useLocalScope()) const
Print the IRUnit to the given stream.
Definition at line 49 of file Unit.cpp.
References printBlock(), printOp(), and printRegion().
Referenced by mlirDebuggerCursorSelectChildIRUnit(), mlirDebuggerCursorSelectNextIRUnit(), mlirDebuggerCursorSelectParentIRUnit(), and mlirDebuggerCursorSelectPreviousIRUnit().
The documentation for this class was generated from the following files:
include/mlir/IR/Unit.h
lib/IR/Unit.cpp