MLIR: mlir::detail::TileOffsetRangeImpl Class Reference
mlir::detail::TileOffsetRangeImpl Class Reference
Encapsulates the set of parameters that are used to make tile offset calculations in the TileOffsetRangeIterator.
#include "mlir/Dialect/Utils/IndexingUtils.h"
Public Member Functions
TileOffsetRangeImpl (ArrayRef< int64_t > shape, ArrayRef< int64_t > tileShape, ArrayRef< int64_t > loopOrder)
int64_t getMaxLinearIndex () const
SmallVector< int64_t > getStaticTileOffsets (int64_t linearIndex) const
SmallVector< AffineExpr > getDynamicTileOffsets (AffineExpr linearIndex) const
template<typename T >
SmallVector< T > getTileOffsets (T linearIndex) const
size_t getRank () const
Detailed Description
Encapsulates the set of parameters that are used to make tile offset calculations in the TileOffsetRangeIterator.
Definition at line 282 of file IndexingUtils.h.
Constructor & Destructor Documentation
TileOffsetRangeImpl()
mlir::detail::TileOffsetRangeImpl::TileOffsetRangeImpl (ArrayRef< int64_t > shape, ArrayRef< int64_t > tileShape, ArrayRef< int64_t > loopOrder)
Definition at line 359 of file IndexingUtils.cpp.
References mlir::applyPermutationToVector(), mlir::computeMaxLinearIndex(), mlir::computeShapeRatio(), mlir::computeStrides(), and mlir::isPermutationVector().
Member Function Documentation
getDynamicTileOffsets()
SmallVector< AffineExpr > mlir::detail::TileOffsetRangeImpl::getDynamicTileOffsets (AffineExpr linearIndex) const
Definition at line 387 of file IndexingUtils.cpp.
References mlir::applyPermutation(), mlir::computeElementwiseMul(), mlir::delinearize(), mlir::getAffineConstantExprs(), and mlir::AffineExpr::getContext().
Referenced by getTileOffsets().
getMaxLinearIndex()
int64_t mlir::detail::TileOffsetRangeImpl::getMaxLinearIndex () const inline
Definition at line 287 of file IndexingUtils.h.
Referenced by mlir::StaticTileOffsetRange::size().
getRank()
size_t mlir::detail::TileOffsetRangeImpl::getRank () const inline
Definition at line 301 of file IndexingUtils.h.
Referenced by mlir::StaticTileOffsetRange::getRank().
getStaticTileOffsets()
SmallVector< int64_t > mlir::detail::TileOffsetRangeImpl::getStaticTileOffsets (int64_t linearIndex) const
Definition at line 379 of file IndexingUtils.cpp.
References mlir::applyPermutation(), mlir::computeElementwiseMul(), and mlir::delinearize().
Referenced by getTileOffsets().
getTileOffsets()
template<typename T > SmallVector<T> mlir::detail::TileOffsetRangeImpl::getTileOffsets (T linearIndex) const inline
Definition at line 294 of file IndexingUtils.h.
References getDynamicTileOffsets(), and getStaticTileOffsets().
Referenced by mlir::detail::TileOffsetRangeIterator< ElementType >::operator*().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Utils/IndexingUtils.h
lib/Dialect/Utils/IndexingUtils.cpp