MLIR: mlir::pdl::PDLType Class Reference
mlir::pdl::PDLType Class Reference
This class represents the base class of all PDL types.
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
Static Public Member Functions
static bool classof (Type type)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractTy & getAbstractType ()
Return the abstract type descriptor for this type.
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
This class represents the base class of all PDL types.
Definition at line 25 of file PDLTypes.h.
Member Function Documentation
classof()
bool PDLType::classof (Type type) static
Definition at line 70 of file PDLTypes.cpp.
References elementType(), mlir::DialectAsmParser::emitError(), mlir::emitError(), mlir::DialectAsmParser::getCurrentLocation(), mlir::Type::getDialect(), getElementType(), mlir::Type::isa(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), parsePDLType(), print(), mlir::success(), mlir::Type::Type(), and mlir::verify().
The documentation for this class was generated from the following files:
include/mlir/Dialect/PDL/IR/PDLTypes.h
lib/Dialect/PDL/IR/PDLTypes.cpp