MLIR: mlir::InvocationBounds Class Reference
mlir::InvocationBounds Class Reference
This class represents upper and lower bounds on the number of times a region of a RegionBranchOpInterface can be invoked.
#include "mlir/Interfaces/ControlFlowInterfaces.h"
Public Member Functions
InvocationBounds (unsigned lb, std::optional< unsigned > ub)
Create invocation bounds.
unsigned getLowerBound () const
Return the lower bound.
std::optional< unsigned > getUpperBound () const
Return the upper bound.
Static Public Member Functions
static InvocationBounds getUnknown ()
Returns the unknown invocation bounds, i.e., there is no information on how many times a region may be invoked.
Detailed Description
This class represents upper and lower bounds on the number of times a region of a RegionBranchOpInterface can be invoked.
The lower bound is at least zero, but the upper bound may not be known.
Definition at line 299 of file ControlFlowInterfaces.h.
Constructor & Destructor Documentation
InvocationBounds()
mlir::InvocationBounds::InvocationBounds (unsigned lb, std::optional< unsigned > ub) inline
Create invocation bounds.
The lower bound must be at least 0 and only the upper bound can be unknown.
Definition at line 303 of file ControlFlowInterfaces.h.
Referenced by getUnknown().
Member Function Documentation
getLowerBound()
unsigned mlir::InvocationBounds::getLowerBound () const inline
Return the lower bound.
Definition at line 309 of file ControlFlowInterfaces.h.
getUnknown()
InvocationBounds mlir::InvocationBounds::getUnknown () inline static
Returns the unknown invocation bounds, i.e., there is no information on how many times a region may be invoked.
Definition at line 316 of file ControlFlowInterfaces.h.
References InvocationBounds().
getUpperBound()
std::optional< unsigned > mlir::InvocationBounds::getUpperBound () const inline
Return the upper bound.
Definition at line 312 of file ControlFlowInterfaces.h.
Referenced by mlir::getSinglyExecutedRegionsToSink().
The documentation for this class was generated from the following file:
include/mlir/Interfaces/ControlFlowInterfaces.h