MLIR: mlir::FallbackAsmResourceMap Class Reference
mlir::FallbackAsmResourceMap Class Reference
A fallback map containing external resources not explicitly handled by another parser/printer.
#include "mlir/IR/AsmState.h"
Classes
struct OpaqueAsmResource
This class represents an opaque resource.
Public Member Functions
AsmResourceParser & getParserFor (StringRef key)
Return a parser than can be used for parsing entries for the given identifier key.
std::vector< std::unique_ptr< AsmResourcePrinter > > getPrinters ()
Build a set of resource printers to print the resources within this map.
Detailed Description
A fallback map containing external resources not explicitly handled by another parser/printer.
Definition at line 421 of file AsmState.h.
Member Function Documentation
getParserFor()
AsmResourceParser & FallbackAsmResourceMap::getParserFor (StringRef key)
Return a parser than can be used for parsing entries for the given identifier key.
Definition at line 1875 of file AsmPrinter.cpp.
Referenced by mlir::ParserConfig::getResourceParser().
getPrinters()
std::vector< std::unique_ptr< AsmResourcePrinter > > FallbackAsmResourceMap::getPrinters ()
Build a set of resource printers to print the resources within this map.
Definition at line 1883 of file AsmPrinter.cpp.
References mlir::AsmResourcePrinter::fromCallable().
Referenced by mlir::BytecodeWriterConfig::attachFallbackResourcePrinter(), and mlir::AsmState::attachFallbackResourcePrinter().
The documentation for this class was generated from the following files:
include/mlir/IR/AsmState.h
lib/IR/AsmPrinter.cpp