MLIR: mlir::pdl_to_pdl_interp::PredicateBuilder Class Reference
mlir::pdl_to_pdl_interp::PredicateBuilder Class Reference
This class provides utilities for constructing predicates.
#include "Conversion/PDLToPDLInterp/Predicate.h"
Public Types
using Predicate = std::pair<Qualifier *, Qualifier *>
An ordinal predicate consists of a "Question" and a set of acceptable "Answers" (later converted to ordinal values).
Public Member Functions
PredicateBuilder (PredicateUniquer &uniquer, MLIRContext *ctx)
Position * getRoot ()
Returns the root operation position.
OperationPosition * getOperandDefiningOp (Position *p)
Returns the parent position defining the value held by the given operand.
OperationPosition * getPassthroughOp (Position *p)
Returns the operation position equivalent to the given position.
ConstraintPosition * getConstraintPosition (ConstraintQuestion *q, unsigned index)
Position * getAttribute (OperationPosition *p, StringRef name)
Returns an attribute position for an attribute of the given operation.
Position * getAttributeLiteral (Attribute attr)
Returns an attribute position for the given attribute.
Position * getForEach (Position *p, unsigned id)
Position * getOperand (OperationPosition *p, unsigned operand)
Returns an operand position for an operand of the given operation.
Position * getOperandGroup (OperationPosition *p, std::optional< unsigned > group, bool isVariadic)
Returns a position for a group of operands of the given operation.
Position * getAllOperands (OperationPosition *p)
Position * getResult (OperationPosition *p, unsigned result)
Returns a result position for a result of the given operation.
Position * getResultGroup (OperationPosition *p, std::optional< unsigned > group, bool isVariadic)
Returns a position for a group of results of the given operation.
Position * getAllResults (OperationPosition *p)
Position * getType (Position *p)
Returns a type position for the given entity.
Position * getTypeLiteral (Attribute attr)
Returns a type position for the given type value.
UsersPosition * getUsers (Position *p, bool useRepresentative)
Returns the users of a position using the value at the given operand.
Predicate getAttributeConstraint (Attribute attr)
Create a predicate comparing an attribute to a known value.
Predicate getEqualTo (Position *pos)
Create a predicate checking if two values are equal.
Predicate getNotEqualTo (Position *pos)
Create a predicate checking if two values are not equal.
Predicate getConstraint (StringRef name, ArrayRef< Position * > args, ArrayRef< Type > resultTypes, bool isNegated)
Create a predicate that applies a generic constraint.
Predicate getIsNotNull ()
Create a predicate comparing a value with null.
Predicate getOperandCount (unsigned count)
Create a predicate comparing the number of operands of an operation to a known value.
Predicate getOperandCountAtLeast (unsigned count)
Predicate getOperationName (StringRef name)
Create a predicate comparing the name of an operation to a known value.
Predicate getResultCount (unsigned count)
Create a predicate comparing the number of results of an operation to a known value.
Predicate getResultCountAtLeast (unsigned count)
Predicate getTypeConstraint (Attribute type)
Create a predicate comparing the type of an attribute or value to a known type.
Detailed Description
This class provides utilities for constructing predicates.
Definition at line 610 of file Predicate.h.
Member Typedef Documentation
Predicate
using mlir::pdl_to_pdl_interp::PredicateBuilder::Predicate = std::pair<Qualifier *, Qualifier *>
An ordinal predicate consists of a "Question" and a set of acceptable "Answers" (later converted to ordinal values).
A predicate will query some property of a positional value and decide what to do based on the result.
Definition at line 707 of file Predicate.h.
Constructor & Destructor Documentation
PredicateBuilder()
mlir::pdl_to_pdl_interp::PredicateBuilder::PredicateBuilder (PredicateUniquer & uniquer, MLIRContext * ctx) inline
Definition at line 612 of file Predicate.h.
Member Function Documentation
getAllOperands()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getAllOperands (OperationPosition * p) inline
Definition at line 665 of file Predicate.h.
References getOperandGroup().
Referenced by getTreePredicates(), and visitUpward().
getAllResults()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getAllResults (OperationPosition * p) inline
Definition at line 679 of file Predicate.h.
References getResultGroup().
Referenced by getTreePredicates(), and visitUpward().
getAttribute()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getAttribute (OperationPosition * p, StringRef name) inline
Returns an attribute position for an attribute of the given operation.
Definition at line 642 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< AttributePosition, Position, std::pair< OperationPosition *, StringAttr >, Predicates::AttributePos >::get().
Referenced by getTreePredicates().
getAttributeConstraint()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getAttributeConstraint (Attribute attr) inline
Create a predicate comparing an attribute to a known value.
Definition at line 710 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< AttributeAnswer, Qualifier, Attribute, Predicates::AttributeAnswer >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< AttributeQuestion, Qualifier, void, Predicates::AttributeQuestion >::get().
Referenced by getTreePredicates().
getAttributeLiteral()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getAttributeLiteral (Attribute attr) inline
Returns an attribute position for the given attribute.
Definition at line 647 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< AttributeLiteralPosition, Position, Attribute, Predicates::AttributeLiteralPos >::get().
Referenced by getAttributePredicates().
getConstraint()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getConstraint (StringRef name, ArrayRef< Position * > args, ArrayRef< Type > resultTypes, bool isNegated) inline
Create a predicate that applies a generic constraint.
Definition at line 726 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< TrueAnswer, Qualifier, void, Predicates::TrueAnswer >::get().
Referenced by getConstraintPredicates().
getConstraintPosition()
ConstraintPosition * mlir::pdl_to_pdl_interp::PredicateBuilder::getConstraintPosition (ConstraintQuestion * q, unsigned index) inline
Definition at line 636 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConstraintPosition, Position, std::pair< ConstraintQuestion *, unsigned >, Predicates::ConstraintResultPos >::get().
Referenced by getConstraintPredicates().
getEqualTo()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getEqualTo (Position * pos) inline
Create a predicate checking if two values are equal.
Definition at line 716 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< EqualToQuestion, Qualifier, Position *, Predicates::EqualToQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< TrueAnswer, Qualifier, void, Predicates::TrueAnswer >::get().
Referenced by getConstraintPredicates(), getOperandTreePredicates(), getTreePredicates(), and visitUpward().
getForEach()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getForEach (Position * p, unsigned id) inline
Definition at line 651 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ForEachPosition, Position, std::pair< Position *, unsigned >, Predicates::ForEachPos >::get().
Referenced by visitUpward().
getIsNotNull()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getIsNotNull () inline
Create a predicate comparing a value with null.
Definition at line 734 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< IsNotNullQuestion, Qualifier, void, Predicates::IsNotNullQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< TrueAnswer, Qualifier, void, Predicates::TrueAnswer >::get().
Referenced by getOperandTreePredicates(), getResultPredicates(), getResultPredicates(), getTreePredicates(), and getTreePredicates().
getNotEqualTo()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getNotEqualTo (Position * pos) inline
Create a predicate checking if two values are not equal.
Definition at line 721 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< EqualToQuestion, Qualifier, Position *, Predicates::EqualToQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< FalseAnswer, Qualifier, void, Predicates::FalseAnswer >::get().
getOperand()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getOperand (OperationPosition * p, unsigned operand) inline
Returns an operand position for an operand of the given operation.
Definition at line 656 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< OperandPosition, Position, std::pair< OperationPosition *, unsigned >, Predicates::OperandPos >::get().
Referenced by getTreePredicates(), and visitUpward().
getOperandCount()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getOperandCount (unsigned count) inline
Create a predicate comparing the number of operands of an operation to a known value.
Definition at line 740 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< OperandCountQuestion, Qualifier, void, Predicates::OperandCountQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< UnsignedAnswer, Qualifier, unsigned, Predicates::UnsignedAnswer >::get().
Referenced by getTreePredicates().
getOperandCountAtLeast()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getOperandCountAtLeast (unsigned count) inline
Definition at line 744 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< OperandCountAtLeastQuestion, Qualifier, void, Predicates::OperandCountAtLeastQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< UnsignedAnswer, Qualifier, unsigned, Predicates::UnsignedAnswer >::get().
Referenced by getTreePredicates().
getOperandDefiningOp()
OperationPosition * mlir::pdl_to_pdl_interp::PredicateBuilder::getOperandDefiningOp (Position * p) inline
Returns the parent position defining the value held by the given operand.
Definition at line 623 of file Predicate.h.
References mlir::pdl_to_pdl_interp::OperationPosition::get().
Referenced by getOperandTreePredicates().
getOperandGroup()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getOperandGroup (OperationPosition * p, std::optional< unsigned > group, bool isVariadic) inline
Returns a position for a group of operands of the given operation.
Definition at line 661 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< OperandGroupPosition, Position, std::tuple< OperationPosition *, std::optional< unsigned >, bool >, Predicates::OperandGroupPos >::get().
Referenced by getAllOperands(), getTreePredicates(), and visitUpward().
getOperationName()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getOperationName (StringRef name) inline
Create a predicate comparing the name of an operation to a known value.
Definition at line 750 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< OperationNameAnswer, Qualifier, OperationName, Predicates::OperationNameAnswer >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< OperationNameQuestion, Qualifier, void, Predicates::OperationNameQuestion >::get().
Referenced by getTreePredicates().
getPassthroughOp()
OperationPosition * mlir::pdl_to_pdl_interp::PredicateBuilder::getPassthroughOp (Position * p) inline
Returns the operation position equivalent to the given position.
Definition at line 630 of file Predicate.h.
References mlir::pdl_to_pdl_interp::OperationPosition::get().
Referenced by visitUpward().
getResult()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getResult (OperationPosition * p, unsigned result) inline
Returns a result position for a result of the given operation.
Definition at line 670 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ResultPosition, Position, std::pair< OperationPosition *, unsigned >, Predicates::ResultPos >::get(), and result.
Referenced by getOperandTreePredicates(), getResultPredicates(), getTreePredicates(), and visitUpward().
getResultCount()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getResultCount (unsigned count) inline
Create a predicate comparing the number of results of an operation to a known value.
Definition at line 757 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ResultCountQuestion, Qualifier, void, Predicates::ResultCountQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< UnsignedAnswer, Qualifier, unsigned, Predicates::UnsignedAnswer >::get().
Referenced by getTreePredicates().
getResultCountAtLeast()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getResultCountAtLeast (unsigned count) inline
Definition at line 761 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ResultCountAtLeastQuestion, Qualifier, void, Predicates::ResultCountAtLeastQuestion >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< UnsignedAnswer, Qualifier, unsigned, Predicates::UnsignedAnswer >::get().
Referenced by getTreePredicates().
getResultGroup()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getResultGroup (OperationPosition * p, std::optional< unsigned > group, bool isVariadic) inline
Returns a position for a group of results of the given operation.
Definition at line 675 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ResultGroupPosition, Position, std::tuple< OperationPosition *, std::optional< unsigned >, bool >, Predicates::ResultGroupPos >::get().
Referenced by getAllResults(), getOperandTreePredicates(), getResultPredicates(), getTreePredicates(), and visitUpward().
getRoot()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getRoot () inline
Returns the root operation position.
Definition at line 620 of file Predicate.h.
References mlir::pdl_to_pdl_interp::OperationPosition::getRoot().
Referenced by buildPredicateList().
getType()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getType (Position * p) inline
Returns a type position for the given entity.
Definition at line 684 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< TypePosition, Position, Position *, Predicates::TypePos >::get().
Referenced by getOperandTreePredicates(), getTreePredicates(), and getTreePredicates().
getTypeConstraint()
Predicate mlir::pdl_to_pdl_interp::PredicateBuilder::getTypeConstraint (Attribute type) inline
Create a predicate comparing the type of an attribute or value to a known type.
The value is stored as either a TypeAttr, or an ArrayAttr of TypeAttr.
Definition at line 769 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< TypeAnswer, Qualifier, Attribute, Predicates::TypeAnswer >::get(), and mlir::pdl_to_pdl_interp::PredicateBase< TypeQuestion, Qualifier, void, Predicates::TypeQuestion >::get().
Referenced by getTreePredicates().
getTypeLiteral()
Position * mlir::pdl_to_pdl_interp::PredicateBuilder::getTypeLiteral (Attribute attr) inline
Returns a type position for the given type value.
The value is stored as either a TypeAttr, or an ArrayAttr of TypeAttr.
Definition at line 688 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< TypeLiteralPosition, Position, Attribute, Predicates::TypeLiteralPos >::get().
Referenced by getTypePredicates().
getUsers()
UsersPosition * mlir::pdl_to_pdl_interp::PredicateBuilder::getUsers (Position * p, bool useRepresentative) inline
Returns the users of a position using the value at the given operand.
Definition at line 693 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< UsersPosition, Position, std::pair< Position *, bool >, Predicates::UsersPos >::get().
Referenced by visitUpward().
The documentation for this class was generated from the following file:
lib/Conversion/PDLToPDLInterp/Predicate.h