MLIR: mlir::ResultRange Class Reference
mlir::ResultRange Class Reference final
This class implements the result iterators for the Operation class.
#include "mlir/IR/ValueRange.h"
Classes
class UseIterator
This class implements a use iterator for a range of operation results.
Public Types
using type_iterator = ValueTypeIterator<iterator>
Returns the types of the values within this range.
using type_range = ValueTypeRange<ResultRange>
using use_iterator = UseIterator
using use_range = iterator_range<use_iterator>
using user_iterator = ValueUserIterator<use_iterator, OpOperand>
using user_range = iterator_range<user_iterator>
Public Member Functions
ResultRange (OpResult result)
type_range getTypes () const
type_range getType () const
use_range getUses () const
Returns a range of all uses of results within this range, which is useful for iterating over all uses.
use_iterator use_begin () const
use_iterator use_end () const
bool use_empty () const
Returns true if no results in this range have uses.
template<typename ValuesT>
std::enable_if_t<!std::is_convertible< ValuesT, Operation * >::value > replaceAllUsesWith (ValuesT &&values)
Replace all uses of results of this range with the provided 'values'.
void replaceAllUsesWith (Operation *op)
Replace all uses of results of this range with results of 'op'.
template<typename ValuesT>
std::enable_if_t<!std::is_convertible< ValuesT, Operation * >::value > replaceUsesWithIf (ValuesT &&values, function_ref< bool(OpOperand &)> shouldReplace)
Replace uses of results of this range with the provided 'values' if the given callback returns true.
void replaceUsesWithIf (Operation *op, function_ref< bool(OpOperand &)> shouldReplace)
Replace uses of results of this range with results of op if the given callback returns true.
user_range getUsers ()
Returns a range of all users.
user_iterator user_begin ()
user_iterator user_end ()
Detailed Description
This class implements the result iterators for the Operation class.
Definition at line 245 of file ValueRange.h.
Member Typedef Documentation
type_iterator
using mlir::ResultRange::type_iterator = ValueTypeIterator<iterator>
Returns the types of the values within this range.
Definition at line 257 of file ValueRange.h.
type_range
using mlir::ResultRange::type_range = ValueTypeRange<ResultRange>
Definition at line 258 of file ValueRange.h.
use_iterator
using mlir::ResultRange::use_iterator = UseIterator
Definition at line 267 of file ValueRange.h.
use_range
using mlir::ResultRange::use_range = iterator_range<use_iterator>
Definition at line 268 of file ValueRange.h.
user_iterator
using mlir::ResultRange::user_iterator = ValueUserIterator<use_iterator, OpOperand>
Definition at line 322 of file ValueRange.h.
user_range
using mlir::ResultRange::user_range = iterator_range<user_iterator>
Definition at line 323 of file ValueRange.h.
Constructor & Destructor Documentation
ResultRange()
ResultRange::ResultRange (OpResult result)
Definition at line 576 of file OperationSupport.cpp.
References result, and ResultRange().
Referenced by ResultRange(), and mlir::ResultRange::UseIterator::UseIterator().
Member Function Documentation
getType()
ResultRange::type_range ResultRange::getType () const
Definition at line 42 of file ValueRange.cpp.
References getTypes().
getTypes()
ResultRange::type_range ResultRange::getTypes () const
Definition at line 38 of file ValueRange.cpp.
Referenced by mlir::impl::foldCastInterfaceOp(), getConstraintPredicates(), mlir::Operation::getResultTypes(), getType(), and mlir::sparse_tensor::hasAnySparseResult().
getUsers()
ResultRange::user_range ResultRange::getUsers ()
Returns a range of all users.
Definition at line 589 of file OperationSupport.cpp.
References user_begin(), and user_end().
getUses()
ResultRange::use_range ResultRange::getUses () const
Returns a range of all uses of results within this range, which is useful for iterating over all uses.
Definition at line 580 of file OperationSupport.cpp.
References use_begin(), and use_end().
Referenced by mlir::Operation::getUses().
replaceAllUsesWith() [1/2]
void ResultRange::replaceAllUsesWith (Operation * op)
Replace all uses of results of this range with results of 'op'.
Definition at line 630 of file OperationSupport.cpp.
References mlir::Operation::getResults(), and replaceAllUsesWith().
replaceAllUsesWith() [2/2]
template<typename ValuesT> std::enable_if_t<!std::is_convertible< ValuesT, Operation * >::value > mlir::ResultRange::replaceAllUsesWith (ValuesT && values) inline
Replace all uses of results of this range with the provided 'values'.
The size of values must match the size of this range.
Definition at line 286 of file ValueRange.h.
Referenced by mlir::Operation::replaceAllUsesWith(), and replaceAllUsesWith().
replaceUsesWithIf() [1/2]
void ResultRange::replaceUsesWithIf (Operation * op, function_ref< bool(OpOperand &)> shouldReplace)
Replace uses of results of this range with results of op if the given callback returns true.
Definition at line 634 of file OperationSupport.cpp.
References mlir::Operation::getResults(), and replaceUsesWithIf().
replaceUsesWithIf() [2/2]
template<typename ValuesT> std::enable_if_t<!std::is_convertible< ValuesT, Operation * >::value > mlir::ResultRange::replaceUsesWithIf (ValuesT && values, function_ref< bool(OpOperand &)> shouldReplace) inline
Replace uses of results of this range with the provided 'values' if the given callback returns true.
The size of values must match the size of this range.
Definition at line 303 of file ValueRange.h.
Referenced by mlir::Operation::replaceUsesWithIf(), and replaceUsesWithIf().
use_begin()
ResultRange::use_iterator ResultRange::use_begin () const
Definition at line 583 of file OperationSupport.cpp.
Referenced by getUses(), mlir::Operation::use_begin(), and user_begin().
use_empty()
bool mlir::ResultRange::use_empty () const inline
Returns true if no results in this range have uses.
Definition at line 277 of file ValueRange.h.
References result.
Referenced by mlir::Operation::use_empty().
use_end()
ResultRange::use_iterator ResultRange::use_end () const
Definition at line 586 of file OperationSupport.cpp.
Referenced by getUses(), mlir::Operation::use_end(), and user_end().
user_begin()
ResultRange::user_iterator ResultRange::user_begin ()
Definition at line 592 of file OperationSupport.cpp.
References use_begin().
Referenced by getUsers().
user_end()
ResultRange::user_iterator ResultRange::user_end ()
Definition at line 595 of file OperationSupport.cpp.
References use_end().
Referenced by getUsers().
The documentation for this class was generated from the following files:
include/mlir/IR/ValueRange.h
lib/IR/OperationSupport.cpp
lib/IR/ValueRange.cpp