MLIR: mlir::python::PyThreadPool Class Reference
mlir::python::PyThreadPool Class Reference
Wrapper around MlirLlvmThreadPool Python object owns the C++ thread pool.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyThreadPool ()
PyThreadPool (const PyThreadPool &)=delete
PyThreadPool (PyThreadPool &&)=delete
int getMaxConcurrency () const
MlirLlvmThreadPool get ()
std::string _mlir_thread_pool_ptr () const
Detailed Description
Wrapper around MlirLlvmThreadPool Python object owns the C++ thread pool.
Definition at line 168 of file IRModule.h.
Constructor & Destructor Documentation
PyThreadPool() [1/3]
mlir::python::PyThreadPool::PyThreadPool () inline
Definition at line 170 of file IRModule.h.
Referenced by PyThreadPool(), and PyThreadPool().
PyThreadPool() [2/3]
mlir::python::PyThreadPool::PyThreadPool (const PyThreadPool &) delete
References PyThreadPool().
PyThreadPool() [3/3]
mlir::python::PyThreadPool::PyThreadPool (PyThreadPool &&) delete
References PyThreadPool().
Member Function Documentation
_mlir_thread_pool_ptr()
std::string mlir::python::PyThreadPool::_mlir_thread_pool_ptr () const inline
Definition at line 179 of file IRModule.h.
get()
MlirLlvmThreadPool mlir::python::PyThreadPool::get () inline
Definition at line 177 of file IRModule.h.
References wrap().
getMaxConcurrency()
int mlir::python::PyThreadPool::getMaxConcurrency () const inline
Definition at line 176 of file IRModule.h.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRModule.h