MLIR: mlir::arith::ConstantFloatOp Class Reference
mlir::arith::ConstantFloatOp Class Reference
Specialization of arith.constant op that returns a floating point value.
#include "mlir/Dialect/Arith/IR/Arith.h"
Public Member Functions
APFloat value ()
Static Public Member Functions
::mlir::TypeID resolveTypeID ()
static void build (OpBuilder &builder, OperationState &result, FloatType type, const APFloat &value)
Build a constant float op that produces a float of the specified type.
static ConstantFloatOp create (OpBuilder &builder, Location location, FloatType type, const APFloat &value)
static ConstantFloatOp create (ImplicitLocOpBuilder &builder, FloatType type, const APFloat &value)
static bool classof (Operation *op)
Detailed Description
Specialization of arith.constant op that returns a floating point value.
Definition at line 92 of file Arith.h.
Member Function Documentation
build()
void arith::ConstantFloatOp::build (OpBuilder & builder, OperationState & result, FloatType type, const APFloat & value) static
Build a constant float op that produces a float of the specified type.
Definition at line 324 of file ArithOps.cpp.
References mlir::Builder::getFloatAttr(), result, and value().
Referenced by create().
classof()
bool arith::ConstantFloatOp::classof (Operation * op) static
Definition at line 347 of file ArithOps.cpp.
create() [1/2]
arith::ConstantFloatOp arith::ConstantFloatOp::create (ImplicitLocOpBuilder & builder, FloatType type, const APFloat & value) static
Definition at line 342 of file ArithOps.cpp.
References create(), mlir::ImplicitLocOpBuilder::getLoc(), and value().
create() [2/2]
arith::ConstantFloatOp arith::ConstantFloatOp::create (OpBuilder & builder, Location location, FloatType type, const APFloat & value) static
Definition at line 330 of file ArithOps.cpp.
References build(), mlir::OpBuilder::create(), result, and value().
Referenced by convertScalarToComplexDtype(), create(), and getZero().
resolveTypeID()
::mlir::TypeID mlir::arith::ConstantFloatOp::resolveTypeID () inline static
Definition at line 95 of file Arith.h.
References mlir::TypeID::get().
value()
APFloat mlir::arith::ConstantFloatOp::value () inline
Definition at line 105 of file Arith.h.
Referenced by build(), create(), and create().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Arith/IR/Arith.h
lib/Dialect/Arith/IR/ArithOps.cpp