MLIR: mlir::quant::UniformQuantizedPerAxisType Class Reference
mlir::quant::UniformQuantizedPerAxisType Class Reference
Represents per-axis (also known as per-channel quantization).
#include "mlir/Dialect/Quant/IR/QuantTypes.h"
Public Member Functions
ArrayRef< double > getScales () const
Gets the quantization scales.
ArrayRef< int64_t > getZeroPoints () const
Gets the storage values corresponding to the real value 0 in the affine equation.
int32_t getQuantizedDimension () const
Specifies the dimension of the Tensor's shape that the scales and zero_points correspond to.
bool isFixedPoint () const
Fixed point values are real numbers divided by a scale.
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static UniformQuantizedPerAxisType get (unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all parameters specified but not checked.
static UniformQuantizedPerAxisType getChecked (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all specified parameters checked.
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Verifies construction invariants and issues errors/warnings.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
static ConcreteType get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteType getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "quant.uniform_per_axis"
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
using Base
Utility declarations for the concrete attribute class.
using ImplType
using HasTraitFn
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents per-axis (also known as per-channel quantization).
Syntax synopsis: Per-axis, all parameters expressed: !quant<uniform[StorageType:ExpressedType:QuantizedDim]{QuantParams}> Per-axis, optional parameters omitted: !quant<uniform[StorageType]{Scale}>
StorageType: 'i'|'u' NumBits ExpressedType: 'f16', 'f32', 'bf16', 'f64' QuantizedDim: An integer value QuantParams: (Scale ':' ZeroPoint)+ Scale: A legal double value ZeroPoint: An integer value
Definition at line 322 of file QuantTypes.h.
Member Function Documentation
get()
UniformQuantizedPerAxisType UniformQuantizedPerAxisType::get (unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all parameters specified but not checked.
Definition at line 335 of file QuantTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), and mlir::Type::getContext().
Referenced by mlirUniformQuantizedPerAxisTypeGet().
getChecked()
UniformQuantizedPerAxisType UniformQuantizedPerAxisType::getChecked (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all specified parameters checked.
Returns a nullptr convertible type on failure.
Definition at line 345 of file QuantTypes.cpp.
References mlir::emitError(), mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getChecked(), and mlir::Type::getContext().
Referenced by mlir::quant::fakeQuantAttrsToType().
getQuantizedDimension()
int32_t UniformQuantizedPerAxisType::getQuantizedDimension () const
Specifies the dimension of the Tensor's shape that the scales and zero_points correspond to.
For example, a tensor t, with dims=[4, 3, 2, 1] with quantization params: scales=[1.0, 2.0, 3.0], zeroPoints=[1, 2, 3], quantizedDimension=1 will be quantized across the second dimension of t. t[:, 0, :, :] will have scale[0]=1.0, zero_point[0]=1 t[:, 1, :, :] will have scale[1]=2.0, zero_point[0]=2 t[:, 2, :, :] will have scale[2]=3.0, zero_point[0]=3
Definition at line 406 of file QuantTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by printUniformQuantizedPerAxisType().
getScales()
ArrayRef< double > UniformQuantizedPerAxisType::getScales () const
Gets the quantization scales.
The scales designate the difference between the real values corresponding to consecutive quantized values differing by 1. The ith scale corresponds to the ith slice in the quantized_dimension.
Definition at line 398 of file QuantTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by printUniformQuantizedPerAxisType().
getZeroPoints()
ArrayRef< int64_t > UniformQuantizedPerAxisType::getZeroPoints () const
Gets the storage values corresponding to the real value 0 in the affine equation.
The ith zero point corresponds to the ith slice in the quantized_dimension.
Definition at line 402 of file QuantTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by isFixedPoint(), and printUniformQuantizedPerAxisType().
isFixedPoint()
bool mlir::quant::UniformQuantizedPerAxisType::isFixedPoint () const inline
Fixed point values are real numbers divided by a scale.
Currently, only signed storage types are treated as fixed point. A fixed point value can be obtained from an affine value by subtracting the zeroPoint. In the future, this may be explicit versus implied by type and zeroPoint.
Definition at line 381 of file QuantTypes.h.
References getZeroPoints().
verifyInvariants()
LogicalResult UniformQuantizedPerAxisType::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax) static
Verifies construction invariants and issues errors/warnings.
Definition at line 355 of file QuantTypes.cpp.
References mlir::emitError(), success(), and mlir::quant::QuantizedType::verifyInvariants().
Member Data Documentation
name
StringLiteral mlir::quant::UniformQuantizedPerAxisType::name = "quant.uniform_per_axis" static constexpr
Definition at line 329 of file QuantTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Quant/IR/QuantTypes.h
lib/Dialect/Quant/IR/QuantTypes.cpp