MLIR: mlir::Pass Class Reference
mlir::Pass Class Reference abstract
The abstract base pass class.
#include "mlir/Pass/Pass.h"
Classes
struct ListOption
This class represents a specific pass option that contains a list of values of the provided data type.
struct Option
This class represents a specific pass option, with a provided data type.
class Statistic
This class represents a single pass statistic.
Public Member Functions
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual StringRef getName () const =0
Returns the derived pass name.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
virtual StringRef getArgument () const
Return the command line argument used when registering this pass.
virtual StringRef getDescription () const
Return the command line description used when registering this pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Protected Member Functions
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
virtual bool canScheduleOn (RegisteredOperationName opName) const =0
Indicate if the current pass can be scheduled on the given operation type.
virtual bool canScheduleOn (Operation *op) const
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
virtual std::unique_ptr< Pass > clonePass () const =0
Create a copy of this pass, ignoring statistics and options.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Friends
class OpPassManager
Allow access to 'clone'.
class PassInfo
Allow access to 'passOptions'.
class PassInstrumentation
Allow access to 'signalPassFailure'.
Detailed Description
The abstract base pass class.
This class contains information describing the derived pass object, e.g its kind and abstract TypeID.
Definition at line 52 of file Pass.h.
Constructor & Destructor Documentation
~Pass()
virtual mlir::Pass::~Pass () virtual default
Pass() [1/3]
mlir::Pass::Pass (TypeID passID, std::optional< StringRef > opName = std::nullopt) inline explicit protected
Definition at line 164 of file Pass.h.
Referenced by mlir::OperationPass< OpT >::classof(), clonePass(), copyOptionValuesFrom(), mlir::ExternalPass::ExternalPass(), getThreadingSibling(), getThreadingSiblingOrThis(), mlir::Pass::ListOption< DataType, OptionParser >::ListOption(), mlir::OperationPass< OpT >::OperationPass(), mlir::OperationPass< void >::OperationPass(), operator=(), operator=(), mlir::Pass::Option< DataType, OptionParser >::Option(), Pass(), Pass(), and mlir::Pass::Statistic::Statistic().
Pass() [2/3]
mlir::Pass::Pass (const Pass & other) inline protected
Definition at line 166 of file Pass.h.
References Pass().
Pass() [3/3]
mlir::Pass::Pass (Pass &&) protected delete
References Pass().
Member Function Documentation
canScheduleOn() [1/2]
virtual bool mlir::Pass::canScheduleOn (Operation * op) const inline protected virtual
Reimplemented in mlir::InterfacePass< InterfaceT >, mlir::InterfacePass< FunctionOpInterface >, and mlir::InterfacePass< mlir::FunctionOpInterface >.
Definition at line 197 of file Pass.h.
References canScheduleOn(), mlir::Operation::getName(), and mlir::OperationName::getRegisteredInfo().
canScheduleOn() [2/2]
virtual bool mlir::Pass::canScheduleOn (RegisteredOperationName opName) const protected pure virtual
Indicate if the current pass can be scheduled on the given operation type.
This is useful for generic operation passes to add restrictions on the operations they operate on.
Implemented in mlir::ExternalPass, mlir::InterfacePass< InterfaceT >, mlir::OperationPass< OpT >, mlir::OperationPass< func::FuncOp >, mlir::OperationPass< gpu::GPUModuleOp >, mlir::OperationPass< mlir::func::FuncOp >, mlir::OperationPass< mlir::ModuleOp >, mlir::OperationPass< ModuleOp >, mlir::OperationPass< spirv::ModuleOp >, mlir::OperationPass< void >, mlir::OperationPass<::mlir::func::FuncOp >, and mlir::OperationPass<::mlir::ModuleOp >.
Referenced by canScheduleOn().
clone()
std::unique_ptr< Pass > mlir::Pass::clone () const inline protected
A clone method to create a copy of this pass.
Definition at line 213 of file Pass.h.
References clonePass().
clonePass()
virtual std::unique_ptr< Pass > mlir::Pass::clonePass () const protected pure virtual
Create a copy of this pass, ignoring statistics and options.
Implemented in mlir::acc::impl::ACCImplicitDataBase< DerivedT >, mlir::acc::impl::ACCImplicitDeclareBase< DerivedT >, mlir::acc::impl::ACCImplicitRoutineBase< DerivedT >, mlir::acc::impl::ACCLegalizeSerialBase< DerivedT >, mlir::acc::impl::ACCLoopTilingBase< DerivedT >, mlir::acc::impl::LegalizeDataValuesInRegionBase< DerivedT >, mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsAsAffineBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsBase< DerivedT >, mlir::affine::impl::AffineLoopFusionBase< DerivedT >, mlir::affine::impl::AffineLoopInvariantCodeMotionBase< DerivedT >, mlir::affine::impl::AffineLoopNormalizeBase< DerivedT >, mlir::affine::impl::AffineLoopTilingBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollAndJamBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollBase< DerivedT >, mlir::affine::impl::AffineParallelizeBase< DerivedT >, mlir::affine::impl::AffinePipelineDataTransferBase< DerivedT >, mlir::affine::impl::AffineScalarReplacementBase< DerivedT >, mlir::affine::impl::AffineVectorizeBase< DerivedT >, mlir::affine::impl::LoopCoalescingBase< DerivedT >, mlir::affine::impl::RaiseMemrefDialectBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< SimplifyAffineMinMaxPass >, mlir::affine::impl::SimplifyAffineStructuresBase< DerivedT >, mlir::amdgpu::impl::AmdgpuEmulateAtomicsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< AmdgpuFoldMemRefOpsPass >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< AmdgpuMaskedloadToLoadPass >, mlir::amdgpu::impl::AmdgpuResolveStridedMetadataPassBase< DerivedT >, mlir::arith::impl::ArithEmulateUnsupportedFloatsBase< DerivedT >, mlir::arith::impl::ArithEmulateWideIntBase< DerivedT >, mlir::arith::impl::ArithExpandOpsPassBase< DerivedT >, mlir::arith::impl::ArithIntRangeNarrowingBase< DerivedT >, mlir::arith::impl::ArithIntRangeOptsBase< DerivedT >, mlir::arith::impl::ArithUnsignedWhenEquivalentPassBase< DerivedT >, mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >, mlir::arm_sme::impl::OuterProductFusionBase< DerivedT >, mlir::arm_sme::impl::TestTileAllocationBase< DerivedT >, mlir::arm_sme::impl::VectorLegalizationBase< DerivedT >, mlir::arm_sve::impl::LegalizeVectorStorageBase< DerivedT >, mlir::bufferization::impl::BufferDeallocationSimplificationPassBase< DerivedT >, mlir::bufferization::impl::BufferHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferLoopHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferResultsToOutParamsPassBase< DerivedT >, mlir::bufferization::impl::DropEquivalentBufferResultsPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorEliminationPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorToAllocTensorPassBase< DerivedT >, mlir::bufferization::impl::LowerDeallocationsPassBase< DerivedT >, mlir::bufferization::impl::OneShotBufferizePassBase< DerivedT >, mlir::bufferization::impl::OptimizeAllocationLivenessPassBase< DerivedT >, mlir::bufferization::impl::OwnershipBasedBufferDeallocationPassBase< DerivedT >, mlir::bufferization::impl::PromoteBuffersToStackPassBase< DerivedT >, mlir::emitc::impl::FormExpressionsPassBase< DerivedT >, mlir::emitc::impl::WrapFuncInClassPassBase< DerivedT >, mlir::ExternalPass, mlir::func::impl::DuplicateFunctionEliminationPassBase< DerivedT >, mlir::impl::ArithToAMDGPUConversionPassBase< DerivedT >, mlir::impl::ArithToAPFloatConversionPassBase< DerivedT >, mlir::impl::ArithToArmSMEConversionPassBase< DerivedT >, mlir::impl::ArithToLLVMConversionPassBase< DerivedT >, mlir::impl::AsyncFuncToAsyncRuntimePassBase< DerivedT >, mlir::impl::AsyncParallelForPassBase< DerivedT >, mlir::impl::AsyncRuntimePolicyBasedRefCountingPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingOptPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingPassBase< DerivedT >, mlir::impl::AsyncToAsyncRuntimePassBase< DerivedT >, mlir::impl::BubbleDownMemorySpaceCastsBase< DerivedT >, mlir::impl::CanonicalizerBase< DerivedT >, mlir::impl::CompositeFixedPointPassBase< DerivedT >, mlir::impl::ControlFlowSinkBase< DerivedT >, mlir::impl::ConvertAffineForToGPUPassBase< DerivedT >, mlir::impl::ConvertAMDGPUToROCDLPassBase< DerivedT >, mlir::impl::ConvertArithToEmitCBase< DerivedT >, mlir::impl::ConvertArithToSPIRVPassBase< DerivedT >, mlir::impl::ConvertArmNeon2dToIntrPassBase< DerivedT >, mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >, mlir::impl::ConvertArmSMEToSCFPassBase< DerivedT >, mlir::impl::ConvertAsyncToLLVMPassBase< DerivedT >, mlir::impl::ConvertBufferizationToMemRefPassBase< DerivedT >, mlir::impl::ConvertComplexToLibmBase< DerivedT >, mlir::impl::ConvertComplexToLLVMPassBase< DerivedT >, mlir::impl::ConvertComplexToROCDLLibraryCallsBase< DerivedT >, mlir::impl::ConvertComplexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertComplexToStandardPassBase< DerivedT >, mlir::impl::ConvertControlFlowToLLVMPassBase< DerivedT >, mlir::impl::ConvertControlFlowToSPIRVPassBase< DerivedT >, mlir::impl::ConvertElementwiseToLinalgPassBase< DerivedT >, mlir::impl::ConvertFuncToEmitCBase< DerivedT >, mlir::impl::ConvertFuncToLLVMPassBase< DerivedT >, mlir::impl::ConvertFuncToSPIRVPassBase< DerivedT >, mlir::impl::ConvertGpuOpsToLLVMSPVOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToNVVMOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToROCDLOpsBase< DerivedT >, mlir::impl::ConvertGPUToSPIRVBase< DerivedT >, mlir::impl::ConvertIndexToLLVMPassBase< DerivedT >, mlir::impl::ConvertIndexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertLinalgToAffineLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToParallelLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToStandardPassBase< DerivedT >, mlir::impl::ConvertMathToEmitCBase< DerivedT >, mlir::impl::ConvertMathToFuncsBase< DerivedT >, mlir::impl::ConvertMathToLibmPassBase< DerivedT >, mlir::impl::ConvertMathToLLVMPassBase< DerivedT >, mlir::impl::ConvertMathToROCDLBase< DerivedT >, mlir::impl::ConvertMathToSPIRVPassBase< DerivedT >, mlir::impl::ConvertMathToXeVMBase< DerivedT >, mlir::impl::ConvertMemRefToEmitCBase< DerivedT >, mlir::impl::ConvertMemRefToSPIRVPassBase< DerivedT >, mlir::impl::ConvertNVGPUToNVVMPassBase< DerivedT >, mlir::impl::ConvertNVVMToLLVMPassBase< DerivedT >, mlir::impl::ConvertOpenACCToSCFPassBase< DerivedT >, mlir::impl::ConvertOpenMPToLLVMPassBase< DerivedT >, mlir::impl::ConvertParallelLoopToGpuPassBase< DerivedT >, mlir::impl::ConvertPDLToPDLInterpPassBase< DerivedT >, mlir::impl::ConvertSCFToOpenMPPassBase< DerivedT >, mlir::impl::ConvertShapeConstraintsPassBase< DerivedT >, mlir::impl::ConvertShapeToStandardPassBase< DerivedT >, mlir::impl::ConvertShardToMPIPassBase< DerivedT >, mlir::impl::ConvertSPIRVToLLVMPassBase< DerivedT >, mlir::impl::ConvertTensorToLinalgPassBase< DerivedT >, mlir::impl::ConvertTensorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertToEmitCBase< DerivedT >, mlir::impl::ConvertToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToAMXBase< DerivedT >, mlir::impl::ConvertVectorToArmSMEPassBase< DerivedT >, mlir::impl::ConvertVectorToGPUBase< DerivedT >, mlir::impl::ConvertVectorToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToSCFBase< DerivedT >, mlir::impl::ConvertVectorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertVectorToXeGPUBase< DerivedT >, mlir::impl::ConvertXeGPUToXeVMPassBase< DerivedT >, mlir::impl::ConvertXeVMToLLVMPassBase< DerivedT >, mlir::impl::CSEBase< DerivedT >, mlir::impl::FinalizeMemRefToLLVMConversionPassBase< DerivedT >, mlir::impl::GenerateRuntimeVerificationBase< DerivedT >, mlir::impl::GpuAsyncRegionPassBase< DerivedT >, mlir::impl::GpuDecomposeMemrefsPassBase< DerivedT >, mlir::impl::GpuEliminateBarriersBase< DerivedT >, mlir::impl::GpuKernelOutliningPassBase< DerivedT >, mlir::impl::GpuLaunchSinkIndexComputationsPassBase< DerivedT >, mlir::impl::GpuMapParallelLoopsPassBase< DerivedT >, mlir::impl::GpuModuleToBinaryPassBase< DerivedT >, mlir::impl::GpuNVVMAttachTargetBase< DerivedT >, mlir::impl::GpuROCDLAttachTargetBase< DerivedT >, mlir::impl::GpuSPIRVAttachTargetBase< DerivedT >, mlir::impl::GpuToLLVMConversionPassBase< DerivedT >, mlir::impl::GpuXeVMAttachTargetBase< DerivedT >, mlir::impl::InlinerBase< DerivedT >, mlir::impl::LiftControlFlowToSCFPassBase< DerivedT >, mlir::impl::LinalgBlockPackMatmulBase< DerivedT >, mlir::impl::LinalgDetensorizePassBase< DerivedT >, mlir::impl::LinalgElementwiseOpFusionPassBase< DerivedT >, mlir::impl::LinalgFoldIntoElementwisePassBase< DerivedT >, mlir::impl::LinalgFoldUnitExtentDimsPassBase< DerivedT >, mlir::impl::LinalgGeneralizeNamedOpsPassBase< DerivedT >, mlir::impl::LinalgInlineScalarOperandsPassBase< DerivedT >, mlir::impl::LinalgMorphOpsPassBase< DerivedT >, mlir::impl::LinalgSpecializeGenericOpsPassBase< DerivedT >, mlir::impl::LocationSnapshotBase< DerivedT >, mlir::impl::LoopInvariantCodeMotionBase< DerivedT >, mlir::impl::LoopInvariantSubsetHoistingBase< DerivedT >, mlir::impl::LowerAffinePassBase< DerivedT >, mlir::impl::LowerForeachToSCFBase< DerivedT >, mlir::impl::LowerHostCodeToLLVMPassBase< DerivedT >, mlir::impl::LowerSparseIterationToSCFBase< DerivedT >, mlir::impl::LowerSparseOpsToForeachBase< DerivedT >, mlir::impl::MapMemRefStorageClassBase< DerivedT >, mlir::impl::Mem2RegBase< DerivedT >, mlir::impl::OptReductionPassBase< DerivedT >, mlir::impl::OutlineShapeComputationPassBase< DerivedT >, mlir::impl::PreSparsificationRewriteBase< DerivedT >, mlir::impl::PrintOpStatsBase< DerivedT >, mlir::impl::ReconcileUnrealizedCastsPassBase< DerivedT >, mlir::impl::ReductionTreePassBase< DerivedT >, mlir::impl::RemoveDeadValuesBase< DerivedT >, mlir::impl::RemoveShapeConstraintsPassBase< DerivedT >, mlir::impl::SCCPBase< DerivedT >, mlir::impl::SCFForallToForLoopBase< DerivedT >, mlir::impl::SCFForallToParallelLoopBase< DerivedT >, mlir::impl::SCFForLoopCanonicalizationBase< DerivedT >, mlir::impl::SCFForLoopPeelingBase< DerivedT >, mlir::impl::SCFForLoopRangeFoldingBase< DerivedT >, mlir::impl::SCFForLoopSpecializationBase< DerivedT >, mlir::impl::SCFForToWhileLoopBase< DerivedT >, mlir::impl::SCFParallelForToNestedForsBase< DerivedT >, mlir::impl::SCFParallelLoopFusionBase< DerivedT >, mlir::impl::SCFParallelLoopSpecializationBase< DerivedT >, mlir::impl::SCFParallelLoopTilingBase< DerivedT >, mlir::impl::SCFToControlFlowPassBase< DerivedT >, mlir::impl::SCFToEmitCBase< DerivedT >, mlir::impl::SCFToSPIRVBase< DerivedT >, mlir::impl::SetLLVMModuleDataLayoutPassBase< DerivedT >, mlir::impl::ShapeToShapeLoweringPassBase< DerivedT >, mlir::impl::SimplifyDepthwiseConvPassBase< DerivedT >, mlir::impl::SparseAssemblerBase< DerivedT >, mlir::impl::SparseBufferRewriteBase< DerivedT >, mlir::impl::SparseGPUCodegenBase< DerivedT >, mlir::impl::SparseReinterpretMapBase< DerivedT >, mlir::impl::SparseSpaceCollapseBase< DerivedT >, mlir::impl::SparseTensorCodegenBase< DerivedT >, mlir::impl::SparseTensorConversionPassBase< DerivedT >, mlir::impl::SparseVectorizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< SparsificationAndBufferizationPass >, mlir::impl::SparsificationPassBase< DerivedT >, mlir::impl::SROABase< DerivedT >, mlir::impl::StageSparseOperationsBase< DerivedT >, mlir::impl::StorageSpecifierToLLVMBase< DerivedT >, mlir::impl::StripDebugInfoBase< DerivedT >, mlir::impl::SymbolDCEBase< DerivedT >, mlir::impl::SymbolPrivatizeBase< DerivedT >, mlir::impl::TestSCFParallelLoopCollapsingBase< DerivedT >, mlir::impl::TopologicalSortBase< DerivedT >, mlir::impl::TosaToArithPassBase< DerivedT >, mlir::impl::TosaToLinalgBase< DerivedT >, mlir::impl::TosaToLinalgNamedBase< DerivedT >, mlir::impl::TosaToMLProgramBase< DerivedT >, mlir::impl::TosaToSCFPassBase< DerivedT >, mlir::impl::TosaToTensorPassBase< DerivedT >, mlir::impl::UBToLLVMConversionPassBase< DerivedT >, mlir::impl::UBToSPIRVConversionPassBase< DerivedT >, mlir::impl::ViewOpGraphBase< DerivedT >, mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >, mlir::LLVM::impl::LLVMAddComdatsBase< DerivedT >, mlir::LLVM::impl::LLVMLegalizeForExportPassBase< DerivedT >, mlir::LLVM::impl::LLVMRequestCWrappersPassBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< TargetToDataLayoutPass >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< TargetToTargetFeaturesPass >, mlir::LLVM::impl::LLVMUseDefaultVisibilityPassBase< DerivedT >, mlir::LLVM::impl::NVVMOptimizeForTargetPassBase< DerivedT >, mlir::math::impl::MathExpandOpsPassBase< DerivedT >, mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >, mlir::math::impl::MathSincosFusionPassBase< DerivedT >, mlir::math::impl::MathUpliftToFMABase< DerivedT >, mlir::memref::impl::ExpandOpsPassBase< DerivedT >, mlir::memref::impl::ExpandReallocPassBase< DerivedT >, mlir::memref::impl::ExpandStridedMetadataPassBase< DerivedT >, mlir::memref::impl::FlattenMemrefsPassBase< DerivedT >, mlir::memref::impl::FoldMemRefAliasOpsPassBase< DerivedT >, mlir::memref::impl::MemRefEmulateWideIntBase< DerivedT >, mlir::memref::impl::NormalizeMemRefsPassBase< DerivedT >, mlir::memref::impl::ReifyResultShapesPassBase< DerivedT >, mlir::memref::impl::ResolveRankedShapeTypeResultDimsPassBase< DerivedT >, mlir::memref::impl::ResolveShapedTypeResultDimsPassBase< DerivedT >, mlir::ml_program::impl::MLProgramPipelineGlobalsPassBase< DerivedT >, mlir::nvgpu::impl::OptimizeSharedMemoryBase< DerivedT >, mlir::omp::impl::PrepareForOMPOffloadPrivatizationPassBase< DerivedT >, mlir::PassWrapper< OpToOpPassAdaptor, OperationPass<> >, mlir::quant::impl::LowerQuantOpsBase< DerivedT >, mlir::quant::impl::NormalizeQuantTypesBase< DerivedT >, mlir::quant::impl::StripFuncQuantTypesBase< DerivedT >, mlir::shard::impl::PartitionBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< ShardingPropagation >, mlir::spirv::impl::SPIRVCanonicalizeGLPassBase< DerivedT >, mlir::spirv::impl::SPIRVCompositeTypeLayoutPassBase< DerivedT >, mlir::spirv::impl::SPIRVLowerABIAttributesPassBase< DerivedT >, mlir::spirv::impl::SPIRVReplicatedConstantCompositePassBase< DerivedT >, mlir::spirv::impl::SPIRVRewriteInsertsPassBase< DerivedT >, mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >, mlir::spirv::impl::SPIRVUpdateVCEPassBase< DerivedT >, mlir::spirv::impl::SPIRVWebGPUPreparePassBase< DerivedT >, mlir::tensor::impl::FoldTensorSubsetOpsPassBase< DerivedT >, mlir::tosa::impl::TosaArithConstantToTosaConstPassBase< DerivedT >, mlir::tosa::impl::TosaAttachTargetBase< DerivedT >, mlir::tosa::impl::TosaConvertIntegerTypeToSignlessBase< DerivedT >, mlir::tosa::impl::TosaInferShapesPassBase< DerivedT >, mlir::tosa::impl::TosaLayerwiseConstantFoldPassBase< DerivedT >, mlir::tosa::impl::TosaMakeBroadcastablePassBase< DerivedT >, mlir::tosa::impl::TosaNarrowI64ToI32PassBase< DerivedT >, mlir::tosa::impl::TosaOptionalDecompositionsPassBase< DerivedT >, mlir::tosa::impl::TosaReduceTransposesBase< DerivedT >, mlir::tosa::impl::TosaValidationBase< DerivedT >, mlir::transform::impl::CheckUsesPassBase< DerivedT >, mlir::transform::impl::InferEffectsPassBase< DerivedT >, mlir::transform::impl::InterpreterPassBase< DerivedT >, mlir::transform::impl::PreloadLibraryPassBase< DerivedT >, mlir::vector::impl::LowerVectorMaskPassBase< DerivedT >, mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >, mlir::vector::impl::LowerVectorToFromElementsToShuffleTreeBase< DerivedT >, mlir::xegpu::impl::XeGPUBlockingBase< DerivedT >, mlir::xegpu::impl::XeGPUFoldAliasOpsBase< DerivedT >, mlir::xegpu::impl::XeGPUOptimizeBlockLoadsBase< DerivedT >, mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >, mlir::xegpu::impl::XeGPUSubgroupDistributeBase< DerivedT >, mlir::xegpu::impl::XeGPUVectorLinearizeBase< DerivedT >, and mlir::xegpu::impl::XeGPUWgToSgDistributeBase< DerivedT >.
References Pass().
Referenced by clone().
copyOptionValuesFrom()
void Pass::copyOptionValuesFrom (const Pass * other) protected
Copy the option values from 'other', which is another instance of this pass.
Definition at line 78 of file Pass.cpp.
References Pass().
getAnalysis() [1/2]
template<typename AnalysisT> AnalysisT & mlir::Pass::getAnalysis () inline protected
Query an analysis for the current ir unit.
Definition at line 230 of file Pass.h.
References mlir::AnalysisManager::getAnalysis(), and getAnalysisManager().
Referenced by mlir::InterfacePass< InterfaceT >::getAnalysis(), and mlir::OperationPass< OpT >::getAnalysis().
getAnalysis() [2/2]
template<typename AnalysisT, typename OpT> AnalysisT & mlir::Pass::getAnalysis () inline protected
Query an analysis for the current ir unit of a specific derived operation type.
Definition at line 237 of file Pass.h.
References mlir::AnalysisManager::getAnalysis(), and getAnalysisManager().
getAnalysisManager()
AnalysisManager mlir::Pass::getAnalysisManager () inline protected
Returns the current analysis manager.
Definition at line 298 of file Pass.h.
References mlir::detail::PassExecutionState::analysisManager, and getPassState().
Referenced by getAnalysis(), getCachedAnalysis(), getCachedChildAnalysis(), getCachedParentAnalysis(), getCachedParentAnalysis(), getChildAnalysis(), and getChildAnalysis().
getArgument()
StringRef Pass::getArgument () const inline virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented in mlir::acc::impl::ACCImplicitDataBase< DerivedT >, mlir::acc::impl::ACCImplicitDeclareBase< DerivedT >, mlir::acc::impl::ACCImplicitRoutineBase< DerivedT >, mlir::acc::impl::ACCLegalizeSerialBase< DerivedT >, mlir::acc::impl::ACCLoopTilingBase< DerivedT >, mlir::acc::impl::LegalizeDataValuesInRegionBase< DerivedT >, mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsAsAffineBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsBase< DerivedT >, mlir::affine::impl::AffineLoopFusionBase< DerivedT >, mlir::affine::impl::AffineLoopInvariantCodeMotionBase< DerivedT >, mlir::affine::impl::AffineLoopNormalizeBase< DerivedT >, mlir::affine::impl::AffineLoopTilingBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollAndJamBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollBase< DerivedT >, mlir::affine::impl::AffineParallelizeBase< DerivedT >, mlir::affine::impl::AffinePipelineDataTransferBase< DerivedT >, mlir::affine::impl::AffineScalarReplacementBase< DerivedT >, mlir::affine::impl::AffineVectorizeBase< DerivedT >, mlir::affine::impl::LoopCoalescingBase< DerivedT >, mlir::affine::impl::RaiseMemrefDialectBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< SimplifyAffineMinMaxPass >, mlir::affine::impl::SimplifyAffineStructuresBase< DerivedT >, mlir::amdgpu::impl::AmdgpuEmulateAtomicsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< AmdgpuFoldMemRefOpsPass >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< AmdgpuMaskedloadToLoadPass >, mlir::amdgpu::impl::AmdgpuResolveStridedMetadataPassBase< DerivedT >, mlir::arith::impl::ArithEmulateUnsupportedFloatsBase< DerivedT >, mlir::arith::impl::ArithEmulateWideIntBase< DerivedT >, mlir::arith::impl::ArithExpandOpsPassBase< DerivedT >, mlir::arith::impl::ArithIntRangeNarrowingBase< DerivedT >, mlir::arith::impl::ArithIntRangeOptsBase< DerivedT >, mlir::arith::impl::ArithUnsignedWhenEquivalentPassBase< DerivedT >, mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >, mlir::arm_sme::impl::OuterProductFusionBase< DerivedT >, mlir::arm_sme::impl::TestTileAllocationBase< DerivedT >, mlir::arm_sme::impl::VectorLegalizationBase< DerivedT >, mlir::arm_sve::impl::LegalizeVectorStorageBase< DerivedT >, mlir::bufferization::impl::BufferDeallocationSimplificationPassBase< DerivedT >, mlir::bufferization::impl::BufferHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferLoopHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferResultsToOutParamsPassBase< DerivedT >, mlir::bufferization::impl::DropEquivalentBufferResultsPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorEliminationPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorToAllocTensorPassBase< DerivedT >, mlir::bufferization::impl::LowerDeallocationsPassBase< DerivedT >, mlir::bufferization::impl::OneShotBufferizePassBase< DerivedT >, mlir::bufferization::impl::OptimizeAllocationLivenessPassBase< DerivedT >, mlir::bufferization::impl::OwnershipBasedBufferDeallocationPassBase< DerivedT >, mlir::bufferization::impl::PromoteBuffersToStackPassBase< DerivedT >, mlir::emitc::impl::FormExpressionsPassBase< DerivedT >, mlir::emitc::impl::WrapFuncInClassPassBase< DerivedT >, mlir::ExternalPass, mlir::func::impl::DuplicateFunctionEliminationPassBase< DerivedT >, mlir::impl::ArithToAMDGPUConversionPassBase< DerivedT >, mlir::impl::ArithToAPFloatConversionPassBase< DerivedT >, mlir::impl::ArithToArmSMEConversionPassBase< DerivedT >, mlir::impl::ArithToLLVMConversionPassBase< DerivedT >, mlir::impl::AsyncFuncToAsyncRuntimePassBase< DerivedT >, mlir::impl::AsyncParallelForPassBase< DerivedT >, mlir::impl::AsyncRuntimePolicyBasedRefCountingPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingOptPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingPassBase< DerivedT >, mlir::impl::AsyncToAsyncRuntimePassBase< DerivedT >, mlir::impl::BubbleDownMemorySpaceCastsBase< DerivedT >, mlir::impl::CanonicalizerBase< DerivedT >, mlir::impl::CompositeFixedPointPassBase< DerivedT >, mlir::impl::ControlFlowSinkBase< DerivedT >, mlir::impl::ConvertAffineForToGPUPassBase< DerivedT >, mlir::impl::ConvertAMDGPUToROCDLPassBase< DerivedT >, mlir::impl::ConvertArithToEmitCBase< DerivedT >, mlir::impl::ConvertArithToSPIRVPassBase< DerivedT >, mlir::impl::ConvertArmNeon2dToIntrPassBase< DerivedT >, mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >, mlir::impl::ConvertArmSMEToSCFPassBase< DerivedT >, mlir::impl::ConvertAsyncToLLVMPassBase< DerivedT >, mlir::impl::ConvertBufferizationToMemRefPassBase< DerivedT >, mlir::impl::ConvertComplexToLibmBase< DerivedT >, mlir::impl::ConvertComplexToLLVMPassBase< DerivedT >, mlir::impl::ConvertComplexToROCDLLibraryCallsBase< DerivedT >, mlir::impl::ConvertComplexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertComplexToStandardPassBase< DerivedT >, mlir::impl::ConvertControlFlowToLLVMPassBase< DerivedT >, mlir::impl::ConvertControlFlowToSPIRVPassBase< DerivedT >, mlir::impl::ConvertElementwiseToLinalgPassBase< DerivedT >, mlir::impl::ConvertFuncToEmitCBase< DerivedT >, mlir::impl::ConvertFuncToLLVMPassBase< DerivedT >, mlir::impl::ConvertFuncToSPIRVPassBase< DerivedT >, mlir::impl::ConvertGpuOpsToLLVMSPVOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToNVVMOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToROCDLOpsBase< DerivedT >, mlir::impl::ConvertGPUToSPIRVBase< DerivedT >, mlir::impl::ConvertIndexToLLVMPassBase< DerivedT >, mlir::impl::ConvertIndexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertLinalgToAffineLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToParallelLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToStandardPassBase< DerivedT >, mlir::impl::ConvertMathToEmitCBase< DerivedT >, mlir::impl::ConvertMathToFuncsBase< DerivedT >, mlir::impl::ConvertMathToLibmPassBase< DerivedT >, mlir::impl::ConvertMathToLLVMPassBase< DerivedT >, mlir::impl::ConvertMathToROCDLBase< DerivedT >, mlir::impl::ConvertMathToSPIRVPassBase< DerivedT >, mlir::impl::ConvertMathToXeVMBase< DerivedT >, mlir::impl::ConvertMemRefToEmitCBase< DerivedT >, mlir::impl::ConvertMemRefToSPIRVPassBase< DerivedT >, mlir::impl::ConvertNVGPUToNVVMPassBase< DerivedT >, mlir::impl::ConvertNVVMToLLVMPassBase< DerivedT >, mlir::impl::ConvertOpenACCToSCFPassBase< DerivedT >, mlir::impl::ConvertOpenMPToLLVMPassBase< DerivedT >, mlir::impl::ConvertParallelLoopToGpuPassBase< DerivedT >, mlir::impl::ConvertPDLToPDLInterpPassBase< DerivedT >, mlir::impl::ConvertSCFToOpenMPPassBase< DerivedT >, mlir::impl::ConvertShapeConstraintsPassBase< DerivedT >, mlir::impl::ConvertShapeToStandardPassBase< DerivedT >, mlir::impl::ConvertShardToMPIPassBase< DerivedT >, mlir::impl::ConvertSPIRVToLLVMPassBase< DerivedT >, mlir::impl::ConvertTensorToLinalgPassBase< DerivedT >, mlir::impl::ConvertTensorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertToEmitCBase< DerivedT >, mlir::impl::ConvertToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToAMXBase< DerivedT >, mlir::impl::ConvertVectorToArmSMEPassBase< DerivedT >, mlir::impl::ConvertVectorToGPUBase< DerivedT >, mlir::impl::ConvertVectorToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToSCFBase< DerivedT >, mlir::impl::ConvertVectorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertVectorToXeGPUBase< DerivedT >, mlir::impl::ConvertXeGPUToXeVMPassBase< DerivedT >, mlir::impl::ConvertXeVMToLLVMPassBase< DerivedT >, mlir::impl::CSEBase< DerivedT >, mlir::impl::FinalizeMemRefToLLVMConversionPassBase< DerivedT >, mlir::impl::GenerateRuntimeVerificationBase< DerivedT >, mlir::impl::GpuAsyncRegionPassBase< DerivedT >, mlir::impl::GpuDecomposeMemrefsPassBase< DerivedT >, mlir::impl::GpuEliminateBarriersBase< DerivedT >, mlir::impl::GpuKernelOutliningPassBase< DerivedT >, mlir::impl::GpuLaunchSinkIndexComputationsPassBase< DerivedT >, mlir::impl::GpuMapParallelLoopsPassBase< DerivedT >, mlir::impl::GpuModuleToBinaryPassBase< DerivedT >, mlir::impl::GpuNVVMAttachTargetBase< DerivedT >, mlir::impl::GpuROCDLAttachTargetBase< DerivedT >, mlir::impl::GpuSPIRVAttachTargetBase< DerivedT >, mlir::impl::GpuToLLVMConversionPassBase< DerivedT >, mlir::impl::GpuXeVMAttachTargetBase< DerivedT >, mlir::impl::InlinerBase< DerivedT >, mlir::impl::LiftControlFlowToSCFPassBase< DerivedT >, mlir::impl::LinalgBlockPackMatmulBase< DerivedT >, mlir::impl::LinalgDetensorizePassBase< DerivedT >, mlir::impl::LinalgElementwiseOpFusionPassBase< DerivedT >, mlir::impl::LinalgFoldIntoElementwisePassBase< DerivedT >, mlir::impl::LinalgFoldUnitExtentDimsPassBase< DerivedT >, mlir::impl::LinalgGeneralizeNamedOpsPassBase< DerivedT >, mlir::impl::LinalgInlineScalarOperandsPassBase< DerivedT >, mlir::impl::LinalgMorphOpsPassBase< DerivedT >, mlir::impl::LinalgSpecializeGenericOpsPassBase< DerivedT >, mlir::impl::LocationSnapshotBase< DerivedT >, mlir::impl::LoopInvariantCodeMotionBase< DerivedT >, mlir::impl::LoopInvariantSubsetHoistingBase< DerivedT >, mlir::impl::LowerAffinePassBase< DerivedT >, mlir::impl::LowerForeachToSCFBase< DerivedT >, mlir::impl::LowerHostCodeToLLVMPassBase< DerivedT >, mlir::impl::LowerSparseIterationToSCFBase< DerivedT >, mlir::impl::LowerSparseOpsToForeachBase< DerivedT >, mlir::impl::MapMemRefStorageClassBase< DerivedT >, mlir::impl::Mem2RegBase< DerivedT >, mlir::impl::OptReductionPassBase< DerivedT >, mlir::impl::OutlineShapeComputationPassBase< DerivedT >, mlir::impl::PreSparsificationRewriteBase< DerivedT >, mlir::impl::PrintOpStatsBase< DerivedT >, mlir::impl::ReconcileUnrealizedCastsPassBase< DerivedT >, mlir::impl::ReductionTreePassBase< DerivedT >, mlir::impl::RemoveDeadValuesBase< DerivedT >, mlir::impl::RemoveShapeConstraintsPassBase< DerivedT >, mlir::impl::SCCPBase< DerivedT >, mlir::impl::SCFForallToForLoopBase< DerivedT >, mlir::impl::SCFForallToParallelLoopBase< DerivedT >, mlir::impl::SCFForLoopCanonicalizationBase< DerivedT >, mlir::impl::SCFForLoopPeelingBase< DerivedT >, mlir::impl::SCFForLoopRangeFoldingBase< DerivedT >, mlir::impl::SCFForLoopSpecializationBase< DerivedT >, mlir::impl::SCFForToWhileLoopBase< DerivedT >, mlir::impl::SCFParallelForToNestedForsBase< DerivedT >, mlir::impl::SCFParallelLoopFusionBase< DerivedT >, mlir::impl::SCFParallelLoopSpecializationBase< DerivedT >, mlir::impl::SCFParallelLoopTilingBase< DerivedT >, mlir::impl::SCFToControlFlowPassBase< DerivedT >, mlir::impl::SCFToEmitCBase< DerivedT >, mlir::impl::SCFToSPIRVBase< DerivedT >, mlir::impl::SetLLVMModuleDataLayoutPassBase< DerivedT >, mlir::impl::ShapeToShapeLoweringPassBase< DerivedT >, mlir::impl::SimplifyDepthwiseConvPassBase< DerivedT >, mlir::impl::SparseAssemblerBase< DerivedT >, mlir::impl::SparseBufferRewriteBase< DerivedT >, mlir::impl::SparseGPUCodegenBase< DerivedT >, mlir::impl::SparseReinterpretMapBase< DerivedT >, mlir::impl::SparseSpaceCollapseBase< DerivedT >, mlir::impl::SparseTensorCodegenBase< DerivedT >, mlir::impl::SparseTensorConversionPassBase< DerivedT >, mlir::impl::SparseVectorizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< SparsificationAndBufferizationPass >, mlir::impl::SparsificationPassBase< DerivedT >, mlir::impl::SROABase< DerivedT >, mlir::impl::StageSparseOperationsBase< DerivedT >, mlir::impl::StorageSpecifierToLLVMBase< DerivedT >, mlir::impl::StripDebugInfoBase< DerivedT >, mlir::impl::SymbolDCEBase< DerivedT >, mlir::impl::SymbolPrivatizeBase< DerivedT >, mlir::impl::TestSCFParallelLoopCollapsingBase< DerivedT >, mlir::impl::TopologicalSortBase< DerivedT >, mlir::impl::TosaToArithPassBase< DerivedT >, mlir::impl::TosaToLinalgBase< DerivedT >, mlir::impl::TosaToLinalgNamedBase< DerivedT >, mlir::impl::TosaToMLProgramBase< DerivedT >, mlir::impl::TosaToSCFPassBase< DerivedT >, mlir::impl::TosaToTensorPassBase< DerivedT >, mlir::impl::UBToLLVMConversionPassBase< DerivedT >, mlir::impl::UBToSPIRVConversionPassBase< DerivedT >, mlir::impl::ViewOpGraphBase< DerivedT >, mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >, mlir::LLVM::impl::LLVMAddComdatsBase< DerivedT >, mlir::LLVM::impl::LLVMLegalizeForExportPassBase< DerivedT >, mlir::LLVM::impl::LLVMRequestCWrappersPassBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< TargetToDataLayoutPass >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< TargetToTargetFeaturesPass >, mlir::LLVM::impl::LLVMUseDefaultVisibilityPassBase< DerivedT >, mlir::LLVM::impl::NVVMOptimizeForTargetPassBase< DerivedT >, mlir::math::impl::MathExpandOpsPassBase< DerivedT >, mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >, mlir::math::impl::MathSincosFusionPassBase< DerivedT >, mlir::math::impl::MathUpliftToFMABase< DerivedT >, mlir::memref::impl::ExpandOpsPassBase< DerivedT >, mlir::memref::impl::ExpandReallocPassBase< DerivedT >, mlir::memref::impl::ExpandStridedMetadataPassBase< DerivedT >, mlir::memref::impl::FlattenMemrefsPassBase< DerivedT >, mlir::memref::impl::FoldMemRefAliasOpsPassBase< DerivedT >, mlir::memref::impl::MemRefEmulateWideIntBase< DerivedT >, mlir::memref::impl::NormalizeMemRefsPassBase< DerivedT >, mlir::memref::impl::ReifyResultShapesPassBase< DerivedT >, mlir::memref::impl::ResolveRankedShapeTypeResultDimsPassBase< DerivedT >, mlir::memref::impl::ResolveShapedTypeResultDimsPassBase< DerivedT >, mlir::ml_program::impl::MLProgramPipelineGlobalsPassBase< DerivedT >, mlir::nvgpu::impl::OptimizeSharedMemoryBase< DerivedT >, mlir::omp::impl::PrepareForOMPOffloadPrivatizationPassBase< DerivedT >, mlir::quant::impl::LowerQuantOpsBase< DerivedT >, mlir::quant::impl::NormalizeQuantTypesBase< DerivedT >, mlir::quant::impl::StripFuncQuantTypesBase< DerivedT >, mlir::shard::impl::PartitionBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< ShardingPropagation >, mlir::spirv::impl::SPIRVCanonicalizeGLPassBase< DerivedT >, mlir::spirv::impl::SPIRVCompositeTypeLayoutPassBase< DerivedT >, mlir::spirv::impl::SPIRVLowerABIAttributesPassBase< DerivedT >, mlir::spirv::impl::SPIRVReplicatedConstantCompositePassBase< DerivedT >, mlir::spirv::impl::SPIRVRewriteInsertsPassBase< DerivedT >, mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >, mlir::spirv::impl::SPIRVUpdateVCEPassBase< DerivedT >, mlir::spirv::impl::SPIRVWebGPUPreparePassBase< DerivedT >, mlir::tensor::impl::FoldTensorSubsetOpsPassBase< DerivedT >, mlir::tosa::impl::TosaArithConstantToTosaConstPassBase< DerivedT >, mlir::tosa::impl::TosaAttachTargetBase< DerivedT >, mlir::tosa::impl::TosaConvertIntegerTypeToSignlessBase< DerivedT >, mlir::tosa::impl::TosaInferShapesPassBase< DerivedT >, mlir::tosa::impl::TosaLayerwiseConstantFoldPassBase< DerivedT >, mlir::tosa::impl::TosaMakeBroadcastablePassBase< DerivedT >, mlir::tosa::impl::TosaNarrowI64ToI32PassBase< DerivedT >, mlir::tosa::impl::TosaOptionalDecompositionsPassBase< DerivedT >, mlir::tosa::impl::TosaReduceTransposesBase< DerivedT >, mlir::tosa::impl::TosaValidationBase< DerivedT >, mlir::transform::impl::CheckUsesPassBase< DerivedT >, mlir::transform::impl::InferEffectsPassBase< DerivedT >, mlir::transform::impl::InterpreterPassBase< DerivedT >, mlir::transform::impl::PreloadLibraryPassBase< DerivedT >, mlir::vector::impl::LowerVectorMaskPassBase< DerivedT >, mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >, mlir::vector::impl::LowerVectorToFromElementsToShuffleTreeBase< DerivedT >, mlir::xegpu::impl::XeGPUBlockingBase< DerivedT >, mlir::xegpu::impl::XeGPUFoldAliasOpsBase< DerivedT >, mlir::xegpu::impl::XeGPUOptimizeBlockLoadsBase< DerivedT >, mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >, mlir::xegpu::impl::XeGPUSubgroupDistributeBase< DerivedT >, mlir::xegpu::impl::XeGPUVectorLinearizeBase< DerivedT >, and mlir::xegpu::impl::XeGPUWgToSgDistributeBase< DerivedT >.
Definition at line 76 of file Pass.h.
Referenced by lookupPassInfo(), and printAsTextualPipeline().
getCachedAnalysis()
template<typename AnalysisT> std::optional< std::reference_wrapper< AnalysisT > > mlir::Pass::getCachedAnalysis () inline protected
Query a cached instance of an analysis for the current ir unit if one exists.
Definition at line 244 of file Pass.h.
References getAnalysisManager(), and mlir::AnalysisManager::getCachedAnalysis().
getCachedChildAnalysis()
template<typename AnalysisT> std::optional< std::reference_wrapper< AnalysisT > > mlir::Pass::getCachedChildAnalysis (Operation * child) inline protected
Returns the analysis for the given child operation if it exists.
Definition at line 279 of file Pass.h.
References getAnalysisManager(), and mlir::AnalysisManager::getCachedChildAnalysis().
getCachedParentAnalysis() [1/2]
template<typename AnalysisT> std::optional< std::reference_wrapper< AnalysisT > > mlir::Pass::getCachedParentAnalysis () inline protected
Returns the analysis for the parent operation if it exists.
Definition at line 271 of file Pass.h.
References getAnalysisManager(), mlir::AnalysisManager::getCachedParentAnalysis(), getOperation(), and mlir::Operation::getParentOp().
getCachedParentAnalysis() [2/2]
template<typename AnalysisT> std::optional< std::reference_wrapper< AnalysisT > > mlir::Pass::getCachedParentAnalysis (Operation * parent) inline protected
Returns the analysis for the given parent operation if it exists.
Definition at line 265 of file Pass.h.
References getAnalysisManager(), and mlir::AnalysisManager::getCachedParentAnalysis().
getChildAnalysis() [1/2]
template<typename AnalysisT> AnalysisT & mlir::Pass::getChildAnalysis (Operation * child) inline protected
Returns the analysis for the given child operation, or creates it if it doesn't exist.
Definition at line 286 of file Pass.h.
References getAnalysisManager(), and mlir::AnalysisManager::getChildAnalysis().
getChildAnalysis() [2/2]
template<typename AnalysisT, typename OpTy> AnalysisT & mlir::Pass::getChildAnalysis (OpTy child) inline protected
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
Definition at line 293 of file Pass.h.
References getAnalysisManager(), and mlir::AnalysisManager::getChildAnalysis().
getContext()
MLIRContext & mlir::Pass::getContext () inline protected
Return the MLIR context for the current operation being transformed.
Definition at line 178 of file Pass.h.
References mlir::Operation::getContext(), and getOperation().
Referenced by mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >::createAmdgpuMaskedloadToLoadPass, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< DerivedT >::getDescription(), mlir::amdgpu::AmdgpuFoldMemRefOpsPass::runOnOperation(), and TargetToTargetFeaturesPass::runOnOperation().
getDependentDialects()
virtual void mlir::Pass::getDependentDialects (DialectRegistry & registry) const inline virtual
Register dependent dialects for the current pass.
A pass is expected to register the dialects it will create entities for (Operations, Types, Attributes), other than dialect that exists in the input. For example, a pass that converts from Linalg to Affine would register the Affine dialect but does not need to register Linalg.
Reimplemented in mlir::detail::OpToOpPassAdaptor, and mlir::ExternalPass.
Definition at line 72 of file Pass.h.
getDescription()
StringRef Pass::getDescription () const inline virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented in mlir::acc::impl::ACCImplicitDataBase< DerivedT >, mlir::acc::impl::ACCImplicitDeclareBase< DerivedT >, mlir::acc::impl::ACCImplicitRoutineBase< DerivedT >, mlir::acc::impl::ACCLegalizeSerialBase< DerivedT >, mlir::acc::impl::ACCLoopTilingBase< DerivedT >, mlir::acc::impl::LegalizeDataValuesInRegionBase< DerivedT >, mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsAsAffineBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsBase< DerivedT >, mlir::affine::impl::AffineLoopFusionBase< DerivedT >, mlir::affine::impl::AffineLoopInvariantCodeMotionBase< DerivedT >, mlir::affine::impl::AffineLoopNormalizeBase< DerivedT >, mlir::affine::impl::AffineLoopTilingBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollAndJamBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollBase< DerivedT >, mlir::affine::impl::AffineParallelizeBase< DerivedT >, mlir::affine::impl::AffinePipelineDataTransferBase< DerivedT >, mlir::affine::impl::AffineScalarReplacementBase< DerivedT >, mlir::affine::impl::AffineVectorizeBase< DerivedT >, mlir::affine::impl::LoopCoalescingBase< DerivedT >, mlir::affine::impl::RaiseMemrefDialectBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< SimplifyAffineMinMaxPass >, mlir::affine::impl::SimplifyAffineStructuresBase< DerivedT >, mlir::amdgpu::impl::AmdgpuEmulateAtomicsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< AmdgpuFoldMemRefOpsPass >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< AmdgpuMaskedloadToLoadPass >, mlir::amdgpu::impl::AmdgpuResolveStridedMetadataPassBase< DerivedT >, mlir::arith::impl::ArithEmulateUnsupportedFloatsBase< DerivedT >, mlir::arith::impl::ArithEmulateWideIntBase< DerivedT >, mlir::arith::impl::ArithExpandOpsPassBase< DerivedT >, mlir::arith::impl::ArithIntRangeNarrowingBase< DerivedT >, mlir::arith::impl::ArithIntRangeOptsBase< DerivedT >, mlir::arith::impl::ArithUnsignedWhenEquivalentPassBase< DerivedT >, mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >, mlir::arm_sme::impl::OuterProductFusionBase< DerivedT >, mlir::arm_sme::impl::TestTileAllocationBase< DerivedT >, mlir::arm_sme::impl::VectorLegalizationBase< DerivedT >, mlir::arm_sve::impl::LegalizeVectorStorageBase< DerivedT >, mlir::bufferization::impl::BufferDeallocationSimplificationPassBase< DerivedT >, mlir::bufferization::impl::BufferHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferLoopHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferResultsToOutParamsPassBase< DerivedT >, mlir::bufferization::impl::DropEquivalentBufferResultsPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorEliminationPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorToAllocTensorPassBase< DerivedT >, mlir::bufferization::impl::LowerDeallocationsPassBase< DerivedT >, mlir::bufferization::impl::OneShotBufferizePassBase< DerivedT >, mlir::bufferization::impl::OptimizeAllocationLivenessPassBase< DerivedT >, mlir::bufferization::impl::OwnershipBasedBufferDeallocationPassBase< DerivedT >, mlir::bufferization::impl::PromoteBuffersToStackPassBase< DerivedT >, mlir::emitc::impl::FormExpressionsPassBase< DerivedT >, mlir::emitc::impl::WrapFuncInClassPassBase< DerivedT >, mlir::ExternalPass, mlir::func::impl::DuplicateFunctionEliminationPassBase< DerivedT >, mlir::impl::ArithToAMDGPUConversionPassBase< DerivedT >, mlir::impl::ArithToAPFloatConversionPassBase< DerivedT >, mlir::impl::ArithToArmSMEConversionPassBase< DerivedT >, mlir::impl::ArithToLLVMConversionPassBase< DerivedT >, mlir::impl::AsyncFuncToAsyncRuntimePassBase< DerivedT >, mlir::impl::AsyncParallelForPassBase< DerivedT >, mlir::impl::AsyncRuntimePolicyBasedRefCountingPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingOptPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingPassBase< DerivedT >, mlir::impl::AsyncToAsyncRuntimePassBase< DerivedT >, mlir::impl::BubbleDownMemorySpaceCastsBase< DerivedT >, mlir::impl::CanonicalizerBase< DerivedT >, mlir::impl::CompositeFixedPointPassBase< DerivedT >, mlir::impl::ControlFlowSinkBase< DerivedT >, mlir::impl::ConvertAffineForToGPUPassBase< DerivedT >, mlir::impl::ConvertAMDGPUToROCDLPassBase< DerivedT >, mlir::impl::ConvertArithToEmitCBase< DerivedT >, mlir::impl::ConvertArithToSPIRVPassBase< DerivedT >, mlir::impl::ConvertArmNeon2dToIntrPassBase< DerivedT >, mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >, mlir::impl::ConvertArmSMEToSCFPassBase< DerivedT >, mlir::impl::ConvertAsyncToLLVMPassBase< DerivedT >, mlir::impl::ConvertBufferizationToMemRefPassBase< DerivedT >, mlir::impl::ConvertComplexToLibmBase< DerivedT >, mlir::impl::ConvertComplexToLLVMPassBase< DerivedT >, mlir::impl::ConvertComplexToROCDLLibraryCallsBase< DerivedT >, mlir::impl::ConvertComplexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertComplexToStandardPassBase< DerivedT >, mlir::impl::ConvertControlFlowToLLVMPassBase< DerivedT >, mlir::impl::ConvertControlFlowToSPIRVPassBase< DerivedT >, mlir::impl::ConvertElementwiseToLinalgPassBase< DerivedT >, mlir::impl::ConvertFuncToEmitCBase< DerivedT >, mlir::impl::ConvertFuncToLLVMPassBase< DerivedT >, mlir::impl::ConvertFuncToSPIRVPassBase< DerivedT >, mlir::impl::ConvertGpuOpsToLLVMSPVOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToNVVMOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToROCDLOpsBase< DerivedT >, mlir::impl::ConvertGPUToSPIRVBase< DerivedT >, mlir::impl::ConvertIndexToLLVMPassBase< DerivedT >, mlir::impl::ConvertIndexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertLinalgToAffineLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToParallelLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToStandardPassBase< DerivedT >, mlir::impl::ConvertMathToEmitCBase< DerivedT >, mlir::impl::ConvertMathToFuncsBase< DerivedT >, mlir::impl::ConvertMathToLibmPassBase< DerivedT >, mlir::impl::ConvertMathToLLVMPassBase< DerivedT >, mlir::impl::ConvertMathToROCDLBase< DerivedT >, mlir::impl::ConvertMathToSPIRVPassBase< DerivedT >, mlir::impl::ConvertMathToXeVMBase< DerivedT >, mlir::impl::ConvertMemRefToEmitCBase< DerivedT >, mlir::impl::ConvertMemRefToSPIRVPassBase< DerivedT >, mlir::impl::ConvertNVGPUToNVVMPassBase< DerivedT >, mlir::impl::ConvertNVVMToLLVMPassBase< DerivedT >, mlir::impl::ConvertOpenACCToSCFPassBase< DerivedT >, mlir::impl::ConvertOpenMPToLLVMPassBase< DerivedT >, mlir::impl::ConvertParallelLoopToGpuPassBase< DerivedT >, mlir::impl::ConvertPDLToPDLInterpPassBase< DerivedT >, mlir::impl::ConvertSCFToOpenMPPassBase< DerivedT >, mlir::impl::ConvertShapeConstraintsPassBase< DerivedT >, mlir::impl::ConvertShapeToStandardPassBase< DerivedT >, mlir::impl::ConvertShardToMPIPassBase< DerivedT >, mlir::impl::ConvertSPIRVToLLVMPassBase< DerivedT >, mlir::impl::ConvertTensorToLinalgPassBase< DerivedT >, mlir::impl::ConvertTensorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertToEmitCBase< DerivedT >, mlir::impl::ConvertToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToAMXBase< DerivedT >, mlir::impl::ConvertVectorToArmSMEPassBase< DerivedT >, mlir::impl::ConvertVectorToGPUBase< DerivedT >, mlir::impl::ConvertVectorToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToSCFBase< DerivedT >, mlir::impl::ConvertVectorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertVectorToXeGPUBase< DerivedT >, mlir::impl::ConvertXeGPUToXeVMPassBase< DerivedT >, mlir::impl::ConvertXeVMToLLVMPassBase< DerivedT >, mlir::impl::CSEBase< DerivedT >, mlir::impl::FinalizeMemRefToLLVMConversionPassBase< DerivedT >, mlir::impl::GenerateRuntimeVerificationBase< DerivedT >, mlir::impl::GpuAsyncRegionPassBase< DerivedT >, mlir::impl::GpuDecomposeMemrefsPassBase< DerivedT >, mlir::impl::GpuEliminateBarriersBase< DerivedT >, mlir::impl::GpuKernelOutliningPassBase< DerivedT >, mlir::impl::GpuLaunchSinkIndexComputationsPassBase< DerivedT >, mlir::impl::GpuMapParallelLoopsPassBase< DerivedT >, mlir::impl::GpuModuleToBinaryPassBase< DerivedT >, mlir::impl::GpuNVVMAttachTargetBase< DerivedT >, mlir::impl::GpuROCDLAttachTargetBase< DerivedT >, mlir::impl::GpuSPIRVAttachTargetBase< DerivedT >, mlir::impl::GpuToLLVMConversionPassBase< DerivedT >, mlir::impl::GpuXeVMAttachTargetBase< DerivedT >, mlir::impl::InlinerBase< DerivedT >, mlir::impl::LiftControlFlowToSCFPassBase< DerivedT >, mlir::impl::LinalgBlockPackMatmulBase< DerivedT >, mlir::impl::LinalgDetensorizePassBase< DerivedT >, mlir::impl::LinalgElementwiseOpFusionPassBase< DerivedT >, mlir::impl::LinalgFoldIntoElementwisePassBase< DerivedT >, mlir::impl::LinalgFoldUnitExtentDimsPassBase< DerivedT >, mlir::impl::LinalgGeneralizeNamedOpsPassBase< DerivedT >, mlir::impl::LinalgInlineScalarOperandsPassBase< DerivedT >, mlir::impl::LinalgMorphOpsPassBase< DerivedT >, mlir::impl::LinalgSpecializeGenericOpsPassBase< DerivedT >, mlir::impl::LocationSnapshotBase< DerivedT >, mlir::impl::LoopInvariantCodeMotionBase< DerivedT >, mlir::impl::LoopInvariantSubsetHoistingBase< DerivedT >, mlir::impl::LowerAffinePassBase< DerivedT >, mlir::impl::LowerForeachToSCFBase< DerivedT >, mlir::impl::LowerHostCodeToLLVMPassBase< DerivedT >, mlir::impl::LowerSparseIterationToSCFBase< DerivedT >, mlir::impl::LowerSparseOpsToForeachBase< DerivedT >, mlir::impl::MapMemRefStorageClassBase< DerivedT >, mlir::impl::Mem2RegBase< DerivedT >, mlir::impl::OptReductionPassBase< DerivedT >, mlir::impl::OutlineShapeComputationPassBase< DerivedT >, mlir::impl::PreSparsificationRewriteBase< DerivedT >, mlir::impl::PrintOpStatsBase< DerivedT >, mlir::impl::ReconcileUnrealizedCastsPassBase< DerivedT >, mlir::impl::ReductionTreePassBase< DerivedT >, mlir::impl::RemoveDeadValuesBase< DerivedT >, mlir::impl::RemoveShapeConstraintsPassBase< DerivedT >, mlir::impl::SCCPBase< DerivedT >, mlir::impl::SCFForallToForLoopBase< DerivedT >, mlir::impl::SCFForallToParallelLoopBase< DerivedT >, mlir::impl::SCFForLoopCanonicalizationBase< DerivedT >, mlir::impl::SCFForLoopPeelingBase< DerivedT >, mlir::impl::SCFForLoopRangeFoldingBase< DerivedT >, mlir::impl::SCFForLoopSpecializationBase< DerivedT >, mlir::impl::SCFForToWhileLoopBase< DerivedT >, mlir::impl::SCFParallelForToNestedForsBase< DerivedT >, mlir::impl::SCFParallelLoopFusionBase< DerivedT >, mlir::impl::SCFParallelLoopSpecializationBase< DerivedT >, mlir::impl::SCFParallelLoopTilingBase< DerivedT >, mlir::impl::SCFToControlFlowPassBase< DerivedT >, mlir::impl::SCFToEmitCBase< DerivedT >, mlir::impl::SCFToSPIRVBase< DerivedT >, mlir::impl::SetLLVMModuleDataLayoutPassBase< DerivedT >, mlir::impl::ShapeToShapeLoweringPassBase< DerivedT >, mlir::impl::SimplifyDepthwiseConvPassBase< DerivedT >, mlir::impl::SparseAssemblerBase< DerivedT >, mlir::impl::SparseBufferRewriteBase< DerivedT >, mlir::impl::SparseGPUCodegenBase< DerivedT >, mlir::impl::SparseReinterpretMapBase< DerivedT >, mlir::impl::SparseSpaceCollapseBase< DerivedT >, mlir::impl::SparseTensorCodegenBase< DerivedT >, mlir::impl::SparseTensorConversionPassBase< DerivedT >, mlir::impl::SparseVectorizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< SparsificationAndBufferizationPass >, mlir::impl::SparsificationPassBase< DerivedT >, mlir::impl::SROABase< DerivedT >, mlir::impl::StageSparseOperationsBase< DerivedT >, mlir::impl::StorageSpecifierToLLVMBase< DerivedT >, mlir::impl::StripDebugInfoBase< DerivedT >, mlir::impl::SymbolDCEBase< DerivedT >, mlir::impl::SymbolPrivatizeBase< DerivedT >, mlir::impl::TestSCFParallelLoopCollapsingBase< DerivedT >, mlir::impl::TopologicalSortBase< DerivedT >, mlir::impl::TosaToArithPassBase< DerivedT >, mlir::impl::TosaToLinalgBase< DerivedT >, mlir::impl::TosaToLinalgNamedBase< DerivedT >, mlir::impl::TosaToMLProgramBase< DerivedT >, mlir::impl::TosaToSCFPassBase< DerivedT >, mlir::impl::TosaToTensorPassBase< DerivedT >, mlir::impl::UBToLLVMConversionPassBase< DerivedT >, mlir::impl::UBToSPIRVConversionPassBase< DerivedT >, mlir::impl::ViewOpGraphBase< DerivedT >, mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >, mlir::LLVM::impl::LLVMAddComdatsBase< DerivedT >, mlir::LLVM::impl::LLVMLegalizeForExportPassBase< DerivedT >, mlir::LLVM::impl::LLVMRequestCWrappersPassBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< TargetToDataLayoutPass >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< TargetToTargetFeaturesPass >, mlir::LLVM::impl::LLVMUseDefaultVisibilityPassBase< DerivedT >, mlir::LLVM::impl::NVVMOptimizeForTargetPassBase< DerivedT >, mlir::math::impl::MathExpandOpsPassBase< DerivedT >, mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >, mlir::math::impl::MathSincosFusionPassBase< DerivedT >, mlir::math::impl::MathUpliftToFMABase< DerivedT >, mlir::memref::impl::ExpandOpsPassBase< DerivedT >, mlir::memref::impl::ExpandReallocPassBase< DerivedT >, mlir::memref::impl::ExpandStridedMetadataPassBase< DerivedT >, mlir::memref::impl::FlattenMemrefsPassBase< DerivedT >, mlir::memref::impl::FoldMemRefAliasOpsPassBase< DerivedT >, mlir::memref::impl::MemRefEmulateWideIntBase< DerivedT >, mlir::memref::impl::NormalizeMemRefsPassBase< DerivedT >, mlir::memref::impl::ReifyResultShapesPassBase< DerivedT >, mlir::memref::impl::ResolveRankedShapeTypeResultDimsPassBase< DerivedT >, mlir::memref::impl::ResolveShapedTypeResultDimsPassBase< DerivedT >, mlir::ml_program::impl::MLProgramPipelineGlobalsPassBase< DerivedT >, mlir::nvgpu::impl::OptimizeSharedMemoryBase< DerivedT >, mlir::omp::impl::PrepareForOMPOffloadPrivatizationPassBase< DerivedT >, mlir::quant::impl::LowerQuantOpsBase< DerivedT >, mlir::quant::impl::NormalizeQuantTypesBase< DerivedT >, mlir::quant::impl::StripFuncQuantTypesBase< DerivedT >, mlir::shard::impl::PartitionBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< ShardingPropagation >, mlir::spirv::impl::SPIRVCanonicalizeGLPassBase< DerivedT >, mlir::spirv::impl::SPIRVCompositeTypeLayoutPassBase< DerivedT >, mlir::spirv::impl::SPIRVLowerABIAttributesPassBase< DerivedT >, mlir::spirv::impl::SPIRVReplicatedConstantCompositePassBase< DerivedT >, mlir::spirv::impl::SPIRVRewriteInsertsPassBase< DerivedT >, mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >, mlir::spirv::impl::SPIRVUpdateVCEPassBase< DerivedT >, mlir::spirv::impl::SPIRVWebGPUPreparePassBase< DerivedT >, mlir::tensor::impl::FoldTensorSubsetOpsPassBase< DerivedT >, mlir::tosa::impl::TosaArithConstantToTosaConstPassBase< DerivedT >, mlir::tosa::impl::TosaAttachTargetBase< DerivedT >, mlir::tosa::impl::TosaConvertIntegerTypeToSignlessBase< DerivedT >, mlir::tosa::impl::TosaInferShapesPassBase< DerivedT >, mlir::tosa::impl::TosaLayerwiseConstantFoldPassBase< DerivedT >, mlir::tosa::impl::TosaMakeBroadcastablePassBase< DerivedT >, mlir::tosa::impl::TosaNarrowI64ToI32PassBase< DerivedT >, mlir::tosa::impl::TosaOptionalDecompositionsPassBase< DerivedT >, mlir::tosa::impl::TosaReduceTransposesBase< DerivedT >, mlir::tosa::impl::TosaValidationBase< DerivedT >, mlir::transform::impl::CheckUsesPassBase< DerivedT >, mlir::transform::impl::InferEffectsPassBase< DerivedT >, mlir::transform::impl::InterpreterPassBase< DerivedT >, mlir::transform::impl::PreloadLibraryPassBase< DerivedT >, mlir::vector::impl::LowerVectorMaskPassBase< DerivedT >, mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >, mlir::vector::impl::LowerVectorToFromElementsToShuffleTreeBase< DerivedT >, mlir::xegpu::impl::XeGPUBlockingBase< DerivedT >, mlir::xegpu::impl::XeGPUFoldAliasOpsBase< DerivedT >, mlir::xegpu::impl::XeGPUOptimizeBlockLoadsBase< DerivedT >, mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >, mlir::xegpu::impl::XeGPUSubgroupDistributeBase< DerivedT >, mlir::xegpu::impl::XeGPUVectorLinearizeBase< DerivedT >, and mlir::xegpu::impl::XeGPUWgToSgDistributeBase< DerivedT >.
Definition at line 80 of file Pass.h.
getName()
virtual StringRef mlir::Pass::getName () const pure virtual
Returns the derived pass name.
Implemented in mlir::acc::impl::ACCImplicitDataBase< DerivedT >, mlir::acc::impl::ACCImplicitDeclareBase< DerivedT >, mlir::acc::impl::ACCImplicitRoutineBase< DerivedT >, mlir::acc::impl::ACCLegalizeSerialBase< DerivedT >, mlir::acc::impl::ACCLoopTilingBase< DerivedT >, mlir::acc::impl::LegalizeDataValuesInRegionBase< DerivedT >, mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsAsAffineBase< DerivedT >, mlir::affine::impl::AffineExpandIndexOpsBase< DerivedT >, mlir::affine::impl::AffineLoopFusionBase< DerivedT >, mlir::affine::impl::AffineLoopInvariantCodeMotionBase< DerivedT >, mlir::affine::impl::AffineLoopNormalizeBase< DerivedT >, mlir::affine::impl::AffineLoopTilingBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollAndJamBase< DerivedT >, mlir::affine::impl::AffineLoopUnrollBase< DerivedT >, mlir::affine::impl::AffineParallelizeBase< DerivedT >, mlir::affine::impl::AffinePipelineDataTransferBase< DerivedT >, mlir::affine::impl::AffineScalarReplacementBase< DerivedT >, mlir::affine::impl::AffineVectorizeBase< DerivedT >, mlir::affine::impl::LoopCoalescingBase< DerivedT >, mlir::affine::impl::RaiseMemrefDialectBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< DerivedT >, mlir::affine::impl::SimplifyAffineMinMaxPassBase< SimplifyAffineMinMaxPass >, mlir::affine::impl::SimplifyAffineStructuresBase< DerivedT >, mlir::amdgpu::impl::AmdgpuEmulateAtomicsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuFoldMemRefOpsPassBase< AmdgpuFoldMemRefOpsPass >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >, mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< AmdgpuMaskedloadToLoadPass >, mlir::amdgpu::impl::AmdgpuResolveStridedMetadataPassBase< DerivedT >, mlir::arith::impl::ArithEmulateUnsupportedFloatsBase< DerivedT >, mlir::arith::impl::ArithEmulateWideIntBase< DerivedT >, mlir::arith::impl::ArithExpandOpsPassBase< DerivedT >, mlir::arith::impl::ArithIntRangeNarrowingBase< DerivedT >, mlir::arith::impl::ArithIntRangeOptsBase< DerivedT >, mlir::arith::impl::ArithUnsignedWhenEquivalentPassBase< DerivedT >, mlir::arm_sme::impl::EnableArmStreamingBase< DerivedT >, mlir::arm_sme::impl::OuterProductFusionBase< DerivedT >, mlir::arm_sme::impl::TestTileAllocationBase< DerivedT >, mlir::arm_sme::impl::VectorLegalizationBase< DerivedT >, mlir::arm_sve::impl::LegalizeVectorStorageBase< DerivedT >, mlir::bufferization::impl::BufferDeallocationSimplificationPassBase< DerivedT >, mlir::bufferization::impl::BufferHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferLoopHoistingPassBase< DerivedT >, mlir::bufferization::impl::BufferResultsToOutParamsPassBase< DerivedT >, mlir::bufferization::impl::DropEquivalentBufferResultsPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorEliminationPassBase< DerivedT >, mlir::bufferization::impl::EmptyTensorToAllocTensorPassBase< DerivedT >, mlir::bufferization::impl::LowerDeallocationsPassBase< DerivedT >, mlir::bufferization::impl::OneShotBufferizePassBase< DerivedT >, mlir::bufferization::impl::OptimizeAllocationLivenessPassBase< DerivedT >, mlir::bufferization::impl::OwnershipBasedBufferDeallocationPassBase< DerivedT >, mlir::bufferization::impl::PromoteBuffersToStackPassBase< DerivedT >, mlir::emitc::impl::FormExpressionsPassBase< DerivedT >, mlir::emitc::impl::WrapFuncInClassPassBase< DerivedT >, mlir::ExternalPass, mlir::func::impl::DuplicateFunctionEliminationPassBase< DerivedT >, mlir::impl::ArithToAMDGPUConversionPassBase< DerivedT >, mlir::impl::ArithToAPFloatConversionPassBase< DerivedT >, mlir::impl::ArithToArmSMEConversionPassBase< DerivedT >, mlir::impl::ArithToLLVMConversionPassBase< DerivedT >, mlir::impl::AsyncFuncToAsyncRuntimePassBase< DerivedT >, mlir::impl::AsyncParallelForPassBase< DerivedT >, mlir::impl::AsyncRuntimePolicyBasedRefCountingPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingOptPassBase< DerivedT >, mlir::impl::AsyncRuntimeRefCountingPassBase< DerivedT >, mlir::impl::AsyncToAsyncRuntimePassBase< DerivedT >, mlir::impl::BubbleDownMemorySpaceCastsBase< DerivedT >, mlir::impl::CanonicalizerBase< DerivedT >, mlir::impl::CompositeFixedPointPassBase< DerivedT >, mlir::impl::ControlFlowSinkBase< DerivedT >, mlir::impl::ConvertAffineForToGPUPassBase< DerivedT >, mlir::impl::ConvertAMDGPUToROCDLPassBase< DerivedT >, mlir::impl::ConvertArithToEmitCBase< DerivedT >, mlir::impl::ConvertArithToSPIRVPassBase< DerivedT >, mlir::impl::ConvertArmNeon2dToIntrPassBase< DerivedT >, mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >, mlir::impl::ConvertArmSMEToSCFPassBase< DerivedT >, mlir::impl::ConvertAsyncToLLVMPassBase< DerivedT >, mlir::impl::ConvertBufferizationToMemRefPassBase< DerivedT >, mlir::impl::ConvertComplexToLibmBase< DerivedT >, mlir::impl::ConvertComplexToLLVMPassBase< DerivedT >, mlir::impl::ConvertComplexToROCDLLibraryCallsBase< DerivedT >, mlir::impl::ConvertComplexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertComplexToStandardPassBase< DerivedT >, mlir::impl::ConvertControlFlowToLLVMPassBase< DerivedT >, mlir::impl::ConvertControlFlowToSPIRVPassBase< DerivedT >, mlir::impl::ConvertElementwiseToLinalgPassBase< DerivedT >, mlir::impl::ConvertFuncToEmitCBase< DerivedT >, mlir::impl::ConvertFuncToLLVMPassBase< DerivedT >, mlir::impl::ConvertFuncToSPIRVPassBase< DerivedT >, mlir::impl::ConvertGpuOpsToLLVMSPVOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToNVVMOpsBase< DerivedT >, mlir::impl::ConvertGpuOpsToROCDLOpsBase< DerivedT >, mlir::impl::ConvertGPUToSPIRVBase< DerivedT >, mlir::impl::ConvertIndexToLLVMPassBase< DerivedT >, mlir::impl::ConvertIndexToSPIRVPassBase< DerivedT >, mlir::impl::ConvertLinalgToAffineLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToParallelLoopsPassBase< DerivedT >, mlir::impl::ConvertLinalgToStandardPassBase< DerivedT >, mlir::impl::ConvertMathToEmitCBase< DerivedT >, mlir::impl::ConvertMathToFuncsBase< DerivedT >, mlir::impl::ConvertMathToLibmPassBase< DerivedT >, mlir::impl::ConvertMathToLLVMPassBase< DerivedT >, mlir::impl::ConvertMathToROCDLBase< DerivedT >, mlir::impl::ConvertMathToSPIRVPassBase< DerivedT >, mlir::impl::ConvertMathToXeVMBase< DerivedT >, mlir::impl::ConvertMemRefToEmitCBase< DerivedT >, mlir::impl::ConvertMemRefToSPIRVPassBase< DerivedT >, mlir::impl::ConvertNVGPUToNVVMPassBase< DerivedT >, mlir::impl::ConvertNVVMToLLVMPassBase< DerivedT >, mlir::impl::ConvertOpenACCToSCFPassBase< DerivedT >, mlir::impl::ConvertOpenMPToLLVMPassBase< DerivedT >, mlir::impl::ConvertParallelLoopToGpuPassBase< DerivedT >, mlir::impl::ConvertPDLToPDLInterpPassBase< DerivedT >, mlir::impl::ConvertSCFToOpenMPPassBase< DerivedT >, mlir::impl::ConvertShapeConstraintsPassBase< DerivedT >, mlir::impl::ConvertShapeToStandardPassBase< DerivedT >, mlir::impl::ConvertShardToMPIPassBase< DerivedT >, mlir::impl::ConvertSPIRVToLLVMPassBase< DerivedT >, mlir::impl::ConvertTensorToLinalgPassBase< DerivedT >, mlir::impl::ConvertTensorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertToEmitCBase< DerivedT >, mlir::impl::ConvertToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToAMXBase< DerivedT >, mlir::impl::ConvertVectorToArmSMEPassBase< DerivedT >, mlir::impl::ConvertVectorToGPUBase< DerivedT >, mlir::impl::ConvertVectorToLLVMPassBase< DerivedT >, mlir::impl::ConvertVectorToSCFBase< DerivedT >, mlir::impl::ConvertVectorToSPIRVPassBase< DerivedT >, mlir::impl::ConvertVectorToXeGPUBase< DerivedT >, mlir::impl::ConvertXeGPUToXeVMPassBase< DerivedT >, mlir::impl::ConvertXeVMToLLVMPassBase< DerivedT >, mlir::impl::CSEBase< DerivedT >, mlir::impl::FinalizeMemRefToLLVMConversionPassBase< DerivedT >, mlir::impl::GenerateRuntimeVerificationBase< DerivedT >, mlir::impl::GpuAsyncRegionPassBase< DerivedT >, mlir::impl::GpuDecomposeMemrefsPassBase< DerivedT >, mlir::impl::GpuEliminateBarriersBase< DerivedT >, mlir::impl::GpuKernelOutliningPassBase< DerivedT >, mlir::impl::GpuLaunchSinkIndexComputationsPassBase< DerivedT >, mlir::impl::GpuMapParallelLoopsPassBase< DerivedT >, mlir::impl::GpuModuleToBinaryPassBase< DerivedT >, mlir::impl::GpuNVVMAttachTargetBase< DerivedT >, mlir::impl::GpuROCDLAttachTargetBase< DerivedT >, mlir::impl::GpuSPIRVAttachTargetBase< DerivedT >, mlir::impl::GpuToLLVMConversionPassBase< DerivedT >, mlir::impl::GpuXeVMAttachTargetBase< DerivedT >, mlir::impl::InlinerBase< DerivedT >, mlir::impl::LiftControlFlowToSCFPassBase< DerivedT >, mlir::impl::LinalgBlockPackMatmulBase< DerivedT >, mlir::impl::LinalgDetensorizePassBase< DerivedT >, mlir::impl::LinalgElementwiseOpFusionPassBase< DerivedT >, mlir::impl::LinalgFoldIntoElementwisePassBase< DerivedT >, mlir::impl::LinalgFoldUnitExtentDimsPassBase< DerivedT >, mlir::impl::LinalgGeneralizeNamedOpsPassBase< DerivedT >, mlir::impl::LinalgInlineScalarOperandsPassBase< DerivedT >, mlir::impl::LinalgMorphOpsPassBase< DerivedT >, mlir::impl::LinalgSpecializeGenericOpsPassBase< DerivedT >, mlir::impl::LocationSnapshotBase< DerivedT >, mlir::impl::LoopInvariantCodeMotionBase< DerivedT >, mlir::impl::LoopInvariantSubsetHoistingBase< DerivedT >, mlir::impl::LowerAffinePassBase< DerivedT >, mlir::impl::LowerForeachToSCFBase< DerivedT >, mlir::impl::LowerHostCodeToLLVMPassBase< DerivedT >, mlir::impl::LowerSparseIterationToSCFBase< DerivedT >, mlir::impl::LowerSparseOpsToForeachBase< DerivedT >, mlir::impl::MapMemRefStorageClassBase< DerivedT >, mlir::impl::Mem2RegBase< DerivedT >, mlir::impl::OptReductionPassBase< DerivedT >, mlir::impl::OutlineShapeComputationPassBase< DerivedT >, mlir::impl::PreSparsificationRewriteBase< DerivedT >, mlir::impl::PrintOpStatsBase< DerivedT >, mlir::impl::ReconcileUnrealizedCastsPassBase< DerivedT >, mlir::impl::ReductionTreePassBase< DerivedT >, mlir::impl::RemoveDeadValuesBase< DerivedT >, mlir::impl::RemoveShapeConstraintsPassBase< DerivedT >, mlir::impl::SCCPBase< DerivedT >, mlir::impl::SCFForallToForLoopBase< DerivedT >, mlir::impl::SCFForallToParallelLoopBase< DerivedT >, mlir::impl::SCFForLoopCanonicalizationBase< DerivedT >, mlir::impl::SCFForLoopPeelingBase< DerivedT >, mlir::impl::SCFForLoopRangeFoldingBase< DerivedT >, mlir::impl::SCFForLoopSpecializationBase< DerivedT >, mlir::impl::SCFForToWhileLoopBase< DerivedT >, mlir::impl::SCFParallelForToNestedForsBase< DerivedT >, mlir::impl::SCFParallelLoopFusionBase< DerivedT >, mlir::impl::SCFParallelLoopSpecializationBase< DerivedT >, mlir::impl::SCFParallelLoopTilingBase< DerivedT >, mlir::impl::SCFToControlFlowPassBase< DerivedT >, mlir::impl::SCFToEmitCBase< DerivedT >, mlir::impl::SCFToSPIRVBase< DerivedT >, mlir::impl::SetLLVMModuleDataLayoutPassBase< DerivedT >, mlir::impl::ShapeToShapeLoweringPassBase< DerivedT >, mlir::impl::SimplifyDepthwiseConvPassBase< DerivedT >, mlir::impl::SparseAssemblerBase< DerivedT >, mlir::impl::SparseBufferRewriteBase< DerivedT >, mlir::impl::SparseGPUCodegenBase< DerivedT >, mlir::impl::SparseReinterpretMapBase< DerivedT >, mlir::impl::SparseSpaceCollapseBase< DerivedT >, mlir::impl::SparseTensorCodegenBase< DerivedT >, mlir::impl::SparseTensorConversionPassBase< DerivedT >, mlir::impl::SparseVectorizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< DerivedT >, mlir::impl::SparsificationAndBufferizationBase< SparsificationAndBufferizationPass >, mlir::impl::SparsificationPassBase< DerivedT >, mlir::impl::SROABase< DerivedT >, mlir::impl::StageSparseOperationsBase< DerivedT >, mlir::impl::StorageSpecifierToLLVMBase< DerivedT >, mlir::impl::StripDebugInfoBase< DerivedT >, mlir::impl::SymbolDCEBase< DerivedT >, mlir::impl::SymbolPrivatizeBase< DerivedT >, mlir::impl::TestSCFParallelLoopCollapsingBase< DerivedT >, mlir::impl::TopologicalSortBase< DerivedT >, mlir::impl::TosaToArithPassBase< DerivedT >, mlir::impl::TosaToLinalgBase< DerivedT >, mlir::impl::TosaToLinalgNamedBase< DerivedT >, mlir::impl::TosaToMLProgramBase< DerivedT >, mlir::impl::TosaToSCFPassBase< DerivedT >, mlir::impl::TosaToTensorPassBase< DerivedT >, mlir::impl::UBToLLVMConversionPassBase< DerivedT >, mlir::impl::UBToSPIRVConversionPassBase< DerivedT >, mlir::impl::ViewOpGraphBase< DerivedT >, mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >, mlir::LLVM::impl::LLVMAddComdatsBase< DerivedT >, mlir::LLVM::impl::LLVMLegalizeForExportPassBase< DerivedT >, mlir::LLVM::impl::LLVMRequestCWrappersPassBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToDataLayoutBase< TargetToDataLayoutPass >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< DerivedT >, mlir::LLVM::impl::LLVMTargetToTargetFeaturesBase< TargetToTargetFeaturesPass >, mlir::LLVM::impl::LLVMUseDefaultVisibilityPassBase< DerivedT >, mlir::LLVM::impl::NVVMOptimizeForTargetPassBase< DerivedT >, mlir::math::impl::MathExpandOpsPassBase< DerivedT >, mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >, mlir::math::impl::MathSincosFusionPassBase< DerivedT >, mlir::math::impl::MathUpliftToFMABase< DerivedT >, mlir::memref::impl::ExpandOpsPassBase< DerivedT >, mlir::memref::impl::ExpandReallocPassBase< DerivedT >, mlir::memref::impl::ExpandStridedMetadataPassBase< DerivedT >, mlir::memref::impl::FlattenMemrefsPassBase< DerivedT >, mlir::memref::impl::FoldMemRefAliasOpsPassBase< DerivedT >, mlir::memref::impl::MemRefEmulateWideIntBase< DerivedT >, mlir::memref::impl::NormalizeMemRefsPassBase< DerivedT >, mlir::memref::impl::ReifyResultShapesPassBase< DerivedT >, mlir::memref::impl::ResolveRankedShapeTypeResultDimsPassBase< DerivedT >, mlir::memref::impl::ResolveShapedTypeResultDimsPassBase< DerivedT >, mlir::ml_program::impl::MLProgramPipelineGlobalsPassBase< DerivedT >, mlir::nvgpu::impl::OptimizeSharedMemoryBase< DerivedT >, mlir::omp::impl::PrepareForOMPOffloadPrivatizationPassBase< DerivedT >, mlir::PassWrapper< OpToOpPassAdaptor, OperationPass<> >, mlir::quant::impl::LowerQuantOpsBase< DerivedT >, mlir::quant::impl::NormalizeQuantTypesBase< DerivedT >, mlir::quant::impl::StripFuncQuantTypesBase< DerivedT >, mlir::shard::impl::PartitionBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< DerivedT >, mlir::shard::impl::ShardingPropagationBase< ShardingPropagation >, mlir::spirv::impl::SPIRVCanonicalizeGLPassBase< DerivedT >, mlir::spirv::impl::SPIRVCompositeTypeLayoutPassBase< DerivedT >, mlir::spirv::impl::SPIRVLowerABIAttributesPassBase< DerivedT >, mlir::spirv::impl::SPIRVReplicatedConstantCompositePassBase< DerivedT >, mlir::spirv::impl::SPIRVRewriteInsertsPassBase< DerivedT >, mlir::spirv::impl::SPIRVUnifyAliasedResourcePassBase< DerivedT >, mlir::spirv::impl::SPIRVUpdateVCEPassBase< DerivedT >, mlir::spirv::impl::SPIRVWebGPUPreparePassBase< DerivedT >, mlir::tensor::impl::FoldTensorSubsetOpsPassBase< DerivedT >, mlir::tosa::impl::TosaArithConstantToTosaConstPassBase< DerivedT >, mlir::tosa::impl::TosaAttachTargetBase< DerivedT >, mlir::tosa::impl::TosaConvertIntegerTypeToSignlessBase< DerivedT >, mlir::tosa::impl::TosaInferShapesPassBase< DerivedT >, mlir::tosa::impl::TosaLayerwiseConstantFoldPassBase< DerivedT >, mlir::tosa::impl::TosaMakeBroadcastablePassBase< DerivedT >, mlir::tosa::impl::TosaNarrowI64ToI32PassBase< DerivedT >, mlir::tosa::impl::TosaOptionalDecompositionsPassBase< DerivedT >, mlir::tosa::impl::TosaReduceTransposesBase< DerivedT >, mlir::tosa::impl::TosaValidationBase< DerivedT >, mlir::transform::impl::CheckUsesPassBase< DerivedT >, mlir::transform::impl::InferEffectsPassBase< DerivedT >, mlir::transform::impl::InterpreterPassBase< DerivedT >, mlir::transform::impl::PreloadLibraryPassBase< DerivedT >, mlir::vector::impl::LowerVectorMaskPassBase< DerivedT >, mlir::vector::impl::LowerVectorMultiReductionBase< DerivedT >, mlir::vector::impl::LowerVectorToFromElementsToShuffleTreeBase< DerivedT >, mlir::xegpu::impl::XeGPUBlockingBase< DerivedT >, mlir::xegpu::impl::XeGPUFoldAliasOpsBase< DerivedT >, mlir::xegpu::impl::XeGPUOptimizeBlockLoadsBase< DerivedT >, mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >, mlir::xegpu::impl::XeGPUSubgroupDistributeBase< DerivedT >, mlir::xegpu::impl::XeGPUVectorLinearizeBase< DerivedT >, and mlir::xegpu::impl::XeGPUWgToSgDistributeBase< DerivedT >.
Referenced by printAsTextualPipeline().
getOperation()
Operation * mlir::Pass::getOperation () inline protected
Return the current operation being transformed.
Definition at line 220 of file Pass.h.
References getPassState(), and mlir::detail::PassExecutionState::irAndPassFailed.
Referenced by getCachedParentAnalysis(), getContext(), mlir::InterfacePass< InterfaceT >::getOperation(), mlir::OperationPass< OpT >::getOperation(), and mlir::ExternalPass::runOnOperation().
getOpName()
std::optional< StringRef > mlir::Pass::getOpName () const inline
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
Definition at line 84 of file Pass.h.
Referenced by mlir::ExternalPass::canScheduleOn(), mlir::OperationPass< OpT >::canScheduleOn(), mlir::OperationPass< OpT >::classof(), and mlir::ExternalPass::clonePass().
getPassState()
detail::PassExecutionState & mlir::Pass::getPassState () inline protected
Returns the current pass state.
Definition at line 172 of file Pass.h.
Referenced by getAnalysisManager(), getOperation(), markAllAnalysesPreserved(), markAnalysesPreserved(), markAnalysesPreserved(), and signalPassFailure().
getStatistics() [1/2]
MutableArrayRef< Statistic * > mlir::Pass::getStatistics () inline
Definition at line 146 of file Pass.h.
getStatistics() [2/2]
ArrayRef< PassStatistic > Pass::getStatistics () const inline
Returns the main statistics for this pass instance.
Definition at line 145 of file Pass.h.
getThreadingSibling()
const Pass * mlir::Pass::getThreadingSibling () const inline
Returns the thread sibling of this pass.
If this pass was cloned by the pass manager for the sake of multi-threading, this function returns the original pass it was cloned from. This is useful for diagnostic purposes to distinguish passes that were replicated for threading purposes from passes instantiated by the user. Used to collapse passes in timing statistics.
Definition at line 155 of file Pass.h.
References Pass().
getThreadingSiblingOrThis()
const Pass * mlir::Pass::getThreadingSiblingOrThis () const inline
Returns the thread sibling of this pass, or the pass itself it has no sibling.
See getThreadingSibling() for details.
Definition at line 159 of file Pass.h.
References Pass().
getTypeID()
TypeID mlir::Pass::getTypeID () const inline
Returns the unique identifier that corresponds to this pass.
Definition at line 57 of file Pass.h.
Referenced by mlir::PassWrapper< PassT, BaseT >::classof().
initialize()
virtual LogicalResult mlir::Pass::initialize (MLIRContext * context) inline protected virtual
Initialize any complex state necessary for running this pass.
This hook should not rely on any state accessible during the execution of a pass. For example, getContext/getOperation/getAnalysis/etc. should not be invoked within this hook. This method is invoked after all dependent dialects for the pipeline are loaded, and is not allowed to load any further dialects (override the getDependentDialects() for this purpose instead). Returns a LogicalResult to indicate failure, in which case the pass pipeline won't execute.
Reimplemented in mlir::ExternalPass.
Definition at line 191 of file Pass.h.
References success().
initializeOptions()
LogicalResult Pass::initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler) virtual
Attempt to initialize the options of this pass from the given string.
Derived classes may override this method to hook into the point at which options are initialized, but should generally always invoke this base class variant.
Definition at line 65 of file Pass.cpp.
References options, and success().
lookupPassInfo()
const PassInfo * mlir::Pass::lookupPassInfo () const inline
Returns the pass info for this pass, or null if unknown.
Definition at line 60 of file Pass.h.
References getArgument(), mlir::PassInfo::lookup(), and PassInfo.
markAllAnalysesPreserved()
void mlir::Pass::markAllAnalysesPreserved () inline protected
Mark all analyses as preserved.
Definition at line 249 of file Pass.h.
References getPassState(), mlir::detail::PreservedAnalyses::preserveAll(), and mlir::detail::PassExecutionState::preservedAnalyses.
markAnalysesPreserved() [1/2]
template<typename... AnalysesT> void mlir::Pass::markAnalysesPreserved () inline protected
Mark the provided analyses as preserved.
Definition at line 255 of file Pass.h.
References getPassState(), mlir::detail::PreservedAnalyses::preserve(), and mlir::detail::PassExecutionState::preservedAnalyses.
markAnalysesPreserved() [2/2]
void mlir::Pass::markAnalysesPreserved (TypeID id) inline protected
Definition at line 258 of file Pass.h.
References getPassState(), mlir::detail::PreservedAnalyses::preserve(), and mlir::detail::PassExecutionState::preservedAnalyses.
operator=() [1/2]
Pass & mlir::Pass::operator= (const Pass &) protected delete
References Pass().
operator=() [2/2]
Pass & mlir::Pass::operator= (Pass &&) protected delete
References Pass().
printAsTextualPipeline()
void Pass::printAsTextualPipeline (raw_ostream & os, bool pretty = false)
Prints out the pass in the textual representation of pipelines.
If this is an adaptor pass, print its pass managers. When pretty is true, the printed pipeline is formatted for readability.
Definition at line 85 of file Pass.cpp.
References getArgument(), getName(), and OpPassManager.
Referenced by mlir::detail::PassCrashReproducerGenerator::prepareReproducerFor(), mlir::detail::PassCrashReproducerGenerator::prepareReproducerFor(), and printAsTextualPipeline().
runOnOperation()
virtual void mlir::Pass::runOnOperation () protected pure virtual
The polymorphic API that runs the pass over the currently held operation.
Implemented in AmdgpuMaskedloadToLoadPass, mlir::amdgpu::AmdgpuFoldMemRefOpsPass, mlir::detail::OpToOpPassAdaptor, mlir::ExternalPass, mlir::sparse_tensor::SparsificationAndBufferizationPass, ShardingPropagation, SimplifyAffineMinMaxPass, TargetToDataLayoutPass, and TargetToTargetFeaturesPass.
Referenced by mlir::bufferization::impl::BufferResultsToOutParamsPassBase< DerivedT >::BufferResultsToOutParamsPassBase(), mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::classof(), mlir::omp::impl::PrepareForOMPOffloadPrivatizationPassBase< DerivedT >::classof(), mlir::affine::impl::AffineDataCopyGenerationBase< DerivedT >::clonePass(), mlir::impl::AsyncFuncToAsyncRuntimePassBase< DerivedT >::clonePass(), mlir::impl::GpuKernelOutliningPassBase< DerivedT >::clonePass(), mlir::memref::impl::ExpandReallocPassBase< DerivedT >::clonePass(), mlir::impl::ReductionTreePassBase< DerivedT >::createReductionTreePass, mlir::impl::BubbleDownMemorySpaceCastsBase< DerivedT >::getArgumentName(), mlir::quant::impl::NormalizeQuantTypesBase< DerivedT >::getDependentDialects(), mlir::tosa::impl::TosaInferShapesPassBase< DerivedT >::getDependentDialects(), mlir::impl::LowerSparseIterationToSCFBase< DerivedT >::getName(), mlir::impl::SparseAssemblerBase< DerivedT >::getName(), mlir::impl::AsyncFuncToAsyncRuntimePassBase< DerivedT >::getPassName(), mlir::impl::LowerForeachToSCFBase< DerivedT >::getPassName(), mlir::impl::GpuAsyncRegionPassBase< DerivedT >::GpuAsyncRegionPassBase(), mlir::emitc::impl::FormExpressionsPassBase< DerivedT >::operator=(), mlir::impl::LowerSparseIterationToSCFBase< DerivedT >::operator=(), mlir::impl::SparseBufferRewriteBase< DerivedT >::operator=(), and mlir::spirv::impl::SPIRVCompositeTypeLayoutPassBase< DerivedT >::SPIRVCompositeTypeLayoutPassBase().
runPipeline()
LogicalResult mlir::Pass::runPipeline (OpPassManager & pipeline, Operation * op) inline protected
Schedule an arbitrary pass pipeline on the provided operation.
This can be invoke any time in a pass to dynamic schedule more passes. The provided operation must be the current one or one nested below.
Definition at line 208 of file Pass.h.
References OpPassManager.
Referenced by mlir::impl::OptReductionPassBase< DerivedT >::clonePass(), and mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation().
signalPassFailure()
void mlir::Pass::signalPassFailure () inline protected
Signal that some invariant was broken when running.
The IR is allowed to be in an invalid state.
Definition at line 226 of file Pass.h.
References getPassState(), and mlir::detail::PassExecutionState::irAndPassFailed.
Referenced by mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >::clonePass(), mlir::impl::SparseBufferRewriteBase< DerivedT >::clonePass(), mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::clonePass(), mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >::ConvertArmSMEToLLVMBase(), mlir::amdgpu::impl::AmdgpuMaskedloadToLoadPassBase< DerivedT >::createAmdgpuMaskedloadToLoadPass, mlir::bufferization::impl::BufferResultsToOutParamsPassBase< DerivedT >::createBufferResultsToOutParamsPass, mlir::impl::BubbleDownMemorySpaceCastsBase< DerivedT >::getArgument(), mlir::impl::ConvertArmSMEToLLVMBase< DerivedT >::getArgument(), mlir::impl::PreSparsificationRewriteBase< DerivedT >::getArgument(), mlir::math::impl::MathExtendToSupportedTypesBase< DerivedT >::getArgumentName(), mlir::impl::GpuKernelOutliningPassBase< DerivedT >::getDependentDialects(), mlir::impl::OptReductionPassBase< DerivedT >::getDependentDialects(), mlir::memref::impl::ExpandReallocPassBase< DerivedT >::getDependentDialects(), mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getDescription(), mlir::impl::OptReductionPassBase< DerivedT >::getDescription(), mlir::emitc::impl::FormExpressionsPassBase< DerivedT >::getName(), mlir::impl::GpuLaunchSinkIndexComputationsPassBase< DerivedT >::getName(), mlir::impl::OptReductionPassBase< DerivedT >::getName(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation(), ShardingPropagation::runOnOperation(), SimplifyAffineMinMaxPass::runOnOperation(), TargetToTargetFeaturesPass::runOnOperation(), mlir::ExternalPass::signalPassFailure(), mlir::PassInstrumentation::signalPassFailure(), and mlir::impl::SparseAssemblerBase< DerivedT >::~SparseAssemblerBase().
Friends And Related Symbol Documentation
OpPassManager
friend class OpPassManager friend
Allow access to 'clone'.
Definition at line 335 of file Pass.h.
References OpPassManager.
Referenced by mlir::detail::OpToOpPassAdaptor::getAdaptorName(), mlir::impl::OptReductionPassBase< DerivedT >::getArgument(), OpPassManager, mlir::detail::OpToOpPassAdaptor::OpToOpPassAdaptor(), printAsTextualPipeline(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation(), runPipeline(), and mlir::detail::OpToOpPassAdaptor::tryMergeInto().
PassInfo
friend class PassInfo friend
Allow access to 'passOptions'.
Definition at line 344 of file Pass.h.
References PassInfo.
Referenced by lookupPassInfo(), and PassInfo.
PassInstrumentation
friend class PassInstrumentation friend
Allow access to 'signalPassFailure'.
Definition at line 347 of file Pass.h.
References PassInstrumentation.
Referenced by PassInstrumentation.
The documentation for this class was generated from the following files:
include/mlir/Pass/Pass.h
lib/Pass/Pass.cpp
lib/TableGen/Pass.cpp