MLIR: mlir::presburger::LinearTransform Class Reference
mlir::presburger::LinearTransform Class Reference
#include "mlir/Analysis/Presburger/LinearTransform.h"
Public Member Functions
LinearTransform (IntMatrix &&oMatrix)
LinearTransform (const IntMatrix &oMatrix)
IntegerRelation applyTo (const IntegerRelation &rel) const
SmallVector< DynamicAPInt, 8 > preMultiplyWithRow (ArrayRef< DynamicAPInt > rowVec) const
SmallVector< DynamicAPInt, 8 > postMultiplyWithColumn (ArrayRef< DynamicAPInt > colVec) const
Static Public Member Functions
static std::pair< unsigned, LinearTransform > makeTransformToColumnEchelon (const IntMatrix &m)
Detailed Description
Definition at line 23 of file LinearTransform.h.
Constructor & Destructor Documentation
LinearTransform() [1/2]
LinearTransform::LinearTransform (IntMatrix && oMatrix) explicit
Definition at line 17 of file LinearTransform.cpp.
Referenced by makeTransformToColumnEchelon().
LinearTransform() [2/2]
LinearTransform::LinearTransform (const IntMatrix & oMatrix) explicit
Definition at line 18 of file LinearTransform.cpp.
Member Function Documentation
applyTo()
IntegerRelation LinearTransform::applyTo (const IntegerRelation & rel) const
Definition at line 45 of file LinearTransform.cpp.
References mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::IntegerRelation::addInequality(), mlir::presburger::IntegerRelation::getEquality(), mlir::presburger::IntegerRelation::getInequality(), mlir::presburger::IntegerRelation::getNumEqualities(), mlir::presburger::IntegerRelation::getNumInequalities(), mlir::presburger::IntegerRelation::getSpace(), and preMultiplyWithRow().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
makeTransformToColumnEchelon()
std::pair< unsigned, LinearTransform > LinearTransform::makeTransformToColumnEchelon (const IntMatrix & m) static
Definition at line 21 of file LinearTransform.cpp.
References mlir::presburger::IntMatrix::computeHermiteNormalForm(), mlir::presburger::Matrix< T >::getNumColumns(), mlir::presburger::Matrix< T >::getNumRows(), and LinearTransform().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
postMultiplyWithColumn()
SmallVector<DynamicAPInt, 8> mlir::presburger::LinearTransform::postMultiplyWithColumn (ArrayRef< DynamicAPInt > colVec) const inline
Definition at line 51 of file LinearTransform.h.
References mlir::presburger::Matrix< T >::postMultiplyWithColumn().
Referenced by mlir::presburger::IntegerRelation::findIntegerSample().
preMultiplyWithRow()
SmallVector<DynamicAPInt, 8> mlir::presburger::LinearTransform::preMultiplyWithRow (ArrayRef< DynamicAPInt > rowVec) const inline
Definition at line 44 of file LinearTransform.h.
References mlir::presburger::Matrix< T >::preMultiplyWithRow().
Referenced by applyTo().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/LinearTransform.h
lib/Analysis/Presburger/LinearTransform.cpp