MLIR: mlir::ScopedDiagnosticHandler Class Reference
mlir::ScopedDiagnosticHandler Class Reference
This diagnostic handler is a simple RAII class that registers and erases a diagnostic handler on a given context.
#include "mlir/IR/Diagnostics.h"
Public Member Functions
ScopedDiagnosticHandler (MLIRContext *ctx)
template<typename FuncTy >
ScopedDiagnosticHandler (MLIRContext *ctx, FuncTy &&handler)
~ScopedDiagnosticHandler ()
Protected Member Functions
template<typename FuncTy >
void setHandler (FuncTy &&handler)
Set the handler to manage via RAII.
Detailed Description
This diagnostic handler is a simple RAII class that registers and erases a diagnostic handler on a given context.
This class can be either be used directly, or in conjunction with a derived diagnostic handler.
Definition at line 522 of file Diagnostics.h.
Constructor & Destructor Documentation
ScopedDiagnosticHandler() [1/2]
mlir::ScopedDiagnosticHandler::ScopedDiagnosticHandler (MLIRContext * ctx) inline explicit
Definition at line 524 of file Diagnostics.h.
ScopedDiagnosticHandler() [2/2]
template<typename FuncTy > mlir::ScopedDiagnosticHandler::ScopedDiagnosticHandler (MLIRContext * ctx, FuncTy && handler) inline
Definition at line 526 of file Diagnostics.h.
References setHandler().
~ScopedDiagnosticHandler()
ScopedDiagnosticHandler::~ScopedDiagnosticHandler ()
Definition at line 353 of file Diagnostics.cpp.
Member Function Documentation
setHandler()
template<typename FuncTy > void mlir::ScopedDiagnosticHandler::setHandler (FuncTy && handler) inline protected
Set the handler to manage via RAII.
Definition at line 535 of file Diagnostics.h.
References mlir::DiagnosticEngine::eraseHandler(), and mlir::MLIRContext::getDiagEngine().
Referenced by ScopedDiagnosticHandler(), and mlir::SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler().
The documentation for this class was generated from the following files:
include/mlir/IR/Diagnostics.h
lib/IR/Diagnostics.cpp