MLIR: mlir::tblgen::PropConstraint Class Reference
mlir::tblgen::PropConstraint Class Reference
#include "mlir/TableGen/Property.h"
Public Member Functions
StringRef getInterfaceType () const
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record, Kind kind)
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
Constraints are pointer-comparable.
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getSummary () const
StringRef getDescription () const
StringRef getDefName () const
Returns the name of the TablGen def of this constraint.
std::string getUniqueDefName () const
Returns a unique name for the TablGen def of this constraint.
std::optional< StringRef > getCppFunctionName () const
Returns the name of the C++ function that should be generated for this constraint, or std::nullopt if no C++ function should be generated.
Kind getKind () const
const llvm::Record & getDef () const
Return the underlying def.
Static Public Member Functions
static bool classof (const Constraint *c)
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind {
CK_Attr , CK_Prop , CK_Region , CK_Successor ,
CK_Type , CK_Uncategorized
}
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 34 of file Property.h.
Member Function Documentation
classof()
bool mlir::tblgen::PropConstraint::classof (const Constraint * c) inline static
Definition at line 38 of file Property.h.
References mlir::tblgen::Constraint::CK_Prop, Constraint(), and mlir::tblgen::Constraint::getKind().
Constraint() [1/2]
Constraint::Constraint (const llvm::Record * record)
Definition at line 45 of file Constraint.cpp.
Constraint() [2/2]
mlir::tblgen::Constraint::Constraint (const llvm::Record * record, Kind kind) inline
Definition at line 43 of file Constraint.h.
Referenced by classof(), and mlir::tblgen::Property::Property().
getInterfaceType()
StringRef PropConstraint::getInterfaceType () const
Definition at line 35 of file Property.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Property.h
lib/TableGen/Property.cpp