MLIR: mlir::HyperrectangularSlice Class Reference
mlir::HyperrectangularSlice Class Reference
A hyperrectangular slice, represented as a list of offsets, sizes and strides.
#include "mlir/Interfaces/ValueBoundsOpInterface.h"
Public Member Functions
HyperrectangularSlice (ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides)
HyperrectangularSlice (ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes)
Create a hyperrectangular slice with unit strides.
HyperrectangularSlice (OffsetSizeAndStrideOpInterface op)
Infer a hyperrectangular slice from OffsetSizeAndStrideOpInterface.
ArrayRef< OpFoldResult > getMixedOffsets () const
ArrayRef< OpFoldResult > getMixedSizes () const
ArrayRef< OpFoldResult > getMixedStrides () const
Detailed Description
A hyperrectangular slice, represented as a list of offsets, sizes and strides.
Definition at line 28 of file ValueBoundsOpInterface.h.
Constructor & Destructor Documentation
HyperrectangularSlice() [1/3]
HyperrectangularSlice::HyperrectangularSlice (ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides)
Definition at line 37 of file ValueBoundsOpInterface.cpp.
Referenced by HyperrectangularSlice().
HyperrectangularSlice() [2/3]
HyperrectangularSlice::HyperrectangularSlice (ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes)
Create a hyperrectangular slice with unit strides.
Definition at line 47 of file ValueBoundsOpInterface.cpp.
HyperrectangularSlice() [3/3]
HyperrectangularSlice::HyperrectangularSlice (OffsetSizeAndStrideOpInterface op)
Infer a hyperrectangular slice from OffsetSizeAndStrideOpInterface.
Definition at line 59 of file ValueBoundsOpInterface.cpp.
References getMixedOffsets(), getMixedSizes(), getMixedStrides(), and HyperrectangularSlice().
Member Function Documentation
getMixedOffsets()
ArrayRef< OpFoldResult > mlir::HyperrectangularSlice::getMixedOffsets () const inline
Definition at line 41 of file ValueBoundsOpInterface.h.
Referenced by mlir::ValueBoundsConstraintSet::areEquivalentSlices(), mlir::ValueBoundsConstraintSet::areOverlappingSlices(), and HyperrectangularSlice().
getMixedSizes()
ArrayRef< OpFoldResult > mlir::HyperrectangularSlice::getMixedSizes () const inline
Definition at line 42 of file ValueBoundsOpInterface.h.
Referenced by mlir::ValueBoundsConstraintSet::areEquivalentSlices(), mlir::ValueBoundsConstraintSet::areOverlappingSlices(), and HyperrectangularSlice().
getMixedStrides()
ArrayRef< OpFoldResult > mlir::HyperrectangularSlice::getMixedStrides () const inline
Definition at line 43 of file ValueBoundsOpInterface.h.
Referenced by mlir::ValueBoundsConstraintSet::areEquivalentSlices(), mlir::ValueBoundsConstraintSet::areOverlappingSlices(), and HyperrectangularSlice().
The documentation for this class was generated from the following files:
include/mlir/Interfaces/ValueBoundsOpInterface.h
lib/Interfaces/ValueBoundsOpInterface.cpp