MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegionList Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegionList Class Reference
Regions of an op are fixed length and indexed numerically so are represented with a sequence-like container.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyRegionList (PyOperationRef operation, intptr_t startIndex=0, intptr_t length=-1, intptr_t step=1)
Public Member Functions inherited from mlir::Sliceable< PyRegionList, PyRegion >
Sliceable (intptr_t startIndex, intptr_t length, intptr_t step)
PyRegion getElement (intptr_t index)
Returns the index-th element in the slice, supports negative indices.
intptr_t size ()
Returns the size of slice.
std::vector< PyRegion > dunderAdd (PyRegionList &other)
Returns a new vector (mapped to Python list) containing elements from two slices.
Static Public Attributes
static constexpr const char * pyClassName = "RegionSequence"
Friends
class Sliceable< PyRegionList, PyRegion >
Give the parent CRTP class access to hook implementations below.
Additional Inherited Members
Static Public Member Functions inherited from mlir::Sliceable< PyRegionList, PyRegion >
static void bind (nanobind::module_ &m)
Binds the indexing and length methods in the Python class.
static void bindDerived (ClassTy &)
Hook for derived classes willing to bind more methods.
Public Attributes inherited from mlir::Sliceable< PyRegionList, PyRegion >
intptr_t startIndex
intptr_t length
intptr_t step
Protected Types inherited from mlir::Sliceable< PyRegionList, PyRegion >
using ClassTy
Protected Member Functions inherited from mlir::Sliceable< PyRegionList, PyRegion >
intptr_t wrapIndex (intptr_t index)
Transforms index into a legal value to access the underlying sequence.
intptr_t linearizeIndex (intptr_t index)
Computes the linear index given the current slice properties.
nanobind::typed< nanobind::object, PyRegion > getItem (intptr_t index)
Returns the element at the given slice index.
nanobind::object getItemSlice (PyObject *slice)
Returns a new instance of the pseudo-container restricted to the given slice.
Static Protected Attributes inherited from mlir::Sliceable< PyRegionList, PyRegion >
static constexpr std::array< const char *, 0 > typeParams
Type parameter names for generic classes.
Detailed Description
Regions of an op are fixed length and indexed numerically so are represented with a sequence-like container.
Definition at line 1513 of file IRCore.h.
Constructor & Destructor Documentation
PyRegionList()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegionList::PyRegionList (PyOperationRef operation, intptr_t startIndex = 0, intptr_t length = -1, intptr_t step = 1)
Definition at line 194 of file IRCore.cpp.
References mlir::get(), mlir::Sliceable< PyRegionList, PyRegion >::length, mlirOperationGetNumRegions(), mlir::Sliceable< PyRegionList, PyRegion >::Sliceable(), mlir::Sliceable< PyRegionList, PyRegion >::startIndex, and mlir::Sliceable< PyRegionList, PyRegion >::step.
Referenced by Sliceable< PyRegionList, PyRegion >.
Friends And Related Symbol Documentation
Sliceable< PyRegionList, PyRegion >
friend class Sliceable< PyRegionList, PyRegion > friend
Give the parent CRTP class access to hook implementations below.
Definition at line 1518 of file IRCore.h.
References mlir::Sliceable< PyRegionList, PyRegion >::length, PyRegionList(), mlir::Sliceable< PyRegionList, PyRegion >::Sliceable(), mlir::Sliceable< PyRegionList, PyRegion >::startIndex, and mlir::Sliceable< PyRegionList, PyRegion >::step.
Member Data Documentation
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegionList::pyClassName = "RegionSequence" static constexpr
Definition at line 1516 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp