MLIR: mlir::DynamicOpDefinition Class Reference
mlir::DynamicOpDefinition Class Reference
The definition of a dynamic op.
#include "mlir/IR/ExtensibleDialect.h"
Public Types
using GetCanonicalizationPatternsFn
Public Member Functions
TypeID getTypeID ()
Returns the op typeID.
void setVerifyFn (OperationName::VerifyInvariantsFn &&verify)
Sets the verifier function for this operation.
void setVerifyRegionFn (OperationName::VerifyRegionInvariantsFn &&verify)
Sets the region verifier function for this operation.
void setParseFn (OperationName::ParseAssemblyFn &&parse)
Sets the static hook for parsing this op assembly.
void setPrintFn (OperationName::PrintAssemblyFn &&print)
Sets the static hook for printing this op assembly.
void setFoldHookFn (OperationName::FoldHookFn &&foldHook)
Sets the hook implementing a generalized folder for the op.
void setGetCanonicalizationPatternsFn (GetCanonicalizationPatternsFn &&getCanonicalizationPatterns)
Set the hook returning any canonicalization pattern rewrites that the op supports, for use by the canonicalization pass.
void setPopulateDefaultAttrsFn (OperationName::PopulateDefaultAttrsFn &&populateDefaultAttrs)
Set the hook populating default attributes.
LogicalResult foldHook (Operation *op, ArrayRef< Attribute > attrs, SmallVectorImpl< OpFoldResult > &results) final
void getCanonicalizationPatterns (RewritePatternSet &set, MLIRContext *context) final
bool hasTrait (TypeID id) final
OperationName::ParseAssemblyFn getParseAssemblyFn () final
void populateDefaultAttrs (const OperationName &name, NamedAttrList &attrs) final
void printAssembly (Operation *op, OpAsmPrinter &printer, StringRef name) final
LogicalResult verifyInvariants (Operation *op) final
LogicalResult verifyRegionInvariants (Operation *op) final
std::optional< Attribute > getInherentAttr (Operation *op, StringRef name) final
Implementation for properties (unsupported right now here).
void setInherentAttr (Operation *op, StringAttr name, Attribute value) final
void populateInherentAttrs (Operation *op, NamedAttrList &attrs) final
LogicalResult verifyInherentAttrs (OperationName opName, NamedAttrList &attributes, function_ref< InFlightDiagnostic()> emitError) final
int getOpPropertyByteSize () final
void initProperties (OperationName opName, OpaqueProperties storage, OpaqueProperties init) final
void deleteProperties (OpaqueProperties prop) final
void populateDefaultProperties (OperationName opName, OpaqueProperties properties) final
LogicalResult setPropertiesFromAttr (OperationName opName, OpaqueProperties properties, Attribute attr, function_ref< InFlightDiagnostic()> emitError) final
Attribute getPropertiesAsAttr (Operation *op) final
void copyProperties (OpaqueProperties lhs, OpaqueProperties rhs) final
bool compareProperties (OpaqueProperties, OpaqueProperties) final
llvm::hash_code hashProperties (OpaqueProperties prop) final
Public Member Functions inherited from mlir::OperationName::Impl
Impl (StringRef, Dialect *dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
Impl (StringAttr name, Dialect *dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
bool isRegistered () const
Returns true if this is a registered operation.
detail::InterfaceMap & getInterfaceMap ()
Dialect * getDialect () const
StringAttr getName () const
TypeID getTypeID () const
ArrayRef< StringAttr > getAttributeNames () const
Public Member Functions inherited from mlir::OperationName::InterfaceConcept
virtual ~InterfaceConcept ()=default
Static Public Member Functions
static std::unique_ptr< DynamicOpDefinition > get (StringRef name, ExtensibleDialect *dialect, OperationName::VerifyInvariantsFn &&verifyFn, OperationName::VerifyRegionInvariantsFn &&verifyRegionFn)
Create a new op at runtime.
static std::unique_ptr< DynamicOpDefinition > get (StringRef name, ExtensibleDialect *dialect, OperationName::VerifyInvariantsFn &&verifyFn, OperationName::VerifyRegionInvariantsFn &&verifyRegionFn, OperationName::ParseAssemblyFn &&parseFn, OperationName::PrintAssemblyFn &&printFn)
static std::unique_ptr< DynamicOpDefinition > get (StringRef name, ExtensibleDialect *dialect, OperationName::VerifyInvariantsFn &&verifyFn, OperationName::VerifyRegionInvariantsFn &&verifyRegionFn, OperationName::ParseAssemblyFn &&parseFn, OperationName::PrintAssemblyFn &&printFn, OperationName::FoldHookFn &&foldHookFn, GetCanonicalizationPatternsFn &&getCanonicalizationPatternsFn, OperationName::PopulateDefaultAttrsFn &&populateDefaultAttrsFn)
Additional Inherited Members
Protected Attributes inherited from mlir::OperationName::Impl
StringAttr name
The name of the operation.
TypeID typeID
The unique identifier of the derived Op class.
Dialect * dialect
The following fields are only populated when the operation is registered.
detail::InterfaceMap interfaceMap
A map of interfaces that were registered to this operation.
ArrayRef< StringAttr > attributeNames
A list of attribute names registered to this operation in StringAttr form.
Detailed Description
The definition of a dynamic op.
A dynamic op is an op that is defined at runtime, and that can be registered at runtime by an extensible dialect (a dialect inheriting ExtensibleDialect). This class implements the method exposed by the OperationName class, and in addition defines the TypeID of the op that will be defined. Each dynamic operation definition refers to one instance of this class.
Definition at line 367 of file ExtensibleDialect.h.
Member Typedef Documentation
GetCanonicalizationPatternsFn
using mlir::DynamicOpDefinition::GetCanonicalizationPatternsFn
Initial value:
      llvm::unique_function<void(RewritePatternSet &, MLIRContext *) const>
Definition at line 369 of file ExtensibleDialect.h.
Member Function Documentation
compareProperties()
bool mlir::DynamicOpDefinition::compareProperties (OpaqueProperties , OpaqueProperties) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 497 of file ExtensibleDialect.h.
copyProperties()
void mlir::DynamicOpDefinition::copyProperties (OpaqueProperties lhs, OpaqueProperties rhs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 496 of file ExtensibleDialect.h.
References lhs, and rhs.
deleteProperties()
void mlir::DynamicOpDefinition::deleteProperties (OpaqueProperties prop) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 484 of file ExtensibleDialect.h.
foldHook()
LogicalResult mlir::DynamicOpDefinition::foldHook (Operation * op, ArrayRef< Attribute > attrs, SmallVectorImpl< OpFoldResult > & results) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 440 of file ExtensibleDialect.h.
Referenced by setFoldHookFn().
get() [1/3]
std::unique_ptr< DynamicOpDefinition > DynamicOpDefinition::get (StringRef name, ExtensibleDialect * dialect, OperationName::VerifyInvariantsFn && verifyFn, OperationName::VerifyRegionInvariantsFn && verifyRegionFn) static
Create a new op at runtime.
The op is registered only after passing it to the dialect using registerDynamicOp.
Definition at line 309 of file ExtensibleDialect.cpp.
References mlir::OperationName::Impl::dialect, mlir::AsmParser::emitError(), get(), mlir::AsmParser::getCurrentLocation(), mlir::OperationName::Impl::name, and result.
Referenced by get(), get(), and loadOperation().
get() [2/3]
std::unique_ptr< DynamicOpDefinition > DynamicOpDefinition::get (StringRef name, ExtensibleDialect * dialect, OperationName::VerifyInvariantsFn && verifyFn, OperationName::VerifyRegionInvariantsFn && verifyRegionFn, OperationName::ParseAssemblyFn && parseFn, OperationName::PrintAssemblyFn && printFn) static
Definition at line 328 of file ExtensibleDialect.cpp.
References mlir::OperationName::Impl::dialect, get(), and mlir::OperationName::Impl::name.
get() [3/3]
std::unique_ptr< DynamicOpDefinition > DynamicOpDefinition::get (StringRef name, ExtensibleDialect * dialect, OperationName::VerifyInvariantsFn && verifyFn, OperationName::VerifyRegionInvariantsFn && verifyRegionFn, OperationName::ParseAssemblyFn && parseFn, OperationName::PrintAssemblyFn && printFn, OperationName::FoldHookFn && foldHookFn, GetCanonicalizationPatternsFn && getCanonicalizationPatternsFn, OperationName::PopulateDefaultAttrsFn && populateDefaultAttrsFn) static
Definition at line 351 of file ExtensibleDialect.cpp.
References mlir::OperationName::Impl::dialect, and mlir::OperationName::Impl::name.
getCanonicalizationPatterns()
void mlir::DynamicOpDefinition::getCanonicalizationPatterns (RewritePatternSet & set, MLIRContext * context) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 444 of file ExtensibleDialect.h.
Referenced by setGetCanonicalizationPatternsFn().
getInherentAttr()
std::optional< Attribute > mlir::DynamicOpDefinition::getInherentAttr (Operation * op, StringRef name) inline final virtual
Implementation for properties (unsupported right now here).
Implements mlir::OperationName::InterfaceConcept.
Definition at line 468 of file ExtensibleDialect.h.
References mlir::OperationName::Impl::name.
getOpPropertyByteSize()
int mlir::DynamicOpDefinition::getOpPropertyByteSize () inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 481 of file ExtensibleDialect.h.
getParseAssemblyFn()
OperationName::ParseAssemblyFn mlir::DynamicOpDefinition::getParseAssemblyFn () inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 449 of file ExtensibleDialect.h.
getPropertiesAsAttr()
Attribute mlir::DynamicOpDefinition::getPropertiesAsAttr (Operation * op) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 495 of file ExtensibleDialect.h.
getTypeID()
TypeID mlir::DynamicOpDefinition::getTypeID () inline
Returns the op typeID.
Definition at line 395 of file ExtensibleDialect.h.
References mlir::OperationName::Impl::typeID.
hashProperties()
llvm::hash_code mlir::DynamicOpDefinition::hashProperties (OpaqueProperties prop) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 498 of file ExtensibleDialect.h.
hasTrait()
bool mlir::DynamicOpDefinition::hasTrait (TypeID id) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 448 of file ExtensibleDialect.h.
initProperties()
void mlir::DynamicOpDefinition::initProperties (OperationName opName, OpaqueProperties storage, OpaqueProperties init) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 482 of file ExtensibleDialect.h.
populateDefaultAttrs()
void mlir::DynamicOpDefinition::populateDefaultAttrs (const OperationName & name, NamedAttrList & attrs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 454 of file ExtensibleDialect.h.
References mlir::OperationName::Impl::name.
Referenced by setPopulateDefaultAttrsFn().
populateDefaultProperties()
void mlir::DynamicOpDefinition::populateDefaultProperties (OperationName opName, OpaqueProperties properties) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 485 of file ExtensibleDialect.h.
populateInherentAttrs()
void mlir::DynamicOpDefinition::populateInherentAttrs (Operation * op, NamedAttrList & attrs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 475 of file ExtensibleDialect.h.
printAssembly()
void mlir::DynamicOpDefinition::printAssembly (Operation * op, OpAsmPrinter & printer, StringRef name) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 458 of file ExtensibleDialect.h.
References mlir::OperationName::Impl::name.
setFoldHookFn()
void mlir::DynamicOpDefinition::setFoldHookFn (OperationName::FoldHookFn && foldHook) inline
Sets the hook implementing a generalized folder for the op.
See RegisteredOperationName::foldHook for more details
Definition at line 423 of file ExtensibleDialect.h.
References foldHook().
setGetCanonicalizationPatternsFn()
void mlir::DynamicOpDefinition::setGetCanonicalizationPatternsFn (GetCanonicalizationPatternsFn && getCanonicalizationPatterns) inline
Set the hook returning any canonicalization pattern rewrites that the op supports, for use by the canonicalization pass.
Definition at line 429 of file ExtensibleDialect.h.
References getCanonicalizationPatterns().
setInherentAttr()
void mlir::DynamicOpDefinition::setInherentAttr (Operation * op, StringAttr name, Attribute value) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 472 of file ExtensibleDialect.h.
References mlir::OperationName::Impl::name.
setParseFn()
void mlir::DynamicOpDefinition::setParseFn (OperationName::ParseAssemblyFn && parse) inline
Sets the static hook for parsing this op assembly.
Definition at line 412 of file ExtensibleDialect.h.
setPopulateDefaultAttrsFn()
void mlir::DynamicOpDefinition::setPopulateDefaultAttrsFn (OperationName::PopulateDefaultAttrsFn && populateDefaultAttrs) inline
Set the hook populating default attributes.
Definition at line 435 of file ExtensibleDialect.h.
References populateDefaultAttrs().
setPrintFn()
void mlir::DynamicOpDefinition::setPrintFn (OperationName::PrintAssemblyFn && print) inline
Sets the static hook for printing this op assembly.
Definition at line 417 of file ExtensibleDialect.h.
References print().
setPropertiesFromAttr()
LogicalResult mlir::DynamicOpDefinition::setPropertiesFromAttr (OperationName opName, OpaqueProperties properties, Attribute attr, function_ref< InFlightDiagnostic()> emitError) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 489 of file ExtensibleDialect.h.
References mlir::emitError().
setVerifyFn()
void mlir::DynamicOpDefinition::setVerifyFn (OperationName::VerifyInvariantsFn && verify) inline
Sets the verifier function for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 400 of file ExtensibleDialect.h.
References mlir::verify().
setVerifyRegionFn()
void mlir::DynamicOpDefinition::setVerifyRegionFn (OperationName::VerifyRegionInvariantsFn && verify) inline
Sets the region verifier function for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 407 of file ExtensibleDialect.h.
References mlir::verify().
verifyInherentAttrs()
LogicalResult mlir::DynamicOpDefinition::verifyInherentAttrs (OperationName opName, NamedAttrList & attributes, function_ref< InFlightDiagnostic()> emitError) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 477 of file ExtensibleDialect.h.
References mlir::emitError(), and success().
verifyInvariants()
LogicalResult mlir::DynamicOpDefinition::verifyInvariants (Operation * op) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 462 of file ExtensibleDialect.h.
verifyRegionInvariants()
LogicalResult mlir::DynamicOpDefinition::verifyRegionInvariants (Operation * op) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 463 of file ExtensibleDialect.h.
The documentation for this class was generated from the following files:
include/mlir/IR/ExtensibleDialect.h
lib/IR/ExtensibleDialect.cpp