MLIR: mlir::OneToNTypeMapping Class Reference
mlir::OneToNTypeMapping Class Reference
Stores a 1:N mapping of types and provides several useful accessors.
#include "mlir/Transforms/OneToNTypeConversion.h"
Public Member Functions
OneToNTypeMapping (TypeRange originalTypes)
TypeRange getConvertedTypes (unsigned originalTypeNo) const
Returns the list of types that corresponds to the original type at the given index.
TypeRange getOriginalTypes () const
Returns the list of original types.
ValueRange getConvertedValues (ValueRange convertedValues, unsigned originalValueNo) const
Returns the slice of converted values that corresponds the original value at the given index.
void convertLocation (Value originalValue, unsigned originalValueNo, llvm::SmallVectorImpl< Location > &result) const
Fills the given result vector with as many copies of the location of the original value as the number of values it is converted to.
void convertLocations (ValueRange originalValues, llvm::SmallVectorImpl< Location > &result) const
Fills the given result vector with as many copies of the lociation of each original value as the number of values they are respectively converted to.
bool hasNonIdentityConversion () const
Returns true iff at least one type conversion maps an input type to a type that is different from itself.
Public Member Functions inherited from mlir::TypeConverter::SignatureConversion
SignatureConversion (unsigned numOrigInputs)
ArrayRef< Type > getConvertedTypes () const
Return the argument types for the new signature.
std::optional< InputMapping > getInputMapping (unsigned input) const
Get the input mapping for the given argument.
void addInputs (unsigned origInputNo, ArrayRef< Type > types)
Remap an input of the original signature with a new set of types.
void addInputs (ArrayRef< Type > types)
Append new input types to the signature conversion, this should only be used if the new types are not intended to remap an existing input.
void remapInput (unsigned origInputNo, Value replacement)
Remap an input of the original signature to another replacement value.
Detailed Description
Stores a 1:N mapping of types and provides several useful accessors.
This class extends SignatureConversion, which already supports 1:N type mappings but lacks some accessors into the mapping as well as access to the original types.
Definition at line 83 of file OneToNTypeConversion.h.
Constructor & Destructor Documentation
OneToNTypeMapping()
mlir::OneToNTypeMapping::OneToNTypeMapping (TypeRange originalTypes) inline
Definition at line 85 of file OneToNTypeConversion.h.
Member Function Documentation
convertLocation()
void OneToNTypeMapping::convertLocation (Value originalValue, unsigned originalValueNo, llvm::SmallVectorImpl< Location > & result) const
Fills the given result vector with as many copies of the location of the original value as the number of values it is converted to.
Definition at line 49 of file OneToNTypeConversion.cpp.
References mlir::Value::getLoc().
convertLocations()
void OneToNTypeMapping::convertLocations (ValueRange originalValues, llvm::SmallVectorImpl< Location > & result) const
Fills the given result vector with as many copies of the lociation of each original value as the number of values they are respectively converted to.
Definition at line 56 of file OneToNTypeConversion.cpp.
References mlir::detail::enumerate().
Referenced by mlir::OneToNPatternRewriter::applySignatureConversion().
getConvertedTypes()
TypeRange OneToNTypeMapping::getConvertedTypes (unsigned originalTypeNo) const
Returns the list of types that corresponds to the original type at the given index.
Definition at line 34 of file OneToNTypeConversion.cpp.
Referenced by mlir::OneToNPatternRewriter::applySignatureConversion(), and buildUnrealizedBackwardsCasts().
getConvertedValues()
ValueRange OneToNTypeMapping::getConvertedValues (ValueRange convertedValues, unsigned originalValueNo) const
Returns the slice of converted values that corresponds the original value at the given index.
Definition at line 42 of file OneToNTypeConversion.cpp.
Referenced by mlir::OneToNPatternRewriter::applySignatureConversion().
getOriginalTypes()
TypeRange mlir::OneToNTypeMapping::getOriginalTypes () const inline
Returns the list of original types.
Definition at line 96 of file OneToNTypeConversion.h.
Referenced by buildUnrealizedBackwardsCasts().
hasNonIdentityConversion()
bool OneToNTypeMapping::hasNonIdentityConversion () const
Returns true iff at least one type conversion maps an input type to a type that is different from itself.
Definition at line 67 of file OneToNTypeConversion.cpp.
References mlir::detail::enumerate(), and isIdentityConversion().
Referenced by ConvertTypesInSCFForOp::matchAndRewrite().
The documentation for this class was generated from the following files:
include/mlir/Transforms/OneToNTypeConversion.h
lib/Transforms/Utils/OneToNTypeConversion.cpp