MLIR: mlir::tracing::BreakpointManagerBase< Derived > Class Template Reference
mlir::tracing::BreakpointManagerBase< Derived > Class Template Reference
CRTP base class for BreakpointManager implementations.
#include "mlir/Debug/BreakpointManager.h"
Public Member Functions
BreakpointManagerBase ()
Public Member Functions inherited from mlir::tracing::BreakpointManager
virtual ~BreakpointManager ()=default
TypeID getTypeID () const
TypeID for the subclass, used for casting purpose.
virtual Breakpoint * match (const Action &action) const =0
Try to match a Breakpoint to a given Action.
Static Public Member Functions
static bool classof (const BreakpointManager *breakpointManager)
Provide classof to allow casting between breakpoint manager types.
Additional Inherited Members
Protected Member Functions inherited from mlir::tracing::BreakpointManager
BreakpointManager (TypeID typeID)
Protected Attributes inherited from mlir::tracing::BreakpointManager
TypeID typeID
Detailed Description
template<typename Derived>
class mlir::tracing::BreakpointManagerBase< Derived >
CRTP base class for BreakpointManager implementations.
Definition at line 82 of file BreakpointManager.h.
Constructor & Destructor Documentation
BreakpointManagerBase()
template<typename Derived> mlir::tracing::BreakpointManagerBase< Derived >::BreakpointManagerBase () inline
Definition at line 84 of file BreakpointManager.h.
References mlir::tracing::BreakpointManager::BreakpointManager(), and mlir::get().
Member Function Documentation
classof()
template<typename Derived> bool mlir::tracing::BreakpointManagerBase< Derived >::classof (const BreakpointManager * breakpointManager) inline static
Provide classof to allow casting between breakpoint manager types.
Definition at line 87 of file BreakpointManager.h.
References mlir::tracing::BreakpointManager::BreakpointManager(), mlir::TypeID::get(), and mlir::tracing::BreakpointManager::getTypeID().
The documentation for this class was generated from the following file:
include/mlir/Debug/BreakpointManager.h