MLIR: mlir::detail::DistinctAttributeUniquer Class Reference
mlir::detail::DistinctAttributeUniquer Class Reference
A specialized attribute uniquer for distinct attributes that always allocates since the distinct attribute instances use the address of their storage as unique identifier.
#include "IR/AttributeDetail.h"
Static Public Member Functions
template<typename T , typename... Args>
static T get (MLIRContext *context, Args &&...args)
Creates a distinct attribute storage.
Detailed Description
A specialized attribute uniquer for distinct attributes that always allocates since the distinct attribute instances use the address of their storage as unique identifier.
Definition at line 376 of file AttributeDetail.h.
Member Function Documentation
get()
template<typename T , typename... Args> static T mlir::detail::DistinctAttributeUniquer::get (MLIRContext * context, Args &&... args) inline static
Creates a distinct attribute storage.
Allocates every time since the address of the storage serves as unique identifier.
Definition at line 381 of file AttributeDetail.h.
References mlir::detail::StorageUserBase< DistinctAttr, Attribute, detail::DistinctAttrStorage, detail::DistinctAttributeUniquer >::getTypeID(), mlir::AttributeStorage::initializeAbstractAttribute(), and mlir::AbstractAttribute::lookup().
The documentation for this class was generated from the following files:
lib/IR/AttributeDetail.h
lib/IR/MLIRContext.cpp