MLIR: mlir::impl::LowerSparseOpsToForeachBase< DerivedT > Class Template Reference
mlir::impl::LowerSparseOpsToForeachBase< DerivedT > Class Template Reference
Public Types
using Base = LowerSparseOpsToForeachBase
Public Member Functions
LowerSparseOpsToForeachBase ()
LowerSparseOpsToForeachBase (const LowerSparseOpsToForeachBase &other)
LowerSparseOpsToForeachBase & operator= (const LowerSparseOpsToForeachBase &)=delete
LowerSparseOpsToForeachBase (LowerSparseOpsToForeachBase &&)=delete
LowerSparseOpsToForeachBase & operator= (LowerSparseOpsToForeachBase &&)=delete
~LowerSparseOpsToForeachBase ()=default
::llvm::StringRef getArgument () const override
Return the command line argument used when registering this pass.
::llvm::StringRef getDescription () const override
Return the command line description used when registering this pass.
::llvm::StringRef getName () const override
Returns the derived pass name.
std::unique_ptr<::mlir::Pass > clonePass () const override
A clone method to create a copy of this pass.
void getDependentDialects (::mlir::DialectRegistry &registry) const override
Return the dialect that must be loaded in the context before this pass.
LowerSparseOpsToForeachBase (LowerSparseOpsToForeachOptions options)
Explicitly declare the TypeID for this class.
Public Member Functions inherited from mlir::OperationPass< ModuleOp >
~OperationPass () override=default
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Static Public Member Functions
static constexpr ::llvm::StringLiteral getArgumentName ()
Returns the command-line argument attached to this pass.
static constexpr ::llvm::StringLiteral getPassName ()
Returns the derived pass name.
static bool classof (const ::mlir::Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Attributes
::mlir::Pass::Option< bool > enableRuntimeLibrary {*this, "enable-runtime-library", ::llvm::cl::desc(R"PO(Enable runtime library for manipulating sparse tensors)PO"), ::llvm::cl::init(true)}
::mlir::Pass::Option< bool > enableConvert {*this, "enable-convert", ::llvm::cl::desc(R"PO(Enable rewriting rules for the convert operator)PO"), ::llvm::cl::init(true)}
Additional Inherited Members
Protected Member Functions inherited from mlir::OperationPass< ModuleOp >
OperationPass (TypeID passID)
OperationPass & operator= (const OperationPass &)=delete
bool canScheduleOn (RegisteredOperationName opName) const final
Indicate if the current pass can be scheduled on the given operation type.
ModuleOp getOperation ()
Return the current operation being transformed.
AnalysisT & getAnalysis ()
Query an analysis for the current operation of the specific derived operation type.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
virtual bool canScheduleOn (Operation *op) const
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Static Protected Member Functions inherited from mlir::OperationPass< ModuleOp >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Detailed Description
template<typename DerivedT>
class mlir::impl::LowerSparseOpsToForeachBase< DerivedT >
Definition at line 167 of file SparseTensorPasses.cpp.
Member Typedef Documentation
Base
template<typename DerivedT> using mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::Base = LowerSparseOpsToForeachBase
Definition at line 169 of file SparseTensorPasses.cpp.
Constructor & Destructor Documentation
LowerSparseOpsToForeachBase() [1/4]
template<typename DerivedT> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::LowerSparseOpsToForeachBase () inline
Definition at line 171 of file SparseTensorPasses.cpp.
LowerSparseOpsToForeachBase() [2/4]
template<typename DerivedT> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::LowerSparseOpsToForeachBase (const LowerSparseOpsToForeachBase< DerivedT > & other) inline
Definition at line 172 of file SparseTensorPasses.cpp.
LowerSparseOpsToForeachBase() [3/4]
template<typename DerivedT> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::LowerSparseOpsToForeachBase (LowerSparseOpsToForeachBase< DerivedT > &&) delete
~LowerSparseOpsToForeachBase()
template<typename DerivedT> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::~LowerSparseOpsToForeachBase () default
References target.
LowerSparseOpsToForeachBase() [4/4]
template<typename DerivedT> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::LowerSparseOpsToForeachBase (LowerSparseOpsToForeachOptions options) inline
Explicitly declare the TypeID for this class.
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 218 of file SparseTensorPasses.cpp.
Member Function Documentation
classof()
template<typename DerivedT> bool mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::classof (const ::mlir::Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 193 of file SparseTensorPasses.cpp.
References getContext(), mlir::patterns, and mlir::Pass::runOnOperation().
clonePass()
template<typename DerivedT> std::unique_ptr<::mlir::Pass > mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::clonePass () const inline override virtual
A clone method to create a copy of this pass.
Implements mlir::Pass.
Definition at line 198 of file SparseTensorPasses.cpp.
References target.
getArgument()
template<typename DerivedT> ::llvm::StringRef mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 182 of file SparseTensorPasses.cpp.
References mlir::patterns.
getArgumentName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getArgumentName () inline static
Returns the command-line argument attached to this pass.
Definition at line 179 of file SparseTensorPasses.cpp.
References target.
getDependentDialects()
template<typename DerivedT> void mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getDependentDialects (::mlir::DialectRegistry & registry) const inline override
Return the dialect that must be loaded in the context before this pass.
Definition at line 203 of file SparseTensorPasses.cpp.
References target.
getDescription()
template<typename DerivedT> ::llvm::StringRef mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 184 of file SparseTensorPasses.cpp.
References mlir::OperationPass< ModuleOp >::getOperation(), mlir::patterns, mlir::Pass::signalPassFailure(), and target.
getName()
template<typename DerivedT> ::llvm::StringRef mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 190 of file SparseTensorPasses.cpp.
getPassName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::getPassName () inline static
Returns the derived pass name.
Definition at line 187 of file SparseTensorPasses.cpp.
operator=() [1/2]
template<typename DerivedT> LowerSparseOpsToForeachBase & mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::operator= (const LowerSparseOpsToForeachBase< DerivedT > &) delete
operator=() [2/2]
template<typename DerivedT> LowerSparseOpsToForeachBase & mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::operator= (LowerSparseOpsToForeachBase< DerivedT > &&) delete
Member Data Documentation
enableConvert
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::enableConvert {*this, "enable-convert", ::llvm::cl::desc(R"PO(Enable rewriting rules for the convert operator)PO"), ::llvm::cl::init(true)} protected
Definition at line 224 of file SparseTensorPasses.cpp.
enableRuntimeLibrary
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::impl::LowerSparseOpsToForeachBase< DerivedT >::enableRuntimeLibrary {*this, "enable-runtime-library", ::llvm::cl::desc(R"PO(Enable runtime library for manipulating sparse tensors)PO"), ::llvm::cl::init(true)} protected
Definition at line 223 of file SparseTensorPasses.cpp.
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/Transforms/SparseTensorPasses.cpp