MLIR: mlir::quant::AnyQuantizedType Class Reference
mlir::quant::AnyQuantizedType Class Reference
A quantized type that maps storage to/from expressed types in an unspecified way.
#include "mlir/Dialect/Quant/IR/QuantTypes.h"
Static Public Member Functions
static AnyQuantizedType get (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all parameters specified but not checked.
static AnyQuantizedType getChecked (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all specified parameters checked.
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Verifies construction invariants and issues errors/warnings.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
static ConcreteType get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteType getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "quant.any"
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
using Base
Utility declarations for the concrete attribute class.
using ImplType
using HasTraitFn
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
A quantized type that maps storage to/from expressed types in an unspecified way.
Typical syntax: quant.any<i8:f32> quant.any<i8> quant.any<i8<-16,15>>
Note that for the any type, the expressed type is optional.
Definition at line 201 of file QuantTypes.h.
Member Function Documentation
get()
AnyQuantizedType AnyQuantizedType::get (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all parameters specified but not checked.
Definition at line 242 of file QuantTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), and mlir::Type::getContext().
Referenced by mlirAnyQuantizedTypeGet().
getChecked()
AnyQuantizedType AnyQuantizedType::getChecked (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all specified parameters checked.
Returns a nullptr convertible type on failure.
Definition at line 251 of file QuantTypes.cpp.
References mlir::emitError(), mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getChecked(), and mlir::Type::getContext().
verifyInvariants()
LogicalResult AnyQuantizedType::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax) static
Verifies construction invariants and issues errors/warnings.
Definition at line 261 of file QuantTypes.cpp.
References mlir::emitError(), success(), and mlir::quant::QuantizedType::verifyInvariants().
Member Data Documentation
name
StringLiteral mlir::quant::AnyQuantizedType::name = "quant.any" static constexpr
Definition at line 208 of file QuantTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Quant/IR/QuantTypes.h
lib/Dialect/Quant/IR/QuantTypes.cpp