MLIR: mlir::dataflow::CFGEdge Class Reference
mlir::dataflow::CFGEdge Class Reference
This lattice anchor represents a control-flow edge between a block and one of its successors.
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
Public Member Functions
Block * getFrom () const
Get the block from which the edge originates.
Block * getTo () const
Get the target block.
void print (raw_ostream &os) const override
Print the blocks between the control-flow edge.
Location getLoc () const override
Get a fused location of both blocks.
Public Member Functions inherited from mlir::GenericLatticeAnchorBase< CFGEdge, std::pair< Block *, Block * > >
GenericLatticeAnchorBase (ValueT &&value)
Construct an instance of the lattice anchor using the provided value and the type ID of the concrete type.
bool operator== (const std::pair< Block *, Block * > &value) const
Two lattice anchors are equal if their values are equal.
const std::pair< Block *, Block * > & getValue () const
Get the contents of the lattice anchor.
Public Member Functions inherited from mlir::GenericLatticeAnchor
virtual ~GenericLatticeAnchor ()
TypeID getTypeID () const
Get the abstract lattice anchor's type identifier.
Additional Inherited Members
Public Types inherited from mlir::GenericLatticeAnchorBase< CFGEdge, std::pair< Block *, Block * > >
using KeyTy = std::pair< Block *, Block * >
The concrete key type used by the storage uniquer.
using Base = GenericLatticeAnchorBase< CFGEdge, std::pair< Block *, Block * > >
Alias for the base class.
Static Public Member Functions inherited from mlir::GenericLatticeAnchorBase< CFGEdge, std::pair< Block *, Block * > >
static CFGEdge * get (StorageUniquer &uniquer, Args &&...args)
Get a uniqued instance of this lattice anchor class with the given arguments.
static CFGEdge * construct (StorageUniquer::StorageAllocator &alloc, ValueT &&value)
Allocate space for a lattice anchor and construct it in-place.
static bool classof (const GenericLatticeAnchor *point)
Provide LLVM-style RTTI using type IDs.
Protected Member Functions inherited from mlir::GenericLatticeAnchor
GenericLatticeAnchor (TypeID typeID)
Create an abstract lattice anchor with type identifier.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
This lattice anchor represents a control-flow edge between a block and one of its successors.
Definition at line 145 of file DeadCodeAnalysis.h.
Member Function Documentation
getFrom()
Block* mlir::dataflow::CFGEdge::getFrom () const inline
Get the block from which the edge originates.
Definition at line 151 of file DeadCodeAnalysis.h.
References mlir::GenericLatticeAnchorBase< CFGEdge, std::pair< Block *, Block * > >::getValue().
Referenced by getLoc(), and print().
getLoc()
Location CFGEdge::getLoc () const override virtual
Get a fused location of both blocks.
Implements mlir::GenericLatticeAnchor.
Definition at line 107 of file DeadCodeAnalysis.cpp.
References mlir::get(), getContext(), getFrom(), mlir::Region::getLoc(), mlir::Block::getParent(), and getTo().
getTo()
Block* mlir::dataflow::CFGEdge::getTo () const inline
Get the target block.
Definition at line 153 of file DeadCodeAnalysis.h.
References mlir::GenericLatticeAnchorBase< CFGEdge, std::pair< Block *, Block * > >::getValue().
Referenced by getLoc(), and print().
print()
void CFGEdge::print (raw_ostream & os) const override virtual
Print the blocks between the control-flow edge.
Implements mlir::GenericLatticeAnchor.
Definition at line 113 of file DeadCodeAnalysis.cpp.
References getFrom(), getTo(), and mlir::Block::print().
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/DeadCodeAnalysis.h
lib/Analysis/DataFlow/DeadCodeAnalysis.cpp