MLIR: mlir::python::PyIntegerSet Class Reference
mlir::python::PyIntegerSet Class Reference
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyIntegerSet (PyMlirContextRef contextRef, MlirIntegerSet integerSet)
bool operator== (const PyIntegerSet &other)
operator MlirIntegerSet () const
MlirIntegerSet get () const
pybind11::object getCapsule ()
Gets a capsule wrapping the void* within the MlirIntegerSet.
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyIntegerSet createFromCapsule (pybind11::object capsule)
Creates a PyIntegerSet from the MlirAffineMap wrapped by a capsule.
Detailed Description
Definition at line 832 of file IRModule.h.
Constructor & Destructor Documentation
PyIntegerSet()
mlir::python::PyIntegerSet::PyIntegerSet (PyMlirContextRef contextRef, MlirIntegerSet integerSet) inline
Definition at line 834 of file IRModule.h.
References mlir::operator==().
Member Function Documentation
createFromCapsule()
PyIntegerSet PyIntegerSet::createFromCapsule (pybind11::object capsule) static
Creates a PyIntegerSet from the MlirAffineMap wrapped by a capsule.
Note that PyIntegerSet instances may be uniqued, so the returned object may be a pre-existing object. Integer sets are owned by the context.
Definition at line 417 of file IRAffine.cpp.
References mlir::python::PyAffineExpr::createFromCapsule(), mlir::python::PyAffineMap::createFromCapsule(), mlir::python::PyMlirContext::forContext(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::PyPrintAccumulator::getCallback(), mlir::python::PyAffineExpr::getCapsule(), mlir::python::PyAffineMap::getCapsule(), getCapsule(), mlir::PyPrintAccumulator::getUserData(), isPermutation(), mlir::PyPrintAccumulator::join(), kDumpDocstring, map(), maps, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirAffineExprDump(), mlirAffineExprPrint(), mlirAffineMapCompressUnusedSymbols(), mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapGet(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetSubMap(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapPrint(), mlirAffineMapReplace(), mlirIntegerSetDump(), mlirIntegerSetEmptyGet(), mlirIntegerSetGet(), mlirIntegerSetGetContext(), mlirIntegerSetGetNumDims(), mlirIntegerSetGetNumEqualities(), mlirIntegerSetGetNumInequalities(), mlirIntegerSetGetNumInputs(), mlirIntegerSetGetNumSymbols(), mlirIntegerSetIsCanonicalEmpty(), mlirIntegerSetIsNull(), mlirIntegerSetPrint(), mlirIntegerSetReplaceGet(), mlirPythonCapsuleToIntegerSet(), mlir::PyPrintAccumulator::parts, mlir::python::populateIRAffine(), and value.
get()
MlirIntegerSet mlir::python::PyIntegerSet::get () const inline
Definition at line 838 of file IRModule.h.
References mlir::python::populateIRAffine(), mlir::python::populateIRAttributes(), mlir::python::populateIRCore(), and mlir::python::populateIRTypes().
getCapsule()
py::object PyIntegerSet::getCapsule ()
Gets a capsule wrapping the void* within the MlirIntegerSet.
Definition at line 412 of file IRAffine.cpp.
References mlirPythonIntegerSetToCapsule().
Referenced by createFromCapsule().
operator MlirIntegerSet()
mlir::python::PyIntegerSet::operator MlirIntegerSet () const inline
Definition at line 837 of file IRModule.h.
operator==()
bool PyIntegerSet::operator== (const PyIntegerSet & other)
Definition at line 408 of file IRAffine.cpp.
References mlirIntegerSetEqual().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRAffine.cpp