MLIR: mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType > Class Template Reference
mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType > Class Template Reference
This class provides return value APIs for ops that are known to have a single result.
#include "mlir/IR/OpDefinition.h"
Public Member Functions
mlir::TypedValue< ResultType > getResult ()
operator mlir::TypedValue< ResultType > ()
If the operation returns a single value, then the Op can be implicitly converted to a Value.
ResultType getType ()
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, OneTypedResult< ResultType >::Impl >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ResultType>
template<typename ConcreteType>
class mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >
This class provides return value APIs for ops that are known to have a single result.
ResultType is the concrete type returned by getType().
Definition at line 702 of file OpDefinition.h.
Member Function Documentation
getResult()
template<typename ResultType > template<typename ConcreteType > mlir::TypedValue<ResultType> mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getResult () inline
Definition at line 705 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, OneTypedResult< ResultType >::Impl >::getOperation(), and mlir::Operation::getResult().
Referenced by mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getType(), and mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::operator mlir::TypedValue< ResultType >().
getType()
template<typename ResultType > template<typename ConcreteType > ResultType mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getType () inline
Definition at line 714 of file OpDefinition.h.
References mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getResult().
operator mlir::TypedValue< ResultType >()
template<typename ResultType > template<typename ConcreteType > mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::operator mlir::TypedValue< ResultType > () inline
If the operation returns a single value, then the Op can be implicitly converted to a Value.
This yields the value of the only result.
Definition at line 712 of file OpDefinition.h.
References mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getResult().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h