MLIR: mlir::python::adaptors::mlir_type_subclass Class Reference
mlir::python::adaptors::mlir_type_subclass Class Reference
Creates a custom subclass of mlir.ir.Type, implementing a casting constructor and type checking methods.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Types
using IsAFunctionTy = bool (*)(MlirType)
using GetTypeIDFunctionTy = MlirTypeID (*)()
Public Member Functions
mlir_type_subclass (py::handle scope, const char *typeClassName, IsAFunctionTy isaFunction, GetTypeIDFunctionTy getTypeIDFunction=nullptr)
Subclasses by looking up the super-class dynamically.
mlir_type_subclass (py::handle scope, const char *typeClassName, IsAFunctionTy isaFunction, const py::object &superCls, GetTypeIDFunctionTy getTypeIDFunction=nullptr)
Subclasses with a provided mlir.ir.Type super-class.
Public Member Functions inherited from mlir::python::adaptors::pure_subclass
pure_subclass (py::handle scope, const char *derivedClassName, const py::object &superClass)
template<typename Func, typename... Extra>
pure_subclass & def (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_property_readonly (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_staticmethod (const char *name, Func &&f, const Extra &...extra)
template<typename Func, typename... Extra>
pure_subclass & def_classmethod (const char *name, Func &&f, const Extra &...extra)
py::object get_class () const
Additional Inherited Members
Protected Attributes inherited from mlir::python::adaptors::pure_subclass
py::object superClass
py::object thisClass
Detailed Description
Creates a custom subclass of mlir.ir.Type, implementing a casting constructor and type checking methods.
Definition at line 479 of file PybindAdaptors.h.
Member Typedef Documentation
GetTypeIDFunctionTy
using mlir::python::adaptors::mlir_type_subclass::GetTypeIDFunctionTy = MlirTypeID (*)()
Definition at line 482 of file PybindAdaptors.h.
IsAFunctionTy
using mlir::python::adaptors::mlir_type_subclass::IsAFunctionTy = bool (*)(MlirType)
Definition at line 481 of file PybindAdaptors.h.
Constructor & Destructor Documentation
mlir_type_subclass() [1/2]
mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass (py::handle scope, const char * typeClassName, IsAFunctionTy isaFunction, GetTypeIDFunctionTy getTypeIDFunction = nullptr) inline
Subclasses by looking up the super-class dynamically.
Definition at line 485 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, and mlir_type_subclass().
Referenced by mlir_type_subclass().
mlir_type_subclass() [2/2]
mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass (py::handle scope, const char * typeClassName, IsAFunctionTy isaFunction, const py::object & superCls, GetTypeIDFunctionTy getTypeIDFunction = nullptr) inline
Subclasses with a provided mlir.ir.Type super-class.
This must be used if the subclass is being defined in the same extension module as the mlir.ir class (otherwise, it will trigger a recursive initialization).
Definition at line 497 of file PybindAdaptors.h.
References mlir::python::adaptors::pure_subclass::def(), mlir::python::adaptors::pure_subclass::def_staticmethod(), MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_TYPE_CASTER_REGISTER_ATTR, mlir::python::adaptors::pure_subclass::pure_subclass(), and mlir::python::adaptors::pure_subclass::thisClass.
The documentation for this class was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h