MLIR: mlir::StridedMetadataRange Class Reference
mlir::StridedMetadataRange Class Reference
A class that represents the strided metadata range information, including offsets, sizes, and strides as integer ranges.
#include "mlir/Interfaces/InferStridedMetadataInterface.h"
Public Member Functions
StridedMetadataRange ()=default
Default constructor creates uninitialized ranges.
bool isUninitialized () const
Returns whether the metadata is uninitialized.
ArrayRef< ConstantIntRanges > getOffsets () const
Get the offsets range.
MutableArrayRef< ConstantIntRanges > getOffsets ()
ArrayRef< ConstantIntRanges > getSizes () const
Get the sizes ranges.
MutableArrayRef< ConstantIntRanges > getSizes ()
ArrayRef< ConstantIntRanges > getStrides () const
Get the strides ranges.
MutableArrayRef< ConstantIntRanges > getStrides ()
bool operator== (const StridedMetadataRange &other) const
Compare two strided metadata ranges.
void print (raw_ostream &os) const
Print the strided metadata range.
Static Public Member Functions
static StridedMetadataRange getRanked (SmallVectorImpl< ConstantIntRanges > &&offsets, SmallVectorImpl< ConstantIntRanges > &&sizes, SmallVectorImpl< ConstantIntRanges > &&strides)
Returns a ranked strided metadata range.
static StridedMetadataRange getMaxRanges (int32_t indexBitwidth, int32_t offsetsRank, int32_t sizeRank, int32_t stridedRank)
Returns a strided metadata range with maximum ranges.
static StridedMetadataRange getMaxRanges (int32_t indexBitwidth, int32_t rank)
static StridedMetadataRange join (const StridedMetadataRange &lhs, const StridedMetadataRange &rhs)
Join two strided metadata ranges, by taking the element-wise union of the metadata.
Detailed Description
A class that represents the strided metadata range information, including offsets, sizes, and strides as integer ranges.
Definition at line 22 of file InferStridedMetadataInterface.h.
Constructor & Destructor Documentation
StridedMetadataRange()
mlir::StridedMetadataRange::StridedMetadataRange () default
Default constructor creates uninitialized ranges.
References StridedMetadataRange().
Referenced by getMaxRanges(), getMaxRanges(), getRanked(), join(), operator==(), and StridedMetadataRange().
Member Function Documentation
getMaxRanges() [1/2]
StridedMetadataRange mlir::StridedMetadataRange::getMaxRanges (int32_t indexBitwidth, int32_t offsetsRank, int32_t sizeRank, int32_t stridedRank) inline static
Returns a strided metadata range with maximum ranges.
Definition at line 37 of file InferStridedMetadataInterface.h.
References mlir::ConstantIntRanges::maxRange(), and StridedMetadataRange().
Referenced by getEntryStateImpl(), and getMaxRanges().
getMaxRanges() [2/2]
StridedMetadataRange mlir::StridedMetadataRange::getMaxRanges (int32_t indexBitwidth, int32_t rank) inline static
Definition at line 50 of file InferStridedMetadataInterface.h.
References getMaxRanges(), and StridedMetadataRange().
getOffsets() [1/2]
MutableArrayRef< ConstantIntRanges > mlir::StridedMetadataRange::getOffsets () inline
Definition at line 62 of file InferStridedMetadataInterface.h.
getOffsets() [2/2]
ArrayRef< ConstantIntRanges > mlir::StridedMetadataRange::getOffsets () const inline
Get the offsets range.
Definition at line 59 of file InferStridedMetadataInterface.h.
getRanked()
StridedMetadataRange mlir::StridedMetadataRange::getRanked (SmallVectorImpl< ConstantIntRanges > && offsets, SmallVectorImpl< ConstantIntRanges > && sizes, SmallVectorImpl< ConstantIntRanges > && strides) inline static
Returns a ranked strided metadata range.
Definition at line 29 of file InferStridedMetadataInterface.h.
References StridedMetadataRange().
getSizes() [1/2]
MutableArrayRef< ConstantIntRanges > mlir::StridedMetadataRange::getSizes () inline
Definition at line 68 of file InferStridedMetadataInterface.h.
getSizes() [2/2]
ArrayRef< ConstantIntRanges > mlir::StridedMetadataRange::getSizes () const inline
Get the sizes ranges.
Definition at line 67 of file InferStridedMetadataInterface.h.
getStrides() [1/2]
MutableArrayRef< ConstantIntRanges > mlir::StridedMetadataRange::getStrides () inline
Definition at line 72 of file InferStridedMetadataInterface.h.
getStrides() [2/2]
ArrayRef< ConstantIntRanges > mlir::StridedMetadataRange::getStrides () const inline
Get the strides ranges.
Definition at line 71 of file InferStridedMetadataInterface.h.
isUninitialized()
bool mlir::StridedMetadataRange::isUninitialized () const inline
Returns whether the metadata is uninitialized.
Definition at line 56 of file InferStridedMetadataInterface.h.
Referenced by print().
join()
StridedMetadataRange mlir::StridedMetadataRange::join (const StridedMetadataRange & lhs, const StridedMetadataRange & rhs) inline static
Join two strided metadata ranges, by taking the element-wise union of the metadata.
Definition at line 85 of file InferStridedMetadataInterface.h.
References lhs, rhs, and StridedMetadataRange().
operator==()
bool mlir::StridedMetadataRange::operator== (const StridedMetadataRange & other) const inline
Compare two strided metadata ranges.
Definition at line 75 of file InferStridedMetadataInterface.h.
References StridedMetadataRange().
print()
void StridedMetadataRange::print (raw_ostream & os) const
Print the strided metadata range.
Definition at line 18 of file InferStridedMetadataInterface.cpp.
References isUninitialized().
Referenced by mlir::operator<<().
The documentation for this class was generated from the following files:
include/mlir/Interfaces/InferStridedMetadataInterface.h
lib/Interfaces/InferStridedMetadataInterface.cpp