MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute Class Reference
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
intptr_t dunderLen () const
bool dunderContains (const std::string &name) const
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDictAttribute >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDictAttribute >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirAttributeIsADictionary
static constexpr const char * pyClassName = "DictAttr"
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name = mlirDictionaryAttrGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDictAttribute >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDictAttribute >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Detailed Description
Definition at line 526 of file IRAttributes.h.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::bindDerived (ClassTy & c) static
Definition at line 1173 of file IRAttributes.cpp.
References MlirNamedAttribute::attribute, dunderContains(), dunderLen(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirAttributeGetContext(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirIdentifierGet(), mlirIdentifierStr(), mlirNamedAttributeGet(), name, MlirNamedAttribute::name, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::PyAttribute(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
dunderContains()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::dunderContains (const std::string & name) const
Definition at line 1168 of file IRAttributes.cpp.
References mlirDictionaryAttrGetElementByName(), name, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef().
Referenced by bindDerived().
dunderLen()
intptr_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::dunderLen () const
Definition at line 1164 of file IRAttributes.cpp.
References mlirDictionaryAttrGetNumElements().
Referenced by bindDerived().
PyConcreteAttribute() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute () default
PyConcreteAttribute() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyAttribute & orig) inline
Definition at line 1085 of file IRCore.h.
PyConcreteAttribute() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr) inline
Definition at line 1083 of file IRCore.h.
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::getTypeIdFunction static constexpr
Initial value:
=
      mlirDictionaryAttrGetTypeID
Definition at line 532 of file IRAttributes.h.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::isaFunction = mlirAttributeIsADictionary static constexpr
Definition at line 529 of file IRAttributes.h.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::name = mlirDictionaryAttrGetName() inline static
Definition at line 534 of file IRAttributes.h.
Referenced by bindDerived(), and dunderContains().
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::pyClassName = "DictAttr" static constexpr
Definition at line 530 of file IRAttributes.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRAttributes.h
lib/Bindings/Python/IRAttributes.cpp