MLIR: mlir::ForwardDataFlowAnalysis< ValueT > Class Template Reference
mlir::ForwardDataFlowAnalysis< ValueT > Class Template Reference abstract
This class provides a general forward dataflow analyis driver utilizing the lattice classes defined above, to enable the easy definition of dataflow analysis algorithms.
#include "mlir/Analysis/DataFlowAnalysis.h"
Public Member Functions
ForwardDataFlowAnalysis (MLIRContext *context)
MLIRContext * getContext ()
Return the MLIR context used when constructing this analysis.
void run (Operation *topLevelOp)
Compute the analysis on operations rooted under the given top-level operation.
LatticeElement< ValueT > * lookupLatticeElement (Value value)
Return the lattice element attached to the given value, or nullptr if no lattice for the value has yet been created.
Public Member Functions inherited from mlir::detail::ForwardDataFlowAnalysisBase
virtual ~ForwardDataFlowAnalysisBase ()
void run (Operation *topLevelOp)
Initialize and compute the analysis on operations rooted under the given top-level operation.
AbstractLatticeElement & getLatticeElement (Value value)
Return the lattice element attached to the given value.
AbstractLatticeElement * lookupLatticeElement (Value value)
Return the lattice element attached to the given value, or nullptr if no lattice for the value has yet been created.
Protected Member Functions
LatticeElement< ValueT > & getLatticeElement (Value value)
Return the lattice element attached to the given value.
ChangeResult markAllPessimisticFixpoint (ValueRange values)
Mark all of the lattices for the given range of Values as having reached a pessimistic fixpoint.
virtual ChangeResult visitOperation (Operation *op, ArrayRef< LatticeElement< ValueT > *> operands)=0
Visit the given operation, and join any necessary analysis state into the lattices for the results and block arguments owned by this operation using the provided set of operand lattice elements (all pointer values are guaranteed to be non-null).
virtual LogicalResult getSuccessorsForOperands (BranchOpInterface branch, ArrayRef< LatticeElement< ValueT > *> operands, SmallVectorImpl< Block *> &successors)
Given a BranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), try to compute a specific set of successors that would be selected for the branch.
virtual void getSuccessorsForOperands (RegionBranchOpInterface branch, Optional< unsigned > sourceIndex, ArrayRef< LatticeElement< ValueT > *> operands, SmallVectorImpl< RegionSuccessor > &successors)
Given a RegionBranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), compute a specific set of region successors that would be selected.
Detailed Description
template<typename ValueT>
class mlir::ForwardDataFlowAnalysis< ValueT >
This class provides a general forward dataflow analyis driver utilizing the lattice classes defined above, to enable the easy definition of dataflow analysis algorithms.
More specically this driver is useful for defining analyses that are forward, sparse, pessimistic (except along unreached backedges) and context-insensitive for the interprocedural aspects.
Definition at line 275 of file DataFlowAnalysis.h.
Constructor & Destructor Documentation
ForwardDataFlowAnalysis()
template<typename ValueT > mlir::ForwardDataFlowAnalysis< ValueT >::ForwardDataFlowAnalysis (MLIRContext * context) inline
Definition at line 277 of file DataFlowAnalysis.h.
Member Function Documentation
getContext()
template<typename ValueT > MLIRContext* mlir::ForwardDataFlowAnalysis< ValueT >::getContext () inline
Return the MLIR context used when constructing this analysis.
Definition at line 280 of file DataFlowAnalysis.h.
getLatticeElement()
template<typename ValueT > LatticeElement<ValueT>& mlir::ForwardDataFlowAnalysis< ValueT >::getLatticeElement (Value value) inline protected
Return the lattice element attached to the given value.
If a lattice has not been added for the given value, a new 'uninitialized' value is inserted and returned.
Definition at line 299 of file DataFlowAnalysis.h.
References mlir::detail::ForwardDataFlowAnalysisBase::getLatticeElement().
getSuccessorsForOperands() [1/2]
template<typename ValueT > virtual LogicalResult mlir::ForwardDataFlowAnalysis< ValueT >::getSuccessorsForOperands (BranchOpInterface branch, ArrayRef< LatticeElement< ValueT > *> operands, SmallVectorImpl< Block *> & successors) inline protected virtual
Given a BranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), try to compute a specific set of successors that would be selected for the branch.
Returns failure if not computable, or if all of the successors would be chosen. If a subset of successors can be selected, successors is populated.
Definition at line 331 of file DataFlowAnalysis.h.
References mlir::failure().
getSuccessorsForOperands() [2/2]
template<typename ValueT > virtual void mlir::ForwardDataFlowAnalysis< ValueT >::getSuccessorsForOperands (RegionBranchOpInterface branch, Optional< unsigned > sourceIndex, ArrayRef< LatticeElement< ValueT > *> operands, SmallVectorImpl< RegionSuccessor > & successors) inline protected virtual
Given a RegionBranchOpInterface, and the current lattice elements that correspond to the branch operands (all pointer values are guaranteed to be non-null), compute a specific set of region successors that would be selected.
Definition at line 342 of file DataFlowAnalysis.h.
References value.
lookupLatticeElement()
template<typename ValueT > LatticeElement<ValueT>* mlir::ForwardDataFlowAnalysis< ValueT >::lookupLatticeElement (Value value) inline
Return the lattice element attached to the given value, or nullptr if no lattice for the value has yet been created.
Definition at line 290 of file DataFlowAnalysis.h.
References mlir::detail::ForwardDataFlowAnalysisBase::lookupLatticeElement().
markAllPessimisticFixpoint()
template<typename ValueT > ChangeResult mlir::ForwardDataFlowAnalysis< ValueT >::markAllPessimisticFixpoint (ValueRange values) inline protected
Mark all of the lattices for the given range of Values as having reached a pessimistic fixpoint.
Definition at line 306 of file DataFlowAnalysis.h.
References mlir::NoChange, op, and value.
run()
template<typename ValueT > void mlir::ForwardDataFlowAnalysis< ValueT >::run (Operation * topLevelOp) inline
Compute the analysis on operations rooted under the given top-level operation.
Note that the top-level operation is not visited.
Definition at line 284 of file DataFlowAnalysis.h.
References mlir::detail::ForwardDataFlowAnalysisBase::run().
visitOperation()
template<typename ValueT > virtual ChangeResult mlir::ForwardDataFlowAnalysis< ValueT >::visitOperation (Operation * op, ArrayRef< LatticeElement< ValueT > *> operands) protected pure virtual
Visit the given operation, and join any necessary analysis state into the lattices for the results and block arguments owned by this operation using the provided set of operand lattice elements (all pointer values are guaranteed to be non-null).
Returns if any result or block argument value lattices changed during the visit. The lattice for a result or block argument value can be obtained by using getLatticeElement.
The documentation for this class was generated from the following file:
include/mlir/Analysis/DataFlowAnalysis.h