MLIR: mlir::pdll::ast::Decl Class Reference
mlir::pdll::ast::Decl Class Reference
This class represents the base Decl node.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
const Name * getName () const
Return the name of the decl, or nullptr if it doesn't have one.
void setDocComment (Context &ctx, StringRef comment)
Set the documentation comment for this decl.
std::optional< StringRef > getDocComment () const
Return the documentation comment attached to this decl if it has been set.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
void walk (function_ref< void(const Node *)> walkFn) const
Walk all of the nodes including, and nested under, this node in pre-order.
template<typename WalkFnT , typename ArgT = typename llvm::function_traits< WalkFnT>::template arg_t<0>>
std::enable_if_t<!std::is_convertible< const Node *, ArgT >::value > walk (WalkFnT &&walkFn) const
Static Public Member Functions
static bool classof (const Node *node)
Provide type casting support.
Protected Member Functions
Decl (TypeID typeID, SMRange loc, const Name *name=nullptr)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, SMRange loc)
Detailed Description
This class represents the base Decl node.
Definition at line 669 of file Nodes.h.
Constructor & Destructor Documentation
Decl()
mlir::pdll::ast::Decl::Decl (TypeID typeID, SMRange loc, const Name * name = nullptr) inline protected
Definition at line 685 of file Nodes.h.
Member Function Documentation
classof()
bool mlir::pdll::ast::Decl::classof (const Node * node) inline static
Provide type casting support.
Definition at line 1324 of file Nodes.h.
getDocComment()
std::optional<StringRef> mlir::pdll::ast::Decl::getDocComment () const inline
Return the documentation comment attached to this decl if it has been set.
Otherwise, returns std::nullopt.
Definition at line 682 of file Nodes.h.
Referenced by getDocumentationFor().
getName()
const Name* mlir::pdll::ast::Decl::getName () const inline
Return the name of the decl, or nullptr if it doesn't have one.
Definition at line 672 of file Nodes.h.
Referenced by mlir::pdll::ast::DeclScope::add(), mlir::pdll::ast::UserConstraintDecl::getName(), mlir::pdll::ast::NamedAttributeDecl::getName(), mlir::pdll::ast::OpNameDecl::getName(), mlir::pdll::ast::UserRewriteDecl::getName(), and mlir::pdll::ast::VariableDecl::getName().
setDocComment()
void Decl::setDocComment (Context & ctx, StringRef comment)
Set the documentation comment for this decl.
Definition at line 377 of file Nodes.cpp.
References mlir::pdll::ast::Context::getAllocator().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp