MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc Class Reference
#include "mlir/Bindings/Python/Globals.h"
Public Types
enum class OnExplicitAction : uint8_t { UseExplicit , UseTraceback }
Policy for handling explicit loc= when loc_tracebacks() is active.
enum class CurrentLocAction : uint8_t { Fallback , NamelocWrap }
Policy for composing Location.current with the computed location.
Public Member Functions
bool locTracebacksEnabled ()
void setLocTracebacksEnabled (bool value)
size_t locTracebackFramesLimit ()
void setLocTracebackFramesLimit (size_t value)
void registerTracebackFileInclusion (const std::string &file)
void registerTracebackFileExclusion (const std::string &file)
bool isUserTracebackFilename (std::string_view file)
OnExplicitAction tracebackActionOnExplicitLoc ()
void setTracebackActionOnExplicitLoc (OnExplicitAction action)
CurrentLocAction tracebackActionOnCurrentLoc ()
void setTracebackActionOnCurrentLoc (CurrentLocAction action)
Static Public Attributes
static constexpr size_t kMaxFrames = 512
Detailed Description
Definition at line 130 of file Globals.h.
Member Enumeration Documentation
CurrentLocAction
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::CurrentLocAction : uint8_t strong
Policy for composing Location.current with the computed location.
TODO: possibly add CallSiteLoc wrap and a generic Fuse option (fused[Location.current, baseLoc]) for non-NameLoc cases.
Enumerator
Fallback
NamelocWrap
Definition at line 141 of file Globals.h.
OnExplicitAction
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::OnExplicitAction : uint8_t strong
Policy for handling explicit loc= when loc_tracebacks() is active.
Enumerator
UseExplicit
UseTraceback
Definition at line 133 of file Globals.h.
Member Function Documentation
isUserTracebackFilename()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::isUserTracebackFilename (std::string_view file)
Definition at line 336 of file Globals.cpp.
locTracebackFramesLimit()
size_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::locTracebackFramesLimit ()
Definition at line 278 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
locTracebacksEnabled()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::locTracebacksEnabled ()
Definition at line 268 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
registerTracebackFileExclusion()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::registerTracebackFileExclusion (const std::string & file)
Definition at line 324 of file Globals.cpp.
References escapeRegex().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
registerTracebackFileInclusion()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::registerTracebackFileInclusion (const std::string & file)
Definition at line 312 of file Globals.cpp.
References escapeRegex().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
setLocTracebackFramesLimit()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setLocTracebackFramesLimit (size_t value)
Definition at line 283 of file Globals.cpp.
References kMaxFrames.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
setLocTracebacksEnabled()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setLocTracebacksEnabled (bool value)
Definition at line 273 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
setTracebackActionOnCurrentLoc()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setTracebackActionOnCurrentLoc (CurrentLocAction action)
Definition at line 306 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
setTracebackActionOnExplicitLoc()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setTracebackActionOnExplicitLoc (OnExplicitAction action)
Definition at line 294 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
tracebackActionOnCurrentLoc()
PyGlobals::TracebackLoc::CurrentLocAction mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::tracebackActionOnCurrentLoc ()
Definition at line 301 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
tracebackActionOnExplicitLoc()
PyGlobals::TracebackLoc::OnExplicitAction mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::tracebackActionOnExplicitLoc ()
Definition at line 289 of file Globals.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot().
Member Data Documentation
kMaxFrames
size_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::kMaxFrames = 512 static constexpr
Definition at line 168 of file Globals.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot(), and setLocTracebackFramesLimit().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/Globals.h
lib/Bindings/Python/Globals.cpp