MLIR: mlir::LLVM::detail::DebugImporter Class Reference
mlir::LLVM::detail::DebugImporter Class Reference
#include "Target/LLVMIR/DebugImporter.h"
Public Member Functions
DebugImporter (ModuleOp mlirModule, bool dropDICompositeTypeElements)
Location translateLoc (llvm::DILocation *loc)
Translates the given LLVM debug location to an MLIR location.
DIExpressionAttr translateExpression (llvm::DIExpression *node)
Translates the LLVM DWARF expression metadata to MLIR.
DIGlobalVariableExpressionAttr translateGlobalVariableExpression (llvm::DIGlobalVariableExpression *node)
Translates the LLVM DWARF global variable expression metadata to MLIR.
Location translateFuncLocation (llvm::Function *func)
Translates the debug information for the given function into a Location.
DINodeAttr translate (llvm::DINode *node)
Translates the given LLVM debug metadata to MLIR.
template<typename DINodeT>
auto translate (DINodeT *node)
Infers the metadata type and translates it to MLIR.
Detailed Description
Definition at line 32 of file DebugImporter.h.
Constructor & Destructor Documentation
DebugImporter()
DebugImporter::DebugImporter (ModuleOp mlirModule, bool dropDICompositeTypeElements)
Definition at line 25 of file DebugImporter.cpp.
Member Function Documentation
translate() [1/2]
template<typename DINodeT> auto mlir::LLVM::detail::DebugImporter::translate (DINodeT * node) inline
Infers the metadata type and translates it to MLIR.
Definition at line 55 of file DebugImporter.h.
References translate().
translate() [2/2]
DINodeAttr DebugImporter::translate (llvm::DINode * node)
Translates the given LLVM debug metadata to MLIR.
Definition at line 360 of file DebugImporter.cpp.
References result.
Referenced by translate(), translateFuncLocation(), translateGlobalVariableExpression(), and translateLoc().
translateExpression()
DIExpressionAttr DebugImporter::translateExpression (llvm::DIExpression * node)
Translates the LLVM DWARF expression metadata to MLIR.
Definition at line 481 of file DebugImporter.cpp.
Referenced by translateGlobalVariableExpression().
translateFuncLocation()
Location DebugImporter::translateFuncLocation (llvm::Function * func)
Translates the debug information for the given function into a Location.
Returns UnknownLoc if func has no debug information attached to it.
Definition at line 31 of file DebugImporter.cpp.
References mlir::FileLineColLoc::get(), and translate().
translateGlobalVariableExpression()
DIGlobalVariableExpressionAttr DebugImporter::translateGlobalVariableExpression (llvm::DIGlobalVariableExpression * node)
Translates the LLVM DWARF global variable expression metadata to MLIR.
Definition at line 499 of file DebugImporter.cpp.
References translate(), and translateExpression().
translateLoc()
Location DebugImporter::translateLoc (llvm::DILocation * loc)
Translates the given LLVM debug location to an MLIR location.
Definition at line 461 of file DebugImporter.cpp.
References mlir::FileLineColLoc::get(), result, translate(), and translateLoc().
Referenced by translateLoc().
The documentation for this class was generated from the following files:
lib/Target/LLVMIR/DebugImporter.h
lib/Target/LLVMIR/DebugImporter.cpp