MLIR: mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT > Class Template Reference
mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT > Class Template Reference
Public Types
using Base = XeGPUPropagateLayoutBase
Public Member Functions
XeGPUPropagateLayoutBase ()
XeGPUPropagateLayoutBase (const XeGPUPropagateLayoutBase &other)
XeGPUPropagateLayoutBase & operator= (const XeGPUPropagateLayoutBase &)=delete
XeGPUPropagateLayoutBase (XeGPUPropagateLayoutBase &&)=delete
XeGPUPropagateLayoutBase & operator= (XeGPUPropagateLayoutBase &&)=delete
~XeGPUPropagateLayoutBase ()=default
::llvm::StringRef getArgument () const override
Return the command line argument used when registering this pass.
::llvm::StringRef getDescription () const override
Return the command line description used when registering this pass.
::llvm::StringRef getName () const override
Returns the derived pass name.
std::unique_ptr<::mlir::Pass > clonePass () const override
A clone method to create a copy of this pass.
void getDependentDialects (::mlir::DialectRegistry &registry) const override
Return the dialect that must be loaded in the context before this pass.
XeGPUPropagateLayoutBase (XeGPUPropagateLayoutOptions options)
Explicitly declare the TypeID for this class.
Public Member Functions inherited from mlir::OperationPass< OpT >
~OperationPass () override=default
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
TypeID getTypeID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass, or null if unknown.
virtual void getDependentDialects (DialectRegistry &registry) const
Register dependent dialects for the current pass.
std::optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or std::nullopt if this is a generic OperationPass.
virtual LogicalResult initializeOptions (StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
const Pass * getThreadingSibling () const
Returns the thread sibling of this pass.
const Pass * getThreadingSiblingOrThis () const
Returns the thread sibling of this pass, or the pass itself it has no sibling.
Static Public Member Functions
static constexpr ::llvm::StringLiteral getArgumentName ()
Returns the command-line argument attached to this pass.
static constexpr ::llvm::StringLiteral getPassName ()
Returns the derived pass name.
static bool classof (const ::mlir::Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Protected Attributes
::mlir::Pass::Option< bool > printOnly {*this, "print-analysis-only", ::llvm::cl::desc(R"PO(Print the result of layout propagation analysis and exit.)PO"), ::llvm::cl::init(false)}
::mlir::Pass::Option< std::string > layoutKind {*this, "layout-kind", ::llvm::cl::desc(R"PO(Propagate `inst` / `lane` level of xegpu layouts.)PO"), ::llvm::cl::init("lane")}
Friends
std::unique_ptr<::mlir::Pass > createXeGPUPropagateLayout ()
std::unique_ptr<::mlir::Pass > createXeGPUPropagateLayout (XeGPUPropagateLayoutOptions options)
Additional Inherited Members
Protected Member Functions inherited from mlir::OperationPass< OpT >
OperationPass (TypeID passID)
OperationPass (const OperationPass &)=default
OperationPass & operator= (const OperationPass &)=delete
OperationPass (OperationPass &&)=delete
OperationPass & operator= (OperationPass &&)=delete
bool canScheduleOn (RegisteredOperationName opName) const final
Indicate if the current pass can be scheduled on the given operation type.
OpT getOperation ()
Return the current operation being transformed.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current operation of the specific derived operation type.
Protected Member Functions inherited from mlir::Pass
Pass (TypeID passID, std::optional< StringRef > opName=std::nullopt)
Pass (const Pass &other)
Pass & operator= (const Pass &)=delete
Pass (Pass &&)=delete
Pass & operator= (Pass &&)=delete
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current operation being transformed.
virtual void runOnOperation ()=0
The polymorphic API that runs the pass over the currently held operation.
virtual LogicalResult initialize (MLIRContext *context)
Initialize any complex state necessary for running this pass.
virtual bool canScheduleOn (Operation *op) const
LogicalResult runPipeline (OpPassManager &pipeline, Operation *op)
Schedule an arbitrary pass pipeline on the provided operation.
std::unique_ptr< Pass > clone () const
A clone method to create a copy of this pass.
Operation * getOperation ()
Return the current operation being transformed.
void signalPassFailure ()
Signal that some invariant was broken when running.
template<typename AnalysisT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
template<typename AnalysisT, typename OpT>
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit of a specific derived operation type.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
template<typename... AnalysesT>
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (TypeID id)
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the given parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Returns the analysis for the parent operation if it exists.
template<typename AnalysisT>
std::optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
template<typename AnalysisT>
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
template<typename AnalysisT, typename OpTy>
AnalysisT & getChildAnalysis (OpTy child)
Returns the analysis for the given child operation of specific derived operation type, or creates it if it doesn't exist.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Static Protected Member Functions inherited from mlir::OperationPass< OpT >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Detailed Description
template<typename DerivedT>
class mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >
Definition at line 271 of file XeGPUPropagateLayout.cpp.
Member Typedef Documentation
Base
template<typename DerivedT> using mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::Base = XeGPUPropagateLayoutBase
Definition at line 273 of file XeGPUPropagateLayout.cpp.
Constructor & Destructor Documentation
XeGPUPropagateLayoutBase() [1/4]
template<typename DerivedT> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::XeGPUPropagateLayoutBase () inline
Definition at line 275 of file XeGPUPropagateLayout.cpp.
XeGPUPropagateLayoutBase() [2/4]
template<typename DerivedT> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::XeGPUPropagateLayoutBase (const XeGPUPropagateLayoutBase< DerivedT > & other) inline
Definition at line 276 of file XeGPUPropagateLayout.cpp.
XeGPUPropagateLayoutBase() [3/4]
template<typename DerivedT> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::XeGPUPropagateLayoutBase (XeGPUPropagateLayoutBase< DerivedT > &&) delete
~XeGPUPropagateLayoutBase()
template<typename DerivedT> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::~XeGPUPropagateLayoutBase () default
XeGPUPropagateLayoutBase() [4/4]
template<typename DerivedT> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::XeGPUPropagateLayoutBase (XeGPUPropagateLayoutOptions options) inline
Explicitly declare the TypeID for this class.
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 318 of file XeGPUPropagateLayout.cpp.
References mlir::Type::getIntOrFloatBitWidth().
Member Function Documentation
classof()
template<typename DerivedT> bool mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::classof (const ::mlir::Pass * pass) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 297 of file XeGPUPropagateLayout.cpp.
clonePass()
template<typename DerivedT> std::unique_ptr<::mlir::Pass > mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::clonePass () const inline override virtual
A clone method to create a copy of this pass.
Implements mlir::Pass.
Definition at line 302 of file XeGPUPropagateLayout.cpp.
getArgument()
template<typename DerivedT> ::llvm::StringRef mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::getArgument () const inline override virtual
Return the command line argument used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 286 of file XeGPUPropagateLayout.cpp.
getArgumentName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::getArgumentName () inline static
Returns the command-line argument attached to this pass.
Definition at line 283 of file XeGPUPropagateLayout.cpp.
getDependentDialects()
template<typename DerivedT> void mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::getDependentDialects (::mlir::DialectRegistry & registry) const inline override
Return the dialect that must be loaded in the context before this pass.
Definition at line 307 of file XeGPUPropagateLayout.cpp.
References mlir::Type::getIntOrFloatBitWidth(), and mlir::Type::isIntOrFloat().
getDescription()
template<typename DerivedT> ::llvm::StringRef mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::getDescription () const inline override virtual
Return the command line description used when registering this pass.
Return an empty string if one does not exist.
Reimplemented from mlir::Pass.
Definition at line 288 of file XeGPUPropagateLayout.cpp.
getName()
template<typename DerivedT> ::llvm::StringRef mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::getName () const inline override virtual
Returns the derived pass name.
Implements mlir::Pass.
Definition at line 294 of file XeGPUPropagateLayout.cpp.
getPassName()
template<typename DerivedT> constexpr ::llvm::StringLiteral mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::getPassName () inline static
Returns the derived pass name.
Definition at line 291 of file XeGPUPropagateLayout.cpp.
operator=() [1/2]
template<typename DerivedT> XeGPUPropagateLayoutBase & mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::operator= (const XeGPUPropagateLayoutBase< DerivedT > &) delete
operator=() [2/2]
template<typename DerivedT> XeGPUPropagateLayoutBase & mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::operator= (XeGPUPropagateLayoutBase< DerivedT > &&) delete
Friends And Related Symbol Documentation
createXeGPUPropagateLayout [1/2]
template<typename DerivedT> std::unique_ptr<::mlir::Pass > createXeGPUPropagateLayout () friend
Definition at line 327 of file XeGPUPropagateLayout.cpp.
createXeGPUPropagateLayout [2/2]
template<typename DerivedT> std::unique_ptr<::mlir::Pass > createXeGPUPropagateLayout (XeGPUPropagateLayoutOptions options) friend
Definition at line 331 of file XeGPUPropagateLayout.cpp.
Member Data Documentation
layoutKind
template<typename DerivedT> ::mlir::Pass::Option<std::string> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::layoutKind {*this, "layout-kind", ::llvm::cl::desc(R"PO(Propagate `inst` / `lane` level of xegpu layouts.)PO"), ::llvm::cl::init("lane")} protected
Definition at line 324 of file XeGPUPropagateLayout.cpp.
printOnly
template<typename DerivedT> ::mlir::Pass::Option<bool> mlir::xegpu::impl::XeGPUPropagateLayoutBase< DerivedT >::printOnly {*this, "print-analysis-only", ::llvm::cl::desc(R"PO(Print the result of layout propagation analysis and exit.)PO"), ::llvm::cl::init(false)} protected
Definition at line 323 of file XeGPUPropagateLayout.cpp.
The documentation for this class was generated from the following file:
lib/Dialect/XeGPU/Transforms/XeGPUPropagateLayout.cpp