MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic Class Reference
Python class mirroring the C MlirDiagnostic struct.
#include "mlir/Bindings/Python/IRCore.h"
Classes
struct DiagnosticInfo
Materialized diagnostic information.
Public Member Functions
PyDiagnostic (MlirDiagnostic diagnostic)
void invalidate ()
bool isValid ()
PyDiagnosticSeverity getSeverity ()
nanobind::typed< nanobind::object, PyLocation > getLocation ()
nanobind::str getMessage ()
nanobind::typed< nanobind::tuple, PyDiagnostic > getNotes ()
DiagnosticInfo getInfo ()
Detailed Description
Python class mirroring the C MlirDiagnostic struct.
Note that these structs are only valid for the duration of a diagnostic callback and attempting to access them outside of that will raise an exception. This applies to nested diagnostics (in the notes) as well.
Definition at line 372 of file IRCore.h.
Constructor & Destructor Documentation
PyDiagnostic()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::PyDiagnostic (MlirDiagnostic diagnostic) inline
Definition at line 374 of file IRCore.h.
Referenced by invalidate().
Member Function Documentation
getInfo()
PyDiagnostic::DiagnosticInfo mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getInfo ()
Definition at line 783 of file IRCore.cpp.
getLocation()
nb::typed< nb::object, PyLocation > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getLocation ()
Definition at line 752 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getMessage()
nb::str mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getMessage ()
Definition at line 759 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getNotes()
nb::typed< nb::tuple, PyDiagnostic > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getNotes ()
Definition at line 767 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
getSeverity()
PyDiagnosticSeverity mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getSeverity ()
Definition at line 746 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
invalidate()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::invalidate ()
Definition at line 712 of file IRCore.cpp.
References PyDiagnostic().
isValid()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::isValid () inline
Definition at line 376 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp