MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator Class Reference
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
PyOpOperandIterator (MlirOpOperand opOperand)
PyOpOperandIterator & dunderIter ()
nanobind::typed< nanobind::object, PyOpOperand > dunderNext ()
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 1627 of file IRCore.h.
Constructor & Destructor Documentation
PyOpOperandIterator()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator::PyOpOperandIterator (MlirOpOperand opOperand) inline
Definition at line 1629 of file IRCore.h.
Referenced by dunderIter().
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator::bind (nanobind::module_ & m) static
Definition at line 394 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderIter()
PyOpOperandIterator & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator::dunderIter () inline
Definition at line 1631 of file IRCore.h.
References PyOpOperandIterator().
dunderNext()
nb::typed< nb::object, PyOpOperand > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator::dunderNext ()
Definition at line 382 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::getOperandNumber().
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp