MLIR: mlir::python::PyInferShapedTypeOpInterface Class Reference
mlir::python::PyInferShapedTypeOpInterface Class Reference
Python wrapper for InferShapedTypeOpInterface.
Classes
struct AppendResultsCallbackData
C-style user-data structure for type appending callback.
Public Member Functions
std::vector< PyShapedTypeComponents > inferReturnTypeComponents (std::optional< nb::list > operandList, std::optional< PyAttribute > attributes, void *properties, std::optional< std::vector< PyRegion >> regions, DefaultingPyMlirContext context, DefaultingPyLocation location)
Given the arguments required to build an operation, attempts to infer the shaped type components.
Public Member Functions inherited from mlir::python::PyConcreteOpInterface< PyInferShapedTypeOpInterface >
PyConcreteOpInterface (nb::object object, DefaultingPyMlirContext context)
Constructs an interface instance from an object that is either an operation or a subclass of OpView.
bool isStatic ()
Returns true if this object was constructed from a subclass of OpView rather than from an operation instance.
nb::object getOperationObject ()
Returns the operation instance from which this object was constructed.
nb::object getOpView ()
Returns the opview of the operation instance from which this object was constructed.
const std::string & getOpName ()
Returns the canonical name of the operation this interface is constructed from.
Static Public Member Functions
static void appendResultsCallback (bool hasRank, intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute attribute, void *userData)
Appends the shaped type components provided as unpacked shape, element type, attribute to the user-data.
static void bindDerived (ClassTy &cls)
Static Public Member Functions inherited from mlir::python::PyConcreteOpInterface< PyInferShapedTypeOpInterface >
static void bind (nb::module_ &m)
Creates the Python bindings for this class in the given module.
static void bindDerived (ClassTy &cls)
Hook for derived classes to add class-specific bindings.
Static Public Attributes
constexpr static const char * pyClassName = "InferShapedTypeOpInterface"
constexpr static GetTypeIDFunctionTy getInterfaceID
Additional Inherited Members
Protected Types inherited from mlir::python::PyConcreteOpInterface< PyInferShapedTypeOpInterface >
using ClassTy = nb::class_< PyInferShapedTypeOpInterface >
using GetTypeIDFunctionTy = MlirTypeID(*)()
Detailed Description
Python wrapper for InferShapedTypeOpInterface.
This interface has only static methods.
Definition at line 399 of file IRInterfaces.cpp.
Member Function Documentation
appendResultsCallback()
static void mlir::python::PyInferShapedTypeOpInterface::appendResultsCallback (bool hasRank, intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute attribute, void * userData) inline static
Appends the shaped type components provided as unpacked shape, element type, attribute to the user-data.
Definition at line 416 of file IRInterfaces.cpp.
References mlir::python::PyInferShapedTypeOpInterface::AppendResultsCallbackData::inferredShapedTypeComponents.
Referenced by inferReturnTypeComponents().
bindDerived()
static void mlir::python::PyInferShapedTypeOpInterface::bindDerived (ClassTy & cls) inline static
Definition at line 463 of file IRInterfaces.cpp.
References inferReturnTypeComponents(), and mlir::python::inferReturnTypeComponentsDoc.
inferReturnTypeComponents()
std::vector<PyShapedTypeComponents> mlir::python::PyInferShapedTypeOpInterface::inferReturnTypeComponents (std::optional< nb::list > operandList, std::optional< PyAttribute > attributes, void * properties, std::optional< std::vector< PyRegion >> regions, DefaultingPyMlirContext context, DefaultingPyLocation location) inline
Given the arguments required to build an operation, attempts to infer the shaped type components.
Throws value_error on failure.
Definition at line 434 of file IRInterfaces.cpp.
References appendResultsCallback(), mlir::python::PyMlirContext::get(), mlir::python::PyConcreteOpInterface< PyInferShapedTypeOpInterface >::getOpName(), mlirAttributeGetNull(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirLogicalResultIsFailure(), mlirStringRefCreate(), mlir::python::DefaultingPyMlirContext::resolve(), and mlir::python::DefaultingPyLocation::resolve().
Referenced by bindDerived().
Member Data Documentation
getInterfaceID
constexpr static GetTypeIDFunctionTy mlir::python::PyInferShapedTypeOpInterface::getInterfaceID static constexpr
Initial value:
=
      &mlirInferShapedTypeOpInterfaceTypeID
Definition at line 406 of file IRInterfaces.cpp.
pyClassName
constexpr static const char* mlir::python::PyInferShapedTypeOpInterface::pyClassName = "InferShapedTypeOpInterface" static constexpr
Definition at line 405 of file IRInterfaces.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRInterfaces.cpp