MLIR: mlir::impl::DataLayoutEntryStorage Class Reference
mlir::impl::DataLayoutEntryStorage Class Reference
Public Types
using KeyTy = std::pair< DataLayoutEntryKey, Attribute >
Public Member Functions
DataLayoutEntryStorage (DataLayoutEntryKey entryKey, Attribute value)
bool operator== (const KeyTy &other) const
Public Member Functions inherited from mlir::AttributeStorage
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static DataLayoutEntryStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
DataLayoutEntryKey entryKey
Attribute value
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 29 of file DLTI.cpp.
Member Typedef Documentation
KeyTy
using mlir::impl::DataLayoutEntryStorage::KeyTy = std::pair<DataLayoutEntryKey, Attribute>
Definition at line 31 of file DLTI.cpp.
Constructor & Destructor Documentation
DataLayoutEntryStorage()
mlir::impl::DataLayoutEntryStorage::DataLayoutEntryStorage (DataLayoutEntryKey entryKey, Attribute value) inline
Definition at line 33 of file DLTI.cpp.
Referenced by construct().
Member Function Documentation
construct()
static DataLayoutEntryStorage* mlir::impl::DataLayoutEntryStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 36 of file DLTI.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and DataLayoutEntryStorage().
operator==()
bool mlir::impl::DataLayoutEntryStorage::operator== (const KeyTy & other) const inline
Definition at line 42 of file DLTI.cpp.
References entryKey, and value.
Member Data Documentation
entryKey
DataLayoutEntryKey mlir::impl::DataLayoutEntryStorage::entryKey
Definition at line 46 of file DLTI.cpp.
Referenced by operator==().
value
Attribute mlir::impl::DataLayoutEntryStorage::value
Definition at line 47 of file DLTI.cpp.
Referenced by operator==().
The documentation for this class was generated from the following file:
lib/Dialect/DLTI/DLTI.cpp