MLIR: mlir::OpBuilder::InsertionGuard Class Reference
mlir::OpBuilder::InsertionGuard Class Reference
RAII guard to reset the insertion point of the builder when destroyed.
#include "mlir/IR/Builders.h"
Public Member Functions
InsertionGuard (OpBuilder &builder)
~InsertionGuard ()
InsertionGuard (const InsertionGuard &)=delete
InsertionGuard & operator= (const InsertionGuard &)=delete
InsertionGuard (InsertionGuard &&other) noexcept
Implement the move constructor to clear the builder field of other.
InsertionGuard & operator= (InsertionGuard &&other)=delete
Detailed Description
RAII guard to reset the insertion point of the builder when destroyed.
Definition at line 348 of file Builders.h.
Constructor & Destructor Documentation
InsertionGuard() [1/3]
mlir::OpBuilder::InsertionGuard::InsertionGuard (OpBuilder & builder) inline
Definition at line 350 of file Builders.h.
References mlir::OpBuilder::OpBuilder(), and mlir::OpBuilder::saveInsertionPoint().
Referenced by InsertionGuard(), InsertionGuard(), operator=(), and operator=().
~InsertionGuard()
mlir::OpBuilder::InsertionGuard::~InsertionGuard () inline
Definition at line 353 of file Builders.h.
InsertionGuard() [2/3]
mlir::OpBuilder::InsertionGuard::InsertionGuard (const InsertionGuard &) delete
References InsertionGuard().
InsertionGuard() [3/3]
mlir::OpBuilder::InsertionGuard::InsertionGuard (InsertionGuard && other) inline noexcept
Implement the move constructor to clear the builder field of other.
That way it does not restore the insertion point upon destruction as that should be done exclusively by the just constructed InsertionGuard.
Definition at line 364 of file Builders.h.
References InsertionGuard().
Member Function Documentation
operator=() [1/2]
InsertionGuard & mlir::OpBuilder::InsertionGuard::operator= (const InsertionGuard &) delete
References InsertionGuard().
operator=() [2/2]
InsertionGuard & mlir::OpBuilder::InsertionGuard::operator= (InsertionGuard && other) delete
References InsertionGuard(), and mlir::OpBuilder::OpBuilder().
The documentation for this class was generated from the following file:
include/mlir/IR/Builders.h