MLIR: mlir::python::PyGlobals::TracebackLoc Class Reference
mlir::python::PyGlobals::TracebackLoc Class Reference
#include "Bindings/Python/Globals.h"
Public Member Functions
bool locTracebacksEnabled ()
void setLocTracebacksEnabled (bool value)
size_t locTracebackFramesLimit ()
void setLocTracebackFramesLimit (size_t value)
void registerTracebackFileInclusion (const std::string &file)
void registerTracebackFileExclusion (const std::string &file)
bool isUserTracebackFilename (llvm::StringRef file)
Static Public Attributes
static constexpr size_t kMaxFrames = 512
Detailed Description
Definition at line 122 of file Globals.h.
Member Function Documentation
isUserTracebackFilename()
bool PyGlobals::TracebackLoc::isUserTracebackFilename (llvm::StringRef file)
Definition at line 245 of file IRModule.cpp.
locTracebackFramesLimit()
size_t PyGlobals::TracebackLoc::locTracebackFramesLimit ()
Definition at line 211 of file IRModule.cpp.
Referenced by NB_MODULE().
locTracebacksEnabled()
bool PyGlobals::TracebackLoc::locTracebacksEnabled ()
Definition at line 201 of file IRModule.cpp.
Referenced by NB_MODULE().
registerTracebackFileExclusion()
void PyGlobals::TracebackLoc::registerTracebackFileExclusion (const std::string & file)
Definition at line 233 of file IRModule.cpp.
Referenced by NB_MODULE().
registerTracebackFileInclusion()
void PyGlobals::TracebackLoc::registerTracebackFileInclusion (const std::string & file)
Definition at line 221 of file IRModule.cpp.
Referenced by NB_MODULE().
setLocTracebackFramesLimit()
void PyGlobals::TracebackLoc::setLocTracebackFramesLimit (size_t value)
Definition at line 216 of file IRModule.cpp.
References kMaxFrames.
Referenced by NB_MODULE().
setLocTracebacksEnabled()
void PyGlobals::TracebackLoc::setLocTracebacksEnabled (bool value)
Definition at line 206 of file IRModule.cpp.
Referenced by NB_MODULE().
Member Data Documentation
kMaxFrames
size_t mlir::python::PyGlobals::TracebackLoc::kMaxFrames = 512 static constexpr
Definition at line 138 of file Globals.h.
Referenced by NB_MODULE(), and setLocTracebackFramesLimit().
The documentation for this class was generated from the following files:
lib/Bindings/Python/Globals.h
lib/Bindings/Python/IRModule.cpp