MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList Class Reference
A list of block arguments.
#include "mlir/Bindings/Python/IRCore.h"
Public Types
using SliceableT = Sliceable<PyBlockArgumentList, PyBlockArgument>
Public Member Functions
PyBlockArgumentList (PyOperationRef operation, MlirBlock block, intptr_t startIndex=0, intptr_t length=-1, intptr_t step=1)
Public Member Functions inherited from mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >
Sliceable (intptr_t startIndex, intptr_t length, intptr_t step)
PyBlockArgument getElement (intptr_t index)
Returns the index-th element in the slice, supports negative indices.
intptr_t size ()
Returns the size of slice.
std::vector< PyBlockArgument > dunderAdd (PyBlockArgumentList &other)
Returns a new vector (mapped to Python list) containing elements from two slices.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >
static void bind (nanobind::module_ &m)
Binds the indexing and length methods in the Python class.
static void bindDerived (ClassTy &)
Hook for derived classes willing to bind more methods.
Static Public Attributes
static constexpr const char * pyClassName = "BlockArgumentList"
Friends
class Sliceable< PyBlockArgumentList, PyBlockArgument >
Give the parent CRTP class access to hook implementations below.
Additional Inherited Members
Public Attributes inherited from mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >
intptr_t startIndex
intptr_t length
intptr_t step
Protected Types inherited from mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >
using ClassTy
Protected Member Functions inherited from mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >
intptr_t wrapIndex (intptr_t index)
Transforms index into a legal value to access the underlying sequence.
intptr_t linearizeIndex (intptr_t index)
Computes the linear index given the current slice properties.
nanobind::typed< nanobind::object, PyBlockArgument > getItem (intptr_t index)
Returns the element at the given slice index.
nanobind::object getItemSlice (PyObject *slice)
Returns a new instance of the pseudo-container restricted to the given slice.
Static Protected Attributes inherited from mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >
static constexpr std::array< const char *, 0 > typeParams
Type parameter names for generic classes.
Detailed Description
A list of block arguments.
Internally, these are stored as consecutive elements, random access is cheap. The argument list is associated with the operation that contains the block (detached blocks are not allowed in Python bindings) and extends its lifetime.
Definition at line 1771 of file IRCore.h.
Member Typedef Documentation
SliceableT
using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList::SliceableT = Sliceable<PyBlockArgumentList, PyBlockArgument>
Definition at line 1775 of file IRCore.h.
Constructor & Destructor Documentation
PyBlockArgumentList()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList::PyBlockArgumentList (PyOperationRef operation, MlirBlock block, intptr_t startIndex = 0, intptr_t length = -1, intptr_t step = 1)
Definition at line 2206 of file IRCore.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandList::PyOpOperandList(), and Sliceable< PyBlockArgumentList, PyBlockArgument >.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList::bindDerived (ClassTy & c) static
Definition at line 2213 of file IRCore.cpp.
References mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::length, mlirBlockGetNumArguments(), mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::Sliceable(), mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::startIndex, and mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::step.
Referenced by Sliceable< PyBlockArgumentList, PyBlockArgument >.
Friends And Related Symbol Documentation
Sliceable< PyBlockArgumentList, PyBlockArgument >
friend class Sliceable< PyBlockArgumentList, PyBlockArgument > friend
Give the parent CRTP class access to hook implementations below.
Definition at line 1781 of file IRCore.h.
References bindDerived(), mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::length, PyBlockArgumentList(), mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::Sliceable(), mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::startIndex, and mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::step.
Member Data Documentation
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockArgumentList::pyClassName = "BlockArgumentList" static constexpr
Definition at line 1774 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp