MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr Class Reference
Public Member Functions
nb::typed< nb::object, PyAffineExpr > lhs ()
nb::typed< nb::object, PyAffineExpr > rhs ()
PyConcreteAffineExpr ()=default
PyConcreteAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr)
PyConcreteAffineExpr (PyAffineExpr &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineBinaryExpr >
PyConcreteAffineExpr ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr
PyAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr)
bool operator== (const PyAffineExpr &other) const
operator MlirAffineExpr () const
MlirAffineExpr get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineExpr.
PyAffineExpr add (const PyAffineExpr &other) const
PyAffineExpr mul (const PyAffineExpr &other) const
PyAffineExpr floorDiv (const PyAffineExpr &other) const
PyAffineExpr ceilDiv (const PyAffineExpr &other) const
PyAffineExpr mod (const PyAffineExpr &other) const
nanobind::typed< nanobind::object, PyAffineExpr > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineBinaryExpr >
static MlirAffineExpr castFrom (PyAffineExpr &orig)
static void bind (nb::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr
static PyAffineExpr createFromCapsule (const nanobind::object &capsule)
Creates a PyAffineExpr from the MlirAffineExpr wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirAffineExprIsABinary
static constexpr const char * pyClassName = "AffineBinaryExpr"
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineBinaryExpr >
using ClassTy
using IsAFunctionTy
Detailed Description
Definition at line 181 of file IRAffine.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::bindDerived (ClassTy & c) inline static
Definition at line 197 of file IRAffine.cpp.
References lhs(), and rhs().
lhs()
nb::typed< nb::object, PyAffineExpr > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::lhs () inline
Definition at line 187 of file IRAffine.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirAffineBinaryOpExprGetLHS(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::PyAffineExpr().
Referenced by bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::getRHSConstant(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::getRHSConstant().
PyConcreteAffineExpr() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr () default
PyConcreteAffineExpr() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr (PyAffineExpr & orig) inline
Definition at line 94 of file IRAffine.cpp.
PyConcreteAffineExpr() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::PyConcreteAffineExpr (PyMlirContextRef contextRef, MlirAffineExpr affineExpr) inline
Definition at line 92 of file IRAffine.cpp.
rhs()
nb::typed< nb::object, PyAffineExpr > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::rhs () inline
Definition at line 192 of file IRAffine.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirAffineBinaryOpExprGetRHS(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::PyAffineExpr().
Referenced by bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::getRHSConstant(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::getRHSConstant().
Member Data Documentation
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::isaFunction = mlirAffineExprIsABinary static constexpr
Definition at line 183 of file IRAffine.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineBinaryExpr::pyClassName = "AffineBinaryExpr" static constexpr
Definition at line 184 of file IRAffine.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRAffine.cpp