MLIR: mlir::IROperand< DerivedT, IRValueT > Class Template Reference
mlir::IROperand< DerivedT, IRValueT > Class Template Reference
A reference to a value, suitable for use as an operand of an operation.
#include "mlir/IR/UseDefLists.h"
Public Member Functions
IROperand (Operation *owner)
IROperand (Operation *owner, IRValueT value)
IROperand (IROperand &&other)
We support a move constructor so IROperand's can be in vectors, but this shouldn't be used by general clients.
IROperand & operator= (IROperand &&other)
bool operator== (const IROperand< DerivedT, IRValueT > &other) const
Two operands are equal if they have the same owner and the same operand number.
bool operator!= (const IROperand< DerivedT, IRValueT > &other) const
IRValueT get () const
Return the current value being used by this operand.
void set (IRValueT newValue)
Set the current value being used by this operand.
bool is (IRValueT other) const
Returns true if this operand contains the given value.
void drop ()
Remove this use of the operand.
Public Member Functions inherited from mlir::detail::IROperandBase
Operation * getOwner () const
Return the owner of this operand.
IROperandBase * getNextOperandUsingThisValue ()
Return the next operand on the use-list of the value we are referring to.
void initChainWithUse (IROperandBase **self)
Initialize the use-def chain by setting the back address to self and nextUse to nullptr.
void linkTo (IROperandBase *next)
Link the current node to next.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::IROperandBase
IROperandBase (Operation *owner)
IROperandBase (IROperandBase &&other)
IROperandBase & operator= (IROperandBase &&other)
IROperandBase (const IROperandBase &use)=delete
Operands are not copyable or assignable.
IROperandBase & operator= (const IROperandBase &use)=delete
~IROperandBase ()
void drop ()
Remove this use of the operand.
void removeFromCurrent ()
Remove this operand from the current use list.
template<typename UseListT>
void insertInto (UseListT *useList)
Insert this operand into the given use list.
Protected Attributes inherited from mlir::detail::IROperandBase
IROperandBase * nextUse = nullptr
The next operand in the use-chain.
IROperandBase ** back = nullptr
This points to the previous link in the use-chain.
Detailed Description
template<typename DerivedT, typename IRValueT>
class mlir::IROperand< DerivedT, IRValueT >
A reference to a value, suitable for use as an operand of an operation.
IRValueT is the root type to use for values this tracks. Derived operand types are expected to provide the following:
static IRObjectWithUseList *getUseList(IRValueT value);
Provide the use list that is attached to the given value.
Definition at line 127 of file UseDefLists.h.
Constructor & Destructor Documentation
IROperand() [1/3]
template<typename DerivedT, typename IRValueT> mlir::IROperand< DerivedT, IRValueT >::IROperand (Operation * owner) inline
Definition at line 129 of file UseDefLists.h.
References mlir::detail::IROperandBase::IROperandBase().
Referenced by IROperand(), operator!=(), operator=(), and operator==().
IROperand() [2/3]
template<typename DerivedT, typename IRValueT> mlir::IROperand< DerivedT, IRValueT >::IROperand (Operation * owner, IRValueT value) inline
Definition at line 130 of file UseDefLists.h.
References mlir::detail::IROperandBase::IROperandBase().
IROperand() [3/3]
template<typename DerivedT, typename IRValueT> mlir::IROperand< DerivedT, IRValueT >::IROperand (IROperand< DerivedT, IRValueT > && other) inline
We support a move constructor so IROperand's can be in vectors, but this shouldn't be used by general clients.
Definition at line 137 of file UseDefLists.h.
References IROperand(), and mlir::detail::IROperandBase::IROperandBase().
Member Function Documentation
drop()
template<typename DerivedT, typename IRValueT> void mlir::IROperand< DerivedT, IRValueT >::drop () inline
Remove this use of the operand.
Definition at line 175 of file UseDefLists.h.
References mlir::detail::IROperandBase::drop().
get()
template<typename DerivedT, typename IRValueT> IRValueT mlir::IROperand< DerivedT, IRValueT >::get () const inline
Return the current value being used by this operand.
Definition at line 160 of file UseDefLists.h.
Referenced by areBinOpsSwapped(), mlir::linalg::areElementwiseOpsFusable(), areNonConflictingSubsets(), bubbleDownCastsPassthroughOpImpl(), mlir::detail::bubbleDownInPlaceMemorySpaceCastImpl(), mlir::bufferization::OneShotAnalysisState::bufferizeInPlace(), buildPackingLoopNestImpl(), buildVectorWrite(), canBeHoisted(), cloneAndFuseFirstUse(), mlir::linalg::computeIndexingMapOpInterfacePaddedShape(), deduplicateInputOperands(), mlir::bufferization::OneShotAnalysisState::findDefinitionsCached(), fuse(), mlir::linalg::fuseElementwiseOps(), mlir::linalg::fuseProducerOfTensor(), mlir::linalg::fuseProducerOfTensor(), genConstantDenseAddressFromLevel(), generateFusedElementwiseOpRegion(), genIndex(), genInsertionLoad(), genInvariants(), genSubscript(), genTensorLoad(), getAllTidLvlsInLatPoints(), mlir::xegpu::getDistributeLayoutAttr(), mlir::xegpu::getDistributeLayoutAttr(), mlir::Operation::getOperand(), getSharding(), mlir::shard::getSharding(), getUntiledProducerFromSliceSource(), getUnusedOutOperand(), mlir::getUsedValuesDefinedAbove(), hasNonTrivialAffineOnSparseOut(), mlir::linalg::hoistRedundantVectorBroadcasts(), hoistSubsetAtIterArg(), isaExternalFillOp(), isFillInterfaceImpl(), isMaterializing(), isSparseTensor(), isValueUsePotentialConsumer(), mlir::linalg::linalgOpAnchoredEmptyTensorEliminationStep(), mlir::shard::maybeInsertSourceShardingAnnotation(), maybeInsertTargetShardingAnnotationImpl(), mlir::affine::numEnclosingInvariantLoops(), numEnclosingInvariantLoops(), mlir::linalg::padAndHoistLinalgOp(), padOperandToSmallestStaticBoundingBox(), relinkBranch(), mlir::scf::replaceAndCastForOpIterArg(), mlir::linalg::rewriteAsPaddedOp(), setInPlaceOpOperand(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), transposeOneLinalgOperandAndReplace(), mlir::linalg::detail::verifyStructuredOpInterface(), verifyYield(), mlir::dataflow::LivenessAnalysis::visitBranchOperand(), mlir::dataflow::LivenessAnalysis::visitCallOperand(), wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
is()
template<typename DerivedT, typename IRValueT> bool mlir::IROperand< DerivedT, IRValueT >::is (IRValueT other) const inline
Returns true if this operand contains the given value.
Definition at line 172 of file UseDefLists.h.
operator!=()
template<typename DerivedT, typename IRValueT> bool mlir::IROperand< DerivedT, IRValueT >::operator!= (const IROperand< DerivedT, IRValueT > & other) const inline
Definition at line 155 of file UseDefLists.h.
References IROperand().
operator=()
template<typename DerivedT, typename IRValueT> IROperand & mlir::IROperand< DerivedT, IRValueT >::operator= (IROperand< DerivedT, IRValueT > && other) inline
Definition at line 140 of file UseDefLists.h.
References IROperand(), and mlir::detail::IROperandBase::operator=().
operator==()
template<typename DerivedT, typename IRValueT> bool mlir::IROperand< DerivedT, IRValueT >::operator== (const IROperand< DerivedT, IRValueT > & other) const inline
Two operands are equal if they have the same owner and the same operand number.
They are stored inside of ops, so it is valid to compare their pointers to determine equality.
Definition at line 152 of file UseDefLists.h.
References IROperand().
set()
template<typename DerivedT, typename IRValueT> void mlir::IROperand< DerivedT, IRValueT >::set (IRValueT newValue) inline
Set the current value being used by this operand.
Definition at line 163 of file UseDefLists.h.
References mlir::detail::IROperandBase::removeFromCurrent().
Referenced by mlir::detail::bubbleDownInPlaceMemorySpaceCastImpl(), mlir::linalg::fuseProducerOfTensor(), mlir::linalg::linalgOpAnchoredEmptyTensorEliminationStep(), and mlir::Operation::setOperand().
The documentation for this class was generated from the following file:
include/mlir/IR/UseDefLists.h