MLIR: mlir::tblgen::Region Class Reference
mlir::tblgen::Region Class Reference
#include "mlir/TableGen/Region.h"
Public Member Functions
bool isVariadic () const
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getSummary () const
Kind getKind () const
const void * getAsOpaquePointer () const
Get an opaque pointer to the constraint.
Static Public Member Functions
static bool classof (const Constraint *c)
Static Public Member Functions inherited from mlir::tblgen::Constraint
static Constraint getFromOpaquePointer (const void *ptr)
Construct a constraint from the opaque pointer representation.
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind {
CK_Attr, CK_Region, CK_Successor, CK_Type,
CK_Uncategorized
}
Protected Member Functions inherited from mlir::tblgen::Constraint
Constraint (Kind kind, const llvm::Record *record)
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 20 of file Region.h.
Member Function Documentation
classof()
static bool mlir::tblgen::Region::classof (const Constraint * c) inline static
Definition at line 24 of file Region.h.
References mlir::tblgen::Constraint::CK_Region, mlir::tblgen::Constraint::getKind(), and isVariadic().
isVariadic()
bool Region::isVariadic () const
Definition at line 20 of file Region.cpp.
References mlir::tblgen::Constraint::def.
Referenced by classof().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Region.h
lib/TableGen/Region.cpp