MLIR: mlir::ValueBoundsConstraintSet::BoundBuilder Class Reference
mlir::ValueBoundsConstraintSet::BoundBuilder Class Reference
Helper class that builds a bound for a shaped value dimension or index-typed value.
#include "mlir/Interfaces/ValueBoundsOpInterface.h"
Public Member Functions
BoundBuilder & operator[] (int64_t dim)
Specify a dimension, assuming that the underlying value is a shaped value.
void operator< (AffineExpr expr)
void operator<= (AffineExpr expr)
void operator> (AffineExpr expr)
void operator>= (AffineExpr expr)
void operator== (AffineExpr expr)
void operator< (OpFoldResult ofr)
void operator<= (OpFoldResult ofr)
void operator> (OpFoldResult ofr)
void operator>= (OpFoldResult ofr)
void operator== (OpFoldResult ofr)
void operator< (int64_t i)
void operator<= (int64_t i)
void operator> (int64_t i)
void operator>= (int64_t i)
void operator== (int64_t i)
Protected Member Functions
BoundBuilder (ValueBoundsConstraintSet &cstr, Value value)
Friends
class ValueBoundsConstraintSet
Detailed Description
Helper class that builds a bound for a shaped value dimension or index-typed value.
Definition at line 73 of file ValueBoundsOpInterface.h.
Constructor & Destructor Documentation
BoundBuilder()
mlir::ValueBoundsConstraintSet::BoundBuilder::BoundBuilder (ValueBoundsConstraintSet & cstr, Value value) inline protected
Definition at line 98 of file ValueBoundsOpInterface.h.
Member Function Documentation
operator<() [1/3]
void ValueBoundsConstraintSet::BoundBuilder::operator< (AffineExpr expr)
Definition at line 975 of file ValueBoundsOpInterface.cpp.
References mlir::FlatLinearConstraints::addBound(), assertValidValueDim(), and mlir::ValueBoundsConstraintSet::cstr.
operator<() [2/3]
void ValueBoundsConstraintSet::BoundBuilder::operator< (int64_t i)
Definition at line 1024 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator<().
operator<() [3/3]
void ValueBoundsConstraintSet::BoundBuilder::operator< (OpFoldResult ofr)
Definition at line 1004 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator<().
operator<=() [1/3]
void ValueBoundsConstraintSet::BoundBuilder::operator<= (AffineExpr expr)
Definition at line 982 of file ValueBoundsOpInterface.cpp.
References mlir::presburger::operator<().
operator<=() [2/3]
void ValueBoundsConstraintSet::BoundBuilder::operator<= (int64_t i)
Definition at line 1028 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator<=().
operator<=() [3/3]
void ValueBoundsConstraintSet::BoundBuilder::operator<= (OpFoldResult ofr)
Definition at line 1008 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator<=().
operator==() [1/3]
void ValueBoundsConstraintSet::BoundBuilder::operator== (AffineExpr expr)
Definition at line 997 of file ValueBoundsOpInterface.cpp.
References mlir::FlatLinearConstraints::addBound(), assertValidValueDim(), and mlir::ValueBoundsConstraintSet::cstr.
operator==() [2/3]
void ValueBoundsConstraintSet::BoundBuilder::operator== (int64_t i)
Definition at line 1040 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::operator==().
operator==() [3/3]
void ValueBoundsConstraintSet::BoundBuilder::operator== (OpFoldResult ofr)
Definition at line 1020 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::operator==().
operator>() [1/3]
void ValueBoundsConstraintSet::BoundBuilder::operator> (AffineExpr expr)
Definition at line 986 of file ValueBoundsOpInterface.cpp.
References mlir::presburger::operator>=().
operator>() [2/3]
void ValueBoundsConstraintSet::BoundBuilder::operator> (int64_t i)
Definition at line 1032 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator>().
operator>() [3/3]
void ValueBoundsConstraintSet::BoundBuilder::operator> (OpFoldResult ofr)
Definition at line 1012 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator>().
operator>=() [1/3]
void ValueBoundsConstraintSet::BoundBuilder::operator>= (AffineExpr expr)
Definition at line 990 of file ValueBoundsOpInterface.cpp.
References mlir::FlatLinearConstraints::addBound(), assertValidValueDim(), and mlir::ValueBoundsConstraintSet::cstr.
operator>=() [2/3]
void ValueBoundsConstraintSet::BoundBuilder::operator>= (int64_t i)
Definition at line 1036 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator>=().
operator>=() [3/3]
void ValueBoundsConstraintSet::BoundBuilder::operator>= (OpFoldResult ofr)
Definition at line 1016 of file ValueBoundsOpInterface.cpp.
References mlir::ValueBoundsConstraintSet::cstr, and mlir::presburger::operator>=().
operator[]()
ValueBoundsConstraintSet::BoundBuilder & ValueBoundsConstraintSet::BoundBuilder::operator[] (int64_t dim)
Specify a dimension, assuming that the underlying value is a shaped value.
Definition at line 966 of file ValueBoundsOpInterface.cpp.
References assertValidValueDim().
Friends And Related Function Documentation
ValueBoundsConstraintSet
friend class ValueBoundsConstraintSet friend
Definition at line 97 of file ValueBoundsOpInterface.h.
The documentation for this class was generated from the following files:
include/mlir/Interfaces/ValueBoundsOpInterface.h
lib/Interfaces/ValueBoundsOpInterface.cpp