MLIR: mlir::NVVM::PtxBuilder Class Reference
mlir::NVVM::PtxBuilder Class Reference
A class to build PTX assembly automatically.
#include "mlir/Dialect/LLVMIR/BasicPtxBuilderInterface.h"
Public Member Functions
PtxBuilder (Operation *op, PatternRewriter &rewriter, bool needsManualRegisterMapping=false)
Single constructor that only initializes members.
LogicalResult insertValue (Value v, PTXRegisterMod itype=PTXRegisterMod::Read)
Add an operand with the read/write input type.
LLVM::InlineAsmOp build ()
Builds the inline assembly Op and returns it.
void buildAndReplaceOp ()
Shortcut to build the inline assembly Op and replace or erase the original op with.
Detailed Description
A class to build PTX assembly automatically.
It is used by BasicPtxBuilderInterface.
Definition at line 62 of file BasicPtxBuilderInterface.h.
Constructor & Destructor Documentation
PtxBuilder()
mlir::NVVM::PtxBuilder::PtxBuilder (Operation * op, PatternRewriter & rewriter, bool needsManualRegisterMapping = false) inline
Single constructor that only initializes members.
Definition at line 80 of file BasicPtxBuilderInterface.h.
Member Function Documentation
build()
LLVM::InlineAsmOp PtxBuilder::build ()
Builds the inline assembly Op and returns it.
The insertValue needs to be called to pass operands before building the PTX.
Definition at line 426 of file BasicPtxBuilderInterface.cpp.
References canonicalizeRegisterConstraints(), mlir::get(), None, packResultTypes(), and rewriteAsmPlaceholders().
Referenced by buildAndReplaceOp().
buildAndReplaceOp()
void PtxBuilder::buildAndReplaceOp ()
Shortcut to build the inline assembly Op and replace or erase the original op with.
Definition at line 467 of file BasicPtxBuilderInterface.cpp.
References build(), mlir::RewriterBase::eraseOp(), extractStructElements(), mlir::detail::IROperandBase::getOwner(), needsPackUnpack(), mlir::NVVM::ReadWrite, and mlir::RewriterBase::replaceOp().
insertValue()
LogicalResult PtxBuilder::insertValue (Value v, PTXRegisterMod itype = PTXRegisterMod::Read)
Add an operand with the read/write input type.
Definition at line 138 of file BasicPtxBuilderInterface.cpp.
References mlir::detail::enumerate(), mlir::remark::failed(), getRegisterType(), mlir::Value::getType(), mlir::RewriterBase::notifyMatchFailure(), mlir::NVVM::Read, mlir::NVVM::ReadWrite, and mlir::NVVM::Write.
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/BasicPtxBuilderInterface.h
lib/Dialect/LLVMIR/IR/BasicPtxBuilderInterface.cpp