MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBoolAttribute Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBoolAttribute Class Reference
Bool Attribute subclass - BoolAttr.
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
PyConcreteAttribute ()=default
PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
PyConcreteAttribute (PyAttribute &orig)
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyBoolAttribute >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyBoolAttribute >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirAttributeIsABool
static constexpr const char * pyClassName = "BoolAttr"
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyBoolAttribute >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyBoolAttribute >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Detailed Description
Bool Attribute subclass - BoolAttr.
Definition at line 350 of file IRAttributes.h.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBoolAttribute::bindDerived (ClassTy & c) static
Definition at line 471 of file IRAttributes.cpp.
References mlir::python::Defaulting< DerivedTy, T >::get(), mlirBoolAttrGet(), and mlirBoolAttrGetValue().
PyConcreteAttribute() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute () default
PyConcreteAttribute() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyAttribute & orig) inline
Definition at line 1085 of file IRCore.h.
PyConcreteAttribute() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< DerivedTy, BaseTy >::PyConcreteAttribute (PyMlirContextRef contextRef, MlirAttribute attr) inline
Definition at line 1083 of file IRCore.h.
Member Data Documentation
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBoolAttribute::isaFunction = mlirAttributeIsABool static constexpr
Definition at line 353 of file IRAttributes.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::integerOrBoolAttributeCaster().
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBoolAttribute::pyClassName = "BoolAttr" static constexpr
Definition at line 354 of file IRAttributes.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRAttributes.h
lib/Bindings/Python/IRAttributes.cpp