MLIR: mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect > Class Template Reference
mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect > Class Template Reference
This base class is used for derived effects that are non-parametric.
#include "mlir/Interfaces/SideEffectInterfaces.h"
Public Types
using BaseT = Base< DerivedEffect >
Static Public Member Functions
static TypeID getEffectID ()
Return the unique identifier for the base effects class.
static bool classof (const ::mlir::SideEffects::Effect *effect)
'classof' used to support llvm style cast functionality.
static DerivedEffect * get ()
Returns a unique instance for the derived effect class.
Static Public Member Functions inherited from mlir::SideEffects::Effect
template<typename DerivedEffect >
static DerivedEffect * get ()
Returns a unique instance for the given effect class.
Protected Member Functions
Base ()
Protected Member Functions inherited from mlir::SideEffects::Effect
Effect (TypeID id)
Additional Inherited Members
Public Member Functions inherited from mlir::SideEffects::Effect
TypeID getEffectID () const
Return the unique identifier for the base effects class.
Detailed Description
template<typename DerivedEffect, typename BaseEffect = Effect>
class mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >
This base class is used for derived effects that are non-parametric.
Definition at line 30 of file SideEffectInterfaces.h.
Member Typedef Documentation
BaseT
template<typename DerivedEffect , typename BaseEffect = Effect> using mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::BaseT = Base<DerivedEffect>
Definition at line 32 of file SideEffectInterfaces.h.
Constructor & Destructor Documentation
Base()
template<typename DerivedEffect , typename BaseEffect = Effect> mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::Base () inline protected
Definition at line 49 of file SideEffectInterfaces.h.
Member Function Documentation
classof()
template<typename DerivedEffect , typename BaseEffect = Effect> static bool mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::classof (const ::mlir::SideEffects::Effect * effect) inline static
'classof' used to support llvm style cast functionality.
Definition at line 38 of file SideEffectInterfaces.h.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::getEffectID().
get()
template<typename DerivedEffect , typename BaseEffect = Effect> static DerivedEffect* mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get () inline static
Returns a unique instance for the derived effect class.
Definition at line 43 of file SideEffectInterfaces.h.
Referenced by mlir::transform::consumesHandle(), mlir::affine::AffineDmaStartOp::getEffects(), mlir::affine::AffineDmaWaitOp::getEffects(), getGenericEffectsImpl(), mlir::transform::modifiesPayload(), mlir::transform::onlyReadsHandle(), mlir::transform::onlyReadsPayload(), and mlir::transform::producesHandle().
getEffectID()
template<typename DerivedEffect , typename BaseEffect = Effect> static TypeID mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::getEffectID () inline static
Return the unique identifier for the base effects class.
Definition at line 35 of file SideEffectInterfaces.h.
Referenced by mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::classof().
The documentation for this class was generated from the following file:
include/mlir/Interfaces/SideEffectInterfaces.h