MLIR: mlir::query::matcher::MatchFinder Class Reference
mlir::query::matcher::MatchFinder Class Reference
Finds and collects matches from the IR.
#include "mlir/Query/Matcher/MatchFinder.h"
Classes
struct MatchResult
A subclass which preserves the matching information.
Public Member Functions
std::vector< MatchResult > collectMatches (Operation *root, DynMatcher matcher) const
Traverses the IR and returns a vector of MatchResult for each match of the matcher.
void printMatch (llvm::raw_ostream &os, QuerySession &qs, Operation *op) const
Prints the matched operation.
void printMatch (llvm::raw_ostream &os, QuerySession &qs, Operation *op, const std::string &binding) const
Labels the matched operation with the given binding (e.g., "root") and prints it.
std::vector< Operation * > flattenMatchedOps (std::vector< MatchResult > &matches) const
Flattens a vector of MatchResult into a vector of operations.
Detailed Description
Finds and collects matches from the IR.
After construction collectMatches can be used to traverse the IR and apply matchers.
Definition at line 27 of file MatchFinder.h.
Member Function Documentation
collectMatches()
std::vector< MatchFinder::MatchResult > mlir::query::matcher::MatchFinder::collectMatches (Operation * root, DynMatcher matcher) const
Traverses the IR and returns a vector of MatchResult for each match of the matcher.
Definition at line 21 of file MatchFinder.cpp.
References mlir::query::matcher::MatchFinder::MatchResult::matchedOps, mlir::query::matcher::MatchFinder::MatchResult::rootOp, and mlir::Operation::walk().
Referenced by mlir::query::MatchQuery::run().
flattenMatchedOps()
std::vector< Operation * > mlir::query::matcher::MatchFinder::flattenMatchedOps (std::vector< MatchResult > & matches) const
Flattens a vector of MatchResult into a vector of operations.
Definition at line 59 of file MatchFinder.cpp.
References result.
Referenced by mlir::query::MatchQuery::run().
printMatch() [1/2]
void mlir::query::matcher::MatchFinder::printMatch (llvm::raw_ostream & os, QuerySession & qs, Operation * op) const
Prints the matched operation.
Definition at line 39 of file MatchFinder.cpp.
References diag(), mlir::query::QuerySession::getBufferId(), mlir::Operation::getLoc(), and mlir::query::QuerySession::getSourceManager().
Referenced by mlir::query::MatchQuery::run().
printMatch() [2/2]
void mlir::query::matcher::MatchFinder::printMatch (llvm::raw_ostream & os, QuerySession & qs, Operation * op, const std::string & binding) const
Labels the matched operation with the given binding (e.g., "root") and prints it.
Definition at line 49 of file MatchFinder.cpp.
References mlir::query::QuerySession::getBufferId(), mlir::Operation::getLoc(), and mlir::query::QuerySession::getSourceManager().
The documentation for this class was generated from the following files:
include/mlir/Query/Matcher/MatchFinder.h
lib/Query/Matcher/MatchFinder.cpp