MLIR: mlir::linalg::BatchMatmulTransposeBOp Class Reference
mlir::linalg::BatchMatmulTransposeBOp Class Reference
Specialization of linalg.batch_matmul op that has a transpose map on B.
#include "mlir/Dialect/Linalg/IR/Linalg.h"
Static Public Member Functions
::mlir::TypeID resolveTypeID ()
static void build (OpBuilder &builder, OperationState &result, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
Build a transpose B matmul.
static BatchMatmulTransposeBOp create (OpBuilder &builder, Location location, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
static void build (OpBuilder &builder, OperationState &result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
Build a transpose B matmul with a specific result type.
static BatchMatmulTransposeBOp create (OpBuilder &builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes={})
static void build (OpBuilder &builder, OperationState &result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes={})
Build a transpose B matmul with a specific result type and a cast type.
static BatchMatmulTransposeBOp create (OpBuilder &builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes={})
static bool isDefaultIndexingMaps (Attribute attr)
Checks if the affine map is the expected one for this operation.
static bool classof (Operation *op)
Detailed Description
Specialization of linalg.batch_matmul op that has a transpose map on B.
Definition at line 298 of file Linalg.h.
Member Function Documentation
build() [1/3]
void mlir::linalg::linalg::BatchMatmulTransposeBOp::build (OpBuilder & builder, OperationState & result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose B matmul with a specific result type.
Definition at line 4293 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
build() [2/3]
void mlir::linalg::linalg::BatchMatmulTransposeBOp::build (OpBuilder & builder, OperationState & result, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose B matmul with a specific result type and a cast type.
Definition at line 4314 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
build() [3/3]
void mlir::linalg::linalg::BatchMatmulTransposeBOp::build (OpBuilder & builder, OperationState & result, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Build a transpose B matmul.
Definition at line 4274 of file LinalgOps.cpp.
References buildMatmulOp(), and result.
Referenced by create(), create(), and create().
classof()
bool mlir::linalg::BatchMatmulTransposeBOp::classof (Operation * op) static
Definition at line 4336 of file LinalgOps.cpp.
References mlir::Operation::getAttr(), and isDefaultIndexingMaps().
create() [1/3]
BatchMatmulTransposeBOp mlir::linalg::BatchMatmulTransposeBOp::create (OpBuilder & builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4303 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
create() [2/3]
BatchMatmulTransposeBOp mlir::linalg::BatchMatmulTransposeBOp::create (OpBuilder & builder, Location location, TypeRange resultTensorTypes, ValueRange inputs, ValueRange outputs, Attribute cast, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4325 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
create() [3/3]
BatchMatmulTransposeBOp mlir::linalg::BatchMatmulTransposeBOp::create (OpBuilder & builder, Location location, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes = {}) static
Definition at line 4283 of file LinalgOps.cpp.
References build(), and mlir::OpBuilder::create().
Referenced by mlir::linalg::transposeBatchMatmul().
isDefaultIndexingMaps()
bool mlir::linalg::BatchMatmulTransposeBOp::isDefaultIndexingMaps (Attribute attr) static
Checks if the affine map is the expected one for this operation.
Definition at line 4260 of file LinalgOps.cpp.
References mlir::linalg::getAffineResultPositions().
Referenced by classof().
resolveTypeID()
::mlir::TypeID mlir::linalg::BatchMatmulTransposeBOp::resolveTypeID () inline static
Definition at line 305 of file Linalg.h.
References mlir::TypeID::get().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/IR/Linalg.h
lib/Dialect/Linalg/IR/LinalgOps.cpp