MLIR: mlir::remark::detail::InFlightRemark Class Reference
mlir::remark::detail::InFlightRemark Class Reference
InFlightRemark is a RAII class that holds a reference to a Remark instance and allows to build the remark using the << operator.
#include "mlir/IR/Remarks.h"
Public Member Functions
InFlightRemark (std::unique_ptr< Remark > diag)
InFlightRemark (RemarkEngine &eng, std::unique_ptr< Remark > diag)
InFlightRemark ()=default
InFlightRemark & operator<< (const LazyTextBuild &l)
template<typename T, typename = std::enable_if_t< !std::is_same_v<std::decay_t<T>, LazyTextBuild>>>
InFlightRemark & operator<< (T &&arg)
operator bool () const
~InFlightRemark ()
InFlightRemark (const InFlightRemark &)=delete
InFlightRemark & operator= (const InFlightRemark &)=delete
InFlightRemark (InFlightRemark &&)=default
InFlightRemark & operator= (InFlightRemark &&)=default
Detailed Description
InFlightRemark is a RAII class that holds a reference to a Remark instance and allows to build the remark using the << operator.
The remark is emitted when the InFlightRemark instance is destroyed, which happens when the scope ends or when the InFlightRemark instance is moved. Similar to InFlightDiagnostic, but for remarks.
Definition at line 292 of file Remarks.h.
Constructor & Destructor Documentation
InFlightRemark() [1/5]
mlir::remark::detail::InFlightRemark::InFlightRemark (std::unique_ptr< Remark > diag) inline explicit
Definition at line 294 of file Remarks.h.
References diag().
Referenced by InFlightRemark(), InFlightRemark(), operator<<(), operator<<(), operator=(), and operator=().
InFlightRemark() [2/5]
mlir::remark::detail::InFlightRemark::InFlightRemark (RemarkEngine & eng, std::unique_ptr< Remark > diag) inline
Definition at line 297 of file Remarks.h.
References diag().
InFlightRemark() [3/5]
mlir::remark::detail::InFlightRemark::InFlightRemark () default
~InFlightRemark()
InFlightRemark::~InFlightRemark ()
Definition at line 164 of file Remarks.cpp.
InFlightRemark() [4/5]
mlir::remark::detail::InFlightRemark::InFlightRemark (const InFlightRemark &) delete
References InFlightRemark().
InFlightRemark() [5/5]
mlir::remark::detail::InFlightRemark::InFlightRemark (InFlightRemark &&) default
References InFlightRemark().
Member Function Documentation
operator bool()
mlir::remark::detail::InFlightRemark::operator bool () const inline explicit
Definition at line 317 of file Remarks.h.
operator<<() [1/2]
InFlightRemark & mlir::remark::detail::InFlightRemark::operator<< (const LazyTextBuild & l) inline
Definition at line 302 of file Remarks.h.
References InFlightRemark(), mlir::remark::detail::LazyTextBuild::key, and mlir::remark::detail::LazyTextBuild::thunk.
operator<<() [2/2]
template<typename T, typename = std::enable_if_t< !std::is_same_v<std::decay_t<T>, LazyTextBuild>>> InFlightRemark & mlir::remark::detail::InFlightRemark::operator<< (T && arg) inline
Definition at line 311 of file Remarks.h.
References InFlightRemark().
operator=() [1/2]
InFlightRemark & mlir::remark::detail::InFlightRemark::operator= (const InFlightRemark &) delete
References InFlightRemark().
operator=() [2/2]
InFlightRemark & mlir::remark::detail::InFlightRemark::operator= (InFlightRemark &&) default
References InFlightRemark().
The documentation for this class was generated from the following files:
include/mlir/IR/Remarks.h
lib/IR/Remarks.cpp