MLIR: mlir::AffineBound Class Reference
mlir::AffineBound Class Reference
AffineBound represents a lower or upper bound in the for operation.
#include "mlir/Dialect/Affine/IR/AffineOps.h"
Public Types
using operand_iterator = AffineForOp::operand_iterator
using operand_range = AffineForOp::operand_range
Public Member Functions
AffineForOp getAffineForOp ()
AffineMap getMap ()
unsigned getNumOperands ()
Value getOperand (unsigned idx)
operand_iterator operand_begin ()
operand_iterator operand_end ()
operand_range getOperands ()
Friends
class AffineForOp
Detailed Description
AffineBound represents a lower or upper bound in the for operation.
This class does not own the underlying operands. Instead, it refers to the operands stored in the AffineForOp. Its life span should not exceed that of the for operation it refers to.
Definition at line 427 of file AffineOps.h.
Member Typedef Documentation
operand_iterator
using mlir::AffineBound::operand_iterator = AffineForOp::operand_iterator
Definition at line 435 of file AffineOps.h.
operand_range
using mlir::AffineBound::operand_range = AffineForOp::operand_range
Definition at line 436 of file AffineOps.h.
Member Function Documentation
getAffineForOp()
AffineForOp mlir::AffineBound::getAffineForOp () inline
Definition at line 429 of file AffineOps.h.
References op.
getMap()
AffineMap mlir::AffineBound::getMap () inline
Definition at line 430 of file AffineOps.h.
References map().
Referenced by constructTiledIndexSetHyperRect(), mlir::normalizeAffineFor(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getNumOperands()
unsigned mlir::AffineBound::getNumOperands () inline
Definition at line 432 of file AffineOps.h.
Referenced by constructTiledIndexSetHyperRect(), mlir::normalizeAffineFor(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getOperand()
Value mlir::AffineBound::getOperand (unsigned idx) inline
Definition at line 433 of file AffineOps.h.
References op.
Referenced by constructTiledIndexSetHyperRect(), mlir::normalizeAffineFor(), setInterTileBoundsParametric(), and setIntraTileBoundsParametric().
getOperands()
operand_range mlir::AffineBound::getOperands () inline
Definition at line 440 of file AffineOps.h.
References map(), and op.
Referenced by mlir::normalizeAffineFor().
operand_begin()
operand_iterator mlir::AffineBound::operand_begin () inline
Definition at line 438 of file AffineOps.h.
References op.
operand_end()
operand_iterator mlir::AffineBound::operand_end () inline
Definition at line 439 of file AffineOps.h.
References op.
Friends And Related Function Documentation
AffineForOp
friend class AffineForOp friend
Definition at line 454 of file AffineOps.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Affine/IR/AffineOps.h