MLIR: mlir::RaggedArray< T >::const_iterator Class Reference
mlir::RaggedArray< T >::const_iterator Class Reference
Constant iterator over the rows.
#include "mlir/Dialect/Transform/Utils/RaggedArray.h"
Public Member Functions
const_iterator (const RaggedArray &ragged)
Creates the start iterator.
const_iterator (const RaggedArray &ragged, size_t pos)
Creates the end iterator.
ArrayRef< T > operator* () const
Dereferences the current iterator. Assumes in-bounds.
const_iterator & operator++ ()
Increments the iterator.
bool operator== (const const_iterator &other) const
Compares the two iterators.
Detailed Description
template<typename T>
class mlir::RaggedArray< T >::const_iterator
Constant iterator over the rows.
Definition at line 76 of file RaggedArray.h.
Constructor & Destructor Documentation
const_iterator() [1/2]
template<typename T> mlir::RaggedArray< T >::const_iterator::const_iterator (const RaggedArray & ragged) inline explicit
Creates the start iterator.
Definition at line 82 of file RaggedArray.h.
Referenced by operator++(), and operator==().
const_iterator() [2/2]
template<typename T> mlir::RaggedArray< T >::const_iterator::const_iterator (const RaggedArray & ragged, size_t pos) inline
Creates the end iterator.
Definition at line 86 of file RaggedArray.h.
Member Function Documentation
operator*()
template<typename T> ArrayRef< T > mlir::RaggedArray< T >::const_iterator::operator* () const inline
Dereferences the current iterator. Assumes in-bounds.
Definition at line 90 of file RaggedArray.h.
operator++()
template<typename T> const_iterator & mlir::RaggedArray< T >::const_iterator::operator++ () inline
Increments the iterator.
Definition at line 93 of file RaggedArray.h.
References const_iterator().
operator==()
template<typename T> bool mlir::RaggedArray< T >::const_iterator::operator== (const const_iterator & other) const inline
Compares the two iterators.
Iterators into different ragged arrays compare not equal.
Definition at line 101 of file RaggedArray.h.
References const_iterator().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/Utils/RaggedArray.h