MLIR: mlir::tblgen::Interface Class Reference
mlir::tblgen::Interface Class Reference
#include "mlir/TableGen/Interfaces.h"
Public Member Functions
Interface (const llvm::Record *def)
Interface (const Interface &rhs)
StringRef getName () const
std::string getFullyQualifiedName () const
StringRef getCppNamespace () const
ArrayRef< InterfaceMethod > getMethods () const
std::optional< StringRef > getDescription () const
std::optional< StringRef > getExtraClassDeclaration () const
std::optional< StringRef > getExtraTraitClassDeclaration () const
std::optional< StringRef > getExtraSharedClassDeclaration () const
std::optional< StringRef > getExtraClassOf () const
std::optional< StringRef > getVerify () const
auto getBaseInterfaces () const
bool verifyWithRegions () const
const llvm::Record & getDef () const
Detailed Description
Definition at line 80 of file Interfaces.h.
Constructor & Destructor Documentation
Interface() [1/2]
mlir::tblgen::Interface::Interface (const llvm::Record * def) explicit
Referenced by Interface().
Interface() [2/2]
mlir::tblgen::Interface::Interface (const Interface & rhs) inline
Definition at line 83 of file Interfaces.h.
References Interface(), and rhs.
Member Function Documentation
getBaseInterfaces()
auto mlir::tblgen::Interface::getBaseInterfaces () const inline
Definition at line 120 of file Interfaces.h.
getCppNamespace()
StringRef Interface::getCppNamespace () const
Definition at line 139 of file Interfaces.cpp.
Referenced by getFullyQualifiedName().
getDef()
const llvm::Record & mlir::tblgen::Interface::getDef () const inline
Definition at line 129 of file Interfaces.h.
Referenced by mlir::tblgen::AttrInterface::classof(), mlir::tblgen::DialectInterface::classof(), mlir::tblgen::OpInterface::classof(), and mlir::tblgen::TypeInterface::classof().
getDescription()
std::optional< StringRef > Interface::getDescription () const
Definition at line 147 of file Interfaces.cpp.
getExtraClassDeclaration()
std::optional< StringRef > Interface::getExtraClassDeclaration () const
Definition at line 153 of file Interfaces.cpp.
getExtraClassOf()
std::optional< StringRef > Interface::getExtraClassOf () const
Definition at line 170 of file Interfaces.cpp.
getExtraSharedClassDeclaration()
std::optional< StringRef > Interface::getExtraSharedClassDeclaration () const
Definition at line 165 of file Interfaces.cpp.
getExtraTraitClassDeclaration()
std::optional< StringRef > Interface::getExtraTraitClassDeclaration () const
Definition at line 159 of file Interfaces.cpp.
getFullyQualifiedName()
std::string Interface::getFullyQualifiedName () const
Definition at line 130 of file Interfaces.cpp.
References getCppNamespace(), and getName().
getMethods()
ArrayRef< InterfaceMethod > Interface::getMethods () const
Definition at line 144 of file Interfaces.cpp.
getName()
StringRef Interface::getName () const
Definition at line 125 of file Interfaces.cpp.
Referenced by getFullyQualifiedName().
getVerify()
std::optional< StringRef > Interface::getVerify () const
Definition at line 176 of file Interfaces.cpp.
verifyWithRegions()
bool Interface::verifyWithRegions () const
Definition at line 184 of file Interfaces.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Interfaces.h
lib/TableGen/Interfaces.cpp