MLIR: mlir::AttrTypeSubElementReplacements< T > Class Template Reference
mlir::AttrTypeSubElementReplacements< T > Class Template Reference
This class is used by AttrTypeSubElementHandler instances to process sub element replacements.
#include "mlir/IR/AttrTypeSubElements.h"
Public Member Functions
AttrTypeSubElementReplacements (ArrayRef< T > repls)
ArrayRef< T > take_front (unsigned n)
Take the first N replacements as an ArrayRef, dropping them from this replacement list.
Detailed Description
template<typename T>
class mlir::AttrTypeSubElementReplacements< T >
This class is used by AttrTypeSubElementHandler instances to process sub element replacements.
Definition at line 357 of file AttrTypeSubElements.h.
Constructor & Destructor Documentation
AttrTypeSubElementReplacements()
template<typename T> mlir::AttrTypeSubElementReplacements< T >::AttrTypeSubElementReplacements (ArrayRef< T > repls) inline
Definition at line 359 of file AttrTypeSubElements.h.
Member Function Documentation
take_front()
template<typename T> ArrayRef< T > mlir::AttrTypeSubElementReplacements< T >::take_front (unsigned n) inline
Take the first N replacements as an ArrayRef, dropping them from this replacement list.
Definition at line 363 of file AttrTypeSubElements.h.
Referenced by mlir::AttrTypeSubElementHandler< ArrayRef< T >, std::enable_if_t< has_sub_attr_or_type_v< T > > >::replace(), mlir::AttrTypeSubElementHandler< LLVM::detail::LLVMStructTypeStorage::Key >::replace(), mlir::AttrTypeSubElementHandler< Location >::replace(), mlir::AttrTypeSubElementHandler< NamedAttribute >::replace(), mlir::AttrTypeSubElementHandler< T, std::enable_if_t< std::is_base_of_v< Attribute, T >||std::is_base_of_v< Type, T > > >::replace(), and mlir::AttrTypeSubElementHandler< TypeRange >::replace().
The documentation for this class was generated from the following file:
include/mlir/IR/AttrTypeSubElements.h