MLIR: mlir::pdll::ods::OperandOrResult Class Reference
mlir::pdll::ods::OperandOrResult Class Reference
This class provides an ODS representation of a specific operation operand or result.
#include "mlir/Tools/PDLL/ODS/Operation.h"
Public Member Functions
StringRef getName () const
Return the name of this value.
bool isVariableLength () const
Returns true if this value is variable length, i.e.
bool isVariadic () const
Returns true if this value is variadic (Note this is false if the value is Optional).
VariableLengthKind getVariableLengthKind () const
Returns the variable length kind of this value.
const TypeConstraint & getConstraint () const
Return the constraint of this value.
Friends
class Operation
Allow access to the private constructor.
Detailed Description
This class provides an ODS representation of a specific operation operand or result.
This includes the name, variable length flags, and more.
Definition at line 74 of file Operation.h.
Member Function Documentation
getConstraint()
const TypeConstraint & mlir::pdll::ods::OperandOrResult::getConstraint () const inline
Return the constraint of this value.
Definition at line 97 of file Operation.h.
Referenced by mlir::pdll::ods::Context::print().
getName()
StringRef mlir::pdll::ods::OperandOrResult::getName () const inline
Return the name of this value.
Definition at line 77 of file Operation.h.
Referenced by mlir::pdll::ods::Context::print().
getVariableLengthKind()
VariableLengthKind mlir::pdll::ods::OperandOrResult::getVariableLengthKind () const inline
Returns the variable length kind of this value.
Definition at line 92 of file Operation.h.
Referenced by mlir::pdll::ods::Context::print().
isVariableLength()
bool mlir::pdll::ods::OperandOrResult::isVariableLength () const inline
Returns true if this value is variable length, i.e.
if it is Variadic or Optional.
Definition at line 81 of file Operation.h.
References mlir::pdll::ods::Single.
isVariadic()
bool mlir::pdll::ods::OperandOrResult::isVariadic () const inline
Returns true if this value is variadic (Note this is false if the value is Optional).
Definition at line 87 of file Operation.h.
References mlir::pdll::ods::Variadic.
Friends And Related Symbol Documentation
Operation
friend class Operation friend
Allow access to the private constructor.
Definition at line 115 of file Operation.h.
References Operation.
Referenced by Operation.
The documentation for this class was generated from the following file:
include/mlir/Tools/PDLL/ODS/Operation.h