MLIR: mlir::VectorType::Builder Class Reference
mlir::VectorType::Builder Class Reference
This is a builder type that keeps local references to arguments.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
Builder (VectorType other)
Build from another VectorType.
Builder (ArrayRef< int64_t > shape, Type elementType, ArrayRef< bool > scalableDims={})
Build from scratch.
Builder & setShape (ArrayRef< int64_t > newShape, ArrayRef< bool > newIsScalableDim={})
Builder & setElementType (Type newElementType)
Builder & dropDim (unsigned pos)
Erase a dim from shape @pos.
Builder & setDim (unsigned pos, int64_t val)
Set a dim in shape @pos to val.
operator VectorType ()
Detailed Description
This is a builder type that keeps local references to arguments.
Arguments that are passed into the builder must outlive the builder.
Definition at line 286 of file BuiltinTypes.h.
Constructor & Destructor Documentation
Builder() [1/2]
mlir::VectorType::Builder::Builder (VectorType other) inline explicit
Build from another VectorType.
Definition at line 289 of file BuiltinTypes.h.
References getElementType(), and getShape().
Referenced by dropDim(), setDim(), setElementType(), and setShape().
Builder() [2/2]
mlir::VectorType::Builder::Builder (ArrayRef< int64_t > shape, Type elementType, ArrayRef< bool > scalableDims = {}) inline
Build from scratch.
Definition at line 294 of file BuiltinTypes.h.
Member Function Documentation
dropDim()
Builder & mlir::VectorType::Builder::dropDim (unsigned pos) inline
Erase a dim from shape @pos.
Definition at line 311 of file BuiltinTypes.h.
References Builder().
Referenced by reshapeLoad(), reshapeStore(), and mlir::vector::unrollVectorOp().
operator VectorType()
mlir::VectorType::Builder::operator VectorType () inline
Definition at line 326 of file BuiltinTypes.h.
setDim()
Builder & mlir::VectorType::Builder::setDim (unsigned pos, int64_t val) inline
Set a dim in shape @pos to val.
Definition at line 320 of file BuiltinTypes.h.
References Builder().
Referenced by mlir::arm_sve::impl::LegalizeVectorStorageBase< DerivedT >::clonePass().
setElementType()
Builder & mlir::VectorType::Builder::setElementType (Type newElementType) inline
Definition at line 305 of file BuiltinTypes.h.
References Builder().
setShape()
Builder & mlir::VectorType::Builder::setShape (ArrayRef< int64_t > newShape, ArrayRef< bool > newIsScalableDim = {}) inline
Definition at line 298 of file BuiltinTypes.h.
References Builder().
The documentation for this class was generated from the following file:
include/mlir/IR/BuiltinTypes.h