MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation Class Reference
Used in function arguments when None should resolve to the current context manager set instance.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
operator MlirLocation () const
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting (ReferrentTy &referrent)
Public Member Functions inherited from mlir::python::Defaulting< DefaultingPyLocation, PyLocation >
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
ReferrentTy * get () const
ReferrentTy * operator-> ()
Static Public Member Functions
static PyLocation & resolve ()
Static Public Attributes
static constexpr const char kTypeDescription [] = "_mlir.ir.Location"
Additional Inherited Members
Public Types inherited from mlir::python::Defaulting< DefaultingPyLocation, PyLocation >
using ReferrentTy
Detailed Description
Used in function arguments when None should resolve to the current context manager set instance.
Definition at line 540 of file IRCore.h.
Member Function Documentation
Defaulting() [1/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting () default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting() [2/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting (ReferrentTy & referrent) inline
Definition at line 108 of file NanobindUtils.h.
operator MlirLocation()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation::operator MlirLocation () const inline
Definition at line 547 of file IRCore.h.
References mlir::python::Defaulting< DefaultingPyLocation, PyLocation >::get().
resolve()
PyLocation & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation::resolve () static
Definition at line 846 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadContextEntry::popLocation().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::createBlock(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::inferReturnTypeComponents(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferTypeOpInterface::inferReturnTypes().
Member Data Documentation
kTypeDescription
const char mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation::kTypeDescription[] = "_mlir.ir.Location" static constexpr
Definition at line 544 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp