MLIR: mlir::tblgen::OpMethod Class Reference
mlir::tblgen::OpMethod Class Reference
#include "mlir/TableGen/OpClass.h"
Public Types
enum Property {
MP_None = 0x0, MP_Static = 0x1, MP_Constructor = 0x2, MP_Private = 0x4,
MP_Declaration = 0x8, MP_Inline = 0x10, MP_Constexpr = 0x20 | MP_Inline, MP_StaticDeclaration = MP_Static | MP_Declaration
}
Public Member Functions
template<typename... Args>
OpMethod (StringRef retType, StringRef name, Property property, unsigned id, Args &&...args)
OpMethod (OpMethod &&)=default
virtual ~OpMethod ()=default
OpMethodBody & body ()
bool isStatic () const
bool isPrivate () const
bool isInline () const
StringRef getName () const
unsigned getID () const
bool makesRedundant (const OpMethod &other) const
virtual void writeDeclTo (raw_ostream &os) const
virtual void writeDefTo (raw_ostream &os, StringRef namePrefix) const
Protected Attributes
Property properties
OpMethodSignature methodSignature
OpMethodBody methodBody
const unsigned id
Detailed Description
Definition at line 231 of file OpClass.h.
Member Enumeration Documentation
Property
enum mlir::tblgen::OpMethod::Property
Enumerator
MP_None
MP_Static
MP_Constructor
MP_Private
MP_Declaration
MP_Inline
MP_Constexpr
MP_StaticDeclaration
Definition at line 235 of file OpClass.h.
Constructor & Destructor Documentation
OpMethod() [1/2]
template<typename... Args> mlir::tblgen::OpMethod::OpMethod (StringRef retType, StringRef name, Property property, unsigned id, Args &&... args) inline
Definition at line 247 of file OpClass.h.
OpMethod() [2/2]
mlir::tblgen::OpMethod::OpMethod (OpMethod &&) default
~OpMethod()
virtual mlir::tblgen::OpMethod::~OpMethod () virtual default
Member Function Documentation
body()
OpMethodBody& mlir::tblgen::OpMethod::body () inline
Definition at line 257 of file OpClass.h.
getID()
unsigned mlir::tblgen::OpMethod::getID () const inline
Definition at line 272 of file OpClass.h.
getName()
StringRef mlir::tblgen::OpMethod::getName () const inline
Definition at line 269 of file OpClass.h.
isInline()
bool mlir::tblgen::OpMethod::isInline () const inline
Definition at line 266 of file OpClass.h.
isPrivate()
bool mlir::tblgen::OpMethod::isPrivate () const inline
Definition at line 263 of file OpClass.h.
Referenced by mlir::tblgen::Class::writeDeclTo(), and mlir::tblgen::OpClass::writeDeclTo().
isStatic()
bool mlir::tblgen::OpMethod::isStatic () const inline
Definition at line 260 of file OpClass.h.
makesRedundant()
bool mlir::tblgen::OpMethod::makesRedundant (const OpMethod & other) const inline
Definition at line 275 of file OpClass.h.
References methodSignature, mlir::tblgen::OpMethodParameter::writeDeclTo(), and mlir::tblgen::OpMethodParameter::writeDefTo().
writeDeclTo()
void OpMethod::writeDeclTo (raw_ostream & os) const virtual
Definition at line 200 of file OpClass.cpp.
Referenced by mlir::tblgen::Class::writeDeclTo(), and mlir::tblgen::OpClass::writeDeclTo().
writeDefTo()
void OpMethod::writeDefTo (raw_ostream & os, StringRef namePrefix) const virtual
Reimplemented in mlir::tblgen::OpConstructor.
Definition at line 216 of file OpClass.cpp.
Referenced by mlir::tblgen::Class::writeDefTo().
Member Data Documentation
id
const unsigned mlir::tblgen::OpMethod::id protected
Definition at line 291 of file OpClass.h.
methodBody
OpMethodBody mlir::tblgen::OpMethod::methodBody protected
Definition at line 290 of file OpClass.h.
methodSignature
OpMethodSignature mlir::tblgen::OpMethod::methodSignature protected
Definition at line 289 of file OpClass.h.
Referenced by makesRedundant().
properties
Property mlir::tblgen::OpMethod::properties protected
Definition at line 288 of file OpClass.h.
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp