MLIR: mlir::pdll::ast::OperationType Class Reference
mlir::pdll::ast::OperationType Class Reference
This class represents a PDLL type that corresponds to an mlir::Operation.
#include "mlir/Tools/PDLL/AST/Types.h"
Public Member Functions
std::optional< StringRef > getName () const
Return the name of this operation type, or std::nullopt if it doesn't have on.
const ods::Operation * getODSOperation () const
Return the ODS operation that this type refers to, or nullptr if the ODS operation is unknown.
Public Member Functions inherited from mlir::pdll::ast::Type
Type (Storage *impl=nullptr)
bool operator== (const Type &other) const
bool operator!= (const Type &other) const
operator bool () const
Storage * getImpl () const
Return the internal storage instance of this type.
TypeID getTypeID () const
Return the TypeID instance of this type.
void print (raw_ostream &os) const
Print this type to the given stream.
Type refineWith (Type other) const
Try to refine this type with the one provided.
Static Public Member Functions
static OperationType get (Context &context, std::optional< StringRef > name=std::nullopt, const ods::Operation *odsOp=nullptr)
Return an instance of the Operation type with an optional operation name.
Static Public Member Functions inherited from mlir::pdll::ast::Type::TypeBase< detail::OperationTypeStorage >
static bool classof (Type type)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Type::TypeBase< detail::OperationTypeStorage >
using Base = TypeBase< detail::OperationTypeStorage, Type >
using ImplTy = detail::OperationTypeStorage
Protected Member Functions inherited from mlir::pdll::ast::Type
template<typename T >
const T * getImplAs () const
Return the internal storage instance of this type reinterpreted as the given derived storage type.
Detailed Description
This class represents a PDLL type that corresponds to an mlir::Operation.
Definition at line 134 of file Types.h.
Member Function Documentation
get()
OperationType OperationType::get (Context & context, std::optional< StringRef > name = std::nullopt, const ods::Operation * odsOp = nullptr) static
Return an instance of the Operation type with an optional operation name.
If no name is provided, this type may refer to any operation.
Definition at line 73 of file Types.cpp.
References mlir::StorageUniquer::get(), and mlir::pdll::ast::Context::getTypeUniquer().
Referenced by mlir::pdll::ast::OperationExpr::create().
getName()
std::optional< StringRef > OperationType::getName () const
Return the name of this operation type, or std::nullopt if it doesn't have on.
Definition at line 81 of file Types.cpp.
getODSOperation()
const ods::Operation * OperationType::getODSOperation () const
Return the ODS operation that this type refers to, or nullptr if the ODS operation is unknown.
Definition at line 87 of file Types.cpp.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Types.h
lib/Tools/PDLL/AST/Types.cpp