MLIR: mlir::ConstantIndexOp Class Reference
mlir::ConstantIndexOp Class Reference
This is a refinement of the "constant" op for the case where it is returning an integer value of Index type.
#include "mlir/Dialect/StandardOps/IR/Ops.h"
Public Member Functions
int64_t getValue ()
Static Public Member Functions
static void build (OpBuilder &builder, OperationState &result, int64_t value)
Build a constant int op producing an index.
static bool classof (Operation *op)
ConstantIndexOp only matches values whose result type is Index.
Detailed Description
This is a refinement of the "constant" op for the case where it is returning an integer value of Index type.
%1 = "std.constant"(){value: 99} : () -> index
Definition at line 93 of file Ops.h.
Member Function Documentation
build()
void ConstantIndexOp::build (OpBuilder & builder, OperationState & result, int64_t value) static
Build a constant int op producing an index.
Definition at line 1287 of file Ops.cpp.
References areVectorCastSimpleCompatible(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), mlir::ShapedType::getElementType(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::ShapedType::getShape(), mlir::RewritePatternSet::insert(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::Type::isSignlessInteger(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
classof()
bool ConstantIndexOp::classof (Operation * op) static
ConstantIndexOp only matches values whose result type is Index.
Definition at line 1283 of file Ops.cpp.
References mlir::Operation::getResult(), mlir::Value::getType(), and mlir::Type::isIndex().
getValue()
int64_t mlir::ConstantIndexOp::getValue () inline
Definition at line 100 of file Ops.h.
References mlir::applyCmpPredicate(), mlir::ConstantFloatOp::classof(), mlir::getIdentityValue(), mlir::getIdentityValueAttr(), mlir::getReductionOp(), kind, loc, and op.
Referenced by buildAffineLoopFromValues(), foldTransferInBoundsAttribute(), isInBounds(), mlir::loopUnrollByFactor(), and mlir::promoteIfSingleIteration().
The documentation for this class was generated from the following files:
include/mlir/Dialect/StandardOps/IR/Ops.h
lib/Dialect/StandardOps/IR/Ops.cpp