MLIR: mlir::query::matcher::Registry Class Reference
mlir::query::matcher::Registry Class Reference
#include "mlir/Query/Matcher/Registry.h"
Public Member Functions
Registry ()=default
~Registry ()=default
const ConstructorMap & constructors () const
template<typename MatcherType >
void registerMatcher (const std::string &name, MatcherType matcher)
Detailed Description
Definition at line 28 of file Registry.h.
Constructor & Destructor Documentation
Registry()
mlir::query::matcher::Registry::Registry () default
~Registry()
mlir::query::matcher::Registry::~Registry () default
Member Function Documentation
constructors()
const ConstructorMap& mlir::query::matcher::Registry::constructors () const inline
Definition at line 33 of file Registry.h.
Referenced by mlir::query::matcher::RegistryManager::getMatcherCompletions(), and mlir::query::matcher::RegistryManager::lookupMatcherCtor().
registerMatcher()
template<typename MatcherType > void mlir::query::matcher::Registry::registerMatcher (const std::string & name, MatcherType matcher) inline
Definition at line 36 of file Registry.h.
References mlir::query::matcher::internal::makeMatcherAutoMarshall().
The documentation for this class was generated from the following files:
include/mlir/Query/Matcher/Registry.h
lib/Query/Matcher/RegistryManager.cpp