MLIR: mlir::spirv::JointMatrixINTELType Class Reference
mlir::spirv::JointMatrixINTELType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
Type getElementType () const
Scope getScope () const
Return the scope of the joint matrix.
unsigned getRows () const
return the number of rows of the matrix.
unsigned getColumns () const
return the number of columns of the matrix.
MatrixLayout getMatrixLayout () const
return the layout of the matrix
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, std::optional< StorageClass > storage=std::nullopt)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, std::optional< StorageClass > storage=std::nullopt)
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static JointMatrixINTELType get (Type elementType, Scope scope, unsigned rows, unsigned columns, MatrixLayout matrixLayout)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.jointmatrix"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verify (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 424 of file SPIRVTypes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 101 of file StorageUniquerSupport.h.
Member Function Documentation
get()
JointMatrixINTELType JointMatrixINTELType::get (Type elementType, Scope scope, unsigned rows, unsigned columns, MatrixLayout matrixLayout) static
Definition at line 298 of file SPIRVTypes.cpp.
References mlir::get(), and mlir::Type::getContext().
Referenced by parseJointMatrixType().
getCapabilities()
void JointMatrixINTELType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, std::optional< StorageClass > storage = std::nullopt)
Definition at line 328 of file SPIRVTypes.cpp.
References getElementType().
getColumns()
unsigned JointMatrixINTELType::getColumns () const
return the number of columns of the matrix.
Definition at line 313 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by print().
getElementType()
Type JointMatrixINTELType::getElementType () const
Definition at line 305 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by getCapabilities(), getExtensions(), and print().
getExtensions()
void JointMatrixINTELType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, std::optional< StorageClass > storage = std::nullopt)
Definition at line 319 of file SPIRVTypes.cpp.
References getElementType().
getMatrixLayout()
MatrixLayout JointMatrixINTELType::getMatrixLayout () const
return the layout of the matrix
Definition at line 315 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by print().
getRows()
unsigned JointMatrixINTELType::getRows () const
return the number of rows of the matrix.
Definition at line 311 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by print().
getScope()
Scope JointMatrixINTELType::getScope () const
Return the scope of the joint matrix.
Definition at line 309 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by print().
Member Data Documentation
name
constexpr StringLiteral mlir::spirv::JointMatrixINTELType::name = "spirv.jointmatrix" static constexpr
Definition at line 430 of file SPIRVTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp