MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter Class Reference
Public Member Functions
PyTypeConverter ()
PyTypeConverter (MlirTypeConverter typeConverter)
~PyTypeConverter ()
void addConversion (const nb::callable &convert)
nb::typed< nb::object, std::optional< PyType > > convertType (PyType &type)
MlirTypeConverter get ()
Detailed Description
Definition at line 167 of file Rewrite.cpp.
Constructor & Destructor Documentation
PyTypeConverter() [1/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::PyTypeConverter () inline
Definition at line 169 of file Rewrite.cpp.
References mlirTypeConverterCreate(), and true.
PyTypeConverter() [2/2]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::PyTypeConverter (MlirTypeConverter typeConverter) inline
Definition at line 170 of file Rewrite.cpp.
References false.
~PyTypeConverter()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::~PyTypeConverter () inline
Definition at line 172 of file Rewrite.cpp.
References mlirTypeConverterDestroy().
Member Function Documentation
addConversion()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::addConversion (const nb::callable & convert) inline
Definition at line 177 of file Rewrite.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlirLogicalResultFailure(), mlirLogicalResultSuccess(), mlirTypeConverterAddConversion(), and mlirTypeGetContext().
convertType()
nb::typed< nb::object, std::optional< PyType > > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::convertType (PyType & type) inline
Definition at line 194 of file Rewrite.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::maybeDownCast(), mlirTypeConverterConvertType(), mlirTypeGetContext(), and mlirTypeIsNull().
get()
MlirTypeConverter mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeConverter::get () inline
Definition at line 203 of file Rewrite.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::addConversion().
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.cpp