MLIR: mlir::quant::UniformQuantizedType Class Reference
mlir::quant::UniformQuantizedType Class Reference
Represents a family of uniform, quantized types.
#include "mlir/Dialect/Quant/IR/QuantTypes.h"
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
using HasTraitFn = bool(*)(TypeID)
Public Member Functions
double getScale () const
Gets the scale term.
int64_t getZeroPoint () const
Gets the storage value corresponding to the real value 0 in the affine equation.
bool isFixedPoint () const
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static UniformQuantizedType get (unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all parameters specified but not checked.
static UniformQuantizedType getChecked (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all specified parameters checked.
static LogicalResult verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Verifies construction invariants and issues errors/warnings.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "quant.uniform"
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents a family of uniform, quantized types.
Each instance of this type expresses a mapping between real values (most often expressed in floating point f32) and quantized values (either fixed point or affine).
The relationship is: real_value = scale * (quantized_value - zero_point)
It is used as part of high level graph transformations that have the goal of re-expressing parts of a computation in terms of this common form for more efficient execution at runtime. In addition, it is designed to be expressive enough to facilitate lowering to precise types and operations in target hardware.
As a high-level type, focused on intermediate passes, this type holds opinions consistent with high-level usage. If lowering math kernels below the high level arithmetic ops (i.e. to LLVM IR or hardware specific instruction sets), it is expected that the information expressed here will be used to drive low level codegen and target specific type selection, but this type will likely be erased in the process.
Syntax synopsis: Per-layer, all parameters expressed: !quant<uniform[StorageType:ExpressedType]{Scale:ZeroPoint}> Per-layer, optional parameters omitted: !quant<uniform[StorageType]{Scale}>
StorageType: 'i'|'u' NumBits ExpressedType: 'f16', 'f32', 'bf16', 'f64' Scale: A legal double value ZeroPoint: An integer value
Definition at line 260 of file QuantTypes.h.
Member Typedef Documentation
Base
using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 100 of file StorageUniquerSupport.h.
Member Function Documentation
get()
UniformQuantizedType UniformQuantizedType::get (unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all parameters specified but not checked.
Definition at line 280 of file QuantTypes.cpp.
References mlir::get(), and mlir::Type::getContext().
Referenced by mlirUniformQuantizedTypeGet().
getChecked() [1/3]
template<typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked (typename... Args) inline static
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
If the arguments provided are invalid, errors are emitted using the provided location and a null object is returned.
Definition at line 189 of file StorageUniquerSupport.h.
getChecked() [2/3]
UniformQuantizedType UniformQuantizedType::getChecked (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all specified parameters checked.
Returns a nullptr convertible type on failure.
Definition at line 289 of file QuantTypes.cpp.
References mlir::emitError(), and mlir::Type::getContext().
Referenced by mlir::quant::fakeQuantAttrsToType().
getChecked() [3/3]
template<typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked (typename... Args) inline static
Get or create a new ConcreteT instance within the ctx.
If the arguments provided are invalid, errors are emitted using the provided emitError and a null object is returned.
Definition at line 198 of file StorageUniquerSupport.h.
getScale()
double UniformQuantizedType::getScale () const
Gets the scale term.
The scale designates the difference between the real values corresponding to consecutive quantized values differing by 1.
Definition at line 329 of file QuantTypes.cpp.
Referenced by printUniformQuantizedType().
getZeroPoint()
int64_t UniformQuantizedType::getZeroPoint () const
Gets the storage value corresponding to the real value 0 in the affine equation.
Definition at line 331 of file QuantTypes.cpp.
Referenced by isFixedPoint(), and printUniformQuantizedType().
isFixedPoint()
bool mlir::quant::UniformQuantizedType::isFixedPoint () const inline
Definition at line 303 of file QuantTypes.h.
References getZeroPoint().
verifyInvariants()
LogicalResult UniformQuantizedType::verifyInvariants (function_ref< InFlightDiagnostic()> emitError, unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax) static
Verifies construction invariants and issues errors/warnings.
Definition at line 298 of file QuantTypes.cpp.
References mlir::emitError(), and mlir::quant::QuantizedType::verifyInvariants().
Member Data Documentation
name
constexpr StringLiteral mlir::quant::UniformQuantizedType::name = "quant.uniform" static constexpr
Definition at line 267 of file QuantTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Quant/IR/QuantTypes.h
lib/Dialect/Quant/IR/QuantTypes.cpp