MLIR: mlir::BytecodeDialectInterface Class Reference
mlir::BytecodeDialectInterface Class Reference
#include "mlir/Bytecode/BytecodeImplementation.h"
Public Member Functions
virtual Attribute readAttribute (DialectBytecodeReader &reader) const
Read an attribute belonging to this dialect from the given reader.
virtual Type readType (DialectBytecodeReader &reader) const
Read a type belonging to this dialect from the given reader.
virtual LogicalResult writeAttribute (Attribute attr, DialectBytecodeWriter &writer) const
Write the given attribute, which belongs to this dialect, to the given writer.
virtual LogicalResult writeType (Type type, DialectBytecodeWriter &writer) const
Write the given type, which belongs to this dialect, to the given writer.
virtual void writeVersion (DialectBytecodeWriter &writer) const
Write the version of this dialect to the given writer.
virtual std::unique_ptr< DialectVersion > readVersion (DialectBytecodeReader &reader) const
virtual LogicalResult upgradeFromVersion (Operation *topLevelOp, const DialectVersion &version) const
Hook invoked after parsing completed, if a version directive was present and included an entry for the current dialect.
Public Member Functions inherited from mlir::DialectInterface
virtual ~DialectInterface ()
Dialect * getDialect () const
Return the dialect that this interface represents.
MLIRContext * getContext () const
Return the context that holds the parent dialect of this interface.
TypeID getID () const
Return the derived interface id.
Additional Inherited Members
Public Types inherited from mlir::detail::DialectInterfaceBase< ConcreteType, DialectInterface >
using Base
Public Types inherited from mlir::DialectInterface
template<typename ConcreteType>
using Base = detail::DialectInterfaceBase<ConcreteType, DialectInterface>
The base class used for all derived interface types.
Static Public Member Functions inherited from mlir::detail::DialectInterfaceBase< ConcreteType, DialectInterface >
static TypeID getInterfaceID ()
Get a unique id for the derived interface type.
Protected Member Functions inherited from mlir::detail::DialectInterfaceBase< ConcreteType, DialectInterface >
DialectInterfaceBase (Dialect *dialect)
Protected Member Functions inherited from mlir::DialectInterface
DialectInterface (Dialect *dialect, TypeID id)
Detailed Description
Definition at line 421 of file BytecodeImplementation.h.
Member Function Documentation
readAttribute()
virtual Attribute mlir::BytecodeDialectInterface::readAttribute (DialectBytecodeReader & reader) const inline virtual
Read an attribute belonging to this dialect from the given reader.
This method should return null in the case of failure. Optionally, the dialect version can be accessed through the reader.
Definition at line 433 of file BytecodeImplementation.h.
References mlir::DialectBytecodeReader::emitError(), mlir::DialectInterface::getDialect(), and mlir::Dialect::getNamespace().
readType()
virtual Type mlir::BytecodeDialectInterface::readType (DialectBytecodeReader & reader) const inline virtual
Read a type belonging to this dialect from the given reader.
This method should return null in the case of failure. Optionally, the dialect version can be accessed thorugh the reader.
Definition at line 442 of file BytecodeImplementation.h.
References mlir::DialectBytecodeReader::emitError(), mlir::DialectInterface::getDialect(), and mlir::Dialect::getNamespace().
readVersion()
virtual std::unique_ptr< DialectVersion > mlir::BytecodeDialectInterface::readVersion (DialectBytecodeReader & reader) const inline virtual
Definition at line 476 of file BytecodeImplementation.h.
References mlir::DialectBytecodeReader::emitError().
upgradeFromVersion()
virtual LogicalResult mlir::BytecodeDialectInterface::upgradeFromVersion (Operation * topLevelOp, const DialectVersion & version) const inline virtual
Hook invoked after parsing completed, if a version directive was present and included an entry for the current dialect.
This hook offers the opportunity to the dialect to visit the IR and upgrades constructs emitted by the version of the dialect corresponding to the provided version.
Definition at line 486 of file BytecodeImplementation.h.
References success().
writeAttribute()
virtual LogicalResult mlir::BytecodeDialectInterface::writeAttribute (Attribute attr, DialectBytecodeWriter & writer) const inline virtual
Write the given attribute, which belongs to this dialect, to the given writer.
This method may return failure to indicate that the given attribute could not be encoded, in which case the textual format will be used to encode this attribute instead.
Definition at line 456 of file BytecodeImplementation.h.
writeType()
virtual LogicalResult mlir::BytecodeDialectInterface::writeType (Type type, DialectBytecodeWriter & writer) const inline virtual
Write the given type, which belongs to this dialect, to the given writer.
This method may return failure to indicate that the given type could not be encoded, in which case the textual format will be used to encode this type instead.
Definition at line 465 of file BytecodeImplementation.h.
writeVersion()
virtual void mlir::BytecodeDialectInterface::writeVersion (DialectBytecodeWriter & writer) const inline virtual
Write the version of this dialect to the given writer.
Definition at line 471 of file BytecodeImplementation.h.
The documentation for this class was generated from the following file:
include/mlir/Bytecode/BytecodeImplementation.h