MLIR: mlir::python::PyMlirContext Class Reference
mlir::python::PyMlirContext Class Reference
#include "Bindings/Python/IRModule.h"
Classes
struct ErrorCapture
RAII object that captures any error diagnostics emitted to the provided context.
Public Member Functions
PyMlirContext ()=delete
PyMlirContext (MlirContext context)
PyMlirContext (const PyMlirContext &)=delete
PyMlirContext (PyMlirContext &&)=delete
~PyMlirContext ()
MlirContext get ()
Accesses the underlying MlirContext.
PyMlirContextRef getRef ()
Gets a strong reference to this context, which will ensure it is kept alive for the life of the reference.
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirContext.
std::vector< PyOperation * > getLiveOperationObjects ()
Get a list of Python objects which are still in the live context map.
size_t getLiveOperationCount ()
Gets the count of live operations associated with this context.
size_t clearLiveOperations ()
Clears the live operations map, returning the number of entries which were invalidated.
void clearOperation (MlirOperation op)
Removes an operation from the live operations map and sets it invalid.
void clearOperationsInside (PyOperationBase &op)
Clears all operations nested inside the given op using clearOperation(MlirOperation).
void clearOperationsInside (MlirOperation op)
void clearOperationAndInside (PyOperationBase &op)
Clears the operaiton and all operations inside using clearOperation(MlirOperation).
size_t getLiveModuleCount ()
Gets the count of live modules associated with this context.
void contextExit (const nanobind::object &excType, const nanobind::object &excVal, const nanobind::object &excTb)
nanobind::object attachDiagnosticHandler (nanobind::object callback)
Attaches a Python callback as a diagnostic handler, returning a registration object (internally a PyDiagnosticHandler).
void setEmitErrorDiagnostics (bool value)
Controls whether error diagnostics should be propagated to diagnostic handlers, instead of being captured by ErrorCapture.
Static Public Member Functions
static PyMlirContext * createNewContextForInit ()
For the case of a python init (nanobind::init) method, pybind11 is quite strict about needing to return a pointer that is not yet associated to an nanobind::object.
static PyMlirContextRef forContext (MlirContext context)
Returns a context reference for the singleton PyMlirContext wrapper for the given context.
static nanobind::object createFromCapsule (nanobind::object capsule)
Creates a PyMlirContext from the MlirContext wrapped by a capsule.
static size_t getLiveCount ()
Gets the count of live context objects. Used for testing.
static nanobind::object contextEnter (nanobind::object context)
Enter and exit the context manager.
Friends
class PyModule
class PyOperation
Detailed Description
Definition at line 188 of file IRModule.h.
Constructor & Destructor Documentation
PyMlirContext() [1/4]
mlir::python::PyMlirContext::PyMlirContext () delete
Referenced by forContext().
PyMlirContext() [2/4]
PyMlirContext::PyMlirContext (MlirContext context)
Definition at line 648 of file IRCore.cpp.
PyMlirContext() [3/4]
mlir::python::PyMlirContext::PyMlirContext (const PyMlirContext &) delete
PyMlirContext() [4/4]
mlir::python::PyMlirContext::PyMlirContext (PyMlirContext &&) delete
~PyMlirContext()
PyMlirContext::~PyMlirContext ()
Definition at line 655 of file IRCore.cpp.
References mlirContextDestroy().
Member Function Documentation
attachDiagnosticHandler()
nb::object PyMlirContext::attachDiagnosticHandler (nanobind::object callback)
Attaches a Python callback as a diagnostic handler, returning a registration object (internally a PyDiagnosticHandler).
Definition at line 796 of file IRCore.cpp.
References get(), mlir::python::PyDiagnostic::invalidate(), mlirContextAttachDiagnosticHandler(), mlirLogicalResultFailure(), and mlirLogicalResultSuccess().
clearLiveOperations()
size_t PyMlirContext::clearLiveOperations ()
Clears the live operations map, returning the number of entries which were invalidated.
To be used as a safety mechanism so that API end-users can't corrupt by holding references they shouldn't have accessed in the first place.
Definition at line 721 of file IRCore.cpp.
clearOperation()
void PyMlirContext::clearOperation (MlirOperation op)
Removes an operation from the live operations map and sets it invalid.
This is useful for when some non-bindings code destroys the operation and the bindings need to made aware. For example, in the case when pass manager is run.
Note that this does NOT clear the nested operations.
Definition at line 734 of file IRCore.cpp.
References mlir::python::PyOperation::setInvalid().
Referenced by clearOperationAndInside(), and mlir::python::PyOperation::~PyOperation().
clearOperationAndInside()
void PyMlirContext::clearOperationAndInside (PyOperationBase & op)
Clears the operaiton and all operations inside using clearOperation(MlirOperation).
Definition at line 773 of file IRCore.cpp.
References clearOperation(), mlir::python::BaseContextObject::getContext(), mlir::python::PyOperationBase::getOperation(), mlirOperationWalk(), MlirWalkPreOrder, and MlirWalkResultAdvance.
Referenced by mlir::python::PyOperation::erase().
clearOperationsInside() [1/2]
void PyMlirContext::clearOperationsInside (MlirOperation op)
Definition at line 768 of file IRCore.cpp.
References clearOperationsInside(), mlir::python::PyOperation::forOperation(), mlir::python::PyOperation::getOperation(), and getRef().
clearOperationsInside() [2/2]
void PyMlirContext::clearOperationsInside (PyOperationBase & op)
Clears all operations nested inside the given op using clearOperation(MlirOperation).
Definition at line 748 of file IRCore.cpp.
References mlir::python::PyOperationBase::getOperation(), mlirOperationWalk(), MlirWalkPreOrder, and MlirWalkResultAdvance.
Referenced by clearOperationsInside().
contextEnter()
nb::object PyMlirContext::contextEnter (nanobind::object context) static
Enter and exit the context manager.
Definition at line 786 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::pushContext().
contextExit()
void PyMlirContext::contextExit (const nanobind::object & excType, const nanobind::object & excVal, const nanobind::object & excTb)
Definition at line 790 of file IRCore.cpp.
References mlir::python::PyThreadContextEntry::popContext().
createFromCapsule()
nb::object PyMlirContext::createFromCapsule (nanobind::object capsule) static
Creates a PyMlirContext from the MlirContext wrapped by a capsule.
Note that PyMlirContext instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirContext is taken by calling this function.
Definition at line 671 of file IRCore.cpp.
References forContext(), mlirContextIsNull(), mlirPythonCapsuleToContext(), and mlir::python::PyObjectRef< T >::releaseObject().
createNewContextForInit()
static PyMlirContext* mlir::python::PyMlirContext::createNewContextForInit () static
For the case of a python init (nanobind::init) method, pybind11 is quite strict about needing to return a pointer that is not yet associated to an nanobind::object.
Since the forContext() method acts like a pool, possibly returning a recycled context, it does not satisfy this need. The usual way in python to accomplish such a thing is to override new, but that is also not supported by pybind11. Instead, we use this entry point which always constructs a fresh context (which cannot alias an existing one because it is fresh).
forContext()
PyMlirContextRef PyMlirContext::forContext (MlirContext context) static
Returns a context reference for the singleton PyMlirContext wrapper for the given context.
Definition at line 678 of file IRCore.cpp.
References PyMlirContext().
Referenced by createFromCapsule(), mlir::python::PyLocation::createFromCapsule(), mlir::python::PyOperation::createFromCapsule(), mlir::python::PyType::createFromCapsule(), mlir::python::PyAttribute::createFromCapsule(), mlir::python::PyValue::createFromCapsule(), mlir::python::PyAffineExpr::createFromCapsule(), mlir::python::PyAffineMap::createFromCapsule(), mlir::python::PyIntegerSet::createFromCapsule(), mlir::python::PyModule::forModule(), and mlir::python::PyDiagnostic::getLocation().
get()
MlirContext mlir::python::PyMlirContext::get () inline
Accesses the underlying MlirContext.
Definition at line 211 of file IRModule.h.
Referenced by attachDiagnosticHandler(), mlir::python::PyOpView::buildGeneric(), getCapsule(), mlir::python::PyInferShapedTypeOpInterface::inferReturnTypeComponents(), mlir::python::PyInferTypeOpInterface::inferReturnTypes(), mlir::python::PyOperation::parse(), mlir::python::PyConcreteOpInterface< ConcreteIface >::PyConcreteOpInterface(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), and mlir::python::PyMlirContext::ErrorCapture::~ErrorCapture().
getCapsule()
nb::object PyMlirContext::getCapsule ()
Gets a capsule wrapping the void* within the MlirContext.
Definition at line 667 of file IRCore.cpp.
References get(), and mlirPythonContextToCapsule().
getLiveCount()
size_t PyMlirContext::getLiveCount () static
Gets the count of live context objects. Used for testing.
Definition at line 703 of file IRCore.cpp.
getLiveModuleCount()
size_t PyMlirContext::getLiveModuleCount ()
Gets the count of live modules associated with this context.
Used for testing.
Definition at line 784 of file IRCore.cpp.
getLiveOperationCount()
size_t PyMlirContext::getLiveOperationCount ()
Gets the count of live operations associated with this context.
Used for testing.
Definition at line 708 of file IRCore.cpp.
getLiveOperationObjects()
std::vector< PyOperation * > PyMlirContext::getLiveOperationObjects ()
Get a list of Python objects which are still in the live context map.
Definition at line 713 of file IRCore.cpp.
getRef()
PyMlirContextRef mlir::python::PyMlirContext::getRef () inline
Gets a strong reference to this context, which will ensure it is kept alive for the life of the reference.
Definition at line 215 of file IRModule.h.
Referenced by clearOperationsInside().
setEmitErrorDiagnostics()
void mlir::python::PyMlirContext::setEmitErrorDiagnostics (bool value) inline
Controls whether error diagnostics should be propagated to diagnostic handlers, instead of being captured by ErrorCapture.
Definition at line 277 of file IRModule.h.
Friends And Related Function Documentation
PyModule
friend class PyModule friend
Definition at line 313 of file IRModule.h.
PyOperation
friend class PyOperation friend
Definition at line 314 of file IRModule.h.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp