MLIR: mlir::vector::CombiningKindAttr Class Reference
mlir::vector::CombiningKindAttr Class Reference
An attribute that specifies the combining function for vector.contract, and vector.reduction.
#include "mlir/Dialect/Vector/VectorOps.h"
Public Member Functions
CombiningKind getKind () const
void print (DialectAsmPrinter &p) const
Static Public Member Functions
static CombiningKindAttr get (CombiningKind kind, MLIRContext *context)
static Attribute parse (DialectAsmParser &parser)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verify (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that specifies the combining function for vector.contract, and vector.reduction.
Definition at line 92 of file VectorOps.h.
Member Function Documentation
get()
CombiningKindAttr CombiningKindAttr::get (CombiningKind kind, MLIRContext * context) static
Definition at line 140 of file VectorOps.cpp.
Referenced by mlir::vector::getVectorReductionOp(), mlir::vector::getVectorSubscriptAttr(), parse(), parseContractionOp(), and parseOuterProductOp().
getKind()
CombiningKind CombiningKindAttr::getKind () const
Definition at line 145 of file VectorOps.cpp.
parse()
Attribute CombiningKindAttr::parse (DialectAsmParser & parser) static
Definition at line 171 of file VectorOps.cpp.
References mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::DialectAsmParser::emitError(), mlir::failed(), get(), mlir::DialectAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::DialectAsmParser::getNameLoc(), kind, loc, materializeConstant(), mlir::parseAttribute(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseKeyword(), mlir::DialectAsmParser::parseLess(), and value.
print()
void CombiningKindAttr::print (DialectAsmPrinter & p) const
Definition at line 161 of file VectorOps.cpp.
References combiningKindsList, and kind.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Vector/VectorOps.h
lib/Dialect/Vector/VectorOps.cpp