MLIR: mlir::DialectInterface Class Reference
mlir::DialectInterface Class Reference
This class represents an interface overridden for a single dialect.
#include "mlir/IR/DialectInterface.h"
Public Types
template<typename ConcreteType>
using Base = detail::DialectInterfaceBase<ConcreteType, DialectInterface>
The base class used for all derived interface types.
Public Member Functions
virtual ~DialectInterface ()
Dialect * getDialect () const
Return the dialect that this interface represents.
MLIRContext * getContext () const
Return the context that holds the parent dialect of this interface.
TypeID getID () const
Return the derived interface id.
Protected Member Functions
DialectInterface (Dialect *dialect, TypeID id)
Detailed Description
This class represents an interface overridden for a single dialect.
Definition at line 42 of file DialectInterface.h.
Member Typedef Documentation
Base
template<typename ConcreteType> using mlir::DialectInterface::Base = detail::DialectInterfaceBase<ConcreteType, DialectInterface>
The base class used for all derived interface types.
This class provides utilities necessary for registration.
Definition at line 49 of file DialectInterface.h.
Constructor & Destructor Documentation
~DialectInterface()
DialectInterface::~DialectInterface () virtual default
DialectInterface()
mlir::DialectInterface::DialectInterface (Dialect * dialect, TypeID id) inline protected
Definition at line 61 of file DialectInterface.h.
Member Function Documentation
getContext()
MLIRContext * DialectInterface::getContext () const
Return the context that holds the parent dialect of this interface.
Definition at line 117 of file Dialect.cpp.
Referenced by mlir::LLVMImportInterface::initializeImport().
getDialect()
Dialect * mlir::DialectInterface::getDialect () const inline
Return the dialect that this interface represents.
Definition at line 52 of file DialectInterface.h.
Referenced by mlir::LLVMImportInterface::initializeImport(), mlir::OpAsmDialectInterface::parseResource(), mlir::detail::Parser::parseResourceHandle(), mlir::BytecodeDialectInterface::readAttribute(), and mlir::BytecodeDialectInterface::readType().
getID()
TypeID mlir::DialectInterface::getID () const inline
Return the derived interface id.
Definition at line 58 of file DialectInterface.h.
The documentation for this class was generated from the following files:
include/mlir/IR/DialectInterface.h
lib/IR/Dialect.cpp