MLIR: mlir::detail::TypeIDResolver< T, Enable > Class Template Reference
mlir::detail::TypeIDResolver< T, Enable > Class Template Reference
This class provides a resolver for getting the ID for a given class T.
#include "mlir/Support/TypeID.h"
Static Public Member Functions
static TypeID resolveTypeID ()
Additional Inherited Members
Static Protected Member Functions inherited from mlir::detail::FallbackTypeIDResolver
static LLVM_ALWAYS_EXPORT TypeID registerImplicitTypeID (StringRef name)
Register an implicit type ID for the given type name.
Detailed Description
template<typename T, typename Enable = void>
class mlir::detail::TypeIDResolver< T, Enable >
This class provides a resolver for getting the ID for a given class T.
This allows for the derived type to specialize its resolution behavior. The default implementation uses the string name of the type to resolve the ID. This provides a strong definition, but at the cost of performance (we need to do an initial lookup) and is not usable by classes defined in anonymous contexts.
TODO: The use of the type name is only necessary when building in the presence of shared libraries. We could add a build flag that guarantees "static"-like environments and switch this to a more optimal implementation when that is enabled.
Definition at line 203 of file TypeID.h.
Member Function Documentation
resolveTypeID()
template<typename T, typename Enable = void> TypeID mlir::detail::TypeIDResolver< T, Enable >::resolveTypeID () inline static
Definition at line 205 of file TypeID.h.
References mlir::detail::is_fully_resolved(), and mlir::detail::FallbackTypeIDResolver::registerImplicitTypeID().
Referenced by mlir::TypeID::get().
The documentation for this class was generated from the following file:
include/mlir/Support/TypeID.h