MLIR: mlir::StructBuilder Class Reference
mlir::StructBuilder Class Reference
Helper class to produce LLVM dialect operations extracting or inserting values to a struct.
#include "mlir/Conversion/LLVMCommon/StructBuilder.h"
Public Member Functions
StructBuilder (Value v)
Construct a helper for the given value.
operator Value ()
Static Public Member Functions
static StructBuilder undef (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating an undef value of the descriptor type.
Protected Member Functions
Value extractPtr (OpBuilder &builder, Location loc, unsigned pos)
Builds IR to extract a value from the struct at position pos.
void setPtr (OpBuilder &builder, Location loc, unsigned pos, Value ptr)
Builds IR to set a value in the struct at position pos.
Protected Attributes
Value value
Type structType
Detailed Description
Helper class to produce LLVM dialect operations extracting or inserting values to a struct.
Definition at line 26 of file StructBuilder.h.
Constructor & Destructor Documentation
StructBuilder()
StructBuilder::StructBuilder (Value v) explicit
Construct a helper for the given value.
Definition at line 20 of file StructBuilder.cpp.
References mlir::LLVM::isCompatibleType(), structType, and value.
Member Function Documentation
extractPtr()
Value StructBuilder::extractPtr (OpBuilder & builder, Location loc, unsigned pos) protected
Builds IR to extract a value from the struct at position pos.
Definition at line 25 of file StructBuilder.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), loc, structType, and value.
Referenced by mlir::MemRefDescriptor::alignedPtr(), mlir::MemRefDescriptor::allocatedPtr(), mlir::UnrankedMemRefDescriptor::memRefDescPtr(), and mlir::UnrankedMemRefDescriptor::rank().
operator Value()
mlir::StructBuilder::operator Value () inline
Definition at line 34 of file StructBuilder.h.
References value.
setPtr()
void StructBuilder::setPtr (OpBuilder & builder, Location loc, unsigned pos, Value ptr) protected
Builds IR to set a value in the struct at position pos.
Definition at line 32 of file StructBuilder.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), loc, structType, and value.
Referenced by mlir::MemRefDescriptor::setAlignedPtr(), mlir::MemRefDescriptor::setAllocatedPtr(), mlir::DataDescriptor::setBasePointer(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), mlir::DataDescriptor::setPointer(), mlir::UnrankedMemRefDescriptor::setRank(), and mlir::DataDescriptor::setSize().
undef()
static StructBuilder mlir::StructBuilder::undef (OpBuilder & builder, Location loc, Type descriptorType) static
Builds IR creating an undef value of the descriptor type.
Member Data Documentation
structType
Type mlir::StructBuilder::structType protected
Definition at line 40 of file StructBuilder.h.
Referenced by extractPtr(), mlir::MemRefDescriptor::setOffset(), setPtr(), mlir::DataDescriptor::setSize(), mlir::MemRefDescriptor::setSize(), mlir::MemRefDescriptor::setStride(), and StructBuilder().
value
Value mlir::StructBuilder::value protected
Definition at line 38 of file StructBuilder.h.
Referenced by createIndexAttrConstant(), mlir::DataDescriptor::DataDescriptor(), extractPtr(), mlir::MemRefDescriptor::getElementPtrType(), mlir::MemRefDescriptor::MemRefDescriptor(), mlir::MemRefDescriptor::offset(), operator Value(), mlir::MemRefDescriptor::setOffset(), setPtr(), mlir::MemRefDescriptor::setSize(), mlir::MemRefDescriptor::setStride(), mlir::MemRefDescriptor::size(), mlir::MemRefDescriptor::stride(), and StructBuilder().
The documentation for this class was generated from the following files:
include/mlir/Conversion/LLVMCommon/StructBuilder.h
lib/Conversion/LLVMCommon/StructBuilder.cpp