MLIR: mlir::OpTrait::OneOperand< ConcreteType > Class Template Reference
mlir::OpTrait::OneOperand< ConcreteType > Class Template Reference
This class provides the API for ops that are known to have exactly one SSA operand.
#include "mlir/IR/OpDefinition.h"
Public Member Functions
Value getOperand ()
void setOperand (Value value)
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, OneOperand >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::OneOperand< ConcreteType >
This class provides the API for ops that are known to have exactly one SSA operand.
Definition at line 462 of file OpDefinition.h.
Member Function Documentation
getOperand()
template<typename ConcreteType > Value mlir::OpTrait::OneOperand< ConcreteType >::getOperand () inline
Definition at line 464 of file OpDefinition.h.
References mlir::Operation::getOperand(), and mlir::OpTrait::TraitBase< ConcreteType, OneOperand >::getOperation().
setOperand()
template<typename ConcreteType > void mlir::OpTrait::OneOperand< ConcreteType >::setOperand (Value value) inline
Definition at line 466 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, OneOperand >::getOperation(), and mlir::Operation::setOperand().
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::OneOperand< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 468 of file OpDefinition.h.
References mlir::OpTrait::impl::verifyOneOperand().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h