MLIR: mlir::Pass::Statistic Class Reference
mlir::Pass::Statistic Class Reference
This class represents a single pass statistic.
#include "mlir/Pass/Pass.h"
Public Member Functions
Statistic (Pass *owner, const char *name, const char *description)
The statistic is initialized by the pass owner, a name, and a description.
Statistic & operator= (unsigned value)
Assign the statistic to the given value.
Detailed Description
This class represents a single pass statistic.
This statistic functions similarly to an unsigned integer value, and may be updated and incremented accordingly. This class can be used to provide additional information about the transformations and analyses performed by a pass.
Definition at line 134 of file Pass.h.
Constructor & Destructor Documentation
Statistic()
Pass::Statistic::Statistic (Pass * owner, const char * name, const char * description)
The statistic is initialized by the pass owner, a name, and a description.
Definition at line 168 of file PassStatistics.cpp.
References mlir::Pass::Pass(), and Statistic().
Referenced by operator=(), and Statistic().
Member Function Documentation
operator=()
auto Pass::Statistic::operator= (unsigned value)
Assign the statistic to the given value.
Definition at line 184 of file PassStatistics.cpp.
References Statistic().
The documentation for this class was generated from the following files:
include/mlir/Pass/Pass.h
lib/Pass/PassStatistics.cpp