MLIR: mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType > Class Template Reference
mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType > Class Template Reference
#include "mlir/IR/OpDefinition.h"
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, Impl >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename... ParentOpTypes>
template<typename ConcreteType>
class mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >
Definition at line 1207 of file OpDefinition.h.
Member Function Documentation
verifyTrait()
template<typename... ParentOpTypes> template<typename ConcreteType > static LogicalResult mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 1209 of file OpDefinition.h.
References mlir::Operation::emitOpError(), mlir::Operation::getParentOp(), and mlir::LogicalResult::success().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h