MLIR: mlir::sparse_tensor::ir_detail::Ranks Class Reference
mlir::sparse_tensor::ir_detail::Ranks Class Reference final
#include "Dialect/SparseTensor/IR/Detail/Var.h"
Public Member Functions
constexpr Ranks (unsigned symRank, unsigned dimRank, unsigned lvlRank)
Ranks (VarKindArray< unsigned > const &ranks)
bool operator== (Ranks const &other) const
bool operator!= (Ranks const &other) const
constexpr unsigned getRank (VarKind vk) const
constexpr unsigned getSymRank () const
constexpr unsigned getDimRank () const
constexpr unsigned getLvlRank () const
constexpr bool isValid (Var var) const
bool isValid (DimLvlExpr expr) const
Detailed Description
Definition at line 205 of file Var.h.
Constructor & Destructor Documentation
Ranks() [1/2]
mlir::sparse_tensor::ir_detail::Ranks::Ranks (unsigned symRank, unsigned dimRank, unsigned lvlRank) inline constexpr
Definition at line 215 of file Var.h.
References mlir::sparse_tensor::ir_detail::Dimension, mlir::sparse_tensor::ir_detail::Level, and mlir::sparse_tensor::ir_detail::Symbol.
Referenced by operator!=(), operator==(), and Ranks().
Ranks() [2/2]
mlir::sparse_tensor::ir_detail::Ranks::Ranks (VarKindArray< unsigned > const & ranks) inline
Definition at line 221 of file Var.h.
References mlir::sparse_tensor::ir_detail::Dimension, mlir::sparse_tensor::ir_detail::Level, Ranks(), and mlir::sparse_tensor::ir_detail::Symbol.
Member Function Documentation
getDimRank()
unsigned mlir::sparse_tensor::ir_detail::Ranks::getDimRank () const inline constexpr
Definition at line 230 of file Var.h.
References mlir::sparse_tensor::ir_detail::Dimension, and getRank().
getLvlRank()
unsigned mlir::sparse_tensor::ir_detail::Ranks::getLvlRank () const inline constexpr
Definition at line 231 of file Var.h.
References getRank(), and mlir::sparse_tensor::ir_detail::Level.
getRank()
unsigned mlir::sparse_tensor::ir_detail::Ranks::getRank (VarKind vk) const inline constexpr
Definition at line 228 of file Var.h.
Referenced by getDimRank(), getLvlRank(), mlir::sparse_tensor::ir_detail::DimLvlMap::getRank(), getSymRank(), isValid(), isValid(), operator==(), and mlir::sparse_tensor::ir_detail::VarSet::VarSet().
getSymRank()
unsigned mlir::sparse_tensor::ir_detail::Ranks::getSymRank () const inline constexpr
Definition at line 229 of file Var.h.
References getRank(), and mlir::sparse_tensor::ir_detail::Symbol.
Referenced by isValid().
isValid() [1/2]
bool Ranks::isValid (DimLvlExpr expr) const nodiscard
Definition at line 57 of file Var.cpp.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::getAffineExpr(), mlir::sparse_tensor::ir_detail::DimLvlExpr::getAllowedVarKind(), mlir::getMaxDimAndSymbol(), getRank(), and getSymRank().
isValid() [2/2]
bool mlir::sparse_tensor::ir_detail::Ranks::isValid (Var var) const inline nodiscard constexpr
Definition at line 233 of file Var.h.
References mlir::sparse_tensor::ir_detail::Var::getKind(), mlir::sparse_tensor::ir_detail::Var::getNum(), and getRank().
Referenced by mlir::sparse_tensor::ir_detail::DimSpec::isValid(), and mlir::sparse_tensor::ir_detail::LvlSpec::isValid().
operator!=()
bool mlir::sparse_tensor::ir_detail::Ranks::operator!= (Ranks const & other) const inline
Definition at line 226 of file Var.h.
References Ranks().
operator==()
bool Ranks::operator== (Ranks const & other) const
Definition at line 50 of file Var.cpp.
References everyVarKind, getRank(), and Ranks().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/Var.h
lib/Dialect/SparseTensor/IR/Detail/Var.cpp