MLIR: mlir::FusionStrategy Class Reference
mlir::FusionStrategy Class Reference
Describes the fusion strategy to be used in the Affine loop fusion utilities.
#include "mlir/Transforms/LoopFusionUtils.h"
Public Types
enum StrategyEnum { Generic, ProducerConsumer, Sibling }
Public Member Functions
FusionStrategy (StrategyEnum strategy)
Construct a generic or producer-consumer fusion strategy.
FusionStrategy (Value memref)
Construct a sibling fusion strategy targeting 'memref'.
StrategyEnum getStrategy () const
Returns the fusion strategy.
Value getSiblingFusionMemRef () const
Returns the memref attached to this sibling fusion strategy.
Detailed Description
Describes the fusion strategy to be used in the Affine loop fusion utilities.
Currently, it is used to specialized the loop fusion utilities with the assumptions made in the AffineLoopFusion pass for producer-consumer and sibling fusion, while sharing a single implementation. The latter strategies are also limited to scenarios where a single memref is involved in the producer-consume or sibling relationship between the candidate loops. We use 'memref' to keep track of such a memref.
Definition at line 54 of file LoopFusionUtils.h.
Member Enumeration Documentation
StrategyEnum
enum mlir::FusionStrategy::StrategyEnum
Enumerator
Generic
ProducerConsumer
Sibling
Definition at line 56 of file LoopFusionUtils.h.
Constructor & Destructor Documentation
FusionStrategy() [1/2]
mlir::FusionStrategy::FusionStrategy (StrategyEnum strategy) inline
Construct a generic or producer-consumer fusion strategy.
Definition at line 77 of file LoopFusionUtils.h.
FusionStrategy() [2/2]
mlir::FusionStrategy::FusionStrategy (Value memref) inline
Construct a sibling fusion strategy targeting 'memref'.
This construct should only be used for sibling fusion.
Definition at line 84 of file LoopFusionUtils.h.
Member Function Documentation
getSiblingFusionMemRef()
Value mlir::FusionStrategy::getSiblingFusionMemRef () const inline
Returns the memref attached to this sibling fusion strategy.
Definition at line 90 of file LoopFusionUtils.h.
References mlir::canFuseLoops(), mlir::fuseLoops(), and Generic.
Referenced by mlir::canFuseLoops().
getStrategy()
StrategyEnum mlir::FusionStrategy::getStrategy () const inline
Returns the fusion strategy.
Definition at line 87 of file LoopFusionUtils.h.
Referenced by mlir::canFuseLoops().
The documentation for this class was generated from the following file:
include/mlir/Transforms/LoopFusionUtils.h