MLIR: mlir::PassManager Class Reference
mlir::PassManager Class Reference
The main pass manager and pipeline builder.
#include "mlir/Pass/PassManager.h"
Classes
class IRPrinterConfig
A configuration struct provided to the IR printer instrumentation.
Public Member Functions
PassManager (MLIRContext *ctx, StringRef operationName=PassManager::getAnyOpAnchorName(), Nesting nesting=Nesting::Explicit)
Create a new pass manager under the given context with a specific nesting style.
PassManager (OperationName operationName, Nesting nesting=Nesting::Explicit)
~PassManager ()
LogicalResult run (Operation *op)
Run the passes within this manager on the provided operation.
MLIRContext * getContext () const
Return an instance of the context.
void enableCrashReproducerGeneration (StringRef outputFile, bool genLocalReproducer=false)
Enable support for the pass manager to generate a reproducer on the event of a crash or a pass failure.
void enableCrashReproducerGeneration (ReproducerStreamFactory factory, bool genLocalReproducer=false)
Enable support for the pass manager to generate a reproducer on the event of a crash or a pass failure.
void enableVerifier (bool enabled=true)
Runs the verifier after each individual pass.
void addInstrumentation (std::unique_ptr< PassInstrumentation > pi)
Add the provided instrumentation to the pass manager.
void enableIRPrinting (std::unique_ptr< IRPrinterConfig > config)
Add an instrumentation to print the IR before and after pass execution, using the provided configuration.
void enableIRPrinting (std::function< bool(Pass *, Operation *)> shouldPrintBeforePass=[](Pass *, Operation *) { return true;}, std::function< bool(Pass *, Operation *)> shouldPrintAfterPass=[](Pass *, Operation *) { return true;}, bool printModuleScope=true, bool printAfterOnlyOnChange=true, bool printAfterOnlyOnFailure=false, raw_ostream &out=llvm::errs(), OpPrintingFlags opPrintingFlags=OpPrintingFlags())
Add an instrumentation to print the IR before and after pass execution, using the provided fields to generate a default configuration:
void enableIRPrintingToFileTree (std::function< bool(Pass *, Operation *)> shouldPrintBeforePass=[](Pass *, Operation *) { return true;}, std::function< bool(Pass *, Operation *)> shouldPrintAfterPass=[](Pass *, Operation *) { return true;}, bool printModuleScope=true, bool printAfterOnlyOnChange=true, bool printAfterOnlyOnFailure=false, llvm::StringRef printTreeDir=".pass_manager_output", OpPrintingFlags opPrintingFlags=OpPrintingFlags())
Similar to enableIRPrinting above, except that instead of printing the IR to a single output stream, the instrumentation will print the output of each pass to a separate file.
void enableTiming (TimingScope &timingScope)
Add an instrumentation to time the execution of passes and the computation of analyses.
void enableTiming (std::unique_ptr< TimingManager > tm)
Add an instrumentation to time the execution of passes and the computation of analyses.
void enableTiming ()
Add an instrumentation to time the execution of passes and the computation of analyses.
void enableStatistics (PassDisplayMode displayMode=PassDisplayMode::Pipeline)
Prompts the pass manager to print the statistics collected for each of the held passes after each call to 'run'.
Public Member Functions inherited from mlir::OpPassManager
OpPassManager (Nesting nesting=Nesting::Explicit)
Construct a new op-agnostic ("any") pass manager with the given operation type and nesting behavior.
OpPassManager (StringRef name, Nesting nesting=Nesting::Explicit)
Construct a new pass manager with the given anchor operation type and nesting behavior.
OpPassManager (OperationName name, Nesting nesting=Nesting::Explicit)
OpPassManager (OpPassManager &&rhs)
OpPassManager (const OpPassManager &rhs)
~OpPassManager ()
OpPassManager & operator= (const OpPassManager &rhs)
OpPassManager & operator= (OpPassManager &&rhs)
pass_iterator begin ()
pass_iterator end ()
iterator_range< pass_iterator > getPasses ()
const_pass_iterator begin () const
const_pass_iterator end () const
iterator_range< const_pass_iterator > getPasses () const
bool empty () const
Returns true if the pass manager has no passes.
OpPassManager & nest (OperationName nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
OpPassManager & nest (StringRef nestedName)
template<typename OpT>
OpPassManager & nest ()
OpPassManager & nestAny ()
Nest a new op-agnostic ("any") pass manager under this pass manager.
void addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
void clear ()
Clear the pipeline, but not the other options set on this OpPassManager.
template<typename OpT>
void addNestedPass (std::unique_ptr< Pass > pass)
Add the given pass to a nested pass manager for the given operation kind OpT.
size_t size () const
Returns the number of passes held by this manager.
std::optional< OperationName > getOpName (MLIRContext &context) const
Return the operation name that this pass manager operates on, or std::nullopt if this is an op-agnostic pass manager.
std::optional< StringRef > getOpName () const
Return the operation name that this pass manager operates on, or std::nullopt if this is an op-agnostic pass manager.
StringRef getOpAnchorName () const
Return the name used to anchor this pass manager.
detail::OpPassManagerImpl & getImpl ()
Returns the internal implementation instance.
void printAsTextualPipeline (raw_ostream &os, bool pretty=false) const
Prints out the passes of the pass manager as the textual representation of pipelines.
void dump ()
Raw dump of the pass manager to llvm::errs().
void mergeStatisticsInto (OpPassManager &other)
Merge the pass statistics of this class into 'other'.
void getDependentDialects (DialectRegistry &dialects) const
Register dependent dialects for the current pass manager.
void setNesting (Nesting nesting)
Enable or disable the implicit nesting on this particular PassManager.
Nesting getNesting ()
Return the current nesting mode.
Static Public Member Functions
template<typename OperationTy>
static PassManager on (MLIRContext *ctx, Nesting nesting=Nesting::Explicit)
Create a new pass manager under the given context with a specific nesting style.
Static Public Member Functions inherited from mlir::OpPassManager
static StringRef getAnyOpAnchorName ()
Return the string name used to anchor op-agnostic pass managers that operate generically on any viable operation.
Additional Inherited Members
Public Types inherited from mlir::OpPassManager
enum class Nesting { Implicit , Explicit }
This enum represents the nesting behavior of the pass manager.
using pass_iterator
Iterator over the passes in this pass manager.
using const_pass_iterator
Detailed Description
The main pass manager and pipeline builder.
Definition at line 232 of file PassManager.h.
Constructor & Destructor Documentation
PassManager() [1/2]
PassManager::PassManager (MLIRContext * ctx, StringRef operationName = PassManager::getAnyOpAnchorName(), Nesting nesting = Nesting::Explicit)
Create a new pass manager under the given context with a specific nesting style.
The created pass manager can schedule operations that match operationName.
Definition at line 1020 of file Pass.cpp.
References false, mlir::OpPassManager::OpPassManager(), and true.
Referenced by on().
PassManager() [2/2]
PassManager::PassManager (OperationName operationName, Nesting nesting = Nesting::Explicit)
Definition at line 1025 of file Pass.cpp.
References false, getContext(), mlir::OpPassManager::OpPassManager(), and true.
~PassManager()
PassManager::~PassManager () default
Member Function Documentation
addInstrumentation()
void PassManager::addInstrumentation (std::unique_ptr< PassInstrumentation > pi)
Add the provided instrumentation to the pass manager.
Definition at line 1114 of file Pass.cpp.
Referenced by enableCrashReproducerGeneration(), enableIRPrinting(), enableTiming(), and enableTiming().
enableCrashReproducerGeneration() [1/2]
void PassManager::enableCrashReproducerGeneration (ReproducerStreamFactory factory, bool genLocalReproducer = false)
Enable support for the pass manager to generate a reproducer on the event of a crash or a pass failure.
factory is used to construct the streams to write the generated reproducer to. If genLocalReproducer is true, the pass manager will attempt to generate a local reproducer that contains the smallest pipeline.
Definition at line 472 of file PassCrashRecovery.cpp.
References addInstrumentation(), and getContext().
enableCrashReproducerGeneration() [2/2]
void PassManager::enableCrashReproducerGeneration (StringRef outputFile, bool genLocalReproducer = false)
Enable support for the pass manager to generate a reproducer on the event of a crash or a pass failure.
outputFile is a .mlir filename used to write the generated reproducer. If genLocalReproducer is true, the pass manager will attempt to generate a local reproducer that contains the smallest pipeline.
Definition at line 466 of file PassCrashRecovery.cpp.
References enableCrashReproducerGeneration(), and makeReproducerStreamFactory().
Referenced by mlir::applyPassManagerCLOptions(), and enableCrashReproducerGeneration().
enableIRPrinting() [1/2]
void PassManager::enableIRPrinting (std::function< bool(Pass *, Operation *)> shouldPrintBeforePass = [](Pass *, Operation *) { return true; }, std::function< bool(Pass *, Operation *)> shouldPrintAfterPass = [](Pass *, Operation *) { return true; }, bool printModuleScope = true, bool printAfterOnlyOnChange = true, bool printAfterOnlyOnFailure = false, raw_ostream & out = llvm::errs(), OpPrintingFlags opPrintingFlags = OpPrintingFlags())
Add an instrumentation to print the IR before and after pass execution, using the provided fields to generate a default configuration:
Add an instrumentation to print the IR before and after pass execution.
'shouldPrintBeforePass' and 'shouldPrintAfterPass' correspond to filter functions that take a 'Pass ' and Operation *. These function should return true if the IR should be printed or not.
'printModuleScope' signals if the module IR should be printed, even for non module passes.
'printAfterOnlyOnChange' signals that when printing the IR after a pass, in the case of a non-failure, we should first check if any potential mutations were made.
'printAfterOnlyOnFailure' signals that when printing the IR after a pass, we only print in the case of a failure.
This option should *not
be used with the other printAfter flags above.
'out' corresponds to the stream to output the printed IR to.
'opPrintingFlags' sets up the printing flags to use when printing the IR.
Definition at line 364 of file IRPrinting.cpp.
References enableIRPrinting(), and mlir::OpPassManager::Pass.
enableIRPrinting() [2/2]
void PassManager::enableIRPrinting (std::unique_ptr< IRPrinterConfig > config)
Add an instrumentation to print the IR before and after pass execution, using the provided configuration.
Definition at line 354 of file IRPrinting.cpp.
References addInstrumentation(), mlir::config, and getContext().
Referenced by enableIRPrinting(), and enableIRPrintingToFileTree().
enableIRPrintingToFileTree()
void PassManager::enableIRPrintingToFileTree (std::function< bool(Pass *, Operation *)> shouldPrintBeforePass = [](Pass *, Operation *) { return true; }, std::function< bool(Pass *, Operation *)> shouldPrintAfterPass = [](Pass *, Operation *) { return true; }, bool printModuleScope = true, bool printAfterOnlyOnChange = true, bool printAfterOnlyOnFailure = false, llvm::StringRef printTreeDir = ".pass_manager_output", OpPrintingFlags opPrintingFlags = OpPrintingFlags())
Similar to enableIRPrinting above, except that instead of printing the IR to a single output stream, the instrumentation will print the output of each pass to a separate file.
Add an instrumentation to print the IR before and after pass execution.
The files will be organized into a directory tree rooted at printTreeDir. The directories mirror the nesting structure of the IR. For example, if the IR is congruent to the pass-pipeline "builtin.module(passA,passB,func.func(passC,passD),passE)", and printTreeDir=/tmp/pipeline_output, then then the tree file tree created will look like:
/tmp/pass_output
 builtin_module_the_symbol_name
    0_passA.mlir
    1_passB.mlir
    2_passE.mlir
    func_func_my_func_name
       1_0_passC.mlir
       1_1__passD.mlir
    func_func_my_other_func_name
       1_0_passC.mlir
       1_1_passD.mlir
The subdirectories are given names that reflect the parent operation name and symbol name (if present). The output MLIR files are prefixed using an atomic counter to indicate the order the passes were printed in and to prevent any potential name collisions.
Definition at line 377 of file IRPrinting.cpp.
References enableIRPrinting(), and mlir::OpPassManager::Pass.
enableStatistics()
void PassManager::enableStatistics (PassDisplayMode displayMode = PassDisplayMode::Pipeline)
Prompts the pass manager to print the statistics collected for each of the held passes after each call to 'run'.
Dump the statistics for each pass after running.
Definition at line 250 of file PassStatistics.cpp.
Referenced by mlir::applyPassManagerCLOptions().
enableTiming() [1/3]
void PassManager::enableTiming ()
Add an instrumentation to time the execution of passes and the computation of analyses.
Creates a temporary TimingManager owned by this PassManager which will be used to report timing.
Note: Timing should be enabled after all other instrumentations to avoid any potential "ghost" timing from other instrumentations being unintentionally included in the timing results.
Definition at line 163 of file PassTiming.cpp.
References enableTiming().
Referenced by enableTiming().
enableTiming() [2/3]
void PassManager::enableTiming (std::unique_ptr< TimingManager > tm)
Add an instrumentation to time the execution of passes and the computation of analyses.
The pass manager will take ownership of the timing manager passed to the function and timing will be reported by nesting timers into the timing manager's root scope.
Note: Timing should be enabled after all other instrumentations to avoid any potential "ghost" timing from other instrumentations being unintentionally included in the timing results.
Definition at line 155 of file PassTiming.cpp.
References addInstrumentation().
enableTiming() [3/3]
void PassManager::enableTiming (TimingScope & timingScope)
Add an instrumentation to time the execution of passes and the computation of analyses.
Timing will be reported by nesting timers into the provided timingScope.
Note: Timing should be enabled after all other instrumentations to avoid any potential "ghost" timing from other instrumentations being unintentionally included in the timing results.
Definition at line 147 of file PassTiming.cpp.
References addInstrumentation().
Referenced by mlir::applyDefaultTimingPassManagerCLOptions(), and performActions().
enableVerifier()
void PassManager::enableVerifier (bool enabled = true)
Runs the verifier after each individual pass.
Definition at line 1032 of file Pass.cpp.
Referenced by mlir::PassReproducerOptions::apply(), and performActions().
getContext()
MLIRContext * mlir::PassManager::getContext () const inline
Return an instance of the context.
Definition at line 257 of file PassManager.h.
Referenced by mlir::PassReproducerOptions::apply(), mlir::applyPassManagerCLOptions(), enableIRPrinting(), PassManager(), performActions(), and run().
on()
template<typename OperationTy> PassManager mlir::PassManager::on (MLIRContext * ctx, Nesting nesting = Nesting::Explicit) inline static
Create a new pass manager under the given context with a specific nesting style.
The created pass manager can schedule operations that match OperationTy.
Definition at line 247 of file PassManager.h.
References mlir::OpPassManager::Explicit, mlir::OpPassManager::PassManager, and PassManager().
run()
LogicalResult PassManager::run (Operation * op)
Run the passes within this manager on the provided operation.
The specified operation must have the same name as the one provided the pass manager on construction.
Definition at line 1035 of file Pass.cpp.
References mlir::emitError(), getContext(), mlir::OpPassManager::getDependentDialects(), mlir::DialectRegistry::getDialectNames(), mlir::OpPassManager::getImpl(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::OpPassManager::getOpAnchorName(), mlir::OpPassManager::getOpName(), mlir::OpPassManager::printAsTextualPipeline(), result, and mlir::OpPassManager::size().
Referenced by mlir::mlirReduceMain(), and performActions().
The documentation for this class was generated from the following files:
include/mlir/Pass/PassManager.h
lib/Pass/IRPrinting.cpp
lib/Pass/Pass.cpp
lib/Pass/PassCrashRecovery.cpp
lib/Pass/PassStatistics.cpp
lib/Pass/PassTiming.cpp