MLIR: mlir::IntegerDivisibility Class Reference
mlir::IntegerDivisibility Class Reference
This lattice value represents the integer divisibility of an SSA value.
#include "mlir/Interfaces/InferIntDivisibilityOpInterface.h"
Public Member Functions
IntegerDivisibility (ConstantIntDivisibility value)
IntegerDivisibility (std::optional< ConstantIntDivisibility > value=std::nullopt)
bool isUninitialized () const
const ConstantIntDivisibility & getValue () const
bool operator== (const IntegerDivisibility &rhs) const
void print (raw_ostream &os) const
Static Public Member Functions
static IntegerDivisibility getMinDivisibility ()
static IntegerDivisibility join (const IntegerDivisibility &lhs, const IntegerDivisibility &rhs)
Detailed Description
This lattice value represents the integer divisibility of an SSA value.
Definition at line 63 of file InferIntDivisibilityOpInterface.h.
Constructor & Destructor Documentation
IntegerDivisibility() [1/2]
mlir::IntegerDivisibility::IntegerDivisibility (ConstantIntDivisibility value) inline
Definition at line 65 of file InferIntDivisibilityOpInterface.h.
Referenced by getMinDivisibility(), join(), and operator==().
IntegerDivisibility() [2/2]
mlir::IntegerDivisibility::IntegerDivisibility (std::optional< ConstantIntDivisibility > value = std::nullopt) inline explicit
Definition at line 67 of file InferIntDivisibilityOpInterface.h.
Member Function Documentation
getMinDivisibility()
IntegerDivisibility mlir::IntegerDivisibility::getMinDivisibility () inline static
Definition at line 72 of file InferIntDivisibilityOpInterface.h.
References IntegerDivisibility().
Referenced by mlir::dataflow::IntegerDivisibilityAnalysis::setToEntryState(), mlir::dataflow::IntegerDivisibilityAnalysis::visitNonControlFlowArguments(), and mlir::dataflow::IntegerDivisibilityAnalysis::visitOperation().
getValue()
const ConstantIntDivisibility & mlir::IntegerDivisibility::getValue () const inline
Definition at line 77 of file InferIntDivisibilityOpInterface.h.
References isUninitialized().
Referenced by getDivisibilityOfOperand(), and mlir::dataflow::IntegerDivisibilityAnalysis::visitNonControlFlowArguments().
isUninitialized()
bool mlir::IntegerDivisibility::isUninitialized () const inline
Definition at line 76 of file InferIntDivisibilityOpInterface.h.
Referenced by getDivisibilityOfOperand(), getValue(), mlir::dataflow::IntegerDivisibilityAnalysis::visitNonControlFlowArguments(), and mlir::dataflow::IntegerDivisibilityAnalysis::visitOperation().
join()
IntegerDivisibility mlir::IntegerDivisibility::join (const IntegerDivisibility & lhs, const IntegerDivisibility & rhs) inline static
Definition at line 86 of file InferIntDivisibilityOpInterface.h.
References IntegerDivisibility(), lhs, and rhs.
operator==()
bool mlir::IntegerDivisibility::operator== (const IntegerDivisibility & rhs) const inline
Definition at line 82 of file InferIntDivisibilityOpInterface.h.
References IntegerDivisibility(), and rhs.
print()
void mlir::IntegerDivisibility::print (raw_ostream & os) const inline
Definition at line 97 of file InferIntDivisibilityOpInterface.h.
The documentation for this class was generated from the following file:
include/mlir/Interfaces/InferIntDivisibilityOpInterface.h