MLIR: mlir::DynamicDialect Class Reference
mlir::DynamicDialect Class Reference
A dialect that can be defined at runtime.
#include "mlir/IR/ExtensibleDialect.h"
Public Member Functions
DynamicDialect (StringRef name, MLIRContext *ctx)
TypeID getTypeID ()
virtual Type parseType (DialectAsmParser &parser) const override
Parse a type registered to this dialect.
virtual void printType (Type type, DialectAsmPrinter &printer) const override
Print a type registered to this dialect.
virtual Attribute parseAttribute (DialectAsmParser &parser, Type type) const override
Parse an attribute registered to this dialect.
virtual void printAttribute (Attribute attr, DialectAsmPrinter &printer) const override
Print an attribute registered to this dialect.
Public Member Functions inherited from mlir::SelfOwningTypeID
SelfOwningTypeID ()=default
SelfOwningTypeID (const SelfOwningTypeID &)=delete
SelfOwningTypeID & operator= (const SelfOwningTypeID &)=delete
SelfOwningTypeID (SelfOwningTypeID &&)=delete
SelfOwningTypeID & operator= (SelfOwningTypeID &&)=delete
operator TypeID () const
Implicitly converts to the owned TypeID.
TypeID getTypeID () const
Return the TypeID owned by this object.
Public Member Functions inherited from mlir::ExtensibleDialect
ExtensibleDialect (StringRef name, MLIRContext *ctx, TypeID typeID)
void registerDynamicType (std::unique_ptr< DynamicTypeDefinition > &&type)
Add a new type defined at runtime to the dialect.
void registerDynamicAttr (std::unique_ptr< DynamicAttrDefinition > &&attr)
Add a new attribute defined at runtime to the dialect.
void registerDynamicOp (std::unique_ptr< DynamicOpDefinition > &&type)
Add a new operation defined at runtime to the dialect.
DynamicTypeDefinition * lookupTypeDefinition (StringRef name) const
Returns nullptr if the definition was not found.
DynamicTypeDefinition * lookupTypeDefinition (TypeID id) const
Returns nullptr if the definition was not found.
DynamicAttrDefinition * lookupAttrDefinition (StringRef name) const
Returns nullptr if the definition was not found.
DynamicAttrDefinition * lookupAttrDefinition (TypeID id) const
Returns nullptr if the definition was not found.
Public Member Functions inherited from mlir::Dialect
virtual ~Dialect ()
MLIRContext * getContext () const
StringRef getNamespace () const
TypeID getTypeID () const
Returns the unique identifier that corresponds to this dialect.
bool allowsUnknownOperations () const
Returns true if this dialect allows for unregistered operations, i.e.
bool allowsUnknownTypes () const
Return true if this dialect allows for unregistered types, i.e., types prefixed with the dialect namespace but not registered with addType.
virtual void getCanonicalizationPatterns (RewritePatternSet &results) const
Register dialect-wide canonicalization patterns.
virtual Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc)
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
virtual std::optional< ParseOpHook > getParseOperationHook (StringRef opName) const
Return the hook to parse an operation registered to this dialect, if any.
virtual llvm::unique_function< void(Operation *, OpAsmPrinter &printer)> getOperationPrinter (Operation *op) const
Print an operation registered to this dialect.
virtual LogicalResult verifyRegionArgAttribute (Operation *, unsigned regionIndex, unsigned argIndex, NamedAttribute)
Verify an attribute from this dialect on the argument at 'argIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyRegionResultAttribute (Operation *, unsigned regionIndex, unsigned resultIndex, NamedAttribute)
Verify an attribute from this dialect on the result at 'resultIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyOperationAttribute (Operation *, NamedAttribute)
Verify an attribute from this dialect on the given operation.
DialectInterface * getRegisteredInterface (TypeID interfaceID)
Lookup an interface for the given ID if one is registered, otherwise nullptr.
template<typename InterfaceT>
InterfaceT * getRegisteredInterface ()
virtual void * getRegisteredInterfaceForOp (TypeID interfaceID, OperationName opName)
Lookup an op interface for the given ID if one is registered, otherwise nullptr.
template<typename InterfaceT>
InterfaceT::Concept * getRegisteredInterfaceForOp (OperationName opName)
void addInterface (std::unique_ptr< DialectInterface > interface)
Register a dialect interface with this dialect instance.
template<typename... Args>
void addInterfaces ()
Register a set of dialect interfaces with this dialect instance.
template<typename InterfaceT, typename... Args>
InterfaceT & addInterface (Args &&...args)
template<typename InterfaceT, typename ConcreteT>
void declarePromisedInterface ()
Declare that the given interface will be implemented, but has a delayed registration.
template<typename InterfaceT, typename... ConcreteT>
void declarePromisedInterfaces ()
void handleUseOfUndefinedPromisedInterface (TypeID interfaceRequestorID, TypeID interfaceID, StringRef interfaceName="")
Checks if the given interface, which is attempting to be used, is a promised interface of this dialect that has yet to be implemented.
void handleAdditionOfUndefinedPromisedInterface (TypeID interfaceRequestorID, TypeID interfaceID)
Checks if the given interface, which is attempting to be attached to a construct owned by this dialect, is a promised interface of this dialect that has yet to be implemented.
bool hasPromisedInterface (TypeID interfaceRequestorID, TypeID interfaceID) const
Checks if a promise has been made for the interface/requestor pair.
template<typename ConcreteT, typename InterfaceT>
bool hasPromisedInterface () const
Checks if a promise has been made for the interface/requestor pair.
Static Public Member Functions
static bool classof (const Dialect *dialect)
Check if the dialect is an extensible dialect.
Static Public Member Functions inherited from mlir::ExtensibleDialect
static bool classof (const Dialect *dialect)
Check if the dialect is an extensible dialect.
Static Public Member Functions inherited from mlir::Dialect
static bool isValidNamespace (StringRef str)
Utility function that returns if the given string is a valid dialect namespace.
Additional Inherited Members
Public Types inherited from mlir::Dialect
using ParseOpHook
Type for a callback provided by the dialect to parse a custom operation.
Protected Member Functions inherited from mlir::ExtensibleDialect
OptionalParseResult parseOptionalDynamicType (StringRef typeName, AsmParser &parser, Type &resultType) const
Parse the dynamic type 'typeName' in the dialect 'dialect'.
OptionalParseResult parseOptionalDynamicAttr (StringRef attrName, AsmParser &parser, Attribute &resultAttr) const
Parse the dynamic attribute 'attrName' in the dialect 'dialect'.
Protected Member Functions inherited from mlir::Dialect
Dialect (StringRef name, MLIRContext *context, TypeID id)
The constructor takes a unique namespace for this dialect as well as the context to bind to.
template<typename... Args>
void addOperations ()
This method is used by derived classes to add their operations to the set.
template<typename... Args>
void addTypes ()
Register a set of type classes with this dialect.
void addType (TypeID typeID, AbstractType &&typeInfo)
Register a type instance with this dialect.
template<typename... Args>
void addAttributes ()
Register a set of attribute classes with this dialect.
void addAttribute (TypeID typeID, AbstractAttribute &&attrInfo)
Register an attribute instance with this dialect.
void allowUnknownOperations (bool allow=true)
Enable support for unregistered operations.
void allowUnknownTypes (bool allow=true)
Enable support for unregistered types.
Static Protected Member Functions inherited from mlir::ExtensibleDialect
static LogicalResult printIfDynamicType (Type type, AsmPrinter &printer)
If 'type' is a dynamic type, print it.
static LogicalResult printIfDynamicAttr (Attribute attr, AsmPrinter &printer)
If 'attr' is a dynamic attribute, print it.
Detailed Description
A dialect that can be defined at runtime.
It can be extended with new operations, types, and attributes at runtime.
Definition at line 631 of file ExtensibleDialect.h.
Constructor & Destructor Documentation
DynamicDialect()
DynamicDialect::DynamicDialect (StringRef name, MLIRContext * ctx)
Definition at line 531 of file ExtensibleDialect.cpp.
References mlir::Dialect::addInterfaces(), mlir::ExtensibleDialect::ExtensibleDialect(), getTypeID(), and mlir::SelfOwningTypeID::SelfOwningTypeID().
Member Function Documentation
classof()
bool DynamicDialect::classof (const Dialect * dialect) static
Check if the dialect is an extensible dialect.
Definition at line 537 of file ExtensibleDialect.cpp.
References mlir::Dialect::getRegisteredInterface().
Referenced by llvm::isa_impl< mlir::DynamicDialect, mlir::Dialect >::doit().
getTypeID()
TypeID mlir::DynamicDialect::getTypeID () inline
Definition at line 635 of file ExtensibleDialect.h.
References mlir::SelfOwningTypeID::getTypeID().
Referenced by DynamicDialect().
parseAttribute()
Attribute DynamicDialect::parseAttribute (DialectAsmParser & parser, Type type) const override virtual
Parse an attribute registered to this dialect.
If 'type' is nonnull, it refers to the expected type of the attribute.
Reimplemented from mlir::Dialect.
Definition at line 569 of file ExtensibleDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseKeyword(), and mlir::ExtensibleDialect::parseOptionalDynamicAttr().
parseType()
Type DynamicDialect::parseType (DialectAsmParser & parser) const override virtual
Parse a type registered to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 542 of file ExtensibleDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseKeyword(), and mlir::ExtensibleDialect::parseOptionalDynamicType().
printAttribute()
void DynamicDialect::printAttribute (Attribute , DialectAsmPrinter &) const override virtual
Print an attribute registered to this dialect.
Note: The type of the attribute need not be printed by this method as it is always printed by the caller.
Reimplemented from mlir::Dialect.
Definition at line 589 of file ExtensibleDialect.cpp.
References mlir::ExtensibleDialect::printIfDynamicAttr().
printType()
void DynamicDialect::printType (Type , DialectAsmPrinter &) const override virtual
Print a type registered to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 562 of file ExtensibleDialect.cpp.
References mlir::ExtensibleDialect::printIfDynamicType().
The documentation for this class was generated from the following files:
include/mlir/IR/ExtensibleDialect.h
lib/IR/ExtensibleDialect.cpp