MLIR: mlir::ConversionTarget Class Reference
mlir::ConversionTarget Class Reference
This class describes a specific conversion target.
#include "mlir/Transforms/DialectConversion.h"
Classes
struct LegalOpDetails
A structure containing additional information describing a specific legal operation instance.
Public Types
enum LegalizationAction { LegalizationAction::Legal, LegalizationAction::Dynamic, LegalizationAction::Illegal }
This enumeration corresponds to the specific action to take when considering an operation legal for this conversion target.
using DynamicLegalityCallbackFn = std::function< bool(Operation *)>
The signature of the callback used to determine if an operation is dynamically legal on the target.
Public Member Functions
ConversionTarget (MLIRContext &ctx)
virtual ~ConversionTarget ()=default
void setOpAction (OperationName op, LegalizationAction action)
Register a legality action for the given operation.
template<typename OpT >
void setOpAction (LegalizationAction action)
template<typename OpT >
void addLegalOp ()
Register the given operations as legal.
template<typename OpT , typename OpT2 , typename... OpTs>
void addLegalOp ()
template<typename OpT >
void addDynamicallyLegalOp ()
Register the given operation as dynamically legal, i.e.
template<typename OpT , typename OpT2 , typename... OpTs>
void addDynamicallyLegalOp ()
template<typename OpT >
void addDynamicallyLegalOp (const DynamicLegalityCallbackFn &callback)
Register the given operation as dynamically legal and set the dynamic legalization callback to the one provided.
template<typename OpT , typename OpT2 , typename... OpTs>
void addDynamicallyLegalOp (const DynamicLegalityCallbackFn &callback)
template<typename OpT , class Callable >
std::enable_if< !llvm::is_invocable< Callable, Operation * >::value >::type addDynamicallyLegalOp (Callable &&callback)
template<typename OpT >
void addIllegalOp ()
Register the given operation as illegal, i.e.
template<typename OpT , typename OpT2 , typename... OpTs>
void addIllegalOp ()
template<typename OpT >
void markOpRecursivelyLegal (const DynamicLegalityCallbackFn &callback={})
Mark an operation, that must have either been set as Legal or DynamicallyLegal, as being recursively legal.
template<typename OpT , typename OpT2 , typename... OpTs>
void markOpRecursivelyLegal (const DynamicLegalityCallbackFn &callback={})
template<typename OpT , class Callable >
std::enable_if< !llvm::is_invocable< Callable, Operation * >::value >::type markOpRecursivelyLegal (Callable &&callback)
void setDialectAction (ArrayRef< StringRef > dialectNames, LegalizationAction action)
Register a legality action for the given dialects.
template<typename... Names>
void addLegalDialect (StringRef name, Names... names)
Register the operations of the given dialects as legal.
template<typename... Args>
void addLegalDialect ()
template<typename... Names>
void addDynamicallyLegalDialect (StringRef name, Names... names)
Register the operations of the given dialects as dynamically legal, i.e.
template<typename... Args>
void addDynamicallyLegalDialect (Optional< DynamicLegalityCallbackFn > callback=llvm::None)
template<typename... Args>
void addDynamicallyLegalDialect (DynamicLegalityCallbackFn callback)
void markUnknownOpDynamicallyLegal (const DynamicLegalityCallbackFn &fn)
Register unknown operations as dynamically legal.
void markUnknownOpDynamicallyLegal ()
template<typename... Names>
void addIllegalDialect (StringRef name, Names... names)
Register the operations of the given dialects as illegal, i.e.
template<typename... Args>
void addIllegalDialect ()
Optional< LegalizationAction > getOpAction (OperationName op) const
Get the legality action for the given operation.
Optional< LegalOpDetails > isLegal (Operation *op) const
If the given operation instance is legal on this target, a structure containing legality information is returned.
Protected Member Functions
virtual bool isDynamicallyLegal (Operation *op) const
Runs a custom legalization query for the given operation.
Detailed Description
This class describes a specific conversion target.
Definition at line 595 of file DialectConversion.h.
Member Typedef Documentation
DynamicLegalityCallbackFn
using mlir::ConversionTarget::DynamicLegalityCallbackFn = std::function<bool(Operation *)>
The signature of the callback used to determine if an operation is dynamically legal on the target.
Definition at line 622 of file DialectConversion.h.
Member Enumeration Documentation
LegalizationAction
enum mlir::ConversionTarget::LegalizationAction strong
This enumeration corresponds to the specific action to take when considering an operation legal for this conversion target.
Enumerator
Legal
The target supports this operation.
Dynamic
This operation has dynamic legalization constraints that must be checked by the target.
Illegal
The target explicitly does not support this operation.
Definition at line 599 of file DialectConversion.h.
Constructor & Destructor Documentation
ConversionTarget()
mlir::ConversionTarget::ConversionTarget (MLIRContext & ctx) inline
Definition at line 624 of file DialectConversion.h.
References op.
~ConversionTarget()
virtual mlir::ConversionTarget::~ConversionTarget () virtual default
Member Function Documentation
addDynamicallyLegalDialect() [1/3]
template<typename... Names> void mlir::ConversionTarget::addDynamicallyLegalDialect (StringRef name, Names... names) inline
Register the operations of the given dialects as dynamically legal, i.e.
requiring custom handling by the target via 'isDynamicallyLegal'.
Definition at line 737 of file DialectConversion.h.
Referenced by mlir::populateTensorBufferizePatterns().
addDynamicallyLegalDialect() [2/3]
template<typename... Args> void mlir::ConversionTarget::addDynamicallyLegalDialect (Optional< DynamicLegalityCallbackFn > callback = llvm::None) inline
Definition at line 742 of file DialectConversion.h.
addDynamicallyLegalDialect() [3/3]
template<typename... Args> void mlir::ConversionTarget::addDynamicallyLegalDialect (DynamicLegalityCallbackFn callback) inline
Definition at line 750 of file DialectConversion.h.
addDynamicallyLegalOp() [1/5]
template<typename OpT > void mlir::ConversionTarget::addDynamicallyLegalOp () inline
Register the given operation as dynamically legal, i.e.
requiring custom handling by the target via 'isDynamicallyLegal'.
Definition at line 653 of file DialectConversion.h.
Referenced by mlir::configureArmSVELegalizeForExportTarget(), mlir::configureParallelLoopToGPULegality(), mlir::populateAsyncStructuralTypeConversionsAndLegality(), mlir::populateOpenACCToLLVMConversionPatterns(), mlir::populateOpenACCToSCFConversionPatterns(), mlir::populateOpenMPToLLVMConversionPatterns(), mlir::scf::populateSCFStructuralTypeConversionsAndLegality(), mlir::populateShapeStructuralTypeConversionsAndLegality(), populateSPIRVLayoutInfoPatterns(), mlir::populateStdBufferizePatterns(), mlir::populateTensorConstantBufferizePatterns(), and sourceMaterializationCallback().
addDynamicallyLegalOp() [2/5]
template<typename OpT , typename OpT2 , typename... OpTs> void mlir::ConversionTarget::addDynamicallyLegalOp () inline
Definition at line 657 of file DialectConversion.h.
addDynamicallyLegalOp() [3/5]
template<typename OpT > void mlir::ConversionTarget::addDynamicallyLegalOp (const DynamicLegalityCallbackFn & callback) inline
Register the given operation as dynamically legal and set the dynamic legalization callback to the one provided.
Definition at line 665 of file DialectConversion.h.
addDynamicallyLegalOp() [4/5]
template<typename OpT , typename OpT2 , typename... OpTs> void mlir::ConversionTarget::addDynamicallyLegalOp (const DynamicLegalityCallbackFn & callback) inline
Definition at line 671 of file DialectConversion.h.
References value.
addDynamicallyLegalOp() [5/5]
template<typename OpT , class Callable > std::enable_if< !llvm::is_invocable<Callable, Operation *>::value>::type mlir::ConversionTarget::addDynamicallyLegalOp (Callable && callback) inline
Definition at line 678 of file DialectConversion.h.
References op.
addIllegalDialect() [1/2]
template<typename... Names> void mlir::ConversionTarget::addIllegalDialect (StringRef name, Names... names) inline
Register the operations of the given dialects as illegal, i.e.
operations of this dialect are not supported by the target.
Definition at line 769 of file DialectConversion.h.
Referenced by mlir::configureGpuToNVVMConversionLegality(), mlir::configureGpuToROCDLConversionLegality(), mlir::populateComplexToLLVMConversionPatterns(), and mlir::populateMathToLibmConversionPatterns().
addIllegalDialect() [2/2]
template<typename... Args> void mlir::ConversionTarget::addIllegalDialect () inline
Definition at line 774 of file DialectConversion.h.
References mlir::TypeConverter::isLegal().
addIllegalOp() [1/2]
template<typename OpT > void mlir::ConversionTarget::addIllegalOp () inline
Register the given operation as illegal, i.e.
this operation is known to not be supported by this target.
Definition at line 686 of file DialectConversion.h.
Referenced by mlir::configureAMXLegalizeForExportTarget(), mlir::configureArmSVELegalizeForExportTarget(), configureBasicSVEArithmeticLegalizations(), mlir::configureGpuToNVVMConversionLegality(), mlir::configureGpuToROCDLConversionLegality(), configureSVEMaskGenerationLegalizations(), mlir::configureX86VectorLegalizeForExportTarget(), getSrcVectorElementType(), mlir::populateComplexToStandardConversionPatterns(), mlir::populateLinalgToLLVMConversionPatterns(), mlir::populateLoopToStdConversionPatterns(), mlir::populateStdToLLVMConversionPatterns(), and mlir::populateTensorBufferizePatterns().
addIllegalOp() [2/2]
template<typename OpT , typename OpT2 , typename... OpTs> void mlir::ConversionTarget::addIllegalOp () inline
Definition at line 690 of file DialectConversion.h.
addLegalDialect() [1/2]
template<typename... Names> void mlir::ConversionTarget::addLegalDialect (StringRef name, Names... names) inline
Register the operations of the given dialects as legal.
Definition at line 724 of file DialectConversion.h.
Referenced by mlir::configureGpuToNVVMConversionLegality(), mlir::configureGpuToROCDLConversionLegality(), mlir::configureParallelLoopToGPULegality(), encodeKernelName(), mlir::populateAffineToVectorConversionPatterns(), mlir::populateComplexToStandardConversionPatterns(), mlir::linalg::populateLinalgToStandardConversionPatterns(), mlir::populateMathToLibmConversionPatterns(), mlir::populateOpenACCToLLVMConversionPatterns(), mlir::populateOpenACCToSCFConversionPatterns(), populateSPIRVLayoutInfoPatterns(), mlir::populateStdBufferizePatterns(), mlir::populateTensorBufferizePatterns(), mlir::populateTensorConstantBufferizePatterns(), and mlir::populateVectorToROCDLConversionPatterns().
addLegalDialect() [2/2]
template<typename... Args> void mlir::ConversionTarget::addLegalDialect () inline
Definition at line 729 of file DialectConversion.h.
addLegalOp() [1/2]
template<typename OpT > void mlir::ConversionTarget::addLegalOp () inline
Register the given operations as legal.
Definition at line 641 of file DialectConversion.h.
Referenced by mlir::configureAMXLegalizeForExportTarget(), mlir::configureArmSVELegalizeForExportTarget(), mlir::configureGpuToNVVMConversionLegality(), mlir::configureGpuToROCDLConversionLegality(), mlir::configureX86VectorLegalizeForExportTarget(), getSrcVectorElementType(), mlir::populateBufferizeMaterializationLegality(), mlir::populateComplexToLLVMConversionPatterns(), mlir::populateLinalgToLLVMConversionPatterns(), mlir::linalg::populateLinalgToStandardConversionPatterns(), mlir::populateMemRefToLLVMConversionPatterns(), mlir::populateOpenACCToLLVMConversionPatterns(), mlir::populateOpenMPToLLVMConversionPatterns(), and populateSPIRVLayoutInfoPatterns().
addLegalOp() [2/2]
template<typename OpT , typename OpT2 , typename... OpTs> void mlir::ConversionTarget::addLegalOp () inline
Definition at line 645 of file DialectConversion.h.
getOpAction()
auto ConversionTarget::getOpAction (OperationName op) const
Get the legality action for the given operation.
Definition at line 2686 of file DialectConversion.cpp.
isDynamicallyLegal()
virtual bool mlir::ConversionTarget::isDynamicallyLegal (Operation * op) const inline protected virtual
Runs a custom legalization query for the given operation.
This should return true if the given operation is legal, otherwise false.
Definition at line 794 of file DialectConversion.h.
References mlir::applyAnalysisConversion(), mlir::applyFullConversion(), and mlir::applyPartialConversion().
isLegal()
auto ConversionTarget::isLegal (Operation * op) const
If the given operation instance is legal on this target, a structure containing legality information is returned.
If the operation is not legal, None is returned.
Definition at line 2695 of file DialectConversion.cpp.
References mlir::OperationName::getDialectNamespace(), mlir::Operation::getName(), mlir::ConversionTarget::LegalOpDetails::isRecursivelyLegal, and markOpRecursivelyLegal().
markOpRecursivelyLegal() [1/3]
template<typename OpT > void mlir::ConversionTarget::markOpRecursivelyLegal (const DynamicLegalityCallbackFn & callback = {}) inline
Mark an operation, that must have either been set as Legal or DynamicallyLegal, as being recursively legal.
This means that in addition to the operation itself, all of the operations nested within are also considered legal. An optional dynamic legality callback may be provided to mark subsets of legal instances as recursively legal.
Definition at line 701 of file DialectConversion.h.
Referenced by isLegal().
markOpRecursivelyLegal() [2/3]
template<typename OpT , typename OpT2 , typename... OpTs> void mlir::ConversionTarget::markOpRecursivelyLegal (const DynamicLegalityCallbackFn & callback = {}) inline
Definition at line 706 of file DialectConversion.h.
References value.
markOpRecursivelyLegal() [3/3]
template<typename OpT , class Callable > std::enable_if< !llvm::is_invocable<Callable, Operation *>::value>::type mlir::ConversionTarget::markOpRecursivelyLegal (Callable && callback) inline
Definition at line 713 of file DialectConversion.h.
References op.
markUnknownOpDynamicallyLegal() [1/2]
void mlir::ConversionTarget::markUnknownOpDynamicallyLegal (const DynamicLegalityCallbackFn & fn) inline
Register unknown operations as dynamically legal.
For operations(and dialects) that do not have a set legalization action, treat them as dynamically legal and invoke the given callback if valid or 'isDynamicallyLegal'.
Definition at line 760 of file DialectConversion.h.
Referenced by mlir::linalg::populateElementwiseToLinalgConversionPatterns(), mlir::populateEliminateBufferizeMaterializationsPatterns(), mlir::populateLoopToStdConversionPatterns(), and sourceMaterializationCallback().
markUnknownOpDynamicallyLegal() [2/2]
void mlir::ConversionTarget::markUnknownOpDynamicallyLegal () inline
Definition at line 764 of file DialectConversion.h.
setDialectAction()
void ConversionTarget::setDialectAction (ArrayRef< StringRef > dialectNames, LegalizationAction action)
Register a legality action for the given dialects.
Definition at line 2679 of file DialectConversion.cpp.
setOpAction() [1/2]
void ConversionTarget::setOpAction (OperationName op, LegalizationAction action)
Register a legality action for the given operation.
Definition at line 2673 of file DialectConversion.cpp.
References op.
setOpAction() [2/2]
template<typename OpT > void mlir::ConversionTarget::setOpAction (LegalizationAction action) inline
Definition at line 635 of file DialectConversion.h.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/Utils/DialectConversion.cpp