MLIR: mlir::query::matcher::internal::Diagnostics::ArgStream Class Reference
mlir::query::matcher::internal::Diagnostics::ArgStream Class Reference
#include "Query/Matcher/Diagnostics.h"
Public Member Functions
ArgStream (std::vector< std::string > *out)
template<class T>
ArgStream & operator<< (const T &arg)
ArgStream & operator<< (const llvm::Twine &arg)
Detailed Description
Definition at line 31 of file Diagnostics.h.
Constructor & Destructor Documentation
ArgStream()
mlir::query::matcher::internal::Diagnostics::ArgStream::ArgStream (std::vector< std::string > * out) inline
Definition at line 33 of file Diagnostics.h.
Referenced by operator<<().
Member Function Documentation
operator<<() [1/2]
Diagnostics::ArgStream & mlir::query::matcher::internal::Diagnostics::ArgStream::operator<< (const llvm::Twine & arg)
Definition at line 14 of file Diagnostics.cpp.
operator<<() [2/2]
template<class T> ArgStream & mlir::query::matcher::internal::Diagnostics::ArgStream::operator<< (const T & arg) inline
Definition at line 35 of file Diagnostics.h.
References ArgStream(), and operator<<().
Referenced by operator<<().
The documentation for this class was generated from the following files:
lib/Query/Matcher/Diagnostics.h
lib/Query/Matcher/Diagnostics.cpp