MLIR: mlir::arith::AttrConverterConstrainedFPToLLVM< SourceOp, TargetOp > Class Template Reference
mlir::arith::AttrConverterConstrainedFPToLLVM< SourceOp, TargetOp > Class Template Reference
#include "mlir/Conversion/ArithCommon/AttrToLLVMConverter.h"
Public Member Functions
AttrConverterConstrainedFPToLLVM (SourceOp srcOp)
ArrayRef< NamedAttribute > getAttrs () const
LLVM::IntegerOverflowFlags getOverflowFlags () const
Detailed Description
template<typename SourceOp, typename TargetOp>
class mlir::arith::AttrConverterConstrainedFPToLLVM< SourceOp, TargetOp >
Definition at line 105 of file AttrToLLVMConverter.h.
Constructor & Destructor Documentation
AttrConverterConstrainedFPToLLVM()
template<typename SourceOp , typename TargetOp > mlir::arith::AttrConverterConstrainedFPToLLVM< SourceOp, TargetOp >::AttrConverterConstrainedFPToLLVM (SourceOp srcOp) inline
Definition at line 112 of file AttrToLLVMConverter.h.
References mlir::arith::convertArithRoundingModeAttrToLLVM(), mlir::NamedAttrList::erase(), mlir::NamedAttrList::getAttrs(), mlir::arith::getLLVMDefaultFPExceptionBehavior(), mlir::op_definition_impl::hasTrait(), and mlir::NamedAttrList::set().
Member Function Documentation
getAttrs()
template<typename SourceOp , typename TargetOp > ArrayRef<NamedAttribute> mlir::arith::AttrConverterConstrainedFPToLLVM< SourceOp, TargetOp >::getAttrs () const inline
Definition at line 131 of file AttrToLLVMConverter.h.
References mlir::NamedAttrList::getAttrs().
getOverflowFlags()
template<typename SourceOp , typename TargetOp > LLVM::IntegerOverflowFlags mlir::arith::AttrConverterConstrainedFPToLLVM< SourceOp, TargetOp >::getOverflowFlags () const inline
Definition at line 132 of file AttrToLLVMConverter.h.
The documentation for this class was generated from the following file:
include/mlir/Conversion/ArithCommon/AttrToLLVMConverter.h