MLIR: mlir::ValueUseIterator< OperandType > Class Template Reference
mlir::ValueUseIterator< OperandType > Class Template Reference
An iterator class that allows for iterating over the uses of an IR operand type.
#include "mlir/IR/UseDefLists.h"
Public Member Functions
ValueUseIterator (detail::IROperandBase *use=nullptr)
Operation * getUser () const
Returns the operation that owns this use.
OperandType * getOperand () const
Returns the current operands.
OperandType & operator* () const
ValueUseIterator & operator++ ()
bool operator== (const ValueUseIterator &rhs) const
Protected Attributes
detail::IROperandBase * current
Detailed Description
template<typename OperandType>
class mlir::ValueUseIterator< OperandType >
An iterator class that allows for iterating over the uses of an IR operand type.
Definition at line 303 of file UseDefLists.h.
Constructor & Destructor Documentation
ValueUseIterator()
template<typename OperandType > mlir::ValueUseIterator< OperandType >::ValueUseIterator (detail::IROperandBase * use = nullptr) inline
Definition at line 308 of file UseDefLists.h.
Member Function Documentation
getOperand()
template<typename OperandType > OperandType* mlir::ValueUseIterator< OperandType >::getOperand () const inline
Returns the current operands.
Definition at line 314 of file UseDefLists.h.
References mlir::ValueUseIterator< OperandType >::current.
Referenced by mlirValueGetFirstUse(), mlir::ValueUseIterator< OperandType >::operator*(), mlir::ResultRange::UseIterator::operator*(), and mlir::ResultRange::UseIterator::operator->().
getUser()
template<typename OperandType > Operation* mlir::ValueUseIterator< OperandType >::getUser () const inline
Returns the operation that owns this use.
Definition at line 311 of file UseDefLists.h.
References mlir::ValueUseIterator< OperandType >::current, and mlir::detail::IROperandBase::getOwner().
operator*()
template<typename OperandType > OperandType& mlir::ValueUseIterator< OperandType >::operator* () const inline
Definition at line 315 of file UseDefLists.h.
References mlir::ValueUseIterator< OperandType >::getOperand().
operator++()
template<typename OperandType > ValueUseIterator& mlir::ValueUseIterator< OperandType >::operator++ () inline
Definition at line 320 of file UseDefLists.h.
References mlir::ValueUseIterator< OperandType >::current, and mlir::detail::IROperandBase::getNextOperandUsingThisValue().
operator==()
template<typename OperandType > bool mlir::ValueUseIterator< OperandType >::operator== (const ValueUseIterator< OperandType > & rhs) const inline
Definition at line 326 of file UseDefLists.h.
References mlir::ValueUseIterator< OperandType >::current.
Member Data Documentation
current
template<typename OperandType > detail::IROperandBase* mlir::ValueUseIterator< OperandType >::current protected
Definition at line 331 of file UseDefLists.h.
Referenced by mlir::ValueUseIterator< OperandType >::getOperand(), mlir::ValueUseIterator< OperandType >::getUser(), mlir::ValueUseIterator< OperandType >::operator++(), and mlir::ValueUseIterator< OperandType >::operator==().
The documentation for this class was generated from the following file:
include/mlir/IR/UseDefLists.h