MLIR: mlir::LLVMTypeConverter Class Reference
mlir::LLVMTypeConverter Class Reference
Conversion from types to the LLVM IR dialect.
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
Public Member Functions
LLVMTypeConverter (MLIRContext *ctx, const DataLayoutAnalysis *analysis=nullptr)
Create an LLVMTypeConverter using the default LowerToLLVMOptions.
LLVMTypeConverter (MLIRContext *ctx, const LowerToLLVMOptions &options, const DataLayoutAnalysis *analysis=nullptr)
Create an LLVMTypeConverter using custom LowerToLLVMOptions.
Type convertFunctionSignature (FunctionType funcTy, bool isVariadic, bool useBarePtrCallConv, SignatureConversion &result) const
Convert a function type.
Type convertFunctionSignature (FunctionOpInterface funcOp, bool isVariadic, bool useBarePtrCallConv, LLVMTypeConverter::SignatureConversion &result, SmallVectorImpl< std::optional< NamedAttribute >> &byValRefNonPtrAttrs) const
Convert a function type.
Type packFunctionResults (TypeRange types, bool useBarePointerCallConv=false) const
Convert a non-empty list of types to be returned from a function into an LLVM-compatible type.
Type packOperationResults (TypeRange types) const
Convert a non-empty list of types of values produced by an operation into an LLVM-compatible type.
Type convertCallingConventionType (Type type, bool useBarePointerCallConv=false) const
Convert a type in the context of the default or bare pointer calling convention.
void promoteBarePtrsToDescriptors (ConversionPatternRewriter &rewriter, Location loc, ArrayRef< Type > stdTypes, SmallVectorImpl< Value > &values) const
Promote the bare pointers in 'values' that resulted from memrefs to descriptors.
MLIRContext & getContext () const
Returns the MLIR context.
LLVM::LLVMDialect * getDialect () const
Returns the LLVM dialect.
const LowerToLLVMOptions & getOptions () const
SmallVector< Value, 4 > promoteOperands (Location loc, ValueRange opOperands, ValueRange operands, OpBuilder &builder, bool useBarePtrCallConv=false) const
Promote the LLVM representation of all operands including promoting MemRef descriptors to stack and use pointers to struct to avoid the complexity of the platform-specific C/C++ ABI lowering related to struct argument passing.
Value promoteOneMemRefDescriptor (Location loc, Value operand, OpBuilder &builder) const
Promote the LLVM struct representation of one MemRef descriptor to stack and use pointer to struct to avoid the complexity of the platform-specific C/C++ ABI lowering related to struct argument passing.
std::pair< LLVM::LLVMFunctionType, LLVM::LLVMStructType > convertFunctionTypeCWrapper (FunctionType type) const
Converts the function type to a C-compatible format, in particular using pointers to memref descriptors for arguments.
const llvm::DataLayout & getDataLayout () const
Returns the data layout to use during and after conversion.
const DataLayoutAnalysis * getDataLayoutAnalysis () const
Returns the data layout analysis to query during conversion.
Type getIndexType () const
Gets the LLVM representation of the index type.
unsigned getIndexTypeBitwidth () const
Gets the bitwidth of the index type when converted to LLVM.
unsigned getPointerBitwidth (unsigned addressSpace=0) const
Gets the pointer bitwidth.
unsigned getMemRefDescriptorSize (MemRefType type, const DataLayout &layout) const
Returns the size of the memref descriptor object in bytes.
unsigned getUnrankedMemRefDescriptorSize (UnrankedMemRefType type, const DataLayout &layout) const
Returns the size of the unranked memref descriptor object in bytes.
FailureOr< unsigned > getMemRefAddressSpace (BaseMemRefType type) const
Return the LLVM address space corresponding to the memory space of the memref type type or failure if the memory space cannot be converted to an integer.
SmallVector< Type, 5 > getMemRefDescriptorFields (MemRefType type, bool unpackAggregates) const
Convert a memref type into a list of LLVM IR types that will form the memref descriptor.
SmallVector< Type, 2 > getUnrankedMemRefDescriptorFields () const
Convert an unranked memref type into a list of non-aggregate LLVM IR types that will form the unranked memref descriptor.
LogicalResult convertType (Type t, SmallVectorImpl< Type > &results) const
Convert the given type.
Type convertType (Type t) const
This hook simplifies defining 1-1 type conversions.
template<typename TargetType >
TargetType convertType (Type t) const
Attempts a 1-1 type conversion, expecting the result type to be TargetType.
Public Member Functions inherited from mlir::TypeConverter
virtual ~TypeConverter ()=default
TypeConverter ()=default
TypeConverter (const TypeConverter &other)
TypeConverter & operator= (const TypeConverter &other)
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<0>>
void addConversion (FnT &&callback)
Register a conversion function.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addSourceMaterialization (FnT &&callback)
All of the following materializations require function objects that are convertible to the following form: Value(OpBuilder &, T, ValueRange, Location), where T is any subclass of Type.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addTargetMaterialization (FnT &&callback)
This method registers a materialization that will be called when converting a value to a target type according to a pattern's type converter.
template<typename FnT , typename T = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<0>, typename A = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<1>>
void addTypeAttributeConversion (FnT &&callback)
Register a conversion function for attributes within types.
LogicalResult convertType (Type t, SmallVectorImpl< Type > &results) const
Convert the given type.
Type convertType (Type t) const
This hook simplifies defining 1-1 type conversions.
template<typename TargetType >
TargetType convertType (Type t) const
Attempts a 1-1 type conversion, expecting the result type to be TargetType.
LogicalResult convertTypes (TypeRange types, SmallVectorImpl< Type > &results) const
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type) const
Return true if the given type is legal for this type converter, i.e.
template<typename RangeT >
std::enable_if_t<!std::is_convertible< RangeT, Type >::value &&!std::is_convertible< RangeT, Operation * >::value, bool > isLegal (RangeT &&range) const
Return true if all of the given types are legal for this type converter.
bool isLegal (Operation *op) const
Return true if the given operation has legal operand and result types.
bool isLegal (Region *region) const
Return true if the types of block arguments within the region are legal.
bool isSignatureLegal (FunctionType ty) const
Return true if the inputs and outputs of the given function type are legal.
LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result) const
This method allows for converting a specific argument of a signature.
LogicalResult convertSignatureArgs (TypeRange types, SignatureConversion &result, unsigned origInputOffset=0) const
std::optional< SignatureConversion > convertBlockSignature (Block *block) const
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
Value materializeSourceConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs) const
Materialize a conversion from a set of types into one result type by generating a cast sequence of some kind.
Value materializeTargetConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs, Type originalType={}) const
SmallVector< Value > materializeTargetConversion (OpBuilder &builder, Location loc, TypeRange resultType, ValueRange inputs, Type originalType={}) const
std::optional< Attribute > convertTypeAttribute (Type type, Attribute attr) const
Convert an attribute present attr from within the type type using the registered conversion functions.
Static Public Member Functions
static bool canConvertToBarePtr (BaseMemRefType type)
Check if a memref type can be converted to a bare pointer.
Protected Member Functions
SmallVector< Type > & getCurrentThreadRecursiveStack ()
Protected Attributes
LLVM::LLVMDialect * llvmDialect
Pointer to the LLVM dialect.
DenseMap< uint64_t, std::unique_ptr< SmallVector< Type > > > conversionCallStack
llvm::sys::SmartRWMutex< true > callStackMutex
Friends
LogicalResult structFuncArgTypeConverter (const LLVMTypeConverter &converter, Type type, SmallVectorImpl< Type > &result)
Give structFuncArgTypeConverter access to memref-specific functions.
Detailed Description
Conversion from types to the LLVM IR dialect.
Definition at line 35 of file TypeConverter.h.
Constructor & Destructor Documentation
LLVMTypeConverter() [1/2]
LLVMTypeConverter::LLVMTypeConverter (MLIRContext * ctx, const DataLayoutAnalysis * analysis = nullptr)
Create an LLVMTypeConverter using the default LowerToLLVMOptions.
Create an LLVMTypeConverter using default LowerToLLVMOptions.
Optionally takes a data layout analysis to use in conversions.
Definition at line 42 of file TypeConverter.cpp.
LLVMTypeConverter() [2/2]
LLVMTypeConverter::LLVMTypeConverter (MLIRContext * ctx, const LowerToLLVMOptions & options, const DataLayoutAnalysis * analysis = nullptr)
Create an LLVMTypeConverter using custom LowerToLLVMOptions.
Optionally takes a data layout analysis to use in conversions.
Definition at line 115 of file TypeConverter.cpp.
References mlir::TypeConverter::addConversion(), mlir::TypeConverter::addSourceMaterialization(), mlir::TypeConverter::addTargetMaterialization(), mlir::TypeConverter::addTypeAttributeConversion(), convertType(), mlir::TypeConverter::convertTypes(), mlir::get(), getCurrentThreadRecursiveStack(), mlir::LLVM::isCompatibleType(), llvmDialect, packRankedMemRefDesc(), packUnrankedMemRefDesc(), rankedMemRefMaterialization(), and unrankedMemRefMaterialization().
Member Function Documentation
canConvertToBarePtr()
bool LLVMTypeConverter::canConvertToBarePtr (BaseMemRefType type) static
Check if a memref type can be converted to a bare pointer.
Definition at line 592 of file TypeConverter.cpp.
Referenced by canBeCalledWithBarePointers().
convertCallingConventionType()
Type LLVMTypeConverter::convertCallingConventionType (Type type, bool useBarePtrCallConv = false) const
Convert a type in the context of the default or bare pointer calling convention.
Calling convention sensitive types, such as MemRefType and UnrankedMemRefType, are converted following the specific rules for the calling convention. Calling convention independent types are converted following the default LLVM type conversions.
Definition at line 661 of file TypeConverter.cpp.
References convertType().
Referenced by mlir::barePtrFuncArgTypeConverter(), and packFunctionResults().
convertFunctionSignature() [1/2]
Type LLVMTypeConverter::convertFunctionSignature (FunctionOpInterface funcOp, bool isVariadic, bool useBarePtrCallConv, LLVMTypeConverter::SignatureConversion & result, SmallVectorImpl< std::optional< NamedAttribute >> & byValRefNonPtrAttrs) const
Convert a function type.
The arguments and results are converted one by one and results are packed into a wrapped LLVM IR structure type. result is populated with argument mapping. Converted types of llvm.byval and llvm.byref function arguments which are not LLVM pointers are overridden with LLVM pointers. Overridden arguments are returned in byValRefNonPtrAttrs.
Definition at line 410 of file TypeConverter.cpp.
References filterByValRefArgAttrs().
convertFunctionSignature() [2/2]
Type LLVMTypeConverter::convertFunctionSignature (FunctionType funcTy, bool isVariadic, bool useBarePtrCallConv, LLVMTypeConverter::SignatureConversion & result) const
Convert a function type.
The arguments and results are converted one by one and results are packed into a wrapped LLVM IR structure type. result is populated with argument mapping.
Definition at line 402 of file TypeConverter.cpp.
Referenced by mlir::convertFuncOpToLLVMFuncOp(), and mlir::GPUFuncOpLowering::matchAndRewrite().
convertFunctionTypeCWrapper()
std::pair< LLVM::LLVMFunctionType, LLVM::LLVMStructType > LLVMTypeConverter::convertFunctionTypeCWrapper (FunctionType type) const
Converts the function type to a C-compatible format, in particular using pointers to memref descriptors for arguments.
Also converts the return type to a pointer argument if it is a struct. Returns true if this was the case.
Definition at line 426 of file TypeConverter.cpp.
References convertType(), mlir::get(), getContext(), mlir::LLVM::isCompatibleType(), and packFunctionResults().
Referenced by wrapExternalFunction(), and wrapForExternalCallers().
convertType() [1/3]
Type TypeConverter::convertType
This hook simplifies defining 1-1 type conversions.
This function returns the type to convert to on success, and a null type on failure.
Definition at line 253 of file DialectConversion.cpp.
convertType() [2/3]
template<typename TargetType > TargetType mlir::TypeConverter::convertType (typename TargetType) inline
Attempts a 1-1 type conversion, expecting the result type to be TargetType.
Returns the converted type cast to TargetType on success, and a null type on conversion or cast failure.
Definition at line 259 of file DialectConversion.h.
convertType() [3/3]
LogicalResult TypeConverter::convertType
Convert the given type.
This function should return failure if no valid conversion exists, success otherwise. If the new set of types is empty, the type is removed and any usages of the existing value are expected to be removed during conversion.
Definition at line 249 of file DialectConversion.cpp.
Referenced by mlir::MemRefDescriptor::bufferPtr(), convertCallingConventionType(), mlir::convertFuncOpToLLVMFuncOp(), convertFunctionTypeCWrapper(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), mlir::LLVM::detail::extractNDVectorTypeInfo(), extractOne(), mlir::MemRefDescriptor::fromStaticShape(), getDynamicSharedMemorySymbol(), getIndexedPtrs(), getMemRefAlignment(), getMemRefDescriptorFields(), mlir::LLVM::getStridedElementPtr(), getVectorAlignment(), insertOne(), LLVMTypeConverter(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::MemRefDescriptor::pack(), mlir::UnrankedMemRefDescriptor::pack(), packOperationResults(), restoreByValRefArgumentType(), mlir::impl::scalarizeVectorOp(), scalarizeVectorOpHelper(), mlir::structFuncArgTypeConverter(), wrapExternalFunction(), and wrapForExternalCallers().
getContext()
MLIRContext & LLVMTypeConverter::getContext () const
Returns the MLIR context.
Definition at line 275 of file TypeConverter.cpp.
References getDialect().
Referenced by addOpaquePointerConversion(), convertFunctionTypeCWrapper(), getCurrentThreadRecursiveStack(), getIndexType(), getUnrankedMemRefDescriptorFields(), packFunctionResults(), packOperationResults(), mlir::populateAMXLegalizeForLLVMExportPatterns(), mlir::populateGpuToLLVMSPVConversionPatterns(), and mlir::populateGpuToNVVMConversionPatterns().
getCurrentThreadRecursiveStack()
SmallVector< Type > & LLVMTypeConverter::getCurrentThreadRecursiveStack () protected
Definition at line 21 of file TypeConverter.cpp.
References callStackMutex, conversionCallStack, and getContext().
Referenced by LLVMTypeConverter().
getDataLayout()
const llvm::DataLayout& mlir::LLVMTypeConverter::getDataLayout () const inline
Returns the data layout to use during and after conversion.
Definition at line 131 of file TypeConverter.h.
References mlir::LowerToLLVMOptions::dataLayout.
Referenced by getMemRefAlignment(), and getVectorAlignment().
getDataLayoutAnalysis()
const DataLayoutAnalysis* mlir::LLVMTypeConverter::getDataLayoutAnalysis () const inline
Returns the data layout analysis to query during conversion.
Definition at line 134 of file TypeConverter.h.
getDialect()
LLVM::LLVMDialect* mlir::LLVMTypeConverter::getDialect () const inline
Returns the LLVM dialect.
Definition at line 105 of file TypeConverter.h.
References llvmDialect.
Referenced by getContext(), mlir::ConvertToLLVMPattern::getDialect(), and mlir::populateVectorToLLVMConversionPatterns().
getIndexType()
Type LLVMTypeConverter::getIndexType () const
Gets the LLVM representation of the index type.
The returned type is an integer type with the size configured for this type converter.
Definition at line 279 of file TypeConverter.cpp.
References mlir::get(), getContext(), and getIndexTypeBitwidth().
Referenced by mlir::MemRefDescriptor::bufferPtr(), mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), mlir::ConvertToLLVMPattern::getIndexType(), getMemRefDescriptorFields(), getMemRefDescriptorSize(), mlir::LLVM::getStridedElementPtr(), getUnrankedMemRefDescriptorFields(), getUnrankedMemRefDescriptorSize(), mlir::UnrankedMemRefDescriptor::offset(), mlir::UnrankedMemRefDescriptor::setSize(), mlir::UnrankedMemRefDescriptor::setStride(), mlir::UnrankedMemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), mlir::UnrankedMemRefDescriptor::stride(), and mlir::UnrankedMemRefDescriptor::strideBasePtr().
getIndexTypeBitwidth()
unsigned mlir::LLVMTypeConverter::getIndexTypeBitwidth () const inline
Gets the bitwidth of the index type when converted to LLVM.
Definition at line 143 of file TypeConverter.h.
References mlir::LowerToLLVMOptions::getIndexBitwidth().
Referenced by mlir::UnrankedMemRefDescriptor::computeSizes(), getIndexType(), and truncOrExtToLLVMType().
getMemRefAddressSpace()
FailureOr< unsigned > LLVMTypeConverter::getMemRefAddressSpace (BaseMemRefType type) const
Return the LLVM address space corresponding to the memory space of the memref type type or failure if the memory space cannot be converted to an integer.
Definition at line 574 of file TypeConverter.cpp.
References mlir::TypeConverter::convertTypeAttribute(), and mlir::BaseMemRefType::getMemorySpace().
Referenced by mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), getDynamicSharedMemorySymbol(), mlir::ConvertToLLVMPattern::getElementPtrType(), getMemRefDescriptorFields(), getMemRefDescriptorSize(), getUnrankedMemRefDescriptorSize(), and isMemRefTypeSupported().
getMemRefDescriptorFields()
SmallVector< Type, 5 > LLVMTypeConverter::getMemRefDescriptorFields (MemRefType type, bool unpackAggregates) const
Convert a memref type into a list of LLVM IR types that will form the memref descriptor.
If unpackAggregates is true the sizes and strides arrays in the descriptors are unpacked to individual index-typed elements, else they are kept as rank-sized arrays of index type. In particular, the list will contain:
two pointers to the memref element type, followed by
an index-typed offset, followed by
(if unpackAggregates = true)
one index-typed size per dimension of the memref, followed by
one index-typed stride per dimension of the memref.
(if unpackArrregates = false)
one rank-sized array of index-type for the size of each dimension
one rank-sized array of index-type for the stride of each dimension
For example, memref<?x?xf32> is converted to the following list:
!llvm<"float*"> (allocated pointer),
!llvm<"float*"> (aligned pointer),
i64 (offset),
i64, i64 (sizes),
i64, i64 (strides). These types can be recomposed to a memref descriptor struct.
The result contains the following types:
The pointer to the allocated data buffer, followed by
The pointer to the aligned data buffer, followed by
A lowered index-type integer containing the distance between the beginning of the buffer and the first element to be accessed through the view, followed by
An array containing as many index-type integers as the rank of the MemRef: the array represents the size, in number of elements, of the memref along the given dimension. For constant MemRef dimensions, the corresponding size entry is a constant whose runtime value must match the static value, followed by
A second array containing as many index-type integers as the rank of the MemRef: the second array represents the "stride" (in tensor abstraction sense), i.e. the number of consecutive elements of the underlying buffer. TODO: add assertions for the static cases.
If unpackAggregates is set to true, the arrays described in (4) and (5) are expanded into individual index-type elements.
template <typename Elem, typename Index, size_t Rank> struct { Elem *allocatedPtr; Elem *alignedPtr; Index offset; Index sizes[Rank]; // omitted when rank == 0 Index strides[Rank]; // omitted when rank == 0 };
Definition at line 485 of file TypeConverter.cpp.
References convertType(), mlir::emitError(), mlir::get(), getIndexType(), and getMemRefAddressSpace().
Referenced by packRankedMemRefDesc(), and mlir::structFuncArgTypeConverter().
getMemRefDescriptorSize()
unsigned LLVMTypeConverter::getMemRefDescriptorSize (MemRefType type, const DataLayout & layout) const
Returns the size of the memref descriptor object in bytes.
Definition at line 525 of file TypeConverter.cpp.
References mlir::detail::divideCeil(), getIndexType(), getMemRefAddressSpace(), getPointerBitwidth(), and mlir::DataLayout::getTypeSize().
getOptions()
const LowerToLLVMOptions& mlir::LLVMTypeConverter::getOptions () const inline
Definition at line 107 of file TypeConverter.h.
Referenced by mlir::GPUReturnOpLowering::matchAndRewrite(), mlir::populateFinalizeMemRefToLLVMConversionPatterns(), and shouldUseBarePtrCallConv().
getPointerBitwidth()
unsigned LLVMTypeConverter::getPointerBitwidth (unsigned addressSpace = 0) const
Gets the pointer bitwidth.
Definition at line 283 of file TypeConverter.cpp.
References mlir::LowerToLLVMOptions::dataLayout.
Referenced by mlir::UnrankedMemRefDescriptor::computeSizes(), getMemRefDescriptorSize(), and getUnrankedMemRefDescriptorSize().
getUnrankedMemRefDescriptorFields()
SmallVector< Type, 2 > LLVMTypeConverter::getUnrankedMemRefDescriptorFields () const
Convert an unranked memref type into a list of non-aggregate LLVM IR types that will form the unranked memref descriptor.
In particular, this list contains:
an integer rank, followed by
a pointer to the memref descriptor struct. For example, memref<xf32> is converted to the following list: i64 (rank) !llvm<"i8</em>"> (type-erased pointer). These types can be recomposed to a unranked memref descriptor struct.
In particular, the fields for an unranked memref descriptor are:
index-typed rank, the dynamic rank of this MemRef
void* ptr, pointer to the static ranked MemRef descriptor. This will be stack allocated (alloca) copy of a MemRef descriptor that got casted to be unranked.
Definition at line 553 of file TypeConverter.cpp.
References mlir::get(), getContext(), and getIndexType().
Referenced by packUnrankedMemRefDesc(), and mlir::structFuncArgTypeConverter().
getUnrankedMemRefDescriptorSize()
unsigned LLVMTypeConverter::getUnrankedMemRefDescriptorSize (UnrankedMemRefType type, const DataLayout & layout) const
Returns the size of the unranked memref descriptor object in bytes.
Definition at line 557 of file TypeConverter.cpp.
References mlir::detail::divideCeil(), getIndexType(), getMemRefAddressSpace(), getPointerBitwidth(), and mlir::DataLayout::getTypeSize().
packFunctionResults()
Type LLVMTypeConverter::packFunctionResults (TypeRange types, bool useBarePtrCallConv = false) const
Convert a non-empty list of types to be returned from a function into an LLVM-compatible type.
In particular, if more than one value is returned, create an LLVM dialect structure type with elements that correspond to each of the types converted with convertCallingConventionType.
Definition at line 709 of file TypeConverter.cpp.
References convertCallingConventionType(), getContext(), mlir::LLVM::isCompatibleType(), and mlir::LowerToLLVMOptions::useBarePtrCallConv.
Referenced by convertFunctionTypeCWrapper(), and mlir::GPUReturnOpLowering::matchAndRewrite().
packOperationResults()
Type LLVMTypeConverter::packOperationResults (TypeRange types) const
Convert a non-empty list of types of values produced by an operation into an LLVM-compatible type.
In particular, if more than one value is produced, create a literal structure with elements that correspond to each of the LLVM-compatible types converted with convertType.
In particular, if more than one value is produced, create a literal structure with elements that correspond to each of the types converted with convertType.
Definition at line 688 of file TypeConverter.cpp.
References convertType(), getContext(), and mlir::LLVM::isCompatibleType().
Referenced by mlir::LLVM::detail::intrinsicRewrite(), and mlir::LLVM::detail::oneToOneRewrite().
promoteBarePtrsToDescriptors()
void LLVMTypeConverter::promoteBarePtrsToDescriptors (ConversionPatternRewriter & rewriter, Location loc, ArrayRef< Type > stdTypes, SmallVectorImpl< Value > & values) const
Promote the bare pointers in 'values' that resulted from memrefs to descriptors.
'stdTypes' holds the types of 'values' before the conversion to the LLVM-IR dialect (i.e., MemRefType, or any other builtin type).
'stdTypes' holds they types of 'values' before the conversion to the LLVM-IR dialect (i.e., MemRefType, or any other builtin type).
Definition at line 673 of file TypeConverter.cpp.
References mlir::MemRefDescriptor::fromStaticShape().
promoteOneMemRefDescriptor()
Value LLVMTypeConverter::promoteOneMemRefDescriptor (Location loc, Value operand, OpBuilder & builder) const
Promote the LLVM struct representation of one MemRef descriptor to stack and use pointer to struct to avoid the complexity of the platform-specific C/C++ ABI lowering related to struct argument passing.
Definition at line 729 of file TypeConverter.cpp.
References mlir::get(), mlir::Builder::getContext(), mlir::Builder::getI64Type(), mlir::Builder::getIndexAttr(), and mlir::Value::getType().
promoteOperands()
SmallVector< Value, 4 > LLVMTypeConverter::promoteOperands (Location loc, ValueRange opOperands, ValueRange operands, OpBuilder & builder, bool useBarePtrCallConv = false) const
Promote the LLVM representation of all operands including promoting MemRef descriptors to stack and use pointers to struct to avoid the complexity of the platform-specific C/C++ ABI lowering related to struct argument passing.
Definition at line 744 of file TypeConverter.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::MemRefDescriptor::unpack(), mlir::UnrankedMemRefDescriptor::unpack(), and mlir::LowerToLLVMOptions::useBarePtrCallConv.
Friends And Related Function Documentation
structFuncArgTypeConverter
LogicalResult structFuncArgTypeConverter (const LLVMTypeConverter & converter, Type type, SmallVectorImpl< Type > & result) friend
Give structFuncArgTypeConverter access to memref-specific functions.
It converts a MemRef function argument to a list of non-aggregate types containing descriptor information, and an UnrankedmemRef function argument to a list containing the rank and a pointer to a descriptor struct.
Member Data Documentation
callStackMutex
llvm::sys::SmartRWMutex<true> mlir::LLVMTypeConverter::callStackMutex protected
Definition at line 206 of file TypeConverter.h.
Referenced by getCurrentThreadRecursiveStack().
conversionCallStack
DenseMap<uint64_t, std::unique_ptr<SmallVector<Type> > > mlir::LLVMTypeConverter::conversionCallStack protected
Definition at line 205 of file TypeConverter.h.
Referenced by getCurrentThreadRecursiveStack().
llvmDialect
LLVM::LLVMDialect* mlir::LLVMTypeConverter::llvmDialect protected
Pointer to the LLVM dialect.
Definition at line 201 of file TypeConverter.h.
Referenced by getDialect(), and LLVMTypeConverter().
The documentation for this class was generated from the following files:
include/mlir/Conversion/LLVMCommon/TypeConverter.h
lib/Conversion/LLVMCommon/TypeConverter.cpp