MLIR: mlir::python::PyAsmState Class Reference
mlir::python::PyAsmState Class Reference
Wrapper around an MlirAsmState.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyAsmState (MlirValue value, bool useLocalScope)
PyAsmState (PyOperationBase &operation, bool useLocalScope)
~PyAsmState ()
PyAsmState (PyAsmState &other)=delete
PyAsmState (const PyAsmState &other)=delete
MlirAsmState get ()
Detailed Description
Wrapper around an MlirAsmState.
Definition at line 778 of file IRModule.h.
Constructor & Destructor Documentation
PyAsmState() [1/4]
mlir::python::PyAsmState::PyAsmState (MlirValue value, bool useLocalScope) inline
Definition at line 780 of file IRModule.h.
References mlirAsmStateCreateForValue(), mlirOpPrintingFlagsCreate(), and mlirOpPrintingFlagsUseLocalScope().
Referenced by PyAsmState(), and PyAsmState().
PyAsmState() [2/4]
mlir::python::PyAsmState::PyAsmState (PyOperationBase & operation, bool useLocalScope) inline
Definition at line 789 of file IRModule.h.
References mlir::python::PyOperation::get(), mlir::python::PyOperationBase::getOperation(), mlirAsmStateCreateForOperation(), mlirOpPrintingFlagsCreate(), and mlirOpPrintingFlagsUseLocalScope().
~PyAsmState()
mlir::python::PyAsmState::~PyAsmState () inline
Definition at line 798 of file IRModule.h.
References mlirOpPrintingFlagsDestroy().
PyAsmState() [3/4]
mlir::python::PyAsmState::PyAsmState (PyAsmState & other) delete
References PyAsmState().
PyAsmState() [4/4]
mlir::python::PyAsmState::PyAsmState (const PyAsmState & other) delete
References PyAsmState().
Member Function Documentation
get()
MlirAsmState mlir::python::PyAsmState::get () inline
Definition at line 803 of file IRModule.h.
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRModule.h