MLIR: mlir::spirv::RuntimeArrayType Class Reference
mlir::spirv::RuntimeArrayType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Member Functions
Type getElementType () const
unsigned getArrayStride () const
Returns the array stride in bytes.
Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Public Member Functions
static RuntimeArrayType get (Type elementType)
static RuntimeArrayType get (Type elementType, unsigned stride)
Returns a runtime array type with the given stride in bytes.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
static HasTraitFn getHasTraitFn ()
Returns the function that returns true if the given Trait ID matches the IDs of any of the traits defined by the storage user.
static auto getWalkImmediateSubElementsFn ()
Returns a function that walks immediate sub elements of a given instance of the storage user.
static auto getReplaceImmediateSubElementsFn ()
Returns a function that replaces immediate sub elements of a given instance of the storage user.
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
static ConcreteType get (MLIRContext *ctx, Args &&...args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getChecked (const Location &loc, Args &&...args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteType getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteType getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr StringLiteral name = "spirv.rtarray"
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
using Base
Utility declarations for the concrete attribute class.
using ImplType
using HasTraitFn
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
static LogicalResult verifyInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 190 of file SPIRVTypes.h.
Member Function Documentation
get() [1/2]
RuntimeArrayType RuntimeArrayType::get (Type elementType) static
Definition at line 509 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), and mlir::Type::getContext().
Referenced by parseRuntimeArrayType(), and mlir::spirv::Deserializer::processRuntimeArrayType().
get() [2/2]
RuntimeArrayType RuntimeArrayType::get (Type elementType, unsigned stride) static
Returns a runtime array type with the given stride in bytes.
Definition at line 513 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), and mlir::Type::getContext().
getArrayStride()
unsigned RuntimeArrayType::getArrayStride () const
Returns the array stride in bytes.
0 means no stride decorated on this type.
Definition at line 519 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by convertRuntimeArrayType(), print(), and mlir::spirv::Serializer::processTypeDecoration< spirv::RuntimeArrayType >().
getElementType()
Type RuntimeArrayType::getElementType () const
Definition at line 517 of file SPIRVTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::getImpl().
Referenced by convertRuntimeArrayType(), and print().
Member Data Documentation
name
StringLiteral mlir::spirv::RuntimeArrayType::name = "spirv.rtarray" static constexpr
Definition at line 196 of file SPIRVTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp