MLIR: mlir::OpConversionPattern< SourceOp > Class Template Reference
mlir::OpConversionPattern< SourceOp > Class Template Reference
OpConversionPattern is a wrapper around ConversionPattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
#include "mlir/Transforms/DialectConversion.h"
Public Types
using OpAdaptor = typename SourceOp::Adaptor
using OneToNOpAdaptor = typename SourceOp::template GenericAdaptor< ArrayRef< ValueRange > >
Public Member Functions
OpConversionPattern (MLIRContext *context, PatternBenefit benefit=1)
OpConversionPattern (const TypeConverter &typeConverter, MLIRContext *context, PatternBenefit benefit=1)
LogicalResult match (Operation *op) const final
Wrappers around the ConversionPattern methods that pass the derived op type.
void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement rewriting.
void rewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const final
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
virtual LogicalResult match (SourceOp op) const
Rewrite and Match methods that operate on the SourceOp type.
virtual void rewrite (SourceOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
virtual void rewrite (SourceOp op, OneToNOpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
virtual LogicalResult matchAndRewrite (SourceOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
virtual LogicalResult matchAndRewrite (SourceOp op, OneToNOpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
Public Member Functions inherited from mlir::ConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
const TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, const ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::ConversionPattern
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
SmallVector< Value > getOneToOneAdaptorOperands (ArrayRef< ValueRange > operands) const
Given an array of value ranges, which are the inputs to a 1:N adaptor, try to extract the single value of each range to construct a the inputs for a 1:1 adaptor.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::ConversionPattern
const TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
template<typename SourceOp>
class mlir::OpConversionPattern< SourceOp >
OpConversionPattern is a wrapper around ConversionPattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
Definition at line 614 of file DialectConversion.h.
Member Typedef Documentation
OneToNOpAdaptor
template<typename SourceOp > using mlir::OpConversionPattern< SourceOp >::OneToNOpAdaptor = typename SourceOp::template GenericAdaptor<ArrayRef<ValueRange> >
Definition at line 617 of file DialectConversion.h.
OpAdaptor
template<typename SourceOp > using mlir::OpConversionPattern< SourceOp >::OpAdaptor = typename SourceOp::Adaptor
Definition at line 616 of file DialectConversion.h.
Constructor & Destructor Documentation
OpConversionPattern() [1/2]
template<typename SourceOp > mlir::OpConversionPattern< SourceOp >::OpConversionPattern (MLIRContext * context, PatternBenefit benefit = 1) inline
Definition at line 620 of file DialectConversion.h.
OpConversionPattern() [2/2]
template<typename SourceOp > mlir::OpConversionPattern< SourceOp >::OpConversionPattern (const TypeConverter & typeConverter, MLIRContext * context, PatternBenefit benefit = 1) inline
Definition at line 622 of file DialectConversion.h.
Member Function Documentation
match() [1/2]
template<typename SourceOp > LogicalResult mlir::OpConversionPattern< SourceOp >::match (Operation * op) const inline final virtual
Wrappers around the ConversionPattern methods that pass the derived op type.
Reimplemented from mlir::RewritePattern.
Definition at line 629 of file DialectConversion.h.
Referenced by mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
match() [2/2]
template<typename SourceOp > virtual LogicalResult mlir::OpConversionPattern< SourceOp >::match (SourceOp op) const inline virtual
Rewrite and Match methods that operate on the SourceOp type.
These must be overridden by the derived pattern class.
Definition at line 658 of file DialectConversion.h.
matchAndRewrite() [1/4]
template<typename SourceOp > LogicalResult mlir::OpConversionPattern< SourceOp >::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline final virtual
Hook for derived classes to implement combined matching and rewriting.
This overload supports only 1:1 replacements. The 1:N overload is called by the driver. By default, it calls this 1:1 overload or reports a fatal error if 1:N replacements were found.
Reimplemented from mlir::ConversionPattern.
Definition at line 643 of file DialectConversion.h.
References mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
Referenced by mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
matchAndRewrite() [2/4]
template<typename SourceOp > LogicalResult mlir::OpConversionPattern< SourceOp >::matchAndRewrite (Operation * op, ArrayRef< ValueRange > operands, ConversionPatternRewriter & rewriter) const inline final virtual
Hook for derived classes to implement combined matching and rewriting.
This overload supports 1:N replacements.
Reimplemented from mlir::ConversionPattern.
Definition at line 649 of file DialectConversion.h.
References mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
matchAndRewrite() [3/4]
template<typename SourceOp > virtual LogicalResult mlir::OpConversionPattern< SourceOp >::matchAndRewrite (SourceOp op, OneToNOpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline virtual
Definition at line 680 of file DialectConversion.h.
References mlir::ConversionPattern::getOneToOneAdaptorOperands(), and mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
matchAndRewrite() [4/4]
template<typename SourceOp > virtual LogicalResult mlir::OpConversionPattern< SourceOp >::matchAndRewrite (SourceOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline virtual
Reimplemented in StorageSpecifierInitOpConverter, SpecifierGetterSetterOpConverter< Base, SourceOp >, GPUSubgroupReduceConversion, GPUAllReduceConversion, AssertOpLowering, and YieldOpLowering.
Definition at line 672 of file DialectConversion.h.
References mlir::OpConversionPattern< SourceOp >::match(), and mlir::OpConversionPattern< SourceOp >::rewrite().
rewrite() [1/4]
template<typename SourceOp > void mlir::OpConversionPattern< SourceOp >::rewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline final virtual
Hook for derived classes to implement rewriting.
op is the (first) operation matched by the pattern, operands is a list of the rewritten operand values that are passed to op, rewriter can be used to emit the new operations. This function should not fail. If some specific cases of the operation are not supported, these cases should not be matched.
Reimplemented from mlir::ConversionPattern.
Definition at line 632 of file DialectConversion.h.
References mlir::OpConversionPattern< SourceOp >::rewrite().
Referenced by mlir::OpConversionPattern< SourceOp >::matchAndRewrite(), and mlir::OpConversionPattern< SourceOp >::rewrite().
rewrite() [2/4]
template<typename SourceOp > void mlir::OpConversionPattern< SourceOp >::rewrite (Operation * op, ArrayRef< ValueRange > operands, ConversionPatternRewriter & rewriter) const inline final virtual
Reimplemented from mlir::ConversionPattern.
Definition at line 637 of file DialectConversion.h.
References mlir::OpConversionPattern< SourceOp >::rewrite().
rewrite() [3/4]
template<typename SourceOp > virtual void mlir::OpConversionPattern< SourceOp >::rewrite (SourceOp op, OneToNOpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline virtual
Definition at line 665 of file DialectConversion.h.
References mlir::ConversionPattern::getOneToOneAdaptorOperands(), and mlir::OpConversionPattern< SourceOp >::rewrite().
rewrite() [4/4]
template<typename SourceOp > virtual void mlir::OpConversionPattern< SourceOp >::rewrite (SourceOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline virtual
Definition at line 661 of file DialectConversion.h.
The documentation for this class was generated from the following file:
include/mlir/Transforms/DialectConversion.h