MLIR: mlir::bufferization::BufferPlacementAllocs Class Reference
mlir::bufferization::BufferPlacementAllocs Class Reference
A simple analysis that detects allocation operations.
#include "mlir/Dialect/Bufferization/Transforms/BufferUtils.h"
Public Types
using AllocEntry = std::tuple< Value, Operation * >
Represents a tuple of allocValue and deallocOperation.
using AllocEntryList = SmallVector< AllocEntry, 8 >
Represents a list containing all alloc entries.
Public Member Functions
BufferPlacementAllocs (Operation *op)
Initializes the internal list by discovering all supported allocation nodes.
AllocEntryList::const_iterator begin () const
Returns the begin iterator to iterate over all allocations.
AllocEntryList::const_iterator end () const
Returns the end iterator that can be used in combination with begin.
AllocEntryList::iterator begin ()
Returns the begin iterator to iterate over all allocations.
AllocEntryList::iterator end ()
Returns the end iterator that can be used in combination with begin.
void registerAlloc (const AllocEntry &entry)
Registers a new allocation entry.
Static Public Member Functions
static Operation * getStartOperation (Value allocValue, Block *placementBlock, const Liveness &liveness)
Get the start operation to place the given alloc value within the specified placement block.
Detailed Description
A simple analysis that detects allocation operations.
Definition at line 35 of file BufferUtils.h.
Member Typedef Documentation
AllocEntry
using mlir::bufferization::BufferPlacementAllocs::AllocEntry = std::tuple<Value, Operation *>
Represents a tuple of allocValue and deallocOperation.
Definition at line 38 of file BufferUtils.h.
AllocEntryList
using mlir::bufferization::BufferPlacementAllocs::AllocEntryList = SmallVector<AllocEntry, 8>
Represents a list containing all alloc entries.
Definition at line 41 of file BufferUtils.h.
Constructor & Destructor Documentation
BufferPlacementAllocs()
BufferPlacementAllocs::BufferPlacementAllocs (Operation * op)
Initializes the internal list by discovering all supported allocation nodes.
Definition at line 53 of file BufferUtils.cpp.
Member Function Documentation
begin() [1/2]
AllocEntryList::iterator mlir::bufferization::BufferPlacementAllocs::begin () inline
Returns the begin iterator to iterate over all allocations.
Definition at line 60 of file BufferUtils.h.
begin() [2/2]
AllocEntryList::const_iterator mlir::bufferization::BufferPlacementAllocs::begin () const inline
Returns the begin iterator to iterate over all allocations.
Definition at line 54 of file BufferUtils.h.
end() [1/2]
AllocEntryList::iterator mlir::bufferization::BufferPlacementAllocs::end () inline
Returns the end iterator that can be used in combination with begin.
Definition at line 63 of file BufferUtils.h.
end() [2/2]
AllocEntryList::const_iterator mlir::bufferization::BufferPlacementAllocs::end () const inline
Returns the end iterator that can be used in combination with begin.
Definition at line 57 of file BufferUtils.h.
getStartOperation()
Operation * BufferPlacementAllocs::getStartOperation (Value allocValue, Block * placementBlock, const Liveness & liveness) static
Get the start operation to place the given alloc value within the specified placement block.
Get the start operation to place the given alloc value withing the.
Definition at line 31 of file BufferUtils.cpp.
References mlir::Block::findAncestorOpInBlock(), mlir::Operation::getBlock(), mlir::Liveness::getLiveness(), mlir::LivenessBlockInfo::getStartOperation(), and mlir::Block::getTerminator().
registerAlloc()
void mlir::bufferization::BufferPlacementAllocs::registerAlloc (const AllocEntry & entry) inline
Registers a new allocation entry.
Definition at line 66 of file BufferUtils.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Bufferization/Transforms/BufferUtils.h
lib/Dialect/Bufferization/Transforms/BufferUtils.cpp