MLIR: mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor Class Reference
mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor Class Reference
#include "mlir/Query/Matcher/Marshallers.h"
Public Types
using VarOp = DynMatcher::VariadicOperator
Public Member Functions
VariadicOperatorMatcherDescriptor (unsigned minCount, unsigned maxCount, VarOp varOp, StringRef matcherName)
VariantMatcher create (SourceRange nameRange, ArrayRef< ParserValue > args, Diagnostics *error) const override
bool isVariadic () const override
unsigned getNumArgs () const override
void getArgKinds (unsigned argNo, std::vector< ArgKind > &kinds) const override
Public Member Functions inherited from mlir::query::matcher::internal::MatcherDescriptor
virtual ~MatcherDescriptor ()=default
Detailed Description
Definition at line 161 of file Marshallers.h.
Member Typedef Documentation
VarOp
using mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::VarOp = DynMatcher::VariadicOperator
Definition at line 163 of file Marshallers.h.
Constructor & Destructor Documentation
VariadicOperatorMatcherDescriptor()
mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::VariadicOperatorMatcherDescriptor (unsigned minCount, unsigned maxCount, VarOp varOp, StringRef matcherName) inline
Definition at line 164 of file Marshallers.h.
Member Function Documentation
create()
VariantMatcher mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::create (SourceRange nameRange, ArrayRef< ParserValue > args, Diagnostics * error) const inline override virtual
Implements mlir::query::matcher::internal::MatcherDescriptor.
Definition at line 169 of file Marshallers.h.
References mlir::query::matcher::internal::addError(), mlir::query::matcher::VariantValue::getMatcher(), mlir::query::matcher::VariantValue::isMatcher(), mlir::query::matcher::ParserValue::range, mlir::query::matcher::internal::RegistryWrongArgCount, mlir::query::matcher::internal::RegistryWrongArgType, mlir::query::matcher::ParserValue::value, and mlir::query::matcher::VariantMatcher::VariadicOperatorMatcher().
getArgKinds()
void mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::getArgKinds (unsigned argNo, std::vector< ArgKind > & kinds) const inline override virtual
Implements mlir::query::matcher::internal::MatcherDescriptor.
Definition at line 198 of file Marshallers.h.
References mlir::query::matcher::Matcher.
getNumArgs()
unsigned mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::getNumArgs () const inline override virtual
Implements mlir::query::matcher::internal::MatcherDescriptor.
Definition at line 196 of file Marshallers.h.
isVariadic()
bool mlir::query::matcher::internal::VariadicOperatorMatcherDescriptor::isVariadic () const inline override virtual
Implements mlir::query::matcher::internal::MatcherDescriptor.
Definition at line 194 of file Marshallers.h.
The documentation for this class was generated from the following file:
include/mlir/Query/Matcher/Marshallers.h