MLIR: mlir::ConversionPattern Class Reference
mlir::ConversionPattern Class Reference
Base class for the conversion patterns.
#include "mlir/Transforms/DialectConversion.h"
Public Member Functions
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual void rewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
const TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, const ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Protected Member Functions
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
SmallVector< Value > getOneToOneAdaptorOperands (ArrayRef< ValueRange > operands) const
Given an array of value ranges, which are the inputs to a 1:N adaptor, try to extract the single value of each range to construct a the inputs for a 1:1 adaptor.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes
const TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Detailed Description
Base class for the conversion patterns.
This pattern class enables type conversions, and other uses specific to the conversion framework. As such, patterns of this type can only be used with the 'apply*' methods below.
Definition at line 530 of file DialectConversion.h.
Constructor & Destructor Documentation
ConversionPattern()
template<typename... Args> mlir::ConversionPattern::ConversionPattern (const TypeConverter & typeConverter, Args &&... args) inline protected
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
Definition at line 589 of file DialectConversion.h.
Member Function Documentation
getOneToOneAdaptorOperands()
SmallVector< Value > ConversionPattern::getOneToOneAdaptorOperands (ArrayRef< ValueRange > operands) const protected
Given an array of value ranges, which are the inputs to a 1:N adaptor, try to extract the single value of each range to construct a the inputs for a 1:1 adaptor.
This function produces a fatal error if at least one range has 0 or more than 1 value: "pattern 'name' does not support 1:N conversion"
Definition at line 1872 of file DialectConversion.cpp.
Referenced by matchAndRewrite(), mlir::OpInterfaceConversionPattern< SourceOp >::matchAndRewrite(), mlir::ConvertOpToLLVMPattern< SourceOp >::matchAndRewrite(), mlir::OpConversionPattern< SourceOp >::matchAndRewrite(), rewrite(), mlir::OpInterfaceConversionPattern< SourceOp >::rewrite(), mlir::ConvertOpToLLVMPattern< SourceOp >::rewrite(), and mlir::OpConversionPattern< SourceOp >::rewrite().
getTypeConverter() [1/2]
const TypeConverter* mlir::ConversionPattern::getTypeConverter () const inline
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Definition at line 573 of file DialectConversion.h.
References typeConverter.
Referenced by mlir::ConvertToLLVMPattern::getTypeConverter(), and mlir::spirv::ElementwiseOpPattern< Op, SPIRVOp >::matchAndRewrite().
getTypeConverter() [2/2]
template<typename ConverterTy > std::enable_if_t<std::is_base_of<TypeConverter, ConverterTy>::value, const ConverterTy *> mlir::ConversionPattern::getTypeConverter () const inline
Definition at line 578 of file DialectConversion.h.
References typeConverter.
matchAndRewrite() [1/3]
virtual LogicalResult mlir::ConversionPattern::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement combined matching and rewriting.
This overload supports only 1:1 replacements. The 1:N overload is called by the driver. By default, it calls this 1:1 overload or reports a fatal error if 1:N replacements were found.
Reimplemented in mlir::OpInterfaceConversionPattern< SourceOp >, mlir::OpConversionPattern< SourceOp >, mlir::OpConversionPattern< Op >, mlir::OpConversionPattern< OpTy >, mlir::OpConversionPattern< StorageSpecifierInitOp >, mlir::OpConversionPattern< memref::LoadOp >, mlir::OpConversionPattern< memref::StoreOp >, mlir::OpConversionPattern< gpu::SubgroupReduceOp >, mlir::OpConversionPattern< gpu::AllReduceOp >, mlir::OpConversionPattern< SPIRVOp >, mlir::OpConversionPattern< async::YieldOp >, mlir::OpConversionPattern< cf::AssertOp >, mlir::ConvertOpToLLVMPattern< SourceOp >, mlir::ConvertOpToLLVMPattern< Op >, mlir::ConvertOpToLLVMPattern< gpu::PrintfOp >, mlir::ConvertOpToLLVMPattern< gpu::GPUFuncOp >, mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >, mlir::ConvertOpToLLVMPattern< memref::TransposeOp >, mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >, and mlir::ConvertOpToLLVMPattern< cf::AssertOp >.
Definition at line 551 of file DialectConversion.h.
References mlir::RewritePattern::match(), and rewrite().
Referenced by matchAndRewrite().
matchAndRewrite() [2/3]
virtual LogicalResult mlir::ConversionPattern::matchAndRewrite (Operation * op, ArrayRef< ValueRange > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement combined matching and rewriting.
This overload supports 1:N replacements.
Reimplemented in mlir::OpInterfaceConversionPattern< SourceOp >, mlir::OpConversionPattern< SourceOp >, mlir::OpConversionPattern< Op >, mlir::OpConversionPattern< OpTy >, mlir::OpConversionPattern< StorageSpecifierInitOp >, mlir::OpConversionPattern< memref::LoadOp >, mlir::OpConversionPattern< memref::StoreOp >, mlir::OpConversionPattern< gpu::SubgroupReduceOp >, mlir::OpConversionPattern< gpu::AllReduceOp >, mlir::OpConversionPattern< SPIRVOp >, mlir::OpConversionPattern< async::YieldOp >, mlir::OpConversionPattern< cf::AssertOp >, mlir::ConvertOpToLLVMPattern< SourceOp >, mlir::ConvertOpToLLVMPattern< Op >, mlir::ConvertOpToLLVMPattern< gpu::PrintfOp >, mlir::ConvertOpToLLVMPattern< gpu::GPUFuncOp >, mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >, mlir::ConvertOpToLLVMPattern< memref::TransposeOp >, mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >, and mlir::ConvertOpToLLVMPattern< cf::AssertOp >.
Definition at line 562 of file DialectConversion.h.
References getOneToOneAdaptorOperands(), and matchAndRewrite().
matchAndRewrite() [3/3]
LogicalResult ConversionPattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const final virtual
Attempt to match and rewrite the IR root at the specified operation.
Reimplemented from mlir::RewritePattern.
Definition at line 1886 of file DialectConversion.cpp.
References mlir::detail::ConversionPatternRewriterImpl::currentTypeConverter, mlir::Operation::getLoc(), mlir::Operation::getOperands(), and mlir::detail::ConversionPatternRewriterImpl::remapValues().
rewrite() [1/2]
virtual void mlir::ConversionPattern::rewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement rewriting.
op is the (first) operation matched by the pattern, operands is a list of the rewritten operand values that are passed to op, rewriter can be used to emit the new operations. This function should not fail. If some specific cases of the operation are not supported, these cases should not be matched.
Reimplemented in mlir::OpInterfaceConversionPattern< SourceOp >, mlir::OpConversionPattern< SourceOp >, mlir::OpConversionPattern< Op >, mlir::OpConversionPattern< OpTy >, mlir::OpConversionPattern< StorageSpecifierInitOp >, mlir::OpConversionPattern< memref::LoadOp >, mlir::OpConversionPattern< memref::StoreOp >, mlir::OpConversionPattern< gpu::SubgroupReduceOp >, mlir::OpConversionPattern< gpu::AllReduceOp >, mlir::OpConversionPattern< SPIRVOp >, mlir::OpConversionPattern< async::YieldOp >, mlir::OpConversionPattern< cf::AssertOp >, mlir::ConvertOpToLLVMPattern< SourceOp >, mlir::ConvertOpToLLVMPattern< Op >, mlir::ConvertOpToLLVMPattern< gpu::PrintfOp >, mlir::ConvertOpToLLVMPattern< gpu::GPUFuncOp >, mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >, mlir::ConvertOpToLLVMPattern< memref::TransposeOp >, mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >, and mlir::ConvertOpToLLVMPattern< cf::AssertOp >.
Definition at line 537 of file DialectConversion.h.
Referenced by matchAndRewrite(), and rewrite().
rewrite() [2/2]
virtual void mlir::ConversionPattern::rewrite (Operation * op, ArrayRef< ValueRange > operands, ConversionPatternRewriter & rewriter) const inline virtual
Reimplemented in mlir::OpInterfaceConversionPattern< SourceOp >, mlir::OpConversionPattern< SourceOp >, mlir::OpConversionPattern< Op >, mlir::OpConversionPattern< OpTy >, mlir::OpConversionPattern< StorageSpecifierInitOp >, mlir::OpConversionPattern< memref::LoadOp >, mlir::OpConversionPattern< memref::StoreOp >, mlir::OpConversionPattern< gpu::SubgroupReduceOp >, mlir::OpConversionPattern< gpu::AllReduceOp >, mlir::OpConversionPattern< SPIRVOp >, mlir::OpConversionPattern< async::YieldOp >, mlir::OpConversionPattern< cf::AssertOp >, mlir::ConvertOpToLLVMPattern< SourceOp >, mlir::ConvertOpToLLVMPattern< Op >, mlir::ConvertOpToLLVMPattern< gpu::PrintfOp >, mlir::ConvertOpToLLVMPattern< gpu::GPUFuncOp >, mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >, mlir::ConvertOpToLLVMPattern< memref::TransposeOp >, mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >, and mlir::ConvertOpToLLVMPattern< cf::AssertOp >.
Definition at line 541 of file DialectConversion.h.
References getOneToOneAdaptorOperands(), and rewrite().
Member Data Documentation
typeConverter
const TypeConverter* mlir::ConversionPattern::typeConverter = nullptr protected
An optional type converter for use by this pattern.
Definition at line 604 of file DialectConversion.h.
Referenced by mlir::ConvertToLLVMPattern::createMemRefDescriptor(), mlir::ConvertToLLVMPattern::getMemRefDescriptorSizes(), mlir::ConvertToLLVMPattern::getSizeInBytes(), getTypeConverter(), mlir::ConvertToLLVMPattern::isConvertibleAndHasIdentityMaps(), mlir::GPUDynamicSharedMemoryOpLowering::matchAndRewrite(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), and mlir::GPUPrintfOpToVPrintfLowering::matchAndRewrite().
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/Utils/DialectConversion.cpp