MLIR: mlir::dataflow::DeadCodeAnalysis Class Reference
mlir::dataflow::DeadCodeAnalysis Class Reference
Dead code analysis analyzes control-flow, as understood by RegionBranchOpInterface and BranchOpInterface, and the callgraph, as understood by CallableOpInterface and CallOpInterface.
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
Public Member Functions
DeadCodeAnalysis (DataFlowSolver &solver)
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting every operation with potential control-flow semantics.
LogicalResult visit (ProgramPoint *point) override
Visit an operation with control-flow semantics and deduce which of its successors are live.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
virtual void initializeEquivalentLatticeAnchor (Operation *top)
Initialize lattice anchor equivalence class from the provided top-level operation.
Additional Inherited Members
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint *point)
Create a dependency between the given analysis state and lattice anchor on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename AnchorT>
void registerAnchorKind ()
Register a custom lattice anchor class.
template<typename AnchorT, typename... Args>
AnchorT * getLatticeAnchor (Args &&...args)
Get or create a custom lattice anchor.
template<typename StateT, typename AnchorT>
void unionLatticeAnchors (AnchorT anchor, AnchorT other)
Union input anchors under the given state.
template<typename StateT, typename AnchorT>
StateT * getOrCreate (AnchorT anchor)
Get the analysis state associated with the lattice anchor.
template<typename StateT, typename AnchorT>
const StateT * getOrCreateFor (ProgramPoint *dependent, AnchorT anchor)
Get a read-only analysis state for the given point and create a dependency on dependent.
ProgramPoint * getProgramPointBefore (Operation *op)
Get a uniqued program point instance.
ProgramPoint * getProgramPointBefore (Block *block)
ProgramPoint * getProgramPointAfter (Operation *op)
ProgramPoint * getProgramPointAfter (Block *block)
const DataFlowConfig & getSolverConfig () const
Return the configuration of the solver used for this analysis.
Detailed Description
Dead code analysis analyzes control-flow, as understood by RegionBranchOpInterface and BranchOpInterface, and the callgraph, as understood by CallableOpInterface and CallOpInterface.
This analysis uses known constant values of operands to determine the liveness of each block and each edge between a block and its predecessors. For region control-flow, this analysis determines the predecessor operations for region entry blocks and region control-flow operations. For the callgraph, this analysis determines the callsites and live returns of every function.
Definition at line 176 of file DeadCodeAnalysis.h.
Constructor & Destructor Documentation
DeadCodeAnalysis()
DeadCodeAnalysis::DeadCodeAnalysis (DataFlowSolver & solver) explicit
Definition at line 133 of file DeadCodeAnalysis.cpp.
References mlir::DataFlowAnalysis::DataFlowAnalysis(), mlir::DataFlowAnalysis::DataFlowSolver, and mlir::DataFlowAnalysis::registerAnchorKind().
Member Function Documentation
initialize()
LogicalResult DeadCodeAnalysis::initialize (Operation * top) override virtual
Initialize the analysis by visiting every operation with potential control-flow semantics.
Implements mlir::DataFlowAnalysis.
Definition at line 138 of file DeadCodeAnalysis.cpp.
References mlir::DataFlowAnalysis::getOrCreate(), mlir::DataFlowAnalysis::getProgramPointBefore(), mlir::Operation::getRegions(), and mlir::DataFlowAnalysis::propagateIfChanged().
visit()
LogicalResult DeadCodeAnalysis::visit (ProgramPoint * point) override virtual
Visit an operation with control-flow semantics and deduce which of its successors are live.
Implements mlir::DataFlowAnalysis.
Definition at line 314 of file DeadCodeAnalysis.cpp.
References mlir::Operation::getBlock(), mlir::Operation::getNumRegions(), mlir::Operation::getNumSuccessors(), mlir::DataFlowAnalysis::getOrCreate(), mlir::DataFlowAnalysis::getOrCreateFor(), mlir::Operation::getParentOp(), mlir::ProgramPoint::getPrevOp(), mlir::DataFlowAnalysis::getProgramPointAfter(), mlir::DataFlowAnalysis::getProgramPointBefore(), mlir::Operation::getSuccessors(), mlir::ProgramPoint::isBlockStart(), isRegionOrCallableReturn(), and success().
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/DeadCodeAnalysis.h
lib/Analysis/DataFlow/DeadCodeAnalysis.cpp