MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyMlirContext Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyMlirContext Class Reference
Used in function arguments when None should resolve to the current context manager set instance.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting (ReferrentTy &referrent)
Public Member Functions inherited from mlir::python::Defaulting< DefaultingPyMlirContext, PyMlirContext >
Defaulting ()=default
Type casters require the type to be default constructible, but using such an instance is illegal.
ReferrentTy * get () const
ReferrentTy * operator-> ()
Static Public Member Functions
static PyMlirContext & resolve ()
Static Public Attributes
static constexpr const char kTypeDescription [] = "_mlir.ir.Context"
Additional Inherited Members
Public Types inherited from mlir::python::Defaulting< DefaultingPyMlirContext, PyMlirContext >
using ReferrentTy
Detailed Description
Used in function arguments when None should resolve to the current context manager set instance.
Definition at line 290 of file IRCore.h.
Member Function Documentation
Defaulting() [1/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting () default
Type casters require the type to be default constructible, but using such an instance is illegal.
Defaulting() [2/2]
mlir::python::Defaulting< DerivedTy, T >::Defaulting (ReferrentTy & referrent) inline
Definition at line 108 of file NanobindUtils.h.
resolve()
PyMlirContext & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyMlirContext::resolve () static
Definition at line 566 of file IRCore.cpp.
References diag().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolRefAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::inferReturnTypeComponents(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferTypeOpInterface::inferReturnTypes(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< ConcreteIface >::PyConcreteOpInterface().
Member Data Documentation
kTypeDescription
const char mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyMlirContext::kTypeDescription[] = "_mlir.ir.Context" static constexpr
Definition at line 294 of file IRCore.h.
The documentation for this class was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp