MLIR: mlir::BoolAttr Class Reference
mlir::BoolAttr Class Reference
Special case of IntegerAttr to represent boolean integers, i.e., signless i1 integers.
#include "mlir/IR/BuiltinAttributes.h"
Public Types
using ValueType = bool
Public Types inherited from mlir::Attribute
template<typename ConcreteType, typename BaseType, typename StorageType, template< typename T > class... Traits>
using AttrBase
Utility class for implementing attributes.
using ImplType = AttributeStorage
using ValueType = void
using AbstractTy = AbstractAttribute
Public Member Functions
operator IntegerAttr () const
Enable conversion to IntegerAttr and its interfaces.
operator TypedAttr () const
bool getValue () const
Return the boolean value of this attribute.
constexpr Attribute ()=default
Attribute (const ImplType *impl)
Attribute (const Attribute &other)=default
Public Member Functions inherited from mlir::Attribute
constexpr Attribute ()=default
Attribute (const ImplType *impl)
Attribute (const Attribute &other)=default
Attribute & operator= (const Attribute &other)=default
bool operator== (Attribute other) const
bool operator!= (Attribute other) const
operator bool () const
bool operator! () const
TypeID getTypeID ()
Return a unique identifier for the concrete attribute type.
MLIRContext * getContext () const
Return the context this attribute belongs to.
Dialect & getDialect () const
Get the dialect this attribute is registered to.
void print (raw_ostream &os, bool elideType=false) const
Print the attribute.
void print (raw_ostream &os, AsmState &state, bool elideType=false) const
void dump () const
void printStripped (raw_ostream &os) const
Print the attribute without dialect wrapping.
void printStripped (raw_ostream &os, AsmState &state) const
const void * getAsOpaquePointer () const
Get an opaque pointer to the attribute.
friend::llvm::hash_code hash_value (Attribute arg)
template<typename InterfaceT>
bool hasPromiseOrImplementsInterface ()
Returns true if InterfaceT has been promised by the dialect or implemented.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the type was registered with a particular trait.
const AbstractTy & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
void walkImmediateSubElements (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn) const
Walk all of the immediately nested sub-attributes and sub-types.
auto replaceImmediateSubElements (ArrayRef< Attribute > replAttrs, ArrayRef< Type > replTypes) const
Replace the immediately nested sub-attributes and sub-types with those provided.
template<WalkOrder Order = WalkOrder::PostOrder, typename... WalkFns>
auto walk (WalkFns &&...walkFns)
Walk this attribute and all attibutes/types nested within using the provided walk functions.
template<typename... ReplacementFns>
auto replace (ReplacementFns &&...replacementFns)
Recursively replace all of the nested sub-attributes and sub-types using the provided map functions.
ImplType * getImpl () const
Return the internal Attribute implementation.
Static Public Member Functions
static BoolAttr get (MLIRContext *context, bool value)
static bool classof (Attribute attr)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::Attribute
static Attribute getFromOpaquePointer (const void *ptr)
Construct an attribute from the opaque pointer representation.
Additional Inherited Members
Protected Attributes inherited from mlir::Attribute
ImplType * impl {nullptr}
Detailed Description
Special case of IntegerAttr to represent boolean integers, i.e., signless i1 integers.
Definition at line 846 of file BuiltinAttributes.h.
Member Typedef Documentation
ValueType
using mlir::BoolAttr::ValueType = bool
Definition at line 849 of file BuiltinAttributes.h.
Member Function Documentation
Attribute() [1/3]
mlir::Attribute::Attribute () constexpr default
Referenced by classof().
Attribute() [2/3]
mlir::Attribute::Attribute (const Attribute & other) default
Attribute() [3/3]
mlir::Attribute::Attribute (const ImplType * impl) inline
Definition at line 38 of file Attributes.h.
classof()
bool BoolAttr::classof (Attribute attr) static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 422 of file BuiltinAttributes.cpp.
References Attribute().
get()
BoolAttr BoolAttr::get (MLIRContext * context, bool value) static
Definition at line 1138 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::falseAttr, mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::trueAttr.
Referenced by mlir::convertToAttribute(), mlir::Builder::getBoolAttr(), getBoolAttribute(), getBoolAttribute(), mlirBoolAttrGet(), and parseWaitClause().
getValue()
bool BoolAttr::getValue () const
Return the boolean value of this attribute.
Definition at line 417 of file BuiltinAttributes.cpp.
Referenced by mlir::tosa::buildQTypeFromMinMax().
operator IntegerAttr()
mlir::BoolAttr::operator IntegerAttr () const inline
Enable conversion to IntegerAttr and its interfaces.
This uses conversion vs. inheritance to avoid bringing in all of IntegerAttrs methods.
Definition at line 855 of file BuiltinAttributes.h.
operator TypedAttr()
mlir::BoolAttr::operator TypedAttr () const inline
Definition at line 856 of file BuiltinAttributes.h.
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinAttributes.h
lib/IR/BuiltinAttributes.cpp
lib/IR/MLIRContext.cpp