MLIR: mlir::NonFloatComplex< T > Class Template Reference
mlir::NonFloatComplex< T > Class Template Reference
#include "mlir/Support/Complex.h"
Public Types
using value_type = T
Public Member Functions
constexpr NonFloatComplex (const T &re=T{}, const T &im=T{})
constexpr NonFloatComplex (const NonFloatComplex &other)=default
template<typename U, std::enable_if_t< detail::is_copy_list_initializable_v< U, T > > ...>
constexpr NonFloatComplex (const NonFloatComplex< U > &other)
template<typename U, std::enable_if_t<!detail::is_copy_list_initializable_v< U, T > > ...>
constexpr NonFloatComplex (const NonFloatComplex< U > &other)
template<typename U, std::enable_if_t< detail::is_copy_list_initializable_v< U, T > > ...>
constexpr NonFloatComplex (const std::complex< U > &other)
template<typename U, std::enable_if_t<!detail::is_copy_list_initializable_v< U, T > > ...>
constexpr NonFloatComplex (const std::complex< U > &other)
constexpr T real () const
constexpr void real (T value)
constexpr T imag () const
constexpr void imag (T value)
constexpr NonFloatComplex & operator= (const NonFloatComplex &other)=default
constexpr NonFloatComplex & operator= (const T &real)
constexpr NonFloatComplex & operator+= (const T &real)
constexpr NonFloatComplex & operator-= (const T &real)
constexpr NonFloatComplex & operator*= (const T &real)
constexpr NonFloatComplex & operator/= (const T &real)
constexpr NonFloatComplex & operator+= (const NonFloatComplex &other)
constexpr NonFloatComplex & operator-= (const NonFloatComplex &other)
constexpr NonFloatComplex & operator*= (const NonFloatComplex &other)
constexpr NonFloatComplex & operator/= (const NonFloatComplex &other)
template<typename U>
constexpr NonFloatComplex & operator= (const std::complex< U > &other)
Detailed Description
template<typename T>
class mlir::NonFloatComplex< T >
Definition at line 52 of file Complex.h.
Member Typedef Documentation
value_type
template<typename T> using mlir::NonFloatComplex< T >::value_type = T
Definition at line 54 of file Complex.h.
Constructor & Destructor Documentation
NonFloatComplex() [1/6]
template<typename T> mlir::NonFloatComplex< T >::NonFloatComplex (const T & re = T{}, const T & im = T{}) inline constexpr
Definition at line 61 of file Complex.h.
Referenced by NonFloatComplex(), NonFloatComplex(), operator*=(), operator*=(), operator+=(), operator+=(), operator-=(), operator-=(), operator/=(), operator/=(), operator=(), operator=(), and operator=().
NonFloatComplex() [2/6]
template<typename T> mlir::NonFloatComplex< T >::NonFloatComplex (const NonFloatComplex< T > & other) constexpr default
References NonFloatComplex().
NonFloatComplex() [3/6]
template<typename T> template<typename U, std::enable_if_t< detail::is_copy_list_initializable_v< U, T > > ...> mlir::NonFloatComplex< T >::NonFloatComplex (const NonFloatComplex< U > & other) inline constexpr
Definition at line 68 of file Complex.h.
References NonFloatComplex().
NonFloatComplex() [4/6]
template<typename T> template<typename U, std::enable_if_t<!detail::is_copy_list_initializable_v< U, T > > ...> mlir::NonFloatComplex< T >::NonFloatComplex (const NonFloatComplex< U > & other) inline explicit constexpr
Definition at line 73 of file Complex.h.
References NonFloatComplex().
NonFloatComplex() [5/6]
template<typename T> template<typename U, std::enable_if_t< detail::is_copy_list_initializable_v< U, T > > ...> mlir::NonFloatComplex< T >::NonFloatComplex (const std::complex< U > & other) inline constexpr
Definition at line 78 of file Complex.h.
References imag(), and real().
NonFloatComplex() [6/6]
template<typename T> template<typename U, std::enable_if_t<!detail::is_copy_list_initializable_v< U, T > > ...> mlir::NonFloatComplex< T >::NonFloatComplex (const std::complex< U > & other) inline explicit constexpr
Definition at line 83 of file Complex.h.
References imag(), and real().
Member Function Documentation
imag() [1/2]
template<typename T> T mlir::NonFloatComplex< T >::imag () const inline nodiscard constexpr
Definition at line 88 of file Complex.h.
Referenced by mlir::imag(), NonFloatComplex(), mlir::operator*(), mlir::operator-(), mlir::operator/(), and mlir::operator==().
imag() [2/2]
template<typename T> void mlir::NonFloatComplex< T >::imag (T value) inline constexpr
Definition at line 89 of file Complex.h.
operator*=() [1/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator*= (const NonFloatComplex< T > & other) inline constexpr
Definition at line 133 of file Complex.h.
References NonFloatComplex().
operator*=() [2/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator*= (const T & real) inline constexpr
Definition at line 109 of file Complex.h.
References NonFloatComplex(), and real().
operator+=() [1/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator+= (const NonFloatComplex< T > & other) inline constexpr
Definition at line 121 of file Complex.h.
References NonFloatComplex().
operator+=() [2/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator+= (const T & real) inline constexpr
Definition at line 99 of file Complex.h.
References NonFloatComplex(), and real().
operator-=() [1/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator-= (const NonFloatComplex< T > & other) inline constexpr
Definition at line 127 of file Complex.h.
References NonFloatComplex().
operator-=() [2/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator-= (const T & real) inline constexpr
Definition at line 104 of file Complex.h.
References NonFloatComplex(), and real().
operator/=() [1/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator/= (const NonFloatComplex< T > & other) inline constexpr
Definition at line 138 of file Complex.h.
References NonFloatComplex().
operator/=() [2/2]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator/= (const T & real) inline constexpr
Definition at line 115 of file Complex.h.
References NonFloatComplex(), and real().
operator=() [1/3]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator= (const NonFloatComplex< T > & other) constexpr default
References NonFloatComplex().
operator=() [2/3]
template<typename T> template<typename U> NonFloatComplex & mlir::NonFloatComplex< T >::operator= (const std::complex< U > & other) inline constexpr
Definition at line 144 of file Complex.h.
References NonFloatComplex(), and real().
operator=() [3/3]
template<typename T> NonFloatComplex & mlir::NonFloatComplex< T >::operator= (const T & real) inline constexpr
Definition at line 93 of file Complex.h.
References NonFloatComplex(), and real().
real() [1/2]
template<typename T> T mlir::NonFloatComplex< T >::real () const inline nodiscard constexpr
Definition at line 86 of file Complex.h.
Referenced by NonFloatComplex(), mlir::operator*(), operator*=(), operator+=(), mlir::operator-(), operator-=(), mlir::operator/(), operator/=(), operator=(), operator=(), mlir::operator==(), and mlir::real().
real() [2/2]
template<typename T> void mlir::NonFloatComplex< T >::real (T value) inline constexpr
Definition at line 87 of file Complex.h.
The documentation for this class was generated from the following file:
include/mlir/Support/Complex.h