MLIR: mlir::OpaqueProperties Class Reference
mlir::OpaqueProperties Class Reference
Simple wrapper around a void* in order to express generically how to pass in op properties through APIs.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OpaqueProperties (void *prop)
operator bool () const
template<typename Dest >
Dest as () const
Detailed Description
Simple wrapper around a void* in order to express generically how to pass in op properties through APIs.
Definition at line 71 of file OperationSupport.h.
Constructor & Destructor Documentation
OpaqueProperties()
mlir::OpaqueProperties::OpaqueProperties (void * prop) inline
Definition at line 73 of file OperationSupport.h.
Member Function Documentation
as()
template<typename Dest > Dest mlir::OpaqueProperties::as () const inline
Definition at line 76 of file OperationSupport.h.
Referenced by mlir::OperationName::UnregisteredOpModel::compareProperties(), mlir::OperationName::UnregisteredOpModel::copyProperties(), mlir::OperationName::UnregisteredOpModel::deleteProperties(), mlir::OperationState::getOrAddProperties(), mlir::OperationName::UnregisteredOpModel::getPropertiesAsAttr(), mlir::Operation::getPropertiesAsAttribute(), mlir::OperationName::UnregisteredOpModel::hashProperties(), mlir::OperationName::UnregisteredOpModel::initProperties(), mlir::OperationName::UnregisteredOpModel::setInherentAttr(), mlir::RegisteredOperationName::Model< ConcreteOp >::setPropertiesFromAttr(), mlir::OperationName::UnregisteredOpModel::setPropertiesFromAttr(), mlir::Operation::setPropertiesFromAttribute(), and mlir::OperationState::useProperties().
operator bool()
mlir::OpaqueProperties::operator bool () const inline
Definition at line 74 of file OperationSupport.h.
The documentation for this class was generated from the following file:
include/mlir/IR/OperationSupport.h