MLIR: mlir::tblgen::FmtObjectBase Class Reference
mlir::tblgen::FmtObjectBase Class Reference
#include "mlir/TableGen/Format.h"
Classes
struct CreateAdapters
Public Member Functions
FmtObjectBase (StringRef fmt, const FmtContext *ctx, size_t numParams)
FmtObjectBase (const FmtObjectBase &that)=delete
FmtObjectBase (FmtObjectBase &&that)
void format (llvm::raw_ostream &s) const
std::string str () const
template<unsigned N>
SmallString< N > sstr () const
template<unsigned N>
operator SmallString< N > () const
operator std::string () const
Protected Attributes
StringRef fmt
const FmtContext * context
std::vector< llvm::support::detail::format_adapter * > adapters
std::vector< FmtReplacement > replacements
Detailed Description
Definition at line 121 of file Format.h.
Constructor & Destructor Documentation
FmtObjectBase() [1/3]
mlir::tblgen::FmtObjectBase::FmtObjectBase (StringRef fmt, const FmtContext * ctx, size_t numParams) inline
Definition at line 148 of file Format.h.
References context, fmt, and replacements.
Referenced by mlir::tblgen::FmtObject< Tuple >::FmtObject(), mlir::tblgen::FmtObject< Tuple >::FmtObject(), FmtObjectBase(), FmtObjectBase(), mlir::tblgen::FmtStrVecObject::FmtStrVecObject(), and mlir::tblgen::FmtStrVecObject::FmtStrVecObject().
FmtObjectBase() [2/3]
mlir::tblgen::FmtObjectBase::FmtObjectBase (const FmtObjectBase & that) delete
References FmtObjectBase().
FmtObjectBase() [3/3]
mlir::tblgen::FmtObjectBase::FmtObjectBase (FmtObjectBase && that) inline
Definition at line 153 of file Format.h.
References adapters, context, fmt, FmtObjectBase(), and replacements.
Member Function Documentation
format()
void FmtObjectBase::format (llvm::raw_ostream & s) const
Definition at line 145 of file Format.cpp.
References adapters, context, mlir::tblgen::FmtContext::Custom, mlir::tblgen::FmtReplacement::Empty, mlir::tblgen::FmtReplacement::end, mlir::tblgen::FmtReplacement::index, kMarkerForNoSubst, mlir::tblgen::FmtReplacement::kUnset, mlir::tblgen::FmtReplacement::Literal, mlir::tblgen::FmtContext::None, mlir::tblgen::FmtReplacement::placeholder, mlir::tblgen::FmtReplacement::PositionalPH, mlir::tblgen::FmtReplacement::PositionalRangePH, replacements, mlir::tblgen::FmtReplacement::spec, mlir::tblgen::FmtReplacement::SpecialPH, and mlir::tblgen::FmtReplacement::type.
Referenced by sstr(), and str().
operator SmallString< N >()
template<unsigned N> mlir::tblgen::FmtObjectBase::operator SmallString< N > () const inline
Definition at line 176 of file Format.h.
References sstr().
operator std::string()
mlir::tblgen::FmtObjectBase::operator std::string () const inline
Definition at line 180 of file Format.h.
References str().
sstr()
template<unsigned N> SmallString< N > mlir::tblgen::FmtObjectBase::sstr () const inline
Definition at line 168 of file Format.h.
References format(), and result.
Referenced by operator SmallString< N >().
str()
std::string mlir::tblgen::FmtObjectBase::str () const inline
Definition at line 160 of file Format.h.
References format(), and result.
Referenced by operator std::string().
Member Data Documentation
adapters
std::vector<llvm::support::detail::format_adapter *> mlir::tblgen::FmtObjectBase::adapters protected
Definition at line 144 of file Format.h.
Referenced by mlir::tblgen::FmtObject< Tuple >::FmtObject(), mlir::tblgen::FmtObject< Tuple >::FmtObject(), FmtObjectBase(), mlir::tblgen::FmtStrVecObject::FmtStrVecObject(), mlir::tblgen::FmtStrVecObject::FmtStrVecObject(), and format().
context
const FmtContext* mlir::tblgen::FmtObjectBase::context protected
Definition at line 143 of file Format.h.
Referenced by FmtObjectBase(), FmtObjectBase(), and format().
fmt
StringRef mlir::tblgen::FmtObjectBase::fmt protected
Definition at line 142 of file Format.h.
Referenced by mlir::tblgen::FmtObject< Tuple >::FmtObject(), FmtObjectBase(), FmtObjectBase(), and mlir::tblgen::FmtStrVecObject::FmtStrVecObject().
replacements
std::vector<FmtReplacement> mlir::tblgen::FmtObjectBase::replacements protected
Definition at line 145 of file Format.h.
Referenced by FmtObjectBase(), FmtObjectBase(), and format().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Format.h
lib/TableGen/Format.cpp