MLIR: mlir::detail::ElementsAttrIterator< T > Class Template Reference
mlir::detail::ElementsAttrIterator< T > Class Template Reference
This class implements a generic iterator for ElementsAttr.
#include "mlir/IR/BuiltinAttributeInterfaces.h"
Public Member Functions
ElementsAttrIterator (ElementsAttrIndexer indexer, size_t dataIndex)
ptrdiff_t operator- (const ElementsAttrIterator &rhs) const
bool operator== (const ElementsAttrIterator &rhs) const
bool operator< (const ElementsAttrIterator &rhs) const
ElementsAttrIterator & operator+= (ptrdiff_t offset)
ElementsAttrIterator & operator-= (ptrdiff_t offset)
T operator* () const
Return the value at the current iterator position.
Detailed Description
template<typename T>
class mlir::detail::ElementsAttrIterator< T >
This class implements a generic iterator for ElementsAttr.
Definition at line 198 of file BuiltinAttributeInterfaces.h.
Constructor & Destructor Documentation
ElementsAttrIterator()
template<typename T> mlir::detail::ElementsAttrIterator< T >::ElementsAttrIterator (ElementsAttrIndexer indexer, size_t dataIndex) inline
Definition at line 203 of file BuiltinAttributeInterfaces.h.
Referenced by operator+=(), operator-(), operator-=(), operator<(), and operator==().
Member Function Documentation
operator*()
template<typename T> T mlir::detail::ElementsAttrIterator< T >::operator* () const inline
Return the value at the current iterator position.
Definition at line 226 of file BuiltinAttributeInterfaces.h.
operator+=()
template<typename T> ElementsAttrIterator & mlir::detail::ElementsAttrIterator< T >::operator+= (ptrdiff_t offset) inline
Definition at line 216 of file BuiltinAttributeInterfaces.h.
References ElementsAttrIterator().
operator-()
template<typename T> ptrdiff_t mlir::detail::ElementsAttrIterator< T >::operator- (const ElementsAttrIterator< T > & rhs) const inline
Definition at line 207 of file BuiltinAttributeInterfaces.h.
References ElementsAttrIterator(), and rhs.
operator-=()
template<typename T> ElementsAttrIterator & mlir::detail::ElementsAttrIterator< T >::operator-= (ptrdiff_t offset) inline
Definition at line 220 of file BuiltinAttributeInterfaces.h.
References ElementsAttrIterator().
operator<()
template<typename T> bool mlir::detail::ElementsAttrIterator< T >::operator< (const ElementsAttrIterator< T > & rhs) const inline
Definition at line 213 of file BuiltinAttributeInterfaces.h.
References ElementsAttrIterator(), and rhs.
operator==()
template<typename T> bool mlir::detail::ElementsAttrIterator< T >::operator== (const ElementsAttrIterator< T > & rhs) const inline
Definition at line 210 of file BuiltinAttributeInterfaces.h.
References ElementsAttrIterator(), and rhs.
The documentation for this class was generated from the following file:
include/mlir/IR/BuiltinAttributeInterfaces.h