MLIR: mlir::spirv::ScalarType Class Reference
mlir::spirv::ScalarType Class Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
Public Member Functions
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< StorageClass > storage=llvm::None)
Optional< int64_t > getSizeInBytes ()
Public Member Functions inherited from mlir::spirv::SPIRVType
bool isScalarOrVector ()
void getExtensions (ExtensionArrayRefVector &extensions, Optional< StorageClass > storage=llvm::None)
Appends to extensions the extensions needed for this type to appear in the given storage class.
void getCapabilities (CapabilityArrayRefVector &capabilities, Optional< StorageClass > storage=llvm::None)
Appends to capabilities the capabilities needed for this type to appear in the given storage class.
Optional< int64_t > getSizeInBytes ()
Returns the size in bytes for each type.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isF80 () const
bool isF128 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os) const
Print the current type.
void dump () const
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractTy & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool classof (Type type)
static bool isValid (FloatType)
Returns true if the given integer type is valid for the SPIR-V dialect.
static bool isValid (IntegerType)
Returns true if the given float type is valid for the SPIR-V dialect.
Static Public Member Functions inherited from mlir::spirv::SPIRVType
static bool classof (Type type)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::spirv::SPIRVType
using ExtensionArrayRefVector = SmallVectorImpl< ArrayRef< Extension > >
The extension requirements for each type are following the ((Extension::A OR Extension::B) AND (Extension::C OR Extension::D)) convention.
using CapabilityArrayRefVector = SmallVectorImpl< ArrayRef< Capability > >
The capability requirements for each type are following the ((Capability::A OR Extension::B) AND (Capability::C OR Capability::D)) convention.
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
using AbstractTy = AbstractType
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
Definition at line 79 of file SPIRVTypes.h.
Member Function Documentation
classof()
bool ScalarType::classof (Type type) static
Definition at line 482 of file SPIRVTypes.cpp.
References mlir::Type::dyn_cast().
getCapabilities()
void ScalarType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< StorageClass > storage = llvm::None)
Definition at line 538 of file SPIRVTypes.cpp.
References STORAGE_CASE, and WIDTH_CASE.
Referenced by convertScalarType().
getExtensions()
void ScalarType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< StorageClass > storage = llvm::None)
Definition at line 507 of file SPIRVTypes.cpp.
Referenced by convertScalarType().
getSizeInBytes()
Optional< int64_t > ScalarType::getSizeInBytes ()
Definition at line 622 of file SPIRVTypes.cpp.
isValid() [1/2]
bool ScalarType::isValid (FloatType type) static
Returns true if the given integer type is valid for the SPIR-V dialect.
Definition at line 492 of file SPIRVTypes.cpp.
References mlir::Type::isBF16().
Referenced by parseAndVerifyType().
isValid() [2/2]
bool ScalarType::isValid (IntegerType type) static
Returns true if the given float type is valid for the SPIR-V dialect.
Definition at line 494 of file SPIRVTypes.cpp.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/IR/SPIRVTypes.h
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp