MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface Class Reference
Static Public Member Functions
static void attach (nb::object &target, const std::string &opName, DefaultingPyMlirContext ctx)
Attach a new TransformOpInterface FallbackModel to the named operation.
static void bindDerived (ClassTy &cls)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyTransformOpInterface >
static void bind (nanobind::module_ &m)
Creates the Python bindings for this class in the given module.
static void bindDerived (ClassTy &cls)
Hook for derived classes to add class-specific bindings.
Static Public Attributes
static constexpr const char * pyClassName = "TransformOpInterface"
static constexpr GetTypeIDFunctionTy getInterfaceID
Additional Inherited Members
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyTransformOpInterface >
PyConcreteOpInterface (nanobind::object object, DefaultingPyMlirContext context)
Constructs an interface instance from an object that is either an operation or a subclass of OpView.
bool isStatic ()
Returns true if this object was constructed from a subclass of OpView rather than from an operation instance.
nanobind::typed< nanobind::object, PyOperation > getOperationObject ()
Returns the operation instance from which this object was constructed.
nanobind::typed< nanobind::object, PyOpView > getOpView ()
Returns the opview of the operation instance from which this object was constructed.
const std::string & getOpName ()
Returns the canonical name of the operation this interface is constructed from.
Protected Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyTransformOpInterface >
using ClassTy
using GetTypeIDFunctionTy
Detailed Description
Definition at line 166 of file DialectTransform.cpp.
Member Function Documentation
attach()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::attach (nb::object & target, const std::string & opName, DefaultingPyMlirContext ctx) inline static
Attach a new TransformOpInterface FallbackModel to the named operation.
The FallbackModel acts as a trampoline for callbacks on the Python class.
Definition at line 177 of file DialectTransform.cpp.
References MlirTransformOpInterfaceCallbacks::allowsRepeatedHandleOperands, MlirTransformOpInterfaceCallbacks::apply, MlirTransformOpInterfaceCallbacks::construct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::createOpView(), MlirTransformOpInterfaceCallbacks::destruct, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::forOperation(), mlir::python::Defaulting< DerivedTy, T >::get(), mlirOperationGetContext(), mlirStringRefCreate(), mlirTransformOpInterfaceAttachFallbackModel(), target, and MlirTransformOpInterfaceCallbacks::userData.
Referenced by bindDerived().
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::bindDerived (ClassTy & cls) inline static
Definition at line 238 of file DialectTransform.cpp.
References attach(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::classmethod(), and target.
Member Data Documentation
getInterfaceID
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::getInterfaceID static constexpr
Initial value:
=
      &mlirTransformOpInterfaceTypeID
Definition at line 172 of file DialectTransform.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::pyClassName = "TransformOpInterface" static constexpr
Definition at line 171 of file DialectTransform.cpp.
The documentation for this class was generated from the following file:
lib/Bindings/Python/DialectTransform.cpp