MLIR: mlir::sparse_tensor::ir_detail::Var::Impl Class Reference
mlir::sparse_tensor::ir_detail::Var::Impl Class Reference final
The underlying implementation of Var.
#include "Dialect/SparseTensor/IR/Detail/Var.h"
Public Member Functions
constexpr Impl (VarKind vk, Num n)
constexpr bool operator== (Impl other) const
constexpr bool operator!= (Impl other) const
constexpr VarKind getKind () const
constexpr Num getNum () const
Detailed Description
The underlying implementation of Var.
Note that this must be kept distinct from Var itself, since we want to ensure that the RTTI methods will select the U(Var::Impl) ctor rather than selecting the U(Var::Num) ctor.
Definition at line 90 of file Var.h.
Constructor & Destructor Documentation
Impl()
mlir::sparse_tensor::ir_detail::Var::Impl::Impl (VarKind vk, Num n) inline constexpr
Definition at line 94 of file Var.h.
References mlir::sparse_tensor::ir_detail::isWF(), and mlir::sparse_tensor::ir_detail::Var::isWF_Num().
Referenced by operator!=(), and operator==().
Member Function Documentation
getKind()
VarKind mlir::sparse_tensor::ir_detail::Var::Impl::getKind () const inline constexpr
Definition at line 102 of file Var.h.
getNum()
Num mlir::sparse_tensor::ir_detail::Var::Impl::getNum () const inline constexpr
Definition at line 103 of file Var.h.
operator!=()
bool mlir::sparse_tensor::ir_detail::Var::Impl::operator!= (Impl other) const inline constexpr
Definition at line 101 of file Var.h.
References Impl().
operator==()
bool mlir::sparse_tensor::ir_detail::Var::Impl::operator== (Impl other) const inline constexpr
Definition at line 100 of file Var.h.
References Impl().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/IR/Detail/Var.h