MLIR: mlir::dataflow::Executable Class Reference
mlir::dataflow::Executable Class Reference
This is a simple analysis state that represents whether the associated lattice anchor (either a block or a control-flow edge) is live.
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
Public Member Functions
ChangeResult setToLive ()
Set the state of the lattice anchor to live.
bool isLive () const
Get whether the lattice anchor is live.
void print (raw_ostream &os) const override
Print the liveness.
void onUpdate (DataFlowSolver *solver) const override
When the state of the lattice anchor is changed to live, re-invoke subscribed analyses on the operations in the block and on the block itself.
void blockContentSubscribe (DataFlowAnalysis *analysis)
Subscribe an analysis to changes to the liveness.
AnalysisState (LatticeAnchor anchor)
Create the analysis state on the given lattice anchor.
Public Member Functions inherited from mlir::AnalysisState
virtual ~AnalysisState ()
AnalysisState (LatticeAnchor anchor)
Create the analysis state on the given lattice anchor.
LatticeAnchor getAnchor () const
Returns the lattice anchor this state is located at.
virtual void print (raw_ostream &os) const =0
Print the contents of the analysis state.
LLVM_DUMP_METHOD void dump () const
void addDependency (ProgramPoint *point, DataFlowAnalysis *analysis)
Add a dependency to this analysis state on a lattice anchor and an analysis.
Additional Inherited Members
Protected Attributes inherited from mlir::AnalysisState
LatticeAnchor anchor
The lattice anchor to which the state belongs.
Detailed Description
This is a simple analysis state that represents whether the associated lattice anchor (either a block or a control-flow edge) is live.
Definition at line 40 of file DeadCodeAnalysis.h.
Member Function Documentation
AnalysisState()
AnalysisState::AnalysisState (LatticeAnchor anchor) inline
Create the analysis state on the given lattice anchor.
Definition at line 493 of file DataFlowFramework.h.
blockContentSubscribe()
void mlir::dataflow::Executable::blockContentSubscribe (DataFlowAnalysis * analysis) inline
Subscribe an analysis to changes to the liveness.
Definition at line 59 of file DeadCodeAnalysis.h.
isLive()
bool mlir::dataflow::Executable::isLive () const inline
Get whether the lattice anchor is live.
Definition at line 48 of file DeadCodeAnalysis.h.
onUpdate()
void Executable::onUpdate (DataFlowSolver * solver) const override virtual
When the state of the lattice anchor is changed to live, re-invoke subscribed analyses on the operations in the block and on the block itself.
Reimplemented from mlir::AnalysisState.
Definition at line 52 of file DeadCodeAnalysis.cpp.
References mlir::AnalysisState::anchor, mlir::AnalysisState::DataFlowSolver, mlir::DataFlowSolver::enqueue(), mlir::Operation::getBlock(), mlir::DataFlowSolver::getProgramPointAfter(), mlir::DataFlowSolver::getProgramPointBefore(), and mlir::AnalysisState::onUpdate().
print()
void Executable::print (raw_ostream & os) const override
Print the liveness.
Definition at line 48 of file DeadCodeAnalysis.cpp.
setToLive()
ChangeResult Executable::setToLive ()
Set the state of the lattice anchor to live.
Definition at line 41 of file DeadCodeAnalysis.cpp.
References mlir::Change, and mlir::NoChange.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/DeadCodeAnalysis.h
lib/Analysis/DataFlow/DeadCodeAnalysis.cpp