MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< DerivedTy > Class Template Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< DerivedTy > Class Template Reference
CRTP Base class for rewriter wrappers.
#include "Bindings/Python/Rewrite.h"
Public Member Functions
PyRewriterBase (MlirRewriterBase rewriter)
PyInsertionPoint getInsertionPoint () const
Static Public Member Functions
static void bind (nanobind::module_ &m)
Detailed Description
template<typename DerivedTy>
class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< DerivedTy >
CRTP Base class for rewriter wrappers.
Definition at line 23 of file Rewrite.h.
Constructor & Destructor Documentation
PyRewriterBase()
template<typename DerivedTy> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< DerivedTy >::PyRewriterBase (MlirRewriterBase rewriter) inline
Definition at line 25 of file Rewrite.h.
References mlirRewriterBaseGetContext().
Member Function Documentation
bind()
template<typename DerivedTy> void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< DerivedTy >::bind (nanobind::module_ & m) inline static
Definition at line 42 of file Rewrite.h.
References getInsertionPoint(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), mlirRewriterBaseEraseOp(), mlirRewriterBaseReplaceOpWithOperation(), and mlirRewriterBaseReplaceOpWithValues().
getInsertionPoint()
template<typename DerivedTy> PyInsertionPoint mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< DerivedTy >::getInsertionPoint () const inline
Definition at line 29 of file Rewrite.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::forOperation(), mlirBlockGetParentOperation(), mlirRewriterBaseGetInsertionBlock(), and mlirRewriterBaseGetOperationAfterInsertion().
Referenced by bind().
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.h