MLIR: mlir::tracing::BreakpointBase< Derived > Class Template Reference
mlir::tracing::BreakpointBase< Derived > Class Template Reference
This class provides a CRTP wrapper around a base breakpoint class to define a few necessary utility methods.
#include "mlir/Debug/BreakpointManager.h"
Static Public Member Functions
static bool classof (const Breakpoint *breakpoint)
Support isa/dyn_cast functionality for the derived pass class.
Protected Member Functions
BreakpointBase ()
Protected Member Functions inherited from mlir::tracing::Breakpoint
Breakpoint (TypeID typeID)
Additional Inherited Members
Public Member Functions inherited from mlir::tracing::Breakpoint
virtual ~Breakpoint ()=default
TypeID getTypeID () const
TypeID for the subclass, used for casting purpose.
bool isEnabled () const
void enable ()
void disable ()
virtual void print (raw_ostream &os) const =0
Detailed Description
template<typename Derived>
class mlir::tracing::BreakpointBase< Derived >
This class provides a CRTP wrapper around a base breakpoint class to define a few necessary utility methods.
Definition at line 49 of file BreakpointManager.h.
Constructor & Destructor Documentation
BreakpointBase()
template<typename Derived> mlir::tracing::BreakpointBase< Derived >::BreakpointBase () inline protected
Definition at line 57 of file BreakpointManager.h.
References mlir::tracing::Breakpoint::Breakpoint(), and mlir::get().
Member Function Documentation
classof()
template<typename Derived> bool mlir::tracing::BreakpointBase< Derived >::classof (const Breakpoint * breakpoint) inline static
Support isa/dyn_cast functionality for the derived pass class.
Definition at line 52 of file BreakpointManager.h.
References mlir::tracing::Breakpoint::Breakpoint(), mlir::TypeID::get(), and mlir::tracing::Breakpoint::getTypeID().
The documentation for this class was generated from the following file:
include/mlir/Debug/BreakpointManager.h