MLIR: mlir::tblgen::ParentClass Class Reference
mlir::tblgen::ParentClass Class Reference
This class describes a C++ parent class declaration.
#include "mlir/TableGen/Class.h"
Public Member Functions
template<typename NameT>
ParentClass (NameT &&name, Visibility visibility=Visibility::Public)
Create a parent class with a class name and visibility.
template<typename ParamT>
void addTemplateParam (ParamT param)
Add a template parameter.
template<typename ContainerT>
void addTemplateParams (ContainerT &&container)
Add a list of template parameters.
void writeTo (raw_indented_ostream &os) const
Write the parent class declaration.
Detailed Description
This class describes a C++ parent class declaration.
Definition at line 521 of file Class.h.
Constructor & Destructor Documentation
ParentClass()
template<typename NameT> mlir::tblgen::ParentClass::ParentClass (NameT && name, Visibility visibility = Visibility::Public) inline
Create a parent class with a class name and visibility.
Definition at line 525 of file Class.h.
References mlir::tblgen::Public, and mlir::tblgen::stringify().
Member Function Documentation
addTemplateParam()
template<typename ParamT> void mlir::tblgen::ParentClass::addTemplateParam (ParamT param) inline
Add a template parameter.
Definition at line 530 of file Class.h.
References mlir::tblgen::stringify().
addTemplateParams()
template<typename ContainerT> void mlir::tblgen::ParentClass::addTemplateParams (ContainerT && container) inline
Add a list of template parameters.
Definition at line 535 of file Class.h.
writeTo()
void ParentClass::writeTo (raw_indented_ostream & os) const
Write the parent class declaration.
Definition at line 266 of file Class.cpp.
References mlir::raw_indented_ostream::scope().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp