MLIR: mlir::pdll::ast::Context Class Reference
mlir::pdll::ast::Context Class Reference
This class represents the main context of the PDLL AST.
#include "mlir/Tools/PDLL/AST/Context.h"
Public Member Functions
Context (ods::Context &odsContext)
Context (const Context &)=delete
Context & operator= (const Context &)=delete
llvm::BumpPtrAllocator & getAllocator ()
Return the allocator owned by this context.
StorageUniquer & getTypeUniquer ()
Return the storage uniquer used for AST types.
ods::Context & getODSContext ()
Return the ODS context used by the AST.
const ods::Context & getODSContext () const
DiagnosticEngine & getDiagEngine ()
Return the diagnostic engine of this context.
Detailed Description
This class represents the main context of the PDLL AST.
It handles allocating all of the AST constructs, and manages all state necessary for the AST.
Definition at line 25 of file Context.h.
Constructor & Destructor Documentation
Context() [1/2]
Context::Context (ods::Context & odsContext) explicit
Definition at line 15 of file Context.cpp.
Referenced by Context(), and operator=().
Context() [2/2]
mlir::pdll::ast::Context::Context (const Context &) delete
References Context().
Member Function Documentation
getAllocator()
llvm::BumpPtrAllocator & mlir::pdll::ast::Context::getAllocator () inline
Return the allocator owned by this context.
Definition at line 32 of file Context.h.
Referenced by copyStringWithNull(), mlir::pdll::ast::AttrConstraintDecl::create(), mlir::pdll::ast::AttributeExpr::create(), mlir::pdll::ast::CallExpr::create(), mlir::pdll::ast::CompoundStmt::create(), mlir::pdll::ast::DeclRefExpr::create(), mlir::pdll::ast::EraseStmt::create(), mlir::pdll::ast::LetStmt::create(), mlir::pdll::ast::MemberAccessExpr::create(), mlir::pdll::ast::Module::create(), mlir::pdll::ast::Name::create(), mlir::pdll::ast::NamedAttributeDecl::create(), mlir::pdll::ast::OpConstraintDecl::create(), mlir::pdll::ast::OperationExpr::create(), mlir::pdll::ast::OpNameDecl::create(), mlir::pdll::ast::OpNameDecl::create(), mlir::pdll::ast::PatternDecl::create(), mlir::pdll::ast::RangeExpr::create(), mlir::pdll::ast::ReplaceStmt::create(), mlir::pdll::ast::ReturnStmt::create(), mlir::pdll::ast::RewriteStmt::create(), mlir::pdll::ast::TupleExpr::create(), mlir::pdll::ast::TypeConstraintDecl::create(), mlir::pdll::ast::TypeExpr::create(), mlir::pdll::ast::TypeRangeConstraintDecl::create(), mlir::pdll::ast::ValueConstraintDecl::create(), mlir::pdll::ast::ValueRangeConstraintDecl::create(), mlir::pdll::ast::VariableDecl::create(), and mlir::pdll::ast::Decl::setDocComment().
getDiagEngine()
DiagnosticEngine & mlir::pdll::ast::Context::getDiagEngine () inline
Return the diagnostic engine of this context.
Definition at line 42 of file Context.h.
Referenced by mlir::parseSourceFile().
getODSContext() [1/2]
ods::Context & mlir::pdll::ast::Context::getODSContext () inline
Return the ODS context used by the AST.
Definition at line 38 of file Context.h.
getODSContext() [2/2]
const ods::Context & mlir::pdll::ast::Context::getODSContext () const inline
Definition at line 39 of file Context.h.
getTypeUniquer()
StorageUniquer & mlir::pdll::ast::Context::getTypeUniquer () inline
Return the storage uniquer used for AST types.
Definition at line 35 of file Context.h.
Referenced by mlir::pdll::ast::AttributeType::get(), mlir::pdll::ast::ConstraintType::get(), mlir::pdll::ast::OperationType::get(), mlir::pdll::ast::RangeType::get(), mlir::pdll::ast::RewriteType::get(), mlir::pdll::ast::TupleType::get(), mlir::pdll::ast::TypeType::get(), and mlir::pdll::ast::ValueType::get().
operator=()
Context & mlir::pdll::ast::Context::operator= (const Context &) delete
References Context().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Context.h
lib/Tools/PDLL/AST/Context.cpp