MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig Class Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig Class Reference
Public Member Functions
PyConversionConfig ()
MlirConversionConfig get ()
void setFoldingMode (PyDialectConversionFoldingMode mode)
PyDialectConversionFoldingMode getFoldingMode ()
void enableBuildMaterializations (bool enabled)
bool isBuildMaterializationsEnabled ()
Detailed Description
Definition at line 505 of file Rewrite.cpp.
Constructor & Destructor Documentation
PyConversionConfig()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig::PyConversionConfig () inline
Definition at line 507 of file Rewrite.cpp.
Referenced by isBuildMaterializationsEnabled().
Member Function Documentation
enableBuildMaterializations()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig::enableBuildMaterializations (bool enabled) inline
Definition at line 523 of file Rewrite.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::AfterPatterns, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BeforePatterns, MLIR_DIALECT_CONVERSION_FOLDING_MODE_AFTER_PATTERNS, MLIR_DIALECT_CONVERSION_FOLDING_MODE_BEFORE_PATTERNS, MLIR_DIALECT_CONVERSION_FOLDING_MODE_NEVER, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::Never.
get()
MlirConversionConfig mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig::get () inline
Definition at line 511 of file Rewrite.cpp.
getFoldingMode()
PyDialectConversionFoldingMode mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig::getFoldingMode () inline
Definition at line 518 of file Rewrite.cpp.
isBuildMaterializationsEnabled()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig::isBuildMaterializationsEnabled () inline
Definition at line 527 of file Rewrite.cpp.
References mlir::get(), mlirConversionConfigCreate(), mlirConversionConfigSetFoldingMode(), PyConversionConfig(), and setFoldingMode().
setFoldingMode()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConversionConfig::setFoldingMode (PyDialectConversionFoldingMode mode) inline
Definition at line 513 of file Rewrite.cpp.
References mlirGreedyRewriteDriverConfigDestroy().
Referenced by isBuildMaterializationsEnabled().
The documentation for this class was generated from the following file:
lib/Bindings/Python/Rewrite.cpp