MLIR: mlir::lsp::JSONTransportInput Class Reference
mlir::lsp::JSONTransportInput Class Reference abstract
An abstract class used by the JSONTransport to read JSON message.
#include "mlir/Tools/lsp-server-support/Transport.h"
Public Member Functions
JSONTransportInput (JSONStreamStyle style=JSONStreamStyle::Standard)
virtual ~JSONTransportInput ()=default
virtual bool hasError () const =0
virtual bool isEndOfInput () const =0
LogicalResult readMessage (std::string &json)
Read in a message from the input stream.
virtual LogicalResult readDelimitedMessage (std::string &json)=0
virtual LogicalResult readStandardMessage (std::string &json)=0
Detailed Description
An abstract class used by the JSONTransport to read JSON message.
Definition at line 47 of file Transport.h.
Constructor & Destructor Documentation
JSONTransportInput()
mlir::lsp::JSONTransportInput::JSONTransportInput (JSONStreamStyle style = JSONStreamStyle::Standard) inline explicit
Definition at line 49 of file Transport.h.
~JSONTransportInput()
virtual mlir::lsp::JSONTransportInput::~JSONTransportInput () virtual default
Member Function Documentation
hasError()
virtual bool mlir::lsp::JSONTransportInput::hasError () const pure virtual
Implemented in mlir::lsp::JSONTransportInputOverFile.
isEndOfInput()
virtual bool mlir::lsp::JSONTransportInput::isEndOfInput () const pure virtual
Implemented in mlir::lsp::JSONTransportInputOverFile.
readDelimitedMessage()
virtual LogicalResult mlir::lsp::JSONTransportInput::readDelimitedMessage (std::string & json) pure virtual
Implemented in mlir::lsp::JSONTransportInputOverFile.
Referenced by readMessage().
readMessage()
LogicalResult mlir::lsp::JSONTransportInput::readMessage (std::string & json) inline
Read in a message from the input stream.
Definition at line 57 of file Transport.h.
References mlir::lsp::Delimited, readDelimitedMessage(), and readStandardMessage().
readStandardMessage()
virtual LogicalResult mlir::lsp::JSONTransportInput::readStandardMessage (std::string & json) pure virtual
Implemented in mlir::lsp::JSONTransportInputOverFile.
Referenced by readMessage().
The documentation for this class was generated from the following file:
include/mlir/Tools/lsp-server-support/Transport.h