MLIR: mlir::LLVM::LLVMFunctionType Class Reference
mlir::LLVM::LLVMFunctionType Class Reference
LLVM dialect function type.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
bool isVarArg ()
Returns whether the function is variadic.
Type getReturnType ()
Returns the result type of the function.
unsigned getNumParams ()
Returns the number of arguments to the function.
Type getParamType (unsigned i)
Returns i-th argument of the function. Asserts on out-of-bounds.
ArrayRef< Type > getParams ()
Returns a list of argument types of the function.
ArrayRef< Type > params ()
Static Public Member Functions
static bool isValidArgumentType (Type type)
Checks if the given type can be used an argument in a function type.
static bool isValidResultType (Type type)
Checks if the given type can be used as a result in a function type.
static LLVMFunctionType get (Type result, ArrayRef< Type > arguments, bool isVarArg=false)
Gets or creates an instance of LLVM dialect function in the same context as the result type.
static LLVMFunctionType getChecked (function_ref< InFlightDiagnostic()> emitError, Type result, ArrayRef< Type > arguments, bool isVarArg=false)
static LogicalResult verify (function_ref< InFlightDiagnostic()> emitError, Type result, ArrayRef< Type > arguments, bool)
Verifies that the type about to be constructed is well-formed.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... IfaceModels>
static void attachInterface (MLIRContext &context)
Attach the given models as implementations of the corresponding interfaces for the concrete storage user class.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static ConcreteT getChecked (function_ref< InFlightDiagnostic()> emitErrorFn, MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verify (Args... args)
Default implementation that just returns success.
Detailed Description
LLVM dialect function type.
It consists of a single return type (unlike MLIR which can have multiple), a list of parameter types and can optionally be variadic.
Definition at line 108 of file LLVMTypes.h.
Member Function Documentation
get()
LLVMFunctionType LLVMFunctionType::get (Type result, ArrayRef< Type > arguments, bool isVarArg = false) static
Gets or creates an instance of LLVM dialect function in the same context as the result type.
Definition at line 74 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), and mlir::Type::getContext().
Referenced by addLLVMFuncDecl(), addResumeFunction(), buildLLVMFunctionType(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), convertOperationImpl(), encodeKernelName(), mlir::LLVM::lookupOrCreateFn(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlirLLVMFunctionTypeGet(), parseCallOp(), parseInvokeOp(), mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType(), and wrapExternalFunction().
getChecked()
LLVMFunctionType LLVMFunctionType::getChecked (function_ref< InFlightDiagnostic()> emitError, Type result, ArrayRef< Type > arguments, bool isVarArg = false) static
Definition at line 81 of file LLVMTypes.cpp.
References mlir::emitError(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked(), and mlir::Type::getContext().
getNumParams()
unsigned LLVMFunctionType::getNumParams ()
Returns the number of arguments to the function.
Definition at line 91 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by parseShuffleVectorOp(), printLLVMFuncOp(), verify(), and wrapExternalFunction().
getParams()
ArrayRef< Type > LLVMFunctionType::getParams ()
Returns a list of argument types of the function.
Definition at line 101 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getParamType()
Type LLVMFunctionType::getParamType (unsigned i)
Returns i-th argument of the function. Asserts on out-of-bounds.
Definition at line 95 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by parseShuffleVectorOp(), printLLVMFuncOp(), and verify().
getReturnType()
Type LLVMFunctionType::getReturnType ()
Returns the result type of the function.
Definition at line 89 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), printLLVMFuncOp(), mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType(), and verify().
isValidArgumentType()
bool LLVMFunctionType::isValidArgumentType (Type type) static
Checks if the given type can be used an argument in a function type.
Definition at line 66 of file LLVMTypes.cpp.
References mlir::Type::isa().
isValidResultType()
bool LLVMFunctionType::isValidResultType (Type type) static
Checks if the given type can be used as a result in a function type.
Definition at line 70 of file LLVMTypes.cpp.
References mlir::Type::isa().
isVarArg()
bool LLVMFunctionType::isVarArg ()
Returns whether the function is variadic.
Definition at line 99 of file LLVMTypes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType(), and verify().
params()
ArrayRef<Type> mlir::LLVM::LLVMFunctionType::params () inline
Definition at line 144 of file LLVMTypes.h.
References mlir::emitError(), and mlir::verify().
verify()
LogicalResult LLVMFunctionType::verify (function_ref< InFlightDiagnostic()> emitError, Type result, ArrayRef< Type > arguments, bool) static
Verifies that the type about to be constructed is well-formed.
Definition at line 106 of file LLVMTypes.cpp.
References mlir::emitError(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp