MLIR: lib/Dialect/SparseTensor/Transforms/Utils/CodegenEnv.cpp File Reference
CodegenEnv.cpp File Reference
#include "CodegenEnv.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorType.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include <optional>
Functions
static bool isMaterializing (Value val)
Returns true if tensor materializes uninitialized into the computation.
static void sortDependentLoops (std::vector< LoopCoeffPair > &target)
Sorts the dependent loops such that it is ordered in the same sequence in which loops will be generated.
Function Documentation
isMaterializing()
static bool isMaterializing (Value val) static
Returns true if tensor materializes uninitialized into the computation.
Definition at line 26 of file CodegenEnv.cpp.
References mlir::Value::getDefiningOp().
Referenced by mlir::sparse_tensor::CodegenEnv::isAdmissibleTensorExp().
sortDependentLoops()
static void sortDependentLoops (std::vector< LoopCoeffPair > & target) static
Sorts the dependent loops such that it is ordered in the same sequence in which loops will be generated.
Definition at line 33 of file CodegenEnv.cpp.
Referenced by mlir::sparse_tensor::CodegenEnv::startEmit().