MLIR: lib/TableGen/CodeGenHelpers.cpp File Reference
CodeGenHelpers.cpp File Reference
#include "mlir/TableGen/CodeGenHelpers.h"
#include "mlir/Support/LLVM.h"
#include "mlir/TableGen/Argument.h"
#include "mlir/TableGen/Attribute.h"
#include "mlir/TableGen/Format.h"
#include "mlir/TableGen/Operator.h"
#include "mlir/TableGen/Pattern.h"
#include "mlir/TableGen/Property.h"
#include "mlir/TableGen/Region.h"
#include "mlir/TableGen/Successor.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/CodeGenHelpers.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include <cassert>
#include <optional>
#include <string>
Functions
static std::string getUniqueOutputLabel (const RecordKeeper &records, StringRef tag)
Generate a unique label based on the current file name to prevent name collisions if multiple generated files are included at once.
static bool canUniqueAttrConstraint (Attribute attr)
An attribute constraint that references anything other than itself and the current op cannot be generically extracted into a function.
static bool canUniquePropConstraint (Property prop)
A property constraint that references anything other than itself and the current op cannot be generically extracted into a function, just as with canUnequePropConstraint().
Variables
static const char *const typeConstraintCode
Code templates for emitting type, attribute, successor, and region constraints.
static const char *const attrConstraintCode
Code for an attribute constraint.
static const char *const propConstraintCode
Code for a property constraint.
static const char *const successorConstraintCode
Code for a successor constraint.
static const char *const regionConstraintCode
Code for a region constraint.
static const char *const patternConstraintCode
Code for a pattern type or attribute constraint.
Function Documentation
canUniqueAttrConstraint()
bool canUniqueAttrConstraint (Attribute attr) static
An attribute constraint that references anything other than itself and the current op cannot be generically extracted into a function.
Most prohibitive are operands and results, which require calls to getODSOperands or getODSResults. Attribute references are tricky too because ops use cached identifiers.
Definition at line 376 of file CodeGenHelpers.cpp.
References mlir::tblgen::FmtContext::addSubst(), mlir::tblgen::tgfmt(), and mlir::tblgen::FmtContext::withSelf().
Referenced by mlir::tblgen::StaticVerifierFunctionEmitter::collectOpConstraints().
canUniquePropConstraint()
bool canUniquePropConstraint (Property prop) static
A property constraint that references anything other than itself and the current op cannot be generically extracted into a function, just as with canUnequePropConstraint().
Additionally, property constraints without an interface type specified can't be uniqued, and ones that are a literal "true" shouldn't be constrained.
Definition at line 389 of file CodeGenHelpers.cpp.
References mlir::tblgen::FmtContext::addSubst(), mlir::tblgen::Constraint::getConditionTemplate(), mlir::tblgen::Property::getInterfaceType(), mlir::tblgen::tgfmt(), and mlir::tblgen::FmtContext::withSelf().
Referenced by mlir::tblgen::StaticVerifierFunctionEmitter::collectOpConstraints().
getUniqueOutputLabel()
std::string getUniqueOutputLabel (const RecordKeeper & records, StringRef tag) static
Generate a unique label based on the current file name to prevent name collisions if multiple generated files are included at once.
Definition at line 42 of file CodeGenHelpers.cpp.
Referenced by mlir::tblgen::StaticVerifierFunctionEmitter::StaticVerifierFunctionEmitter().
Variable Documentation
attrConstraintCode
const char* const attrConstraintCode static
Initial value:
= R"(
static ::llvm::LogicalResult {0}(
    ::mlir::Attribute attr, ::llvm::StringRef attrName, llvm::function_ref<::mlir::InFlightDiagnostic()> emitError) {{
  if (attr && !({1}))
    return emitError() << "attribute '" << attrName
        << "' failed to satisfy constraint: {2}";
  return ::mlir::success();
}
static ::llvm::LogicalResult {0}(
    ::mlir::Operation *op, ::mlir::Attribute attr, ::llvm::StringRef attrName) {{
  return {0}(attr, attrName, [op]() {{
    return op->emitOpError();
  });
}
)"
Code for an attribute constraint.
These may be called from ops only. Attribute constraints cannot reference anything other than $_self and $_op.
TODO: Unique constraints for adaptors. However, most Adaptor::verify functions are stripped anyways.
Definition at line 205 of file CodeGenHelpers.cpp.
patternConstraintCode
const char* const patternConstraintCode static
Initial value:
= R"(
static ::llvm::LogicalResult {0}(
    ::mlir::PatternRewriter &rewriter, ::mlir::Operation *op, {3},
    ::llvm::StringRef failureStr) {
  if (!({1})) {
    return rewriter.notifyMatchFailure(op, [&](::mlir::Diagnostic &diag) {
      diag << failureStr << ": {2}";
    });
  }
  return ::mlir::success();
}
)"
Code for a pattern type or attribute constraint.
{0}: name of function {1}: Condition template {2}: Constraint summary {3}: "::mlir::Type type" or "::mlirAttribute attr" or "propType prop". Can be "T prop" for generic property constraints.
Definition at line 275 of file CodeGenHelpers.cpp.
propConstraintCode
const char* const propConstraintCode static
Initial value:
= R"(
  static ::llvm::LogicalResult {0}(
      {3} prop, ::llvm::StringRef propName, llvm::function_ref<::mlir::InFlightDiagnostic()> emitError) {{
    if (!({1}))
      return emitError() << "property '" << propName
          << "' failed to satisfy constraint: {2}";
    return ::mlir::success();
  }
  static ::llvm::LogicalResult {0}(
      ::mlir::Operation *op, {3} prop, ::llvm::StringRef propName) {{
    return {0}(prop, propName, [op]() {{
      return op->emitOpError();
    });
  }
  )"
Code for a property constraint.
These may be called from ops only. Property constraints cannot reference anything other than $_self and $_op. {3} is the interface type of the property.
Definition at line 224 of file CodeGenHelpers.cpp.
regionConstraintCode
const char* const regionConstraintCode static
Initial value:
= R"(
static ::llvm::LogicalResult {0}(
    ::mlir::Operation *op, ::mlir::Region &region, ::llvm::StringRef regionName,
    unsigned regionIndex) {
  if (!({1})) {
    return op->emitOpError("region #") << regionIndex
        << (regionName.empty() ? " " : " ('" + regionName + "') ")
        << "failed to verify constraint: {2}";
  }
  return ::mlir::success();
}
)"
Code for a region constraint.
Callers will need to pass in the region's name for emitting an error message.
Definition at line 255 of file CodeGenHelpers.cpp.
successorConstraintCode
const char* const successorConstraintCode static
Initial value:
= R"(
static ::llvm::LogicalResult {0}(
    ::mlir::Operation *op, ::mlir::Block *successor,
    ::llvm::StringRef successorName, unsigned successorIndex) {
  if (!({1})) {
    return op->emitOpError("successor #") << successorIndex << " ('"
        << successorName << ")' failed to verify constraint: {2}";
  }
  return ::mlir::success();
}
)"
Code for a successor constraint.
Definition at line 241 of file CodeGenHelpers.cpp.
typeConstraintCode
const char* const typeConstraintCode static
Initial value:
= R"(
static ::llvm::LogicalResult {0}(
    ::mlir::Operation *op, ::mlir::Type type, ::llvm::StringRef valueKind,
    unsigned valueIndex) {
  if (!({1})) {
    return op->emitOpError(valueKind) << " #" << valueIndex
        << " must be {2}, but got " << type;
  }
  return ::mlir::success();
}
)"
Code templates for emitting type, attribute, successor, and region constraints.
Each of these templates require the following arguments:
{0}: The unique constraint name. {1}: The constraint code. {2}: The constraint description. Code for a type constraint. These may be called on the type of either operands or results.
Definition at line 187 of file CodeGenHelpers.cpp.