MLIR: lib/Dialect/Linalg/Transforms/ComprehensiveBufferize.cpp File Reference
ComprehensiveBufferize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/BufferUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
Macros
#define DEBUG_TYPE "comprehensive-func-bufferize"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X)
Enumerations
enum InPlaceSpec { InPlaceSpec::False, InPlaceSpec::True, InPlaceSpec::None }
Functions
static bool isaTensor (Type t)
static FuncOp getCalledFunction (CallOpInterface callOp)
Return the FuncOp called by callOp.
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static void map (BlockAndValueMapping &bvm, ValueRange keys, ValueRange values)
Wrapper for better debugging.
static void map (BlockAndValueMapping &bvm, Value key, Value value)
Wrapper for better debugging.
static Value lookup (const BlockAndValueMapping &bvm, Value key)
Wrapper for better debugging.
static StringRef stringify (InPlaceSpec val)
static Optional< InPlaceSpec > symbolize (StringRef str)
static void setInPlaceOpResult (OpResult opResult, InPlaceSpec inPlace=InPlaceSpec::True)
Mark whether OpResult can actually be bufferized inplace.
static InPlaceSpec getInPlace (OpResult opResult)
Get the InPlaceSpec attribute entry kInPlaceResultsAttrName for opResult.
static InPlaceSpec getInPlace (BlockArgument bbArg)
Get inPlace information for bbArg.
static void setInPlaceFuncArgument (BlockArgument bbArg, InPlaceSpec inPlaceSpec=InPlaceSpec::True)
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void removeBufferizationFuncArguments (BlockArgument bbArg)
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static LLVM_ATTRIBUTE_UNUSED InPlaceSpec getInPlace (Value v)
static bool hasKnownBufferizationAliasingBehavior (Operation *op)
Return true if the op is explicitly supported by bufferization or if it has no result tensors.
static OpResult getInplaceableOpResult (TiledLoopOp op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (scf::ForOp forOp, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (LinalgOp linalgOp, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (VectorTransferOpInterface op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (InsertSliceOp op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (tensor::CastOp op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static Optional< OpOperand * > getAliasingOpOperand (OpResult result)
Determine which OpOperand* will alias with result if the op is bufferized in place.
static Optional< OpResult > getAliasingOpResult (OpOperand &opOperand)
Determine which OpResult will alias with opOperand if the op is bufferized in place.
static bool bufferizesToMemoryRead (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory read.
static bool bufferizesToMemoryWrite (OpOperand &opOperand, InPlaceSpec inPlaceSpec=InPlaceSpec::None)
Return true if opOperand bufferizes to a memory write.
static Operation * getEquivalentAlloc (Value value, const BufferizationAliasInfo &aliasInfo)
Return the op with Allocate MemoryEffect if v is equivalent to an such an op.
static BlockArgument getEquivalentEnclosingFuncBBArg (Value v, const BufferizationAliasInfo &aliasInfo)
Return the first argument of the enclosing FuncOp that is equivalent to v.
static MemRefType getContiguousMemRefType (ShapedType shapedType, ArrayRef< AffineMap > layout={}, unsigned addressSpace=0)
Return a contiguous MemRefType (i.e.
static Type getContiguousOrUnrankedMemRefType (Type type, ArrayRef< AffineMap > layout={}, unsigned addressSpace=0)
Return a contiguous MemRefType (i.e.
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace=0)
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
static FunctionType getBufferizedFunctionType (MLIRContext *ctx, TypeRange argumentTypes, TypeRange resultTypes)
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
static Value createNewAllocDeallocPairForShapedValue (OpBuilder &b, Location loc, Value shapedValue, BufferizationAliasInfo &aliasInfo)
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
static void allocateBuffersForResults (OpBuilder &b, Location loc, LinalgOp op, SmallVectorImpl< Value > &resultBuffers, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Helper function for LinalgOp bufferization.
static LogicalResult bufferize (OpBuilder &b, LinalgOp op, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Generic conversion for any LinalgOp on tensors.
static LogicalResult bufferize (OpBuilder &b, CallOpInterface callOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
static LogicalResult bufferize (OpBuilder &b, tensor::CastOp castOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
tensor::CastOp bufferizes to memref::CastOp.
static LogicalResult bufferize (OpBuilder &b, ConstantOp constantOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, GlobalCreator &globalCreator)
static LogicalResult bufferize (OpBuilder &b, tensor::DimOp dimOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
DimOp tensor operand is modified inplace.
static LogicalResult bufferize (OpBuilder &b, scf::ForOp forOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, FuncOp funcOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
FuncOp always creates TensorToMemRef ops.
static LogicalResult bufferize (OpBuilder &b, InitTensorOp initTensorOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
InitTensor always allocates.
static LogicalResult bufferize (OpBuilder &b, ReturnOp returnOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
ReturnOp always creates memref::TensorLoadOp.
static LogicalResult bufferize (OpBuilder &b, TiledLoopOp tiledLoopOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferization for TiledLoopOp..
static LogicalResult bufferize (OpBuilder &b, ExtractSliceOp extractSliceOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferize ExtractSliceOp to subview with optional alloc + copy depending on whether or not it is marked inplaceable.
static LogicalResult bufferize (OpBuilder &b, InsertSliceOp insertSliceOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, VectorTransferOpInterface op, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, scf::YieldOp yieldOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, linalg::YieldOp yieldOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferization for linalg::YieldOp either does not involve tensors or just results in later canonicalization.
static LogicalResult bufferize (OpBuilder &b, tensor::ExtractOp extractOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferization for tensor::ExtractOp just translate to memref.load, it only reads the tensor.
static LogicalResult bufferizableInPlaceAnalysis (ExtractSliceOp extractSliceOp, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace.
static LogicalResult bufferizableInPlaceAnalysis (OpOperand &operand, OpResult result, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Analyze the (opOperand, result) pair to determine whether the result can be bufferized inPlace.
static LogicalResult inPlaceAnalysisFuncOpBody (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Analyze the funcOp body to determine which OpResults are inplaceable.
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes, GlobalCreator &globalCreator)
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > &orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void applyEnablingTransformations (ModuleOp moduleOp)
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> &callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit)
static void layoutPostProcessing (ModuleOp moduleOp)
Postprocess the linalg.buffer_layout annotation across function boundaries.
Variables
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 137 of file ComprehensiveBufferize.cpp.
Referenced by bufferizeFuncOpBoundary().
DEBUG_TYPE
#define DEBUG_TYPE "comprehensive-func-bufferize"
Definition at line 131 of file ComprehensiveBufferize.cpp.
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X)
Definition at line 138 of file ComprehensiveBufferize.cpp.
Referenced by bufferizableInPlaceAnalysis(), bufferize(), bufferizeFuncOpInternals(), bufferizesToMemoryWrite(), getOrCreateBufferizedFunctionType(), inPlaceAnalysisFuncOpBody(), lookup(), map(), and setInPlaceOpResult().
Enumeration Type Documentation
InPlaceSpec
enum InPlaceSpec strong
Enumerator
False
True
None
Definition at line 220 of file ComprehensiveBufferize.cpp.
Function Documentation
allocateBuffersForResults()
static void allocateBuffersForResults (OpBuilder & b, Location loc, LinalgOp op, SmallVectorImpl< Value > & resultBuffers, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Helper function for LinalgOp bufferization.
Examines each result and determines whether it bufferizes inplace on an operand. If the opResult bufferizes inplace, just reuse the existing buffer. Otherwise allocate a new buffer to hold the result. When allocating a new buffer, analyze whether op want to read form that buffer. In such a case, insert a copy to ensure the newly allocated buffer is properly initialiazed.
Definition at line 1376 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::Value::getDefiningOp(), getInPlace(), getInplaceableOpResult(), mlir::Value::getType(), mlir::Type::isa(), loc, lookup(), mlir::BlockAndValueMapping::lookupOrDefault(), map(), mlir::OpBuilder::setInsertionPointAfter(), and True.
Referenced by bufferize().
applyEnablingTransformations()
static void applyEnablingTransformations (ModuleOp moduleOp) static
Definition at line 2632 of file ComprehensiveBufferize.cpp.
References mlir::RewritePatternSet::add(), and mlir::applyPatternsAndFoldGreedily().
Referenced by layoutPostProcessing().
bufferizableInPlaceAnalysis() [1/2]
static LogicalResult bufferizableInPlaceAnalysis (ExtractSliceOp extractSliceOp, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace.
===========================================================
When bufferized out of place, a ExtractSlice lowers to alloc + copy. This cannot change the flow of information for either the source or the result buffers.
When bufferized inplace, a ExtractSliceOp does not by itself create any read or write from memory. Instead, it has the effect of merging the alias sets of the source and the result buffers.
An analysis is required to ensure inplace bufferization would not result in RaW dependence violations.
Definition at line 2153 of file ComprehensiveBufferize.cpp.
References LDBG, and mlir::success().
Referenced by inPlaceAnalysisFuncOpBody().
bufferizableInPlaceAnalysis() [2/2]
static LogicalResult bufferizableInPlaceAnalysis (OpOperand & operand, OpResult result, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Analyze the (opOperand, result) pair to determine whether the result can be bufferized inPlace.
If successful, InPlaceSpec::True is set for result. Otherwise, InPlaceSpec::False is set for result.
Definition at line 2191 of file ComprehensiveBufferize.cpp.
References mlir::Value::getDefiningOp(), getInplaceableOpResult(), mlir::OpOperand::getOperandNumber(), mlir::OpResult::getResultNumber(), LDBG, op, and mlir::success().
bufferize() [1/16]
static LogicalResult bufferize (OpBuilder & b, LinalgOp op, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Generic conversion for any LinalgOp on tensors.
Definition at line 1419 of file ComprehensiveBufferize.cpp.
References allocateBuffersForResults(), loc, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by bufferizeFuncOpInternals().
bufferize() [2/16]
static LogicalResult bufferize (OpBuilder & b, CallOpInterface callOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
For now, it is the responsibility of the callOp bufferization to allow FuncOp that are inplaceable to write inPlace.
Definition at line 1464 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), getAssumedUniqueReturnOp(), getCalledFunction(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), lookup(), map(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setAttrs(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [3/16]
static LogicalResult bufferize (OpBuilder & b, tensor::CastOp castOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
tensor::CastOp bufferizes to memref::CastOp.
Definition at line 1601 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getContiguousOrUnrankedMemRefType(), mlir::Type::isa(), lookup(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [4/16]
static LogicalResult bufferize (OpBuilder & b, ConstantOp constantOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, GlobalCreator & globalCreator) static
Definition at line 1629 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::GlobalCreator::getGlobalFor(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [5/16]
static LogicalResult bufferize (OpBuilder & b, tensor::DimOp dimOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
DimOp tensor operand is modified inplace.
This allows leaving dead tensors behind that will get DCE'd.
Definition at line 1651 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [6/16]
static LogicalResult bufferize (OpBuilder & b, scf::ForOp forOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 1667 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), getInPlace(), loc, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), and True.
bufferize() [7/16]
static LogicalResult bufferize (OpBuilder & b, FuncOp funcOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
FuncOp always creates TensorToMemRef ops.
Definition at line 1709 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), map(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
bufferize() [8/16]
static LogicalResult bufferize (OpBuilder & b, InitTensorOp initTensorOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
InitTensor always allocates.
TODO: consider hoisting across function boundaries prior to bufferization.
Definition at line 1735 of file ComprehensiveBufferize.cpp.
References createNewAllocDeallocPairForShapedValue(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [9/16]
static LogicalResult bufferize (OpBuilder & b, ReturnOp returnOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
ReturnOp always creates memref::TensorLoadOp.
Definition at line 1749 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), lookup(), map(), mlir::IROperand< DerivedT, IRValueT >::set(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [10/16]
static LogicalResult bufferize (OpBuilder & b, TiledLoopOp tiledLoopOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferization for TiledLoopOp..
Definition at line 1773 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::Block::getArgument(), mlir::Value::getDefiningOp(), mlir::Builder::getI32VectorAttr(), getInPlace(), mlir::Operation::getOpOperand(), mlir::Value::getType(), mlir::Block::insertArgument(), loc, lookup(), map(), resultIndex(), mlir::IROperand< DerivedT, IRValueT >::set(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferize() [11/16]
static LogicalResult bufferize (OpBuilder & b, ExtractSliceOp extractSliceOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferize ExtractSliceOp to subview with optional alloc + copy depending on whether or not it is marked inplaceable.
Note that getInplaceableOpResult on a ExtractSliceOp always returns null. As consequence a ExtractSliceOp always alloc + copy when taken in isolation.
If not inplaceable, copy.
Definition at line 1906 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::failure(), getInPlace(), mlir::Value::getType(), LDBG, loc, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferize() [12/16]
static LogicalResult bufferize (OpBuilder & b, InsertSliceOp insertSliceOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 1956 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::failure(), mlir::Value::getDefiningOp(), getInPlace(), mlir::Value::getType(), LDBG, loc, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferize() [13/16]
static LogicalResult bufferize (OpBuilder & b, VectorTransferOpInterface op, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
transfer_read from buffer always reads from the bufferized op.source().
Definition at line 2017 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::failure(), getInPlace(), loc, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferize() [14/16]
static LogicalResult bufferize (OpBuilder & b, scf::YieldOp yieldOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 2067 of file ComprehensiveBufferize.cpp.
References mlir::Type::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::Value::getType(), lookup(), mlir::IROperand< DerivedT, IRValueT >::set(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [15/16]
static LogicalResult bufferize (OpBuilder & b, linalg::YieldOp yieldOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferization for linalg::YieldOp either does not involve tensors or just results in later canonicalization.
In either case it does nothing.
Definition at line 2104 of file ComprehensiveBufferize.cpp.
References isaTensor(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [16/16]
static LogicalResult bufferize (OpBuilder & b, tensor::ExtractOp extractOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferization for tensor::ExtractOp just translate to memref.load, it only reads the tensor.
Definition at line 2121 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), loc, lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferizeFuncOpBoundary()
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
This relies on a buffer equivalence analysis of each return operand. When a result buffer is equivalent to:
a BlockArgument of funcOp, it can be dropped from the return values and becomes inplaceable at all callers. This assumes all CallOp perform the necessary work to clone operands so as to make them inplaceable. 2. an op with an Alloc effect, this currently fails bufferization but is a candidate for hoisting and creating a new inplace operand at all caller sites.
if such a hoisting for 2. is not possible (e.g. data-dependent that prevents hoisting), this is currently unsupported and will require a refcounted buffer type.
Definition at line 2430 of file ComprehensiveBufferize.cpp.
References mlir::Block::addArgument(), DBGS, mlir::Type::dyn_cast(), mlir::Block::eraseArgument(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), getAssumedUniqueReturnOp(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), mlir::Block::getNumArguments(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by layoutPostProcessing().
bufferizeFuncOpInternals()
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes, GlobalCreator & globalCreator) static
Start by bufferizing funcOp arguments.
Definition at line 2301 of file ComprehensiveBufferize.cpp.
References bufferize(), mlir::Operation::emitError(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), isaTensor(), LDBG, op, mlir::PreOrder, mlir::success(), and mlir::WalkResult::wasInterrupted().
Referenced by layoutPostProcessing().
bufferizesToMemoryRead()
static bool bufferizesToMemoryRead (OpOperand & opOperand) static
Return true if opOperand bufferizes to a memory read.
Definition at line 537 of file ComprehensiveBufferize.cpp.
References getAliasingOpResult(), and mlir::detail::IROperandBase::getOwner().
Referenced by bufferizesToMemoryWrite().
bufferizesToMemoryWrite()
static bool bufferizesToMemoryWrite (OpOperand & opOperand, InPlaceSpec inPlaceSpec = InPlaceSpec::None) static
Return true if opOperand bufferizes to a memory write.
If inPlaceSpec is different from InPlaceSpec::None, additionally require the write to match the inplace specification.
Definition at line 583 of file ComprehensiveBufferize.cpp.
References bufferizesToMemoryRead(), mlir::DominanceInfo::dominates(), mlir::Value::dyn_cast(), False, mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpOperand(), getAliasingOpResult(), mlir::Value::getDefiningOp(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), mlir::Value::getImpl(), getInPlace(), getInplaceableOpResult(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::Value::getUses(), hasKnownBufferizationAliasingBehavior(), mlir::isEqualConstantIntOrValue(), LDBG, None, op, mlir::operator<(), mlir::operator==(), print(), mlir::DominanceInfo::properlyDominates(), sameOffsetsSizesAndStrides(), setInPlaceOpResult(), True, value, mlir::Operation::walk(), and wrap().
createNewAllocDeallocPairForShapedValue()
static Value createNewAllocDeallocPairForShapedValue (OpBuilder & b, Location loc, Value shapedValue, BufferizationAliasInfo & aliasInfo) static
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
Definition at line 1322 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::linalg::createOrFoldDimOp(), mlir::Type::dyn_cast(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), getContiguousMemRefType(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::Value::getParentBlock(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::kDynamicSize, loc, mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by allocateBuffersForResults(), and bufferize().
foreachCaller()
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> & callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit) static
Definition at line 2639 of file ComprehensiveBufferize.cpp.
Referenced by layoutPostProcessing().
getAliasingOpOperand()
static Optional<OpOperand *> getAliasingOpOperand (OpResult result) static
Determine which OpOperand* will alias with result if the op is bufferized in place.
Return None if the owner of opOperand does not have known bufferization aliasing behavior, which indicates that the op must allocate all of its tensor results. TODO: in the future this may need to evolve towards a list of OpOperand*.
Definition at line 481 of file ComprehensiveBufferize.cpp.
References mlir::Operation::dump(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), hasKnownBufferizationAliasingBehavior(), and op.
Referenced by bufferizesToMemoryWrite().
getAliasingOpResult()
static Optional<OpResult> getAliasingOpResult (OpOperand & opOperand) static
Determine which OpResult will alias with opOperand if the op is bufferized in place.
This is a superset of getInplaceableOpResult. Return None if the owner of opOperand does not have known bufferization aliasing behavior, which indicates that the op must allocate all of its tensor results. TODO: in the future this may need to evolve towards a list of OpResult.
Definition at line 517 of file ComprehensiveBufferize.cpp.
References getInplaceableOpResult(), mlir::detail::IROperandBase::getOwner(), hasKnownBufferizationAliasingBehavior(), and op.
Referenced by bufferizesToMemoryRead(), and bufferizesToMemoryWrite().
getAssumedUniqueReturnOp()
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 157 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), bufferizeFuncOpBoundary(), and getFuncOpsOrderedByCalls().
getBufferizedFunctionType()
static FunctionType getBufferizedFunctionType (MLIRContext * ctx, TypeRange argumentTypes, TypeRange resultTypes) static
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
In order for all the callers to agree, this must bufferize to the most dynamic buffer type supported. A later pass across all CallOps in the module can decide whether to simplify the types of to version according to some cost model.
Definition at line 1279 of file ComprehensiveBufferize.cpp.
References getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), and rewrite().
Referenced by getOrCreateBufferizedFunctionType().
getCalledFunction()
static FuncOp getCalledFunction (CallOpInterface callOp) static
Return the FuncOp called by callOp.
Definition at line 147 of file ComprehensiveBufferize.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by bufferize(), and getFuncOpsOrderedByCalls().
getContiguousMemRefType()
static MemRefType getContiguousMemRefType (ShapedType shapedType, ArrayRef< AffineMap > layout = {}, unsigned addressSpace = 0) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace.
Definition at line 1234 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), and mlir::Type::dyn_cast().
Referenced by createNewAllocDeallocPairForShapedValue(), and getContiguousOrUnrankedMemRefType().
getContiguousOrUnrankedMemRefType()
static Type getContiguousOrUnrankedMemRefType (Type type, ArrayRef< AffineMap > layout = {}, unsigned addressSpace = 0) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace or an UnrankedMemRefType otherwise.
Definition at line 1248 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), getContiguousMemRefType(), mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by bufferize(), and getBufferizedFunctionType().
getDynamicMemRefType()
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace = 0) static
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
The layout must be the most dynamic possible and canonicalize away once bufferization is finished.
Definition at line 1261 of file ComprehensiveBufferize.cpp.
References mlir::ShapedType::kDynamicStrideOrOffset, and mlir::makeStridedLinearLayoutMap().
Referenced by bufferize(), and getBufferizedFunctionType().
getEquivalentAlloc()
static Operation * getEquivalentAlloc (Value value, const BufferizationAliasInfo & aliasInfo) static
Return the op with Allocate MemoryEffect if v is equivalent to an such an op.
Return the op with Allocate MemoryEffect if v is equivalent to such an an op.
Return null otherwise.
Definition at line 2380 of file ComprehensiveBufferize.cpp.
References mlir::Value::getDefiningOp().
Referenced by bufferize(), bufferizeFuncOpBoundary(), and bufferizesToMemoryWrite().
getEquivalentEnclosingFuncBBArg()
static BlockArgument getEquivalentEnclosingFuncBBArg (Value v, const BufferizationAliasInfo & aliasInfo) static
Return the first argument of the enclosing FuncOp that is equivalent to v.
Return null if no such bbArg can be found.
Definition at line 2397 of file ComprehensiveBufferize.cpp.
References mlir::Value::getParentBlock(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Type::isa(), and op.
Referenced by bufferize(), bufferizeFuncOpBoundary(), and bufferizesToMemoryWrite().
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > & orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 2568 of file ComprehensiveBufferize.cpp.
References mlir::WalkResult::advance(), mlir::failure(), getAssumedUniqueReturnOp(), getCalledFunction(), mlir::DialectRegistry::insert(), mlir::success(), and mlir::WalkResult::wasInterrupted().
Referenced by layoutPostProcessing().
getInPlace() [1/3]
static InPlaceSpec getInPlace (OpResult opResult) static
Get the InPlaceSpec attribute entry kInPlaceResultsAttrName for opResult.
If the result is InPlaceSpec::True, the use-def chain analysis has guaranteed that no subsequent read of the tensor value occurs and the result can be buferized inPlace. If no InPlaceSpec attribute has been set for opResult, return InPlaceSpec::None.
Definition at line 276 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, None, op, and symbolize().
Referenced by allocateBuffersForResults(), bufferize(), bufferizesToMemoryWrite(), and getInPlace().
getInPlace() [2/3]
static InPlaceSpec getInPlace (BlockArgument bbArg) static
Get inPlace information for bbArg.
FuncOp allow argument attributes, we use those to encode the information. BlockArgument of other ops delegate to their owner's parent op.
Definition at line 294 of file ComprehensiveBufferize.cpp.
References False, mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::BoolAttr::getValue(), None, and True.
getInPlace() [3/3]
static LLVM_ATTRIBUTE_UNUSED InPlaceSpec getInPlace (Value v) static
Definition at line 335 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), mlir::Value::dyn_cast(), and getInPlace().
getInplaceableOpResult() [1/7]
static OpResult getInplaceableOpResult (TiledLoopOp op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 385 of file ComprehensiveBufferize.cpp.
Referenced by allocateBuffersForResults(), bufferizableInPlaceAnalysis(), bufferizesToMemoryWrite(), getAliasingOpResult(), getInplaceableOpResult(), and inPlaceAnalysisFuncOpBody().
getInplaceableOpResult() [2/7]
static OpResult getInplaceableOpResult (scf::ForOp forOp, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 392 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
getInplaceableOpResult() [3/7]
static OpResult getInplaceableOpResult (LinalgOp linalgOp, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 401 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::Value::getType(), and mlir::Type::isa().
getInplaceableOpResult() [4/7]
static OpResult getInplaceableOpResult (VectorTransferOpInterface op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 421 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
getInplaceableOpResult() [5/7]
static OpResult getInplaceableOpResult (InsertSliceOp op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 432 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get().
getInplaceableOpResult() [6/7]
static OpResult getInplaceableOpResult (tensor::CastOp op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 441 of file ComprehensiveBufferize.cpp.
getInplaceableOpResult() [7/7]
static OpResult getInplaceableOpResult (OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
The inplace analysis uses this information along with interfering read analysis to determine which op results reuse the same buffer as some operand.
Definition at line 451 of file ComprehensiveBufferize.cpp.
References getInplaceableOpResult(), mlir::detail::IROperandBase::getOwner(), and op.
getOrCreateBufferizedFunctionType()
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
Otherwise, construct a new entry based on argumentTypes and resultTypes.
Definition at line 1300 of file ComprehensiveBufferize.cpp.
References getBufferizedFunctionType(), and LDBG.
Referenced by bufferize(), and bufferizeFuncOpBoundary().
hasKnownBufferizationAliasingBehavior()
static bool hasKnownBufferizationAliasingBehavior (Operation * op) static
Return true if the op is explicitly supported by bufferization or if it has no result tensors.
Other cases must be conservative.
Definition at line 361 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), isaTensor(), and op.
Referenced by bufferizesToMemoryWrite(), getAliasingOpOperand(), and getAliasingOpResult().
inPlaceAnalysisFuncOpBody()
static LogicalResult inPlaceAnalysisFuncOpBody (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Analyze the funcOp body to determine which OpResults are inplaceable.
Definition at line 2238 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysis(), mlir::failed(), mlir::failure(), getInplaceableOpResult(), mlir::Operation::getOperandTypes(), mlir::Operation::getOpOperands(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), LDBG, op, and mlir::success().
Referenced by layoutPostProcessing().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 144 of file ComprehensiveBufferize.cpp.
References mlir::Type::isa().
Referenced by bufferize(), bufferizeFuncOpBoundary(), bufferizeFuncOpInternals(), hasKnownBufferizationAliasingBehavior(), and inPlaceAnalysisFuncOpBody().
layoutPostProcessing()
static void layoutPostProcessing (ModuleOp moduleOp) static
Postprocess the linalg.buffer_layout annotation across function boundaries.
This is a purely mechanical process that may later become part of a separate pass with its own layout assignment heuristic.
Definition at line 2651 of file ComprehensiveBufferize.cpp.
References mlir::OpPassManager::addPass(), applyEnablingTransformations(), bufferizeFuncOpBoundary(), bufferizeFuncOpInternals(), mlir::OpBuilder::create(), mlir::createCanonicalizerPass(), mlir::createCSEPass(), mlir::createLoopInvariantCodeMotionPass(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), foreachCaller(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), getFuncOpsOrderedByCalls(), mlir::Operation::getOperand(), mlir::BlockArgument::getOwner(), mlir::getStridedLinearLayoutMap(), inPlaceAnalysisFuncOpBody(), kInPlaceResultsAttrName, op, mlir::Operation::removeAttr(), removeBufferizationFuncArguments(), mlir::Value::replaceAllUsesExcept(), setInPlaceFuncArgument(), mlir::OpBuilder::setInsertionPointToStart(), mlir::Operation::setOperands(), mlir::Value::setType(), and mlir::succeeded().
lookup()
static Value lookup (const BlockAndValueMapping & bvm, Value key) static
Wrapper for better debugging.
Definition at line 187 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Value::getParentBlock(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Type::isa(), LDBG, and mlir::BlockAndValueMapping::lookupOrNull().
Referenced by allocateBuffersForResults(), bufferize(), mlir::detail::InterfaceMap::contains(), mlir::detail::InterfaceMap::insert(), mlir::detail::InterfaceMap::lookup(), and mlir::ContractionOpLowering::matchAndRewrite().
map() [1/2]
static void map (BlockAndValueMapping & bvm, ValueRange keys, ValueRange values) static
Wrapper for better debugging.
Definition at line 174 of file ComprehensiveBufferize.cpp.
References LDBG, and mlir::BlockAndValueMapping::map().
Referenced by acceptBitWidth(), addDomainConstraints(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addNamedOpBuilders(), allocateBuffersForResults(), mlir::linalg::applyPermutationToVector(), bufferize(), buildVectorRead(), buildVectorWrite(), calculateImplicitMap(), canonicalizeLoopBounds(), mlir::canonicalizeMapAndOperands(), mlir::canonicalizeSetAndOperands(), mlir::ConstraintsSet::composeAffineApply(), mlir::ConstraintsSet::composeMax(), computeIterationGraph(), createFoldedComposedAffineApply(), mlir::python::PyAffineExpr::createFromCapsule(), mlir::python::PyIntegerSet::createFromCapsule(), createOrFoldDimOp(), denseUnitStrides(), mlir::vector::distributPointwiseVectorOp(), findSparseAnnotations(), fuseElementwiseOpsImpl(), fuseWithReshapeByExpansion(), genBuffers(), generateCopy(), genInvariants(), genResult(), genTensorLoad(), genTensorStore(), mlir::MemRefAccess::getAccessMap(), mlir::AffineMap::getAsOpaquePointer(), getCollapsedOutputDimFromInputShape(), mlir::getConstantTripCount(), mlir::AffineMap::getContext(), mlir::MutableAffineMap::getContext(), getDimMap(), getExpandedDimToCollapsedDimMap(), mlir::AffineMap::getFromOpaquePointer(), mlir::getLargestDivisorOfTripCount(), mlir::AffineBound::getMap(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineBound::getOperands(), mlir::gpu::getProcessor(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), getShapeDefiningLoopRange(), mlir::AffineDmaWaitOp::getTagMapAttrName(), mlir::Builder::getType(), mlir::FlatAffineConstraints::getUniverse(), inferTransposeResultType(), inlineRegionAndEmitStore(), mlir::detail::NestedAnalysisMap::invalidate(), mlir::ConvertToLLVMPattern::isConvertibleAndHasIdentityMaps(), mlir::AffineMap::isFunctionOfSymbol(), linalgOpToLoopsImpl(), logFailure(), mlir::makeComposedAffineApply(), mlir::linalg::makeTiledShapes(), mlir::linalg::AffineMinRangeCanonicalizationPattern::matchAndRewrite(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), ContractExtractPattern::matchAndRewrite(), TransferReadPermutationLowering::matchAndRewrite(), TransferWritePermutationLowering::matchAndRewrite(), TransferOpReduceRank::matchAndRewrite(), mlir::MutableAffineMap::MutableAffineMap(), mlir::normalizeAffineParallel(), mlir::AffineMap::operator bool(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), mlir::AffineMap::operator==(), outlineKernelFuncImpl(), parseAffineApplyOp(), parseAffineMapWithMinMax(), mlir::detail::Parser::parseAttribute(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), parseBound(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), mlir::detail::Parser::parseIntegerSetReference(), mlir::detail::Parser::parseMemRefType(), mlir::detail::Parser::parseOptionalAttributeWithToken(), parseTransferReadOp(), printBound(), printDenseElementsAttrImpl(), remainsLegalAfterInline(), mlir::AffineExpr::replace(), replaceUnitDims(), mlir::FlatAffineConstraints::setIdValues(), mlir::MemRefType::Builder::setMemorySpace(), mlir::sinkOperationsIntoLaunchOp(), sliceTransferIndices(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), tilePadTensorOp(), vectorizeAsLinalgGeneric(), verify(), verifyDimMap(), verifyNamedStructuredOp(), verifyOutputShape(), mlir::verifyReshapeLikeShapes(), and mlir::AsmState::~AsmState().
map() [2/2]
static void map (BlockAndValueMapping & bvm, Value key, Value value) static
Wrapper for better debugging.
Definition at line 181 of file ComprehensiveBufferize.cpp.
References LDBG, and mlir::BlockAndValueMapping::map().
removeBufferizationFuncArguments()
static void removeBufferizationFuncArguments (BlockArgument bbArg) static
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 327 of file ComprehensiveBufferize.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by layoutPostProcessing().
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, InPlaceSpec inPlaceSpec = InPlaceSpec::True) static
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 317 of file ComprehensiveBufferize.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), and True.
Referenced by layoutPostProcessing().
setInPlaceOpResult()
static void setInPlaceOpResult (OpResult opResult, InPlaceSpec inPlace = InPlaceSpec::True) static
Mark whether OpResult can actually be bufferized inplace.
If inPlace is InPlaceSpec::True, the use-def chain analysis has guaranteed that no subsequent write would occur to the bufferized tensor value (i.e. the result can be bufferized inPlace).
Definition at line 250 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::Operation::getNumResults(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, LDBG, None, op, mlir::Operation::setAttr(), and stringify().
Referenced by bufferizesToMemoryWrite().
stringify()
static StringRef stringify (InPlaceSpec val) static
Definition at line 226 of file ComprehensiveBufferize.cpp.
References False, None, and True.
Referenced by parseOptionalLLVMKeyword(), and setInPlaceOpResult().
symbolize()
static Optional<InPlaceSpec> symbolize (StringRef str) static
Definition at line 238 of file ComprehensiveBufferize.cpp.
References False, None, and True.
Referenced by getInPlace().
Variable Documentation
kInPlaceResultsAttrName
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Definition at line 217 of file ComprehensiveBufferize.cpp.
Referenced by getInPlace(), layoutPostProcessing(), and setInPlaceOpResult().