MLIR: lib/CAPI/Dialect/Complex.cpp File Reference
Complex.cpp File Reference
#include "mlir-c/Dialect/Complex.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
Functions
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION (Complex, complex, mlir::complex::ComplexDialect) bool mlirAttributeIsAComplex(MlirAttribute attr)
MlirAttribute mlirComplexAttrDoubleGet (MlirContext ctx, MlirType type, double real, double imag)
Creates a complex attribute in the given context with the given double real and imaginary values and double-precision FP semantics.
MlirAttribute mlirComplexAttrDoubleGetChecked (MlirLocation loc, MlirType type, double real, double imag)
Same as "mlirComplexAttrDoubleGet", but if the type is not valid for a construction of a ComplexAttr, returns a null MlirAttribute.
double mlirComplexAttrGetRealDouble (MlirAttribute attr)
Returns the real value stored in the given complex attribute, interpreting the value as double.
double mlirComplexAttrGetImagDouble (MlirAttribute attr)
Returns the imaginaryvalue stored in the given complex attribute, interpreting the value as double.
MlirTypeID mlirComplexAttrGetTypeID (void)
Returns the typeID of a Complex attribute.
Function Documentation
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION()
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION (Complex , complex , mlir::complex::ComplexDialect)
Definition at line 17 of file Complex.cpp.
References unwrap().
mlirComplexAttrDoubleGet()
MlirAttribute mlirComplexAttrDoubleGet (MlirContext ctx, MlirType type, double real, double imag)
Creates a complex attribute in the given context with the given double real and imaginary values and double-precision FP semantics.
Definition at line 24 of file Complex.cpp.
References mlir::imag(), mlir::real(), unwrap(), and wrap().
mlirComplexAttrDoubleGetChecked()
MlirAttribute mlirComplexAttrDoubleGetChecked (MlirLocation loc, MlirType type, double real, double imag)
Same as "mlirComplexAttrDoubleGet", but if the type is not valid for a construction of a ComplexAttr, returns a null MlirAttribute.
Definition at line 30 of file Complex.cpp.
References mlir::imag(), mlir::real(), unwrap(), and wrap().
mlirComplexAttrGetImagDouble()
double mlirComplexAttrGetImagDouble (MlirAttribute attr)
Returns the imaginaryvalue stored in the given complex attribute, interpreting the value as double.
Definition at line 40 of file Complex.cpp.
References unwrap().
mlirComplexAttrGetRealDouble()
double mlirComplexAttrGetRealDouble (MlirAttribute attr)
Returns the real value stored in the given complex attribute, interpreting the value as double.
Definition at line 36 of file Complex.cpp.
References unwrap().
mlirComplexAttrGetTypeID()
MlirTypeID mlirComplexAttrGetTypeID (void)
Returns the typeID of a Complex attribute.
Definition at line 44 of file Complex.cpp.
References wrap().