MLIR: lib/Conversion/ControlFlowToSPIRV/ControlFlowToSPIRV.cpp File Reference
ControlFlowToSPIRV.cpp File Reference
#include "mlir/Conversion/ControlFlowToSPIRV/ControlFlowToSPIRV.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "cf-to-spirv-pattern"
Functions
static LogicalResult legalizeBlockArguments (Block &block, Operation *op, PatternRewriter &rewriter, const TypeConverter &converter)
Legailze target block arguments.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "cf-to-spirv-pattern"
Definition at line 23 of file ControlFlowToSPIRV.cpp.
Function Documentation
legalizeBlockArguments()
LogicalResult legalizeBlockArguments (Block & block, Operation * op, PatternRewriter & rewriter, const TypeConverter & converter) static
Legailze target block arguments.
Definition at line 28 of file ControlFlowToSPIRV.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::Block::eraseArgument(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArgument(), mlir::BlockArgument::getLoc(), mlir::Operation::getLoc(), mlir::Block::getNumArguments(), mlir::Value::getType(), mlir::Block::insertArgument(), mlir::RewriterBase::notifyMatchFailure(), mlir::Value::replaceAllUsesWith(), and success().