MLIR: lib/Dialect/Linalg/Transforms/ConvertToDestinationStyle.cpp File Reference
ConvertToDestinationStyle.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/STLExtras.h"
Functions
static Value createInserts (RewriterBase &rewriter, Location loc, int dim, Value destination, ArrayRef< int64_t > shape, ArrayRef< Value > constants, OperandRange::iterator &elementIt, SmallVectorImpl< Value > &indices)
static void createMemcpy (OpBuilder &b, Location loc, Value tensorSource, Value memrefDest, const linalg::BufferizeToAllocationOptions &options)
Create a memcpy from the given source tensor to the given destination memref.
static Operation * movePaddingToFillOrGenericOp (RewriterBase &rewriter, Location loc, PadOp padOp, Value dest)
static SmallVector< Value > reifyOrComputeDynamicSizes (OpBuilder &b, Value value)
static Value createAllocationForTensor (RewriterBase &rewriter, Location loc, Value value, const linalg::BufferizeToAllocationOptions &options, Attribute memorySpace={})
Function Documentation
createAllocationForTensor()
Value createAllocationForTensor (RewriterBase & rewriter, Location loc, Value value, const linalg::BufferizeToAllocationOptions & options, Attribute memorySpace = {}) static
Definition at line 189 of file ConvertToDestinationStyle.cpp.
References options.
Referenced by mlir::linalg::bufferizeToAllocation(), and mlir::linalg::bufferizeToAllocation().
createInserts()
Value createInserts (RewriterBase & rewriter, Location loc, int dim, Value destination, ArrayRef< int64_t > shape, ArrayRef< Value > constants, OperandRange::iterator & elementIt, SmallVectorImpl< Value > & indices) static
Definition at line 32 of file ConvertToDestinationStyle.cpp.
References createInserts(), and indices.
Referenced by createInserts(), and mlir::linalg::rewriteInDestinationPassingStyle().
createMemcpy()
void createMemcpy (OpBuilder & b, Location loc, Value tensorSource, Value memrefDest, const linalg::BufferizeToAllocationOptions & options) static
Create a memcpy from the given source tensor to the given destination memref.
The copy op type can be specified in the options.
Definition at line 56 of file ConvertToDestinationStyle.cpp.
References b, mlir::Value::getType(), mlir::linalg::BufferizeToAllocationOptions::LinalgCopy, mlir::linalg::BufferizeToAllocationOptions::MemrefCopy, and options.
Referenced by mlir::linalg::bufferizeToAllocation().
movePaddingToFillOrGenericOp()
Operation * movePaddingToFillOrGenericOp (RewriterBase & rewriter, Location loc, PadOp padOp, Value dest) static
Definition at line 93 of file ConvertToDestinationStyle.cpp.
References mlir::OpBuilder::createBlock(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::MLIRContext::getLoadedDialect(), mlir::Value::getLoc(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getParentOp(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::m_Constant(), mlir::matchPattern(), mlir::Dialect::materializeConstant(), mlir::RewriterBase::mergeBlocks(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToStart(), and ValueRange.
Referenced by mlir::linalg::rewriteInDestinationPassingStyle().
reifyOrComputeDynamicSizes()
SmallVector< Value > reifyOrComputeDynamicSizes (OpBuilder & b, Value value) static
Definition at line 158 of file ConvertToDestinationStyle.cpp.
References b, mlir::arith::ConstantIndexOp::create(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Value::getType(), and mlir::reifyResultShapes().