MLIR: include/mlir/ExecutionEngine/CRunnerUtils.h File Reference
CRunnerUtils.h File Reference
#include <array>
#include <cassert>
#include <cstdint>
#include <initializer_list>
Classes
struct mlir::detail::Vector1D< T, Dim, IsPowerOf2 >
struct mlir::detail::Vector1D< T, Dim, true >
struct mlir::detail::Vector1D< T, Dim, false >
struct Vector< T, Dim, Dims >
struct Vector< T, Dim >
class StridedMemrefIterator< T, Rank >
Iterate over all elements in a strided memref.
struct StridedMemRefType< T, N >
StridedMemRef descriptor type with static rank.
struct StridedMemRefType< T, 1 >
StridedMemRef descriptor type specialized for rank 1.
struct StridedMemRefType< T, 0 >
StridedMemRef descriptor type specialized for rank 0.
class StridedMemrefIterator< T, Rank >
Iterate over all elements in a strided memref.
class StridedMemrefIterator< T, 0 >
Iterate over all elements in a 0-ranked strided memref.
struct UnrankedMemRefType< T >
class DynamicMemRefType< T >
Namespaces
mlir
Include the generated interface declarations.
mlir::detail
Macros
#define MLIR_CRUNNERUTILS_EXPORT
#define MLIR_CRUNNERUTILS_DEFINE_FUNCTIONS
Typedefs
template<int D1, typename T >
using Vector1D = Vector< T, D1 >
template<int D1, int D2, typename T >
using Vector2D = Vector< T, D1, D2 >
template<int D1, int D2, int D3, typename T >
using Vector3D = Vector< T, D1, D2, D3 >
template<int D1, int D2, int D3, int D4, typename T >
using Vector4D = Vector< T, D1, D2, D3, D4 >
Functions
constexpr bool mlir::detail::isPowerOf2 (int N)
constexpr unsigned mlir::detail::nextPowerOf2 (int N)
template<int N>
void dropFront (int64_t arr[N], int64_t *res)
MLIR_CRUNNERUTILS_EXPORT void memrefCopy (int64_t elemSize, UnrankedMemRefType< char > *src, UnrankedMemRefType< char > *dst)
MLIR_CRUNNERUTILS_EXPORT void printI64 (int64_t i)
MLIR_CRUNNERUTILS_EXPORT void printU64 (uint64_t u)
MLIR_CRUNNERUTILS_EXPORT void printF32 (float f)
MLIR_CRUNNERUTILS_EXPORT void printF64 (double d)
MLIR_CRUNNERUTILS_EXPORT void printOpen ()
MLIR_CRUNNERUTILS_EXPORT void printClose ()
MLIR_CRUNNERUTILS_EXPORT void printComma ()
MLIR_CRUNNERUTILS_EXPORT void printNewline ()
MLIR_CRUNNERUTILS_EXPORT void print_flops (double flops)
MLIR_CRUNNERUTILS_EXPORT double rtclock ()
Macro Definition Documentation
MLIR_CRUNNERUTILS_DEFINE_FUNCTIONS
#define MLIR_CRUNNERUTILS_DEFINE_FUNCTIONS
Definition at line 31 of file CRunnerUtils.h.
MLIR_CRUNNERUTILS_EXPORT
#define MLIR_CRUNNERUTILS_EXPORT
Definition at line 30 of file CRunnerUtils.h.
Typedef Documentation
Vector1D
template<int D1, typename T > using Vector1D = Vector<T, D1>
Definition at line 107 of file CRunnerUtils.h.
Vector2D
template<int D1, int D2, typename T > using Vector2D = Vector<T, D1, D2>
Definition at line 109 of file CRunnerUtils.h.
Vector3D
template<int D1, int D2, int D3, typename T > using Vector3D = Vector<T, D1, D2, D3>
Definition at line 111 of file CRunnerUtils.h.
Vector4D
template<int D1, int D2, int D3, int D4, typename T > using Vector4D = Vector<T, D1, D2, D3, D4>
Definition at line 113 of file CRunnerUtils.h.
Function Documentation
dropFront()
template<int N> void dropFront (int64_t arr[N], int64_t * res)
Definition at line 116 of file CRunnerUtils.h.
Referenced by foldExtractStridedOpFromInsertChain(), and getI64SubArray().
memrefCopy()
MLIR_CRUNNERUTILS_EXPORT void memrefCopy (int64_t elemSize, UnrankedMemRefType< char > * src, UnrankedMemRefType< char > * dst)
print_flops()
MLIR_CRUNNERUTILS_EXPORT void print_flops (double flops)
printClose()
MLIR_CRUNNERUTILS_EXPORT void printClose ()
printComma()
MLIR_CRUNNERUTILS_EXPORT void printComma ()
Referenced by castDataPtr().
printF32()
MLIR_CRUNNERUTILS_EXPORT void printF32 (float f)
printF64()
MLIR_CRUNNERUTILS_EXPORT void printF64 (double d)
printI64()
MLIR_CRUNNERUTILS_EXPORT void printI64 (int64_t i)
printNewline()
MLIR_CRUNNERUTILS_EXPORT void printNewline ()
Referenced by operator<<(), and printDenseElementsAttrImpl().
printOpen()
MLIR_CRUNNERUTILS_EXPORT void printOpen ()
printU64()
MLIR_CRUNNERUTILS_EXPORT void printU64 (uint64_t u)
rtclock()
MLIR_CRUNNERUTILS_EXPORT double rtclock ()