MLIR: lib/Target/LLVMIR/DebugTranslation.cpp File Reference
DebugTranslation.cpp File Reference
#include "DebugTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
Functions
static WalkResult interruptIfValidLocation (Operation *op)
A utility walker that interrupts if the operation has valid debug information.
template<class DINodeT , class... Ts>
static DINodeT * getDistinctOrUnique (bool isDistinct, Ts &&...args)
Returns a new DINodeT that is either distinct or not, depending on isDistinct.
Variables
static constexpr StringRef kDebugVersionKey = "Debug Info Version"
static constexpr StringRef kCodeViewKey = "CodeView"
Function Documentation
getDistinctOrUnique()
template<class DINodeT , class... Ts> static DINodeT* getDistinctOrUnique (bool isDistinct, Ts &&... args) static
Returns a new DINodeT that is either distinct or not, depending on isDistinct.
Definition at line 138 of file DebugTranslation.cpp.
References mlir::get().
interruptIfValidLocation()
static WalkResult interruptIfValidLocation (Operation * op) static
A utility walker that interrupts if the operation has valid debug information.
Definition at line 23 of file DebugTranslation.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getLoc(), and mlir::WalkResult::interrupt().
Referenced by mlir::LLVM::detail::DebugTranslation::DebugTranslation().
Variable Documentation
kCodeViewKey
constexpr StringRef kCodeViewKey = "CodeView" static constexpr
Definition at line 38 of file DebugTranslation.cpp.
Referenced by mlir::LLVM::detail::DebugTranslation::addModuleFlagsIfNotPresent().
kDebugVersionKey
constexpr StringRef kDebugVersionKey = "Debug Info Version" static constexpr
Definition at line 37 of file DebugTranslation.cpp.
Referenced by mlir::LLVM::detail::DebugTranslation::addModuleFlagsIfNotPresent().