MLIR: lib/CAPI/Debug/Debug.cpp File Reference
Debug.cpp File Reference
#include "mlir-c/Debug.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/Support.h"
#include "llvm/Support/Debug.h"
Functions
void mlirEnableGlobalDebug (bool enable)
Sets the global debugging flag.
bool mlirIsGlobalDebugEnabled ()
Retuns true if the global debugging flag is set, false otherwise.
void mlirSetGlobalDebugType (const char *type)
Sets the current debug type, similarly to -debug-only=type in the command-line tools.
void mlirSetGlobalDebugTypes (const char **types, intptr_t n)
bool mlirIsCurrentDebugType (const char *type)
Sets multiple current debug types, similarly to `-debug-only=type1,type2" in / the command-line tools.
Function Documentation
mlirEnableGlobalDebug()
void mlirEnableGlobalDebug (bool enable)
Sets the global debugging flag.
Definition at line 16 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::set().
mlirIsCurrentDebugType()
bool mlirIsCurrentDebugType (const char * type)
Sets multiple current debug types, similarly to `-debug-only=type1,type2" in / the command-line tools.
Note that global debug should be enabled for any / output to be produced. MLIR_CAPI_EXPORTED void mlirSetGlobalDebugTypes(const char **types, intptr_t n);
/ Checks if type is set as the current debug type.
Definition at line 33 of file Debug.cpp.
mlirIsGlobalDebugEnabled()
bool mlirIsGlobalDebugEnabled ()
Retuns true if the global debugging flag is set, false otherwise.
Definition at line 18 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::get().
mlirSetGlobalDebugType()
void mlirSetGlobalDebugType (const char * type)
Sets the current debug type, similarly to -debug-only=type in the command-line tools.
Note that global debug should be enabled for any output to be produced.
Definition at line 20 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::bind().
mlirSetGlobalDebugTypes()
void mlirSetGlobalDebugTypes (const char ** types, intptr_t n)
Definition at line 28 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::bind().