MLIR: include/mlir-c/Debug.h File Reference
Debug.h File Reference
#include "mlir-c/Support.h"
#include <stdbool.h>
Macros
#define MLIR_C_DEBUG_H
Functions
MLIR_CAPI_EXPORTED void mlirEnableGlobalDebug (bool enable)
Sets the global debugging flag.
MLIR_CAPI_EXPORTED bool mlirIsGlobalDebugEnabled ()
Retuns true if the global debugging flag is set, false otherwise.
MLIR_CAPI_EXPORTED void mlirSetGlobalDebugType (const char *type)
Sets the current debug type, similarly to -debug-only=type in the command-line tools.
MLIR_CAPI_EXPORTED void mlirSetGlobalDebugTypes (const char **types, intptr_t n)
Sets multiple current debug types, similarly to `-debug-only=type1,type2" in the command-line tools.
MLIR_CAPI_EXPORTED bool mlirIsCurrentDebugType (const char *type)
Checks if type is set as the current debug type.
Macro Definition Documentation
MLIR_C_DEBUG_H
#define MLIR_C_DEBUG_H
Definition at line 42 of file Debug.h.
Function Documentation
mlirEnableGlobalDebug()
MLIR_CAPI_EXPORTED void mlirEnableGlobalDebug (bool enable)
Sets the global debugging flag.
Definition at line 16 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::set().
mlirIsCurrentDebugType()
MLIR_CAPI_EXPORTED bool mlirIsCurrentDebugType (const char * type)
Checks if type is set as the current debug type.
Definition at line 33 of file Debug.cpp.
mlirIsGlobalDebugEnabled()
MLIR_CAPI_EXPORTED bool mlirIsGlobalDebugEnabled ()
Retuns true if the global debugging flag is set, false otherwise.
Definition at line 18 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::get().
mlirSetGlobalDebugType()
MLIR_CAPI_EXPORTED void mlirSetGlobalDebugType (const char * type)
Sets the current debug type, similarly to -debug-only=type in the command-line tools.
Note that global debug should be enabled for any output to be produced.
Definition at line 20 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::bind().
mlirSetGlobalDebugTypes()
MLIR_CAPI_EXPORTED void mlirSetGlobalDebugTypes (const char ** types, intptr_t n)
Sets multiple current debug types, similarly to `-debug-only=type1,type2" in the command-line tools.
Note that global debug should be enabled for any output to be produced.
Definition at line 28 of file Debug.cpp.
Referenced by PyGlobalDebugFlag::bind().