MLIR: lib/Dialect/GPU/Transforms/DecomposeMemRefs.cpp File Reference
DecomposeMemRefs.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h.inc"
Classes
class mlir::impl::GpuDecomposeMemrefsPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_GPUDECOMPOSEMEMREFSPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuDecomposeMemrefsPass ()
std::unique_ptr<::mlir::Pass > mlir::createGpuDecomposeMemrefsPass ()
static MemRefType inferCastResultType (Value source, OpFoldResult offset)
static void setInsertionPointToStart (OpBuilder &builder, Value val)
static bool isInsideLaunch (Operation *op)
static std::tuple< Value, OpFoldResult, SmallVector< OpFoldResult > > getFlatOffsetAndStrides (OpBuilder &rewriter, Location loc, Value source, ArrayRef< OpFoldResult > subOffsets, ArrayRef< OpFoldResult > subStrides={})
static Value getFlatMemref (OpBuilder &rewriter, Location loc, Value source, ValueRange offsets)
static bool needFlatten (Value val)
static bool checkLayout (Value val)
Macro Definition Documentation
GEN_PASS_DEF_GPUDECOMPOSEMEMREFSPASS
#define GEN_PASS_DEF_GPUDECOMPOSEMEMREFSPASS
Definition at line 24 of file DecomposeMemRefs.cpp.
Function Documentation
checkLayout()
bool checkLayout (Value val) static
Definition at line 121 of file DecomposeMemRefs.cpp.
getFlatMemref()
Value getFlatMemref (OpBuilder & rewriter, Location loc, Value source, ValueRange offsets) static
Definition at line 105 of file DecomposeMemRefs.cpp.
References mlir::getAsOpFoldResult(), and getFlatOffsetAndStrides().
getFlatOffsetAndStrides()
std::tuple< Value, OpFoldResult, SmallVector< OpFoldResult > > getFlatOffsetAndStrides (OpBuilder & rewriter, Location loc, Value source, ArrayRef< OpFoldResult > subOffsets, ArrayRef< OpFoldResult > subStrides = {}) static
Definition at line 54 of file DecomposeMemRefs.cpp.
Referenced by getFlatMemref().
inferCastResultType()
MemRefType inferCastResultType (Value source, OpFoldResult offset) static
Definition at line 30 of file DecomposeMemRefs.cpp.
References mlir::dispatchIndexOpFoldResults(), mlir::Value::getContext(), and mlir::Value::getType().
isInsideLaunch()
bool isInsideLaunch (Operation * op) static
Definition at line 49 of file DecomposeMemRefs.cpp.
References mlir::Operation::getParentOfType().
needFlatten()
bool needFlatten (Value val) static
Definition at line 116 of file DecomposeMemRefs.cpp.
setInsertionPointToStart()
void setInsertionPointToStart (OpBuilder & builder, Value val) static
Definition at line 41 of file DecomposeMemRefs.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getParentBlock(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().