MLIR: lib/Target/SPIRV/Deserialization/DeserializeOps.cpp File Reference
DeserializeOps.cpp File Reference
#include "Deserializer.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Location.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVSerialization.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Macros
#define DEBUG_TYPE "spirv-deserialization"
#define GET_DESERIALIZATION_FNS
Functions
static spirv::Opcode extractOpcode (uint32_t word)
Extracts the opcode from the given first word of a SPIR-V instruction.
template<>
LogicalResult mlir::spirv::Deserializer::processOp< spirv::EntryPointOp > (ArrayRef< uint32_t > words)
template<>
LogicalResult mlir::spirv::Deserializer::processOp< spirv::ExecutionModeOp > (ArrayRef< uint32_t > words)
template<>
LogicalResult mlir::spirv::Deserializer::processOp< spirv::ControlBarrierOp > (ArrayRef< uint32_t > operands)
template<>
LogicalResult mlir::spirv::Deserializer::processOp< spirv::FunctionCallOp > (ArrayRef< uint32_t > operands)
template<>
LogicalResult mlir::spirv::Deserializer::processOp< spirv::MemoryBarrierOp > (ArrayRef< uint32_t > operands)
template<>
LogicalResult mlir::spirv::Deserializer::processOp< spirv::CopyMemoryOp > (ArrayRef< uint32_t > words)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-deserialization"
Definition at line 24 of file DeserializeOps.cpp.
GET_DESERIALIZATION_FNS
#define GET_DESERIALIZATION_FNS
Definition at line 569 of file DeserializeOps.cpp.
Function Documentation
extractOpcode()
static spirv::Opcode extractOpcode (uint32_t word) inline static
Extracts the opcode from the given first word of a SPIR-V instruction.
Definition at line 31 of file DeserializeOps.cpp.
References mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::emitError(), mlir::OpBuilder::getBlock(), mlir::Block::getParentOp(), mlir::Operation::getResult(), mlir::Builder::getSymbolRefAttr(), mlir::Operation::hasTrait(), loc, op, and mlir::success().