MLIR: lib/Bindings/Python/DialectGPU.cpp File Reference
DialectGPU.cpp File Reference
#include "mlir-c/Dialect/GPU.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
NB_MODULE (_mlirDialectsGPU, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlirDialectsGPU , m)
Definition at line 26 of file DialectGPU.cpp.
References MlirStringRef::data, mlir::python::nanobind_adaptors::pure_subclass::def_classmethod(), MlirStringRef::length, mlirAttributeGetContext(), mlirAttributeIsAGPUObjectAttr(), mlirGPUAsyncTokenTypeGet(), mlirGPUObjectAttrGetFormat(), mlirGPUObjectAttrGetKernels(), mlirGPUObjectAttrGetObject(), mlirGPUObjectAttrGetProperties(), mlirGPUObjectAttrGetTarget(), mlirGPUObjectAttrGetWithKernels(), mlirGPUObjectAttrHasKernels(), mlirGPUObjectAttrHasProperties(), mlirStringRefCreate(), mlirTypeIsAGPUAsyncTokenType(), and target.