MLIR: lib/Dialect/Linalg/Transforms/Transforms.cpp File Reference
Transforms.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Functions
static LogicalResult padOperandToSmallestStaticBoundingBox (PatternRewriter &rewriter, linalg::LinalgOp opToPad, OpOperand *opOperand, const LinalgTilingOptions &options, Value &result)
Try to compute a static bounding box for operand Return success if either:
static LogicalResult rewriteAsPaddedOp (PatternRewriter &rewriter, TiledLinalgOp &res, const LinalgTilingOptions &options)
static ValueRange getTiledOpResult (TiledLinalgOp tiledOp)
static ValueRange getTiledAndFusedOpResult (TiledAndFusedLinalgOps tiledAndFusedOp)
static AffineMap substitute (AffineMap map, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols, GetMinMaxExprFn getMinMaxExpr)
Traverse the dims and substitute known min or max expressions returned by the lambda |getMinMaxExpr|.
static SmallVector< StringRef > getNParallelLoopsAttrs (unsigned nParallelLoops)
static Value asValue (OpBuilder &builder, Location loc, OpFoldResult ofr)
Given an OpFoldResult, return a Value.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 38 of file Transforms.cpp.
Referenced by mlir::linalg::applyStagedPatterns(), mlir::linalg::AffineMinRangeCanonicalizationPattern::matchAndRewrite(), and substitute().
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 33 of file Transforms.cpp.
Function Documentation
asValue()
static Value asValue (OpBuilder & builder, Location loc, OpFoldResult ofr) static
Given an OpFoldResult, return a Value.
If the OpFoldResult is an Attribute, it must be of type Integer.
Definition at line 794 of file Transforms.cpp.
References mlir::OpBuilder::create(), mlir::getConstantIntValue(), and loc.
Referenced by mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite().
getNParallelLoopsAttrs()
static SmallVector<StringRef> getNParallelLoopsAttrs (unsigned nParallelLoops) static
Definition at line 638 of file Transforms.cpp.
References mlir::getParallelIteratorTypeName().
Referenced by mlir::linalg::PadTensorOpTransformationPattern::matchAndRewrite().
getTiledAndFusedOpResult()
static ValueRange getTiledAndFusedOpResult (TiledAndFusedLinalgOps tiledAndFusedOp) static
Definition at line 286 of file Transforms.cpp.
References mlir::linalg::TiledAndFusedLinalgOps::fusedLoops, and mlir::linalg::TiledAndFusedLinalgOps::op.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
getTiledOpResult()
static ValueRange getTiledOpResult (TiledLinalgOp tiledOp) static
Definition at line 279 of file Transforms.cpp.
References mlir::linalg::TiledLinalgOp::loops, and mlir::linalg::TiledLinalgOp::op.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
padOperandToSmallestStaticBoundingBox()
static LogicalResult padOperandToSmallestStaticBoundingBox (PatternRewriter & rewriter, linalg::LinalgOp opToPad, OpOperand * opOperand, const LinalgTilingOptions & options, Value & result) static
Try to compute a static bounding box for operand Return success if either:
The operand is already statically shaped, result is left unchanged.
The operand is (partially) dynamic, result is the result of a freshly created PadTensorOp. Return failure if the operand cannot be padded to a static shape.
Definition at line 127 of file Transforms.cpp.
References mlir::Attribute::dyn_cast(), mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::getElementTypeOrSelf(), mlir::Value::getLoc(), mlir::linalg::getSmallestBoundingIndex(), mlir::ShapedType::isDynamic(), mlir::RewriterBase::notifyMatchFailure(), mlir::linalg::LinalgTilingOptions::paddingValueComputationFunction, rewriter, and mlir::success().
Referenced by rewriteAsPaddedOp().
rewriteAsPaddedOp()
static LogicalResult rewriteAsPaddedOp (PatternRewriter & rewriter, TiledLinalgOp & res, const LinalgTilingOptions & options) static
Definition at line 162 of file Transforms.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Builder::getIndexAttr(), mlir::detail::IROperandBase::getOwner(), loc, mlir::linalg::TiledLinalgOp::loops, mlir::linalg::TiledLinalgOp::op, padOperandToSmallestStaticBoundingBox(), mlir::RewriterBase::replaceOpWithIf(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and mlir::linalg::TiledLinalgOp::tensorResults.
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase().
substitute()
static AffineMap substitute (AffineMap map, SmallVectorImpl< Value > & dims, SmallVectorImpl< Value > & symbols, GetMinMaxExprFn getMinMaxExpr) static
Traverse the dims and substitute known min or max expressions returned by the lambda |getMinMaxExpr|.
Definition at line 501 of file Transforms.cpp.
References mlir::canonicalizeMapAndOperands(), DBGS, mlir::fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getResults(), mlir::simplifyAffineMap(), and mlir::substWithMin().
Referenced by mlir::linalg::substituteMin().