MLIR: lib/Bindings/Python/DialectLinalg.cpp File Reference
DialectLinalg.cpp File Reference
#include "mlir-c/Dialect/Linalg.h"
#include "mlir-c/IR.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
static std::optional< MlirLinalgContractionDimensions > InferContractionDimensions (MlirOperation op)
static std::optional< MlirLinalgConvolutionDimensions > InferConvolutionDimensions (MlirOperation op)
static void populateDialectLinalgSubmodule (nb::module_ m)
NB_MODULE (_mlirDialectsLinalg, m)
Function Documentation
InferContractionDimensions()
std::optional< MlirLinalgContractionDimensions > InferContractionDimensions (MlirOperation op) static
Definition at line 18 of file DialectLinalg.cpp.
References MlirLinalgContractionDimensions::batch, MlirLinalgContractionDimensions::k, MlirLinalgContractionDimensions::m, mlirLinalgInferContractionDimensions(), and MlirLinalgContractionDimensions::n.
Referenced by populateDialectLinalgSubmodule().
InferConvolutionDimensions()
std::optional< MlirLinalgConvolutionDimensions > InferConvolutionDimensions (MlirOperation op) static
Definition at line 32 of file DialectLinalg.cpp.
References MlirLinalgConvolutionDimensions::batch, MlirLinalgConvolutionDimensions::depth, MlirLinalgConvolutionDimensions::dilations, MlirLinalgConvolutionDimensions::filterLoop, MlirLinalgConvolutionDimensions::inputChannel, mlirLinalgInferConvolutionDimensions(), MlirLinalgConvolutionDimensions::outputChannel, MlirLinalgConvolutionDimensions::outputImage, and MlirLinalgConvolutionDimensions::strides.
Referenced by populateDialectLinalgSubmodule().
NB_MODULE()
NB_MODULE (_mlirDialectsLinalg , m)
Definition at line 157 of file DialectLinalg.cpp.
References populateDialectLinalgSubmodule().
populateDialectLinalgSubmodule()
void populateDialectLinalgSubmodule (nb::module_ m) static
Definition at line 51 of file DialectLinalg.cpp.
References MlirLinalgContractionDimensions::batch, InferContractionDimensions(), InferConvolutionDimensions(), MlirLinalgContractionDimensions::k, MlirLinalgContractionDimensions::m, mlirLinalgFillBuiltinNamedOpRegion(), mlirLinalgGetIndexingMapsAttribute(), mlirLinalgInferContractionDimensionsFromMaps(), mlirLinalgIsAContractionOp(), mlirLinalgIsAConvolutionOp(), and MlirLinalgContractionDimensions::n.
Referenced by NB_MODULE().