MLIR: lib/Bindings/Python/DialectSMT.cpp File Reference
DialectSMT.cpp File Reference
#include "NanobindUtils.h"
#include "mlir-c/Dialect/SMT.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir-c/Target/ExportSMTLIB.h"
#include "mlir/Bindings/Python/Diagnostics.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
void populateDialectSMTSubmodule (nanobind::module_ &m)
NB_MODULE (_mlirDialectsSMT, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlirDialectsSMT , m)
Definition at line 79 of file DialectSMT.cpp.
References populateDialectSMTSubmodule().
populateDialectSMTSubmodule()
void populateDialectSMTSubmodule (nanobind::module_ & m)
Definition at line 27 of file DialectSMT.cpp.
References mlir::python::nanobind_adaptors::pure_subclass::def_classmethod(), mlir::smt::exportSMTLIB(), mlir::PyPrintAccumulator::getCallback(), mlir::PyPrintAccumulator::getUserData(), mlir::PyPrintAccumulator::join(), mlirLogicalResultIsSuccess(), mlirModuleGetOperation(), mlirOperationGetContext(), mlirSMTTypeGetBitVector(), mlirSMTTypeGetBool(), mlirSMTTypeIsABitVector(), mlirSMTTypeIsABool(), mlirTranslateOperationToSMTLIB(), and mlir::python::CollectDiagnosticsToStringScope::takeMessage().
Referenced by NB_MODULE().