MLIR: lib/Bindings/Python/DialectPDL.cpp File Reference
DialectPDL.cpp File Reference
#include "mlir-c/Dialect/PDL.h"
#include "mlir-c/IR.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
static void populateDialectPDLSubmodule (const nanobind::module_ &m)
NB_MODULE (_mlirDialectsPDL, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlirDialectsPDL , m)
Definition at line 102 of file DialectPDL.cpp.
References populateDialectPDLSubmodule().
populateDialectPDLSubmodule()
void populateDialectPDLSubmodule (const nanobind::module_ & m) static
Definition at line 20 of file DialectPDL.cpp.
References MAKE_MLIR_PYTHON_QUALNAME, mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirTypeIsAPDLAttributeType(), mlirTypeIsAPDLOperationType(), mlirTypeIsAPDLRangeType(), mlirTypeIsAPDLType(), mlirTypeIsAPDLTypeType(), and mlirTypeIsAPDLValueType().
Referenced by NB_MODULE().