MLIR: lib/Dialect/Linalg/Transforms/Bufferize.cpp File Reference
Bufferize.cpp File Reference
#include "mlir/Transforms/Bufferize.h"
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/StandardOps/Transforms/Passes.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
Functions
static Value cloneMemref (Location loc, Value memref, OpBuilder &b)
static LogicalResult allocateBuffersForResults (Location loc, LinalgOp linalgOp, ValueRange outputs, SmallVectorImpl< Value > &resultBuffers, OpBuilder &b)
static void finalizeBufferAllocationForGenericOp (ConversionPatternRewriter &rewriter, GenericOp genericOp, ValueRange inputs, ValueRange outputs)
Specialization for linalg::GenericOp.
static void finalizeBufferAllocation (ConversionPatternRewriter &rewriter, linalg::LinalgOp linalgOp, ValueRange inputs, ValueRange outputs)
Specialization for all other linalg::LinalgOp.
Function Documentation
allocateBuffersForResults()
static LogicalResult allocateBuffersForResults (Location loc, LinalgOp linalgOp, ValueRange outputs, SmallVectorImpl< Value > & resultBuffers, OpBuilder & b) static
Definition at line 36 of file Bufferize.cpp.
References cloneMemref(), mlir::detail::enumerate(), mlir::failure(), mlir::linalg::getDynOperands(), resultIndex(), and mlir::success().
Referenced by finalizeBufferAllocation().
cloneMemref()
static Value cloneMemref (Location loc, Value memref, OpBuilder & b) static
Definition at line 27 of file Bufferize.cpp.
References mlir::linalg::getDynOperands(), and loc.
Referenced by allocateBuffersForResults(), and finalizeBufferAllocation().
finalizeBufferAllocation()
static void finalizeBufferAllocation (ConversionPatternRewriter & rewriter, linalg::LinalgOp linalgOp, ValueRange inputs, ValueRange outputs) static
Specialization for all other linalg::LinalgOp.
Definition at line 116 of file Bufferize.cpp.
References allocateBuffersForResults(), mlir::applyPartialConversion(), cloneMemref(), mlir::failed(), mlir::failure(), finalizeBufferAllocationForGenericOp(), loc, op, mlir::linalg::populateLinalgBufferizePatterns(), rewriter, mlir::success(), and value.
finalizeBufferAllocationForGenericOp()
static void finalizeBufferAllocationForGenericOp (ConversionPatternRewriter & rewriter, GenericOp genericOp, ValueRange inputs, ValueRange outputs) static
Specialization for linalg::GenericOp.
A pattern to convert Generic Linalg operations which work on tensors to use buffers. BufferPlacement pass should be later used to move Alloc operations to the correct positions and insert the missing Dealloc operations in the correct places.
Definition at line 82 of file Bufferize.cpp.
References op.
Referenced by finalizeBufferAllocation().