MLIR: lib/Dialect/Arith/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "llvm/ADT/SmallBitVector.h"
#include <numeric>
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::arith
Functions
static Value convertScalarToIntDtype (ImplicitLocOpBuilder &b, Value operand, IntegerType toType, bool isUnsigned)
static Value convertScalarToFpDtype (ImplicitLocOpBuilder &b, Value operand, FloatType toType, bool isUnsigned)
static Value convertScalarToComplexDtype (ImplicitLocOpBuilder &b, Value operand, ComplexType targetType, bool isUnsigned)
Value mlir::arith::createProduct (OpBuilder &builder, Location loc, ArrayRef< Value > values)
Value mlir::arith::createProduct (OpBuilder &builder, Location loc, ArrayRef< Value > values, Type resultType)
std::optional< FloatType > mlir::arith::parseFloatType (MLIRContext *ctx, StringRef name)
Map strings to float types.
Function Documentation
convertScalarToComplexDtype()
Value convertScalarToComplexDtype (ImplicitLocOpBuilder & b, Value operand, ComplexType targetType, bool isUnsigned) static
Definition at line 186 of file Utils.cpp.
References b, mlir::arith::ConstantFloatOp::create(), mlir::Type::getIntOrFloatBitWidth(), and mlir::Value::getType().
Referenced by mlir::convertScalarToDtype().
convertScalarToFpDtype()
Value convertScalarToFpDtype (ImplicitLocOpBuilder & b, Value operand, FloatType toType, bool isUnsigned) static
Definition at line 166 of file Utils.cpp.
References b, and mlir::Value::getType().
Referenced by mlir::convertScalarToDtype().
convertScalarToIntDtype()
Value convertScalarToIntDtype (ImplicitLocOpBuilder & b, Value operand, IntegerType toType, bool isUnsigned) static
Definition at line 140 of file Utils.cpp.
References b, mlir::Value::getType(), and mlir::Type::isIndex().
Referenced by mlir::convertScalarToDtype().