MLIR: lib/Bindings/Python/DialectSparseTensor.cpp File Reference
DialectSparseTensor.cpp File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/Dialect/SparseTensor.h"
#include "mlir-c/IR.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
#include <optional>
#include <pybind11/cast.h>
#include <pybind11/detail/common.h>
#include <pybind11/pybind11.h>
#include <pybind11/pytypes.h>
#include <vector>
Functions
static void populateDialectSparseTensorSubmodule (const py::module &m)
PYBIND11_MODULE (_mlirDialectsSparseTensor, m)
Function Documentation
populateDialectSparseTensorSubmodule()
static void populateDialectSparseTensorSubmodule (const py::module & m) static
Definition at line 25 of file DialectSparseTensor.cpp.
References mlir::python::adaptors::pure_subclass::def_classmethod(), mlir::python::adaptors::pure_subclass::def_property_readonly(), MLIR_SPARSE_PROPERTY_NON_ORDERED, MLIR_SPARSE_PROPERTY_NON_UNIQUE, MLIR_SPARSE_TENSOR_LEVEL_COMPRESSED, MLIR_SPARSE_TENSOR_LEVEL_DENSE, MLIR_SPARSE_TENSOR_LEVEL_LOOSE_COMPRESSED, MLIR_SPARSE_TENSOR_LEVEL_N_OUT_OF_M, MLIR_SPARSE_TENSOR_LEVEL_SINGLETON, mlirAffineMapIsNull(), mlirAttributeIsASparseTensorEncodingAttr(), mlirAttributeIsNull(), mlirSparseTensorEncodingAttrBuildLvlType(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetCrdWidth(), mlirSparseTensorEncodingAttrGetDimToLvl(), mlirSparseTensorEncodingAttrGetExplicitVal(), mlirSparseTensorEncodingAttrGetImplicitVal(), mlirSparseTensorEncodingAttrGetLvlFmt(), mlirSparseTensorEncodingAttrGetLvlToDim(), mlirSparseTensorEncodingAttrGetLvlType(), mlirSparseTensorEncodingAttrGetPosWidth(), mlirSparseTensorEncodingAttrGetStructuredM(), mlirSparseTensorEncodingAttrGetStructuredN(), and mlirSparseTensorEncodingGetLvlRank().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (_mlirDialectsSparseTensor , m)
Definition at line 145 of file DialectSparseTensor.cpp.
References populateDialectSparseTensorSubmodule().