MLIR: lib/Bindings/Python/DialectLLVM.cpp File Reference
DialectLLVM.cpp File Reference
#include <string>
#include "mlir-c/Dialect/LLVM.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir-c/Target/LLVMIR.h"
#include "mlir/Bindings/Python/Diagnostics.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
static void populateDialectLLVMSubmodule (nanobind::module_ &m)
NB_MODULE (_mlirDialectsLLVM, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlirDialectsLLVM , m)
Definition at line 171 of file DialectLLVM.cpp.
References populateDialectLLVMSubmodule().
populateDialectLLVMSubmodule()
void populateDialectLLVMSubmodule (nanobind::module_ & m) static
Definition at line 28 of file DialectLLVM.cpp.
References MlirStringRef::data, mlir::python::nanobind_adaptors::pure_subclass::def(), mlir::python::nanobind_adaptors::pure_subclass::def_classmethod(), MlirStringRef::length, MAKE_MLIR_PYTHON_QUALNAME, mlirLLVMPointerTypeGet(), mlirLLVMPointerTypeGetAddressSpace(), mlirLLVMPointerTypeGetTypeID(), mlirLLVMStructTypeGetElementType(), mlirLLVMStructTypeGetIdentifier(), mlirLLVMStructTypeGetNumElementTypes(), mlirLLVMStructTypeGetTypeID(), mlirLLVMStructTypeIdentifiedGet(), mlirLLVMStructTypeIdentifiedNewGet(), mlirLLVMStructTypeIsLiteral(), mlirLLVMStructTypeIsOpaque(), mlirLLVMStructTypeIsPacked(), mlirLLVMStructTypeLiteralGet(), mlirLLVMStructTypeLiteralGetChecked(), mlirLLVMStructTypeOpaqueGet(), mlirLLVMStructTypeSetBody(), mlirLocationGetContext(), mlirLogicalResultIsSuccess(), mlirStringRefCreate(), mlirTranslateModuleToLLVMIRToString(), mlirTypeIsALLVMPointerType(), mlirTypeIsALLVMStructType(), mlirTypeIsNull(), result, and mlir::python::CollectDiagnosticsToStringScope::takeMessage().
Referenced by NB_MODULE().