MLIR: lib/Bindings/Python/DialectTransform.cpp File Reference
DialectTransform.cpp File Reference
#include <string>
#include "mlir-c/Dialect/Transform.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
static void populateDialectTransformSubmodule (const nb::module_ &m)
NB_MODULE (_mlirDialectsTransform, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlirDialectsTransform , m)
Definition at line 119 of file DialectTransform.cpp.
References populateDialectTransformSubmodule().
populateDialectTransformSubmodule()
void populateDialectTransformSubmodule (const nb::module_ & m) static
Definition at line 22 of file DialectTransform.cpp.
References MlirStringRef::data, MlirStringRef::length, mlirStringRefCreate(), mlirTransformAnyOpTypeGet(), mlirTransformAnyOpTypeGetTypeID(), mlirTransformAnyParamTypeGet(), mlirTransformAnyParamTypeGetTypeID(), mlirTransformAnyValueTypeGet(), mlirTransformAnyValueTypeGetTypeID(), mlirTransformOperationTypeGet(), mlirTransformOperationTypeGetOperationName(), mlirTransformOperationTypeGetTypeID(), mlirTransformParamTypeGet(), mlirTransformParamTypeGetType(), mlirTransformParamTypeGetTypeID(), mlirTypeIsATransformAnyOpType(), mlirTypeIsATransformAnyParamType(), mlirTypeIsATransformAnyValueType(), mlirTypeIsATransformOperationType(), and mlirTypeIsATransformParamType().
Referenced by NB_MODULE().