MLIR: lib/Dialect/Async/IR/Async.cpp File Reference
Async.cpp File Reference
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/Async/IR/AsyncOpsDialect.cpp.inc"
#include "mlir/Dialect/Async/IR/AsyncOps.cpp.inc"
#include "mlir/Dialect/Async/IR/AsyncOpsTypes.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_TYPEDEF_LIST
#define GET_OP_CLASSES
#define GET_TYPEDEF_CLASSES
Functions
static LogicalResult verify (YieldOp op)
static void print (OpAsmPrinter &p, ExecuteOp op)
static ParseResult parseExecuteOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ExecuteOp op)
static ParseResult parseAwaitResultType (OpAsmParser &parser, Type &operandType, Type &resultType)
static void printAwaitResultType (OpAsmPrinter &p, Operation *op, Type operandType, Type resultType)
static LogicalResult verify (AwaitOp op)
Variables
constexpr char kOperandSegmentSizesAttr [] = "operand_segment_sizes"
ExecuteOp.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 333 of file Async.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 340 of file Async.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
parseAwaitResultType()
static ParseResult parseAwaitResultType (OpAsmParser & parser, Type & operandType, Type & resultType) static
Definition at line 294 of file Async.cpp.
References mlir::Type::dyn_cast(), mlir::failure(), mlir::OpAsmParser::parseType(), and mlir::success().
parseExecuteOp()
static ParseResult parseExecuteOp (OpAsmParser & parser, OperationState & result) static
Definition at line 146 of file Async.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addRegion(), mlir::OpAsmParser::addTypesToList(), mlir::OpAsmParser::addTypeToList(), mlir::failed(), mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::OperationState::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI32Type(), kOperandSegmentSizesAttr, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseOptionalLSquare(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
print()
static void print (OpAsmPrinter & p, ExecuteOp op) static
Definition at line 121 of file Async.cpp.
References mlir::Block::empty(), mlir::Block::getArgument(), mlir::Value::getType(), kOperandSegmentSizesAttr, mlir::OpAsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), and mlir::OpAsmPrinter::printRegion().
printAwaitResultType()
static void printAwaitResultType (OpAsmPrinter & p, Operation * op, Type operandType, Type resultType) static
Definition at line 306 of file Async.cpp.
verify() [1/3]
static LogicalResult verify (YieldOp op) static
Definition at line 34 of file Async.cpp.
References mlir::success().
verify() [2/3]
static LogicalResult verify (ExecuteOp op) static
Definition at line 236 of file Async.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Value::getType(), mlir::Operation::getUsers(), op, rewriter, and mlir::success().
verify() [3/3]
static LogicalResult verify (AwaitOp op) static
Definition at line 311 of file Async.cpp.
References mlir::Type::dyn_cast(), mlir::Type::isa(), mlir::success(), and value.
Variable Documentation
kOperandSegmentSizesAttr
constexpr char kOperandSegmentSizesAttr[] = "operand_segment_sizes"
ExecuteOp.
Definition at line 53 of file Async.cpp.
Referenced by parseExecuteOp(), and print().