MLIR: lib/Dialect/SparseTensor/IR/Detail/DimLvlMapParser.cpp File Reference
DimLvlMapParser.cpp File Reference
#include "DimLvlMapParser.h"
Macros
#define FAILURE_IF_FAILED(RES)
#define FAILURE_IF_NULLOPT_OR_FAILED(RES)
#define ERROR_IF(COND, MSG)
Functions
static bool didntSucceed (OptionalParseResult res)
Helper function for FAILURE_IF_NULLOPT_OR_FAILED to avoid duplicating its RES parameter.
static Twine nth (Var::Num n)
Macro Definition Documentation
ERROR_IF
#define ERROR_IF (COND, MSG)
Value:
  if (COND) {                                                                  \
    return parser.emitError(loc, MSG);                                         \
  }
Definition at line 32 of file DimLvlMapParser.cpp.
Referenced by mlir::sparse_tensor::ir_detail::LvlTypeParser::parseLvlType().
FAILURE_IF_FAILED
#define FAILURE_IF_FAILED (RES)
Value:
  if (failed(RES)) {                                                           \
    return failure();                                                          \
  }
Definition at line 15 of file DimLvlMapParser.cpp.
Referenced by mlir::sparse_tensor::ir_detail::DimLvlMapParser::parseDimLvlMap(), and mlir::sparse_tensor::ir_detail::LvlTypeParser::parseLvlType().
FAILURE_IF_NULLOPT_OR_FAILED
#define FAILURE_IF_NULLOPT_OR_FAILED (RES)
Value:
  if (didntSucceed(RES)) {                                                     \
    return failure();                                                          \
  }
Definition at line 26 of file DimLvlMapParser.cpp.
Function Documentation
didntSucceed()
bool didntSucceed (OptionalParseResult res) inline static
Helper function for FAILURE_IF_NULLOPT_OR_FAILED to avoid duplicating its RES parameter.
Definition at line 22 of file DimLvlMapParser.cpp.
References mlir::OptionalParseResult::has_value().
nth()
Twine nth (Var::Num n) inline static
Definition at line 248 of file DimLvlMapParser.cpp.
References nth().
Referenced by nth().