MLIR: lib/Dialect/LLVMIR/Transforms/DIScopeForLLVMFuncOp.cpp File Reference
DIScopeForLLVMFuncOp.cpp File Reference
#include "mlir/Dialect/LLVMIR/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/Support/Path.h"
#include "mlir/Dialect/LLVMIR/Transforms/Passes.h.inc"
Classes
struct mlir::LLVM::DIScopeForLLVMFuncOpPassOptions
class mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >
struct mlir::LLVM::LLVMUseDefaultVisibilityPassOptions
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::LLVM
namespace mlir::LLVM::impl
Macros
#define GEN_PASS_DEF_DISCOPEFORLLVMFUNCOPPASS
#define GEN_PASS_DECL_DISCOPEFORLLVMFUNCOPPASS
#define GEN_PASS_DECL_LLVMADDCOMDATS
#define GEN_PASS_DECL_LLVMLEGALIZEFOREXPORTPASS
#define GEN_PASS_DECL_LLVMREQUESTCWRAPPERSPASS
#define GEN_PASS_DECL_LLVMUSEDEFAULTVISIBILITYPASS
#define GEN_PASS_DECL_NVVMOPTIMIZEFORTARGETPASS
#define GEN_PASS_REGISTRATION_DISCOPEFORLLVMFUNCOPPASS
#define GEN_PASS_REGISTRATION_LLVMADDCOMDATS
#define GEN_PASS_REGISTRATION_LLVMLEGALIZEFOREXPORTPASS
#define GEN_PASS_REGISTRATION_LLVMREQUESTCWRAPPERSPASS
#define GEN_PASS_REGISTRATION_LLVMUSEDEFAULTVISIBILITYPASS
#define GEN_PASS_REGISTRATION_NVVMOPTIMIZEFORTARGETPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::LLVM::createDIScopeForLLVMFuncOpPass ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createDIScopeForLLVMFuncOpPass (DIScopeForLLVMFuncOpPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::LLVM::impl::createDIScopeForLLVMFuncOpPass ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::impl::createDIScopeForLLVMFuncOpPass (DIScopeForLLVMFuncOpPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMAddComdats ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMLegalizeForExportPass ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMRequestCWrappersPass ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMUseDefaultVisibilityPass ()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMUseDefaultVisibilityPass (LLVMUseDefaultVisibilityPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::LLVM::createNVVMOptimizeForTargetPass ()
void mlir::LLVM::registerDIScopeForLLVMFuncOpPass ()
void mlir::LLVM::registerDIScopeForLLVMFuncOpPassPass ()
void mlir::LLVM::registerLLVMAddComdats ()
void mlir::LLVM::registerLLVMAddComdatsPass ()
void mlir::LLVM::registerLLVMLegalizeForExportPass ()
void mlir::LLVM::registerLLVMLegalizeForExportPassPass ()
void mlir::LLVM::registerLLVMRequestCWrappersPass ()
void mlir::LLVM::registerLLVMRequestCWrappersPassPass ()
void mlir::LLVM::registerLLVMUseDefaultVisibilityPass ()
void mlir::LLVM::registerLLVMUseDefaultVisibilityPassPass ()
void mlir::LLVM::registerNVVMOptimizeForTargetPass ()
void mlir::LLVM::registerNVVMOptimizeForTargetPassPass ()
void mlir::LLVM::registerLLVMPasses ()
static FileLineColLoc extractFileLoc (Location loc)
Attempt to extract a filename for the given loc.
static void addScopeToFunction (LLVM::LLVMFuncOp llvmFunc, LLVM::DICompileUnitAttr compileUnitAttr)
Creates a DISubprogramAttr with the provided compile unit and attaches it to the function.
static Location getNestedLoc (Operation *op, LLVM::DIScopeAttr scopeAttr, Location calleeLoc)
static void setLexicalBlockFileAttr (Operation *op)
Adds DILexicalBlockFileAttr for operations with CallSiteLoc and operations from different files than their containing function.
Macro Definition Documentation
GEN_PASS_DECL_DISCOPEFORLLVMFUNCOPPASS
#define GEN_PASS_DECL_DISCOPEFORLLVMFUNCOPPASS
GEN_PASS_DECL_LLVMADDCOMDATS
#define GEN_PASS_DECL_LLVMADDCOMDATS
GEN_PASS_DECL_LLVMLEGALIZEFOREXPORTPASS
#define GEN_PASS_DECL_LLVMLEGALIZEFOREXPORTPASS
GEN_PASS_DECL_LLVMREQUESTCWRAPPERSPASS
#define GEN_PASS_DECL_LLVMREQUESTCWRAPPERSPASS
GEN_PASS_DECL_LLVMUSEDEFAULTVISIBILITYPASS
#define GEN_PASS_DECL_LLVMUSEDEFAULTVISIBILITYPASS
GEN_PASS_DECL_NVVMOPTIMIZEFORTARGETPASS
#define GEN_PASS_DECL_NVVMOPTIMIZEFORTARGETPASS
GEN_PASS_DEF_DISCOPEFORLLVMFUNCOPPASS
#define GEN_PASS_DEF_DISCOPEFORLLVMFUNCOPPASS
Definition at line 17 of file DIScopeForLLVMFuncOp.cpp.
GEN_PASS_REGISTRATION_DISCOPEFORLLVMFUNCOPPASS
#define GEN_PASS_REGISTRATION_DISCOPEFORLLVMFUNCOPPASS
GEN_PASS_REGISTRATION_LLVMADDCOMDATS
#define GEN_PASS_REGISTRATION_LLVMADDCOMDATS
GEN_PASS_REGISTRATION_LLVMLEGALIZEFOREXPORTPASS
#define GEN_PASS_REGISTRATION_LLVMLEGALIZEFOREXPORTPASS
GEN_PASS_REGISTRATION_LLVMREQUESTCWRAPPERSPASS
#define GEN_PASS_REGISTRATION_LLVMREQUESTCWRAPPERSPASS
GEN_PASS_REGISTRATION_LLVMUSEDEFAULTVISIBILITYPASS
#define GEN_PASS_REGISTRATION_LLVMUSEDEFAULTVISIBILITYPASS
GEN_PASS_REGISTRATION_NVVMOPTIMIZEFORTARGETPASS
#define GEN_PASS_REGISTRATION_NVVMOPTIMIZEFORTARGETPASS
Function Documentation
addScopeToFunction()
void addScopeToFunction (LLVM::LLVMFuncOp llvmFunc, LLVM::DICompileUnitAttr compileUnitAttr) static
Creates a DISubprogramAttr with the provided compile unit and attaches it to the function.
Does nothing when the function already has an attached subprogram.
Definition at line 46 of file DIScopeForLLVMFuncOp.cpp.
extractFileLoc()
FileLineColLoc extractFileLoc (Location loc) static
Attempt to extract a filename for the given loc.
Definition at line 25 of file DIScopeForLLVMFuncOp.cpp.
References extractFileLoc().
Referenced by mlir::LLVM::impl::DIScopeForLLVMFuncOpPassBase< DerivedT >::createDIScopeForLLVMFuncOpPass, extractFileLoc(), and setLexicalBlockFileAttr().
getNestedLoc()
Location getNestedLoc (Operation * op, LLVM::DIScopeAttr scopeAttr, Location calleeLoc) static
Definition at line 94 of file DIScopeForLLVMFuncOp.cpp.
Referenced by mlir::LLVM::createDIScopeForLLVMFuncOpPass(), and setLexicalBlockFileAttr().
setLexicalBlockFileAttr()
void setLexicalBlockFileAttr (Operation * op) static
Adds DILexicalBlockFileAttr for operations with CallSiteLoc and operations from different files than their containing function.
Definition at line 114 of file DIScopeForLLVMFuncOp.cpp.
References extractFileLoc(), mlir::Operation::getContext(), mlir::FileLineColLoc::getFilename(), mlir::Operation::getLoc(), getNestedLoc(), mlir::Operation::getParentOfType(), and mlir::Operation::setLoc().