MLIR: lib/Dialect/Linalg/Transforms/EliminateEmptyTensors.cpp File Reference
EliminateEmptyTensors.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
Functions
static OpOperand * getUnusedOutOperand (LinalgOp op, OpOperand *in)
Get an output operand that matches the given input operand and can be used to eliminate a tensor.empty op.
Function Documentation
getUnusedOutOperand()
OpOperand * getUnusedOutOperand (LinalgOp op, OpOperand * in) static
Get an output operand that matches the given input operand and can be used to eliminate a tensor.empty op.
Definition at line 23 of file EliminateEmptyTensors.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), and mlir::Value::getType().
Referenced by mlir::linalg::linalgOpAnchoredEmptyTensorEliminationStep().