MLIR: lib/Dialect/EmitC/IR/EmitC.cpp File Reference
EmitC.cpp File Reference
#include "mlir/Dialect/EmitC/IR/EmitC.h"
#include "mlir/Dialect/EmitC/IR/EmitCTraits.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Types.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Casting.h"
#include "mlir/Dialect/EmitC/IR/EmitCDialect.cpp.inc"
#include "mlir/Dialect/EmitC/IR/EmitC.cpp.inc"
#include "mlir/Dialect/EmitC/IR/EmitCTypes.cpp.inc"
#include "mlir/Dialect/EmitC/IR/EmitCAttributes.cpp.inc"
#include "mlir/Dialect/EmitC/IR/EmitCEnums.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_TYPEDEF_LIST
#define GET_ATTRDEF_LIST
#define GET_ATTRDEF_CLASSES
#define GET_TYPEDEF_CLASSES
#define GET_OP_CLASSES
Functions
static LogicalResult verifyInitializationAttribute (Operation *op, Attribute value)
Check that the type of the initial value is compatible with the operations result type.
static void printEmitCGlobalOpTypeAndInitialValue (OpAsmPrinter &p, GlobalOp op, TypeAttr type, Attribute initialValue)
static Type getInitializerTypeForGlobal (Type type)
static ParseResult parseEmitCGlobalOpTypeAndInitialValue (OpAsmParser &parser, TypeAttr &typeAttr, Attribute &initialValue)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 905 of file EmitC.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1103 of file EmitC.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 912 of file EmitC.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
getInitializerTypeForGlobal()
static Type getInitializerTypeForGlobal (Type type) static
Definition at line 1008 of file EmitC.cpp.
References mlir::get().
Referenced by parseEmitCGlobalOpTypeAndInitialValue().
parseEmitCGlobalOpTypeAndInitialValue()
static ParseResult parseEmitCGlobalOpTypeAndInitialValue (OpAsmParser & parser, TypeAttr & typeAttr, Attribute & initialValue) static
Definition at line 1015 of file EmitC.cpp.
References mlir::AsmParser::emitError(), mlir::get(), getInitializerTypeForGlobal(), mlir::AsmParser::getNameLoc(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseOptionalEqual(), and mlir::AsmParser::parseType().
printEmitCGlobalOpTypeAndInitialValue()
static void printEmitCGlobalOpTypeAndInitialValue (OpAsmPrinter & p, GlobalOp op, TypeAttr type, Attribute initialValue) static
Definition at line 998 of file EmitC.cpp.
verifyInitializationAttribute()
static LogicalResult verifyInitializationAttribute (Operation * op, Attribute value) static
Check that the type of the initial value is compatible with the operations result type.
Definition at line 136 of file EmitC.cpp.