MLIR: lib/Dialect/Bufferization/Transforms/EmptyTensorElimination.cpp File Reference
EmptyTensorElimination.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotModuleBufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/Transforms.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Interfaces/SubsetOpInterface.h"
#include "mlir/Transforms/RegionUtils.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Classes
class mlir::bufferization::impl::EmptyTensorEliminationPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::bufferization
namespace mlir::bufferization::impl
Macros
#define GEN_PASS_DEF_EMPTYTENSORELIMINATIONPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::bufferization::impl::createEmptyTensorEliminationPass ()
std::unique_ptr<::mlir::Pass > mlir::bufferization::createEmptyTensorEliminationPass ()
static bool neededValuesDominateInsertionPoint (const DominanceInfo &domInfo, Operation *insertionPoint, const SmallVector< Value > &neededValues)
Return true if all neededValues are in scope at the given insertionPoint.
static Operation * findValidInsertionPoint (Operation *emptyTensorOp, Operation *user, const SmallVector< Value > &neededValues)
Find a valid insertion point for a replacement of emptyTensorOp's use of user operation, assuming that the replacement may use any value from neededValues.
Macro Definition Documentation
GEN_PASS_DEF_EMPTYTENSORELIMINATIONPASS
#define GEN_PASS_DEF_EMPTYTENSORELIMINATIONPASS
Definition at line 23 of file EmptyTensorElimination.cpp.
Function Documentation
findValidInsertionPoint()
Operation * findValidInsertionPoint (Operation * emptyTensorOp, Operation * user, const SmallVector< Value > & neededValues) static
Find a valid insertion point for a replacement of emptyTensorOp's use of user operation, assuming that the replacement may use any value from neededValues.
Definition at line 55 of file EmptyTensorElimination.cpp.
References mlir::DominanceInfo::dominates(), and neededValuesDominateInsertionPoint().
Referenced by mlir::bufferization::buildSubsetExtraction().
neededValuesDominateInsertionPoint()
bool neededValuesDominateInsertionPoint (const DominanceInfo & domInfo, Operation * insertionPoint, const SmallVector< Value > & neededValues) static
Return true if all neededValues are in scope at the given insertionPoint.
Definition at line 34 of file EmptyTensorElimination.cpp.
References mlir::Block::findAncestorOpInBlock(), and mlir::DominanceInfo::properlyDominates().
Referenced by findValidInsertionPoint().