MLIR: lib/Dialect/AMDGPU/Transforms/EmulateAtomics.cpp File Reference
EmulateAtomics.cpp File Reference
#include "mlir/Dialect/AMDGPU/Transforms/Passes.h"
#include "mlir/Dialect/AMDGPU/IR/AMDGPUDialect.h"
#include "mlir/Dialect/AMDGPU/Utils/Chipset.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Dialect/AMDGPU/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::amdgpu
Macros
#define GEN_PASS_DEF_AMDGPUEMULATEATOMICSPASS
Functions
static void patchOperandSegmentSizes (ArrayRef< NamedAttribute > attrs, SmallVectorImpl< NamedAttribute > &newAttrs, DataArgAction action)
static Value flattenVecToBits (ConversionPatternRewriter &rewriter, Location loc, Value val)
Macro Definition Documentation
GEN_PASS_DEF_AMDGPUEMULATEATOMICSPASS
#define GEN_PASS_DEF_AMDGPUEMULATEATOMICSPASS
Definition at line 21 of file EmulateAtomics.cpp.
Function Documentation
flattenVecToBits()
static Value flattenVecToBits (ConversionPatternRewriter & rewriter, Location loc, Value val) static
Definition at line 92 of file EmulateAtomics.cpp.
References mlir::get(), mlir::Builder::getIntegerType(), and mlir::Value::getType().
patchOperandSegmentSizes()
static void patchOperandSegmentSizes (ArrayRef< NamedAttribute > attrs, SmallVectorImpl< NamedAttribute > & newAttrs, DataArgAction action) static
Definition at line 60 of file EmulateAtomics.cpp.
References mlir::detail::DenseArrayAttrImpl< int32_t >::get().