MLIR: lib/Dialect/Arith/Transforms/EmulateUnsupportedFloats.cpp File Reference
EmulateUnsupportedFloats.cpp File Reference
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/ErrorHandling.h"
#include <optional>
#include "mlir/Dialect/Arith/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::arith
Macros
#define GEN_PASS_DEF_ARITHEMULATEUNSUPPORTEDFLOATS
Functions
static std::optional< FloatType > parseFloatType (MLIRContext *ctx, StringRef name)
Map strings to float types.
Macro Definition Documentation
GEN_PASS_DEF_ARITHEMULATEUNSUPPORTEDFLOATS
#define GEN_PASS_DEF_ARITHEMULATEUNSUPPORTEDFLOATS
Definition at line 26 of file EmulateUnsupportedFloats.cpp.
Function Documentation
parseFloatType()
static std::optional<FloatType> parseFloatType (MLIRContext * ctx, StringRef name) static
Map strings to float types.
This function is here because no one else needs it yet, feel free to abstract it out.
Definition at line 54 of file EmulateUnsupportedFloats.cpp.
References mlir::Builder::getBF16Type(), mlir::Builder::getF128Type(), mlir::Builder::getF16Type(), mlir::Builder::getF32Type(), mlir::Builder::getF64Type(), mlir::Builder::getF80Type(), mlir::Builder::getFloat8E3M4Type(), mlir::Builder::getFloat8E4M3FNType(), mlir::Builder::getFloat8E4M3FNUZType(), mlir::Builder::getFloat8E4M3Type(), mlir::Builder::getFloat8E5M2FNUZType(), and mlir::Builder::getFloat8E5M2Type().