MLIR: lib/ExecutionEngine/ExecutionEngine.cpp File Reference
ExecutionEngine.cpp File Reference
#include "mlir/ExecutionEngine/ExecutionEngine.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/LLVMIR/Export.h"
#include "llvm/ExecutionEngine/JITEventListener.h"
#include "llvm/ExecutionEngine/ObjectCache.h"
#include "llvm/ExecutionEngine/Orc/CompileUtils.h"
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
#include "llvm/ExecutionEngine/Orc/IRTransformLayer.h"
#include "llvm/ExecutionEngine/Orc/JITTargetMachineBuilder.h"
#include "llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h"
#include "llvm/ExecutionEngine/SectionMemoryManager.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/ToolOutputFile.h"
Macros
#define DEBUG_TYPE "execution-engine"
Functions
static Error make_string_error (const Twine &message)
Wrap a string into an llvm::StringError.
static std::string makePackedFunctionName (StringRef name)
static void packFunctionArguments (Module *module)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "execution-engine"
Definition at line 36 of file ExecutionEngine.cpp.
Function Documentation
make_string_error()
static Error make_string_error (const Twine & message) static
Wrap a string into an llvm::StringError.
Definition at line 61 of file ExecutionEngine.cpp.
References mlir::Error.
Referenced by mlir::ExecutionEngine::create(), and mlir::ExecutionEngine::lookup().
makePackedFunctionName()
static std::string makePackedFunctionName (StringRef name) static
Definition at line 142 of file ExecutionEngine.cpp.
Referenced by mlir::ExecutionEngine::lookup(), and packFunctionArguments().
packFunctionArguments()
static void packFunctionArguments (Module * module) static
Definition at line 149 of file ExecutionEngine.cpp.
References mlir::detail::enumerate(), and makePackedFunctionName().
Referenced by mlir::ExecutionEngine::create().