MLIR: lib/Bindings/Python/ExecutionEngineModule.cpp File Reference
ExecutionEngineModule.cpp File Reference
#include "mlir-c/ExecutionEngine.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Functions
NB_MODULE (_mlirExecutionEngine, m)
Create the mlir.execution_engine module here.
Function Documentation
NB_MODULE()
NB_MODULE (_mlirExecutionEngine , m)
Create the mlir.execution_engine module here.
Definition at line 67 of file ExecutionEngineModule.cpp.
References MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirExecutionEngineCreate(), mlirExecutionEngineDumpToObjectFile(), mlirExecutionEngineInitialize(), mlirExecutionEngineIsNull(), mlirExecutionEngineLookupPacked(), mlirExecutionEngineRegisterSymbol(), and mlirStringRefCreate().