MLIR: lib/Dialect/Math/Transforms/ExpandPatterns.cpp File Reference
ExpandPatterns.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Math/Transforms/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static Value createFloatConst (Location loc, Type type, APFloat value, OpBuilder &b)
Create a float constant.
static Value createFloatConst (Location loc, Type type, double value, OpBuilder &b)
static Value createIntConst (Location loc, Type type, int64_t value, OpBuilder &b)
Create an integer constant.
static Value createTruncatedFPValue (Value operand, ImplicitLocOpBuilder &b)
static LogicalResult convertSinhOp (math::SinhOp op, PatternRewriter &rewriter)
static LogicalResult convertCoshOp (math::CoshOp op, PatternRewriter &rewriter)
static LogicalResult convertTanhOp (math::TanhOp op, PatternRewriter &rewriter)
Expands tanh op into 1-exp^{-2x} / 1+exp^{-2x} To avoid overflow we exploit the reflection symmetry tanh(-x) = -tanh(x).
static LogicalResult convertTanOp (math::TanOp op, PatternRewriter &rewriter)
static LogicalResult convertAsinhOp (math::AsinhOp op, PatternRewriter &rewriter)
static LogicalResult convertAcoshOp (math::AcoshOp op, PatternRewriter &rewriter)
static LogicalResult convertAtanhOp (math::AtanhOp op, PatternRewriter &rewriter)
static LogicalResult convertFmaFOp (math::FmaOp op, PatternRewriter &rewriter)
static LogicalResult convertCeilOp (math::CeilOp op, PatternRewriter &rewriter)
static LogicalResult convertFPowIOp (math::FPowIOp op, PatternRewriter &rewriter)
static LogicalResult convertPowfOp (math::PowFOp op, PatternRewriter &rewriter)
static LogicalResult convertExp2fOp (math::Exp2Op op, PatternRewriter &rewriter)
static LogicalResult convertRoundOp (math::RoundOp op, PatternRewriter &rewriter)
static LogicalResult convertCtlzOp (math::CountLeadingZerosOp op, PatternRewriter &rewriter)
static LogicalResult convertRoundEvenOp (math::RoundEvenOp op, PatternRewriter &rewriter)
static LogicalResult convertRsqrtOp (math::RsqrtOp op, PatternRewriter &rewriter)
Function Documentation
convertAcoshOp()
static LogicalResult convertAcoshOp (math::AcoshOp op, PatternRewriter & rewriter) static
Definition at line 171 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandAcoshPattern().
convertAsinhOp()
static LogicalResult convertAsinhOp (math::AsinhOp op, PatternRewriter & rewriter) static
Definition at line 155 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandAsinhPattern().
convertAtanhOp()
static LogicalResult convertAtanhOp (math::AtanhOp op, PatternRewriter & rewriter) static
Definition at line 187 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandAtanhPattern().
convertCeilOp()
static LogicalResult convertCeilOp (math::CeilOp op, PatternRewriter & rewriter) static
Definition at line 222 of file ExpandPatterns.cpp.
References createFloatConst(), createTruncatedFPValue(), mlir::ImplicitLocOpBuilder::getLoc(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandCeilFPattern().
convertCoshOp()
static LogicalResult convertCoshOp (math::CoshOp op, PatternRewriter & rewriter) static
Definition at line 87 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandCoshPattern().
convertCtlzOp()
static LogicalResult convertCtlzOp (math::CountLeadingZerosOp op, PatternRewriter & rewriter) static
Definition at line 468 of file ExpandPatterns.cpp.
References createIntConst(), mlir::getElementTypeOrSelf(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandCtlzPattern().
convertExp2fOp()
static LogicalResult convertExp2fOp (math::Exp2Op op, PatternRewriter & rewriter) static
Definition at line 396 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::ImplicitLocOpBuilder::getLoc(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandExp2FPattern().
convertFmaFOp()
static LogicalResult convertFmaFOp (math::FmaOp op, PatternRewriter & rewriter) static
Definition at line 205 of file ExpandPatterns.cpp.
References mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandFmaFPattern().
convertFPowIOp()
static LogicalResult convertFPowIOp (math::FPowIOp op, PatternRewriter & rewriter) static
Definition at line 251 of file ExpandPatterns.cpp.
References mlir::presburger::abs(), createFloatConst(), mlir::getElementTypeOrSelf(), mlir::ImplicitLocOpBuilder::getLoc(), mlir::Value::getType(), getZero(), mlir::m_Constant(), mlir::m_ConstantInt(), mlir::matchPattern(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandFPowIPattern().
convertPowfOp()
static LogicalResult convertPowfOp (math::PowFOp op, PatternRewriter & rewriter) static
Definition at line 322 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), mlir::m_ConstantFloat(), mlir::matchPattern(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandPowFPattern().
convertRoundEvenOp()
static LogicalResult convertRoundEvenOp (math::RoundEvenOp op, PatternRewriter & rewriter) static
Definition at line 511 of file ExpandPatterns.cpp.
References createFloatConst(), createIntConst(), mlir::getElementTypeOrSelf(), mlir::Builder::getIntegerType(), mlir::Type::getIntOrFloatBitWidth(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), and mlir::presburger::round().
Referenced by mlir::populateExpandRoundEvenPattern().
convertRoundOp()
static LogicalResult convertRoundOp (math::RoundOp op, PatternRewriter & rewriter) static
Definition at line 408 of file ExpandPatterns.cpp.
References createFloatConst(), createIntConst(), createTruncatedFPValue(), mlir::getElementTypeOrSelf(), mlir::Builder::getI32Type(), mlir::Value::getType(), mlir::Type::isF32(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandRoundFPattern().
convertRsqrtOp()
static LogicalResult convertRsqrtOp (math::RsqrtOp op, PatternRewriter & rewriter) static
Definition at line 643 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::getElementTypeOrSelf(), and mlir::RewriterBase::replaceOpWithNewOp().
Referenced by mlir::populateExpandRsqrtPattern().
convertSinhOp()
static LogicalResult convertSinhOp (math::SinhOp op, PatternRewriter & rewriter) static
Definition at line 71 of file ExpandPatterns.cpp.
References createFloatConst(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandSinhPattern().
convertTanhOp()
static LogicalResult convertTanhOp (math::TanhOp op, PatternRewriter & rewriter) static
Expands tanh op into 1-exp^{-2x} / 1+exp^{-2x} To avoid overflow we exploit the reflection symmetry tanh(-x) = -tanh(x).
We compute a "signs" value which is -1 if input is negative and +1 if input is positive. Then multiply the input by this value, guaranteeing that the result is positive, which also guarantees exp^{-2x * sign(x)} is in (0, 1]. Expand the computation on the input x * sign(x), then multiply the result by sign(x) to retain sign of the real result.
Definition at line 110 of file ExpandPatterns.cpp.
References createFloatConst(), and mlir::RewriterBase::replaceOpWithNewOp().
Referenced by mlir::populateExpandTanhPattern().
convertTanOp()
static LogicalResult convertTanOp (math::TanOp op, PatternRewriter & rewriter) static
Definition at line 143 of file ExpandPatterns.cpp.
References mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::populateExpandTanPattern().
createFloatConst() [1/2]
static Value createFloatConst (Location loc, Type type, APFloat value, OpBuilder & b) static
Create a float constant.
Definition at line 25 of file ExpandPatterns.cpp.
References mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), and mlir::Builder::getFloatAttr().
Referenced by convertAcoshOp(), convertAsinhOp(), convertAtanhOp(), convertCeilOp(), convertCoshOp(), convertExp2fOp(), convertFPowIOp(), convertPowfOp(), convertRoundEvenOp(), convertRoundOp(), convertRsqrtOp(), convertSinhOp(), convertTanhOp(), and createFloatConst().
createFloatConst() [2/2]
static Value createFloatConst (Location loc, Type type, double value, OpBuilder & b) static
Definition at line 41 of file ExpandPatterns.cpp.
References createFloatConst().
createIntConst()
static Value createIntConst (Location loc, Type type, int64_t value, OpBuilder & b) static
Create an integer constant.
Definition at line 47 of file ExpandPatterns.cpp.
References mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), and mlir::Builder::getIntegerAttr().
Referenced by convertCtlzOp(), convertRoundEvenOp(), and convertRoundOp().
createTruncatedFPValue()
static Value createTruncatedFPValue (Value operand, ImplicitLocOpBuilder & b) static
Definition at line 58 of file ExpandPatterns.cpp.
References mlir::Builder::getI64Type(), and mlir::Value::getType().
Referenced by convertCeilOp(), and convertRoundOp().