MLIR: lib/Dialect/Linalg/Transforms/FoldAddIntoDest.cpp File Reference
FoldAddIntoDest.cpp File Reference
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Interfaces/DestinationStyleOpInterface.h"
Classes
struct FoldAddIntoDest
Replace a linalg.add with one operand the single user of a contraction, which has a zero-filled, "identity-mapped" destination and is dominated by the other operand, by the contraction with other as its dest.
Functions
static bool isDefinedAsZero (Value val)
Function Documentation
isDefinedAsZero()
bool isDefinedAsZero (Value val) static
Definition at line 18 of file FoldAddIntoDest.cpp.
References mlir::Value::getDefiningOp(), isDefinedAsZero(), mlir::m_AnyZeroFloat(), mlir::m_Zero(), and mlir::matchPattern().
Referenced by isDefinedAsZero(), and FoldAddIntoDest::matchAndRewrite().