MLIR: lib/Transforms/Utils/FoldUtils.cpp File Reference
FoldUtils.cpp File Reference
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Operation.h"
Functions
static Region * getInsertionRegion (DialectInterfaceCollection< DialectFoldInterface > &interfaces, Block *insertionBlock)
Given an operation, find the parent region that folded constants should be inserted into.
static Operation * materializeConstant (Dialect *dialect, OpBuilder &builder, Attribute value, Type type, Location loc)
A utility function used to materialize a constant for a given attribute and type.
Function Documentation
getInsertionRegion()
static Region* getInsertionRegion (DialectInterfaceCollection< DialectFoldInterface > & interfaces, Block * insertionBlock) static
Given an operation, find the parent region that folded constants should be inserted into.
Definition at line 26 of file FoldUtils.cpp.
References mlir::Block::getParent(), and mlir::Region::getParentOp().
Referenced by mlir::OperationFolder::getOrCreateConstant(), and mlir::OperationFolder::notifyRemoval().
materializeConstant()
static Operation* materializeConstant (Dialect * dialect, OpBuilder & builder, Attribute value, Type type, Location loc) static
A utility function used to materialize a constant for a given attribute and type.
On success, a valid constant value is returned. Otherwise, null is returned
Definition at line 51 of file FoldUtils.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::getInsertionPoint(), loc, mlir::m_Constant(), mlir::matchPattern(), mlir::Dialect::materializeConstant(), and value.
Referenced by mlir::OperationFolder::getOrCreateConstant(), mlir::vector::CombiningKindAttr::parse(), print(), printStandardCastOp(), remainsLegalAfterInline(), and verifyShapeOrExtentTensorOp().