MLIR: lib/Rewrite/FrozenRewritePatternSet.cpp File Reference
FrozenRewritePatternSet.cpp File Reference
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "ByteCode.h"
#include "mlir/Conversion/PDLToPDLInterp/PDLToPDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
Functions
static LogicalResult convertPDLToPDLInterp (ModuleOp pdlModule)
Function Documentation
convertPDLToPDLInterp()
static LogicalResult convertPDLToPDLInterp (ModuleOp pdlModule) static
Lower the PDL pattern module to the interpreter dialect.
Definition at line 19 of file FrozenRewritePatternSet.cpp.
References mlir::createPDLToPDLInterpPass(), mlir::PassManager::enableVerifier(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::isOpTriviallyDead(), op, and mlir::success().
Referenced by mlir::FrozenRewritePatternSet::FrozenRewritePatternSet().