MLIR: lib/Interfaces/FunctionInterfaces.cpp File Reference
FunctionInterfaces.cpp File Reference
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/FunctionInterfaces.cpp.inc"
Functions
static bool isEmptyAttrDict (Attribute attr)
template<bool isArg>
static ArrayAttr getArgResAttrs (FunctionOpInterface op)
Get either the argument or result attributes array.
template<bool isArg>
static void setArgResAttrs (FunctionOpInterface op, ArrayAttr attrs)
Set either the argument or result attributes array.
template<bool isArg>
static void removeArgResAttrs (FunctionOpInterface op)
Erase either the argument or result attributes array.
template<bool isArg>
static void setAllArgResAttrDicts (FunctionOpInterface op, ArrayRef< Attribute > attrs)
Set all of the argument or result attribute dictionaries for a function.
template<bool isArg>
static void setArgResAttrDict (FunctionOpInterface op, unsigned numTotalIndices, unsigned index, DictionaryAttr attrs)
Update the given index into an argument or result attribute dictionary.
Function Documentation
getArgResAttrs()
template<bool isArg> ArrayAttr getArgResAttrs (FunctionOpInterface op) static
Get either the argument or result attributes array.
Definition at line 59 of file FunctionInterfaces.cpp.
References ArrayAttr().
Referenced by setArgResAttrDict(), and mlir::function_interface_impl::setFunctionType().
isEmptyAttrDict()
bool isEmptyAttrDict (Attribute attr) static
Definition at line 23 of file FunctionInterfaces.cpp.
Referenced by setAllArgResAttrDicts(), and setArgResAttrDict().
removeArgResAttrs()
template<bool isArg> void removeArgResAttrs (FunctionOpInterface op) static
Erase either the argument or result attributes array.
Definition at line 77 of file FunctionInterfaces.cpp.
Referenced by setAllArgResAttrDicts(), setArgResAttrDict(), and mlir::function_interface_impl::setFunctionType().
setAllArgResAttrDicts()
template<bool isArg> void setAllArgResAttrDicts (FunctionOpInterface op, ArrayRef< Attribute > attrs) static
Set all of the argument or result attribute dictionaries for a function.
Definition at line 86 of file FunctionInterfaces.cpp.
References isEmptyAttrDict(), removeArgResAttrs(), and setArgResAttrs().
Referenced by mlir::function_interface_impl::setAllArgAttrDicts(), mlir::function_interface_impl::setAllResultAttrDicts(), and mlir::function_interface_impl::setFunctionType().
setArgResAttrDict()
template<bool isArg> void setArgResAttrDict (FunctionOpInterface op, unsigned numTotalIndices, unsigned index, DictionaryAttr attrs) static
Update the given index into an argument or result attribute dictionary.
Definition at line 122 of file FunctionInterfaces.cpp.
References ArrayAttr(), getArgResAttrs(), isEmptyAttrDict(), removeArgResAttrs(), and setArgResAttrs().
Referenced by mlir::function_interface_impl::setArgAttrs(), mlir::function_interface_impl::setArgAttrs(), mlir::function_interface_impl::setResultAttrs(), and mlir::function_interface_impl::setResultAttrs().
setArgResAttrs()
template<bool isArg> void setArgResAttrs (FunctionOpInterface op, ArrayAttr attrs) static
Set either the argument or result attributes array.
Definition at line 68 of file FunctionInterfaces.cpp.
References ArrayAttr().
Referenced by setAllArgResAttrDicts(), and setArgResAttrDict().