MLIR: lib/CAPI/Dialect/Func.cpp File Reference
Func.cpp File Reference
#include "mlir-c/Dialect/Func.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
Functions
void mlirFuncSetArgAttr (MlirOperation op, intptr_t pos, MlirStringRef name, MlirAttribute attr)
Sets the argument attribute 'name' of an argument at index 'pos'.
void mlirFuncSetResultAttr (MlirOperation op, intptr_t pos, MlirStringRef name, MlirAttribute attr)
Function Documentation
mlirFuncSetArgAttr()
void mlirFuncSetArgAttr (MlirOperation op, intptr_t pos, MlirStringRef name, MlirAttribute attr)
Sets the argument attribute 'name' of an argument at index 'pos'.
Asserts that the operation is a FuncOp.
Definition at line 17 of file Func.cpp.
References mlirFuncSetArgAttr(), and unwrap().
Referenced by mlirFuncSetArgAttr().
mlirFuncSetResultAttr()
void mlirFuncSetResultAttr (MlirOperation op, intptr_t pos, MlirStringRef name, MlirAttribute attr)
Definition at line 23 of file Func.cpp.
References unwrap().