MLIR: lib/Dialect/Linalg/Transforms/Generalization.cpp File Reference
Generalization.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "linalg-generalization"
Functions
static GenericOp createGenericOpFromNamedOp (LinalgOp namedOp, PatternRewriter &rewriter)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-generalization"
Definition at line 27 of file Generalization.cpp.
Function Documentation
createGenericOpFromNamedOp()
static GenericOp createGenericOpFromNamedOp (LinalgOp namedOp, PatternRewriter & rewriter) static
Definition at line 34 of file Generalization.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::linalg::LinalgTransformationFilter::checkAndNotify(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::OpBuilder::getBlock(), mlir::Operation::getResults(), mlir::RewriterBase::inlineRegionBefore(), iterators, loc, mlir::linalg::populateLinalgConvGeneralizationPatterns(), mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns(), mlir::linalg::LinalgTransformationFilter::replaceLinalgTransformationFilter(), mlir::RewriterBase::replaceOp(), rewriter, and mlir::success().