MLIR: include/mlir-c/Dialect/GPU.h File Reference
GPU.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Dialect/GPU/Transforms/Passes.capi.h.inc"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (GPU, gpu)
MLIR_CAPI_EXPORTED bool mlirTypeIsAGPUAsyncTokenType (MlirType type)
MLIR_CAPI_EXPORTED MlirType mlirGPUAsyncTokenTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirAttributeIsAGPUObjectAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGet (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps)
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetWithKernels (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps, MlirAttribute mlirKernelsAttr)
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetTarget (MlirAttribute mlirObjectAttr)
MLIR_CAPI_EXPORTED uint32_t mlirGPUObjectAttrGetFormat (MlirAttribute mlirObjectAttr)
MLIR_CAPI_EXPORTED MlirStringRef mlirGPUObjectAttrGetObject (MlirAttribute mlirObjectAttr)
MLIR_CAPI_EXPORTED bool mlirGPUObjectAttrHasProperties (MlirAttribute mlirObjectAttr)
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetProperties (MlirAttribute mlirObjectAttr)
MLIR_CAPI_EXPORTED bool mlirGPUObjectAttrHasKernels (MlirAttribute mlirObjectAttr)
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetKernels (MlirAttribute mlirObjectAttr)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (GPU , gpu)
References MLIR_CAPI_EXPORTED, and target.
mlirAttributeIsAGPUObjectAttr()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAGPUObjectAttr (MlirAttribute attr)
Definition at line 34 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirGPUAsyncTokenTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirGPUAsyncTokenTypeGet (MlirContext ctx)
Definition at line 26 of file GPU.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGet (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps)
Definition at line 38 of file GPU.cpp.
References target, unwrap(), and wrap().
mlirGPUObjectAttrGetFormat()
MLIR_CAPI_EXPORTED uint32_t mlirGPUObjectAttrGetFormat (MlirAttribute mlirObjectAttr)
Definition at line 76 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetKernels()
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetKernels (MlirAttribute mlirObjectAttr)
Definition at line 107 of file GPU.cpp.
References unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetObject()
MLIR_CAPI_EXPORTED MlirStringRef mlirGPUObjectAttrGetObject (MlirAttribute mlirObjectAttr)
Definition at line 82 of file GPU.cpp.
References mlirStringRefCreate(), and unwrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetProperties()
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetProperties (MlirAttribute mlirObjectAttr)
Definition at line 95 of file GPU.cpp.
References unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetTarget()
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetTarget (MlirAttribute mlirObjectAttr)
Definition at line 70 of file GPU.cpp.
References unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetWithKernels()
MLIR_CAPI_EXPORTED MlirAttribute mlirGPUObjectAttrGetWithKernels (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps, MlirAttribute mlirKernelsAttr)
Definition at line 51 of file GPU.cpp.
References target, unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrHasKernels()
MLIR_CAPI_EXPORTED bool mlirGPUObjectAttrHasKernels (MlirAttribute mlirObjectAttr)
Definition at line 101 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrHasProperties()
MLIR_CAPI_EXPORTED bool mlirGPUObjectAttrHasProperties (MlirAttribute mlirObjectAttr)
Definition at line 89 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirTypeIsAGPUAsyncTokenType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAGPUAsyncTokenType (MlirType type)
Definition at line 22 of file GPU.cpp.
References mlirTypeIsAGPUAsyncTokenType(), and unwrap().
Referenced by mlirTypeIsAGPUAsyncTokenType(), and NB_MODULE().