MLIR: lib/CAPI/Dialect/GPU.cpp File Reference
GPU.cpp File Reference
#include "mlir-c/Dialect/GPU.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "llvm/Support/Casting.h"
Functions
bool mlirTypeIsAGPUAsyncTokenType (MlirType type)
MlirType mlirGPUAsyncTokenTypeGet (MlirContext ctx)
bool mlirAttributeIsAGPUObjectAttr (MlirAttribute attr)
MlirAttribute mlirGPUObjectAttrGet (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps)
MlirAttribute mlirGPUObjectAttrGetWithKernels (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps, MlirAttribute mlirKernelsAttr)
MlirAttribute mlirGPUObjectAttrGetTarget (MlirAttribute mlirObjectAttr)
uint32_t mlirGPUObjectAttrGetFormat (MlirAttribute mlirObjectAttr)
MlirStringRef mlirGPUObjectAttrGetObject (MlirAttribute mlirObjectAttr)
bool mlirGPUObjectAttrHasProperties (MlirAttribute mlirObjectAttr)
MlirAttribute mlirGPUObjectAttrGetProperties (MlirAttribute mlirObjectAttr)
bool mlirGPUObjectAttrHasKernels (MlirAttribute mlirObjectAttr)
MlirAttribute mlirGPUObjectAttrGetKernels (MlirAttribute mlirObjectAttr)
Function Documentation
mlirAttributeIsAGPUObjectAttr()
bool mlirAttributeIsAGPUObjectAttr (MlirAttribute attr)
Definition at line 34 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirGPUAsyncTokenTypeGet()
MlirType mlirGPUAsyncTokenTypeGet (MlirContext ctx)
Definition at line 26 of file GPU.cpp.
References mlir::detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >::get(), unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGet()
MlirAttribute mlirGPUObjectAttrGet (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps)
Definition at line 38 of file GPU.cpp.
References target, unwrap(), and wrap().
mlirGPUObjectAttrGetFormat()
uint32_t mlirGPUObjectAttrGetFormat (MlirAttribute mlirObjectAttr)
Definition at line 76 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetKernels()
MlirAttribute mlirGPUObjectAttrGetKernels (MlirAttribute mlirObjectAttr)
Definition at line 107 of file GPU.cpp.
References unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetObject()
MlirStringRef mlirGPUObjectAttrGetObject (MlirAttribute mlirObjectAttr)
Definition at line 82 of file GPU.cpp.
References mlirStringRefCreate(), and unwrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetProperties()
MlirAttribute mlirGPUObjectAttrGetProperties (MlirAttribute mlirObjectAttr)
Definition at line 95 of file GPU.cpp.
References unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetTarget()
MlirAttribute mlirGPUObjectAttrGetTarget (MlirAttribute mlirObjectAttr)
Definition at line 70 of file GPU.cpp.
References unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrGetWithKernels()
MlirAttribute mlirGPUObjectAttrGetWithKernels (MlirContext mlirCtx, MlirAttribute target, uint32_t format, MlirStringRef objectStrRef, MlirAttribute mlirObjectProps, MlirAttribute mlirKernelsAttr)
Definition at line 51 of file GPU.cpp.
References target, unwrap(), and wrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrHasKernels()
bool mlirGPUObjectAttrHasKernels (MlirAttribute mlirObjectAttr)
Definition at line 101 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirGPUObjectAttrHasProperties()
bool mlirGPUObjectAttrHasProperties (MlirAttribute mlirObjectAttr)
Definition at line 89 of file GPU.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirTypeIsAGPUAsyncTokenType()
bool mlirTypeIsAGPUAsyncTokenType (MlirType type)
Definition at line 22 of file GPU.cpp.
References mlirTypeIsAGPUAsyncTokenType(), and unwrap().
Referenced by mlirTypeIsAGPUAsyncTokenType(), and NB_MODULE().