MLIR: lib/Dialect/GPU/IR/GPUDialect.cpp File Reference
GPUDialect.cpp File Reference
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/GPU/GPUOpsDialect.cpp.inc"
#include "mlir/Dialect/GPU/GPUOps.cpp.inc"
#include "mlir/Dialect/GPU/GPUOpInterfaces.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Enumerations
enum GPUMemorySpace { kGenericMemorySpace = 0, kGlobalMemorySpace = 1, kSharedMemorySpace = 3 }
GPU memory space identifiers.
Functions
template<typename T >
static LogicalResult verifyIndexOp (T op)
static LogicalResult verifyAllReduce (gpu::AllReduceOp allReduce)
static LogicalResult verifyShuffleOp (gpu::ShuffleOp shuffleOp)
static void printShuffleOp (OpAsmPrinter &p, ShuffleOp op)
static ParseResult parseShuffleOp (OpAsmParser &parser, OperationState &state)
static LogicalResult verify (LaunchOp op)
static void printSizeAssignment (OpAsmPrinter &p, KernelDim3 size, KernelDim3 operands, KernelDim3 ids)
static void printLaunchOp (OpAsmPrinter &p, LaunchOp op)
static ParseResult parseSizeAssignment (OpAsmParser &parser, MutableArrayRef< OpAsmParser::OperandType > sizes, MutableArrayRef< OpAsmParser::OperandType > regionSizes, MutableArrayRef< OpAsmParser::OperandType > indices)
static ParseResult parseLaunchOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (LaunchFuncOp op)
static ParseResult parseLaunchFuncOperands (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes)
static void printLaunchFuncOperands (OpAsmPrinter &printer, Operation *, OperandRange operands, TypeRange types)
static ParseResult parseAttributions (OpAsmParser &parser, StringRef keyword, SmallVectorImpl< OpAsmParser::OperandType > &args, SmallVectorImpl< Type > &argTypes)
Parses a GPU function memory attribution.
static ParseResult parseGPUFuncOp (OpAsmParser &parser, OperationState &result)
Parses a GPU function.
static void printAttributions (OpAsmPrinter &p, StringRef keyword, ArrayRef< BlockArgument > values)
static void printGPUFuncOp (OpAsmPrinter &p, GPUFuncOp op)
Prints a GPU Func op.
static LogicalResult verifyAttributions (Operation *op, ArrayRef< BlockArgument > attributions, unsigned memorySpace)
static ParseResult parseReturnOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (gpu::ReturnOp returnOp)
static ParseResult parseGPUModuleOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, GPUModuleOp op)
static LogicalResult verify (MemcpyOp op)
static ParseResult parseAsyncDependencies (OpAsmParser &parser, Type &asyncTokenType, SmallVectorImpl< OpAsmParser::OperandType > &asyncDependencies)
static void printAsyncDependencies (OpAsmPrinter &printer, Operation *op, Type asyncTokenType, OperandRange asyncDependencies)
static LogicalResult verify (SubgroupMmaLoadMatrixOp op)
static LogicalResult verify (SubgroupMmaStoreMatrixOp op)
static LogicalResult verify (SubgroupMmaComputeOp op)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1094 of file GPUDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
GPUMemorySpace
enum GPUMemorySpace
GPU memory space identifiers.
Enumerator
kGenericMemorySpace
Generic memory space identifier.
kGlobalMemorySpace
Global memory space identifier.
kSharedMemorySpace
Shared memory space identifier.
Definition at line 87 of file GPUDialect.cpp.
Function Documentation
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref.cast into the root operation directly.
Definition at line 1075 of file GPUDialect.cpp.
References mlir::Operation::getOpOperands(), and mlir::success().
parseAsyncDependencies()
static ParseResult parseAsyncDependencies (OpAsmParser & parser, Type & asyncTokenType, SmallVectorImpl< OpAsmParser::OperandType > & asyncDependencies) static
Definition at line 958 of file GPUDialect.cpp.
References mlir::OpAsmParser::emitError(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::OpAsmParser::getNumResults(), mlir::Builder::getType(), loc, mlir::OpAsmParser::OptionalSquare, mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalKeyword(), and mlir::succeeded().
parseAttributions()
static ParseResult parseAttributions (OpAsmParser & parser, StringRef keyword, SmallVectorImpl< OpAsmParser::OperandType > & args, SmallVectorImpl< Type > & argTypes) static
Parses a GPU function memory attribution.
memory-attribution ::= (workgroup (ssa-id-and-type-list))? (private (ssa-id-and-type-list))?
Note that this function parses only one of the two similar parts, with the keyword provided as argument.
Definition at line 675 of file GPUDialect.cpp.
References mlir::failed(), mlir::failure(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
Referenced by parseGPUFuncOp().
parseGPUFuncOp()
static ParseResult parseGPUFuncOp (OpAsmParser & parser, OperationState & result) static
Parses a GPU function.
<operation> ::= gpu.func symbol-ref-id (argument-list) (-> function-result-list)? memory-attribution kernel? function-attributes? region
Definition at line 708 of file GPUDialect.cpp.
References mlir::function_like_impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getFunctionType(), mlir::Builder::getI64IntegerAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_like_impl::getTypeAttrName(), mlir::Builder::getUnitAttr(), parseAttributions(), mlir::function_like_impl::parseFunctionSignature(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseSymbolName(), and mlir::succeeded().
parseGPUModuleOp()
static ParseResult parseGPUModuleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 911 of file GPUDialect.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::SymbolTable::getSymbolAttrName(), mlir::OperationState::location, mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseSymbolName(), and mlir::success().
parseLaunchFuncOperands()
static ParseResult parseLaunchFuncOperands (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes) static
Definition at line 598 of file GPUDialect.cpp.
References mlir::function_like_impl::parseFunctionArgumentList(), mlir::OpAsmParser::parseOptionalKeyword(), and mlir::success().
parseLaunchOp()
static ParseResult parseLaunchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 490 of file GPUDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::gpu::MMAMatrixType::getOperand(), mlir::Builder::getSymbolRefAttr(), mlir::OperationState::operands, mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), parseSizeAssignment(), mlir::OpAsmParser::resolveOperands(), mlir::gpu::KernelDim3::x, mlir::gpu::KernelDim3::y, and mlir::gpu::KernelDim3::z.
parseReturnOp()
static ParseResult parseReturnOp (OpAsmParser & parser, OperationState & result) static
Definition at line 865 of file GPUDialect.cpp.
References mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalColonTypeList(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseShuffleOp()
static ParseResult parseShuffleOp (OpAsmParser & parser, OperationState & state) static
Definition at line 306 of file GPUDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypesToList(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI1Type(), mlir::Builder::getIntegerType(), mlir::Builder::getStringAttr(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
parseSizeAssignment()
static ParseResult parseSizeAssignment (OpAsmParser & parser, MutableArrayRef< OpAsmParser::OperandType > sizes, MutableArrayRef< OpAsmParser::OperandType > regionSizes, MutableArrayRef< OpAsmParser::OperandType > indices) static
Definition at line 462 of file GPUDialect.cpp.
References mlir::failure(), mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::parseRegionArgumentList(), and mlir::OpAsmParser::parseRParen().
Referenced by parseLaunchOp().
print()
static void print (OpAsmPrinter & p, GPUModuleOp op) static
Definition at line 932 of file GPUDialect.cpp.
References mlir::SymbolTable::getSymbolAttrName(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), and mlir::OpAsmPrinter::printSymbolName().
printAsyncDependencies()
static void printAsyncDependencies (OpAsmPrinter & printer, Operation * op, Type asyncTokenType, OperandRange asyncDependencies) static
Definition at line 971 of file GPUDialect.cpp.
printAttributions()
static void printAttributions (OpAsmPrinter & p, StringRef keyword, ArrayRef< BlockArgument > values) static
Definition at line 771 of file GPUDialect.cpp.
References mlir::Value::getType().
Referenced by printGPUFuncOp().
printGPUFuncOp()
static void printGPUFuncOp (OpAsmPrinter & p, GPUFuncOp op) static
Prints a GPU Func op.
Definition at line 783 of file GPUDialect.cpp.
References mlir::function_like_impl::getTypeAttrName(), mlir::Type::isa(), printAttributions(), mlir::function_like_impl::printFunctionAttributes(), mlir::function_like_impl::printFunctionSignature(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmPrinter::printSymbolName(), and mlir::success().
printLaunchFuncOperands()
static void printLaunchFuncOperands (OpAsmPrinter & printer, Operation * , OperandRange operands, TypeRange types) static
Definition at line 610 of file GPUDialect.cpp.
References mlir::Block::addArguments(), mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addRegion(), mlir::Region::getBlocks(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_like_impl::getTypeAttrName(), mlir::OpAsmPrinter::printOperand(), and mlir::OpAsmPrinter::printType().
printLaunchOp()
static void printLaunchOp (OpAsmPrinter & p, LaunchOp op) static
Definition at line 442 of file GPUDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), and printSizeAssignment().
printShuffleOp()
static void printShuffleOp (OpAsmPrinter & p, ShuffleOp op) static
Definition at line 301 of file GPUDialect.cpp.
printSizeAssignment()
static void printSizeAssignment (OpAsmPrinter & p, KernelDim3 size, KernelDim3 operands, KernelDim3 ids) static
Definition at line 434 of file GPUDialect.cpp.
References mlir::gpu::KernelDim3::x, mlir::gpu::KernelDim3::y, and mlir::gpu::KernelDim3::z.
Referenced by printLaunchOp().
verify() [1/7]
static LogicalResult verify (LaunchOp op) static
Definition at line 400 of file GPUDialect.cpp.
References mlir::success().
verify() [2/7]
static LogicalResult verify (LaunchFuncOp op) static
Definition at line 578 of file GPUDialect.cpp.
References mlir::success().
verify() [3/7]
static LogicalResult verify (gpu::ReturnOp returnOp) static
Definition at line 877 of file GPUDialect.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::detail::enumerate(), mlir::Builder::getNamedAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::Value::getType(), mlir::OperationState::location, mlir::NamedAttrList::push_back(), and mlir::success().
verify() [4/7]
static LogicalResult verify (MemcpyOp op) static
Definition at line 945 of file GPUDialect.cpp.
References mlir::failed(), mlir::getElementTypeOrSelf(), mlir::success(), and mlir::verifyCompatibleShape().
verify() [5/7]
static LogicalResult verify (SubgroupMmaLoadMatrixOp op) static
Definition at line 987 of file GPUDialect.cpp.
References mlir::gpu::MMAMatrixType::getOperand(), kGenericMemorySpace, kGlobalMemorySpace, kSharedMemorySpace, and mlir::success().
verify() [6/7]
static LogicalResult verify (SubgroupMmaStoreMatrixOp op) static
Definition at line 1016 of file GPUDialect.cpp.
References kGenericMemorySpace, kGlobalMemorySpace, kSharedMemorySpace, and mlir::success().
verify() [7/7]
static LogicalResult verify (SubgroupMmaComputeOp op) static
Definition at line 1044 of file GPUDialect.cpp.
References mlir::gpu::MMAMatrixType::getOperand(), op, and mlir::success().
verifyAllReduce()
static LogicalResult verifyAllReduce (gpu::AllReduceOp allReduce) static
Definition at line 253 of file GPUDialect.cpp.
References mlir::success().
verifyAttributions()
static LogicalResult verifyAttributions (Operation * op, ArrayRef< BlockArgument > attributions, unsigned memorySpace) static
Definition at line 817 of file GPUDialect.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), and mlir::success().
verifyIndexOp()
template<typename T > static LogicalResult verifyIndexOp (T op) static
Definition at line 246 of file GPUDialect.cpp.
References mlir::success().
verifyShuffleOp()
static LogicalResult verifyShuffleOp (gpu::ShuffleOp shuffleOp) static
Definition at line 288 of file GPUDialect.cpp.
References mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isSignlessIntOrFloat(), and mlir::success().