MLIR: lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp File Reference
GPUToLLVMSPV.cpp File Reference
#include "mlir/Conversion/GPUToLLVMSPV/GPUToLLVMSPVPass.h"
#include "../GPUCommon/GPUOpsLowering.h"
#include "mlir/Conversion/GPUCommon/AttrToSPIRVConverter.h"
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/LoweringOptions.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Conversion/SPIRVCommon/AttrToLLVMConverter.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMAttrs.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVEnums.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "mlir/Conversion/Passes.h.inc"
Classes
class mlir::impl::ConvertGpuOpsToLLVMSPVOpsBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define DEBUG_TYPE "gpu-to-llvm-spv"
#define GEN_PASS_DEF_CONVERTGPUOPSTOLLVMSPVOPS
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToLLVMSPVOps ()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToLLVMSPVOps (ConvertGpuOpsToLLVMSPVOpsOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToLLVMSPVOps ()
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToLLVMSPVOps (ConvertGpuOpsToLLVMSPVOpsOptions options)
static LLVM::LLVMFuncOp lookupOrCreateSPIRVFn (Operation *symbolTable, StringRef name, ArrayRef< Type > paramTypes, Type resultType, bool isMemNone, bool isConvergent)
static LLVM::CallOp createSPIRVBuiltinCall (Location loc, ConversionPatternRewriter &rewriter, LLVM::LLVMFuncOp func, ValueRange args)
void mlir::populateGpuToLLVMSPVConversionPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns)
void mlir::populateGpuMemorySpaceAttributeConversions (TypeConverter &typeConverter)
Populates memory space attribute conversion rules for lowering gpu.address_space to integer values.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gpu-to-llvm-spv"
Definition at line 35 of file GPUToLLVMSPV.cpp.
GEN_PASS_DEF_CONVERTGPUOPSTOLLVMSPVOPS
#define GEN_PASS_DEF_CONVERTGPUOPSTOLLVMSPVOPS
Definition at line 40 of file GPUToLLVMSPV.cpp.
Function Documentation
createSPIRVBuiltinCall()
LLVM::CallOp createSPIRVBuiltinCall (Location loc, ConversionPatternRewriter & rewriter, LLVM::LLVMFuncOp func, ValueRange args) static
Definition at line 81 of file GPUToLLVMSPV.cpp.
lookupOrCreateSPIRVFn()
LLVM::LLVMFuncOp lookupOrCreateSPIRVFn (Operation * symbolTable, StringRef name, ArrayRef< Type > paramTypes, Type resultType, bool isMemNone, bool isConvergent) static
Definition at line 48 of file GPUToLLVMSPV.cpp.
References b, mlir::Operation::getLoc(), mlir::Operation::getRegion(), and mlir::SymbolTable::lookupSymbolIn().