MLIR: lib/Conversion/GPUToSPIRV/GPUToSPIRV.cpp File Reference
GPUToSPIRV.cpp File Reference
#include "mlir/Conversion/GPUToSPIRV/GPUToSPIRV.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVEnums.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Transforms/DialectConversion.h"
#include <optional>
Classes
class GPUAllReduceConversion
Pattern to convert a gpu.all_reduce op into a SPIR-V group op.
class GPUSubgroupReduceConversion
Pattern to convert a gpu.subgroup_reduce op into a SPIR-V group op.
Functions
static spirv::FuncOp lowerAsEntryFunction (gpu::GPUFuncOp funcOp, const TypeConverter &typeConverter, ConversionPatternRewriter &rewriter, spirv::EntryPointABIAttr entryPointInfo, ArrayRef< spirv::InterfaceVarABIAttr > argABIInfo)
static LogicalResult getDefaultABIAttrs (const spirv::TargetEnv &targetEnv, gpu::GPUFuncOp funcOp, SmallVectorImpl< spirv::InterfaceVarABIAttr > &argABI)
Populates argABI with spirv.interface_var_abi attributes for lowering gpu.func to spirv.func if no arguments have the attributes set already.
template<typename UniformOp , typename NonUniformOp >
static Value createGroupReduceOpImpl (OpBuilder &builder, Location loc, Value arg, bool isGroup, bool isUniform, std::optional< uint32_t > clusterSize)
static std::optional< Value > createGroupReduceOp (OpBuilder &builder, Location loc, Value arg, gpu::AllReduceOperation opType, bool isGroup, bool isUniform, std::optional< uint32_t > clusterSize)
static std::string makeVarName (spirv::ModuleOp moduleOp, llvm::Twine prefix)
Variables
static constexpr const char kSPIRVModule [] = "__spv__"
Function Documentation
createGroupReduceOp()
static std::optional<Value> createGroupReduceOp (OpBuilder & builder, Location loc, Value arg, gpu::AllReduceOperation opType, bool isGroup, bool isUniform, std::optional< uint32_t > clusterSize) static
Definition at line 578 of file GPUToSPIRV.cpp.
References createGroupReduceOpImpl(), mlir::Value::getType(), kind, and MINUI.
Referenced by GPUAllReduceConversion::matchAndRewrite(), and GPUSubgroupReduceConversion::matchAndRewrite().
createGroupReduceOpImpl()
template<typename UniformOp , typename NonUniformOp > static Value createGroupReduceOpImpl (OpBuilder & builder, Location loc, Value arg, bool isGroup, bool isUniform, std::optional< uint32_t > clusterSize) static
Definition at line 550 of file GPUToSPIRV.cpp.
References mlir::get(), mlir::Builder::getContext(), mlir::Builder::getI32Type(), mlir::Builder::getIntegerAttr(), and mlir::Value::getType().
Referenced by createGroupReduceOp().
getDefaultABIAttrs()
static LogicalResult getDefaultABIAttrs (const spirv::TargetEnv & targetEnv, gpu::GPUFuncOp funcOp, SmallVectorImpl< spirv::InterfaceVarABIAttr > & argABI) static
Populates argABI with spirv.interface_var_abi attributes for lowering gpu.func to spirv.func if no arguments have the attributes set already.
Returns failure if any argument has the ABI attribute set already.
Definition at line 291 of file GPUToSPIRV.cpp.
References mlir::spirv::getInterfaceVarABIAttr(), mlir::spirv::getInterfaceVarABIAttrName(), and mlir::spirv::needsInterfaceVarABIAttrs().
lowerAsEntryFunction()
static spirv::FuncOp lowerAsEntryFunction (gpu::GPUFuncOp funcOp, const TypeConverter & typeConverter, ConversionPatternRewriter & rewriter, spirv::EntryPointABIAttr entryPointInfo, ArrayRef< spirv::InterfaceVarABIAttr > argABIInfo) static
Definition at line 231 of file GPUToSPIRV.cpp.
References mlir::TypeConverter::SignatureConversion::addInputs(), mlir::ConversionPatternRewriter::convertRegionTypes(), mlir::TypeConverter::convertType(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::TypeConverter::SignatureConversion::getConvertedTypes(), mlir::spirv::getEntryPointABIAttrName(), mlir::Builder::getFunctionType(), mlir::spirv::getInterfaceVarABIAttrName(), mlir::SymbolTable::getSymbolAttrName(), and mlir::RewriterBase::inlineRegionBefore().
makeVarName()
static std::string makeVarName (spirv::ModuleOp moduleOp, llvm::Twine prefix) static
Definition at line 711 of file GPUToSPIRV.cpp.
Variable Documentation
kSPIRVModule
constexpr const char kSPIRVModule[] = "__spv__" static constexpr
Definition at line 27 of file GPUToSPIRV.cpp.