MLIR: lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp File Reference
GPUToLLVMConversion.cpp File Reference
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
#include "mlir/Conversion/ConvertToLLVM/ToLLVMPass.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/GPUCommon/GPUToLLVM.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/STLExtras.h"
#include "mlir/Conversion/Passes.h.inc"
Classes
class mlir::impl::GpuToLLVMConversionPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define DEBUG_TYPE "gpu-to-llvm"
#define GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
#define DECLARE_CONVERT_OP_TO_GPU_RUNTIME_CALL_PATTERN(op_name)
Generic rewriting rule for operation on sparse matrices.
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuToLLVMConversionPass (GpuToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createGpuToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > mlir::createGpuToLLVMConversionPass (GpuToLLVMConversionPassOptions options)
static int32_t getCuSparseIndexTypeFrom (Type type)
static int32_t getCuSparseLtDataTypeFrom (Type type)
static int32_t getCuSparseDataTypeFrom (Type type)
static gpu::Prune2To4SpMatFlag get2To4PruneFlag (Value spMat)
static bool is2To4Sparsity (Value spMat)
static bool isSpMMCusparseLtOp (Value op)
static LogicalResult areAllLLVMTypes (Operation *op, ValueRange operands, ConversionPatternRewriter &rewriter)
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter &rewriter, gpu::AsyncOpInterface op)
static bool isGpuAsyncTokenType (Value value)
static bool isDefinedByCallTo (Value value, StringRef functionName)
static Value bitAndAddrspaceCast (Location loc, ConversionPatternRewriter &rewriter, LLVM::LLVMPointerType destinationType, Value sourcePtr, const LLVMTypeConverter &typeConverter)
template<typename T>
static Value genConstInt32From (OpBuilder &builder, Location loc, T tValue)
template<typename T>
static Value genConstFloat32From (OpBuilder &builder, Location loc, T tValue)
template<typename T>
static void addOpaquePointerConversion (LLVMTypeConverter &converter)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gpu-to-llvm"
Definition at line 42 of file GPUToLLVMConversion.cpp.
DECLARE_CONVERT_OP_TO_GPU_RUNTIME_CALL_PATTERN
#define DECLARE_CONVERT_OP_TO_GPU_RUNTIME_CALL_PATTERN (op_name)
Value:
  class Convert##op_name##ToGpuRuntimeCallPattern                              \
      : public ConvertOpToGpuRuntimeCallPattern<gpu::op_name> {                \
  public:                                                                      \
    Convert##op_name##ToGpuRuntimeCallPattern(                                 \
        const LLVMTypeConverter &typeConverter)                                \
        : ConvertOpToGpuRuntimeCallPattern<gpu::op_name>(typeConverter) {}     \
                                                                               \
  private:                                                                     \
    LogicalResult                                                              \
    matchAndRewrite(gpu::op_name op, OpAdaptor adaptor,                        \
                    ConversionPatternRewriter &rewriter) const override;       \
  };
Generic rewriting rule for operation on sparse matrices.
Currently supports CUDA (by means of cuSparse and cuSparseLt).
Definition at line 488 of file GPUToLLVMConversion.cpp.
GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
Definition at line 45 of file GPUToLLVMConversion.cpp.
Function Documentation
addOpaquePointerConversion()
template<typename T> void addOpaquePointerConversion (LLVMTypeConverter & converter) static
Definition at line 1549 of file GPUToLLVMConversion.cpp.
References mlir::LLVMTypeConverter::getContext().
Referenced by mlir::populateGpuToLLVMConversionPatterns().
areAllLLVMTypes()
LogicalResult areAllLLVMTypes (Operation * op, ValueRange operands, ConversionPatternRewriter & rewriter) static
Definition at line 689 of file GPUToLLVMConversion.cpp.
References mlir::Value::getType(), mlir::LLVM::isCompatibleType(), and success().
bitAndAddrspaceCast()
Value bitAndAddrspaceCast (Location loc, ConversionPatternRewriter & rewriter, LLVM::LLVMPointerType destinationType, Value sourcePtr, const LLVMTypeConverter & typeConverter) static
Definition at line 1047 of file GPUToLLVMConversion.cpp.
References mlir::Value::getType().
genConstFloat32From()
template<typename T> Value genConstFloat32From (OpBuilder & builder, Location loc, T tValue) static
Definition at line 1161 of file GPUToLLVMConversion.cpp.
References mlir::Builder::getF32FloatAttr(), and mlir::Builder::getF32Type().
genConstInt32From()
template<typename T> Value genConstInt32From (OpBuilder & builder, Location loc, T tValue) static
Definition at line 1154 of file GPUToLLVMConversion.cpp.
References mlir::Builder::getIntegerType().
get2To4PruneFlag()
gpu::Prune2To4SpMatFlag get2To4PruneFlag (Value spMat) static
Definition at line 647 of file GPUToLLVMConversion.cpp.
References mlir::Value::getDefiningOp().
getCuSparseDataTypeFrom()
int32_t getCuSparseDataTypeFrom (Type type) static
Definition at line 610 of file GPUToLLVMConversion.cpp.
References mlir::Type::isBF16(), mlir::Type::isF16(), mlir::Type::isF32(), mlir::Type::isF64(), and mlir::Type::isInteger().
getCuSparseIndexTypeFrom()
int32_t getCuSparseIndexTypeFrom (Type type) static
Definition at line 592 of file GPUToLLVMConversion.cpp.
References mlir::Type::isInteger().
getCuSparseLtDataTypeFrom()
int32_t getCuSparseLtDataTypeFrom (Type type) static
Definition at line 600 of file GPUToLLVMConversion.cpp.
References mlir::Type::isF16(), and mlir::Type::isInteger().
is2To4Sparsity()
bool is2To4Sparsity (Value spMat) static
Definition at line 658 of file GPUToLLVMConversion.cpp.
References mlir::Value::getDefiningOp(), and mlir::Operation::print().
Referenced by isSpMMCusparseLtOp().
isAsyncWithOneDependency()
LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter & rewriter, gpu::AsyncOpInterface op) static
Definition at line 700 of file GPUToLLVMConversion.cpp.
References success().
isDefinedByCallTo()
bool isDefinedByCallTo (Value value, StringRef functionName) static
Definition at line 868 of file GPUToLLVMConversion.cpp.
References mlir::Value::getDefiningOp(), and mlir::Value::getType().
isGpuAsyncTokenType()
bool isGpuAsyncTokenType (Value value) static
Definition at line 833 of file GPUToLLVMConversion.cpp.
References mlir::Value::getType().
isSpMMCusparseLtOp()
bool isSpMMCusparseLtOp (Value op) static
Definition at line 676 of file GPUToLLVMConversion.cpp.
References mlir::Value::getUsers(), and is2To4Sparsity().