MLIR: lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp File Reference
GreedyPatternRewriteDriver.cpp File Reference
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Config/mlir-config.h"
#include "mlir/IR/Action.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Rewrite/PatternApplicator.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "greedy-rewriter"
Functions
static Region * findCommonAncestor (ArrayRef< Operation * > ops)
Find the region that is the closest common ancestor of all given ops.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "greedy-rewriter"
Definition at line 36 of file GreedyPatternRewriteDriver.cpp.
Function Documentation
findCommonAncestor()
static Region* findCommonAncestor (ArrayRef< Operation * > ops) static
Find the region that is the closest common ancestor of all given ops.
Note: This function returns nullptr if there is a top-level op among the given list of ops.
Definition at line 990 of file GreedyPatternRewriteDriver.cpp.
References mlir::Region::findAncestorOpInRegion(), and mlir::Region::getParentRegion().
Referenced by mlir::applyOpPatternsGreedily().