MLIR: lib/Dialect/Linalg/Transforms/Hoisting.cpp File Reference
Hoisting.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Hoisting.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Linalg/Analysis/ConstraintsSet.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SCF/Utils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/LoopUtils.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "linalg-hoisting"
#define DBGS() (dbgs() << '[' << DEBUG_TYPE << "] ")
Functions
static bool isEqualOffsetSizeOrStride (OpFoldResult op1, OpFoldResult op2)
Return true if op1 and op2 are the same constant or the same SSA value.
static bool sameOffsetsSizesAndStrides (tensor::ExtractSliceOp s, tensor::InsertSliceOp si)
Return true is all offsets, sizes and strides are equal.
static HoistableRead findMatchingTransferRead (HoistableWrite write, Value srcTensor)
Look for a HoistableRead, in the given tensor uses, accessing the same offset as the HoistableWrite.
static bool tensorChunkAccessedByUnknownOp (HoistableWrite write, HoistableRead candidateRead, BlockArgument tensorArg)
Check if the chunk of data inserted by the HoistableWrite are read by any other op than the HoistableRead candidate.
static HoistableWrite getLoopInvariantTransferWriteOpDefining (scf::ForOp forOp, OpOperand &yieldOperand)
Return the forOp-invariant HoistableWrite that produces yieldOperand.
static void hoistReadWrite (HoistableRead read, HoistableWrite write, BlockArgument tensorBBArg)
Mechanical hoisting of a matching HoistableRead / HoistableWrite pair.
template<typename... OpTypeList>
static bool backwardsSliceOnlyHasOpsOfType (scf::ForOp outerLimit, Value v)
Return success if v is a value that is only transitively defined by ops of type in OpTypeList.
bool isDefinedOutsideOrConstant (scf::ForOp outer, Value v)
static Value buildLoopIterationCount (OpBuilder &b, scf::ForOp outer, scf::ForOp forOp)
Return the current iteration number in the loop (iv - lb).ceilDiv(step).
static ConstraintsSet initLoopIvsAndBounds (ArrayRef< Operation *> loops)
Given a set of loops, assumed to be scf::ForOp, create a constraint set containing the inequalities iv - lb >= 0 and -iv + ub >= 0 for each loop.
static LogicalResult foldUpperBoundsIntoConstraintsSet (ConstraintsSet &constraints, scf::ForOp outerLimit, ArrayRef< Operation *> loops)
For each loop in loops, determine the ops involved in the construction of its upper bound—up to the outerLimit loop— and fold them as new inequalities in the constraint set.
static LogicalResult computeBounds (scf::ForOp outer, ArrayRef< Operation *> packingLoops, SmallVector< AffineMap > &lbs, SmallVector< AffineMap > &ubs)
Compute dynamic tensor sizes, independent of any value defined inside outer and such that every n-D iteration of the packingLoops has its own space (so that each packed buffer has a storage location).
static LogicalResult hoistPaddingOnTensorsPrerequisites (linalg::PadTensorOp padTensorOp, int nLevels, SetVector< Operation *> &backwardSlice, SetVector< Operation *> &packingLoops, SmallVector< Value > &dynamicTensorSizes)
Ensure prerequisites that guarantee pad op hoisting can occur.
Macro Definition Documentation
DBGS
#define DBGS () (dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 38 of file Hoisting.cpp.
Referenced by backwardsSliceOnlyHasOpsOfType(), findMatchingTransferRead(), hoistReadWrite(), mlir::linalg::hoistRedundantVectorTransfers(), and mlir::linalg::hoistRedundantVectorTransfersOnTensor().
DEBUG_TYPE
#define DEBUG_TYPE "linalg-hoisting"
Definition at line 36 of file Hoisting.cpp.
Function Documentation
backwardsSliceOnlyHasOpsOfType()
template<typename... OpTypeList> static bool backwardsSliceOnlyHasOpsOfType (scf::ForOp outerLimit, Value v) static
Return success if v is a value that is only transitively defined by ops of type in OpTypeList.
Definition at line 514 of file Hoisting.cpp.
References DBGS, mlir::getBackwardSlice(), and op.
buildLoopIterationCount()
static Value buildLoopIterationCount (OpBuilder & b, scf::ForOp outer, scf::ForOp forOp) static
Return the current iteration number in the loop (iv - lb).ceilDiv(step).
The returned Value is guaranteed not to depend on any loop comprised in [outer, forOp]. Return null if such a loop-independent quantity cannot be computed.
Definition at line 539 of file Hoisting.cpp.
References mlir::bindDims(), mlir::bindSymbols(), mlir::ceilDiv(), mlir::OpBuilder::createOrFold(), isDefinedOutsideOrConstant(), and loc.
Referenced by mlir::linalg::hoistPaddingOnTensors().
computeBounds()
static LogicalResult computeBounds (scf::ForOp outer, ArrayRef< Operation *> packingLoops, SmallVector< AffineMap > & lbs, SmallVector< AffineMap > & ubs) static
Compute dynamic tensor sizes, independent of any value defined inside outer and such that every n-D iteration of the packingLoops has its own space (so that each packed buffer has a storage location).
This is achieved by computing the extent for each of the packing loops.
Definition at line 661 of file Hoisting.cpp.
References mlir::failed(), mlir::failure(), foldUpperBoundsIntoConstraintsSet(), mlir::FlatAffineConstraints::getSliceBounds(), initLoopIvsAndBounds(), and mlir::success().
Referenced by hoistPaddingOnTensorsPrerequisites().
findMatchingTransferRead()
static HoistableRead findMatchingTransferRead (HoistableWrite write, Value srcTensor) static
Look for a HoistableRead, in the given tensor uses, accessing the same offset as the HoistableWrite.
Definition at line 99 of file Hoisting.cpp.
References DBGS, mlir::Value::getUsers(), mlir::Operation::getUsers(), and sameOffsetsSizesAndStrides().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().
foldUpperBoundsIntoConstraintsSet()
static LogicalResult foldUpperBoundsIntoConstraintsSet (ConstraintsSet & constraints, scf::ForOp outerLimit, ArrayRef< Operation *> loops) static
For each loop in loops, determine the ops involved in the construction of its upper bound—up to the outerLimit loop— and fold them as new inequalities in the constraint set.
This is achieved by computing the backwardSlice of the loop's upper bound and iteratively folding each op in reverse topological order to guarantee use-def ordering. As operations are folded in, their result is projected out of the constraints set. The following operations are supported:
scf::ForOp are simply skipped.
AffineApplyOp are composed to replace the result by an equality.
AffineMinOp are composed by adding each entry as an upper bound. If any other operation is met, return failure.
Definition at line 601 of file Hoisting.cpp.
References mlir::ConstraintsSet::composeAffineApply(), mlir::ConstraintsSet::composeMin(), mlir::ConstraintsSet::ensureIdOfType(), mlir::failed(), mlir::failure(), mlir::getBackwardSlice(), mlir::Operation::getOperands(), mlir::Operation::getResult(), mlir::Operation::getResults(), isDefinedOutsideOrConstant(), op, mlir::FlatAffineConstraints::projectOut(), and mlir::success().
Referenced by computeBounds(), and hoistPaddingOnTensorsPrerequisites().
getLoopInvariantTransferWriteOpDefining()
static HoistableWrite getLoopInvariantTransferWriteOpDefining (scf::ForOp forOp, OpOperand & yieldOperand) static
Return the forOp-invariant HoistableWrite that produces yieldOperand.
Return the null HoistableWrite() if it is not comprised of a vector.transfer_write + optional insert_slice or if any of the indexings is forOp-dependent.
Definition at line 223 of file Hoisting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), and mlir::OpOperand::getOperandNumber().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().
hoistPaddingOnTensorsPrerequisites()
static LogicalResult hoistPaddingOnTensorsPrerequisites (linalg::PadTensorOp padTensorOp, int nLevels, SetVector< Operation *> & backwardSlice, SetVector< Operation *> & packingLoops, SmallVector< Value > & dynamicTensorSizes) static
Ensure prerequisites that guarantee pad op hoisting can occur.
Return failure in the cases when we cannot perform hoisting; i.e. if either:
There exists a use of padTensorOp that is not a linalg input operand.
There isn't an enclosing outermostEnclosingForOp loop.
There exists an op with a region that is dominated by outermostEnclosingForOp and that isn't a LoopLikeInterface or a LinalgOp.
There exists an op with side effects that is dominated by outermostEnclosingForOp and that isn't a LoopLikeInterface.
The lower bound, upper bound and step of all the loops involved in the hoisting can be
While ensuring prerequisites:
Fill the backwardSlice to contain the topologically sorted ops dominated by outermostEnclosingForOp.
Fill the packingLoops to contain only the enclosing loops of backwardSlice whose IV is actually used in computing padding. Loops that remain in backwardSlice but that are not in packingLoops are dimensions of reuse.
Definition at line 696 of file Hoisting.cpp.
References mlir::bindDims(), mlir::bindSymbols(), mlir::canonicalizeMapAndOperands(), mlir::ceilDiv(), computeBounds(), mlir::DominanceInfo::dominates(), mlir::failed(), mlir::failure(), foldUpperBoundsIntoConstraintsSet(), mlir::getBackwardSlice(), mlir::Operation::getNumRegions(), mlir::Operation::getParentOfType(), mlir::Operation::getUsers(), initLoopIvsAndBounds(), op, and mlir::success().
Referenced by mlir::linalg::hoistPaddingOnTensors().
hoistReadWrite()
static void hoistReadWrite (HoistableRead read, HoistableWrite write, BlockArgument tensorBBArg) static
Mechanical hoisting of a matching HoistableRead / HoistableWrite pair.
Definition at line 261 of file Hoisting.cpp.
References mlir::cloneWithNewYields(), DBGS, mlir::failed(), mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().
initLoopIvsAndBounds()
static ConstraintsSet initLoopIvsAndBounds (ArrayRef< Operation *> loops) static
Given a set of loops, assumed to be scf::ForOp, create a constraint set containing the inequalities iv - lb >= 0 and -iv + ub >= 0 for each loop.
Definition at line 558 of file Hoisting.cpp.
References mlir::FlatAffineConstraints::addDimId(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimIds(), and op.
Referenced by computeBounds(), and hoistPaddingOnTensorsPrerequisites().
isDefinedOutsideOrConstant()
bool isDefinedOutsideOrConstant (scf::ForOp outer, Value v)
Definition at line 531 of file Hoisting.cpp.
References mlir::Value::getDefiningOp().
Referenced by buildLoopIterationCount(), and foldUpperBoundsIntoConstraintsSet().
isEqualOffsetSizeOrStride()
static bool isEqualOffsetSizeOrStride (OpFoldResult op1, OpFoldResult op2) static
Return true if op1 and op2 are the same constant or the same SSA value.
Definition at line 59 of file Hoisting.cpp.
References mlir::Attribute::dyn_cast(), mlir::Attribute::dyn_cast_or_null(), mlir::getConstantIntValue(), and mlir::Value::getDefiningOp().
Referenced by sameOffsetsSizesAndStrides().
sameOffsetsSizesAndStrides()
static bool sameOffsetsSizesAndStrides (tensor::ExtractSliceOp s, tensor::InsertSliceOp si) static
Return true is all offsets, sizes and strides are equal.
Definition at line 77 of file Hoisting.cpp.
References isEqualOffsetSizeOrStride().
Referenced by bufferizesToMemoryWrite(), and findMatchingTransferRead().
tensorChunkAccessedByUnknownOp()
static bool tensorChunkAccessedByUnknownOp (HoistableWrite write, HoistableRead candidateRead, BlockArgument tensorArg) static
Check if the chunk of data inserted by the HoistableWrite are read by any other op than the HoistableRead candidate.
Definition at line 162 of file Hoisting.cpp.
References mlir::Value::getUses().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().