MLIR: include/mlir/CAPI/Diagnostics.h File Reference
Diagnostics.h File Reference
#include "mlir-c/Diagnostics.h"
#include <cassert>
Namespaces
namespace mlir
Include the generated interface declarations.
Functions
mlir::Diagnostic & unwrap (MlirDiagnostic diagnostic)
MlirDiagnostic wrap (mlir::Diagnostic &diagnostic)
Function Documentation
unwrap()
mlir::Diagnostic & unwrap (MlirDiagnostic diagnostic) inline
Definition at line 19 of file Diagnostics.h.
References MlirDiagnostic::ptr.
Referenced by DEFINE_C_API_PTR_METHODS(), getDenseAttribute(), getDenseResource(), getDenseResourceVal(), mlir::ExternalPass::initialize(), mlir::ExternalConversionPattern::matchAndRewrite(), mlir::ExternalRewritePattern::matchAndRewrite(), MLIR_DEFINE_CAPI_DIALECT_REGISTRATION(), MLIR_DEFINE_CAPI_DIALECT_REGISTRATION(), mlirAffineAddExprGet(), mlirAffineBinaryOpExprGetLHS(), mlirAffineBinaryOpExprGetRHS(), mlirAffineCeilDivExprGet(), mlirAffineConstantExprGet(), mlirAffineConstantExprGetValue(), mlirAffineDimExprGet(), mlirAffineDimExprGetPosition(), mlirAffineExprCompose(), mlirAffineExprDump(), mlirAffineExprEqual(), mlirAffineExprGetContext(), mlirAffineExprGetLargestKnownDivisor(), mlirAffineExprIsAAdd(), mlirAffineExprIsABinary(), mlirAffineExprIsACeilDiv(), mlirAffineExprIsAConstant(), mlirAffineExprIsADim(), mlirAffineExprIsAFloorDiv(), mlirAffineExprIsAMod(), mlirAffineExprIsAMul(), mlirAffineExprIsASymbol(), mlirAffineExprIsFunctionOfDim(), mlirAffineExprIsMultipleOf(), mlirAffineExprIsPureAffine(), mlirAffineExprIsSymbolicOrConstant(), mlirAffineExprPrint(), mlirAffineExprShiftDims(), mlirAffineExprShiftSymbols(), mlirAffineFloorDivExprGet(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapCompressUnusedSymbols(), mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapEqual(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetResult(), mlirAffineMapGetSingleConstantResult(), mlirAffineMapGetSubMap(), mlirAffineMapIsEmpty(), mlirAffineMapIsIdentity(), mlirAffineMapIsMinorIdentity(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapIsSingleConstant(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapPrint(), mlirAffineMapReplace(), mlirAffineMapZeroResultGet(), mlirAffineModExprGet(), mlirAffineMulExprGet(), mlirAffineSymbolExprGet(), mlirAffineSymbolExprGetPosition(), mlirAMDGPUTDMBaseTypeGet(), mlirAMDGPUTDMDescriptorTypeGet(), mlirAMDGPUTDMGatherBaseTypeGet(), mlirAnyQuantizedTypeGet(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), mlirAttributeIsAAffineMap(), mlirAttributeIsAArray(), mlirAttributeIsABool(), mlirAttributeIsADenseBoolArray(), mlirAttributeIsADenseElements(), mlirAttributeIsADenseF32Array(), mlirAttributeIsADenseF64Array(), mlirAttributeIsADenseFPElements(), mlirAttributeIsADenseI16Array(), mlirAttributeIsADenseI32Array(), mlirAttributeIsADenseI64Array(), mlirAttributeIsADenseI8Array(), mlirAttributeIsADenseIntElements(), mlirAttributeIsADenseResourceElements(), mlirAttributeIsADictionary(), mlirAttributeIsADynamicAttr(), mlirAttributeIsAElements(), mlirAttributeIsAEmitCCmpPredicate(), mlirAttributeIsAEmitCOpaque(), mlirAttributeIsAFlatSymbolRef(), mlirAttributeIsAFloat(), mlirAttributeIsAGPUObjectAttr(), mlirAttributeIsAInteger(), mlirAttributeIsAIntegerSet(), mlirAttributeIsALocation(), mlirAttributeIsAOpaque(), mlirAttributeIsASparseElements(), mlirAttributeIsASparseTensorEncodingAttr(), mlirAttributeIsAStridedLayout(), mlirAttributeIsAString(), mlirAttributeIsASymbolRef(), mlirAttributeIsAType(), mlirAttributeIsAUnit(), mlirBF16TypeGet(), mlirBlockCreate(), mlirBlockInsertOwnedOperation(), mlirBlockInsertOwnedOperationAfter(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirCalibratedQuantizedTypeGet(), mlirCalibratedQuantizedTypeGetMax(), mlirCalibratedQuantizedTypeGetMin(), mlirComplexAttrDoubleGet(), mlirComplexAttrDoubleGetChecked(), mlirComplexAttrGetImagDouble(), mlirComplexAttrGetRealDouble(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirConditionallySpeculatableOpInterfaceAttachFallbackModel(), mlirConditionallySpeculatableOpInterfaceGetSpeculatability(), mlirContextAttachDiagnosticHandler(), mlirContextDetachDiagnosticHandler(), mlirCreateExternalPass(), mlirDenseArrayGetNumElements(), mlirDenseBoolArrayGet(), mlirDenseBoolArrayGetElement(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetBoolSplatValue(), mlirDenseElementsAttrGetBoolValue(), mlirDenseElementsAttrGetDoubleSplatValue(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatSplatValue(), mlirDenseElementsAttrGetFloatValue(), mlirDenseElementsAttrGetIndexValue(), mlirDenseElementsAttrGetInt16Value(), mlirDenseElementsAttrGetInt32SplatValue(), mlirDenseElementsAttrGetInt32Value(), mlirDenseElementsAttrGetInt64SplatValue(), mlirDenseElementsAttrGetInt64Value(), mlirDenseElementsAttrGetInt8SplatValue(), mlirDenseElementsAttrGetInt8Value(), mlirDenseElementsAttrGetRawData(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrGetUInt16Value(), mlirDenseElementsAttrGetUInt32SplatValue(), mlirDenseElementsAttrGetUInt32Value(), mlirDenseElementsAttrGetUInt64SplatValue(), mlirDenseElementsAttrGetUInt64Value(), mlirDenseElementsAttrGetUInt8SplatValue(), mlirDenseElementsAttrGetUInt8Value(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrRawBufferGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), mlirDenseF32ArrayGet(), mlirDenseF32ArrayGetElement(), mlirDenseF64ArrayGet(), mlirDenseF64ArrayGetElement(), mlirDenseI16ArrayGet(), mlirDenseI16ArrayGetElement(), mlirDenseI32ArrayGet(), mlirDenseI32ArrayGetElement(), mlirDenseI64ArrayGet(), mlirDenseI64ArrayGetElement(), mlirDenseI8ArrayGet(), mlirDenseI8ArrayGetElement(), mlirDiagnosticGetLocation(), mlirDiagnosticGetNote(), mlirDiagnosticGetNumNotes(), mlirDiagnosticGetSeverity(), mlirDiagnosticPrint(), mlirDialectIsAExtensibleDialect(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetNumElements(), mlirDistinctAttrCreate(), mlirDominanceInfoCreate(), mlirDominanceInfoDestroy(), mlirDominanceInfoDominatesBlock(), mlirDominanceInfoDominatesOperation(), mlirDominanceInfoFindNearestCommonDominator(), mlirDominanceInfoInvalidate(), mlirDominanceInfoIsReachableFromEntry(), mlirDominanceInfoProperlyDominatesBlock(), mlirDominanceInfoProperlyDominatesOperation(), mlirDominanceInfoValueDominates(), mlirDominanceInfoValueProperlyDominates(), mlirDynamicAttrDefinitionGetDialect(), mlirDynamicAttrDefinitionGetName(), mlirDynamicAttrDefinitionGetTypeID(), mlirDynamicAttrGet(), mlirDynamicAttrGetAttrDef(), mlirDynamicAttrGetNumParams(), mlirDynamicAttrGetParam(), mlirDynamicOpTraitAttach(), mlirDynamicOpTraitCreate(), mlirDynamicOpTraitDestroy(), mlirDynamicTypeDefinitionGetDialect(), mlirDynamicTypeDefinitionGetName(), mlirDynamicTypeDefinitionGetTypeID(), mlirDynamicTypeGet(), mlirDynamicTypeGetNumParams(), mlirDynamicTypeGetParam(), mlirDynamicTypeGetTypeDef(), mlirElementsAttrGetNumElements(), mlirElementsAttrGetValue(), mlirElementsAttrIsValidIndex(), mlirEmitCArrayTypeGet(), mlirEmitCCmpPredicateAttrGet(), mlirEmitCCmpPredicateAttrGetValue(), mlirEmitCLValueTypeGet(), mlirEmitCOpaqueAttrGet(), mlirEmitCOpaqueAttrGetValue(), mlirEmitCOpaqueTypeGet(), mlirEmitCPointerTypeGet(), mlirEmitCPtrDiffTTypeGet(), mlirEmitCSignedSizeTTypeGet(), mlirEmitCSizeTTypeGet(), mlirEmitError(), mlirExecutionEngineCreate(), mlirExecutionEngineDestroy(), mlirExecutionEngineDumpToObjectFile(), mlirExecutionEngineInitialize(), mlirExecutionEngineInvokePacked(), mlirExecutionEngineLookup(), mlirExecutionEngineLookupPacked(), mlirExecutionEngineRegisterSymbol(), mlirExtensibleDialectLookupAttrDefinition(), mlirExtensibleDialectLookupTypeDefinition(), mlirExternalPassSignalFailure(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloat4E2M1FNTypeGet(), mlirFloat6E2M3FNTypeGet(), mlirFloat6E3M2FNTypeGet(), mlirFloat8E3M4TypeGet(), mlirFloat8E4M3B11FNUZTypeGet(), mlirFloat8E4M3FNTypeGet(), mlirFloat8E4M3FNUZTypeGet(), mlirFloat8E4M3TypeGet(), mlirFloat8E5M2FNUZTypeGet(), mlirFloat8E5M2TypeGet(), mlirFloat8E8M0FNUTypeGet(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFloatAttrGetValueDouble(), mlirFloatTypeGetWidth(), mlirFuncSetArgAttr(), mlirFuncSetResultAttr(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetNumInputs(), mlirFunctionTypeGetNumResults(), mlirFunctionTypeGetResult(), mlirGPUAsyncTokenTypeGet(), mlirGPUObjectAttrGet(), mlirGPUObjectAttrGetFormat(), mlirGPUObjectAttrGetKernels(), mlirGPUObjectAttrGetObject(), mlirGPUObjectAttrGetProperties(), mlirGPUObjectAttrGetTarget(), mlirGPUObjectAttrGetWithKernels(), mlirGPUObjectAttrHasKernels(), mlirGPUObjectAttrHasProperties(), mlirIndexTypeGet(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirIntegerAttrGet(), mlirIntegerAttrGetFromWords(), mlirIntegerAttrGetValueBitWidth(), mlirIntegerAttrGetValueInt(), mlirIntegerAttrGetValueNumWords(), mlirIntegerAttrGetValueSInt(), mlirIntegerAttrGetValueUInt(), mlirIntegerAttrGetValueWords(), mlirIntegerSetAttrGet(), mlirIntegerSetAttrGetValue(), mlirIntegerSetDump(), mlirIntegerSetEmptyGet(), mlirIntegerSetEqual(), mlirIntegerSetGetConstraint(), mlirIntegerSetGetContext(), mlirIntegerSetGetNumConstraints(), mlirIntegerSetGetNumDims(), mlirIntegerSetGetNumEqualities(), mlirIntegerSetGetNumInequalities(), mlirIntegerSetGetNumInputs(), mlirIntegerSetGetNumSymbols(), mlirIntegerSetIsCanonicalEmpty(), mlirIntegerSetIsConstraintEq(), mlirIntegerSetPrint(), mlirIntegerSetReplaceGet(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirIRDLVariadicityArrayAttrGet(), mlirIRDLVariadicityAttrGet(), mlirLinalgFillBuiltinNamedOpRegion(), mlirLinalgGetIndexingMapsAttribute(), mlirLinalgInferContractionDimensions(), mlirLinalgInferContractionDimensionsFromMaps(), mlirLinalgInferConvolutionDimensions(), mlirLinalgInferConvolutionDimensionsFromMaps(), mlirLinalgIsAContractionOp(), mlirLinalgIsAConvolutionOp(), mlirLLVMArrayTypeGet(), mlirLLVMArrayTypeGetElementType(), mlirLLVMArrayTypeGetNumElements(), mlirLLVMAttrIsAMDConstantAttr(), mlirLLVMAttrIsAMDFuncAttr(), mlirLLVMAttrIsAMDNodeAttr(), mlirLLVMAttrIsAMDStringAttr(), mlirLLVMCConvAttrGet(), mlirLLVMComdatAttrGet(), mlirLLVMDIAnnotationAttrGet(), mlirLLVMDIBasicTypeAttrGet(), mlirLLVMDICompileUnitAttrGet(), mlirLLVMDICompileUnitAttrGetRecSelf(), mlirLLVMDICompositeTypeAttrGet(), mlirLLVMDICompositeTypeAttrGetRecSelf(), mlirLLVMDIDerivedTypeAttrGet(), mlirLLVMDIDerivedTypeAttrGetBaseType(), mlirLLVMDIExpressionAttrGet(), mlirLLVMDIExpressionElemAttrGet(), mlirLLVMDIFileAttrGet(), mlirLLVMDIFlagsAttrGet(), mlirLLVMDIImportedEntityAttrGet(), mlirLLVMDILexicalBlockAttrGet(), mlirLLVMDILexicalBlockFileAttrGet(), mlirLLVMDILocalVariableAttrGet(), mlirLLVMDIModuleAttrGet(), mlirLLVMDIModuleAttrGetScope(), mlirLLVMDINullTypeAttrGet(), mlirLLVMDIStringTypeAttrGet(), mlirLLVMDISubprogramAttrGet(), mlirLLVMDISubprogramAttrGetCompileUnit(), mlirLLVMDISubprogramAttrGetFile(), mlirLLVMDISubprogramAttrGetLine(), mlirLLVMDISubprogramAttrGetRecSelf(), mlirLLVMDISubprogramAttrGetScope(), mlirLLVMDISubprogramAttrGetScopeLine(), mlirLLVMDISubprogramAttrGetType(), mlirLLVMDISubroutineTypeAttrGet(), mlirLLVMFunctionTypeGet(), mlirLLVMFunctionTypeGetInput(), mlirLLVMFunctionTypeGetNumInputs(), mlirLLVMFunctionTypeGetReturnType(), mlirLLVMFunctionTypeIsVarArg(), mlirLLVMLinkageAttrGet(), mlirLLVMMDConstantAttrGet(), mlirLLVMMDConstantAttrGetValue(), mlirLLVMMDFuncAttrGet(), mlirLLVMMDFuncAttrGetName(), mlirLLVMMDNodeAttrGet(), mlirLLVMMDNodeAttrGetNumOperands(), mlirLLVMMDNodeAttrGetOperand(), mlirLLVMMDStringAttrGet(), mlirLLVMMDStringAttrGetValue(), mlirLLVMPointerTypeGet(), mlirLLVMPointerTypeGetAddressSpace(), mlirLlvmRawFdOStreamDestroy(), mlirLlvmRawFdOStreamWrite(), mlirLLVMStructTypeGetElementType(), mlirLLVMStructTypeGetIdentifier(), mlirLLVMStructTypeGetNumElementTypes(), mlirLLVMStructTypeIdentifiedGet(), mlirLLVMStructTypeIdentifiedNewGet(), mlirLLVMStructTypeIsLiteral(), mlirLLVMStructTypeIsOpaque(), mlirLLVMStructTypeIsPacked(), mlirLLVMStructTypeLiteralGet(), mlirLLVMStructTypeLiteralGetChecked(), mlirLLVMStructTypeOpaqueGet(), mlirLLVMStructTypeSetBody(), mlirLlvmThreadPoolDestroy(), mlirLlvmThreadPoolGetMaxConcurrency(), mlirLLVMVoidTypeGet(), mlirLoadIRDLDialects(), mlirMemoryEffectsOpInterfaceAttachFallbackModel(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetChecked(), mlirMemRefTypeGetLayout(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetStridesAndOffset(), mlirMergeSymbolsIntoFromClone(), mlirNoneTypeGet(), mlirNVGPUTensorMapDescriptorTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOpaqueTypeGet(), mlirOpaqueTypeGetData(), mlirOpaqueTypeGetDialectNamespace(), mlirOpConversionPatternCreate(), mlirOperationCreate(), mlirOperationImplementsInterface(), mlirOperationImplementsInterfaceStatic(), mlirOpPassManagerAddOwnedPass(), mlirOpPassManagerAddPipeline(), mlirOpPassManagerGetNestedUnder(), mlirParsePassPipeline(), mlirPassManagerAddOwnedPass(), mlirPassManagerCreate(), mlirPassManagerCreateOnOperation(), mlirPassManagerDestroy(), mlirPassManagerEnableIRPrinting(), mlirPassManagerEnableStatistics(), mlirPassManagerEnableTiming(), mlirPassManagerEnableVerifier(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPassManagerRunOnOp(), mlirPatternDescriptorOpInterfaceAttachFallbackModel(), mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirPostDominanceInfoCreate(), mlirPostDominanceInfoDestroy(), mlirPostDominanceInfoInvalidate(), mlirPostDominanceInfoPostDominatesBlock(), mlirPostDominanceInfoPostDominatesOperation(), mlirPostDominanceInfoProperlyPostDominatesBlock(), mlirPostDominanceInfoProperlyPostDominatesOperation(), mlirPrintPassPipeline(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetFlags(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetStorageType(), mlirQuantizedTypeGetStorageTypeIntegralWidth(), mlirQuantizedTypeGetStorageTypeMax(), mlirQuantizedTypeGetStorageTypeMin(), mlirQuantizedTypeIsCompatibleExpressedType(), mlirQuantizedTypeIsSigned(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRankedTensorTypeGetEncoding(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegisterAllDialects(), mlirRegisterAllLLVMTranslations(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirShapedTypeIsStaticDim(), mlirSimplifyAffineExpr(), mlirSMTAttrCheckBVCmpPredicate(), mlirSMTAttrCheckIntPredicate(), mlirSMTAttrGetBitVector(), mlirSMTAttrGetBVCmpPredicate(), mlirSMTAttrGetIntPredicate(), mlirSMTAttrIsASMTAttribute(), mlirSMTTypeGetArray(), mlirSMTTypeGetBitVector(), mlirSMTTypeGetBool(), mlirSMTTypeGetInt(), mlirSMTTypeGetSMTFunc(), mlirSMTTypeGetSort(), mlirSMTTypeIsAArray(), mlirSMTTypeIsABitVector(), mlirSMTTypeIsABool(), mlirSMTTypeIsAInt(), mlirSMTTypeIsAnyNonFuncSMTValueType(), mlirSMTTypeIsAnySMTValueType(), mlirSMTTypeIsASMTFunc(), mlirSMTTypeIsASort(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetCrdWidth(), mlirSparseTensorEncodingAttrGetDimToLvl(), mlirSparseTensorEncodingAttrGetExplicitVal(), mlirSparseTensorEncodingAttrGetImplicitVal(), mlirSparseTensorEncodingAttrGetLvlToDim(), mlirSparseTensorEncodingAttrGetLvlType(), mlirSparseTensorEncodingAttrGetPosWidth(), mlirSparseTensorEncodingGetLvlRank(), mlirStridedLayoutAttrGet(), mlirStridedLayoutAttrGetNumStrides(), mlirStridedLayoutAttrGetOffset(), mlirStridedLayoutAttrGetStride(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetNumNestedReferences(), mlirSymbolRefAttrGetRootReference(), mlirTF32TypeGet(), mlirTransformAnyOpTypeGet(), mlirTransformAnyParamTypeGet(), mlirTransformAnyValueTypeGet(), mlirTransformApplyNamedSequence(), mlirTransformConsumesHandle(), mlirTransformModifiesPayload(), mlirTransformOnlyReadsHandle(), mlirTransformOnlyReadsPayload(), mlirTransformOperationTypeGet(), mlirTransformOperationTypeGetOperationName(), mlirTransformOpInterfaceAttachFallbackModel(), mlirTransformOptionsDestroy(), mlirTransformOptionsEnableExpensiveChecks(), mlirTransformOptionsEnforceSingleTopLevelTransformOp(), mlirTransformOptionsGetEnforceSingleTopLevelTransformOp(), mlirTransformOptionsGetExpensiveChecksEnabled(), mlirTransformParamTypeGet(), mlirTransformParamTypeGetType(), mlirTransformProducesHandle(), mlirTransformResultsSetOps(), mlirTransformResultsSetParams(), mlirTransformResultsSetValues(), mlirTransformRewriterAsBase(), mlirTransformStateForEachParam(), mlirTransformStateForEachPayloadOp(), mlirTransformStateForEachPayloadValue(), mlirTranslateModuleToLLVMIR(), mlirTranslateOperationToSMTLIB(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeFromLLVMIRTranslatorDestroy(), mlirTypeFromLLVMIRTranslatorTranslateType(), mlirTypeIDAllocatorAllocateTypeID(), mlirTypeIDAllocatorDestroy(), mlirTypeIDEqual(), mlirTypeIDHashValue(), mlirTypeIsAAMDGPUTDMBaseType(), mlirTypeIsAAMDGPUTDMDescriptorType(), mlirTypeIsAAMDGPUTDMGatherBaseType(), mlirTypeIsAAnyQuantizedType(), mlirTypeIsABF16(), mlirTypeIsACalibratedQuantizedType(), mlirTypeIsAComplex(), mlirTypeIsADynamicType(), mlirTypeIsAEmitCArrayType(), mlirTypeIsAEmitCLValueType(), mlirTypeIsAEmitCOpaqueType(), mlirTypeIsAEmitCPointerType(), mlirTypeIsAEmitCPtrDiffTType(), mlirTypeIsAEmitCSignedSizeTType(), mlirTypeIsAEmitCSizeTType(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAFloat(), mlirTypeIsAFloat4E2M1FN(), mlirTypeIsAFloat6E2M3FN(), mlirTypeIsAFloat6E3M2FN(), mlirTypeIsAFloat8E3M4(), mlirTypeIsAFloat8E4M3(), mlirTypeIsAFloat8E4M3B11FNUZ(), mlirTypeIsAFloat8E4M3FN(), mlirTypeIsAFloat8E4M3FNUZ(), mlirTypeIsAFloat8E5M2(), mlirTypeIsAFloat8E5M2FNUZ(), mlirTypeIsAFloat8E8M0FNU(), mlirTypeIsAFunction(), mlirTypeIsAGPUAsyncTokenType(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsALLVMArrayType(), mlirTypeIsALLVMFunctionType(), mlirTypeIsALLVMPointerType(), mlirTypeIsALLVMStructType(), mlirTypeIsAMemRef(), mlirTypeIsANone(), mlirTypeIsANVGPUTensorMapDescriptorType(), mlirTypeIsAOpaque(), mlirTypeIsAPDLAttributeType(), mlirTypeIsAPDLOperationType(), mlirTypeIsAPDLRangeType(), mlirTypeIsAPDLType(), mlirTypeIsAPDLTypeType(), mlirTypeIsAPDLValueType(), mlirTypeIsAQuantizedType(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATensor(), mlirTypeIsATF32(), mlirTypeIsATransformAnyParamType(), mlirTypeIsATransformAnyValueType(), mlirTypeIsATransformOperationType(), mlirTypeIsATransformParamType(), mlirTypeIsATuple(), mlirTypeIsAUniformQuantizedPerAxisType(), mlirTypeIsAUniformQuantizedSubChannelType(), mlirTypeIsAUniformQuantizedType(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeToLLVMIRTranslatorDestroy(), mlirTypeToLLVMIRTranslatorTranslateType(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedPerAxisTypeGetNumDims(), mlirUniformQuantizedPerAxisTypeGetQuantizedDimension(), mlirUniformQuantizedPerAxisTypeGetScale(), mlirUniformQuantizedPerAxisTypeGetZeroPoint(), mlirUniformQuantizedPerAxisTypeIsFixedPoint(), mlirUniformQuantizedSubChannelTypeGet(), mlirUniformQuantizedSubChannelTypeGetBlockSize(), mlirUniformQuantizedSubChannelTypeGetNumBlockSizes(), mlirUniformQuantizedSubChannelTypeGetQuantizedDimension(), mlirUniformQuantizedSubChannelTypeGetScales(), mlirUniformQuantizedSubChannelTypeGetZeroPoints(), mlirUniformQuantizedTypeGet(), mlirUniformQuantizedTypeGetScale(), mlirUniformQuantizedTypeGetZeroPoint(), mlirUniformQuantizedTypeIsFixedPoint(), mlirUnitAttrGet(), mlirUnmanagedDenseResourceElementsAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirVectorTypeGet(), mlirVectorTypeGetChecked(), mlirVectorTypeGetScalable(), mlirVectorTypeGetScalableChecked(), mlirVectorTypeIsDimScalable(), mlirVectorTypeIsScalable(), unwrapList(), mlir::ExternalDynamicOpTrait::verifyRegionTrait(), and mlir::ExternalDynamicOpTrait::verifyTrait().
wrap()
MlirDiagnostic wrap (mlir::Diagnostic & diagnostic) inline
Definition at line 24 of file Diagnostics.h.
Referenced by TransformOpInterfaceFallbackModel::allowsRepeatedHandleOperands(), TransformOpInterfaceFallbackModel::apply(), DEFINE_C_API_PTR_METHODS(), DEFINE_C_API_PTR_METHODS(), getDenseAttribute(), getDenseResource(), mlir::ExternalPass::getDependentDialects(), MemoryEffectOpInterfaceFallbackModel::getEffects(), ConditionallySpeculatableOpInterfaceFallbackModel::getSpeculatability(), mlir::ExternalPass::initialize(), mlir::sparse_tensor::makeTraverseSubSectIterator(), mlir::ExternalConversionPattern::matchAndRewrite(), mlir::ExternalRewritePattern::matchAndRewrite(), mlirAffineAddExprGet(), mlirAffineBinaryOpExprGetLHS(), mlirAffineBinaryOpExprGetRHS(), mlirAffineCeilDivExprGet(), mlirAffineConstantExprGet(), mlirAffineDimExprGet(), mlirAffineExprCompose(), mlirAffineExprGetContext(), mlirAffineExprShiftDims(), mlirAffineExprShiftSymbols(), mlirAffineFloorDivExprGet(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetName(), mlirAffineMapAttrGetTypeID(), mlirAffineMapAttrGetValue(), mlirAffineMapCompressUnusedSymbols(), mlirAffineMapConstantGet(), mlirAffineMapEmptyGet(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetResult(), mlirAffineMapGetSubMap(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapReplace(), mlirAffineMapZeroResultGet(), mlirAffineModExprGet(), mlirAffineMulExprGet(), mlirAffineSymbolExprGet(), mlirAMDGPUTDMBaseTypeGet(), mlirAMDGPUTDMBaseTypeGetName(), mlirAMDGPUTDMBaseTypeGetTypeID(), mlirAMDGPUTDMDescriptorTypeGet(), mlirAMDGPUTDMDescriptorTypeGetName(), mlirAMDGPUTDMDescriptorTypeGetTypeID(), mlirAMDGPUTDMGatherBaseTypeGet(), mlirAMDGPUTDMGatherBaseTypeGetName(), mlirAMDGPUTDMGatherBaseTypeGetTypeID(), mlirAnyQuantizedTypeGet(), mlirAnyQuantizedTypeGetName(), mlirAnyQuantizedTypeGetTypeID(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetName(), mlirArrayAttrGetTypeID(), mlirAsmStateCreateForOperation(), mlirAsmStateCreateForValue(), mlirAttributeGetContext(), mlirAttributeGetDialect(), mlirAttributeGetType(), mlirAttributeGetTypeID(), mlirAttributeParseGet(), mlirBF16TypeGet(), mlirBF16TypeGetName(), mlirBFloat16TypeGetTypeID(), mlirBlockAddArgument(), mlirBlockArgumentGetOwner(), mlirBlockCreate(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockGetPredecessor(), mlirBlockGetSuccessor(), mlirBlockGetTerminator(), mlirBlockInsertArgument(), mlirBoolAttrGet(), mlirBytecodeWriterConfigCreate(), mlirCalibratedQuantizedTypeGet(), mlirCalibratedQuantizedTypeGetName(), mlirCalibratedQuantizedTypeGetTypeID(), mlirComplexAttrDoubleGet(), mlirComplexAttrDoubleGetChecked(), mlirComplexAttrGetTypeID(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirComplexTypeGetName(), mlirComplexTypeGetTypeID(), mlirConditionallySpeculatableOpInterfaceTypeID(), mlirContextAttachDiagnosticHandler(), mlirContextCreate(), mlirContextCreateWithRegistry(), mlirContextCreateWithThreading(), mlirContextGetOrLoadDialect(), mlirContextGetThreadPool(), mlirCreateExternalPass(), mlirDenseArrayAttrGetTypeID(), mlirDenseBoolArrayGet(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrRawBufferGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), mlirDenseF32ArrayGet(), mlirDenseF64ArrayGet(), mlirDenseI16ArrayGet(), mlirDenseI32ArrayGet(), mlirDenseI64ArrayGet(), mlirDenseI8ArrayGet(), mlirDenseResourceElementsAttrGetName(), mlirDenseTypedElementsAttrGetTypeID(), mlirDiagnosticGetLocation(), mlirDiagnosticGetNote(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDialectHandleRegisterDialect(), mlirDialectRegistryCreate(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetName(), mlirDictionaryAttrGetTypeID(), mlirDistinctAttrCreate(), mlirDominanceInfoCreate(), mlirDominanceInfoFindNearestCommonDominator(), mlirDynamicAttrDefinitionGetDialect(), mlirDynamicAttrDefinitionGetName(), mlirDynamicAttrDefinitionGetTypeID(), mlirDynamicAttrGet(), mlirDynamicAttrGetAttrDef(), mlirDynamicAttrGetParam(), mlirDynamicAttrGetTypeID(), mlirDynamicOpTraitCreate(), mlirDynamicOpTraitIsTerminatorCreate(), mlirDynamicOpTraitIsTerminatorGetTypeID(), mlirDynamicOpTraitNoTerminatorCreate(), mlirDynamicOpTraitNoTerminatorGetTypeID(), mlirDynamicTypeDefinitionGetDialect(), mlirDynamicTypeDefinitionGetName(), mlirDynamicTypeDefinitionGetTypeID(), mlirDynamicTypeGet(), mlirDynamicTypeGetParam(), mlirDynamicTypeGetTypeDef(), mlirDynamicTypeGetTypeID(), mlirElementsAttrGetValue(), mlirEmitCArrayTypeGet(), mlirEmitCArrayTypeGetName(), mlirEmitCArrayTypeGetTypeID(), mlirEmitCCmpPredicateAttrGet(), mlirEmitCCmpPredicateAttrGetName(), mlirEmitCCmpPredicateAttrGetTypeID(), mlirEmitCLValueTypeGet(), mlirEmitCLValueTypeGetName(), mlirEmitCLValueTypeGetTypeID(), mlirEmitCOpaqueAttrGet(), mlirEmitCOpaqueAttrGetName(), mlirEmitCOpaqueAttrGetTypeID(), mlirEmitCOpaqueAttrGetValue(), mlirEmitCOpaqueTypeGet(), mlirEmitCOpaqueTypeGetName(), mlirEmitCOpaqueTypeGetTypeID(), mlirEmitCPointerTypeGet(), mlirEmitCPointerTypeGetName(), mlirEmitCPointerTypeGetTypeID(), mlirEmitCPtrDiffTTypeGet(), mlirEmitCPtrDiffTTypeGetName(), mlirEmitCPtrDiffTTypeGetTypeID(), mlirEmitCSignedSizeTTypeGet(), mlirEmitCSignedSizeTTypeGetName(), mlirEmitCSignedSizeTTypeGetTypeID(), mlirEmitCSizeTTypeGet(), mlirEmitCSizeTTypeGetName(), mlirEmitCSizeTTypeGetTypeID(), mlirExecutionEngineCreate(), mlirExecutionEngineInvokePacked(), mlirExtensibleDialectLookupAttrDefinition(), mlirExtensibleDialectLookupTypeDefinition(), mlirF16TypeGet(), mlirF16TypeGetName(), mlirF32TypeGet(), mlirF32TypeGetName(), mlirF64TypeGet(), mlirF64TypeGetName(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetName(), mlirFlatSymbolRefAttrGetValue(), mlirFloat16TypeGetTypeID(), mlirFloat32TypeGetTypeID(), mlirFloat4E2M1FNTypeGet(), mlirFloat4E2M1FNTypeGetName(), mlirFloat4E2M1FNTypeGetTypeID(), mlirFloat64TypeGetTypeID(), mlirFloat6E2M3FNTypeGet(), mlirFloat6E2M3FNTypeGetName(), mlirFloat6E2M3FNTypeGetTypeID(), mlirFloat6E3M2FNTypeGet(), mlirFloat6E3M2FNTypeGetName(), mlirFloat6E3M2FNTypeGetTypeID(), mlirFloat8E3M4TypeGet(), mlirFloat8E3M4TypeGetName(), mlirFloat8E3M4TypeGetTypeID(), mlirFloat8E4M3B11FNUZTypeGet(), mlirFloat8E4M3B11FNUZTypeGetName(), mlirFloat8E4M3B11FNUZTypeGetTypeID(), mlirFloat8E4M3FNTypeGet(), mlirFloat8E4M3FNTypeGetName(), mlirFloat8E4M3FNTypeGetTypeID(), mlirFloat8E4M3FNUZTypeGet(), mlirFloat8E4M3FNUZTypeGetName(), mlirFloat8E4M3FNUZTypeGetTypeID(), mlirFloat8E4M3TypeGet(), mlirFloat8E4M3TypeGetName(), mlirFloat8E4M3TypeGetTypeID(), mlirFloat8E5M2FNUZTypeGet(), mlirFloat8E5M2FNUZTypeGetName(), mlirFloat8E5M2FNUZTypeGetTypeID(), mlirFloat8E5M2TypeGet(), mlirFloat8E5M2TypeGetName(), mlirFloat8E5M2TypeGetTypeID(), mlirFloat8E8M0FNUTypeGet(), mlirFloat8E8M0FNUTypeGetName(), mlirFloat8E8M0FNUTypeGetTypeID(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFloatAttrGetName(), mlirFloatAttrGetTypeID(), mlirFloatTF32TypeGetTypeID(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetName(), mlirFunctionTypeGetResult(), mlirFunctionTypeGetTypeID(), mlirGPUAsyncTokenTypeGet(), mlirGPUAsyncTokenTypeGetName(), mlirGPUObjectAttrGet(), mlirGPUObjectAttrGetKernels(), mlirGPUObjectAttrGetName(), mlirGPUObjectAttrGetProperties(), mlirGPUObjectAttrGetTarget(), mlirGPUObjectAttrGetWithKernels(), mlirIdentifierGet(), mlirIdentifierGetContext(), mlirIdentifierStr(), mlirIndexTypeGet(), mlirIndexTypeGetName(), mlirIndexTypeGetTypeID(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirInferShapedTypeOpInterfaceTypeID(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirInferTypeOpInterfaceTypeID(), mlirIntegerAttrGet(), mlirIntegerAttrGetFromWords(), mlirIntegerAttrGetName(), mlirIntegerAttrGetTypeID(), mlirIntegerSetAttrGet(), mlirIntegerSetAttrGetName(), mlirIntegerSetAttrGetTypeID(), mlirIntegerSetAttrGetValue(), mlirIntegerSetEmptyGet(), mlirIntegerSetGet(), mlirIntegerSetGetConstraint(), mlirIntegerSetGetContext(), mlirIntegerSetReplaceGet(), mlirIntegerTypeGet(), mlirIntegerTypeGetName(), mlirIntegerTypeGetTypeID(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirIRDLVariadicityArrayAttrGet(), mlirIRDLVariadicityArrayAttrGetName(), mlirIRDLVariadicityAttrGet(), mlirIRDLVariadicityAttrGetName(), mlirIRMappingCreate(), mlirIRMappingLookupOrDefaultBlock(), mlirIRMappingLookupOrDefaultOperation(), mlirIRMappingLookupOrDefaultValue(), mlirIRMappingLookupOrNullBlock(), mlirIRMappingLookupOrNullOperation(), mlirIRMappingLookupOrNullValue(), mlirLinalgGetIndexingMapsAttribute(), mlirLLVMArrayTypeGet(), mlirLLVMArrayTypeGetElementType(), mlirLLVMArrayTypeGetName(), mlirLLVMArrayTypeGetTypeID(), mlirLLVMCConvAttrGet(), mlirLLVMCConvAttrGetName(), mlirLLVMComdatAttrGet(), mlirLLVMComdatAttrGetName(), mlirLLVMDIAnnotationAttrGet(), mlirLLVMDIAnnotationAttrGetName(), mlirLLVMDIBasicTypeAttrGet(), mlirLLVMDIBasicTypeAttrGetName(), mlirLLVMDICompileUnitAttrGet(), mlirLLVMDICompileUnitAttrGetName(), mlirLLVMDICompileUnitAttrGetRecSelf(), mlirLLVMDICompositeTypeAttrGet(), mlirLLVMDICompositeTypeAttrGetName(), mlirLLVMDICompositeTypeAttrGetRecSelf(), mlirLLVMDIDerivedTypeAttrGet(), mlirLLVMDIDerivedTypeAttrGetBaseType(), mlirLLVMDIDerivedTypeAttrGetName(), mlirLLVMDIExpressionAttrGet(), mlirLLVMDIExpressionAttrGetName(), mlirLLVMDIExpressionElemAttrGet(), mlirLLVMDIExpressionElemAttrGetName(), mlirLLVMDIFileAttrGet(), mlirLLVMDIFileAttrGetName(), mlirLLVMDIFlagsAttrGet(), mlirLLVMDIFlagsAttrGetName(), mlirLLVMDIImportedEntityAttrGet(), mlirLLVMDIImportedEntityAttrGetName(), mlirLLVMDILexicalBlockAttrGet(), mlirLLVMDILexicalBlockAttrGetName(), mlirLLVMDILexicalBlockFileAttrGet(), mlirLLVMDILexicalBlockFileAttrGetName(), mlirLLVMDILocalVariableAttrGet(), mlirLLVMDILocalVariableAttrGetName(), mlirLLVMDIModuleAttrGet(), mlirLLVMDIModuleAttrGetName(), mlirLLVMDIModuleAttrGetScope(), mlirLLVMDINullTypeAttrGet(), mlirLLVMDINullTypeAttrGetName(), mlirLLVMDIStringTypeAttrGet(), mlirLLVMDIStringTypeAttrGetName(), mlirLLVMDISubprogramAttrGet(), mlirLLVMDISubprogramAttrGetCompileUnit(), mlirLLVMDISubprogramAttrGetFile(), mlirLLVMDISubprogramAttrGetName(), mlirLLVMDISubprogramAttrGetRecSelf(), mlirLLVMDISubprogramAttrGetScope(), mlirLLVMDISubprogramAttrGetType(), mlirLLVMDISubroutineTypeAttrGet(), mlirLLVMDISubroutineTypeAttrGetName(), mlirLLVMFunctionTypeGet(), mlirLLVMFunctionTypeGetInput(), mlirLLVMFunctionTypeGetName(), mlirLLVMFunctionTypeGetReturnType(), mlirLLVMFunctionTypeGetTypeID(), mlirLLVMLinkageAttrGet(), mlirLLVMLinkageAttrGetName(), mlirLLVMMDConstantAttrGet(), mlirLLVMMDConstantAttrGetTypeID(), mlirLLVMMDConstantAttrGetValue(), mlirLLVMMDFuncAttrGet(), mlirLLVMMDFuncAttrGetName(), mlirLLVMMDFuncAttrGetTypeID(), mlirLLVMMDNodeAttrGet(), mlirLLVMMDNodeAttrGetOperand(), mlirLLVMMDNodeAttrGetTypeID(), mlirLLVMMDStringAttrGet(), mlirLLVMMDStringAttrGetTypeID(), mlirLLVMMDStringAttrGetValue(), mlirLLVMPointerTypeGet(), mlirLLVMPointerTypeGetName(), mlirLLVMPointerTypeGetTypeID(), mlirLlvmRawFdOStreamCreate(), mlirLLVMStructTypeGetElementType(), mlirLLVMStructTypeGetIdentifier(), mlirLLVMStructTypeGetName(), mlirLLVMStructTypeGetTypeID(), mlirLLVMStructTypeIdentifiedGet(), mlirLLVMStructTypeIdentifiedNewGet(), mlirLLVMStructTypeLiteralGet(), mlirLLVMStructTypeLiteralGetChecked(), mlirLLVMStructTypeOpaqueGet(), mlirLLVMStructTypeSetBody(), mlirLlvmThreadPoolCreate(), mlirLLVMVoidTypeGet(), mlirLLVMVoidTypeGetName(), mlirLoadIRDLDialects(), mlirLocationCallSiteGet(), mlirLocationCallSiteGetCallee(), mlirLocationCallSiteGetCaller(), mlirLocationCallSiteGetTypeID(), mlirLocationFileLineColGet(), mlirLocationFileLineColRangeGet(), mlirLocationFileLineColRangeGetFilename(), mlirLocationFileLineColRangeGetTypeID(), mlirLocationFromAttribute(), mlirLocationFusedGet(), mlirLocationFusedGetLocations(), mlirLocationFusedGetMetadata(), mlirLocationFusedGetTypeID(), mlirLocationGetAttribute(), mlirLocationGetContext(), mlirLocationNameGet(), mlirLocationNameGetChildLoc(), mlirLocationNameGetName(), mlirLocationNameGetTypeID(), mlirLocationUnknownGet(), mlirLocationUnknownGetTypeID(), mlirMemoryEffectsOpInterfaceTypeID(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetChecked(), mlirMemRefTypeGetLayout(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetName(), mlirMemRefTypeGetTypeID(), mlirMergeSymbolsIntoFromClone(), mlirModuleCreateEmpty(), mlirModuleFromOperation(), mlirModuleGetBody(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirNoneTypeGetName(), mlirNoneTypeGetTypeID(), mlirNVGPUTensorMapDescriptorTypeGet(), mlirNVGPUTensorMapDescriptorTypeGetName(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOpaqueAttrGetName(), mlirOpaqueAttrGetTypeID(), mlirOpaqueTypeGet(), mlirOpaqueTypeGetData(), mlirOpaqueTypeGetDialectNamespace(), mlirOpaqueTypeGetName(), mlirOpaqueTypeGetTypeID(), mlirOperationClone(), mlirOperationCloneWithMapping(), mlirOperationCreate(), mlirOperationCreateParse(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetBlock(), mlirOperationGetContext(), mlirOperationGetDiscardableAttribute(), mlirOperationGetDiscardableAttributeByName(), mlirOperationGetFirstRegion(), mlirOperationGetInherentAttributeByName(), mlirOperationGetLocation(), mlirOperationGetName(), mlirOperationGetNextInBlock(), mlirOperationGetOperand(), mlirOperationGetOpOperand(), mlirOperationGetParentOperation(), mlirOperationGetRegion(), mlirOperationGetResult(), mlirOperationGetSuccessor(), mlirOperationGetTypeID(), mlirOperationWalk(), mlirOperationWriteBytecodeWithConfig(), mlirOpOperandGetNextUse(), mlirOpOperandGetOwner(), mlirOpOperandGetValue(), mlirOpPassManagerAddPipeline(), mlirOpPassManagerGetNestedUnder(), mlirOpPrintingFlagsCreate(), mlirOpResultGetOwner(), mlirParsePassPipeline(), mlirPassManagerCreate(), mlirPassManagerCreateOnOperation(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPassManagerRunOnOp(), mlirPatternDescriptorOpInterfaceTypeID(), mlirPDLAttributeTypeGet(), mlirPDLAttributeTypeGetName(), mlirPDLAttributeTypeGetTypeID(), mlirPDLOperationTypeGet(), mlirPDLOperationTypeGetName(), mlirPDLOperationTypeGetTypeID(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLRangeTypeGetName(), mlirPDLRangeTypeGetTypeID(), mlirPDLTypeTypeGet(), mlirPDLTypeTypeGetName(), mlirPDLTypeTypeGetTypeID(), mlirPDLValueTypeGet(), mlirPDLValueTypeGetName(), mlirPDLValueTypeGetTypeID(), mlirPostDominanceInfoCreate(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetStorageType(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRankedTensorTypeGetEncoding(), mlirRankedTensorTypeGetName(), mlirRankedTensorTypeGetTypeID(), mlirRegionCreate(), mlirRegionGetFirstBlock(), mlirRegionGetNextInOperation(), mlirShapedTypeGetElementType(), mlirSimplifyAffineExpr(), mlirSMTAttrGetBitVector(), mlirSMTAttrGetBVCmpPredicate(), mlirSMTAttrGetIntPredicate(), mlirSMTBitVectorTypeGetName(), mlirSMTBitVectorTypeGetTypeID(), mlirSMTBoolTypeGetName(), mlirSMTBoolTypeGetTypeID(), mlirSMTIntTypeGetName(), mlirSMTIntTypeGetTypeID(), mlirSMTTypeGetArray(), mlirSMTTypeGetBitVector(), mlirSMTTypeGetBool(), mlirSMTTypeGetInt(), mlirSMTTypeGetSMTFunc(), mlirSMTTypeGetSort(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetTypeID(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetDimToLvl(), mlirSparseTensorEncodingAttrGetExplicitVal(), mlirSparseTensorEncodingAttrGetImplicitVal(), mlirSparseTensorEncodingAttrGetLvlToDim(), mlirSparseTensorEncodingAttrGetName(), mlirStridedLayoutAttrGet(), mlirStridedLayoutAttrGetName(), mlirStridedLayoutAttrGetTypeID(), mlirStringAttrGet(), mlirStringAttrGetName(), mlirStringAttrGetTypeID(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetName(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetRootReference(), mlirSymbolRefAttrGetTypeID(), mlirSymbolTableCreate(), mlirSymbolTableGetSymbolAttributeName(), mlirSymbolTableGetVisibilityAttributeName(), mlirSymbolTableInsert(), mlirSymbolTableLookup(), mlirSymbolTableReplaceAllSymbolUses(), mlirSymbolTableWalkSymbolTables(), mlirTF32TypeGet(), mlirTF32TypeGetName(), mlirTransformAnyOpTypeGet(), mlirTransformAnyOpTypeGetName(), mlirTransformAnyOpTypeGetTypeID(), mlirTransformAnyParamTypeGet(), mlirTransformAnyParamTypeGetName(), mlirTransformAnyParamTypeGetTypeID(), mlirTransformAnyValueTypeGet(), mlirTransformAnyValueTypeGetName(), mlirTransformAnyValueTypeGetTypeID(), mlirTransformApplyNamedSequence(), mlirTransformOperationTypeGet(), mlirTransformOperationTypeGetName(), mlirTransformOperationTypeGetOperationName(), mlirTransformOperationTypeGetTypeID(), mlirTransformOpInterfaceTypeID(), mlirTransformOptionsCreate(), mlirTransformParamTypeGet(), mlirTransformParamTypeGetName(), mlirTransformParamTypeGetType(), mlirTransformParamTypeGetTypeID(), mlirTransformRewriterAsBase(), mlirTransformStateForEachParam(), mlirTransformStateForEachPayloadOp(), mlirTransformStateForEachPayloadValue(), mlirTranslateOperationToSMTLIB(), mlirTupleTypeGet(), mlirTupleTypeGetName(), mlirTupleTypeGetType(), mlirTupleTypeGetTypeID(), mlirTypeAttrGet(), mlirTypeAttrGetName(), mlirTypeAttrGetTypeID(), mlirTypeAttrGetValue(), mlirTypeFromLLVMIRTranslatorTranslateType(), mlirTypeGetContext(), mlirTypeGetDialect(), mlirTypeGetTypeID(), mlirTypeIDAllocatorAllocateTypeID(), mlirTypeIDAllocatorCreate(), mlirTypeIDCreate(), mlirTypeParseGet(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedPerAxisTypeGetName(), mlirUniformQuantizedPerAxisTypeGetTypeID(), mlirUniformQuantizedSubChannelTypeGet(), mlirUniformQuantizedSubChannelTypeGetName(), mlirUniformQuantizedSubChannelTypeGetScales(), mlirUniformQuantizedSubChannelTypeGetTypeID(), mlirUniformQuantizedSubChannelTypeGetZeroPoints(), mlirUniformQuantizedTypeGet(), mlirUniformQuantizedTypeGetName(), mlirUniformQuantizedTypeGetTypeID(), mlirUnitAttrGet(), mlirUnitAttrGetName(), mlirUnitAttrGetTypeID(), mlirUnmanagedDenseResourceElementsAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedMemRefTypeGetName(), mlirUnrankedMemRefTypeGetTypeID(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirUnrankedTensorTypeGetName(), mlirUnrankedTensorTypeGetTypeID(), mlirValueGetContext(), mlirValueGetFirstUse(), mlirValueGetLocation(), mlirValueGetType(), mlirVectorTypeGet(), mlirVectorTypeGetChecked(), mlirVectorTypeGetName(), mlirVectorTypeGetScalable(), mlirVectorTypeGetScalableChecked(), mlirVectorTypeGetTypeID(), PatternDescriptorOpInterfaceFallbackModel::populatePatterns(), PatternDescriptorOpInterfaceFallbackModel::populatePatternsWithState(), mlir::ExternalPass::runOnOperation(), mlir::sparse_tensor::SparseIterator::SparseIterator(), toContractionDimensions(), toConvolutionDimensions(), mlir::ExternalDynamicOpTrait::verifyRegionTrait(), and mlir::ExternalDynamicOpTrait::verifyTrait().