MLIR: lib/Dialect/Index/IR/InferIntRangeInterfaceImpls.cpp File Reference
InferIntRangeInterfaceImpls.cpp File Reference
#include "mlir/Dialect/Index/IR/IndexOps.h"
#include "mlir/Interfaces/InferIntRangeInterface.h"
#include "mlir/Interfaces/Utils/InferIntRangeCommon.h"
#include <optional>
Macros
#define DEBUG_TYPE "int-range-analysis"
Functions
static std::function< ConstantIntRanges(ArrayRef< ConstantIntRanges >)> inferWithoutOverflowFlags (InferRangeWithOvfFlagsFn inferWithOvfFn)
static ConstantIntRanges makeLikeDest (const ConstantIntRanges &range, unsigned srcWidth, unsigned destWidth, bool isSigned)
static ConstantIntRanges inferIndexCast (const ConstantIntRanges &range, Type sourceType, Type destType, bool isSigned)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "int-range-analysis"
Definition at line 15 of file InferIntRangeInterfaceImpls.cpp.
Function Documentation
inferIndexCast()
static ConstantIntRanges inferIndexCast (const ConstantIntRanges & range, Type sourceType, Type destType, bool isSigned) static
Definition at line 193 of file InferIntRangeInterfaceImpls.cpp.
References mlir::intrange::extRange(), mlir::ConstantIntRanges::getStorageBitwidth(), mlir::intrange::indexMinWidth, mlir::Type::isIndex(), makeLikeDest(), and mlir::ConstantIntRanges::rangeUnion().
inferWithoutOverflowFlags()
static std::function<ConstantIntRanges(ArrayRef<ConstantIntRanges>)> inferWithoutOverflowFlags (InferRangeWithOvfFlagsFn inferWithOvfFn) static
Definition at line 50 of file InferIntRangeInterfaceImpls.cpp.
References None.
makeLikeDest()
static ConstantIntRanges makeLikeDest (const ConstantIntRanges & range, unsigned srcWidth, unsigned destWidth, bool isSigned) static
Definition at line 180 of file InferIntRangeInterfaceImpls.cpp.
References mlir::intrange::extSIRange(), mlir::intrange::extUIRange(), and mlir::intrange::truncRange().
Referenced by inferIndexCast().