MLIR: lib/Dialect/Transform/Transforms/InferEffects.cpp File Reference
InferEffects.cpp File Reference
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/Transforms/Passes.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/IR/Visitors.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "llvm/ADT/DenseSet.h"
#include "mlir/Dialect/Transform/Transforms/Passes.h.inc"
Classes
class mlir::transform::impl::InferEffectsPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::transform
namespace mlir::transform::impl
Macros
#define GEN_PASS_DEF_INFEREFFECTSPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::transform::impl::createInferEffectsPass ()
std::unique_ptr<::mlir::Pass > mlir::transform::createInferEffectsPass ()
static LogicalResult inferSideEffectAnnotations (Operation *op)
Macro Definition Documentation
GEN_PASS_DEF_INFEREFFECTSPASS
#define GEN_PASS_DEF_INFEREFFECTSPASS
Definition at line 21 of file InferEffects.cpp.
Function Documentation
inferSideEffectAnnotations()
LogicalResult inferSideEffectAnnotations (Operation * op) static
Definition at line 26 of file InferEffects.cpp.
References mlir::Operation::emitError(), mlir::transform::getConsumedBlockArguments(), mlir::Operation::getContext(), and success().