MLIR: lib/Transforms/InlinerPass.cpp File Reference
InlinerPass.cpp File Reference
#include "mlir/Transforms/Passes.h"
#include "mlir/Analysis/CallGraph.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/Inliner.h"
#include "llvm/Support/DebugLog.h"
#include "mlir/Transforms/Passes.h.inc"
Classes
class mlir::impl::InlinerPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_INLINERPASS
#define DEBUG_TYPE "inliner-pass"
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createInlinerPass ()
std::unique_ptr<::mlir::Pass > mlir::impl::createInlinerPass (InlinerPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::createInlinerPass ()
std::unique_ptr<::mlir::Pass > mlir::createInlinerPass (InlinerPassOptions options)
static void defaultInlinerOptPipeline (OpPassManager &pm)
This function implements the inliner optimization pipeline.
static bool isProfitableToInline (const Inliner::ResolvedCall &resolvedCall, unsigned inliningThreshold)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inliner-pass"
Definition at line 28 of file InlinerPass.cpp.
GEN_PASS_DEF_INLINERPASS
#define GEN_PASS_DEF_INLINERPASS
Definition at line 24 of file InlinerPass.cpp.
Function Documentation
defaultInlinerOptPipeline()
void defaultInlinerOptPipeline (OpPassManager & pm) static
This function implements the inliner optimization pipeline.
Definition at line 33 of file InlinerPass.cpp.
References mlir::OpPassManager::addPass(), and mlir::createCanonicalizerPass().
Referenced by mlir::createInlinerPass().
isProfitableToInline()
bool isProfitableToInline (const Inliner::ResolvedCall & resolvedCall, unsigned inliningThreshold) static
Definition at line 98 of file InlinerPass.cpp.
References mlir::CallGraphNode::getCallableRegion(), mlir::Inliner::ResolvedCall::sourceNode, and mlir::Inliner::ResolvedCall::targetNode.