MLIR: include/mlir-c/Dialect/Transform/Interpreter.h File Reference
Interpreter.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Functions
DEFINE_C_API_STRUCT (MlirTransformOptions, void)
MLIR_CAPI_EXPORTED MlirTransformOptions mlirTransformOptionsCreate (void)
Creates a default-initialized transform options object.
MLIR_CAPI_EXPORTED void mlirTransformOptionsEnableExpensiveChecks (MlirTransformOptions transformOptions, bool enable)
Enables or disables expensive checks in transform options.
MLIR_CAPI_EXPORTED bool mlirTransformOptionsGetExpensiveChecksEnabled (MlirTransformOptions transformOptions)
Returns true if expensive checks are enabled in transform options.
MLIR_CAPI_EXPORTED void mlirTransformOptionsEnforceSingleTopLevelTransformOp (MlirTransformOptions transformOptions, bool enable)
Enables or disables the enforcement of the top-level transform op being single in transform options.
MLIR_CAPI_EXPORTED bool mlirTransformOptionsGetEnforceSingleTopLevelTransformOp (MlirTransformOptions transformOptions)
Returns true if the enforcement of the top-level transform op being single is enabled in transform options.
MLIR_CAPI_EXPORTED void mlirTransformOptionsDestroy (MlirTransformOptions transformOptions)
Destroys a transform options object previously created by mlirTransformOptionsCreate.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirTransformApplyNamedSequence (MlirOperation payload, MlirOperation transformRoot, MlirOperation transformModule, MlirTransformOptions transformOptions)
Applies the transformation script starting at the given transform root operation to the given payload operation.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirMergeSymbolsIntoFromClone (MlirOperation target, MlirOperation other)
Merge the symbols from other into target, potentially renaming them to avoid conflicts.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
  struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Definition at line 21 of file Interpreter.h.
Function Documentation
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (MlirTransformOptions , void)
References MLIR_CAPI_EXPORTED, and target.
mlirMergeSymbolsIntoFromClone()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirMergeSymbolsIntoFromClone (MlirOperation target, MlirOperation other)
Merge the symbols from other into target, potentially renaming them to avoid conflicts.
Private symbols may be renamed during the merge, public symbols must have at most one declaration. A name conflict in public symbols is reported as an error before returning a failure.
Note that this clones the other operation unlike the C++ counterpart that takes ownership.
Definition at line 76 of file TransformInterpreter.cpp.
References mlir::clone(), mlir::transform::detail::mergeSymbolsInto(), result, target, unwrap(), and wrap().
Referenced by populateTransformInterpreterSubmodule().
mlirTransformApplyNamedSequence()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirTransformApplyNamedSequence (MlirOperation payload, MlirOperation transformRoot, MlirOperation transformModule, MlirTransformOptions transformOptions)
Applies the transformation script starting at the given transform root operation to the given payload operation.
The module containing the transform root as well as the transform options should be provided. The transform operation must implement TransformOpInterface and the module must be a ModuleOp. Returns the status of the application.
Definition at line 56 of file TransformInterpreter.cpp.
References mlir::transform::applyTransformNamedSequence(), mlir::Operation::emitError(), mlirLogicalResultFailure(), unwrap(), and wrap().
Referenced by populateTransformInterpreterSubmodule().
mlirTransformOptionsCreate()
MLIR_CAPI_EXPORTED MlirTransformOptions mlirTransformOptionsCreate (void)
Creates a default-initialized transform options object.
Definition at line 28 of file TransformInterpreter.cpp.
References wrap().
mlirTransformOptionsDestroy()
MLIR_CAPI_EXPORTED void mlirTransformOptionsDestroy (MlirTransformOptions transformOptions)
Destroys a transform options object previously created by mlirTransformOptionsCreate.
Definition at line 52 of file TransformInterpreter.cpp.
References unwrap().
mlirTransformOptionsEnableExpensiveChecks()
MLIR_CAPI_EXPORTED void mlirTransformOptionsEnableExpensiveChecks (MlirTransformOptions transformOptions, bool enable)
Enables or disables expensive checks in transform options.
Definition at line 32 of file TransformInterpreter.cpp.
References unwrap().
Referenced by populateTransformInterpreterSubmodule().
mlirTransformOptionsEnforceSingleTopLevelTransformOp()
MLIR_CAPI_EXPORTED void mlirTransformOptionsEnforceSingleTopLevelTransformOp (MlirTransformOptions transformOptions, bool enable)
Enables or disables the enforcement of the top-level transform op being single in transform options.
Definition at line 42 of file TransformInterpreter.cpp.
References unwrap().
Referenced by populateTransformInterpreterSubmodule().
mlirTransformOptionsGetEnforceSingleTopLevelTransformOp()
MLIR_CAPI_EXPORTED bool mlirTransformOptionsGetEnforceSingleTopLevelTransformOp (MlirTransformOptions transformOptions)
Returns true if the enforcement of the top-level transform op being single is enabled in transform options.
Definition at line 47 of file TransformInterpreter.cpp.
References unwrap().
Referenced by populateTransformInterpreterSubmodule().
mlirTransformOptionsGetExpensiveChecksEnabled()
MLIR_CAPI_EXPORTED bool mlirTransformOptionsGetExpensiveChecksEnabled (MlirTransformOptions transformOptions)
Returns true if expensive checks are enabled in transform options.
Definition at line 37 of file TransformInterpreter.cpp.
References unwrap().
Referenced by populateTransformInterpreterSubmodule().