MLIR: lib/Dialect/Transform/Transforms/InterpreterPass.cpp File Reference
InterpreterPass.cpp File Reference
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/Dialect/Transform/Transforms/Passes.h"
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/Dialect/Transform/Transforms/Passes.h.inc"
Classes
class mlir::transform::impl::InterpreterPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::transform
namespace mlir::transform::impl
Macros
#define GEN_PASS_DEF_INTERPRETERPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::transform::impl::createInterpreterPass ()
std::unique_ptr<::mlir::Pass > mlir::transform::impl::createInterpreterPass (InterpreterPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::transform::createInterpreterPass ()
std::unique_ptr<::mlir::Pass > mlir::transform::createInterpreterPass (InterpreterPassOptions options)
static Operation * findPayloadRoot (Operation *passRoot, StringRef tag)
Returns the payload operation to be used as payload root:
Macro Definition Documentation
GEN_PASS_DEF_INTERPRETERPASS
#define GEN_PASS_DEF_INTERPRETERPASS
Definition at line 18 of file InterpreterPass.cpp.
Function Documentation
findPayloadRoot()
Operation * findPayloadRoot (Operation * passRoot, StringRef tag) static
Returns the payload operation to be used as payload root:
the operation nested under passRoot that has the given tag attribute, must be unique;
the passRoot itself if the tag is empty.
Definition at line 27 of file InterpreterPass.cpp.
References mlir::WalkResult::advance(), diag(), mlir::Operation::emitError(), mlir::Operation::getAttrOfType(), mlir::Operation::getContext(), mlir::WalkResult::interrupt(), nullptr, target, mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().