MLIR: include/mlir-c/Bindings/Python/Interop.h File Reference
Interop.h File Reference
#include <Python.h>
#include "mlir-c/AffineExpr.h"
#include "mlir-c/AffineMap.h"
#include "mlir-c/ExecutionEngine.h"
#include "mlir-c/IR.h"
#include "mlir-c/IntegerSet.h"
#include "mlir-c/Pass.h"
#include "mlir-c/Rewrite.h"
Macros
#define MLIR_PYTHON_PACKAGE_PREFIX mlir.
#define MLIR_PYTHON_STRINGIZE(s)
#define MLIR_PYTHON_STRINGIZE_ARG(arg)
#define MAKE_MLIR_PYTHON_QUALNAME(local)
#define MLIR_PYTHON_CAPSULE_AFFINE_EXPR MAKE_MLIR_PYTHON_QUALNAME("ir.AffineExpr._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_AFFINE_MAP MAKE_MLIR_PYTHON_QUALNAME("ir.AffineMap._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_ATTRIBUTE MAKE_MLIR_PYTHON_QUALNAME("ir.Attribute._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_BLOCK MAKE_MLIR_PYTHON_QUALNAME("ir.Block._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_CONTEXT MAKE_MLIR_PYTHON_QUALNAME("ir.Context._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_DIALECT_REGISTRY MAKE_MLIR_PYTHON_QUALNAME("ir.DialectRegistry._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE MAKE_MLIR_PYTHON_QUALNAME("execution_engine.ExecutionEngine._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_INTEGER_SET MAKE_MLIR_PYTHON_QUALNAME("ir.IntegerSet._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_LOCATION MAKE_MLIR_PYTHON_QUALNAME("ir.Location._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_MODULE MAKE_MLIR_PYTHON_QUALNAME("ir.Module._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_OPERATION MAKE_MLIR_PYTHON_QUALNAME("ir.Operation._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_TYPE MAKE_MLIR_PYTHON_QUALNAME("ir.Type._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_PASS_MANAGER MAKE_MLIR_PYTHON_QUALNAME("passmanager.PassManager._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_VALUE MAKE_MLIR_PYTHON_QUALNAME("ir.Value._CAPIPtr")
#define MLIR_PYTHON_CAPSULE_TYPEID MAKE_MLIR_PYTHON_QUALNAME("ir.TypeID._CAPIPtr")
#define MLIR_PYTHON_CAPI_PTR_ATTR "_CAPIPtr"
Attribute on MLIR Python objects that expose their C-API pointer.
#define MLIR_PYTHON_CAPI_FACTORY_ATTR "_CAPICreate"
Attribute on MLIR Python objects that exposes a factory function for constructing the corresponding Python object from a type-specific capsule wrapping the C-API pointer.
#define MLIR_PYTHON_MAYBE_DOWNCAST_ATTR "maybe_downcast"
Attribute on MLIR Python objects that expose a function for downcasting the corresponding Python object to a subclass if the object is in fact a subclass (Concrete or mlir_type_subclass) of ir.Type.
#define MLIR_PYTHON_CAPI_TYPE_CASTER_REGISTER_ATTR "register_type_caster"
Attribute on main C extension module (_mlir) that corresponds to the type caster registration binding.
#define MLIR_PYTHON_CAPI_VALUE_CASTER_REGISTER_ATTR "register_value_caster"
Attribute on main C extension module (_mlir) that corresponds to the value caster registration binding.
#define MLIR_PYTHON_GET_WRAPPED_POINTER(object)
Gets a void* from a wrapped struct.
Functions
static PyObject * mlirPythonAffineExprToCapsule (MlirAffineExpr expr)
Creates a capsule object encapsulating the raw C-API MlirAffineExpr.
static MlirAffineExpr mlirPythonCapsuleToAffineExpr (PyObject *capsule)
Extracts an MlirAffineExpr from a capsule as produced from mlirPythonAffineExprToCapsule.
static PyObject * mlirPythonAttributeToCapsule (MlirAttribute attribute)
Creates a capsule object encapsulating the raw C-API MlirAttribute.
static MlirAttribute mlirPythonCapsuleToAttribute (PyObject *capsule)
Extracts an MlirAttribute from a capsule as produced from mlirPythonAttributeToCapsule.
static PyObject * mlirPythonBlockToCapsule (MlirBlock block)
Creates a capsule object encapsulating the raw C-API MlirBlock.
static MlirBlock mlirPythonCapsuleToBlock (PyObject *capsule)
Extracts an MlirBlock from a capsule as produced from mlirPythonBlockToCapsule.
static PyObject * mlirPythonContextToCapsule (MlirContext context)
Creates a capsule object encapsulating the raw C-API MlirContext.
static MlirContext mlirPythonCapsuleToContext (PyObject *capsule)
Extracts a MlirContext from a capsule as produced from mlirPythonContextToCapsule.
static PyObject * mlirPythonDialectRegistryToCapsule (MlirDialectRegistry registry)
Creates a capsule object encapsulating the raw C-API MlirDialectRegistry.
static MlirDialectRegistry mlirPythonCapsuleToDialectRegistry (PyObject *capsule)
Extracts an MlirDialectRegistry from a capsule as produced from mlirPythonDialectRegistryToCapsule.
static PyObject * mlirPythonLocationToCapsule (MlirLocation loc)
Creates a capsule object encapsulating the raw C-API MlirLocation.
static MlirLocation mlirPythonCapsuleToLocation (PyObject *capsule)
Extracts an MlirLocation from a capsule as produced from mlirPythonLocationToCapsule.
static PyObject * mlirPythonModuleToCapsule (MlirModule module)
Creates a capsule object encapsulating the raw C-API MlirModule.
static MlirModule mlirPythonCapsuleToModule (PyObject *capsule)
Extracts an MlirModule from a capsule as produced from mlirPythonModuleToCapsule.
static PyObject * mlirPythonFrozenRewritePatternSetToCapsule (MlirFrozenRewritePatternSet pm)
Creates a capsule object encapsulating the raw C-API MlirFrozenRewritePatternSet.
static MlirFrozenRewritePatternSet mlirPythonCapsuleToFrozenRewritePatternSet (PyObject *capsule)
Extracts an MlirFrozenRewritePatternSet from a capsule as produced from mlirPythonFrozenRewritePatternSetToCapsule.
static PyObject * mlirPythonPassManagerToCapsule (MlirPassManager pm)
Creates a capsule object encapsulating the raw C-API MlirPassManager.
static MlirPassManager mlirPythonCapsuleToPassManager (PyObject *capsule)
Extracts an MlirPassManager from a capsule as produced from mlirPythonPassManagerToCapsule.
static PyObject * mlirPythonOperationToCapsule (MlirOperation operation)
Creates a capsule object encapsulating the raw C-API MlirOperation.
static MlirOperation mlirPythonCapsuleToOperation (PyObject *capsule)
Extracts an MlirOperations from a capsule as produced from mlirPythonOperationToCapsule.
static PyObject * mlirPythonTypeIDToCapsule (MlirTypeID typeID)
Creates a capsule object encapsulating the raw C-API MlirTypeID.
static MlirTypeID mlirPythonCapsuleToTypeID (PyObject *capsule)
Extracts an MlirTypeID from a capsule as produced from mlirPythonTypeIDToCapsule.
static PyObject * mlirPythonTypeToCapsule (MlirType type)
Creates a capsule object encapsulating the raw C-API MlirType.
static MlirType mlirPythonCapsuleToType (PyObject *capsule)
Extracts an MlirType from a capsule as produced from mlirPythonTypeToCapsule.
static PyObject * mlirPythonAffineMapToCapsule (MlirAffineMap affineMap)
Creates a capsule object encapsulating the raw C-API MlirAffineMap.
static MlirAffineMap mlirPythonCapsuleToAffineMap (PyObject *capsule)
Extracts an MlirAffineMap from a capsule as produced from mlirPythonAffineMapToCapsule.
static PyObject * mlirPythonIntegerSetToCapsule (MlirIntegerSet integerSet)
Creates a capsule object encapsulating the raw C-API MlirIntegerSet.
static MlirIntegerSet mlirPythonCapsuleToIntegerSet (PyObject *capsule)
Extracts an MlirIntegerSet from a capsule as produced from mlirPythonIntegerSetToCapsule.
static PyObject * mlirPythonExecutionEngineToCapsule (MlirExecutionEngine jit)
Creates a capsule object encapsulating the raw C-API MlirExecutionEngine.
static MlirExecutionEngine mlirPythonCapsuleToExecutionEngine (PyObject *capsule)
Extracts an MlirExecutionEngine from a capsule as produced from mlirPythonIntegerSetToCapsule.
static PyObject * mlirPythonValueToCapsule (MlirValue value)
Creates a capsule object encapsulating the raw C-API MlirValue.
static MlirValue mlirPythonCapsuleToValue (PyObject *capsule)
Extracts an MlirValue from a capsule as produced from mlirPythonValueToCapsule.
Macro Definition Documentation
MAKE_MLIR_PYTHON_QUALNAME
#define MAKE_MLIR_PYTHON_QUALNAME (local)
Value:
  MLIR_PYTHON_STRINGIZE_ARG(MLIR_PYTHON_PACKAGE_PREFIX) local
Definition at line 57 of file Interop.h.
Referenced by pybind11::detail::type_caster< MlirAffineMap >::cast(), pybind11::detail::type_caster< MlirAttribute >::cast(), pybind11::detail::type_caster< MlirDialectRegistry >::cast(), pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::cast(), pybind11::detail::type_caster< MlirLocation >::cast(), pybind11::detail::type_caster< MlirModule >::cast(), pybind11::detail::type_caster< MlirOperation >::cast(), pybind11::detail::type_caster< MlirType >::cast(), pybind11::detail::type_caster< MlirTypeID >::cast(), pybind11::detail::type_caster< MlirValue >::cast(), nanobind::detail::type_caster< MlirFrozenRewritePatternSet >::from_cpp(), pybind11::detail::type_caster< MlirContext >::load(), pybind11::detail::type_caster< MlirLocation >::load(), mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::nanobind_adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass(), mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass(), mlir::python::nanobind_adaptors::mlir_type_subclass::mlir_type_subclass(), mlir::python::adaptors::mlir_value_subclass::mlir_value_subclass(), mlir::python::nanobind_adaptors::mlir_value_subclass::mlir_value_subclass(), populateDialectLLVMSubmodule(), populateDialectPDLSubmodule(), and mlir::python::PyGlobals::PyGlobals().
MLIR_PYTHON_CAPI_FACTORY_ATTR
#define MLIR_PYTHON_CAPI_FACTORY_ATTR "_CAPICreate"
Attribute on MLIR Python objects that exposes a factory function for constructing the corresponding Python object from a type-specific capsule wrapping the C-API pointer.
The signature of the function is: def _CAPICreate(capsule) -> object Calling such a function implies a transfer of ownership of the object the capsule wraps: after such a call, the capsule should be considered invalid, and its wrapped pointer must not be destroyed.
Only a very small number of Python objects can be created in such a fashion (i.e. top-level types such as Context where the lifetime can be cleanly delineated).
Definition at line 110 of file Interop.h.
Referenced by pybind11::detail::type_caster< MlirAffineMap >::cast(), pybind11::detail::type_caster< MlirAttribute >::cast(), pybind11::detail::type_caster< MlirDialectRegistry >::cast(), pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::cast(), pybind11::detail::type_caster< MlirLocation >::cast(), pybind11::detail::type_caster< MlirModule >::cast(), pybind11::detail::type_caster< MlirOperation >::cast(), pybind11::detail::type_caster< MlirType >::cast(), pybind11::detail::type_caster< MlirTypeID >::cast(), pybind11::detail::type_caster< MlirValue >::cast(), nanobind::detail::type_caster< MlirAffineMap >::from_cpp(), nanobind::detail::type_caster< MlirAttribute >::from_cpp(), nanobind::detail::type_caster< MlirDialectRegistry >::from_cpp(), nanobind::detail::type_caster< MlirFrozenRewritePatternSet >::from_cpp(), nanobind::detail::type_caster< MlirLocation >::from_cpp(), nanobind::detail::type_caster< MlirModule >::from_cpp(), nanobind::detail::type_caster< MlirOperation >::from_cpp(), nanobind::detail::type_caster< MlirType >::from_cpp(), nanobind::detail::type_caster< MlirTypeID >::from_cpp(), nanobind::detail::type_caster< MlirValue >::from_cpp(), and NB_MODULE().
MLIR_PYTHON_CAPI_PTR_ATTR
#define MLIR_PYTHON_CAPI_PTR_ATTR "_CAPIPtr"
Attribute on MLIR Python objects that expose their C-API pointer.
This will be a type-specific capsule created as per one of the helpers below.
Ownership is not transferred by acquiring a capsule in this way: the validity of the pointer wrapped by the capsule will be bounded by the lifetime of the Python object that produced it. Only the name and pointer of the capsule are set. The caller is free to set a destructor and context as needed to manage anything further.
Definition at line 97 of file Interop.h.
Referenced by nanobind::detail::mlirApiObjectToCapsule(), pybind11::detail::mlirApiObjectToCapsule(), and NB_MODULE().
MLIR_PYTHON_CAPI_TYPE_CASTER_REGISTER_ATTR
#define MLIR_PYTHON_CAPI_TYPE_CASTER_REGISTER_ATTR "register_type_caster"
Attribute on main C extension module (_mlir) that corresponds to the type caster registration binding.
The signature of the function is: def register_type_caster(MlirTypeID mlirTypeID, *, bool replace) which then takes a typeCaster (register_type_caster is meant to be used as a decorator from python), and where replace indicates the typeCaster should replace any existing registered type casters (such as those for upstream ConcreteTypes). The interface of the typeCaster is: def type_caster(ir.Type) -> SubClassTypeT where SubClassTypeT indicates the result should be a subclass (inherit from) ir.Type.
Definition at line 130 of file Interop.h.
Referenced by mlir::python::adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::nanobind_adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::adaptors::mlir_type_subclass::mlir_type_subclass(), mlir::python::nanobind_adaptors::mlir_type_subclass::mlir_type_subclass(), and NB_MODULE().
MLIR_PYTHON_CAPI_VALUE_CASTER_REGISTER_ATTR
#define MLIR_PYTHON_CAPI_VALUE_CASTER_REGISTER_ATTR "register_value_caster"
Attribute on main C extension module (_mlir) that corresponds to the value caster registration binding.
The signature of the function is: def register_value_caster(MlirTypeID mlirTypeID, *, bool replace) which then takes a valueCaster (register_value_caster is meant to be used as a decorator, from python), and where replace indicates the valueCaster should replace any existing registered value casters. The interface of the valueCaster is: def value_caster(ir.Value) -> SubClassValueT where SubClassValueT indicates the result should be a subclass (inherit from) ir.Value.
Definition at line 142 of file Interop.h.
Referenced by NB_MODULE().
MLIR_PYTHON_CAPSULE_AFFINE_EXPR
#define MLIR_PYTHON_CAPSULE_AFFINE_EXPR MAKE_MLIR_PYTHON_QUALNAME("ir.AffineExpr._CAPIPtr")
Definition at line 60 of file Interop.h.
Referenced by mlirPythonAffineExprToCapsule(), and mlirPythonCapsuleToAffineExpr().
MLIR_PYTHON_CAPSULE_AFFINE_MAP
#define MLIR_PYTHON_CAPSULE_AFFINE_MAP MAKE_MLIR_PYTHON_QUALNAME("ir.AffineMap._CAPIPtr")
Definition at line 62 of file Interop.h.
Referenced by mlirPythonAffineMapToCapsule(), and mlirPythonCapsuleToAffineMap().
MLIR_PYTHON_CAPSULE_ATTRIBUTE
#define MLIR_PYTHON_CAPSULE_ATTRIBUTE MAKE_MLIR_PYTHON_QUALNAME("ir.Attribute._CAPIPtr")
Definition at line 64 of file Interop.h.
Referenced by mlirPythonAttributeToCapsule(), and mlirPythonCapsuleToAttribute().
MLIR_PYTHON_CAPSULE_BLOCK
#define MLIR_PYTHON_CAPSULE_BLOCK MAKE_MLIR_PYTHON_QUALNAME("ir.Block._CAPIPtr")
Definition at line 66 of file Interop.h.
Referenced by mlirPythonBlockToCapsule(), and mlirPythonCapsuleToBlock().
MLIR_PYTHON_CAPSULE_CONTEXT
#define MLIR_PYTHON_CAPSULE_CONTEXT MAKE_MLIR_PYTHON_QUALNAME("ir.Context._CAPIPtr")
Definition at line 67 of file Interop.h.
Referenced by mlirPythonCapsuleToContext(), and mlirPythonContextToCapsule().
MLIR_PYTHON_CAPSULE_DIALECT_REGISTRY
#define MLIR_PYTHON_CAPSULE_DIALECT_REGISTRY MAKE_MLIR_PYTHON_QUALNAME("ir.DialectRegistry._CAPIPtr")
Definition at line 69 of file Interop.h.
Referenced by mlirPythonCapsuleToDialectRegistry(), and mlirPythonDialectRegistryToCapsule().
MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE
#define MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE MAKE_MLIR_PYTHON_QUALNAME("execution_engine.ExecutionEngine._CAPIPtr")
Definition at line 71 of file Interop.h.
Referenced by mlirPythonCapsuleToExecutionEngine(), and mlirPythonExecutionEngineToCapsule().
MLIR_PYTHON_CAPSULE_INTEGER_SET
#define MLIR_PYTHON_CAPSULE_INTEGER_SET MAKE_MLIR_PYTHON_QUALNAME("ir.IntegerSet._CAPIPtr")
Definition at line 73 of file Interop.h.
Referenced by mlirPythonCapsuleToIntegerSet(), and mlirPythonIntegerSetToCapsule().
MLIR_PYTHON_CAPSULE_LOCATION
#define MLIR_PYTHON_CAPSULE_LOCATION MAKE_MLIR_PYTHON_QUALNAME("ir.Location._CAPIPtr")
Definition at line 75 of file Interop.h.
Referenced by mlirPythonCapsuleToLocation(), and mlirPythonLocationToCapsule().
MLIR_PYTHON_CAPSULE_MODULE
#define MLIR_PYTHON_CAPSULE_MODULE MAKE_MLIR_PYTHON_QUALNAME("ir.Module._CAPIPtr")
Definition at line 77 of file Interop.h.
Referenced by mlirPythonCapsuleToModule(), and mlirPythonModuleToCapsule().
MLIR_PYTHON_CAPSULE_OPERATION
#define MLIR_PYTHON_CAPSULE_OPERATION MAKE_MLIR_PYTHON_QUALNAME("ir.Operation._CAPIPtr")
Definition at line 79 of file Interop.h.
Referenced by mlirPythonCapsuleToOperation(), and mlirPythonOperationToCapsule().
MLIR_PYTHON_CAPSULE_PASS_MANAGER
#define MLIR_PYTHON_CAPSULE_PASS_MANAGER MAKE_MLIR_PYTHON_QUALNAME("passmanager.PassManager._CAPIPtr")
Definition at line 82 of file Interop.h.
Referenced by mlirPythonCapsuleToFrozenRewritePatternSet(), mlirPythonCapsuleToPassManager(), mlirPythonFrozenRewritePatternSetToCapsule(), and mlirPythonPassManagerToCapsule().
MLIR_PYTHON_CAPSULE_TYPE
#define MLIR_PYTHON_CAPSULE_TYPE MAKE_MLIR_PYTHON_QUALNAME("ir.Type._CAPIPtr")
Definition at line 81 of file Interop.h.
Referenced by mlirPythonCapsuleToType(), and mlirPythonTypeToCapsule().
MLIR_PYTHON_CAPSULE_TYPEID
#define MLIR_PYTHON_CAPSULE_TYPEID MAKE_MLIR_PYTHON_QUALNAME("ir.TypeID._CAPIPtr")
Definition at line 85 of file Interop.h.
Referenced by mlirPythonCapsuleToTypeID(), and mlirPythonTypeIDToCapsule().
MLIR_PYTHON_CAPSULE_VALUE
#define MLIR_PYTHON_CAPSULE_VALUE MAKE_MLIR_PYTHON_QUALNAME("ir.Value._CAPIPtr")
Definition at line 84 of file Interop.h.
Referenced by mlirPythonCapsuleToValue(), and mlirPythonValueToCapsule().
MLIR_PYTHON_GET_WRAPPED_POINTER
#define MLIR_PYTHON_GET_WRAPPED_POINTER (object)
Value:
(void *)(object.ptr)
Gets a void* from a wrapped struct.
Needed because const cast is different between C/C++.
Definition at line 150 of file Interop.h.
Referenced by mlirPythonAffineExprToCapsule(), mlirPythonAffineMapToCapsule(), mlirPythonAttributeToCapsule(), mlirPythonBlockToCapsule(), mlirPythonExecutionEngineToCapsule(), mlirPythonFrozenRewritePatternSetToCapsule(), mlirPythonIntegerSetToCapsule(), mlirPythonLocationToCapsule(), mlirPythonModuleToCapsule(), mlirPythonPassManagerToCapsule(), mlirPythonTypeIDToCapsule(), mlirPythonTypeToCapsule(), and mlirPythonValueToCapsule().
MLIR_PYTHON_MAYBE_DOWNCAST_ATTR
#define MLIR_PYTHON_MAYBE_DOWNCAST_ATTR "maybe_downcast"
Attribute on MLIR Python objects that expose a function for downcasting the corresponding Python object to a subclass if the object is in fact a subclass (Concrete or mlir_type_subclass) of ir.Type.
The signature of the function is: def maybe_downcast(self) -> object where the resulting object will (possibly) be an instance of the subclass.
Definition at line 118 of file Interop.h.
Referenced by pybind11::detail::type_caster< MlirAttribute >::cast(), pybind11::detail::type_caster< MlirType >::cast(), pybind11::detail::type_caster< MlirValue >::cast(), nanobind::detail::type_caster< MlirAttribute >::from_cpp(), nanobind::detail::type_caster< MlirType >::from_cpp(), and nanobind::detail::type_caster< MlirValue >::from_cpp().
MLIR_PYTHON_PACKAGE_PREFIX
#define MLIR_PYTHON_PACKAGE_PREFIX mlir.
Definition at line 51 of file Interop.h.
MLIR_PYTHON_STRINGIZE
#define MLIR_PYTHON_STRINGIZE (s)
Value:
#s
Definition at line 55 of file Interop.h.
MLIR_PYTHON_STRINGIZE_ARG
#define MLIR_PYTHON_STRINGIZE_ARG (arg)
Value:
MLIR_PYTHON_STRINGIZE(arg)
Definition at line 56 of file Interop.h.
Function Documentation
mlirPythonAffineExprToCapsule()
PyObject * mlirPythonAffineExprToCapsule (MlirAffineExpr expr) inline static
Creates a capsule object encapsulating the raw C-API MlirAffineExpr.
The returned capsule does not extend or affect ownership of any Python objects that reference the expression in any way.
Definition at line 161 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_EXPR, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by mlir::python::PyAffineExpr::getCapsule().
mlirPythonAffineMapToCapsule()
PyObject * mlirPythonAffineMapToCapsule (MlirAffineMap affineMap) inline static
Creates a capsule object encapsulating the raw C-API MlirAffineMap.
The returned capsule does not extend or affect ownership of any Python objects that reference the type in any way.
Definition at line 386 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_MAP, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirAffineMap >::cast(), nanobind::detail::type_caster< MlirAffineMap >::from_cpp(), and mlir::python::PyAffineMap::getCapsule().
mlirPythonAttributeToCapsule()
PyObject * mlirPythonAttributeToCapsule (MlirAttribute attribute) inline static
Creates a capsule object encapsulating the raw C-API MlirAttribute.
The returned capsule does not extend or affect ownership of any Python objects that reference the attribute in any way.
Definition at line 180 of file Interop.h.
References MLIR_PYTHON_CAPSULE_ATTRIBUTE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirAttribute >::cast(), nanobind::detail::type_caster< MlirAttribute >::from_cpp(), and mlir::python::PyAttribute::getCapsule().
mlirPythonBlockToCapsule()
PyObject * mlirPythonBlockToCapsule (MlirBlock block) inline static
Creates a capsule object encapsulating the raw C-API MlirBlock.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 198 of file Interop.h.
References MLIR_PYTHON_CAPSULE_BLOCK, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by mlir::python::PyBlock::getCapsule().
mlirPythonCapsuleToAffineExpr()
MlirAffineExpr mlirPythonCapsuleToAffineExpr (PyObject * capsule) inline static
Extracts an MlirAffineExpr from a capsule as produced from mlirPythonAffineExprToCapsule.
If the capsule is not of the right type, then a null expression is returned (as checked via mlirAffineExprIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 170 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_EXPR.
Referenced by mlir::python::PyAffineExpr::createFromCapsule().
mlirPythonCapsuleToAffineMap()
MlirAffineMap mlirPythonCapsuleToAffineMap (PyObject * capsule) inline static
Extracts an MlirAffineMap from a capsule as produced from mlirPythonAffineMapToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirAffineMapIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 395 of file Interop.h.
References MLIR_PYTHON_CAPSULE_AFFINE_MAP.
Referenced by mlir::python::PyAffineMap::createFromCapsule(), and pybind11::detail::type_caster< MlirAffineMap >::load().
mlirPythonCapsuleToAttribute()
MlirAttribute mlirPythonCapsuleToAttribute (PyObject * capsule) inline static
Extracts an MlirAttribute from a capsule as produced from mlirPythonAttributeToCapsule.
If the capsule is not of the right type, then a null attribute is returned (as checked via mlirAttributeIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 189 of file Interop.h.
References MLIR_PYTHON_CAPSULE_ATTRIBUTE.
Referenced by mlir::python::PyAttribute::createFromCapsule(), and pybind11::detail::type_caster< MlirAttribute >::load().
mlirPythonCapsuleToBlock()
MlirBlock mlirPythonCapsuleToBlock (PyObject * capsule) inline static
Extracts an MlirBlock from a capsule as produced from mlirPythonBlockToCapsule.
If the capsule is not of the right type, then a null pass manager is returned (as checked via mlirBlockIsNull).
Definition at line 206 of file Interop.h.
References MLIR_PYTHON_CAPSULE_BLOCK.
Referenced by pybind11::detail::type_caster< MlirBlock >::load().
mlirPythonCapsuleToContext()
MlirContext mlirPythonCapsuleToContext (PyObject * capsule) inline static
Extracts a MlirContext from a capsule as produced from mlirPythonContextToCapsule.
If the capsule is not of the right type, then a null context is returned (as checked via mlirContextIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 224 of file Interop.h.
References MLIR_PYTHON_CAPSULE_CONTEXT.
Referenced by mlir::python::PyMlirContext::createFromCapsule(), and pybind11::detail::type_caster< MlirContext >::load().
mlirPythonCapsuleToDialectRegistry()
MlirDialectRegistry mlirPythonCapsuleToDialectRegistry (PyObject * capsule) inline static
Extracts an MlirDialectRegistry from a capsule as produced from mlirPythonDialectRegistryToCapsule.
If the capsule is not of the right type, then a null context is returned (as checked via mlirContextIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 245 of file Interop.h.
References MLIR_PYTHON_CAPSULE_DIALECT_REGISTRY.
Referenced by mlir::python::PyDialectRegistry::createFromCapsule(), and pybind11::detail::type_caster< MlirDialectRegistry >::load().
mlirPythonCapsuleToExecutionEngine()
MlirExecutionEngine mlirPythonCapsuleToExecutionEngine (PyObject * capsule) inline static
Extracts an MlirExecutionEngine from a capsule as produced from mlirPythonIntegerSetToCapsule.
If the capsule is not of the right type, then a null set is returned (as checked via mlirExecutionEngineIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 434 of file Interop.h.
References MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE.
mlirPythonCapsuleToFrozenRewritePatternSet()
MlirFrozenRewritePatternSet mlirPythonCapsuleToFrozenRewritePatternSet (PyObject * capsule) inline static
Extracts an MlirFrozenRewritePatternSet from a capsule as produced from mlirPythonFrozenRewritePatternSetToCapsule.
If the capsule is not of the right type, then a null module is returned.
Definition at line 302 of file Interop.h.
References MLIR_PYTHON_CAPSULE_PASS_MANAGER.
Referenced by pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::load().
mlirPythonCapsuleToIntegerSet()
MlirIntegerSet mlirPythonCapsuleToIntegerSet (PyObject * capsule) inline static
Extracts an MlirIntegerSet from a capsule as produced from mlirPythonIntegerSetToCapsule.
If the capsule is not of the right type, then a null set is returned (as checked via mlirIntegerSetIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 414 of file Interop.h.
References MLIR_PYTHON_CAPSULE_INTEGER_SET.
Referenced by mlir::python::PyIntegerSet::createFromCapsule().
mlirPythonCapsuleToLocation()
MlirLocation mlirPythonCapsuleToLocation (PyObject * capsule) inline static
Extracts an MlirLocation from a capsule as produced from mlirPythonLocationToCapsule.
If the capsule is not of the right type, then a null module is returned (as checked via mlirLocationIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 264 of file Interop.h.
References MLIR_PYTHON_CAPSULE_LOCATION.
Referenced by mlir::python::PyLocation::createFromCapsule(), and pybind11::detail::type_caster< MlirLocation >::load().
mlirPythonCapsuleToModule()
MlirModule mlirPythonCapsuleToModule (PyObject * capsule) inline static
Extracts an MlirModule from a capsule as produced from mlirPythonModuleToCapsule.
If the capsule is not of the right type, then a null module is returned (as checked via mlirModuleIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 282 of file Interop.h.
References MLIR_PYTHON_CAPSULE_MODULE.
Referenced by mlir::python::PyModule::createFromCapsule(), and pybind11::detail::type_caster< MlirModule >::load().
mlirPythonCapsuleToOperation()
MlirOperation mlirPythonCapsuleToOperation (PyObject * capsule) inline static
Extracts an MlirOperations from a capsule as produced from mlirPythonOperationToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirOperationIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 338 of file Interop.h.
References MLIR_PYTHON_CAPSULE_OPERATION.
Referenced by mlir::python::PyOperation::createFromCapsule(), and pybind11::detail::type_caster< MlirOperation >::load().
mlirPythonCapsuleToPassManager()
MlirPassManager mlirPythonCapsuleToPassManager (PyObject * capsule) inline static
Extracts an MlirPassManager from a capsule as produced from mlirPythonPassManagerToCapsule.
If the capsule is not of the right type, then a null pass manager is returned (as checked via mlirPassManagerIsNull).
Definition at line 320 of file Interop.h.
References MLIR_PYTHON_CAPSULE_PASS_MANAGER.
Referenced by pybind11::detail::type_caster< MlirPassManager >::load().
mlirPythonCapsuleToType()
MlirType mlirPythonCapsuleToType (PyObject * capsule) inline static
Extracts an MlirType from a capsule as produced from mlirPythonTypeToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirTypeIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 376 of file Interop.h.
References MLIR_PYTHON_CAPSULE_TYPE.
Referenced by mlir::python::PyType::createFromCapsule(), and pybind11::detail::type_caster< MlirType >::load().
mlirPythonCapsuleToTypeID()
MlirTypeID mlirPythonCapsuleToTypeID (PyObject * capsule) inline static
Extracts an MlirTypeID from a capsule as produced from mlirPythonTypeIDToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirTypeIDIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 357 of file Interop.h.
References MLIR_PYTHON_CAPSULE_TYPEID.
Referenced by mlir::python::PyTypeID::createFromCapsule(), and pybind11::detail::type_caster< MlirTypeID >::load().
mlirPythonCapsuleToValue()
MlirValue mlirPythonCapsuleToValue (PyObject * capsule) inline static
Extracts an MlirValue from a capsule as produced from mlirPythonValueToCapsule.
If the capsule is not of the right type, then a null type is returned (as checked via mlirValueIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 454 of file Interop.h.
References MLIR_PYTHON_CAPSULE_VALUE.
Referenced by mlir::python::PyValue::createFromCapsule(), and pybind11::detail::type_caster< MlirValue >::load().
mlirPythonContextToCapsule()
PyObject * mlirPythonContextToCapsule (MlirContext context) inline static
Creates a capsule object encapsulating the raw C-API MlirContext.
The returned capsule does not extend or affect ownership of any Python objects that reference the context in any way.
Definition at line 216 of file Interop.h.
References MLIR_PYTHON_CAPSULE_CONTEXT.
Referenced by mlir::python::PyMlirContext::getCapsule().
mlirPythonDialectRegistryToCapsule()
PyObject * mlirPythonDialectRegistryToCapsule (MlirDialectRegistry registry) inline static
Creates a capsule object encapsulating the raw C-API MlirDialectRegistry.
The returned capsule does not extend or affect ownership of any Python objects that reference the context in any way.
Definition at line 235 of file Interop.h.
References MLIR_PYTHON_CAPSULE_DIALECT_REGISTRY.
Referenced by pybind11::detail::type_caster< MlirDialectRegistry >::cast(), nanobind::detail::type_caster< MlirDialectRegistry >::from_cpp(), and mlir::python::PyDialectRegistry::getCapsule().
mlirPythonExecutionEngineToCapsule()
PyObject * mlirPythonExecutionEngineToCapsule (MlirExecutionEngine jit) inline static
Creates a capsule object encapsulating the raw C-API MlirExecutionEngine.
The returned capsule does not extend or affect ownership of any Python objects that reference the set in any way.
Definition at line 424 of file Interop.h.
References MLIR_PYTHON_CAPSULE_EXECUTION_ENGINE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
mlirPythonFrozenRewritePatternSetToCapsule()
PyObject * mlirPythonFrozenRewritePatternSetToCapsule (MlirFrozenRewritePatternSet pm) inline static
Creates a capsule object encapsulating the raw C-API MlirFrozenRewritePatternSet.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 293 of file Interop.h.
References MLIR_PYTHON_CAPSULE_PASS_MANAGER, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::cast(), and nanobind::detail::type_caster< MlirFrozenRewritePatternSet >::from_cpp().
mlirPythonIntegerSetToCapsule()
PyObject * mlirPythonIntegerSetToCapsule (MlirIntegerSet integerSet) inline static
Creates a capsule object encapsulating the raw C-API MlirIntegerSet.
The returned capsule does not extend or affect ownership of any Python objects that reference the set in any way.
Definition at line 405 of file Interop.h.
References MLIR_PYTHON_CAPSULE_INTEGER_SET, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by mlir::python::PyIntegerSet::getCapsule().
mlirPythonLocationToCapsule()
PyObject * mlirPythonLocationToCapsule (MlirLocation loc) inline static
Creates a capsule object encapsulating the raw C-API MlirLocation.
The returned capsule does not extend or affect ownership of any Python objects that reference the location in any way.
Definition at line 255 of file Interop.h.
References MLIR_PYTHON_CAPSULE_LOCATION, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirLocation >::cast(), nanobind::detail::type_caster< MlirLocation >::from_cpp(), and mlir::python::PyLocation::getCapsule().
mlirPythonModuleToCapsule()
PyObject * mlirPythonModuleToCapsule (MlirModule module) inline static
Creates a capsule object encapsulating the raw C-API MlirModule.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 273 of file Interop.h.
References MLIR_PYTHON_CAPSULE_MODULE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirModule >::cast(), nanobind::detail::type_caster< MlirModule >::from_cpp(), and mlir::python::PyModule::getCapsule().
mlirPythonOperationToCapsule()
PyObject * mlirPythonOperationToCapsule (MlirOperation operation) inline static
Creates a capsule object encapsulating the raw C-API MlirOperation.
The returned capsule does not extend or affect ownership of any Python objects that reference the operation in any way.
Definition at line 330 of file Interop.h.
References MLIR_PYTHON_CAPSULE_OPERATION.
Referenced by pybind11::detail::type_caster< MlirOperation >::cast(), nanobind::detail::type_caster< MlirOperation >::from_cpp(), and mlir::python::PyOperation::getCapsule().
mlirPythonPassManagerToCapsule()
PyObject * mlirPythonPassManagerToCapsule (MlirPassManager pm) inline static
Creates a capsule object encapsulating the raw C-API MlirPassManager.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 311 of file Interop.h.
References MLIR_PYTHON_CAPSULE_PASS_MANAGER, and MLIR_PYTHON_GET_WRAPPED_POINTER.
mlirPythonTypeIDToCapsule()
PyObject * mlirPythonTypeIDToCapsule (MlirTypeID typeID) inline static
Creates a capsule object encapsulating the raw C-API MlirTypeID.
The returned capsule does not extend or affect ownership of any Python objects that reference the type in any way.
Definition at line 348 of file Interop.h.
References MLIR_PYTHON_CAPSULE_TYPEID, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirTypeID >::cast(), nanobind::detail::type_caster< MlirTypeID >::from_cpp(), and mlir::python::PyTypeID::getCapsule().
mlirPythonTypeToCapsule()
PyObject * mlirPythonTypeToCapsule (MlirType type) inline static
Creates a capsule object encapsulating the raw C-API MlirType.
The returned capsule does not extend or affect ownership of any Python objects that reference the type in any way.
Definition at line 367 of file Interop.h.
References MLIR_PYTHON_CAPSULE_TYPE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirType >::cast(), nanobind::detail::type_caster< MlirType >::from_cpp(), and mlir::python::PyType::getCapsule().
mlirPythonValueToCapsule()
PyObject * mlirPythonValueToCapsule (MlirValue value) inline static
Creates a capsule object encapsulating the raw C-API MlirValue.
The returned capsule does not extend or affect ownership of any Python objects that reference the operation in any way.
Definition at line 445 of file Interop.h.
References MLIR_PYTHON_CAPSULE_VALUE, and MLIR_PYTHON_GET_WRAPPED_POINTER.
Referenced by pybind11::detail::type_caster< MlirValue >::cast(), nanobind::detail::type_caster< MlirValue >::from_cpp(), and mlir::python::PyValue::getCapsule().