MLIR: lib/Dialect/Arith/Transforms/IntRangeOptimizations.cpp File Reference
IntRangeOptimizations.cpp File Reference
#include <utility>
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
#include "mlir/Analysis/DataFlow/IntegerRangeAnalysis.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::arith
Macros
#define GEN_PASS_DEF_ARITHINTRANGEOPTS
Functions
static bool intersects (const ConstantIntRanges &lhs, const ConstantIntRanges &rhs)
Returns true if 2 integer ranges have intersection.
static FailureOr< bool > handleEq (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleNe (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleSlt (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleSle (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleSgt (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleSge (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleUlt (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleUle (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleUgt (ConstantIntRanges lhs, ConstantIntRanges rhs)
static FailureOr< bool > handleUge (ConstantIntRanges lhs, ConstantIntRanges rhs)
Macro Definition Documentation
GEN_PASS_DEF_ARITHINTRANGEOPTS
#define GEN_PASS_DEF_ARITHINTRANGEOPTS
Definition at line 19 of file IntRangeOptimizations.cpp.
Function Documentation
handleEq()
static FailureOr<bool> handleEq (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 34 of file IntRangeOptimizations.cpp.
References mlir::failure(), and intersects().
handleNe()
static FailureOr<bool> handleNe (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 41 of file IntRangeOptimizations.cpp.
References mlir::failure(), and intersects().
handleSge()
static FailureOr<bool> handleSge (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 72 of file IntRangeOptimizations.cpp.
References handleSle().
handleSgt()
static FailureOr<bool> handleSgt (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 68 of file IntRangeOptimizations.cpp.
References handleSlt().
handleSle()
static FailureOr<bool> handleSle (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 58 of file IntRangeOptimizations.cpp.
References mlir::failure(), mlir::ConstantIntRanges::smax(), and mlir::ConstantIntRanges::smin().
Referenced by handleSge().
handleSlt()
static FailureOr<bool> handleSlt (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 48 of file IntRangeOptimizations.cpp.
References mlir::failure(), mlir::ConstantIntRanges::smax(), and mlir::ConstantIntRanges::smin().
Referenced by handleSgt().
handleUge()
static FailureOr<bool> handleUge (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 100 of file IntRangeOptimizations.cpp.
References handleUle().
handleUgt()
static FailureOr<bool> handleUgt (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 96 of file IntRangeOptimizations.cpp.
References handleUlt().
handleUle()
static FailureOr<bool> handleUle (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 86 of file IntRangeOptimizations.cpp.
References mlir::failure(), mlir::ConstantIntRanges::umax(), and mlir::ConstantIntRanges::umin().
Referenced by handleUge().
handleUlt()
static FailureOr<bool> handleUlt (ConstantIntRanges lhs, ConstantIntRanges rhs) static
Definition at line 76 of file IntRangeOptimizations.cpp.
References mlir::failure(), mlir::ConstantIntRanges::umax(), and mlir::ConstantIntRanges::umin().
Referenced by handleUgt().
intersects()
static bool intersects (const ConstantIntRanges & lhs, const ConstantIntRanges & rhs) static
Returns true if 2 integer ranges have intersection.
Definition at line 28 of file IntRangeOptimizations.cpp.
References mlir::ConstantIntRanges::smax(), mlir::ConstantIntRanges::smin(), mlir::ConstantIntRanges::umax(), and mlir::ConstantIntRanges::umin().
Referenced by computeIntersectionBuckets(), handleEq(), and handleNe().