MLIR: lib/IR/Operation.cpp File Reference
Operation.cpp File Reference
#include "mlir/IR/Operation.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/FoldInterfaces.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/ErrorHandling.h"
#include <numeric>
#include <optional>
Functions
static void checkFoldResultTypes (Operation *op, SmallVectorImpl< OpFoldResult > &results)
Assert that the folded results (in case of values) have the same type as the results of the given op.
static Type getTensorOrVectorElementType (Type type)
If this is a vector type, or a tensor type, return the scalar element type that it is built around, otherwise return the type unmodified.
static LogicalResult verifyTerminatorSuccessors (Operation *op)
Function Documentation
checkFoldResultTypes()
void checkFoldResultTypes (Operation * op, SmallVectorImpl< OpFoldResult > & results) static
Assert that the folded results (in case of values) have the same type as the results of the given op.
Definition at line 610 of file Operation.cpp.
References mlir::Operation::emitOpError(), and mlir::Operation::getResults().
Referenced by mlir::Operation::fold().
getTensorOrVectorElementType()
Type getTensorOrVectorElementType (Type type) static
If this is a vector type, or a tensor type, return the scalar element type that it is built around, otherwise return the type unmodified.
Definition at line 926 of file Operation.cpp.
References getTensorOrVectorElementType().
Referenced by getTensorOrVectorElementType(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), and mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike().
verifyTerminatorSuccessors()
LogicalResult verifyTerminatorSuccessors (Operation * op) static
Definition at line 1188 of file Operation.cpp.
References mlir::Operation::emitError(), mlir::Operation::getParentRegion(), mlir::Operation::getSuccessors(), and success().
Referenced by mlir::OpTrait::impl::verifyAtLeastNSuccessors(), mlir::OpTrait::impl::verifyNSuccessors(), and mlir::OpTrait::impl::verifyOneSuccessor().