MLIR: lib/Dialect/IRDL/IRDLSymbols.cpp File Reference
IRDLSymbols.cpp File Reference
#include "mlir/Dialect/IRDL/IRDLSymbols.h"
#include "mlir/Dialect/IRDL/IR/IRDL.h"
Functions
static Operation * lookupDialectOp (Operation *source)
Function Documentation
lookupDialectOp()
Operation * lookupDialectOp (Operation * source) static
Definition at line 15 of file IRDLSymbols.cpp.
References mlir::Operation::getParentOp().
Referenced by mlir::irdl::lookupSymbolNearDialect(), and mlir::irdl::lookupSymbolNearDialect().