MLIR: lib/Dialect/SparseTensor/Transforms/Utils/IterationGraphSorter.cpp File Reference
IterationGraphSorter.cpp File Reference
#include "IterationGraphSorter.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/BuiltinTypes.h"
Functions
static bool includesAny (SortMask mask1, SortMask mask2)
static bool includesDenseInput (SortMask mask)
static bool includesDenseOutput (SortMask mask)
static unsigned getLoopSparsityRank (unsigned loop, ArrayRef< Value > allTensors, ArrayRef< AffineMap > allMaps)
Returns a sparsity rank for loop ordering: lower values indicate dimensions that should be placed in outer loops.
Function Documentation
getLoopSparsityRank()
unsigned getLoopSparsityRank (unsigned loop, ArrayRef< Value > allTensors, ArrayRef< AffineMap > allMaps) static
Returns a sparsity rank for loop ordering: lower values indicate dimensions that should be placed in outer loops.
0 = Dense, 1 = Compressed, 2 = Singleton, 3 = Other/Unknown.
Definition at line 86 of file IterationGraphSorter.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::isCompressedLT(), mlir::sparse_tensor::isDenseLT(), and mlir::sparse_tensor::isSingletonLT().
includesAny()
bool includesAny (SortMask mask1, SortMask mask2) inline static
Definition at line 71 of file IterationGraphSorter.cpp.
Referenced by includesDenseInput(), and includesDenseOutput().
includesDenseInput()
bool includesDenseInput (SortMask mask) inline static
Definition at line 75 of file IterationGraphSorter.cpp.
References includesAny(), and mlir::sparse_tensor::kIncludeDenseInput.
Referenced by mlir::sparse_tensor::IterationGraphSorter::sort().
includesDenseOutput()
bool includesDenseOutput (SortMask mask) inline static
Definition at line 79 of file IterationGraphSorter.cpp.
References includesAny(), and mlir::sparse_tensor::kIncludeDenseOutput.
Referenced by mlir::sparse_tensor::IterationGraphSorter::sort().