MLIR: lib/Dialect/Linalg/TransformOps/LinalgMatchOps.cpp File Reference
LinalgMatchOps.cpp File Reference
#include "mlir/Dialect/Linalg/TransformOps/LinalgMatchOps.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.h"
#include "mlir/Dialect/Linalg/TransformOps/Syntax.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Transform/IR/TransformTypes.h"
#include "mlir/Dialect/Transform/Interfaces/MatchInterfaces.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "llvm/Support/DebugLog.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/InterleavedRange.h"
#include "mlir/Dialect/Linalg/TransformOps/LinalgMatchOps.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-transforms"
#define GET_OP_CLASSES
Functions
static DiagnosedSilenceableFailure containsAll (ArrayRef< unsigned > reference, ArrayRef< int64_t > list, Location loc, const char *message)
Checks if all values from list are also contained in reference.
template<typename OpTy>
LogicalResult verifyStructuredOperandOp (OpTy op)
Verifies a matcher op for structured input or output, specifically the attributes specifying the operand positions.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 24 of file LinalgMatchOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 714 of file LinalgMatchOps.cpp.
Function Documentation
containsAll()
DiagnosedSilenceableFailure containsAll (ArrayRef< unsigned > reference, ArrayRef< int64_t > list, Location loc, const char * message) static
Checks if all values from list are also contained in reference.
Returns a silenceable error with the given message at the given location when it is not the case. The error message must contain the "{0}" placeholder that will be substituted with the value from list that is not contained in reference.
Definition at line 321 of file LinalgMatchOps.cpp.
References mlir::emitSilenceableFailure(), and mlir::DiagnosedSilenceableFailure::success().
verifyStructuredOperandOp()
template<typename OpTy> LogicalResult verifyStructuredOperandOp (OpTy op)
Verifies a matcher op for structured input or output, specifically the attributes specifying the operand positions.
Definition at line 496 of file LinalgMatchOps.cpp.
References success().