MLIR: lib/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp File Reference
LinalgTransformOps.cpp File Reference
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.h"
#include "mlir/AsmParser/AsmParser.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/TransformOps/GPUHeuristics.h"
#include "mlir/Dialect/Linalg/TransformOps/Syntax.h"
#include "mlir/Dialect/Linalg/Transforms/Hoisting.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/Transforms/TileUsingInterface.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformTypes.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/Dialect/Transform/Utils/Utils.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
#include "mlir/Dialect/Vector/Transforms/VectorRewritePatterns.h"
#include "mlir/IR/BuiltinTypeInterfaces.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/TilingInterface.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/DebugLog.h"
#include "llvm/Support/LogicalResult.h"
#include <type_traits>
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOpsEnums.cpp.inc"
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DOWNSCALE(trans)
#define DOWNSCALE_CALL(a, b) DownscaleSizeOneWindowed2DConvolution<a, b>
#define DOWNSCALE_NORMAL(a, b) DOWNSCALE(DOWNSCALE_CALL(a, b))
#define GET_OP_CLASSES
Functions
template<typename PatternTy , typename... Args>
static FailureOr< LinalgOp > tryApply (Operation *operation, Args &&...args)
Attempts to apply the pattern specified as template argument to the given operation.
static DiagnosedSilenceableFailure unpackSingleIndexResultPayloadOperations (transform::TransformState &state, TransformOpInterface transformOp, SmallVector< OpFoldResult > &result, ArrayRef< OpFoldResult > ofrs)
Assuming that ofr is an index attr or a param of index type or a transform dialect handle mapped to exactly one op with one index result, return that value.
static DiagnosedSilenceableFailure unpackSingleIndexResultPayloadOperations (transform::TransformState &state, TransformOpInterface transformOp, SmallVector< OpFoldResult > &result, Value packedHandle)
static DiagnosedSilenceableFailure reifyMixedParamAndHandleResults (TransformState &state, TransformOpInterface &transformOp, ArrayRef< OpFoldResult > mixedResults, SmallVectorImpl< int64_t > &reified)
When possible, converts each OpFoldResult in mixedResult to an integer if the value can be statically inferred.
template<typename Range >
static LogicalResult applyTilingToAll (RewriterBase &rewriter, Operation *transformOp, Range &&payloadOps, unsigned numLoops, transform::TransformResults &transformResults, function_ref< FailureOr< scf::SCFTileAndFuseResult >(TilingInterface)> applyFn)
Apply a tiling transformation to all payload ops and store both the tiled operation as well as the created tile loops.
static Operation * replaceForAllWithNewSignature (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp, TilingResult &tileAndFuseResult, int64_t resultNumber, SmallVector< OpFoldResult > &offsets, SmallVector< OpFoldResult > &sizes)
Add new operands to the forall op for users of the producerOp that are dominated by the containing scf.forall op.
static bool sameOrEquivalentIterArg (Value src, Value dst)
Given two operands coming from a loop iter arg, 'src' and 'dst', return true if the operand 'src' is equal to 'dst' or equal to a iter arg present in a outer loop.
static std::tuple< SmallVector< Operation * >, Operation * > tileAndFuseFirstExtractUse (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp)
Find the first "extract" user of producerOp and tile it right before its use.
static SmallVector< Operation * > tileAndFuseFirstExtractUseThroughContainingOpBlockArgument (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp)
First, find the first "scf::ForallOp" user of producerOp and ensure it is exactly the containingOp, otherwise bail.
static Operation * cloneAndFuseFirstUse (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp)
static void printMultitileSizesTypes (OpAsmPrinter &printer, Operation *op, Type targetType, Type lowSizeType, Type, Type)
static ParseResult parseMultitileSizesTypes (OpAsmParser &parser, Type &targetType, Type &lowSizeType, Type &highSizeType, Type &splitPointType)
template<typename RelayoutOpTy >
bool isValidPackingPermutation (RelayoutOpTy op, ArrayRef< int64_t > permutation, OuterOrInnerPerm outerOrInnerPerm=OuterOrInnerPerm::Outer)
Return true if permutation is a valid permutation of the outer_dims_perm (case OuterOrInnerPerm::Outer) or inner_dims_pos (OuterOrInnerPerm::Inner) of the tensor.pack or tensor.unpack op.
static void printContinuousTileSizeTypes (OpAsmPrinter &printer, Operation *op, Type targetType, Type tile_sizes, Type)
static ParseResult parseContinuousTileSizeTypes (OpAsmParser &parser, Type &targetType, Type &tileSizesType, Type &chunkSizesType)
static SmallVector< OpFoldResult > normalizeUpperBounds (RewriterBase &rewriter, Location loc, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > ubs, ArrayRef< OpFoldResult > steps)
Given lbs, ubs and steps of loops, return (for each loop), the normalized upper bound.
static SmallVector< Value > denormalizeIndVar (RewriterBase &rewriter, Location loc, ValueRange ivs, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > steps)
When a loop is normalized, the uses of the induction variable within the loop need to replaced with original_lb + old_iv * original_step.
static scf::ForallOp normalizeForallLoopOp (RewriterBase &rewriter, scf::ForallOp loop)
Given a scf.forall loop return a loop op with the loop bounds normalized.
template<typename OpTy >
DiagnosedSilenceableFailure doit (RewriterBase &rewriter, OpTy target, transform::ApplyToEachResultList &results, transform::TransformState &state)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 51 of file LinalgTransformOps.cpp.
DOWNSCALE
#define DOWNSCALE (trans)
Value:
  {                                                                            \
    FailureOr<LinalgOp> res = tryApply<trans>(target);                         \
    if (succeeded(res)) {                                                      \
      results.push_back(*res);                                                 \
      return DiagnosedSilenceableFailure::success();                           \
    }                                                                          \
  }
DOWNSCALE_CALL
#define DOWNSCALE_CALL (a, b) DownscaleSizeOneWindowed2DConvolution<a, b>
DOWNSCALE_NORMAL
#define DOWNSCALE_NORMAL (a, b) DOWNSCALE(DOWNSCALE_CALL(a, b))
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 4314 of file LinalgTransformOps.cpp.
Function Documentation
applyTilingToAll()
template<typename Range > static LogicalResult applyTilingToAll (RewriterBase & rewriter, Operation * transformOp, Range && payloadOps, unsigned numLoops, transform::TransformResults & transformResults, function_ref< FailureOr< scf::SCFTileAndFuseResult >(TilingInterface)> applyFn) static
Apply a tiling transformation to all payload ops and store both the tiled operation as well as the created tile loops.
Definition at line 520 of file LinalgTransformOps.cpp.
References mlir::Operation::emitError(), mlir::RewriterBase::eraseOp(), mlir::Operation::getOpResult(), mlir::RewriterBase::replaceAllUsesWith(), mlir::transform::TransformResults::set(), and mlir::OpBuilder::setInsertionPoint().
cloneAndFuseFirstUse()
static Operation* cloneAndFuseFirstUse (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp) static
Definition at line 993 of file LinalgTransformOps.cpp.
References mlir::OpBuilder::clone(), diag(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getLoc(), mlir::Operation::getOpResults(), mlir::detail::IROperandBase::getOwner(), mlir::Operation::isProperAncestor(), mlir::RewriterBase::modifyOpInPlace(), and mlir::OpBuilder::setInsertionPoint().
denormalizeIndVar()
static SmallVector<Value> denormalizeIndVar (RewriterBase & rewriter, Location loc, ValueRange ivs, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > steps) static
When a loop is normalized, the uses of the induction variable within the loop need to replaced with original_lb + old_iv * original_step.
Definition at line 3582 of file LinalgTransformOps.cpp.
References mlir::bindDims(), mlir::bindSymbols(), mlir::Builder::getContext(), mlir::getValueOrCreateConstantIndexOp(), and mlir::affine::makeComposedFoldedAffineApply().
Referenced by normalizeForallLoopOp().
doit()
template<typename OpTy > DiagnosedSilenceableFailure doit (RewriterBase & rewriter, OpTy target, transform::ApplyToEachResultList & results, transform::TransformState & state)
Definition at line 4113 of file LinalgTransformOps.cpp.
Referenced by llvm::cast_convert_val< T, ::mlir::Dialect *, ::mlir::Dialect * >::doit(), and tileLinalgOpImpl().
isValidPackingPermutation()
template<typename RelayoutOpTy > bool isValidPackingPermutation (RelayoutOpTy op, ArrayRef< int64_t > permutation, OuterOrInnerPerm outerOrInnerPerm = OuterOrInnerPerm::Outer)
Return true if permutation is a valid permutation of the outer_dims_perm (case OuterOrInnerPerm::Outer) or inner_dims_pos (OuterOrInnerPerm::Inner) of the tensor.pack or tensor.unpack op.
This is the case when thepermutationrank matches the rank expected by opandpermutationis itself a permutation vector. Return true if eitheroporpermutation` are empty to allow a simpler polymorphic implementation.
Definition at line 1776 of file LinalgTransformOps.cpp.
References mlir::isPermutationVector().
normalizeForallLoopOp()
static scf::ForallOp normalizeForallLoopOp (RewriterBase & rewriter, scf::ForallOp loop) static
Given a scf.forall loop return a loop op with the loop bounds normalized.
TODO: Replace this with a general utility to normalize scf.forall. At the time of writing, this wasnt done since adding this to scf dialect would disallow using of affine.apply operations due to cyclic dependencies. To avoid churn in lit tests with the change this was added with, defer that to a follow up.
Definition at line 3609 of file LinalgTransformOps.cpp.
References denormalizeIndVar(), mlir::Builder::getIndexAttr(), mlir::isOneInteger(), mlir::isZeroInteger(), mlir::RewriterBase::mergeBlocks(), normalizeUpperBounds(), mlir::RewriterBase::replaceOp(), and mlir::OpBuilder::setInsertionPointToStart().
normalizeUpperBounds()
static SmallVector<OpFoldResult> normalizeUpperBounds (RewriterBase & rewriter, Location loc, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > ubs, ArrayRef< OpFoldResult > steps) static
Given lbs, ubs and steps of loops, return (for each loop), the normalized upper bound.
Definition at line 3565 of file LinalgTransformOps.cpp.
References mlir::bindSymbols(), mlir::Builder::getContext(), and mlir::affine::makeComposedFoldedAffineApply().
Referenced by normalizeForallLoopOp().
parseContinuousTileSizeTypes()
static ParseResult parseContinuousTileSizeTypes (OpAsmParser & parser, Type & targetType, Type & tileSizesType, Type & chunkSizesType) static
Definition at line 3207 of file LinalgTransformOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseType().
parseMultitileSizesTypes()
static ParseResult parseMultitileSizesTypes (OpAsmParser & parser, Type & targetType, Type & lowSizeType, Type & highSizeType, Type & splitPointType) static
Definition at line 1502 of file LinalgTransformOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseType().
printContinuousTileSizeTypes()
static void printContinuousTileSizeTypes (OpAsmPrinter & printer, Operation * op, Type targetType, Type tile_sizes, Type) static
Definition at line 3201 of file LinalgTransformOps.cpp.
References mlir::OpAsmPrinter::printFunctionalType().
printMultitileSizesTypes()
static void printMultitileSizesTypes (OpAsmPrinter & printer, Operation * op, Type targetType, Type lowSizeType, Type , Type) static
Definition at line 1496 of file LinalgTransformOps.cpp.
References mlir::OpAsmPrinter::printFunctionalType().
reifyMixedParamAndHandleResults()
static DiagnosedSilenceableFailure reifyMixedParamAndHandleResults (TransformState & state, TransformOpInterface & transformOp, ArrayRef< OpFoldResult > mixedResults, SmallVectorImpl< int64_t > & reified) static
When possible, converts each OpFoldResult in mixedResult to an integer if the value can be statically inferred.
If a result is a Value then it must be either a ParamType or a handle to an a constant like op.
Definition at line 173 of file LinalgTransformOps.cpp.
replaceForAllWithNewSignature()
static Operation* replaceForAllWithNewSignature (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp, TilingResult & tileAndFuseResult, int64_t resultNumber, SmallVector< OpFoldResult > & offsets, SmallVector< OpFoldResult > & sizes) static
Add new operands to the forall op for users of the producerOp that are dominated by the containing scf.forall op.
Definition at line 639 of file LinalgTransformOps.cpp.
References mlir::DominanceInfo::dominates(), mlir::detail::enumerate(), mlir::RewriterBase::eraseBlock(), mlir::Builder::getIndexAttr(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::Value::getUsers(), mlir::Operation::isAncestor(), mlir::RewriterBase::replaceAllUsesWith(), mlir::RewriterBase::replaceUsesWithIf(), mlir::OpBuilder::setInsertionPoint(), and mlir::TilingResult::tiledValues.
sameOrEquivalentIterArg()
static bool sameOrEquivalentIterArg (Value src, Value dst) static
Given two operands coming from a loop iter arg, 'src' and 'dst', return true if the operand 'src' is equal to 'dst' or equal to a iter arg present in a outer loop.
To determine the second condition, this function iterates using a worklist over the enclosing loops, trying to find 'src' in any of the parent loop's iter args.
Definition at line 721 of file LinalgTransformOps.cpp.
References mlir::OpOperand::getOperandNumber(), and mlir::Block::getParentOp().
tileAndFuseFirstExtractUse()
static std::tuple<SmallVector<Operation *>, Operation *> tileAndFuseFirstExtractUse (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp) static
Find the first "extract" user of producerOp and tile it right before its use.
The tiled op is fused under the containingOp. Return this fused op on success or nullptr if anything fails. If tiled op has uses that are dominated by containingOp, return a new containingOp with results of the fused op appended to results of the containingOp or nullptr if there are no dominated uses.
Definition at line 771 of file LinalgTransformOps.cpp.
References mlir::clone(), mlir::OpBuilder::clone(), diag(), mlir::Operation::getLoc(), mlir::Operation::getOperand(), mlir::RewriterBase::modifyOpInPlace(), and mlir::OpBuilder::setInsertionPoint().
tileAndFuseFirstExtractUseThroughContainingOpBlockArgument()
static SmallVector<Operation *> tileAndFuseFirstExtractUseThroughContainingOpBlockArgument (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp) static
First, find the first "scf::ForallOp" user of producerOp and ensure it is exactly the containingOp, otherwise bail.
Then, find the first "extract" user of the tied block argument and tile it right before its "extract" use. The tiled op is fused under the containingOp. Return this fused op on success or nullptr if anything fails.
Definition at line 891 of file LinalgTransformOps.cpp.
References mlir::OpBuilder::clone(), diag(), mlir::RewriterBase::eraseOp(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getLoc(), mlir::OpOperand::getOperandNumber(), mlir::tensor::getOrCreateDestinations(), mlir::Value::getUsers(), mlir::IRMapping::map(), mlir::RewriterBase::modifyOpInPlace(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), and mlir::Operation::setOperand().
tryApply()
template<typename PatternTy , typename... Args> static FailureOr<LinalgOp> tryApply (Operation * operation, Args &&... args) static
Attempts to apply the pattern specified as template argument to the given operation.
The pattern is expected to have a returningMatchAndRewrite function that returns the "main" result or failure. Returns failure if the pattern failed to apply. Extra arguments are forwarded to the pattern constructor.
Definition at line 59 of file LinalgTransformOps.cpp.
References mlir::Operation::getContext().
unpackSingleIndexResultPayloadOperations() [1/2]
static DiagnosedSilenceableFailure unpackSingleIndexResultPayloadOperations (transform::TransformState & state, TransformOpInterface transformOp, SmallVector< OpFoldResult > & result, ArrayRef< OpFoldResult > ofrs) static
Assuming that ofr is an index attr or a param of index type or a transform dialect handle mapped to exactly one op with one index result, return that value.
Definition at line 87 of file LinalgTransformOps.cpp.
unpackSingleIndexResultPayloadOperations() [2/2]
static DiagnosedSilenceableFailure unpackSingleIndexResultPayloadOperations (transform::TransformState & state, TransformOpInterface transformOp, SmallVector< OpFoldResult > & result, Value packedHandle) static
Definition at line 139 of file LinalgTransformOps.cpp.