MLIR: lib/Dialect/Linalg/IR/LinalgOps.cpp File Reference
LinalgOps.cpp File Reference
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Parser.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Linalg/IR/LinalgOpsDialect.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.tcgen.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yamlgen.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgOps.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define DEFINE_POOLING_OP_GET_EFFECTS(OP_NAME)
#define GET_OP_CLASSES
#define GET_OP_CLASSES
#define INSTANTIATE_WEIGHTED_POOLING_INPUT_INDEX(OP_TYPE)
#define LINALGOP_FOLDERS(XXX)
Functions
template<typename NamedStructuredOpType >
static void fillStructuredOpRegion (OpBuilder &opBuilder, Region &region, TypeRange inputTypes, TypeRange outputTypes, std::function< void(unsigned, unsigned)> errorHandler=nullptr)
Forward declarations.
template<typename NamedStructuredOpType >
static void createAndFillStructuredOpRegion (OpBuilder &opBuilder, OperationState &result, TypeRange inputTypes, TypeRange outputTypes)
Generic entry point to create both the region and the block of a LinalgOp.
static ParseResult parseCommonStructuredOpParts (OpAsmParser &parser, OperationState &result, SmallVectorImpl< Type > &inputTypes, SmallVectorImpl< Type > &outputTypes)
Common parsing and printing used for both named structured ops created by ods-gen and by manually defined C++ ops.
template<typename NamedStructuredOpType >
static void printCommonStructuredOpParts (OpAsmPrinter &p, NamedStructuredOpType op)
template<typename NamedStructuredOpType >
static ParseResult parseNamedStructuredOpRegion (OpAsmParser &parser, Region &region, TypeRange inputTypes, TypeRange outputTypes)
Specific parsing and printing for named structured ops created by ods-gen.
static ParseResult parseNamedStructuredOpResults (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes)
template<typename NamedStructuredOpType >
static ParseResult parseNamedStructuredOp (OpAsmParser &parser, OperationState &result)
static void printNamedStructuredOpResults (OpAsmPrinter &p, TypeRange resultTypes)
template<typename NamedStructuredOpType >
static void printNamedStructuredOp (OpAsmPrinter &p, NamedStructuredOpType op)
static SmallVector< Value > getAsValues (OpBuilder &b, Location loc, ArrayRef< OpFoldResult > valueOrAttrVec)
Helper function to convert a vector of OpFoldResults into a vector of Values.
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form
someop(memrefcast(%src)) -> someop(%src)
It folds the source of the memref.cast into the root operation directly.
static LogicalResult foldMemRefCastInTiledLoopOp (TiledLoopOp op)
This is a specialization of foldMemRefCast used for patterns of the form
tiled_loop(memrefcast(%src)) -> tiled_loop(%src)
It folds the source of the memref.cast into the root operation directly.
ParseResult parseCopyOpRegion (OpAsmParser &parser, Region &r, Type inputType, Type outputType)
void printCopyOpRegion (OpAsmPrinter &, Operation *, Region &, Type, Type)
CopyOp region is elided when printing.
static LogicalResult verify (CopyOp op)
ParseResult parseFillOpRegion (OpAsmParser &parser, Region &r, Type valueType, Type outputType)
void printFillOpRegion (OpAsmPrinter &, Operation *, Region &, Type, Type)
FillOp region is elided when printing.
static LogicalResult verify (FillOp op)
static void print (OpAsmPrinter &p, GenericOp op)
static ParseResult parseGenericOp (OpAsmParser &parser, OperationState &result)
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> &effects, ValueRange results, ValueRange inputBuffers, ValueRange outputs)
template<typename GenericOpType >
static LogicalResult verifyGenericOp (GenericOpType op)
static LogicalResult verify (GenericOp op)
static LogicalResult verify (InitTensorOp op)
void printInferType (OpAsmPrinter &printer, Operation *op, Value optOperand, Type typeToInfer, Type typeToInferFrom)
ParseResult parseInferType (OpAsmParser &parser, Optional< OpAsmParser::OperandType > optOperand, Type &typeToInfer, Type typeToInferFrom)
static LogicalResult verify (PadTensorOp op)
static void print (OpAsmPrinter &p, linalg::TensorExpandShapeOp op)
static void print (OpAsmPrinter &p, linalg::TensorCollapseShapeOp op)
template<typename AffineExprTy >
unsigned getMaxPosOfType (ArrayRef< ReassociationExprs > exprArrays)
static OpFoldResult getCollapsedOutputDimFromInputShape (OpBuilder &builder, Location loc, int64_t dimIndex, Value src, ArrayRef< AffineMap > reassociationMap)
For reshape op compute the shape at dimension dimIndex of the output in terms of shape of the src, when the reshape op is a collapsing operation.
static SmallVector< OpFoldResult, 4 > getCollapsedOutputShapeFromInputShape (OpBuilder &builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation)
Given the src of a collapsing reshape op and its reassociation maps, compute the shape of the result of the reshape.
static llvm::DenseMap< int64_t, int64_t > getExpandedDimToCollapsedDimMap (ArrayRef< AffineMap > reassociation)
Compute a map that for a given dimension of the expanded type gives the dimension in the collapsed type it maps to.
static OpFoldResult getExpandedOutputDimFromInputShape (OpBuilder &builder, Location loc, int64_t dimIndex, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation, llvm::DenseMap< int64_t, int64_t > &expandedDimToCollapsedDim)
For an expanding reshape op, compute the value for a dimension of the output from the shape of the input.
static SmallVector< OpFoldResult, 4 > getExpandedOutputShapeFromInputShape (OpBuilder &builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation)
Given the src of an expanding reshape op, the reassociation maps and the result type, compute the shape of the result of the reshape.
static SmallVector< OpFoldResult, 4 > getReshapeOutputShapeFromInputShape (OpBuilder &builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassocation)
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation)
Compute the RankedTensorType obtained by applying reassociation to type.
template<typename TensorReshapeOp , bool isExpansion = std::is_same<TensorReshapeOp, TensorExpandShapeOp>::value>
static LogicalResult verifyTensorReshapeOp (TensorReshapeOp op, RankedTensorType expandedType, RankedTensorType collapsedType)
static LogicalResult verify (TensorExpandShapeOp op)
static LogicalResult verify (TensorCollapseShapeOp op)
static void print (OpAsmPrinter &p, linalg::YieldOp op)
static ParseResult parseYieldOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOp)
static LogicalResult verify (linalg::YieldOp op)
static void print (OpAsmPrinter &p, TiledLoopOp op)
static ParseResult parseTiledLoopOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TiledLoopOp op)
static LogicalResult verify (IndexOp op)
template<typename LinalgPoolingOp >
static LogicalResult verifyStrideOrDilation (LinalgPoolingOp op, ArrayRef< Attribute > attrs, bool isStride)
static LogicalResult verify (ConvOp op)
template<typename PoolingOp >
static LogicalResult verifySingleInputPoolingOp (PoolingOp op)
static LogicalResult verify (PoolingMaxOp op)
static LogicalResult verify (PoolingMinOp op)
static LogicalResult verify (PoolingSumOp op)
static void appendMangledType (llvm::raw_string_ostream &ss, Type t)
template<typename NamedStructuredOpType >
void createAndFillStructuredOpRegion (OpBuilder &opBuilder, OperationState &result, TypeRange inputTypes, TypeRange outputTypes)
Generic entry point to create both the region and the block of a LinalgOp.
template<typename NamedStructuredOpType >
static LogicalResult verifyNamedStructuredOp (NamedStructuredOpType op)
Macro Definition Documentation
DEFINE_POOLING_OP_GET_EFFECTS
#define DEFINE_POOLING_OP_GET_EFFECTS (OP_NAME)
Value:
void OP_NAME::getEffects(\
      SmallVectorImpl<SideEffects::EffectInstance<MemoryEffects::Effect>>      \
          &effects) {                                                          \
    effects.emplace_back(MemoryEffects::Read::get(), input(),                  \
                         SideEffects::DefaultResource::get());                 \
    effects.emplace_back(MemoryEffects::Write::get(), output(),                \
                         SideEffects::DefaultResource::get());                 \
  }
Definition at line 2067 of file LinalgOps.cpp.
Referenced by verify().
GET_OP_CLASSES [1/2]
#define GET_OP_CLASSES
Definition at line 2097 of file LinalgOps.cpp.
GET_OP_CLASSES [2/2]
#define GET_OP_CLASSES
Definition at line 2097 of file LinalgOps.cpp.
INSTANTIATE_WEIGHTED_POOLING_INPUT_INDEX
#define INSTANTIATE_WEIGHTED_POOLING_INPUT_INDEX (OP_TYPE)
Value:
template SmallVector<AffineExpr, 4>                                          \
  mlir::linalg::weightedPoolingInputIndex<OP_TYPE>(                            \
      OP_TYPE op, ArrayRef<AffineExpr> outputDims,                             \
      ArrayRef<AffineExpr> windowDims);
Definition at line 2154 of file LinalgOps.cpp.
LINALGOP_FOLDERS
#define LINALGOP_FOLDERS (XXX)
Value:
LogicalResult XXX::fold(ArrayRef<Attribute>,                                 \
                          SmallVectorImpl<OpFoldResult> &) {                   \
    return foldMemRefCast(*this);                                              \
  }
Definition at line 2647 of file LinalgOps.cpp.
Function Documentation
appendMangledType()
static void appendMangledType (llvm::raw_string_ostream & ss, Type t) static
Definition at line 2173 of file LinalgOps.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isSignlessIntOrIndexOrFloat().
Referenced by mlir::linalg::generateLibraryCallName().
computeTensorReshapeCollapsedType()
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation) static
Compute the RankedTensorType obtained by applying reassociation to type.
Definition at line 1271 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::getReassociationAttrName(), mlir::getReassociationIndicesAttribute(), mlir::getSymbolLessAffineMaps(), mlir::Value::getType(), mlir::isReassociationValid(), mlir::ShapedType::kDynamicSize, and value.
Referenced by verifyTensorReshapeOp().
createAndFillStructuredOpRegion() [1/2]
template<typename NamedStructuredOpType > static void createAndFillStructuredOpRegion (OpBuilder & opBuilder, OperationState & result, TypeRange inputTypes, TypeRange outputTypes) static
Generic entry point to create both the region and the block of a LinalgOp.
Definition at line 2267 of file LinalgOps.cpp.
References mlir::OperationState::addRegion().
createAndFillStructuredOpRegion() [2/2]
template<typename NamedStructuredOpType > void createAndFillStructuredOpRegion (OpBuilder & opBuilder, OperationState & result, TypeRange inputTypes, TypeRange outputTypes)
Generic entry point to create both the region and the block of a LinalgOp.
Definition at line 2267 of file LinalgOps.cpp.
References mlir::OperationState::addRegion().
fillStructuredOpRegion()
template<typename NamedStructuredOpType > static void fillStructuredOpRegion (OpBuilder & opBuilder, Region & region, TypeRange inputTypes, TypeRange outputTypes, std::function< void(unsigned, unsigned)> errorHandler = nullptr) static
Forward declarations.
Generic entry point to create the block for the region of a LinalgOp.
Generic entry point to create the block for the region of a LinalgOp. This is used by both named structured ops created by ods-gen and by manually defined C++ ops. This is used by both builders and parsers. This function creates the block in the region with arguments corresponding to the elemental types of inputTypes and outputTypes. The latter are asserted to be of ShapedType.
This is used by both named structured ops created by ods-gen and by manually defined C++ ops. This is used by both builders and parsers. This function creates the block in the region with arguments corresponding to the elemental types of inputTypes and outputTypes, which are asserted to be ShapedType.
Definition at line 2233 of file LinalgOps.cpp.
References mlir::OpBuilder::createBlock(), mlir::getElementTypeOrSelf(), mlir::Block::getNumArguments(), mlir::Builder::getUnknownLoc(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPointToStart().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form
someop(memrefcast(%src)) -> someop(%src)
It folds the source of the memref.cast into the root operation directly.
Definition at line 111 of file LinalgOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::getOpOperands(), and mlir::success().
foldMemRefCastInTiledLoopOp()
static LogicalResult foldMemRefCastInTiledLoopOp (TiledLoopOp op) static
This is a specialization of foldMemRefCast used for patterns of the form
tiled_loop(memrefcast(%src)) -> tiled_loop(%src)
It folds the source of the memref.cast into the root operation directly.
Definition at line 128 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OpBuilder::atBlockBegin(), mlir::tensor::canFoldIntoConsumerOp(), mlir::ImplicitLocOpBuilder::create(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::emitWarning(), mlir::Block::eraseArgument(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArgument(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Block::getNumArguments(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::Builder::getUnknownLoc(), mlir::Block::insertArgument(), mlir::Type::isa(), mlir::Type::isIndex(), loc, mlir::parseAttribute(), mlir::OperationState::regions, mlir::Value::replaceAllUsesWith(), mlir::IROperand< DerivedT, IRValueT >::set(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::success(), and value.
Referenced by verify().
getAsValues()
static SmallVector<Value> getAsValues (OpBuilder & b, Location loc, ArrayRef< OpFoldResult > valueOrAttrVec) static
Helper function to convert a vector of OpFoldResults into a vector of Values.
Definition at line 95 of file LinalgOps.cpp.
References mlir::Location::cast(), mlir::OpBuilder::create(), and value.
Referenced by verify().
getCollapsedOutputDimFromInputShape()
static OpFoldResult getCollapsedOutputDimFromInputShape (OpBuilder & builder, Location loc, int64_t dimIndex, Value src, ArrayRef< AffineMap > reassociationMap) static
For reshape op compute the shape at dimension dimIndex of the output in terms of shape of the src, when the reshape op is a collapsing operation.
It is the product of the shape of the collapsed dimensions of the src.
Definition at line 1151 of file LinalgOps.cpp.
References mlir::linalg::applyMapToValues(), mlir::OpBuilder::createOrFold(), mlir::AffineMap::get(), mlir::Builder::getAffineSymbolExpr(), mlir::AffineMap::getResults(), and map().
Referenced by getCollapsedOutputShapeFromInputShape().
getCollapsedOutputShapeFromInputShape()
static SmallVector<OpFoldResult, 4> getCollapsedOutputShapeFromInputShape (OpBuilder & builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation) static
Given the src of a collapsing reshape op and its reassociation maps, compute the shape of the result of the reshape.
Definition at line 1172 of file LinalgOps.cpp.
References getCollapsedOutputDimFromInputShape().
Referenced by getReshapeOutputShapeFromInputShape().
getExpandedDimToCollapsedDimMap()
static llvm::DenseMap<int64_t, int64_t> getExpandedDimToCollapsedDimMap (ArrayRef< AffineMap > reassociation) static
Compute a map that for a given dimension of the expanded type gives the dimension in the collapsed type it maps to.
Essentially its the inverse of the reassocation maps.
Definition at line 1186 of file LinalgOps.cpp.
References mlir::detail::enumerate(), and map().
Referenced by getExpandedOutputShapeFromInputShape().
getExpandedOutputDimFromInputShape()
static OpFoldResult getExpandedOutputDimFromInputShape (OpBuilder & builder, Location loc, int64_t dimIndex, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation, llvm::DenseMap< int64_t, int64_t > & expandedDimToCollapsedDim) static
For an expanding reshape op, compute the value for a dimension of the output from the shape of the input.
Definition at line 1202 of file LinalgOps.cpp.
References mlir::linalg::applyMapToValues(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::AffineExpr::floorDiv(), mlir::AffineMap::get(), mlir::Builder::getAffineSymbolExpr(), mlir::Builder::getI64IntegerAttr(), mlir::ShapedType::isDynamic(), and loc.
Referenced by getExpandedOutputShapeFromInputShape().
getExpandedOutputShapeFromInputShape()
static SmallVector<OpFoldResult, 4> getExpandedOutputShapeFromInputShape (OpBuilder & builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation) static
Given the src of an expanding reshape op, the reassociation maps and the result type, compute the shape of the result of the reshape.
Definition at line 1240 of file LinalgOps.cpp.
References getExpandedDimToCollapsedDimMap(), and getExpandedOutputDimFromInputShape().
Referenced by getReshapeOutputShapeFromInputShape().
getGenericEffectsImpl()
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> & effects, ValueRange results, ValueRange inputBuffers, ValueRange outputs) static
Definition at line 613 of file LinalgOps.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< DefaultResource >::get().
getMaxPosOfType()
template<typename AffineExprTy > unsigned getMaxPosOfType (ArrayRef< ReassociationExprs > exprArrays)
Definition at line 1116 of file LinalgOps.cpp.
References mlir::convertReassociationIndicesToExprs(), mlir::AffineExpr::dyn_cast(), mlir::getSymbolLessAffineMaps(), and max().
getReshapeOutputShapeFromInputShape()
static SmallVector<OpFoldResult, 4> getReshapeOutputShapeFromInputShape (OpBuilder & builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassocation) static
Definition at line 1254 of file LinalgOps.cpp.
References mlir::Type::cast(), getCollapsedOutputShapeFromInputShape(), getExpandedOutputShapeFromInputShape(), and mlir::Value::getType().
Referenced by verify().
parseCommonStructuredOpParts()
static ParseResult parseCommonStructuredOpParts (OpAsmParser & parser, OperationState & result, SmallVectorImpl< Type > & inputTypes, SmallVectorImpl< Type > & outputTypes) static
Common parsing and printing used for both named structured ops created by ods-gen and by manually defined C++ ops.
Common parsing used for both named structured ops created by ods-gen and by manually defined C++ ops.
Does not handle regions.
Definition at line 2282 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI32VectorAttr(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
Referenced by parseGenericOp(), and parseNamedStructuredOp().
parseCopyOpRegion()
ParseResult parseCopyOpRegion (OpAsmParser & parser, Region & r, Type inputType, Type outputType)
Definition at line 376 of file LinalgOps.cpp.
References mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), and mlir::success().
parseFillOpRegion()
ParseResult parseFillOpRegion (OpAsmParser & parser, Region & r, Type valueType, Type outputType)
Definition at line 446 of file LinalgOps.cpp.
References mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), and mlir::success().
parseGenericOp()
static ParseResult parseGenericOp (OpAsmParser & parser, OperationState & result) static
Definition at line 572 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::NamedAttrList::assign(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::OpAsmParser::parseAttribute(), parseCommonStructuredOpParts(), mlir::OpAsmParser::parseEqual(), parseNamedStructuredOpResults(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::succeeded(), and mlir::success().
parseInferType()
ParseResult parseInferType (OpAsmParser & parser, Optional< OpAsmParser::OperandType > optOperand, Type & typeToInfer, Type typeToInferFrom)
Definition at line 850 of file LinalgOps.cpp.
References mlir::success().
parseNamedStructuredOp()
template<typename NamedStructuredOpType > static ParseResult parseNamedStructuredOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2364 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::failure(), parseCommonStructuredOpParts(), parseNamedStructuredOpResults(), and mlir::success().
parseNamedStructuredOpRegion()
template<typename NamedStructuredOpType > static ParseResult parseNamedStructuredOpRegion (OpAsmParser & parser, Region & region, TypeRange inputTypes, TypeRange outputTypes) static
Specific parsing and printing for named structured ops created by ods-gen.
Definition at line 2335 of file LinalgOps.cpp.
References mlir::OpAsmParser::emitError(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), and mlir::success().
parseNamedStructuredOpResults()
static ParseResult parseNamedStructuredOpResults (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes) static
Definition at line 2356 of file LinalgOps.cpp.
References mlir::failure(), mlir::OpAsmParser::parseOptionalArrowTypeList(), and mlir::success().
Referenced by parseGenericOp(), and parseNamedStructuredOp().
parseTiledLoopOp()
static ParseResult parseTiledLoopOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1635 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::getDistributionTypesAttrName(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::getIteratorTypesAttrName(), mlir::getParallelIteratorTypeName(), mlir::Value::getParentRegion(), mlir::Builder::getStringAttr(), mlir::Region::isAncestor(), mlir::Operation::moveBefore(), op, mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseAssignmentListWithTypes(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
parseYieldOp()
static ParseResult parseYieldOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1449 of file LinalgOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OpAsmParser::resolveOperands().
print() [1/5]
static void print (OpAsmPrinter & p, GenericOp op) static
Definition at line 531 of file LinalgOps.cpp.
References printCommonStructuredOpParts(), printNamedStructuredOpResults(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [2/5]
static void print (OpAsmPrinter & p, linalg::TensorExpandShapeOp op) static
Definition at line 1107 of file LinalgOps.cpp.
References op.
print() [3/5]
static void print (OpAsmPrinter & p, linalg::TensorCollapseShapeOp op) static
Definition at line 1111 of file LinalgOps.cpp.
References op.
print() [4/5]
static void print (OpAsmPrinter & p, linalg::YieldOp op) static
Definition at line 1440 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/5]
static void print (OpAsmPrinter & p, TiledLoopOp op) static
Definition at line 1595 of file LinalgOps.cpp.
References mlir::getDistributionTypesAttrName(), mlir::getIteratorTypesAttrName(), mlir::getParallelIteratorTypeName(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
printCommonStructuredOpParts()
template<typename NamedStructuredOpType > static void printCommonStructuredOpParts (OpAsmPrinter & p, NamedStructuredOpType op) static
Definition at line 2321 of file LinalgOps.cpp.
Referenced by print(), and printNamedStructuredOp().
printCopyOpRegion()
void printCopyOpRegion (OpAsmPrinter & , Operation * , Region & , Type , Type)
CopyOp region is elided when printing.
Definition at line 385 of file LinalgOps.cpp.
printFillOpRegion()
void printFillOpRegion (OpAsmPrinter & , Operation * , Region & , Type , Type)
FillOp region is elided when printing.
Definition at line 455 of file LinalgOps.cpp.
printInferType()
void printInferType (OpAsmPrinter & printer, Operation * op, Value optOperand, Type typeToInfer, Type typeToInferFrom)
Definition at line 847 of file LinalgOps.cpp.
printNamedStructuredOp()
template<typename NamedStructuredOpType > static void printNamedStructuredOp (OpAsmPrinter & p, NamedStructuredOpType op) static
Definition at line 2395 of file LinalgOps.cpp.
References printCommonStructuredOpParts(), printNamedStructuredOpResults(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printNamedStructuredOpResults()
static void printNamedStructuredOpResults (OpAsmPrinter & p, TypeRange resultTypes) static
Definition at line 2387 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalArrowTypeList().
Referenced by print(), and printNamedStructuredOp().
verify() [1/14]
static LogicalResult verify (CopyOp op) static
Definition at line 387 of file LinalgOps.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::Type::dyn_cast(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Block::getArgument(), mlir::getElementTypeOrSelf(), mlir::Block::getNumArguments(), mlir::Value::getType(), mlir::OperationState::regions, mlir::success(), and value.
verify() [2/14]
static LogicalResult verify (FillOp op) static
Definition at line 457 of file LinalgOps.cpp.
References mlir::OpBuilder::createBlock(), mlir::Region::end(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArguments(), mlir::getElementTypeOrSelf(), mlir::Builder::getStrArrayAttr(), mlir::Builder::getStringAttr(), mlir::OperationState::location, mlir::OperationState::regions, and mlir::success().
verify() [3/14]
static LogicalResult verify (GenericOp op) static
Definition at line 647 of file LinalgOps.cpp.
References mlir::OperationState::addAttributes(), mlir::dispatchIndexOpFoldResult(), elementType(), mlir::Builder::getI64ArrayAttr(), mlir::ShapedType::kDynamicSize, and verifyGenericOp().
verify() [4/14]
static LogicalResult verify (InitTensorOp op) static
Definition at line 667 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::getAsOpFoldResult(), mlir::Value::getDefiningOp(), mlir::Builder::getI64ArrayAttr(), getShape(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), mlir::ShapedType::kDynamicSize, loc, op, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::success(), and mlir::verifyListOfOperandsOrIntegers().
verify() [5/14]
static LogicalResult verify (PadTensorOp op) static
Definition at line 858 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::linalg::applyMapToValues(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::OpBuilder::createOrFold(), mlir::dispatchIndexOpFoldResult(), mlir::Value::dyn_cast(), mlir::Region::end(), mlir::detail::enumerate(), mlir::extractFromI64ArrayAttr(), mlir::failure(), mlir::Region::front(), mlir::Block::front(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineSymbolExpr(), mlir::Block::getArgumentTypes(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::Block::getNumArguments(), mlir::Value::getParentBlock(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::kDynamicSize, loc, mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, and mlir::success().
verify() [6/14]
static LogicalResult verify (TensorExpandShapeOp op) static
Definition at line 1342 of file LinalgOps.cpp.
References verifyTensorReshapeOp().
verify() [7/14]
static LogicalResult verify (TensorCollapseShapeOp op) static
Definition at line 1346 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::failure(), getAsValues(), mlir::DenseElementsAttr::getFromRawBuffer(), mlir::DenseElementsAttr::getRawData(), getReshapeOutputShapeFromInputShape(), getShape(), mlir::DenseElementsAttr::isSplat(), loc, mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::success(), and verifyTensorReshapeOp().
verify() [8/14]
static LogicalResult verify (linalg::YieldOp op) static
Definition at line 1482 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OpBuilder::createBlock(), mlir::detail::enumerate(), mlir::Block::getArguments(), mlir::getDistributionTypesAttrName(), getElementType(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::getIteratorTypesAttrName(), mlir::Value::getType(), mlir::Type::isa(), mlir::OperationState::location, mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and verifyYield().
verify() [9/14]
static LogicalResult verify (TiledLoopOp op) static
Definition at line 1773 of file LinalgOps.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), foldMemRefCastInTiledLoopOp(), mlir::OpBuilder::getListener(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::RewritePatternSet::insert(), mlir::Type::isa(), loc, mlir::BlockAndValueMapping::map(), op, mlir::RewriterBase::replaceOp(), rewriter, mlir::success(), and mlir::Value::use_empty().
verify() [10/14]
static LogicalResult verify (IndexOp op) static
Definition at line 1983 of file LinalgOps.cpp.
References mlir::success().
verify() [11/14]
static LogicalResult verify (ConvOp op) static
Definition at line 2020 of file LinalgOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyStrideOrDilation().
verify() [12/14]
static LogicalResult verify (PoolingMaxOp op) static
Definition at line 2077 of file LinalgOps.cpp.
References verifySingleInputPoolingOp().
verify() [13/14]
static LogicalResult verify (PoolingMinOp op) static
Definition at line 2080 of file LinalgOps.cpp.
References verifySingleInputPoolingOp().
verify() [14/14]
static LogicalResult verify (PoolingSumOp op) static
Definition at line 2083 of file LinalgOps.cpp.
References DEFINE_POOLING_OP_GET_EFFECTS, and verifySingleInputPoolingOp().
verifyGenericOp()
template<typename GenericOpType > static LogicalResult verifyGenericOp (GenericOpType op) static
Definition at line 643 of file LinalgOps.cpp.
References mlir::success().
Referenced by verify().
verifyNamedStructuredOp()
template<typename NamedStructuredOpType > static LogicalResult verifyNamedStructuredOp (NamedStructuredOpType op) static
Definition at line 2414 of file LinalgOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::clone(), mlir::OpBuilder::create(), mlir::Block::eraseArgument(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Region::front(), mlir::Block::front(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Operation::getNumResults(), mlir::Operation::getRegion(), mlir::Operation::getResults(), mlir::Block::getTerminator(), mlir::Value::getType(), map(), op, mlir::Value::replaceAllUsesWith(), mlir::RewriterBase::replaceOp(), rewriter, mlir::Operation::setAttr(), and mlir::success().
verifySingleInputPoolingOp()
template<typename PoolingOp > static LogicalResult verifySingleInputPoolingOp (PoolingOp op) static
Definition at line 2043 of file LinalgOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyStrideOrDilation().
Referenced by verify().
verifyStrideOrDilation()
template<typename LinalgPoolingOp > static LogicalResult verifyStrideOrDilation (LinalgPoolingOp op, ArrayRef< Attribute > attrs, bool isStride) static
Definition at line 1997 of file LinalgOps.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), and mlir::success().
Referenced by verify(), and verifySingleInputPoolingOp().
verifyTensorReshapeOp()
template<typename TensorReshapeOp , bool isExpansion = std::is_same<TensorReshapeOp, TensorExpandShapeOp>::value> static LogicalResult verifyTensorReshapeOp (TensorReshapeOp op, RankedTensorType expandedType, RankedTensorType collapsedType) static
Definition at line 1326 of file LinalgOps.cpp.
References computeTensorReshapeCollapsedType(), mlir::failed(), mlir::failure(), maps, mlir::success(), and mlir::verifyReshapeLikeTypes().
Referenced by verify().
verifyYield()
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOp) static
Definition at line 1461 of file LinalgOps.cpp.
References elementType(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), and mlir::success().
Referenced by verify().