MLIR: include/mlir-c/Dialect/Linalg.h File Reference
Linalg.h File Reference
#include "mlir-c/Registration.h"
#include "mlir-c/Support.h"
#include "mlir/Dialect/Linalg/Passes.capi.h.inc"
Functions
MLIR_CAPI_EXPORTED void mlirLinalgFillBuiltinNamedOpRegion (MlirDialect linalgDialect, MlirOperation op)
Apply the special region builder for the builtin named Linalg op.
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Linalg, linalg)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Linalg , linalg)
mlirLinalgFillBuiltinNamedOpRegion()
MLIR_CAPI_EXPORTED void mlirLinalgFillBuiltinNamedOpRegion (MlirDialect linalgDialect, MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
Assert that op is a builtin named Linalg op.
Definition at line 18 of file Linalg.cpp.
References mlir::Region::getBlocks(), mlir::Operation::getContext(), mlir::getElementTypeOrSelf(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::OperationName::getStringRef(), MLIR_DEFINE_CAPI_DIALECT_REGISTRATION(), op, and unwrap().