MLIR: lib/Conversion/LinalgToStandard/LinalgToStandard.cpp File Reference
LinalgToStandard.cpp File Reference
#include "mlir/Conversion/LinalgToStandard/LinalgToStandard.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Conversion/Passes.h.inc"
Classes
class mlir::impl::ConvertLinalgToStandardPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_CONVERTLINALGTOSTANDARDPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertLinalgToStandardPass ()
std::unique_ptr<::mlir::Pass > mlir::createConvertLinalgToStandardPass ()
static MemRefType makeStridedLayoutDynamic (MemRefType type)
static SmallVector< Type, 4 > extractOperandTypes (Operation *op)
Helper function to extract the operand types that are passed to the generated CallOp.
static FailureOr< FlatSymbolRefAttr > getLibraryCallSymbolRef (Operation *op, PatternRewriter &rewriter)
static SmallVector< Value, 4 > createTypeCanonicalizedMemRefOperands (OpBuilder &b, Location loc, ValueRange operands)
Macro Definition Documentation
GEN_PASS_DEF_CONVERTLINALGTOSTANDARDPASS
#define GEN_PASS_DEF_CONVERTLINALGTOSTANDARDPASS
Definition at line 20 of file LinalgToStandard.cpp.
Function Documentation
createTypeCanonicalizedMemRefOperands()
SmallVector< Value, 4 > createTypeCanonicalizedMemRefOperands (OpBuilder & b, Location loc, ValueRange operands) static
Definition at line 93 of file LinalgToStandard.cpp.
References b, and makeStridedLayoutDynamic().
Referenced by mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite().
extractOperandTypes()
SmallVector< Type, 4 > extractOperandTypes (Operation * op) static
Helper function to extract the operand types that are passed to the generated CallOp.
MemRefTypes have their layout canonicalized since the information is not used in signature generation. Note that static size information is not modified.
Definition at line 37 of file LinalgToStandard.cpp.
References mlir::Operation::getNumOperands(), mlir::Operation::getOperandTypes(), makeStridedLayoutDynamic(), and result.
Referenced by getLibraryCallSymbolRef().
getLibraryCallSymbolRef()
FailureOr< FlatSymbolRefAttr > getLibraryCallSymbolRef (Operation * op, PatternRewriter & rewriter) static
Definition at line 55 of file LinalgToStandard.cpp.
References extractOperandTypes(), mlir::FlatSymbolRefAttr::getAttr(), mlir::Builder::getContext(), mlir::Operation::getContext(), mlir::Builder::getFunctionType(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::FlatSymbolRefAttr::getValue(), mlir::RewriterBase::notifyMatchFailure(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite().
makeStridedLayoutDynamic()
MemRefType makeStridedLayoutDynamic (MemRefType type) static
Definition at line 27 of file LinalgToStandard.cpp.
References mlir::MemRefType::Builder::setLayout().
Referenced by createTypeCanonicalizedMemRefOperands(), and extractOperandTypes().