MLIR: include/mlir-c/Target/LLVMIR.h File Reference
LLVMIR.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "llvm-c/Core.h"
#include "llvm-c/Support.h"
Classes
struct MlirTypeFromLLVMIRTranslator
struct MlirTypeToLLVMIRTranslator
Typedefs
typedef struct MlirTypeFromLLVMIRTranslator MlirTypeFromLLVMIRTranslator
typedef struct MlirTypeToLLVMIRTranslator MlirTypeToLLVMIRTranslator
Functions
MLIR_CAPI_EXPORTED LLVMModuleRef mlirTranslateModuleToLLVMIR (MlirOperation module, LLVMContextRef context)
Translate operation that satisfies LLVM dialect module requirements into an LLVM IR module living in the given context.
MLIR_CAPI_EXPORTED char * mlirTranslateModuleToLLVMIRToString (MlirOperation module)
MLIR_CAPI_EXPORTED MlirTypeFromLLVMIRTranslator mlirTypeFromLLVMIRTranslatorCreate (MlirContext ctx)
Create an LLVM::TypeFromLLVMIRTranslator and transfer ownership to the caller.
MLIR_CAPI_EXPORTED void mlirTypeFromLLVMIRTranslatorDestroy (MlirTypeFromLLVMIRTranslator translator)
Takes an LLVM::TypeFromLLVMIRTranslator owned by the caller and destroys it.
MLIR_CAPI_EXPORTED MlirType mlirTypeFromLLVMIRTranslatorTranslateType (MlirTypeFromLLVMIRTranslator translator, LLVMTypeRef llvmType)
Translates the given LLVM IR type to the MLIR LLVM dialect.
MLIR_CAPI_EXPORTED MlirTypeToLLVMIRTranslator mlirTypeToLLVMIRTranslatorCreate (LLVMContextRef ctx)
Create an LLVM::TypeToLLVMIRTranslator and transfer ownership to the caller.
MLIR_CAPI_EXPORTED void mlirTypeToLLVMIRTranslatorDestroy (MlirTypeToLLVMIRTranslator translator)
Takes an LLVM::TypeToLLVMIRTranslator owned by the caller and destroys it.
MLIR_CAPI_EXPORTED LLVMTypeRef mlirTypeToLLVMIRTranslatorTranslateType (MlirTypeToLLVMIRTranslator translator, MlirType mlirType)
Translates the given MLIR LLVM dialect to the LLVM IR type.
Typedef Documentation
MlirTypeFromLLVMIRTranslator
typedef struct MlirTypeFromLLVMIRTranslator MlirTypeFromLLVMIRTranslator
Definition at line 43 of file LLVMIR.h.
MlirTypeToLLVMIRTranslator
typedef struct MlirTypeToLLVMIRTranslator MlirTypeToLLVMIRTranslator
Definition at line 64 of file LLVMIR.h.
Function Documentation
mlirTranslateModuleToLLVMIR()
MLIR_CAPI_EXPORTED LLVMModuleRef mlirTranslateModuleToLLVMIR (MlirOperation module, LLVMContextRef context)
Translate operation that satisfies LLVM dialect module requirements into an LLVM IR module living in the given context.
This translates operations from any dilalect that has a registered implementation of LLVMTranslationDialectInterface.
Returns
the generated LLVM IR Module from the translated MLIR module, it is owned by the caller.
Definition at line 23 of file LLVMIR.cpp.
References mlir::translateModuleToLLVMIR(), and unwrap().
Referenced by mlirTranslateModuleToLLVMIRToString().
mlirTranslateModuleToLLVMIRToString()
MLIR_CAPI_EXPORTED char * mlirTranslateModuleToLLVMIRToString (MlirOperation module)
Definition at line 37 of file LLVMIR.cpp.
References mlirTranslateModuleToLLVMIR().
Referenced by populateDialectLLVMSubmodule().
mlirTypeFromLLVMIRTranslatorCreate()
MLIR_CAPI_EXPORTED MlirTypeFromLLVMIRTranslator mlirTypeFromLLVMIRTranslatorCreate (MlirContext ctx)
Create an LLVM::TypeFromLLVMIRTranslator and transfer ownership to the caller.
References MLIR_CAPI_EXPORTED.
mlirTypeFromLLVMIRTranslatorDestroy()
MLIR_CAPI_EXPORTED void mlirTypeFromLLVMIRTranslatorDestroy (MlirTypeFromLLVMIRTranslator translator)
Takes an LLVM::TypeFromLLVMIRTranslator owned by the caller and destroys it.
It is the responsibility of the user to only pass an LLVM::TypeFromLLVMIRTranslator class.
Definition at line 56 of file LLVMIR.cpp.
References unwrap().
mlirTypeFromLLVMIRTranslatorTranslateType()
MLIR_CAPI_EXPORTED MlirType mlirTypeFromLLVMIRTranslatorTranslateType (MlirTypeFromLLVMIRTranslator translator, LLVMTypeRef llvmType)
Translates the given LLVM IR type to the MLIR LLVM dialect.
Definition at line 61 of file LLVMIR.cpp.
References mlir::LLVM::TypeFromLLVMIRTranslator::translateType(), unwrap(), and wrap().
mlirTypeToLLVMIRTranslatorCreate()
MLIR_CAPI_EXPORTED MlirTypeToLLVMIRTranslator mlirTypeToLLVMIRTranslatorCreate (LLVMContextRef ctx)
Create an LLVM::TypeToLLVMIRTranslator and transfer ownership to the caller.
References MLIR_CAPI_EXPORTED.
mlirTypeToLLVMIRTranslatorDestroy()
MLIR_CAPI_EXPORTED void mlirTypeToLLVMIRTranslatorDestroy (MlirTypeToLLVMIRTranslator translator)
Takes an LLVM::TypeToLLVMIRTranslator owned by the caller and destroys it.
It is the responsibility of the user to only pass an LLVM::TypeToLLVMIRTranslator class.
Definition at line 78 of file LLVMIR.cpp.
References unwrap().
mlirTypeToLLVMIRTranslatorTranslateType()
MLIR_CAPI_EXPORTED LLVMTypeRef mlirTypeToLLVMIRTranslatorTranslateType (MlirTypeToLLVMIRTranslator translator, MlirType mlirType)
Translates the given MLIR LLVM dialect to the LLVM IR type.
Definition at line 83 of file LLVMIR.cpp.
References mlir::LLVM::TypeToLLVMIRTranslator::translateType(), and unwrap().