MLIR: lib/Dialect/LLVMIR/IR/LLVMInterfaces.cpp File Reference
LLVMInterfaces.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMInterfaces.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMInterfaces.cpp.inc"
Functions
template<class AttrT>
static LogicalResult isArrayOf (Operation *op, ArrayAttr array)
Verifies that all elements of array are instances of Attr.
Function Documentation
isArrayOf()
template<class AttrT> LogicalResult isArrayOf (Operation * op, ArrayAttr array) static
Verifies that all elements of array are instances of Attr.
Definition at line 22 of file LLVMInterfaces.cpp.
References ArrayAttr(), mlir::Operation::emitOpError(), and success().
Referenced by mlir::LLVM::detail::verifyAccessGroupOpInterface(), and mlir::LLVM::detail::verifyAliasAnalysisOpInterface().