MLIR: lib/CAPI/Dialect/LLVM.cpp File Reference
LLVM.cpp File Reference
#include "mlir-c/Dialect/LLVM.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Wrap.h"
#include "mlir/Dialect/LLVMIR/LLVMAttrs.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "llvm-c/Core.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/SmallVectorExtras.h"
Functions
MlirType mlirLLVMPointerTypeGet (MlirContext ctx, unsigned addressSpace)
Creates an llvm.ptr type.
MlirStringRef mlirLLVMPointerTypeGetName (void)
MlirTypeID mlirLLVMPointerTypeGetTypeID ()
bool mlirTypeIsALLVMPointerType (MlirType type)
Returns true if the type is an LLVM dialect pointer type.
unsigned mlirLLVMPointerTypeGetAddressSpace (MlirType pointerType)
Returns address space of llvm.ptr.
MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
MlirStringRef mlirLLVMVoidTypeGetName (void)
bool mlirTypeIsALLVMArrayType (MlirType type)
Returns true if the type is an LLVM dialect array type.
MlirTypeID mlirLLVMArrayTypeGetTypeID ()
MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
MlirStringRef mlirLLVMArrayTypeGetName (void)
MlirType mlirLLVMArrayTypeGetElementType (MlirType type)
Returns the element type of the llvm.array type.
unsigned mlirLLVMArrayTypeGetNumElements (MlirType type)
Returns the number of elements in the llvm.array type.
MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const *argumentTypes, bool isVarArg)
Creates an llvm.func type.
MlirStringRef mlirLLVMFunctionTypeGetName (void)
bool mlirTypeIsALLVMFunctionType (MlirType type)
Returns true if the type is an LLVM dialect function type.
MlirTypeID mlirLLVMFunctionTypeGetTypeID (void)
Returns the TypeID of an LLVM function type.
intptr_t mlirLLVMFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
MlirType mlirLLVMFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
MlirType mlirLLVMFunctionTypeGetReturnType (MlirType type)
Returns the return type of the function type.
bool mlirLLVMFunctionTypeIsVarArg (MlirType type)
Returns true if the function type is variadic.
bool mlirTypeIsALLVMStructType (MlirType type)
Returns true if the type is an LLVM dialect struct type.
MlirTypeID mlirLLVMStructTypeGetTypeID ()
MlirStringRef mlirLLVMStructTypeGetName (void)
bool mlirLLVMStructTypeIsLiteral (MlirType type)
Returns true if the type is a literal (unnamed) LLVM struct type.
intptr_t mlirLLVMStructTypeGetNumElementTypes (MlirType type)
Returns the number of fields in the struct.
MlirType mlirLLVMStructTypeGetElementType (MlirType type, intptr_t position)
Returns the positions-th field of the struct.
bool mlirLLVMStructTypeIsPacked (MlirType type)
Returns true if the struct is packed.
MlirStringRef mlirLLVMStructTypeGetIdentifier (MlirType type)
Returns the identifier of the identified struct.
bool mlirLLVMStructTypeIsOpaque (MlirType type)
Returns true is the struct is explicitly opaque (will not have a body) or uninitialized (will eventually have a body).
MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
MlirType mlirLLVMStructTypeLiteralGetChecked (MlirLocation loc, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type if possible.
MlirType mlirLLVMStructTypeOpaqueGet (MlirContext ctx, MlirStringRef name)
MlirType mlirLLVMStructTypeIdentifiedGet (MlirContext ctx, MlirStringRef name)
Creates an LLVM identified struct type with no body.
MlirType mlirLLVMStructTypeIdentifiedNewGet (MlirContext ctx, MlirStringRef name, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM identified struct type with no body and a name starting with the given prefix.
MlirLogicalResult mlirLLVMStructTypeSetBody (MlirType structType, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Sets the body of the identified struct if it hasn't been set yet.
MlirAttribute mlirLLVMDIExpressionElemAttrGet (MlirContext ctx, unsigned int opcode, intptr_t nArguments, uint64_t const *arguments)
Creates a LLVM DIExpressionElem attribute.
MlirStringRef mlirLLVMDIExpressionElemAttrGetName (void)
MlirAttribute mlirLLVMDIExpressionAttrGet (MlirContext ctx, intptr_t nOperations, MlirAttribute const *operations)
Creates a LLVM DIExpression attribute.
MlirStringRef mlirLLVMDIExpressionAttrGetName (void)
MlirAttribute mlirLLVMDINullTypeAttrGet (MlirContext ctx)
Creates a LLVM DINullType attribute.
MlirStringRef mlirLLVMDINullTypeAttrGetName (void)
MlirAttribute mlirLLVMDIBasicTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, MlirLLVMTypeEncoding encoding)
Creates a LLVM DIBasicType attribute.
MlirStringRef mlirLLVMDIBasicTypeAttrGetName (void)
MlirAttribute mlirLLVMDICompositeTypeAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompositeType attribute.
MlirAttribute mlirLLVMDICompositeTypeAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, int64_t flags, uint64_t sizeInBits, uint64_t alignInBits, intptr_t nElements, MlirAttribute const *elements, MlirAttribute dataLocation, MlirAttribute rank, MlirAttribute allocated, MlirAttribute associated, MlirAttribute identifier, MlirAttribute discriminator)
Creates a LLVM DICompositeType attribute.
MlirStringRef mlirLLVMDICompositeTypeAttrGetName (void)
MlirAttribute mlirLLVMDIDerivedTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, uint64_t sizeInBits, uint32_t alignInBits, uint64_t offsetInBits, int64_t dwarfAddressSpace, int64_t flags, MlirAttribute extraData)
Creates a LLVM DIDerivedType attribute.
MlirStringRef mlirLLVMDIDerivedTypeAttrGetName (void)
MlirAttribute mlirLLVMDIStringTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, uint32_t alignInBits, MlirAttribute stringLength, MlirAttribute stringLengthExp, MlirAttribute stringLocationExp, MlirLLVMTypeEncoding encoding)
MlirStringRef mlirLLVMDIStringTypeAttrGetName (void)
MlirAttribute mlirLLVMDIDerivedTypeAttrGetBaseType (MlirAttribute diDerivedType)
Gets the base type from a LLVM DIDerivedType attribute.
MlirAttribute mlirLLVMCConvAttrGet (MlirContext ctx, MlirLLVMCConv cconv)
Creates a LLVM CConv attribute.
MlirStringRef mlirLLVMCConvAttrGetName (void)
MlirAttribute mlirLLVMComdatAttrGet (MlirContext ctx, MlirLLVMComdat comdat)
Creates a LLVM Comdat attribute.
MlirStringRef mlirLLVMComdatAttrGetName (void)
MlirAttribute mlirLLVMLinkageAttrGet (MlirContext ctx, MlirLLVMLinkage linkage)
Creates a LLVM Linkage attribute.
MlirStringRef mlirLLVMLinkageAttrGetName (void)
MlirAttribute mlirLLVMDIFileAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute directory)
Creates a LLVM DIFileAttr attribute.
MlirStringRef mlirLLVMDIFileAttrGetName (void)
MlirAttribute mlirLLVMDICompileUnitAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompileUnitAttr attribute.
MlirAttribute mlirLLVMDICompileUnitAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, unsigned int sourceLanguage, MlirAttribute file, MlirAttribute producer, bool isOptimized, MlirLLVMDIEmissionKind emissionKind, bool isDebugInfoForProfiling, MlirLLVMDINameTableKind nameTableKind, MlirAttribute splitDebugFilename, intptr_t nImportedEntities, MlirAttribute const *importedEntities)
Creates a LLVM DICompileUnit attribute.
MlirStringRef mlirLLVMDICompileUnitAttrGetName (void)
MlirAttribute mlirLLVMDIFlagsAttrGet (MlirContext ctx, uint64_t value)
Creates a LLVM DIFlags attribute.
MlirStringRef mlirLLVMDIFlagsAttrGetName (void)
MlirAttribute mlirLLVMDILexicalBlockAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int line, unsigned int column)
Creates a LLVM DILexicalBlock attribute.
MlirStringRef mlirLLVMDILexicalBlockAttrGetName (void)
MlirAttribute mlirLLVMDILexicalBlockFileAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int discriminator)
Creates a LLVM DILexicalBlockFile attribute.
MlirStringRef mlirLLVMDILexicalBlockFileAttrGetName (void)
MlirAttribute mlirLLVMDILocalVariableAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute name, MlirAttribute diFile, unsigned int line, unsigned int arg, unsigned int alignInBits, MlirAttribute diType, int64_t flags)
Creates a LLVM DILocalVariableAttr attribute.
MlirStringRef mlirLLVMDILocalVariableAttrGetName (void)
MlirAttribute mlirLLVMDISubroutineTypeAttrGet (MlirContext ctx, unsigned int callingConvention, intptr_t nTypes, MlirAttribute const *types)
Creates a LLVM DISubroutineTypeAttr attribute.
MlirStringRef mlirLLVMDISubroutineTypeAttrGetName (void)
MlirAttribute mlirLLVMDISubprogramAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DISubprogramAttr attribute.
MlirAttribute mlirLLVMDISubprogramAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, MlirAttribute compileUnit, MlirAttribute scope, MlirAttribute name, MlirAttribute linkageName, MlirAttribute file, unsigned int line, unsigned int scopeLine, uint64_t subprogramFlags, MlirAttribute type, intptr_t nRetainedNodes, MlirAttribute const *retainedNodes, intptr_t nAnnotations, MlirAttribute const *annotations)
Creates a LLVM DISubprogramAttr attribute.
MlirStringRef mlirLLVMDISubprogramAttrGetName (void)
MlirAttribute mlirLLVMDISubprogramAttrGetScope (MlirAttribute diSubprogram)
Gets the scope from this DISubprogramAttr.
unsigned int mlirLLVMDISubprogramAttrGetLine (MlirAttribute diSubprogram)
Gets the line from this DISubprogramAttr.
unsigned int mlirLLVMDISubprogramAttrGetScopeLine (MlirAttribute diSubprogram)
Gets the scope line from this DISubprogram.
MlirAttribute mlirLLVMDISubprogramAttrGetCompileUnit (MlirAttribute diSubprogram)
Gets the compile unit from this DISubprogram.
MlirAttribute mlirLLVMDISubprogramAttrGetFile (MlirAttribute diSubprogram)
Gets the file from this DISubprogramAttr.
MlirAttribute mlirLLVMDISubprogramAttrGetType (MlirAttribute diSubprogram)
Gets the type from this DISubprogramAttr.
MlirAttribute mlirLLVMDIModuleAttrGet (MlirContext ctx, MlirAttribute file, MlirAttribute scope, MlirAttribute name, MlirAttribute configMacros, MlirAttribute includePath, MlirAttribute apinotes, unsigned int line, bool isDecl)
Creates a LLVM DIModuleAttr attribute.
MlirStringRef mlirLLVMDIModuleAttrGetName (void)
MlirAttribute mlirLLVMDIModuleAttrGetScope (MlirAttribute diModule)
Gets the scope of this DIModuleAttr.
MlirAttribute mlirLLVMDIImportedEntityAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute scope, MlirAttribute entity, MlirAttribute file, unsigned int line, MlirAttribute name, intptr_t nElements, MlirAttribute const *elements)
Creates a LLVM DIImportedEntityAttr attribute.
MlirStringRef mlirLLVMDIImportedEntityAttrGetName (void)
MlirAttribute mlirLLVMDIAnnotationAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute value)
Creates a LLVM DIAnnotation attribute.
MlirStringRef mlirLLVMDIAnnotationAttrGetName (void)
MlirAttribute mlirLLVMMDStringAttrGet (MlirContext ctx, MlirStringRef value)
Creates an LLVM MDStringAttr.
bool mlirLLVMAttrIsAMDStringAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDStringAttr.
MlirTypeID mlirLLVMMDStringAttrGetTypeID (void)
Returns the TypeID of MDStringAttr.
MlirStringRef mlirLLVMMDStringAttrGetValue (MlirAttribute attr)
Returns the string value of an LLVM MDStringAttr.
MlirAttribute mlirLLVMMDConstantAttrGet (MlirContext ctx, MlirAttribute valueAttr)
Creates an LLVM MDConstantAttr wrapping an attribute.
bool mlirLLVMAttrIsAMDConstantAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDConstantAttr.
MlirTypeID mlirLLVMMDConstantAttrGetTypeID (void)
Returns the TypeID of MDConstantAttr.
MlirAttribute mlirLLVMMDConstantAttrGetValue (MlirAttribute attr)
Returns the attribute value of an LLVM MDConstantAttr.
MlirAttribute mlirLLVMMDFuncAttrGet (MlirContext ctx, MlirAttribute name)
Creates an LLVM MDFuncAttr referencing a function symbol.
bool mlirLLVMAttrIsAMDFuncAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDFuncAttr.
MlirTypeID mlirLLVMMDFuncAttrGetTypeID (void)
Returns the TypeID of MDFuncAttr.
MlirAttribute mlirLLVMMDFuncAttrGetName (MlirAttribute attr)
Returns the symbol name of an LLVM MDFuncAttr.
MlirAttribute mlirLLVMMDNodeAttrGet (MlirContext ctx, intptr_t nOperands, MlirAttribute const *operands)
Creates an LLVM MDNodeAttr.
bool mlirLLVMAttrIsAMDNodeAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDNodeAttr.
MlirTypeID mlirLLVMMDNodeAttrGetTypeID (void)
Returns the TypeID of MDNodeAttr.
intptr_t mlirLLVMMDNodeAttrGetNumOperands (MlirAttribute attr)
Returns the number of operands in an LLVM MDNodeAttr.
MlirAttribute mlirLLVMMDNodeAttrGetOperand (MlirAttribute attr, intptr_t index)
Returns the operand at the given index of an LLVM MDNodeAttr.
Function Documentation
mlirLLVMArrayTypeGet()
MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
Definition at line 60 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived().
mlirLLVMArrayTypeGetElementType()
MlirType mlirLLVMArrayTypeGetElementType (MlirType type)
Returns the element type of the llvm.array type.
Definition at line 68 of file LLVM.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived().
mlirLLVMArrayTypeGetName()
MlirStringRef mlirLLVMArrayTypeGetName (void)
Definition at line 64 of file LLVM.cpp.
References wrap().
mlirLLVMArrayTypeGetNumElements()
unsigned mlirLLVMArrayTypeGetNumElements (MlirType type)
Returns the number of elements in the llvm.array type.
Definition at line 72 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived().
mlirLLVMArrayTypeGetTypeID()
MlirTypeID mlirLLVMArrayTypeGetTypeID (void)
Definition at line 56 of file LLVM.cpp.
References wrap().
mlirLLVMAttrIsAMDConstantAttr()
bool mlirLLVMAttrIsAMDConstantAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDConstantAttr.
Definition at line 581 of file LLVM.cpp.
References unwrap().
mlirLLVMAttrIsAMDFuncAttr()
bool mlirLLVMAttrIsAMDFuncAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDFuncAttr.
Definition at line 598 of file LLVM.cpp.
References unwrap().
mlirLLVMAttrIsAMDNodeAttr()
bool mlirLLVMAttrIsAMDNodeAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDNodeAttr.
Definition at line 618 of file LLVM.cpp.
References unwrap().
mlirLLVMAttrIsAMDStringAttr()
bool mlirLLVMAttrIsAMDStringAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDStringAttr.
Definition at line 564 of file LLVM.cpp.
References unwrap().
mlirLLVMCConvAttrGet()
MlirAttribute mlirLLVMCConvAttrGet (MlirContext ctx, MlirLLVMCConv cconv)
Creates a LLVM CConv attribute.
Definition at line 320 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMCConvAttrGetName()
MlirStringRef mlirLLVMCConvAttrGetName (void)
Definition at line 324 of file LLVM.cpp.
References wrap().
mlirLLVMComdatAttrGet()
MlirAttribute mlirLLVMComdatAttrGet (MlirContext ctx, MlirLLVMComdat comdat)
Creates a LLVM Comdat attribute.
Definition at line 326 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMComdatAttrGetName()
MlirStringRef mlirLLVMComdatAttrGetName (void)
Definition at line 330 of file LLVM.cpp.
References wrap().
mlirLLVMDIAnnotationAttrGet()
MlirAttribute mlirLLVMDIAnnotationAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute value)
Creates a LLVM DIAnnotation attribute.
Definition at line 545 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIAnnotationAttrGetName()
MlirStringRef mlirLLVMDIAnnotationAttrGetName (void)
Definition at line 551 of file LLVM.cpp.
References wrap().
mlirLLVMDIBasicTypeAttrGet()
MlirAttribute mlirLLVMDIBasicTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, MlirLLVMTypeEncoding encoding)
Creates a LLVM DIBasicType attribute.
Definition at line 232 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIBasicTypeAttrGetName()
MlirStringRef mlirLLVMDIBasicTypeAttrGetName (void)
Definition at line 241 of file LLVM.cpp.
References wrap().
mlirLLVMDICompileUnitAttrGet()
MlirAttribute mlirLLVMDICompileUnitAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, unsigned int sourceLanguage, MlirAttribute file, MlirAttribute producer, bool isOptimized, MlirLLVMDIEmissionKind emissionKind, bool isDebugInfoForProfiling, MlirLLVMDINameTableKind nameTableKind, MlirAttribute splitDebugFilename, intptr_t nImportedEntities, MlirAttribute const * importedEntities)
Creates a LLVM DICompileUnit attribute.
Definition at line 352 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDICompileUnitAttrGetName()
MlirStringRef mlirLLVMDICompileUnitAttrGetName (void)
Definition at line 373 of file LLVM.cpp.
References wrap().
mlirLLVMDICompileUnitAttrGetRecSelf()
MlirAttribute mlirLLVMDICompileUnitAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompileUnitAttr attribute.
Definition at line 348 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDICompositeTypeAttrGet()
MlirAttribute mlirLLVMDICompositeTypeAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, int64_t flags, uint64_t sizeInBits, uint64_t alignInBits, intptr_t nElements, MlirAttribute const * elements, MlirAttribute dataLocation, MlirAttribute rank, MlirAttribute allocated, MlirAttribute associated, MlirAttribute identifier, MlirAttribute discriminator)
Creates a LLVM DICompositeType attribute.
Definition at line 250 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDICompositeTypeAttrGetName()
MlirStringRef mlirLLVMDICompositeTypeAttrGetName (void)
Definition at line 276 of file LLVM.cpp.
References wrap().
mlirLLVMDICompositeTypeAttrGetRecSelf()
MlirAttribute mlirLLVMDICompositeTypeAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompositeType attribute.
Definition at line 245 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIDerivedTypeAttrGet()
MlirAttribute mlirLLVMDIDerivedTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, uint64_t sizeInBits, uint32_t alignInBits, uint64_t offsetInBits, int64_t dwarfAddressSpace, int64_t flags, MlirAttribute extraData)
Creates a LLVM DIDerivedType attribute.
Note that dwarfAddressSpace is an optional field, where MLIR_CAPI_DWARF_ADDRESS_SPACE_NULL indicates null and non-negative values indicate a value present.
Definition at line 280 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIDerivedTypeAttrGetBaseType()
MlirAttribute mlirLLVMDIDerivedTypeAttrGetBaseType (MlirAttribute diDerivedType)
Gets the base type from a LLVM DIDerivedType attribute.
Definition at line 316 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIDerivedTypeAttrGetName()
MlirStringRef mlirLLVMDIDerivedTypeAttrGetName (void)
Definition at line 295 of file LLVM.cpp.
References wrap().
mlirLLVMDIExpressionAttrGet()
MlirAttribute mlirLLVMDIExpressionAttrGet (MlirContext ctx, intptr_t nOperations, MlirAttribute const * operations)
Creates a LLVM DIExpression attribute.
Definition at line 209 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDIExpressionAttrGetName()
MlirStringRef mlirLLVMDIExpressionAttrGetName (void)
Definition at line 220 of file LLVM.cpp.
References wrap().
mlirLLVMDIExpressionElemAttrGet()
MlirAttribute mlirLLVMDIExpressionElemAttrGet (MlirContext ctx, unsigned int opcode, intptr_t nArguments, uint64_t const * arguments)
Creates a LLVM DIExpressionElem attribute.
Definition at line 197 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIExpressionElemAttrGetName()
MlirStringRef mlirLLVMDIExpressionElemAttrGetName (void)
Definition at line 205 of file LLVM.cpp.
References wrap().
mlirLLVMDIFileAttrGet()
MlirAttribute mlirLLVMDIFileAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute directory)
Creates a LLVM DIFileAttr attribute.
Definition at line 340 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIFileAttrGetName()
MlirStringRef mlirLLVMDIFileAttrGetName (void)
Definition at line 346 of file LLVM.cpp.
References wrap().
mlirLLVMDIFlagsAttrGet()
MlirAttribute mlirLLVMDIFlagsAttrGet (MlirContext ctx, uint64_t value)
Creates a LLVM DIFlags attribute.
Definition at line 377 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIFlagsAttrGetName()
MlirStringRef mlirLLVMDIFlagsAttrGetName (void)
Definition at line 381 of file LLVM.cpp.
References wrap().
mlirLLVMDIImportedEntityAttrGet()
MlirAttribute mlirLLVMDIImportedEntityAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute scope, MlirAttribute entity, MlirAttribute file, unsigned int line, MlirAttribute name, intptr_t nElements, MlirAttribute const * elements)
Creates a LLVM DIImportedEntityAttr attribute.
Definition at line 527 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDIImportedEntityAttrGetName()
MlirStringRef mlirLLVMDIImportedEntityAttrGetName (void)
Definition at line 541 of file LLVM.cpp.
References wrap().
mlirLLVMDILexicalBlockAttrGet()
MlirAttribute mlirLLVMDILexicalBlockAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int line, unsigned int column)
Creates a LLVM DILexicalBlock attribute.
Definition at line 385 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDILexicalBlockAttrGetName()
MlirStringRef mlirLLVMDILexicalBlockAttrGetName (void)
Definition at line 395 of file LLVM.cpp.
References wrap().
mlirLLVMDILexicalBlockFileAttrGet()
MlirAttribute mlirLLVMDILexicalBlockFileAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int discriminator)
Creates a LLVM DILexicalBlockFile attribute.
Definition at line 399 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDILexicalBlockFileAttrGetName()
MlirStringRef mlirLLVMDILexicalBlockFileAttrGetName (void)
Definition at line 408 of file LLVM.cpp.
References wrap().
mlirLLVMDILocalVariableAttrGet()
MlirAttribute mlirLLVMDILocalVariableAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute name, MlirAttribute diFile, unsigned int line, unsigned int arg, unsigned int alignInBits, MlirAttribute diType, int64_t flags)
Creates a LLVM DILocalVariableAttr attribute.
Definition at line 412 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDILocalVariableAttrGetName()
MlirStringRef mlirLLVMDILocalVariableAttrGetName (void)
Definition at line 422 of file LLVM.cpp.
References wrap().
mlirLLVMDIModuleAttrGet()
MlirAttribute mlirLLVMDIModuleAttrGet (MlirContext ctx, MlirAttribute file, MlirAttribute scope, MlirAttribute name, MlirAttribute configMacros, MlirAttribute includePath, MlirAttribute apinotes, unsigned int line, bool isDecl)
Creates a LLVM DIModuleAttr attribute.
Definition at line 505 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIModuleAttrGetName()
MlirStringRef mlirLLVMDIModuleAttrGetName (void)
Definition at line 519 of file LLVM.cpp.
References wrap().
mlirLLVMDIModuleAttrGetScope()
MlirAttribute mlirLLVMDIModuleAttrGetScope (MlirAttribute diModule)
Gets the scope of this DIModuleAttr.
Definition at line 523 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDINullTypeAttrGet()
MlirAttribute mlirLLVMDINullTypeAttrGet (MlirContext ctx)
Creates a LLVM DINullType attribute.
Definition at line 224 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDINullTypeAttrGetName()
MlirStringRef mlirLLVMDINullTypeAttrGetName (void)
Definition at line 228 of file LLVM.cpp.
References wrap().
mlirLLVMDIStringTypeAttrGet()
MlirAttribute mlirLLVMDIStringTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, uint32_t alignInBits, MlirAttribute stringLength, MlirAttribute stringLengthExp, MlirAttribute stringLocationExp, MlirLLVMTypeEncoding encoding)
Definition at line 299 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIStringTypeAttrGetName()
MlirStringRef mlirLLVMDIStringTypeAttrGetName (void)
Definition at line 311 of file LLVM.cpp.
References wrap().
mlirLLVMDISubprogramAttrGet()
MlirAttribute mlirLLVMDISubprogramAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, MlirAttribute compileUnit, MlirAttribute scope, MlirAttribute name, MlirAttribute linkageName, MlirAttribute file, unsigned int line, unsigned int scopeLine, uint64_t subprogramFlags, MlirAttribute type, intptr_t nRetainedNodes, MlirAttribute const * retainedNodes, intptr_t nAnnotations, MlirAttribute const * annotations)
Creates a LLVM DISubprogramAttr attribute.
Definition at line 447 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDISubprogramAttrGetCompileUnit()
MlirAttribute mlirLLVMDISubprogramAttrGetCompileUnit (MlirAttribute diSubprogram)
Gets the compile unit from this DISubprogram.
Definition at line 493 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetFile()
MlirAttribute mlirLLVMDISubprogramAttrGetFile (MlirAttribute diSubprogram)
Gets the file from this DISubprogramAttr.
Definition at line 497 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetLine()
unsigned int mlirLLVMDISubprogramAttrGetLine (MlirAttribute diSubprogram)
Gets the line from this DISubprogramAttr.
Definition at line 484 of file LLVM.cpp.
References unwrap().
mlirLLVMDISubprogramAttrGetName()
MlirStringRef mlirLLVMDISubprogramAttrGetName (void)
Definition at line 476 of file LLVM.cpp.
References wrap().
mlirLLVMDISubprogramAttrGetRecSelf()
MlirAttribute mlirLLVMDISubprogramAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DISubprogramAttr attribute.
Definition at line 443 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetScope()
MlirAttribute mlirLLVMDISubprogramAttrGetScope (MlirAttribute diSubprogram)
Gets the scope from this DISubprogramAttr.
Definition at line 480 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetScopeLine()
unsigned int mlirLLVMDISubprogramAttrGetScopeLine (MlirAttribute diSubprogram)
Gets the scope line from this DISubprogram.
Definition at line 488 of file LLVM.cpp.
References unwrap().
mlirLLVMDISubprogramAttrGetType()
MlirAttribute mlirLLVMDISubprogramAttrGetType (MlirAttribute diSubprogram)
Gets the type from this DISubprogramAttr.
Definition at line 501 of file LLVM.cpp.
References mlir::getType(), unwrap(), and wrap().
mlirLLVMDISubroutineTypeAttrGet()
MlirAttribute mlirLLVMDISubroutineTypeAttrGet (MlirContext ctx, unsigned int callingConvention, intptr_t nTypes, MlirAttribute const * types)
Creates a LLVM DISubroutineTypeAttr attribute.
Definition at line 426 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDISubroutineTypeAttrGetName()
MlirStringRef mlirLLVMDISubroutineTypeAttrGetName (void)
Definition at line 439 of file LLVM.cpp.
References wrap().
mlirLLVMFunctionTypeGet()
MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const * argumentTypes, bool isVarArg)
Creates an llvm.func type.
Definition at line 76 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetInput()
MlirType mlirLLVMFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
Definition at line 100 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetName()
MlirStringRef mlirLLVMFunctionTypeGetName (void)
Definition at line 84 of file LLVM.cpp.
References wrap().
mlirLLVMFunctionTypeGetNumInputs()
intptr_t mlirLLVMFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
Definition at line 96 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetReturnType()
MlirType mlirLLVMFunctionTypeGetReturnType (MlirType type)
Returns the return type of the function type.
Definition at line 106 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetTypeID()
MlirTypeID mlirLLVMFunctionTypeGetTypeID (void)
Returns the TypeID of an LLVM function type.
Definition at line 92 of file LLVM.cpp.
References wrap().
mlirLLVMFunctionTypeIsVarArg()
bool mlirLLVMFunctionTypeIsVarArg (MlirType type)
Returns true if the function type is variadic.
Definition at line 110 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMLinkageAttrGet()
MlirAttribute mlirLLVMLinkageAttrGet (MlirContext ctx, MlirLLVMLinkage linkage)
Creates a LLVM Linkage attribute.
Definition at line 332 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMLinkageAttrGetName()
MlirStringRef mlirLLVMLinkageAttrGetName (void)
Definition at line 336 of file LLVM.cpp.
References wrap().
mlirLLVMMDConstantAttrGet()
MlirAttribute mlirLLVMMDConstantAttrGet (MlirContext ctx, MlirAttribute valueAttr)
Creates an LLVM MDConstantAttr wrapping an attribute.
Definition at line 576 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDConstantAttr::bindDerived().
mlirLLVMMDConstantAttrGetTypeID()
MlirTypeID mlirLLVMMDConstantAttrGetTypeID (void)
Returns the TypeID of MDConstantAttr.
Definition at line 585 of file LLVM.cpp.
References wrap().
mlirLLVMMDConstantAttrGetValue()
MlirAttribute mlirLLVMMDConstantAttrGetValue (MlirAttribute attr)
Returns the attribute value of an LLVM MDConstantAttr.
Definition at line 589 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDConstantAttr::bindDerived().
mlirLLVMMDFuncAttrGet()
MlirAttribute mlirLLVMMDFuncAttrGet (MlirContext ctx, MlirAttribute name)
Creates an LLVM MDFuncAttr referencing a function symbol.
Definition at line 593 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDFuncAttr::bindDerived().
mlirLLVMMDFuncAttrGetName()
MlirAttribute mlirLLVMMDFuncAttrGetName (MlirAttribute attr)
Returns the symbol name of an LLVM MDFuncAttr.
Definition at line 606 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDFuncAttr::bindDerived().
mlirLLVMMDFuncAttrGetTypeID()
MlirTypeID mlirLLVMMDFuncAttrGetTypeID (void)
Returns the TypeID of MDFuncAttr.
Definition at line 602 of file LLVM.cpp.
References wrap().
mlirLLVMMDNodeAttrGet()
MlirAttribute mlirLLVMMDNodeAttrGet (MlirContext ctx, intptr_t nOperands, MlirAttribute const * operands)
Creates an LLVM MDNodeAttr.
Definition at line 610 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived().
mlirLLVMMDNodeAttrGetNumOperands()
intptr_t mlirLLVMMDNodeAttrGetNumOperands (MlirAttribute attr)
Returns the number of operands in an LLVM MDNodeAttr.
Definition at line 626 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived().
mlirLLVMMDNodeAttrGetOperand()
MlirAttribute mlirLLVMMDNodeAttrGetOperand (MlirAttribute attr, intptr_t index)
Returns the operand at the given index of an LLVM MDNodeAttr.
Definition at line 630 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived().
mlirLLVMMDNodeAttrGetTypeID()
MlirTypeID mlirLLVMMDNodeAttrGetTypeID (void)
Returns the TypeID of MDNodeAttr.
Definition at line 622 of file LLVM.cpp.
References wrap().
mlirLLVMMDStringAttrGet()
MlirAttribute mlirLLVMMDStringAttrGet (MlirContext ctx, MlirStringRef value)
Creates an LLVM MDStringAttr.
Definition at line 559 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDStringAttr::bindDerived().
mlirLLVMMDStringAttrGetTypeID()
MlirTypeID mlirLLVMMDStringAttrGetTypeID (void)
Returns the TypeID of MDStringAttr.
Definition at line 568 of file LLVM.cpp.
References wrap().
mlirLLVMMDStringAttrGetValue()
MlirStringRef mlirLLVMMDStringAttrGetValue (MlirAttribute attr)
Returns the string value of an LLVM MDStringAttr.
Definition at line 572 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDStringAttr::bindDerived().
mlirLLVMPointerTypeGet()
MlirType mlirLLVMPointerTypeGet (MlirContext ctx, unsigned addressSpace)
Creates an llvm.ptr type.
Definition at line 26 of file LLVM.cpp.
References mlirLLVMPointerTypeGet(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::PointerType::bindDerived(), and mlirLLVMPointerTypeGet().
mlirLLVMPointerTypeGetAddressSpace()
unsigned mlirLLVMPointerTypeGetAddressSpace (MlirType pointerType)
Returns address space of llvm.ptr.
Definition at line 42 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::PointerType::bindDerived().
mlirLLVMPointerTypeGetName()
MlirStringRef mlirLLVMPointerTypeGetName (void)
Definition at line 30 of file LLVM.cpp.
References wrap().
mlirLLVMPointerTypeGetTypeID()
MlirTypeID mlirLLVMPointerTypeGetTypeID (void)
Definition at line 34 of file LLVM.cpp.
References wrap().
mlirLLVMStructTypeGetElementType()
MlirType mlirLLVMStructTypeGetElementType (MlirType type, intptr_t position)
Returns the positions-th field of the struct.
Asserts if the struct is opaque, not yet initialized or if the position is out of range.
Definition at line 134 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeGetIdentifier()
MlirStringRef mlirLLVMStructTypeGetIdentifier (MlirType type)
Returns the identifier of the identified struct.
Asserts that the struct is identified, i.e., not literal.
Definition at line 142 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeGetName()
MlirStringRef mlirLLVMStructTypeGetName (void)
Definition at line 122 of file LLVM.cpp.
References wrap().
mlirLLVMStructTypeGetNumElementTypes()
intptr_t mlirLLVMStructTypeGetNumElementTypes (MlirType type)
Returns the number of fields in the struct.
Asserts if the struct is opaque or not yet initialized.
Definition at line 130 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeGetTypeID()
MlirTypeID mlirLLVMStructTypeGetTypeID (void)
Definition at line 118 of file LLVM.cpp.
References wrap().
mlirLLVMStructTypeIdentifiedGet()
MlirType mlirLLVMStructTypeIdentifiedGet (MlirContext ctx, MlirStringRef name)
Creates an LLVM identified struct type with no body.
If a struct type with this name already exists in the context, returns that type. Use mlirLLVMStructTypeIdentifiedNewGet to create a fresh struct type, potentially renaming it. The body should be set separatelty by calling mlirLLVMStructTypeSetBody, if it isn't set already.
Definition at line 173 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIdentifiedNewGet()
MlirType mlirLLVMStructTypeIdentifiedNewGet (MlirContext ctx, MlirStringRef name, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM identified struct type with no body and a name starting with the given prefix.
If a struct with the exact name as the given prefix already exists, appends an unspecified suffix to the name so that the name is unique in context.
Definition at line 177 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIsLiteral()
bool mlirLLVMStructTypeIsLiteral (MlirType type)
Returns true if the type is a literal (unnamed) LLVM struct type.
Definition at line 126 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIsOpaque()
bool mlirLLVMStructTypeIsOpaque (MlirType type)
Returns true is the struct is explicitly opaque (will not have a body) or uninitialized (will eventually have a body).
Definition at line 146 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIsPacked()
bool mlirLLVMStructTypeIsPacked (MlirType type)
Returns true if the struct is packed.
Definition at line 138 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeLiteralGet()
MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
This may assert if the fields have types not compatible with the LLVM dialect. For a graceful failure, use the checked version.
Definition at line 150 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeLiteralGetChecked()
MlirType mlirLLVMStructTypeLiteralGetChecked (MlirLocation loc, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type if possible.
Emits a diagnostic at the given location and returns null otherwise.
Definition at line 159 of file LLVM.cpp.
References mlir::emitError(), unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeOpaqueGet()
MlirType mlirLLVMStructTypeOpaqueGet (MlirContext ctx, MlirStringRef name)
Definition at line 169 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeSetBody()
MlirLogicalResult mlirLLVMStructTypeSetBody (MlirType structType, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Sets the body of the identified struct if it hasn't been set yet.
Returns whether the operation was successful.
Definition at line 187 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMVoidTypeGet()
MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
Definition at line 46 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMVoidTypeGetName()
MlirStringRef mlirLLVMVoidTypeGetName (void)
Definition at line 50 of file LLVM.cpp.
References wrap().
mlirTypeIsALLVMArrayType()
bool mlirTypeIsALLVMArrayType (MlirType type)
Returns true if the type is an LLVM dialect array type.
Definition at line 52 of file LLVM.cpp.
References unwrap().
mlirTypeIsALLVMFunctionType()
bool mlirTypeIsALLVMFunctionType (MlirType type)
Returns true if the type is an LLVM dialect function type.
Definition at line 88 of file LLVM.cpp.
References unwrap().
mlirTypeIsALLVMPointerType()
bool mlirTypeIsALLVMPointerType (MlirType type)
Returns true if the type is an LLVM dialect pointer type.
Definition at line 38 of file LLVM.cpp.
References unwrap().
mlirTypeIsALLVMStructType()
bool mlirTypeIsALLVMStructType (MlirType type)
Returns true if the type is an LLVM dialect struct type.
Definition at line 114 of file LLVM.cpp.
References unwrap().