MLIR: lib/Dialect/LLVMIR/IR/LLVMAttrs.cpp File Reference
LLVMAttrs.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMAttrs.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/Ptr/IR/PtrEnums.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "mlir/Dialect/LLVMIR/LLVMAttrInterfaces.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpsEnums.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpsAttrDefs.cpp.inc"
Macros
#define GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_LIST
Functions
static ParseResult parseExpressionArg (AsmParser &parser, uint64_t opcode, SmallVector< uint64_t > &args)
Parses DWARF expression arguments with respect to the DWARF operation opcode.
static void printExpressionArg (AsmPrinter &printer, uint64_t opcode, ArrayRef< uint64_t > args)
Prints DWARF expression arguments with respect to the specific DWARF operation.
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 40 of file LLVMAttrs.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
Function Documentation
parseExpressionArg()
ParseResult parseExpressionArg (AsmParser & parser, uint64_t opcode, SmallVector< uint64_t > & args) static
Parses DWARF expression arguments with respect to the DWARF operation opcode.
Some DWARF expression operations have a specific number of operands and may appear in a textual form.
Definition at line 259 of file LLVMAttrs.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseInteger(), mlir::AsmParser::parseOptionalKeyword(), and success().
printExpressionArg()
void printExpressionArg (AsmPrinter & printer, uint64_t opcode, ArrayRef< uint64_t > args) static
Prints DWARF expression arguments with respect to the specific DWARF operation.
Some operands are printed in their textual form.
Definition at line 295 of file LLVMAttrs.cpp.