MLIR: lib/Dialect/Linalg/Transforms/Loops.cpp File Reference
Loops.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/TypeSwitch.h"
Classes
struct InputAndOutputIndices
Functions
static SmallVector< Value > makeCanonicalAffineApplies (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > vals)
template<typename LoadOpTy , typename StoreOpTy , typename OpType >
static void inlineRegionAndEmitStore (OpBuilder &b, Location loc, OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value >> indexing, ArrayRef< Value > outputBuffers)
template<typename SingleInputPoolingOp >
static InputAndOutputIndices getInputAndOutputIndices (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, SingleInputPoolingOp op)
template<typename LoadOpTy , typename StoreOpTy >
static void emitScalarImplementation (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, LinalgOp linalgOp)
Emits the MLIR for the scalar part of the generic op by:
Value getPaddedInput (OpBuilder &b, Location loc, Value input, ArrayRef< Value > indices, ArrayRef< int > skipPadding, Value padValue)
static bool hasPadding (ConvOp convOp)
Returns true is convOp has a non-zero padding.
template<typename LoadOpTy , typename StoreOpTy >
static void emitScalarImplementation (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, ConvOp convOp)
template<typename PoolingOp >
static bool hasPadding (PoolingOp poolingOp)
template<typename LoadOpTy , typename StoreOpTy , typename PoolingOp >
static Value getPoolingInput (OpBuilder &b, Location loc, PoolingOp op, ArrayRef< Value > inputIndices)
template<typename LoadOpTy , typename StoreOpTy , typename OpType >
void emitPoolingMinMaxScalarImplementation (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, OpType op)
template<typename LoadOpTy , typename StoreOpTy >
static void emitScalarImplementation (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, PoolingMaxOp op)
template<typename LoadOpTy , typename StoreOpTy >
static void emitScalarImplementation (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, PoolingMinOp op)
template<typename LoadOpTy , typename StoreOpTy >
static void emitScalarImplementation (OpBuilder &b, Location loc, ArrayRef< Value > allIvs, PoolingSumOp op)
static void replaceIndexOpsByInductionVariables (LinalgOp linalgOp, PatternRewriter &rewriter, ArrayRef< Operation *> loopOps)
Replace the index operations in the body of the loop nest by the matching induction variables.
template<typename LoopTy >
static Optional< LinalgLoops > linalgOpToLoopsImpl (PatternRewriter &rewriter, LinalgOp linalgOp)
Function Documentation
emitPoolingMinMaxScalarImplementation()
template<typename LoadOpTy , typename StoreOpTy , typename OpType > void emitPoolingMinMaxScalarImplementation (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, OpType op)
Definition at line 336 of file Loops.cpp.
References mlir::OpBuilder::create(), getInputAndOutputIndices(), InputAndOutputIndices::inputs, loc, op, InputAndOutputIndices::outputs, mlir::ArithBuilder::select(), and value.
emitScalarImplementation() [1/5]
template<typename LoadOpTy , typename StoreOpTy > static void emitScalarImplementation (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, LinalgOp linalgOp) static
Emits the MLIR for the scalar part of the generic op by:
Emitting load ops for each input and output view in order. This is achieved by applying the appropriate input or output map to the enclosing induction variables.
Emitting a call to op.fun() that takes as arguments the scalars from point 1. above.
Emitting store ops to store the results of 2. to the output views.
An example output may resemble:
scf.for %i = %c0 to %0 step %c1 {
  scf.for %j = %c0 to %1 step %c1 {
    scf.for %k = %c0 to %4 step %c1 {
      %11 = load %arg0[%i, %j] :
        memref<?x?xf32, stride_specification>
      %12 = load %arg1[%i, %j, %k] :
        memref<?x?x?xf32, stride_specification>
      %13 = load %arg2[%i, %k, %j] :
        memref<?x?x?xf32, stride_specification>
      %14:2 = call @foo(%11, %12, %13) : (f32, f32, f32) -> (f32, f32)
      store %14#0, %arg1[%i, %j, %k] :
        memref<?x?x?Xf32, stride_specification>
      store %14#1, %arg2[%i, %k, %j] :
        memref<?x?x?Xf32, stride_specification>
   }
  }
}
Definition at line 117 of file Loops.cpp.
References mlir::OpBuilder::create(), loc, and makeCanonicalAffineApplies().
emitScalarImplementation() [2/5]
template<typename LoadOpTy , typename StoreOpTy > static void emitScalarImplementation (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, ConvOp convOp) static
Definition at line 274 of file Loops.cpp.
References mlir::ArithBuilder::add(), mlir::Type::cast(), mlir::OpBuilder::create(), getElementType(), getPaddedInput(), hasPadding(), loc, makeCanonicalAffineApplies(), maps, and mlir::ArithBuilder::mul().
emitScalarImplementation() [3/5]
template<typename LoadOpTy , typename StoreOpTy > static void emitScalarImplementation (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, PoolingMaxOp op) static
Definition at line 355 of file Loops.cpp.
References loc, and op.
emitScalarImplementation() [4/5]
template<typename LoadOpTy , typename StoreOpTy > static void emitScalarImplementation (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, PoolingMinOp op) static
Definition at line 362 of file Loops.cpp.
References loc, and op.
emitScalarImplementation() [5/5]
template<typename LoadOpTy , typename StoreOpTy > static void emitScalarImplementation (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, PoolingSumOp op) static
Definition at line 369 of file Loops.cpp.
References mlir::ArithBuilder::add(), getInputAndOutputIndices(), loc, and op.
getInputAndOutputIndices()
template<typename SingleInputPoolingOp > static InputAndOutputIndices getInputAndOutputIndices (OpBuilder & b, Location loc, ArrayRef< Value > allIvs, SingleInputPoolingOp op) static
Definition at line 76 of file Loops.cpp.
References makeCanonicalAffineApplies(), and maps.
Referenced by emitPoolingMinMaxScalarImplementation(), and emitScalarImplementation().
getPaddedInput()
Value getPaddedInput (OpBuilder & b, Location loc, Value input, ArrayRef< Value > indices, ArrayRef< int > skipPadding, Value padValue)
Definition at line 165 of file Loops.cpp.
References mlir::OpBuilder::create(), mlir::linalg::createOrFoldDimOp(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Type::getContext(), mlir::Value::getContext(), mlir::AffineMap::inferFromExprList(), and loc.
Referenced by emitScalarImplementation(), and getPoolingInput().
getPoolingInput()
template<typename LoadOpTy , typename StoreOpTy , typename PoolingOp > static Value getPoolingInput (OpBuilder & b, Location loc, PoolingOp op, ArrayRef< Value > inputIndices) static
Definition at line 322 of file Loops.cpp.
References mlir::OpBuilder::create(), getElementType(), getPaddedInput(), hasPadding(), and loc.
hasPadding() [1/2]
static bool hasPadding (ConvOp convOp) static
Returns true is convOp has a non-zero padding.
Definition at line 265 of file Loops.cpp.
Referenced by emitScalarImplementation(), and getPoolingInput().
hasPadding() [2/2]
template<typename PoolingOp > static bool hasPadding (PoolingOp poolingOp) static
Definition at line 313 of file Loops.cpp.
inlineRegionAndEmitStore()
template<typename LoadOpTy , typename StoreOpTy , typename OpType > static void inlineRegionAndEmitStore (OpBuilder & b, Location loc, OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value >> indexing, ArrayRef< Value > outputBuffers) static
Definition at line 48 of file Loops.cpp.
References mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Operation::getOpOperands(), loc, mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), and map().
linalgOpToLoopsImpl()
template<typename LoopTy > static Optional<LinalgLoops> linalgOpToLoopsImpl (PatternRewriter & rewriter, LinalgOp linalgOp) static
Definition at line 412 of file Loops.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsAndFoldGreedily(), mlir::scf::buildLoopNest(), mlir::linalg::GenerateLoopNest< LoopTy >::doit(), mlir::AffineExpr::dyn_cast(), mlir::Value::dyn_cast(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::OpBuilder::getInsertionBlock(), mlir::Operation::getOperand(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::Block::getTerminator(), mlir::DialectRegistry::insert(), loc, map(), mlir::RewriterBase::mergeBlocks(), op, mlir::linalg::populateTiledLoopToSCFPattern(), replaceIndexOpsByInductionVariables(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::success(), and value.
makeCanonicalAffineApplies()
static SmallVector<Value> makeCanonicalAffineApplies (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > vals) static
Definition at line 28 of file Loops.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::AffineMap::isEmpty().
Referenced by emitScalarImplementation(), and getInputAndOutputIndices().
replaceIndexOpsByInductionVariables()
static void replaceIndexOpsByInductionVariables (LinalgOp linalgOp, PatternRewriter & rewriter, ArrayRef< Operation *> loopOps) static
Replace the index operations in the body of the loop nest by the matching induction variables.
Definition at line 381 of file Loops.cpp.
References op, and mlir::RewriterBase::replaceOp().
Referenced by linalgOpToLoopsImpl().