MLIR: lib/Dialect/Affine/Transforms/LoopUnroll.cpp File Reference
LoopUnroll.cpp File Reference
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/LoopUtils.h"
#include "llvm/Support/CommandLine.h"
#include <optional>
#include "mlir/Dialect/Affine/Passes.h.inc"
Classes
class mlir::affine::impl::AffineLoopUnrollBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::affine
namespace mlir::affine::impl
Macros
#define GEN_PASS_DEF_AFFINELOOPUNROLL
#define DEBUG_TYPE "affine-loop-unroll"
Functions
static bool isInnermostAffineForOp (AffineForOp op)
Returns true if no other affine.for ops are nested within op.
static void gatherInnermostLoops (FunctionOpInterface f, SmallVectorImpl< AffineForOp > &loops)
Gathers loops that have no affine.for's nested within.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-unroll"
Definition at line 28 of file LoopUnroll.cpp.
GEN_PASS_DEF_AFFINELOOPUNROLL
#define GEN_PASS_DEF_AFFINELOOPUNROLL
Definition at line 23 of file LoopUnroll.cpp.
Function Documentation
gatherInnermostLoops()
void gatherInnermostLoops (FunctionOpInterface f, SmallVectorImpl< AffineForOp > & loops) static
Gathers loops that have no affine.for's nested within.
Definition at line 76 of file LoopUnroll.cpp.
References isInnermostAffineForOp().
isInnermostAffineForOp()
bool isInnermostAffineForOp (AffineForOp op) static
Returns true if no other affine.for ops are nested within op.
Definition at line 67 of file LoopUnroll.cpp.
References mlir::WalkResult::interrupt().
Referenced by gatherInnermostLoops().