MLIR: lib/Dialect/SparseTensor/Transforms/Utils/LoopEmitter.cpp File Reference
LoopEmitter.cpp File Reference
#include "LoopEmitter.h"
#include "CodegenUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorType.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
Macros
#define CMPI(p, l, r)
#define C_IDX(v)
#define YIELD(vs)
#define ADDI(lhs, rhs)
#define ANDI(lhs, rhs)
#define SUBI(lhs, rhs)
#define MULI(lhs, rhs)
#define REMUI(lhs, rhs)
#define DIVUI(lhs, rhs)
#define SELECT(c, l, r)
Functions
static void dumpIndexMemRef (OpBuilder &builder, Location loc, Value memref)
static Value genSliceOffset (OpBuilder &builder, Location loc, Value tensor, Level lvl)
static Value genSliceStride (OpBuilder &builder, Location loc, Value tensor, Level lvl)
static bool isIntOrFPZero (Attribute attr)
static Value unFoldOpIntResult (OpBuilder &builder, Location loc, OpFoldResult ofr)
static Value tryFoldTensors (Value t)
Macro Definition Documentation
ADDI
#define ADDI (lhs, rhs)
Value:
(arith::AddIOp::create(builder, loc, (lhs), (rhs)))
Definition at line 33 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::LoopEmitter::genAffine().
ANDI
#define ANDI (lhs, rhs)
Value:
(arith::AndIOp::create(builder, loc, (lhs), (rhs)))
Definition at line 34 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::genCoIteration().
C_IDX
#define C_IDX (v)
Value:
(constantIndex(builder, loc, (v)))
Definition at line 31 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::LoopEmitter::enterNewLoopSeq(), mlir::sparse_tensor::LoopEmitter::genAffine(), mlir::sparse_tensor::makeNonEmptySubSectIterator(), mlir::sparse_tensor::makeTraverseSubSectIterator(), and mlir::sparse_tensor::SparseIterationSpace::SparseIterationSpace().
CMPI
#define CMPI (p, l, r)
Value:
  (arith::CmpIOp::create(builder, loc, arith::CmpIPredicate::p, (l), (r))      \
       .getResult())
Definition at line 27 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::genCoIteration().
DIVUI
#define DIVUI (lhs, rhs)
Value:
(arith::DivUIOp::create(builder, loc, (lhs), (rhs)))
Definition at line 38 of file LoopEmitter.cpp.
MULI
#define MULI (lhs, rhs)
Value:
(arith::MulIOp::create(builder, loc, (lhs), (rhs)))
Definition at line 36 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::LoopEmitter::genAffine().
REMUI
#define REMUI (lhs, rhs)
Value:
(arith::RemUIOp::create(builder, loc, (lhs), (rhs)))
Definition at line 37 of file LoopEmitter.cpp.
SELECT
#define SELECT (c, l, r)
Value:
(arith::SelectOp::create(builder, loc, (c), (l), (r)))
Definition at line 39 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::genCoIteration().
SUBI
#define SUBI (lhs, rhs)
Value:
(arith::SubIOp::create(builder, loc, (lhs), (rhs)))
Definition at line 35 of file LoopEmitter.cpp.
YIELD
#define YIELD (vs)
Value:
(scf::YieldOp::create(builder, loc, (vs)))
Definition at line 32 of file LoopEmitter.cpp.
Referenced by mlir::sparse_tensor::SparseIterator::forwardIf().
Function Documentation
dumpIndexMemRef()
void dumpIndexMemRef (OpBuilder & builder, Location loc, Value memref) static
Definition at line 46 of file LoopEmitter.cpp.
References mlir::sparse_tensor::createFuncCall(), mlir::Builder::getIndexType(), and mlir::sparse_tensor::On.
genSliceOffset()
Value genSliceOffset (OpBuilder & builder, Location loc, Value tensor, Level lvl) static
Definition at line 64 of file LoopEmitter.cpp.
References mlir::sparse_tensor::createOrFoldSliceOffsetOp(), mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::sparse_tensor::toDim().
genSliceStride()
Value genSliceStride (OpBuilder & builder, Location loc, Value tensor, Level lvl) static
Definition at line 70 of file LoopEmitter.cpp.
References mlir::sparse_tensor::createOrFoldSliceStrideOp(), mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::sparse_tensor::toDim().
isIntOrFPZero()
bool isIntOrFPZero (Attribute attr) static
Definition at line 76 of file LoopEmitter.cpp.
Referenced by tryFoldTensors().
tryFoldTensors()
Value tryFoldTensors (Value t) static
Definition at line 91 of file LoopEmitter.cpp.
References mlir::Value::getDefiningOp(), isIntOrFPZero(), mlir::m_Constant(), mlir::m_Op(), mlir::matchPattern(), and mlir::sparse_tensor::tryGetSparseTensorType().
Referenced by mlir::sparse_tensor::LoopEmitter::initializeLoopEmit().
unFoldOpIntResult()
Value unFoldOpIntResult (OpBuilder & builder, Location loc, OpFoldResult ofr) static
Definition at line 84 of file LoopEmitter.cpp.
References mlir::sparse_tensor::constantIndex(), and mlir::getConstantIntValue().