MLIR: lib/Dialect/Vector/Transforms/LowerVectorTransfer.cpp File Reference
LowerVectorTransfer.cpp File Reference
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
Functions
static ArrayAttr inverseTransposeInBoundsAttr (OpBuilder &builder, ArrayAttr attr, const SmallVector< unsigned > &permutation)
Transpose a vector transfer op's in_bounds attribute by applying reverse permutation based on the given indices.
static Value extendVectorRank (OpBuilder &builder, Location loc, Value vec, int64_t addedRank)
Extend the rank of a vector Value by addedRanks by adding outer unit dimensions.
static Value extendMaskRank (OpBuilder &builder, Location loc, Value vec, int64_t addedRank)
Extend the rank of a vector Value by addedRanks by adding inner unit dimensions.
Function Documentation
extendMaskRank()
static Value extendMaskRank (OpBuilder & builder, Location loc, Value vec, int64_t addedRank) static
Extend the rank of a vector Value by addedRanks by adding inner unit dimensions.
Definition at line 52 of file LowerVectorTransfer.cpp.
References extendVectorRank(), and mlir::Value::getType().
extendVectorRank()
static Value extendVectorRank (OpBuilder & builder, Location loc, Value vec, int64_t addedRank) static
Extend the rank of a vector Value by addedRanks by adding outer unit dimensions.
Definition at line 35 of file LowerVectorTransfer.cpp.
References mlir::get(), and mlir::Value::getType().
Referenced by extendMaskRank().
inverseTransposeInBoundsAttr()
static ArrayAttr inverseTransposeInBoundsAttr (OpBuilder & builder, ArrayAttr attr, const SmallVector< unsigned > & permutation) static
Transpose a vector transfer op's in_bounds attribute by applying reverse permutation based on the given indices.
Definition at line 23 of file LowerVectorTransfer.cpp.
References mlir::Builder::getBoolArrayAttr().