MLIR: lib/Conversion/GPUToNVVM/LowerGpuOpsToNVVMOps.cpp File Reference
LowerGpuOpsToNVVMOps.cpp File Reference
#include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
#include "mlir/Conversion/ConvertToLLVM/ToLLVMPass.h"
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "mlir/Conversion/GPUToNVVM/GPUToNVVM.h"
#include "mlir/Conversion/GPUToNVVM/GPUToNVVMPass.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/LoweringOptions.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/NVGPU/IR/NVGPUDialect.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "../GPUCommon/GPUOpsLowering.h"
#include "../GPUCommon/IndexIntrinsicsOpLowering.h"
#include "../GPUCommon/OpToFuncCallLowering.h"
#include <optional>
#include "mlir/Conversion/Passes.h.inc"
#include "GPUToNVVM.cpp.inc"
Classes
class mlir::impl::ConvertGpuOpsToNVVMOpsBase< DerivedT >
struct SincosOpLowering
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_CONVERTGPUOPSTONVVMOPS
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToNVVMOps ()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToNVVMOps (ConvertGpuOpsToNVVMOpsOptions options)
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToNVVMOps ()
std::unique_ptr<::mlir::Pass > mlir::createConvertGpuOpsToNVVMOps (ConvertGpuOpsToNVVMOpsOptions options)
template<typename OpTy>
static void populateOpPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func, StringRef f32ApproxFunc="", StringRef f16Func="")
template<typename OpTy>
static void populateIntOpPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns, PatternBenefit benefit, StringRef i32Func)
template<typename OpTy>
static void populateFloatIntOpPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func)
Macro Definition Documentation
GEN_PASS_DEF_CONVERTGPUOPSTONVVMOPS
#define GEN_PASS_DEF_CONVERTGPUOPSTONVVMOPS
Definition at line 40 of file LowerGpuOpsToNVVMOps.cpp.
Function Documentation
populateFloatIntOpPatterns()
template<typename OpTy> void populateFloatIntOpPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func) static
Definition at line 589 of file LowerGpuOpsToNVVMOps.cpp.
References mlir::patterns.
Referenced by mlir::populateLibDeviceConversionPatterns().
populateIntOpPatterns()
template<typename OpTy> void populateIntOpPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns, PatternBenefit benefit, StringRef i32Func) static
Definition at line 580 of file LowerGpuOpsToNVVMOps.cpp.
References mlir::patterns.
Referenced by mlir::populateLibDeviceConversionPatterns().
populateOpPatterns()
template<typename OpTy> void populateOpPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func, StringRef f32ApproxFunc = "", StringRef f16Func = "") static
Definition at line 568 of file LowerGpuOpsToNVVMOps.cpp.
References mlir::patterns.
Referenced by mlir::populateLibDeviceConversionPatterns().