MLIR: lib/Dialect/SPIRV/Transforms/LowerABIAttributesPass.cpp File Reference
LowerABIAttributesPass.cpp File Reference
#include "mlir/Dialect/SPIRV/Transforms/Passes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVEnums.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/FormatVariadic.h"
#include "mlir/Dialect/SPIRV/Transforms/Passes.h.inc"
Classes
class mlir::spirv::impl::SPIRVLowerABIAttributesPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::spirv
namespace mlir::spirv::impl
Macros
#define GEN_PASS_DEF_SPIRVLOWERABIATTRIBUTESPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::spirv::impl::createSPIRVLowerABIAttributesPass ()
std::unique_ptr<::mlir::Pass > mlir::spirv::createSPIRVLowerABIAttributesPass ()
static spirv::GlobalVariableOp createGlobalVarForEntryPointArgument (OpBuilder &builder, spirv::FuncOp funcOp, unsigned argIndex, spirv::InterfaceVarABIAttr abiInfo)
Creates a global variable for an argument based on the ABI info.
static spirv::GlobalVariableOp createGlobalVarForGraphEntryPoint (OpBuilder &builder, spirv::GraphARMOp graphOp, unsigned index, bool isArg, spirv::InterfaceVarABIAttr abiInfo)
Creates a global variable for an argument or result based on the ABI info.
static LogicalResult getInterfaceVariables (mlir::FunctionOpInterface funcOp, SmallVectorImpl< Attribute > &interfaceVars)
Gets the global variables that need to be specified as interface variable with an spirv.EntryPointOp.
static LogicalResult lowerEntryPointABIAttr (spirv::FuncOp funcOp, OpBuilder &builder)
Lowers the entry point attribute.
Macro Definition Documentation
GEN_PASS_DEF_SPIRVLOWERABIATTRIBUTESPASS
#define GEN_PASS_DEF_SPIRVLOWERABIATTRIBUTESPASS
Definition at line 29 of file LowerABIAttributesPass.cpp.
Function Documentation
createGlobalVarForEntryPointArgument()
spirv::GlobalVariableOp createGlobalVarForEntryPointArgument (OpBuilder & builder, spirv::FuncOp funcOp, unsigned argIndex, spirv::InterfaceVarABIAttr abiInfo) static
Creates a global variable for an argument based on the ABI info.
Definition at line 38 of file LowerABIAttributesPass.cpp.
References mlir::VulkanLayoutUtils::decorateType(), mlir::spirv::PointerType::get(), mlir::spirv::StructType::get(), mlir::spirv::InterfaceVarABIAttr::getBinding(), mlir::spirv::InterfaceVarABIAttr::getDescriptorSet(), mlir::spirv::InterfaceVarABIAttr::getStorageClass(), and mlir::OpBuilder::setInsertionPoint().
createGlobalVarForGraphEntryPoint()
spirv::GlobalVariableOp createGlobalVarForGraphEntryPoint (OpBuilder & builder, spirv::GraphARMOp graphOp, unsigned index, bool isArg, spirv::InterfaceVarABIAttr abiInfo) static
Creates a global variable for an argument or result based on the ABI info.
Definition at line 91 of file LowerABIAttributesPass.cpp.
References mlir::spirv::PointerType::get(), mlir::spirv::InterfaceVarABIAttr::getBinding(), mlir::spirv::InterfaceVarABIAttr::getDescriptorSet(), mlir::spirv::InterfaceVarABIAttr::getStorageClass(), and mlir::OpBuilder::setInsertionPoint().
getInterfaceVariables()
LogicalResult getInterfaceVariables (mlir::FunctionOpInterface funcOp, SmallVectorImpl< Attribute > & interfaceVars) static
Gets the global variables that need to be specified as interface variable with an spirv.EntryPointOp.
Traverses the body of a entry function to do so.
Definition at line 118 of file LowerABIAttributesPass.cpp.
References mlir::spirv::TargetEnv::getVersion(), mlir::spirv::lookupTargetEnv(), and success().
Referenced by lowerEntryPointABIAttr().
lowerEntryPointABIAttr()
LogicalResult lowerEntryPointABIAttr (spirv::FuncOp funcOp, OpBuilder & builder) static
Lowers the entry point attribute.
Definition at line 157 of file LowerABIAttributesPass.cpp.
References mlir::spirv::getEntryPointABIAttrName(), mlir::spirv::getExecutionModel(), getInterfaceVariables(), mlir::spirv::lookupTargetEnv(), and mlir::OpBuilder::setInsertionPointToEnd().