MLIR: lib/Bindings/Python/MainModule.cpp File Reference
MainModule.cpp File Reference
#include "Globals.h"
#include "IRModule.h"
#include "NanobindUtils.h"
#include "Pass.h"
#include "Rewrite.h"
#include "mlir/Bindings/Python/Nanobind.h"
Functions
NB_MODULE (_mlir, m)
Function Documentation
NB_MODULE()
NB_MODULE (_mlir , m)
Definition at line 25 of file MainModule.cpp.
References mlir::python::PyGlobals::addDialectSearchPrefix(), mlir::python::PyGlobals::get(), mlir::python::PyGlobals::getDialectSearchPrefixes(), mlir::python::PyGlobals::getTracebackLoc(), mlir::python::PyGlobals::TracebackLoc::kMaxFrames, mlir::python::PyGlobals::loadDialectModule(), mlir::python::PyGlobals::TracebackLoc::locTracebackFramesLimit(), mlir::python::PyGlobals::TracebackLoc::locTracebacksEnabled(), MLIR_PYTHON_CAPI_TYPE_CASTER_REGISTER_ATTR, MLIR_PYTHON_CAPI_VALUE_CASTER_REGISTER_ATTR, mlir::python::populateIRAffine(), mlir::python::populateIRAttributes(), mlir::python::populateIRCore(), mlir::python::populateIRInterfaces(), mlir::python::populateIRTypes(), mlir::python::populatePassManagerSubmodule(), mlir::python::populateRewriteSubmodule(), mlir::python::PyGlobals::registerDialectImpl(), mlir::python::PyGlobals::registerOperationImpl(), mlir::python::PyGlobals::TracebackLoc::registerTracebackFileExclusion(), mlir::python::PyGlobals::TracebackLoc::registerTracebackFileInclusion(), mlir::python::PyGlobals::registerTypeCaster(), mlir::python::PyGlobals::registerValueCaster(), mlir::python::PyGlobals::setDialectSearchPrefixes(), mlir::python::PyGlobals::TracebackLoc::setLocTracebackFramesLimit(), and mlir::python::PyGlobals::TracebackLoc::setLocTracebacksEnabled().