MLIR: lib/Conversion/MathToNVVM/MathToNVVM.cpp File Reference
MathToNVVM.cpp File Reference
#include "mlir/Conversion/MathToNVVM/MathToNVVM.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/Pass/Pass.h"
#include "../GPUCommon/GPUOpsLowering.h"
#include "../GPUCommon/OpToFuncCallLowering.h"
#include "mlir/Conversion/Passes.h.inc"
Classes
class mlir::impl::ConvertMathToNVVMBase< DerivedT >
struct SincosOpLowering
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_CONVERTMATHTONVVM
#define DEBUG_TYPE "math-to-nvvm"
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToNVVM ()
std::unique_ptr<::mlir::Pass > mlir::createConvertMathToNVVM ()
template<typename OpTy>
static void populateOpPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func, StringRef f32ApproxFunc="", StringRef f16Func="")
template<typename OpTy>
static void populateIntOpPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns, PatternBenefit benefit, StringRef i32Func)
template<typename OpTy>
static void populateFloatIntOpPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "math-to-nvvm"
Definition at line 29 of file MathToNVVM.cpp.
GEN_PASS_DEF_CONVERTMATHTONVVM
#define GEN_PASS_DEF_CONVERTMATHTONVVM
Definition at line 23 of file MathToNVVM.cpp.
Function Documentation
populateFloatIntOpPatterns()
template<typename OpTy> void populateFloatIntOpPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func) static
Definition at line 53 of file MathToNVVM.cpp.
References mlir::RewritePatternSet::add().
Referenced by mlir::populateLibDeviceConversionPatterns().
populateIntOpPatterns()
template<typename OpTy> void populateIntOpPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns, PatternBenefit benefit, StringRef i32Func) static
Definition at line 44 of file MathToNVVM.cpp.
References mlir::RewritePatternSet::add().
Referenced by mlir::populateLibDeviceConversionPatterns().
populateOpPatterns()
template<typename OpTy> void populateOpPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns, PatternBenefit benefit, StringRef f32Func, StringRef f64Func, StringRef f32ApproxFunc = "", StringRef f16Func = "") static
Definition at line 32 of file MathToNVVM.cpp.
References mlir::RewritePatternSet::add().
Referenced by mlir::populateLibDeviceConversionPatterns().