MLIR: lib/Conversion/LLVMCommon/MemRefBuilder.cpp File Reference
MemRefBuilder.cpp File Reference
#include "mlir/Conversion/LLVMCommon/MemRefBuilder.h"
#include "MemRefDescriptor.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/Builders.h"
#include "llvm/Support/MathExtras.h"
Functions
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
static std::pair< Value, Type > castToElemPtrPtr (OpBuilder &builder, Location loc, Value memRefDescPtr, LLVM::LLVMPointerType elemPtrType)
Function Documentation
castToElemPtrPtr()
static std::pair<Value, Type> castToElemPtrPtr (OpBuilder & builder, Location loc, Value memRefDescPtr, LLVM::LLVMPointerType elemPtrType) static
Definition at line 417 of file MemRefBuilder.cpp.
References mlir::get(), and mlir::Builder::getContext().
Referenced by mlir::UnrankedMemRefDescriptor::alignedPtr(), mlir::UnrankedMemRefDescriptor::offsetBasePtr(), and mlir::UnrankedMemRefDescriptor::setAlignedPtr().
createIndexAttrConstant()
static Value createIndexAttrConstant (OpBuilder & builder, Location loc, Type resultType, int64_t value) static
Definition at line 100 of file MemRefBuilder.cpp.
References mlir::Builder::getIndexAttr().
Referenced by mlir::MemRefDescriptor::bufferPtr(), mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::MemRefDescriptor::setConstantOffset(), mlir::MemRefDescriptor::setConstantSize(), mlir::MemRefDescriptor::setConstantStride(), and mlir::MemRefDescriptor::size().