MLIR: include/mlir-c/Target/ExportSMTLIB.h File Reference
ExportSMTLIB.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_CAPI_EXPORTED MlirLogicalResult mlirTranslateModuleToSMTLIB (MlirModule, MlirStringCallback, void *userData, bool inlineSingleUseValues, bool indentLetBody)
Emits SMTLIB for the specified module using the provided callback and user data.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirTranslateOperationToSMTLIB (MlirOperation, MlirStringCallback, void *userData, bool inlineSingleUseValues, bool indentLetBody)
Function Documentation
mlirTranslateModuleToSMTLIB()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirTranslateModuleToSMTLIB (MlirModule module, MlirStringCallback callback, void * userData, bool inlineSingleUseValues, bool indentLetBody)
Emits SMTLIB for the specified module using the provided callback and user data.
Definition at line 34 of file ExportSMTLIB.cpp.
References mlirModuleGetOperation(), and mlirTranslateOperationToSMTLIB().
mlirTranslateOperationToSMTLIB()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirTranslateOperationToSMTLIB (MlirOperation module, MlirStringCallback callback, void * userData, bool inlineSingleUseValues, bool indentLetBody)
Definition at line 22 of file ExportSMTLIB.cpp.
References mlir::smt::exportSMTLIB(), options, unwrap(), and wrap().
Referenced by mlirTranslateModuleToSMTLIB(), and populateDialectSMTSubmodule().