MLIR: include/mlir-c/Dialect/Complex.h File Reference
Complex.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Complex, complex)
MLIR_CAPI_EXPORTED bool mlirAttributeIsAComplex (MlirAttribute attr)
Checks whether the given attribute is a complex attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirComplexAttrDoubleGet (MlirContext ctx, MlirType type, double real, double imag)
Creates a complex attribute in the given context with the given double real and imaginary values and double-precision FP semantics.
MLIR_CAPI_EXPORTED MlirAttribute mlirComplexAttrDoubleGetChecked (MlirLocation loc, MlirType type, double real, double imag)
Same as "mlirComplexAttrDoubleGet", but if the type is not valid for a construction of a ComplexAttr, returns a null MlirAttribute.
MLIR_CAPI_EXPORTED double mlirComplexAttrGetRealDouble (MlirAttribute attr)
Returns the real value stored in the given complex attribute, interpreting the value as double.
MLIR_CAPI_EXPORTED double mlirComplexAttrGetImagDouble (MlirAttribute attr)
Returns the imaginaryvalue stored in the given complex attribute, interpreting the value as double.
MLIR_CAPI_EXPORTED MlirTypeID mlirComplexAttrGetTypeID (void)
Returns the typeID of a Complex attribute.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Complex , complex)
mlirAttributeIsAComplex()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAComplex (MlirAttribute attr)
Checks whether the given attribute is a complex attribute.
References MLIR_CAPI_EXPORTED.
mlirComplexAttrDoubleGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirComplexAttrDoubleGet (MlirContext ctx, MlirType type, double real, double imag)
Creates a complex attribute in the given context with the given double real and imaginary values and double-precision FP semantics.
Definition at line 24 of file Complex.cpp.
References mlir::imag(), mlir::real(), unwrap(), and wrap().
mlirComplexAttrDoubleGetChecked()
MLIR_CAPI_EXPORTED MlirAttribute mlirComplexAttrDoubleGetChecked (MlirLocation loc, MlirType type, double real, double imag)
Same as "mlirComplexAttrDoubleGet", but if the type is not valid for a construction of a ComplexAttr, returns a null MlirAttribute.
Definition at line 30 of file Complex.cpp.
References mlir::imag(), mlir::real(), unwrap(), and wrap().
mlirComplexAttrGetImagDouble()
MLIR_CAPI_EXPORTED double mlirComplexAttrGetImagDouble (MlirAttribute attr)
Returns the imaginaryvalue stored in the given complex attribute, interpreting the value as double.
Definition at line 40 of file Complex.cpp.
References unwrap().
mlirComplexAttrGetRealDouble()
MLIR_CAPI_EXPORTED double mlirComplexAttrGetRealDouble (MlirAttribute attr)
Returns the real value stored in the given complex attribute, interpreting the value as double.
Definition at line 36 of file Complex.cpp.
References unwrap().
mlirComplexAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirComplexAttrGetTypeID (void)
Returns the typeID of a Complex attribute.
Definition at line 44 of file Complex.cpp.
References wrap().