MLIR: lib/Tools/mlir-lsp-server/MLIRServer.cpp File Reference
MLIRServer.cpp File Reference
#include "MLIRServer.h"
#include "lsp/Logging.h"
#include "lsp/Protocol.h"
#include "mlir/IR/Operation.h"
#include "mlir/Parser.h"
#include "mlir/Parser/AsmParserState.h"
#include "llvm/Support/SourceMgr.h"
Classes
struct mlir::lsp::MLIRServer::Impl
Functions
static lsp::Position getPosFromLoc (llvm::SourceMgr &mgr, llvm::SMLoc loc)
Returns a language server position for the given source location.
static llvm::SMLoc getPosFromLoc (llvm::SourceMgr &mgr, lsp::Position pos)
Returns a source location from the given language server position.
static lsp::Range getRangeFromLoc (llvm::SourceMgr &mgr, llvm::SMRange range)
Returns a language server range for the given source range.
static lsp::Location getLocationFromLoc (llvm::SourceMgr &mgr, llvm::SMRange range, const lsp::URIForFile &uri)
Returns a language server location from the given source range.
static Optional< lsp::Location > getLocationFromLoc (FileLineColLoc loc)
Returns a language server location from the given MLIR file location.
static Optional< lsp::Location > getLocationFromLoc (llvm::SourceMgr &sourceMgr, Location loc, const lsp::URIForFile *uri=nullptr)
Returns a language server location from the given MLIR location, or None if one couldn't be created.
static void collectLocationsFromLoc (Location loc, std::vector< lsp::Location > &locations, const lsp::URIForFile &uri)
Collect all of the locations from the given MLIR location that are not contained within the given URI.
static bool contains (llvm::SMRange range, llvm::SMLoc loc)
Returns true if the given range contains the given source location.
static bool isDefOrUse (const AsmParserState::SMDefinition &def, llvm::SMLoc loc, llvm::SMRange *overlappedRange=nullptr)
Returns true if the given location is contained by the definition or one of the uses of the given SMDefinition.
static Optional< unsigned > getResultNumberFromLoc (llvm::SMLoc loc)
Given a location pointing to a result, return the result number it refers to or None if it refers to all of the results.
static Optional< StringRef > getTextFromRange (llvm::SMRange range)
Given a source location range, return the text covered by the given range.
static unsigned getBlockNumber (Block *block)
Given a block, return its position in its parent region.
static void printDefBlockName (raw_ostream &os, Block *block, llvm::SMRange loc={})
Given a block and source location, print the source name of the block to the given output stream.
static void printDefBlockName (raw_ostream &os, const AsmParserState::BlockDefinition &def)
static lsp::Diagnostic getLspDiagnoticFromDiag (llvm::SourceMgr &sourceMgr, Diagnostic &diag, const lsp::URIForFile &uri)
Convert the given MLIR diagnostic to the LSP form.
Function Documentation
collectLocationsFromLoc()
static void collectLocationsFromLoc (Location loc, std::vector< lsp::Location > & locations, const lsp::URIForFile & uri) static
Collect all of the locations from the given MLIR location that are not contained within the given URI.
Definition at line 99 of file MLIRServer.cpp.
References mlir::WalkResult::advance(), mlir::Location::dyn_cast(), getLocationFromLoc(), and mlir::LocationAttr::walk().
Referenced by getLspDiagnoticFromDiag().
contains()
static bool contains (llvm::SMRange range, llvm::SMLoc loc) static
Returns true if the given range contains the given source location.
Note that this has slightly different behavior than SMRange because it is inclusive of the end location.
Definition at line 118 of file MLIRServer.cpp.
Referenced by mlir::tblgen::SymbolInfoMap::end(), getLspDiagnoticFromDiag(), and isDefOrUse().
getBlockNumber()
static unsigned getBlockNumber (Block * block) static
Given a block, return its position in its parent region.
Definition at line 184 of file MLIRServer.cpp.
References mlir::Region::begin(), and mlir::Block::getParent().
Referenced by getLspDiagnoticFromDiag(), and printDefBlockName().
getLocationFromLoc() [1/3]
static lsp::Location getLocationFromLoc (llvm::SourceMgr & mgr, llvm::SMRange range, const lsp::URIForFile & uri) static
Returns a language server location from the given source range.
Definition at line 40 of file MLIRServer.cpp.
References getRangeFromLoc().
Referenced by collectLocationsFromLoc(), getLocationFromLoc(), and getLspDiagnoticFromDiag().
getLocationFromLoc() [2/3]
static Optional<lsp::Location> getLocationFromLoc (FileLineColLoc loc) static
Returns a language server location from the given MLIR file location.
Definition at line 47 of file MLIRServer.cpp.
References mlir::lsp::Position::character, mlir::lsp::Logger::error(), mlir::lsp::URIForFile::fromFile(), mlir::lsp::Position::line, and mlir::toString().
getLocationFromLoc() [3/3]
static Optional<lsp::Location> getLocationFromLoc (llvm::SourceMgr & sourceMgr, Location loc, const lsp::URIForFile * uri = nullptr) static
Returns a language server location from the given MLIR location, or None if one couldn't be created.
uri is an optional additional filter that, when present, is used to filter sub locations that do not share the same uri.
Definition at line 67 of file MLIRServer.cpp.
References mlir::WalkResult::advance(), mlir::AsmParserState::convertIdLocToRange(), mlir::Location::dyn_cast(), getLocationFromLoc(), mlir::WalkResult::interrupt(), max(), and mlir::LocationAttr::walk().
getLspDiagnoticFromDiag()
static lsp::Diagnostic getLspDiagnoticFromDiag (llvm::SourceMgr & sourceMgr, Diagnostic & diag, const lsp::URIForFile & uri) static
Convert the given MLIR diagnostic to the LSP form.
Definition at line 208 of file MLIRServer.cpp.
References mlir::AsmParserState::BlockDefinition::block, mlir::lsp::Diagnostic::category, mlir::lsp::DocumentSymbol::children, mlir::lsp::Class, collectLocationsFromLoc(), contains(), mlir::lsp::Hover::contents, diag(), mlir::lsp::Range::end, mlir::detail::enumerate(), mlir::lsp::Logger::error(), mlir::Error, mlir::lsp::Error, mlir::failed(), mlir::lsp::URIForFile::file(), mlir::lsp::Function, mlir::BlockArgument::getArgNumber(), mlir::Block::getArgument(), getBlockNumber(), mlir::Operation::getLoc(), mlir::Diagnostic::getLocation(), getLocationFromLoc(), mlir::Operation::getName(), mlir::Diagnostic::getNotes(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Block::getParentOp(), getPosFromLoc(), mlir::Block::getPredecessors(), getRangeFromLoc(), mlir::Operation::getRegions(), mlir::Operation::getResult(), getResultNumberFromLoc(), mlir::Operation::getResults(), mlir::Diagnostic::getSeverity(), mlir::OperationName::getStringRef(), mlir::Block::getSuccessors(), mlir::Value::getType(), mlir::ResultRange::getType(), mlir::Block::hasNoPredecessors(), mlir::Block::hasNoSuccessors(), mlir::Operation::hasTrait(), mlir::lsp::Information, isDefOrUse(), mlir::lsp::Position::line, loc, mlir::lsp::Diagnostic::message, mlir::lsp::Namespace, mlir::Note, mlir::AsmParserState::OperationDefinition::op, op, mlir::parseSourceFile(), mlir::Operation::print(), printDefBlockName(), mlir::lsp::DocumentSymbol::range, mlir::lsp::Diagnostic::range, mlir::lsp::Diagnostic::relatedInformation, mlir::Remark, mlir::lsp::DocumentSymbol::selectionRange, mlir::lsp::Diagnostic::severity, mlir::lsp::Diagnostic::source, mlir::lsp::Range::start, mlir::Diagnostic::str(), mlir::lsp::Location::uri, mlir::lsp::MarkupContent::value, mlir::Warning, and mlir::lsp::Warning.
getPosFromLoc() [1/2]
static lsp::Position getPosFromLoc (llvm::SourceMgr & mgr, llvm::SMLoc loc) static
Returns a language server position for the given source location.
Definition at line 20 of file MLIRServer.cpp.
References mlir::lsp::Position::character, and mlir::lsp::Position::line.
Referenced by getLspDiagnoticFromDiag(), and getRangeFromLoc().
getPosFromLoc() [2/2]
static llvm::SMLoc getPosFromLoc (llvm::SourceMgr & mgr, lsp::Position pos) static
Returns a source location from the given language server position.
Definition at line 29 of file MLIRServer.cpp.
References mlir::lsp::Position::character, and mlir::lsp::Position::line.
getRangeFromLoc()
static lsp::Range getRangeFromLoc (llvm::SourceMgr & mgr, llvm::SMRange range) static
Returns a language server range for the given source range.
Definition at line 35 of file MLIRServer.cpp.
References getPosFromLoc().
Referenced by getLocationFromLoc(), and getLspDiagnoticFromDiag().
getResultNumberFromLoc()
static Optional<unsigned> getResultNumberFromLoc (llvm::SMLoc loc) static
Given a location pointing to a result, return the result number it refers to or None if it refers to all of the results.
Definition at line 149 of file MLIRServer.cpp.
Referenced by getLspDiagnoticFromDiag().
getTextFromRange()
static Optional<StringRef> getTextFromRange (llvm::SMRange range) static
Given a source location range, return the text covered by the given range.
If the range is invalid, returns None.
Definition at line 176 of file MLIRServer.cpp.
References None.
Referenced by printDefBlockName().
isDefOrUse()
static bool isDefOrUse (const AsmParserState::SMDefinition & def, llvm::SMLoc loc, llvm::SMRange * overlappedRange = nullptr) static
Returns true if the given location is contained by the definition or one of the uses of the given SMDefinition.
If provided, overlappedRange is set to the range within def that the provided loc overlapped with.
Definition at line 126 of file MLIRServer.cpp.
References contains(), mlir::AsmParserState::SMDefinition::loc, and mlir::AsmParserState::SMDefinition::uses.
Referenced by getLspDiagnoticFromDiag().
printDefBlockName() [1/2]
static void printDefBlockName (raw_ostream & os, Block * block, llvm::SMRange loc = {}) static
Given a block and source location, print the source name of the block to the given output stream.
Definition at line 190 of file MLIRServer.cpp.
References getBlockNumber(), getTextFromRange(), and loc.
Referenced by getLspDiagnoticFromDiag(), and printDefBlockName().
printDefBlockName() [2/2]
static void printDefBlockName (raw_ostream & os, const AsmParserState::BlockDefinition & def) static
Definition at line 202 of file MLIRServer.cpp.
References mlir::AsmParserState::BlockDefinition::block, mlir::AsmParserState::BlockDefinition::definition, mlir::AsmParserState::SMDefinition::loc, and printDefBlockName().