MLIR: include/mlir-c/BuiltinTypes.h File Reference
BuiltinTypes.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include <stdint.h>
Functions
MLIR_CAPI_EXPORTED MlirTypeID mlirIntegerTypeGetTypeID (void)
Returns the typeID of an Integer type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
MLIR_CAPI_EXPORTED unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
MLIR_CAPI_EXPORTED MlirTypeID mlirIndexTypeGetTypeID (void)
Returns the typeID of an Index type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
MLIR_CAPI_EXPORTED MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat (MlirType type)
Checks whether the given type is a floating-point type.
MLIR_CAPI_EXPORTED unsigned mlirFloatTypeGetWidth (MlirType type)
Returns the bitwidth of a floating-point type.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat4E2M1FNTypeGetTypeID (void)
Returns the typeID of an Float4E2M1FN type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat4E2M1FN (MlirType type)
Checks whether the given type is an f4E2M1FN type.
MLIR_CAPI_EXPORTED MlirType mlirFloat4E2M1FNTypeGet (MlirContext ctx)
Creates an f4E2M1FN type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat6E2M3FNTypeGetTypeID (void)
Returns the typeID of an Float6E2M3FN type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat6E2M3FN (MlirType type)
Checks whether the given type is an f6E2M3FN type.
MLIR_CAPI_EXPORTED MlirType mlirFloat6E2M3FNTypeGet (MlirContext ctx)
Creates an f6E2M3FN type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat6E3M2FNTypeGetTypeID (void)
Returns the typeID of an Float6E3M2FN type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat6E3M2FN (MlirType type)
Checks whether the given type is an f6E3M2FN type.
MLIR_CAPI_EXPORTED MlirType mlirFloat6E3M2FNTypeGet (MlirContext ctx)
Creates an f6E3M2FN type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E5M2TypeGetTypeID (void)
Returns the typeID of an Float8E5M2 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E5M2 (MlirType type)
Checks whether the given type is an f8E5M2 type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E5M2TypeGet (MlirContext ctx)
Creates an f8E5M2 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3TypeGetTypeID (void)
Returns the typeID of an Float8E4M3 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3 (MlirType type)
Checks whether the given type is an f8E4M3 type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3TypeGet (MlirContext ctx)
Creates an f8E4M3 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3FNTypeGetTypeID (void)
Returns the typeID of an Float8E4M3FN type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3FN (MlirType type)
Checks whether the given type is an f8E4M3FN type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3FNTypeGet (MlirContext ctx)
Creates an f8E4M3FN type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E5M2FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E5M2FNUZ type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E5M2FNUZ (MlirType type)
Checks whether the given type is an f8E5M2FNUZ type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E5M2FNUZTypeGet (MlirContext ctx)
Creates an f8E5M2FNUZ type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E4M3FNUZ type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3FNUZ (MlirType type)
Checks whether the given type is an f8E4M3FNUZ type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3FNUZ type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3B11FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E4M3B11FNUZ type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3B11FNUZ (MlirType type)
Checks whether the given type is an f8E4M3B11FNUZ type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3B11FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3B11FNUZ type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E3M4TypeGetTypeID (void)
Returns the typeID of an Float8E3M4 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E3M4 (MlirType type)
Checks whether the given type is an f8E3M4 type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E3M4TypeGet (MlirContext ctx)
Creates an f8E3M4 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E8M0FNUTypeGetTypeID (void)
Returns the typeID of an Float8E8M0FNU type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E8M0FNU (MlirType type)
Checks whether the given type is an f8E8M0FNU type.
MLIR_CAPI_EXPORTED MlirType mlirFloat8E8M0FNUTypeGet (MlirContext ctx)
Creates an f8E8M0FNU type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirBFloat16TypeGetTypeID (void)
Returns the typeID of an BFloat16 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
MLIR_CAPI_EXPORTED MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat16TypeGetTypeID (void)
Returns the typeID of an Float16 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
MLIR_CAPI_EXPORTED MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat32TypeGetTypeID (void)
Returns the typeID of an Float32 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
MLIR_CAPI_EXPORTED MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat64TypeGetTypeID (void)
Returns the typeID of an Float64 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
MLIR_CAPI_EXPORTED MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloatTF32TypeGetTypeID (void)
Returns the typeID of a TF32 type.
MLIR_CAPI_EXPORTED bool mlirTypeIsATF32 (MlirType type)
Checks whether the given type is an TF32 type.
MLIR_CAPI_EXPORTED MlirType mlirTF32TypeGet (MlirContext ctx)
Creates a TF32 type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirNoneTypeGetTypeID (void)
Returns the typeID of an None type.
MLIR_CAPI_EXPORTED bool mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
MLIR_CAPI_EXPORTED MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirComplexTypeGetTypeID (void)
Returns the typeID of an Complex type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
MLIR_CAPI_EXPORTED MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is dynamic.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsStaticDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is static.
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsStaticSize (int64_t size)
Checks whether the given shaped type dimension value is statically-sized.
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDynamicSize (void)
Returns the value indicating a dynamic size in a shaped type.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsStaticStrideOrOffset (int64_t val)
Checks whether the given dimension value of a stride or an offset is statically-sized.
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDynamicStrideOrOffset (void)
Returns the value indicating a dynamic stride or offset in a shaped type.
MLIR_CAPI_EXPORTED MlirTypeID mlirVectorTypeGetTypeID (void)
Returns the typeID of an Vector type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGet (intptr_t rank, const int64_t *shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, MlirType elementType)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetScalable (intptr_t rank, const int64_t *shape, const bool *scalable, MlirType elementType)
Creates a scalable vector type with the shape identified by its rank and dimensions.
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetScalableChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, const bool *scalable, MlirType elementType)
Same as "mlirVectorTypeGetScalable" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED bool mlirVectorTypeIsScalable (MlirType type)
Checks whether the given vector type is scalable, i.e., has at least one scalable dimension.
MLIR_CAPI_EXPORTED bool mlirVectorTypeIsDimScalable (MlirType type, intptr_t dim)
Checks whether the "dim"-th dimension of the given vector is scalable.
MLIR_CAPI_EXPORTED bool mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
MLIR_CAPI_EXPORTED MlirTypeID mlirRankedTensorTypeGetTypeID (void)
Returns the typeID of an RankedTensor type.
MLIR_CAPI_EXPORTED bool mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
MLIR_CAPI_EXPORTED MlirTypeID mlirUnrankedTensorTypeGetTypeID (void)
Returns the typeID of an UnrankedTensor type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGet (intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute encoding)
Creates a tensor type of a fixed rank with the given shape, element type, and optional encoding in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t *shape, MlirType elementType, MlirAttribute encoding)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirAttribute mlirRankedTensorTypeGetEncoding (MlirType type)
Gets the 'encoding' attribute from the ranked tensor type, returning a null attribute if none.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGetChecked (MlirLocation loc, MlirType elementType)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirTypeID mlirMemRefTypeGetTypeID (void)
Returns the typeID of an MemRef type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
MLIR_CAPI_EXPORTED MlirTypeID mlirUnrankedMemRefTypeGetTypeID (void)
Returns the typeID of an UnrankedMemRef type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute layout, MlirAttribute memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute layout, MlirAttribute memorySpace)
Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t *shape, MlirAttribute memorySpace)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, MlirAttribute memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, MlirAttribute memorySpace)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MLIR_CAPI_EXPORTED MlirAttribute mlirMemRefTypeGetLayout (MlirType type)
Returns the layout of the given MemRef type.
MLIR_CAPI_EXPORTED MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type)
Returns the affine map of the given MemRef type.
MLIR_CAPI_EXPORTED MlirAttribute mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirMemRefTypeGetStridesAndOffset (MlirType type, int64_t *strides, int64_t *offset)
Returns the strides of the MemRef if the layout map is in strided form.
MLIR_CAPI_EXPORTED MlirAttribute mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
MLIR_CAPI_EXPORTED MlirTypeID mlirTupleTypeGetTypeID (void)
Returns the typeID of an Tuple type.
MLIR_CAPI_EXPORTED bool mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType const *elements)
Creates a tuple type that consists of the given list of elemental types.
MLIR_CAPI_EXPORTED intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
MLIR_CAPI_EXPORTED MlirTypeID mlirFunctionTypeGetTypeID (void)
Returns the typeID of an Function type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType const *inputs, intptr_t numResults, MlirType const *results)
Creates a function type, mapping a list of input types to result types.
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
MLIR_CAPI_EXPORTED MlirTypeID mlirOpaqueTypeGetTypeID (void)
Returns the typeID of an Opaque type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAOpaque (MlirType type)
Checks whether the given type is an opaque type.
MLIR_CAPI_EXPORTED MlirType mlirOpaqueTypeGet (MlirContext ctx, MlirStringRef dialectNamespace, MlirStringRef typeData)
Creates an opaque type in the given context associated with the dialect identified by its namespace.
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueTypeGetDialectNamespace (MlirType type)
Returns the namespace of the dialect with which the given opaque type is associated.
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueTypeGetData (MlirType type)
Returns the raw data as a string reference.
Function Documentation
mlirBF16TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
The type is owned by the context.
Definition at line 228 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirBFloat16TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirBFloat16TypeGetTypeID (void)
Returns the typeID of an BFloat16 type.
Definition at line 220 of file BuiltinTypes.cpp.
References wrap().
mlirComplexTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 298 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirComplexTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
Definition at line 302 of file BuiltinTypes.cpp.
References getElementType(), unwrap(), and wrap().
mlirComplexTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirComplexTypeGetTypeID (void)
Returns the typeID of an Complex type.
Definition at line 292 of file BuiltinTypes.cpp.
References wrap().
mlirF16TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
The type is owned by the context.
Definition at line 238 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirF32TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
The type is owned by the context.
Definition at line 260 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirF64TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
The type is owned by the context.
Definition at line 270 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat16TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat16TypeGetTypeID (void)
Returns the typeID of an Float16 type.
Definition at line 232 of file BuiltinTypes.cpp.
References wrap().
mlirFloat32TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat32TypeGetTypeID (void)
Returns the typeID of an Float32 type.
Definition at line 254 of file BuiltinTypes.cpp.
References wrap().
mlirFloat4E2M1FNTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat4E2M1FNTypeGet (MlirContext ctx)
Creates an f4E2M1FN type in the given context.
The type is owned by the context.
Definition at line 96 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat4E2M1FNTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat4E2M1FNTypeGetTypeID (void)
Returns the typeID of an Float4E2M1FN type.
Definition at line 88 of file BuiltinTypes.cpp.
References wrap().
mlirFloat64TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat64TypeGetTypeID (void)
Returns the typeID of an Float64 type.
Definition at line 264 of file BuiltinTypes.cpp.
References wrap().
mlirFloat6E2M3FNTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat6E2M3FNTypeGet (MlirContext ctx)
Creates an f6E2M3FN type in the given context.
The type is owned by the context.
Definition at line 108 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat6E2M3FNTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat6E2M3FNTypeGetTypeID (void)
Returns the typeID of an Float6E2M3FN type.
Definition at line 100 of file BuiltinTypes.cpp.
References wrap().
mlirFloat6E3M2FNTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat6E3M2FNTypeGet (MlirContext ctx)
Creates an f6E3M2FN type in the given context.
The type is owned by the context.
Definition at line 120 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat6E3M2FNTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat6E3M2FNTypeGetTypeID (void)
Returns the typeID of an Float6E3M2FN type.
Definition at line 112 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E3M4TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E3M4TypeGet (MlirContext ctx)
Creates an f8E3M4 type in the given context.
The type is owned by the context.
Definition at line 204 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E3M4TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E3M4TypeGetTypeID (void)
Returns the typeID of an Float8E3M4 type.
Definition at line 196 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3B11FNUZTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3B11FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3B11FNUZ type in the given context.
The type is owned by the context.
Definition at line 192 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3B11FNUZTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3B11FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E4M3B11FNUZ type.
Definition at line 184 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3FNTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3FNTypeGet (MlirContext ctx)
Creates an f8E4M3FN type in the given context.
The type is owned by the context.
Definition at line 156 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3FNTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3FNTypeGetTypeID (void)
Returns the typeID of an Float8E4M3FN type.
Definition at line 148 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3FNUZTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3FNUZTypeGet (MlirContext ctx)
Creates an f8E4M3FNUZ type in the given context.
The type is owned by the context.
Definition at line 180 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3FNUZTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E4M3FNUZ type.
Definition at line 172 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E4M3TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E4M3TypeGet (MlirContext ctx)
Creates an f8E4M3 type in the given context.
The type is owned by the context.
Definition at line 144 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E4M3TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E4M3TypeGetTypeID (void)
Returns the typeID of an Float8E4M3 type.
Definition at line 136 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E5M2FNUZTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E5M2FNUZTypeGet (MlirContext ctx)
Creates an f8E5M2FNUZ type in the given context.
The type is owned by the context.
Definition at line 168 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E5M2FNUZTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E5M2FNUZTypeGetTypeID (void)
Returns the typeID of an Float8E5M2FNUZ type.
Definition at line 160 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E5M2TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E5M2TypeGet (MlirContext ctx)
Creates an f8E5M2 type in the given context.
The type is owned by the context.
Definition at line 132 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E5M2TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E5M2TypeGetTypeID (void)
Returns the typeID of an Float8E5M2 type.
Definition at line 124 of file BuiltinTypes.cpp.
References wrap().
mlirFloat8E8M0FNUTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFloat8E8M0FNUTypeGet (MlirContext ctx)
Creates an f8E8M0FNU type in the given context.
The type is owned by the context.
Definition at line 216 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFloat8E8M0FNUTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloat8E8M0FNUTypeGetTypeID (void)
Returns the typeID of an Float8E8M0FNU type.
Definition at line 208 of file BuiltinTypes.cpp.
References wrap().
mlirFloatTF32TypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloatTF32TypeGetTypeID (void)
Returns the typeID of a TF32 type.
Definition at line 242 of file BuiltinTypes.cpp.
References wrap().
mlirFloatTypeGetWidth()
MLIR_CAPI_EXPORTED unsigned mlirFloatTypeGetWidth (MlirType type)
Returns the bitwidth of a floating-point type.
Definition at line 84 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType const * inputs, intptr_t numResults, MlirType const * results)
Creates a function type, mapping a list of input types to result types.
Definition at line 606 of file BuiltinTypes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirFunctionTypeGetInput()
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
Definition at line 624 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFunctionTypeGetNumInputs()
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
Definition at line 616 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGetNumResults()
MLIR_CAPI_EXPORTED intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
Definition at line 620 of file BuiltinTypes.cpp.
References unwrap().
mlirFunctionTypeGetResult()
MLIR_CAPI_EXPORTED MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
Definition at line 630 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirFunctionTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFunctionTypeGetTypeID (void)
Returns the typeID of an Function type.
Definition at line 598 of file BuiltinTypes.cpp.
References wrap().
mlirIndexTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
The type is owned by the context.
Definition at line 72 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIndexTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirIndexTypeGetTypeID (void)
Returns the typeID of an Index type.
Definition at line 66 of file BuiltinTypes.cpp.
References wrap().
mlirIntegerTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 34 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIntegerTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirIntegerTypeGetTypeID (void)
Returns the typeID of an Integer type.
Definition at line 28 of file BuiltinTypes.cpp.
References wrap().
mlirIntegerTypeGetWidth()
MLIR_CAPI_EXPORTED unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
Definition at line 46 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsSigned()
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
Definition at line 54 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsSignless()
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
Definition at line 50 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeIsUnsigned()
MLIR_CAPI_EXPORTED bool mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
Definition at line 58 of file BuiltinTypes.cpp.
References unwrap().
mlirIntegerTypeSignedGet()
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 38 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirIntegerTypeUnsignedGet()
MLIR_CAPI_EXPORTED MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 42 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeContiguousGet()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
The type has no affine maps, i.e. represents a default row-major contiguous memref. The type is owned by the context.
Definition at line 502 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeContiguousGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeContiguousGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute memorySpace)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 510 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute layout, MlirAttribute memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
The type is owned by the context.
Definition at line 478 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetAffineMap()
MLIR_CAPI_EXPORTED MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type)
Returns the affine map of the given MemRef type.
Definition at line 523 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, intptr_t rank, const int64_t * shape, MlirAttribute layout, MlirAttribute memorySpace)
Same as "mlirMemRefTypeGet" but returns a nullptr-wrapping MlirType o illegal arguments, emitting appropriate diagnostics.
Definition at line 489 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetLayout()
MLIR_CAPI_EXPORTED MlirAttribute mlirMemRefTypeGetLayout (MlirType type)
Returns the layout of the given MemRef type.
Definition at line 519 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetMemorySpace()
MLIR_CAPI_EXPORTED MlirAttribute mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
Definition at line 527 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirMemRefTypeGetStridesAndOffset()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirMemRefTypeGetStridesAndOffset (MlirType type, int64_t * strides, int64_t * offset)
Returns the strides of the MemRef if the layout map is in strided form.
Both strides and offset are out params. strides must point to pre-allocated memory of length equal to the rank of the memref.
Definition at line 531 of file BuiltinTypes.cpp.
References mlirLogicalResultFailure(), mlirLogicalResultSuccess(), and unwrap().
mlirMemRefTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirMemRefTypeGetTypeID (void)
Returns the typeID of an MemRef type.
Definition at line 472 of file BuiltinTypes.cpp.
References wrap().
mlirNoneTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
The type is owned by the context.
Definition at line 284 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirNoneTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirNoneTypeGetTypeID (void)
Returns the typeID of an None type.
Definition at line 278 of file BuiltinTypes.cpp.
References wrap().
mlirOpaqueTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirOpaqueTypeGet (MlirContext ctx, MlirStringRef dialectNamespace, MlirStringRef typeData)
Creates an opaque type in the given context associated with the dialect identified by its namespace.
The type contains opaque byte data of the specified length (data need not be null-terminated).
Definition at line 646 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirOpaqueTypeGetData()
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueTypeGetData (MlirType type)
Returns the raw data as a string reference.
The data remains live as long as the context in which the type lives.
Definition at line 658 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirOpaqueTypeGetDialectNamespace()
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueTypeGetDialectNamespace (MlirType type)
Returns the namespace of the dialect with which the given opaque type is associated.
The namespace string is owned by the context.
Definition at line 653 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirOpaqueTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirOpaqueTypeGetTypeID (void)
Returns the typeID of an Opaque type.
Definition at line 640 of file BuiltinTypes.cpp.
References wrap().
mlirRankedTensorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGet (intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute encoding)
Creates a tensor type of a fixed rank with the given shape, element type, and optional encoding in the same context as the element type.
The type is owned by the context. Tensor types without any specific encoding field should assign mlirAttributeGetNull() to this parameter.
Definition at line 439 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirRankedTensorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, MlirType elementType, MlirAttribute encoding)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 446 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetEncoding()
MLIR_CAPI_EXPORTED MlirAttribute mlirRankedTensorTypeGetEncoding (MlirType type)
Gets the 'encoding' attribute from the ranked tensor type, returning a null attribute if none.
Definition at line 455 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirRankedTensorTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirRankedTensorTypeGetTypeID (void)
Returns the typeID of an RankedTensor type.
Definition at line 423 of file BuiltinTypes.cpp.
References wrap().
mlirShapedTypeGetDimSize()
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
Definition at line 340 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetDynamicSize()
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDynamicSize (void)
Returns the value indicating a dynamic size in a shaped type.
Prefer mlirShapedTypeIsDynamicSize and mlirShapedTypeIsStaticSize to direct comparisons with this value.
Definition at line 345 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetDynamicStrideOrOffset()
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetDynamicStrideOrOffset (void)
Returns the value indicating a dynamic stride or offset in a shaped type.
Prefer mlirShapedTypeIsDynamicStrideOrOffset and mlirShapedTypeIsStaticStrideOrOffset to direct comparisons with this value.
Definition at line 363 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
Definition at line 314 of file BuiltinTypes.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeGetRank()
MLIR_CAPI_EXPORTED int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
Definition at line 322 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeHasRank()
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
Definition at line 318 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeHasStaticShape()
MLIR_CAPI_EXPORTED bool mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
Definition at line 326 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsDynamicDim()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is dynamic.
Definition at line 330 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsDynamicSize()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
Definition at line 347 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsDynamicStrideOrOffset()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
Definition at line 355 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsStaticDim()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsStaticDim (MlirType type, intptr_t dim)
Checks whether the dim-th dimension of the given shaped type is static.
Definition at line 335 of file BuiltinTypes.cpp.
References unwrap().
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsStaticSize()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsStaticSize (int64_t size)
Checks whether the given shaped type dimension value is statically-sized.
Definition at line 351 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirShapedTypeIsStaticStrideOrOffset()
MLIR_CAPI_EXPORTED bool mlirShapedTypeIsStaticStrideOrOffset (int64_t val)
Checks whether the given dimension value of a stride or an offset is statically-sized.
Definition at line 359 of file BuiltinTypes.cpp.
Referenced by mlir::PyShapedType::bindDerived().
mlirTF32TypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTF32TypeGet (MlirContext ctx)
Creates a TF32 type in the given context.
The type is owned by the context.
Definition at line 250 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirTupleTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType const * elements)
Creates a tuple type that consists of the given list of elemental types.
The type is owned by the context.
Definition at line 578 of file BuiltinTypes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirTupleTypeGetNumTypes()
MLIR_CAPI_EXPORTED intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
Definition at line 585 of file BuiltinTypes.cpp.
References unwrap().
mlirTupleTypeGetType()
MLIR_CAPI_EXPORTED MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
Definition at line 589 of file BuiltinTypes.cpp.
References mlir::getType(), unwrap(), and wrap().
mlirTupleTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTupleTypeGetTypeID (void)
Returns the typeID of an Tuple type.
Definition at line 572 of file BuiltinTypes.cpp.
References wrap().
mlirTypeIsABF16()
MLIR_CAPI_EXPORTED bool mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
Definition at line 224 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAComplex()
MLIR_CAPI_EXPORTED bool mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
Definition at line 294 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF16()
MLIR_CAPI_EXPORTED bool mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
Definition at line 234 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF32()
MLIR_CAPI_EXPORTED bool mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
Definition at line 256 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAF64()
MLIR_CAPI_EXPORTED bool mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
Definition at line 266 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat (MlirType type)
Checks whether the given type is a floating-point type.
Definition at line 80 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat4E2M1FN()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat4E2M1FN (MlirType type)
Checks whether the given type is an f4E2M1FN type.
Definition at line 92 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat6E2M3FN()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat6E2M3FN (MlirType type)
Checks whether the given type is an f6E2M3FN type.
Definition at line 104 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat6E3M2FN()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat6E3M2FN (MlirType type)
Checks whether the given type is an f6E3M2FN type.
Definition at line 116 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E3M4()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E3M4 (MlirType type)
Checks whether the given type is an f8E3M4 type.
Definition at line 200 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3 (MlirType type)
Checks whether the given type is an f8E4M3 type.
Definition at line 140 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3B11FNUZ()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3B11FNUZ (MlirType type)
Checks whether the given type is an f8E4M3B11FNUZ type.
Definition at line 188 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3FN()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3FN (MlirType type)
Checks whether the given type is an f8E4M3FN type.
Definition at line 152 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E4M3FNUZ()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E4M3FNUZ (MlirType type)
Checks whether the given type is an f8E4M3FNUZ type.
Definition at line 176 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E5M2()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E5M2 (MlirType type)
Checks whether the given type is an f8E5M2 type.
Definition at line 128 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E5M2FNUZ()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E5M2FNUZ (MlirType type)
Checks whether the given type is an f8E5M2FNUZ type.
Definition at line 164 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFloat8E8M0FNU()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFloat8E8M0FNU (MlirType type)
Checks whether the given type is an f8E8M0FNU type.
Definition at line 212 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAFunction()
MLIR_CAPI_EXPORTED bool mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
Definition at line 602 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAIndex()
MLIR_CAPI_EXPORTED bool mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
Definition at line 68 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAInteger()
MLIR_CAPI_EXPORTED bool mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
Definition at line 30 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAMemRef()
MLIR_CAPI_EXPORTED bool mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
Definition at line 474 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsANone()
MLIR_CAPI_EXPORTED bool mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
Definition at line 280 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAOpaque()
MLIR_CAPI_EXPORTED bool mlirTypeIsAOpaque (MlirType type)
Checks whether the given type is an opaque type.
Definition at line 642 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsARankedTensor()
MLIR_CAPI_EXPORTED bool mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
Definition at line 427 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAShaped()
MLIR_CAPI_EXPORTED bool mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
Definition at line 310 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATensor()
MLIR_CAPI_EXPORTED bool mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
Definition at line 419 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATF32()
MLIR_CAPI_EXPORTED bool mlirTypeIsATF32 (MlirType type)
Checks whether the given type is an TF32 type.
Definition at line 246 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsATuple()
MLIR_CAPI_EXPORTED bool mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
Definition at line 574 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAUnrankedMemRef()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
Definition at line 547 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAUnrankedTensor()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
Definition at line 435 of file BuiltinTypes.cpp.
References unwrap().
mlirTypeIsAVector()
MLIR_CAPI_EXPORTED bool mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
Definition at line 373 of file BuiltinTypes.cpp.
References unwrap().
mlirUnrankedMemrefGetMemorySpace()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
Definition at line 564 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, MlirAttribute memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
The type is owned by the context of element type.
Definition at line 551 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedMemRefTypeGetChecked (MlirLocation loc, MlirType elementType, MlirAttribute memorySpace)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 557 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedMemRefTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirUnrankedMemRefTypeGetTypeID (void)
Returns the typeID of an UnrankedMemRef type.
Definition at line 543 of file BuiltinTypes.cpp.
References wrap().
mlirUnrankedTensorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 459 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedTensorTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirUnrankedTensorTypeGetChecked (MlirLocation loc, MlirType elementType)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 463 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirUnrankedTensorTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirUnrankedTensorTypeGetTypeID (void)
Returns the typeID of an UnrankedTensor type.
Definition at line 431 of file BuiltinTypes.cpp.
References wrap().
mlirVectorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGet (intptr_t rank, const int64_t * shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 377 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, MlirType elementType)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 383 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetScalable()
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetScalable (intptr_t rank, const int64_t * shape, const bool * scalable, MlirType elementType)
Creates a scalable vector type with the shape identified by its rank and dimensions.
A subset of dimensions may be marked as scalable via the corresponding flag list, which is expected to have as many entries as the rank of the vector. The vector is created in the same context as the element type.
Definition at line 390 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetScalableChecked()
MLIR_CAPI_EXPORTED MlirType mlirVectorTypeGetScalableChecked (MlirLocation loc, intptr_t rank, const int64_t * shape, const bool * scalable, MlirType elementType)
Same as "mlirVectorTypeGetScalable" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 397 of file BuiltinTypes.cpp.
References unwrap(), and wrap().
mlirVectorTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirVectorTypeGetTypeID (void)
Returns the typeID of an Vector type.
Definition at line 371 of file BuiltinTypes.cpp.
References wrap().
mlirVectorTypeIsDimScalable()
MLIR_CAPI_EXPORTED bool mlirVectorTypeIsDimScalable (MlirType type, intptr_t dim)
Checks whether the "dim"-th dimension of the given vector is scalable.
Definition at line 411 of file BuiltinTypes.cpp.
References unwrap().
mlirVectorTypeIsScalable()
MLIR_CAPI_EXPORTED bool mlirVectorTypeIsScalable (MlirType type)
Checks whether the given vector type is scalable, i.e., has at least one scalable dimension.
Definition at line 407 of file BuiltinTypes.cpp.
References unwrap().