MLIR: include/mlir-c/ExecutionEngine.h File Reference
ExecutionEngine.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Functions
DEFINE_C_API_STRUCT (MlirExecutionEngine, void)
MLIR_CAPI_EXPORTED MlirExecutionEngine mlirExecutionEngineCreate (MlirModule op, int optLevel, int numPaths, const MlirStringRef *sharedLibPaths, bool enableObjectDump, bool enablePIC)
Creates an ExecutionEngine for the provided ModuleOp.
MLIR_CAPI_EXPORTED void mlirExecutionEngineInitialize (MlirExecutionEngine jit)
Initialize the ExecutionEngine.
MLIR_CAPI_EXPORTED void mlirExecutionEngineDestroy (MlirExecutionEngine jit)
Destroy an ExecutionEngine instance.
static bool mlirExecutionEngineIsNull (MlirExecutionEngine jit)
Checks whether an execution engine is null.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExecutionEngineInvokePacked (MlirExecutionEngine jit, MlirStringRef name, void **arguments)
Invoke a native function in the execution engine by name with the arguments and result of the invoked function passed as an array of pointers.
MLIR_CAPI_EXPORTED void * mlirExecutionEngineLookupPacked (MlirExecutionEngine jit, MlirStringRef name)
Lookup the wrapper of the native function in the execution engine with the given name, returns nullptr if the function can't be looked-up.
MLIR_CAPI_EXPORTED void * mlirExecutionEngineLookup (MlirExecutionEngine jit, MlirStringRef name)
Lookup a native function in the execution engine by name, returns nullptr if the name can't be looked-up.
MLIR_CAPI_EXPORTED void mlirExecutionEngineRegisterSymbol (MlirExecutionEngine jit, MlirStringRef name, void *sym)
Register a symbol with the jit: this symbol will be accessible to the jitted code.
MLIR_CAPI_EXPORTED void mlirExecutionEngineDumpToObjectFile (MlirExecutionEngine jit, MlirStringRef fileName)
Dump as an object in fileName.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
  struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Definition at line 25 of file ExecutionEngine.h.
Function Documentation
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (MlirExecutionEngine , void)
References MLIR_CAPI_EXPORTED.
mlirExecutionEngineCreate()
MLIR_CAPI_EXPORTED MlirExecutionEngine mlirExecutionEngineCreate (MlirModule op, int optLevel, int numPaths, const MlirStringRef * sharedLibPaths, bool enableObjectDump, bool enablePIC)
Creates an ExecutionEngine for the provided ModuleOp.
The ModuleOp is expected to be "translatable" to LLVM IR (only contains operations in dialects that implement the LLVMTranslationDialectInterface). The module ownership stays with the client and can be destroyed as soon as the call returns. optLevel is the optimization level to be used for transformation and code generation. LLVM passes at optLevel are run before code generation. The number and array of paths corresponding to shared libraries that will be loaded are specified via numPaths and sharedLibPaths respectively. The enablePIC arguments controls the relocation model, when true the generated code is emitted as "position independent", making it possible to save it and reload it as a shared object in another process. TODO: figure out other options.
Definition at line 23 of file ExecutionEngine.cpp.
References mlir::ExecutionEngine::create(), MlirStringRef::data, mlir::ExecutionEngineOptions::enableObjectDump, mlir::ExecutionEngineOptions::jitCodeGenOptLevel, mlir::makeOptimizingTransformer(), mlir::registerBuiltinDialectTranslation(), mlir::registerLLVMDialectTranslation(), mlir::registerOpenMPDialectTranslation(), mlir::ExecutionEngineOptions::sharedLibPaths, mlir::ExecutionEngineOptions::transformer, unwrap(), and wrap().
Referenced by NB_MODULE().
mlirExecutionEngineDestroy()
MLIR_CAPI_EXPORTED void mlirExecutionEngineDestroy (MlirExecutionEngine jit)
Destroy an ExecutionEngine instance.
Definition at line 82 of file ExecutionEngine.cpp.
References unwrap().
mlirExecutionEngineDumpToObjectFile()
MLIR_CAPI_EXPORTED void mlirExecutionEngineDumpToObjectFile (MlirExecutionEngine jit, MlirStringRef fileName)
Dump as an object in fileName.
Definition at line 126 of file ExecutionEngine.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirExecutionEngineInitialize()
MLIR_CAPI_EXPORTED void mlirExecutionEngineInitialize (MlirExecutionEngine jit)
Initialize the ExecutionEngine.
Global constructors specified by llvm.mlir.global_ctors will be run. One common scenario is that kernel binary compiled from gpu.module gets loaded during initialization. Make sure all symbols are resolvable before initialization by calling mlirExecutionEngineRegisterSymbol or including shared libraries.
Definition at line 78 of file ExecutionEngine.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirExecutionEngineInvokePacked()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExecutionEngineInvokePacked (MlirExecutionEngine jit, MlirStringRef name, void ** arguments)
Invoke a native function in the execution engine by name with the arguments and result of the invoked function passed as an array of pointers.
The function must have been tagged with the llvm.emit_c_interface attribute. Returns a failure if the execution fails for any reason (the function name can't be resolved for instance).
Definition at line 87 of file ExecutionEngine.cpp.
References success(), unwrap(), and wrap().
mlirExecutionEngineIsNull()
bool mlirExecutionEngineIsNull (MlirExecutionEngine jit) inline static
Checks whether an execution engine is null.
Definition at line 63 of file ExecutionEngine.h.
Referenced by NB_MODULE().
mlirExecutionEngineLookup()
MLIR_CAPI_EXPORTED void * mlirExecutionEngineLookup (MlirExecutionEngine jit, MlirStringRef name)
Lookup a native function in the execution engine by name, returns nullptr if the name can't be looked-up.
Definition at line 106 of file ExecutionEngine.cpp.
References unwrap().
mlirExecutionEngineLookupPacked()
MLIR_CAPI_EXPORTED void * mlirExecutionEngineLookupPacked (MlirExecutionEngine jit, MlirStringRef name)
Lookup the wrapper of the native function in the execution engine with the given name, returns nullptr if the function can't be looked-up.
Definition at line 97 of file ExecutionEngine.cpp.
References unwrap().
Referenced by NB_MODULE().
mlirExecutionEngineRegisterSymbol()
MLIR_CAPI_EXPORTED void mlirExecutionEngineRegisterSymbol (MlirExecutionEngine jit, MlirStringRef name, void * sym)
Register a symbol with the jit: this symbol will be accessible to the jitted code.
Definition at line 115 of file ExecutionEngine.cpp.
References unwrap().
Referenced by NB_MODULE().