MLIR: include/mlir-c/Dialect/PDL.h File Reference
PDL.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (PDL, pdl)
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLType (MlirType type)
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLAttributeType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLAttributeTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirPDLAttributeTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLAttributeTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLOperationType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLOperationTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirPDLOperationTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLOperationTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLRangeType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLRangeTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirPDLRangeTypeGet (MlirType elementType)
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLRangeTypeGetName (void)
MLIR_CAPI_EXPORTED MlirType mlirPDLRangeTypeGetElementType (MlirType type)
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLTypeType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLTypeTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirPDLTypeTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLTypeTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLValueType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLValueTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirPDLValueTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLValueTypeGetName (void)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (PDL , pdl)
References MLIR_CAPI_EXPORTED.
mlirPDLAttributeTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirPDLAttributeTypeGet (MlirContext ctx)
Definition at line 39 of file PDL.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::AttributeType::bindDerived().
mlirPDLAttributeTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLAttributeTypeGetName (void)
Definition at line 43 of file PDL.cpp.
References wrap().
mlirPDLAttributeTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLAttributeTypeGetTypeID (void)
Definition at line 35 of file PDL.cpp.
References wrap().
mlirPDLOperationTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirPDLOperationTypeGet (MlirContext ctx)
Definition at line 59 of file PDL.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::OperationType::bindDerived().
mlirPDLOperationTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLOperationTypeGetName (void)
Definition at line 63 of file PDL.cpp.
References wrap().
mlirPDLOperationTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLOperationTypeGetTypeID (void)
Definition at line 55 of file PDL.cpp.
References wrap().
mlirPDLRangeTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirPDLRangeTypeGet (MlirType elementType)
Definition at line 79 of file PDL.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::bindDerived().
mlirPDLRangeTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirPDLRangeTypeGetElementType (MlirType type)
Definition at line 87 of file PDL.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::bindDerived().
mlirPDLRangeTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLRangeTypeGetName (void)
Definition at line 83 of file PDL.cpp.
References wrap().
mlirPDLRangeTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLRangeTypeGetTypeID (void)
Definition at line 75 of file PDL.cpp.
References wrap().
mlirPDLTypeTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirPDLTypeTypeGet (MlirContext ctx)
Definition at line 103 of file PDL.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::TypeType::bindDerived().
mlirPDLTypeTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLTypeTypeGetName (void)
Definition at line 107 of file PDL.cpp.
References wrap().
mlirPDLTypeTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLTypeTypeGetTypeID (void)
Definition at line 99 of file PDL.cpp.
References wrap().
mlirPDLValueTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirPDLValueTypeGet (MlirContext ctx)
Definition at line 121 of file PDL.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::ValueType::bindDerived().
mlirPDLValueTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirPDLValueTypeGetName (void)
Definition at line 125 of file PDL.cpp.
References wrap().
mlirPDLValueTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirPDLValueTypeGetTypeID (void)
Definition at line 117 of file PDL.cpp.
References wrap().
mlirTypeIsAPDLAttributeType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLAttributeType (MlirType type)
Definition at line 31 of file PDL.cpp.
References unwrap().
mlirTypeIsAPDLOperationType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLOperationType (MlirType type)
Definition at line 51 of file PDL.cpp.
References unwrap().
mlirTypeIsAPDLRangeType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLRangeType (MlirType type)
Definition at line 71 of file PDL.cpp.
References unwrap().
mlirTypeIsAPDLType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLType (MlirType type)
Definition at line 23 of file PDL.cpp.
References mlirTypeIsAPDLType(), and unwrap().
Referenced by mlirTypeIsAPDLType().
mlirTypeIsAPDLTypeType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLTypeType (MlirType type)
Definition at line 95 of file PDL.cpp.
References unwrap().
mlirTypeIsAPDLValueType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAPDLValueType (MlirType type)
Definition at line 113 of file PDL.cpp.
References unwrap().