MLIR: include/mlir/CAPI/Support.h File Reference
Support.h File Reference
#include "mlir-c/Support.h"
#include "mlir/CAPI/Wrap.h"
#include "mlir/Support/TypeID.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/LogicalResult.h"
Namespaces
llvm
The OpAsmOpInterface, see OpAsmInterface.td for more details.
Functions
MlirStringRef wrap (llvm::StringRef ref)
Converts a StringRef into its MLIR C API equivalent.
llvm::StringRef unwrap (MlirStringRef ref)
Creates a StringRef out of its MLIR C API equivalent.
MlirLogicalResult wrap (llvm::LogicalResult res)
llvm::LogicalResult unwrap (MlirLogicalResult res)
Function Documentation
unwrap() [1/2]
llvm::LogicalResult unwrap (MlirLogicalResult res) inline
Definition at line 44 of file Support.h.
References mlirLogicalResultIsSuccess().
unwrap() [2/2]
llvm::StringRef unwrap (MlirStringRef ref) inline
Creates a StringRef out of its MLIR C API equivalent.
Definition at line 34 of file Support.h.
References MlirStringRef::data, and MlirStringRef::length.
wrap() [1/2]
MlirLogicalResult wrap (llvm::LogicalResult res) inline
Definition at line 38 of file Support.h.
References mlirLogicalResultFailure(), and mlirLogicalResultSuccess().
wrap() [2/2]
MlirStringRef wrap (llvm::StringRef ref) inline
Converts a StringRef into its MLIR C API equivalent.
Definition at line 29 of file Support.h.
References mlirStringRefCreate().