MLIR: include/mlir-c/BuiltinAttributes.h File Reference
BuiltinAttributes.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include "mlir-c/IntegerSet.h"
#include "mlir-c/Support.h"
Functions
MLIR_CAPI_EXPORTED MlirAttribute mlirAttributeGetNull (void)
Returns an empty attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsALocation (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsAAffineMap (MlirAttribute attr)
Checks whether the given attribute is an affine map attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirAffineMapAttrGet (MlirAffineMap map)
Creates an affine map attribute wrapping the given map.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapAttrGetValue (MlirAttribute attr)
Returns the affine map wrapped in the given affine map attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirAffineMapAttrGetTypeID (void)
Returns the typeID of an AffineMap attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAArray (MlirAttribute attr)
Checks whether the given attribute is an array attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirArrayAttrGet (MlirContext ctx, intptr_t numElements, MlirAttribute const *elements)
Creates an array element containing the given list of elements in the given context.
MLIR_CAPI_EXPORTED intptr_t mlirArrayAttrGetNumElements (MlirAttribute attr)
Returns the number of elements stored in the given array attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirArrayAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element stored in the given array attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirArrayAttrGetTypeID (void)
Returns the typeID of an Array attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsADictionary (MlirAttribute attr)
Checks whether the given attribute is a dictionary attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirDictionaryAttrGet (MlirContext ctx, intptr_t numElements, MlirNamedAttribute const *elements)
Creates a dictionary attribute containing the given list of elements in the provided context.
MLIR_CAPI_EXPORTED intptr_t mlirDictionaryAttrGetNumElements (MlirAttribute attr)
Returns the number of attributes contained in a dictionary attribute.
MLIR_CAPI_EXPORTED MlirNamedAttribute mlirDictionaryAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element of the given dictionary attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirDictionaryAttrGetElementByName (MlirAttribute attr, MlirStringRef name)
Returns the dictionary attribute element with the given name or NULL if the given name does not exist in the dictionary.
MLIR_CAPI_EXPORTED MlirTypeID mlirDictionaryAttrGetTypeID (void)
Returns the typeID of a Dictionary attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAFloat (MlirAttribute attr)
Checks whether the given attribute is a floating point attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirFloatAttrDoubleGet (MlirContext ctx, MlirType type, double value)
Creates a floating point attribute in the given context with the given double value and double-precision FP semantics.
MLIR_CAPI_EXPORTED MlirAttribute mlirFloatAttrDoubleGetChecked (MlirLocation loc, MlirType type, double value)
Same as "mlirFloatAttrDoubleGet", but if the type is not valid for a construction of a FloatAttr, returns a null MlirAttribute.
MLIR_CAPI_EXPORTED double mlirFloatAttrGetValueDouble (MlirAttribute attr)
Returns the value stored in the given floating point attribute, interpreting the value as double.
MLIR_CAPI_EXPORTED MlirTypeID mlirFloatAttrGetTypeID (void)
Returns the typeID of a Float attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAInteger (MlirAttribute attr)
Checks whether the given attribute is an integer attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirIntegerAttrGet (MlirType type, int64_t value)
Creates an integer attribute of the given type with the given integer value.
MLIR_CAPI_EXPORTED int64_t mlirIntegerAttrGetValueInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value is of signless type and fits into a signed 64-bit integer.
MLIR_CAPI_EXPORTED int64_t mlirIntegerAttrGetValueSInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value is of signed type and fits into a signed 64-bit integer.
MLIR_CAPI_EXPORTED uint64_t mlirIntegerAttrGetValueUInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value is of unsigned type and fits into an unsigned 64-bit integer.
MLIR_CAPI_EXPORTED MlirTypeID mlirIntegerAttrGetTypeID (void)
Returns the typeID of an Integer attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsABool (MlirAttribute attr)
Checks whether the given attribute is a bool attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirBoolAttrGet (MlirContext ctx, int value)
Creates a bool attribute in the given context with the given value.
MLIR_CAPI_EXPORTED bool mlirBoolAttrGetValue (MlirAttribute attr)
Returns the value stored in the given bool attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAIntegerSet (MlirAttribute attr)
Checks whether the given attribute is an integer set attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirIntegerSetAttrGet (MlirIntegerSet set)
Creates an integer set attribute wrapping the given set.
MLIR_CAPI_EXPORTED MlirIntegerSet mlirIntegerSetAttrGetValue (MlirAttribute attr)
Returns the integer set wrapped in the given integer set attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirIntegerSetAttrGetTypeID (void)
Returns the typeID of an IntegerSet attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAOpaque (MlirAttribute attr)
Checks whether the given attribute is an opaque attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirOpaqueAttrGet (MlirContext ctx, MlirStringRef dialectNamespace, intptr_t dataLength, const char *data, MlirType type)
Creates an opaque attribute in the given context associated with the dialect identified by its namespace.
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueAttrGetDialectNamespace (MlirAttribute attr)
Returns the namespace of the dialect with which the given opaque attribute is associated.
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueAttrGetData (MlirAttribute attr)
Returns the raw data as a string reference.
MLIR_CAPI_EXPORTED MlirTypeID mlirOpaqueAttrGetTypeID (void)
Returns the typeID of an Opaque attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAString (MlirAttribute attr)
Checks whether the given attribute is a string attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirStringAttrGet (MlirContext ctx, MlirStringRef str)
Creates a string attribute in the given context containing the given string.
MLIR_CAPI_EXPORTED MlirAttribute mlirStringAttrTypedGet (MlirType type, MlirStringRef str)
Creates a string attribute in the given context containing the given string.
MLIR_CAPI_EXPORTED MlirStringRef mlirStringAttrGetValue (MlirAttribute attr)
Returns the attribute values as a string reference.
MLIR_CAPI_EXPORTED MlirTypeID mlirStringAttrGetTypeID (void)
Returns the typeID of a String attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsASymbolRef (MlirAttribute attr)
Checks whether the given attribute is a symbol reference attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirSymbolRefAttrGet (MlirContext ctx, MlirStringRef symbol, intptr_t numReferences, MlirAttribute const *references)
Creates a symbol reference attribute in the given context referencing a symbol identified by the given string inside a list of nested references.
MLIR_CAPI_EXPORTED MlirStringRef mlirSymbolRefAttrGetRootReference (MlirAttribute attr)
Returns the string reference to the root referenced symbol.
MLIR_CAPI_EXPORTED MlirStringRef mlirSymbolRefAttrGetLeafReference (MlirAttribute attr)
Returns the string reference to the leaf referenced symbol.
MLIR_CAPI_EXPORTED intptr_t mlirSymbolRefAttrGetNumNestedReferences (MlirAttribute attr)
Returns the number of references nested in the given symbol reference attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirSymbolRefAttrGetNestedReference (MlirAttribute attr, intptr_t pos)
Returns pos-th reference nested in the given symbol reference attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirSymbolRefAttrGetTypeID (void)
Returns the typeID of an SymbolRef attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirDisctinctAttrCreate (MlirAttribute referencedAttr)
Creates a DisctinctAttr with the referenced attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAFlatSymbolRef (MlirAttribute attr)
Checks whether the given attribute is a flat symbol reference attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirFlatSymbolRefAttrGet (MlirContext ctx, MlirStringRef symbol)
Creates a flat symbol reference attribute in the given context referencing a symbol identified by the given string.
MLIR_CAPI_EXPORTED MlirStringRef mlirFlatSymbolRefAttrGetValue (MlirAttribute attr)
Returns the referenced symbol as a string reference.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAType (MlirAttribute attr)
Checks whether the given attribute is a type attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirTypeAttrGet (MlirType type)
Creates a type attribute wrapping the given type in the same context as the type.
MLIR_CAPI_EXPORTED MlirType mlirTypeAttrGetValue (MlirAttribute attr)
Returns the type stored in the given type attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirTypeAttrGetTypeID (void)
Returns the typeID of a Type attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAUnit (MlirAttribute attr)
Checks whether the given attribute is a unit attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirUnitAttrGet (MlirContext ctx)
Creates a unit attribute in the given context.
MLIR_CAPI_EXPORTED MlirTypeID mlirUnitAttrGetTypeID (void)
Returns the typeID of a Unit attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAElements (MlirAttribute attr)
Checks whether the given attribute is an elements attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirElementsAttrGetValue (MlirAttribute attr, intptr_t rank, uint64_t *idxs)
Returns the element at the given rank-dimensional index.
MLIR_CAPI_EXPORTED bool mlirElementsAttrIsValidIndex (MlirAttribute attr, intptr_t rank, uint64_t *idxs)
Checks whether the given rank-dimensional index is valid in the given elements attribute.
MLIR_CAPI_EXPORTED int64_t mlirElementsAttrGetNumElements (MlirAttribute attr)
Gets the total number of elements in the given elements attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirDenseArrayAttrGetTypeID (void)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseBoolArray (MlirAttribute attr)
Checks whether the given attribute is a dense array attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI8Array (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI16Array (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI32Array (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI64Array (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseF32Array (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseF64Array (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseBoolArrayGet (MlirContext ctx, intptr_t size, int const *values)
Create a dense array attribute with the given elements.
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI8ArrayGet (MlirContext ctx, intptr_t size, int8_t const *values)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI16ArrayGet (MlirContext ctx, intptr_t size, int16_t const *values)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI32ArrayGet (MlirContext ctx, intptr_t size, int32_t const *values)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI64ArrayGet (MlirContext ctx, intptr_t size, int64_t const *values)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseF32ArrayGet (MlirContext ctx, intptr_t size, float const *values)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseF64ArrayGet (MlirContext ctx, intptr_t size, double const *values)
MLIR_CAPI_EXPORTED intptr_t mlirDenseArrayGetNumElements (MlirAttribute attr)
Get the size of a dense array.
MLIR_CAPI_EXPORTED bool mlirDenseBoolArrayGetElement (MlirAttribute attr, intptr_t pos)
Get an element of a dense array.
MLIR_CAPI_EXPORTED int8_t mlirDenseI8ArrayGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int16_t mlirDenseI16ArrayGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int32_t mlirDenseI32ArrayGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int64_t mlirDenseI64ArrayGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED float mlirDenseF32ArrayGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED double mlirDenseF64ArrayGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseElements (MlirAttribute attr)
Checks whether the given attribute is a dense elements attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseIntElements (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseFPElements (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirTypeID mlirDenseIntOrFPElementsAttrGetTypeID (void)
Returns the typeID of an DenseIntOrFPElements attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrGet (MlirType shapedType, intptr_t numElements, MlirAttribute const *elements)
Creates a dense elements attribute with the given Shaped type and elements in the same context as the type.
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrRawBufferGet (MlirType shapedType, size_t rawBufferSize, const void *rawBuffer)
Creates a dense elements attribute with the given Shaped type and elements populated from a packed, row-major opaque buffer of contents.
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrSplatGet (MlirType shapedType, MlirAttribute element)
Creates a dense elements attribute with the given Shaped type containing a single replicated element (splat).
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrBoolSplatGet (MlirType shapedType, bool element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt8SplatGet (MlirType shapedType, uint8_t element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt8SplatGet (MlirType shapedType, int8_t element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt32SplatGet (MlirType shapedType, uint32_t element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt32SplatGet (MlirType shapedType, int32_t element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt64SplatGet (MlirType shapedType, uint64_t element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt64SplatGet (MlirType shapedType, int64_t element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrFloatSplatGet (MlirType shapedType, float element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrDoubleSplatGet (MlirType shapedType, double element)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrBoolGet (MlirType shapedType, intptr_t numElements, const int *elements)
Creates a dense elements attribute with the given shaped type from elements of a specific type.
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt8Get (MlirType shapedType, intptr_t numElements, const uint8_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt8Get (MlirType shapedType, intptr_t numElements, const int8_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt16Get (MlirType shapedType, intptr_t numElements, const uint16_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt16Get (MlirType shapedType, intptr_t numElements, const int16_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt32Get (MlirType shapedType, intptr_t numElements, const uint32_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt32Get (MlirType shapedType, intptr_t numElements, const int32_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt64Get (MlirType shapedType, intptr_t numElements, const uint64_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt64Get (MlirType shapedType, intptr_t numElements, const int64_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrFloatGet (MlirType shapedType, intptr_t numElements, const float *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrDoubleGet (MlirType shapedType, intptr_t numElements, const double *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrBFloat16Get (MlirType shapedType, intptr_t numElements, const uint16_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrFloat16Get (MlirType shapedType, intptr_t numElements, const uint16_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrStringGet (MlirType shapedType, intptr_t numElements, MlirStringRef *strs)
Creates a dense elements attribute with the given shaped type from string elements.
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrReshapeGet (MlirAttribute attr, MlirType shapedType)
Creates a dense elements attribute that has the same data as the given dense elements attribute and a different shaped type.
MLIR_CAPI_EXPORTED bool mlirDenseElementsAttrIsSplat (MlirAttribute attr)
Checks whether the given dense elements attribute contains a single replicated value (splat).
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrGetSplatValue (MlirAttribute attr)
Returns the single replicated value (splat) of a specific type contained by the given dense elements attribute.
MLIR_CAPI_EXPORTED int mlirDenseElementsAttrGetBoolSplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED int8_t mlirDenseElementsAttrGetInt8SplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED uint8_t mlirDenseElementsAttrGetUInt8SplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED int32_t mlirDenseElementsAttrGetInt32SplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED uint32_t mlirDenseElementsAttrGetUInt32SplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED int64_t mlirDenseElementsAttrGetInt64SplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED uint64_t mlirDenseElementsAttrGetUInt64SplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED float mlirDenseElementsAttrGetFloatSplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED double mlirDenseElementsAttrGetDoubleSplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirStringRef mlirDenseElementsAttrGetStringSplatValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool mlirDenseElementsAttrGetBoolValue (MlirAttribute attr, intptr_t pos)
Returns the pos-th value (flat contiguous indexing) of a specific type contained by the given dense elements attribute.
MLIR_CAPI_EXPORTED int8_t mlirDenseElementsAttrGetInt8Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint8_t mlirDenseElementsAttrGetUInt8Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int16_t mlirDenseElementsAttrGetInt16Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint16_t mlirDenseElementsAttrGetUInt16Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int32_t mlirDenseElementsAttrGetInt32Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint32_t mlirDenseElementsAttrGetUInt32Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int64_t mlirDenseElementsAttrGetInt64Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint64_t mlirDenseElementsAttrGetUInt64Value (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint64_t mlirDenseElementsAttrGetIndexValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED float mlirDenseElementsAttrGetFloatValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED double mlirDenseElementsAttrGetDoubleValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED MlirStringRef mlirDenseElementsAttrGetStringValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED const void * mlirDenseElementsAttrGetRawData (MlirAttribute attr)
Returns the raw data of the given dense elements attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseResourceElements (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, void *data, size_t dataLength, size_t dataAlignment, bool dataIsMutable, void(*deleter)(void *userData, const void *data, size_t size, size_t align), void *userData)
Unlike the typed accessors below, constructs the attribute with a raw data buffer and no type/alignment checking.
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseBoolResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt8ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint8_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt8ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int8_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt16ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint16_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt16ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int16_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt32ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint32_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt32ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int32_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt64ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint64_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt64ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int64_t *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseFloatResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const float *elements)
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseDoubleResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const double *elements)
MLIR_CAPI_EXPORTED bool mlirDenseBoolResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Returns the pos-th value (flat contiguous indexing) of a specific type contained by the given dense resource elements attribute.
MLIR_CAPI_EXPORTED int8_t mlirDenseInt8ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint8_t mlirDenseUInt8ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int16_t mlirDenseInt16ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint16_t mlirDenseUInt16ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int32_t mlirDenseInt32ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint32_t mlirDenseUInt32ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED int64_t mlirDenseInt64ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED uint64_t mlirDenseUInt64ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED float mlirDenseFloatResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED double mlirDenseDoubleResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED bool mlirAttributeIsASparseElements (MlirAttribute attr)
Checks whether the given attribute is a sparse elements attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseElementsAttribute (MlirType shapedType, MlirAttribute denseIndices, MlirAttribute denseValues)
Creates a sparse elements attribute of the given shape from a list of indices and a list of associated values.
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseElementsAttrGetIndices (MlirAttribute attr)
Returns the dense elements attribute containing 64-bit integer indices of non-null elements in the given sparse elements attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseElementsAttrGetValues (MlirAttribute attr)
Returns the dense elements attribute containing the non-null elements in the given sparse elements attribute.
MLIR_CAPI_EXPORTED MlirTypeID mlirSparseElementsAttrGetTypeID (void)
Returns the typeID of a SparseElements attribute.
MLIR_CAPI_EXPORTED bool mlirAttributeIsAStridedLayout (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute mlirStridedLayoutAttrGet (MlirContext ctx, int64_t offset, intptr_t numStrides, const int64_t *strides)
MLIR_CAPI_EXPORTED int64_t mlirStridedLayoutAttrGetOffset (MlirAttribute attr)
MLIR_CAPI_EXPORTED intptr_t mlirStridedLayoutAttrGetNumStrides (MlirAttribute attr)
MLIR_CAPI_EXPORTED int64_t mlirStridedLayoutAttrGetStride (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED MlirTypeID mlirStridedLayoutAttrGetTypeID (void)
Returns the typeID of a StridedLayout attribute.
Function Documentation
mlirAffineMapAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirAffineMapAttrGet (MlirAffineMap map)
Creates an affine map attribute wrapping the given map.
The attribute belongs to the same context as the affine map.
Definition at line 40 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirAffineMapAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirAffineMapAttrGetTypeID (void)
Returns the typeID of an AffineMap attribute.
Definition at line 48 of file BuiltinAttributes.cpp.
References wrap().
mlirAffineMapAttrGetValue()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapAttrGetValue (MlirAttribute attr)
Returns the affine map wrapped in the given affine map attribute.
Definition at line 44 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirArrayAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirArrayAttrGet (MlirContext ctx, intptr_t numElements, MlirAttribute const * elements)
Creates an array element containing the given list of elements in the given context.
Definition at line 60 of file BuiltinAttributes.cpp.
References unwrap(), unwrapList(), and wrap().
mlirArrayAttrGetElement()
MLIR_CAPI_EXPORTED MlirAttribute mlirArrayAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element stored in the given array attribute.
Definition at line 72 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirArrayAttrGetNumElements()
MLIR_CAPI_EXPORTED intptr_t mlirArrayAttrGetNumElements (MlirAttribute attr)
Returns the number of elements stored in the given array attribute.
Definition at line 68 of file BuiltinAttributes.cpp.
References unwrap().
mlirArrayAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirArrayAttrGetTypeID (void)
Returns the typeID of an Array attribute.
Definition at line 76 of file BuiltinAttributes.cpp.
References wrap().
mlirAttributeGetNull()
MLIR_CAPI_EXPORTED MlirAttribute mlirAttributeGetNull (void)
Returns an empty attribute.
Definition at line 22 of file BuiltinAttributes.cpp.
Referenced by mlir::python::PyInferShapedTypeOpInterface::inferReturnTypeComponents(), mlir::python::PyInferTypeOpInterface::inferReturnTypes(), and mlirDenseElementsAttrRawBufferGet().
mlirAttributeIsAAffineMap()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAAffineMap (MlirAttribute attr)
Checks whether the given attribute is an affine map attribute.
Definition at line 36 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAArray()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAArray (MlirAttribute attr)
Checks whether the given attribute is an array attribute.
Definition at line 56 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsABool()
MLIR_CAPI_EXPORTED bool mlirAttributeIsABool (MlirAttribute attr)
Checks whether the given attribute is a bool attribute.
Definition at line 172 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseBoolArray()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseBoolArray (MlirAttribute attr)
Checks whether the given attribute is a dense array attribute.
Definition at line 389 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseElements()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseElements (MlirAttribute attr)
Checks whether the given attribute is a dense elements attribute.
Definition at line 493 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseF32Array()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseF32Array (MlirAttribute attr)
Definition at line 404 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseF64Array()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseF64Array (MlirAttribute attr)
Definition at line 407 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseFPElements()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseFPElements (MlirAttribute attr)
Definition at line 501 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseI16Array()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI16Array (MlirAttribute attr)
Definition at line 395 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseI32Array()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI32Array (MlirAttribute attr)
Definition at line 398 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseI64Array()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI64Array (MlirAttribute attr)
Definition at line 401 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseI8Array()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseI8Array (MlirAttribute attr)
Definition at line 392 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseIntElements()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseIntElements (MlirAttribute attr)
Definition at line 497 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADenseResourceElements()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADenseResourceElements (MlirAttribute attr)
Definition at line 789 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsADictionary()
MLIR_CAPI_EXPORTED bool mlirAttributeIsADictionary (MlirAttribute attr)
Checks whether the given attribute is a dictionary attribute.
Definition at line 82 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAElements()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAElements (MlirAttribute attr)
Checks whether the given attribute is an elements attribute.
Definition at line 357 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAFlatSymbolRef()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAFlatSymbolRef (MlirAttribute attr)
Checks whether the given attribute is a flat symbol reference attribute.
Definition at line 309 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAFloat()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAFloat (MlirAttribute attr)
Checks whether the given attribute is a floating point attribute.
Definition at line 120 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAInteger()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAInteger (MlirAttribute attr)
Checks whether the given attribute is an integer attribute.
Definition at line 144 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAIntegerSet()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAIntegerSet (MlirAttribute attr)
Checks whether the given attribute is an integer set attribute.
Definition at line 188 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsALocation()
MLIR_CAPI_EXPORTED bool mlirAttributeIsALocation (MlirAttribute attr)
Definition at line 28 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAOpaque()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAOpaque (MlirAttribute attr)
Checks whether the given attribute is an opaque attribute.
Definition at line 208 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsASparseElements()
MLIR_CAPI_EXPORTED bool mlirAttributeIsASparseElements (MlirAttribute attr)
Checks whether the given attribute is a sparse elements attribute.
Definition at line 944 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAStridedLayout()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAStridedLayout (MlirAttribute attr)
Definition at line 973 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAString()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAString (MlirAttribute attr)
Checks whether the given attribute is a string attribute.
Definition at line 237 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsASymbolRef()
MLIR_CAPI_EXPORTED bool mlirAttributeIsASymbolRef (MlirAttribute attr)
Checks whether the given attribute is a symbol reference attribute.
Definition at line 261 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAType()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAType (MlirAttribute attr)
Checks whether the given attribute is a type attribute.
Definition at line 325 of file BuiltinAttributes.cpp.
References unwrap().
mlirAttributeIsAUnit()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAUnit (MlirAttribute attr)
Checks whether the given attribute is a unit attribute.
Definition at line 343 of file BuiltinAttributes.cpp.
References unwrap().
mlirBoolAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirBoolAttrGet (MlirContext ctx, int value)
Creates a bool attribute in the given context with the given value.
Definition at line 176 of file BuiltinAttributes.cpp.
References mlir::BoolAttr::get(), unwrap(), and wrap().
mlirBoolAttrGetValue()
MLIR_CAPI_EXPORTED bool mlirBoolAttrGetValue (MlirAttribute attr)
Returns the value stored in the given bool attribute.
Definition at line 180 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseArrayAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirDenseArrayAttrGetTypeID (void)
Definition at line 381 of file BuiltinAttributes.cpp.
References wrap().
mlirDenseArrayGetNumElements()
MLIR_CAPI_EXPORTED intptr_t mlirDenseArrayGetNumElements (MlirAttribute attr)
Get the size of a dense array.
Definition at line 455 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseBoolArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseBoolArrayGet (MlirContext ctx, intptr_t size, int const * values)
Create a dense array attribute with the given elements.
Definition at line 415 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< bool >::get(), unwrap(), and wrap().
mlirDenseBoolArrayGetElement()
MLIR_CAPI_EXPORTED bool mlirDenseBoolArrayGetElement (MlirAttribute attr, intptr_t pos)
Get an element of a dense array.
Definition at line 463 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseBoolResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED bool mlirDenseBoolResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Returns the pos-th value (flat contiguous indexing) of a specific type contained by the given dense resource elements attribute.
Definition at line 892 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseDoubleResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED double mlirDenseDoubleResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 935 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseElementsAttrBFloat16Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrBFloat16Get (MlirType shapedType, intptr_t numElements, const uint16_t * elements)
Definition at line 653 of file BuiltinAttributes.cpp.
References mlirDenseElementsAttrRawBufferGet().
mlirDenseElementsAttrBoolGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrBoolGet (MlirType shapedType, intptr_t numElements, const int * elements)
Creates a dense elements attribute with the given shaped type from elements of a specific type.
Expects the element type of the shaped type to match the data element type.
Definition at line 586 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrBoolSplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrBoolSplatGet (MlirType shapedType, bool element)
Definition at line 540 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrDoubleGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrDoubleGet (MlirType shapedType, intptr_t numElements, const double * elements)
Definition at line 648 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrDoubleSplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrDoubleSplatGet (MlirType shapedType, double element)
Definition at line 580 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrFloat16Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrFloat16Get (MlirType shapedType, intptr_t numElements, const uint16_t * elements)
Definition at line 660 of file BuiltinAttributes.cpp.
References mlirDenseElementsAttrRawBufferGet().
mlirDenseElementsAttrFloatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrFloatGet (MlirType shapedType, intptr_t numElements, const float * elements)
Definition at line 643 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrFloatSplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrFloatSplatGet (MlirType shapedType, float element)
Definition at line 575 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrGet (MlirType shapedType, intptr_t numElements, MlirAttribute const * elements)
Creates a dense elements attribute with the given Shaped type and elements in the same context as the type.
Definition at line 513 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), unwrapList(), and wrap().
mlirDenseElementsAttrGetBoolSplatValue()
MLIR_CAPI_EXPORTED int mlirDenseElementsAttrGetBoolSplatValue (MlirAttribute attr)
Definition at line 698 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetBoolValue()
MLIR_CAPI_EXPORTED bool mlirDenseElementsAttrGetBoolValue (MlirAttribute attr, intptr_t pos)
Returns the pos-th value (flat contiguous indexing) of a specific type contained by the given dense elements attribute.
Definition at line 734 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetDoubleSplatValue()
MLIR_CAPI_EXPORTED double mlirDenseElementsAttrGetDoubleSplatValue (MlirAttribute attr)
Definition at line 722 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetDoubleValue()
MLIR_CAPI_EXPORTED double mlirDenseElementsAttrGetDoubleValue (MlirAttribute attr, intptr_t pos)
Definition at line 767 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetFloatSplatValue()
MLIR_CAPI_EXPORTED float mlirDenseElementsAttrGetFloatSplatValue (MlirAttribute attr)
Definition at line 719 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetFloatValue()
MLIR_CAPI_EXPORTED float mlirDenseElementsAttrGetFloatValue (MlirAttribute attr, intptr_t pos)
Definition at line 764 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetIndexValue()
MLIR_CAPI_EXPORTED uint64_t mlirDenseElementsAttrGetIndexValue (MlirAttribute attr, intptr_t pos)
Definition at line 761 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt16Value()
MLIR_CAPI_EXPORTED int16_t mlirDenseElementsAttrGetInt16Value (MlirAttribute attr, intptr_t pos)
Definition at line 743 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt32SplatValue()
MLIR_CAPI_EXPORTED int32_t mlirDenseElementsAttrGetInt32SplatValue (MlirAttribute attr)
Definition at line 707 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt32Value()
MLIR_CAPI_EXPORTED int32_t mlirDenseElementsAttrGetInt32Value (MlirAttribute attr, intptr_t pos)
Definition at line 749 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt64SplatValue()
MLIR_CAPI_EXPORTED int64_t mlirDenseElementsAttrGetInt64SplatValue (MlirAttribute attr)
Definition at line 713 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt64Value()
MLIR_CAPI_EXPORTED int64_t mlirDenseElementsAttrGetInt64Value (MlirAttribute attr, intptr_t pos)
Definition at line 755 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt8SplatValue()
MLIR_CAPI_EXPORTED int8_t mlirDenseElementsAttrGetInt8SplatValue (MlirAttribute attr)
Definition at line 701 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetInt8Value()
MLIR_CAPI_EXPORTED int8_t mlirDenseElementsAttrGetInt8Value (MlirAttribute attr, intptr_t pos)
Definition at line 737 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetRawData()
MLIR_CAPI_EXPORTED const void * mlirDenseElementsAttrGetRawData (MlirAttribute attr)
Returns the raw data of the given dense elements attribute.
Definition at line 780 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetSplatValue()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrGetSplatValue (MlirAttribute attr)
Returns the single replicated value (splat) of a specific type contained by the given dense elements attribute.
Definition at line 694 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirDenseElementsAttrGetStringSplatValue()
MLIR_CAPI_EXPORTED MlirStringRef mlirDenseElementsAttrGetStringSplatValue (MlirAttribute attr)
Definition at line 725 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirDenseElementsAttrGetStringValue()
MLIR_CAPI_EXPORTED MlirStringRef mlirDenseElementsAttrGetStringValue (MlirAttribute attr, intptr_t pos)
Definition at line 770 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirDenseElementsAttrGetUInt16Value()
MLIR_CAPI_EXPORTED uint16_t mlirDenseElementsAttrGetUInt16Value (MlirAttribute attr, intptr_t pos)
Definition at line 746 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetUInt32SplatValue()
MLIR_CAPI_EXPORTED uint32_t mlirDenseElementsAttrGetUInt32SplatValue (MlirAttribute attr)
Definition at line 710 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetUInt32Value()
MLIR_CAPI_EXPORTED uint32_t mlirDenseElementsAttrGetUInt32Value (MlirAttribute attr, intptr_t pos)
Definition at line 752 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetUInt64SplatValue()
MLIR_CAPI_EXPORTED uint64_t mlirDenseElementsAttrGetUInt64SplatValue (MlirAttribute attr)
Definition at line 716 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetUInt64Value()
MLIR_CAPI_EXPORTED uint64_t mlirDenseElementsAttrGetUInt64Value (MlirAttribute attr, intptr_t pos)
Definition at line 758 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetUInt8SplatValue()
MLIR_CAPI_EXPORTED uint8_t mlirDenseElementsAttrGetUInt8SplatValue (MlirAttribute attr)
Definition at line 704 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetUInt8Value()
MLIR_CAPI_EXPORTED uint8_t mlirDenseElementsAttrGetUInt8Value (MlirAttribute attr, intptr_t pos)
Definition at line 740 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrInt16Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt16Get (MlirType shapedType, intptr_t numElements, const int16_t * elements)
Definition at line 618 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrInt32Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt32Get (MlirType shapedType, intptr_t numElements, const int32_t * elements)
Definition at line 628 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrInt32SplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt32SplatGet (MlirType shapedType, int32_t element)
Definition at line 560 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrInt64Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt64Get (MlirType shapedType, intptr_t numElements, const int64_t * elements)
Definition at line 638 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrInt64SplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt64SplatGet (MlirType shapedType, int64_t element)
Definition at line 570 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrInt8Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt8Get (MlirType shapedType, intptr_t numElements, const int8_t * elements)
Definition at line 608 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrInt8SplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrInt8SplatGet (MlirType shapedType, int8_t element)
Definition at line 550 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrIsSplat()
MLIR_CAPI_EXPORTED bool mlirDenseElementsAttrIsSplat (MlirAttribute attr)
Checks whether the given dense elements attribute contains a single replicated value (splat).
Definition at line 690 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseElementsAttrRawBufferGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrRawBufferGet (MlirType shapedType, size_t rawBufferSize, const void * rawBuffer)
Creates a dense elements attribute with the given Shaped type and elements populated from a packed, row-major opaque buffer of contents.
The format of the raw buffer is a densely packed array of values that can be bitcast to the storage format of the element type specified. Types that are not byte aligned will be:
For bitwidth > 1: Rounded up to the next byte.
For bitwidth = 1: Packed into 8bit bytes with bits corresponding to the linear order of the shape type from MSB to LSB, padded to on the right.
A raw buffer of a single element (or for 1-bit, a byte of value 0 or 255) will be interpreted as a splat. User code should be prepared for additional, conformant patterns to be identified as splats in the future.
Definition at line 522 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::getFromRawBuffer(), mlir::DenseElementsAttr::isValidRawBuffer(), mlirAttributeGetNull(), unwrap(), and wrap().
Referenced by mlirDenseElementsAttrBFloat16Get(), and mlirDenseElementsAttrFloat16Get().
mlirDenseElementsAttrReshapeGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrReshapeGet (MlirAttribute attr, MlirType shapedType)
Creates a dense elements attribute that has the same data as the given dense elements attribute and a different shaped type.
The new type must have the same total number of elements.
Definition at line 680 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirDenseElementsAttrSplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrSplatGet (MlirType shapedType, MlirAttribute element)
Creates a dense elements attribute with the given Shaped type containing a single replicated element (splat).
Definition at line 535 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrStringGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrStringGet (MlirType shapedType, intptr_t numElements, MlirStringRef * strs)
Creates a dense elements attribute with the given shaped type from string elements.
Definition at line 668 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrUInt16Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt16Get (MlirType shapedType, intptr_t numElements, const uint16_t * elements)
Definition at line 613 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrUInt32Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt32Get (MlirType shapedType, intptr_t numElements, const uint32_t * elements)
Definition at line 623 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrUInt32SplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt32SplatGet (MlirType shapedType, uint32_t element)
Definition at line 555 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrUInt64Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt64Get (MlirType shapedType, intptr_t numElements, const uint64_t * elements)
Definition at line 633 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrUInt64SplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt64SplatGet (MlirType shapedType, uint64_t element)
Definition at line 565 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseElementsAttrUInt8Get()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt8Get (MlirType shapedType, intptr_t numElements, const uint8_t * elements)
Definition at line 603 of file BuiltinAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrUInt8SplatGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseElementsAttrUInt8SplatGet (MlirType shapedType, uint8_t element)
Definition at line 545 of file BuiltinAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and wrap().
mlirDenseF32ArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseF32ArrayGet (MlirContext ctx, intptr_t size, float const * values)
Definition at line 440 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< float >::get(), unwrap(), and wrap().
mlirDenseF32ArrayGetElement()
MLIR_CAPI_EXPORTED float mlirDenseF32ArrayGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 478 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseF64ArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseF64ArrayGet (MlirContext ctx, intptr_t size, double const * values)
Definition at line 445 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< double >::get(), unwrap(), and wrap().
mlirDenseF64ArrayGetElement()
MLIR_CAPI_EXPORTED double mlirDenseF64ArrayGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 481 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseFloatResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED float mlirDenseFloatResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 931 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseI16ArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI16ArrayGet (MlirContext ctx, intptr_t size, int16_t const * values)
Definition at line 425 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< int16_t >::get(), unwrap(), and wrap().
mlirDenseI16ArrayGetElement()
MLIR_CAPI_EXPORTED int16_t mlirDenseI16ArrayGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 469 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseI32ArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI32ArrayGet (MlirContext ctx, intptr_t size, int32_t const * values)
Definition at line 430 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< int32_t >::get(), unwrap(), and wrap().
Referenced by mlir::python::PyOpView::buildGeneric().
mlirDenseI32ArrayGetElement()
MLIR_CAPI_EXPORTED int32_t mlirDenseI32ArrayGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 472 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseI64ArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI64ArrayGet (MlirContext ctx, intptr_t size, int64_t const * values)
Definition at line 435 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< int64_t >::get(), unwrap(), and wrap().
mlirDenseI64ArrayGetElement()
MLIR_CAPI_EXPORTED int64_t mlirDenseI64ArrayGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 475 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseI8ArrayGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDenseI8ArrayGet (MlirContext ctx, intptr_t size, int8_t const * values)
Definition at line 420 of file BuiltinAttributes.cpp.
References mlir::detail::DenseArrayAttrImpl< int8_t >::get(), unwrap(), and wrap().
mlirDenseI8ArrayGetElement()
MLIR_CAPI_EXPORTED int8_t mlirDenseI8ArrayGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 466 of file BuiltinAttributes.cpp.
References unwrap().
mlirDenseInt16ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED int16_t mlirDenseInt16ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 919 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseInt32ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED int32_t mlirDenseInt32ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 923 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseInt64ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED int64_t mlirDenseInt64ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 927 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseInt8ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED int8_t mlirDenseInt8ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 915 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseIntOrFPElementsAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirDenseIntOrFPElementsAttrGetTypeID (void)
Returns the typeID of an DenseIntOrFPElements attribute.
Definition at line 505 of file BuiltinAttributes.cpp.
References wrap().
mlirDenseUInt16ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED uint16_t mlirDenseUInt16ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 900 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseUInt32ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED uint32_t mlirDenseUInt32ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 905 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseUInt64ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED uint64_t mlirDenseUInt64ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 910 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDenseUInt8ResourceElementsAttrGetValue()
MLIR_CAPI_EXPORTED uint8_t mlirDenseUInt8ResourceElementsAttrGetValue (MlirAttribute attr, intptr_t pos)
Definition at line 896 of file BuiltinAttributes.cpp.
References getDenseResourceVal().
mlirDictionaryAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirDictionaryAttrGet (MlirContext ctx, intptr_t numElements, MlirNamedAttribute const * elements)
Creates a dictionary attribute containing the given list of elements in the provided context.
Definition at line 86 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirDictionaryAttrGetElement()
MLIR_CAPI_EXPORTED MlirNamedAttribute mlirDictionaryAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element of the given dictionary attribute.
Definition at line 100 of file BuiltinAttributes.cpp.
References mlir::NamedAttribute::getName(), mlir::NamedAttribute::getValue(), unwrap(), and wrap().
mlirDictionaryAttrGetElementByName()
MLIR_CAPI_EXPORTED MlirAttribute mlirDictionaryAttrGetElementByName (MlirAttribute attr, MlirStringRef name)
Returns the dictionary attribute element with the given name or NULL if the given name does not exist in the dictionary.
Definition at line 107 of file BuiltinAttributes.cpp.
References mlir::get(), unwrap(), and wrap().
mlirDictionaryAttrGetNumElements()
MLIR_CAPI_EXPORTED intptr_t mlirDictionaryAttrGetNumElements (MlirAttribute attr)
Returns the number of attributes contained in a dictionary attribute.
Definition at line 96 of file BuiltinAttributes.cpp.
References unwrap().
mlirDictionaryAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirDictionaryAttrGetTypeID (void)
Returns the typeID of a Dictionary attribute.
Definition at line 112 of file BuiltinAttributes.cpp.
References wrap().
mlirDisctinctAttrCreate()
MLIR_CAPI_EXPORTED MlirAttribute mlirDisctinctAttrCreate (MlirAttribute referencedAttr)
Creates a DisctinctAttr with the referenced attribute.
Definition at line 301 of file BuiltinAttributes.cpp.
References mlir::DistinctAttr::create(), unwrap(), and wrap().
mlirElementsAttrGetNumElements()
MLIR_CAPI_EXPORTED int64_t mlirElementsAttrGetNumElements (MlirAttribute attr)
Gets the total number of elements in the given elements attribute.
In order to iterate over the attribute, obtain its type, which must be a statically shaped type and use its sizes to build a multi-dimensional index.
Definition at line 373 of file BuiltinAttributes.cpp.
References unwrap().
mlirElementsAttrGetValue()
MLIR_CAPI_EXPORTED MlirAttribute mlirElementsAttrGetValue (MlirAttribute attr, intptr_t rank, uint64_t * idxs)
Returns the element at the given rank-dimensional index.
Definition at line 361 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirElementsAttrIsValidIndex()
MLIR_CAPI_EXPORTED bool mlirElementsAttrIsValidIndex (MlirAttribute attr, intptr_t rank, uint64_t * idxs)
Checks whether the given rank-dimensional index is valid in the given elements attribute.
Definition at line 367 of file BuiltinAttributes.cpp.
References unwrap().
mlirFlatSymbolRefAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirFlatSymbolRefAttrGet (MlirContext ctx, MlirStringRef symbol)
Creates a flat symbol reference attribute in the given context referencing a symbol identified by the given string.
Definition at line 313 of file BuiltinAttributes.cpp.
References mlir::FlatSymbolRefAttr::get(), unwrap(), and wrap().
mlirFlatSymbolRefAttrGetValue()
MLIR_CAPI_EXPORTED MlirStringRef mlirFlatSymbolRefAttrGetValue (MlirAttribute attr)
Returns the referenced symbol as a string reference.
The data remains live as long as the context in which the attribute lives.
Definition at line 317 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirFloatAttrDoubleGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirFloatAttrDoubleGet (MlirContext ctx, MlirType type, double value)
Creates a floating point attribute in the given context with the given double value and double-precision FP semantics.
Definition at line 124 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirFloatAttrDoubleGetChecked()
MLIR_CAPI_EXPORTED MlirAttribute mlirFloatAttrDoubleGetChecked (MlirLocation loc, MlirType type, double value)
Same as "mlirFloatAttrDoubleGet", but if the type is not valid for a construction of a FloatAttr, returns a null MlirAttribute.
Definition at line 129 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirFloatAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirFloatAttrGetTypeID (void)
Returns the typeID of a Float attribute.
Definition at line 138 of file BuiltinAttributes.cpp.
References wrap().
mlirFloatAttrGetValueDouble()
MLIR_CAPI_EXPORTED double mlirFloatAttrGetValueDouble (MlirAttribute attr)
Returns the value stored in the given floating point attribute, interpreting the value as double.
Definition at line 134 of file BuiltinAttributes.cpp.
References unwrap().
mlirIntegerAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirIntegerAttrGet (MlirType type, int64_t value)
Creates an integer attribute of the given type with the given integer value.
Definition at line 148 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirIntegerAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirIntegerAttrGetTypeID (void)
Returns the typeID of an Integer attribute.
Definition at line 164 of file BuiltinAttributes.cpp.
References wrap().
mlirIntegerAttrGetValueInt()
MLIR_CAPI_EXPORTED int64_t mlirIntegerAttrGetValueInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value is of signless type and fits into a signed 64-bit integer.
Definition at line 152 of file BuiltinAttributes.cpp.
References unwrap().
mlirIntegerAttrGetValueSInt()
MLIR_CAPI_EXPORTED int64_t mlirIntegerAttrGetValueSInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value is of signed type and fits into a signed 64-bit integer.
Definition at line 156 of file BuiltinAttributes.cpp.
References unwrap().
mlirIntegerAttrGetValueUInt()
MLIR_CAPI_EXPORTED uint64_t mlirIntegerAttrGetValueUInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value is of unsigned type and fits into an unsigned 64-bit integer.
Definition at line 160 of file BuiltinAttributes.cpp.
References unwrap().
mlirIntegerSetAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirIntegerSetAttrGet (MlirIntegerSet set)
Creates an integer set attribute wrapping the given set.
The attribute belongs to the same context as the integer set.
Definition at line 196 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirIntegerSetAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirIntegerSetAttrGetTypeID (void)
Returns the typeID of an IntegerSet attribute.
Definition at line 192 of file BuiltinAttributes.cpp.
References wrap().
mlirIntegerSetAttrGetValue()
MLIR_CAPI_EXPORTED MlirIntegerSet mlirIntegerSetAttrGetValue (MlirAttribute attr)
Returns the integer set wrapped in the given integer set attribute.
Definition at line 200 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirOpaqueAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirOpaqueAttrGet (MlirContext ctx, MlirStringRef dialectNamespace, intptr_t dataLength, const char * data, MlirType type)
Creates an opaque attribute in the given context associated with the dialect identified by its namespace.
The attribute contains opaque byte data of the specified length (data need not be null-terminated).
Definition at line 212 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirOpaqueAttrGetData()
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueAttrGetData (MlirAttribute attr)
Returns the raw data as a string reference.
The data remains live as long as the context in which the attribute lives.
Definition at line 225 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirOpaqueAttrGetDialectNamespace()
MLIR_CAPI_EXPORTED MlirStringRef mlirOpaqueAttrGetDialectNamespace (MlirAttribute attr)
Returns the namespace of the dialect with which the given opaque attribute is associated.
The namespace string is owned by the context.
Definition at line 220 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirOpaqueAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirOpaqueAttrGetTypeID (void)
Returns the typeID of an Opaque attribute.
Definition at line 229 of file BuiltinAttributes.cpp.
References wrap().
mlirSparseElementsAttrGetIndices()
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseElementsAttrGetIndices (MlirAttribute attr)
Returns the dense elements attribute containing 64-bit integer indices of non-null elements in the given sparse elements attribute.
Definition at line 957 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirSparseElementsAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirSparseElementsAttrGetTypeID (void)
Returns the typeID of a SparseElements attribute.
Definition at line 965 of file BuiltinAttributes.cpp.
References wrap().
mlirSparseElementsAttrGetValues()
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseElementsAttrGetValues (MlirAttribute attr)
Returns the dense elements attribute containing the non-null elements in the given sparse elements attribute.
Definition at line 961 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirSparseElementsAttribute()
MLIR_CAPI_EXPORTED MlirAttribute mlirSparseElementsAttribute (MlirType shapedType, MlirAttribute denseIndices, MlirAttribute denseValues)
Creates a sparse elements attribute of the given shape from a list of indices and a list of associated values.
Both lists are expected to be dense elements attributes with the same number of elements. The list of indices is expected to contain 64-bit integers. The attribute is created in the same context as the type.
Definition at line 948 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirStridedLayoutAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirStridedLayoutAttrGet (MlirContext ctx, int64_t offset, intptr_t numStrides, const int64_t * strides)
Definition at line 977 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirStridedLayoutAttrGetNumStrides()
MLIR_CAPI_EXPORTED intptr_t mlirStridedLayoutAttrGetNumStrides (MlirAttribute attr)
Definition at line 988 of file BuiltinAttributes.cpp.
References unwrap().
mlirStridedLayoutAttrGetOffset()
MLIR_CAPI_EXPORTED int64_t mlirStridedLayoutAttrGetOffset (MlirAttribute attr)
Definition at line 984 of file BuiltinAttributes.cpp.
References unwrap().
mlirStridedLayoutAttrGetStride()
MLIR_CAPI_EXPORTED int64_t mlirStridedLayoutAttrGetStride (MlirAttribute attr, intptr_t pos)
Definition at line 993 of file BuiltinAttributes.cpp.
References unwrap().
mlirStridedLayoutAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirStridedLayoutAttrGetTypeID (void)
Returns the typeID of a StridedLayout attribute.
Definition at line 997 of file BuiltinAttributes.cpp.
References wrap().
mlirStringAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirStringAttrGet (MlirContext ctx, MlirStringRef str)
Creates a string attribute in the given context containing the given string.
Definition at line 241 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyStringAttribute::bindDerived(), mlir::python::PySymbolTable::setSymbolName(), and mlir::python::PySymbolTable::setVisibility().
mlirStringAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirStringAttrGetTypeID (void)
Returns the typeID of a String attribute.
Definition at line 253 of file BuiltinAttributes.cpp.
References wrap().
mlirStringAttrGetValue()
MLIR_CAPI_EXPORTED MlirStringRef mlirStringAttrGetValue (MlirAttribute attr)
Returns the attribute values as a string reference.
The data remains live as long as the context in which the attribute lives.
Definition at line 249 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyStringAttribute::bindDerived().
mlirStringAttrTypedGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirStringAttrTypedGet (MlirType type, MlirStringRef str)
Creates a string attribute in the given context containing the given string.
Additionally, the attribute has the given type.
Definition at line 245 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyStringAttribute::bindDerived().
mlirSymbolRefAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirSymbolRefAttrGet (MlirContext ctx, MlirStringRef symbol, intptr_t numReferences, MlirAttribute const * references)
Creates a symbol reference attribute in the given context referencing a symbol identified by the given string inside a list of nested references.
Each of the references in the list must not be nested.
Definition at line 265 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirSymbolRefAttrGetLeafReference()
MLIR_CAPI_EXPORTED MlirStringRef mlirSymbolRefAttrGetLeafReference (MlirAttribute attr)
Returns the string reference to the leaf referenced symbol.
The data remains live as long as the context in which the attribute lives.
Definition at line 281 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirSymbolRefAttrGetNestedReference()
MLIR_CAPI_EXPORTED MlirAttribute mlirSymbolRefAttrGetNestedReference (MlirAttribute attr, intptr_t pos)
Returns pos-th reference nested in the given symbol reference attribute.
Definition at line 291 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirSymbolRefAttrGetNumNestedReferences()
MLIR_CAPI_EXPORTED intptr_t mlirSymbolRefAttrGetNumNestedReferences (MlirAttribute attr)
Returns the number of references nested in the given symbol reference attribute.
Definition at line 286 of file BuiltinAttributes.cpp.
References unwrap().
mlirSymbolRefAttrGetRootReference()
MLIR_CAPI_EXPORTED MlirStringRef mlirSymbolRefAttrGetRootReference (MlirAttribute attr)
Returns the string reference to the root referenced symbol.
The data remains live as long as the context in which the attribute lives.
Definition at line 276 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirSymbolRefAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirSymbolRefAttrGetTypeID (void)
Returns the typeID of an SymbolRef attribute.
Definition at line 297 of file BuiltinAttributes.cpp.
References wrap().
mlirTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirTypeAttrGet (MlirType type)
Creates a type attribute wrapping the given type in the same context as the type.
Definition at line 329 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirTypeAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTypeAttrGetTypeID (void)
Returns the typeID of a Type attribute.
Definition at line 337 of file BuiltinAttributes.cpp.
References wrap().
mlirTypeAttrGetValue()
MLIR_CAPI_EXPORTED MlirType mlirTypeAttrGetValue (MlirAttribute attr)
Returns the type stored in the given type attribute.
Definition at line 333 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirUnitAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnitAttrGet (MlirContext ctx)
Creates a unit attribute in the given context.
Definition at line 347 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirUnitAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirUnitAttrGetTypeID (void)
Returns the typeID of a Unit attribute.
Definition at line 351 of file BuiltinAttributes.cpp.
References wrap().
mlirUnmanagedDenseBoolResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseBoolResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int * elements)
Definition at line 821 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseDoubleResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseDoubleResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const double * elements)
Definition at line 881 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseFloatResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseFloatResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const float * elements)
Definition at line 875 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseInt16ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt16ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int16_t * elements)
Definition at line 857 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseInt32ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt32ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int32_t * elements)
Definition at line 863 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseInt64ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt64ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int64_t * elements)
Definition at line 869 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseInt8ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseInt8ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const int8_t * elements)
Definition at line 851 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, void * data, size_t dataLength, size_t dataAlignment, bool dataIsMutable, void(* deleter)(void *userData, const void *data, size_t size, size_t align), void * userData)
Unlike the typed accessors below, constructs the attribute with a raw data buffer and no type/alignment checking.
Use a more strongly typed accessor if possible. If dataIsMutable is false, then an immutable AsmResourceBlob will be created and that passed data contents will be treated as const. If the deleter is non NULL, then it will be called when the data buffer can no longer be accessed (passing userData to it).
Definition at line 793 of file BuiltinAttributes.cpp.
References unwrap(), and wrap().
mlirUnmanagedDenseUInt16ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt16ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint16_t * elements)
Definition at line 833 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseUInt32ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt32ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint32_t * elements)
Definition at line 839 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseUInt64ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt64ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint64_t * elements)
Definition at line 845 of file BuiltinAttributes.cpp.
References getDenseResource().
mlirUnmanagedDenseUInt8ResourceElementsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirUnmanagedDenseUInt8ResourceElementsAttrGet (MlirType shapedType, MlirStringRef name, intptr_t numElements, const uint8_t * elements)
Definition at line 827 of file BuiltinAttributes.cpp.
References getDenseResource().