MLIR: include/mlir-c/Dialect/EmitC.h File Reference
EmitC.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Enumerations
enum MlirEmitCCmpPredicate : uint64_t {
MLIR_EMITC_CMP_PREDICATE_EQ = 0 , MLIR_EMITC_CMP_PREDICATE_NE = 1 , MLIR_EMITC_CMP_PREDICATE_LT = 2 , MLIR_EMITC_CMP_PREDICATE_LE = 3 ,
MLIR_EMITC_CMP_PREDICATE_GT = 4 , MLIR_EMITC_CMP_PREDICATE_GE = 5 , MLIR_EMITC_CMP_PREDICATE_THREE_WAY = 6
}
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (EmitC, emitc)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCArrayType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCArrayTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCArrayTypeGet (intptr_t nDims, int64_t *shape, MlirType elementType)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCLValueType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCLValueTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCLValueTypeGet (MlirType valueType)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCOpaqueType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCOpaqueTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCOpaqueTypeGet (MlirContext ctx, MlirStringRef value)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCPointerType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCPointerTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCPointerTypeGet (MlirType pointee)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCPtrDiffTType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCPtrDiffTTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCPtrDiffTTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCSignedSizeTType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCSignedSizeTTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCSignedSizeTTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCSizeTType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCSizeTTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirEmitCSizeTTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirAttributeIsAEmitCCmpPredicate (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute mlirEmitCCmpPredicateAttrGet (MlirContext ctx, enum MlirEmitCCmpPredicate val)
MLIR_CAPI_EXPORTED enum MlirEmitCCmpPredicate mlirEmitCCmpPredicateAttrGetValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCCmpPredicateAttrGetTypeID (void)
MLIR_CAPI_EXPORTED bool mlirAttributeIsAEmitCOpaque (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute mlirEmitCOpaqueAttrGet (MlirContext ctx, MlirStringRef value)
MLIR_CAPI_EXPORTED MlirStringRef mlirEmitCOpaqueAttrGetValue (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCOpaqueAttrGetTypeID (void)
Enumeration Type Documentation
MlirEmitCCmpPredicate
enum MlirEmitCCmpPredicate : uint64_t
Enumerator
MLIR_EMITC_CMP_PREDICATE_EQ
MLIR_EMITC_CMP_PREDICATE_NE
MLIR_EMITC_CMP_PREDICATE_LT
MLIR_EMITC_CMP_PREDICATE_LE
MLIR_EMITC_CMP_PREDICATE_GT
MLIR_EMITC_CMP_PREDICATE_GE
MLIR_EMITC_CMP_PREDICATE_THREE_WAY
Definition at line 22 of file EmitC.h.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (EmitC , emitc)
mlirAttributeIsAEmitCCmpPredicate()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAEmitCCmpPredicate (MlirAttribute attr)
Definition at line 152 of file EmitC.cpp.
References unwrap().
mlirAttributeIsAEmitCOpaque()
MLIR_CAPI_EXPORTED bool mlirAttributeIsAEmitCOpaque (MlirAttribute attr)
Definition at line 175 of file EmitC.cpp.
References unwrap().
mlirEmitCArrayTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCArrayTypeGet (intptr_t nDims, int64_t * shape, MlirType elementType)
Definition at line 46 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCArrayTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCArrayTypeGetTypeID (void)
Definition at line 42 of file EmitC.cpp.
References wrap().
mlirEmitCCmpPredicateAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirEmitCCmpPredicateAttrGet (MlirContext ctx, enum MlirEmitCCmpPredicate val)
Definition at line 156 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCCmpPredicateAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCCmpPredicateAttrGetTypeID (void)
Definition at line 167 of file EmitC.cpp.
References wrap().
mlirEmitCCmpPredicateAttrGetValue()
MLIR_CAPI_EXPORTED enum MlirEmitCCmpPredicate mlirEmitCCmpPredicateAttrGetValue (MlirAttribute attr)
Definition at line 162 of file EmitC.cpp.
References unwrap().
mlirEmitCLValueTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCLValueTypeGet (MlirType valueType)
Definition at line 64 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCLValueTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCLValueTypeGetTypeID (void)
Definition at line 60 of file EmitC.cpp.
References wrap().
mlirEmitCOpaqueAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirEmitCOpaqueAttrGet (MlirContext ctx, MlirStringRef value)
Definition at line 179 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCOpaqueAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCOpaqueAttrGetTypeID (void)
Definition at line 187 of file EmitC.cpp.
References wrap().
mlirEmitCOpaqueAttrGetValue()
MLIR_CAPI_EXPORTED MlirStringRef mlirEmitCOpaqueAttrGetValue (MlirAttribute attr)
Definition at line 183 of file EmitC.cpp.
References unwrap(), and wrap().
mlirEmitCOpaqueTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCOpaqueTypeGet (MlirContext ctx, MlirStringRef value)
Definition at line 80 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCOpaqueTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCOpaqueTypeGetTypeID (void)
Definition at line 76 of file EmitC.cpp.
References wrap().
mlirEmitCPointerTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCPointerTypeGet (MlirType pointee)
Definition at line 96 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCPointerTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCPointerTypeGetTypeID (void)
Definition at line 92 of file EmitC.cpp.
References wrap().
mlirEmitCPtrDiffTTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCPtrDiffTTypeGet (MlirContext ctx)
Definition at line 112 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCPtrDiffTTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCPtrDiffTTypeGetTypeID (void)
Definition at line 108 of file EmitC.cpp.
References wrap().
mlirEmitCSignedSizeTTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCSignedSizeTTypeGet (MlirContext ctx)
Definition at line 128 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCSignedSizeTTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCSignedSizeTTypeGetTypeID (void)
Definition at line 124 of file EmitC.cpp.
References wrap().
mlirEmitCSizeTTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirEmitCSizeTTypeGet (MlirContext ctx)
Definition at line 144 of file EmitC.cpp.
References mlir::get(), unwrap(), and wrap().
mlirEmitCSizeTTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirEmitCSizeTTypeGetTypeID (void)
Definition at line 140 of file EmitC.cpp.
References wrap().
mlirTypeIsAEmitCArrayType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCArrayType (MlirType type)
Definition at line 38 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCLValueType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCLValueType (MlirType type)
Definition at line 56 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCOpaqueType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCOpaqueType (MlirType type)
Definition at line 72 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCPointerType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCPointerType (MlirType type)
Definition at line 88 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCPtrDiffTType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCPtrDiffTType (MlirType type)
Definition at line 104 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCSignedSizeTType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCSignedSizeTType (MlirType type)
Definition at line 120 of file EmitC.cpp.
References unwrap().
mlirTypeIsAEmitCSizeTType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAEmitCSizeTType (MlirType type)
Definition at line 136 of file EmitC.cpp.
References unwrap().