MLIR: include/mlir-c/Dialect/Linalg.h File Reference
Linalg.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Dialect/Linalg/Passes.capi.h.inc"
Classes
struct MlirLinalgContractionDimensions
struct MlirLinalgConvolutionDimensions
Typedefs
typedef struct MlirLinalgContractionDimensions MlirLinalgContractionDimensions
typedef struct MlirLinalgConvolutionDimensions MlirLinalgConvolutionDimensions
Functions
MLIR_CAPI_EXPORTED void mlirLinalgFillBuiltinNamedOpRegion (MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
MLIR_CAPI_EXPORTED bool mlirLinalgIsAContractionOp (MlirOperation op)
MLIR_CAPI_EXPORTED MlirLinalgContractionDimensions mlirLinalgInferContractionDimensions (MlirOperation op)
MLIR_CAPI_EXPORTED MlirLinalgContractionDimensions mlirLinalgInferContractionDimensionsFromMaps (const MlirAffineMap *indexingMaps, size_t numMaps)
MLIR_CAPI_EXPORTED bool mlirLinalgIsAConvolutionOp (MlirOperation op)
MLIR_CAPI_EXPORTED MlirLinalgConvolutionDimensions mlirLinalgInferConvolutionDimensions (MlirOperation op)
MLIR_CAPI_EXPORTED MlirAttribute mlirLinalgGetIndexingMapsAttribute (MlirOperation op)
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Linalg, linalg)
Typedef Documentation
MlirLinalgContractionDimensions
typedef struct MlirLinalgContractionDimensions MlirLinalgContractionDimensions
MlirLinalgConvolutionDimensions
typedef struct MlirLinalgConvolutionDimensions MlirLinalgConvolutionDimensions
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Linalg , linalg)
mlirLinalgFillBuiltinNamedOpRegion()
MLIR_CAPI_EXPORTED void mlirLinalgFillBuiltinNamedOpRegion (MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
Assert that mlirOp is a builtin named Linalg op.
Assert that op is a builtin named Linalg op.
Definition at line 19 of file Linalg.cpp.
References b, mlir::Operation::getAttrs(), mlir::Region::getBlocks(), mlir::Operation::getContext(), mlir::getElementTypeOrSelf(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::OperationName::getStringRef(), and unwrap().
Referenced by populateDialectLinalgSubmodule().
mlirLinalgGetIndexingMapsAttribute()
MLIR_CAPI_EXPORTED MlirAttribute mlirLinalgGetIndexingMapsAttribute (MlirOperation op)
Definition at line 156 of file Linalg.cpp.
References ArrayAttr(), unwrap(), and wrap().
Referenced by populateDialectLinalgSubmodule().
mlirLinalgInferContractionDimensions()
MLIR_CAPI_EXPORTED MlirLinalgContractionDimensions mlirLinalgInferContractionDimensions (MlirOperation op)
Definition at line 52 of file Linalg.cpp.
References mlir::linalg::ContractionDimensions::batch, mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::linalg::inferContractionDims(), mlir::linalg::ContractionDimensions::k, mlir::linalg::ContractionDimensions::m, mlir::linalg::ContractionDimensions::n, result, unwrap(), and wrap().
Referenced by InferContractionDimensions().
mlirLinalgInferContractionDimensionsFromMaps()
MLIR_CAPI_EXPORTED MlirLinalgContractionDimensions mlirLinalgInferContractionDimensionsFromMaps (const MlirAffineMap * indexingMaps, size_t numMaps)
Definition at line 79 of file Linalg.cpp.
References mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::linalg::inferContractionDims(), result, unwrap(), and wrap().
Referenced by populateDialectLinalgSubmodule().
mlirLinalgInferConvolutionDimensions()
MLIR_CAPI_EXPORTED MlirLinalgConvolutionDimensions mlirLinalgInferConvolutionDimensions (MlirOperation op)
Definition at line 119 of file Linalg.cpp.
References mlir::linalg::ConvolutionDimensions::batch, mlir::linalg::ConvolutionDimensions::depth, mlir::linalg::ConvolutionDimensions::dilations, mlir::linalg::ConvolutionDimensions::filterLoop, mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::detail::DenseArrayAttrImpl< int64_t >::get(), mlir::linalg::inferConvolutionDims(), mlir::linalg::ConvolutionDimensions::inputChannel, mlir::linalg::ConvolutionDimensions::outputChannel, mlir::linalg::ConvolutionDimensions::outputImage, result, mlir::linalg::ConvolutionDimensions::strides, unwrap(), and wrap().
Referenced by InferConvolutionDimensions().
mlirLinalgIsAContractionOp()
MLIR_CAPI_EXPORTED bool mlirLinalgIsAContractionOp (MlirOperation op)
Definition at line 45 of file Linalg.cpp.
References mlir::linalg::isaContractionOpInterface(), MLIR_CAPI_EXPORTED, and unwrap().
Referenced by populateDialectLinalgSubmodule().
mlirLinalgIsAConvolutionOp()
MLIR_CAPI_EXPORTED bool mlirLinalgIsAConvolutionOp (MlirOperation op)
Definition at line 110 of file Linalg.cpp.
References mlir::linalg::isaConvolutionOpInterface(), MLIR_CAPI_EXPORTED, and unwrap().
Referenced by populateDialectLinalgSubmodule().