MLIR: lib/Tools/mlir-tblgen/MlirTblgenMain.cpp File Reference
MlirTblgenMain.cpp File Reference
#include "mlir/Tools/mlir-tblgen/MlirTblgenMain.h"
#include "mlir/TableGen/GenInfo.h"
#include "mlir/TableGen/GenNameParser.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/Signals.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Main.h"
#include "llvm/TableGen/Record.h"
Enumerations
enum DeprecatedAction { None , Warn , Error }
Functions
static bool findUse (const Init *field, const Init *deprecatedInit, llvm::DenseMap< const Init *, bool > &known)
static bool findUse (Record &record, const Init *deprecatedInit, llvm::DenseMap< const Init *, bool > &known)
static void warnOfDeprecatedUses (const RecordKeeper &records)
static bool mlirTableGenMain (raw_ostream &os, const RecordKeeper &records)
Variables
static DeprecatedAction actionOnDeprecatedValue
static const mlir::GenInfo * generator
Enumeration Type Documentation
DeprecatedAction
enum DeprecatedAction
Enumerator
None
Warn
Error
Definition at line 27 of file MlirTblgenMain.cpp.
Function Documentation
findUse() [1/2]
bool findUse (const Init * field, const Init * deprecatedInit, llvm::DenseMap< const Init *, bool > & known) static
Definition at line 32 of file MlirTblgenMain.cpp.
References findUse().
Referenced by findUse(), and warnOfDeprecatedUses().
findUse() [2/2]
bool findUse (Record & record, const Init * deprecatedInit, llvm::DenseMap< const Init *, bool > & known) static
Definition at line 85 of file MlirTblgenMain.cpp.
mlirTableGenMain()
bool mlirTableGenMain (raw_ostream & os, const RecordKeeper & records) static
Definition at line 128 of file MlirTblgenMain.cpp.
References actionOnDeprecatedValue, generator, None, and warnOfDeprecatedUses().
Referenced by mlir::MlirTblgenMain().
warnOfDeprecatedUses()
void warnOfDeprecatedUses (const RecordKeeper & records) static
Definition at line 92 of file MlirTblgenMain.cpp.
References actionOnDeprecatedValue, Error, and findUse().
Referenced by mlirTableGenMain().
Variable Documentation
actionOnDeprecatedValue
DeprecatedAction actionOnDeprecatedValue static
Definition at line 29 of file MlirTblgenMain.cpp.
Referenced by mlirTableGenMain(), mlir::MlirTblgenMain(), and warnOfDeprecatedUses().
generator
const mlir::GenInfo* generator static
Definition at line 124 of file MlirTblgenMain.cpp.
Referenced by mlir::GenInfo::invoke(), mlirTableGenMain(), and mlir::MlirTblgenMain().