MLIR: lib/Tools/mlir-reduce/MlirReduceMain.cpp File Reference
MlirReduceMain.cpp File Reference
#include "mlir/Tools/mlir-reduce/MlirReduceMain.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Reducer/Passes.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
static LogicalResult loadModule (MLIRContext &context, OwningOpRef< ModuleOp > &module, StringRef inputFilename)
Function Documentation
loadModule()
static LogicalResult loadModule (MLIRContext & context, OwningOpRef< ModuleOp > & module, StringRef inputFilename) static
Definition at line 31 of file MlirReduceMain.cpp.
References mlir::failure(), mlir::parseSourceFile(), and mlir::success().
Referenced by mlir::mlirReduceMain().