MLIR: include/mlir-c/Dialect/Quant.h File Reference
Quant.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (quant, quant)
MLIR_CAPI_EXPORTED bool mlirTypeIsAQuantizedType (MlirType type)
Returns true if the given type is a quantization dialect type.
MLIR_CAPI_EXPORTED unsigned mlirQuantizedTypeGetSignedFlag (void)
Returns the bit flag used to indicate signedness of a quantized type.
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetDefaultMinimumForInteger (bool isSigned, unsigned integralWidth)
Returns the minimum possible value stored by a quantized type.
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetDefaultMaximumForInteger (bool isSigned, unsigned integralWidth)
Returns the maximum possible value stored by a quantized type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeGetExpressedType (MlirType type)
Gets the original type approximated by the given quantized type.
MLIR_CAPI_EXPORTED unsigned mlirQuantizedTypeGetFlags (MlirType type)
Gets the flags associated with the given quantized type.
MLIR_CAPI_EXPORTED bool mlirQuantizedTypeIsSigned (MlirType type)
Returns true if the given type is signed, false otherwise.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeGetStorageType (MlirType type)
Returns the underlying type used to store the values.
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetStorageTypeMin (MlirType type)
Returns the minimum value that the storage type of the given quantized type can take.
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetStorageTypeMax (MlirType type)
Returns the maximum value that the storage type of the given quantized type can take.
MLIR_CAPI_EXPORTED unsigned mlirQuantizedTypeGetStorageTypeIntegralWidth (MlirType type)
Returns the integral bitwidth that the storage type of the given quantized type can represent exactly.
MLIR_CAPI_EXPORTED bool mlirQuantizedTypeIsCompatibleExpressedType (MlirType type, MlirType candidate)
Returns true if the candidate type is compatible with the given quantized type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeGetQuantizedElementType (MlirType type)
Returns the element type of the given quantized type as another quantized type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastFromStorageType (MlirType type, MlirType candidate)
Casts from a type based on the storage type of the given type to a corresponding type based on the given type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastToStorageType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the storage type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastFromExpressedType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given type to a corresponding type based on the given type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastToExpressedType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the expressed type.
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastExpressedToStorageType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given quantized type to equivalent type based on storage type of the same quantized type.
MLIR_CAPI_EXPORTED bool mlirTypeIsAAnyQuantizedType (MlirType type)
Returns true if the given type is an AnyQuantizedType.
MLIR_CAPI_EXPORTED MlirType mlirAnyQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of AnyQuantizedType with the given parameters in the same context as storageType and returns it.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUniformQuantizedType (MlirType type)
Returns true if the given type is a UniformQuantizedType.
MLIR_CAPI_EXPORTED MlirType mlirUniformQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedType with the given parameters in the same context as storageType and returns it.
MLIR_CAPI_EXPORTED double mlirUniformQuantizedTypeGetScale (MlirType type)
Returns the scale of the given uniform quantized type.
MLIR_CAPI_EXPORTED int64_t mlirUniformQuantizedTypeGetZeroPoint (MlirType type)
Returns the zero point of the given uniform quantized type.
MLIR_CAPI_EXPORTED bool mlirUniformQuantizedTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized type is fixed-point.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUniformQuantizedPerAxisType (MlirType type)
Returns true if the given type is a UniformQuantizedPerAxisType.
MLIR_CAPI_EXPORTED MlirType mlirUniformQuantizedPerAxisTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, intptr_t nDims, double *scales, int64_t *zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedPerAxisType with the given parameters in the same context as storageType and returns it.
MLIR_CAPI_EXPORTED intptr_t mlirUniformQuantizedPerAxisTypeGetNumDims (MlirType type)
Returns the number of axes in the given quantized per-axis type.
MLIR_CAPI_EXPORTED double mlirUniformQuantizedPerAxisTypeGetScale (MlirType type, intptr_t pos)
Returns pos-th scale of the given quantized per-axis type.
MLIR_CAPI_EXPORTED int64_t mlirUniformQuantizedPerAxisTypeGetZeroPoint (MlirType type, intptr_t pos)
Returns pos-th zero point of the given quantized per-axis type.
MLIR_CAPI_EXPORTED int32_t mlirUniformQuantizedPerAxisTypeGetQuantizedDimension (MlirType type)
Returns the index of the quantized dimension in the given quantized per-axis type.
MLIR_CAPI_EXPORTED bool mlirUniformQuantizedPerAxisTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized per-axis type is fixed-point.
MLIR_CAPI_EXPORTED bool mlirTypeIsAUniformQuantizedSubChannelType (MlirType type)
Returns true if the given type is a UniformQuantizedSubChannel.
MLIR_CAPI_EXPORTED MlirType mlirUniformQuantizedSubChannelTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, MlirAttribute scalesAttr, MlirAttribute zeroPointsAttr, intptr_t blockSizeInfoLength, int32_t *quantizedDimensions, int64_t *blockSizes, int64_t storageTypeMin, int64_t storageTypeMax)
Creates a UniformQuantizedSubChannelType with the given parameters.
MLIR_CAPI_EXPORTED intptr_t mlirUniformQuantizedSubChannelTypeGetNumBlockSizes (MlirType type)
Returns the number of block sizes provided in type.
MLIR_CAPI_EXPORTED int32_t mlirUniformQuantizedSubChannelTypeGetQuantizedDimension (MlirType type, intptr_t pos)
Returns the quantized dimension at the given position.
MLIR_CAPI_EXPORTED int64_t mlirUniformQuantizedSubChannelTypeGetBlockSize (MlirType type, intptr_t pos)
Returns the block size at the given position.
MLIR_CAPI_EXPORTED MlirAttribute mlirUniformQuantizedSubChannelTypeGetScales (MlirType type)
Returns the scales of the quantized type.
MLIR_CAPI_EXPORTED MlirAttribute mlirUniformQuantizedSubChannelTypeGetZeroPoints (MlirType type)
Returns the zero-points of the quantized type.
MLIR_CAPI_EXPORTED bool mlirTypeIsACalibratedQuantizedType (MlirType type)
Returns true if the given type is a CalibratedQuantizedType.
MLIR_CAPI_EXPORTED MlirType mlirCalibratedQuantizedTypeGet (MlirType expressedType, double min, double max)
Creates an instance of CalibratedQuantizedType with the given parameters in the same context as expressedType and returns it.
MLIR_CAPI_EXPORTED double mlirCalibratedQuantizedTypeGetMin (MlirType type)
Returns the min value of the given calibrated quantized type.
MLIR_CAPI_EXPORTED double mlirCalibratedQuantizedTypeGetMax (MlirType type)
Returns the max value of the given calibrated quantized type.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (quant , quant)
mlirAnyQuantizedTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirAnyQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of AnyQuantizedType with the given parameters in the same context as storageType and returns it.
The instance is owned by the context.
Definition at line 116 of file Quant.cpp.
References mlir::quant::AnyQuantizedType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirCalibratedQuantizedTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirCalibratedQuantizedTypeGet (MlirType expressedType, double min, double max)
Creates an instance of CalibratedQuantizedType with the given parameters in the same context as expressedType and returns it.
The instance is owned by the context.
Definition at line 261 of file Quant.cpp.
References mlir::quant::CalibratedQuantizedType::get(), max(), min(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirCalibratedQuantizedTypeGetMax()
MLIR_CAPI_EXPORTED double mlirCalibratedQuantizedTypeGetMax (MlirType type)
Returns the max value of the given calibrated quantized type.
Definition at line 271 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirCalibratedQuantizedTypeGetMin()
MLIR_CAPI_EXPORTED double mlirCalibratedQuantizedTypeGetMin (MlirType type)
Returns the min value of the given calibrated quantized type.
Definition at line 267 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastExpressedToStorageType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastExpressedToStorageType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given quantized type to equivalent type based on storage type of the same quantized type.
Definition at line 102 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastFromExpressedType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastFromExpressedType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given type to a corresponding type based on the given type.
Returns a null type if the cast is not valid.
Definition at line 92 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastFromStorageType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastFromStorageType (MlirType type, MlirType candidate)
Casts from a type based on the storage type of the given type to a corresponding type based on the given type.
Returns a null type if the cast is not valid.
Definition at line 81 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastToExpressedType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastToExpressedType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the expressed type.
Returns a null type if the cast is not valid.
Definition at line 98 of file Quant.cpp.
References mlir::quant::QuantizedType::castToExpressedType(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastToStorageType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeCastToStorageType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the storage type.
Returns a null type if the cast is not valid.
Definition at line 87 of file Quant.cpp.
References mlir::quant::QuantizedType::castToStorageType(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetDefaultMaximumForInteger()
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetDefaultMaximumForInteger (bool isSigned, unsigned integralWidth)
Returns the maximum possible value stored by a quantized type.
Definition at line 37 of file Quant.cpp.
References mlir::quant::QuantizedType::getDefaultMaximumForInteger().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetDefaultMinimumForInteger()
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetDefaultMinimumForInteger (bool isSigned, unsigned integralWidth)
Returns the minimum possible value stored by a quantized type.
Definition at line 31 of file Quant.cpp.
References mlir::quant::QuantizedType::getDefaultMinimumForInteger().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetExpressedType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeGetExpressedType (MlirType type)
Gets the original type approximated by the given quantized type.
Definition at line 43 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetFlags()
MLIR_CAPI_EXPORTED unsigned mlirQuantizedTypeGetFlags (MlirType type)
Gets the flags associated with the given quantized type.
Definition at line 47 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetQuantizedElementType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeGetQuantizedElementType (MlirType type)
Returns the element type of the given quantized type as another quantized type.
Definition at line 77 of file Quant.cpp.
References mlir::quant::QuantizedType::getQuantizedElementType(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetSignedFlag()
MLIR_CAPI_EXPORTED unsigned mlirQuantizedTypeGetSignedFlag (void)
Returns the bit flag used to indicate signedness of a quantized type.
Definition at line 27 of file Quant.cpp.
References mlir::quant::QuantizationFlags::Signed.
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageType()
MLIR_CAPI_EXPORTED MlirType mlirQuantizedTypeGetStorageType (MlirType type)
Returns the underlying type used to store the values.
Definition at line 55 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageTypeIntegralWidth()
MLIR_CAPI_EXPORTED unsigned mlirQuantizedTypeGetStorageTypeIntegralWidth (MlirType type)
Returns the integral bitwidth that the storage type of the given quantized type can represent exactly.
Definition at line 67 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageTypeMax()
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetStorageTypeMax (MlirType type)
Returns the maximum value that the storage type of the given quantized type can take.
Definition at line 63 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageTypeMin()
MLIR_CAPI_EXPORTED int64_t mlirQuantizedTypeGetStorageTypeMin (MlirType type)
Returns the minimum value that the storage type of the given quantized type can take.
Definition at line 59 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeIsCompatibleExpressedType()
MLIR_CAPI_EXPORTED bool mlirQuantizedTypeIsCompatibleExpressedType (MlirType type, MlirType candidate)
Returns true if the candidate type is compatible with the given quantized type.
Definition at line 71 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeIsSigned()
MLIR_CAPI_EXPORTED bool mlirQuantizedTypeIsSigned (MlirType type)
Returns true if the given type is signed, false otherwise.
Definition at line 51 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAAnyQuantizedType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAAnyQuantizedType (MlirType type)
Returns true if the given type is an AnyQuantizedType.
Definition at line 112 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsACalibratedQuantizedType()
MLIR_CAPI_EXPORTED bool mlirTypeIsACalibratedQuantizedType (MlirType type)
Returns true if the given type is a CalibratedQuantizedType.
Definition at line 257 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAQuantizedType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAQuantizedType (MlirType type)
Returns true if the given type is a quantization dialect type.
Definition at line 23 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAUniformQuantizedPerAxisType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUniformQuantizedPerAxisType (MlirType type)
Returns true if the given type is a UniformQuantizedPerAxisType.
Definition at line 157 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAUniformQuantizedSubChannelType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUniformQuantizedSubChannelType (MlirType type)
Returns true if the given type is a UniformQuantizedSubChannel.
Definition at line 202 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAUniformQuantizedType()
MLIR_CAPI_EXPORTED bool mlirTypeIsAUniformQuantizedType (MlirType type)
Returns true if the given type is a UniformQuantizedType.
Definition at line 128 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUniformQuantizedPerAxisTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, intptr_t nDims, double * scales, int64_t * zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedPerAxisType with the given parameters in the same context as storageType and returns it.
scales and zeroPoints point to nDims number of elements. The instance is owned by the context.
Definition at line 161 of file Quant.cpp.
References mlir::quant::UniformQuantizedPerAxisType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetNumDims()
MLIR_CAPI_EXPORTED intptr_t mlirUniformQuantizedPerAxisTypeGetNumDims (MlirType type)
Returns the number of axes in the given quantized per-axis type.
Definition at line 172 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetQuantizedDimension()
MLIR_CAPI_EXPORTED int32_t mlirUniformQuantizedPerAxisTypeGetQuantizedDimension (MlirType type)
Returns the index of the quantized dimension in the given quantized per-axis type.
Definition at line 189 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetScale()
MLIR_CAPI_EXPORTED double mlirUniformQuantizedPerAxisTypeGetScale (MlirType type, intptr_t pos)
Returns pos-th scale of the given quantized per-axis type.
Definition at line 178 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetZeroPoint()
MLIR_CAPI_EXPORTED int64_t mlirUniformQuantizedPerAxisTypeGetZeroPoint (MlirType type, intptr_t pos)
Returns pos-th zero point of the given quantized per-axis type.
Definition at line 183 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeIsFixedPoint()
MLIR_CAPI_EXPORTED bool mlirUniformQuantizedPerAxisTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized per-axis type is fixed-point.
Definition at line 194 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUniformQuantizedSubChannelTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, MlirAttribute scalesAttr, MlirAttribute zeroPointsAttr, intptr_t blockSizeInfoLength, int32_t * quantizedDimensions, int64_t * blockSizes, int64_t storageTypeMin, int64_t storageTypeMax)
Creates a UniformQuantizedSubChannelType with the given parameters.
The type is owned by the context. scalesAttr and zeroPointsAttr must be DenseElementsAttrs. quantizedDimensions and blockSizes point to blockSizeInfoLength number of elements, describing respectively the quantization axis and corresponding block size.
Definition at line 206 of file Quant.cpp.
References mlir::quant::UniformQuantizedSubChannelType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetBlockSize()
MLIR_CAPI_EXPORTED int64_t mlirUniformQuantizedSubChannelTypeGetBlockSize (MlirType type, intptr_t pos)
Returns the block size at the given position.
Definition at line 237 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetNumBlockSizes()
MLIR_CAPI_EXPORTED intptr_t mlirUniformQuantizedSubChannelTypeGetNumBlockSizes (MlirType type)
Returns the number of block sizes provided in type.
Definition at line 225 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetQuantizedDimension()
MLIR_CAPI_EXPORTED int32_t mlirUniformQuantizedSubChannelTypeGetQuantizedDimension (MlirType type, intptr_t pos)
Returns the quantized dimension at the given position.
Definition at line 231 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetScales()
MLIR_CAPI_EXPORTED MlirAttribute mlirUniformQuantizedSubChannelTypeGetScales (MlirType type)
Returns the scales of the quantized type.
Definition at line 243 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetZeroPoints()
MLIR_CAPI_EXPORTED MlirAttribute mlirUniformQuantizedSubChannelTypeGetZeroPoints (MlirType type)
Returns the zero-points of the quantized type.
Definition at line 248 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirUniformQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedType with the given parameters in the same context as storageType and returns it.
The instance is owned by the context.
Definition at line 132 of file Quant.cpp.
References mlir::quant::UniformQuantizedType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeGetScale()
MLIR_CAPI_EXPORTED double mlirUniformQuantizedTypeGetScale (MlirType type)
Returns the scale of the given uniform quantized type.
Definition at line 141 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeGetZeroPoint()
MLIR_CAPI_EXPORTED int64_t mlirUniformQuantizedTypeGetZeroPoint (MlirType type)
Returns the zero point of the given uniform quantized type.
Definition at line 145 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeIsFixedPoint()
MLIR_CAPI_EXPORTED bool mlirUniformQuantizedTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized type is fixed-point.
Definition at line 149 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().