MLIR: include/mlir-c/Dialect/LLVM.h File Reference
LLVM.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Dialect/LLVMIR/Transforms/Passes.capi.h.inc"
Macros
#define MLIR_CAPI_DWARF_ADDRESS_SPACE_NULL -1
Constant to represent std::nullopt for dwarfAddressSpace to omit the field.
Typedefs
typedef enum MlirLLVMCConv MlirLLVMCConv
typedef enum MlirLLVMComdat MlirLLVMComdat
typedef enum MlirLLVMLinkage MlirLLVMLinkage
typedef enum MlirLLVMTypeEncoding MlirLLVMTypeEncoding
typedef enum MlirLLVMDIEmissionKind MlirLLVMDIEmissionKind
typedef enum MlirLLVMDINameTableKind MlirLLVMDINameTableKind
Enumerations
enum MlirLLVMCConv {
MlirLLVMCConvC = 0 , MlirLLVMCConvFast = 8 , MlirLLVMCConvCold = 9 , MlirLLVMCConvGHC = 10 ,
MlirLLVMCConvHiPE = 11 , MlirLLVMCConvAnyReg = 13 , MlirLLVMCConvPreserveMost = 14 , MlirLLVMCConvPreserveAll = 15 ,
MlirLLVMCConvSwift = 16 , MlirLLVMCConvCXX_FAST_TLS = 17 , MlirLLVMCConvTail = 18 , MlirLLVMCConvCFGuard_Check = 19 ,
MlirLLVMCConvSwiftTail = 20 , MlirLLVMCConvX86_StdCall = 64 , MlirLLVMCConvX86_FastCall = 65 , MlirLLVMCConvARM_APCS = 66 ,
MlirLLVMCConvARM_AAPCS = 67 , MlirLLVMCConvARM_AAPCS_VFP = 68 , MlirLLVMCConvMSP430_INTR = 69 , MlirLLVMCConvX86_ThisCall = 70 ,
MlirLLVMCConvPTX_Kernel = 71 , MlirLLVMCConvPTX_Device = 72 , MlirLLVMCConvSPIR_FUNC = 75 , MlirLLVMCConvSPIR_KERNEL = 76 ,
MlirLLVMCConvIntel_OCL_BI = 77 , MlirLLVMCConvX86_64_SysV = 78 , MlirLLVMCConvWin64 = 79 , MlirLLVMCConvX86_VectorCall = 80 ,
MlirLLVMCConvDUMMY_HHVM = 81 , MlirLLVMCConvDUMMY_HHVM_C = 82 , MlirLLVMCConvX86_INTR = 83 , MlirLLVMCConvAVR_INTR = 84 ,
MlirLLVMCConvAVR_BUILTIN = 86 , MlirLLVMCConvAMDGPU_VS = 87 , MlirLLVMCConvAMDGPU_GS = 88 , MlirLLVMCConvAMDGPU_CS = 90 ,
MlirLLVMCConvAMDGPU_KERNEL = 91 , MlirLLVMCConvX86_RegCall = 92 , MlirLLVMCConvAMDGPU_HS = 93 , MlirLLVMCConvMSP430_BUILTIN = 94 ,
MlirLLVMCConvAMDGPU_LS = 95 , MlirLLVMCConvAMDGPU_ES = 96 , MlirLLVMCConvAArch64_VectorCall = 97 , MlirLLVMCConvAArch64_SVE_VectorCall = 98 ,
MlirLLVMCConvWASM_EmscriptenInvoke = 99 , MlirLLVMCConvAMDGPU_Gfx = 100 , MlirLLVMCConvM68k_INTR = 101
}
enum MlirLLVMComdat {
MlirLLVMComdatAny = 0 , MlirLLVMComdatExactMatch = 1 , MlirLLVMComdatLargest = 2 , MlirLLVMComdatNoDeduplicate = 3 ,
MlirLLVMComdatSameSize = 4
}
enum MlirLLVMLinkage {
MlirLLVMLinkageExternal = 0 , MlirLLVMLinkageAvailableExternally = 1 , MlirLLVMLinkageLinkonce = 2 , MlirLLVMLinkageLinkonceODR = 3 ,
MlirLLVMLinkageWeak = 4 , MlirLLVMLinkageWeakODR = 5 , MlirLLVMLinkageAppending = 6 , MlirLLVMLinkageInternal = 7 ,
MlirLLVMLinkagePrivate = 8 , MlirLLVMLinkageExternWeak = 9 , MlirLLVMLinkageCommon = 10
}
enum MlirLLVMTypeEncoding {
MlirLLVMTypeEncodingAddress = 0x1 , MlirLLVMTypeEncodingBoolean = 0x2 , MlirLLVMTypeEncodingComplexFloat = 0x31 , MlirLLVMTypeEncodingFloatT = 0x4 ,
MlirLLVMTypeEncodingSigned = 0x5 , MlirLLVMTypeEncodingSignedChar = 0x6 , MlirLLVMTypeEncodingUnsigned = 0x7 , MlirLLVMTypeEncodingUnsignedChar = 0x08 ,
MlirLLVMTypeEncodingImaginaryFloat = 0x09 , MlirLLVMTypeEncodingPackedDecimal = 0x0a , MlirLLVMTypeEncodingNumericString = 0x0b , MlirLLVMTypeEncodingEdited = 0x0c ,
MlirLLVMTypeEncodingSignedFixed = 0x0d , MlirLLVMTypeEncodingUnsignedFixed = 0x0e , MlirLLVMTypeEncodingDecimalFloat = 0x0f , MlirLLVMTypeEncodingUTF = 0x10 ,
MlirLLVMTypeEncodingUCS = 0x11 , MlirLLVMTypeEncodingASCII = 0x12 , MlirLLVMTypeEncodingLoUser = 0x80 , MlirLLVMTypeEncodingHiUser = 0xff
}
enum MlirLLVMDIEmissionKind { MlirLLVMDIEmissionKindNone = 0 , MlirLLVMDIEmissionKindFull = 1 , MlirLLVMDIEmissionKindLineTablesOnly = 2 , MlirLLVMDIEmissionKindDebugDirectivesOnly = 3 }
enum MlirLLVMDINameTableKind { MlirLLVMDINameTableKindDefault = 0 , MlirLLVMDINameTableKindGNU = 1 , MlirLLVMDINameTableKindNone = 2 , MlirLLVMDINameTableKindApple = 3 }
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (LLVM, llvm)
MLIR_CAPI_EXPORTED MlirType mlirLLVMPointerTypeGet (MlirContext ctx, unsigned addressSpace)
Creates an llvm.ptr type.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMPointerTypeGetName (void)
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMPointerTypeGetTypeID (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMPointerType (MlirType type)
Returns true if the type is an LLVM dialect pointer type.
MLIR_CAPI_EXPORTED unsigned mlirLLVMPointerTypeGetAddressSpace (MlirType pointerType)
Returns address space of llvm.ptr.
MLIR_CAPI_EXPORTED MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMVoidTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMArrayType (MlirType type)
Returns true if the type is an LLVM dialect array type.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMArrayTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMArrayTypeGetName (void)
MLIR_CAPI_EXPORTED MlirType mlirLLVMArrayTypeGetElementType (MlirType type)
Returns the element type of the llvm.array type.
MLIR_CAPI_EXPORTED unsigned mlirLLVMArrayTypeGetNumElements (MlirType type)
Returns the number of elements in the llvm.array type.
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const *argumentTypes, bool isVarArg)
Creates an llvm.func type.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMFunctionTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMFunctionType (MlirType type)
Returns true if the type is an LLVM dialect function type.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMFunctionTypeGetTypeID (void)
Returns the TypeID of an LLVM function type.
MLIR_CAPI_EXPORTED intptr_t mlirLLVMFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
MLIR_CAPI_EXPORTED bool mlirLLVMFunctionTypeIsVarArg (MlirType type)
Returns true if the function type is variadic.
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGetReturnType (MlirType type)
Returns the return type of the function type.
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMStructType (MlirType type)
Returns true if the type is an LLVM dialect struct type.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMStructTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMStructTypeGetName (void)
MLIR_CAPI_EXPORTED bool mlirLLVMStructTypeIsLiteral (MlirType type)
Returns true if the type is a literal (unnamed) LLVM struct type.
MLIR_CAPI_EXPORTED intptr_t mlirLLVMStructTypeGetNumElementTypes (MlirType type)
Returns the number of fields in the struct.
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeGetElementType (MlirType type, intptr_t position)
Returns the positions-th field of the struct.
MLIR_CAPI_EXPORTED bool mlirLLVMStructTypeIsPacked (MlirType type)
Returns true if the struct is packed.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMStructTypeGetIdentifier (MlirType type)
Returns the identifier of the identified struct.
MLIR_CAPI_EXPORTED bool mlirLLVMStructTypeIsOpaque (MlirType type)
Returns true is the struct is explicitly opaque (will not have a body) or uninitialized (will eventually have a body).
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeLiteralGetChecked (MlirLocation loc, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type if possible.
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeIdentifiedGet (MlirContext ctx, MlirStringRef name)
Creates an LLVM identified struct type with no body.
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeIdentifiedNewGet (MlirContext ctx, MlirStringRef name, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM identified struct type with no body and a name starting with the given prefix.
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeOpaqueGet (MlirContext ctx, MlirStringRef name)
MLIR_CAPI_EXPORTED MlirLogicalResult mlirLLVMStructTypeSetBody (MlirType structType, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Sets the body of the identified struct if it hasn't been set yet.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMCConvAttrGet (MlirContext ctx, MlirLLVMCConv cconv)
Creates a LLVM CConv attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMCConvAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMComdatAttrGet (MlirContext ctx, MlirLLVMComdat comdat)
Creates a LLVM Comdat attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMComdatAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMLinkageAttrGet (MlirContext ctx, MlirLLVMLinkage linkage)
Creates a LLVM Linkage attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMLinkageAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDINullTypeAttrGet (MlirContext ctx)
Creates a LLVM DINullType attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDINullTypeAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIExpressionElemAttrGet (MlirContext ctx, unsigned int opcode, intptr_t nArguments, uint64_t const *arguments)
Creates a LLVM DIExpressionElem attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIExpressionElemAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIExpressionAttrGet (MlirContext ctx, intptr_t nOperations, MlirAttribute const *operations)
Creates a LLVM DIExpression attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIExpressionAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIBasicTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, MlirLLVMTypeEncoding encoding)
Creates a LLVM DIBasicType attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIBasicTypeAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompositeTypeAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompositeType attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompositeTypeAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, int64_t flags, uint64_t sizeInBits, uint64_t alignInBits, intptr_t nElements, MlirAttribute const *elements, MlirAttribute dataLocation, MlirAttribute rank, MlirAttribute allocated, MlirAttribute associated, MlirAttribute identifier, MlirAttribute discriminator)
Creates a LLVM DICompositeType attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDICompositeTypeAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIDerivedTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, uint64_t sizeInBits, uint32_t alignInBits, uint64_t offsetInBits, int64_t dwarfAddressSpace, int64_t flags, MlirAttribute extraData)
Creates a LLVM DIDerivedType attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIDerivedTypeAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIStringTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, uint32_t alignInBits, MlirAttribute stringLength, MlirAttribute stringLengthExp, MlirAttribute stringLocationExp, MlirLLVMTypeEncoding encoding)
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIStringTypeAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIDerivedTypeAttrGetBaseType (MlirAttribute diDerivedType)
Gets the base type from a LLVM DIDerivedType attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIFileAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute directory)
Creates a LLVM DIFileAttr attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIFileAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompileUnitAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompileUnitAttr attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompileUnitAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, unsigned int sourceLanguage, MlirAttribute file, MlirAttribute producer, bool isOptimized, MlirLLVMDIEmissionKind emissionKind, bool isDebugInfoForProfiling, MlirLLVMDINameTableKind nameTableKind, MlirAttribute splitDebugFilename, intptr_t nImportedEntities, MlirAttribute const *importedEntities)
Creates a LLVM DICompileUnit attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDICompileUnitAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIFlagsAttrGet (MlirContext ctx, uint64_t value)
Creates a LLVM DIFlags attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIFlagsAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDILexicalBlockAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int line, unsigned int column)
Creates a LLVM DILexicalBlock attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDILexicalBlockAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDILexicalBlockFileAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int discriminator)
Creates a LLVM DILexicalBlockFile attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDILexicalBlockFileAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDILocalVariableAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute name, MlirAttribute diFile, unsigned int line, unsigned int arg, unsigned int alignInBits, MlirAttribute diType, int64_t flags)
Creates a LLVM DILocalVariableAttr attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDILocalVariableAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DISubprogramAttr attribute.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, MlirAttribute compileUnit, MlirAttribute scope, MlirAttribute name, MlirAttribute linkageName, MlirAttribute file, unsigned int line, unsigned int scopeLine, uint64_t subprogramFlags, MlirAttribute type, intptr_t nRetainedNodes, MlirAttribute const *retainedNodes, intptr_t nAnnotations, MlirAttribute const *annotations)
Creates a LLVM DISubprogramAttr attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDISubprogramAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIAnnotationAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute value)
Creates a LLVM DIAnnotation attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIAnnotationAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetScope (MlirAttribute diSubprogram)
Gets the scope from this DISubprogramAttr.
MLIR_CAPI_EXPORTED unsigned int mlirLLVMDISubprogramAttrGetLine (MlirAttribute diSubprogram)
Gets the line from this DISubprogramAttr.
MLIR_CAPI_EXPORTED unsigned int mlirLLVMDISubprogramAttrGetScopeLine (MlirAttribute diSubprogram)
Gets the scope line from this DISubprogram.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetCompileUnit (MlirAttribute diSubprogram)
Gets the compile unit from this DISubprogram.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetFile (MlirAttribute diSubprogram)
Gets the file from this DISubprogramAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetType (MlirAttribute diSubprogram)
Gets the type from this DISubprogramAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubroutineTypeAttrGet (MlirContext ctx, unsigned int callingConvention, intptr_t nTypes, MlirAttribute const *types)
Creates a LLVM DISubroutineTypeAttr attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDISubroutineTypeAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIModuleAttrGet (MlirContext ctx, MlirAttribute file, MlirAttribute scope, MlirAttribute name, MlirAttribute configMacros, MlirAttribute includePath, MlirAttribute apinotes, unsigned int line, bool isDecl)
Creates a LLVM DIModuleAttr attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIModuleAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIImportedEntityAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute scope, MlirAttribute entity, MlirAttribute file, unsigned int line, MlirAttribute name, intptr_t nElements, MlirAttribute const *elements)
Creates a LLVM DIImportedEntityAttr attribute.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIImportedEntityAttrGetName (void)
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIModuleAttrGetScope (MlirAttribute diModule)
Gets the scope of this DIModuleAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDStringAttrGet (MlirContext ctx, MlirStringRef value)
Creates an LLVM MDStringAttr.
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDStringAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDStringAttr.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDStringAttrGetTypeID (void)
Returns the TypeID of MDStringAttr.
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMMDStringAttrGetValue (MlirAttribute attr)
Returns the string value of an LLVM MDStringAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDConstantAttrGet (MlirContext ctx, MlirAttribute valueAttr)
Creates an LLVM MDConstantAttr wrapping an attribute.
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDConstantAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDConstantAttr.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDConstantAttrGetTypeID (void)
Returns the TypeID of MDConstantAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDConstantAttrGetValue (MlirAttribute attr)
Returns the attribute value of an LLVM MDConstantAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDFuncAttrGet (MlirContext ctx, MlirAttribute name)
Creates an LLVM MDFuncAttr referencing a function symbol.
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDFuncAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDFuncAttr.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDFuncAttrGetTypeID (void)
Returns the TypeID of MDFuncAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDFuncAttrGetName (MlirAttribute attr)
Returns the symbol name of an LLVM MDFuncAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDNodeAttrGet (MlirContext ctx, intptr_t nOperands, MlirAttribute const *operands)
Creates an LLVM MDNodeAttr.
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDNodeAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDNodeAttr.
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDNodeAttrGetTypeID (void)
Returns the TypeID of MDNodeAttr.
MLIR_CAPI_EXPORTED intptr_t mlirLLVMMDNodeAttrGetNumOperands (MlirAttribute attr)
Returns the number of operands in an LLVM MDNodeAttr.
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDNodeAttrGetOperand (MlirAttribute attr, intptr_t index)
Returns the operand at the given index of an LLVM MDNodeAttr.
Macro Definition Documentation
MLIR_CAPI_DWARF_ADDRESS_SPACE_NULL
#define MLIR_CAPI_DWARF_ADDRESS_SPACE_NULL -1
Constant to represent std::nullopt for dwarfAddressSpace to omit the field.
Definition at line 335 of file LLVM.h.
Typedef Documentation
MlirLLVMCConv
typedef enum MlirLLVMCConv MlirLLVMCConv
Definition at line 203 of file LLVM.h.
MlirLLVMComdat
typedef enum MlirLLVMComdat MlirLLVMComdat
Definition at line 219 of file LLVM.h.
MlirLLVMDIEmissionKind
typedef enum MlirLLVMDIEmissionKind MlirLLVMDIEmissionKind
Definition at line 355 of file LLVM.h.
MlirLLVMDINameTableKind
typedef enum MlirLLVMDINameTableKind MlirLLVMDINameTableKind
Definition at line 364 of file LLVM.h.
MlirLLVMLinkage
typedef enum MlirLLVMLinkage MlirLLVMLinkage
Definition at line 241 of file LLVM.h.
MlirLLVMTypeEncoding
typedef enum MlirLLVMTypeEncoding MlirLLVMTypeEncoding
Definition at line 290 of file LLVM.h.
Enumeration Type Documentation
MlirLLVMCConv
enum MlirLLVMCConv
Enumerator
MlirLLVMCConvC
MlirLLVMCConvFast
MlirLLVMCConvCold
MlirLLVMCConvGHC
MlirLLVMCConvHiPE
MlirLLVMCConvAnyReg
MlirLLVMCConvPreserveMost
MlirLLVMCConvPreserveAll
MlirLLVMCConvSwift
MlirLLVMCConvCXX_FAST_TLS
MlirLLVMCConvTail
MlirLLVMCConvCFGuard_Check
MlirLLVMCConvSwiftTail
MlirLLVMCConvX86_StdCall
MlirLLVMCConvX86_FastCall
MlirLLVMCConvARM_APCS
MlirLLVMCConvARM_AAPCS
MlirLLVMCConvARM_AAPCS_VFP
MlirLLVMCConvMSP430_INTR
MlirLLVMCConvX86_ThisCall
MlirLLVMCConvPTX_Kernel
MlirLLVMCConvPTX_Device
MlirLLVMCConvSPIR_FUNC
MlirLLVMCConvSPIR_KERNEL
MlirLLVMCConvIntel_OCL_BI
MlirLLVMCConvX86_64_SysV
MlirLLVMCConvWin64
MlirLLVMCConvX86_VectorCall
MlirLLVMCConvDUMMY_HHVM
MlirLLVMCConvDUMMY_HHVM_C
MlirLLVMCConvX86_INTR
MlirLLVMCConvAVR_INTR
MlirLLVMCConvAVR_BUILTIN
MlirLLVMCConvAMDGPU_VS
MlirLLVMCConvAMDGPU_GS
MlirLLVMCConvAMDGPU_CS
MlirLLVMCConvAMDGPU_KERNEL
MlirLLVMCConvX86_RegCall
MlirLLVMCConvAMDGPU_HS
MlirLLVMCConvMSP430_BUILTIN
MlirLLVMCConvAMDGPU_LS
MlirLLVMCConvAMDGPU_ES
MlirLLVMCConvAArch64_VectorCall
MlirLLVMCConvAArch64_SVE_VectorCall
MlirLLVMCConvWASM_EmscriptenInvoke
MlirLLVMCConvAMDGPU_Gfx
MlirLLVMCConvM68k_INTR
Definition at line 153 of file LLVM.h.
MlirLLVMComdat
enum MlirLLVMComdat
Enumerator
MlirLLVMComdatAny
MlirLLVMComdatExactMatch
MlirLLVMComdatLargest
MlirLLVMComdatNoDeduplicate
MlirLLVMComdatSameSize
Definition at line 211 of file LLVM.h.
MlirLLVMDIEmissionKind
enum MlirLLVMDIEmissionKind
Enumerator
MlirLLVMDIEmissionKindNone
MlirLLVMDIEmissionKindFull
MlirLLVMDIEmissionKindLineTablesOnly
MlirLLVMDIEmissionKindDebugDirectivesOnly
Definition at line 348 of file LLVM.h.
MlirLLVMDINameTableKind
enum MlirLLVMDINameTableKind
Enumerator
MlirLLVMDINameTableKindDefault
MlirLLVMDINameTableKindGNU
MlirLLVMDINameTableKindNone
MlirLLVMDINameTableKindApple
Definition at line 357 of file LLVM.h.
MlirLLVMLinkage
enum MlirLLVMLinkage
Enumerator
MlirLLVMLinkageExternal
MlirLLVMLinkageAvailableExternally
MlirLLVMLinkageLinkonce
MlirLLVMLinkageLinkonceODR
MlirLLVMLinkageWeak
MlirLLVMLinkageWeakODR
MlirLLVMLinkageAppending
MlirLLVMLinkageInternal
MlirLLVMLinkagePrivate
MlirLLVMLinkageExternWeak
MlirLLVMLinkageCommon
Definition at line 227 of file LLVM.h.
MlirLLVMTypeEncoding
enum MlirLLVMTypeEncoding
Enumerator
MlirLLVMTypeEncodingAddress
MlirLLVMTypeEncodingBoolean
MlirLLVMTypeEncodingComplexFloat
MlirLLVMTypeEncodingFloatT
MlirLLVMTypeEncodingSigned
MlirLLVMTypeEncodingSignedChar
MlirLLVMTypeEncodingUnsigned
MlirLLVMTypeEncodingUnsignedChar
MlirLLVMTypeEncodingImaginaryFloat
MlirLLVMTypeEncodingPackedDecimal
MlirLLVMTypeEncodingNumericString
MlirLLVMTypeEncodingEdited
MlirLLVMTypeEncodingSignedFixed
MlirLLVMTypeEncodingUnsignedFixed
MlirLLVMTypeEncodingDecimalFloat
MlirLLVMTypeEncodingUTF
MlirLLVMTypeEncodingUCS
MlirLLVMTypeEncodingASCII
MlirLLVMTypeEncodingLoUser
MlirLLVMTypeEncodingHiUser
Definition at line 267 of file LLVM.h.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (LLVM , llvm)
References MLIR_CAPI_EXPORTED.
mlirLLVMArrayTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
Definition at line 60 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived().
mlirLLVMArrayTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirLLVMArrayTypeGetElementType (MlirType type)
Returns the element type of the llvm.array type.
Definition at line 68 of file LLVM.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived().
mlirLLVMArrayTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMArrayTypeGetName (void)
Definition at line 64 of file LLVM.cpp.
References wrap().
mlirLLVMArrayTypeGetNumElements()
MLIR_CAPI_EXPORTED unsigned mlirLLVMArrayTypeGetNumElements (MlirType type)
Returns the number of elements in the llvm.array type.
Definition at line 72 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::ArrayType::bindDerived().
mlirLLVMArrayTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMArrayTypeGetTypeID (void)
Definition at line 56 of file LLVM.cpp.
References wrap().
mlirLLVMAttrIsAMDConstantAttr()
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDConstantAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDConstantAttr.
Definition at line 581 of file LLVM.cpp.
References unwrap().
mlirLLVMAttrIsAMDFuncAttr()
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDFuncAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDFuncAttr.
Definition at line 598 of file LLVM.cpp.
References unwrap().
mlirLLVMAttrIsAMDNodeAttr()
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDNodeAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDNodeAttr.
Definition at line 618 of file LLVM.cpp.
References unwrap().
mlirLLVMAttrIsAMDStringAttr()
MLIR_CAPI_EXPORTED bool mlirLLVMAttrIsAMDStringAttr (MlirAttribute attr)
Returns true if the attribute is an LLVM MDStringAttr.
Definition at line 564 of file LLVM.cpp.
References unwrap().
mlirLLVMCConvAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMCConvAttrGet (MlirContext ctx, MlirLLVMCConv cconv)
Creates a LLVM CConv attribute.
Definition at line 320 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMCConvAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMCConvAttrGetName (void)
Definition at line 324 of file LLVM.cpp.
References wrap().
mlirLLVMComdatAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMComdatAttrGet (MlirContext ctx, MlirLLVMComdat comdat)
Creates a LLVM Comdat attribute.
Definition at line 326 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMComdatAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMComdatAttrGetName (void)
Definition at line 330 of file LLVM.cpp.
References wrap().
mlirLLVMDIAnnotationAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIAnnotationAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute value)
Creates a LLVM DIAnnotation attribute.
Definition at line 545 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIAnnotationAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIAnnotationAttrGetName (void)
Definition at line 551 of file LLVM.cpp.
References wrap().
mlirLLVMDIBasicTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIBasicTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, MlirLLVMTypeEncoding encoding)
Creates a LLVM DIBasicType attribute.
Definition at line 232 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIBasicTypeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIBasicTypeAttrGetName (void)
Definition at line 241 of file LLVM.cpp.
References wrap().
mlirLLVMDICompileUnitAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompileUnitAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, unsigned int sourceLanguage, MlirAttribute file, MlirAttribute producer, bool isOptimized, MlirLLVMDIEmissionKind emissionKind, bool isDebugInfoForProfiling, MlirLLVMDINameTableKind nameTableKind, MlirAttribute splitDebugFilename, intptr_t nImportedEntities, MlirAttribute const * importedEntities)
Creates a LLVM DICompileUnit attribute.
Definition at line 352 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDICompileUnitAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDICompileUnitAttrGetName (void)
Definition at line 373 of file LLVM.cpp.
References wrap().
mlirLLVMDICompileUnitAttrGetRecSelf()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompileUnitAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompileUnitAttr attribute.
Definition at line 348 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDICompositeTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompositeTypeAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, int64_t flags, uint64_t sizeInBits, uint64_t alignInBits, intptr_t nElements, MlirAttribute const * elements, MlirAttribute dataLocation, MlirAttribute rank, MlirAttribute allocated, MlirAttribute associated, MlirAttribute identifier, MlirAttribute discriminator)
Creates a LLVM DICompositeType attribute.
Definition at line 250 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDICompositeTypeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDICompositeTypeAttrGetName (void)
Definition at line 276 of file LLVM.cpp.
References wrap().
mlirLLVMDICompositeTypeAttrGetRecSelf()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDICompositeTypeAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DICompositeType attribute.
Definition at line 245 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIDerivedTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIDerivedTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, MlirAttribute file, uint32_t line, MlirAttribute scope, MlirAttribute baseType, uint64_t sizeInBits, uint32_t alignInBits, uint64_t offsetInBits, int64_t dwarfAddressSpace, int64_t flags, MlirAttribute extraData)
Creates a LLVM DIDerivedType attribute.
Note that dwarfAddressSpace is an optional field, where MLIR_CAPI_DWARF_ADDRESS_SPACE_NULL indicates null and non-negative values indicate a value present.
Definition at line 280 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIDerivedTypeAttrGetBaseType()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIDerivedTypeAttrGetBaseType (MlirAttribute diDerivedType)
Gets the base type from a LLVM DIDerivedType attribute.
Definition at line 316 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIDerivedTypeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIDerivedTypeAttrGetName (void)
Definition at line 295 of file LLVM.cpp.
References wrap().
mlirLLVMDIExpressionAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIExpressionAttrGet (MlirContext ctx, intptr_t nOperations, MlirAttribute const * operations)
Creates a LLVM DIExpression attribute.
Definition at line 209 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDIExpressionAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIExpressionAttrGetName (void)
Definition at line 220 of file LLVM.cpp.
References wrap().
mlirLLVMDIExpressionElemAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIExpressionElemAttrGet (MlirContext ctx, unsigned int opcode, intptr_t nArguments, uint64_t const * arguments)
Creates a LLVM DIExpressionElem attribute.
Definition at line 197 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIExpressionElemAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIExpressionElemAttrGetName (void)
Definition at line 205 of file LLVM.cpp.
References wrap().
mlirLLVMDIFileAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIFileAttrGet (MlirContext ctx, MlirAttribute name, MlirAttribute directory)
Creates a LLVM DIFileAttr attribute.
Definition at line 340 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIFileAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIFileAttrGetName (void)
Definition at line 346 of file LLVM.cpp.
References wrap().
mlirLLVMDIFlagsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIFlagsAttrGet (MlirContext ctx, uint64_t value)
Creates a LLVM DIFlags attribute.
Definition at line 377 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIFlagsAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIFlagsAttrGetName (void)
Definition at line 381 of file LLVM.cpp.
References wrap().
mlirLLVMDIImportedEntityAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIImportedEntityAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute scope, MlirAttribute entity, MlirAttribute file, unsigned int line, MlirAttribute name, intptr_t nElements, MlirAttribute const * elements)
Creates a LLVM DIImportedEntityAttr attribute.
Definition at line 527 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDIImportedEntityAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIImportedEntityAttrGetName (void)
Definition at line 541 of file LLVM.cpp.
References wrap().
mlirLLVMDILexicalBlockAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDILexicalBlockAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int line, unsigned int column)
Creates a LLVM DILexicalBlock attribute.
Definition at line 385 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDILexicalBlockAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDILexicalBlockAttrGetName (void)
Definition at line 395 of file LLVM.cpp.
References wrap().
mlirLLVMDILexicalBlockFileAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDILexicalBlockFileAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute file, unsigned int discriminator)
Creates a LLVM DILexicalBlockFile attribute.
Definition at line 399 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDILexicalBlockFileAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDILexicalBlockFileAttrGetName (void)
Definition at line 408 of file LLVM.cpp.
References wrap().
mlirLLVMDILocalVariableAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDILocalVariableAttrGet (MlirContext ctx, MlirAttribute scope, MlirAttribute name, MlirAttribute diFile, unsigned int line, unsigned int arg, unsigned int alignInBits, MlirAttribute diType, int64_t flags)
Creates a LLVM DILocalVariableAttr attribute.
Definition at line 412 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDILocalVariableAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDILocalVariableAttrGetName (void)
Definition at line 422 of file LLVM.cpp.
References wrap().
mlirLLVMDIModuleAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIModuleAttrGet (MlirContext ctx, MlirAttribute file, MlirAttribute scope, MlirAttribute name, MlirAttribute configMacros, MlirAttribute includePath, MlirAttribute apinotes, unsigned int line, bool isDecl)
Creates a LLVM DIModuleAttr attribute.
Definition at line 505 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIModuleAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIModuleAttrGetName (void)
Definition at line 519 of file LLVM.cpp.
References wrap().
mlirLLVMDIModuleAttrGetScope()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIModuleAttrGetScope (MlirAttribute diModule)
Gets the scope of this DIModuleAttr.
Definition at line 523 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDINullTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDINullTypeAttrGet (MlirContext ctx)
Creates a LLVM DINullType attribute.
Definition at line 224 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDINullTypeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDINullTypeAttrGetName (void)
Definition at line 228 of file LLVM.cpp.
References wrap().
mlirLLVMDIStringTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDIStringTypeAttrGet (MlirContext ctx, unsigned int tag, MlirAttribute name, uint64_t sizeInBits, uint32_t alignInBits, MlirAttribute stringLength, MlirAttribute stringLengthExp, MlirAttribute stringLocationExp, MlirLLVMTypeEncoding encoding)
Definition at line 299 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDIStringTypeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDIStringTypeAttrGetName (void)
Definition at line 311 of file LLVM.cpp.
References wrap().
mlirLLVMDISubprogramAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGet (MlirContext ctx, MlirAttribute recId, bool isRecSelf, MlirAttribute id, MlirAttribute compileUnit, MlirAttribute scope, MlirAttribute name, MlirAttribute linkageName, MlirAttribute file, unsigned int line, unsigned int scopeLine, uint64_t subprogramFlags, MlirAttribute type, intptr_t nRetainedNodes, MlirAttribute const * retainedNodes, intptr_t nAnnotations, MlirAttribute const * annotations)
Creates a LLVM DISubprogramAttr attribute.
Definition at line 447 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDISubprogramAttrGetCompileUnit()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetCompileUnit (MlirAttribute diSubprogram)
Gets the compile unit from this DISubprogram.
Definition at line 493 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetFile()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetFile (MlirAttribute diSubprogram)
Gets the file from this DISubprogramAttr.
Definition at line 497 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetLine()
MLIR_CAPI_EXPORTED unsigned int mlirLLVMDISubprogramAttrGetLine (MlirAttribute diSubprogram)
Gets the line from this DISubprogramAttr.
Definition at line 484 of file LLVM.cpp.
References unwrap().
mlirLLVMDISubprogramAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDISubprogramAttrGetName (void)
Definition at line 476 of file LLVM.cpp.
References wrap().
mlirLLVMDISubprogramAttrGetRecSelf()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetRecSelf (MlirAttribute recId)
Creates a self-referencing LLVM DISubprogramAttr attribute.
Definition at line 443 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetScope()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetScope (MlirAttribute diSubprogram)
Gets the scope from this DISubprogramAttr.
Definition at line 480 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMDISubprogramAttrGetScopeLine()
MLIR_CAPI_EXPORTED unsigned int mlirLLVMDISubprogramAttrGetScopeLine (MlirAttribute diSubprogram)
Gets the scope line from this DISubprogram.
Definition at line 488 of file LLVM.cpp.
References unwrap().
mlirLLVMDISubprogramAttrGetType()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubprogramAttrGetType (MlirAttribute diSubprogram)
Gets the type from this DISubprogramAttr.
Definition at line 501 of file LLVM.cpp.
References mlir::getType(), unwrap(), and wrap().
mlirLLVMDISubroutineTypeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMDISubroutineTypeAttrGet (MlirContext ctx, unsigned int callingConvention, intptr_t nTypes, MlirAttribute const * types)
Creates a LLVM DISubroutineTypeAttr attribute.
Definition at line 426 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
mlirLLVMDISubroutineTypeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMDISubroutineTypeAttrGetName (void)
Definition at line 439 of file LLVM.cpp.
References wrap().
mlirLLVMFunctionTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const * argumentTypes, bool isVarArg)
Creates an llvm.func type.
Definition at line 76 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetInput()
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
Definition at line 100 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMFunctionTypeGetName (void)
Definition at line 84 of file LLVM.cpp.
References wrap().
mlirLLVMFunctionTypeGetNumInputs()
MLIR_CAPI_EXPORTED intptr_t mlirLLVMFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
Definition at line 96 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetReturnType()
MLIR_CAPI_EXPORTED MlirType mlirLLVMFunctionTypeGetReturnType (MlirType type)
Returns the return type of the function type.
Definition at line 106 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMFunctionTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMFunctionTypeGetTypeID (void)
Returns the TypeID of an LLVM function type.
Definition at line 92 of file LLVM.cpp.
References wrap().
mlirLLVMFunctionTypeIsVarArg()
MLIR_CAPI_EXPORTED bool mlirLLVMFunctionTypeIsVarArg (MlirType type)
Returns true if the function type is variadic.
Definition at line 110 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived().
mlirLLVMLinkageAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMLinkageAttrGet (MlirContext ctx, MlirLLVMLinkage linkage)
Creates a LLVM Linkage attribute.
Definition at line 332 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMLinkageAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMLinkageAttrGetName (void)
Definition at line 336 of file LLVM.cpp.
References wrap().
mlirLLVMMDConstantAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDConstantAttrGet (MlirContext ctx, MlirAttribute valueAttr)
Creates an LLVM MDConstantAttr wrapping an attribute.
Definition at line 576 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDConstantAttr::bindDerived().
mlirLLVMMDConstantAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDConstantAttrGetTypeID (void)
Returns the TypeID of MDConstantAttr.
Definition at line 585 of file LLVM.cpp.
References wrap().
mlirLLVMMDConstantAttrGetValue()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDConstantAttrGetValue (MlirAttribute attr)
Returns the attribute value of an LLVM MDConstantAttr.
Definition at line 589 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDConstantAttr::bindDerived().
mlirLLVMMDFuncAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDFuncAttrGet (MlirContext ctx, MlirAttribute name)
Creates an LLVM MDFuncAttr referencing a function symbol.
Definition at line 593 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDFuncAttr::bindDerived().
mlirLLVMMDFuncAttrGetName()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDFuncAttrGetName (MlirAttribute attr)
Returns the symbol name of an LLVM MDFuncAttr.
Definition at line 606 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDFuncAttr::bindDerived().
mlirLLVMMDFuncAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDFuncAttrGetTypeID (void)
Returns the TypeID of MDFuncAttr.
Definition at line 602 of file LLVM.cpp.
References wrap().
mlirLLVMMDNodeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDNodeAttrGet (MlirContext ctx, intptr_t nOperands, MlirAttribute const * operands)
Creates an LLVM MDNodeAttr.
Definition at line 610 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived().
mlirLLVMMDNodeAttrGetNumOperands()
MLIR_CAPI_EXPORTED intptr_t mlirLLVMMDNodeAttrGetNumOperands (MlirAttribute attr)
Returns the number of operands in an LLVM MDNodeAttr.
Definition at line 626 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived().
mlirLLVMMDNodeAttrGetOperand()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDNodeAttrGetOperand (MlirAttribute attr, intptr_t index)
Returns the operand at the given index of an LLVM MDNodeAttr.
Definition at line 630 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived().
mlirLLVMMDNodeAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDNodeAttrGetTypeID (void)
Returns the TypeID of MDNodeAttr.
Definition at line 622 of file LLVM.cpp.
References wrap().
mlirLLVMMDStringAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute mlirLLVMMDStringAttrGet (MlirContext ctx, MlirStringRef value)
Creates an LLVM MDStringAttr.
Definition at line 559 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDStringAttr::bindDerived().
mlirLLVMMDStringAttrGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMMDStringAttrGetTypeID (void)
Returns the TypeID of MDStringAttr.
Definition at line 568 of file LLVM.cpp.
References wrap().
mlirLLVMMDStringAttrGetValue()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMMDStringAttrGetValue (MlirAttribute attr)
Returns the string value of an LLVM MDStringAttr.
Definition at line 572 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDStringAttr::bindDerived().
mlirLLVMPointerTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMPointerTypeGet (MlirContext ctx, unsigned addressSpace)
Creates an llvm.ptr type.
Definition at line 26 of file LLVM.cpp.
References mlirLLVMPointerTypeGet(), unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::PointerType::bindDerived(), and mlirLLVMPointerTypeGet().
mlirLLVMPointerTypeGetAddressSpace()
MLIR_CAPI_EXPORTED unsigned mlirLLVMPointerTypeGetAddressSpace (MlirType pointerType)
Returns address space of llvm.ptr.
Definition at line 42 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::PointerType::bindDerived().
mlirLLVMPointerTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMPointerTypeGetName (void)
Definition at line 30 of file LLVM.cpp.
References wrap().
mlirLLVMPointerTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMPointerTypeGetTypeID (void)
Definition at line 34 of file LLVM.cpp.
References wrap().
mlirLLVMStructTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeGetElementType (MlirType type, intptr_t position)
Returns the positions-th field of the struct.
Asserts if the struct is opaque, not yet initialized or if the position is out of range.
Definition at line 134 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeGetIdentifier()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMStructTypeGetIdentifier (MlirType type)
Returns the identifier of the identified struct.
Asserts that the struct is identified, i.e., not literal.
Definition at line 142 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMStructTypeGetName (void)
Definition at line 122 of file LLVM.cpp.
References wrap().
mlirLLVMStructTypeGetNumElementTypes()
MLIR_CAPI_EXPORTED intptr_t mlirLLVMStructTypeGetNumElementTypes (MlirType type)
Returns the number of fields in the struct.
Asserts if the struct is opaque or not yet initialized.
Definition at line 130 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirLLVMStructTypeGetTypeID (void)
Definition at line 118 of file LLVM.cpp.
References wrap().
mlirLLVMStructTypeIdentifiedGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeIdentifiedGet (MlirContext ctx, MlirStringRef name)
Creates an LLVM identified struct type with no body.
If a struct type with this name already exists in the context, returns that type. Use mlirLLVMStructTypeIdentifiedNewGet to create a fresh struct type, potentially renaming it. The body should be set separatelty by calling mlirLLVMStructTypeSetBody, if it isn't set already.
Definition at line 173 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIdentifiedNewGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeIdentifiedNewGet (MlirContext ctx, MlirStringRef name, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM identified struct type with no body and a name starting with the given prefix.
If a struct with the exact name as the given prefix already exists, appends an unspecified suffix to the name so that the name is unique in context.
Definition at line 177 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIsLiteral()
MLIR_CAPI_EXPORTED bool mlirLLVMStructTypeIsLiteral (MlirType type)
Returns true if the type is a literal (unnamed) LLVM struct type.
Definition at line 126 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIsOpaque()
MLIR_CAPI_EXPORTED bool mlirLLVMStructTypeIsOpaque (MlirType type)
Returns true is the struct is explicitly opaque (will not have a body) or uninitialized (will eventually have a body).
Definition at line 146 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeIsPacked()
MLIR_CAPI_EXPORTED bool mlirLLVMStructTypeIsPacked (MlirType type)
Returns true if the struct is packed.
Definition at line 138 of file LLVM.cpp.
References unwrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeLiteralGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
This may assert if the fields have types not compatible with the LLVM dialect. For a graceful failure, use the checked version.
Definition at line 150 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeLiteralGetChecked()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeLiteralGetChecked (MlirLocation loc, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type if possible.
Emits a diagnostic at the given location and returns null otherwise.
Definition at line 159 of file LLVM.cpp.
References mlir::emitError(), unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeOpaqueGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMStructTypeOpaqueGet (MlirContext ctx, MlirStringRef name)
Definition at line 169 of file LLVM.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMStructTypeSetBody()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirLLVMStructTypeSetBody (MlirType structType, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Sets the body of the identified struct if it hasn't been set yet.
Returns whether the operation was successful.
Definition at line 187 of file LLVM.cpp.
References unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived().
mlirLLVMVoidTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
Definition at line 46 of file LLVM.cpp.
References unwrap(), and wrap().
mlirLLVMVoidTypeGetName()
MLIR_CAPI_EXPORTED MlirStringRef mlirLLVMVoidTypeGetName (void)
Definition at line 50 of file LLVM.cpp.
References wrap().
mlirTypeIsALLVMArrayType()
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMArrayType (MlirType type)
Returns true if the type is an LLVM dialect array type.
Definition at line 52 of file LLVM.cpp.
References unwrap().
mlirTypeIsALLVMFunctionType()
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMFunctionType (MlirType type)
Returns true if the type is an LLVM dialect function type.
Definition at line 88 of file LLVM.cpp.
References unwrap().
mlirTypeIsALLVMPointerType()
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMPointerType (MlirType type)
Returns true if the type is an LLVM dialect pointer type.
Definition at line 38 of file LLVM.cpp.
References unwrap().
mlirTypeIsALLVMStructType()
MLIR_CAPI_EXPORTED bool mlirTypeIsALLVMStructType (MlirType type)
Returns true if the type is an LLVM dialect struct type.
Definition at line 114 of file LLVM.cpp.
References unwrap().