MLIR: lib/Dialect/SPIRV/Linking/ModuleCombiner/ModuleCombiner.cpp File Reference
ModuleCombiner.cpp File Reference
#include "mlir/Dialect/SPIRV/Linking/ModuleCombiner.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/SymbolTable.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/StringExtras.h"
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Functions
static SmallString< 64 > renameSymbol (StringRef oldSymName, unsigned &lastUsedID, spirv::ModuleOp combinedModule)
static LogicalResult updateSymbolAndAllUses (SymbolOpInterface op, spirv::ModuleOp target, spirv::ModuleOp source, unsigned &lastUsedID)
Check if a symbol with the same name as op already exists in source.
template<typename KeyTy , typename SymbolOpTy >
static SymbolOpTy emplaceOrGetReplacementSymbol (KeyTy key, SymbolOpTy symbolOp, DenseMap< KeyTy, SymbolOpTy > &deduplicationMap)
static llvm::hash_code computeHash (SymbolOpInterface symbolOp)
Computes a hash code to represent the argument SymbolOpInterface based on all the Op's attributes except for the symbol name.
llvm::hash_code computeHash (Block *block)
Computes a hash code from the argument Block.
OwningOpRef< spirv::ModuleOp > mlir::spirv::combine (llvm::MutableArrayRef< spirv::ModuleOp > modules, OpBuilder &combinedModuleBuilder, llvm::function_ref< void(ModuleOp, StringRef, StringRef)> symRenameListener)
Variables
static constexpr unsigned maxFreeID = 1 << 20
Function Documentation
computeHash() [1/2]
static llvm::hash_code computeHash (SymbolOpInterface symbolOp) static
Computes a hash code to represent the argument SymbolOpInterface based on all the Op's attributes except for the symbol name.
Returns
the hash code computed from the Op's attributes as described above.
Note: We use the operation's name (not the symbol name) as part of the hash computation. This prevents, for example, mistakenly considering a global variable and a spec constant as duplicates because their descriptor set + binding and spec_id, respectively, happen to hash to the same value.
Definition at line 85 of file ModuleCombiner.cpp.
References mlir::SymbolTable::getSymbolAttrName().
Referenced by mlir::spirv::combine().
computeHash() [2/2]
llvm::hash_code computeHash (Block * block)
Computes a hash code from the argument Block.
Definition at line 99 of file ModuleCombiner.cpp.
References mlir::OperationEquivalence::computeHash(), mlir::Operation::getNumRegions(), and op.
emplaceOrGetReplacementSymbol()
template<typename KeyTy , typename SymbolOpTy > static SymbolOpTy emplaceOrGetReplacementSymbol (KeyTy key, SymbolOpTy symbolOp, DenseMap< KeyTy, SymbolOpTy > & deduplicationMap) static
Definition at line 66 of file ModuleCombiner.cpp.
Referenced by mlir::spirv::combine().
renameSymbol()
static SmallString<64> renameSymbol (StringRef oldSymName, unsigned & lastUsedID, spirv::ModuleOp combinedModule) static
Definition at line 27 of file ModuleCombiner.cpp.
References mlir::SymbolTable::lookupSymbolIn(), and maxFreeID.
Referenced by updateSymbolAndAllUses().
updateSymbolAndAllUses()
static LogicalResult updateSymbolAndAllUses (SymbolOpInterface op, spirv::ModuleOp target, spirv::ModuleOp source, unsigned & lastUsedID) static
Check if a symbol with the same name as op already exists in source.
If so, rename op and update all its references in target.
Definition at line 46 of file ModuleCombiner.cpp.
References mlir::failed(), mlir::SymbolTable::lookupSymbolIn(), renameSymbol(), mlir::SymbolTable::replaceAllSymbolUses(), mlir::SymbolTable::setSymbolName(), and mlir::success().
Referenced by mlir::spirv::combine().
Variable Documentation
maxFreeID
constexpr unsigned maxFreeID = 1 << 20 static
Definition at line 25 of file ModuleCombiner.cpp.
Referenced by renameSymbol().