MLIR: llvm Namespace Reference
llvm Namespace Reference
The OpAsmOpInterface, see OpAsmInterface.td for more details.
Namespaces
namespace cl
namespace detail
namespace ilist_detail
namespace lsp
namespace orc
namespace sys
namespace yaml
Classes
class ArrayRef
struct cast_convert_val< T, ::mlir::Dialect *, ::mlir::Dialect * >
struct cast_convert_val< T, ::mlir::Dialect, ::mlir::Dialect >
struct cast_retty_impl< T, ::mlir::Dialect * >
struct cast_retty_impl< T, ::mlir::Dialect >
struct CastInfo< const ::mlir::Operation *, const ::mlir::Operation * >
struct CastInfo< T, ::mlir::Operation * >
Cast from an (const) Operation * to a derived operation type.
struct CastInfo< T, ::mlir::Operation >
Cast from an (const) Operation & to a derived operation type.
struct CastInfo< T, const ::mlir::Operation * >
struct CastInfo< T, const ::mlir::Operation >
struct CastInfo< To, const mlir::CallInterfaceCallable >
struct CastInfo< To, const mlir::IRUnit >
struct CastInfo< To, const mlir::LatticeAnchor >
struct CastInfo< To, const mlir::LLVM::GEPArg >
struct CastInfo< To, const mlir::OpFoldResult >
struct CastInfo< To, From, std::enable_if_t< std::is_same_v< mlir::AffineExpr, std::remove_const_t< From > >||std::is_base_of_v< mlir::AffineExpr, From > > >
Add support for llvm style casts.
struct CastInfo< To, From, std::enable_if_t< std::is_same_v< mlir::Attribute, std::remove_const_t< From > >||std::is_base_of_v< mlir::Attribute, From > > >
Add support for llvm style casts.
struct CastInfo< To, From, std::enable_if_t< std::is_same_v< mlir::Location, std::remove_const_t< From > >||std::is_base_of_v< mlir::Location, From > > >
Add support for llvm style casts.
struct CastInfo< To, From, std::enable_if_t< std::is_same_v< mlir::pdll::ast::Type, std::remove_const_t< From > >||std::is_base_of_v< mlir::pdll::ast::Type, From > > >
Add support for llvm style casts.
struct CastInfo< To, From, std::enable_if_t< std::is_same_v< mlir::Type, std::remove_const_t< From > >||std::is_base_of_v< mlir::Type, From > > >
Add support for llvm style casts.
struct CastInfo< To, From, std::enable_if_t< std::is_same_v< mlir::Value, std::remove_const_t< From > >||std::is_base_of_v< mlir::Value, From > > >
Add support for llvm style casts.
struct CastInfo< To, mlir::CallInterfaceCallable >
struct CastInfo< To, mlir::IRUnit >
struct CastInfo< To, mlir::LatticeAnchor >
struct CastInfo< To, mlir::LLVM::GEPArg >
struct CastInfo< To, mlir::OpFoldResult >
struct CastInfo<::mlir::Operation *, ::mlir::Operation * >
Cast (const) Operation * to itself.
class DenseMap
struct DenseMapInfo
struct DenseMapInfo< mlir::AffineExpr >
struct DenseMapInfo< mlir::AffineMap >
struct DenseMapInfo< mlir::AsmDialectResourceHandle >
struct DenseMapInfo< mlir::Attribute >
struct DenseMapInfo< mlir::Block::iterator >
struct DenseMapInfo< mlir::BlockArgument >
struct DenseMapInfo< mlir::detail::TypedValue< T > >
struct DenseMapInfo< mlir::IntegerSet >
struct DenseMapInfo< mlir::LatticeAnchor >
struct DenseMapInfo< mlir::Location >
struct DenseMapInfo< mlir::NamedAttribute >
struct DenseMapInfo< mlir::OperationName >
struct DenseMapInfo< mlir::OpResult >
struct DenseMapInfo< mlir::PassInstrumentation::PipelineParentInfo >
struct DenseMapInfo< mlir::pdll::ast::Type >
struct DenseMapInfo< mlir::ProgramPoint >
Allow hashing of lattice anchors and program points.
struct DenseMapInfo< mlir::RegisteredOperationName >
struct DenseMapInfo< mlir::remark::detail::Remark >
struct DenseMapInfo< mlir::StringAttr >
struct DenseMapInfo< mlir::SuccessorRange >
Provide support for hashing successor ranges.
struct DenseMapInfo< mlir::tblgen::Constraint >
Unique constraints by their predicate and summary.
struct DenseMapInfo< mlir::tblgen::DagLeaf >
struct DenseMapInfo< mlir::tblgen::DagNode >
struct DenseMapInfo< mlir::Type >
struct DenseMapInfo< mlir::TypeID >
struct DenseMapInfo< mlir::TypeRange >
struct DenseMapInfo< mlir::Value >
struct DenseMapInfo< MlirTypeID >
struct DenseMapInfo< T, std::enable_if_t< mlir::detail::IsInterface< T >::value > >
struct DenseMapInfo< T, std::enable_if_t< std::is_base_of< mlir::Attribute, T >::value &&!mlir::detail::IsInterface< T >::value > >
struct DenseMapInfo< T, std::enable_if_t< std::is_base_of< mlir::OpState, T >::value &&!mlir::detail::IsInterface< T >::value > >
struct DenseMapInfo< T, std::enable_if_t< std::is_base_of< mlir::Type, T >::value &&!mlir::detail::IsInterface< T >::value > >
class DenseSet
class Expected
class function_ref
struct GraphTraits< const mlir::Block * >
struct GraphTraits< const mlir::CallGraph * >
struct GraphTraits< const mlir::CallGraphNode * >
struct GraphTraits< const mlir::DominanceInfoNode * >
struct GraphTraits< Inverse< const mlir::Block * > >
struct GraphTraits< Inverse< mlir::Block * > >
struct GraphTraits< Inverse< mlir::Region * > >
struct GraphTraits< mlir::Block * >
struct GraphTraits< mlir::DominanceInfoNode * >
DominatorTree GraphTraits specialization so the DominatorTree can be iterated by generic graph iterators.
struct GraphTraits< mlir::Region * >
struct ilist_traits<::mlir::Block >
struct ilist_traits<::mlir::Operation >
struct isa_impl< mlir::DynamicDialect, mlir::Dialect >
Provide isa functionality for DynamicDialect.
struct isa_impl< mlir::ExtensibleDialect, mlir::Dialect >
Provide isa functionality for ExtensibleDialect.
struct isa_impl< T, ::mlir::Dialect, std::enable_if_t< std::is_base_of<::mlir::Dialect, T >::value > >
Provide isa functionality for Dialects.
struct isa_impl< T, ::mlir::Dialect, std::enable_if_t< std::is_base_of<::mlir::DialectInterface, T >::value > >
struct isa_impl< T, ::mlir::StateStackFrame >
class iterator_range
class MutableArrayRef
struct PointerLikeTypeTraits< mlir::async::FuncOp >
Allow stealing the low bits of async::FuncOp.
struct PointerLikeTypeTraits< mlir::Attribute >
Allow LLVM to steal the low bits of Attributes.
struct PointerLikeTypeTraits< mlir::BlockArgument >
struct PointerLikeTypeTraits< mlir::detail::TypedValue< T > >
struct PointerLikeTypeTraits< mlir::func::FuncOp >
Allow stealing the low bits of FuncOp.
struct PointerLikeTypeTraits< mlir::IntegerAttr >
struct PointerLikeTypeTraits< mlir::Location >
We align LocationStorage by 8, so allow LLVM to steal the low bits.
struct PointerLikeTypeTraits< mlir::ModuleOp >
Allow stealing the low bits of ModuleOp.
struct PointerLikeTypeTraits< mlir::OperationName >
struct PointerLikeTypeTraits< mlir::OpResult >
struct PointerLikeTypeTraits< mlir::RegisteredOperationName >
struct PointerLikeTypeTraits< mlir::spirv::FuncOp >
Allow stealing the low bits of spirv::Function ops.
struct PointerLikeTypeTraits< mlir::StringAttr >
struct PointerLikeTypeTraits< mlir::SymbolRefAttr >
struct PointerLikeTypeTraits< mlir::Type >
We align TypeStorage by 8, so allow LLVM to steal the low bits.
struct PointerLikeTypeTraits< mlir::TypeID >
We align TypeID::Storage by 8, so allow LLVM to steal the low bits.
struct PointerLikeTypeTraits< mlir::Value >
Allow stealing the low bits of a value.
class PointerUnion
class SetVector
class SmallPtrSet
class SmallPtrSetImpl
class SmallString
class SmallVector
class SmallVectorImpl
class StringSet
class StringSwitch
class TinyPtrVector
class TypeSwitch
struct ValueIsPresent< mlir::Location >
The constructors in mlir::Location ensure that the class is a non-nullable wrapper around mlir::LocationAttr.
Functions
static LogicalResult embedBinaryImpl (StringRef moduleName, gpu::ObjectAttr object, Module &module)
Detailed Description
The OpAsmOpInterface, see OpAsmInterface.td for more details.
Explicitly register a set of "builtin" types.
void must be self-owning, it can't be fully resolved.
Function Documentation
embedBinaryImpl()
LogicalResult llvm::embedBinaryImpl (StringRef moduleName, gpu::ObjectAttr object, Module & module) static
Definition at line 96 of file SelectObjectAttr.cpp.
References mlir::Constant, mlir::gpu::elfSectionName, embedBinaryImpl(), getModuleIdentifier(), and success().
Referenced by embedBinaryImpl().