MLIR: mlir::x86vector::avx2::inline_asm Namespace Reference
mlir::x86vector::avx2::inline_asm Namespace Reference
Functions
Value mm256BlendPsAsm (ImplicitLocOpBuilder &b, Value v1, Value v2, uint8_t mask)
Methods in the inline_asm namespace emit calls to LLVM::InlineAsmOp.
Function Documentation
mm256BlendPsAsm()
Value mlir::x86vector::avx2::inline_asm::mm256BlendPsAsm (ImplicitLocOpBuilder & b, Value v1, Value v2, uint8_t mask)
Methods in the inline_asm namespace emit calls to LLVM::InlineAsmOp.
If bit i of mask is zero, take f32@i from v1 else take it from v2.
Definition at line 30 of file AVXTranspose.cpp.
References mlir::get(), mlir::Builder::getContext(), mlir::Value::getType(), and None.
Referenced by mlir::x86vector::avx2::transpose8x8xf32().