MLIR: mlir::runtime Namespace Reference
mlir::runtime Namespace Reference
Classes
struct AsyncGroup
struct AsyncToken
struct AsyncValue
Typedefs
using AsyncToken = struct AsyncToken
using AsyncGroup = struct AsyncGroup
using AsyncValue = struct AsyncValue
using ValueStorage = std::byte *
using CoroHandle = void *
using CoroResume = void (*)(void *)
using RefCountedObjPtr = void *
Functions
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAddRef (RefCountedObjPtr, int64_t)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeDropRef (RefCountedObjPtr, int64_t)
MLIR_ASYNC_RUNTIME_EXPORT AsyncToken * mlirAsyncRuntimeCreateToken ()
MLIR_ASYNC_RUNTIME_EXPORT AsyncValue * mlirAsyncRuntimeCreateValue (int64_t)
MLIR_ASYNC_RUNTIME_EXPORT AsyncGroup * mlirAsyncRuntimeCreateGroup (int64_t size)
MLIR_ASYNC_RUNTIME_EXPORT int64_t mlirAsyncRuntimeAddTokenToGroup (AsyncToken *, AsyncGroup *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeEmplaceToken (AsyncToken *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeEmplaceValue (AsyncValue *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeSetTokenError (AsyncToken *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeSetValueError (AsyncValue *)
MLIR_ASYNC_RUNTIME_EXPORT bool mlirAsyncRuntimeIsTokenError (AsyncToken *)
MLIR_ASYNC_RUNTIME_EXPORT bool mlirAsyncRuntimeIsValueError (AsyncValue *)
MLIR_ASYNC_RUNTIME_EXPORT bool mlirAsyncRuntimeIsGroupError (AsyncGroup *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAwaitToken (AsyncToken *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAwaitValue (AsyncValue *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAwaitAllInGroup (AsyncGroup *)
MLIR_ASYNC_RUNTIME_EXPORT ValueStorage mlirAsyncRuntimeGetValueStorage (AsyncValue *)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeExecute (CoroHandle, CoroResume)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAwaitTokenAndExecute (AsyncToken *, CoroHandle, CoroResume)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAwaitValueAndExecute (AsyncValue *, CoroHandle, CoroResume)
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimeAwaitAllInGroupAndExecute (AsyncGroup *, CoroHandle, CoroResume)
MLIR_ASYNC_RUNTIME_EXPORT int64_t mlirAsyncRuntimGetNumWorkerThreads ()
MLIR_ASYNC_RUNTIME_EXPORT void mlirAsyncRuntimePrintCurrentThreadId ()
static std::unique_ptr< AsyncRuntime > & getDefaultAsyncRuntimeInstance ()
static void resetDefaultAsyncRuntime ()
static AsyncRuntime * getDefaultAsyncRuntime ()
static void setTokenState (AsyncToken *token, State state)
static void setValueState (AsyncValue *value, State state)
MLIR_ASYNC_RUNTIME_EXPORT void __mlir_execution_engine_init (llvm::StringMap< void * > &exportSymbols)
MLIR_ASYNC_RUNTIME_EXPORT void __mlir_execution_engine_destroy ()
Typedef Documentation
AsyncGroup
using mlir::runtime::AsyncGroup = struct AsyncGroup
Definition at line 46 of file AsyncRuntime.h.
AsyncToken
using mlir::runtime::AsyncToken = struct AsyncToken
Definition at line 43 of file AsyncRuntime.h.
AsyncValue
using mlir::runtime::AsyncValue = struct AsyncValue
Definition at line 49 of file AsyncRuntime.h.
CoroHandle
using mlir::runtime::CoroHandle = void *
Definition at line 57 of file AsyncRuntime.h.
CoroResume
using mlir::runtime::CoroResume = void (*)(void *)
Definition at line 58 of file AsyncRuntime.h.
RefCountedObjPtr
using mlir::runtime::RefCountedObjPtr = void *
Definition at line 62 of file AsyncRuntime.h.
ValueStorage
using mlir::runtime::ValueStorage = std::byte *
Definition at line 52 of file AsyncRuntime.h.
Function Documentation
__mlir_execution_engine_destroy()
MLIR_ASYNC_RUNTIME_EXPORT void mlir::runtime::__mlir_execution_engine_destroy ()
Definition at line 521 of file AsyncRuntime.cpp.
References MLIR_ASYNC_RUNTIME_EXPORT, and resetDefaultAsyncRuntime().
__mlir_execution_engine_init()
void mlir::runtime::__mlir_execution_engine_init (llvm::StringMap< void * > & exportSymbols)
Definition at line 466 of file AsyncRuntime.cpp.
References mlirAsyncRuntimeAddRef(), mlirAsyncRuntimeAddTokenToGroup(), mlirAsyncRuntimeAwaitAllInGroup(), mlirAsyncRuntimeAwaitAllInGroupAndExecute(), mlirAsyncRuntimeAwaitToken(), mlirAsyncRuntimeAwaitTokenAndExecute(), mlirAsyncRuntimeAwaitValue(), mlirAsyncRuntimeAwaitValueAndExecute(), mlirAsyncRuntimeCreateGroup(), mlirAsyncRuntimeCreateToken(), mlirAsyncRuntimeCreateValue(), mlirAsyncRuntimeDropRef(), mlirAsyncRuntimeEmplaceToken(), mlirAsyncRuntimeEmplaceValue(), mlirAsyncRuntimeExecute(), mlirAsyncRuntimeGetValueStorage(), mlirAsyncRuntimeIsGroupError(), mlirAsyncRuntimeIsTokenError(), mlirAsyncRuntimeIsValueError(), mlirAsyncRuntimePrintCurrentThreadId(), mlirAsyncRuntimeSetTokenError(), mlirAsyncRuntimeSetValueError(), and mlirAsyncRuntimGetNumWorkerThreads().
getDefaultAsyncRuntime()
AsyncRuntime * mlir::runtime::getDefaultAsyncRuntime () static
Definition at line 166 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntimeInstance().
Referenced by mlirAsyncRuntimeCreateGroup(), mlirAsyncRuntimeCreateToken(), mlirAsyncRuntimeCreateValue(), mlirAsyncRuntimeExecute(), and mlirAsyncRuntimGetNumWorkerThreads().
getDefaultAsyncRuntimeInstance()
std::unique_ptr< AsyncRuntime > & mlir::runtime::getDefaultAsyncRuntimeInstance () static
Definition at line 157 of file AsyncRuntime.cpp.
Referenced by getDefaultAsyncRuntime(), and resetDefaultAsyncRuntime().
mlirAsyncRuntimeAddRef()
void mlir::runtime::mlirAsyncRuntimeAddRef (RefCountedObjPtr ptr, int64_t count)
Definition at line 226 of file AsyncRuntime.cpp.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAddTokenToGroup()
int64_t mlir::runtime::mlirAsyncRuntimeAddTokenToGroup (AsyncToken * token, AsyncGroup * group)
Definition at line 255 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncGroup::awaiters, mlir::runtime::AsyncToken::awaiters, mlir::runtime::AsyncGroup::cv, mlir::runtime::AsyncGroup::mu, mlir::runtime::AsyncToken::mu, mlir::runtime::AsyncGroup::numErrors, mlir::runtime::AsyncGroup::pendingTokens, mlir::runtime::AsyncGroup::rank, and mlir::runtime::AsyncToken::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAwaitAllInGroup()
void mlir::runtime::mlirAsyncRuntimeAwaitAllInGroup (AsyncGroup * group)
Definition at line 383 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncGroup::cv, mlir::runtime::AsyncGroup::mu, and mlir::runtime::AsyncGroup::pendingTokens.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAwaitAllInGroupAndExecute()
void mlir::runtime::mlirAsyncRuntimeAwaitAllInGroupAndExecute (AsyncGroup * group, CoroHandle handle, CoroResume resume)
Definition at line 426 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncGroup::awaiters, mlir::runtime::AsyncGroup::mu, and mlir::runtime::AsyncGroup::pendingTokens.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAwaitToken()
void mlir::runtime::mlirAsyncRuntimeAwaitToken (AsyncToken * token)
Definition at line 369 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncToken::cv, mlir::runtime::AsyncToken::mu, and mlir::runtime::AsyncToken::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAwaitTokenAndExecute()
void mlir::runtime::mlirAsyncRuntimeAwaitTokenAndExecute (AsyncToken * token, CoroHandle handle, CoroResume resume)
Definition at line 400 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncToken::awaiters, mlir::runtime::AsyncToken::mu, and mlir::runtime::AsyncToken::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAwaitValue()
void mlir::runtime::mlirAsyncRuntimeAwaitValue (AsyncValue * value)
Definition at line 376 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncValue::cv, mlir::runtime::AsyncValue::mu, and mlir::runtime::AsyncValue::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeAwaitValueAndExecute()
void mlir::runtime::mlirAsyncRuntimeAwaitValueAndExecute (AsyncValue * value, CoroHandle handle, CoroResume resume)
Definition at line 413 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncValue::awaiters, mlir::runtime::AsyncValue::mu, and mlir::runtime::AsyncValue::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeCreateGroup()
AsyncGroup * mlir::runtime::mlirAsyncRuntimeCreateGroup (int64_t size)
Definition at line 250 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntime().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeCreateToken()
AsyncToken * mlir::runtime::mlirAsyncRuntimeCreateToken ()
Definition at line 238 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntime().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeCreateValue()
AsyncValue * mlir::runtime::mlirAsyncRuntimeCreateValue (int64_t size)
Definition at line 244 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntime().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeDropRef()
void mlir::runtime::mlirAsyncRuntimeDropRef (RefCountedObjPtr ptr, int64_t count)
Definition at line 232 of file AsyncRuntime.cpp.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeEmplaceToken()
void mlir::runtime::mlirAsyncRuntimeEmplaceToken (AsyncToken * token)
Definition at line 341 of file AsyncRuntime.cpp.
References setTokenState().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeEmplaceValue()
void mlir::runtime::mlirAsyncRuntimeEmplaceValue (AsyncValue * value)
Definition at line 345 of file AsyncRuntime.cpp.
References setValueState().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeExecute()
void mlir::runtime::mlirAsyncRuntimeExecute (CoroHandle handle, CoroResume resume)
Definition at line 395 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntime().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeGetValueStorage()
ValueStorage mlir::runtime::mlirAsyncRuntimeGetValueStorage (AsyncValue * value)
Definition at line 390 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncValue::state, and mlir::runtime::AsyncValue::storage.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeIsGroupError()
bool mlir::runtime::mlirAsyncRuntimeIsGroupError (AsyncGroup * group)
Definition at line 365 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncGroup::numErrors.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeIsTokenError()
bool mlir::runtime::mlirAsyncRuntimeIsTokenError (AsyncToken * token)
Definition at line 357 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncToken::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeIsValueError()
bool mlir::runtime::mlirAsyncRuntimeIsValueError (AsyncValue * value)
Definition at line 361 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncValue::state.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimePrintCurrentThreadId()
void mlir::runtime::mlirAsyncRuntimePrintCurrentThreadId ()
Definition at line 447 of file AsyncRuntime.cpp.
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeSetTokenError()
void mlir::runtime::mlirAsyncRuntimeSetTokenError (AsyncToken * token)
Definition at line 349 of file AsyncRuntime.cpp.
References setTokenState().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimeSetValueError()
void mlir::runtime::mlirAsyncRuntimeSetValueError (AsyncValue * value)
Definition at line 353 of file AsyncRuntime.cpp.
References setValueState().
Referenced by __mlir_execution_engine_init().
mlirAsyncRuntimGetNumWorkerThreads()
int64_t mlir::runtime::mlirAsyncRuntimGetNumWorkerThreads ()
Definition at line 439 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntime().
Referenced by __mlir_execution_engine_init().
resetDefaultAsyncRuntime()
void mlir::runtime::resetDefaultAsyncRuntime () static
Definition at line 162 of file AsyncRuntime.cpp.
References getDefaultAsyncRuntimeInstance().
Referenced by __mlir_execution_engine_destroy().
setTokenState()
void mlir::runtime::setTokenState (AsyncToken * token, State state) static
Definition at line 305 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncToken::awaiters, mlir::runtime::AsyncToken::cv, mlir::runtime::AsyncToken::mu, and mlir::runtime::AsyncToken::state.
Referenced by mlirAsyncRuntimeEmplaceToken(), and mlirAsyncRuntimeSetTokenError().
setValueState()
void mlir::runtime::setValueState (AsyncValue * value, State state) static
Definition at line 323 of file AsyncRuntime.cpp.
References mlir::runtime::AsyncValue::awaiters, mlir::runtime::AsyncValue::cv, mlir::runtime::AsyncValue::mu, and mlir::runtime::AsyncValue::state.
Referenced by mlirAsyncRuntimeEmplaceValue(), and mlirAsyncRuntimeSetValueError().