MLIR: mlir::LLVM Namespace Reference
mlir::LLVM Namespace Reference
Namespaces
namespace detail
namespace impl
Classes
struct AssumeAlignTag
struct AssumeSeparateStorageTag
class DIExpressionRewriter
Rewriter for DIExpressionAttr.
class DILocalScopeAttr
This class represents a LLVM attribute that describes a local debug info scope.
class DINodeAttr
This class represents the base attribute for all debug info attributes.
class DIScopeAttr
This class represents a LLVM attribute that describes a debug info scope.
struct DIScopeForLLVMFuncOpPassOptions
class DITypeAttr
This class represents a LLVM attribute that describes a debug info type.
class DIVariableAttr
This class represents a LLVM attribute that describes a debug info variable.
class GEPArg
Class used for building a 'llvm.getelementptr'.
class GEPIndicesAdaptor
Class used for convenient access and iteration over GEP indices.
struct LLVMTargetToDataLayoutOptions
struct LLVMTargetToTargetFeaturesOptions
struct LLVMUseDefaultVisibilityPassOptions
class MergeFragments
Adjacent DW_OP_LLVM_fragment should be merged into one.
class ModuleImport
Module import implementation class that provides methods to import globals and functions from an LLVM module into an MLIR module.
class ModuleToObject
Utility base class for transforming operations into binary objects, by default it returns the serialized LLVM bitcode for the module.
class ModuleTranslation
Implementation class for module translation.
class TBAANodeAttr
Base class for LLVM attributes participating in the TBAA graph.
class TypeFromLLVMIRTranslator
Utility class to translate LLVM IR types to the MLIR LLVM dialect.
class TypeToLLVMIRTranslator
Utility class to translate MLIR LLVM dialect types to LLVM IR.
Typedefs
using GEPConstantIndex
Wrapper around a int32_t for use in a PointerUnion.
Enumerations
enum class PtrDLEntryPos { Size = 0 , Abi = 1 , Preferred = 2 , Index = 3 }
The positions of different values in the data layout entry for pointers.
Functions
SmallVector< Value > decomposeValue (OpBuilder &builder, Location loc, Value src, Type dstType)
Decomposes a src value into a set of values of type dstType through series of bitcasts and vector ops.
Value composeValue (OpBuilder &builder, Location loc, ValueRange src, Type dstType)
Composes a set of src values into a single value of type dstType through series of bitcasts and vector ops.
Value getStridedElementPtr (OpBuilder &builder, Location loc, const LLVMTypeConverter &converter, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags=LLVM::GEPNoWrapFlags::none)
Performs the index computation to get to the element at indices of the memory pointed to by memRefDesc, using the layout map of type.
LogicalResult createPrintStrCall (OpBuilder &builder, Location loc, ModuleOp moduleOp, StringRef symbolName, StringRef string, const LLVMTypeConverter &typeConverter, bool addNewline=true, std::optional< StringRef > runtimeFunctionName={}, SymbolTableCollection *symbolTables=nullptr)
Generate IR that prints the given string to stdout.
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintI64Fn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
Helper functions to look up or create the declaration for commonly used external C function calls.
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintU64Fn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintF16Fn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintBF16Fn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintF32Fn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintF64Fn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateApFloatPrintFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintStringFn (OpBuilder &b, Operation *moduleOp, std::optional< StringRef > runtimeFunctionName={}, SymbolTableCollection *symbolTables=nullptr)
Declares a function to print a C-string.
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintOpenFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintCloseFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintCommaFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreatePrintNewlineFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateMallocFn (OpBuilder &b, Operation *moduleOp, Type indexType, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateAlignedAllocFn (OpBuilder &b, Operation *moduleOp, Type indexType, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateFreeFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateGenericAllocFn (OpBuilder &b, Operation *moduleOp, Type indexType, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateGenericAlignedAllocFn (OpBuilder &b, Operation *moduleOp, Type indexType, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateGenericFreeFn (OpBuilder &b, Operation *moduleOp, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateMemRefCopyFn (OpBuilder &b, Operation *moduleOp, Type indexType, Type unrankedDescriptorType, SymbolTableCollection *symbolTables=nullptr)
FailureOr< LLVM::LLVMFuncOp > lookupOrCreateFn (OpBuilder &b, Operation *moduleOp, StringRef name, ArrayRef< Type > paramTypes={}, Type resultType={}, bool isVarArg=false, bool isReserved=false, SymbolTableCollection *symbolTables=nullptr)
Create a FuncOp with signature resultType(paramTypes) and name name`.
Value createGlobalString (Location loc, OpBuilder &builder, StringRef name, StringRef value, Linkage linkage)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
bool satisfiesLLVMModule (Operation *op)
LLVM requires some operations to be inside of a Module operation.
Operation * parentLLVMModule (Operation *op)
Lookup parent Module satisfying LLVM conditions on the Module Operation.
template<typename IntT = int64_t>
SmallVector< IntT > convertArrayToIndices (ArrayRef< Attribute > attrs)
Convert an array of integer attributes to a vector of integers that can be used as indices in LLVM operations.
template<typename IntT = int64_t>
SmallVector< IntT > convertArrayToIndices (ArrayAttr attrs)
Convert an ArrayAttr of integer attributes to a vector of integers that can be used as indices in LLVM operations.
DEFINE_TRIVIAL_LLVM_TYPE (LLVMVoidType, "llvm.void")
DEFINE_TRIVIAL_LLVM_TYPE (LLVMTokenType, "llvm.token")
DEFINE_TRIVIAL_LLVM_TYPE (LLVMLabelType, "llvm.label")
DEFINE_TRIVIAL_LLVM_TYPE (LLVMMetadataType, "llvm.metadata")
ParseResult parsePrettyLLVMType (AsmParser &p, Type &type)
Parse any MLIR type or a concise syntax for LLVM types.
void printPrettyLLVMType (AsmPrinter &p, Type type)
Print any MLIR type or a concise syntax for LLVM types.
bool isCompatibleType (Type type)
Returns true if the given type is compatible with the LLVM dialect.
bool isCompatibleOuterType (Type type)
Returns true if the given outer type is compatible with the LLVM dialect without checking its potential nested types such as struct elements.
bool isCompatibleFloatingPointType (Type type)
Returns true if the given type is a floating-point type compatible with the LLVM dialect.
bool isCompatibleVectorType (Type type)
Returns true if the given type is a vector type compatible with the LLVM dialect.
bool isLoadableType (Type type)
Returns true if the given type is a loadable type compatible with the LLVM dialect.
bool isTypeCompatibleWithAtomicOp (Type type, const DataLayout &dataLayout)
Returns true if the given type is supported by atomic operations.
llvm::ElementCount getVectorNumElements (Type type)
Returns the element count of any LLVM-compatible vector type.
bool isScalableVectorType (Type vectorType)
Returns whether a vector type is scalable or not.
Type getVectorType (Type elementType, unsigned numElements, bool isScalable=false)
Creates an LLVM dialect-compatible vector type with the given element type and length.
Type getVectorType (Type elementType, const llvm::ElementCount &numElements)
Creates an LLVM dialect-compatible vector type with the given element type and length.
llvm::TypeSize getPrimitiveTypeSizeInBits (Type type)
Returns the size of the given primitive LLVM dialect-compatible type (including vectors) in bits, for example, the size of i16 is 16 and the size of vector<4xi16> is 64.
std::optional< uint64_t > extractPointerSpecValue (Attribute attr, PtrDLEntryPos pos)
Returns the value that corresponds to named position pos from the data layout entry attr assuming it's a dense integer elements attribute.
std::unique_ptr<::mlir::Pass > createLLVMAddComdats ()
void legalizeDIExpressionsRecursively (Operation *op)
Register all known legalization patterns declared here and apply them to all ops in op.
void registerInlinerInterface (DialectRegistry &registry)
Register the LLVMInlinerInterface implementation of DialectInlinerInterface with the LLVM dialect.
std::unique_ptr<::mlir::Pass > createLLVMLegalizeForExportPass ()
void ensureDistinctSuccessors (Operation *op)
Make argument-taking successors of each block distinct.
std::unique_ptr<::mlir::Pass > createNVVMOptimizeForTargetPass ()
std::unique_ptr<::mlir::Pass > createDIScopeForLLVMFuncOpPass ()
std::unique_ptr<::mlir::Pass > createDIScopeForLLVMFuncOpPass (DIScopeForLLVMFuncOpPassOptions options)
std::unique_ptr<::mlir::Pass > createLLVMRequestCWrappersPass ()
std::unique_ptr<::mlir::Pass > createLLVMUseDefaultVisibilityPass ()
std::unique_ptr<::mlir::Pass > createLLVMUseDefaultVisibilityPass (LLVMUseDefaultVisibilityPassOptions options)
void registerDIScopeForLLVMFuncOpPass ()
void registerDIScopeForLLVMFuncOpPassPass ()
void registerLLVMAddComdats ()
void registerLLVMAddComdatsPass ()
void registerLLVMLegalizeForExportPass ()
void registerLLVMLegalizeForExportPassPass ()
void registerLLVMRequestCWrappersPass ()
void registerLLVMRequestCWrappersPassPass ()
void registerLLVMUseDefaultVisibilityPass ()
void registerLLVMUseDefaultVisibilityPassPass ()
void registerNVVMOptimizeForTargetPass ()
void registerNVVMOptimizeForTargetPassPass ()
void registerLLVMPasses ()
llvm::Constant * createSourceLocStrFromLocation (Location loc, llvm::OpenMPIRBuilder &builder, StringRef name, uint32_t &strLen)
Create a constant string location from the MLIR Location information.
llvm::Constant * createMappingInformation (Location loc, llvm::OpenMPIRBuilder &builder)
Create a constant string representing the mapping information extracted from the MLIR location information.
std::unique_ptr<::mlir::Pass > createLLVMTargetToDataLayout ()
std::unique_ptr<::mlir::Pass > createLLVMTargetToDataLayout (LLVMTargetToDataLayoutOptions options)
std::unique_ptr<::mlir::Pass > createLLVMTargetToTargetFeatures ()
std::unique_ptr<::mlir::Pass > createLLVMTargetToTargetFeatures (LLVMTargetToTargetFeaturesOptions options)
void registerLLVMTargetToDataLayout ()
void registerLLVMTargetToDataLayoutPass ()
void registerLLVMTargetToTargetFeatures ()
void registerLLVMTargetToTargetFeaturesPass ()
void registerTargetLLVMIRTransformsPasses ()
void registerTargetLLVMPasses ()
Variables
constexpr int kGEPConstantBitWidth = 29
Bit-width of a 'GEPConstantIndex' within GEPArg.
Typedef Documentation
GEPConstantIndex
using mlir::LLVM::GEPConstantIndex
Initial value:
    llvm::PointerEmbeddedInt<int32_t, kGEPConstantBitWidth>
Wrapper around a int32_t for use in a PointerUnion.
Definition at line 64 of file LLVMDialect.h.
Enumeration Type Documentation
PtrDLEntryPos
enum class mlir::LLVM::PtrDLEntryPos strong
The positions of different values in the data layout entry for pointers.
Enumerator
Size
Abi
Preferred
Index
Definition at line 146 of file LLVMTypes.h.
Function Documentation
composeValue()
Value mlir::LLVM::composeValue (OpBuilder & builder, Location loc, ValueRange src, Type dstType)
Composes a set of src values into a single value of type dstType through series of bitcasts and vector ops.
Inversely to decomposeValue, this function is used to combine multiple values into a single value.
Definition at line 432 of file Pattern.cpp.
References createI32Constant(), getBitWidth(), mlir::Builder::getIntegerType(), mlir::Value::getType(), and mlir::ValueRange::getType().
convertArrayToIndices() [1/2]
template<typename IntT = int64_t> SmallVector< IntT > mlir::LLVM::convertArrayToIndices (ArrayAttr attrs)
Convert an ArrayAttr of integer attributes to a vector of integers that can be used as indices in LLVM operations.
Definition at line 238 of file LLVMDialect.h.
References ArrayAttr(), and convertArrayToIndices().
convertArrayToIndices() [2/2]
template<typename IntT = int64_t> SmallVector< IntT > mlir::LLVM::convertArrayToIndices (ArrayRef< Attribute > attrs)
Convert an array of integer attributes to a vector of integers that can be used as indices in LLVM operations.
Definition at line 227 of file LLVMDialect.h.
References indices.
Referenced by convertArrayToIndices().
createDIScopeForLLVMFuncOpPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createDIScopeForLLVMFuncOpPass ()
Definition at line 105 of file DIScopeForLLVMFuncOp.cpp.
References getNestedLoc().
createDIScopeForLLVMFuncOpPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createDIScopeForLLVMFuncOpPass (DIScopeForLLVMFuncOpPassOptions options)
Definition at line 109 of file DIScopeForLLVMFuncOp.cpp.
createGlobalString()
Value mlir::LLVM::createGlobalString (Location loc, OpBuilder & builder, StringRef name, StringRef value, Linkage linkage)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
Obtain the address of that global and use it to compute the address of the first character in the string (operations inserted at the builder insertion point).
createLLVMAddComdats()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMAddComdats ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 184 of file AddComdats.cpp.
createLLVMLegalizeForExportPass()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMLegalizeForExportPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 259 of file LegalizeForExport.cpp.
createLLVMRequestCWrappersPass()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMRequestCWrappersPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 334 of file RequestCWrappers.cpp.
createLLVMTargetToDataLayout() [1/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMTargetToDataLayout ()
Definition at line 96 of file TargetToDataLayout.cpp.
createLLVMTargetToDataLayout() [2/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMTargetToDataLayout (LLVMTargetToDataLayoutOptions options)
Definition at line 100 of file TargetToDataLayout.cpp.
createLLVMTargetToTargetFeatures() [1/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMTargetToTargetFeatures ()
Definition at line 191 of file TargetToTargetFeatures.cpp.
createLLVMTargetToTargetFeatures() [2/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMTargetToTargetFeatures (LLVMTargetToTargetFeaturesOptions options)
Definition at line 195 of file TargetToTargetFeatures.cpp.
createLLVMUseDefaultVisibilityPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMUseDefaultVisibilityPass ()
Definition at line 428 of file UseDefaultVisibilityPass.cpp.
createLLVMUseDefaultVisibilityPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::LLVM::createLLVMUseDefaultVisibilityPass (LLVMUseDefaultVisibilityPassOptions options)
Definition at line 432 of file UseDefaultVisibilityPass.cpp.
createMappingInformation()
llvm::Constant * mlir::LLVM::createMappingInformation (Location loc, llvm::OpenMPIRBuilder & builder)
Create a constant string representing the mapping information extracted from the MLIR location information.
Definition at line 32 of file OpenMPCommon.cpp.
References createSourceLocStrFromLocation().
Referenced by mapParentWithMembers(), processMapMembersWithParent(), and processOperands().
createNVVMOptimizeForTargetPass()
std::unique_ptr<::mlir::Pass > mlir::LLVM::createNVVMOptimizeForTargetPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 507 of file OptimizeForNVVM.cpp.
createPrintStrCall()
LogicalResult mlir::LLVM::createPrintStrCall (OpBuilder & builder, Location loc, ModuleOp moduleOp, StringRef symbolName, StringRef string, const LLVMTypeConverter & typeConverter, bool addNewline = true, std::optional< StringRef > runtimeFunctionName = {}, SymbolTableCollection * symbolTables = nullptr)
Generate IR that prints the given string to stdout.
If a custom runtime function is defined via runtimeFunctionName, it must have the signature void(char const*). The default function is printString.
Definition at line 48 of file PrintCallHelper.cpp.
References ensureSymbolNameIsUnique(), mlir::DenseElementsAttr::get(), mlir::Builder::getContext(), mlir::Builder::getI8Type(), indices, lookupOrCreatePrintStringFn(), mlir::OpBuilder::restoreInsertionPoint(), mlir::OpBuilder::saveInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), success(), and TypeRange.
createSourceLocStrFromLocation()
llvm::Constant * mlir::LLVM::createSourceLocStrFromLocation (Location loc, llvm::OpenMPIRBuilder & builder, StringRef name, uint32_t & strLen)
Create a constant string location from the MLIR Location information.
Definition at line 16 of file OpenMPCommon.cpp.
Referenced by createMappingInformation(), and createSourceLocationInfo().
decomposeValue()
SmallVector< Value > mlir::LLVM::decomposeValue (OpBuilder & builder, Location loc, Value src, Type dstType)
Decomposes a src value into a set of values of type dstType through series of bitcasts and vector ops.
Src and dst types are expected to be int or float types or vector types of them.
Definition at line 393 of file Pattern.cpp.
References createI32Constant(), getBitWidth(), mlir::Builder::getIntegerType(), and mlir::Value::getType().
DEFINE_TRIVIAL_LLVM_TYPE() [1/4]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMLabelType , "llvm.label")
DEFINE_TRIVIAL_LLVM_TYPE() [2/4]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMMetadataType , "llvm.metadata")
DEFINE_TRIVIAL_LLVM_TYPE() [3/4]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMTokenType , "llvm.token")
DEFINE_TRIVIAL_LLVM_TYPE() [4/4]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMVoidType , "llvm.void")
ensureDistinctSuccessors()
void mlir::LLVM::ensureDistinctSuccessors (Operation * op)
Make argument-taking successors of each block distinct.
PHI nodes in LLVM IR use the predecessor ID to identify which value to take. They do not support different values coming from the same predecessor. If a block has another block as a successor more than once with different values, insert a new dummy block for LLVM PHI nodes to tell the sources apart.
Definition at line 67 of file LegalizeForExport.cpp.
References ensureDistinctSuccessors(), mlir::Operation::getRegions(), and mlir::Operation::walk().
extractPointerSpecValue()
std::optional< uint64_t > mlir::LLVM::extractPointerSpecValue (Attribute attr, PtrDLEntryPos pos)
Returns the value that corresponds to named position pos from the data layout entry attr assuming it's a dense integer elements attribute.
Returns std::nullopt if pos is not present in the entry. Currently only PtrDLEntryPos::Index is optional, and all other positions may be assumed to be present.
Definition at line 266 of file LLVMTypes.cpp.
Referenced by getPointerDataLayoutEntry().
getPrimitiveTypeSizeInBits()
llvm::TypeSize mlir::LLVM::getPrimitiveTypeSizeInBits (Type type)
Returns the size of the given primitive LLVM dialect-compatible type (including vectors) in bits, for example, the size of i16 is 16 and the size of vector<4xi16> is 64.
Returns 0 for non-primitive (aggregates such as struct) or types that don't have a size (such as void).
Definition at line 887 of file LLVMTypes.cpp.
References getPrimitiveTypeSizeInBits(), isCompatibleType(), and isCompatibleVectorType().
Referenced by getPrimitiveTypeSizeInBits().
getStridedElementPtr()
Value mlir::LLVM::getStridedElementPtr (OpBuilder & builder, Location loc, const LLVMTypeConverter & converter, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags = LLVM::GEPNoWrapFlags::none)
Performs the index computation to get to the element at indices of the memory pointed to by memRefDesc, using the layout map of type.
The indices are linearized as: base_offset + index_0 * stride_0 + ... + index_n * stride_n.
Definition at line 471 of file Pattern.cpp.
References mlir::MemRefDescriptor::bufferPtr(), mlir::MemRefDescriptor::getElementPtrType(), mlir::Builder::getIndexAttr(), mlir::LLVMTypeConverter::getIndexType(), indices, and mlir::MemRefDescriptor::stride().
Referenced by mlir::ConvertToLLVMPattern::getStridedElementPtr().
getVectorNumElements()
llvm::ElementCount mlir::LLVM::getVectorNumElements (Type type)
Returns the element count of any LLVM-compatible vector type.
Definition at line 857 of file LLVMTypes.cpp.
Referenced by getI1SameShape(), and verifyExtOp().
getVectorType() [1/2]
Type mlir::LLVM::getVectorType (Type elementType, const llvm::ElementCount & numElements)
Creates an LLVM dialect-compatible vector type with the given element type and length.
Definition at line 878 of file LLVMTypes.cpp.
References getVectorType().
getVectorType() [2/2]
Type mlir::LLVM::getVectorType (Type elementType, unsigned numElements, bool isScalable = false)
Creates an LLVM dialect-compatible vector type with the given element type and length.
Definition at line 871 of file LLVMTypes.cpp.
Referenced by getI1SameShape(), getIndexedPtrs(), getVectorType(), and parseShuffleType().
isCompatibleFloatingPointType()
bool mlir::LLVM::isCompatibleFloatingPointType (Type type)
Returns true if the given type is a floating-point type compatible with the LLVM dialect.
Definition at line 838 of file LLVMTypes.cpp.
Referenced by isTypeCompatibleWithAtomicOp().
isCompatibleOuterType()
bool mlir::LLVM::isCompatibleOuterType (Type type)
Returns true if the given outer type is compatible with the LLVM dialect without checking its potential nested types such as struct elements.
Definition at line 720 of file LLVMTypes.cpp.
References isCompatiblePtrType().
Referenced by isLoadableType(), and mlir::LLVM::detail::parseType().
isCompatibleType()
bool mlir::LLVM::isCompatibleType (Type type)
Returns true if the given type is compatible with the LLVM dialect.
This is an alias to LLVMDialect::isCompatibleType.
Definition at line 813 of file LLVMTypes.cpp.
References mlir::Type::getContext(), mlir::MLIRContext::getLoadedDialect(), and isCompatibleImpl().
Referenced by areAllLLVMTypes(), mlir::impl::ArithToLLVMConversionPassBase< DerivedT >::ArithToLLVMConversionPassBase(), buildLLVMFunctionType(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), dispatchPrint(), mlir::LLVM::detail::extractNDVectorTypeInfo(), mlir::impl::ArithToLLVMConversionPassBase< DerivedT >::getDescription(), getInsertExtractValueElementType(), getPrimitiveTypeSizeInBits(), mlir::LLVM::detail::intrinsicRewrite(), mlir::LLVMTypeConverter::LLVMTypeConverter(), optionallyTruncateOrExtend(), mlir::LLVMTypeConverter::packOperationResults(), parseCmpOp(), mlir::StructBuilder::StructBuilder(), and mlir::LLVM::detail::vectorOneToOneRewrite().
isCompatibleVectorType()
bool mlir::LLVM::isCompatibleVectorType (Type type)
Returns true if the given type is a vector type compatible with the LLVM dialect.
Compatible types include 1D built-in vector types of built-in integers and floating-point values, LLVM dialect fixed vector types of LLVM dialect pointers and LLVM dialect scalable vector types.
Definition at line 843 of file LLVMTypes.cpp.
References isCompatiblePtrType().
Referenced by mlir::LLVM::detail::extractNDVectorTypeInfo(), getI1SameShape(), getPrimitiveTypeSizeInBits(), parseShuffleType(), and verifyExtOp().
isLoadableType()
bool mlir::LLVM::isLoadableType (Type type)
Returns true if the given type is a loadable type compatible with the LLVM dialect.
Definition at line 826 of file LLVMTypes.cpp.
References isCompatibleOuterType().
Referenced by mlir::LLVM::detail::isValidLoadStoreImpl().
isScalableVectorType()
bool mlir::LLVM::isScalableVectorType (Type vectorType)
Returns whether a vector type is scalable or not.
Definition at line 865 of file LLVMTypes.cpp.
Referenced by parseShuffleType().
isTypeCompatibleWithAtomicOp()
bool mlir::LLVM::isTypeCompatibleWithAtomicOp (Type type, const DataLayout & dataLayout)
Returns true if the given type is supported by atomic operations.
All integer, float, and pointer types with a power-of-two bitsize and a minimal size of 8 bits are supported.
Definition at line 856 of file LLVMDialect.cpp.
References mlir::DataLayout::getTypeSizeInBits(), and isCompatibleFloatingPointType().
Referenced by mlir::LLVM::detail::isValidLoadStoreImpl(), and verifyAtomicMemOp().
legalizeDIExpressionsRecursively()
void mlir::LLVM::legalizeDIExpressionsRecursively (Operation * op)
Register all known legalization patterns declared here and apply them to all ops in op.
Definition at line 52 of file DIExpressionLegalization.cpp.
References mlir::LLVM::DIExpressionRewriter::addPattern(), mlir::detail::AttrTypeReplacerBase< Concrete >::addReplacement(), mlir::detail::AttrTypeReplacerBase< Concrete >::recursivelyReplaceElementsIn(), and mlir::LLVM::DIExpressionRewriter::simplify().
lookupOrCreateAlignedAllocFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateAlignedAllocFn (OpBuilder & b, Operation * moduleOp, Type indexType, SymbolTableCollection * symbolTables = nullptr)
Definition at line 235 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), getVoidPtr(), kAlignedAlloc, and lookupOrCreateReservedFn().
lookupOrCreateApFloatPrintFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateApFloatPrintFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 165 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintApFloat, and lookupOrCreateReservedFn().
lookupOrCreateFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateFn (OpBuilder & b, Operation * moduleOp, StringRef name, ArrayRef< Type > paramTypes = {}, Type resultType = {}, bool isVarArg = false, bool isReserved = false, SymbolTableCollection * symbolTables = nullptr)
Create a FuncOp with signature resultType(paramTypes) and name name`.
Generic print function lookupOrCreate helper.
Return a failure if the FuncOp found has unexpected signature.
Definition at line 66 of file FunctionCallUtils.cpp.
References b, mlir::Block::begin(), mlir::Region::empty(), mlir::Region::front(), mlir::Operation::getLoc(), mlir::Operation::getRegion(), mlir::SymbolTableCollection::getSymbolTable(), mlir::Operation::hasTrait(), and mlir::SymbolTable::insert().
Referenced by lookupOrCreateReservedFn(), and ConvertNativeFuncPattern< Op >::matchAndRewrite().
lookupOrCreateFreeFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateFreeFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 244 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), getVoidPtr(), kFree, and lookupOrCreateReservedFn().
Referenced by mlir::ConvertToLLVMPattern::copyUnrankedDescriptor().
lookupOrCreateGenericAlignedAllocFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateGenericAlignedAllocFn (OpBuilder & b, Operation * moduleOp, Type indexType, SymbolTableCollection * symbolTables = nullptr)
Definition at line 260 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), getVoidPtr(), kGenericAlignedAlloc, and lookupOrCreateReservedFn().
lookupOrCreateGenericAllocFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateGenericAllocFn (OpBuilder & b, Operation * moduleOp, Type indexType, SymbolTableCollection * symbolTables = nullptr)
Definition at line 252 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), getVoidPtr(), kGenericAlloc, and lookupOrCreateReservedFn().
lookupOrCreateGenericFreeFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateGenericFreeFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 269 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), getVoidPtr(), kGenericFree, and lookupOrCreateReservedFn().
lookupOrCreateMallocFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateMallocFn (OpBuilder & b, Operation * moduleOp, Type indexType, SymbolTableCollection * symbolTables = nullptr)
Definition at line 226 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), getVoidPtr(), kMalloc, and lookupOrCreateReservedFn().
Referenced by mlir::ConvertToLLVMPattern::copyUnrankedDescriptor().
lookupOrCreateMemRefCopyFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreateMemRefCopyFn (OpBuilder & b, Operation * moduleOp, Type indexType, Type unrankedDescriptorType, SymbolTableCollection * symbolTables = nullptr)
Definition at line 276 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kMemRefCopy, and lookupOrCreateReservedFn().
lookupOrCreatePrintBF16Fn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintBF16Fn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 140 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintBF16, and lookupOrCreateReservedFn().
lookupOrCreatePrintCloseFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintCloseFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 202 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintClose, and lookupOrCreateReservedFn().
lookupOrCreatePrintCommaFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintCommaFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 210 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintComma, and lookupOrCreateReservedFn().
lookupOrCreatePrintF16Fn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintF16Fn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 131 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintF16, and lookupOrCreateReservedFn().
lookupOrCreatePrintF32Fn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintF32Fn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 149 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintF32, and lookupOrCreateReservedFn().
lookupOrCreatePrintF64Fn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintF64Fn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 157 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintF64, and lookupOrCreateReservedFn().
lookupOrCreatePrintI64Fn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintI64Fn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Helper functions to look up or create the declaration for commonly used external C function calls.
The list of functions provided here must be implemented separately (e.g. as part of a support runtime library or as part of the libc). Failure if an unexpected version of function is found.
Definition at line 115 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintI64, and lookupOrCreateReservedFn().
lookupOrCreatePrintNewlineFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintNewlineFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 218 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintNewline, and lookupOrCreateReservedFn().
lookupOrCreatePrintOpenFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintOpenFn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 194 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintOpen, and lookupOrCreateReservedFn().
lookupOrCreatePrintStringFn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintStringFn (OpBuilder & b, Operation * moduleOp, std::optional< StringRef > runtimeFunctionName = {}, SymbolTableCollection * symbolTables = nullptr)
Declares a function to print a C-string.
If a custom runtime function is defined via runtimeFunctionName, it must have the signature void(char const*). The default function is printString.
Definition at line 183 of file FunctionCallUtils.cpp.
References b, getCharPtr(), mlir::Operation::getContext(), kPrintString, and lookupOrCreateReservedFn().
Referenced by createPrintStrCall().
lookupOrCreatePrintU64Fn()
FailureOr< LLVM::LLVMFuncOp > mlir::LLVM::lookupOrCreatePrintU64Fn (OpBuilder & b, Operation * moduleOp, SymbolTableCollection * symbolTables = nullptr)
Definition at line 123 of file FunctionCallUtils.cpp.
References b, mlir::Operation::getContext(), kPrintU64, and lookupOrCreateReservedFn().
parentLLVMModule()
Operation * mlir::LLVM::parentLLVMModule (Operation * op)
Lookup parent Module satisfying LLVM conditions on the Module Operation.
Definition at line 4538 of file LLVMDialect.cpp.
References mlir::Operation::getParentOp(), and satisfiesLLVMModule().
Referenced by convertOperationImpl().
parsePrettyLLVMType()
ParseResult mlir::LLVM::parsePrettyLLVMType (AsmParser & p, Type & type)
Parse any MLIR type or a concise syntax for LLVM types.
Definition at line 303 of file LLVMTypeSyntax.cpp.
References dispatchParse().
Referenced by parseExtTypeParams(), and parseFunctionTypes().
printPrettyLLVMType()
void mlir::LLVM::printPrettyLLVMType (AsmPrinter & p, Type type)
Print any MLIR type or a concise syntax for LLVM types.
Definition at line 307 of file LLVMTypeSyntax.cpp.
References dispatchPrint().
Referenced by printFunctionTypes().
registerDIScopeForLLVMFuncOpPass()
void mlir::LLVM::registerDIScopeForLLVMFuncOpPass () inline
Definition at line 527 of file Passes.h.
registerDIScopeForLLVMFuncOpPassPass()
void mlir::LLVM::registerDIScopeForLLVMFuncOpPassPass () inline
Definition at line 534 of file Passes.h.
registerInlinerInterface()
void mlir::LLVM::registerInlinerInterface (DialectRegistry & registry)
Register the LLVMInlinerInterface implementation of DialectInlinerInterface with the LLVM dialect.
Definition at line 829 of file InlinerInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects().
registerLLVMAddComdats()
void mlir::LLVM::registerLLVMAddComdats () inline
Definition at line 548 of file Passes.h.
registerLLVMAddComdatsPass()
void mlir::LLVM::registerLLVMAddComdatsPass () inline
Definition at line 555 of file Passes.h.
registerLLVMLegalizeForExportPass()
void mlir::LLVM::registerLLVMLegalizeForExportPass () inline
Definition at line 569 of file Passes.h.
registerLLVMLegalizeForExportPassPass()
void mlir::LLVM::registerLLVMLegalizeForExportPassPass () inline
Definition at line 576 of file Passes.h.
registerLLVMPasses()
void mlir::LLVM::registerLLVMPasses () inline
Definition at line 653 of file Passes.h.
Referenced by mlir::registerAllPasses().
registerLLVMRequestCWrappersPass()
void mlir::LLVM::registerLLVMRequestCWrappersPass () inline
Definition at line 590 of file Passes.h.
registerLLVMRequestCWrappersPassPass()
void mlir::LLVM::registerLLVMRequestCWrappersPassPass () inline
Definition at line 597 of file Passes.h.
registerLLVMTargetToDataLayout()
void mlir::LLVM::registerLLVMTargetToDataLayout () inline
Definition at line 211 of file Passes.h.
registerLLVMTargetToDataLayoutPass()
void mlir::LLVM::registerLLVMTargetToDataLayoutPass () inline
Definition at line 218 of file Passes.h.
registerLLVMTargetToTargetFeatures()
void mlir::LLVM::registerLLVMTargetToTargetFeatures () inline
Definition at line 232 of file Passes.h.
registerLLVMTargetToTargetFeaturesPass()
void mlir::LLVM::registerLLVMTargetToTargetFeaturesPass () inline
Definition at line 239 of file Passes.h.
registerLLVMUseDefaultVisibilityPass()
void mlir::LLVM::registerLLVMUseDefaultVisibilityPass () inline
Definition at line 611 of file Passes.h.
registerLLVMUseDefaultVisibilityPassPass()
void mlir::LLVM::registerLLVMUseDefaultVisibilityPassPass () inline
Definition at line 618 of file Passes.h.
registerNVVMOptimizeForTargetPass()
void mlir::LLVM::registerNVVMOptimizeForTargetPass () inline
Definition at line 632 of file Passes.h.
registerNVVMOptimizeForTargetPassPass()
void mlir::LLVM::registerNVVMOptimizeForTargetPassPass () inline
Definition at line 639 of file Passes.h.
registerTargetLLVMIRTransformsPasses()
void mlir::LLVM::registerTargetLLVMIRTransformsPasses () inline
Definition at line 253 of file Passes.h.
Referenced by mlir::registerAllPasses().
registerTargetLLVMPasses()
void mlir::LLVM::registerTargetLLVMPasses ()
satisfiesLLVMModule()
bool mlir::LLVM::satisfiesLLVMModule (Operation * op)
LLVM requires some operations to be inside of a Module operation.
This function confirms that the Operation has the desired properties.
Definition at line 4533 of file LLVMDialect.cpp.
References mlir::Operation::hasTrait().
Referenced by parentLLVMModule().
Variable Documentation
kGEPConstantBitWidth
int mlir::LLVM::kGEPConstantBitWidth = 29 constexpr
Bit-width of a 'GEPConstantIndex' within GEPArg.
Definition at line 62 of file LLVMDialect.h.
Referenced by destructureIndices(), and getSubslotAccessInfo().