MLIR: mlir::OpTrait Namespace Reference
mlir::OpTrait Namespace Reference
Namespaces
namespace detail
namespace impl
namespace spirv
namespace tosa
namespace util
Classes
class AffineScope
A trait of region holding operations that defines a new scope for polyhedral optimization purposes.
struct AlwaysSpeculatableImplTrait
This trait marks an op (which must be tagged as implementing the ConditionallySpeculatable interface) as being always speculatable.
class AtLeastNOperands
This class provides the API for ops that are known to have a at least a specified number of operands.
class AtLeastNRegions
This class provides APIs for ops that are known to have at least a specified number of regions.
class AtLeastNResults
This class provides the API for ops that are known to have at least a specified number of results.
class AtLeastNSuccessors
This class provides APIs for ops that are known to have at least a specified number of successors.
class AtMostOneChildOf
Characterize operations that have at most a single operation of certain types in their region.
class AttrSizedOperandSegments
A trait for operations that have an attribute specifying operand segments.
class AttrSizedResultSegments
Similar to AttrSizedOperandSegments but used for results.
class AutomaticAllocationScope
A trait of region holding operations that define a new scope for automatic allocations, i.e., allocations that are freed when control is transferred back from the operation's region.
class ConstantLike
This class provides the API for a sub-set of ops that are known to be constant-like.
class DistinctObjectsTrait
This trai indicates that pointer-like objects (such as memrefs) returned from this operation will never alias with each other.
struct Elementwise
This trait tags element-wise ops on vectors or tensors.
class HasOnlyGraphRegion
A trait that specifies that an operation only defines graph regions.
class HasParallelRegion
struct HasParent
This class provides a verifier for ops that are expecting their parent to be one of the given parent ops.
class HasRecursiveMemoryEffects
This trait indicates that the memory effects of an operation includes the effects of operations nested within its regions.
struct hasSingleBlockImplicitTerminator
Support to check if an operation has the SingleBlockImplicitTerminator trait.
struct hasSingleBlockImplicitTerminator< Op, false >
class InferShapedTypeOpAdaptor
class InferTensorType
Tensor type inference trait that constructs a tensor from the inferred shape and elemental types.
class InferTypeOpAdaptor
class IsCommutative
This class adds property that the operation is commutative.
class IsIdempotent
This class adds property that the operation is idempotent.
class IsInvolution
This class adds property that the operation is an involution.
class IsIsolatedFromAbove
This class provides the API for ops that are known to be isolated from above.
class IsTerminator
This class provides the API for ops that are known to be terminators.
struct MemRefsNormalizable
class NOperands
This class provides the API for ops that are known to have a specified number of operands.
struct NoRegionArguments
This trait provides a verifier for ops that are expecting their regions to not have any arguments.
class NoTerminator
This class indicates that the regions associated with this op don't have terminators.
class NRegions
This class provides the API for ops that are known to have a specified number of regions.
class NResults
This class provides the API for ops that are known to have a specified number of results.
class NSuccessors
This class provides the API for ops that are known to have a specified number of successors.
class NVVMRequiresSM
class NVVMRequiresSMa
class OneOperand
This class provides the API for ops that are known to have exactly one SSA operand.
class OneRegion
This class provides APIs for ops that are known to have a single region.
class OneResult
This class provides return value APIs for ops that are known to have a single result.
class OneSuccessor
This class provides APIs for ops that are known to have a single successor.
class OneTypedResult
This trait is used for return value APIs for ops that are known to have a specific type other than Type.
class OperandsAreFloatLike
This class verifies that all operands of the specified op have a float type, a vector thereof, or a tensor thereof.
class OperandsAreSignlessIntegerLike
This class verifies that all operands of the specified op have a signless integer or index type, a vector thereof, or a tensor thereof.
class OpInvariants
verifyInvariantsImpl verifies the invariants like the types, attrs, .etc.
struct RecursivelySpeculatableImplTrait
This trait marks an op (which must be tagged as implementing the ConditionallySpeculatable interface) as being recursively speculatable.
class ResultsAreBoolLike
This class verifies that any results of the specified op have a boolean type, a vector thereof, or a tensor thereof.
class ResultsAreFloatLike
This class verifies that any results of the specified op have a floating point type, a vector thereof, or a tensor thereof.
class ResultsAreSignlessIntegerLike
This class verifies that any results of the specified op have a signless integer or index type, a vector thereof, or a tensor thereof.
class ResultsBroadcastableShape
Trait for ops that are known to have broadcast compatible operands and result types.
struct ReturnLike
This trait indicates that a terminator operation is "return-like".
class SameOperandsAndResultElementType
This class provides verification for ops that are known to have the same operand and result element type (or the type itself if it is scalar).
class SameOperandsAndResultRank
This class verifies that op has same ranks for all operands and results types, if known.
class SameOperandsAndResultShape
This class provides verification for ops that are known to have the same operand and result shape: both are scalars, vectors/tensors of the same shape.
class SameOperandsAndResultType
This class provides verification for ops that are known to have the same operand and result type.
class SameOperandsElementType
This class provides verification for ops that are known to have the same operand element type (or the type itself if it is scalar).
class SameOperandsShape
This class provides verification for ops that are known to have the same operand shape: all operands are scalars, vectors/tensors of the same shape.
class SameTypeOperands
This class verifies that all operands of the specified op have the same type.
struct Scalarizable
This trait tags Elementwise operatons that can be systematically scalarized.
struct SingleBlock
This class provides APIs and verifiers for ops with regions having a single block.
struct SingleBlockImplicitTerminator
This class provides APIs and verifiers for ops with regions having a single block that must terminate with TerminatorOpType.
class SymbolTable
A trait used to provide symbol table functionalities to a region operation.
struct Tensorizable
This trait tags Elementwise operatons that can be systematically tensorized.
class TraitBase
Helper class for implementing traits.
class VariadicOperands
This class provides the API for ops which have an unknown number of SSA operands.
class VariadicRegions
This class provides the API for ops which have an unknown number of regions.
class VariadicResults
This class provides the API for ops which have an unknown number of results.
class VariadicSuccessors
This class provides the API for ops which have an unknown number of successors.
struct Vectorizable
This trait tags Elementwise operatons that can be systematically vectorized.
class ZeroOperands
This class provides the API for ops that are known to have no SSA operand.
class ZeroRegions
This class provides verification for ops that are known to have zero regions.
class ZeroResults
This class provides return value APIs for ops that are known to have zero results.
class ZeroSuccessors
This class provides verification for ops that are known to have zero successors.
Typedefs
template<class T>
using has_implicit_terminator_t = typename T::ImplicitTerminatorOpT
Check is an op defines the ImplicitTerminatorOpT member.
Functions
bool hasElementwiseMappableTraits (Operation *op)
Together, Elementwise, Scalarizable, Vectorizable, and Tensorizable provide an easy way for scalar operations to conveniently generalize their behavior to vectors/tensors, and systematize conversion between these forms.
Typedef Documentation
has_implicit_terminator_t
template<class T> using mlir::OpTrait::has_implicit_terminator_t = typename T::ImplicitTerminatorOpT
Check is an op defines the ImplicitTerminatorOpT member.
This is intended to be used with llvm::is_detected.
Definition at line 1024 of file OpDefinition.h.
Function Documentation
hasElementwiseMappableTraits()
bool mlir::OpTrait::hasElementwiseMappableTraits (Operation * op)
Together, Elementwise, Scalarizable, Vectorizable, and Tensorizable provide an easy way for scalar operations to conveniently generalize their behavior to vectors/tensors, and systematize conversion between these forms.
Definition at line 1390 of file Operation.cpp.
References mlir::Operation::hasTrait().
Referenced by mlir::spirv::getNativeVectorShape(), getSubgroupMmaNativeVectorSize(), mlir::linalg::hasOnlyScalarElementwiseOp(), isElementwiseMappableOpOnRankedTensors(), vectorizeOneOp(), and mlir::xegpu::impl::XeGPUWgToSgDistributeBase< DerivedT >::~XeGPUWgToSgDistributeBase().