MLIR: mlir::ub Namespace Reference
mlir::ub Namespace Reference
Namespaces
namespace detail
Functions
void populateUBToLLVMConversionPatterns (const LLVMTypeConverter &converter, RewritePatternSet &patterns)
void registerConvertUBToLLVMInterface (DialectRegistry &registry)
void populateUBToSPIRVConversionPatterns (const SPIRVTypeConverter &converter, RewritePatternSet &patterns)
detail::poison_attr_matcher m_Poison ()
Matches a poison constant (any attribute implementing PoisonAttrInterface).
Function Documentation
m_Poison()
detail::poison_attr_matcher mlir::ub::m_Poison () inline
Matches a poison constant (any attribute implementing PoisonAttrInterface).
Works with matchPattern on Value, Operation*, and Attribute.
Examples: matchPattern(value, ub::m_Poison()) // Matches ub.poison op via Value. matchPattern(op, ub::m_Poison()) // Matches ub.poison op directly. matchPattern(attr, ub::m_Poison()) // Matches PoisonAttr(Interface).
Definition at line 46 of file UBMatchers.h.
Referenced by foldFromElementsToConstant(), foldPoisonSrcExtractOp(), foldShuffleConstantInputs(), foldShufflePoisonInputs(), foldShufflePoisonOperandToMask(), and padOperand().
populateUBToLLVMConversionPatterns()
void mlir::ub::populateUBToLLVMConversionPatterns (const LLVMTypeConverter & converter, RewritePatternSet & patterns)
Definition at line 115 of file UBToLLVM.cpp.
References mlir::RewritePatternSet::add().
populateUBToSPIRVConversionPatterns()
void mlir::ub::populateUBToSPIRVConversionPatterns (const SPIRVTypeConverter & converter, RewritePatternSet & patterns)
Definition at line 87 of file UBToSPIRV.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
registerConvertUBToLLVMInterface()
void mlir::ub::registerConvertUBToLLVMInterface (DialectRegistry & registry)
Definition at line 144 of file UBToLLVM.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllExtensions().