MLIR: mlir::mesh::detail Namespace Reference
mlir::mesh::detail Namespace Reference
Functions
FailureOr< ShardingOption > defaultGetShardingOption (Operation *op, ArrayRef< MeshSharding > operandShardings, ArrayRef< MeshSharding > resultShardings)
FailureOr< std::vector< MeshSharding > > defaultGetShardingAnnotations (Operation *op, const ShardingOption &shardingOption)
LogicalResult defaultAddShardingAnnotations (Operation *op, OpBuilder &b, const ShardingOption &shardingOption)
Function Documentation
defaultAddShardingAnnotations()
LogicalResult mlir::mesh::detail::defaultAddShardingAnnotations (Operation * op, OpBuilder & b, const ShardingOption & shardingOption)
Definition at line 547 of file ShardingInterface.cpp.
References addShardOp(), mlir::mesh::ShardingOption::empty, mlir::Operation::getNumOperands(), mlir::Operation::getOpOperands(), mlir::Operation::getResults(), and mlir::mesh::ShardingOption::mesh.
defaultGetShardingAnnotations()
FailureOr< std::vector< MeshSharding > > mlir::mesh::detail::defaultGetShardingAnnotations (Operation * op, const ShardingOption & shardingOption)
Definition at line 483 of file ShardingInterface.cpp.
References mlir::Operation::getNumOperands(), mlir::Operation::getOpOperands(), mlir::Operation::getResults(), and getSharding().
defaultGetShardingOption()
FailureOr< ShardingOption > mlir::mesh::detail::defaultGetShardingOption (Operation * op, ArrayRef< MeshSharding > operandShardings, ArrayRef< MeshSharding > resultShardings)
Definition at line 265 of file ShardingInterface.cpp.
References checkOperandAffineExpr(), mlir::Operation::emitOpError(), mlir::mesh::ShardingOption::empty, mlir::detail::enumerate(), mlir::mesh::MeshSharding::getMeshAttr(), mlir::AffineMap::getNumDims(), mlir::Operation::getNumOperands(), mlir::mesh::MeshSharding::getPartialAxes(), mlir::AffineMap::getResults(), mlir::mesh::MeshSharding::getSplitAxes(), mlir::mesh::isReductionLoop(), mlir::mesh::removeTrailingEmptySubArray(), and mlir::mesh::ShardingOption::shardingArray.