MLIR: mlir::shard::detail Namespace Reference
mlir::shard::detail Namespace Reference
Functions
FailureOr< ShardingOption > defaultGetShardingOption (Operation *op, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings)
FailureOr< std::vector< Sharding > > defaultGetShardingAnnotations (Operation *op, const ShardingOption &shardingOption)
LogicalResult defaultAddShardingAnnotations (Operation *op, OpBuilder &b, const ShardingOption &shardingOption)
Function Documentation
defaultAddShardingAnnotations()
LogicalResult mlir::shard::detail::defaultAddShardingAnnotations (Operation * op, OpBuilder & b, const ShardingOption & shardingOption)
Definition at line 487 of file ShardingInterface.cpp.
References addShardOp(), b, mlir::shard::ShardingOption::empty, mlir::Operation::getNumOperands(), mlir::Operation::getOpOperands(), mlir::Operation::getResults(), mlir::shard::ShardingOption::grid, result, and success().
defaultGetShardingAnnotations()
FailureOr< std::vector< Sharding > > mlir::shard::detail::defaultGetShardingAnnotations (Operation * op, const ShardingOption & shardingOption)
Definition at line 428 of file ShardingInterface.cpp.
References mlir::Operation::getNumOperands(), mlir::Operation::getOpOperands(), mlir::Operation::getResults(), mlir::shard::getSharding(), and result.
defaultGetShardingOption()
FailureOr< ShardingOption > mlir::shard::detail::defaultGetShardingOption (Operation * op, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings)
Definition at line 259 of file ShardingInterface.cpp.
References checkOperandAffineExpr(), mlir::Operation::emitOpError(), mlir::shard::ShardingOption::empty, mlir::shard::Sharding::getGridAttr(), mlir::AffineMap::getNumDims(), mlir::Operation::getNumOperands(), mlir::AffineMap::getResults(), mlir::shard::Sharding::getSplitAxes(), mlir::shard::ShardingOption::grid, mlir::shard::removeTrailingEmptySubArray(), and mlir::shard::ShardingOption::shardingArray.