MLIR: mlir::tosa Namespace Reference
mlir::tosa Namespace Reference
Namespaces
namespace detail
Implemented by ops that correspond to the Tosa specification.
namespace impl
Classes
class TargetEnv
This class represents the capability enabled in the target implementation such as profile, extension, and level.
struct TosaAttachTargetOptions
struct TosaInferShapesPassOptions
struct TosaInputShapeOptions
struct TosaLayerwiseConstantFoldPassOptions
struct TosaLevel
struct TosaNarrowF64ToF32PassOptions
struct TosaNarrowI64ToI32PassOptions
class TosaOp
class TosaSpecificationVersion
A thin wrapper around the SpecificationVersion enum to represent and provide utilities around the TOSA specification version.
struct TosaValidationOptions
struct ValueKnowledge
Statically known information for a particular Value.
Functions
void populateTosaToArithConversionPatterns (RewritePatternSet *patterns)
void populateTosaRescaleToArithConversionPatterns (RewritePatternSet *patterns, bool include32Bit=false)
std::unique_ptr< Pass > createTosaToLinalg ()
std::unique_ptr< Pass > createTosaToLinalgNamed (const TosaToLinalgNamedOptions &options=TosaToLinalgNamedOptions())
void addTosaToLinalgPasses (OpPassManager &pm, const TosaToLinalgOptions &options, const TosaToLinalgNamedOptions &tosaToLinalgNamedOptions=TosaToLinalgNamedOptions(), std::optional< tosa::TosaValidationOptions > validationOptions=tosa::TosaValidationOptions{false, false}, std::optional< TosaAttachTargetOptions > attachTargetOptions=std::nullopt)
Populates passes to convert from TOSA to Linalg.
void registerTosaToLinalgPipelines ()
Populates TOSA to linalg pipelines Currently, this includes only the "tosa-to-linalg-pipeline".
void populateTosaToLinalgConversionPatterns (const TypeConverter &converter, RewritePatternSet *patterns)
Populates conversion passes from TOSA dialect to Linalg dialect.
void populateTosaToLinalgNamedConversionPatterns (const TypeConverter &converter, RewritePatternSet *patterns, const TosaToLinalgNamedOptions &options)
Populates conversion passes from TOSA dialect to Linalg named operations.
void populateTosaToMLProgramConversionPatterns (RewritePatternSet *patterns)
void populateTosaToSCFConversionPatterns (RewritePatternSet *patterns)
void addTosaToSCFPasses (OpPassManager &pm)
Populates passes to convert from TOSA to SCF.
std::unique_ptr< Pass > createTosaToSPIRVTosaMarkGraphConstants ()
std::unique_ptr< Pass > createTosaToSPIRVTosa ()
spirv::VerCapExtAttr getDefaultVerCapExtAttr (MLIRContext *context)
spirv::TargetEnvAttr constructTargetEnvAttrWithCapExtDefaults (MLIRContext *context, spirv::ResourceLimitsAttr limits={}, spirv::ClientAPI clientAPI=spirv::ClientAPI::Unknown, spirv::Vendor vendorID=spirv::Vendor::Unknown, spirv::DeviceType deviceType=spirv::DeviceType::Unknown, uint32_t deviceID=spirv::TargetEnvAttr::kUnknownDeviceID)
void populateTosaToSPIRVTosaConversionPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns, spirv::TargetEnvAttr targetAttr)
void populateTosaToSPIRVTosaOpsConversionPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns)
void populateTosaToSPIRVTosaCustomConversionPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns, llvm::StringMap< int32_t > domainToOpcode)
void populateTosaToTensorConversionPatterns (const TypeConverter &converter, RewritePatternSet *patterns)
void registerShardingInterfaceExternalModels (DialectRegistry &registry)
TosaLevel getTosaLevelFromEnum (const Level level)
TargetEnvAttr lookupTargetEnv (Operation *op)
TargetEnvAttr getDefaultTargetEnv (MLIRContext *context)
TargetEnvAttr lookupTargetEnvOrDefault (Operation *op)
Queries the target environment recursively from enclosing symbol table ops containing the given op or returns the default target environment as returned by getDefaultTargetEnv() if not provided.
TosaSpecificationVersion getMinVersion (const Profile &profile)
TosaSpecificationVersion getMinVersion (const Extension &extension)
TosaSpecificationVersion getMinVersion (const Level &level)
llvm::SmallString< 4 > stringifyVersion (TosaSpecificationVersion version)
ParseResult parseVariableOpTypeOrInitialValue (OpAsmParser &parser, DenseElementsAttr &varShapeAttr, TypeAttr &typeAttr, Attribute &initialValueAttr)
void printVariableOpTypeOrInitialValue (OpAsmPrinter &p, Operation *op, DenseElementsAttr varShapeAttr, TypeAttr typeAttr, Attribute initialValueAttr)
bool isa_tosa_shape_type (mlir::Type t)
std::optional< Value > createZeroPointTensor (OpBuilder &builder, Location loc, Type srcElemType, int64_t zp=0)
Value createPadConstTensor (OpBuilder &builder, Location loc, Value src, int32_t val=0)
RankedTensorType getVariableType (VariableOp variableOp)
unsigned getBitWidth (Type type)
Type getStorageElementTypeOrSelf (Type type)
Type getStorageElementTypeOrSelf (Value value)
std::unique_ptr<::mlir::Pass > createTosaArithConstantToTosaConstPass ()
std::unique_ptr<::mlir::Pass > createTosaAttachTarget ()
std::unique_ptr<::mlir::Pass > createTosaAttachTarget (TosaAttachTargetOptions options)
std::unique_ptr<::mlir::Pass > createTosaConvertIntegerTypeToSignless ()
std::unique_ptr<::mlir::Pass > createTosaDowngrade1p1To1p0Pass ()
std::unique_ptr<::mlir::Pass > createTosaInferShapesPass ()
std::unique_ptr<::mlir::Pass > createTosaInferShapesPass (TosaInferShapesPassOptions options)
std::unique_ptr<::mlir::Pass > createTosaLayerwiseConstantFoldPass ()
std::unique_ptr<::mlir::Pass > createTosaLayerwiseConstantFoldPass (TosaLayerwiseConstantFoldPassOptions options)
std::unique_ptr<::mlir::Pass > createTosaMakeBroadcastablePass ()
std::unique_ptr<::mlir::Pass > createTosaNarrowF64ToF32Pass ()
std::unique_ptr<::mlir::Pass > createTosaNarrowF64ToF32Pass (TosaNarrowF64ToF32PassOptions options)
std::unique_ptr<::mlir::Pass > createTosaNarrowI64ToI32Pass ()
std::unique_ptr<::mlir::Pass > createTosaNarrowI64ToI32Pass (TosaNarrowI64ToI32PassOptions options)
std::unique_ptr<::mlir::Pass > createTosaOptionalDecompositionsPass ()
std::unique_ptr<::mlir::Pass > createTosaReduceTransposes ()
std::unique_ptr<::mlir::Pass > createTosaValidation ()
std::unique_ptr<::mlir::Pass > createTosaValidation (TosaValidationOptions options)
void populateTosaDecomposeTransposeConv (MLIRContext *ctx, RewritePatternSet &patterns)
void populateTosaDecomposeDepthwise (MLIRContext *ctx, RewritePatternSet &patterns)
void populateTosaFoldConstantReciprocalPatterns (MLIRContext *ctx, RewritePatternSet &patterns)
void populateTosaFoldConstantTransposePatterns (MLIRContext *ctx, RewritePatternSet &patterns)
void populateTosaConstantReduction (MLIRContext *ctx, RewritePatternSet &patterns, bool aggressiveReduceConstant)
void populateTosaTypeConversion (TypeConverter &converter)
std::unique_ptr< Pass > createTosaTestQuantUtilAPIPass ()
std::unique_ptr< Pass > createTosaInputShapePass (std::vector< std::string > args={})
void registerTosaArithConstantToTosaConstPass ()
void registerTosaArithConstantToTosaConstPassPass ()
void registerTosaAttachTarget ()
void registerTosaAttachTargetPass ()
void registerTosaConvertIntegerTypeToSignless ()
void registerTosaConvertIntegerTypeToSignlessPass ()
void registerTosaDowngrade1p1To1p0Pass ()
void registerTosaDowngrade1p1To1p0PassPass ()
void registerTosaInferShapesPass ()
void registerTosaInferShapesPassPass ()
void registerTosaInputShape ()
void registerTosaInputShapePass ()
void registerTosaLayerwiseConstantFoldPass ()
void registerTosaLayerwiseConstantFoldPassPass ()
void registerTosaMakeBroadcastablePass ()
void registerTosaMakeBroadcastablePassPass ()
void registerTosaNarrowF64ToF32Pass ()
void registerTosaNarrowF64ToF32PassPass ()
void registerTosaNarrowI64ToI32Pass ()
void registerTosaNarrowI64ToI32PassPass ()
void registerTosaOptionalDecompositionsPass ()
void registerTosaOptionalDecompositionsPassPass ()
void registerTosaReduceTransposes ()
void registerTosaReduceTransposesPass ()
void registerTosaValidation ()
void registerTosaValidationPass ()
void registerTosaPasses ()
SmallVector< utils::IteratorType > getNParallelLoopsAttrs (unsigned nParallelLoops)
SmallVector< Value > condenseValues (const SmallVector< Value > &values)
Value clampFloatHelper (Location loc, Value arg, Value min, Value max, OpBuilder &rewriter)
Value clampIntHelper (Location loc, Value arg, Value min, Value max, OpBuilder &rewriter, bool isUnsigned)
bool validIntegerRange (IntegerType ty, int64_t value)
template<typename Op>
std::optional< SmallVector< Value > > checkHasDynamicBatchDims (PatternRewriter &rewriter, Op op, ArrayRef< Value > params)
LogicalResult EqualizeRanks (PatternRewriter &rewriter, Location loc, Value &input1, Value &input2)
Common code to create the reshape op where necessary to make the rank of two values equal.
LogicalResult EqualizeRanks (ImplicitLocOpBuilder &builder, Value &input1, Value &input2)
template<typename TosaOp, typename... Args>
TosaOp CreateOpAndInferShape (ImplicitLocOpBuilder &builder, Type resultTy, Args &&...args)
template<typename TosaOp, typename... Args>
TosaOp CreateOpAndInferShape (PatternRewriter &rewriter, Location loc, Type resultTy, Args &&...args)
template<typename T>
SmallVector< T > applyTOSAPermutation (ArrayRef< T > input, ArrayRef< int32_t > perms)
Value getTosaConstShape (ImplicitLocOpBuilder &builder, llvm::ArrayRef< int64_t > shape)
Value getTosaConstShape (PatternRewriter &rewriter, Location loc, llvm::ArrayRef< int64_t > shape)
SmallVector< int64_t > convertFromMlirShape (ArrayRef< int64_t > shape)
bool getConstShapeValues (Operation *op, llvm::SmallVector< int64_t > &result_shape)
SmallVector< int64_t > convertFromIntAttr (const DenseElementsAttr &attr, const int rank)
bool hasUniqueConstantScatterIndices (ShapedType indicesType, DenseIntElementsAttr indicesAttr)
template<typename T>
std::optional< ArrayRef< T > > tryGetDenseResourceValues (ElementsAttr attr)
template<typename T>
FailureOr< T > getConstantScalarIntValue (Value val)
bool computeMultiplierAndShift (double scale, int32_t &multiplier, int32_t &shift, int32_t scaleWidth)
From a scale value, computes multiplier and shift values for 16 or 32-bit scale widths.
template<typename IntType>
Value getConstTensorInt (OpBuilder &builder, Location loc, ArrayRef< IntType > vec)
ConvOpQuantizationAttr buildConvOpQuantizationAttr (OpBuilder &builder, Value input, Value weight)
Method to build ConvOpQuantizationAttr, called from ConvOpQuantInfoBuilder/TransConvOpQuantInfoBuilder: input_zp: input zeropoint weight_zp: weight zeropoint.
std::pair< Value, Value > createZPsAsConst (OpBuilder &builder, Value input, Value weight)
MatMulOpQuantizationAttr buildMatMulOpQuantizationAttr (OpBuilder &builder, Value a, Value b)
Builds MatMulOpQuantizationAttr, called from MatMulOpQuantInfoBuilder: aZp: input a zeropoint bZp: input b zeropoint.
UnaryOpQuantizationAttr buildUnaryOpQuantizationAttr (OpBuilder &builder, Value input, Type outputRawType)
Builds UnaryOpQuantizationAttr UnaryOpQuantInfoBuilder: inputZp: input zeropoint outputZp: output zeropoint.
PadOpQuantizationAttr buildPadOpQuantizationAttr (OpBuilder &builder, Value input)
Builds PadOpQuantizationAttr, called from PadOpQuantInfoBuilder: inputZp: input zeropoint.
Type buildConvOpResultTypeInfo (OpBuilder &builder, Type outputType, Value input, Value weight)
construct ConvOp output type with correct bitwidth based on input/weight width.
Type buildQTypeFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
TypeAttr buildQTypeAttrFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
Type getStorageElementTypeFromQuantized (quant::QuantizedType quantizedType)
SmallVector< Profile, 2 > getCooperativeProfiles (Extension ext)
Variables
constexpr llvm::StringLiteral graphARMInterfaceVarABIAttrName
constexpr llvm::StringLiteral graphARMGraphConstantIdAttrName
static constexpr TosaLevel TOSA_LEVEL_EIGHTK
static constexpr TosaLevel TOSA_LEVEL_NONE
constexpr int64_t kInferableDimSize = -1
Represents a dimension in the shape of a tensor that can be inferred based on the other provided dimensions.
Function Documentation
addTosaToLinalgPasses()
void mlir::tosa::addTosaToLinalgPasses (OpPassManager & pm, const TosaToLinalgOptions & options, const TosaToLinalgNamedOptions & tosaToLinalgNamedOptions = TosaToLinalgNamedOptions(), std::optional< tosa::TosaValidationOptions > validationOptions = tosa::TosaValidationOptions{false, false}, std::optional< TosaAttachTargetOptions > attachTargetOptions = std::nullopt)
Populates passes to convert from TOSA to Linalg.
At the end of the pass, the function will only contain linalg ops or standard ops if the pipeline succeeds. The option to disable decompositions is available for benchmarking performance improvements from the canonicalizations.
Definition at line 82 of file TosaToLinalgPass.cpp.
References mlir::OpPassManager::addNestedPass(), mlir::OpPassManager::addPass(), mlir::createCanonicalizerPass(), createTosaAttachTarget(), createTosaInferShapesPass(), createTosaLayerwiseConstantFoldPass(), createTosaMakeBroadcastablePass(), createTosaOptionalDecompositionsPass(), createTosaToLinalg(), createTosaToLinalgNamed(), createTosaValidation(), and options.
Referenced by registerTosaToLinalgPipelines().
addTosaToSCFPasses()
void mlir::tosa::addTosaToSCFPasses (OpPassManager & pm)
Populates passes to convert from TOSA to SCF.
Definition at line 49 of file TosaToSCFPass.cpp.
References mlir::OpPassManager::addNestedPass(), and mlir::createTosaToSCFPass().
applyTOSAPermutation()
template<typename T> SmallVector< T > mlir::tosa::applyTOSAPermutation (ArrayRef< T > input, ArrayRef< int32_t > perms)
Definition at line 223 of file ConversionUtils.h.
buildConvOpQuantizationAttr()
ConvOpQuantizationAttr mlir::tosa::buildConvOpQuantizationAttr (OpBuilder & builder, Value input, Value weight)
Method to build ConvOpQuantizationAttr, called from ConvOpQuantInfoBuilder/TransConvOpQuantInfoBuilder: input_zp: input zeropoint weight_zp: weight zeropoint.
Definition at line 198 of file QuantUtils.cpp.
References mlir::Builder::getAttr(), and getConvZeroPoints().
Referenced by buildConvOpWithQuantInfo(), and buildTransConvOpWithQuantInfo().
buildConvOpResultTypeInfo()
Type mlir::tosa::buildConvOpResultTypeInfo (OpBuilder & builder, Type outputType, Value input, Value weight)
construct ConvOp output type with correct bitwidth based on input/weight width.
Builds output type for a quantized ConvOp with the right bitwidth.
This is called by the builder when dealing with quantized content.
Definition at line 289 of file QuantUtils.cpp.
References GET_QTYPE, mlir::Builder::getI32Type(), mlir::Builder::getIntegerType(), and mlir::Value::getType().
Referenced by buildConvOpWithQuantInfo(), and buildTransConvOpWithQuantInfo().
buildMatMulOpQuantizationAttr()
MatMulOpQuantizationAttr mlir::tosa::buildMatMulOpQuantizationAttr (OpBuilder & builder, Value a, Value b)
Builds MatMulOpQuantizationAttr, called from MatMulOpQuantInfoBuilder: aZp: input a zeropoint bZp: input b zeropoint.
Definition at line 214 of file QuantUtils.cpp.
References b, GET_UQTYPE, mlir::Builder::getAttr(), and mlir::Value::getType().
Referenced by buildMatMulLikeOpWithQuantInfo().
buildPadOpQuantizationAttr()
PadOpQuantizationAttr mlir::tosa::buildPadOpQuantizationAttr (OpBuilder & builder, Value input)
Builds PadOpQuantizationAttr, called from PadOpQuantInfoBuilder: inputZp: input zeropoint.
Definition at line 269 of file QuantUtils.cpp.
References GET_UQTYPE, mlir::Builder::getAttr(), and mlir::Value::getType().
Referenced by buildPadOpWithQuantInfo().
buildQTypeAttrFromMinMax()
TypeAttr mlir::tosa::buildQTypeAttrFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
Definition at line 389 of file QuantUtils.cpp.
References buildQTypeFromMinMax().
buildQTypeFromMinMax()
Type mlir::tosa::buildQTypeFromMinMax (OpBuilder builder, Type inputDType, Attribute minAttr, Attribute maxAttr, IntegerAttr quantBits, int filterQuantDim, bool isSigned, BoolAttr narrowRange)
Builds Tosa quantization attributes from min/max values.
Definition at line 321 of file QuantUtils.cpp.
References mlir::quant::fakeQuantAttrsToType(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), mlir::Builder::getUnknownLoc(), mlir::BoolAttr::getValue(), max(), and min().
Referenced by buildQTypeAttrFromMinMax().
buildUnaryOpQuantizationAttr()
UnaryOpQuantizationAttr mlir::tosa::buildUnaryOpQuantizationAttr (OpBuilder & builder, Value input, Type outputRawType)
Builds UnaryOpQuantizationAttr UnaryOpQuantInfoBuilder: inputZp: input zeropoint outputZp: output zeropoint.
Definition at line 243 of file QuantUtils.cpp.
References GET_UQTYPE, mlir::Builder::getAttr(), and mlir::Value::getType().
Referenced by buildAvgPool2dAdaptiveOpWithQuantInfo(), buildAvgPool2dOpWithQuantInfo(), and buildNegateOpWithQuantInfo().
checkHasDynamicBatchDims()
template<typename Op> std::optional< SmallVector< Value > > mlir::tosa::checkHasDynamicBatchDims (PatternRewriter & rewriter, Op op, ArrayRef< Value > params)
Definition at line 52 of file ConversionUtils.h.
References mlir::OpState::getLoc(), and mlir::RewriterBase::notifyMatchFailure().
clampFloatHelper()
Value mlir::tosa::clampFloatHelper (Location loc, Value arg, Value min, Value max, OpBuilder & rewriter)
Definition at line 35 of file ConversionUtils.cpp.
References max(), and min().
Referenced by createLinalgBodyCalculationForElementwiseOp().
clampIntHelper()
Value mlir::tosa::clampIntHelper (Location loc, Value arg, Value min, Value max, OpBuilder & rewriter, bool isUnsigned)
Definition at line 41 of file ConversionUtils.cpp.
References max(), and min().
Referenced by createLinalgBodyCalculationForElementwiseOp().
computeMultiplierAndShift()
bool mlir::tosa::computeMultiplierAndShift (double scale, int32_t & multiplier, int32_t & shift, int32_t scaleWidth)
From a scale value, computes multiplier and shift values for 16 or 32-bit scale widths.
Generates a quantized multiplier/shift from double.
Definition at line 95 of file QuantUtils.cpp.
References computeMultiplierAndShiftTosaScale16(), and computeMultiplierAndShiftTosaScale32().
condenseValues()
SmallVector< Value > mlir::tosa::condenseValues (const SmallVector< Value > & values)
Definition at line 27 of file ConversionUtils.cpp.
Referenced by inferDynamicDimsForConv().
constructTargetEnvAttrWithCapExtDefaults()
spirv::TargetEnvAttr mlir::tosa::constructTargetEnvAttrWithCapExtDefaults (MLIRContext * context, spirv::ResourceLimitsAttr limits = {}, spirv::ClientAPI clientAPI = spirv::ClientAPI::Unknown, spirv::Vendor vendorID = spirv::Vendor::Unknown, spirv::DeviceType deviceType = spirv::DeviceType::Unknown, uint32_t deviceID = spirv::TargetEnvAttr::kUnknownDeviceID)
Definition at line 95 of file TosaToSPIRVTosaPass.cpp.
References mlir::spirv::TargetEnvAttr::get(), mlir::spirv::getDefaultResourceLimits(), and getDefaultVerCapExtAttr().
convertFromIntAttr()
SmallVector< int64_t > mlir::tosa::convertFromIntAttr (const DenseElementsAttr & attr, const int rank)
Definition at line 208 of file ConversionUtils.cpp.
References mlir::DenseElementsAttr::getSplatValue(), and mlir::DenseElementsAttr::isSplat().
convertFromMlirShape()
SmallVector< int64_t > mlir::tosa::convertFromMlirShape (ArrayRef< int64_t > shape)
Definition at line 183 of file ConversionUtils.cpp.
Referenced by buildVariableOp(), and getTosaConstShape().
CreateOpAndInferShape() [1/2]
template<typename TosaOp, typename... Args> TosaOp mlir::tosa::CreateOpAndInferShape (ImplicitLocOpBuilder & builder, Type resultTy, Args &&... args)
Definition at line 147 of file ConversionUtils.h.
References EqualizeRanks().
Referenced by CreateOpAndInferShape().
CreateOpAndInferShape() [2/2]
template<typename TosaOp, typename... Args> TosaOp mlir::tosa::CreateOpAndInferShape (PatternRewriter & rewriter, Location loc, Type resultTy, Args &&... args)
Definition at line 214 of file ConversionUtils.h.
References CreateOpAndInferShape().
createPadConstTensor()
Value mlir::tosa::createPadConstTensor (OpBuilder & builder, Location loc, Value src, int32_t val = 0)
Definition at line 615 of file TosaOps.cpp.
References mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), mlir::Builder::getFloatAttr(), mlir::Builder::getIntegerAttr(), and getStorageElementTypeOrSelf().
Referenced by buildPadOpWithQuantInfo().
createTosaArithConstantToTosaConstPass()
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaArithConstantToTosaConstPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 91 of file TosaArithConstantToConst.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsGreedily(), getContext(), and mlir::DialectRegistry::insert().
createTosaAttachTarget() [1/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaAttachTarget ()
Definition at line 202 of file TosaAttachTarget.cpp.
Referenced by addTosaToLinalgPasses().
createTosaAttachTarget() [2/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaAttachTarget (TosaAttachTargetOptions options)
Definition at line 206 of file TosaAttachTarget.cpp.
createTosaConvertIntegerTypeToSignless()
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaConvertIntegerTypeToSignless ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 281 of file TosaConvertIntegerTypeToSignless.cpp.
createTosaDowngrade1p1To1p0Pass()
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaDowngrade1p1To1p0Pass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 356 of file TosaDowngrade1p1To1p0.cpp.
createTosaInferShapesPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaInferShapesPass ()
Definition at line 452 of file TosaInferShapes.cpp.
Referenced by addTosaToLinalgPasses().
createTosaInferShapesPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaInferShapesPass (TosaInferShapesPassOptions options)
Definition at line 456 of file TosaInferShapes.cpp.
createTosaInputShapePass()
std::unique_ptr< Pass > mlir::tosa::createTosaInputShapePass (std::vector< std::string > args = {})
Definition at line 183 of file TosaInputShape.cpp.
createTosaLayerwiseConstantFoldPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaLayerwiseConstantFoldPass ()
Definition at line 616 of file TosaLayerwiseConstantFoldPass.cpp.
Referenced by addTosaToLinalgPasses().
createTosaLayerwiseConstantFoldPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaLayerwiseConstantFoldPass (TosaLayerwiseConstantFoldPassOptions options)
Definition at line 620 of file TosaLayerwiseConstantFoldPass.cpp.
createTosaMakeBroadcastablePass()
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaMakeBroadcastablePass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 695 of file TosaMakeBroadcastable.cpp.
Referenced by addTosaToLinalgPasses().
createTosaNarrowF64ToF32Pass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaNarrowF64ToF32Pass ()
Definition at line 790 of file TosaNarrowTypes.cpp.
createTosaNarrowF64ToF32Pass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaNarrowF64ToF32Pass (TosaNarrowF64ToF32PassOptions options)
Definition at line 794 of file TosaNarrowTypes.cpp.
createTosaNarrowI64ToI32Pass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaNarrowI64ToI32Pass ()
Definition at line 889 of file TosaNarrowTypes.cpp.
createTosaNarrowI64ToI32Pass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaNarrowI64ToI32Pass (TosaNarrowI64ToI32PassOptions options)
Definition at line 893 of file TosaNarrowTypes.cpp.
createTosaOptionalDecompositionsPass()
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaOptionalDecompositionsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 968 of file TosaOptionalDecompositions.cpp.
Referenced by addTosaToLinalgPasses().
createTosaReduceTransposes()
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaReduceTransposes ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1043 of file TosaReduceTransposes.cpp.
createTosaTestQuantUtilAPIPass()
std::unique_ptr< Pass > mlir::tosa::createTosaTestQuantUtilAPIPass ()
createTosaToLinalg()
std::unique_ptr< Pass > mlir::tosa::createTosaToLinalg ()
Definition at line 78 of file TosaToLinalgPass.cpp.
Referenced by addTosaToLinalgPasses().
createTosaToLinalgNamed()
std::unique_ptr< Pass > mlir::tosa::createTosaToLinalgNamed (const TosaToLinalgNamedOptions & options = TosaToLinalgNamedOptions())
Definition at line 79 of file TosaToLinalgNamedPass.cpp.
References options.
Referenced by addTosaToLinalgPasses().
createTosaToSPIRVTosa()
std::unique_ptr< Pass > mlir::tosa::createTosaToSPIRVTosa ()
Definition at line 279 of file TosaToSPIRVTosaPass.cpp.
createTosaToSPIRVTosaMarkGraphConstants()
std::unique_ptr< Pass > mlir::tosa::createTosaToSPIRVTosaMarkGraphConstants ()
Definition at line 87 of file TosaToSPIRVTosaConstants.cpp.
createTosaValidation() [1/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaValidation ()
Definition at line 1137 of file TosaValidation.cpp.
Referenced by addTosaToLinalgPasses().
createTosaValidation() [2/2]
std::unique_ptr<::mlir::Pass > mlir::tosa::createTosaValidation (TosaValidationOptions options)
Definition at line 1141 of file TosaValidation.cpp.
createZeroPointTensor()
std::optional< Value > mlir::tosa::createZeroPointTensor (OpBuilder & builder, Location loc, Type srcElemType, int64_t zp = 0)
Definition at line 5761 of file TosaOps.cpp.
References mlir::DenseElementsAttr::get(), mlir::Builder::getFloatAttr(), mlir::Builder::getIntegerAttr(), and getStorageElementTypeOrSelf().
Referenced by buildAvgPool2dAdaptiveOpWithQuantInfo(), buildAvgPool2dOpWithQuantInfo(), buildNegateOpWithQuantInfo(), and createZPsAsConst().
createZPsAsConst()
std::pair< Value, Value > mlir::tosa::createZPsAsConst (OpBuilder & builder, Value input, Value weight)
Definition at line 162 of file QuantUtils.cpp.
References createZeroPointTensor(), getConvZeroPoints(), mlir::getElementTypeOrSelf(), mlir::Value::getLoc(), and mlir::Value::getType().
Referenced by buildConvOpWithQuantInfo(), buildMatMulLikeOpWithQuantInfo(), and buildTransConvOpWithQuantInfo().
EqualizeRanks() [1/2]
LogicalResult mlir::tosa::EqualizeRanks (ImplicitLocOpBuilder & builder, Value & input1, Value & input2)
Definition at line 114 of file ConversionUtils.cpp.
References getTosaConstShape(), mlir::Value::getType(), and success().
EqualizeRanks() [2/2]
LogicalResult mlir::tosa::EqualizeRanks (PatternRewriter & rewriter, Location loc, Value & input1, Value & input2)
Common code to create the reshape op where necessary to make the rank of two values equal.
input1 and input2 will be updated when the rank has changed. The caller is expected to use these to rewrite the original operator with the RESHAPE now in the graph.
Definition at line 108 of file ConversionUtils.cpp.
References EqualizeRanks().
Referenced by CreateOpAndInferShape(), and EqualizeRanks().
getBitWidth()
unsigned mlir::tosa::getBitWidth (Type type)
Definition at line 630 of file TosaOps.cpp.
References mlir::Type::getIntOrFloatBitWidth().
getConstantScalarIntValue()
template<typename T> template FailureOr< int32_t > mlir::tosa::getConstantScalarIntValue< int32_t > (Value val)
Definition at line 253 of file ConversionUtils.cpp.
References mlir::m_Constant(), and mlir::matchPattern().
Referenced by RowGatherToGather::matchAndRewrite().
getConstShapeValues()
bool mlir::tosa::getConstShapeValues (Operation * op, llvm::SmallVector< int64_t > & result_shape)
Definition at line 188 of file ConversionUtils.cpp.
References mlir::DenseElementsAttr::getValues(), and mlir::DenseElementsAttr::size().
Referenced by extractAdaptivePoolingConstShapeOperands(), ConvInferShapeAdaptor< Conv2DBlockScaledOp::Adaptor >::getSpatialParameters(), AvgPool2dAdaptiveToAvgPool2d::matchAndRewrite(), MaxPool2dAdaptiveToMaxPool2d::matchAndRewrite(), mlir::tosa::impl::TosaValidationBase< DerivedT >::operator=(), and mlir::tosa::impl::TosaValidationBase< DerivedT >::~TosaValidationBase().
getConstTensorInt()
template<typename IntType> Value mlir::tosa::getConstTensorInt (OpBuilder & builder, Location loc, ArrayRef< IntType > vec)
Definition at line 36 of file QuantUtils.h.
References mlir::DenseElementsAttr::get(), and mlir::Builder::getIntegerType().
getCooperativeProfiles()
SmallVector< Profile, 2 > mlir::tosa::getCooperativeProfiles (Extension ext)
Definition at line 66 of file TargetEnv.cpp.
Referenced by mlir::tosa::TargetEnv::verifyTargetInformation().
getDefaultTargetEnv()
TargetEnvAttr mlir::tosa::getDefaultTargetEnv (MLIRContext * context)
Definition at line 180 of file TargetEnv.cpp.
Referenced by lookupTargetEnvOrDefault().
getDefaultVerCapExtAttr()
spirv::VerCapExtAttr mlir::tosa::getDefaultVerCapExtAttr (MLIRContext * context)
Definition at line 67 of file TosaToSPIRVTosaPass.cpp.
References mlir::spirv::VerCapExtAttr::get().
Referenced by constructTargetEnvAttrWithCapExtDefaults().
getMinVersion() [1/3]
TosaSpecificationVersion mlir::tosa::getMinVersion (const Extension & extension)
Definition at line 41 of file TargetEnv.cpp.
getMinVersion() [2/3]
TosaSpecificationVersion mlir::tosa::getMinVersion (const Level & level)
Definition at line 92 of file TargetEnv.cpp.
getMinVersion() [3/3]
TosaSpecificationVersion mlir::tosa::getMinVersion (const Profile & profile)
Definition at line 30 of file TargetEnv.cpp.
Referenced by mlir::tosa::TargetEnv::verifyTargetInformation().
getNParallelLoopsAttrs()
SmallVector< utils::IteratorType > mlir::tosa::getNParallelLoopsAttrs (unsigned nParallelLoops)
Definition at line 21 of file ConversionUtils.cpp.
Referenced by broadcastDynamicDimension(), emitElementwiseComputation(), linalgBroadcastAndMaybeExt(), linalgIntBroadcastExtSIAdd(), and reduceMatchAndRewriteHelper().
getStorageElementTypeFromQuantized()
Type mlir::tosa::getStorageElementTypeFromQuantized (quant::QuantizedType quantizedType)
Definition at line 399 of file QuantUtils.cpp.
References mlir::quant::QuantizedType::getStorageType(), and mlir::quant::QuantizedType::isSigned().
Referenced by getStorageElementTypeOrSelf(), ClampClampOptimization::matchAndRewrite(), verifyConvOp(), and verifyConvOpModes().
getStorageElementTypeOrSelf() [1/2]
Type mlir::tosa::getStorageElementTypeOrSelf (Type type)
Definition at line 584 of file TosaOps.cpp.
References mlir::getElementTypeOrSelf(), and getStorageElementTypeFromQuantized().
Referenced by buildMatMulLikeOpWithQuantInfo(), createPadConstTensor(), createZeroPointTensor(), getStorageElementTypeOrSelf(), verifyAvgPoolCommonTypeAndZpChecks(), verifyConvOp(), verifyMatMulZeroPointType(), and verifyRescaleValueAndZpTypes().
getStorageElementTypeOrSelf() [2/2]
Type mlir::tosa::getStorageElementTypeOrSelf (Value value)
Definition at line 591 of file TosaOps.cpp.
References getStorageElementTypeOrSelf(), and mlir::Value::getType().
getTosaConstShape() [1/2]
Value mlir::tosa::getTosaConstShape (ImplicitLocOpBuilder & builder, llvm::ArrayRef< int64_t > shape)
Definition at line 169 of file ConversionUtils.cpp.
References convertFromMlirShape(), mlir::Builder::getContext(), mlir::Builder::getIndexTensorAttr(), and mlir::Operation::getResult().
Referenced by buildAvgPool2dAdaptiveOpWithQuantInfo(), EqualizeRanks(), getTosaConstShape(), ConcatSliceOptimization::matchAndRewrite(), PadSliceOptimization::matchAndRewrite(), SliceDynamicSizeCanonicalization::matchAndRewrite(), and TransposeIsReshape::matchAndRewrite().
getTosaConstShape() [2/2]
Value mlir::tosa::getTosaConstShape (PatternRewriter & rewriter, Location loc, llvm::ArrayRef< int64_t > shape)
Definition at line 177 of file ConversionUtils.cpp.
References getTosaConstShape().
getTosaLevelFromEnum()
TosaLevel mlir::tosa::getTosaLevelFromEnum (const Level level)
Definition at line 15 of file TargetEnv.cpp.
References TOSA_LEVEL_EIGHTK, and TOSA_LEVEL_NONE.
Referenced by ConsecutiveConcatOptimization::matchAndRewrite().
getVariableType()
RankedTensorType mlir::tosa::getVariableType (VariableOp variableOp)
Referenced by verifyVariableOpErrorIf().
hasUniqueConstantScatterIndices()
bool mlir::tosa::hasUniqueConstantScatterIndices (ShapedType indicesType, DenseIntElementsAttr indicesAttr)
Definition at line 224 of file ConversionUtils.cpp.
References b, and indices.
isa_tosa_shape_type()
bool mlir::tosa::isa_tosa_shape_type (mlir::Type t)
Definition at line 5785 of file TosaOps.cpp.
lookupTargetEnv()
TargetEnvAttr mlir::tosa::lookupTargetEnv (Operation * op)
Definition at line 165 of file TargetEnv.cpp.
References mlir::Operation::getAttrOfType(), mlir::SymbolTable::getNearestSymbolTable(), and mlir::Operation::getParentOp().
Referenced by lookupTargetEnvOrDefault(), and ConsecutiveConcatOptimization::matchAndRewrite().
lookupTargetEnvOrDefault()
TargetEnvAttr mlir::tosa::lookupTargetEnvOrDefault (Operation * op)
Queries the target environment recursively from enclosing symbol table ops containing the given op or returns the default target environment as returned by getDefaultTargetEnv() if not provided.
Definition at line 185 of file TargetEnv.cpp.
References mlir::Operation::getContext(), getDefaultTargetEnv(), and lookupTargetEnv().
parseVariableOpTypeOrInitialValue()
ParseResult mlir::tosa::parseVariableOpTypeOrInitialValue (OpAsmParser & parser, DenseElementsAttr & varShapeAttr, TypeAttr & typeAttr, Attribute & initialValueAttr)
Definition at line 228 of file TosaOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), and mlir::AsmParser::parseOptionalEqual().
populateTosaConstantReduction()
void mlir::tosa::populateTosaConstantReduction (MLIRContext * ctx, RewritePatternSet & patterns, bool aggressiveReduceConstant)
Definition at line 433 of file TosaFolders.cpp.
References mlir::RewritePatternSet::add().
populateTosaDecomposeDepthwise()
void mlir::tosa::populateTosaDecomposeDepthwise (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 198 of file TosaDecomposeDepthwise.cpp.
References mlir::RewritePatternSet::add().
populateTosaDecomposeTransposeConv()
void mlir::tosa::populateTosaDecomposeTransposeConv (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 345 of file TosaDecomposeTransposeConv.cpp.
References mlir::RewritePatternSet::add().
populateTosaFoldConstantReciprocalPatterns()
void mlir::tosa::populateTosaFoldConstantReciprocalPatterns (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 455 of file TosaFolders.cpp.
References mlir::RewritePatternSet::add().
populateTosaFoldConstantTransposePatterns()
void mlir::tosa::populateTosaFoldConstantTransposePatterns (MLIRContext * ctx, RewritePatternSet & patterns)
Definition at line 450 of file TosaFolders.cpp.
References mlir::RewritePatternSet::add().
populateTosaRescaleToArithConversionPatterns()
void mlir::tosa::populateTosaRescaleToArithConversionPatterns (RewritePatternSet * patterns, bool include32Bit = false)
Definition at line 258 of file TosaToArith.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToArithConversionPatterns()
void mlir::tosa::populateTosaToArithConversionPatterns (RewritePatternSet * patterns)
Definition at line 253 of file TosaToArith.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToLinalgConversionPatterns()
void mlir::tosa::populateTosaToLinalgConversionPatterns (const TypeConverter & converter, RewritePatternSet * patterns)
Populates conversion passes from TOSA dialect to Linalg dialect.
Definition at line 3031 of file TosaToLinalg.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToLinalgNamedConversionPatterns()
void mlir::tosa::populateTosaToLinalgNamedConversionPatterns (const TypeConverter & converter, RewritePatternSet * patterns, const TosaToLinalgNamedOptions & options)
Populates conversion passes from TOSA dialect to Linalg named operations.
Definition at line 1118 of file TosaToLinalgNamed.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
populateTosaToMLProgramConversionPatterns()
void mlir::tosa::populateTosaToMLProgramConversionPatterns (RewritePatternSet * patterns)
Definition at line 72 of file TosaToMLProgram.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToSCFConversionPatterns()
void mlir::tosa::populateTosaToSCFConversionPatterns (RewritePatternSet * patterns)
Definition at line 181 of file TosaToSCF.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToSPIRVTosaConversionPatterns()
void mlir::tosa::populateTosaToSPIRVTosaConversionPatterns (SPIRVTypeConverter & typeConverter, RewritePatternSet & patterns, spirv::TargetEnvAttr targetAttr)
Definition at line 173 of file TosaToSPIRVTosa.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToSPIRVTosaCustomConversionPatterns()
void mlir::tosa::populateTosaToSPIRVTosaCustomConversionPatterns (SPIRVTypeConverter & typeConverter, RewritePatternSet & patterns, llvm::StringMap< int32_t > domainToOpcode)
Definition at line 100 of file TosaToSPIRVTosaCustom.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToSPIRVTosaOpsConversionPatterns()
void mlir::tosa::populateTosaToSPIRVTosaOpsConversionPatterns (SPIRVTypeConverter & typeConverter, RewritePatternSet & patterns)
Definition at line 483 of file TosaToSPIRVTosaOps.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaToTensorConversionPatterns()
void mlir::tosa::populateTosaToTensorConversionPatterns (const TypeConverter & converter, RewritePatternSet * patterns)
Definition at line 459 of file TosaToTensor.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTosaTypeConversion()
void mlir::tosa::populateTosaTypeConversion (TypeConverter & converter)
Definition at line 20 of file TosaTypeConverters.cpp.
References mlir::Type::getContext(), mlir::Type::getIntOrFloatBitWidth(), and mlir::Type::isUnsignedInteger().
printVariableOpTypeOrInitialValue()
void mlir::tosa::printVariableOpTypeOrInitialValue (OpAsmPrinter & p, Operation * op, DenseElementsAttr varShapeAttr, TypeAttr typeAttr, Attribute initialValueAttr)
Definition at line 253 of file TosaOps.cpp.
References convertToMlirShape(), mlir::DenseElementsAttr::getValues(), and mlir::AsmPrinter::printAttribute().
registerShardingInterfaceExternalModels()
void mlir::tosa::registerShardingInterfaceExternalModels (DialectRegistry & registry)
Definition at line 116 of file ShardingInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects().
registerTosaArithConstantToTosaConstPass()
void mlir::tosa::registerTosaArithConstantToTosaConstPass () inline
Definition at line 1168 of file Passes.h.
registerTosaArithConstantToTosaConstPassPass()
void mlir::tosa::registerTosaArithConstantToTosaConstPassPass () inline
Definition at line 1175 of file Passes.h.
registerTosaAttachTarget()
void mlir::tosa::registerTosaAttachTarget () inline
Definition at line 1189 of file Passes.h.
registerTosaAttachTargetPass()
void mlir::tosa::registerTosaAttachTargetPass () inline
Definition at line 1196 of file Passes.h.
registerTosaConvertIntegerTypeToSignless()
void mlir::tosa::registerTosaConvertIntegerTypeToSignless () inline
Definition at line 1210 of file Passes.h.
registerTosaConvertIntegerTypeToSignlessPass()
void mlir::tosa::registerTosaConvertIntegerTypeToSignlessPass () inline
Definition at line 1217 of file Passes.h.
registerTosaDowngrade1p1To1p0Pass()
void mlir::tosa::registerTosaDowngrade1p1To1p0Pass () inline
Definition at line 1231 of file Passes.h.
registerTosaDowngrade1p1To1p0PassPass()
void mlir::tosa::registerTosaDowngrade1p1To1p0PassPass () inline
Definition at line 1238 of file Passes.h.
registerTosaInferShapesPass()
void mlir::tosa::registerTosaInferShapesPass () inline
Definition at line 1252 of file Passes.h.
registerTosaInferShapesPassPass()
void mlir::tosa::registerTosaInferShapesPassPass () inline
Definition at line 1259 of file Passes.h.
registerTosaInputShape()
void mlir::tosa::registerTosaInputShape () inline
Definition at line 1273 of file Passes.h.
registerTosaInputShapePass()
void mlir::tosa::registerTosaInputShapePass () inline
Definition at line 1280 of file Passes.h.
registerTosaLayerwiseConstantFoldPass()
void mlir::tosa::registerTosaLayerwiseConstantFoldPass () inline
Definition at line 1294 of file Passes.h.
registerTosaLayerwiseConstantFoldPassPass()
void mlir::tosa::registerTosaLayerwiseConstantFoldPassPass () inline
Definition at line 1301 of file Passes.h.
registerTosaMakeBroadcastablePass()
void mlir::tosa::registerTosaMakeBroadcastablePass () inline
Definition at line 1315 of file Passes.h.
registerTosaMakeBroadcastablePassPass()
void mlir::tosa::registerTosaMakeBroadcastablePassPass () inline
Definition at line 1322 of file Passes.h.
registerTosaNarrowF64ToF32Pass()
void mlir::tosa::registerTosaNarrowF64ToF32Pass () inline
Definition at line 1336 of file Passes.h.
registerTosaNarrowF64ToF32PassPass()
void mlir::tosa::registerTosaNarrowF64ToF32PassPass () inline
Definition at line 1343 of file Passes.h.
registerTosaNarrowI64ToI32Pass()
void mlir::tosa::registerTosaNarrowI64ToI32Pass () inline
Definition at line 1357 of file Passes.h.
registerTosaNarrowI64ToI32PassPass()
void mlir::tosa::registerTosaNarrowI64ToI32PassPass () inline
Definition at line 1364 of file Passes.h.
registerTosaOptionalDecompositionsPass()
void mlir::tosa::registerTosaOptionalDecompositionsPass () inline
Definition at line 1378 of file Passes.h.
registerTosaOptionalDecompositionsPassPass()
void mlir::tosa::registerTosaOptionalDecompositionsPassPass () inline
Definition at line 1385 of file Passes.h.
registerTosaPasses()
void mlir::tosa::registerTosaPasses () inline
Definition at line 1441 of file Passes.h.
Referenced by mlir::registerAllPasses().
registerTosaReduceTransposes()
void mlir::tosa::registerTosaReduceTransposes () inline
Definition at line 1399 of file Passes.h.
registerTosaReduceTransposesPass()
void mlir::tosa::registerTosaReduceTransposesPass () inline
Definition at line 1406 of file Passes.h.
registerTosaToLinalgPipelines()
void mlir::tosa::registerTosaToLinalgPipelines ()
Populates TOSA to linalg pipelines Currently, this includes only the "tosa-to-linalg-pipeline".
Definition at line 136 of file TosaToLinalgPass.cpp.
References addTosaToLinalgPasses().
Referenced by mlir::registerAllPasses().
registerTosaValidation()
void mlir::tosa::registerTosaValidation () inline
Definition at line 1420 of file Passes.h.
registerTosaValidationPass()
void mlir::tosa::registerTosaValidationPass () inline
Definition at line 1427 of file Passes.h.
stringifyVersion()
llvm::SmallString< 4 > mlir::tosa::stringifyVersion (TosaSpecificationVersion version)
Definition at line 25 of file TargetEnv.cpp.
References mlir::tosa::TosaSpecificationVersion::getMajor(), mlir::tosa::TosaSpecificationVersion::getMinor(), and mlir::tosa::TosaSpecificationVersion::isDraft().
Referenced by TosaProfileCompliance::checkProfileOrExtension(), and mlir::tosa::TargetEnv::verifyTargetInformation().
tryGetDenseResourceValues()
template<typename T> std::optional< ArrayRef< T > > mlir::tosa::tryGetDenseResourceValues (ElementsAttr attr)
Definition at line 255 of file ConversionUtils.h.
References mlir::AsmResourceBlob::getData(), and mlir::DenseElementsAttr::isValidRawBuffer().
validIntegerRange()
bool mlir::tosa::validIntegerRange (IntegerType ty, int64_t value)
Definition at line 51 of file ConversionUtils.cpp.
Variable Documentation
graphARMGraphConstantIdAttrName
llvm::StringLiteral mlir::tosa::graphARMGraphConstantIdAttrName constexpr
Initial value:
=
    "grapharm.graph_constant_id"
Definition at line 41 of file TosaToSPIRVTosa.h.
graphARMInterfaceVarABIAttrName
llvm::StringLiteral mlir::tosa::graphARMInterfaceVarABIAttrName constexpr
Initial value:
=
    "grapharm.interface_var_abi"
Definition at line 36 of file TosaToSPIRVTosa.h.
kInferableDimSize
int64_t mlir::tosa::kInferableDimSize = -1 constexpr
Represents a dimension in the shape of a tensor that can be inferred based on the other provided dimensions.
For example, in a reshape operation, -1 can be used to indicate a size that is the remainder of the other dimensions.
Definition at line 106 of file TosaOps.h.
Referenced by PadSliceOptimization::matchAndRewrite(), and SliceDynamicSizeCanonicalization::matchAndRewrite().
TOSA_LEVEL_EIGHTK
TosaLevel mlir::tosa::TOSA_LEVEL_EIGHTK static constexpr
Initial value:
= {6,  8192, 8192, 256,
                                                31, 6,    64,   16}
Definition at line 43 of file TargetEnv.h.
Referenced by getTosaLevelFromEnum().
TOSA_LEVEL_NONE
TosaLevel mlir::tosa::TOSA_LEVEL_NONE static constexpr
Initial value:
= {32, 2147483647, 2147483647, 2048,
                                              63, 256,        256,        64}
Definition at line 45 of file TargetEnv.h.
Referenced by getTosaLevelFromEnum().