MLIR: mlir::remark::detail Namespace Reference
mlir::remark::detail Namespace Reference
Classes
class Remark
class OptRemarkBase
struct LazyTextBuild
Lazy text building for zero cost string formatting.
class InFlightRemark
InFlightRemark is a RAII class that holds a reference to a Remark instance and allows to build the remark using the << operator.
class MLIRRemarkStreamerBase
Base class for MLIR remark streamers that is used to stream optimization remarks to the underlying remark streamer.
class RemarkEngine
class LLVMRemarkStreamer
Concrete streamer that writes LLVM optimization remarks to a file (YAML or Bitstream).
Typedefs
using OptRemarkAnalysis = OptRemarkBase< RemarkKind::RemarkAnalysis, DiagnosticSeverity::Remark >
using OptRemarkPass = OptRemarkBase< RemarkKind::RemarkPassed, DiagnosticSeverity::Remark >
using OptRemarkMissed = OptRemarkBase< RemarkKind::RemarkMissed, DiagnosticSeverity::Remark >
using OptRemarkFailure = OptRemarkBase< RemarkKind::RemarkFailure, DiagnosticSeverity::Remark >
Functions
Remark & operator<< (Remark &r, StringRef s)
Remark && operator<< (Remark &&r, StringRef s)
Remark & operator<< (Remark &r, const Remark::Arg &kv)
template<typename Fn , typename... Args>
InFlightRemark withEngine (Fn fn, Location loc, Args &&...args)
Typedef Documentation
OptRemarkAnalysis
using mlir::remark::detail::OptRemarkAnalysis = typedef OptRemarkBase<RemarkKind::RemarkAnalysis, DiagnosticSeverity::Remark>
Definition at line 252 of file Remarks.h.
OptRemarkFailure
using mlir::remark::detail::OptRemarkFailure = typedef OptRemarkBase<RemarkKind::RemarkFailure, DiagnosticSeverity::Remark>
Definition at line 261 of file Remarks.h.
OptRemarkMissed
using mlir::remark::detail::OptRemarkMissed = typedef OptRemarkBase<RemarkKind::RemarkMissed, DiagnosticSeverity::Remark>
Definition at line 258 of file Remarks.h.
OptRemarkPass
using mlir::remark::detail::OptRemarkPass = typedef OptRemarkBase<RemarkKind::RemarkPassed, DiagnosticSeverity::Remark>
Definition at line 255 of file Remarks.h.
Function Documentation
operator<<() [1/3]
Remark&& mlir::remark::detail::operator<< (Remark && r, StringRef s) inline
Definition at line 232 of file Remarks.h.
References mlir::remark::detail::Remark::insert().
operator<<() [2/3]
Remark& mlir::remark::detail::operator<< (Remark & r, const Remark::Arg & kv) inline
Definition at line 236 of file Remarks.h.
References mlir::remark::detail::Remark::insert().
operator<<() [3/3]
Remark& mlir::remark::detail::operator<< (Remark & r, StringRef s) inline
Definition at line 228 of file Remarks.h.
References mlir::remark::detail::Remark::insert().
withEngine()
template<typename Fn , typename... Args> InFlightRemark mlir::remark::detail::withEngine (Fn fn, Location loc, Args &&... args) inline
Definition at line 434 of file Remarks.h.
References mlir::Attribute::getContext(), and mlir::MLIRContext::getRemarkEngine().
Referenced by mlir::remark::analysis(), mlir::remark::failed(), mlir::remark::missed(), and mlir::remark::passed().