MLIR: mlir::xegpu::uArch Namespace Reference
mlir::xegpu::uArch Namespace Reference
Classes
struct BMGuArch
struct CacheInfo
struct Instruction
struct MMAInstructionInterface
struct PVCuArch
struct RegisterFileInfo
struct SharedMemory
struct Subgroup2DBlockLoadInstruction
struct Subgroup2DBlockPrefetchInstruction
struct Subgroup2DBlockStoreInstruction
struct SubgroupMatrixMultiplyAcc
struct uArch
struct Xe2Plus
struct XeCoreInfo
Enumerations
enum class InstructionScope { Lane , Subgroup , Workgroup , Cluster }
enum class InstructionKind { SubgroupMatrixMultiplyAcc , Subgroup2DBlockStore , Subgroup2DBlockLoad , Subgroup2DBlockPrefetch }
enum class RegisterFileMode : uint8_t { Small , Large }
enum class RegisterFileType : uint8_t { GRF , ARF }
enum class CacheHierarchyLevel { L1 = 1 , L2 = 2 , L3 = 3 }
enum class MMAOpndKind { MatrixA , MatrixB , MatrixC , MatrixD }
Functions
const uArch * getUArch (llvm::StringRef archName)
Variables
constexpr unsigned generalPackedFormatBitSize {32}
Enumeration Type Documentation
CacheHierarchyLevel
enum class mlir::xegpu::uArch::CacheHierarchyLevel strong
Enumerator
L1
L2
L3
Definition at line 117 of file uArchBase.h.
InstructionKind
enum class mlir::xegpu::uArch::InstructionKind strong
Enumerator
SubgroupMatrixMultiplyAcc
Subgroup2DBlockStore
Subgroup2DBlockLoad
Subgroup2DBlockPrefetch
Definition at line 36 of file uArchBase.h.
InstructionScope
enum class mlir::xegpu::uArch::InstructionScope strong
Enumerator
Lane
Subgroup
Workgroup
Cluster
Definition at line 35 of file uArchBase.h.
MMAOpndKind
enum class mlir::xegpu::uArch::MMAOpndKind strong
Enumerator
MatrixA
MatrixB
MatrixC
MatrixD
Definition at line 207 of file uArchBase.h.
RegisterFileMode
enum class mlir::xegpu::uArch::RegisterFileMode : uint8_t strong
Enumerator
Small
Large
Definition at line 86 of file uArchBase.h.
RegisterFileType
enum class mlir::xegpu::uArch::RegisterFileType : uint8_t strong
Enumerator
GRF
ARF
Definition at line 87 of file uArchBase.h.
Function Documentation
getUArch()
const uArch * mlir::xegpu::uArch::getUArch (llvm::StringRef archName) inline
Definition at line 268 of file IntelGpuXe2.h.
References mlir::xegpu::uArch::BMGuArch::getInstance(), and mlir::xegpu::uArch::PVCuArch::getInstance().
Referenced by mlir::xegpu::createXeGPUOptimizeBlockLoads().
Variable Documentation
generalPackedFormatBitSize
unsigned mlir::xegpu::uArch::generalPackedFormatBitSize {32} constexpr
Definition at line 32 of file uArchBase.h.