MLIR: impl Namespace Reference
impl Namespace Reference
Classes
struct StaticSizeMult
struct StaticSizeMult< N, Dims... >
struct VectorDataPrinter
struct MemRefDataPrinter
struct MemRefDataVerifier
Verify the result of two computations are equivalent up to a small numerical error and return the number of errors.
Typedefs
using index_type = uint64_t
using complex64 = std::complex< double >
using complex32 = std::complex< float >
Functions
template<typename T , int M, int... Dims>
std::ostream & operator<< (std::ostream &os, const Vector< T, M, Dims... > &v)
static void printSpace (std::ostream &os, int count)
template<typename T , int N>
void printMemRefShape (StridedMemRefType< T, N > &m)
template<typename T >
void printMemRefShape (UnrankedMemRefType< T > &m)
template<typename T >
void printMemRef (const DynamicMemRefType< T > &m)
template<typename T , int N>
void printMemRef (StridedMemRefType< T, N > &m)
template<typename T >
void printMemRef (UnrankedMemRefType< T > &m)
template<typename T >
int64_t verifyMemRef (const DynamicMemRefType< T > &actual, const DynamicMemRefType< T > &expected)
Verify the equivalence of two dynamic memrefs and return the number of errors or -1 if the shape of the memrefs do not match.
template<typename T >
int64_t verifyMemRef (UnrankedMemRefType< T > &actual, UnrankedMemRefType< T > &expected)
Verify the equivalence of two unranked memrefs and return the number of errors or -1 if the shape of the memrefs do not match.
Typedef Documentation
complex32
using impl::complex32 = typedef std::complex<float>
Definition at line 83 of file RunnerUtils.h.
complex64
using impl::complex64 = typedef std::complex<double>
Definition at line 82 of file RunnerUtils.h.
index_type
using impl::index_type = typedef uint64_t
Definition at line 81 of file RunnerUtils.h.
Function Documentation
operator<<()
template<typename T , int M, int... Dims> std::ostream & impl::operator<< (std::ostream & os, const Vector< T, M, Dims... > & v)
Definition at line 137 of file RunnerUtils.h.
References impl::VectorDataPrinter< T, M, Dims >::print().
printMemRef() [1/3]
template<typename T > void impl::printMemRef (const DynamicMemRefType< T > & m)
Definition at line 218 of file RunnerUtils.h.
References DynamicMemRefType< T >::data, DynamicMemRefType< T >::offset, impl::MemRefDataPrinter< T >::print(), printMemRefMetaData(), DynamicMemRefType< T >::rank, DynamicMemRefType< T >::sizes, and DynamicMemRefType< T >::strides.
Referenced by _mlir_ciface_printMemref0dF32(), _mlir_ciface_printMemref1dC32(), _mlir_ciface_printMemref1dC64(), _mlir_ciface_printMemref1dF32(), _mlir_ciface_printMemref1dF64(), _mlir_ciface_printMemref1dI32(), _mlir_ciface_printMemref1dI64(), _mlir_ciface_printMemref1dI8(), _mlir_ciface_printMemref1dInd(), _mlir_ciface_printMemref2dF32(), _mlir_ciface_printMemref3dF32(), _mlir_ciface_printMemref4dF32(), _mlir_ciface_printMemrefBF16(), _mlir_ciface_printMemrefC32(), _mlir_ciface_printMemrefC64(), _mlir_ciface_printMemrefF16(), _mlir_ciface_printMemrefF32(), _mlir_ciface_printMemrefF64(), _mlir_ciface_printMemrefI16(), _mlir_ciface_printMemrefI32(), _mlir_ciface_printMemrefI64(), _mlir_ciface_printMemrefI8(), _mlir_ciface_printMemrefInd(), _mlir_ciface_printMemrefVector4x4xf32(), and printMemRef().
printMemRef() [2/3]
template<typename T , int N> void impl::printMemRef (StridedMemRefType< T, N > & m)
Definition at line 231 of file RunnerUtils.h.
References printMemRef().
printMemRef() [3/3]
template<typename T > void impl::printMemRef (UnrankedMemRefType< T > & m)
Definition at line 237 of file RunnerUtils.h.
References printMemRef().
printMemRefShape() [1/2]
template<typename T , int N> void impl::printMemRefShape (StridedMemRefType< T, N > & m)
Definition at line 206 of file RunnerUtils.h.
References printMemRefMetaData().
printMemRefShape() [2/2]
template<typename T > void impl::printMemRefShape (UnrankedMemRefType< T > & m)
Definition at line 212 of file RunnerUtils.h.
References printMemRefMetaData().
printSpace()
static void impl::printSpace (std::ostream & os, int count) inline static
Definition at line 98 of file RunnerUtils.h.
Referenced by impl::VectorDataPrinter< T, M, Dims >::print(), impl::MemRefDataPrinter< T >::print(), impl::MemRefDataPrinter< T >::printLast(), mlir::FlatLinearConstraints::printSpace(), and mlir::FlatLinearValueConstraints::printSpace().
verifyMemRef() [1/2]
template<typename T > int64_t impl::verifyMemRef (const DynamicMemRefType< T > & actual, const DynamicMemRefType< T > & expected)
Verify the equivalence of two dynamic memrefs and return the number of errors or -1 if the shape of the memrefs do not match.
Definition at line 320 of file RunnerUtils.h.
References DynamicMemRefType< T >::data, DynamicMemRefType< T >::offset, printMemRefMetaData(), DynamicMemRefType< T >::rank, DynamicMemRefType< T >::sizes, DynamicMemRefType< T >::strides, and impl::MemRefDataVerifier< T >::verify().
Referenced by _mlir_ciface_verifyMemRefBF16(), _mlir_ciface_verifyMemRefC32(), _mlir_ciface_verifyMemRefC64(), _mlir_ciface_verifyMemRefF16(), _mlir_ciface_verifyMemRefF32(), _mlir_ciface_verifyMemRefF64(), _mlir_ciface_verifyMemRefI16(), _mlir_ciface_verifyMemRefI32(), _mlir_ciface_verifyMemRefI64(), _mlir_ciface_verifyMemRefI8(), _mlir_ciface_verifyMemRefInd(), and verifyMemRef().
verifyMemRef() [2/2]
template<typename T > int64_t impl::verifyMemRef (UnrankedMemRefType< T > & actual, UnrankedMemRefType< T > & expected)
Verify the equivalence of two unranked memrefs and return the number of errors or -1 if the shape of the memrefs do not match.
Definition at line 342 of file RunnerUtils.h.
References verifyMemRef().