MLIR: mlir::query Namespace Reference
mlir::query Namespace Reference
Namespaces
matcher
Computes the backward-slice of all transitive defs reachable from rootOp, if innerMatcher matches.
Classes
struct Query
struct InvalidQuery
struct NoOpQuery
struct HelpQuery
struct QuitQuery
struct MatchQuery
class QuerySession
class QueryParser
Typedefs
typedef llvm::IntrusiveRefCntPtr< Query > QueryRef
Enumerations
enum class QueryKind {
Invalid , NoOp , Help , Match ,
Quit
}
Functions
QueryRef parse (llvm::StringRef line, const QuerySession &qs)
std::vector< llvm::LineEditor::Completion > complete (llvm::StringRef line, size_t pos, const QuerySession &qs)
static Operation * extractFunction (std::vector< Operation * > &ops, MLIRContext *context, llvm::StringRef functionName)
Typedef Documentation
QueryRef
typedef llvm::IntrusiveRefCntPtr<Query> mlir::query::QueryRef
Definition at line 36 of file Query.h.
Enumeration Type Documentation
QueryKind
enum mlir::query::QueryKind strong
Enumerator
Invalid
NoOp
Match
Quit
Definition at line 20 of file Query.h.
Function Documentation
complete()
std::vector< llvm::LineEditor::Completion > mlir::query::complete (llvm::StringRef line, size_t pos, const QuerySession & qs)
Definition at line 26 of file Query.cpp.
References mlir::query::QueryParser::complete().
Referenced by mlir::mlirQueryMain().
extractFunction()
static Operation* mlir::query::extractFunction (std::vector< Operation * > & ops, MLIRContext * context, llvm::StringRef functionName) static
Definition at line 32 of file Query.cpp.
References mlir::detail::enumerate(), mlir::MLIRContext::loadDialect(), mlir::IRMapping::map(), mlir::Operation::result_begin(), and mlir::Operation::result_end().
Referenced by mlir::query::MatchQuery::run().
parse()
QueryRef mlir::query::parse (llvm::StringRef line, const QuerySession & qs)
Definition at line 21 of file Query.cpp.
References mlir::query::QueryParser::parse().
Referenced by mlir::RegisteredOperationName::Model< ConcreteOp >::getParseAssemblyFn(), mlir::mlirQueryMain(), mlir::FieldParser< ContainerT, std::enable_if_t< llvm::is_detected< detail::has_push_back_t, ContainerT >::value, ContainerT > >::parse(), mlir::AsmParser::parseCustomAttributeWithFallback(), mlir::AsmParser::parseCustomTypeWithFallback(), mlir::lsp::JSONTransport::run(), mlir::DynamicOpDefinition::setParseFn(), mlir::DynamicAttrDefinition::setParseFn(), and mlir::DynamicTypeDefinition::setParseFn().