MLIR: mlir::impl Namespace Reference
mlir::impl Namespace Reference
Attribute collections provide a dictionary-like interface.
Classes
class ArithToAMDGPUConversionPassBase
class ArithToAPFloatConversionPassBase
class ArithToArmSMEConversionPassBase
class ArithToLLVMConversionPassBase
class AsyncFuncToAsyncRuntimePassBase
class AsyncParallelForPassBase
class AsyncRuntimePolicyBasedRefCountingPassBase
class AsyncRuntimeRefCountingOptPassBase
class AsyncRuntimeRefCountingPassBase
class AsyncToAsyncRuntimePassBase
class BubbleDownMemorySpaceCastsBase
class CanonicalizerBase
class CompositeFixedPointPassBase
class ControlFlowSinkBase
class ConvertAffineForToGPUPassBase
class ConvertAMDGPUToROCDLPassBase
class ConvertArithToEmitCBase
class ConvertArithToSPIRVPassBase
class ConvertArmNeon2dToIntrPassBase
class ConvertArmSMEToLLVMBase
class ConvertArmSMEToSCFPassBase
class ConvertAsyncToLLVMPassBase
class ConvertBufferizationToMemRefPassBase
class ConvertComplexToLibmBase
class ConvertComplexToLLVMPassBase
class ConvertComplexToROCDLLibraryCallsBase
class ConvertComplexToSPIRVPassBase
class ConvertComplexToStandardPassBase
class ConvertControlFlowToLLVMPassBase
class ConvertControlFlowToSPIRVPassBase
class ConvertElementwiseToLinalgPassBase
class ConvertFuncToEmitCBase
class ConvertFuncToLLVMPassBase
class ConvertFuncToSPIRVPassBase
class ConvertGpuOpsToLLVMSPVOpsBase
class ConvertGpuOpsToNVVMOpsBase
class ConvertGpuOpsToROCDLOpsBase
class ConvertGPUToSPIRVBase
class ConvertIndexToLLVMPassBase
class ConvertIndexToSPIRVPassBase
class ConvertLinalgToAffineLoopsPassBase
class ConvertLinalgToLoopsPassBase
class ConvertLinalgToParallelLoopsPassBase
class ConvertLinalgToStandardPassBase
class ConvertMathToEmitCBase
class ConvertMathToFuncsBase
class ConvertMathToLibmPassBase
class ConvertMathToLLVMPassBase
class ConvertMathToROCDLBase
class ConvertMathToSPIRVPassBase
class ConvertMathToXeVMBase
class ConvertMemRefToEmitCBase
class ConvertMemRefToSPIRVPassBase
class ConvertNVGPUToNVVMPassBase
class ConvertNVVMToLLVMPassBase
class ConvertOpenACCToSCFPassBase
class ConvertOpenMPToLLVMPassBase
class ConvertParallelLoopToGpuPassBase
class ConvertPDLToPDLInterpPassBase
class ConvertSCFToOpenMPPassBase
class ConvertShapeConstraintsPassBase
class ConvertShapeToStandardPassBase
class ConvertShardToMPIPassBase
class ConvertSPIRVToLLVMPassBase
class ConvertTensorToLinalgPassBase
class ConvertTensorToSPIRVPassBase
class ConvertToEmitCBase
class ConvertToLLVMPassBase
class ConvertVectorToAMXBase
class ConvertVectorToArmSMEPassBase
class ConvertVectorToGPUBase
class ConvertVectorToLLVMPassBase
class ConvertVectorToSCFBase
class ConvertVectorToSPIRVPassBase
class ConvertVectorToXeGPUBase
class ConvertXeGPUToXeVMPassBase
class ConvertXeVMToLLVMPassBase
class CSEBase
class FinalizeMemRefToLLVMConversionPassBase
class GenerateRuntimeVerificationBase
class GpuAsyncRegionPassBase
class GpuDecomposeMemrefsPassBase
class GpuEliminateBarriersBase
class GpuKernelOutliningPassBase
class GpuLaunchSinkIndexComputationsPassBase
class GpuMapParallelLoopsPassBase
class GpuModuleToBinaryPassBase
class GpuNVVMAttachTargetBase
class GpuROCDLAttachTargetBase
class GpuSPIRVAttachTargetBase
class GpuToLLVMConversionPassBase
class GpuXeVMAttachTargetBase
class InlinerBase
class LiftControlFlowToSCFPassBase
class LinalgBlockPackMatmulBase
class LinalgDetensorizePassBase
class LinalgElementwiseOpFusionPassBase
class LinalgFoldIntoElementwisePassBase
class LinalgFoldUnitExtentDimsPassBase
class LinalgGeneralizeNamedOpsPassBase
class LinalgInlineScalarOperandsPassBase
class LinalgMorphOpsPassBase
class LinalgSpecializeGenericOpsPassBase
class LocationSnapshotBase
class LoopInvariantCodeMotionBase
class LoopInvariantSubsetHoistingBase
class LowerAffinePassBase
class LowerForeachToSCFBase
class LowerHostCodeToLLVMPassBase
class LowerSparseIterationToSCFBase
class LowerSparseOpsToForeachBase
class MapMemRefStorageClassBase
class Mem2RegBase
class OptReductionPassBase
class OutlineShapeComputationPassBase
class PreSparsificationRewriteBase
class PrintOpStatsBase
class ReconcileUnrealizedCastsPassBase
class ReductionTreePassBase
class RemoveDeadValuesBase
class RemoveShapeConstraintsPassBase
class SCCPBase
class SCFForallToForLoopBase
class SCFForallToParallelLoopBase
class SCFForLoopCanonicalizationBase
class SCFForLoopPeelingBase
class SCFForLoopRangeFoldingBase
class SCFForLoopSpecializationBase
class SCFForToWhileLoopBase
class SCFParallelForToNestedForsBase
class SCFParallelLoopFusionBase
class SCFParallelLoopSpecializationBase
class SCFParallelLoopTilingBase
class SCFToControlFlowPassBase
class SCFToEmitCBase
class SCFToSPIRVBase
class SetLLVMModuleDataLayoutPassBase
class ShapeToShapeLoweringPassBase
class SimplifyDepthwiseConvPassBase
class SparseAssemblerBase
class SparseBufferRewriteBase
class SparseGPUCodegenBase
class SparseReinterpretMapBase
class SparseSpaceCollapseBase
class SparseTensorCodegenBase
class SparseTensorConversionPassBase
class SparseVectorizationBase
class SparsificationAndBufferizationBase
class SparsificationPassBase
class SROABase
class StageSparseOperationsBase
class StorageSpecifierToLLVMBase
class StripDebugInfoBase
class SymbolDCEBase
class SymbolPrivatizeBase
class TestSCFParallelLoopCollapsingBase
class TopologicalSortBase
class TosaToArithPassBase
class TosaToLinalgBase
class TosaToLinalgNamedBase
class TosaToMLProgramBase
class TosaToSCFPassBase
class TosaToTensorPassBase
class UBToLLVMConversionPassBase
class UBToSPIRVConversionPassBase
class ViewOpGraphBase
Functions
LogicalResult verifyHasDefaultDLTIDataLayoutTrait (Operation *op)
DataLayoutSpecInterface getDataLayoutSpec (Operation *op)
TargetSystemSpecInterface getTargetSystemSpec (Operation *op)
LogicalResult foldCastInterfaceOp (Operation *op, ArrayRef< Attribute > attrOperands, SmallVectorImpl< OpFoldResult > &foldResults)
Attempt to fold the given cast operation.
LogicalResult verifyCastInterfaceOp (Operation *op)
Attempt to verify the given cast operation.
void ensureRegionTerminator (Region &region, OpBuilder &builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Insert an operation, generated by buildTerminatorOp, at the end of the region's only block if it does not have a terminator already.
void ensureRegionTerminator (Region &region, Builder &builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Create a simple OpBuilder and forward to the OpBuilder version of this function.
template<typename IteratorT, typename NameT>
std::pair< IteratorT, bool > findAttrUnsorted (IteratorT first, IteratorT last, NameT name)
Unsorted string search or identifier lookups are linear scans.
template<typename IteratorT>
std::pair< IteratorT, bool > findAttrSorted (IteratorT first, IteratorT last, StringRef name)
Using llvm::lower_bound requires an extra string comparison to check whether the returned iterator points to the found element or whether it indicates the lower bound.
template<typename IteratorT>
std::pair< IteratorT, bool > findAttrSorted (IteratorT first, IteratorT last, StringAttr name)
StringAttr lookups on large attribute lists will switch to string binary search.
template<typename IteratorT, typename NameT>
Attribute getAttrFromSortedRange (IteratorT first, IteratorT last, NameT name)
Get an attribute from a sorted range of named attributes.
template<typename IteratorT, typename NameT>
std::optional< NamedAttribute > getNamedAttrFromSortedRange (IteratorT first, IteratorT last, NameT name)
Get an attribute from a sorted range of named attributes.
ParseResult parseOptionalVisibilityKeyword (OpAsmParser &parser, NamedAttrList &attrs)
Parse an optional visibility attribute keyword (i.e., public, private, or nested) without quotes in a string attribute named 'attrName'.
std::unique_ptr<::mlir::Pass > createLowerAffinePass ()
std::unique_ptr<::mlir::Pass > createConvertAMDGPUToROCDLPass ()
std::unique_ptr<::mlir::Pass > createConvertAMDGPUToROCDLPass (ConvertAMDGPUToROCDLPassOptions options)
std::unique_ptr<::mlir::Pass > createArithToAMDGPUConversionPass ()
std::unique_ptr<::mlir::Pass > createArithToAMDGPUConversionPass (ArithToAMDGPUConversionPassOptions options)
std::unique_ptr<::mlir::Pass > createArithToAPFloatConversionPass ()
std::unique_ptr<::mlir::Pass > createArithToArmSMEConversionPass ()
std::unique_ptr<::mlir::Pass > createConvertArithToEmitC ()
std::unique_ptr<::mlir::Pass > createArithToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > createArithToLLVMConversionPass (ArithToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertArithToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertArithToSPIRVPass (ConvertArithToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertArmNeon2dToIntrPass ()
std::unique_ptr<::mlir::Pass > createConvertArmSMEToSCFPass ()
std::unique_ptr<::mlir::Pass > createConvertAsyncToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertBufferizationToMemRefPass ()
std::unique_ptr<::mlir::Pass > createConvertComplexToLibm ()
std::unique_ptr<::mlir::Pass > createConvertComplexToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertComplexToLLVMPass (ConvertComplexToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertComplexToROCDLLibraryCalls ()
std::unique_ptr<::mlir::Pass > createConvertComplexToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertComplexToStandardPass ()
std::unique_ptr<::mlir::Pass > createConvertComplexToStandardPass (ConvertComplexToStandardPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertControlFlowToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertControlFlowToLLVMPass (ConvertControlFlowToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createLiftControlFlowToSCFPass ()
std::unique_ptr<::mlir::Pass > createConvertControlFlowToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertControlFlowToSPIRVPass (ConvertControlFlowToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertToEmitC ()
std::unique_ptr<::mlir::Pass > createConvertToEmitC (ConvertToEmitCOptions options)
std::unique_ptr<::mlir::Pass > createConvertToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertToLLVMPass (ConvertToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertFuncToEmitC ()
std::unique_ptr<::mlir::Pass > createConvertFuncToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertFuncToLLVMPass (ConvertFuncToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createSetLLVMModuleDataLayoutPass ()
std::unique_ptr<::mlir::Pass > createSetLLVMModuleDataLayoutPass (SetLLVMModuleDataLayoutPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertFuncToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertFuncToSPIRVPass (ConvertFuncToSPIRVPassOptions options)
LogicalResult scalarizeVectorOp (Operation *op, ValueRange operands, ConversionPatternRewriter &rewriter, const LLVMTypeConverter &converter)
Unrolls op to array/vector elements.
std::unique_ptr<::mlir::Pass > createGpuToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > createGpuToLLVMConversionPass (GpuToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertGpuOpsToLLVMSPVOps ()
std::unique_ptr<::mlir::Pass > createConvertGpuOpsToLLVMSPVOps (ConvertGpuOpsToLLVMSPVOpsOptions options)
std::unique_ptr<::mlir::Pass > createConvertGpuOpsToNVVMOps ()
std::unique_ptr<::mlir::Pass > createConvertGpuOpsToNVVMOps (ConvertGpuOpsToNVVMOpsOptions options)
std::unique_ptr<::mlir::Pass > createConvertGpuOpsToROCDLOps ()
std::unique_ptr<::mlir::Pass > createConvertGpuOpsToROCDLOps (ConvertGpuOpsToROCDLOpsOptions options)
std::unique_ptr<::mlir::Pass > createConvertIndexToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertIndexToLLVMPass (ConvertIndexToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertIndexToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertIndexToSPIRVPass (ConvertIndexToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertLinalgToStandardPass ()
std::unique_ptr<::mlir::Pass > createConvertMathToEmitC ()
std::unique_ptr<::mlir::Pass > createConvertMathToEmitC (ConvertMathToEmitCOptions options)
std::unique_ptr<::mlir::Pass > createConvertMathToFuncs ()
std::unique_ptr<::mlir::Pass > createConvertMathToFuncs (ConvertMathToFuncsOptions options)
std::unique_ptr<::mlir::Pass > createConvertMathToLibmPass ()
std::unique_ptr<::mlir::Pass > createConvertMathToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertMathToLLVMPass (ConvertMathToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertMathToROCDL ()
std::unique_ptr<::mlir::Pass > createConvertMathToROCDL (ConvertMathToROCDLOptions options)
std::unique_ptr<::mlir::Pass > createConvertMathToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertMathToXeVM ()
std::unique_ptr<::mlir::Pass > createConvertMathToXeVM (ConvertMathToXeVMOptions options)
std::unique_ptr<::mlir::Pass > createConvertMemRefToEmitC ()
std::unique_ptr<::mlir::Pass > createConvertMemRefToEmitC (ConvertMemRefToEmitCOptions options)
std::unique_ptr<::mlir::Pass > createFinalizeMemRefToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > createFinalizeMemRefToLLVMConversionPass (FinalizeMemRefToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertMemRefToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertMemRefToSPIRVPass (ConvertMemRefToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertNVGPUToNVVMPass ()
std::unique_ptr<::mlir::Pass > createConvertNVVMToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertOpenACCToSCFPass ()
std::unique_ptr<::mlir::Pass > createConvertOpenMPToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertPDLToPDLInterpPass ()
std::unique_ptr<::mlir::Pass > createReconcileUnrealizedCastsPass ()
std::unique_ptr<::mlir::Pass > createSCFToControlFlowPass ()
std::unique_ptr<::mlir::Pass > createSCFToControlFlowPass (SCFToControlFlowPassOptions options)
std::unique_ptr<::mlir::Pass > createSCFToEmitC ()
std::unique_ptr<::mlir::Pass > createConvertAffineForToGPUPass ()
std::unique_ptr<::mlir::Pass > createConvertAffineForToGPUPass (ConvertAffineForToGPUPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertParallelLoopToGpuPass ()
std::unique_ptr<::mlir::Pass > createConvertSCFToOpenMPPass ()
std::unique_ptr<::mlir::Pass > createConvertSCFToOpenMPPass (ConvertSCFToOpenMPPassOptions options)
std::unique_ptr<::mlir::Pass > createSCFToSPIRV ()
std::unique_ptr<::mlir::Pass > createConvertShapeConstraintsPass ()
std::unique_ptr<::mlir::Pass > createConvertShapeToStandardPass ()
std::unique_ptr<::mlir::Pass > createConvertShardToMPIPass ()
std::unique_ptr<::mlir::Pass > createLowerHostCodeToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertSPIRVToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertSPIRVToLLVMPass (ConvertSPIRVToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertTensorToLinalgPass ()
std::unique_ptr<::mlir::Pass > createConvertTensorToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertTensorToSPIRVPass (ConvertTensorToSPIRVPassOptions options)
std::unique_ptr<::mlir::Pass > createTosaToArithPass ()
std::unique_ptr<::mlir::Pass > createTosaToArithPass (TosaToArithPassOptions options)
std::unique_ptr<::mlir::Pass > createTosaToMLProgram ()
std::unique_ptr<::mlir::Pass > createTosaToSCFPass ()
std::unique_ptr<::mlir::Pass > createTosaToTensorPass ()
std::unique_ptr<::mlir::Pass > createUBToLLVMConversionPass ()
std::unique_ptr<::mlir::Pass > createUBToLLVMConversionPass (UBToLLVMConversionPassOptions options)
std::unique_ptr<::mlir::Pass > createUBToSPIRVConversionPass ()
std::unique_ptr<::mlir::Pass > createConvertVectorToAMX ()
std::unique_ptr<::mlir::Pass > createConvertVectorToArmSMEPass ()
std::unique_ptr<::mlir::Pass > createConvertVectorToLLVMPass ()
std::unique_ptr<::mlir::Pass > createConvertVectorToLLVMPass (ConvertVectorToLLVMPassOptions options)
std::unique_ptr<::mlir::Pass > createConvertVectorToSPIRVPass ()
std::unique_ptr<::mlir::Pass > createConvertVectorToXeGPU ()
std::unique_ptr<::mlir::Pass > createConvertXeGPUToXeVMPass ()
std::unique_ptr<::mlir::Pass > createConvertXeVMToLLVMPass ()
std::unique_ptr<::mlir::Pass > createAsyncParallelForPass ()
std::unique_ptr<::mlir::Pass > createAsyncParallelForPass (AsyncParallelForPassOptions options)
std::unique_ptr<::mlir::Pass > createAsyncRuntimePolicyBasedRefCountingPass ()
std::unique_ptr<::mlir::Pass > createAsyncRuntimeRefCountingPass ()
std::unique_ptr<::mlir::Pass > createAsyncRuntimeRefCountingOptPass ()
std::unique_ptr<::mlir::Pass > createAsyncFuncToAsyncRuntimePass ()
std::unique_ptr<::mlir::Pass > createAsyncToAsyncRuntimePass ()
std::unique_ptr<::mlir::Pass > createGpuAsyncRegionPass ()
std::unique_ptr<::mlir::Pass > createGpuDecomposeMemrefsPass ()
std::unique_ptr<::mlir::Pass > createGpuEliminateBarriers ()
std::unique_ptr<::mlir::Pass > createGpuKernelOutliningPass ()
std::unique_ptr<::mlir::Pass > createGpuKernelOutliningPass (GpuKernelOutliningPassOptions options)
std::unique_ptr<::mlir::Pass > createGpuLaunchSinkIndexComputationsPass ()
std::unique_ptr<::mlir::Pass > createGpuModuleToBinaryPass ()
std::unique_ptr<::mlir::Pass > createGpuModuleToBinaryPass (GpuModuleToBinaryPassOptions options)
std::unique_ptr<::mlir::Pass > createGpuNVVMAttachTarget ()
std::unique_ptr<::mlir::Pass > createGpuNVVMAttachTarget (GpuNVVMAttachTargetOptions options)
std::unique_ptr<::mlir::Pass > createGpuMapParallelLoopsPass ()
std::unique_ptr<::mlir::Pass > createGpuMapParallelLoopsPass (GpuMapParallelLoopsPassOptions options)
std::unique_ptr<::mlir::Pass > createGpuROCDLAttachTarget ()
std::unique_ptr<::mlir::Pass > createGpuROCDLAttachTarget (GpuROCDLAttachTargetOptions options)
std::unique_ptr<::mlir::Pass > createGpuSPIRVAttachTarget ()
std::unique_ptr<::mlir::Pass > createGpuSPIRVAttachTarget (GpuSPIRVAttachTargetOptions options)
std::unique_ptr<::mlir::Pass > createGpuXeVMAttachTarget ()
std::unique_ptr<::mlir::Pass > createGpuXeVMAttachTarget (GpuXeVMAttachTargetOptions options)
std::unique_ptr<::mlir::Pass > createLinalgBlockPackMatmul ()
std::unique_ptr<::mlir::Pass > createLinalgBlockPackMatmul (LinalgBlockPackMatmulOptions options)
std::unique_ptr<::mlir::Pass > createLinalgDetensorizePass ()
std::unique_ptr<::mlir::Pass > createLinalgDetensorizePass (LinalgDetensorizePassOptions options)
std::unique_ptr<::mlir::Pass > createLinalgFoldUnitExtentDimsPass ()
std::unique_ptr<::mlir::Pass > createLinalgFoldUnitExtentDimsPass (LinalgFoldUnitExtentDimsPassOptions options)
std::unique_ptr<::mlir::Pass > createLinalgElementwiseOpFusionPass ()
std::unique_ptr<::mlir::Pass > createConvertElementwiseToLinalgPass ()
std::unique_ptr<::mlir::Pass > createLinalgFoldIntoElementwisePass ()
std::unique_ptr<::mlir::Pass > createLinalgGeneralizeNamedOpsPass ()
std::unique_ptr<::mlir::Pass > createLinalgInlineScalarOperandsPass ()
std::unique_ptr<::mlir::Pass > createConvertLinalgToAffineLoopsPass ()
std::unique_ptr<::mlir::Pass > createConvertLinalgToLoopsPass ()
std::unique_ptr<::mlir::Pass > createConvertLinalgToParallelLoopsPass ()
std::unique_ptr<::mlir::Pass > createLinalgMorphOpsPass ()
std::unique_ptr<::mlir::Pass > createLinalgMorphOpsPass (LinalgMorphOpsPassOptions options)
std::unique_ptr<::mlir::Pass > createSimplifyDepthwiseConvPass ()
std::unique_ptr<::mlir::Pass > createLinalgSpecializeGenericOpsPass ()
std::unique_ptr<::mlir::Pass > createOutlineShapeComputationPass ()
std::unique_ptr<::mlir::Pass > createRemoveShapeConstraintsPass ()
std::unique_ptr<::mlir::Pass > createShapeToShapeLoweringPass ()
std::unique_ptr<::mlir::Pass > createOptReductionPass ()
std::unique_ptr<::mlir::Pass > createOptReductionPass (OptReductionPassOptions options)
std::unique_ptr<::mlir::Pass > createReductionTreePass ()
std::unique_ptr<::mlir::Pass > createReductionTreePass (ReductionTreePassOptions options)
std::unique_ptr<::mlir::Pass > createBubbleDownMemorySpaceCasts ()
std::unique_ptr<::mlir::Pass > createCompositeFixedPointPass ()
std::unique_ptr<::mlir::Pass > createCompositeFixedPointPass (CompositeFixedPointPassOptions options)
std::unique_ptr<::mlir::Pass > createLocationSnapshot ()
std::unique_ptr<::mlir::Pass > createLocationSnapshot (LocationSnapshotOptions options)
std::unique_ptr<::mlir::Pass > createMem2Reg ()
std::unique_ptr<::mlir::Pass > createMem2Reg (Mem2RegOptions options)
std::unique_ptr<::mlir::Pass > createSROA ()
Detailed Description
Attribute collections provide a dictionary-like interface.
Define common lookup functions.
Function Documentation
createArithToAMDGPUConversionPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToAMDGPUConversionPass ()
Definition at line 173 of file ArithToAMDGPU.cpp.
createArithToAMDGPUConversionPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToAMDGPUConversionPass (ArithToAMDGPUConversionPassOptions options)
Definition at line 177 of file ArithToAMDGPU.cpp.
createArithToAPFloatConversionPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToAPFloatConversionPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 258 of file ArithToAPFloat.cpp.
createArithToArmSMEConversionPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToArmSMEConversionPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 333 of file ArithToArmSME.cpp.
createArithToLLVMConversionPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToLLVMConversionPass ()
Definition at line 420 of file ArithToLLVM.cpp.
createArithToLLVMConversionPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createArithToLLVMConversionPass (ArithToLLVMConversionPassOptions options)
Definition at line 424 of file ArithToLLVM.cpp.
createAsyncFuncToAsyncRuntimePass()
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncFuncToAsyncRuntimePass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 79 of file AsyncToAsyncRuntime.cpp.
createAsyncParallelForPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncParallelForPass ()
Definition at line 175 of file AsyncParallelFor.cpp.
createAsyncParallelForPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncParallelForPass (AsyncParallelForPassOptions options)
Definition at line 179 of file AsyncParallelFor.cpp.
createAsyncRuntimePolicyBasedRefCountingPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncRuntimePolicyBasedRefCountingPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 258 of file AsyncRuntimeRefCounting.cpp.
createAsyncRuntimeRefCountingOptPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncRuntimeRefCountingOptPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 333 of file AsyncRuntimeRefCountingOpt.cpp.
createAsyncRuntimeRefCountingPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncRuntimeRefCountingPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 408 of file AsyncRuntimeRefCounting.cpp.
createAsyncToAsyncRuntimePass()
std::unique_ptr<::mlir::Pass > mlir::impl::createAsyncToAsyncRuntimePass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 485 of file AsyncToAsyncRuntime.cpp.
createBubbleDownMemorySpaceCasts()
std::unique_ptr<::mlir::Pass > mlir::impl::createBubbleDownMemorySpaceCasts ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 93 of file BubbleDownMemorySpaceCasts.cpp.
createCompositeFixedPointPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createCompositeFixedPointPass ()
Definition at line 344 of file CompositePass.cpp.
createCompositeFixedPointPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createCompositeFixedPointPass (CompositeFixedPointPassOptions options)
Definition at line 348 of file CompositePass.cpp.
createConvertAffineForToGPUPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertAffineForToGPUPass ()
Definition at line 614 of file SCFToGPUPass.cpp.
createConvertAffineForToGPUPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertAffineForToGPUPass (ConvertAffineForToGPUPassOptions options)
Definition at line 618 of file SCFToGPUPass.cpp.
createConvertAMDGPUToROCDLPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertAMDGPUToROCDLPass ()
Definition at line 516 of file AMDGPUToROCDL.cpp.
createConvertAMDGPUToROCDLPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertAMDGPUToROCDLPass (ConvertAMDGPUToROCDLPassOptions options)
Definition at line 520 of file AMDGPUToROCDL.cpp.
createConvertArithToEmitC()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertArithToEmitC ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 697 of file ArithToEmitCPass.cpp.
createConvertArithToSPIRVPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertArithToSPIRVPass ()
Definition at line 787 of file ArithToSPIRV.cpp.
createConvertArithToSPIRVPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertArithToSPIRVPass (ConvertArithToSPIRVPassOptions options)
Definition at line 791 of file ArithToSPIRV.cpp.
createConvertArmNeon2dToIntrPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertArmNeon2dToIntrPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 871 of file ArmNeon2dToIntr.cpp.
createConvertArmSMEToSCFPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertArmSMEToSCFPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1019 of file ArmSMEToSCF.cpp.
createConvertAsyncToLLVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertAsyncToLLVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1097 of file AsyncToLLVM.cpp.
createConvertBufferizationToMemRefPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertBufferizationToMemRefPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1175 of file BufferizationToMemRef.cpp.
createConvertComplexToLibm()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToLibm ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1349 of file ComplexToLibm.cpp.
createConvertComplexToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToLLVMPass ()
Definition at line 1266 of file ComplexToLLVM.cpp.
createConvertComplexToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToLLVMPass (ConvertComplexToLLVMPassOptions options)
Definition at line 1270 of file ComplexToLLVM.cpp.
createConvertComplexToROCDLLibraryCalls()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToROCDLLibraryCalls ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1424 of file ComplexToROCDLLibraryCalls.cpp.
createConvertComplexToSPIRVPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToSPIRVPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1499 of file ComplexToSPIRVPass.cpp.
createConvertComplexToStandardPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToStandardPass ()
Definition at line 1590 of file ComplexToStandard.cpp.
createConvertComplexToStandardPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertComplexToStandardPass (ConvertComplexToStandardPassOptions options)
Definition at line 1594 of file ComplexToStandard.cpp.
createConvertControlFlowToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertControlFlowToLLVMPass ()
Definition at line 1685 of file ControlFlowToLLVM.cpp.
createConvertControlFlowToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertControlFlowToLLVMPass (ConvertControlFlowToLLVMPassOptions options)
Definition at line 1689 of file ControlFlowToLLVM.cpp.
createConvertControlFlowToSPIRVPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertControlFlowToSPIRVPass ()
Definition at line 1783 of file ControlFlowToSPIRVPass.cpp.
createConvertControlFlowToSPIRVPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertControlFlowToSPIRVPass (ConvertControlFlowToSPIRVPassOptions options)
Definition at line 1787 of file ControlFlowToSPIRVPass.cpp.
createConvertElementwiseToLinalgPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertElementwiseToLinalgPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 87 of file ElementwiseToLinalg.cpp.
createConvertFuncToEmitC()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertFuncToEmitC ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1866 of file FuncToEmitCPass.cpp.
createConvertFuncToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertFuncToLLVMPass ()
Definition at line 1956 of file FuncToLLVM.cpp.
createConvertFuncToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertFuncToLLVMPass (ConvertFuncToLLVMPassOptions options)
Definition at line 1960 of file FuncToLLVM.cpp.
createConvertFuncToSPIRVPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertFuncToSPIRVPass ()
Definition at line 2054 of file FuncToSPIRVPass.cpp.
createConvertFuncToSPIRVPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertFuncToSPIRVPass (ConvertFuncToSPIRVPassOptions options)
Definition at line 2058 of file FuncToSPIRVPass.cpp.
createConvertGpuOpsToLLVMSPVOps() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToLLVMSPVOps ()
Definition at line 2219 of file GPUToLLVMSPV.cpp.
createConvertGpuOpsToLLVMSPVOps() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToLLVMSPVOps (ConvertGpuOpsToLLVMSPVOpsOptions options)
Definition at line 2223 of file GPUToLLVMSPV.cpp.
createConvertGpuOpsToNVVMOps() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToNVVMOps ()
Definition at line 2328 of file LowerGpuOpsToNVVMOps.cpp.
createConvertGpuOpsToNVVMOps() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToNVVMOps (ConvertGpuOpsToNVVMOpsOptions options)
Definition at line 2332 of file LowerGpuOpsToNVVMOps.cpp.
createConvertGpuOpsToROCDLOps() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToROCDLOps ()
Definition at line 2443 of file LowerGpuOpsToROCDLOps.cpp.
createConvertGpuOpsToROCDLOps() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertGpuOpsToROCDLOps (ConvertGpuOpsToROCDLOpsOptions options)
Definition at line 2447 of file LowerGpuOpsToROCDLOps.cpp.
createConvertIndexToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertIndexToLLVMPass ()
Definition at line 2538 of file IndexToLLVM.cpp.
createConvertIndexToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertIndexToLLVMPass (ConvertIndexToLLVMPassOptions options)
Definition at line 2542 of file IndexToLLVM.cpp.
createConvertIndexToSPIRVPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertIndexToSPIRVPass ()
Definition at line 2633 of file IndexToSPIRV.cpp.
createConvertIndexToSPIRVPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertIndexToSPIRVPass (ConvertIndexToSPIRVPassOptions options)
Definition at line 2637 of file IndexToSPIRV.cpp.
createConvertLinalgToAffineLoopsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertLinalgToAffineLoopsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 164 of file Loops.cpp.
createConvertLinalgToLoopsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertLinalgToLoopsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 241 of file Loops.cpp.
createConvertLinalgToParallelLoopsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertLinalgToParallelLoopsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 319 of file Loops.cpp.
createConvertLinalgToStandardPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertLinalgToStandardPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 2717 of file LinalgToStandard.cpp.
createConvertMathToEmitC() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToEmitC ()
Definition at line 2807 of file MathToEmitCPass.cpp.
createConvertMathToEmitC() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToEmitC (ConvertMathToEmitCOptions options)
Definition at line 2811 of file MathToEmitCPass.cpp.
createConvertMathToFuncs() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToFuncs ()
Definition at line 2910 of file MathToFuncs.cpp.
createConvertMathToFuncs() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToFuncs (ConvertMathToFuncsOptions options)
Definition at line 2914 of file MathToFuncs.cpp.
createConvertMathToLibmPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToLibmPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3090 of file MathToLibm.cpp.
createConvertMathToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToLLVMPass ()
Definition at line 3005 of file MathToLLVM.cpp.
createConvertMathToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToLLVMPass (ConvertMathToLLVMPassOptions options)
Definition at line 3009 of file MathToLLVM.cpp.
createConvertMathToROCDL() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToROCDL ()
Definition at line 3180 of file MathToROCDL.cpp.
createConvertMathToROCDL() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToROCDL (ConvertMathToROCDLOptions options)
Definition at line 3184 of file MathToROCDL.cpp.
createConvertMathToSPIRVPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToSPIRVPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3263 of file MathToSPIRVPass.cpp.
createConvertMathToXeVM() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToXeVM ()
Definition at line 3352 of file MathToXeVM.cpp.
createConvertMathToXeVM() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMathToXeVM (ConvertMathToXeVMOptions options)
Definition at line 3356 of file MathToXeVM.cpp.
createConvertMemRefToEmitC() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMemRefToEmitC ()
Definition at line 3447 of file MemRefToEmitCPass.cpp.
createConvertMemRefToEmitC() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMemRefToEmitC (ConvertMemRefToEmitCOptions options)
Definition at line 3451 of file MemRefToEmitCPass.cpp.
createConvertMemRefToSPIRVPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMemRefToSPIRVPass ()
Definition at line 3545 of file MemRefToSPIRVPass.cpp.
createConvertMemRefToSPIRVPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertMemRefToSPIRVPass (ConvertMemRefToSPIRVPassOptions options)
Definition at line 3549 of file MemRefToSPIRVPass.cpp.
createConvertNVGPUToNVVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertNVGPUToNVVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3631 of file NVGPUToNVVM.cpp.
createConvertNVVMToLLVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertNVVMToLLVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3706 of file NVVMToLLVM.cpp.
createConvertOpenACCToSCFPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertOpenACCToSCFPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3782 of file OpenACCToSCF.cpp.
createConvertOpenMPToLLVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertOpenMPToLLVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3857 of file OpenMPToLLVM.cpp.
createConvertParallelLoopToGpuPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertParallelLoopToGpuPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4008 of file SCFToGPUPass.cpp.
createConvertPDLToPDLInterpPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertPDLToPDLInterpPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 3932 of file PDLToPDLInterp.cpp.
createConvertSCFToOpenMPPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertSCFToOpenMPPass ()
Definition at line 4097 of file SCFToOpenMP.cpp.
createConvertSCFToOpenMPPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertSCFToOpenMPPass (ConvertSCFToOpenMPPassOptions options)
Definition at line 4101 of file SCFToOpenMP.cpp.
createConvertShapeConstraintsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertShapeConstraintsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4282 of file ConvertShapeConstraints.cpp.
createConvertShapeToStandardPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertShapeToStandardPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4357 of file ShapeToStandard.cpp.
createConvertShardToMPIPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertShardToMPIPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4437 of file ShardToMPI.cpp.
createConvertSPIRVToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertSPIRVToLLVMPass ()
Definition at line 4198 of file SPIRVToLLVMPass.cpp.
createConvertSPIRVToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertSPIRVToLLVMPass (ConvertSPIRVToLLVMPassOptions options)
Definition at line 4202 of file SPIRVToLLVMPass.cpp.
createConvertTensorToLinalgPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertTensorToLinalgPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4513 of file TensorToLinalgPass.cpp.
createConvertTensorToSPIRVPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertTensorToSPIRVPass ()
Definition at line 4603 of file TensorToSPIRVPass.cpp.
createConvertTensorToSPIRVPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertTensorToSPIRVPass (ConvertTensorToSPIRVPassOptions options)
Definition at line 4607 of file TensorToSPIRVPass.cpp.
createConvertToEmitC() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertToEmitC ()
Definition at line 4698 of file ConvertToEmitCPass.cpp.
createConvertToEmitC() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertToEmitC (ConvertToEmitCOptions options)
Definition at line 4702 of file ConvertToEmitCPass.cpp.
createConvertToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertToLLVMPass ()
Definition at line 4799 of file ConvertToLLVMPass.cpp.
createConvertToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertToLLVMPass (ConvertToLLVMPassOptions options)
Definition at line 4803 of file ConvertToLLVMPass.cpp.
createConvertVectorToAMX()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertVectorToAMX ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4887 of file VectorToAMX.cpp.
createConvertVectorToArmSMEPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertVectorToArmSMEPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 4963 of file VectorToArmSMEPass.cpp.
createConvertVectorToLLVMPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertVectorToLLVMPass ()
Definition at line 5171 of file ConvertVectorToLLVMPass.cpp.
createConvertVectorToLLVMPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertVectorToLLVMPass (ConvertVectorToLLVMPassOptions options)
Definition at line 5175 of file ConvertVectorToLLVMPass.cpp.
createConvertVectorToSPIRVPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertVectorToSPIRVPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 5336 of file VectorToSPIRVPass.cpp.
createConvertVectorToXeGPU()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertVectorToXeGPU ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 5414 of file VectorToXeGPU.cpp.
createConvertXeGPUToXeVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertXeGPUToXeVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 5496 of file XeGPUToXeVM.cpp.
createConvertXeVMToLLVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createConvertXeVMToLLVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 5571 of file XeVMToLLVM.cpp.
createFinalizeMemRefToLLVMConversionPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createFinalizeMemRefToLLVMConversionPass ()
Definition at line 5664 of file MemRefToLLVM.cpp.
createFinalizeMemRefToLLVMConversionPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createFinalizeMemRefToLLVMConversionPass (FinalizeMemRefToLLVMConversionPassOptions options)
Definition at line 5668 of file MemRefToLLVM.cpp.
createGpuAsyncRegionPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuAsyncRegionPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 83 of file AsyncRegionRewriter.cpp.
createGpuDecomposeMemrefsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuDecomposeMemrefsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 160 of file DecomposeMemRefs.cpp.
createGpuEliminateBarriers()
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuEliminateBarriers ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 237 of file EliminateBarriers.cpp.
createGpuKernelOutliningPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuKernelOutliningPass ()
Definition at line 325 of file KernelOutlining.cpp.
createGpuKernelOutliningPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuKernelOutliningPass (GpuKernelOutliningPassOptions options)
Definition at line 329 of file KernelOutlining.cpp.
createGpuLaunchSinkIndexComputationsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuLaunchSinkIndexComputationsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 408 of file KernelOutlining.cpp.
createGpuMapParallelLoopsPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuMapParallelLoopsPass ()
Definition at line 495 of file ParallelLoopMapper.cpp.
createGpuMapParallelLoopsPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuMapParallelLoopsPass (GpuMapParallelLoopsPassOptions options)
Definition at line 499 of file ParallelLoopMapper.cpp.
createGpuModuleToBinaryPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuModuleToBinaryPass ()
Definition at line 602 of file ModuleToBinary.cpp.
createGpuModuleToBinaryPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuModuleToBinaryPass (GpuModuleToBinaryPassOptions options)
Definition at line 606 of file ModuleToBinary.cpp.
createGpuNVVMAttachTarget() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuNVVMAttachTarget ()
Definition at line 721 of file NVVMAttachTarget.cpp.
createGpuNVVMAttachTarget() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuNVVMAttachTarget (GpuNVVMAttachTargetOptions options)
Definition at line 725 of file NVVMAttachTarget.cpp.
createGpuROCDLAttachTarget() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuROCDLAttachTarget ()
Definition at line 852 of file ROCDLAttachTarget.cpp.
createGpuROCDLAttachTarget() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuROCDLAttachTarget (GpuROCDLAttachTargetOptions options)
Definition at line 856 of file ROCDLAttachTarget.cpp.
createGpuSPIRVAttachTarget() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuSPIRVAttachTarget ()
Definition at line 968 of file SPIRVAttachTarget.cpp.
createGpuSPIRVAttachTarget() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuSPIRVAttachTarget (GpuSPIRVAttachTargetOptions options)
Definition at line 972 of file SPIRVAttachTarget.cpp.
createGpuToLLVMConversionPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuToLLVMConversionPass ()
Definition at line 5766 of file GPUToLLVMConversion.cpp.
createGpuToLLVMConversionPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuToLLVMConversionPass (GpuToLLVMConversionPassOptions options)
Definition at line 5770 of file GPUToLLVMConversion.cpp.
createGpuXeVMAttachTarget() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuXeVMAttachTarget ()
Definition at line 1078 of file XeVMAttachTarget.cpp.
createGpuXeVMAttachTarget() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createGpuXeVMAttachTarget (GpuXeVMAttachTargetOptions options)
Definition at line 1082 of file XeVMAttachTarget.cpp.
createLiftControlFlowToSCFPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLiftControlFlowToSCFPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 5852 of file ControlFlowToSCF.cpp.
createLinalgBlockPackMatmul() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgBlockPackMatmul ()
Definition at line 428 of file BlockPackMatmul.cpp.
createLinalgBlockPackMatmul() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgBlockPackMatmul (LinalgBlockPackMatmulOptions options)
Definition at line 432 of file BlockPackMatmul.cpp.
createLinalgDetensorizePass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgDetensorizePass ()
Definition at line 523 of file Detensorize.cpp.
createLinalgDetensorizePass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgDetensorizePass (LinalgDetensorizePassOptions options)
Definition at line 527 of file Detensorize.cpp.
createLinalgElementwiseOpFusionPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgElementwiseOpFusionPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 608 of file ElementwiseOpFusion.cpp.
createLinalgFoldIntoElementwisePass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgFoldIntoElementwisePass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 683 of file FoldIntoElementwise.cpp.
createLinalgFoldUnitExtentDimsPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgFoldUnitExtentDimsPass ()
Definition at line 772 of file DropUnitDims.cpp.
createLinalgFoldUnitExtentDimsPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgFoldUnitExtentDimsPass (LinalgFoldUnitExtentDimsPassOptions options)
Definition at line 776 of file DropUnitDims.cpp.
createLinalgGeneralizeNamedOpsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgGeneralizeNamedOpsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 855 of file Generalization.cpp.
createLinalgInlineScalarOperandsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgInlineScalarOperandsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 930 of file InlineScalarOperands.cpp.
createLinalgMorphOpsPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgMorphOpsPass ()
Definition at line 1026 of file MorphOps.cpp.
createLinalgMorphOpsPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgMorphOpsPass (LinalgMorphOpsPassOptions options)
Definition at line 1030 of file MorphOps.cpp.
createLinalgSpecializeGenericOpsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgSpecializeGenericOpsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1109 of file Specialize.cpp.
createLocationSnapshot() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLocationSnapshot ()
Definition at line 664 of file LocationSnapshot.cpp.
createLocationSnapshot() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createLocationSnapshot (LocationSnapshotOptions options)
Definition at line 668 of file LocationSnapshot.cpp.
createLowerAffinePass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLowerAffinePass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 5930 of file AffineToStandard.cpp.
createLowerHostCodeToLLVMPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createLowerHostCodeToLLVMPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6005 of file ConvertLaunchFuncToLLVMCalls.cpp.
createMem2Reg() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createMem2Reg ()
Definition at line 885 of file Mem2Reg.cpp.
createMem2Reg() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createMem2Reg (Mem2RegOptions options)
Definition at line 889 of file Mem2Reg.cpp.
createOptReductionPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createOptReductionPass ()
Definition at line 92 of file OptReductionPass.cpp.
createOptReductionPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createOptReductionPass (OptReductionPassOptions options)
Definition at line 96 of file OptReductionPass.cpp.
createOutlineShapeComputationPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createOutlineShapeComputationPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 75 of file OutlineShapeComputation.cpp.
createReconcileUnrealizedCastsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createReconcileUnrealizedCastsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6149 of file ReconcileUnrealizedCasts.cpp.
createReductionTreePass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createReductionTreePass ()
Definition at line 193 of file ReductionTreePass.cpp.
createReductionTreePass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createReductionTreePass (ReductionTreePassOptions options)
Definition at line 197 of file ReductionTreePass.cpp.
createRemoveShapeConstraintsPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createRemoveShapeConstraintsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 150 of file RemoveShapeConstraints.cpp.
createSCFToControlFlowPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createSCFToControlFlowPass ()
Definition at line 6236 of file SCFToControlFlow.cpp.
createSCFToControlFlowPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createSCFToControlFlowPass (SCFToControlFlowPassOptions options)
Definition at line 6240 of file SCFToControlFlow.cpp.
createSCFToEmitC()
std::unique_ptr<::mlir::Pass > mlir::impl::createSCFToEmitC ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6319 of file SCFToEmitC.cpp.
createSCFToSPIRV()
std::unique_ptr<::mlir::Pass > mlir::impl::createSCFToSPIRV ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6394 of file SCFToSPIRVPass.cpp.
createSetLLVMModuleDataLayoutPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createSetLLVMModuleDataLayoutPass ()
Definition at line 6481 of file FuncToLLVM.cpp.
createSetLLVMModuleDataLayoutPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createSetLLVMModuleDataLayoutPass (SetLLVMModuleDataLayoutPassOptions options)
Definition at line 6485 of file FuncToLLVM.cpp.
createShapeToShapeLoweringPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createShapeToShapeLoweringPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 225 of file ShapeToShapeLowering.cpp.
createSimplifyDepthwiseConvPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createSimplifyDepthwiseConvPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1185 of file SimplifyDepthwiseConv.cpp.
createSROA()
std::unique_ptr<::mlir::Pass > mlir::impl::createSROA ()
Definition at line 1233 of file SROA.cpp.
createTosaToArithPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createTosaToArithPass ()
Definition at line 6579 of file TosaToArithPass.cpp.
createTosaToArithPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createTosaToArithPass (TosaToArithPassOptions options)
Definition at line 6583 of file TosaToArithPass.cpp.
createTosaToMLProgram()
std::unique_ptr<::mlir::Pass > mlir::impl::createTosaToMLProgram ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6803 of file TosaToMLProgramPass.cpp.
createTosaToSCFPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createTosaToSCFPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6878 of file TosaToSCFPass.cpp.
createTosaToTensorPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createTosaToTensorPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 6953 of file TosaToTensorPass.cpp.
createUBToLLVMConversionPass() [1/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createUBToLLVMConversionPass ()
Definition at line 7040 of file UBToLLVM.cpp.
createUBToLLVMConversionPass() [2/2]
std::unique_ptr<::mlir::Pass > mlir::impl::createUBToLLVMConversionPass (UBToLLVMConversionPassOptions options)
Definition at line 7044 of file UBToLLVM.cpp.
createUBToSPIRVConversionPass()
std::unique_ptr<::mlir::Pass > mlir::impl::createUBToSPIRVConversionPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 7123 of file UBToSPIRV.cpp.
ensureRegionTerminator() [1/2]
void mlir::impl::ensureRegionTerminator (Region & region, Builder & builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Create a simple OpBuilder and forward to the OpBuilder version of this function.
Definition at line 1420 of file Operation.cpp.
References ensureRegionTerminator(), and mlir::Builder::getContext().
ensureRegionTerminator() [2/2]
void mlir::impl::ensureRegionTerminator (Region & region, OpBuilder & builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Insert an operation, generated by buildTerminatorOp, at the end of the region's only block if it does not have a terminator already.
If the region is empty, insert a new block first. buildTerminatorOp should return the terminator operation to insert.
Definition at line 1403 of file Operation.cpp.
References mlir::Block::back(), mlir::Region::back(), mlir::OpBuilder::createBlock(), mlir::Block::empty(), mlir::Region::empty(), mlir::Operation::hasTrait(), mlir::OpBuilder::insert(), and mlir::OpBuilder::setInsertionPointToEnd().
Referenced by ensureRegionTerminator(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ensureTerminator(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ensureTerminator().
findAttrSorted() [1/2]
template<typename IteratorT> std::pair< IteratorT, bool > mlir::impl::findAttrSorted (IteratorT first, IteratorT last, StringAttr name)
StringAttr lookups on large attribute lists will switch to string binary search.
String binary searches become significantly faster than linear scans with the identifier when the attribute list becomes very large.
Definition at line 763 of file OperationSupport.h.
References findAttrSorted(), and findAttrUnsorted().
findAttrSorted() [2/2]
template<typename IteratorT> std::pair< IteratorT, bool > mlir::impl::findAttrSorted (IteratorT first, IteratorT last, StringRef name)
Using llvm::lower_bound requires an extra string comparison to check whether the returned iterator points to the found element or whether it indicates the lower bound.
Skip this redundant comparison by checking if compare == / 0 during the binary search.
Definition at line 739 of file OperationSupport.h.
Referenced by findAttrSorted(), getAttrFromSortedRange(), and getNamedAttrFromSortedRange().
findAttrUnsorted()
template<typename IteratorT, typename NameT> std::pair< IteratorT, bool > mlir::impl::findAttrUnsorted (IteratorT first, IteratorT last, NameT name)
Unsorted string search or identifier lookups are linear scans.
Definition at line 726 of file OperationSupport.h.
Referenced by findAttrSorted().
foldCastInterfaceOp()
LogicalResult mlir::impl::foldCastInterfaceOp (Operation * op, ArrayRef< Attribute > attrOperands, SmallVectorImpl< OpFoldResult > & foldResults)
Attempt to fold the given cast operation.
Definition at line 22 of file CastInterfaces.cpp.
References foldCastInterfaceOp(), mlir::Operation::getOperands(), mlir::Operation::getResults(), mlir::OperandRange::getTypes(), mlir::ResultRange::getTypes(), and success().
Referenced by foldCastInterfaceOp().
getAttrFromSortedRange()
template<typename IteratorT, typename NameT> Attribute mlir::impl::getAttrFromSortedRange (IteratorT first, IteratorT last, NameT name)
Get an attribute from a sorted range of named attributes.
Returns null if the attribute was not found.
Definition at line 774 of file OperationSupport.h.
References findAttrSorted(), and result.
getDataLayoutSpec()
DataLayoutSpecInterface mlir::impl::getDataLayoutSpec (Operation * op)
Definition at line 26 of file Traits.cpp.
References mlir::Operation::getAttrOfType().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::getDataLayoutSpec().
getNamedAttrFromSortedRange()
template<typename IteratorT, typename NameT> std::optional< NamedAttribute > mlir::impl::getNamedAttrFromSortedRange (IteratorT first, IteratorT last, NameT name)
Get an attribute from a sorted range of named attributes.
Returns std::nullopt if the attribute was not found.
Definition at line 783 of file OperationSupport.h.
References findAttrSorted(), and result.
getTargetSystemSpec()
TargetSystemSpecInterface mlir::impl::getTargetSystemSpec (Operation * op)
Definition at line 31 of file Traits.cpp.
References mlir::Operation::getAttrOfType().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::getTargetSystemSpec().
parseOptionalVisibilityKeyword()
ParseResult mlir::impl::parseOptionalVisibilityKeyword (OpAsmParser & parser, NamedAttrList & attrs)
Parse an optional visibility attribute keyword (i.e., public, private, or nested) without quotes in a string attribute named 'attrName'.
Definition at line 1124 of file SymbolTable.cpp.
References mlir::AsmParser::getBuilder(), mlir::Builder::getNamedAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getVisibilityAttrName(), mlir::AsmParser::parseOptionalKeyword(), mlir::NamedAttrList::push_back(), and success().
Referenced by mlir::function_interface_impl::parseFunctionOp().
scalarizeVectorOp()
LogicalResult mlir::impl::scalarizeVectorOp (Operation * op, ValueRange operands, ConversionPatternRewriter & rewriter, const LLVMTypeConverter & converter)
Unrolls op to array/vector elements.
Definition at line 639 of file GPUOpsLowering.cpp.
References mlir::Operation::getResultTypes(), mlir::LLVM::detail::handleMultidimensionalVectors(), scalarizeVectorOpHelper(), and success().
Referenced by mlir::ScalarizeVectorOpLowering< SourceOp >::matchAndRewrite().
verifyCastInterfaceOp()
LogicalResult mlir::impl::verifyCastInterfaceOp (Operation * op)
Attempt to verify the given cast operation.
Definition at line 39 of file CastInterfaces.cpp.
References diag(), mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), success(), and verifyCastInterfaceOp().
Referenced by verifyCastInterfaceOp().
verifyHasDefaultDLTIDataLayoutTrait()
LogicalResult mlir::impl::verifyHasDefaultDLTIDataLayoutTrait (Operation * op)
Definition at line 15 of file Traits.cpp.
References success().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::verifyTrait().