MLIR: mlir::bufferization::func_ext Namespace Reference
mlir::bufferization::func_ext Namespace Reference
Classes
struct CallOpInterface
struct FuncAnalysisState
Extra analysis state that is required for bufferization of function boundaries.
struct FuncOpInterface
struct ReturnOpInterface
Enumerations
enum class FuncOpAnalysisState { NotAnalyzed , InProgress , Analyzed }
The state of analysis of a FuncOp.
Functions
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
static mlir::Attribute getDefaultMemorySpace (const BufferizationOptions &options, TensorLikeType type)
static BufferLikeType getBufferizedFunctionArgType (FuncOp funcOp, int64_t index, const BufferizationOptions &options)
Return the index-th bufferized function argument type.
static FuncOp getCalledFunction (CallOpInterface callOp, SymbolTableCollection &symbolTables)
Return the FuncOp called by callOp.
static FuncOp getCalledFunction (CallOpInterface callOp, const AnalysisState &state)
Return the FuncOp called by callOp.
static const FuncAnalysisState & getFuncAnalysisState (const AnalysisState &state)
Get FuncAnalysisState.
static FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState &state, FuncOp funcOp)
Return the state (phase) of analysis of the FuncOp.
static std::optional< int64_t > getEquivalentFuncArgIdx (FuncOp funcOp, const FuncAnalysisState &state, int64_t returnValIdx)
Return the index of the bbArg in the given FuncOp that is equivalent to the specified return value (if any).
Enumeration Type Documentation
FuncOpAnalysisState
enum class mlir::bufferization::func_ext::FuncOpAnalysisState strong
The state of analysis of a FuncOp.
Enumerator
NotAnalyzed
InProgress
Analyzed
Definition at line 30 of file FuncBufferizableOpInterfaceImpl.h.
Function Documentation
getBufferizedFunctionArgType()
BufferLikeType mlir::bufferization::func_ext::getBufferizedFunctionArgType (FuncOp funcOp, int64_t index, const BufferizationOptions & options) static
Return the index-th bufferized function argument type.
This assumes that the specified argument is a tensor. If the tensor is ranked, a layout map may be specified by the user (as per options.functionArgTypeConverterFn).
Definition at line 67 of file FuncBufferizableOpInterfaceImpl.cpp.
References options.
Referenced by mlir::bufferization::func_ext::FuncOpInterface::bufferize(), and mlir::bufferization::func_ext::FuncOpInterface::getBufferType().
getCalledFunction() [1/2]
FuncOp mlir::bufferization::func_ext::getCalledFunction (CallOpInterface callOp, const AnalysisState & state) static
Return the FuncOp called by callOp.
Definition at line 102 of file FuncBufferizableOpInterfaceImpl.cpp.
References getCalledFunction().
getCalledFunction() [2/2]
FuncOp mlir::bufferization::func_ext::getCalledFunction (CallOpInterface callOp, SymbolTableCollection & symbolTables) static
Return the FuncOp called by callOp.
Definition at line 96 of file FuncBufferizableOpInterfaceImpl.cpp.
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryWrite(), mlir::bufferization::func_ext::CallOpInterface::getAliasingValues(), mlir::bufferization::func_ext::CallOpInterface::getBufferType(), getCalledFunction(), and getFuncOpsOrderedByCalls().
getDefaultMemorySpace()
mlir::Attribute mlir::bufferization::func_ext::getDefaultMemorySpace (const BufferizationOptions & options, TensorLikeType type) static
Definition at line 55 of file FuncBufferizableOpInterfaceImpl.cpp.
References options.
Referenced by mlir::bufferization::func_ext::FuncOpInterface::bufferize(), and mlir::bufferization::func_ext::CallOpInterface::getBufferType().
getEquivalentFuncArgIdx()
std::optional< int64_t > mlir::bufferization::func_ext::getEquivalentFuncArgIdx (FuncOp funcOp, const FuncAnalysisState & state, int64_t returnValIdx) static
Return the index of the bbArg in the given FuncOp that is equivalent to the specified return value (if any).
Definition at line 145 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::equivalentFuncArgs.
Referenced by mlir::bufferization::func_ext::CallOpInterface::getAliasingValues().
getFuncAnalysisState()
const FuncAnalysisState & mlir::bufferization::func_ext::getFuncAnalysisState (const AnalysisState & state) static
Get FuncAnalysisState.
Definition at line 118 of file FuncBufferizableOpInterfaceImpl.cpp.
References result.
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryWrite(), and mlir::bufferization::func_ext::CallOpInterface::getAliasingValues().
getFuncOpAnalysisState()
FuncOpAnalysisState mlir::bufferization::func_ext::getFuncOpAnalysisState (const AnalysisState & state, FuncOp funcOp) static
Return the state (phase) of analysis of the FuncOp.
Definition at line 127 of file FuncBufferizableOpInterfaceImpl.cpp.
References NotAnalyzed.
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryWrite(), and mlir::bufferization::func_ext::CallOpInterface::getAliasingValues().
registerBufferizableOpInterfaceExternalModels()
void mlir::bufferization::func_ext::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 540 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects().