MLIR: mlir::ml_program Namespace Reference
mlir::ml_program Namespace Reference
Namespaces
namespace impl
Functions
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
std::unique_ptr<::mlir::Pass > createMLProgramPipelineGlobalsPass ()
void registerMLProgramPipelineGlobalsPass ()
void registerMLProgramPipelineGlobalsPassPass ()
void registerMLProgramPasses ()
Function Documentation
createMLProgramPipelineGlobalsPass()
std::unique_ptr<::mlir::Pass > mlir::ml_program::createMLProgramPipelineGlobalsPass ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 79 of file PipelineGlobalOps.cpp.
registerBufferizableOpInterfaceExternalModels()
void mlir::ml_program::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 160 of file BufferizableOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects().
registerMLProgramPasses()
void mlir::ml_program::registerMLProgramPasses () inline
Definition at line 115 of file Passes.h.
Referenced by mlir::registerAllPasses().
registerMLProgramPipelineGlobalsPass()
void mlir::ml_program::registerMLProgramPipelineGlobalsPass () inline
Definition at line 94 of file Passes.h.
registerMLProgramPipelineGlobalsPassPass()
void mlir::ml_program::registerMLProgramPipelineGlobalsPassPass () inline
Definition at line 101 of file Passes.h.