MLIR: mlir::vector::detail Namespace Reference
mlir::vector::detail Namespace Reference
Classes
struct BitmaskEnumStorage
Functions
VectorType transferMaskType (VectorType vecType, AffineMap map)
Given the vector type and the permutation map of a vector transfer op, compute the expected mask type.
Function Documentation
transferMaskType()
VectorType mlir::vector::detail::transferMaskType (VectorType vecType, AffineMap map)
Given the vector type and the permutation map of a vector transfer op, compute the expected mask type.
Definition at line 13 of file VectorInterfaces.cpp.
References mlir::AffineMap::getContext(), and mlir::AffineMap::getResult().
Referenced by parseTransferReadOp(), and verifyTransferOp().