MLIR: mlir::function_like_impl Namespace Reference
mlir::function_like_impl Namespace Reference
Namespaces
detail
Classes
class VariadicFlag
A named class for passing around the variadic flag.
Typedefs
using FuncTypeBuilder = function_ref< Type(Builder &, ArrayRef< Type >, ArrayRef< Type >, VariadicFlag, std::string &)>
Callback type for parseFunctionLikeOp, the callback should produce the type that will be associated with a function-like operation from lists of function arguments and results, VariadicFlag indicates whether the function should have variadic arguments; in case of error, it may populate the last argument with a message.
Functions
void addArgAndResultAttrs (Builder &builder, OperationState &result, ArrayRef< DictionaryAttr > argAttrs, ArrayRef< DictionaryAttr > resultAttrs)
Adds argument and result attributes, provided as argAttrs and resultAttrs arguments, to the list of operation attributes in result.
void addArgAndResultAttrs (Builder &builder, OperationState &result, ArrayRef< NamedAttrList > argAttrs, ArrayRef< NamedAttrList > resultAttrs)
ParseResult parseFunctionArgumentList (OpAsmParser &parser, bool allowAttributes, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< NamedAttrList > &argAttrs, bool &isVariadic)
Parses function arguments using parser.
ParseResult parseFunctionSignature (OpAsmParser &parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< NamedAttrList > &argAttrs, bool &isVariadic, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs)
Parses a function signature using parser.
ParseResult parseFunctionLikeOp (OpAsmParser &parser, OperationState &result, bool allowVariadic, FuncTypeBuilder funcTypeBuilder)
Parser implementation for function-like operations.
void printFunctionLikeOp (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Printer implementation for function-like operations.
void printFunctionSignature (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Prints the signature of the function-like operation op.
void printFunctionAttributes (OpAsmPrinter &p, Operation *op, unsigned numInputs, unsigned numResults, ArrayRef< StringRef > elided={})
Prints the list of function prefixed with the "attributes" keyword.
StringRef getTypeAttrName ()
Return the name of the attribute used for function types.
StringRef getArgDictAttrName ()
Return the name of the attribute used for function argument attributes.
StringRef getResultDictAttrName ()
Return the name of the attribute used for function argument attributes.
DictionaryAttr getArgAttrDict (Operation *op, unsigned index)
Returns the dictionary attribute corresponding to the argument at 'index'.
DictionaryAttr getResultAttrDict (Operation *op, unsigned index)
Returns the dictionary attribute corresponding to the result at 'index'.
void setAllArgAttrDicts (Operation *op, ArrayRef< DictionaryAttr > attrs)
Set all of the argument or result attribute dictionaries for a function.
void setAllArgAttrDicts (Operation *op, ArrayRef< Attribute > attrs)
void setAllResultAttrDicts (Operation *op, ArrayRef< DictionaryAttr > attrs)
void setAllResultAttrDicts (Operation *op, ArrayRef< Attribute > attrs)
ArrayRef< NamedAttribute > getArgAttrs (Operation *op, unsigned index)
Return all of the attributes for the argument at 'index'.
ArrayRef< NamedAttribute > getResultAttrs (Operation *op, unsigned index)
Return all of the attributes for the result at 'index'.
void insertFunctionArguments (Operation *op, ArrayRef< unsigned > argIndices, TypeRange argTypes, ArrayRef< DictionaryAttr > argAttrs, ArrayRef< Optional< Location >> argLocs, unsigned originalNumArgs, Type newType)
Insert the specified arguments and update the function type attribute.
void insertFunctionResults (Operation *op, ArrayRef< unsigned > resultIndices, TypeRange resultTypes, ArrayRef< DictionaryAttr > resultAttrs, unsigned originalNumResults, Type newType)
Insert the specified results and update the function type attribute.
void eraseFunctionArguments (Operation *op, ArrayRef< unsigned > argIndices, unsigned originalNumArgs, Type newType)
Erase the specified arguments and update the function type attribute.
void eraseFunctionResults (Operation *op, ArrayRef< unsigned > resultIndices, unsigned originalNumResults, Type newType)
Erase the specified results and update the function type attribute.
FunctionType getFunctionType (Operation *op)
Get and set a FunctionLike operation's type signature.
void setFunctionType (Operation *op, FunctionType newType)
Region & getFunctionBody (Operation *op)
Get a FunctionLike operation's body.
Typedef Documentation
FuncTypeBuilder
using mlir::function_like_impl::FuncTypeBuilder = typedef function_ref<Type(Builder &, ArrayRef<Type>, ArrayRef<Type>, VariadicFlag, std::string &)>
Callback type for parseFunctionLikeOp, the callback should produce the type that will be associated with a function-like operation from lists of function arguments and results, VariadicFlag indicates whether the function should have variadic arguments; in case of error, it may populate the last argument with a message.
Definition at line 53 of file FunctionImplementation.h.
Function Documentation
addArgAndResultAttrs() [1/2]
void mlir::function_like_impl::addArgAndResultAttrs (Builder & builder, OperationState & result, ArrayRef< DictionaryAttr > argAttrs, ArrayRef< DictionaryAttr > resultAttrs)
Adds argument and result attributes, provided as argAttrs and resultAttrs arguments, to the list of operation attributes in result.
Internally, argument and result attributes are stored as dict attributes with special names given by getResultAttrName, getArgumentAttrName.
Definition at line 171 of file FunctionImplementation.cpp.
References addArgAndResultAttrsImpl().
Referenced by mlir::function_like_impl::VariadicFlag::isVariadic(), parseFuncOp(), parseFunctionLikeOp(), parseGPUFuncOp(), parseLLVMFuncOp(), and parseShuffleVectorOp().
addArgAndResultAttrs() [2/2]
void mlir::function_like_impl::addArgAndResultAttrs (Builder & builder, OperationState & result, ArrayRef< NamedAttrList > argAttrs, ArrayRef< NamedAttrList > resultAttrs)
Definition at line 179 of file FunctionImplementation.cpp.
References addArgAndResultAttrsImpl(), mlir::Builder::getContext(), and mlir::NamedAttrList::getDictionary().
eraseFunctionArguments()
void mlir::function_like_impl::eraseFunctionArguments (Operation * op, ArrayRef< unsigned > argIndices, unsigned originalNumArgs, Type newType)
Erase the specified arguments and update the function type attribute.
Definition at line 213 of file FunctionSupport.cpp.
References mlir::Block::eraseArguments(), mlir::Region::front(), getArgDictAttrName(), mlir::Operation::getAttrOfType(), mlir::Operation::getRegion(), getTypeAttrName(), iterateIndicesExcept(), setAllArgAttrDicts(), and mlir::Operation::setAttr().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::eraseArguments(), and getResultAttrs().
eraseFunctionResults()
void mlir::function_like_impl::eraseFunctionResults (Operation * op, ArrayRef< unsigned > resultIndices, unsigned originalNumResults, Type newType)
Erase the specified results and update the function type attribute.
Definition at line 237 of file FunctionSupport.cpp.
References mlir::Operation::getAttrOfType(), getResultDictAttrName(), getTypeAttrName(), iterateIndicesExcept(), setAllResultAttrDicts(), and mlir::Operation::setAttr().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::eraseResults(), and getResultAttrs().
getArgAttrDict()
DictionaryAttr mlir::function_like_impl::getArgAttrDict (Operation * op, unsigned index)
Returns the dictionary attribute corresponding to the argument at 'index'.
If there are no argument attributes at 'index', a null attribute is returned.
Definition at line 38 of file FunctionSupport.cpp.
References getArgDictAttrName(), and mlir::Operation::getAttrOfType().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrDict(), getArgAttrs(), getResultDictAttrName(), mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr().
getArgAttrs()
ArrayRef<NamedAttribute> mlir::function_like_impl::getArgAttrs (Operation * op, unsigned index) inline
Return all of the attributes for the argument at 'index'.
Definition at line 60 of file FunctionSupport.h.
References getArgAttrDict().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrs().
getArgDictAttrName()
StringRef mlir::function_like_impl::getArgDictAttrName () inline
Return the name of the attribute used for function argument attributes.
Definition at line 29 of file FunctionSupport.h.
Referenced by addArgAndResultAttrsImpl(), eraseFunctionArguments(), filterFuncAttributes(), mlir::OpTrait::FunctionLike< ConcreteType >::getAllArgAttrs(), getArgAttrDict(), insertFunctionArguments(), printFunctionAttributes(), printFunctionSignature(), setAllArgAttrDicts(), mlir::OpTrait::FunctionLike< ConcreteType >::setAllArgAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs(), setFunctionType(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait(), and wrapExternalFunction().
getFunctionBody()
Region & mlir::function_like_impl::getFunctionBody (Operation * op)
Get a FunctionLike operation's body.
Definition at line 315 of file FunctionSupport.cpp.
References mlir::Operation::getRegion(), and mlir::Operation::hasTrait().
Referenced by mlir::TypeConverter::convertBlockSignature(), mlir::OpTrait::FunctionLike< ConcreteType >::getBody(), getResultAttrs(), and sourceMaterializationCallback().
getFunctionType()
FunctionType mlir::function_like_impl::getFunctionType (Operation * op)
Get and set a FunctionLike operation's type signature.
Definition at line 262 of file FunctionSupport.cpp.
References mlir::Operation::getAttrOfType(), getTypeAttrName(), and mlir::Operation::hasTrait().
Referenced by mlir::TypeConverter::convertBlockSignature(), getResultAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::getType(), and setFunctionType().
getResultAttrDict()
DictionaryAttr mlir::function_like_impl::getResultAttrDict (Operation * op, unsigned index)
Returns the dictionary attribute corresponding to the result at 'index'.
If there are no result attributes at 'index', a null attribute is returned.
Definition at line 46 of file FunctionSupport.cpp.
References mlir::Operation::getAttrOfType(), and getResultDictAttrName().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrDict(), getResultAttrs(), getResultDictAttrName(), mlir::OpTrait::FunctionLike< ConcreteType >::removeResultAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr().
getResultAttrs()
ArrayRef<NamedAttribute> mlir::function_like_impl::getResultAttrs (Operation * op, unsigned index) inline
Return all of the attributes for the result at 'index'.
Definition at line 66 of file FunctionSupport.h.
References eraseFunctionArguments(), eraseFunctionResults(), getFunctionBody(), getFunctionType(), getResultAttrDict(), insertFunctionArguments(), insertFunctionResults(), and setFunctionType().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrs().
getResultDictAttrName()
StringRef mlir::function_like_impl::getResultDictAttrName () inline
Return the name of the attribute used for function argument attributes.
Definition at line 32 of file FunctionSupport.h.
References getArgAttrDict(), getResultAttrDict(), and op.
Referenced by addArgAndResultAttrsImpl(), eraseFunctionResults(), mlir::OpTrait::FunctionLike< ConcreteType >::getAllResultAttrs(), getResultAttrDict(), insertFunctionResults(), printFunctionAttributes(), printFunctionSignature(), setAllResultAttrDicts(), mlir::OpTrait::FunctionLike< ConcreteType >::setAllResultAttrs(), setFunctionType(), mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait().
getTypeAttrName()
StringRef mlir::function_like_impl::getTypeAttrName () inline
Return the name of the attribute used for function types.
Definition at line 26 of file FunctionSupport.h.
Referenced by eraseFunctionArguments(), eraseFunctionResults(), filterFuncAttributes(), getFunctionType(), mlir::OpTrait::FunctionLike< ConcreteType >::getTypeAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::getTypeAttrName(), insertFunctionArguments(), insertFunctionResults(), lowerAsEntryFunction(), mlir::GPUFuncOpLowering::matchAndRewrite(), parseFuncOp(), parseFunctionLikeOp(), parseGPUFuncOp(), parseLLVMFuncOp(), print(), printFunctionAttributes(), printGPUFuncOp(), printLaunchFuncOperands(), printLLVMFuncOp(), setFunctionType(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), and mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait().
insertFunctionArguments()
void mlir::function_like_impl::insertFunctionArguments (Operation * op, ArrayRef< unsigned > argIndices, TypeRange argTypes, ArrayRef< DictionaryAttr > argAttrs, ArrayRef< Optional< Location >> argLocs, unsigned originalNumArgs, Type newType)
Insert the specified arguments and update the function type attribute.
Definition at line 124 of file FunctionSupport.cpp.
References mlir::Region::front(), getArgDictAttrName(), mlir::Operation::getAttrOfType(), mlir::Operation::getRegion(), getTypeAttrName(), mlir::Block::insertArgument(), setAllArgAttrDicts(), and mlir::Operation::setAttr().
Referenced by getResultAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::insertArguments().
insertFunctionResults()
void mlir::function_like_impl::insertFunctionResults (Operation * op, ArrayRef< unsigned > resultIndices, TypeRange resultTypes, ArrayRef< DictionaryAttr > resultAttrs, unsigned originalNumResults, Type newType)
Insert the specified results and update the function type attribute.
Definition at line 171 of file FunctionSupport.cpp.
References mlir::Operation::getAttrOfType(), getResultDictAttrName(), getTypeAttrName(), setAllResultAttrDicts(), and mlir::Operation::setAttr().
Referenced by getResultAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::insertResults().
parseFunctionArgumentList()
ParseResult mlir::function_like_impl::parseFunctionArgumentList (OpAsmParser & parser, bool allowAttributes, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< NamedAttrList > & argAttrs, bool & isVariadic)
Parses function arguments using parser.
The allowVariadic argument indicates whether functions with variadic arguments are supported. The trailing arguments are populated by this function with names, types and attributes of the arguments.
Definition at line 16 of file FunctionImplementation.cpp.
References mlir::OpAsmParser::emitError(), mlir::NamedAttrList::empty(), mlir::failed(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), loc, mlir::OpAsmParser::OperandType::name, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalEllipsis(), mlir::OpAsmParser::parseOptionalLocationSpecifier(), mlir::OpAsmParser::parseOptionalRegionArgument(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
Referenced by parseFunctionSignature(), and parseLaunchFuncOperands().
parseFunctionLikeOp()
ParseResult mlir::function_like_impl::parseFunctionLikeOp (OpAsmParser & parser, OperationState & result, bool allowVariadic, FuncTypeBuilder funcTypeBuilder)
Parser implementation for function-like operations.
Uses funcTypeBuilder to construct the custom function type given lists of input and output types. If allowVariadic is set, the parser will accept trailing ellipsis in the function signature and indicate to the builder whether the function is variadic. If the builder returns a null type, result will not contain the type attribute. The caller can then add a type, report the error or delegate the reporting to the op's verifier.
Uses funcTypeBuilder to construct the custom function type given lists of input and output types.
Definition at line 194 of file FunctionImplementation.cpp.
References addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::NamedAttrList::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::SymbolTable::getSymbolAttrName(), getTypeAttrName(), mlir::SymbolTable::getVisibilityAttrName(), mlir::OptionalParseResult::hasValue(), loc, parseFunctionSignature(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalRegion(), mlir::impl::parseOptionalVisibilityKeyword(), mlir::OpAsmParser::parseSymbolName(), and mlir::success().
Referenced by parseFuncOp().
parseFunctionSignature()
ParseResult mlir::function_like_impl::parseFunctionSignature (OpAsmParser & parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< NamedAttrList > & argAttrs, bool & isVariadic, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs)
Parses a function signature using parser.
The allowVariadic argument indicates whether functions with variadic arguments are supported. The trailing arguments are populated by this function with names, types and attributes of the arguments and those of the results.
Definition at line 135 of file FunctionImplementation.cpp.
References mlir::failure(), parseFunctionArgumentList(), parseFunctionResultList(), mlir::OpAsmParser::parseOptionalArrow(), mlir::succeeded(), and mlir::success().
Referenced by parseFuncOp(), parseFunctionLikeOp(), parseGPUFuncOp(), and parseLLVMFuncOp().
printFunctionAttributes()
void mlir::function_like_impl::printFunctionAttributes (OpAsmPrinter & p, Operation * op, unsigned numInputs, unsigned numResults, ArrayRef< StringRef > elided = {})
Prints the list of function prefixed with the "attributes" keyword.
The attributes with names listed in "elided" as well as those used by the function-like operation internally are not printed. Nothing is printed if all attributes are elided. Assumes op has the FunctionLike trait and passed the verification.
Definition at line 339 of file FunctionImplementation.cpp.
References getArgDictAttrName(), mlir::Operation::getAttrs(), getResultDictAttrName(), mlir::SymbolTable::getSymbolAttrName(), getTypeAttrName(), and mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword().
Referenced by print(), printFunctionLikeOp(), printGPUFuncOp(), and printLLVMFuncOp().
printFunctionLikeOp()
void mlir::function_like_impl::printFunctionLikeOp (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Printer implementation for function-like operations.
Accepts lists of argument and result types to use while printing.
Definition at line 353 of file FunctionImplementation.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getName(), mlir::Operation::getRegion(), mlir::SymbolTable::getSymbolAttrName(), mlir::SymbolTable::getVisibilityAttrName(), printFunctionAttributes(), printFunctionSignature(), mlir::OpAsmPrinter::printRegion(), and mlir::OpAsmPrinter::printSymbolName().
Referenced by print().
printFunctionSignature()
void mlir::function_like_impl::printFunctionSignature (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Prints the signature of the function-like operation op.
Print the signature of the function-like operation op.
Assumes op has the FunctionLike trait and passed the verification.
Definition at line 295 of file FunctionImplementation.cpp.
References mlir::Region::empty(), getArgDictAttrName(), mlir::Region::getArgument(), mlir::Operation::getAttrOfType(), mlir::Operation::getRegion(), getResultDictAttrName(), mlir::OpAsmPrinter::getStream(), printFunctionResultList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegionArgument(), and mlir::OpAsmPrinter::printType().
Referenced by print(), printFunctionLikeOp(), printGPUFuncOp(), and printLLVMFuncOp().
setAllArgAttrDicts() [1/2]
void mlir::function_like_impl::setAllArgAttrDicts (Operation * op, ArrayRef< DictionaryAttr > attrs)
Set all of the argument or result attribute dictionaries for a function.
The size of attrs is expected to match the number of arguments/results of the given op.
Definition at line 98 of file FunctionSupport.cpp.
Referenced by eraseFunctionArguments(), insertFunctionArguments(), mlir::OpTrait::FunctionLike< ConcreteType >::setAllArgAttrs(), and setFunctionType().
setAllArgAttrDicts() [2/2]
void mlir::function_like_impl::setAllArgAttrDicts (Operation * op, ArrayRef< Attribute > attrs)
Definition at line 102 of file FunctionSupport.cpp.
References getArgDictAttrName(), mlir::Operation::getContext(), and setAllArgResAttrDicts().
setAllResultAttrDicts() [1/2]
void mlir::function_like_impl::setAllResultAttrDicts (Operation * op, ArrayRef< DictionaryAttr > attrs)
Definition at line 111 of file FunctionSupport.cpp.
Referenced by eraseFunctionResults(), insertFunctionResults(), mlir::OpTrait::FunctionLike< ConcreteType >::setAllResultAttrs(), and setFunctionType().
setAllResultAttrDicts() [2/2]
void mlir::function_like_impl::setAllResultAttrDicts (Operation * op, ArrayRef< Attribute > attrs)
Definition at line 115 of file FunctionSupport.cpp.
References mlir::Operation::getContext(), getResultDictAttrName(), and setAllArgResAttrDicts().
setFunctionType()
void mlir::function_like_impl::setFunctionType (Operation * op, FunctionType newType)
Definition at line 269 of file FunctionSupport.cpp.
References getArgDictAttrName(), mlir::Operation::getAttrOfType(), getFunctionType(), getResultDictAttrName(), getTypeAttrName(), mlir::Operation::hasTrait(), op, mlir::Operation::removeAttr(), setAllArgAttrDicts(), setAllResultAttrDicts(), and mlir::Operation::setAttr().
Referenced by mlir::TypeConverter::convertBlockSignature(), getResultAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::setType().