MLIR: mlir::complex Namespace Reference
mlir::complex Namespace Reference
Functions
void convertDivToLLVMUsingAlgebraic (ConversionPatternRewriter &rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, LLVM::FastmathFlagsAttr fmf, Value *resultRe, Value *resultIm)
convert a complex division to the LLVM dialect using algebraic method
void convertDivToStandardUsingAlgebraic (ConversionPatternRewriter &rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, arith::FastMathFlagsAttr fmf, Value *resultRe, Value *resultIm)
convert a complex division to the arith/math dialects using algebraic method
void convertDivToLLVMUsingRangeReduction (ConversionPatternRewriter &rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, LLVM::FastmathFlagsAttr fmf, Value *resultRe, Value *resultIm)
convert a complex division to the LLVM dialect using Smith's method
void convertDivToStandardUsingRangeReduction (ConversionPatternRewriter &rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, arith::FastMathFlagsAttr fmf, Value *resultRe, Value *resultIm)
convert a complex division to the arith/math dialects using Smith's method
Function Documentation
convertDivToLLVMUsingAlgebraic()
void mlir::complex::convertDivToLLVMUsingAlgebraic (ConversionPatternRewriter & rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, LLVM::FastmathFlagsAttr fmf, Value * resultRe, Value * resultIm)
convert a complex division to the LLVM dialect using algebraic method
Definition at line 22 of file DivisionConverter.cpp.
convertDivToLLVMUsingRangeReduction()
void mlir::complex::convertDivToLLVMUsingRangeReduction (ConversionPatternRewriter & rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, LLVM::FastmathFlagsAttr fmf, Value * resultRe, Value * resultIm)
convert a complex division to the LLVM dialect using Smith's method
Definition at line 92 of file DivisionConverter.cpp.
References mlir::Builder::getFloatAttr(), mlir::Value::getType(), and mlir::Builder::getZeroAttr().
convertDivToStandardUsingAlgebraic()
void mlir::complex::convertDivToStandardUsingAlgebraic (ConversionPatternRewriter & rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, arith::FastMathFlagsAttr fmf, Value * resultRe, Value * resultIm)
convert a complex division to the arith/math dialects using algebraic method
Definition at line 44 of file DivisionConverter.cpp.
convertDivToStandardUsingRangeReduction()
void mlir::complex::convertDivToStandardUsingRangeReduction (ConversionPatternRewriter & rewriter, Location loc, Value lhsRe, Value lhsIm, Value rhsRe, Value rhsIm, arith::FastMathFlagsAttr fmf, Value * resultRe, Value * resultIm)
convert a complex division to the arith/math dialects using Smith's method
Definition at line 280 of file DivisionConverter.cpp.
References mlir::Builder::getFloatAttr(), mlir::Value::getType(), and mlir::Builder::getZeroAttr().