MLIR: mlir::mpi Namespace Reference
mlir::mpi Namespace Reference
Functions
void populateMPIToLLVMConversionPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns)
void registerConvertMPIToLLVMInterface (DialectRegistry &registry)
template<typename OpT>
LogicalResult FoldToDLTIConst (OpT op, const char *key, mlir::PatternRewriter &b)
Function Documentation
FoldToDLTIConst()
template<typename OpT> LogicalResult mlir::mpi::FoldToDLTIConst (OpT op, const char * key, mlir::PatternRewriter & b)
Definition at line 19 of file Utils.h.
References b, and mlir::dlti::query().
populateMPIToLLVMConversionPatterns()
void mlir::mpi::populateMPIToLLVMConversionPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns)
Definition at line 1011 of file MPIToLLVM.cpp.
References mlir::RewritePatternSet::add().
registerConvertMPIToLLVMInterface()
void mlir::mpi::registerConvertMPIToLLVMInterface (DialectRegistry & registry)
Definition at line 1025 of file MPIToLLVM.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllExtensions().