MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Namespaces
namespace detail
Classes
class BatchMatmulTransposeAOp
Specialization of linalg.batch_matmul op that has a transpose map on A.
class BatchMatmulTransposeBOp
Specialization of linalg.batch_matmul op that has a transpose map on B.
struct BlockPackMatmulOptions
struct BufferizeToAllocationOptions
struct CollapseResult
struct ContinuousTileSizeSpecification
struct ContractionDimensions
Positions of a Linalg op loops that correspond to different kinds of a contraction dimension.
struct ControlDropUnitDims
Transformation to drop unit-extent dimensions from linalg.generic operations.
class ConvMatcherBuilder
Helper class for building convolution op matchers with minimal boilerplate.
struct ConvolutionDimensions
Positions of a Linalg op loops that correspond to different kinds of a convolution dimension.
struct CopyVectorizationPattern
Vectorization pattern for memref::CopyOp.
struct DecomposeOuterUnitDimsPackOpPattern
Rewrites a linalg::PackOp into a sequence of:
struct DecomposeOuterUnitDimsUnPackOpPattern
Rewrites a linalg::UnPackOp into a sequence of:
struct DecomposePadOpPattern
Rewrite a tensor::PadOp into a sequence of EmptyOp, FillOp and InsertSliceOp.
struct DilationsAndStrides
A struct containing dilations and strides inferred from convolution ops.
struct DropUnitDimsResult
struct ElementwiseOpFusionResult
Fuse two linalg.generic operations that have a producer-consumer relationship captured through fusedOperand.
struct ExtractSliceOfPadTensorSwapPattern
Rewrite extract_slice(tensor.pad(x)) into tensor.pad(extract_slice(x)).
struct FoldTensorCastPackOp
Folds a tensor.cast op into a consuming PackOp op if the tensor.cast has source that is more static than the consuming op.
struct FoldTensorCastUnPackOp
Folds a tensor.cast op into a consuming UnPackOp op if the tensor.cast has source that is more static than the consuming op.
struct ForallReductionTilingResult
Transformation information returned after reduction tiling.
struct FusionInfo
A struct containing the Linalg producer before and after fusion.
struct GenerateLoopNest
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
struct GenericOpSpecializationOptions
struct Im2ColToInputDimsExprs
struct Im2ColToOperandsExprs
struct LinalgCopyVTRForwardingPattern
Match and rewrite for the pattern:
struct LinalgCopyVTWForwardingPattern
Match and rewrite for the pattern:
struct LinalgGeneralizationPattern
Linalg generalization pattern.
struct LinalgLoopDistributionOptions
Options that allow distribution of loops generated in Linalg transforms to processors while generating the loops.
class LinalgOpToLibraryCallRewrite
struct LinalgPaddingOptions
struct LinalgPromotionOptions
struct LinalgSpecializationPattern
struct LinalgTilingAndFusionOptions
struct LinalgTilingOptions
struct LowerPackResult
struct LowerUnPackOpResult
class MatmulTransposeAOp
Specialization of linalg.matmul op that has a transpose map on A.
class MatmulTransposeBOp
Specialization of linalg.matmul op that has a transpose map on B.
struct MultiSizeSpecification
A description of a multi-size tiling comprising tile sizes and numbers of tiles, expressed as Values which may or may not be constant.
struct PackResult
Struct to hold the result of a pack call.
struct PackTransposeResult
Struct to hold the result of a packTranspose call.
struct PadTilingInterfaceOptions
struct PadTilingInterfaceResult
Operations and values created in the process of padding a TilingInterface operation.
struct ProcInfo
Callback function type used to get processor ID, and number of processors used for distribution for all parallel loops generated.
struct PromotionInfo
Create a new buffer using the allocationFn provided.
struct RegionMatcher
A struct containing common matchers over linalg op's region.
struct SliceParameters
A struct containg offsets-sizes-strides arguments of the tiled shape.
struct SplitReductionOptions
Split Reduction options.
struct SplitReductionResult
Apply transformation to split the single linalg op reduction into a parallel and reduction dimension.
struct StaticContinuousTileSizeSpecification
struct StaticMultiSizeSpecification
struct TiledLinalgOp
Perform standalone tiling of a single LinalgOp by tileSizes.
struct VectorizationResult
Transformation information returned after vectorizing.
Typedefs
using TileSizeComputationFunction
using AllocBufferCallbackFn
Callback function type used to perform the allocation for the promoted subView.
using DeallocBufferCallbackFn
Callback function type used to deallocate the buffers used to hold the promoted subview.
using CopyCallbackFn
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
using ControlSplitReductionFn
Function signature to control reduction splitting.
using LinalgLoops = SmallVector<Operation *, 4>
using DroppedUnitDimsBuilder
using PadSizeComputationFunction
using LoopIndexToRangeIndexMap = DenseMap<int, int>
Creates a number of ranges equal to the number of non-zero in tileSizes.
using ControlBlockPackMatmulFn
Function type which is used to control matmul packing.
using OptimizeCopyFn
using ControlFusionFn = std::function<bool(OpOperand *fusedOperand)>
Function type which is used to control when to stop fusion.
using ControlPropagationFn = std::function<bool(OpOperand *opOperand)>
Function type which is used to control propagation of linalg.pack/unpack ops.
using GetCollapsableDimensionsFn
Function type to control generic op dimension collapsing.
using ControlFoldIntoPackUnpackFn = std::function<bool(OpOperand *opOperand)>
Function type which is used to control folding operations like tensor.pad and tensor.extract_slice into linalg.pack/unpack ops.
using ProcInfoCallBackFn
using GridAxis = shard::GridAxis
using ReductionKind = shard::ReductionKind
using Sharding = shard::Sharding
using ShardingArray = shard::ShardingArray
using GridOp = shard::GridOp
Enumerations
enum class LinalgTilingLoopType { Loops = 0 , AffineLoops = 1 , ParallelLoops = 2 }
The type of loops to be generated during tiling.
enum class DistributionMethod { Cyclic = 0 , CyclicNumProcsGeNumIters = 1 , CyclicNumProcsEqNumIters = 2 , None = 3 }
Scheme used to distribute loops to processors.
enum class PoolingType {
None , MaxSigned , MaxUnsigned , MinSigned ,
MinUnsigned , Sum
}
Enum representing pooling operation types used by ConvMatcherBuilder.
Functions
void populateLinalgToStandardConversionPatterns (RewritePatternSet &patterns)
Populate the given list with patterns that convert from Linalg to Standard.
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &startIdx, MLIRContext *context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
AffineMap extractOrIdentityMap (std::optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Value createOrFoldDimOp (OpBuilder &b, Location loc, Value val, int64_t dim)
Create one memref::DimOp or tensor::DimOp depending on the type of val.
OpFoldResult createFoldedDimOp (OpBuilder &b, Location loc, Value val, int64_t dim)
Create one memref::DimOp or tensor::DimOp depending on the type of val.
std::optional< WinogradConv2DFmr > getWinogradConv2DFmr (int64_t m, int64_t r)
Converts the given m and r parameters to a WinogradConv2DFmr enumeration value.
std::pair< int64_t, int64_t > getFmrFromWinogradConv2DFmr (WinogradConv2DFmr fmr)
Converts the given WinogradConv2DFmr enumeration value to a pair of m and r parameters.
template<typename OpTy, typename = std::enable_if_t<std::is_same_v<OpTy, linalg::PackOp> || std::is_same_v<OpTy, linalg::UnPackOp>>>
SmallVector< int64_t > getPackedOuterShapeWithoutTransposition (OpTy packOrUnPack)
Returns the outer shape in the packed domain before applying the transposition.
FailureOr< ContractionDimensions > inferContractionDims (LinalgOp linalgOp)
Find at least 2 parallel (m and n) and 1 reduction (k) dimension candidates that form a matmul subcomputation within linalgOp.
FailureOr< ContractionDimensions > inferContractionDims (ArrayRef< AffineMap > indexingMaps)
bool isaContractionOpInterface (LinalgOp linalgOp)
Checks whether linalgOp conforms to ContractionOpInterface.
FailureOr< ConvolutionDimensions > inferConvolutionDims (LinalgOp linalgOp)
Find at least 1 parallel (output_image) and reduction (filter_loop) dimension candidates that form a convolution subcomputation within linalgOp.
FailureOr< ConvolutionDimensions > inferConvolutionDims (ArrayRef< AffineMap > indexingMaps)
Maps-based overload of inferConvolutionDims.
bool isaConvolutionOpInterface (LinalgOp linalgOp, bool allowEmptyConvolvedDims=false)
Checks whether linalgOp conforms to ConvolutionOpInterface.
bool isaCopyOpInterface (LinalgOp linalgOp)
Checks whether linalgOp is semantically equivalent to a linalg.copyOp.
std::optional< SmallVector< int64_t > > isaBroadcastOpInterface (LinalgOp linalgOp)
Checks whether linalgOp is semantically equivalent to a broadcast operation.
std::optional< SmallVector< int64_t > > isaTransposeOpInterface (GenericOp genericOp)
Checks whether genericOp is semantically equivalent to a linalg.transpose.
bool isaElemwiseSingleUnaryOpInterface (GenericOp genericOp, bool allowNonIdentityMaps=false)
Checks whether a given genericOp is semantically equivalent to a single linalg elementwise unary op, e.g.
bool isaElemwiseSingleBinaryOpInterface (GenericOp genericOp, bool allowNonIdentityMaps=false)
Checks whether genericOp is semantically equivalent to a single linalg elementwise binary op e.g.
std::optional< Value > isaFillOpInterface (GenericOp genericOp)
Checks whether genericOp is semantically equivalent to a linalg.fill.
void registerValueBoundsOpInterfaceExternalModels (DialectRegistry &registry)
void registerTransformDialectExtension (DialectRegistry &registry)
void registerAllDialectInterfaceImplementations (DialectRegistry &registry)
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
void hoistRedundantVectorTransfers (Operation *root, bool verifyNonZeroTrip=false)
Hoist vector.transfer_read/vector.transfer_write on buffers pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
void hoistRedundantVectorBroadcasts (RewriterBase &rewriter, Operation *root)
Hoist vector.extract/vector.broadcast pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are met:
void registerRuntimeVerifiableOpInterfaceExternalModels (DialectRegistry &registry)
void registerShardingInterfaceExternalModels (DialectRegistry &registry)
void registerSubsetOpInterfaceExternalModels (DialectRegistry &registry)
void registerTilingInterfaceExternalModels (DialectRegistry &registry)
void registerTilingInterfaceExternalModelsForPackUnPackOps (DialectRegistry &registry)
Similar to the above registeration, but it is only for tensor.pack and tensor.unpack ops.
std::optional< vector::CombiningKind > getCombinerOpKind (Operation *combinerOp)
Return vector::CombiningKind for the given op.
Value bufferizeToAllocation (RewriterBase &rewriter, const BufferizeToAllocationOptions &options, tensor::PadOp padOp, Attribute memorySpace={}, Operation *insertionPoint=nullptr)
Materialize a buffer allocation for the given tensor.pad op and lower the op to linalg.fill/linalg.generic + bufferization.materialize_in_destination.
Value bufferizeToAllocation (RewriterBase &rewriter, const BufferizeToAllocationOptions &options, vector::MaskOp maskOp, Attribute memorySpace={}, Operation *insertionPoint=nullptr)
Materialize a buffer allocation for the given vector.mask op and bufferize the op, including its region.
Value bufferizeToAllocation (RewriterBase &rewriter, const BufferizeToAllocationOptions &options, bufferization::AllocTensorOp allocTensorOp, Attribute memorySpace={}, Operation *insertionPoint=nullptr)
Materialize a buffer allocation for the given bufferization.alloc_tensor op and lower the op to memref.alloc + memref.tensor_store.
Value bufferizeToAllocation (RewriterBase &rewriter, const BufferizeToAllocationOptions &options, Operation *op, Attribute memorySpace={}, Operation *insertionPoint=nullptr)
Bufferize the given op with tensor semantics and materialize the result in a newly allocated buffer.
LogicalResult linalgOpAnchoredEmptyTensorEliminationStep (RewriterBase &rewriter, Operation *op, bufferization::OneShotAnalysisState &state)
Try to eliminate tensor::EmptyOps inside op that are anchored on a LinalgOp.
bool areElementwiseOpsFusable (OpOperand *fusedOperand)
Return true if two linalg.generic operations with producer/consumer relationship through fusedOperand can be fused using elementwise op fusion.
LogicalResult promoteSubviewsPrecondition (Operation *op, LinalgPromotionOptions options)
Promote memref.subviews feeding linalg-on-buffers operations.
LogicalResult vectorizeOpPrecondition (Operation *op, ArrayRef< int64_t > inputVectorSizes={}, ArrayRef< bool > inputScalableVecDims={}, bool vectorizeNDExtract=false, bool flatten1DDepthwiseConv=false)
Return success if the operation can be vectorized.
FailureOr< DropUnitDimsResult > dropUnitDims (RewriterBase &rewriter, IndexingMapOpInterface op, const DroppedUnitDimsBuilder &droppedUnitDimsBuilder, const ControlDropUnitDims &options)
Drop unit extent dimensions from the op and its operands.
FailureOr< DropUnitDimsResult > dropUnitDims (RewriterBase &rewriter, GenericOp genericOp, const ControlDropUnitDims &options)
Drop unit extent dimensions from the genericOp and its operands.
FailureOr< ElementwiseOpFusionResult > fuseElementwiseOps (RewriterBase &rewriter, OpOperand *fusedOperand)
This transformation is intended to be used with a top-down traversal (from producer to consumer).
llvm::SmallDenseSet< int > getPreservedProducerResults (GenericOp producer, GenericOp consumer, OpOperand *fusedOperand)
Returns a set of indices of the producer's results which would be preserved after the fusion.
SmallVector< Value > peelLoop (RewriterBase &rewriter, Operation *op)
Try to peel and canonicalize loop op and return the new result.
void peelLoops (RewriterBase &rewriter, ArrayRef< scf::ForOp > loops)
Peel 'loops' and applies affine_min/max bounds simplification on the fly where relevant.
LogicalResult rewriteAsPaddedOp (RewriterBase &rewriter, LinalgOp opToPad, const LinalgPaddingOptions &options, LinalgOp &paddedOp, SmallVector< Value > &replacements, SmallVector< tensor::PadOp > &padOps)
Pad the iterator dimensions options.paddingDimensions of all opToPad operands to a static bounding box.
SmallVector< OpFoldResult > computePaddedShape (OpBuilder &, TypedValue< RankedTensorType > v, AffineMap indexingMap, ArrayRef< OpFoldResult > indexingSizes, const PadTilingInterfaceOptions &options)
Helper function to compute the padded shape of the given value v of RankedTensorType given:
FailureOr< SmallVector< OpFoldResult > > computeIndexingMapOpInterfacePaddedShape (OpBuilder &, OpOperand &operandToPad, ArrayRef< Range > iterationDomain, const PadTilingInterfaceOptions &)
Specific helper for Linalg ops.
FailureOr< PadTilingInterfaceResult > rewriteAsPaddedOp (OpBuilder &, TilingInterface toPad, PadTilingInterfaceOptions options, const PadSizeComputationFunction &=&computeIndexingMapOpInterfacePaddedShape)
Pad the iterator dimensions of toPad.
FailureOr< Value > hoistPaddingOnTensors (RewriterBase &rewriter, tensor::PadOp opToHoist, int64_t numLoops, ArrayRef< int64_t > transposeVector, tensor::PadOp &hoistedOp, SmallVectorImpl< TransposeOp > &transposeOps)
Mechanically hoist padding operations on tensors by numLoops into a new, generally larger tensor.
FailureOr< Value > hoistPaddingOnTensors (tensor::PadOp opToHoist, int64_t numLoops, ArrayRef< int64_t > transposeVector, tensor::PadOp &hoistedOp, SmallVectorImpl< TransposeOp > &transposeOps)
Calls into hoistPaddingOnTensors with a local IRRewriter.
FailureOr< LinalgOp > padAndHoistLinalgOp (RewriterBase &rewriter, LinalgOp linalgOp, const LinalgPaddingOptions &options)
Apply padding and hoisting to linalgOp according to the configuration specified in options.
std::pair< TilingInterface, TilingInterface > splitOp (RewriterBase &rewriter, TilingInterface op, unsigned dimension, OpFoldResult splitPoint)
Split the given op into two parts along the given iteration space dimension at the specified splitPoint, and return the two parts.
FailureOr< TiledLinalgOp > tileLinalgOp (RewriterBase &b, LinalgOp op, const LinalgTilingOptions &options)
FailureOr< GenericOp > interchangeGenericOp (RewriterBase &rewriter, GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Interchange the iterator_types and iterator_maps dimensions and adapts the index accesses of op.
FailureOr< GenericOp > generalizeNamedOp (RewriterBase &rewriter, LinalgOp linalgOp)
Create a GenericOp from the given named operation linalgOp and replace the given linalgOp.
FailureOr< LinalgOp > specializeGenericOp (RewriterBase &rewriter, GenericOp genericOp, const GenericOpSpecializationOptions &options={})
Replace the given GenericOp with a namedOp or categoryOp.
FailureOr< PromotionInfo > promoteSubviewAsNewBuffer (OpBuilder &b, Location loc, memref::SubViewOp subView, bool useOriginalSubviewSize, const AllocBufferCallbackFn &allocationFn, DataLayout &layout)
FailureOr< LinalgOp > promoteSubViews (OpBuilder &b, LinalgOp op, const LinalgPromotionOptions &options)
Promote the subViews into a new buffer allocated at the insertion point b.
std::optional< Value > allocateWorkgroupMemory (OpBuilder &builder, memref::SubViewOp subview, ArrayRef< Value > sizeBounds, DataLayout &)
Allocate the subview in the GPU workgroup memory.
LogicalResult deallocateWorkgroupMemory (OpBuilder &, Value)
In case of GPU group memory there is no need to deallocate.
LogicalResult copyToWorkgroupMemory (OpBuilder &b, Value src, Value dst)
Create Memref copy operations and add gpu barrier guards before and after the copy operation to ensure data integrity.
std::optional< Value > allocateGPUPrivateMemory (OpBuilder &builder, memref::SubViewOp subview, ArrayRef< Value > sizeBounds, DataLayout &)
Allocate the subview in the GPU private memory.
LogicalResult copyToGPUPrivateMemory (OpBuilder &b, Value src, Value dst)
Normal copy to between src and dst.
LogicalResult deallocateGPUPrivateMemory (OpBuilder &, Value)
In case of GPU private memory there is no need to deallocate since the memory is freed when going outside of the scope.
bool hasVectorizationImpl (Operation *)
Return true if there's dedicated logic in the Linalg Vectorizer to vectorize this Op, false otherwise.
FailureOr< VectorizationResult > vectorize (RewriterBase &rewriter, Operation *op, ArrayRef< int64_t > inputVectorSizes={}, ArrayRef< bool > inputScalableVecDims={}, bool vectorizeNDExtract=false, bool flatten1DDepthwiseConv=false, bool assumeDynamicDimsMatchVecSizes=false, bool createNamedContraction=false)
Returns a VectorizationResult containing the results of the vectorized op, or failure if the transformation fails.
LogicalResult vectorizeCopy (RewriterBase &builder, memref::CopyOp copyOp)
Emit a suitable vector form for a Copy op with fully static shape.
FailureOr< LinalgLoops > linalgOpToLoops (RewriterBase &rewriter, LinalgOp linalgOp)
Emit a loop nest of scf.for with the proper body for linalgOp.
FailureOr< LinalgLoops > linalgOpToParallelLoops (RewriterBase &rewriter, LinalgOp linalgOp)
Emit a loop nest of scf.parallel with the proper body for linalgOp.
FailureOr< LinalgLoops > linalgOpToAffineLoops (RewriterBase &rewriter, LinalgOp linalgOp)
Emit a loop nest of affine.for with the proper body for linalgOp.
std::tuple< SmallVector< Range, 4 >, LoopIndexToRangeIndexMap > makeTiledLoopRanges (RewriterBase &b, Location loc, AffineMap map, ArrayRef< OpFoldResult > allShapeSizes, ArrayRef< OpFoldResult > allTileSizes)
FailureOr< MultiSizeSpecification > computeMultiTileSizes (OpBuilder &builder, LinalgOp op, unsigned dimension, OpFoldResult targetSize, OpFoldResult divisor, bool emitAssertions=true)
Emits the IR computing the multi-sized tiling specification with two tile sizes not exceeding targetSize, each divisible by sizeDivisor, such that there exist numbers of tiles with these sizes that fully cover the given iteration space dimension of the structured op.
FailureOr< StaticMultiSizeSpecification > computeStaticMultiTileSizes (LinalgOp op, unsigned dimension, int64_t targetSize, int64_t divisor)
FailureOr< StaticContinuousTileSizeSpecification > computeStaticContinuousTileSizes (LinalgOp op, unsigned dimension, unsigned targetSize)
FailureOr< ContinuousTileSizeSpecification > computeContinuousTileSizes (OpBuilder &builder, TilingInterface op, unsigned dimension, OpFoldResult targetSize, bool emitAssertions)
FailureOr< ForallReductionTilingResult > tileReductionUsingForall (RewriterBase &b, PartialReductionOpInterface op, ArrayRef< OpFoldResult > numThreads, ArrayRef< OpFoldResult > tileSizes={}, std::optional< ArrayAttr > mapping=std::nullopt)
Method to tile a reduction to parallel iterations computing partial reductions.
void transformIndexOps (RewriterBase &b, LinalgOp op, SmallVectorImpl< Value > &ivs, const LoopIndexToRangeIndexMap &loopIndexToRangeIndex)
All indices returned by IndexOp should be invariant with respect to tiling.
FailureOr< SplitReductionResult > splitReduction (RewriterBase &b, LinalgOp op, const ControlSplitReductionFn &controlSplitReductionFn, bool useAlloc=false)
FailureOr< SplitReductionResult > splitReductionByScaling (RewriterBase &b, LinalgOp op, const ControlSplitReductionFn &controlSplitReductionFn, bool useAlloc=false)
Scaling-based implementation of the split reduction transformation.
bool isDimSequencePreserved (AffineMap map, ReassociationIndicesRef dimSequence)
Return true if a given sequence of dimensions are contiguous in the range of the specified indexing map.
bool areDimSequencesPreserved (ArrayRef< AffineMap > maps, ArrayRef< ReassociationIndices > dimSequences)
Return true if all sequences of dimensions specified in dimSequences are contiguous in all the ranges of the maps.
FailureOr< CollapseResult > collapseOpIterationDims (LinalgOp op, ArrayRef< ReassociationIndices > foldedIterationDims, RewriterBase &rewriter)
Collapses dimensions of linalg.generic/linalg.copy operation.
FailureOr< LowerPackResult > lowerPack (RewriterBase &rewriter, linalg::PackOp packOp, bool lowerPadLikeWithInsertSlice=true)
Rewrite pack as pad + reshape + transpose.
FailureOr< LowerUnPackOpResult > lowerUnPack (RewriterBase &rewriter, linalg::UnPackOp unPackOp, bool lowerUnpadLikeWithExtractSlice=true)
Rewrite pack as empty + transpose + reshape + extract_slice + copy.
FailureOr< PackResult > pack (RewriterBase &rewriter, linalg::LinalgOp linalgOp, ArrayRef< OpFoldResult > packedSizes)
Implement packing of a single LinalgOp by packedSizes.
FailureOr< PackTransposeResult > packTranspose (RewriterBase &rewriter, linalg::PackOp packOp, linalg::LinalgOp linalgOp, linalg::UnPackOp maybeUnPackOp, ArrayRef< int64_t > outerPerm, ArrayRef< int64_t > innerPerm)
Transpose a single PackOp -> LinalgOp -> UnPackOp chain and return the transposed PackOp -> LinalgOp -> UnPackOp chain after replacements.
FailureOr< PackResult > packMatmulGreedily (RewriterBase &rewriter, LinalgOp linalgOp, ArrayRef< OpFoldResult > mnkPackedSizes, ArrayRef< int64_t > mnkPaddedSizesNextMultipleOf, ArrayRef< int64_t > mnkOrder)
Pack a LinalgOp by greedily inferring matmul dimensions (m, n, k) where m and n are proper parallel dimensions and k is a proper reduction dimension.
FailureOr< PackResult > blockPackMatmul (RewriterBase &rewriter, linalg::LinalgOp linalgOp, const ControlBlockPackMatmulFn &controlPackMatmul)
Pack a matmul operation into blocked 4D layout.
FailureOr< Operation * > rewriteInDestinationPassingStyle (RewriterBase &rewriter, tensor::FromElementsOp fromElementsOp)
Rewrite tensor.from_elements to linalg.generic.
FailureOr< Operation * > rewriteInDestinationPassingStyle (RewriterBase &rewriter, tensor::GenerateOp generateOp)
Rewrite tensor.generate to linalg.generic.
FailureOr< Operation * > rewriteInDestinationPassingStyle (RewriterBase &rewriter, tensor::PadOp padOp)
Rewrite tensor.pad to linalg.generic + tensor.insert_slice.
FailureOr< std::pair< Operation *, Operation * > > rewriteInIm2Col (RewriterBase &rewriter, linalg::Conv2DNhwcHwcfOp convOp)
Convert linalg.conv_2d_nhwc_hwcf into linalg.generic (for img2col packing) and linalg.matmul.
FailureOr< std::pair< Operation *, Operation * > > rewriteInIm2Col (RewriterBase &rewriter, linalg::Conv2DNhwcFhwcOp convOp)
Same as the above but for Fhwc channel orderings in the filter.
FailureOr< std::pair< Operation *, Operation * > > rewriteInIm2Col (RewriterBase &rewriter, linalg::DepthwiseConv2DNhwcHwcOp convOp)
Similar to rewriteInIm2Col with linalg::Conv2DNhwcHwcfOp except there is no reduction among the input channels so each convolution can be a matrix-vector product and by transposing both input filter so channels are outer most the computation is a batched matrix-vector product.
FailureOr< std::pair< Operation *, Operation * > > rewriteInIm2Col (RewriterBase &rewriter, linalg::Conv2DNchwFchwOp convOp)
Similar to rewriteInIm2Col with linalg::Conv2DNhwcHwcfOp except because the channels are to the left of the image shape dimensions, the position of the contraction dimension in the resulting matmul is reversed.
FailureOr< Operation * > transposeConv2D (RewriterBase &rewriter, linalg::Conv2DNhwcFhwcOp op)
Convert linalg.conv_2d_nhwc_fhwc(_q) to linalg.conv_2d_nhwc_hwcf(_q) by materializing transpose.
FailureOr< Operation * > transposeConv2D (RewriterBase &rewriter, linalg::Conv2DNhwcFhwcQOp op)
FailureOr< Operation * > transposeMatmul (RewriterBase &rewriter, linalg::MatmulOp op, bool transposeLHS=true)
Convert Linalg matmul ops to transposed variants.
FailureOr< Operation * > transposeBatchMatmul (RewriterBase &rewriter, linalg::BatchMatmulOp op, bool transposeLHS=true)
Pattern to replace.
FailureOr< Operation * > winogradConv2D (RewriterBase &rewriter, linalg::Conv2DNhwcFhwcOp op, WinogradConv2DFmr fmr)
Convert linalg.conv_2d_nhwc_fhwc to Winograd Conv2D algorithm F(m x m, r x r).
FailureOr< Operation * > decomposeWinogradFilterTransformOp (RewriterBase &rewriter, linalg::WinogradFilterTransformOp op)
Rewrite linalg.winograd_filter_transform.
FailureOr< Operation * > decomposeWinogradInputTransformOp (RewriterBase &rewriter, linalg::WinogradInputTransformOp op)
Rewrite linalg.winograd_input_transform.
FailureOr< Operation * > decomposeWinogradOutputTransformOp (RewriterBase &rewriter, linalg::WinogradOutputTransformOp op)
Rewrite linalg.winograd_output_transform.
FailureOr< linalg::GenericOp > deduplicateOperandsAndRemoveDeadResults (RewriterBase &rewriter, linalg::GenericOp genericOp, bool removeOutputs)
Method to deduplicate operands and remove dead results of linalg.generic operations.
FailureOr< LinalgOp > downscaleSizeOneWindowedConvolution (RewriterBase &rewriter, LinalgOp op)
Rewrite convolution/pooling/depthwise ops with size-1 window dimensions into lower-dimensional ops.
void populateLinalgTilingCanonicalizationPatterns (RewritePatternSet &patterns)
Canonicalization patterns relevant to apply after tiling patterns.
void populateLinalgNamedOpsGeneralizationPatterns (RewritePatternSet &patterns)
Linalg generalization patterns.
void populateLinalgGenericOpsSpecializationPatterns (RewritePatternSet &patterns, const GenericOpSpecializationOptions &options={})
Populates patterns with patterns to convert linalg.generic ops to named or category ops where possible.
void populateLinalgNamedToElementwisePatterns (RewritePatternSet &patterns)
Populates patterns that convert linalg named ops e.g.
void populateLinalgCategoryToNamedPatterns (RewritePatternSet &patterns)
Populates patterns that convert linalg category ops (e.g.
void populateLinalgFoldIntoElementwisePatterns (RewritePatternSet &patterns)
Populates patterns with patterns that fold operations like linalg.transform into elementwise op map.
void populateDecomposeConvolutionPatterns (RewritePatternSet &patterns, PatternBenefit benefit=1)
Linalg decompose convolutions patterns.
void populateDecomposePackUnpackPatterns (RewritePatternSet &patterns)
Populates patterns to decompose linalg.pack and linalg.unpack Ops into e.g.
void populateDecomposePadPatterns (RewritePatternSet &patterns)
Populates patterns to decompose tensor.pad into e.g.
void populateConvertConv2DToImg2ColPatterns (RewritePatternSet &patterns)
Populates patterns to transform linalg.conv_2d_xxx operations into linalg.generic (for img2col packing) and linalg.matmul.
void populatePadOpVectorizationPatterns (RewritePatternSet &patterns, PatternBenefit baseBenefit=1)
Populates patterns with patterns that vectorize tensor.pad.
void populateDecomposeLinalgOpsPattern (RewritePatternSet &patterns, bool removeDeadArgsAndResults=true)
Populate patterns for splitting a LinalgOp with multiple statements within its payload into multiple GenericOp that have a single statement.
void populateConvertToDestinationStylePatterns (RewritePatternSet &patterns)
Populate patterns that convert non-destination-style ops to destination style ops.
void populateConvolutionVectorizationPatterns (RewritePatternSet &patterns, PatternBenefit benefit=1)
Populate patterns for vectorizing low-D convolution ops.
void populateElementwiseToLinalgConversionPatterns (RewritePatternSet &patterns)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
void populateSparseTensorRewriting (RewritePatternSet &patterns)
Populate patterns that are only useful in the context of sparse tensors.
void populateElementwiseOpsFusionPatterns (RewritePatternSet &patterns, const ControlFusionFn &controlElementwiseOpFusion)
Patterns for fusing linalg operation on tensors.
void populateDataLayoutPropagationPatterns (RewritePatternSet &patterns, const ControlPropagationFn &controlPackUnPackPropagation, bool PoisonPaddingOk=false)
Patterns to bubble up or down data layout ops across other operations.
void populateExtractSliceSinkingPatterns (RewritePatternSet &patterns, const ControlPropagationFn &controlPackUnPackPropagation)
Patterns to sink extract slice across other operations.
void populateEraseUnusedOperandsAndResultsPatterns (RewritePatternSet &patterns)
Pattern to remove dead operands and results of linalg.generic operations.
void populateEraseUnnecessaryInputsPatterns (RewritePatternSet &patterns)
Patterns to promote inputs to outputs and remove unused inputs of linalg.generic ops.
void populateCollapseDimensions (RewritePatternSet &patterns, const GetCollapsableDimensionsFn &controlCollapseDimensions)
Pattern to collapse dimensions in a linalg.generic op.
void populateFoldReshapeOpsByExpansionPatterns (RewritePatternSet &patterns, const ControlFusionFn &controlFoldingReshapes)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
void populateFoldReshapeOpsByCollapsingPatterns (RewritePatternSet &patterns, const ControlFusionFn &controlFoldingReshapes)
Patterns to fold an expanding tensor.expand_shape operation with its producer generic operation by collapsing the dimensions of the generic op.
void populateConstantFoldLinalgOperations (RewritePatternSet &patterns, const ControlFusionFn &controlFn)
Patterns to constant fold Linalg operations.
void populateFoldAddIntoDestPatterns (RewritePatternSet &patterns)
Pattern to replace linalg.add when destination passing on a contraction op suffices for achieving the sum.
void populateFuseTensorPadWithProducerLinalgOpPatterns (RewritePatternSet &patterns)
Pattern to fuse a tensor.pad operation with the producer of its source, if the producer is a linalg operation with all parallel iterator types.
void populateSimplifyDepthwiseConvPatterns (RewritePatternSet &patterns)
Patterns to simplify depthwise convolutions.
void populateFoldUnitExtentDimsPatterns (RewritePatternSet &patterns, ControlDropUnitDims &options)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors and memref.
void populateFoldUnitExtentDimsCanonicalizationPatterns (RewritePatternSet &patterns, ControlDropUnitDims &options)
Populates canonicalization patterns that simplify IR after folding unit-extent dimensions.
void populateMoveInitOperandsToInputPattern (RewritePatternSet &patterns)
A pattern that converts init operands to input operands.
void populateInlineConstantOperandsPatterns (RewritePatternSet &patterns)
Patterns that are used to inline constant operands into linalg generic ops.
void populateBubbleUpExtractSliceOpPatterns (RewritePatternSet &patterns)
Patterns that are used to bubble up extract slice op above linalg op.
void populateSwapExtractSliceWithFillPatterns (RewritePatternSet &patterns)
Adds patterns that waps tensor.extract_slice(linalg.fill(cst, init)) into linalg.fill(cst, tensor.extract_slice(init)).
void populateDecomposeProjectedPermutationPatterns (RewritePatternSet &patterns)
Add patterns to make explicit broadcasts and transforms in the input operands of a genericOp.
void populateSplitReductionPattern (RewritePatternSet &patterns, const ControlSplitReductionFn &controlSplitReductionFn, bool useAlloc=false)
Patterns to apply splitReduction below.
void populateTransposeMatmulPatterns (RewritePatternSet &patterns, bool transposeLHS=true)
Patterns to convert Linalg matmul ops to transposed variants.
void populateBlockPackMatmulPatterns (RewritePatternSet &patterns, const ControlBlockPackMatmulFn &controlFn)
Patterns to block pack Linalg matmul ops.
void populateWinogradConv2DPatterns (RewritePatternSet &patterns, WinogradConv2DFmr fmr)
Patterns to apply Winograd Conv2D algorithm F(m x m, r x r).
void populateDecomposeWinogradOpsPatterns (RewritePatternSet &patterns)
Patterns to decompose Winograd operators.
void populateContractionOpRankReducingPatterns (RewritePatternSet &patterns)
Adds patterns that reduce the rank of named contraction ops that have unit dimensions in the operand(s) by converting to a sequence of collapse_shape, <corresponding linalg named op>, expand_shape (if on tensors).
void populateFoldIntoPackAndUnpackPatterns (RewritePatternSet &patterns, const ControlFoldIntoPackUnpackFn &controlFn=nullptr)
Populates patterns with patterns that fold operations like tensor.pad and tensor.extract_slice into tensor.pack and tensor.unpack operations respectively.
void populateFoldPackUnpackIntoTensorEmptyPatterns (RewritePatternSet &patterns)
Populates patterns with patterns that fold operations like linalg.pack and linalg.unpack into tensor.empty.
void populateSimplifyPackAndUnpackPatterns (RewritePatternSet &patterns)
Populates patterns with patterns that simplify tensor.pack and tensor.unpack operations.
SmallVector< int64_t > getPackInverseDestPerm (linalg::PackOp packOp, PackingMetadata &metadata)
Compute inverse permutation for the destination tensor (i.e.
SmallVector< int64_t > getUnPackInverseSrcPerm (linalg::UnPackOp, PackingMetadata &metadata)
Compute inverse permutation for the source tensor (i.e.
bool allIndexingsAreProjectedPermutation (LinalgOp op)
Check if all indexing maps are projected permutations.
bool hasOnlyScalarElementwiseOp (Region &r)
Detect whether r has only ConstantOp, ElementwiseMappable and YieldOp.
bool isElementwise (LinalgOp op)
Check if a LinalgOp is an element-wise operation.
bool isParallelIterator (utils::IteratorType iteratorType)
Check if iterator type has "parallel" semantics.
bool isReductionIterator (utils::IteratorType iteratorType)
Check if iterator type has "reduction" semantics.
Value makeComposedPadHighOp (OpBuilder &b, Location loc, RankedTensorType type, Value source, Value padding, bool nofold, ValueRange typeDynDims={})
Create a tensor::PadOp that pads source to the shape of type whose sizes are assumed to be greater than the dynamic source size.
GenericOp makeMemRefCopyOp (OpBuilder &b, Location loc, Value from, Value to)
Returns GenericOp that copies an n-D memref.
std::optional< SmallVector< ReassociationIndices > > getReassociationMapForFoldingUnitDims (ArrayRef< OpFoldResult > mixedSizes)
Get the reassociation maps to fold the result of a extract_slice (or source of a insert_slice) operation with given offsets, and sizes to its rank-reduced version.
template<typename ConvOpTy>
std::optional< DilationsAndStrides > matchConvolutionOpOfType (LinalgOp op)
Given a linalg op this function returns DilationsAndStrides if it is a convolution op of type ConvOpTy, otherwise returns std::nullopt.
template<typename ConvOpTy>
bool isaConvolutionOpOfType (LinalgOp op)
Returns true if the linalg op is a convolution op of type ConvOpTy.
SmallVector< OpFoldResult > computeTileOffsets (OpBuilder &b, Location loc, ArrayRef< OpFoldResult > ivs, ArrayRef< OpFoldResult > tileSizes)
Computes tile offsets, given a list of loop ivs and tileSizes.
SmallVector< OpFoldResult > computeTileSizes (OpBuilder &b, Location loc, ArrayRef< OpFoldResult > tileSizes, ArrayRef< OpFoldResult > sizeBounds)
Computes tile sizes, given a list of tileSizes and dimension sizes (sizeBounds).
SmallVector< Type > getTensorOutputTypes (LinalgOp op, ValueRange operands)
Returns the list of tensor output types produced when the given structured operation op is applied to the given operands.
SmallVector< Value > insertSlicesBack (OpBuilder &builder, Location loc, LinalgOp op, ValueRange operands, ValueRange results)
Creates insert_slice ops that insert results back into larger tensors they were originally extracted from with extract_slice before being passed as operands to the given structured operation op or its clone.
SliceParameters computeSliceParameters (OpBuilder &builder, Location loc, Value valueToTile, ArrayRef< OpFoldResult > tileSizes, AffineMap map, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > ubs, ArrayRef< OpFoldResult > subShapeSizes, bool omitPartialTileCheck)
Computes SliceParameters for a single valueToTile assuming that its user is being tiled with the given loop bounds lbs and ubs and the tile sizes tileSizes.
SmallVector< std::optional< SliceParameters > > computeAllSliceParameters (OpBuilder &builder, Location loc, LinalgOp linalgOp, ValueRange valuesToTile, ArrayRef< OpFoldResult > ivs, ArrayRef< OpFoldResult > tileSizes, ArrayRef< OpFoldResult > sizeBounds, bool omitPartialTileCheck)
Computes SliceParamaters for all valuesToTile of the given linalgOp, assuming linalgOp is being fused into a loop nest.
Operation * makeTiledShape (OpBuilder &builder, Location loc, Value valueToTile, ArrayRef< OpFoldResult > tileSizes, AffineMap map, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > ubs, ArrayRef< OpFoldResult > subShapeSizes, bool omitPartialTileCheck)
Creates an extract_slice/subview op for a single valueToTile with builder.
SmallVector< Value > makeTiledShapes (OpBuilder &builder, Location loc, LinalgOp linalgOp, ValueRange valuesToTile, ArrayRef< OpFoldResult > ivs, ArrayRef< OpFoldResult > tileSizes, ArrayRef< OpFoldResult > sizeBounds, bool omitPartialTileCheck)
Creates extract_slice/subview ops for all valuesToTile of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
void offsetIndices (OpBuilder &b, LinalgOp linalgOp, ArrayRef< OpFoldResult > offests)
Add the specified offsets to any linalg.index ops contained in the given linalgOp.
void offsetIndices (RewriterBase &b, LinalgOp linalgOp, ArrayRef< OpFoldResult > offests)
FailureOr< FusionInfo > fuseProducerOfTensor (OpBuilder &b, OpOperand &consumerOpOperand)
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a extract_slice op (generally obtained by applying the tiling transformation).
FailureOr< FusionInfo > fuseProducerOfTensor (OpBuilder &b, OpResult producerOpResult, OpOperand &consumerOpOperand)
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a extract_slice op (generally obtained by applying the tiling transformation).
void updateBoundsForCyclicDistribution (OpBuilder &builder, Location loc, Value procId, Value nprocs, Value &lb, Value &ub, Value &step)
Update the lb, ub and step to get per processor lb, ub and step.
template<typename OpTy>
SmallVector< NamedAttribute > getPrunedAttributeList (OpTy op)
Returns an attribute list that excludes pre-defined attributes.
static FailureOr< SmallVector< SmallVector< int64_t > > > getAffineResultPositions (ArrayAttr maps)
static FailureOr< ArrayAttr > parseIndexingMapsAttr (OpAsmParser &parser)
static ArityGroupAndKind getArityGroupAndKind (ElementwiseKind kind)
template SmallVector< int64_t > getPackedOuterShapeWithoutTransposition< PackOp > (PackOp)
template SmallVector< int64_t > getPackedOuterShapeWithoutTransposition< UnPackOp > (UnPackOp)
static SmallVector< OpFoldResult > getNewMixedTileSizes (PatternRewriter &rewriter, Type newPackedTy, ArrayRef< OpFoldResult > mixedTiles)
template<typename OpTy>
static LogicalResult reifyResultShapesImpl (OpTy op, OpBuilder &builder, ReifiedRankedShapedTypeDims &reifiedReturnShapes)
template<typename OpTy>
static DenseMap< int64_t, OpFoldResult > getDimAndTileMappingImpl (OpTy op)
template<typename OpTy>
static SmallVector< OpFoldResult > getMixedTilesImpl (OpTy op)
template<typename OpTy>
static SmallVector< int64_t > getStaticTilesImpl (OpTy op)
static bool isInvalidPackingPosSpecification (ArrayRef< int64_t > dimsPos, size_t rank)
Returns true if dimsPos is invalid.
template<typename OpTy>
static LogicalResult commonVerifierPackAndUnPackOp (OpTy packOrUnPack)
template<typename OpTy>
static PackOrUnPackTransposeResult commonPermutationOfPackAndUnPackOp (OpTy packOrUnPackOp, ArrayRef< int64_t > innerPermutation, ArrayRef< int64_t > outerPermutation)
static SmallVector< int64_t > asShapeWithAnyValueAsDynamic (ArrayRef< OpFoldResult > ofrs)
Converts OpFoldResults to int64_t shape entries, unconditionally mapping all Value's to kDynamic, even if they are arith.constant values.
template<typename OpTy>
static void getPackUnPackEffectsImpl (OpTy op, SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect > > &effects)
template<typename OpTy>
static bool areTilesAndTiledDimsAllConstant (OpTy op)
Returns true if the tiles and the tiled dims are constant.
static bool hasSameInnerOuterAttribute (PackOp packOp, UnPackOp unPackOp)
static bool haveSameTiles (PackOp packOp, UnPackOp unPackOp)
static bool paddingIsNotNeeded (PackOp op)
Returns true if the pack op does not need a padding value.
static bool inferStaticShape (PackOp packOp, SmallVectorImpl< int64_t > &srcShape, SmallVectorImpl< int64_t > &destShape)
Returns true if the srcShape or destShape is different from the one in packOp and populates each with the inferred static shape.
template<typename PackOrUnpackOp>
static bool isLikePadUnPad (PackOrUnpackOp packOp, ShapedType packedTensorType)
static bool inferStaticShape (UnPackOp op, SmallVectorImpl< int64_t > &srcShape, SmallVectorImpl< int64_t > &destShape)
Returns true if the srcShape or destShape is different from the one in op and populates each with the inferred static shape.
static bool hasAllOneValues (DenseIntElementsAttr attr)
static Value createAdd (Location loc, Value x, Value y, OpBuilder &builder)
static Value createMul (Location loc, Value x, Value y, Type accType, OpBuilder &builder)
static AffineExpr getConvolvedExpr (OpBuilder &b, int64_t stride, bool useSymbols=true)
static Im2ColToInputDimsExprs getIm2ColInputExpressions (Im2ColToOperandsExprs exprs, ArrayRef< int64_t > strides, RewriterBase &rewriter)
Construct the affine expressions that map the indices of the im2col matrix to the corresponding input tensor indices for a 2D convolution with the the provided strides.
static ReductionKind getReductionKind (Operation *op)
static std::optional< Operation * > getCombinerOp (LinalgOp op)
static ReductionKind getReductionKindOfLinalgOp (LinalgOp op)
static GridOp getGrid (Operation *op, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, SymbolTableCollection &symbolTable)
static Value createDestinationPassingStyleInitOperand (LinalgOp op, int operandNumber, Value partitionedOperand, ArrayRef< GridAxis > reductionGridAxes, GridOp gridOp, ImplicitLocOpBuilder &builder)
static SmallVector< Value > createDestinationPassingStyleInitOperands (LinalgOp op, GridOp gridOp, ArrayRef< Value > partitionedOperands, ArrayRef< GridAxis > reductionGridAxes, IRMapping &partitionMap, ImplicitLocOpBuilder &builder)
static void createAllReduceForResultsWithoutPartialShardings (LinalgOp unshardedOp, ArrayRef< GridAxis > opReductionGridAxes, ArrayRef< Sharding > resultShardings, IRMapping &partitionMap, ImplicitLocOpBuilder &builder)
static void partitionLinalgOpWithShardedReduction (LinalgOp op, ArrayRef< Value > partitionedOperands, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, ArrayRef< utils::IteratorType > loopIteratorTypes, ArrayRef< SmallVector< GridAxis > > gridAxisAssignmentForLoopIterators, IRMapping &partitionMap, SymbolTableCollection &symbolTable, ImplicitLocOpBuilder &builder)
template<typename OpType>
static void registerOne (MLIRContext *ctx)
template<typename... OpTypes>
static void registerAll (MLIRContext *ctx)
Variadic helper function.
void populateTransposeConv2DPatterns (RewritePatternSet &patterns)
FailureOr< Operation * > winogradConv2D (RewriterBase &rewriter, linalg::Conv2DNhwcFhwcOp op, linalg::WinogradConv2DFmr fmr)
SmallVector< int64_t > getPackInverseDestPerm (PackOp packOp, PackingMetadata &metadata)
SmallVector< int64_t > getUnPackInverseSrcPerm (UnPackOp unpackOp, PackingMetadata &metadata)
static BlockArgument getBlockArgumentWithOptionalCastOps (Value val)
Returns the BlockArgument that leads to val, if any.
static bool bodyMatcherForZeroPointOffsets (Operation *addOp, Operation *mulOp, Block *body)
Utility function to match the zero point offset body of quantized convolution ops.
static bool bodyMatcherForConvolutionOps (Value yieldVal, Block *body, bool containsZeroPointOffset=false)
Utility to match block body for convolution ops.
template<typename... OpTypes>
static bool bodyMatcherForPoolOps (Value yieldVal, Block *body)
Utility to match block body for linalg.pool* ops.
static bool bodyMatcherForMaxSignedPoolOps (Value yieldVal, Block *body)
static bool bodyMatcherForMaxUnsignedPoolOps (Value yieldVal, Block *body)
static bool bodyMatcherForMinSignedPoolOps (Value yieldVal, Block *body)
static bool bodyMatcherForMinUnsignedPoolOps (Value yieldVal, Block *body)
static bool bodyMatcherForSumPoolOps (Value yieldVal, Block *body)
Matches sum pooling body pattern.
static AffineExpr getAffineMapDim (ArrayAttr indexingMaps, uint32_t mapIndex, uint32_t dimIndex)
static int64_t isDimTimesConstantOrDimOnly (AffineExpr expr, AffineExpr &dim)
Check if expr is either:
static bool matchConvDimAddExprPattern (ArrayAttr indexingMaps, unsigned iDim, unsigned fDim, unsigned oDim, int64_t &dilation, int64_t &stride)
Given an array of AffineMaps indexingMaps verify the following commutatively:- indexingMaps[0].getResult(iDim) == indexingMaps[1].getResult(fDim) * <c0> + indexingMaps[n-1].getResult(oDim) * <c1> where,.
static bool convLayoutMatches (ArrayRef< ArrayRef< AffineExpr > > mapListExpected, ArrayAttr indexingMaps, MLIRContext *context)
Returns true if the given indexing maps matches with the expected indexing maps.
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv1DOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv1DNwcWcfOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv1DNcwFcwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNhwcHwcfOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNhwcHwcfQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNhwcFhwcOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNhwcFhwcQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNchwFchwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNchwFchwQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNgchwFgchwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNgchwGfchwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNgchwGfchwQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNhwgcGfhwcOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv2DNhwgcGfhwcQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv3DOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv3DNdhwcDhwcfOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv3DNdhwcDhwcfQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::Conv3DNcdhwFcdhwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv1DNcwCwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv1DNwcWcOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv1DNwcWcmOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv2DNchwChwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcmOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcmQOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv3DNdhwcDhwcOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv3DNcdhwCdhwOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::DepthwiseConv3DNdhwcDhwcmOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNhwcMaxOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNhwcMinOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNhwcSumOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNhwcMaxUnsignedOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNhwcMinUnsignedOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNchwSumOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNchwMaxOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNwcSumOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNcwSumOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNwcMaxOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNwcMaxUnsignedOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNcwMaxOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNwcMinOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNwcMinUnsignedOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNdhwcSumOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNdhwcMaxOp > (LinalgOp op)
template<>
std::optional< DilationsAndStrides > matchConvolutionOpOfType< linalg::PoolingNdhwcMinOp > (LinalgOp op)
static void generateParallelLoopNest (OpBuilder &b, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< utils::IteratorType > iteratorTypes, ArrayRef< linalg::ProcInfo > procInfo, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage)
Generates a loop nest consisting of scf.parallel and scf.for, depending on the iteratorTypes.
static Operation * materializeTiledShape (OpBuilder &builder, Location loc, Value valueToTile, const SliceParameters &sliceParams)
Typedef Documentation
AllocBufferCallbackFn
using mlir::linalg::AllocBufferCallbackFn
Initial value:
 std::function<std::optional<Value>(
    OpBuilder &b, memref::SubViewOp subView,
    ArrayRef<Value> boundingSubViewSize, DataLayout &layout)>
Callback function type used to perform the allocation for the promoted subView.
In boundingSubViewsize a best attempt is made to find the smallest constant value for the size of the buffer needed for each dimension. If that is not possible, contains the dynamic size of the subview. The call back should return the buffer to use.
Definition at line 378 of file Transforms.h.
ControlBlockPackMatmulFn
using mlir::linalg::ControlBlockPackMatmulFn
Initial value:
    std::function<std::optional<BlockPackMatmulOptions>(linalg::LinalgOp)>
Function type which is used to control matmul packing.
It is expected to return valid packing configuration for each operation. Lack of packing options indicates that no valid configuration could be assigned and the operation will not be packed.
Definition at line 1453 of file Transforms.h.
ControlFoldIntoPackUnpackFn
using mlir::linalg::ControlFoldIntoPackUnpackFn = std::function<bool(OpOperand *opOperand)>
Function type which is used to control folding operations like tensor.pad and tensor.extract_slice into linalg.pack/unpack ops.
Definition at line 2129 of file Transforms.h.
ControlFusionFn
using mlir::linalg::ControlFusionFn = std::function<bool(OpOperand *fusedOperand)>
Function type which is used to control when to stop fusion.
It is expected that OpOperand is not modified in the callback. The OpOperand is not marked as const to allow callers to use non-const methods.
Definition at line 1995 of file Transforms.h.
ControlPropagationFn
using mlir::linalg::ControlPropagationFn = std::function<bool(OpOperand *opOperand)>
Function type which is used to control propagation of linalg.pack/unpack ops.
Definition at line 2007 of file Transforms.h.
ControlSplitReductionFn
using mlir::linalg::ControlSplitReductionFn
Initial value:
    std::function<SplitReductionOptions(LinalgOp op)>
Function signature to control reduction splitting.
This returns SplitReductionOptions.
Definition at line 489 of file Transforms.h.
CopyCallbackFn
using mlir::linalg::CopyCallbackFn
Initial value:
    std::function<LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
The copy has to happen from src to dst.
Definition at line 391 of file Transforms.h.
DeallocBufferCallbackFn
using mlir::linalg::DeallocBufferCallbackFn
Initial value:
    std::function<LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
Definition at line 384 of file Transforms.h.
DroppedUnitDimsBuilder
using mlir::linalg::DroppedUnitDimsBuilder
Initial value:
 std::function<IndexingMapOpInterface(
    Location loc, OpBuilder &, IndexingMapOpInterface,
    ArrayRef<Value> newOperands, ArrayRef<AffineMap> newIndexingMaps,
    const llvm::SmallDenseSet<unsigned> &droppedDims)>
Definition at line 629 of file Transforms.h.
GetCollapsableDimensionsFn
using mlir::linalg::GetCollapsableDimensionsFn
Initial value:
    std::function<SmallVector<ReassociationIndices>(linalg::LinalgOp)>
Function type to control generic op dimension collapsing.
It is expected to return an array of ReassociationIndices representing dimensions that should be merged.
Definition at line 2033 of file Transforms.h.
GridAxis
using mlir::linalg::GridAxis = shard::GridAxis
Definition at line 39 of file ShardingInterfaceImpl.cpp.
GridOp
using mlir::linalg::GridOp = shard::GridOp
Definition at line 43 of file ShardingInterfaceImpl.cpp.
LinalgLoops
using mlir::linalg::LinalgLoops = SmallVector<Operation *, 4>
Definition at line 517 of file Transforms.h.
LoopIndexToRangeIndexMap
using mlir::linalg::LoopIndexToRangeIndexMap = DenseMap<int, int>
Creates a number of ranges equal to the number of non-zero in tileSizes.
One for each loop of the LinalgOp that is tiled. The tileSizes argument has one entry per surrounding loop. It uses zero as the convention that a particular loop is not tiled. This convention simplifies implementations by avoiding affine map manipulations. The returned ranges correspond to the loop ranges, in the proper order, that are tiled and for which new loops will be created. Also the function returns a map from loop indices of the LinalgOp to the corresponding non-empty range indices of newly created loops.
Definition at line 1044 of file Transforms.h.
OptimizeCopyFn
using mlir::linalg::OptimizeCopyFn
Initial value:
    std::function<LogicalResult(RewriterBase &, tensor::PadOp, Value)>
Definition at line 1713 of file Transforms.h.
PadSizeComputationFunction
using mlir::linalg::PadSizeComputationFunction
Initial value:
    std::function<FailureOr<SmallVector<OpFoldResult>>(
        OpBuilder &, OpOperand &, ArrayRef<Range>,
        const PadTilingInterfaceOptions &)>
Definition at line 726 of file Transforms.h.
ProcInfoCallBackFn
using mlir::linalg::ProcInfoCallBackFn
Initial value:
 std::function<SmallVector<ProcInfo>(
    OpBuilder &b, Location loc, ArrayRef<Range> parallelLoopRanges)>
Definition at line 331 of file Utils.h.
ReductionKind
using mlir::linalg::ReductionKind = shard::ReductionKind
Definition at line 40 of file ShardingInterfaceImpl.cpp.
Sharding
using mlir::linalg::Sharding = shard::Sharding
Definition at line 41 of file ShardingInterfaceImpl.cpp.
ShardingArray
using mlir::linalg::ShardingArray = shard::ShardingArray
Definition at line 42 of file ShardingInterfaceImpl.cpp.
TileSizeComputationFunction
using mlir::linalg::TileSizeComputationFunction
Initial value:
    std::function<SmallVector<Value, 4>(OpBuilder &, Operation *)>
Definition at line 187 of file Transforms.h.
Enumeration Type Documentation
DistributionMethod
enum class mlir::linalg::DistributionMethod strong
Scheme used to distribute loops to processors.
Enumerator
Cyclic
Cyclic distribution where no assumption is made about the dynamic relationship between number of processors and number of iterations of the distributed loop.
Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
scf.parallel(iv)= (lb + procId * step) to (ub) step (step * nprocs)
CyclicNumProcsGeNumIters
Cyclic distribution where the number of processors can be assumed to be more than or equal to the number of iterations of the distributed loop.
In such cases, a simple in-bounds check is enough (instead of materializing a loop). Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step cond = arith.cmpi "slt", iv, ub scf.if cond { ... }
CyclicNumProcsEqNumIters
Cyclic distribution where the number of processors can be assumed to be equal to the number of iterations of the distributed loop.
In such cases, no bounds check is needed. Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step
None
No Distribution.
Definition at line 276 of file Utils.h.
LinalgTilingLoopType
enum class mlir::linalg::LinalgTilingLoopType strong
The type of loops to be generated during tiling.
Enumerator
Loops
AffineLoops
ParallelLoops
Definition at line 135 of file Utils.h.
PoolingType
enum class mlir::linalg::PoolingType strong
Enum representing pooling operation types used by ConvMatcherBuilder.
Enumerator
None
MaxSigned
MaxUnsigned
MinSigned
MinUnsigned
Sum
Definition at line 509 of file Utils.cpp.
Function Documentation
allIndexingsAreProjectedPermutation()
bool mlir::linalg::allIndexingsAreProjectedPermutation (LinalgOp op)
Check if all indexing maps are projected permutations.
Definition at line 197 of file Utils.cpp.
Referenced by isElementwise().
allocateGPUPrivateMemory()
std::optional< Value > mlir::linalg::allocateGPUPrivateMemory (OpBuilder & builder, memref::SubViewOp subview, ArrayRef< Value > sizeBounds, DataLayout &)
Allocate the subview in the GPU private memory.
Definition at line 496 of file Promotion.cpp.
References allocateSubviewGPUMemoryInAddressSpace().
allocateWorkgroupMemory()
std::optional< Value > mlir::linalg::allocateWorkgroupMemory (OpBuilder & builder, memref::SubViewOp subview, ArrayRef< Value > sizeBounds, DataLayout &)
Allocate the subview in the GPU workgroup memory.
Definition at line 471 of file Promotion.cpp.
References allocateSubviewGPUMemoryInAddressSpace().
areDimSequencesPreserved()
bool mlir::linalg::areDimSequencesPreserved (ArrayRef< AffineMap > maps, ArrayRef< ReassociationIndices > dimSequences)
Return true if all sequences of dimensions specified in dimSequences are contiguous in all the ranges of the maps.
Definition at line 1351 of file ElementwiseOpFusion.cpp.
References isDimSequencePreserved().
areElementwiseOpsFusable()
bool mlir::linalg::areElementwiseOpsFusable (OpOperand * fusedOperand)
Return true if two linalg.generic operations with producer/consumer relationship through fusedOperand can be fused using elementwise op fusion.
Conditions for elementwise fusion of generic operations.
Definition at line 140 of file ElementwiseOpFusion.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp(), mlir::AffineMap::getNumResults(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getType(), mlir::AffineMap::isPermutation(), and result.
Referenced by fuseElementwiseOps(), and mlir::impl::LinalgElementwiseOpFusionPassBase< DerivedT >::getArgumentName().
areTilesAndTiledDimsAllConstant()
template<typename OpTy> bool mlir::linalg::areTilesAndTiledDimsAllConstant (OpTy op) static
Returns true if the tiles and the tiled dims are constant.
Definition at line 5844 of file LinalgOps.cpp.
References mlir::getConstantIntValue(), and mlir::tile().
asShapeWithAnyValueAsDynamic()
SmallVector< int64_t > mlir::linalg::asShapeWithAnyValueAsDynamic (ArrayRef< OpFoldResult > ofrs) static
Converts OpFoldResults to int64_t shape entries, unconditionally mapping all Value's to kDynamic, even if they are arith.constant values.
Definition at line 5666 of file LinalgOps.cpp.
References mlir::getConstantIntValue(), and result.
blockPackMatmul()
FailureOr< PackResult > mlir::linalg::blockPackMatmul (RewriterBase & rewriter, linalg::LinalgOp linalgOp, const ControlBlockPackMatmulFn & controlPackMatmul)
Pack a matmul operation into blocked 4D layout.
Relayout a matmul operation into blocked layout with two levels of subdivision:
major 2D blocks - outer dimensions, consist of minor blocks
minor 2D blocks - inner dimensions, consist of scalar elements
A 2D matmul MxNxK gets reshaped into blocked 4D representation as: [MB][NB][mb][nb] += [MB][KB][mb][kb] * [NB][KB][nb][kb] where the (MB, NB, KB) dimensions represent the major blocks, and the (mb, nb, kb) are the minor blocks of their respective original 2D dimensions (M, N, K).
Depending on the initial operands' data layout and the specified packing options, the major blocks dimensions might get transposed e.g., [MB][KB] -> [KB][MB]. The minor blocks can also be transposed e.g., [mb][kb] -> [kb][mb]. Any present batch dimensions remain unchanged. The final result is unpacked back to the original shape.
Return failure if no valid packing options are provided.
Definition at line 142 of file BlockPackMatmul.cpp.
References mlir::getAsOpFoldResult(), mlir::Builder::getI64ArrayAttr(), inferContractionDims(), mlir::RewriterBase::notifyMatchFailure(), options, packMatmulGreedily(), mlir::OpBuilder::setInsertionPointAfter(), transposePackedMatmul(), and validateFullTilesOnDims().
bodyMatcherForConvolutionOps()
bool mlir::linalg::bodyMatcherForConvolutionOps (Value yieldVal, Block * body, bool containsZeroPointOffset = false) static
Utility to match block body for convolution ops.
The body is thus expected to yield :- out + (lhs * rhs) where: lhs, rhs and out are block arguments and lhs and rhs can have optional upcast operation. For i1 element types, the pattern matches: out | (lhs & rhs) using arith.ori for accumulation and arith.andi for multiplication. NOTE: In case of zero point offset convolution ops lhs and rhs would be :- input - input_scalar where, input_scalar can have optional upcast operation.
Definition at line 331 of file Utils.cpp.
References bodyMatcherForZeroPointOffsets(), mlir::BlockArgument::getArgNumber(), getBlockArgumentWithOptionalCastOps(), mlir::Value::getDefiningOp(), mlir::Operation::getOperand(), and mlir::BlockArgument::getOwner().
Referenced by mlir::linalg::ConvMatcherBuilder::matchBody().
bodyMatcherForMaxSignedPoolOps()
bool mlir::linalg::bodyMatcherForMaxSignedPoolOps (Value yieldVal, Block * body) static
Definition at line 382 of file Utils.cpp.
References bodyMatcherForPoolOps().
Referenced by mlir::linalg::ConvMatcherBuilder::matchBody().
bodyMatcherForMaxUnsignedPoolOps()
bool mlir::linalg::bodyMatcherForMaxUnsignedPoolOps (Value yieldVal, Block * body) static
Definition at line 387 of file Utils.cpp.
References bodyMatcherForPoolOps().
Referenced by mlir::linalg::ConvMatcherBuilder::matchBody().
bodyMatcherForMinSignedPoolOps()
bool mlir::linalg::bodyMatcherForMinSignedPoolOps (Value yieldVal, Block * body) static
Definition at line 391 of file Utils.cpp.
References bodyMatcherForPoolOps().
Referenced by mlir::linalg::ConvMatcherBuilder::matchBody().
bodyMatcherForMinUnsignedPoolOps()
bool mlir::linalg::bodyMatcherForMinUnsignedPoolOps (Value yieldVal, Block * body) static
Definition at line 396 of file Utils.cpp.
References bodyMatcherForPoolOps().
Referenced by mlir::linalg::ConvMatcherBuilder::matchBody().
bodyMatcherForPoolOps()
template<typename... OpTypes> bool mlir::linalg::bodyMatcherForPoolOps (Value yieldVal, Block * body) static
Utility to match block body for linalg.pool* ops.
Definition at line 366 of file Utils.cpp.
References mlir::BlockArgument::getArgNumber(), getBlockArgumentWithOptionalCastOps(), mlir::Value::getDefiningOp(), mlir::Operation::getOperand(), and mlir::BlockArgument::getOwner().
Referenced by bodyMatcherForMaxSignedPoolOps(), bodyMatcherForMaxUnsignedPoolOps(), bodyMatcherForMinSignedPoolOps(), bodyMatcherForMinUnsignedPoolOps(), and bodyMatcherForSumPoolOps().
bodyMatcherForSumPoolOps()
bool mlir::linalg::bodyMatcherForSumPoolOps (Value yieldVal, Block * body) static
Matches sum pooling body pattern.
For i1 element types, arith.ori is used instead of arith.addi/arith.addf for accumulation.
Definition at line 402 of file Utils.cpp.
References bodyMatcherForPoolOps().
Referenced by mlir::linalg::ConvMatcherBuilder::matchBody().
bodyMatcherForZeroPointOffsets()
bool mlir::linalg::bodyMatcherForZeroPointOffsets (Operation * addOp, Operation * mulOp, Block * body) static
Utility function to match the zero point offset body of quantized convolution ops.
Quantized convolutions have a body of the form: out + ((input - inputZp) * (filter - filterZp)) where:
input is the input tensor element (block arg 0)
filter is the filter tensor element (block arg 1)
inputZp is the input zero-point scalar (block arg 2)
filterZp is the filter zero-point scalar (block arg 3)
out is the output accumulator (block arg 4)
This function verifies that the multiplication operands are subtraction operations matching this pattern.
Definition at line 275 of file Utils.cpp.
References mlir::BlockArgument::getArgNumber(), getBlockArgumentWithOptionalCastOps(), mlir::Value::getDefiningOp(), mlir::Operation::getOperand(), and mlir::BlockArgument::getOwner().
Referenced by bodyMatcherForConvolutionOps().
bufferizeToAllocation() [1/4]
Value mlir::linalg::bufferizeToAllocation (RewriterBase & rewriter, const BufferizeToAllocationOptions & options, bufferization::AllocTensorOp allocTensorOp, Attribute memorySpace = {}, Operation * insertionPoint = nullptr)
Materialize a buffer allocation for the given bufferization.alloc_tensor op and lower the op to memref.alloc + memref.tensor_store.
In addition to rewriting the IR, this function returns the newly allocated buffer. The insertionPoint parameter can be used to specify a custom insertion point for the buffer allocation.
Definition at line 335 of file ConvertToDestinationStyle.cpp.
References createAllocationForTensor(), options, mlir::RewriterBase::replaceOp(), and mlir::OpBuilder::setInsertionPoint().
bufferizeToAllocation() [2/4]
Value mlir::linalg::bufferizeToAllocation (RewriterBase & rewriter, const BufferizeToAllocationOptions & options, Operation * op, Attribute memorySpace = {}, Operation * insertionPoint = nullptr)
Bufferize the given op with tensor semantics and materialize the result in a newly allocated buffer.
Only bufferizable ops that bufferize to a memory write or have an aliasing OpOperand (and do not themselves bufferize to an allocation) are supported. They are bufferized using their BufferizableOpInterface implementation.
Selected ops that bufferize to an allocation (or need special handling) are also supported:
tensor.pad
vector.mask
This function returns the newly allocated buffer. The insertionPoint parameter can be used to specify a custom insertion point for the buffer allocation.
Definition at line 485 of file ConvertToDestinationStyle.cpp.
References bufferizeToAllocation(), createAllocationForTensor(), createMemcpy(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), mlir::Operation::getOpOperands(), mlir::Operation::getResults(), mlir::RewriterBase::modifyOpInPlace(), options, result, mlir::OpBuilder::setInsertionPoint(), and mlir::Operation::walk().
bufferizeToAllocation() [3/4]
Value mlir::linalg::bufferizeToAllocation (RewriterBase & rewriter, const BufferizeToAllocationOptions & options, tensor::PadOp padOp, Attribute memorySpace = {}, Operation * insertionPoint = nullptr)
Materialize a buffer allocation for the given tensor.pad op and lower the op to linalg.fill/linalg.generic + bufferization.materialize_in_destination.
E.g.:
%0 = tensor.pad low[l] high[h] t ...
is lowered to:
alloc = memref.alloc linalg.fill ... outs(alloc) subview = memref.subview alloc [l] [...] [1] bufferization.materialize_in_destination t in subview %0 = bufferization.to_tensor alloc restrict writable
In addition to rewriting the IR as shown above, this function returns the newly allocated buffer. The insertionPoint parameter can be used to specify a custom insertion point for the buffer allocation.
References options.
Referenced by bufferizeToAllocation(), and bufferizeToAllocation().
bufferizeToAllocation() [4/4]
Value mlir::linalg::bufferizeToAllocation (RewriterBase & rewriter, const BufferizeToAllocationOptions & options, vector::MaskOp maskOp, Attribute memorySpace = {}, Operation * insertionPoint = nullptr)
Materialize a buffer allocation for the given vector.mask op and bufferize the op, including its region.
E.g.:
%0 = vector.mask { vector.transfer_write v, t : vector<16xf32>, tensor<?xf32> } : vector<16xi1> -> tensor<?xf32>
is lowered to:
alloc = memref.alloc bufferization.materialize_in_destination t in subview vector.mask { vector.transfer_write arg0, alloc : vector<16xf32>, memref<?xf32> } : vector<16xi1> %0 = bufferization.to_tensor alloc restrict writable
In addition to rewriting the IR as shown above, this function returns the newly allocated buffer. The insertionPoint parameter can be used to specify a custom insertion point for the buffer allocation.
Definition at line 268 of file ConvertToDestinationStyle.cpp.
References bufferizeToAllocation(), mlir::RewriterBase::eraseOp(), mlir::RewriterBase::modifyOpInPlace(), options, result, and mlir::OpBuilder::setInsertionPoint().
collapseOpIterationDims()
FailureOr< CollapseResult > mlir::linalg::collapseOpIterationDims (LinalgOp op, ArrayRef< ReassociationIndices > foldedIterationDims, RewriterBase & rewriter)
Collapses dimensions of linalg.generic/linalg.copy operation.
A precondition to calling this method is that for each list in foldedIterationDim, the sequence of dimensions is contiguous in domains of all indexing_maps of the linalgOp. This can be checked using areDimSequencePreserved method. When valid, the method also collapses the operands of the op. Returns replacement values of the results of the original linalgOp by inserting reshapes to get back values of compatible types.
commonPermutationOfPackAndUnPackOp()
template<typename OpTy> PackOrUnPackTransposeResult mlir::linalg::commonPermutationOfPackAndUnPackOp (OpTy packOrUnPackOp, ArrayRef< int64_t > innerPermutation, ArrayRef< int64_t > outerPermutation) static
Definition at line 5328 of file LinalgOps.cpp.
References mlir::applyPermutationToVector(), and mlir::isPermutationVector().
commonVerifierPackAndUnPackOp()
template<typename OpTy> LogicalResult mlir::linalg::commonVerifierPackAndUnPackOp (OpTy packOrUnPack) static
Definition at line 5201 of file LinalgOps.cpp.
References mlir::Operation::emitError(), isInvalidPackingPosSpecification(), mlir::isZeroInteger(), success(), mlir::tile(), and mlir::verifyCompatibleShape().
computeAllSliceParameters()
SmallVector< std::optional< SliceParameters > > mlir::linalg::computeAllSliceParameters (OpBuilder & builder, Location loc, LinalgOp linalgOp, ValueRange valuesToTile, ArrayRef< OpFoldResult > ivs, ArrayRef< OpFoldResult > tileSizes, ArrayRef< OpFoldResult > sizeBounds, bool omitPartialTileCheck)
Computes SliceParamaters for all valuesToTile of the given linalgOp, assuming linalgOp is being fused into a loop nest.
Calls computeSliceParameters for every individual value.
Note that a constant zero in tileSizes means no tiling at that implicit loop. The number of non-zero values in tileSizes should be equal to the number of values in ivs.
Some of the valuesToTile won't be affected by tiling. For these values, std::nullopt will be returned.
Definition at line 2799 of file Utils.cpp.
References computeSliceParameters(), computeTileOffsets(), computeTileSizes(), and isTiled().
Referenced by makeTiledShapes().
computeContinuousTileSizes()
FailureOr< ContinuousTileSizeSpecification > mlir::linalg::computeContinuousTileSizes (OpBuilder & builder, TilingInterface op, unsigned dimension, OpFoldResult targetSize, bool emitAssertions)
Definition at line 156 of file Tiling.cpp.
References b, mlir::OpBuilder::createOrFold(), emitIsPositiveIndexAssertion(), mlir::AffineExpr::floorDiv(), mlir::getConstantIntValue(), mlir::getValueOrCreateConstantIndexOp(), mlir::affine::makeComposedAffineApply(), mlir::affine::makeComposedFoldedAffineApply(), mlir::linalg::detail::ContinuousTileSizeSpecificationBase< T >::tileSizes, and mlir::linalg::detail::ContinuousTileSizeSpecificationBase< T >::tripCounts.
computeIndexingMapOpInterfacePaddedShape()
FailureOr< SmallVector< OpFoldResult > > mlir::linalg::computeIndexingMapOpInterfacePaddedShape (OpBuilder & builder, OpOperand & operandToPad, ArrayRef< Range > iterationDomain, const PadTilingInterfaceOptions & options)
Specific helper for Linalg ops.
Definition at line 200 of file PadTilingInterface.cpp.
References computePaddedShape(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Builder::getIndexAttr(), mlir::detail::IROperandBase::getOwner(), mlir::Range::offset, options, and mlir::Range::stride.
computeMultiTileSizes()
FailureOr< MultiSizeSpecification > mlir::linalg::computeMultiTileSizes (OpBuilder & builder, LinalgOp op, unsigned dimension, OpFoldResult targetSize, OpFoldResult divisor, bool emitAssertions = true)
Emits the IR computing the multi-sized tiling specification with two tile sizes not exceeding targetSize, each divisible by sizeDivisor, such that there exist numbers of tiles with these sizes that fully cover the given iteration space dimension of the structured op.
The computation is as follows:
b = originalTripCount floordiv sizeDivisor t = (targetSize + sizeDivisor - 1) floordiv sizeDivisor d = (b + t - 1) floordiv t s = (b floordiv d) * sizeDivisor v = b % d u = d - v
where the tile sizes are s and s + sizeDivisor, and the numbers of the corresponding tiles are u and v, respectively. Alternatively,
s * u + (s + sizeDivisor) * v == original size, where s mod sizeDivisor = 0.
Expects all values to be positive. In some cases with the target tile size sufficiently close to the dimension shape and non-unit divisor, it is impossible to compute such sizes. If emitAssertion is set, also emit the assertion that size computation succeeded.
Returns the specification consisting of both tile values and the number of tiles of each size.
Definition at line 262 of file Tiling.cpp.
References b, emitIsPositiveIndexAssertion(), mlir::AffineExpr::floorDiv(), mlir::Builder::getAffineSymbolExpr(), mlir::Builder::getStringAttr(), mlir::getValueOrCreateConstantIndexOp(), mlir::linalg::detail::MultiSizeSpecificationBase< T >::lowTileSize, mlir::affine::makeComposedAffineApply(), and mlir::affine::makeComposedFoldedMultiResultAffineApply().
computePaddedShape()
SmallVector< OpFoldResult > mlir::linalg::computePaddedShape (OpBuilder & builder, TypedValue< RankedTensorType > v, AffineMap indexingMap, ArrayRef< OpFoldResult > indexingSizes, const PadTilingInterfaceOptions & options)
Helper function to compute the padded shape of the given value v of RankedTensorType given:
Compute the padded shape of the given value v of RankedTensorType given.
the indexingSizes as a list of OpFoldResult.
an indexingMap that encodes how the padded shape varies with increases in indexingSizes. The implementation iteratively combines increases from contributing using affine.apply operations. The indexingMap + indexingSizes encoding suits StructuredOps and provides a gentle portability path for Linalg-like ops with affine maps. The padded shape is computed by evaluating the maximum accessed index per dimension, which may involve multiplying by constant factors derived from the affine indexing expressions. Currently, only a limited set of projected permuation indexing maps are supported, such as
affine_map<(d0, d1, d2) -> (d0, d1)>
affine_map<(d0, d1, d2) -> (d0, d1 + d2)>
affine_map<(d0, d1) -> (d0 * 3 + d1)> In the future, more general interfaces can be devised to encode similar shape evolutions and map between an op and its operands.
indexingSizes a list of OpFoldResult.
an indexingMap that encodes how the shape of varies with increases in indexingSizes. The indexingMap encodes how the shape of varies with indexingSizes. The indexingMap + indexingSizes encoding suits StructuredOps. The implementaiton below iteratively combines increases from contributing dimensions using affine.apply operations. The padded shape is computed by evaluating the maximum accessed index per dimension, which may involve multiplying by constant factors derived from the affine indexing expressions. Currently, only a limited set of projected permutation indexing maps are supported, such as
affine_map<(d0, d1, d2) -> (d0, d1)>
affine_map<(d0, d1, d2) -> (d0, d1 + d2)>
affine_map<(d0, d1) -> (d0 * 3 + d1)> In the future, more general interfaces can be devised to encode similar shape evolutions and map between an op and its operands.
Definition at line 99 of file PadTilingInterface.cpp.
References mlir::bindDims(), mlir::bindDimsList(), mlir::bindSymbols(), mlir::AffineExpr::ceilDiv(), mlir::AffineMap::compose(), createFoldedDimOp(), DBGS, extractConstantMultiplier(), mlir::AffineMap::get(), mlir::Builder::getContext(), getFullRankPaddingSizes(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), mlir::AffineMap::getSubMap(), mlir::affine::makeComposedFoldedAffineApply(), options, and mlir::projectDims().
Referenced by computeIndexingMapOpInterfacePaddedShape().
computeSliceParameters()
SliceParameters mlir::linalg::computeSliceParameters (OpBuilder & builder, Location loc, Value valueToTile, ArrayRef< OpFoldResult > tileSizes, AffineMap map, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > ubs, ArrayRef< OpFoldResult > subShapeSizes, bool omitPartialTileCheck)
Computes SliceParameters for a single valueToTile assuming that its user is being tiled with the given loop bounds lbs and ubs and the tile sizes tileSizes.
omitPartialTileCheck controls whether to omit the partial/boundary tile condition check in cases where we statically know that it is unnecessary.
Definition at line 2614 of file Utils.cpp.
References mlir::bindDims(), createFoldedDimOp(), mlir::getAffineSymbolExpr(), mlir::getConstantIntValue(), mlir::Builder::getContext(), mlir::Builder::getIndexAttr(), mlir::AffineMap::getSubMap(), mlir::Value::getType(), mlir::AffineMap::inferFromExprList(), isTiled(), mlir::affine::makeComposedFoldedAffineApply(), mlir::affine::makeComposedFoldedAffineMin(), mlir::linalg::SliceParameters::offsets, mlir::linalg::SliceParameters::sizes, and mlir::linalg::SliceParameters::strides.
Referenced by computeAllSliceParameters(), and makeTiledShape().
computeStaticContinuousTileSizes()
FailureOr< StaticContinuousTileSizeSpecification > mlir::linalg::computeStaticContinuousTileSizes (LinalgOp op, unsigned dimension, unsigned targetSize)
Definition at line 106 of file Tiling.cpp.
References mlir::linalg::detail::ContinuousTileSizeSpecificationBase< T >::tileSizes, and mlir::linalg::detail::ContinuousTileSizeSpecificationBase< T >::tripCounts.
computeStaticMultiTileSizes()
FailureOr< StaticMultiSizeSpecification > mlir::linalg::computeStaticMultiTileSizes (LinalgOp op, unsigned dimension, int64_t targetSize, int64_t divisor)
Definition at line 236 of file Tiling.cpp.
References mlir::linalg::detail::MultiSizeSpecificationBase< T >::highTileSize, mlir::linalg::detail::MultiSizeSpecificationBase< T >::highTripCount, mlir::linalg::detail::MultiSizeSpecificationBase< T >::lowTileSize, and mlir::linalg::detail::MultiSizeSpecificationBase< T >::lowTripCount.
computeTileOffsets()
SmallVector< OpFoldResult > mlir::linalg::computeTileOffsets (OpBuilder & b, Location loc, ArrayRef< OpFoldResult > ivs, ArrayRef< OpFoldResult > tileSizes)
Computes tile offsets, given a list of loop ivs and tileSizes.
In case a tile size is zero (i.e., no tiling), the corresponding offset is also zero.
Definition at line 2731 of file Utils.cpp.
References b, isTiled(), and mlir::isZeroInteger().
Referenced by computeAllSliceParameters().
computeTileSizes()
SmallVector< OpFoldResult > mlir::linalg::computeTileSizes (OpBuilder & b, Location loc, ArrayRef< OpFoldResult > tileSizes, ArrayRef< OpFoldResult > sizeBounds)
Computes tile sizes, given a list of tileSizes and dimension sizes (sizeBounds).
In case a tile size is zero (i.e., no tiling), the corresponding result size is the corresponding value from sizeBounds. Note: The returned tile sizes are closed intervals.
Definition at line 2745 of file Utils.cpp.
References b, mlir::getAffineDimExpr(), isTiled(), mlir::isZeroInteger(), and mlir::affine::makeComposedFoldedAffineApply().
Referenced by computeAllSliceParameters().
concat()
SmallVector< AffineExpr, 4 > mlir::linalg::concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Definition at line 2590 of file LinalgOps.cpp.
References b.
convLayoutMatches()
bool mlir::linalg::convLayoutMatches (ArrayRef< ArrayRef< AffineExpr > > mapListExpected, ArrayAttr indexingMaps, MLIRContext * context) static
Returns true if the given indexing maps matches with the expected indexing maps.
Definition at line 496 of file Utils.cpp.
References mlir::AffineMap::inferFromExprList().
Referenced by mlir::linalg::ConvMatcherBuilder::matchMaps().
copyToGPUPrivateMemory()
LogicalResult mlir::linalg::copyToGPUPrivateMemory (OpBuilder & b, Value src, Value dst)
Normal copy to between src and dst.
Definition at line 504 of file Promotion.cpp.
References b, mlir::Value::getLoc(), and success().
copyToWorkgroupMemory()
LogicalResult mlir::linalg::copyToWorkgroupMemory (OpBuilder & b, Value src, Value dst)
Create Memref copy operations and add gpu barrier guards before and after the copy operation to ensure data integrity.
Definition at line 487 of file Promotion.cpp.
References b, mlir::Operation::getLoc(), mlir::Value::getLoc(), and success().
createAdd()
Value mlir::linalg::createAdd (Location loc, Value x, Value y, OpBuilder & builder) static
Definition at line 34 of file ConvertConv2DToImg2Col.cpp.
References mlir::Value::getType().
Referenced by rewriteInIm2Col(), rewriteInIm2Col(), and rewriteInIm2Col().
createAllReduceForResultsWithoutPartialShardings()
void mlir::linalg::createAllReduceForResultsWithoutPartialShardings (LinalgOp unshardedOp, ArrayRef< GridAxis > opReductionGridAxes, ArrayRef< Sharding > resultShardings, IRMapping & partitionMap, ImplicitLocOpBuilder & builder) static
Definition at line 188 of file ShardingInterfaceImpl.cpp.
References getReductionKindOfLinalgOp(), mlir::IRMapping::lookup(), and mlir::IRMapping::map().
Referenced by partitionLinalgOpWithShardedReduction().
createDestinationPassingStyleInitOperand()
Value mlir::linalg::createDestinationPassingStyleInitOperand (LinalgOp op, int operandNumber, Value partitionedOperand, ArrayRef< GridAxis > reductionGridAxes, GridOp gridOp, ImplicitLocOpBuilder & builder) static
Definition at line 126 of file ShardingInterfaceImpl.cpp.
References mlir::arith::ConstantIndexOp::create(), mlir::shard::createProcessLinearIndex(), mlir::Builder::getI1Type(), mlir::ImplicitLocOpBuilder::getLoc(), mlir::tensor::getMixedSizes(), mlir::arith::getNeutralElement(), mlir::Value::getType(), mlir::matchReduction(), and mlir::OpBuilder::setInsertionPointToEnd().
Referenced by createDestinationPassingStyleInitOperands().
createDestinationPassingStyleInitOperands()
SmallVector< Value > mlir::linalg::createDestinationPassingStyleInitOperands (LinalgOp op, GridOp gridOp, ArrayRef< Value > partitionedOperands, ArrayRef< GridAxis > reductionGridAxes, IRMapping & partitionMap, ImplicitLocOpBuilder & builder) static
Definition at line 172 of file ShardingInterfaceImpl.cpp.
References createDestinationPassingStyleInitOperand(), and mlir::IRMapping::lookup().
Referenced by partitionLinalgOpWithShardedReduction().
createFoldedDimOp()
OpFoldResult mlir::linalg::createFoldedDimOp (OpBuilder & b, Location loc, Value val, int64_t dim)
Create one memref::DimOp or tensor::DimOp depending on the type of val.
This is a polymorphic convenience function to abstract away the rank and concrete type of val. Asserts that val is a memref or tensor type.
Definition at line 117 of file LinalgOps.cpp.
References b, createOrFoldDimOp(), and mlir::Value::getType().
Referenced by computePaddedShape(), computeSliceParameters(), fuse(), and reifyResultShapesImpl().
createMul()
Value mlir::linalg::createMul (Location loc, Value x, Value y, Type accType, OpBuilder & builder) static
Definition at line 42 of file ConvertConv2DToImg2Col.cpp.
References mlir::convertScalarToDtype().
Referenced by rewriteInIm2Col(), rewriteInIm2Col(), and rewriteInIm2Col().
createOrFoldDimOp()
Value mlir::linalg::createOrFoldDimOp (OpBuilder & b, Location loc, Value val, int64_t dim)
Create one memref::DimOp or tensor::DimOp depending on the type of val.
This is a polymorphic convenience function to abstract away the rank and concrete type of val. Asserts that val is a memref or tensor type.
Definition at line 108 of file LinalgOps.cpp.
References b, and mlir::Value::getType().
Referenced by concatSizesFromInputs(), createFoldedDimOp(), and mlir::sparse_tensor::sizesFromSrc().
deallocateGPUPrivateMemory()
LogicalResult mlir::linalg::deallocateGPUPrivateMemory (OpBuilder & , Value)
In case of GPU private memory there is no need to deallocate since the memory is freed when going outside of the scope.
Definition at line 512 of file Promotion.cpp.
References success().
deallocateWorkgroupMemory()
LogicalResult mlir::linalg::deallocateWorkgroupMemory (OpBuilder & , Value)
In case of GPU group memory there is no need to deallocate.
Definition at line 480 of file Promotion.cpp.
References success().
decomposeWinogradFilterTransformOp()
FailureOr< Operation * > mlir::linalg::decomposeWinogradFilterTransformOp (RewriterBase & rewriter, linalg::WinogradFilterTransformOp op)
Rewrite linalg.winograd_filter_transform.
The data layout of the filter is FHWC. The transformation matrix is 2-dimension. We need to extract H x W from FHWC first. We generate 2 levels of loops to iterate on F and C. After the rewriting, we get
scf.for f = lo_f to hi_f step 1 scf.for c = lo_c to hi_c step 1 extracted = extract filter<h x w> from filter<f x h x w x c> ret = linalg.matmul G, extracted ret = linalg.matmul ret, GT inserted = insert ret into filter<h x w x c x f>
Definition at line 1196 of file WinogradConv2D.cpp.
decomposeWinogradInputTransformOp()
FailureOr< Operation * > mlir::linalg::decomposeWinogradInputTransformOp (RewriterBase & rewriter, linalg::WinogradInputTransformOp op)
Rewrite linalg.winograd_input_transform.
The data layout of the input is NHWC. The transformation matrix is 2-dimension. We need to extract H x W from NHWC first. We generate 4 levels of loops to iterate on N, C, tileH, and tileW. After the rewriting, we get
scf.for h = 0 to tileH step 1 scf.for w = 0 to tileW step 1 scf.for n = 0 to N step 1 scf.for c = 0 to C step 1 extracted = extract extracted<alphaH x alphaW> from input<N x H x W x C> at [n, (h x m), (w x m), c] ret = linalg.matmul BT, extracted ret = linalg.matmul ret, B inserted = insert ret<alphaH x alphaW> into output<alphaH x alphaW x tileH x tileW x N x C> at [0, 0, h, w, n, c]
Definition at line 1202 of file WinogradConv2D.cpp.
decomposeWinogradOutputTransformOp()
FailureOr< Operation * > mlir::linalg::decomposeWinogradOutputTransformOp (RewriterBase & rewriter, linalg::WinogradOutputTransformOp op)
Rewrite linalg.winograd_output_transform.
The data layout of the output is HWNF. The transformation matrix is 2-dimension. We need to extract H x W from HWNF first. We generate 4 levels of loops to iterate on N, F, tileH, and tileW. After the transformation, we get
scf.for h = 0 to tileH step 1 scf.for w = 0 to tileW step 1 scf.for n = 0 to N step 1 scf.for f = 0 to F step 1 extracted = extract extracted<alphaH x alphaW> from input<alphaH x alphaW x tileH x tileW x N x F> at [0, 0, h, w, n, f] ret = linalg.matmul AT, extracted ret = linalg.matmul ret, A inserted = insert ret<alphaH x alphaW> into output<N x H x W x F> at [n, (h x m), (w x m), f]
Definition at line 1208 of file WinogradConv2D.cpp.
deduplicateOperandsAndRemoveDeadResults()
FailureOr< linalg::GenericOp > mlir::linalg::deduplicateOperandsAndRemoveDeadResults (RewriterBase & rewriter, linalg::GenericOp genericOp, bool removeOutputs)
Method to deduplicate operands and remove dead results of linalg.generic operations.
This is effectively DCE for a linalg.generic op. If there is deduplication of operands orremoval of results, replaces the genericOp with a new op and returns it. Returns the same operation if there is no deduplication/removal.
Definition at line 231 of file EraseUnusedOperandsAndResults.cpp.
References deduplicateInputOperands(), deduplicateOutputOperands(), mlir::Builder::getAffineMapArrayAttr(), populateOpPayload(), mlir::RewriterBase::replaceOp(), and result.
downscaleSizeOneWindowedConvolution()
FailureOr< LinalgOp > mlir::linalg::downscaleSizeOneWindowedConvolution (RewriterBase & rewriter, LinalgOp op)
Rewrite convolution/pooling/depthwise ops with size-1 window dimensions into lower-dimensional ops.
Uses inferConvolutionDims to work with any layout and handles both named ops and equivalent linalg.generic ops uniformly. The result is specialized back to a named op if the input was a named op. TODO: Support n-D to (n-1)-D downscaling. Currently it only support 2D->1D downscaling.
Definition at line 1510 of file Transforms.cpp.
References mlir::tensor::createCanonicalRankReducingInsertSliceOp(), createRankReducingExtractSlice(), dropDimsAndCompress(), mlir::AffineMap::get(), mlir::IROperand< DerivedT, IRValueT >::get(), getResultIndicesReferencingDims(), mlir::Value::getType(), inferConvolutionDims(), mlir::RewriterBase::inlineRegionBefore(), mlir::RewriterBase::replaceOp(), result, and specializeGenericOp().
dropUnitDims() [1/2]
FailureOr< DropUnitDimsResult > mlir::linalg::dropUnitDims (RewriterBase & rewriter, GenericOp genericOp, const ControlDropUnitDims & options)
Drop unit extent dimensions from the genericOp and its operands.
The transformation is aborted if unit dimensions cannot be dropped from any of the operands. Note that this function may insert trivially dead operations if the transformation is aborted and should therefore not be called from greedy drivers.
Definition at line 547 of file DropUnitDims.cpp.
References b, dropUnitDims(), mlir::getType(), options, and replaceUnitDimIndexOps().
dropUnitDims() [2/2]
FailureOr< DropUnitDimsResult > mlir::linalg::dropUnitDims (RewriterBase & rewriter, IndexingMapOpInterface op, const DroppedUnitDimsBuilder & droppedUnitDimsBuilder, const ControlDropUnitDims & options)
Drop unit extent dimensions from the op and its operands.
The transformation is aborted if unit dimensions cannot be dropped from any of the operands. Note that this function may insert trivially dead operations if the transformation is aborted and should therefore not be called from greedy drivers.
Definition at line 400 of file DropUnitDims.cpp.
References mlir::concatAffineMaps(), dropUnitExtentFromOperandMetadata(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getResults(), mlir::inversePermutation(), mlir::RewriterBase::notifyMatchFailure(), options, and result.
Referenced by dropUnitDims().
extractOrIdentityMap()
AffineMap mlir::linalg::extractOrIdentityMap (std::optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
Definition at line 2570 of file LinalgOps.cpp.
References mlir::AffineMap::get(), and mlir::AffineMap::getMultiDimIdentityMap().
fuseElementwiseOps()
FailureOr< mlir::linalg::ElementwiseOpFusionResult > mlir::linalg::fuseElementwiseOps (RewriterBase & rewriter, OpOperand * fusedOperand)
This transformation is intended to be used with a top-down traversal (from producer to consumer).
In that way fusion logic can safely handle producers with multiple users.
Find the results of the producer that have uses outside of the consumer, after the fusion.
Definition at line 340 of file ElementwiseOpFusion.cpp.
References areElementwiseOpsFusable(), mlir::AffineMap::compose(), mlir::RewriterBase::eraseOp(), generateFusedElementwiseOpRegion(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Builder::getAffineMapArrayAttr(), getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp(), mlir::detail::IROperandBase::getOwner(), getPreservedProducerResults(), mlir::inversePermutation(), mlir::RewriterBase::notifyMatchFailure(), and result.
fuseProducerOfTensor() [1/2]
FailureOr< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, OpOperand & consumerOpOperand)
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a extract_slice op (generally obtained by applying the tiling transformation).
Definition at line 218 of file Fusion.cpp.
References b, fuseProducerOfTensor(), mlir::IROperand< DerivedT, IRValueT >::get(), and getProducerOfTensor().
Referenced by fuseProducerOfTensor().
fuseProducerOfTensor() [2/2]
FailureOr< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, OpResult producerOpResult, OpOperand & consumerOpOperand)
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a extract_slice op (generally obtained by applying the tiling transformation).
Assumes producerOfTensor is a Linalg op that produces consumerOpOperand.
Definition at line 230 of file Fusion.cpp.
References b, mlir::tensor::dropGivenUnitDims(), fuse(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::detail::IROperandBase::getOwner(), mlir::OpResult::getOwner(), mlir::Value::getParentBlock(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), and mlir::IROperand< DerivedT, IRValueT >::set().
generalizeNamedOp()
FailureOr< GenericOp > mlir::linalg::generalizeNamedOp (RewriterBase & rewriter, LinalgOp linalgOp)
Create a GenericOp from the given named operation linalgOp and replace the given linalgOp.
Return failure if linalgOp is a GenericOp or misses a region builder.
Definition at line 46 of file Generalization.cpp.
References generalizeNamedOpPrecondition(), mlir::RewriterBase::inlineRegionBefore(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), TypeRange, and ValueRange.
Referenced by packMatmulGreedily(), and mlir::linalg::LinalgGeneralizationPattern::returningMatchAndRewrite().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(f, A) : f32, memref<f32> name mangles into linalg_fill_f32_viewf32
linalg.dot A, B, C : (memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32>) name mangles into linalg_dot_viewxf32_viewxf32_viewf32
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32
Definition at line 2631 of file LinalgOps.cpp.
References appendMangledType(), mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), and mlir::OperationName::getStringRef().
generateParallelLoopNest()
void mlir::linalg::generateParallelLoopNest (OpBuilder & b, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< utils::IteratorType > iteratorTypes, ArrayRef< linalg::ProcInfo > procInfo, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > & ivStorage) static
Generates a loop nest consisting of scf.parallel and scf.for, depending on the iteratorTypes.
Consecutive parallel loops create a single scf.parallel operation; each sequential loop creates a new scf.for operation. The body of the innermost loop is populated by bodyBuilderFn that accepts a range of induction variables for all loops. ivStorage is used to store the partial list of induction variables.
Definition at line 2421 of file Utils.cpp.
References mlir::ArithBuilder::_and(), b, mlir::scf::buildLoopNest(), Cyclic, CyclicNumProcsEqNumIters, CyclicNumProcsGeNumIters, mlir::linalg::ProcInfo::distributionMethod, generateParallelLoopNest(), isParallelIterator(), None, and mlir::ArithBuilder::slt().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit(), and generateParallelLoopNest().
getAffineMapDim()
AffineExpr mlir::linalg::getAffineMapDim (ArrayAttr indexingMaps, uint32_t mapIndex, uint32_t dimIndex) static
Definition at line 407 of file Utils.cpp.
Referenced by matchConvDimAddExprPattern().
getAffineResultPositions()
FailureOr< SmallVector< SmallVector< int64_t > > > mlir::linalg::getAffineResultPositions (ArrayAttr maps) static
Definition at line 3890 of file LinalgOps.cpp.
References result.
Referenced by mlir::linalg::BatchMatmulTransposeAOp::isDefaultIndexingMaps(), mlir::linalg::BatchMatmulTransposeBOp::isDefaultIndexingMaps(), mlir::linalg::MatmulTransposeAOp::isDefaultIndexingMaps(), and mlir::linalg::MatmulTransposeBOp::isDefaultIndexingMaps().
getArityGroupAndKind()
ArityGroupAndKind mlir::linalg::getArityGroupAndKind (ElementwiseKind kind) static
Definition at line 4874 of file LinalgOps.cpp.
References result.
getBlockArgumentWithOptionalCastOps()
BlockArgument mlir::linalg::getBlockArgumentWithOptionalCastOps (Value val) static
Returns the BlockArgument that leads to val, if any.
Traverses optional ext*‍/sitofp ops.
Definition at line 246 of file Utils.cpp.
References mlir::Value::getDefiningOp(), and mlir::Operation::getOperand().
Referenced by bodyMatcherForConvolutionOps(), bodyMatcherForPoolOps(), and bodyMatcherForZeroPointOffsets().
getCombinerOp()
std::optional< Operation * > mlir::linalg::getCombinerOp (LinalgOp op) static
Definition at line 76 of file ShardingInterfaceImpl.cpp.
References mlir::matchReduction().
Referenced by getReductionKindOfLinalgOp().
getCombinerOpKind()
std::optional< vector::CombiningKind > mlir::linalg::getCombinerOpKind (Operation * combinerOp)
Return vector::CombiningKind for the given op.
Definition at line 640 of file Vectorization.cpp.
Referenced by buildMultiDimReduce().
getConvolvedExpr()
AffineExpr mlir::linalg::getConvolvedExpr (OpBuilder & b, int64_t stride, bool useSymbols = true) static
Definition at line 59 of file ConvertConv2DToImg2Col.cpp.
References b, mlir::bindDims(), and mlir::bindSymbols().
Referenced by getIm2ColInputExpressions().
getDimAndTileMappingImpl()
template<typename OpTy> DenseMap< int64_t, OpFoldResult > mlir::linalg::getDimAndTileMappingImpl (OpTy op) static
Definition at line 5143 of file LinalgOps.cpp.
getFmrFromWinogradConv2DFmr()
std::pair< int64_t, int64_t > mlir::linalg::getFmrFromWinogradConv2DFmr (WinogradConv2DFmr fmr)
Converts the given WinogradConv2DFmr enumeration value to a pair of m and r parameters.
Definition at line 3873 of file LinalgOps.cpp.
getGrid()
GridOp mlir::linalg::getGrid (Operation * op, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, SymbolTableCollection & symbolTable) static
Definition at line 100 of file ShardingInterfaceImpl.cpp.
References mlir::shard::getGrid().
Referenced by partitionLinalgOpWithShardedReduction().
getIm2ColInputExpressions()
Im2ColToInputDimsExprs mlir::linalg::getIm2ColInputExpressions (Im2ColToOperandsExprs exprs, ArrayRef< int64_t > strides, RewriterBase & rewriter) static
Construct the affine expressions that map the indices of the im2col matrix to the corresponding input tensor indices for a 2D convolution with the the provided strides.
Parameters
exprs Affine expressions for output and filter indices.
strides [height, width] stride values for the convolution.
rewriter Pattern rewriter.
Returns
Affine expressions mapping im2col matrix indices to input offsets.
Definition at line 98 of file ConvertConv2DToImg2Col.cpp.
References mlir::linalg::Im2ColToOperandsExprs::fhIndex, mlir::linalg::Im2ColToOperandsExprs::fwIndex, mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), getConvolvedExpr(), mlir::linalg::Im2ColToOperandsExprs::icIndex, mlir::AffineMap::inferFromExprList(), mlir::linalg::Im2ColToOperandsExprs::ohIndex, and mlir::linalg::Im2ColToOperandsExprs::owIndex.
Referenced by rewriteInIm2Col(), rewriteInIm2Col(), and rewriteInIm2Col().
getMixedTilesImpl()
template<typename OpTy> SmallVector< OpFoldResult > mlir::linalg::getMixedTilesImpl (OpTy op) static
Definition at line 5158 of file LinalgOps.cpp.
References mlir::Builder::getI64IntegerAttr().
getNewMixedTileSizes()
SmallVector< OpFoldResult > mlir::linalg::getNewMixedTileSizes (PatternRewriter & rewriter, Type newPackedTy, ArrayRef< OpFoldResult > mixedTiles) static
Definition at line 5110 of file LinalgOps.cpp.
References mlir::Builder::getIndexAttr(), and getShape().
Referenced by mlir::linalg::FoldTensorCastPackOp::matchAndRewrite(), and mlir::linalg::FoldTensorCastUnPackOp::matchAndRewrite().
getPackedOuterShapeWithoutTransposition()
template<typename OpTy, typename = std::enable_if_t<std::is_same_v<OpTy, linalg::PackOp> || std::is_same_v<OpTy, linalg::UnPackOp>>> SmallVector< int64_t > mlir::linalg::getPackedOuterShapeWithoutTransposition (OpTy packOrUnPack)
Returns the outer shape in the packed domain before applying the transposition.
Definition at line 5083 of file LinalgOps.cpp.
References mlir::applyPermutationToVector(), mlir::invertPermutationVector(), and result.
getPackedOuterShapeWithoutTransposition< PackOp >()
template SmallVector< int64_t > mlir::linalg::getPackedOuterShapeWithoutTransposition< PackOp > (PackOp)
getPackedOuterShapeWithoutTransposition< UnPackOp >()
template SmallVector< int64_t > mlir::linalg::getPackedOuterShapeWithoutTransposition< UnPackOp > (UnPackOp)
getPackInverseDestPerm() [1/2]
SmallVector< int64_t > mlir::linalg::getPackInverseDestPerm (linalg::PackOp packOp, PackingMetadata & metadata)
Compute inverse permutation for the destination tensor (i.e.
in the packed domain).
Referenced by lowerPack().
getPackInverseDestPerm() [2/2]
SmallVector< int64_t > mlir::linalg::getPackInverseDestPerm (PackOp packOp, PackingMetadata & metadata)
Definition at line 176 of file Utils.cpp.
References computePackUnPackPerm().
getPackUnPackEffectsImpl()
template<typename OpTy> void mlir::linalg::getPackUnPackEffectsImpl (OpTy op, SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect > > & effects) static
Definition at line 5804 of file LinalgOps.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::SideEffects::Effect::Base< DerivedEffect, Effect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), and mlir::Value::getType().
getPreservedProducerResults()
llvm::SmallDenseSet< int > mlir::linalg::getPreservedProducerResults (GenericOp producer, GenericOp consumer, OpOperand * fusedOperand)
Returns a set of indices of the producer's results which would be preserved after the fusion.
There is a chance that the implementation of the transformation does not agree with the result of this method. This function gives a prediction based on an optimized fusion.
Definition at line 113 of file ElementwiseOpFusion.cpp.
References isOpOperandCanBeDroppedAfterFusedLinalgs().
Referenced by fuseElementwiseOps().
getPrunedAttributeList()
template<typename OpTy> SmallVector< NamedAttribute > mlir::linalg::getPrunedAttributeList (OpTy op)
Returns an attribute list that excludes pre-defined attributes.
Definition at line 402 of file Utils.h.
References getPrunedAttributeList().
Referenced by getPrunedAttributeList(), and matchAndReplaceDepthwiseConv().
getReassociationMapForFoldingUnitDims()
std::optional< SmallVector< ReassociationIndices > > mlir::linalg::getReassociationMapForFoldingUnitDims (ArrayRef< OpFoldResult > mixedSizes)
Get the reassociation maps to fold the result of a extract_slice (or source of a insert_slice) operation with given offsets, and sizes to its rank-reduced version.
This is only done for the cases where the size is 1 and offset is 0. Strictly speaking the offset 0 is not required in general, but non-zero offsets are not handled by SPIR-V backend at this point (and potentially cannot be handled).
Definition at line 2908 of file Utils.cpp.
getReductionKind()
ReductionKind mlir::linalg::getReductionKind (Operation * op) static
Definition at line 46 of file ShardingInterfaceImpl.cpp.
Referenced by getReductionKindOfLinalgOp().
getReductionKindOfLinalgOp()
ReductionKind mlir::linalg::getReductionKindOfLinalgOp (LinalgOp op) static
Definition at line 86 of file ShardingInterfaceImpl.cpp.
References getCombinerOp(), and getReductionKind().
Referenced by createAllReduceForResultsWithoutPartialShardings().
getStaticTilesImpl()
template<typename OpTy> SmallVector< int64_t > mlir::linalg::getStaticTilesImpl (OpTy op) static
Definition at line 5174 of file LinalgOps.cpp.
References mlir::dispatchIndexOpFoldResults().
getTensorOutputTypes()
SmallVector< Type > mlir::linalg::getTensorOutputTypes (LinalgOp op, ValueRange operands)
Returns the list of tensor output types produced when the given structured operation op is applied to the given operands.
Note that operands are not necessarily the actual operands of op.
Definition at line 2761 of file Utils.cpp.
Referenced by tileLinalgOpImpl().
getUnPackInverseSrcPerm() [1/2]
SmallVector< int64_t > mlir::linalg::getUnPackInverseSrcPerm (linalg::UnPackOp , PackingMetadata & metadata)
Compute inverse permutation for the source tensor (i.e.
in the packed domain).
References b.
Referenced by lowerUnPack().
getUnPackInverseSrcPerm() [2/2]
SmallVector< int64_t > mlir::linalg::getUnPackInverseSrcPerm (UnPackOp unpackOp, PackingMetadata & metadata)
Definition at line 187 of file Utils.cpp.
References computePackUnPackPerm().
getWinogradConv2DFmr()
std::optional< WinogradConv2DFmr > mlir::linalg::getWinogradConv2DFmr (int64_t m, int64_t r)
Converts the given m and r parameters to a WinogradConv2DFmr enumeration value.
Definition at line 3863 of file LinalgOps.cpp.
hasAllOneValues()
bool mlir::linalg::hasAllOneValues (DenseIntElementsAttr attr) static
Definition at line 29 of file ConvertConv2DToImg2Col.cpp.
Referenced by rewriteInIm2Col(), rewriteInIm2Col(), rewriteInIm2Col(), and rewriteInIm2Col().
hasOnlyScalarElementwiseOp()
bool mlir::linalg::hasOnlyScalarElementwiseOp (Region & r)
Detect whether r has only ConstantOp, ElementwiseMappable and YieldOp.
Definition at line 203 of file Utils.cpp.
References mlir::Region::front(), mlir::OpTrait::hasElementwiseMappableTraits(), and mlir::Region::hasOneBlock().
Referenced by isElementwise().
hasSameInnerOuterAttribute()
bool mlir::linalg::hasSameInnerOuterAttribute (PackOp packOp, UnPackOp unPackOp) static
Definition at line 5877 of file LinalgOps.cpp.
References mlir::isIdentityPermutation().
hasVectorizationImpl()
bool mlir::linalg::hasVectorizationImpl (Operation *)
Return true if there's dedicated logic in the Linalg Vectorizer to vectorize this Op, false otherwise.
Note that this helper merely implements a very high level check and that the vectorizer also requires various additional pre-conditions to be met for it to work (these are checked by the vectorizer itself).
haveSameTiles()
bool mlir::linalg::haveSameTiles (PackOp packOp, UnPackOp unPackOp) static
Definition at line 5891 of file LinalgOps.cpp.
References mlir::isEqualConstantIntOrValue().
hoistPaddingOnTensors() [1/2]
FailureOr< Value > mlir::linalg::hoistPaddingOnTensors (RewriterBase & rewriter, tensor::PadOp opToHoist, int64_t numLoops, ArrayRef< int64_t > transposeVector, tensor::PadOp & hoistedOp, SmallVectorImpl< TransposeOp > & transposeOps)
Mechanically hoist padding operations on tensors by numLoops into a new, generally larger tensor.
This achieves packing of multiple padding ops into a larger tensor. On success, opToHoist is replaced by the cloned version in the packing loop so the caller can continue reasoning about the padding operation. If transposeVector is non-empty, hoist padding introduces a TransposeOp to transpose the padded tensor before inserting it into the packed tensor. A transposeVector can change the storage order of the padded tensor but does not change the order of the pack or compute loops.
TODO: In the future, we should consider rewriting as a linalg.pack after hoisting since this abstraction is now available.
Example in pseudo-mlir:
If hoistPaddingOnTensors is called with nLoops = 2 on the following IR.
scf.for (%i, %j, %k)
  %st0 = tensor.extract_slice f(%i, %k) : ... to tensor<?x?xf32>
  %0 = tensor.pad %st0 low[0, 0] high[...] {
  ^bb0( ... ):
    linalg.yield %pad
  } : tensor<?x?xf32> to tensor<4x8xf32>
  compute(%0)
IR resembling the following is produced:
scf.for (%i) {
  %packed_init = tensor.empty range(%j) : tensor<?x4x8xf32>
  %packed = scf.for (%k) iter_args(%p : %packed_init) {
    %st0 = tensor.extract_slice f(%i, %k) : ... to tensor<?x?xf32>
    %0 = tensor.pad %st0 low[0, 0] high[...] {
    ^bb0( ... ):
      linalg.yield %pad
    } : tensor<?x?xf32> to tensor<4x8xf32>
    %1 = tensor.insert_slice %0 ...
        : tensor<4x8xf32> to tensor<?x4x8xf32>
    scf.yield %1: tensor<?x4x8xf32>
  } -> tensor<?x4x8xf32>
  scf.for (%j, %k) {
    %st0 = tensor.extract_slice %packed [%k, 0, 0][1, 4, 8][1, 1, 1] :
             tensor<?x4x8xf32> to tensor<4x8xf32>
    compute(%st0)
  }
}
Construct the packing loop nest.
Definition at line 943 of file HoistPadding.cpp.
References buildPackingLoopNestImpl(), mlir::tensor::computeTransposedType(), DBGS, mlir::Value::getDefiningOp(), mlir::Operation::getParentOfType(), replaceByPackingResult(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by hoistPaddingOnTensors(), and padAndHoistLinalgOp().
hoistPaddingOnTensors() [2/2]
FailureOr< Value > mlir::linalg::hoistPaddingOnTensors (tensor::PadOp opToHoist, int64_t numLoops, ArrayRef< int64_t > transposeVector, tensor::PadOp & hoistedOp, SmallVectorImpl< TransposeOp > & transposeOps)
Calls into hoistPaddingOnTensors with a local IRRewriter.
Definition at line 1008 of file HoistPadding.cpp.
References hoistPaddingOnTensors().
hoistRedundantVectorBroadcasts()
void mlir::linalg::hoistRedundantVectorBroadcasts (RewriterBase & rewriter, Operation * root)
Hoist vector.extract/vector.broadcast pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are met:
The vector.extract operation is applied on an iter_argument, and no other operator is using this argument in the body of the loop.
The position of the vector.extract is either a static value, or defined outside of the loop.
The vector.broadcast operation is yielded by the loop. To improve hoisting opportunities, call the moveLoopInvariantCode helper function on the candidate loop above which to hoist.
Definition at line 89 of file Hoisting.cpp.
References mlir::WalkResult::advance(), broadcast(), DBGS, mlir::IROperand< DerivedT, IRValueT >::get(), mlir::WalkResult::interrupt(), mlir::RewriterBase::modifyOpInPlace(), mlir::moveLoopInvariantCode(), mlir::RewriterBase::moveOpAfter(), mlir::RewriterBase::replaceAllUsesWith(), replaceWithDifferentYield(), and mlir::Operation::walk().
hoistRedundantVectorTransfers()
void mlir::linalg::hoistRedundantVectorTransfers (Operation * root, bool verifyNonZeroTrip = false)
Hoist vector.transfer_read/vector.transfer_write on buffers pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
The two ops access the same memref with the same indices.
All operands are invariant under the enclosing scf::ForOp.
No uses of the memref either dominate the transfer_read or are dominated by the transfer_write (i.e. no aliasing between the write and the read across the loop)
The source operands for vector.transfer_{read|write} do not originate from Ops implementing ViewLikeOpInterface (to reduce the risk of aliasing).
If verifyNonZeroTrip is true, then the lower bound of the loop must be statically smaller than the upper bound of the loop, guaranteeing that the loop body will execute at least once. To improve hoisting opportunities, call the moveLoopInvariantCode helper function on the candidate loop above which to hoist. Hoisting the transfers results in scf::ForOp yielding the value that originally transited through memory.
TODO: To further improve hoisting opportunities, fold aliasing memref operations into respective vector.transfer{read|write} operations and avoid using ops implementing ViewLikeOpInterface as the source for transfer Ops.
WARNING: This hoisting does not model parallelism and is generally incorrect when used on distributed loops with memref semantics! NOTE: Setting verifyNonZeroTrip = true makes this more stable for distributed loops with memref semantics, but there could still be some issues when loops are executed a different number of times for different threads.
Definition at line 198 of file Hoisting.cpp.
References mlir::WalkResult::advance(), b, mlir::ValueBoundsConstraintSet::computeConstantBound(), DBGS, mlir::Value::getDefiningOp(), mlir::getForwardSlice(), mlir::Value::hasOneUse(), mlir::WalkResult::interrupt(), mlir::vector::isDisjointTransferSet(), mlir::presburger::LB, mlir::moveLoopInvariantCode(), noAliasingUseInLoop(), mlir::DominanceInfo::properlyDominates(), mlir::presburger::UB, and mlir::Operation::walk().
inferContractionDims() [1/2]
FailureOr< ContractionDimensions > mlir::linalg::inferContractionDims (ArrayRef< AffineMap > indexingMaps)
Definition at line 510 of file LinalgInterfaces.cpp.
References inferContractionDimsImpl(), and inferIteratorsFromOutMap().
inferContractionDims() [2/2]
FailureOr< ContractionDimensions > mlir::linalg::inferContractionDims (LinalgOp linalgOp)
Find at least 2 parallel (m and n) and 1 reduction (k) dimension candidates that form a matmul subcomputation within linalgOp.
These dimensions are such that:
The m dimension is involved in an outer-product along LHS (i.e. it is a permutation on RES and LHS and does not appear in RHS).
The n dimension is involved in an outer-product along RHS (i.e. it is a permutation on RES and RHS and does not appear in LHS).
The k dimension appears as a permutation on LHS and RHS.
m, n and k appear only once in any given indexing.
Optional batch dimensions that appear in all operands are captured. This allows e.g. detecting that some contraction is embedded within linalgOp with some orthogonal heuristic. When multiple dimension occurrences exist that match batch, m, n, or k, indices are returned in sorted order. Returns a failure if any of m, n or k is empty.
Definition at line 502 of file LinalgInterfaces.cpp.
References inferContractionDimsImpl().
Referenced by blockPackMatmul(), mlir::linalg::detail::isContractionInterfaceImpl(), mlir::x86::isInVnniLayout(), mlirLinalgInferContractionDimensions(), mlirLinalgInferContractionDimensionsFromMaps(), packMatmulGreedily(), and validateFullTilesOnDims().
inferConvolutionDims() [1/2]
FailureOr< ConvolutionDimensions > mlir::linalg::inferConvolutionDims (ArrayRef< AffineMap > indexingMaps)
Maps-based overload of inferConvolutionDims.
The indexingMaps are expected in operand order: input, filter, output. The iterator types are inferred from the output map: dimensions that appear in the output are parallel, all others are reduction. Since there is no operation to carry native strides/dilations attributes, the strides and dilations are derived from the convolution access pattern in the input indexing map. Returns a failure if there are not exactly 3 maps, the output map is not a projected permutation, or output_image (and implicitly filter_loop) is empty.
Definition at line 906 of file LinalgInterfaces.cpp.
References inferConvolutionDimsImpl(), and inferIteratorsFromOutMap().
inferConvolutionDims() [2/2]
FailureOr< ConvolutionDimensions > mlir::linalg::inferConvolutionDims (LinalgOp linalgOp)
Find at least 1 parallel (output_image) and reduction (filter_loop) dimension candidates that form a convolution subcomputation within linalgOp.
The LHS is assumed to be the convolution input while the RHS is assumed as the filter. These dimensions are such that:
Optional batch dimensions that appear in the input and filter.
The output_image dimension is involved in a cross-correlation along LHS (i.e. it is a permutation on RES and LHS and has an associated filter_loop in RHS).
Optional output_channel dimension is involved in an outer-product along RHS (i.e. it is a permutation on RES and RHS and does not appear in LHS).
Optional input_channel dimension appears as a permutation on LHS and RHS.
The filter_loop dimension appears as a permutation on the RHS and represents the shape of the kernel cross-correlated along a corresponding output_image dim.
The input_channel dimension appears as a permutation on LHS and RHS.
All dimensions appear only once in any given indexing map. This allows e.g. detecting that some convolution is embedded within linalgOp with some orthogonal heuristic.
The outputImage and filterLoop arrays are ordered such that outputImage[i] pairs with filterLoop[i] based on the convolution access pattern in the input indexing map (e.g., d0 + d2 pairs dimension 0 with dimension 2). Other dimension sets are returned in sorted order.
Returns a failure if output_image (and implicitly filter_loop) is empty.
Definition at line 886 of file LinalgInterfaces.cpp.
References inferConvolutionDimsImpl().
Referenced by downscaleSizeOneWindowedConvolution(), mlirLinalgInferConvolutionDimensions(), and mlirLinalgInferConvolutionDimensionsFromMaps().
inferStaticShape() [1/2]
bool mlir::linalg::inferStaticShape (PackOp packOp, SmallVectorImpl< int64_t > & srcShape, SmallVectorImpl< int64_t > & destShape) static
Returns true if the srcShape or destShape is different from the one in packOp and populates each with the inferred static shape.
Definition at line 5921 of file LinalgOps.cpp.
References mlir::invertPermutationVector().
inferStaticShape() [2/2]
bool mlir::linalg::inferStaticShape (UnPackOp op, SmallVectorImpl< int64_t > & srcShape, SmallVectorImpl< int64_t > & destShape) static
Returns true if the srcShape or destShape is different from the one in op and populates each with the inferred static shape.
Definition at line 6386 of file LinalgOps.cpp.
References mlir::invertPermutationVector().
insertSlicesBack()
SmallVector< Value > mlir::linalg::insertSlicesBack (OpBuilder & builder, Location loc, LinalgOp op, ValueRange operands, ValueRange results)
Creates insert_slice ops that insert results back into larger tensors they were originally extracted from with extract_slice before being passed as operands to the given structured operation op or its clone.
Note that operands are not necessarily the actual operands of op, the operation serves only as metadata container for operand types and positions.
Definition at line 2770 of file Utils.cpp.
References mlir::Value::getDefiningOp(), and inserted().
Referenced by tileLinalgOpImpl().
interchangeGenericOp()
FailureOr< GenericOp > mlir::linalg::interchangeGenericOp (RewriterBase & rewriter, GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Interchange the iterator_types and iterator_maps dimensions and adapts the index accesses of op.
This is an in-place transformation controlled by interchangeVector. An empty vector is interpreted as the identity permutation and the transformation returns early.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed with interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..op.rank without duplications (i.e. [1,1,2] is an invalid permutation).
Return failure if the permutation is not valid.
Definition at line 45 of file Interchange.cpp.
References mlir::applyPermutationToVector(), mlir::AffineMap::compose(), mlir::RewriterBase::finalizeOpModification(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getArrayAttr(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getSubMap(), interchangeGenericOpPrecondition(), mlir::inversePermutation(), mlir::AffineMap::isEmpty(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), and mlir::RewriterBase::startOpModification().
Referenced by packMatmulGreedily().
isaBroadcastOpInterface()
std::optional< SmallVector< int64_t > > mlir::linalg::isaBroadcastOpInterface (LinalgOp linalgOp)
Checks whether linalgOp is semantically equivalent to a broadcast operation.
Returns broadcast dimensions if true.
Definition at line 141 of file LinalgInterfaces.cpp.
Referenced by specializeGenericOp().
isaContractionOpInterface()
bool mlir::linalg::isaContractionOpInterface (LinalgOp linalgOp)
Checks whether linalgOp conforms to ContractionOpInterface.
Definition at line 583 of file LinalgInterfaces.cpp.
References mlir::linalg::detail::isContractionInterfaceImpl(), and mlir::linalg::detail::Success.
Referenced by FoldAddIntoDest::matchAndRewrite(), mlirLinalgIsAContractionOp(), and specializeGenericOp().
isaConvolutionOpInterface()
bool mlir::linalg::isaConvolutionOpInterface (LinalgOp linalgOp, bool allowEmptyConvolvedDims = false)
Checks whether linalgOp conforms to ConvolutionOpInterface.
By default, we require the linalgOp to have non-empty convolved dims (implicitly non-empty output_image and filter_loop). Users can loosen the constraint by setting allowEmptyConvolvedDims to true
Definition at line 1104 of file LinalgInterfaces.cpp.
References mlir::linalg::detail::isConvolutionInterfaceImpl(), and mlir::linalg::detail::Success.
Referenced by mlirLinalgIsAConvolutionOp(), and specializeGenericOp().
isaConvolutionOpOfType()
template<typename ConvOpTy> bool mlir::linalg::isaConvolutionOpOfType (LinalgOp op)
Returns true if the linalg op is a convolution op of type ConvOpTy.
This is a convenience wrapper around matchConvolutionOpOfType.
Definition at line 126 of file Utils.h.
References matchConvolutionOpOfType().
isaCopyOpInterface()
bool mlir::linalg::isaCopyOpInterface (LinalgOp linalgOp)
Checks whether linalgOp is semantically equivalent to a linalg.copyOp.
Definition at line 61 of file LinalgInterfaces.cpp.
References mlir::Block::back(), mlir::Block::getArgument(), and mlir::Block::getOperations().
Referenced by specializeGenericOp().
isaElemwiseSingleBinaryOpInterface()
bool mlir::linalg::isaElemwiseSingleBinaryOpInterface (GenericOp genericOp, bool allowNonIdentityMaps = false)
Checks whether genericOp is semantically equivalent to a single linalg elementwise binary op e.g.
linalg.sub. If allowNonIdentityMaps is true, operations with custom indexing maps are included in the check. Note that these operations can only be represented by the category op.
References mlir::thread_safe_nulls().
Referenced by specializeGenericOp().
isaElemwiseSingleUnaryOpInterface()
bool mlir::linalg::isaElemwiseSingleUnaryOpInterface (GenericOp genericOp, bool allowNonIdentityMaps = false)
Checks whether a given genericOp is semantically equivalent to a single linalg elementwise unary op, e.g.
linalg.exp or linalg.elementwise kind=#linalg.elementwise_kind<exp>. If allowNonIdentityMaps is true, operations with custom indexing maps are included in the check. Note that these operations can only be represented by the category op. A linalg.generic body could be a series of unary elementwise ops e.g. exp(neg(x)), such as formed by linalg op fusion. Here we restrict it to detecting cases where body is is a single computation op.
Referenced by specializeGenericOp().
isaFillOpInterface()
std::optional< Value > mlir::linalg::isaFillOpInterface (GenericOp genericOp)
Checks whether genericOp is semantically equivalent to a linalg.fill.
Supports two patterns:
External: linalg.generic ins(scalar) outs(tensor) { yield scalar }
Inlined: linalg.generic outs(tensor) { yield constant } Returns the scalar fill value if true.
Definition at line 131 of file LinalgInterfaces.cpp.
References isaExternalFillOp(), and isaInlinedFillOp().
Referenced by specializeGenericOp().
isaTransposeOpInterface()
std::optional< SmallVector< int64_t > > mlir::linalg::isaTransposeOpInterface (GenericOp genericOp)
Checks whether genericOp is semantically equivalent to a linalg.transpose.
Returns permuted dimensions if true.
Definition at line 199 of file LinalgInterfaces.cpp.
Referenced by specializeGenericOp().
isDimSequencePreserved()
bool mlir::linalg::isDimSequencePreserved (AffineMap indexingMap, ReassociationIndicesRef dimSequence)
Return true if a given sequence of dimensions are contiguous in the range of the specified indexing map.
For a given dimSequence, check if the sequence is conserved in the indexingMap.
indexingMap is expected to be a projected permutation. Non-existence of the sequence returns true as well.
Definition at line 1307 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), and mlir::AffineMap::isProjectedPermutation().
Referenced by areDimSequencesPreserved().
isDimTimesConstantOrDimOnly()
int64_t mlir::linalg::isDimTimesConstantOrDimOnly (AffineExpr expr, AffineExpr & dim) static
Check if expr is either:
a dimension expr alone (implying multiplication by 1), or
a multiplication of dimension expr by any positive constant != 1 In both cases we will capture the dimension expression into dim and return the constant multiplier. Returns -1 in case of a match failure.
Definition at line 420 of file Utils.cpp.
References mlir::AffineConstantExpr::getValue(), lhs, mlir::Mul, and rhs.
Referenced by matchConvDimAddExprPattern().
isElementwise()
bool mlir::linalg::isElementwise (LinalgOp op)
Check if a LinalgOp is an element-wise operation.
Definition at line 217 of file Utils.cpp.
References allIndexingsAreProjectedPermutation(), and hasOnlyScalarElementwiseOp().
isInvalidPackingPosSpecification()
bool mlir::linalg::isInvalidPackingPosSpecification (ArrayRef< int64_t > dimsPos, size_t rank) static
Returns true if dimsPos is invalid.
It is invalid when: a) It contains duplicate. b) At least one dimension is out of bound (dimPos is >= 0 and < rank). c) The number of elements in dimsPos is > than rank.
Definition at line 5187 of file LinalgOps.cpp.
Referenced by commonVerifierPackAndUnPackOp().
isLikePadUnPad()
template<typename PackOrUnpackOp> bool mlir::linalg::isLikePadUnPad (PackOrUnpackOp packOp, ShapedType packedTensorType) static
Definition at line 6016 of file LinalgOps.cpp.
isParallelIterator()
bool mlir::linalg::isParallelIterator (utils::IteratorType iteratorType)
Check if iterator type has "parallel" semantics.
Definition at line 232 of file Utils.cpp.
Referenced by generateParallelLoopNest(), getCollapsableIterationSpaceDims(), and tileLinalgOpImpl().
isReductionIterator()
bool mlir::linalg::isReductionIterator (utils::IteratorType iteratorType)
Check if iterator type has "reduction" semantics.
Definition at line 236 of file Utils.cpp.
Referenced by getCollapsableIterationSpaceDims(), getDimsToReduce(), hasReductionIterator(), and mlir::sparse_tensor::CodegenEnv::isAdmissibleTensorExp().
linalgOpAnchoredEmptyTensorEliminationStep()
LogicalResult mlir::linalg::linalgOpAnchoredEmptyTensorEliminationStep (RewriterBase & rewriter, Operation * op, bufferization::OneShotAnalysisState & state)
Try to eliminate tensor::EmptyOps inside op that are anchored on a LinalgOp.
This transforms looks for LinalgOps that have an unused output operand and an input operand that is rooted in a tensor::EmptyOp. The tensor::EmptyOp uses are replaced with the output operand and the two operands of the LinalgOp are swapped.
Example: %0 = tensor.empty() %1 = linalg.matmul ins(...) outs(%0) %2 = linalg.generic ins(%1) outs(dest) { ^bb0(in: f32, out: f32): // out not used }
The IR is transformed as follows: %0 = tensor.empty() %1 = linalg.matmul ins(...) outs(dest) %2 = linalg.generic ins(%0) outs(%1) { ^bb0(in: f32, out: f32): // Use out instead of in }
The "ins" operand has no uses inside the body of the LinalgOp and can be folded away with existing cleanup patterns. Afterwards, the tensor::EmptyOp can also fold away.
Definition at line 39 of file EliminateEmptyTensors.cpp.
References mlir::WalkResult::advance(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::Value::getType(), getUnusedOutOperand(), mlir::Value::getUses(), mlir::RewriterBase::modifyOpInPlace(), mlir::DominanceInfo::properlyDominates(), mlir::RewriterBase::replaceAllUsesWith(), mlir::bufferization::OneShotAnalysisState::resetCache(), mlir::IROperand< DerivedT, IRValueT >::set(), mlir::WalkResult::skip(), success(), and mlir::Operation::walk().
linalgOpToAffineLoops()
FailureOr< LinalgLoops > mlir::linalg::linalgOpToAffineLoops (RewriterBase & rewriter, LinalgOp linalgOp)
Emit a loop nest of affine.for with the proper body for linalgOp.
Emits a loop nest of affine.for with the proper body for linalgOp.
Definition at line 363 of file Loops.cpp.
References linalgOpToLoopsImpl().
linalgOpToLoops()
FailureOr< LinalgLoops > mlir::linalg::linalgOpToLoops (RewriterBase & rewriter, LinalgOp linalgOp)
Emit a loop nest of scf.for with the proper body for linalgOp.
Emits a loop nest of scf.for with the proper body for linalgOp.
Definition at line 368 of file Loops.cpp.
References linalgOpToLoopsImpl().
linalgOpToParallelLoops()
FailureOr< LinalgLoops > mlir::linalg::linalgOpToParallelLoops (RewriterBase & rewriter, LinalgOp linalgOp)
Emit a loop nest of scf.parallel with the proper body for linalgOp.
Emits a loop nest of scf.parallel with the proper body for linalgOp.
Definition at line 375 of file Loops.cpp.
References linalgOpToLoopsImpl().
lowerPack()
FailureOr< LowerPackResult > mlir::linalg::lowerPack (RewriterBase & rewriter, linalg::PackOp packOp, bool lowerPadLikeWithInsertSlice = true)
Rewrite pack as pad + reshape + transpose.
Definition at line 221 of file Transforms.cpp.
References mlir::applyPermutationToVector(), mlir::bindDims(), mlir::bindSymbols(), mlir::AffineMap::get(), mlir::Builder::getContext(), mlir::getElementTypeOrSelf(), mlir::Builder::getIndexAttr(), mlir::tensor::getMixedSize(), mlir::tensor::getMixedSizes(), getPackInverseDestPerm(), mlir::Builder::getZeroAttr(), mlir::invertPermutationVector(), mlir::isRankReducedType(), mlir::affine::makeComposedFoldedAffineApply(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::RankedTensorType::Builder::setShape(), stringifyReassocIndices(), and mlir::Success.
lowerUnPack()
FailureOr< LowerUnPackOpResult > mlir::linalg::lowerUnPack (RewriterBase & rewriter, linalg::UnPackOp unPackOp, bool lowerUnpadLikeWithExtractSlice = true)
Rewrite pack as empty + transpose + reshape + extract_slice + copy.
Definition at line 356 of file Transforms.cpp.
References mlir::applyPermutationToVector(), mlir::Builder::getIndexAttr(), mlir::tensor::getMixedSizes(), getUnPackInverseSrcPerm(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::RankedTensorType::Builder::setShape(), and stringifyReassocIndices().
makeAffineDimExprs()
SmallVector< AffineExpr, 4 > mlir::linalg::makeAffineDimExprs (unsigned num, unsigned & startIdx, MLIRContext * context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
Definition at line 2581 of file LinalgOps.cpp.
References mlir::getAffineDimExpr().
makeComposedPadHighOp()
Value mlir::linalg::makeComposedPadHighOp (OpBuilder & b, Location loc, RankedTensorType type, Value source, Value padding, bool nofold, ValueRange typeDynDims = {})
Create a tensor::PadOp that pads source to the shape of type whose sizes are assumed to be greater than the dynamic source size.
If typeDynDims is specified, then it must contain the sizes of all the dynamic dimensions in order of appearance in type, otherwise the function will pad those values to 0. The padding introduces trailing pad values until the target size is met. If source is defined by one or more LinalgOps that have been padded with the same value and sizes, return their padded result instead of creating a tensor::PadOp.
Example:
%0 = tensor.extract_slice %arg0 [%iv0, %iv1] [%sz0, %sz1]
%1 = tensor.pad %0 low[0, 0] high[...] { tensor.yield %cst }
%2 = linalg.matmul ins(...) outs(%1)
%3 = tensor.extract_slice %2 [0, 0] [%sz0, %sz1]
makeComposedPadHighOp(source=%3, pad=cst) returns %2 makeComposedPadHighOp(source=%3, pad=other_cst) returns %4
%4 = tensor.pad %3 low[0, 0] high[...] { tensor.yield %other_cst }
Definition at line 2233 of file Utils.cpp.
References b, mlir::tensor::createPadHighOp(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), mlir::m_Constant(), and mlir::matchPattern().
Referenced by padOperand(), and padOperandToSmallestStaticBoundingBox().
makeMemRefCopyOp()
GenericOp mlir::linalg::makeMemRefCopyOp (OpBuilder & b, Location loc, Value from, Value to)
Returns GenericOp that copies an n-D memref.
Unlike the current implementation of memref::CopyOp, this op can further tile, lower to loops or vectorize.
Definition at line 2301 of file Utils.cpp.
References b, mlir::AffineMap::getMultiDimIdentityMap(), and mlir::Value::getType().
makeTiledLoopRanges()
std::tuple< SmallVector< Range, 4 >, LoopIndexToRangeIndexMap > mlir::linalg::makeTiledLoopRanges (RewriterBase & b, Location loc, AffineMap map, ArrayRef< OpFoldResult > allShapeSizes, ArrayRef< OpFoldResult > allTileSizes)
Definition at line 44 of file Tiling.cpp.
References b, mlir::getConstantIntValue(), mlir::AffineMap::getNumResults(), and mlir::affine::makeComposedFoldedMultiResultAffineApply().
Referenced by tileLinalgOpImpl().
makeTiledShape()
Operation * mlir::linalg::makeTiledShape (OpBuilder & builder, Location loc, Value valueToTile, ArrayRef< OpFoldResult > tileSizes, AffineMap map, ArrayRef< OpFoldResult > lbs, ArrayRef< OpFoldResult > ubs, ArrayRef< OpFoldResult > subShapeSizes, bool omitPartialTileCheck)
Creates an extract_slice/subview op for a single valueToTile with builder.
This new operation extracts a tile of valueToTile, starting at offsets lbs and with sizes subShapeSizes. omitPartialTileCheck controls whether to omit the partial/boundary tile condition check in cases where we statically know that it is unnecessary.
Definition at line 2601 of file Utils.cpp.
References computeSliceParameters(), and materializeTiledShape().
makeTiledShapes()
SmallVector< Value > mlir::linalg::makeTiledShapes (OpBuilder & builder, Location loc, LinalgOp linalgOp, ValueRange valuesToTile, ArrayRef< OpFoldResult > ivs, ArrayRef< OpFoldResult > tileSizes, ArrayRef< OpFoldResult > sizeBounds, bool omitPartialTileCheck)
Creates extract_slice/subview ops for all valuesToTile of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
sizeBounds are the iteration space bounds for all the implicit loops in linalgOp. omitPartialTileCheck controls whether to omit the partial/boundary tile condition check in cases where we statically know that it is unnecessary.
Note that a constant zero in tileSizes means no tiling at that implicit loop. The number of non-zero values in tileSizes should be equal to the number of values in ivs.
Definition at line 2850 of file Utils.cpp.
References computeAllSliceParameters(), and materializeTiledShape().
Referenced by fuse(), and tileLinalgOpImpl().
matchConvDimAddExprPattern()
bool mlir::linalg::matchConvDimAddExprPattern (ArrayAttr indexingMaps, unsigned iDim, unsigned fDim, unsigned oDim, int64_t & dilation, int64_t & stride) static
Given an array of AffineMaps indexingMaps verify the following commutatively:- indexingMaps[0].getResult(iDim) == indexingMaps[1].getResult(fDim) * <c0> + indexingMaps[n-1].getResult(oDim) * <c1> where,.
c0 and c1 can be any constant,
n is the size of the indexingMaps' array,
0, 1 and n-1 are input, filter and output map indices respectively,
iDim, fDim and oDim are the input, filter and output dimension indices in their respective indexing maps Example: #inputMap = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d0, d1 * 2 + d4 * 3, d2 + d5, d6)> #filterMap = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d4, d5, d6, d3)> #outputMap = affine_map<(d0, d1, d2, d3, d4, d5, d6) -> (d0, d1, d2, d3)>
Here, #inputMap[1] = #outputMap[1] * 2 + #filterMap[0] * 3 Therefore, matchConvDimAddExprPattern(indexingMaps, 1, 0, 1, dilation, stride) would return true and update dilation = 3 and stride = 2
Definition at line 462 of file Utils.cpp.
References mlir::Add, getAffineMapDim(), and isDimTimesConstantOrDimOnly().
Referenced by mlir::linalg::ConvMatcherBuilder::matchStride().
matchConvolutionOpOfType()
template<typename ConvOpTy> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType (LinalgOp op)
Given a linalg op this function returns DilationsAndStrides if it is a convolution op of type ConvOpTy, otherwise returns std::nullopt.
The dilations and strides are inferred from the indexing maps. For ops like Conv1DOp, Conv2DOp and Conv3DOp that have no strides/dilations attributes, defaults of [1, ...] are returned for both.
Referenced by isaConvolutionOpOfType().
matchConvolutionOpOfType< linalg::Conv1DNcwFcwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv1DNcwFcwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv1DNwcWcfOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv1DNwcWcfOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv1DOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv1DOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNchwFchwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNchwFchwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNchwFchwQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNchwFchwQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNgchwFgchwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNgchwFgchwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNgchwGfchwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNgchwGfchwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNgchwGfchwQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNgchwGfchwQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNhwcFhwcOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNhwcFhwcOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNhwcFhwcQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNhwcFhwcQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNhwcHwcfOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNhwcHwcfOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNhwcHwcfQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNhwcHwcfQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNhwgcGfhwcOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNhwgcGfhwcOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DNhwgcGfhwcQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DNhwgcGfhwcQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv2DOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv2DOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv3DNcdhwFcdhwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv3DNcdhwFcdhwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv3DNdhwcDhwcfOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv3DNdhwcDhwcfOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv3DNdhwcDhwcfQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv3DNdhwcDhwcfQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::Conv3DOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::Conv3DOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv1DNcwCwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv1DNcwCwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv1DNwcWcmOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv1DNwcWcmOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv1DNwcWcOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv1DNwcWcOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv2DNchwChwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv2DNchwChwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcmOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcmOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcmQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcmQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcQOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv2DNhwcHwcQOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv3DNcdhwCdhwOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv3DNcdhwCdhwOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv3DNdhwcDhwcmOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv3DNdhwcDhwcmOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::DepthwiseConv3DNdhwcDhwcOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::DepthwiseConv3DNdhwcDhwcOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNchwMaxOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNchwMaxOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNchwSumOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNchwSumOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNcwMaxOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNcwMaxOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNcwSumOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNcwSumOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNdhwcMaxOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNdhwcMaxOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNdhwcMinOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNdhwcMinOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNdhwcSumOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNdhwcSumOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNhwcMaxOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNhwcMaxOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNhwcMaxUnsignedOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNhwcMaxUnsignedOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNhwcMinOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNhwcMinOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNhwcMinUnsignedOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNhwcMinUnsignedOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNhwcSumOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNhwcSumOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNwcMaxOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNwcMaxOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNwcMaxUnsignedOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNwcMaxUnsignedOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNwcMinOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNwcMinOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNwcMinUnsignedOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNwcMinUnsignedOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
matchConvolutionOpOfType< linalg::PoolingNwcSumOp >()
template<> std::optional< DilationsAndStrides > mlir::linalg::matchConvolutionOpOfType< linalg::PoolingNwcSumOp > (LinalgOp op)
Definition at line 496 of file Utils.cpp.
materializeTiledShape()
Operation * mlir::linalg::materializeTiledShape (OpBuilder & builder, Location loc, Value valueToTile, const SliceParameters & sliceParams) static
Definition at line 2582 of file Utils.cpp.
References mlir::Value::getType(), mlir::linalg::SliceParameters::offsets, mlir::linalg::SliceParameters::sizes, and mlir::linalg::SliceParameters::strides.
Referenced by makeTiledShape(), and makeTiledShapes().
offsetIndices() [1/2]
void mlir::linalg::offsetIndices (OpBuilder & b, LinalgOp linalgOp, ArrayRef< OpFoldResult > offests)
Add the specified offsets to any linalg.index ops contained in the given linalgOp.
The offsets are provided in the same order as iteration space dimensions. Null offests are assumed to be zero.
Definition at line 2872 of file Utils.cpp.
References b, and offsetIndices().
Referenced by fuse(), offsetIndices(), and transformIndexOps().
offsetIndices() [2/2]
void mlir::linalg::offsetIndices (RewriterBase & b, LinalgOp linalgOp, ArrayRef< OpFoldResult > offests)
Definition at line 2878 of file Utils.cpp.
References b, mlir::bindDims(), mlir::Value::getDefiningOp(), mlir::detail::IROperandBase::getOwner(), mlir::getValueOrCreateConstantIndexOp(), and mlir::affine::makeComposedFoldedAffineApply().
pack()
FailureOr< PackResult > mlir::linalg::pack (RewriterBase & rewriter, linalg::LinalgOp linalgOp, ArrayRef< OpFoldResult > packedSizes)
Implement packing of a single LinalgOp by packedSizes.
Implement packing of a single LinalgOp by performing packing by packedSizes.
There must be one packedSizes entry per linalgOp iterator. Return the packed Linalg op on success, failure otherwise.
Definition at line 480 of file Transforms.cpp.
References mlir::getConstantIntValue(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::Builder::getZeroAttr(), mlir::RewriterBase::notifyMatchFailure(), packLinalgMetadataOnce(), mlir::RewriterBase::replaceOp(), result, and mlir::tile().
Referenced by packMatmulGreedily().
packMatmulGreedily()
FailureOr< PackResult > mlir::linalg::packMatmulGreedily (RewriterBase & rewriter, LinalgOp linalgOp, ArrayRef< OpFoldResult > mnkPackedSizes, ArrayRef< int64_t > mnkPaddedSizesNextMultipleOf, ArrayRef< int64_t > mnkOrder)
Pack a LinalgOp by greedily inferring matmul dimensions (m, n, k) where m and n are proper parallel dimensions and k is a proper reduction dimension.
Packing occurs by rewriting the op as a linalg.generic and calling linalg::pack by mnkPackedSizes. The order of the packed dimensions is customizable: the mnkOrder is a permutation of {0, 1, 2} to reorder {m, n, k} into one of the 8 possible forms. The outer dimensions of the operands are not permuted at this time, this is left for future work.
Definition at line 772 of file Transforms.cpp.
References mlir::bindDims(), mlir::bindSymbols(), mlir::AffineExpr::ceilDiv(), mlir::computePermutationVector(), generalizeNamedOp(), mlir::Builder::getContext(), mlir::Builder::getIndexAttr(), inferContractionDims(), interchangeGenericOp(), mlir::isPermutationVector(), mlir::affine::makeComposedFoldedAffineApply(), mlir::RewriterBase::notifyMatchFailure(), pack(), and mlir::Range::size.
Referenced by blockPackMatmul().
packTranspose()
FailureOr< PackTransposeResult > mlir::linalg::packTranspose (RewriterBase & rewriter, linalg::PackOp packOp, linalg::LinalgOp linalgOp, linalg::UnPackOp maybeUnPackOp, ArrayRef< int64_t > outerPerm, ArrayRef< int64_t > innerPerm)
Transpose a single PackOp -> LinalgOp -> UnPackOp chain and return the transposed PackOp -> LinalgOp -> UnPackOp chain after replacements.
Return failure if either:
the packOp does not have the linalgOp as its unique use.
the maybeUnPackOp, if specified must be a consumer of the result tied to the unique packOp use.
outerPerm (resp. innerPerm) must be valid permutations of packOp.getOuterDimsPerm (resp. packOp.getInnerDimsPerm) or empty.
Definition at line 678 of file Transforms.cpp.
References mlir::RewriterBase::eraseOp(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::isPermutationVector(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), and transposeOneLinalgOperandAndReplace().
Referenced by transposePackedMatmul().
padAndHoistLinalgOp()
FailureOr< LinalgOp > mlir::linalg::padAndHoistLinalgOp (RewriterBase & rewriter, LinalgOp linalgOp, const LinalgPaddingOptions & options)
Apply padding and hoisting to linalgOp according to the configuration specified in options.
Definition at line 355 of file Padding.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), hoistPaddingOnTensors(), mlir::linalg::LinalgPaddingOptions::None, mlir::RewriterBase::notifyMatchFailure(), options, mlir::RewriterBase::replaceOp(), and rewriteAsPaddedOp().
paddingIsNotNeeded()
bool mlir::linalg::paddingIsNotNeeded (PackOp op) static
Returns true if the pack op does not need a padding value.
Definition at line 5904 of file LinalgOps.cpp.
parseIndexingMapsAttr()
FailureOr< ArrayAttr > mlir::linalg::parseIndexingMapsAttr (OpAsmParser & parser) static
Definition at line 4009 of file LinalgOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseEqual(), and mlir::AsmParser::parseOptionalKeyword().
partitionLinalgOpWithShardedReduction()
void mlir::linalg::partitionLinalgOpWithShardedReduction (LinalgOp op, ArrayRef< Value > partitionedOperands, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, ArrayRef< utils::IteratorType > loopIteratorTypes, ArrayRef< SmallVector< GridAxis > > gridAxisAssignmentForLoopIterators, IRMapping & partitionMap, SymbolTableCollection & symbolTable, ImplicitLocOpBuilder & builder) static
Definition at line 204 of file ShardingInterfaceImpl.cpp.
References createAllReduceForResultsWithoutPartialShardings(), createDestinationPassingStyleInitOperands(), getGrid(), mlir::shard::getReductionGridAxes(), mlir::IRMapping::lookup(), mlir::IRMapping::map(), and result.
peelLoop()
SmallVector< Value > mlir::linalg::peelLoop (RewriterBase & rewriter, Operation * op)
Try to peel and canonicalize loop op and return the new result.
Also applies affine_min/max bounds simplification on the fly where relevant.
Definition at line 57 of file Transforms.cpp.
References mlir::Operation::getResults(), and mlir::scf::peelForLoopAndSimplifyBounds().
Referenced by peelLoops().
peelLoops()
void mlir::linalg::peelLoops (RewriterBase & rewriter, ArrayRef< scf::ForOp > loops)
Peel 'loops' and applies affine_min/max bounds simplification on the fly where relevant.
Definition at line 73 of file Transforms.cpp.
References peelLoop().
populateBlockPackMatmulPatterns()
void mlir::linalg::populateBlockPackMatmulPatterns (RewritePatternSet & patterns, const ControlBlockPackMatmulFn & controlFn)
Patterns to block pack Linalg matmul ops.
Definition at line 323 of file BlockPackMatmul.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateBubbleUpExtractSliceOpPatterns()
void mlir::linalg::populateBubbleUpExtractSliceOpPatterns (RewritePatternSet & patterns)
Patterns that are used to bubble up extract slice op above linalg op.
Definition at line 131 of file BubbleUpExtractSlice.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateCollapseDimensions()
void mlir::linalg::populateCollapseDimensions (RewritePatternSet & patterns, const GetCollapsableDimensionsFn & controlCollapseDimensions)
Pattern to collapse dimensions in a linalg.generic op.
This will collapse tensor operands when needed and expand back the result tensors.
Definition at line 2464 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateConstantFoldLinalgOperations()
void mlir::linalg::populateConstantFoldLinalgOperations (RewritePatternSet & patterns, const ControlFusionFn & controlFn)
Patterns to constant fold Linalg operations.
Definition at line 305 of file ConstantFold.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateContractionOpRankReducingPatterns()
void mlir::linalg::populateContractionOpRankReducingPatterns (RewritePatternSet & patterns)
Adds patterns that reduce the rank of named contraction ops that have unit dimensions in the operand(s) by converting to a sequence of collapse_shape, <corresponding linalg named op>, expand_shape (if on tensors).
For example a linalg.batch_matmul with unit batch size will convert to linalg.matmul and a linalg.matvec with with unit spatial dim in lhs will convert to a linalg.dot.
Definition at line 1117 of file DropUnitDims.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateConvertConv2DToImg2ColPatterns()
void mlir::linalg::populateConvertConv2DToImg2ColPatterns (RewritePatternSet & patterns)
Populates patterns to transform linalg.conv_2d_xxx operations into linalg.generic (for img2col packing) and linalg.matmul.
Note: currently limited to Tensor semantics only.
See also
rewriteInIm2Col for more details.
Definition at line 742 of file ConvertConv2DToImg2Col.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateConvertToDestinationStylePatterns()
void mlir::linalg::populateConvertToDestinationStylePatterns (RewritePatternSet & patterns)
Populate patterns that convert non-destination-style ops to destination style ops.
Definition at line 624 of file ConvertToDestinationStyle.cpp.
References mlir::RewritePatternSet::add().
populateConvolutionVectorizationPatterns()
void mlir::linalg::populateConvolutionVectorizationPatterns (RewritePatternSet & patterns, PatternBenefit benefit = 1)
Populate patterns for vectorizing low-D convolution ops.
This is a step in progressive lowering for convolution ops, it assume high-D convolution ops were decomposed previously.
populateDataLayoutPropagationPatterns()
void mlir::linalg::populateDataLayoutPropagationPatterns (RewritePatternSet & patterns, const ControlPropagationFn & controlPackUnPackPropagation, bool PoisonPaddingOk = false)
Patterns to bubble up or down data layout ops across other operations.
The function also has an option to allow the patterns to propagate with poison padding if requested by the caller.
Definition at line 1634 of file DataLayoutPropagation.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateDecomposeConvolutionPatterns()
void mlir::linalg::populateDecomposeConvolutionPatterns (RewritePatternSet & patterns, PatternBenefit benefit = 1)
Linalg decompose convolutions patterns.
Populates patterns to decompose high-D convolution ops into low-D ones. This is a step in progressive lowering for convolution ops, afterwards we can vectorize the low-D convolution ops.
Definition at line 1637 of file Transforms.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateDecomposeLinalgOpsPattern()
void mlir::linalg::populateDecomposeLinalgOpsPattern (RewritePatternSet & patterns, bool removeDeadArgsAndResults = true)
Populate patterns for splitting a LinalgOp with multiple statements within its payload into multiple GenericOp that have a single statement.
The option removeDeadArgsAndResults adds patterns to remove dead arguments and results from the generated decomposed ops. This is default true since the core decomposition patterns relies on these clean up patterns. It is set to false only for testing purposes.
Definition at line 372 of file DecomposeLinalgOps.cpp.
References mlir::RewritePatternSet::getContext(), mlir::RewritePatternSet::insert(), and populateEraseUnusedOperandsAndResultsPatterns().
populateDecomposePackUnpackPatterns()
void mlir::linalg::populateDecomposePackUnpackPatterns (RewritePatternSet & patterns)
Populates patterns to decompose linalg.pack and linalg.unpack Ops into e.g.
tensor.pad, linalg.transpose, tensor.{insert|extract}_slice. Require all outer dims to be unit.
Definition at line 1643 of file Transforms.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateDecomposePadPatterns()
void mlir::linalg::populateDecomposePadPatterns (RewritePatternSet & patterns)
Populates patterns to decompose tensor.pad into e.g.
tensor.empty, linalg.fill, tensor.insert_slice.
Definition at line 1648 of file Transforms.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateDecomposeProjectedPermutationPatterns()
void mlir::linalg::populateDecomposeProjectedPermutationPatterns (RewritePatternSet & patterns)
Add patterns to make explicit broadcasts and transforms in the input operands of a genericOp.
Definition at line 245 of file DecomposeGenericByUnfoldingPermutation.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateDecomposeWinogradOpsPatterns()
void mlir::linalg::populateDecomposeWinogradOpsPatterns (RewritePatternSet & patterns)
Patterns to decompose Winograd operators.
Definition at line 1220 of file WinogradConv2D.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateElementwiseOpsFusionPatterns()
void mlir::linalg::populateElementwiseOpsFusionPatterns (RewritePatternSet & patterns, const ControlFusionFn & controlElementwiseOpFusion)
Patterns for fusing linalg operation on tensors.
Pattern to fuse linalg.generic -> linalg.generic operations when both operations are fusable elementwise operations.
Definition at line 2453 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and populateEraseUnusedOperandsAndResultsPatterns().
populateElementwiseToLinalgConversionPatterns()
void mlir::linalg::populateElementwiseToLinalgConversionPatterns (RewritePatternSet & patterns)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
Definition at line 156 of file ElementwiseToLinalg.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateEraseUnnecessaryInputsPatterns()
void mlir::linalg::populateEraseUnnecessaryInputsPatterns (RewritePatternSet & patterns)
Patterns to promote inputs to outputs and remove unused inputs of linalg.generic ops.
Definition at line 438 of file EraseUnusedOperandsAndResults.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateEraseUnusedOperandsAndResultsPatterns()
void mlir::linalg::populateEraseUnusedOperandsAndResultsPatterns (RewritePatternSet & patterns)
Pattern to remove dead operands and results of linalg.generic operations.
This is a pattern wrapper for deduplicateOperandsAndRemoveDeadResults.
Definition at line 431 of file EraseUnusedOperandsAndResults.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
Referenced by populateDecomposeLinalgOpsPattern(), and populateElementwiseOpsFusionPatterns().
populateExtractSliceSinkingPatterns()
void mlir::linalg::populateExtractSliceSinkingPatterns (RewritePatternSet & patterns, const ControlPropagationFn & controlPackUnPackPropagation)
Patterns to sink extract slice across other operations.
Definition at line 1646 of file DataLayoutPropagation.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateFoldAddIntoDestPatterns()
void mlir::linalg::populateFoldAddIntoDestPatterns (RewritePatternSet & patterns)
Pattern to replace linalg.add when destination passing on a contraction op suffices for achieving the sum.
Definition at line 150 of file FoldAddIntoDest.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateFoldIntoPackAndUnpackPatterns()
void mlir::linalg::populateFoldIntoPackAndUnpackPatterns (RewritePatternSet & patterns, const ControlFoldIntoPackUnpackFn & controlFn = nullptr)
Populates patterns with patterns that fold operations like tensor.pad and tensor.extract_slice into tensor.pack and tensor.unpack operations respectively.
Definition at line 645 of file PackAndUnpackPatterns.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateFoldPackUnpackIntoTensorEmptyPatterns()
void mlir::linalg::populateFoldPackUnpackIntoTensorEmptyPatterns (RewritePatternSet & patterns)
Populates patterns with patterns that fold operations like linalg.pack and linalg.unpack into tensor.empty.
Definition at line 660 of file PackAndUnpackPatterns.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateFoldReshapeOpsByCollapsingPatterns()
void mlir::linalg::populateFoldReshapeOpsByCollapsingPatterns (RewritePatternSet & patterns, const ControlFusionFn & controlFoldingReshapes)
Patterns to fold an expanding tensor.expand_shape operation with its producer generic operation by collapsing the dimensions of the generic op.
Definition at line 2440 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateFoldReshapeOpsByExpansionPatterns()
void mlir::linalg::populateFoldReshapeOpsByExpansionPatterns (RewritePatternSet & patterns, const ControlFusionFn & controlFoldingReshapes)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
Definition at line 2427 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateFoldUnitExtentDimsCanonicalizationPatterns()
void mlir::linalg::populateFoldUnitExtentDimsCanonicalizationPatterns (RewritePatternSet & patterns, linalg::ControlDropUnitDims & options)
Populates canonicalization patterns that simplify IR after folding unit-extent dimensions.
Definition at line 824 of file DropUnitDims.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), options, mlir::tensor::populateFoldTensorEmptyPatterns(), mlir::memref::populateResolveRankedShapedTypeResultDimsPatterns(), mlir::memref::populateResolveShapedTypeResultDimsPatterns(), and mlir::linalg::ControlDropUnitDims::ReassociativeReshape.
populateFoldUnitExtentDimsPatterns()
void mlir::linalg::populateFoldUnitExtentDimsPatterns (RewritePatternSet & patterns, linalg::ControlDropUnitDims & options)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors and memref.
Patterns that are used to canonicalize the use of unit-extent dims for broadcasting.
Note that these patterns should not be used with a greedy driver.
Definition at line 817 of file DropUnitDims.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
populateFuseTensorPadWithProducerLinalgOpPatterns()
void mlir::linalg::populateFuseTensorPadWithProducerLinalgOpPatterns (RewritePatternSet & patterns)
Pattern to fuse a tensor.pad operation with the producer of its source, if the producer is a linalg operation with all parallel iterator types.
Definition at line 120 of file FusePadOpWithLinalgProducer.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateInlineConstantOperandsPatterns()
void mlir::linalg::populateInlineConstantOperandsPatterns (RewritePatternSet & patterns)
Patterns that are used to inline constant operands into linalg generic ops.
Definition at line 98 of file InlineScalarOperands.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateLinalgCategoryToNamedPatterns()
void mlir::linalg::populateLinalgCategoryToNamedPatterns (RewritePatternSet & patterns)
Populates patterns that convert linalg category ops (e.g.
linalg.elementwise, linalg.contract) to equivalent linalg named ops (e.g. linalg.add, linalg.matmul).
Definition at line 100 of file CategoryToNamedOp.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateLinalgFoldIntoElementwisePatterns()
void mlir::linalg::populateLinalgFoldIntoElementwisePatterns (RewritePatternSet & patterns)
Populates patterns with patterns that fold operations like linalg.transform into elementwise op map.
Definition at line 101 of file FoldIntoElementwise.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateLinalgGenericOpsSpecializationPatterns()
void mlir::linalg::populateLinalgGenericOpsSpecializationPatterns (RewritePatternSet & patterns, const GenericOpSpecializationOptions & options = {})
Populates patterns with patterns to convert linalg.generic ops to named or category ops where possible.
A linalg.generic can represent wide range and complex computations for which equivalent linalg named op may not exist e.g. linalg.generic that takes a tensor and computes a polynomial such as: p(x) = an*x^n + ... + a1x + a0 There is no equivalent named op to convert to. Many such cases exist.
Definition at line 819 of file Specialize.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
populateLinalgNamedOpsGeneralizationPatterns()
void mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns (RewritePatternSet & patterns)
Linalg generalization patterns.
Populates patterns with patterns to convert spec-generated named ops to linalg.generic ops.
Definition at line 97 of file Generalization.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateLinalgNamedToElementwisePatterns()
void mlir::linalg::populateLinalgNamedToElementwisePatterns (RewritePatternSet & patterns)
Populates patterns that convert linalg named ops e.g.
linalg.add to equivalent linalg.elementwise.
Definition at line 73 of file NamedToElementwise.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateLinalgTilingCanonicalizationPatterns()
void mlir::linalg::populateLinalgTilingCanonicalizationPatterns (RewritePatternSet & patterns)
Canonicalization patterns relevant to apply after tiling patterns.
These are applied automatically by the tiling pass but need to be applied manually when tiling is called programmatically.
Definition at line 866 of file Tiling.cpp.
populateLinalgToStandardConversionPatterns()
void mlir::linalg::populateLinalgToStandardConversionPatterns (RewritePatternSet & patterns)
Populate the given list with patterns that convert from Linalg to Standard.
Definition at line 126 of file LinalgToStandard.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateMoveInitOperandsToInputPattern()
void mlir::linalg::populateMoveInitOperandsToInputPattern (RewritePatternSet & patterns)
A pattern that converts init operands to input operands.
Definition at line 845 of file DropUnitDims.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populatePadOpVectorizationPatterns()
void mlir::linalg::populatePadOpVectorizationPatterns (RewritePatternSet & patterns, PatternBenefit baseBenefit = 1)
Populates patterns with patterns that vectorize tensor.pad.
These patterns are meant to apply in a complementary fashion. Benefits are used to encode a certain ordering of pattern application. To avoid scattering magic constants throughout the code base, the patterns must be added with this function. baseBenefit can be used to offset the benefit of all tensor::PadOp vectorization patterns by a certain value.
populateSimplifyDepthwiseConvPatterns()
void mlir::linalg::populateSimplifyDepthwiseConvPatterns (RewritePatternSet & patterns)
Patterns to simplify depthwise convolutions.
Definition at line 161 of file SimplifyDepthwiseConv.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateSimplifyPackAndUnpackPatterns()
void mlir::linalg::populateSimplifyPackAndUnpackPatterns (RewritePatternSet & patterns)
Populates patterns with patterns that simplify tensor.pack and tensor.unpack operations.
Definition at line 655 of file PackAndUnpackPatterns.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateSparseTensorRewriting()
void mlir::linalg::populateSparseTensorRewriting (RewritePatternSet & patterns)
Populate patterns that are only useful in the context of sparse tensors.
populateSplitReductionPattern()
void mlir::linalg::populateSplitReductionPattern (RewritePatternSet & patterns, const ControlSplitReductionFn & controlSplitReductionFn, bool useAlloc = false)
Patterns to apply splitReduction below.
Definition at line 448 of file SplitReduction.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateSwapExtractSliceWithFillPatterns()
void mlir::linalg::populateSwapExtractSliceWithFillPatterns (RewritePatternSet & patterns)
Adds patterns that waps tensor.extract_slice(linalg.fill(cst, init)) into linalg.fill(cst, tensor.extract_slice(init)).
Definition at line 42 of file SwapExtractSliceWithFillPatterns.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateTransposeConv2DPatterns()
void mlir::linalg::populateTransposeConv2DPatterns (RewritePatternSet & patterns)
Definition at line 134 of file TransposeConv2D.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateTransposeMatmulPatterns()
void mlir::linalg::populateTransposeMatmulPatterns (RewritePatternSet & patterns, bool transposeLHS = true)
Patterns to convert Linalg matmul ops to transposed variants.
Definition at line 168 of file TransposeMatmul.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateWinogradConv2DPatterns()
void mlir::linalg::populateWinogradConv2DPatterns (RewritePatternSet & patterns, WinogradConv2DFmr fmr)
Patterns to apply Winograd Conv2D algorithm F(m x m, r x r).
Definition at line 1213 of file WinogradConv2D.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
promoteSubviewAsNewBuffer()
FailureOr< PromotionInfo > mlir::linalg::promoteSubviewAsNewBuffer (OpBuilder & b, Location loc, memref::SubViewOp subView, bool useOriginalSubviewSize, const AllocBufferCallbackFn & allocationFn, DataLayout & layout)
Definition at line 237 of file Promotion.cpp.
References b, mlir::ValueBoundsConstraintSet::computeConstantBound(), mlir::arith::ConstantIndexOp::create(), mlir::getValueOrCreateConstantIndexOp(), and mlir::presburger::UB.
Referenced by promoteSubViews().
promoteSubViews()
FailureOr< LinalgOp > mlir::linalg::promoteSubViews (OpBuilder & b, LinalgOp op, const LinalgPromotionOptions & options)
Promote the subViews into a new buffer allocated at the insertion point b.
Promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer.
Take a partial slice of the full view in step 2. and copy into it.
Return the modified linalg op (the modification happens in place) as well as all the copy ops created.
Definition at line 422 of file Promotion.cpp.
References b, mlir::DataLayout::closest(), options, and promoteSubViews().
Referenced by promoteSubViews(), and promoteSubViews().
promoteSubviewsPrecondition()
LogicalResult mlir::linalg::promoteSubviewsPrecondition (Operation * op, LinalgPromotionOptions options)
Promote memref.subviews feeding linalg-on-buffers operations.
Definition at line 400 of file Promotion.cpp.
References options, and success().
registerAll()
template<typename... OpTypes> void mlir::linalg::registerAll (MLIRContext * ctx) static
Variadic helper function.
Definition at line 327 of file ShardingInterfaceImpl.cpp.
References registerOne().
Referenced by registerShardingInterfaceExternalModels(), and registerTilingInterfaceExternalModels().
registerAllDialectInterfaceImplementations()
void mlir::linalg::registerAllDialectInterfaceImplementations (DialectRegistry & registry)
Definition at line 17 of file AllInterfaces.cpp.
References registerBufferizableOpInterfaceExternalModels(), registerShardingInterfaceExternalModels(), registerSubsetOpInterfaceExternalModels(), registerTilingInterfaceExternalModels(), and registerValueBoundsOpInterfaceExternalModels().
Referenced by mlir::registerAllDialects().
registerBufferizableOpInterfaceExternalModels()
void mlir::linalg::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 274 of file BufferizableOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by registerAllDialectInterfaceImplementations().
registerOne()
template<typename OpType> void mlir::linalg::registerOne (MLIRContext * ctx) static
Definition at line 321 of file ShardingInterfaceImpl.cpp.
Referenced by registerAll(), registerAll(), registerShardingInterfaceExternalModels(), and registerTilingInterfaceExternalModels().
registerRuntimeVerifiableOpInterfaceExternalModels()
void mlir::linalg::registerRuntimeVerifiableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 153 of file RuntimeOpVerification.cpp.
References mlir::DialectRegistry::addExtension(), and mlir::MLIRContext::loadDialect().
Referenced by mlir::registerAllDialects().
registerShardingInterfaceExternalModels()
void mlir::linalg::registerShardingInterfaceExternalModels (DialectRegistry & registry)
Definition at line 331 of file ShardingInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension(), mlir::MLIRContext::appendDialectRegistry(), mlir::MLIRContext::getOrLoadDialect(), mlir::DialectRegistry::getRegisteredDialectNames(), mlir::DialectRegistry::insert(), registerAll(), and registerOne().
Referenced by registerAllDialectInterfaceImplementations().
registerSubsetOpInterfaceExternalModels()
void mlir::linalg::registerSubsetOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 72 of file SubsetInsertionOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by registerAllDialectInterfaceImplementations().
registerTilingInterfaceExternalModels()
void mlir::linalg::registerTilingInterfaceExternalModels (DialectRegistry & registry)
Definition at line 1728 of file TilingInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension(), registerAll(), and registerOne().
Referenced by registerAllDialectInterfaceImplementations().
registerTilingInterfaceExternalModelsForPackUnPackOps()
void mlir::linalg::registerTilingInterfaceExternalModelsForPackUnPackOps (DialectRegistry & registry)
Similar to the above registeration, but it is only for tensor.pack and tensor.unpack ops.
Definition at line 1740 of file TilingInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
registerTransformDialectExtension()
void mlir::nvgpu::registerTransformDialectExtension (DialectRegistry & registry)
Definition at line 58 of file DialectExtension.cpp.
References mlir::DialectRegistry::addExtensions().
Referenced by mlir::registerAllExtensions().
registerValueBoundsOpInterfaceExternalModels()
void mlir::linalg::registerValueBoundsOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 54 of file ValueBoundsOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by registerAllDialectInterfaceImplementations().
reifyResultShapesImpl()
template<typename OpTy> LogicalResult mlir::linalg::reifyResultShapesImpl (OpTy op, OpBuilder & builder, ReifiedRankedShapedTypeDims & reifiedReturnShapes) static
Definition at line 5130 of file LinalgOps.cpp.
References createFoldedDimOp(), and success().
rewriteAsPaddedOp() [1/2]
FailureOr< PadTilingInterfaceResult > mlir::linalg::rewriteAsPaddedOp (OpBuilder & builder, TilingInterface toPad, PadTilingInterfaceOptions options, const PadSizeComputationFunction & computePaddingSizeFun = &computeIndexingMapOpInterfacePaddedShape)
Pad the iterator dimensions of toPad.
"options.paddingSizes" indicates that each padding dimension should be padded to the specified padding size.
"options.padToMultipleOf" indicates that the paddingSizes should be
Use "options.paddingValues" to set the padding value of the created
Definition at line 266 of file PadTilingInterface.cpp.
References mlir::clone(), DBGS, mlir::Value::getDefiningOp(), mlir::getElementTypeOrSelf(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), mlir::Builder::getZeroAttr(), options, padOperand(), mlir::reifyResultShapes(), and ValueRange.
rewriteAsPaddedOp() [2/2]
LogicalResult mlir::linalg::rewriteAsPaddedOp (RewriterBase & rewriter, LinalgOp opToPad, const LinalgPaddingOptions & options, LinalgOp & paddedOp, SmallVector< Value > & replacements, SmallVector< tensor::PadOp > & padOps)
Pad the iterator dimensions options.paddingDimensions of all opToPad operands to a static bounding box.
The original opToPad is cloned and operates on the padded tensors.
"options.padToMultipleOf" indicates that each padding dimension should be padded to the specified multiple.
Use "options.paddingValues" and "options.nofoldFlags" to set padding value and nofold attribute of the created tensor::PadOps, respectively.
The unpadded results (extracted slice of the cloned operation) are returned via replacements.
The tensor::PadOps are returned via padOps.
"options.copyBackOp" specifies the op type for copying back the unpadded result to the original destination tensor.
Definition at line 244 of file Padding.cpp.
References mlir::clone(), DBGS, mlir::get(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), mlir::Builder::getZeroAttr(), mlir::linalg::LinalgPaddingOptions::LinalgCopy, mlir::linalg::LinalgPaddingOptions::None, mlir::RewriterBase::notifyMatchFailure(), options, padOperandToSmallestStaticBoundingBox(), mlir::reifyResultShapes(), mlir::OpBuilder::setInsertionPointAfter(), success(), and ValueRange.
Referenced by padAndHoistLinalgOp().
rewriteInDestinationPassingStyle() [1/3]
FailureOr< Operation * > mlir::linalg::rewriteInDestinationPassingStyle (RewriterBase & rewriter, tensor::FromElementsOp fromElementsOp)
Rewrite tensor.from_elements to linalg.generic.
Lower tensor.from_elements to a sequence of chained tensor.insert.
Definition at line 359 of file ConvertToDestinationStyle.cpp.
References mlir::arith::ConstantIndexOp::create(), createInserts(), indices, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), result, and ValueRange.
rewriteInDestinationPassingStyle() [2/3]
FailureOr< Operation * > mlir::linalg::rewriteInDestinationPassingStyle (RewriterBase & rewriter, tensor::GenerateOp generateOp)
Rewrite tensor.generate to linalg.generic.
Lower tensor.generate to linalg.generic.
Definition at line 397 of file ConvertToDestinationStyle.cpp.
References mlir::OpBuilder::createBlock(), mlir::Builder::getMultiDimIdentityMap(), mlir::RewriterBase::mergeBlocks(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToStart(), and ValueRange.
rewriteInDestinationPassingStyle() [3/3]
FailureOr< Operation * > mlir::linalg::rewriteInDestinationPassingStyle (RewriterBase & rewriter, tensor::PadOp padOp)
Rewrite tensor.pad to linalg.generic + tensor.insert_slice.
Lower tensor.pad to linalg.generic + tensor.insert_slice.
Definition at line 438 of file ConvertToDestinationStyle.cpp.
References mlir::Builder::getIndexAttr(), mlir::tensor::getMixedSizes(), mlir::Operation::getResult(), mlir::isZeroInteger(), movePaddingToFillOrGenericOp(), mlir::RewriterBase::notifyMatchFailure(), mlir::reifyResultShapes(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::OpBuilder::setInsertionPointAfter().
rewriteInIm2Col() [1/4]
FailureOr< std::pair< Operation *, Operation * > > mlir::linalg::rewriteInIm2Col (RewriterBase & rewriter, linalg::Conv2DNchwFchwOp convOp)
Similar to rewriteInIm2Col with linalg::Conv2DNhwcHwcfOp except because the channels are to the left of the image shape dimensions, the position of the contraction dimension in the resulting matmul is reversed.
This swaps the LHS and RHS of the matmul when compared with nhwc (i.e. (D, C x Kh x Kw) * (C x Kh x Kw, Ho x Wo))
Definition at line 417 of file ConvertConv2DToImg2Col.cpp.
References add, mlir::bindDims(), mlir::linalg::Im2ColToInputDimsExprs::bIndex, mlir::linalg::Im2ColToInputDimsExprs::cIndex, createAdd(), createMul(), mlir::delinearize(), mlir::linalg::Im2ColToOperandsExprs::fhIndex, mlir::linalg::Im2ColToOperandsExprs::fwIndex, mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), getIm2ColInputExpressions(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::getType(), mlir::Value::getType(), hasAllOneValues(), mlir::linalg::Im2ColToInputDimsExprs::hIndex, mlir::linalg::Im2ColToOperandsExprs::icIndex, mlir::AffineMap::inferFromExprList(), mul, mlir::RewriterBase::notifyMatchFailure(), mlir::linalg::Im2ColToOperandsExprs::ohIndex, mlir::linalg::Im2ColToOperandsExprs::owIndex, mlir::RewriterBase::replaceOp(), result, and mlir::linalg::Im2ColToInputDimsExprs::wIndex.
rewriteInIm2Col() [2/4]
FailureOr< std::pair< Operation *, Operation * > > mlir::linalg::rewriteInIm2Col (RewriterBase & rewriter, linalg::Conv2DNhwcFhwcOp convOp)
Same as the above but for Fhwc channel orderings in the filter.
In this case the matrix multiplication is actually a row-wise dot-product rather than a row-column dot-product. This is to avoid transposing the filter matrix which would be required for a regular matrix multiplication to produce the correct output dimensions.
Definition at line 551 of file ConvertConv2DToImg2Col.cpp.
References add, mlir::bindDims(), mlir::linalg::Im2ColToInputDimsExprs::bIndex, mlir::linalg::Im2ColToInputDimsExprs::cIndex, createAdd(), createMul(), mlir::delinearize(), mlir::linalg::Im2ColToOperandsExprs::fhIndex, mlir::linalg::Im2ColToOperandsExprs::fwIndex, mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), getIm2ColInputExpressions(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::getType(), mlir::Value::getType(), hasAllOneValues(), mlir::linalg::Im2ColToInputDimsExprs::hIndex, mlir::linalg::Im2ColToOperandsExprs::icIndex, mlir::AffineMap::inferFromExprList(), mul, mlir::RewriterBase::notifyMatchFailure(), mlir::linalg::Im2ColToOperandsExprs::ohIndex, mlir::linalg::Im2ColToOperandsExprs::owIndex, mlir::RewriterBase::replaceOp(), result, and mlir::linalg::Im2ColToInputDimsExprs::wIndex.
rewriteInIm2Col() [3/4]
FailureOr< std::pair< Operation *, Operation * > > mlir::linalg::rewriteInIm2Col (RewriterBase & rewriter, linalg::Conv2DNhwcHwcfOp convOp)
Convert linalg.conv_2d_nhwc_hwcf into linalg.generic (for img2col packing) and linalg.matmul.
A convolution operation can be written as a matrix-matrix multiplication by unfolding the cross-correlation between input and filter and explicitly copy overlapped sliding window inputs.
Consider 2D input X with single channel input and output and 2x2 filter W: [x(0, 0) , x(0, 1) , ..., x(0, n) ] [x(1, 0) , x(1, 1) , ..., x(1, n) ] [. , . ,. , . ] [w(0, 0), w(0, 1)] [. , . , . , . ] (conv) [w(1, 0), w(1, 1)] [. , . , ., . ] [x(n-1, 0), x(n-1, 1), ..., x(n-1, n-1)]
The packed input data (img2col) is a matrix with |rows| = output spatial size, |columns| = filter spatial size. To compute the output Y(i, j) we need to calculate the dot product between filter window at input X(x, y)) and the filter which will look like the following where r.h.s is the img2col matrix and l.h.s is the flattened filter:
[x(0,0), x(0,1), x(1,0), x(1,1)] [x(0,1), x(1,1), x(0,2), x(1,2)] (matmul) [w(0,0), w(0,1), w(1,0), w(1,1)] [x(0,1), x(1,1), x(0,2), x(1,2)] [ . , . , . , . ]
In general for 2D case with (N, H, W, C) input and (Kh, Kw, C, D) filter and output (N, Ho, Wo, D) the convolution is the following matrix-matrix multiplication (Ho x Wo, Kh x Kw x C) * (Kh x Kw x C, D) for each input in the N input. For the case where N > 1 its a batched matrix-matrix multiplication.
On success, return both the operation that produces the img2col tensor and the final operation of the sequence that replaces the original convolution.
Definition at line 124 of file ConvertConv2DToImg2Col.cpp.
References add, mlir::bindDims(), mlir::linalg::Im2ColToInputDimsExprs::bIndex, mlir::linalg::Im2ColToInputDimsExprs::cIndex, createAdd(), createMul(), mlir::delinearize(), mlir::linalg::Im2ColToOperandsExprs::fhIndex, mlir::linalg::Im2ColToOperandsExprs::fwIndex, mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), getIm2ColInputExpressions(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::getType(), mlir::Value::getType(), hasAllOneValues(), mlir::linalg::Im2ColToInputDimsExprs::hIndex, mlir::linalg::Im2ColToOperandsExprs::icIndex, mlir::AffineMap::inferFromExprList(), mul, mlir::RewriterBase::notifyMatchFailure(), mlir::linalg::Im2ColToOperandsExprs::ohIndex, mlir::linalg::Im2ColToOperandsExprs::owIndex, mlir::RewriterBase::replaceOp(), result, and mlir::linalg::Im2ColToInputDimsExprs::wIndex.
rewriteInIm2Col() [4/4]
FailureOr< std::pair< Operation *, Operation * > > mlir::linalg::rewriteInIm2Col (RewriterBase & rewriter, linalg::DepthwiseConv2DNhwcHwcOp convOp)
Similar to rewriteInIm2Col with linalg::Conv2DNhwcHwcfOp except there is no reduction among the input channels so each convolution can be a matrix-vector product and by transposing both input filter so channels are outer most the computation is a batched matrix-vector product.
Definition at line 261 of file ConvertConv2DToImg2Col.cpp.
References mlir::bindDims(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::Value::getType(), hasAllOneValues(), indices, mlir::inversePermutation(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOp().
specializeGenericOp()
FailureOr< LinalgOp > mlir::linalg::specializeGenericOp (RewriterBase & rewriter, GenericOp genericOp, const GenericOpSpecializationOptions & options = {})
Replace the given GenericOp with a namedOp or categoryOp.
Definition at line 731 of file Specialize.cpp.
References isaBroadcastOpInterface(), isaContractionOpInterface(), isaConvolutionOpInterface(), isaCopyOpInterface(), isaElemwiseSingleBinaryOpInterface(), isaElemwiseSingleUnaryOpInterface(), isaFillOpInterface(), isaTransposeOpInterface(), mlir::RewriterBase::notifyMatchFailure(), options, mlir::RewriterBase::replaceOpWithNewOp(), and specializeLinalgElementwise().
Referenced by downscaleSizeOneWindowedConvolution(), and mlir::linalg::LinalgSpecializationPattern::returningMatchAndRewrite().
splitOp()
std::pair< TilingInterface, TilingInterface > mlir::linalg::splitOp (RewriterBase & rewriter, TilingInterface op, unsigned dimension, OpFoldResult splitPoint)
Split the given op into two parts along the given iteration space dimension at the specified splitPoint, and return the two parts.
If the second part is statically known to be empty, do not create it and return nullptr instead. Error state is signalled by returning a pair of nullptrs.
For example, the following op:
linalg.matmul ins(%0, %1 : tensor<128x32xf32>, tensor<32x64xf32>) outs(%2 : tensor<128x64xf32>)
split along the first dimension at position 42 will result in:
%3 = tensor.extract_slice %0[0, 0][42, 32][1, 1] %4 = tensor.extract_slice %2[0, 0][42, 64][1, 1] %5 = linalg.matmul ins(%3, %1 : tensor<42x32xf32>, tensor<32x64xf32>) outs(%5 : tensor<42x64xf32>) %6 = tensor.insert_slice %5 into %2[0, 0][42, 64][1, 1]
%7 = tensor.extract_slice %0[42, 0][86, 32][1, 1] %8 = tensor.extract_slice %6[42, 0][86, 64][1, 1] %9 = linalg.matmul ins(%7, %1 : tensor<86x32xf32>, tensor<32x64xf32>) outs(%8 : tensor<86x64xf32>) tensor.insert_slice %5 into %6[42, 0][86, 64][1, 1]
Note that there is no simplification other than constant propagation applied to slice extraction and insertion.
Definition at line 68 of file Split.cpp.
References mlir::bindDims(), createSplitPart(), mlir::Builder::getContext(), mlir::tensor::getOrCreateDestinations(), mlir::AffineMap::inferFromExprList(), mlir::affine::makeComposedFoldedAffineApply(), mlir::affine::makeComposedFoldedAffineMin(), mlir::RewriterBase::modifyOpInPlace(), mlir::Range::offset, mlir::RewriterBase::replaceOp(), and mlir::Range::size.
splitReduction()
FailureOr< SplitReductionResult > mlir::linalg::splitReduction (RewriterBase & b, LinalgOp op, const ControlSplitReductionFn & controlSplitReductionFn, bool useAlloc = false)
Definition at line 30 of file SplitReduction.cpp.
References b, mlir::AffineMap::get(), mlir::Value::getDefiningOp(), mlir::AffineMap::getDimPosition(), mlir::arith::getNeutralElement(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::linalg::SplitReductionOptions::index, mlir::linalg::SplitReductionOptions::innerParallel, mlir::matchReduction(), mlir::linalg::SplitReductionOptions::ratio, mlir::Operation::setOperand(), TypeRange, and ValueRange.
splitReductionByScaling()
FailureOr< SplitReductionResult > mlir::linalg::splitReductionByScaling (RewriterBase & b, LinalgOp op, const ControlSplitReductionFn & controlSplitReductionFn, bool useAlloc = false)
Scaling-based implementation of the split reduction transformation.
Core rewrite implementation.
Instead of introducing an ExpandShapeOp, this rewrites a reduction dimension k into k * scale + kk.
Example:
%0 = linalg.matmul ins(%A, %B: tensor<16x256xf32>, tensor<256x32xf32>)
  outs(%C: tensor<16x32xf32>) -> tensor<16x32xf32>
Is transformed to:
     #map0 = affine_map<(d0, d1, d2, d3) -> (d0, d2 * 4 + d3)>
     #map1 = affine_map<(d0, d1, d2, d3) -> (d2 * 4 + d3, d1)>
     #map2 = affine_map<(d0, d1, d2, d3) -> (d2, d3)>
     #map3 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>
     #map4 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
     #map5 = affine_map<(d0, d1, d2) -> (d0, d1)>
     %0 = tensor.empty [16, 32, 64] : tensor<16x32x64xf32>
     %cst = arith.constant 0.000000e+00 : f32
     %1 = linalg.fill ins(%cst : f32) outs(%0 : tensor<16x32x64xf32>) ->
        tensor<16x32x64xf32>
     %2 = tensor.empty [64, 4] : tensor<64x4xi1>
     %3 = linalg.generic {indexing_maps = [#map0, #map1, #map2, #map3],
       iterator_types = ["parallel", "parallel", "parallel", "reduction"]}
       ins(%A, %B, %2 : tensor<16x256xf32>, tensor<256x32xf32>,
       tensor<64x4xi1>)
      outs(%1 : tensor<16x32x64xf32>) {
         ^bb0(%arg3: f32, %arg4: f32, %arg5: i1, %arg6: f32):
           %5 = arith.mulf %arg3, %arg4 : f32
           %6 = arith.addf %arg6, %5 : f32
           linalg.yield %6 : f32
     } -> tensor<16x32x64xf32>
     %4 = linalg.generic {indexing_maps = [#map4, #map5],
       iterator_types = ["parallel", "parallel", "reduction"]} */
//     ins(%3 : tensor<16x32x64xf32>)
/**    outs(%C : tensor<16x32xf32>) {
         ^bb0(%arg3: f32, %arg4: f32):
           %5 = arith.addf %arg3, %arg4 : f32
           linalg.yield %5 : f32
     } -> tensor<16x32xf32>
     return %4 : tensor<16x32xf32>
Definition at line 241 of file SplitReduction.cpp.
References b, mlir::tensor::createDynamicDimValues(), mlir::AffineMap::dropResult(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Value::getDefiningOp(), mlir::arith::getNeutralElement(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::linalg::SplitReductionOptions::index, mlir::linalg::SplitReductionOptions::innerParallel, mlir::RankedTensorType::Builder::insertDim(), insertParallelDim(), mlir::matchReduction(), mlir::linalg::SplitReductionOptions::ratio, scaleReductionDim(), mlir::Operation::setOperand(), and ValueRange.
tileLinalgOp()
FailureOr< TiledLinalgOp > mlir::linalg::tileLinalgOp (RewriterBase & b, LinalgOp op, const LinalgTilingOptions & options)
Definition at line 816 of file Tiling.cpp.
References b, Loops, options, ParallelLoops, and tileLinalgOpImpl().
tileReductionUsingForall()
FailureOr< linalg::ForallReductionTilingResult > mlir::linalg::tileReductionUsingForall (RewriterBase & b, PartialReductionOpInterface op, ArrayRef< OpFoldResult > numThreads, ArrayRef< OpFoldResult > tileSizes = {}, std::optional< ArrayAttr > mapping = std::nullopt)
Method to tile a reduction to parallel iterations computing partial reductions.
After the loop all the partial reduction are merged into a final reduction. For example for the following sequence
%0 = linalg.generic %in ["parallel", "reduction"]
  : tensor<7x9xf32> -> tensor<7xf32>
into:
%0 = linalg.fill ... : tensor<7x4xf32>
%1 = scf.forall (%iv) in (%c4) shared_outs(%arg0 = %0)
  -> (tensor<7x4xf32>) {
  %2 = tensor.extract_slice %arg3 : tensor<7x4xf32> to tensor<7xf32>
  %3 = tensor.extract_slice %in : tensor<7x9xf32> -> tensor<7x?xf32>
  %4 = linalg.generic %2, %3 ["parallel", "reduction"]
    : tensor<7x?xf32> -> tensor<7xf32>
  %5 = tensor.insert_slice %3, %arg0[0, %iv] : tensor<7x4xf32>
}
%6 = linalg.generic %1 ["parallel", "reduction"]
  : tensor<7x4xf32> -> tensor<7xf32>
Definition at line 588 of file Tiling.cpp.
References b, calculateTileOffsetsAndSizes(), mlir::Operation::emitError(), mlir::getAsOpFoldResult(), mlir::tensor::getOrCreateDestinations(), mlir::getValueOrCreateConstantIndexOp(), mlir::linalg::ForallReductionTilingResult::initialValues, mlir::isZeroInteger(), mlir::linalg::ForallReductionTilingResult::loops, mlir::linalg::ForallReductionTilingResult::mergeOps, options, mlir::linalg::ForallReductionTilingResult::parallelTiledOps, result, and tileLinalgOpImpl().
transformIndexOps()
void mlir::linalg::transformIndexOps (RewriterBase & b, LinalgOp op, SmallVectorImpl< Value > & ivs, const LoopIndexToRangeIndexMap & loopIndexToRangeIndex)
All indices returned by IndexOp should be invariant with respect to tiling.
Therefore, if an operation is tiled, we have to transform the indices accordingly, i.e. offset them by the values of the corresponding induction variables that are captured implicitly in the body of the op.
Example. linalg.generic before tiling:
#id_2d = (i, j) -> (i, j) #pointwise_2d_trait = { indexing_maps = [#id_2d, #id_2d], iterator_types = ["parallel", "parallel"] } linalg.generic #pointwise_2d_trait operand, result { ^bb0(operand_in: f32, result_in: f32): i = linalg.index 0 : index j = linalg.index 1 : index <some operations that use i, j> }: memref<50x100xf32>, memref<50x100xf32>
After tiling pass with tiles sizes 10 and 25:
#strided = (i, j)[s0, s1, s2] -> (i * s1 + s0 + j * s2)
c1 = arith.constant 1 : index c0 = arith.constant 0 : index c25 = arith.constant 25 : index c10 = arith.constant 10 : index operand_dim_0 = dim operand, 0 : memref<50x100xf32> operand_dim_1 = dim operand, 1 : memref<50x100xf32> scf.for k = c0 to operand_dim_0 step c10 { scf.for l = c0 to operand_dim_1 step c25 { %4 = memref.subview operand[k, l][c10, c25][c1, c1] : memref<50x100xf32> to memref<?x?xf32, #strided> %5 = memref.subview result[k, l][c10, c25][c1, c1] : memref<50x100xf32> to memref<?x?xf32, #strided> linalg.generic pointwise_2d_trait %4, %5 { ^bb0(operand_in: f32, result_in: f32): i = linalg.index 0 : index j = linalg.index 1 : index // Indices k and l are implicitly captured in the body. transformed_i = arith.addi i, k : index // index i is offset by k transformed_j = arith.addi j, l : index // index j is offset by l // Every use of i, j is replaced with transformed_i, transformed_j <some operations that use transformed_i, transformed_j> }: memref<?x?xf32, #strided>, memref<?x?xf32, #strided> } }
TODO: Investigate whether mixing implicit and explicit indices does not lead to losing information.
Definition at line 73 of file Tiling.cpp.
References b, mlir::getAsOpFoldResult(), and offsetIndices().
Referenced by tileLinalgOpImpl().
transposeBatchMatmul()
FailureOr< Operation * > mlir::linalg::transposeBatchMatmul (RewriterBase & rewriter, linalg::BatchMatmulOp batchMatmulOp, bool transposeLHS = true)
Pattern to replace.
linalg.batch_matmul(a, b)
with
linalg.batch_matmul_transpose_a(linalg.transpose(a), b)
Only the non-batch dimensions are transposed. By default the LHS is transposed. Set transposeLHS=false to transpose RHS instead.
Definition at line 87 of file TransposeMatmul.cpp.
References mlir::linalg::BatchMatmulTransposeAOp::create(), mlir::linalg::BatchMatmulTransposeBOp::create(), mlir::Value::getType(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOp().
transposeConv2D() [1/2]
FailureOr< Operation * > mlir::linalg::transposeConv2D (RewriterBase & rewriter, linalg::Conv2DNhwcFhwcOp op)
Convert linalg.conv_2d_nhwc_fhwc(_q) to linalg.conv_2d_nhwc_hwcf(_q) by materializing transpose.
Definition at line 120 of file TransposeConv2D.cpp.
transposeConv2D() [2/2]
FailureOr< Operation * > mlir::linalg::transposeConv2D (RewriterBase & rewriter, linalg::Conv2DNhwcFhwcQOp op)
Definition at line 127 of file TransposeConv2D.cpp.
transposeMatmul()
FailureOr< Operation * > mlir::linalg::transposeMatmul (RewriterBase & rewriter, linalg::MatmulOp matmulOp, bool transposeLHS = true)
Convert Linalg matmul ops to transposed variants.
Pattern to replace.
linalg.matmul(a, b)
with
linalg.matmul_transpose_a(linalg.transpose(a), b)
By default the LHS is transposed. Set transposeLHS=false to transpose RHS instead.
Definition at line 30 of file TransposeMatmul.cpp.
References mlir::linalg::MatmulTransposeAOp::create(), mlir::linalg::MatmulTransposeBOp::create(), mlir::Value::getType(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOp().
updateBoundsForCyclicDistribution()
void mlir::linalg::updateBoundsForCyclicDistribution (OpBuilder & builder, Location loc, Value procId, Value nprocs, Value & lb, Value & ub, Value & step)
Update the lb, ub and step to get per processor lb, ub and step.
Definition at line 2400 of file Utils.cpp.
References b, mlir::bindDims(), mlir::getAffineSymbolExpr(), and mlir::affine::makeComposedAffineApply().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
vectorize()
FailureOr< VectorizationResult > mlir::linalg::vectorize (RewriterBase & rewriter, Operation * op, ArrayRef< int64_t > inputVectorSizes = {}, ArrayRef< bool > inputScalableVecDims = {}, bool vectorizeNDExtract = false, bool flatten1DDepthwiseConv = false, bool assumeDynamicDimsMatchVecSizes = false, bool createNamedContraction = false)
Returns a VectorizationResult containing the results of the vectorized op, or failure if the transformation fails.
If provided, inputVectorSizes are used to vectorize this operation. inputVectorSizes must match the rank of the iteration space of the operation and the input vector sizes must be greater than or equal to their counterpart iteration space sizes, if static. inputVectorShapes also allows the vectorization of operations with dynamic shapes. Optionally, createNamedContraction can force compatible contractions to be vectorized directly to vector.contract operation.
vectorizeCopy()
LogicalResult mlir::linalg::vectorizeCopy (RewriterBase & builder, memref::CopyOp copyOp)
Emit a suitable vector form for a Copy op with fully static shape.
Referenced by mlir::linalg::CopyVectorizationPattern::matchAndRewrite().
vectorizeOpPrecondition()
LogicalResult mlir::linalg::vectorizeOpPrecondition (Operation * op, ArrayRef< int64_t > inputVectorSizes = {}, ArrayRef< bool > inputScalableVecDims = {}, bool vectorizeNDExtract = false, bool flatten1DDepthwiseConv = false)
Return success if the operation can be vectorized.
winogradConv2D() [1/2]
FailureOr< Operation * > mlir::linalg::winogradConv2D (RewriterBase & rewriter, linalg::Conv2DNhwcFhwcOp op, linalg::WinogradConv2DFmr fmr)
Definition at line 1189 of file WinogradConv2D.cpp.
winogradConv2D() [2/2]
FailureOr< Operation * > mlir::linalg::winogradConv2D (RewriterBase & rewriter, linalg::Conv2DNhwcFhwcOp op, WinogradConv2DFmr fmr)
Convert linalg.conv_2d_nhwc_fhwc to Winograd Conv2D algorithm F(m x m, r x r).
m is the dimension size of output and r is the dimension size of filter.