MLIR: mlir::remark Namespace Reference
mlir::remark Namespace Reference
Namespaces
detail
Classes
struct RemarkCategories
Define an the set of categories to accept.
struct RemarkOpts
Options to create a Remark.
Enumerations
enum class RemarkKind {
RemarkUnknown = 0 , RemarkPassed , RemarkMissed , RemarkFailure ,
RemarkAnalysis
}
Categories describe the outcome of an transformation, not the mechanics of emitting/serializing remarks.
Functions
template<class... Ts>
detail::LazyTextBuild reason (const char *fmt, Ts &&...ts)
Create a Reason with llvm::formatv formatting.
template<class... Ts>
detail::LazyTextBuild suggest (const char *fmt, Ts &&...ts)
Create a Suggestion with llvm::formatv formatting.
template<class... Ts>
detail::LazyTextBuild add (const char *fmt, Ts &&...ts)
Create a Remark with llvm::formatv formatting.
template<class V >
detail::LazyTextBuild metric (StringRef key, V &&v)
detail::InFlightRemark passed (Location loc, RemarkOpts opts)
Report an optimization remark that was passed.
detail::InFlightRemark missed (Location loc, RemarkOpts opts)
Report an optimization remark that was missed.
detail::InFlightRemark failed (Location loc, RemarkOpts opts)
Report an optimization remark that failed.
detail::InFlightRemark analysis (Location loc, RemarkOpts opts)
Report an optimization analysis remark.
LogicalResult enableOptimizationRemarks (MLIRContext &ctx, std::unique_ptr< remark::detail::MLIRRemarkStreamerBase > streamer, const remark::RemarkCategories &cats, bool printAsEmitRemarks=false)
Setup remarks for the context.
LogicalResult enableOptimizationRemarksWithLLVMStreamer (MLIRContext &ctx, StringRef filePath, llvm::remarks::Format fmt, const RemarkCategories &cat, bool printAsEmitRemarks=false)
Enable optimization remarks to a file with the given path and format.
Enumeration Type Documentation
RemarkKind
enum mlir::remark::RemarkKind strong
Categories describe the outcome of an transformation, not the mechanics of emitting/serializing remarks.
Enumerator
RemarkUnknown
RemarkPassed
An optimization was applied.
RemarkMissed
A profitable optimization opportunity was found but not applied.
RemarkFailure
The compiler attempted the optimization but failed (e.g., legality checks, or better opportunites).
RemarkAnalysis
Informational context (e.g., analysis numbers) without a pass/fail outcome.
Definition at line 37 of file Remarks.h.
Function Documentation
add()
template<class... Ts> detail::LazyTextBuild mlir::remark::add (const char * fmt, Ts &&... ts) inline
Create a Remark with llvm::formatv formatting.
Definition at line 463 of file Remarks.h.
Referenced by convertAcoshOp(), convertAsinhOp(), convertAtanhOp(), convertCoshOp(), convertCtlzOp(), convertFmaFOp(), convertRoundOp(), declareReduction(), genInsertionStore(), mlir::sparse_tensor::genMapBuffers(), isPairTemplateImpl(), mlir::sparse_tensor::Merger::optimizeSet(), and mlir::linalg::rewriteInIm2Col().
analysis()
detail::InFlightRemark mlir::remark::analysis (Location loc, RemarkOpts opts) inline
Report an optimization analysis remark.
Definition at line 497 of file Remarks.h.
References mlir::remark::detail::RemarkEngine::emitOptimizationRemarkAnalysis(), and mlir::remark::detail::withEngine().
Referenced by mlir::AliasAnalysis::addAnalysisImplementation(), mlir::AnalysisState::addDependency(), mlir::dataflow::Executable::blockContentSubscribe(), mlir::linalg::detail::buildPackingLoopNest(), buildPackingLoopNestImpl(), mlir::detail::AnalysisMap::getCachedAnalysis(), mlir::linalg::hoistPaddingOnTensors(), mlir::DataFlowSolver::initializeAndRun(), mlir::detail::analysis_impl::isInvalidated(), mlir::dataflow::Executable::onUpdate(), mlir::dataflow::AbstractSparseLattice::onUpdate(), potentiallyAliasesMemref(), replaceByPackingResult(), and mlir::dataflow::AbstractSparseLattice::useDefSubscribe().
enableOptimizationRemarks()
LogicalResult mlir::remark::enableOptimizationRemarks (MLIRContext & ctx, std::unique_ptr< remark::detail::MLIRRemarkStreamerBase > streamer, const remark::RemarkCategories & cats, bool printAsEmitRemarks = false)
Setup remarks for the context.
This function will enable the remark engine and set the streamer to be used for optimization remarks. The remark categories are used to filter the remarks that will be emitted by the remark engine. If a category is not specified, it will not be emitted. If printAsEmitRemarks is true, the remarks will be printed as mlir::emitRemarks. 'streamer' must inherit from MLIRRemarkStreamerBase and will be used to stream the remarks.
Referenced by enableOptimizationRemarksWithLLVMStreamer(), and performActions().
enableOptimizationRemarksWithLLVMStreamer()
LogicalResult mlir::remark::enableOptimizationRemarksWithLLVMStreamer (MLIRContext & ctx, StringRef filePath, llvm::remarks::Format fmt, const RemarkCategories & cat, bool printAsEmitRemarks = false)
Enable optimization remarks to a file with the given path and format.
The remark categories are used to filter the remarks that are emitted. If the printAsEmitRemarks flag is set, remarks will also be printed using mlir::emitRemarks.
Definition at line 56 of file RemarkStreamer.cpp.
References mlir::remark::detail::LLVMRemarkStreamer::createToFile(), enableOptimizationRemarks(), and failed().
Referenced by performActions().
failed()
detail::InFlightRemark mlir::remark::failed (Location loc, RemarkOpts opts) inline
Report an optimization remark that failed.
Definition at line 491 of file Remarks.h.
References mlir::remark::detail::RemarkEngine::emitOptimizationRemarkFailure(), and mlir::remark::detail::withEngine().
Referenced by mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::affine::FlatAffineValueConstraints::addAffineParallelOpDomain(), mlir::ValueBoundsConstraintSet::addBound(), mlir::FlatLinearConstraints::addBound(), mlir::affine::FlatAffineValueConstraints::addBound(), mlir::affine::FlatAffineValueConstraints::addDomainFromSliceMaps(), mlir::affine::FlatAffineValueConstraints::addInductionVarOrTerminalSymbol(), addInitOperandsToLoopNest(), addMissingLoopIVBounds(), addShardOp(), mlir::affine::FlatAffineValueConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), mlir::affine::affineDataCopyGenerate(), allocAndInitializeReductionVars(), mlir::arm_sme::allocateSMETiles(), allocReductionVars(), mlir::bufferization::OneShotAnalysisState::analyzeOp(), analyzeProfitability(), mlir::bufferization::OneShotAnalysisState::analyzeSingleOp(), appendMangledType(), mlir::PassReproducerOptions::apply(), mlir::applyOpPatternsGreedily(), mlir::applyPatternsGreedily(), applyTilingToAll(), mlir::transform::TransformState::applyTransform(), mlir::transform::applyTransformNamedSequence(), mlir::transform::applyTransforms(), mlir::ValueBoundsConstraintSet::areEquivalentSlices(), mlir::ValueBoundsConstraintSet::areOverlappingSlices(), mlir::bufferization::detail::asMemRefType(), mlir::transform::detail::assembleTransformLibraryFromPaths(), mlir::linalg::blockPackMatmul(), mlir::bufferization::bufferizeOp(), mlir::linalg::bufferizeToAllocation(), mlir::tensor::buildIndependentOp(), MmaSyncBuilder::buildMmaSync(), buildPackingLoopNestImpl(), mlir::LLVMTypeConverter::canConvertToBarePtr(), canonicalizeMapExprAndTermOrder(), canonicalizeMinMaxOp(), mlir::scf::canonicalizeMinMaxOpInLoop(), mlir::bufferization::castOrReallocMemRefValue(), checkAssumptionForLoop(), ValueEquivalenceCache::checkCommutativeEquivalent(), checkIfHyperRectangular(), TosaProfileCompliance::checkInvalid(), mlir::affine::checkMemrefAccessDependence(), checkOperandAffineExpr(), checkOperandAffineExprRecursively(), TosaProfileCompliance::checkProfileOrExtension(), cleanupPrivateVars(), mlir::pdll::codegenPDLLToMLIR(), mlir::linalg::collapseOpIterationDims(), mlir::spirv::combine(), mlir::FlatLinearConstraints::composeMatchingMap(), mlir::affine::MemRefRegion::compute(), computeCollapsedLayoutMap(), computeExpandedLayoutMap(), mlir::detail::SourceMgrDiagnosticVerifierHandlerImpl::computeExpectedDiags(), computeMemRefRankReductionMask(), mlir::presburger::computeSingleVarRepr(), mlir::affine::computeSliceUnion(), mlir::presburger::SymbolicLexSimplex::computeSymbolicIntegerLexMin(), mlir::presburger::IntegerRelation::constantFoldVarRange(), mlir::detail::constructContainerOpForParserIfNecessary(), convertAffineLoopNestToGPULaunch(), mlir::LLVM::ModuleImport::convertAliases(), mlir::LLVM::ModuleTranslation::convertArgAndResultAttrs(), mlir::TypeConverter::convertBlockSignature(), convertCallLLVMIntrinsicOp(), convertConstantOpMmaSync(), convertDataOp(), convertExtractStridedSlice(), mlir::lsp::MLIRServer::convertFromBytecode(), convertFuncOpTypes(), mlir::LLVM::ModuleImport::convertFunctions(), mlir::LLVM::ModuleImport::convertGlobals(), convertHostOrTargetOperation(), mlir::LLVM::ModuleImport::convertIFuncs(), mlir::LLVM::ModuleImport::convertIntrinsicArguments(), mlir::LLVM::ModuleImport::convertMetadata(), convertMLIRAttributesToLLVM(), convertOmpAtomicCapture(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), convertOmpAtomicWrite(), convertOmpCancel(), convertOmpCancellationPoint(), convertOmpCritical(), convertOmpDistribute(), convertOmpLoopNest(), convertOmpMasked(), convertOmpMaster(), convertOmpOpRegions(), convertOmpOrdered(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSections(), convertOmpSimd(), convertOmpSingle(), convertOmpTarget(), convertOmpTargetData(), convertOmpTaskgroupOp(), convertOmpTaskOp(), convertOmpTaskwaitOp(), convertOmpTeams(), convertOmpThreadprivate(), convertOmpWsloop(), convertOperationImpl(), mlir::OperationConverter::convertOperations(), mlir::convertOpResultTypes(), convertProfileSummaryModuleFlagValue(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertSignatureArgs(), convertStandaloneDataOp(), convertStructTypePacked(), convertStructTypeWithOffset(), convertTargetOpsInNest(), convertTransferReadToLoads(), convertTransferWriteToStores(), mlir::TypeConverter::convertType(), mlir::TypeConverter::convertTypes(), mlir::LLVM::ModuleImport::convertValues(), mlir::convertVectorToMMAOps(), mlir::convertVectorToNVVMCompatibleMMASync(), copyFirstPrivateVars(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptor(), mlir::tensor::ExtractSliceFromCollapseHelper::create(), mlir::nvgpu::createAsyncGroups(), mlir::PassPipelineOptions< T >::createFromString(), createIfNonNull(), createInitialTensorsForTiling(), createLinalgBodyCalculationForElementwiseOp(), createMemRefMetadataType(), createNewAliasScopesFromNoAliasParameter(), createNonLdMatrixLoads(), mlir::tosa::CreateOpAndInferShape(), mlir::LLVM::createPrintStrCall(), createReductionsAndCleanup(), createSingleExitingLatch(), createSplitPart(), createTreePrinterOutputPath(), creatLdMatrixCompatibleLoads(), mlir::shard::detail::defaultAddShardingAnnotations(), mlir::shard::detail::defaultGetShardingAnnotations(), mlir::shard::detail::defaultGetShardingOption(), mlir::detail::defaultOperatesOnDisjointSubset(), mlir::detail::defaultOperatesOnEquivalentSubset(), mlir::affine::delinearizeIndex(), mlir::spirv::Deserializer::deserialize(), mlir::spirv::deserialize(), mlir::presburger::Simplex::detectRedundant(), didntSucceed(), dispatchMappedValues(), mlir::ConversionPattern::dispatchTo1To1(), mlir::Inliner::doInlining(), doubleBuffer(), doVerifyRoundTrip(), mlir::bufferization::dropEquivalentBufferResults(), emitSwitchCase(), emitUserDefinedMapper(), enableOptimizationRemarksWithLLVMStreamer(), mlir::encodeBindAttribute(), encodeKernelName(), mlir::tosa::EqualizeRanks(), errorIfTypeOrShapeMismatch(), mlir::smt::exportSMTLIB(), extractStridedSliceSupportsMMAMatrixType(), mlir::failableParallelForEach(), mlir::BytecodeReader::Impl::finalize(), mlir::detail::OpPassManagerImpl::finalizePassList(), mlir::presburger::LexSimplex::findIntegerLexMin(), findOptimal(), mlir::presburger::LexSimplex::findRationalLexMin(), findReassociationRangesForCollapse(), mlir::FlatLinearValueConstraints::FlatLinearValueConstraints(), mlir::FlatLinearConstraints::flattenAlignedMapAndMergeLocals(), foldLoopBounds(), mlir::amdgpu::foldMemrefViewOp(), mlir::bufferization::foldToBufferToTensorPair(), mlir::FrozenRewritePatternSet::FrozenRewritePatternSet(), fuseWithReshapeByExpansion(), mlir::linalg::generalizeNamedOp(), mlir::affine::generateCopyForMemRegion(), generateInclude(), mlir::linalg::generateLibraryCallName(), generateLoopNestUsingForallOp(), generateLoopNestUsingForOp(), mlir::affine::MemRefAccess::getAccessRelation(), mlir::detail::getAffineMapStridesAndOffset(), mlir::affine::ComputationSliceState::getAsConstraints(), mlir::FlatLinearConstraints::getAsIntegerSet(), mlir::getBoundForAffineExpr(), getCanonicalSubViewResultType(), getCastCompatibleMemRefType(), mlir::DynamicAttr::getChecked(), mlir::DynamicType::getChecked(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked(), mlir::getConstantIntValues(), getConsumerFromLoopUses(), mlir::LLVM::detail::getDataLayout(), getDynamicSharedMemorySymbol(), mlir::ConvertToLLVMPattern::getElementPtrType(), mlir::spirv::getElementPtrType(), mlir::spirv::StructType::getEmpty(), getFlattenedAffineExprs(), getFlattenMemrefAndOffset(), getGridAndVerifyAxes(), mlir::affine::getIndexSet(), mlir::affine::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::nvgpu::getLaneIdAndValueIdToOperandCoord(), getMemoryFootprintBytes(), mlir::LLVMTypeConverter::getMemRefDescriptorFields(), mlir::spirv::getOpenCLElementPtr(), mlir::tensor::getOrCreateDestination(), mlir::tensor::getOrCreateDestinations(), mlir::getReassociationIndicesForCollapse(), mlir::affine::getRelationFromMap(), mlir::ConversionPatternRewriter::getRemappedValue(), mlir::ConversionPatternRewriter::getRemappedValues(), getSharding(), mlir::affine::ComputationSliceState::getSourceAsConstraints(), getStaticallyKnownRowStride(), getStridesAndOffset(), getTargetShape(), getUntiledConsumerFromSlice(), getUntiledConsumerOperandsFromSlices(), getVectorToLLVMAlignment(), mlir::spirv::getVulkanElementPtr(), mlir::nvgpu::getWarpMatrixInfo(), mlir::detail::PassOptions::ListOption< DataType, OptionParser >::handleOccurrence(), hasFullyDynamicLayoutMap(), haveCompatibleStrides(), mlir::linalg::hoistPaddingOnTensors(), mlir::linalg::hoistRedundantVectorTransfers(), hoistSubsetAtIterArg(), mlir::linalg::inferContractionDims(), mlir::dataflow::AbstractDenseForwardDataFlowAnalysis::initialize(), mlir::dataflow::AbstractDenseBackwardDataFlowAnalysis::initialize(), mlir::DataFlowSolver::initializeAndRun(), mlir::Pass::initializeOptions(), initPrivateVar(), initReductionVars(), VulkanRuntime::initRuntime(), VectorizationState::initState(), mlir::inlineCall(), inlineConvertOmpRegions(), inlineOmpRegionCleanup(), mlir::Inliner::Impl::inlineSCC(), mlir::bufferization::insertTensorCopies(), mlir::NVVM::PtxBuilder::insertValue(), mlir::linalg::interchangeGenericOp(), interleaveWithError(), irdlAttrOrTypeVerifier(), irdlOpVerifier(), irdlRegionVerifier(), mlir::tensor::isCastLikeExtractSliceOp(), mlir::tensor::isCastLikeInsertSliceOp(), mlir::linalg::detail::isConvolutionInterfaceImpl(), mlir::linalg::MatmulTransposeAOp::isDefaultIndexingMaps(), mlir::linalg::MatmulTransposeBOp::isDefaultIndexingMaps(), mlir::linalg::BatchMatmulTransposeAOp::isDefaultIndexingMaps(), mlir::linalg::BatchMatmulTransposeBOp::isDefaultIndexingMaps(), mlir::DiagnosedSilenceableFailure::isDefiniteFailure(), mlir::OperationEquivalence::isEquivalentTo(), isFusionProfitable(), mlir::Tester::isInteresting(), mlir::affine::ComputationSliceState::isMaximal(), isMemRefTypeSupported(), isOpSibling(), mlir::affine::ComputationSliceState::isSliceValid(), mlir::memref::isStaticShapeAndContiguousRowMajor(), mlir::JitRunnerMain(), mlir::AsmParser::KeywordSwitch< ResultT >::KeywordSwitch(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::LLVM::ModuleToObject::loadBitcodeFile(), mlir::NVVM::SerializeGPUModuleBase::loadBitcodeFiles(), mlir::ROCDL::SerializeGPUModuleBase::loadBitcodeFiles(), mlir::xevm::SerializeGPUModuleBase::loadBitcodeFiles(), mlir::LLVM::ModuleToObject::loadBitcodeFilesFromList(), mlir::SymbolTable::lookupSymbolIn(), mlir::SymbolTableCollection::lookupSymbolIn(), mlir::LockedSymbolTableCollection::lookupSymbolIn(), mlir::affine::loopUnrollByFactor(), mlir::loopUnrollByFactor(), mlir::affine::loopUnrollJamByFactor(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::scf::lowerToLoopsUsingSCFForOp(), makeAtomicReductionGen(), mlir::affine::makeComposedFoldedAffineApply(), makeComposedFoldedMinMax(), makeIndependent(), makeReductionGen(), mlir::transform::TransformState::mapBlockArguments(), WrapFuncInClass::matchAndRewrite(), mlir::amdgpu::FoldMemRefOpsIntoGatherToLDSOp::matchAndRewrite(), mlir::GPUFuncOpLowering::matchAndRewrite(), IndexSwitchOpLowering::matchAndRewrite(), mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite(), VectorizeConvolution::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), mlir::HomomorphismSimplification< GetHomomorphismOpOperandFn, GetHomomorphismOpResultFn, GetSourceAlgebraicOpOperandsFn, GetSourceAlgebraicOpResultFn, GetTargetAlgebraicOpResultFn, IsHomomorphismOpFn, IsSourceAlgebraicOpFn, CreateTargetAlgebraicOpFn >::matchAndRewrite(), mlir::PatternApplicator::matchAndRewrite(), mlir::OpWithOffsetSizesAndStridesConstantArgumentFolder< OpType, ResultTypeFn, CastOpFunc >::matchAndRewrite(), CanonicalizeAffineMinMaxOpExprAndTermOrder< T >::matchAndRewrite(), mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite(), TransposeOpLowering::matchAndRewrite(), mlir::BytecodeReader::Impl::materializeAll(), mlir::transform::detail::mergeSymbolsInto(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirLinalgInferContractionDimensions(), mlirLinalgInferConvolutionDimensions(), mlirMemRefTypeGetStridesAndOffset(), mlir::MlirOptMain(), mlir::mlirQueryMain(), mlir::mlirReduceMain(), mlir::arith::NarrowTypeEmulationConverter::NarrowTypeEmulationConverter(), NAryInferReturnTypes(), mlir::affine::normalizeMemRef(), mlir::affine::normalizeMemRefType(), GpuAsyncRegionPass::ThreadTokenCallback::operator()(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), mlir::outlineIfOp(), mlir::linalg::pack(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::linalg::packMatmulGreedily(), mlir::linalg::padAndHoistLinalgOp(), padOperandToSmallestStaticBoundingBox(), mlir::FieldParser< ContainerT, std::enable_if_t< llvm::is_detected< detail::has_push_back_t, ContainerT >::value, ContainerT > >::parse(), mlir::FieldParser< AffineMap >::parse(), mlir::DynamicAttr::parse(), mlir::DynamicType::parse(), llvm::cl::detail::VectorParserBase< VectorT, ElementT >::parse(), parseAccVar(), parseAffineMapWithMinMax(), parseAlignedClause(), parseAngleBracketedEntries(), parseApplyRegisteredPassOptions(), parseArrayType(), mlir::DynamicDialect::parseAttribute(), mlir::detail::Parser::parseAttribute(), parseAttributions(), parseBindName(), parseBlockArgClause(), parseBlockArgRegion(), parseBound(), mlir::detail::pass_options::parseCommaSeparatedList(), parseCommonStructuredOpParts(), parseContinuousTileSizeTypes(), parseCopyprivate(), parseCreateOperationOpResults(), mlir::detail::Parser::parseDecOrHexAttr(), mlir::detail::Parser::parseDenseResourceElementsAttr(), parseDependVarList(), parseDeviceTypeArrayAttr(), parseDeviceTypeOperands(), parseDeviceTypeOperandsWithKeywordOnly(), parseDeviceTypeOperandsWithSegment(), parseDialectGrouping(), mlir::detail::Parser::parseDialectSymbolBody(), mlir::parseDimensionList(), mlir::detail::Parser::parseDimensionListRanked(), mlir::sparse_tensor::ir_detail::DimLvlMapParser::parseDimLvlMap(), parseDstStyleOp(), mlir::parseDynamicIndexList(), parseEntry(), parseExpressedTypeAndRange(), parseExtTypeParams(), mlir::detail::AsmParserImpl< BaseT >::parseFloat(), mlir::function_interface_impl::parseFunctionOp(), mlir::call_interface_impl::parseFunctionResultList(), mlir::call_interface_impl::parseFunctionSignature(), parseGangClause(), parseGEPIndices(), parseIndirectBrOpSucessors(), parseInterfaceVarABIAttr(), parseKeyValuePair(), parseKeywordList(), mlir::AsmParser::parseKeywordOrString(), mlir::sparse_tensor::ir_detail::LvlTypeParser::parseLvlType(), parseMembersIndex(), parseMultitileSizesTypes(), parseNumGangs(), parseOperandsWithKeywordOnly(), parseOperandWithKeywordOnly(), parseOptionalArrayStride(), mlir::detail::AsmParserImpl< BaseT >::parseOptionalAttrDictWithKeyword(), parseOptionalCallFuncPtr(), mlir::AsmParser::parseOptionalDecimalInteger(), mlir::xegpu::parseOptionalDynamicIndexList(), mlir::parsePassPipeline(), parseQuantParams(), mlir::AsmParser::parseResourceHandle(), mlir::detail::Parser::parseResourceHandle(), parseRoutineGangClause(), parseRuntimeArrayType(), parseSequenceOpOperands(), parseSingleBlockRegion(), mlir::detail::parseSourceFile(), mlir::parseSourceString(), parseStorageRange(), mlir::detail::Parser::parseStridedLayoutAttr(), parseStructMemberDecorations(), parseStructType(), parseSwitchOpCases(), mlir::AsmParser::parseSymbolName(), parseSymOperandList(), parseSynchronizationHint(), mlir::detail::Parser::parseTensorType(), parseTokenOrdering(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::DynamicDialect::parseType(), parseTypedInitialValue(), parseVar(), mlir::tosa::parseVariableOpTypeOrInitialValue(), parseVarPtrType(), parseWaitClause(), mlir::detail::DenseArrayAttrImpl< T >::parseWithoutBraces(), mlir::shard::partitionBlock(), mlir::shard::partitionFuncOp(), mlir::shard::partitionOperation(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), pdllConvertValues(), performActions(), performPreTilingChecks(), mlir::scf::pipelineForLoop(), pipelineForSharedCopies(), mlir::memref::populateMemRefNarrowTypeEmulationConversions(), mlir::ptr::populatePtrToLLVMConversionPatterns(), prepareLLVMModule(), print(), printBinaryOperation(), printCallOperation(), printConstantOp(), printFunctionBody(), mlir::AsmPrinter::Impl::printLocation(), printOperation(), printUnaryOperation(), processDataOperands(), mlir::spirv::processDecorationList(), mlir::LLVM::ModuleImport::processFunction(), ProfileInfoDepot::ProfileInfoDepot(), mlir::bufferization::promoteBufferResultsToOutParams(), mlir::linalg::promoteSubviewAsNewBuffer(), promoteSubViews(), mlir::linalg::promoteSubViews(), mlir::dlti::query(), mlir::BytecodeReader::Impl::read(), mlir::DialectBytecodeReader::readAttribute(), mlir::DialectBytecodeReader::readList(), mlir::DialectBytecodeReader::readOptionalAttribute(), mlir::DialectBytecodeReader::readResourceHandle(), mlir::readResourceHandle(), mlir::DialectBytecodeReader::readSparseArray(), mlir::DialectBytecodeReader::readType(), mlir::DialectBytecodeReader::readVarIntWithFlag(), mlir::ReductionNode::ReductionNode(), mlir::registerConversionPDLFunctions(), mlir::registerIRDLToCppTranslation(), registerTranslateToMLIRFunction(), reifyOpResultShapes(), mlir::reifyResultShapes(), mlir::affine::reifyValueBound(), mlir::arith::reifyValueBound(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::SymbolTable::rename(), mlir::SymbolTable::renameToUnique(), mlir::affine::replaceAllMemRefUsesWith(), mlir::detail::AttrTypeReplacerBase< AttrTypeReplacer >::replaceElementsIn(), mlir::tensor::replaceExtractSliceWithTiledProducer(), mlir::tensor::replaceInsertSlicesWithTiledConsumer(), replaceSubElements(), mlir::memref::replaceWithIndependentOp(), mlir::AsmParserState::Impl::resolveSymbolUses(), mlir::linalg::rewriteAsPaddedOp(), mlir::linalg::rewriteInDestinationPassingStyle(), roundTripModule(), mlir::LLVM::ModuleToObject::run(), VulkanRuntime::run(), mlir::query::MatchQuery::run(), mlir::PassManager::run(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runDenseBufferization(), SimplifyAffineMinMaxPass::runOnOperation(), AmdgpuMaskedloadToLoadPass::runOnOperation(), ShardingPropagation::runOnOperation(), mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation(), TargetToDataLayoutPass::runOnOperation(), TargetToTargetFeaturesPass::runOnOperation(), runTransformOnCGSCCs(), selectShardingOption(), mlir::affine::separateFullTiles(), mlir::spirv::Serializer::serialize(), serializeModule(), mlir::spirv::Serializer::processOp< spirv::CopyMemoryOp >(), mlir::spirv::Serializer::processOp< spirv::FunctionCallOp >(), mlir::spirv::Serializer::processOp< spirv::GenericCastToPtrExplicitOp >(), setAccessGroupsAttr(), setAliasScopesAttr(), setDereferenceableAttr(), setNoaliasScopesAttr(), mlir::MlirOptMainConfig::setPassPipelineParser(), mlir::simplifyAffineExpr(), simplifyAffineMinMaxOp(), mlir::affine::simplifyAffineMinMaxOps(), mlir::tensor::simplifyCollapseShapeWithRankReducingExtractSlice(), mlir::affine::simplifyConstrainedMinMaxOp(), simplifyPassThroughBr(), mlir::splitAndProcessBuffer(), staticallyOutOfBounds(), mlir::ValueBoundsConstraintSet::strongCompare(), mlir::scf::tileAndFuseConsumerOfSlices(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), mlir::scf::tileAndFuseProducerOfSlice(), mlir::scf::tileConsumerAndFuseProducersUsingSCF(), mlir::affine::tilePerfectlyNested(), mlir::affine::tilePerfectlyNestedParametric(), mlir::linalg::tileReductionUsingForall(), mlir::scf::tileUsingSCF(), mlir::transformCFGToSCF(), transformCyclesToSCFLoops(), mlir::gpu::transformGpuModulesToBinaries(), transformToStructuredCFBranches(), translateDataLayout(), mlir::translateLLVMIRToModule(), mlir::DenseElementsAttr::try_value_begin(), mlir::DenseElementsAttr::try_value_end(), tryApply(), mlir::AsmParser::tryStartCyclicParse(), mlir::AsmPrinter::tryStartCyclicPrint(), mlir::OperationFolder::tryToFold(), mlir::spirv::unrollVectorsInFuncBodies(), updateCalls(), mlir::lsp::PDLLServer::updateDocument(), mlir::lsp::TableGenServer::updateDocument(), updateFuncOp(), updateSymbolAndAllUses(), validateFullTilesOnDims(), mlir::linalg::vectorize(), mlir::affine::vectorizeAffineLoopNest(), vectorizeLinalgOpPrecondition(), vectorizeLoops(), mlir::linalg::vectorizeOpPrecondition(), vectorizePackOpPrecondition(), vectorizePadOpPrecondition(), vectorizeUnPackOpPrecondition(), mlir::irdl::DynParametricAttrConstraint::verify(), mlir::irdl::DynParametricTypeConstraint::verify(), mlir::irdl::AllOfConstraint::verify(), mlir::irdl::RegionConstraint::verify(), mlir::LLVM::detail::verifyAliasAnalysisOpInterface(), verifyAllToAllOperandAndResultShape(), mlir::spirv::verifyAtomicUpdateOp(), mlir::verifyCompatibleShapes(), verifyConstantType(), verifyConvOpErrorIf(), mlir::detail::verifyDataLayoutOp(), mlir::detail::verifyDataLayoutSpec(), mlir::OpTrait::impl::verifyElementwise(), verifyExtendedBatchVariantMatmulSemantic(), verifyGatherOperandAndResultShape(), mlir::spirv::verifyGroupNonUniformArithmeticOp(), mlir::detail::verifyInferredResultTypes(), mlir::quant::UniformQuantizedPerAxisType::verifyInvariants(), mlir::quant::UniformQuantizedSubChannelType::verifyInvariants(), mlir::quant::UniformQuantizedType::verifyInvariants(), mlir::quant::AnyQuantizedType::verifyInvariants(), verifyMemoryOpIndexing(), verifyNames(), mlir::detail::verifyOffsetSizeAndStrideOp(), verifyPoolingOp(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultRank(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), verifyScatterOrSliceOperandAndResultShape(), verifyStructArrayConstant(), mlir::linalg::detail::verifyStructuredOpInterface(), mlir::detail::verifyTargetSystemSpec(), verifyTensorReshapeOp(), mlir::OpTrait::tosa::verifyTosaShapeOperatorWithSameRanks(), mlir::function_interface_impl::verifyTrait(), mlir::OpTrait::tosa::MulOperandsAndResultElementType< ConcreteType >::verifyTrait(), verifyTypesAlongAllEdges(), mlir::detail::verifyTypesAlongControlFlowEdges(), verifyVariableOpErrorIf(), visitOp(), mlir::dataflow::SparseConstantPropagation::visitOperation(), mlir::walkAndApplyPatterns(), mlir::AffineExprVisitor< SubClass, LogicalResult >::walkPostOrder(), walkReferenceCountedValues(), mlir::arith::WideIntEmulationConverter::WideIntEmulationConverter(), and mlir::scf::yieldReplacementForFusedProducer().
metric()
template<class V > detail::LazyTextBuild mlir::remark::metric (StringRef key, V && v) inline
Definition at line 468 of file Remarks.h.
References mlir::remark::detail::Remark::Arg::val.
missed()
detail::InFlightRemark mlir::remark::missed (Location loc, RemarkOpts opts) inline
Report an optimization remark that was missed.
Definition at line 485 of file Remarks.h.
References mlir::remark::detail::RemarkEngine::emitOptimizationRemarkMiss(), and mlir::remark::detail::withEngine().
passed()
detail::InFlightRemark mlir::remark::passed (Location loc, RemarkOpts opts) inline
Report an optimization remark that was passed.
Definition at line 480 of file Remarks.h.
References mlir::remark::detail::RemarkEngine::emitOptimizationRemark(), and mlir::remark::detail::withEngine().
reason()
template<class... Ts> detail::LazyTextBuild mlir::remark::reason (const char * fmt, Ts &&... ts) inline
Create a Reason with llvm::formatv formatting.
Definition at line 451 of file Remarks.h.
suggest()
template<class... Ts> detail::LazyTextBuild mlir::remark::suggest (const char * fmt, Ts &&... ts) inline
Create a Suggestion with llvm::formatv formatting.
Definition at line 457 of file Remarks.h.