MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm Namespace Reference
Classes
struct ArrayType
struct FunctionType
struct MDConstantAttr
struct MDFuncAttr
struct MDNodeAttr
struct MDStringAttr
struct PointerType
struct StructType
Functions
static void populateDialectLLVMSubmodule (nanobind::module_ &m)
Function Documentation
populateDialectLLVMSubmodule()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::populateDialectLLVMSubmodule (nanobind::module_ & m) static
Definition at line 386 of file DialectLLVM.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDConstantAttr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDFuncAttr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDNodeAttr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDStringAttr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< ArrayType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< FunctionType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PointerType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< StructType >::bind(), and mlirTranslateModuleToLLVMIRToString().
Referenced by NB_MODULE().