MLIR: mlir::dlti Namespace Reference
mlir::dlti Namespace Reference
Functions
FailureOr< Attribute > query (Operation *op, ArrayRef< DataLayoutEntryKey > keys, bool emitError=false)
Perform a DLTI-query at op, recursively querying each key of keys on query interface-implementing attrs, starting from attr obtained from op.
FailureOr< Attribute > query (Operation *op, ArrayRef< StringRef > keys, bool emitError=false)
Perform a DLTI-query at op using each string in keys as a separate DLTI entry key, recursively querying on query interface-implementing attrs, starting from attr obtained from op.
void registerTransformDialectExtension (DialectRegistry &registry)
Function Documentation
query() [1/2]
FailureOr< Attribute > mlir::dlti::query (Operation * op, ArrayRef< DataLayoutEntryKey > keys, bool emitError = false)
Perform a DLTI-query at op, recursively querying each key of keys on query interface-implementing attrs, starting from attr obtained from op.
Definition at line 537 of file DLTI.cpp.
References diag(), mlir::Operation::emitError(), mlir::emitError(), mlir::detail::enumerate(), getClosestQueryable(), mlir::Operation::getLoc(), and keyToStr().
Referenced by mlir::query::InvalidQuery::classof(), mlir::query::NoOpQuery::classof(), mlir::query::HelpQuery::classof(), mlir::query::QuitQuery::classof(), mlir::query::MatchQuery::classof(), and query().
query() [2/2]
FailureOr< Attribute > mlir::dlti::query (Operation * op, ArrayRef< StringRef > keys, bool emitError = false)
Perform a DLTI-query at op using each string in keys as a separate DLTI entry key, recursively querying on query interface-implementing attrs, starting from attr obtained from op.
Definition at line 595 of file DLTI.cpp.
References mlir::emitError(), mlir::get(), mlir::Operation::getContext(), and query().
registerTransformDialectExtension()
void mlir::dlti::registerTransformDialectExtension (DialectRegistry & registry)
Definition at line 82 of file DLTITransformOps.cpp.
References mlir::DialectRegistry::addExtensions().