MLIR: mlir::arm_sve Namespace Reference
mlir::arm_sve Namespace Reference
Namespaces
namespace impl
Functions
void registerTransformDialectExtension (DialectRegistry &registry)
std::unique_ptr< Pass > createLegalizeVectorStoragePass ()
Pass to legalize Arm SVE vector storage.
void populateLegalizeVectorStoragePatterns (RewritePatternSet &patterns)
Collect a set of patterns to legalize Arm SVE vector storage.
void registerLegalizeVectorStorage ()
void registerLegalizeVectorStoragePass ()
void registerArmSVEPasses ()
Function Documentation
createLegalizeVectorStoragePass()
std::unique_ptr< Pass > mlir::arm_sve::createLegalizeVectorStoragePass ()
Pass to legalize Arm SVE vector storage.
Definition at line 477 of file LegalizeVectorStorage.cpp.
populateLegalizeVectorStoragePatterns()
void mlir::arm_sve::populateLegalizeVectorStoragePatterns (RewritePatternSet & patterns)
Collect a set of patterns to legalize Arm SVE vector storage.
Definition at line 443 of file LegalizeVectorStorage.cpp.
References mlir::patterns.
registerArmSVEPasses()
void mlir::arm_sve::registerArmSVEPasses () inline
Definition at line 105 of file Passes.h.
Referenced by mlir::registerAllPasses().
registerLegalizeVectorStorage()
void mlir::arm_sve::registerLegalizeVectorStorage () inline
Definition at line 84 of file Passes.h.
registerLegalizeVectorStoragePass()
void mlir::arm_sve::registerLegalizeVectorStoragePass () inline
Definition at line 91 of file Passes.h.
registerTransformDialectExtension()
void mlir::arm_sve::registerTransformDialectExtension (DialectRegistry & registry)
Definition at line 56 of file ArmSVEVectorTransformOps.cpp.
References mlir::DialectRegistry::addExtensions().
Referenced by mlir::registerAllExtensions().