MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::linalg Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::linalg Namespace Reference
Classes
struct PyLinalgContractionDimensions
struct PyLinalgConvolutionDimensions
Functions
static std::optional< PyLinalgContractionDimensions > InferContractionDimensions (PyOperationBase &op)
static std::optional< PyLinalgConvolutionDimensions > InferConvolutionDimensions (PyOperationBase &op)
static void populateDialectLinalgSubmodule (nb::module_ m)
Function Documentation
InferContractionDimensions()
std::optional< PyLinalgContractionDimensions > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::linalg::InferContractionDimensions (PyOperationBase & op) static
Definition at line 46 of file DialectLinalg.cpp.
References MlirLinalgContractionDimensions::batch, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), MlirLinalgContractionDimensions::k, MlirLinalgContractionDimensions::m, mlirLinalgInferContractionDimensions(), and MlirLinalgContractionDimensions::n.
Referenced by populateDialectLinalgSubmodule().
InferConvolutionDimensions()
std::optional< PyLinalgConvolutionDimensions > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::linalg::InferConvolutionDimensions (PyOperationBase & op) static
Definition at line 60 of file DialectLinalg.cpp.
References MlirLinalgConvolutionDimensions::batch, MlirLinalgConvolutionDimensions::depth, MlirLinalgConvolutionDimensions::dilations, MlirLinalgConvolutionDimensions::filterLoop, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), MlirLinalgConvolutionDimensions::inputChannel, mlirLinalgInferConvolutionDimensions(), MlirLinalgConvolutionDimensions::outputChannel, MlirLinalgConvolutionDimensions::outputImage, and MlirLinalgConvolutionDimensions::strides.
Referenced by populateDialectLinalgSubmodule().
populateDialectLinalgSubmodule()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::linalg::populateDialectLinalgSubmodule (nb::module_ m) static
Definition at line 79 of file DialectLinalg.cpp.
References MlirLinalgContractionDimensions::batch, MlirLinalgConvolutionDimensions::batch, MlirLinalgConvolutionDimensions::depth, MlirLinalgConvolutionDimensions::dilations, MlirLinalgConvolutionDimensions::filterLoop, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), InferContractionDimensions(), InferConvolutionDimensions(), MlirLinalgConvolutionDimensions::inputChannel, MlirLinalgContractionDimensions::k, MlirLinalgContractionDimensions::m, mlirLinalgFillBuiltinNamedOpRegion(), mlirLinalgGetIndexingMapsAttribute(), mlirLinalgInferContractionDimensionsFromMaps(), mlirLinalgInferConvolutionDimensionsFromMaps(), mlirLinalgIsAContractionOp(), mlirLinalgIsAConvolutionOp(), MlirLinalgContractionDimensions::n, MlirLinalgConvolutionDimensions::outputChannel, MlirLinalgConvolutionDimensions::outputImage, and MlirLinalgConvolutionDimensions::strides.
Referenced by NB_MODULE().