MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN Namespace Reference
Namespaces
namespace amdgpu
namespace execution_engine
namespace gpu
namespace linalg
namespace llvm
namespace nvgpu
namespace pdl
namespace PyDynamicOpTraits
namespace quant
namespace smt
namespace sparse_tensor
namespace transform
namespace transform_interpreter
Classes
class BaseContextObject
Base class for all objects that directly or indirectly depend on an MlirContext.
class DefaultingPyLocation
Used in function arguments when None should resolve to the current context manager set instance.
class DefaultingPyMlirContext
Used in function arguments when None should resolve to the current context manager set instance.
struct MLIRError
Custom exception that allows access to error diagnostic information.
class nb_buffer
struct nb_buffer_info
struct nb_format_descriptor
struct nb_format_descriptor< bool >
struct nb_format_descriptor< double >
struct nb_format_descriptor< float >
struct nb_format_descriptor< int16_t >
struct nb_format_descriptor< int32_t >
struct nb_format_descriptor< int64_t >
struct nb_format_descriptor< int8_t >
struct nb_format_descriptor< uint16_t >
struct nb_format_descriptor< uint32_t >
struct nb_format_descriptor< uint64_t >
struct nb_format_descriptor< uint8_t >
class PyAffineAddExpr
class PyAffineBinaryExpr
class PyAffineCeilDivExpr
class PyAffineConstantExpr
class PyAffineDimExpr
class PyAffineExpr
Wrapper around MlirAffineExpr. Affine expressions are owned by the context.
class PyAffineFloorDivExpr
class PyAffineMap
class PyAffineMapAttribute
class PyAffineMapExprList
A list of expressions contained in an affine map.
class PyAffineModExpr
class PyAffineMulExpr
class PyAffineSymbolExpr
class PyArrayAttribute
class PyAsmState
Wrapper around an MlirAsmState.
struct PyAttrBuilderMap
class PyAttribute
Wrapper around the generic MlirAttribute.
class PyBF16Type
Floating Point Type subclass - BF16Type.
class PyBlock
Wrapper around an MlirBlock.
class PyBlockArgument
Python wrapper for MlirBlockArgument.
class PyBlockArgumentList
A list of block arguments.
class PyBlockIterator
class PyBlockList
Blocks are exposed by the C-API as a forward-only linked list.
class PyBlockPredecessors
A list of block predecessors.
class PyBlockSuccessors
A list of block successors.
class PyBoolAttribute
Bool Attribute subclass - BoolAttr.
class PyCallSiteLocation
class PyComplexType
Complex Type subclass - ComplexType.
class PyConcreteAffineExpr
CRTP base class for Python MLIR affine expressions that subclass AffineExpr and should be castable from it.
class PyConcreteAttribute
CRTP base classes for Python attributes that subclass Attribute and should be castable from it (i.e.
class PyConcreteLocation
CRTP base class for Python classes that subclass Location and should be castable from it (i.e.
class PyConcreteOpInterface
CRTP base class for Python classes representing MLIR Op interfaces.
class PyConcreteType
CRTP base classes for Python types that subclass Type and should be castable from it (i.e.
class PyConcreteValue
CRTP base class for Python MLIR values that subclass Value and should be castable from it.
class PyConditionallySpeculatableOpInterface
Wrapper around the ConditionallySpeculatable interface.
class PyConversionConfig
class PyConversionPattern
class PyConversionPatternRewriter
class PyConversionTarget
class PyDenseArrayAttribute
A python-wrapped dense array attribute with an element type and a derived implementation class.
struct PyDenseBoolArrayAttribute
Instantiate the python dense array classes.
class PyDenseElementsAttribute
struct PyDenseF32ArrayAttribute
struct PyDenseF64ArrayAttribute
class PyDenseFPElementsAttribute
Refinement of PyDenseElementsAttribute for attributes containing floating-point values.
struct PyDenseI16ArrayAttribute
struct PyDenseI32ArrayAttribute
struct PyDenseI64ArrayAttribute
struct PyDenseI8ArrayAttribute
class PyDenseIntElementsAttribute
Refinement of the PyDenseElementsAttribute for attributes containing integer (and boolean) values.
class PyDenseResourceElementsAttribute
class PyDiagnostic
Python class mirroring the C MlirDiagnostic struct.
class PyDiagnosticHandler
Represents a diagnostic handler attached to the context.
class PyDialect
User-level dialect object.
class PyDialectDescriptor
Wrapper around an MlirDialect.
class PyDialectRegistry
Wrapper around an MlirDialectRegistry.
class PyDialects
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
class PyDictAttribute
class PyDynamicAttribute
class PyDynamicOpTrait
class PyDynamicType
class PyF16Type
Floating Point Type subclass - F16Type.
class PyF32Type
Floating Point Type subclass - F32Type.
class PyF64Type
Floating Point Type subclass - F64Type.
class PyFileLineColLocation
class PyFlatSymbolRefAttribute
class PyFloat4E2M1FNType
Floating Point Type subclass - Float4E2M1FNType.
class PyFloat6E2M3FNType
Floating Point Type subclass - Float6E2M3FNType.
class PyFloat6E3M2FNType
Floating Point Type subclass - Float6E3M2FNType.
class PyFloat8E3M4Type
Floating Point Type subclass - Float8E3M4Type.
class PyFloat8E4M3B11FNUZType
Floating Point Type subclass - Float8E4M3B11FNUZ.
class PyFloat8E4M3FNType
Floating Point Type subclass - Float8E4M3FNType.
class PyFloat8E4M3FNUZType
Floating Point Type subclass - Float8E4M3FNUZ.
class PyFloat8E4M3Type
Floating Point Type subclass - Float8E4M3Type.
class PyFloat8E5M2FNUZType
Floating Point Type subclass - Float8E5M2FNUZ.
class PyFloat8E5M2Type
Floating Point Type subclass - Float8E5M2Type.
class PyFloat8E8M0FNUType
Floating Point Type subclass - Float8E8M0FNUType.
class PyFloatAttribute
Float Point Attribute subclass - FloatAttr.
class PyFloatType
class PyFrozenRewritePatternSet
Owning Wrapper around a FrozenRewritePatternSet.
class PyFunctionType
Function type.
class PyFusedLocation
struct PyGlobalDebugFlag
Wrapper for the global LLVM debugging flag.
class PyGlobals
Globals that are always accessible once the extension has been initialized.
class PyGreedyRewriteConfig
Owning Wrapper around a GreedyRewriteDriverConfig.
class PyIndexType
Index Type subclass - IndexType.
class PyInferShapedTypeOpInterface
Python wrapper for InferShapedTypeOpInterface.
class PyInferTypeOpInterface
Python wrapper for InferTypeOpInterface.
class PyInsertionPoint
An insertion point maintains a pointer to a Block and a reference operation.
class PyIntegerAttribute
Integer Attribute subclass - IntegerAttr.
class PyIntegerSet
class PyIntegerSetAttribute
class PyIntegerSetConstraint
class PyIntegerSetConstraintList
class PyIntegerType
class PyLocation
Wrapper around an MlirLocation.
struct PyMemoryEffectsInstanceList
class PyMemoryEffectsOpInterface
Wrapper around the MemoryEffectsOpInterface.
class PyMemRefType
Ranked MemRef Type subclass - MemRefType.
class PyMlirContext
struct PyMlirExternalPass
class PyModule
class PyNamedAttribute
Represents a Python MlirNamedAttr, carrying an optional owned name.
class PyNameLocation
class PyNoneType
None Type subclass - NoneType.
class PyObjectRef
Template for a reference to a concrete type which captures a python reference to its underlying python object.
class PyOpAdaptor
Base class of operation adaptors.
class PyOpaqueAttribute
class PyOpaqueType
Opaque Type subclass - OpaqueType.
class PyOpAttributeMap
A list of operation attributes.
class PyOperation
class PyOperationBase
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
class PyOperationIterator
class PyOperationList
Operations are exposed by the C-API as a forward-only linked list.
class PyOpOperand
class PyOpOperandIterator
class PyOpOperandList
A list of operation operands.
class PyOpOperands
A list of OpOperands.
class PyOpResult
Python wrapper for MlirOpResult.
class PyOpResultList
A list of operation results.
class PyOpSuccessors
A list of operation successors.
class PyOpView
A PyOpView is equivalent to the C++ "Op" wrappers: these are the basis for providing more instance-specific accessors and serve as the base class for custom ODS-style operation classes.
class PyPassManager
Owning Wrapper around a PassManager.
class PyPatternRewriter
class PyRankedTensorType
Ranked Tensor Type subclass - RankedTensorType.
class PyRegion
Wrapper around an MlirRegion.
class PyRegionList
Regions of an op are fixed length and indexed numerically so are represented with a sequence-like container.
class PyRewritePatternSet
class PyRewriterBase
CRTP Base class for rewriter wrappers.
class PyShapedType
Shaped Type Interface - ShapedType.
class PyShapedTypeComponents
Wrapper around an shaped type components.
class PyStridedLayoutAttribute
Strided layout attribute subclass.
class PyStringAttribute
class PySymbolRefAttribute
class PySymbolTable
Bindings for MLIR symbol tables.
class PyTF32Type
Floating Point Type subclass - TF32Type.
class PyThreadContextEntry
Tracks an entry in the thread context stack.
class PyThreadPool
Wrapper around MlirLlvmThreadPool Python object owns the C++ thread pool.
class PyTupleType
Tuple Type subclass - TupleType.
class PyType
Wrapper around the generic MlirType.
class PyTypeAttribute
class PyTypeConverter
class PyTypeID
A TypeID provides an efficient and unique identifier for a specific C++ type.
class PyUnitAttribute
Unit Attribute subclass. Unit attributes don't have values.
class PyUnknownLocation
class PyUnrankedMemRefType
Unranked MemRef Type subclass - UnrankedMemRefType.
class PyUnrankedTensorType
Unranked Tensor Type subclass - UnrankedTensorType.
class PyValue
class PyVectorType
Vector Type subclass - VectorType.
Typedefs
using PyMlirContextRef = PyObjectRef<PyMlirContext>
Wrapper around MlirContext.
using PyModuleRef = PyObjectRef<PyModule>
using PyOperationRef = PyObjectRef<PyOperation>
Enumerations
enum class PyDiagnosticSeverity : std::underlying_type_t< MlirDiagnosticSeverity > { Error = MlirDiagnosticError , Warning = MlirDiagnosticWarning , Note = MlirDiagnosticNote , Remark = MlirDiagnosticRemark }
enum class PyWalkResult : std::underlying_type_t< MlirWalkResult > { Advance = MlirWalkResultAdvance , Interrupt = MlirWalkResultInterrupt , Skip = MlirWalkResultSkip }
enum class PyWalkOrder : std::underlying_type_t< MlirWalkOrder > { PreOrder = MlirWalkPreOrder , PostOrder = MlirWalkPostOrder }
Traversal order for operation walk.
enum class PyMlirPassDisplayMode : std::underlying_type_t< MlirPassDisplayMode > { LIST = MLIR_PASS_DISPLAY_MODE_LIST , PIPELINE = MLIR_PASS_DISPLAY_MODE_PIPELINE }
enum class PyGreedyRewriteStrictness : std::underlying_type_t< MlirGreedyRewriteStrictness > { ANY_OP = MLIR_GREEDY_REWRITE_STRICTNESS_ANY_OP , EXISTING_AND_NEW_OPS = MLIR_GREEDY_REWRITE_STRICTNESS_EXISTING_AND_NEW_OPS , EXISTING_OPS = MLIR_GREEDY_REWRITE_STRICTNESS_EXISTING_OPS }
enum class PyGreedySimplifyRegionLevel : std::underlying_type_t< MlirGreedySimplifyRegionLevel > { DISABLED = MLIR_GREEDY_SIMPLIFY_REGION_LEVEL_DISABLED , NORMAL = MLIR_GREEDY_SIMPLIFY_REGION_LEVEL_NORMAL , AGGRESSIVE = MLIR_GREEDY_SIMPLIFY_REGION_LEVEL_AGGRESSIVE }
enum class PyDialectConversionFoldingMode : std::underlying_type_t< MlirDialectConversionFoldingMode > { Never = MLIR_DIALECT_CONVERSION_FOLDING_MODE_NEVER , BeforePatterns = MLIR_DIALECT_CONVERSION_FOLDING_MODE_BEFORE_PATTERNS , AfterPatterns = MLIR_DIALECT_CONVERSION_FOLDING_MODE_AFTER_PATTERNS }
Functions
template<typename T>
static T pyTryCast (nanobind::handle object)
MLIR_PYTHON_API_EXPORTED void populateIRAttributes (nanobind::module_ &m)
MlirStringRef toMlirStringRef (const std::string &s)
MlirStringRef toMlirStringRef (std::string_view s)
MlirStringRef toMlirStringRef (const nanobind::bytes &s)
MlirBlock MLIR_PYTHON_API_EXPORTED createBlock (const nanobind::typed< nanobind::sequence, PyType > &pyArgTypes, const std::optional< nanobind::typed< nanobind::sequence, PyLocation > > &pyArgLocs)
Create a block, using the current location context if no locations are specified.
MLIR_PYTHON_API_EXPORTED MlirValue getUniqueResult (MlirOperation operation)
MLIR_PYTHON_API_EXPORTED void populateIRCore (nanobind::module_ &m)
MLIR_PYTHON_API_EXPORTED void populateRoot (nanobind::module_ &m)
template<class Func, typename... Args>
nanobind::object classmethod (Func f, Args... args)
Helper for creating an @classmethod.
MLIR_PYTHON_API_EXPORTED int mlirTypeIsAIntegerOrFloat (MlirType type)
MLIR_PYTHON_API_EXPORTED void populateIRTypes (nanobind::module_ &m)
void populateIRAffine (nb::module_ &m)
nb::object denseArrayAttributeCaster (PyAttribute &pyAttribute)
nb::object denseTypedElementsAttributeCaster (PyAttribute &pyAttribute)
nb::object integerOrBoolAttributeCaster (PyAttribute &pyAttribute)
nb::object symbolRefOrFlatSymbolRefAttributeCaster (PyAttribute &pyAttribute)
static MlirDynamicAttrDefinition getDynamicAttrDef (const std::string &fullAttrName, DefaultingPyMlirContext context)
void populateIRAttributes (nb::module_ &m)
MlirBlock createBlock (const nb::typed< nb::sequence, PyType > &pyArgTypes, const std::optional< nb::typed< nb::sequence, PyLocation > > &pyArgLocs)
static void maybeInsertOperation (PyOperationRef &op, const nb::object &maybeIp)
template<typename Container>
static std::vector< nb::typed< nb::object, PyType > > getValueTypes (Container &container, PyMlirContextRef &context)
Returns the list of types of the values held by container.
static void populateResultTypes (std::string_view name, nb::sequence resultTypeList, const nb::object &resultSegmentSpecObj, std::vector< int32_t > &resultSegmentLengths, std::vector< PyType * > &resultTypes)
static MlirValue getOpResultOrValue (nb::handle operand)
static PyOperationRef getValueOwnerRef (MlirValue value)
static MlirLogicalResult verifyTraitByMethod (MlirOperation op, void *userData, const char *methodName)
static bool attachOpTrait (const nb::object &opName, MlirDynamicOpTrait trait, PyMlirContext &context)
static std::string formatMLIRError (const MLIRError &e)
void populateRoot (nb::module_ &m)
void populateIRCore (nb::module_ &m)
void populateIRInterfaces (nb::module_ &m)
static MlirDynamicTypeDefinition getDynamicTypeDef (const std::string &fullTypeName, DefaultingPyMlirContext context)
void populateIRTypes (nb::module_ &m)
void populatePassManagerSubmodule (nb::module_ &m)
Create the mlir.passmanager here.
void populatePassManagerSubmodule (nanobind::module_ &m)
static MlirLogicalResult logicalResultFromObject (const nb::object &obj)
static std::string operationNameFromObject (nb::handle root)
static std::string dialectNameFromObject (nb::handle root)
void populateRewriteSubmodule (nb::module_ &m)
Create the mlir.rewrite here.
void MLIR_PYTHON_API_EXPORTED populateRewriteSubmodule (nanobind::module_ &m)
Variables
static constexpr const char * inferReturnTypesDoc
static constexpr const char * inferReturnTypeComponentsDoc
Typedef Documentation
PyMlirContextRef
using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContextRef = PyObjectRef<PyMlirContext>
Wrapper around MlirContext.
Definition at line 210 of file IRCore.h.
PyModuleRef
using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyModuleRef = PyObjectRef<PyModule>
Definition at line 553 of file IRCore.h.
PyOperationRef
using mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationRef = PyObjectRef<PyOperation>
Definition at line 646 of file IRCore.h.
Enumeration Type Documentation
PyDiagnosticSeverity
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnosticSeverity : std::underlying_type_t< MlirDiagnosticSeverity > strong
Enumerator
Error
Warning
Note
Remark
Definition at line 348 of file IRCore.h.
PyDialectConversionFoldingMode
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectConversionFoldingMode : std::underlying_type_t< MlirDialectConversionFoldingMode > strong
Enumerator
Never
BeforePatterns
AfterPatterns
Definition at line 498 of file Rewrite.cpp.
PyGreedyRewriteStrictness
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedyRewriteStrictness : std::underlying_type_t< MlirGreedyRewriteStrictness > strong
Enumerator
ANY_OP
EXISTING_AND_NEW_OPS
EXISTING_OPS
Definition at line 401 of file Rewrite.cpp.
PyGreedySimplifyRegionLevel
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGreedySimplifyRegionLevel : std::underlying_type_t< MlirGreedySimplifyRegionLevel > strong
Enumerator
DISABLED
NORMAL
AGGRESSIVE
Definition at line 408 of file Rewrite.cpp.
PyMlirPassDisplayMode
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirPassDisplayMode : std::underlying_type_t< MlirPassDisplayMode > strong
Enumerator
LIST
PIPELINE
Definition at line 58 of file Pass.cpp.
PyWalkOrder
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyWalkOrder : std::underlying_type_t< MlirWalkOrder > strong
Traversal order for operation walk.
Enumerator
PreOrder
PostOrder
Definition at line 363 of file IRCore.h.
PyWalkResult
enum class mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyWalkResult : std::underlying_type_t< MlirWalkResult > strong
Enumerator
Advance
Interrupt
Skip
Definition at line 356 of file IRCore.h.
Function Documentation
attachOpTrait()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::attachOpTrait (const nb::object & opName, MlirDynamicOpTrait trait, PyMlirContext & context) static
Definition at line 2556 of file IRCore.cpp.
References mlirLogicalResultFailure(), and success().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::IsTerminator::bind(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::NoTerminator::bind().
classmethod()
template<class Func, typename... Args> nanobind::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::classmethod (Func f, Args... args) inline
Helper for creating an @classmethod.
Definition at line 2002 of file IRCore.h.
References mlir::python::SafeInit< T >::get().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyPatternDescriptorOpInterface::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::bindDerived(), and populateIRCore().
createBlock() [1/2]
MlirBlock MLIR_PYTHON_API_EXPORTED mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::createBlock (const nanobind::typed< nanobind::sequence, PyType > & pyArgTypes, const std::optional< nanobind::typed< nanobind::sequence, PyLocation > > & pyArgLocs)
Create a block, using the current location context if no locations are specified.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::appendBlock(), and populateIRCore().
createBlock() [2/2]
MlirBlock mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::createBlock (const nb::typed< nb::sequence, PyType > & pyArgTypes, const std::optional< nb::typed< nb::sequence, PyLocation > > & pyArgLocs)
Definition at line 80 of file IRCore.cpp.
References join(), mlirBlockCreate(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation::resolve().
denseArrayAttributeCaster()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::denseArrayAttributeCaster (PyAttribute & pyAttribute)
Definition at line 1313 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseBoolArrayAttribute::isaFunction, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseF32ArrayAttribute::isaFunction, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseF64ArrayAttribute::isaFunction, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseI16ArrayAttribute::isaFunction, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseI32ArrayAttribute::isaFunction, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseI64ArrayAttribute::isaFunction, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseI8ArrayAttribute::isaFunction.
Referenced by populateIRAttributes().
denseTypedElementsAttributeCaster()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::denseTypedElementsAttributeCaster (PyAttribute & pyAttribute)
Definition at line 1334 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseFPElementsAttribute::isaFunction, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseIntElementsAttribute::isaFunction.
Referenced by populateIRAttributes().
dialectNameFromObject()
std::string mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::dialectNameFromObject (nb::handle root) static
Definition at line 51 of file Rewrite.cpp.
formatMLIRError()
std::string mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::formatMLIRError (const MLIRError & e) static
Definition at line 2827 of file IRCore.cpp.
References diag(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::errorDiagnostics, mlir::PyPrintAccumulator::getCallback(), mlir::PyPrintAccumulator::getUserData(), mlir::PyPrintAccumulator::join(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::message, and mlirLocationPrint().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::bind().
getDynamicAttrDef()
MlirDynamicAttrDefinition mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getDynamicAttrDef (const std::string & fullAttrName, DefaultingPyMlirContext context) static
Definition at line 1412 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects::getDialectForKey(), mlirDialectIsAExtensibleDialect(), mlirExtensibleDialectLookupAttrDefinition(), and toMlirStringRef().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicAttribute::bindDerived().
getDynamicTypeDef()
MlirDynamicTypeDefinition mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getDynamicTypeDef (const std::string & fullTypeName, DefaultingPyMlirContext context) static
Definition at line 846 of file IRTypes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialects::getDialectForKey(), mlirDialectIsAExtensibleDialect(), mlirExtensibleDialectLookupTypeDefinition(), and toMlirStringRef().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicType::bindDerived().
getOpResultOrValue()
MlirValue mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getOpResultOrValue (nb::handle operand) static
Definition at line 1544 of file IRCore.cpp.
getUniqueResult()
MlirValue mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getUniqueResult (MlirOperation operation)
Definition at line 1529 of file IRCore.cpp.
Referenced by populateIRCore().
getValueOwnerRef()
PyOperationRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getValueOwnerRef (MlirValue value) static
Definition at line 1975 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::get(), and mlirPythonValueToCapsule().
getValueTypes()
template<typename Container> std::vector< nb::typed< nb::object, PyType > > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::getValueTypes (Container & container, PyMlirContextRef & context) static
Returns the list of types of the values held by container.
Definition at line 1389 of file IRCore.cpp.
integerOrBoolAttributeCaster()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::integerOrBoolAttributeCaster (PyAttribute & pyAttribute)
Definition at line 1345 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBoolAttribute::isaFunction, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerAttribute::isaFunction.
Referenced by populateIRAttributes().
logicalResultFromObject()
MlirLogicalResult mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::logicalResultFromObject (const nb::object & obj) static
Definition at line 34 of file Rewrite.cpp.
References mlirLogicalResultFailure(), and mlirLogicalResultSuccess().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::add(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::addConversion().
maybeInsertOperation()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::maybeInsertOperation (PyOperationRef & op, const nb::object & maybeIp) static
Definition at line 1213 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext().
mlirTypeIsAIntegerOrFloat()
int mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::mlirTypeIsAIntegerOrFloat (MlirType type)
Definition at line 31 of file IRTypes.cpp.
References mlirTypeIsABF16(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), and mlirTypeIsAInteger().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyComplexType::bindDerived().
operationNameFromObject()
std::string mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::operationNameFromObject (nb::handle root) static
Definition at line 42 of file Rewrite.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::add(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewritePatternSet::addConversion().
populateIRAffine()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAffine (nb::module_ & m)
Definition at line 535 of file IRAffine.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineAddExpr, PyAffineBinaryExpr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineBinaryExpr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineConstantExpr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineDimExpr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< PyAffineSymbolExpr >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSetConstraint::bind(), mlir::Sliceable< PyAffineMapExprList, PyAffineExpr >::bind(), mlir::Sliceable< PyIntegerSetConstraintList, PyIntegerSetConstraint >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSet::createFromCapsule(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineConstantExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineDimExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineSymbolExpr::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::get(), mlir::PyPrintAccumulator::getCallback(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMap::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyIntegerSet::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::getLHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::getObject(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineAddExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineCeilDivExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineFloorDivExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineModExpr::getRHSConstant(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineMulExpr::getRHSConstant(), mlir::PyPrintAccumulator::getUserData(), isPermutation(), mlir::PyPrintAccumulator::join(), kDumpDocstring, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAffineExpr::maybeDownCast(), MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, MLIR_PYTHON_MAYBE_DOWNCAST_ATTR, mlirAffineExprCompose(), mlirAffineExprDump(), mlirAffineExprPrint(), mlirAffineExprShiftDims(), mlirAffineExprShiftSymbols(), mlirAffineMapCompressUnusedSymbols(), mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapGet(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetSubMap(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapPrint(), mlirAffineMapReplace(), mlirIntegerSetDump(), mlirIntegerSetEmptyGet(), mlirIntegerSetGet(), mlirIntegerSetGetNumDims(), mlirIntegerSetGetNumEqualities(), mlirIntegerSetGetNumInequalities(), mlirIntegerSetGetNumInputs(), mlirIntegerSetGetNumSymbols(), mlirIntegerSetIsCanonicalEmpty(), mlirIntegerSetPrint(), mlirIntegerSetReplaceGet(), mlirSimplifyAffineExpr(), mlir::PyPrintAccumulator::parts, pyListToVector(), replacement(), and result.
Referenced by NB_MODULE().
populateIRAttributes() [1/2]
MLIR_PYTHON_API_EXPORTED void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAttributes (nanobind::module_ & m)
References MLIR_PYTHON_API_EXPORTED.
Referenced by NB_MODULE().
populateIRAttributes() [2/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRAttributes (nb::module_ & m)
Definition at line 1490 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::PyArrayAttributeIterator::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyAffineMapAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyBoolAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseBoolArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseElementsAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseF32ArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseF64ArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseI16ArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseI32ArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseI64ArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseI8ArrayAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDenseResourceElementsAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDictAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyDynamicAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyFlatSymbolRefAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyFloatAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyIntegerAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyIntegerSetAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyOpaqueAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyStridedLayoutAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyStringAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PySymbolRefAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyTypeAttribute >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< PyUnitAttribute >::bind(), denseArrayAttributeCaster(), denseTypedElementsAttributeCaster(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), integerOrBoolAttributeCaster(), mlirDenseArrayAttrGetTypeID(), mlirDenseTypedElementsAttrGetTypeID(), mlirIntegerAttrGetTypeID(), mlirSymbolRefAttrGetTypeID(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerTypeCaster(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::slots, and symbolRefOrFlatSymbolRefAttributeCaster().
populateIRCore() [1/2]
MLIR_PYTHON_API_EXPORTED void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore (nanobind::module_ & m)
References MLIR_PYTHON_API_EXPORTED.
Referenced by NB_MODULE().
populateIRCore() [2/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore (nb::module_ & m)
Definition at line 3259 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::_mlir_thread_pool_ptr(), Advance, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInsertionPoint::after(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInsertionPoint::atBlockBegin(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInsertionPoint::atBlockTerminator(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::attachDiagnosticHandler(), b, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockIterator::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlockList::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyCallSiteLocation >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyFileLineColLocation >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyFusedLocation >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyNameLocation >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteLocation< PyUnknownLocation >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< PyBlockArgument >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteValue< PyOpResult >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTrait::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::IsTerminator::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTraits::NoTerminator::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobalDebugFlag::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAdaptor::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationIterator::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationList::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperand::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpOperandIterator::bind(), mlir::Sliceable< PyBlockArgumentList, PyBlockArgument >::bind(), mlir::Sliceable< PyBlockPredecessors, PyBlock >::bind(), mlir::Sliceable< PyBlockSuccessors, PyBlock >::bind(), mlir::Sliceable< PyOpOperandList, PyValue >::bind(), mlir::Sliceable< PyOpOperands, PyOpOperand >::bind(), mlir::Sliceable< PyOpResultList, PyOpResult >::bind(), mlir::Sliceable< PyOpSuccessors, PyBlock >::bind(), mlir::Sliceable< PyRegionList, PyRegion >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpView::buildGeneric(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::checkValid(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::checkValid(), classmethod(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyModule::clearMlirModule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpView::constructDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnosticHandler::contextEnter(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInsertionPoint::contextEnter(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::contextEnter(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::contextEnter(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnosticHandler::contextExit(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInsertionPoint::contextExit(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::contextExit(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::contextExit(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::create(), createBlock(), createCustomDialectWrapper(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyModule::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeID::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::createFromCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::createOpView(), MlirStringRef::data, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnosticHandler::detach(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::detachFromParent(), diag(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::dunderDel(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::erase(), Error, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::forContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyModule::forModule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::forOperation(), mlir::get(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAsmState::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeID::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getAsm(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::getBlock(), mlir::PyPrintAccumulator::getCallback(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyBlock::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDialectRegistry::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyModule::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyTypeID::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadContextEntry::getDefaultContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadContextEntry::getDefaultInsertionPoint(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadContextEntry::getDefaultLocation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::getEmitErrorDiagnostics(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnosticHandler::getHadError(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::getLiveCount(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::getLiveModuleCount(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getLocation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadPool::getMaxConcurrency(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getMessage(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getNotes(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::getObject(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRegion::getParentOperation(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::getRef(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::getRef(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::getSeverity(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyThreadContextEntry::getStack(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::getSymbolName(), getUniqueResult(), mlir::PyPrintAccumulator::getUserData(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::getVisibility(), hash(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInsertionPoint::insert(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::insert(), Interrupt, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnosticHandler::isAttached(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::isAttached(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::isBeforeInBlock(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::isValid(), join(), mlir::PyPrintAccumulator::join(), kDumpDocstring, kModuleParseDocstring, kValueReplaceAllUsesExceptDocstring, MlirStringRef::length, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::DiagnosticInfo::location, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::maybeDownCast(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyLocation::maybeDownCast(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::maybeDownCast(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyValue::maybeDownCast(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::DiagnosticInfo::message, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, MLIR_PYTHON_MAYBE_DOWNCAST_ATTR, mlirAsmStateCreateForValue(), mlirAsmStateDestroy(), mlirAttributeDump(), mlirAttributeGetType(), mlirAttributeGetTypeID(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBlockAddArgument(), mlirBlockAppendOwnedOperation(), mlirBlockArgumentGetOwner(), mlirBlockDetach(), mlirBlockEraseArgument(), mlirBlockGetFirstOperation(), mlirBlockGetParentRegion(), mlirBlockPrint(), mlirContextAppendDialectRegistry(), mlirContextCreateWithThreading(), mlirContextEnableMultithreading(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetNumThreads(), mlirContextGetOrLoadDialect(), mlirContextGetThreadPool(), mlirContextIsRegisteredOperation(), mlirContextLoadAllAvailableDialects(), mlirContextSetAllowUnregisteredDialects(), mlirContextSetThreadPool(), mlirDialectGetNamespace(), mlirDialectIsNull(), mlirEmitError(), mlirIdentifierStr(), mlirLocationCallSiteGet(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationFileLineColRangeGet(), mlirLocationFromAttribute(), mlirLocationFusedGet(), mlirLocationGetAttribute(), mlirLocationNameGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleCreateParseFromFile(), mlirModuleEqual(), mlirModuleGetBody(), mlirModuleGetOperation(), mlirModuleHashValue(), mlirOperationDump(), mlirOperationEqual(), mlirOperationGetLocation(), mlirOperationGetName(), mlirOperationHashValue(), mlirOperationNameHasTrait(), mlirOperationReplaceUsesOfWith(), mlirOperationSetLocation(), mlirOpPrintingFlagsCreate(), mlirOpPrintingFlagsDestroy(), mlirOpPrintingFlagsPrintNameLocAsPrefix(), mlirOpPrintingFlagsUseLocalScope(), mlirOpResultGetOwner(), mlirRegionAppendOwnedBlock(), mlirRegionGetFirstBlock(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), mlirRegionIsNull(), mlirStringRefCreate(), mlirSymbolTableLookup(), mlirTypeDump(), mlirTypeGetTypeID(), mlirTypeIDHashValue(), mlirTypeIDIsNull(), mlirTypeIsNull(), mlirTypeParseGet(), mlirTypePrint(), mlirValueDump(), mlirValueGetContext(), mlirValueGetFirstUse(), mlirValueGetLocation(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValuePrint(), mlirValuePrintAsOperand(), mlirValueReplaceAllUsesExcept(), mlirValueReplaceAllUsesOfWith(), mlirValueSetType(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::moveAfter(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::moveBefore(), Note, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::DiagnosticInfo::notes, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::parse(), mlir::PyPrintAccumulator::parts, PostOrder, PreOrder, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::print(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyObjectRef< T >::releaseObject(), Remark, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::replaceAllSymbolUses(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::setAttached(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::setEmitErrorDiagnostics(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::setInvalid(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::setSymbolName(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::setVisibility(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDiagnostic::DiagnosticInfo::severity, Skip, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture::take(), toMlirStringRef(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDynamicOpTrait::typeIDAttr, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::verify(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::walkSymbolTables(), Warning, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::writeBytecode().
populateIRInterfaces()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRInterfaces (nb::module_ & m)
Definition at line 471 of file IRInterfaces.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyConditionallySpeculatableOpInterface >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyInferShapedTypeOpInterface >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyInferTypeOpInterface >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyMemoryEffectsOpInterface >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyShapedTypeComponents::bind(), MlirSpeculatabilityNotSpeculatable, MlirSpeculatabilityRecursivelySpeculatable, and MlirSpeculatabilitySpeculatable.
Referenced by NB_MODULE().
populateIRTypes() [1/2]
MLIR_PYTHON_API_EXPORTED void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRTypes (nanobind::module_ & m)
References MLIR_PYTHON_API_EXPORTED.
Referenced by NB_MODULE().
populateIRTypes() [2/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRTypes (nb::module_ & m)
Definition at line 924 of file IRTypes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyBF16Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyComplexType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyDynamicType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyF16Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyF32Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyF64Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat4E2M1FNType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat6E2M3FNType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat6E3M2FNType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E3M4Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E4M3B11FNUZType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E4M3FNType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E4M3FNUZType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E4M3Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E5M2FNUZType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E5M2Type, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloat8E8M0FNUType, PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFloatType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyFunctionType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyIndexType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyIntegerType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyMemRefType, PyShapedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyNoneType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyOpaqueType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyRankedTensorType, PyShapedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyShapedType >::bind(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PyTupleType >::bind().
populatePassManagerSubmodule() [1/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule (nanobind::module_ & m)
populatePassManagerSubmodule() [2/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule (nb::module_ & m)
Create the mlir.passmanager here.
Definition at line 66 of file Pass.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::allocateTypeID(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::createFromCapsule(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperation::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::get(), mlir::PyPrintAccumulator::getCallback(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::getCapsule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOperationBase::getOperation(), mlir::PyPrintAccumulator::getUserData(), mlir::PyPrintAccumulator::join(), LIST, MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirCreateExternalPass(), mlirExternalPassSignalFailure(), mlirLogicalResultIsFailure(), mlirOpPassManagerAddPipeline(), mlirOpPrintingFlagsCreate(), mlirOpPrintingFlagsDestroy(), mlirOpPrintingFlagsElideLargeElementsAttrs(), mlirOpPrintingFlagsElideLargeResourceString(), mlirOpPrintingFlagsEnableDebugInfo(), mlirOpPrintingFlagsPrintGenericOpForm(), mlirParsePassPipeline(), mlirPassManagerAddOwnedPass(), mlirPassManagerCreate(), mlirPassManagerCreateOnOperation(), mlirPassManagerEnableIRPrinting(), mlirPassManagerEnableStatistics(), mlirPassManagerEnableTiming(), mlirPassManagerEnableVerifier(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerRunOnOp(), mlirPrintPassPipeline(), mlirStringRefCreate(), PIPELINE, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyPassManager::release(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture::take().
Referenced by NB_MODULE().
populateResultTypes()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateResultTypes (std::string_view name, nb::sequence resultTypeList, const nb::object & resultSegmentSpecObj, std::vector< int32_t > & resultSegmentLengths, std::vector< PyType * > & resultTypes) static
Definition at line 1442 of file IRCore.cpp.
References join().
populateRewriteSubmodule() [1/2]
void MLIR_PYTHON_API_EXPORTED mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRewriteSubmodule (nanobind::module_ & m)
References MLIR_PYTHON_API_EXPORTED.
populateRewriteSubmodule() [2/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRewriteSubmodule (nb::module_ & m)
Create the mlir.rewrite here.
Definition at line 539 of file Rewrite.cpp.
Referenced by NB_MODULE().
populateRoot() [1/2]
MLIR_PYTHON_API_EXPORTED void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot (nanobind::module_ & m)
References MLIR_PYTHON_API_EXPORTED.
Referenced by NB_MODULE().
populateRoot() [2/2]
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateRoot (nb::module_ & m)
Definition at line 2896 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::addDialectSearchPrefix(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::Fallback, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::getDialectSearchPrefixes(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::getTracebackLoc(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::kMaxFrames, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::loadDialectModule(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::locTracebackFramesLimit(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::locTracebacksEnabled(), MLIR_PYTHON_CAPI_TYPE_CASTER_REGISTER_ATTR, MLIR_PYTHON_CAPI_VALUE_CASTER_REGISTER_ATTR, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::NamelocWrap, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerDialectImpl(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerOpAdaptorImpl(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerOperationImpl(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::registerTracebackFileExclusion(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::registerTracebackFileInclusion(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerTypeCaster(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerValueCaster(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::setDialectSearchPrefixes(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setLocTracebackFramesLimit(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setLocTracebacksEnabled(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setTracebackActionOnCurrentLoc(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::setTracebackActionOnExplicitLoc(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::tracebackActionOnCurrentLoc(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::tracebackActionOnExplicitLoc(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::UseExplicit, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::TracebackLoc::UseTraceback.
pyTryCast()
template<typename T> T mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pyTryCast (nanobind::handle object) static
Definition at line 100 of file IRAttributes.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyArrayAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseArrayAttribute< EltTy, DerivedT >::bindDerived(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::getFromList().
symbolRefOrFlatSymbolRefAttributeCaster()
nb::object mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::symbolRefOrFlatSymbolRefAttributeCaster (PyAttribute & pyAttribute)
Definition at line 1356 of file IRAttributes.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFlatSymbolRefAttribute::isaFunction, and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolRefAttribute::isaFunction.
Referenced by populateIRAttributes().
toMlirStringRef() [1/3]
MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef (const nanobind::bytes & s) inline
Definition at line 1485 of file IRCore.h.
References mlirStringRefCreate().
toMlirStringRef() [2/3]
MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef (const std::string & s) inline
Definition at line 1477 of file IRCore.h.
References mlirStringRefCreate().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFileLineColLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFlatSymbolRefAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyNameLocation::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpaqueAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpaqueType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyStringAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDictAttribute::dunderContains(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderDelItem(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::dunderLen(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpAttributeMap::forEachAttr(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolRefAttribute::fromList(), getDynamicAttrDef(), getDynamicTypeDef(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseResourceElementsAttribute::getFromBuffer(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::getVisibility(), populateIRCore(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyNamedAttribute::PyNamedAttribute(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PySymbolTable::replaceAllSymbolUses().
toMlirStringRef() [3/3]
MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::toMlirStringRef (std::string_view s) inline
Definition at line 1481 of file IRCore.h.
References mlirStringRefCreate().
verifyTraitByMethod()
MlirLogicalResult mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::verifyTraitByMethod (MlirOperation op, void * userData, const char * methodName) static
Definition at line 2545 of file IRCore.cpp.
Variable Documentation
inferReturnTypeComponentsDoc
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::inferReturnTypeComponentsDoc static constexpr
Initial value:
=
    R"(Given the arguments required to build an operation, attempts to infer
its return shaped type components. Raises ValueError on failure.)"
Definition at line 31 of file IRInterfaces.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferShapedTypeOpInterface::bindDerived().
inferReturnTypesDoc
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::inferReturnTypesDoc static constexpr
Initial value:
=
    R"(Given the arguments required to build an operation, attempts to infer
its return types. Raises ValueError on failure.)"
Definition at line 27 of file IRInterfaces.cpp.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyInferTypeOpInterface::bindDerived().