MLIR: mlir::python Namespace Reference
mlir::python Namespace Reference
Namespaces
adaptors
nanobind_adaptors
Classes
class CollectDiagnosticsToStringScope
RAII scope intercepting all diagnostics into a string.
class PyGlobals
Globals that are always accessible once the extension has been initialized.
class PyConcreteOpInterface
CRTP base class for Python classes representing MLIR Op interfaces.
class PyInferTypeOpInterface
Python wrapper for InferTypeOpInterface.
class PyShapedTypeComponents
Wrapper around an shaped type components.
class PyInferShapedTypeOpInterface
Python wrapper for InferShapedTypeOpInterface.
class PyObjectRef
Template for a reference to a concrete type which captures a python reference to its underlying python object.
class PyThreadContextEntry
Tracks an entry in the thread context stack.
class PyThreadPool
Wrapper around MlirLlvmThreadPool Python object owns the C++ thread pool.
class PyMlirContext
class DefaultingPyMlirContext
Used in function arguments when None should resolve to the current context manager set instance.
class BaseContextObject
Base class for all objects that directly or indirectly depend on an MlirContext.
class PyLocation
Wrapper around an MlirLocation.
class PyDiagnostic
Python class mirroring the C MlirDiagnostic struct.
class PyDiagnosticHandler
Represents a diagnostic handler attached to the context.
class PyDialectDescriptor
Wrapper around an MlirDialect.
class PyDialects
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
class PyDialect
User-level dialect object.
class PyDialectRegistry
Wrapper around an MlirDialectRegistry.
class DefaultingPyLocation
Used in function arguments when None should resolve to the current context manager set instance.
class PyModule
class PyOperationBase
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
class PyOperation
class PyOpView
A PyOpView is equivalent to the C++ "Op" wrappers: these are the basis for providing more instance-specific accessors and serve as the base class for custom ODS-style operation classes.
class PyRegion
Wrapper around an MlirRegion.
class PyAsmState
Wrapper around an MlirAsmState.
class PyBlock
Wrapper around an MlirBlock.
class PyInsertionPoint
An insertion point maintains a pointer to a Block and a reference operation.
class PyType
Wrapper around the generic MlirType.
class PyTypeID
A TypeID provides an efficient and unique identifier for a specific C++ type.
class PyConcreteType
CRTP base classes for Python types that subclass Type and should be castable from it (i.e.
class PyAttribute
Wrapper around the generic MlirAttribute.
class PyNamedAttribute
Represents a Python MlirNamedAttr, carrying an optional owned name.
class PyConcreteAttribute
CRTP base classes for Python attributes that subclass Attribute and should be castable from it (i.e.
class PyValue
Wrapper around the generic MlirValue.
class PyAffineExpr
Wrapper around MlirAffineExpr. Affine expressions are owned by the context.
class PyAffineMap
class PyIntegerSet
class PySymbolTable
Bindings for MLIR symbol tables.
struct MLIRError
Custom exception that allows access to error diagnostic information.
class Defaulting
CRTP template for special wrapper types that are allowed to be passed in as 'None' function arguments and can be resolved by some global mechanic if so.
Typedefs
using PyMlirContextRef = PyObjectRef< PyMlirContext >
Wrapper around MlirContext.
using PyModuleRef = PyObjectRef< PyModule >
using PyOperationRef = PyObjectRef< PyOperation >
Functions
void populateIRInterfaces (nb::module_ &m)
void populateIRAffine (nanobind::module_ &m)
void populateIRAttributes (nanobind::module_ &m)
void populateIRCore (nanobind::module_ &m)
void populateIRInterfaces (nanobind::module_ &m)
void populateIRTypes (nanobind::module_ &m)
void populatePassManagerSubmodule (nanobind::module_ &m)
void populateRewriteSubmodule (nanobind::module_ &m)
Variables
constexpr static const char * constructorDoc
constexpr static const char * operationDoc
constexpr static const char * opviewDoc
constexpr static const char * inferReturnTypesDoc
constexpr static const char * inferReturnTypeComponentsDoc
Typedef Documentation
PyMlirContextRef
using mlir::python::PyMlirContextRef = typedef PyObjectRef<PyMlirContext>
Wrapper around MlirContext.
Definition at line 187 of file IRModule.h.
PyModuleRef
using mlir::python::PyModuleRef = typedef PyObjectRef<PyModule>
Definition at line 558 of file IRModule.h.
PyOperationRef
using mlir::python::PyOperationRef = typedef PyObjectRef<PyOperation>
Definition at line 649 of file IRModule.h.
Function Documentation
populateIRAffine()
void mlir::python::populateIRAffine (nanobind::module_ & m)
Referenced by NB_MODULE().
populateIRAttributes()
void mlir::python::populateIRAttributes (nanobind::module_ & m)
Referenced by NB_MODULE().
populateIRCore()
void mlir::python::populateIRCore (nanobind::module_ & m)
Referenced by NB_MODULE().
populateIRInterfaces() [1/2]
void mlir::python::populateIRInterfaces (nanobind::module_ & m)
populateIRInterfaces() [2/2]
void mlir::python::populateIRInterfaces (nb::module_ & m)
Definition at line 475 of file IRInterfaces.cpp.
References mlir::python::PyConcreteOpInterface< PyInferShapedTypeOpInterface >::bind(), mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >::bind(), and mlir::python::PyShapedTypeComponents::bind().
Referenced by NB_MODULE().
populateIRTypes()
void mlir::python::populateIRTypes (nanobind::module_ & m)
Referenced by NB_MODULE().
populatePassManagerSubmodule()
void mlir::python::populatePassManagerSubmodule (nanobind::module_ & m)
Referenced by NB_MODULE().
populateRewriteSubmodule()
void mlir::python::populateRewriteSubmodule (nanobind::module_ & m)
Referenced by NB_MODULE().
Variable Documentation
constructorDoc
constexpr static const char* mlir::python::constructorDoc static constexpr
Initial value:
=
    R"(Creates an interface from a given operation/opview object or from a
subclass of OpView. Raises ValueError if the operation does not implement the
interface.)"
Definition at line 29 of file IRInterfaces.cpp.
Referenced by mlir::python::PyConcreteOpInterface< ConcreteIface >::bind().
inferReturnTypeComponentsDoc
constexpr static const char* mlir::python::inferReturnTypeComponentsDoc static constexpr
Initial value:
=
    R"(Given the arguments required to build an operation, attempts to infer
its return shaped type components. Raises ValueError on failure.)"
Definition at line 45 of file IRInterfaces.cpp.
Referenced by mlir::python::PyInferShapedTypeOpInterface::bindDerived().
inferReturnTypesDoc
constexpr static const char* mlir::python::inferReturnTypesDoc static constexpr
Initial value:
=
    R"(Given the arguments required to build an operation, attempts to infer
its return types. Raises ValueError on failure.)"
Definition at line 41 of file IRInterfaces.cpp.
Referenced by mlir::python::PyInferTypeOpInterface::bindDerived().
operationDoc
constexpr static const char* mlir::python::operationDoc static constexpr
Initial value:
=
    R"(Returns an Operation for which the interface was constructed.)"
Definition at line 34 of file IRInterfaces.cpp.
Referenced by mlir::python::PyConcreteOpInterface< ConcreteIface >::bind().
opviewDoc
constexpr static const char* mlir::python::opviewDoc static constexpr
Initial value:
=
    R"(Returns an OpView subclass _instance_ for which the interface was
constructed)"
Definition at line 37 of file IRInterfaces.cpp.
Referenced by mlir::python::PyConcreteOpInterface< ConcreteIface >::bind().