MLIR: mlir::vector::impl Namespace Reference
mlir::vector::impl Namespace Reference
Functions
AffineMap getTransferMinorIdentityMap (ShapedType shapedType, VectorType vectorType)
Build the default minor identity map suitable for a vector transfer.
Function Documentation
getTransferMinorIdentityMap()
AffineMap mlir::vector::impl::getTransferMinorIdentityMap (ShapedType shapedType, VectorType vectorType)
Build the default minor identity map suitable for a vector transfer.
This also handles the case memref<... x vector<...>> -> vector<...> in which the rank of the identity map must take the vector element type into account.
Referenced by foldTransferInBoundsAttribute(), getEnclosingforOps(), parseTransferReadOp(), and verifyTransferOp().