MLIR: mlir::function_like_impl::detail Namespace Reference
mlir::function_like_impl::detail Namespace Reference
Functions
void setArgResAttrDict (Operation *op, StringRef attrName, unsigned numTotalIndices, unsigned index, DictionaryAttr attrs)
Update the given index into an argument or result attribute dictionary.
Function Documentation
setArgResAttrDict()
void mlir::function_like_impl::detail::setArgResAttrDict (Operation * op, StringRef attrName, unsigned numTotalIndices, unsigned index, DictionaryAttr attrs)
Update the given index into an argument or result attribute dictionary.
Definition at line 54 of file FunctionSupport.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getContext(), isEmptyAttrDict(), mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs().