MLIR: mlir::pdll::ast Namespace Reference
mlir::pdll::ast Namespace Reference
Namespaces
detail
Classes
class Context
This class represents the main context of the PDLL AST.
class Diagnostic
This class provides a simple implementation of a PDLL diagnostic.
class InFlightDiagnostic
This class represents a diagnostic that is inflight and set to be reported.
class DiagnosticEngine
This class manages the construction and emission of PDLL diagnostics.
struct Name
This class provides a convenient API for interacting with source names.
class DeclScope
This class represents a scope for named AST decls.
class Node
This class represents a base AST node.
class Stmt
This class represents a base AST Statement node.
class CompoundStmt
This statement represents a compound statement, which contains a collection of other statements.
class LetStmt
This statement represents a let statement in PDLL.
class OpRewriteStmt
This class represents a base operation rewrite statement.
class EraseStmt
This statement represents the erase statement in PDLL.
class ReplaceStmt
This statement represents the replace statement in PDLL.
class RewriteStmt
This statement represents an operation rewrite that contains a block of nested rewrite commands.
class ReturnStmt
This statement represents a return from a "callable" like decl, e.g.
class Expr
This class represents a base AST Expression node.
class AttributeExpr
This expression represents a literal MLIR Attribute, and contains the textual assembly format of that attribute.
class CallExpr
This expression represents a call to a decl, such as a UserConstraintDecl/UserRewriteDecl.
class DeclRefExpr
This expression represents a reference to a Decl node.
class MemberAccessExpr
This expression represents a named member or field access of a given parent expression.
class AllResultsMemberAccessExpr
This class represents an instance of MemberAccessExpr that references all results of an operation.
class OperationExpr
This expression represents the structural form of an MLIR Operation.
class RangeExpr
This expression builds a range from a set of element values (which may be ranges themselves).
class TupleExpr
This expression builds a tuple from a set of element values.
class TypeExpr
This expression represents a literal MLIR Type, and contains the textual assembly format of that type.
class Decl
This class represents the base Decl node.
class ConstraintDecl
This class represents the base of all AST Constraint decls.
struct ConstraintRef
This class represents a reference to a constraint, and contains a constraint and the location of the reference.
class CoreConstraintDecl
This class represents the base of all "core" constraints.
class AttrConstraintDecl
The class represents an Attribute constraint, and constrains a variable to be an Attribute.
class OpConstraintDecl
The class represents an Operation constraint, and constrains a variable to be an Operation.
class TypeConstraintDecl
The class represents a Type constraint, and constrains a variable to be a Type.
class TypeRangeConstraintDecl
The class represents a TypeRange constraint, and constrains a variable to be a TypeRange.
class ValueConstraintDecl
The class represents a Value constraint, and constrains a variable to be a Value.
class ValueRangeConstraintDecl
The class represents a ValueRange constraint, and constrains a variable to be a ValueRange.
class UserConstraintDecl
This decl represents a user defined constraint.
class NamedAttributeDecl
This Decl represents a NamedAttribute, and contains a string name and attribute value.
class OpNameDecl
This Decl represents an OperationName.
class PatternDecl
This Decl represents a single Pattern.
class UserRewriteDecl
This decl represents a user defined rewrite.
class CallableDecl
This decl represents a shared interface for all callable decls.
class VariableDecl
This Decl represents the definition of a PDLL variable.
class Module
This class represents a top-level AST module.
class Type
class AttributeType
This class represents a PDLL type that corresponds to an mlir::Attribute.
class ConstraintType
This class represents a PDLL type that corresponds to a constraint.
class OperationType
This class represents a PDLL type that corresponds to an mlir::Operation.
class RangeType
This class represents a PDLL type that corresponds to a range of elements with a given element type.
class TypeRangeType
This class represents a PDLL type that corresponds to an mlir::TypeRange.
class ValueRangeType
This class represents a PDLL type that corresponds to an mlir::ValueRange.
class RewriteType
This class represents a PDLL type that corresponds to a rewrite reference.
class TupleType
This class represents a PDLL tuple type, i.e.
class TypeType
This class represents a PDLL type that corresponds to an mlir::Type.
class ValueType
This class represents a PDLL type that corresponds to an mlir::Value.
Functions
llvm::hash_code hash_value (Type type)
raw_ostream & operator<< (raw_ostream &os, Type type)
Function Documentation
hash_value()
llvm::hash_code mlir::pdll::ast::hash_value (Type type) inline
Definition at line 93 of file Types.h.
References mlir::pdll::ast::Type::getImpl().
Referenced by llvm::DenseMapInfo< mlir::pdll::ast::Type >::getHashValue().
operator<<()
raw_ostream& mlir::pdll::ast::operator<< (raw_ostream & os, Type type) inline
Definition at line 97 of file Types.h.
References mlir::pdll::ast::Type::print().