MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform Namespace Reference
Classes
struct AnyOpType
struct AnyParamType
struct AnyValueType
struct OperationType
struct ParamType
class PyPatternDescriptorOpInterface
class PyTransformOpInterface
class PyTransformResults
class PyTransformRewriter
class PyTransformState
Functions
static void populateDialectTransformSubmodule (nb::module_ &m)
Function Documentation
populateDialectTransformSubmodule()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::populateDialectTransformSubmodule (nb::module_ & m) static
Definition at line 532 of file DialectTransform.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyPatternDescriptorOpInterface >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteOpInterface< PyTransformOpInterface >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< AnyOpType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< AnyParamType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< AnyValueType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< OperationType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< ParamType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRewriterBase< PyTransformRewriter >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformResults::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformState::bind(), MlirDiagnosedSilenceableFailureDefiniteFailure, MlirDiagnosedSilenceableFailureSilenceableFailure, and MlirDiagnosedSilenceableFailureSuccess.
Referenced by NB_MODULE().