MLIR: mlir::matcher Namespace Reference
mlir::matcher Namespace Reference
Functions
NestedPattern Op (FilterFunctionType filter=defaultFilterFunction)
NestedPattern If (NestedPattern child)
NestedPattern If (FilterFunctionType filter, NestedPattern child)
NestedPattern If (ArrayRef< NestedPattern > nested={})
NestedPattern If (FilterFunctionType filter, ArrayRef< NestedPattern > nested={})
NestedPattern For (NestedPattern child)
NestedPattern For (FilterFunctionType filter, NestedPattern child)
NestedPattern For (ArrayRef< NestedPattern > nested={})
NestedPattern For (FilterFunctionType filter, ArrayRef< NestedPattern > nested={})
bool isParallelLoop (Operation &op)
bool isReductionLoop (Operation &op)
bool isLoadOrStore (Operation &op)
Function Documentation
For() [1/4]
NestedPattern mlir::matcher::For (NestedPattern child)
Definition at line 155 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
Referenced by makePattern().
For() [2/4]
NestedPattern mlir::matcher::For (FilterFunctionType filter, NestedPattern child)
Definition at line 158 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
For() [3/4]
NestedPattern mlir::matcher::For (ArrayRef< NestedPattern > nested = {})
Definition at line 162 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
For() [4/4]
NestedPattern mlir::matcher::For (FilterFunctionType filter, ArrayRef< NestedPattern > nested = {})
Definition at line 165 of file NestedMatcher.cpp.
References isAffineForOp(), and mlir::NestedPattern::NestedPattern().
If() [1/4]
NestedPattern mlir::matcher::If (NestedPattern child)
Definition at line 138 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
Referenced by isVectorizableLoopBodyWithOpCond().
If() [2/4]
NestedPattern mlir::matcher::If (FilterFunctionType filter, NestedPattern child)
Definition at line 141 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
If() [3/4]
NestedPattern mlir::matcher::If (ArrayRef< NestedPattern > nested = {})
Definition at line 146 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
If() [4/4]
NestedPattern mlir::matcher::If (FilterFunctionType filter, ArrayRef< NestedPattern > nested = {})
Definition at line 149 of file NestedMatcher.cpp.
References isAffineIfOp(), and mlir::NestedPattern::NestedPattern().
isLoadOrStore()
bool mlir::matcher::isLoadOrStore (Operation & op)
Definition at line 170 of file NestedMatcher.cpp.
References op.
Referenced by isVectorizableLoopBodyWithOpCond().
isParallelLoop()
bool mlir::matcher::isParallelLoop (Operation & op)
Referenced by mlir::sinkSequentialLoops().
isReductionLoop()
bool mlir::matcher::isReductionLoop (Operation & op)
Op()
NestedPattern mlir::matcher::Op (FilterFunctionType filter = defaultFilterFunction)
Definition at line 134 of file NestedMatcher.cpp.
References mlir::NestedPattern::NestedPattern().
Referenced by isVectorizableLoopBodyWithOpCond(), and vectorTransferPattern().