MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant Namespace Reference
Classes
struct AnyQuantizedType
struct CalibratedQuantizedType
struct QuantizedType
struct UniformQuantizedPerAxisType
struct UniformQuantizedSubChannelType
struct UniformQuantizedType
Functions
static void populateDialectQuantSubmodule (nb::module_ &m)
Function Documentation
populateDialectQuantSubmodule()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::populateDialectQuantSubmodule (nb::module_ & m) static
Definition at line 496 of file DialectQuant.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< AnyQuantizedType, QuantizedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< CalibratedQuantizedType, QuantizedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< QuantizedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedPerAxisType, QuantizedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedSubChannelType, QuantizedType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedType, QuantizedType >::bind(), and mlirQuantizedTypeGetSignedFlag().
Referenced by NB_MODULE().