MLIR: mlir::irdl Namespace Reference
mlir::irdl Namespace Reference
Namespaces
namespace detail
Classes
class AllOfConstraint
A constraint checking that all of the given constraints are satisfied.
class AnyAttributeConstraint
A constraint that is always satisfied.
class AnyOfConstraint
A constraint checking that one of the given constraints is satisfied.
class BaseAttrConstraint
A constraint that checks that an attribute is of a given attribute base (e.g.
class BaseTypeConstraint
A constraint that checks that a type is of a given type base (e.g.
class Constraint
Once turned into IRDL verifiers, all constraints are attribute constraints.
class ConstraintVerifier
Provides context to the verification of constraints.
class DynParametricAttrConstraint
A constraint that checks that an attribute is of a specific dynamic attribute definition, and that all of its parameters satisfy the given constraints.
class DynParametricTypeConstraint
A constraint that checks that a type is of a specific dynamic type definition, and that all of its parameters satisfy the given constraints.
class IsConstraint
A constraint that checks that an attribute is equal to a given attribute.
struct RegionConstraint
A constraint checking that a region satisfies irdl.region requirements.
Functions
llvm::LogicalResult loadDialects (ModuleOp op)
Load all the dialects defined in the module.
Operation * lookupSymbolNearDialect (SymbolTableCollection &symbolTable, Operation *source, SymbolRefAttr symbol)
Looks up a symbol from the symbol table containing the source operation's dialect definition operation.
Operation * lookupSymbolNearDialect (Operation *source, SymbolRefAttr symbol)
Looks up a symbol from the symbol table containing the source operation's dialect definition operation.
llvm::unique_function< LogicalResult(Operation *) const > createVerifier (OperationOp operation, const DenseMap< irdl::TypeOp, std::unique_ptr< DynamicTypeDefinition > > &typeDefs, const DenseMap< irdl::AttributeOp, std::unique_ptr< DynamicAttrDefinition > > &attrDefs)
Generate an op verifier function from the given IRDL operation definition.
LogicalResult translateIRDLDialectToCpp (llvm::ArrayRef< irdl::DialectOp > dialects, raw_ostream &output)
Translates an IRDL dialect definition to a C++ definition that can be used with MLIR.
Function Documentation
createVerifier()
llvm::unique_function< LogicalResult(Operation *) const > mlir::irdl::createVerifier (OperationOp operation, const DenseMap< irdl::TypeOp, std::unique_ptr< DynamicTypeDefinition > > & typeDefs, const DenseMap< irdl::AttributeOp, std::unique_ptr< DynamicAttrDefinition > > & attrDefs)
Generate an op verifier function from the given IRDL operation definition.
Definition at line 271 of file IRDLLoading.cpp.
References mlir::Region::getOps(), mlir::Operation::getRegion(), irdlOpVerifier(), irdlRegionVerifier(), and result.
Referenced by loadOperation().
loadDialects()
LogicalResult mlir::irdl::loadDialects (ModuleOp op)
Load all the dialects defined in the module.
Definition at line 656 of file IRDLLoading.cpp.
References mlir::WalkResult::advance(), anyOf, checkCorrectAnyOf(), getAttrOrTypeVerifier(), mlir::WalkResult::interrupt(), loadEmptyDialects(), loadOperation(), preallocateAttrDefs(), preallocateTypeDefs(), mlir::ExtensibleDialect::registerDynamicAttr(), mlir::ExtensibleDialect::registerDynamicType(), success(), and mlir::WalkResult::wasInterrupted().
Referenced by loadIRDLDialects(), and mlirLoadIRDLDialects().
lookupSymbolNearDialect() [1/2]
Operation * mlir::irdl::lookupSymbolNearDialect (Operation * source, SymbolRefAttr symbol)
Looks up a symbol from the symbol table containing the source operation's dialect definition operation.
The source operation must be nested within an IRDL dialect definition operation.
Definition at line 34 of file IRDLSymbols.cpp.
References lookupDialectOp(), and mlir::SymbolTable::lookupNearestSymbolFrom().
lookupSymbolNearDialect() [2/2]
Operation * mlir::irdl::lookupSymbolNearDialect (SymbolTableCollection & symbolTable, Operation * source, SymbolRefAttr symbol)
Looks up a symbol from the symbol table containing the source operation's dialect definition operation.
The source operation must be nested within an IRDL dialect definition operation. This exploits SymbolTableCollection for better symbol table lookup.
Definition at line 28 of file IRDLSymbols.cpp.
References lookupDialectOp(), and mlir::SymbolTableCollection::lookupNearestSymbolFrom().
Referenced by checkSymbolIsTypeOrAttribute(), and getBases().
translateIRDLDialectToCpp()
LogicalResult mlir::irdl::translateIRDLDialectToCpp (llvm::ArrayRef< irdl::DialectOp > dialects, raw_ostream & output)
Translates an IRDL dialect definition to a C++ definition that can be used with MLIR.
The following preprocessor macros will generate the following code:
// This define generates code for the dialect's class declarations #define GEN_DIALECT_DECL_HEADER
// This define generates code for the dialect's class definitions #define GEN_DIALECT_DEF
Definition at line 637 of file IRDLToCpp.cpp.
Referenced by mlir::registerIRDLToCppTranslation().