MLIR: mlir::xevm Namespace Reference
mlir::xevm Namespace Reference
Classes
class SerializeGPUModuleBase
Base class for all XeVM serializations from GPU modules into binary strings.
Functions
void registerXeVMTargetInterfaceExternalModels (mlir::DialectRegistry &registry)
Registers the TargetAttrInterface for the #xevm.target attribute in the given registry.
void registerXeVMTargetInterfaceExternalModels (mlir::MLIRContext &context)
Registers the TargetAttrInterface for the #xevm.target attribute in the registry associated with the given context.
Function Documentation
registerXeVMTargetInterfaceExternalModels() [1/2]
void mlir::xevm::registerXeVMTargetInterfaceExternalModels (mlir::DialectRegistry & registry)
Registers the TargetAttrInterface for the #xevm.target attribute in the given registry.
Definition at line 64 of file Target.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects(), and registerXeVMTargetInterfaceExternalModels().
registerXeVMTargetInterfaceExternalModels() [2/2]
void mlir::xevm::registerXeVMTargetInterfaceExternalModels (mlir::MLIRContext & context)
Registers the TargetAttrInterface for the #xevm.target attribute in the registry associated with the given context.
Definition at line 71 of file Target.cpp.
References mlir::MLIRContext::appendDialectRegistry(), and registerXeVMTargetInterfaceExternalModels().