MLIR: mlir::acc Namespace Reference
mlir::acc Namespace Reference
Namespaces
namespace AttributeTrait
namespace detail
namespace impl
Classes
struct ACCBindRoutineOptions
struct ACCComputeLoweringOptions
class ACCDeclareEnterOpConversion
Pattern to erase acc.declare_enter and its associated acc.declare_exit.
struct ACCEmitRemarksLoopOptions
struct ACCImplicitDataOptions
struct ACCImplicitRoutineOptions
struct ACCLoopTilingOptions
class ACCOpEraseConversion
Pattern to simply erase an ACC op (for ops with no results).
class ACCOpReplaceWithVarConversion
Pattern to replace an ACC op with its var operand.
class ACCParMappingPolicy
Policy class that defines how OpenACC parallelism levels map to target-specific parallel dimension attributes.
class ACCRegionUnwrapConversion
Pattern to unwrap a region from an ACC op and erase the wrapper.
struct ACCRoutineLoweringOptions
struct ACCRoutineToGPUFuncOptions
struct ACCSpecializeForHostOptions
struct ConstructResource
struct CurrentDeviceIdResource
class DefaultACCToGPUMappingPolicy
Default policy that provides the standard GPU mapping: gang(dim:1) -> BlockX (gridDim.x / blockIdx.x) gang(dim:2) -> BlockY (gridDim.y / blockIdx.y) gang(dim:3) -> BlockZ (gridDim.z / blockIdx.z) worker -> ThreadY (blockDim.y / threadIdx.y) vector -> ThreadX (blockDim.x / threadIdx.x) seq -> Sequential.
struct LegalizeDataValuesInRegionOptions
struct OffloadTargetVerifierOptions
class OpenACCSupport
struct RuntimeCounters
class VariableInfoAttr
Base attribute class for language-specific variable information carried through the OpenACC type interface helpers.
Typedefs
using ACCToGPUMappingPolicy
Type alias for the GPU-specific mapping policy.
Enumerations
enum OpenACCExecMapping { NONE = 0 , VECTOR = 1 , WORKER = 2 , GANG = 4 }
Enumeration used to encode the execution mapping on a loop construct.
Functions
mlir::Value getVar (mlir::Operation *accDataClauseOp)
Used to obtain the var from a data clause operation.
mlir::TypedValue< mlir::acc::PointerLikeType > getVarPtr (mlir::Operation *accDataClauseOp)
Used to obtain the var from a data clause operation if it implements PointerLikeType.
mlir::Type getVarType (mlir::Operation *accDataClauseOp)
Used to obtains the varType from a data clause operation which records the type of variable.
mlir::Value getAccVar (mlir::Operation *accDataClauseOp)
Used to obtain the accVar from a data clause operation.
mlir::TypedValue< mlir::acc::PointerLikeType > getAccPtr (mlir::Operation *accDataClauseOp)
Used to obtain the accVar from a data clause operation if it implements PointerLikeType.
mlir::Value getVarPtrPtr (mlir::Operation *accDataClauseOp)
Used to obtain the varPtrPtr from a data clause operation.
mlir::SmallVector< mlir::Value > getBounds (mlir::Operation *accDataClauseOp)
Used to obtain bounds from an acc data clause operation.
mlir::SmallVector< mlir::Value > getAsyncOperands (mlir::Operation *accDataClauseOp)
Used to obtain async operands from an acc data clause operation.
mlir::ArrayAttr getAsyncOperandsDeviceType (mlir::Operation *accDataClauseOp)
Returns an array of acc:DeviceTypeAttr attributes attached to an acc data clause operation, that correspond to the device types associated with the async clauses with an async-value.
mlir::ArrayAttr getAsyncOnly (mlir::Operation *accDataClauseOp)
Returns an array of acc:DeviceTypeAttr attributes attached to an acc data clause operation, that correspond to the device types associated with the async clauses without an async-value.
std::optional< llvm::StringRef > getVarName (mlir::Operation *accOp)
Used to obtain the name from an acc operation.
std::optional< mlir::acc::DataClause > getDataClause (mlir::Operation *accDataEntryOp)
Used to obtain the dataClause from a data entry operation.
bool getImplicitFlag (mlir::Operation *accDataEntryOp)
Used to find out whether data operation is implicit.
mlir::ValueRange getDataOperands (mlir::Operation *accOp)
Used to get an immutable range iterating over the data operands.
mlir::MutableOperandRange getMutableDataOperands (mlir::Operation *accOp)
Used to get a mutable range iterating over the data operands.
mlir::SymbolRefAttr getRecipe (mlir::Operation *accOp)
Used to get the recipe attribute from a data clause operation.
bool isPointerLikeType (mlir::Type type)
Used to check whether the provided type implements the PointerLikeType interface.
bool isMappableType (mlir::Type type)
Used to check whether the provided type implements the MappableType interface.
static constexpr StringLiteral getDeclareAttrName ()
Used to obtain the attribute name for declare.
static constexpr StringLiteral getDeclareActionAttrName ()
static constexpr StringLiteral getRoutineInfoAttrName ()
static constexpr StringLiteral getSpecializedRoutineAttrName ()
bool isAccRoutine (mlir::Operation *op)
Used to check whether the current operation is marked with acc routine.
bool isSpecializedAccRoutine (mlir::Operation *op)
Used to check whether this is a specialized accelerator version of acc routine function.
static constexpr StringLiteral getFromDefaultClauseAttrName ()
static constexpr StringLiteral getCollapseCountAttrName ()
Name for an attribute attached to a loop indicating the number of loops collapsed to create that loop.
static constexpr StringLiteral getVarNameAttrName ()
static constexpr StringLiteral getCombinedConstructsAttrName ()
ParLevel getGangParLevel (int64_t gangDimValue)
Convert a gang dimension value (1, 2, or 3) to the corresponding ParLevel.
mlir::Operation * getEnclosingComputeOp (mlir::Region &region)
Used to obtain the enclosing compute construct operation that contains the provided region.
mlir::Value getACCOperandForBlockArg (mlir::Value v)
If v is not a block argument of an acc.compute_region body, returns nullptr.
mlir::Operation * getACCDataClauseOpForBlockArg (mlir::Value v)
If v is not a block argument of an acc.compute_region body, returns nullptr.
bool isOnlyUsedByPrivateClauses (mlir::Value val, mlir::Region &region)
Returns true if this value is only used by acc.private operations in the region.
bool isOnlyUsedByReductionClauses (mlir::Value val, mlir::Region &region)
Returns true if this value is only used by acc.reduction operations in the region.
std::optional< ClauseDefaultValue > getDefaultAttr (mlir::Operation *op)
Looks for an OpenACC default attribute on the current operation op or in a parent operation which encloses op.
mlir::acc::VariableTypeCategory getTypeCategory (mlir::Value var)
Get the type category of an OpenACC variable.
std::string getVariableName (mlir::Value v)
Attempts to extract the variable name from a value by walking through view-like operations until an acc.var_name attribute is found.
llvm::StringLiteral getVarNamePlaceholder ()
Returns a placeholder string for use as an acc.var_name attribute value when the actual variable name is not yet known at the point of IR construction.
std::string getRecipeName (mlir::acc::RecipeKind kind, mlir::Type type)
Get the recipe name for a given recipe kind and type.
mlir::Value getBaseEntity (mlir::Value val)
bool isValidSymbolUse (mlir::Operation *user, mlir::SymbolRefAttr symbol, mlir::Operation **definingOpPtr=nullptr)
Check if a symbol use is valid for use in an OpenACC region.
bool isDeviceValue (mlir::Value val)
Check if a value represents device data.
bool isValidValueUse (mlir::Value val, mlir::Region &region)
Check if a value use is valid in an OpenACC region.
llvm::SmallVector< mlir::Value > getDominatingDataClauses (mlir::Operation *computeConstructOp, mlir::DominanceInfo &domInfo, mlir::PostDominanceInfo &postDomInfo)
Collects all data clauses that dominate the compute construct.
remark::detail::InFlightRemark emitRemark (mlir::Operation *op, const std::function< std::string()> &messageFn, llvm::StringRef category="openacc")
Emit an OpenACC remark with lazy message generation.
remark::detail::InFlightRemark emitRemark (mlir::Operation *op, const llvm::Twine &message, llvm::StringRef category="openacc")
Emit an OpenACC remark for the given operation with the given message.
std::optional< DataLayout > getDataLayout (Operation *op, bool allowDefault=true)
Get the data layout for an operation.
ComputeRegionOp buildComputeRegion (Location loc, ValueRange launchArgs, ValueRange inputArgs, llvm::StringRef origin, Region &regionToClone, RewriterBase &rewriter, IRMapping &mapping, ValueRange output={}, FlatSymbolRefAttr kernelFuncName={}, FlatSymbolRefAttr kernelModuleName={}, Value stream={}, ValueRange inputArgsToMap={})
Build an acc.compute_region operation by cloning a source region.
std::optional< gpu::GPUModuleOp > getOrCreateGPUModule (ModuleOp mod, bool create=true, llvm::StringRef name=kDefaultGPUModuleName)
Get or create a GPU module in the given module.
std::pair< llvm::SmallVector< Value >, Block::iterator > cloneACCRegionInto (Region *src, Block *dest, Block::iterator inlinePoint, IRMapping &mapping, ValueRange resultsToReplace)
Clone an ACC region into a destination block at the given insertion point.
scf::ExecuteRegionOp wrapMultiBlockRegionWithSCFExecuteRegion (Region &region, IRMapping &mapping, Location loc, RewriterBase &rewriter)
Wrap a multi-block region in an scf.execute_region.
scf::ForOp convertACCLoopToSCFFor (LoopOp loopOp, RewriterBase &rewriter, bool enableCollapse)
Convert a structured acc.loop to scf.for.
scf::ParallelOp convertACCLoopToSCFParallel (LoopOp loopOp, RewriterBase &rewriter)
Convert acc.loop to scf.parallel.
scf::ExecuteRegionOp convertUnstructuredACCLoopToSCFExecuteRegion (LoopOp loopOp, RewriterBase &rewriter)
Convert an unstructured acc.loop to scf.execute_region.
void setCollapseCountAttr (Operation *op, uint64_t count)
Record on a collapsed loop how many original loops were folded into it.
uint64_t getCollapseCount (Operation *op)
Number of original loops collapsed into op, or 1 when op carries no collapse_count attribute.
llvm::SmallVector< mlir::acc::LoopOp > uncollapseLoops (mlir::acc::LoopOp origLoop, unsigned tileCount, unsigned collapseCount, mlir::RewriterBase &rewriter)
Uncollapse tile loops with multiple IVs and collapseCount < tileCount.
mlir::acc::LoopOp tileACCLoops (llvm::SmallVector< mlir::acc::LoopOp > &tileLoops, const llvm::SmallVector< mlir::Value > &tileSizes, int32_t defaultTileSize, mlir::RewriterBase &rewriter)
Tile ACC loops according to the given tile sizes.
std::unique_ptr<::mlir::Pass > createACCBindRoutine ()
std::unique_ptr<::mlir::Pass > createACCBindRoutine (ACCBindRoutineOptions options)
std::unique_ptr<::mlir::Pass > createACCComputeLowering ()
std::unique_ptr<::mlir::Pass > createACCComputeLowering (ACCComputeLoweringOptions options)
std::unique_ptr<::mlir::Pass > createACCDeclareGPUModuleInsertion ()
std::unique_ptr<::mlir::Pass > createACCEmitRemarksLoop ()
std::unique_ptr<::mlir::Pass > createACCEmitRemarksLoop (ACCEmitRemarksLoopOptions options)
std::unique_ptr<::mlir::Pass > createACCEmitRemarksPrivate ()
std::unique_ptr<::mlir::Pass > createACCIfClauseLowering ()
std::unique_ptr<::mlir::Pass > createACCImplicitData ()
std::unique_ptr<::mlir::Pass > createACCImplicitData (ACCImplicitDataOptions options)
std::unique_ptr<::mlir::Pass > createACCImplicitDeclare ()
std::unique_ptr<::mlir::Pass > createACCImplicitRoutine ()
std::unique_ptr<::mlir::Pass > createACCImplicitRoutine (ACCImplicitRoutineOptions options)
std::unique_ptr<::mlir::Pass > createACCLegalizeSerial ()
std::unique_ptr<::mlir::Pass > createACCLoopTiling ()
std::unique_ptr<::mlir::Pass > createACCLoopTiling (ACCLoopTilingOptions options)
std::unique_ptr<::mlir::Pass > createACCRecipeMaterialization ()
std::unique_ptr<::mlir::Pass > createACCRoutineLowering ()
std::unique_ptr<::mlir::Pass > createACCRoutineLowering (ACCRoutineLoweringOptions options)
std::unique_ptr<::mlir::Pass > createACCRoutineToGPUFunc ()
std::unique_ptr<::mlir::Pass > createACCRoutineToGPUFunc (ACCRoutineToGPUFuncOptions options)
std::unique_ptr<::mlir::Pass > createACCSpecializeForDevice ()
std::unique_ptr<::mlir::Pass > createACCSpecializeForHost ()
std::unique_ptr<::mlir::Pass > createACCSpecializeForHost (ACCSpecializeForHostOptions options)
std::unique_ptr<::mlir::Pass > createLegalizeDataValuesInRegion ()
std::unique_ptr<::mlir::Pass > createLegalizeDataValuesInRegion (LegalizeDataValuesInRegionOptions options)
std::unique_ptr<::mlir::Pass > createOffloadLiveInValueCanonicalization ()
std::unique_ptr<::mlir::Pass > createOffloadTargetVerifier ()
std::unique_ptr<::mlir::Pass > createOffloadTargetVerifier (OffloadTargetVerifierOptions options)
void populateACCSpecializeForDevicePatterns (RewritePatternSet &patterns)
Populates all patterns for device specialization.
void populateACCOrphanToHostPatterns (RewritePatternSet &patterns, OpenACCSupport &accSupport, bool enableLoopConversion=true)
Populates patterns for converting orphan ACC operations to host.
void populateACCHostFallbackPatterns (RewritePatternSet &patterns, OpenACCSupport &accSupport, bool enableLoopConversion=true)
Populates all patterns for host fallback path (when if clause evaluates to false).
void registerACCBindRoutine ()
void registerACCBindRoutinePass ()
void registerACCComputeLowering ()
void registerACCComputeLoweringPass ()
void registerACCDeclareGPUModuleInsertion ()
void registerACCDeclareGPUModuleInsertionPass ()
void registerACCEmitRemarksLoop ()
void registerACCEmitRemarksLoopPass ()
void registerACCEmitRemarksPrivate ()
void registerACCEmitRemarksPrivatePass ()
void registerACCIfClauseLowering ()
void registerACCIfClauseLoweringPass ()
void registerACCImplicitData ()
void registerACCImplicitDataPass ()
void registerACCImplicitDeclare ()
void registerACCImplicitDeclarePass ()
void registerACCImplicitRoutine ()
void registerACCImplicitRoutinePass ()
void registerACCLegalizeSerial ()
void registerACCLegalizeSerialPass ()
void registerACCLoopTiling ()
void registerACCLoopTilingPass ()
void registerACCRecipeMaterialization ()
void registerACCRecipeMaterializationPass ()
void registerACCRoutineLowering ()
void registerACCRoutineLoweringPass ()
void registerACCRoutineToGPUFunc ()
void registerACCRoutineToGPUFuncPass ()
void registerACCSpecializeForDevice ()
void registerACCSpecializeForDevicePass ()
void registerACCSpecializeForHost ()
void registerACCSpecializeForHostPass ()
void registerLegalizeDataValuesInRegion ()
void registerLegalizeDataValuesInRegionPass ()
void registerOffloadLiveInValueCanonicalization ()
void registerOffloadLiveInValueCanonicalizationPass ()
void registerOffloadTargetVerifier ()
void registerOffloadTargetVerifierPass ()
void registerOpenACCPasses ()
Variables
constexpr llvm::StringLiteral kDefaultGPUModuleName = "acc_gpu_module"
Default GPU module name used by OpenACC.
Typedef Documentation
ACCToGPUMappingPolicy
using mlir::acc::ACCToGPUMappingPolicy
Initial value:
    ACCParMappingPolicy<mlir::acc::GPUParallelDimAttr>
Type alias for the GPU-specific mapping policy.
Definition at line 158 of file OpenACCParMapping.h.
Enumeration Type Documentation
OpenACCExecMapping
enum mlir::acc::OpenACCExecMapping
Enumeration used to encode the execution mapping on a loop construct.
They refer directly to the OpenACC 3.3 standard: 2.9.2. gang 2.9.3. worker 2.9.4. vector
Value can be combined bitwise to reflect the mapping applied to the construct. e.g. acc.loop gang vector, the gang and vector could be combined and the final mapping value would be 5 (4 | 1).
Enumerator
NONE
VECTOR
WORKER
GANG
Definition at line 91 of file OpenACC.h.
Function Documentation
buildComputeRegion()
ComputeRegionOp mlir::acc::buildComputeRegion (Location loc, ValueRange launchArgs, ValueRange inputArgs, llvm::StringRef origin, Region & regionToClone, RewriterBase & rewriter, IRMapping & mapping, ValueRange output = {}, FlatSymbolRefAttr kernelFuncName = {}, FlatSymbolRefAttr kernelModuleName = {}, Value stream = {}, ValueRange inputArgsToMap = {})
Build an acc.compute_region operation by cloning a source region.
Creates a new acc.compute_region with the given launch arguments and origin string, then clones the operations from regionToClone into its body. Launch operands should be acc.par_width results (index); the region entry block gets matching index block arguments first, then arguments for each ins operand. Multi-block regions are wrapped with scf.execute_region.
The mapping is used and updated during cloning, allowing callers to track value correspondences. Optional output, kernelFuncName, kernelModuleName, and stream arguments are forwarded to the op.
When inputArgsToMap is non-empty, it is used as the key set for the clone mapping (instead of inputArgs). Use this when cloning a region that references one set of values (e.g. the source function's args) while the op's operands are another set (e.g. the current block's args). inputArgsToMap must have the same size as inputArgs when provided.
Definition at line 58 of file OpenACCUtilsCG.cpp.
References mlir::Block::addArgument(), mlir::OpBuilder::clone(), mlir::OpBuilder::createBlock(), mlir::RewriterBase::eraseOp(), mlir::Region::front(), mlir::Block::getArgument(), mlir::Region::getBlocks(), mlir::Builder::getIndexType(), mlir::Block::getOperations(), mlir::IRMapping::lookup(), mlir::IRMapping::map(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and wrapMultiBlockRegionWithSCFExecuteRegion().
cloneACCRegionInto()
std::pair< SmallVector< Value >, Block::iterator > mlir::acc::cloneACCRegionInto (Region * src, Block * dest, Block::iterator inlinePoint, IRMapping & mapping, ValueRange resultsToReplace)
Clone an ACC region into a destination block at the given insertion point.
Requires a single-block source region. Maps block arguments and optional result replacement: values in resultsToReplace are replaced with the operands of the cloned region's acc.yield (1:1). Erases acc.yield/terminator and merges blocks. Returns (replacement values, insertion point after clone).
Definition at line 106 of file OpenACCUtilsLoop.cpp.
References mlir::Region::cloneInto(), mlir::Block::end(), mlir::Block::erase(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::Block::getTerminator(), mlir::Region::hasOneBlock(), mlir::replaceAllUsesInRegionWith(), replacement(), and mlir::Block::splitBlock().
convertACCLoopToSCFFor()
scf::ForOp mlir::acc::convertACCLoopToSCFFor (LoopOp loopOp, RewriterBase & rewriter, bool enableCollapse)
Convert a structured acc.loop to scf.for.
The loop arguments are converted to index type. If enableCollapse is true, nested loops are collapsed into a single loop.
Parameters
loopOp The acc.loop operation to convert (must not be unstructured)
rewriter RewriterBase for creating operations
enableCollapse Whether to collapse nested loops into one
Returns
The created scf.for operation or nullptr on creation error. An InFlightDiagnostic is emitted on creation error.
Definition at line 183 of file OpenACCUtilsLoop.cpp.
References mlir::coalesceLoops(), mlir::arith::ConstantIndexOp::create(), mlir::OpBuilder::getInsertionPoint(), mlir::IRMapping::map(), setCollapseCountAttr(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::Value::use_empty().
convertACCLoopToSCFParallel()
scf::ParallelOp mlir::acc::convertACCLoopToSCFParallel (LoopOp loopOp, RewriterBase & rewriter)
Convert acc.loop to scf.parallel.
The loop induction variables are converted to index types.
Parameters
loopOp The acc.loop operation to convert
rewriter RewriterBase for creating and erasing operations
Returns
The created scf.parallel operation or nullptr on creation error. An InFlightDiagnostic is emitted on creation error.
Definition at line 263 of file OpenACCUtilsLoop.cpp.
References mlir::arith::ConstantIndexOp::create(), mlir::RewriterBase::eraseOp(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::Block::getParentOp(), mlir::OpBuilder::setInsertionPointToStart(), mlir::Value::use_empty(), and wrapMultiBlockRegionWithSCFExecuteRegion().
convertUnstructuredACCLoopToSCFExecuteRegion()
scf::ExecuteRegionOp mlir::acc::convertUnstructuredACCLoopToSCFExecuteRegion (LoopOp loopOp, RewriterBase & rewriter)
Convert an unstructured acc.loop to scf.execute_region.
Parameters
loopOp The acc.loop operation to convert (must be unstructured)
rewriter RewriterBase for creating and erasing operations
Returns
The created scf.execute_region operation or nullptr on creation error. An InFlightDiagnostic is emitted on creation error.
Definition at line 327 of file OpenACCUtilsLoop.cpp.
References mlir::OpBuilder::getInsertionBlock(), mlir::Block::getParentOp(), and wrapMultiBlockRegionWithSCFExecuteRegion().
createACCBindRoutine() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCBindRoutine ()
Definition at line 119 of file ACCBindRoutine.cpp.
createACCBindRoutine() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCBindRoutine (ACCBindRoutineOptions options)
Definition at line 123 of file ACCBindRoutine.cpp.
createACCComputeLowering() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCComputeLowering ()
Definition at line 222 of file ACCComputeLowering.cpp.
References mlir::acc::ACCParMappingPolicy< ParDimAttrT >::gangDim(), and getGangParLevel().
createACCComputeLowering() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCComputeLowering (ACCComputeLoweringOptions options)
Definition at line 226 of file ACCComputeLowering.cpp.
createACCDeclareGPUModuleInsertion()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCDeclareGPUModuleInsertion ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 302 of file ACCDeclareGPUModuleInsertion.cpp.
createACCEmitRemarksLoop() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCEmitRemarksLoop ()
Definition at line 393 of file ACCEmitRemarksLoop.cpp.
createACCEmitRemarksLoop() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCEmitRemarksLoop (ACCEmitRemarksLoopOptions options)
Definition at line 397 of file ACCEmitRemarksLoop.cpp.
createACCEmitRemarksPrivate()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCEmitRemarksPrivate ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 472 of file ACCEmitRemarksPrivate.cpp.
createACCIfClauseLowering()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCIfClauseLowering ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 548 of file ACCIfClauseLowering.cpp.
createACCImplicitData() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCImplicitData ()
Definition at line 644 of file ACCImplicitData.cpp.
createACCImplicitData() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCImplicitData (ACCImplicitDataOptions options)
Definition at line 648 of file ACCImplicitData.cpp.
References getBaseEntity(), and mlir::Value::getDefiningOp().
createACCImplicitDeclare()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCImplicitDeclare ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 723 of file ACCImplicitDeclare.cpp.
createACCImplicitRoutine() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCImplicitRoutine ()
Definition at line 820 of file ACCImplicitRoutine.cpp.
createACCImplicitRoutine() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCImplicitRoutine (ACCImplicitRoutineOptions options)
Definition at line 824 of file ACCImplicitRoutine.cpp.
createACCLegalizeSerial()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCLegalizeSerial ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 900 of file ACCLegalizeSerial.cpp.
createACCLoopTiling() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCLoopTiling ()
Definition at line 992 of file ACCLoopTiling.cpp.
createACCLoopTiling() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCLoopTiling (ACCLoopTilingOptions options)
Definition at line 996 of file ACCLoopTiling.cpp.
createACCRecipeMaterialization()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCRecipeMaterialization ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1072 of file ACCRecipeMaterialization.cpp.
createACCRoutineLowering() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCRoutineLowering ()
Definition at line 1171 of file ACCRoutineLowering.cpp.
createACCRoutineLowering() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCRoutineLowering (ACCRoutineLoweringOptions options)
Definition at line 1175 of file ACCRoutineLowering.cpp.
createACCRoutineToGPUFunc() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCRoutineToGPUFunc ()
Definition at line 1272 of file ACCRoutineToGPUFunc.cpp.
createACCRoutineToGPUFunc() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCRoutineToGPUFunc (ACCRoutineToGPUFuncOptions options)
Definition at line 1276 of file ACCRoutineToGPUFunc.cpp.
createACCSpecializeForDevice()
std::unique_ptr<::mlir::Pass > mlir::acc::createACCSpecializeForDevice ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1351 of file ACCSpecializeForDevice.cpp.
createACCSpecializeForHost() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCSpecializeForHost ()
Definition at line 1443 of file ACCSpecializeForHost.cpp.
createACCSpecializeForHost() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createACCSpecializeForHost (ACCSpecializeForHostOptions options)
Definition at line 1447 of file ACCSpecializeForHost.cpp.
createLegalizeDataValuesInRegion() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createLegalizeDataValuesInRegion ()
Definition at line 1541 of file LegalizeDataValues.cpp.
createLegalizeDataValuesInRegion() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createLegalizeDataValuesInRegion (LegalizeDataValuesInRegionOptions options)
Definition at line 1545 of file LegalizeDataValues.cpp.
createOffloadLiveInValueCanonicalization()
std::unique_ptr<::mlir::Pass > mlir::acc::createOffloadLiveInValueCanonicalization ()
We declare an explicit private instantiation because Pass classes should only be visible by the current library.
Definition at line 1620 of file OffloadLiveInValueCanonicalization.cpp.
createOffloadTargetVerifier() [1/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createOffloadTargetVerifier ()
Definition at line 1720 of file OffloadTargetVerifier.cpp.
createOffloadTargetVerifier() [2/2]
std::unique_ptr<::mlir::Pass > mlir::acc::createOffloadTargetVerifier (OffloadTargetVerifierOptions options)
Definition at line 1724 of file OffloadTargetVerifier.cpp.
emitRemark() [1/2]
remark::detail::InFlightRemark mlir::acc::emitRemark (mlir::Operation * op, const llvm::Twine & message, llvm::StringRef category = "openacc") inline
Emit an OpenACC remark for the given operation with the given message.
Parameters
op The operation to emit the remark for.
message The remark message.
category Optional category for the remark. Defaults to "openacc".
Returns
An in-flight remark object that can be used to append additional information to the remark.
Definition at line 150 of file OpenACCUtils.h.
References emitRemark().
emitRemark() [2/2]
mlir::remark::detail::InFlightRemark mlir::acc::emitRemark (mlir::Operation * op, const std::function< std::string()> & messageFn, llvm::StringRef category = "openacc")
Emit an OpenACC remark with lazy message generation.
The messageFn is only invoked if remarks are enabled, allowing callers to avoid constructing expensive messages when remarks are disabled.
Parameters
op The operation to emit the remark for.
messageFn A callable that returns the remark message.
category Optional category for the remark. Defaults to "openacc".
Returns
An in-flight remark object that can be used to append additional information to the remark.
Definition at line 371 of file OpenACCUtils.cpp.
References mlir::Attribute::getContext(), mlir::Operation::getLoc(), mlir::Operation::getParentOfType(), mlir::MLIRContext::getRemarkEngine(), and mlir::remark::RemarkOpts::name().
Referenced by mlir::acc::detail::OpenACCSupportTraits::Model< ImplT >::emitRemark(), emitRemark(), and mlir::acc::OpenACCSupport::emitRemark().
getACCDataClauseOpForBlockArg()
mlir::Operation * mlir::acc::getACCDataClauseOpForBlockArg (mlir::Value v)
If v is not a block argument of an acc.compute_region body, returns nullptr.
Otherwise maps the block argument to its operand and returns the defining operation if it is one of ACC_DATA_ENTRY_OPS.
Definition at line 43 of file OpenACCUtils.cpp.
References getACCOperandForBlockArg(), and mlir::Value::getDefiningOp().
getACCOperandForBlockArg()
mlir::Value mlir::acc::getACCOperandForBlockArg (mlir::Value v)
If v is not a block argument of an acc.compute_region body, returns nullptr.
Otherwise maps the block argument to its operand and returns it.
Definition at line 28 of file OpenACCUtils.cpp.
References mlir::Block::getParentOp().
Referenced by getACCDataClauseOpForBlockArg().
getAccPtr()
mlir::TypedValue< mlir::acc::PointerLikeType > mlir::acc::getAccPtr (mlir::Operation * accDataClauseOp)
Used to obtain the accVar from a data clause operation if it implements PointerLikeType.
Definition at line 5236 of file OpenACC.cpp.
getAccVar()
mlir::Value mlir::acc::getAccVar (mlir::Operation * accDataClauseOp)
Used to obtain the accVar from a data clause operation.
When a data entry operation, it obtains its result accVar value. If a data exit operation, it obtains its operand accVar value. Returns empty value if not a data clause operation.
Definition at line 5248 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS, and ACC_DATA_EXIT_OPS.
getAsyncOnly()
mlir::ArrayAttr mlir::acc::getAsyncOnly (mlir::Operation * accDataClauseOp)
Returns an array of acc:DeviceTypeAttr attributes attached to an acc data clause operation, that correspond to the device types associated with the async clauses without an async-value.
Definition at line 5303 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS, and ACC_DATA_EXIT_OPS.
getAsyncOperands()
mlir::SmallVector< mlir::Value > mlir::acc::getAsyncOperands (mlir::Operation * accDataClauseOp)
Used to obtain async operands from an acc data clause operation.
Returns an empty vector if there are no such operands.
Definition at line 5281 of file OpenACC.cpp.
getAsyncOperandsDeviceType()
mlir::ArrayAttr mlir::acc::getAsyncOperandsDeviceType (mlir::Operation * accDataClauseOp)
Returns an array of acc:DeviceTypeAttr attributes attached to an acc data clause operation, that correspond to the device types associated with the async clauses with an async-value.
Definition at line 5295 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS, and ACC_DATA_EXIT_OPS.
getBaseEntity()
mlir::Value mlir::acc::getBaseEntity (mlir::Value val)
Definition at line 182 of file OpenACCUtils.cpp.
References mlir::Value::getDefiningOp().
Referenced by createACCImplicitData().
getBounds()
mlir::SmallVector< mlir::Value > mlir::acc::getBounds (mlir::Operation * accDataClauseOp)
Used to obtain bounds from an acc data clause operation.
Returns an empty vector if there are no bounds.
Definition at line 5266 of file OpenACC.cpp.
Referenced by mlir::acc::impl::ACCImplicitDataBase< DerivedT >::createACCImplicitData.
getCollapseCount()
uint64_t mlir::acc::getCollapseCount (Operation * op)
Number of original loops collapsed into op, or 1 when op carries no collapse_count attribute.
Definition at line 346 of file OpenACCUtilsLoop.cpp.
References mlir::Operation::getAttrOfType(), and getCollapseCountAttrName().
getCollapseCountAttrName()
constexpr StringLiteral mlir::acc::getCollapseCountAttrName () static constexpr
Name for an attribute attached to a loop indicating the number of loops collapsed to create that loop.
Definition at line 211 of file OpenACC.h.
Referenced by getCollapseCount(), and setCollapseCountAttr().
getCombinedConstructsAttrName()
constexpr StringLiteral mlir::acc::getCombinedConstructsAttrName () static constexpr
Definition at line 219 of file OpenACC.h.
getDataClause()
std::optional< mlir::acc::DataClause > mlir::acc::getDataClause (mlir::Operation * accDataEntryOp)
Used to obtain the dataClause from a data entry operation.
Returns empty optional if not a data entry operation.
Definition at line 5321 of file OpenACC.cpp.
Referenced by checkDeclareOperands(), and mlir::acc::impl::ACCImplicitDataBase< DerivedT >::createACCImplicitData.
getDataLayout()
std::optional< DataLayout > mlir::acc::getDataLayout (Operation * op, bool allowDefault = true)
Get the data layout for an operation.
Attempts to get the data layout from the operation or its parent module. If allowDefault is true (default), a default data layout may be constructed when no explicit data layout spec is found.
Parameters
op The operation to get the data layout for.
allowDefault If true, allow returning a default data layout.
Returns
The data layout if available, std::nullopt otherwise.
Definition at line 23 of file OpenACCUtilsCG.cpp.
References mlir::Operation::getParentOfType(), and mlir::Operation::getParentOp().
getDataOperands()
mlir::ValueRange mlir::acc::getDataOperands (mlir::Operation * accOp)
Used to get an immutable range iterating over the data operands.
Definition at line 5339 of file OpenACC.cpp.
References ACC_COMPUTE_AND_DATA_CONSTRUCT_OPS.
getDeclareActionAttrName()
constexpr StringLiteral mlir::acc::getDeclareActionAttrName () static constexpr
Definition at line 181 of file OpenACC.h.
getDeclareAttrName()
constexpr StringLiteral mlir::acc::getDeclareAttrName () static constexpr
Used to obtain the attribute name for declare.
Definition at line 177 of file OpenACC.h.
Referenced by isDeviceValue(), and isValidSymbolUse().
getDefaultAttr()
std::optional< mlir::acc::ClauseDefaultValue > mlir::acc::getDefaultAttr (mlir::Operation * op)
Looks for an OpenACC default attribute on the current operation op or in a parent operation which encloses op.
This is useful because OpenACC specification notes that a visible default clause is the nearest default clause appearing on the compute construct or a lexically containing data construct.
Definition at line 75 of file OpenACCUtils.cpp.
References mlir::Operation::getParentOp().
getDominatingDataClauses()
llvm::SmallVector< mlir::Value > mlir::acc::getDominatingDataClauses (mlir::Operation * computeConstructOp, mlir::DominanceInfo & domInfo, mlir::PostDominanceInfo & postDomInfo)
Collects all data clauses that dominate the compute construct.
This includes data clauses from:
The compute construct itself
Enclosing data constructs
Applicable declare directives (those that dominate and post-dominate) This is used to determine if a variable is already covered by an existing data clause.
Parameters
computeConstructOp The compute construct operation
domInfo Dominance information
postDomInfo Post-dominance information
Returns
Vector of data clause values that dominate the compute construct
Definition at line 312 of file OpenACCUtils.cpp.
References mlir::DominanceInfo::dominates(), mlir::Operation::getParentOfType(), and mlir::Operation::getParentOp().
getEnclosingComputeOp()
mlir::Operation * mlir::acc::getEnclosingComputeOp (mlir::Region & region)
Used to obtain the enclosing compute construct operation that contains the provided region.
Returns nullptr if no compute construct operation is found. The returned operation is one of types defined by ACC_COMPUTE_CONSTRUCT_OPS.
Definition at line 23 of file OpenACCUtils.cpp.
References ACC_COMPUTE_CONSTRUCT_OPS, and mlir::Region::getParentOfType().
getFromDefaultClauseAttrName()
constexpr StringLiteral mlir::acc::getFromDefaultClauseAttrName () static constexpr
Definition at line 205 of file OpenACC.h.
getGangParLevel()
ParLevel mlir::acc::getGangParLevel (int64_t gangDimValue) inline
Convert a gang dimension value (1, 2, or 3) to the corresponding ParLevel.
Asserts if the value is not a valid gang dimension.
Definition at line 33 of file OpenACCParMapping.h.
Referenced by createACCComputeLowering().
getImplicitFlag()
bool mlir::acc::getImplicitFlag (mlir::Operation * accDataEntryOp)
Used to find out whether data operation is implicit.
Returns false if not a data operation or if it is a data operation without implicit flag.
Definition at line 5331 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS.
getMutableDataOperands()
mlir::MutableOperandRange mlir::acc::getMutableDataOperands (mlir::Operation * accOp)
Used to get a mutable range iterating over the data operands.
Definition at line 5349 of file OpenACC.cpp.
References ACC_COMPUTE_AND_DATA_CONSTRUCT_OPS.
getOrCreateGPUModule()
std::optional< gpu::GPUModuleOp > mlir::acc::getOrCreateGPUModule (ModuleOp mod, bool create = true, llvm::StringRef name = kDefaultGPUModuleName)
Get or create a GPU module in the given module.
If a GPU module with the specified name already exists, it is returned. If create is true and no GPU module exists, one is created. If create is false and no GPU module exists, std::nullopt is returned.
Parameters
mod The module to search or create the GPU module in.
create If true (default), create the GPU module if it doesn't exist.
name The name for the GPU module. If empty, uses kDefaultGPUModuleName.
Returns
The GPU module if found or created, std::nullopt otherwise.
Definition at line 20 of file OpenACCUtilsGPU.cpp.
References mlir::SymbolTable::insert(), kDefaultGPUModuleName, and mlir::SymbolTable::lookup().
Referenced by mlir::acc::detail::OpenACCSupportTraits::Model< ImplT >::getOrCreateGPUModule(), and mlir::acc::OpenACCSupport::getOrCreateGPUModule().
getRecipe()
mlir::SymbolRefAttr mlir::acc::getRecipe (mlir::Operation * accOp)
Used to get the recipe attribute from a data clause operation.
Definition at line 5358 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS.
getRecipeName()
std::string mlir::acc::getRecipeName (mlir::acc::RecipeKind kind, mlir::Type type)
Get the recipe name for a given recipe kind and type.
Returns an empty string if not possible to generate a recipe name.
Definition at line 144 of file OpenACCUtils.cpp.
References mlir::Type::print().
Referenced by mlir::acc::OpenACCSupport::getRecipeName().
getRoutineInfoAttrName()
constexpr StringLiteral mlir::acc::getRoutineInfoAttrName () static constexpr
Definition at line 185 of file OpenACC.h.
Referenced by mlir::acc::impl::ACCBindRoutineBase< DerivedT >::createACCBindRoutine, isAccRoutine(), and isValidSymbolUse().
getSpecializedRoutineAttrName()
constexpr StringLiteral mlir::acc::getSpecializedRoutineAttrName () static constexpr
Definition at line 189 of file OpenACC.h.
Referenced by isSpecializedAccRoutine().
getTypeCategory()
mlir::acc::VariableTypeCategory mlir::acc::getTypeCategory (mlir::Value var)
Get the type category of an OpenACC variable.
Definition at line 96 of file OpenACCUtils.cpp.
References mlir::Value::getType().
getVar()
mlir::Value mlir::acc::getVar (mlir::Operation * accDataClauseOp)
Used to obtain the var from a data clause operation.
Returns empty value if not a data clause operation or is a data exit operation with no var.
Definition at line 5217 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS.
Referenced by checkDeclareOperands().
getVariableName()
std::string mlir::acc::getVariableName (mlir::Value v)
Attempts to extract the variable name from a value by walking through view-like operations until an acc.var_name attribute is found.
Returns empty string if no name is found.
Definition at line 113 of file OpenACCUtils.cpp.
References getConstantIntValue(), mlir::Value::getDefiningOp(), getVarName(), and getVarNameAttrName().
Referenced by mlir::acc::OpenACCSupport::getVariableName().
getVarName()
std::optional< llvm::StringRef > mlir::acc::getVarName (mlir::Operation * accOp)
Used to obtain the name from an acc operation.
Definition at line 5310 of file OpenACC.cpp.
Referenced by mlir::acc::impl::ACCImplicitDataBase< DerivedT >::createACCImplicitData, and getVariableName().
getVarNameAttrName()
constexpr StringLiteral mlir::acc::getVarNameAttrName () static constexpr
Definition at line 215 of file OpenACC.h.
Referenced by getVariableName().
getVarNamePlaceholder()
llvm::StringLiteral mlir::acc::getVarNamePlaceholder ()
Returns a placeholder string for use as an acc.var_name attribute value when the actual variable name is not yet known at the point of IR construction.
The placeholder is meant to be replaced with the real name at a later lowering stage. For example, recipe init regions may attach this to ops at recipe-generation time, and ACCRecipeMaterialization will subsequently replace the placeholder with the actual variable name on all marked ops after inlining the recipe into the compute construct.
Definition at line 109 of file OpenACCUtils.cpp.
getVarPtr()
mlir::TypedValue< mlir::acc::PointerLikeType > mlir::acc::getVarPtr (mlir::Operation * accDataClauseOp)
Used to obtain the var from a data clause operation if it implements PointerLikeType.
Definition at line 5203 of file OpenACC.cpp.
getVarPtrPtr()
mlir::Value mlir::acc::getVarPtrPtr (mlir::Operation * accDataClauseOp)
Used to obtain the varPtrPtr from a data clause operation.
Returns empty value if not a data clause operation.
Definition at line 5256 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS.
getVarType()
mlir::Type mlir::acc::getVarType (mlir::Operation * accDataClauseOp)
Used to obtains the varType from a data clause operation which records the type of variable.
When var is PointerLikeType, this returns the type of the pointer target.
Definition at line 5225 of file OpenACC.cpp.
References ACC_DATA_ENTRY_OPS.
isAccRoutine()
bool mlir::acc::isAccRoutine (mlir::Operation * op) inline
Used to check whether the current operation is marked with acc routine.
The operation passed in should be a function.
Definition at line 195 of file OpenACC.h.
References getRoutineInfoAttrName(), and mlir::Operation::hasAttr().
isDeviceValue()
bool mlir::acc::isDeviceValue (mlir::Value val)
Check if a value represents device data.
This checks if the value represents device data via the MappableType, PointerLikeType, and GlobalVariableOpInterface interfaces, and whether the defining operation carries acc.declare with the deviceptr clause.
Parameters
val The value to check
Returns
true if the value is device data, false otherwise
Definition at line 246 of file OpenACCUtils.cpp.
References mlir::Operation::getAttrOfType(), getDeclareAttrName(), mlir::Value::getDefiningOp(), mlir::Value::getType(), isDeviceValue(), and mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by isDeviceValue(), and isValidValueUse().
isMappableType()
bool mlir::acc::isMappableType (mlir::Type type) inline
Used to check whether the provided type implements the MappableType interface.
Definition at line 172 of file OpenACC.h.
Referenced by checkRecipe().
isOnlyUsedByPrivateClauses()
bool mlir::acc::isOnlyUsedByPrivateClauses (mlir::Value val, mlir::Region & region)
Returns true if this value is only used by acc.private operations in the region.
Definition at line 64 of file OpenACCUtils.cpp.
References isOnlyUsedByOpClauses().
Referenced by isValidValueUse().
isOnlyUsedByReductionClauses()
bool mlir::acc::isOnlyUsedByReductionClauses (mlir::Value val, mlir::Region & region)
Returns true if this value is only used by acc.reduction operations in the region.
Definition at line 69 of file OpenACCUtils.cpp.
References isOnlyUsedByOpClauses().
isPointerLikeType()
bool mlir::acc::isPointerLikeType (mlir::Type type) inline
Used to check whether the provided type implements the PointerLikeType interface.
Definition at line 166 of file OpenACC.h.
isSpecializedAccRoutine()
bool mlir::acc::isSpecializedAccRoutine (mlir::Operation * op) inline
Used to check whether this is a specialized accelerator version of acc routine function.
Definition at line 201 of file OpenACC.h.
References getSpecializedRoutineAttrName(), and mlir::Operation::hasAttr().
isValidSymbolUse()
bool mlir::acc::isValidSymbolUse (mlir::Operation * user, mlir::SymbolRefAttr symbol, mlir::Operation ** definingOpPtr = nullptr)
Check if a symbol use is valid for use in an OpenACC region.
This includes looking for various attributes such as acc.routine_info and acc.declare attributes.
Parameters
user The operation using the symbol
symbol The symbol reference being used
definingOpPtr Optional output parameter to receive the defining op
Returns
true if the symbol use is valid, false otherwise
Definition at line 192 of file OpenACCUtils.cpp.
References getDeclareAttrName(), getRoutineInfoAttrName(), mlir::Operation::hasAttr(), mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::SymbolTable::Private.
Referenced by mlir::acc::detail::OpenACCSupportTraits::Model< ImplT >::isValidSymbolUse(), and mlir::acc::OpenACCSupport::isValidSymbolUse().
isValidValueUse()
bool mlir::acc::isValidValueUse (mlir::Value val, mlir::Region & region)
Check if a value use is valid in an OpenACC region.
This is true if:
The value is produced by an ACC data entry operation
The value is device data
The value is only used by private clauses in the region
Parameters
val The value to check
region The OpenACC region
Returns
true if the value use is valid, false otherwise
Definition at line 289 of file OpenACCUtils.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getType(), isDeviceValue(), mlir::Type::isIntOrIndexOrFloat(), and isOnlyUsedByPrivateClauses().
Referenced by mlir::acc::detail::OpenACCSupportTraits::Model< ImplT >::isValidValueUse(), and mlir::acc::OpenACCSupport::isValidValueUse().
populateACCHostFallbackPatterns()
void mlir::acc::populateACCHostFallbackPatterns (RewritePatternSet & patterns, OpenACCSupport & accSupport, bool enableLoopConversion = true)
Populates all patterns for host fallback path (when if clause evaluates to false).
In this mode, ALL ACC operations should be converted or removed.
Parameters
enableLoopConversion Whether to convert orphan acc.loop operations.
Definition at line 400 of file ACCSpecializeForHost.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateACCOrphanToHostPatterns()
void mlir::acc::populateACCOrphanToHostPatterns (RewritePatternSet & patterns, OpenACCSupport & accSupport, bool enableLoopConversion = true)
Populates patterns for converting orphan ACC operations to host.
All patterns check that the operation is NOT inside or associated with a compute region before converting.
Parameters
enableLoopConversion Whether to convert orphan acc.loop operations.
Definition at line 363 of file ACCSpecializeForHost.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
populateACCSpecializeForDevicePatterns()
void mlir::acc::populateACCSpecializeForDevicePatterns (RewritePatternSet & patterns)
Populates all patterns for device specialization.
In specialized device code (such as specialized acc routine), many ACC operations do not make sense because they are host-side constructs. This function adds patterns to remove or transform them.
Definition at line 129 of file ACCSpecializeForDevice.cpp.
References mlir::RewritePatternSet::getContext(), and mlir::RewritePatternSet::insert().
registerACCBindRoutine()
void mlir::acc::registerACCBindRoutine () inline
Definition at line 1757 of file Passes.h.
registerACCBindRoutinePass()
void mlir::acc::registerACCBindRoutinePass () inline
Definition at line 1764 of file Passes.h.
registerACCComputeLowering()
void mlir::acc::registerACCComputeLowering () inline
Definition at line 1778 of file Passes.h.
registerACCComputeLoweringPass()
void mlir::acc::registerACCComputeLoweringPass () inline
Definition at line 1785 of file Passes.h.
registerACCDeclareGPUModuleInsertion()
void mlir::acc::registerACCDeclareGPUModuleInsertion () inline
Definition at line 1799 of file Passes.h.
registerACCDeclareGPUModuleInsertionPass()
void mlir::acc::registerACCDeclareGPUModuleInsertionPass () inline
Definition at line 1806 of file Passes.h.
registerACCEmitRemarksLoop()
void mlir::acc::registerACCEmitRemarksLoop () inline
Definition at line 1820 of file Passes.h.
registerACCEmitRemarksLoopPass()
void mlir::acc::registerACCEmitRemarksLoopPass () inline
Definition at line 1827 of file Passes.h.
registerACCEmitRemarksPrivate()
void mlir::acc::registerACCEmitRemarksPrivate () inline
Definition at line 1841 of file Passes.h.
registerACCEmitRemarksPrivatePass()
void mlir::acc::registerACCEmitRemarksPrivatePass () inline
Definition at line 1848 of file Passes.h.
registerACCIfClauseLowering()
void mlir::acc::registerACCIfClauseLowering () inline
Definition at line 1862 of file Passes.h.
registerACCIfClauseLoweringPass()
void mlir::acc::registerACCIfClauseLoweringPass () inline
Definition at line 1869 of file Passes.h.
registerACCImplicitData()
void mlir::acc::registerACCImplicitData () inline
Definition at line 1883 of file Passes.h.
registerACCImplicitDataPass()
void mlir::acc::registerACCImplicitDataPass () inline
Definition at line 1890 of file Passes.h.
registerACCImplicitDeclare()
void mlir::acc::registerACCImplicitDeclare () inline
Definition at line 1904 of file Passes.h.
registerACCImplicitDeclarePass()
void mlir::acc::registerACCImplicitDeclarePass () inline
Definition at line 1911 of file Passes.h.
registerACCImplicitRoutine()
void mlir::acc::registerACCImplicitRoutine () inline
Definition at line 1925 of file Passes.h.
registerACCImplicitRoutinePass()
void mlir::acc::registerACCImplicitRoutinePass () inline
Definition at line 1932 of file Passes.h.
registerACCLegalizeSerial()
void mlir::acc::registerACCLegalizeSerial () inline
Definition at line 1946 of file Passes.h.
registerACCLegalizeSerialPass()
void mlir::acc::registerACCLegalizeSerialPass () inline
Definition at line 1953 of file Passes.h.
registerACCLoopTiling()
void mlir::acc::registerACCLoopTiling () inline
Definition at line 1967 of file Passes.h.
registerACCLoopTilingPass()
void mlir::acc::registerACCLoopTilingPass () inline
Definition at line 1974 of file Passes.h.
registerACCRecipeMaterialization()
void mlir::acc::registerACCRecipeMaterialization () inline
Definition at line 1988 of file Passes.h.
registerACCRecipeMaterializationPass()
void mlir::acc::registerACCRecipeMaterializationPass () inline
Definition at line 1995 of file Passes.h.
registerACCRoutineLowering()
void mlir::acc::registerACCRoutineLowering () inline
Definition at line 2009 of file Passes.h.
registerACCRoutineLoweringPass()
void mlir::acc::registerACCRoutineLoweringPass () inline
Definition at line 2016 of file Passes.h.
registerACCRoutineToGPUFunc()
void mlir::acc::registerACCRoutineToGPUFunc () inline
Definition at line 2030 of file Passes.h.
registerACCRoutineToGPUFuncPass()
void mlir::acc::registerACCRoutineToGPUFuncPass () inline
Definition at line 2037 of file Passes.h.
registerACCSpecializeForDevice()
void mlir::acc::registerACCSpecializeForDevice () inline
Definition at line 2051 of file Passes.h.
registerACCSpecializeForDevicePass()
void mlir::acc::registerACCSpecializeForDevicePass () inline
Definition at line 2058 of file Passes.h.
registerACCSpecializeForHost()
void mlir::acc::registerACCSpecializeForHost () inline
Definition at line 2072 of file Passes.h.
registerACCSpecializeForHostPass()
void mlir::acc::registerACCSpecializeForHostPass () inline
Definition at line 2079 of file Passes.h.
registerLegalizeDataValuesInRegion()
void mlir::acc::registerLegalizeDataValuesInRegion () inline
Definition at line 2093 of file Passes.h.
registerLegalizeDataValuesInRegionPass()
void mlir::acc::registerLegalizeDataValuesInRegionPass () inline
Definition at line 2100 of file Passes.h.
registerOffloadLiveInValueCanonicalization()
void mlir::acc::registerOffloadLiveInValueCanonicalization () inline
Definition at line 2114 of file Passes.h.
registerOffloadLiveInValueCanonicalizationPass()
void mlir::acc::registerOffloadLiveInValueCanonicalizationPass () inline
Definition at line 2121 of file Passes.h.
registerOffloadTargetVerifier()
void mlir::acc::registerOffloadTargetVerifier () inline
Definition at line 2135 of file Passes.h.
registerOffloadTargetVerifierPass()
void mlir::acc::registerOffloadTargetVerifierPass () inline
Definition at line 2142 of file Passes.h.
registerOpenACCPasses()
void mlir::acc::registerOpenACCPasses () inline
Definition at line 2156 of file Passes.h.
Referenced by mlir::registerAllPasses().
setCollapseCountAttr()
void mlir::acc::setCollapseCountAttr (Operation * op, uint64_t count)
Record on a collapsed loop how many original loops were folded into it.
Definition at line 341 of file OpenACCUtilsLoop.cpp.
References getCollapseCountAttrName(), mlir::Operation::getContext(), and mlir::Operation::setAttr().
Referenced by convertACCLoopToSCFFor().
tileACCLoops()
mlir::acc::LoopOp mlir::acc::tileACCLoops (llvm::SmallVector< mlir::acc::LoopOp > & tileLoops, const llvm::SmallVector< mlir::Value > & tileSizes, int32_t defaultTileSize, mlir::RewriterBase & rewriter)
Tile ACC loops according to the given tile sizes.
Tiling a 2-level nested loop will create two 'tile' loops containing two 'element' loops. The transformation looks like:
Before Tiling:
#pragma acc loop tile(tile_size1, tile_size2)
 for (i = lb1; i < ub1; i += step1) { // original loop
   for (j = lb2; j < ub2; j += step2) {
     a[i,j] = i + j;
   }
 }
After Tiling:
for (i = lb1; i < ub1; i += (step1 * tile_size1)) { // tile loop 1
  for (j = lb2; j < ub2; j += (step2 * tile_size2)) { // tile loop 2
    for (ii = i; ii < min(ub1, (step1 * tile_size1) + i); ii += step1) {
    // element loop 1
      for (jj = j; jj < min(ub2, (step2 * tile_size2) + j); jj += step2)
      { // element loop 2
        a[ii,jj] = i + j;
      }
    }
  }
}
Unknown tile sizes (represented as -1 in acc dialect for tile(*)) are resolved to the provided default tile size.
Parameters
tileLoops The loops to tile (outermost first).
tileSizes The tile sizes for each dimension. Values of -1 are treated as unknown and resolved to defaultTileSize.
defaultTileSize The default tile size to use for unknown (*) tiles.
rewriter The rewriter to use for modifications.
Returns
The outermost loop after tiling.
Definition at line 153 of file OpenACCUtilsTiling.cpp.
References createInnerLoop(), mlir::RewriterBase::finalizeOpModification(), mlir::Builder::getDenseBoolArrayAttr(), mlir::Builder::getIntegerAttr(), mlir::getType(), moveOpsAndReplaceIVs(), removeWorkerVectorFromLoop(), resolveAndCastTileSize(), mlir::OpBuilder::setInsertionPoint(), and mlir::RewriterBase::startOpModification().
uncollapseLoops()
llvm::SmallVector< mlir::acc::LoopOp > mlir::acc::uncollapseLoops (mlir::acc::LoopOp origLoop, unsigned tileCount, unsigned collapseCount, mlir::RewriterBase & rewriter)
Uncollapse tile loops with multiple IVs and collapseCount < tileCount.
This is used to prepare loops for tiling when the collapse count is less than the tile count.
Parameters
origLoop The original loop operation to uncollapse.
tileCount The number of tile dimensions.
collapseCount The collapse count from the original loop.
rewriter The rewriter to use for modifications.
Returns
A vector of uncollapsed loop operations.
Definition at line 270 of file OpenACCUtilsTiling.cpp.
References createACCLoopFromOriginal(), mlir::OpBuilder::createBlock(), createInnerLoop(), mlir::Builder::getDenseBoolArrayAttr(), moveOpsAndReplaceIVs(), mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointToEnd().
wrapMultiBlockRegionWithSCFExecuteRegion()
scf::ExecuteRegionOp mlir::acc::wrapMultiBlockRegionWithSCFExecuteRegion (Region & region, IRMapping & mapping, Location loc, RewriterBase & rewriter)
Wrap a multi-block region in an scf.execute_region.
Wrap a multi-block region with scf.execute_region.
Clones the given region into a new scf.execute_region. Terminators with no successors (i.e., region exit points) are replaced with scf.yield. Use this to convert unstructured control flow (e.g. multiple blocks with branches) into a single SCF region.
Parameters
region The region to wrap (cloned into the execute_region; not modified).
mapping IR mapping for the clone; updated with block and value mappings.
loc Location for the created execute_region op.
rewriter RewriterBase for creating and erasing operations.
Returns
The created scf.execute_region operation.
Definition at line 150 of file OpenACCUtilsLoop.cpp.
References mlir::OpBuilder::cloneRegionBefore(), mlir::Region::end(), mlir::RewriterBase::eraseOp(), mlir::Region::getBlocks(), mlir::Operation::getLoc(), mlir::Operation::getNumSuccessors(), mlir::Operation::getOperands(), mlir::IRMapping::lookup(), mlir::OpBuilder::setInsertionPoint(), and TypeRange.
Referenced by buildComputeRegion(), convertACCLoopToSCFParallel(), and convertUnstructuredACCLoopToSCFExecuteRegion().
Variable Documentation
kDefaultGPUModuleName
llvm::StringLiteral mlir::acc::kDefaultGPUModuleName = "acc_gpu_module" constexpr
Default GPU module name used by OpenACC.
Definition at line 25 of file OpenACCUtilsGPU.h.
Referenced by getOrCreateGPUModule().