MLIR: mlir::x86 Namespace Reference
mlir::x86 Namespace Reference
Namespaces
namespace amx
namespace avx2
Helpers extracted from:
Classes
struct MaskHelper
Helper class to factor out the creation and extraction of masks from nibs.
struct ShuffleMasks
Functions
void registerTransformDialectExtension (DialectRegistry &registry)
void populateVectorContractToFMAPatterns (RewritePatternSet &patterns)
void populateVectorContractToPackedTypeDotProductPatterns (RewritePatternSet &patterns)
void populateVectorContractBF16ToFMAPatterns (RewritePatternSet &patterns)
void populateSinkVectorProducerOpsPatterns (RewritePatternSet &patterns)
void populateShuffleVectorFMAOpsPatterns (RewritePatternSet &patterns)
void populateVectorContractToAMXDotProductPatterns (RewritePatternSet &patterns)
bool isInVnniLayout (Operation *op, llvm::ArrayRef< AffineMap > indexingMaps, std::optional< unsigned > blockingFactor=std::nullopt)
bool validatePairVectorContract (vector::ContractionOp contractOp, vector::ContractionOp pairContOp, bool rhsHasMultipleNonUnitDims, int64_t nonUnitDimValue)
Operation * traceToVectorReadLikeParentOperation (Value v)
Operation * traceToVectorWriteLikeUserOperation (Value v)
LogicalResult shuffleAfterReadLikeOp (PatternRewriter &rewriter, Operation *opA, Operation *opB, vector::ContractionOp contractA, vector::ContractionOp contractB, int64_t nonUnitDimAcc, VectorType accTy)
LogicalResult shuffleBeforeWriteLikeOp (PatternRewriter &rewriter, Operation *opA, Operation *opB, int64_t nonUnitDimAcc, VectorType accTy)
static FailureOr< SmallVector< mlir::utils::IteratorType > > inferIteratorsFromOutMap (AffineMap map)
ShuffleMasks getShuffleMasks (int64_t nonUnitDimAcc, bool isInt8Avx2)
Function Documentation
getShuffleMasks()
ShuffleMasks mlir::x86::getShuffleMasks (int64_t nonUnitDimAcc, bool isInt8Avx2) inline
Definition at line 119 of file X86Utils.cpp.
Referenced by shuffleAfterReadLikeOp(), and shuffleBeforeWriteLikeOp().
inferIteratorsFromOutMap()
FailureOr< SmallVector< mlir::utils::IteratorType > > mlir::x86::inferIteratorsFromOutMap (AffineMap map) static
Definition at line 29 of file X86Utils.cpp.
References mlir::AffineMap::getNumDims(), mlir::AffineMap::getResults(), and mlir::AffineMap::isProjectedPermutation().
Referenced by isInVnniLayout().
isInVnniLayout()
bool mlir::x86::isInVnniLayout (Operation * op, llvm::ArrayRef< AffineMap > indexingMaps, std::optional< unsigned > blockingFactor = std::nullopt)
Definition at line 42 of file X86Utils.cpp.
References mlir::Operation::getOperand(), mlir::AffineMap::getResult(), mlir::linalg::inferContractionDims(), and inferIteratorsFromOutMap().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().
populateShuffleVectorFMAOpsPatterns()
void mlir::x86::populateShuffleVectorFMAOpsPatterns (RewritePatternSet & patterns)
Definition at line 183 of file ShuffleVectorFMAOps.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateSinkVectorProducerOpsPatterns()
void mlir::x86::populateSinkVectorProducerOpsPatterns (RewritePatternSet & patterns)
Definition at line 144 of file SinkVectorProducerOps.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateVectorContractBF16ToFMAPatterns()
void mlir::x86::populateVectorContractBF16ToFMAPatterns (RewritePatternSet & patterns)
Definition at line 507 of file VectorContractBF16ToFMA.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateVectorContractToAMXDotProductPatterns()
void mlir::x86::populateVectorContractToAMXDotProductPatterns (RewritePatternSet & patterns)
Definition at line 1523 of file VectorContractToAMXDotProduct.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateVectorContractToFMAPatterns()
void mlir::x86::populateVectorContractToFMAPatterns (RewritePatternSet & patterns)
Definition at line 140 of file VectorContractToFMA.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateVectorContractToPackedTypeDotProductPatterns()
void mlir::x86::populateVectorContractToPackedTypeDotProductPatterns (RewritePatternSet & patterns)
Definition at line 491 of file VectorContractToPackedTypeDotProduct.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
registerTransformDialectExtension()
void mlir::x86::registerTransformDialectExtension (DialectRegistry & registry)
Definition at line 80 of file X86TransformOps.cpp.
References mlir::DialectRegistry::addExtensions().
Referenced by mlir::registerAllExtensions().
shuffleAfterReadLikeOp()
LogicalResult mlir::x86::shuffleAfterReadLikeOp (PatternRewriter & rewriter, Operation * opA, Operation * opB, vector::ContractionOp contractA, vector::ContractionOp contractB, int64_t nonUnitDimAcc, VectorType accTy)
Definition at line 242 of file X86Utils.cpp.
References mlir::Operation::getLoc(), mlir::Operation::getResult(), getShuffleMasks(), mlir::Operation::isBeforeInBlock(), mlir::RewriterBase::replaceUsesWithIf(), mlir::OpBuilder::setInsertionPointAfter(), and success().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().
shuffleBeforeWriteLikeOp()
LogicalResult mlir::x86::shuffleBeforeWriteLikeOp (PatternRewriter & rewriter, Operation * opA, Operation * opB, int64_t nonUnitDimAcc, VectorType accTy)
Definition at line 292 of file X86Utils.cpp.
References mlir::Operation::getLoc(), getShuffleMasks(), mlir::Operation::isBeforeInBlock(), mlir::RewriterBase::modifyOpInPlace(), mlir::OpBuilder::setInsertionPoint(), mlir::Operation::setOperand(), and success().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().
traceToVectorReadLikeParentOperation()
Operation * mlir::x86::traceToVectorReadLikeParentOperation (Value v)
Definition at line 154 of file X86Utils.cpp.
References mlir::Value::getDefiningOp().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().
traceToVectorWriteLikeUserOperation()
Operation * mlir::x86::traceToVectorWriteLikeUserOperation (Value v)
Definition at line 194 of file X86Utils.cpp.
References mlir::Value::getNumUses(), mlir::Operation::getParentOp(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::Value::getUses(), and traceToVectorWriteLikeUserOperation().
Referenced by VectorContractBF16ToFMA::matchAndRewrite(), and traceToVectorWriteLikeUserOperation().
validatePairVectorContract()
bool mlir::x86::validatePairVectorContract (vector::ContractionOp contractOp, vector::ContractionOp pairContOp, bool rhsHasMultipleNonUnitDims, int64_t nonUnitDimValue)
Definition at line 352 of file X86Utils.cpp.
References mlir::getConstantIntValue(), and mlir::Value::getDefiningOp().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().