MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl Namespace Reference
Classes
struct AttributeType
struct OperationType
struct PDLType
struct RangeType
struct TypeType
struct ValueType
Functions
static void populateDialectPDLSubmodule (nanobind::module_ &m)
Function Documentation
populateDialectPDLSubmodule()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::populateDialectPDLSubmodule (nanobind::module_ & m) static
Definition at line 162 of file DialectPDL.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< AttributeType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< OperationType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< PDLType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< RangeType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< TypeType >::bind(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< ValueType >::bind().
Referenced by NB_MODULE().