MLIR: nanobind::detail Namespace Reference
nanobind::detail Namespace Reference
Classes
struct MlirDefaultingCaster
struct type_caster< mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyLocation >
struct type_caster< mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::DefaultingPyMlirContext >
struct type_caster< MlirAffineMap >
Casts object <-> MlirAffineMap.
struct type_caster< MlirAttribute >
Casts object <-> MlirAttribute.
struct type_caster< MlirBlock >
Casts object -> MlirBlock.
struct type_caster< MlirContext >
Casts object -> MlirContext.
struct type_caster< MlirDialectRegistry >
Casts object <-> MlirDialectRegistry.
struct type_caster< MlirFrozenRewritePatternSet >
Casts object <-> MlirFrozenRewritePatternSet.
struct type_caster< MlirLocation >
Casts object <-> MlirLocation.
struct type_caster< MlirModule >
Casts object <-> MlirModule.
struct type_caster< MlirOperation >
Casts object <-> MlirOperation.
struct type_caster< MlirPassManager >
Casts object -> MlirPassManager.
struct type_caster< MlirStringRef >
Casts MlirStringRef -> object.
struct type_caster< MlirType >
Casts object <-> MlirType.
struct type_caster< MlirTypeID >
Casts object <-> MlirTypeID.
struct type_caster< MlirValue >
Casts object <-> MlirValue.
Functions
static std::optional< nanobind::object > mlirApiObjectToCapsule (nanobind::handle apiObject)
Helper to convert a presumed MLIR API object to a capsule, accepting either an explicit Capsule (which can happen when two C APIs are communicating directly via Python) or indirectly by querying the MLIR_PYTHON_CAPI_PTR_ATTR attribute (through which supported MLIR Python API objects export their contained API pointer as a capsule).
bool pyErrClearIfFalse (bool val)
Clears the Python error indicator if the given condition val is false and returns the condition.
template<typename... Ts>
std::string join (const Ts &...args)
Helper function to concatenate arguments into a std::string.
Function Documentation
join()
template<typename... Ts> std::string nanobind::detail::join (const Ts &... args) inline
Helper function to concatenate arguments into a std::string.
Definition at line 125 of file NanobindUtils.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyComplexType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAffineExpr< DerivedTy, BaseTy >::castFrom(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyDenseElementsAttribute::getFromList(), mlir::python::nanobind_adaptors::mlir_attribute_subclass::mlir_attribute_subclass(), mlir::python::nanobind_adaptors::mlir_type_subclass::mlir_type_subclass(), mlir::python::nanobind_adaptors::mlir_value_subclass::mlir_value_subclass(), pyListToVector(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerAttributeBuilder(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerDialectImpl(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerOpAdaptorImpl(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerOperationImpl().
mlirApiObjectToCapsule()
std::optional< nanobind::object > nanobind::detail::mlirApiObjectToCapsule (nanobind::handle apiObject) static
Helper to convert a presumed MLIR API object to a capsule, accepting either an explicit Capsule (which can happen when two C APIs are communicating directly via Python) or indirectly by querying the MLIR_PYTHON_CAPI_PTR_ATTR attribute (through which supported MLIR Python API objects export their contained API pointer as a capsule).
Throws a type error if the object is neither. This is intended to be used from type casters, which are invoked with a raw handle (unowned). The returned object's lifetime may not extend beyond the apiObject handle without explicitly having its refcount increased (i.e. on return).
Definition at line 65 of file NanobindAdaptors.h.
References MLIR_PYTHON_CAPI_PTR_ATTR.
pyErrClearIfFalse()
bool nanobind::detail::pyErrClearIfFalse (bool val) inline
Clears the Python error indicator if the given condition val is false and returns the condition.
This is needed in from_python of the type casters below, where a failed conversion from a Python capsule sets the Python error indicator but the caller of the caster expects or may even need a clean error indicator.
Definition at line 80 of file NanobindAdaptors.h.