MLIR: mlir::x86vector::avx2 Namespace Reference
mlir::x86vector::avx2 Namespace Reference
Helpers extracted from:
Namespaces
namespace inline_asm
namespace intrin
Classes
struct LoweringOptions
Options for controlling specialized AVX2 lowerings.
struct TransposeLoweringOptions
Structure to control the behavior of specialized AVX2 transpose lowering.
Functions
void transpose4x8xf32 (ImplicitLocOpBuilder &ib, MutableArrayRef< Value > vs)
Generic lowerings may either use intrin or inline_asm depending on needs.
void transpose8x8xf32 (ImplicitLocOpBuilder &ib, MutableArrayRef< Value > vs)
8x8xf32-specific AVX2 transpose lowering.
void populateSpecializedTransposeLoweringPatterns (RewritePatternSet &patterns, LoweringOptions options=LoweringOptions(), int benefit=10)
Insert specialized transpose lowering patterns.
Detailed Description
Helpers extracted from:
clang/lib/Headers/avxintrin.h
clang/test/CodeGen/X86/avx-builtins.c
clang/test/CodeGen/X86/avx2-builtins.c
clang/test/CodeGen/X86/avx-shuffle-builtins.c as well as the Intel Intrinsics Guide (https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html) make it easier to just implement known good lowerings. All intrinsics correspond 1-1 to the Intel definition.
Function Documentation
populateSpecializedTransposeLoweringPatterns()
void mlir::x86vector::avx2::populateSpecializedTransposeLoweringPatterns (RewritePatternSet & patterns, LoweringOptions options = LoweringOptions(), int benefit = 10)
Insert specialized transpose lowering patterns.
Definition at line 287 of file AVXTranspose.cpp.
References options, and mlir::patterns.
transpose4x8xf32()
void mlir::x86vector::avx2::transpose4x8xf32 (ImplicitLocOpBuilder & ib, MutableArrayRef< Value > vs)
Generic lowerings may either use intrin or inline_asm depending on needs.
AVX2 4x8xf32-specific transpose lowering using a "C intrinsics" model.
4x8xf32-specific AVX2 transpose lowering.
Definition at line 114 of file AVXTranspose.cpp.
References mlir::Builder::getContext(), mlir::ValueRange::getTypes(), mlir::x86vector::avx2::intrin::mm256Permute2f128Ps(), mlir::x86vector::avx2::intrin::mm256ShufflePs(), mlir::x86vector::avx2::intrin::mm256UnpackHiPs(), mlir::x86vector::avx2::intrin::mm256UnpackLoPs(), mlir::x86vector::MaskHelper::permute(), and mlir::x86vector::MaskHelper::shuffle().
Referenced by TransposeOpLowering::matchAndRewrite().
transpose8x8xf32()
void mlir::x86vector::avx2::transpose8x8xf32 (ImplicitLocOpBuilder & ib, MutableArrayRef< Value > vs)
8x8xf32-specific AVX2 transpose lowering.
AVX2 8x8xf32-specific transpose lowering using a "C intrinsics" model.
Definition at line 139 of file AVXTranspose.cpp.
References mlir::x86vector::MaskHelper::blend(), mlir::Builder::getContext(), mlir::ValueRange::getTypes(), mlir::x86vector::avx2::inline_asm::mm256BlendPsAsm(), mlir::x86vector::avx2::intrin::mm256Permute2f128Ps(), mlir::x86vector::avx2::intrin::mm256ShufflePs(), mlir::x86vector::avx2::intrin::mm256UnpackHiPs(), mlir::x86vector::avx2::intrin::mm256UnpackLoPs(), mlir::x86vector::MaskHelper::permute(), and mlir::x86vector::MaskHelper::shuffle().
Referenced by TransposeOpLowering::matchAndRewrite().