MLIR: mlir::OpTrait::tosa Namespace Reference
mlir::OpTrait::tosa Namespace Reference
Classes
class MulOperandsAndResultElementType
class TosaElementwiseOperator
This class indicates that an op is tosa-elementwise (permits broadcasting, unlike Elementwise trait).
class TosaResolvableShapeOperands
This class verifies that tosa shape operands are compile time resolvable.
class TosaShapeOperator
This class indicates that op operates on tosa shape types.
class TosaShapeOperatorWithSameRanks
This class indicates that op operates on tosa shape types.
Functions
LogicalResult verifyTosaResolvableShapeOperands (Operation *op)
LogicalResult verifyTosaShapeOperator (Operation *op)
LogicalResult verifyTosaShapeOperatorWithSameRanks (Operation *op)
Function Documentation
verifyTosaResolvableShapeOperands()
LogicalResult mlir::OpTrait::tosa::verifyTosaResolvableShapeOperands (Operation * op)
Definition at line 4028 of file TosaOps.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperands(), and mlir::Operation::hasTrait().
Referenced by mlir::OpTrait::tosa::TosaResolvableShapeOperands< ConcreteType >::verifyTrait().
verifyTosaShapeOperator()
LogicalResult mlir::OpTrait::tosa::verifyTosaShapeOperator (Operation * op)
Definition at line 4040 of file TosaOps.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), and mlir::Operation::getResultTypes().
Referenced by verifyTosaShapeOperatorWithSameRanks(), and mlir::OpTrait::tosa::TosaShapeOperator< ConcreteType >::verifyTrait().
verifyTosaShapeOperatorWithSameRanks()
LogicalResult mlir::OpTrait::tosa::verifyTosaShapeOperatorWithSameRanks (Operation * op)
Definition at line 4055 of file TosaOps.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::OpTrait::impl::verifyAtLeastNOperands(), and verifyTosaShapeOperator().
Referenced by mlir::OpTrait::tosa::TosaShapeOperatorWithSameRanks< ConcreteType >::verifyTrait().