MLIR: mlir::ptr Namespace Reference
mlir::ptr Namespace Reference
Functions
void populatePtrToLLVMConversionPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns)
Populate the convert to LLVM patterns for the ptr dialect.
void registerConvertPtrToLLVMInterface (DialectRegistry &registry)
Register the convert to LLVM interface for the ptr dialect.
Function Documentation
populatePtrToLLVMConversionPatterns()
void mlir::ptr::populatePtrToLLVMConversionPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns)
Populate the convert to LLVM patterns for the ptr dialect.
Definition at line 399 of file PtrToLLVM.cpp.
References mlir::TypeConverter::addConversion(), mlir::TypeConverter::addTypeAttributeConversion(), mlir::TypeConverter::convertTypeAttribute(), createMemRefMetadataType(), mlir::remark::failed(), mlir::get(), mlir::TypeConverter::AttributeConversionResult::na(), and mlir::patterns.
registerConvertPtrToLLVMInterface()
void mlir::ptr::registerConvertPtrToLLVMInterface (DialectRegistry & registry)
Register the convert to LLVM interface for the ptr dialect.
Definition at line 437 of file PtrToLLVM.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllExtensions().