MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu Namespace Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu Namespace Reference
Classes
struct TDMBaseType
struct TDMDescriptorType
struct TDMGatherBaseType
Functions
static void populateDialectAMDGPUSubmodule (nb::module_ &m)
Function Documentation
populateDialectAMDGPUSubmodule()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::amdgpu::populateDialectAMDGPUSubmodule (nb::module_ & m) static
Definition at line 91 of file DialectAMDGPU.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< TDMBaseType >::bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< TDMDescriptorType >::bind(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< TDMGatherBaseType >::bind().
Referenced by NB_MODULE().