MLIR: mlir::wasmssa::detail Namespace Reference
mlir::wasmssa::detail Namespace Reference
Functions
LogicalResult verifyConstantExpressionInterface (Operation *op)
Verify that op conforms to the ConstantExpressionInterface.
LogicalResult verifyLabelBranchingOpInterface (Operation *op)
Verify that op conforms to the LabelBranchingOpInterface Checks that the branching is targetting something within its scope.
template<typename OpType>
LogicalResult verifyLabelLevelInterfaceIsTerminator ()
Verify that op conforms to LabelLevelInterfaceIsTerminator.
LogicalResult verifyLabelLevelInterface (Operation *op)
Verify that op conforms to the LabelLevelInterface op's target should defined at the same scope level.
Function Documentation
verifyConstantExpressionInterface()
LogicalResult mlir::wasmssa::detail::verifyConstantExpressionInterface (Operation * op)
Verify that op conforms to the ConstantExpressionInterface.
op must be initialized with valid constant expressions.
Definition at line 32 of file WasmSSAInterfaces.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::Operation::getRegion(), mlir::Operation::hasTrait(), mlir::WalkResult::interrupt(), success(), mlir::Region::walk(), and mlir::WalkResult::wasInterrupted().
Referenced by mlir::wasmssa::ConstantExpressionInitializerOpTrait< OpType >::verifyTrait().
verifyLabelBranchingOpInterface()
LogicalResult mlir::wasmssa::detail::verifyLabelBranchingOpInterface (Operation * op)
Verify that op conforms to the LabelBranchingOpInterface Checks that the branching is targetting something within its scope.
Definition at line 24 of file WasmSSAInterfaces.cpp.
References mlir::Operation::getBlock().
verifyLabelLevelInterface()
LogicalResult mlir::wasmssa::detail::verifyLabelLevelInterface (Operation * op)
Verify that op conforms to the LabelLevelInterface op's target should defined at the same scope level.
Definition at line 46 of file WasmSSAInterfaces.cpp.
References mlir::Operation::emitError(), mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), success(), and target.
verifyLabelLevelInterfaceIsTerminator()
template<typename OpType> LogicalResult mlir::wasmssa::detail::verifyLabelLevelInterfaceIsTerminator ()
Verify that op conforms to LabelLevelInterfaceIsTerminator.
Definition at line 31 of file WasmSSAInterfaces.h.
References success().