MLIR: lib/Dialect/Affine/Analysis/NestedMatcher.cpp File Reference
NestedMatcher.cpp File Reference
#include <utility>
#include "mlir/Dialect/Affine/Analysis/NestedMatcher.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Allocator.h"
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::affine
namespace mlir::affine::matcher
Functions
static bool isAffineForOp (Operation &op)
static bool isAffineIfOp (Operation &op)
NestedPattern mlir::affine::matcher::Op (FilterFunctionType filter=defaultFilterFunction)
NestedPattern mlir::affine::matcher::If (const NestedPattern &child)
NestedPattern mlir::affine::matcher::If (const FilterFunctionType &filter, const NestedPattern &child)
NestedPattern mlir::affine::matcher::If (ArrayRef< NestedPattern > nested={})
NestedPattern mlir::affine::matcher::If (const FilterFunctionType &filter, ArrayRef< NestedPattern > nested={})
NestedPattern mlir::affine::matcher::For (const NestedPattern &child)
NestedPattern mlir::affine::matcher::For (const FilterFunctionType &filter, const NestedPattern &child)
NestedPattern mlir::affine::matcher::For (ArrayRef< NestedPattern > nested={})
NestedPattern mlir::affine::matcher::For (const FilterFunctionType &filter, ArrayRef< NestedPattern > nested={})
bool mlir::affine::matcher::isLoadOrStore (Operation &op)
Function Documentation
isAffineForOp()
bool isAffineForOp (Operation & op) static
Definition at line 127 of file NestedMatcher.cpp.
Referenced by mlir::affine::matcher::For(), mlir::affine::matcher::For(), mlir::affine::matcher::For(), and mlir::affine::matcher::For().
isAffineIfOp()
bool isAffineIfOp (Operation & op) static
Definition at line 129 of file NestedMatcher.cpp.
Referenced by mlir::affine::matcher::If(), mlir::affine::matcher::If(), mlir::affine::matcher::If(), and mlir::affine::matcher::If().