MLIR: include/mlir-c/Dialect/NVGPU.h File Reference
NVGPU.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (NVGPU, nvgpu)
MLIR_CAPI_EXPORTED bool mlirTypeIsANVGPUTensorMapDescriptorType (MlirType type)
MLIR_CAPI_EXPORTED MlirType mlirNVGPUTensorMapDescriptorTypeGet (MlirContext ctx, MlirType tensorMemrefType, int swizzle, int l2promo, int oobFill, int interleave)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (NVGPU , nvgpu)
References MLIR_CAPI_EXPORTED.
mlirNVGPUTensorMapDescriptorTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirNVGPUTensorMapDescriptorTypeGet (MlirContext ctx, MlirType tensorMemrefType, int swizzle, int l2promo, int oobFill, int interleave)
Definition at line 23 of file NVGPU.cpp.
References unwrap(), and wrap().
Referenced by populateDialectNVGPUSubmodule().
mlirTypeIsANVGPUTensorMapDescriptorType()
MLIR_CAPI_EXPORTED bool mlirTypeIsANVGPUTensorMapDescriptorType (MlirType type)
Definition at line 19 of file NVGPU.cpp.
References mlirTypeIsANVGPUTensorMapDescriptorType(), and unwrap().
Referenced by mlirTypeIsANVGPUTensorMapDescriptorType(), and populateDialectNVGPUSubmodule().