MLIR: lib/CAPI/Dialect/NVGPU.cpp File Reference
NVGPU.cpp File Reference
#include "mlir-c/Dialect/NVGPU.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/NVGPU/IR/NVGPUDialect.h"
#include "mlir/IR/BuiltinTypes.h"
Functions
bool mlirTypeIsANVGPUTensorMapDescriptorType (MlirType type)
MlirType mlirNVGPUTensorMapDescriptorTypeGet (MlirContext ctx, MlirType tensorMemrefType, int swizzle, int l2promo, int oobFill, int interleave)
Function Documentation
mlirNVGPUTensorMapDescriptorTypeGet()
MlirType mlirNVGPUTensorMapDescriptorTypeGet (MlirContext ctx, MlirType tensorMemrefType, int swizzle, int l2promo, int oobFill, int interleave)
Definition at line 23 of file NVGPU.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectNVGPUSubmodule().
mlirTypeIsANVGPUTensorMapDescriptorType()
bool mlirTypeIsANVGPUTensorMapDescriptorType (MlirType type)
Definition at line 19 of file NVGPU.cpp.
References unwrap().
Referenced by populateDialectNVGPUSubmodule().