MLIR: lib/IR/ODSSupport.cpp File Reference
ODSSupport.cpp File Reference
#include "mlir/IR/ODSSupport.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
Functions
template<typename DenseArrayTy, typename T>
static LogicalResult convertDenseArrayFromAttr (MutableArrayRef< T > storage, Attribute attr, function_ref< InFlightDiagnostic()> emitError, StringRef denseArrayTyStr)
template<typename DenseArrayTy, typename T>
static LogicalResult convertDenseArrayFromAttr (SmallVectorImpl< T > &storage, Attribute attr, function_ref< InFlightDiagnostic()> emitError, StringRef denseArrayTyStr)
Function Documentation
convertDenseArrayFromAttr() [1/2]
template<typename DenseArrayTy, typename T> LogicalResult convertDenseArrayFromAttr (MutableArrayRef< T > storage, Attribute attr, function_ref< InFlightDiagnostic()> emitError, StringRef denseArrayTyStr) static
Definition at line 116 of file ODSSupport.cpp.
References mlir::emitError(), and success().
Referenced by mlir::convertFromAttribute(), mlir::convertFromAttribute(), mlir::convertFromAttribute(), and mlir::convertFromAttribute().
convertDenseArrayFromAttr() [2/2]
template<typename DenseArrayTy, typename T> LogicalResult convertDenseArrayFromAttr (SmallVectorImpl< T > & storage, Attribute attr, function_ref< InFlightDiagnostic()> emitError, StringRef denseArrayTyStr) static
Definition at line 147 of file ODSSupport.cpp.
References mlir::emitError(), and success().