MLIR: lib/Dialect/Bufferization/Transforms/OneShotModuleBufferize.cpp File Reference
OneShotModuleBufferize.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/OneShotModuleBufferize.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/Transforms.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
Typedefs
using FuncCallerMap = DenseMap<func::FuncOp, DenseSet<Operation *>>
A mapping of FuncOps to their callers.
Functions
static FuncAnalysisState & getOrCreateFuncAnalysisState (OneShotAnalysisState &state)
Get or create FuncAnalysisState.
static void removeBufferizationAttributes (BlockArgument bbArg)
Remove bufferization attributes on FuncOp arguments.
static func::FuncOp getCalledFunction (func::CallOp callOp, mlir::SymbolTableCollection &symbolTable)
Return the func::FuncOp called by callOp.
static bool hasTensorSignature (func::FuncOp funcOp)
Return "true" if the given function signature has tensor semantics.
static LogicalResult getFuncOpsOrderedByCalls (Operation *moduleOp, SmallVectorImpl< func::FuncOp > &orderedFuncOps, SmallVectorImpl< func::FuncOp > &remainingFuncOps, FuncCallerMap &callerMap, SymbolTableCollection &symbolTables)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e., callees without callers first).
static Value unpackCast (Value v)
Helper function that extracts the source from a memref.cast.
static SmallVector< Type > getReturnTypes (SmallVector< func::ReturnOp > returnOps)
Helper function that returns the return types (skipping casts) of the given func.return ops.
static void foldMemRefCasts (func::FuncOp funcOp)
Fold return values that are memref casts and update function return types.
Typedef Documentation
FuncCallerMap
using FuncCallerMap = DenseMap<func::FuncOp, DenseSet<Operation *>>
A mapping of FuncOps to their callers.
Definition at line 80 of file OneShotModuleBufferize.cpp.
Function Documentation
foldMemRefCasts()
void foldMemRefCasts (func::FuncOp funcOp) static
Fold return values that are memref casts and update function return types.
During FuncOp bufferization, the exact type of the returned memrefs (if any) is not known yet. Therefore, the bufferization uses memref types with the most generic layout map as function return types. After bufferizing the entire function body, a more concise memref type can potentially be used for the return type of the function.
Definition at line 417 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::getReturnOps(), getReturnTypes(), and unpackCast().
Referenced by mlir::bufferization::bufferizeModuleOp().
getCalledFunction()
func::FuncOp getCalledFunction (func::CallOp callOp, mlir::SymbolTableCollection & symbolTable) static
Return the func::FuncOp called by callOp.
Definition at line 286 of file OneShotModuleBufferize.cpp.
getFuncOpsOrderedByCalls()
LogicalResult getFuncOpsOrderedByCalls (Operation * moduleOp, SmallVectorImpl< func::FuncOp > & orderedFuncOps, SmallVectorImpl< func::FuncOp > & remainingFuncOps, FuncCallerMap & callerMap, SymbolTableCollection & symbolTables) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e., callees without callers first).
Store all remaining functions (i.e., the ones that call each other recursively) in remainingFuncOps. Does not traverse nested symbol tables.
Store the map of FuncOp to all its callers in callerMap.
Return failure() if we are unable to retrieve the called FuncOp from any func::CallOp.
Definition at line 309 of file OneShotModuleBufferize.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::func_ext::getCalledFunction(), mlir::Operation::getRegions(), hasTensorSignature(), mlir::WalkResult::skip(), success(), and mlir::WalkResult::wasInterrupted().
Referenced by mlir::bufferization::analyzeModuleOp(), and mlir::bufferization::bufferizeModuleOp().
getOrCreateFuncAnalysisState()
FuncAnalysisState & getOrCreateFuncAnalysisState (OneShotAnalysisState & state) static
Get or create FuncAnalysisState.
Definition at line 84 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::OneShotAnalysisState::addExtension(), mlir::bufferization::OneShotAnalysisState::getExtension(), and result.
Referenced by mlir::bufferization::analyzeModuleOp().
getReturnTypes()
SmallVector< Type > getReturnTypes (SmallVector< func::ReturnOp > returnOps) static
Helper function that returns the return types (skipping casts) of the given func.return ops.
This function returns as many types as the return ops have operands. If the i-th operand is not the same for all func.return ops, then the i-th returned type is an "empty" type.
Definition at line 387 of file OneShotModuleBufferize.cpp.
References mlir::Value::getType(), result, and unpackCast().
Referenced by foldMemRefCasts().
hasTensorSignature()
bool hasTensorSignature (func::FuncOp funcOp) static
Return "true" if the given function signature has tensor semantics.
Definition at line 293 of file OneShotModuleBufferize.cpp.
Referenced by getFuncOpsOrderedByCalls().
removeBufferizationAttributes()
void removeBufferizationAttributes (BlockArgument bbArg) static
Remove bufferization attributes on FuncOp arguments.
Definition at line 276 of file OneShotModuleBufferize.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::bufferization::removeBufferizationAttributesInModule().
unpackCast()
Value unpackCast (Value v) static
Helper function that extracts the source from a memref.cast.
If the given value is not a memref.cast result, simply returns the given value.
Definition at line 376 of file OneShotModuleBufferize.cpp.
References mlir::Value::getDefiningOp().
Referenced by foldMemRefCasts(), and getReturnTypes().