MLIR: lib/Dialect/OpenACC/IR/OpenACC.cpp File Reference
OpenACC.cpp File Reference
#include "mlir/Dialect/OpenACC/OpenACC.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/LogicalResult.h"
#include <variant>
#include "mlir/Dialect/OpenACC/OpenACCOpsDialect.cpp.inc"
#include "mlir/Dialect/OpenACC/OpenACCOpsEnums.cpp.inc"
#include "mlir/Dialect/OpenACC/OpenACCOpsInterfaces.cpp.inc"
#include "mlir/Dialect/OpenACC/OpenACCTypeInterfaces.cpp.inc"
#include "mlir/Dialect/OpenACCMPCommon/Interfaces/OpenACCMPOpsInterfaces.cpp.inc"
#include "mlir/Dialect/OpenACC/OpenACCOps.cpp.inc"
#include "mlir/Dialect/OpenACC/OpenACCOpsAttributes.cpp.inc"
#include "mlir/Dialect/OpenACC/OpenACCOpsTypes.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_TYPEDEF_LIST
#define GET_OP_CLASSES
#define GET_ATTRDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Functions
static void getSingleRegionOpSuccessorRegions (Operation *op, Region &region, RegionBranchPoint point, SmallVectorImpl< RegionSuccessor > &regions)
Generic helper for single-region OpenACC ops that execute their body once and then return to the parent operation with their results (if any).
static bool hasDeviceTypeValues (std::optional< mlir::ArrayAttr > arrayAttr)
static bool hasDeviceType (std::optional< mlir::ArrayAttr > arrayAttr, mlir::acc::DeviceType deviceType)
static void printDeviceTypes (mlir::OpAsmPrinter &p, std::optional< mlir::ArrayAttr > deviceTypes)
static std::optional< unsigned > findSegment (ArrayAttr segments, mlir::acc::DeviceType deviceType)
static mlir::Operation::operand_range getValuesFromSegments (std::optional< mlir::ArrayAttr > arrayAttr, mlir::Operation::operand_range range, std::optional< llvm::ArrayRef< int32_t > > segments, mlir::acc::DeviceType deviceType)
static mlir::Value getWaitDevnumValue (std::optional< mlir::ArrayAttr > deviceTypeAttr, mlir::Operation::operand_range operands, std::optional< llvm::ArrayRef< int32_t > > segments, std::optional< mlir::ArrayAttr > hasWaitDevnum, mlir::acc::DeviceType deviceType)
static mlir::Operation::operand_range getWaitValuesWithoutDevnum (std::optional< mlir::ArrayAttr > deviceTypeAttr, mlir::Operation::operand_range operands, std::optional< llvm::ArrayRef< int32_t > > segments, std::optional< mlir::ArrayAttr > hasWaitDevnum, mlir::acc::DeviceType deviceType)
template<typename Op>
static LogicalResult checkWaitAndAsyncConflict (Op op)
template<typename Op>
static LogicalResult checkVarAndVarType (Op op)
template<typename Op>
static LogicalResult checkVarAndAccVar (Op op)
template<typename Op>
static LogicalResult checkNoModifier (Op op)
template<typename Op>
static LogicalResult checkValidModifier (Op op, acc::DataClauseModifier validModifiers)
template<typename OpT, typename RecipeOpT>
static LogicalResult checkRecipe (OpT op, llvm::StringRef operandName)
static ParseResult parseVar (mlir::OpAsmParser &parser, OpAsmParser::UnresolvedOperand &var)
static void printVar (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::Value var)
static ParseResult parseAccVar (mlir::OpAsmParser &parser, OpAsmParser::UnresolvedOperand &var, mlir::Type &accVarType)
static void printAccVar (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::Value accVar, mlir::Type accVarType)
static ParseResult parseVarPtrType (mlir::OpAsmParser &parser, mlir::Type &varPtrType, mlir::TypeAttr &varTypeAttr)
static void printVarPtrType (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::Type varPtrType, mlir::TypeAttr varTypeAttr)
static ParseResult parseRecipeSym (mlir::OpAsmParser &parser, mlir::SymbolRefAttr &recipeAttr)
static void printRecipeSym (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::SymbolRefAttr recipeAttr)
template<typename StructureOp>
static ParseResult parseRegions (OpAsmParser &parser, OperationState &state, unsigned nRegions=1)
static bool isComputeOperation (Operation *op)
static LogicalResult verifyInitLikeSingleArgRegion (Operation *op, Region &region, StringRef regionType, StringRef regionName, Type type, bool verifyYield, bool optional=false)
template<typename Op>
static LogicalResult checkDataOperands (Op op, const mlir::ValueRange &operands)
Check dataOperands for acc.parallel, acc.serial and acc.kernels.
template<typename OpT, typename RecipeOpT>
static LogicalResult checkPrivateOperands (mlir::Operation *accConstructOp, const mlir::ValueRange &operands, llvm::StringRef operandName)
template<typename Op>
static LogicalResult verifyDeviceTypeCountMatch (Op op, OperandRange operands, ArrayAttr deviceTypes, llvm::StringRef keyword)
template<typename Op>
static LogicalResult verifyDeviceTypeAndSegmentCountMatch (Op op, OperandRange operands, DenseI32ArrayAttr segments, ArrayAttr deviceTypes, llvm::StringRef keyword, int32_t maxInSegment=0)
static mlir::Value getValueInDeviceTypeSegment (std::optional< mlir::ArrayAttr > arrayAttr, mlir::Operation::operand_range range, mlir::acc::DeviceType deviceType)
static ParseResult parseNumGangs (mlir::OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, mlir::ArrayAttr &deviceTypes, mlir::DenseI32ArrayAttr &segments)
static void printSingleDeviceType (mlir::OpAsmPrinter &p, mlir::Attribute attr)
static void printNumGangs (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments)
static ParseResult parseDeviceTypeOperandsWithSegment (mlir::OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, mlir::ArrayAttr &deviceTypes, mlir::DenseI32ArrayAttr &segments)
static void printDeviceTypeOperandsWithSegment (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments)
static ParseResult parseWaitClause (mlir::OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, mlir::ArrayAttr &deviceTypes, mlir::DenseI32ArrayAttr &segments, mlir::ArrayAttr &hasDevNum, mlir::ArrayAttr &keywordOnly)
static bool hasOnlyDeviceTypeNone (std::optional< mlir::ArrayAttr > attrs)
static void printWaitClause (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments, std::optional< mlir::ArrayAttr > hasDevNum, std::optional< mlir::ArrayAttr > keywordOnly)
static ParseResult parseDeviceTypeOperands (mlir::OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, mlir::ArrayAttr &deviceTypes)
static void printDeviceTypeOperands (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes)
static ParseResult parseDeviceTypeOperandsWithKeywordOnly (mlir::OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, mlir::ArrayAttr &deviceTypes, mlir::ArrayAttr &keywordOnlyDeviceType)
static void printDeviceTypeOperandsWithKeywordOnly (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::ArrayAttr > keywordOnlyDeviceTypes)
static ParseResult parseOperandWithKeywordOnly (mlir::OpAsmParser &parser, std::optional< OpAsmParser::UnresolvedOperand > &operand, mlir::Type &operandType, mlir::UnitAttr &attr)
static void printOperandWithKeywordOnly (mlir::OpAsmPrinter &p, mlir::Operation *op, std::optional< mlir::Value > operand, mlir::Type operandType, mlir::UnitAttr attr)
static ParseResult parseOperandsWithKeywordOnly (mlir::OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, mlir::UnitAttr &attr)
static void printOperandsWithKeywordOnly (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::OperandRange operands, mlir::TypeRange types, mlir::UnitAttr attr)
static ParseResult parseCombinedConstructsLoop (mlir::OpAsmParser &parser, mlir::acc::CombinedConstructsTypeAttr &attr)
static void printCombinedConstructsLoop (mlir::OpAsmPrinter &p, mlir::Operation *op, mlir::acc::CombinedConstructsTypeAttr attr)
static ParseResult parseGangValue (OpAsmParser &parser, llvm::StringRef keyword, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &operands, llvm::SmallVectorImpl< Type > &types, llvm::SmallVector< GangArgTypeAttr > &attributes, GangArgTypeAttr gangArgType, bool &needCommaBetweenValues, bool &newValue)
static ParseResult parseGangClause (OpAsmParser &parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > &gangOperands, llvm::SmallVectorImpl< Type > &gangOperandsType, mlir::ArrayAttr &gangArgType, mlir::ArrayAttr &deviceType, mlir::DenseI32ArrayAttr &segments, mlir::ArrayAttr &gangOnlyDeviceType)
void printGangClause (OpAsmPrinter &p, Operation *op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > gangArgTypes, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments, std::optional< mlir::ArrayAttr > gangOnlyDeviceTypes)
bool hasDuplicateDeviceTypes (std::optional< mlir::ArrayAttr > segments, llvm::SmallSet< mlir::acc::DeviceType, 3 > &deviceTypes)
static std::optional< mlir::acc::DeviceType > checkDeviceTypes (mlir::ArrayAttr deviceTypes)
Check for duplicates in the DeviceType array attribute.
ParseResult parseLoopControl (OpAsmParser &parser, Region &region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &lowerbound, SmallVectorImpl< Type > &lowerboundType, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &upperbound, SmallVectorImpl< Type > &upperboundType, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &step, SmallVectorImpl< Type > &stepType)
loop-control ::= control (ssa-id-and-type-list) = (ssa-id-and-type-list) to (ssa-id-and-type-list) step (ssa-id-and-type-list) region
void printLoopControl (OpAsmPrinter &p, Operation *op, Region &region, ValueRange lowerbound, TypeRange lowerboundType, ValueRange upperbound, TypeRange upperboundType, ValueRange steps, TypeRange stepType)
template<typename Op>
static LogicalResult checkDeclareOperands (Op &op, const mlir::ValueRange &operands, bool requireAtLeastOneOperand=true)
static unsigned getParallelismForDeviceType (acc::RoutineOp op, acc::DeviceType dtype)
static ParseResult parseBindName (OpAsmParser &parser, mlir::ArrayAttr &bindIdName, mlir::ArrayAttr &bindStrName, mlir::ArrayAttr &deviceIdTypes, mlir::ArrayAttr &deviceStrTypes)
static void printBindName (mlir::OpAsmPrinter &p, mlir::Operation *op, std::optional< mlir::ArrayAttr > bindIdName, std::optional< mlir::ArrayAttr > bindStrName, std::optional< mlir::ArrayAttr > deviceIdTypes, std::optional< mlir::ArrayAttr > deviceStrTypes)
static ParseResult parseRoutineGangClause (OpAsmParser &parser, mlir::ArrayAttr &gang, mlir::ArrayAttr &gangDim, mlir::ArrayAttr &gangDimDeviceTypes)
void printRoutineGangClause (OpAsmPrinter &p, Operation *op, std::optional< mlir::ArrayAttr > gang, std::optional< mlir::ArrayAttr > gangDim, std::optional< mlir::ArrayAttr > gangDimDeviceTypes)
static ParseResult parseDeviceTypeArrayAttr (OpAsmParser &parser, mlir::ArrayAttr &deviceTypes)
static void printDeviceTypeArrayAttr (mlir::OpAsmPrinter &p, mlir::Operation *op, std::optional< mlir::ArrayAttr > deviceTypes)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 4779 of file OpenACC.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 4776 of file OpenACC.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 4782 of file OpenACC.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
checkDataOperands()
template<typename Op> LogicalResult checkDataOperands (Op op, const mlir::ValueRange & operands) static
Check dataOperands for acc.parallel, acc.serial and acc.kernels.
Definition at line 1645 of file OpenACC.cpp.
References mlir::OpState::emitError(), and success().
checkDeclareOperands()
template<typename Op> LogicalResult checkDeclareOperands (Op & op, const mlir::ValueRange & operands, bool requireAtLeastOneOperand = true) static
Definition at line 4083 of file OpenACC.cpp.
References mlir::emitError(), mlir::OpState::emitError(), mlir::acc::getDataClause(), mlir::OpState::getLoc(), mlir::acc::getVar(), and success().
checkDeviceTypes()
std::optional< mlir::acc::DeviceType > checkDeviceTypes (mlir::ArrayAttr deviceTypes) static
Check for duplicates in the DeviceType array attribute.
Returns std::nullopt if no duplicates, or the duplicate DeviceType if found.
Definition at line 3088 of file OpenACC.cpp.
checkNoModifier()
template<typename Op> LogicalResult checkNoModifier (Op op) static
Definition at line 593 of file OpenACC.cpp.
References mlir::OpState::emitError(), and success().
checkPrivateOperands()
template<typename OpT, typename RecipeOpT> LogicalResult checkPrivateOperands (mlir::Operation * accConstructOp, const mlir::ValueRange & operands, llvm::StringRef operandName) static
Definition at line 1659 of file OpenACC.cpp.
References mlir::Operation::emitOpError(), and success().
checkRecipe()
template<typename OpT, typename RecipeOpT> LogicalResult checkRecipe (OpT op, llvm::StringRef operandName) static
Definition at line 611 of file OpenACC.cpp.
References mlir::acc::isMappableType(), mlir::SymbolTable::lookupNearestSymbolFrom(), and success().
checkValidModifier()
template<typename Op> LogicalResult checkValidModifier (Op op, acc::DataClauseModifier validModifiers) static
Definition at line 601 of file OpenACC.cpp.
References mlir::OpState::emitError(), and success().
checkVarAndAccVar()
template<typename Op> LogicalResult checkVarAndAccVar (Op op) static
Definition at line 585 of file OpenACC.cpp.
References mlir::OpState::emitError(), and success().
checkVarAndVarType()
template<typename Op> LogicalResult checkVarAndVarType (Op op) static
Definition at line 567 of file OpenACC.cpp.
References mlir::OpState::emitError(), and success().
checkWaitAndAsyncConflict()
template<typename Op> LogicalResult checkWaitAndAsyncConflict (Op op) static
Definition at line 545 of file OpenACC.cpp.
References mlir::OpState::emitError(), hasDeviceType(), and success().
findSegment()
std::optional< unsigned > findSegment (ArrayAttr segments, mlir::acc::DeviceType deviceType) static
Definition at line 480 of file OpenACC.cpp.
References ArrayAttr().
Referenced by getValueInDeviceTypeSegment(), getValuesFromSegments(), getWaitDevnumValue(), and getWaitValuesWithoutDevnum().
getParallelismForDeviceType()
unsigned getParallelismForDeviceType (acc::RoutineOp op, acc::DeviceType dtype) static
Definition at line 4142 of file OpenACC.cpp.
getSingleRegionOpSuccessorRegions()
void getSingleRegionOpSuccessorRegions (Operation * op, Region & region, RegionBranchPoint point, SmallVectorImpl< RegionSuccessor > & regions) static
Generic helper for single-region OpenACC ops that execute their body once and then return to the parent operation with their results (if any).
Definition at line 400 of file OpenACC.cpp.
References mlir::Operation::getResults(), and mlir::RegionBranchPoint::isParent().
getValueInDeviceTypeSegment()
mlir::Value getValueInDeviceTypeSegment (std::optional< mlir::ArrayAttr > arrayAttr, mlir::Operation::operand_range range, mlir::acc::DeviceType deviceType) static
Definition at line 1772 of file OpenACC.cpp.
References findSegment().
getValuesFromSegments()
mlir::Operation::operand_range getValuesFromSegments (std::optional< mlir::ArrayAttr > arrayAttr, mlir::Operation::operand_range range, std::optional< llvm::ArrayRef< int32_t > > segments, mlir::acc::DeviceType deviceType) static
Definition at line 493 of file OpenACC.cpp.
References findSegment().
Referenced by getWaitDevnumValue(), and getWaitValuesWithoutDevnum().
getWaitDevnumValue()
mlir::Value getWaitDevnumValue (std::optional< mlir::ArrayAttr > deviceTypeAttr, mlir::Operation::operand_range operands, std::optional< llvm::ArrayRef< int32_t > > segments, std::optional< mlir::ArrayAttr > hasWaitDevnum, mlir::acc::DeviceType deviceType) static
Definition at line 509 of file OpenACC.cpp.
References findSegment(), getValuesFromSegments(), and hasDeviceTypeValues().
getWaitValuesWithoutDevnum()
mlir::Operation::operand_range getWaitValuesWithoutDevnum (std::optional< mlir::ArrayAttr > deviceTypeAttr, mlir::Operation::operand_range operands, std::optional< llvm::ArrayRef< int32_t > > segments, std::optional< mlir::ArrayAttr > hasWaitDevnum, mlir::acc::DeviceType deviceType) static
Definition at line 525 of file OpenACC.cpp.
References findSegment(), and getValuesFromSegments().
hasDeviceType()
bool hasDeviceType (std::optional< mlir::ArrayAttr > arrayAttr, mlir::acc::DeviceType deviceType) static
Definition at line 455 of file OpenACC.cpp.
References hasDeviceTypeValues().
Referenced by checkWaitAndAsyncConflict().
hasDeviceTypeValues()
bool hasDeviceTypeValues (std::optional< mlir::ArrayAttr > arrayAttr) static
Definition at line 451 of file OpenACC.cpp.
Referenced by getWaitDevnumValue(), hasDeviceType(), hasOnlyDeviceTypeNone(), printBindName(), printDeviceTypeArrayAttr(), printDeviceTypeOperands(), printDeviceTypeOperandsWithKeywordOnly(), printDeviceTypes(), printGangClause(), printRoutineGangClause(), and printWaitClause().
hasDuplicateDeviceTypes()
bool hasDuplicateDeviceTypes (std::optional< mlir::ArrayAttr > segments, llvm::SmallSet< mlir::acc::DeviceType, 3 > & deviceTypes)
Definition at line 3072 of file OpenACC.cpp.
hasOnlyDeviceTypeNone()
bool hasOnlyDeviceTypeNone (std::optional< mlir::ArrayAttr > attrs) static
Definition at line 2186 of file OpenACC.cpp.
References hasDeviceTypeValues().
Referenced by printDeviceTypeOperandsWithKeywordOnly(), printGangClause(), and printWaitClause().
isComputeOperation()
bool isComputeOperation (Operation * op) static
Definition at line 1158 of file OpenACC.cpp.
parseAccVar()
ParseResult parseAccVar (mlir::OpAsmParser & parser, OpAsmParser::UnresolvedOperand & var, mlir::Type & accVarType) static
Definition at line 656 of file OpenACC.cpp.
References mlir::AsmParser::parseColon(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), and success().
parseBindName()
ParseResult parseBindName (OpAsmParser & parser, mlir::ArrayAttr & bindIdName, mlir::ArrayAttr & bindStrName, mlir::ArrayAttr & deviceIdTypes, mlir::ArrayAttr & deviceStrTypes) static
Definition at line 4176 of file OpenACC.cpp.
References if(), mlir::AsmParser::parseCommaSeparatedList(), and mlir::AsmParser::parseOptionalLSquare().
parseCombinedConstructsLoop()
ParseResult parseCombinedConstructsLoop (mlir::OpAsmParser & parser, mlir::acc::CombinedConstructsTypeAttr & attr) static
Definition at line 2437 of file OpenACC.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseOptionalKeyword(), and success().
parseDeviceTypeArrayAttr()
ParseResult parseDeviceTypeArrayAttr (OpAsmParser & parser, mlir::ArrayAttr & deviceTypes) static
Definition at line 4351 of file OpenACC.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseRSquare(), and success().
parseDeviceTypeOperands()
ParseResult parseDeviceTypeOperands (mlir::OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, mlir::ArrayAttr & deviceTypes) static
Definition at line 2233 of file OpenACC.cpp.
References mlir::AsmParser::parseCommaSeparatedList(), and success().
parseDeviceTypeOperandsWithKeywordOnly()
ParseResult parseDeviceTypeOperandsWithKeywordOnly (mlir::OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, mlir::ArrayAttr & deviceTypes, mlir::ArrayAttr & keywordOnlyDeviceType) static
Definition at line 2271 of file OpenACC.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and success().
parseDeviceTypeOperandsWithSegment()
ParseResult parseDeviceTypeOperandsWithSegment (mlir::OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, mlir::ArrayAttr & deviceTypes, mlir::DenseI32ArrayAttr & segments) static
Definition at line 2039 of file OpenACC.cpp.
References mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::AsmParser::getContext(), mlir::AsmParser::None, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseLBrace(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRBrace(), mlir::AsmParser::parseRSquare(), and success().
parseGangClause()
ParseResult parseGangClause (OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & gangOperands, llvm::SmallVectorImpl< Type > & gangOperandsType, mlir::ArrayAttr & gangArgType, mlir::ArrayAttr & deviceType, mlir::DenseI32ArrayAttr & segments, mlir::ArrayAttr & gangOnlyDeviceType) static
Definition at line 2900 of file OpenACC.cpp.
References mlir::AsmParser::emitError(), mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseCommaSeparatedList(), parseGangValue(), mlir::AsmParser::parseLBrace(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRBrace(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseRSquare(), and success().
parseGangValue()
ParseResult parseGangValue (OpAsmParser & parser, llvm::StringRef keyword, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, llvm::SmallVector< GangArgTypeAttr > & attributes, GangArgTypeAttr gangArgType, bool & needCommaBetweenValues, bool & newValue) static
Definition at line 2881 of file OpenACC.cpp.
References mlir::AsmParser::parseColonType(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), and success().
Referenced by parseGangClause().
parseLoopControl()
ParseResult parseLoopControl (OpAsmParser & parser, Region & region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & lowerbound, SmallVectorImpl< Type > & lowerboundType, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & upperbound, SmallVectorImpl< Type > & upperboundType, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & step, SmallVectorImpl< Type > & stepType)
loop-control ::= control (ssa-id-and-type-list) = (ssa-id-and-type-list) to (ssa-id-and-type-list) step (ssa-id-and-type-list) region
Definition at line 3456 of file OpenACC.cpp.
References mlir::AsmParser::None, mlir::OpAsmParser::parseArgumentList(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), and mlir::AsmParser::parseRParen().
parseNumGangs()
ParseResult parseNumGangs (mlir::OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, mlir::ArrayAttr & deviceTypes, mlir::DenseI32ArrayAttr & segments) static
Definition at line 1972 of file OpenACC.cpp.
References mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::AsmParser::getContext(), mlir::AsmParser::None, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseLBrace(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRBrace(), mlir::AsmParser::parseRSquare(), and success().
parseOperandsWithKeywordOnly()
ParseResult parseOperandsWithKeywordOnly (mlir::OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, mlir::UnitAttr & attr) static
Definition at line 2391 of file OpenACC.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), and success().
parseOperandWithKeywordOnly()
ParseResult parseOperandWithKeywordOnly (mlir::OpAsmParser & parser, std::optional< OpAsmParser::UnresolvedOperand > & operand, mlir::Type & operandType, mlir::UnitAttr & attr) static
Definition at line 2352 of file OpenACC.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), and success().
parseRecipeSym()
ParseResult parseRecipeSym (mlir::OpAsmParser & parser, mlir::SymbolRefAttr & recipeAttr) static
Definition at line 738 of file OpenACC.cpp.
References mlir::AsmParser::parseAttribute(), and success().
parseRegions()
template<typename StructureOp> ParseResult parseRegions (OpAsmParser & parser, OperationState & state, unsigned nRegions = 1) static
Definition at line 1144 of file OpenACC.cpp.
References mlir::OperationState::addRegion(), mlir::OpAsmParser::parseRegion(), and success().
parseRoutineGangClause()
ParseResult parseRoutineGangClause (OpAsmParser & parser, mlir::ArrayAttr & gang, mlir::ArrayAttr & gangDim, mlir::ArrayAttr & gangDimDeviceTypes) static
Definition at line 4260 of file OpenACC.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and success().
parseVar()
ParseResult parseVar (mlir::OpAsmParser & parser, OpAsmParser::UnresolvedOperand & var) static
Definition at line 632 of file OpenACC.cpp.
References mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), and success().
parseVarPtrType()
ParseResult parseVarPtrType (mlir::OpAsmParser & parser, mlir::Type & varPtrType, mlir::TypeAttr & varTypeAttr) static
Definition at line 690 of file OpenACC.cpp.
References getElementType(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), and success().
parseWaitClause()
ParseResult parseWaitClause (mlir::OpAsmParser & parser, llvm::SmallVectorImpl< mlir::OpAsmParser::UnresolvedOperand > & operands, llvm::SmallVectorImpl< Type > & types, mlir::ArrayAttr & deviceTypes, mlir::DenseI32ArrayAttr & segments, mlir::ArrayAttr & hasDevNum, mlir::ArrayAttr & keywordOnly) static
Definition at line 2102 of file OpenACC.cpp.
References mlir::BoolAttr::get(), mlir::detail::DenseArrayAttrImpl< int32_t >::get(), mlir::AsmParser::getContext(), mlir::AsmParser::None, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseLBrace(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRBrace(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseRSquare(), and success().
printAccVar()
void printAccVar (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::Value accVar, mlir::Type accVarType) static
Definition at line 678 of file OpenACC.cpp.
References mlir::Value::getType(), mlir::OpAsmPrinter::printOperand(), and mlir::AsmPrinter::printType().
printBindName()
void printBindName (mlir::OpAsmPrinter & p, mlir::Operation * op, std::optional< mlir::ArrayAttr > bindIdName, std::optional< mlir::ArrayAttr > bindStrName, std::optional< mlir::ArrayAttr > deviceIdTypes, std::optional< mlir::ArrayAttr > deviceStrTypes) static
Definition at line 4230 of file OpenACC.cpp.
References hasDeviceTypeValues(), and printSingleDeviceType().
printCombinedConstructsLoop()
void printCombinedConstructsLoop (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::acc::CombinedConstructsTypeAttr attr) static
Definition at line 2457 of file OpenACC.cpp.
printDeviceTypeArrayAttr()
void printDeviceTypeArrayAttr (mlir::OpAsmPrinter & p, mlir::Operation * op, std::optional< mlir::ArrayAttr > deviceTypes) static
Definition at line 4378 of file OpenACC.cpp.
References hasDeviceTypeValues().
printDeviceTypeOperands()
void printDeviceTypeOperands (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes) static
Definition at line 2260 of file OpenACC.cpp.
References hasDeviceTypeValues(), and printSingleDeviceType().
Referenced by printDeviceTypeOperandsWithKeywordOnly().
printDeviceTypeOperandsWithKeywordOnly()
void printDeviceTypeOperandsWithKeywordOnly (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::ArrayAttr > keywordOnlyDeviceTypes) static
Definition at line 2333 of file OpenACC.cpp.
References hasDeviceTypeValues(), hasOnlyDeviceTypeNone(), printDeviceTypeOperands(), and printDeviceTypes().
printDeviceTypeOperandsWithSegment()
void printDeviceTypeOperandsWithSegment (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments) static
Definition at line 2085 of file OpenACC.cpp.
References printSingleDeviceType().
printDeviceTypes()
void printDeviceTypes (mlir::OpAsmPrinter & p, std::optional< mlir::ArrayAttr > deviceTypes) static
Definition at line 469 of file OpenACC.cpp.
References hasDeviceTypeValues().
Referenced by printDeviceTypeOperandsWithKeywordOnly(), printGangClause(), printRoutineGangClause(), and printWaitClause().
printGangClause()
void printGangClause (OpAsmPrinter & p, Operation * op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > gangArgTypes, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments, std::optional< mlir::ArrayAttr > gangOnlyDeviceTypes)
Definition at line 3027 of file OpenACC.cpp.
References hasDeviceTypeValues(), hasOnlyDeviceTypeNone(), printDeviceTypes(), and printSingleDeviceType().
printLoopControl()
void printLoopControl (OpAsmPrinter & p, Operation * op, Region & region, ValueRange lowerbound, TypeRange lowerboundType, ValueRange upperbound, TypeRange upperboundType, ValueRange steps, TypeRange stepType)
Definition at line 3487 of file OpenACC.cpp.
References mlir::Region::front(), mlir::Block::getArguments(), mlir::Value::getType(), and mlir::OpAsmPrinter::printRegion().
printNumGangs()
void printNumGangs (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments) static
Definition at line 2022 of file OpenACC.cpp.
References printSingleDeviceType().
printOperandsWithKeywordOnly()
void printOperandsWithKeywordOnly (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::OperandRange operands, mlir::TypeRange types, mlir::UnitAttr attr) static
Definition at line 2421 of file OpenACC.cpp.
printOperandWithKeywordOnly()
void printOperandWithKeywordOnly (mlir::OpAsmPrinter & p, mlir::Operation * op, std::optional< mlir::Value > operand, mlir::Type operandType, mlir::UnitAttr attr) static
Definition at line 2376 of file OpenACC.cpp.
References mlir::OpAsmPrinter::printOperand(), and mlir::AsmPrinter::printType().
printRecipeSym()
void printRecipeSym (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::SymbolRefAttr recipeAttr) static
Definition at line 745 of file OpenACC.cpp.
printRoutineGangClause()
void printRoutineGangClause (OpAsmPrinter & p, Operation * op, std::optional< mlir::ArrayAttr > gang, std::optional< mlir::ArrayAttr > gangDim, std::optional< mlir::ArrayAttr > gangDimDeviceTypes)
Definition at line 4321 of file OpenACC.cpp.
References hasDeviceTypeValues(), printDeviceTypes(), and printSingleDeviceType().
printSingleDeviceType()
void printSingleDeviceType (mlir::OpAsmPrinter & p, mlir::Attribute attr) static
Definition at line 2016 of file OpenACC.cpp.
Referenced by printBindName(), printDeviceTypeOperands(), printDeviceTypeOperandsWithSegment(), printGangClause(), printNumGangs(), printRoutineGangClause(), and printWaitClause().
printVar()
void printVar (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::Value var) static
Definition at line 647 of file OpenACC.cpp.
References mlir::Value::getType(), and mlir::OpAsmPrinter::printOperand().
printVarPtrType()
void printVarPtrType (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::Type varPtrType, mlir::TypeAttr varTypeAttr) static
Definition at line 719 of file OpenACC.cpp.
References mlir::AsmPrinter::printType().
printWaitClause()
void printWaitClause (mlir::OpAsmPrinter & p, mlir::Operation * op, mlir::OperandRange operands, mlir::TypeRange types, std::optional< mlir::ArrayAttr > deviceTypes, std::optional< mlir::DenseI32ArrayAttr > segments, std::optional< mlir::ArrayAttr > hasDevNum, std::optional< mlir::ArrayAttr > keywordOnly) static
Definition at line 2197 of file OpenACC.cpp.
References hasDeviceTypeValues(), hasOnlyDeviceTypeNone(), printDeviceTypes(), and printSingleDeviceType().
verifyDeviceTypeAndSegmentCountMatch()
template<typename Op> LogicalResult verifyDeviceTypeAndSegmentCountMatch (Op op, OperandRange operands, DenseI32ArrayAttr segments, ArrayAttr deviceTypes, llvm::StringRef keyword, int32_t maxInSegment = 0) static
Definition at line 1700 of file OpenACC.cpp.
References ArrayAttr(), mlir::detail::DenseArrayAttrImpl< T >::asArrayRef(), mlir::OpState::emitOpError(), and success().
verifyDeviceTypeCountMatch()
template<typename Op> LogicalResult verifyDeviceTypeCountMatch (Op op, OperandRange operands, ArrayAttr deviceTypes, llvm::StringRef keyword) static
Definition at line 1690 of file OpenACC.cpp.
References ArrayAttr(), mlir::OpState::emitOpError(), and success().
verifyInitLikeSingleArgRegion()
LogicalResult verifyInitLikeSingleArgRegion (Operation * op, Region & region, StringRef regionType, StringRef regionName, Type type, bool verifyYield, bool optional = false) static
Definition at line 1425 of file OpenACC.cpp.
References mlir::Operation::emitOpError(), mlir::Region::empty(), mlir::Region::front(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::Region::getOps(), mlir::Value::getType(), success(), and verifyYield().