MLIR: lib/Dialect/OpenACC/Utils/OpenACCUtils.cpp File Reference
OpenACCUtils.cpp File Reference
#include "mlir/Dialect/OpenACC/OpenACCUtils.h"
#include "mlir/Dialect/OpenACC/OpenACC.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/Support/Casting.h"
Functions
template<typename OpTy>
static bool isOnlyUsedByOpClauses (mlir::Value val, mlir::Region &region)
Function Documentation
isOnlyUsedByOpClauses()
template<typename OpTy> bool isOnlyUsedByOpClauses (mlir::Value val, mlir::Region & region) static
Definition at line 32 of file OpenACCUtils.cpp.
References mlir::Value::getUsers(), and mlir::Region::isAncestor().
Referenced by mlir::acc::isOnlyUsedByPrivateClauses(), and mlir::acc::isOnlyUsedByReductionClauses().