MLIR: lib/Dialect/OpenMP/IR/OpenMPDialect.cpp File Reference
OpenMPDialect.cpp File Reference
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/OpenMP/OpenMPClauseOperands.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Interfaces/FoldInterfaces.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/STLForwardCompat.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/bit.h"
#include "llvm/Support/InterleavedRange.h"
#include <cstddef>
#include <iterator>
#include <optional>
#include <variant>
#include "mlir/Dialect/OpenMP/OpenMPOpsDialect.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOpsEnums.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOpsInterfaces.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPTypeInterfaces.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOps.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOpsAttributes.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOpsTypes.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_TYPEDEF_LIST
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
#define GET_TYPEDEF_CLASSES
Functions
static ArrayAttr makeArrayAttr (MLIRContext *context, llvm::ArrayRef< Attribute > attrs)
static DenseBoolArrayAttr makeDenseBoolArrayAttr (MLIRContext *ctx, const ArrayRef< bool > boolArray)
static DenseI64ArrayAttr makeDenseI64ArrayAttr (MLIRContext *ctx, const ArrayRef< int64_t > intArray)
static std::string generateLoopNestingName (StringRef prefix, CanonicalLoopOp op)
Generate a name of a canonical loop nest of the format <prefix>(_r<idx>_s<idx>)*.
static ParseResult parseAllocateAndAllocator (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &allocateVars, SmallVectorImpl< Type > &allocateTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &allocatorVars, SmallVectorImpl< Type > &allocatorTypes)
Parse an allocate clause with allocators and a list of operands with types.
static void printAllocateAndAllocator (OpAsmPrinter &p, Operation *op, OperandRange allocateVars, TypeRange allocateTypes, OperandRange allocatorVars, TypeRange allocatorTypes)
Print allocate clause.
template<typename ClauseAttr>
static ParseResult parseClauseAttr (AsmParser &parser, ClauseAttr &attr)
template<typename ClauseAttr>
static void printClauseAttr (OpAsmPrinter &p, Operation *op, ClauseAttr attr)
static ParseResult parseLinearClause (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &linearVars, SmallVectorImpl< Type > &linearTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &linearStepVars)
linear ::= linear (linear-list) linear-list := linear-val | linear-val linear-list linear-val := ssa-id-and-type = ssa-id-and-type
static void printLinearClause (OpAsmPrinter &p, Operation *op, ValueRange linearVars, TypeRange linearTypes, ValueRange linearStepVars)
Print Linear Clause.
static LogicalResult verifyNontemporalClause (Operation *op, OperandRange nontemporalVars)
static LogicalResult verifyAlignedClause (Operation *op, std::optional< ArrayAttr > alignments, OperandRange alignedVars)
static ParseResult parseAlignedClause (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &alignedVars, SmallVectorImpl< Type > &alignedTypes, ArrayAttr &alignmentsAttr)
aligned ::= aligned (aligned-list) aligned-list := aligned-val | aligned-val aligned-list aligned-val := ssa-id-and-type -> alignment
static void printAlignedClause (OpAsmPrinter &p, Operation *op, ValueRange alignedVars, TypeRange alignedTypes, std::optional< ArrayAttr > alignments)
Print Aligned Clause.
static ParseResult verifyScheduleModifiers (OpAsmParser &parser, SmallVectorImpl< SmallString< 12 > > &modifiers)
static ParseResult parseScheduleClause (OpAsmParser &parser, ClauseScheduleKindAttr &scheduleAttr, ScheduleModifierAttr &scheduleMod, UnitAttr &scheduleSimd, std::optional< OpAsmParser::UnresolvedOperand > &chunkSize, Type &chunkType)
schedule ::= schedule (sched-list) sched-list ::= sched-val | sched-val sched-list | sched-val , sched-modifier sched-val ::= sched-with-chunk | sched-wo-chunk sched-with-chunk ::= sched-with-chunk-types (= ssa-id-and-type)?
static void printScheduleClause (OpAsmPrinter &p, Operation *op, ClauseScheduleKindAttr scheduleKind, ScheduleModifierAttr scheduleMod, UnitAttr scheduleSimd, Value scheduleChunk, Type scheduleChunkType)
Print schedule clause.
static ParseResult parseOrderClause (OpAsmParser &parser, ClauseOrderKindAttr &order, OrderModifierAttr &orderMod)
static void printOrderClause (OpAsmPrinter &p, Operation *op, ClauseOrderKindAttr order, OrderModifierAttr orderMod)
template<typename ClauseTypeAttr, typename ClauseType>
static ParseResult parseGranularityClause (OpAsmParser &parser, ClauseTypeAttr &prescriptiveness, std::optional< OpAsmParser::UnresolvedOperand > &operand, Type &operandType, std::optional< ClauseType >(*symbolizeClause)(StringRef), StringRef clauseName)
template<typename ClauseTypeAttr, typename ClauseType>
static void printGranularityClause (OpAsmPrinter &p, Operation *op, ClauseTypeAttr prescriptiveness, Value operand, mlir::Type operandType, StringRef(*stringifyClauseType)(ClauseType))
static ParseResult parseGrainsizeClause (OpAsmParser &parser, ClauseGrainsizeTypeAttr &grainsizeMod, std::optional< OpAsmParser::UnresolvedOperand > &grainsize, Type &grainsizeType)
static void printGrainsizeClause (OpAsmPrinter &p, Operation *op, ClauseGrainsizeTypeAttr grainsizeMod, Value grainsize, mlir::Type grainsizeType)
static ParseResult parseNumTasksClause (OpAsmParser &parser, ClauseNumTasksTypeAttr &numTasksMod, std::optional< OpAsmParser::UnresolvedOperand > &numTasks, Type &numTasksType)
static void printNumTasksClause (OpAsmPrinter &p, Operation *op, ClauseNumTasksTypeAttr numTasksMod, Value numTasks, mlir::Type numTasksType)
static constexpr StringRef getPrivateNeedsBarrierSpelling ()
static ParseResult parseClauseWithRegionArgs (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &operands, SmallVectorImpl< Type > &types, SmallVectorImpl< OpAsmParser::Argument > &regionPrivateArgs, ArrayAttr *symbols=nullptr, DenseI64ArrayAttr *mapIndices=nullptr, DenseBoolArrayAttr *byref=nullptr, ReductionModifierAttr *modifier=nullptr, UnitAttr *needsBarrier=nullptr)
static ParseResult parseBlockArgClause (OpAsmParser &parser, llvm::SmallVectorImpl< OpAsmParser::Argument > &entryBlockArgs, StringRef keyword, std::optional< MapParseArgs > mapArgs)
static ParseResult parseBlockArgClause (OpAsmParser &parser, llvm::SmallVectorImpl< OpAsmParser::Argument > &entryBlockArgs, StringRef keyword, std::optional< PrivateParseArgs > privateArgs)
static ParseResult parseBlockArgClause (OpAsmParser &parser, llvm::SmallVectorImpl< OpAsmParser::Argument > &entryBlockArgs, StringRef keyword, std::optional< ReductionParseArgs > reductionArgs)
static ParseResult parseBlockArgRegion (OpAsmParser &parser, Region &region, AllRegionParseArgs args)
static ParseResult parseTargetOpRegion (OpAsmParser &parser, Region &region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &hasDeviceAddrVars, SmallVectorImpl< Type > &hasDeviceAddrTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &hostEvalVars, SmallVectorImpl< Type > &hostEvalTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &inReductionVars, SmallVectorImpl< Type > &inReductionTypes, DenseBoolArrayAttr &inReductionByref, ArrayAttr &inReductionSyms, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &mapVars, SmallVectorImpl< Type > &mapTypes, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > &privateVars, llvm::SmallVectorImpl< Type > &privateTypes, ArrayAttr &privateSyms, UnitAttr &privateNeedsBarrier, DenseI64ArrayAttr &privateMaps)
static ParseResult parseInReductionPrivateRegion (OpAsmParser &parser, Region &region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &inReductionVars, SmallVectorImpl< Type > &inReductionTypes, DenseBoolArrayAttr &inReductionByref, ArrayAttr &inReductionSyms, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > &privateVars, llvm::SmallVectorImpl< Type > &privateTypes, ArrayAttr &privateSyms, UnitAttr &privateNeedsBarrier)
static ParseResult parseInReductionPrivateReductionRegion (OpAsmParser &parser, Region &region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &inReductionVars, SmallVectorImpl< Type > &inReductionTypes, DenseBoolArrayAttr &inReductionByref, ArrayAttr &inReductionSyms, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > &privateVars, llvm::SmallVectorImpl< Type > &privateTypes, ArrayAttr &privateSyms, UnitAttr &privateNeedsBarrier, ReductionModifierAttr &reductionMod, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &reductionVars, SmallVectorImpl< Type > &reductionTypes, DenseBoolArrayAttr &reductionByref, ArrayAttr &reductionSyms)
static ParseResult parsePrivateRegion (OpAsmParser &parser, Region &region, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > &privateVars, llvm::SmallVectorImpl< Type > &privateTypes, ArrayAttr &privateSyms, UnitAttr &privateNeedsBarrier)
static ParseResult parsePrivateReductionRegion (OpAsmParser &parser, Region &region, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > &privateVars, llvm::SmallVectorImpl< Type > &privateTypes, ArrayAttr &privateSyms, UnitAttr &privateNeedsBarrier, ReductionModifierAttr &reductionMod, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &reductionVars, SmallVectorImpl< Type > &reductionTypes, DenseBoolArrayAttr &reductionByref, ArrayAttr &reductionSyms)
static ParseResult parseTaskReductionRegion (OpAsmParser &parser, Region &region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &taskReductionVars, SmallVectorImpl< Type > &taskReductionTypes, DenseBoolArrayAttr &taskReductionByref, ArrayAttr &taskReductionSyms)
static ParseResult parseUseDeviceAddrUseDevicePtrRegion (OpAsmParser &parser, Region &region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &useDeviceAddrVars, SmallVectorImpl< Type > &useDeviceAddrTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &useDevicePtrVars, SmallVectorImpl< Type > &useDevicePtrTypes)
static void printClauseWithRegionArgs (OpAsmPrinter &p, MLIRContext *ctx, StringRef clauseName, ValueRange argsSubrange, ValueRange operands, TypeRange types, ArrayAttr symbols=nullptr, DenseI64ArrayAttr mapIndices=nullptr, DenseBoolArrayAttr byref=nullptr, ReductionModifierAttr modifier=nullptr, UnitAttr needsBarrier=nullptr)
static void printBlockArgClause (OpAsmPrinter &p, MLIRContext *ctx, StringRef clauseName, ValueRange argsSubrange, std::optional< MapPrintArgs > mapArgs)
static void printBlockArgClause (OpAsmPrinter &p, MLIRContext *ctx, StringRef clauseName, ValueRange argsSubrange, std::optional< PrivatePrintArgs > privateArgs)
static void printBlockArgClause (OpAsmPrinter &p, MLIRContext *ctx, StringRef clauseName, ValueRange argsSubrange, std::optional< ReductionPrintArgs > reductionArgs)
static void printBlockArgRegion (OpAsmPrinter &p, Operation *op, Region &region, const AllRegionPrintArgs &args)
static void printTargetOpRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange hasDeviceAddrVars, TypeRange hasDeviceAddrTypes, ValueRange hostEvalVars, TypeRange hostEvalTypes, ValueRange inReductionVars, TypeRange inReductionTypes, DenseBoolArrayAttr inReductionByref, ArrayAttr inReductionSyms, ValueRange mapVars, TypeRange mapTypes, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier, DenseI64ArrayAttr privateMaps)
static void printInReductionPrivateRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange inReductionVars, TypeRange inReductionTypes, DenseBoolArrayAttr inReductionByref, ArrayAttr inReductionSyms, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier)
static void printInReductionPrivateReductionRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange inReductionVars, TypeRange inReductionTypes, DenseBoolArrayAttr inReductionByref, ArrayAttr inReductionSyms, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier, ReductionModifierAttr reductionMod, ValueRange reductionVars, TypeRange reductionTypes, DenseBoolArrayAttr reductionByref, ArrayAttr reductionSyms)
static void printPrivateRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier)
static void printPrivateReductionRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier, ReductionModifierAttr reductionMod, ValueRange reductionVars, TypeRange reductionTypes, DenseBoolArrayAttr reductionByref, ArrayAttr reductionSyms)
static void printTaskReductionRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange taskReductionVars, TypeRange taskReductionTypes, DenseBoolArrayAttr taskReductionByref, ArrayAttr taskReductionSyms)
static void printUseDeviceAddrUseDevicePtrRegion (OpAsmPrinter &p, Operation *op, Region &region, ValueRange useDeviceAddrVars, TypeRange useDeviceAddrTypes, ValueRange useDevicePtrVars, TypeRange useDevicePtrTypes)
static LogicalResult verifyReductionVarList (Operation *op, std::optional< ArrayAttr > reductionSyms, OperandRange reductionVars, std::optional< ArrayRef< bool > > reductionByref)
Verifies Reduction Clause.
static ParseResult parseCopyprivate (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &copyprivateVars, SmallVectorImpl< Type > &copyprivateTypes, ArrayAttr &copyprivateSyms)
copyprivate-entry-list ::= copyprivate-entry | copyprivate-entry-list , copyprivate-entry copyprivate-entry ::= ssa-id -> symbol-ref : type
static void printCopyprivate (OpAsmPrinter &p, Operation *op, OperandRange copyprivateVars, TypeRange copyprivateTypes, std::optional< ArrayAttr > copyprivateSyms)
Print Copyprivate clause.
static LogicalResult verifyCopyprivateVarList (Operation *op, OperandRange copyprivateVars, std::optional< ArrayAttr > copyprivateSyms)
Verifies CopyPrivate Clause.
static ParseResult parseDependVarList (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &dependVars, SmallVectorImpl< Type > &dependTypes, ArrayAttr &dependKinds)
depend-entry-list ::= depend-entry | depend-entry-list , depend-entry depend-entry ::= depend-kind -> ssa-id : type
static void printDependVarList (OpAsmPrinter &p, Operation *op, OperandRange dependVars, TypeRange dependTypes, std::optional< ArrayAttr > dependKinds)
Print Depend clause.
static LogicalResult verifyDependVarList (Operation *op, std::optional< ArrayAttr > dependKinds, OperandRange dependVars)
Verifies Depend clause.
static ParseResult parseSynchronizationHint (OpAsmParser &parser, IntegerAttr &hintAttr)
Parses a Synchronization Hint clause.
static void printSynchronizationHint (OpAsmPrinter &p, Operation *op, IntegerAttr hintAttr)
Prints a Synchronization Hint clause.
static LogicalResult verifySynchronizationHint (Operation *op, uint64_t hint)
Verifies a synchronization hint clause.
static bool mapTypeToBool (ClauseMapFlags value, ClauseMapFlags flag)
return success ()
if (parser.parseCommaSeparatedList(parseIndices)) return failure()
if (failed(parser.parseRSquare())) return failure()
memberIdxs push_back (ArrayAttr::get(parser.getContext(), values))
values clear ()
while (succeeded(parser.parseOptionalComma()))
if (!memberIdxs.empty()) membersIdx
static void printMembersIndex (OpAsmPrinter &p, MapInfoOp op, ArrayAttr membersIdx)
static void printCaptureType (OpAsmPrinter &p, Operation *op, VariableCaptureKindAttr mapCaptureType)
static ParseResult parseCaptureType (OpAsmParser &parser, VariableCaptureKindAttr &mapCaptureType)
static LogicalResult verifyMapClause (Operation *op, OperandRange mapVars)
static LogicalResult verifyPrivateVarsMapping (TargetOp targetOp)
static LogicalResult verifyMapInfoDefinedArgs (Operation *op, StringRef clauseName, OperandRange vars)
static Operation * findCapturedOmpOp (Operation *rootOp, bool checkSingleMandatoryExec, llvm::function_ref< bool(Operation *)> siblingAllowedFn)
static bool canPromoteToNoLoop (Operation *capturedOp, TeamsOp teamsOp, WsloopOp *wsLoopOp)
Check if we can promote SPMD kernel to No-Loop kernel.
template<typename OpType>
static LogicalResult verifyPrivateVarList (OpType &op)
static bool opInGlobalImplicitParallelRegion (Operation *op)
static void printLoopTransformClis (OpAsmPrinter &p, TileOp op, OperandRange generatees, OperandRange applyees)
static ParseResult parseLoopTransformClis (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &generateesOperands, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &applyeesOperands)
static LogicalResult verifyOrderedParent (Operation &op)
static Operation * getParentInSameDialect (Operation *thisOp)
*attr dict without keyword *static mlir::ParseResult parseTargetAllocMemOp (mlir::OpAsmParser &parser, mlir::OperationState &result)
operation ::= res = (omp.target_alloc_mem) $device : devicetype, $in_type (($typeparams))? (, $shape)?
Variables
false
Parses a map_entries map type from a string format back into its numeric value.
do
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 4461 of file OpenMPDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 4464 of file OpenMPDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 4467 of file OpenMPDialect.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
canPromoteToNoLoop()
bool canPromoteToNoLoop (Operation * capturedOp, TeamsOp teamsOp, WsloopOp * wsLoopOp) static
Check if we can promote SPMD kernel to No-Loop kernel.
Definition at line 2370 of file OpenMPDialect.cpp.
References mlir::Operation::getParentOfType().
clear()
values clear ()
Referenced by mlir::detail::PassOptions::ListOption< DataType, OptionParser >::handleOccurrence().
findCapturedOmpOp()
Operation * findCapturedOmpOp (Operation * rootOp, bool checkSingleMandatoryExec, llvm::function_ref< bool(Operation *)> siblingAllowedFn) static
Definition at line 2283 of file OpenMPDialect.cpp.
References mlir::WalkResult::advance(), mlir::DominanceInfo::dominates(), mlir::Operation::getBlock(), mlir::Operation::getDialect(), mlir::Operation::getNumRegions(), mlir::Region::getOps(), mlir::Operation::getParentRegion(), mlir::Block::getSuccessors(), mlir::WalkResult::interrupt(), mlir::detail::DominanceInfoBase< IsPostDom >::isReachableFromEntry(), mlir::PreOrder, mlir::WalkResult::skip(), and mlir::Operation::walk().
generateLoopNestingName()
std::string generateLoopNestingName (StringRef prefix, CanonicalLoopOp op) static
Generate a name of a canonical loop nest of the format <prefix>(_r<idx>_s<idx>)*.
Hereby, _r<idx> identifies the region argument index of an operation that has multiple regions, if the operation has multiple regions. _s<idx> identifies the position of an operation within a region, where only operations that may potentially contain loops ("container operations" i.e. have region arguments) are counted. Again, it is omitted if there is only one such operation in a region. If there are canonical loops nested inside each other, also may also use the format _d<num> where <num> is the nesting depth of the loop.
The generated name is a best-effort to make canonical loop unique within an SSA namespace. This also means that regions with IsolatedFromAbove property do not consider any parents or siblings.
If true, this component describes a region operand of an operation (the operand's owner) If false, this component describes an operation located in a parent region
Definition at line 94 of file OpenMPDialect.cpp.
References b, mlir::Region::getBlocks(), mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), mlir::Operation::getRegions(), mlir::Operation::hasTrait(), and isUnique().
getParentInSameDialect()
Operation * getParentInSameDialect (Operation * thisOp) static
Definition at line 4035 of file OpenMPDialect.cpp.
References mlir::Operation::getDialect(), and mlir::Operation::getParentOp().
getPrivateNeedsBarrierSpelling()
constexpr StringRef getPrivateNeedsBarrierSpelling () inline static constexpr
Definition at line 852 of file OpenMPDialect.cpp.
Referenced by printClauseWithRegionArgs().
if() [1/3]
if (!memberIdxs. empty())
if() [2/3]
if (failed(parser.parseRSquare()))
if() [3/3]
if (parser. parseCommaSeparatedListparseIndices)
makeArrayAttr()
ArrayAttr makeArrayAttr (MLIRContext * context, llvm::ArrayRef< Attribute > attrs) static
Definition at line 49 of file OpenMPDialect.cpp.
References ArrayAttr(), and nullptr.
makeDenseBoolArrayAttr()
DenseBoolArrayAttr makeDenseBoolArrayAttr (MLIRContext * ctx, const ArrayRef< bool > boolArray) static
Definition at line 55 of file OpenMPDialect.cpp.
References mlir::detail::DenseArrayAttrImpl< bool >::get(), and nullptr.
makeDenseI64ArrayAttr()
DenseI64ArrayAttr makeDenseI64ArrayAttr (MLIRContext * ctx, const ArrayRef< int64_t > intArray) static
Definition at line 60 of file OpenMPDialect.cpp.
References mlir::detail::DenseArrayAttrImpl< int64_t >::get(), and nullptr.
mapTypeToBool()
bool mapTypeToBool (ClauseMapFlags value, ClauseMapFlags flag) static
Definition at line 1742 of file OpenMPDialect.cpp.
Referenced by convertClauseMapFlags(), and verifyMapClause().
opInGlobalImplicitParallelRegion()
bool opInGlobalImplicitParallelRegion (Operation * op) static
Definition at line 2616 of file OpenMPDialect.cpp.
References mlir::Operation::getDialect(), and mlir::Operation::getParentOp().
parseAlignedClause()
ParseResult parseAlignedClause (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & alignedVars, SmallVectorImpl< Type > & alignedTypes, ArrayAttr & alignmentsAttr) static
aligned ::= aligned (aligned-list) aligned-list := aligned-val | aligned-val aligned-list aligned-val := ssa-id-and-type -> alignment
Definition at line 515 of file OpenMPDialect.cpp.
References ArrayAttr(), mlir::AsmParser::parseCommaSeparatedList(), and success().
parseAllocateAndAllocator()
ParseResult parseAllocateAndAllocator (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & allocateVars, SmallVectorImpl< Type > & allocateTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & allocatorVars, SmallVectorImpl< Type > & allocatorTypes) static
Parse an allocate clause with allocators and a list of operands with types.
allocate-operand-list :: = allocate-operand | allocator-operand , allocate-operand-list allocate-operand :: = ssa-id-and-type -> ssa-id-and-type ssa-id-and-type ::= ssa-id : type
Definition at line 354 of file OpenMPDialect.cpp.
References mlir::AsmParser::parseArrow(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseCommaSeparatedList(), mlir::OpAsmParser::parseOperand(), and success().
parseBlockArgClause() [1/3]
ParseResult parseBlockArgClause (OpAsmParser & parser, llvm::SmallVectorImpl< OpAsmParser::Argument > & entryBlockArgs, StringRef keyword, std::optional< MapParseArgs > mapArgs) static
Definition at line 960 of file OpenMPDialect.cpp.
References parseClauseWithRegionArgs(), mlir::AsmParser::parseOptionalKeyword(), and success().
Referenced by parseBlockArgRegion().
parseBlockArgClause() [2/3]
ParseResult parseBlockArgClause (OpAsmParser & parser, llvm::SmallVectorImpl< OpAsmParser::Argument > & entryBlockArgs, StringRef keyword, std::optional< PrivateParseArgs > privateArgs) static
Definition at line 975 of file OpenMPDialect.cpp.
References parseClauseWithRegionArgs(), mlir::AsmParser::parseOptionalKeyword(), and success().
parseBlockArgClause() [3/3]
ParseResult parseBlockArgClause (OpAsmParser & parser, llvm::SmallVectorImpl< OpAsmParser::Argument > & entryBlockArgs, StringRef keyword, std::optional< ReductionParseArgs > reductionArgs) static
Definition at line 992 of file OpenMPDialect.cpp.
References parseClauseWithRegionArgs(), mlir::AsmParser::parseOptionalKeyword(), and success().
parseBlockArgRegion()
ParseResult parseBlockArgRegion (OpAsmParser & parser, Region & region, AllRegionParseArgs args) static
Definition at line 1008 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), parseBlockArgClause(), and mlir::OpAsmParser::parseRegion().
Referenced by parseInReductionPrivateReductionRegion(), parseInReductionPrivateRegion(), parsePrivateReductionRegion(), parsePrivateRegion(), parseTargetOpRegion(), parseTaskReductionRegion(), and parseUseDeviceAddrUseDevicePtrRegion().
parseCaptureType()
ParseResult parseCaptureType (OpAsmParser & parser, VariableCaptureKindAttr & mapCaptureType) static
Definition at line 1969 of file OpenMPDialect.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseKeyword(), and success().
parseClauseAttr()
template<typename ClauseAttr> ParseResult parseClauseAttr (AsmParser & parser, ClauseAttr & attr) static
Definition at line 397 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseKeyword(), and success().
parseClauseWithRegionArgs()
ParseResult parseClauseWithRegionArgs (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & operands, SmallVectorImpl< Type > & types, SmallVectorImpl< OpAsmParser::Argument > & regionPrivateArgs, ArrayAttr * symbols = nullptr, DenseI64ArrayAttr * mapIndices = nullptr, DenseBoolArrayAttr * byref = nullptr, ReductionModifierAttr * modifier = nullptr, UnitAttr * needsBarrier = nullptr) static
Definition at line 856 of file OpenMPDialect.cpp.
References ArrayAttr(), mlir::AsmParser::getContext(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), and success().
Referenced by parseBlockArgClause(), parseBlockArgClause(), and parseBlockArgClause().
parseCopyprivate()
ParseResult parseCopyprivate (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & copyprivateVars, SmallVectorImpl< Type > & copyprivateTypes, ArrayAttr & copyprivateSyms) static
copyprivate-entry-list ::= copyprivate-entry | copyprivate-entry-list , copyprivate-entry copyprivate-entry ::= ssa-id -> symbol-ref : type
Definition at line 1487 of file OpenMPDialect.cpp.
References ArrayAttr(), mlir::AsmParser::getContext(), mlir::AsmParser::parseCommaSeparatedList(), and success().
parseDependVarList()
ParseResult parseDependVarList (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & dependVars, SmallVectorImpl< Type > & dependTypes, ArrayAttr & dependKinds) static
depend-entry-list ::= depend-entry | depend-entry-list , depend-entry depend-entry ::= depend-kind -> ssa-id : type
Definition at line 1591 of file OpenMPDialect.cpp.
References ArrayAttr(), mlir::AsmParser::getContext(), mlir::AsmParser::parseCommaSeparatedList(), and success().
parseGrainsizeClause()
ParseResult parseGrainsizeClause (OpAsmParser & parser, ClauseGrainsizeTypeAttr & grainsizeMod, std::optional< OpAsmParser::UnresolvedOperand > & grainsize, Type & grainsizeType) static
Definition at line 764 of file OpenMPDialect.cpp.
References parseGranularityClause().
parseGranularityClause()
template<typename ClauseTypeAttr, typename ClauseType> ParseResult parseGranularityClause (OpAsmParser & parser, ClauseTypeAttr & prescriptiveness, std::optional< OpAsmParser::UnresolvedOperand > & operand, Type & operandType, std::optional< ClauseType >(* symbolizeClause)(StringRef), StringRef clauseName) static
Definition at line 710 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), and success().
Referenced by parseGrainsizeClause(), and parseNumTasksClause().
parseInReductionPrivateReductionRegion()
ParseResult parseInReductionPrivateReductionRegion (OpAsmParser & parser, Region & region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & inReductionVars, SmallVectorImpl< Type > & inReductionTypes, DenseBoolArrayAttr & inReductionByref, ArrayAttr & inReductionSyms, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > & privateVars, llvm::SmallVectorImpl< Type > & privateTypes, ArrayAttr & privateSyms, UnitAttr & privateNeedsBarrier, ReductionModifierAttr & reductionMod, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & reductionVars, SmallVectorImpl< Type > & reductionTypes, DenseBoolArrayAttr & reductionByref, ArrayAttr & reductionSyms) static
Definition at line 1103 of file OpenMPDialect.cpp.
References ArrayAttr(), and parseBlockArgRegion().
parseInReductionPrivateRegion()
ParseResult parseInReductionPrivateRegion (OpAsmParser & parser, Region & region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & inReductionVars, SmallVectorImpl< Type > & inReductionTypes, DenseBoolArrayAttr & inReductionByref, ArrayAttr & inReductionSyms, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > & privateVars, llvm::SmallVectorImpl< Type > & privateTypes, ArrayAttr & privateSyms, UnitAttr & privateNeedsBarrier) static
Definition at line 1087 of file OpenMPDialect.cpp.
References ArrayAttr(), and parseBlockArgRegion().
parseLinearClause()
ParseResult parseLinearClause (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & linearVars, SmallVectorImpl< Type > & linearTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & linearStepVars) static
linear ::= linear (linear-list) linear-list := linear-val | linear-val linear-list linear-val := ssa-id-and-type = ssa-id-and-type
Definition at line 422 of file OpenMPDialect.cpp.
References mlir::AsmParser::parseColonType(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), and success().
parseLoopTransformClis()
ParseResult parseLoopTransformClis (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & generateesOperands, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & applyeesOperands) static
Definition at line 3695 of file OpenMPDialect.cpp.
References mlir::AsmParser::Paren, mlir::AsmParser::parseLess(), mlir::AsmParser::parseMinus(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalLess(), and success().
parseNumTasksClause()
ParseResult parseNumTasksClause (OpAsmParser & parser, ClauseNumTasksTypeAttr & numTasksMod, std::optional< OpAsmParser::UnresolvedOperand > & numTasks, Type & numTasksType) static
Definition at line 786 of file OpenMPDialect.cpp.
References parseGranularityClause().
parseOrderClause()
ParseResult parseOrderClause (OpAsmParser & parser, ClauseOrderKindAttr & order, OrderModifierAttr & orderMod) static
Definition at line 675 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalColon(), and success().
parsePrivateReductionRegion()
ParseResult parsePrivateReductionRegion (OpAsmParser & parser, Region & region, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > & privateVars, llvm::SmallVectorImpl< Type > & privateTypes, ArrayAttr & privateSyms, UnitAttr & privateNeedsBarrier, ReductionModifierAttr & reductionMod, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & reductionVars, SmallVectorImpl< Type > & reductionTypes, DenseBoolArrayAttr & reductionByref, ArrayAttr & reductionSyms) static
Definition at line 1135 of file OpenMPDialect.cpp.
References ArrayAttr(), and parseBlockArgRegion().
parsePrivateRegion()
ParseResult parsePrivateRegion (OpAsmParser & parser, Region & region, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > & privateVars, llvm::SmallVectorImpl< Type > & privateTypes, ArrayAttr & privateSyms, UnitAttr & privateNeedsBarrier) static
Definition at line 1124 of file OpenMPDialect.cpp.
References ArrayAttr(), and parseBlockArgRegion().
parseScheduleClause()
ParseResult parseScheduleClause (OpAsmParser & parser, ClauseScheduleKindAttr & scheduleAttr, ScheduleModifierAttr & scheduleMod, UnitAttr & scheduleSimd, std::optional< OpAsmParser::UnresolvedOperand > & chunkSize, Type & chunkType) static
schedule ::= schedule (sched-list) sched-list ::= sched-val | sched-val sched-list | sched-val , sched-modifier sched-val ::= sched-with-chunk | sched-wo-chunk sched-with-chunk ::= sched-with-chunk-types (= ssa-id-and-type)?
sched-with-chunk-types ::= static | dynamic | guided sched-wo-chunk ::= auto | runtime sched-modifier ::= sched-mod-val | sched-mod-val , sched-mod-val sched-mod-val ::= monotonic | nonmonotonic | simd | none
Definition at line 593 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getContext(), mlir::Builder::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalEqual(), success(), and verifyScheduleModifiers().
parseSynchronizationHint()
ParseResult parseSynchronizationHint (OpAsmParser & parser, IntegerAttr & hintAttr) static
Parses a Synchronization Hint clause.
The value of hint is an integer which is a combination of different hints from omp_sync_hint_t.
hint-clause = hint (hint-value)
Definition at line 1655 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI64Type(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalKeyword(), and success().
parseTargetAllocMemOp()
*attr dict without keyword *static mlir::ParseResult parseTargetAllocMemOp (mlir::OpAsmParser & parser, mlir::OperationState & result) static
operation ::= res = (omp.target_alloc_mem) $device : devicetype, $in_type (($typeparams))? (, $shape)?
Definition at line 4319 of file OpenMPDialect.cpp.
References mlir::AsmParser::addTypeToList(), mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::Builder::getDenseI32ArrayAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::AsmParser::None, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and result.
parseTargetOpRegion()
ParseResult parseTargetOpRegion (OpAsmParser & parser, Region & region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & hasDeviceAddrVars, SmallVectorImpl< Type > & hasDeviceAddrTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & hostEvalVars, SmallVectorImpl< Type > & hostEvalTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & inReductionVars, SmallVectorImpl< Type > & inReductionTypes, DenseBoolArrayAttr & inReductionByref, ArrayAttr & inReductionSyms, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & mapVars, SmallVectorImpl< Type > & mapTypes, llvm::SmallVectorImpl< OpAsmParser::UnresolvedOperand > & privateVars, llvm::SmallVectorImpl< Type > & privateTypes, ArrayAttr & privateSyms, UnitAttr & privateNeedsBarrier, DenseI64ArrayAttr & privateMaps) static
Definition at line 1062 of file OpenMPDialect.cpp.
References ArrayAttr(), and parseBlockArgRegion().
parseTaskReductionRegion()
ParseResult parseTaskReductionRegion (OpAsmParser & parser, Region & region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & taskReductionVars, SmallVectorImpl< Type > & taskReductionTypes, DenseBoolArrayAttr & taskReductionByref, ArrayAttr & taskReductionSyms) static
Definition at line 1151 of file OpenMPDialect.cpp.
References ArrayAttr(), and parseBlockArgRegion().
parseUseDeviceAddrUseDevicePtrRegion()
ParseResult parseUseDeviceAddrUseDevicePtrRegion (OpAsmParser & parser, Region & region, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & useDeviceAddrVars, SmallVectorImpl< Type > & useDeviceAddrTypes, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & useDevicePtrVars, SmallVectorImpl< Type > & useDevicePtrTypes) static
Definition at line 1162 of file OpenMPDialect.cpp.
References parseBlockArgRegion().
printAlignedClause()
void printAlignedClause (OpAsmPrinter & p, Operation * op, ValueRange alignedVars, TypeRange alignedTypes, std::optional< ArrayAttr > alignments) static
Print Aligned Clause.
Definition at line 536 of file OpenMPDialect.cpp.
References mlir::ValueRange::getType().
printAllocateAndAllocator()
void printAllocateAndAllocator (OpAsmPrinter & p, Operation * op, OperandRange allocateVars, TypeRange allocateTypes, OperandRange allocatorVars, TypeRange allocatorTypes) static
Print allocate clause.
Definition at line 380 of file OpenMPDialect.cpp.
printBlockArgClause() [1/3]
void printBlockArgClause (OpAsmPrinter & p, MLIRContext * ctx, StringRef clauseName, ValueRange argsSubrange, std::optional< MapPrintArgs > mapArgs) static
Definition at line 1270 of file OpenMPDialect.cpp.
References printClauseWithRegionArgs().
Referenced by printBlockArgRegion().
printBlockArgClause() [2/3]
void printBlockArgClause (OpAsmPrinter & p, MLIRContext * ctx, StringRef clauseName, ValueRange argsSubrange, std::optional< PrivatePrintArgs > privateArgs) static
Definition at line 1278 of file OpenMPDialect.cpp.
References printClauseWithRegionArgs().
printBlockArgClause() [3/3]
void printBlockArgClause (OpAsmPrinter & p, MLIRContext * ctx, StringRef clauseName, ValueRange argsSubrange, std::optional< ReductionPrintArgs > reductionArgs) static
Definition at line 1289 of file OpenMPDialect.cpp.
References printClauseWithRegionArgs().
printBlockArgRegion()
void printBlockArgRegion (OpAsmPrinter & p, Operation * op, Region & region, const AllRegionPrintArgs & args) static
Definition at line 1299 of file OpenMPDialect.cpp.
References mlir::Operation::getContext(), printBlockArgClause(), and mlir::OpAsmPrinter::printRegion().
Referenced by printInReductionPrivateReductionRegion(), printInReductionPrivateRegion(), printPrivateReductionRegion(), printPrivateRegion(), printTargetOpRegion(), printTaskReductionRegion(), and printUseDeviceAddrUseDevicePtrRegion().
printCaptureType()
void printCaptureType (OpAsmPrinter & p, Operation * op, VariableCaptureKindAttr mapCaptureType) static
Definition at line 1954 of file OpenMPDialect.cpp.
printClauseAttr()
template<typename ClauseAttr> void printClauseAttr (OpAsmPrinter & p, Operation * op, ClauseAttr attr) static
Definition at line 411 of file OpenMPDialect.cpp.
printClauseWithRegionArgs()
void printClauseWithRegionArgs (OpAsmPrinter & p, MLIRContext * ctx, StringRef clauseName, ValueRange argsSubrange, ValueRange operands, TypeRange types, ArrayAttr symbols = nullptr, DenseI64ArrayAttr mapIndices = nullptr, DenseBoolArrayAttr byref = nullptr, ReductionModifierAttr modifier = nullptr, UnitAttr needsBarrier = nullptr) static
Definition at line 1218 of file OpenMPDialect.cpp.
References ArrayAttr(), mlir::detail::DenseArrayAttrImpl< bool >::get(), mlir::detail::DenseArrayAttrImpl< int64_t >::get(), and getPrivateNeedsBarrierSpelling().
Referenced by printBlockArgClause(), printBlockArgClause(), and printBlockArgClause().
printCopyprivate()
void printCopyprivate (OpAsmPrinter & p, Operation * op, OperandRange copyprivateVars, TypeRange copyprivateTypes, std::optional< ArrayAttr > copyprivateSyms) static
Print Copyprivate clause.
Definition at line 1507 of file OpenMPDialect.cpp.
printDependVarList()
void printDependVarList (OpAsmPrinter & p, Operation * op, OperandRange dependVars, TypeRange dependTypes, std::optional< ArrayAttr > dependKinds) static
Print Depend clause.
Definition at line 1616 of file OpenMPDialect.cpp.
printGrainsizeClause()
void printGrainsizeClause (OpAsmPrinter & p, Operation * op, ClauseGrainsizeTypeAttr grainsizeMod, Value grainsize, mlir::Type grainsizeType) static
Definition at line 772 of file OpenMPDialect.cpp.
References printGranularityClause().
printGranularityClause()
template<typename ClauseTypeAttr, typename ClauseType> void printGranularityClause (OpAsmPrinter & p, Operation * op, ClauseTypeAttr prescriptiveness, Value operand, mlir::Type operandType, StringRef(* stringifyClauseType)(ClauseType)) static
Definition at line 746 of file OpenMPDialect.cpp.
Referenced by printGrainsizeClause(), and printNumTasksClause().
printInReductionPrivateReductionRegion()
void printInReductionPrivateReductionRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange inReductionVars, TypeRange inReductionTypes, DenseBoolArrayAttr inReductionByref, ArrayAttr inReductionSyms, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier, ReductionModifierAttr reductionMod, ValueRange reductionVars, TypeRange reductionTypes, DenseBoolArrayAttr reductionByref, ArrayAttr reductionSyms) static
Definition at line 1365 of file OpenMPDialect.cpp.
References ArrayAttr(), and printBlockArgRegion().
printInReductionPrivateRegion()
void printInReductionPrivateRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange inReductionVars, TypeRange inReductionTypes, DenseBoolArrayAttr inReductionByref, ArrayAttr inReductionSyms, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier) static
Definition at line 1351 of file OpenMPDialect.cpp.
References ArrayAttr(), and printBlockArgRegion().
printLinearClause()
void printLinearClause (OpAsmPrinter & p, Operation * op, ValueRange linearVars, TypeRange linearTypes, ValueRange linearStepVars) static
Print Linear Clause.
Definition at line 443 of file OpenMPDialect.cpp.
printLoopTransformClis()
void printLoopTransformClis (OpAsmPrinter & p, TileOp op, OperandRange generatees, OperandRange applyees) static
Definition at line 3685 of file OpenMPDialect.cpp.
printMembersIndex()
void printMembersIndex (OpAsmPrinter & p, MapInfoOp op, ArrayAttr membersIdx) static
Definition at line 1939 of file OpenMPDialect.cpp.
References ArrayAttr().
printNumTasksClause()
void printNumTasksClause (OpAsmPrinter & p, Operation * op, ClauseNumTasksTypeAttr numTasksMod, Value numTasks, mlir::Type numTasksType) static
Definition at line 794 of file OpenMPDialect.cpp.
References printGranularityClause().
printOrderClause()
void printOrderClause (OpAsmPrinter & p, Operation * op, ClauseOrderKindAttr order, OrderModifierAttr orderMod) static
Definition at line 699 of file OpenMPDialect.cpp.
printPrivateReductionRegion()
void printPrivateReductionRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier, ReductionModifierAttr reductionMod, ValueRange reductionVars, TypeRange reductionTypes, DenseBoolArrayAttr reductionByref, ArrayAttr reductionSyms) static
Definition at line 1395 of file OpenMPDialect.cpp.
References ArrayAttr(), and printBlockArgRegion().
printPrivateRegion()
void printPrivateRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier) static
Definition at line 1384 of file OpenMPDialect.cpp.
References ArrayAttr(), and printBlockArgRegion().
printScheduleClause()
void printScheduleClause (OpAsmPrinter & p, Operation * op, ClauseScheduleKindAttr scheduleKind, ScheduleModifierAttr scheduleMod, UnitAttr scheduleSimd, Value scheduleChunk, Type scheduleChunkType) static
Print schedule clause.
Definition at line 655 of file OpenMPDialect.cpp.
References mlir::Value::getType().
printSynchronizationHint()
void printSynchronizationHint (OpAsmPrinter & p, Operation * op, IntegerAttr hintAttr) static
Prints a Synchronization Hint clause.
Definition at line 1686 of file OpenMPDialect.cpp.
printTargetOpRegion()
void printTargetOpRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange hasDeviceAddrVars, TypeRange hasDeviceAddrTypes, ValueRange hostEvalVars, TypeRange hostEvalTypes, ValueRange inReductionVars, TypeRange inReductionTypes, DenseBoolArrayAttr inReductionByref, ArrayAttr inReductionSyms, ValueRange mapVars, TypeRange mapTypes, ValueRange privateVars, TypeRange privateTypes, ArrayAttr privateSyms, UnitAttr privateNeedsBarrier, DenseI64ArrayAttr privateMaps) static
Definition at line 1331 of file OpenMPDialect.cpp.
References ArrayAttr(), and printBlockArgRegion().
printTaskReductionRegion()
void printTaskReductionRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange taskReductionVars, TypeRange taskReductionTypes, DenseBoolArrayAttr taskReductionByref, ArrayAttr taskReductionSyms) static
Definition at line 1410 of file OpenMPDialect.cpp.
References ArrayAttr(), and printBlockArgRegion().
printUseDeviceAddrUseDevicePtrRegion()
void printUseDeviceAddrUseDevicePtrRegion (OpAsmPrinter & p, Operation * op, Region & region, ValueRange useDeviceAddrVars, TypeRange useDeviceAddrTypes, ValueRange useDevicePtrVars, TypeRange useDevicePtrTypes) static
Definition at line 1422 of file OpenMPDialect.cpp.
References printBlockArgRegion().
push_back()
memberIdxs push_back (ArrayAttr::get(parser.getContext(), values))
Referenced by applyTilingToAll(), and getReassociationForFlattening().
success()
return success ()
Referenced by parseAllocateAndAllocator(), parseBlockArgClause(), parseBlockArgClause(), parseBlockArgClause(), parseCaptureType(), parseClauseAttr(), parseCopyprivate(), parseDependVarList(), parseGranularityClause(), parseLinearClause(), parseLoopTransformClis(), parseOrderClause(), parseScheduleClause(), parseSynchronizationHint(), verifyAlignedClause(), verifyCopyprivateVarList(), verifyDependVarList(), verifyMapClause(), verifyMapInfoDefinedArgs(), verifyNontemporalClause(), verifyOrderedParent(), verifyPrivateVarList(), verifyPrivateVarsMapping(), verifyReductionVarList(), verifyScheduleModifiers(), and verifySynchronizationHint().
verifyAlignedClause()
LogicalResult verifyAlignedClause (Operation * op, std::optional< ArrayAttr > alignments, OperandRange alignedVars) static
Definition at line 475 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), and success().
verifyCopyprivateVarList()
LogicalResult verifyCopyprivateVarList (Operation * op, OperandRange copyprivateVars, std::optional< ArrayAttr > copyprivateSyms) static
Verifies CopyPrivate Clause.
Definition at line 1523 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), mlir::SymbolTable::lookupNearestSymbolFrom(), and success().
verifyDependVarList()
LogicalResult verifyDependVarList (Operation * op, std::optional< ArrayAttr > dependKinds, OperandRange dependVars) static
Verifies Depend clause.
Definition at line 1631 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), and success().
verifyMapClause()
LogicalResult verifyMapClause (Operation * op, OperandRange mapVars) static
Definition at line 1991 of file OpenMPDialect.cpp.
References mlir::emitError(), mlir::Operation::getLoc(), mapTypeToBool(), and success().
verifyMapInfoDefinedArgs()
LogicalResult verifyMapInfoDefinedArgs (Operation * op, StringRef clauseName, OperandRange vars) static
Definition at line 2082 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), and success().
verifyNontemporalClause()
LogicalResult verifyNontemporalClause (Operation * op, OperandRange nontemporalVars) static
Definition at line 460 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), and success().
verifyOrderedParent()
LogicalResult verifyOrderedParent (Operation & op) static
Definition at line 3844 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), mlir::Operation::getParentOfType(), mlir::Operation::getParentOp(), and success().
verifyPrivateVarList()
template<typename OpType> LogicalResult verifyPrivateVarList (OpType & op) static
Definition at line 2528 of file OpenMPDialect.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom(), and success().
verifyPrivateVarsMapping()
LogicalResult verifyPrivateVarsMapping (TargetOp targetOp) static
Definition at line 2060 of file OpenMPDialect.cpp.
References mlir::emitError(), and success().
verifyReductionVarList()
LogicalResult verifyReductionVarList (Operation * op, std::optional< ArrayAttr > reductionSyms, OperandRange reductionVars, std::optional< ArrayRef< bool > > reductionByref) static
Verifies Reduction Clause.
Definition at line 1436 of file OpenMPDialect.cpp.
References mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::Value::getType(), mlir::SymbolTable::lookupNearestSymbolFrom(), and success().
verifyScheduleModifiers()
ParseResult verifyScheduleModifiers (OpAsmParser & parser, SmallVectorImpl< SmallString< 12 > > & modifiers) static
Definition at line 552 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getNameLoc(), and success().
Referenced by parseScheduleClause().
verifySynchronizationHint()
LogicalResult verifySynchronizationHint (Operation * op, uint64_t hint) static
Verifies a synchronization hint clause.
Definition at line 1717 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), and success().
while()
while (succeeded(parser.parseOptionalComma()))
Variable Documentation
do
do
Initial value:
{
    if (failed(parser.parseLSquare()))
      return failure()
Definition at line 1919 of file OpenMPDialect.cpp.
false
false
Parses a map_entries map type from a string format back into its numeric value.
map-clause = map_clauses (((always, ? implicit, ? ompx_hold, ? / close, ? present, ? (to | from | delete))+)`) static ParseResult parseMapClause(OpAsmParser &parser, ClauseMapFlagsAttr &mapType) { ClauseMapFlags mapTypeBits = ClauseMapFlags::none; This simply verifies the correct keyword is read in, the keyword itself is stored inside of the operation auto parseTypeAndMod = [&]() -> ParseResult { StringRef mapTypeMod; if (parser.parseKeyword(&mapTypeMod)) return failure();
if (mapTypeMod == "always") mapTypeBits |= ClauseMapFlags::always;
if (mapTypeMod == "implicit") mapTypeBits |= ClauseMapFlags::implicit;
if (mapTypeMod == "ompx_hold") mapTypeBits |= ClauseMapFlags::ompx_hold;
if (mapTypeMod == "close") mapTypeBits |= ClauseMapFlags::close;
if (mapTypeMod == "present") mapTypeBits |= ClauseMapFlags::present;
if (mapTypeMod == "to") mapTypeBits |= ClauseMapFlags::to;
if (mapTypeMod == "from") mapTypeBits |= ClauseMapFlags::from;
if (mapTypeMod == "tofrom") mapTypeBits |= ClauseMapFlags::to | ClauseMapFlags::from;
if (mapTypeMod == "delete") mapTypeBits |= ClauseMapFlags::del;
if (mapTypeMod == "storage") mapTypeBits |= ClauseMapFlags::storage;
if (mapTypeMod == "return_param") mapTypeBits |= ClauseMapFlags::return_param;
if (mapTypeMod == "private") mapTypeBits |= ClauseMapFlags::priv;
if (mapTypeMod == "literal") mapTypeBits |= ClauseMapFlags::literal;
if (mapTypeMod == "attach") mapTypeBits |= ClauseMapFlags::attach;
if (mapTypeMod == "attach_always") mapTypeBits |= ClauseMapFlags::attach_always;
if (mapTypeMod == "attach_none") mapTypeBits |= ClauseMapFlags::attach_none;
if (mapTypeMod == "attach_auto") mapTypeBits |= ClauseMapFlags::attach_auto;
if (mapTypeMod == "ref_ptr") mapTypeBits |= ClauseMapFlags::ref_ptr;
if (mapTypeMod == "ref_ptee") mapTypeBits |= ClauseMapFlags::ref_ptee;
if (mapTypeMod == "ref_ptr_ptee") mapTypeBits |= ClauseMapFlags::ref_ptr_ptee;
if (mapTypeMod == "is_device_ptr") mapTypeBits |= ClauseMapFlags::is_device_ptr;
return success(); };
if (parser.parseCommaSeparatedList(parseTypeAndMod)) return failure();
mapType = parser.getBuilder().getAttr<mlir::omp::ClauseMapFlagsAttr>(mapTypeBits);
return success(); }
/ Prints a map_entries map type from its numeric value out into its string / format. static void printMapClause(OpAsmPrinter &p, Operation *op, ClauseMapFlagsAttr mapType) { llvm::SmallVector<std::string, 4> mapTypeStrs; ClauseMapFlags mapFlags = mapType.getValue();
handling of always, close, present placed at the beginning of the string to aid readability if (mapTypeToBool(mapFlags, ClauseMapFlags::always)) mapTypeStrs.push_back("always"); if (mapTypeToBool(mapFlags, ClauseMapFlags::implicit)) mapTypeStrs.push_back("implicit"); if (mapTypeToBool(mapFlags, ClauseMapFlags::ompx_hold)) mapTypeStrs.push_back("ompx_hold"); if (mapTypeToBool(mapFlags, ClauseMapFlags::close)) mapTypeStrs.push_back("close"); if (mapTypeToBool(mapFlags, ClauseMapFlags::present)) mapTypeStrs.push_back("present");
special handling of to/from/tofrom/delete and release/alloc, release + alloc are the abscense of one of the other flags, whereas tofrom requires both the to and from flag to be set. bool to = mapTypeToBool(mapFlags, ClauseMapFlags::to); bool from = mapTypeToBool(mapFlags, ClauseMapFlags::from);
if (to && from) mapTypeStrs.push_back("tofrom"); else if (from) mapTypeStrs.push_back("from"); else if (to) mapTypeStrs.push_back("to");
if (mapTypeToBool(mapFlags, ClauseMapFlags::del)) mapTypeStrs.push_back("delete"); if (mapTypeToBool(mapFlags, ClauseMapFlags::return_param)) mapTypeStrs.push_back("return_param"); if (mapTypeToBool(mapFlags, ClauseMapFlags::storage)) mapTypeStrs.push_back("storage"); if (mapTypeToBool(mapFlags, ClauseMapFlags::priv)) mapTypeStrs.push_back("private"); if (mapTypeToBool(mapFlags, ClauseMapFlags::literal)) mapTypeStrs.push_back("literal"); if (mapTypeToBool(mapFlags, ClauseMapFlags::attach)) mapTypeStrs.push_back("attach"); if (mapTypeToBool(mapFlags, ClauseMapFlags::attach_always)) mapTypeStrs.push_back("attach_always"); if (mapTypeToBool(mapFlags, ClauseMapFlags::attach_none)) mapTypeStrs.push_back("attach_none"); if (mapTypeToBool(mapFlags, ClauseMapFlags::attach_auto)) mapTypeStrs.push_back("attach_auto"); if (mapTypeToBool(mapFlags, ClauseMapFlags::ref_ptr)) mapTypeStrs.push_back("ref_ptr"); if (mapTypeToBool(mapFlags, ClauseMapFlags::ref_ptee)) mapTypeStrs.push_back("ref_ptee"); if (mapTypeToBool(mapFlags, ClauseMapFlags::ref_ptr_ptee)) mapTypeStrs.push_back("ref_ptr_ptee"); if (mapTypeToBool(mapFlags, ClauseMapFlags::is_device_ptr)) mapTypeStrs.push_back("is_device_ptr"); if (mapFlags == ClauseMapFlags::none) mapTypeStrs.push_back("none");
for (unsigned int i = 0; i < mapTypeStrs.size(); ++i) { p << mapTypeStrs[i]; if (i + 1 < mapTypeStrs.size()) { p << ", "; } } }
static ParseResult parseMembersIndex(OpAsmParser &parser, ArrayAttr &membersIdx) { SmallVector<Attribute> values, memberIdxs;
auto parseIndices = [&]() -> ParseResult { int64_t value; if (parser.parseInteger(value)) return failure(); values.push_back(IntegerAttr::get(parser.getBuilder().getIntegerType(64), APInt(64, value, /*isSigned=
Definition at line 1915 of file OpenMPDialect.cpp.
Referenced by mlir::Operation::CloneOptions::CloneOptions(), mlir::LLVM::detail::DebugTranslation::DebugTranslation(), mlir::sparse_tensor::ir_detail::DimLvlMap::DimLvlMap(), mlir::SideEffects::EffectInstance< Effect >::EffectInstance(), mlir::SideEffects::EffectInstance< Effect >::EffectInstance(), mlir::SideEffects::EffectInstance< Effect >::EffectInstance(), mlir::SideEffects::EffectInstance< Effect >::EffectInstance(), mlir::SideEffects::EffectInstance< Effect >::EffectInstance(), mlir::SideEffects::EffectInstance< Effect >::EffectInstance(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::Key(), mlir::sparse_tensor::LatPoint::LatPoint(), mlir::pdll::Lexer::Lexer(), mlir::sparse_tensor::Merger::Merger(), mlir::detail::OperandStorage::OperandStorage(), mlir::OpPrintingFlags::OpPrintingFlags(), mlir::detail::PassOptions::Option< DataType, OptionParser >::Option(), mlir::detail::PassExecutionState::PassExecutionState(), mlir::PassManager::PassManager(), mlir::PassManager::PassManager(), mlir::PassPipelineCLParser::PassPipelineCLParser(), mlir::ShapedTypeComponents::ShapedTypeComponents(), mlir::presburger::Simplex::Simplex(), mlir::presburger::SimplexBase::SimplexBase(), mlir::spirv::detail::StructTypeStorage::StructTypeStorage(), mlir::spirv::detail::StructTypeStorage::StructTypeStorage(), and mlir::tosa::ValueKnowledge::ValueKnowledge().