MLIR: lib/Dialect/OpenACC/Utils/OpenACCUtilsTiling.cpp File Reference
OpenACCUtilsTiling.cpp File Reference
#include "mlir/Dialect/OpenACC/OpenACCUtilsTiling.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/OpenACC/OpenACC.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Transforms/RegionUtils.h"
Functions
static mlir::Value resolveAndCastTileSize (mlir::Value tileSize, int32_t defaultTileSize, mlir::Type targetType, mlir::RewriterBase &rewriter, mlir::Location loc)
static void removeWorkerVectorFromLoop (mlir::acc::LoopOp loop)
static mlir::acc::LoopOp createACCLoopFromOriginal (mlir::acc::LoopOp origLoop, mlir::RewriterBase &rewriter, mlir::ValueRange lb, mlir::ValueRange ub, mlir::ValueRange step, mlir::DenseBoolArrayAttr inclusiveUBAttr, mlir::acc::CombinedConstructsTypeAttr combinedAttr, mlir::Location loc, bool preserveCollapse)
static mlir::acc::LoopOp createInnerLoop (mlir::acc::LoopOp inputLoop, mlir::RewriterBase &rewriter, mlir::ValueRange lb, mlir::ValueRange ub, mlir::ValueRange step, mlir::DenseBoolArrayAttr inclusiveUBAttr, mlir::Location loc)
static void moveOpsAndReplaceIVs (mlir::acc::LoopOp sourceLoop, mlir::acc::LoopOp targetLoop, llvm::ArrayRef< mlir::Value > newIVs, llvm::ArrayRef< mlir::Value > origIVs, size_t nOps, mlir::RewriterBase &rewriter)
Function Documentation
createACCLoopFromOriginal()
mlir::acc::LoopOp createACCLoopFromOriginal (mlir::acc::LoopOp origLoop, mlir::RewriterBase & rewriter, mlir::ValueRange lb, mlir::ValueRange ub, mlir::ValueRange step, mlir::DenseBoolArrayAttr inclusiveUBAttr, mlir::acc::CombinedConstructsTypeAttr combinedAttr, mlir::Location loc, bool preserveCollapse) static
Definition at line 52 of file OpenACCUtilsTiling.cpp.
Referenced by createInnerLoop(), and mlir::acc::uncollapseLoops().
createInnerLoop()
mlir::acc::LoopOp createInnerLoop (mlir::acc::LoopOp inputLoop, mlir::RewriterBase & rewriter, mlir::ValueRange lb, mlir::ValueRange ub, mlir::ValueRange step, mlir::DenseBoolArrayAttr inclusiveUBAttr, mlir::Location loc) static
Definition at line 83 of file OpenACCUtilsTiling.cpp.
References createACCLoopFromOriginal(), mlir::OpBuilder::createBlock(), mlir::RewriterBase::finalizeOpModification(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::RewriterBase::startOpModification().
Referenced by mlir::acc::tileACCLoops(), and mlir::acc::uncollapseLoops().
moveOpsAndReplaceIVs()
void moveOpsAndReplaceIVs (mlir::acc::LoopOp sourceLoop, mlir::acc::LoopOp targetLoop, llvm::ArrayRef< mlir::Value > newIVs, llvm::ArrayRef< mlir::Value > origIVs, size_t nOps, mlir::RewriterBase & rewriter) static
Definition at line 119 of file OpenACCUtilsTiling.cpp.
References mlir::replaceAllUsesInRegionWith().
Referenced by mlir::acc::tileACCLoops(), and mlir::acc::uncollapseLoops().
removeWorkerVectorFromLoop()
void removeWorkerVectorFromLoop (mlir::acc::LoopOp loop) static
Definition at line 40 of file OpenACCUtilsTiling.cpp.
Referenced by mlir::acc::tileACCLoops().
resolveAndCastTileSize()
mlir::Value resolveAndCastTileSize (mlir::Value tileSize, int32_t defaultTileSize, mlir::Type targetType, mlir::RewriterBase & rewriter, mlir::Location loc) static
Definition at line 23 of file OpenACCUtilsTiling.cpp.
References mlir::getConstantIntValue(), mlir::Builder::getIntegerAttr(), and mlir::getValueOrCreateCastToIndexLike().
Referenced by mlir::acc::tileACCLoops().