MLIR: lib/TableGen/Operator.cpp File Reference
Operator.cpp File Reference
#include "mlir/TableGen/Operator.h"
#include "mlir/TableGen/Argument.h"
#include "mlir/TableGen/Predicate.h"
#include "mlir/TableGen/Trait.h"
#include "mlir/TableGen/Type.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
Macros
#define DEBUG_TYPE "mlir-tblgen-operator"
Functions
static void assertAccessorInvariants (const Operator &op, StringRef name)
Assert the invariants of accessors generated for the given name.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-tblgen-operator"
Definition at line 29 of file Operator.cpp.
Function Documentation
assertAccessorInvariants()
static void assertAccessorInvariants (const Operator & op, StringRef name) static
Assert the invariants of accessors generated for the given name.
Definition at line 80 of file Operator.cpp.
References mlir::tblgen::Operator::getLoc(), mlir::tblgen::Operator::getNumOperands(), mlir::tblgen::Operator::getNumRegions(), mlir::tblgen::Operator::getNumResults(), mlir::tblgen::Operator::getNumVariableLengthOperands(), and mlir::tblgen::Operator::getNumVariadicRegions().
Referenced by mlir::tblgen::Operator::assertInvariants().