MLIR: lib/ExecutionEngine/OptUtils.cpp File Reference
OptUtils.cpp File Reference
#include "mlir/ExecutionEngine/OptUtils.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/LegacyPassNameParser.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Coroutines.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include <climits>
#include <mutex>
Functions
static void runPasses (llvm::legacy::PassManager &modulePM, llvm::legacy::FunctionPassManager &funcPM, llvm::Module &m)
static void populatePassManagers (llvm::legacy::PassManager &modulePM, llvm::legacy::FunctionPassManager &funcPM, unsigned optLevel, unsigned sizeLevel, llvm::TargetMachine *targetMachine)
Function Documentation
populatePassManagers()
static void populatePassManagers (llvm::legacy::PassManager & modulePM, llvm::legacy::FunctionPassManager & funcPM, unsigned optLevel, unsigned sizeLevel, llvm::TargetMachine * targetMachine) static
Definition at line 65 of file OptUtils.cpp.
References mlir::makeLLVMPassesTransformer, mlir::makeOptimizingTransformer, runPasses(), and mlir::success().
runPasses()
static void runPasses (llvm::legacy::PassManager & modulePM, llvm::legacy::FunctionPassManager & funcPM, llvm::Module & m) static
Definition at line 35 of file OptUtils.cpp.
Referenced by mlir::PassManager::IRPrinterConfig::getOpPrintingFlags(), populatePassManagers(), and mlir::detail::PassCrashReproducerGenerator::removeLastReproducerFor().