MLIR: lib/Dialect/Bufferization/Transforms/OwnershipBasedBufferDeallocation.cpp File Reference
OwnershipBasedBufferDeallocation.cpp File Reference
#include "mlir/Dialect/Bufferization/IR/BufferDeallocationOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/Iterators.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Classes
class mlir::bufferization::impl::OwnershipBasedBufferDeallocationPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::bufferization
namespace mlir::bufferization::impl
Macros
#define GEN_PASS_DEF_OWNERSHIPBASEDBUFFERDEALLOCATIONPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::bufferization::impl::createOwnershipBasedBufferDeallocationPass ()
std::unique_ptr<::mlir::Pass > mlir::bufferization::impl::createOwnershipBasedBufferDeallocationPass (OwnershipBasedBufferDeallocationPassOptions options)
std::unique_ptr<::mlir::Pass > mlir::bufferization::createOwnershipBasedBufferDeallocationPass ()
std::unique_ptr<::mlir::Pass > mlir::bufferization::createOwnershipBasedBufferDeallocationPass (OwnershipBasedBufferDeallocationPassOptions options)
static Value buildBoolValue (OpBuilder &builder, Location loc, bool value)
static bool isMemref (Value v)
static bool hasNeitherAllocateNorFreeSideEffect (Operation *op)
Return "true" if the given op is guaranteed to have neither "Allocate" nor "Free" side effects.
static bool hasBufferSemantics (Operation *op)
Return "true" if the given op has buffer semantics.
Macro Definition Documentation
GEN_PASS_DEF_OWNERSHIPBASEDBUFFERDEALLOCATIONPASS
#define GEN_PASS_DEF_OWNERSHIPBASEDBUFFERDEALLOCATIONPASS
Definition at line 33 of file OwnershipBasedBufferDeallocation.cpp.
Function Documentation
buildBoolValue()
Value buildBoolValue (OpBuilder & builder, Location loc, bool value) static
Definition at line 45 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::Builder::getBoolAttr().
hasBufferSemantics()
bool hasBufferSemantics (Operation * op) static
Return "true" if the given op has buffer semantics.
I.e., it has buffer operands, buffer results and/or buffer region entry block arguments.
Definition at line 60 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::Operation::getOperands(), mlir::Operation::getRegions(), mlir::Operation::getResults(), and isMemref().
hasNeitherAllocateNorFreeSideEffect()
bool hasNeitherAllocateNorFreeSideEffect (Operation * op) static
Return "true" if the given op is guaranteed to have neither "Allocate" nor "Free" side effects.
Definition at line 53 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::mightHaveEffect().
isMemref()
bool isMemref (Value v) static
Definition at line 49 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::Value::getType().
Referenced by mlir::bufferization::createOwnershipBasedBufferDeallocationPass().