MLIR: lib/Dialect/GPU/Transforms/ParallelLoopMapper.cpp File Reference
ParallelLoopMapper.cpp File Reference
#include "mlir/Dialect/GPU/ParallelLoopMapper.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/GPU/Passes.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Dialect/GPU/ParallelLoopMapperAttr.cpp.inc"
#include "mlir/Dialect/GPU/ParallelLoopMapperEnums.cpp.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::gpu
Enumerations
enum MappingLevel
Functions
StringRef mlir::gpu::getMappingAttrName ()
Name of the mapping attribute produced by loop mappers.
ParallelLoopDimMapping mlir::gpu::getParallelLoopDimMappingAttr (Processor processor, AffineMap map, AffineMap bound)
Helper function to create a ParallelDimMapperAttr.
LogicalResult mlir::gpu::setMappingAttr (scf::ParallelOp ploopOp, ArrayRef< ParallelLoopDimMapping > mapping)
Sets the mapping attribute of a scf.parallel operation.
MappingLevel & operator++ (MappingLevel &mappingLevel)
Bounded increment on MappingLevel.
static gpu::Processor getHardwareIdForMapping (MappingLevel level, int dimension)
Computed the hardware id to use for a given mapping level.
static void mapParallelOp (ParallelOp parallelOp, MappingLevel mappingLevel=MapGrid)
Add mapping information to the given parallel loop.
Enumeration Type Documentation
MappingLevel
enum MappingLevel
Definition at line 64 of file ParallelLoopMapper.cpp.
Function Documentation
getHardwareIdForMapping()
static gpu::Processor getHardwareIdForMapping (MappingLevel level, int dimension) static
Computed the hardware id to use for a given mapping level.
Will assign x,y and z hardware ids for the first 3 dimensions and use sequential after. TODO: Make this use x for the inner-most loop that is distributed to map to x, the next innermost to y and the next innermost to z.
Definition at line 85 of file ParallelLoopMapper.cpp.
Referenced by mapParallelOp().
mapParallelOp()
static void mapParallelOp (ParallelOp parallelOp, MappingLevel mappingLevel = MapGrid) static
Add mapping information to the given parallel loop.
Do not add mapping information if the loop already has it. Also, don't start a mapping at a nested loop.
Definition at line 122 of file ParallelLoopMapper.cpp.
References mlir::Builder::getDimIdentityMap(), getHardwareIdForMapping(), mlir::gpu::getMappingAttrName(), mlir::gpu::getParallelLoopDimMappingAttr(), op, and mlir::gpu::setMappingAttr().
Referenced by mlir::greedilyMapParallelSCFToGPU().
operator++()
MappingLevel& operator++ (MappingLevel & mappingLevel)
Bounded increment on MappingLevel.
Increments to the next level unless Sequential was already reached.
Definition at line 72 of file ParallelLoopMapper.cpp.
Referenced by mlir::ReductionNode::getVariants().