MLIR: lib/Pass/PassCrashRecovery.cpp File Reference
PassCrashRecovery.cpp File Reference
#include "PassDetail.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/ToolOutputFile.h"
Classes
struct mlir::detail::RecoveryReproducerContext
This class contains all of the context for generating a recovery reproducer.
struct mlir::detail::PassCrashReproducerGenerator::Impl
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::detail
AttrTypeReplacer.
Functions
static void appendReproducer (std::string &description, Operation *op, const ReproducerStreamFactory &factory, const std::string &pipelineElements, bool disableThreads, bool verifyPasses)
static void formatPassOpReproducerMessage (Diagnostic &os, std::pair< Pass *, Operation * > passOpPair)
static ReproducerStreamFactory makeReproducerStreamFactory (StringRef outputFile)
void printAsTextualPipeline (raw_ostream &os, StringRef anchorName, const llvm::iterator_range< OpPassManager::pass_iterator > &passes, bool pretty=false)
Function Documentation
appendReproducer()
void appendReproducer (std::string & description, Operation * op, const ReproducerStreamFactory & factory, const std::string & pipelineElements, bool disableThreads, bool verifyPasses) static
Definition at line 107 of file PassCrashRecovery.cpp.
References mlir::AsmState::attachResourcePrinter(), mlir::AsmResourceBuilder::buildBool(), mlir::AsmResourceBuilder::buildString(), mlir::Operation::getName(), and mlir::Operation::print().
Referenced by mlir::detail::RecoveryReproducerContext::generate(), and mlir::makeReproducer().
formatPassOpReproducerMessage()
void formatPassOpReproducerMessage (Diagnostic & os, std::pair< Pass *, Operation * > passOpPair) static
Definition at line 227 of file PassCrashRecovery.cpp.
Referenced by mlir::detail::PassCrashReproducerGenerator::finalize().
makeReproducerStreamFactory()
ReproducerStreamFactory makeReproducerStreamFactory (StringRef outputFile) static
Definition at line 431 of file PassCrashRecovery.cpp.
References mlir::openOutputFile().
Referenced by mlir::PassManager::enableCrashReproducerGeneration(), and mlir::makeReproducer().
printAsTextualPipeline()
void printAsTextualPipeline (raw_ostream & os, StringRef anchorName, const llvm::iterator_range< OpPassManager::pass_iterator > & passes, bool pretty = false)
Definition at line 445 of file Pass.cpp.
References printAsTextualPipeline().