MLIR: lib/Dialect/PDLInterp/IR/PDLInterp.cpp File Reference
PDLInterp.cpp File Reference
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOpsDialect.cpp.inc"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
template<typename OpT>
static LogicalResult verifySwitchOp (OpT op)
static ParseResult parseCreateOperationOpAttributes (OpAsmParser &p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &attrOperands, ArrayAttr &attrNamesAttr)
static void printCreateOperationOpAttributes (OpAsmPrinter &p, CreateOperationOp op, OperandRange attrArgs, ArrayAttr attrNames)
static ParseResult parseCreateOperationOpResults (OpAsmParser &p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &resultOperands, SmallVectorImpl< Type > &resultTypes, UnitAttr &inferredResultTypes)
static void printCreateOperationOpResults (OpAsmPrinter &p, CreateOperationOp op, OperandRange resultOperands, TypeRange resultTypes, UnitAttr inferredResultTypes)
static Type getGetValueTypeOpValueType (Type type)
Given the result type of a GetValueTypeOp, return the expected input type.
static ParseResult parseRangeType (OpAsmParser &p, TypeRange argumentTypes, Type &resultType)
static void printRangeType (OpAsmPrinter &p, CreateRangeOp op, TypeRange argumentTypes, Type resultType)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 318 of file PDLInterp.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getGetValueTypeOpValueType()
Type getGetValueTypeOpValueType (Type type) static
Given the result type of a GetValueTypeOp, return the expected input type.
Definition at line 238 of file PDLInterp.cpp.
References mlir::Type::getContext().
parseCreateOperationOpAttributes()
ParseResult parseCreateOperationOpAttributes (OpAsmParser & p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & attrOperands, ArrayAttr & attrNamesAttr) static
Definition at line 66 of file PDLInterp.cpp.
References ArrayAttr(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalLBrace(), mlir::AsmParser::parseRBrace(), and success().
parseCreateOperationOpResults()
ParseResult parseCreateOperationOpResults (OpAsmParser & p, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & resultOperands, SmallVectorImpl< Type > & resultTypes, UnitAttr & inferredResultTypes) static
Definition at line 102 of file PDLInterp.cpp.
References mlir::AsmParser::getBuilder(), mlir::Builder::getUnitAttr(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalArrow(), mlir::AsmParser::parseOptionalLess(), mlir::AsmParser::parseRParen(), and success().
parseRangeType()
ParseResult parseRangeType (OpAsmParser & p, TypeRange argumentTypes, Type & resultType) static
Definition at line 248 of file PDLInterp.cpp.
References mlir::pdl::getRangeElementTypeOrSelf(), mlir::AsmParser::parseColonType(), and success().
printCreateOperationOpAttributes()
void printCreateOperationOpAttributes (OpAsmPrinter & p, CreateOperationOp op, OperandRange attrArgs, ArrayAttr attrNames) static
Definition at line 90 of file PDLInterp.cpp.
References ArrayAttr().
printCreateOperationOpResults()
void printCreateOperationOpResults (OpAsmPrinter & p, CreateOperationOp op, OperandRange resultOperands, TypeRange resultTypes, UnitAttr inferredResultTypes) static
Definition at line 122 of file PDLInterp.cpp.
printRangeType()
void printRangeType (OpAsmPrinter & p, CreateRangeOp op, TypeRange argumentTypes, Type resultType) static
Definition at line 260 of file PDLInterp.cpp.
verifySwitchOp()
template<typename OpT> LogicalResult verifySwitchOp (OpT op) static
Definition at line 31 of file PDLInterp.cpp.
References success().