MLIR: lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp File Reference
PDLToPDLInterp.cpp File Reference
#include "mlir/Conversion/PDLToPDLInterp/PDLToPDLInterp.h"
#include "../PassDetail.h"
#include "PredicateTree.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
template<typename OpT , typename PredT , typename ValT = typename PredT::KeyTy>
static void createSwitchOp (Value val, Block *defaultDest, OpBuilder &builder, llvm::MapVector< Qualifier *, Block *> &dests)
Function Documentation
createSwitchOp()
template<typename OpT , typename PredT , typename ValT = typename PredT::KeyTy> static void createSwitchOp (Value val, Block * defaultDest, OpBuilder & builder, llvm::MapVector< Qualifier *, Block *> & dests) static
Definition at line 363 of file PDLToPDLInterp.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::pdl_to_pdl_interp::Predicates::AttributeQuestion, mlir::OpBuilder::create(), mlir::Block::end(), mlir::detail::enumerate(), mlir::Block::erase(), mlir::Operation::getBlock(), mlir::pdl_to_pdl_interp::SwitchNode::getChild(), mlir::pdl_to_pdl_interp::SwitchNode::getChildren(), mlir::Value::getDefiningOp(), mlir::Builder::getFunctionType(), mlir::pdl_to_pdl_interp::Qualifier::getKind(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Block::getOperations(), mlir::Builder::getType(), mlir::Value::getType(), mlir::OperandRange::getType(), mlir::Type::isa(), mlir::Operation::isBeforeInBlock(), loc, op, mlir::pdl_to_pdl_interp::Predicates::OperandCountAtLeastQuestion, mlir::pdl_to_pdl_interp::Predicates::OperandCountQuestion, mlir::pdl_to_pdl_interp::Predicates::OperationNameQuestion, mlir::pdl_to_pdl_interp::Predicates::ResultCountAtLeastQuestion, mlir::pdl_to_pdl_interp::Predicates::ResultCountQuestion, rewriter, mlir::pdl_to_pdl_interp::Predicates::TypeQuestion, mlir::pdl_to_pdl_interp::Predicates::UnsignedAnswer, and value.