MLIR: lib/Dialect/PDL/IR/PDLTypes.cpp File Reference
PDLTypes.cpp File Reference
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/PDL/IR/PDLOpsTypes.cpp.inc"
Macros
#define GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_LIST
Functions
static Type parsePDLType (DialectAsmParser &parser)
Macro Definition Documentation
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 22 of file PDLTypes.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
parsePDLType()
static Type parsePDLType (DialectAsmParser & parser) static
Definition at line 36 of file PDLTypes.cpp.
References mlir::DialectAsmParser::emitError(), mlir::failed(), mlir::DialectAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::DialectAsmParser::getNameLoc(), mlir::DialectAsmParser::parseKeyword(), mlir::LLVM::detail::parseType(), and mlir::LLVM::detail::printType().
Referenced by mlir::pdl::PDLType::classof().