MLIR: lib/Dialect/Math/Transforms/PolynomialApproximation.cpp File Reference
PolynomialApproximation.cpp File Reference
#include <climits>
#include <cmath>
#include <cstddef>
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Math/Transforms/Approximation.h"
#include "mlir/Dialect/Math/Transforms/Passes.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/Dialect/X86Vector/X86VectorDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/MathExtras.h"
Classes
struct VectorShape
Macros
#define LN2_VALUE 0.693147180559945309417232121458176568075500134360255254120680009493393621L
#define LOG2E_VALUE 1.442695040888963407359924681001892137426645954152985934135449406931109219L
#define TWO_OVER_PI 0.6366197723675813430755350534900574481378385829618257949906693762L
#define PI_OVER_2 1.5707963267948966192313216916397514420985846996875529104874722961L
Functions
static std::optional< VectorShape > vectorShape (Type type)
static std::optional< VectorShape > vectorShape (Value value)
static Type broadcast (Type type, std::optional< VectorShape > shape)
static Value broadcast (ImplicitLocOpBuilder &builder, Value value, std::optional< VectorShape > shape)
static Value handleMultidimensionalVectors (ImplicitLocOpBuilder &builder, ValueRange operands, int64_t vectorWidth, llvm::function_ref< Value(ValueRange)> compute)
static Value boolCst (ImplicitLocOpBuilder &builder, bool value)
static Value floatCst (ImplicitLocOpBuilder &builder, float value, Type elementType)
static Value f32Cst (ImplicitLocOpBuilder &builder, double value)
static Value i32Cst (ImplicitLocOpBuilder &builder, int32_t value)
static Value f32FromBits (ImplicitLocOpBuilder &builder, uint32_t bits)
static Value min (ImplicitLocOpBuilder &builder, Value value, Value bound)
static Value max (ImplicitLocOpBuilder &builder, Value value, Value bound)
static Value clamp (ImplicitLocOpBuilder &builder, Value value, Value lowerBound, Value upperBound)
static std::pair< Value, Value > frexp (ImplicitLocOpBuilder &builder, Value arg, bool isPositive=false)
static Value exp2I32 (ImplicitLocOpBuilder &builder, Value arg)
template<typename T >
LogicalResult insertCasts (Operation *op, PatternRewriter &rewriter)
template<typename OpType >
static void populateMathF32ExpansionPattern (RewritePatternSet &patterns, llvm::function_ref< bool(StringRef)> predicate, PatternBenefit benefit)
template<typename OpType , typename PatternType >
static void populateMathPolynomialApproximationPattern (RewritePatternSet &patterns, llvm::function_ref< bool(StringRef)> predicate, PatternBenefit benefit)
Macro Definition Documentation
LN2_VALUE
#define LN2_VALUE 0.693147180559945309417232121458176568075500134360255254120680009493393621L
Definition at line 620 of file PolynomialApproximation.cpp.
LOG2E_VALUE
#define LOG2E_VALUE 1.442695040888963407359924681001892137426645954152985934135449406931109219L
Definition at line 622 of file PolynomialApproximation.cpp.
PI_OVER_2
#define PI_OVER_2 1.5707963267948966192313216916397514420985846996875529104874722961L
Definition at line 1482 of file PolynomialApproximation.cpp.
TWO_OVER_PI
#define TWO_OVER_PI 0.6366197723675813430755350534900574481378385829618257949906693762L
Definition at line 1480 of file PolynomialApproximation.cpp.
Function Documentation
boolCst()
static Value boolCst (ImplicitLocOpBuilder & builder, bool value) static
Definition at line 174 of file PolynomialApproximation.cpp.
References mlir::Builder::getBoolAttr().
Referenced by mlir::math::ErfcPolynomialApproximation::matchAndRewrite().
broadcast() [1/2]
static Value broadcast (ImplicitLocOpBuilder & builder, Value value, std::optional< VectorShape > shape) static
Definition at line 70 of file PolynomialApproximation.cpp.
References broadcast(), and mlir::Value::getType().
broadcast() [2/2]
static Type broadcast (Type type, std::optional< VectorShape > shape) static
Definition at line 63 of file PolynomialApproximation.cpp.
References mlir::get().
Referenced by broadcast(), exp2I32(), frexp(), mlir::math::ErfcPolynomialApproximation::matchAndRewrite(), and mlir::math::ErfPolynomialApproximation::matchAndRewrite().
clamp()
static Value clamp (ImplicitLocOpBuilder & builder, Value value, Value lowerBound, Value upperBound) static
Definition at line 220 of file PolynomialApproximation.cpp.
References max(), and min().
Referenced by createLinalgBodyCalculationForElementwiseOp(), isMaskTriviallyFoldable(), and wmmaPushOutputOperand().
exp2I32()
static Value exp2I32 (ImplicitLocOpBuilder & builder, Value arg) static
Definition at line 268 of file PolynomialApproximation.cpp.
References broadcast(), mlir::getElementTypeOrSelf(), mlir::Builder::getF32Type(), i32Cst(), and vectorShape().
f32Cst()
static Value f32Cst (ImplicitLocOpBuilder & builder, double value) static
Definition at line 186 of file PolynomialApproximation.cpp.
References mlir::Builder::getF32FloatAttr().
Referenced by frexp().
f32FromBits()
static Value f32FromBits (ImplicitLocOpBuilder & builder, uint32_t bits) static
Definition at line 194 of file PolynomialApproximation.cpp.
References mlir::Builder::getF32Type(), and i32Cst().
Referenced by frexp().
floatCst()
static Value floatCst (ImplicitLocOpBuilder & builder, float value, Type elementType) static
Definition at line 178 of file PolynomialApproximation.cpp.
References mlir::Builder::getFloatAttr(), mlir::Type::isF16(), and mlir::Type::isF32().
Referenced by mlir::math::ErfcPolynomialApproximation::matchAndRewrite(), and mlir::math::ErfPolynomialApproximation::matchAndRewrite().
frexp()
static std::pair<Value, Value> frexp (ImplicitLocOpBuilder & builder, Value arg, bool isPositive = false) static
Definition at line 227 of file PolynomialApproximation.cpp.
References broadcast(), f32Cst(), f32FromBits(), mlir::getElementTypeOrSelf(), mlir::Builder::getF32Type(), mlir::Builder::getIntegerType(), i32Cst(), and vectorShape().
Referenced by computeMultiplierAndShiftTosaScale16(), and computeMultiplierAndShiftTosaScale32().
handleMultidimensionalVectors()
static Value handleMultidimensionalVectors (ImplicitLocOpBuilder & builder, ValueRange operands, int64_t vectorWidth, llvm::function_ref< Value(ValueRange)> compute) static
Definition at line 97 of file PolynomialApproximation.cpp.
References mlir::computeMaxLinearIndex(), mlir::computeStrides(), mlir::delinearize(), mlir::detail::enumerate(), mlir::get(), mlir::getType(), and mlir::Builder::getZeroAttr().
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite().
i32Cst()
static Value i32Cst (ImplicitLocOpBuilder & builder, int32_t value) static
Definition at line 190 of file PolynomialApproximation.cpp.
References mlir::Builder::getI32IntegerAttr().
Referenced by exp2I32(), f32FromBits(), and frexp().
insertCasts()
template<typename T > LogicalResult insertCasts (Operation * op, PatternRewriter & rewriter)
Definition at line 318 of file PolynomialApproximation.cpp.
References mlir::ValueTypeRange< ValueRangeT >::front(), mlir::Operation::getAttrs(), mlir::getElementTypeOrSelf(), mlir::Builder::getF32Type(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOpWithNewOp().
max()
static Value max (ImplicitLocOpBuilder & builder, Value value, Value bound) static
Definition at line 212 of file PolynomialApproximation.cpp.
Referenced by mlir::tensor::bubbleUpPadSlice(), mlir::tosa::buildQTypeFromMinMax(), calculateStructAlignment(), mlir::sparse_tensor::detail::checkedMul(), mlir::sparse_tensor::detail::checkOverflowCast(), clamp(), mlir::tosa::clampFloatHelper(), clampInput(), mlir::tosa::clampIntHelper(), computeDirectionVector(), computeMultiplierAndShiftTosaScale16(), computeMultiplierAndShiftTosaScale32(), mlir::presburger::IntegerRelation::computeVolume(), mlir::concatAffineMaps(), createLinalgBodyCalculationForElementwiseOp(), declareReduction(), executeGetOperandsResults(), mlir::quant::CalibratedQuantizedType::get(), mlir::quant::CalibratedQuantizedType::getChecked(), getDefaultStorageParams(), mlir::affine::NestedPattern::getDepth(), mlir::affine::getInnermostCommonLoopDepth(), mlir::affine::getLargestDivisorOfTripCount(), mlir::AffineMap::getLargestKnownDivisorOfMapExprs(), getLocationFromLoc(), mlir::getMaxDimAndSymbol(), getMaxPosOfType(), mlir::presburger::detail::getNonOrthogonalVector(), getNumRecords(), mlir::detail::PassOptions::getOptionWidth(), mlir::affine::getPerfectlyNestedLoops(), getReduxIntrinsicId(), getSemiAffineExprFromFlatForm(), mlir::presburger::PresburgerSpace::getVarKindOverlap(), handleByValArgument(), mlir::intrange::inferShapedDimOpInterface(), mlir::intrange::inferXor(), isFusionProfitable(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), mlir::AffineMap::isPermutationOfMinorIdentityWithBroadcasting(), isSumOfIntegerArrayAttrConfinedToShape(), loopScheduling(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), ClampClampOptimization::matchAndRewrite(), mlir::presburger::Matrix< T >::Matrix(), maybeConstantDimsAttr(), minMaxBy(), mlirCalibratedQuantizedTypeGet(), parseAndVerify< unsigned >(), parseCalibratedType(), parseExpressedTypeAndRange(), mlir::detail::Parser::parseIntegerInDimensionList(), mlir::detail::Parser::parseStridedLayoutAttr(), populateDialectQuantSubmodule(), mlir::printRegisteredPasses(), mlir::ConstantIntRanges::range(), mlir::affine::FlatAffineRelation::removeVarRange(), mlir::InlinerConfig::setMaxInliningIterations(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::OpTrait::util::staticallyKnownBroadcastable(), staticallyOutOfBounds(), mlir::affine::substWithMin(), mlir::raw_indented_ostream::unindent(), mlir::presburger::IntegerRelation::unionBoundingBox(), mlir::presburger::updatePrintMetrics(), mlir::quant::CalibratedQuantizedType::verifyInvariants(), mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments(), and mlir::quant::UniformQuantizedValueConverter::~UniformQuantizedValueConverter().
min()
static Value min (ImplicitLocOpBuilder & builder, Value value, Value bound) static
Definition at line 204 of file PolynomialApproximation.cpp.
Referenced by addOrderingConstraints(), mlir::tensor::bubbleUpPadSlice(), mlir::tosa::buildQTypeFromMinMax(), mlir::sparse_tensor::detail::checkOverflowCast(), clamp(), mlir::tosa::clampFloatHelper(), clampInput(), mlir::tosa::clampIntHelper(), computeDirectionVector(), mlir::presburger::IntegerRelation::computeVolume(), createLinalgBodyCalculationForElementwiseOp(), declareReduction(), mlir::shard::Sharding::equalSplitAxes(), mlir::sparse_tensor::genCoIteration(), mlir::quant::CalibratedQuantizedType::get(), getBestVarToEliminate(), mlir::quant::CalibratedQuantizedType::getChecked(), mlir::affine::getConstantTripCount(), getDefaultStorageParams(), mlir::affine::getInnermostCommonLoopDepth(), getMaxLoopDepth(), getNumCommonLoops(), mlir::affine::getNumCommonSurroundingLoops(), getReduxIntrinsicId(), mlir::presburger::PresburgerSpace::getVarKindOverlap(), mlir::intrange::inferShapedDimOpInterface(), mlir::intrange::inferXor(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isSumOfIntegerArrayAttrConfinedToShape(), loopScheduling(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::gpu::index_lowering::OpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), ClampClampOptimization::matchAndRewrite(), memsetRewire(), minMaxBy(), minMaxValueForFloat(), minMaxValueForSignedInt(), minMaxValueForUnsignedInt(), mlirCalibratedQuantizedTypeGet(), parseCalibratedType(), parseExpressedTypeAndRange(), populateDialectQuantSubmodule(), mlir::detail::pass_options::printOptionValue(), mlir::raw_indented_ostream::printReindented(), mlir::ConstantIntRanges::range(), mlir::presburger::IntegerRelation::removeVarRange(), mlir::affine::FlatAffineRelation::removeVarRange(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::affine::substWithMin(), mlir::presburger::IntegerRelation::unionBoundingBox(), mlir::quant::CalibratedQuantizedType::verifyInvariants(), mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments(), and mlir::quant::UniformQuantizedValueConverter::~UniformQuantizedValueConverter().
populateMathF32ExpansionPattern()
template<typename OpType > static void populateMathF32ExpansionPattern (RewritePatternSet & patterns, llvm::function_ref< bool(StringRef)> predicate, PatternBenefit benefit) static
Definition at line 1785 of file PolynomialApproximation.cpp.
References mlir::patterns.
populateMathPolynomialApproximationPattern()
template<typename OpType , typename PatternType > static void populateMathPolynomialApproximationPattern (RewritePatternSet & patterns, llvm::function_ref< bool(StringRef)> predicate, PatternBenefit benefit) static
Definition at line 1825 of file PolynomialApproximation.cpp.
References mlir::patterns.
Referenced by mlir::populateMathPolynomialApproximationPatterns().
vectorShape() [1/2]
static std::optional<VectorShape> vectorShape (Type type) static
Definition at line 47 of file PolynomialApproximation.cpp.
Referenced by exp2I32(), extractInsertFoldConstantOp(), foreachIndividualVectorElement(), frexp(), VectorizationState::getCanonicalVecType(), mlir::vector::isContiguousSlice(), mlir::math::ErfcPolynomialApproximation::matchAndRewrite(), mlir::math::ErfPolynomialApproximation::matchAndRewrite(), and vectorShape().
vectorShape() [2/2]
static std::optional<VectorShape> vectorShape (Value value) static
Definition at line 54 of file PolynomialApproximation.cpp.
References mlir::Value::getType(), and vectorShape().