MLIR: lib/Tools/mlir-lsp-server/lsp/Protocol.cpp File Reference
Protocol.cpp File Reference
#include "Protocol.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
Functions
template<typename T >
static bool mapOptOrNull (const llvm::json::Value &params, llvm::StringLiteral prop, T &out, llvm::json::Path path)
static bool isWindowsPath (StringRef path)
static bool isNetworkPath (StringRef path)
static bool shouldEscapeInURI (unsigned char c)
static void percentEncode (StringRef content, std::string &out)
Encodes a string according to percent-encoding.
static std::string percentDecode (StringRef content)
Decodes a string according to percent-encoding.
static bool isValidScheme (StringRef scheme)
static llvm::Expected< std::string > uriFromAbsolutePath (StringRef absolutePath)
static llvm::Expected< std::string > getAbsolutePath (StringRef authority, StringRef body)
static llvm::Expected< std::string > parseFilePathFromURI (StringRef origUri)
static llvm::StringRef toTextKind (MarkupKind kind)
Function Documentation
getAbsolutePath()
static llvm::Expected<std::string> getAbsolutePath (StringRef authority, StringRef body) static
Definition at line 154 of file Protocol.cpp.
References isWindowsPath().
Referenced by parseFilePathFromURI().
isNetworkPath()
static bool isNetworkPath (StringRef path) static
Definition at line 56 of file Protocol.cpp.
Referenced by uriFromAbsolutePath().
isValidScheme()
static bool isValidScheme (StringRef scheme) static
Definition at line 116 of file Protocol.cpp.
Referenced by parseFilePathFromURI().
isWindowsPath()
static bool isWindowsPath (StringRef path) static
Definition at line 52 of file Protocol.cpp.
Referenced by getAbsolutePath(), and uriFromAbsolutePath().
mapOptOrNull()
template<typename T > static bool mapOptOrNull (const llvm::json::Value & params, llvm::StringLiteral prop, T & out, llvm::json::Path path) static
Definition at line 29 of file Protocol.cpp.
References mlir::lsp::fromJSON(), and mlir::lsp::LSPError::ID.
parseFilePathFromURI()
static llvm::Expected<std::string> parseFilePathFromURI (StringRef origUri) static
Definition at line 175 of file Protocol.cpp.
References getAbsolutePath(), isValidScheme(), and percentDecode().
Referenced by mlir::lsp::URIForFile::fromURI().
percentDecode()
static std::string percentDecode (StringRef content) static
Decodes a string according to percent-encoding.
Definition at line 98 of file Protocol.cpp.
Referenced by parseFilePathFromURI().
percentEncode()
static void percentEncode (StringRef content, std::string & out) static
Encodes a string according to percent-encoding.
Unreserved characters are not escaped.
Reserved characters always escaped with exceptions like '/'.
All other characters are escaped.
Definition at line 85 of file Protocol.cpp.
References shouldEscapeInURI().
Referenced by uriFromAbsolutePath().
shouldEscapeInURI()
static bool shouldEscapeInURI (unsigned char c) static
Definition at line 61 of file Protocol.cpp.
Referenced by percentEncode().
toTextKind()
static llvm::StringRef toTextKind (MarkupKind kind) static
Definition at line 485 of file Protocol.cpp.
References mlir::lsp::Markdown, and mlir::lsp::PlainText.
Referenced by mlir::lsp::operator<<(), and mlir::lsp::toJSON().
uriFromAbsolutePath()
static llvm::Expected<std::string> uriFromAbsolutePath (StringRef absolutePath) static
Definition at line 126 of file Protocol.cpp.
References isNetworkPath(), isWindowsPath(), and percentEncode().
Referenced by mlir::lsp::URIForFile::fromFile().