MLIR: lib/Dialect/Ptr/IR/PtrDialect.cpp File Reference
PtrDialect.cpp File Reference
#include "mlir/Dialect/Ptr/IR/PtrOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Interfaces/DataLayoutInterfaces.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/Ptr/IR/PtrOps.cpp.inc"
#include "mlir/Dialect/Ptr/IR/PtrOpsAttrs.cpp.inc"
#include "mlir/Dialect/Ptr/IR/PtrOpsTypes.cpp.inc"
#include "mlir/Dialect/Ptr/IR/PtrOpsDialect.cpp.inc"
#include "mlir/Dialect/Ptr/IR/PtrOpsEnums.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_TYPEDEF_LIST
#define GET_ATTRDEF_CLASSES
#define GET_TYPEDEF_CLASSES
#define GET_OP_CLASSES
Functions
static LogicalResult verifyAlignment (std::optional< int64_t > alignment, function_ref< InFlightDiagnostic()> emitError)
Verifies that the alignment attribute is a power of 2 if present.
template<typename OpTy>
static LogicalResult verifyAtomicMemOp (OpTy memOp, ArrayRef< AtomicOrdering > unsupportedOrderings)
Verifies the attributes and the type of atomic memory access operations.
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 479 of file PtrDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 487 of file PtrDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 484 of file PtrDialect.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
verifyAlignment()
LogicalResult verifyAlignment (std::optional< int64_t > alignment, function_ref< InFlightDiagnostic()> emitError) static
Verifies that the alignment attribute is a power of 2 if present.
Definition at line 49 of file PtrDialect.cpp.
References mlir::emitError(), and success().
verifyAtomicMemOp()
template<typename OpTy> LogicalResult verifyAtomicMemOp (OpTy memOp, ArrayRef< AtomicOrdering > unsupportedOrderings) static
Verifies the attributes and the type of atomic memory access operations.
Definition at line 151 of file PtrDialect.cpp.
References success().