MLIR: lib/Conversion/PtrToLLVM/PtrToLLVM.cpp File Reference
PtrToLLVM.cpp File Reference
#include "mlir/Conversion/PtrToLLVM/PtrToLLVM.h"
#include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Dialect/LLVMIR/LLVMAttrs.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/Ptr/IR/PtrOps.h"
#include "mlir/IR/TypeUtilities.h"
#include <type_traits>
Functions
static FailureOr< LLVM::LLVMStructType > createMemRefMetadataType (MemRefType type, const LLVMTypeConverter &typeConverter)
Function Documentation
createMemRefMetadataType()
FailureOr< LLVM::LLVMStructType > createMemRefMetadataType (MemRefType type, const LLVMTypeConverter & typeConverter) static
Definition at line 84 of file PtrToLLVM.cpp.
References mlir::LLVMTypeConverter::getIndexType(), and mlir::LLVMTypeConverter::getMemRefAddressSpace().
Referenced by mlir::ptr::populatePtrToLLVMConversionPatterns().