MLIR: lib/CAPI/Dialect/Quant.cpp File Reference
Quant.cpp File Reference
#include "mlir-c/Dialect/Quant.h"
#include "mlir-c/BuiltinAttributes.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/Quant/IR/Quant.h"
#include "mlir/Dialect/Quant/IR/QuantTypes.h"
Functions
bool mlirTypeIsAQuantizedType (MlirType type)
Returns true if the given type is a quantization dialect type.
unsigned mlirQuantizedTypeGetSignedFlag ()
Returns the bit flag used to indicate signedness of a quantized type.
int64_t mlirQuantizedTypeGetDefaultMinimumForInteger (bool isSigned, unsigned integralWidth)
Returns the minimum possible value stored by a quantized type.
int64_t mlirQuantizedTypeGetDefaultMaximumForInteger (bool isSigned, unsigned integralWidth)
Returns the maximum possible value stored by a quantized type.
MlirType mlirQuantizedTypeGetExpressedType (MlirType type)
Gets the original type approximated by the given quantized type.
unsigned mlirQuantizedTypeGetFlags (MlirType type)
Gets the flags associated with the given quantized type.
bool mlirQuantizedTypeIsSigned (MlirType type)
Returns true if the given type is signed, false otherwise.
MlirType mlirQuantizedTypeGetStorageType (MlirType type)
Returns the underlying type used to store the values.
int64_t mlirQuantizedTypeGetStorageTypeMin (MlirType type)
Returns the minimum value that the storage type of the given quantized type can take.
int64_t mlirQuantizedTypeGetStorageTypeMax (MlirType type)
Returns the maximum value that the storage type of the given quantized type can take.
unsigned mlirQuantizedTypeGetStorageTypeIntegralWidth (MlirType type)
Returns the integral bitwidth that the storage type of the given quantized type can represent exactly.
bool mlirQuantizedTypeIsCompatibleExpressedType (MlirType type, MlirType candidate)
Returns true if the candidate type is compatible with the given quantized type.
MlirType mlirQuantizedTypeGetQuantizedElementType (MlirType type)
Returns the element type of the given quantized type as another quantized type.
MlirType mlirQuantizedTypeCastFromStorageType (MlirType type, MlirType candidate)
Casts from a type based on the storage type of the given type to a corresponding type based on the given type.
MlirType mlirQuantizedTypeCastToStorageType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the storage type.
MlirType mlirQuantizedTypeCastFromExpressedType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given type to a corresponding type based on the given type.
MlirType mlirQuantizedTypeCastToExpressedType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the expressed type.
MlirType mlirQuantizedTypeCastExpressedToStorageType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given quantized type to equivalent type based on storage type of the same quantized type.
bool mlirTypeIsAAnyQuantizedType (MlirType type)
Returns true if the given type is an AnyQuantizedType.
MlirType mlirAnyQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of AnyQuantizedType with the given parameters in the same context as storageType and returns it.
bool mlirTypeIsAUniformQuantizedType (MlirType type)
Returns true if the given type is a UniformQuantizedType.
MlirType mlirUniformQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedType with the given parameters in the same context as storageType and returns it.
double mlirUniformQuantizedTypeGetScale (MlirType type)
Returns the scale of the given uniform quantized type.
int64_t mlirUniformQuantizedTypeGetZeroPoint (MlirType type)
Returns the zero point of the given uniform quantized type.
bool mlirUniformQuantizedTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized type is fixed-point.
bool mlirTypeIsAUniformQuantizedPerAxisType (MlirType type)
Returns true if the given type is a UniformQuantizedPerAxisType.
MlirType mlirUniformQuantizedPerAxisTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, intptr_t nDims, double *scales, int64_t *zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedPerAxisType with the given parameters in the same context as storageType and returns it.
intptr_t mlirUniformQuantizedPerAxisTypeGetNumDims (MlirType type)
Returns the number of axes in the given quantized per-axis type.
double mlirUniformQuantizedPerAxisTypeGetScale (MlirType type, intptr_t pos)
Returns pos-th scale of the given quantized per-axis type.
int64_t mlirUniformQuantizedPerAxisTypeGetZeroPoint (MlirType type, intptr_t pos)
Returns pos-th zero point of the given quantized per-axis type.
int32_t mlirUniformQuantizedPerAxisTypeGetQuantizedDimension (MlirType type)
Returns the index of the quantized dimension in the given quantized per-axis type.
bool mlirUniformQuantizedPerAxisTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized per-axis type is fixed-point.
bool mlirTypeIsAUniformQuantizedSubChannelType (MlirType type)
Returns true if the given type is a UniformQuantizedSubChannel.
MlirType mlirUniformQuantizedSubChannelTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, MlirAttribute scalesAttr, MlirAttribute zeroPointsAttr, intptr_t nDims, int32_t *quantizedDimensions, int64_t *blockSizes, int64_t storageTypeMin, int64_t storageTypeMax)
Creates a UniformQuantizedSubChannelType with the given parameters.
intptr_t mlirUniformQuantizedSubChannelTypeGetNumBlockSizes (MlirType type)
Returns the number of block sizes provided in type.
int32_t mlirUniformQuantizedSubChannelTypeGetQuantizedDimension (MlirType type, intptr_t pos)
Returns the quantized dimension at the given position.
int64_t mlirUniformQuantizedSubChannelTypeGetBlockSize (MlirType type, intptr_t pos)
Returns the block size at the given position.
MlirAttribute mlirUniformQuantizedSubChannelTypeGetScales (MlirType type)
Returns the scales of the quantized type.
MlirAttribute mlirUniformQuantizedSubChannelTypeGetZeroPoints (MlirType type)
Returns the zero-points of the quantized type.
bool mlirTypeIsACalibratedQuantizedType (MlirType type)
Returns true if the given type is a CalibratedQuantizedType.
MlirType mlirCalibratedQuantizedTypeGet (MlirType expressedType, double min, double max)
Creates an instance of CalibratedQuantizedType with the given parameters in the same context as expressedType and returns it.
double mlirCalibratedQuantizedTypeGetMin (MlirType type)
Returns the min value of the given calibrated quantized type.
double mlirCalibratedQuantizedTypeGetMax (MlirType type)
Returns the max value of the given calibrated quantized type.
Function Documentation
mlirAnyQuantizedTypeGet()
MlirType mlirAnyQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of AnyQuantizedType with the given parameters in the same context as storageType and returns it.
The instance is owned by the context.
Definition at line 116 of file Quant.cpp.
References mlir::quant::AnyQuantizedType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirCalibratedQuantizedTypeGet()
MlirType mlirCalibratedQuantizedTypeGet (MlirType expressedType, double min, double max)
Creates an instance of CalibratedQuantizedType with the given parameters in the same context as expressedType and returns it.
The instance is owned by the context.
Definition at line 261 of file Quant.cpp.
References mlir::quant::CalibratedQuantizedType::get(), max(), min(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirCalibratedQuantizedTypeGetMax()
double mlirCalibratedQuantizedTypeGetMax (MlirType type)
Returns the max value of the given calibrated quantized type.
Definition at line 271 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirCalibratedQuantizedTypeGetMin()
double mlirCalibratedQuantizedTypeGetMin (MlirType type)
Returns the min value of the given calibrated quantized type.
Definition at line 267 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastExpressedToStorageType()
MlirType mlirQuantizedTypeCastExpressedToStorageType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given quantized type to equivalent type based on storage type of the same quantized type.
Definition at line 102 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastFromExpressedType()
MlirType mlirQuantizedTypeCastFromExpressedType (MlirType type, MlirType candidate)
Casts from a type based on the expressed type of the given type to a corresponding type based on the given type.
Returns a null type if the cast is not valid.
Definition at line 92 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastFromStorageType()
MlirType mlirQuantizedTypeCastFromStorageType (MlirType type, MlirType candidate)
Casts from a type based on the storage type of the given type to a corresponding type based on the given type.
Returns a null type if the cast is not valid.
Definition at line 81 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastToExpressedType()
MlirType mlirQuantizedTypeCastToExpressedType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the expressed type.
Returns a null type if the cast is not valid.
Definition at line 98 of file Quant.cpp.
References mlir::quant::QuantizedType::castToExpressedType(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeCastToStorageType()
MlirType mlirQuantizedTypeCastToStorageType (MlirType type)
Casts from a type based on a quantized type to a corresponding typed based on the storage type.
Returns a null type if the cast is not valid.
Definition at line 87 of file Quant.cpp.
References mlir::quant::QuantizedType::castToStorageType(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetDefaultMaximumForInteger()
int64_t mlirQuantizedTypeGetDefaultMaximumForInteger (bool isSigned, unsigned integralWidth)
Returns the maximum possible value stored by a quantized type.
Definition at line 37 of file Quant.cpp.
References mlir::quant::QuantizedType::getDefaultMaximumForInteger().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetDefaultMinimumForInteger()
int64_t mlirQuantizedTypeGetDefaultMinimumForInteger (bool isSigned, unsigned integralWidth)
Returns the minimum possible value stored by a quantized type.
Definition at line 31 of file Quant.cpp.
References mlir::quant::QuantizedType::getDefaultMinimumForInteger().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetExpressedType()
MlirType mlirQuantizedTypeGetExpressedType (MlirType type)
Gets the original type approximated by the given quantized type.
Definition at line 43 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetFlags()
unsigned mlirQuantizedTypeGetFlags (MlirType type)
Gets the flags associated with the given quantized type.
Definition at line 47 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetQuantizedElementType()
MlirType mlirQuantizedTypeGetQuantizedElementType (MlirType type)
Returns the element type of the given quantized type as another quantized type.
Definition at line 77 of file Quant.cpp.
References mlir::quant::QuantizedType::getQuantizedElementType(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetSignedFlag()
unsigned mlirQuantizedTypeGetSignedFlag (void)
Returns the bit flag used to indicate signedness of a quantized type.
Definition at line 27 of file Quant.cpp.
References mlir::quant::QuantizationFlags::Signed.
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageType()
MlirType mlirQuantizedTypeGetStorageType (MlirType type)
Returns the underlying type used to store the values.
Definition at line 55 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageTypeIntegralWidth()
unsigned mlirQuantizedTypeGetStorageTypeIntegralWidth (MlirType type)
Returns the integral bitwidth that the storage type of the given quantized type can represent exactly.
Definition at line 67 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageTypeMax()
int64_t mlirQuantizedTypeGetStorageTypeMax (MlirType type)
Returns the maximum value that the storage type of the given quantized type can take.
Definition at line 63 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeGetStorageTypeMin()
int64_t mlirQuantizedTypeGetStorageTypeMin (MlirType type)
Returns the minimum value that the storage type of the given quantized type can take.
Definition at line 59 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeIsCompatibleExpressedType()
bool mlirQuantizedTypeIsCompatibleExpressedType (MlirType type, MlirType candidate)
Returns true if the candidate type is compatible with the given quantized type.
Definition at line 71 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirQuantizedTypeIsSigned()
bool mlirQuantizedTypeIsSigned (MlirType type)
Returns true if the given type is signed, false otherwise.
Definition at line 51 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAAnyQuantizedType()
bool mlirTypeIsAAnyQuantizedType (MlirType type)
Returns true if the given type is an AnyQuantizedType.
Definition at line 112 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsACalibratedQuantizedType()
bool mlirTypeIsACalibratedQuantizedType (MlirType type)
Returns true if the given type is a CalibratedQuantizedType.
Definition at line 257 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAQuantizedType()
bool mlirTypeIsAQuantizedType (MlirType type)
Returns true if the given type is a quantization dialect type.
Definition at line 23 of file Quant.cpp.
References mlirTypeIsAQuantizedType(), and unwrap().
Referenced by mlirTypeIsAQuantizedType(), and populateDialectQuantSubmodule().
mlirTypeIsAUniformQuantizedPerAxisType()
bool mlirTypeIsAUniformQuantizedPerAxisType (MlirType type)
Returns true if the given type is a UniformQuantizedPerAxisType.
Definition at line 157 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAUniformQuantizedSubChannelType()
bool mlirTypeIsAUniformQuantizedSubChannelType (MlirType type)
Returns true if the given type is a UniformQuantizedSubChannel.
Definition at line 202 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirTypeIsAUniformQuantizedType()
bool mlirTypeIsAUniformQuantizedType (MlirType type)
Returns true if the given type is a UniformQuantizedType.
Definition at line 128 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGet()
MlirType mlirUniformQuantizedPerAxisTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, intptr_t nDims, double * scales, int64_t * zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedPerAxisType with the given parameters in the same context as storageType and returns it.
scales and zeroPoints point to nDims number of elements. The instance is owned by the context.
Definition at line 161 of file Quant.cpp.
References mlir::quant::UniformQuantizedPerAxisType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetNumDims()
intptr_t mlirUniformQuantizedPerAxisTypeGetNumDims (MlirType type)
Returns the number of axes in the given quantized per-axis type.
Definition at line 172 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetQuantizedDimension()
int32_t mlirUniformQuantizedPerAxisTypeGetQuantizedDimension (MlirType type)
Returns the index of the quantized dimension in the given quantized per-axis type.
Definition at line 189 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetScale()
double mlirUniformQuantizedPerAxisTypeGetScale (MlirType type, intptr_t pos)
Returns pos-th scale of the given quantized per-axis type.
Definition at line 178 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeGetZeroPoint()
int64_t mlirUniformQuantizedPerAxisTypeGetZeroPoint (MlirType type, intptr_t pos)
Returns pos-th zero point of the given quantized per-axis type.
Definition at line 183 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedPerAxisTypeIsFixedPoint()
bool mlirUniformQuantizedPerAxisTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized per-axis type is fixed-point.
Definition at line 194 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGet()
MlirType mlirUniformQuantizedSubChannelTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, MlirAttribute scalesAttr, MlirAttribute zeroPointsAttr, intptr_t blockSizeInfoLength, int32_t * quantizedDimensions, int64_t * blockSizes, int64_t storageTypeMin, int64_t storageTypeMax)
Creates a UniformQuantizedSubChannelType with the given parameters.
The type is owned by the context. scalesAttr and zeroPointsAttr must be DenseElementsAttrs. quantizedDimensions and blockSizes point to blockSizeInfoLength number of elements, describing respectively the quantization axis and corresponding block size.
Definition at line 206 of file Quant.cpp.
References mlir::quant::UniformQuantizedSubChannelType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetBlockSize()
int64_t mlirUniformQuantizedSubChannelTypeGetBlockSize (MlirType type, intptr_t pos)
Returns the block size at the given position.
Definition at line 237 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetNumBlockSizes()
intptr_t mlirUniformQuantizedSubChannelTypeGetNumBlockSizes (MlirType type)
Returns the number of block sizes provided in type.
Definition at line 225 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetQuantizedDimension()
int32_t mlirUniformQuantizedSubChannelTypeGetQuantizedDimension (MlirType type, intptr_t pos)
Returns the quantized dimension at the given position.
Definition at line 231 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetScales()
MlirAttribute mlirUniformQuantizedSubChannelTypeGetScales (MlirType type)
Returns the scales of the quantized type.
Definition at line 243 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedSubChannelTypeGetZeroPoints()
MlirAttribute mlirUniformQuantizedSubChannelTypeGetZeroPoints (MlirType type)
Returns the zero-points of the quantized type.
Definition at line 248 of file Quant.cpp.
References unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeGet()
MlirType mlirUniformQuantizedTypeGet (unsigned flags, MlirType storageType, MlirType expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
Creates an instance of UniformQuantizedType with the given parameters in the same context as storageType and returns it.
The instance is owned by the context.
Definition at line 132 of file Quant.cpp.
References mlir::quant::UniformQuantizedType::get(), unwrap(), and wrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeGetScale()
double mlirUniformQuantizedTypeGetScale (MlirType type)
Returns the scale of the given uniform quantized type.
Definition at line 141 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeGetZeroPoint()
int64_t mlirUniformQuantizedTypeGetZeroPoint (MlirType type)
Returns the zero point of the given uniform quantized type.
Definition at line 145 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().
mlirUniformQuantizedTypeIsFixedPoint()
bool mlirUniformQuantizedTypeIsFixedPoint (MlirType type)
Returns true if the given uniform quantized type is fixed-point.
Definition at line 149 of file Quant.cpp.
References unwrap().
Referenced by populateDialectQuantSubmodule().