MLIR: include/mlir-c/RegisterEverything.h File Reference
RegisterEverything.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_CAPI_EXPORTED void mlirRegisterAllDialects (MlirDialectRegistry registry)
Appends all upstream dialects and extensions to the dialect registry.
MLIR_CAPI_EXPORTED void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
MLIR_CAPI_EXPORTED void mlirRegisterAllPasses (void)
Register all compiler passes of MLIR.
Function Documentation
mlirRegisterAllDialects()
MLIR_CAPI_EXPORTED void mlirRegisterAllDialects (MlirDialectRegistry registry)
Appends all upstream dialects and extensions to the dialect registry.
Definition at line 20 of file RegisterEverything.cpp.
References mlir::registerAllDialects(), mlir::registerAllExtensions(), and unwrap().
Referenced by NB_MODULE().
mlirRegisterAllLLVMTranslations()
MLIR_CAPI_EXPORTED void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
Definition at line 25 of file RegisterEverything.cpp.
References mlir::registerAllToLLVMIRTranslations(), and unwrap().
Referenced by NB_MODULE().
mlirRegisterAllPasses()
MLIR_CAPI_EXPORTED void mlirRegisterAllPasses (void)
Register all compiler passes of MLIR.
Definition at line 32 of file RegisterEverything.cpp.
References mlir::registerAllPasses().
Referenced by NB_MODULE().