MLIR: lib/Dialect/MemRef/Transforms/ResolveShapedTypeResultDims.cpp File Reference
ResolveShapedTypeResultDims.cpp File Reference
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h.inc"
Macros
#define GEN_PASS_CLASSES
Functions
static Value getResultDimFromShapeInterface (OpBuilder &builder, OpResult result, int64_t dimIndex)
Helper method to get the Value that is the shape of the resultIdx-th result at dimension dimIndex from the ShapedTypeOpInterface.
Macro Definition Documentation
GEN_PASS_CLASSES
#define GEN_PASS_CLASSES
Definition at line 104 of file ResolveShapedTypeResultDims.cpp.
Function Documentation
getResultDimFromShapeInterface()
static Value getResultDimFromShapeInterface (OpBuilder & builder, OpResult result, int64_t dimIndex) static
Helper method to get the Value that is the shape of the resultIdx-th result at dimension dimIndex from the ShapedTypeOpInterface.
TODO(ravishankarm): This is better put as a interface utility method somewhere, but that would imply the interface will depend on the tensor dialect. Ideally maybe a utility method in the tensor dialect.
Definition at line 29 of file ResolveShapedTypeResultDims.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), loc, mlir::RewriterBase::replaceOp(), rewriter, mlir::succeeded(), and mlir::success().