MLIR: lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp File Reference
ROCDLDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/GPU/IR/CompilationInterfaces.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/LLVMIR/ROCDLOpsDialect.cpp.inc"
#include "mlir/Dialect/LLVMIR/ROCDLOpsEnums.cpp.inc"
#include "mlir/Dialect/LLVMIR/ROCDLOps.cpp.inc"
#include "mlir/Dialect/LLVMIR/ROCDLOpsAttributes.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_OP_CLASSES
#define GET_ATTRDEF_CLASSES
Functions
template<typename EnumAttrT, typename EnumT>
static ParseResult parseCachePolicyEnum (OpAsmParser &parser, Attribute &cachePolicy)
static ParseResult parseCachePolicy (OpAsmParser &parser, Attribute &cachePolicy)
template<typename EnumAttrT>
static void printCachePolicyEnum (OpAsmPrinter &printer, EnumAttrT cachePolicy, StringRef family)
static void printCachePolicy (OpAsmPrinter &printer, Operation *, Attribute cachePolicy)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 226 of file ROCDLDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 223 of file ROCDLDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseCachePolicy()
ParseResult parseCachePolicy (OpAsmParser & parser, Attribute & cachePolicy) static
Definition at line 128 of file ROCDLDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::OptionalParseResult::has_value(), parseCachePolicyEnum(), mlir::AsmParser::parseOptionalInteger(), mlir::AsmParser::parseOptionalKeyword(), and success().
parseCachePolicyEnum()
template<typename EnumAttrT, typename EnumT> ParseResult parseCachePolicyEnum (OpAsmParser & parser, Attribute & cachePolicy) static
Definition at line 115 of file ROCDLDialect.cpp.
References mlir::AsmParser::getContext(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and success().
Referenced by parseCachePolicy().
printCachePolicy()
void printCachePolicy (OpAsmPrinter & printer, Operation * , Attribute cachePolicy) static
Definition at line 169 of file ROCDLDialect.cpp.
References printCachePolicyEnum().
printCachePolicyEnum()
template<typename EnumAttrT> void printCachePolicyEnum (OpAsmPrinter & printer, EnumAttrT cachePolicy, StringRef family) static
Definition at line 164 of file ROCDLDialect.cpp.
Referenced by printCachePolicy().