MLIR: lib/Target/LLVMIR/Dialect/ROCDL/ROCDLToLLVMIRTranslation.cpp File Reference
ROCDLToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/ROCDL/ROCDLToLLVMIRTranslation.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "mlir/Dialect/LLVMIR/ROCDLConversions.inc"
Functions
static llvm::Value * createDeviceFunctionCall (llvm::IRBuilderBase &builder, StringRef fn_name, int parameter)
Function Documentation
createDeviceFunctionCall()
static llvm::Value* createDeviceFunctionCall (llvm::IRBuilderBase & builder, StringRef fn_name, int parameter) static
Definition at line 30 of file ROCDLToLLVMIRTranslation.cpp.
References mlir::failure(), mlir::LLVMTranslationDialectInterface::LLVMTranslationDialectInterface(), mlir::LLVM::ModuleTranslation::lookupFunction(), op, and mlir::success().