MLIR: lib/ExecutionEngine/RunnerUtils.cpp File Reference
RunnerUtils.cpp File Reference
#include "mlir/ExecutionEngine/RunnerUtils.h"
#include <chrono>
Functions
void _mlir_ciface_printMemrefShapeI8 (UnrankedMemRefType< int8_t > *M)
void _mlir_ciface_printMemrefShapeI32 (UnrankedMemRefType< int32_t > *M)
void _mlir_ciface_printMemrefShapeI64 (UnrankedMemRefType< int64_t > *M)
void _mlir_ciface_printMemrefShapeF32 (UnrankedMemRefType< float > *M)
void _mlir_ciface_printMemrefShapeF64 (UnrankedMemRefType< double > *M)
void _mlir_ciface_printMemrefShapeInd (UnrankedMemRefType< impl::index_type > *M)
void _mlir_ciface_printMemrefShapeC32 (UnrankedMemRefType< impl::complex32 > *M)
void _mlir_ciface_printMemrefShapeC64 (UnrankedMemRefType< impl::complex64 > *M)
void _mlir_ciface_printMemrefVector4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > *M)
void _mlir_ciface_printMemrefI8 (UnrankedMemRefType< int8_t > *M)
void _mlir_ciface_printMemrefI16 (UnrankedMemRefType< int16_t > *M)
void _mlir_ciface_printMemrefI32 (UnrankedMemRefType< int32_t > *M)
void _mlir_ciface_printMemrefI64 (UnrankedMemRefType< int64_t > *M)
void _mlir_ciface_printMemrefF16 (UnrankedMemRefType< f16 > *M)
void _mlir_ciface_printMemrefBF16 (UnrankedMemRefType< bf16 > *M)
void _mlir_ciface_printMemrefF32 (UnrankedMemRefType< float > *M)
void _mlir_ciface_printMemrefF64 (UnrankedMemRefType< double > *M)
void _mlir_ciface_printMemrefInd (UnrankedMemRefType< impl::index_type > *M)
void _mlir_ciface_printMemrefC32 (UnrankedMemRefType< impl::complex32 > *M)
void _mlir_ciface_printMemrefC64 (UnrankedMemRefType< impl::complex64 > *M)
int64_t _mlir_ciface_nanoTime ()
void printMemrefI32 (int64_t rank, void *ptr)
void printMemrefI64 (int64_t rank, void *ptr)
void printMemrefF32 (int64_t rank, void *ptr)
void printMemrefF64 (int64_t rank, void *ptr)
void printMemrefInd (int64_t rank, void *ptr)
void printMemrefC32 (int64_t rank, void *ptr)
void printMemrefC64 (int64_t rank, void *ptr)
void _mlir_ciface_printMemref0dF32 (StridedMemRefType< float, 0 > *M)
void _mlir_ciface_printMemref1dF32 (StridedMemRefType< float, 1 > *M)
void _mlir_ciface_printMemref2dF32 (StridedMemRefType< float, 2 > *M)
void _mlir_ciface_printMemref3dF32 (StridedMemRefType< float, 3 > *M)
void _mlir_ciface_printMemref4dF32 (StridedMemRefType< float, 4 > *M)
void _mlir_ciface_printMemref1dI8 (StridedMemRefType< int8_t, 1 > *M)
void _mlir_ciface_printMemref1dI32 (StridedMemRefType< int32_t, 1 > *M)
void _mlir_ciface_printMemref1dI64 (StridedMemRefType< int64_t, 1 > *M)
void _mlir_ciface_printMemref1dF64 (StridedMemRefType< double, 1 > *M)
void _mlir_ciface_printMemref1dInd (StridedMemRefType< impl::index_type, 1 > *M)
void _mlir_ciface_printMemref1dC32 (StridedMemRefType< impl::complex32, 1 > *M)
void _mlir_ciface_printMemref1dC64 (StridedMemRefType< impl::complex64, 1 > *M)
int64_t _mlir_ciface_verifyMemRefI8 (UnrankedMemRefType< int8_t > *actual, UnrankedMemRefType< int8_t > *expected)
int64_t _mlir_ciface_verifyMemRefI16 (UnrankedMemRefType< int16_t > *actual, UnrankedMemRefType< int16_t > *expected)
int64_t _mlir_ciface_verifyMemRefI32 (UnrankedMemRefType< int32_t > *actual, UnrankedMemRefType< int32_t > *expected)
int64_t _mlir_ciface_verifyMemRefI64 (UnrankedMemRefType< int64_t > *actual, UnrankedMemRefType< int64_t > *expected)
int64_t _mlir_ciface_verifyMemRefF16 (UnrankedMemRefType< f16 > *actual, UnrankedMemRefType< f16 > *expected)
int64_t _mlir_ciface_verifyMemRefBF16 (UnrankedMemRefType< bf16 > *actual, UnrankedMemRefType< bf16 > *expected)
int64_t _mlir_ciface_verifyMemRefF32 (UnrankedMemRefType< float > *actual, UnrankedMemRefType< float > *expected)
int64_t _mlir_ciface_verifyMemRefF64 (UnrankedMemRefType< double > *actual, UnrankedMemRefType< double > *expected)
int64_t _mlir_ciface_verifyMemRefInd (UnrankedMemRefType< impl::index_type > *actual, UnrankedMemRefType< impl::index_type > *expected)
int64_t _mlir_ciface_verifyMemRefC32 (UnrankedMemRefType< impl::complex32 > *actual, UnrankedMemRefType< impl::complex32 > *expected)
int64_t _mlir_ciface_verifyMemRefC64 (UnrankedMemRefType< impl::complex64 > *actual, UnrankedMemRefType< impl::complex64 > *expected)
int64_t verifyMemRefI32 (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefF32 (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefF64 (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefInd (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefC32 (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefC64 (int64_t rank, void *actualPtr, void *expectedPtr)
Function Documentation
_mlir_ciface_nanoTime()
int64_t _mlir_ciface_nanoTime ()
Definition at line 127 of file RunnerUtils.cpp.
_mlir_ciface_printMemref0dF32()
void _mlir_ciface_printMemref0dF32 (StridedMemRefType< float, 0 > * M)
Definition at line 173 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dC32()
void _mlir_ciface_printMemref1dC32 (StridedMemRefType< impl::complex32, 1 > * M)
Definition at line 213 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dC64()
void _mlir_ciface_printMemref1dC64 (StridedMemRefType< impl::complex64, 1 > * M)
Definition at line 218 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dF32()
void _mlir_ciface_printMemref1dF32 (StridedMemRefType< float, 1 > * M)
Definition at line 176 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dF64()
void _mlir_ciface_printMemref1dF64 (StridedMemRefType< double, 1 > * M)
Definition at line 203 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dI32()
void _mlir_ciface_printMemref1dI32 (StridedMemRefType< int32_t, 1 > * M)
Definition at line 194 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dI64()
void _mlir_ciface_printMemref1dI64 (StridedMemRefType< int64_t, 1 > * M)
Definition at line 199 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dI8()
void _mlir_ciface_printMemref1dI8 (StridedMemRefType< int8_t, 1 > * M)
Definition at line 189 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dInd()
void _mlir_ciface_printMemref1dInd (StridedMemRefType< impl::index_type, 1 > * M)
Definition at line 208 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref2dF32()
void _mlir_ciface_printMemref2dF32 (StridedMemRefType< float, 2 > * M)
Definition at line 179 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref3dF32()
void _mlir_ciface_printMemref3dF32 (StridedMemRefType< float, 3 > * M)
Definition at line 182 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref4dF32()
void _mlir_ciface_printMemref4dF32 (StridedMemRefType< float, 4 > * M)
Definition at line 185 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefBF16()
void _mlir_ciface_printMemrefBF16 (UnrankedMemRefType< bf16 > * M)
Definition at line 100 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefC32()
void _mlir_ciface_printMemrefC32 (UnrankedMemRefType< impl::complex32 > * M)
Definition at line 118 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefC32().
_mlir_ciface_printMemrefC64()
void _mlir_ciface_printMemrefC64 (UnrankedMemRefType< impl::complex64 > * M)
Definition at line 123 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefC64().
_mlir_ciface_printMemrefF16()
void _mlir_ciface_printMemrefF16 (UnrankedMemRefType< f16 > * M)
Definition at line 96 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefF32()
void _mlir_ciface_printMemrefF32 (UnrankedMemRefType< float > * M)
Definition at line 104 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefF32().
_mlir_ciface_printMemrefF64()
void _mlir_ciface_printMemrefF64 (UnrankedMemRefType< double > * M)
Definition at line 108 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefF64().
_mlir_ciface_printMemrefI16()
void _mlir_ciface_printMemrefI16 (UnrankedMemRefType< int16_t > * M)
Definition at line 84 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefI32()
void _mlir_ciface_printMemrefI32 (UnrankedMemRefType< int32_t > * M)
Definition at line 88 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefI32().
_mlir_ciface_printMemrefI64()
void _mlir_ciface_printMemrefI64 (UnrankedMemRefType< int64_t > * M)
Definition at line 92 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefI64().
_mlir_ciface_printMemrefI8()
void _mlir_ciface_printMemrefI8 (UnrankedMemRefType< int8_t > * M)
Definition at line 80 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefInd()
void _mlir_ciface_printMemrefInd (UnrankedMemRefType< impl::index_type > * M)
Definition at line 113 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefInd().
_mlir_ciface_printMemrefShapeC32()
void _mlir_ciface_printMemrefShapeC32 (UnrankedMemRefType< impl::complex32 > * M)
Definition at line 62 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeC64()
void _mlir_ciface_printMemrefShapeC64 (UnrankedMemRefType< impl::complex64 > * M)
Definition at line 69 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeF32()
void _mlir_ciface_printMemrefShapeF32 (UnrankedMemRefType< float > * M)
Definition at line 41 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeF64()
void _mlir_ciface_printMemrefShapeF64 (UnrankedMemRefType< double > * M)
Definition at line 48 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeI32()
void _mlir_ciface_printMemrefShapeI32 (UnrankedMemRefType< int32_t > * M)
Definition at line 28 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeI64()
void _mlir_ciface_printMemrefShapeI64 (UnrankedMemRefType< int64_t > * M)
Definition at line 35 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeI8()
void _mlir_ciface_printMemrefShapeI8 (UnrankedMemRefType< int8_t > * M)
Definition at line 21 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeInd()
void _mlir_ciface_printMemrefShapeInd (UnrankedMemRefType< impl::index_type > * M)
Definition at line 55 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefVector4x4xf32()
void _mlir_ciface_printMemrefVector4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > * M)
Definition at line 75 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_verifyMemRefBF16()
int64_t _mlir_ciface_verifyMemRefBF16 (UnrankedMemRefType< bf16 > * actual, UnrankedMemRefType< bf16 > * expected)
Definition at line 253 of file RunnerUtils.cpp.
References impl::verifyMemRef().
_mlir_ciface_verifyMemRefC32()
int64_t _mlir_ciface_verifyMemRefC32 (UnrankedMemRefType< impl::complex32 > * actual, UnrankedMemRefType< impl::complex32 > * expected)
Definition at line 277 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefC32().
_mlir_ciface_verifyMemRefC64()
int64_t _mlir_ciface_verifyMemRefC64 (UnrankedMemRefType< impl::complex64 > * actual, UnrankedMemRefType< impl::complex64 > * expected)
Definition at line 283 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefC64().
_mlir_ciface_verifyMemRefF16()
int64_t _mlir_ciface_verifyMemRefF16 (UnrankedMemRefType< f16 > * actual, UnrankedMemRefType< f16 > * expected)
Definition at line 247 of file RunnerUtils.cpp.
References impl::verifyMemRef().
_mlir_ciface_verifyMemRefF32()
int64_t _mlir_ciface_verifyMemRefF32 (UnrankedMemRefType< float > * actual, UnrankedMemRefType< float > * expected)
Definition at line 259 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefF32().
_mlir_ciface_verifyMemRefF64()
int64_t _mlir_ciface_verifyMemRefF64 (UnrankedMemRefType< double > * actual, UnrankedMemRefType< double > * expected)
Definition at line 265 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefF64().
_mlir_ciface_verifyMemRefI16()
int64_t _mlir_ciface_verifyMemRefI16 (UnrankedMemRefType< int16_t > * actual, UnrankedMemRefType< int16_t > * expected)
Definition at line 229 of file RunnerUtils.cpp.
References impl::verifyMemRef().
_mlir_ciface_verifyMemRefI32()
int64_t _mlir_ciface_verifyMemRefI32 (UnrankedMemRefType< int32_t > * actual, UnrankedMemRefType< int32_t > * expected)
Definition at line 235 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefI32().
_mlir_ciface_verifyMemRefI64()
int64_t _mlir_ciface_verifyMemRefI64 (UnrankedMemRefType< int64_t > * actual, UnrankedMemRefType< int64_t > * expected)
Definition at line 241 of file RunnerUtils.cpp.
References impl::verifyMemRef().
_mlir_ciface_verifyMemRefI8()
int64_t _mlir_ciface_verifyMemRefI8 (UnrankedMemRefType< int8_t > * actual, UnrankedMemRefType< int8_t > * expected)
Definition at line 223 of file RunnerUtils.cpp.
References impl::verifyMemRef().
_mlir_ciface_verifyMemRefInd()
int64_t _mlir_ciface_verifyMemRefInd (UnrankedMemRefType< impl::index_type > * actual, UnrankedMemRefType< impl::index_type > * expected)
Definition at line 271 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefInd().
printMemrefC32()
void printMemrefC32 (int64_t rank, void * ptr)
Definition at line 163 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefC32().
printMemrefC64()
void printMemrefC64 (int64_t rank, void * ptr)
Definition at line 168 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefC64().
printMemrefF32()
void printMemrefF32 (int64_t rank, void * ptr)
Definition at line 145 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefF32().
printMemrefF64()
void printMemrefF64 (int64_t rank, void * ptr)
Definition at line 150 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefF64().
printMemrefI32()
void printMemrefI32 (int64_t rank, void * ptr)
Definition at line 135 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefI32().
printMemrefI64()
void printMemrefI64 (int64_t rank, void * ptr)
Definition at line 140 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefI64().
printMemrefInd()
void printMemrefInd (int64_t rank, void * ptr)
Definition at line 158 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefInd().
verifyMemRefC32()
int64_t verifyMemRefC32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 316 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefC32().
verifyMemRefC64()
int64_t verifyMemRefC64 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 323 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefC64().
verifyMemRefF32()
int64_t verifyMemRefF32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 295 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefF32().
verifyMemRefF64()
int64_t verifyMemRefF64 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 302 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefF64().
verifyMemRefI32()
int64_t verifyMemRefI32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 288 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefI32().
verifyMemRefInd()
int64_t verifyMemRefInd (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 309 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefInd().