MLIR: lib/Transforms/SCCP.cpp File Reference
SCCP.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/DataFlowAnalysis.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Dialect.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/Passes.h"
Functions
static LogicalResult replaceWithConstant (SCCPAnalysis &analysis, OpBuilder &builder, OperationFolder &folder, Value value)
Replace the given value with a constant if the corresponding lattice represents a constant.
static void rewrite (SCCPAnalysis &analysis, MLIRContext *context, MutableArrayRef< Region > initialRegions)
Rewrite the given regions using the computing analysis.
Function Documentation
replaceWithConstant()
static LogicalResult replaceWithConstant (SCCPAnalysis & analysis, OpBuilder & builder, OperationFolder & folder, Value value) static
Replace the given value with a constant if the corresponding lattice represents a constant.
Returns success if the value was replaced, failure otherwise.
Definition at line 164 of file SCCP.cpp.
References mlir::failure(), mlir::Value::getLoc(), mlir::OperationFolder::getOrCreateConstant(), mlir::Value::getType(), mlir::LatticeElement< ValueT >::getValue(), mlir::Value::replaceAllUsesWith(), and mlir::success().
Referenced by rewrite().
rewrite()
static void rewrite (SCCPAnalysis & analysis, MLIRContext * context, MutableArrayRef< Region > initialRegions) static
Rewrite the given regions using the computing analysis.
This replaces the uses of all values that have been computed to be constant, and erases as many newly dead operations.
Definition at line 189 of file SCCP.cpp.
References mlir::Operation::erase(), mlir::Block::getArguments(), mlir::Operation::getContext(), mlir::Operation::getNumResults(), mlir::Operation::getRegions(), mlir::Operation::getResults(), op, replaceWithConstant(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), mlir::succeeded(), mlir::Operation::use_empty(), and mlir::wouldOpBeTriviallyDead().
Referenced by getBufferizedFunctionType(), mlir::detail::PDLByteCode::getPatterns(), mlir::ConvertOpToLLVMPattern< ScalableLoadOp >::matchAndRewrite(), mlir::RewritePattern::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >::matchAndRewrite(), mlir::detail::OpOrInterfaceConversionPatternBase< async::YieldOp >::matchAndRewrite(), mlir::ConvertOpToLLVMPattern< ScalableLoadOp >::rewrite(), mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >::rewrite(), mlir::detail::OpOrInterfaceConversionPatternBase< async::YieldOp >::rewrite(), and mlir::RewritePattern::~RewritePattern().