MLIR: lib/Interfaces/SideEffectInterfaces.cpp File Reference
SideEffectInterfaces.cpp File Reference
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/IR/SymbolTable.h"
#include <utility>
#include "mlir/Interfaces/SideEffectInterfaces.cpp.inc"
Functions
static bool wouldOpBeTriviallyDeadImpl (Operation *rootOp)
Internal implementation of mlir::wouldOpBeTriviallyDead that also considers terminator operations as dead if they have no side effects.
template bool mlir::hasSingleEffect< MemoryEffects::Allocate > (Operation *)
template bool mlir::hasSingleEffect< MemoryEffects::Free > (Operation *)
template bool mlir::hasSingleEffect< MemoryEffects::Read > (Operation *)
template bool mlir::hasSingleEffect< MemoryEffects::Write > (Operation *)
template bool mlir::hasSingleEffect< MemoryEffects::Allocate > (Operation *, Value value)
template bool mlir::hasSingleEffect< MemoryEffects::Free > (Operation *, Value value)
template bool mlir::hasSingleEffect< MemoryEffects::Read > (Operation *, Value value)
template bool mlir::hasSingleEffect< MemoryEffects::Write > (Operation *, Value value)
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Allocate > (Operation *, OpOperand *)
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Free > (Operation *, OpOperand *)
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Read > (Operation *, OpOperand *)
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Write > (Operation *, OpOperand *)
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Allocate > (Operation *, OpResult)
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Free > (Operation *, OpResult)
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Read > (Operation *, OpResult)
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Write > (Operation *, OpResult)
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Allocate > (Operation *, BlockArgument)
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Free > (Operation *, BlockArgument)
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Read > (Operation *, BlockArgument)
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Write > (Operation *, BlockArgument)
template bool mlir::hasEffect< MemoryEffects::Allocate > (Operation *)
template bool mlir::hasEffect< MemoryEffects::Free > (Operation *)
template bool mlir::hasEffect< MemoryEffects::Read > (Operation *)
template bool mlir::hasEffect< MemoryEffects::Write > (Operation *)
template bool mlir::hasEffect< MemoryEffects::Write, MemoryEffects::Free > (Operation *)
template bool mlir::hasEffect< MemoryEffects::Allocate > (Operation *, Value value)
template bool mlir::hasEffect< MemoryEffects::Free > (Operation *, Value value)
template bool mlir::hasEffect< MemoryEffects::Read > (Operation *, Value value)
template bool mlir::hasEffect< MemoryEffects::Write > (Operation *, Value value)
template bool mlir::hasEffect< MemoryEffects::Write, MemoryEffects::Free > (Operation *, Value value)
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Allocate > (Operation *, OpOperand *)
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Free > (Operation *, OpOperand *)
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Read > (Operation *, OpOperand *)
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Write > (Operation *, OpOperand *)
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Write, MemoryEffects::Free > (Operation *, OpOperand *)
template bool mlir::hasEffect< OpResult, MemoryEffects::Allocate > (Operation *, OpResult)
template bool mlir::hasEffect< OpResult, MemoryEffects::Free > (Operation *, OpResult)
template bool mlir::hasEffect< OpResult, MemoryEffects::Read > (Operation *, OpResult)
template bool mlir::hasEffect< OpResult, MemoryEffects::Write > (Operation *, OpResult)
template bool mlir::hasEffect< OpResult, MemoryEffects::Write, MemoryEffects::Free > (Operation *, OpResult)
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Allocate > (Operation *, BlockArgument)
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Free > (Operation *, BlockArgument)
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Read > (Operation *, BlockArgument)
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Write > (Operation *, BlockArgument)
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Write, MemoryEffects::Free > (Operation *, BlockArgument)
Function Documentation
mlir::hasEffect< BlockArgument, MemoryEffects::Allocate >()
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Allocate > (Operation * , BlockArgument)
mlir::hasEffect< BlockArgument, MemoryEffects::Free >()
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Free > (Operation * , BlockArgument)
mlir::hasEffect< BlockArgument, MemoryEffects::Read >()
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Read > (Operation * , BlockArgument)
mlir::hasEffect< BlockArgument, MemoryEffects::Write >()
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Write > (Operation * , BlockArgument)
mlir::hasEffect< BlockArgument, MemoryEffects::Write, MemoryEffects::Free >()
template bool mlir::hasEffect< BlockArgument, MemoryEffects::Write, MemoryEffects::Free > (Operation * , BlockArgument)
mlir::hasEffect< MemoryEffects::Allocate >() [1/2]
template bool mlir::hasEffect< MemoryEffects::Allocate > (Operation *)
mlir::hasEffect< MemoryEffects::Allocate >() [2/2]
template bool mlir::hasEffect< MemoryEffects::Allocate > (Operation * , Value value)
mlir::hasEffect< MemoryEffects::Free >() [1/2]
template bool mlir::hasEffect< MemoryEffects::Free > (Operation *)
mlir::hasEffect< MemoryEffects::Free >() [2/2]
template bool mlir::hasEffect< MemoryEffects::Free > (Operation * , Value value)
mlir::hasEffect< MemoryEffects::Read >() [1/2]
template bool mlir::hasEffect< MemoryEffects::Read > (Operation *)
mlir::hasEffect< MemoryEffects::Read >() [2/2]
template bool mlir::hasEffect< MemoryEffects::Read > (Operation * , Value value)
mlir::hasEffect< MemoryEffects::Write >() [1/2]
template bool mlir::hasEffect< MemoryEffects::Write > (Operation *)
mlir::hasEffect< MemoryEffects::Write >() [2/2]
template bool mlir::hasEffect< MemoryEffects::Write > (Operation * , Value value)
mlir::hasEffect< MemoryEffects::Write, MemoryEffects::Free >() [1/2]
template bool mlir::hasEffect< MemoryEffects::Write, MemoryEffects::Free > (Operation *)
mlir::hasEffect< MemoryEffects::Write, MemoryEffects::Free >() [2/2]
template bool mlir::hasEffect< MemoryEffects::Write, MemoryEffects::Free > (Operation * , Value value)
mlir::hasEffect< OpOperand *, MemoryEffects::Allocate >()
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Allocate > (Operation * , OpOperand *)
mlir::hasEffect< OpOperand *, MemoryEffects::Free >()
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Free > (Operation * , OpOperand *)
mlir::hasEffect< OpOperand *, MemoryEffects::Read >()
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Read > (Operation * , OpOperand *)
mlir::hasEffect< OpOperand *, MemoryEffects::Write >()
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Write > (Operation * , OpOperand *)
mlir::hasEffect< OpOperand *, MemoryEffects::Write, MemoryEffects::Free >()
template bool mlir::hasEffect< OpOperand *, MemoryEffects::Write, MemoryEffects::Free > (Operation * , OpOperand *)
mlir::hasEffect< OpResult, MemoryEffects::Allocate >()
template bool mlir::hasEffect< OpResult, MemoryEffects::Allocate > (Operation * , OpResult)
mlir::hasEffect< OpResult, MemoryEffects::Free >()
template bool mlir::hasEffect< OpResult, MemoryEffects::Free > (Operation * , OpResult)
mlir::hasEffect< OpResult, MemoryEffects::Read >()
template bool mlir::hasEffect< OpResult, MemoryEffects::Read > (Operation * , OpResult)
mlir::hasEffect< OpResult, MemoryEffects::Write >()
template bool mlir::hasEffect< OpResult, MemoryEffects::Write > (Operation * , OpResult)
mlir::hasEffect< OpResult, MemoryEffects::Write, MemoryEffects::Free >()
template bool mlir::hasEffect< OpResult, MemoryEffects::Write, MemoryEffects::Free > (Operation * , OpResult)
mlir::hasSingleEffect< BlockArgument, MemoryEffects::Allocate >()
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Allocate > (Operation * , BlockArgument)
mlir::hasSingleEffect< BlockArgument, MemoryEffects::Free >()
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Free > (Operation * , BlockArgument)
mlir::hasSingleEffect< BlockArgument, MemoryEffects::Read >()
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Read > (Operation * , BlockArgument)
mlir::hasSingleEffect< BlockArgument, MemoryEffects::Write >()
template bool mlir::hasSingleEffect< BlockArgument, MemoryEffects::Write > (Operation * , BlockArgument)
mlir::hasSingleEffect< MemoryEffects::Allocate >() [1/2]
template bool mlir::hasSingleEffect< MemoryEffects::Allocate > (Operation *)
mlir::hasSingleEffect< MemoryEffects::Allocate >() [2/2]
template bool mlir::hasSingleEffect< MemoryEffects::Allocate > (Operation * , Value value)
mlir::hasSingleEffect< MemoryEffects::Free >() [1/2]
template bool mlir::hasSingleEffect< MemoryEffects::Free > (Operation *)
mlir::hasSingleEffect< MemoryEffects::Free >() [2/2]
template bool mlir::hasSingleEffect< MemoryEffects::Free > (Operation * , Value value)
mlir::hasSingleEffect< MemoryEffects::Read >() [1/2]
template bool mlir::hasSingleEffect< MemoryEffects::Read > (Operation *)
mlir::hasSingleEffect< MemoryEffects::Read >() [2/2]
template bool mlir::hasSingleEffect< MemoryEffects::Read > (Operation * , Value value)
mlir::hasSingleEffect< MemoryEffects::Write >() [1/2]
template bool mlir::hasSingleEffect< MemoryEffects::Write > (Operation *)
mlir::hasSingleEffect< MemoryEffects::Write >() [2/2]
template bool mlir::hasSingleEffect< MemoryEffects::Write > (Operation * , Value value)
mlir::hasSingleEffect< OpOperand *, MemoryEffects::Allocate >()
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Allocate > (Operation * , OpOperand *)
mlir::hasSingleEffect< OpOperand *, MemoryEffects::Free >()
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Free > (Operation * , OpOperand *)
mlir::hasSingleEffect< OpOperand *, MemoryEffects::Read >()
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Read > (Operation * , OpOperand *)
mlir::hasSingleEffect< OpOperand *, MemoryEffects::Write >()
template bool mlir::hasSingleEffect< OpOperand *, MemoryEffects::Write > (Operation * , OpOperand *)
mlir::hasSingleEffect< OpResult, MemoryEffects::Allocate >()
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Allocate > (Operation * , OpResult)
mlir::hasSingleEffect< OpResult, MemoryEffects::Free >()
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Free > (Operation * , OpResult)
mlir::hasSingleEffect< OpResult, MemoryEffects::Read >()
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Read > (Operation * , OpResult)
mlir::hasSingleEffect< OpResult, MemoryEffects::Write >()
template bool mlir::hasSingleEffect< OpResult, MemoryEffects::Write > (Operation * , OpResult)
wouldOpBeTriviallyDeadImpl()
static bool wouldOpBeTriviallyDeadImpl (Operation * rootOp) static
Internal implementation of mlir::wouldOpBeTriviallyDead that also considers terminator operations as dead if they have no side effects.
This allows for marking region operations as trivially dead without always being conservative of terminators.
Definition at line 43 of file SideEffectInterfaces.cpp.
References mlir::SideEffects::EffectInstance< EffectT >::getEffect(), mlir::Operation::getRegions(), mlir::SideEffects::EffectInstance< EffectT >::getValue(), and mlir::Operation::hasTrait().
Referenced by mlir::wouldOpBeTriviallyDead().