MLIR: lib/Dialect/Linalg/Transforms/SimplifyDepthwiseConv.cpp File Reference
SimplifyDepthwiseConv.cpp File Reference
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/Linalg/Passes.h.inc"
Classes
class mlir::impl::SimplifyDepthwiseConvPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_SIMPLIFYDEPTHWISECONVPASS
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createSimplifyDepthwiseConvPass ()
std::unique_ptr<::mlir::Pass > mlir::createSimplifyDepthwiseConvPass ()
static llvm::SmallVector< int64_t > getIndicesVector (int start, int end)
static LogicalResult matchAndReplaceDepthwiseConv (Operation *operation, Value input, Value kernel, Value iZp, Value kZp, Value init, Attribute stride, Attribute dilation, PatternRewriter &rewriter)
Macro Definition Documentation
GEN_PASS_DEF_SIMPLIFYDEPTHWISECONVPASS
#define GEN_PASS_DEF_SIMPLIFYDEPTHWISECONVPASS
Definition at line 24 of file SimplifyDepthwiseConv.cpp.
Function Documentation
getIndicesVector()
llvm::SmallVector< int64_t > getIndicesVector (int start, int end) static
Definition at line 31 of file SimplifyDepthwiseConv.cpp.
Referenced by matchAndReplaceDepthwiseConv().
matchAndReplaceDepthwiseConv()
LogicalResult matchAndReplaceDepthwiseConv (Operation * operation, Value input, Value kernel, Value iZp, Value kZp, Value init, Attribute stride, Attribute dilation, PatternRewriter & rewriter) static
Definition at line 36 of file SimplifyDepthwiseConv.cpp.
References getIndicesVector(), mlir::Operation::getLoc(), mlir::linalg::getPrunedAttributeList(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::RewriterBase::replaceOpWithNewOp(), result, mlir::Operation::setAttr(), and success().