MLIR: lib/Dialect/X86Vector/Transforms/SinkVectorProducerOps.cpp File Reference
SinkVectorProducerOps.cpp File Reference
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/Dialect/X86Vector/Transforms.h"
#include "mlir/Dialect/X86Vector/X86VectorDialect.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
Classes
struct SinkVectorProducerOps< producerOp >
Sink vector producers forward to reduce live ranges.
Functions
static FailureOr< llvm::SmallVector< Operation * > > getSameBlockUsers (Operation *op)
static bool checkLooping (Operation *op)
Function Documentation
checkLooping()
bool checkLooping (Operation * op) static
Definition at line 48 of file SinkVectorProducerOps.cpp.
References getSameBlockUsers().
Referenced by SinkVectorProducerOps< producerOp >::matchAndRewrite().
getSameBlockUsers()
FailureOr< llvm::SmallVector< Operation * > > getSameBlockUsers (Operation * op) static
Definition at line 26 of file SinkVectorProducerOps.cpp.
References mlir::Operation::getBlock(), mlir::Operation::getResults(), and result.
Referenced by checkLooping(), and SinkVectorProducerOps< producerOp >::matchAndRewrite().