MLIR: lib/Dialect/SparseTensor/Transforms/SparseAssembler.cpp File Reference
SparseAssembler.cpp File Reference
#include "Utils/CodegenUtils.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorStorageLayout.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorType.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static void convTypes (bool &hasAnnotation, TypeRange types, SmallVectorImpl< Type > &convTypes, SmallVectorImpl< Type > *extraTypes, bool directOut)
static void convVals (OpBuilder &builder, Location loc, TypeRange types, ValueRange fromVals, ValueRange extraVals, SmallVectorImpl< Value > &toVals, unsigned extra, bool isIn, bool directOut)
Function Documentation
convTypes()
static void convTypes (bool & hasAnnotation, TypeRange types, SmallVectorImpl< Type > & convTypes, SmallVectorImpl< Type > * extraTypes, bool directOut) static
Definition at line 25 of file SparseAssembler.cpp.
References mlir::sparse_tensor::CrdMemRef, mlir::sparse_tensor::foreachFieldAndTypeInSparseTensor(), mlir::get(), mlir::sparse_tensor::getSparseTensorEncoding(), kind, mlir::sparse_tensor::PosMemRef, and mlir::sparse_tensor::ValMemRef.
convVals()
static void convVals (OpBuilder & builder, Location loc, TypeRange types, ValueRange fromVals, ValueRange extraVals, SmallVectorImpl< Value > & toVals, unsigned extra, bool isIn, bool directOut) static
Definition at line 59 of file SparseAssembler.cpp.
References mlir::sparse_tensor::CrdMemRef, mlir::sparse_tensor::foreachFieldAndTypeInSparseTensor(), mlir::get(), mlir::Builder::getIndexType(), mlir::sparse_tensor::getSparseTensorEncoding(), kind, mlir::sparse_tensor::PosMemRef, and mlir::sparse_tensor::ValMemRef.