MLIR: lib/Dialect/SparseTensor/Transforms/SparseReinterpretMap.cpp File Reference
SparseReinterpretMap.cpp File Reference
#include "Utils/CodegenUtils.h"
#include "Utils/IterationGraphSorter.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorType.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
Functions
static InadmissInfo collectInadmissInfo (AffineMap map, bool isOutput)
static AffineMap genReplaceDimToLvlMap (const InadmissInfo &info, AffineMap idxMap, SmallVector< utils::IteratorType > &itTps)
static std::optional< std::pair< ArrayAttr, ArrayAttr > > translateMap (linalg::GenericOp op, PatternRewriter &rewriter)
static Value genDemap (OpBuilder &builder, SparseTensorEncodingAttr enc, Value val)
static Value genRemap (OpBuilder &builder, SparseTensorEncodingAttr enc, Value val)
static SmallVector< Value > remapValueRange (OpBuilder &rewriter, TypeRange types, ValueRange outs)
Function Documentation
collectInadmissInfo()
static InadmissInfo collectInadmissInfo (AffineMap map, bool isOutput) static
Definition at line 106 of file SparseReinterpretMap.cpp.
References mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResult().
Referenced by translateMap().
genDemap()
static Value genDemap (OpBuilder & builder, SparseTensorEncodingAttr enc, Value val) static
Definition at line 339 of file SparseReinterpretMap.cpp.
References mlir::Value::getLoc().
genRemap()
static Value genRemap (OpBuilder & builder, SparseTensorEncodingAttr enc, Value val) static
Definition at line 346 of file SparseReinterpretMap.cpp.
References mlir::Value::getLoc().
genReplaceDimToLvlMap()
static AffineMap genReplaceDimToLvlMap (const InadmissInfo & info, AffineMap idxMap, SmallVector< utils::IteratorType > & itTps) static
Definition at line 152 of file SparseReinterpretMap.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), and mlir::sparse_tensor::inferLvlToDim().
Referenced by translateMap().
remapValueRange()
static SmallVector<Value> remapValueRange (OpBuilder & rewriter, TypeRange types, ValueRange outs) static
Definition at line 351 of file SparseReinterpretMap.cpp.
translateMap()
static std::optional<std::pair<ArrayAttr, ArrayAttr> > translateMap (linalg::GenericOp op, PatternRewriter & rewriter) static
Definition at line 243 of file SparseReinterpretMap.cpp.
References mlir::changed, collectInadmissInfo(), mlir::AffineMap::compose(), mlir::FloorDiv, genReplaceDimToLvlMap(), mlir::get(), mlir::getAffineBinaryOpExpr(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getArrayAttr(), mlir::AffineMap::getNumDims(), mlir::Mod, mlir::AffineMap::replace(), and mlir::sparse_tensor::tryGetSparseTensorType().