MLIR: lib/Dialect/SparseTensor/Transforms/Utils/SparseTensorDescriptor.cpp File Reference
SparseTensorDescriptor.cpp File Reference
#include "SparseTensorDescriptor.h"
#include "CodegenUtils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static IntegerAttr optionalLevelAttr (MLIRContext *ctx, std::optional< Level > lvl)
Constructs a nullable LevelAttr from the std::optional<Level>.
static std::optional< LogicalResult > convertSparseTensorType (RankedTensorType rtp, SmallVectorImpl< Type > &fields)
static Value materializeTuple (OpBuilder &builder, RankedTensorType tp, ValueRange inputs, Location loc)
Function Documentation
convertSparseTensorType()
static std::optional<LogicalResult> convertSparseTensorType (RankedTensorType rtp, SmallVectorImpl< Type > & fields) static
Definition at line 35 of file SparseTensorDescriptor.cpp.
References mlir::sparse_tensor::foreachFieldAndTypeInSparseTensor(), and mlir::sparse_tensor::SparseTensorType::hasEncoding().
Referenced by mlir::SparseTensorTypeToBufferConverter::SparseTensorTypeToBufferConverter().
materializeTuple()
static Value materializeTuple (OpBuilder & builder, RankedTensorType tp, ValueRange inputs, Location loc) static
Definition at line 58 of file SparseTensorDescriptor.cpp.
References mlir::sparse_tensor::genTuple(), and mlir::sparse_tensor::getSparseTensorEncoding().
Referenced by mlir::SparseTensorTypeToBufferConverter::SparseTensorTypeToBufferConverter().
optionalLevelAttr()
static IntegerAttr optionalLevelAttr (MLIRContext * ctx, std::optional< Level > lvl) static
Constructs a nullable LevelAttr from the std::optional<Level>.
Definition at line 25 of file SparseTensorDescriptor.cpp.
References mlir::get().
Referenced by mlir::sparse_tensor::SparseTensorSpecifier::getSpecifierField(), and mlir::sparse_tensor::SparseTensorSpecifier::setSpecifierField().