MLIR: lib/Dialect/SparseTensor/Transforms/SparseIterationToScf.cpp File Reference
SparseIterationToScf.cpp File Reference
#include "Utils/CodegenUtils.h"
#include "Utils/LoopEmitter.h"
#include "Utils/SparseTensorIterator.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static void convertLevelType (SparseTensorEncodingAttr enc, Level lvl, SmallVectorImpl< Type > &fields)
static std::optional< LogicalResult > convertIterSpaceType (IterSpaceType itSp, SmallVectorImpl< Type > &fields)
static std::optional< LogicalResult > convertIteratorType (IteratorType itTp, SmallVectorImpl< Type > &fields)
static ValueRange genCoIterateBranchNest (PatternRewriter &rewriter, Location loc, CoIterateOp op, Value loopCrd, ArrayRef< std::unique_ptr< SparseIterator > > iters, ArrayRef< Block * > newBlocks, ArrayRef< Block * > oldBlocks, ArrayRef< Value > userReduc)
static ValueRange genLoopWithIterator (PatternRewriter &rewriter, Location loc, SparseIterator *it, ValueRange reduc, function_ref< SmallVector< Value >(PatternRewriter &rewriter, Location loc, Region &loopBody, SparseIterator *it, ValueRange reduc)> bodyBuilder)
Function Documentation
convertIteratorType()
std::optional< LogicalResult > convertIteratorType (IteratorType itTp, SmallVectorImpl< Type > & fields) static
Definition at line 40 of file SparseIterationToScf.cpp.
References success().
Referenced by mlir::SparseIterationTypeConverter::SparseIterationTypeConverter().
convertIterSpaceType()
std::optional< LogicalResult > convertIterSpaceType (IterSpaceType itSp, SmallVectorImpl< Type > & fields) static
Definition at line 27 of file SparseIterationToScf.cpp.
References convertLevelType(), and success().
Referenced by mlir::SparseIterationTypeConverter::SparseIterationTypeConverter().
convertLevelType()
void convertLevelType (SparseTensorEncodingAttr enc, Level lvl, SmallVectorImpl< Type > & fields) static
Definition at line 15 of file SparseIterationToScf.cpp.
Referenced by convertIterSpaceType().
genCoIterateBranchNest()
ValueRange genCoIterateBranchNest (PatternRewriter & rewriter, Location loc, CoIterateOp op, Value loopCrd, ArrayRef< std::unique_ptr< SparseIterator > > iters, ArrayRef< Block * > newBlocks, ArrayRef< Block * > oldBlocks, ArrayRef< Value > userReduc) static
Definition at line 54 of file SparseIterationToScf.cpp.
References mlir::Region::begin(), mlir::sparse_tensor::I64BitSet::bits(), mlir::OpBuilder::cloneRegionBefore(), mlir::sparse_tensor::constantI1(), mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), genCoIterateBranchNest(), mlir::Block::getArguments(), mlir::sparse_tensor::SparseIterator::getCrd(), mlir::Block::getParent(), mlir::Region::getRegionNumber(), mlir::IRMapping::map(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and ValueRange.
Referenced by genCoIterateBranchNest().
genLoopWithIterator()
ValueRange genLoopWithIterator (PatternRewriter & rewriter, Location loc, SparseIterator * it, ValueRange reduc, function_ref< SmallVector< Value >(PatternRewriter &rewriter, Location loc, Region &loopBody, SparseIterator *it, ValueRange reduc)> bodyBuilder) static
Definition at line 120 of file SparseIterationToScf.cpp.
References b, mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::createBlock(), mlir::sparse_tensor::SparseIterator::forward(), mlir::sparse_tensor::SparseIterator::genForCond(), mlir::sparse_tensor::SparseIterator::genWhileCond(), mlir::Block::getArguments(), mlir::sparse_tensor::SparseIterator::getCursor(), mlir::sparse_tensor::SparseIterator::iteratableByFor(), mlir::sparse_tensor::SparseIterator::linkNewScope(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and ValueRange.