MLIR: lib/Dialect/Linalg/Transforms/Specialize.cpp File Reference
Specialize.cpp File Reference
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Dialect/Linalg/Passes.h.inc"
Classes
class mlir::impl::LinalgSpecializeGenericOpsPassBase< DerivedT >
Namespaces
namespace mlir
Include the generated interface declarations.
namespace mlir::impl
Attribute collections provide a dictionary-like interface.
Macros
#define GEN_PASS_DEF_LINALGSPECIALIZEGENERICOPSPASS
#define DEBUG_TYPE "linalg-specialization"
#define CONV_OP_SPECIALIZER(ConvOpTy)
Functions
std::unique_ptr<::mlir::Pass > mlir::impl::createLinalgSpecializeGenericOpsPass ()
std::unique_ptr<::mlir::Pass > mlir::createLinalgSpecializeGenericOpsPass ()
static bool areBinOpsSwapped (GenericOp genericOp)
static bool findIndexOfScalarOperand (GenericOp genericOp, int &index)
static FailureOr< LinalgOp > specializeLinalgElementwise (RewriterBase &rewriter, GenericOp genericOp, bool emitCategoryOp)
Macro Definition Documentation
CONV_OP_SPECIALIZER
#define CONV_OP_SPECIALIZER (ConvOpTy)
Value:
  if (std::optional<DilationsAndStrides> convParams =                          \
          matchConvolutionOpOfType<ConvOpTy>(genericOp))                       \
    return specializeToConvOp<ConvOpTy>(                                       \
        rewriter, genericOp, convParams->dilations, convParams->strides);      \
DEBUG_TYPE
#define DEBUG_TYPE "linalg-specialization"
Definition at line 29 of file Specialize.cpp.
GEN_PASS_DEF_LINALGSPECIALIZEGENERICOPSPASS
#define GEN_PASS_DEF_LINALGSPECIALIZEGENERICOPSPASS
Definition at line 25 of file Specialize.cpp.
Function Documentation
areBinOpsSwapped()
bool areBinOpsSwapped (GenericOp genericOp) static
Definition at line 49 of file Specialize.cpp.
References mlir::Block::front(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Block::getArgument(), and mlir::Operation::getOpOperand().
Referenced by specializeLinalgElementwise().
findIndexOfScalarOperand()
bool findIndexOfScalarOperand (GenericOp genericOp, int & index) static
Definition at line 80 of file Specialize.cpp.
References mlir::Block::front(), and mlir::Operation::getOperands().
Referenced by specializeLinalgElementwise().
specializeLinalgElementwise()
FailureOr< LinalgOp > specializeLinalgElementwise (RewriterBase & rewriter, GenericOp genericOp, bool emitCategoryOp) static
Definition at line 121 of file Specialize.cpp.
References areBinOpsSwapped(), findIndexOfScalarOperand(), mlir::AffineMap::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getContext(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::linalg::specializeGenericOp().