MLIR: lib/Dialect/SPIRV/IR/SPIRVCanonicalization.cpp File Reference
SPIRVCanonicalization.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "SPIRVCanonicalization.inc"
Functions
static Optional< bool > getScalarOrSplatBoolAttr (Attribute boolAttr)
Returns the boolean value under the hood if the given boolAttr is a scalar or splat vector bool constant.
static Attribute extractCompositeElement (Attribute composite, ArrayRef< unsigned > indices)
Function Documentation
extractCompositeElement()
static Attribute extractCompositeElement (Attribute composite, ArrayRef< unsigned > indices) static
Definition at line 48 of file SPIRVCanonicalization.cpp.
References mlir::RewritePatternSet::add(), mlir::Block::begin(), mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::Block::end(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::Builder::getIntegerAttr(), mlir::Operation::getRegion(), getScalarOrSplatBoolAttr(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), op, mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::success(), and value.
getScalarOrSplatBoolAttr()
static Optional<bool> getScalarOrSplatBoolAttr (Attribute boolAttr) static
Returns the boolean value under the hood if the given boolAttr is a scalar or splat vector bool constant.
Definition at line 29 of file SPIRVCanonicalization.cpp.
References mlir::Attribute::cast(), mlir::Attribute::dyn_cast(), mlir::Attribute::getType(), and mlir::BoolAttr::getValue().
Referenced by extractCompositeElement().