MLIR: lib/Target/SPIRV/TranslateRegistration.cpp File Reference
TranslateRegistration.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/SPIRV/Deserialization.h"
#include "mlir/Target/SPIRV/Serialization.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Namespaces
namespace mlir
Include the generated interface declarations.
Functions
static OwningOpRef< Operation * > deserializeModule (const llvm::MemoryBuffer *input, MLIRContext *context, const spirv::DeserializationOptions &options)
void mlir::registerFromSPIRVTranslation ()
static LogicalResult serializeModule (spirv::ModuleOp moduleOp, raw_ostream &output, const spirv::SerializationOptions &options)
void mlir::registerToSPIRVTranslation ()
static LogicalResult roundTripModule (spirv::ModuleOp module, bool emitDebugInfo, raw_ostream &output)
void mlir::registerTestRoundtripSPIRV ()
void mlir::registerTestRoundtripDebugSPIRV ()
Function Documentation
deserializeModule()
OwningOpRef< Operation * > deserializeModule (const llvm::MemoryBuffer * input, MLIRContext * context, const spirv::DeserializationOptions & options) static
Definition at line 39 of file TranslateRegistration.cpp.
References mlir::spirv::deserialize(), mlir::emitError(), mlir::MLIRContext::loadDialect(), and options.
Referenced by mlir::registerFromSPIRVTranslation().
roundTripModule()
LogicalResult roundTripModule (spirv::ModuleOp module, bool emitDebugInfo, raw_ostream & output) static
Definition at line 153 of file TranslateRegistration.cpp.
References mlir::spirv::deserialize(), mlir::MLIRContext::getDialectRegistry(), mlir::MLIRContext::loadAllAvailableDialects(), options, and mlir::spirv::serialize().
Referenced by mlir::registerTestRoundtripDebugSPIRV(), and mlir::registerTestRoundtripSPIRV().
serializeModule()
LogicalResult serializeModule (spirv::ModuleOp moduleOp, raw_ostream & output, const spirv::SerializationOptions & options) static
Definition at line 83 of file TranslateRegistration.cpp.
References options, and mlir::spirv::serialize().
Referenced by mlir::registerToSPIRVTranslation().