MLIR: lib/Conversion/StandardToSPIRV/StandardToSPIRV.cpp File Reference
StandardToSPIRV.cpp File Reference
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/Debug.h"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "std-to-spirv-pattern"
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
Functions
static bool isBoolScalarOrVector (Type type)
Returns true if the given type is a boolean scalar or vector type.
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder)
Converts the given srcAttr into a boolean attribute if it holds an integral value.
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder &builder)
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
static Value getOffsetForBitwidth (Location loc, Value srcIdx, int sourceBits, int targetBits, OpBuilder &builder)
Returns the offset of the value in targetBits representation.
static Value adjustAccessChainForBitwidth (SPIRVTypeConverter &typeConverter, spirv::AccessChainOp op, int sourceBits, int targetBits, OpBuilder &builder)
Returns an adjusted spirv::AccessChainOp.
static Value shiftValue (Location loc, Value value, Value offset, Value mask, int targetBits, OpBuilder &builder)
Returns the shifted targetBits-bit value with the given offset.
static bool isAllocationSupported (MemRefType t)
Returns true if the allocations of type t can be lowered to SPIR-V.
static Optional< spirv::Scope > getAtomicOpScope (MemRefType t)
Returns the scope to use for atomic operations use for emulating store operations of unsupported integer bitwidths, based on the memref type.
void mlir::populateStandardToSPIRVPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns)
Appends to a pattern list additional patterns for translating standard ops to SPIR-V ops.
void mlir::populateTensorToSPIRVPatterns (SPIRVTypeConverter &typeConverter, int64_t byteCountThreshold, RewritePatternSet &patterns)
Appends to a pattern list additional patterns for translating tensor ops to SPIR-V ops.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "std-to-spirv-pattern"
Definition at line 26 of file StandardToSPIRV.cpp.
DISPATCH [1/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpFOp, cmpFOp.getResult().getType(), \
                                         cmpFOpOperands.lhs(),                 \
                                         cmpFOpOperands.rhs());                \
    return success();
Referenced by getAtomicOpScope().
DISPATCH [2/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         cmpIOpOperands.lhs(),                 \
                                         cmpIOpOperands.rhs());                \
    return success();
DISPATCH [3/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    if (spirvOp::template hasTrait<OpTrait::spirv::UnsignedOp>() &&            \
        operandType != this->getTypeConverter()->convertType(operandType)) {   \
      return cmpIOp.emitError(                                                 \
          "bitwidth emulation is not implemented yet on unsigned op");         \
    }                                                                          \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         cmpIOpOperands.lhs(),                 \
                                         cmpIOpOperands.rhs());                \
    return success();
Function Documentation
adjustAccessChainForBitwidth()
static Value adjustAccessChainForBitwidth (SPIRVTypeConverter & typeConverter, spirv::AccessChainOp op, int sourceBits, int targetBits, OpBuilder & builder) static
Returns an adjusted spirv::AccessChainOp.
Based on the extension/capabilities, certain integer bitwidths sourceBits might not be supported. During conversion if a memref of an unsupported type is used, load/stores to this memref need to be modified to use a supported higher bitwidth targetBits and extracting the required bits. For an accessing a 1D array (spv.array or spv.rt_array), the last index is modified to load the bits needed. The extraction of the actual bits needed are handled separately. Note that this only works for a 1-D tensor.
Definition at line 165 of file StandardToSPIRV.cpp.
References mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), and loc.
Referenced by getAtomicOpScope().
convertBoolAttr()
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder) static
Converts the given srcAttr into a boolean attribute if it holds an integral value.
Returns null attribute if conversion fails.
Definition at line 45 of file StandardToSPIRV.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Builder::getBoolAttr().
Referenced by getAtomicOpScope().
convertFloatAttr()
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if dstType is not 32-bit or conversion fails.
Definition at line 82 of file StandardToSPIRV.cpp.
References mlir::Builder::getF32FloatAttr(), and mlir::Type::isF32().
Referenced by getAtomicOpScope().
convertIntegerAttr()
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if conversion fails.
Definition at line 55 of file StandardToSPIRV.cpp.
References mlir::Builder::getIntegerAttr().
Referenced by getAtomicOpScope().
emulateSignedRemainder()
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder & builder) static
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Note that this is needed for Vulkan. Per the Vulkan's SPIR-V environment spec, "for the OpSRem and OpSMod instructions, if either operand is negative the result is undefined." So we cannot directly use spv.SRem/spv.SMod if either operand can be negative. Emulate it via spv.UMod.
Definition at line 110 of file StandardToSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::Value::getType(), and loc.
Referenced by getAtomicOpScope().
getAtomicOpScope()
static Optional<spirv::Scope> getAtomicOpScope (MemRefType t) static
Returns the scope to use for atomic operations use for emulating store operations of unsupported integer bitwidths, based on the memref type.
Returns None on failure.
Definition at line 210 of file StandardToSPIRV.cpp.
References adjustAccessChainForBitwidth(), mlir::Region::begin(), mlir::Location::cast(), mlir::Type::cast(), convertBoolAttr(), convertFloatAttr(), convertIntegerAttr(), mlir::OpBuilder::create(), DISPATCH, mlir::Type::dyn_cast(), emulateSignedRemainder(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::spirv::PointerType::get(), mlir::ShapedType::getDimSize(), mlir::spirv::getElementPtr(), getElementType(), mlir::ShapedType::getElementTypeBitWidth(), mlir::Builder::getIntegerAttr(), mlir::Type::getIntOrFloatBitWidth(), mlir::SymbolTable::getNearestSymbolTable(), mlir::ShapedType::getNumElements(), getOffsetForBitwidth(), mlir::Block::getOps(), mlir::ShapedType::getRank(), mlir::Operation::getRegion(), mlir::SPIRVTypeConverter::getStorageClassForMemorySpace(), mlir::Value::getType(), mlir::ShapedType::hasStaticShape(), mlir::Type::isa(), isAllocationSupported(), isBoolScalarOrVector(), mlir::Type::isInteger(), mlir::Type::isIntOrIndexOrFloat(), mlir::spirv::CompositeType::isValid(), mlir::spirv::linearizeIndex(), loc, mlir::ConversionPatternRewriter::notifyMatchFailure(), op, mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::OpBuilder::setInsertionPointToStart(), shiftValue(), and mlir::success().
getOffsetForBitwidth()
static Value getOffsetForBitwidth (Location loc, Value srcIdx, int sourceBits, int targetBits, OpBuilder & builder) static
Returns the offset of the value in targetBits representation.
srcIdx is an index into a 1-D array with each element having sourceBits. It's assumed to be non-negative.
When accessing an element in the array treating as having elements of targetBits, multiple values are loaded in the same time. The method returns the offset where the srcIdx locates in the value. For example, if sourceBits equals to 8 and targetBits equals to 32, the x-th element is located at (x % 4) * 8. Because there are four elements in one i32, and one element has 8 bits.
Definition at line 143 of file StandardToSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), and loc.
Referenced by getAtomicOpScope().
isAllocationSupported()
static bool isAllocationSupported (MemRefType t) static
Returns true if the allocations of type t can be lowered to SPIR-V.
Definition at line 194 of file StandardToSPIRV.cpp.
References mlir::Type::dyn_cast(), elementType(), mlir::SPIRVTypeConverter::getMemorySpaceForStorageClass(), and mlir::Type::isIntOrFloat().
Referenced by getAtomicOpScope().
isBoolScalarOrVector()
static bool isBoolScalarOrVector (Type type) static
Returns true if the given type is a boolean scalar or vector type.
Definition at line 35 of file StandardToSPIRV.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isInteger().
Referenced by getAtomicOpScope().
shiftValue()
static Value shiftValue (Location loc, Value value, Value offset, Value mask, int targetBits, OpBuilder & builder) static
Returns the shifted targetBits-bit value with the given offset.
Definition at line 185 of file StandardToSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIntegerType(), loc, and value.
Referenced by getAtomicOpScope().