MLIR: lib/Conversion/StandardToLLVM/StandardToLLVM.cpp File Reference
StandardToLLVM.cpp File Reference
#include "../PassDetail.h"
#include "mlir/Analysis/DataLayoutAnalysis.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/LLVMCommon/VectorPattern.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/FunctionCallUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FormatVariadic.h"
#include <functional>
Macros
#define PASS_NAME "convert-std-to-llvm"
Functions
static void filterFuncAttributes (ArrayRef< NamedAttribute > attrs, bool filterArgAttrs, SmallVectorImpl< NamedAttribute > &result)
Only retain those attributes that are not constructed by LLVMFuncOp::build.
static void wrapForExternalCallers (OpBuilder &rewriter, Location loc, LLVMTypeConverter &typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp)
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
static void wrapExternalFunction (OpBuilder &builder, Location loc, LLVMTypeConverter &typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp)
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
static Optional< LLVM::AtomicBinOp > matchSimpleAtomicOp (AtomicRMWOp atomicOp)
Try to match the kind of a std.atomic_rmw to determine whether to use a lowering to llvm.atomicrmw or fallback to llvm.cmpxchg.
Macro Definition Documentation
PASS_NAME
#define PASS_NAME "convert-std-to-llvm"
Definition at line 48 of file StandardToLLVM.cpp.
Function Documentation
filterFuncAttributes()
static void filterFuncAttributes (ArrayRef< NamedAttribute > attrs, bool filterArgAttrs, SmallVectorImpl< NamedAttribute > & result) static
Only retain those attributes that are not constructed by LLVMFuncOp::build.
If filterArgAttrs is set, also filter out argument attributes.
Definition at line 53 of file StandardToLLVM.cpp.
References mlir::function_like_impl::getArgDictAttrName(), mlir::SymbolTable::getSymbolAttrName(), and mlir::function_like_impl::getTypeAttrName().
Referenced by wrapExternalFunction(), and wrapForExternalCallers().
matchSimpleAtomicOp()
static Optional<LLVM::AtomicBinOp> matchSimpleAtomicOp (AtomicRMWOp atomicOp) static
Try to match the kind of a std.atomic_rmw to determine whether to use a lowering to llvm.atomicrmw or fallback to llvm.cmpxchg.
Definition at line 887 of file StandardToLLVM.cpp.
References mlir::Block::back(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::Builder::getContext(), mlir::Builder::getI64ArrayAttr(), mlir::OpBuilder::getInsertionBlock(), mlir::LLVM::LLVMStructType::getLiteral(), mlir::Operation::getOperand(), mlir::Operation::getResults(), mlir::Block::getTerminator(), loc, mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::map(), max(), min(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and mlir::Block::without_terminator().
wrapExternalFunction()
static void wrapExternalFunction (OpBuilder & builder, Location loc, LLVMTypeConverter & typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp) static
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
Creates a body for the (external) newFuncOp that allocates a memref descriptor on stack, packs the individual arguments into this descriptor and passes a pointer to it into the auxiliary function. If the result of the function cannot be directly returned, we write it to a special first argument that provides a pointer to a corresponding struct. This auxiliary external function is now compatible with functions defined in C using pointers to C structs corresponding to a memref descriptor.
Definition at line 131 of file StandardToLLVM.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::Type::cast(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::ConversionPatternRewriter::convertRegionTypes(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Type::dyn_cast(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::LLVM::detail::extractNDVectorTypeInfo(), mlir::failed(), mlir::failure(), filterFuncAttributes(), mlir::LLVM::LLVMFunctionType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::function_like_impl::getArgDictAttrName(), mlir::Builder::getArrayAttr(), mlir::getElementTypeOrSelf(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Builder::getNamedAttr(), mlir::LLVM::LLVMFunctionType::getNumParams(), mlir::MemRefDescriptor::getNumUnpackedValues(), mlir::UnrankedMemRefDescriptor::getNumUnpackedValues(), mlir::Value::getType(), mlir::Builder::getUnknownLoc(), mlir::Builder::getZeroAttr(), mlir::LLVM::detail::handleMultidimensionalVectors(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::Type::isa(), mlir::LLVM::isCompatibleType(), loc, mlir::LLVM::detail::nDVectorIterate(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::LLVM::detail::oneToOneRewrite(), op, mlir::MemRefDescriptor::pack(), mlir::UnrankedMemRefDescriptor::pack(), mlir::UnrankedMemRefDescriptor::rank(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewriter, mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::ConversionPatternRewriter::splitBlock(), mlir::succeeded(), mlir::success(), vectorType(), and wrapForExternalCallers().
wrapForExternalCallers()
static void wrapForExternalCallers (OpBuilder & rewriter, Location loc, LLVMTypeConverter & typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp) static
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
This function can be called from C by passing a pointer to a C struct corresponding to a memref descriptor. Similarly, returned memrefs are passed via pointers to a C struct that is passed as additional argument. Internally, the auxiliary function unpacks the descriptor into individual components and forwards them to newFuncOp and forwards the results to the extra arguments.
Definition at line 75 of file StandardToLLVM.cpp.
References mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::OpBuilder::create(), mlir::detail::enumerate(), filterFuncAttributes(), loc, mlir::OpBuilder::setInsertionPointToStart(), mlir::MemRefDescriptor::unpack(), and mlir::UnrankedMemRefDescriptor::unpack().
Referenced by wrapExternalFunction().