MLIR: lib/Analysis/DataFlow/StridedMetadataRangeAnalysis.cpp File Reference
StridedMetadataRangeAnalysis.cpp File Reference
#include "mlir/Analysis/DataFlow/StridedMetadataRangeAnalysis.h"
#include "mlir/Analysis/DataFlow/IntegerRangeAnalysis.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/DebugStringHelper.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugLog.h"
Macros
#define DEBUG_TYPE "strided-metadata-range-analysis"
Functions
static StridedMetadataRange getEntryStateImpl (Value v, int32_t indexBitwidth)
Get the entry state for a value.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "strided-metadata-range-analysis"
Definition at line 25 of file StridedMetadataRangeAnalysis.cpp.
Function Documentation
getEntryStateImpl()
StridedMetadataRange getEntryStateImpl (Value v, int32_t indexBitwidth) static
Get the entry state for a value.
For any value that is not a ranked memref, this function sets the metadata to a top state with no offsets, sizes, or strides. For memref types, this function will use the metadata in the type to try to deduce as much informaiton as possible.
Definition at line 34 of file StridedMetadataRangeAnalysis.cpp.
References mlir::ConstantIntRanges::constant(), mlir::StridedMetadataRange::getMaxRanges(), getStridesAndOffset(), and mlir::Value::getType().
Referenced by mlir::dataflow::StridedMetadataRangeAnalysis::setToEntryState().