MLIR: mlir::tblgen::Operator::VariableDecoratorIterator Struct Reference
mlir::tblgen::Operator::VariableDecoratorIterator Struct Reference
A utility iterator over a list of variable decorators.
#include "mlir/TableGen/Operator.h"
Public Member Functions
VariableDecoratorIterator (const llvm::Init *const *it)
Initializes the iterator to the specified iterator.
Static Public Member Functions
static VariableDecorator unwrap (const llvm::Init *init)
Detailed Description
A utility iterator over a list of variable decorators.
Definition at line 121 of file Operator.h.
Constructor & Destructor Documentation
VariableDecoratorIterator()
mlir::tblgen::Operator::VariableDecoratorIterator::VariableDecoratorIterator (const llvm::Init *const * it) inline
Initializes the iterator to the specified iterator.
Definition at line 126 of file Operator.h.
References unwrap().
Member Function Documentation
unwrap()
auto Operator::VariableDecoratorIterator::unwrap (const llvm::Init * init) static
Definition at line 868 of file Operator.cpp.
References mlir::tblgen::Operator::getDef().
Referenced by VariableDecoratorIterator().
The documentation for this struct was generated from the following files:
include/mlir/TableGen/Operator.h
lib/TableGen/Operator.cpp