MLIR: PyGlobalDebugFlag Struct Reference
PyGlobalDebugFlag Struct Reference
Wrapper for the global LLVM debugging flag.
Static Public Member Functions
static void set (py::object &o, bool enable)
static bool get (py::object)
static void bind (py::module &m)
Detailed Description
Wrapper for the global LLVM debugging flag.
Definition at line 159 of file IRCore.cpp.
Member Function Documentation
bind()
static void PyGlobalDebugFlag::bind (py::module & m) inline static
Definition at line 164 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::createOpView(), mlir::python::PyOperation::forOperation(), get(), mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), kAppendBlockDocstring, mlirBlockCreate(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockIsNull(), mlirOperationGetNextInBlock(), mlirOperationGetNumRegions(), mlirOperationGetRegion(), mlirOperationIsNull(), mlirRegionAppendOwnedBlock(), mlirRegionGetFirstBlock(), mlir::python::PyMlirContext::PyMlirContext(), set(), and mlir::python::SetPyError().
Referenced by mlir::python::PyValue::createFromCapsule().
get()
static bool PyGlobalDebugFlag::get (py::object) inline static
Definition at line 162 of file IRCore.cpp.
References mlirIsGlobalDebugEnabled().
Referenced by bind().
set()
static void PyGlobalDebugFlag::set (py::object & o, bool enable) inline static
Definition at line 160 of file IRCore.cpp.
References mlirEnableGlobalDebug().
Referenced by bind().
The documentation for this struct was generated from the following file:
lib/Bindings/Python/IRCore.cpp