MLIR: mlir::LLVM::detail::LLVMTypeAndSizeStorage Struct Reference
mlir::LLVM::detail::LLVMTypeAndSizeStorage Struct Reference
Common storage used for LLVM dialect types that need an element type and a number: arrays, fixed and scalable vectors.
#include "Dialect/LLVMIR/IR/TypeDetail.h"
Public Types
using KeyTy = std::tuple<Type, unsigned>
Public Member Functions
LLVMTypeAndSizeStorage (const KeyTy &key)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static LLVMTypeAndSizeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type elementType
unsigned numElements
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Common storage used for LLVM dialect types that need an element type and a number: arrays, fixed and scalable vectors.
The actual semantics of the type is defined by its kind.
Definition at line 366 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::LLVM::detail::LLVMTypeAndSizeStorage::KeyTy = std::tuple<Type, unsigned>
Definition at line 367 of file TypeDetail.h.
Constructor & Destructor Documentation
LLVMTypeAndSizeStorage()
mlir::LLVM::detail::LLVMTypeAndSizeStorage::LLVMTypeAndSizeStorage (const KeyTy & key) inline
Definition at line 369 of file TypeDetail.h.
References elementType, mlir::get(), and numElements.
Referenced by construct().
Member Function Documentation
construct()
LLVMTypeAndSizeStorage * mlir::LLVM::detail::LLVMTypeAndSizeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 372 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and LLVMTypeAndSizeStorage().
operator==()
bool mlir::LLVM::detail::LLVMTypeAndSizeStorage::operator== (const KeyTy & key) const inline
Definition at line 378 of file TypeDetail.h.
References elementType, and numElements.
Member Data Documentation
elementType
Type mlir::LLVM::detail::LLVMTypeAndSizeStorage::elementType
Definition at line 382 of file TypeDetail.h.
Referenced by LLVMTypeAndSizeStorage(), and operator==().
numElements
unsigned mlir::LLVM::detail::LLVMTypeAndSizeStorage::numElements
Definition at line 383 of file TypeDetail.h.
Referenced by LLVMTypeAndSizeStorage(), and operator==().
The documentation for this struct was generated from the following file:
lib/Dialect/LLVMIR/IR/TypeDetail.h