MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedSubChannelType, QuantizedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "UniformQuantizedSubChannelType"
static const MlirStringRef name
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedSubChannelType, QuantizedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedSubChannelType, QuantizedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedSubChannelType, QuantizedType >
PyConcreteType ()=default
Detailed Description
Definition at line 368 of file DialectQuant.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType::bindDerived (ClassTy & c) inline static
Definition at line 379 of file DialectQuant.cpp.
References mlirUniformQuantizedSubChannelTypeGet(), mlirUniformQuantizedSubChannelTypeGetBlockSize(), mlirUniformQuantizedSubChannelTypeGetNumBlockSizes(), mlirUniformQuantizedSubChannelTypeGetQuantizedDimension(), mlirUniformQuantizedSubChannelTypeGetScales(), and mlirUniformQuantizedSubChannelTypeGetZeroPoints().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType::getTypeIdFunction static constexpr
Initial value:
=
      mlirUniformQuantizedSubChannelTypeGetTypeID
Definition at line 372 of file DialectQuant.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType::isaFunction static constexpr
Initial value:
=
      mlirTypeIsAUniformQuantizedSubChannelType
Definition at line 370 of file DialectQuant.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType::name inline static
Initial value:
=
      mlirUniformQuantizedSubChannelTypeGetName()
Definition at line 375 of file DialectQuant.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedSubChannelType::pyClassName = "UniformQuantizedSubChannelType" static constexpr
Definition at line 374 of file DialectQuant.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectQuant.cpp