MLIR: pybind11::detail::type_caster< MlirContext > Struct Reference
pybind11::detail::type_caster< MlirContext > Struct Reference
Casts object -> MlirContext.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirContext, _("MlirContext"))
bool load (handle src, bool)
Detailed Description
Casts object -> MlirContext.
Definition at line 121 of file PybindAdaptors.h.
Member Function Documentation
load()
bool pybind11::detail::type_caster< MlirContext >::load (handle src, bool) inline
Definition at line 123 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, pybind11::detail::mlirApiObjectToCapsule(), mlirContextIsNull(), and mlirPythonCapsuleToContext().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirContext >::PYBIND11_TYPE_CASTER (MlirContext , _("MlirContext"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h