MLIR: mlir::mesh::ElementwiseShardingInterface< ElemwiseOp > Struct Template Reference
mlir::mesh::ElementwiseShardingInterface< ElemwiseOp > Struct Template Reference
#include "mlir/Dialect/Mesh/Interfaces/ShardingInterfaceImpl.h"
Public Member Functions
SmallVector< utils::IteratorType > getLoopIteratorTypes (Operation *op) const
SmallVector< AffineMap > getIndexingMaps (Operation *op) const
LogicalResult spmdize (Operation *op, ArrayRef< Value > spmdizedOperands, ArrayRef< MeshSharding > operandShardings, ArrayRef< MeshSharding > resultShardings, IRMapping &spmdizationMap, SymbolTableCollection &symbolTable, OpBuilder &builder) const
Detailed Description
template<typename ElemwiseOp>
struct mlir::mesh::ElementwiseShardingInterface< ElemwiseOp >
Definition at line 106 of file ShardingInterfaceImpl.h.
Member Function Documentation
getIndexingMaps()
template<typename ElemwiseOp > SmallVector<AffineMap> mlir::mesh::ElementwiseShardingInterface< ElemwiseOp >::getIndexingMaps (Operation * op) const inline
Definition at line 119 of file ShardingInterfaceImpl.h.
References mlir::Operation::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), and mlir::Value::getType().
getLoopIteratorTypes()
template<typename ElemwiseOp > SmallVector<utils::IteratorType> mlir::mesh::ElementwiseShardingInterface< ElemwiseOp >::getLoopIteratorTypes (Operation * op) const inline
Definition at line 109 of file ShardingInterfaceImpl.h.
References mlir::Operation::getOperand(), and mlir::Value::getType().
spmdize()
template<typename ElemwiseOp > LogicalResult mlir::mesh::ElementwiseShardingInterface< ElemwiseOp >::spmdize (Operation * op, ArrayRef< Value > spmdizedOperands, ArrayRef< MeshSharding > operandShardings, ArrayRef< MeshSharding > resultShardings, IRMapping & spmdizationMap, SymbolTableCollection & symbolTable, OpBuilder & builder) const inline
Definition at line 132 of file ShardingInterfaceImpl.h.
References mlir::mesh::spmdizeTriviallyShardableOperation().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Mesh/Interfaces/ShardingInterfaceImpl.h