MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture Struct Reference
RAII object that captures any error diagnostics emitted to the provided context.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
ErrorCapture (PyMlirContextRef ctx)
~ErrorCapture ()
std::vector< PyDiagnostic::DiagnosticInfo > take ()
Detailed Description
RAII object that captures any error diagnostics emitted to the provided context.
Definition at line 450 of file IRCore.h.
Constructor & Destructor Documentation
ErrorCapture()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture::ErrorCapture (PyMlirContextRef ctx) inline
Definition at line 451 of file IRCore.h.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::get(), mlirContextAttachDiagnosticHandler(), and nullptr.
~ErrorCapture()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture::~ErrorCapture () inline
Definition at line 455 of file IRCore.h.
References mlirContextDetachDiagnosticHandler().
Member Function Documentation
take()
std::vector< PyDiagnostic::DiagnosticInfo > mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMlirContext::ErrorCapture::take () inline
Definition at line 460 of file IRCore.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyFloatAttribute::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemRefType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyRankedTensorType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedMemRefType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyUnrankedTensorType::bindDerived(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populatePassManagerSubmodule().
The documentation for this struct was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp