MLIR: mlir::detail::DynamicAttrStorage Struct Reference
mlir::detail::DynamicAttrStorage Struct Reference
Storage of DynamicAttr.
Public Types
using KeyTy = std::pair<DynamicAttrDefinition *, ArrayRef<Attribute>>
Public Member Functions
DynamicAttrStorage (DynamicAttrDefinition *attrDef, ArrayRef< Attribute > params)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::AttributeStorage
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static llvm::hash_code hashKey (const KeyTy &key)
static DynamicAttrStorage * construct (AttributeStorageAllocator &alloc, const KeyTy &key)
Public Attributes
DynamicAttrDefinition * attrDef
Definition of the type.
ArrayRef< Attribute > params
The type parameters.
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Storage of DynamicAttr.
Contains a pointer to the attribute definition and attribute parameters.
Definition at line 213 of file ExtensibleDialect.cpp.
Member Typedef Documentation
KeyTy
using mlir::detail::DynamicAttrStorage::KeyTy = std::pair<DynamicAttrDefinition *, ArrayRef<Attribute>>
Definition at line 214 of file ExtensibleDialect.cpp.
Constructor & Destructor Documentation
DynamicAttrStorage()
mlir::detail::DynamicAttrStorage::DynamicAttrStorage (DynamicAttrDefinition * attrDef, ArrayRef< Attribute > params) inline explicit
Definition at line 216 of file ExtensibleDialect.cpp.
References attrDef, and params.
Referenced by construct().
Member Function Documentation
construct()
DynamicAttrStorage * mlir::detail::DynamicAttrStorage::construct (AttributeStorageAllocator & alloc, const KeyTy & key) inline static
Definition at line 228 of file ExtensibleDialect.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::StorageUniquer::StorageAllocator::copyInto(), and DynamicAttrStorage().
hashKey()
llvm::hash_code mlir::detail::DynamicAttrStorage::hashKey (const KeyTy & key) inline static
Definition at line 224 of file ExtensibleDialect.cpp.
operator==()
bool mlir::detail::DynamicAttrStorage::operator== (const KeyTy & key) const inline
Definition at line 220 of file ExtensibleDialect.cpp.
References attrDef, and params.
Member Data Documentation
attrDef
DynamicAttrDefinition* mlir::detail::DynamicAttrStorage::attrDef
Definition of the type.
Definition at line 235 of file ExtensibleDialect.cpp.
Referenced by DynamicAttrStorage(), and operator==().
params
ArrayRef<Attribute> mlir::detail::DynamicAttrStorage::params
The type parameters.
Definition at line 238 of file ExtensibleDialect.cpp.
Referenced by DynamicAttrStorage(), and operator==().
The documentation for this struct was generated from the following file:
lib/IR/ExtensibleDialect.cpp