MLIR: mlir::FieldParser< DeviceIDTargetDeviceSpecPair > Struct Reference
mlir::FieldParser< DeviceIDTargetDeviceSpecPair > Struct Reference
A FieldParser for key-value pairs of DeviceID-target device spec pairs that make up a target system spec.
Static Public Member Functions
static FailureOr< DeviceIDTargetDeviceSpecPair > parse (AsmParser &parser)
Detailed Description
A FieldParser for key-value pairs of DeviceID-target device spec pairs that make up a target system spec.
Definition at line 321 of file DLTI.cpp.
Member Function Documentation
parse()
static FailureOr<DeviceIDTargetDeviceSpecPair> mlir::FieldParser< DeviceIDTargetDeviceSpecPair >::parse (AsmParser & parser) inline static
Definition at line 322 of file DLTI.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getStringAttr(), mlir::query::parse(), mlir::AsmParser::parseColon(), and mlir::AsmParser::parseString().
The documentation for this struct was generated from the following file:
lib/Dialect/DLTI/DLTI.cpp