MLIR: mlir::OptionValue< mlir::OpPassManager > Struct Reference
mlir::OptionValue< mlir::OpPassManager > Struct Reference final
#include "mlir/Pass/PassOptions.h"
Public Types
using WrapperType = mlir::OpPassManager
Public Member Functions
OptionValue ()
OptionValue (const OptionValue< mlir::OpPassManager > &rhs)
OptionValue (const mlir::OpPassManager &value)
OptionValue< mlir::OpPassManager > & operator= (const mlir::OpPassManager &rhs)
~OptionValue ()
bool hasValue () const
Returns if the current option has a value.
mlir::OpPassManager & getValue () const
Returns the current value of the option.
void setValue (const mlir::OpPassManager &newValue)
Set the value of the option.
void setValue (StringRef pipelineStr)
bool compare (const mlir::OpPassManager &rhs) const
Compare the option with the provided value.
bool compare (const GenericOptionValue &rhs) const override
Detailed Description
Definition at line 474 of file PassOptions.h.
Member Typedef Documentation
WrapperType
using mlir::OptionValue< mlir::OpPassManager >::WrapperType = mlir::OpPassManager
Definition at line 475 of file PassOptions.h.
Constructor & Destructor Documentation
OptionValue() [1/3]
mlir::OptionValue< mlir::OpPassManager >::OptionValue ()
Referenced by compare(), operator=(), and OptionValue().
OptionValue() [2/3]
mlir::OptionValue< mlir::OpPassManager >::OptionValue (const OptionValue< mlir::OpPassManager > & rhs)
References OptionValue(), and rhs.
OptionValue() [3/3]
mlir::OptionValue< mlir::OpPassManager >::OptionValue (const mlir::OpPassManager & value)
~OptionValue()
mlir::OptionValue< mlir::OpPassManager >::~OptionValue ()
Member Function Documentation
compare() [1/2]
bool mlir::OptionValue< mlir::OpPassManager >::compare (const GenericOptionValue< mlir::OpPassManager > & rhs) const inline override
Definition at line 498 of file PassOptions.h.
References compare(), OptionValue(), and rhs.
compare() [2/2]
bool mlir::OptionValue< mlir::OpPassManager >::compare (const mlir::OpPassManager & rhs) const
Compare the option with the provided value.
References rhs.
Referenced by compare().
getValue()
mlir::OpPassManager & mlir::OptionValue< mlir::OpPassManager >::getValue () const inline
Returns the current value of the option.
Definition at line 487 of file PassOptions.h.
References hasValue().
hasValue()
bool mlir::OptionValue< mlir::OpPassManager >::hasValue () const inline
Returns if the current option has a value.
Definition at line 484 of file PassOptions.h.
Referenced by getValue().
operator=()
OptionValue< mlir::OpPassManager > & mlir::OptionValue< mlir::OpPassManager >::operator= (const mlir::OpPassManager & rhs)
References OptionValue(), and rhs.
setValue() [1/2]
void mlir::OptionValue< mlir::OpPassManager >::setValue (const mlir::OpPassManager & newValue)
Set the value of the option.
setValue() [2/2]
void mlir::OptionValue< mlir::OpPassManager >::setValue (StringRef pipelineStr)
The documentation for this struct was generated from the following file:
include/mlir/Pass/PassOptions.h