MLIR: mlir::JamBlockGatherer< OpTy > Struct Template Reference
mlir::JamBlockGatherer< OpTy > Struct Template Reference
#include "mlir/Interfaces/LoopLikeInterface.h"
Public Member Functions
void walk (Operation *op)
void walk (Block &block)
Public Attributes
SmallVector< std::pair< Block::iterator, Block::iterator > > subBlocks
Detailed Description
template<typename OpTy>
struct mlir::JamBlockGatherer< OpTy >
Definition at line 56 of file LoopLikeInterface.h.
Member Function Documentation
walk() [1/2]
template<typename OpTy > void mlir::JamBlockGatherer< OpTy >::walk (Block & block) inline
Definition at line 67 of file LoopLikeInterface.h.
References mlir::Block::back(), mlir::Block::begin(), mlir::Block::empty(), mlir::Block::end(), mlir::Operation::hasTrait(), mlir::JamBlockGatherer< OpTy >::subBlocks, and mlir::JamBlockGatherer< OpTy >::walk().
walk() [2/2]
template<typename OpTy > void mlir::JamBlockGatherer< OpTy >::walk (Operation * op) inline
Definition at line 61 of file LoopLikeInterface.h.
References mlir::Operation::getRegions().
Referenced by mlir::affine::loopUnrollJamByFactor(), mlir::loopUnrollJamByFactor(), and mlir::JamBlockGatherer< OpTy >::walk().
Member Data Documentation
subBlocks
template<typename OpTy > SmallVector<std::pair<Block::iterator, Block::iterator> > mlir::JamBlockGatherer< OpTy >::subBlocks
Definition at line 58 of file LoopLikeInterface.h.
Referenced by mlir::affine::loopUnrollJamByFactor(), mlir::loopUnrollJamByFactor(), and mlir::JamBlockGatherer< OpTy >::walk().
The documentation for this struct was generated from the following file:
include/mlir/Interfaces/LoopLikeInterface.h