MLIR: ReifyCollapseShapeOp Struct Reference
ReifyCollapseShapeOp Struct Reference
Public Member Functions
LogicalResult reifyResultShapes (Operation *op, OpBuilder &b, ReifiedRankedShapedTypeDims &reifiedReturnShapes) const
Detailed Description
Definition at line 60 of file TensorInferTypeOpInterfaceImpl.cpp.
Member Function Documentation
reifyResultShapes()
LogicalResult ReifyCollapseShapeOp::reifyResultShapes (Operation * op, OpBuilder & b, ReifiedRankedShapedTypeDims & reifiedReturnShapes) const inline
Definition at line 64 of file TensorInferTypeOpInterfaceImpl.cpp.
References b, getCollapsedOutputShapeFromInputShape(), mlir::Operation::getLoc(), and success().
The documentation for this struct was generated from the following file:
lib/Dialect/Tensor/IR/TensorInferTypeOpInterfaceImpl.cpp