MLIR: nanobind::detail::type_caster< MlirType > Struct Reference
nanobind::detail::type_caster< MlirType > Struct Reference
Casts object <-> MlirType.
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Public Member Functions
bool from_python (handle src, uint8_t flags, cleanup_list *cleanup) noexcept
Static Public Member Functions
static handle from_cpp (MlirType t, rv_policy, cleanup_list *cleanup) noexcept
Detailed Description
Casts object <-> MlirType.
Definition at line 324 of file NanobindAdaptors.h.
Member Function Documentation
from_cpp()
static handle nanobind::detail::type_caster< MlirType >::from_cpp (MlirType t, rv_policy , cleanup_list * cleanup) inline static noexcept
Definition at line 333 of file NanobindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_MAYBE_DOWNCAST_ATTR, and mlirPythonTypeToCapsule().
from_python()
bool nanobind::detail::type_caster< MlirType >::from_python (handle src, uint8_t flags, cleanup_list * cleanup) inline noexcept
Definition at line 326 of file NanobindAdaptors.h.
References nanobind::detail::mlirApiObjectToCapsule(), mlirPythonCapsuleToType(), and mlirTypeIsNull().
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/NanobindAdaptors.h