MLIR: mlir::detail::constant_float_predicate_matcher Struct Reference
mlir::detail::constant_float_predicate_matcher Struct Reference
The matcher that matches a given target constant scalar / vector splat / tensor splat float value that fulfills a predicate.
#include "mlir/IR/Matchers.h"
Public Member Functions
bool match (Attribute attr)
bool match (Operation *op)
Public Attributes
bool(* predicate)(const APFloat &)
Detailed Description
The matcher that matches a given target constant scalar / vector splat / tensor splat float value that fulfills a predicate.
Definition at line 194 of file Matchers.h.
Member Function Documentation
match() [1/2]
bool mlir::detail::constant_float_predicate_matcher::match (Attribute attr) inline
Definition at line 197 of file Matchers.h.
References mlir::detail::constant_float_value_binder::match(), and predicate.
match() [2/2]
bool mlir::detail::constant_float_predicate_matcher::match (Operation * op) inline
Definition at line 202 of file Matchers.h.
References mlir::detail::constant_float_value_binder::match(), and predicate.
Member Data Documentation
predicate
bool(* mlir::detail::constant_float_predicate_matcher::predicate) (const APFloat &)
Definition at line 195 of file Matchers.h.
Referenced by match(), and match().
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h