MLIR: mlir::xegpu::uArch::Instruction Struct Reference
mlir::xegpu::uArch::Instruction Struct Reference
#include "mlir/Dialect/XeGPU/uArch/uArchBase.h"
Public Member Functions
Instruction (InstructionKind kind, InstructionScope scope)
~Instruction ()=default
InstructionKind getInstructionKind () const
InstructionScope getScope () const
Static Public Member Functions
static llvm::StringRef toString (InstructionKind instKind)
static std::optional< InstructionKind > parseInstructionKind (llvm::StringRef str)
Protected Attributes
const InstructionKind instKind
const InstructionScope scope
Detailed Description
Definition at line 50 of file uArchBase.h.
Constructor & Destructor Documentation
Instruction()
mlir::xegpu::uArch::Instruction::Instruction (InstructionKind kind, InstructionScope scope) inline
Definition at line 51 of file uArchBase.h.
References instKind, and scope.
Referenced by mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction::classof(), mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction::classof(), mlir::xegpu::uArch::Subgroup2DBlockStoreInstruction::classof(), mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc::classof(), mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction::Subgroup2DBlockLoadInstruction(), mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction::Subgroup2DBlockPrefetchInstruction(), mlir::xegpu::uArch::Subgroup2DBlockStoreInstruction::Subgroup2DBlockStoreInstruction(), and mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc::SubgroupMatrixMultiplyAcc().
~Instruction()
mlir::xegpu::uArch::Instruction::~Instruction () default
Member Function Documentation
getInstructionKind()
InstructionKind mlir::xegpu::uArch::Instruction::getInstructionKind () const inline
Definition at line 56 of file uArchBase.h.
References instKind.
getScope()
InstructionScope mlir::xegpu::uArch::Instruction::getScope () const inline
Definition at line 57 of file uArchBase.h.
References scope.
parseInstructionKind()
std::optional< InstructionKind > mlir::xegpu::uArch::Instruction::parseInstructionKind (llvm::StringRef str) inline static
Definition at line 73 of file uArchBase.h.
References mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc.
toString()
llvm::StringRef mlir::xegpu::uArch::Instruction::toString (InstructionKind instKind) inline static
Definition at line 58 of file uArchBase.h.
References instKind, mlir::xegpu::uArch::Subgroup2DBlockLoad, mlir::xegpu::uArch::Subgroup2DBlockPrefetch, mlir::xegpu::uArch::Subgroup2DBlockStore, and mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc.
Member Data Documentation
instKind
const InstructionKind mlir::xegpu::uArch::Instruction::instKind protected
Definition at line 80 of file uArchBase.h.
Referenced by getInstructionKind(), Instruction(), and toString().
scope
const InstructionScope mlir::xegpu::uArch::Instruction::scope protected
Definition at line 81 of file uArchBase.h.
Referenced by getScope(), and Instruction().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/uArchBase.h