MLIR: ValueEquivalenceCache Struct Reference
ValueEquivalenceCache Struct Reference
Public Member Functions
LogicalResult checkEquivalent (Value lhsValue, Value rhsValue)
LogicalResult checkCommutativeEquivalent (ValueRange lhsRange, ValueRange rhsRange)
void markEquivalent (Value lhsResult, Value rhsResult)
Public Attributes
DenseMap< Value, Value > equivalentValues
Detailed Description
Definition at line 765 of file OperationSupport.cpp.
Member Function Documentation
checkCommutativeEquivalent()
LogicalResult ValueEquivalenceCache::checkCommutativeEquivalent (ValueRange lhsRange, ValueRange rhsRange) inline
Definition at line 771 of file OperationSupport.cpp.
References b, checkEquivalent(), mlir::Value::getAsOpaquePointer(), and success().
Referenced by mlir::OperationEquivalence::isEquivalentTo(), and mlir::OperationEquivalence::isRegionEquivalentTo().
checkEquivalent()
LogicalResult ValueEquivalenceCache::checkEquivalent (Value lhsValue, Value rhsValue) inline
Definition at line 767 of file OperationSupport.cpp.
References equivalentValues, and success().
Referenced by checkCommutativeEquivalent(), mlir::OperationEquivalence::isEquivalentTo(), and mlir::OperationEquivalence::isRegionEquivalentTo().
markEquivalent()
void ValueEquivalenceCache::markEquivalent (Value lhsResult, Value rhsResult) inline
Definition at line 801 of file OperationSupport.cpp.
References equivalentValues.
Referenced by mlir::OperationEquivalence::isEquivalentTo(), and mlir::OperationEquivalence::isRegionEquivalentTo().
Member Data Documentation
equivalentValues
DenseMap<Value, Value> ValueEquivalenceCache::equivalentValues
Definition at line 766 of file OperationSupport.cpp.
Referenced by checkEquivalent(), and markEquivalent().
The documentation for this struct was generated from the following file:
lib/IR/OperationSupport.cpp