MLIR: pybind11::detail::type_caster< MlirDialectRegistry > Struct Reference
pybind11::detail::type_caster< MlirDialectRegistry > Struct Reference
Casts object <-> MlirDialectRegistry.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirDialectRegistry, _("MlirDialectRegistry"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirDialectRegistry v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirDialectRegistry.
Definition at line 141 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirDialectRegistry >::cast (MlirDialectRegistry v, return_value_policy , handle) inline static
Definition at line 148 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonDialectRegistryToCapsule().
load()
bool pybind11::detail::type_caster< MlirDialectRegistry >::load (handle src, bool) inline
Definition at line 143 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirDialectRegistryIsNull(), and mlirPythonCapsuleToDialectRegistry().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirDialectRegistry >::PYBIND11_TYPE_CASTER (MlirDialectRegistry , _("MlirDialectRegistry"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h