MLIR: mlir::remark::RemarkOpts Struct Reference
mlir::remark::RemarkOpts Struct Reference
Options to create a Remark.
#include "mlir/IR/Remarks.h"
Public Member Functions
RemarkOpts category (StringRef v) const
Return a copy with the category set.
RemarkOpts subCategory (StringRef v) const
Return a copy with the subcategory set.
RemarkOpts function (StringRef v) const
Return a copy with the function name set.
RemarkOpts relatedTo (RemarkId id) const
Link this remark to a previously emitted remark by explicit ID.
RemarkOpts relatedTo (const detail::InFlightRemark &r) const
Link this remark to a related remark that is still in flight.
Static Public Member Functions
static RemarkOpts name (StringRef n)
Public Attributes
StringRef remarkName
StringRef categoryName
StringRef subCategoryName
StringRef functionName
RemarkId relatedId
Link to a related remark by explicit ID.
Detailed Description
Options to create a Remark.
Definition at line 95 of file Remarks.h.
Member Function Documentation
category()
RemarkOpts mlir::remark::RemarkOpts::category (StringRef v) const inline
Return a copy with the category set.
Definition at line 112 of file Remarks.h.
References copy().
function()
RemarkOpts mlir::remark::RemarkOpts::function (StringRef v) const inline
Return a copy with the function name set.
Definition at line 124 of file Remarks.h.
References copy().
name()
RemarkOpts mlir::remark::RemarkOpts::name (StringRef n) inline static
Definition at line 105 of file Remarks.h.
References remarkName.
Referenced by mlir::acc::emitRemark().
relatedTo() [1/2]
mlir::remark::RemarkOpts mlir::remark::RemarkOpts::relatedTo (const detail::InFlightRemark & r) const inline
Link this remark to a related remark that is still in flight.
Extracts the ID from the InFlightRemark.
Definition at line 631 of file Remarks.h.
References mlir::remark::detail::InFlightRemark::getId(), and relatedTo().
relatedTo() [2/2]
RemarkOpts mlir::remark::RemarkOpts::relatedTo (RemarkId id) const inline
Link this remark to a previously emitted remark by explicit ID.
Definition at line 131 of file Remarks.h.
References copy().
Referenced by relatedTo().
subCategory()
RemarkOpts mlir::remark::RemarkOpts::subCategory (StringRef v) const inline
Return a copy with the subcategory set.
Definition at line 118 of file Remarks.h.
References copy().
Member Data Documentation
categoryName
StringRef mlir::remark::RemarkOpts::categoryName
Definition at line 97 of file Remarks.h.
functionName
StringRef mlir::remark::RemarkOpts::functionName
Definition at line 99 of file Remarks.h.
relatedId
RemarkId mlir::remark::RemarkOpts::relatedId
Link to a related remark by explicit ID.
Definition at line 102 of file Remarks.h.
Referenced by mlir::remark::detail::Remark::Remark().
remarkName
StringRef mlir::remark::RemarkOpts::remarkName
Definition at line 96 of file Remarks.h.
Referenced by name().
subCategoryName
StringRef mlir::remark::RemarkOpts::subCategoryName
Definition at line 98 of file Remarks.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/Remarks.h