MLIR: mlir::FunctionCallBuilder Struct Reference
mlir::FunctionCallBuilder Struct Reference
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
Public Member Functions
FunctionCallBuilder (StringRef functionName, Type returnType, ArrayRef< Type > argumentTypes)
LLVM::CallOp create (Location loc, OpBuilder &builder, ArrayRef< Value > arguments) const
Public Attributes
StringRef functionName
LLVM::LLVMFunctionType functionType
Detailed Description
Definition at line 50 of file GPUCommonPass.h.
Constructor & Destructor Documentation
FunctionCallBuilder()
mlir::FunctionCallBuilder::FunctionCallBuilder (StringRef functionName, Type returnType, ArrayRef< Type > argumentTypes) inline
Definition at line 51 of file GPUCommonPass.h.
Member Function Documentation
create()
LLVM::CallOp FunctionCallBuilder::create (Location loc, OpBuilder & builder, ArrayRef< Value > arguments) const
Definition at line 576 of file GPUToLLVMConversion.cpp.
References mlir::OpBuilder::atBlockEnd(), functionName, functionType, mlir::OpBuilder::getBlock(), mlir::Block::getParent(), and mlir::Region::getParentOfType().
Member Data Documentation
functionName
StringRef mlir::FunctionCallBuilder::functionName
Definition at line 58 of file GPUCommonPass.h.
Referenced by create().
functionType
LLVM::LLVMFunctionType mlir::FunctionCallBuilder::functionType
Definition at line 59 of file GPUCommonPass.h.
Referenced by create().
The documentation for this struct was generated from the following files:
include/mlir/Conversion/GPUCommon/GPUCommonPass.h
lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp