MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< CalibratedQuantizedType, QuantizedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "CalibratedQuantizedType"
static const MlirStringRef name = mlirCalibratedQuantizedTypeGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< CalibratedQuantizedType, QuantizedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< CalibratedQuantizedType, QuantizedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< CalibratedQuantizedType, QuantizedType >
PyConcreteType ()=default
Detailed Description
Definition at line 463 of file DialectQuant.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType::bindDerived (ClassTy & c) inline static
Definition at line 473 of file DialectQuant.cpp.
References max(), min(), mlirCalibratedQuantizedTypeGet(), mlirCalibratedQuantizedTypeGetMax(), and mlirCalibratedQuantizedTypeGetMin().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType::getTypeIdFunction static constexpr
Initial value:
=
      mlirCalibratedQuantizedTypeGetTypeID
Definition at line 467 of file DialectQuant.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType::isaFunction static constexpr
Initial value:
=
      mlirTypeIsACalibratedQuantizedType
Definition at line 465 of file DialectQuant.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType::name = mlirCalibratedQuantizedTypeGetName() inline static
Definition at line 470 of file DialectQuant.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::CalibratedQuantizedType::pyClassName = "CalibratedQuantizedType" static constexpr
Definition at line 469 of file DialectQuant.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectQuant.cpp