MLIR: mlir::Pass::ListOption< DataType, OptionParser > Struct Template Reference
mlir::Pass::ListOption< DataType, OptionParser > Struct Template Reference
This class represents a specific pass option that contains a list of values of the provided data type.
#include "mlir/Pass/Pass.h"
Public Member Functions
template<typename... Args>
ListOption (Pass &parent, StringRef arg, Args &&...args)
Public Member Functions inherited from mlir::detail::PassOptions::ListOption< DataType, OptionParser >
template<typename... Args>
ListOption (PassOptions &parent, StringRef arg, Args &&...args)
~ListOption () override=default
ListOption< DataType, OptionParser > & operator= (const ListOption< DataType, OptionParser > &other)
bool handleOccurrence (unsigned pos, StringRef argName, StringRef arg) override
ListOption< DataType, OptionParser > & operator= (ArrayRef< DataType > values)
Allow assigning from an ArrayRef.
MutableArrayRef< DataType > operator* ()
Allow accessing the data held by this option.
ArrayRef< DataType > operator* () const
Detailed Description
template<typename DataType, typename OptionParser = detail::PassOptions::OptionParser<DataType>>
struct mlir::Pass::ListOption< DataType, OptionParser >
This class represents a specific pass option that contains a list of values of the provided data type.
Definition at line 104 of file Pass.h.
Constructor & Destructor Documentation
ListOption()
template<typename DataType, typename OptionParser = detail::PassOptions::OptionParser<DataType>> template<typename... Args> mlir::Pass::ListOption< DataType, OptionParser >::ListOption (Pass & parent, StringRef arg, Args &&... args) inline
Definition at line 107 of file Pass.h.
References ListOption(), and mlir::Pass::Pass().
Referenced by ListOption().
The documentation for this struct was generated from the following file:
include/mlir/Pass/Pass.h