MLIR: mlir::OperationState Struct Reference
mlir::OperationState Struct Reference
This represents an operation in an abstracted form, suitable for use with the builder APIs.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OperationState (Location location, StringRef name)
OperationState (Location location, OperationName name)
OperationState (Location location, StringRef name, ValueRange operands, TypeRange types, ArrayRef< NamedAttribute > attributes, BlockRange successors={}, MutableArrayRef< std::unique_ptr< Region >> regions={})
void addOperands (ValueRange newOperands)
void addTypes (ArrayRef< Type > newTypes)
template<typename RangeT >
std::enable_if_t<!std::is_convertible< RangeT, ArrayRef< Type > >::value > addTypes (RangeT &&newTypes)
void addAttribute (StringRef name, Attribute attr)
Add an attribute with the specified name.
void addAttribute (Identifier name, Attribute attr)
Add an attribute with the specified name.
void addAttributes (ArrayRef< NamedAttribute > newAttributes)
Add an array of named attributes.
void addSuccessors (Block *successor)
void addSuccessors (BlockRange newSuccessors)
Region * addRegion ()
Create a region that should be attached to the operation.
void addRegion (std::unique_ptr< Region > &&region)
Take a region that should be attached to the Operation.
void addRegions (MutableArrayRef< std::unique_ptr< Region >> regions)
Take ownership of a set of regions that should be attached to the Operation.
MLIRContext * getContext () const
Get the context held by this operation state.
Public Attributes
Location location
OperationName name
SmallVector< Value, 4 > operands
SmallVector< Type, 4 > types
Types of the results of this operation.
NamedAttrList attributes
SmallVector< Block *, 1 > successors
Successors of this operation and their respective operands.
SmallVector< std::unique_ptr< Region >, 1 > regions
Regions that the op will hold.
Detailed Description
This represents an operation in an abstracted form, suitable for use with the builder APIs.
This object is a large and heavy weight object meant to be used as a temporary object on the stack. It is generally unwise to put this in a collection.
Definition at line 446 of file OperationSupport.h.
Constructor & Destructor Documentation
OperationState() [1/3]
OperationState::OperationState (Location location, StringRef name)
Definition at line 179 of file OperationSupport.cpp.
OperationState() [2/3]
OperationState::OperationState (Location location, OperationName name)
Definition at line 182 of file OperationSupport.cpp.
OperationState() [3/3]
OperationState::OperationState (Location location, StringRef name, ValueRange operands, TypeRange types, ArrayRef< NamedAttribute > attributes, BlockRange successors = {}, MutableArrayRef< std::unique_ptr< Region >> regions = {})
Definition at line 185 of file OperationSupport.cpp.
References regions.
Member Function Documentation
addAttribute() [1/2]
void mlir::OperationState::addAttribute (StringRef name, Attribute attr) inline
Add an attribute with the specified name.
Definition at line 480 of file OperationSupport.h.
Referenced by addArgAndResultAttrsImpl(), mlir::AffineDmaStartOp::build(), mlir::AffineDmaWaitOp::build(), buildAvgPool2dOpWithQuantInfo(), buildCmpFOp(), buildCmpIOp(), buildConvOpWithQuantInfo(), buildFCOpWithQuantInfo(), buildMatMulOpWithQuantInfo(), buildPadOpWithQuantInfo(), buildScalableCmpFOp(), buildScalableCmpIOp(), buildTransConvOpWithQuantInfo(), buildUnaryOpWithQuantInfo(), computeReshapeCollapsedType(), computeTensorReshapeCollapsedType(), mlir::AffineDmaWaitOp::fold(), foldMemRefCastInTiledLoopOp(), foldTransferInBoundsAttribute(), getUnnamedAddrAttrName(), mlir::vector::getVectorReductionOp(), mlir::vector::getVectorSubscriptAttr(), inferExtractOpResultType(), inferStridedSliceOpResultType(), inferTransposeResultType(), mlir::detail::PDLByteCode::initializeMutableState(), mlirOperationCreate(), parseAffineForOp(), parseAffineMapWithMinMax(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAtomicBinOp(), parseAtomicOrdering(), parseBound(), parseBranchConditionalOp(), parseCommonStructuredOpParts(), parseConstShapeOp(), parseContractionOp(), parseControlAttribute(), parseEntryPointOp(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseExecuteOp(), parseExecutionModeOp(), parseFenceOp(), parseFuncOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseIncludeOp(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseLLVMFuncOp(), parseLoadOp(), parseLoopOp(), parseOptionalLLVMKeyword(), parseParallelOp(), parsePrefetchOp(), mlir::parseReshapeLikeOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantCompositeOp(), parseStoreOp(), parseTiledLoopOp(), parseTransferReadOp(), parseTransposeOp(), parseVariableOp(), parseWsLoopOp(), print(), printLaunchFuncOperands(), verify(), and verifyReductionOp().
addAttribute() [2/2]
void mlir::OperationState::addAttribute (Identifier name, Attribute attr) inline
Add an attribute with the specified name.
Definition at line 485 of file OperationSupport.h.
addAttributes()
void mlir::OperationState::addAttributes (ArrayRef< NamedAttribute > newAttributes) inline
Add an array of named attributes.
Definition at line 490 of file OperationSupport.h.
Referenced by extractOpcode(), foldIdentityOffsetSizeAndStrideOpInterface(), foldMemRefCastInTiledLoopOp(), getOrCreateOperandsMatchingResultTypes(), CastAwayElementwiseLeadingOneDim::matchAndRewrite(), parseCallOp(), parseExecuteOp(), printLaunchFuncOperands(), vectorizeOneOp(), verify(), and verifyReductionOp().
addOperands()
void OperationState::addOperands (ValueRange newOperands)
Definition at line 199 of file OperationSupport.cpp.
References operands.
Referenced by mlir::gpu::addAsyncDependency(), mlir::AffineDmaStartOp::build(), mlir::memref::DmaStartOp::build(), mlir::memref::DmaWaitOp::build(), mlir::AffineDmaWaitOp::build(), buildAvgPool2dOpWithQuantInfo(), mlir::impl::buildBinaryOp(), mlir::impl::buildCastOp(), buildCmpFOp(), buildCmpIOp(), buildConvOpWithQuantInfo(), buildFCOpWithQuantInfo(), buildLogicalBinaryOp(), buildLogicalUnaryOp(), mlir::scf::buildLoopNest(), buildMatMulOpWithQuantInfo(), buildPadOpWithQuantInfo(), buildScalableCmpFOp(), buildScalableCmpIOp(), buildTransConvOpWithQuantInfo(), buildUnaryOpWithQuantInfo(), extractOpcode(), mlir::AffineDmaWaitOp::fold(), foldMemRefCastInTiledLoopOp(), foldTransferInBoundsAttribute(), getLLVMAtomicOrdering(), mlir::scf::getParallelForInductionVarOwner(), mlir::getReductionOp(), mlir::vector::getVectorReductionOp(), mlir::vector::getVectorSubscriptAttr(), inferExtractOpResultType(), inferStridedSliceOpResultType(), isMemRefNormalizable(), MultiBlockExecuteInliner::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), mlirOperationCreate(), parseBranchConditionalOp(), parseInvokeOp(), parseLaunchOp(), parseShuffleOp(), print(), verify(), and verifyReductionOp().
addRegion() [1/2]
Region * OperationState::addRegion ()
Create a region that should be attached to the operation.
These regions can be filled in immediately without waiting for Operation to be created. When it is, the region bodies will be transferred.
Definition at line 207 of file OperationSupport.cpp.
References regions.
Referenced by mlir::gpu::addAsyncDependency(), addRegions(), mlir::scf::buildLoopNest(), createAndFillStructuredOpRegion(), mlir::AffineDmaWaitOp::fold(), foldMemRefCastInTiledLoopOp(), mlir::scf::getParallelForInductionVarOwner(), mlir::getReductionOp(), getUnnamedAddrAttrName(), MultiBlockExecuteInliner::matchAndRewrite(), mlirOperationCreate(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAllocaScopeOp(), parseAssumingOp(), parseExecuteOp(), parseExecuteRegionOp(), parseForOp(), parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseIfOp(), parseLaunchOp(), parseLLVMFuncOp(), parseLoopOp(), parseModuleOp(), parseNamedStructuredOp(), parseParallelOp(), parseReduceOp(), parseRegions(), parseSelectionOp(), parseShuffleVectorOp(), parseSpecConstantOperationOp(), parseTiledLoopOp(), parseWsLoopOp(), print(), printLaunchFuncOperands(), verify(), and verifyReductionOp().
addRegion() [2/2]
void OperationState::addRegion (std::unique_ptr< Region > && region)
Take a region that should be attached to the Operation.
The body of the region will be transferred when the Operation is constructed. If the region is null, a new empty region will be attached to the Operation.
Definition at line 212 of file OperationSupport.cpp.
References regions.
addRegions()
void OperationState::addRegions (MutableArrayRef< std::unique_ptr< Region >> regions)
Take ownership of a set of regions that should be attached to the Operation.
Definition at line 216 of file OperationSupport.cpp.
References addRegion(), and regions.
addSuccessors() [1/2]
void mlir::OperationState::addSuccessors (Block * successor) inline
Definition at line 494 of file OperationSupport.h.
Referenced by mlirOperationCreate(), parseBranchConditionalOp(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), and parseInvokeOp().
addSuccessors() [2/2]
void OperationState::addSuccessors (BlockRange newSuccessors)
Definition at line 203 of file OperationSupport.cpp.
References successors.
addTypes() [1/2]
void mlir::OperationState::addTypes (ArrayRef< Type > newTypes) inline
Definition at line 470 of file OperationSupport.h.
References value.
Referenced by mlir::impl::buildCastOp(), buildConvOpWithQuantInfo(), buildFCOpWithQuantInfo(), buildLogicalBinaryOp(), buildLogicalUnaryOp(), mlir::scf::buildLoopNest(), buildMatMulOpWithQuantInfo(), buildTransConvOpWithQuantInfo(), diag(), extractOpcode(), mlir::AffineDmaWaitOp::fold(), foldTransferInBoundsAttribute(), getLLVMAtomicOrdering(), mlir::getReductionOp(), mlir::vector::getVectorReductionOp(), mlir::vector::getVectorSubscriptAttr(), inferExtractOpResultType(), inferStridedSliceOpResultType(), MultiBlockExecuteInliner::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), mlirOperationCreate(), mlir::LLVM::detail::oneToOneRewrite(), parseAccessChainOp(), parseAllocaOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseCallOp(), parseCmpOp(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCooperativeMatrixLoadNVOp(), parseExtractElementOp(), parseExtractValueOp(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), parseGenericOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseNamedStructuredOp(), mlir::parseReshapeLikeOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantOperationOp(), parseSubgroupBlockReadINTELOp(), parseTiledLoopOp(), parseUnaryOp(), parseVariableOp(), parseWMMAMmaF16F16M16N16K16Op(), print(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), and verifyReductionOp().
addTypes() [2/2]
template<typename RangeT > std::enable_if_t<!std::is_convertible<RangeT, ArrayRef<Type> >::value> mlir::OperationState::addTypes (RangeT && newTypes) inline
Definition at line 475 of file OperationSupport.h.
getContext()
MLIRContext* mlir::OperationState::getContext () const inline
Get the context held by this operation state.
Definition at line 512 of file OperationSupport.h.
References mlir::Attribute::getContext().
Referenced by mlir::Operation::create(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), parseContractionOp(), parseExecuteOp(), and parseOuterProductOp().
Member Data Documentation
attributes
NamedAttrList mlir::OperationState::attributes
Definition at line 452 of file OperationSupport.h.
Referenced by mlir::Operation::create(), foldTransferInBoundsAttribute(), getUnnamedAddrAttrName(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), mlirOperationCreate(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMapWithMinMax(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseBound(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCommonStructuredOpParts(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseCopyMemoryOp(), parseEntryPointOp(), parseExecuteRegionOp(), parseExecutionModeOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), parseForOp(), parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseIfOp(), parseIncludeOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLaunchOp(), parseLLVMFuncOp(), parseLoadOp(), parseLoopOp(), parseMemoryAccessAttributes(), parseModuleOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), mlir::parseReshapeLikeOp(), parseReturnOp(), parseSelectOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSourceMemoryAccessAttributes(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseSpecConstantOperationOp(), parseStoreOp(), parseTiledLoopOp(), parseTransferReadOp(), parseTransposeOp(), parseVariableDecorations(), parseViewOp(), parseWMMAMmaF16F16M16N16K16Op(), parseYieldOp(), print(), and verify().
location
Location mlir::OperationState::location
Definition at line 447 of file OperationSupport.h.
Referenced by mlir::scf::buildLoopNest(), mlir::Operation::create(), mlir::AffineDmaWaitOp::fold(), getElementPtrType(), mlir::scf::getParallelForInductionVarOwner(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), joinShapes(), MultiBlockExecuteInliner::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), parseAccessChainOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAllocaScopeOp(), parseAssumingOp(), parseForOp(), parseGPUModuleOp(), parseIfOp(), parseParallelOp(), parseShuffleOp(), parseSpecConstantOperationOp(), print(), verify(), and verifyTransferOp().
name
OperationName mlir::OperationState::name
Definition at line 448 of file OperationSupport.h.
Referenced by mlir::Operation::create(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), parseParallelOp(), and parseWsLoopOp().
operands
SmallVector<Value, 4> mlir::OperationState::operands
Definition at line 449 of file OperationSupport.h.
Referenced by addOperands(), mlir::Operation::create(), foldTransferInBoundsAttribute(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), mlir::memref::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::memref::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMapWithMinMax(), parseAffineMinMaxOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicRMWOp(), parseAtomicUpdateOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseExecuteOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandAndType(), parseOperandList(), parseOptionalOperand(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), mlir::parseReshapeLikeOp(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), parseTiledLoopOp(), parseTransferReadOp(), parseTransposeOp(), parseUnaryOp(), parseVariableOp(), parseViewOp(), parseWMMAMmaF16F16M16N16K16Op(), parseWsLoopOp(), parseYieldOp(), mlir::replaceAllMemRefUsesWith(), and verify().
regions
SmallVector<std::unique_ptr<Region>, 1> mlir::OperationState::regions
Regions that the op will hold.
Definition at line 456 of file OperationSupport.h.
Referenced by addRegion(), addRegions(), mlir::Operation::create(), foldMemRefCastInTiledLoopOp(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), OperationState(), parseAffineIfOp(), parseAllocaScopeOp(), parseAssumingOp(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), parseIfOp(), and verify().
successors
SmallVector<Block *, 1> mlir::OperationState::successors
Successors of this operation and their respective operands.
Definition at line 454 of file OperationSupport.h.
Referenced by addSuccessors(), and mlir::Operation::create().
types
SmallVector<Type, 4> mlir::OperationState::types
Types of the results of this operation.
Definition at line 451 of file OperationSupport.h.
Referenced by buildAvgPool2dOpWithQuantInfo(), mlir::impl::buildBinaryOp(), buildCmpFOp(), buildCmpIOp(), buildPadOpWithQuantInfo(), buildScalableCmpFOp(), buildScalableCmpIOp(), buildUnaryOpWithQuantInfo(), mlir::Operation::create(), foldTransferInBoundsAttribute(), inferOperationTypes(), mlir::detail::PDLByteCode::initializeMutableState(), mlirOperationCreate(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffineVectorLoadOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), mlir::impl::parseCastOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseExecuteOp(), parseExecuteRegionOp(), parseExtractOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseLoopOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parseReduceOp(), parseReductionOp(), parseROCDLMubufLoadOp(), parseShuffleOp(), parseTransferReadOp(), parseTransposeOp(), parseViewOp(), print(), and verify().
The documentation for this struct was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp