MLIR: mlir::detail::constant_int_op_binder Struct Reference
mlir::detail::constant_int_op_binder Struct Reference
The matcher that matches a constant scalar / vector splat / tensor splat integer operation and binds the constant integer value.
#include "mlir/IR/Matchers.h"
Public Member Functions
constant_int_op_binder (IntegerAttr::ValueType *bv)
Creates a matcher instance that binds the value to bv if match succeeds.
bool match (Operation *op)
Public Attributes
IntegerAttr::ValueType * bind_value
Detailed Description
The matcher that matches a constant scalar / vector splat / tensor splat integer operation and binds the constant integer value.
Definition at line 96 of file Matchers.h.
Constructor & Destructor Documentation
constant_int_op_binder()
mlir::detail::constant_int_op_binder::constant_int_op_binder (IntegerAttr::ValueType * bv) inline
Creates a matcher instance that binds the value to bv if match succeeds.
Definition at line 100 of file Matchers.h.
Member Function Documentation
match()
bool mlir::detail::constant_int_op_binder::match (Operation * op) inline
Definition at line 102 of file Matchers.h.
References mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::bind_value, mlir::Attribute::dyn_cast(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::match().
Referenced by mlir::detail::constant_int_value_matcher< TargetValue >::match(), and mlir::detail::constant_int_not_value_matcher< TargetNotValue >::match().
Member Data Documentation
bind_value
IntegerAttr::ValueType* mlir::detail::constant_int_op_binder::bind_value
Definition at line 97 of file Matchers.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h