MLIR: llvm::DenseMapInfo< MlirTypeID > Struct Reference
llvm::DenseMapInfo< MlirTypeID > Struct Reference
#include "Bindings/Python/NanobindUtils.h"
Static Public Member Functions
static MlirTypeID getEmptyKey ()
static MlirTypeID getTombstoneKey ()
static unsigned getHashValue (const MlirTypeID &val)
static bool isEqual (const MlirTypeID &lhs, const MlirTypeID &rhs)
Detailed Description
Definition at line 409 of file NanobindUtils.h.
Member Function Documentation
getEmptyKey()
static MlirTypeID llvm::DenseMapInfo< MlirTypeID >::getEmptyKey () inline static
Definition at line 410 of file NanobindUtils.h.
References mlirTypeIDCreate().
getHashValue()
static unsigned llvm::DenseMapInfo< MlirTypeID >::getHashValue (const MlirTypeID & val) inline static
Definition at line 418 of file NanobindUtils.h.
References mlirTypeIDHashValue().
getTombstoneKey()
static MlirTypeID llvm::DenseMapInfo< MlirTypeID >::getTombstoneKey () inline static
Definition at line 414 of file NanobindUtils.h.
References mlirTypeIDCreate().
isEqual()
static bool llvm::DenseMapInfo< MlirTypeID >::isEqual (const MlirTypeID & lhs, const MlirTypeID & rhs) inline static
Definition at line 421 of file NanobindUtils.h.
References mlirTypeIDEqual().
The documentation for this struct was generated from the following file:
lib/Bindings/Python/NanobindUtils.h