MLIR: mlir::GPUDynamicSharedMemoryOpLowering Struct Reference
mlir::GPUDynamicSharedMemoryOpLowering Struct Reference
Lowering for gpu.dynamic.shared.memory to LLVM dialect.
#include "Conversion/GPUCommon/GPUOpsLowering.h"
Public Member Functions
GPUDynamicSharedMemoryOpLowering (const LLVMTypeConverter &converter, unsigned alignmentBit=0, PatternBenefit benefit=1)
LogicalResult matchAndRewrite (gpu::DynamicSharedMemoryOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Methods that operate on the SourceOp type.
Public Member Functions inherited from mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >
ConvertOpToLLVMPattern (const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
virtual LogicalResult matchAndRewrite (gpu::DynamicSharedMemoryOp op, OneToNOpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
Public Member Functions inherited from mlir::ConvertToLLVMPattern
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::ConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
const TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, const ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Public Types inherited from mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >
using OpAdaptor = typename SourceOp::Adaptor
using OneToNOpAdaptor = typename SourceOp::template GenericAdaptor< ArrayRef< ValueRange > >
Public Types inherited from mlir::ConversionPattern
using OpAdaptor = ArrayRef< Value >
using OneToNOpAdaptor = ArrayRef< ValueRange >
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::ConvertToLLVMPattern
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
const LLVMTypeConverter * getTypeConverter () const
Type getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Type getIntPtrType (unsigned addressSpace=0) const
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
Type getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
Type getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Type getPtrType (unsigned addressSpace=0) const
Get the MLIR type wrapping the LLVM ptr type.
Value getStridedElementPtr (ConversionPatternRewriter &rewriter, Location loc, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags=LLVM::GEPNoWrapFlags::none) const
Convenience wrapper for the corresponding helper utility.
bool isConvertibleAndHasIdentityMaps (MemRefType type) const
Returns if the given memref type is convertible to LLVM and has an identity layout map.
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &strides, Value &size, bool sizeInBytes=true) const
Computes sizes, strides and buffer size of memRefType with identity layout.
Value getSizeInBytes (Location loc, Type type, ConversionPatternRewriter &rewriter) const
Computes the size of type in bytes.
Value getNumElements (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter) const
Computes total number of elements for the given MemRef and dynamicSizes.
MemRefDescriptor createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter &rewriter) const
Creates and populates a canonical memref descriptor struct.
LogicalResult copyUnrankedDescriptors (OpBuilder &builder, Location loc, TypeRange origTypes, SmallVectorImpl< Value > &operands, bool toDynamic) const
Copies the memory descriptor for any operands that were unranked descriptors originally to heap-allocated memory (if toDynamic is true) or to stack-allocated memory (otherwise).
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
See ConversionPattern::ConversionPattern for information on the other available constructors.
Protected Member Functions inherited from mlir::ConversionPattern
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
SmallVector< Value > getOneToOneAdaptorOperands (ArrayRef< ValueRange > operands) const
Given an array of value ranges, which are the inputs to a 1:N adaptor, try to extract the single value of each range to construct a the inputs for a 1:1 adaptor.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Static Protected Member Functions inherited from mlir::ConvertToLLVMPattern
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
Create a constant Op producing a value of resultType from an index-typed integer attribute.
Protected Attributes inherited from mlir::ConversionPattern
const TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
Lowering for gpu.dynamic.shared.memory to LLVM dialect.
The pattern first create a 0-sized global array symbol similar as LLVM expects. It constructs a memref descriptor with these values and return it.
Definition at line 41 of file GPUOpsLowering.h.
Constructor & Destructor Documentation
GPUDynamicSharedMemoryOpLowering()
mlir::GPUDynamicSharedMemoryOpLowering::GPUDynamicSharedMemoryOpLowering (const LLVMTypeConverter & converter, unsigned alignmentBit = 0, PatternBenefit benefit = 1) inline
Definition at line 45 of file GPUOpsLowering.h.
Member Function Documentation
matchAndRewrite()
LogicalResult GPUDynamicSharedMemoryOpLowering::matchAndRewrite (gpu::DynamicSharedMemoryOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const override virtual
Methods that operate on the SourceOp type.
One of these must be overridden by the derived pattern class.
Reimplemented from mlir::ConvertOpToLLVMPattern< gpu::DynamicSharedMemoryOp >.
Definition at line 717 of file GPUOpsLowering.cpp.
References mlir::TypeConverter::convertType(), mlir::ConvertToLLVMPattern::createMemRefDescriptor(), mlir::get(), getDynamicSharedMemorySymbol(), mlir::ConvertToLLVMPattern::getMemRefDescriptorSizes(), mlir::ConvertToLLVMPattern::getTypeConverter(), mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::setInsertionPoint(), and mlir::ConversionPattern::typeConverter.
The documentation for this struct was generated from the following files:
lib/Conversion/GPUCommon/GPUOpsLowering.h
lib/Conversion/GPUCommon/GPUOpsLowering.cpp