MLIR: mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy Struct Reference
mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Public Member Functions
KeyTy (Type expressedType, double min, double max)
bool operator== (const KeyTy &other) const
unsigned getHashValue () const
Static Public Member Functions
template<typename T, typename U>
static bool genericIsEqual (const T &lhs, const U &rhs)
Public Attributes
Type expressedType
double min
double max
Detailed Description
Definition at line 376 of file TypeDetail.h.
Constructor & Destructor Documentation
KeyTy()
mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::KeyTy (Type expressedType, double min, double max) inline
Definition at line 377 of file TypeDetail.h.
References expressedType, max, and min.
Referenced by operator==().
Member Function Documentation
genericIsEqual()
template<typename T, typename U> bool mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::genericIsEqual (const T & lhs, const U & rhs) inline static
Definition at line 388 of file TypeDetail.h.
References lhs, and rhs.
Referenced by operator==(), and mlir::quant::detail::CalibratedQuantizedTypeStorage::operator==().
getHashValue()
unsigned mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::getHashValue () const inline
Definition at line 397 of file TypeDetail.h.
References expressedType, max, and min.
Referenced by mlir::quant::detail::CalibratedQuantizedTypeStorage::hashKey().
operator==()
bool mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::operator== (const KeyTy & other) const inline
Definition at line 393 of file TypeDetail.h.
References genericIsEqual(), and KeyTy().
Member Data Documentation
expressedType
Type mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::expressedType
Definition at line 380 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
max
double mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::max
Definition at line 383 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
min
double mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::min
Definition at line 382 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h