MLIR: mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy Struct Reference
mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Public Member Functions
KeyTy (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
bool operator== (const KeyTy &other) const
unsigned getHashValue () const
Static Public Member Functions
template<typename T, typename U>
static bool genericIsEqual (const T &lhs, const U &rhs)
Public Attributes
unsigned flags
Type storageType
Type expressedType
int64_t storageTypeMin
int64_t storageTypeMax
Detailed Description
Definition at line 47 of file TypeDetail.h.
Constructor & Destructor Documentation
KeyTy()
mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::KeyTy (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax) inline
Definition at line 48 of file TypeDetail.h.
References expressedType, flags, storageType, storageTypeMax, and storageTypeMin.
Referenced by operator==().
Member Function Documentation
genericIsEqual()
template<typename T, typename U> bool mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::genericIsEqual (const T & lhs, const U & rhs) inline static
Definition at line 61 of file TypeDetail.h.
References lhs, and rhs.
Referenced by operator==(), and mlir::quant::detail::AnyQuantizedTypeStorage::operator==().
getHashValue()
unsigned mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::getHashValue () const inline
Definition at line 72 of file TypeDetail.h.
References expressedType, flags, storageType, storageTypeMax, and storageTypeMin.
Referenced by mlir::quant::detail::AnyQuantizedTypeStorage::hashKey().
operator==()
bool mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::operator== (const KeyTy & other) const inline
Definition at line 68 of file TypeDetail.h.
References genericIsEqual(), and KeyTy().
Member Data Documentation
expressedType
Type mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::expressedType
Definition at line 54 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
flags
unsigned mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::flags
Definition at line 52 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
storageType
Type mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::storageType
Definition at line 53 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
storageTypeMax
int64_t mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::storageTypeMax
Definition at line 56 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
storageTypeMin
int64_t mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::storageTypeMin
Definition at line 55 of file TypeDetail.h.
Referenced by getHashValue(), and KeyTy().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h