MLIR: mlir::xegpu::uArch::BlockIOInstructionInterface Struct Reference
mlir::xegpu::uArch::BlockIOInstructionInterface Struct Reference abstract
#include "mlir/Dialect/XeGPU/uArch/uArchBase.h"
Public Types
using BlockShapes
Public Member Functions
std::optional< BlockShapes > getBlockWidthHeightCount (Type elemTy, bool hasTransform=false, bool hasTranspose=false, bool upConv=false) const
virtual int32_t getPackedFormatBitSize () const =0
virtual ~BlockIOInstructionInterface ()=default
Protected Member Functions
virtual std::optional< BlockShapes > computeBlockWidthHeightCount (Type elemTy, bool hasTransform, bool hasTranspose, bool upConv) const =0
Detailed Description
Definition at line 168 of file uArchBase.h.
Member Typedef Documentation
BlockShapes
using mlir::xegpu::uArch::BlockIOInstructionInterface::BlockShapes
Initial value:
      std::tuple<llvm::ArrayRef<int>, llvm::ArrayRef<int>, llvm::ArrayRef<int>>
Definition at line 169 of file uArchBase.h.
Constructor & Destructor Documentation
~BlockIOInstructionInterface()
virtual mlir::xegpu::uArch::BlockIOInstructionInterface::~BlockIOInstructionInterface () virtual default
Member Function Documentation
computeBlockWidthHeightCount()
virtual std::optional< BlockShapes > mlir::xegpu::uArch::BlockIOInstructionInterface::computeBlockWidthHeightCount (Type elemTy, bool hasTransform, bool hasTranspose, bool upConv) const protected pure virtual
Implemented in mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction, mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction, and mlir::xegpu::uArch::Subgroup2DBlockStoreInstruction.
Referenced by getBlockWidthHeightCount().
getBlockWidthHeightCount()
std::optional< BlockShapes > mlir::xegpu::uArch::BlockIOInstructionInterface::getBlockWidthHeightCount (Type elemTy, bool hasTransform = false, bool hasTranspose = false, bool upConv = false) const inline
Definition at line 175 of file uArchBase.h.
References computeBlockWidthHeightCount().
Referenced by get2DBlockIOInstDataLayout().
getPackedFormatBitSize()
virtual int32_t mlir::xegpu::uArch::BlockIOInstructionInterface::getPackedFormatBitSize () const pure virtual
Implemented in mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction, mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction, and mlir::xegpu::uArch::Subgroup2DBlockStoreInstruction.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/uArchBase.h