MLIR: mlir::detail::infer_int_range_op_binder Struct Reference
mlir::detail::infer_int_range_op_binder Struct Reference
A matcher that matches operations that implement the InferIntRangeInterface interface, and binds the inferred range.
#include "mlir/IR/Matchers.h"
Public Member Functions
infer_int_range_op_binder (IntegerValueRange *bind_value)
bool match (Operation *op)
Public Attributes
IntegerValueRange * bind_value
Detailed Description
A matcher that matches operations that implement the InferIntRangeInterface interface, and binds the inferred range.
Definition at line 106 of file Matchers.h.
Constructor & Destructor Documentation
infer_int_range_op_binder()
mlir::detail::infer_int_range_op_binder::infer_int_range_op_binder (IntegerValueRange * bind_value) inline explicit
Definition at line 109 of file Matchers.h.
References bind_value.
Member Function Documentation
match()
bool mlir::detail::infer_int_range_op_binder::match (Operation * op) inline
Definition at line 112 of file Matchers.h.
References bind_value, mlir::IntegerValueRange::getMaxRange(), mlir::Operation::getOperands(), and mlir::Operation::getResult().
Referenced by mlir::detail::constant_int_range_predicate_matcher::match().
Member Data Documentation
bind_value
IntegerValueRange* mlir::detail::infer_int_range_op_binder::bind_value
Definition at line 107 of file Matchers.h.
Referenced by infer_int_range_op_binder(), and match().
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h