MLIR: mlir::dataflow::RunLivenessAnalysis Struct Reference
mlir::dataflow::RunLivenessAnalysis Struct Reference
Runs liveness analysis on the IR defined by op.
#include "mlir/Analysis/DataFlow/LivenessAnalysis.h"
Public Member Functions
RunLivenessAnalysis (Operation *op)
const Liveness * getLiveness (Value val)
Detailed Description
Runs liveness analysis on the IR defined by op.
Definition at line 97 of file LivenessAnalysis.h.
Constructor & Destructor Documentation
RunLivenessAnalysis()
RunLivenessAnalysis::RunLivenessAnalysis (Operation * op)
Definition at line 322 of file LivenessAnalysis.cpp.
References getLiveness(), mlir::Operation::getName(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::dataflow::loadBaselineAnalyses(), result, and mlir::Operation::walk().
Member Function Documentation
getLiveness()
const Liveness * RunLivenessAnalysis::getLiveness (Value val)
Definition at line 358 of file LivenessAnalysis.cpp.
Referenced by RunLivenessAnalysis().
The documentation for this struct was generated from the following files:
include/mlir/Analysis/DataFlow/LivenessAnalysis.h
lib/Analysis/DataFlow/LivenessAnalysis.cpp