MLIR: mlir::bufferization::func_ext::CallOpInterface Struct Reference
mlir::bufferization::func_ext::CallOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
AliasingValueList getAliasingValues (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
FailureOr< BufferLikeType > getBufferType (Operation *op, Value value, const BufferizationOptions &options, const BufferizationState &state, SmallVector< Value > &invocationStack) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationOptions &options, BufferizationState &state) const
All function arguments are writable.
Detailed Description
Definition at line 160 of file FuncBufferizableOpInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::bufferization::func_ext::CallOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationOptions & options, BufferizationState & state) const inline
All function arguments are writable.
It is the responsibility of the CallOp to insert buffer copies where necessary.
Definition at line 255 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::castOrReallocMemRefValue(), mlir::bufferization::func_ext::getCalledFunction(), mlir::Operation::getResults(), mlir::Value::getType(), options, replacement(), result, mlir::Operation::setAttrs(), and success().
bufferizesToMemoryRead()
bool mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 163 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and mlir::bufferization::func_ext::FuncAnalysisState::readBbArgs.
bufferizesToMemoryWrite()
bool mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 178 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and mlir::bufferization::func_ext::FuncAnalysisState::writtenBbArgs.
getAliasingValues()
AliasingValueList mlir::bufferization::func_ext::CallOpInterface::getAliasingValues (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 193 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::aliasingReturnVals, mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getEquivalentFuncArgIdx(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and result.
getBufferType()
FailureOr< BufferLikeType > mlir::bufferization::func_ext::CallOpInterface::getBufferType (Operation * op, Value value, const BufferizationOptions & options, const BufferizationState & state, SmallVector< Value > & invocationStack) const inline
Definition at line 227 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getDefaultMemorySpace(), and options.
The documentation for this struct was generated from the following file:
lib/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.cpp