MLIR: mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction Struct Reference
mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction Struct Reference
#include "mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h"
Public Member Functions
Subgroup2DBlockPrefetchInstruction ()
std::optional< std::tuple< llvm::ArrayRef< int >, llvm::ArrayRef< int >, llvm::ArrayRef< int > > > getBlockWidthHeightCount (Type elemTy) const
int32_t getPackedFormatBitSize () const
Public Member Functions inherited from mlir::xegpu::uArch::Instruction
Instruction (InstructionKind kind, InstructionScope scope)
~Instruction ()=default
InstructionKind getInstructionKind () const
InstructionScope getScope () const
Static Public Member Functions
static bool classof (const Instruction *B)
Static Public Member Functions inherited from mlir::xegpu::uArch::Instruction
static llvm::StringRef toString (InstructionKind instKind)
static std::optional< InstructionKind > parseInstructionKind (llvm::StringRef str)
Additional Inherited Members
Protected Attributes inherited from mlir::xegpu::uArch::Instruction
const InstructionKind instKind
const InstructionScope scope
Detailed Description
Definition at line 132 of file IntelGpuXe2.h.
Constructor & Destructor Documentation
Subgroup2DBlockPrefetchInstruction()
mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction::Subgroup2DBlockPrefetchInstruction () inline
Definition at line 133 of file IntelGpuXe2.h.
References mlir::xegpu::uArch::Instruction::Instruction(), mlir::xegpu::uArch::Subgroup, and mlir::xegpu::uArch::Subgroup2DBlockPrefetch.
Member Function Documentation
classof()
bool mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction::classof (const Instruction * B) inline static
Definition at line 136 of file IntelGpuXe2.h.
References mlir::xegpu::uArch::Instruction::Instruction(), and mlir::xegpu::uArch::Subgroup2DBlockPrefetch.
getBlockWidthHeightCount()
std::optional< std::tuple< llvm::ArrayRef< int >, llvm::ArrayRef< int >, llvm::ArrayRef< int > > > mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction::getBlockWidthHeightCount (Type elemTy) const inline
Definition at line 143 of file IntelGpuXe2.h.
References mlir::Type::getIntOrFloatBitWidth().
getPackedFormatBitSize()
int32_t mlir::xegpu::uArch::Subgroup2DBlockPrefetchInstruction::getPackedFormatBitSize () const inline
Definition at line 167 of file IntelGpuXe2.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h