MLIR: pybind11::detail::type_caster< MlirAffineMap > Struct Reference
pybind11::detail::type_caster< MlirAffineMap > Struct Reference
Casts object <-> MlirAffineMap.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirAffineMap, _("MlirAffineMap"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirAffineMap v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirAffineMap.
Definition at line 68 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirAffineMap >::cast (MlirAffineMap v, return_value_policy , handle) inline static
Definition at line 78 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonAffineMapToCapsule().
load()
bool pybind11::detail::type_caster< MlirAffineMap >::load (handle src, bool) inline
Definition at line 70 of file PybindAdaptors.h.
References mlirAffineMapIsNull(), pybind11::detail::mlirApiObjectToCapsule(), and mlirPythonCapsuleToAffineMap().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirAffineMap >::PYBIND11_TYPE_CASTER (MlirAffineMap , _("MlirAffineMap"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h