MLIR: mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType > Struct Template Reference
mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType > Struct Template Reference
Utility trait base that provides accessors for derived traits that have multiple regions.
#include "mlir/IR/OpDefinition.h"
Public Types
using region_iterator = MutableArrayRef< Region >
using region_range = RegionRange
Public Member Functions
unsigned getNumRegions ()
Return the number of regions.
Region & getRegion (unsigned i)
Return the region at index.
region_iterator region_begin ()
Region iterator access.
region_iterator region_end ()
region_range getRegions ()
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, TraitType >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType, template< typename > class TraitType>
struct mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >
Utility trait base that provides accessors for derived traits that have multiple regions.
Definition at line 535 of file OpDefinition.h.
Member Typedef Documentation
region_iterator
template<typename ConcreteType , template< typename > class TraitType> using mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::region_iterator = MutableArrayRef<Region>
Definition at line 536 of file OpDefinition.h.
region_range
template<typename ConcreteType , template< typename > class TraitType> using mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::region_range = RegionRange
Definition at line 537 of file OpDefinition.h.
Member Function Documentation
getNumRegions()
template<typename ConcreteType , template< typename > class TraitType> unsigned mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getNumRegions () inline
Return the number of regions.
Definition at line 540 of file OpDefinition.h.
References mlir::Operation::getNumRegions(), and mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation().
getRegion()
template<typename ConcreteType , template< typename > class TraitType> Region& mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegion (unsigned i) inline
Return the region at index.
Definition at line 543 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation(), and mlir::Operation::getRegion().
getRegions()
template<typename ConcreteType , template< typename > class TraitType> region_range mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegions () inline
Definition at line 550 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation(), and mlir::Operation::getRegions().
region_begin()
template<typename ConcreteType , template< typename > class TraitType> region_iterator mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::region_begin () inline
Region iterator access.
Definition at line 546 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation().
region_end()
template<typename ConcreteType , template< typename > class TraitType> region_iterator mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::region_end () inline
Definition at line 549 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation().
The documentation for this struct was generated from the following file:
include/mlir/IR/OpDefinition.h