MLIR: mlir::SparsificationOptions Struct Reference
mlir::SparsificationOptions Struct Reference
Options for the Sparsification pass.
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
Public Member Functions
SparsificationOptions (SparseParallelizationStrategy p, SparseEmitStrategy d, bool enableRT)
SparsificationOptions (SparseParallelizationStrategy p, bool enableRT)
SparsificationOptions ()
Public Attributes
SparseParallelizationStrategy parallelizationStrategy
SparseEmitStrategy sparseEmitStrategy
bool enableRuntimeLibrary
Detailed Description
Options for the Sparsification pass.
Definition at line 109 of file Passes.h.
Constructor & Destructor Documentation
SparsificationOptions() [1/3]
mlir::SparsificationOptions::SparsificationOptions (SparseParallelizationStrategy p, SparseEmitStrategy d, bool enableRT) inline
Definition at line 110 of file Passes.h.
References enableRuntimeLibrary, parallelizationStrategy, and sparseEmitStrategy.
Referenced by SparsificationOptions(), and SparsificationOptions().
SparsificationOptions() [2/3]
mlir::SparsificationOptions::SparsificationOptions (SparseParallelizationStrategy p, bool enableRT) inline
Definition at line 115 of file Passes.h.
References mlir::kFunctional, and SparsificationOptions().
SparsificationOptions() [3/3]
mlir::SparsificationOptions::SparsificationOptions () inline
Definition at line 118 of file Passes.h.
References mlir::kFunctional, mlir::kNone, SparsificationOptions(), and true.
Member Data Documentation
enableRuntimeLibrary
bool mlir::SparsificationOptions::enableRuntimeLibrary
Definition at line 124 of file Passes.h.
Referenced by SparsificationOptions().
parallelizationStrategy
SparseParallelizationStrategy mlir::SparsificationOptions::parallelizationStrategy
Definition at line 122 of file Passes.h.
Referenced by isParallelFor(), and SparsificationOptions().
sparseEmitStrategy
SparseEmitStrategy mlir::SparsificationOptions::sparseEmitStrategy
Definition at line 123 of file Passes.h.
Referenced by genSubscript(), genTensorLoad(), and SparsificationOptions().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/SparseTensor/Transforms/Passes.h