MLIR: mlir::xegpu::uArch::uArch Struct Reference
mlir::xegpu::uArch::uArch Struct Reference abstract
#include "mlir/Dialect/XeGPU/uArch/uArchBase.h"
Public Types
enum class Kind {
Xe2_First , PVC = Xe2_First , BMG , Xe2_Last = BMG ,
Xe3_First , CRI = Xe3_First , Xe3_Last = CRI
}
Public Member Functions
uArch (Kind kind, llvm::ArrayRef< const Instruction * > instructionRegistry)
virtual ~uArch ()=default
Kind getKind () const
virtual int getSubgroupSize () const =0
virtual unsigned getGeneralPackedFormatBitSize () const =0
const Instruction * getInstruction (InstructionKind instKind) const
bool isSupportedInstruction (InstructionKind instr) const
Protected Attributes
Kind kind
llvm::SmallDenseMap< InstructionKind, const Instruction *, 32 > instructionRegistry
Detailed Description
Definition at line 91 of file uArchBase.h.
Member Enumeration Documentation
Kind
enum class mlir::xegpu::uArch::uArch::Kind strong
Enumerator
Xe2_First
PVC
BMG
Xe2_Last
Xe3_First
CRI
Xe3_Last
Definition at line 92 of file uArchBase.h.
Constructor & Destructor Documentation
uArch()
mlir::xegpu::uArch::uArch::uArch (Kind kind, llvm::ArrayRef< const Instruction * > instructionRegistry) inline
Definition at line 104 of file uArchBase.h.
References instructionRegistry, and kind.
Referenced by mlir::xegpu::uArch::Xe2::classof(), mlir::xegpu::uArch::Xe3::classof(), mlir::xegpu::uArch::Xe2::Xe2(), and mlir::xegpu::uArch::Xe3::Xe3().
~uArch()
virtual mlir::xegpu::uArch::uArch::~uArch () virtual default
Member Function Documentation
getGeneralPackedFormatBitSize()
virtual unsigned mlir::xegpu::uArch::uArch::getGeneralPackedFormatBitSize () const pure virtual
Implemented in mlir::xegpu::uArch::Xe2, and mlir::xegpu::uArch::Xe3.
getInstruction()
const Instruction * mlir::xegpu::uArch::uArch::getInstruction (InstructionKind instKind) const inline
Definition at line 115 of file uArchBase.h.
References instructionRegistry.
Referenced by createScaleLayout().
getKind()
Kind mlir::xegpu::uArch::uArch::getKind () const inline
Definition at line 110 of file uArchBase.h.
References kind.
Referenced by mlir::xegpu::uArch::BMGuArch::classof(), mlir::xegpu::uArch::PVCuArch::classof(), and mlir::xegpu::uArch::Xe2::classof().
getSubgroupSize()
virtual int mlir::xegpu::uArch::uArch::getSubgroupSize () const pure virtual
Implemented in mlir::xegpu::uArch::Xe2, and mlir::xegpu::uArch::Xe3.
Referenced by adjustInnermostDimForDivisibility().
isSupportedInstruction()
bool mlir::xegpu::uArch::uArch::isSupportedInstruction (InstructionKind instr) const inline
Definition at line 122 of file uArchBase.h.
References instructionRegistry.
Member Data Documentation
instructionRegistry
llvm::SmallDenseMap<InstructionKind, const Instruction *, 32> mlir::xegpu::uArch::uArch::instructionRegistry protected
Definition at line 129 of file uArchBase.h.
Referenced by getInstruction(), isSupportedInstruction(), uArch(), mlir::xegpu::uArch::Xe2::Xe2(), and mlir::xegpu::uArch::Xe3::Xe3().
kind
Kind mlir::xegpu::uArch::uArch::kind protected
Definition at line 127 of file uArchBase.h.
Referenced by getKind(), uArch(), mlir::xegpu::uArch::Xe2::Xe2(), and mlir::xegpu::uArch::Xe3::Xe3().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/uArchBase.h