MLIR: pybind11::detail::type_caster< MlirModule > Struct Reference
pybind11::detail::type_caster< MlirModule > Struct Reference
Casts object <-> MlirModule.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirModule, _("MlirModule"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirModule v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirModule.
Definition at line 185 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirModule >::cast (MlirModule v, return_value_policy , handle) inline static
Definition at line 192 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonModuleToCapsule().
load()
bool pybind11::detail::type_caster< MlirModule >::load (handle src, bool) inline
Definition at line 187 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirModuleIsNull(), and mlirPythonCapsuleToModule().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirModule >::PYBIND11_TYPE_CASTER (MlirModule , _("MlirModule"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h