MLIR: mlir::spirv::detail::MatrixTypeStorage Struct Reference
mlir::spirv::detail::MatrixTypeStorage Struct Reference
Public Types
using KeyTy = std::tuple<Type, uint32_t>
Public Member Functions
MatrixTypeStorage (Type columnType, uint32_t columnCount)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static MatrixTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type columnType
const uint32_t columnCount
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 1151 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::MatrixTypeStorage::KeyTy = std::tuple<Type, uint32_t>
Definition at line 1155 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
MatrixTypeStorage()
mlir::spirv::detail::MatrixTypeStorage::MatrixTypeStorage (Type columnType, uint32_t columnCount) inline
Definition at line 1152 of file SPIRVTypes.cpp.
References columnCount, and columnType.
Referenced by construct().
Member Function Documentation
construct()
MatrixTypeStorage * mlir::spirv::detail::MatrixTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 1157 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and MatrixTypeStorage().
operator==()
bool mlir::spirv::detail::MatrixTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 1165 of file SPIRVTypes.cpp.
References columnCount, and columnType.
Member Data Documentation
columnCount
const uint32_t mlir::spirv::detail::MatrixTypeStorage::columnCount
Definition at line 1170 of file SPIRVTypes.cpp.
Referenced by MatrixTypeStorage(), and operator==().
columnType
Type mlir::spirv::detail::MatrixTypeStorage::columnType
Definition at line 1169 of file SPIRVTypes.cpp.
Referenced by MatrixTypeStorage(), and operator==().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp