MLIR: mlir::quant::detail::UniformQuantizedSubChannelTypeStorage Struct Reference
mlir::quant::detail::UniformQuantizedSubChannelTypeStorage Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Classes
struct KeyTy
Public Member Functions
UniformQuantizedSubChannelTypeStorage (const KeyTy &key, DenseElementsAttr scales, DenseElementsAttr zeroPoints, ArrayRef< int32_t > quantizedDimensions, ArrayRef< int64_t > blockSizes)
bool operator== (const KeyTy &key) const
DenseElementsAttr getScales () const
DenseElementsAttr getZeroPoints () const
ArrayRef< int32_t > getQuantizedDimensions () const
ArrayRef< int64_t > getBlockSizes () const
Public Member Functions inherited from mlir::quant::detail::QuantizedTypeStorage
QuantizedTypeStorage (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static UniformQuantizedSubChannelTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
static unsigned hashKey (const KeyTy &key)
Public Attributes
DenseElementsAttr scales
DenseElementsAttr zeroPoints
ArrayRef< int32_t > quantizedDimensions
ArrayRef< int64_t > blockSizes
Public Attributes inherited from mlir::quant::detail::QuantizedTypeStorage
unsigned flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Type storageType
Type expressedType
int64_t storageTypeMin
int64_t storageTypeMax
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 256 of file TypeDetail.h.
Constructor & Destructor Documentation
UniformQuantizedSubChannelTypeStorage()
mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::UniformQuantizedSubChannelTypeStorage (const KeyTy & key, DenseElementsAttr scales, DenseElementsAttr zeroPoints, ArrayRef< int32_t > quantizedDimensions, ArrayRef< int64_t > blockSizes) inline
Definition at line 330 of file TypeDetail.h.
References blockSizes, mlir::quant::detail::QuantizedTypeStorage::expressedType, mlir::quant::detail::QuantizedTypeStorage::flags, quantizedDimensions, mlir::quant::detail::QuantizedTypeStorage::QuantizedTypeStorage(), scales, mlir::quant::detail::QuantizedTypeStorage::storageType, mlir::quant::detail::QuantizedTypeStorage::storageTypeMax, mlir::quant::detail::QuantizedTypeStorage::storageTypeMin, and zeroPoints.
Referenced by construct().
Member Function Documentation
construct()
UniformQuantizedSubChannelTypeStorage * mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 346 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), blockSizes, mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::KeyTy::blockSizes, mlir::StorageUniquer::StorageAllocator::copyInto(), mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::KeyTy::quantizedDimensions, quantizedDimensions, mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::KeyTy::scales, scales, UniformQuantizedSubChannelTypeStorage(), mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::KeyTy::zeroPoints, and zeroPoints.
getBlockSizes()
ArrayRef< int64_t > mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::getBlockSizes () const inline
Definition at line 367 of file TypeDetail.h.
References blockSizes.
getQuantizedDimensions()
ArrayRef< int32_t > mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::getQuantizedDimensions () const inline
Definition at line 363 of file TypeDetail.h.
References quantizedDimensions.
getScales()
DenseElementsAttr mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::getScales () const inline
Definition at line 359 of file TypeDetail.h.
References scales.
getZeroPoints()
DenseElementsAttr mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::getZeroPoints () const inline
Definition at line 361 of file TypeDetail.h.
References zeroPoints.
hashKey()
unsigned mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 357 of file TypeDetail.h.
References mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::KeyTy::getHashValue().
operator==()
bool mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 340 of file TypeDetail.h.
References mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::KeyTy::genericIsEqual().
Member Data Documentation
blockSizes
ArrayRef<int64_t> mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::blockSizes
Definition at line 372 of file TypeDetail.h.
Referenced by construct(), getBlockSizes(), and UniformQuantizedSubChannelTypeStorage().
quantizedDimensions
ArrayRef<int32_t> mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::quantizedDimensions
Definition at line 371 of file TypeDetail.h.
Referenced by construct(), getQuantizedDimensions(), and UniformQuantizedSubChannelTypeStorage().
scales
DenseElementsAttr mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::scales
Definition at line 369 of file TypeDetail.h.
Referenced by construct(), getScales(), and UniformQuantizedSubChannelTypeStorage().
zeroPoints
DenseElementsAttr mlir::quant::detail::UniformQuantizedSubChannelTypeStorage::zeroPoints
Definition at line 370 of file TypeDetail.h.
Referenced by construct(), getZeroPoints(), and UniformQuantizedSubChannelTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h