MLIR: mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction Struct Reference
mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction Struct Reference
#include "mlir/Dialect/XeGPU/uArch/uArchBase.h"
Public Member Functions
Subgroup2DBlockLoadInstruction ()
int32_t getPackedFormatBitSize () const override
Public Member Functions inherited from mlir::xegpu::uArch::Instruction
Instruction (InstructionKind kind, InstructionScope scope)
~Instruction ()=default
InstructionKind getInstructionKind () const
InstructionScope getScope () const
Public Member Functions inherited from mlir::xegpu::uArch::BlockIOInstructionInterface
std::optional< BlockShapes > getBlockWidthHeightCount (Type elemTy, bool hasTransform=false, bool hasTranspose=false, bool upConv=false) const
virtual ~BlockIOInstructionInterface ()=default
Static Public Member Functions
static bool classof (const Instruction *B)
Static Public Member Functions inherited from mlir::xegpu::uArch::Instruction
static llvm::StringRef toString (InstructionKind instKind)
Protected Member Functions
std::optional< BlockShapes > computeBlockWidthHeightCount (Type elemTy, bool hasTransform, bool hasTranspose, bool upConv) const override
Additional Inherited Members
Public Types inherited from mlir::xegpu::uArch::BlockIOInstructionInterface
using BlockShapes
Protected Attributes inherited from mlir::xegpu::uArch::Instruction
const InstructionKind instKind
const InstructionScope scope
Detailed Description
Definition at line 262 of file uArchBase.h.
Constructor & Destructor Documentation
Subgroup2DBlockLoadInstruction()
mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction::Subgroup2DBlockLoadInstruction () inline
Definition at line 264 of file uArchBase.h.
References mlir::xegpu::uArch::Instruction::Instruction(), mlir::xegpu::uArch::Subgroup, and mlir::xegpu::uArch::Subgroup2DBlockLoad.
Member Function Documentation
classof()
bool mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction::classof (const Instruction * B) inline static
Definition at line 267 of file uArchBase.h.
References mlir::xegpu::uArch::Instruction::Instruction(), and mlir::xegpu::uArch::Subgroup2DBlockLoad.
computeBlockWidthHeightCount()
std::optional< BlockShapes > mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction::computeBlockWidthHeightCount (Type elemTy, bool hasTransform, bool hasTranspose, bool upConv) const inline override protected virtual
Implements mlir::xegpu::uArch::BlockIOInstructionInterface.
Definition at line 277 of file uArchBase.h.
References mlir::Type::getIntOrFloatBitWidth().
getPackedFormatBitSize()
int32_t mlir::xegpu::uArch::Subgroup2DBlockLoadInstruction::getPackedFormatBitSize () const inline override virtual
Implements mlir::xegpu::uArch::BlockIOInstructionInterface.
Definition at line 273 of file uArchBase.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/uArchBase.h