MLIR: pybind11::detail::type_caster< MlirValue > Struct Reference
pybind11::detail::type_caster< MlirValue > Struct Reference
Casts object <-> MlirValue.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirValue, _("MlirValue"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirValue v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirValue.
Definition at line 246 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirValue >::cast (MlirValue v, return_value_policy , handle) inline static
Definition at line 253 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_MAYBE_DOWNCAST_ATTR, and mlirPythonValueToCapsule().
load()
bool pybind11::detail::type_caster< MlirValue >::load (handle src, bool) inline
Definition at line 248 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirPythonCapsuleToValue(), and mlirValueIsNull().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirValue >::PYBIND11_TYPE_CASTER (MlirValue , _("MlirValue"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h