MLIR: MlirConditionallySpeculatableOpInterfaceCallbacks Struct Reference
MlirConditionallySpeculatableOpInterfaceCallbacks Struct Reference
Callbacks for implementing ConditionallySpeculatable from external code.
#include "mlir-c/Interfaces.h"
Public Attributes
void(* construct)(void *userData)
Optional constructor for user data. Set to nullptr to disable it.
void(* destruct)(void *userData)
Optional destructor for user data. Set to nullptr to disable it.
MlirSpeculatability(* getSpeculatability)(MlirOperation op, void *userData)
Returns the speculatability of the given operation.
void * userData
Detailed Description
Callbacks for implementing ConditionallySpeculatable from external code.
Definition at line 119 of file Interfaces.h.
Member Data Documentation
construct
void(* MlirConditionallySpeculatableOpInterfaceCallbacks::construct) (void *userData)
Optional constructor for user data. Set to nullptr to disable it.
Definition at line 121 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::attach().
destruct
void(* MlirConditionallySpeculatableOpInterfaceCallbacks::destruct) (void *userData)
Optional destructor for user data. Set to nullptr to disable it.
Definition at line 123 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::attach().
getSpeculatability
MlirSpeculatability(* MlirConditionallySpeculatableOpInterfaceCallbacks::getSpeculatability) (MlirOperation op, void *userData)
Returns the speculatability of the given operation.
Definition at line 125 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::attach().
userData
void* MlirConditionallySpeculatableOpInterfaceCallbacks::userData
Definition at line 126 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConditionallySpeculatableOpInterface::attach().
The documentation for this struct was generated from the following file:
include/mlir-c/Interfaces.h