MLIR: mlir::detail::constant_int_predicate_matcher Struct Reference
mlir::detail::constant_int_predicate_matcher Struct Reference
The matcher that matches a given target constant scalar / vector splat / tensor splat integer value that fulfills a predicate.
#include "mlir/IR/Matchers.h"
Public Member Functions
bool match (Attribute attr)
bool match (Operation *op)
Public Attributes
bool(* predicate)(const APInt &)
Detailed Description
The matcher that matches a given target constant scalar / vector splat / tensor splat integer value that fulfills a predicate.
Definition at line 242 of file Matchers.h.
Member Function Documentation
match() [1/2]
bool mlir::detail::constant_int_predicate_matcher::match (Attribute attr) inline
Definition at line 245 of file Matchers.h.
References mlir::detail::constant_int_value_binder::match(), and predicate.
match() [2/2]
bool mlir::detail::constant_int_predicate_matcher::match (Operation * op) inline
Definition at line 250 of file Matchers.h.
References mlir::detail::constant_int_value_binder::match(), and predicate.
Member Data Documentation
predicate
bool(* mlir::detail::constant_int_predicate_matcher::predicate) (const APInt &)
Definition at line 243 of file Matchers.h.
Referenced by match(), and match().
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h