MLIR: mlir::detail::FileLineColRangeAttrStorage Struct Reference
mlir::detail::FileLineColRangeAttrStorage Struct Reference final
Public Types
using PointerPair = llvm::PointerIntPair<StringAttr, 2>
using KeyTy = std::tuple<StringAttr, ::llvm::ArrayRef<unsigned>>
Public Member Functions
FileLineColRangeAttrStorage (StringAttr filename, int numLocs)
unsigned size () const
bool operator== (const KeyTy &tblgenKey) const
unsigned getLineCols (unsigned index) const
unsigned getStartLine () const
unsigned getStartColumn () const
unsigned getEndColumn () const
unsigned getEndLine () const
Public Member Functions inherited from mlir::AttributeStorage
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static FileLineColRangeAttrStorage * construct (::mlir::AttributeStorageAllocator &allocator, KeyTy &&tblgenKey)
::llvm::hash_code hashKey (const KeyTy &tblgenKey)
Public Attributes
llvm::PointerIntPair< StringAttr, 2 > filenameAndTrailing
unsigned startLine = 0
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 31 of file Location.cpp.
Member Typedef Documentation
KeyTy
using mlir::detail::FileLineColRangeAttrStorage::KeyTy = std::tuple<StringAttr, ::llvm::ArrayRef<unsigned>>
Definition at line 36 of file Location.cpp.
PointerPair
using mlir::detail::FileLineColRangeAttrStorage::PointerPair = llvm::PointerIntPair<StringAttr, 2>
Definition at line 35 of file Location.cpp.
Constructor & Destructor Documentation
FileLineColRangeAttrStorage()
mlir::detail::FileLineColRangeAttrStorage::FileLineColRangeAttrStorage (StringAttr filename, int numLocs) inline
Definition at line 38 of file Location.cpp.
References filenameAndTrailing.
Referenced by construct().
Member Function Documentation
construct()
FileLineColRangeAttrStorage * mlir::detail::FileLineColRangeAttrStorage::construct (::mlir::AttributeStorageAllocator & allocator, KeyTy && tblgenKey) inline static
Definition at line 42 of file Location.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), FileLineColRangeAttrStorage(), result, and size().
getEndColumn()
unsigned mlir::detail::FileLineColRangeAttrStorage::getEndColumn () const inline
Definition at line 88 of file Location.cpp.
References getLineCols(), getStartColumn(), and size().
getEndLine()
unsigned mlir::detail::FileLineColRangeAttrStorage::getEndLine () const inline
Definition at line 93 of file Location.cpp.
References getLineCols(), getStartLine(), and size().
getLineCols()
unsigned mlir::detail::FileLineColRangeAttrStorage::getLineCols (unsigned index) const inline
Definition at line 78 of file Location.cpp.
Referenced by getEndColumn(), getEndLine(), and getStartColumn().
getStartColumn()
unsigned mlir::detail::FileLineColRangeAttrStorage::getStartColumn () const inline
Definition at line 83 of file Location.cpp.
References getLineCols(), and size().
Referenced by getEndColumn().
getStartLine()
unsigned mlir::detail::FileLineColRangeAttrStorage::getStartLine () const inline
Definition at line 82 of file Location.cpp.
References startLine.
Referenced by getEndLine().
hashKey()
::llvm::hash_code mlir::detail::FileLineColRangeAttrStorage::hashKey (const KeyTy & tblgenKey) inline static
Definition at line 99 of file Location.cpp.
operator==()
bool mlir::detail::FileLineColRangeAttrStorage::operator== (const KeyTy & tblgenKey) const inline
Definition at line 70 of file Location.cpp.
References filenameAndTrailing, size(), and startLine.
size()
unsigned mlir::detail::FileLineColRangeAttrStorage::size () const inline
Definition at line 68 of file Location.cpp.
References filenameAndTrailing.
Referenced by construct(), getEndColumn(), getEndLine(), getStartColumn(), and operator==().
Member Data Documentation
filenameAndTrailing
llvm::PointerIntPair<StringAttr, 2> mlir::detail::FileLineColRangeAttrStorage::filenameAndTrailing
Definition at line 108 of file Location.cpp.
Referenced by FileLineColRangeAttrStorage(), operator==(), and size().
startLine
unsigned mlir::detail::FileLineColRangeAttrStorage::startLine = 0
Definition at line 109 of file Location.cpp.
Referenced by getStartLine(), and operator==().
The documentation for this struct was generated from the following file:
lib/IR/Location.cpp