MLIR: llvm::DenseMapInfo< mlir::OperationName > Struct Template Reference
llvm::DenseMapInfo< mlir::OperationName > Struct Template Reference
#include "mlir/IR/OperationSupport.h"
Static Public Member Functions
static mlir::OperationName getEmptyKey ()
static mlir::OperationName getTombstoneKey ()
static unsigned getHashValue (mlir::OperationName Val)
static bool isEqual (mlir::OperationName LHS, mlir::OperationName RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< mlir::OperationName >
Definition at line 929 of file OperationSupport.h.
Member Function Documentation
getEmptyKey()
static mlir::OperationName llvm::DenseMapInfo< mlir::OperationName >::getEmptyKey () inline static
Definition at line 930 of file OperationSupport.h.
References mlir::OperationName::getFromOpaquePointer().
getHashValue()
static unsigned llvm::DenseMapInfo< mlir::OperationName >::getHashValue (mlir::OperationName Val) inline static
Definition at line 938 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
getTombstoneKey()
static mlir::OperationName llvm::DenseMapInfo< mlir::OperationName >::getTombstoneKey () inline static
Definition at line 934 of file OperationSupport.h.
References mlir::OperationName::getFromOpaquePointer().
isEqual()
static bool llvm::DenseMapInfo< mlir::OperationName >::isEqual (mlir::OperationName LHS, mlir::OperationName RHS) inline static
Definition at line 941 of file OperationSupport.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/OperationSupport.h