MLIR: impl::MemRefDataPrinter< T > Struct Template Reference
impl::MemRefDataPrinter< T > Struct Template Reference
#include "mlir/ExecutionEngine/RunnerUtils.h"
Static Public Member Functions
static void print (std::ostream &os, T *base, int64_t dim, int64_t rank, int64_t offset, const int64_t *sizes, const int64_t *strides)
static void printFirst (std::ostream &os, T *base, int64_t dim, int64_t rank, int64_t offset, const int64_t *sizes, const int64_t *strides)
static void printLast (std::ostream &os, T *base, int64_t dim, int64_t rank, int64_t offset, const int64_t *sizes, const int64_t *strides)
Detailed Description
template<typename T>
struct impl::MemRefDataPrinter< T >
Definition at line 143 of file RunnerUtils.h.
Member Function Documentation
print()
template<typename T> void impl::MemRefDataPrinter< T >::print (std::ostream & os, T * base, int64_t dim, int64_t rank, int64_t offset, const int64_t * sizes, const int64_t * strides) static
Definition at line 173 of file RunnerUtils.h.
References print(), printFirst(), printLast(), and impl::printSpace().
Referenced by impl::printMemRef().
printFirst()
template<typename T> void impl::MemRefDataPrinter< T >::printFirst (std::ostream & os, T * base, int64_t dim, int64_t rank, int64_t offset, const int64_t * sizes, const int64_t * strides) static
Definition at line 156 of file RunnerUtils.h.
References print().
Referenced by print().
printLast()
template<typename T> void impl::MemRefDataPrinter< T >::printLast (std::ostream & os, T * base, int64_t dim, int64_t rank, int64_t offset, const int64_t * sizes, const int64_t * strides) static
Definition at line 195 of file RunnerUtils.h.
References print(), and impl::printSpace().
Referenced by print().
The documentation for this struct was generated from the following file:
include/mlir/ExecutionEngine/RunnerUtils.h