MLIR: mlir::FieldParser< std::optional< AttributeT >, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, std::optional< AttributeT > > > Struct Template Reference
mlir::FieldParser< std::optional< AttributeT >, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, std::optional< AttributeT > > > Struct Template Reference
Parse an Optional attribute.
#include "mlir/IR/DialectImplementation.h"
Static Public Member Functions
static FailureOr< std::optional< AttributeT > > parse (AsmParser &parser)
Detailed Description
template<typename AttributeT>
struct mlir::FieldParser< std::optional< AttributeT >, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, std::optional< AttributeT > > >
Parse an Optional attribute.
Definition at line 129 of file DialectImplementation.h.
Member Function Documentation
parse()
template<typename AttributeT > static FailureOr<std::optional<AttributeT> > mlir::FieldParser< std::optional< AttributeT >, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, std::optional< AttributeT > > >::parse (AsmParser & parser) inline static
Definition at line 133 of file DialectImplementation.h.
References mlir::AsmParser::getContext(), mlir::MLIRContext::getOrLoadDialect(), mlir::OptionalParseResult::has_value(), and mlir::AsmParser::parseOptionalAttribute().
The documentation for this struct was generated from the following file:
include/mlir/IR/DialectImplementation.h