MLIR: mlir::xegpu::uArch::PVCuArch Struct Reference
mlir::xegpu::uArch::PVCuArch Struct Reference final
#include "mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h"
Public Member Functions
PVCuArch ()
Public Member Functions inherited from mlir::xegpu::uArch::Xe2Plus
Xe2Plus (StringRef archName, StringRef archDescription, llvm::ArrayRef< const Instruction * > instructionRegistry, const XeCoreInfo &xeCore)
int getSubgroupSize () const override
unsigned getGeneralPackedFormatBitSize () const override
Public Member Functions inherited from mlir::xegpu::uArch::uArch
uArch (StringRef name, StringRef description, llvm::ArrayRef< const Instruction * > instructionRegistry)
virtual ~uArch ()=default
StringRef getName () const
StringRef getDescription () const
const Instruction * getInstruction (InstructionKind instKind) const
bool isSupportedInstruction (InstructionKind instr) const
Static Public Member Functions
static llvm::ArrayRef< const Instruction * > getInstructionRegistryArr ()
static const uArch * getInstance ()
Additional Inherited Members
Protected Attributes inherited from mlir::xegpu::uArch::Xe2Plus
XeCoreInfo xeCore
Protected Attributes inherited from mlir::xegpu::uArch::uArch
StringRef name
StringRef description
llvm::SmallDenseMap< InstructionKind, const Instruction *, 32 > instructionRegistry
Detailed Description
Definition at line 222 of file IntelGpuXe2.h.
Constructor & Destructor Documentation
PVCuArch()
mlir::xegpu::uArch::PVCuArch::PVCuArch () inline
Definition at line 233 of file IntelGpuXe2.h.
References getInstructionRegistryArr(), and mlir::xegpu::uArch::Xe2Plus::Xe2Plus().
Referenced by getInstance().
Member Function Documentation
getInstance()
const uArch * mlir::xegpu::uArch::PVCuArch::getInstance () inline static
Definition at line 239 of file IntelGpuXe2.h.
References PVCuArch().
Referenced by mlir::xegpu::uArch::getUArch().
getInstructionRegistryArr()
llvm::ArrayRef< const Instruction * > mlir::xegpu::uArch::PVCuArch::getInstructionRegistryArr () inline static
Definition at line 223 of file IntelGpuXe2.h.
Referenced by PVCuArch().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h