MLIR: MlirMemoryEffectsOpInterfaceCallbacks Struct Reference
MlirMemoryEffectsOpInterfaceCallbacks Struct Reference
Callbacks for implementing MemoryEffectsOpInterface from external code.
#include "mlir-c/Interfaces.h"
Public Attributes
void(* construct)(void *userData)
Optional constructor for user data. Set to nullptr to disable it.
void(* destruct)(void *userData)
Optional destructor for user data. Set to nullptr to disable it.
void(* getEffects)(MlirOperation op, MlirMemoryEffectInstancesList effects, void *userData)
Get memory effects callback.
void * userData
Detailed Description
Callbacks for implementing MemoryEffectsOpInterface from external code.
Definition at line 151 of file Interfaces.h.
Member Data Documentation
construct
void(* MlirMemoryEffectsOpInterfaceCallbacks::construct) (void *userData)
Optional constructor for user data. Set to nullptr to disable it.
Definition at line 153 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::attach().
destruct
void(* MlirMemoryEffectsOpInterfaceCallbacks::destruct) (void *userData)
Optional destructor for user data. Set to nullptr to disable it.
Definition at line 155 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::attach().
getEffects
void(* MlirMemoryEffectsOpInterfaceCallbacks::getEffects) (MlirOperation op, MlirMemoryEffectInstancesList effects, void *userData)
Get memory effects callback.
Definition at line 157 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::attach().
userData
void* MlirMemoryEffectsOpInterfaceCallbacks::userData
Definition at line 159 of file Interfaces.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyMemoryEffectsOpInterface::attach().
The documentation for this struct was generated from the following file:
include/mlir-c/Interfaces.h