MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< RangeType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirTypeIsAPDLRangeType
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "RangeType"
static const MlirStringRef name = mlirPDLRangeTypeGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< RangeType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< RangeType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< RangeType >
PyConcreteType ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::typed< nanobind::object, PyType > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Definition at line 87 of file DialectPDL.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::bindDerived (ClassTy & c) inline static
Definition at line 95 of file DialectPDL.cpp.
References mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::getTypeIdFunction static constexpr
Initial value:
=
      mlirPDLRangeTypeGetTypeID
Definition at line 89 of file DialectPDL.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::isaFunction = mlirTypeIsAPDLRangeType static constexpr
Definition at line 88 of file DialectPDL.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::name = mlirPDLRangeTypeGetName() inline static
Definition at line 92 of file DialectPDL.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::pdl::RangeType::pyClassName = "RangeType" static constexpr
Definition at line 91 of file DialectPDL.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectPDL.cpp