MLIR: llvm::GraphTraits< const mlir::CallGraphNode * > Struct Reference
llvm::GraphTraits< const mlir::CallGraphNode * > Struct Reference
#include "mlir/Analysis/CallGraph.h"
Public Types
using NodeRef = mlir::CallGraphNode *
using ChildIteratorType = mapped_iterator< mlir::CallGraphNode::iterator, decltype(&unwrap)>
Static Public Member Functions
static NodeRef getEntryNode (NodeRef node)
static NodeRef unwrap (const mlir::CallGraphNode::Edge &edge)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 233 of file CallGraph.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< const mlir::CallGraphNode * >::ChildIteratorType = mapped_iterator<mlir::CallGraphNode::iterator, decltype(&unwrap)>
Definition at line 242 of file CallGraph.h.
NodeRef
using llvm::GraphTraits< const mlir::CallGraphNode * >::NodeRef = mlir::CallGraphNode *
Definition at line 234 of file CallGraph.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< const mlir::CallGraphNode * >::child_begin (NodeRef node) inline static
Definition at line 244 of file CallGraph.h.
References mlir::CallGraphNode::begin(), and unwrap().
child_end()
static ChildIteratorType llvm::GraphTraits< const mlir::CallGraphNode * >::child_end (NodeRef node) inline static
Definition at line 247 of file CallGraph.h.
References mlir::CallGraphNode::end(), and unwrap().
getEntryNode()
static NodeRef llvm::GraphTraits< const mlir::CallGraphNode * >::getEntryNode (NodeRef node) inline static
Definition at line 235 of file CallGraph.h.
unwrap()
static NodeRef llvm::GraphTraits< const mlir::CallGraphNode * >::unwrap (const mlir::CallGraphNode::Edge & edge) inline static
Definition at line 237 of file CallGraph.h.
References mlir::CallGraphNode::Edge::getTarget().
The documentation for this struct was generated from the following file:
include/mlir/Analysis/CallGraph.h