MLIR: mlir::xegpu::uArch::BMGuArch Struct Reference
mlir::xegpu::uArch::BMGuArch Struct Reference
#include "mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h"
Public Member Functions
BMGuArch ()
Public Member Functions inherited from mlir::xegpu::uArch::Xe2Plus
Xe2Plus (StringRef archName, StringRef archDescription, llvm::ArrayRef< const Instruction * > instructionRegistry, const XeCoreInfo &xeCore)
int getSubgroupSize () const override
unsigned getGeneralPackedFormatBitSize () const override
Public Member Functions inherited from mlir::xegpu::uArch::uArch
uArch (StringRef name, StringRef description, llvm::ArrayRef< const Instruction * > instructionRegistry)
virtual ~uArch ()=default
StringRef getName () const
StringRef getDescription () const
const Instruction * getInstruction (InstructionKind instKind) const
bool isSupportedInstruction (InstructionKind instr) const
Static Public Member Functions
static llvm::ArrayRef< const Instruction * > getInstructionRegistryArr ()
static const uArch * getInstance ()
Additional Inherited Members
Protected Attributes inherited from mlir::xegpu::uArch::Xe2Plus
XeCoreInfo xeCore
Protected Attributes inherited from mlir::xegpu::uArch::uArch
StringRef name
StringRef description
llvm::SmallDenseMap< InstructionKind, const Instruction *, 32 > instructionRegistry
Detailed Description
Definition at line 245 of file IntelGpuXe2.h.
Constructor & Destructor Documentation
BMGuArch()
mlir::xegpu::uArch::BMGuArch::BMGuArch () inline
Definition at line 256 of file IntelGpuXe2.h.
References getInstructionRegistryArr(), and mlir::xegpu::uArch::Xe2Plus::Xe2Plus().
Referenced by getInstance().
Member Function Documentation
getInstance()
const uArch * mlir::xegpu::uArch::BMGuArch::getInstance () inline static
Definition at line 262 of file IntelGpuXe2.h.
References BMGuArch().
Referenced by mlir::xegpu::uArch::getUArch().
getInstructionRegistryArr()
llvm::ArrayRef< const Instruction * > mlir::xegpu::uArch::BMGuArch::getInstructionRegistryArr () inline static
Definition at line 246 of file IntelGpuXe2.h.
Referenced by BMGuArch().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h