MLIR: pybind11::detail::type_caster< MlirPassManager > Struct Reference
pybind11::detail::type_caster< MlirPassManager > Struct Reference
Casts object -> MlirPassManager.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirPassManager, _("MlirPassManager"))
bool load (handle src, bool)
Detailed Description
Casts object -> MlirPassManager.
Definition at line 268 of file PybindAdaptors.h.
Member Function Documentation
load()
bool pybind11::detail::type_caster< MlirPassManager >::load (handle src, bool) inline
Definition at line 270 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirPassManagerIsNull(), and mlirPythonCapsuleToPassManager().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirPassManager >::PYBIND11_TYPE_CASTER (MlirPassManager , _("MlirPassManager"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h