MLIR: mlir::vector::VectorTransformsOptions Struct Reference
mlir::vector::VectorTransformsOptions Struct Reference
Structure to control the behavior of vector transform patterns.
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
Public Member Functions
VectorTransformsOptions & setVectorTransformsOptions (VectorContractLowering opt)
VectorTransformsOptions & setVectorMultiReductionLowering (VectorMultiReductionLowering opt)
VectorTransformsOptions & setVectorTransposeLowering (VectorTransposeLowering opt)
VectorTransformsOptions & setVectorTransferSplit (VectorTransferSplit opt)
Public Attributes
VectorContractLowering vectorContractLowering = VectorContractLowering::Dot
Option to control the lowering of vector.contract.
VectorMultiReductionLowering vectorMultiReductionLowering
Option to control the lowering of vector.multi_reduction.
VectorTransposeLowering vectorTransposeLowering
Option to control the lowering of vector.transpose.
VectorTransferSplit vectorTransferSplit = VectorTransferSplit::None
Option to control the splitting of vector transfers.
Detailed Description
Structure to control the behavior of vector transform patterns.
Definition at line 33 of file VectorTransforms.h.
Member Function Documentation
setVectorMultiReductionLowering()
VectorTransformsOptions & mlir::vector::VectorTransformsOptions::setVectorMultiReductionLowering (VectorMultiReductionLowering opt) inline
Definition at line 45 of file VectorTransforms.h.
References vectorMultiReductionLowering.
Referenced by mlir::vector::LowerVectorsOptions::setVectorMultiReductionLowering().
setVectorTransferSplit()
VectorTransformsOptions & mlir::vector::VectorTransformsOptions::setVectorTransferSplit (VectorTransferSplit opt) inline
Definition at line 59 of file VectorTransforms.h.
References vectorTransferSplit.
Referenced by mlir::vector::LowerVectorsOptions::setVectorTransferSplit().
setVectorTransformsOptions()
VectorTransformsOptions & mlir::vector::VectorTransformsOptions::setVectorTransformsOptions (VectorContractLowering opt) inline
Definition at line 37 of file VectorTransforms.h.
References vectorContractLowering.
Referenced by mlir::vector::LowerVectorsOptions::setVectorTransformsOptions().
setVectorTransposeLowering()
VectorTransformsOptions & mlir::vector::VectorTransformsOptions::setVectorTransposeLowering (VectorTransposeLowering opt) inline
Definition at line 53 of file VectorTransforms.h.
References vectorTransposeLowering.
Referenced by mlir::vector::LowerVectorsOptions::setVectorTransposeLowering().
Member Data Documentation
vectorContractLowering
VectorContractLowering mlir::vector::VectorTransformsOptions::vectorContractLowering = VectorContractLowering::Dot
Option to control the lowering of vector.contract.
Definition at line 35 of file VectorTransforms.h.
Referenced by setVectorTransformsOptions().
vectorMultiReductionLowering
VectorMultiReductionLowering mlir::vector::VectorTransformsOptions::vectorMultiReductionLowering
Initial value:
=
      VectorMultiReductionLowering::InnerParallel
Option to control the lowering of vector.multi_reduction.
Definition at line 42 of file VectorTransforms.h.
Referenced by setVectorMultiReductionLowering().
vectorTransferSplit
VectorTransferSplit mlir::vector::VectorTransformsOptions::vectorTransferSplit = VectorTransferSplit::None
Option to control the splitting of vector transfers.
Definition at line 58 of file VectorTransforms.h.
Referenced by setVectorTransferSplit().
vectorTransposeLowering
VectorTransposeLowering mlir::vector::VectorTransformsOptions::vectorTransposeLowering
Initial value:
=
      VectorTransposeLowering::EltWise
Option to control the lowering of vector.transpose.
Definition at line 50 of file VectorTransforms.h.
Referenced by setVectorTransposeLowering().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Vector/Transforms/VectorTransforms.h