MLIR: mlir::ArithBuilder Struct Reference
mlir::ArithBuilder Struct Reference
Helper struct to build simple arithmetic quantities with minimal type inference support.
#include "mlir/Dialect/Arith/Utils/Utils.h"
Public Member Functions
ArithBuilder (OpBuilder &b, Location loc, arith::IntegerOverflowFlags ovf=arith::IntegerOverflowFlags::none)
Value _and (Value lhs, Value rhs)
Value add (Value lhs, Value rhs)
Value sub (Value lhs, Value rhs)
Value mul (Value lhs, Value rhs)
Value select (Value cmp, Value lhs, Value rhs)
Value sgt (Value lhs, Value rhs)
Value slt (Value lhs, Value rhs)
Detailed Description
Helper struct to build simple arithmetic quantities with minimal type inference support.
Definition at line 103 of file Utils.h.
Constructor & Destructor Documentation
ArithBuilder()
mlir::ArithBuilder::ArithBuilder (OpBuilder & b, Location loc, arith::IntegerOverflowFlags ovf = arith::IntegerOverflowFlags::none) inline
Definition at line 104 of file Utils.h.
Referenced by mlir::ArithIndexingBuilder::ArithIndexingBuilder().
Member Function Documentation
_and()
Value ArithBuilder::_and (Value lhs, Value rhs)
Definition at line 311 of file Utils.cpp.
References lhs, and rhs.
Referenced by mlir::linalg::generateParallelLoopNest().
add()
Value ArithBuilder::add (Value lhs, Value rhs)
Definition at line 314 of file Utils.cpp.
References lhs, and rhs.
mul()
Value ArithBuilder::mul (Value lhs, Value rhs)
Definition at line 324 of file Utils.cpp.
References lhs, and rhs.
Referenced by mlir::arith::createProduct().
select()
Value ArithBuilder::select (Value cmp, Value lhs, Value rhs)
Definition at line 339 of file Utils.cpp.
References lhs, and rhs.
sgt()
Value ArithBuilder::sgt (Value lhs, Value rhs)
Definition at line 329 of file Utils.cpp.
References lhs, and rhs.
slt()
Value ArithBuilder::slt (Value lhs, Value rhs)
Definition at line 334 of file Utils.cpp.
References lhs, and rhs.
Referenced by mlir::linalg::generateParallelLoopNest().
sub()
Value ArithBuilder::sub (Value lhs, Value rhs)
Definition at line 319 of file Utils.cpp.
References lhs, and rhs.
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Arith/Utils/Utils.h
lib/Dialect/Arith/Utils/Utils.cpp