MLIR: ConvertAccessChain Struct Reference
ConvertAccessChain Struct Reference
Public Member Functions
LogicalResult matchAndRewrite (spirv::AccessChainOp acOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
ConvertAliasResource (const ResourceAliasAnalysis &analysis, MLIRContext *context, PatternBenefit benefit=1)
Public Member Functions inherited from ConvertAliasResource< spirv::AccessChainOp >
ConvertAliasResource (const ResourceAliasAnalysis &analysis, MLIRContext *context, PatternBenefit benefit=1)
Additional Inherited Members
Protected Attributes inherited from ConvertAliasResource< spirv::AccessChainOp >
const ResourceAliasAnalysis & analysis
Detailed Description
Definition at line 340 of file UnifyAliasedResourcePass.cpp.
Member Function Documentation
ConvertAliasResource()
ConvertAliasResource< OpTy >::ConvertAliasResource inline
Definition at line 303 of file UnifyAliasedResourcePass.cpp.
matchAndRewrite()
LogicalResult ConvertAccessChain::matchAndRewrite (spirv::AccessChainOp acOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 344 of file UnifyAliasedResourcePass.cpp.
References ConvertAliasResource< spirv::AccessChainOp >::analysis, areSameBitwidthScalarType(), mlir::Builder::getIntegerAttr(), mlir::spirv::SPIRVType::getSizeInBytes(), mlir::Value::getType(), mlir::Type::isIntOrFloat(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOpWithNewOp().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/Transforms/UnifyAliasedResourcePass.cpp