MLIR: nanobind::detail::type_caster< MlirTypeID > Struct Reference
nanobind::detail::type_caster< MlirTypeID > Struct Reference
Casts object <-> MlirTypeID.
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Public Member Functions
bool from_python (handle src, uint8_t flags, cleanup_list *cleanup) noexcept
Static Public Member Functions
static handle from_cpp (MlirTypeID v, rv_policy, cleanup_list *cleanup) noexcept
Detailed Description
Casts object <-> MlirTypeID.
Definition at line 300 of file NanobindAdaptors.h.
Member Function Documentation
from_cpp()
static handle nanobind::detail::type_caster< MlirTypeID >::from_cpp (MlirTypeID v, rv_policy , cleanup_list * cleanup) inline static noexcept
Definition at line 309 of file NanobindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonTypeIDToCapsule().
from_python()
bool nanobind::detail::type_caster< MlirTypeID >::from_python (handle src, uint8_t flags, cleanup_list * cleanup) inline noexcept
Definition at line 302 of file NanobindAdaptors.h.
References nanobind::detail::mlirApiObjectToCapsule(), mlirPythonCapsuleToTypeID(), and mlirTypeIDIsNull().
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/NanobindAdaptors.h