MLIR: mlir::spirv::detail::TensorArmTypeStorage Struct Reference
mlir::spirv::detail::TensorArmTypeStorage Struct Reference final
Public Types
using KeyTy = std::tuple<ArrayRef<int64_t>, Type>
Public Member Functions
bool operator== (const KeyTy &key) const
TensorArmTypeStorage (ArrayRef< int64_t > shape, Type elementType)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static TensorArmTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
static llvm::hash_code hashKey (const KeyTy &key)
Public Attributes
ArrayRef< int64_t > shape
Type elementType
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 1238 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::TensorArmTypeStorage::KeyTy = std::tuple<ArrayRef<int64_t>, Type>
Definition at line 1239 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
TensorArmTypeStorage()
mlir::spirv::detail::TensorArmTypeStorage::TensorArmTypeStorage (ArrayRef< int64_t > shape, Type elementType) inline
Definition at line 1258 of file SPIRVTypes.cpp.
References elementType, and shape.
Referenced by construct().
Member Function Documentation
construct()
TensorArmTypeStorage * mlir::spirv::detail::TensorArmTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 1241 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::StorageUniquer::StorageAllocator::copyInto(), elementType, shape, and TensorArmTypeStorage().
hashKey()
llvm::hash_code mlir::spirv::detail::TensorArmTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 1249 of file SPIRVTypes.cpp.
References elementType, and shape.
operator==()
bool mlir::spirv::detail::TensorArmTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 1254 of file SPIRVTypes.cpp.
References elementType, and shape.
Member Data Documentation
elementType
Type mlir::spirv::detail::TensorArmTypeStorage::elementType
Definition at line 1262 of file SPIRVTypes.cpp.
Referenced by construct(), hashKey(), operator==(), and TensorArmTypeStorage().
shape
ArrayRef<int64_t> mlir::spirv::detail::TensorArmTypeStorage::shape
Definition at line 1261 of file SPIRVTypes.cpp.
Referenced by construct(), hashKey(), operator==(), and TensorArmTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp