MLIR: SubViewCanonicalizer Struct Reference
SubViewCanonicalizer Struct Reference
A canonicalizer wrapper to replace SubViewOps.
Public Member Functions
void operator() (PatternRewriter &rewriter, SubViewOp op, SubViewOp newOp)
Detailed Description
A canonicalizer wrapper to replace SubViewOps.
Definition at line 2061 of file MemRefOps.cpp.
Member Function Documentation
operator()()
void SubViewCanonicalizer::operator() (PatternRewriter & rewriter, SubViewOp op, SubViewOp newOp) inline
Definition at line 2062 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::failure(), mlir::Value::getType(), op, mlir::RewriterBase::replaceOpWithNewOp(), rewriter, and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/MemRef/IR/MemRefOps.cpp