MLIR: GenericPadTensorOpVectorizationPattern Struct Reference
GenericPadTensorOpVectorizationPattern Struct Reference
Rewrite a PadTensorOp into a sequence of InitTensorOp, FillOp and InsertSliceOp.
Public Member Functions
GenericPadTensorOpVectorizationPattern (MLIRContext *context, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::linalg::GeneralizePadTensorOpPattern
GeneralizePadTensorOpPattern (MLIRContext *context, OptimizeCopyFn optimizeCopyFn=nullptr, PatternBenefit benefit=1)
LogicalResult matchAndRewrite (PadTensorOp padOp, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< PadTensorOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< PadTensorOp >
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (PadTensorOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (PadTensorOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Static Public Member Functions
static LogicalResult tryVectorizeCopy (PatternRewriter &rewriter, PadTensorOp padOp, Value dest)
Vectorize the copying of a PadTensorOp's source.
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&... args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Additional Inherited Members
Protected Member Functions inherited from mlir::linalg::GeneralizePadTensorOpPattern
Value createFillOrGenerateOp (PatternRewriter &rewriter, PadTensorOp padOp, Value dest, const SmallVector< Value > &dynSizes) const
Filling dest using FillOp constant padding value if possible.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::linalg::GeneralizePadTensorOpPattern
OptimizeCopyFn optimizeCopyFn
Detailed Description
Rewrite a PadTensorOp into a sequence of InitTensorOp, FillOp and InsertSliceOp.
For now, only constant padding values are supported. If there is enough static type information, TransferReadOps and TransferWriteOps may be generated instead of InsertSliceOps.
Definition at line 684 of file Vectorization.cpp.
Constructor & Destructor Documentation
GenericPadTensorOpVectorizationPattern()
GenericPadTensorOpVectorizationPattern::GenericPadTensorOpVectorizationPattern (MLIRContext * context, PatternBenefit benefit = 1) inline
Definition at line 686 of file Vectorization.cpp.
Member Function Documentation
tryVectorizeCopy()
static LogicalResult GenericPadTensorOpVectorizationPattern::tryVectorizeCopy (PatternRewriter & rewriter, PadTensorOp padOp, Value dest) inline static
Vectorize the copying of a PadTensorOp's source.
This is possible if each dimension size is statically know in the source type or the result type (or both).
Definition at line 692 of file Vectorization.cpp.
References mlir::OpBuilder::create(), mlir::failure(), mlir::getConstantIntValue(), mlir::Builder::getZeroAttr(), ofrToIndexValues(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/Transforms/Vectorization.cpp