MLIR: llvm::ilist_traits<::mlir::Operation > Struct Reference
llvm::ilist_traits<::mlir::Operation > Struct Reference
#include "mlir/IR/BlockSupport.h"
Public Types
using Operation = ::mlir::Operation
using op_iterator = simple_ilist<Operation>::iterator
Public Member Functions
void addNodeToList (Operation *op)
This is a trait method invoked when an operation is added to a block.
void removeNodeFromList (Operation *op)
This is a trait method invoked when an operation is removed from a block.
void transferNodesFromList (ilist_traits< Operation > &otherList, op_iterator first, op_iterator last)
This is a trait method invoked when an operation is moved from one block to another.
Static Public Member Functions
static void deleteNode (Operation *op)
Detailed Description
Definition at line 226 of file BlockSupport.h.
Member Typedef Documentation
op_iterator
using llvm::ilist_traits<::mlir::Operation >::op_iterator = simple_ilist<Operation>::iterator
Definition at line 228 of file BlockSupport.h.
Operation
using llvm::ilist_traits<::mlir::Operation >::Operation = ::mlir::Operation
Definition at line 227 of file BlockSupport.h.
Member Function Documentation
addNodeToList()
void llvm::ilist_traits<::mlir::Operation >::addNodeToList (Operation * op)
This is a trait method invoked when an operation is added to a block.
We keep the block pointer up to date.
Definition at line 498 of file Operation.cpp.
References mlir::Operation::getBlock().
deleteNode()
void llvm::ilist_traits<::mlir::Operation >::deleteNode (Operation * op) static
Definition at line 486 of file Operation.cpp.
References mlir::Operation::destroy().
removeNodeFromList()
void llvm::ilist_traits<::mlir::Operation >::removeNodeFromList (Operation * op)
This is a trait method invoked when an operation is removed from a block.
We keep the block pointer up to date.
Definition at line 508 of file Operation.cpp.
transferNodesFromList()
void llvm::ilist_traits<::mlir::Operation >::transferNodesFromList (ilist_traits< Operation > & otherList, op_iterator first, op_iterator last)
This is a trait method invoked when an operation is moved from one block to another.
We keep the block pointer up to date.
Definition at line 515 of file Operation.cpp.
References mlir::Block::invalidateOpOrder().
The documentation for this struct was generated from the following files:
include/mlir/IR/BlockSupport.h
lib/IR/Operation.cpp