MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< FunctionType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirTypeIsALLVMFunctionType
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "FunctionType"
static const MlirStringRef name = mlirLLVMFunctionTypeGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< FunctionType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< FunctionType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< FunctionType >
PyConcreteType ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::typed< nanobind::object, PyType > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Definition at line 230 of file DialectLLVM.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::bindDerived (ClassTy & c) inline static
Definition at line 238 of file DialectLLVM.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirLLVMFunctionTypeGet(), mlirLLVMFunctionTypeGetInput(), mlirLLVMFunctionTypeGetNumInputs(), mlirLLVMFunctionTypeGetReturnType(), mlirLLVMFunctionTypeIsVarArg(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType::PyType().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::getTypeIdFunction static constexpr
Initial value:
=
      mlirLLVMFunctionTypeGetTypeID
Definition at line 232 of file DialectLLVM.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::isaFunction = mlirTypeIsALLVMFunctionType static constexpr
Definition at line 231 of file DialectLLVM.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::name = mlirLLVMFunctionTypeGetName() inline static
Definition at line 235 of file DialectLLVM.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::FunctionType::pyClassName = "FunctionType" static constexpr
Definition at line 234 of file DialectLLVM.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectLLVM.cpp