MLIR: mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc Struct Reference
mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc Struct Reference
#include "mlir/Dialect/XeGPU/uArch/uArchBase.h"
Public Member Functions
SubgroupScaledMatrixMultiplyAcc (unsigned packedFormatBitSizeA, unsigned packedFormatBitSizeB)
llvm::SmallVector< std::pair< uint32_t, uint32_t >, 16 > getSupportedShapes (Type dataType, MMAOpndKind matrixType) override
llvm::SmallVector< Type, 8 > getSupportedTypes (MLIRContext &context, MMAOpndKind matrixType) override
llvm::SmallVector< uint32_t, 8 > getSupportedM (Type type) const override
llvm::SmallVector< uint32_t, 8 > getSupportedK (Type type) const override
llvm::SmallVector< uint32_t, 8 > getSupportedN (Type type) const override
unsigned getPackedFormatBitSizeA () const
unsigned getPackedFormatBitSizeB () const
bool isLaneLayoutRowMajorOrder () const override
Public Member Functions inherited from mlir::xegpu::uArch::Instruction
Instruction (InstructionKind kind, InstructionScope scope)
~Instruction ()=default
InstructionKind getInstructionKind () const
InstructionScope getScope () const
Public Member Functions inherited from mlir::xegpu::uArch::MMAInstructionInterface
virtual ~MMAInstructionInterface ()=default
Static Public Member Functions
static bool classof (const Instruction *B)
Static Public Member Functions inherited from mlir::xegpu::uArch::Instruction
static llvm::StringRef toString (InstructionKind instKind)
Protected Attributes
const unsigned packedFormatBitSizeA
const unsigned packedFormatBitSizeB
Protected Attributes inherited from mlir::xegpu::uArch::Instruction
const InstructionKind instKind
const InstructionScope scope
Detailed Description
Definition at line 405 of file uArchBase.h.
Constructor & Destructor Documentation
SubgroupScaledMatrixMultiplyAcc()
mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::SubgroupScaledMatrixMultiplyAcc (unsigned packedFormatBitSizeA, unsigned packedFormatBitSizeB) inline
Definition at line 407 of file uArchBase.h.
References mlir::xegpu::uArch::Instruction::Instruction(), packedFormatBitSizeA, packedFormatBitSizeB, mlir::xegpu::uArch::Subgroup, and SubgroupScaledMatrixMultiplyAcc().
Referenced by SubgroupScaledMatrixMultiplyAcc().
Member Function Documentation
classof()
bool mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::classof (const Instruction * B) inline static
Definition at line 413 of file uArchBase.h.
References mlir::xegpu::uArch::Instruction::Instruction(), and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
getPackedFormatBitSizeA()
unsigned mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getPackedFormatBitSizeA () const inline
Definition at line 429 of file uArchBase.h.
References packedFormatBitSizeA.
getPackedFormatBitSizeB()
unsigned mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getPackedFormatBitSizeB () const inline
Definition at line 430 of file uArchBase.h.
References packedFormatBitSizeB.
getSupportedK()
llvm::SmallVector< uint32_t, 8 > mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getSupportedK (Type type) const inline override virtual
Implements mlir::xegpu::uArch::MMAInstructionInterface.
Definition at line 568 of file uArchBase.h.
References mlir::Type::getIntOrFloatBitWidth(), and mlir::Type::isIntOrFloat().
Referenced by getSupportedShapes().
getSupportedM()
llvm::SmallVector< uint32_t, 8 > mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getSupportedM (Type type) const inline override virtual
Implements mlir::xegpu::uArch::MMAInstructionInterface.
Definition at line 563 of file uArchBase.h.
Referenced by getSupportedShapes().
getSupportedN()
llvm::SmallVector< uint32_t, 8 > mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getSupportedN (Type type) const inline override virtual
Implements mlir::xegpu::uArch::MMAInstructionInterface.
Definition at line 585 of file uArchBase.h.
Referenced by getSupportedShapes().
getSupportedShapes()
llvm::SmallVector< std::pair< uint32_t, uint32_t >, 16 > mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getSupportedShapes (Type dataType, MMAOpndKind matrixType) inline override virtual
Implements mlir::xegpu::uArch::MMAInstructionInterface.
Definition at line 526 of file uArchBase.h.
References mlir::xegpu::uArch::util::crossProduct(), getSupportedK(), getSupportedM(), getSupportedN(), mlir::xegpu::uArch::MatrixA, mlir::xegpu::uArch::MatrixB, mlir::xegpu::uArch::MatrixC, and mlir::xegpu::uArch::MatrixD.
getSupportedTypes()
llvm::SmallVector< Type, 8 > mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::getSupportedTypes (MLIRContext & context, MMAOpndKind matrixType) inline override virtual
Implements mlir::xegpu::uArch::MMAInstructionInterface.
Definition at line 543 of file uArchBase.h.
References mlir::xegpu::uArch::MatrixA, mlir::xegpu::uArch::MatrixB, mlir::xegpu::uArch::MatrixC, and mlir::xegpu::uArch::MatrixD.
isLaneLayoutRowMajorOrder()
bool mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::isLaneLayoutRowMajorOrder () const inline override virtual
Implements mlir::xegpu::uArch::MMAInstructionInterface.
Definition at line 431 of file uArchBase.h.
Member Data Documentation
packedFormatBitSizeA
const unsigned mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::packedFormatBitSizeA protected
Definition at line 434 of file uArchBase.h.
Referenced by getPackedFormatBitSizeA(), and SubgroupScaledMatrixMultiplyAcc().
packedFormatBitSizeB
const unsigned mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc::packedFormatBitSizeB protected
Definition at line 435 of file uArchBase.h.
Referenced by getPackedFormatBitSizeB(), and SubgroupScaledMatrixMultiplyAcc().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/uArchBase.h