MLIR: nanobind::detail::type_caster< MlirFrozenRewritePatternSet > Struct Reference
nanobind::detail::type_caster< MlirFrozenRewritePatternSet > Struct Reference
Casts object <-> MlirFrozenRewritePatternSet.
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Public Member Functions
NB_TYPE_CASTER (MlirFrozenRewritePatternSet, const_name("MlirFrozenRewritePatternSet"))
bool from_python (handle src, uint8_t flags, cleanup_list *cleanup)
Static Public Member Functions
static handle from_cpp (MlirFrozenRewritePatternSet v, rv_policy, handle)
Detailed Description
Casts object <-> MlirFrozenRewritePatternSet.
Definition at line 207 of file NanobindAdaptors.h.
Member Function Documentation
from_cpp()
static handle nanobind::detail::type_caster< MlirFrozenRewritePatternSet >::from_cpp (MlirFrozenRewritePatternSet v, rv_policy , handle) inline static
Definition at line 215 of file NanobindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonFrozenRewritePatternSetToCapsule().
from_python()
bool nanobind::detail::type_caster< MlirFrozenRewritePatternSet >::from_python (handle src, uint8_t flags, cleanup_list * cleanup) inline
Definition at line 210 of file NanobindAdaptors.h.
References nanobind::detail::mlirApiObjectToCapsule(), and mlirPythonCapsuleToFrozenRewritePatternSet().
NB_TYPE_CASTER()
nanobind::detail::type_caster< MlirFrozenRewritePatternSet >::NB_TYPE_CASTER (MlirFrozenRewritePatternSet , const_name("MlirFrozenRewritePatternSet"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/NanobindAdaptors.h