MLIR: DynamicEventPool Struct Reference
DynamicEventPool Struct Reference
Public Member Functions
DynamicEventPool (L0RTContextWrapper *rtCtx)
DynamicEventPool (const DynamicEventPool &)=delete
DynamicEventPool & operator= (const DynamicEventPool &)=delete
DynamicEventPool (DynamicEventPool &&) noexcept=default
DynamicEventPool & operator= (DynamicEventPool &&) noexcept=default
~DynamicEventPool ()
void createNewPool (size_t numEvents)
ze_event_handle_t takeEvent ()
void releaseEvent (ze_event_handle_t event)
Public Attributes
std::vector< UniqueZeEventPool > eventPools
std::vector< UniqueZeEvent > availableEvents
std::unordered_map< ze_event_handle_t, UniqueZeEvent > takenEvents
size_t maxEventsCount {32768}
size_t currentEventsLimit {0}
size_t currentEventsCnt {0}
L0RTContextWrapper * rtCtx
Static Public Attributes
static constexpr size_t numEventsPerPool {128}
Detailed Description
Definition at line 244 of file LevelZeroRuntimeWrappers.cpp.
Constructor & Destructor Documentation
DynamicEventPool() [1/3]
DynamicEventPool::DynamicEventPool (L0RTContextWrapper * rtCtx) inline
Definition at line 259 of file LevelZeroRuntimeWrappers.cpp.
References createNewPool(), numEventsPerPool, and rtCtx.
Referenced by DynamicEventPool(), DynamicEventPool(), operator=(), operator=(), and ~DynamicEventPool().
DynamicEventPool() [2/3]
DynamicEventPool::DynamicEventPool (const DynamicEventPool &) delete
References DynamicEventPool().
DynamicEventPool() [3/3]
DynamicEventPool::DynamicEventPool (DynamicEventPool &&) default noexcept
References DynamicEventPool().
~DynamicEventPool()
DynamicEventPool::~DynamicEventPool () inline
Definition at line 270 of file LevelZeroRuntimeWrappers.cpp.
References DynamicEventPool(), and takenEvents.
Member Function Documentation
createNewPool()
void DynamicEventPool::createNewPool (size_t numEvents) inline
Definition at line 274 of file LevelZeroRuntimeWrappers.cpp.
References currentEventsLimit, eventPools, L0_SAFE_CALL, and rtCtx.
Referenced by DynamicEventPool(), and takeEvent().
operator=() [1/2]
DynamicEventPool & DynamicEventPool::operator= (const DynamicEventPool &) delete
References DynamicEventPool().
operator=() [2/2]
DynamicEventPool & DynamicEventPool::operator= (DynamicEventPool &&) default noexcept
References DynamicEventPool().
releaseEvent()
void DynamicEventPool::releaseEvent (ze_event_handle_t event) inline
Definition at line 320 of file LevelZeroRuntimeWrappers.cpp.
References availableEvents, L0_SAFE_CALL, and takenEvents.
Referenced by mgpuEventDestroy().
takeEvent()
ze_event_handle_t DynamicEventPool::takeEvent () inline
Definition at line 287 of file LevelZeroRuntimeWrappers.cpp.
References availableEvents, createNewPool(), currentEventsCnt, currentEventsLimit, eventPools, L0_SAFE_CALL, maxEventsCount, numEventsPerPool, and takenEvents.
Referenced by mgpuEventCreate().
Member Data Documentation
availableEvents
std::vector<UniqueZeEvent> DynamicEventPool::availableEvents
Definition at line 248 of file LevelZeroRuntimeWrappers.cpp.
Referenced by releaseEvent(), and takeEvent().
currentEventsCnt
size_t DynamicEventPool::currentEventsCnt {0}
Definition at line 256 of file LevelZeroRuntimeWrappers.cpp.
Referenced by takeEvent().
currentEventsLimit
size_t DynamicEventPool::currentEventsLimit {0}
Definition at line 255 of file LevelZeroRuntimeWrappers.cpp.
Referenced by createNewPool(), and takeEvent().
eventPools
std::vector<UniqueZeEventPool> DynamicEventPool::eventPools
Definition at line 247 of file LevelZeroRuntimeWrappers.cpp.
Referenced by createNewPool(), and takeEvent().
maxEventsCount
size_t DynamicEventPool::maxEventsCount {32768}
Definition at line 254 of file LevelZeroRuntimeWrappers.cpp.
Referenced by takeEvent().
numEventsPerPool
size_t DynamicEventPool::numEventsPerPool {128} static constexpr
Definition at line 245 of file LevelZeroRuntimeWrappers.cpp.
Referenced by DynamicEventPool(), and takeEvent().
rtCtx
L0RTContextWrapper* DynamicEventPool::rtCtx
Definition at line 257 of file LevelZeroRuntimeWrappers.cpp.
Referenced by createNewPool(), and DynamicEventPool().
takenEvents
std::unordered_map<ze_event_handle_t, UniqueZeEvent> DynamicEventPool::takenEvents
Definition at line 249 of file LevelZeroRuntimeWrappers.cpp.
Referenced by releaseEvent(), takeEvent(), and ~DynamicEventPool().
The documentation for this struct was generated from the following file:
lib/ExecutionEngine/LevelZeroRuntimeWrappers.cpp