MLIR: mlir::Pass::Option< DataType, OptionParser > Struct Template Reference
mlir::Pass::Option< DataType, OptionParser > Struct Template Reference
This class represents a specific pass option, with a provided data type.
#include "mlir/Pass/Pass.h"
Public Member Functions
template<typename... Args>
Option (Pass &parent, StringRef arg, Args &&...args)
Public Member Functions inherited from mlir::detail::PassOptions::Option< DataType, OptionParser >
template<typename... Args>
Option (PassOptions &parent, StringRef arg, Args &&...args)
~Option () override=default
Option & operator= (const Option &other)
Detailed Description
template<typename DataType, typename OptionParser = detail::PassOptions::OptionParser<DataType>>
struct mlir::Pass::Option< DataType, OptionParser >
This class represents a specific pass option, with a provided data type.
Definition at line 93 of file Pass.h.
Constructor & Destructor Documentation
Option()
template<typename DataType, typename OptionParser = detail::PassOptions::OptionParser<DataType>> template<typename... Args> mlir::Pass::Option< DataType, OptionParser >::Option (Pass & parent, StringRef arg, Args &&... args) inline
Definition at line 95 of file Pass.h.
References Option(), and mlir::Pass::Pass().
Referenced by Option().
The documentation for this struct was generated from the following file:
include/mlir/Pass/Pass.h