MLIR: mlir::xegpu::uArch::MMAInstructionInterface Struct Reference
mlir::xegpu::uArch::MMAInstructionInterface Struct Reference abstract
#include "mlir/Dialect/XeGPU/uArch/uArchBase.h"
Public Member Functions
virtual llvm::SmallVector< std::pair< uint32_t, uint32_t >, 16 > getSupportedShapes (Type dataType, MMAOpndKind matrixType)=0
virtual llvm::SmallVector< Type, 8 > getSupportedTypes (MLIRContext &context, MMAOpndKind matrixType)=0
virtual llvm::SmallVector< uint32_t, 8 > getSupportedM (Type type) const =0
virtual llvm::SmallVector< uint32_t, 8 > getSupportedK (Type type) const =0
virtual llvm::SmallVector< uint32_t, 8 > getSupportedN (Type type) const =0
virtual bool isLaneLayoutRowMajorOrder () const =0
virtual ~MMAInstructionInterface ()=default
Detailed Description
Definition at line 136 of file uArchBase.h.
Constructor & Destructor Documentation
~MMAInstructionInterface()
virtual mlir::xegpu::uArch::MMAInstructionInterface::~MMAInstructionInterface () virtual default
Member Function Documentation
getSupportedK()
virtual llvm::SmallVector< uint32_t, 8 > mlir::xegpu::uArch::MMAInstructionInterface::getSupportedK (Type type) const pure virtual
Implemented in mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc, and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
Referenced by getDpasInstDataLayouts().
getSupportedM()
virtual llvm::SmallVector< uint32_t, 8 > mlir::xegpu::uArch::MMAInstructionInterface::getSupportedM (Type type) const pure virtual
Implemented in mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc, and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
Referenced by getDpasInstDataLayouts().
getSupportedN()
virtual llvm::SmallVector< uint32_t, 8 > mlir::xegpu::uArch::MMAInstructionInterface::getSupportedN (Type type) const pure virtual
Implemented in mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc, and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
Referenced by getDpasInstDataLayouts().
getSupportedShapes()
virtual llvm::SmallVector< std::pair< uint32_t, uint32_t >, 16 > mlir::xegpu::uArch::MMAInstructionInterface::getSupportedShapes (Type dataType, MMAOpndKind matrixType) pure virtual
Implemented in mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc, and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
getSupportedTypes()
virtual llvm::SmallVector< Type, 8 > mlir::xegpu::uArch::MMAInstructionInterface::getSupportedTypes (MLIRContext & context, MMAOpndKind matrixType) pure virtual
Implemented in mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc, and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
isLaneLayoutRowMajorOrder()
virtual bool mlir::xegpu::uArch::MMAInstructionInterface::isLaneLayoutRowMajorOrder () const pure virtual
Implemented in mlir::xegpu::uArch::SubgroupMatrixMultiplyAcc, and mlir::xegpu::uArch::SubgroupScaledMatrixMultiplyAcc.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/uArchBase.h