MLIR: mlir::RAIIMlirLlvmRawFdOStream Struct Reference
mlir::RAIIMlirLlvmRawFdOStream Struct Reference
RAII wrapper for MlirLlvmRawFdOStream that ensures destruction on scope exit.
#include "mlir/Bindings/Python/NanobindUtils.h"
Public Member Functions
RAIIMlirLlvmRawFdOStream (MlirLlvmRawFdOStream stream)
RAIIMlirLlvmRawFdOStream (const RAIIMlirLlvmRawFdOStream &)=delete
RAIIMlirLlvmRawFdOStream & operator= (const RAIIMlirLlvmRawFdOStream &)=delete
~RAIIMlirLlvmRawFdOStream ()
Detailed Description
RAII wrapper for MlirLlvmRawFdOStream that ensures destruction on scope exit.
Definition at line 196 of file NanobindUtils.h.
Constructor & Destructor Documentation
RAIIMlirLlvmRawFdOStream() [1/2]
mlir::RAIIMlirLlvmRawFdOStream::RAIIMlirLlvmRawFdOStream (MlirLlvmRawFdOStream stream) inline
Definition at line 197 of file NanobindUtils.h.
Referenced by operator=(), and RAIIMlirLlvmRawFdOStream().
RAIIMlirLlvmRawFdOStream() [2/2]
mlir::RAIIMlirLlvmRawFdOStream::RAIIMlirLlvmRawFdOStream (const RAIIMlirLlvmRawFdOStream &) delete
References RAIIMlirLlvmRawFdOStream().
~RAIIMlirLlvmRawFdOStream()
mlir::RAIIMlirLlvmRawFdOStream::~RAIIMlirLlvmRawFdOStream () inline
Definition at line 202 of file NanobindUtils.h.
References mlirLlvmRawFdOStreamDestroy().
Member Function Documentation
operator=()
RAIIMlirLlvmRawFdOStream & mlir::RAIIMlirLlvmRawFdOStream::operator= (const RAIIMlirLlvmRawFdOStream &) delete
References RAIIMlirLlvmRawFdOStream().
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/NanobindUtils.h