MLIR: mlir::SPIRVTypeConverter::Options Struct Reference
mlir::SPIRVTypeConverter::Options Struct Reference
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
Public Member Functions
Options ()
Public Attributes
bool emulateNon32BitScalarTypes
Whether to emulate non-32-bit scalar types with 32-bit scalar types if no native support.
unsigned boolNumBits
The number of bits to store a boolean value.
Detailed Description
Definition at line 35 of file SPIRVConversion.h.
Constructor & Destructor Documentation
Options()
mlir::SPIRVTypeConverter::Options::Options () inline
Definition at line 58 of file SPIRVConversion.h.
References mlir::SPIRVTypeConverter::getIndexType(), mlir::SPIRVTypeConverter::getMemorySpaceForStorageClass(), mlir::SPIRVTypeConverter::getOptions(), mlir::SPIRVTypeConverter::getStorageClassForMemorySpace(), and mlir::SPIRVTypeConverter::SPIRVTypeConverter().
Member Data Documentation
boolNumBits
unsigned mlir::SPIRVTypeConverter::Options::boolNumBits
The number of bits to store a boolean value.
It is eight bits by default.
Definition at line 54 of file SPIRVConversion.h.
Referenced by convertBoolMemrefType().
emulateNon32BitScalarTypes
bool mlir::SPIRVTypeConverter::Options::emulateNon32BitScalarTypes
Whether to emulate non-32-bit scalar types with 32-bit scalar types if no native support.
Non-32-bit scalar types require special hardware support that may not exist on all GPUs. This is reflected in SPIR-V as that non-32-bit scalar types require special capabilities or extensions. This option controls whether to use 32-bit types to emulate, if a scalar type of a certain bitwidth is not supported in the target environment. This requires the runtime to also feed in data with a matched bitwidth and layout for interface types. The runtime can do that by inspecting the SPIR-V module.
If the original scalar type has less than 32-bit, a multiple of its values will be packed into one 32-bit value to be memory efficient.
Definition at line 50 of file SPIRVConversion.h.
Referenced by convertScalarType().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h