MLIR: mlir::detail::constant_int_range_predicate_matcher Struct Reference
mlir::detail::constant_int_range_predicate_matcher Struct Reference
A matcher that matches a given a constant scalar / vector splat / tensor splat integer value or a constant integer range that fulfills a predicate.
#include "mlir/IR/Matchers.h"
Public Member Functions
bool match (Attribute attr)
bool match (Operation *op)
Public Attributes
bool(* predicate)(const ConstantIntRanges &)
Detailed Description
A matcher that matches a given a constant scalar / vector splat / tensor splat integer value or a constant integer range that fulfills a predicate.
Definition at line 258 of file Matchers.h.
Member Function Documentation
match() [1/2]
bool mlir::detail::constant_int_range_predicate_matcher::match (Attribute attr) inline
Definition at line 261 of file Matchers.h.
References mlir::ConstantIntRanges::constant(), mlir::detail::constant_int_value_binder::match(), and predicate.
Referenced by match().
match() [2/2]
bool mlir::detail::constant_int_range_predicate_matcher::match (Operation * op) inline
Definition at line 267 of file Matchers.h.
References mlir::ConstantIntRanges::constant(), mlir::IntegerValueRange::getValue(), match(), mlir::detail::infer_int_range_op_binder::match(), and predicate.
Member Data Documentation
predicate
bool(* mlir::detail::constant_int_range_predicate_matcher::predicate) (const ConstantIntRanges &)
Definition at line 259 of file Matchers.h.
Referenced by match(), and match().
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h