MLIR: pybind11::detail::type_caster< MlirAttribute > Struct Reference
pybind11::detail::type_caster< MlirAttribute > Struct Reference
Casts object <-> MlirAttribute.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirAttribute, _("MlirAttribute"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirAttribute v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirAttribute.
Definition at line 90 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirAttribute >::cast (MlirAttribute v, return_value_policy , handle) inline static
Definition at line 97 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_MAYBE_DOWNCAST_ATTR, and mlirPythonAttributeToCapsule().
load()
bool pybind11::detail::type_caster< MlirAttribute >::load (handle src, bool) inline
Definition at line 92 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirAttributeIsNull(), and mlirPythonCapsuleToAttribute().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirAttribute >::PYBIND11_TYPE_CASTER (MlirAttribute , _("MlirAttribute"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h