MLIR: mlir::ForwardIterator Struct Reference
mlir::ForwardIterator Struct Reference
This iterator enumerates the elements in "forward" order.
#include "mlir/IR/Visitors.h"
Static Public Member Functions
static MutableArrayRef< Region > makeIterable (Operation &range)
Make operations iterable: return the list of regions.
template<typename T>
static constexpr T & makeIterable (T &range)
Regions and block are already iterable.
Detailed Description
This iterator enumerates the elements in "forward" order.
Definition at line 31 of file Visitors.h.
Member Function Documentation
makeIterable() [1/2]
MutableArrayRef< Region > ForwardIterator::makeIterable (Operation & range) static
Make operations iterable: return the list of regions.
Definition at line 17 of file Visitors.cpp.
References mlir::Operation::getRegions().
Referenced by mlir::ForwardDominanceIterator< NoGraphRegions >::makeIterable(), mlir::ForwardDominanceIterator< NoGraphRegions >::makeIterable(), mlir::ReverseDominanceIterator< NoGraphRegions >::makeIterable(), mlir::ReverseDominanceIterator< NoGraphRegions >::makeIterable(), and mlir::ReverseIterator::makeIterable().
makeIterable() [2/2]
template<typename T> constexpr T & mlir::ForwardIterator::makeIterable (T & range) inline static constexpr
Regions and block are already iterable.
Definition at line 37 of file Visitors.h.
The documentation for this struct was generated from the following files:
include/mlir/IR/Visitors.h
lib/IR/Visitors.cpp