MLIR: StreamWrapper Struct Reference
StreamWrapper Struct Reference
Public Member Functions
StreamWrapper (DynamicEventPool &dynEventPool)
~StreamWrapper ()
ze_event_handle_t * getLastImplicitEventPtr ()
void sync (ze_event_handle_t explicitEvent=nullptr)
template<typename Func>
void enqueueOp (Func &&op)
Public Attributes
std::deque< ze_event_handle_t > implicitEventStack
DynamicEventPool & dynEventPool
Detailed Description
Definition at line 341 of file LevelZeroRuntimeWrappers.cpp.
Constructor & Destructor Documentation
StreamWrapper()
StreamWrapper::StreamWrapper (DynamicEventPool & dynEventPool) inline
Definition at line 346 of file LevelZeroRuntimeWrappers.cpp.
References dynEventPool.
~StreamWrapper()
StreamWrapper::~StreamWrapper () inline
Definition at line 347 of file LevelZeroRuntimeWrappers.cpp.
References sync().
Member Function Documentation
enqueueOp()
template<typename Func> void StreamWrapper::enqueueOp (Func && op) inline
Definition at line 373 of file LevelZeroRuntimeWrappers.cpp.
References dynEventPool, getLastImplicitEventPtr(), and implicitEventStack.
Referenced by mgpuLaunchKernel(), mgpuMemcpy(), and mgpuMemset().
getLastImplicitEventPtr()
ze_event_handle_t * StreamWrapper::getLastImplicitEventPtr () inline
Definition at line 349 of file LevelZeroRuntimeWrappers.cpp.
References implicitEventStack.
Referenced by enqueueOp(), and sync().
sync()
void StreamWrapper::sync (ze_event_handle_t explicitEvent = nullptr) inline
Definition at line 354 of file LevelZeroRuntimeWrappers.cpp.
References dynEventPool, getLastImplicitEventPtr(), implicitEventStack, and L0_SAFE_CALL.
Referenced by mgpuMemFree(), mgpuStreamSynchronize(), mgpuStreamWaitEvent(), and ~StreamWrapper().
Member Data Documentation
dynEventPool
DynamicEventPool& StreamWrapper::dynEventPool
Definition at line 344 of file LevelZeroRuntimeWrappers.cpp.
Referenced by enqueueOp(), StreamWrapper(), and sync().
implicitEventStack
std::deque<ze_event_handle_t> StreamWrapper::implicitEventStack
Definition at line 343 of file LevelZeroRuntimeWrappers.cpp.
Referenced by enqueueOp(), getLastImplicitEventPtr(), and sync().
The documentation for this struct was generated from the following file:
lib/ExecutionEngine/LevelZeroRuntimeWrappers.cpp