MLIR: mlir::quant::detail::UniformQuantizedPerAxisTypeStorage Struct Reference
mlir::quant::detail::UniformQuantizedPerAxisTypeStorage Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Classes
struct KeyTy
Public Member Functions
UniformQuantizedPerAxisTypeStorage (const KeyTy &key, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints)
bool operator== (const KeyTy &key) const
ArrayRef< double > getScales () const
ArrayRef< int64_t > getZeroPoints () const
Public Member Functions inherited from mlir::quant::detail::QuantizedTypeStorage
QuantizedTypeStorage (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static UniformQuantizedPerAxisTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
static unsigned hashKey (const KeyTy &key)
Public Attributes
const double * scaleElements
const int64_t * zeroPointElements
unsigned quantParamsSize
int32_t quantizedDimension
Public Attributes inherited from mlir::quant::detail::QuantizedTypeStorage
unsigned flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Type storageType
Type expressedType
int64_t storageTypeMin
int64_t storageTypeMax
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 161 of file TypeDetail.h.
Constructor & Destructor Documentation
UniformQuantizedPerAxisTypeStorage()
mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::UniformQuantizedPerAxisTypeStorage (const KeyTy & key, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints) inline
Definition at line 219 of file TypeDetail.h.
References mlir::quant::detail::QuantizedTypeStorage::expressedType, mlir::quant::detail::QuantizedTypeStorage::flags, quantizedDimension, mlir::quant::detail::QuantizedTypeStorage::QuantizedTypeStorage(), quantParamsSize, scaleElements, mlir::quant::detail::QuantizedTypeStorage::storageType, mlir::quant::detail::QuantizedTypeStorage::storageTypeMax, mlir::quant::detail::QuantizedTypeStorage::storageTypeMin, and zeroPointElements.
Referenced by construct().
Member Function Documentation
construct()
UniformQuantizedPerAxisTypeStorage * mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 233 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::StorageUniquer::StorageAllocator::copyInto(), mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::KeyTy::scales, UniformQuantizedPerAxisTypeStorage(), and mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::KeyTy::zeroPoints.
getScales()
ArrayRef< double > mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::getScales () const inline
Definition at line 242 of file TypeDetail.h.
References quantParamsSize, and scaleElements.
getZeroPoints()
ArrayRef< int64_t > mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::getZeroPoints () const inline
Definition at line 246 of file TypeDetail.h.
References quantParamsSize, and zeroPointElements.
hashKey()
unsigned mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 240 of file TypeDetail.h.
References mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::KeyTy::getHashValue().
operator==()
bool mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 227 of file TypeDetail.h.
References mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::KeyTy::genericIsEqual().
Member Data Documentation
quantizedDimension
int32_t mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::quantizedDimension
Definition at line 253 of file TypeDetail.h.
Referenced by UniformQuantizedPerAxisTypeStorage().
quantParamsSize
unsigned mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::quantParamsSize
Definition at line 252 of file TypeDetail.h.
Referenced by getScales(), getZeroPoints(), and UniformQuantizedPerAxisTypeStorage().
scaleElements
const double* mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::scaleElements
Definition at line 250 of file TypeDetail.h.
Referenced by getScales(), and UniformQuantizedPerAxisTypeStorage().
zeroPointElements
const int64_t* mlir::quant::detail::UniformQuantizedPerAxisTypeStorage::zeroPointElements
Definition at line 251 of file TypeDetail.h.
Referenced by getZeroPoints(), and UniformQuantizedPerAxisTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h