MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions Struct Reference
Public Member Functions
PyTransformOptions ()
PyTransformOptions (PyTransformOptions &&other)
PyTransformOptions (const PyTransformOptions &)=delete
~PyTransformOptions ()
Public Attributes
MlirTransformOptions options
Detailed Description
Definition at line 27 of file TransformInterpreter.cpp.
Constructor & Destructor Documentation
PyTransformOptions() [1/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions::PyTransformOptions () inline
Definition at line 28 of file TransformInterpreter.cpp.
References mlirTransformOptionsCreate(), and options.
Referenced by PyTransformOptions(), and PyTransformOptions().
PyTransformOptions() [2/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions::PyTransformOptions (PyTransformOptions && other) inline
Definition at line 29 of file TransformInterpreter.cpp.
References options, and PyTransformOptions().
PyTransformOptions() [3/3]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions::PyTransformOptions (const PyTransformOptions &) delete
References PyTransformOptions().
~PyTransformOptions()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions::~PyTransformOptions () inline
Definition at line 35 of file TransformInterpreter.cpp.
References mlirTransformOptionsDestroy(), and options.
Member Data Documentation
options
MlirTransformOptions mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform_interpreter::PyTransformOptions::options
Definition at line 37 of file TransformInterpreter.cpp.
Referenced by PyTransformOptions(), PyTransformOptions(), and ~PyTransformOptions().
The documentation for this struct was generated from the following file:
lib/Bindings/Python/TransformInterpreter.cpp