MLIR: mlir::RegisteredOperationName::Model< ConcreteOp > Struct Template Reference
mlir::RegisteredOperationName::Model< ConcreteOp > Struct Template Reference
Implementation of the InterfaceConcept for operation APIs that forwarded to a concrete op implementation.
#include "mlir/IR/OperationSupport.h"
Public Types
using Properties
Public Member Functions
Model (Dialect *dialect)
LogicalResult foldHook (Operation *op, ArrayRef< Attribute > attrs, SmallVectorImpl< OpFoldResult > &results) final
void getCanonicalizationPatterns (RewritePatternSet &set, MLIRContext *context) final
bool hasTrait (TypeID id) final
OperationName::ParseAssemblyFn getParseAssemblyFn () final
void populateDefaultAttrs (const OperationName &name, NamedAttrList &attrs) final
void printAssembly (Operation *op, OpAsmPrinter &printer, StringRef name) final
LogicalResult verifyInvariants (Operation *op) final
LogicalResult verifyRegionInvariants (Operation *op) final
std::optional< Attribute > getInherentAttr (Operation *op, StringRef name) final
Implementation for "Properties".
void setInherentAttr (Operation *op, StringAttr name, Attribute value) final
void populateInherentAttrs (Operation *op, NamedAttrList &attrs) final
LogicalResult verifyInherentAttrs (OperationName opName, NamedAttrList &attributes, function_ref< InFlightDiagnostic()> emitError) final
int getOpPropertyByteSize () final
void initProperties (OperationName opName, PropertyRef storage, PropertyRef init) final
void deleteProperties (PropertyRef prop) final
void populateDefaultProperties (OperationName opName, PropertyRef properties) final
LogicalResult setPropertiesFromAttr (OperationName opName, PropertyRef properties, Attribute attr, function_ref< InFlightDiagnostic()> emitError) final
Attribute getPropertiesAsAttr (Operation *op) final
bool compareProperties (PropertyRef lhs, PropertyRef rhs) final
void copyProperties (PropertyRef lhs, PropertyRef rhs) final
llvm::hash_code hashProperties (PropertyRef prop) final
Public Member Functions inherited from mlir::OperationName::Impl
Impl (StringRef, Dialect *dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
Impl (StringAttr name, Dialect *dialect, TypeID typeID, detail::InterfaceMap interfaceMap)
bool isRegistered () const
Returns true if this is a registered operation.
detail::InterfaceMap & getInterfaceMap ()
Dialect * getDialect () const
StringAttr getName () const
TypeID getTypeID () const
TypeID getPropertiesTypeID () const
ArrayRef< StringAttr > getAttributeNames () const
Public Member Functions inherited from mlir::OperationName::InterfaceConcept
virtual ~InterfaceConcept ()=default
Static Public Attributes
static constexpr bool hasProperties
Additional Inherited Members
Protected Attributes inherited from mlir::OperationName::Impl
StringAttr name
The name of the operation.
TypeID typeID
The unique identifier of the derived Op class.
Dialect * dialect
The following fields are only populated when the operation is registered.
detail::InterfaceMap interfaceMap
A map of interfaces that were registered to this operation.
ArrayRef< StringAttr > attributeNames
A list of attribute names registered to this operation in StringAttr form.
TypeID propertiesTypeID
The TypeID of the Properties struct for this operation.
Detailed Description
template<typename ConcreteOp>
struct mlir::RegisteredOperationName::Model< ConcreteOp >
Implementation of the InterfaceConcept for operation APIs that forwarded to a concrete op implementation.
Definition at line 554 of file OperationSupport.h.
Member Typedef Documentation
Properties
template<typename ConcreteOp> using mlir::RegisteredOperationName::Model< ConcreteOp >::Properties
Initial value:
 std::remove_reference_t<
        decltype(std::declval<ConcreteOp>().getProperties())>
Definition at line 555 of file OperationSupport.h.
Constructor & Destructor Documentation
Model()
template<typename ConcreteOp> mlir::RegisteredOperationName::Model< ConcreteOp >::Model (Dialect * dialect) inline
Definition at line 557 of file OperationSupport.h.
References mlir::OperationName::Impl::dialect, mlir::get(), mlir::TypeID::get(), mlir::OperationName::Impl::getInterfaceMap(), mlir::OperationName::Impl::Impl(), and mlir::OperationName::Impl::propertiesTypeID.
Member Function Documentation
compareProperties()
template<typename ConcreteOp> bool mlir::RegisteredOperationName::Model< ConcreteOp >::compareProperties (PropertyRef lhs, PropertyRef rhs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 675 of file OperationSupport.h.
References hasProperties, lhs, and rhs.
copyProperties()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::copyProperties (PropertyRef lhs, PropertyRef rhs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 680 of file OperationSupport.h.
References lhs, and rhs.
deleteProperties()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::deleteProperties (PropertyRef prop) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 646 of file OperationSupport.h.
foldHook()
template<typename ConcreteOp> LogicalResult mlir::RegisteredOperationName::Model< ConcreteOp >::foldHook (Operation * op, ArrayRef< Attribute > attrs, SmallVectorImpl< OpFoldResult > & results) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 562 of file OperationSupport.h.
getCanonicalizationPatterns()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::getCanonicalizationPatterns (RewritePatternSet & set, MLIRContext * context) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 566 of file OperationSupport.h.
getInherentAttr()
template<typename ConcreteOp> std::optional< Attribute > mlir::RegisteredOperationName::Model< ConcreteOp >::getInherentAttr (Operation * op, StringRef name) inline final virtual
Implementation for "Properties".
Implements mlir::OperationName::InterfaceConcept.
Definition at line 591 of file OperationSupport.h.
References hasProperties, and mlir::OperationName::Impl::name.
getOpPropertyByteSize()
template<typename ConcreteOp> int mlir::RegisteredOperationName::Model< ConcreteOp >::getOpPropertyByteSize () inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 629 of file OperationSupport.h.
References hasProperties.
getParseAssemblyFn()
template<typename ConcreteOp> OperationName::ParseAssemblyFn mlir::RegisteredOperationName::Model< ConcreteOp >::getParseAssemblyFn () inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 571 of file OperationSupport.h.
getPropertiesAsAttr()
template<typename ConcreteOp> Attribute mlir::RegisteredOperationName::Model< ConcreteOp >::getPropertiesAsAttr (Operation * op) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 667 of file OperationSupport.h.
References hasProperties.
hashProperties()
template<typename ConcreteOp> llvm::hash_code mlir::RegisteredOperationName::Model< ConcreteOp >::hashProperties (PropertyRef prop) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 683 of file OperationSupport.h.
References hasProperties.
hasTrait()
template<typename ConcreteOp> bool mlir::RegisteredOperationName::Model< ConcreteOp >::hasTrait (TypeID id) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 570 of file OperationSupport.h.
initProperties()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::initProperties (OperationName opName, PropertyRef storage, PropertyRef init) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 634 of file OperationSupport.h.
References hasProperties.
populateDefaultAttrs()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::populateDefaultAttrs (const OperationName & name, NamedAttrList & attrs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 574 of file OperationSupport.h.
References mlir::OperationName::Impl::name.
populateDefaultProperties()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::populateDefaultProperties (OperationName opName, PropertyRef properties) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 649 of file OperationSupport.h.
References hasProperties.
populateInherentAttrs()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::populateInherentAttrs (Operation * op, NamedAttrList & attrs) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 610 of file OperationSupport.h.
References hasProperties.
printAssembly()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::printAssembly (Operation * op, OpAsmPrinter & printer, StringRef name) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 578 of file OperationSupport.h.
References mlir::OperationName::Impl::name.
setInherentAttr()
template<typename ConcreteOp> void mlir::RegisteredOperationName::Model< ConcreteOp >::setInherentAttr (Operation * op, StringAttr name, Attribute value) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 600 of file OperationSupport.h.
References hasProperties, and mlir::OperationName::Impl::name.
setPropertiesFromAttr()
template<typename ConcreteOp> LogicalResult mlir::RegisteredOperationName::Model< ConcreteOp >::setPropertiesFromAttr (OperationName opName, PropertyRef properties, Attribute attr, function_ref< InFlightDiagnostic()> emitError) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 657 of file OperationSupport.h.
References mlir::PropertyRef::as(), mlir::emitError(), and hasProperties.
verifyInherentAttrs()
template<typename ConcreteOp> LogicalResult mlir::RegisteredOperationName::Model< ConcreteOp >::verifyInherentAttrs (OperationName opName, NamedAttrList & attributes, function_ref< InFlightDiagnostic()> emitError) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 618 of file OperationSupport.h.
References mlir::emitError(), hasProperties, and success().
verifyInvariants()
template<typename ConcreteOp> LogicalResult mlir::RegisteredOperationName::Model< ConcreteOp >::verifyInvariants (Operation * op) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 582 of file OperationSupport.h.
verifyRegionInvariants()
template<typename ConcreteOp> LogicalResult mlir::RegisteredOperationName::Model< ConcreteOp >::verifyRegionInvariants (Operation * op) inline final virtual
Implements mlir::OperationName::InterfaceConcept.
Definition at line 585 of file OperationSupport.h.
Member Data Documentation
hasProperties
template<typename ConcreteOp> bool mlir::RegisteredOperationName::Model< ConcreteOp >::hasProperties static constexpr
Initial value:
= !std::is_same_v<
        typename ConcreteOp::template InferredProperties<ConcreteOp>,
        EmptyProperties>
Definition at line 625 of file OperationSupport.h.
Referenced by compareProperties(), getInherentAttr(), getOpPropertyByteSize(), getPropertiesAsAttr(), hashProperties(), initProperties(), populateDefaultProperties(), populateInherentAttrs(), setInherentAttr(), setPropertiesFromAttr(), and verifyInherentAttrs().
The documentation for this struct was generated from the following file:
include/mlir/IR/OperationSupport.h