MLIR: mlir::affine::LoopNestStateCollector Struct Reference
mlir::affine::LoopNestStateCollector Struct Reference
#include "mlir/Dialect/Affine/Analysis/Utils.h"
Public Member Functions
void collect (Operation *opToWalk)
Public Attributes
SmallVector< AffineForOp, 4 > forOps
SmallVector< Operation *, 4 > loadOpInsts
SmallVector< Operation *, 4 > storeOpInsts
SmallVector< Operation *, 4 > memrefLoads
SmallVector< Operation *, 4 > memrefStores
SmallVector< Operation *, 4 > memrefFrees
Detailed Description
Definition at line 38 of file Utils.h.
Member Function Documentation
collect()
void LoopNestStateCollector::collect (Operation * opToWalk)
Definition at line 41 of file Utils.cpp.
References mlir::Operation::getOperands(), mlir::Operation::hasTrait(), and mlir::Operation::walk().
Referenced by addNodeToMDG().
Member Data Documentation
forOps
SmallVector<AffineForOp, 4> mlir::affine::LoopNestStateCollector::forOps
Definition at line 39 of file Utils.h.
loadOpInsts
SmallVector<Operation *, 4> mlir::affine::LoopNestStateCollector::loadOpInsts
Definition at line 41 of file Utils.h.
Referenced by addNodeToMDG().
memrefFrees
SmallVector<Operation *, 4> mlir::affine::LoopNestStateCollector::memrefFrees
Definition at line 49 of file Utils.h.
Referenced by addNodeToMDG().
memrefLoads
SmallVector<Operation *, 4> mlir::affine::LoopNestStateCollector::memrefLoads
Definition at line 45 of file Utils.h.
Referenced by addNodeToMDG().
memrefStores
SmallVector<Operation *, 4> mlir::affine::LoopNestStateCollector::memrefStores
Definition at line 47 of file Utils.h.
Referenced by addNodeToMDG().
storeOpInsts
SmallVector<Operation *, 4> mlir::affine::LoopNestStateCollector::storeOpInsts
Definition at line 43 of file Utils.h.
Referenced by addNodeToMDG().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Affine/Analysis/Utils.h
lib/Dialect/Affine/Analysis/Utils.cpp