MLIR: llvm::DenseMapInfo< mlir::TypeID > Struct Reference
llvm::DenseMapInfo< mlir::TypeID > Struct Reference
#include "mlir/Support/TypeID.h"
Static Public Member Functions
static mlir::TypeID getEmptyKey ()
static mlir::TypeID getTombstoneKey ()
static unsigned getHashValue (mlir::TypeID val)
static bool isEqual (mlir::TypeID lhs, mlir::TypeID rhs)
Detailed Description
Definition at line 396 of file TypeID.h.
Member Function Documentation
getEmptyKey()
static mlir::TypeID llvm::DenseMapInfo< mlir::TypeID >::getEmptyKey () inline static
Definition at line 397 of file TypeID.h.
References mlir::TypeID::getFromOpaquePointer().
getHashValue()
static unsigned llvm::DenseMapInfo< mlir::TypeID >::getHashValue (mlir::TypeID val) inline static
Definition at line 405 of file TypeID.h.
References mlir::hash_value().
getTombstoneKey()
static mlir::TypeID llvm::DenseMapInfo< mlir::TypeID >::getTombstoneKey () inline static
Definition at line 401 of file TypeID.h.
References mlir::TypeID::getFromOpaquePointer().
isEqual()
static bool llvm::DenseMapInfo< mlir::TypeID >::isEqual (mlir::TypeID lhs, mlir::TypeID rhs) inline static
Definition at line 408 of file TypeID.h.
The documentation for this struct was generated from the following file:
include/mlir/Support/TypeID.h