MLIR: ShardingPropagation Struct Reference
ShardingPropagation Struct Reference
Public Member Functions
void runOnOperation () override
Detailed Description
Definition at line 358 of file ShardingPropagation.cpp.
Member Function Documentation
runOnOperation()
void ShardingPropagation::runOnOperation () inline override
Definition at line 363 of file ShardingPropagation.cpp.
References mlir::shard::Backward, mlir::shard::BackwardForward, DBGS, mlir::shard::ForwardBackward, mlir::Region::front(), mlir::Block::getOperations(), mlir::Region::hasOneBlock(), mlir::verify(), and visitOp().
The documentation for this struct was generated from the following file:
lib/Dialect/Shard/Transforms/ShardingPropagation.cpp