MLIR: GpuAsyncRegionPass::ThreadTokenCallback Struct Reference
GpuAsyncRegionPass::ThreadTokenCallback Struct Reference
Public Member Functions
ThreadTokenCallback (MLIRContext &context)
WalkResult operator() (Block *block)
Detailed Description
Definition at line 47 of file AsyncRegionRewriter.cpp.
Constructor & Destructor Documentation
ThreadTokenCallback()
GpuAsyncRegionPass::ThreadTokenCallback::ThreadTokenCallback (MLIRContext & context) inline
Definition at line 48 of file AsyncRegionRewriter.cpp.
Member Function Documentation
operator()()
WalkResult GpuAsyncRegionPass::ThreadTokenCallback::operator() (Block * block) inline
Definition at line 50 of file AsyncRegionRewriter.cpp.
References mlir::WalkResult::advance(), copy(), mlir::Operation::create(), mlir::Operation::emitOpError(), mlir::Operation::erase(), mlir::failed(), mlir::Operation::getAttrDictionary(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), mlir::Operation::getSuccessors(), hasSideEffects(), mlir::WalkResult::interrupt(), isTerminator(), loc, op, mlir::Operation::replaceAllUsesWith(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/GPU/Transforms/AsyncRegionRewriter.cpp