MLIR: mlir::vector::ScalableValueBoundsConstraintSet::ConstantOrScalableBound Struct Reference
mlir::vector::ScalableValueBoundsConstraintSet::ConstantOrScalableBound Struct Reference
A thin wrapper over an AffineMap which can represent a constant bound, or a scalable bound (in terms of vscale).
#include "mlir/Dialect/Vector/IR/ScalableValueBoundsConstraintSet.h"
Classes
struct BoundSize
Public Member Functions
FailureOr< BoundSize > getSize () const
Get the (possibly) scalable size of the bound, returns failure if the bound cannot be represented as a single quantity.
Public Attributes
AffineMap map
Detailed Description
A thin wrapper over an AffineMap which can represent a constant bound, or a scalable bound (in terms of vscale).
The AffineMap will always take at most one parameter, vscale, and returns a single result, which is the bound of value.
Definition at line 47 of file ScalableValueBoundsConstraintSet.h.
Member Function Documentation
getSize()
FailureOr< ConstantOrScalableBound::BoundSize > mlir::vector::ConstantOrScalableBound::getSize () const
Get the (possibly) scalable size of the bound, returns failure if the bound cannot be represented as a single quantity.
Definition at line 14 of file ScalableValueBoundsConstraintSet.cpp.
References mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::AffineMap::getSingleConstantResult(), mlir::AffineMap::isSingleConstant(), map, and mlir::Mul.
Member Data Documentation
map
AffineMap mlir::vector::ScalableValueBoundsConstraintSet::ConstantOrScalableBound::map
Definition at line 48 of file ScalableValueBoundsConstraintSet.h.
Referenced by getSize().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Vector/IR/ScalableValueBoundsConstraintSet.h
lib/Dialect/Vector/IR/ScalableValueBoundsConstraintSet.cpp