MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError Struct Reference
Custom exception that allows access to error diagnostic information.
#include "mlir/Bindings/Python/IRCore.h"
Public Member Functions
MLIRError (std::string message, std::vector< PyDiagnostic::DiagnosticInfo > &&errorDiagnostics={})
const char * what () const noexcept override
Static Public Member Functions
static void bind (nanobind::module_ &m)
Bind the MLIRError exception class to the given module.
Public Attributes
std::string message
std::vector< PyDiagnostic::DiagnosticInfo > errorDiagnostics
Detailed Description
Custom exception that allows access to error diagnostic information.
This is translated to the ir.MLIRError python exception when thrown.
Definition at line 1459 of file IRCore.h.
Constructor & Destructor Documentation
MLIRError()
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::MLIRError (std::string message, std::vector< PyDiagnostic::DiagnosticInfo > && errorDiagnostics = {}) inline
Definition at line 1460 of file IRCore.h.
References errorDiagnostics, and message.
Referenced by bind().
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::bind (nanobind::module_ & m) static
Bind the MLIRError exception class to the given module.
Definition at line 2862 of file IRCore.cpp.
References errorDiagnostics, mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::formatMLIRError(), message, and MLIRError().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
what()
const char * mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::what () const inline override noexcept
Definition at line 1464 of file IRCore.h.
References message.
Member Data Documentation
errorDiagnostics
std::vector<PyDiagnostic::DiagnosticInfo> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::errorDiagnostics
Definition at line 1470 of file IRCore.h.
Referenced by bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::formatMLIRError(), and MLIRError().
message
std::string mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::MLIRError::message
Definition at line 1469 of file IRCore.h.
Referenced by bind(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::formatMLIRError(), MLIRError(), and what().
The documentation for this struct was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp