MLIR: BuiltinDialectVersion Struct Reference
BuiltinDialectVersion Struct Reference
#include "mlir/IR/BuiltinDialect.h"
Public Member Functions
BuiltinDialectVersion (int64_t version)
int64_t getVersion () const
bool operator< (const BuiltinDialectVersion &other) const
Public Member Functions inherited from mlir::DialectVersion
virtual ~DialectVersion ()=default
Static Public Member Functions
static BuiltinDialectVersion getCurrentVersion ()
Detailed Description
Definition at line 24 of file BuiltinDialect.h.
Constructor & Destructor Documentation
BuiltinDialectVersion()
BuiltinDialectVersion::BuiltinDialectVersion (int64_t version) inline
Definition at line 25 of file BuiltinDialect.h.
Referenced by getCurrentVersion(), and operator<().
Member Function Documentation
getCurrentVersion()
BuiltinDialectVersion BuiltinDialectVersion::getCurrentVersion () inline static
Definition at line 29 of file BuiltinDialect.h.
References BuiltinDialectVersion().
getVersion()
int64_t BuiltinDialectVersion::getVersion () const inline
Definition at line 27 of file BuiltinDialect.h.
operator<()
bool BuiltinDialectVersion::operator< (const BuiltinDialectVersion & other) const inline
Definition at line 31 of file BuiltinDialect.h.
References BuiltinDialectVersion().
The documentation for this struct was generated from the following file:
include/mlir/IR/BuiltinDialect.h