MLIR: mlir::spirv::detail::CooperativeMatrixTypeStorage Struct Reference
mlir::spirv::detail::CooperativeMatrixTypeStorage Struct Reference final
Public Types
using KeyTy
Public Member Functions
bool operator== (const KeyTy &key) const
CooperativeMatrixTypeStorage (const KeyTy &key)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static CooperativeMatrixTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type elementType
std::array< int64_t, 2 > shape
Scope scope
CooperativeMatrixUseKHR use
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 230 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::CooperativeMatrixTypeStorage::KeyTy
Initial value:
      std::tuple<Type, int64_t, int64_t, Scope, CooperativeMatrixUseKHR>
Definition at line 244 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
CooperativeMatrixTypeStorage()
mlir::spirv::detail::CooperativeMatrixTypeStorage::CooperativeMatrixTypeStorage (const KeyTy & key) inline
Definition at line 257 of file SPIRVTypes.cpp.
References elementType, mlir::get(), and shape.
Referenced by construct().
Member Function Documentation
construct()
CooperativeMatrixTypeStorage * mlir::spirv::detail::CooperativeMatrixTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 248 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and CooperativeMatrixTypeStorage().
operator==()
bool mlir::spirv::detail::CooperativeMatrixTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 253 of file SPIRVTypes.cpp.
References elementType, scope, shape, and use.
Member Data Documentation
elementType
Type mlir::spirv::detail::CooperativeMatrixTypeStorage::elementType
Definition at line 262 of file SPIRVTypes.cpp.
Referenced by CooperativeMatrixTypeStorage(), and operator==().
scope
Scope mlir::spirv::detail::CooperativeMatrixTypeStorage::scope
Definition at line 265 of file SPIRVTypes.cpp.
Referenced by operator==().
shape
std::array<int64_t, 2> mlir::spirv::detail::CooperativeMatrixTypeStorage::shape
Definition at line 264 of file SPIRVTypes.cpp.
Referenced by CooperativeMatrixTypeStorage(), and operator==().
use
CooperativeMatrixUseKHR mlir::spirv::detail::CooperativeMatrixTypeStorage::use
Definition at line 266 of file SPIRVTypes.cpp.
Referenced by operator==().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp