MLIR: mlir::linalg::ExtractSliceOfPadTensorSwapPattern Struct Reference
mlir::linalg::ExtractSliceOfPadTensorSwapPattern Struct Reference
Rewrite extract_slice(tensor.pad(x)) into tensor.pad(extract_slice(x)).
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Types
using ControlFn = std::function<std::optional<bool>(tensor::ExtractSliceOp)>
A function to control pattern application and rewrite logic.
Public Types inherited from mlir::OpRewritePattern< tensor::ExtractSliceOp >
using Base
Type alias to allow derived classes to inherit constructors with using Base::Base;.
Public Member Functions
ExtractSliceOfPadTensorSwapPattern (MLIRContext *context, ControlFn controlFn=nullptr, PatternBenefit benefit=1)
LogicalResult matchAndRewrite (tensor::ExtractSliceOp sliceOp, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< tensor::ExtractSliceOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1, ArrayRef< StringRef > generatedNames={})
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching and a list of generated ops.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< tensor::ExtractSliceOp >
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Wrapper around the RewritePattern method that passes the derived op type.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T, typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Rewrite extract_slice(tensor.pad(x)) into tensor.pad(extract_slice(x)).
Definition at line 1801 of file Transforms.h.
Member Typedef Documentation
ControlFn
using mlir::linalg::ExtractSliceOfPadTensorSwapPattern::ControlFn = std::function<std::optional<bool>(tensor::ExtractSliceOp)>
A function to control pattern application and rewrite logic.
The function will be given the slice op and should return:
std::nullopt: to fail the match and not apply the pattern;
true: to apply the pattern with zero slice guard;
false: to apply the pattern without zero slice guard.
See the documentation for tensor::bubbleUpPadSlice regarding zero slice guard.
Definition at line 1812 of file Transforms.h.
Constructor & Destructor Documentation
ExtractSliceOfPadTensorSwapPattern()
mlir::linalg::ExtractSliceOfPadTensorSwapPattern::ExtractSliceOfPadTensorSwapPattern (MLIRContext * context, ControlFn controlFn = nullptr, PatternBenefit benefit = 1) inline
Definition at line 1814 of file Transforms.h.
References mlir::OpRewritePattern< tensor::ExtractSliceOp >::OpRewritePattern().
Member Function Documentation
matchAndRewrite()
LogicalResult ExtractSliceOfPadTensorSwapPattern::matchAndRewrite (tensor::ExtractSliceOp sliceOp, PatternRewriter & rewriter) const override
Definition at line 972 of file Transforms.cpp.
References mlir::tensor::bubbleUpPadSlice(), mlir::tensor::createCanonicalRankReducingExtractSliceOp(), mlir::RewriterBase::replaceOp(), and success().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Transforms.cpp