MLIR: nanobind::detail::type_caster< MlirLocation > Struct Reference
nanobind::detail::type_caster< MlirLocation > Struct Reference
Casts object <-> MlirLocation.
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Public Member Functions
bool from_python (handle src, uint8_t flags, cleanup_list *cleanup) noexcept
Static Public Member Functions
static handle from_cpp (MlirLocation v, rv_policy, cleanup_list *cleanup) noexcept
Detailed Description
Casts object <-> MlirLocation.
Definition at line 165 of file NanobindAdaptors.h.
Member Function Documentation
from_cpp()
static handle nanobind::detail::type_caster< MlirLocation >::from_cpp (MlirLocation v, rv_policy , cleanup_list * cleanup) inline static noexcept
Definition at line 180 of file NanobindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonLocationToCapsule().
from_python()
bool nanobind::detail::type_caster< MlirLocation >::from_python (handle src, uint8_t flags, cleanup_list * cleanup) inline noexcept
Definition at line 167 of file NanobindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, nanobind::detail::mlirApiObjectToCapsule(), mlirLocationIsNull(), and mlirPythonCapsuleToLocation().
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/NanobindAdaptors.h