MLIR: llvm::DenseMapInfo< mlir::Location > Struct Reference
llvm::DenseMapInfo< mlir::Location > Struct Reference
#include "mlir/IR/Location.h"
Static Public Member Functions
static mlir::Location getEmptyKey ()
static mlir::Location getTombstoneKey ()
static unsigned getHashValue (mlir::Location val)
static bool isEqual (mlir::Location LHS, mlir::Location RHS)
Detailed Description
Definition at line 230 of file Location.h.
Member Function Documentation
getEmptyKey()
static mlir::Location llvm::DenseMapInfo< mlir::Location >::getEmptyKey () inline static
Definition at line 231 of file Location.h.
References mlir::Location::getFromOpaquePointer().
getHashValue()
static unsigned llvm::DenseMapInfo< mlir::Location >::getHashValue (mlir::Location val) inline static
Definition at line 239 of file Location.h.
References mlir::hash_value().
getTombstoneKey()
static mlir::Location llvm::DenseMapInfo< mlir::Location >::getTombstoneKey () inline static
Definition at line 235 of file Location.h.
References mlir::Location::getFromOpaquePointer().
isEqual()
static bool llvm::DenseMapInfo< mlir::Location >::isEqual (mlir::Location LHS, mlir::Location RHS) inline static
Definition at line 242 of file Location.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/Location.h