MLIR: mlir::OpConversionPattern< SourceOp > Struct Template Reference
mlir::OpConversionPattern< SourceOp > Struct Template Reference
OpConversionPattern is a wrapper around ConversionPattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
#include "mlir/Transforms/DialectConversion.h"
Public Member Functions
OpConversionPattern (MLIRContext *context, PatternBenefit benefit=1)
OpConversionPattern (TypeConverter &typeConverter, MLIRContext *context, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::detail::OpOrInterfaceConversionPatternBase< SourceOp >
void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Wrappers around the ConversionPattern methods that pass the derived op type.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
virtual void rewrite (SourceOp op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
virtual LogicalResult matchAndRewrite (SourceOp op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Public Member Functions inherited from mlir::ConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&... args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::ConversionPattern
template<typename... Args>
ConversionPattern (TypeConverter &typeConverter, Args &&... args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
template<typename SourceOp>
struct mlir::OpConversionPattern< SourceOp >
OpConversionPattern is a wrapper around ConversionPattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
Definition at line 416 of file DialectConversion.h.
Constructor & Destructor Documentation
OpConversionPattern() [1/2]
template<typename SourceOp> mlir::OpConversionPattern< SourceOp >::OpConversionPattern (MLIRContext * context, PatternBenefit benefit = 1) inline
Definition at line 418 of file DialectConversion.h.
Referenced by addResumeFunction(), getFirstIntValue(), getLocalInvocationDimSize(), outlineExecuteOp(), mlir::populateBufferizeMaterializationLegality(), and sourceMaterializationCallback().
OpConversionPattern() [2/2]
template<typename SourceOp> mlir::OpConversionPattern< SourceOp >::OpConversionPattern (TypeConverter & typeConverter, MLIRContext * context, PatternBenefit benefit = 1) inline
Definition at line 421 of file DialectConversion.h.
The documentation for this struct was generated from the following file:
include/mlir/Transforms/DialectConversion.h