MLIR: mlir::shard::ElementwiseShardingInterface< ElemwiseOp > Struct Template Reference
mlir::shard::ElementwiseShardingInterface< ElemwiseOp > Struct Template Reference
#include "mlir/Dialect/Shard/Interfaces/ShardingInterfaceImpl.h"
Public Member Functions
SmallVector< utils::IteratorType > getLoopIteratorTypes (Operation *op) const
SmallVector< AffineMap > getIndexingMaps (Operation *op) const
LogicalResult partition (Operation *op, ArrayRef< Value > partitionedOperands, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, IRMapping &partitionMap, SymbolTableCollection &symbolTable, OpBuilder &builder) const
Detailed Description
template<typename ElemwiseOp>
struct mlir::shard::ElementwiseShardingInterface< ElemwiseOp >
Definition at line 105 of file ShardingInterfaceImpl.h.
Member Function Documentation
getIndexingMaps()
template<typename ElemwiseOp> SmallVector< AffineMap > mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getIndexingMaps (Operation * op) const inline
Definition at line 118 of file ShardingInterfaceImpl.h.
References mlir::Operation::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), and mlir::Value::getType().
getLoopIteratorTypes()
template<typename ElemwiseOp> SmallVector< utils::IteratorType > mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::getLoopIteratorTypes (Operation * op) const inline
Definition at line 108 of file ShardingInterfaceImpl.h.
References mlir::Operation::getOperand(), and mlir::Value::getType().
partition()
template<typename ElemwiseOp> LogicalResult mlir::shard::ElementwiseShardingInterface< ElemwiseOp >::partition (Operation * op, ArrayRef< Value > partitionedOperands, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, IRMapping & partitionMap, SymbolTableCollection & symbolTable, OpBuilder & builder) const inline
Definition at line 131 of file ShardingInterfaceImpl.h.
References mlir::shard::partitionTriviallyShardableOperation(), and success().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Shard/Interfaces/ShardingInterfaceImpl.h