MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info Struct Reference
#include "mlir/Bindings/Python/IRAttributes.h"
Public Member Functions
nb_buffer_info (void *ptr, Py_ssize_t itemsize, const char *format, Py_ssize_t ndim, std::vector< Py_ssize_t > shape_in, std::vector< Py_ssize_t > strides_in, bool readonly=false, std::unique_ptr< Py_buffer, void(*)(Py_buffer *)> owned_view_in=std::unique_ptr< Py_buffer, void(*)(Py_buffer *)>(nullptr, nullptr))
nb_buffer_info (Py_buffer *view)
nb_buffer_info (const nb_buffer_info &)=delete
nb_buffer_info (nb_buffer_info &&)=default
nb_buffer_info & operator= (const nb_buffer_info &)=delete
nb_buffer_info & operator= (nb_buffer_info &&)=default
Public Attributes
void * ptr = nullptr
Py_ssize_t itemsize = 0
Py_ssize_t size = 0
const char * format = nullptr
Py_ssize_t ndim = 0
std::vector< Py_ssize_t > shape
std::vector< Py_ssize_t > strides
bool readonly = false
Detailed Description
Definition at line 29 of file IRAttributes.h.
Constructor & Destructor Documentation
nb_buffer_info() [1/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::nb_buffer_info (void * ptr, Py_ssize_t itemsize, const char * format, Py_ssize_t ndim, std::vector< Py_ssize_t > shape_in, std::vector< Py_ssize_t > strides_in, bool readonly = false, std::unique_ptr< Py_buffer, void(* owned_view_in)(Py_buffer *)> = std::unique_ptr<Py_buffer, void (*)(Py_buffer *)>(nullptr, nullptr))
Definition at line 156 of file IRAttributes.cpp.
References format, itemsize, ndim, ptr, readonly, shape, size, and strides.
Referenced by nb_buffer_info(), nb_buffer_info(), nb_buffer_info(), operator=(), and operator=().
nb_buffer_info() [2/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::nb_buffer_info (Py_buffer * view) inline explicit
Definition at line 46 of file IRAttributes.h.
References format, itemsize, nb_buffer_info(), and ndim.
nb_buffer_info() [3/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::nb_buffer_info (const nb_buffer_info &) delete
References nb_buffer_info().
nb_buffer_info() [4/4]
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::nb_buffer_info (nb_buffer_info &&) default
References nb_buffer_info().
Member Function Documentation
operator=() [1/2]
nb_buffer_info & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::operator= (const nb_buffer_info &) delete
References nb_buffer_info().
operator=() [2/2]
nb_buffer_info & mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::operator= (nb_buffer_info &&) default
References nb_buffer_info().
Member Data Documentation
format
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::format = nullptr
Definition at line 33 of file IRAttributes.h.
Referenced by nb_buffer_info(), and nb_buffer_info().
itemsize
Py_ssize_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::itemsize = 0
Definition at line 31 of file IRAttributes.h.
Referenced by nb_buffer_info(), and nb_buffer_info().
ndim
Py_ssize_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::ndim = 0
Definition at line 34 of file IRAttributes.h.
Referenced by nb_buffer_info(), and nb_buffer_info().
ptr
void* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::ptr = nullptr
Definition at line 30 of file IRAttributes.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpaqueAttribute::bindDerived(), and nb_buffer_info().
readonly
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::readonly = false
Definition at line 37 of file IRAttributes.h.
Referenced by nb_buffer_info().
shape
std::vector<Py_ssize_t> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::shape
Definition at line 35 of file IRAttributes.h.
Referenced by nb_buffer_info().
size
Py_ssize_t mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::size = 0
Definition at line 32 of file IRAttributes.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyOpaqueAttribute::bindDerived(), and nb_buffer_info().
strides
std::vector<Py_ssize_t> mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::nb_buffer_info::strides
Definition at line 36 of file IRAttributes.h.
Referenced by nb_buffer_info().
The documentation for this struct was generated from the following files:
include/mlir/Bindings/Python/IRAttributes.h
lib/Bindings/Python/IRAttributes.cpp