MLIR: mlir::PassReproducerOptions Struct Reference
mlir::PassReproducerOptions Struct Reference
#include "mlir/Pass/PassRegistry.h"
Public Member Functions
void attachResourceParser (ParserConfig &config)
Attach an assembly resource parser to 'config' that collects the MLIR reproducer configuration into this instance.
LogicalResult apply (PassManager &pm) const
Apply the reproducer options to 'pm' and its context.
Detailed Description
Definition at line 300 of file PassRegistry.h.
Member Function Documentation
apply()
LogicalResult PassReproducerOptions::apply (PassManager & pm) const
Apply the reproducer options to 'pm' and its context.
Definition at line 517 of file PassCrashRecovery.cpp.
References mlir::MLIRContext::disableMultithreading(), mlir::PassManager::enableVerifier(), mlir::PassManager::getContext(), mlir::parsePassPipeline(), and success().
Referenced by performActions().
attachResourceParser()
void PassReproducerOptions::attachResourceParser (ParserConfig & config)
Attach an assembly resource parser to 'config' that collects the MLIR reproducer configuration into this instance.
Definition at line 491 of file PassCrashRecovery.cpp.
References mlir::config.
Referenced by performActions().
The documentation for this struct was generated from the following files:
include/mlir/Pass/PassRegistry.h
lib/Pass/PassCrashRecovery.cpp