MLIR: mlir::TranslateFromMLIRRegistration Struct Reference
mlir::TranslateFromMLIRRegistration Struct Reference
#include "mlir/Translation.h"
Public Member Functions
TranslateFromMLIRRegistration (llvm::StringRef name, const TranslateFromMLIRFunction &function, std::function< void(DialectRegistry &)> dialectRegistration=[](DialectRegistry &) {})
Detailed Description
Definition at line 78 of file Translation.h.
Constructor & Destructor Documentation
TranslateFromMLIRRegistration()
TranslateFromMLIRRegistration::TranslateFromMLIRRegistration (llvm::StringRef name, const TranslateFromMLIRFunction & function, std::function< void(DialectRegistry &)> dialectRegistration = [](DialectRegistry &) {})
Definition at line 95 of file Translation.cpp.
References mlir::MLIRContext::appendDialectRegistry(), mlir::failure(), mlir::parseSourceFile(), and registerTranslation().
The documentation for this struct was generated from the following files:
include/mlir/Translation.h
lib/Translation/Translation.cpp