MLIR: MlirTransformOpInterfaceCallbacks Struct Reference
MlirTransformOpInterfaceCallbacks Struct Reference
Callbacks for implementing TransformOpInterface from external code.
#include "mlir-c/Dialect/Transform.h"
Public Attributes
void(* construct)(void *userData)
Optional constructor for the user data.
void(* destruct)(void *userData)
Optional destructor for the user data.
MlirDiagnosedSilenceableFailure(* apply)(MlirOperation op, MlirTransformRewriter rewriter, MlirTransformResults results, MlirTransformState state, void *userData)
Apply callback that implements the transformation.
bool(* allowsRepeatedHandleOperands)(MlirOperation op, void *userData)
Callback to check if repeated handle operands are allowed.
void * userData
Detailed Description
Callbacks for implementing TransformOpInterface from external code.
Definition at line 186 of file Transform.h.
Member Data Documentation
allowsRepeatedHandleOperands
bool(* MlirTransformOpInterfaceCallbacks::allowsRepeatedHandleOperands) (MlirOperation op, void *userData)
Callback to check if repeated handle operands are allowed.
Definition at line 200 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::attach().
apply
MlirDiagnosedSilenceableFailure(* MlirTransformOpInterfaceCallbacks::apply) (MlirOperation op, MlirTransformRewriter rewriter, MlirTransformResults results, MlirTransformState state, void *userData)
Apply callback that implements the transformation.
Definition at line 194 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::attach().
construct
void(* MlirTransformOpInterfaceCallbacks::construct) (void *userData)
Optional constructor for the user data.
Set to nullptr to disable it.
Definition at line 189 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::attach().
destruct
void(* MlirTransformOpInterfaceCallbacks::destruct) (void *userData)
Optional destructor for the user data.
Set to nullptr to disable it.
Definition at line 192 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::attach().
userData
void* MlirTransformOpInterfaceCallbacks::userData
Definition at line 201 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyTransformOpInterface::attach().
The documentation for this struct was generated from the following file:
include/mlir-c/Dialect/Transform.h