MLIR: mlir::NVVM::NVVMCheckSMVersion Struct Reference
mlir::NVVM::NVVMCheckSMVersion Struct Reference
#include "mlir/Dialect/LLVMIR/NVVMRequiresSMTraits.h"
Public Member Functions
template<typename... Ints>
NVVMCheckSMVersion (bool archAccelerated, Ints... smVersions)
bool isCompatibleWith (const NVVMCheckSMVersion &targetSM) const
bool isMinimumSMVersion () const
Static Public Member Functions
static const NVVMCheckSMVersion getTargetSMVersionFromStr (StringRef smVersionString)
Public Attributes
bool archAccelerated
llvm::SmallVector< int, 1 > smVersionList
Detailed Description
Definition at line 25 of file NVVMRequiresSMTraits.h.
Constructor & Destructor Documentation
NVVMCheckSMVersion()
template<typename... Ints> mlir::NVVM::NVVMCheckSMVersion::NVVMCheckSMVersion (bool archAccelerated, Ints... smVersions) inline
Definition at line 36 of file NVVMRequiresSMTraits.h.
References archAccelerated, and smVersionList.
Referenced by getTargetSMVersionFromStr(), and isCompatibleWith().
Member Function Documentation
getTargetSMVersionFromStr()
const NVVMCheckSMVersion mlir::NVVM::NVVMCheckSMVersion::getTargetSMVersionFromStr (StringRef smVersionString) inline static
Definition at line 66 of file NVVMRequiresSMTraits.h.
References NVVMCheckSMVersion().
isCompatibleWith()
bool mlir::NVVM::NVVMCheckSMVersion::isCompatibleWith (const NVVMCheckSMVersion & targetSM) const inline
Definition at line 42 of file NVVMRequiresSMTraits.h.
References archAccelerated, NVVMCheckSMVersion(), and smVersionList.
isMinimumSMVersion()
bool mlir::NVVM::NVVMCheckSMVersion::isMinimumSMVersion () const inline
Definition at line 61 of file NVVMRequiresSMTraits.h.
References smVersionList.
Member Data Documentation
archAccelerated
bool mlir::NVVM::NVVMCheckSMVersion::archAccelerated
Definition at line 27 of file NVVMRequiresSMTraits.h.
Referenced by isCompatibleWith(), and NVVMCheckSMVersion().
smVersionList
llvm::SmallVector<int, 1> mlir::NVVM::NVVMCheckSMVersion::smVersionList
Definition at line 33 of file NVVMRequiresSMTraits.h.
Referenced by isCompatibleWith(), isMinimumSMVersion(), and NVVMCheckSMVersion().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/LLVMIR/NVVMRequiresSMTraits.h