MLIR: mlir::query::Query Struct Reference
mlir::query::Query Struct Reference abstract
#include "mlir/Query/Query.h"
Public Member Functions
Query (QueryKind kind)
virtual ~Query ()
virtual llvm::LogicalResult run (llvm::raw_ostream &os, QuerySession &qs) const =0
Public Attributes
llvm::StringRef remainingContent
const QueryKind kind
Detailed Description
Definition at line 24 of file Query.h.
Constructor & Destructor Documentation
Query()
mlir::query::Query::Query (QueryKind kind) inline
Definition at line 25 of file Query.h.
References kind.
Referenced by mlir::query::HelpQuery::classof(), mlir::query::InvalidQuery::classof(), mlir::query::MatchQuery::classof(), mlir::query::NoOpQuery::classof(), mlir::query::QuitQuery::classof(), mlir::query::HelpQuery::HelpQuery(), mlir::query::InvalidQuery::InvalidQuery(), mlir::query::MatchQuery::MatchQuery(), mlir::query::NoOpQuery::NoOpQuery(), and mlir::query::QuitQuery::QuitQuery().
~Query()
mlir::query::Query::~Query () virtual default
Member Function Documentation
run()
virtual llvm::LogicalResult mlir::query::Query::run (llvm::raw_ostream & os, QuerySession & qs) const pure virtual
Implemented in mlir::query::HelpQuery, mlir::query::InvalidQuery, mlir::query::MatchQuery, mlir::query::NoOpQuery, and mlir::query::QuitQuery.
Member Data Documentation
kind
const QueryKind mlir::query::Query::kind
Definition at line 33 of file Query.h.
Referenced by Query().
remainingContent
llvm::StringRef mlir::query::Query::remainingContent
Definition at line 32 of file Query.h.
The documentation for this struct was generated from the following files:
include/mlir/Query/Query.h
lib/Query/Query.cpp