MLIR: mlir::spirv::detail::PointerTypeStorage Struct Reference
mlir::spirv::detail::PointerTypeStorage Struct Reference
Public Types
using KeyTy = std::pair<Type, StorageClass>
Public Member Functions
bool operator== (const KeyTy &key) const
PointerTypeStorage (const KeyTy &key)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static PointerTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type pointeeType
StorageClass storageClass
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 429 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::PointerTypeStorage::KeyTy = std::pair<Type, StorageClass>
Definition at line 432 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
PointerTypeStorage()
mlir::spirv::detail::PointerTypeStorage::PointerTypeStorage (const KeyTy & key) inline
Definition at line 444 of file SPIRVTypes.cpp.
References pointeeType, and storageClass.
Referenced by construct().
Member Function Documentation
construct()
PointerTypeStorage * mlir::spirv::detail::PointerTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 434 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and PointerTypeStorage().
operator==()
bool mlir::spirv::detail::PointerTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 440 of file SPIRVTypes.cpp.
References pointeeType, and storageClass.
Member Data Documentation
pointeeType
Type mlir::spirv::detail::PointerTypeStorage::pointeeType
Definition at line 447 of file SPIRVTypes.cpp.
Referenced by operator==(), and PointerTypeStorage().
storageClass
StorageClass mlir::spirv::detail::PointerTypeStorage::storageClass
Definition at line 448 of file SPIRVTypes.cpp.
Referenced by operator==(), and PointerTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp