MLIR: AmdgpuMaskedloadToLoadPass Struct Reference
AmdgpuMaskedloadToLoadPass Struct Reference final
Public Member Functions
void runOnOperation () override
Detailed Description
Definition at line 233 of file MaskedloadToLoad.cpp.
Member Function Documentation
runOnOperation()
void AmdgpuMaskedloadToLoadPass::runOnOperation () inline override
Definition at line 235 of file MaskedloadToLoad.cpp.
References mlir::applyPatternsGreedily(), getContext(), mlir::patterns, and mlir::amdgpu::populateAmdgpuMaskedloadToLoadPatterns().
The documentation for this struct was generated from the following file:
lib/Dialect/AMDGPU/Transforms/MaskedloadToLoad.cpp