MLIR: mlir::spirv::detail::RuntimeArrayTypeStorage Struct Reference
mlir::spirv::detail::RuntimeArrayTypeStorage Struct Reference
Public Types
using KeyTy = std::pair<Type, unsigned>
Public Member Functions
bool operator== (const KeyTy &key) const
RuntimeArrayTypeStorage (const KeyTy &key)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static RuntimeArrayTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type elementType
unsigned stride
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 489 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::RuntimeArrayTypeStorage::KeyTy = std::pair<Type, unsigned>
Definition at line 490 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
RuntimeArrayTypeStorage()
mlir::spirv::detail::RuntimeArrayTypeStorage::RuntimeArrayTypeStorage (const KeyTy & key) inline
Definition at line 502 of file SPIRVTypes.cpp.
References elementType, and stride.
Referenced by construct().
Member Function Documentation
construct()
RuntimeArrayTypeStorage * mlir::spirv::detail::RuntimeArrayTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 492 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and RuntimeArrayTypeStorage().
operator==()
bool mlir::spirv::detail::RuntimeArrayTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 498 of file SPIRVTypes.cpp.
References elementType, and stride.
Member Data Documentation
elementType
Type mlir::spirv::detail::RuntimeArrayTypeStorage::elementType
Definition at line 505 of file SPIRVTypes.cpp.
Referenced by operator==(), and RuntimeArrayTypeStorage().
stride
unsigned mlir::spirv::detail::RuntimeArrayTypeStorage::stride
Definition at line 506 of file SPIRVTypes.cpp.
Referenced by operator==(), and RuntimeArrayTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp