MLIR: mlir::spirv::ElementwiseOpPattern< Op, SPIRVOp > Struct Template Reference
mlir::spirv::ElementwiseOpPattern< Op, SPIRVOp > Struct Template Reference
Converts elementwise unary, binary and ternary standard operations to SPIR-V operations.
#include "Conversion/SPIRVCommon/Pattern.h"
Public Member Functions
LogicalResult matchAndRewrite (Op op, typename Op::Adaptor adaptor, ConversionPatternRewriter &rewriter) const override
Detailed Description
template<typename Op, typename SPIRVOp>
struct mlir::spirv::ElementwiseOpPattern< Op, SPIRVOp >
Converts elementwise unary, binary and ternary standard operations to SPIR-V operations.
Definition at line 23 of file Pattern.h.
Member Function Documentation
matchAndRewrite()
template<typename Op, typename SPIRVOp> LogicalResult mlir::spirv::ElementwiseOpPattern< Op, SPIRVOp >::matchAndRewrite (Op op, typename Op::Adaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 27 of file Pattern.h.
References mlir::OpState::dump(), mlir::OpState::emitError(), mlir::getElementTypeOrSelf(), mlir::OpState::getLoc(), mlir::Type::isIndex(), and success().
The documentation for this struct was generated from the following file:
lib/Conversion/SPIRVCommon/Pattern.h