MLIR: pybind11::detail::type_caster< MlirBlock > Struct Reference
pybind11::detail::type_caster< MlirBlock > Struct Reference
Casts object -> MlirBlock.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirBlock, _("MlirBlock"))
bool load (handle src, bool)
Detailed Description
Casts object -> MlirBlock.
Definition at line 110 of file PybindAdaptors.h.
Member Function Documentation
load()
bool pybind11::detail::type_caster< MlirBlock >::load (handle src, bool) inline
Definition at line 112 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirBlockIsNull(), and mlirPythonCapsuleToBlock().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirBlock >::PYBIND11_TYPE_CASTER (MlirBlock , _("MlirBlock"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h