MLIR: mlir::bufferization::BranchOpBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp > Struct Template Reference
mlir::bufferization::BranchOpBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp > Struct Template Reference
A template that provides a default implementation of getAliasingValues for ops that implement the BranchOpInterface.
#include "mlir/Dialect/Bufferization/IR/UnstructuredControlFlow.h"
Public Member Functions
AliasingValueList getAliasingValues (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
Detailed Description
template<typename ConcreteModel, typename ConcreteOp>
struct mlir::bufferization::BranchOpBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp >
A template that provides a default implementation of getAliasingValues for ops that implement the BranchOpInterface.
Definition at line 139 of file UnstructuredControlFlow.h.
Member Function Documentation
getAliasingValues()
template<typename ConcreteModel, typename ConcreteOp> AliasingValueList mlir::bufferization::BranchOpBufferizableOpInterfaceExternalModel< ConcreteModel, ConcreteOp >::getAliasingValues (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 141 of file UnstructuredControlFlow.h.
References mlir::Block::getArgument(), mlir::OperandRange::getBeginOperandIndex(), mlir::SuccessorOperands::getForwardedOperands(), mlir::OpOperand::getOperandNumber(), mlir::SuccessorOperands::getProducedOperandCount(), mlir::Operation::getSuccessors(), and result.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Bufferization/IR/UnstructuredControlFlow.h