MLIR: PadOpVectorizationWithTransferWritePattern Struct Reference
PadOpVectorizationWithTransferWritePattern Struct Reference
Rewrite use of tensor::PadOp result in TransferWriteOp.
Public Member Functions
LogicalResult rewriteUser (PatternRewriter &rewriter, tensor::PadOp padOp, vector::TransferWriteOp xferOp) const override
bool hasSameTensorSize (Value beforePadding, tensor::ExtractSliceOp afterTrimming) const
Check if beforePadding and afterTrimming have the same tensor size, i.e., same dimensions.
Public Member Functions inherited from VectorizePadOpUserPattern< vector::TransferWriteOp >
LogicalResult matchAndRewrite (tensor::PadOp padOp, PatternRewriter &rewriter) const final
Public Member Functions inherited from mlir::OpRewritePattern< tensor::PadOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1, ArrayRef< StringRef > generatedNames={})
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching and a list of generated ops.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Wrapper around the RewritePattern method that passes the derived op type.
virtual LogicalResult matchAndRewrite (SourceOp op, PatternRewriter &rewriter) const =0
Method that operates on the SourceOp type.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from VectorizePadOpUserPattern< vector::TransferWriteOp >
virtual LogicalResult rewriteUser (PatternRewriter &rewriter, tensor::PadOp padOp, vector::TransferWriteOp op) const=0
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Rewrite use of tensor::PadOp result in TransferWriteOp.
This pattern rewrites TransferWriteOps that write to a padded tensor value, where the same amount of padding is immediately removed again after the write. In such cases, the TransferWriteOp can write to the non-padded tensor value and apply out-of-bounds masking. E.g.:
%0 = tensor.extract_slice ...[...] [%s0, %s1] [1, 1]
    : tensor<...> to tensor<?x?xf32>
%1 = tensor.pad %0 ... : tensor<?x?xf32> to tensor<17x5xf32>
%2 = vector.transfer_write %vec, %1[...]
    : vector<17x5xf32>, tensor<17x5xf32>
%r = tensor.extract_slice %2[0, 0] [%s0, %s1] [1, 1]
    : tensor<17x5xf32> to tensor<?x?xf32>
is rewritten to:
%0 = tensor.extract_slice ...[...] [%s0, %s1] [1, 1]
    : tensor<...> to tensor<?x?xf32>
%r = vector.transfer_write %vec, %0[...] : vector<17x5xf32>,
tensor<?x?xf32>
Note: It is important that the ExtractSliceOp r resizes the result of the TransferWriteOp to the same size as the input of the TensorPadOp (or an even smaller size). Otherwise, r's new (dynamic) dimensions would differ from r's old dimensions.
This rewrite is possible if:
Low padding is static 0.
xferOp has exactly one use, which is an ExtractSliceOp. This ExtractSliceOp trims the same amount of padding that was added beforehand.
Single, scalar padding value.
Definition at line 2911 of file Vectorization.cpp.
Member Function Documentation
hasSameTensorSize()
bool PadOpVectorizationWithTransferWritePattern::hasSameTensorSize (Value beforePadding, tensor::ExtractSliceOp afterTrimming) const inline
Check if beforePadding and afterTrimming have the same tensor size, i.e., same dimensions.
Dimensions may be static, dynamic or mix of both. In case of dynamic dimensions, this function tries to infer the (static) tensor size by looking at the defining op and utilizing op-specific knowledge.
This is a conservative analysis. In case equal tensor sizes cannot be proven statically, this analysis returns false even though the tensor sizes may turn out to be equal at runtime.
Definition at line 2965 of file Vectorization.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getType(), and mlir::isEqualConstantIntOrValue().
rewriteUser()
LogicalResult PadOpVectorizationWithTransferWritePattern::rewriteUser (PatternRewriter & rewriter, tensor::PadOp padOp, vector::TransferWriteOp xferOp) const inline override
Definition at line 2916 of file Vectorization.cpp.
References mlir::Builder::getBoolArrayAttr(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::OpBuilder::setInsertionPoint().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/Transforms/Vectorization.cpp