MLIR: mlir::linalg::CodegenStrategy Struct Reference
mlir::linalg::CodegenStrategy Struct Reference
Codegen strategy controls how a Linalg op is progressively lowered.
#include "mlir/Dialect/Linalg/Transforms/CodegenStrategy.h"
Public Member Functions
template<typename LinalgOpType >
CodegenStrategy & tile (linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to add a level of tiling for LinalgOpType with tiling options.
template<typename LinalgOpType >
CodegenStrategy & tile (StringRef opName, linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to add a level of tiling for LinalgOpType with tiling options.
template<typename LinalgOpType >
CodegenStrategy & tileIf (bool b, linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
template<typename LinalgOpType >
CodegenStrategy & tileIf (bool b, StringRef opName, linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
template<typename LinalgOpType >
CodegenStrategy & promote (linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
template<typename LinalgOpType >
CodegenStrategy & promote (StringRef opName, linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
template<typename LinalgOpType >
CodegenStrategy & promoteIf (bool b, StringRef opName, linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
template<typename LinalgOpType >
CodegenStrategy & promoteIf (bool b, linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
template<typename LinalgOpType >
CodegenStrategy & vectorize (linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to rewrite LinalgOpType as a vector operation.
template<typename LinalgOpType >
CodegenStrategy & vectorizeIf (bool b, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & vectorize (StringRef opName, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & vectorizeIf (bool b, StringRef opName, linalg::LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & setVectorTransformsOptions (vector::VectorTransformsOptions options)
Configure the post staged-patterns late vector transformations.
CodegenStrategy & setVectorTransferToSCFOptions (VectorTransferToSCFOptions options)
Configure the post staged-patterns late vector.transfer to scf conversion.
CodegenStrategy & setEnableLICM (bool val)
Configure the application of late transformations.
CodegenStrategy & setEnableHoistRedundantVectorTransfers (bool val)
CodegenStrategy & setEnableHoistRedundantVectorTransfersOnTensor (bool val)
CodegenStrategy & setEnableVectorTransferPartialRewrite (bool val)
CodegenStrategy & setEnableVectorContractLowering (bool val)
CodegenStrategy & setEnableVectorToSCFConversion (bool val)
void transform (FuncOp func) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Detailed Description
Codegen strategy controls how a Linalg op is progressively lowered.
The application uses a 3-level staged patterns strategy which allows ordering transformations by using the Linalg applyStagedPatterns function, where:
The first stage consists of the successive tile, promote and vectorize patterns, applied sequentially.
The second stage consists of common local canonicalization patterns that are applied eagerly after each stage-1 pattern.
the third stage consists of more global transformation, also applied eagerly, after all stage-2 patterns. Such more global transformations
Definition at line 173 of file CodegenStrategy.h.
Member Function Documentation
promote() [1/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::promote (linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 214 of file CodegenStrategy.h.
promote() [2/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::promote (StringRef opName, linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 224 of file CodegenStrategy.h.
promoteIf() [1/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::promoteIf (bool b, StringRef opName, linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 234 of file CodegenStrategy.h.
References options.
promoteIf() [2/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::promoteIf (bool b, linalg::LinalgPromotionOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 243 of file CodegenStrategy.h.
References options.
setEnableHoistRedundantVectorTransfers()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableHoistRedundantVectorTransfers (bool val) inline
Definition at line 303 of file CodegenStrategy.h.
setEnableHoistRedundantVectorTransfersOnTensor()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableHoistRedundantVectorTransfersOnTensor (bool val) inline
Definition at line 307 of file CodegenStrategy.h.
setEnableLICM()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableLICM (bool val) inline
Configure the application of late transformations.
Definition at line 299 of file CodegenStrategy.h.
setEnableVectorContractLowering()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorContractLowering (bool val) inline
Definition at line 316 of file CodegenStrategy.h.
setEnableVectorToSCFConversion()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorToSCFConversion (bool val) inline
Definition at line 320 of file CodegenStrategy.h.
setEnableVectorTransferPartialRewrite()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorTransferPartialRewrite (bool val) inline
Definition at line 312 of file CodegenStrategy.h.
setVectorTransferToSCFOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransferToSCFOptions (VectorTransferToSCFOptions options) inline
Configure the post staged-patterns late vector.transfer to scf conversion.
Definition at line 292 of file CodegenStrategy.h.
References options.
setVectorTransformsOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransformsOptions (vector::VectorTransformsOptions options) inline
Configure the post staged-patterns late vector transformations.
Definition at line 285 of file CodegenStrategy.h.
References options.
tile() [1/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::tile (linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 178 of file CodegenStrategy.h.
tile() [2/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::tile (StringRef opName, linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 188 of file CodegenStrategy.h.
tileIf() [1/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::tileIf (bool b, linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 198 of file CodegenStrategy.h.
References options.
tileIf() [2/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::tileIf (bool b, StringRef opName, linalg::LinalgTilingOptions options, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 206 of file CodegenStrategy.h.
References options.
transform()
void mlir::linalg::CodegenStrategy::transform (FuncOp func) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Definition at line 29 of file CodegenStrategy.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsAndFoldGreedily(), mlir::linalg::applyStagedPatterns(), mlir::failed(), mlir::Identifier::get(), mlir::linalg::getLinalgTilingCanonicalizationPatterns(), mlir::linalg::hoistRedundantVectorTransfers(), mlir::linalg::hoistRedundantVectorTransfersOnTensor(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::moveLoopInvariantCode(), op, mlir::populateVectorToSCFConversionPatterns(), mlir::vector::populateVectorTransferPermutationMapLoweringPatterns(), mlir::promoteSingleIterationLoops(), mlir::Operation::removeAttr(), mlir::success(), and mlir::Operation::walk().
vectorize() [1/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::vectorize (linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 251 of file CodegenStrategy.h.
vectorize() [2/2]
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorize (StringRef opName, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 268 of file CodegenStrategy.h.
vectorizeIf() [1/2]
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::vectorizeIf (bool b, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 261 of file CodegenStrategy.h.
vectorizeIf() [2/2]
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorizeIf (bool b, StringRef opName, linalg::LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 278 of file CodegenStrategy.h.
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/CodegenStrategy.h
lib/Dialect/Linalg/Transforms/CodegenStrategy.cpp