MLIR: HasAffineDimExprVisitor Struct Reference
HasAffineDimExprVisitor Struct Reference
Visitor to check if any of the given set of positions from AffineDimExprs are used within an AffineExpr.
Public Member Functions
HasAffineDimExprVisitor (llvm::SmallSet< unsigned, 4 > &positions)
bool visitAffineBinaryOpExpr (AffineBinaryOpExpr binaryOpExpr)
bool visitDimExpr (AffineDimExpr dimExpr)
bool visitConstantExpr (AffineConstantExpr constExpr)
bool visitSymbolExpr (AffineSymbolExpr symbolExpr)
Public Member Functions inherited from mlir::AffineExprVisitor< HasAffineDimExprVisitor, bool >
bool walkPostOrder (AffineExpr expr)
bool visit (AffineExpr expr)
bool visitAffineBinaryOpExpr (AffineBinaryOpExpr expr)
bool visitAddExpr (AffineBinaryOpExpr expr)
bool visitMulExpr (AffineBinaryOpExpr expr)
bool visitModExpr (AffineBinaryOpExpr expr)
bool visitFloorDivExpr (AffineBinaryOpExpr expr)
bool visitCeilDivExpr (AffineBinaryOpExpr expr)
bool visitConstantExpr (AffineConstantExpr expr)
bool visitDimExpr (AffineDimExpr expr)
bool visitSymbolExpr (AffineSymbolExpr expr)
Detailed Description
Visitor to check if any of the given set of positions from AffineDimExprs are used within an AffineExpr.
Definition at line 256 of file LinalgInterfaces.cpp.
Constructor & Destructor Documentation
HasAffineDimExprVisitor()
HasAffineDimExprVisitor::HasAffineDimExprVisitor (llvm::SmallSet< unsigned, 4 > & positions) inline
Definition at line 258 of file LinalgInterfaces.cpp.
Member Function Documentation
visitAffineBinaryOpExpr()
bool HasAffineDimExprVisitor::visitAffineBinaryOpExpr (AffineBinaryOpExpr binaryOpExpr) inline
Definition at line 261 of file LinalgInterfaces.cpp.
References mlir::AffineBinaryOpExpr::getLHS(), and mlir::AffineBinaryOpExpr::getRHS().
visitConstantExpr()
bool HasAffineDimExprVisitor::visitConstantExpr (AffineConstantExpr constExpr) inline
Definition at line 269 of file LinalgInterfaces.cpp.
visitDimExpr()
bool HasAffineDimExprVisitor::visitDimExpr (AffineDimExpr dimExpr) inline
Definition at line 265 of file LinalgInterfaces.cpp.
References mlir::AffineDimExpr::getPosition().
visitSymbolExpr()
bool HasAffineDimExprVisitor::visitSymbolExpr (AffineSymbolExpr symbolExpr) inline
Definition at line 271 of file LinalgInterfaces.cpp.
References mlir::linalg::applyMapToValues(), mlir::AffineMap::compose(), mlir::linalg::createOrFoldDimOp(), mlir::AffineMap::getResults(), mlir::AffineMap::getSubMap(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/IR/LinalgInterfaces.cpp