MLIR: pybind11::detail::type_caster< MlirLocation > Struct Template Reference
pybind11::detail::type_caster< MlirLocation > Struct Template Reference
Casts object <-> MlirLocation.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirLocation, _("MlirLocation"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirLocation v, return_value_policy, handle)
Detailed Description
template<>
struct pybind11::detail::type_caster< MlirLocation >
Casts object <-> MlirLocation.
Definition at line 134 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirLocation >::cast (MlirLocation v, return_value_policy , handle) inline static
Definition at line 144 of file PybindAdaptors.h.
References MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_PACKAGE_PREFIX, and mlirPythonLocationToCapsule().
load()
bool pybind11::detail::type_caster< MlirLocation >::load (handle src, bool) inline
Definition at line 136 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirLocationIsNull(), mlirPythonCapsuleToLocation(), and value.
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirLocation >::PYBIND11_TYPE_CASTER (MlirLocation , _("MlirLocation"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h