MLIR: ClampClampOptimization::ClampRange< T > Struct Template Reference
ClampClampOptimization::ClampRange< T > Struct Template Reference
Public Member Functions
ClampRange (const T &start, const T &end)
bool intersects (const ClampRange< T > &otherRange)
Public Attributes
T start
T end
Detailed Description
template<typename T>
struct ClampClampOptimization::ClampRange< T >
Definition at line 508 of file TosaCanonicalizations.cpp.
Constructor & Destructor Documentation
ClampRange()
template<typename T> ClampClampOptimization::ClampRange< T >::ClampRange (const T & start, const T & end) inline
Definition at line 509 of file TosaCanonicalizations.cpp.
References end, and start.
Referenced by intersects().
Member Function Documentation
intersects()
template<typename T> bool ClampClampOptimization::ClampRange< T >::intersects (const ClampRange< T > & otherRange) inline
Definition at line 514 of file TosaCanonicalizations.cpp.
References ClampRange(), end, and start.
Referenced by ClampClampOptimization::matchAndRewrite().
Member Data Documentation
end
template<typename T> T ClampClampOptimization::ClampRange< T >::end
Definition at line 511 of file TosaCanonicalizations.cpp.
Referenced by ClampRange(), and intersects().
start
template<typename T> T ClampClampOptimization::ClampRange< T >::start
Definition at line 510 of file TosaCanonicalizations.cpp.
Referenced by ClampRange(), and intersects().
The documentation for this struct was generated from the following file:
lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp