MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobalDebugFlag Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobalDebugFlag Struct Reference
Wrapper for the global LLVM debugging flag.
#include "mlir/Bindings/Python/IRCore.h"
Static Public Member Functions
static void set (nanobind::object &o, bool enable)
static bool get (const nanobind::object &)
static void bind (nanobind::module_ &m)
Detailed Description
Wrapper for the global LLVM debugging flag.
Definition at line 54 of file IRCore.h.
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobalDebugFlag::bind (nanobind::module_ & m) static
Definition at line 118 of file IRCore.cpp.
References get(), mlirSetGlobalDebugType(), mlirSetGlobalDebugTypes(), and set().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
get()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobalDebugFlag::get (const nanobind::object &) static
Definition at line 113 of file IRCore.cpp.
References mlirIsGlobalDebugEnabled().
Referenced by bind().
set()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobalDebugFlag::set (nanobind::object & o, bool enable) static
Definition at line 108 of file IRCore.cpp.
References mlirEnableGlobalDebug().
Referenced by bind().
The documentation for this struct was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp