MLIR: mlir::AsmParserState::Impl::PartialOpDef Struct Reference
mlir::AsmParserState::Impl::PartialOpDef Struct Reference
Public Member Functions
PartialOpDef (const OperationName &opName)
bool isSymbolTable () const
Return if this operation is a symbol table.
Public Attributes
std::unique_ptr< SymbolUseMap > symbolTable
If this operation is a symbol table, the following contains symbol uses within this operation.
Detailed Description
Definition at line 38 of file AsmParserState.cpp.
Constructor & Destructor Documentation
PartialOpDef()
mlir::AsmParserState::Impl::PartialOpDef::PartialOpDef (const OperationName & opName) inline explicit
Definition at line 39 of file AsmParserState.cpp.
References mlir::OperationName::hasTrait(), and symbolTable.
Member Function Documentation
isSymbolTable()
bool mlir::AsmParserState::Impl::PartialOpDef::isSymbolTable () const inline
Return if this operation is a symbol table.
Definition at line 45 of file AsmParserState.cpp.
References symbolTable.
Referenced by mlir::AsmParserState::finalize(), mlir::AsmParserState::finalizeOperationDefinition(), mlir::AsmParserState::finalizeRegionDefinition(), mlir::AsmParserState::initialize(), and mlir::AsmParserState::startRegionDefinition().
Member Data Documentation
symbolTable
std::unique_ptr<SymbolUseMap> mlir::AsmParserState::Impl::PartialOpDef::symbolTable
If this operation is a symbol table, the following contains symbol uses within this operation.
Definition at line 49 of file AsmParserState.cpp.
Referenced by mlir::AsmParserState::finalize(), mlir::AsmParserState::finalizeOperationDefinition(), mlir::AsmParserState::initialize(), isSymbolTable(), PartialOpDef(), and mlir::AsmParserState::startRegionDefinition().
The documentation for this struct was generated from the following file:
lib/AsmParser/AsmParserState.cpp