MLIR: mlir::FieldParser< AttributeT, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, AttributeT > > Struct Template Reference
mlir::FieldParser< AttributeT, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, AttributeT > > Struct Template Reference
Parse an attribute.
#include "mlir/IR/DialectImplementation.h"
Static Public Member Functions
static FailureOr< AttributeT > parse (AsmParser &parser)
Detailed Description
template<typename AttributeT>
struct mlir::FieldParser< AttributeT, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, AttributeT > >
Parse an attribute.
Definition at line 78 of file DialectImplementation.h.
Member Function Documentation
parse()
template<typename AttributeT> FailureOr< AttributeT > mlir::FieldParser< AttributeT, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, AttributeT > >::parse (AsmParser & parser) inline static
Definition at line 81 of file DialectImplementation.h.
References mlir::AsmParser::getContext(), mlir::MLIRContext::getOrLoadDialect(), and mlir::AsmParser::parseCustomAttributeWithFallback().
The documentation for this struct was generated from the following file:
include/mlir/IR/DialectImplementation.h