MLIR: MlirPatternDescriptorOpInterfaceCallbacks Struct Reference
MlirPatternDescriptorOpInterfaceCallbacks Struct Reference
Callbacks for implementing PatternDescriptorOpInterface from external code.
#include "mlir-c/Dialect/Transform.h"
Public Attributes
void(* construct)(void *userData)
Optional constructor for the user data.
void(* destruct)(void *userData)
Optional destructor for the user data.
void(* populatePatterns)(MlirOperation op, MlirRewritePatternSet patterns, void *userData)
Callback to populate rewrite patterns into the given pattern set.
void(* populatePatternsWithState)(MlirOperation op, MlirRewritePatternSet patterns, MlirTransformState state, void *userData)
Optional callback to populate rewrite patterns with transform state.
void * userData
Detailed Description
Callbacks for implementing PatternDescriptorOpInterface from external code.
Definition at line 218 of file Transform.h.
Member Data Documentation
construct
void(* MlirPatternDescriptorOpInterfaceCallbacks::construct) (void *userData)
Optional constructor for the user data.
Set to nullptr to disable it.
Definition at line 221 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyPatternDescriptorOpInterface::attach().
destruct
void(* MlirPatternDescriptorOpInterfaceCallbacks::destruct) (void *userData)
Optional destructor for the user data.
Set to nullptr to disable it.
Definition at line 224 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyPatternDescriptorOpInterface::attach().
populatePatterns
void(* MlirPatternDescriptorOpInterfaceCallbacks::populatePatterns) (MlirOperation op, MlirRewritePatternSet patterns, void *userData)
Callback to populate rewrite patterns into the given pattern set.
Definition at line 226 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyPatternDescriptorOpInterface::attach().
populatePatternsWithState
void(* MlirPatternDescriptorOpInterfaceCallbacks::populatePatternsWithState) (MlirOperation op, MlirRewritePatternSet patterns, MlirTransformState state, void *userData)
Optional callback to populate rewrite patterns with transform state.
Set to nullptr to use the default implementation (calls populatePatterns).
Definition at line 230 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyPatternDescriptorOpInterface::attach().
userData
void* MlirPatternDescriptorOpInterfaceCallbacks::userData
Definition at line 233 of file Transform.h.
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::transform::PyPatternDescriptorOpInterface::attach().
The documentation for this struct was generated from the following file:
include/mlir-c/Dialect/Transform.h