MLIR: mlir::detail::OpPassManagerImpl Struct Reference
mlir::detail::OpPassManagerImpl Struct Reference
Public Member Functions
OpPassManagerImpl (OperationName opName, OpPassManager::Nesting nesting)
OpPassManagerImpl (StringRef name, OpPassManager::Nesting nesting)
OpPassManagerImpl (OpPassManager::Nesting nesting)
OpPassManagerImpl (const OpPassManagerImpl &rhs)
void mergeInto (OpPassManagerImpl &rhs)
Merge the passes of this pass manager into the one provided.
OpPassManager & nest (OperationName nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
OpPassManager & nest (StringRef nestedName)
OpPassManager & nestAny ()
OpPassManager & nest (OpPassManager &&nested)
Nest the given pass manager under this pass manager.
void addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
void clear ()
Clear the list of passes in this pass manager, other options are preserved.
LogicalResult finalizePassList (MLIRContext *ctx)
Finalize the pass list in preparation for execution.
std::optional< OperationName > getOpName (MLIRContext &context)
Return the operation name of this pass manager.
std::optional< StringRef > getOpName () const
StringRef getOpAnchorName () const
Return the name used to anchor this pass manager.
bool canScheduleOn (MLIRContext &context, OperationName opName)
Indicate if the current pass manager can be scheduled on the given operation type.
Public Attributes
std::string name
The name of the operation that passes of this pass manager operate on.
std::optional< OperationName > opName
The cached OperationName (internalized in the context) for the name of the operation that passes of this pass manager operate on.
std::vector< std::unique_ptr< Pass > > passes
The set of passes to run as part of this pass manager.
unsigned initializationGeneration
The current initialization generation of this pass manager.
OpPassManager::Nesting nesting
Control the implicit nesting of passes that mismatch the name set for this OpPassManager.
Detailed Description
Definition at line 115 of file Pass.cpp.
Constructor & Destructor Documentation
OpPassManagerImpl() [1/4]
mlir::detail::OpPassManagerImpl::OpPassManagerImpl (OperationName opName, OpPassManager::Nesting nesting) inline
Definition at line 116 of file Pass.cpp.
References initializationGeneration, name, nesting, and opName.
Referenced by mergeInto(), and OpPassManagerImpl().
OpPassManagerImpl() [2/4]
mlir::detail::OpPassManagerImpl::OpPassManagerImpl (StringRef name, OpPassManager::Nesting nesting) inline
Definition at line 119 of file Pass.cpp.
References initializationGeneration, name, and nesting.
OpPassManagerImpl() [3/4]
mlir::detail::OpPassManagerImpl::OpPassManagerImpl (OpPassManager::Nesting nesting) inline
Definition at line 122 of file Pass.cpp.
References initializationGeneration, and nesting.
OpPassManagerImpl() [4/4]
mlir::detail::OpPassManagerImpl::OpPassManagerImpl (const OpPassManagerImpl & rhs) inline
Definition at line 124 of file Pass.cpp.
References initializationGeneration, name, nesting, opName, OpPassManagerImpl(), and rhs.
Member Function Documentation
addPass()
void OpPassManagerImpl::addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
If this pass has a concrete operation type, it must be the same type as this pass manager.
Definition at line 220 of file Pass.cpp.
References getOpAnchorName(), getOpName(), mlir::OpPassManager::Implicit, nest(), nesting, and passes.
Referenced by nest().
canScheduleOn()
bool OpPassManagerImpl::canScheduleOn (MLIRContext & context, OperationName opName)
Indicate if the current pass manager can be scheduled on the given operation type.
Definition at line 323 of file Pass.cpp.
References getOpName(), opName, and passes.
Referenced by findPassManagerFor(), and mlir::detail::OpToOpPassAdaptor::tryMergeInto().
clear()
void OpPassManagerImpl::clear ()
Clear the list of passes in this pass manager, other options are preserved.
Definition at line 237 of file Pass.cpp.
References passes.
finalizePassList()
LogicalResult OpPassManagerImpl::finalizePassList (MLIRContext * ctx)
Finalize the pass list in preparation for execution.
This includes coalescing adjacent pass managers when possible, verifying scheduled passes, etc.
Definition at line 239 of file Pass.cpp.
References mlir::emitError(), getOpAnchorName(), getOpName(), opName, passes, and success().
getOpAnchorName()
StringRef mlir::detail::OpPassManagerImpl::getOpAnchorName () const inline
Return the name used to anchor this pass manager.
This is either the name of an operation, or the result of getAnyOpAnchorName() in the case of an op-agnostic pass manager.
Definition at line 178 of file Pass.cpp.
References mlir::OpPassManager::getAnyOpAnchorName(), and getOpName().
Referenced by addPass(), and finalizePassList().
getOpName() [1/2]
std::optional< StringRef > mlir::detail::OpPassManagerImpl::getOpName () const inline
Definition at line 170 of file Pass.cpp.
References name.
Referenced by getOpAnchorName().
getOpName() [2/2]
std::optional< OperationName > mlir::detail::OpPassManagerImpl::getOpName (MLIRContext & context) inline
Return the operation name of this pass manager.
Definition at line 165 of file Pass.cpp.
References name, and opName.
Referenced by addPass(), canScheduleOn(), and finalizePassList().
mergeInto()
void OpPassManagerImpl::mergeInto (OpPassManagerImpl & rhs)
Merge the passes of this pass manager into the one provided.
Definition at line 207 of file Pass.cpp.
References name, OpPassManagerImpl(), passes, and rhs.
Referenced by mlir::detail::OpToOpPassAdaptor::tryMergeInto().
nest() [1/3]
OpPassManager & mlir::detail::OpPassManagerImpl::nest (OperationName nestedName) inline
Nest a new operation pass manager for the given operation kind under this pass manager.
Definition at line 140 of file Pass.cpp.
References nest(), and nesting.
Referenced by addPass(), nest(), nest(), and nestAny().
nest() [2/3]
OpPassManager & OpPassManagerImpl::nest (OpPassManager && nested)
Nest the given pass manager under this pass manager.
Definition at line 214 of file Pass.cpp.
References addPass().
nest() [3/3]
OpPassManager & mlir::detail::OpPassManagerImpl::nest (StringRef nestedName) inline
Definition at line 143 of file Pass.cpp.
References nest(), and nesting.
nestAny()
OpPassManager & mlir::detail::OpPassManagerImpl::nestAny () inline
Definition at line 146 of file Pass.cpp.
References nest(), and nesting.
Member Data Documentation
initializationGeneration
unsigned mlir::detail::OpPassManagerImpl::initializationGeneration
The current initialization generation of this pass manager.
This is used to indicate when a pass manager should be reinitialized.
Definition at line 198 of file Pass.cpp.
Referenced by OpPassManagerImpl(), OpPassManagerImpl(), OpPassManagerImpl(), and OpPassManagerImpl().
name
std::string mlir::detail::OpPassManagerImpl::name
The name of the operation that passes of this pass manager operate on.
Definition at line 187 of file Pass.cpp.
Referenced by getOpName(), getOpName(), mergeInto(), OpPassManagerImpl(), OpPassManagerImpl(), and OpPassManagerImpl().
nesting
OpPassManager::Nesting mlir::detail::OpPassManagerImpl::nesting
Control the implicit nesting of passes that mismatch the name set for this OpPassManager.
Definition at line 202 of file Pass.cpp.
Referenced by addPass(), nest(), nest(), nestAny(), OpPassManagerImpl(), OpPassManagerImpl(), OpPassManagerImpl(), and OpPassManagerImpl().
opName
std::optional<OperationName> mlir::detail::OpPassManagerImpl::opName
The cached OperationName (internalized in the context) for the name of the operation that passes of this pass manager operate on.
Definition at line 191 of file Pass.cpp.
Referenced by canScheduleOn(), finalizePassList(), getOpName(), OpPassManagerImpl(), and OpPassManagerImpl().
passes
std::vector<std::unique_ptr<Pass> > mlir::detail::OpPassManagerImpl::passes
The set of passes to run as part of this pass manager.
Definition at line 194 of file Pass.cpp.
Referenced by addPass(), canScheduleOn(), clear(), finalizePassList(), and mergeInto().
The documentation for this struct was generated from the following file:
lib/Pass/Pass.cpp