MLIR: mlir::MutableAffineMap Struct Reference
mlir::MutableAffineMap Struct Reference
A mutable affine map. Its affine expressions are however unique.
#include "mlir/IR/AffineMap.h"
Public Member Functions
MutableAffineMap ()=default
MutableAffineMap (AffineMap map)
ArrayRef< AffineExpr > getResults () const
AffineExpr getResult (unsigned idx) const
void setResult (unsigned idx, AffineExpr result)
unsigned getNumResults () const
unsigned getNumDims () const
void setNumDims (unsigned d)
unsigned getNumSymbols () const
void setNumSymbols (unsigned d)
MLIRContext * getContext () const
bool isMultipleOf (unsigned idx, int64_t factor) const
Returns true if the idx'th result expression is a multiple of factor.
void reset (AffineMap map)
Resets this MutableAffineMap with 'map'.
void simplify ()
Simplify the (result) expressions in this map using analysis (used by.
AffineMap getAffineMap () const
Get the AffineMap corresponding to this MutableAffineMap.
Detailed Description
A mutable affine map. Its affine expressions are however unique.
Definition at line 430 of file AffineMap.h.
Constructor & Destructor Documentation
MutableAffineMap() [1/2]
mlir::MutableAffineMap::MutableAffineMap () default
MutableAffineMap() [2/2]
MutableAffineMap::MutableAffineMap (AffineMap map)
Definition at line 959 of file AffineMap.cpp.
References getContext(), getNumDims(), getNumSymbols(), and getResults().
Member Function Documentation
getAffineMap()
AffineMap MutableAffineMap::getAffineMap () const
Get the AffineMap corresponding to this MutableAffineMap.
Note that an AffineMap will be uniqued and stored in context, while a mutable one isn't.
Definition at line 985 of file AffineMap.cpp.
References mlir::AffineMap::get().
getContext()
MLIRContext * mlir::MutableAffineMap::getContext () const inline
Definition at line 443 of file AffineMap.h.
Referenced by MutableAffineMap().
getNumDims()
unsigned mlir::MutableAffineMap::getNumDims () const inline
Definition at line 439 of file AffineMap.h.
Referenced by MutableAffineMap().
getNumResults()
unsigned mlir::MutableAffineMap::getNumResults () const inline
Definition at line 438 of file AffineMap.h.
Referenced by simplify().
getNumSymbols()
unsigned mlir::MutableAffineMap::getNumSymbols () const inline
Definition at line 441 of file AffineMap.h.
Referenced by MutableAffineMap().
getResult()
AffineExpr mlir::MutableAffineMap::getResult (unsigned idx) const inline
Definition at line 436 of file AffineMap.h.
Referenced by simplify().
getResults()
ArrayRef< AffineExpr > mlir::MutableAffineMap::getResults () const inline
Definition at line 435 of file AffineMap.h.
Referenced by MutableAffineMap().
isMultipleOf()
bool MutableAffineMap::isMultipleOf (unsigned idx, int64_t factor) const
Returns true if the idx'th result expression is a multiple of factor.
Definition at line 971 of file AffineMap.cpp.
reset()
void MutableAffineMap::reset (AffineMap map)
Resets this MutableAffineMap with 'map'.
Definition at line 963 of file AffineMap.cpp.
References mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
setNumDims()
void mlir::MutableAffineMap::setNumDims (unsigned d) inline
Definition at line 440 of file AffineMap.h.
setNumSymbols()
void mlir::MutableAffineMap::setNumSymbols (unsigned d) inline
Definition at line 442 of file AffineMap.h.
setResult()
void mlir::MutableAffineMap::setResult (unsigned idx, AffineExpr result) inline
Definition at line 437 of file AffineMap.h.
References result.
simplify()
void MutableAffineMap::simplify ()
Simplify the (result) expressions in this map using analysis (used by.
Definition at line 977 of file AffineMap.cpp.
References getNumResults(), getResult(), and mlir::simplifyAffineExpr().
The documentation for this struct was generated from the following files:
include/mlir/IR/AffineMap.h
lib/IR/AffineMap.cpp