MLIR: mlir::bufferization::ValueComparator Struct Reference
mlir::bufferization::ValueComparator Struct Reference
Compare two SSA values in a deterministic manner.
#include "mlir/Dialect/Bufferization/IR/BufferDeallocationOpInterface.h"
Public Member Functions
bool operator() (const Value &lhs, const Value &rhs) const
Detailed Description
Compare two SSA values in a deterministic manner.
Two block arguments are ordered by argument number, block arguments are always less than operation results, and operation results are ordered by the isBeforeInBlock order of their defining operation.
Definition at line 24 of file BufferDeallocationOpInterface.h.
Member Function Documentation
operator()()
bool ValueComparator::operator() (const Value & lhs, const Value & rhs) const
Definition at line 222 of file BufferDeallocationOpInterface.cpp.
References mlir::Value::getDefiningOp(), mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), mlir::Region::getParentRegion(), mlir::Region::getRegionNumber(), and mlir::Operation::isBeforeInBlock().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Bufferization/IR/BufferDeallocationOpInterface.h
lib/Dialect/Bufferization/IR/BufferDeallocationOpInterface.cpp