MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< StructType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
static PyType createFromCapsule (nanobind::object capsule)
Creates a PyType from the MlirType wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirTypeIsALLVMStructType
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "StructType"
static const MlirStringRef name = mlirLLVMStructTypeGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< StructType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< StructType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< StructType >
PyConcreteType ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyType
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other) const
operator MlirType () const
MlirType get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirType.
nanobind::typed< nanobind::object, PyType > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Definition at line 35 of file DialectLLVM.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::bindDerived (ClassTy & c) inline static
Definition at line 43 of file DialectLLVM.cpp.
References mlir::python::Defaulting< DerivedTy, T >::get(), mlirLLVMStructTypeGetElementType(), mlirLLVMStructTypeGetIdentifier(), mlirLLVMStructTypeGetNumElementTypes(), mlirLLVMStructTypeIdentifiedGet(), mlirLLVMStructTypeIdentifiedNewGet(), mlirLLVMStructTypeIsLiteral(), mlirLLVMStructTypeIsOpaque(), mlirLLVMStructTypeIsPacked(), mlirLLVMStructTypeLiteralGet(), mlirLLVMStructTypeLiteralGetChecked(), mlirLLVMStructTypeOpaqueGet(), mlirLLVMStructTypeSetBody(), mlirLocationGetContext(), mlirLogicalResultIsSuccess(), mlirStringRefCreate(), mlirTypeIsNull(), name, result, and mlir::python::CollectDiagnosticsToStringScope::takeMessage().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::getTypeIdFunction static constexpr
Initial value:
=
      mlirLLVMStructTypeGetTypeID
Definition at line 37 of file DialectLLVM.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::isaFunction = mlirTypeIsALLVMStructType static constexpr
Definition at line 36 of file DialectLLVM.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::name = mlirLLVMStructTypeGetName() inline static
Definition at line 40 of file DialectLLVM.cpp.
Referenced by bindDerived().
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::StructType::pyClassName = "StructType" static constexpr
Definition at line 39 of file DialectLLVM.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectLLVM.cpp