MLIR: mlir::quant::detail::CalibratedQuantizedTypeStorage Struct Reference
mlir::quant::detail::CalibratedQuantizedTypeStorage Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Classes
struct KeyTy
Public Member Functions
CalibratedQuantizedTypeStorage (const KeyTy &key)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::quant::detail::QuantizedTypeStorage
QuantizedTypeStorage (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static CalibratedQuantizedTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
static unsigned hashKey (const KeyTy &key)
Public Attributes
double min
double max
Public Attributes inherited from mlir::quant::detail::QuantizedTypeStorage
unsigned flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Type storageType
Type expressedType
int64_t storageTypeMin
int64_t storageTypeMax
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 375 of file TypeDetail.h.
Constructor & Destructor Documentation
CalibratedQuantizedTypeStorage()
mlir::quant::detail::CalibratedQuantizedTypeStorage::CalibratedQuantizedTypeStorage (const KeyTy & key) inline
Definition at line 404 of file TypeDetail.h.
References mlir::quant::detail::QuantizedTypeStorage::expressedType, max, min, and mlir::quant::detail::QuantizedTypeStorage::QuantizedTypeStorage().
Referenced by construct().
Member Function Documentation
construct()
CalibratedQuantizedTypeStorage * mlir::quant::detail::CalibratedQuantizedTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 414 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and CalibratedQuantizedTypeStorage().
hashKey()
unsigned mlir::quant::detail::CalibratedQuantizedTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 419 of file TypeDetail.h.
References mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::getHashValue().
operator==()
bool mlir::quant::detail::CalibratedQuantizedTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 408 of file TypeDetail.h.
References mlir::quant::detail::CalibratedQuantizedTypeStorage::KeyTy::genericIsEqual().
Member Data Documentation
max
double mlir::quant::detail::CalibratedQuantizedTypeStorage::max
Definition at line 422 of file TypeDetail.h.
Referenced by CalibratedQuantizedTypeStorage().
min
double mlir::quant::detail::CalibratedQuantizedTypeStorage::min
Definition at line 421 of file TypeDetail.h.
Referenced by CalibratedQuantizedTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h