MLIR: mlir::quant::detail::UniformQuantizedTypeStorage Struct Reference
mlir::quant::detail::UniformQuantizedTypeStorage Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Classes
struct KeyTy
Public Member Functions
UniformQuantizedTypeStorage (const KeyTy &key)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::quant::detail::QuantizedTypeStorage
QuantizedTypeStorage (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static UniformQuantizedTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
static unsigned hashKey (const KeyTy &key)
Public Attributes
double scale
int64_t zeroPoint
Public Attributes inherited from mlir::quant::detail::QuantizedTypeStorage
unsigned flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Type storageType
Type expressedType
int64_t storageTypeMin
int64_t storageTypeMax
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 96 of file TypeDetail.h.
Constructor & Destructor Documentation
UniformQuantizedTypeStorage()
mlir::quant::detail::UniformQuantizedTypeStorage::UniformQuantizedTypeStorage (const KeyTy & key) inline
Definition at line 139 of file TypeDetail.h.
References mlir::quant::detail::QuantizedTypeStorage::expressedType, mlir::quant::detail::QuantizedTypeStorage::flags, mlir::quant::detail::QuantizedTypeStorage::QuantizedTypeStorage(), scale, mlir::quant::detail::QuantizedTypeStorage::storageType, mlir::quant::detail::QuantizedTypeStorage::storageTypeMax, mlir::quant::detail::QuantizedTypeStorage::storageTypeMin, and zeroPoint.
Referenced by construct().
Member Function Documentation
construct()
UniformQuantizedTypeStorage * mlir::quant::detail::UniformQuantizedTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 149 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and UniformQuantizedTypeStorage().
hashKey()
unsigned mlir::quant::detail::UniformQuantizedTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 155 of file TypeDetail.h.
References mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::getHashValue().
operator==()
bool mlir::quant::detail::UniformQuantizedTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 144 of file TypeDetail.h.
References mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::genericIsEqual().
Member Data Documentation
scale
double mlir::quant::detail::UniformQuantizedTypeStorage::scale
Definition at line 157 of file TypeDetail.h.
Referenced by UniformQuantizedTypeStorage().
zeroPoint
int64_t mlir::quant::detail::UniformQuantizedTypeStorage::zeroPoint
Definition at line 158 of file TypeDetail.h.
Referenced by UniformQuantizedTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h