MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedPerAxisType, QuantizedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "UniformQuantizedPerAxisType"
static const MlirStringRef name
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedPerAxisType, QuantizedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedPerAxisType, QuantizedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedPerAxisType, QuantizedType >
PyConcreteType ()=default
Detailed Description
Definition at line 280 of file DialectQuant.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType::bindDerived (ClassTy & c) inline static
Definition at line 291 of file DialectQuant.cpp.
References mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedPerAxisTypeGetNumDims(), mlirUniformQuantizedPerAxisTypeGetQuantizedDimension(), mlirUniformQuantizedPerAxisTypeGetScale(), mlirUniformQuantizedPerAxisTypeGetZeroPoint(), and mlirUniformQuantizedPerAxisTypeIsFixedPoint().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType::getTypeIdFunction static constexpr
Initial value:
=
      mlirUniformQuantizedPerAxisTypeGetTypeID
Definition at line 284 of file DialectQuant.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType::isaFunction static constexpr
Initial value:
=
      mlirTypeIsAUniformQuantizedPerAxisType
Definition at line 282 of file DialectQuant.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType::name inline static
Initial value:
=
      mlirUniformQuantizedPerAxisTypeGetName()
Definition at line 287 of file DialectQuant.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedPerAxisType::pyClassName = "UniformQuantizedPerAxisType" static constexpr
Definition at line 286 of file DialectQuant.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectQuant.cpp