MLIR: mlir::detail::TupleTypeStorage Struct Reference
mlir::detail::TupleTypeStorage Struct Reference final
A type representing a collection of other types.
#include "IR/TypeDetail.h"
Public Types
using KeyTy = TypeRange
Public Member Functions
TupleTypeStorage (unsigned numTypes)
bool operator== (const KeyTy &key) const
unsigned size () const
Return the number of held types.
ArrayRef< Type > getTypes () const
Return the held types.
KeyTy getAsKey () const
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static TupleTypeStorage * construct (TypeStorageAllocator &allocator, TypeRange key)
Construction.
Public Attributes
unsigned numElements
The number of tuple elements.
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
A type representing a collection of other types.
Definition at line 103 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::TupleTypeStorage::KeyTy = TypeRange
Definition at line 107 of file TypeDetail.h.
Constructor & Destructor Documentation
TupleTypeStorage()
mlir::detail::TupleTypeStorage::TupleTypeStorage (unsigned numTypes) inline
Definition at line 109 of file TypeDetail.h.
References numElements.
Referenced by construct().
Member Function Documentation
construct()
TupleTypeStorage * mlir::detail::TupleTypeStorage::construct (TypeStorageAllocator & allocator, TypeRange key) inline static
Construction.
Definition at line 112 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), result, and TupleTypeStorage().
getAsKey()
KeyTy mlir::detail::TupleTypeStorage::getAsKey () const inline
Definition at line 132 of file TypeDetail.h.
References getTypes().
getTypes()
ArrayRef< Type > mlir::detail::TupleTypeStorage::getTypes () const inline
Return the held types.
Definition at line 130 of file TypeDetail.h.
References size().
Referenced by getAsKey(), and operator==().
operator==()
bool mlir::detail::TupleTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 124 of file TypeDetail.h.
References getTypes().
size()
unsigned mlir::detail::TupleTypeStorage::size () const inline
Return the number of held types.
Definition at line 127 of file TypeDetail.h.
References numElements.
Referenced by getTypes().
Member Data Documentation
numElements
unsigned mlir::detail::TupleTypeStorage::numElements
The number of tuple elements.
Definition at line 135 of file TypeDetail.h.
Referenced by size(), and TupleTypeStorage().
The documentation for this struct was generated from the following file:
lib/IR/TypeDetail.h