MLIR: llvm::DenseMapInfo< mlir::remark::detail::Remark > Struct Reference
llvm::DenseMapInfo< mlir::remark::detail::Remark > Struct Reference
#include "mlir/IR/Remarks.h"
Static Public Member Functions
static mlir::MLIRContext * getStaticDummyContext ()
Helper to provide a static dummy context for sentinel keys.
static mlir::remark::detail::Remark getEmptyKey ()
Create an empty remark.
static mlir::remark::detail::Remark getTombstoneKey ()
Create a dead remark.
static unsigned getHashValue (const mlir::remark::detail::Remark &remark)
Compute the hash value of the remark.
static bool isEqual (const mlir::remark::detail::Remark &lhs, const mlir::remark::detail::Remark &rhs)
Static Public Attributes
static constexpr StringRef kEmptyKey = "<EMPTY_KEY>"
static constexpr StringRef kTombstoneKey = "<TOMBSTONE_KEY>"
Detailed Description
Definition at line 607 of file Remarks.h.
Member Function Documentation
getEmptyKey()
mlir::remark::detail::Remark llvm::DenseMapInfo< mlir::remark::detail::Remark >::getEmptyKey () inline static
Create an empty remark.
Definition at line 618 of file Remarks.h.
References getStaticDummyContext(), kEmptyKey, mlir::remark::RemarkOpts::name(), mlir::Note, and mlir::remark::RemarkUnknown.
getHashValue()
unsigned llvm::DenseMapInfo< mlir::remark::detail::Remark >::getHashValue (const mlir::remark::detail::Remark & remark) inline static
Compute the hash value of the remark.
Definition at line 634 of file Remarks.h.
References mlir::Location::getAsOpaquePointer(), mlir::remark::detail::Remark::getCombinedCategoryName(), mlir::remark::detail::Remark::getLocation(), and mlir::remark::detail::Remark::getRemarkName().
getStaticDummyContext()
mlir::MLIRContext * llvm::DenseMapInfo< mlir::remark::detail::Remark >::getStaticDummyContext () inline static
Helper to provide a static dummy context for sentinel keys.
Definition at line 612 of file Remarks.h.
Referenced by getEmptyKey(), and getTombstoneKey().
getTombstoneKey()
mlir::remark::detail::Remark llvm::DenseMapInfo< mlir::remark::detail::Remark >::getTombstoneKey () inline static
Create a dead remark.
Definition at line 626 of file Remarks.h.
References getStaticDummyContext(), kTombstoneKey, mlir::remark::RemarkOpts::name(), mlir::Note, and mlir::remark::RemarkUnknown.
isEqual()
bool llvm::DenseMapInfo< mlir::remark::detail::Remark >::isEqual (const mlir::remark::detail::Remark & lhs, const mlir::remark::detail::Remark & rhs) inline static
Definition at line 641 of file Remarks.h.
References kEmptyKey, kTombstoneKey, lhs, and rhs.
Member Data Documentation
kEmptyKey
StringRef llvm::DenseMapInfo< mlir::remark::detail::Remark >::kEmptyKey = "<EMPTY_KEY>" static constexpr
Definition at line 608 of file Remarks.h.
Referenced by getEmptyKey(), and isEqual().
kTombstoneKey
StringRef llvm::DenseMapInfo< mlir::remark::detail::Remark >::kTombstoneKey = "<TOMBSTONE_KEY>" static constexpr
Definition at line 609 of file Remarks.h.
Referenced by getTombstoneKey(), and isEqual().
The documentation for this struct was generated from the following file:
include/mlir/IR/Remarks.h