MLIR: mlir::PassRegistration< ConcretePass > Struct Template Reference
mlir::PassRegistration< ConcretePass > Struct Template Reference
PassRegistration provides a global initializer that registers a Pass allocation routine for a concrete pass instance.
#include "mlir/Pass/PassRegistry.h"
Public Member Functions
PassRegistration (const PassAllocatorFunction &constructor)
PassRegistration ()
Detailed Description
template<typename ConcretePass>
struct mlir::PassRegistration< ConcretePass >
PassRegistration provides a global initializer that registers a Pass allocation routine for a concrete pass instance.
The argument is optional and provides a callback to construct a pass that does not have a default constructor.
Usage:
/// At namespace scope. static PassRegistration<MyPass> reg;
Definition at line 155 of file PassRegistry.h.
Constructor & Destructor Documentation
PassRegistration() [1/2]
template<typename ConcretePass> mlir::PassRegistration< ConcretePass >::PassRegistration (const PassAllocatorFunction & constructor) inline
Definition at line 156 of file PassRegistry.h.
References mlir::registerPass().
Referenced by PassRegistration().
PassRegistration() [2/2]
template<typename ConcretePass> mlir::PassRegistration< ConcretePass >::PassRegistration () inline
Definition at line 159 of file PassRegistry.h.
References PassRegistration().
The documentation for this struct was generated from the following file:
include/mlir/Pass/PassRegistry.h