MLIR: RowColIndexing Struct Reference
RowColIndexing Struct Reference
Helper struct to encode a pair of row/column indexings in the form of affine expressions.
Public Member Functions
RowColIndexing (AffineExpr row, AffineExpr col)
AffineExpr row () const
AffineExpr col () const
void print (llvm::raw_ostream &os) const
Detailed Description
Helper struct to encode a pair of row/column indexings in the form of affine expressions.
Definition at line 425 of file NVGPUTransformOps.cpp.
Constructor & Destructor Documentation
RowColIndexing()
RowColIndexing::RowColIndexing (AffineExpr row, AffineExpr col) inline
Definition at line 426 of file NVGPUTransformOps.cpp.
References col(), and row().
Member Function Documentation
col()
AffineExpr RowColIndexing::col () const inline
Definition at line 430 of file NVGPUTransformOps.cpp.
Referenced by RowColIndexing().
print()
void RowColIndexing::print (llvm::raw_ostream & os) const inline
Definition at line 432 of file NVGPUTransformOps.cpp.
row()
AffineExpr RowColIndexing::row () const inline
Definition at line 429 of file NVGPUTransformOps.cpp.
Referenced by RowColIndexing().
The documentation for this struct was generated from the following file:
lib/Dialect/NVGPU/TransformOps/NVGPUTransformOps.cpp