MLIR: mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy Struct Reference
mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Public Member Functions
KeyTy (unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax)
bool operator== (const KeyTy &other) const
unsigned getHashValue () const
Static Public Member Functions
template<typename T , typename U >
static bool genericIsEqual (const T &lhs, const U &rhs)
Public Attributes
unsigned flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Type storageType
Type expressedType
double scale
int64_t zeroPoint
int64_t storageTypeMin
int64_t storageTypeMax
Detailed Description
Definition at line 97 of file TypeDetail.h.
Constructor & Destructor Documentation
KeyTy()
mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::KeyTy (unsigned flags, Type storageType, Type expressedType, double scale, int64_t zeroPoint, int64_t storageTypeMin, int64_t storageTypeMax) inline
Definition at line 98 of file TypeDetail.h.
Member Function Documentation
genericIsEqual()
template<typename T , typename U > static bool mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::genericIsEqual (const T & lhs, const U & rhs) inline static
Definition at line 120 of file TypeDetail.h.
Referenced by mlir::quant::detail::UniformQuantizedTypeStorage::operator==(), and operator==().
getHashValue()
unsigned mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::getHashValue () const inline
Definition at line 132 of file TypeDetail.h.
References expressedType, flags, scale, storageType, storageTypeMax, storageTypeMin, and zeroPoint.
Referenced by mlir::quant::detail::UniformQuantizedTypeStorage::hashKey().
operator==()
bool mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::operator== (const KeyTy & other) const inline
Definition at line 128 of file TypeDetail.h.
References genericIsEqual().
Member Data Documentation
expressedType
Type mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::expressedType
Definition at line 110 of file TypeDetail.h.
Referenced by getHashValue().
flags
unsigned mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Definition at line 104 of file TypeDetail.h.
Referenced by getHashValue().
scale
double mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::scale
Definition at line 112 of file TypeDetail.h.
Referenced by getHashValue().
storageType
Type mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::storageType
Definition at line 107 of file TypeDetail.h.
Referenced by getHashValue().
storageTypeMax
int64_t mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::storageTypeMax
Definition at line 115 of file TypeDetail.h.
Referenced by getHashValue().
storageTypeMin
int64_t mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::storageTypeMin
Definition at line 114 of file TypeDetail.h.
Referenced by getHashValue().
zeroPoint
int64_t mlir::quant::detail::UniformQuantizedTypeStorage::KeyTy::zeroPoint
Definition at line 113 of file TypeDetail.h.
Referenced by getHashValue().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h