MLIR: mlir::spirv::detail::ArrayTypeStorage Struct Reference
mlir::spirv::detail::ArrayTypeStorage Struct Reference
Public Types
using KeyTy = std::tuple<Type, unsigned, unsigned>
Public Member Functions
bool operator== (const KeyTy &key) const
ArrayTypeStorage (const KeyTy &key)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static ArrayTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type elementType
unsigned elementCount
unsigned stride
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 137 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::ArrayTypeStorage::KeyTy = std::tuple<Type, unsigned, unsigned>
Definition at line 138 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
ArrayTypeStorage()
mlir::spirv::detail::ArrayTypeStorage::ArrayTypeStorage (const KeyTy & key) inline
Definition at line 149 of file SPIRVTypes.cpp.
References elementCount, elementType, mlir::get(), and stride.
Referenced by construct().
Member Function Documentation
construct()
ArrayTypeStorage * mlir::spirv::detail::ArrayTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 140 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and ArrayTypeStorage().
operator==()
bool mlir::spirv::detail::ArrayTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 145 of file SPIRVTypes.cpp.
References elementCount, elementType, and stride.
Member Data Documentation
elementCount
unsigned mlir::spirv::detail::ArrayTypeStorage::elementCount
Definition at line 154 of file SPIRVTypes.cpp.
Referenced by ArrayTypeStorage(), and operator==().
elementType
Type mlir::spirv::detail::ArrayTypeStorage::elementType
Definition at line 153 of file SPIRVTypes.cpp.
Referenced by ArrayTypeStorage(), and operator==().
stride
unsigned mlir::spirv::detail::ArrayTypeStorage::stride
Definition at line 155 of file SPIRVTypes.cpp.
Referenced by ArrayTypeStorage(), and operator==().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp