MLIR: SliceCanonicalizer Struct Reference
SliceCanonicalizer Struct Reference
A canonicalizer wrapper to replace ExtractSliceOps.
Public Member Functions
void operator() (PatternRewriter &rewriter, ExtractSliceOp op, ExtractSliceOp newOp)
Detailed Description
A canonicalizer wrapper to replace ExtractSliceOps.
Definition at line 954 of file TensorOps.cpp.
Member Function Documentation
operator()()
void SliceCanonicalizer::operator() (PatternRewriter & rewriter, ExtractSliceOp op, ExtractSliceOp newOp) inline
Definition at line 955 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::Value::getType(), and mlir::RewriterBase::replaceOp().
The documentation for this struct was generated from the following file:
lib/Dialect/Tensor/IR/TensorOps.cpp