MLIR: mlir::affine::AffineValueExpr Struct Reference
mlir::affine::AffineValueExpr Struct Reference
#include "mlir/Dialect/Affine/Utils.h"
Public Member Functions
AffineValueExpr (AffineExpr e)
AffineValueExpr bind (Value v)
AffineValueExpr bind (OpFoldResult v)
operator AffineExpr () const
operator OpFoldResult () const
Public Attributes
AffineExpr e
OpFoldResult v
Detailed Description
Definition at line 354 of file Utils.h.
Constructor & Destructor Documentation
AffineValueExpr()
mlir::affine::AffineValueExpr::AffineValueExpr (AffineExpr e) inline explicit
Definition at line 355 of file Utils.h.
References e.
Referenced by bind(), and bind().
Member Function Documentation
bind() [1/2]
AffineValueExpr mlir::affine::AffineValueExpr::bind (OpFoldResult v) inline
Definition at line 360 of file Utils.h.
References AffineValueExpr(), and v.
bind() [2/2]
AffineValueExpr mlir::affine::AffineValueExpr::bind (Value v) inline
Definition at line 356 of file Utils.h.
References AffineValueExpr(), and v.
operator AffineExpr()
mlir::affine::AffineValueExpr::operator AffineExpr () const inline
Definition at line 364 of file Utils.h.
References e.
operator OpFoldResult()
mlir::affine::AffineValueExpr::operator OpFoldResult () const inline
Definition at line 365 of file Utils.h.
References v.
Member Data Documentation
e
AffineExpr mlir::affine::AffineValueExpr::e
Definition at line 366 of file Utils.h.
Referenced by AffineValueExpr(), and operator AffineExpr().
v
OpFoldResult mlir::affine::AffineValueExpr::v
Definition at line 367 of file Utils.h.
Referenced by bind(), bind(), and operator OpFoldResult().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Affine/Utils.h