MLIR: mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType > Struct Template Reference
mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType > Struct Template Reference
Utility trait base that provides accessors for derived traits that have multiple successors.
#include "mlir/IR/OpDefinition.h"
Public Types
using succ_iterator = Operation::succ_iterator
using succ_range = SuccessorRange
Public Member Functions
unsigned getNumSuccessors ()
Return the number of successors.
Block * getSuccessor (unsigned i)
Return the successor at index.
void setSuccessor (Block *block, unsigned i)
Set the successor at index.
succ_iterator succ_begin ()
Successor iterator access.
succ_iterator succ_end ()
succ_range getSuccessors ()
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, TraitType >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType, template< typename > class TraitType>
struct mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >
Utility trait base that provides accessors for derived traits that have multiple successors.
Definition at line 794 of file OpDefinition.h.
Member Typedef Documentation
succ_iterator
template<typename ConcreteType , template< typename > class TraitType> using mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::succ_iterator = Operation::succ_iterator
Definition at line 795 of file OpDefinition.h.
succ_range
template<typename ConcreteType , template< typename > class TraitType> using mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::succ_range = SuccessorRange
Definition at line 796 of file OpDefinition.h.
Member Function Documentation
getNumSuccessors()
template<typename ConcreteType , template< typename > class TraitType> unsigned mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getNumSuccessors () inline
Return the number of successors.
Definition at line 799 of file OpDefinition.h.
References mlir::Operation::getNumSuccessors(), and mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation().
getSuccessor()
template<typename ConcreteType , template< typename > class TraitType> Block* mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessor (unsigned i) inline
Return the successor at index.
Definition at line 804 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation(), and mlir::Operation::getSuccessor().
getSuccessors()
template<typename ConcreteType , template< typename > class TraitType> succ_range mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessors () inline
Definition at line 816 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation(), and mlir::Operation::getSuccessors().
setSuccessor()
template<typename ConcreteType , template< typename > class TraitType> void mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::setSuccessor (Block * block, unsigned i) inline
Set the successor at index.
Definition at line 809 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation(), and mlir::Operation::setSuccessor().
succ_begin()
template<typename ConcreteType , template< typename > class TraitType> succ_iterator mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::succ_begin () inline
Successor iterator access.
Definition at line 814 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation().
succ_end()
template<typename ConcreteType , template< typename > class TraitType> succ_iterator mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::succ_end () inline
Definition at line 815 of file OpDefinition.h.
References mlir::OpTrait::TraitBase< ConcreteType, TraitType >::getOperation().
The documentation for this struct was generated from the following file:
include/mlir/IR/OpDefinition.h