MLIR: mlir::PyPrintAccumulator Struct Reference
mlir::PyPrintAccumulator Struct Reference
Accumulates into a python string from a method that accepts an MlirStringCallback.
#include "Bindings/Python/NanobindUtils.h"
Public Member Functions
void * getUserData ()
MlirStringCallback getCallback ()
nanobind::str join ()
Public Attributes
nanobind::list parts
Detailed Description
Accumulates into a python string from a method that accepts an MlirStringCallback.
Definition at line 116 of file NanobindUtils.h.
Member Function Documentation
getCallback()
MlirStringCallback mlir::PyPrintAccumulator::getCallback () inline
Definition at line 121 of file NanobindUtils.h.
References MlirStringRef::data, MlirStringRef::length, and parts.
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::bind(), and populateDialectSMTSubmodule().
getUserData()
void * mlir::PyPrintAccumulator::getUserData () inline
Definition at line 119 of file NanobindUtils.h.
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::bind(), and populateDialectSMTSubmodule().
join()
nanobind::str mlir::PyPrintAccumulator::join () inline
Definition at line 131 of file NanobindUtils.h.
References parts.
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::bind(), and populateDialectSMTSubmodule().
Member Data Documentation
parts
nanobind::list mlir::PyPrintAccumulator::parts
Definition at line 117 of file NanobindUtils.h.
Referenced by mlir::python::PyConcreteAttribute< DerivedTy, BaseTy >::bind(), mlir::python::PyConcreteType< DerivedTy, BaseTy >::bind(), getCallback(), and join().
The documentation for this struct was generated from the following file:
lib/Bindings/Python/NanobindUtils.h