MLIR: L0RTContextWrapper Struct Reference
L0RTContextWrapper Struct Reference
Public Member Functions
L0RTContextWrapper ()=default
L0RTContextWrapper (const uint32_t driverIdx=0, const int32_t devIdx=0)
L0RTContextWrapper (const L0RTContextWrapper &)=delete
L0RTContextWrapper & operator= (const L0RTContextWrapper &)=delete
L0RTContextWrapper (L0RTContextWrapper &&) noexcept=default
L0RTContextWrapper & operator= (L0RTContextWrapper &&) noexcept=default
~L0RTContextWrapper ()=default
Public Attributes
ze_driver_handle_t driver {nullptr}
ze_device_handle_t device {nullptr}
UniqueZeContext context
UniqueZeCommandList immCmdListCompute
UniqueZeCommandList immCmdListCopy
uint32_t copyEngineMaxMemoryFillPatternSize {-1u}
Detailed Description
Definition at line 139 of file LevelZeroRuntimeWrappers.cpp.
Constructor & Destructor Documentation
L0RTContextWrapper() [1/4]
L0RTContextWrapper::L0RTContextWrapper () default
Referenced by L0RTContextWrapper(), L0RTContextWrapper(), mgpuSetDefaultDevice(), operator=(), operator=(), and ~L0RTContextWrapper().
L0RTContextWrapper() [2/4]
L0RTContextWrapper::L0RTContextWrapper (const uint32_t driverIdx = 0, const int32_t devIdx = 0) inline
Definition at line 152 of file LevelZeroRuntimeWrappers.cpp.
References context, copyEngineMaxMemoryFillPatternSize, device, driver, getContext(), getDevice(), getDriver(), immCmdListCompute, immCmdListCopy, and L0_SAFE_CALL.
L0RTContextWrapper() [3/4]
L0RTContextWrapper::L0RTContextWrapper (const L0RTContextWrapper &) delete
References L0RTContextWrapper().
L0RTContextWrapper() [4/4]
L0RTContextWrapper::L0RTContextWrapper (L0RTContextWrapper &&) default noexcept
References L0RTContextWrapper().
~L0RTContextWrapper()
L0RTContextWrapper::~L0RTContextWrapper () default
References L0RTContextWrapper().
Member Function Documentation
operator=() [1/2]
L0RTContextWrapper & L0RTContextWrapper::operator= (const L0RTContextWrapper &) delete
References L0RTContextWrapper().
operator=() [2/2]
L0RTContextWrapper & L0RTContextWrapper::operator= (L0RTContextWrapper &&) default noexcept
References L0RTContextWrapper().
Member Data Documentation
context
UniqueZeContext L0RTContextWrapper::context
Definition at line 142 of file LevelZeroRuntimeWrappers.cpp.
Referenced by L0RTContextWrapper(), loadModule(), mgpuMemAlloc(), and mgpuMemFree().
copyEngineMaxMemoryFillPatternSize
uint32_t L0RTContextWrapper::copyEngineMaxMemoryFillPatternSize {-1u}
Definition at line 149 of file LevelZeroRuntimeWrappers.cpp.
Referenced by L0RTContextWrapper(), and mgpuMemset().
device
ze_device_handle_t L0RTContextWrapper::device {nullptr}
Definition at line 141 of file LevelZeroRuntimeWrappers.cpp.
Referenced by L0RTContextWrapper(), loadModule(), and mgpuMemAlloc().
driver
ze_driver_handle_t L0RTContextWrapper::driver {nullptr}
Definition at line 140 of file LevelZeroRuntimeWrappers.cpp.
Referenced by L0RTContextWrapper().
immCmdListCompute
UniqueZeCommandList L0RTContextWrapper::immCmdListCompute
Definition at line 145 of file LevelZeroRuntimeWrappers.cpp.
Referenced by L0RTContextWrapper(), mgpuEventRecord(), mgpuLaunchKernel(), and mgpuMemset().
immCmdListCopy
UniqueZeCommandList L0RTContextWrapper::immCmdListCopy
Definition at line 148 of file LevelZeroRuntimeWrappers.cpp.
Referenced by L0RTContextWrapper(), mgpuEventRecord(), mgpuMemcpy(), and mgpuMemset().
The documentation for this struct was generated from the following file:
lib/ExecutionEngine/LevelZeroRuntimeWrappers.cpp