MLIR: mlir::presburger::PWMAFunction::Piece Struct Reference
mlir::presburger::PWMAFunction::Piece Struct Reference
#include "mlir/Analysis/Presburger/PWMAFunction.h"
Public Member Functions
bool isConsistent () const
Public Attributes
PresburgerSet domain
MultiAffineFunction output
Detailed Description
Definition at line 155 of file PWMAFunction.h.
Member Function Documentation
isConsistent()
bool mlir::presburger::PWMAFunction::Piece::isConsistent () const inline
Definition at line 159 of file PWMAFunction.h.
References domain, mlir::presburger::MultiAffineFunction::getDomainSpace(), mlir::presburger::PresburgerRelation::getSpace(), mlir::presburger::PresburgerSpace::isCompatible(), and output.
Referenced by mlir::presburger::PWMAFunction::addPiece().
Member Data Documentation
domain
PresburgerSet mlir::presburger::PWMAFunction::Piece::domain
Definition at line 156 of file PWMAFunction.h.
Referenced by mlir::presburger::PWMAFunction::addPiece(), mlir::presburger::IntegerRelation::findSymbolicIntegerLexMax(), isConsistent(), and tiebreakLex().
output
MultiAffineFunction mlir::presburger::PWMAFunction::Piece::output
Definition at line 157 of file PWMAFunction.h.
Referenced by isConsistent(), and tiebreakLex().
The documentation for this struct was generated from the following file:
include/mlir/Analysis/Presburger/PWMAFunction.h