MLIR: llvm::GraphTraits< mlir::Region * > Struct Reference
llvm::GraphTraits< mlir::Region * > Struct Reference
#include "mlir/IR/RegionGraphTraits.h"
Public Types
using GraphType = mlir::Region *
using NodeRef = mlir::Block *
using nodes_iterator = pointer_iterator<mlir::Region::iterator>
Public Types inherited from llvm::GraphTraits< mlir::Block * >
using ChildIteratorType = mlir::Block::succ_iterator
using Node = mlir::Block
using NodeRef = Node *
Static Public Member Functions
static NodeRef getEntryNode (GraphType fn)
static nodes_iterator nodes_begin (GraphType fn)
static nodes_iterator nodes_end (GraphType fn)
Static Public Member Functions inherited from llvm::GraphTraits< mlir::Block * >
static NodeRef getEntryNode (NodeRef bb)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 87 of file RegionGraphTraits.h.
Member Typedef Documentation
GraphType
using llvm::GraphTraits< mlir::Region * >::GraphType = mlir::Region *
Definition at line 88 of file RegionGraphTraits.h.
NodeRef
using llvm::GraphTraits< mlir::Region * >::NodeRef = mlir::Block *
Definition at line 89 of file RegionGraphTraits.h.
nodes_iterator
using llvm::GraphTraits< mlir::Region * >::nodes_iterator = pointer_iterator<mlir::Region::iterator>
Definition at line 93 of file RegionGraphTraits.h.
Member Function Documentation
getEntryNode()
NodeRef llvm::GraphTraits< mlir::Region * >::getEntryNode (GraphType fn) inline static
Definition at line 91 of file RegionGraphTraits.h.
References mlir::Region::front().
nodes_begin()
nodes_iterator llvm::GraphTraits< mlir::Region * >::nodes_begin (GraphType fn) inline static
Definition at line 94 of file RegionGraphTraits.h.
References mlir::Region::begin().
nodes_end()
nodes_iterator llvm::GraphTraits< mlir::Region * >::nodes_end (GraphType fn) inline static
Definition at line 97 of file RegionGraphTraits.h.
References mlir::Region::end().
The documentation for this struct was generated from the following file:
include/mlir/IR/RegionGraphTraits.h