MLIR: mlir::transform::gpu::GpuIdBuilder Struct Reference
mlir::transform::gpu::GpuIdBuilder Struct Reference
Helper struct for configuring the rewrite of mapped scf.forall ops to various gpu id configurations.
#include "mlir/Dialect/GPU/TransformOps/Utils.h"
Public Types
using MappingIdBuilderFnType
Public Member Functions
GpuIdBuilder ()=default
GpuIdBuilder (MLIRContext *ctx, bool useLinearMapping, const MappingIdBuilderFnType &builder)
Public Attributes
SmallVector< DeviceMappingAttrInterface > mappingAttributes
The mapping attributes targeted by this generator.
GpuIdBuilderFnType idBuilder
The constructor that builds the concrete IR for mapping ids.
Detailed Description
Helper struct for configuring the rewrite of mapped scf.forall ops to various gpu id configurations.
Definition at line 60 of file Utils.h.
Member Typedef Documentation
MappingIdBuilderFnType
using mlir::transform::gpu::GpuIdBuilder::MappingIdBuilderFnType
Initial value:
 std::function<DeviceMappingAttrInterface(
      MLIRContext *, mlir::gpu::MappingId)>
Definition at line 61 of file Utils.h.
Constructor & Destructor Documentation
GpuIdBuilder() [1/2]
mlir::transform::gpu::GpuIdBuilder::GpuIdBuilder () default
Referenced by mlir::transform::gpu::GpuBlockIdBuilder::GpuBlockIdBuilder(), mlir::transform::gpu::GpuLaneIdBuilder::GpuLaneIdBuilder(), mlir::transform::gpu::GpuThreadIdBuilder::GpuThreadIdBuilder(), mlir::transform::gpu::GpuWarpgroupIdBuilder::GpuWarpgroupIdBuilder(), and mlir::transform::gpu::GpuWarpIdBuilder::GpuWarpIdBuilder().
GpuIdBuilder() [2/2]
mlir::transform::gpu::GpuIdBuilder::GpuIdBuilder (MLIRContext * ctx, bool useLinearMapping, const MappingIdBuilderFnType & builder)
Definition at line 280 of file Utils.cpp.
References idBuilder, and mappingAttributes.
Member Data Documentation
idBuilder
GpuIdBuilderFnType mlir::transform::gpu::GpuIdBuilder::idBuilder
The constructor that builds the concrete IR for mapping ids.
Definition at line 72 of file Utils.h.
Referenced by GpuIdBuilder(), and rewriteOneForallCommonImpl().
mappingAttributes
SmallVector<DeviceMappingAttrInterface> mlir::transform::gpu::GpuIdBuilder::mappingAttributes
The mapping attributes targeted by this generator.
Definition at line 69 of file Utils.h.
Referenced by GpuIdBuilder(), and rewriteOneForallCommonImpl().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/GPU/TransformOps/Utils.h
lib/Dialect/GPU/TransformOps/Utils.cpp