MLIR: mlir::LLVM::detail::LLVMStructTypeStorage Struct Reference
mlir::LLVM::detail::LLVMStructTypeStorage Struct Reference
Type storage for LLVM structure types.
#include "Dialect/LLVMIR/IR/TypeDetail.h"
Classes
class Key
Construction/uniquing key class for LLVM dialect structure storage.
Public Types
using KeyTy = Key
Public Member Functions
StringRef getIdentifier () const
Returns the string identifier of an identified struct.
ArrayRef< Type > getTypeList () const
Returns the list of types (partially) identifying a literal struct.
ArrayRef< Type > getIdentifiedStructBody () const
Returns the list of types contained in an identified struct.
bool isIdentified () const
Checks whether the struct is identified.
bool isPacked () const
Checks whether the struct is packed (both literal and identified structs).
bool isOpaque () const
Checks whether a struct is marked as intentionally opaque (an uninitialized struct is also considered opaque by the user, call isInitialized to check that).
bool isInitialized () const
Checks whether an identified struct has been explicitly initialized either by setting its body or by marking it as intentionally opaque.
LLVMStructTypeStorage (const KeyTy &key)
Constructs the storage from the given key.
bool operator== (const KeyTy &other) const
Hook into the type uniquing infrastructure.
LogicalResult mutate (TypeStorageAllocator &allocator, ArrayRef< Type > body, bool packed)
Sets the body of an identified struct.
Key getAsKey () const
Returns the key for the current storage.
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static llvm::hash_code hashKey (const KeyTy &key)
static LLVMStructTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Type storage for LLVM structure types.
Structures are uniqued using:
a bit indicating whether a struct is literal or identified;
for identified structs, in addition to the bit:
a string identifier;
for literal structs, in addition to the bit:
a list of contained types;
a bit indicating whether the literal struct is packed.
Identified structures only have a mutable component consisting of:
a list of contained types;
a bit indicating whether the identified struct is packed;
a bit indicating whether the identified struct is intentionally opaque;
a bit indicating whether the identified struct has been initialized. Uninitialized structs are considered opaque by the user, and can be mutated. Initialized and still opaque structs cannot be mutated.
The struct storage consists of:
immutable part:
a pointer to the first element of the key (character for identified structs, type for literal structs);
the number of elements in the key packed together with bits indicating whether a type is literal or identified, and the packedness bit for literal structs only;
mutable part:
a pointer to the first contained type for identified structs only;
the number of contained types packed together with bits of the mutable component, for identified structs only.
Definition at line 61 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::LLVM::detail::LLVMStructTypeStorage::KeyTy = Key
Definition at line 154 of file TypeDetail.h.
Constructor & Destructor Documentation
LLVMStructTypeStorage()
mlir::LLVM::detail::LLVMStructTypeStorage::LLVMStructTypeStorage (const KeyTy & key) inline
Constructs the storage from the given key.
This sets up the uniquing key components and optionally the mutable component if they construction key has the relevant information. In the latter case, the struct is considered as initialized and can no longer be mutated.
Definition at line 207 of file TypeDetail.h.
References mlir::LLVM::detail::LLVMStructTypeStorage::Key::getIdentifier(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::getTypeList(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::isIdentified(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::isOpaque(), and mlir::LLVM::detail::LLVMStructTypeStorage::Key::isPacked().
Referenced by construct().
Member Function Documentation
construct()
LLVMStructTypeStorage * mlir::LLVM::detail::LLVMStructTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 232 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::copyIntoAllocator(), and LLVMStructTypeStorage().
getAsKey()
Key mlir::LLVM::detail::LLVMStructTypeStorage::getAsKey () const inline
Returns the key for the current storage.
Definition at line 262 of file TypeDetail.h.
References getIdentifiedStructBody(), getIdentifier(), getTypeList(), isIdentified(), isOpaque(), and isPacked().
Referenced by operator==().
getIdentifiedStructBody()
ArrayRef< Type > mlir::LLVM::detail::LLVMStructTypeStorage::getIdentifiedStructBody () const inline
Returns the list of types contained in an identified struct.
Definition at line 170 of file TypeDetail.h.
References isIdentified().
Referenced by getAsKey(), and mutate().
getIdentifier()
StringRef mlir::LLVM::detail::LLVMStructTypeStorage::getIdentifier () const inline
Returns the string identifier of an identified struct.
Definition at line 157 of file TypeDetail.h.
References isIdentified().
Referenced by getAsKey().
getTypeList()
ArrayRef< Type > mlir::LLVM::detail::LLVMStructTypeStorage::getTypeList () const inline
Returns the list of types (partially) identifying a literal struct.
Definition at line 163 of file TypeDetail.h.
References isIdentified().
Referenced by getAsKey().
hashKey()
llvm::hash_code mlir::LLVM::detail::LLVMStructTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 231 of file TypeDetail.h.
References mlir::LLVM::detail::LLVMStructTypeStorage::Key::hashValue().
isIdentified()
bool mlir::LLVM::detail::LLVMStructTypeStorage::isIdentified () const inline
Checks whether the struct is identified.
Definition at line 178 of file TypeDetail.h.
Referenced by getAsKey(), getIdentifiedStructBody(), getIdentifier(), getTypeList(), isPacked(), and mutate().
isInitialized()
bool mlir::LLVM::detail::LLVMStructTypeStorage::isInitialized () const inline
Checks whether an identified struct has been explicitly initialized either by setting its body or by marking it as intentionally opaque.
Definition at line 198 of file TypeDetail.h.
Referenced by mutate().
isOpaque()
bool mlir::LLVM::detail::LLVMStructTypeStorage::isOpaque () const inline
Checks whether a struct is marked as intentionally opaque (an uninitialized struct is also considered opaque by the user, call isInitialized to check that).
Definition at line 192 of file TypeDetail.h.
Referenced by getAsKey(), and mutate().
isPacked()
bool mlir::LLVM::detail::LLVMStructTypeStorage::isPacked () const inline
Checks whether the struct is packed (both literal and identified structs).
Definition at line 183 of file TypeDetail.h.
References isIdentified().
Referenced by getAsKey(), and mutate().
mutate()
LogicalResult mlir::LLVM::detail::LLVMStructTypeStorage::mutate (TypeStorageAllocator & allocator, ArrayRef< Type > body, bool packed) inline
Sets the body of an identified struct.
If the struct is already initialized, succeeds only if the body is equal to the current body. Fails if the struct is marked as intentionally opaque. The struct will be marked as initialized as a result of this operation and can no longer be changed.
Definition at line 242 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::copyInto(), getIdentifiedStructBody(), isIdentified(), isInitialized(), isOpaque(), isPacked(), and success().
operator==()
bool mlir::LLVM::detail::LLVMStructTypeStorage::operator== (const KeyTy & other) const inline
Hook into the type uniquing infrastructure.
Definition at line 230 of file TypeDetail.h.
References getAsKey().
The documentation for this struct was generated from the following file:
lib/Dialect/LLVMIR/IR/TypeDetail.h