MLIR: mlir::spirv::detail::SampledImageTypeStorage Struct Reference
mlir::spirv::detail::SampledImageTypeStorage Struct Reference
Public Types
using KeyTy = Type
Public Member Functions
SampledImageTypeStorage (const KeyTy &key)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static SampledImageTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Type imageType
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 740 of file SPIRVTypes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::SampledImageTypeStorage::KeyTy = Type
Definition at line 741 of file SPIRVTypes.cpp.
Constructor & Destructor Documentation
SampledImageTypeStorage()
mlir::spirv::detail::SampledImageTypeStorage::SampledImageTypeStorage (const KeyTy & key) inline
Definition at line 743 of file SPIRVTypes.cpp.
References imageType.
Referenced by construct().
Member Function Documentation
construct()
SampledImageTypeStorage * mlir::spirv::detail::SampledImageTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 747 of file SPIRVTypes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and SampledImageTypeStorage().
operator==()
bool mlir::spirv::detail::SampledImageTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 745 of file SPIRVTypes.cpp.
References imageType.
Member Data Documentation
imageType
Type mlir::spirv::detail::SampledImageTypeStorage::imageType
Definition at line 753 of file SPIRVTypes.cpp.
Referenced by operator==(), and SampledImageTypeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVTypes.cpp