MLIR: mlir::tblgen::DialectInterface Struct Reference
mlir::tblgen::DialectInterface Struct Reference
#include "mlir/TableGen/Interfaces.h"
Public Member Functions
Interface (const llvm::Record *def)
Interface (const Interface &rhs)
Public Member Functions inherited from mlir::tblgen::Interface
Interface (const llvm::Record *def)
Interface (const Interface &rhs)
StringRef getName () const
std::string getFullyQualifiedName () const
StringRef getCppNamespace () const
ArrayRef< InterfaceMethod > getMethods () const
std::optional< StringRef > getDescription () const
std::optional< StringRef > getExtraClassDeclaration () const
std::optional< StringRef > getExtraTraitClassDeclaration () const
std::optional< StringRef > getExtraSharedClassDeclaration () const
std::optional< StringRef > getExtraClassOf () const
std::optional< StringRef > getVerify () const
auto getBaseInterfaces () const
bool verifyWithRegions () const
const llvm::Record & getDef () const
Static Public Member Functions
static bool classof (const Interface *interface)
Detailed Description
Definition at line 161 of file Interfaces.h.
Member Function Documentation
classof()
bool DialectInterface::classof (const Interface * interface) static
Definition at line 216 of file Interfaces.cpp.
References mlir::tblgen::Interface::getDef(), and Interface().
Interface() [1/2]
mlir::tblgen::Interface::Interface (const Interface & rhs) inline
Definition at line 83 of file Interfaces.h.
Interface() [2/2]
mlir::tblgen::Interface::Interface (const llvm::Record * def) explicit
Referenced by classof().
The documentation for this struct was generated from the following files:
include/mlir/TableGen/Interfaces.h
lib/TableGen/Interfaces.cpp