MLIR: mlir::python::PyMlirContext::ErrorCapture Struct Reference
mlir::python::PyMlirContext::ErrorCapture Struct Reference
RAII object that captures any error diagnostics emitted to the provided context.
#include "Bindings/Python/IRModule.h"
Public Member Functions
ErrorCapture (PyMlirContextRef ctx)
~ErrorCapture ()
std::vector< PyDiagnostic::DiagnosticInfo > take ()
Detailed Description
RAII object that captures any error diagnostics emitted to the provided context.
Definition at line 455 of file IRModule.h.
Constructor & Destructor Documentation
ErrorCapture()
mlir::python::PyMlirContext::ErrorCapture::ErrorCapture (PyMlirContextRef ctx) inline
Definition at line 456 of file IRModule.h.
~ErrorCapture()
mlir::python::PyMlirContext::ErrorCapture::~ErrorCapture () inline
Definition at line 460 of file IRModule.h.
References mlir::python::PyMlirContext::get(), and mlirContextDetachDiagnosticHandler().
Member Function Documentation
take()
std::vector<PyDiagnostic::DiagnosticInfo> mlir::python::PyMlirContext::ErrorCapture::take () inline
Definition at line 465 of file IRModule.h.
Referenced by mlir::python::PyOperation::parse(), and mlir::python::PyOperationBase::verify().
The documentation for this struct was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp