MLIR: mlir::AttrTypeSubElementHandler< LLVM::detail::LLVMStructTypeStorage::Key > Struct Reference
mlir::AttrTypeSubElementHandler< LLVM::detail::LLVMStructTypeStorage::Key > Struct Reference
Allow walking and replacing the subelements of a LLVMStructTypeStorage key.
#include "Dialect/LLVMIR/IR/TypeDetail.h"
Static Public Member Functions
static void walk (const LLVM::detail::LLVMStructTypeStorage::Key &param, AttrTypeImmediateSubElementWalker &walker)
static FailureOr< LLVM::detail::LLVMStructTypeStorage::Key > replace (const LLVM::detail::LLVMStructTypeStorage::Key &param, AttrSubElementReplacements &attrRepls, TypeSubElementReplacements &typeRepls)
Detailed Description
Allow walking and replacing the subelements of a LLVMStructTypeStorage key.
Definition at line 335 of file TypeDetail.h.
Member Function Documentation
replace()
static FailureOr<LLVM::detail::LLVMStructTypeStorage::Key> mlir::AttrTypeSubElementHandler< LLVM::detail::LLVMStructTypeStorage::Key >::replace (const LLVM::detail::LLVMStructTypeStorage::Key & param, AttrSubElementReplacements & attrRepls, TypeSubElementReplacements & typeRepls) inline static
Definition at line 344 of file TypeDetail.h.
References mlir::LLVM::detail::LLVMStructTypeStorage::Key::getTypeList(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::isIdentified(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::isPacked(), and mlir::AttrTypeSubElementReplacements< T >::take_front().
walk()
static void mlir::AttrTypeSubElementHandler< LLVM::detail::LLVMStructTypeStorage::Key >::walk (const LLVM::detail::LLVMStructTypeStorage::Key & param, AttrTypeImmediateSubElementWalker & walker) inline static
Definition at line 336 of file TypeDetail.h.
References mlir::LLVM::detail::LLVMStructTypeStorage::Key::getIdentifiedStructBody(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::getTypeList(), mlir::LLVM::detail::LLVMStructTypeStorage::Key::isIdentified(), and mlir::AttrTypeImmediateSubElementWalker::walkRange().
The documentation for this struct was generated from the following file:
lib/Dialect/LLVMIR/IR/TypeDetail.h