MLIR: mlir::lsp::LSPServer::Impl Struct Reference
mlir::lsp::LSPServer::Impl Struct Reference
Public Member Functions
Impl (MLIRServer &server, JSONTransport &transport)
void onInitialize (const InitializeParams &params, Callback< llvm::json::Value > reply)
void onInitialized (const InitializedParams &params)
void onShutdown (const NoParams &params, Callback< std::nullptr_t > reply)
void onDocumentDidOpen (const DidOpenTextDocumentParams &params)
void onDocumentDidClose (const DidCloseTextDocumentParams &params)
void onDocumentDidChange (const DidChangeTextDocumentParams &params)
void onGoToDefinition (const TextDocumentPositionParams &params, Callback< std::vector< Location >> reply)
void onReference (const ReferenceParams &params, Callback< std::vector< Location >> reply)
void onHover (const TextDocumentPositionParams &params, Callback< Optional< Hover >> reply)
void onDocumentSymbol (const DocumentSymbolParams &params, Callback< std::vector< DocumentSymbol >> reply)
Public Attributes
MLIRServer & server
JSONTransport & transport
OutgoingNotification< PublishDiagnosticsParams > publishDiagnostics
An outgoing notification used to send diagnostics to the client when they are ready to be processed.
bool shutdownRequestReceived = false
Used to indicate that the 'shutdown' request was received from the Language Server client.
Detailed Description
Definition at line 26 of file LSPServer.cpp.
Constructor & Destructor Documentation
Impl()
mlir::lsp::LSPServer::Impl::Impl (MLIRServer & server, JSONTransport & transport) inline
Definition at line 27 of file LSPServer.cpp.
References mlir::lsp::LSPServer::Impl::onDocumentDidChange(), mlir::lsp::LSPServer::Impl::onDocumentDidClose(), mlir::lsp::LSPServer::Impl::onDocumentDidOpen(), mlir::lsp::LSPServer::Impl::onDocumentSymbol(), mlir::lsp::LSPServer::Impl::onGoToDefinition(), mlir::lsp::LSPServer::Impl::onHover(), mlir::lsp::LSPServer::Impl::onInitialize(), mlir::lsp::LSPServer::Impl::onInitialized(), mlir::lsp::LSPServer::Impl::onReference(), and mlir::lsp::LSPServer::Impl::onShutdown().
Member Function Documentation
onDocumentDidChange()
void mlir::lsp::LSPServer::Impl::onDocumentDidChange (const DidChangeTextDocumentParams & params)
Definition at line 143 of file LSPServer.cpp.
References mlir::lsp::MLIRServer::addOrUpdateDocument(), mlir::lsp::DidChangeTextDocumentParams::contentChanges, mlir::lsp::PublishDiagnosticsParams::diagnostics, mlir::lsp::LSPServer::Impl::publishDiagnostics, mlir::lsp::LSPServer::Impl::server, mlir::lsp::DidChangeTextDocumentParams::textDocument, mlir::lsp::VersionedTextDocumentIdentifier::uri, and mlir::lsp::VersionedTextDocumentIdentifier::version.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onDocumentDidClose()
void mlir::lsp::LSPServer::Impl::onDocumentDidClose (const DidCloseTextDocumentParams & params)
Definition at line 131 of file LSPServer.cpp.
References mlir::lsp::LSPServer::Impl::publishDiagnostics, mlir::lsp::MLIRServer::removeDocument(), mlir::lsp::LSPServer::Impl::server, mlir::lsp::DidCloseTextDocumentParams::textDocument, and mlir::lsp::TextDocumentIdentifier::uri.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onDocumentDidOpen()
void mlir::lsp::LSPServer::Impl::onDocumentDidOpen (const DidOpenTextDocumentParams & params)
Definition at line 120 of file LSPServer.cpp.
References mlir::lsp::MLIRServer::addOrUpdateDocument(), mlir::lsp::PublishDiagnosticsParams::diagnostics, mlir::lsp::LSPServer::Impl::publishDiagnostics, mlir::lsp::LSPServer::Impl::server, mlir::lsp::TextDocumentItem::text, mlir::lsp::DidOpenTextDocumentParams::textDocument, mlir::lsp::TextDocumentItem::uri, and mlir::lsp::TextDocumentItem::version.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onDocumentSymbol()
void mlir::lsp::LSPServer::Impl::onDocumentSymbol (const DocumentSymbolParams & params, Callback< std::vector< DocumentSymbol >> reply)
Definition at line 187 of file LSPServer.cpp.
References mlir::lsp::MLIRServer::findDocumentSymbols(), mlir::lsp::LSPServer::Impl::server, mlir::lsp::DocumentSymbolParams::textDocument, and mlir::lsp::TextDocumentIdentifier::uri.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onGoToDefinition()
void mlir::lsp::LSPServer::Impl::onGoToDefinition (const TextDocumentPositionParams & params, Callback< std::vector< Location >> reply)
Definition at line 162 of file LSPServer.cpp.
References mlir::lsp::MLIRServer::getLocationsOf(), mlir::lsp::TextDocumentPositionParams::position, mlir::lsp::LSPServer::Impl::server, mlir::lsp::TextDocumentPositionParams::textDocument, and mlir::lsp::TextDocumentIdentifier::uri.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onHover()
void mlir::lsp::LSPServer::Impl::onHover (const TextDocumentPositionParams & params, Callback< Optional< Hover >> reply)
Definition at line 179 of file LSPServer.cpp.
References mlir::lsp::MLIRServer::findHover(), mlir::lsp::TextDocumentPositionParams::position, mlir::lsp::LSPServer::Impl::server, mlir::lsp::TextDocumentPositionParams::textDocument, and mlir::lsp::TextDocumentIdentifier::uri.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onInitialize()
void mlir::lsp::LSPServer::Impl::onInitialize (const InitializeParams & params, Callback< llvm::json::Value > reply)
Definition at line 84 of file LSPServer.cpp.
References mlir::lsp::InitializeParams::capabilities, mlir::lsp::Full, and mlir::lsp::ClientCapabilities::hierarchicalDocumentSymbol.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onInitialized()
void mlir::lsp::LSPServer::Impl::onInitialized (const InitializedParams & params)
Definition at line 110 of file LSPServer.cpp.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onReference()
void mlir::lsp::LSPServer::Impl::onReference (const ReferenceParams & params, Callback< std::vector< Location >> reply)
Definition at line 169 of file LSPServer.cpp.
References mlir::lsp::MLIRServer::findReferencesOf(), mlir::lsp::TextDocumentPositionParams::position, mlir::lsp::LSPServer::Impl::server, mlir::lsp::TextDocumentPositionParams::textDocument, and mlir::lsp::TextDocumentIdentifier::uri.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
onShutdown()
void mlir::lsp::LSPServer::Impl::onShutdown (const NoParams & params, Callback< std::nullptr_t > reply)
Definition at line 111 of file LSPServer.cpp.
References mlir::lsp::LSPServer::Impl::shutdownRequestReceived.
Referenced by mlir::lsp::LSPServer::Impl::Impl(), and mlir::lsp::LSPServer::run().
Member Data Documentation
publishDiagnostics
OutgoingNotification<PublishDiagnosticsParams> mlir::lsp::LSPServer::Impl::publishDiagnostics
An outgoing notification used to send diagnostics to the client when they are ready to be processed.
Definition at line 74 of file LSPServer.cpp.
Referenced by mlir::lsp::LSPServer::Impl::onDocumentDidChange(), mlir::lsp::LSPServer::Impl::onDocumentDidClose(), and mlir::lsp::LSPServer::Impl::onDocumentDidOpen().
server
MLIRServer& mlir::lsp::LSPServer::Impl::server
Definition at line 69 of file LSPServer.cpp.
Referenced by mlir::lsp::LSPServer::Impl::onDocumentDidChange(), mlir::lsp::LSPServer::Impl::onDocumentDidClose(), mlir::lsp::LSPServer::Impl::onDocumentDidOpen(), mlir::lsp::LSPServer::Impl::onDocumentSymbol(), mlir::lsp::LSPServer::Impl::onGoToDefinition(), mlir::lsp::LSPServer::Impl::onHover(), and mlir::lsp::LSPServer::Impl::onReference().
shutdownRequestReceived
bool mlir::lsp::LSPServer::Impl::shutdownRequestReceived = false
Used to indicate that the 'shutdown' request was received from the Language Server client.
Definition at line 78 of file LSPServer.cpp.
Referenced by mlir::lsp::LSPServer::Impl::onShutdown().
transport
JSONTransport& mlir::lsp::LSPServer::Impl::transport
Definition at line 70 of file LSPServer.cpp.
The documentation for this struct was generated from the following file:
lib/Tools/mlir-lsp-server/LSPServer.cpp