MLIR: mlir::spirv::detail::InterfaceVarABIAttributeStorage Struct Reference
mlir::spirv::detail::InterfaceVarABIAttributeStorage Struct Reference
Public Types
using KeyTy = std::tuple<Attribute, Attribute, Attribute>
Public Member Functions
InterfaceVarABIAttributeStorage (Attribute descriptorSet, Attribute binding, Attribute storageClass)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::AttributeStorage
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static InterfaceVarABIAttributeStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Attribute descriptorSet
Attribute binding
Attribute storageClass
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
void initializeAbstractAttribute (const AbstractAttribute &abstractAttr)
Set the abstract attribute for this storage instance.
void initialize (MLIRContext *context)
Default initialization for attribute storage classes that require no additional initialization.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 36 of file SPIRVAttributes.cpp.
Member Typedef Documentation
KeyTy
using mlir::spirv::detail::InterfaceVarABIAttributeStorage::KeyTy = std::tuple<Attribute, Attribute, Attribute>
Definition at line 37 of file SPIRVAttributes.cpp.
Constructor & Destructor Documentation
InterfaceVarABIAttributeStorage()
mlir::spirv::detail::InterfaceVarABIAttributeStorage::InterfaceVarABIAttributeStorage (Attribute descriptorSet, Attribute binding, Attribute storageClass) inline
Definition at line 39 of file SPIRVAttributes.cpp.
References binding, descriptorSet, and storageClass.
Referenced by construct().
Member Function Documentation
construct()
InterfaceVarABIAttributeStorage * mlir::spirv::detail::InterfaceVarABIAttributeStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 50 of file SPIRVAttributes.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), and InterfaceVarABIAttributeStorage().
operator==()
bool mlir::spirv::detail::InterfaceVarABIAttributeStorage::operator== (const KeyTy & key) const inline
Definition at line 44 of file SPIRVAttributes.cpp.
References binding, and descriptorSet.
Member Data Documentation
binding
Attribute mlir::spirv::detail::InterfaceVarABIAttributeStorage::binding
Definition at line 57 of file SPIRVAttributes.cpp.
Referenced by InterfaceVarABIAttributeStorage(), and operator==().
descriptorSet
Attribute mlir::spirv::detail::InterfaceVarABIAttributeStorage::descriptorSet
Definition at line 56 of file SPIRVAttributes.cpp.
Referenced by InterfaceVarABIAttributeStorage(), and operator==().
storageClass
Attribute mlir::spirv::detail::InterfaceVarABIAttributeStorage::storageClass
Definition at line 58 of file SPIRVAttributes.cpp.
Referenced by InterfaceVarABIAttributeStorage().
The documentation for this struct was generated from the following file:
lib/Dialect/SPIRV/IR/SPIRVAttributes.cpp