MLIR: mlir::raw_indented_ostream::DelimitedScope Struct Reference
mlir::raw_indented_ostream::DelimitedScope Struct Reference
Simple RAII struct to use to indentation around entering/exiting region.
#include "mlir/Support/IndentedOstream.h"
Public Member Functions
DelimitedScope (raw_indented_ostream &os, StringRef open="", StringRef close="")
~DelimitedScope ()
Public Attributes
raw_indented_ostream & os
Detailed Description
Simple RAII struct to use to indentation around entering/exiting region.
Definition at line 30 of file IndentedOstream.h.
Constructor & Destructor Documentation
DelimitedScope()
mlir::raw_indented_ostream::DelimitedScope::DelimitedScope (raw_indented_ostream & os, StringRef open = "", StringRef close = "") inline explicit
Definition at line 31 of file IndentedOstream.h.
References mlir::raw_indented_ostream::indent().
Referenced by mlir::raw_indented_ostream::scope().
~DelimitedScope()
mlir::raw_indented_ostream::DelimitedScope::~DelimitedScope () inline
Definition at line 37 of file IndentedOstream.h.
References os, and mlir::raw_indented_ostream::unindent().
Member Data Documentation
os
raw_indented_ostream& mlir::raw_indented_ostream::DelimitedScope::os
Definition at line 42 of file IndentedOstream.h.
Referenced by mlir::raw_indented_ostream::indent(), and ~DelimitedScope().
The documentation for this struct was generated from the following file:
include/mlir/Support/IndentedOstream.h