MLIR: mlir::detail::DynamicTypeStorage Struct Reference
mlir::detail::DynamicTypeStorage Struct Reference
Storage of DynamicType.
Public Types
using KeyTy = std::pair<DynamicTypeDefinition *, ArrayRef<Attribute>>
Public Member Functions
DynamicTypeStorage (DynamicTypeDefinition *typeDef, ArrayRef< Attribute > params)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static llvm::hash_code hashKey (const KeyTy &key)
static DynamicTypeStorage * construct (TypeStorageAllocator &alloc, const KeyTy &key)
Public Attributes
DynamicTypeDefinition * typeDef
Definition of the type.
ArrayRef< Attribute > params
The type parameters.
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Storage of DynamicType.
Contains a pointer to the type definition and type parameters.
Definition at line 95 of file ExtensibleDialect.cpp.
Member Typedef Documentation
KeyTy
using mlir::detail::DynamicTypeStorage::KeyTy = std::pair<DynamicTypeDefinition *, ArrayRef<Attribute>>
Definition at line 97 of file ExtensibleDialect.cpp.
Constructor & Destructor Documentation
DynamicTypeStorage()
mlir::detail::DynamicTypeStorage::DynamicTypeStorage (DynamicTypeDefinition * typeDef, ArrayRef< Attribute > params) inline explicit
Definition at line 99 of file ExtensibleDialect.cpp.
References params, and typeDef.
Referenced by construct().
Member Function Documentation
construct()
DynamicTypeStorage * mlir::detail::DynamicTypeStorage::construct (TypeStorageAllocator & alloc, const KeyTy & key) inline static
Definition at line 111 of file ExtensibleDialect.cpp.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::StorageUniquer::StorageAllocator::copyInto(), and DynamicTypeStorage().
hashKey()
llvm::hash_code mlir::detail::DynamicTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 107 of file ExtensibleDialect.cpp.
operator==()
bool mlir::detail::DynamicTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 103 of file ExtensibleDialect.cpp.
References params, and typeDef.
Member Data Documentation
params
ArrayRef<Attribute> mlir::detail::DynamicTypeStorage::params
The type parameters.
Definition at line 121 of file ExtensibleDialect.cpp.
Referenced by DynamicTypeStorage(), and operator==().
typeDef
DynamicTypeDefinition* mlir::detail::DynamicTypeStorage::typeDef
Definition of the type.
Definition at line 118 of file ExtensibleDialect.cpp.
Referenced by DynamicTypeStorage(), and operator==().
The documentation for this struct was generated from the following file:
lib/IR/ExtensibleDialect.cpp