MLIR: mlir::linalg::GenerateLoopNest< LoopTy > Struct Template Reference
mlir::linalg::GenerateLoopNest< LoopTy > Struct Template Reference
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
#include "mlir/Dialect/Linalg/Utils/Utils.h"
Public Member Functions
template<>
void doit (OpBuilder &b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions, ArrayRef< StringRef > distributionTypes)
Specialization to build an scf "for" nest.
template<>
void doit (OpBuilder &b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >, ArrayRef< StringRef >)
Specialization to build affine "for" nest.
template<>
void doit (OpBuilder &b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions, ArrayRef< StringRef > distributionTypes)
Specialization to build an linalg.tiled_loop.
template<>
void doit (OpBuilder &b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions, ArrayRef< StringRef > distributionTypes)
Specialization for generating a mix of parallel and sequential scf loops.
Static Public Member Functions
static void doit (OpBuilder &b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >=None, ArrayRef< StringRef > distributionTypes={})
Detailed Description
template<typename LoopTy>
struct mlir::linalg::GenerateLoopNest< LoopTy >
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
bodyBuilderFn is used to generate the body of the innermost loop. It is passed a range of loop induction variables and a range of iterArgs.
Definition at line 281 of file Utils.h.
Member Function Documentation
doit() [1/5]
template<> void mlir::linalg::GenerateLoopNest< scf::ForOp >::doit (OpBuilder & b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions, ArrayRef< StringRef > distributionTypes)
Specialization to build an scf "for" nest.
Definition at line 220 of file Utils.cpp.
References mlir::scf::buildLoopNest(), mlir::linalg::Cyclic, mlir::detail::enumerate(), mlir::linalg::isParallelIteratorType(), mlir::scf::LoopNest::loops, mlir::mapLoopToProcessorIds(), and unpackRanges().
doit() [2/5]
template<> void mlir::linalg::GenerateLoopNest< AffineForOp >::doit (OpBuilder & b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > , ArrayRef< StringRef >)
Specialization to build affine "for" nest.
Definition at line 269 of file Utils.cpp.
References mlir::buildAffineLoopNest(), op, and unpackRanges().
doit() [3/5]
template<typename LoopTy> static void mlir::linalg::GenerateLoopNest< LoopTy >::doit (OpBuilder & b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > = None, ArrayRef< StringRef > distributionTypes = {}) static
Referenced by linalgOpToLoopsImpl(), and tileLinalgOpImpl().
doit() [4/5]
template<> void mlir::linalg::GenerateLoopNest< TiledLoopOp >::doit (OpBuilder & b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions, ArrayRef< StringRef > distributionTypes)
Specialization to build an linalg.tiled_loop.
Definition at line 298 of file Utils.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getArrayAttr(), loc, and unpackRanges().
doit() [5/5]
template<> void mlir::linalg::GenerateLoopNest< scf::ParallelOp >::doit (OpBuilder & b, Location loc, ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(OpBuilder &, Location, ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions, ArrayRef< StringRef > distributionTypes)
Specialization for generating a mix of parallel and sequential scf loops.
Definition at line 473 of file Utils.cpp.
References mlir::detail::enumerate(), mlir::linalg::generateParallelLoopNest(), mlir::linalg::isParallelIteratorType(), options, unpackRanges(), and mlir::linalg::updateBoundsForCyclicDistribution().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/Utils/Utils.h