MLIR: mlir::ComputationSliceState Struct Reference
mlir::ComputationSliceState Struct Reference
ComputationSliceState aggregates loop IVs, loop bound AffineMaps and their associated operands for a set of loops within a loop nest (typically the set of loops surrounding a store operation).
#include "mlir/Analysis/Utils.h"
Public Member Functions
LogicalResult getAsConstraints (FlatAffineConstraints *cst)
LogicalResult getSourceAsConstraints (FlatAffineConstraints &cst)
Adds to 'cst' constraints which represent the original loop bounds on 'ivs' in 'this'.
void clearBounds ()
bool isEmpty () const
Returns true if the computation slice is empty.
Optional< bool > isMaximal () const
Returns true if the computation slice encloses all the iterations of the sliced loop nest.
Optional< bool > isSliceValid ()
Checks the validity of the slice computed.
void dump () const
Public Attributes
SmallVector< Value, 4 > ivs
SmallVector< AffineMap, 4 > lbs
SmallVector< AffineMap, 4 > ubs
std::vector< SmallVector< Value, 4 > > lbOperands
std::vector< SmallVector< Value, 4 > > ubOperands
Block::iterator insertPoint
Detailed Description
ComputationSliceState aggregates loop IVs, loop bound AffineMaps and their associated operands for a set of loops within a loop nest (typically the set of loops surrounding a store operation).
Loop bound AffineMaps which are non-null represent slices of that loop's iteration space.
Definition at line 76 of file Utils.h.
Member Function Documentation
clearBounds()
void ComputationSliceState::clearBounds ()
Definition at line 118 of file Utils.cpp.
References lbOperands, lbs, ubOperands, and ubs.
Referenced by mlir::computeSliceUnion().
dump()
void ComputationSliceState::dump () const
Definition at line 125 of file Utils.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::detail::enumerate(), mlir::getForInductionVarOwner(), mlir::AffineMap::getNumResults(), mlir::AffineDimExpr::getPosition(), mlir::AffineMap::getResult(), mlir::AffineExpr::isa(), ivs, lbOperands, lbs, ubOperands, and ubs.
getAsConstraints()
LogicalResult ComputationSliceState::getAsConstraints (FlatAffineConstraints * cst)
Definition at line 82 of file Utils.cpp.
References mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::FlatAffineConstraints::containsId(), mlir::failed(), mlir::failure(), mlir::Value::getDefiningOp(), mlir::getForInductionVarOwner(), mlir::isValidSymbol(), ivs, lbOperands, lbs, mlir::FlatAffineConstraints::reset(), mlir::FlatAffineConstraints::setIdToConstant(), mlir::succeeded(), mlir::success(), ubs, and value.
Referenced by mlir::computeSliceUnion(), and isSliceValid().
getSourceAsConstraints()
LogicalResult ComputationSliceState::getSourceAsConstraints (FlatAffineConstraints & cst)
Adds to 'cst' constraints which represent the original loop bounds on 'ivs' in 'this'.
This corresponds to the original domain of the loop nest from which the slice is being computed. Returns failure if we cannot add loop bounds because of unsupported cases.
Definition at line 68 of file Utils.cpp.
References mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::failed(), mlir::failure(), mlir::getForInductionVarOwner(), ivs, mlir::FlatAffineConstraints::reset(), and mlir::success().
Referenced by isSliceValid().
isEmpty()
bool mlir::ComputationSliceState::isEmpty () const inline
Returns true if the computation slice is empty.
Definition at line 108 of file Utils.h.
References mlir::buildSliceTripCountMap(), mlir::computeSliceUnion(), mlir::getComputationSliceState(), mlir::getSliceIterationCount(), and mlir::insertBackwardComputationSlice().
Referenced by isFusionProfitable().
isMaximal()
Optional< bool > ComputationSliceState::isMaximal () const
Returns true if the computation slice encloses all the iterations of the sliced loop nest.
Returns false if it does not. Returns llvm::None if it cannot determine if the slice is maximal or not.
Definition at line 289 of file Utils.cpp.
References mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addDomainFromSliceMaps(), mlir::failed(), mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::PresburgerSet::isIntegerEmpty(), ivs, lbOperands, lbs, mlir::FlatAffineConstraints::reset(), mlir::PresburgerSet::subtract(), and ubs.
Referenced by mlir::createLoopFusionPass(), and mlir::getComputationSliceState().
isSliceValid()
Optional< bool > ComputationSliceState::isSliceValid ()
Checks the validity of the slice computed.
Returns true if it is deterministically verified that the original iteration space of the slice is contained within the new iteration space that is created after fusing 'this' slice into its destination.
This is done using the following steps:
Get the new domain of the slice that would be created if fusion succeeds. This domain gets constructed with source loop IVS and destination loop IVS as dimensions.
Project out the dimensions of the destination loop from the domain above calculated in step(1) to express it purely in terms of the source loop IVs.
Calculate a set difference between the iterations of the new domain and the original domain of the source loop. If this difference is empty, the slice is declared to be valid. Otherwise, return false as it implies that the effective fusion results in at least one iteration of the slice that was not originally in the source's domain. If the validity cannot be determined, returns llvm:None.
Definition at line 219 of file Utils.cpp.
References mlir::FlatAffineConstraints::dump(), mlir::failed(), getAsConstraints(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), getSourceAsConstraints(), mlir::PresburgerSet::isIntegerEmpty(), ivs, mlir::FlatAffineConstraints::projectOut(), and mlir::PresburgerSet::subtract().
Referenced by mlir::computeSliceUnion().
Member Data Documentation
insertPoint
Block::iterator mlir::ComputationSliceState::insertPoint
Definition at line 89 of file Utils.h.
Referenced by mlir::computeSliceUnion(), mlir::fuseLoops(), mlir::getComputationSliceState(), and mlir::getFusionComputeCost().
ivs
SmallVector<Value, 4> mlir::ComputationSliceState::ivs
Definition at line 79 of file Utils.h.
Referenced by mlir::buildSliceTripCountMap(), mlir::MemRefRegion::compute(), mlir::computeSliceUnion(), dump(), mlir::fuseLoops(), getAsConstraints(), mlir::getComputationSliceState(), getSourceAsConstraints(), isMaximal(), and isSliceValid().
lbOperands
std::vector<SmallVector<Value, 4> > mlir::ComputationSliceState::lbOperands
Definition at line 85 of file Utils.h.
Referenced by clearBounds(), mlir::MemRefRegion::compute(), mlir::computeSliceUnion(), dump(), mlir::fuseLoops(), getAsConstraints(), mlir::getComputationSliceState(), mlir::insertBackwardComputationSlice(), and isMaximal().
lbs
SmallVector<AffineMap, 4> mlir::ComputationSliceState::lbs
Definition at line 81 of file Utils.h.
Referenced by mlir::buildSliceTripCountMap(), clearBounds(), mlir::MemRefRegion::compute(), mlir::computeSliceUnion(), dump(), mlir::fuseLoops(), getAsConstraints(), mlir::getComputationSliceState(), mlir::MemRefRegion::getConstantBoundingSizeAndShape(), mlir::insertBackwardComputationSlice(), and isMaximal().
ubOperands
std::vector<SmallVector<Value, 4> > mlir::ComputationSliceState::ubOperands
Definition at line 87 of file Utils.h.
Referenced by clearBounds(), mlir::computeSliceUnion(), dump(), mlir::fuseLoops(), mlir::getComputationSliceState(), and mlir::insertBackwardComputationSlice().
ubs
SmallVector<AffineMap, 4> mlir::ComputationSliceState::ubs
Definition at line 83 of file Utils.h.
Referenced by mlir::buildSliceTripCountMap(), clearBounds(), mlir::MemRefRegion::compute(), mlir::computeSliceUnion(), dump(), mlir::fuseLoops(), getAsConstraints(), mlir::getComputationSliceState(), mlir::insertBackwardComputationSlice(), and isMaximal().
The documentation for this struct was generated from the following files:
include/mlir/Analysis/Utils.h
lib/Analysis/Utils.cpp