MLIR: mlir::xegpu::uArch::Xe2 Struct Reference
mlir::xegpu::uArch::Xe2 Struct Reference
#include "mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h"
Public Member Functions
Xe2 (Kind kind, llvm::ArrayRef< const Instruction * > instructionRegistry)
int getSubgroupSize () const override
unsigned getGeneralPackedFormatBitSize () const override
Public Member Functions inherited from mlir::xegpu::uArch::uArch
uArch (Kind kind, llvm::ArrayRef< const Instruction * > instructionRegistry)
virtual ~uArch ()=default
Kind getKind () const
const Instruction * getInstruction (InstructionKind instKind) const
bool isSupportedInstruction (InstructionKind instr) const
Static Public Member Functions
static bool classof (const uArch *u)
Additional Inherited Members
Public Types inherited from mlir::xegpu::uArch::uArch
enum class Kind {
Xe2_First , PVC = Xe2_First , BMG , Xe2_Last = BMG ,
Xe3_First , CRI = Xe3_First , Xe3_Last = CRI
}
Protected Attributes inherited from mlir::xegpu::uArch::uArch
Kind kind
llvm::SmallDenseMap< InstructionKind, const Instruction *, 32 > instructionRegistry
Detailed Description
Definition at line 24 of file IntelGpuXe2.h.
Constructor & Destructor Documentation
Xe2()
mlir::xegpu::uArch::Xe2::Xe2 (Kind kind, llvm::ArrayRef< const Instruction * > instructionRegistry) inline
Definition at line 25 of file IntelGpuXe2.h.
References mlir::xegpu::uArch::uArch::instructionRegistry, mlir::xegpu::uArch::uArch::kind, and mlir::xegpu::uArch::uArch::uArch().
Referenced by mlir::xegpu::uArch::BMGuArch::BMGuArch(), and mlir::xegpu::uArch::PVCuArch::PVCuArch().
Member Function Documentation
classof()
bool mlir::xegpu::uArch::Xe2::classof (const uArch * u) inline static
Definition at line 30 of file IntelGpuXe2.h.
References mlir::xegpu::uArch::uArch::getKind(), mlir::xegpu::uArch::uArch::uArch(), mlir::xegpu::uArch::uArch::Xe2_First, and mlir::xegpu::uArch::uArch::Xe2_Last.
getGeneralPackedFormatBitSize()
unsigned mlir::xegpu::uArch::Xe2::getGeneralPackedFormatBitSize () const inline override virtual
Implements mlir::xegpu::uArch::uArch.
Definition at line 28 of file IntelGpuXe2.h.
getSubgroupSize()
int mlir::xegpu::uArch::Xe2::getSubgroupSize () const inline override virtual
Implements mlir::xegpu::uArch::uArch.
Definition at line 27 of file IntelGpuXe2.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/XeGPU/uArch/IntelGpuXe2.h