MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< EncodingAttr >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction
static constexpr const char * pyClassName = "EncodingAttr"
static const MlirStringRef name
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< EncodingAttr >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< EncodingAttr >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< EncodingAttr >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Definition at line 43 of file DialectSparseTensor.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr::bindDerived (ClassTy & c) inline static
Definition at line 51 of file DialectSparseTensor.cpp.
References mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject::getContext(), mlirAffineMapIsNull(), mlirSparseTensorEncodingAttrBuildLvlType(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetCrdWidth(), mlirSparseTensorEncodingAttrGetDimToLvl(), mlirSparseTensorEncodingAttrGetExplicitVal(), mlirSparseTensorEncodingAttrGetImplicitVal(), mlirSparseTensorEncodingAttrGetLvlFmt(), mlirSparseTensorEncodingAttrGetLvlToDim(), mlirSparseTensorEncodingAttrGetLvlType(), mlirSparseTensorEncodingAttrGetPosWidth(), mlirSparseTensorEncodingAttrGetStructuredM(), mlirSparseTensorEncodingAttrGetStructuredN(), mlirSparseTensorEncodingGetLvlRank(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute::PyAttribute().
Member Data Documentation
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr::isaFunction static constexpr
Initial value:
=
      mlirAttributeIsASparseTensorEncodingAttr
Definition at line 44 of file DialectSparseTensor.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr::name inline static
Initial value:
=
      mlirSparseTensorEncodingAttrGetName()
Definition at line 47 of file DialectSparseTensor.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::sparse_tensor::EncodingAttr::pyClassName = "EncodingAttr" static constexpr
Definition at line 46 of file DialectSparseTensor.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectSparseTensor.cpp