MLIR: pybind11::detail::type_caster< MlirTypeID > Struct Reference
pybind11::detail::type_caster< MlirTypeID > Struct Reference
Casts object <-> MlirTypeID.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirTypeID, _("MlirTypeID"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirTypeID v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirTypeID.
Definition at line 279 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirTypeID >::cast (MlirTypeID v, return_value_policy , handle) inline static
Definition at line 286 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonTypeIDToCapsule().
load()
bool pybind11::detail::type_caster< MlirTypeID >::load (handle src, bool) inline
Definition at line 281 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirPythonCapsuleToTypeID(), and mlirTypeIDIsNull().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirTypeID >::PYBIND11_TYPE_CASTER (MlirTypeID , _("MlirTypeID"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h