MLIR: llvm::GraphTraits< const mlir::CallGraph * > Struct Reference
llvm::GraphTraits< const mlir::CallGraph * > Struct Reference
#include "mlir/Analysis/CallGraph.h"
Public Types
using nodes_iterator = mlir::CallGraph::iterator
Public Types inherited from llvm::GraphTraits< const mlir::CallGraphNode * >
using NodeRef = mlir::CallGraphNode *
using ChildIteratorType = mapped_iterator< mlir::CallGraphNode::iterator, decltype(&unwrap)>
Static Public Member Functions
static NodeRef getEntryNode (const mlir::CallGraph *cg)
The entry node into the graph is the external node.
static nodes_iterator nodes_begin (mlir::CallGraph *cg)
static nodes_iterator nodes_end (mlir::CallGraph *cg)
Static Public Member Functions inherited from llvm::GraphTraits< const mlir::CallGraphNode * >
static NodeRef getEntryNode (NodeRef node)
static NodeRef unwrap (const mlir::CallGraphNode::Edge &edge)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 253 of file CallGraph.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< const mlir::CallGraph * >::nodes_iterator = mlir::CallGraph::iterator
Definition at line 261 of file CallGraph.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< const mlir::CallGraph * >::getEntryNode (const mlir::CallGraph * cg) inline static
The entry node into the graph is the external node.
Definition at line 256 of file CallGraph.h.
References mlir::CallGraph::getExternalCallerNode().
nodes_begin()
static nodes_iterator llvm::GraphTraits< const mlir::CallGraph * >::nodes_begin (mlir::CallGraph * cg) inline static
Definition at line 262 of file CallGraph.h.
References mlir::CallGraph::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< const mlir::CallGraph * >::nodes_end (mlir::CallGraph * cg) inline static
Definition at line 263 of file CallGraph.h.
References mlir::CallGraph::end().
The documentation for this struct was generated from the following file:
include/mlir/Analysis/CallGraph.h