MLIR: mlir::OpToFuncCallLowering< SourceOp > Struct Template Reference
mlir::OpToFuncCallLowering< SourceOp > Struct Template Reference
Rewriting that replaces SourceOp with a CallOp to f32Func or f64Func or f32ApproxFunc or f16Func or i32Type depending on the element type and the fastMathFlag of that Op, if present.
#include "Conversion/GPUCommon/OpToFuncCallLowering.h"
Public Member Functions
OpToFuncCallLowering (const LLVMTypeConverter &lowering, StringRef f32Func, StringRef f64Func, StringRef f32ApproxFunc, StringRef f16Func, StringRef i32Func="", PatternBenefit benefit=1)
LogicalResult matchAndRewrite (SourceOp op, typename SourceOp::Adaptor adaptor, ConversionPatternRewriter &rewriter) const override
Methods that operate on the SourceOp type.
Value maybeCast (Value operand, PatternRewriter &rewriter) const
Type getFunctionType (Type resultType, ValueRange operands) const
LLVM::LLVMFuncOp appendOrGetFuncOp (StringRef funcName, Type funcType, Operation *op) const
StringRef getFunctionName (Type type, SourceOp op) const
Public Member Functions inherited from mlir::ConvertOpToLLVMPattern< SourceOp >
ConvertOpToLLVMPattern (const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< ValueRange > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
virtual LogicalResult matchAndRewrite (SourceOp op, OneToNOpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
Public Member Functions inherited from mlir::ConvertToLLVMPattern
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, const LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::ConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
const TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
template<typename ConverterTy >
std::enable_if_t< std::is_base_of< TypeConverter, ConverterTy >::value, const ConverterTy * > getTypeConverter () const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
std::optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
std::optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
std::optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Public Attributes
const std::string f32Func
const std::string f64Func
const std::string f32ApproxFunc
const std::string f16Func
const std::string i32Func
Additional Inherited Members
Public Types inherited from mlir::ConvertOpToLLVMPattern< SourceOp >
using OpAdaptor = typename SourceOp::Adaptor
using OneToNOpAdaptor = typename SourceOp::template GenericAdaptor< ArrayRef< ValueRange > >
Public Types inherited from mlir::ConversionPattern
using OpAdaptor = ArrayRef< Value >
using OneToNOpAdaptor = ArrayRef< ValueRange >
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::ConvertToLLVMPattern
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
const LLVMTypeConverter * getTypeConverter () const
Type getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Type getIntPtrType (unsigned addressSpace=0) const
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
Type getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
Type getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Type getPtrType (unsigned addressSpace=0) const
Get the MLIR type wrapping the LLVM ptr type.
Value getStridedElementPtr (ConversionPatternRewriter &rewriter, Location loc, MemRefType type, Value memRefDesc, ValueRange indices, LLVM::GEPNoWrapFlags noWrapFlags=LLVM::GEPNoWrapFlags::none) const
Convenience wrapper for the corresponding helper utility.
bool isConvertibleAndHasIdentityMaps (MemRefType type) const
Returns if the given memref type is convertible to LLVM and has an identity layout map.
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &strides, Value &size, bool sizeInBytes=true) const
Computes sizes, strides and buffer size of memRefType with identity layout.
Value getSizeInBytes (Location loc, Type type, ConversionPatternRewriter &rewriter) const
Computes the size of type in bytes.
Value getNumElements (Location loc, MemRefType memRefType, ValueRange dynamicSizes, ConversionPatternRewriter &rewriter) const
Computes total number of elements for the given MemRef and dynamicSizes.
MemRefDescriptor createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter &rewriter) const
Creates and populates a canonical memref descriptor struct.
LogicalResult copyUnrankedDescriptors (OpBuilder &builder, Location loc, TypeRange origTypes, SmallVectorImpl< Value > &operands, bool toDynamic) const
Copies the memory descriptor for any operands that were unranked descriptors originally to heap-allocated memory (if toDynamic is true) or to stack-allocated memory (otherwise).
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
See ConversionPattern::ConversionPattern for information on the other available constructors.
Protected Member Functions inherited from mlir::ConversionPattern
template<typename... Args>
ConversionPattern (const TypeConverter &typeConverter, Args &&...args)
Construct a conversion pattern with the given converter, and forward the remaining arguments to RewritePattern.
SmallVector< Value > getOneToOneAdaptorOperands (ArrayRef< ValueRange > operands) const
Given an array of value ranges, which are the inputs to a 1:N adaptor, try to extract the single value of each range to construct a the inputs for a 1:1 adaptor.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Static Protected Member Functions inherited from mlir::ConvertToLLVMPattern
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
Create a constant Op producing a value of resultType from an index-typed integer attribute.
Protected Attributes inherited from mlir::ConversionPattern
const TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
template<typename SourceOp>
struct mlir::OpToFuncCallLowering< SourceOp >
Rewriting that replaces SourceOp with a CallOp to f32Func or f64Func or f32ApproxFunc or f16Func or i32Type depending on the element type and the fastMathFlag of that Op, if present.
The function declaration is added in case it was not added before.
If the input values are of bf16 type (or f16 type if f16Func is empty), the value is first casted to f32, the function called and then the result casted back.
Example with NVVM: exp_f32 = math.exp arg_f32 : f32
will be transformed into llvm.call @__nv_expf(arg_f32) : (f32) -> f32
If the fastMathFlag attribute of SourceOp is afn or fast, this Op lowers to the approximate calculation function.
Also example with NVVM: exp_f32 = math.exp arg_f32 fastmath<afn> : f32
will be transformed into llvm.call @__nv_fast_expf(arg_f32) : (f32) -> f32
Final example with NVVM: pow_f32 = math.fpowi arg_f32, arg_i32
will be transformed into llvm.call @__nv_powif(arg_f32, arg_i32) : (f32, i32) -> f32
Definition at line 55 of file OpToFuncCallLowering.h.
Constructor & Destructor Documentation
OpToFuncCallLowering()
template<typename SourceOp > mlir::OpToFuncCallLowering< SourceOp >::OpToFuncCallLowering (const LLVMTypeConverter & lowering, StringRef f32Func, StringRef f64Func, StringRef f32ApproxFunc, StringRef f16Func, StringRef i32Func = "", PatternBenefit benefit = 1) inline explicit
Definition at line 57 of file OpToFuncCallLowering.h.
Member Function Documentation
appendOrGetFuncOp()
template<typename SourceOp > LLVM::LLVMFuncOp mlir::OpToFuncCallLowering< SourceOp >::appendOrGetFuncOp (StringRef funcName, Type funcType, Operation * op) const inline
Definition at line 156 of file OpToFuncCallLowering.h.
References mlir::LocationAttr::findInstanceOfOrUnknown(), mlir::get(), mlir::Operation::getContext(), mlir::Operation::getLoc(), and mlir::Operation::getParentOfType().
Referenced by mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite().
getFunctionName()
template<typename SourceOp > StringRef mlir::OpToFuncCallLowering< SourceOp >::getFunctionName (Type type, SourceOp op) const inline
Definition at line 177 of file OpToFuncCallLowering.h.
References mlir::OpToFuncCallLowering< SourceOp >::f16Func, mlir::OpToFuncCallLowering< SourceOp >::f32ApproxFunc, mlir::OpToFuncCallLowering< SourceOp >::f32Func, mlir::OpToFuncCallLowering< SourceOp >::f64Func, mlir::OpToFuncCallLowering< SourceOp >::i32Func, and mlir::Type::isInteger().
Referenced by mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite().
getFunctionType()
template<typename SourceOp > Type mlir::OpToFuncCallLowering< SourceOp >::getFunctionType (Type resultType, ValueRange operands) const inline
Definition at line 151 of file OpToFuncCallLowering.h.
References mlir::get(), and mlir::ValueRange::getTypes().
Referenced by mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite().
matchAndRewrite()
template<typename SourceOp > LogicalResult mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite (SourceOp op, typename SourceOp::Adaptor adaptor, ConversionPatternRewriter & rewriter) const inline override virtual
Methods that operate on the SourceOp type.
One of these must be overridden by the derived pattern class.
Reimplemented from mlir::ConvertOpToLLVMPattern< SourceOp >.
Definition at line 67 of file OpToFuncCallLowering.h.
References mlir::OpToFuncCallLowering< SourceOp >::appendOrGetFuncOp(), mlir::OpToFuncCallLowering< SourceOp >::getFunctionName(), mlir::OpToFuncCallLowering< SourceOp >::getFunctionType(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getIntegerType(), mlir::Builder::getType(), mlir::OpToFuncCallLowering< SourceOp >::maybeCast(), mlir::RewriterBase::notifyMatchFailure(), and mlir::ConversionPatternRewriter::replaceOp().
maybeCast()
template<typename SourceOp > Value mlir::OpToFuncCallLowering< SourceOp >::maybeCast (Value operand, PatternRewriter & rewriter) const inline
Definition at line 137 of file OpToFuncCallLowering.h.
References mlir::OpToFuncCallLowering< SourceOp >::f16Func, mlir::get(), mlir::Builder::getContext(), mlir::Value::getLoc(), and mlir::Value::getType().
Referenced by mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite().
Member Data Documentation
f16Func
template<typename SourceOp > const std::string mlir::OpToFuncCallLowering< SourceOp >::f16Func
Definition at line 203 of file OpToFuncCallLowering.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::getFunctionName(), and mlir::OpToFuncCallLowering< SourceOp >::maybeCast().
f32ApproxFunc
template<typename SourceOp > const std::string mlir::OpToFuncCallLowering< SourceOp >::f32ApproxFunc
Definition at line 202 of file OpToFuncCallLowering.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::getFunctionName().
f32Func
template<typename SourceOp > const std::string mlir::OpToFuncCallLowering< SourceOp >::f32Func
Definition at line 200 of file OpToFuncCallLowering.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::getFunctionName().
f64Func
template<typename SourceOp > const std::string mlir::OpToFuncCallLowering< SourceOp >::f64Func
Definition at line 201 of file OpToFuncCallLowering.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::getFunctionName().
i32Func
template<typename SourceOp > const std::string mlir::OpToFuncCallLowering< SourceOp >::i32Func
Definition at line 204 of file OpToFuncCallLowering.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::getFunctionName().
The documentation for this struct was generated from the following file:
lib/Conversion/GPUCommon/OpToFuncCallLowering.h