MLIR: mlir::tracing::ActionActiveStack Struct Reference
mlir::tracing::ActionActiveStack Struct Reference
This class is used to keep track of the active actions in the stack.
#include "mlir/Debug/ExecutionContext.h"
Public Member Functions
ActionActiveStack (const ActionActiveStack *parent, const Action &action, int depth)
const ActionActiveStack * getParent () const
const Action & getAction () const
int getDepth () const
void print (raw_ostream &os, bool withContext) const
void dump () const
Breakpoint * getBreakpoint () const
void setBreakpoint (Breakpoint *breakpoint)
Detailed Description
This class is used to keep track of the active actions in the stack.
It provides the current action but also access to the parent entry in the stack. This allows to keep track of the nested nature in which actions may be executed.
Definition at line 23 of file ExecutionContext.h.
Constructor & Destructor Documentation
ActionActiveStack()
mlir::tracing::ActionActiveStack::ActionActiveStack (const ActionActiveStack * parent, const Action & action, int depth) inline
Definition at line 25 of file ExecutionContext.h.
References ActionActiveStack().
Referenced by ActionActiveStack(), getParent(), and print().
Member Function Documentation
dump()
void mlir::tracing::ActionActiveStack::dump () const inline
Definition at line 32 of file ExecutionContext.h.
References print().
getAction()
const Action & mlir::tracing::ActionActiveStack::getAction () const inline
Definition at line 29 of file ExecutionContext.h.
Referenced by mlir::tracing::ActionLogger::afterExecute(), mlir::tracing::ActionLogger::beforeExecute(), and mlirDebuggerPrintContext().
getBreakpoint()
Breakpoint * mlir::tracing::ActionActiveStack::getBreakpoint () const inline
Definition at line 36 of file ExecutionContext.h.
getDepth()
int mlir::tracing::ActionActiveStack::getDepth () const inline
Definition at line 30 of file ExecutionContext.h.
Referenced by print().
getParent()
const ActionActiveStack * mlir::tracing::ActionActiveStack::getParent () const inline
Definition at line 28 of file ExecutionContext.h.
References ActionActiveStack().
Referenced by mlir::tracing::ExecutionContext::operator()().
print()
void ActionActiveStack::print (raw_ostream & os, bool withContext) const
Definition at line 21 of file ExecutionContext.cpp.
References ActionActiveStack(), mlir::tracing::Action::getContextIRUnits(), getDepth(), and mlir::tracing::Action::print().
Referenced by dump(), and mlirDebuggerPrintActionBacktrace().
setBreakpoint()
void mlir::tracing::ActionActiveStack::setBreakpoint (Breakpoint * breakpoint) inline
Definition at line 37 of file ExecutionContext.h.
Referenced by mlir::tracing::ExecutionContext::operator()().
The documentation for this struct was generated from the following files:
include/mlir/Debug/ExecutionContext.h
lib/Debug/ExecutionContext.cpp