MLIR: mlir::amdgpu::AmdgpuFoldMemRefOpsPass Struct Reference
mlir::amdgpu::AmdgpuFoldMemRefOpsPass Struct Reference final
Public Member Functions
void runOnOperation () override
Detailed Description
Definition at line 22 of file FoldMemRefsOps.cpp.
Member Function Documentation
runOnOperation()
void mlir::amdgpu::AmdgpuFoldMemRefOpsPass::runOnOperation () inline override
Definition at line 24 of file FoldMemRefsOps.cpp.
References getContext(), mlir::patterns, mlir::amdgpu::populateAmdgpuFoldMemRefOpsPatterns(), and mlir::walkAndApplyPatterns().
The documentation for this struct was generated from the following file:
lib/Dialect/AMDGPU/Transforms/FoldMemRefsOps.cpp