MLIR: pybind11::detail::type_caster< MlirType > Struct Reference
pybind11::detail::type_caster< MlirType > Struct Reference
Casts object <-> MlirType.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirType, _("MlirType"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirType t, return_value_policy, handle)
Detailed Description
Casts object <-> MlirType.
Definition at line 300 of file PybindAdaptors.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< MlirType >::cast (MlirType t, return_value_policy , handle) inline static
Definition at line 307 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_MAYBE_DOWNCAST_ATTR, and mlirPythonTypeToCapsule().
load()
bool pybind11::detail::type_caster< MlirType >::load (handle src, bool) inline
Definition at line 302 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), mlirPythonCapsuleToType(), and mlirTypeIsNull().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirType >::PYBIND11_TYPE_CASTER (MlirType , _("MlirType"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h