MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedType, QuantizedType >
static MlirType castFrom (PyType &orig)
static void bind (nanobind::module_ &m)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirTypeIsAUniformQuantizedType
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "UniformQuantizedType"
static const MlirStringRef name = mlirUniformQuantizedTypeGetName()
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedType, QuantizedType >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedType, QuantizedType >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteType< UniformQuantizedType, QuantizedType >
PyConcreteType ()=default
Detailed Description
Definition at line 226 of file DialectQuant.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType::bindDerived (ClassTy & c) inline static
Definition at line 235 of file DialectQuant.cpp.
References mlirUniformQuantizedTypeGet(), mlirUniformQuantizedTypeGetScale(), mlirUniformQuantizedTypeGetZeroPoint(), and mlirUniformQuantizedTypeIsFixedPoint().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType::getTypeIdFunction static constexpr
Initial value:
=
      mlirUniformQuantizedTypeGetTypeID
Definition at line 229 of file DialectQuant.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType::isaFunction = mlirTypeIsAUniformQuantizedType static constexpr
Definition at line 228 of file DialectQuant.cpp.
name
const MlirStringRef mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType::name = mlirUniformQuantizedTypeGetName() inline static
Definition at line 232 of file DialectQuant.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::quant::UniformQuantizedType::pyClassName = "UniformQuantizedType" static constexpr
Definition at line 231 of file DialectQuant.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectQuant.cpp