MLIR: llvm::GraphTraits< Block * > Struct Template Reference
llvm::GraphTraits< Block * > Struct Template Reference
Public Types
using GraphType = Block *
using NodeRef = Operation *
using ChildIteratorType = Operation::user_iterator
using nodes_iterator = mapped_iterator< Block::iterator, decltype(&AddressOf)>
Static Public Member Functions
static ChildIteratorType child_begin (NodeRef n)
static ChildIteratorType child_end (NodeRef n)
static Operation * AddressOf (Operation &op)
static nodes_iterator nodes_begin (Block *b)
static nodes_iterator nodes_end (Block *b)
Detailed Description
template<>
struct llvm::GraphTraits< Block * >
Definition at line 30 of file ViewOpGraph.cpp.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< Block * >::ChildIteratorType = Operation::user_iterator
Definition at line 34 of file ViewOpGraph.cpp.
GraphType
using llvm::GraphTraits< Block * >::GraphType = Block *
Definition at line 31 of file ViewOpGraph.cpp.
NodeRef
using llvm::GraphTraits< Block * >::NodeRef = Operation *
Definition at line 32 of file ViewOpGraph.cpp.
nodes_iterator
using llvm::GraphTraits< Block * >::nodes_iterator = mapped_iterator<Block::iterator, decltype(&AddressOf)>
Definition at line 41 of file ViewOpGraph.cpp.
Member Function Documentation
AddressOf()
static Operation* llvm::GraphTraits< Block * >::AddressOf (Operation & op) inline static
Definition at line 40 of file ViewOpGraph.cpp.
References op.
child_begin()
static ChildIteratorType llvm::GraphTraits< Block * >::child_begin (NodeRef n) inline static
Definition at line 35 of file ViewOpGraph.cpp.
References mlir::Operation::user_begin().
child_end()
static ChildIteratorType llvm::GraphTraits< Block * >::child_end (NodeRef n) inline static
Definition at line 36 of file ViewOpGraph.cpp.
References mlir::Operation::user_end().
nodes_begin()
static nodes_iterator llvm::GraphTraits< Block * >::nodes_begin (Block * b) inline static
Definition at line 42 of file ViewOpGraph.cpp.
References mlir::Block::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< Block * >::nodes_end (Block * b) inline static
Definition at line 45 of file ViewOpGraph.cpp.
References mlir::Block::end().
The documentation for this struct was generated from the following file:
lib/Transforms/ViewOpGraph.cpp