MLIR: mlir::LatticeAnchor Struct Reference
mlir::LatticeAnchor Struct Reference
Fundamental IR components are supported as first-class lattice anchor.
#include "mlir/Analysis/DataFlowFramework.h"
Public Types
using ParentTy = PointerUnion< GenericLatticeAnchor *, ProgramPoint *, Value >
Public Member Functions
LatticeAnchor (ParentTy point=nullptr)
Allow implicit conversion from the parent type.
void print (raw_ostream &os) const
Print the lattice anchor.
Location getLoc () const
Get the source location of the lattice anchor.
Detailed Description
Fundamental IR components are supported as first-class lattice anchor.
Definition at line 251 of file DataFlowFramework.h.
Member Typedef Documentation
ParentTy
using mlir::LatticeAnchor::ParentTy = PointerUnion<GenericLatticeAnchor *, ProgramPoint *, Value>
Definition at line 253 of file DataFlowFramework.h.
Constructor & Destructor Documentation
LatticeAnchor()
mlir::LatticeAnchor::LatticeAnchor (ParentTy point = nullptr) inline
Allow implicit conversion from the parent type.
Definition at line 257 of file DataFlowFramework.h.
Member Function Documentation
getLoc()
Location LatticeAnchor::getLoc () const
Get the source location of the lattice anchor.
Definition at line 90 of file DataFlowFramework.cpp.
References mlir::ProgramPoint::getBlock(), mlir::Operation::getLoc(), mlir::Region::getLoc(), getLoc(), mlir::Block::getParent(), mlir::ProgramPoint::getPrevOp(), and mlir::ProgramPoint::isBlockStart().
Referenced by getLoc().
print()
void LatticeAnchor::print (raw_ostream & os) const
Print the lattice anchor.
Definition at line 76 of file DataFlowFramework.cpp.
References print().
Referenced by mlir::operator<<(), and print().
The documentation for this struct was generated from the following files:
include/mlir/Analysis/DataFlowFramework.h
lib/Analysis/DataFlowFramework.cpp