MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap Struct Reference
#include "mlir/Bindings/Python/IRCore.h"
Static Public Member Functions
static bool dunderContains (const std::string &attributeKind)
static nanobind::callable dunderGetItemNamed (const std::string &attributeKind)
static void dunderSetItemNamed (const std::string &attributeKind, nanobind::callable func, bool replace, bool allow_existing)
static void bind (nanobind::module_ &m)
Detailed Description
Definition at line 1496 of file IRCore.h.
Member Function Documentation
bind()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap::bind (nanobind::module_ & m) static
Definition at line 165 of file IRCore.cpp.
References dunderContains(), dunderGetItemNamed(), and dunderSetItemNamed().
Referenced by mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::populateIRCore().
dunderContains()
bool mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap::dunderContains (const std::string & attributeKind) static
Definition at line 146 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::lookupAttributeBuilder().
Referenced by bind().
dunderGetItemNamed()
nb::callable mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap::dunderGetItemNamed (const std::string & attributeKind) static
Definition at line 151 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::lookupAttributeBuilder().
Referenced by bind().
dunderSetItemNamed()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttrBuilderMap::dunderSetItemNamed (const std::string & attributeKind, nanobind::callable func, bool replace, bool allow_existing) static
Definition at line 158 of file IRCore.cpp.
References mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::get(), and mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyGlobals::registerAttributeBuilder().
Referenced by bind().
The documentation for this struct was generated from the following files:
include/mlir/Bindings/Python/IRCore.h
lib/Bindings/Python/IRCore.cpp