MLIR: mlir::vector::UnrollVectorOptions Struct Reference
mlir::vector::UnrollVectorOptions Struct Reference
Options that control the vector unrolling.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintFnType = std::function< LogicalResult(Operation *op)>
using NativeShapeFnType = std::function< Optional< SmallVector< int64_t, 4 > >(Operation *op)>
Public Member Functions
UnrollVectorOptions & setFilterConstraint (FilterConstraintFnType constraint)
UnrollVectorOptions & setNativeShapeFn (NativeShapeFnType fn)
UnrollVectorOptions & setNativeShape (ArrayRef< int64_t > shape)
Set the native shape to use for unrolling.
Public Attributes
FilterConstraintFnType filterConstraint = nullptr
Callback function that indicates whether vector unrolling should be attempted on the operation.
NativeShapeFnType nativeShape = nullptr
Function that returns the shape of the vector to unroll to for a given operation.
Detailed Description
Options that control the vector unrolling.
Definition at line 37 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintFnType
using mlir::vector::UnrollVectorOptions::FilterConstraintFnType = std::function<LogicalResult(Operation *op)>
Definition at line 38 of file VectorTransforms.h.
NativeShapeFnType
using mlir::vector::UnrollVectorOptions::NativeShapeFnType = std::function<Optional<SmallVector<int64_t, 4> >(Operation *op)>
Definition at line 48 of file VectorTransforms.h.
Member Function Documentation
setFilterConstraint()
UnrollVectorOptions& mlir::vector::UnrollVectorOptions::setFilterConstraint (FilterConstraintFnType constraint) inline
Definition at line 42 of file VectorTransforms.h.
setNativeShape()
UnrollVectorOptions& mlir::vector::UnrollVectorOptions::setNativeShape (ArrayRef< int64_t > shape) inline
Set the native shape to use for unrolling.
Definition at line 58 of file VectorTransforms.h.
References options, mlir::vector::populateVectorUnrollPatterns(), mlir::vector::splitFullAndPartialTransfer(), and mlir::vector::splitFullAndPartialTransferPrecondition().
setNativeShapeFn()
UnrollVectorOptions& mlir::vector::UnrollVectorOptions::setNativeShapeFn (NativeShapeFnType fn) inline
Definition at line 52 of file VectorTransforms.h.
Member Data Documentation
filterConstraint
FilterConstraintFnType mlir::vector::UnrollVectorOptions::filterConstraint = nullptr
Callback function that indicates whether vector unrolling should be attempted on the operation.
Definition at line 41 of file VectorTransforms.h.
Referenced by getTargetShape().
nativeShape
NativeShapeFnType mlir::vector::UnrollVectorOptions::nativeShape = nullptr
Function that returns the shape of the vector to unroll to for a given operation.
The unrolling is aborted if the function returns llvm::None.
Definition at line 51 of file VectorTransforms.h.
Referenced by getTargetShape().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Vector/VectorTransforms.h