MLIR: mlir::vector::LowerVectorsOptions Struct Reference
mlir::vector::LowerVectorsOptions Struct Reference
Helper structure used to hold the different options of LowerVectorsOp.
#include "mlir/Dialect/Vector/TransformOps/VectorTransformOps.h"
Public Member Functions
LowerVectorsOptions ()
LowerVectorsOptions & setTransposeAVX2Lowering (bool opt)
LowerVectorsOptions & setUnrollVectorTransfers (bool opt)
LowerVectorsOptions & setVectorTransformsOptions (VectorContractLowering opt)
Duplicate the base API of VectorTransformsOptions but return the LowerVectorsOptions type.
LowerVectorsOptions & setVectorMultiReductionLowering (VectorMultiReductionLowering opt)
LowerVectorsOptions & setVectorTransposeLowering (VectorTransposeLowering opt)
LowerVectorsOptions & setVectorTransferSplit (VectorTransferSplit opt)
Public Member Functions inherited from mlir::vector::VectorTransformsOptions
VectorTransformsOptions & setVectorTransformsOptions (VectorContractLowering opt)
VectorTransformsOptions & setVectorMultiReductionLowering (VectorMultiReductionLowering opt)
VectorTransformsOptions & setVectorTransposeLowering (VectorTransposeLowering opt)
VectorTransformsOptions & setVectorTransferSplit (VectorTransferSplit opt)
Public Attributes
bool transposeAVX2Lowering = false
bool unrollVectorTransfers = true
Public Attributes inherited from mlir::vector::VectorTransformsOptions
VectorContractLowering vectorContractLowering = VectorContractLowering::Dot
Option to control the lowering of vector.contract.
VectorMultiReductionLowering vectorMultiReductionLowering
Option to control the lowering of vector.multi_reduction.
VectorTransposeLowering vectorTransposeLowering
Option to control the lowering of vector.transpose.
VectorTransferSplit vectorTransferSplit = VectorTransferSplit::None
Option to control the splitting of vector transfers.
Detailed Description
Helper structure used to hold the different options of LowerVectorsOp.
Definition at line 38 of file VectorTransformOps.h.
Constructor & Destructor Documentation
LowerVectorsOptions()
mlir::vector::LowerVectorsOptions::LowerVectorsOptions () inline
Definition at line 40 of file VectorTransformOps.h.
References setVectorMultiReductionLowering(), setVectorTransferSplit(), setVectorTransformsOptions(), and setVectorTransposeLowering().
Referenced by setTransposeAVX2Lowering(), setUnrollVectorTransfers(), setVectorTransferSplit(), setVectorTransformsOptions(), and setVectorTransposeLowering().
Member Function Documentation
setTransposeAVX2Lowering()
LowerVectorsOptions & mlir::vector::LowerVectorsOptions::setTransposeAVX2Lowering (bool opt) inline
Definition at line 72 of file VectorTransformOps.h.
References LowerVectorsOptions(), and transposeAVX2Lowering.
setUnrollVectorTransfers()
LowerVectorsOptions & mlir::vector::LowerVectorsOptions::setUnrollVectorTransfers (bool opt) inline
Definition at line 78 of file VectorTransformOps.h.
References LowerVectorsOptions(), and unrollVectorTransfers.
setVectorMultiReductionLowering()
LowerVectorsOptions & mlir::vector::LowerVectorsOptions::setVectorMultiReductionLowering (VectorMultiReductionLowering opt) inline
Definition at line 57 of file VectorTransformOps.h.
References mlir::vector::VectorTransformsOptions::setVectorMultiReductionLowering().
Referenced by LowerVectorsOptions().
setVectorTransferSplit()
LowerVectorsOptions & mlir::vector::LowerVectorsOptions::setVectorTransferSplit (VectorTransferSplit opt) inline
Definition at line 65 of file VectorTransformOps.h.
References LowerVectorsOptions(), and mlir::vector::VectorTransformsOptions::setVectorTransferSplit().
Referenced by LowerVectorsOptions().
setVectorTransformsOptions()
LowerVectorsOptions & mlir::vector::LowerVectorsOptions::setVectorTransformsOptions (VectorContractLowering opt) inline
Duplicate the base API of VectorTransformsOptions but return the LowerVectorsOptions type.
This allows to really set up the different options in any order via chained setXXX calls.
Definition at line 51 of file VectorTransformOps.h.
References LowerVectorsOptions(), and mlir::vector::VectorTransformsOptions::setVectorTransformsOptions().
Referenced by LowerVectorsOptions().
setVectorTransposeLowering()
LowerVectorsOptions & mlir::vector::LowerVectorsOptions::setVectorTransposeLowering (VectorTransposeLowering opt) inline
Definition at line 61 of file VectorTransformOps.h.
References LowerVectorsOptions(), and mlir::vector::VectorTransformsOptions::setVectorTransposeLowering().
Referenced by LowerVectorsOptions().
Member Data Documentation
transposeAVX2Lowering
bool mlir::vector::LowerVectorsOptions::transposeAVX2Lowering = false
Definition at line 71 of file VectorTransformOps.h.
Referenced by setTransposeAVX2Lowering().
unrollVectorTransfers
bool mlir::vector::LowerVectorsOptions::unrollVectorTransfers = true
Definition at line 77 of file VectorTransformOps.h.
Referenced by setUnrollVectorTransfers().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Vector/TransformOps/VectorTransformOps.h