MLIR: MlirExternalPassCallbacks Struct Reference
MlirExternalPassCallbacks Struct Reference
Structure of external MlirPass callbacks.
#include "mlir-c/Pass.h"
Public Attributes
void(* construct)(void *userData)
This callback is called from the pass is created.
void(* destruct)(void *userData)
This callback is called when the pass is destroyed This is analogous to a C++ pass destructor.
MlirLogicalResult(* initialize)(MlirContext ctx, void *userData)
This callback is optional.
void *(* clone)(void *userData)
This callback is called when the pass is cloned.
void(* run)(MlirOperation op, MlirExternalPass pass, void *userData)
This callback is called when the pass is run.
Detailed Description
Structure of external MlirPass callbacks.
All callbacks are required to be set unless otherwise specified.
Definition at line 153 of file Pass.h.
Member Data Documentation
clone
void*(* MlirExternalPassCallbacks::clone) (void *userData)
This callback is called when the pass is cloned.
See Pass::clonePass().
Definition at line 170 of file Pass.h.
Referenced by mlir::ExternalPass::clonePass().
construct
void(* MlirExternalPassCallbacks::construct) (void *userData)
This callback is called from the pass is created.
This is analogous to a C++ pass constructor.
Definition at line 156 of file Pass.h.
Referenced by mlir::ExternalPass::ExternalPass().
destruct
void(* MlirExternalPassCallbacks::destruct) (void *userData)
This callback is called when the pass is destroyed This is analogous to a C++ pass destructor.
Definition at line 160 of file Pass.h.
Referenced by mlir::ExternalPass::~ExternalPass().
initialize
MlirLogicalResult(* MlirExternalPassCallbacks::initialize) (MlirContext ctx, void *userData)
This callback is optional.
The callback is called before the pass is run, allowing a chance to initialize any complex state necessary for running the pass. See Pass::initialize(MLIRContext *).
Definition at line 166 of file Pass.h.
Referenced by mlir::ExternalPass::initialize().
run
void(* MlirExternalPassCallbacks::run) (MlirOperation op, MlirExternalPass pass, void *userData)
This callback is called when the pass is run.
See Pass::runOnOperation().
Definition at line 174 of file Pass.h.
Referenced by mlir::ExternalPass::runOnOperation().
The documentation for this struct was generated from the following file:
include/mlir-c/Pass.h