MLIR: mlir::query::MatchQuery Struct Reference
mlir::query::MatchQuery Struct Reference
#include "mlir/Query/Query.h"
Public Member Functions
MatchQuery (llvm::StringRef source, const matcher::DynMatcher &matcher)
llvm::LogicalResult run (llvm::raw_ostream &os, QuerySession &qs) const override
Public Member Functions inherited from mlir::query::Query
Query (QueryKind kind)
virtual ~Query ()
Static Public Member Functions
static bool classof (const Query *query)
Public Attributes
const matcher::DynMatcher matcher
llvm::StringRef source
Public Attributes inherited from mlir::query::Query
llvm::StringRef remainingContent
const QueryKind kind
Detailed Description
Definition at line 91 of file Query.h.
Constructor & Destructor Documentation
MatchQuery()
mlir::query::MatchQuery::MatchQuery (llvm::StringRef source, const matcher::DynMatcher & matcher) inline
Definition at line 92 of file Query.h.
References mlir::query::Match, matcher, mlir::query::Query::Query(), and source.
Member Function Documentation
classof()
bool mlir::query::MatchQuery::classof (const Query * query) inline static
Definition at line 101 of file Query.h.
References mlir::query::Match, and mlir::query::Query::Query().
run()
LogicalResult mlir::query::MatchQuery::run (llvm::raw_ostream & os, QuerySession & qs) const override virtual
Implements mlir::query::Query.
Definition at line 120 of file Query.cpp.
References mlir::query::matcher::MatchFinder::collectMatches(), mlir::Operation::erase(), mlir::query::extractFunction(), mlir::query::matcher::MatchFinder::flattenMatchedOps(), mlir::Operation::getContext(), mlir::query::QuerySession::getRootOp(), matcher, mlir::query::matcher::MatchFinder::printMatch(), and mlir::verify().
Member Data Documentation
matcher
const matcher::DynMatcher mlir::query::MatchQuery::matcher
Definition at line 97 of file Query.h.
Referenced by MatchQuery(), and run().
source
llvm::StringRef mlir::query::MatchQuery::source
Definition at line 99 of file Query.h.
Referenced by MatchQuery().
The documentation for this struct was generated from the following files:
include/mlir/Query/Query.h
lib/Query/Query.cpp