MLIR: nanobind::detail::type_caster< MlirPassManager > Struct Reference
nanobind::detail::type_caster< MlirPassManager > Struct Reference
Casts object -> MlirPassManager.
#include "mlir/Bindings/Python/NanobindAdaptors.h"
Public Member Functions
bool from_python (handle src, uint8_t flags, cleanup_list *cleanup) noexcept
Detailed Description
Casts object -> MlirPassManager.
Definition at line 287 of file NanobindAdaptors.h.
Member Function Documentation
from_python()
bool nanobind::detail::type_caster< MlirPassManager >::from_python (handle src, uint8_t flags, cleanup_list * cleanup) inline noexcept
Definition at line 289 of file NanobindAdaptors.h.
References nanobind::detail::mlirApiObjectToCapsule(), mlirPassManagerIsNull(), and mlirPythonCapsuleToPassManager().
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/NanobindAdaptors.h