MLIR: PyAttrBuilderMap Struct Reference
PyAttrBuilderMap Struct Reference
Static Public Member Functions
static bool dunderContains (const std::string &attributeKind)
static nb::callable dunderGetItemNamed (const std::string &attributeKind)
static void dunderSetItemNamed (const std::string &attributeKind, nb::callable func, bool replace)
static void bind (nb::module_ &m)
Detailed Description
Definition at line 159 of file IRCore.cpp.
Member Function Documentation
bind()
void PyAttrBuilderMap::bind (nb::module_ & m) inline static
Definition at line 175 of file IRCore.cpp.
References dunderContains(), dunderGetItemNamed(), and dunderSetItemNamed().
dunderContains()
bool PyAttrBuilderMap::dunderContains (const std::string & attributeKind) inline static
Definition at line 160 of file IRCore.cpp.
References mlir::python::PyGlobals::get(), and mlir::python::PyGlobals::lookupAttributeBuilder().
Referenced by bind().
dunderGetItemNamed()
nb::callable PyAttrBuilderMap::dunderGetItemNamed (const std::string & attributeKind) inline static
Definition at line 163 of file IRCore.cpp.
References mlir::python::PyGlobals::get(), and mlir::python::PyGlobals::lookupAttributeBuilder().
Referenced by bind().
dunderSetItemNamed()
void PyAttrBuilderMap::dunderSetItemNamed (const std::string & attributeKind, nb::callable func, bool replace) inline static
Definition at line 169 of file IRCore.cpp.
References mlir::python::PyGlobals::get(), and mlir::python::PyGlobals::registerAttributeBuilder().
Referenced by bind().
The documentation for this struct was generated from the following file:
lib/Bindings/Python/IRCore.cpp