MLIR: mlir::OperationConverter Struct Reference
mlir::OperationConverter Struct Reference
Public Member Functions
OperationConverter (MLIRContext *ctx, const ConversionTarget &target, const FrozenRewritePatternSet &patterns, const ConversionConfig &config, OpConversionMode mode)
LogicalResult applyConversion (ArrayRef< Operation * > ops)
Applies the conversion to the given operations (and their nested operations).
template<typename Fn>
LogicalResult legalizeOperations (ArrayRef< Operation * > ops, Fn onFailure, bool isRecursiveLegalization=false)
Legalizes the given operations (and their nested operations) to the conversion target.
LogicalResult legalizeOperations (ArrayRef< Operation * > ops, bool isRecursiveLegalization=false)
LogicalResult convert (Operation *op, bool isRecursiveLegalization=false)
Converts a single operation.
const ConversionTarget & getTarget ()
Detailed Description
Definition at line 3264 of file DialectConversion.cpp.
Constructor & Destructor Documentation
OperationConverter()
mlir::OperationConverter::OperationConverter (MLIRContext * ctx, const ConversionTarget & target, const FrozenRewritePatternSet & patterns, const ConversionConfig & config, OpConversionMode mode) inline explicit
Definition at line 3265 of file DialectConversion.cpp.
References target.
Member Function Documentation
applyConversion()
LogicalResult OperationConverter::applyConversion (ArrayRef< Operation * > ops)
Applies the conversion to the given operations (and their nested operations).
Definition at line 3463 of file DialectConversion.cpp.
References mlir::detail::ConversionPatternRewriterImpl::applyRewrites(), mlir::detail::ConversionPatternRewriterImpl::config, kPureTypeConversionMarker, legalizeOperations(), legalizeUnresolvedMaterialization(), mlir::reconcileUnrealizedCasts(), mlir::detail::ConversionPatternRewriterImpl::rewriter, success(), mlir::detail::ConversionPatternRewriterImpl::undoRewrites(), and mlir::detail::ConversionPatternRewriterImpl::unresolvedMaterializations.
Referenced by applyConversion().
convert()
LogicalResult OperationConverter::convert (Operation * op, bool isRecursiveLegalization = false)
Converts a single operation.
If isRecursiveLegalization is "true", the conversion is a recursive legalization request, triggered from within a pattern. In that case, do not emit errors because there will be another attempt at legalizing the operation later (via the regular pre-order legalization mechanism).
Definition at line 3308 of file DialectConversion.cpp.
References diag(), mlir::Operation::emitError(), mlir::Operation::getName(), and success().
Referenced by legalizeOperations().
getTarget()
const ConversionTarget & mlir::OperationConverter::getTarget () inline
Definition at line 3294 of file DialectConversion.cpp.
legalizeOperations() [1/2]
LogicalResult mlir::OperationConverter::legalizeOperations (ArrayRef< Operation * > ops, bool isRecursiveLegalization = false) inline
Definition at line 3281 of file DialectConversion.cpp.
References legalizeOperations().
legalizeOperations() [2/2]
template<typename Fn> LogicalResult OperationConverter::legalizeOperations (ArrayRef< Operation * > ops, Fn onFailure, bool isRecursiveLegalization = false)
Legalizes the given operations (and their nested operations) to the conversion target.
Definition at line 3401 of file DialectConversion.cpp.
References mlir::WalkResult::advance(), convert(), mlir::PreOrder, mlir::WalkResult::skip(), success(), and target.
Referenced by applyConversion(), and legalizeOperations().
The documentation for this struct was generated from the following file:
lib/Transforms/Utils/DialectConversion.cpp