MLIR: TransferReadExtractPattern Struct Reference
TransferReadExtractPattern Struct Reference
Converts TransferRead op used by ExtractMap op into a smaller dimension TransferRead.
Public Member Functions
TransferReadExtractPattern (MLIRContext *context)
LogicalResult matchAndRewrite (vector::TransferReadOp read, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< vector::TransferReadOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferReadOp >
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (vector::TransferReadOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (vector::TransferReadOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&... args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Converts TransferRead op used by ExtractMap op into a smaller dimension TransferRead.
Example:
%a = vector.transfer_read %A[%c0, %c0, %c0], %cf0:
  memref<64x64x64xf32>, vector<64x4x32xf32>
%e = vector.extract_map %a[%id] : vector<64x4x32xf32> to vector<2x4x1xf32>
to:
%id1 = affine.apply affine_map<()[s0] -> (s0 * 2)> (%id)
%e = vector.transfer_read %A[%id1, %c0, %id1], %cf0 :
  memref<64x64x64xf32>, vector<2x4x1xf32>
Definition at line 2379 of file VectorTransforms.cpp.
Constructor & Destructor Documentation
TransferReadExtractPattern()
TransferReadExtractPattern::TransferReadExtractPattern (MLIRContext * context) inline
Definition at line 2381 of file VectorTransforms.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult TransferReadExtractPattern::matchAndRewrite (vector::TransferReadOp read, PatternRewriter & rewriter) const inline override virtual
Reimplemented from mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferReadOp >.
Definition at line 2383 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::failure(), mlir::getAffineConstantExpr(), mlir::Builder::getZeroAttr(), mlir::makeComposedAffineApply(), mlir::RewriterBase::replaceOp(), rewriter, and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/Vector/VectorTransforms.cpp