MLIR: mlir::affine::AffineBuilder Struct Reference
mlir::affine::AffineBuilder Struct Reference
Helper struct to build simple AffineValueExprs with minimal type inference support.
#include "mlir/Dialect/Affine/Utils.h"
Public Member Functions
AffineBuilder (OpBuilder &b, Location loc)
OpFoldResult add (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult sub (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult mul (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult floor (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult ceil (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult min (ArrayRef< OpFoldResult > vals)
OpFoldResult max (ArrayRef< OpFoldResult > vals)
Detailed Description
Helper struct to build simple AffineValueExprs with minimal type inference support.
Definition at line 372 of file Utils.h.
Constructor & Destructor Documentation
AffineBuilder()
mlir::affine::AffineBuilder::AffineBuilder (OpBuilder & b, Location loc) inline
Definition at line 373 of file Utils.h.
Member Function Documentation
add()
OpFoldResult mlir::affine::AffineBuilder::add (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 374 of file Utils.h.
References mlir::affine::AffineValueExpr::e, and mlir::affine::makeComposedFoldedAffineApply().
ceil()
OpFoldResult mlir::affine::AffineBuilder::ceil (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 387 of file Utils.h.
References mlir::AffineExpr::ceilDiv(), mlir::affine::AffineValueExpr::e, and mlir::affine::makeComposedFoldedAffineApply().
floor()
OpFoldResult mlir::affine::AffineBuilder::floor (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 383 of file Utils.h.
References mlir::affine::AffineValueExpr::e, mlir::AffineExpr::floorDiv(), and mlir::affine::makeComposedFoldedAffineApply().
max()
OpFoldResult mlir::affine::AffineBuilder::max (ArrayRef< OpFoldResult > vals) inline
Definition at line 396 of file Utils.h.
References mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::affine::makeComposedFoldedAffineMax().
min()
OpFoldResult mlir::affine::AffineBuilder::min (ArrayRef< OpFoldResult > vals) inline
Definition at line 391 of file Utils.h.
References mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::affine::makeComposedFoldedAffineMin().
mul()
OpFoldResult mlir::affine::AffineBuilder::mul (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 380 of file Utils.h.
References mlir::affine::AffineValueExpr::e, and mlir::affine::makeComposedFoldedAffineApply().
sub()
OpFoldResult mlir::affine::AffineBuilder::sub (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 377 of file Utils.h.
References mlir::affine::AffineValueExpr::e, and mlir::affine::makeComposedFoldedAffineApply().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Affine/Utils.h