MLIR: mlir::detail::RecoveryReproducerContext Struct Reference
mlir::detail::RecoveryReproducerContext Struct Reference
This class contains all of the context for generating a recovery reproducer.
Public Member Functions
RecoveryReproducerContext (std::string passPipelineStr, Operation *op, ReproducerStreamFactory &streamFactory, bool verifyPasses)
~RecoveryReproducerContext ()
void generate (std::string &description)
Generate a reproducer with the current context.
void disable ()
Disable this reproducer context.
void enable ()
Enable a previously disabled reproducer context.
Detailed Description
This class contains all of the context for generating a recovery reproducer.
Each recovery context is registered globally to allow for generating reproducers when a signal is raised, such as a segfault.
Definition at line 37 of file PassCrashRecovery.cpp.
Constructor & Destructor Documentation
RecoveryReproducerContext()
RecoveryReproducerContext::RecoveryReproducerContext (std::string passPipelineStr, Operation * op, ReproducerStreamFactory & streamFactory, bool verifyPasses)
Definition at line 91 of file PassCrashRecovery.cpp.
References mlir::clone(), enable(), and getContext().
~RecoveryReproducerContext()
RecoveryReproducerContext::~RecoveryReproducerContext ()
Definition at line 101 of file PassCrashRecovery.cpp.
References disable().
Member Function Documentation
disable()
void RecoveryReproducerContext::disable ()
Disable this reproducer context.
This prevents the context from generating a reproducer in the result of a crash.
Definition at line 141 of file PassCrashRecovery.cpp.
Referenced by ~RecoveryReproducerContext().
enable()
void RecoveryReproducerContext::enable ()
Enable a previously disabled reproducer context.
Definition at line 148 of file PassCrashRecovery.cpp.
Referenced by RecoveryReproducerContext().
generate()
void RecoveryReproducerContext::generate (std::string & description)
Generate a reproducer with the current context.
Definition at line 136 of file PassCrashRecovery.cpp.
References appendReproducer().
Referenced by mlir::detail::PassCrashReproducerGenerator::finalize().
The documentation for this struct was generated from the following file:
lib/Pass/PassCrashRecovery.cpp