MLIR: mlir::detail::DiagnosticEngineImpl Struct Reference
mlir::detail::DiagnosticEngineImpl Struct Reference
Public Member Functions
void emit (Diagnostic diag)
Emit a diagnostic using the registered issue handle if present, or with the default behavior if not.
Public Attributes
llvm::sys::SmartMutex< true > mutex
A mutex to ensure that diagnostics emission is thread-safe.
llvm::SmallMapVector< DiagnosticEngine::HandlerID, DiagnosticEngine::HandlerTy, 2 > handlers
These are the handlers used to report diagnostics.
DiagnosticEngine::HandlerID uniqueHandlerId = 1
This is a unique identifier counter for diagnostic handlers in the context.
Detailed Description
Definition at line 199 of file Diagnostics.cpp.
Member Function Documentation
emit()
void DiagnosticEngineImpl::emit (Diagnostic diag)
Emit a diagnostic using the registered issue handle if present, or with the default behavior if not.
Definition at line 221 of file Diagnostics.cpp.
References mlir::Error, mlir::Diagnostic::getLocation(), mlir::Diagnostic::getSeverity(), mlir::Location::isa(), and mlir::succeeded().
Member Data Documentation
handlers
llvm::SmallMapVector<DiagnosticEngine::HandlerID, DiagnosticEngine::HandlerTy, 2> mlir::detail::DiagnosticEngineImpl::handlers
These are the handlers used to report diagnostics.
Definition at line 210 of file Diagnostics.cpp.
mutex
llvm::sys::SmartMutex<true> mlir::detail::DiagnosticEngineImpl::mutex
A mutex to ensure that diagnostics emission is thread-safe.
Definition at line 205 of file Diagnostics.cpp.
uniqueHandlerId
DiagnosticEngine::HandlerID mlir::detail::DiagnosticEngineImpl::uniqueHandlerId = 1
This is a unique identifier counter for diagnostic handlers in the context.
This id starts at 1 to allow for 0 to be used as a sentinel.
Definition at line 214 of file Diagnostics.cpp.
The documentation for this struct was generated from the following file:
lib/IR/Diagnostics.cpp