MLIR: AmdgpuTransferReadToLoadPass Struct Reference
AmdgpuTransferReadToLoadPass Struct Reference final
Public Member Functions
void runOnOperation () override
Detailed Description
Definition at line 229 of file TransferReadToLoad.cpp.
Member Function Documentation
runOnOperation()
void AmdgpuTransferReadToLoadPass::runOnOperation () inline override
Definition at line 232 of file TransferReadToLoad.cpp.
References mlir::applyPatternsGreedily(), getContext(), mlir::patterns, and mlir::amdgpu::populateAmdgpuTransferReadToLoadPatterns().
The documentation for this struct was generated from the following file:
lib/Dialect/AMDGPU/Transforms/TransferReadToLoad.cpp