MLIR: mlir::TimeRecord Struct Reference
mlir::TimeRecord Struct Reference
Simple record class to record timing information.
#include "mlir/Support/Timing.h"
Public Member Functions
TimeRecord (double wall=0.0, double user=0.0)
TimeRecord & operator+= (const TimeRecord &other)
TimeRecord & operator-= (const TimeRecord &other)
Public Attributes
double wall
double user
Detailed Description
Simple record class to record timing information.
Definition at line 328 of file Timing.h.
Constructor & Destructor Documentation
TimeRecord()
mlir::TimeRecord::TimeRecord (double wall = 0.0, double user = 0.0) inline
Definition at line 329 of file Timing.h.
References user, and wall.
Referenced by operator+=(), and operator-=().
Member Function Documentation
operator+=()
TimeRecord & mlir::TimeRecord::operator+= (const TimeRecord & other) inline
Definition at line 331 of file Timing.h.
References TimeRecord(), user, and wall.
operator-=()
TimeRecord & mlir::TimeRecord::operator-= (const TimeRecord & other) inline
Definition at line 337 of file Timing.h.
References TimeRecord(), user, and wall.
Member Data Documentation
user
double mlir::TimeRecord::user
Definition at line 343 of file Timing.h.
Referenced by operator+=(), operator-=(), and TimeRecord().
wall
double mlir::TimeRecord::wall
Definition at line 343 of file Timing.h.
Referenced by operator+=(), operator-=(), and TimeRecord().
The documentation for this struct was generated from the following file:
include/mlir/Support/Timing.h