MLIR: mlir::quant::detail::AnyQuantizedTypeStorage Struct Reference
mlir::quant::detail::AnyQuantizedTypeStorage Struct Reference
#include "Dialect/Quant/IR/TypeDetail.h"
Classes
struct KeyTy
Public Member Functions
AnyQuantizedTypeStorage (const KeyTy &key)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::quant::detail::QuantizedTypeStorage
QuantizedTypeStorage (unsigned flags, Type storageType, Type expressedType, int64_t storageTypeMin, int64_t storageTypeMax)
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static AnyQuantizedTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
static unsigned hashKey (const KeyTy &key)
Additional Inherited Members
Public Attributes inherited from mlir::quant::detail::QuantizedTypeStorage
unsigned flags
Flags corresponding to the bitmapped enum QuantizationFlags::FlagValue.
Type storageType
Type expressedType
int64_t storageTypeMin
int64_t storageTypeMax
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 46 of file TypeDetail.h.
Constructor & Destructor Documentation
AnyQuantizedTypeStorage()
mlir::quant::detail::AnyQuantizedTypeStorage::AnyQuantizedTypeStorage (const KeyTy & key) inline
Definition at line 78 of file TypeDetail.h.
References mlir::quant::detail::QuantizedTypeStorage::expressedType, mlir::quant::detail::QuantizedTypeStorage::flags, mlir::quant::detail::QuantizedTypeStorage::QuantizedTypeStorage(), mlir::quant::detail::QuantizedTypeStorage::storageType, mlir::quant::detail::QuantizedTypeStorage::storageTypeMax, and mlir::quant::detail::QuantizedTypeStorage::storageTypeMin.
Referenced by construct().
Member Function Documentation
construct()
AnyQuantizedTypeStorage * mlir::quant::detail::AnyQuantizedTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 87 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and AnyQuantizedTypeStorage().
hashKey()
unsigned mlir::quant::detail::AnyQuantizedTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 93 of file TypeDetail.h.
References mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::getHashValue().
operator==()
bool mlir::quant::detail::AnyQuantizedTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 82 of file TypeDetail.h.
References mlir::quant::detail::AnyQuantizedTypeStorage::KeyTy::genericIsEqual().
The documentation for this struct was generated from the following file:
lib/Dialect/Quant/IR/TypeDetail.h