MLIR: mlir::affine::ComputationSliceState Struct Reference
mlir::affine::ComputationSliceState Struct Reference
ComputationSliceState aggregates loop IVs, loop bound AffineMaps and their associated operands for a set of loops within a loop nest (typically the set of loops surrounding a store operation).
#include "mlir/Dialect/Affine/Analysis/Utils.h"
Public Member Functions
LogicalResult getAsConstraints (FlatAffineValueConstraints *cst) const
LogicalResult getSourceAsConstraints (FlatAffineValueConstraints &cst) const
Adds to 'cst' constraints which represent the original loop bounds on 'ivs' in 'this'.
void clearBounds ()
bool isEmpty () const
Returns true if the computation slice is empty.
std::optional< bool > isMaximal () const
Returns true if the computation slice encloses all the iterations of the sliced loop nest.
std::optional< bool > isSliceValid () const
Checks the validity of the slice computed.
void dump () const
Public Attributes
SmallVector< Value, 4 > ivs
SmallVector< AffineMap, 4 > lbs
SmallVector< AffineMap, 4 > ubs
std::vector< SmallVector< Value, 4 > > lbOperands
std::vector< SmallVector< Value, 4 > > ubOperands
Block::iterator insertPoint
Detailed Description
ComputationSliceState aggregates loop IVs, loop bound AffineMaps and their associated operands for a set of loops within a loop nest (typically the set of loops surrounding a store operation).
Loop bound AffineMaps which are non-null represent slices of that loop's iteration space.
Definition at line 318 of file Utils.h.
Member Function Documentation
clearBounds()
void ComputationSliceState::clearBounds ()
Definition at line 934 of file Utils.cpp.
References lbOperands, lbs, ubOperands, and ubs.
Referenced by mlir::affine::computeSliceUnion().
dump()
void ComputationSliceState::dump () const
Definition at line 941 of file Utils.cpp.
References ivs, lbOperands, lbs, ubOperands, and ubs.
getAsConstraints()
LogicalResult ComputationSliceState::getAsConstraints (FlatAffineValueConstraints * cst) const
Definition at line 898 of file Utils.cpp.
References mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::affine::FlatAffineValueConstraints::addBound(), mlir::affine::FlatAffineValueConstraints::addSliceBounds(), mlir::FlatLinearValueConstraints::containsVar(), mlir::getConstantIntValue(), mlir::affine::getForInductionVarOwner(), mlir::affine::isValidSymbol(), ivs, lbOperands, lbs, success(), and ubs.
Referenced by mlir::affine::computeSliceUnion(), and isSliceValid().
getSourceAsConstraints()
LogicalResult ComputationSliceState::getSourceAsConstraints (FlatAffineValueConstraints & cst) const
Adds to 'cst' constraints which represent the original loop bounds on 'ivs' in 'this'.
This corresponds to the original domain of the loop nest from which the slice is being computed. Returns failure if we cannot add loop bounds because of unsupported cases.
Definition at line 882 of file Utils.cpp.
References mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::affine::getForInductionVarOwner(), ivs, and success().
Referenced by isSliceValid().
isEmpty()
bool mlir::affine::ComputationSliceState::isEmpty () const inline
Returns true if the computation slice is empty.
Definition at line 350 of file Utils.h.
References ivs.
Referenced by isFusionProfitable().
isMaximal()
std::optional< bool > ComputationSliceState::isMaximal () const
Returns true if the computation slice encloses all the iterations of the sliced loop nest.
Returns false if it does not. Returns std::nullopt if it cannot determine if the slice is maximal or not.
Definition at line 1106 of file Utils.cpp.
References mlir::affine::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::affine::FlatAffineValueConstraints::addDomainFromSliceMaps(), mlir::affine::getForInductionVarOwner(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::PresburgerRelation::isIntegerEmpty(), ivs, lbOperands, lbs, mlir::presburger::PresburgerSet::subtract(), and ubs.
Referenced by canRemoveSrcNodeAfterFusion(), and mlir::affine::getComputationSliceState().
isSliceValid()
std::optional< bool > ComputationSliceState::isSliceValid () const
Checks the validity of the slice computed.
Returns true if it is deterministically verified that the original iteration space of the slice is contained within the new iteration space that is created after fusing 'this' slice into its destination.
This is done using the following steps:
Get the new domain of the slice that would be created if fusion succeeds. This domain gets constructed with source loop IVS and destination loop IVS as dimensions.
Project out the dimensions of the destination loop from the domain above calculated in step(1) to express it purely in terms of the source loop IVs.
Calculate a set difference between the iterations of the new domain and the original domain of the source loop. If this difference is empty, the slice is declared to be valid. Otherwise, return false as it implies that the effective fusion results in at least one iteration of the slice that was not originally in the source's domain. If the validity cannot be determined, returns std::nullopt.
Definition at line 1036 of file Utils.cpp.
References getAsConstraints(), mlir::presburger::IntegerRelation::getNumLocalVars(), mlir::presburger::IntegerRelation::getNumSymbolVars(), mlir::presburger::IntegerRelation::getNumVars(), getSourceAsConstraints(), mlir::presburger::PresburgerRelation::isIntegerEmpty(), ivs, mlir::FlatLinearValueConstraints::projectOut(), and mlir::presburger::PresburgerSet::subtract().
Referenced by mlir::affine::computeSliceUnion().
Member Data Documentation
insertPoint
Block::iterator mlir::affine::ComputationSliceState::insertPoint
Definition at line 331 of file Utils.h.
Referenced by mlir::affine::computeSliceUnion(), mlir::affine::fuseLoops(), mlir::affine::getComputationSliceState(), and mlir::affine::getFusionComputeCost().
ivs
SmallVector<Value, 4> mlir::affine::ComputationSliceState::ivs
Definition at line 321 of file Utils.h.
Referenced by mlir::affine::buildSliceTripCountMap(), mlir::affine::MemRefRegion::compute(), mlir::affine::computeSliceUnion(), dump(), mlir::affine::fuseLoops(), getAsConstraints(), mlir::affine::getComputationSliceState(), getSourceAsConstraints(), isEmpty(), isMaximal(), and isSliceValid().
lbOperands
std::vector<SmallVector<Value, 4> > mlir::affine::ComputationSliceState::lbOperands
Definition at line 327 of file Utils.h.
Referenced by clearBounds(), mlir::affine::MemRefRegion::compute(), mlir::affine::computeSliceUnion(), dump(), mlir::affine::fuseLoops(), getAsConstraints(), mlir::affine::getComputationSliceState(), mlir::affine::insertBackwardComputationSlice(), and isMaximal().
lbs
SmallVector<AffineMap, 4> mlir::affine::ComputationSliceState::lbs
Definition at line 323 of file Utils.h.
Referenced by mlir::affine::buildSliceTripCountMap(), clearBounds(), mlir::affine::MemRefRegion::compute(), mlir::affine::computeSliceUnion(), dump(), mlir::affine::fuseLoops(), getAsConstraints(), mlir::affine::getComputationSliceState(), mlir::affine::insertBackwardComputationSlice(), and isMaximal().
ubOperands
std::vector<SmallVector<Value, 4> > mlir::affine::ComputationSliceState::ubOperands
Definition at line 329 of file Utils.h.
Referenced by clearBounds(), mlir::affine::computeSliceUnion(), dump(), mlir::affine::fuseLoops(), mlir::affine::getComputationSliceState(), and mlir::affine::insertBackwardComputationSlice().
ubs
SmallVector<AffineMap, 4> mlir::affine::ComputationSliceState::ubs
Definition at line 325 of file Utils.h.
Referenced by mlir::affine::buildSliceTripCountMap(), clearBounds(), mlir::affine::MemRefRegion::compute(), mlir::affine::computeSliceUnion(), dump(), mlir::affine::fuseLoops(), getAsConstraints(), mlir::affine::getComputationSliceState(), mlir::affine::insertBackwardComputationSlice(), and isMaximal().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Affine/Analysis/Utils.h
lib/Dialect/Affine/Analysis/Utils.cpp