MLIR: mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr Struct Reference
mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr Struct Reference
Static Public Member Functions
static void bindDerived (ClassTy &c)
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDNodeAttr >
static MlirAttribute castFrom (PyAttribute &orig)
static void bind (nanobind::module_ &m, PyType_Slot *slots=nullptr)
static void bindDerived (ClassTy &m)
Implemented by derived classes to add methods to the Python subclass.
Static Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
static PyAttribute createFromCapsule (const nanobind::object &capsule)
Creates a PyAttribute from the MlirAttribute wrapped by a capsule.
Static Public Attributes
static constexpr IsAFunctionTy isaFunction = mlirLLVMAttrIsAMDNodeAttr
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static constexpr const char * pyClassName = "MDNodeAttr"
Static Public Attributes inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDNodeAttr >
static constexpr GetTypeIDFunctionTy getTypeIdFunction
static const MlirStringRef name
Additional Inherited Members
Public Types inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDNodeAttr >
using ClassTy
using IsAFunctionTy
using GetTypeIDFunctionTy
using Base
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyConcreteAttribute< MDNodeAttr >
PyConcreteAttribute ()=default
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::PyAttribute
PyAttribute (PyMlirContextRef contextRef, MlirAttribute attr)
bool operator== (const PyAttribute &other) const
operator MlirAttribute () const
MlirAttribute get () const
nanobind::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAttribute.
nanobind::typed< nanobind::object, PyAttribute > maybeDownCast ()
Public Member Functions inherited from mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Detailed Description
Definition at line 351 of file DialectLLVM.cpp.
Member Function Documentation
bindDerived()
void mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::bindDerived (ClassTy & c) inline static
Definition at line 358 of file DialectLLVM.cpp.
References mlir::python::Defaulting< DerivedTy, T >::get(), mlirLLVMMDNodeAttrGet(), mlirLLVMMDNodeAttrGetNumOperands(), and mlirLLVMMDNodeAttrGetOperand().
Member Data Documentation
getTypeIdFunction
GetTypeIDFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::getTypeIdFunction static constexpr
Initial value:
=
      mlirLLVMMDNodeAttrGetTypeID
Definition at line 353 of file DialectLLVM.cpp.
isaFunction
IsAFunctionTy mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::isaFunction = mlirLLVMAttrIsAMDNodeAttr static constexpr
Definition at line 352 of file DialectLLVM.cpp.
pyClassName
const char* mlir::python::MLIR_BINDINGS_PYTHON_DOMAIN::llvm::MDNodeAttr::pyClassName = "MDNodeAttr" static constexpr
Definition at line 355 of file DialectLLVM.cpp.
The documentation for this struct was generated from the following file:
lib/Bindings/Python/DialectLLVM.cpp