MLIR: mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem Struct Reference
mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem Struct Reference
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
Public Types
using OpView = PointerUnion< OpOperand *, Value >
Public Member Functions
Operation * getDependentOp () const
Operation * getIndexingOp () const
Value getDependentValue () const
Value getIndexingValue () const
Optional< unsigned > getDependentOpViewOperandNum () const
Optional< unsigned > getIndexingOpViewOperandNum () const
Optional< unsigned > getDependentOpViewResultNum () const
Optional< unsigned > getIndexingOpViewResultNum () const
Optional< AffineMap > getDependentOpViewIndexingMap () const
Optional< AffineMap > getIndexingOpViewIndexingMap () const
Static Public Member Functions
static Operation * getOwner (OpView opView)
static Value getValue (OpView opView)
static Optional< AffineMap > getIndexingMap (OpView opView)
static Optional< unsigned > getOperandNumber (OpView opView)
static Optional< unsigned > getResultNumber (OpView opView)
Public Attributes
OpView dependentOpView
OpView indexingOpView
DependenceType dependenceType
Detailed Description
Definition at line 50 of file DependenceAnalysis.h.
Member Typedef Documentation
OpView
using mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::OpView = PointerUnion<OpOperand *, Value>
Definition at line 51 of file DependenceAnalysis.h.
Member Function Documentation
getDependentOp()
Operation* mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getDependentOp () const inline
Definition at line 103 of file DependenceAnalysis.h.
Referenced by getConsumerLoopToProducerLoopMap().
getDependentOpViewIndexingMap()
Optional<AffineMap> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getDependentOpViewIndexingMap () const inline
Definition at line 140 of file DependenceAnalysis.h.
Referenced by getConsumerLoopToProducerLoopMap().
getDependentOpViewOperandNum()
Optional<unsigned> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getDependentOpViewOperandNum () const inline
Definition at line 116 of file DependenceAnalysis.h.
getDependentOpViewResultNum()
Optional<unsigned> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getDependentOpViewResultNum () const inline
Definition at line 128 of file DependenceAnalysis.h.
getDependentValue()
Value mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getDependentValue () const inline
Definition at line 109 of file DependenceAnalysis.h.
getIndexingMap()
static Optional<AffineMap> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getIndexingMap (OpView opView) inline static
Definition at line 78 of file DependenceAnalysis.h.
References mlir::Value::cast(), and mlir::OpResult::getResultNumber().
getIndexingOp()
Operation* mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getIndexingOp () const inline
Definition at line 106 of file DependenceAnalysis.h.
getIndexingOpViewIndexingMap()
Optional<AffineMap> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getIndexingOpViewIndexingMap () const inline
Definition at line 146 of file DependenceAnalysis.h.
Referenced by getConsumerLoopToProducerLoopMap().
getIndexingOpViewOperandNum()
Optional<unsigned> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getIndexingOpViewOperandNum () const inline
Definition at line 122 of file DependenceAnalysis.h.
getIndexingOpViewResultNum()
Optional<unsigned> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getIndexingOpViewResultNum () const inline
Definition at line 134 of file DependenceAnalysis.h.
getIndexingValue()
Value mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getIndexingValue () const inline
Definition at line 112 of file DependenceAnalysis.h.
getOperandNumber()
static Optional<unsigned> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getOperandNumber (OpView opView) inline static
Definition at line 89 of file DependenceAnalysis.h.
getOwner()
static Operation* mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getOwner (OpView opView) inline static
Definition at line 65 of file DependenceAnalysis.h.
Referenced by mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraph().
getResultNumber()
static Optional<unsigned> mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getResultNumber (OpView opView) inline static
Definition at line 96 of file DependenceAnalysis.h.
References mlir::Value::cast().
getValue()
static Value mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::getValue (OpView opView) inline static
Definition at line 71 of file DependenceAnalysis.h.
Referenced by mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraph().
Member Data Documentation
dependenceType
DependenceType mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::dependenceType
Definition at line 61 of file DependenceAnalysis.h.
dependentOpView
OpView mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::dependentOpView
Definition at line 55 of file DependenceAnalysis.h.
indexingOpView
OpView mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::indexingOpView
Definition at line 59 of file DependenceAnalysis.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h