MLIR: mlir::detail::constant_int_value_binder Struct Reference
mlir::detail::constant_int_value_binder Struct Reference
The matcher that matches a constant scalar / vector splat / tensor splat integer Attribute or Operation and binds the constant integer value.
#include "mlir/IR/Matchers.h"
Public Member Functions
constant_int_value_binder (IntegerAttr::ValueType *bv)
Creates a matcher instance that binds the value to bv if match succeeds.
bool match (Attribute attr)
bool match (Operation *op)
Public Attributes
IntegerAttr::ValueType * bind_value
Detailed Description
The matcher that matches a constant scalar / vector splat / tensor splat integer Attribute or Operation and binds the constant integer value.
Definition at line 210 of file Matchers.h.
Constructor & Destructor Documentation
constant_int_value_binder()
mlir::detail::constant_int_value_binder::constant_int_value_binder (IntegerAttr::ValueType * bv) inline
Creates a matcher instance that binds the value to bv if match succeeds.
Definition at line 214 of file Matchers.h.
References bind_value.
Member Function Documentation
match() [1/2]
bool mlir::detail::constant_int_value_binder::match (Attribute attr) inline
Definition at line 216 of file Matchers.h.
References bind_value, and mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::match().
Referenced by mlir::detail::constant_int_predicate_matcher::match(), mlir::detail::constant_int_predicate_matcher::match(), mlir::detail::constant_int_range_predicate_matcher::match(), and match().
match() [2/2]
bool mlir::detail::constant_int_value_binder::match (Operation * op) inline
Definition at line 227 of file Matchers.h.
References mlir::Operation::getResult(), mlir::Value::getType(), and match().
Member Data Documentation
bind_value
IntegerAttr::ValueType* mlir::detail::constant_int_value_binder::bind_value
Definition at line 211 of file Matchers.h.
Referenced by constant_int_value_binder(), and match().
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h