MLIR: mlir::pdl_to_pdl_interp::ConstraintQuestion Struct Reference
mlir::pdl_to_pdl_interp::ConstraintQuestion Struct Reference
Apply a parameterized constraint to multiple position values and possibly produce results.
#include "Conversion/PDLToPDLInterp/Predicate.h"
Public Member Functions
StringRef getName () const
Return the name of the constraint.
ArrayRef< Position * > getArgs () const
Return the arguments of the constraint.
ArrayRef< Type > getResultTypes () const
Return the result types of the constraint.
bool getIsNegated () const
Return the negation status of the constraint.
Public Member Functions inherited from mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >
PredicateBase (KeyT &&key)
bool operator== (const KeyTy &key) const
Utility methods required by the storage allocator.
const KeyTy & getValue () const
Return the key value of this predicate.
Public Member Functions inherited from mlir::pdl_to_pdl_interp::Qualifier
Qualifier (Predicates::Kind kind)
Predicates::Kind getKind () const
Returns the kind of this qualifier.
Static Public Member Functions
static ConstraintQuestion * construct (StorageUniquer::StorageAllocator &alloc, KeyTy key)
Construct an instance with the given storage allocator.
static llvm::hash_code hashKey (const KeyTy &key)
Returns a hash suitable for the given keytype.
Static Public Member Functions inherited from mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >
static ConstraintQuestion * get (StorageUniquer &uniquer, Args &&...args)
Get an instance of this position.
static ConstraintQuestion * construct (StorageUniquer::StorageAllocator &alloc, KeyT &&key)
Construct an instance with the given storage allocator.
static bool classof (const Qualifier *pred)
Additional Inherited Members
Public Types inherited from mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >
using KeyTy = std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >
using Base = PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Kind >
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Protected Attributes inherited from mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >
KeyTy key
Detailed Description
Apply a parameterized constraint to multiple position values and possibly produce results.
Definition at line 489 of file Predicate.h.
Member Function Documentation
construct()
static ConstraintQuestion* mlir::pdl_to_pdl_interp::ConstraintQuestion::construct (StorageUniquer::StorageAllocator & alloc, KeyTy key) inline static
Construct an instance with the given storage allocator.
Definition at line 509 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConcreteT, BaseT, Key, Kind >::construct(), mlir::StorageUniquer::StorageAllocator::copyInto(), and mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::key.
getArgs()
ArrayRef<Position *> mlir::pdl_to_pdl_interp::ConstraintQuestion::getArgs () const inline
Return the arguments of the constraint.
Definition at line 500 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::key.
getIsNegated()
bool mlir::pdl_to_pdl_interp::ConstraintQuestion::getIsNegated () const inline
Return the negation status of the constraint.
Definition at line 506 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::key.
getName()
StringRef mlir::pdl_to_pdl_interp::ConstraintQuestion::getName () const inline
Return the name of the constraint.
Definition at line 497 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::key.
getResultTypes()
ArrayRef<Type> mlir::pdl_to_pdl_interp::ConstraintQuestion::getResultTypes () const inline
Return the result types of the constraint.
Definition at line 503 of file Predicate.h.
References mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::key.
hashKey()
static llvm::hash_code mlir::pdl_to_pdl_interp::ConstraintQuestion::hashKey (const KeyTy & key) inline static
Returns a hash suitable for the given keytype.
Definition at line 518 of file Predicate.h.
References mlir::spirv::hash_value(), and mlir::pdl_to_pdl_interp::PredicateBase< ConstraintQuestion, Qualifier, std::tuple< StringRef, ArrayRef< Position * >, ArrayRef< Type >, bool >, Predicates::ConstraintQuestion >::key.
The documentation for this struct was generated from the following file:
lib/Conversion/PDLToPDLInterp/Predicate.h