MLIR: pybind11::detail::type_caster< MlirFrozenRewritePatternSet > Struct Reference
pybind11::detail::type_caster< MlirFrozenRewritePatternSet > Struct Reference
Casts object <-> MlirFrozenRewritePatternSet.
#include "mlir/Bindings/Python/PybindAdaptors.h"
Public Member Functions
PYBIND11_TYPE_CASTER (MlirFrozenRewritePatternSet, _("MlirFrozenRewritePatternSet"))
bool load (handle src, bool)
Static Public Member Functions
static handle cast (MlirFrozenRewritePatternSet v, return_value_policy, handle)
Detailed Description
Casts object <-> MlirFrozenRewritePatternSet.
Definition at line 204 of file PybindAdaptors.h.
Member Function Documentation
cast()
handle pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::cast (MlirFrozenRewritePatternSet v, return_value_policy , handle) inline static
Definition at line 212 of file PybindAdaptors.h.
References MAKE_MLIR_PYTHON_QUALNAME, MLIR_PYTHON_CAPI_FACTORY_ATTR, and mlirPythonFrozenRewritePatternSetToCapsule().
load()
bool pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::load (handle src, bool) inline
Definition at line 207 of file PybindAdaptors.h.
References pybind11::detail::mlirApiObjectToCapsule(), and mlirPythonCapsuleToFrozenRewritePatternSet().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< MlirFrozenRewritePatternSet >::PYBIND11_TYPE_CASTER (MlirFrozenRewritePatternSet , _("MlirFrozenRewritePatternSet"))
The documentation for this struct was generated from the following file:
include/mlir/Bindings/Python/PybindAdaptors.h