MLIR: mlir::tblgen::NamedTypeConstraint Struct Reference
mlir::tblgen::NamedTypeConstraint Struct Reference
#include "mlir/TableGen/Argument.h"
Public Member Functions
bool hasPredicate () const
bool isOptional () const
bool isVariadic () const
bool isVariadicOfVariadic () const
bool isVariableLength () const
Public Attributes
llvm::StringRef name
TypeConstraint constraint
Detailed Description
Definition at line 44 of file Argument.h.
Member Function Documentation
hasPredicate()
bool NamedTypeConstraint::hasPredicate () const
Definition at line 18 of file Argument.cpp.
References constraint, mlir::tblgen::Constraint::getPredicate(), and mlir::tblgen::Pred::isNull().
isOptional()
bool NamedTypeConstraint::isOptional () const
Definition at line 22 of file Argument.cpp.
References constraint, and mlir::tblgen::TypeConstraint::isOptional().
Referenced by isVariableLength().
isVariableLength()
bool mlir::tblgen::NamedTypeConstraint::isVariableLength () const inline
Definition at line 56 of file Argument.h.
References isOptional(), and isVariadic().
isVariadic()
bool NamedTypeConstraint::isVariadic () const
Definition at line 24 of file Argument.cpp.
References constraint, and mlir::tblgen::TypeConstraint::isVariadic().
Referenced by mlir::tblgen::Operator::hasSingleVariadicArg(), mlir::tblgen::Operator::hasSingleVariadicResult(), isVariableLength(), and mlir::tblgen::Operator::isVariadic().
isVariadicOfVariadic()
bool NamedTypeConstraint::isVariadicOfVariadic () const
Definition at line 26 of file Argument.cpp.
References constraint, and mlir::tblgen::TypeConstraint::isVariadicOfVariadic().
Member Data Documentation
constraint
TypeConstraint mlir::tblgen::NamedTypeConstraint::constraint
Definition at line 59 of file Argument.h.
Referenced by mlir::tblgen::Operator::getNumVariableLengthOperands(), mlir::tblgen::Operator::getNumVariableLengthResults(), hasPredicate(), isOptional(), isVariadic(), and isVariadicOfVariadic().
name
llvm::StringRef mlir::tblgen::NamedTypeConstraint::name
Definition at line 58 of file Argument.h.
The documentation for this struct was generated from the following files:
include/mlir/TableGen/Argument.h
lib/TableGen/Argument.cpp