MLIR: mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op > Struct Template Reference
mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op > Struct Template Reference
#include "mlir/Dialect/Shard/Interfaces/ShardingInterfaceImpl.h"
Public Member Functions
SmallVector< utils::IteratorType > getLoopIteratorTypes (Operation *operation) const
SmallVector< AffineMap > getIndexingMaps (Operation *op) const
LogicalResult partition (Operation *op, ArrayRef< Value > partitionedOperands, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, IRMapping &partitionMap, SymbolTableCollection &symbolTable, OpBuilder &builder) const
Detailed Description
template<typename Op>
struct mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >
Definition at line 55 of file ShardingInterfaceImpl.h.
Member Function Documentation
getIndexingMaps()
template<typename Op> SmallVector< AffineMap > mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >::getIndexingMaps (Operation * op) const inline
Definition at line 70 of file ShardingInterfaceImpl.h.
getLoopIteratorTypes()
template<typename Op> SmallVector< utils::IteratorType > mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >::getLoopIteratorTypes (Operation * operation) const inline
Definition at line 59 of file ShardingInterfaceImpl.h.
References mlir::Operation::getOperandTypes(), and mlir::Operation::getResultTypes().
partition()
template<typename Op> LogicalResult mlir::shard::IndependentParallelIteratorDomainShardingInterface< Op >::partition (Operation * op, ArrayRef< Value > partitionedOperands, ArrayRef< Sharding > operandShardings, ArrayRef< Sharding > resultShardings, IRMapping & partitionMap, SymbolTableCollection & symbolTable, OpBuilder & builder) const inline
Definition at line 75 of file ShardingInterfaceImpl.h.
References mlir::shard::partitionTriviallyShardableOperation(), and success().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Shard/Interfaces/ShardingInterfaceImpl.h