MLIR: mlir::detail::AffineMapStorage Struct Reference
mlir::detail::AffineMapStorage Struct Reference final
#include "IR/AffineMapDetail.h"
Public Types
using KeyTy = std::tuple< unsigned, unsigned, ArrayRef< AffineExpr > >
The hash key used for uniquing.
Public Member Functions
ArrayRef< AffineExpr > results () const
The affine expressions for this (multi-dimensional) map.
bool operator== (const KeyTy &key) const
Static Public Member Functions
static AffineMapStorage * construct (StorageUniquer::StorageAllocator &allocator, const KeyTy &key)
Public Attributes
unsigned numDims
unsigned numSymbols
unsigned numResults
MLIRContext * context
Additional Inherited Members
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
Definition at line 25 of file AffineMapDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::AffineMapStorage::KeyTy = std::tuple<unsigned, unsigned, ArrayRef<AffineExpr> >
The hash key used for uniquing.
Definition at line 31 of file AffineMapDetail.h.
Member Function Documentation
construct()
static AffineMapStorage* mlir::detail::AffineMapStorage::construct (StorageUniquer::StorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 52 of file AffineMapDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), numDims, and results().
operator==()
bool mlir::detail::AffineMapStorage::operator== (const KeyTy & key) const inline
Definition at line 44 of file AffineMapDetail.h.
References numDims, numSymbols, and results().
results()
ArrayRef<AffineExpr> mlir::detail::AffineMapStorage::results () const inline
The affine expressions for this (multi-dimensional) map.
Definition at line 40 of file AffineMapDetail.h.
References numResults.
Referenced by construct(), mlir::AffineMap::getResults(), and operator==().
Member Data Documentation
context
MLIRContext* mlir::detail::AffineMapStorage::context
Definition at line 37 of file AffineMapDetail.h.
Referenced by mlir::AffineMap::getContext().
numDims
unsigned mlir::detail::AffineMapStorage::numDims
Definition at line 33 of file AffineMapDetail.h.
Referenced by construct(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), and operator==().
numResults
unsigned mlir::detail::AffineMapStorage::numResults
Definition at line 35 of file AffineMapDetail.h.
Referenced by results().
numSymbols
unsigned mlir::detail::AffineMapStorage::numSymbols
Definition at line 34 of file AffineMapDetail.h.
Referenced by mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumSymbols(), and operator==().
The documentation for this struct was generated from the following file:
lib/IR/AffineMapDetail.h