MLIR: mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers > Struct Template Reference
mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers > Struct Template Reference
RecursivePatternMatcher that composes.
#include "mlir/IR/Matchers.h"
Public Member Functions
RecursivePatternMatcher (OperandMatchers... matchers)
bool match (Operation *op)
Public Attributes
std::tuple< OperandMatchers... > operandMatchers
Detailed Description
template<typename OpType, typename... OperandMatchers>
struct mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >
RecursivePatternMatcher that composes.
Definition at line 351 of file Matchers.h.
Constructor & Destructor Documentation
RecursivePatternMatcher()
template<typename OpType , typename... OperandMatchers> mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::RecursivePatternMatcher (OperandMatchers... matchers) inline
Definition at line 352 of file Matchers.h.
Member Function Documentation
match()
template<typename OpType , typename... OperandMatchers> bool mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match (Operation * op) inline
Definition at line 354 of file Matchers.h.
References mlir::detail::enumerate(), mlir::Operation::getNumOperands(), mlir::detail::matchOperandOrValueAtIndex(), and mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::operandMatchers.
Member Data Documentation
operandMatchers
template<typename OpType , typename... OperandMatchers> std::tuple<OperandMatchers...> mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::operandMatchers
Definition at line 363 of file Matchers.h.
Referenced by mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match().
The documentation for this struct was generated from the following file:
include/mlir/IR/Matchers.h