MLIR: lib/TableGen/Predicate.cpp File Reference
Predicate.cpp File Reference
#include "mlir/TableGen/Predicate.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
Enumerations
enum PredCombinerKind
Functions
static PredCombinerKind getPredCombinerKind (const Pred &pred)
static void performSubstitutions (std::string &str, ArrayRef< Subst > substitutions)
Perform the given substitutions on 'str' in-place.
static PredNode * buildPredicateTree (const Pred &root, llvm::SpecificBumpPtrAllocator< PredNode > &allocator, ArrayRef< Subst > substitutions)
static PredNode * propagateGroundTruth (PredNode *node, const llvm::SmallPtrSetImpl< Pred *> &knownTruePreds, const llvm::SmallPtrSetImpl< Pred *> &knownFalsePreds)
static std::string combineBinary (ArrayRef< std::string > children, std::string combiner, std::string init)
static std::string combineNot (ArrayRef< std::string > children)
static std::string getCombinedCondition (const PredNode &root)
Enumeration Type Documentation
PredCombinerKind
enum PredCombinerKind strong
Definition at line 90 of file Predicate.cpp.
Function Documentation
buildPredicateTree()
static PredNode* buildPredicateTree (const Pred & root, llvm::SpecificBumpPtrAllocator< PredNode > & allocator, ArrayRef< Subst > substitutions) static
Definition at line 158 of file Predicate.cpp.
References mlir::tblgen::Pred::getCondition(), getPredCombinerKind(), mlir::tblgen::Pred::isCombined(), performSubstitutions(), and mlir::tblgen::Pred::Pred().
Referenced by mlir::tblgen::CombinedPred::getConditionImpl().
combineBinary()
static std::string combineBinary (ArrayRef< std::string > children, std::string combiner, std::string init) static
Definition at line 287 of file Predicate.cpp.
Referenced by getCombinedCondition().
combineNot()
static std::string combineNot (ArrayRef< std::string > children) static
Definition at line 306 of file Predicate.cpp.
Referenced by getCombinedCondition().
getCombinedCondition()
static std::string getCombinedCondition (const PredNode & root) static
Definition at line 313 of file Predicate.cpp.
References combineBinary(), and combineNot().
Referenced by mlir::tblgen::CombinedPred::getConditionImpl().
getPredCombinerKind()
static PredCombinerKind getPredCombinerKind (const Pred & pred) static
Definition at line 117 of file Predicate.cpp.
References mlir::tblgen::Pred::isCombined().
Referenced by buildPredicateTree().
performSubstitutions()
static void performSubstitutions (std::string & str, ArrayRef< Subst > substitutions) static
Perform the given substitutions on 'str' in-place.
Definition at line 137 of file Predicate.cpp.
Referenced by buildPredicateTree().
propagateGroundTruth()
static PredNode* propagateGroundTruth (PredNode * node, const llvm::SmallPtrSetImpl< Pred *> & knownTruePreds, const llvm::SmallPtrSetImpl< Pred *> & knownFalsePreds) static
Definition at line 204 of file Predicate.cpp.
Referenced by mlir::tblgen::CombinedPred::getConditionImpl().