MLIR: lib/Target/LLVMIR/Transforms/TargetToDataLayout.cpp File Reference
TargetToDataLayout.cpp File Reference
#include "mlir/Target/LLVMIR/Transforms/Passes.h"
#include "mlir/Dialect/DLTI/DLTI.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Target/LLVMIR/Import.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Target/TargetMachine.h"
#include "mlir/Target/LLVMIR/Transforms/Passes.h.inc"
Classes
struct TargetToDataLayoutPass
Namespaces
mlir
Include the generated interface declarations.
mlir::LLVM
Macros
#define DEBUG_TYPE "mlir-llvm-target-to-data-layout"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X << "\n")
#define GEN_PASS_DEF_LLVMTARGETTODATALAYOUT
Functions
static FailureOr< std::unique_ptr< llvm::TargetMachine > > getTargetMachine (LLVM::TargetAttrInterface attr)
static FailureOr< llvm::DataLayout > getDataLayout (LLVM::TargetAttrInterface attr)
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 20 of file TargetToDataLayout.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "mlir-llvm-target-to-data-layout"
Definition at line 19 of file TargetToDataLayout.cpp.
GEN_PASS_DEF_LLVMTARGETTODATALAYOUT
#define GEN_PASS_DEF_LLVMTARGETTODATALAYOUT
Definition at line 25 of file TargetToDataLayout.cpp.
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X << "\n")
Definition at line 21 of file TargetToDataLayout.cpp.
Function Documentation
getDataLayout()
static FailureOr<llvm::DataLayout> getDataLayout (LLVM::TargetAttrInterface attr) static
Definition at line 51 of file TargetToDataLayout.cpp.
References mlir::remark::failed(), getTargetMachine(), and LDBG.
Referenced by TargetToDataLayoutPass::runOnOperation().
getTargetMachine()
static FailureOr<std::unique_ptr<llvm::TargetMachine> > getTargetMachine (LLVM::TargetAttrInterface attr) static
Definition at line 33 of file TargetToDataLayout.cpp.
References LDBG.
Referenced by getDataLayout().