MLIR: lib/Dialect/Linalg/Transforms/Tiling.cpp File Reference
Tiling.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/CommandLine.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-tiling"
#define GET_OP_LIST
#define GET_OP_LIST
Typedefs
using LoopIndexToRangeIndexMap = DenseMap< int, int >
Functions
static bool isZero (Value v)
static std::tuple< SmallVector< Range, 4 >, LoopIndexToRangeIndexMap > makeTiledLoopRanges (OpBuilder &b, Location loc, AffineMap map, ValueRange allShapeSizes, ValueRange allTileSizes)
static void transformIndexOps (OpBuilder &b, LinalgOp op, SmallVectorImpl< Value > &ivs, const LoopIndexToRangeIndexMap &loopIndexToRangeIndex)
static Value insertSliceIntoTensor (OpBuilder &b, Location loc, tensor::ExtractSliceOp sliceOp, Value source, Value dest)
template<typename LoopTy >
static Optional< TiledLinalgOp > tileLinalgOpImpl (OpBuilder &b, LinalgOp op, ValueRange tileSizes, const LinalgTilingOptions &options)
template<typename LoopTy >
static Optional< TiledLinalgOp > tileLinalgOpImpl (OpBuilder &b, LinalgOp op, const LinalgTilingOptions &options)
static LogicalResult tilePadTensorOp (OpBuilder &builder, PadTensorOp op, PadTensorOp &newPadOp, LoopNest &loopNest, const LinalgTilingOptions &options)
Generate a loop nest around a given PadTensorOp (for tiling).
static void insertTilingPatterns (RewritePatternSet &patterns, const LinalgTilingOptions &options)
Populate the given list with patterns that apply Linalg tiling.
static void applyExtractSliceOfPadTensorSwapPattern (FuncOp funcOp)
static void applyTilingToLoopPatterns (LinalgTilingLoopType loopType, FuncOp funcOp, ArrayRef< int64_t > tileSizes, ArrayRef< StringRef > distributionTypes={})
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-tiling"
Definition at line 31 of file Tiling.cpp.
GET_OP_LIST [1/2]
#define GET_OP_LIST
GET_OP_LIST [2/2]
#define GET_OP_LIST
Typedef Documentation
LoopIndexToRangeIndexMap
using LoopIndexToRangeIndexMap = DenseMap<int, int>
Definition at line 39 of file Tiling.cpp.
Function Documentation
applyExtractSliceOfPadTensorSwapPattern()
static void applyExtractSliceOfPadTensorSwapPattern (FuncOp funcOp) static
Definition at line 519 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsAndFoldGreedily(), mlir::RewritePatternSet::getContext(), and mlir::linalg::getLinalgTilingCanonicalizationPatterns().
Referenced by applyTilingToLoopPatterns().
applyTilingToLoopPatterns()
static void applyTilingToLoopPatterns (LinalgTilingLoopType loopType, FuncOp funcOp, ArrayRef< int64_t > tileSizes, ArrayRef< StringRef > distributionTypes = {}) static
Definition at line 529 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), applyExtractSliceOfPadTensorSwapPattern(), mlir::applyPatternsAndFoldGreedily(), mlir::RewritePatternSet::getContext(), mlir::linalg::getLinalgTilingCanonicalizationPatterns(), insertTilingPatterns(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::linalg::Loops, op, options, mlir::linalg::ParallelLoops, mlir::linalg::LinalgTilingOptions::setDistributionTypes(), mlir::linalg::LinalgTilingOptions::setLoopType(), mlir::linalg::LinalgTilingOptions::setTileSizes(), and mlir::linalg::TiledLoops.
insertSliceIntoTensor()
static Value insertSliceIntoTensor (OpBuilder & b, Location loc, tensor::ExtractSliceOp sliceOp, Value source, Value dest) static
Definition at line 158 of file Tiling.cpp.
References mlir::OpBuilder::create(), and loc.
Referenced by tileLinalgOpImpl(), and tilePadTensorOp().
insertTilingPatterns()
static void insertTilingPatterns (RewritePatternSet & patterns, const LinalgTilingOptions & options) static
Populate the given list with patterns that apply Linalg tiling.
Definition at line 510 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
Referenced by applyTilingToLoopPatterns().
isZero()
static bool isZero (Value v) static
Definition at line 33 of file Tiling.cpp.
References mlir::Value::getDefiningOp().
Referenced by makeTiledLoopRanges(), tileLinalgOpImpl(), and tilePadTensorOp().
makeTiledLoopRanges()
static std::tuple<SmallVector<Range, 4>, LoopIndexToRangeIndexMap> makeTiledLoopRanges (OpBuilder & b, Location loc, AffineMap map, ValueRange allShapeSizes, ValueRange allTileSizes) static
Definition at line 51 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::AffineMap::getNumResults(), and isZero().
Referenced by tileLinalgOpImpl().
tileLinalgOpImpl() [1/2]
template<typename LoopTy > static Optional<TiledLinalgOp> tileLinalgOpImpl (OpBuilder & b, LinalgOp op, ValueRange tileSizes, const LinalgTilingOptions & options) static
Definition at line 169 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::linalg::applyPermutationToVector(), mlir::linalg::LinalgTilingOptions::distribution, mlir::linalg::LinalgTilingOptions::distributionTypes, mlir::linalg::GenerateLoopNest< LoopTy >::doit(), mlir::detail::enumerate(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::AffineMap::getPermutationMap(), mlir::Operation::getResults(), insertSliceIntoTensor(), mlir::linalg::LinalgTilingOptions::interchangeVector, mlir::inversePermutation(), isZero(), loc, makeTiledLoopRanges(), mlir::linalg::makeTiledShapes(), op, and transformIndexOps().
tileLinalgOpImpl() [2/2]
template<typename LoopTy > static Optional<TiledLinalgOp> tileLinalgOpImpl (OpBuilder & b, LinalgOp op, const LinalgTilingOptions & options) static
Definition at line 316 of file Tiling.cpp.
References mlir::OpBuilder::create(), op, options, mlir::OpBuilder::setInsertionPoint(), and mlir::linalg::LinalgTilingOptions::tileSizeComputationFunction.
tilePadTensorOp()
static LogicalResult tilePadTensorOp (OpBuilder & builder, PadTensorOp op, PadTensorOp & newPadOp, LoopNest & loopNest, const LinalgTilingOptions & options) static
Generate a loop nest around a given PadTensorOp (for tiling).
newPadOp and loopNest are output parameters that return the new (tiled) PadTensorOp and the loop nest.
Definition at line 356 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), mlir::scf::buildLoopNest(), mlir::OpBuilder::clone(), mlir::linalg::computeTileOffsets(), mlir::linalg::computeTileSizes(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Identifier::get(), mlir::Builder::getContext(), mlir::RewritePatternSet::getContext(), mlir::Value::getDefiningOp(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::scf::LoopNest::getResults(), mlir::Builder::getUnitAttr(), insertSliceIntoTensor(), isZero(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, loc, mlir::linalg::makeTiledShape(), map(), op, options, mlir::RewriterBase::replaceOp(), rewriter, mlir::OpBuilder::setInsertionPoint(), mlir::success(), and mlir::linalg::LinalgTilingOptions::tileSizeComputationFunction.
transformIndexOps()
static void transformIndexOps (OpBuilder & b, LinalgOp op, SmallVectorImpl< Value > & ivs, const LoopIndexToRangeIndexMap & loopIndexToRangeIndex) static
Definition at line 129 of file Tiling.cpp.
References mlir::bindDims(), mlir::OpBuilder::create(), mlir::Block::front(), mlir::Builder::getContext(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by tileLinalgOpImpl().