MLIR: lib/Analysis/TopologicalSortUtils.cpp File Reference
TopologicalSortUtils.cpp File Reference
#include "mlir/Analysis/TopologicalSortUtils.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/RegionGraphTraits.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
Functions
static bool isOpReady (Operation *op, DenseSet< Operation * > &unscheduledOps, function_ref< bool(Value, Operation *)> isOperandReady)
Return true if the given operation is ready to be scheduled.
Function Documentation
isOpReady()
static bool isOpReady (Operation * op, DenseSet< Operation * > & unscheduledOps, function_ref< bool(Value, Operation *)> isOperandReady) static
Return true if the given operation is ready to be scheduled.
Definition at line 20 of file TopologicalSortUtils.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getOperands(), mlir::Operation::getParentOp(), mlir::WalkResult::interrupt(), mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().
Referenced by mlir::computeTopologicalSorting(), and mlir::sortTopologically().