MLIR: lib/Conversion/TosaToLinalg/TosaToLinalg.cpp File Reference
TosaToLinalg.cpp File Reference
#include "mlir/Conversion/TosaToLinalg/TosaToLinalg.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Index/IR/IndexOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/Dialect/Tosa/Utils/ConversionUtils.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include <type_traits>
Typedefs
using IndexPool = DenseMap< int64_t, Value >
Functions
template<typename OpTy >
static Value materializeBinaryNanCheckIfRequired (OpTy op, PatternRewriter &rewriter, Value lhs, Value rhs, Value result)
static Value createLinalgBodyCalculationForElementwiseOp (Operation *op, ValueRange args, ArrayRef< Type > resultTypes, ConversionPatternRewriter &rewriter)
static Value createIndex (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, int64_t index)
static Value getTensorDim (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, Value tensor, int64_t index)
static OpFoldResult getOrFoldTensorDim (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, Value tensor, int64_t index)
static bool operandsAndResultsRanked (Operation *operation)
static std::pair< OpFoldResult, Value > computeTargetSize (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, ValueRange operands, int64_t dim)
static std::pair< SmallVector< OpFoldResult >, SmallVector< Value > > computeTargetShape (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, ValueRange operands)
static Value broadcastDynamicDimension (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, Value operand, int64_t dim, OpFoldResult targetSize, Value masterOperand)
static Value broadcastDynamicDimensions (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, Value operand, ArrayRef< OpFoldResult > targetShape, ArrayRef< Value > masterOperands)
static SmallVector< Value > broadcastDynamicDimensions (PatternRewriter &rewriter, Location loc, IndexPool &indexPool, ValueRange operands, ArrayRef< OpFoldResult > targetShape, ArrayRef< Value > masterOperands)
static LogicalResult emitElementwiseComputation (ConversionPatternRewriter &rewriter, Location loc, Operation *operation, ValueRange operands, ArrayRef< OpFoldResult > targetShape, const TypeConverter &converter)
static ValueRange getBroadcastableOperands (Operation *operation, ValueRange operands)
static LogicalResult elementwiseMatchAndRewriteHelper (Operation *operation, ValueRange operands, ConversionPatternRewriter &rewriter, const TypeConverter &converter)
static TypedAttr createInitialValueForReduceOp (Operation *op, Type elementTy, PatternRewriter &rewriter)
static Value createLinalgBodyCalculationForReduceOp (Operation *op, ValueRange args, Type elementTy, PatternRewriter &rewriter)
template<typename OpTy >
static LogicalResult reduceMatchAndRewriteHelper (OpTy op, uint64_t axis, PatternRewriter &rewriter)
Typedef Documentation
IndexPool
using IndexPool = DenseMap<int64_t, Value>
Definition at line 710 of file TosaToLinalg.cpp.
Function Documentation
broadcastDynamicDimension()
static Value broadcastDynamicDimension (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, Value operand, int64_t dim, OpFoldResult targetSize, Value masterOperand) static
Definition at line 816 of file TosaToLinalg.cpp.
References createIndex(), mlir::OpBuilder::createOrFold(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Builder::getMultiDimIdentityMap(), mlir::tosa::getNParallelLoopsAttrs(), getOrFoldTensorDim(), getTensorDim(), and mlir::Value::getType().
Referenced by broadcastDynamicDimensions().
broadcastDynamicDimensions() [1/2]
static Value broadcastDynamicDimensions (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, Value operand, ArrayRef< OpFoldResult > targetShape, ArrayRef< Value > masterOperands) static
Definition at line 898 of file TosaToLinalg.cpp.
References broadcastDynamicDimension(), and mlir::Value::getType().
Referenced by broadcastDynamicDimensions(), and elementwiseMatchAndRewriteHelper().
broadcastDynamicDimensions() [2/2]
static SmallVector<Value> broadcastDynamicDimensions (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, ValueRange operands, ArrayRef< OpFoldResult > targetShape, ArrayRef< Value > masterOperands) static
Definition at line 913 of file TosaToLinalg.cpp.
References broadcastDynamicDimensions().
computeTargetShape()
static std::pair<SmallVector<OpFoldResult>, SmallVector<Value> > computeTargetShape (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, ValueRange operands) static
Definition at line 801 of file TosaToLinalg.cpp.
References computeTargetSize(), and mlir::ValueRange::getType().
Referenced by elementwiseMatchAndRewriteHelper().
computeTargetSize()
static std::pair<OpFoldResult, Value> computeTargetSize (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, ValueRange operands, int64_t dim) static
Definition at line 760 of file TosaToLinalg.cpp.
References mlir::Builder::getIndexAttr(), getTensorDim(), and mlir::Value::getType().
Referenced by computeTargetShape().
createIndex()
static Value createIndex (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, int64_t index) static
Definition at line 715 of file TosaToLinalg.cpp.
References mlir::Builder::getIndexAttr().
Referenced by broadcastDynamicDimension(), and getTensorDim().
createInitialValueForReduceOp()
static TypedAttr createInitialValueForReduceOp (Operation * op, Type elementTy, PatternRewriter & rewriter) static
Definition at line 1029 of file TosaToLinalg.cpp.
References mlir::Builder::getFloatAttr(), mlir::Builder::getIntegerAttr(), mlir::Type::getIntOrFloatBitWidth(), getZero(), and mlir::Type::isInteger().
Referenced by reduceMatchAndRewriteHelper().
createLinalgBodyCalculationForElementwiseOp()
static Value createLinalgBodyCalculationForElementwiseOp (Operation * op, ValueRange args, ArrayRef< Type > resultTypes, ConversionPatternRewriter & rewriter) static
Definition at line 82 of file TosaToLinalg.cpp.
References mlir::presburger::abs(), clamp(), mlir::tosa::clampFloatHelper(), mlir::tosa::clampIntHelper(), mlir::arith::ConstantIntOp::create(), mlir::get(), mlir::Operation::getAttr(), mlir::Builder::getContext(), mlir::getElementTypeOrSelf(), mlir::Builder::getFloatAttr(), mlir::Builder::getI32Type(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Operation::getLoc(), mlir::Operation::getOperand(), mlir::Builder::getStringAttr(), mlir::Value::getType(), mlir::DenseElementsAttr::getValues(), mlir::Builder::getZeroAttr(), mlir::Type::isInteger(), mlir::Type::isIntOrFloat(), mlir::Type::isUnsignedInteger(), mlir::m_Constant(), mlir::matchPattern(), materializeBinaryNanCheckIfRequired(), max(), min(), mlir::RewriterBase::notifyMatchFailure(), and mlir::presburger::round().
Referenced by emitElementwiseComputation().
createLinalgBodyCalculationForReduceOp()
static Value createLinalgBodyCalculationForReduceOp (Operation * op, ValueRange args, Type elementTy, PatternRewriter & rewriter) static
Definition at line 1081 of file TosaToLinalg.cpp.
References mlir::Operation::getLoc(), and mlir::Type::isInteger().
Referenced by reduceMatchAndRewriteHelper().
elementwiseMatchAndRewriteHelper()
static LogicalResult elementwiseMatchAndRewriteHelper (Operation * operation, ValueRange operands, ConversionPatternRewriter & rewriter, const TypeConverter & converter) static
Definition at line 1002 of file TosaToLinalg.cpp.
References broadcastDynamicDimensions(), computeTargetShape(), emitElementwiseComputation(), getBroadcastableOperands(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::RewriterBase::notifyMatchFailure(), and operandsAndResultsRanked().
emitElementwiseComputation()
static LogicalResult emitElementwiseComputation (ConversionPatternRewriter & rewriter, Location loc, Operation * operation, ValueRange operands, ArrayRef< OpFoldResult > targetShape, const TypeConverter & converter) static
Definition at line 929 of file TosaToLinalg.cpp.
References mlir::TypeConverter::convertType(), createLinalgBodyCalculationForElementwiseOp(), mlir::OpBuilder::createOrFold(), mlir::detail::enumerate(), mlir::ValueTypeRange< ValueRangeT >::front(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Builder::getMultiDimIdentityMap(), mlir::tosa::getNParallelLoopsAttrs(), mlir::Operation::getNumOperands(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::RewriterBase::notifyMatchFailure(), and mlir::ConversionPatternRewriter::replaceOp().
Referenced by elementwiseMatchAndRewriteHelper().
getBroadcastableOperands()
static ValueRange getBroadcastableOperands (Operation * operation, ValueRange operands) static
Definition at line 990 of file TosaToLinalg.cpp.
Referenced by elementwiseMatchAndRewriteHelper().
getOrFoldTensorDim()
static OpFoldResult getOrFoldTensorDim (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, Value tensor, int64_t index) static
Definition at line 730 of file TosaToLinalg.cpp.
References mlir::Builder::getIndexAttr(), getTensorDim(), and mlir::Value::getType().
Referenced by broadcastDynamicDimension().
getTensorDim()
static Value getTensorDim (PatternRewriter & rewriter, Location loc, IndexPool & indexPool, Value tensor, int64_t index) static
Definition at line 724 of file TosaToLinalg.cpp.
References createIndex().
Referenced by broadcastDynamicDimension(), computeTargetSize(), and getOrFoldTensorDim().
materializeBinaryNanCheckIfRequired()
template<typename OpTy > static Value materializeBinaryNanCheckIfRequired (OpTy op, PatternRewriter & rewriter, Value lhs, Value rhs, Value result) static
Definition at line 61 of file TosaToLinalg.cpp.
References mlir::getElementTypeOrSelf().
Referenced by createLinalgBodyCalculationForElementwiseOp().
operandsAndResultsRanked()
static bool operandsAndResultsRanked (Operation * operation) static
Definition at line 741 of file TosaToLinalg.cpp.
References mlir::Operation::getOperands(), and mlir::Operation::getResults().
Referenced by elementwiseMatchAndRewriteHelper().
reduceMatchAndRewriteHelper()
template<typename OpTy > static LogicalResult reduceMatchAndRewriteHelper (OpTy op, uint64_t axis, PatternRewriter & rewriter) static
Definition at line 1131 of file TosaToLinalg.cpp.
References createInitialValueForReduceOp(), createLinalgBodyCalculationForReduceOp(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getBoolAttr(), mlir::Builder::getFloatAttr(), mlir::RewriterBase::notifyMatchFailure(), and mlir::RewriterBase::replaceOpWithNewOp().