MLIR: lib/Conversion/TosaToLinalg/TosaToLinalgNamed.cpp File Reference
TosaToLinalgNamed.cpp File Reference
#include "mlir/Conversion/TosaToLinalg/TosaToLinalg.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/Dialect/Tosa/Utils/ConversionUtils.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include <type_traits>
Functions
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, TypedAttr padAttr, OpBuilder &rewriter)
static mlir::Value linalgIntBroadcastExtSIAdd (PatternRewriter &rewriter, Location loc, Value bias, Value conv, Value result, ArrayRef< AffineMap > indexingMaps)
static AffineMap getBroadcastingMap (PatternRewriter &rewriter, Value source, Value result)
static mlir::Value linalgBroadcastAndMaybeExt (PatternRewriter &rewriter, Location loc, Value source, Value result)
static mlir::Value reifyConstantDim (int64_t attr, ImplicitLocOpBuilder &builder)
static mlir::Value getConvOrPoolOutputDim (Location loc, Value inputDim, int64_t padBeforeAttr, int64_t padAfterAttr, Value kernelDim, int64_t strideAttr, int64_t dilationAttr, OpBuilder &rewriter)
static SmallVector< Value > inferDynamicDimsForConv (Location loc, Value input, Value weight, ShapedType resultTy, ArrayRef< int64_t > padAttr, ArrayRef< int64_t > strideAttr, ArrayRef< int64_t > dilationAttr, ArrayRef< int64_t > inputSizeDims, ArrayRef< int64_t > kernelSizeDims, OpBuilder &rewriter)
static void createDepthwiseConvCollapseMap (int64_t outputRank, SmallVector< ReassociationExprs, 4 > &reassociationMap, OpBuilder &rewriter)
Function Documentation
applyPad()
mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, TypedAttr padAttr, OpBuilder & rewriter) static
Definition at line 29 of file TosaToLinalgNamed.cpp.
References mlir::Builder::getIndexAttr(), and mlir::Value::getType().
createDepthwiseConvCollapseMap()
void createDepthwiseConvCollapseMap (int64_t outputRank, SmallVector< ReassociationExprs, 4 > & reassociationMap, OpBuilder & rewriter) static
Definition at line 224 of file TosaToLinalgNamed.cpp.
References mlir::Builder::getAffineDimExpr().
getBroadcastingMap()
AffineMap getBroadcastingMap (PatternRewriter & rewriter, Value source, Value result) static
Definition at line 86 of file TosaToLinalgNamed.cpp.
References mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Value::getType(), and result.
Referenced by linalgBroadcastAndMaybeExt().
getConvOrPoolOutputDim()
mlir::Value getConvOrPoolOutputDim (Location loc, Value inputDim, int64_t padBeforeAttr, int64_t padAfterAttr, Value kernelDim, int64_t strideAttr, int64_t dilationAttr, OpBuilder & rewriter) static
Definition at line 157 of file TosaToLinalgNamed.cpp.
References mlir::Value::getType(), and reifyConstantDim().
Referenced by inferDynamicDimsForConv().
inferDynamicDimsForConv()
SmallVector< Value > inferDynamicDimsForConv (Location loc, Value input, Value weight, ShapedType resultTy, ArrayRef< int64_t > padAttr, ArrayRef< int64_t > strideAttr, ArrayRef< int64_t > dilationAttr, ArrayRef< int64_t > inputSizeDims, ArrayRef< int64_t > kernelSizeDims, OpBuilder & rewriter) static
Definition at line 183 of file TosaToLinalgNamed.cpp.
References mlir::tosa::condenseValues(), getConvOrPoolOutputDim(), and mlir::Value::getType().
linalgBroadcastAndMaybeExt()
mlir::Value linalgBroadcastAndMaybeExt (PatternRewriter & rewriter, Location loc, Value source, Value result) static
Definition at line 117 of file TosaToLinalgNamed.cpp.
References getBroadcastingMap(), mlir::Builder::getMultiDimIdentityMap(), mlir::tosa::getNParallelLoopsAttrs(), mlir::Value::getType(), result, and ValueRange.
linalgIntBroadcastExtSIAdd()
mlir::Value linalgIntBroadcastExtSIAdd (PatternRewriter & rewriter, Location loc, Value bias, Value conv, Value result, ArrayRef< AffineMap > indexingMaps) static
Definition at line 63 of file TosaToLinalgNamed.cpp.
References mlir::tosa::getNParallelLoopsAttrs(), mlir::Value::getType(), result, and ValueRange.
reifyConstantDim()
mlir::Value reifyConstantDim (int64_t attr, ImplicitLocOpBuilder & builder) static
Definition at line 148 of file TosaToLinalgNamed.cpp.
References mlir::arith::ConstantIndexOp::create().
Referenced by getConvOrPoolOutputDim().