MLIR: lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp File Reference
TosaCanonicalizations.cpp File Reference
#include "mlir/Dialect/Quant/IR/Quant.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/IR/TargetEnv.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/Dialect/Tosa/Utils/ConversionUtils.h"
#include "mlir/Dialect/Tosa/Utils/QuantUtils.h"
#include "mlir/Dialect/Traits.h"
#include "mlir/IR/BuiltinTypeInterfaces.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include <functional>
Classes
struct AvgPool2dAdaptiveToAvgPool2d
struct AvgPool2dIsNoOp
struct MaxPool2dIsNoOp
struct MaxPool2dAdaptiveToMaxPool2d
struct ConcatOptimization
struct ConsecutiveConcatOptimization
struct ConsolidateTransposeOptimization
struct TransposeIsReshape
struct ClampIsNoOp
struct ClampClampOptimization
struct ClampClampOptimization::ClampRange< T >
struct ConcatSliceOptimization
struct PadSliceOptimization
struct SliceDynamicSizeCanonicalization
struct NonNarrowingCastsOptimization
struct CancellingBlockScaledCastsOptimization
struct RowGatherToGather
struct AddFoldAdaptor
struct SubFoldAdaptor
struct MulFoldAdaptor
struct DivFoldAdaptor< Ceil >
struct ModFoldAdaptor
struct MaxFoldAdaptor
struct MinFoldAdaptor
struct Exp2FoldAdaptor
struct ShapeDivFoldAdaptor< Ceil >
struct Log2CeilFoldAdaptor
struct Log2FloorFoldAdaptor
struct GreaterFoldAdaptor
struct GreaterEqualFoldAdaptor
struct EqualFoldAdaptor
Macros
#define REDUCE_FOLDER(OP)
Functions
static bool checkMatchingPadConstAndZp (Value padConst, Value zp)
template<typename Folder>
static DenseElementsAttr binaryFolder (DenseElementsAttr lhs, DenseElementsAttr rhs, ShapedType returnTy, bool foldDenseValues=false)
template<typename Folder>
static DenseElementsAttr unaryFolder (DenseElementsAttr val, ShapedType returnTy, bool foldDenseValues=false)
static FailureOr< int64_t > getSingleI64From1ElementTensor (Value v)
static bool signsDiffer (const APInt &a, const APInt &b)
static bool isSplatZero (Type elemType, DenseElementsAttr val)
static bool isSplatOne (Type elemType, DenseElementsAttr val, int64_t shift)
template<typename Op, typename OpFoldAdaptor>
OpFoldResult unaryShapeFold (Op *op)
template<typename Op, typename OpFoldAdaptor>
OpFoldResult binaryFold (Op *op)
OpFoldResult concatShapeFold (tosa::ConcatShapeOp *op)
OpFoldResult sliceShapeFold (tosa::SliceShapeOp *op)
Macro Definition Documentation
REDUCE_FOLDER
#define REDUCE_FOLDER (OP)
Value:
  OpFoldResult OP::fold(FoldAdaptor adaptor) {                                 \
    ShapedType inputTy = llvm::cast<ShapedType>(getInput().getType());         \
    if (!inputTy.hasRank())                                                    \
      return {};                                                               \
    if (inputTy != getType())                                                  \
      return {};                                                               \
    if (inputTy.getRank() == 0 || inputTy.getDimSize(getAxis()) == 1)          \
      return getInput();                                                       \
    return {};                                                                 \
  }
Definition at line 2032 of file TosaCanonicalizations.cpp.
Function Documentation
binaryFold()
template<typename Op, typename OpFoldAdaptor> OpFoldResult binaryFold (Op * op)
Definition at line 2405 of file TosaCanonicalizations.cpp.
References binaryFolder().
binaryFolder()
template<typename Folder> DenseElementsAttr binaryFolder (DenseElementsAttr lhs, DenseElementsAttr rhs, ShapedType returnTy, bool foldDenseValues = false) static
Definition at line 1319 of file TosaCanonicalizations.cpp.
References mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getElementType(), lhs, and rhs.
Referenced by binaryFold().
checkMatchingPadConstAndZp()
bool checkMatchingPadConstAndZp (Value padConst, Value zp) static
Definition at line 50 of file TosaCanonicalizations.cpp.
References mlir::DenseIntElementsAttr::begin(), mlir::m_Constant(), mlir::matchPattern(), and mlir::DenseElementsAttr::size().
concatShapeFold()
OpFoldResult concatShapeFold (tosa::ConcatShapeOp * op)
Definition at line 2436 of file TosaCanonicalizations.cpp.
References mlir::DenseElementsAttr::get().
getSingleI64From1ElementTensor()
FailureOr< int64_t > getSingleI64From1ElementTensor (Value v) static
Definition at line 1408 of file TosaCanonicalizations.cpp.
References mlir::m_Constant(), and mlir::matchPattern().
Referenced by sliceShapeFold().
isSplatOne()
bool isSplatOne (Type elemType, DenseElementsAttr val, int64_t shift) static
Definition at line 1665 of file TosaCanonicalizations.cpp.
References mlir::DenseElementsAttr::getSplatValue(), and mlir::DenseElementsAttr::isSplat().
isSplatZero()
bool isSplatZero (Type elemType, DenseElementsAttr val) static
Definition at line 1657 of file TosaCanonicalizations.cpp.
References mlir::DenseElementsAttr::getSplatValue(), and mlir::DenseElementsAttr::isSplat().
signsDiffer()
bool signsDiffer (const APInt & a, const APInt & b) static
Definition at line 1480 of file TosaCanonicalizations.cpp.
References b.
Referenced by DivFoldAdaptor< Ceil >::fold().
sliceShapeFold()
OpFoldResult sliceShapeFold (tosa::SliceShapeOp * op)
Definition at line 2466 of file TosaCanonicalizations.cpp.
References mlir::DenseElementsAttr::get(), and getSingleI64From1ElementTensor().
unaryFolder()
template<typename Folder> DenseElementsAttr unaryFolder (DenseElementsAttr val, ShapedType returnTy, bool foldDenseValues = false) static
Definition at line 1370 of file TosaCanonicalizations.cpp.
References mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getElementType(), mlir::DenseElementsAttr::getSplatValue(), mlir::DenseElementsAttr::getType(), mlir::DenseElementsAttr::getValues(), mlir::Type::isIntOrIndex(), and mlir::DenseElementsAttr::isSplat().
Referenced by unaryShapeFold().
unaryShapeFold()
template<typename Op, typename OpFoldAdaptor> OpFoldResult unaryShapeFold (Op * op)
Definition at line 2392 of file TosaCanonicalizations.cpp.
References unaryFolder().