MLIR: lib/Conversion/TosaToSCF/TosaToSCF.cpp File Reference
TosaToSCF.cpp File Reference
#include "mlir/Conversion/TosaToSCF/TosaToSCF.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
Functions
static void inlineIfCase (Region &srcRegion, Region &dstRegion, OperandRange operands, PatternRewriter &rewriter)
static void inlineWhileCase (Region &srcRegion, Region &dstRegion, PatternRewriter &rewriter, bool isCond)
Function Documentation
inlineIfCase()
static void inlineIfCase (Region & srcRegion, Region & dstRegion, OperandRange operands, PatternRewriter & rewriter) static
Definition at line 24 of file TosaToSCF.cpp.
References mlir::Region::back(), mlir::RewriterBase::cloneRegionBefore(), mlir::OpBuilder::create(), mlir::Block::eraseArguments(), mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), mlir::Region::front(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getTerminator(), and mlir::OpBuilder::setInsertionPoint().
Referenced by inlineWhileCase().
inlineWhileCase()
static void inlineWhileCase (Region & srcRegion, Region & dstRegion, PatternRewriter & rewriter, bool isCond) static
Definition at line 42 of file TosaToSCF.cpp.
References mlir::Region::back(), mlir::RewriterBase::cloneRegionBefore(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), mlir::Region::front(), mlir::Block::getArguments(), mlir::Block::getTerminator(), inlineIfCase(), op, mlir::RewriterBase::replaceOp(), rewriter, mlir::OpBuilder::setInsertionPoint(), and mlir::success().