MLIR: lib/Target/Cpp/TranslateToCpp.cpp File Reference
TranslateToCpp.cpp File Reference
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/EmitC/IR/EmitC.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/IndentedOstream.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/Cpp/CppEmitter.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include <stack>
Macros
#define DEBUG_TYPE "translate-to-cpp"
Functions
template<typename ForwardIterator, typename UnaryFunctor, typename NullaryFunctor>
static LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn)
Convenience functions to produce interleaved output with functions returning a LogicalResult.
template<typename Container, typename UnaryFunctor, typename NullaryFunctor>
static LogicalResult interleaveWithError (const Container &c, UnaryFunctor eachFn, NullaryFunctor betweenFn)
template<typename Container, typename UnaryFunctor>
static LogicalResult interleaveCommaWithError (const Container &c, raw_ostream &os, UnaryFunctor eachFn)
static FailureOr< int > getOperatorPrecedence (Operation *operation)
Return the precedence of a operator as an integer, higher values imply higher precedence.
static bool shouldBeInlined (Operation *op)
Determine whether operation op should be emitted inline, i.e.
static bool hasDeferredEmission (Operation *op)
Determine whether expression op should be emitted in a deferred way.
static LogicalResult printOperation (CppEmitter &emitter, emitc::DereferenceOp dereferenceOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::GetFieldOp getFieldOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::GetGlobalOp getGlobalOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::LiteralOp literalOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::MemberOp memberOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::MemberOfPtrOp memberOfPtrOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::SubscriptOp subscriptOp)
static LogicalResult printConstantOp (CppEmitter &emitter, Operation *operation, Attribute value)
static LogicalResult printOperation (CppEmitter &emitter, emitc::AddressOfOp addressOfOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::VariableOp variableOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::GlobalOp globalOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::AssignOp assignOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::LoadOp loadOp)
static LogicalResult printBinaryOperation (CppEmitter &emitter, Operation *operation, StringRef binaryOperator)
static LogicalResult printUnaryOperation (CppEmitter &emitter, Operation *operation, StringRef unaryOperator)
static LogicalResult printOperation (CppEmitter &emitter, emitc::AddOp addOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::DivOp divOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::MulOp mulOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::RemOp remOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::SubOp subOp)
static LogicalResult emitSwitchCase (CppEmitter &emitter, raw_indented_ostream &os, Region &region)
static LogicalResult printOperation (CppEmitter &emitter, emitc::SwitchOp switchOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::DoOp doOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CmpOp cmpOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ConditionalOp conditionalOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::VerbatimOp verbatimOp)
static LogicalResult printOperation (CppEmitter &emitter, cf::BranchOp branchOp)
static LogicalResult printOperation (CppEmitter &emitter, cf::CondBranchOp condBranchOp)
static LogicalResult printCallOperation (CppEmitter &emitter, Operation *callOp, StringRef callee)
static LogicalResult printOperation (CppEmitter &emitter, func::CallOp callOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CallOp callOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CallOpaqueOp callOpaqueOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ApplyOp applyOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::BitwiseAndOp bitwiseAndOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::BitwiseLeftShiftOp bitwiseLeftShiftOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::BitwiseNotOp bitwiseNotOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::BitwiseOrOp bitwiseOrOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::BitwiseRightShiftOp bitwiseRightShiftOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::BitwiseXorOp bitwiseXorOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::UnaryPlusOp unaryPlusOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::UnaryMinusOp unaryMinusOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CastOp castOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ExpressionOp expressionOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::IncludeOp includeOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::LogicalAndOp logicalAndOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::LogicalNotOp logicalNotOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::LogicalOrOp logicalOrOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ForOp forOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::IfOp ifOp)
static LogicalResult printOperation (CppEmitter &emitter, func::ReturnOp returnOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ReturnOp returnOp)
static LogicalResult printOperation (CppEmitter &emitter, ModuleOp moduleOp)
static LogicalResult printOperation (CppEmitter &emitter, ClassOp classOp)
static LogicalResult printOperation (CppEmitter &emitter, FieldOp fieldOp)
static LogicalResult printOperation (CppEmitter &emitter, FileOp file)
static LogicalResult printFunctionArgs (CppEmitter &emitter, Operation *functionOp, ArrayRef< Type > arguments)
static LogicalResult printFunctionArgs (CppEmitter &emitter, Operation *functionOp, Region::BlockArgListType arguments)
static LogicalResult printFunctionBody (CppEmitter &emitter, Operation *functionOp, Region::BlockListType &blocks)
static LogicalResult printOperation (CppEmitter &emitter, func::FuncOp functionOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::FuncOp functionOp)
static LogicalResult printOperation (CppEmitter &emitter, DeclareFuncOp declareFuncOp)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "translate-to-cpp"
Definition at line 28 of file TranslateToCpp.cpp.
Function Documentation
emitSwitchCase()
LogicalResult emitSwitchCase (CppEmitter & emitter, raw_indented_ostream & os, Region & region) static
Definition at line 617 of file TranslateToCpp.cpp.
References mlir::Region::op_begin(), mlir::Region::op_end(), and success().
Referenced by printOperation().
getOperatorPrecedence()
FailureOr< int > getOperatorPrecedence (Operation * operation) static
Return the precedence of a operator as an integer, higher values imply higher precedence.
Definition at line 71 of file TranslateToCpp.cpp.
hasDeferredEmission()
bool hasDeferredEmission (Operation * op) static
Determine whether expression op should be emitted in a deferred way.
Definition at line 335 of file TranslateToCpp.cpp.
Referenced by shouldBeInlined().
interleaveCommaWithError()
template<typename Container, typename UnaryFunctor> LogicalResult interleaveCommaWithError (const Container & c, raw_ostream & os, UnaryFunctor eachFn) inline static
Definition at line 63 of file TranslateToCpp.cpp.
References interleaveWithError().
Referenced by printFunctionArgs(), printFunctionArgs(), and printOperation().
interleaveWithError() [1/2]
template<typename Container, typename UnaryFunctor, typename NullaryFunctor> LogicalResult interleaveWithError (const Container & c, UnaryFunctor eachFn, NullaryFunctor betweenFn) inline static
Definition at line 56 of file TranslateToCpp.cpp.
References interleaveWithError().
interleaveWithError() [2/2]
template<typename ForwardIterator, typename UnaryFunctor, typename NullaryFunctor> LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn) inline static
Convenience functions to produce interleaved output with functions returning a LogicalResult.
This is different than those in STLExtras as functions used on each element doesn't return a string.
Definition at line 40 of file TranslateToCpp.cpp.
References success().
Referenced by interleaveCommaWithError(), and interleaveWithError().
printBinaryOperation()
LogicalResult printBinaryOperation (CppEmitter & emitter, Operation * operation, StringRef binaryOperator) static
Definition at line 552 of file TranslateToCpp.cpp.
References mlir::Operation::getOperand(), and success().
Referenced by printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), printOperation(), and printOperation().
printCallOperation()
LogicalResult printCallOperation (CppEmitter & emitter, Operation * callOp, StringRef callee) static
Definition at line 827 of file TranslateToCpp.cpp.
References success().
Referenced by printOperation(), and printOperation().
printConstantOp()
LogicalResult printConstantOp (CppEmitter & emitter, Operation * operation, Attribute value) static
Definition at line 467 of file TranslateToCpp.cpp.
References mlir::Operation::getLoc(), mlir::Operation::getResult(), result, and success().
Referenced by printOperation(), and printOperation().
printFunctionArgs() [1/2]
LogicalResult printFunctionArgs (CppEmitter & emitter, Operation * functionOp, ArrayRef< Type > arguments) static
Definition at line 1205 of file TranslateToCpp.cpp.
References mlir::Operation::getLoc(), and interleaveCommaWithError().
Referenced by printOperation(), printOperation(), and printOperation().
printFunctionArgs() [2/2]
LogicalResult printFunctionArgs (CppEmitter & emitter, Operation * functionOp, Region::BlockArgListType arguments) static
Definition at line 1216 of file TranslateToCpp.cpp.
References mlir::Operation::getLoc(), mlir::Value::getType(), and interleaveCommaWithError().
printFunctionBody()
LogicalResult printFunctionBody (CppEmitter & emitter, Operation * functionOp, Region::BlockListType & blocks) static
Definition at line 1228 of file TranslateToCpp.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::Operation::getParentOp(), mlir::Operation::getResults(), mlir::raw_indented_ostream::indent(), mlir::PreOrder, result, shouldBeInlined(), mlir::WalkResult::skip(), success(), mlir::raw_indented_ostream::unindent(), and mlir::Operation::walk().
Referenced by printOperation(), and printOperation().
printOperation() [1/54]
LogicalResult printOperation (CppEmitter & emitter, cf::BranchOp branchOp) static
Definition at line 759 of file TranslateToCpp.cpp.
References mlir::Block::getArguments(), mlir::Block::getSuccessor(), and success().
printOperation() [2/54]
LogicalResult printOperation (CppEmitter & emitter, cf::CondBranchOp condBranchOp) static
Definition at line 779 of file TranslateToCpp.cpp.
References mlir::Block::getArguments(), mlir::raw_indented_ostream::indent(), success(), and mlir::raw_indented_ostream::unindent().
printOperation() [3/54]
LogicalResult printOperation (CppEmitter & emitter, ClassOp classOp) static
Definition at line 1160 of file TranslateToCpp.cpp.
References mlir::raw_indented_ostream::indent(), success(), and mlir::raw_indented_ostream::unindent().
printOperation() [4/54]
LogicalResult printOperation (CppEmitter & emitter, DeclareFuncOp declareFuncOp) static
Definition at line 1373 of file TranslateToCpp.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom(), printFunctionArgs(), and success().
printOperation() [5/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::AddOp addOp) static
Definition at line 587 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [6/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::AddressOfOp addressOfOp) static
Definition at line 499 of file TranslateToCpp.cpp.
printOperation() [7/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::ApplyOp applyOp) static
Definition at line 906 of file TranslateToCpp.cpp.
printOperation() [8/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::AssignOp assignOp) static
Definition at line 535 of file TranslateToCpp.cpp.
References result.
printOperation() [9/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::BitwiseAndOp bitwiseAndOp) static
Definition at line 917 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [10/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::BitwiseLeftShiftOp bitwiseLeftShiftOp) static
Definition at line 924 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [11/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::BitwiseNotOp bitwiseNotOp) static
Definition at line 930 of file TranslateToCpp.cpp.
References printUnaryOperation().
printOperation() [12/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::BitwiseOrOp bitwiseOrOp) static
Definition at line 936 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [13/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::BitwiseRightShiftOp bitwiseRightShiftOp) static
Definition at line 943 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [14/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::BitwiseXorOp bitwiseXorOp) static
Definition at line 949 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [15/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::CallOp callOp) static
Definition at line 847 of file TranslateToCpp.cpp.
References printCallOperation().
printOperation() [16/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::CallOpaqueOp callOpaqueOp) static
Definition at line 854 of file TranslateToCpp.cpp.
References mlir::Operation::getLoc(), mlir::Operation::getOperand(), interleaveCommaWithError(), and success().
printOperation() [17/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::CastOp castOp) static
Definition at line 967 of file TranslateToCpp.cpp.
References mlir::Operation::getLoc(), mlir::Operation::getResult(), and mlir::Value::getType().
printOperation() [18/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::CmpOp cmpOp) static
Definition at line 681 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [19/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::ConditionalOp conditionalOp) static
Definition at line 713 of file TranslateToCpp.cpp.
References success().
printOperation() [20/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::ConstantOp constantOp) static
Definition at line 510 of file TranslateToCpp.cpp.
References mlir::Operation::getLoc(), and printConstantOp().
printOperation() [21/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::DereferenceOp dereferenceOp) static
Definition at line 407 of file TranslateToCpp.cpp.
References success().
printOperation() [22/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::DivOp divOp) static
Definition at line 593 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [23/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::DoOp doOp) static
Definition at line 657 of file TranslateToCpp.cpp.
References mlir::Block::back(), mlir::Block::front(), mlir::raw_indented_ostream::indent(), success(), and mlir::raw_indented_ostream::unindent().
printOperation() [24/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::ExpressionOp expressionOp) static
Definition at line 980 of file TranslateToCpp.cpp.
References shouldBeInlined(), and success().
printOperation() [25/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::ForOp forOp) static
Definition at line 1024 of file TranslateToCpp.cpp.
References mlir::Value::getDefiningOp(), mlir::Region::getOps(), mlir::raw_indented_ostream::indent(), shouldBeInlined(), success(), and mlir::raw_indented_ostream::unindent().
printOperation() [26/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::FuncOp functionOp) static
Definition at line 1332 of file TranslateToCpp.cpp.
References printFunctionArgs(), printFunctionBody(), and success().
printOperation() [27/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::GetFieldOp getFieldOp) static
Definition at line 416 of file TranslateToCpp.cpp.
References success().
printOperation() [28/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::GetGlobalOp getGlobalOp) static
Definition at line 423 of file TranslateToCpp.cpp.
References success().
printOperation() [29/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::GlobalOp globalOp) static
Definition at line 529 of file TranslateToCpp.cpp.
printOperation() [30/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::IfOp ifOp) static
Definition at line 1081 of file TranslateToCpp.cpp.
References mlir::Region::empty(), mlir::raw_indented_ostream::indent(), success(), and mlir::raw_indented_ostream::unindent().
printOperation() [31/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::IncludeOp includeOp) static
Definition at line 993 of file TranslateToCpp.cpp.
References success().
printOperation() [32/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::LiteralOp literalOp) static
Definition at line 429 of file TranslateToCpp.cpp.
References success().
printOperation() [33/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::LoadOp loadOp) static
Definition at line 545 of file TranslateToCpp.cpp.
printOperation() [34/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::LogicalAndOp logicalAndOp) static
Definition at line 1006 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [35/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::LogicalNotOp logicalNotOp) static
Definition at line 1012 of file TranslateToCpp.cpp.
References printUnaryOperation().
printOperation() [36/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::LogicalOrOp logicalOrOp) static
Definition at line 1018 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [37/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::MemberOfPtrOp memberOfPtrOp) static
Definition at line 445 of file TranslateToCpp.cpp.
References success().
printOperation() [38/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::MemberOp memberOp) static
Definition at line 435 of file TranslateToCpp.cpp.
References success().
printOperation() [39/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::MulOp mulOp) static
Definition at line 599 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [40/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::RemOp remOp) static
Definition at line 605 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [41/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::ReturnOp returnOp) static
Definition at line 1139 of file TranslateToCpp.cpp.
References success().
printOperation() [42/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::SubOp subOp) static
Definition at line 611 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [43/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::SubscriptOp subscriptOp) static
Definition at line 455 of file TranslateToCpp.cpp.
References success().
printOperation() [44/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::SwitchOp switchOp) static
Definition at line 628 of file TranslateToCpp.cpp.
References emitSwitchCase(), mlir::raw_indented_ostream::indent(), success(), and mlir::raw_indented_ostream::unindent().
printOperation() [45/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::UnaryMinusOp unaryMinusOp) static
Definition at line 961 of file TranslateToCpp.cpp.
References printUnaryOperation().
printOperation() [46/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::UnaryPlusOp unaryPlusOp) static
Definition at line 955 of file TranslateToCpp.cpp.
References printUnaryOperation().
printOperation() [47/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::VariableOp variableOp) static
Definition at line 521 of file TranslateToCpp.cpp.
References printConstantOp().
printOperation() [48/54]
LogicalResult printOperation (CppEmitter & emitter, emitc::VerbatimOp verbatimOp) static
Definition at line 736 of file TranslateToCpp.cpp.
References success().
printOperation() [49/54]
LogicalResult printOperation (CppEmitter & emitter, FieldOp fieldOp) static
Definition at line 1178 of file TranslateToCpp.cpp.
References success().
printOperation() [50/54]
LogicalResult printOperation (CppEmitter & emitter, FileOp file) static
Definition at line 1194 of file TranslateToCpp.cpp.
References success().
printOperation() [51/54]
LogicalResult printOperation (CppEmitter & emitter, func::CallOp callOp) static
Definition at line 840 of file TranslateToCpp.cpp.
References printCallOperation().
printOperation() [52/54]
LogicalResult printOperation (CppEmitter & emitter, func::FuncOp functionOp) static
Definition at line 1295 of file TranslateToCpp.cpp.
References printFunctionArgs(), printFunctionBody(), and success().
printOperation() [53/54]
LogicalResult printOperation (CppEmitter & emitter, func::ReturnOp returnOp) static
Definition at line 1118 of file TranslateToCpp.cpp.
References success().
printOperation() [54/54]
LogicalResult printOperation (CppEmitter & emitter, ModuleOp moduleOp) static
Definition at line 1152 of file TranslateToCpp.cpp.
References success().
printUnaryOperation()
LogicalResult printUnaryOperation (CppEmitter & emitter, Operation * operation, StringRef unaryOperator) static
Definition at line 571 of file TranslateToCpp.cpp.
References mlir::Operation::getOperand(), and success().
Referenced by printOperation(), printOperation(), printOperation(), and printOperation().
shouldBeInlined()
bool shouldBeInlined (Operation * op) static
Determine whether operation op should be emitted inline, i.e.
as part of its user. This function recommends inlining of any expressions that can be inlined unless it is used by another expression, under the assumption that any expression fusion/re-materialization was taken care of by transformations run by the backend.
Definition at line 347 of file TranslateToCpp.cpp.
References mlir::Operation::getParentOp(), hasDeferredEmission(), and result.
Referenced by printFunctionBody(), printOperation(), and printOperation().