MLIR: include/mlir-c/Dialect/Transform.h File Reference
Transform.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Transform, transform)
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformAnyOpType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformAnyOpTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirTransformAnyOpTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformAnyParamType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformAnyParamTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirTransformAnyParamTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformAnyValueType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformAnyValueTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirTransformAnyValueTypeGet (MlirContext ctx)
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformOperationType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformOperationTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirTransformOperationTypeGet (MlirContext ctx, MlirStringRef operationName)
MLIR_CAPI_EXPORTED MlirStringRef mlirTransformOperationTypeGetOperationName (MlirType type)
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformParamType (MlirType type)
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformParamTypeGetTypeID (void)
MLIR_CAPI_EXPORTED MlirType mlirTransformParamTypeGet (MlirContext ctx, MlirType type)
MLIR_CAPI_EXPORTED MlirType mlirTransformParamTypeGetType (MlirType type)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Transform , transform)
mlirTransformAnyOpTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTransformAnyOpTypeGet (MlirContext ctx)
Definition at line 32 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformAnyOpTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformAnyOpTypeGetTypeID (void)
Definition at line 28 of file Transform.cpp.
References wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformAnyParamTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTransformAnyParamTypeGet (MlirContext ctx)
Definition at line 48 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformAnyParamTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformAnyParamTypeGetTypeID (void)
Definition at line 44 of file Transform.cpp.
References wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformAnyValueTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTransformAnyValueTypeGet (MlirContext ctx)
Definition at line 64 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformAnyValueTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformAnyValueTypeGetTypeID (void)
Definition at line 60 of file Transform.cpp.
References wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformOperationTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTransformOperationTypeGet (MlirContext ctx, MlirStringRef operationName)
Definition at line 80 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformOperationTypeGetOperationName()
MLIR_CAPI_EXPORTED MlirStringRef mlirTransformOperationTypeGetOperationName (MlirType type)
Definition at line 86 of file Transform.cpp.
References unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformOperationTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformOperationTypeGetTypeID (void)
Definition at line 76 of file Transform.cpp.
References wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformParamTypeGet()
MLIR_CAPI_EXPORTED MlirType mlirTransformParamTypeGet (MlirContext ctx, MlirType type)
Definition at line 102 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformParamTypeGetType()
MLIR_CAPI_EXPORTED MlirType mlirTransformParamTypeGetType (MlirType type)
Definition at line 106 of file Transform.cpp.
References mlir::getType(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformParamTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID mlirTransformParamTypeGetTypeID (void)
Definition at line 98 of file Transform.cpp.
References wrap().
Referenced by populateDialectTransformSubmodule().
mlirTypeIsATransformAnyOpType()
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformAnyOpType (MlirType type)
Referenced by populateDialectTransformSubmodule().
mlirTypeIsATransformAnyParamType()
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformAnyParamType (MlirType type)
Definition at line 40 of file Transform.cpp.
References unwrap().
Referenced by populateDialectTransformSubmodule().
mlirTypeIsATransformAnyValueType()
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformAnyValueType (MlirType type)
Definition at line 56 of file Transform.cpp.
References unwrap().
Referenced by populateDialectTransformSubmodule().
mlirTypeIsATransformOperationType()
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformOperationType (MlirType type)
Definition at line 72 of file Transform.cpp.
References unwrap().
Referenced by populateDialectTransformSubmodule().
mlirTypeIsATransformParamType()
MLIR_CAPI_EXPORTED bool mlirTypeIsATransformParamType (MlirType type)
Definition at line 94 of file Transform.cpp.
References unwrap().
Referenced by populateDialectTransformSubmodule().