MLIR: lib/Dialect/Transform/Transforms/TransformInterpreterUtils.cpp File Reference
TransformInterpreterUtils.cpp File Reference
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/IR/Utils.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Verifier.h"
#include "mlir/IR/Visitors.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "transform-dialect-interpreter-utils"
#define DBGS()
Functions
static transform::TransformOpInterface findTransformEntryPointNonRecursive (Operation *op, StringRef entryPoint)
static transform::TransformOpInterface findTransformEntryPointRecursive (Operation *op, StringRef entryPoint)
static transform::TransformOpInterface findTransformEntryPointInOp (Operation *op, StringRef entryPoint)
Macro Definition Documentation
DBGS
#define DBGS ()
Value:
(llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 32 of file TransformInterpreterUtils.cpp.
Referenced by mlir::transform::applyTransformNamedSequence(), mlir::transform::detail::expandPathsToMLIRFiles(), and mlir::transform::detail::parseTransformModuleFromFile().
DEBUG_TYPE
#define DEBUG_TYPE "transform-dialect-interpreter-utils"
Definition at line 31 of file TransformInterpreterUtils.cpp.
Function Documentation
findTransformEntryPointInOp()
transform::TransformOpInterface findTransformEntryPointInOp (Operation * op, StringRef entryPoint) static
Definition at line 190 of file TransformInterpreterUtils.cpp.
References findTransformEntryPointNonRecursive(), and findTransformEntryPointRecursive().
Referenced by mlir::transform::detail::findTransformEntryPoint().
findTransformEntryPointNonRecursive()
transform::TransformOpInterface findTransformEntryPointNonRecursive (Operation * op, StringRef entryPoint) static
Definition at line 125 of file TransformInterpreterUtils.cpp.
References mlir::Operation::getRegions().
Referenced by findTransformEntryPointInOp().
findTransformEntryPointRecursive()
transform::TransformOpInterface findTransformEntryPointRecursive (Operation * op, StringRef entryPoint) static
Definition at line 140 of file TransformInterpreterUtils.cpp.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), mlir::PreOrder, and mlir::Operation::walk().
Referenced by findTransformEntryPointInOp().