MLIR: lib/Dialect/Transform/TuneExtension/TuneExtensionOps.cpp File Reference
TuneExtensionOps.cpp File Reference
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Transform/TuneExtension/TuneExtensionOps.h"
#include "mlir/Dialect/Transform/TuneExtension/TuneExtensionOps.cpp.inc"
Macros
#define GET_OP_CLASSES
#define DEBUG_TYPE "transform-tune"
#define DBGS()
Functions
static ParseResult parseAlternativesOpSelectedRegion (OpAsmParser &parser, IntegerAttr &selectedRegionAttr, std::optional< OpAsmParser::UnresolvedOperand > &selectedRegionParam)
static void printAlternativesOpSelectedRegion (OpAsmPrinter &printer, Operation *op, IntegerAttr selectedRegionAttr, Value selectedRegionParam)
Macro Definition Documentation
DBGS
#define DBGS ()
Value:
(llvm::dbgs() << "[" DEBUG_TYPE "] ")
Definition at line 32 of file TuneExtensionOps.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "transform-tune"
Definition at line 31 of file TuneExtensionOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 28 of file TuneExtensionOps.cpp.
Function Documentation
parseAlternativesOpSelectedRegion()
ParseResult parseAlternativesOpSelectedRegion (OpAsmParser & parser, IntegerAttr & selectedRegionAttr, std::optional< OpAsmParser::UnresolvedOperand > & selectedRegionParam) static
Definition at line 77 of file TuneExtensionOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getIndexAttr(), mlir::OptionalParseResult::has_value(), mlir::AsmParser::parseOptionalInteger(), mlir::OpAsmParser::parseOptionalOperand(), and success().
printAlternativesOpSelectedRegion()
void printAlternativesOpSelectedRegion (OpAsmPrinter & printer, Operation * op, IntegerAttr selectedRegionAttr, Value selectedRegionParam) static
Definition at line 105 of file TuneExtensionOps.cpp.