MLIR: lib/IR/Unit.cpp File Reference
Unit.cpp File Reference
#include "mlir/IR/Unit.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/Region.h"
#include "llvm/Support/raw_ostream.h"
#include <iterator>
Functions
static void printOp (llvm::raw_ostream &os, Operation *op, OpPrintingFlags &flags)
static void printRegion (llvm::raw_ostream &os, Region *region, OpPrintingFlags &flags)
static void printBlock (llvm::raw_ostream &os, Block *block, OpPrintingFlags &flags)
Function Documentation
printBlock()
static void printBlock (llvm::raw_ostream & os, Block * block, OpPrintingFlags & flags) static
Definition at line 37 of file Unit.cpp.
References mlir::Region::front(), mlir::Block::getParent(), mlir::Block::print(), printRegion(), mlir::OpPrintingFlags::shouldSkipRegions(), and mlir::OpPrintingFlags::skipRegions().
Referenced by mlir::IRUnit::print().
printOp()
static void printOp (llvm::raw_ostream & os, Operation * op, OpPrintingFlags & flags) static
Definition at line 18 of file Unit.cpp.
References mlir::Operation::print().
Referenced by mlir::IRUnit::print(), and printRegion().
printRegion()
static void printRegion (llvm::raw_ostream & os, Region * region, OpPrintingFlags & flags) static
Definition at line 27 of file Unit.cpp.
References mlir::Region::getParentOp(), mlir::Region::getRegionNumber(), and printOp().
Referenced by mlir::IRUnit::print(), and printBlock().