MLIR: lib/Interfaces/ValueBoundsOpInterface.cpp File Reference
ValueBoundsOpInterface.cpp File Reference
#include <utility>
#include "mlir/Interfaces/ValueBoundsOpInterface.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Interfaces/DestinationStyleOpInterface.h"
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugLog.h"
#include "mlir/Interfaces/ValueBoundsOpInterface.cpp.inc"
Namespaces
namespace mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "value-bounds-op-interface"
Functions
static Operation * getOwnerOfValue (Value value)
static std::optional< int64_t > getConstantIntValue (OpFoldResult ofr)
If ofr is a constant integer or an IntegerAttr, return the integer.
static void assertValidValueDim (Value value, std::optional< int64_t > dim)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "value-bounds-op-interface"
Definition at line 21 of file ValueBoundsOpInterface.cpp.
Function Documentation
assertValidValueDim()
void assertValidValueDim (Value value, std::optional< int64_t > dim) static
Definition at line 167 of file ValueBoundsOpInterface.cpp.
References mlir::Value::getType(), and mlir::Type::isIndex().
Referenced by mlir::ValueBoundsConstraintSet::computeConstantDelta(), mlir::ValueBoundsConstraintSet::getExpr(), mlir::ValueBoundsConstraintSet::getPos(), mlir::ValueBoundsConstraintSet::insert(), mlir::ValueBoundsConstraintSet::BoundBuilder::operator<(), mlir::ValueBoundsConstraintSet::BoundBuilder::operator==(), mlir::ValueBoundsConstraintSet::BoundBuilder::operator>=(), mlir::ValueBoundsConstraintSet::BoundBuilder::operator[](), and mlir::ValueBoundsConstraintSet::populateConstraints().
getConstantIntValue()
std::optional< int64_t > getConstantIntValue (OpFoldResult ofr) static
If ofr is a constant integer or an IntegerAttr, return the integer.
Definition at line 64 of file ValueBoundsOpInterface.cpp.
References mlir::m_ConstantInt(), and mlir::matchPattern().
getOwnerOfValue()
Operation * getOwnerOfValue (Value value) static
Definition at line 31 of file ValueBoundsOpInterface.cpp.
References mlir::Value::getDefiningOp(), and mlir::Operation::getParentOp().
Referenced by mlir::ValueBoundsConstraintSet::dump(), mlir::ValueBoundsConstraintSet::getPos(), mlir::ValueBoundsConstraintSet::insert(), mlir::bufferization::OneShotAnalysisState::isWritable(), and mlir::ValueBoundsConstraintSet::processWorklist().