MLIR: lib/Dialect/SparseTensor/IR/Detail/Var.cpp File Reference
Var.cpp File Reference
#include "Var.h"
#include "DimLvlMap.h"
Functions
static LLVM_ATTRIBUTE_UNUSED llvm::SMLoc minSMLoc (AsmParser &parser, llvm::SMLoc sm1, llvm::SMLoc sm2)
Helper function for assertUsageConsistency to better handle SMLoc mismatches.
bool isInternalConsistent (VarEnv const &env, VarInfo::ID id, StringRef name)
bool isUsageConsistent (VarEnv const &env, VarInfo::ID id, llvm::SMLoc loc, VarKind vk)
Variables
static constexpr const VarKind everyVarKind []
For use in foreach loops.
Function Documentation
isInternalConsistent()
bool isInternalConsistent (VarEnv const & env, VarInfo::ID id, StringRef name)
Definition at line 159 of file Var.cpp.
References mlir::sparse_tensor::ir_detail::VarEnv::access().
Referenced by mlir::sparse_tensor::ir_detail::VarEnv::create(), and mlir::sparse_tensor::ir_detail::VarEnv::lookup().
isUsageConsistent()
bool isUsageConsistent (VarEnv const & env, VarInfo::ID id, llvm::SMLoc loc, VarKind vk)
Definition at line 164 of file Var.cpp.
References mlir::sparse_tensor::ir_detail::VarEnv::access(), and mlir::sparse_tensor::ir_detail::VarInfo::getKind().
Referenced by mlir::sparse_tensor::ir_detail::VarEnv::create(), and mlir::sparse_tensor::ir_detail::VarEnv::lookupOrCreate().
minSMLoc()
static LLVM_ATTRIBUTE_UNUSED llvm::SMLoc minSMLoc (AsmParser & parser, llvm::SMLoc sm1, llvm::SMLoc sm2) static
Helper function for assertUsageConsistency to better handle SMLoc mismatches.
Definition at line 147 of file Var.cpp.
References mlir::AsmParser::getEncodedSourceLoc().
Variable Documentation
everyVarKind
constexpr const VarKind everyVarKind[] static constexpr
Initial value:
= {
    VarKind::Dimension, VarKind::Symbol, VarKind::Level}
For use in foreach loops.
Definition at line 21 of file Var.cpp.
Referenced by mlir::sparse_tensor::ir_detail::VarSet::add(), mlir::sparse_tensor::ir_detail::Ranks::operator==(), and mlir::sparse_tensor::ir_detail::VarSet::VarSet().