MLIR: lib/Conversion/VectorToROCDL/VectorToROCDL.cpp File Reference
VectorToROCDL.cpp File Reference
#include "mlir/Conversion/VectorToROCDL/VectorToROCDL.h"
#include "../PassDetail.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter &rewriter, ArrayRef< Value > operands, LLVMTypeConverter &typeConverter, Location loc, TransferReadOp xferOp, Type &vecTy, Value &dwordConfig, Value &vindex, Value &offsetSizeInBytes, Value &glc, Value &slc)
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter &rewriter, ArrayRef< Value > operands, LLVMTypeConverter &typeConverter, Location loc, TransferWriteOp xferOp, Type &vecTy, Value &dwordConfig, Value &vindex, Value &offsetSizeInBytes, Value &glc, Value &slc)
Function Documentation
replaceTransferOpWithMubuf() [1/2]
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter & rewriter, ArrayRef< Value > operands, LLVMTypeConverter & typeConverter, Location loc, TransferReadOp xferOp, Type & vecTy, Value & dwordConfig, Value & vindex, Value & offsetSizeInBytes, Value & glc, Value & slc) static
Definition at line 32 of file VectorToROCDL.cpp.
References mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by replaceTransferOpWithMubuf().
replaceTransferOpWithMubuf() [2/2]
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter & rewriter, ArrayRef< Value > operands, LLVMTypeConverter & typeConverter, Location loc, TransferWriteOp xferOp, Type & vecTy, Value & dwordConfig, Value & vindex, Value & offsetSizeInBytes, Value & glc, Value & slc) static
Definition at line 42 of file VectorToROCDL.cpp.
References mlir::OpBuilder::create(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::LLVM::getFixedVectorType(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::LLVM::getVectorNumElements(), loc, mlir::RewriterBase::replaceOpWithNewOp(), replaceTransferOpWithMubuf(), rewriter, and mlir::success().