MLIR: lib/Dialect/Vector/Transforms/VectorLinearize.cpp File Reference
VectorLinearize.cpp File Reference
#include "mlir/Dialect/UB/IR/UBOps.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorRewritePatterns.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/ArrayRef.h"
#include <cstdint>
#include <numeric>
#include <optional>
Functions
static FailureOr< Attribute > linearizeConstAttr (Location loc, ConversionPatternRewriter &rewriter, VectorType resType, Attribute value)
static bool isLinearizable (Operation *op)
This method defines the set of operations that are linearizable, and hence that are considered illegal for the conversion target.
Function Documentation
isLinearizable()
static bool isLinearizable (Operation * op) static
This method defines the set of operations that are linearizable, and hence that are considered illegal for the conversion target.
Definition at line 769 of file VectorLinearize.cpp.
References mlir::Operation::getDialect(), mlir::Dialect::getNamespace(), and mlir::Operation::hasTrait().
linearizeConstAttr()
static FailureOr<Attribute> linearizeConstAttr (Location loc, ConversionPatternRewriter & rewriter, VectorType resType, Attribute value) static
Definition at line 30 of file VectorLinearize.cpp.
References mlir::RewriterBase::notifyMatchFailure().