MLIR: lib/Dialect/Vector/Transforms/VectorTransferOpTransforms.cpp File Reference
VectorTransferOpTransforms.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/DebugLog.h"
Macros
#define DEBUG_TYPE "vector-transfer-opt"
Functions
static Operation * findAncestorOpInRegion (Region *region, Operation *op)
Return the ancestor op in the region or nullptr if the region is not an ancestor of the op.
static SmallVector< int64_t > getReducedShape (ArrayRef< OpFoldResult > mixedSizes)
Converts OpFoldResults to int64_t shape without unit dims.
static MemRefType dropUnitDims (MemRefType inputType, ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides)
Drops unit dimensions from the input MemRefType.
static Value rankReducingSubviewDroppingUnitDims (PatternRewriter &rewriter, mlir::Location loc, Value input)
Creates a rank-reducing memref.subview op that drops unit dims from its input.
static int getReducedRank (ArrayRef< int64_t > shape)
Returns the number of dims that aren't unit dims.
static VectorType trimNonScalableUnitDims (VectorType oldType)
Trims non-scalable one dimensions from oldType and returns the result type.
static FailureOr< Value > createMaskDropNonScalableUnitDims (PatternRewriter &rewriter, Location loc, vector::CreateMaskOp op)
static Value collapseInnerDims (PatternRewriter &rewriter, mlir::Location loc, Value input, int64_t firstDimToCollapse)
Creates a memref.collapse_shape collapsing all inner dimensions of the input starting at firstDimToCollapse.
static SmallVector< Value > getCollapsedIndices (RewriterBase &rewriter, Location loc, ArrayRef< int64_t > shape, ValueRange indices, int64_t firstDimToCollapse)
Returns the new indices that collapses the inner dimensions starting from the firstDimToCollapse dimension.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-transfer-opt"
Definition at line 30 of file VectorTransferOpTransforms.cpp.
Function Documentation
collapseInnerDims()
static Value collapseInnerDims (PatternRewriter & rewriter, mlir::Location loc, Value input, int64_t firstDimToCollapse) static
Creates a memref.collapse_shape collapsing all inner dimensions of the input starting at firstDimToCollapse.
Definition at line 505 of file VectorTransferOpTransforms.cpp.
References mlir::Value::getType().
createMaskDropNonScalableUnitDims()
static FailureOr<Value> createMaskDropNonScalableUnitDims (PatternRewriter & rewriter, Location loc, vector::CreateMaskOp op) static
Definition at line 308 of file VectorTransferOpTransforms.cpp.
References trimNonScalableUnitDims().
dropUnitDims()
static MemRefType dropUnitDims (MemRefType inputType, ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides) static
Drops unit dimensions from the input MemRefType.
Definition at line 257 of file VectorTransferOpTransforms.cpp.
References getReducedShape().
Referenced by rankReducingSubviewDroppingUnitDims().
findAncestorOpInRegion()
static Operation* findAncestorOpInRegion (Region * region, Operation * op) static
Return the ancestor op in the region or nullptr if the region is not an ancestor of the op.
Definition at line 36 of file VectorTransferOpTransforms.cpp.
References mlir::Operation::getParentOp(), and mlir::Operation::getParentRegion().
Referenced by mlir::applyOpPatternsGreedily().
getCollapsedIndices()
static SmallVector<Value> getCollapsedIndices (RewriterBase & rewriter, Location loc, ArrayRef< int64_t > shape, ValueRange indices, int64_t firstDimToCollapse) static
Returns the new indices that collapses the inner dimensions starting from the firstDimToCollapse dimension.
Definition at line 522 of file VectorTransferOpTransforms.cpp.
References mlir::computeLinearIndex(), mlir::computeSuffixProduct(), mlir::arith::ConstantIndexOp::create(), mlir::getConstantIntValue(), mlir::isZeroInteger(), and mlir::affine::makeComposedFoldedAffineApply().
getReducedRank()
static int getReducedRank (ArrayRef< int64_t > shape) static
Returns the number of dims that aren't unit dims.
Definition at line 288 of file VectorTransferOpTransforms.cpp.
getReducedShape()
static SmallVector<int64_t> getReducedShape (ArrayRef< OpFoldResult > mixedSizes) static
Converts OpFoldResults to int64_t shape without unit dims.
Definition at line 240 of file VectorTransferOpTransforms.cpp.
Referenced by dropUnitDims().
rankReducingSubviewDroppingUnitDims()
static Value rankReducingSubviewDroppingUnitDims (PatternRewriter & rewriter, mlir::Location loc, Value input) static
Creates a rank-reducing memref.subview op that drops unit dims from its input.
Or just returns the input if it was already without unit dims.
Definition at line 269 of file VectorTransferOpTransforms.cpp.
References dropUnitDims(), mlir::Builder::getIndexAttr(), mlir::memref::getMixedSizes(), and mlir::Value::getType().
trimNonScalableUnitDims()
static VectorType trimNonScalableUnitDims (VectorType oldType) static
Trims non-scalable one dimensions from oldType and returns the result type.
Definition at line 294 of file VectorTransferOpTransforms.cpp.
References mlir::detail::enumerate(), and mlir::get().
Referenced by createMaskDropNonScalableUnitDims().