MLIR: lib/Dialect/X86/Transforms/VectorContractBF16ToFMA.cpp File Reference
VectorContractBF16ToFMA.cpp File Reference
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/Dialect/X86/Transforms.h"
#include "mlir/Dialect/X86/Utils/X86Utils.h"
#include "mlir/Dialect/X86/X86Dialect.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/Casting.h"
Classes
struct VectorContractBF16ToFMA
Functions
static bool validateVectorContractOperands (Value prodOp, bool isVnni)
static SmallVector< memref::SubViewOp > getSubviewFromVectorInput (Location loc, PatternRewriter &rewriter, Value prodOp, ArrayRef< int64_t > nonUnitDimShape, bool isUnitDim, bool isVNNI)
Function Documentation
getSubviewFromVectorInput()
SmallVector< memref::SubViewOp > getSubviewFromVectorInput (Location loc, PatternRewriter & rewriter, Value prodOp, ArrayRef< int64_t > nonUnitDimShape, bool isUnitDim, bool isVNNI) static
Definition at line 100 of file VectorContractBF16ToFMA.cpp.
References mlir::Value::getDefiningOp(), and mlir::Builder::getIndexAttr().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().
validateVectorContractOperands()
bool validateVectorContractOperands (Value prodOp, bool isVnni) static
Definition at line 33 of file VectorContractBF16ToFMA.cpp.
References mlir::getConstantIntValue(), mlir::Value::getDefiningOp(), and mlir::Value::getType().
Referenced by VectorContractBF16ToFMA::matchAndRewrite().