MLIR: lib/IR/Verifier.cpp File Reference
Verifier.cpp File Reference
#include "mlir/IR/Verifier.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/RegionKindInterface.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/Regex.h"
#include <atomic>
Functions
static bool mayBeValidWithoutTerminator (Block *block)
Returns true if this block may be valid without terminator.
static void diagnoseInvalidOperandDominance (Operation &op, unsigned operandNo)
Emit an error when the specified operand of the specified operation is an invalid use because of dominance properties.
Function Documentation
diagnoseInvalidOperandDominance()
static void diagnoseInvalidOperandDominance (Operation & op, unsigned operandNo) static
Emit an error when the specified operand of the specified operation is an invalid use because of dominance properties.
Attach a note to an in-flight diagnostic that provide more information about where an op operand is defined.
Definition at line 253 of file Verifier.cpp.
References mlir::InFlightDiagnostic::attachNote(), mlir::Region::begin(), mlir::Value::cast(), diag(), mlir::Operation::emitError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Operation::getBlock(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::Operation::getNumRegions(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Block::getParent(), mlir::Block::getParentOp(), mlir::Operation::getRegions(), mlir::Operation::hasTrait(), mlir::Region::isProperAncestor(), mlir::detail::DominanceInfoBase< IsPostDom >::isReachableFromEntry(), loc, op, mlir::DominanceInfo::properlyDominates(), and mlir::success().
mayBeValidWithoutTerminator()
static bool mayBeValidWithoutTerminator (Block * block) static
Returns true if this block may be valid without terminator.
That is if:
it does not have a parent region.
Or the parent region have a single block and:
This region does not have a parent op.
Or the parent op is unregistered.
Or the parent op has the NoTerminator trait.
Definition at line 98 of file Verifier.cpp.
References mlir::Dialect::allowsUnknownOperations(), mlir::MLIRContext::allowsUnregisteredDialects(), mlir::emitError(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::Region::empty(), mlir::Block::empty(), mlir::failed(), mlir::failure(), mlir::Region::front(), mlir::OperationName::getAbstractOperation(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Operation::getContext(), mlir::OperationName::getDialect(), mlir::Region::getLoc(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Dialect::getNamespace(), mlir::Operation::getNumRegions(), mlir::Operation::getNumSuccessors(), mlir::Operation::getOperands(), mlir::Block::getParent(), mlir::Block::getParentOp(), mlir::Operation::getRegion(), mlir::Block::getSuccessors(), mlir::Graph, mlir::Block::hasNoPredecessors(), mlir::Region::hasOneBlock(), mlir::Operation::hasTrait(), mlir::Operation::isRegistered(), kind, mlir::Operation::mightHaveTrait(), op, mlir::SSACFG, and mlir::success().