MLIR: lib/Dialect/X86Vector/IR/X86VectorDialect.cpp File Reference
X86VectorDialect.cpp File Reference
#include "mlir/Dialect/X86Vector/X86VectorDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Dialect/X86Vector/X86VectorInterfaces.cpp.inc"
#include "mlir/Dialect/X86Vector/X86VectorDialect.cpp.inc"
#include "mlir/Dialect/X86Vector/X86Vector.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static SmallVector< Value > getMemrefBuffPtr (Location loc, ::mlir::TypedValue<::mlir::MemRefType > memrefVal, RewriterBase &rewriter, const LLVMTypeConverter &typeConverter)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 113 of file X86VectorDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getMemrefBuffPtr()
static SmallVector<Value> getMemrefBuffPtr (Location loc, ::mlir::TypedValue<::mlir::MemRefType > memrefVal, RewriterBase & rewriter, const LLVMTypeConverter & typeConverter) static
Definition at line 35 of file X86VectorDialect.cpp.
References mlir::MemRefDescriptor::bufferPtr(), mlir::LLVMTypeConverter::convertType(), and mlir::OpBuilder::create().